### ISSUE TITLE
Improve performance of TSI planning using bitsets

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#10014]
__Proposal:__ 

Rather than streaming and merging sets of series IDs, we could instead return bitsets up to callers, and merge those bitsets together. This would only work for local iterators and not remote ones, since they can't use series IDs.

__Current behavior:__

Planning can be considerably slower for TSI because of all the merging and filtering we have to do of values stored in binary format on disk (or mmap'd in), compared to the `inmem` index, which simply merges integers that are already on the heap.

For example, given a dataset created as follows:

```
inch -b 10000 -c 8 -t 4,863000,2 -f 2 -m 1 -p 1 -v
```

The following explain plans are produced:

**inmem***

```
> EXPLAIN ANALYZE select v0 from m0 where tag0='value1' and tag1 = 'value100000'
EXPLAIN ANALYZE
---------------
.
└── select
    ├── execution_time: 15.534µs
    ├── planning_time: 1.734161ms
    ├── total_time: 1.749695ms
    └── build_cursor
        ├── labels
        │   └── statement: SELECT v0::float FROM stress.autogen.m0 WHERE tag0::tag = 'value1' AND tag1::tag = 'value100000'
        └── iterator_scanner
            ├── labels
            │   └── auxiliary_fields: v0::float
            └── create_iterator
                ├── labels
                │   ├── cond: tag0::tag = 'value1' AND tag1::tag = 'value100000'
                │   ├── measurement: m0
                │   └── shard_id: 2
                ├── cursors_ref: 0
                ├── cursors_aux: 2
                ├── cursors_cond: 0
                ├── float_blocks_decoded: 2
                ├── float_blocks_size_bytes: 68
                ├── integer_blocks_decoded: 0
                ├── integer_blocks_size_bytes: 0
                ├── unsigned_blocks_decoded: 0
                ├── unsigned_blocks_size_bytes: 0
                ├── string_blocks_decoded: 0
                ├── string_blocks_size_bytes: 0
                ├── boolean_blocks_decoded: 0
                ├── boolean_blocks_size_bytes: 0
                └── planning_time: 1.602931ms
```

**tsi1**

```
> EXPLAIN ANALYZE select v0 from m0 where tag0='value1' and tag1 = 'value100000'
EXPLAIN ANALYZE
---------------
.
└── select
    ├── execution_time: 12.791µs
    ├── planning_time: 93.465474ms
    ├── total_time: 93.478265ms
    └── build_cursor
        ├── labels
        │   └── statement: SELECT v0::float FROM stress.autogen.m0 WHERE tag0::tag = 'value1' AND tag1::tag = 'value100000'
        └── iterator_scanner
            ├── labels
            │   └── auxiliary_fields: v0::float
            └── create_iterator
                ├── labels
                │   ├── cond: tag0::tag = 'value1' AND tag1::tag = 'value100000'
                │   ├── measurement: m0
                │   └── shard_id: 2
                ├── cursors_ref: 0
                ├── cursors_aux: 2
                ├── cursors_cond: 0
                ├── float_blocks_decoded: 2
                ├── float_blocks_size_bytes: 68
                ├── integer_blocks_decoded: 0
                ├── integer_blocks_size_bytes: 0
                ├── unsigned_blocks_decoded: 0
                ├── unsigned_blocks_size_bytes: 0
                ├── string_blocks_decoded: 0
                ├── string_blocks_size_bytes: 0
                ├── boolean_blocks_decoded: 0
                ├── boolean_blocks_size_bytes: 0
                └── planning_time: 93.251198ms
```

You can get some good profiles of what's going on using [qprof](https://github.com/influxdata/qprof).

For example this works well:

```
qprof -c 4 -db stress -t 90s "select v0 from m0 where tag0='value1' and tag1 = 'value100000'"
```

You can see in the attached flame graph that all the time is spent merging and filtering. Merging is expensive because we have to decode the series ids from binary to `uint64`.

![screen shot 2018-06-28 at 17 15 22](https://user-images.githubusercontent.com/501993/42046942-e267e538-7af6-11e8-928c-33d57018e32f.png)
 

__Desired behavior:__

Planning performance using the `tsi1` index to be closer to the `inmem` index performance.

__Use case:__ 

This is important because for queries with short execution time, e.g., dashboard style queries for recent data, the planning time will dominate the query time. These are a significant proportion of queries used with InfluxDB.

**Comment by e-dard** [comment]
When re-running this analysis with #10044 and #10048, we're still not fully benefitting from the bitsets because we have to still drain the `rawSeriesIDIterator` each time we plan a query involving those series ids. 

Whilst we have some bitset caching in the `LogFile` from #10048, we need more at the `FileSet` level. The proposal is that we next begin caching per-measurement bitsets at the `FileSet` level, and we update them with each write and delete. 

When the bitsets are invalidated then we would rebuild them, the next time we need the series ids for the given measurement. We could maintain an LRU of these bitsets to keep heap usage down.

The current hotspot is as follows:

![screen shot 2018-07-09 at 15 46 49](https://user-images.githubusercontent.com/501993/42458321-973cdb42-8391-11e8-98be-31a30c167012.png)

**Comment by migue** [comment]
Hello all,

Has been there any improvements in this area? I've been hit by this issue since I moved from the in-memory index to the new TSI.

I have a few queries asking for a one-day window with a simple group by; something like this:

```
explain analyze select mean(span_duration), sum(num_executions),sum(technical_errors) from "one_min_aggregation"."span-metric-set-type" where time >= now() - 24h and "monitoredResource._id"='my-value' group by serviceRegistryId
```
And the planning time cleary dominates the total time

```
EXPLAIN ANALYZE
---------------
.
└── select
    ├── execution_time: 1.076871701s
    ├── planning_time: 12.566906086s
    ├── total_time: 13.643777787s
    └── build_cursor
        ├── labels
        │   └── statement: SELECT mean(span_duration::float), sum(num_executions::float), sum(technical_errors) FROM "mydatabase"."one_min_aggregation"."span-metric-set-type" WHERE "monitoredResource._id"::tag = 'my-value' GROUP BY serviceRegistryId
        ├── iterator_scanner
        │   ├── labels
        │   │   └── expr: sum(num_executions::float)
        │   └── create_iterator
        │       ├── labels
        │       │   ├── cond: "monitoredResource._id"::tag = 'my-value'
        │       │   ├── measurement: span-metric-set-type
        │       │   └── shard_id: 6417
        │       ├── cursors_ref: 257069
        │       ├── cursors_aux: 0
        │       ├── cursors_cond: 0
        │       ├── float_blocks_decoded: 816508
        │       ├── float_blocks_size_bytes: 117719365
        │       ├── integer_blocks_decoded: 0
        │       ├── integer_blocks_size_bytes: 0
        │       ├── unsigned_blocks_decoded: 0
        │       ├── unsigned_blocks_size_bytes: 0
        │       ├── string_blocks_decoded: 0
        │       ├── string_blocks_size_bytes: 0
        │       ├── boolean_blocks_decoded: 0
        │       ├── boolean_blocks_size_bytes: 0
        │       └── planning_time: 6.057418098s
        └── iterator_scanner
            ├── labels
            │   └── expr: mean(span_duration::float)
            └── create_iterator
                ├── labels
                │   ├── cond: "monitoredResource._id"::tag = 'my-value'
                │   ├── measurement: span-metric-set-type
                │   └── shard_id: 6417
                ├── cursors_ref: 257073
                ├── cursors_aux: 0
                ├── cursors_cond: 0
                ├── float_blocks_decoded: 816447
                ├── float_blocks_size_bytes: 219967824
                ├── integer_blocks_decoded: 0
                ├── integer_blocks_size_bytes: 0
                ├── unsigned_blocks_decoded: 0
                ├── unsigned_blocks_size_bytes: 0
                ├── string_blocks_decoded: 0
                ├── string_blocks_size_bytes: 0
                ├── boolean_blocks_decoded: 0
                ├── boolean_blocks_size_bytes: 0
                └── planning_time: 6.509171495s
```
I would be willing to help to improve this area if there's something where I could really help.

Thanks a lot!

**Comment by e-dard** [comment]
@migue Hi!

Do you think you could possibly run the `qprof` tool to help us get some profiles of this behaviour? The tool is [available here](https://github.com/influxdata/qprof). We don't have any releases available at the moment but we could provide a binary if you can't/don't want to build it yourself. 

You would run something like:

```
$ qprof -db mydb -host http://example.com:8086 -t 5m "select mean(span_duration), sum(num_executions),sum(technical_errors) from \"one_min_aggregation\".\"span-metric-set-type\" where time >= now() - 24h and \"monitoredResource._id\"='my-value' group by serviceRegistryId"
```

That would run your above query repeatedly for 5 minutes. It would help us understand where in the TSI index the performance issues are.

An archive will be produced that you can put on this issue, or given it may contain sensitive information about your system you can email to me - `edd@database_name.com`. Cheers!

**Comment by migue** [comment]
Hello @e-dard ,

I will try to give it a try later this week and will update this issue once I have the results are available.

Thanks a lot!

Migue

**Comment by migue** [comment]
Hello @e-dard ,

Apologies for the delay. I've sent you an email with the results of the `qprof` executions.

Let me know if I can help.

Migue

**Comment by e-dard** [comment]
This issue was generally resolved with https://github.com/influxdata/influxdb/pull/10234, which was part of the 1.7 release.
