### ISSUE TITLE
HOW TO : Inserting timestamp key values

### ISSUE THREAD

**Issue by mrafeeq** [influxdata/influxdb#10011]
I have a event, and i want to store the date time the event happened as a timestamp, currently(v1.5) the key values only can be floats, integers, strings, or Booleans

usecase : to store start time , end time of a event, one of these can go as time, but how to store the other one

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.
