### ISSUE TITLE
Debugging Crashing/Restarting InfluxDb Being run Windows Service

### ISSUE THREAD

**Issue by JLorch** [influxdata/influxdb#10010]
I have a situation where InfluxDb sometimes will crash/restart and the entries in the Windows Event Log is not enought to debug the issue.

I have problems enabling logging of InfluxDb when running InfluxDb on Windows as a service (through nssm). I have succeded in enabling HTTP request logging by setting [access-log-path = “/test/access.log”] in influxdb.conf. However I cannot get the general InfluxDb logging to be written to file.

Do any of you have any advise on how to achieve this?

**Comment by e-dard** [comment]
Hi @JLorch we need a lot more information to triage this issue. If you're unable to get that information, e.g., logs and so on, then possibly asking on the InfluxData community site: https://community.influxdata.com might get you the help you need.

Thanks.
