### ISSUE TITLE
tsi inverted index may lose index data when server crash

### ISSUE THREAD

**Issue by huhue** [influxdata/influxdb#10027]
__System info:__ [InfluxDB 1.5, Darwin Kernel Version 16.7.0]

__Steps to reproduce:__

1. create new series 
2. series data persist in tsl file
3. tsl log file use bufio.Writer module, call bufio.Writer.Write() and bufio.Writer will buffer the series index data, then if server crash, will lose up to 4KB bytes data. 

__Additional info:__ [Include gist of relevant config, logs, etc.]

I think need do bufio.Writer.Flush() in every write case. 
Strictly speaking, I think may need do f.Sync() like wal writer.

**Comment by e-dard** [comment]
Thanks for the issue and related PR @huhue!

This is has already been fixed in #9982, and will be part of the 1.6 release.
