### ISSUE TITLE
Response time changes for the same query

### ISSUE THREAD

**Issue by arbabkhalil** [influxdata/influxdb#10025]
__System info:__
InfluxDB version 1.5.3
OS: CentOS 7
kernel version: (3.10.0-862.3.3.el7.x86_64)
2 VCPU cores
7.5 GB RAM.
__Steps to reproduce:__
I have a table with 85 fields and one tag, tag is device id where I have 2000 devices means 2000 series.
15 fields and tag are of String type and other are of float type.There are total of 79 million packets in db.
1. run the following queries:
`SELECT max(float_value) FROM may_data WHERE time >= 1525132800000000000 AND time < 1527811200000000000 AND float_value >= 0 AND float_value <= 9999 GROUP BY dev_id my_data
`
`SELECT min(float_value) FROM may_data WHERE time >= 1525132800000000000 AND time < 1527811200000000000 AND float_value >= 0 AND float_value <= 9999 GROUP BY dev_id my_data
`
`SELECT count(float_value) FROM may_data WHERE time >= 1525132800000000000 AND time < 1527811200000000000 AND float_value >= 0 AND float_value <= 9999 GROUP BY dev_id my_data
`
the response time I got was around 160 seconds for each.
2. Now run these queries repeatedly 6 to 8 times and the response time becomes 1200 to 1600 seconds.
3. Leave the db running without any query for almost 1.5 to 2 hours and again time becomes normal but after doing the above queries repeatedly, it become 1200 to 1600 seconds.

__Expected behavior:__ Every time the query response time should be around 160 seconds.

__Actual behavior:__ Query response time becomes 1200 to 1600 seconds after running above mentioned queries repeatedly.

__Additional info:__
[iostat.txt](https://github.com/influxdata/influxdb/files/2157807/iostat.txt)
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/2157808/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/influxdb/files/2157809/vars.txt)

**Comment by e-dard** [comment]
@arbabkhalil thanks for the issue.

 - which index type are you using?
 - did you capture the `profiles.tar.gz` _while_ you were executing one of these problematic queries?

**Comment by arbabkhalil** [comment]
I am using time index and time is ingested with point not the ingestion timestamp, I am using python-influxdb to ingest data.  
Yes captured profiles.tar.gz while one of these problematic query was running.
I am using Google Cloud Platform and instance type is n1-standard-2. No other workload is running on this vm. Even cpu utilization is very low at that time.
