### ISSUE TITLE
cannot reload configuration file from /etc/influxdb/influxdb.conf

### ISSUE THREAD

**Issue by stuart3501** [influxdata/influxdb#10026]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
1.oracle linux 7.4( disable firewalld,  disable selinux)
2.InfluxDB version: 1.5.2
3.

__Steps to reproduce:__

1. [First Step]
add yum.repo
[influxdb]
name = InfluxDB Repository - RHEL \$releasever
baseurl = https://repos.influxdata.com/centos/\$releasever/\$basearch/stable
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdb.key
2. [Second Step]
yum install influxdb
3. [and so on...]
change the influxdb.conf as below:
4. then execute systemctl restart influxdb.service
5.execute command netstat -ntlp

__Expected behavior:__ [What you expected to happen]
1.influxdb should loged in /var/log/influxdb/
2.influxdb should enable http port : 8083
3.influxdb should enable graphite port: 2003
__Actual behavior:__ [What actually happened]
only port: 8086 and port : 8088 exist.
and I cannot get the log 
__Additional info:__ [Include gist of relevant config, logs, etc.]

the influxdb.conf I use is below:
[meta]
  # Where the metadata/raft database is stored
  dir = "/var/lib/influxdb/meta"
  hostname = "tick.localdomain"
  bind-address = ":8088"
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"
  
  logging-enabled = true

[data]
  # The directory where the TSM storage engine stores TSM files.
  dir = "/var/lib/influxdb/data"

  # The directory where the TSM storage engine stores WAL files.
  wal-dir = "/var/lib/influxdb/wal"
  wal-enable-logging = true

  trace-logging-enabled = true
[admin]
  enabled = true
  bind-address = ":8083"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

[logging]
   format = "auto"
   level = "info"
   suppress-logo = false
[[graphite]]
  # Determines whether the graphite endpoint is enabled.
   enabled = true
   database = "jmeter"
   retention-policy = ""
   bind-address = ":2003"
   protocol = "tcp"
   consistency-level = "one"
   batch-size = 5000
   batch-pending = 10
   batch-timeout = "1s"
   udp-read-buffer = 0
   separator = "."

**Comment by NocturnalShadow** [comment]
In your configuration you are disabling Graphite with `enabled = false`.

**Comment by e-dard** [comment]
@stuart3501 the admin interface was deprecated in `v1.1`, and finally removed in `v1.3`
