### ISSUE TITLE
docs: add detailed info how to use influx_inspect to check if I use TSM or TSI

### ISSUE THREAD

**Issue by akavel** [influxdata/influxdb#10031]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

influxdb 1.5.4

__Steps to reproduce:__

```shell
$ docker run --name mytest -d influxdb:1.5.4 
cb4256853c00c6f389af44fb3a27ce09fe72f8c02f7a2a39b986b0a90839549f
$ docker exec mytest influx_inspect report -help
Displays shard level report.

Usage: influx_inspect report [flags]

    -pattern <pattern>
            Include only files matching a pattern.
    -exact
            Report exact cardinality counts instead of estimates.  Note: this can use a lot of memory.
            Defaults to "false".
    -detailed
            Report detailed cardinality estimates.
            Defaults to "false".

$ docker exec mytest influx_inspect report
report: lstat : no such file or directory
```

__Expected behavior:__ [What you expected to happen]

Some info about existing database contents, showing me whether I use TSM or TSI. The `--help` contents for `influx_inspect` should explain how to actually use the command to get some correct result, possibly by showing example command line.

__Actual behavior:__ [What actually happened]

Trying to use `influx_inspect report` fails with unintelligible error. Similarly for `influx_inspect dumptsm`, I have no idea how to actually use it after reading the `--help`. I tried running both of them with various options, but never managed to get any meaningful info.

__Additional info:__ [Include gist of relevant config, logs, etc.]

The influxdb 1.5 [upgrade guide](https://docs.influxdata.com/influxdb/v1.5/administration/upgrading/) only repeatedly says "use `influx_inspect buildtsi`"; but the docs for the tool are super sparse and cryptic. Anyway, I can't find out a way how to call `influx_inspect` to check whether I have TSM or TSI indexes *before* running the upgrade (buildtsi), and to verify whether the upgrade worked successfully *after* the upgrade. Without being able to check this, it doesn't make much sense to me to even attempt the upgrade, as I don't know how to check if the call succeeded.

**Comment by e-dard** [comment]
@akavel we have a dedicated docs repo: https://github.com/influxdata/docs.influxdata.com; I think that this issue should be filed over there. /cc @stevebang

**Comment by stevebang** [comment]
This issue was moved to influxdata/docs.influxdata.com#1703
