### ISSUE TITLE
Percentile function is broken when using with time grouping

### ISSUE THREAD

**Issue by ArnaudLevaufre** [influxdata/influxdb#10038]
Hello,

I have an issue that is quite limiting for my use case where the percentile function doesn't return any point when grouping by time. Here is the description of the issue following your standard template.

__System info:__

Influxdb 1.5 running inside docker on linux.

__Steps to reproduce:__

1. Prepare a database with whatever values you want, each one separated by 719 seconds (~12minutes)
2. Make a query of any percentile above 25 while gouping by 15 minutes windows.
3. Make a query of any percentile bellow 25 while gouping by 15 minutes windows.

__Expected behavior:__

I expect to have the percentile I requested at step 2 and 3.

__Actual behavior:__ 

There is no result at the third step.

__Additional info:__

It's really interesting to play with the percentile value and the grouping window length.

Let's say i need to compute at least the fifth percentile or above over time. Trying 109 minutes will give me some results when the count of points in that time windows is above 10.

If I need to compute the 10th percentile or above over time I only have the first values for time windows above 48 minutes when the number of point per time window is equal to 5.

Proceding the other way around, if I set the time window so it only select one value at a time, I can compute all percentiles above 50 and can't compute anything under 50.

While I didn't check for the validity of the values, it's clear that it's broken as the behavior is not consistent.

It's also probably related to #9741 

For reference here is a list of queries I used while debuging
```
select percentile(value, 5), count(value) from anl where time >= '2018-01-01T00:00:00Z' and time < '2018-02-01T00:00:00Z' group by time(108m);
select percentile(value, 10), count(value) from anl where time >= '2018-01-01T00:00:00Z' and time < '2018-02-01T00:00:00Z' group by time(48m);
select percentile(value, 100), count(value) from anl where time >= '2018-01-01T00:00:00Z' and time < '2018-02-01T00:00:00Z' group by time(1m);
```
The presence/abscence of result can be verified by removing the `count(value)` in the request.

**Comment by CptTZ** [comment]
We are experiencing this issue too, 25 seems to be a threshold.

**Comment by bret** [comment]
We are seeing this issue too, but the notes here have given us a workaround
