### ISSUE TITLE
Logging level ignored

### ISSUE THREAD

**Issue by mididix** [influxdata/influxdb#10040]
Dear influx,

It looks like influxdb-1.5.4-1.x86_64 is completely ignoring the Logging level setting. 

If I set "error" or "warn" level, influx still logs all the queries (corresponding to the "info" level).

This behaviour is seen both when logging in syslog and when logging to standard output, when I launch influx manually.

I know my Logging section is indeed read by influx as when I toggle the "suppress-logo" switch it acts as intended.

I run it in a RHEL 7.4, kernel 3.10.0-693.17.1.el7.x86_64.

Thanks

**Comment by JKJameson** [comment]
This issue still exists in 1.7.9-r0 on Alpine Linux.
I can confirm the behaviour that mididix is correct. The "suppress-logo" option works, but it is not possible to suppress info messages.

**Comment by osresearch** [comment]
1.8.4 continues to output all HTTP queries, regardless of the log level.
