### ISSUE TITLE
Get size on disk per measurements

### ISSUE THREAD

**Issue by thomasboussekey** [influxdata/influxdb#10059]
__Proposal:__  Provide the size on disk per MEASUREMENT

__Current behavior:__ Unable to retrieve this information

__Desired behavior:__ Have an administrative command to list the measurement and their size

__Use case:__ Diagnose the size increase, realize capacity planning for the DB

Requests may be closed if we're not actively planning to work on them.

**Comment by jcmartins** [comment]
+1
