### ISSUE TITLE
'count' difference between SQLs using group by time or not 

### ISSUE THREAD

**Issue by alexandnpu** [influxdata/influxdb#10055]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

influxdb: 1.5.4
os: CentOS Linux release 7.2.1511 (Core)
kernel:3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

__Steps to reproduce:__

```
SELECT count("http_version") FROM "three_days"."production_nginx_access_log" WHERE time >= now() - 1s
name: production_nginx_access_log
time                count
----                -----
1531104466490448482 12463
SELECT count("http_version") FROM "three_days"."production_nginx_access_log" WHERE time >= now() - 1s group by time(100ms) fill(0);
name: production_nginx_access_log
time                count
----                -----
1531104479900000000 29
1531104480000000000 264
1531104480100000000 285
1531104480200000000 277
1531104480300000000 290
1531104480400000000 297
1531104480500000000 284
1531104480600000000 275
1531104480700000000 293
1531104480800000000 290
1531104480900000000 246
```

__Expected behavior:__ [What you expected to happen]
What you can see that the difference between the two sqls above is using group by or not.
What I epected is that the first count is nearly the same as the sum of second output.
But it turns out that the two are too far away.

**Comment by iwittkau** [comment]
You can not assume that you are accessing the same data if you use `now()`. The ungrouped timestamp `1531104466490448482` does not overlap with any of the grouped ones. Data may change between your queries.
