### ISSUE TITLE
Regression in query regex handling (panic)

### ISSUE THREAD

**Issue by dswarbrick** [influxdata/influxdb#10069]
__System info:__ InfluxDB 1.6.0, Debian stretch

__Steps to reproduce:__
With our existing data, the following query used to work without issue:
```
SELECT non_negative_derivative(mean("tx"), 1s) * 8
FROM "interface_if_octets"
WHERE ("host" =~ /^gw101[ab]-\d\./ AND "plugin_instance" =~ /^eth2\.1\d{3}$/) AND time >= now() - 5m
GROUP BY time(1m), "host"
```

__Expected behavior:__ Results returned as per previously successful operation.

__Actual behavior:__ No data shown in Grafana, InfluxDB CLI reports a panic
Since upgrading to InfluxDB 1.6.0, it fails, and a panic can be see in the `influx` CLI tool:
```
> SELECT non_negative_derivative(mean("tx"), 1s) * 8 FROM "interface_if_octets" WHERE ("host" =~ /^gw101[ab]-\d\./ AND "plugin_instance" =~ /^eth2\.1\d{3}$/) AND time >= now() - 5m GROUP BY time(1m), "host"
ERR: SELECT non_negative_derivative(mean(tx), 1s) * 8 FROM perfdb."default".interface_if_octets WHERE (host =~ /^gw101[ab]-\d\./ AND plugin_instance =~ /^eth2\.1\d{3}$/) AND time >= now() - 5m GROUP BY time(1m), host [panic:runtime error: index out of range]
```

__Additional info:__
After some experimentation looking for workarounds, it seems to be failing on the `/^eth2\.1\d{3}$/` regex, specifically the `$` end-of-line match. Removing the `$` allows the query to work.

Also, changing the regex to `/^eth2\.1\d{1,3}$/` works, however `/^eth2\.1\d{3,3}$/` panics.

The tag in the database contains values such as `eth2.1xxx`, where `x` is a digit 0-9.

This has the hallmarks of an off-by-one error when comparing to the tag value, since the `/^eth2\.1\d{3}$/` regex would eat the entire string length of the values we have for that tag.

Somewhat mysteriously, the regex `/^e[a-z0-9]+\.1\d{3}$/` works successfully.

**Comment by dswarbrick** [comment]
A `SHOW TAG VALUES` query with the same regex is successful:
```
> show tag values from interface_if_octets with key = plugin_instance where plugin_instance =~ /^eth2\.1\d{3}$/
name: interface_if_octets
key             value
---             -----
plugin_instance eth2.1101
plugin_instance eth2.1102
plugin_instance eth2.1117
plugin_instance eth2.1201
plugin_instance eth2.1202
plugin_instance eth2.1203
plugin_instance eth2.1219
plugin_instance eth2.1221
plugin_instance eth2.1301
plugin_instance eth2.1302
plugin_instance eth2.1303
plugin_instance eth2.1304
plugin_instance eth2.1305
plugin_instance eth2.1306
plugin_instance eth2.1307
plugin_instance eth2.1309
plugin_instance eth2.1311
plugin_instance eth2.1327
plugin_instance eth2.1501
```

**Comment by jsternberg** [comment]
I can confirm this would be a bug. I'll be taking a look at it to fix it.
