### ISSUE TITLE
Add instrumentation for storage read requests

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#10081]
We don't have any significant metrics around storage read requests. We need metrics for at least the following things:

 - Number of total read requests;
 - Number of active (in-flight) read requests;
 - The duration of all read requests.

In fact, we probably want to mainly duplicate the `queryExecutor` stats:

```
queriesActive queriesExecuted queriesFinished queryDurationNs
```

with something like:

```
reqActive reqExecuted reqFinished reqDurationNs
```

under a `storage_read` measurement or similar.

**Comment by liukun4515** [comment]
Is this feature reviewed by PM?

**Comment by liukun4515** [comment]
Can I implement this feature?

**Comment by e-dard** [comment]
@liukun4515 I would be open to that sure 👍

**Comment by liukun4515** [comment]
The storage read you referred to is about the grpc read method in the rpc_service?
@e-dard
