### ISSUE TITLE
Exactly 1 week of data went missing from InfluxDB

### ISSUE THREAD

**Issue by srclosson** [influxdata/influxdb#10093]
__System info:__ 
Hardware: 6 Core 2.30 GHz Intel Zeon(R)E5-2697 v4
Memory: 16 GB
OS: Windows Server 2016
Free Space: 503.45 GB

__Steps to reproduce:__
I have no idea how to reproduce this, but we have data sitting in a common database called "equipment" This includes both server data, and data about the enterprise network, as well as data from mobile equipment. 

__Expected behavior:__ 
No data get's lost

__Actual behavior:__
At around 9:00am this morning, I checked a server metrics dashboard, and went back 30 days. There were no gaps in the data. At around 11:30, I noticed a large gap from July 8th at 6:00pm all the way to July 15 at 6:00pm, so exactly 1 week of data was lost.

__Additional info:__ [Include gist of relevant config, logs, etc.]
I'm using the default config with default "autogen" retention policy

**Comment by phmaes** [comment]
Hello,

I have exactly the same behavior and have no clue why this is happening! I tried several things from cleaning index and _series folders, rebuilding tsi indices, changing parameters, different versions (starting from 1.4.2 to 1.5+) etc, it still happens. Now I use version 1.5.3-r1.

In my case, we use custom retention periods (2w, 1months, 6 months, 1y with cqs to downsample data between each rp) and the the strange thing is that it seems to correspond to the retention period's duration. But that could be a pure coincidence. 
It's like, when the engine checks for data to delete for a particular retention period, it doesn't delete the outdated shards, but the newest on a range that corresponds to the retention period's duration.

**Comment by e-dard** [comment]
@srclosson what version of InfluxDB are you running please? Has any more data been lost since you sent in this issue?

**Comment by srclosson** [comment]
@e-dard - v1.5.0

No, it's not happened since. I've looked at the windows event log, and notice that I restarted the service at 11:32am that morning, the exact time that I noticed the data missing. Exactly the issue that  @phmaes has referenced. I believe I'm seeing the same thing.

**Comment by russorat** [comment]
closing due to age. please ensure you are on the latest influxdb version and open a new issue if the problem persists.
