### ISSUE TITLE
After restarting Influxdb Data present on disk but Not queryable

### ISSUE THREAD

**Issue by singhankur** [influxdata/influxdb#10100]
```
Influxdb version 1.5.1
index-version = "tsi1"
```

Influxdb is restarted because of
**fatal error: runtime: out of memory**, this is caused by some **lvl=warn msg="Detected slow query:**

after this influxdb service is down, then after restarting the influx via command

`sudo service influxdb start
`
Data for all databases is present in data directory
but for few databases the data is not queryable,
while accessing via query. No result is returned

when the restart happens, for the problematic databases data is only present from the beginning of the day when the influxdb got restarted

**Comment by amanmj** [comment]
Facing the same issue! Some of the databases are able to load whole data , but for some databases I see data is not loaded before a particular date. And data is present on the disk for the all dates.

**Comment by phmaes** [comment]
Same here. Maybe it's linked to https://github.com/influxdata/influxdb/issues/10093 ?

**Comment by e-dard** [comment]
@singhankur @amanmj did you correctly create the TSI indexes before changing to the `tsi1` index? If you change to `index-version = "inmem"` and restart the database does your data return?

**Comment by amanmj** [comment]
@e-dard we have created it correctly as it was working fine until a couple of weeks after which this problem started to exacerbate .

**Comment by e-dard** [comment]
@singhankur  Is your data dir `/var/lib/influxdb` or `~/.influxdb`? It can't be both.

You should _not_ have influxdb running when you build the indexes. The steps should be:

1) Stop influxdb
2) `sudo runuser -l influxdb -c 'influx_inspect buildtsi -datadir ~/.influxdb/data -waldir ~/.influxdb/wal'`
3) update `/etc/influxdb/influxdb.conf with the value index-version = "tsi1"`
4) Start influxdb.

**Comment by singhankur** [comment]
@e-dard 
Followed the same steps 
But today influx restarted data loss again

**Comment by e-dard** [comment]
@singhankur can you upgrade to 1.6 and provide the logs from startup?

**Comment by PugachevDK** [comment]
Hi,

influxdb on windows
index-version = "tsi1"
after upgrade from 1.5.4 to 1.6.1 some old data not queryable while accessing via query. 
```
.\influx.exe -port 5450 -database archive -precision 'rfc3339'
> select * from flow where time < '2018-08-13T00:00:05Z' and position = 'UOS:11-19.PI813.P'
name: flow
time                         position          slice stat val
----                         --------          ----- ---- ---
2018-08-13T00:00:00.1095944Z UOS:11-19.PI813.P 0     192  22.5996246337891
2018-08-13T00:00:01.1166951Z UOS:11-19.PI813.P 0     192  22.5951080322266
2018-08-13T00:00:02.1087943Z UOS:11-19.PI813.P 0     192  22.6026992797852
2018-08-13T00:00:03.1148949Z UOS:11-19.PI813.P 0     192  22.5994567871094
2018-08-13T00:00:04.1139948Z UOS:11-19.PI813.P 0     192  22.5954513549805
```

**Comment by tarvip** [comment]
Had the same issue in 1.5.4. Upgraded to 1.6.2 and rebuilt the all indexes, data is queryable again.
