### ISSUE TITLE
Slash in query results in parser error

### ISSUE THREAD

**Issue by VanKurt** [influxdata/influxdb#10119]
I have created a database "sensors" and wrote some MQTT measurement values into it.
E.g. I have a MQTT topic "sensors/smartmeters/water" with the value 1000.
Now I would like to view these values:

> influx -username admin -password mypw
> use sensors
> select * from sensors/smartmeters/water

Results in **ERR: error parsing query: found /, expected ; at line 1, char 22**

Also putting the topic name in quotes (select * from "sensors/smartmeters/water") does not help.
How can I make this work with the slashes?

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.

`select * from "sensors/smartmeters/water"`
