### ISSUE TITLE
Prevent excessively long names for database and retention policy

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#10110]
Various InfluxDB subsystems use the database and retention policy name as an identifier for the local file system (directories). If the name exceeds the limit, the directories cannot be created and writes will fail.

**Comment by e-dard** [comment]
We'll set a hard limit of 255 characters.

**Comment by e-dard** [comment]
@stuartcarnie did this get fixed?

**Comment by stuartcarnie** [comment]
@e-dard no and I agree 255 is reasonable, given differing filename length limits identified on [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits) across various file systems.
