### ISSUE TITLE
Implement columnar encoders and TSM compaction process

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#10124]
Compactions 
===========

There are two distinct compaction processes:

1. TSM compactions, which aim to replace a set of TSM files with versions that are of increased density along with removing any tombstoned data.
2. WAL Snapshots, which write time / value data from the in-memory cache to level-0 TSM files

For reference, [issue #9981][issue_9981] implements the columnar decoders and readers. 

For the sake of simplicity, some examples will refer to the `Float` data type, however, any of the other supported data types (`Integer`, `String`, etc) could be substituted.

TSM Compactions
---------------

When merging blocks of data for a series + field, the existing compaction implementation decodes and encodes compressed data using the iterative decoder / encoder APIs. This process should be refactored to use batch-oriented APIs to improve performance. 

Starting from the top and working down, the key component responsible for merging a set of TSM files is the `tsmKeyIterator`, which is:

* an implementation of the LSM Tree merge operation
* that merges a specific set of TSM files
* in series-key order
* producing compressed and merged blocks of time and value data for each series
* in ascending time order
* for all series keys across the set of TSM files

Under certain conditions, as an optimization, blocks may not require decoding and re-encoding. This behavior can be observed for `Float` values:

https://github.com/influxdata/influxdb/blob/a85306c53e2de2fa29c43e951bd9d486bea5dc39/tsdb/engine/tsm1/compact.gen.go#L104-L118

The `KeyIterator`, defined as:

https://github.com/influxdata/influxdb/blob/1c0e49e00210cd61aa41a1c07e1ca12a3f24595e/tsdb/engine/tsm1/compact.go#L1204-L1221

is an abstraction used by the `Compactor` to read encoded TSM blocks for each series key. `tsmKeyIterator` conforms to this interface, such that it can be used by the `write` function:

https://github.com/influxdata/influxdb/blob/1c0e49e00210cd61aa41a1c07e1ca12a3f24595e/tsdb/engine/tsm1/compact.go#L1128-L1163

to produce a new set of TSM files. Note that `iter.Next()` is called for each iteration of the loop to move to the next merged block and `iter.Read()` is called to obtain the data to be encoded. The `tsmKeyIterator` provides two strategies for compacting data, per the `fast` option:

https://github.com/influxdata/influxdb/blob/1c0e49e00210cd61aa41a1c07e1ca12a3f24595e/tsdb/engine/tsm1/compact.go#L1240-L1246

The focus for the remainder of this document will be to define the requirements to implement a new `KeyIterator`, which merges a set of TSM files using the existing batch-oriented decoders and new batch-oriented encoders.

Cache Snapshots
---------------

The cache (WAL) is periodically snapshotted to generate a level-0 TSM file. A separate investigation is necessary to understand what would be required to utilize batch encoders for this process.

Tasks
-----

Similar to moving the query / read path to batch-oriented APIs, it makes sense to start from the lowest layers and work up to defining a new `KeyIterator`.

### Unit tests and benchmarks

In order to demonstrate correctness and show the scale of the performance improvements, unit tests should be replicated from the existing encoders. A [diary of benchmarks][diary] was created to keep track of the improvements to the decoders. It would be useful to maintain a similar diary for the encoders.

### Add batch encoders

Similarly to the array decoders, new implementations of the encoders should provide a single API for encoding a block of values. These encoders are responsible for encoding a single column of data, such as timestamps, floats or strings. 

An example of a batch decoder in `tsdb/engine/tsm1/batch_float.go`:

```go
func FloatBatchDecodeAll(b []byte, dst []int64) ([]int64, error)
```

which decodes the byte slice `b`, using `dst` (to potentially avoid allocations) and returning the decoded slice or an error if decoding fails. The `Float` decoder was rewritten from the iterative approach:

https://github.com/influxdata/influxdb/blob/426a9a0b8b727c1923d83fc5fb7c8eb83ebc18d0/tsdb/engine/tsm1/float.go#L142-L155

Which required the client call `Next() bool` to decode the next value and `Values() float64` to fetch the value. The improvements resulted in a single loop to decode an entire block of values, allowing a host of compiler optimizations.

A similar API for a batch encoder:

```go
func FloatArrayEncodeAll(src []int, b []byte) ([]byte, error)
```

which encodes the slice `src`, using the byte slice `b` and returns the encoded slice or an error if encoding fails.  The definition of the `FloatEncoder` can be found here:

https://github.com/influxdata/influxdb/blob/426a9a0b8b727c1923d83fc5fb7c8eb83ebc18d0/tsdb/engine/tsm1/float.go#L29-L41

#### Implement batch encoders

- [x] `IntegerArrayEncodeAll`
- [x] `UnsignedArrayEncodeAll`
- [x] `FloatArrayEncodeAll`
- [x] `StringArrayEncodeAll`
- [x] `BooleanArrayEncodeAll`
- [x] `TimestampArrayEncodeAll`

**NOTE**: `FloatBatchDecodeAll` should be renamed to `FloatArrayDecodeAll`, which follows the `Array` naming convention established throughout the remainder of the columnar work.

### Add batch block encoders

The block encoders are responsible for TSM blocks, encoding a columns of up to 1,000 timestamps and values.

An example of a `Float` block decoder:

```go
func DecodeFloatArrayBlock(block []byte, a *tsdb.FloatArray) error
```

decodes the `block` of time and value data into the `FloatArray` `a` using the block decoders. `FloatArray`, defined as:

https://github.com/influxdata/influxdb/blob/0841c51d9319a8a9fc9f13530759bbf1d0f0c23c/tsdb/arrayvalues.gen.go#L9-L12

maintains the timestamps and values as separate slices. This is knows as a Struct of Arrays layout. `FloatArray` replaces `FloatValues`:

```go
type FloatValue struct {
	unixnano int64
	value    float64
}

type FloatValues []FloatValue
```

which is an array of structs. [Struct of Arrays][AOS_and_SOA] improves cache locality and is better suited to leverage SIMD and is also the layout specified by Apache Arrow.

The `tsmKeyIterator` uses the `FloatValues#Encode` API to encode a block of values:

https://github.com/influxdata/influxdb/blob/9cd31520ec2ead0b1975689806a313ebbc092b2f/tsdb/engine/tsm1/encoding.gen.go#L454-L456

which forwards to `encodeFloatValuesBlock`:

https://github.com/influxdata/influxdb/blob/9cd31520ec2ead0b1975689806a313ebbc092b2f/tsdb/engine/tsm1/encoding.gen.go#L458-L496

The existing implementation uses the iterative encoders and therefore requires a new implementation is required to encode a `FloatArray`, leveraging the batch encoders:

```go
func encodeFloatArrayBlock(a *tsdb.FloatArray, b []byte) ([]byte, error)
```

where `a` is encoded using `b` and the result returned or an error if there was a problem encoding the data.

#### Implement batch block encoders

- [x] `encodeIntegerArrayBlock`
- [x] `encodeUnsignedArrayBlock`
- [x] `encodeFloatArrayBlock`
- [x] `encodeStringArrayBlock`
- [x] `encodeBooleanArrayBlock`

### Add `Encode` to `FloatArray`

Add a `FloatValues#Encode` method to the the code generation template `arrayvalues.gen.go.tmpl`

As noted above, the existing `FloatValues#Encode` method calls the `encodeFloatValuesBlock`. This task is to add the equivalent `FloatArray#Encode` methods, calling the new `encodeFloatArrayBlock` API.

#### Implement batch block encoders

- [x] `IntegerArray#Encode`
- [x] `UnsignedArray#Encode`
- [x] `FloatArray#Encode`
- [x] `StringArray#Encode`
- [x] `BooleanArray#Encode`

### Implement batch-oriented `KeyIterator`

This task must implement a new version of the `tsmKeyIterator` using the batch-oriented types, including `FloatArray`, `DecodeFloatArrayBlock` and `FloatArray#Encode` APIs.

- [x] `tsmKeyIterator` replacement

#### Possible optimizations

It has been observed that large compactions generate a considerable amount of garbage. This is likely due to the merging of blocks:

https://github.com/influxdata/influxdb/blob/a85306c53e2de2fa29c43e951bd9d486bea5dc39/tsdb/engine/tsm1/compact.gen.go#L162

and the later encoding of blocks:

https://github.com/influxdata/influxdb/blob/a85306c53e2de2fa29c43e951bd9d486bea5dc39/tsdb/engine/tsm1/compact.gen.go#L175

and

https://github.com/influxdata/influxdb/blob/a85306c53e2de2fa29c43e951bd9d486bea5dc39/tsdb/engine/tsm1/compact.gen.go#L193

It would be worth investigating ways of recycling memory, as this should also improve performance and reduce GC pressure.

[issue_9981]: https://github.com/influxdata/influxdb/issues/9981
[diary]: https://gist.github.com/stuartcarnie/d7982073380e6e7a8a093c0d88b57260
[AOS_and_SOA]: https://en.wikipedia.org/wiki/AOS_and_SOA

**Comment by e-dard** [comment]
Fixed via #10300.
