### ISSUE TITLE
Write multiple data points using http request

### ISSUE THREAD

**Issue by FerriadWang** [influxdata/influxdb#10127]
__System info: InfluxDB 1.6.0, Windows 10 64bit.

1. I am using the web API to write data to influxDB but I can't write multiple data points into the database.
2. Here is my code in C#:
 
`static void Main(string[] args)
        {
            Task.Run(() => MainAsync());
            Console.ReadLine();
        }

        static async Task MainAsync()
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:8086");
                
                var content = new ByteArrayContent(Encoding.ASCII.GetBytes("Measurements,device=601 value=0.8,value2=120.5,value3=60.007c\r\nMeasurements,device=601 value=0.8,value2=120.5,value3=60.008"));
            
                var result = await client.PostAsync("/write?db=data", content);
                string resultContent = await result.Content.ReadAsStringAsync();
                Console.WriteLine(resultContent);
            }
        }`
__Expected behavior: Two rows are supposed to be added into the DB.

__Actual behavior: I got the exception-->"{\"error\":\"partial write: unable to parse 'Measurements,device=601 value=0.8,value2=120.5,value3=60.007\\r': invalid number dropped=0\"}\n"

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.
