### ISSUE TITLE
Improved documentation around optimising memory usage

### ISSUE THREAD

**Issue by steveww** [influxdata/influxdb#10121]
__Proposal:__ [Description of the feature]
I see lots of posts on the internet about excessive memory usage of Influxdb and these have various anecdotal hints and tips. It would be better if the official documentation had a definitive guide on considerations for memory usage and how to optimise it.

__Current behavior:__ [What currently happens]
I am running a very small Influxdb with very little data and the memory usage just keeps growing until it either crashes, kills my system or both. Currently I have a cronjob to periodically restart Influxdb to free up memory.

Requests may be closed if we're not actively planning to work on them.

**Comment by stevebang** [comment]
This issue was moved to influxdata/docs.influxdata.com#1746
