### ISSUE TITLE
tsi indexing is not getting enabled

### ISSUE THREAD

**Issue by pranshumalviya** [influxdata/influxdb#10134]
__System info:__ [centos , influx db 1.5.4]

__Steps to reproduce:__

1. Install 1.4 
2. start data flow
3. upgrade to 1.5.4
4. change indexing to tsi in config file
5. rebuild index to use tsi
6. restart influxdb service

__Expected behavior:__ After upgrading and changing config influx should use tsi

__Actual behavior:__influx is still running on tsm, 
logs are showing engine=tsm1 
 tsm files are getting created inside data directory 

_
![screen shot 2018-07-27 at 11 25 07](https://user-images.githubusercontent.com/26020106/43303978-ca164268-918f-11e8-8e8e-804523cb39e0.png)

**Comment by e-dard** [comment]
The TSM engine runs on both indexes. Please consider upgrading to `1.6.0`, where it will now tell you directly in the logs which index shards are using.
