### ISSUE TITLE
USE DATABASE fails although database should exist

### ISSUE THREAD

**Issue by VanKurt** [influxdata/influxdb#10131]
__System info:__ 
InfluxDB 1.6, Raspberry Pi

__Steps to reproduce:__
I ran the following from the command line:

```
pi@raspberrypi:~ $ influx
Connected to http://localhost:8086 version 1.6.0
InfluxDB shell version: 1.6.0
> auth
username: admin
password: 
> SHOW DATABASES
name: databases
name
----
_internal
sensors
> USE DATABASE sensors
ERR: Database DATABASE sensors doesn't exist. Run SHOW DATABASES for a list of existing databases.
DB does not exist!
```

__Expected behavior:__ 
I would have expected the database "sensors" to be found, since it was listed before.

__Actual behavior:__
I got the error message shown above.

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.

`use sensors`
