### ISSUE TITLE
Unable to connect to influxdb configured on VM

### ISSUE THREAD

**Issue by PoojaLalit-iwiz** [influxdata/influxdb#10136]
I have configured TICK stack on Azure windows VM and I am able to run the influxdb on localhost:8086, but if am trying to access the influxdb outside the VM it is giving me an error: unable to connect to the influx, error contacting the source.
I have opened all the inbound and outbound port for the influx. Can you please help me how  should i connect to influx running on a VM

**Comment by e-dard** [comment]
# #
Hi! We try and keep GitHub Issues for actionable bug reports or feature requests. 

This question would be better posted on the InfluxData community site: https://community.influxdata.com We would be happy to help there.

Thanks.
