### ISSUE TITLE
Limiting IP access to only localhost

### ISSUE THREAD

**Issue by sibis** [influxdata/influxdb#10148]
__Proposal:__ [Description of the feature]
Please provide an option limit IP access only to localhost so that other IP cannot make HTTP calls

__Current behaviour:__ [What currently happens]
Any IP can access to query by its host IP and port. Even though we can secure it by providing auth, I don't even want other IP to call my influx

__Desired behaviour:__ [What you would like to happen]
Influx whitelists only localhost IP so that requests cannot be made from outside IP.

__Use case:__ [Why is this important (helps with prioritizing requests)]
Though we have an option to secure it with auth, just hitting the port without limit causes CPU usage. so anyone can execute the script by targeting the IP and port can achieve it

**Comment by mark-rushakoff** [comment]
If you set the bind-address to `127.0.0.1:8086` then the OS will disallow connections from external IPs.   This is the case for any software that binds to an IP address.

Does that suit your needs?

**Comment by sibis** [comment]
@mark-rushakoff Thanks mark that's exactly what I was looking for.
