### ISSUE TITLE
Ability to reset admin password

### ISSUE THREAD

**Issue by touatily** [influxdata/influxdb#10144]
__Proposal:__ Reset admin password

__Current behavior:__ If we forget admin user password we cannot reset it

__Desired behavior:__ provide a simple way to reset admin user password

__Use case:__ If we forget admin password, we can reset it and redefine it again.

**Comment by anthosz** [comment]
Hello,

Someone have a workaround for this issue?

Indeed, I lost the admin password in 1.0.2 and I cannot reset it.. If I try a dump -> restore but same issue because after restore, I need the restore password...

Best regards,
