### ISSUE TITLE
Add counter when exceeding http.max-row-limit

### ISSUE THREAD

**Issue by benbjohnson** [influxdata/influxdb#10146]
__Proposal:__ Add an internal metric to track how many requests hit the `http.max-row-limit` value.

__Current behavior:__ No metric is reported.

__Desired behavior:__ Add `1` to a counter whenever a request exceeds the row limit.

__Use case:__ Operators wish to limit the number of rows that users can query but have no visibility into the settings and how to tune them.

**Comment by liukun4515** [comment]
Can I implement this feature in the `httpd.hander`?
@benbjohnson

**Comment by liukun4515** [comment]
This feature is reveiewed by PM?
