### ISSUE TITLE
Ping Endpoint Should Respect Auth Configuration

### ISSUE THREAD

**Issue by jjathman** [influxdata/influxdb#10167]
__Proposal:__ Enable Auth for Ping Endpoint

__Current behavior:__ Currently, the /ping endpoint will return successfully when Influx is running with HTTP authentication turned on even if the client does not provide the basic auth credentials. 

__Desired behavior:__ Either make the /ping endpoint respect the HTTP auth setting or allow a configuration setting to turn this on.

__Use case:__ Spring Boot uses the Influx Java driver which currently uses the ping endpoint to determine the health of Influx. However, if authentication is enabled on Influx but the client does not have it configured or it isn't configured correctly any queries or writes will fail. Having a successful ping and health check provides a false indication that there aren't any configuration issues on the client. I would like at least for a configuration option to force the /ping endpoint to respect auth settings.

**Comment by jjathman** [comment]
I would still like to see this done. The current behavior goes against what I think a users expectations are.

**Comment by jacobmarble** [comment]
@jjathman this fix will land in 1.7.9.
