### ISSUE TITLE
Creating retention policy delete data 

### ISSUE THREAD

**Issue by touatily** [influxdata/influxdb#10162]
I created a retention policy 

> CREATE RETENTION POLICY thirty_days ON database1 DURATION 30d REPLICATION 1 DEFAULT

Then, I noticed that all data is deleted !

I expected that only data before 30 days is deleted but all data was.

**Comment by teeson** [comment]
You set the new created retention policy to be DEFAULT, 
there is no data for new created retention policy.
Check your SELECT query, use full qualification form to query as 
`SELECT value FROM "db_name"."rp_name"."metric"  WHERE ...`
