### ISSUE TITLE
DERIVATIVE for boolean or whatever to get only points with changed values

### ISSUE THREAD

**Issue by schoendort** [influxdata/influxdb#10176]
__Proposal:__ I have sensors that generates boolean data, e.g. 0,0,0,1,1,1,0,0,1,1,1. I need a option to query only the changes. so that i would get 0 (at time of the first 0), 1 (time of first 1) and so on.

__Current behavior:__ There is no way I know to do that, I tried it with the derivative-Operator but this throws a exception (no boolean supported)

__Desired behavior:__ There should be a operator for series (not only boolean) to get only the points where a value of one field as changed.

__Use case:__ Polling a sensor without checking if the value changed will cause series where many points have the same value as the point before. But often its only interesting when did the value changed (special for boolean values). In my case I have a sensor on a door and the sensor value (1 - open, 0- closed) will be stored every second. I have to calculate when the door was open and how long it was. With such a kind of operator I could do it within one query

**Comment by postgetme** [comment]
need this feature too
