### ISSUE TITLE
Memory gradually grows until crash

### ISSUE THREAD

**Issue by philippreston** [influxdata/influxdb#10178]
__System info:__  [Include InfluxDB version, operating system name, and other relevant details]

- InfluxDB 1.6.0 - TSI index
- Running in Docker
- Ubuntu 16.04.2 LTS
- 4.4.0-77-generic x86_64
- 8 CPU / 32G 
- KVM, SSD backed storage

__Steps to reproduce:__

I originally reported this in #9938.

We are seeing continual, gradual memory growth until ultimately the kernel kills influx and the instance is restarted.  Most of the time this appears to run out of memory during compaction, however, I believe that's as a result of the memory has risen to a point where the expected spike will take it into the OOM state.  See the graph below:

<img width="1961" alt="43151693-6e703306-8f64-11e8-86c5-a7b76a72cd90" src="https://user-images.githubusercontent.com/4885250/43897103-ec8d26b6-9bd2-11e8-9763-379abf0e326d.png">

And to zoom in at the crash:

<img width="1963" alt="43151782-a41cd39c-8f64-11e8-8db0-5d069aa6965a" src="https://user-images.githubusercontent.com/4885250/43897125-003bbf7e-9bd3-11e8-815e-860bb49255c7.png">

The data is written by telegraf from across a sub-set of our platform.  Current cardinality:

```> show series cardinality
cardinality estimation
----------------------
9873
```

We had previously run on 4-core / 16G of RAM and moved up to 8-core 32G which seems in line with a recommendation for our result set. 

__Expected behaviour:__ 

Not expecting the continual memory growth.

__Actual behaviour:__ 

Memory gradually grows until killed by the kernel with OOM.   The pattern certainly looks a pattern consistent with leaked memory.

__Additional info:__ 

[profiles.tar.gz](https://github.com/influxdata/influxdb/files/2274065/profiles.tar.gz)
[influxdb.conf.zip](https://github.com/influxdata/influxdb/files/2274075/influxdb.conf.zip)

(This happens every couple of days so happy to produce anything that is needed)

**Comment by philippreston** [comment]
Any thoughts or feedback on this issue?  Is there anything else I can provide?

**Comment by tux-00** [comment]
I encounter the same thing with 1.6.0 and docker.

**Comment by e-wiese** [comment]
The same on CentOS6 and 1.6.1. Had a high load with TSI, both CPU and memory. I increased RAM from 4GB to 8GB, but no improvement: influxd was killed by OS after running 2 days in average, having already swapped.
Then i switched back to inmem and everything is fine again. 

Cardinalities:
_internal: 3310
realtime: 3149
rtnet: 1322
telegraf: 121

Load with TSI:
![influx_tsi](https://user-images.githubusercontent.com/11369197/44902320-315fdb80-acf9-11e8-969d-f20aa34e942b.PNG)

Load with inmem:
![influx_inmem](https://user-images.githubusercontent.com/11369197/44902656-1fcb0380-acfa-11e8-96a4-b656ddd8bba3.PNG)

**Comment by philippreston** [comment]
Any update on thoughts on this memory growth/leak?  Happy to provide any additional information.

**Comment by steffenknott** [comment]
We seem to have the same effect running 1.6.2 on Debian 8 (vsphere VM running just InfluxDB, SSD storage, 16 GB RAM, 8 cores). We do have rather high cardinality, 

```
cardinality estimation
----------------------
4588114
```

but this didn't rise much in recent weeks (we didn't have this kind of problem before, even with higher cardinality). 

According to log files, the problem seems to have started after we upgraded from 1.5.2 to 1.6.2 last week. Since then, we encountered up to 61 crashes per day. We were able to reduce it dramatically by changing the influxdb_retention_check_interval from 30m to 24h. We still have crashes, but just 1 in the last 15 hours. That one was not related to a "Retention policy deletion check" but 2m after "Cache snapshot (end)":

```
Sep 17 10:45:11 tsdb01 influxd[24821]: ts=2018-09-17T10:45:11.548583Z lvl=info msg="Cache snapshot (end)" log_id=0A_uOHP0000 engine=tsm1 trace_id=0Aamzs7W000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=478.428ms
Sep 17 10:47:33 tsdb01 kernel: [229459.561110] influxd invoked oom-killer: gfp_mask=0x200da, order=0, oom_score_adj=0

```

We are also happy to provide any information that might help.

**Comment by philippreston** [comment]
Hey 

Managed to get back to investigate this in more detail.  I upgraded to 1.7.0 and moved out of Docker.  Same issue presented itself.

When investigating the pprof data - I could see that the memory was increasing around the write handler for the HTTP server:

<img width="386" alt="screenshot 2018-11-13 at 09 46 18" src="https://user-images.githubusercontent.com/4885250/48404823-08ac8700-e729-11e8-834e-8e249ccef004.png">

So looking at the connections being established I believe I have found where our memory issue was:

```
$ sudo netstat -tap -n | egrep 8086  | awk 'BEGIN{FS=" "} /10/{ print $5}' | cut -d":" -f1 | sort | uniq -c | sort -n | tail -n 10
      1 104.244.212.20
      1 172.19.0.3
      2 10.22.16.0
      2 10.22.16.4
      2 10.23.167.246
      6 10.0.0.2
   4716 10.22.160.21
   4716 10.22.160.98
   4717 10.22.160.22
   4717 10.22.160.99
```

So there are four devices (all switches) which seem to be accumulating a large number of connections.  Looking at the sending side I can see the connections are in FIN_WAIT.

```
$ sudo /sbin/ip netns exec ns-mgmt netstat -tap -n | egrep 8086
tcp        0  95569 10.22.160.21:39838      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 112945 10.22.160.21:39842      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 107241 10.22.160.21:39835      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 137561 10.22.160.21:39848      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 176656 10.22.160.21:39850      10.23.167.246:8086      ESTABLISHED 4950/telegraf
tcp        0 154937 10.22.160.21:39843      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 181001 10.22.160.21:39847      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 160729 10.22.160.21:39846      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 169417 10.22.160.21:39841      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 181001 10.22.160.21:39840      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 176657 10.22.160.21:39845      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 157833 10.22.160.21:39836      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 123081 10.22.160.21:39839      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 178105 10.22.160.21:39837      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 121633 10.22.160.21:39844      10.23.167.246:8086      FIN_WAIT1   -
tcp        0 175209 10.22.160.21:39849      10.23.167.246:8086      FIN_WAIT1   -```

These just continue to tick up and up, obviously hogging and never releasing the resources.  Looking at our captures its looks (for whatever reason) that the FIN is being sent - but never arrives...

I'll clean up this issue, verify it resolves the issue, then close out.

Thanks

Phil

**Comment by philippreston** [comment]
Closing issue.  Confirmed it was a very subtle routing issue on our management network where FIN was getting lost.

Thanks

Phil
