### ISSUE TITLE
influxd not openning ports when run as influxdb user

### ISSUE THREAD

**Issue by Grimblee** [influxdata/influxdb#10177]
__System info:__ 

InfluxDB shell version: 1.5.2
CentOS Linux release 7.5.1804 (Core)
SELinux disabled

__Steps to reproduce:__

Starting up the process normally as the influxdb user doesn't open ports specified with the bind-address parameter.

When starting it as root with _/usr/bin/influxd -config /etc/inflxudb/influxdb.conf_ said ports are open and listening.

Modifiyng the /usr/lib/systemd/system/influxdb.service file to execute as root also works.

Grafana is also running on this server and can open port 3000 as grafana user without any issue.

__Additional info:__ 

I tried modifying the port or the IP in bind-address (to either 127.0.0.1, 0.0.0.0 or the actual private ip) without success.

I tried adding the influxdb user to sys and wheel group, as explained in some discussion, to allow it to open ports without success.

I tried running _setcap 'cap_net_bind_service=+ep' /usr/bin/influxd_ and changing the port in bind-address to 886 without success.

At the moment only solution I found is modifying the systemd unit file to run as root, but that seem a bit insecure.

Thank you in advance for your help,

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for actionable bug reports or feature requests. 

This question would be better posted on the InfluxData community site: https://community.influxdata.com We would be happy to help there.

Thanks.
