### ISSUE TITLE
batch UDP data doesn't is written in the database

### ISSUE THREAD

**Issue by jeanguirro** [influxdata/influxdb#10182]
__System info:__ 
InfluxDB Version: 1.6.0
CentOS Linux release 7.3.1611

Config:

> Merging with configuration at: /etc/influxdb/influxdb.conf
> reporting-disabled = false
> bind-address = ":8088"
> 
> [meta]
>   dir = "/var/lib/influxdb/meta"
>   retention-autocreate = true
>   logging-enabled = true
> 
> [data]
>   dir = "/var/lib/influxdb/data"
>   index-version = "tsi1"
>   wal-dir = "/var/lib/influxdb/wal"
>   wal-fsync-delay = "0s"
>   query-log-enabled = true
>   cache-max-memory-size = 524288000
>   cache-snapshot-memory-size = 26214400
>   cache-snapshot-write-cold-duration = "1h0m0s"
>   compact-full-write-cold-duration = "24h0m0s"
>   max-series-per-database = 1000000
>   max-values-per-tag = 100000
>   max-concurrent-compactions = 0
>   max-index-log-file-size = 1048576
>   trace-logging-enabled = false
> 
> [coordinator]
>   write-timeout = "10s"
>   max-concurrent-queries = 0
>   query-timeout = "0s"
>   log-queries-after = "0s"
>   max-select-point = 0
>   max-select-series = 0
>   max-select-buckets = 0
> 
> [retention]
>   enabled = true
>   check-interval = "30m0s"
> 
> [shard-precreation]
>   enabled = true
>   check-interval = "10m0s"
>   advance-period = "30m0s"
> 
> [monitor]
>   store-enabled = true
>   store-database = "_internal"
>   store-interval = "10s"
> 
> [subscriber]
>   enabled = true
>   http-timeout = "30s"
>   insecure-skip-verify = false
>   ca-certs = ""
>   write-concurrency = 40
>   write-buffer-size = 1000
> 
> [http]
>   enabled = true
>   bind-address = ":8086"
>   auth-enabled = false
>   log-enabled = true
>   suppress-write-log = false
>   write-tracing = false
>   pprof-enabled = false
>   debug-pprof-enabled = false
>   https-enabled = false
>   https-certificate = "/etc/ssl/influxdb.pem"
>   https-private-key = ""
>   max-row-limit = 10000
>   max-connection-limit = 0
>   shared-secret = ""
>   realm = "InfluxDB"
>   unix-socket-enabled = false
>   unix-socket-permissions = "0777"
>   bind-socket = "/var/run/influxdb.sock"
>   max-body-size = 25000000
>   access-log-path = ""
>   max-concurrent-write-limit = 0
>   max-enqueued-write-limit = 0
>   enqueued-write-timeout = 30000000000
> 
> [logging]
>   format = "auto"
>   level = "error"
>   suppress-logo = false
> 
> [ifql]
>   enabled = false
>   log-enabled = true
>   bind-address = ":8082"
> 
> [[graphite]]
>   enabled = false
>   bind-address = ":2003"
>   database = "graphite"
>   retention-policy = ""
>   protocol = "tcp"
>   batch-size = 5000
>   batch-pending = 10
>   batch-timeout = "1s"
>   consistency-level = "one"
>   separator = "."
>   udp-read-buffer = 0
> 
> [[collectd]]
>   enabled = false
>   bind-address = ":25826"
>   database = "collectd"
>   retention-policy = ""
>   batch-size = 5000
>   batch-pending = 5
>   batch-timeout = "10s"
>   read-buffer = 0
>   typesdb = "/usr/share/collectd/types.db"
>   security-level = "none"
>   auth-file = "/etc/collectd/auth_file"
>   parse-multivalue-plugin = "split"
> 
> [[opentsdb]]
>   enabled = false
>   bind-address = ":4242"
>   database = "opentsdb"
>   retention-policy = ""
>   consistency-level = "one"
>   tls-enabled = false
>   certificate = "/etc/ssl/influxdb.pem"
>   batch-size = 1000
>   batch-pending = 5
>   batch-timeout = "1s"
>   log-point-errors = true
> 
> [[udp]]
>   enabled = true
>   bind-address = ":4444"
>   database = "metricsdb"
>   retention-policy = ""
>   batch-size = 50000
>   batch-pending = 20
>   read-buffer = 0
>   batch-timeout = "1m0s"
>   precision = ""
> 
> [continuous_queries]
>   log-enabled = true
>   enabled = true
>   query-stats-enabled = false
>   run-interval = "1s"

__Steps to reproduce:__
My application sends the data in batches using UDP, using tcpdump (tcpdump -i eth0 udp port 4444 -xxXX -w teste_jlg.cap) I was able to capture the data in influxdb server, but the data doesn't is written in the database, (select * from app_test where time > now() - 1h)

tcpdump exemple:
```
$ strings teste_jlg.cap | grep statuses | grep 1533838242706994944
app_test,city=foo,product=bar0 count=0 1533838242706994944
app_test,city=foo,product=bar1 count=0 1533838242706994944
app_test,city=foo,product=bar2 count=0 1533838242706994944
app_test,city=foo,product=bar3 count=0 1533838242706994944
app_test,city=foo,product=bar4 count=0 1533838242706994944
app_test,city=foo,product=bar5 count=0 1533838242706994944
app_test,city=foo,product=bar6 count=0 1533838242706994944
app_test,city=foo,product=bar7 count=0 1533838242706994944
app_test,city=foo,product=bar8 count=0 1533838242706994944
app_test,city=foo,product=bar9 count=0 1533838242706994944
app_test,city=foo,product=bar10 count=0 1533838242706994944
app_test,city=foo,product=bar11 count=0 1533838242706994944
app_test,city=foo,product=bar12 count=0 1533838242706994944
```

Others data delivered in UDP, but not in the batch was written normally;

In internal stats i have the following data:
```
> USE _internal
Using database _internal
> select * from udp order by desc limit 10
name: udp
time                 batchesTx batchesTxFail bind  bytesRx  hostname           pointsParseFail pointsRx pointsTx readFail
----                 --------- ------------- ----  -------  --------           --------------- -------- -------- --------
2018-08-09T18:20:40Z 12        0             :4444 83886488 data-influx-server 0               566686   556790   0
2018-08-09T18:20:30Z 12        0             :4444 82771131 data-influx-server 0               559108   556790   0
2018-08-09T18:20:20Z 11        0             :4444 81600800 data-influx-server 0               551203   510171   0
2018-08-09T18:20:10Z 11        0             :4444 80456969 data-influx-server 0               543494   510171   0
2018-08-09T18:20:00Z 11        0             :4444 79296694 data-influx-server 0               535612   510171   0
```

my UDP sysctl parameters:
```
# sysctl -a | grep udp
net.ipv4.udp_mem = 190737	254317	381474
net.ipv4.udp_rmem_min = 4096
net.ipv4.udp_wmem_min = 4096
net.netfilter.nf_conntrack_udp_timeout = 30
net.netfilter.nf_conntrack_udp_timeout_stream = 180
```

Thanks in advance for any help

**Comment by e-dard** [comment]
@jeanguirro are you sure that the times in the points were within the time boundaries of the query?

**Comment by dgnorton** [comment]
Closing since no response.
