### ISSUE TITLE
Cannot drop database

### ISSUE THREAD

**Issue by michelgokan** [influxdata/influxdb#10198]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Latest version. Installed via `helm latest/influxdb` in Kubernetes
__Steps to reproduce:__

1. create database a
2. Insert lots of measurements
3. drop database a

__Expected behavior:__ [What you expected to happen]
Deleting the database with its all measurements

__Actual behavior:__ [What actually happened]
Nothing happened

**Comment by e-dard** [comment]
@michelgokan can you tell us exactly what version you're running? Ideally from the logs. Can you provide some more accurate reproduction steps?

**Comment by michelgokan** [comment]
I restarted the influxdb, and the problem gone. I will provide more info as soon as I experienced something similar again.

**Comment by dgnorton** [comment]
Closing since it seems the issue hasn't reoccurred.
