### ISSUE TITLE
Enabling Unix domain socket prevents start-up

### ISSUE THREAD

**Issue by drfickle** [influxdata/influxdb#10199]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

Ubuntu Server 18.04.1
InfluxDB 1.6.1 (from https://repos.influxdata.com/ubuntu)

__Steps to reproduce:__

1. Edit influxdb.conf and set unix-socket-enabled = true
2. Restart influxdb daemon

__Expected behavior:__ [What you expected to happen]

Service should restart and be available on both HTTP and Unix socket.

__Actual behavior:__ [What actually happened]

The HTTP service never starts and port 8086 never listens.

__Additional info:__ [Include gist of relevant config, logs, etc.]

```
Aug 16 08:28:24 zt-tick-0 influxd[23269]: ts=2018-08-16T13:28:24.703842Z lvl=info msg="Storing statistics" log_id=09xjbND0000 service=monitor db_instance=_internal db_rp=monitor interval=10s
Aug 16 08:28:24 zt-tick-0 influxd[23269]: ts=2018-08-16T13:28:24.706871Z lvl=info msg="Listening on HTTP" log_id=09xjbND0000 service=httpd addr=[::]:8086 https=true
Aug 16 08:28:24 zt-tick-0 influxd[23269]: run: open server: open service: listen unix /var/run/influxdb.sock: bind: permission denied
Aug 16 08:28:24 zt-tick-0 systemd[1]: influxdb.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 08:28:24 zt-tick-0 systemd[1]: influxdb.service: Failed with result 'exit-code'.
Aug 16 08:28:25 zt-tick-0 systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.
Aug 16 08:28:25 zt-tick-0 systemd[1]: influxdb.service: Scheduled restart job, restart counter is at 6.
Aug 16 08:28:25 zt-tick-0 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
```
Looking at the permissions on the directory
```
root@zt-tick-0:~# ls -dl /var/run/
drwxr-xr-x 28 root root 940 Aug 16 06:25 /var/run/
drwxr-xr-x  2 root     root       60 Aug 15 15:26 apache2
-rw-r--r--  1 root     root        5 Aug 15 15:26 atd.pid
drwxr-xr-x  2 root     root       80 Aug 15 15:25 blkid
drwxr-xr-x  2 root     root       80 Aug 15 15:26 console-setup
-rw-r--r--  1 root     root        5 Aug 15 15:26 crond.pid
----------  1 root     root        0 Aug 15 15:26 crond.reboot
[snip]
drwxr-xr-x  2 root     root       60 Aug 15 15:26 mount
drwxr-xr-x  2 root     root      140 Aug 15 15:26 network
drwxrwsr-x  3 postgres postgres  120 Aug 15 15:26 postgresql
drwxr-xr-x  3 root     root      100 Aug 15 15:26 resolvconf
-rw-r--r--  1 root     root        4 Aug 15 15:26 rsyslogd.pid
drwxr-xr-x  2 root     root       40 Aug 15 15:26 samba
```
It seems that Postgres creates its own subdirectory and sets the ownership when it starts up (prior to dropping root privileges), because apt has no record of providing that directory.
```
root@zt-tick-0:~# dpkg -S /var/run/postgresql
dpkg-query: no path found matching pattern /var/run/postgresql
```
Apache does not need to do that because it maintains one master process that runs as root.
```
root@zt-tick-0:~# ps -ef | grep apache
root      2260     1  0 Aug15 ?        00:00:02 /usr/sbin/apache2 -k start
www-data  2268     1  0 Aug15 ?        00:00:01 /usr/bin/htcacheclean -d 120 -p /var/cache/apache2/mod_cache_disk -l 300M -n
root      4832  8783  0 08:55 pts/0    00:00:00 grep apache
www-data 22272  2260  0 06:25 ?        00:00:01 /usr/sbin/apache2 -k start
www-data 22273  2260  0 06:25 ?        00:00:01 /usr/sbin/apache2 -k start
```
It appears that systemd can manage this directory for you using the [RuntimeDirectory](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=) option in the service file. The ssh.service file on my system also uses this method. I added ```RuntimeDirectory=influxdb``` to my ```/etc/systemd/system/influxd.service``` file, changed influxdb.conf to use ```bind-socket = "/var/run/influxdb/influxdb.sock"``` and restarted the service successfully. Now I can access the database with both methods.

**Comment by MaksVal** [comment]
I have a similar bug.
Strace InfluxDB , cmd `sudo -u influxdb strace -f /usr/bin/influxd -config /etc/influxdb/influxdb.conf`:
```
[pid 28864] newfstatat(AT_FDCWD, "/var/run", {st_mode=S_IFDIR|0755, st_size=1280, ...}, 0) = 0
[pid 28864] unlinkat(AT_FDCWD, "/var/run/influxdb.sock", 0) = -1 EACCES (Permission denied)
[pid 28864] write(2, "run: open server: open service: "..., 50run: open server: open service: permission denied
) = 50
+++ exited with 1 +++
```
Socket:
```
user@h:~$ stat /var/run/influxdb.sock
  File: '/var/run/influxdb.sock'
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 13h/19d	Inode: 292         Links: 1
Access: (0666/srw-rw-rw-)  Uid: (  999/influxdb)   Gid: (  999/influxdb)
Access: 2019-02-27 10:31:52.920675684 +0300
Modify: 2019-02-27 10:31:52.920675684 +0300
Change: 2019-02-27 10:31:52.920675684 +0300
 Birth: -
```

**Comment by ankithoney1987** [comment]
I am facing this issue where when trying to start influxdb with the below:
# Bind address to use for the RPC service for backup and restore.
bind-address = "127.0.0.1:8088"

[http]
  unix-socket-enabled = true
  bind-address = /var/run/influxdb.sock 

Failed Log:
`Apr 04 20:46:46 ubnt1804template systemd[1]: influxdb.service: Failed with result 'exit-code'.
Apr 04 20:46:46 ubnt1804template systemd[1]: influxdb.service: Main process exited, code=exited, status=1/FAILURE
Apr 04 20:46:46 ubnt1804template influxd[24329]: run: open server: open service: mkdir unix:: permission denied
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106663Z lvl=info msg="Listening on HTTP" log_id=0Lyjz4bW000 service=httpd addr=[::]:8086 https=false
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106632Z lvl=info msg="Storing statistics" log_id=0Lyjz4bW000 service=monitor db_instance=_internal db_rp=monitor 
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106583Z lvl=info msg="opened HTTP access log" log_id=0Lyjz4bW000 service=httpd path=stderr
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106579Z lvl=info msg="Starting HTTP service" log_id=0Lyjz4bW000 service=httpd authentication=false
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106571Z lvl=info msg="Starting continuous query service" log_id=0Lyjz4bW000 service=continuous_querier
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106567Z lvl=info msg="Starting snapshot service" log_id=0Lyjz4bW000 service=snapshot
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106562Z lvl=info msg="Starting precreation service" log_id=0Lyjz4bW000 service=shard-precreation check_interval=1
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106548Z lvl=info msg="Registered diagnostics client" log_id=0Lyjz4bW000 service=monitor name=system
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106541Z lvl=info msg="Registered diagnostics client" log_id=0Lyjz4bW000 service=monitor name=network
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106537Z lvl=info msg="Registered diagnostics client" log_id=0Lyjz4bW000 service=monitor name=runtime
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106533Z lvl=info msg="Registered diagnostics client" log_id=0Lyjz4bW000 service=monitor name=build
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106527Z lvl=info msg="Starting monitor service" log_id=0Lyjz4bW000 service=monitor
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106515Z lvl=info msg="Opened service" log_id=0Lyjz4bW000 service=subscriber
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106425Z lvl=info msg="Open store (end)" log_id=0Lyjz4bW000 service=store trace_id=0Lyjz50G000 op_name=tsdb_open o
Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.105961Z lvl=info msg="Opened shard" log_id=0Lyjz4bW000 service=store trace_id=0Lyjz50G000 op_name=tsdb_open index
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.860856Z lvl=info msg="Reading file" log_id=0Lyjz4bW000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.547534Z lvl=info msg="Opened shard" log_id=0Lyjz4bW000 service=store trace_id=0Lyjz50G000 op_name=tsdb_open index
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.547156Z lvl=info msg="Opened shard" log_id=0Lyjz4bW000 service=store trace_id=0Lyjz50G000 op_name=tsdb_open index
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.538291Z lvl=info msg="Opened shard" log_id=0Lyjz4bW000 service=store trace_id=0Lyjz50G000 op_name=tsdb_open index
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.509353Z lvl=info msg="Opened file" log_id=0Lyjz4bW000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/t
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.509086Z lvl=info msg="Opened file" log_id=0Lyjz4bW000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/_
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.508987Z lvl=info msg="Reading file" log_id=0Lyjz4bW000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.508585Z lvl=info msg="Opened file" log_id=0Lyjz4bW000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/_
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.505487Z lvl=info msg="Open store (start)" log_id=0Lyjz4bW000 service=store trace_id=0Lyjz50G000 op_name=tsdb_open
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.505424Z lvl=info msg="Compaction settings" log_id=0Lyjz4bW000 service=store max_concurrent_compactions=6 throughp
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.505380Z lvl=info msg="Using data dir" log_id=0Lyjz4bW000 service=store path=/var/lib/influxdb/data
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.402788Z lvl=info msg="Go runtime" log_id=0Lyjz4bW000 version=go1.12.6 maxprocs=12
Apr 04 20:46:45 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:45.402676Z lvl=info msg="InfluxDB starting" log_id=0Lyjz4bW000 version=1.7.10 branch=1.7 commit=f46f63d4e2d9684a2dd7
Apr 04 20:46:42 ubnt1804template systemd[1]: Started InfluxDB is an open-source, distributed, time series database.`


OS Details:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

**Comment by melroy89** [comment]
> I am facing this issue where when trying to start influxdb with the below:
> 
> ###Config Bind address to use for the RPC service for backup and restore. bind-address = "127.0.0.1:8088" [http] unix-socket-enabled = true bind-address = /var/run/influxdb.sock
> 
> ###Failed Log: `Apr 04 20:46:46 ubnt1804template systemd[1]: influxdb.service: Main process exited, code=exited, status=1/FAILURE
> 
> Apr 04 20:46:46 ubnt1804template influxd[24329]: run: open server: open service: mkdir unix:: permission denied
> 
> Apr 04 20:46:46 ubnt1804template influxd[24329]: ts=2020-04-04T20:46:46.106663Z lvl=info msg="Listening on HTTP" log_id=0Lyjz4bW000 service=httpd addr=[::]:8086 https=false`
> 
> ###OS Details: DISTRIB_ID=Ubuntu DISTRIB_RELEASE=18.04 DISTRIB_CODENAME=bionic DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

I found myself with the same problem.

The easier solution for me was to create a sub-directory instead: 

```
sudo mkdir -p /var/run/influxdb
```

Then give it the correct rights (`influxdb` user and group):

```sh
sudo chown influxdb.influxdb /var/run/influxdb
````

Change the influx config socket location, edit: `/etc/influxdb/influxdb.conf` (eg. `sudo nano /etc/influxdb/influxdb.conf`) and change:

```
bind-socket = "/var/run/influxdb.sock"
```

To:
```
bind-socket = "/var/run/influxdb/influxdb.sock"
```

Restart the service: `sudo systemctl restart influxdb.service`
