### ISSUE TITLE
when

### ISSUE THREAD

**Issue by lazycattylqm** [influxdata/influxdb#10192]
__Proposal:__ [query goes slow]

__Current behavior:__ [What currently happens]
when I tried to query a sql like select sum(feild) as feild from measuement group by tag
it goes slow sometimes especially when there is huge data

__Desired behavior:__ [What you would like to happen]
I wanna know if there is a to optimize it

Requests may be closed if we're not actively planning to work on them.

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for actionable bug reports or feature requests. 

This question would be better posted on the InfluxData community site: https://community.influxdata.com We would be happy to help there.

Thanks.
