### ISSUE TITLE
query goes slow

### ISSUE THREAD

**Issue by lazycattylqm** [influxdata/influxdb#10193]
Proposal: [query goes slow]

Current behavior: [What currently happens]
when I tried to query a sql like select sum(feild) as feild from measuement group by tag
it goes slow sometimes especially when there is huge data When there are million pieces of data ,the quries may run several seconds or longer

Desired behavior: [What you would like to happen]
I wanna know if there is a to optimize it

Requests may be closed if we're not actively planning to work on them.

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for actionable bug reports or feature requests. 

This question would be better posted on the InfluxData community site: https://community.influxdata.com We would be happy to help there.

Thanks.
