### ISSUE TITLE
error parsing query: unable to find time zone 

### ISSUE THREAD

**Issue by CoderOverflow** [influxdata/influxdb#10196]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
1.6.1 window 2003
__Steps to reproduce:__

![5v l2lc aojs8vy0 v 74w](https://user-images.githubusercontent.com/29338660/44128233-71db66ac-a074-11e8-93b5-9c35f9c53966.png)

I used tz(), but it cannot run correctly.

received status code 400 from server: err: error parsing query: unable to find time zone Europe/Athens

![dzz41e _f46y4tl8mzulp q](https://user-images.githubusercontent.com/29338660/44128393-57f1a1c4-a075-11e8-9eac-7ab80a82aea0.png)

**Comment by kabua** [comment]
I got the same thing when trying to use America/Chicago or America/New_York

Here's some example code:
```
> select * from "computerInfo1"
name: computerInfo1
time                Host      Region  cpu              ram
----                ----      ------  ---              ---
1536016386197803300 some-host west-eu 0.29180121807931 1122304810
>
> select * from "computerInfo1" tz('America/New_York')
ERR: error parsing query: unable to find time zone America/New_York
> select * from "computerInfo1" tz('America/Chicago')
ERR: error parsing query: unable to find time zone America/Chicago
```

**Comment by steinelg** [comment]
+1 It would be great to have this feature back, any help much appreciated

**Comment by zhgqiang** [comment]
因为InfluxDB开发语言是go，我测试了一下配置go环境变量，就没有问题了，主要依赖go下边的lib库。

**Comment by zheng7yan** [comment]
@zhgqiang 你好，请问您是在windows机器上配置的go环境变量来解决这个问题的吗？如果是的话，能大体告知一下吗？
ps:我用的influxd版本是`1.7.4.1`，系统是`win server 2016`

**Comment by bomerzz** [comment]
Any updates on the above issue? Still present on windows for 1.7.7

**Comment by sbhenderson** [comment]
This describes what's happening in more detail: [Golong TZ issue](https://github.com/golang/go/issues/21881)

Turns out, this is a general issue with Go on Windows platforms, but anyone who is Googling may at least find out the answer from the referenced issue. Personally, I was able to resolve it by getting the zoneinfo.zip from installing Go locally (not necessary on the Windows machine running InfluxDB) and placing it into the correct folder.

**Comment by ashishtaldeokar** [comment]
In case, anyone has this issue in Ubuntu systems,
you probably are missing Timezone data in OS that is `timedatectl list-timezones` returns only UTC format. In this case, you can just install the `tzdata` package, ex `apt install tzdata` or if it is already installed you can just reconfigure using ` dpkg-reconfigure tzdata` 
This worked for me, as a fresh VM from gcp did not have `tzdata` and my influx setup came across this error.
