### ISSUE TITLE
data stopping at 2147483647

### ISSUE THREAD

**Issue by krywenko** [influxdata/influxdb#10204]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
ubuntu 16.04.lts and on windows os  influxd 1.6.1
__Steps to reproduce:__
it use to work fine on older version of influx, but now it stopping at 2147483647
I wrote a piece of software that reads collectd CSV and processes them and sends them to influxd
if i send multi value  csv 
example:
timestamp,rx,tx
2018-08-16 22:02:02,578527857,12037843403

the data stops  when it reaches  2147483647  for each value

if i use a single value csv
example:
timestamp, value
2018-08-16 22:02:02,57852785712037843403

it will publish with out any limit of 2147483647  I tried with values up to 30 digits long  no problems. it only happens when I send multiple values , then the value caps at 2147483647 for some reason

[profiles.tar.gz](https://github.com/influxdata/influxdb/files/2295710/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/influxdb/files/2295711/vars.txt)

**Comment by e-dard** [comment]
@krywenko what architecture are you running on? Is it a 32bit system? `2147483647` is the largest 32 bit signed integer value. You could be hitting a limit somewhere.

**Comment by krywenko** [comment]
locally Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-32-generic x86_64)  just a fresh install of ubuntu  and newly downloaded influx from influx webpage 

how does one tell the arch type of influx  maybe  for some reason the 32bit is installing  on the ubuntu instead of the 64 bit version... but  it is also having the same issue on a remote 64 bit windows  version also a fresh install, may they are installing a 32 bit by mistake too . ( I have no direct access to that computer as it 1/2 around the world so I am taking them at their world )

currently I wrote a small work around converted my   integer values  to float and it all goes through fine

**Comment by dgnorton** [comment]
@krywenko run `od -An -t x1 -j 4 -N 1 influxd`. If it outputs `01` it's 32-bit and `02` means 64-bit.

I'm going to close this. If it turns out that you're running 64-bit everywhere and this is still an issue, reply here and we can re-open the issue.
