### ISSUE TITLE
problem with "sum(xx) group by time(1m) "

### ISSUE THREAD

**Issue by CoderOverflow** [influxdata/influxdb#10205]
Hi, 
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
1.6.1 windows 2003   
__Steps to reproduce:__

I want to get sum result, but I find that the last minute data is missing.

SELECT sum("Bytes_Received_persec") AS "data1", count("Bytes_Received_persec") AS "count1" FROM "telegraf"."autogen"."win_net" WHERE time > now() - 1h GROUP BY time(1m) FILL(null)
![g 6 j l20p gyp u65bcig](https://user-images.githubusercontent.com/29338660/44245773-24c58880-a20d-11e8-906b-1cec37072394.png)

I have to use  "time < now() + 1m " to get the last minute before now()
SELECT sum("Bytes_Received_persec") AS "data1", count("Bytes_Received_persec") AS "count1" FROM "telegraf"."autogen"."win_net" WHERE time > now() - 1h and **time < now() + 1m** GROUP BY time(1m) FILL(null)

![1phad7 isusjv _ p a3uk](https://user-images.githubusercontent.com/29338660/44245743-e5973780-a20c-11e8-87c0-b263c026648a.png)

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for actionable bug reports or feature requests. 

This question would be better posted on the InfluxData community site: https://community.influxdata.com We would be happy to help there.

Thanks.
