### ISSUE TITLE
Influxdb failing Unable to connect 

### ISSUE THREAD

**Issue by SARUNAR** [influxdata/influxdb#10203]
influx
Failed to connect to http://localhost:8086: Get http://localhost:8086/ping: dial tcp [::1]:8086: getsockopt: connection refused
Please check your connection settings and ensure 'influxd' is running.
Unable 
![image](https://user-images.githubusercontent.com/29358331/44231959-f2f4e900-a15c-11e8-84a1-b5087bf275b1.png)
netstat -tlpun | grep 8086
[root@bolprbinflux01v data]#
netstat -tlpun | grep influx
tcp 0 0 10.109.123.106:8088 0.0.0.0:* LISTEN 50161/influxd

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for actionable bug reports or feature requests. 

This question would be better posted on the InfluxData community site: https://community.influxdata.com We would be happy to help there.

Thanks.
