### ISSUE TITLE
DELETE query is very slow -- still slow in InfluxDb 1.6.0

### ISSUE THREAD

**Issue by hpbieker** [influxdata/influxdb#10218]
__System info:__
InfluxDb 1.6.0
Ubuntu 16.04

__Steps to reproduce:__
I reported this before in #9015 for InfluxDb 1.3.x, but the issue remains: deletes are very slow.

I get a lot of the following in the log:
```
ts=2018-08-22T11:50:40.932742Z lvl=warn msg="Detected slow query: DELETE FROM \"XXX\" WHERE (time >= '2018-08-11 00:00:00' AND time < '2018-08-12 00:00:00') (qid: 1092268, database: xxx, threshold: 10s)" log_id=09NfXRsW000 service=query
```

__Expected behavior:__ 
Deletes should be fast.

__Actual behavior:__
Deletes takes maybe 5-10 seconds in some cases.

__Profile:__
I did a profile while running a delete from in a loop, each taking around 4 seconds.
[block.txt](https://github.com/influxdata/influxdb/files/2332378/block.txt)
[cpu.txt](https://github.com/influxdata/influxdb/files/2332379/cpu.txt)
[diagnostics.txt](https://github.com/influxdata/influxdb/files/2332380/diagnostics.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/2332381/goroutine.txt)
[mutex.txt](https://github.com/influxdata/influxdb/files/2332382/mutex.txt)
[shards.txt](https://github.com/influxdata/influxdb/files/2332383/shards.txt)
[stats.txt](https://github.com/influxdata/influxdb/files/2332384/stats.txt)

**Comment by hpbieker** [comment]
It looks like this is the method that is waiting when doing the delete:
```
A
```


'''
2257863519459 260056 @ 0x4759c5 0x47687e 0x93b2ad 0xae7e67 0xae7909 0x94a8ee 0x966fa4 0x966228 0x45e4d1
#	0x4759c4	sync.(*Mutex).Unlock+0x74									/usr/local/go/src/sync/mutex.go:201
#	0x47687d	sync.(*RWMutex).Unlock+0x7d									/usr/local/go/src/sync/rwmutex.go:132
#	0x93b2ac	github.com/influxdata/influxdb/tsdb.(*SeriesFile).Wait+0x5c					/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:132
#	0xae7e66	github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).DeleteSeriesRangeWithPredicate+0x526	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1434
#	0xae7908	github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).DeleteSeriesRange+0x68		/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1352
#	0x94a8ed	github.com/influxdata/influxdb/tsdb.(*Shard).DeleteSeriesRange+0x8d				/go/src/github.com/influxdata/influxdb/tsdb/shard.go:704
#	0x966fa3	github.com/influxdata/influxdb/tsdb.(*Store).DeleteSeries.func1+0x583				/go/src/github.com/influxdata/influxdb/tsdb/store.go:1224
#	0x966227	github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1+0x47				/go/src/github.com/influxdata/influxdb/tsdb/store.go:878
'''

**Comment by hpbieker** [comment]
Is the problem with DELETE FROM that it takes long time to update the series indeces?
![image](https://user-images.githubusercontent.com/24992762/44848832-78e25b00-ac58-11e8-8933-865ac22b6931.png)

**Comment by hpbieker** [comment]
Just doing some testing.

The query below takes around four seconds. There is no data in this delete interval, but all/many of the shards has data for this series.
```
delete from "TEST+TEST" WHERE time > 2000000000000000000
```

The query below takes a few ms (I do not notice any delay). But this has only a single sample (but still outside the delete interval).
```
delete from "TEST+TEST2" WHERE time > 2000000000000000000
```

Taking a similar query for a different database with ~1000 shards and a series which exists in all shards too around ~70 seconds. The database has around 17-18 k measurements and 10-20 fields each.

@jwilder To me it looks like there is a missing check for min/max that causes some expensive operation to be done in all shards where the series key exist even if it it is **outside the min/max time interval** that is specified. Does this make any sense?

**Comment by nicolas17** [comment]
Is this the same as #9636?

**Comment by hpbieker** [comment]
It might be, but to me it looks like the problem is that all series lists are rebuilt independently of the time range of where we delete data removed. If you have many shards or many series this will take time.

If you actually drop a series completely it makes sense to rebuild all series lists.
