### ISSUE TITLE
Incremental backup is not so incremental.

### ISSUE THREAD

**Issue by painhardcore** [influxdata/influxdb#10210]
https://en.wikipedia.org/wiki/Incremental_backup
Right now backup cli is making full backup. Why it's called incremental?
Yeah, we have -start -end and -since. But we have to adjust it manually.
I propose to make it clear and simple:

1. When directory is empty - 1st backup will be "full" (optionally with timestamp). All later backups will take last backup timestamp and make "incremental".
2. When you make backup - you need retention policy for it. We don't need to store data, that too old.

Am i wrong at something?

**Comment by 908875137** [comment]
What's your version? In 1.6 , there is not words 'Incremental backup' in document

**Comment by painhardcore** [comment]
@908875137 https://docs.influxdata.com/influxdb/v1.6/administration/backup_and_restore/ 

> [ -since <timestamp> ]: **Perform an incremental backup** after the specified timestamp RFC3339 format. Use -start instead, unless needed for legacy backup support.

**Comment by adampl** [comment]
See also #11524.

**Comment by adampl** [comment]
Is Influx team dead or what?

**Comment by painhardcore** [comment]
I think for them backup/restore is not the first priority.

**Comment by hjsjy** [comment]
i want to know influxDb whether  support incremental backup.
