### ISSUE TITLE
use 'm_id' as tag value will make show series where clause not work

### ISSUE THREAD

**Issue by zwg-zero** [influxdata/influxdb#10239]
influxdb 1.6.2， system： ubuntu16.04

__Steps to reproduce:__

1. insert records: 
insert li.ss.bb.cc,m_id=23 value=535
insert li.ss.bb.cc,m_id=455 value=884
insert li.ss.bb.cc,mid=ieie value=848
2. show series from "li.ss.bb.cc" where "m_id"='23'  (or other "m_id"='ANYTHING')

__Expected behavior:
    only return series of m_id equal '23'

__Actual behavior:
   all the series returned

__Additional info:
  influxdb verson 1.5 also has same problem, but influxdb version 1.2 has no such problem

If this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"

curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
```

**Please note** It will take at least 30 seconds for the first cURL command above to return a response.
This is because it will run a CPU profile as part of its information gathering, which takes 30 seconds to collect.
Ideally you should run these commands when you're experiencing problems, so we can capture the state of the system at that time.

If you're concerned about running a CPU profile (which only has a small, temporary impact on performance), then you can set `?cpu=false` or omit `?cpu=true` altogether.

Please run those if possible and link them from a [gist](http://gist.github.com) or simply attach them as a comment to the issue.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

**Comment by e-dard** [comment]
@zwg-zero I'm unable to reproduce this. Are you sure you were running `1.6.2` when you encountered this bug?

```
⇒  influx
Connected to http://localhost:8086 version unknown
InfluxDB shell version: unknown
> create database dn
> create database db
> use db
Using database db
> insert li.ss.bb.cc,m_id=23 value=535
> insert li.ss.bb.cc,m_id=455 value=884
> insert li.ss.bb.cc,mid=ieie value=848
>
> show series from "li.ss.bb.cc" where "m_id"='23'
key
---
li.ss.bb.cc,m_id=23
> show series from "li.ss.bb.cc" where "m_id"='23asdd'
>
```

**Comment by dgnorton** [comment]
Closing since no response and unable to repro
