### ISSUE TITLE
GROUP BY should not include null value?

### ISSUE THREAD

**Issue by ash0080** [influxdata/influxdb#10235]
For example:

| SHOPNAME | MESSAGE |
|----------|---------|
|          | hello   |
| A        | world   |
| B        | welcome |

SELECT count(message) FROM shop.measure WHERE [ !~/./not work，!=null not work,  !="" not work, IS NOT NULL not work ]  GROUP BY shopname

or I  am wrong? anyone can tell me how to query exclude a null value?

**Comment by scmod** [comment]
perhaps always insert a '' for shopname will be ok?
[https://stackoverflow.com/questions/30091980/select-from-influxdb-where-value-is-null](url)
