### ISSUE TITLE
client should durations.

### ISSUE THREAD

**Issue by james-lawrence** [influxdata/influxdb#10233]
__Proposal:__ client should be able to support duration fields.

__Current behavior:__ time.Duration is encoded as a string.

__Desired behavior:__ have it encoded as a numeric value

__Use case:__ its surprising behaviour, and leads to fields with strings when a user expects a number meaning aggregate functions cannot be used when querying.

see [appendField](https://github.com/influxdata/influxdb/blob/master/models/points.go#L2375)

**Comment by e-dard** [comment]
@james-lawrence how are you inserting data into Influx? I'm assuming you're using the Go client library? You can make the `time.Duration` numeric by converting it to an `int64` before you set it as a field value.

**Comment by james-lawrence** [comment]
@e-dard I'm aware of the workaround, problem is it is unexpected behaviour and leads to bad data in the database that then becomes somewhat painful to clear out. best to just avoid that behaviour all together.

**Comment by e-dard** [comment]
@james-lawrence we support very language agnostic datatypes: integers, floats, strings and bools. A duration is just an integer with some extra semantic meaning.

**Comment by james-lawrence** [comment]
correct, and thats my point. it should be converted to an integer and not a string.
