### ISSUE TITLE
dumptsm usage of "Points" label inconsistent with glossary definition

### ISSUE THREAD

**Issue by fluffynukeit** [influxdata/influxdb#10248]
__System info:__ 1.6, Linux, Arm

__Steps to reproduce:__

1. Log data points containing multiple fields with each timestamp, say 3, until the TSM file rolls over to a new one.
2. Use influx_inspect dumptsm to show the TSM info.  Note the number of Points and the Time Range
3. In influx, run a count query on the measurement using the Time Range given in step 2 to count the number of "points" as defined in https://docs.influxdata.com/influxdb/v1.6/concepts/key_concepts/#point

__Expected behavior:__ The number of Points reported by dumptsm and the number of points identified by the query are the same.

__Actual behavior:__ The number of points reported by dumptsm is actually 3 times the number of points reported by the query.  The dumptsm tool is not using "Points" consistently with the InfluxDB documentation, which states that a "point" includes the entire field set.  Instead, it is reporting the number of single time-stamped values indexed by the TSM.  In addition to showing the wrong number of points, the bytes/point calculation is also misleading because it is reporting the bytes per time-stamped value, not number of bytes per time-stamped field set (i.e., a "point")

__Additional info:__ The Influx documentation does a good job of being precise with terminology.  I think it would be good to reflect that level of clarity in the inspect utility.

**Comment by e-dard** [comment]
Thanks @fluffynukeit, you're right. In the inspect tools, when we talk about points in TSM data, we're really talking about individual series.

**Comment by khalibartan** [comment]
@e-dard I want to help in fixing this issue. Do you want to share some points before I start?
