### ISSUE TITLE
Influxd startup fails eventually with fatal error: runtime: address space conflict 

### ISSUE THREAD

**Issue by AriSuutariST** [influxdata/influxdb#10244]
__System info:__ InfluxDB 1.5.2 & 1.6.1 on FreeBSD 10.4

__Steps to reproduce:__

1. Create a large database (this is about 1 Tb)
2. Stop influxd
3. Start influxd again

Influxd starts going through all tsm files and eventually spits out:

Aug 30 15:08:27 xserver influxd: ts=2018-08-30T12:08:27.217423Z lvl=info msg="Opened shard" log_id=0AEgKNG0000 service=store trace_id=0AEgKOP0000 op_name=tsdb_open index_version=tsi1 path=/va
r/db/influxdb/data/xxxxx/autogen/218 duration=73352.407ms
Aug 30 15:08:27 xserver influxd: runtime: address space conflict: map(0xc460a70000) = 0xcc6f190000(err 0)
Aug 30 15:08:27 xserver influxd: fatal error: runtime: address space conflict
Aug 30 15:08:27 xserver influxd:
Aug 30 15:08:27 xserver influxd: runtime stack:
Aug 30 15:08:27 xserver influxd: runtime.throw(0xe01d8e, 0x1f)
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/panic.go:616 +0x81
Aug 30 15:08:27 xserver influxd: runtime.sysMap(0xc460a70000, 0x100000, 0x0, 0x13568d8)
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/mem_bsd.go:85 +0x1ef
Aug 30 15:08:27 xserver influxd: runtime.(*mheap).sysAlloc(0x133d640, 0x100000, 0x0)
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/malloc.go:470 +0xd4
Aug 30 15:08:27 xserver influxd: runtime.(*mheap).grow(0x133d640, 0x8, 0x0)
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/mheap.go:907 +0x60
Aug 30 15:08:27 xserver influxd: runtime.(*mheap).allocSpanLocked(0x133d640, 0x8, 0x13568e8, 0x800)
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/mheap.go:820 +0x2d1
Aug 30 15:08:27 xserver influxd: runtime.(*mheap).alloc_m(0x133d640, 0x8, 0x7fffffff0101, 0x42460a)
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/mheap.go:686 +0x118
Aug 30 15:08:27 xserver influxd: runtime.(*mheap).alloc.func1()
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/mheap.go:753 +0x4d
Aug 30 15:08:27 xserver influxd: runtime.(*mheap).alloc(0x133d640, 0x8, 0x1131010101, 0x7fffffffec08)
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/mheap.go:752 +0x8a
Aug 30 15:08:27 xserver influxd: runtime.largeAlloc(0x10000, 0x7fffffff0101, 0x454b7e)
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/malloc.go:826 +0x94
Aug 30 15:08:27 xserver influxd: runtime.mallocgc.func1()
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/malloc.go:721 +0x46
Aug 30 15:08:27 xserver influxd: runtime.systemstack(0x0)
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/asm_amd64.s:409 +0x79
Aug 30 15:08:27 xserver influxd: runtime.mstart()
Aug 30 15:08:27 xserver influxd:        /usr/local/go/src/runtime/proc.go:1175

**Comment by e-dard** [comment]
@AriSuutariST this might be a runtime bug, there is something similar [here](https://github.com/golang/go/issues/11886), though it's for a different architecture and Go version.

Unfortunately we don't support FreeBSD, but if you could reproduce this on Linux then we would certainly look into it.

**Comment by AriSuutariST** [comment]
The problem occurred with go runtime 1.10.2. I found out that there is 1.11 available and rebuild the 1.6.1 package with it.

Now the error is different, apparently there is a corrupt tsm file but influxd fails to recover from it:

Sep  5 12:43:11 xserver2 influxd: ts=2018-09-05T09:43:11.655889Z lvl=error msg="Cannot read corrupt tsm file, renaming" log_id=0AMHf1dG000 engine=tsm1 service=filestore path=/var/db/influxdb/data/xxxxxx/autogen/319/000005669-000000001.tsm id=15 error="can only read from tsm file"
Sep  5 12:43:11 xserver2 influxd: panic: runtime error: invalid memory address or nil pointer dereference
Sep  5 12:43:11 xserver2 influxd: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xb1b0c1]
Sep  5 12:43:11 xserver2 influxd:
Sep  5 12:43:11 xserver2 influxd: goroutine 1368 [running]:
Sep  5 12:43:11 xserver2 influxd: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*TSMReader).WithObserver(...)
Sep  5 12:43:11 xserver2 influxd:     /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.6.1/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:273
Sep  5 12:43:11 xserver2 influxd: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*FileStore).Open.func1(0xc049124680, 0xc02137d6e0, 0xf, 0xc034bd6cb8)
Sep  5 12:43:11 xserver2 influxd:     /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.6.1/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.go:535 +0xe91
Sep  5 12:43:11 xserver2 influxd: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*FileStore).Open
Sep  5 12:43:11 xserver2 influxd:     /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.6.1/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.go:510 +0x414

**Comment by e-dard** [comment]
@AriSuutariST nice. OK, this looks like a genuine bug. I'll triage accordingly.

**Comment by e-dard** [comment]
@AriSuutariST in the mean time, you could try moving the renamed TSM file out of the shard directory and seeing if that gets you started again.

**Comment by AriSuutariST** [comment]
It seems that the bad file was actually renamed before crash. Second startup succeeded, I have the database up again :-)

**Comment by e-dard** [comment]
Yeah I think the issue was the logic doesn't handle the case where a TSM file is renamed whilst it's opening up. Glad you're back up. We'll get a fix together.

**Comment by dnievas** [comment]
Hi.
We seem to be having the same issue

ts=2018-09-18T17:53:06.107192Z lvl=info msg="Failed to open shard" log_id=0AcSr6F0000 service=store trace_id=0AcSr6iW000 op_name=tsdb_open db_shard_id=13344 error="[shard 13344] cannot allocate memory"
ts=2018-09-18T17:53:06.107613Z lvl=info msg="Failed to open shard" log_id=0AcSr6F0000 service=store trace_id=0AcSr6iW000 op_name=tsdb_open db_shard_id=14733 error="[shard 14733] cannot allocate memory"
ts=2018-09-18T17:53:06.107834Z lvl=info msg="Failed to open shard" log_id=0AcSr6F0000 service=store trace_id=0AcSr6iW000 op_name=tsdb_open db_shard_id=16525 error="[shard 16525] cannot allocate memory"
ts=2018-09-18T17:53:06.108082Z lvl=info msg="Opened file" log_id=0AcSr6F0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/medalliaRP/15543/000000011-000000001.tsm id=3 duration=108.968ms
ts=2018-09-18T17:53:06.108219Z lvl=error msg="Cannot read corrupt tsm file, renaming" log_id=0AcSr6F0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/medalliaRP/15543/000000011-000000001.tsm id=3 error="cannot allocate memory"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xaf6214]

goroutine 77103 [running]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*TSMReader).WithObserver(...)
    /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:273
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*FileStore).Open.func1(0xc684a91110, 0xc554f72420, 0x3, 0xc61d4720b8)
    /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.go:535 +0xe74
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*FileStore).Open
    /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.go:510 +0x4a9
W0918 17:52:40.413782 193758 logging.cpp:91] RAW: Received signal SIGTERM from process 45216 of user 0; exiting

**Comment by benbjohnson** [comment]
Fix added: https://github.com/influxdata/influxdb/pull/10299
