### ISSUE TITLE
Can't use ABS with aggregations

### ISSUE THREAD

**Issue by Raniz85** [influxdata/influxdb#10259]
__System info:__ InfluxDB 1.6.2, Ubuntu 16.04.3

__Steps to reproduce:__

1. Have measurements with both negative and positive values
2. Run a query requesting the sum of the absolute values

__Expected behavior:__
`SUM(ABS("value"))` should return the sum of the absolute values of _value_. - e.g. if the values are -1, 3, -5 the result should be 9.

__Actual behavior:__
> ERR: expected field argument in sum()

__Additional information:__
I've tried with `MEAN(SUM("value"))` too and that gives a similar error.

**Comment by divankovic** [comment]
I think that influx doesn't support nesting functions with sum and mean, they must receive a field argument, as it says. Try using a nested query.

**Comment by e-dard** [comment]
We don't support these nested functions.

**Comment by semakamisli** [comment]
Are there any enhancement related with issue? I have similar problem using ABS with aggregation.
