### ISSUE TITLE
Unable to create retention policy for database admin user

### ISSUE THREAD

**Issue by ponsakthi** [influxdata/influxdb#10250]
__System info:__ Influx 1.6 OSS

__Steps to reproduce:__

1. Create admin user
2. Login as admin user using influx cli
3. Create database sampletest
4. Create sampletest admin user using following command `create user sampletestadmin with password '123123'`
5. Grant all privileges for sampeltestadmin on sampletest database using  `grant all on sampletest to sampletestadmin`
6.Logout from CLI and login as sampletestadmin user
7.Try creating retention policy on sampletestadmin database using `CREATE RETENTION POLICY "one_day_only" ON "sampletest" DURATION 1d REPLICATION 1`

__Expected behavior:__ Retention Policy should be created

__Actual behavior:__ An error is thrown `error authorizing query: sampletestadmin not authorized to execute statement 'CREATE RETENTION POLICY one_day_only ON sampletest DURATION 1d REPLICATION 1', requires admin privilege`

**Comment by e-dard** [comment]
This seems like an authorisation bug.
