### ISSUE TITLE
Query for InfluxDb to select a range of tag keys

### ISSUE THREAD

**Issue by deepSalva** [influxdata/influxdb#10268]
__Proposal:__ [Description of the feature]
Hi there, I am trying to select a range of values with a condition. My condition is select the values where the “key” of this values is in the range between Key>1 and key<200. My Influx database has 2 measurements, field “value” and a tag field “key”.

I need a query to select this values in my key range to visualize them into Grafana.

__Current behavior:__ [What currently happens]
I already try something like:

> select * from where “key” > ‘1’ and “key” < 200

but it is not working. but It is not working. Nevertheless I can select the values from one single key:

> select value from leuko where “key” = ‘2’

__Desired behavior:__ [What you would like to happen]
That is working. How could I do the same but just not for the values with the key ‘2’ but also for all the values between ‘2’ and ‘200’? Thanks

**Comment by tomekit** [comment]
I've came across similar issue, would it be possible to mention about this limitation on this page?
https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#the-where-clause

Not only the `between` range works, but simple range queries like: "tag" > 10 doesn't return any value as well.

My understanding is, that it is possible to filter on `time` and `value` fields using the range query.

I've actually checked and the range filtering works OK to me on non-indexed `field`, but it doesn't work on `tag`, which to me looks like an actually bug with `tag` filtering.

Using the Docker image of influxdb:
influxdb                                        latest              d1e103e42e17        10 days ago         258MB
