### ISSUE TITLE
Add flux support to InfluxDB OSS

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#10272]
High level tasks

* [x] Add `flux` package dependency to InfluxDB
* [x] implement `storage.Reader` adaptor over `services/Store`
* [x] add http endpoint to execute `flux` queries
    * [x] implement flux query service to handle HTTP queries and read via `storage.Reader`

## Questions

* HTTP handler path for flux queries?

**Comment by nathanielc** [comment]
Should be this `https://github.com/influxdata/platform/blob/master/http/swagger.yml#L950` which is a `/v2/query` endpoint
