### ISSUE TITLE
backup/restore with time boundaries

### ISSUE THREAD

**Issue by dawidpogorzelski** [influxdata/influxdb#10282]
__System info:__ 
influxdb version: 1.6.1
freebsd 11.2

__Steps to reproduce:__
take a backup with time boundaries:
```
influxd backup -portable -database mydb -start 2018-09-13T09:00:00Z -end 2018-09-13T09:50:00Z backup/
018/09/13 13:54:59 backing up metastore to backup/meta.00
2018/09/13 13:54:59 backing up db=mydb
2018/09/13 13:54:59 backing up db=mydb rp=somepolicy shard=6 to backup/mydb.somepolicy.00006.00 with boundaries start=2018-09-13T09:00:00Z, end=2018-09-13T09:50:00Z
2018/09/13 13:55:00 backup complete:
2018/09/13 13:55:00 	backup/20180913T135459Z.meta
2018/09/13 13:55:00 	backup/20180913T135459Z.s6.tar.gz
2018/09/13 13:55:00 	backup/20180913T135459Z.manifest
```
restore te backup:
```
influxd restore -db mydb -portable -newdb restoreddb backup/
```
__Expected behavior:__ 
I would expect to find only data points between time boundaries in `restoreddb`

__Actual behavior:__ 
I get data points that go up to some apparently random upper limit:
```
> use restoreddb
Using database restoreddb
> select bytes_recv from net order by desc limit 1
name: net
time                bytes_recv
----                ----------
1536841022000000000 133035567
```

**Comment by blankroom** [comment]
I have the same problem, and I found message like `backing up db=*** rp=*** shard=* to backupfilepath` in the backup output log. So I wonder if influxd backups in units of shards, which means influxd just backup the whole shard which has points in the given time range.
So, is that what exactly happens in influxdb?

**Comment by cnjax** [comment]
influxd backup -portable  -db history -start 2018-12-26T23:59:56Z  -end 2018-12-27T00:00:00Z 4seconds
and restore

Same problem here.
----                           ------ ---------- ---------- -----
2018-12-26T17:23:04.000549021Z 10     true       2194966    0.814
2018-12-26T17:23:04.000592128Z 10.1   true       2194956    0.814
2018-12-26T17:23:04.00061132Z  72.1   true       2194957    0.814
2018-12-26T17:23:04.000640765Z 68.5   true       2194958    0.814
2018-12-26T17:23:04.000644959Z 38.3   true       2194953    0.814
2018-12-26T17:23:04.000657911Z 305.4  true       2194946    0.814
2018-12-26T17:23:04.000689973Z 47.4   true       2194948    0.814
2018-12-26T17:23:04.000713398Z 45.8   true       2194963    0.814
