### ISSUE TITLE
Make default InfluxDB client support custom HTTP endpoints

### ISSUE THREAD

**Issue by mattiasb** [influxdata/influxdb#10294]
__Proposal:__

Make it possible to connect to an InfluxDB instance running behind a reverse proxy with a custom subpath / endpoint with the default InfluxDB client `influx`.

__Current behavior:__

I have InfluxDB, Grafana and nginx running as docker containers in a test VM at `192.168.122.26`.
InfluxDB is exposed at `192.168.122.26/influxdb/`

I can issue a ping command with `curl` but I can't log in using `influx`:
```shell
$ curl -sL -I l http://192.168.122.26/influxdb/ping
HTTP/1.1 204 No Content
Server: nginx/1.14.0
Date: Thu, 20 Sep 2018 11:21:11 GMT
Content-Type: application/json
Connection: keep-alive
Request-Id: 4714b565-bcc7-11e8-8009-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.5.4
X-Request-Id: 4714b565-bcc7-11e8-8009-000000000000

$ influx -host 192.168.122.26/influxdb -port 80
Failed to connect to http://192.168.122.26%2Finfluxdb: parse http://192.168.122.26%2Finfluxdb/ping: invalid URL escape "%2F"
Please check your connection settings and ensure 'influxd' is running.
```

__Desired behavior:__

I'd like to be able to connect to a custom endpoint with `influx`. :)

__Use case:__

I'm just getting started with InfluxDB but I'd like to be able to test the database with `influx` as the server is set up now. I might go back to just exposing the server directly via its default port and no endpoint instead if necessary.

**Comment by jimis** [comment]
@stale I'm still watching this and in need of this. AFAIK there is no workaround, so it's impossible to use the `influx` CLI to connect to such endpoints.

**Comment by jimis** [comment]
So every few months the stale bot tries to auto-close valid and accepted issues, and we have to keep spamming them in order to keep them open...

**Comment by dontsovcmc** [comment]
I also have topic starter's problem!
I run influxdb in docker-compose as described here: https://towardsdatascience.com/get-system-metrics-for-5-min-with-docker-telegraf-influxdb-and-grafana-97cfd957f0ac
I setup nginx as reverse proxy for ssl connection and checking link failed!
```
influx -ssl -host myhost.com/influxdb -port 443
Failed to connect to https://myhost.com%2Finfluxdb:443
Please check your connection settings and ensure 'influxd' is running.
```
It spends a lot of time for understanding, that it works!
```
curl -sL -I l https://myhost.com/influxdb/ping
HTTP/1.1 204 No Content
Server: nginx
Date: Sun, 22 Dec 2019 22:23:34 GMT
Content-Type: application/json
Connection: keep-alive
Request-Id: b11af176-2509-11ea-1111-0242ac181111
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.9
X-Request-Id: b11af176-2509-11ea-1111-0242ac181111
X-Frame-Options: SAMEORIGIN
```
