### ISSUE TITLE
Sensitive Data Exposure Vulnerability

### ISSUE THREAD

**Issue by dp1140a** [influxdata/influxdb#10292]
System info:
InfluxDB v1.6.2

Steps to reproduce:

Install InfluxDB v1.6.2
Create an admin-user
Enable authentication and restart Influxdb
Create non-admin user for example “myuser"
Create database for example called “granted”
Create database for example called “notgranted”
Create continuous query to database “notgranted”
Grant read permissions for “myuser” to “granted” database (GRANT READ ON granted TO myuser)
Login to influxdb using “myuser” account
Query continuous queries (show continuous queries) -> result shows continuous query inside notgranted db.

**Comment by davidby-influx** [comment]
<pre>&gt; create USER myuser with password &apos;myuser&apos;
&gt; create database granted
&gt; create database notgranted
&gt; use notgranted
&gt; INSERT foo,t1=&quot;babble&quot; v=3
&gt; CREATE CONTINUOUS QUERY fooq ON notgranted BEGIN SELECT COUNT(*) INTO baz FROM foo GROUP BY time(1d) END
&gt; GRANT READ ON granted TO myuser
&gt; exit
&gt; influx -username admin -password admin
Connected to http://localhost:8086 version unknown
InfluxDB shell version: unknown
&gt; show users
user     admin
----     -----
test-bob false
admin    true
myuser   false
&gt; show grants for myuser
database privilege
-------- ---------
granted  READ
&gt; exit
&gt; influx -username myuser -password myuser
Connected to http://localhost:8086 version unknown
InfluxDB shell version: unknown
&gt; use granted
Using database granted
&gt; show continuous queries
name: _internal
name query
---- -----

name: TestData
name query
---- -----

name: telegraf
name query
---- -----

name: quick
name query
---- -----

name: cq_test
name query
---- -----

name: test_rp
name query
---- -----

name: granted
name query
---- -----

name: notgranted
name query
---- -----
fooq CREATE CONTINUOUS QUERY fooq ON notgranted BEGIN SELECT count(*) INTO notgranted.autogen.baz FROM notgranted.autogen.foo GROUP BY time(1d) END
&gt; </pre>
