### ISSUE TITLE
Drop Measurement very slow

### ISSUE THREAD

**Issue by mdollemore** [influxdata/influxdb#10306]
InfluxDB shell version: 1.6.3 on Centos Linux 7

DB with 200k measurements

Drop measurement using the following command takes anything between 30-50secs to complete

drop measurement "measurement name"

I have 5000+ measurements that need to be dropped, this is just not possible with the present performance.

Debug info below taken during a drop measurement operation;-

[iostat.txt](https://github.com/influxdata/influxdb/files/2419046/iostat.txt)
[vars.txt](https://github.com/influxdata/influxdb/files/2419048/vars.txt)
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/2419049/profiles.tar.gz)

**Comment by nicolas17** [comment]
How do you have 200k measurements?! Don't you mean series?

**Comment by ziflyingyo** [comment]
I'm also confused why drop measurement need so much time.

**Comment by mdollemore** [comment]
Yes its 200k measurements.  Data is written by a third party app in graphite format and not tags or fields are defined. Hence each metric recorded is a measurement, I know this is not ideal, however there is a scripted dashboard that dynamically builds a view for each host based on the available measurements. If I was to add tags/fields then this script would require re-writing.  

Even with 200k measurements I am at a loss as to why dropping a measurement should take so long?

**Comment by rbetts** [comment]
Dropping a measurement requires a full re-compaction of the shard(s) containing that measurement. It isn't expected to be a fast operation as it requires a rewrite of large portions of the persisted database. 

I understand your frustration here but we don't have plans prioritized to improve `drop measurement` performance at the moment. 

Options here are to wait for the retention service, or scripting the `drop measurement` to run over a long period of time. I suppose, alternately, if you wanted to write code to filter a measurement as an offline re-write of the database, you could start here (https://github.com/influxdata/influxdb/tree/master/cmd/influx_tools) .. but that seems like a last-ditch effort.

**Comment by nicolas17** [comment]
Isn't the re-compaction done asynchronously in the background? It shouldn't be what's making the drop command itself take so long.

**Comment by hackery** [comment]
We're encountering the same problem - 200k measurements we need to drop, which looks like about 45 days at 20s per DROP.
Yes, we _should not_ have this many measurements - they were ingested in error (names included docker instance IDs which of course ballooned very quickly as containers were recycled) hence the need to remove them.
