### ISSUE TITLE
Incorrect absolute time with grouping causes a huge load

### ISSUE THREAD

**Issue by azhurbilo** [influxdata/influxdb#10311]
__System info:__ 
- reproduced both in Influxdb 1.6.1 and 1.5.2
- linux ubuntu 16.04

__Steps to reproduce:__

1. have measurement with metrics **only for several days**
2. run query with "GROUP BY" and absolute time not a nanoseconds epoch time (in seconds)
```
EXPLAIN ANALYZE SELECT mean("usage_irq") FROM "telegraf_infra"."autogen"."cpu" WHERE time > 1537893600 GROUP BY time(1m)
```
> .
└── select
├── execution_time: 1m25.407921961s
├── planning_time: 145.665392ms
├── total_time: 1m25.553587353s

it's the same if choose big time range like `WHERE time > now() - 9999d`

__Expected behavior:__ 
I am not sure but may be Influxdb should *warn* that this time format incorrect according
https://docs.influxdata.com/influxdb/v1.6/query_language/data_exploration/#epoch-time

or query engine should understand that you need limit grouping only for existed measurement (several days) not a time range since 1 January 1970

Ideally it will be great to limit somehow Globally that I have all metrics **only > 2017.01.01** for example
and nor any Adhoc query by other users nor time range variable from Grafana http://docs.grafana.org/reference/templating/#the-timefilter-or-timefilter-variable
**don't crash** influxdb server

__Actual behavior:__ 
influxdb query engine try to group metrics since 1 January 1970
without any warn (sometimes crash/panic influxdb cause all Memory HEAP consumed)

__Additional info:__ 

```
EXPLAIN ANALYZE SELECT mean("usage_irq") FROM "telegraf_infra"."autogen"."cpu" WHERE time > now() - 1h GROUP BY time(1m)

└── select
├── execution_time: 6.338811ms
├── planning_time: 1.065231ms
├── total_time: 7.404042ms


EXPLAIN ANALYZE SELECT mean("usage_irq") FROM "telegraf_infra"."autogen"."cpu" WHERE time > 1537893600 GROUP BY time(1m)

.
└── select
├── execution_time: 1m25.407921961s
├── planning_time: 145.665392ms
├── total_time: 1m25.553587353s

```

![sreen_9_27_18__11_09_am](https://user-images.githubusercontent.com/6387460/46135998-46278480-c24f-11e8-842a-5f30c71158da.jpg)

**Comment by dgnorton** [comment]
@azhurbilo That timestamp format is correct so InfluxDB can't warn that it isn't. Crashing or OOMing is an issue though. We're working on better query resource management / limits in 2.0 but this particular case isn't something we're currently planning to address in 1.x.
