### ISSUE TITLE
Verify _f and _m work in InfluxDB OSS for Flux integration

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#10319]

**Comment by aanthony1243** [comment]
@nathanielc   I think this was fixed yesterday by https://github.com/influxdata/influxdb/pull/10360, not sure what you were intending to verify.

**Comment by stuartcarnie** [comment]
@aanthony1243 I asked @nathanielc to create this so I could verify it was working, as Jeff ran into some issues when migrating code to platform.

I too have verified it is working 👍
