### ISSUE TITLE
when using batchPoints to write records into influxdb,only series added but no fields are recorded

### ISSUE THREAD

**Issue by yashangyoukecai** [influxdata/influxdb#10314]
we are using java api add some click issues,but after batchpoints insert ,only see series in database ,not any fields are records. use count,sum only return nothing.why does this happen?we checked the point builder,after using "builder.hasFields()",it returns true

**Comment by dgnorton** [comment]
@yashangyoukecai are you using the [influxdata/influxdb-java](https://github.com/influxdata/influxdb-java) library? If so, please create an issue there. Or, if you're unsure if this is a bug or a usage problem, post as a question on the [InfluxData community site](https://github.com/influxdata/influxdb-java).
