### ISSUE TITLE
Influx is running out of memory

### ISSUE THREAD

**Issue by scotloach** [influxdata/influxdb#10324]
__System info:__ 
InfluxDB 1.6.3 on Fedora using tsi indexing
This happened on older versions as well.

__Steps to reproduce:__

I have two InfluxDB instances which normally uses a floor of about 50GB of RAM during runtime.  As it runs, the heap is normally between 50-100GB of RAM.  This seems like a lot; there are lots of queries running but few live beyond a few seconds, normally SHOW QUERIES is empty.  Occasionally the memory spikes up much higher; this usually doesn't show up in the heap stats, it happens much faster and just runs the server out of memory.  In our environment this results in an OOM kill of the service.

__Expected behavior:__
I don't expect InfluxDB to use this much variable memory, or I expect some way to control it.  At the least I should have a way to diagnose what uses all that memory.

__Actual behavior:__ 

__Additional info:__ 
I have detailed metrics on the heap, it's not a gradual increase, it happens so fast it doesn't show up in those stats.  I've taken memory profiles within 10s before this happens and it doesn't show a high heap utilization.

**Comment by dgnorton** [comment]
@scotloach can you attach the heap metrics and memory profiles you collected to the issue? Thanks.

**Comment by scotloach** [comment]
I don't have the profiles handy right now; however when I looked at them they didn't show the high memory use, it seems to happen all at once.  I'm continuing to investigate and trying to figure out how to reproduce it.  I'm starting to think it's related to querying shards with high series counts (using TSI indexes).

**Comment by russorat** [comment]
closing due to lack of response.
