### ISSUE TITLE
SELECT INTO: Continue after error: "points beyond retention policy dropped"

### ISSUE THREAD

**Issue by kevinhogan111** [influxdata/influxdb#10330]
__Proposal:__ [Description of the feature]

__Current behavior:__ [What currently happens]

In a case like this:
```
> USE restored_kpi 
Using database restored_kpi 
> SELECT * INTO kpi..:MEASUREMENT FROM /.*/ GROUP BY * 
ERR: partial write: points beyond retention policy dropped=270

```
The ERR causes the process to stop, it does not write beyond where the problem is found. 

__Desired behavior:__ [What you would like to happen]

Log the error, but continue through the remaining "wildcard" options.

__Use case:__ [Why is this important (helps with prioritizing requests)]

This would prevent the need for the workaround where you increase the retention policy time, do the restore, then switch it back.

Requests may be closed if we're not actively planning to work on them.

**Comment by jefferyKuhn** [comment]
We're also encountering this issue, and would really like this "feature" to be implemented. It can easily be a config option in the conf file, but ideally, I don't see why you wouldn't continue with the remaining data even when this error occurs, at least this specific error, "points beyond retention policy dropped"

**Comment by eaglerainbow** [comment]
👍 
This error message makes you simply speechless if you just entered a simple
```
SELECT * INTO xyz_clean FROM xyz WHERE tagkey !~ /abc_.*/
```
