### ISSUE TITLE
Can influxDB use multiple SSD

### ISSUE THREAD

**Issue by ziflyingyo** [influxdata/influxdb#10340]
AS we have 12 SSD, but one ssd only 400G, so I'm confused whether influxDB can use multiple SSD?

**Comment by dgnorton** [comment]
@ziflyingyo the `WAL` and `data` can be configured to write to different directories but `data` can't be configured for multiple locations. Please post usage questions to the [InfluxData community site](https://community.influxdata.com/). GitHub issues are for bugs and feature requests.
