### ISSUE TITLE
runtime error with specific tag value regex filters 

### ISSUE THREAD

**Issue by kalidasya** [influxdata/influxdb#10354]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Centos 7.2 Influxdb 1.6.3
__Steps to reproduce:__
Following queries give `[panic:runtime error: invalid memory address or nil pointer dereference]` error:
Both cases should return data:
> SHOW TAG VALUES FROM load_longterm WITH KEY = host WHERE host =~ /^5.*/ LIMIT 1
> SHOW TAG VALUES FROM load_longterm WITH KEY = host WHERE host =~ /^.*st/  LIMIT 1

These queries however work fine:
> SHOW TAG VALUES FROM load_longterm WITH KEY = host WHERE host =~ /^.*/  LIMIT 1  --> has data
> SHOW TAG VALUES FROM load_longterm WITH KEY = host WHERE host =~ /^s.*/  LIMIT 1  --> has no data but its expected

__Additional info:__ [Include gist of relevant config, logs, etc.]

It is somehow related to the https://github.com/influxdata/influxdb/issues/9548 but it is on a newer version. I tried to get a trace but I failed, if someone can help me I can attach it as well. This is what I tried to do:
* edit `/etc/default/influxdb` and add `INFLUXD_OPTS="GOTRACEBACK=crash"`
* edit service file and add `Environment=GOTRACEBACK=crash` 
both cases I see either in the process' environ or in the path with `ps` the setting, but either case there is no trace anywhere (journal, /var/log/influxdb/influxdb.log, /var/log/messages) when I hit the error in the influx command line tool

The issue seem to happen with select filters as well, but it is always with regular expressions.

**Comment by dgnorton** [comment]
@kalidasya can you post the stack trace? Thanks.

**Comment by dgnorton** [comment]
@kalidasya my bad. Just noticed you said the stack trace wasn't in the log. Can you attach the log to the issue?

**Comment by kalidasya** [comment]
@dgnorton there is nothing in the log, probably I have some settings wrong, will try to set the query log level I remember setting it to warning but what else?

**Comment by joshuajoh** [comment]
Having the same issue with queries that have regular expressions.

Please let me know what information can be provided to help with this.

Red Hat Enterprise Linux Server release 6.4 (Santiago)
InfluxDB 1.6.3

`ts=2018-10-11T19:14:29.544135Z lvl=error msg="SELECT non_negative_derivative(first(VALUE), 5m) FROM myDB.autogen.myMEA WHERE (t3 = 'myApplication' AND t4 = 'API' AND t5 =~ /^FlowController$/ AND monitor =~ /_hist_bucket$/) AND time >= 427325h GROUP BY time(5m), t5, t6, t7, monitor, metric [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 1664453018 [running]:\nruntime/debug.Stack(0xc77daa6ae0, 0xc429228c60, 0x104)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/influxdata/influxdb/query.(*Executor).recover(0xc420042f60, 0xc77daa6ae0, 0xc591079f80)\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:394 +0xaf\npanic(0xcd0740, 0x1354d50)\n\t/usr/local/go/src/runtime/panic.go:502 +0x229\ngithub.com/influxdata/influxdb/tsdb.SeriesIDIterators.Close(0xc576aa0e00, 0x19, 0x20, 0xcd5840, 0x7fc1e6d25008)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:277 +0x66\ngithub.com/influxdata/influxdb/tsdb.(*seriesIDMergeIterator).Close(0xc76e985260, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:453 +0x41\ngithub.com/influxdata/influxdb/tsdb.(*seriesIDIntersectIterator).Close(0xc59055d090, 0x50, 0x50)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:528 +0x68\ngithub.com/influxdata/influxdb/tsdb.(*filterUndeletedSeriesIDIterator).Close(0xc57b0cfac0, 0xc4200bd6d0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:366 +0x34\npanic(0xcd0740, 0x1354d50)\n\t/usr/local/go/src/runtime/panic.go:502 +0x229\ngithub.com/influxdata/influxdb/tsdb.(*seriesIDMergeIterator).Next(0xc76e985260, 0x613fa, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:466 +0xd7\ngithub.com/influxdata/influxdb/tsdb.(*seriesIDIntersectIterator).Next(0xc59055d090, 0xc5efa677e8, 0x409113, 0xd425a0, 0xc57b0cfb00, 0x9066ef)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:544 +0x1d8\ngithub.com/influxdata/influxdb/tsdb.(*filterUndeletedSeriesIDIterator).Next(0xc57b0cfac0, 0x1, 0x1, 0xc4200bd6d0, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:371 +0x38\ngithub.com/influxdata/influxdb/tsdb.IndexSet.TagSets(0xc7a4a0d310, 0x1, 0x1, 0xc4200bd6d0, 0x0, 0x0, 0x0, 0xc4200bd6d0, 0xc4c59dec00, 0x3, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:2541 +0x2a9\ngithub.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createCallIterator(0xc443a265a0, 0xea8360, 0xc464f54e10, 0xc490577755, 0x3, 0xc464f54f30, 0xea63a0, 0xc464f54f30, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2353 +0x269\ngithub.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).CreateIterator(0xc443a265a0, 0xea8360, 0xc464f54e10, 0xc490577755, 0x3, 0xea63a0, 0xc464f54f30, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2314 +0x3ad\ngithub.com/influxdata/influxdb/tsdb.(*Shard).CreateIterator(0xc4ce1cbb00, 0xea8360, 0xc464f54e10, 0xc445a9a3c0, 0xea63a0, 0xc464f54f30, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/shard.go:842 +0x13d\ngithub.com/influxdata/influxdb/tsdb.Shards.CreateIterator(0xc43403d9b0, 0x2, 0x2, 0xea8360, 0xc464f54e10, 0xc445a9a3c0, 0xea63a0, 0xc464f54f30, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/shard.go:1286 +0x155\ngithub.com/influxdata/influxdb/coordinator.(*LocalShardMapping).CreateIterator(0xc7540f93c0, 0xea8360, 0xc464f54e10, 0xc445a9a3c0, 0xea63a0, 0xc464f54f30, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/coordinator/shard_mapper.go:208 +0x45d\ngithub.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator.func1(0xc5efa69db8, 0xea8360, 0xc464f54e10, 0xc5efa68be0, 0xc5efa68b98, 0xc464f54f30, 0xc584cc14b8, 0x8)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:581 +0x139\ngithub.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator(0xc4e1b2bdb8, 0xea8360, 0xc464f54e10, 0xc464f54f30, 0xea63a0, 0xc464f54f30, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:605 +0xd5\ngithub.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator.func1(0xc464f54f30, 0xea8360, 0xc464f54e10, 0xc4e1b2bdb8, 0xc4e1b2b298, 0x0, 0xc5fca2a000, 0x7fbcba208e10, 0xc570895260)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:513 +0xee\ngithub.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator(0xc5efa69db8, 0xea8360, 0xc464f54e10, 0xc464f54f30, 0xc4cf7ccc00, 0x1, 0x0, 0xc4e1b2be00)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:557 +0xdad\ngithub.com/influxdata/influxdb/query.buildExprIterator(0xea8360, 0xc464f54e10, 0xea63a0, 0xc464f54f30, 0x7fbcc0be43b0, 0xc7540f93c0, 0xc43403d9d0, 0x1, 0x1, 0xea63a0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:154 +0x1f4\ngithub.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator(0xc4e1b2ce38, 0xea8360, 0xc464f54e10, 0xc464f54f60, 0x411ed9, 0xc52c0a8b00, 0x8, 0x8)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:266 +0x12bc\ngithub.com/influxdata/influxdb/query.buildExprIterator(0xea8360, 0xc464f54e10, 0xea63a0, 0xc464f54f60, 0x7fbcc0be43b0, 0xc7540f93c0, 0xc43403d9d0, 0x1, 0x1, 0xea63a0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:154 +0x1f4\ngithub.com/influxdata/influxdb/query.buildFieldIterator(0xea8360, 0xc464f54e10, 0xea63a0, 0xc464f54f60, 0x7fbcc0be43b0, 0xc7540f93c0, 0xc43403d9d0, 0x1, 0x1, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:851 +0x45f\ngithub.com/influxdata/influxdb/query.buildCursor(0xea8360, 0xc464f54e10, 0xc43403a900, 0x7fbcc0be43b0, 0xc7540f93c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:736 +0xcca\ngithub.com/influxdata/influxdb/query.(*preparedStatement).Select(0xc585bf8160, 0xea8360, 0xc464f54e10, 0x7fbcba208e10, 0xc570895260, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:119 +0x180\ngithub.com/influxdata/influxdb/query.Select(0xea8560, 0xc686ff80c0, 0xc43403a600, 0xe97d60, 0xc4202d1260, 0x7fbcba208e10, 0xc570895260, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:96 +0xf7\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).createIterators(0xc42026ca80, 0xea8560, 0xc686ff80c0, 0xc43403a600, 0xc4560dbdce, 0x9, 0x0, 0x0, 0x7fbcba208e10, 0xc570895260, ...)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:635 +0x101\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc42026ca80, 0xc43403a600, 0xc686ff80c0, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:540 +0x99\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc42026ca80, 0xea8f60, 0xc43403a600, 0xc686ff80c0, 0x1, 0x1)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:62 +0x23c6\ngithub.com/influxdata/influxdb/query.(*Executor).executeQuery(0xc420042f60, 0xc77daa6ae0, 0xc4560dbdce, 0x9, 0x0, 0x0, 0x7fbcba208e10, 0xc570895260, 0x2710, 0x1, ...)\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:334 +0xb72\ncreated by github.com/influxdata/influxdb/query.(*Executor).ExecuteQuery\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:236 +0xc9\n" log_id=0B2hy4xl000 service=query`

**Comment by joshuajoh** [comment]
Had a chance to look at this and it seems to be triggered on regular expression usage when accessing shards older than the current - 1.

Please let me know if anything can be provided to help with investigation.

```
# Queries:

> select first("STATUS") FROM "myMeasurement" WHERE "monitor" =~ /myTag001/ AND time > '2018-10-29T00:00:00Z'
name: myMeasurement
time                     first
----                     -----
2018-10-29T00:01:35.636Z 0
> select first("STATUS") FROM "myMeasurement" WHERE "monitor" =~ /myTag001/ AND time > '2018-10-22T00:00:00Z'
name: myMeasurement
time                     first
----                     -----
2018-10-22T00:03:15.784Z 0
> select first("STATUS") FROM "myMeasurement" WHERE "monitor" =~ /myTag001/ AND time > '2018-10-15T00:00:00Z'
ERR: SELECT first(STATUS) FROM myDatabase.autogen.myMeasurement WHERE monitor =~ /myTag001/ AND time > '2018-10-15T00:00:00Z' [panic:runtime error: invalid memory address or nil pointer dereference]
>
>  select first("STATUS") FROM "myMeasurement" WHERE "monitor" = 'myTag001' AND time > '2018-10-15T00:00:00Z'
name: myMeasurement
time                     first
----                     -----
2018-10-15T00:02:20.582Z 0
>  select first("STATUS") FROM "myMeasurement" WHERE "monitor" = 'myTag001' AND time > '2018-10-08T00:00:00Z'
name: myMeasurement
time                     first
----                     -----
2018-10-08T00:01:15.726Z 0
>


# Shards:

8788 myDatabase autogen          8788        2018-09-24T00:00:00Z 2018-10-01T00:00:00Z 2018-10-01T00:00:00Z
8977 myDatabase autogen          8977        2018-10-01T00:00:00Z 2018-10-08T00:00:00Z 2018-10-08T00:00:00Z
9144 myDatabase autogen          9144        2018-10-08T00:00:00Z 2018-10-15T00:00:00Z 2018-10-15T00:00:00Z
9330 myDatabase autogen          9330        2018-10-15T00:00:00Z 2018-10-22T00:00:00Z 2018-10-22T00:00:00Z
9519 myDatabase autogen          9519        2018-10-22T00:00:00Z 2018-10-29T00:00:00Z 2018-10-29T00:00:00Z
9708 myDatabase autogen          9708        2018-10-29T00:00:00Z 2018-11-05T00:00:00Z 2018-11-05T00:00:00Z
```

**Comment by srinivasrk** [comment]
Same issue here when using regex

**Comment by joshuajoh** [comment]
This is working now in 1.6.4

For 1.6.3, anchoring the regexp with ^ $ can help in some scenarios like Grafana template variables.

**Comment by e-dard** [comment]
@kalidasya  can you confirm running a version `>= 1.6.4` resolves this for you too?

**Comment by kalidasya** [comment]
@e-dard will try to check it in the coming weeks, unfortunately we are in a release period and I cannot upgrade the influx machine, so I have to set up a dev environment which is not easy because... did I mention release period? :)

**Comment by kalidasya** [comment]
@e-dard sorry for the late response, I finally updated influxdb to 1.7.6 and the issue is resolved. My original problem is gone and also the test queries are working. Thanks!
