### ISSUE TITLE
InfluxDB 1.6.3 journalctl logs only contains INFO level. WARN/ERROR logs are not showing up

### ISSUE THREAD

**Issue by maazkhan** [influxdata/influxdb#10365]
We are running two separate versions of InfluxDB 1.2.2 and 1.6.3

The problem we are seeing with 1.6.3 is that WARN/ERROR messages are not showing up when running the command. We only see INFO
"journalctl -fu influxdb.service"

But we see error/warn/info/ logs coming through in 1.2.2

**Comment by dgnorton** [comment]
@maazkhan is 1.6.3 running with the default logging level? If it's using a config file, it will be set in:
```
[logging]
  level = "info"
```

**Comment by maazkhan** [comment]
@dgnorton Below is the logging section in the config file. My understanding is that the default "info" level should also log error/warn since they are high priority then info.

```
[logging]
  # Determines which log encoder to use for logs. Available options
  # are auto, logfmt, and json. auto will use a more a more user-friendly
  # output format if the output terminal is a TTY, but the format is not as
  # easily machine-readable. When the output is a non-TTY, auto will use
  # logfmt.
  # format = "auto"

  # Determines which level of logs will be emitted. The available levels
  # are error, warn, info, and debug. Logs that are equal to or above the
  # specified level will be emitted.
  # level = "info"

  # Suppresses the logo output that is printed when the program is started.
  # The logo is always suppressed if STDOUT is not a TTY.
  # suppress-logo = false
```
