### ISSUE TITLE
Question: SELECT values from measurements except if they match regex

### ISSUE THREAD

**Issue by roycepope** [influxdata/influxdb#10378]
I am trying to run a query but am not sure if its possible. Hoping someone here can tell me how do it or explain why it can't be done. 

What I need is a way to SELECT values from measurements except if they match certain IPs that I specify. I have a logparser input that watches my apache logs. I also have a script that checks the status of my website periodically. This results in my apache logs flooded with messages from my own IP addresses.

## Wanted Query
`SELECT "clientip" FROM "apache_access_log" WHERE "clientip" != "127.0.0.1" AND "host" =~ "web01"  AND "response" =~ "200" AND $timeFilter`

Can a query like this be constructed?

**Comment by dgnorton** [comment]
Change the double quotes to single quotes around the IP address: `WHERE "clientip" != '127.0.0.1'`. Double quotes indicate an identifier (e.g., db name, tag key, field name). Single quotes indicate a string value.

The best place to ask usage questions is on the [InfluxData community site](https://community.influxdata.com/).
