### ISSUE TITLE
Local Storage to Docker Volume?

### ISSUE THREAD

**Issue by Nefariis** [influxdata/influxdb#10370]
Sooo I inherited a server with docker/influx installed and I got a request to upgrade to the latest influx.

I noticed that the guy before me has the influx data pointed to local storage on the same server - what I would like to do is take the influx data that's on the local storage and make it a docker volume where it can be regularly backed up with the other docker volumes.

In the meantime I upgraded influx normally, pointing it to the same local storage - but is it possible to turn the local storage into a docker volume? Maybe mount it inside the container first and then sync that with a docker volume? 

Any help would be greatly appreciated - thanks guys

**Comment by dgnorton** [comment]
@Nefariis Welcome to InfluxDB. Since this is a usage question, and not a bug or feature request, can you post it on the [InfluxData community site](https://community.influxdata.com/)? Thanks.
