### ISSUE TITLE
Influxd remote restore: error updating meta: Response did not contain the proper header tag.

### ISSUE THREAD

**Issue by egee-irl** [influxdata/influxdb#10386]
Both hosts (local and remote) are using the InfluxDB 1.6 Docker container.

__Steps to reproduce:__

1. Deploy an InfluxDB container on a remote instance
2. Deploy an InfluxDB container on your local machine
3. Create a backup on your local machine
4. Restore your backup to the remote instance: `influxd restore -portable -host $hostmachine:$hostport $(pwd)`

__Expected behavior:__ Backup is restored on the remote instance

__Actual behavior:__ The following error occurs:

```
2018/10/18 07:45:41 error updating meta: Response did not contain the proper header tag.
restore: Response did not contain the proper header tag.
```

**Comment by egee-irl** [comment]
Configuration issue on my end.

**Comment by jclementes-uga** [comment]
What was the configuration issue? I have the same problem. PLS

**Comment by ConstantMown** [comment]
For me it was one line that was commented in influxd.conf

```
# Bind address to use for the RPC service for backup and restore.
# bind-address = "127.0.0.1:8088"
```
I removed "# " from the "bind-address" line and replaced the 127.0.0.1 address with hostname.
In my environment hostname is resolved to the correct IP address, YMMV.
Restarted influxd and after that I could restore remotely.

Why I left this comment? [I wanted to unfrak this error message](https://www.reddit.com/r/ProgrammerHumor/comments/aehus6/the_moment_when_you_know_you_are_fucked/)

**Comment by hanssens** [comment]
For what it's worth, solution was pretty much the same for me. In my case I was using a Docker container, in specific the [Docker Compose sandbox](https://github.com/influxdata/sandbox), where port `8088` needed to be opened manually for backup/restore. The default port 8086 for the API was already OK.
