### ISSUE TITLE
Parent query scan all shards even if subquery has time interval

### ISSUE THREAD

**Issue by julienmathevet** [influxdata/influxdb#10380]
__System info:__ [1.6.3, centos]

__Steps to reproduce:__

1. `explain SELECT count(tot) FROM (SELECT count("foo") as tot FROM "data" WHERE $timeFilter GROUP BY "bar" fill(null)) WHERE tot != 0`

__Expected behavior:__ scan only given interval

__Actual behavior:__ It will scan all shard and in my case do an oom killed

__Additional info:__ workaround is to filter parent query too, eg: 
`
`explain SELECT count(tot) FROM (SELECT count("foo") as tot FROM "data" WHERE $timeFilter  GROUP BY "bar" fill(null)) WHERE  $timeFilter AND tot != 0`
`

**Comment by krokodilerian** [comment]
The issue exists also on 1.7.2.

**Comment by krokodilerian** [comment]
The issue still exists in 1.7.7 (latest current release).

**Comment by krokodilerian** [comment]
The issue still exists, current stable 1.7.8.
