### ISSUE TITLE
mean() returns incorrect results

### ISSUE THREAD

**Issue by scotty595** [influxdata/influxdb#10406]
__System info:__ X-Influxdb-Version: 1.6.4

__Steps to reproduce:__

1. Collect data and save into InfluxDB, Raw data example (All data points are exactly equal):
![data_is_the_same](https://user-images.githubusercontent.com/19480825/47428475-21d3af00-d7df-11e8-81e0-439d580f7f5d.png)![raw_data](https://user-images.githubusercontent.com/19480825/47428393-d4efd880-d7de-11e8-9635-7f13463e644c.png)

2. Query data using mean() 
`SELECT mean("value") AS "mean_value" FROM "database"."autogen"."measurement" WHERE time > now() - 1h `

3. Mean is inaccurate
![mean](https://user-images.githubusercontent.com/19480825/47428531-46c82200-d7df-11e8-85e5-7f743ea8be5d.png)

__Expected behavior:__ Mean should be calculated correctly

__Actual behavior:__ Mean is incorrectly calculated

**Comment by dgnorton** [comment]
@scotty595 InfluxDB supports storing signed 64-bit integers. The values shown in the issue above are close to the max possible value so I suspect it's overflowing when `mean` sums them.

https://docs.influxdata.com/influxdb/v1.6/troubleshooting/frequently-asked-questions/#what-are-the-minimum-and-maximum-integers-that-influxdb-can-store

**Comment by timhallinflux** [comment]
You might try this as a workaround:
```
SELECT mean("value")*10000 AS "mean_value" FROM (SELECT "value"/10000 AS "value" from "database"."autogen"."measurement" WHERE time > now()-1h) ```

**Comment by forcie** [comment]
This is obviously still an issue. I didn't want to believe mean() was broken at first, I assumed I was doing something wrong, and spent so much time trying to correct something I was not doing wrong until I found this issue.
![image](https://user-images.githubusercontent.com/1842198/194695855-29514e73-831a-4e07-b425-2659cbe75c7b.png)
