### ISSUE TITLE
go modules checksum mismatch for tag v1.6.4

### ISSUE THREAD

**Issue by ekle** [influxdata/influxdb#10405]
go modules saves checksums of the used package versions.
this checksum changed for the git tag `v1.6.4` breaking go modules build.
```
go: verifying github.com/influxdata/influxdb@v1.6.4: checksum mismatch
	downloaded: h1:K8wPlkrP02HzHTJbbUQQ1CZ2Hw6LtpG4xbNEgnlhMZU=
	go.sum:     h1:r+X/d8WTO9ZiCOyXBBMVKiwn+LNGZiB4z4C6axyYpIg=
```

**Comment by dgnorton** [comment]
@ekle Sorry about that. We moved the tag. You can manually edit `go.sum` to use the new checksum and you may need to remove `go/pkg/mod/github.com/influxdata/influxdb@...`.
