### ISSUE TITLE
influxdb run out of memory and can't start up again

### ISSUE THREAD

**Issue by zhouyuanchao** [influxdata/influxdb#10441]
InfluxDB version is 1.5.0

**ERROR log:**
![image](https://user-images.githubusercontent.com/38806828/47848751-48f73580-de0a-11e8-97cd-9fd855823520.png)

**data folder size:** 
![image](https://user-images.githubusercontent.com/38806828/47848496-742d5500-de09-11e8-8e56-be121c5990f6.png)

**NO.55 data folder has hundreds of tsm file:**
![image](https://user-images.githubusercontent.com/38806828/47848585-cb332a00-de09-11e8-9d1e-2169eed0c619.png)

My machine has 72C and 384G memory
The cardinality datasets size is about 500000
The shard info is "DURATION 7d shard DURATION 1d" 

Please help me find the reason and give me a optimum proposal, thank you!

**Comment by timhallinflux** [comment]
Upgrade to 1.6.4 -- switch from in-mem index to TSI.
https://docs.influxdata.com/influxdb/v1.6/administration/upgrading/

**Comment by russorat** [comment]
closing due to lack of response.
