### ISSUE TITLE
InfluxDB stuck in full compaction process

### ISSUE THREAD

**Issue by conet** [influxdata/influxdb#10465]
__System info:__ InfluxDB 1.7.0, CentOS 7

__Steps to reproduce:__
I upgraded from 1.6.4 a few days ago, I also needed to drop some measurements (I dropped them while running 1.6.4 but some leftovers remained). After the upgrade to 1.7.0 everything seemed fine, then I tried to drop one such measurement which would not go away (seems like #9694). After that operation (which hanged) influxdb seem to be stuck in a continuous full compaction process on the latest shard. Even after several restarts all shards had a successful full compaction (pretty fast, in a couple of minutes) but the process never finishes on the current shard. 

__Expected behavior:__
It should eventually stop compaction which does not seem to progress.

__Actual behavior:__
Compaction seem to run indefinitely.

Is there a way to make influxdb stop hugging the CPU while doing this without loosing data? I will keep in mind to never delete any data since it seems to be causing problems. I hope that this will go away once the shard expires (it seem to have some problems although `influx_inspect verify` reports no issues), but it would be nice if influxdb would not consume CPU for months until this happens.

Besides uselessly consuming CPU it's more annoying that restarts are much slower in this state. 

<img width="1342" alt="compaction-process" src="https://user-images.githubusercontent.com/11311763/48253398-cffe6c00-e40f-11e8-9e2a-eb1eefbbf982.png">

**Comment by conet** [comment]
Could it be that full compaction fails to finish because the shard is currently being written to?
```
658 telegraf autogen          658         2018-11-05T00:00:00Z 2018-11-12T00:00:00Z 2019-02-10T00:00:00Z 
```

**Comment by conet** [comment]
One more question would rolling back to 1.6.4 work? I couldn't find any information related to rollbacks.

**Comment by conet** [comment]
> One more question would rolling back to 1.6.4 work? I couldn't find any information related to rollbacks.

I tried a rollback to 1.6.4 (it worked) but the compaction process was still running indefinitely so I'll just wait for the shard to expire and hopefully the new shard will not exhibit this problem.

**Comment by e-dard** [comment]
Hi @conet,

Would it be possible to provide some profiles whilst your system it exhibiting this behaviour? Ideally with it running 1.7, but if you have downgraded backt to 1.6.4 and the problem still exists then 1.6.4 profiles could be helpful too.

```
curl -o profiles.tar.gz http://localhost:8086/debug/pprof/all?cpu=true
```

The output of `curl -o vars.txt "http://localhost:8086/debug/vars" ` would be useful too, though consider that it contains the names of things like databases and retention policies, so you can email that to me directly if you prefer (my email is `edd` at the company or database dot com).

**Comment by conet** [comment]
@e-dard first of all, thanks for taking the time to have a look at this issue, since the shard exhibiting this behaviour just ended it's lifetime (it's duration was 7 days which was reached today) I have new information about what happened after the shard stopped receiving writes.

<img width="664" alt="shard 77" src="https://user-images.githubusercontent.com/11311763/48348839-1c091500-e68b-11e8-9827-ae5b6301fa8b.png">

As you can see in the above image after 4 hours (the default setting for `compact-full-write-cold-duration`) there was a very short second full compaction operation which shrank the storage with about 100MB. That process finished very fast but the other full compaction operation is still running and there is no way to stop it.

I already tried exporting all the data from one instance and restoring it in another one without any success (the full compaction process started in the new instance on the same shard with the same behaviour).

I'll send you the diagnostic files via email. Shard `77` is part of the `telegraf` database and it's the only one having this problem. I might have some extra leads about what could be causing this: I just upgraded telegraf from `1.7.4` to `1.8.3` the same week as I upgraded influxdb. I also use the mysql plugin which changed the types of some columns and I recall to seeing something similar to #10052. 

I started moving out different kinds of measurements into different databases so in the long this will make it easier to simply drop such a faulty database, if drop measurement does not work. Until now we collected everything into `telegraf` (it's the only collector that we use).

**Comment by e-dard** [comment]
@conet thanks for the update. Can you run this on shard 77? Pick the most recent TSM file possible. It will have the largest `-000000XYZ.tsm` number.

```
influx_inspect dumptsm -index path/to/shard/77/0000000xy-00000000z.tsm
```

You don't need to provide the output here, but could you check if the max times in the first page of the output make sense, or if they're smaller than the min times, or stuck at 1970 or similar? There was a bug we recently fixed where the max times in the TSM indexes could get written incorrectly.

**Comment by conet** [comment]
Yes, they make sense, I didn't see max times smaller than min times and all times seem valid from `2018-11-...`, should I check the entire output for this?

**Comment by e-dard** [comment]
@conet if it was still that bug then I think they would all be bad. Possible it might be worth having a cursory glance at all the TSM files in that shard, but I wouldn't look into it further than that. Thanks for your email, I'm looking at your attachements right now.

**Comment by conet** [comment]
All files look OK, based on the files the largest one is having difficulties finishing the compaction:
```
du -hs /var/lib/influxdb/data/telegraf/autogen/77/*
229M	/var/lib/influxdb/data/telegraf/autogen/77/000000807-000000004.tsm
215M	/var/lib/influxdb/data/telegraf/autogen/77/000000937-000000004.tsm
231M	/var/lib/influxdb/data/telegraf/autogen/77/000001066-000000004.tsm
220M	/var/lib/influxdb/data/telegraf/autogen/77/000001195-000000004.tsm
1.9G	/var/lib/influxdb/data/telegraf/autogen/77/000001751-000000002.tsm
157M	/var/lib/influxdb/data/telegraf/autogen/77/000001751-000000003.tsm.tmp
56K	/var/lib/influxdb/data/telegraf/autogen/77/fields.idx
```

**Comment by e-dard** [comment]
@conet your listing looks strange to me. Since this shard has gone cold, I would assume that the full compaction running on that shard is the final "cold" one. I would expect the resulting file to have a level higher than `3`, which is what seems to be indicated by the temp file in that directory.

In fact, given the temp file in the directory I would expect a `level 2` compaction to be running, but your `/debug/vars` output provided out-of-band indicates a full compaction is running on that shard. 🤔 

If you restart your node the temp file would be cleaned up—does the full compaction startup again on that shard with the same level file? I understand you may not be able to restart your node, so don't worry if that's the case.

**Comment by conet** [comment]
> In fact, given the temp file in the directory I would expect a level 2 compaction to be running, but your /debug/vars output provided out-of-band indicates a full compaction is running on that shard. 🤔

It also seems strange to me I can send you the entire compaction history so you can see there were other level compactions running (you will see them in the logs).

<img width="669" alt="shard 77 full history" src="https://user-images.githubusercontent.com/11311763/48352160-c20d4d00-e694-11e8-9cba-1e2d1f3ba083.png">

> If you restart your node the temp file would be cleaned up—does the full compaction startup again on that shard with the same level file?

Yes, in fact I just restarted the server before to be able to send debug stats, I had `pprof-enabled = false`. Don't worry I'm working on the copy instance (as I said I setup a copy using backup/restore hoping to solve this), as you can see after I setup the copy everything was fine, there was no unusual CPU usage but after about an hour the full compaction process started and has been running ever since.

<img width="668" alt="shard 77 start" src="https://user-images.githubusercontent.com/11311763/48352290-11537d80-e695-11e8-8353-e99d8857f8b6.png">

Will send you the logs over email.

**Comment by e-dard** [comment]
Thanks @conet; I believe this is the same underlying issue as reported in #10468. I'm going to keep this issue open though, as you're running your copy instance on 1.7.0 still, which could provide us with the ability to do some more investigation. If you could keep the instance around that would be great.

**Comment by conet** [comment]
Looking at the CPU usage I noticed that the load has increased, I now have a new and different kind (level 2) of compaction process that seem to go on without stopping. Please note that this is a completely new shard written by `1.7.0`.

<img width="660" alt="shard 90" src="https://user-images.githubusercontent.com/11311763/48364823-0d822400-e6b2-11e8-851a-22907ef5049b.png">

**Comment by conet** [comment]
A service restart does not make any difference:
```
du -hs /var/lib/influxdb/data/logs/autogen/90/*
133M	/var/lib/influxdb/data/logs/autogen/90/000000032-000000003.tsm
34M	/var/lib/influxdb/data/logs/autogen/90/000000040-000000002.tsm
33M	/var/lib/influxdb/data/logs/autogen/90/000000048-000000002.tsm
34M	/var/lib/influxdb/data/logs/autogen/90/000000056-000000002.tsm
34M	/var/lib/influxdb/data/logs/autogen/90/000000064-000000002.tsm
32M	/var/lib/influxdb/data/logs/autogen/90/000000064-000000003.tsm.tmp
33M	/var/lib/influxdb/data/logs/autogen/90/000000073-000000002.tsm
4.1M	/var/lib/influxdb/data/logs/autogen/90/000000074-000000001.tsm
4.2M	/var/lib/influxdb/data/logs/autogen/90/000000075-000000001.tsm
4.2M	/var/lib/influxdb/data/logs/autogen/90/000000077-000000001.tsm
4.0K	/var/lib/influxdb/data/logs/autogen/90/fields.idx
```

**Comment by e-dard** [comment]
@conet please see my comment https://github.com/influxdata/influxdb/issues/10468#issuecomment-438658124

I'm going to close this issue, and we will use the other one for any further discussion. And thank you once again for your help with data to debug with.
