### ISSUE TITLE
I seem to have encountered an error

### ISSUE THREAD

**Issue by entrehuihui** [influxdata/influxdb#10469]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB shell version: 1.7.0~n201811080800
Enter an InfluxQL query
window 7
__Steps to reproduce:__
I created a table to store my data and insert a sequence of data use  github.com/influxdata/influxdb/client/v2 like this

tags := map[string]string{
			"system_name": "dev001",
		}
		fields := map[string]interface{}{
			"value": i,
		}
		pt, err := client.NewPoint("test", tags, fields, time.Now())
		if err != nil {
			log.Fatalln("Error: ", err)
		}
		bp.AddPoint(pt)
err := clnt.Write(bp)

Data is inserted in seconds，t But when I am at the CMD delete the data like 
drop measurement test
and select count(*) from test  the result is 0, this is true,But when I wait a second to insert the data program after inserting the data， then use  select count(*) from test， The data I deleted before will be restored to the table.I am using the default strategy

1. [First Step]
2. [Second Step]
3. [and so on...]

If this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"

curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
```

**Please note** It will take at least 30 seconds for the first cURL command above to return a response.
This is because it will run a CPU profile as part of its information gathering, which takes 30 seconds to collect.
Ideally you should run these commands when you're experiencing problems, so we can capture the state of the system at that time.

If you're concerned about running a CPU profile (which only has a small, temporary impact on performance), then you can set `?cpu=false` or omit `?cpu=true` altogether.

Please run those if possible and link them from a [gist](http://gist.github.com) or simply attach them as a comment to the issue.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for actionable bug reports or feature requests. 

This question would be better posted on the InfluxData community site: https://community.influxdata.com We would be happy to help there.

Thanks.
