### ISSUE TITLE
Automatically migrate shards when running out of disk space

### ISSUE THREAD

**Issue by ono760** [influxdata/influxdb#10478]
InfluxDB should automatically rebalance (migrate) shards based on resource availability. For example, if host A is running out of disk space, InfluxDB should automatically trigger a migration to host B, which has plenty of disk space. 

Currently, using a manual process such as exporting to LP could take a very long time for a 1.3TB DB.  Manually copying shards to a new host and then removing them from the original host to create disk space is also not ideal when working across several databases.

**Comment by timhallinflux** [comment]
This is unlikely to be considered on the 1.x line.  The easier solution is to have nodes with sufficient and equivalent disk space.  When scaling out, administrators should carefully consider where shards should land -- as opposed to a potential random re-distribution of shards.
