### ISSUE TITLE
storage.proto missing from the source

### ISSUE THREAD

**Issue by aviau** [influxdata/influxdb#10473]
Hello!

It looks like ``services/storage/storage.proto`` is missing from the source.

I am getting the following when running go generate:
```
src/github.com/influxdata/influxdb/services/storage/gen.go
storage.proto: No such file or directory
```

**Comment by aviau** [comment]
Linking relevant discussion from the commit that introduced this generate command https://github.com/influxdata/influxdb/commit/6affa7c7f59409b37b010bb8859f5675804b6258.

Apparently storage.proto is not available in OSS InfluxDB but it is required to build it.

**Comment by stuartcarnie** [comment]
@aviau the issue is the `gen.go` source should refer to `source.proto`. Thanks for logging the issue; we'll get that resolved 👍

**Comment by aviau** [comment]
Thanks!
