### ISSUE TITLE
Ability to take backup date based on different user defined time field instead of influx time field

### ISSUE THREAD

**Issue by sibis** [influxdata/influxdb#10485]
__Proposal:__ [Description of the feature]
Ability to take backup date based on different user defined time field instead of influx time field

__Current behavior:__ [What currently happens]
Currently start date mentioned in the backup depends on influx time field.

__Desired behavior:__ [What you would like to happen]
If dev wants to take backup based on different defined time field, there should be an option for it.

__Use case:__ [Why is this important (helps with prioritizing requests)]
Incase if my entry in db is unordered the depending on time while takig backup fails.

**Comment by timhallinflux** [comment]
The databases are index by the influx time field.  There is no secondary index based on fields -- so, every shard would need to be scanned to determine if the input field matches.  For folks who have TBs of data, this would lead to a very poor result.  

I don't think we are going to extend the DB in this direction.
