### ISSUE TITLE
how to use the new parameter "access-log-status-filters" in influxdb.conf of influxdb 1.7.1

### ISSUE THREAD

**Issue by ziflyingyo** [influxdata/influxdb#10487]
**Proposal:** 

**Current behavior:**
with parameter access-log-status-filters like this:
  access-log-status-filters = ["4xx", "5xx"]
then restart influxdb can't work, and logs are:
run: parse config: Near line 250 (last key parsed 'http.access-log-status-filters'): expected a comma or array terminator ']', but got 'x' instead

or 

run: apply env config: status filter must be a digit that starts with 1-5 optionally followed by X characters

So, how to use access-log-status-filters correctly.

Requests may be closed if we're not actively planning to work on them.

**Comment by timhallinflux** [comment]
I have been able to reproduce this issue.  We are investigating the cause.
