### ISSUE TITLE
Dropped database still present in `show databases` but can't be `use'd`

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/influxdb#10491]
__System info:__Influxdb v1.7.1
__Steps to reproduce:__

1. [snapshot.tar.gz](https://github.com/influxdata/influxdb/files/2591039/snapshot.tar.gz)
2. drop database NOA 
3. show databases 

__Expected behavior:__ 
```
> show databases
name: databases
name
----
_internal
telegraf
NOAA_water_database
chronograf
> 
```

__Actual behavior:__ [What actually happened]
```
> show databases
name: databases
name
----
_internal
telegraf
NOA 
NOAA_water_database
chronograf
> 
```
The NOA database is still there 

__Additional info:__ 
use database works as expected:
```> use database NOA
ERR: Database database NOA doesn't exist. Run SHOW DATABASES for a list of existing databases.
DB does not exist!
```
Can't delete this database through Chronograf either.

**Comment by rbetts** [comment]
From slack:

> I didn't know whether to mention this in the issue, but that database was the first database I created, and I'm 80% sure I created it with Chronograf. I haven't had this problem for any other databases thereafter created in the CLI or with Chronograf.

**Comment by e-dard** [comment]
I looked at the binary of the provided `meta.db` and I can see that there is an extra byte `20` (a space), before the two byte `1207` separator between the db name and the retention policy:

In other words, the DB is not `"NOA"`, but is `"NOA "`. We could consider adding a message if there exists a database that's prefixed or suffixed via spaces possibly.
