### ISSUE TITLE
Binding parameters does not support regex

### ISSUE THREAD

**Issue by Hawaii-ol** [influxdata/influxdb#10496]
Official [document](https://docs.influxdata.com/influxdb/v1.7/tools/api/#examples-3) shows three examples of binding parameters to get rid of SQL injections, but they seem not to be working when encountering queries with regular expressions like `=~ /something/` or `!~ /something/`
For example if I send a query like this:
`$ curl -G 'http://localhost:8086/query?db=mydb' --data-urlencode 'q=SELECT * FROM "mymeas" WHERE "mytag1" =~ $tag_value' --data-urlencode 'params={"tag_value":"/12/"}'`
I'll get a 400 Bad Request saying that `"error parsing query: found $tag_value, expected regex at line 1, char 42"`
If I change my query to
`$ curl -G 'http://localhost:8086/query?db=mydb' --data-urlencode 'q=SELECT * FROM "mymeas" WHERE "mytag1" =~ /$tag_value/' --data-urlencode 'params={"tag_value":"12"}'`
This time it won't return an error, but I won't get any result either.
Till now the only workaround I found was to use raw queries, which may lead to exposure to SQL injections like `/ OR 1=1; --`. Sure I can do some filtering work before executing the query, but I'm not an expert on this and when it comes to regular expressions, things can be much more complicated. I believe there is a better way to do this.
Can you add support to this? Thanks so much.

**Comment by palmamartin** [comment]
Any update on this?

**Comment by smifun** [comment]
I run into similar issue with params containing relative path ex.
```
curl -G 'http://localhost:8086/query?db=test' --data-urlencode 'q=SELECT sum(inputLogRecords) as value FROM "default"."metrics_feed_reader" WHERE time >= $from' --data-urlencode 'params={"from":"now() - 1h"}'
{"results":[{"statement_id":0,"error":"invalid operation: time and *influxql.StringLiteral are not compatible"}]}
```
