### ISSUE TITLE
After retention policy values-per-tag is not decrease

### ISSUE THREAD

**Issue by lzf575** [influxdata/influxdb#10500]
__System info:influxdb V1.6.4 Centos 
__Steps to reproduce:__

1. Set "max-values-per-tag" to 5 , 
2.  create database db1
    alter retention policy autogen on db1 duration 1h shard duration 1h
     insert m1,t1=1 v1=1
     insert m1,t1=2 v1=1
     insert m1,t1=3 v1=1
     insert m1,t1=4 v1=1
     insert m1,t1=5 v1=1
 3. in next hour,   
       insert m1,t1=1 v1=1
       insert m1,t1=2 v1=1
    In order to keep measurement 'm1' not to be deleted after do RP. 
4. after do retention policy 
   insert m1,t1=3 v1=1

__Expected behavior: can insert data success

__Actual behavior:  insert failed error is  {"error":"partial write: max-values-per-tag limit exceeded (5/5): measurement=\"m1\" tag=\"t1\" value=\"3\" dropped=1"}

Maybe after RP, on DeleteShard(), only do DropSeriesGlobal() is not enough, 

```
In DropSeriesGlobal()  it calls 'series.Measurement.DropSeries(series)'
in '(m *measurement) AddSeries(s *series)'  it call 'm.seriesByTagKeyValue[string(t.Key)] = valueMap', 
but in '(m *measurement) DropSeries(series *series)' not drop the 'seriesByTagKeyValue' data.
```
I see on normal delete data，will call 'inmem.(*measurement).Rebuild', So maybe you also need to call 'inmem.(*measurement).Rebuild'

**Comment by xiaobeiyang** [comment]
Encounter the same problem. Could anyone help to fix it? This issue lead to data lose.
