### ISSUE TITLE
InfluxDB command line interface import doesn't support windows line endings

### ISSUE THREAD

**Issue by slauson** [influxdata/influxdb#10507]
__System info:__
InfluxDB shell version 1.7.1 for Windows
InfluxDB server version 1.6.0 running on CentOS 7.2.1511

__Steps to reproduce:__

1. Run influx command line interface using import option
`influx.exe -host x.y.z -import -path test.txt`
2. Specify path to file with windows line endings (\r\n)
[test.txt](https://github.com/influxdata/influxdb/files/2601212/test.txt)

__Expected behavior:__ 
File should be imported correctly.

__Actual behavior:__ 
File fails to import with following error.

> 2018/11/20 10:56:29 error writing batch:  {"error":"unable to parse ''82d1ca6a-f580-420f-b808-ecff8ecb18d9' value=0 1439856000\r': bad timestamp\n...

Converting the file to unix style line endings (\n) fixes the issue, but it's not entirely clear this is the problem from the error message.

**Comment by dubnemo** [comment]
If its JSON, it should be agnostic to the the variety of end of line approaches.   Most integration tools will add these EOL values, and it would be a hex replace to remove / replace them to a single line JSON.  What is the issue with this?  I cannot even POST using application/JSON via POSTMAN...

**Comment by slauson** [comment]
This is using the influx CLI/shell import option. The import data uses the line protocol.
https://docs.influxdata.com/influxdb/v1.7/tools/shell/#import-data-from-a-file-with-import

It's not a major issue, just wasted some time debugging the import command due to windows line endings being present in the import file.

**Comment by ilgrank** [comment]
I can confirm the issue is still present.
