### ISSUE TITLE
Flux REPL incorrectly loaded in Windows

### ISSUE THREAD

**Issue by Stephen-Ross** [influxdata/influxdb#10512]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Windows 7
InfluxDB version 1.7.0~n201811210800 (also occurs within the released version of 1.7 for Windows)
enable-flux is set to true within the config file

__Steps to reproduce:__
1. Within powershell (or command line) execute `influx.exe -type=flux`

__Expected behavior:__ [What you expected to happen]
I am able to type flux commands into the window as I would any other REPL environment.

__Actual behavior:__ [What actually happened]
The system prints out a seemingly random selection of characters at startup and whenever I attempt to type or simple click on the window as shown within the screenshot.

![image](https://user-images.githubusercontent.com/22176150/48849791-05f00880-ed9f-11e8-9d66-3a38c59dd294.png)

__Additional info:__ [Include gist of relevant config, logs, etc.]
Within the influxdb process I get the following message, which occurs when I attempt to open the influx.exe process with the flux flag:

```
[httpd] ::1 - - [21/Nov/2018:15:00:44 +0000] "GET /ping HTTP/1.1" 204 0 "-" "InfluxDBShell/1.7.0~n201811210800" '386754a1-ed9e-11e8-8004-5048494f4e43 0'
```

**Comment by Stephen-Ross** [comment]
After leaving the powershell window with the influx.exe running in this state it has finally threw an exception after 1069 minutes, which may be of help in diagnosing this issue.

```
Exception 0xc0000005 0x1 0xc0002
88498 0x7768c4e0
PC=0x7768c4e0

syscall.Syscall6(0x776d54f0, 0x4, 0xf, 0xc0004fdce0, 0x1, 0xc000288498, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/syscall_windows.go:185 +0xfc
syscall.(*Proc).Call(0xc0002d8040, 0xc0004fdd00, 0x4, 0x4, 0x20, 0xb0abc0, 0xce6e01, 0xc0004fdd00)
        /usr/local/go/src/syscall/dll_windows.go:152 +0x39d
syscall.(*LazyProc).Call(0xc000118cc0, 0xc0004fdd00, 0x4, 0x4, 0x40c3af, 0x20, 0xb9fa80, 0x1000000012ca601)
        /usr/local/go/src/syscall/dll_windows.go:302 +0x66
github.com/influxdata/influxdb/vendor/github.com/mattn/go-tty.readConsoleInput(0xf, 0xc0004fdce0, 0xc000423fa0, 0x18406a
0)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/mattn/go-tty/tty_windows.go:134 +0xad
github.com/influxdata/influxdb/vendor/github.com/mattn/go-tty.(*TTY).readRune(0xc0001e2780, 0xafdda0, 0x1, 0xc0000cdc00)

        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/mattn/go-tty/tty_windows.go:201 +0xce
github.com/influxdata/influxdb/vendor/github.com/mattn/go-tty.(*TTY).ReadRune(0xc0001e2780, 0x400, 0x400, 0xc0000cdc00)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/mattn/go-tty/tty.go:30 +0x32
github.com/influxdata/influxdb/vendor/github.com/c-bata/go-prompt.(*WindowsParser).Read(0xc000094398, 0xc000532480, 0x0,
 0x400, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/c-bata/go-prompt/windows_input.go:47 +0x79
github.com/influxdata/influxdb/vendor/github.com/c-bata/go-prompt.(*Prompt).readBuffer(0xc0000a28a0, 0xc0000a2960, 0xc00
0532480)
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/c-bata/go-prompt/prompt.go:246 +0x96
created by github.com/influxdata/influxdb/vendor/github.com/c-bata/go-prompt.(*Prompt).Run
        /root/go/src/github.com/influxdata/influxdb/vendor/github.com/c-bata/go-prompt/prompt.go:56 +0x169
````

**Comment by blu3r4y** [comment]
As a (potentially huge) workaround you can use [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install-win10), install `influxdb` from the influxdata package-repository (to get the newest flux-enabled release) and use the [wsl-terminal](https://github.com/goreliu/wsl-terminal). This will render the flux-mode correctly.

1. Install and set up [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) _(choose whatever distribution you like)_
2. Download [wsl-terminal](https://github.com/goreliu/wsl-terminal/releases) and start `open-wsl.exe` _(no install required)_
3. Follow the [InfluxDB install instructions](https://docs.influxdata.com/influxdb/v1.7/introduction/installation/#installing-influxdb-oss) for the distribution you chose earlier
4. Start and enjoy `influx -type=flux`
