### ISSUE TITLE
Add signature based authentication

### ISSUE THREAD

**Issue by remilapeyre** [influxdata/influxdb#10524]
__Proposal:__

I would like to add a new authentication scheme where authentication is done using basic auth or JWT.
Using a signature scheme like the one used by AWS S3 buckets would allow us to give temporary access using signed requests that would only be usable in the next few minutes

__Current behavior:__

We are using another system to authenticate clients that can access InfluxDB, this force us to use a proxy like so:

```
                           2. check auth
┌────────┐                 ┌───────────┐               ┌────────┐
│        │                 │           │               │        │
│        │ 1. ask for data │           │ 3. fetch data │        │
│        ├─────────────────▶           ├───────────────▶        │
│        │                 │           │               │        │
│Frontend│                 │  Backend  │               │InfluxDB│
│        │                 │           │               │        │
│        ◀─────────────────┤           ◀───────────────┤        │
│        │ 5. send data    │           │ 4. send data  │        │
│        │                 │           │               │        │
└────────┘                 └───────────┘               └────────┘
```

__Desired behavior:__ 

Using signature based authentication our backend would be able to redirect the frontend with the authentication information in the URL, this would simplify our process as we could deploy the backend and influxDB on a separate infrastructure and InfluxDB would check the signature using the shared key:

```

┌────────┐              1. ask for data               ┌─────────┐
│        ├────────────────────────────────────────────▶         │2. check auth
│        │                                            │ Backend │and sign request
│        ◀────────────────────────────────────────────┤         │
│        │3. HTTP 301: /query?...&signature=DlRgRl0Jpi└─────────┘
│Frontend│                                            ┌─────────┐
│        │       4. fetch data with the signature     │         │
│        ├────────────────────────────────────────────▶InfluxDB │
│        │                                            │         │
│        ◀────────────────────────────────────────────┤         │
└────────┘               5. send data                 └─────────┘

```

__Use case:__ 

We are using similar schemes to protect other resources and the hability to check the authenticity of the request offline and to separate the authentication and the service have been very useful.

A nonce could be added if we want the client to be able to execute the request only once.

If this feature is accepted, I'm willing to work on it.

**Comment by dgnorton** [comment]
@remilapeyre InfluxDB supports JWT authentication: https://docs.influxdata.com/influxdb/v1.7/administration/config/#shared-secret. Also some info in the original PR where it was implemented: https://github.com/influxdata/influxdb/pull/6609.

Closing this but we can discuss if you have further requirements.
