### ISSUE TITLE
select count(*) leads batch write becoming slow,  Influx cpu up to 700%

### ISSUE THREAD

**Issue by unanao** [influxdata/influxdb#10520]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Influxdb: 1.7.0
Ubuntu: 16.04
Docker: 18.06.0-ce, build 0ffa825
CPU:         8 core
Memory:  16G
data/wal ：separate storage

__Steps to reproduce:__

1. [First Step]
Run Batch insert 20000 records every 200ms。 

I have 50 measurements, and 40 field per measurement. All measurement have same structure。
```
> select * from "gateway-1" limit 10
name: gateway-1
time                0 1 10 11 12 13 14 15 16 17 18 19 2 20 21 22 23 24 25 26 27 28 29 3 30 31 32 33 34 35 36 37 38 39 4 5 6 7 8 9 createTime    dataSource type
----                - - -- -- -- -- -- -- -- -- -- -- - -- -- -- -- -- -- -- -- -- -- - -- -- -- -- -- -- -- -- -- -- - - - - - - ----------    ---------- ----
1542857556252000000 0                                                                                                             1542857556356 0          String
1542857556252000000                                                                                                             9 1542857556356 9          String
1542857556252000000   1                                                                                                           1542857556356 1          String
1542857556252000000        11                                                                                                     1542857556356 11         String
1542857556252000000                    15                                                                                         1542857556356 15         String
1542857556252000000                                           22                                                                  1542857556356 22         String
1542857556252000000                                                                                          37                   1542857556356 37         String
1542857556252000000                                                                                             38                1542857556356 38         String
1542857556252000000                                              23                                                               1542857556356 23         String
1542857556252000000                                                                                                39             1542857556356 39         String

```

2. [Second Step]
After insert more than 10 hours.
RUN:  select count(*) from "gateway-1"

__Expected behavior:__ [What you expected to happen]
- Select operation have no effect on insert
- Cpu not too high

__Actual behavior:__ [What actually happened]
- Insert become slowly when excute select operation.
- cpu up to 700%

__Additional info:__ [Include gist of relevant config, logs, etc.]
- Docker's default config
[logs.txt](https://github.com/influxdata/influxdb/files/2609922/logs.txt)

If this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

[iostat.txt](https://github.com/influxdata/influxdb/files/2609912/iostat.txt)
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/2609913/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/influxdb/files/2609914/vars.txt)

**Comment by dgnorton** [comment]
@unanao It's writing 20,000 * 40 fields every 200ms? If so, that's about 4 million values per second or about 144 billion values in the 10 hour test period. That's a high write load for a single server.

**Comment by russorat** [comment]
closing due to lack of response.
