### ISSUE TITLE
HttpClient Post params Influxdb can't recognize database {"error":"database is required"}

### ISSUE THREAD

**Issue by boonyachengdu** [influxdata/influxdb#10532]
I used C# HttpClient to write data into influxdb by post method.But,I always get

` {"error":"database is required"}`

1. [HttpPost method]
`
public static async System.Threading.Tasks.Task<string> PostAsync(string url,string database, string username, string password,string sql,string rp)
        {
            using (var client = new HttpClient())
            {
                HttpHelper.SetRequestHeaders(client,username,password);
                var values = new List<System.Collections.Generic.KeyValuePair<string, string>>();
                values.Add(new KeyValuePair<string, string>("db", database));
                values.Add(new KeyValuePair<string, string>("u", username));
                values.Add(new KeyValuePair<string, string>("p", password));
                values.Add(new KeyValuePair<string, string>("q", sql));
                values.Add(new KeyValuePair<string, string>("rp", rp));
                var content = new FormUrlEncodedContent(values);

                var response = await client.PostAsync(url, content);

                var responseString = await response.Content.ReadAsStringAsync();

                return responseString;
            }
        }
`
2. [To call my HttpPost method]
`
 public async System.Threading.Tasks.Task<string> WriteAsync(string database, string sql)
        {
            string rp = "20_days";
            string url = _baseAddress + string.Format("/write","");
            string result = await HttpHelper.PostAsync(url, database,  _username, _password,sql,rp);
            return result;
        }
`
3. [my data formats]

test,type=logs Field0=10,Field1=10,Field2=20

I don't know how to deal with it,somebody can help me?

**Comment by boonyachengdu** [comment]
If I write url with 'db' and 'q' 

`
string url = _baseAddress + string.Format("/write?db={0}&q={1}", database, sql);
`

 **error like**  `{"error":"unable to parse 'db=rtvsweb\u0026u=admin\u0026p=admin\u0026q=test%2Ctype%3Dlogs+Field0%3D10%2CField1%3D10%2CField2%3D20\u0026rp=20_days': missing fields"}
`

**Comment by dgnorton** [comment]
`q` is for queries (reading data). Since you're writing data, put the data in the body of the POST instead of URL parameter.

The best place to ask usage questions is on the [InfluxData community site](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwj6hdq_jYTfAhUOVK0KHWqRBWEQFjAAegQIBRAC&url=https%3A%2F%2Fcommunity.influxdata.com%2F&usg=AOvVaw30uYpyhmmI2SJjSUl9s5Dx).
