### ISSUE TITLE
Completely remove "table"

### ISSUE THREAD

**Issue by palsivertsen** [influxdata/influxdb#10547]
I'm trying to change the type of a column from `float` to `integer`using a rename strategy.

__System info:__ 1.7.1(docker)

__Steps to reproduce:__

1. Initialize database:
```
> drop database test
> create database test
> use test
Using database test
> insert m1,tag=test value=123
> select * from m1
name: m1
time                tag  value
----                ---  -----
1544187238963878641 test 123
```
2. Move measurement and drop old measurements:
```
> select value::integer into m1_copy from m1 group by *
name: result
time written
---- -------
0    1
> drop measurement m1
> select * from m1
> show field keys
name: m1_copy
fieldKey fieldType
-------- ---------
value    integer
```
3. Move measurements back with `value` type changed from `float` to `integer`
```
> select value into m1 from m1_copy group by *
ERR: partial write: field type conflict: input field "value" on measurement "m1" is type integer, already exists as type float dropped=1
```

__Expected behavior:__
I expected that `drop measurement m1` would remove any trace of `m1` measurement, including schema

__Actual behavior:__
The `value` field still persists.

__Additional info:__
I also tried:
```
> drop series from m1
> delete from m1
```

**Comment by jlancasterhmma** [comment]
I have a very similar issue.
In my case, when I insert the data into the newly recreated table, I get duplicated columns with different data types.
It started happening after I imported some data from another measurement into this measurement.
Not sure if that is related, but it is when the issue started occurring.
I could never truly use that measurement name again, I had to start with a new measurement name which affected all my grafana graphs etc.

I can provide more detail if needed.

**Comment by Bombenleger** [comment]
I have the same issue, inserting Strings, then dropping the measurement and inserting boolean results in a `field type conflict`.

I can only reproduce this in my integration tests using docker and `influxdb:1.7`. This does not occur with `influxdb:1.6`.
