### ISSUE TITLE
syntax error: unexpected = in type declaration

### ISSUE THREAD

**Issue by P9110963** [influxdata/influxdb#10553]
When we build the docker image with influxdb source code we are getting the below syntax error. 

Cloning into 'src'...
# github.com/influxdata/influxdb/models
src/github.com/influxdata/influxdb/models/points.go:1885: syntax error: unexpected = in type declaration
src/github.com/influxdata/influxdb/models/points.go:1896: syntax error: unexpected = in type declaration

**Comment by mark-rushakoff** [comment]
It sounds like you're building with an outdated version of Go.

What version of influxdb are you trying to build, and what version of Go are you using?

**Comment by mark-rushakoff** [comment]
Sorry, I don't remember the last version of influxdb that's compatible with Go 1.8. It's been a long time, I think. You'll have to use the version of Go specified in Contributing.md: https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#installing-go

On master, that's go1.11. If you check out the 1.7 or 1.6 or 1.5 branch of influxdb it's probably go1.10 or maybe go1.9. I don't think we're going to put any effort into supporting older versions of Go.
