### ISSUE TITLE
Change shard duration

### ISSUE THREAD

**Issue by HeathKang** [influxdata/influxdb#10551]
I want to change influxdb default shard duration for my database since the data is growing bigger. I realized infinite RP needs more longer shard duration than 7 days. Now my database and memory useage get more slower and bigger than few months ago. And I thought the reason is maybe the shard duration is short（now is 7 day）. So I want to know can I change my database shard duration directly and how?
Here is my server information:
CPU: 32
CPU MHz： 1200
Mem:64G
Data series：1306
data points: 500,000

**Comment by dgnorton** [comment]
@HeathKang the [InfluxData community forum](https://community.influxdata.com/) is the best place to ask usage questions. GitHub issues are for bugs and feature requests. Thanks.
