### ISSUE TITLE
How to Use influxdb project

### ISSUE THREAD

**Issue by ashuptdr** [influxdata/influxdb#10550]
Will anyone explained me how to use above project with "pre-built packages."

I have below packages on my linux machine but i don't know how to use mentioned project in git hub.
wget https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1_linux_amd64.tar.gz
tar xvfz influxdb-1.7.1_linux_amd64.tar.gz

**Comment by dgnorton** [comment]
@ashuptdr the [InfluxData community forum](https://community.influxdata.com/) is the best place to ask usage questions. GitHub issues are for bugs or feature requests. Thanks.
