### ISSUE TITLE
Data Discrepancies in Influx DB values when compared with Jmeter actual aggregate report

### ISSUE THREAD

**Issue by DeepambikaNagarajan** [influxdata/influxdb#10566]
Hi,

We have generated a dashboard in Grafana for aggregate summary report, but we are facing deviations in values like avg,min,max,etc of a sample when comparing grafana dashboard results with jmeter aggregate report values.

For example:  
**In Jmeter Aggregate report:**                                         **Grafana result:**
       sample1-> avg=21025                                                    sample1-> avg=19523        
                          min=29                                                                            min=50
                          max=304457                                                                    max=23654

Please let us know the possible solution for this issue.

Thanks,
Deepa

**Comment by vishalgoyan** [comment]
Hi @DeepambikaNagarajan,

I have built a solution for this issue as Jmeter aggregates raw data while sending to Jmeter.
You can find a solution in below link:

https://www.linkedin.com/pulse/jmeter-influxdb-grafana-issues-transactional-metrics-vishal-goyan/
