### ISSUE TITLE
Data Size Is Increasing Even If I deleted  data

### ISSUE THREAD

**Issue by Puvipavan** [influxdata/influxdb#10560]
**__System info:__** 
InfluxDB Version: 1.6.3
Running on AWS & Only running this db instance
Instance Size: m4.xlarge
OS: CentOS Linux release 7.5.1804 (Core)
AMI ID: centos7-v1.0.90 (ami-079f2af253b31d440)

Database Name: usprod
```
root@ip-removed:/mnt/db/data/data/usprod [0]# du -ch
80M     ./autogen/828
75M     ./autogen/568
2.4M    ./autogen/565
676K    ./autogen/569
12K     ./autogen/571
12K     ./autogen/570
104K    ./autogen/566
724K    ./autogen/567
158M    ./autogen
8.0K    ./default/1065
8.0K    ./default/1066
20K     ./default
1.8G    ./_series/06
1.8G    ./_series/03
1.8G    ./_series/05
1.8G    ./_series/02
1.8G    ./_series/01
1.8G    ./_series/00
1.8G    ./_series/04
1.8G    ./_series/07
15G     ./_series
15G     .
15G     total
```

```
> show retention policies
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
default 5h0m0s   5h0m0s             1        false
autogen 0s       720h0m0s           1        true
```

**__Steps to reproduce:__**
We are collecting metrics data from heapster. It's exporting huge amount of data(RP: default). After processing the data, we are deleting it. And storing processed data in same same database but different measurement (RP: autogen). 

**__Expected behavior:__**
It should reduce the db size once we deleted data

**__Actual behavior:__**
DB Size is increasing day by day

**__Additional info:__** 
Because of increased db size, influxdb instance is taking much CPU & MEMORY. At the end of that we loose connectivity to the instance. 
To fix it, We have to delete /mnt/db/data/data/usprod/_series directory But it won't delete any data But this will fix the issue.
```
root@ip-removed:/mnt/db/data/data/usprod [0]# ls -al
total 20
drwx------.  5 influxdb influxdb 4096 Nov 23 07:34 .
drwxr-xr-x.  5 influxdb influxdb 4096 Oct 18 15:43 ..
drwx------. 10 influxdb influxdb 4096 Nov 13 07:02 autogen
drwx------.  4 influxdb influxdb 4096 Dec 11 18:18 default
drwxr-xr-x. 10 influxdb influxdb 4096 Nov 23 07:34 _series
```

[profiles.tar.gz](https://github.com/influxdata/influxdb/files/2669057/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/influxdb/files/2669058/vars.txt)

**Comment by Puvipavan** [comment]
I have used DROP MEASUREMENT query to delete unwanted data. Won't it delete series?

**Comment by Puvipavan** [comment]
@dgnorton Could you please help?

**Comment by meysampg** [comment]
I have the same problem! Any description about questions of this issue?

P.S. https://stackoverflow.com/questions/57358820/how-to-release-the-deleted-shard-storage-in-influxdb

**Comment by Puvipavan** [comment]
I'm just deleting _series and restarting database. That's the thing doing until now. Otherwise it will take higher amount of memory, because of that I couldn't access the instance and need to stop the instance.

**Comment by myereach** [comment]
I have the same problem, can anyone please explain the usage of _series directory.

**Comment by myereach** [comment]
@Puvipavan @meysampg  I suspect this is because I am using tsi1 index engine not the default one. how about you guys, which index engine do you use?

**Comment by meysampg** [comment]
@myereach I was using the default engine.

**Comment by myereach** [comment]
@meysampg Well, then I have no clue why we are the few people have this issue. Thanks for your response

**Comment by akshayjain847** [comment]
Any update on this, i am also facing the same issue with influx 1.8 and 1.5 as well. Btw i am using default settings - "inmem" of influx.

**Comment by dgnorton** [comment]
This is caused by https://github.com/influxdata/influxdb/issues/9371#issuecomment-455251712 and some offline tooling was added in 1.8.x to help with that in this PR: https://github.com/influxdata/influxdb/pull/16542. For those running InfluxDB 2.x, this tooling was separated out of the `buildtsi` subcommand into its own subcommand by this PR: https://github.com/influxdata/influxdb/pull/17185.

**Comment by saina-m** [comment]
i have this problem. could any one solve this or any helps? :)
