### ISSUE TITLE
influxdb:error parsing query: unable to find time zone

### ISSUE THREAD

**Issue by xiaolings** [influxdata/influxdb#10564]
When I came across this problem in the process of using influxdb, an error parsing query was made using the tz('Asia/Shanghai') function to find the time zone，This kind of mistake only exists in win10/win7

**Comment by dgnorton** [comment]
@xiaolings can you post a full query example? Are you using `curl`, Go client, etc?

**Comment by fresty** [comment]
select * from t_data WHERE time >='2018-11-01T10:00:00Z' order by time desc tz('Asia/Shanghai')
ERR: error parsing query: unable to find time zone Asia/Shanghai
this is in windows  server 2016

**Comment by DyingLight123** [comment]
select * from t_data WHERE time >='2018-11-01T10:00:00+08:00' order by time desc

**Comment by DyingLight123** [comment]
> select * from t_data WHERE time >='2018-11-01T10:00:00Z' order by time desc tz('Asia/Shanghai')
> ERR: error parsing query: unable to find time zone Asia/Shanghai
> this is in windows server 2016

select * from t_data WHERE time >='2018-11-01T10:00:00+08:00' order by time desc
