### ISSUE TITLE
Restore followed by SELECT * INTO mydb..:MEASUREMENT FROM /.*/ GROUP BY * is painfully slow

### ISSUE THREAD

**Issue by nethi-imorph** [influxdata/influxdb#10589]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Linux, InfluxDB 1.7.1, using tsi1 index

__Steps to reproduce:__

1. [First Step]
Bring up a brand new influxdb instance with 2CPUs and 8G RAM
Restore the backup using -portable flag.  The size of the data is around 5G. This finishes up in less than a minute

2. [Second Step]
Side load the restored data into an existing database using SELECT * INTO mydb..:MEASUREMENT FROM /.*/ GROUP BY *

__Expected behavior:__ [What you expected to happen]
Expect the 2nd step to complete in a reasonable amount of time & memory. But it runs out of memory. within a minute or two. Same behaviour even when the memory is increased up to 12G.

So, then modified the side loading statement to use a single measurement such as "cpu", which has about 14 million endpoints. But it still runs out of memory
select count(*) from cpu shows about 14280261 points

Then, we reduced the number of points to be imported to be much smaller time windows, something like this. This finally completed but after several minutes (close to 7 to 8 min)
> SELECT * INTO telegraf..:MEASUREMENT FROM /.*/ WHERE time > '2018-10-24T20:54:30Z' and time < '2018-10-24T21:14:30Z' GROUP BY *
name: result
time written
---- -------
0    244811

__Actual behavior:__ [What actually happened]
Expect side load to complete in a reasonable amount of time without running out of memory
Are there any recommendations on tweaking configuration to make this faster ?

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by pinky1981** [comment]
I am facing the same issue. SELECT INTO times out when copying from tmp DB to main DB, if backup is more than 100 MB. Can anyone pls suggest a workaround?
