### ISSUE TITLE
start influx error

### ISSUE THREAD

**Issue by chiangyn** [influxdata/influxdb#10607]
panic: runtime error: slice bounds out of range
Dec 31 09:24:40 zhiqiweb4 influxd: goroutine 293 [running]:
Dec 31 09:24:40 zhiqiweb4 influxd: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Tombstoner).readTombstoneV4.func1(0xc4629a54b8, 0xc4200b4000, 0xc4629a54e0, 0xc4629a54c8, 0xc4629a5480, 0xc4629a5488, 0xc4629a56c8, 0x42c926, 0xe28078)
Dec 31 09:24:40 zhiqiweb4 influxd: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/tombstone.go:619 +0x5c5
Dec 31 09:24:40 zhiqiweb4 influxd: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Tombstoner).readTombstoneV4(0xc4219e2ab0, 0xc479056000, 0xc4629a56c8, 0x0, 0x0)
Dec 31 09:24:40 zhiqiweb4 influxd: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/tombstone.go:638 +0x452
Dec 31 09:24:40 zhiqiweb4 influxd: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Tombstoner).Walk(0xc4219e2ab0, 0xc4629a56c8, 0x0, 0x0)
Dec 31 09:24:40 zhiqiweb4 influxd: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/tombstone.go:234 +0x29a
Dec 31 09:24:40 zhiqiweb4 influxd: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*TSMReader).applyTombstones(0xc4205dd6c0, 0xc4acb58000, 0x50)
Dec 31 09:24:40 zhiqiweb4 influxd: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:260 +0x17a
Dec 31 09:24:40 zhiqiweb4 influxd: github.com/influxdata/influxdb/tsdb/engine/tsm1.NewTSMReader(0xc4a5c97d58, 0x17f82b3560, 0x131d6c0, 0xc473a7f7d8)
Dec 31 09:24:40 zhiqiweb4 influxd: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:249 +0x2a5
Dec 31 09:24:40 zhiqiweb4 influxd: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*FileStore).Open.func1(0xc4217e6dc0, 0xc582e8ed80, 0x1, 0xc4a5c97d58)
Dec 31 09:24:40 zhiqiweb4 influxd: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.go:488 +0x65
Dec 31 09:24:40 zhiqiweb4 influxd: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*FileStore).Open
Dec 31 09:24:40 zhiqiweb4 influxd: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.go:486 +0x4e8
Dec 31 09:24:42 zhiqiweb4 systemd: in

**Comment by dgnorton** [comment]
@chiangyn what version of InfluxDB?
