### ISSUE TITLE
Configuration validation errors to journal but missing the service indentifier of the systemd service unit

### ISSUE THREAD

**Issue by konstantinblaesi** [influxdata/influxdb#10611]
__System info:__

InfluxDB:  v1.7.2
OS: Centos 7

__Steps to reproduce:__

1. `journalctl -af -u influxdb`
2. add configuration error to /etc/influxdb/influxdb.conf , e.g. set boolean to _yes_ instead of _true_
3. `systemctl start influxdb`

__Expected behavior:__ 

Config validation errors are logged in the journal as the service **influxdb**

__Actual behavior:__ 

Config validation errors are only visible when viewing journal with the service filter, e.g. `journalctl -af`

__Additional info:__ 

The missing validation message was
> run: parse config: Near line 242 (last key parsed 'http.auth-enabled'): expected value but found "yes" instead

Note that the message **is** stored in the journal, except it's not visible when filtering by **service influxdb**. This behavior is confusing when trying to figure out why your service fails to start.

**Comment by konstantinblaesi** [comment]
iovec in #systemd on freenode mentioned that this is an already reported systemd bug. Unfortunately I do not know the issue number.
Adding SyslogIdentifier=influxdb to /usr/lib/systemd/system/influxdb.service and filtering using `SYSLOG_IDENTIFIER=influxdb journalctl -af` will work but of course it's not what I want :)

**Comment by dgnorton** [comment]
Sounds like this is a `systemd` bug so closing this issue. Let me know if I misunderstood and we can re-open this issue.
