### ISSUE TITLE
Lock on older version of go-billy.v4, does not compile on Solaris

### ISSUE THREAD

**Issue by dewi-ny-je** [influxdata/influxdb#10610]
I performed the usual

```
go get github.com/influxdata/influxdb
cd $GOPATH/src/github.com/influxdata/
go get ./...

```
and the compilation stopped with:

```
# gopkg.in/src-d/go-billy.v4/osfs
../../gopkg.in/src-d/go-billy.v4/osfs/os_posix.go:13:9: undefined: syscall.Flock
../../gopkg.in/src-d/go-billy.v4/osfs/os_posix.go:13:41: undefined: syscall.LOCK_EX
../../gopkg.in/src-d/go-billy.v4/osfs/os_posix.go:20:9: undefined: syscall.Flock
../../gopkg.in/src-d/go-billy.v4/osfs/os_posix.go:20:41: undefined: syscall.LOCK_UN

```
I checked os_posix.go and I noticed it does not correspond to the latest version available in its official repo, that would not present the compilation error I experienced.

After replacing the file with the latest one, the compilation proceeds further.

**Comment by dgnorton** [comment]
@dewi-ny-je did you run `dep ensure --vendor-only`?

**Comment by dewi-ny-je** [comment]
I'll try, but the $GOPATH had just been created and everything got downloaded as part of the influxdb install process.
