### ISSUE TITLE
"SHOW TAG KEYS" returns empty after influxdb 1.7 upgrade

### ISSUE THREAD

**Issue by oori** [influxdata/influxdb#10612]
__System info:__ 
influxdb 1.7.2
chronograph 1.6.x and 1.7.x
influx CLI

__Steps to reproduce:__

After influxdb 1.7.2 upgrade, **some** measurements don't respond with their tag keys.
`SHOW TAG KEYS ON "db" FROM "autogen"."measurementABC"` --> WORKS
`SHOW TAG KEYS ON "db" FROM "autogen"."measurementXYZ"` --> EMPTY

__Additional info:__
In chronograph's data explorer, selecting a measurement and clicking the expand arrow (to show tags) does nothing on those affected measurements (tags do not appear).

Other then the above, there are **no** other issues since the upgrade.   the system is working fine, and one can filter/group by tags normally (even on the above affected measurements!).

Any tip on how to debug this strange issue?

**Comment by e-dard** [comment]
@oori if you go back to your previous version do the tag keys for `measurementXYZ` reappear?

**Comment by oori** [comment]
@e-dard Well, downgrade back to influxdb 1.6 ?  
it's a production database (docker), but I guess I can try it..    any other idea (less intrusive) on how to debug this, before I do this downgrade?   Thanks!

**Comment by TheOneValen** [comment]
I have the same problem since 1.6.x there are multiple reports like this in #9953

**Comment by oori** [comment]
@TheOneValen  It's not exactly the case.      Unlike #9953, I can do `SHOW TAG VALUES`, even get the new tag values.    my issue is with showing the keys, ie:
`SHOW TAG KEYS ON "db" FROM "measurement"` --> returns empty !
`SHOW TAG VALUES ON "db" FROM "measurement" WITH KEY = "device"`  --> returns correct results !

**Comment by imcom** [comment]
hey guys, i actually run into this very issue with version `influxdb:1.5.2-alpine`, I did no upgrade nor downgrade and there was no restart or any sort of things like that. It just happened out of no where.
The symptom is the same

```
`SHOW TAG KEYS ON "db" FROM "measurement"` --> returns empty !
`SHOW TAG VALUES ON "db" FROM "measurement" WITH KEY = "device"` --> returns correct results !
```

**Comment by oori** [comment]
@e-dard, as @imcom, I'm also not convinced it has to do to the upgrade.     Any hint how we can debug this query?

**Comment by TheOneValen** [comment]
Is there any news on this?

**Comment by oori** [comment]
Nope.   But I can share that in my case it was resolved after full backup&restore of the database.       which proves the issue was **not** in the data..

**Comment by kangelos** [comment]
select * from availability limit 10
name: availability
time                availability hostname       name
----                ------------ --------       ----
1616253303983879401 99.653       192.168.50.50  86400
1616253303986775685 99.95        192.168.50.50  604800
1616253303988706880 99.988       192.168.50.50  2592000
1616253303990600717 99.999       192.168.50.50  31536000
1616253304033047183 99.654       192.168.50.2   86400
1616253304035038697 99.951       192.168.50.2   604800
1616253304037019778 99.988       192.168.50.2   2592000
1616253304039041926 99.999       192.168.50.2   31536000
1616253304100174806 99.654       192.168.50.217 86400
1616253304102135453 99.951       192.168.50.217 604800
==================================================
> SHOW TAG VALUES FROM "availability" with key =~ /host/
> 
-- empty like the void
