### ISSUE TITLE
vendor: remove local fork of github.com/getkin/kin-openapi when/if pull request is merged.

### ISSUE THREAD

**Issue by goller** [influxdata/influxdb#10626]
Here is the PR: https://github.com/getkin/kin-openapi/pull/54

Once merged, run this command to remove our local fork:

```sh
go mod edit -dropreplace=github.com/getkin/kin-openapi
```

(also, whoever you are in the future, would you remove our local fork repo too? I don't think we'll need it)

**Comment by mark-rushakoff** [comment]
I'd like to delete our fork, but that would break builds of old versions that depend on our fork.

I'll archive our fork after #10949 is merged.
