### ISSUE TITLE
High memory usage every 30mn

### ISSUE THREAD

**Issue by dodgers** [influxdata/influxdb#10620]

**Comment by dodgers** [comment]
Hi, 

I'm running influxdb influxdb-1.3.7 on Redhat distribution with 4 CPU and 60 Gb of RAM because each 30 minutes influxdb process consumes a size of 50G . 
6000 series , 400G for data disk space 

![image](https://user-images.githubusercontent.com/5651212/50901484-98646e00-1418-11e9-9a9c-0de81a8d8183.png)

Does someone can explain why influx need this huge amount of memory ? 
What can i do to reduce memory usage ?

This is my conf : 

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = true
  logfile = "/var/log/telegraf/telegraf.log"
  hostname = ""
  omit_hostname = false

regards

**Comment by job-lukasz** [comment]
@dodgers have you diagnose why such situation exists? I have similar issue.

**Comment by dodgers** [comment]
Hi ,

still have the issue and don't understand what is the problem

Regards

**Comment by dodgers** [comment]
Seems that the issue come from the old influxdb storage method. 
I've migrated to a newer version of influxdb and the problem is gone
