### ISSUE TITLE
Integrate query billing logic

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#10632]
All layers of the stack now understand query billing mertrics. We need to validate the all the integration points are complete and that the query metrics are being stored with our normal query metrics.

**Comment by nathanielc** [comment]
I have some more details on this issue:

We need to push billing metrics to an external endpoint. The specific metrics we need to collect are:

* `bytes scanned` - The number of bytes scanned to serve the query
* `values scanned` - The number of values scanned to serve the query
* `bytes returned` - The number of bytes sent to the client. 

Each metric needs to collected per query with an organization tag.

The basic idea suggested was to push these metrics as line protocol to a local telegraf instance using UDP, this way billing availability doesn't affect query availability. Then the telegraf would be configured to forward those metrics in batches onto a billing service that would then do the aggregation etc with them.

We currently have the query.Statistics that contains most of this info, we need to update the queryd process to push these metrics to telegraf. 

The gateway is just a proxy, so bytes written in response to a query from queryd will be the same for bytes written from gateway (i.e. to the client). If gateway ever changes we will need to revisit this design.

**Comment by jsternberg** [comment]
The open source section of this, which is the tracking of bytes scanned and values scanned to the statistics, has been done.

#12156 and influxdata/flux#1003.
