### ISSUE TITLE
Transpiler: Implement field wildcards

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#10654]
Implement the `*` functionality and the `function(*)`. This will require a working schema implementation to function.

**Comment by jsternberg** [comment]
This is documented now for the how to do: https://github.com/influxdata/influxdb/blob/master/query/influxql/README.md#-generate-the-pivot-table

I'll begin working on this.

**Comment by jsternberg** [comment]
This may actually cause an issue. In the trivial case, this can be quite easy such as in the example of `SELECT * FROM m0`. But, influxql also allows  `SELECT * + 2, value FROM cpu` and then it starts to  become harder. We would need to apply the `+ 2` to every field that was selected and have it as a separate column. We would also have to deal with the inevitable field conflict. It is not possible to infer that `value` is selected by `*` because `value` may not be a field or tag. If a field or tag was present  with the key `value`, then the second `value` would be `value_1` (or maybe `value_0`). If it wasn't, then it would keep its name and just be an empty column.

So this has a lot of edge cases that are pretty complicated.

**Comment by aanthony1243** [comment]
if value is not a field or tag what would it be?

**Comment by jsternberg** [comment]
Nothing. It gets returned as null. It annoyed me for a very long time, but influxql treats everything as something and does not return errors when you reference nothing because it believes nothing is something.

**Comment by jsternberg** [comment]
I am going to treat this issue as "implement field wildcards when a wildcard is the only thing present". We can do that with pivot. We will have to design the more complex stuff.

**Comment by jsternberg** [comment]
Good news: This was too complex for influxql at the time too: https://github.com/influxdata/influxdb/blob/728bdd6562858ff7e0793bcf54b619e462f55a1c/query/compile.go#L309
