### ISSUE TITLE
`influx auth create` should accept bucket name and org name

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb#10721]
I execute the command `influx auth create --user jacob --read-bucket 0200443fa8ec3000 --write-bucket 0200443fa8ec3000` a lot, right after `influx org create --name my-org` and `influx bucket create --org my-org --name my-bucket --retention 168h`.

It would be much easier to script these commands if `influx auth create` accepted the bucket name instead of (in addition to) bucket ID.

**Comment by kaspergrubbe** [comment]
This is still an issue, and it's very annoying to have to resort to more scripting because the command doesn't accept a name.

**Comment by kaspergrubbe** [comment]
It's me, 3 hours later, if anyone else finds themselves here, here is a way to extract bucket id, org name and org id:

```bash
org_id=$(influx org ls | awk 'NR==2 {print $1}') 
org_name=$(influx org ls | awk 'NR==2 {print $2}') 
bucket_id=$(influx bucket list --org-id ${org_id} --name ${bucket_name} | awk 'NR==2 {print $1}')
```

Now, let's break down the awk script:

- `NR==2`: NR is a built-in variable in awk that represents the current record number (i.e., the line number). Here, it checks if the line number is equal to 2. So, this condition is true only for the second line of input data.

- `{print $1}`: When the condition `NR==2` is true, this part of the script is executed. `print $1` instructs awk to print the first field (column) of the current line. Fields in awk are separated by a delimiter (usually whitespace, by default).

**Comment by vidstige** [comment]
@kaspergrubbe thanks for this. I was able to do it without any `awk` scriptin

``` 
influx org ls --hide-headers --name <orgname> | cut -f1
```

And likewise for buckets

```
influx bucket ls --hide-headers --name <bucket-name> | cut -f1
```
