### ISSUE TITLE
Transpiler: Implement elapsed

### ISSUE THREAD

**Issue by jlapacik** [influxdata/influxdb#10733]

**Comment by yzhang1991** [comment]
Several issues that make this harder to fix compared to other aggregate functions:
* The default unit is `1s` in Flux [[Doc]](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/elapsed/) but `1ns` in InfluxQL [[Doc]](https://docs.influxdata.com/influxdb/v1.7/query_language/functions/#elapsed)
* Flux preserves the `_value` column and add a new column `elapsed` while InfluxQL does not preserve the `_value` column. In `mapFields()` phase during trasnpilation, the normal routine is to rename `_value` to `elapsed` which is not correct. The trasnpiler needs to treat this function in a special way.

**Comment by jsternberg** [comment]
To clarify, the `elapsed` function doesn't overwrite the old column. It creates a new column that is next to the value so when we see elapsed we need a different pattern to drop the old value column and rename the new column to the value column.

**Comment by jsternberg** [comment]
Because elapsed seems to be a bit special, we should find an end to end test with elapsed and write the pure flux end to end test as a model for what to do with the transpiler.

**Comment by fchikwekwe** [comment]
I wrote the end to end test for elapsed right [here](https://github.com/influxdata/flux/pull/2584) and I can move on to trying to work on fixing the transpiler to work properly with this function today. I appreciate the discussion here, gives me a little bit more direction for this one.

**Comment by fchikwekwe** [comment]
What I actually ended up doing in the end to end test is just dropping the _value column. The `elapsed()` function produces a column with the default name `elapsed` and the expected values, so I didn't need to rename anything.
