### ISSUE TITLE
api: define how to re-run task over time range

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#10752]
We have an endpoint to retry a single run: https://github.com/influxdata/platform/blob/6a861f2648a3a52da9f022bb892a29ba98d72a74/http/swagger.yml#L855-L885

But we don't yet have an endpoint that says "re-run this task over the time range [start, end]". We need that endpoint to support manual re-runs of a task for a known backfilled time range.

**Comment by docmerlin** [comment]
Is this still a thing?

**Comment by mark-rushakoff** [comment]
The task backend supports it, but there is still no user-facing HTTP API to do it. I think this is still valid on the long-term roadmap, but it's another one that we probably shouldn't do before we get more concrete user input.
