### ISSUE TITLE
Break out each Read physical operation into its own RPC call

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#10758]
Currently we have a Read call with various parameters. Not all combinations of parametes are valid, and certain combinations require that the read service behave differently. 

By explicitly exposing those individual physical operations we prevent invalid combinations, expose to the planner the cost of each operation, protect against breaking existing behavior and separate concerns between the client and the server.

**Comment by jlapacik** [comment]
Each physical read operation now has its own RPC call, so closing this issue.
