### ISSUE TITLE
Add meta information to tasks

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#10779]
Same as dashboards:
```
meta: {
  createdAt: date
  updatedAt: date
}
```

connect #2225

**Comment by mark-rushakoff** [comment]
Tasks report updatedAt and createdAt as of #11794. Removing blocking label.

**Comment by mark-rushakoff** [comment]
Actually, I'm unsure whether this issue is supposed to track the work in tasks that happened in #11794, or whether this is supposed to track something in the frontend. @alexpaxton should this issue be closed?

**Comment by alexpaxton** [comment]
@mark-rushakoff I believe this issue was just for tracking the API work
