### ISSUE TITLE
Retention rule is not being set when it is omitted from the request body

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#10777]
Since retention rule is not mandatory then, if it is omitted, it should be set to default value - 0 (zero),keep the data indefinitely (see https://github.com/influxdata/platform/issues/419)
 - Create a bucket (omit the retentionRules):
> requests.post('http://localhost:9999/api/v2/buckets', data='{"name":"b_1","organizationID":"03380f3f03b38000"}', headers={'Authorization': 'Token -pWn5fCwomE9q0oTBHtHN7xmRhQwzfLZ6tmvEAhhn9-Lz5Zf-6qB1GrgLtedMa614kgs8Q96rxhNZCAEt_drcA=='})

- Request response:
> {u'name': u'b_1', u'links': {u'org': u'/api/v2/orgs/03380f3f03b38000', u'self': u'/api/v2/buckets/0338186368338000', u'log': u'/api/v2/buckets/0338186368338000/log'}, u'organizationID': u'03380f3f03b38000', u'retentionRules': [], u'organization': u'a', u'id': u'0338186368338000'}

Note that `retentionRules': []`

- getting the info about created bucket (using HTTP GET request) also returns `retentionRules:[]`
> requests.get('http://localhost:9999/api/v2/buckets/0338186368338000', headers={'Authorization': 'Token -pWn5fCwomE9q0oTBHtHN7xmRhQwzfLZ6tmvEAhhn9-Lz5Zf-6qB1GrgLtedMa614kgs8Q96rxhNZCAEt_drcA=='})

> {u'name': u'b_1', u'links': {u'org': u'/api/v2/orgs/03380f3f03b38000', u'self': u'/api/v2/buckets/0338186368338000', u'log': u'/api/v2/buckets/0338186368338000/log'}, u'organizationID': u'03380f3f03b38000', u'retentionRules': [], u'organization': u'a', u'id': u'0338186368338000'}

**Comment by goller** [comment]
@gshif this is correct behavior.  retention rules are for when data is deleted.  No rules mean that the data isn't deleted.
