### ISSUE TITLE
Add the ability to select bucket from dropdown on scraper overlay

### ISSUE THREAD

**Issue by Palakp41** [influxdata/influxdb#10784]
as an org manager
with admin permissions or higher
when i view the list of org members
then i would like to be able to select a bucket when adding a new scraper to the org

**Comment by ischolten** [comment]
currently there is just one bucket in this dropdown. lets make sure to actually get all of the bucket options to display here

**Comment by ischolten** [comment]
dependent on https://github.com/influxdata/influxdb/issues/10785 getting closed
