### ISSUE TITLE
Clicking add data opens dataloader wizard

### ISSUE THREAD

**Issue by Palakp41** [influxdata/influxdb#10781]
as an org manager
with admin permissions or higher
when i view the list of buckets and click the add data button,
then i would like the data loader wizard to appear

**Comment by ischolten** [comment]
we need a wizard that uses the selection, configuration, and verify steps from onboarding. additionally this will require new redux state

**Comment by Palakp41** [comment]
Depended on https://github.com/influxdata/influxdb/issues/10782
