### ISSUE TITLE
A more space/time efficient structure for permissions and permission checking.

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#10812]
Currently both `platform.Authorization` and `platform.Session` use a very naive structure (`[]platform.Permission`) to check if an action is authorized. This will likely not be an appropriate structure for sessions or authorizations with a large number of permissions.

**Comment by kelwang** [comment]
We can make a map of resource->permissions. 
permission, can be either read or write, we could use the linux based 2^ integer system to concat them. (we would prefer to make a larger integer, in-case more complex permission is needed future).
```go
const
Read permission = 1<<iota
Create 
Delete
Update
Write = Create|Delete|Update
```
Resource currently has 3 components: resourceType, orgID, resourceID
we can simplely make a string as hashkey {resourceID}_{orgID}_{resourceType}. use zero for nil values.

Permission match of []Permission function will be removed. Instead, we will reimplement Allowed(p Permission) bool in Authorizer interface. with a simple map matching
