### ISSUE TITLE
Extract color selector from Label creator and use wherever single colors are selected

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#10810]

**Comment by OfTheDelmer** [comment]
Changes in #11973 introduced an alternative to the Label color dropdown selector, a random label color button. The button is useful for areas where there isn't much room for a dropdown or in the ResourceLabelForm where we wanted to avoid a dropdown in a dropdown.

**Comment by alexpaxton** [comment]
![image](https://user-images.githubusercontent.com/2433762/53852886-61be5600-3f78-11e9-9cc6-69d2df7bb7fa.png)
