### ISSUE TITLE
Configurable session timeouts by org

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#10841]
as a admin user
with admin permissions or higher
when i configure the settings for the org
then i would like the ability to configure the session timeout for each org
then i would like the default session timeout to be 30 mins
then i would like the session to be refreshed with each web request from the user (/me requests shouldn't count)

**Comment by alexpaxton** [comment]
I've seen a couple feature requests for this, maybe time to revisit?

**Comment by russorat** [comment]
we will revisit this later
