### ISSUE TITLE
api: authorization links do not follow swagger schema

### ISSUE THREAD

**Issue by goller** [influxdata/influxdb#10879]
Links look like this in the response now:

```json
{"links":{"self":"/api/v2/authorizations"}}
```

In the schema it is:
https://github.com/influxdata/platform/blob/master/http/swagger.yml#L4053-L4067

The swaggernschema needs to be updated to be the response.

**Comment by desa** [comment]
@goller did the link you provided reference https://github.com/influxdata/influxdb/blob/d73d73c0d4b708462ef58c8851577486aeb3de56/http/swagger.yml#L4822-L4831

**Comment by goller** [comment]
Hey @desa, yuppers, that's the correct link.
