### ISSUE TITLE
white line appearing on the select streaming page

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#10887]
white line appears under streaming selector in smaller page (looks like a fancy scrollbar artifact)

![screen shot 2018-12-18 at 1 05 34 pm](https://user-images.githubusercontent.com/5751863/50183017-c8ab6780-02c5-11e9-85f7-1c12fc7b0c0e.png)

**Comment by mavarius** [comment]
Closed by https://github.com/influxdata/platform/pull/2395
