### ISSUE TITLE
Api doesn't fully implement swagger spec

### ISSUE THREAD

**Issue by glinton** [influxdata/influxdb#10880]
Some of the responses contain empty bodies, contrary to the [api swagger spec.](
https://github.com/influxdata/platform/blob/3e54ef9f532ad6fa6ec1bd6ca3c08fa7e9adee27/http/swagger.yml#L574-L579)

Known/tested response codes that return an empty body in the `/api/v2/write` path are `401` and `403` responses.

**Comment by russorat** [comment]
@goller can this be closed?
