### ISSUE TITLE
Add the ability to save the query from data explorer as a Task

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#10896]
Depends on #1868

as a data explorer
with admin permissions or higher
when i open the save as modal from the data explorer
then i would like the ability to save this query as a task
then i would like a way to set the name of the task
then i would like a way to set the org the task belongs to
then i would like the task to be saved as inactive
then i would like a notification telling me that the task was saved
then i would like a way to quickly jump to the task after creating it to continue configuring  and editing it

**Comment by AlirieGray** [comment]
should be done after/alongside: https://github.com/influxdata/influxdb/issues/10897
