### ISSUE TITLE
add an option in the UI to run a task once

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#10903]
as a task builder
with admin permissions or higher
when i view the list of tasks 
then i would like to be able to execute the task immediately outside of the schedule

this is pending work from the tasks team

https://github.com/influxdata/platform/issues/1490

**Comment by mark-rushakoff** [comment]
This is supported in the task API as of https://github.com/influxdata/influxdb/commit/0e41f240f2ceaa292dfff7a4d122004e3808a9c0.
