### ISSUE TITLE
add the ability to update the token's description

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#10910]
as a user
with admin permissions or higher
when i open the Token Editor Overlay (TEO)
then i would like the ability to edit the description of the token

**Comment by Palakp41** [comment]
Token description is not being updated when update is called with new description on a PATCH api call: `/authorizations/{authID}` with new description for auth in the request body

**Comment by kelwang** [comment]
The swagger doc is a little deceptive. 
The only thing PATCH did is just updating the auth status. User may not be able to update the permission, or description. 
It seems to me, there is a reason which I don't really know. 
My suggestion is,  we could add the description update, which I don't think it will hurt anything. And also remove permissions update from the swagger docs.

What do you guys think? 
cc @goller, @desa , @jademcgough

**Comment by Palakp41** [comment]
@kelwang The token description should be mutable, so we can update it from the ui. I have created an issue for the api here: https://github.com/influxdata/influxdb/issues/12938

**Comment by desa** [comment]
@kelwang I think it makes sense to make a patch so that status or description can be updated. Might be worthwhile to look into if there are any other fields that make sense to update like that.
