### ISSUE TITLE
Add minLength: 1 to organization's name in swagger

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#10923]
Chris, If I understood you correctly, then organizations with empty and duplicate names could be created. Currently, the `an organization name must be specified` error is returned if organization name is an empty string and `organization with name <name> already exists` error is returned when name of the org already exists.

**Comment by goller** [comment]
@gshif it is no longer the case that orgs can have empty names.

the organization name in swagger needs to have a `minLength: 1`
