### ISSUE TITLE
"fatal error: runtime: cannot allocate memory" while starting InfluxDB

### ISSUE THREAD

**Issue by benpaxton-hf** [influxdata/influxdb#10939]
__System info:__
OS: Ubuntu 16.04.4 LTS x86_64 (linux 4.4.0)
InfluxDB: Various versions (1.4.x, 1.5.x, 1.7.1, master) as detailed below; when running on the test data these versions were built from the `vX.Y.Z` tags; when running on the full data these were downloaded from dl.influxdata.com.

__Steps to reproduce:__

Unknown; start InfluxDB with >~1000 databases and/or >~30000 shards?

__Expected behavior:__ InfluxDB would start up correctly

__Actual behavior:__ InfluxDB fails to start up with a "cannot allocate memory" error; the system does not appear to run out of memory

__Additional info:__

"cannot allocate memory" at startup with >~1000 databases

Initially encountered when upgrading an InfluxDB instance (1210 dbs, 34332 shards, 312GB on disk) from 1.2.x to 1.7.1.
We attempted to reproduce the issue by taking our largest 20 databases (210 shards, 176GB) but were unable to.
We then tested with the other 1190 databases; InfluxDB recreated the `_internal` database leaving us with 1191 databases (34122 shards, 136GB), which displayed the same crash.

The *system* does not appear to run out of memory - only ~12-14GB of memory is in use according to `htop` (of 64GB in the system) when the crash occurs.

Version tested    | Result (test data) | Result (full data)
------------------|--------------------|--------------------
1.4.0rc0          | OK                 | -
1.4.3             | OK                 | sometimes crashes
1.5.0rc0          | Crash              | -
1.7.1             | Crash              | always crashes
master (8ab48459) | Crash              | -

We attempted bisection between 1.4.0rc0 and 1.5.0rc0 but didn't get far due to several seemingly unrelated issues encountered while compiling or running intermediate commits; however, this crash is not behaving as if it was introduced in a specific commit; more that it is the result of increases to specific parts of InfluxDB's memory usage over time, so a newer version requires less data to crash - 1.4.3 was stable with our test data, but is only mostly stable with our full data.

Logs from a crash encountered on 8ab48459:
```
ts=2019-01-09T17:08:27.083822Z lvl=error msg="Cannot read corrupt tsm file, renaming" log_id=0Ctu7JHl000 engine=tsm1 service=filestore path=/influxdb/data/<database1>/autogen/33302/000000014-000000002.tsm id=0 error="cannot allocate memory"
ts=2019-01-09T17:08:27.098669Z lvl=error msg="Cannot read corrupt tsm file, renaming" log_id=0Ctu7JHl000 engine=tsm1 service=filestore path=/influxdb/data/<database1>/autogen/33303/000000002-000000002.tsm id=0 error="cannot allocate memory"
ts=2019-01-09T17:08:27.099271Z lvl=error msg="Cannot read corrupt tsm file, renaming" log_id=0Ctu7JHl000 engine=tsm1 service=filestore path=/influxdb/data/<database1>/autogen/45330/000000024-000000002.tsm id=0 error="cannot allocate memory"
ts=2019-01-09T17:08:27.104431Z lvl=error msg="Cannot read corrupt tsm file, renaming" log_id=0Ctu7JHl000 engine=tsm1 service=filestore path=/influxdb/data/<database1>/autogen/33304/000000001-000000001.tsm id=0 error="cannot allocate memory"
ts=2019-01-09T17:08:27.106083Z lvl=error msg="Cannot read corrupt tsm file, renaming" log_id=0Ctu7JHl000 engine=tsm1 service=filestore path=/influxdb/data/<database2>/autogen/27796/000000073-000000002.tsm id=0 error="cannot allocate memory"
fatal error: runtime: cannot allocate memory

runtime stack:
runtime.throw(0x124e3e8, 0x1f)
	/usr/lib/go/src/runtime/panic.go:608 +0x72
runtime.persistentalloc1(0x4000, 0x0, 0x1db05d8, 0x7ff1aecdf990)
	/usr/lib/go/src/runtime/malloc.go:1190 +0x280
runtime.persistentalloc.func1()
	/usr/lib/go/src/runtime/malloc.go:1143 +0x45
runtime.persistentalloc(0x4000, 0x0, 0x1db05d8, 0x1d97008)
	/usr/lib/go/src/runtime/malloc.go:1142 +0x82
runtime.(*fixalloc).alloc(0x1d99cb8, 0x1)
	/usr/lib/go/src/runtime/mfixalloc.go:80 +0x109
runtime.(*mheap).allocSpanLocked(0x1d96800, 0x1, 0x1db05a8, 0x400)
	/usr/lib/go/src/runtime/mheap.go:873 +0x13a
runtime.(*mheap).alloc_m(0x1d96800, 0x1, 0x21, 0x7fd310f0bfff)
	/usr/lib/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/lib/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x1d96800, 0x1, 0x7fd310010021, 0x7fd30f926c90)
	/usr/lib/go/src/runtime/mheap.go:758 +0x8a
runtime.(*mcentral).grow(0x1d98378, 0x0)
	/usr/lib/go/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0x1d98378, 0x1ff)
	/usr/lib/go/src/runtime/mcentral.go:106 +0x2f8
runtime.(*mcache).refill(0x7ff1aecd5880, 0xc000060021)
	/usr/lib/go/src/runtime/mcache.go:122 +0x95
runtime.(*mcache).nextFree.func1()
	/usr/lib/go/src/runtime/malloc.go:749 +0x32
runtime.systemstack(0x0)
	/usr/lib/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1229


goroutine 34643 [running]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:311 fp=0xc26a6deb40 sp=0xc26a6deb38 pc=0x45bd30
runtime.(*mcache).nextFree(0x7ff1aecd5880, 0xc395319421, 0x1, 0x1, 0xc39cca52b0)
	/usr/lib/go/src/runtime/malloc.go:748 +0xb6 fp=0xc26a6deb98 sp=0xc26a6deb40 pc=0x40d606
runtime.mallocgc(0xf0, 0x0, 0xc4ad596905b4a300, 0xc26a6decb0)
	/usr/lib/go/src/runtime/malloc.go:903 +0x793 fp=0xc26a6dec38 sp=0xc26a6deb98 pc=0x40df53
runtime.rawbyteslice(0xea, 0x0, 0x0, 0x0)
	/usr/lib/go/src/runtime/string.go:271 +0xa0 fp=0xc26a6dec78 sp=0xc26a6dec38 pc=0x4492a0
runtime.stringtoslicebyte(0x0, 0xc39ccc14a0, 0xea, 0xf0, 0xc39cca52b0, 0x1)
	/usr/lib/go/src/runtime/string.go:160 +0xb5 fp=0xc26a6decc0 sp=0xc26a6dec78 pc=0x448c85
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Cache).WriteMulti(0xc37523e840, 0xc39551f0e0, 0x0, 0x0)
	/repos/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:343 +0x275 fp=0xc26a6dee60 sp=0xc26a6decc0 pc=0xec3835
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*CacheLoader).Load.func1(0xc26a6df288, 0xc3818b4f00, 0xc26a6df278, 0xc37523e840, 0x0, 0x0)
	/repos/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:747 +0x64c fp=0xc26a6df238 sp=0xc26a6dee60 pc=0xf3dcbc
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*CacheLoader).Load(0xc3818b4f00, 0xc37523e840, 0x1, 0xc3818b4f00)
	/repos/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:758 +0xa6 fp=0xc26a6df2a8 sp=0xc26a6df238 pc=0xec5116
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).reloadCache(0xc37bca0360, 0x0, 0x0)
	/repos/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2252 +0x186 fp=0xc26a6df3f0 sp=0xc26a6df2a8 pc=0xef9996
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).Open(0xc37bca0360, 0xc0000ddd00, 0xc36b24cd00)
	/repos/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:745 +0x2a0 fp=0xc26a6df478 sp=0xc26a6df3f0 pc=0xeef440
github.com/influxdata/influxdb/tsdb.(*Shard).Open.func1(0xc36b15f440, 0x0, 0x0)
	/repos/go/src/github.com/influxdata/influxdb/tsdb/shard.go:340 +0x36d fp=0xc26a6df6a8 sp=0xc26a6df478 pc=0x9d1a1d
github.com/influxdata/influxdb/tsdb.(*Shard).Open(0xc36b15f440, 0xc0000ddda0, 0x44)
	/repos/go/src/github.com/influxdata/influxdb/tsdb/shard.go:351 +0x2f fp=0xc26a6df700 sp=0xc26a6df6a8 pc=0x9b537f
github.com/influxdata/influxdb/tsdb.(*Store).loadShards.func1(0xc0000c2900, 0xc000e71200, 0xc00163a360, 0xc0000c2960, 0x1222d40, 0xc0649aeab0, 0xc02c3aa500, 0xc001692e0f, 0x27, 0xc0132372f7, ...)
	/repos/go/src/github.com/influxdata/influxdb/tsdb/store.go:404 +0x517 fp=0xc26a6dff78 sp=0xc26a6df700 pc=0x9d2d27
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc26a6dff80 sp=0xc26a6dff78 pc=0x45de11
created by github.com/influxdata/influxdb/tsdb.(*Store).loadShards
	/repos/go/src/github.com/influxdata/influxdb/tsdb/store.go:362 +0x19d6


[3817 goroutines omitted]
```

**Comment by benpaxton-hf** [comment]
possibly related to https://github.com/influxdata/influxdb/issues/4548?

**Comment by jacobmarble** [comment]
> Unknown; start InfluxDB with >~1000 databases and/or >~30000 shards?

@benpaxton-hf that's a lot of databases, and a lot of shards. InfluxDB memory usage scales somewhat linearly with shard count, so OOM isn't surprising. Even if each database only had 1 shard, 1000 shards can be too many in some cases.

To help you scale vertically, here are some ideas:
- Be sure to use TSI for indexing, so 1.5.x or later, and [make sure it's enabled](http://docs.influxdata.com/influxdb/v1.7/administration/config/#index-version-inmem)
- How are you organizing databases? Perhaps regroup by team/department/geography, whatever makes sense for your situation, but try to reduce 1000 databases to <100
- 30 shards per database is probably fine. If you find shards that are particularly small compared to others (for example, 10MB vs 1GB) then consider adjusting the [shard group duration](https://stackoverflow.com/questions/39878027/influxdb-whats-shard-group-duration) so that you have fewer, larger shards

**Comment by jacobmarble** [comment]
Tell me more about degraded performance with TSI. It's the opposite of what we expect when folks switch to TSI.

In which version of InfluxDB was TSI problematic?

**Comment by benpaxton-hf** [comment]
Sorry, after speaking with a few co-workers, it was less that the performance was degraded and more that it a) didn't solve the performance issues we were having at the time, and b) took *far* more memory than inmem indexes to start up, to the point some deployments that were perfectly stable (if a little slow) on inmem would OOM at startup on TSI.

Apologies for the confusion.

**Comment by jacobmarble** [comment]
The inmem index should take longer to init, and use more memory, on average, than TSI. That's why TSI exists. Perhaps try TSI again?

The problem with inmem is that all data must be read from disk on init, in order to create the in-memory index. With TSI, the index is on disk, so we mmap the bulk of the index and move on with initialization.

With that many shards, and that much data on disk, you're pushing the limits of a single node pretty hard, especially with the in-memory index. This might be a good time to talk to our sales team about an enterprise contract. Our enterprise support team regularly digs in with customers to resolve this type of issue as companies scale.

**Comment by kshcherban** [comment]
Same issue with database converted from inmem indexes to TSI. Influxdb version 1.7.4

**Comment by kshcherban** [comment]
Seems to be related to #11830.

**Comment by ianwoolf** [comment]
I have encountered the same problem. The influxdb above version 1.4.3 will panic.
I increase vm.max_map_count(increase  to 2048000, default is 65530), it works for me.
