### ISSUE TITLE
creating an empty task fails with a 500 error

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#10987]
on the UI, we should handle this gracefully.

in the api, it should return an error message for invalid task.

**Comment by mark-rushakoff** [comment]
From a quick look into this, it appears to be a 500 due to an EOF - presumably `json.NewDecoder(resp.Body).Decode(&x)` is the issue. That pattern appears about 59 times in the codebase, so it likely warrants a more general solution involving wrapping the standard library's JSON parser.

**Comment by lyondhill** [comment]
The body of the 500 error I'm able to reproduce is `type error 3:3-3:8: undefined identifier "every"`

When I look at the request body I see:
```
{"organizationID":"033f4992c799a000","flux":"option task = { \n  name: \"\",\n  every: ,\n}\n"}
```

@russorat What kind of error would you like to receive with a poorly formed request body?

@mark-rushakoff All though that didn't cause this specific error I think we should probably a clean way of handling a empty body. maybe with a different response code.

Maybe for both scenarios (no body in request and a malformed body) we could use `400 Bad Request`?
