### ISSUE TITLE
Remote InfluxDB v2 Failed to Load

### ISSUE THREAD

**Issue by BondAnthony** [influxdata/influxdb#11013]
__System info:__ InfluxDB v2 darwin amd64
__Steps to reproduce:__

1. Startup two different InfluxDB v2 and run through the configuration of creating a user, org, and bucket
2. Using one of the InfluxDB instances setup the a new source and configure the other instance.
3. Click connect to the remote source
4. Open the data explorer screen

__Expected behavior:__ Load the remote bucket information

__Actual behavior:__ Bucket column returns "Failed To Load"

__Additional info:__
```
X-Influx-Error: json: error calling MarshalJSON for type *query.ProxyRequest: json: error calling MarshalJSON for type query.Request: json: error calling MarshalJSON for type influxdb.ID: invalid ID
```
https://github.com/influxdata/influxdb/blob/next/http/source_proxy_service.go#L35

**Comment by goller** [comment]
- [ ] Error message for proxy request needs to be easier to understand
- [ ] Error needs to be platform.Error
- [ ] source_proxy_service.go does not send org <-- root cause

**Comment by russorat** [comment]
sources have been removed for now
