### ISSUE TITLE
owner does not come back from the dashboards list api

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#11026]
owner should be returned in the api to list dashboards similar to tasks

**Comment by goller** [comment]
@russorat owners should be able to be retrieved from `/api/v2/dashboards/:id/owners`

/cc @jademcgough

**Comment by jademcgough** [comment]
Yes, the `/api/v2/dashboards/:id/owners` endpoint can be used for this.

It's missing from the links response for dashboards; I'll add a PR to fix that.

**Comment by jademcgough** [comment]
@russorat let me know if anything else is needed for this

**Comment by russorat** [comment]
i think this is done
