### ISSUE TITLE
Add high level meta query API

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#11046]
- [ ] Build out storage engine APIs that expose measurement, tag key, tag value and field information via TSM indexes and/or TSI indexes.
  - [ ] Add RPC for the flux keys function to interact with new storage APIs.

**Comment by stuartcarnie** [comment]
Flux requires meta queries support time ranges using the `range(start:end:)` function. This implies storage must touch TSM data to validate.

Various meta queries can be found in [v1.flux](https://github.com/influxdata/flux/blob/master/stdlib/influxdata/influxdb/v1/v1.flux)

For example, the following Flux query should return a list of values for `tag0`:

```flux
import "influxdata/influxdb/v1"

v1.tagValues(bucket:"foo", tag: "tag0", start: -1h)
```

The final output presented to the user will be N rows, where N is the number of unique tag values for `tag0` that falls within the specified time range.

To be more specific, imagine `N` represents the number of tag values for `tag0` within the specified time range and `M` the total number of series in the bucket `foo`. `N` is 10 and `M` is 1,000,000. 

The current implementation will call the `Read` RPC, which enumerates all series keys (M) and touches the first TSM block within the time range for every series key, returning those series keys with data within the specified time range, represented by `M'`. There are a few problems with calling the `Read` RPC:

* The Flux reader will receive `M'` rows and reduce those to `N`. Typically `M'` is going to be close to `M`.
* The Read response format is excessive given the request. The client is interested in a distinct list of strings.

By introducing a new RPC API, the planner can express the request more specifically to fetch tag values for a given tag key. Arbitrary predicates would still be supported, however, at a much greater cost as TSM blocks will need to be decoded and evaluated. 

```
tag_values = tsi.get_tag_values(tag_key) // returns the distinct list of tag values for tag_key
TAGKEYS:
for each tagvalue in tag_values:
  # find first series that is within this time range
  for each series_key in series_keys where tag_key == value [and predicate]:
    if has_data(series_key, time_range, predicate):
      add tagvalue to list
      continue TAGKEYS
```

**Comment by e-dard** [comment]
This was completed via the Schema API work.
