### ISSUE TITLE
JSON parser errors are usually indicated by 500 status

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#11057]
(from discussion in #10987)

Due to the way we represent errors in headers, there is at least one common class of error that propagates as a 500 when it should probably be a 400 - submitting invalid JSON. Here are two such requests that should have been rejected due to an empty request body, but instead propagated an EOF as a 500 error:

```
$ curl -v -XPOST -H "Authorization: Token $(cat ~/.influxdbv2/credentials)" localhost:9999/api/v2/tasks
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9999 (#0)
> POST /api/v2/tasks HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Token ...
>
< HTTP/1.1 500 Internal Server Error
< X-Influx-Error: EOF
< X-Influx-Reference: 1
< Date: Mon, 14 Jan 2019 21:59:04 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact

$ curl -v -XPOST -H "Authorization: Token $(cat ~/.influxdbv2/credentials)" localhost:9999/api/v2/users
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9999 (#0)
> POST /api/v2/users HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Token ...
>
< HTTP/1.1 500 Internal Server Error
< X-Influx-Error: EOF
< X-Influx-Reference: 1
< Date: Mon, 14 Jan 2019 21:59:48 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

Respectively, those errors originated from:

https://github.com/influxdata/influxdb/blob/d42f6aa1f3c028ec713b0105537ef6cc2148173c/http/task_service.go#L319-L323
https://github.com/influxdata/influxdb/blob/d42f6aa1f3c028ec713b0105537ef6cc2148173c/http/user_service.go#L149-L153

We should have a generic solution to this issue. One option would be to explicitly check for io.EOF everywhere, but it would probably be simpler to either:

-  provide something like kit/json that provides a json decoder that returns errors compatible with kit/error
- add something like a `FromJSONDecodeError` function to kit/errors that converts json decoder errors into kit errors

The latter would work like:

```go
if err := json.NewDecoder(r.Body).Decode(&foo); err != nil {
  return nil, kerrors.FromJSONDecodeError(err)
}
```

I assume there are several other error patterns that will need a similar treatment, so that should inform design decisions in making this new API.

**Comment by kelwang** [comment]
this is related to the new platform error
