### ISSUE TITLE
Support CreatedAt, UpdatedAt in task results

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#11061]
Frontend issue to display last modified column: https://github.com/influxdata/influxdb/issues/10822

@goller can you point us at some detail on what we've standardized on with updated at and created at?

**Comment by goller** [comment]
@mark-rushakoff 

Here is the standard we did for dashboards:

https://github.com/influxdata/influxdb/blob/master/http/swagger.yml#L6247-L6255

Here is the interface describing those operations:
https://github.com/influxdata/influxdb/blob/master/keyvalue_log.go

Here is the current implementation using bolt:
https://github.com/influxdata/influxdb/blob/master/bolt/keyvalue_log.go

However, after the alpha, we'd like to implement `KeyValueLog` using a new system bucket.

**Comment by mark-rushakoff** [comment]
AFAICS, the bolt-backed dashboards aren't currently using the KeyValueLog service:

https://github.com/influxdata/influxdb/blob/0b8bc6061c2842f673cf346ae9573fba4b8d069c/bolt/dashboard.go#L287-L290

https://github.com/influxdata/influxdb/blob/0b8bc6061c2842f673cf346ae9573fba4b8d069c/bolt/dashboard.go#L698-L702

I see the benefit of the KVL approach for an actual audit log, like the godoc on the interface explains; but it seems a bit heavy for literally tracking the creation and update timestamp on a given object.

**Comment by goller** [comment]
@mark-rushakoff the requirements at the time were around being able to see creation/update but eventually get to seeing the log.

**Comment by mark-rushakoff** [comment]
For now, we'll add CreatedAt and UpdatedAt both to the task's meta info.
