### ISSUE TITLE
Wrong set of bootstrap permissions 

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#11069]
When running `setup` for the first time after starting up the `influxd` daemon, the set of permissions seems to be wrong:
- Create default user/org/bucket (via rest service)
```
requests.post('http://localhost:9999/api/v2/setup', 
data='{""username":"admin_user","password":"admin_pass","org":"admin_org","bucket":"admin_bucket","retentionPeriodHrs":0}')
```

- The set of permissions returned by the request
```
{u'action': u'read', u'orgID': u'033fa063fde19000', u'resource': u'authorizations'}
{u'action': u'write', u'orgID': u'033fa063fde19000', u'resource': u'authorizations’}

{u'action': u'read', u'orgID': u'033fa063fde19000', u'resource': u'buckets'}
{u'action': u'write', u'orgID': u'033fa063fde19000', u'resource': u'buckets'}

{u'action': u'read', u'orgID': u'033fa063fde19000', u'resource': u'dashboards'}
{u'action': u'write', u'orgID': u'033fa063fde19000', u'resource': u'dashboards'}

{u'action': u'read', u'orgID': u'033fa063fde19000', u'resource': u'orgs'}
{u'action': u'write', u'orgID': u'033fa063fde19000', u'resource': u'orgs'}

{u'action': u'read', u'orgID': u'033fa063fde19000', u'resource': u'sources'}
{u'action': u'write', u'orgID': u'033fa063fde19000', u'resource': u'sources'}

{u'action': u'read', u'orgID': u'033fa063fde19000', u'resource': u'tasks'}
{u'action': u'write', u'orgID': u'033fa063fde19000', u'resource': u'tasks'}

{u'action': u'read', u'orgID': u'033fa063fde19000', u'resource': u'telegrafs'}
{u'action': u'write', u'orgID': u'033fa063fde19000', u'resource': u'telegrafs'}

{u'action': u'read', u'orgID': u'033fa063fde19000', u'resource': u'users’}
{u'action': u'write', u'orgID': u'033fa063fde19000', u'resource': u'users’}
```

- Expected:
   - For resource `org`, the correct set of actions should be `create`, `delete`, `update`
   - For resource `user`, the correct set of actions should be `create`, 'delete`, `update`
   - For resource `tasks`, the correct set of actions should be `create`, `delete`, `update`
   - For resource `authorization`, the correct set of actions should `create`, `delete`, (`update`?)

I am not sure about `telegraf` resource, as I do not know what it does in this context.
`Sources` and `dashboards` should probably have `create`, `delete` and `update` actions,

**Comment by goller** [comment]
actions will only be `read` and `write.`  

Additionally, we'll be change resource a bit soon as well.

Here is the current documentation:

https://github.com/influxdata/influxdb/blob/master/http/swagger.yml#L4840-L4855

It's currently acting as designed.
