### ISSUE TITLE
task: investigate consolidating bolt and in-mem store behind kv interface

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#11063]

**Comment by lyondhill** [comment]
After investigating the current shortcomings of our system and a few meetings a refactor is in order. It should relieve a significant amount of technical debt and put us in a good place for code readability, stability, and transactionality. 

As a result of this investigation I have created a number of new issues.
#12724 
#12725 
#12726
#12727 
#12728 
#12729 
#12730
