### ISSUE TITLE
User created during setup does not have sufficient permissions to write to any bucket

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#11084]
- Setup initial user/org and bucket

`requests.post('http://localhost:9999/api/v2/setup',data='{"username":"admin_user","password":"admin_pass","org":"admin_org","bucket":"admin_bucket","retentionPeriodHrs":0}')`

- Returned response auth object:

```
{
  "description": "admin_user's Token", 
  "id": "033fe6ab08d8d000", 
  "links": {
    "self": "/api/v2/authorizations/033fe6ab08d8d000", 
    "user": "/api/v2/users/033fe6aaf758d000"
  }, 
  "org": "admin_org", 
  "orgID": "033fe6ab0858d000", 
  "permissions": [
    {
      "action": "read", 
      "orgID": "033fe6ab0858d000", 
      "resource": "authorizations"
    }, 
    {
      "action": "write", 
      "orgID": "033fe6ab0858d000", 
      "resource": "authorizations"
    }, 
    {
      "action": "read", 
      "orgID": "033fe6ab0858d000", 
      "resource": "buckets"
    }, 
    {
      "action": "write", 
      "orgID": "033fe6ab0858d000", 
      "resource": "buckets"
    }, 
    {
      "action": "read", 
      "orgID": "033fe6ab0858d000", 
      "resource": "dashboards"
    }, 
    {
      "action": "write", 
      "orgID": "033fe6ab0858d000", 
      "resource": "dashboards"
    }, 
    {
      "action": "read", 
      "orgID": "033fe6ab0858d000", 
      "resource": "orgs"
    }, 
    {
      "action": "write", 
      "orgID": "033fe6ab0858d000", 
      "resource": "orgs"
    }, 
    {
      "action": "read", 
      "orgID": "033fe6ab0858d000", 
      "resource": "sources"
    }, 
    {
      "action": "write", 
      "orgID": "033fe6ab0858d000", 
      "resource": "sources"
    }, 
    {
      "action": "read", 
      "orgID": "033fe6ab0858d000", 
      "resource": "tasks"
    }, 
    {
      "action": "write", 
      "orgID": "033fe6ab0858d000", 
      "resource": "tasks"
    }, 
    {
      "action": "read", 
      "orgID": "033fe6ab0858d000", 
      "resource": "telegrafs"
    }, 
    {
      "action": "write", 
      "orgID": "033fe6ab0858d000", 
      "resource": "telegrafs"
    }, 
    {
      "action": "read", 
      "orgID": "033fe6ab0858d000", 
      "resource": "users"
    }, 
    {
      "action": "write", 
      "orgID": "033fe6ab0858d000", 
      "resource": "users"
    }
  ], 
  "status": "active", 
  "token": "slx3HycogynjXiBfuyhDgeCRvOJ4ZvAd5T3FN0tk_sBw05WqxdMJzdzw2KSTj4-cLgdQ8IwrL0Mlui1Anq6O9Q==", 
  "user": "admin_user", 
  "userID": "033fe6aaf758d000"
}
```

- Create a different organization using the `admin` user's token `slx3HycogynjXiBfuyhDgeCRvOJ4ZvAd5T3FN0tk_sBw05WqxdMJzdzw2KSTj4-cLgdQ8IwrL0Mlui1Anq6O9Q==`

`requests.post('http://localhost:9999/api/v2/orgs', data='{"name":"org_test_1"}', headers={'Authorization': 'Token slx3HycogynjXiBfuyhDgeCRvOJ4ZvAd5T3FN0tk_sBw05WqxdMJzdzw2KSTj4-cLgdQ8IwrL0Mlui1Anq6O9Q=='})`

The organization created successfully.  
Response json object:
```
{
  "id": "033fe9d5e818d000", 
  "links": {
    "buckets": "/api/v2/buckets?org=org_test_1", 
    "dashboards": "/api/v2/dashboards?org=org_test_1", 
    "labels": "/api/v2/orgs/033fe9d5e818d000/labels", 
    "log": "/api/v2/orgs/033fe9d5e818d000/log", 
    "members": "/api/v2/orgs/033fe9d5e818d000/members", 
    "secrets": "/api/v2/orgs/033fe9d5e818d000/secrets", 
    "self": "/api/v2/orgs/033fe9d5e818d000", 
    "tasks": "/api/v2/tasks?org=org_test_1"
  }, 
  "name": "org_test_1"
}
```

Based on the `admin user` permission for resource `org`, `{u'action': u'read', u'orgID': u'033fe6ab0858d000', u'resource': u'orgs'}, {u'action': u'write', u'orgID': u'033fe6ab0858d000', u'resource': u'orgs'},`, looks like this user can create or delete any org, despite the `orgID` key

- Create a bucket in the above create organization:
`requests.post('http://localhost:9999/api/v2/buckets', data='{"name":"b_1_","organizationID":"033fe9d5e818d000"}',headers={'Authorization': 'Token slx3HycogynjXiBfuyhDgeCRvOJ4ZvAd5T3FN0tk_sBw05WqxdMJzdzw2KSTj4-cLgdQ8IwrL0Mlui1Anq6O9Q=='})`

Bucket is created successfully
Response object:
```
{
  "id": "033fec4e4c58d000", 
  "labels": [], 
  "links": {
    "labels": "/api/v2/buckets/033fec4e4c58d000/labels", 
    "log": "/api/v2/buckets/033fec4e4c58d000/log", 
    "org": "/api/v2/orgs/033fe9d5e818d000", 
    "self": "/api/v2/buckets/033fec4e4c58d000"
  }, 
  "name": "b_1_", 
  "organization": "org_test_1", 
  "organizationID": "033fe9d5e818d000", 
  "retentionRules": []
}
```

- I am assuming that admin_user (or user created during setup above) has all permissions, among them the permission to write data to any bucket. The permissions for a `bucket` resource is similar to a permission for a `org` resource: 
```
[
  {
    "action": "read", 
    "orgID": "033fe6ab0858d000", 
    "resource": "buckets"
  }, 
  {
    "action": "write", 
    "orgID": "033fe6ab0858d000", 
    "resource": "buckets"
  }
]
```

But writing data to a bucket created in the previous step fails with error
```
insufficient permissions for write
```

- Write data:
`requests.post('http://localhost:9999/api/v2/write?org=org_test_1&bucket=b_1_', data='cpu,de=1 f=1', headers={'Authorization': 'Token slx3HycogynjXiBfuyhDgeCRvOJ4ZvAd5T3FN0tk_sBw05WqxdMJzdzw2KSTj4-cLgdQ8IwrL0Mlui1Anq6O9Q=='})`

**Comment by russorat** [comment]
@kelwang @goller do you know if this is still a problem?
