### ISSUE TITLE
Move the WAL up from tsm1 to storage engine

### ISSUE THREAD

**Issue by zeebo** [influxdata/influxdb#11094]
# Tear down that WAL

This document is a proposal with cost/benefits for moving the WAL out of the `tsm1.Engine` and
in to the `storage.Engine`. The high level goals are:

- Keeping consistency with all the on disk structures
- A closer architecture to cloud 2.0
- Reducing moving parts for more involved TSM work

## Consistency

Right now, the flow of data is:

```
Writes:
┌──────────────────────────────────────────────────────────────┐
│Storage Engine                                                │
│                        ┌────────────────────────────────────┐│
│                        │TSM1 Engine                         ││
│┌───────────────────┐   │┌───┐   ┌─────┐   ┌────────────────┐││
││Index + Series File├──>││WAL├──>│Cache├──>│Compaction (TSM)│││
│└───────────────────┘   │└───┘   └─────┘   └────────────────┘││
│                        └────────────────────────────────────┘│
└──────────────────────────────────────────────────────────────┘

Deletes:
┌───────────────────────────────────────────────┐
│TSM1 Engine                                    │
│┌───┐   ┌───┐   ┌─────┐   ┌───────────────────┐│
││TSM├──>│WAL├──>│Cache├──>│Index + Series File││
│└───┘   └───┘   └─────┘   └───────────────────┘│
└───────────────────────────────────────────────┘
```

Writes have a problem if there is a crash or hard exit between the index + series file and the WAL.
Deletes have a problem if there are deletes during the TSM delete (partial tombstones written), or
after the WAL, or during the index + series file (partial series deletion). The partial deletes are
a problem because delete operations do not know the full set of keys that could be deleted since
they operate on buckets. This means that we may not know to delete a series from the index or
series file because we won't observe the series being deleted.

The proposal is to change the flow to look like this:

```
Writes:
┌──────────────────────────────────────────────────────────────┐
│Storage Engine                                                │
│                                ┌────────────────────────────┐│
│                                │TSM1 Engine                 ││
│┌───┐   ┌───────────────────┐   │┌─────┐   ┌────────────────┐││
││WAL├──>│Index + Series File├──>││Cache├──>│Compaction (TSM)│││
│└───┘   └───────────────────┘   │└─────┘   └────────────────┘││
│                                └────────────────────────────┘│
└──────────────────────────────────────────────────────────────┘

Deletes:
┌─────────────────────────────────────────────────┐
│Storage Engine                                   │
│        ┌───────────────────────────────────────┐│
│        │TSM1 Engine                            ││
│┌───┐   │┌─────┐   ┌───────────────────┐   ┌───┐││
││WAL├──>││Cache├──>│Index + Series File├──>│TSM│││
│└───┘   │└─────┘   └───────────────────┘   └───┘││
│        └───────────────────────────────────────┘│
└─────────────────────────────────────────────────┘

```

This solves the above issues because the operations are idempotent. Moving the TSM deletes last
in the pipeline for deletes makes it so that partial failures are still ok.

## Closer architecture

This is closer to cloud 2.0 which means that testing, performance and bug fixes for that will
be more applicable to our open source code, and visa versa. It's synergistic!

## Reducing moving parts

By moving the WAL up out of the tsm engine, we are allowed to assume inside of it that any
partial operations will be replayed automatically. This greatly simplifies the concerns at
those layers, making it so that we just have to worry about keeping the state in a working
state. Additionally, it can help performance because we can batch up operations in memory or
delay fsyncs until more work has been done confident that any uncomitted work will be replayed
by the WAL.

# Challenges

The challenges for this proposal include

- The WAL is tied into the tsm1 package and engine fairly deeply
- Knowing when it's safe to truncate the WAL requires upward signaling
- It only replays into a cache

## Deep ties

TODO: Investigate all the spots the WAL is used and under what locks

## Knowing when to truncate

The WAL right now truncates writes when compactions happen. This is problematic because we also
need to keep track of when deletes have been fully applied for the truncate to be possible.
Additionally, knowing when compactions happen and exactly what values have been compacted will
require signaling from the `tsm1.Engine` upward to the `storage.Engine`, with possibly some
risk with locks and stuff.

## Replay

The cache kinda directly loads from the internal WAL data structures, which causes some problems
for moving it. We need the WAL to replay not only to the cache, but to the index as well. It
will become more like an op log and less like some special purpose data structure to load values
into a cache. That may be challenging to keep performance up.

**Comment by e-dard** [comment]
In general I am 👍 on this. It makes a lot of sense. Part of the potential problems vis the keys came about when we introduced the Series File, and removed keys from the index. I like the solution to this.

One other architectural benefit I think of moving the WAL up and out, is that it will be simpler to implement back pressure in the WAL, protecting the engine from being overloaded. Typically this manifests itself as the cache blowing. We will want to put backoff at the WAL layer so that we can make writes durable but not let them proceed into the cache/engine if it's under too much load.
