### ISSUE TITLE
Query Explorer tabs should scroll instead of pushing toolbar buttons off-screen.

### ISSUE THREAD

**Issue by mavarius** [influxdata/influxdb#11158]
![image](https://user-images.githubusercontent.com/11937365/51277953-ff8ca000-198d-11e9-92af-9323ac7619fa.png)

Query Explorer tabs should scroll instead of pushing toolbar buttons off-screen.

**Comment by alexpaxton** [comment]
What do you think about truncating and having a tooltip appear? Similar to how chrome handles it when there are too many tabs and you can switch via a dropdown

**Comment by chnn** [comment]
It might be worth thinking about stacking tabs vertically again (on the left side of the query builder).

Right now the controls start getting squished with a single tab and a screen width of ~1100px, which is quite wide IMO.

So I think we'd still have a space issue even with scrolling or a dropdown.
