### ISSUE TITLE
api: tasks returns owner in response but should not.

### ISSUE THREAD

**Issue by goller** [influxdata/influxdb#11164]
Ownership of resources is to be handled at the /api/v2/{RESOURCE}/{id}/owners endpoint.

For now, tasks needs to remove the field `owner` from the task API.

This is a response that contains owner, but, should not: 

<img width="466" alt="screen shot 2019-01-16 at 12 36 20 pm" src="https://user-images.githubusercontent.com/1922921/51279532-34572200-19a3-11e9-9352-2d3a44439906.png">

/cc @Palakp41 @ebb-tide

**Comment by mark-rushakoff** [comment]
It looks like tasks still needs more full integration with the owners service, so while it would be simple to just remove the existing `owner` object from task responses, proper integration will be a somewhat involved change:

- On task create, assign owning user and org via UserResourceMappingService
- (task/backend.Store).ListTasks needs to look up task IDs through the UserResourceMappingService
- Task store needs to stop maintaining its own user and owner index

We can probably do those 3 steps incrementally so it's not one gigantic change.
