### ISSUE TITLE
Make sure binary has sufficient privileges to access the default /protos directory

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#11178]
ensure permissions structure of /protos folder. in ~/.influxdbv2/protos which is the default directory for protos. Currently with available permissions, build halts at the load step for protos with error `Error: lstat /Users/USERNAME/.influxdbv2/protos/FILENAME.json: permission denied`

**Comment by goller** [comment]
This needs to be 0700:

https://github.com/influxdata/influxdb/blob/master/fs/proto.go#L44
