### ISSUE TITLE
testcontainers/testcontainer-go has been renamed to testcontainers/testcontainers-go

### ISSUE THREAD

**Issue by F21** [influxdata/influxdb#11199]
https://github.com/testcontainers/testcontainer-go has been renamed to https://github.com/testcontainers/testcontainers-go

I was having issues with Go modules and discovered that the `testcontainer-go` repo was renamed to `testcontainers-go` while trying to import `hashicorp/vault/api` whose repo requires the influxdb repo.

I didn't have time to familiar myself with influxdb nor its code base, so I don't have a PR available. On the surface it doesn't seem to be a massive change, but I am not sure if `testcontainers-go` also broke other interfaces with this change.

**Comment by vangent** [comment]
I ran into this too.

I tried to create a PR to fix it but I get a weird `exec: "bzr": executable file not found in $PATH` error when building. The `README` references this but only says how to fix on MacOS; I'm on Linux.

**Comment by vangent** [comment]
I spent some time trying to get this to work and failed. The code using `testcontainers-go` doesn't seem to be run during tests. I also got errors like this:

```
go: verifying github.com/docker/docker@v1.13.1: checksum mismatch                                                                                   
        downloaded: h1:5VBhsO6ckUxB0A8CE5LlUJdXzik9cbEbBTQ/ggeml7M=                                                                                 
        go.sum:     h1:IkZjBSIc8hBjLpqeAbeE5mca5mNgeatLHBy3GO78BWo=                                                                                 
```

**Comment by F21** [comment]
@vangent I have seen similar issues before. I believe part of the problem is because there was some changes to how the checksum was calculated between certain Go 1.11 patch releases. My usual fix is to delete everything in `$GOPATH/pkg/mod/` and try again. If it doesn't work, then delete the `go.sum` file and `go mod` should regenerate it.

**Comment by vangent** [comment]
Sorry, I'm not comfortable doing that for someone else's project. This should be a trivial change for a regular contributor; 
https://github.com/influxdata/influxdb/blob/master/vault/secret_test.go#L13

just needs to be updated to reference `github.com/testcontainers/testcontainers-go` (note the extra "s").

**Comment by mark-rushakoff** [comment]
> go: verifying github.com/docker/docker@v1.13.1: checksum mismatch        

The correct solution here is to upgrade to the most recent version of Go (1.11.5), since old versions (1.11.0 - 1.11.3) calculated the checksum incorrectly. After upgrading, you probably need to run `go clean -modcache` so that your system pulls the repository again and calculates the checksum correctly.
