### ISSUE TITLE
InfluxQL modulo operator on WHERE clause for timestamp `now()` function

### ISSUE THREAD

**Issue by wisn** [influxdata/influxdb#11200]
I want to query my records from today at `00.00` to `now()`. The problem is that I want to do this dynamically so I need to manipulate the timestamp using `now()` function.

Here is the query as an example.

```
SELECT SUM("something")
FROM "any_table_whatsoever"
WHERE time >= (now() - (now() % 86400) - (now() % 3600))
```

Here is the response.

```
error parsing query: found %, expected ) at line 3, char 29
```

It seems InfluxQL doesn't support modulo over timestamp.
I also think that's I might treat it wrongs.
For your information, I'm using InfluxQL on Grafana.

Are there any alternatives to achieve this?

**Comment by neerolyte** [comment]
Would be great to have an update on this despite stalebot closing it...
