### ISSUE TITLE
task: section when editing a script isn't calculated correctly

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#11289]
seems like editing a task doesn't calc the offset properly. see gif

![kapture 2019-01-18 at 9 03 44](https://user-images.githubusercontent.com/4805997/51401757-73e75080-1b00-11e9-8ed4-26b9310e1ea9.gif)

**Comment by chnn** [comment]
We investigated this same bug in Chrongraf 1.7 and didn't find a solution. It might be a bug within the CodeMirror library. See https://github.com/influxdata/applications-team-issues/issues/161

Additionally, I can't reproduce it locally.

Continue? [Y/n]
