### ISSUE TITLE
No longer require @ for filepath arguments in the influx CLI

### ISSUE THREAD

**Issue by sanderson** [influxdata/influxdb#11282]
The 2.0 `influx` CLI requires and `@` character at the beginning of a file paths. From a quality of life perspective, this breaks file path autocompletion and can make typing full paths rather tedious. I believe this could be passed as a flag:

```sh
-i, --input

# using a file path
influx task create -i /path/to/task-script.flux

# opening a pipe
influx task create -i -

# using raw flux
influx task create -i 'options task = { ... '
```

**Comment by sanderson** [comment]
`-i` may not be the appropriate flag. On some commands, this flag is already used for `--id`.

**Comment by mark-rushakoff** [comment]
As far as I know, we aren't using stdin for anything. I wouldn't want to encourage `echo abc | influx foo bar` over `influx foo bar "abc"`, but `influx foo bar < /path/to/whatever` is pretty natural.
