### ISSUE TITLE
In search of a standard influxdb docker image

### ISSUE THREAD

**Issue by allen13** [influxdata/influxdb#1129]
It would be nice to see a standard influxdb docker image under the influxdb namespace.  Currently the most popular image is [tutum-docker-influxdb](https://github.com/tutumcloud/tutum-docker-influxdb). Also I recently used this image as a reference to build a busybox single executable image [docker-influxdb-min](https://github.com/allen13/docker-influxdb-min) currently 18.02 MB.

**Comment by pauldix** [comment]
@jwilder, did you end up putting up an official docker image?

**Comment by jwilder** [comment]
@pauldix Not yet.  Still in progress.

**Comment by pires** [comment]
Any updates on this?

**Comment by abcfy2** [comment]
+1 for official ``TICK stack`` docker images.

**Comment by easyrasta** [comment]
+1 official image

**Comment by arthurgeek** [comment]
Would love docker images from InfluxData. Using the static binary would be awesome (can't use the binaries right now, since they're still dynamically linked to libgcc).

**Comment by jsternberg** [comment]
We are currently trying to get official images merged into the official docker images repository. I'm closing this in favor of the PR for doing that at docker-library/official-images#1583.

Thanks for your interest and patience! We hope to have those images merged into the official project soon.
