### ISSUE TITLE
Cannot add non existent task option through api

### ISSUE THREAD

**Issue by bthesorceror** [influxdata/influxdb#11324]
When I try to add a property through the api i.e. offset and that task property is not in the script then I get an error. Once I add it to the script I can update. In the UI I should be able to provide a offset without changing the script.

**Comment by bthesorceror** [comment]
example error

```
cannot find property 'offset' in object expression
```

**Comment by docmerlin** [comment]
Ok, this looks like it is a bug in Flux, I will make a flux bug.

**Comment by docmerlin** [comment]
This is fixed in flux, closing now, it will be fixed in influxdb when the next version of flux gets merged in.
