### ISSUE TITLE
Organization: creating Organization with session authentication scheme does not work

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#11344]
When I trying create Organization with the [session auth scheme](https://github.com/influxdata/influxdb/blob/1811ed43b4e8f9fccf6c754e5ba69a82fbefe01a/http/authentication_middleware.go#L46) then the response is unsuccessful with an error:

```bash
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
X-Platform-Error-Code: unauthorized
Date: Mon, 21 Jan 2019 09:16:08 GMT
Content-Length: 62

{"code":"unauthorized","message":"write:orgs is unauthorized"}
```

Here are shell commands to reproduce:

```bash
$ docker pull quay.io/influxdb/influx:nightly
$ docker run --detach --publish 9999:9999 quay.io/influxdb/influx:nightly

# OnBoarding
$ curl -i -X POST http://localhost:9999/api/v2/setup -H 'accept: application/json' \
    -d '{
            "username": "my-user",
            "password": "my-password",
            "org": "my-org",
            "bucket": "my-bucket"
        }'

# Login and store cookies
$ curl -i -X POST http://localhost:9999/api/v2/signin -H 'accept: application/json' \
    -H 'Authorization: Basic bXktdXNlcjpteS1wYXNzd29yZA==' -D 'header.txt'

# Cookie value
$ cat ./header.txt | grep Set-Cookie | cut -d ' ' -f2

# Create new Organization
$ curl -i -X POST http://localhost:9999/api/v2/orgs -H 'accept: application/json' \
    --cookie session=VqYT53EwN23PJXT9ZlmCm0Tb0i0a8i2odYQ9OSPOnkmM-KPv823mv7SOXIcpE9GLDqEyGFJzIZJnkznzeDMpPg== \
    -d '{"name":"New Org Name"}'

# Response

HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
X-Platform-Error-Code: unauthorized
Date: Mon, 21 Jan 2019 09:25:24 GMT
Content-Length: 62

{"code":"unauthorized","message":"write:orgs is unauthorized"}
```

The possible solution is add all my permissions after initialised [MePermissions](https://github.com/influxdata/influxdb/blob/1811ed43b4e8f9fccf6c754e5ba69a82fbefe01a/bolt/session.go#L113):

```go
authorizations, err := c.findAuthorizations(ctx, tx, platform.AuthorizationFilter{})
if err != nil {
	return nil, &platform.Error{
		Err: err,
	}
}
for _, a := range authorizations {
	ps = append(ps, a.Permissions...)
}
```

@desa

**Comment by desa** [comment]
Thanks for making this issue. This was partially intentional. Specifically, I was unsure about who should be allowed to create organizations. For that reason, I didn't grant the session permission to create users. At the moment, the only entity that can create users is the onboarding authorization token.

**Comment by bednar** [comment]
@desa thanks for response. The same problem is also in "InfluxDB 2.0 UI" when I trying to create an organization nothings happened and error is displayed in "web developer tools".

The creation of organizations will be removed from UI?

<img width="1316" alt="influxdb 2 0 - create organization" src="https://user-images.githubusercontent.com/455137/51516816-e9ad2e00-1e18-11e9-9d71-e0e94a112f70.png">
<img width="1331" alt="influxdb 2 0 - create organization - console error" src="https://user-images.githubusercontent.com/455137/51516822-f3cf2c80-1e18-11e9-9af8-93ef537f54d8.png">

**Comment by desa** [comment]
This is a good question for @russorat. The issue I was potentially trying to avoid is that if any user can create organizations. I can add the privilege to create orgs on the session if that is needed for alpha.

**Comment by bednar** [comment]
Thx @desa
