### ISSUE TITLE
InfluxDB fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by amfergom** [influxdata/influxdb#11343]
Hello:

I am using influxdb to storage weather data, the data was created from a simulator.
I have stored 2 years and appear the following problem:

ts=2019-01-21T07:55:36.355392Z lvl=info msg="Reading file" log_id=0D7rH4ml000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/_internal/monitor/361/_02188.wal size=799311
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x120f230, 0x16)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc1cc000000, 0x4000000, 0x1d45398)
	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x1d2b6a0, 0x4000000, 0x1d2b6b8, 0x7efd35b14d18)
	/usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x1d2b6a0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x1d2b6a0, 0x1, 0x1d453a8, 0x400)
	/usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x1d2b6a0, 0x1, 0x25, 0x7efd35d97fff)
	/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x1d2b6a0, 0x1, 0x7efd35010025, 0x7efd35b14d18)
	/usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.(*mcentral).grow(0x1d2d318, 0x0)
	/usr/local/go/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0x1d2d318, 0x7efd35b14d18)
	/usr/local/go/src/runtime/mcentral.go:106 +0x2f8
runtime.(*mcache).refill(0x7efd86a05000, 0xc000046025)
	/usr/local/go/src/runtime/mcache.go:122 +0x95
runtime.(*mcache).nextFree.func1()
	/usr/local/go/src/runtime/malloc.go:749 +0x32
runtime.systemstack(0x45b7e9)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1229

goroutine 15 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc00067ab40 sp=0xc00067ab38 pc=0x45b8e0
runtime.(*mcache).nextFree(0x7efd86a05000, 0xc1b0d30c25, 0x1, 0x3b, 0xc1cbacec60)
	/usr/local/go/src/runtime/malloc.go:748 +0xb6 fp=0xc00067ab98 sp=0xc00067ab40 pc=0x40d4a6
runtime.mallocgc(0x120, 0x0, 0x1383b3e2033e2700, 0xc00067acb0)
	/usr/local/go/src/runtime/malloc.go:903 +0x793 fp=0xc00067ac38 sp=0xc00067ab98 pc=0x40ddf3
runtime.rawbyteslice(0x105, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:271 +0xa0 fp=0xc00067ac78 sp=0xc00067ac38 pc=0x448f30
runtime.stringtoslicebyte(0x0, 0xc1cbb0c000, 0x105, 0xe0, 0xc1cbacec60, 0x1)
	/usr/local/go/src/runtime/string.go:160 +0xb5 fp=0xc00067acc0 sp=0xc00067ac78 pc=0x448925
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Cache).WriteMulti(0xc0004106e0, 0xc1999a2de0, 0xc00067b178, 0x134ec20)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:343 +0x275 fp=0xc00067ae60 sp=0xc00067acc0 pc=0xe9ac45
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*CacheLoader).Load.func1(0xc00067b288, 0xc0026c68c0, 0xc00067b278, 0xc0004106e0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:747 +0x64c fp=0xc00067b238 sp=0xc00067ae60 pc=0xf1464c
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*CacheLoader).Load(0xc0026c68c0, 0xc0004106e0, 0x6a8, 0xc0026c68c0)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:758 +0xa6 fp=0xc00067b2a8 sp=0xc00067b238 pc=0xe9c516
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).reloadCache(0xc00032d7a0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2252 +0x186 fp=0xc00067b3f0 sp=0xc00067b2a8 pc=0xed0596
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).Open(0xc00032d7a0, 0xc000541400, 0xc0000afd40)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:745 +0x2a0 fp=0xc00067b478 sp=0xc00067b3f0 pc=0xec6060
github.com/influxdata/influxdb/tsdb.(*Shard).Open.func1(0xc000528d80, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/shard.go:340 +0x36d fp=0xc00067b6a8 sp=0xc00067b478 pc=0x9c6ecd
github.com/influxdata/influxdb/tsdb.(*Shard).Open(0xc000528d80, 0xc000541440, 0x2c)
	/go/src/github.com/influxdata/influxdb/tsdb/shard.go:351 +0x2f fp=0xc00067b700 sp=0xc00067b6a8 pc=0x9aa9bf
github.com/influxdata/influxdb/tsdb.(*Store).loadShards.func1(0xc0002007e0, 0xc000131000, 0xc0001afda0, 0xc000200840, 0x11edba0, 0xc000112ea0, 0xc000234fa0, 0xc000214fd7, 0x9, 0xc00036d581, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/store.go:404 +0x517 fp=0xc00067bf78 sp=0xc00067b700 pc=0x9c8187
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00067bf80 sp=0xc00067bf78 pc=0x45d9c1
created by github.com/influxdata/influxdb/tsdb.(*Store).loadShards
	/go/src/github.com/influxdata/influxdb/tsdb/store.go:362 +0x19d6

goroutine 1 [chan receive, 1 minutes]:
github.com/influxdata/influxdb/tsdb.(*Store).loadShards(0xc000131000, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/store.go:421 +0x644
github.com/influxdata/influxdb/tsdb.(*Store).Open(0xc000131000, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/store.go:221 +0x25e
github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open(0xc00032c120, 0xc0002f4100, 0xc00032c120)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:435 +0x857
github.com/influxdata/influxdb/cmd/influxd/run.(*Command).Run(0xc0000d31e0, 0xc00003a1b0, 0x0, 0x0, 0x0, 0xc00003a1b0)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/command.go:149 +0xe2d
main.(*Main).Run(0xc00030bf58, 0xc00003a1b0, 0x0, 0x0, 0xc00030bf68, 0xf2ffef)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:81 +0x14f
main.main()
	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:45 +0x12f

goroutine 5 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 10 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7efd869a9f00, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000107318, 0x72, 0xc00050ca00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000107318, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc000107300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc000107300, 0xc0000586c0, 0x3, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000f838, 0x475a0e, 0xc0001af4a0, 0x47593d)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).Accept(0xc00000f838, 0xc000058740, 0x1, 0x9fd38e, 0x123c301)
	/usr/local/go/src/net/tcpsock.go:260 +0x47
github.com/influxdata/influxdb/tcp.(*Mux).Serve(0xc0001af4a0, 0x135fb80, 0xc00000f838, 0xc00000f838, 0x0)
	/go/src/github.com/influxdata/influxdb/tcp/mux.go:75 +0x92
created by github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open
	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:386 +0x28b

**Comment by nikunjdnp** [comment]
Hi @tkyocum, I am also getting the same error. It is running as a service in Ubuntu and total memory is 4GB.
