### ISSUE TITLE
Add a button for viewing telegraf instructions in the telegrafs list

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#11481]
right now, once i close the verify step, there's no way for a user to re-install the telegraf config.

Add button that says "Instructions" on hover in the telegraf list row.
Clicking this button opens an overlay displaying the same instructions that appear in the verify step

**Comment by ischolten** [comment]
@russorat, is this just essentially so they can see the instructions again? currently going to the verify step will update or create the telegraf config based on whether it exists yet or not, so that should probably not happen when we reopen
