### ISSUE TITLE
Add the ability to view the runs of a specific task

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#11501]
as a task user
with admin
when i view the list of tasks 
then i would like to view the runs of a specific task

**Comment by timhallinflux** [comment]
access to log data which is specific to the tag would help in debugging.  
Need the ability to filter the time range for the log access...that would correlate to task runs.

**Comment by mavarius** [comment]
Design Prototype: [https://drive.google.com/open?id=1dRj2NIL6JDZdikjzjRCXfu8A01s8dfDgXDYY9q5wlHI](https://drive.google.com/open?id=1dRj2NIL6JDZdikjzjRCXfu8A01s8dfDgXDYY9q5wlHI)
