### ISSUE TITLE
Restore command consuming only the latest file for each shard

### ISSUE THREAD

**Issue by adampl** [influxdata/influxdb#11524]
I create an incremental portable backup every 6 hours (with the time range starting 6 hours ago) and all backup files always go into the same directory. Each backup process creates files for all shards existing in the database, though only the last 1 or 2 files contain any data, as the shard duration is 1 day. The data for each shard are therefore split between 4 to 5 files (remaining shard files don't contain any data). 

The problem is that (according to the logs) the `restore` command consumes only the latest file for each shard, ignoring all previous files, so the restored database ends up incomplete (max. 25% of all data).

I believe the problem lies [here](https://github.com/influxdata/influxdb/blob/26afe32611a36fd61dcf017658ab5ab316f56a5e/cmd/influxd/backup_util/backup_util.go#L195-L198):
```golang
e := shards[sh.ShardID]
if e == nil || sh.LastModified > e.LastModified {
    shards[sh.ShardID] = &sh
}
```
As you see, the `shards` mapping can contain only one shard file for each shard ID.

Obviously, it's wrong to assume that each shard can be in just one file in case of incremental backups. Moreover, the `backup` command always creates shard files for all shards (regardless of the start-end range), so the actual result in the case described above is that only the latest 1 or 2 shards are populated with data, as the latest files for previous shards are empty (while older, non-empty files are ignored).

Instead, the `restore` command should load all files present in the directory.

**This issue makes incremental backups totally useless.**
Unfortunately, I'm not familiar with the Go language, not to mention InfluxDB internals :(

**Comment by adampl** [comment]
This shouldn't be closed.

**Comment by adampl** [comment]
This is really important.

**Comment by hjsjy** [comment]
i have the same problem with you.
