### ISSUE TITLE
Telegraf UI should join two or more plugins into one telegraf config

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/influxdb#11527]
Telegraf UI should join two or more plugins into one config

git: bd3c9cc75cbb38aad54aae23f39bfe6df32875b4 (in master 4 after alpha)

Steps to reproduce:
1. in new influxdb2, create eg docker telegraf plugin with endpoint unix:///var/run/docker.sock 
2. then create the second plugin, eg system one

This is the result in UI, there are two configs...
![image](https://user-images.githubusercontent.com/8028110/51688839-b1af1200-1ff5-11e9-832c-eab5461761a1.png)

Observations:

* There is no hint in the table which config is the docker one and which is the system one, because both the config lines are named equally. The two lines look like duplicity.
* When I download one config and run telegraf, I can use system monitoring only
* When I download the other config and run telegraf, I can use docker monitoring only

Proposed solution:
* As user who has one telegraf I want influxdb2 to be able to provide me with just one config having both configurations in order I can listen to more than 1 plugin from one instance of telegraf.
* As user I want to have version number in the config name or new column with timestamp, so that I do not see 2 lines with same information (duplicate lines) at the /organizations/034c0f2d08bc9000/collectors_tab  

Workaround: do a manual join of the two configs on localhost 

The issue seems to relate to #10771

**Comment by goller** [comment]
good call @ivankudibal ... would be nice to have it only one configuration

**Comment by alexpaxton** [comment]
@ivankudibal we are working on allowing users to name telegraf configs. Your suggestions are great, thank you for making an issue!
