### ISSUE TITLE
On import create dashboard from template, also create any included resources

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#11533]
as a user
with admin
when i see a list of resources (dashboard/task/variable for now)
then i would like the ability to export resource as JSON, 
and import it back from that JSON, to be instantiated as that resource. 

If imported JSON is not valid for that resource, I would like to see an error. 

what happens to other resources bundled with that resource? like variables included in dashboard?

**Comment by ebb-tide** [comment]
closed by: https://github.com/influxdata/influxdb2-js/pull/42
