### ISSUE TITLE
influx repl: add command to terminate session

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/influxdb#11530]
How can I quit influx cli?

Question:
* Are there better ways how to exit from the console other than #11529 ?

I tried exit, bye, quit commands with no luck

**Comment by mark-rushakoff** [comment]
[Press ctrl-d to send an EOF](https://unix.stackexchange.com/questions/110240/why-does-ctrl-d-eof-exit-the-shell) to terminate the REPL.

I'll retitle the issue to support a command to quit.
