### ISSUE TITLE
InfluxDB 2.0 Feature Request - Export graph as image

### ISSUE THREAD

**Issue by alexbowers** [influxdata/influxdb#11554]
The only feature keeping me currently using Grafana at the moment is the ability to take a URL for a specific graph and resize it on the fly as a static image.

We use this for Screenly (screenly.io) dashboards of our stats, since it does not take well to the heavy JS for grafana or Chronograf, and the interactivity is useless in a dashboard screen with no mouse to interact with it.

If this feature can be implemented, that will be the only hurdle we have to move fully into the Influx setup.

**Comment by alexbowers** [comment]
Please reopen.

**Comment by alexbowers** [comment]
Please reopen.

**Comment by gazzat5** [comment]
Please reopen!

**Comment by DeWarmte** [comment]
+1 for feature request. 

If the export could also be an interactive graph this would be even more awesome. Query once and download the resulting graph data for use whenever. Expecially usefull for graphs that require some computational time and for which only specific time windows are interested such that filling new buckets with aggregated data would be cumbersome.

**Comment by hflatoey** [comment]
+1 for feature request.

**Comment by alexbowers** [comment]
Please reopen

**Comment by ser** [comment]
i need this!

**Comment by fdebrabander** [comment]
Would be very useful indeed.

**Comment by BrentonPoke** [comment]
I also need this, as my paper just got accepted and I was never able to screenshot good-enough quality graphs.

**Comment by Mr-Groch** [comment]
+1

**Comment by khataev** [comment]
+1

**Comment by WJ4IoT** [comment]
+1
