### ISSUE TITLE
influx 2.0 alpha "system dashboard" bucket name still "default" 

### ISSUE THREAD

**Issue by jordo1138** [influxdata/influxdb#11588]
super stoked for influxdb 2.0, running latest docker alpha image using the "Getting Started" guide
`docker run --name influxdb -p 9999:9999 quay.io/influxdb/influxdb:2.0.0-alpha`
Then in the CLI, setup default user/org etc
then browsed to localhost:9999 where I generated a telegraf config for system and docker metrics, added in my docker endpoint running on the mac
ran the latest mac version of telegraf 1.9.3 and started it with the config.toml which I downloaded from the localhost:9999 telegraf section after it was generated when choosing the plugins.
I can see the data fine for the system and docker plugins in the data explorer to create queries, but the default System dashboard gave me this error
<img width="1569" alt="screen shot 2019-01-25 at 1 43 47 am" src="https://user-images.githubusercontent.com/8525512/51730015-ecd83200-2043-11e9-8527-0784938c325b.png">

little checking into the dashboard shows that the issue is because the bucket name is still "default" for all the queries in this dashboard, and didn't take my bucket name I chose when did `influx setup` from the CLI. Changing the bucket name to the correct name fixes each of the panels to show the right data.
<img width="690" alt="screen shot 2019-01-25 at 2 00 16 am" src="https://user-images.githubusercontent.com/8525512/51730389-49881c80-2045-11e9-9d0b-418b7b11326b.png">

issue is in the proto system json,, the queries seems to be expecting a default bucket chosen, not sure if that's explicitly called "default" when setting up influx if you don't declare a different name but I guess it would be
https://github.com/influxdata/influxdb/blob/64285764d31f296607ed08958e30eeafd2acbf92/proto/system.json

**Comment by timhallinflux** [comment]
Yep.  We need to confirm which bucket you want these pre-built dashboards to bind to when they are pulled in.

Thank you for your interest and for filing this issue!

**Comment by ebb-tide** [comment]
closed by https://github.com/influxdata/influxdb/pull/12533. Dashboards added to accompany telegraf configs are now created by templates which can accept variables, rather than protoboards which could not. However, templates are initialized at onboarding, and will not  exist for users who have previously gone through onboarding.
