### ISSUE TITLE
InfluxDB 2.0: Task API return Internal Server Error (500) instead Not Found (404)

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#11589]
The Internal Server Error (500) is returned when I trying cancel the run of a Task that does not exist:

```json
-> DELETE 
-> http://127.0.0.1:9999/api/v2/tasks/034cf54e5bb39000/runs/034cf54f99339000

<- 500 
<- Internal Server Error
<- {"code":"internal error","message":"An internal error has occurred.","error":"run not found"}
```

The [task_service](https://github.com/influxdata/influxdb/blob/master/http/task_service.go) has to return 404 when is used [ErrTaskNotFound](https://github.com/influxdata/influxdb/blob/5570e5ef44cd58d22e3ad686edcaf2859aee5722/task/backend/store.go#L24) or [ErrRunNotFound](https://github.com/influxdata/influxdb/blob/5570e5ef44cd58d22e3ad686edcaf2859aee5722/task/backend/store.go#L36).

**Comment by bednar** [comment]
Hi @mark-rushakoff 

Can you also fix the 500 that is returned if the [query_loader.FindRunByID](https://github.com/influxdata/influxdb/blob/37b189174f7eb81176eb2b50829bf2ef539a0ac4/task/backend/query_logreader.go#L140) didn't find the run?

Here is a patch for that:

[NotFound_for_LogReader_error.txt](https://github.com/influxdata/influxdb/files/2803190/NotFound_for_LogReader_error.txt)

Thx

**Comment by mark-rushakoff** [comment]
@bednar Thanks for finding that - I have a slightly different approach to fix that in https://github.com/influxdata/influxdb/pull/11645.

**Comment by bednar** [comment]
@mark-rushakoff Thanks for fix that. Your approach is definitely better ;)
