### ISSUE TITLE
InfluxDB 2.0: There is no way how to set password to the created User (API)

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#11590]
The Internal Server Error (500) is returned when I trying update the user password (the user was created by User HTTP API):

1/ Authenticated by Token

```
-> PUT 
-> http://127.0.0.1:9999/api/v2/users/034cfc4790f1e000/password
-> {"password":"strong-password"}

<- 500 
<- Internal Server Error http://127.0.0.1:9999/api/v2/users/034cfc4790f1e000/password (2ms)
<- Header: X-Influx-Error: invalid basic auth
```

This error is caused because the [decodePasswordResetRequest](https://github.com/influxdata/influxdb/blob/5570e5ef44cd58d22e3ad686edcaf2859aee5722/http/user_service.go#L103) expect the Basic Authorization header, but we are authenticated by Token.

2/ Authenticated by Session

```
-> PUT 
-> http://127.0.0.1:9999/api/v2/users/034cfc4790f1e000/password
-> {"password":"strong-password"}

<- 500 
<- Internal Server Error http://127.0.0.1:9999/api/v2/users/034cfc4790f1e000/password (2ms)
<- Header: X-Influx-Error: crypto/bcrypt: hashedSecret too short to be a bcrypted password
```

The error is caused by [CompareHashAndPassword function](https://github.com/influxdata/influxdb/blob/5570e5ef44cd58d22e3ad686edcaf2859aee5722/bolt/basic_auth_service.go#L58) because [hash](https://github.com/influxdata/influxdb/blob/5570e5ef44cd58d22e3ad686edcaf2859aee5722/bolt/basic_auth_service.go#L56) is nil.

**Comment by kelwang** [comment]
talked this with @desa, update password will need to re-input the old password.
for reset, we will have to create a special one-time session, which expires in 15 mins, to reset the password.

**Comment by myqqai** [comment]
how to set password to the created User (API)？

1.cli run: influx user create username
2. curl {{host}}/api/v2/users/{{userID}}/password --body {"password": "mypassword"}
![image](https://user-images.githubusercontent.com/8164404/64749017-aa1d8880-d546-11e9-9eae-cc2c5523b6b8.png)

I don't really understand 
what shout i do
