### ISSUE TITLE
"panic:runtime error" on prometheus remote_read

### ISSUE THREAD

**Issue by ZyanKLee** [influxdata/influxdb#11638]
During setup of a test environment where a prometheus should write/read its metrics to/from influxdb via the remote_write / remote_read interfaces I encountered panic messages in the influxdb log:

https://paste.ubuntu.com/p/J8TD67qtKJ/

It seems like those were triggered by read's (I never saw a panic related to a write).

InfluxDB has been in version 1.7.3 and prometheus 2.6.0. I just now saw that prometheus 2.7.0 was released yesterday, but did not test with this version, yet.

Here is another snippet of the log, which shows the startup of influxdb docker container with provisioning:
https://paste.ubuntu.com/p/fnpqXzcKYX/

I disabled remote_read afterwards as we intend to let multiple prometheus instances only write to influxdb and connect grafana directly to the influxdb for displaying.

**Comment by dbellinghoven** [comment]
I actually fixed it with [this](https://github.com/influxdata/influxdb/pull/10591) pull request about a month ago but it doesn't seem to be getting much attention

**Comment by e-dard** [comment]
Fixed via https://github.com/influxdata/influxdb/pull/10591
