### ISSUE TITLE
Chronograf Flux tab crashing InfluxDB, 'fatal error: runtime: out of memory' 

### ISSUE THREAD

**Issue by digrich** [influxdata/influxdb#11633]
Recently I have started exploring Flux scripts on Chronograf UI and noticed that whenever I go to Flux tab which is having a simple script to query one measurement, it kills InfluxDB. 

Flux script:
---------------------
  from(bucket: "db1/autogen")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r._measurement == "measurement1" and (r._field == "field1"))
  |> window(every: autoInterval)
  |> mean()
  |> group(columns: ["_time", "_start", "_stop", "_value"], mode: "except")

Setup Details:
------------------ 
InfluxDB version: 1.7.3-1
Chronograf version: 1.7.7
Series Cardinality: ~200k
Container: Bare metal 
OS: CentOS 6.5 Linux version
RAM: 128 GB
TSI is enabled.

StackTrace: 
----------------------
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x123d974, , 0x16)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xdb54000000, 0x82c000000, 0x1da9518)
	/usr/local/go/src/runtime/mem_linux.go:/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc((0x1d8f780, , 0x82c000000, 0x7efef5ecab18, 0x7efef5ecab18, 0x7eff6abfcc98)
	/usr/local/go/src/runtime/malloc.go	/usr/local/go/src/runtime/malloc.go:619619 +0x1c7
runtime.(*mheap).growruntime.(*mheap).grow(0x1d8f780, 0x4152ac, 0x0)
	/usr/local/go/src/runtime/mheap.go/usr/local/go/src/runtime/mheap.go:920920 +0x42
runtime.(*mheap).allocSpanLocked(0x1d8f780, 0x4152ac, 0x1da9528, 0x434b75)
	/usr/local/go/src/runtime/mheap.go::848 + +0x337
runtime.(*mheap).alloc_m((0x1d8f780, 0x4152ac, 0x101, 0x1800000000)
)
	/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1(()
	/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc((0x1d8f780, 0x4152ac, 0xc017000101, 0xc0079b8780)
	/usr/local/go/src/runtime/mheap.go/usr/local/go/src/runtime/mheap.go:758758 +0x8a
runtime.largeAllocruntime.largeAlloc(0x82a558000, 0xc000430100, 0x5)
	/usr/local/go/src/runtime/malloc.go:1019 ++0x97
runtime.mallocgc.func1(()
		/usr/local/go/src/runtime/malloc.go/usr/local/go/src/runtime/malloc.go:914 +0x460x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 + +0x66
runtime.mstart()
		/usr/local/go/src/runtime/proc.go/usr/local/go/src/runtime/proc.go:1229

goroutine 169627 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc01866e808 sp=0xc01866e800 pc=0x45b890

runtime.mallocgc(0x82a5580000x82a558000, , 0x0, 0x539d04000, 0xd4a4c04000)
	/usr/local/go/src/runtime/malloc.go:913 +0x8960x896 fp= fp=0xc01866e8a8 sp=0xc01866e808 pc=0x40def6
runtime.growslice(0x11997e0, 0xd4a4c04000, 0x68844600, 0x68844600, 0x68844601, 0xd4a4c04000, 0x539d0400, 0x68844600)
	/usr/local/go/src/runtime/slice.go:197 +0x219 fp=0xc01866e910 sp=0xc01866e8a8 pc=0x444ba9
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations.(*fixedWindowTransformation).getWindowBounds(0xc00f688d10, , 0x157e150666fef0000x157e150666fef000, 0xc01cc990c0, , 0xc01a7afb00, 0x0)
		/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations/window.go:429429 +0x126 fp= fp=0xc01866e988 sp=0xc01866e910 pc=0xdb33d60xdb33d6
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations.(*fixedWindowTransformation).Process.func1(0x13a3d400x13a3d40, 0xc0123dc960, 0xc0123dc960, 0x1)
		/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations/window.go:340340 +0x126 fp=0xc01866eaa80x126 fp=0xc01866eaa8 sp=0xc01866e988 pc= pc=0xdbd176
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*floatTable).DoArrow(0xc0123dc960, 0xc01a7afb00, 0x0, , 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.gen.go:	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.gen.go:88 +0x940x94 fp=0xc01866eae0 sp= sp=0xc01866eaa8 pc=0xcf9fe4
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations.(*fixedWindowTransformation).Process(0xc00f688d10, 0x985c8830a4e2e770, 0xc92844ef6f1ff99b, 0x7efe96b7df10, 0xc0123dc960, 0x1931ef01, 0x2)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations/window.go:336 +0x9a2 fp=0xc01866ed28 sp=0xc01866eae0 pc=0xdb2322
:336 +0x9a2 fp=0xc01866ed28 sp=0xc01866eae0 pc=0xdb2322
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.processMessage(0x139ab00, 0xc00f688d10, 0x1388720, 0xc019110a40, 0xc00d0f9768, 0x5edf8d, 0xc01ced7050)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:199 +0x1fc fp=0xc01866ee30 sp=0xc01866ed28 pc=0xb9ce8c
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc0133af740, 0xa)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:156 +0xa1 fp=0xc01866eeb8 sp=0xc01866ee30 pc=0xb9cb01
, 0x5edf8d, 0xc01ced7050)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:199 +0x1fc fp=0xc01866ee30 sp=0xc01866ed28 pc=0xb9ce8c
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc0133af740, 0xa)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:156 +0xa1 fp=0xc01866eeb8 sp=0xc01866ee30 pc=0xb9cb01
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages-fm(0xa)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:137 +0x34 fp=0xc01866eed8 sp=0xc01866eeb8 pc=0xba0594
/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/transport.go:137 +0x34 fp=0xc01866eed8 sp=0xc01866eeb8 pc=0xba0594
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc0133af6e0, 0x1396480, , 0x1396480, 0xc01664f560)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go::126 + +0x4b fp=0xc01866efa0 sp=0xc01866eed8 pc=0xb857bb
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc0133af6e0, , 0x1396480, 0xc01664f5600xc01664f560)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:80 +0x950x95 fp=0xc01866efc8 sp= sp=0xc01866efa0 pc=0xb9e8250xb9e825
runtime.goexit(runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp= fp=0xc01866efd0 sp=0xc01866efc80xc01866efc8 pc=0x45d971

created by github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*poolDispatcher).Start

	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/dispatcher.go:61:61 +0x7e

goroutine goroutine 1 [chan receive, chan receive, 9 minutes]:
]:
main.(*Main).Run(0xc0006bdf58, 0xc0000d2070, 0xc0000d2070, 0x2, , 0x2, , 0xc0006bdf68, 0xf53846)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go::90 + +0x2d1
main.main(()
	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:45 + +0x12f

goroutine 19 [syscall, syscall, 9 minutes]:
os/signal.signal_recv((0x0)
	/usr/local/go/src/runtime/sigqueue.go::139 + +0x9c
os/signal.loop(()
	/usr/local/go/src/os/signal/signal_unix.go	/usr/local/go/src/os/signal/signal_unix.go:2323 +0x22
created by created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x410x41

goroutine 14 [IO wait [IO wait, 9 minutes minutes]:
internal/poll.runtime_pollWait(0x7eff90863f00, 0x72, , 0x0)
	/usr/local/go/src/runtime/netpoll.go:173:173 +0x660x66
internal/poll.(*pollDesc).wait(0xc00016e798, 0x72, 0x72, 0xc0000e2000, 0x0, 0x0)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go::85 +0x9a
internal/poll.(*pollDesc).waitRead((0xc00016e798, 0xffffffffffffff00, , 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go::90 + +0x3d
internal/poll.(*FD).Accept(0xc00016e780, , 0x0, 0x0, 0x0, , 0x0, , 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc00016e780, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go	/usr/local/go/src/net/fd_unix.go:238238 +0x42
net.(*TCPListener).accept(0xc000414360, 0x47595e, 0xc00003c840, , 0x47588d)
)
	/usr/local/go/src/net/tcpsock_posix.go::139 + +0x2e

net.(*TCPListener).Accept(0xc000414360, , 0x0, , 0x0, 0x0, 0x0)
)
	/usr/local/go/src/net/tcpsock.go::260 + +0x47
github.com/influxdata/influxdb/tcp.(*Mux).Serve(0xc00003c840, 0x13948000x1394800, 0xc000414360, 0xc000414360, 0x00x0)
		/go/src/github.com/influxdata/influxdb/tcp/mux.go:7575 +0x920x92
created by github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open
		/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:387 +0x28b

goroutine 15 [select]:
select]:
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control.(*Controller).run(0xc0001ca8f00xc0001ca8f0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control/controller.go/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control/controller.go:290 +0x21f
created by github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control.New

	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control/controller.go/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control/controller.go:106 +0x36a

goroutine 368 [chan receive, 8 minutes]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc000660d200xc000660d20, 0x1381480, 0xc000cdc870, 0xc0000fddc8, 0xc0000fddd0, 0xc00003cd80)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e

github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1((0xc00553a0a0, , 0xc000660d20, 0x1381480, , 0xc000cdc870, 0xc0000fddc80xc0000fddc8, 0xc0000fddd0, 0xc00003cd80)
		/go/src/github.com/influxdata/influxdb/services/subscriber/service.go::314 + +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312312 +0xff7

goroutine goroutine 366 [chan receivechan receive, 9 minutes]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc000660d200xc000660d20, 0x1381480, , 0xc000cdc870, 0xc0000fddc80xc0000fddc8, 0xc0000fddd0, , 0xc00003cd80)
		/go/src/github.com/influxdata/influxdb/services/subscriber/service.go::372 +0x4e0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1((0xc00553a0a0, 0xc000660d200xc000660d20, 0x1381480, 0xc000cdc8700xc000cdc870, 0xc0000fddc8, , 0xc0000fddd0, 0xc00003cd80)
		/go/src/github.com/influxdata/influxdb/services/subscriber/service.go::314 +0x65

created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 + +0xff7

**Comment by rbetts** [comment]
Flux currently is allocation heavy when many windows and groups are required; this will be addressed shortly in an upcoming flux release. Thanks for trying flux and giving this feedback.

**Comment by russorat** [comment]
@nisley noticed that Chronograf actually sets it's autoInterval variable to `0ms` which is crashing Flux.

**Comment by macd2** [comment]
Is there a quick and dirty fix in the meantime for this issue?
influx became unusable and is constantly crashing with  the Error: **fatal error: runtime: out of memory**

**Comment by russorat** [comment]
@macd2 we will be updating chronograf in the next day or two with the fix. The workaround would be to not use the flux builder with aggregates which is the only way it gets inserted in there.  If you have a query that is crashing, clear your browser storage to get rid of it.

**Comment by digrich** [comment]
I noticed similar behaviour with Grafana Flux Plugin also, not sure if it is also setting autoInterval variable to 0ms.
