### ISSUE TITLE
InfluxDB 2.0: User API - GetUserLog return Internal Server Error (500) instead Not Found (404)

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#11632]
The Internal Server Error (500) is returned when I trying retrieves a user log for a user that does not exist:

```bash
-> GET 
-> http://127.0.0.1:9999/api/v2/users/020f755c3c082000/log

<- 500 
<- Internal Server Error
<- {"code":"internal error","error":"oplog not found"}
```

I think that the [GetUserOperationLog](https://github.com/influxdata/influxdb/blob/37b189174f7eb81176eb2b50829bf2ef539a0ac4/bolt/user.go#L438) should return a [ENotFound](https://github.com/influxdata/influxdb/blob/37b189174f7eb81176eb2b50829bf2ef539a0ac4/errors.go#L14) error.

**Comment by zhulongcheng** [comment]
The `/log` endpoint returns a list of logs:
```
{
    "links": {
        "self": "/api/v2/users/034560b68654b000/log"
    },
    "log": [
        {
            "links": {},
            "description": "User Created",
            "time": "2019-01-19T17:51:11.897732+08:00"
        }
    ]
}
```

I think there are two things to do:
- check user existence, return a `UserNotFound` err if user not exist.
- if no logs for the user, return an empty list of logs.

@desa How do you think?

**Comment by bednar** [comment]
It is already fixed.
