### ISSUE TITLE
Influx 'drop series' do not work

### ISSUE THREAD

**Issue by nicolargo** [influxdata/influxdb#11653]
Hi all,

a strange beahaviour with InfluxDB 1.7.2:

Remove series with a where clause (host = "SCC-V3-SSA02.nutanix.indus") do not work. I try to restart the InfluxDB daemon, but do not solve the issue.

```
# influx
Connected to http://localhost:8086 version 1.7.2
InfluxDB shell version: 1.7.2
Enter an InfluxQL query

> use telegraf
Using database telegraf

> SELECT "status","host" FROM "exec_systemctl" WHERE ("service" =~ /^interio.*$/) GROUP BY host ORDER BY time DESC limit 1
...
name: exec_systemctl
tags: host=SCC-V3-SSA02.nutanix.indus
time                status host
----                ------ ----
1548951840000000000 0      SCC-V3-SSA02.nutanix.indus
...

> drop series from /.*/ where host = "SCC-V3-SSA02.nutanix.indus"

> SELECT "status","host" FROM "exec_systemctl" WHERE ("service" =~ /^interio.*$/) GROUP BY host ORDER BY time DESC limit 1
...
name: exec_systemctl
tags: host=SCC-V3-SSA02.nutanix.indus
time                status host
----                ------ ----
1548951840000000000 0      SCC-V3-SSA02.nutanix.indus
...
```

**Comment by thulle** [comment]
Influx 1.7.4 here, I'm seeing something similar.

I ran:
$ influx -database prometheus -execute 'drop series where job=node_exporter'
which seems to work:
$ influx -database prometheus -execute 'show series where job=node_exporter'|wc -l
0

But I can still see the series:
$ influx -database prometheus -execute 'show series'|grep job=node_exporter -c
14474
$ influx -database prometheus -execute 'show series'|grep node_zfs_zpool_nread
node_zfs_zpool_nread,__name__=node_zfs_zpool_nread,instance=andromeda:9100,job=node_exporter,monitor=prometheus,zpool=andromeda

And the data remains:
$ influx -database prometheus -execute 'select count(*) from node_zfs_zpool_nread'
name: node_zfs_zpool_nread
time count_value
---- -----------
0    4826

Restart didn't change anything.

**Comment by e-dard** [comment]
@nicolargo 

Use single quotes for string literals:

```
drop series from /.*/ where host = 'SCC-V3-SSA02.nutanix.indus'
```

Please see the docs here about using single versus double quotes: https://docs.influxdata.com/influxdb/v1.7/troubleshooting/frequently-asked-questions/#when-should-i-single-quote-and-when-should-i-double-quote-in-queries
