### ISSUE TITLE
task: store authorizationID with task metadata

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#11668]
1. Add a new field, AuthorizationID, to StoreTaskMeta.
2. When a new task is created, take the AuthorizationID associated with the create request, and store it with the StoreTaskMeta.
3. Outgoing requests originated from a task -- particularly, such as requests to the query service -- should associate that AuthorizationID with that request's context.
4. If the authorization ID is invalid when the task executes, continue to run and fail; do not deactivate the task.

**Comment by mark-rushakoff** [comment]
I have WIP at https://github.com/influxdata/influxdb/tree/feat/task-authorization which covers most of this issue and #11669, but I need some advice on the API specifics for updating authorizations.

1. When creating a new task, the intent is to associate that task with the authorization ID of the request to create the new task. Should we support an override during creation, or should we say you must create the task with your current token/authz and then update the task to use a different token/authz?
2. What should the API look like for updating the authorization ID on an existing task? The WIP adds a new key, `authorizationID`, to the task update request object (as of this moment it's a code-only update, the swagger hasn't been updated yet). We have the option of switching it to the user specifying a token instead -- I think that's probably a more natural experience. We would still store the authorization ID in the backend in that case.
3. When updating a task's authorization ID, I think we need to verify that the requester has write permission for the task and read permission for the token/authorization. Does that sound sufficient/correct?

/cc @desa @goller

**Comment by desa** [comment]
> 1. ... Should we support an override during creation, or should we say you must create the task with your current token/authz and then update the task to use a different token/authz?

I think supplying an optional override makes sense.

> 2. What should the API look like for updating the authorization ID on an existing task? The WIP adds a new key, `authorizationID`, to the task update request object (as of this moment it's a code-only update, the swagger hasn't been updated yet). We have the option of switching it to the user specifying a token instead -- I think that's probably a more natural experience. We would still store the authorization ID in the backend in that case.

I think specifying the token on update makes sense.

> 3. When updating a task's authorization ID, I think we need to verify that the requester has write permission for the task and read permission for the token/authorization. Does that sound sufficient/correct?

Sounds correct to me.


---

The only question I have is what if the task was created via the UI where there isn't an associated authorization. I think during that call, we had talked about making a special authorization that was the users maximal privilege and then having various sessions point at that authorization, but that has yet to be implemented. Thoughts @goller 

An alternative would be to just require that a task always have an authorization specified, which kind of makes sense. Though, we'd need UI for that. cc @russorat

**Comment by mark-rushakoff** [comment]
Thanks @desa, I'll move my branch forward  with an optional token override during creation, and with preferring token rather than authz ID during update.

I'm not completely up to speed on how authorizations tie in to UI sessions, so I'm not going to do anything special on my end to handle that at the moment.

**Comment by mark-rushakoff** [comment]
I suppose we should require a token to set the authorization, but report back the authorization ID, so that the token isn't exposed on a read operation. Luckily the swagger already has a separate definition for TaskCreateRequest vs a Task.
