### ISSUE TITLE
readOnly properties of create authorization endpoint should not be included in requests. 

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#11714]
POST request body for the Authorization endpoint has following elements with `readOnly: true` properties:
`id`, `token`, `userID`, `user`, `org` and `links`.  Since these elements has readOnly set to true, then they should only be included in `responses` and not in the `requests`, but I can pass `userID` as part of a request and it won't be ignored (as well as `user` and `org`), i.e. the same userID that is passed to the request will be returned in the response.
- Should the swagger doc be changed to remove `readOnly` properties from `userID`, `user` and `org`?
- Permission resource can be defined with `orgID` and `org`. Since `orgID` element is already required, should these two elements, `orgID` and `org`  be removed?

Reference: swagger.yml

**Comment by goller** [comment]
@gshif would you add your request and response JSON structures?

**Comment by gshif** [comment]
- Creat a test user:
> requests.post('http://localhost:9999/api/v2/users', data='{"name":"u_1"}', headers=headers)

-  Create test org:
> requests.post('http://localhost:9999/api/v2/orgs',data='{"name":"b","status:":"active"}' , headers=headers

- Create authorization for the above test user:
> requests.post('http://localhost:9999/api/v2/authorizations', data='{"orgID":"035c17edbd97a000", "userID":"035c1869c297a000", "permissions":[{"action":"write","resource":{"type":"buckets"}}]}', headers=headers)

- Response:
> {u'status': u'active', u'description': u'', u'links': {u'self': u'/api/v2/authorizations/035d0f7f1d17a000', u'user': u'/api/v2/users/035c1869c297a000'}, u'userID': u'035c1869c297a000', u'token': u'd0LBLLShwT7fXBl9tolPz69peR8z_9gUnBkN12QHRK8ExOJyf_iCA85pAvQin-9F6Babhzczzj8KJrcqqro5WQ==', u'orgID': u'035c17edbd97a000', u'user': u'u_1', u'org': u'b', u'id': u'035d0f7f1d17a000', u'permissions': [{u'action': u'write', u'resource': {u'type': u'buckets'}}]}

**Comment by gshif** [comment]
If I create an authorization without passing a `userID`, then `admin user`'s id and name will be used:
- requests.post('http://localhost:9999/api/v2/authorizations', data='{"orgID":"035c17edbd97a000", "permissions":[{"action":"write","resource":{"type":"buckets"}}]}', headers=headers)

- response:
> status  ---->  active
description  ---->  
links  ---->  {u'self': u'/api/v2/authorizations/035c21a84f97a000', u'user': u'/api/v2/users/035c17eda4d7a000'}
userID  ---->  035c17eda4d7a000
token  ---->  eFeCnyuJzE-2L3O1hJNRZP2jToM2_UAzWAjD7AxwxsEftd57ZrmVo3bVW7JVJc64jy05YJgpAQlK6jzPcKYYyA==
orgID  ---->  035c17edbd97a000
user  ---->  admin_user
org  ---->  d
id  ---->  035c21a84f97a000

**Comment by goller** [comment]
We'll need to revert this PR:
https://github.com/influxdata/influxdb/commit/a3541b22d455584b8c0d7f3c97a6027394d9837c#diff-baac977c6f31754f1f789e8bef5924fcR156

/cc @desa

**Comment by goller** [comment]
Closed in https://github.com/influxdata/influxdb/pull/11722
