### ISSUE TITLE
Can't add labels to things

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#11734]
![kapture 2019-02-06 at 14 50 39](https://user-images.githubusercontent.com/10937678/52379195-9f35cf00-2a1e-11e9-8768-52698ce276d3.gif)

**Comment by alexpaxton** [comment]
This seems intertwined with #11624 and #11774

**Comment by OfTheDelmer** [comment]
Could not reproduce #11774 but it may have been resolved by the labels api fixes. This issue seems like a dupe of #11624
