### ISSUE TITLE
Data explorer: Empty bucket, deleting last card throws an error

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#11753]
to repro, delete your .influxdbv2 folder
go through onboarding
do not load any data
go to data explorer
delete the card that says no tags found

![image](https://user-images.githubusercontent.com/4805997/52434844-2fc6ea80-2ac5-11e9-9d96-db410882130f.png)

**Comment by OfTheDelmer** [comment]
Confirmed that this is still reproducible on master
![screen shot 2019-02-12 at 11 13 46 am](https://user-images.githubusercontent.com/4994741/52649999-603cc900-2eb7-11e9-8ba5-69d68013d9d4.png)

Similar to the query editor where a user cannot remove the only tab do we want to prevent removal of the only tag card in the explorer? @russorat @alexpaxton

**Comment by russorat** [comment]
see #11012
