### ISSUE TITLE
Drop Measurement query crashes Influxdb

### ISSUE THREAD

**Issue by ADados** [influxdata/influxdb#11759]
**System info:** CentOS release 6.10, influxdb 1.7.2

**Steps to reproduce:**

`drop measurement "delete_me";`

**Expected behavior:** 

measurement to be dropped

**Actual behavior:** 

Influxdb crashed after 2 hours

Inside the log file:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x987826]

goroutine 8757975 [running]:
github.com/influxdata/influxdb/tsdb.(*epochTracker).WaitDelete(0x0, 0xc68488e2d0, 0x626e, 0x1d44760, 0x1, 0x0)
    /go/src/github.com/influxdata/influxdb/tsdb/epoch_tracker.go:128 +0x26
github.com/influxdata/influxdb/tsdb.(*Store).DeleteSeries.func1(0xc25af9e000, 0x0, 0x0)
    /go/src/github.com/influxdata/influxdb/tsdb/store.go:1321 +0x264
github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1(0xc41bd95440, 0xc4c8e3df80, 0xc25af9e000)
    /go/src/github.com/influxdata/influxdb/tsdb/store.go:984 +0x48
created by github.com/influxdata/influxdb/tsdb.(*Store).walkShards
    /go/src/github.com/influxdata/influxdb/tsdb/store.go:983 +0x80
```

**Additional info:** 

The total influxdb database is not that large (~100GB), this measurement is probably have 4GB of data.

we tried to delete this measurment using `influx_inspect` while database was offline:

`influx_inspect deletetsm -measurement "delete_me"  /mnt/data/influxdb/data/database/forever/*/*.tsm`

but I got error:
`deletetsm: max blocks exceeded`

I verified all blocks of the database usgin `influx_inspect verify`, but it returns everything is ok:
`Broken Blocks: 0 / 73338792, in 144.25744743s`

we even tried to delete series of small period:
`delete FROM  delete_me WHERE time > 1545327008s and time < 1545499808s`

and that also crashed our database with same error above.

I know this isn't enough information to fix, but, I'm more than open to gathering more information, just let me know what you need.

**Comment by timhallinflux** [comment]
See also: https://github.com/influxdata/influxdb/issues/9694

**Comment by timhallinflux** [comment]
run the deletes command over shorter time ranges...

**Comment by josephxsxn** [comment]
Thanks @timhallinflux will give this a try.
