### ISSUE TITLE
Renaming Tasks should actually update task name

### ISSUE THREAD

**Issue by mavarius** [influxdata/influxdb#11853]
As a platform user
When I rename a task from the inline edit in the organizations task list
Then I see the updated name reflected in the task list
When I rename a task in the task page and click Save
Then I see the updated name reflected in the task list

Tasks List Rename
![tasklistrename](https://user-images.githubusercontent.com/11937365/52736656-3222bc00-2f7f-11e9-80e8-9e10463b7e5a.gif)

Task Page Rename
![taskpagerename](https://user-images.githubusercontent.com/11937365/52737007-24216b00-2f80-11e9-9997-22c4bb523d3f.gif)

**Comment by Palakp41** [comment]
This is a known issue for the tasks team: https://github.com/influxdata/influxdb/issues/11670

**Comment by Palakp41** [comment]
This issue has been fixed by closing this: https://github.com/influxdata/influxdb/issues/12093
