### ISSUE TITLE
Add ability to export variables

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#11872]
As a user, 
I can export variables that I can view. 
On export, I see a variables export overlay at route `http://localhost:9999/organizations/ORGID/variables/VARID/export`
Variables are exported in the template format ie. dashboards and tasks.

**Comment by OfTheDelmer** [comment]
Interpreting this currently to want the config variables tab to open the export overlay at `http://localhost:9999/organizations/ORGID/variables/VARID/export`, but if we don't want that we can create a route to `/configuation/variables_tab/:varID/export` that opens an overlay
