### ISSUE TITLE
Documentation about shards and shard spaces

### ISSUE THREAD

**Issue by nomadium** [influxdata/influxdb#1188]
Hi folks,

This is more a question than an issue. I have an influxdb database in production used to store collectd metrics and to display them with grafana.

I created my db with default options and as is expected after a while I'm noticing how influxdb is taking storage space because I didn't define any retention or storage policies.

My question is how I can see the current settings for my db and how I can change them? The documentation is not clear in this regard: http://influxdb.com/docs/v0.8/advanced_topics/sharding_and_storage.html.

The documentation includes this: "You must set up shard spaces when you create your database.".
Does this mean I have to recreate my db?

In general, I'm unable to find any kind of GET request in the API to check current settings.
I don't want to try the POST requests examples in documentation that change things in the db without an understanding of what is going on.

Thanks,

**Comment by nhonnavar** [comment]
Hi Paul,
I have a production setup of influxdb v0.8.8 , can I change existing database default retention policies..? if I cannot, can you guide me how to change the existing database path.
