### ISSUE TITLE
Proposal: add .editorconfig to enforce style on non-source files

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#11895]
After [some discussion on a separate PR](https://github.com/influxdata/influxdb/pull/11876#pullrequestreview-203833845) regarding the EOL at the end of the swagger.yml file, it would probably be a better use of time to automate style enforcement for YAML and other non-source files.

As far as I'm aware, [EditorConfig](https://editorconfig.org/) is as close to a standard tool as we'll get there. Many editors support it already, and many other editors support EditorConfig through a plugin.

For that particular case of the trailing newline, it looks like the config would be as simple as:

```ini
[*.yaml]
insert_final_newline: true
```

There are [standalone implementations](https://github.com/editorconfig/editorconfig/wiki/FAQ#are-there-any-tools-to-check-orand-reformat-existing-files-against-editorconfig-rules) that we could use as a CI step to enforce the rules outside of an editor.

**Comment by jacobmarble** [comment]
This is a great idea. Without giving this much thought, it would be helpful to use an implementation that is easily `brew`d or `apt-get`d.

**Comment by mark-rushakoff** [comment]
I did stumble across https://github.com/editorconfig-checker/editorconfig-checker, which is written in Go, but which was not listed in the standalone implementations part of EditorConfig's wiki. If we do this proposal, and if that project is a good fit, we can add it to the other tooling dependencies of influxdb, since installing Go binaries is a solved problem for us.
