### ISSUE TITLE
Error compacting TSM files - StringArrayDecodeAll: short buffer

### ISSUE THREAD

**Issue by gusutabopb** [influxdata/influxdb#11932]
After backfilling about 1 week worth of data into an InfluxDB (v1.7.3) instance, I am having some performance issues. The data backfilled data time range is ends on the current "hot shard" and the begins in the previous one (I'm using default 0s/1w autogen retention policy).

The issues are higher than usual CPU usage and extremely slow querying times for part of the back filled data. Writing and queries to other series/time ranges seem to be fine.

Upon some investigation I lots of lines like this on the logs:

```
lvl=info msg="Error compacting TSM files" log_id=0Dbsp5Tl000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0DdEXJG0000 op_name=tsm1_compact_group error="StringArrayDecodeAll: short buffer"
```

Which seems to be coming from this line: https://github.com/influxdata/influxdb/blob/v1.7.3/tsdb/engine/tsm1/batch_string.go#L109

Here's a dashboard screenshot showing the spike in errors:

<img width="979" alt="screen shot 2019-02-15 at 22 47 12" src="https://user-images.githubusercontent.com/4231387/52860963-52679c00-3174-11e9-93d8-261f29d4a0f9.png">

Is there anything I can/should do to fix this? Will it fix itself somehow once the shard goes cold?
Thanks!

**Comment by stuartcarnie** [comment]
@gusutabopb how large are your shards? 

InfluxDB 1.7.3 had a critical bug related to compactions that could result in data loss. We [posted an announcement](https://www.influxdata.com/blog/critical-release-announcement-influxdb-1-7-4-influxdb-enterprise-1-7-4/) regarding the issue and a subsequent fix.

**Comment by gusutabopb** [comment]
I ran `influx_inspect` but had no corrupted data.

It turns out upgrading to 1.7.4 and restarting the InfluxDB solved the error issue, therefore I will close this.

Query performance for a narrow time range (of about 1d) is still terribly bad however, so I will try waiting for the shard to go cold and see if performance improves. In case it's still bad I will try dropping the whole shard.
