### ISSUE TITLE
add concurrency to the task ui

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#11955]
as a tasks builder
with admin
when i create a new task
then i would like the ability to configure the concurrency in the ui

What is the concurrency strategy? 
is 1 the right default? 
do tasks queue or do they drop? 
what's the queue depth?

**Comment by chnn** [comment]
Some good examples of configuring concurrency [here](http://ember-concurrency.com/docs/task-concurrency) and [here](http://ember-concurrency.com/docs/task-concurrency-advanced/).

(It's from a concurrency management library that also happens to have an unrelated API primitive called "tasks").
