### ISSUE TITLE
Zero as result from division

### ISSUE THREAD

**Issue by mmolnar** [influxdata/influxdb#1196]
I am trying to run the following query:

select "calls", "hits", ("hits" / "calls") as percent from "series.name" where calls >0
For percent I allways get zero.

Here are the example results:

![datapoints](https://cloud.githubusercontent.com/assets/1432531/5298820/ab106616-7bc0-11e4-9836-6fbade377d67.png)

I have tried this on 0.8.7 version.

**Comment by lucasbritos** [comment]
Just in case, float conversion can be achieved via Cast operations
https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#data-types-and-cast-operations
