### ISSUE TITLE
ci: circleci litmus_daily job fails on PRs from forks

### ISSUE THREAD

**Issue by zhulongcheng** [influxdata/influxdb#11965]
Influxdb 2.0

![image](https://user-images.githubusercontent.com/11815801/52985469-ec5a6d80-342e-11e9-99e1-65ecf27cdcd4.png)

The litmus_daily job failed in forked PRs:
https://github.com/influxdata/influxdb/pull/11487
https://github.com/influxdata/influxdb/pull/11963
https://github.com/influxdata/influxdb/pull/11934

**Comment by zhulongcheng** [comment]
cc @goller

**Comment by mark-rushakoff** [comment]
For security reasons, we disable reading "secret" environment variables from forked PRs.

Maybe there's a way to skip the litmus tests from forks, although I'm not sure that's the right solution either.

I'm going to re-title the issue to mention forks.

**Comment by gshif** [comment]
It is possible to run `litmus_daily` job only on master, but the whole intention is to catch any issues before merging to master. One thing is I am not sure why litmus is trying to log into quay.io. The daily jobs are using `influxd` binaries and not docker images. I am going to look into that.

**Comment by gshif** [comment]
My bad, Litmus image is being used to run tests...

**Comment by gshif** [comment]
One of the options is to disable test runs on PR's from forks. CircleCI has the blog dedicated to the building open source projects : https://circleci.com/blog/managing-secrets-when-you-have-pull-requests-from-outside-contributors/

@mark-rushakoff, that seems like the quick solution to avoid failures. What do you think?

**Comment by mark-rushakoff** [comment]
The example they used to check CIRCLE_PR_NUMBER and skip the step seems
like a reasonable approach for us to skip litmus_tests on forks.

**Comment by zhulongcheng** [comment]
Thanks @gshif @mark-rushakoff @goller @BondAnthony
