### ISSUE TITLE
Add metrics for level of TSM files

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#11969]
Currently we have a metric to track the number of TSM files in a storage engine:

https://github.com/influxdata/influxdb/blob/cbef811c63bf76ae0ce844fc1d5e95e39d53a871/tsdb/tsm1/metrics.go#L134-L155

These get updated when a `tsm1.FileStore` is opened and closed. They also get updated whenever a compaction completes.

https://github.com/influxdata/influxdb/blob/cbef811c63bf76ae0ce844fc1d5e95e39d53a871/tsdb/tsm1/file_store.go#L939-L950

I would like to add a new label to these metrics called `level`. This metric would have the following possible values: `level = {1, 2, 3, 4+}`. The label value would be set by iterating over the file set when they're replaced via a compaction and inspecting the filenames to determine the level. Simply put:

```
000000001.tsm <- level = "1"
000000002.tsm <- level = "2"
000000003.tsm <- level = "3"
000000004.tsm <- level = "4+"
...
...
...
000000092.tsm <- level = "4+"
```

**Comment by tmgordeeva** [comment]
PR at https://github.com/influxdata/influxdb/pull/13353
