### ISSUE TITLE
Epoch tracker is racy

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#11967]
https://github.com/influxdata/influxdb/blob/6a48d640d42d65fd154f4fca282b091aceb54934/tsdb/store.go#L1380

is racy on `s.epochs`.

**Comment by zeebo** [comment]
Turns out this was fixed for `WriteToShard` in the 1.8 line by https://github.com/influxdata/influxdb/commit/b87605f521bdfde6983190e445da7b21c3b59707, but there's still a couple of other races in `DeleteMeasurement` and `DeleteSeries`. Those are addressed by #11970.
