### ISSUE TITLE
when you create an organization, you should automatically become the owner and a member

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#11980]
as a user
with admin
when i create a new organization
then i should automatically be added as the owner of that organization and a member

**Comment by russorat** [comment]
right now, when you create an org, you might be the owner, but when you list the members of that new org, you are not listed on the members page.

**Comment by Palakp41** [comment]
Blocked on: https://github.com/influxdata/influxdb/issues/12091

**Comment by Palakp41** [comment]
This is not blocked and being handled in the backend when org is created.
