### ISSUE TITLE
GET to tasks returns nothing following successful task creation

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#11998]
following several successful POST to tasks, see https://github.com/influxdata/influxdb/issues/11996
`GET` to `/tasks` returns a 200 and nothing
`GET` to `/tasks?org=org` returns a 200 and nothing
`GET` to `/tasks?user=034c56f697beb000` returns a 200 and nothing.

**Comment by docmerlin** [comment]
https://github.com/influxdata/influxdb/blob/46d9c80022c452cebb735b80d4aab513ee83a136/http/task_service.go#L307


It looks like, its looking for "organization" not "org", will fix. 
Also we no longer directly store the users they are stored by the user service, could be a bug there.  I'll look into it deeper.

**Comment by docmerlin** [comment]
Also, org should be an org ID not an org name (from the swagger spec)

**Comment by docmerlin** [comment]
Ok talked to Goller and am making that change.

**Comment by russorat** [comment]
Seeing this in the UI. what's the latest on this issue?

![image](https://user-images.githubusercontent.com/4805997/53187556-4470ab80-35b8-11e9-88cc-ad39e109485a.png)

**Comment by ebb-tide** [comment]
The UI is currently sending:
```
{"org":"org","flux":"option task = { \n  name: \"asdf\",\n  every: 1d,\n  offset: 1m\n}\n\nfrom(bucket: \"default\")\n  |> range(start: -task.every)"}
```
that should be correct once BE is fixed. :)

**Comment by docmerlin** [comment]
Can I go ahead and close this?
