### ISSUE TITLE
http: Task_CRUD fails race tests intermittently 

### ISSUE THREAD

**Issue by goller** [influxdata/influxdb#12003]
```
--- FAIL: TestTaskService (2.31s)
    --- FAIL: TestTaskService/TaskService (0.00s)
        --- PASS: TestTaskService/TaskService/Task_Meta_Updates (0.46s)
        --- FAIL: TestTaskService/TaskService/Task_CRUD (0.46s)
            servicetest.go:182: task not found

```

**Comment by mark-rushakoff** [comment]
I haven't been able to reproduce this locally, even with massive `-count` arguments to `go test`, with and without `-race`. I believe @lyondhill also tried to repro this without success. Please reopen if this is still occurring on CI.

**Comment by goller** [comment]
@mark-rushakoff it's currently happening with master:

https://circleci.com/gh/influxdata/influxdb/30280

**Comment by mark-rushakoff** [comment]
I'm pretty confident #12314 has the fix here. This was a legitimate bug; see the description in that PR.
