### ISSUE TITLE
ensure that the notification shown on onboarding 2 is not chopped

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#12029]

**Comment by Palakp41** [comment]
I am not seeing this issue anymore (see attached screenshot)

<img width="874" alt="screen shot 2019-02-25 at 2 08 05 pm" src="https://user-images.githubusercontent.com/26464594/53372128-ee2ca100-3906-11e9-9267-3079eded4969.png">

**Comment by russorat** [comment]
This is still happening on Firefox
