### ISSUE TITLE
Setting retention to infinite via flag in `influx setup` causes interactive question

### ISSUE THREAD

**Issue by juliusv** [influxdata/influxdb#12048]
In InfluxDB v2.0.0-alpha3 I am trying to set up InfluxDB non-interactively with infinite retention, but I get:

```
$ influx setup -b prometheus -f -o prometheus -p prometheus -u prometheus
Welcome to InfluxDB 2.0!
Please type your retention period in hours.
Or press ENTER for infinite.: 
```

Adding `-r -1` gives the same result.

Changing it to `-r 1000` works and makes the whole process non-interactive.

I would expect it to be possible to non-interactively set up InfluxDB with infinite retention as well.

**Comment by goller** [comment]
@juliusv thanks for writing in on this!  Try out latest master... the work was i #12049

**Comment by juliusv** [comment]
@goller Nice, thanks!
