### ISSUE TITLE
dashboard index sort order not stable when updating name

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#12060]
In the list of dashboards, updating the name of a dashboard causes the list to resort itself. I would expect the sort order to stay as is unless I clicked a sort button.

In combination with the lack of loading states in the dashboards list (#12059) or with a long dashboards list, this is a jarring experience:

![reordering](https://user-images.githubusercontent.com/638955/53189782-1d68a880-35bd-11e9-8e3f-e01851c7044f.gif)

**Comment by OfTheDelmer** [comment]
Summarizing from @alexpaxton: it looks like this will need some design work to indicate the kind of sorting active in the list. If a sort is shown as active on the list this behavior is fine, but it should be stable if no active sorting is displayed

**Comment by alexpaxton** [comment]
Closing in favor of https://github.com/influxdata/influxdb/issues/12514
