### ISSUE TITLE
Not able to override cron option with every in a flux script

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#12100]
I am not sure if that is supported, but I am seeing errors trying to override `cron` option with `every` and vise versa

Running `8016599605faf3b85ae2f3ef98213f8586080dc8@master` of `influxdb` 

- Create a task with `cron` or `every` in flux script:
Task is being created with following params:
```
Organization ID : '0370c48cf85aa000'
Flux Script: 'option task = {name: "task_uceifs", every: 1h} from(bucket:"read_from_b_query_params") |> range(start: -1h)'
Status : 'active'
Token : 'EepQdPw4MGQMmVIwwuy0DUALJBWKRfxuVIWmb9SG1Qv3lM5R2XcuqI9_eZoc0D3TYw9OJblGaR8hHlWukFqLtg=='
```

- Update Task
Request Body:
```
'{"cron": "1 2 3 4 5"}'
```

Error is returned:
```
error_message_headers = 'None'
e_msg = 'failed to update task'
e_code = 'internal error'
e_op = 'None'
e_err = 'cannot use both cron and every in task options'
error_message = '{u'message': u'failed to update task', u'code': u'internal error', u'error': u'cannot use both cron and every in task options'}'
```

**Comment by gshif** [comment]
I have rebuilt influxdb master@2f0dd5873720ff9aaceb35b9b57f61769d2a563c and I am still seeing the error 
```
cannot use both cron and every in task options
```

**Comment by docmerlin** [comment]
cannot use both cron and every in task options
Are you using both a cron and an every? If you are then it is appropriate.

**Comment by gshif** [comment]
Nope, I am not using both.
The flux script when task is created:
```
Flux Script: 'option task = {name: "task_uceifs", every: 1h} from(bucket:"read_from_b_query_params") |> range(start: -1h)'
```

The request to update the task:
```
{"cron": "1 2 3 4 5"}
```
