### ISSUE TITLE
Error message on setting 'every' to '0s' is not descriptive.

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#12167]
Since updating `every` option of flux script to any value less than `1s` returns an error, this error should be the same for every value that is less than `1s`, but error message for updating `every` option to `0s` returns message that is different.

- Update `every` option to `999ms`. 
```
requests.patch('http://localhost:9999/api/v2/tasks/0375a440777bd000', data='{"every": "999ms"}', headers={'Authorization': u'Token Jinef0hrq871McKlr8O4KvoJZZtuhxqwxsjP_7bR5-A3OzXcynT7SfT1vCQPNniRJMI_JseVei10BzyfniSpSQ=='})
```

This request returns error:
```
invalid options: every option must be at least 1 second
```

- Update `every` option to `0s`.
```
requests.patch('http://localhost:9999/api/v2/tasks/0375a440777bd000', data='{"every": "999ms"}', headers={'Authorization': u'Token Jinef0hrq871McKlr8O4KvoJZZtuhxqwxsjP_7bR5-A3OzXcynT7SfT1vCQPNniRJMI_JseVei10BzyfniSpSQ=='})
```
This request returns error:
```
cannot update task without content
```

The error message for setting `every` option to `0s` should be changed to 
```
invalid options: every option must be at least 1 second
```

**Comment by russorat** [comment]
no longer valid

**Comment by gshif** [comment]
I am still seeing different errors.
- Update `every` to `999ms`:

```
'message': 'failed to decode request', 
'code': 'invalid', 
'error': 'strconv.ParseInt: parsing "": invalid syntax'
```

And in case of a `1s`:
```
'message': 'failed to decode request', 
'code': 'invalid', 
'error': 'cannot update task without content'
```

Ans I am not seeing any more `invalid options: every option must be at least 1 second` error.
