### ISSUE TITLE
Run query to show available values for a Variable

### ISSUE THREAD

**Issue by AlirieGray** [influxdata/influxdb#12162]

**Comment by chnn** [comment]
Blocked pending answers to the following questions:

- When a user is using the data explorer, what variables do they see?
- When a user is viewing a dashboard, what variables do they see?
- When a user edits a cell on a dashboard, what variables do they see?
- If a user saves a cell to a dashboard that uses a variable that they were not using before does it appear in the variable toolbar for the dashboard? Or do they add the variable explicitly?
- If a user changes the value for a variable in a dropdown in the CEO, does it change the value selected on the dashboard?
- If a user can see every variable when opening the CEO, does that mean we load the values for every variable? What's the max number of variables that we expect a user would have access to, and would this be too slow?
- Once executed, should the query for a variable ever reexecute? Does this matter for variables with `now` etc in them? Should there be a way for a user to explicitly refresh a variable?
- Does a dashboard save variable value selections? If so, is it to the server, or to browser local storage?
- Can variables be used in tasks?

I've set up a meeting for tomorrow to resolve this.
