### ISSUE TITLE
tasks: should be able to find task by name

### ISSUE THREAD

**Issue by docmerlin** [influxdata/influxdb#12170]
tasks: should be able to find task by name
@goller asked that I add this.

- [ ] Check swagger to understand how other resources are searched by name
    - This should determine the type of search (prefix, exact, wildcard, etc)
- [ ] Replicate behavior for finding tasks

**Comment by goller** [comment]
Here is a more context from @lyondhill 
> TaskService `FindTasks` currently doesn't support org name. It can be moved to the platform adapter if we wanted to update the FindTasks method in the interface.
Out of this context The FindTasks probably needs to be updated to use `FindOptions` sometime. When that happens would be a good time to move this out of the http handler.


https://github.com/influxdata/influxdb/pull/12022#discussion_r258737266

**Comment by lyondhill** [comment]
Task names are not unique. What is the consequence of finding a task with a non unique name? Would we error or return 'first'?

**Comment by docmerlin** [comment]
I figured it would be a task-list action.  This does mean we need to re-add the index for task names, which means for backwards compatibility this needs to happen while we are still alpha, before the beta, unless we want to check versions and add indexing after the fact.
