### ISSUE TITLE
Querying for the progress of continuous queries

### ISSUE THREAD

**Issue by YaronWittenstein** [influxdata/influxdb#1218]
after we create a new CQ it takes time to catch up with existing data.
being able to query for the CQ progress can help much

**Comment by jsternberg** [comment]
I think this should now be partially responsible with the new query management functions in 0.12. You will be able to see the currently running queries, although you won't be able to see how that relates to continuous queries.

Will that work or do you want to have a command to query for specifically continuous queries?

**Comment by beckettsean** [comment]
@jsternberg I think we can close this issue. Query status is available for ad hoc and CQs, and combined with the logs, it's easy to tell:

1 when a CQ has run
2 when it will run next
3 whether it is running right now

Not sure what else is needed, and I don't think there's a reason to make a query for number 1. Although I could see an argument for number 2 being something we could query for.

**Comment by jsternberg** [comment]
I was thinking of leaving this as a longer term feature to track the continuous query execution. So if a continuous query needs to run 4 queries as part of a single run, `SHOW QUERIES` would show each of those 4 queries getting run individually, but another command would show something with continuous query specific information.

I'm not sure exactly what it would be and it would likely have to be specced out further before anybody worked on it. It might be worth just closing this and keeping it in mind as something else to add if somebody runs into a problem with seeing how many continuous queries are running. I also think it might be good at some point to add another option to restrict how many continuous queries can run at the same time so it doesn't overload the system with a queue for any continuous queries that need to run.

**Comment by beckettsean** [comment]
I vote we close it for now. If it's a useful feature it will resurface.
