### ISSUE TITLE
tasks: tasks/{taskID}/runs/{runID}/logs returning an array instead of an object

### ISSUE THREAD

**Issue by Palakp41** [influxdata/influxdb#12214]
The api get for logs: tasks/{taskID}/runs/{runID}/logs is supposed to return an object like this:
`{
  "events": [
    {
      "time": "2019-02-27T17:38:08.500Z",
      "message": "Halt and catch fire"
    }
  ]
}`

but instead returns an array:
`[
"2019-02-26T22:52:00.085724Z: Started task from script: "option task = { \n name: \"lol\",\n every: 1m,\n}\n\nfrom(bucket: \"a\")\n\t|> range(start: -15m, stop: now())" 2019-02-26T22:52:00.237874Z: Completed successfully"
]`

**Comment by mark-rushakoff** [comment]
Here's the validation error I get from the swagger validation branch:

```
SWAGGER RESPONSE VALIDATION ERROR: Field must be set to array or not be present
Schema:
  {
    "properties": {
      "events": {
        "items": {
          "$ref": "#/components/schemas/LogEvent"
        },
        "readOnly": true,
        "type": "array"
      }
    },
    "type": "object"
  }

Value:
  "object"
```

**Comment by Palakp41** [comment]
@mark-rushakoff Can you give me some clarification on what it means by "swagger validation branch"?

**Comment by mark-rushakoff** [comment]
I have an experimental branch at https://github.com/influxdata/influxdb/pull/12136 which includes HTTP middleware to validate the request and response against http/swagger.yml.
