### ISSUE TITLE
task: Updating a task breaks the runs api /tasks/{taskID}/runs

### ISSUE THREAD

**Issue by Palakp41** [influxdata/influxdb#12218]
If the task options are updated with new name or every/cron, the runs api returns with an error for unauthorized:

`code: "unauthorized"
error: {code: "not found", message: "authorization not found"}
code: "not found"
message: "authorization not found"
message: "unable to access task authorization"`

**Comment by mark-rushakoff** [comment]
I see what's wrong with the code here. The update path unconditionally re-sets the authorization: https://github.com/influxdata/influxdb/blob/dcb8c6e9b95901abe76284f4c0183fb52d59d627/task/platform_adapter.go#L210-L213
It should only re-set the authorization if the update request includes an explicit token.

Then,  it sees we have a session, and incorrectly uses the session ID as an authorization ID: https://github.com/influxdata/influxdb/blob/dcb8c6e9b95901abe76284f4c0183fb52d59d627/task/platform_adapter.go#L343-L351

The latter part was missed during https://github.com/influxdata/influxdb/pull/12078 and/or https://github.com/influxdata/influxdb/pull/12112.

**Comment by mark-rushakoff** [comment]
I'm pretty sure https://github.com/influxdata/influxdb/pull/12385 fixes this issue. Really sorry to snipe an issue that was already assigned to someone else, but it seemed more urgent to get the frontend unblocked on this.

**Comment by docmerlin** [comment]
Nah, its great, thanks mark.

**Comment by mark-rushakoff** [comment]
@Palakp41 I manually tested this from master at bea47b1a7e2ead84d2bda69641a34bffade5c702.

- I created a task.
- I let it run a few executions.
- I disabled it from the UI.
- I waited to confirm that it was inactive.
- I re-enabled it and confirmed it started executing again.
- I took my cookie from my browser and confirmed I could use curl with that cookie to read the runs of that task.

I believe this is fixed so I'm closing the issue.
