### ISSUE TITLE
Remove organization from Task Data Structure on chronograf. 

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#12250]
The task type definition includes an organization it is unclear why we need this, let's remove it also let's remove the Task type coersion on line 25 of ui/src/organizations/actions/orgView.ts

**Comment by AlirieGray** [comment]
The organization name is being used for looking up tasks by organization name, so I'm going to leave that property for now. However, I did notice that we are putting an Organization object in the `organization` field, when it's supposed to be the organization name string. I will be changing our implementation to use a string for this property.
