### ISSUE TITLE
Influxdb pod getting wrong IP address

### ISSUE THREAD

**Issue by farrukh90** [influxdata/influxdb#12261]
Hi,

We are using influxdb as a deployment on kubernetes, for some reason it is listening on different IP address. Hence pod is not being created. is there anyway I can make it listen on the node IP? 

`run: open server: listen: listen tcp IP:8088: bind: cannot assign requested address`

This is what I get.

**Comment by goller** [comment]
@farrukh90 would you share your k8s deployment?

**Comment by farrukh90** [comment]
Version 1.10.13 kubernetes
Docker Version: 18.09.2
3 Master nodes
3 Worker nodes.



`piVersion: extensions/v1beta1
kind: Deployment
metadata:
name: monitoring-influxdb
namespace: kube-system
spec:
replicas: 1
template:
metadata:
labels:
task: monitoring
k8s-app: influxdb
spec:
containers:
- name: influxdb
image: k8s.gcr.io/heapster-influxdb-amd64:v1.5.2
volumeMounts:
- mountPath: /data
name: influxdb-storage
volumes:
- name: influxdb-storage
emptyDir: {}`

**Comment by goller** [comment]
@farrukh90 seems fine although do be careful with `emptyDir`... you may want a persistent volume.

So, next would be to check the service.  Would you post the service definition?

**Comment by farrukh90** [comment]
---
apiVersion: v1
kind: Service
metadata:
labels:
task: monitoring
# For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
# If you are NOT using this as an addon, you should comment out this line.
kubernetes.io/cluster-service: 'true'
kubernetes.io/name: monitoring-influxdb
name: monitoring-influxdb
namespace: kube-system
spec:
ports:
- port: 8086
targetPort: 8086
selector:
k8s-app: influxdb

**Comment by goller** [comment]
@farrukh90 we are getting somewhere... your error specifies 8088 but the service configuration is 8086.

Would you dig into the influxdb configuration and see where 8088 is being used?

**Comment by farrukh90** [comment]
But, 

The pod is not created and in error state, I cant login or exec into that pod.

**Comment by farrukh90** [comment]
and the image is not hosted on our system. It is coming from 
* image: k8s.gcr.io/heapster-influxdb-amd64:v1.5.2

**Comment by goller** [comment]
@farrukh90 ok, I have an idea... you aren't using a configmap; that means you are using the default configuration.

I'd like you to try to set the environment variable `INFLUXDB_BIND_ADDRESS` to
`:8088`

(https://docs.influxdata.com/influxdb/v1.7/administration/config#bind-address-127-0-0-1-8088)

**Comment by farrukh90** [comment]
`[containers:
- env:
- name: INFLUXDB_BIND_ADDRESS
value: :8088
image: k8s.gcr.io/heapster-influxdb-amd64:v1.5.2
imagePullPolicy: IfNotPresent`

You have been very helpfull @goller  it works now

**Comment by goller** [comment]
@farrukh90 Yay!!! Have fun !

**Comment by farrukh90** [comment]
It was using the wrong env variable
