### ISSUE TITLE
Use Org Name for routing instead of ids?

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#12278]
I find myself looking up orgName by the orgID that I get from the routes a lot. Since org names are guaranteed to be unique, and we are using them in many of our client functions. why not make our routes more human readable by using org name in the url directly?  
`http://localhost:9999/organizations/0376b9289f334000/members`
would be 

`http://localhost:9999/organizations/ORGNAME/members`

**Comment by goller** [comment]
@ebb-tide they are guaranteed to be unique right now, but, I'd rather they not be treated that way.  That's a shortcut we took in alpha.  I want people to be able to rename their organizations if they want.

**Comment by ebb-tide** [comment]
ah that makes sense, ids don't change, names do and that would break links. nevermind! :)
