### ISSUE TITLE
api: define request to unset task options

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#12288]
Here is the current API definition to update a task:

https://github.com/influxdata/influxdb/blob/cc33679de7472e162d17b2f6dfa080ce2e3d180f/http/swagger.yml#L3879-L3890

https://github.com/influxdata/influxdb/blob/cc33679de7472e162d17b2f6dfa080ce2e3d180f/http/swagger.yml#L7548-L7575

The `status`, `flux`, `name`, and `token` properties are all straightforward: if provided, they can only override an existing required value. None of those existing values are allowed to be empty.

However, `every`, `cron`, and `offset` are more complicated.

`offset` is optional. You can have an offset or not have one. Right now, if your task has an offset and you want to remove that option, the only way is to directly modify the flux content. If you provide `0s` for the offset, the backend behaves the same as if you didn't specify offset at all.

Similar for every and cron. If your task has a cron and you want to replace the cron with an every, you might think that simply providing `every: 1h` would clear out the cron value. Instead, the backend tries to "merge in" cron on top of the existing values and then errors out because you had a cron and you're adding an every.

This generic issue has already come up specifically: 
- https://github.com/influxdata/influxdb/issues/12167
- https://github.com/influxdata/influxdb/issues/12100

Maybe there's a way to solve this in parsing JSON, by detecting an explicit `every: 0s` or `cron: ""` or `offset: 0s` as opposed to an omitted value. Or maybe there's a more standard way of something like `{"delete": ["every", "offset"]}`.

I'm not sure what's the most standard answer for this type of API, so I'm adding this to the API backlog for that team to answer.

**Comment by goller** [comment]
@mark-rushakoff typically, what I do for an update for optional fields whose absence means to remove:

```go
type Howdy struct {
    Offset *string `json:"offset"`
}
```

If it has been specified as empty string:

```json
{
    "offset": ""
}
```

I remove the option.

If the option is not set at all:
```json
{
 // offset not here
}
```

then I check for nil and do not clear the option.

So, on PATCH one must specify the fields to change.  If the fields are not specified, then, no updates occur.  If the fields are empty string, the values are cleared.

**Comment by mark-rushakoff** [comment]
Thanks, that makes a lot of sense. I'll leave this issue open for now to track supporting this style in the task update API, and I'll try to remember that pattern going forward.

**Comment by mark-rushakoff** [comment]
@docmerlin please follow the pattern that Goller described above.

**Comment by docmerlin** [comment]
This is done and should be closed.
