### ISSUE TITLE
Regression: Aggregations from two subqueries containing aggregations are not working from v1.4.0

### ISSUE THREAD

**Issue by lkslawek** [influxdata/influxdb#12334]
Last working release: v1.3.9
First non-working release: v1.4.0 (and still present in v1.7.4)
Breaking commit: 5a9553b2c4fe404d2b9118ba7a93e69eb7b85c36

We are using query:

```
SELECT 100*sum("slow") / sum("all") as "%>1s"
FROM
  (SELECT count("uuid") as "slow"
   FROM "app.rack"
   WHERE "environment"='production'
     AND $timeFilter
     AND "duration" >= 1000
     GROUP BY time(1h)),
  (SELECT count("uuid") as "all"
   FROM "app.rack"
   WHERE "environment"='production'
     AND $timeFilter
   GROUP BY time(1h))
WHERE $timeFilter
GROUP BY time(1h)
```

to make a graph showing us the percent of queries to application that were slow in each hour. This worked good in InfluxDB 1.3.7. But after upgrading to 1.7.4 all we got are nulls instead of numbers. I've checked that the break was introduced in 1.4.0.

In order to give a simple example how this stopped working I've set a sample measurement:

```
> select * from m
name: m
time a b
---- - -
0    0 
1      0
2    0 
```

and given a (not very useful) query in InfluxDB 1.3.9 I get:

```
> select sum(*) from (select count(a) as cnt_a from m),(select count(b) as cnt_b from m)
name: m
time sum_cnt_a sum_cnt_b
---- --------- ---------
0    2         1
```

while in InfluxDB 1.4.0:

```
> select sum(*) from (select count(a) as cnt_a from m),(select count(b) as cnt_b from m)
name: m
time sum_cnt_a sum_cnt_b
---- --------- ---------
0    2       
```

Using `git bisect` I've pinpointed the regression to commit 5a9553b2c4fe404d2b9118ba7a93e69eb7b85c36.

**Comment by lkslawek** [comment]
@martinkoch-geniebelt looked more into the diff on the deleted lines https://github.com/influxdata/influxdb/commit/5a9553b2c4fe404d2b9118ba7a93e69eb7b85c36#diff-64cf9c2f9744911c0654fff64d5ffa99L42 in `newFloatIterators()` that removed cast there from integer to float and that lead him to discovering the workaround. This is on 1.7.4 with the test data above:

Originally we had:

```
> select sum(*) from (select count(a) as cnt_a from m),(select count(b) as cnt_b from m)
name: m
time sum_cnt_a sum_cnt_b
---- --------- ---------
0    2       
```

while with slight modification:

```
> select sum(*) from (select count(a) as cnt_a from m),(select 1. * count(b) as cnt_b from m)
name: m
time sum_cnt_a sum_cnt_b
---- --------- ---------
0    2         1
```

The difference is adding `1. *` in second subquery, which forces the float on the returned values.

I've also tried with adding the removed code in `newFloatIterators()` back along with `integerFloatCastIterator` struct (it has been removed in f8d60a881d11bd177579548e422a5751e8dc60bd) to branch 1.7 and this fixes the problem, but I wouldn't dare to assume that this is a good place to fix this. Is it, @jsternberg?

So the problem is not with aggregation itself but with some type casting in aggregations, which is in line with what the commit introducing the regression changed.

**Comment by jgitlin-bt** [comment]
I too am affected by this issue where multiple subqueries with GROUP BY clauses cause all measurements to return zero. In my case the query is:

`SELECT max("usage") AS peak_usage FROM (SELECT sum("active")/sum("total") AS usage FROM (SELECT max("active_processes") AS "active", max("total_processes") AS "total" FROM "phpfpm" WHERE ("realm" =~ /prod/) AND $timeFilter GROUP BY time(30s), "host") GROUP BY time(30s)) WHERE $timeFilter GROUP BY time(1h)`

The goal being to re-aggregate metrics over a longer period (downsampling but without a CQ)

**Comment by jgitlin-bt** [comment]
As a workaround in my case (where the values are percentages) we can multiply our values by something in an inner query (E.G. 10000) and then divide by that in the outer query:

`SELECT max("usage")/10000 AS peak_usage FROM (SELECT 10000*sum("active")/sum("total") AS usage FROM (SELECT max("active_processes") AS "active", max("total_processes") AS "total" FROM "phpfpm" WHERE ("realm" =~ /prod/) AND $timeFilter GROUP BY time(30s), "host") GROUP BY time(30s)) WHERE $timeFilter GROUP BY time(1h)`

**Comment by martinkoch-geniebelt** [comment]
Hope this would get fixed :)

**Comment by lkslawek** [comment]
This still doesn't work in 1.7.8.
