### ISSUE TITLE
litmus tests could add test metadata to circle output

### ISSUE THREAD

**Issue by goller** [influxdata/influxdb#12358]
Litmus has a lot of debugging information so it can be hard to look through the output and identify the failing test.  However!  Litmus produces a junit formatted output:

https://circleci.com/gh/influxdata/influxdb/31013#artifacts/containers/0

If we add a `store_test_results` section to the circle configuration we'd be able to to _easy_ see the failing test quickly as well as get more long term tracking.

https://circleci.com/docs/2.0/collect-test-data/#pytest

**Comment by gshif** [comment]
@BondAnthony , can use a little bit help here. I added the `store_test_results` to the `config.yaml` file, but was not able to see the Test Meta Data under Test Summary. I even tried different paths for the store_test_results, but result is the same. I did a little bit of searching and saw other people had/have similar problems, but could not find any solution. If you are aware of any, please let me know. 
For now there is a `report.html` file that gives you nicely formatted results.
