### ISSUE TITLE
Can't login as root / root as on Mac OS X Yosemite via a fresh brew install influxdb

### ISSUE THREAD

**Issue by tobilg** [influxdata/influxdb#1238]
I was trying to install InfluxDB 0.8.7 on my Mac OS X Yosemite machine via homebrew, as outlined in http://influxdb.com/docs/v0.8/introduction/installation.html
- Step 1

brew install influxdb
- Step 2

Run influxdb -config=/usr/local/etc/influxdb.conf

Issues:
- Logging configuration

On startup, I get an error that the process can't write to the actual folder. After adding the /tmp path, the db starts up without having to use sudo.

I'm using `file   = "/tmp/influxdb.log"` instead of the standard `file   = "influxdb.log"` in the influxdb.conf.
- Login into the web admin gui

I can't login using the specified root / root credentials (see http://influxdb.com/docs/v0.8/introduction/getting_started.html), I receive a `Couldn't authenticate user: Invalid username/password` error.

**Comment by ViswanathL** [comment]
Iam getting in to this issue again. Please have a look at my `/usr/local/var/influxdb/raft/` folder  

+ ls -al /usr/local/var/influxdb/raft/
total 24
drwxr--r--  6 viswanath  admin  204 May 29 15:57 .
drwxrwxrwx  6 viswanath  admin  204 May 29 15:57 ..
-rw-------  1 viswanath  admin   28 May 29 15:57 conf
-rw-------  1 viswanath  admin  382 May 29 15:57 log
-rw-r--r--  1 viswanath  admin   15 May 29 15:57 name
drwx------  2 viswanath  admin   68 May 29 15:57 snapshot
