### ISSUE TITLE
linter does not pick up console.logs

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#12398]
Somewhere along the way we must have disabled that check, because I just checked in a console.log with no complaints!

**Comment by chnn** [comment]
I just tested this out and it seems to be working the same as always (`console.log` disallowed, `console.warn` and `console.error` are OK).

I added a `console.log` statement and then ran `npm run eslint`:

```
$ npm run eslint

> chronograf-ui@2.0.0 eslint /Users/chris/Dev/influxdb/ui
> eslint '{src,cypress}**/*.{ts,tsx}'


/Users/chris/Dev/influxdb/ui/src/Setup.tsx
  47:5  error  Unexpected console statement  no-console

✖ 1 problem (1 error, 0 warnings)
```

**Comment by chnn** [comment]
Actually now I'm seeing this again. Will investigate.
