### ISSUE TITLE
Discuss how system services communicate to other secured services

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#12407]
Problem:

1. **User** issues read request to **Resource A**, for which they have read permission
2. **Resource A** invokes **Service T**, passing existing token
3. **Service T** issues read request to **System-Resource B**, passing user token
4. User token does not have read permissions to **System-Resource B**
5. All users should have read-access to **System-Resource B** via **Service T**

A concrete example of this is calling the `Task.FindRuns`, which ultimately calls [ListRuns](https://github.com/influxdata/influxdb/blob/abd6fee7571f3491c428f9b432bccbe1c8133277/task/backend/query_logreader.go#L91). ListRuns attempts to issue a Flux query to read from task system bucket [`0x000000000000000a`](https://github.com/influxdata/influxdb/blob/abd6fee7571f3491c428f9b432bccbe1c8133277/task/backend/query_logreader.go#L114). The [existing user token](https://github.com/influxdata/influxdb/blob/abd6fee7571f3491c428f9b432bccbe1c8133277/task/backend/query_logreader.go#L125) does not have read permissions to this system bucket.

----

A solution is required that allows ad-hoc permissions to be added to the existing token or for a new token to be constructed in **Service-T** with access to **System-Resource B**. This new token should be cheap to construct.

Ideally, the existing user token would be preserved or included in the ad-hoc token, so that upstream requests may still be traced to the originating user.

**Comment by mark-rushakoff** [comment]
> A solution is required that allows ad-hoc permissions to be added to the existing token or for a new token to be constructed in Service-T with access to System-Resource B. This new token should be cheap to construct.

There should be some way for **Service-T** to prove itself as the originator of the request, so that the remote service does not have to blindly trust the request coming in from the network. Without such proof to validate, it's conceivable that a malicious actor with network access could spoof the system and do just about anything.

Granted this is more of a cloud/enterprise concern, but it will have effect on the design that enters open source.
