### ISSUE TITLE
task: require explicit authorization when creating task

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#12409]
In the HTTP handler for tasks today, we conditionally create a new authorization for the task if you are using a Session to make the request: https://github.com/influxdata/influxdb/blob/fe6ce24c8051a78fa952407e3ea8972e7fcd7855/http/task_service.go#L495-L526

If you are making an HTTP request to create a task, and in that request you're using a Token associated with an Authorization, and your create request doesn't explicitly set the task's token field, then we use the token (really the authorization ID) associated with the request.

https://github.com/influxdata/influxdb/blob/fe6ce24c8051a78fa952407e3ea8972e7fcd7855/task/platform_adapter.go#L143-L157
https://github.com/influxdata/influxdb/blob/fe6ce24c8051a78fa952407e3ea8972e7fcd7855/task/platform_adapter.go#L338-L354

Both of these behaviors are too implicit and will ultimately surprise users.

Instead, we should make the token a required field when creating a task, and cut out the conditional authorization creation and the current token grabbing.

Before we can make the token required, the UI needs to support setting a token when creating a task.

**Comment by mark-rushakoff** [comment]
Related work for telegraf tokens: https://github.com/influxdata/influxdb/issues/12579

**Comment by kelwang** [comment]
Hey, @mark-rushakoff . Shall we add the token into the session as well?

**Comment by mark-rushakoff** [comment]
I'll have to defer to someone more knowledgeable about the relation between sessions and tokens. It's been too long since I've touched either.

**Comment by AlirieGray** [comment]
blocked on https://github.com/influxdata/influxdb/issues/14365
