### ISSUE TITLE
SHOW MEASUREMENTS slow using non-admin user and many measurements

### ISSUE THREAD

**Issue by dataviruset** [influxdata/influxdb#12416]
### Bug report

**System info:**
InfluxDB shell version: 1.7.4
Running in Kubernetes, Docker image influxdb:1.7.4
Kubernetes Version: v1.10.5

    > show diagnostics
    name: build
    Branch Build Time Commit                                   Version
    ------ ---------- ------                                   -------
    1.7               ef77e72f435b71b1ad6da7d6a6a4c4a262439379 1.7.4

    name: config
    bind-address reporting-disabled
    ------------ ------------------
    :8088        false

    name: config-coordinator
    log-queries-after max-concurrent-queries max-select-buckets max-select-point max-select-series query-timeout write-timeout
    ----------------- ---------------------- ------------------ ---------------- ----------------- ------------- -------------
    10s               0                      0                  0                0                 15s           10s

    name: config-cqs
    enabled query-stats-enabled run-interval
    ------- ------------------- ------------
    true    false               1s

    name: config-data
    cache-max-memory-size cache-snapshot-memory-size cache-snapshot-write-cold-duration compact-full-write-cold-duration dir                    max-concurrent-compactions max-index-log-file-size max-series-per-database max-values-per-tag series-id-set-cache-size wal-dir               wal-fsync-delay
    --------------------- -------------------------- ---------------------------------- -------------------------------- ---                    -------------------------- ----------------------- ----------------------- ------------------ ------------------------ -------               ---------------
    1073741824            26214400                   10m0s                              4h0m0s                           /var/lib/influxdb/data 0                          1048576                 40000000                100000             100                      /var/lib/influxdb/wal 0s

    name: config-httpd
    access-log-path bind-address enabled https-enabled max-connection-limit max-row-limit
    --------------- ------------ ------- ------------- -------------------- -------------
            :8086        true    false         0                    0

    name: config-meta
    dir
    ---
    /var/lib/influxdb/meta

    name: config-monitor
    store-database store-enabled store-interval
    -------------- ------------- --------------
    _internal      true          10s

    name: config-precreator
    advance-period check-interval enabled
    -------------- -------------- -------
    30m0s          10m0s          true

    name: config-retention
    check-interval enabled
    -------------- -------
    30m0s          true

    name: config-subscriber
    enabled http-timeout write-buffer-size write-concurrency
    ------- ------------ ----------------- -----------------
    true    30s          1000              40

    name: network
    hostname
    --------
    influxdb-7cf98ff85f-pj9bd

    name: runtime
    GOARCH GOMAXPROCS GOOS  version
    ------ ---------- ----  -------
    amd64  48         linux go1.11

    name: system
    PID currentTime                    started                        uptime
    --- -----------                    -------                        ------
    1   2019-03-07T05:45:43.507269413Z 2019-03-06T13:10:00.263211692Z 16h35m43.244057721s

    > show users
    user          admin
    ----          -----
    admin         true
    api           false

**Expected behavior:**
That my `api` (non-admin) user would return the measurement list as fast as the `admin` user does.

**Actual behavior:**

    $ time curl -s -u admin:password 'http://1.2.3.4:8086/query?db=api&q=SHOW+MEASUREMENTS' | python -m json.tool | grep '"' | wc -l
    6857

    real	0m0.993s
    user	0m0.066s
    sys	0m0.024s
    $ time curl -s -u api:password 'http://1.2.3.4:8086/query?db=api&q=SHOW+MEASUREMENTS' | python -m json.tool | grep '"' | wc -l
    6857

    real	0m30.435s
    user	0m0.065s
    sys	0m0.015s

**Additional info:**
None.

**Comment by bapBardas** [comment]
I face the exact same issue in v1.8.0 using the influxd command line to perform the query.
On a pretty large database (12M series) performing a show measurements query

- using admin account took 0m1.042s
- using another user account took 0m18.664s to complete

**Comment by chopchopjames** [comment]
same issue on 1.8.0
