### ISSUE TITLE
task: listing runs for task that hasn't run yet should be 200 status, not 404

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#12421]
We specifically treat `ErrRun(s)NotFound` as a 404 in some places at the HTTP layer, but that ended up being too aggressive in the case of a task that exists but hasn't run yet.

When the task exists but we haven't found any runs, it should be a 200 status with an empty array of runs. When the task doesn't exist, it can be a 404.

**Comment by lyondhill** [comment]
I like the behavior change. I think I will fix this and make the log's work the same way. If none exist return [], 200 instead of 404

**Comment by mark-rushakoff** [comment]
That sounds appropriate to include as part of this change. Thanks.

**Comment by lyondhill** [comment]
fixed by #12432
