### ISSUE TITLE
Awkward empty state when no labels exist

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#12469]
<img width="385" alt="Screen Shot 2019-03-08 at 2 26 01 PM" src="https://user-images.githubusercontent.com/638955/54059923-b697e180-41af-11e9-8a74-d14eafc9cfe8.png">

This showed up since I have no labels. While technically true, I would expect it to say something like _No labels exist_ or _Start typing to create a label_.

**Comment by alexpaxton** [comment]
Ahh seems like this could be handled with some improved logic and copy.  Maybe something like `Start typing to create a label`
