### ISSUE TITLE
ERR: Cannot use a database that exists

### ISSUE THREAD

**Issue by santakd** [influxdata/influxdb#12475]
Connected to http://localhost:8086 **version 1.7.3**
InfluxDB shell version: 1.7.3
Enter an InfluxQL query

> show databases
name: databases
name
----
_internal
telegraf
jmeter
micrometer
locust
**collectd**
> use database **collectd**
ERR: Database database collectd doesn't exist. Run SHOW DATABASES for a list of existing databases.
DB does not exist!
> use database locust
ERR: Database database locust doesn't exist. Run SHOW DATABASES for a list of existing databases.
DB does not exist!

**Comment by santakd** [comment]
#2258

**Comment by vspinu** [comment]
Same here with the default config on ubuntu linux:

```
Linux 4.18.0-25-generic x86_64
InfluxDB v1.7.6 (git: 1.7 01c8dd416270f424ab0c40f9291e269ac6921964)
```

**Comment by andi20002000** [comment]
Hi if anyone stumbles across this error, the solution is the following command:
`SHOW DATABASES`
choose the name you need for example telegraf and then select it:
`USE telegraf`
