### ISSUE TITLE
Initial username and password

### ISSUE THREAD

**Issue by bongsam89** [influxdata/influxdb#12474]
I installed InfluxDB addon and was successful to run it after changing 'ssl' to 'false'.

But if I click 'Open web ui', it requires username and password and I don't know where to set the username and password.

Can anyone tell me how to figure this out?

**Comment by dgnorton** [comment]
@bongsam89 the best place to ask usage questions is on the [InfluxData Community site](https://community.influxdata.com/). We use GitHub issues for bugs and features.
