### ISSUE TITLE
Aggregate data in groups of N elements

### ISSUE THREAD

**Issue by GerardBCN** [influxdata/influxdb#12478]
Dear Influxdb family, I'm trying to perform an operation (e.g. average, max) on groups of N elements. I don't want to group by time but group by N number of elements. Is there any syntax to achieve this behaviour?

Here's an example:

This is my measurement table:
```
Timestamp      value
=========      ====
0                      2
1                      4
2                      1
3                      2
4                       3
5                       3
```

The query would look something like:
```
select max(value) from my_measurement group by count(2);
```

would return:
```
4, 2, 3
```

Thanks!

**Comment by dgnorton** [comment]
@GerardBCN the best place to ask usage questions is on the [InfluxData Community site](https://community.influxdata.com/). We use GitHub issues to track bugs and features.
