### ISSUE TITLE
Questions about replacing series block with series file

### ISSUE THREAD

**Issue by johnnyjian** [influxdata/influxdb#12486]
I am looking into the source code of tsi, and I find that originally series are written to the series block inside tsi files per-shard, but then are written to the database-wide series file.

I wonder why but cannot find any docs or issues related to the reason to this change.

IMO, maintaining series per-shard maybe slower for reading and writing, but the database-wide series file is unbounded and expired series cannot be removed expect for rewriting the whole series file.

**Comment by benbjohnson** [comment]
@johnnyjian The database-level series file was added to alleviate a lot of the performance impact of rolling over shards and to improve planning performance by working with `uint64` values instead of string keys. 

We are working on expiring and compacting series files and that work will be included in a later release.

**Comment by johnnyjian** [comment]
@benbjohnson Why not use per-shard series files instead? Then the series files can be expired along with shards. Does it have poorer performance than database-wide series files?

**Comment by benbjohnson** [comment]
@johnnyjian Yes, there is a very significant performance hit when we use per-shard series files.

**Comment by johnnyjian** [comment]
@benbjohnson Can you share some performance numbers for comparison?
For clarification, I mean implementing the exact series file per-shard as the one per-database, not the series block per tsi file.

**Comment by benbjohnson** [comment]
I don't have the performance numbers on-hand. We made the change from per-shard to per-database a while ago. It was several orders of magnitude faster though.
