### ISSUE TITLE
Make data explorer org-centric

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#12505]
as a multi-org user
with viewer permissions or higher
when i use the data explorer to explore my data
then i would like to choose the organization i am exploring data in
then i would like that choice saved in browser local storage the next time i visited explorer
then i would like a default org chosen which would be the first one returned.

**Comment by ebb-tide** [comment]
DataExplorer page title should be [OrgName] / DataExplorer
All new resources created from this page should be scoped to org
