### ISSUE TITLE
Task: Create tests to validate user access control

### ISSUE THREAD

**Issue by lyondhill** [influxdata/influxdb#12516]
Confirm that users are only allowed to see tasks they have access to.

**Comment by mark-rushakoff** [comment]
@lyondhill did you have more specific cases in mind? Which system/subsystem needs more coverage?

**Comment by lyondhill** [comment]
This issue was in response to the issue we had last week. I dont have any specific examples but a good starting point would be for user1 to go through the crud actions and ensure that user2 cannot take any actions on user 1's tasks. The specific issue was was user2 could list user1's tasks.
