### ISSUE TITLE
No time range selected is causing errors

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#12520]
I seem to be getting into a state after refreshing and navigating away and back to a dashboard and the time range is empty. This is causing errors in my dashboard cells. I can select a time range and refresh and they are fine, but as soon as i go away and come back to the dashboard its in the errorred state again.

<img width="999" alt="Screen Shot 2019-03-11 at 3 01 56 PM" src="https://user-images.githubusercontent.com/5751863/54161286-e98be080-440e-11e9-92b8-0611a9dd5e51.png">

<img width="568" alt="Screen Shot 2019-03-11 at 3 04 35 PM" src="https://user-images.githubusercontent.com/5751863/54161323-09bb9f80-440f-11e9-9ed9-bca383eb4c2d.png">

**Comment by alexpaxton** [comment]
I might have broken this via https://github.com/influxdata/influxdb/pull/12499

I'm guessing somewhere the first item in the time ranges list is being automatically selected, and it is now a divider instead of a valid time range
