### ISSUE TITLE
Check type safety for components that use default props with Partial<Props> type

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#12565]
@bthesorceror noticed that the reason some components are losing type definitions and type safety is because they have default props that use type Partial<Props>. 
We should check that components are not typeless in a way that has not been previously noticed. 
One solution to restore type safety can be found in the component `ExportOverlay.tsx`

**Comment by 121watts** [comment]
@ebb-tide with Typescript 3.0 and `@react/types 16.4.11` the compiler can infer the `defaultProp` types from props.

**Comment by OfTheDelmer** [comment]
I like the `DefaultProps` interface

**Comment by chnn** [comment]
For class components, it seems nice to have the compiler infer default props (less to do, less type noise).

For function components, I'm inclined to write them like this:

```
interface Props {
  foo: string
  bar?: string
}

const Plerps: FunctionComponent<Props> = ({ foo, bar = 'baz'}) => {
}
```

but that won't catch when don't supply the default in the component definition (unless we turn on strict null checks). I'm ok with that.

Saw a somewhat relevant discussion earlier: https://twitter.com/brian_d_vaughn/status/1108013631453618179
