### ISSUE TITLE
wal-fsync-delay >10s results in 500 errors (timeouts) on every write

### ISSUE THREAD

**Issue by rdslw** [influxdata/influxdb#12563]
Behaviour:
If you set wal-fsync-delay to 10s you will get 500 errors during writes (http api).

Expected behaviour/solutions:
1. influxdb should limit wal-fsync-delay to reasonable values, if it can not work with values > few seconds (6s worked for me)
2. influxdb should warn about correlation between http timeout/wal-fsync-delay etc.
3. influxdb shall not wait for actual disk fsync, before replying to http call or at least allow it to be configurable parameter - this point is a root cause of timeouts errors if connected with high wal-fsync-delay value. a byeffect will be huge performance boost, but it should NOT be enabled by default.

This might be actual reason for https://github.com/influxdata/influxdb/issues/8533

**Comment by mueslo** [comment]
ran into this too when trying to tune influxdb to cause less disk writes

**Comment by ElisaPiccin** [comment]
@mueslo how did you solve it?

**Comment by mueslo** [comment]
I didn't, I set it back to zero :/

**Comment by formtapez** [comment]
@mueslo thanks. i ran into the same issue.

**Comment by jvs87** [comment]
@mueslo , @formtapez  . Any advice about that ? Im stuck on this.

**Comment by BlackEdder0815** [comment]
Same problem here, no solution, yet.

**Comment by isarrider** [comment]
hallo dev team,
I have the same issue and it already killed one Flash memory storage...
(here write amplification really does hurt)...
especially 3 from @rdslw seems like a viable solution to me.

I would go as far as saying in my case the WAL Files can be written into a TSM every x hours
and never need to be placed on the storage, as there is an UPS (Uninterruptible power supply) anyway...

-> so maybe make it possible to disable the WAL files completely, as my understanding is that the TSM files
are taken from the RAM anyway?

**Comment by Cadence-GitHub** [comment]
Got hit with the same problem. Influxdb is killing my SSD with frequent unnecessary writes. I would like to be able to flush all data on disk once every minute or so, instead of generating of millions of tiny writes that quickly kill SSDs. Please fix this.

**Comment by isarrider** [comment]
I think this is not changing, but take a look at VictoriaMetrics,
there you can do "-inmemoryDataFlushInterval=1h"...
