### ISSUE TITLE
Saving existing cell causes error

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#12562]
Even with no changes, saving an a existing cell causes errors.

![saving-errors](https://user-images.githubusercontent.com/5751863/54227646-a2105d80-44bd-11e9-9dd2-59e147d5bc13.gif)

![Screen Shot 2019-03-12 at 11 55 11 AM](https://user-images.githubusercontent.com/5751863/54227701-beac9580-44bd-11e9-82bf-7f7711ce7f8d.png)

**Comment by chnn** [comment]
I believe this will be fixed by https://github.com/influxdata/influxdb/pull/12556. Just need to wait for the code freeze to end to merge.

Sorry for the breakage!
