### ISSUE TITLE
Creating a telegraf config always creates new token label

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#12579]
Every time a telegraf config is created a new label named token is created. 
It seems like the label should only be created if it doesnt already exist since the ui doesnt allow duplicate label names.

**Comment by ischolten** [comment]
@121watts Is this the intended behavior?

**Comment by 121watts** [comment]
yes.  this is how we hacked together persisting a relationship between a token and a telegraf config.

**Comment by ischolten** [comment]
i see. it just bizarre when going to add a label elsewhere and seeing 4 different token label options in my label list.

**Comment by 121watts** [comment]
@ischolten for sure.  we should create a namespace for application specific tokens and filter them from the labels view.
