### ISSUE TITLE
Listitem colors in configuration view blend in with background

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#12576]
The items in this list should probably be different than the background like they are in the org view lists.

![Screen Shot 2019-03-12 at 1 31 39 PM](https://user-images.githubusercontent.com/5751863/54239868-ad718200-44d9-11e9-8f63-4696f37e7f8b.png)

**Comment by alexpaxton** [comment]
This is a byproduct of the two different tabbed page components we have. The styles that ensure contrast with panels/lists/cards inside the tabbed page are part of the newer tabbed page component (seen in orgs page) and not in the old component (config)

It's my understanding the goal is to factor out the old component, aka implement the tabbed page component in the config page
