### ISSUE TITLE
Bucket rows in org view dont match header

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#12581]
The header has name and retention policy where as the content of the row has name, org and retention policy.

![Screen Shot 2019-03-12 at 2 47 44 PM](https://user-images.githubusercontent.com/5751863/54240915-bca5ff00-44dc-11e9-8150-0b6cc29d2918.png)

**Comment by ischolten** [comment]
@russorat  Should the header get updated or should org get removed since this is in the org view?
(if it gets removed we need to make sure it doesnt get removed in the configuration view)

**Comment by russorat** [comment]
org1 should not show on this page.
