### ISSUE TITLE
InfluxDB deployment kubernetes readiness probe fails

### ISSUE THREAD

**Issue by stafot** [influxdata/influxdb#12589]
When adding a `readinessProbe` to `/ping` endpoint fails and restarting forever with the following error.  `request canceled (Client.Timeout exceeded while awaiting headers)`
If I delete the pod manually starting behave normally until at some point starting again failing after some days. 
Any thought would be appreciated.

**Comment by zar3bski** [comment]
I am experimenting similar issues using
```
  service:
    type: ClusterIP
    port: 8086

```

**Comment by sevakghazaryan** [comment]
Hi all, I also face this issue; the pod restarts several times, and the status changed CrashLoopBackOff. 
The logs show that the problem is liveness probe failed. Any thoughts?
