### ISSUE TITLE
Can't scroll dropdowns in Firefox

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#12629]
![firefox dropdown](https://user-images.githubusercontent.com/638955/54370694-508ade80-4635-11e9-8668-85941402f299.gif)
![firefox dropdown 2](https://user-images.githubusercontent.com/638955/54370696-51bc0b80-4635-11e9-89bc-c5213ccf333b.gif)

**Comment by OfTheDelmer** [comment]
this is the cause we see of the clipping in the hover legend according to @alexpaxton https://github.com/influxdata/influxdb/issues/12630

**Comment by OfTheDelmer** [comment]
the needs to be fixed in influxdata/react-custom-scrollbars

```
there’s a difference of 15px between the fancy scroll area and what the component is told to be
```
