### ISSUE TITLE
Graph legend items hidden in Firefox / can't scroll

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#12630]
Sometimes a few legend items will show, but the rest will be hidden out of view and not reachable by scrolling. In this case, the legend items didn't show up at all:

<img width="504" alt="Screen Shot 2019-03-14 at 8 49 18 AM" src="https://user-images.githubusercontent.com/638955/54371125-1b32c080-4636-11e9-84b8-5255eb6592ef.png">

- [x] explore the effectiveness of adding conditional styling in firefox for padding and scrollable lists
- [x] iterate on the `react-custom-scrollbars` to remove scrollbar styling and explore `padding` and other styling rules to always hide native scrollbars.

-----

### Horizontal / No Trackbar Width

- [x]  Scrollable view does not need horizontal scrollbar
   - Solution: no need for margin-bottom
- [ ]  ***Scrollable view does need horizontal scrollbar*** and still scrolls vertically
   - Note: add negative margin-bottom but adding padding-bottom doesn’t really help

### Horizontal / Scrollbar Trackbar Width

- [x]  Overflow scroll always adds space for scrollbar
   - Solution: just add negative margin

### Vertical  / No Trackbar Width

- [x] Scroll view does need vert scrollbar
   - Solution: adding negative margin and padding should be fine
- [ ] ***Scroll view does not need vert scrollbar*** and still scrolls horizontally
  - Note: needs verification that negative margin-right and adding padding-right solves this 

### Vertical / With Trackbar Width

- [x] Overflow scroll always adds space for scrollbar
   - Solution: just add negative margin

------

- [x] add Chrome scrollbar width/height styling when calling `getScrollbarWidth()` to remove check for `isFirefox`. This means Chrome never allocates space for a scrollbar.
- [x] update initial rendering to always apply negative margins
- [ ] update initial rendering to only apply padding or some kind scroll spacing  when  `getScrollbarWidth()` is zero.

**Comment by OfTheDelmer** [comment]
To reproduce in Firefox

- Have a mouse plugged then the legend looks fine
- Unplug mouse and trackpad over graph... legend collapses and hides contents

![Kapture 2019-03-21 at 13 05 46](https://user-images.githubusercontent.com/4994741/54770719-2fe4fa80-4bda-11e9-948b-a734ed3df53d.gif)

**Comment by OfTheDelmer** [comment]
@alexpaxton I think this is a fancy scrollbars firefox issue relating to mouse vs trackpad on mac
