### ISSUE TITLE
Cannot read property 'toDomXCoord' of undefined

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#12658]
To repro, start with a fresh install, add a telegraf config, push data, open the system dashboard, and change the dashboard to refresh every 5 seconds

Version 2.0.0 (0e5e2a5)

![image](https://user-images.githubusercontent.com/4805997/54464957-1c4b1700-4736-11e9-984a-812120516e99.png)

**Comment by OfTheDelmer** [comment]
Not able to reproduce this

**Comment by OfTheDelmer** [comment]
I actually saw this error. I was configuring a graph and another graph failed with this message

**Comment by OfTheDelmer** [comment]
![Screen Shot 2019-03-21 at 11 47 47 AM](https://user-images.githubusercontent.com/4994741/54765053-3752d680-4bcf-11e9-9b4b-786e53dcfe80.png)
![Screen Shot 2019-03-21 at 11 47 20 AM](https://user-images.githubusercontent.com/4994741/54765069-3e79e480-4bcf-11e9-9404-5cc342c16d6c.png)
