### ISSUE TITLE
Remove extra nesting from template relationships

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#12653]
```
relationships : {
      ["label"]: {data : [ labelrelationships ] } 
}
```

the data here is extra nesting that doesn't accomplish anything. Convert to:

```
relationships : {
      ["label"]: [ labelrelationships ]
}
```

**Comment by ebb-tide** [comment]
We need to change
- resourceToTemplate.js,
- template instantiation functions in task and dashboard wrappers in client
- the system template

**Comment by OfTheDelmer** [comment]
not sure how much we've deviated form the JSON API spec already on export/import, but if we stick with it then we could both transition to using a lib for deserialization/serialization for import/export and encourage the use of such libs to work with the compound documents.
