### ISSUE TITLE
How can I receive subscribed data of tags and fields

### ISSUE THREAD

**Issue by zxbzswxr** [influxdata/influxdb#12666]
I want to subscribe custom data with influxdb. now Walking through what I have tried and please help me with these problem
first , I create a database named  'myDB' with one measurement  "temperature" in which these is  one tag named "officename", one field named "value" . I prepared some data for inserting operation like this.
INSERT temperature,officename=office1 value=5
INSERT temperature,officename=office1 value=62
.....
And it works, the data is definitely stored into influxdb.
Next I want to create my own subscription item.
I tried to follow influxdb  subscription-management tutorial https://docs.influxdata.com/kapacitor/v1.5/administration/subscription-management/

and paste the below line to influx client cmd,
create subscription "mysub1" on "myDB"."autogen" DESTINATIONS ALL 'http://localhost:6770'

I have already written a http server using node.js  and listen 6770 port;

![image](https://user-images.githubusercontent.com/18022264/54469853-1bb78c80-47d9-11e9-8d9a-8dac2a66e9f6.png)

In order to see what influxdb would post to my http server.
I copy and paste the prepared INSERT commands to Influx client cmd  which showed above .
The INSERT operation is OK. 
but what my node.js http server receive is like this.
![image](https://user-images.githubusercontent.com/18022264/54469894-e6f80500-47d9-11e9-927e-dbd34ae8c1a1.png)
![image](https://user-images.githubusercontent.com/18022264/54469944-97fe9f80-47da-11e9-9ac9-cb66fecceedb.png)

and I searched in the request params ,this may be the only data that can be useful to determinate the operation I had performed like "/write?consistency=&db=myDB&precision=ns&rp=autogen"

but I want the influxdb to post data about measurements "temperature", tag "officename" and field "value". What can I do to make it work ,help me please!

**Comment by russorat** [comment]
@zxbzswxr if i understand your issue correctly, there is no way to change the format of the subscription data influxdb forwards. You will need to update your code to conform to the POST request being forwarded from influxdb.

Please open a new issue for a feature request and reference this issue if you think this would be valuable.
