### ISSUE TITLE
Storage does not call Free on tables

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#12681]

**Comment by jlapacik** [comment]
Storage uses a `memory.Allocator` to track the memory of each table that it produces here:

https://github.com/influxdata/influxdb/blob/master/storage/reads/table.go#L265-L294

However, the above calls to `Allocate` are never paired with a corresponding call to `Free`, and the max memory allocated climbs as storage produces more tables for the query tier to consume.
