### ISSUE TITLE
task: formalize accepted cron syntax

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#12701]
The task code currently uses https://gopkg.in/robfig/cron.v2 (source code at https://github.com/robfig/cron/tree/v2) for parsing Cron syntax. It's been working fine, but we need to whether we are happy with that syntax, whether we want to support or allow or reject `@monthly`, `@weekly`, `@daily`, etc.

Also noteworthy is that v3 of the library is in development and by default disallows specifying seconds in cron syntax, due to seconds being nonstandard.

**Comment by russorat** [comment]
let's plan a meeting to discuss

**Comment by aanthony1243** [comment]
need an RFC to get this moving
