### ISSUE TITLE
InfluxDB 2.0: Missing horizontal scrollbar on Script Editor (from dashboard) with raw data

### ISSUE THREAD

**Issue by pmazon** [influxdata/influxdb#12719]
Seen on InfluxDB 2.0.0 Alpha 6, worked ok on Alpha 5.

![output](https://user-images.githubusercontent.com/800287/54592095-f078ab80-4a2b-11e9-8b29-5e7a5438d8b7.gif)

**Comment by russorat** [comment]
@pmazon thank you! we will fix.
