### ISSUE TITLE
Error response from /api/v2/write does not match swagger documentation

### ISSUE THREAD

**Issue by danielnelson** [influxdata/influxdb#12713]
When a request to `/api/v2/write` fails the error response does not match the documented error responses.

#### steps

1. `curl -X POST 'http://127.0.0.1:9999/api/v2/write?bucket=foobar&org=influxdata'`

#### expected

Response should contain 4 strings: `code`, `message`, `op`, and `err`.

#### actual

No `err` value, instead a `error` object containing several strings.

```
HTTP/1.1 404 Not Found
Content-Length: 131
Content-Type: application/json; charset=utf-8
Date: Tue, 19 Mar 2019 00:29:44 GMT
X-Platform-Error-Code: not found

{
    "code": "not found", 
    "error": {
        "code": "not found", 
        "message": "bucket not found"
    }, 
    "message": "bucket not found", 
    "op": "http/handleWrite"
}
```

**Comment by russorat** [comment]
please ensure the bucket name is provided in the error response. https://github.com/influxdata/telegraf/issues/5600

**Comment by danielnelson** [comment]
I suggest against putting the bucket name in the error response, as that allows the client to have some limited control over the response body.  That's not a problem so long as we do everything right but if we mess up it can be a security issue.

@russorat If we want to provide for the issue in Telegraf, we should open a new feature request issue for consideration.
