### ISSUE TITLE
cURL single quotes for WHERE clause in DROP SERIES not recognized by InfluxDB

### ISSUE THREAD

**Issue by shantanoo-desai** [influxdata/influxdb#12720]
## System
__InfluxDB__: `v1.6.1`
__Machine__: `Windows 10`

## Purpose
Want to drop some series with particular tags via `DROP SERIES` command.

    DROP SERIES FROM "measurement_name" WHERE "tag_name"='tag_value'

> Since Dropping series is not possible via Chronograf as retention policies are not recognized

I am using cURL to perform the same.

## Execution

    curl -i -XPOST 'http://localhost:8086/query?db=test' --data-urlencode 'q=drop series  from "pressure" where "unit"='hPa''

Which produces a log in the daemon as follows:

```
2019-03-18T18:36:37.818018Z     info    Executing query {"log_id": "0EGWa~nl000", "service": "query", "query": "DROP SERIES FROM pressure WHERE unit = hPa"}
[httpd] 127.0.0.1 - - [18/Mar/2019:19:36:37 +0100] "POST /query?db=test HTTP/1.1" 200 33 "-" "curl/7.35.0" c3b5ba54-49ac-11e9-800e-000000000000 0
```
observe that: ` "query": "DROP SERIES FROM pressure WHERE unit = hPa"` no single quotes are recognized

And the corresponding response is in fact __HTTP 200 OK__:

```
HTTP/1.1 200 OK
Content-Type: application/json
Request-Id: ebd5b2a4-49ab-11e9-800b-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.6.1
X-Request-Id: ebd5b2a4-49ab-11e9-800b-000000000000
Date: Mon, 18 Mar 2019 18:30:35 GMT
Transfer-Encoding: chunked

{"results":[{"statement_id":0}]}
```

The data still exists and nothing is dropped:

```
select * from pressure limit 10

name: pressure
time                unit                  v
----                ----                    -
1545153813714000000 hPa  101997
1545153814761000000 hPa  102004
1545153816045000000 hPa  102006
1545153817203000000 hPa  102003
1545153818265000000 hPa  102003
1545153819446000000 hPa  102003
1545153820498000000 hPa  102004
1545153821680000000 hPa  102007
1545153822854000000 hPa  102003
1545153823904000000 hPa  102003
```

Even if I restart the Daemon again the data still exists.

However when I use the InfluxCLI to perform the same query:

     drop series  from "pressure" where "unit"='hPa'

The series is dropped successfully and the Logs in the Daemon recognizes the single quotes around the tag values:

    DROP SERIES FROM pressure WHERE unit = 'hPa'

I tried escaping the quotes in curl but the it shoots an error of `\\` not being recognized

     curl -X POST 'http://localhost:8086/query?db=test' --data-urlencode 'q=DROP SERIES WHERE "unit"=\'hPa\' '

    {"error":"error parsing query: found \\, expected identifier, string, number, bool at line 1, char 26"}

The single quotes usage is consistent with that of the InfluxDB Docs Examples

**Comment by rickard-von-essen** [comment]
Your command isn't properly escaped. Try adding backslashes here: `where "unit"=\'hPa\''`

**Comment by shantanoo-desai** [comment]
@rickard-von-essen I tried doing the same but the WSL terminal still anticipates a single quote ending

**Comment by shantanoo-desai** [comment]
I managed to get something to work. 
I am using Windows Subsystem For Linux (WSL) with `zsh` so I decided to use double quotes and multi-line usage:

```
curl -i -XPOST \
> 'http://localhost:8086/query?db=test' \
> --date-urlencode \
> "q=DROP SERIES FROM WHERE "unit"='hPa'"
```

This works
