### ISSUE TITLE
Table options column re-ordering is broken

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#12743]
![column-rearrange-weirdness](https://user-images.githubusercontent.com/2433762/54628737-5fa5ce00-4a33-11e9-8a30-a609bc83ee1d.gif)
Does not behave as expected

**Comment by mark-rushakoff** [comment]
This is still an issue as of db72f57da4035b2f9a32859c27e9677d4251b449.

**Comment by russorat** [comment]
this is no longer an issue.
