### ISSUE TITLE
To transformation should be able to write nulls

### ISSUE THREAD

**Issue by affo** [influxdata/influxdb#12781]
from REPL:

```
> data = "#datatype,string,long,string,string,string,dateTime:RFC3339,double
#group,false,false,true,true,true,false,false
#default,_result,,,,,,
,result,table,_measurement,_field,t0,_time,_value
,,0,m1,f1,server01,2018-12-19T22:13:30Z,-61.68790887989735
,,0,m1,f1,server01,2018-12-19T22:13:40Z,-6.3173755351186465
,,0,m1,f1,server01,2018-12-19T22:13:50Z,
,,0,m1,f1,server01,2018-12-19T22:14:00Z,114.285955884979
,,0,m1,f1,server01,2018-12-19T22:14:10Z,16.140262630578995
,,0,m1,f1,server01,2018-12-19T22:14:20Z,29.50336437998469
,,1,m1,f1,server02,2018-12-19T22:13:30Z,
,,1,m1,f1,server02,2018-12-19T22:13:40Z,49.460104214779086
,,1,m1,f1,server02,2018-12-19T22:13:50Z,-36.564150808873954
,,1,m1,f1,server02,2018-12-19T22:14:00Z,34.319039251798635
,,1,m1,f1,server02,2018-12-19T22:14:10Z,
,,1,m1,f1,server02,2018-12-19T22:14:20Z,41.91029522104053"
> import "csv"
> csv.from(csv: data) |> to(bucket:"test", org:"root")
Error: point without fields is unsupported
```

The error gets returned here: https://github.com/influxdata/influxdb/blob/582ed6834c4e7c465f3b02f742f3977eed467d7c/models/points.go#L1382.

When `to` is writing points: https://github.com/influxdata/influxdb/blob/d18c6e5ffe8d2d025875a4cb3d21c82d88751ab3/query/stdlib/influxdata/influxdb/to.go#L591

**Comment by nathanielc** [comment]
The storage engine does not have a way of writing `null` values. We can make the `to` function not error on nulls but it will only be able to ignore them, not write them.

Does that sound like an reasonable solution?

**Comment by affo** [comment]
Yeah, I see your point.

The problem emerges when we are running e2e tests for flux.  
We use `to` to store input data and then we extract it with a `from`. If that input data doesn't have `nulls`, then the expected result would be different.  

We should somehow add a `map` transformation after `from` that adds nulls (however, we cannot express it in flux right now) or keep skipping tests that contains nulls in input data.
