### ISSUE TITLE
Update left nav for new org centric context

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#12798]
Basically, remove the Organizations tab, and replace it with the current organization and an option for settings and switch orgs. Settings would go to the current Organizations -> My Org page.

```
- [Username] 
   - Logout 
- Data Explorer
- Dashboards
- Tasks
- [Active OrgName]
   - Settings
   - Switch Orgs (would open some sort of modal)
```

**Comment by alexpaxton** [comment]
@russorat does it make sense to have a sub-item under `[Active OrgName]`  for `Create New Org`?

By removing the orgs index page we also lose the ability to create orgs

**Comment by russorat** [comment]
if we don't have a modal for switching orgs, then it would have to be there. If we have a modal for switching then maybe it should go there?

**Comment by ebb-tide** [comment]
closed in favor of https://github.com/influxdata/influxdb/issues/12941
