### ISSUE TITLE
Add Org Name to the title of the Tasks page

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#12800]
as a user
with viewer
when i view the list of tasks
then i would like to know the org that i am viewing tasks for
then i would like to be able to quickly switch orgs from this view

**Comment by OfTheDelmer** [comment]
I think this dropdown already exists. Should this issue be design polish to make it more discoverable?

![Screen Shot 2019-03-21 at 11 09 59 AM](https://user-images.githubusercontent.com/4994741/54762140-e4c2eb80-4bc9-11e9-96fa-639a8250455d.png)

**Comment by russorat** [comment]
We are changing everything to be in an org specific view. So this page won't show the tasks from all orgs, but only the tasks in the current org you are in. So in this case, we want to remove the All Orgs dropdown, and add the name of the Org to the title of the page, so that it says "Org's Tasks".
