### ISSUE TITLE
refreshing the veo opened from editing a cell, does not persist the cell's view information

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#12803]

**Comment by ischolten** [comment]
either we should go back to the dashboard on refresh and close the overlay, or we should fetch the cell/view's data again and populate the veo. @russorat thoughts?

**Comment by russorat** [comment]
populate

**Comment by OfTheDelmer** [comment]
See also https://github.com/influxdata/influxdb/issues/12816
