### ISSUE TITLE
Could I make a custom variable for Tags Query?

### ISSUE THREAD

**Issue by alphacr** [influxdata/influxdb#12809]
I have main query named `Type` that returns 10 results and takes the query
```SHOW TAG VALUES FROM "transactions_per_minute" WITH KEY = "product_type"```
I would like to use the "Value groups/tags" feature that will show a tag named `Foo` that will automatically checks 7 values out of the 10 results. and the rest of the 3 onto another.

Trying to follow the guide from [this thread](https://github.com/grafana/grafana/issues/4299)
I have created another variable named `FooValues` where it takes the query 
```SHOW TAG VALUES FROM "transactions_per_minute" WITH KEY = "product_type" where product_type!='bar' and product_type!='qux' and product_type!='quux``` and 
I've added a new variable named `FooVariable` that contains the string `Foo`

I have also added the following query for the `Type` Tag values query but it doesn't seem to work as I don't know what to put on the "Tags query":
```SHOW TAG VALUES FROM "transactions_per_minute" WITH KEY = "product_type" WHERE "product_type"=$FooValues```

I tried to put the above query on the "Tags query" but it seems to return all of the values of `FooValues` and even then it doesn't even link itself to the actual main query.
![image](https://user-images.githubusercontent.com/14267755/54734749-69b30280-4bd4-11e9-8483-81dd530ee1cb.png)

Any help would be greatly appreciated

Grafana version: 4.6.5

**Update**:
I've read up on [this document](http://docs.grafana.org/reference/templating/#formatting-multiple-values) and it seems that I needed to add in the `$tag` in the query somewhere but i still dont exactly know how i'll map each values.

**Comment by russorat** [comment]
@alphacr this is an issue that should be opened with the Grafana team https://github.com/grafana/grafana
