### ISSUE TITLE
Safari: Keyboard shortcut to submit query crashes viz 

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#12818]
To repro, open the system dashboard in safari, switch to the editor, make a change, and try to use the keyboard shortcut to submit the change. (ctrl+enter)

![image](https://user-images.githubusercontent.com/4805997/54770499-978e4c00-4bc0-11e9-8e3b-ca9b42e7b507.png)

**Comment by chnn** [comment]
Can't reproduce on latest master (`89b38cd21`).
