### ISSUE TITLE
Return to cell editor after signin 

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/influxdb#12816]
Routing to the cell editor redirects back to `signin` page on exit.

Steps to reproduce.

- Open cell editor 
- Clear application state in the browser developer tools
- Wait at most 60 seconds for redirection to signin again
- Signin and be returned to the cell editor
- Exit the cell editor and be redirected to `/siginin`

This looks like an issue of using `goBack` on close

`influxdb/ui/src/dashboards/components/VEO.tsx`

```ts
  private close = (): void => {
    this.props.router.goBack()
  }
```

![Kapture 2019-03-21 at 10 49 57](https://user-images.githubusercontent.com/4994741/54761127-e2f82880-4bc7-11e9-8f10-ad4dbd311362.gif)

**Comment by ischolten** [comment]
https://github.com/influxdata/influxdb/pull/12836 should have fixed this
