### ISSUE TITLE
task: Remove Option caching in tests

### ISSUE THREAD

**Issue by lyondhill** [influxdata/influxdb#12829]
We no longer need to cache options in task tests because flux is much faster
see https://github.com/influxdata/platform/issues/484

**Comment by mark-rushakoff** [comment]
Last time I took a stab at this, the tests had a noticeable slowdown after removing caching, so I left the caching in.

Whoever picks this up, please confirm the timing difference on the change, and file a new flux issue if warranted.

**Comment by lyondhill** [comment]
@mark-rushakoff good point. I didn't test if it were faster I just saw the issue linked has been closed.
