### ISSUE TITLE
so slow in count(*)

### ISSUE THREAD

**Issue by zeinsteinz** [influxdata/influxdb#12839]
I am using influxdb v1.7.4 in ubuntu 16.04. I insert high frequency data (12000Hz), total amount is around 400 millions. I also set shard duration as 1hour. The data has only one series.
When I am trying to get total number of items by using "select count (*) from data", it is always running background over one hour and still output nothing.(cpu usage of influxd is around 200%) I can not wait it each time so I stop it. 
Could anyone help me to figure out the problem

**Comment by russorat** [comment]
@zeinsteinz can you describe a little more as to what you are trying to accomplish and what your schema is?

**Comment by Zhan-boyi** [comment]
I have the same problem. My measurement has a timestamp, a tag, and 22 fields. When I use the count function, it takes 80 seconds to query 100 million pieces of point.
