### ISSUE TITLE
Add a way for the user to create a Read/Write Token to read/write to one or many buckets

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#12848]
as a user
with admin
when i view the list of tokens
then i would like the ability to create a new Read/Write API token

A Read/Write token will only give users the ability to read/write to all, one or multiple buckets as well as read telegraf configurations for that org. The purpose of these tokens are to use them with either Telegraf or one of the Client Libraries.

**Comment by 121watts** [comment]
@russorat aren't we punting on this until we get the taxonomy of permissions?
