### ISSUE TITLE
Crosshairs go past the edge of the visualization

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#12852]
to reproduce:
1. create a cell with relative time and make sure autorefresh is paused.
1. around 30s to a minute later, create another cell with a query (this one will have more recent data than the original). 
1. Hover over the end of the newer cell's data and the crosshair should go off to the right of the original cell.  
1. Hover over the beginning of the original cell's data and the crosshair should go off the left of the newer cell. 

![crosshairs-over](https://user-images.githubusercontent.com/5751863/54856895-e4a21900-4cb9-11e9-878b-ec02ff411c45.gif)

Expectation: the crosshairs stay within the cell's visualization.

**Comment by chnn** [comment]
Fixed when we integrated the new vis library.
