### ISSUE TITLE
Meta queries should have their own RPC call

### ISSUE THREAD

**Issue by jlapacik** [influxdata/influxdb#12851]
Meta queries in Flux come in 2 flavors:

* Queries that fetch tag keys
* Queries that fetch tag values

Q: Are there more? SHOW SERIES?

Storage has efficient APIs for fetching both of these and which don't require touching TSM files like normal queries do. Unfortunately right now, unbounded flux queries (queries without a range) are not allowed, so all meta queries specify a default range of 30 days, and this guarantees that we touch TSM files which negatively impacts the performance of these meta queries.

These queries should instead be answered using two specialized RPC calls that use the storage APIs for fetching tag keys and values. These RPC calls would correspond to two physical index read operations at the query planning level:

* ReadTagKeys
* ReadTagValues

These types of queries correspond to the following flux patterns respectively:

```
from |> filter |> keys |> keep |> unique     // tag keys
from |> filter |> keep |> unique             // tag values
```

Note that a call to `from` as well as a terminating `keep |> unique` is required. Any unbounded query not satisfying this pattern would fail planning.

I'm not entirely if we need 2 RPC calls or just one, as the data access pattern should be mostly the same between the two types of queries (when a filter is specified).

It would also be nice to incorporate this into the stack based planning method defined in #10758. A `unique` call at the top of the stack would map to the meta query RPC call. I don't know if this would work though, as `from |> range |> filter |> keep |> unique` is a meta query that must touch TSM files whereas `from |> filter |> keep |> unique` does not. Also a plain `from |> filter` is not valid.

**Comment by wolffcm** [comment]
I like this approach a lot.  I think it will work with the stack-based approach from #10758.

If there is no `range`, then the logical planner would still produce `from |> filter ...` and the desired patterns metaqueries in the physical planner could match what's described here.  So basically the physical planner would have a set of rules:
- `from |> range |> ...` --> produce a normal read gRPC call
- `from |> filter |> ...` --> produce a meta-query gRPC call if possible

If someone tried to roll their own metaquery that included a call to `range` it might be slow.  But most users (and the UI) will use the `influxdata/influxdb/v1` wrappers, which we can optimize to use the patterns above.

**Comment by jlapacik** [comment]
All queries must be time bounded. That is a product requirement. Therefore meta queries will need to include a range. So the pattern for meta queries then becomes:

```
from |> range |> keys |> keep |> unique  // tag keys
from |> range |> keep |> unique          // tag values
```

**Comment by jsternberg** [comment]
My understanding of this is that there will be a procedure op for these RPC calls and that the planner will replace the from procedure (with the requisite optimizations after) to become these procedure specs.

I'll start learning about the planner and trying to put this together.

**Comment by jlapacik** [comment]
Here is the relevant PR for the tag keys and values API https://github.com/influxdata/influxdb/pull/13409

We already have a `ReadRangePhysSpec` corresponding to the pattern `from |> range`.
https://github.com/influxdata/influxdb/blob/53c28250d634dd8881cc774372025e4874aa9053/query/stdlib/influxdata/influxdb/operators.go#L13

The way I see it working is that there will be a rule matching the pattern `ReadRange |> keep |> unique`. Matching this pattern, the planner will create a `ReadTagKeysPhysSpec`. This procedure spec will be associated with a `ReadTagKeysSource` which will be responsible for calling the relevant storage APIs.

See
https://github.com/influxdata/influxdb/blob/53c28250d634dd8881cc774372025e4874aa9053/query/stdlib/influxdata/influxdb/rules.go#L15
https://github.com/influxdata/influxdb/blob/53c28250d634dd8881cc774372025e4874aa9053/query/stdlib/influxdata/influxdb/source.go#L19
