### ISSUE TITLE
[feature request] JSONP support for query returns

### ISSUE THREAD

**Issue by gingerlime** [influxdata/influxdb#1286]
Influxdb looks really great. Thanks for open-sourcing it.

I'm the creator of [Giraffe](https://github.com/kenhub/giraffe) - a graphite dashboard, and I'm looking at adding Influxdb support to it. JSONP would make things easier / better for Giraffe, and probably other use-cases.

Do you guys have any plans to add JSONP support? (I would love to create a PR, but have zero experience with go, so am a bit hesitant...)

**Comment by pauldix** [comment]
We can put it on our todo list. We have a bunch of other stuff that we're doing for the 0.9.0 release so it'll take us a bit to get to it.

**Comment by gingerlime** [comment]
Thanks @pauldix. I imagine there are lots of other stuff on your list, but if this can also be added / implemented at some point, it would be great.

**Comment by beckettsean** [comment]
JSON is likely to be deprecated in favor of the new line protocol. Closing this issue.

**Comment by juddgaddie** [comment]
Could we please reopen this. As far as I am aware there are no plans to deprecate JSON for reading data.

:+1: for JSONP support.

**Comment by beckettsean** [comment]
Thanks for the note, @juddgaddie, I'll re-open as a feature request for query return formats.

**Comment by jsternberg** [comment]
I'm going to close this for now since I don't think we're going to do it. Please comment if you still really want this.

I think a better implementation for this might be to natively support CORS through a configuration option. If this works as an alternative, please open a new issue so we can work on that for a future release.

Thanks.
