### ISSUE TITLE
Group pushed down to storage always includes _start and _stop

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#12885]
Even when a `group` transformation does not include the `_start` or `_stop` columns, a group pushed into storage will include those columns in the group key:
```
> from(bucket: "my-bucket") 
  |> range(start: -20s) 
  |> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_user") 
  |> group(columns: ["_field"])

Result: _result
Table: keys: [_start, _stop, _field]
...
```
Since the column list in `group` does not include `_start` or `_stop`, it should not be in the group key.  However if I insert a `yield` to inhibit pushing the `group` down, I see the correct behavior:
```
from(bucket: "my-bucket") 
  |> range(start: -20s) 
  |> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_user") 
  |> yield(name: "ignore") 
  |> group(columns: ["_field"])

Result: _result
Table: keys: [_field]
...
```

**Comment by python273** [comment]
so is it a bug or there's some way to group without `_start` and `_stop`?
