### ISSUE TITLE
Update Tasks for private Spec

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#12883]
The flux.Spec is being made private see https://github.com/influxdata/flux/issues/1085. We need to ensure that the uses from within Tasks use the AST version of the API endpoints instead of the Spec.

**Comment by nathanielc** [comment]
Determine what needs to be updated. i.e How does the task code consume the SPEC?

This is part of #12928

**Comment by wolffcm** [comment]
#13219 addresses using the `Query` interface in tasks.  Making tasks use `ASTCompiler` seems straightforward and will be done as part of https://github.com/influxdata/influxdb/issues/12928
