### ISSUE TITLE
influx time is earlier than now()

### ISSUE THREAD

**Issue by renchili** [influxdata/influxdb#12895]
we can see the influxDB is running with now as in screenshot :
![Screen Shot 2019-03-26 at 11 01 42 PM](https://user-images.githubusercontent.com/33677006/55008204-9d01f100-501b-11e9-9326-e8ab5269e50f.png)
but  my data got something like this 
![Screen Shot 2019-03-26 at 11 02 21 PM](https://user-images.githubusercontent.com/33677006/55008395-ea7e5e00-501b-11e9-9a29-bbcacdd31664.png)

**Comment by russorat** [comment]
@renchili we use UTC for times. is the difference the offset between your time zone and UTC?
