### ISSUE TITLE
Dashboard view component cannot read properties

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/influxdb#12905]
![Screen Shot 2019-03-26 at 2 16 43 PM](https://user-images.githubusercontent.com/4994741/55024811-0101c680-4fd6-11e9-8170-52e01176c287.png)

Steps to reproduce:

- On a new influxdb create a user
- Create a dashboard with an empty cell
- Add a telegraf and system dashboard
- Go to the dashboards index and select one
- Go back click the other dashboard and all the cells fail to load
- Refreshing the page all cells render fine

**Comment by bthesorceror** [comment]
Can no longer reproduce on master
