### ISSUE TITLE
GROUP BY requires at least one aggregate function

### ISSUE THREAD

**Issue by meriemaboudi** [influxdata/influxdb#12929]
While executing this query : 
Query queryObject = new Query("Select * from metric where  \"name\" = "+"'"+nameMetric+"' and time >= '"+fD+"' AND time <= '"+tD+"' GROUP BY time(12m)" , dbName);

I'm getting this error: 
Exception in thread "main" org.influxdb.InfluxDBMapperException: InfluxDB returned an error with Series: GROUP BY requires at least one aggregate function

**Comment by MK-2001** [comment]
This is needed. You can find it in the readme below the example.

The example is not working without it:
step - (required if aggregate is not "none") used for aggregate functions (max, min, average, total, count) step in ms of intervals

`var end = new Date().getTime();
sendTo('influxdb.0', 'getHistory', {
    id: 'system.adapter.admin.0.memRss',
    options: {
        start:      end - 3600000,
        end:        end,
        step:       60000,
        aggregate: 'average' // or 'none' to get raw values
    }
}, function (result) {
    for (var i = 0; i < result.result.length; i++) {
        console.log(result.result[i].val + ' ' + new Date(result.result[i].ts).toISOString());
    }
});`
