### ISSUE TITLE
Make all Flux clients use ASTCompiler instead of SpecCompiler

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#12928]
The `SpecCompiler` is being retired, since `Spec` is becoming a private data structure internal to `Flux`.  Some clients still use `SpecCompiler` including the REPLs, maybe others.

Child issue of: https://github.com/influxdata/flux/issues/1085

**Comment by jsternberg** [comment]
We will be excluding the REPL from this task as the REPL needs to be redesigned.
