### ISSUE TITLE
Password bypass vulnerability

### ISSUE THREAD

**Issue by a1ien** [influxdata/influxdb#12927]
We can authorize by any user. For that we can use jwt token with empty shared_secret.
It's happen because https://github.com/influxdata/influxdb/blob/e2af85d6503ecaaa4dbdbdd9ddad740741dae582/services/httpd/handler.go#L1585-L1602 here we not check that h.Config.SharedSecret is not empty string.
In `Authentication and authorization in InfluxDB` document we not mention anything about `shared-secret` variable.

Also sems like we also not check exp state of token. And once generated token valid forewer.

**Comment by e-dard** [comment]
Thanks for the report @a1ien. We are investigating this issue as a priority.

**Comment by dgnorton** [comment]
@a1ien again, thanks for reporting the issue. A PR to fix the shared secret issue has been made.

> Also sems like we also not check exp state of token. And once generated token valid forever.

If the expiration claim is set on the token and it has expired, the parser will return an error here:

https://github.com/influxdata/influxdb/blob/932521b6ffb98d2a96b5895c6cecd5ebae83bd32/services/httpd/handler.go#L1606-L1608

It ensures an expiration was set here:

https://github.com/influxdata/influxdb/blob/932521b6ffb98d2a96b5895c6cecd5ebae83bd32/services/httpd/handler.go#L1623-L1627

And is tested here:

https://github.com/influxdata/influxdb/blob/932521b6ffb98d2a96b5895c6cecd5ebae83bd32/services/httpd/handler_test.go#L209-L219

**Comment by a1ien** [comment]
i am not see any check that exp > time.now

**Comment by dgnorton** [comment]
@a1ien the check isn't done by InfluxDB. It's done by the [jwt library](github.com/dgrijalva/jwt-go) InfluxDB uses to parse tokens. The `jwt.Parse` function mentioned above will return an error if it sees that the token has expired.

**Comment by a1ien** [comment]
@dgnorton Ah you are correct.

**Comment by e-dard** [comment]
Fixed via #13088, #13132, #13133.
