### ISSUE TITLE
CQ with offset interval

### ISSUE THREAD

**Issue by nywitness** [influxdata/influxdb#12926]
Hi there,
##### System
- Windows 10
- InfluxDB 1.7.5

##### Problem
My CQ is:
```
CREATE CONTINUOUS QUERY cq_2m ON temp 
BEGIN 
        SELECT mean(rate) AS rate INTO temp.autogen.cq_2m 
        FROM temp.autogen.perflog 
        GROUP BY time(2m,8h) fill(0) 
END
```
I'm using this `8h` because we insert perflog data with local time instead of UTC time and CQ executes with UTC time rather than localtime. However, it turned out that the clause `GROUP BY time(2m,8h)` didn't take effects and the log shows time range is still in UTC form(localtime is `15:04:00`): 
```
2019-03-27T07:04:00.029446Z     info    Executing continuous query {"log_id": "0ERSB7o0000", "service": "continuous_querier", "trace_id": "0ERVFR7G000", "op_name": "continuous_querier_execute", "name": "cq_2m", "db_instance": "temp", "start": "2019-03-27T07:02:00.000000Z", "end": "2019-03-27T07:04:00.000000Z"}
2019-03-27T07:04:00.030061Z     info    Executing query {"log_id": "0ERSB7o0000", "service": "query", "query": "SELECT mean(rate) AS rate INTO temp.autogen.cq_2m FROM temp.autogen.perflog WHERE time >= '2019-03-27T07:02:00Z' AND time < '2019-03-27T07:04:00Z' GROUP BY time(2m,8h) fill(0)"}
```
Did i miss anything?
Any help is appreciated!

**Comment by mzanders** [comment]
Hi,
time(2m,8h) won't have an effect as the function only takes one argument, which is the period to which you are aggregating the source data to. Output data is also referenced to UTC.
You can enlarge the dataset for each consecutive CQ run by using the advanced syntax (RESAMPLE FOR 8h) but that will only work if the local time is less then UTC as the dataset is enlarged before now(). In your case, using it will result in "start": "2019-03-26T23:02:00.000000Z", "end": "2019-03-27T07:04:00.000000Z".
I think the logical assumption is that you're not supposed to generate data after now() and use CQ's on it.
I'm afraid you will have to transform your data to UTC in some way.
And the bad news: I don't see a way to do this with the current feature set inside influx but might be wrong.

**Comment by nywitness** [comment]
> Hi,
> time(2m,8h) won't have an effect as the function only takes one argument, which is the period to which you are aggregating the source data to. Output data is also referenced to UTC.
> You can enlarge the dataset for each consecutive CQ run by using the advanced syntax (RESAMPLE FOR 8h) but that will only work if the local time is less then UTC as the dataset is enlarged before now(). In your case, using it will result in "start": "2019-03-26T23:02:00.000000Z", "end": "2019-03-27T07:04:00.000000Z".
> I think the logical assumption is that you're not supposed to generate data after now() and use CQ's on it.
> I'm afraid you will have to transform your data to UTC in some way.
> And the bad news: I don't see a way to do this with the current feature set inside influx but might be wrong.

Right, `time(2m, 8h)` hasn't take the `8h` argument. However, it is said it should be taken as is shown in the [influx document](https://docs.influxdata.com/influxdb/v1.7/query_language/continuous_queries/#basic-syntax) (Example 4).

Actually i tried from version 1.0 to 1.7 and none of them is working. I guess store data in UTC might be a good way. Thanks for the help.

Cheers.
