### ISSUE TITLE
Replace FancyScrollbars with DapperScrollbars

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#12960]
FancyScrollbars has been a point of frustration for a long time and the maintainer of the underlying library doesn't seem interested in fixing the problems that affect our use case. Looks like we're not the only ones seeing as there's a new library created as an offshoot of `react-custom-scrollbars` that's called `react-scrollbars-custom` that seems to work better so far.

Since `FancyScrollbars` is used fairly widely it will take multiple PRs to fully replace it with `DapperScrollbars`

**Comment by russorat** [comment]
break this up into a few cards for various parts of the app
