### ISSUE TITLE
Variables control bar should not look for partial match

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#12991]
currently if a cell uses v.buckets as a variable in a query, v.buck also shows up in the variables control bar as a match. This will cause v.buck to also be exported in a template of the dashboard.

**Comment by OfTheDelmer** [comment]
This is no longer an issue. Closed in  https://github.com/influxdata/influxdb/pull/13089

We now match a variable up to a boundary
https://github.com/influxdata/influxdb/blame/master/ui/src/variables/utils/hydrateVars.ts#L75
