### ISSUE TITLE
ReadRange RPC call

### ISSUE THREAD

**Issue by jlapacik** [influxdata/influxdb#12998]
The query planner should have a physical read operation called `ReadRange` matching the flux pattern `from |> range`. This operation should map to a corresponding RPC that calls the necessary storage APIs responsible for performing the actual scan of the TSM data.

**Comment by nathanielc** [comment]
See #10758, this is the first step in breaking up the RPC calls.

**Comment by nathanielc** [comment]
Is this different in the storage side if a Filter is included. If a filter on value is included that is a different storage path, but what about filters on just tags?

**Comment by jlapacik** [comment]
Closed with #13122 .
