### ISSUE TITLE
Flux filter() is not applied when using distinct() function

### ISSUE THREAD

**Issue by rhajek** [influxdata/influxdb#13016]
When the `distinct` function is called on end of flux command, it looks like that the previous filter functions are not applied. In my case `filter(fn: (r) => r.state == "XXX")` should return empty result, but the filter is ignored and result contains records with all possible state values.

When I comment out `distinct(column: "pod_name")` , filtering is working correctly and result is empty.

```
from(bucket: "default")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "kubernetes_pod_container")
  |> filter(fn: (r) => r._field == "state_code")
  |> filter(fn: (r) => r.host == v.host)
//  |> filter(fn: (r) => r.namespace == v.namespace)
  |> filter(fn: (r) => r.state == "XXX") 
  |> drop(columns: ["container_name"])
  |> distinct(column: "pod_name")
//  |> group(columns:["state","pod_name","_value", "namespace"], mode: "except")
//  |> count()
```

"version": "2.0.0-alpha.7", "commit": "3ceae6198", "build_date": "2019-03-29T01:09:17Z"

**Comment by rhajek** [comment]
![Kapture 2019-04-03 at 10 23 07](https://user-images.githubusercontent.com/2169548/55464242-f3ae9280-55fa-11e9-8d47-24449998c134.gif)

**Comment by rhajek** [comment]
This strange bug is also somehow related with filtering by v.host variable. When I replaced "v.host" with the real hostname, filtering starts to work correctly.

![Kapture 2019-04-03 at 11 00 06](https://user-images.githubusercontent.com/2169548/55466673-f2cc2f80-55ff-11e9-86ea-34725004dba2.gif)

**Comment by maxpain** [comment]
Any updates?
