### ISSUE TITLE
Change Log / {Debian,Ubuntu} packages missing for v1.7.5

### ISSUE THREAD

**Issue by dictvm** [influxdata/influxdb#13038]
I cannot find a change log for the latest 1.7.5 release of InfluxDB and there has been no update to the Debian/Ubuntu repo index yet.

**Comment by tsupertramp** [comment]
Just found the reason (https://docs.influxdata.com/influxdb/v1.7/about_the_project/releasenotes-changelog/)

> Update (2019-04-01): If your InfluxDB OSS server is using the default in-memory index ([data].index-version = "inmem"), then do not upgrade to this release. Customers have reported that InfluxDB 1.7.5 stops responding without warning. For details, see GitHub issue #13010. The planned fix will be available soon.

So they removed it on purpose.

**Comment by dictvm** [comment]
I see. IMHO, this could have been made more clear. A simple "we have removed the packages from the public repos" would have been sufficient.

I'm closing this then.
