### ISSUE TITLE
Update variables wrapper in client to add labels

### ISSUE THREAD

**Issue by Palakp41** [influxdata/influxdb#13051]
- [ ] update the client variables wrapper to include the following methods: `addLabels`, `removeLabels`. Will these be clonable? 
- [ ] Create an `IVariable` type that uses `ILabel` type and `ILabelProperties`
https://github.com/influxdata/influxdb2-js/blob/master/src/wrappers/tasks.ts#L2
....

**Comment by Palakp41** [comment]
Blocked on #13059

**Comment by OfTheDelmer** [comment]
Will be closed after https://github.com/influxdata/influxdb2-js/pull/82
