### ISSUE TITLE
On Org Tasks, the labels are created but not displaying until refreshed

### ISSUE THREAD

**Issue by Palakp41** [influxdata/influxdb#13057]
Tasks tab on orgs page doesn't display labels being added or removed. They need to be added to the redux state in order for them to populate on the task in org page.

**Comment by 121watts** [comment]
@ebb-tide will this story be necessary after your reorg PR is merged?

**Comment by ebb-tide** [comment]
do not do

**Comment by ebb-tide** [comment]
This issue will be gone after org reborg
