### ISSUE TITLE
Move chronograf to use AST types from client

### ISSUE THREAD

**Issue by bthesorceror** [influxdata/influxdb#13069]
Migrate any place in the UI that is using AST types defined in the UI to instead import them from the client library.

**Comment by chnn** [comment]
It looks like the types were removed from the client at some point. We only have the autogenerated ones left.

So I think this task would be to move [these](https://github.com/influxdata/influxdb/blob/master/ui/src/types/ast.ts) into the client, and then to start consuming them.

**Comment by 121watts** [comment]
- [ ] Move `influxdb/ui` AST types to client
- [ ] Consume migrated types in `influxdb/ui`
- [ ] Delete `influxdb/ui` local ast types
