### ISSUE TITLE
Audit all resource types in the API to ensure they have the following: Name, Description, Labels, CreatedAt, LastUpdatedAt

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13066]
Audit all resource types in the API to ensure they have the following: Name, Description, Labels, CreatedAt, LastUpdatedAt

**Comment by jademcgough** [comment]
I've added a google doc with this information to the influxdata org.

**Comment by russorat** [comment]
see the following for resolution:
- https://github.com/influxdata/influxdb/issues/13489
- https://github.com/influxdata/influxdb/issues/13488
- https://github.com/influxdata/influxdb/issues/13487
- https://github.com/influxdata/influxdb/issues/13486
- https://github.com/influxdata/influxdb/issues/13485
- https://github.com/influxdata/influxdb/issues/13484
- https://github.com/influxdata/influxdb/issues/13483
- https://github.com/influxdata/influxdb/issues/13482
- https://github.com/influxdata/influxdb/issues/13481
- https://github.com/influxdata/influxdb/issues/13480
- https://github.com/influxdata/influxdb/issues/13479
- https://github.com/influxdata/influxdb/issues/13478
- https://github.com/influxdata/influxdb/issues/13477
- https://github.com/influxdata/influxdb/issues/13476
- https://github.com/influxdata/influxdb/issues/13475
