### ISSUE TITLE
Support `uint64` types in 2.0 UX

### ISSUE THREAD

**Issue by rbetts** [influxdata/influxdb#13092]
In 1.x, we added `uint64` support to influxdb behind a build flag. We flagged this until telegraf, kapacitor, and chronograf added `uint64` support for end-to-end TICK stack functionality. Telegraf supports `uint64` now with an option on the influxdb output. Flux supports `uint64` and tasks inherit that implicitly.  

We still need to add support the UX, I think. Support for `uint64` should (maybe?) be easier with the 2.0 query response format - as we don't have to work around JSON 64-bit serialization weirdnesses.

See: https://github.com/influxdata/influxdb/issues/7801#issuecomment-466801839 for a user using telegraf and influx 1.x successfully with uint64.

**Comment by lucasbritos** [comment]
@rbetts sorry if this is not the correct place to ask it but is expected any advance on having uint64 end-to-end support this year or next year ? At least in Kapacitor ?
I just opened an issue on Kapacitor https://github.com/influxdata/kapacitor/issues/2199
64 bit counters are a common thing on "Network Infrastructure Monitoring" use case, im not expert on GOLANG but is there anything can I do to help?
