### ISSUE TITLE
Add support for .key and .crt files

### ISSUE THREAD

**Issue by timbru31** [influxdata/influxdb#1310]
I tried to use my existing .crt file for the ssl API however noticed that my influxdb silently crashed with these settings.

The relevant panic string
``panic: crypto/tls: failed to parse key PEM data`` was not logged :-1: 

I'd love to see some support for cert and key files and not just a pem :)
When I changed my config to the pem file, everything worked again.

Cheers

**Comment by sc0rp10** [comment]
+1

**Comment by timbru31** [comment]
any news on this issue?

**Comment by Millnert** [comment]
+1

**Comment by sc0rp1us** [comment]
+1

**Comment by jblaine** [comment]
+1

`  https-certificate = "/etc/httpd/ssl.crt/etc-metrics.our.org.crt"`

```
log:etc-metrics# ls -ld /etc/httpd/ssl.crt/etc-metrics.our.org.crt
-rw-r--r-- 1 root root 2203 Apr 13 12:45 /etc/httpd/ssl.crt/etc-metrics.our.org.crt
log:etc-metrics#
```

`run: open server: open service: crypto/tls: failed to parse key PEM data`

**Comment by jsternberg** [comment]
I don't think this panics anymore if you have an incorrect file, but the issue still isn't completely resolved. Most servers give a way to specify the certificate file separately from the private key file, but we currently rely on a concatenated PEM file to supply both.

I'm going to add a way to specify the private key separately. For now, you can concatenate the private key and the certificate into the same file and specify it as the `https-certificate`. If this doesn't work or you have experienced a panic or lack of a log message when this fails, please comment here so I can make sure to fix it. Thanks.

**Comment by dandv** [comment]
Wanted to add my (and [others'](https://groups.google.com/forum/#!msg/influxdb/Xf8fLoRIJXc/oBndOI7WBQAJ)) voice here - any chance for an easy way to reuse LetsEncrypt certificates without creating any extra files? LetsEncrypt is typically set up to autorenew certificates, and if those `.pem` files can be used by InfluxDB without any extra cron job processing, that would simplify things.

**Comment by jsternberg** [comment]
@dandv can you make a new issue with a write up of what you mean? I'm not familiar with the specifics of how LetsEncrypt works, but I'm certainly interested in learning and ensuring that that workflow works seamlessly. If you can make an issue with how LetsEncrypt works and what currently doesn't work, we can investigate it.

**Comment by dandv** [comment]
Thanks @jsternberg! I've created #7283.

Also, I noticed that the private key option is present only under `[http]`, but not under `[admin]` in the [sample config](https://github.com/influxdata/influxdb/blob/master/etc/config.sample.toml#L172). Does it actually work for both?

**Comment by jsternberg** [comment]
I don't think so. It's likely worth making a feature request if you want to do the same thing under `[admin]` too.

**Comment by dandv** [comment]
I've just filed #7284. I'd like to use the same two `.pem` files for both HTTP connections and the Admin interface. Does this make sense? (I'm very new to InfluxDB.)

**Comment by jsternberg** [comment]
Yep. It makes sense. We'll talk about it more in the issue you filed.

**Comment by qgicup** [comment]
any news on this?
