### ISSUE TITLE
InfluxDB v1.7: Incorrect error message when time outside range

### ISSUE THREAD

**Issue by chaosbox** [influxdata/influxdb#13118]
System Info:
InfluxDB version: 1.7.4

Downgrading the precision on the influxdb-client from Milliseconds to Seconds, the writes to influx failed with an HTTP 400 Bad request.

`timestamp: 1554195335057 --> time outside range -9223372036854775806 - 9223372036854775806`

the error message was defaulting to the nano time range and doesn't consider the precision multiplier.

**Comment by domenicquirl** [comment]
Having just run into this, the error message is extremely confusing, as it is just plain wrong and gives no indication of the actual issue. Since https://github.com/influxdata/influxdb/pull/13120 already exists to improve the situation here, maybe this could be considered again.
