### ISSUE TITLE
Can not drop measurement with 1.7.0

### ISSUE THREAD

**Issue by zhouyuanchao** [influxdata/influxdb#13144]
Case 1:
I execute "drop measurement" and quickly return, but I execute "show measurements" after several hours, the measurement is also exist.
![image](https://user-images.githubusercontent.com/38806828/55538361-d9ef7700-56f0-11e9-84cd-9cd46628765d.png)

Case 2:
In the other node, I execute "drop measurement" but has no response in several hours.

**Comment by foobar** [comment]
still seeing this issue with 1.7.10
