### ISSUE TITLE
InfluxDB 2.0: Create forever Bucket through GUI raise error on period 0sec

### ISSUE THREAD

**Issue by laurelgr** [influxdata/influxdb#13149]
### Version used
InfluxDB 2.0.0-alpha.6

### Steps to reproduce
In GUI,
- go to **Configuration --> Buckets**
- click on "**Create Bucket**", default retention policy is forever (clear --> **Never**)
- select clear "**Periodically**"
- select back "**Never**"
- name and create the bucket
==> failed to create bucket

#### Additional notes

Same error of course also appends if creating bucket through first selecting an organization.

Error remains if value of retention changed before selecting back **Never** (and is reset to zero if selecting **Periodically** again).

Must close the dialog box to clear the error and be able to create a neverending bucket.

### Error raised
(from network monitor)

**422 - Unprocessable entity
"expiration seconds must be greater than or equal to one second"**

**Comment by russorat** [comment]
@laurelgr i believe this was fixed in https://github.com/influxdata/influxdb/issues/12688 and should be in the latest alpha 7 release.

**Comment by laurelgr** [comment]
@russorat Damn, and I spent so much time checking that the issue was not yet reported. Thanks
