### ISSUE TITLE
Backup influxdb 0.10.0 and restore in version 1.7.4

### ISSUE THREAD

**Issue by PhuTaliban** [influxdata/influxdb#13143]
Hi everyone, i'm trying to upgrade directly influxdb from version 0.10.0 to newest version 1.7.4, but it failed because the command "show measurements" doesn't show anything. When restore service run, it doesn't display text chain "unpacking /var/lib/influxdb/data....". Instead of, it's only show "Restoring from backup.....", but in influxdb's data directory, it still have data with full of retention and shardId, the data too. I was run the command chown -R influxdb:influxdb but it can't help anything except fix the error cannot start influxdb service. Can anyone help me? Thanks a lot :smile:

**Comment by dgnorton** [comment]
@PhuTaliban `1.7.x` isn't backward compatible with pre-`1.0` versions. You may be able to use `influx_inspect` to export the data to line protocol (text) and then write that into `1.7.4`. May require some massaging of the exported line protocol.
