### ISSUE TITLE
InfluxDB 2.0: Support for OAuth authentication

### ISSUE THREAD

**Issue by pmazon** [influxdata/influxdb#13188]
Chronograf supports OAuth for authenticating users: cf [this link](https://docs.influxdata.com/chronograf/v1.7/administration/managing-security/#oauth-2-0-providers-with-jwt-tokens).

I don't see such support planned in [alpha/beta](https://github.com/influxdata/influxdb#what-you-can-expect-alpha-and-beta-phases).
It would be great if were supported in InfluxDB v2, too.

[Related Influxdata Community post](https://community.influxdata.com/t/oauth-authentication-authorization/9267).

**Comment by jspc** [comment]
Hello Influxdata, is there any update/ anywhere that may hold update on whether this feature is likely to be picked up/ is a feature which could be picked up?

**Comment by sinisterrook** [comment]
Also looking for this feature as well.

**Comment by mwmahlberg** [comment]
I'd like to add that especially when one scales out, managing users locally seems a bit off.

**Comment by wsgomes** [comment]
Hi InfluxData, OAuth authentication is a requirement for us. We use Keycloak to manage our users and permissions. Is there any plan to implement this on InfluxDB 2.0? Thanks in advance!

**Comment by Viajaz** [comment]
@russorat Is this issue actually dead? Are more authentication options on the InfluxDB 2 roadmap?

**Comment by synchris** [comment]
Chronograf supports OAuth already and not InfluxDB v2.

**Comment by wsgomes** [comment]
@synchris yeah... we have Chronograf as part of our InfluxDB v1 solution... however, in order to upgrade to InfluxDB v2, we need OAuth available in v2.

**Comment by wsgomes** [comment]
@russorat I think issue is relevant and should be reopened

**Comment by russorat** [comment]
@dgnorton

**Comment by sinisterrook** [comment]
I second this request to reopen.

**Comment by chickenkiller** [comment]
+1 to reopen the request please

**Comment by Jaimenms** [comment]
+1

**Comment by mabnz** [comment]
+1

**Comment by afausti** [comment]
Is this in the InfluxDB 2 roadmap? It would help us to migrate from Chronograf to the InfluxDB 2 UI and use some of the new UI features - thanks.

**Comment by Fran-78** [comment]
any update on this SSO issue?

**Comment by GeorgeJose7** [comment]
+1

**Comment by schwankner** [comment]
+1

**Comment by grafael** [comment]
+1

**Comment by maximdogonov** [comment]
+1

**Comment by benidi** [comment]
+1

**Comment by kristiandrucker** [comment]
+1

**Comment by andrejvanderzee** [comment]
+1

**Comment by janschiiii** [comment]
+1

**Comment by NoneTirex** [comment]
I'll be glad if this is added to influx v2, until then, I'll check how influx flux dsl support works in Grafana

**Comment by madansu** [comment]
This feature is super important to us, and is holding us back on v1, using Chronograf, rather than migrating to v2

Please consider adding OAUTH support to the roadmap

**Comment by smartshader** [comment]
+1

**Comment by pts211** [comment]
+1

**Comment by pwilimzig** [comment]
+1

**Comment by XtremeOwnageDotCom** [comment]
Yup. Needs OIDC, OAUTH, SAML... Something.

**Comment by seanhold3n** [comment]
Adding to the +1 train

**Comment by ivolucas** [comment]
+1

**Comment by jkoops** [comment]
+1

**Comment by mogaleaf** [comment]
+1

**Comment by peterchen25** [comment]
+1

**Comment by paulwer** [comment]
+1

**Comment by SK-StYleZ** [comment]
bump

**Comment by inaneverb** [comment]
+1

**Comment by Hadatko** [comment]
+1

**Comment by cbto** [comment]
+1

**Comment by Hadatko** [comment]
+1

**Comment by Davidbon1** [comment]
+1

**Comment by nubam** [comment]
+1

**Comment by Mirokko** [comment]
+1

**Comment by davama** [comment]
+1

**Comment by septatrix** [comment]
Please do not follow the path of other projects by adding the [single-sign-on tax](https://goauthentik.io/blog/2023-10-18-taxed-out-of-security) and only making this available in the enterprise version once this feature gets implemented

**Comment by Saske912** [comment]
Please add this feature.

**Comment by davidcawork** [comment]
+1

**Comment by j-brewer** [comment]
+1

**Comment by gtato** [comment]
+1

**Comment by CrazyWolf13** [comment]
+1

**Comment by Dominik-esb** [comment]
+1

**Comment by ahein88** [comment]
+1

**Comment by septatrix** [comment]
Please, stop spamming this issue with "+1"! Instead use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.

Writing "+1" just annoys and unnecessarily pings everyone who is subscribed to this issue. Also when looking for desired features the team is more likely to sort by reactions instead of looking into each comment. If you want to get notified upon further changes you can also click the "Subscribe" button in the side panel (or at the very bottom on mobile devices I think). Whenever I see the title of this issue in my mails I get hopeful that someone actually wrote something meaningful or that there is an update from the team but instead I always get annoyed that some people still not grasp the concept of upvoting instead of spamming. Spamming just annoys everyone and makes the maintainers less willing to help. If this is not getting better I would even suggest to the maintainers to lock this issue...

**Comment by Mirokko** [comment]
Bot added "wontfix" label, so... Yeah!

**Comment by archef2000** [comment]
That was just the stale bot

**Comment by Hadatko** [comment]
I love these bots on github. When maintainers don't reply bots are doing decission. Which is great for example when you report bug (not this case) :DDD

**Comment by wsgomes** [comment]
@septatrix When people make use of the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that they are interested into the feature, does it avoid stale bot to act?... or is it required to make a comment?

**Comment by divStar** [comment]
Oh well, I guess it won't be implemented. Apparently the clustered v3 has something: https://docs.influxdata.com/influxdb3/clustered/install/secure-cluster/auth/ . Taking whatever I can get I guess so thanks for that. But this DB is an absolute no-go for anything enterprise-y without the ability to actually manage the users externally.

By the way: if you're on a similar setup like I am (Docker + Traefik + Zitadel/OIDC provider), you might get away with [`traefik-oidc-auth` plugin](https://traefik-oidc-auth.sevensolutions.cc/docs/getting-started), which I am using with PiHole and e.g. the Traefik Dashboard (both services don't have a nice authentication system, even though PiHole at least has some sort of password protection).
