### ISSUE TITLE
High disk latency every hours 

### ISSUE THREAD

**Issue by AndreyNovik1993** [influxdata/influxdb#13192]
Hi, All. I have problem with high latency every hour. Every hour latency increase with 5 to 25 ms. 
Disk space's on that period (10 minutes) decrease 15Gb. All free memory become cache, and increase load average VM. I'm having remote storage (HP 3par, with SAS disk). Influxdb is writing  1M  point/min.  

![image](https://user-images.githubusercontent.com/43274094/55628574-be9c6e80-57b9-11e9-8330-12840a6968a2.png)
![image](https://user-images.githubusercontent.com/43274094/55628595-cd832100-57b9-11e9-8541-7b086a519a0c.png)
![image](https://user-images.githubusercontent.com/43274094/55628613-daa01000-57b9-11e9-941c-2ec925a7282d.png)

Who saw that problem ? please tell how it's tackle.

**Comment by dgnorton** [comment]
@AndreyNovik1993 what version is this on?
