### ISSUE TITLE
LAST nor returning LAST, using GROUP BY

### ISSUE THREAD

**Issue by laimaretto** [influxdata/influxdb#13257]
I have the following query:

    SELECT LAST("number") FROM "stats" WHERE "router" = "R1" AND "alarm" = "LinkDown" AND time >= now() - 7d GROUP BY "alarm", "object", "router", "severity"

And I'm getting two records, even though I was expecting only one (hence the LAST) ...

```
time                | Object | alarm    | router | severity | number
2019-04-07 19:05:10 | port A | LinkDown | R1     | deleted  | 2
2019-04-07 18:59:37 | port A | LinkDown | R1     | set      | 2
```
I was hoping to get the last one (`2019-04-07 19:05:10`) but I'm getting the last two ... 

Why is that? What is it that I'm not understanding?

Thanks!

**Comment by dgnorton** [comment]
@laimaretto try removing the `GROUP BY`.
