### ISSUE TITLE
too many TCP close_wait cause Influxdb crash

### ISSUE THREAD

**Issue by HeathKang** [influxdata/influxdb#13252]
Hi，
I use `Influxdb 1.5.2`. 
Influxdb crashed recently and  log showed``` too many open files```. I found there was more than 65000 `TCP CLOSE_WAIT` state connected to Influxdb host by command ```netstat -nap ``` and I thought this is the reason why influxdb crashed.
So I was wondering what could cause so many `TCP CLOSE_WAIT` and why Influxdb didn't close those `CLOSE_WAIT` tcp connections.

**Comment by HeathKang** [comment]
I think maybe I found the reason. 
- 1 Some of my apps execute ```select * from mydatabase limit 1```, and this query can 
easily trigger slow query.   
- 2 My agent influxdb query timeout is `10s`, but Influxdb query timeout is `15s`. So when some slow query  happened, my client cut the tcp connection and rebuild new connection try to query more times. But influxdb still excute the last query, so influxdb didn't close last TCP connection and the last connection run into `CLOSE_WAIT` state.So the `CLOSE_WAIT` state tcp connections increase very fast since I have more than 100 agents and every agent try build tcp connection 10 times when slow query happened. And too many `CLOSE_WAIT` tcp state trigger influxdb run out of open file handles.

So, here are my ways to solve these problems.
- 1 optimize the slow query
- 2 reset influxdb query timeout less than agent query timeout, so the influxdb can kill slow query and prevent tcp connection run into `CLOSE_WAIT` state

**Comment by elhenro** [comment]
i also had the 'too many open files' error while trying to write to influxdb. i happened after a `SELECT *` statement didn't return. restarting influxd fixed the problem for me, for now

**Comment by iver3on** [comment]
should we close the connections ? close()

**Comment by HeathKang** [comment]
> should we close the connections ? close()

The point is client close the connection and Influxdb didn't response for that cause the too many `CLOSE_WAIT` state tcp connections. So the way to solve this is set influxdb query timeout less than your client query timeout.
