### ISSUE TITLE
Variable name should be unique

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/influxdb#13297]
Variables can be created with the same name using the create overlay or when importing.

- [x] Verify variable name is unique in Variable Overlay
> -  Import variable name should error if name already exists

This could be enforced in api side. However, we don't currently do this for labels, which also requires name uniqueness in the ui.

**Comment by AlirieGray** [comment]
variable names should only be unique within the org, right? as in, you could have a variable with the same name as a variable in another org?

**Comment by OfTheDelmer** [comment]
@AlirieGray  Yeah we should we have uniqueness per org.

**Comment by OfTheDelmer** [comment]
Separating out the issue of importing. Needs discussion for resource reconciliation.

**Comment by ebb-tide** [comment]
yes @AlirieGray and the UI should never be "seeing" the variables in another org.
