### ISSUE TITLE
collectd: "Failed to write point batch to database"  -  Timesync issue?

### ISSUE THREAD

**Issue by ercpe** [influxdata/influxdb#13313]
For a few days, this problem has been bugging me: I have a collectd database in InfluxDB v1.7.5 (git: 1.7 2f49e00f7f3801a506304c3b6d8165b2f4039f3d)
 which runs in a docker container.

At some point the collectd database stops working and logs 

`2019-04-11T01:28:19.273457Z	info	Failed to write point batch to database	{"log_id": "0EiwPTel000", "service": "collectd", "db_instance": "collectd", "error": "timeout"}`

over and over until the influxdb container is restarted.

After some digging, I found that at the same time a docker container on the same host was started and systemd thought it would be a great idea to synchronize the clock:

    Apr 11 01:28:08 sb33 kernel: [3439057.844715] docker0: port 19(veth616a4c9) entered blocking state
    Apr 11 01:28:08 sb33 kernel: [3439057.844719] docker0: port 19(veth616a4c9) entered disabled state
    Apr 11 01:28:08 sb33 kernel: [3439057.844840] device veth616a4c9 entered promiscuous mode
    Apr 11 01:28:08 sb33 kernel: [3439057.844997] IPv6: ADDRCONF(NETDEV_UP): veth616a4c9: link is not ready
    Apr 11 01:28:08 sb33 kernel: [3439057.845005] docker0: port 19(veth616a4c9) entered blocking state
    Apr 11 01:28:08 sb33 kernel: [3439057.845008] docker0: port 19(veth616a4c9) entered forwarding state
    Apr 11 01:28:08 sb33 systemd-timesyncd[7824]: Network configuration changed, trying to establish connection.
    Apr 11 01:28:08 sb33 networkd-dispatcher[1301]: WARNING:Unknown index 356 seen, reloading interface list
    Apr 11 01:28:08 sb33 systemd-timesyncd[7824]: Synchronized to time server [2a01:4f8:0:a0a1::2:1]:123 (ntp1.hetzner.de).
    Apr 11 01:28:08 sb33 kernel: [3439057.849583] docker0: port 19(veth616a4c9) entered disabled state
    Apr 11 01:28:08 sb33 systemd-timesyncd[7824]: Network configuration changed, trying to establish connection.
    Apr 11 01:28:08 sb33 systemd-timesyncd[7824]: Synchronized to time server [2a01:4f8:0:a0a1::2:1]:123 (ntp1.hetzner.de).
    Apr 11 01:28:09 sb33 dockerd[1596]: time="2019-04-11T01:28:09Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/adad969f2c6ce7fb6f29bd5401add53f19fb11b2a2899361e5f477da2f9135fe/shim.sock" debug=false pid=14239
    Apr 11 01:28:09 sb33 systemd-timesyncd[7824]: Network configuration changed, trying to establish connection.
    Apr 11 01:28:09 sb33 systemd-timesyncd[7824]: Synchronized to time server [2a01:4f8:0:a0a1::2:1]:123 (ntp1.hetzner.de).
    Apr 11 01:28:09 sb33 kernel: [3439058.798370] eth0: renamed from vethae3e135
    Apr 11 01:28:09 sb33 kernel: [3439058.844826] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
    Apr 11 01:28:09 sb33 systemd-networkd[7758]: veth616a4c9: Gained carrier
    Apr 11 01:28:09 sb33 systemd-timesyncd[7824]: Network configuration changed, trying to establish connection.
    Apr 11 01:28:09 sb33 systemd-networkd[7758]: veth616a4c9: Gained IPv6LL
    Apr 11 01:28:09 sb33 kernel: [3439058.847121] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
    Apr 11 01:28:09 sb33 kernel: [3439058.847128] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
    Apr 11 01:28:09 sb33 kernel: [3439058.847144] IPv6: ADDRCONF(NETDEV_CHANGE): veth616a4c9: link becomes ready
    Apr 11 01:28:09 sb33 kernel: [3439058.847174] docker0: port 19(veth616a4c9) entered blocking state
    Apr 11 01:28:09 sb33 kernel: [3439058.847176] docker0: port 19(veth616a4c9) entered forwarding state
    Apr 11 01:28:09 sb33 systemd-timesyncd[7824]: Synchronized to time server [2a01:4f8:0:a0a1::2:1]:123 (ntp1.hetzner.de).

After that, the influxdb collectd database stopped working.

I can reproduce the issue sometimes by starting a container and thus causing the network change. I suspect that systemd-timesyncd changes the clock enough to break influxdb.

Related issue: https://github.com/systemd/systemd/issues/8603 Unfortunately, Ubuntu 18.04 (the hosts OS) doesn't have systemd 239.

**Comment by jeroenhendricksen** [comment]
It seems we might be running into a similar issue as the one you are describing. I see no `systemd-timesyncd` service at my machine, but I do see a `ntpd` daemon and maybe is causing a similar situation. I'll report back if I spot a possible relation.

**Comment by ercpe** [comment]
After upgrading the server to Ubuntu 18.10 the problem is still there and I can still correlate the issue to the start of other docker containers. However, with 18.10, systemd 239 does no longer start a full time sync after a network change.

I tried to force the issue by

- stopping systemd-timesyncd
- set the system time back using `date --set`
- start systemd-timesyncd

without success.
My best guess here is that, if it is indeed related to time change, a write call must happen at the same time on the `collectd` connector. Another database in the same influxdb instance (written to only via http api) is not affected by this issue.

**Comment by TheMoves** [comment]
Also getting same error with collectd stats, only the issue resolves itself after like a day if left untouched, otherwise I have to restart the DB to resolve it.

**Comment by TheMoves** [comment]
I downgraded to 1.7.4 and have not seen the issue.

**Comment by ruslanV1** [comment]
> I downgraded to 1.7.4 and have not seen the issue.

Thanks!
I had a similar problem at 1.7.5:
`ts=2019-04-24T06:37:59.282603Z lvl=info msg=\"Failed to write point batch to database\" log_id=0E~WdfaW000 service=collectd db_instance=collectd error=timeout`
After downgrading to 1.7.4 the problem disappeared.

**Comment by sysadmin1139** [comment]
We had the same occurrence while using the graphite endpoint with collectd on 1.7.5. A large percentage of our system metrics come in that way, so it was a major issue. Had to downgrade to 1.7.4, which worked. This was an upgrade from 1.5.2.

Of interest, whatever happened also slowed queries to those database to the point our dashboarding systems couldn't even display historic information. The downgrade to 1.7.4 fixed it.
