### ISSUE TITLE
Backup Issue 

### ISSUE THREAD

**Issue by noqqe** [influxdata/influxdb#13316]
Hi,

I'm trying to do a backup of my instance:

```
$ influxd backup -database sensors -host localhost:8088 /backups/influxdb/
2019/04/11 08:24:24 backing up db=sensors since 0001-01-01 00:00:00 +0000 UTC
2019/04/11 08:24:24 backup failed: EOF
backup: EOF
```

Getting the following error in the log file:

```
ts=2019-04-11T06:24:24.041828Z lvl=info msg="read request: json: cannot unmarshal string into Go value of type snapshotter.Request" log_id=0EjlcN5l000 service=snapshot
```

Versions are the following, running on NixOS

```
$ influx
Connected to http://localhost:8086 version 1.6.3
InfluxDB shell version: 1.4.1
```

What can I do?

**Comment by noqqe** [comment]
influxd and influxdb service were not using the same version.

I was upgrading the service and fixed it :)

**Comment by Emrica** [comment]
influxd and influxdb service using the same version? Good.
But if you set a wrong database name `influxd backup -database wrong_db_name ...args`, the error `backup: EOF` happens.
