### ISSUE TITLE
Refactor APIHandler to use router instead of a bunch of conditionals

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#13320]
Currently the `http.APIHandler` does route checking with conditionals that do prefix matching on the route

https://github.com/influxdata/influxdb/blob/f56c42794b7bf6c51052b86d30a8daa8826fae9f/http/api_handler.go#L209-L222

This pattern forces http handlers to push all routes that start with a common prefix to be defined together like so
https://github.com/influxdata/influxdb/blob/f56c42794b7bf6c51052b86d30a8daa8826fae9f/http/bucket_service.go#L61-L69
https://github.com/influxdata/influxdb/blob/f56c42794b7bf6c51052b86d30a8daa8826fae9f/http/bucket_service.go#L86-L122

Ideally we'd be able to separate out the endpoints that handle buckets directly with the endpoints that deal with labels/members/etc. This way we could separate out the concerns of each handler.

I propose that we require that http handlers expose the HTTP verbs and routes that they expose. This way we can do something like

```go
// NewAPIHandler constructs all api handlers beneath it and returns an APIHandler
func NewAPIHandler(b *APIBackend) *APIHandler {
	h := &APIHandler{router: httprouter.New()}
        ...
	bucketBackend := NewBucketBackend(b)
	bucketBackend.BucketService = authorizer.NewBucketService(b.BucketService)
	h.BucketHandler = NewBucketHandler(bucketBackend)
        h.Register(h.BucketHandler.Routes())
        ...
        h.Register(h.BucketLabelsHandler.Routes())
        ...
}
```

This way all of the routes for the buckets will point to the bucket handler and all the bucket label routes will point to the bucket label handler.

Additionally, since we added a router to the api handler we'll no longer need to implement `ServeHTTP`.

**Comment by jademcgough** [comment]
Reopening. I like this idea a lot, and it won't take significant effort to implement.
