### ISSUE TITLE
Can't execute any requests to db

### ISSUE THREAD

**Issue by crazyhare86** [influxdata/influxdb#13336]
InfluxDB shell version: 1.6.0
I have 10 databases , all working fine execept one DB, when i try:

use pft_pnl
show measurements
or
drop database pft_pnl 

I see no errors or results - just empty console in waiting process
DB size in data folder ~1GB
Other DB have size more then 300GB and all working fast

and i can't make http request to this db , i see - timeout error (only for this DB)

1. How can i fix this?
2. How can i delete this db by hand (from data and meta)?

Maybe problem in idx or tsm files?

**Comment by timhallinflux** [comment]
if you run a `show databases` command does pft_pnl show up?

you can use the `influx_inspect` tool to inspect the shards containing your data
https://docs.influxdata.com/influxdb/v1.6/tools/influx_inspect/#sidebar
