### ISSUE TITLE
add type to template meta 

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/influxdb#13333]
UI needs the ability to filter document templates on type. For example, UI might want to show a dropdown of just the `task` templates that an org has created. Currently, we'd need to get all template summaries and then fetch each template to select those with `template.content.data.type` of `task`.

----

Adding `type` to meta in document template. This would help distinguish what kind of template we are working with in the UI.

**Comment by ebb-tide** [comment]
should be a string type.
