### ISSUE TITLE
Time range dropdown selected dot overlaps with text

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#13341]
![Screen Shot 2019-04-11 at 1 44 19 PM](https://user-images.githubusercontent.com/5751863/55991876-0d398500-5c60-11e9-9386-c8bbf07fdb52.png)

**Comment by alexpaxton** [comment]
This happens when a dropdown's mode prop is set to `ActionList` and a `selectedID` is also passed in

I think we can alter the styles to adapt but it's indicative of a larger issue which I think will be addressed in a clockface update
