### ISSUE TITLE
Strange behavior when clicking on switch orgs menu

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13348]
When clicking Switch Orgs, sometimes the menu disappears.

The desired behavior is:
 - the menu should not disappear when clicking switch orgs
 - the menu should not remain with the list of orgs after it is closed.

![Kapture 2019-04-12 at 1 44 25](https://user-images.githubusercontent.com/4805997/56014834-b35eac80-5cab-11e9-95b6-fb5b227aa2d6.gif)

**Comment by OfTheDelmer** [comment]
@russorat I've also observed clicking switch orgs sometimes causes the menu to close. In the above it looks like that eventually happened too after enough clicks.
