### ISSUE TITLE
Repositories are not up-to-date

### ISSUE THREAD

**Issue by dhoppe** [influxdata/influxdb#13350]
The InfluxDB packages at the following mirrors are not up-to-date:
* https://repos.influxdata.com/debian
* https://repos.influxdata.com/ubuntu
* https://repos.influxdata.com/rhel
* https://repos.influxdata.com/centos

There is only version 1.7.4 offered, while the download server already contains version 1.7.5.

**Comment by timhallinflux** [comment]
1.7.5 has an issue #13010  which we are working to resolve.  We won't likely publish to those repos until 1.7.6 is available.

**Comment by dhoppe** [comment]
Why is this version still available on the website?

**Comment by timhallinflux** [comment]
The issue only impacts folks using `inmem`.  We have documented that https://docs.influxdata.com/influxdb/v1.7/about_the_project/releasenotes-changelog/

**Comment by Apollon77** [comment]
I'm now at 1.7.6 and have the feelip it uses much more memory ... I wanted to go back to 1.7.4 ... but it is not available in the repo... any chance to get the deb file?
