### ISSUE TITLE
How to fetch folder details?

### ISSUE THREAD

**Issue by Siddhu1096** [influxdata/influxdb#13352]
Hi Team,

I am using Grafana as InfluxDB as the data source and I use telegraf to fetch the data. My requirement is to fetch the folder details which resides in a specific location say, /var/lib/details. I need to show the folders inside this location in Grafana. What should I do? Thanks in advance.

Best,
Siddharth

**Comment by timhallinflux** [comment]
Issue moved to [influxdata/telegraf #5722](https://github.com/influxdata/telegraf/issues/5722) via [**ZenHub**](https://www.zenhub.com/)

**Comment by timhallinflux** [comment]
This is a question specifically about how to configure Telegraf to gather information from the filesystem.
