### ISSUE TITLE
Wrong dates in Github releases changelogs

### ISSUE THREAD

**Issue by tinuzz** [influxdata/influxdb#13398]
Hi,

I wasn't sure how else to report this, but I just wanted to note that @russorat has been tagging the v2.0.0-alpha releases on Github with dates in 2018, what surely must have been 2019 for each of them:

- v2.0.0-alpha.8 [**2018**-04-12]
- v2.0.0-alpha.7 [**2018**-03-28]
etc.

Best regards,
Martijn.

**Comment by russorat** [comment]
🤦‍♂️ thanks!

**Comment by russorat** [comment]
fixed!
