### ISSUE TITLE
Health/Metrics/Debug endpoints  publicly available without auth

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#13413]
Currently all

https://github.com/influxdata/influxdb/blob/401ec79bffc5f3ab44c12b702e50678faf741351/http/handler.go#L20-L29

are exposed publicly and do not require auth. This is likely to expose some amount of private data.

We should either

1. Add an option to ensure that those endpoints are unexposed
2. Require authentication to access those endpoints

**Comment by lafrech** [comment]
I just stumbled upon this. I wanted to report it and found this issue already open.

I can confirm, except for `debug`, which returns a 404 error.

**Comment by DSpeichert** [comment]
I was just looking through the issues before reporting this as well.
It makes it even "hard" to test out the beta, considering how InfluxDB kinda has to be exposed for Telegraf to reach it, at the same time InfluxDB should be able to scrape itself.

How about adding some sort of ACL for `/metrics`?
The `/ready` and `/health` routes are useful for k8s, obviously, and do not seem to be leaking sensitive information.
Having `/metrics` locked down to access from 127.0.0.1 would be a good sane default setting.

**Comment by russorat** [comment]
connect https://github.com/influxdata/influxdb/issues/20764

**Comment by danxmoran** [comment]
Closing this since we've split the work into multiple issues:
* #20764 for pprof
* #20755 for metrics
