### ISSUE TITLE
cluster concept in influx

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/influxdb#13435]
HI,

I am using open source monitoring tool, where telegraf is collecting the OS information, influx is the database which is connected through grafana( for display)

Now in my environment we have four separate influx instance.
Is clustering possible in open source, that four node gives data to one influx?
or any other way to take data from four data source and point to one?

Regards,
Priyanka

**Comment by sanderson** [comment]
@priyankamondalairtel InfluxDB OSS doesn't support clustering (multiple instances working together as one) but [InfluxEnterprise](https://www.influxdata.com/influxenterprise/) does. You could use [Kapacitor](https://www.influxdata.com/time-series-platform/kapacitor/) to pull data from the 4 InfluxDB instances and write the data to a single InfluxDB instance, but this isn't a HA cluster setup. The single InfluxDB instance receiving data from the other 4 would represent a single point of failure and you wouldn't have the benefits of failover and redundancy that a true cluster setup would provide.
