### ISSUE TITLE
Add the ability for an admin user to change the org name

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13447]
as an admin
with admin
when i view the settings for an organization
then i have the ability to change the organization name

Org names are unique so if the user tries to rename to an org that already exists, we need a nice error message.

we should populate a warning saying that changing the name of the org may impact any Flux scripts or Telegraf configurations where the org name is being used.

**Comment by ischolten** [comment]
something like below from github

![image (1)](https://user-images.githubusercontent.com/5751863/56247050-75210e80-6058-11e9-9fc9-619850387cba.png)
