### ISSUE TITLE
Influxdb error near unexpected token `(' on version version: 1.4.2 on Ubuntu 14.04

### ISSUE THREAD

**Issue by adeel26** [influxdata/influxdb#13455]
I am getting this error when I input now() in my influx query.

influx --username **** -password *** -precision rfc3339  -database '***' -host 'localhost' -execute 'select * from ar' where time>now()-5m  -format 'csv'> data.csv

I always get following error 

bash: syntax error near unexpected token `('

**Comment by dgnorton** [comment]
There is a single quote after `ar`
