### ISSUE TITLE
Inner joins not work as expacted 

### ISSUE THREAD

**Issue by sharathmankala** [influxdata/influxdb#13498]
Hi Team,
I have followed document and try to use inner joins in influxdb. getting below error.
Kindly guide me.

SELECT jen.project_name FROM "jenkins_data" jen INNER JOIN "changelog_data" cha; 
ERR: error parsing query: found jen, expected ; at line 1, char 45

**Comment by timhallinflux** [comment]
INNER JOIN is not currently supported within InfluxQL.  

There was some preliminary INNER JOIN support prior to the 1.0 release of InfluxDB, but it was removed.

**Comment by sharathmankala** [comment]
Thanks for update.
Any alternative for joins in influxdb.
Thanks in Advance,
Sharath Mankala.

**Comment by timhallinflux** [comment]
We are introducing a new query language, called Flux.  It is in technical preview with 1.7.x.
See more here: https://www.influxdata.com/blog/influxdb-how-to-do-joins-math-across-measurements/

**Comment by pauloangelo** [comment]
:O!  It is not possible to join measurements?!

**Comment by timhallinflux** [comment]
Joins are not supported via InfluxQL.  You'll need to use Flux for that capability. Flux is currently available as a technical preview language with the 1.7.x release.  We will declare it `production ready` as a part of our 1.8 release.  Flux is also available with InfluxDB 2.0 editions; OSS and Cloud.  

More details about the language here:  
InfluxDB v1.7.x current -> https://docs.influxdata.com/flux/v0.50/guides/join/
InfluxDB v2.0 current -> https://v2.docs.influxdata.com/v2.0/query-data/guides/join/
