### ISSUE TITLE
Task Runs on Cloud2 comes back with incorrect finishedAt date

### ISSUE THREAD

**Issue by Palakp41** [influxdata/influxdb#13511]
We are using task runs finishedAt and startedAt date to calculate the duration for the run.
Duration = finishedAt - startedAt
The finishedAt date is correct on local machine but on Cloud2, the finishedAt date sometimes comes as `1970-01-01T00:00:00Z` which causes the duration to go into negative seconds. Sometimes the date is correct on Cloud2 for some runs. See the screenshot below:

<img width="415" alt="Screen Shot 2019-04-18 at 1 02 02 PM" src="https://user-images.githubusercontent.com/26464594/56387883-62cede00-61da-11e9-9f07-20b9bb144717.png">

**Comment by goller** [comment]
Hey @Palakp41, @lyondhill, @docmerlin,  and @AlirieGray have a fix in this pull request:

https://github.com/influxdata/influxdb/pull/13641
