### ISSUE TITLE
Telegraf does not seem to buffer data when telegraf token is disabled in UI

### ISSUE THREAD

**Issue by bpalani** [influxdata/influxdb#13515]
_Description_
When a user disables the telegraf token in UI under Settings->Tokens, the telegraf writes error out with `Failed to write metric: forbidden: insufficient permissions for write` which is expected, however the data does not seem to be buffered on telegraf side and there seems to be a data loss during that time period.
_Expected behavior_
When writes are rejected for whatever reason by the gateway, Telegraf should buffer the data (unless the local buffer becomes full) to be retried when the gateway starts accepting writes again.
_Steps to reproduce_
1. Log in to ui and set up a Telegraf config with write permissions to a bucket. I used system plugin, but should not matter which plugin you select.
2. Start Telegraf with the config you just created (make sure you use the token created in step 1).
3. Make sure data is getting collected in the bucket by going to Data Explorer in the UI
3. In the UI go to Settings->Tokens and disable the token created in Step 1 as part of the Telegraf config
4. If you go to the Telegraf console, you should see error `Failed to write metric: forbidden: insufficient permissions for write` as in the attached image: 
![image](https://user-images.githubusercontent.com/10112209/56412229-4d889c80-6238-11e9-9a14-13362bddb676.png)
5. Wait for 5 or 10 mins and re-enable the disabled Token.
6. Go back to Data Explorer and you should see a gap for the time the token was disabled which I assume means that data got dropped by Telegraf and is not buffered to be retried later.
![image](https://user-images.githubusercontent.com/10112209/56412669-c805ec00-6239-11e9-8290-f6cb5b6f2cec.png)
_Environment_
Checked that this is a bug on both OSS and Cloud 2.0

**Comment by russorat** [comment]
if you upgrade your telegraf, this issue will be resolved.
