### ISSUE TITLE
Add danger confirmation warning for deleting a bucket

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#13525]
should have a similar confirmation as renaming a bucket when deleting a bucket.

**Comment by ischolten** [comment]
@alexpaxton @russorat  what should happen after confirming. Should the delete just happen or do they need to do anything extra in a "next step" like with the renaming of buckets and orgs

**Comment by russorat** [comment]
The user should need to type in the name of the organization in order to delete it.
