### ISSUE TITLE
api: executing query with Content-Type: application/vnd.flux does not include "csv headers" in response

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#13537]
```
$ curl -s -v -H 'Authorization: Token 8Q3VLY1jxCfXBKYSOgcTRhxtVhtBm0yEZ1U9mEkxfnLZFH-77zoA3oDSRnVDx53Hm1WP4BX4mbvVWevmJHt9sw==' -H 'Content-Type: application/vnd.flux' -X POST --data-binary @/tmp/buckets.flux 'http://localhost:9999/api/v2/query?orgID=03bd66957dae9000'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9999 (#0)
> POST /api/v2/query?orgID=03bd66957dae9000 HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Token 8Q3VLY1jxCfXBKYSOgcTRhxtVhtBm0yEZ1U9mEkxfnLZFH-77zoA3oDSRnVDx53Hm1WP4BX4mbvVWevmJHt9sw==
> Content-Type: application/vnd.flux
> Content-Length: 10
>
* upload completely sent off: 10 out of 10 bytes
< HTTP/1.1 200 OK
< Content-Type: text/csv; charset=utf-8
< Date: Mon, 22 Apr 2019 15:18:32 GMT
< Transfer-Encoding: chunked
<
,result,table,name,id,organization,organizationID,retentionPolicy,retentionPeriod
,_result,0,a,03bd66957dae9001,a,03bd66957dae9000,,399600000000000

* Connection #0 to host localhost left intact
```

The response does not include the `#group`, `#datatype`, and `#default` like when I execute the equivalent query in Chronograf, which uses a JSON-encoded request payload. As a result, I cannot copy the raw response and use it in a new flux script with `csv.from` -- something I have wanted to do when attempting to file a standalone repro script for a Flux bug.

```
bash-3.2$ cat /tmp/csv-repro.flux
import "csv"

data = ",result,table,name,id,organization,organizationID,retentionPolicy,retentionPeriod
,_result,0,a,03bd66957dae9001,a,03bd66957dae9000,,399600000000000"

csv.from(csv: data)
bash-3.2$ ./flux execute @/tmp/csv-repro.flux
#datatype,string,string
#group,true,true
#default,,
,error,reference
,error in csv.from(): missing expected annotation datatype,
```

**Comment by mark-rushakoff** [comment]
Looking at this a little more closely, I see that the outgoing requests from the browser in Chronograf set annotations in the dialect. But if I'm reading the code right, there's no way to set the annotations when you're using `Content-Type: application/vnd.flux`: https://github.com/influxdata/influxdb/blob/cf8785dc76cf79d2fab8e0f55a5cc4e6e9ea9de1/http/query.go#L313-L347

**Comment by nathanielc** [comment]
I agree, we should make the default when using `application/vnd.flux` include the annotations.

**Comment by mark-rushakoff** [comment]
Keep this open, stalebot!

**Comment by cailloumajor** [comment]
Hello, I would be happy to see this issue go further.

**Comment by OdneOksavik** [comment]
Hi. I would also be happy if annotations were included using vnd.flux. At the moment I understand that there is no way for me to know data types when querying this way?

**Comment by skydiablo** [comment]
I have also encountered the issue of not receiving annotations when using the Query API with a Flux query. When I review my old code, it appears that these annotations were once present. What criteria determine when the API includes these annotations and when it does not?
