### ISSUE TITLE
poor write performance with high measurement cardinality

### ISSUE THREAD

**Issue by cfz** [influxdata/influxdb#13536]
when writing to a newly created database, with a high measurement cardinality, e.g. 100k, data set, the performance is poor.
after some digging, i found that the `MeasurementFieldSet` would synchronously overwrite and fsync the 'fields.idx' file within a mutex with each measurement/field update, which lead to all writing requests to queue up.
one solution is to involve some delay sync techniq like the one used in WAL

**Comment by kumud-pe** [comment]
@cfz Do you think #13319 is related to this?

**Comment by cfz** [comment]
@kumud-pe it happens when you write large amount of new measurements/fields in different requests in a very short period. does it sound familiar with your case?

**Comment by kumud-pe** [comment]
Yes. We were trying to push Kafka metrics through a StatsD server. There will be a bunch of new measurements. But, it's not a delay in our case, the measurements are not being written at all. Now, even if I try to write one new dummy measurement (manually), it's not getting written.

**Comment by cfz** [comment]
i saw a 204 successful response in your log. i'm afraid it's not my case. in my case, the write request will hung for a long time until http timeout or an error.

**Comment by kumud-pe** [comment]
Oh. Ok. This could be a different issue then. Did you check disk I/O stats? That could be becoming a bottleneck.

**Comment by cfz** [comment]
yep, i will submit a PR later for this

**Comment by dgnorton** [comment]
@cfz @kumud-pe what version are you running?

**Comment by kumud-pe** [comment]
@dgnorton Mine is a different issue (I was using 1.7.4 on K8s using tick-charts). I have closed #13319

**Comment by cfz** [comment]
i'm using 1.6.4, but i believe 1.7.x has the same behavior
