### ISSUE TITLE
There can only be one logout button

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#13550]
![Screen Shot 2019-04-22 at 9 59 00 AM](https://user-images.githubusercontent.com/2433762/56512838-65d11380-64e5-11e9-9cd5-950cc4698967.png)

**Comment by 121watts** [comment]
I am not seeing this

![Screen Shot 2019-04-24 at 8 41 27 AM](https://user-images.githubusercontent.com/7582765/56673294-d8b8c680-666c-11e9-8ae2-dc3028e09d84.png)
