### ISSUE TITLE
ui: table view uses wrong heuristics to decide text or number for strings containing hex values

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#13592]
Here is the raw data output of my query:

```
#group,false,false,false
#datatype,string,long,string
#default,_result,,
,result,table,_value
,,0,03435e1933247000
,,0,0380508833448000
,,0,03a26bc365a95000
,,0,03b7192c934fc000
,,0,3171e9b2ec5d12ed
,,0,6d7b04b1f3dc274a
,,0,a17df4ca53167736
,,0,f2dffd780a7bb955
```

As you can see, the `_value` column is all strings. When rendered as a table, the last two entries starting with `a` and `f` are displayed blue and left-justified; the other entries starting with a digit are displayed gray and right-justified.

![Screen Shot 2019-04-23 at 2 56 04 PM](https://user-images.githubusercontent.com/290647/56618717-44048900-65d8-11e9-8115-0ac192cf0b01.png)

The CSS inspector indicates that the first group have CSS class `.table-graph-cell__numerical`.

IMO it would be better to simply inspect the `#datatype` row of the data to see that the column is of type string or long, and use that information to decide CSS classes. If a user has strings that they want rendered as numbers, they should be able to use `toInt`.

**Comment by mark-rushakoff** [comment]
I think this is still an issue.

**Comment by desa** [comment]
@russorat @chnn collaborate on what new table UI will be

**Comment by Asalem1** [comment]
@mark-rushakoff I can't seem to reproduce this. Would you be able to take a look and see if this can be closed out?

**Comment by mark-rushakoff** [comment]
Looks fixed now, thanks for following up.
