### ISSUE TITLE
Guage Graph doesn't scale

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13600]
![Kapture 2019-04-23 at 16 45 41](https://user-images.githubusercontent.com/4805997/56623037-4d492200-65e7-11e9-8b6a-0d3d2be4c9fd.gif)

**Comment by alexpaxton** [comment]
The gauge is rendered via a html canvas which his it's own internal model of size. The canvas needs to be passed pixel values for how big its container is so it can rerender its contents at the correct resolution.

So when a cell is resized or the window is resized (which causes a cell resize), updated container dimensions need to be passed to the gauge canvas
