### ISSUE TITLE
deadlock  in query, irresponsive on 8086

### ISSUE THREAD

**Issue by ThomasKurz** [influxdata/influxdb#13606]
InfluxDB version : 1.7.5 (from official docker image influxdb:1.7.5)

- Neither our application nor the ```influx``` tool can connect/communicate.
- Restart would help
- Moderate/low memory and cpu usage:
![image](https://user-images.githubusercontent.com/89192/56660757-7e395d80-66a0-11e9-86fa-773e1e69a2ed.png)

Environment:
```
    image: influxdb:1.7.5
    mem_limit: 16000m
    environment:
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
      - INFLUXDB_SUBSCRIBER_ENABLED=false
      - INFLUXDB_DATA_WAL_FSYNC_DELAY=10ms
```

In goroutine stackdump ~ 200 x goroutine in ```runtime_SemacquireMutex```:
```
goroutine 20408 [semacquire, 100 minutes]:
sync.runtime_SemacquireMutex(0xc0000e3b34, 0xc03eabb900)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
```
[influx-stack-1556109180.txt](https://github.com/influxdata/influxdb/files/3112279/influx-stack-1556109180.txt)

Last log outputs before becoming irresponsive:
```
ts=2019-04-24T10:52:26.438913Z lvl=info msg="Executing query" log_id=0E~dlJRG000 service=query query="SELECT integral(value, 1h) FROM stadtwerke.autogen.v WHERE time > '2019-03-31 00:00:00' AND time < '2019-04-01 00:00:00' AND plantid = '1531' AND fr_compressed_pac_yield = 'true' GROUP BY *, time(1000d) TZ('Europe/Berlin')"
[httpd] 172.29.0.3 - iplon [24/Apr/2019:10:52:26 +0000] "POST /query?db=stadtwerke&params=null&q=SELECT+integral%28%22value%22%2C1h%29+FROM+%22v%22+WHERE+%22time%22+%3E+%272019-03-31+00%3A00%3A00%27+AND+%22time%22+%3C+%272019-04-01+00%3A00%3A00%27+AND+%22plantid%22+%3D+%271531%27+and+fr_compressed_pac_yield+%3D+%27true%27+GROUP+BY+%2A%2C+time%281000d%29+tz%28%27Europe%2FBerlin%27%29 HTTP/1.1" 200 57 "-" "InfluxDBClient" 0c47325d-667f-11e9-8278-0242ac1d0008 1979
[httpd] 172.29.0.3 - iplon [24/Apr/2019:10:52:26 +0000] "POST /write?consistency=&db=stadtwerke&precision=s&rp=autogen HTTP/1.1" 204 0 "-" "InfluxDBClient" 0c45ab1f-667f-11e9-8277-0242ac1d0008 20429
ts=2019-04-24T10:52:26.449804Z lvl=info msg="Executing query" log_id=0E~dlJRG000 service=query query="SELECT integral(value, 1h) FROM stadtwerke.autogen.v WHERE time > '2019-03-31 00:00:00' AND time < '2019-04-01 00:00:00' AND plantid = '1531' AND fr_compressed_integral = 'true' GROUP BY *, time(1000d) TZ('Europe/Berlin')"
[httpd] 172.29.0.3 - iplon [24/Apr/2019:10:52:26 +0000] "POST /query?db=stadtwerke&params=null&q=SELECT+integral%28%22value%22%2C1h%29+FROM+%22v%22+WHERE+%22time%22+%3E+%272019-03-31+00%3A00%3A00%27+AND+%22time%22+%3C+%272019-04-01+00%3A00%3A00%27+AND+%22plantid%22+%3D+%271531%27+and+fr_compressed_integral+%3D+%27true%27+GROUP+BY+%2A%2C+time%281000d%29+tz%28%27Europe%2FBerlin%27%29 HTTP/1.1" 200 57 "-" "InfluxDBClient" 0c48dff5-667f-11e9-8279-0242ac1d0008 1397
ts=2019-04-24T10:52:26.451280Z lvl=info msg="Executing query" log_id=0E~dlJRG000 service=query query="SELECT mean(value) AS irradiation FROM stadtwerke.autogen.v WHERE plantid = '1531' AND time > '2019-04-01 00:00:00' AND time < '2019-04-02 00:00:00' AND fr_plant = 'SOLAR_RADIATION' GROUP BY fr_orientation, p, bn, ctn, cti, time(1h) TZ('Europe/Berlin')"
ts=2019-04-24T10:52:26.451761Z lvl=info msg="Executing query" log_id=0E~dlJRG000 service=query query="SELECT mean(value) FROM stadtwerke.autogen.v WHERE time > '2019-03-31 00:00:00' AND time < '2019-04-01 00:00:00' AND plantid = '1531' AND fr_compressed_mean = 'true' GROUP BY *, time(1000d) TZ('Europe/Berlin')"
[httpd] 172.29.0.3 - iplon [24/Apr/2019:10:52:26 +0000] "POST /query?db=stadtwerke&params=null&q=SELECT+mean%28%22value%22%29+as+%22irradiation%22+FROM+%22v%22+WHERE+%22plantid%22+%3D+%271531%27+and+%22time%22+%3E+%272019-04-01+00%3A00%3A00%27+AND+%22time%22%3C%272019-04-02+00%3A00%3A00%27+AND+fr_plant+%3D+%27SOLAR_RADIATION%27+GROUP+BY+%22fr_orientation%22%2C+%22p%22%2C%22bn%22%2C%22ctn%22%2C+%22cti%22%2C+time%281h%29+tz%28%27Europe%2FBerlin%27%29 HTTP/1.1" 200 57 "-" "InfluxDBClient" 0c491d3d-667f-11e9-827a-0242ac1d0008 1035
[httpd] 172.29.0.3 - iplon [24/Apr/2019:10:52:26 +0000] "POST /query?db=stadtwerke&params=null&q=SELECT+mean%28%22value%22%29+FROM+%22v%22+WHERE+%22time%22+%3E+%272019-03-31+00%3A00%3A00%27+AND+%22time%22+%3C+%272019-04-01+00%3A00%3A00%27+AND+%22plantid%22+%3D+%271531%27+and+fr_compressed_mean+%3D+%27true%27+GROUP+BY+%2A%2C+time%281000d%29+tz%28%27Europe%2FBerlin%27%29 HTTP/1.1" 200 57 "-" "InfluxDBClient" 0c4930c6-667f-11e9-827b-0242ac1d0008 1103
ts=2019-04-24T10:52:26.458250Z lvl=info msg="Executing query" log_id=0E~dlJRG000 service=query query="SELECT first(value) AS yield FROM stadtwerke.autogen.v WHERE time > '2019-04-02 00:00:00' AND plantid = '1531' AND (fd = 'Yield' OR fr_compressed_difference = 'true') GROUP BY *, time(1000d) LIMIT 1 TZ('Europe/Berlin')"
```

**Comment by timhallinflux** [comment]
1.7.5 had a significant issue with the `inmem` index.  1.7.6 addresses this issue and is available now.
https://docs.influxdata.com/influxdb/v1.7/about_the_project/releasenotes-changelog/

**Comment by ThomasKurz** [comment]
would that issue match despite our configuration with
```
INFLUXDB_DATA_INDEX_VERSION=tsi1
```
and the databases being quite fresh and definitely created with this config ?

**Comment by timhallinflux** [comment]
are you seeing something like this in your logs at startup: 
`ts=2019-04-23T16:24:58.614031Z lvl=info msg="index opened with 8 partitions" log_id=<some ID> index=tsi `

**Comment by stevebang** [comment]
@ThomasKurz I tested using InfluxDB OSS 1.7.6:
1. `export INFLUXDB_DATA_INDEX_VERSION=tsi1` (without quotes)
2. `export INFLUXDB_DATA_INDEX_VERSION="tsi1"` (with quotes)
Both times the results showed up correctly in the console log and using the /debug/vars HTTP endpoint.
Upon startup, both logs showed the same  `index=tsi` that @timhallinflux mentions.

When you try this again, you can look at the logs or try searching for `indexType` using the `/debug/vars` HTTP endpoint:

`http://localhost:8086/debug/vars`

In the results, you should find listings showing the indexType for database shards, displaying similar to this:

```
  "shard:/usr/local/var/influxdb/data/mydb/autogen/357:357": {
    "name": "shard",
    "tags": {
      "database": "mydb",
      "engine": "tsm1",
      "id": "357",
      "indexType": "tsi1",
      "path": "/usr/local/var/influxdb/data/tsi1/autogen/357",
      "retentionPolicy": "autogen",
      "walPath": "/usr/local/var/influxdb/wal/tsi1/autogen/357"
    },
```

**Comment by ThomasKurz** [comment]
I checked in /debug/vars and all "indexType" are "tsi1", while all "engine" are "tsm1".
In the logs i find this:
```
ts=2019-04-25T00:00:00.096829Z lvl=info msg="index opened with 8 partitions" log_id=0E~uKHAl000 index=tsi
```
so I assume that my installation is completely tsi1-based.

**Comment by stevebang** [comment]
If there are no `inmem` shards, the 1.7.5 issue is probably irrelevant. 

A few questions:
1. Is the nonresponsiveness still an issue?
2. You mention that restart helps.  When you restart, is that a manual or auto restart?
3. After a restart, does it work for a while, then become nonresponsive again?
4. Have you tried using 1.7.5 outside of the Docker image?

**Comment by ThomasKurz** [comment]
This happened now 3 or 4 times in the last several weeks, 
but only after we changed from 1.6.x to 1.7.5.
We observed it on multiple different installations.

Regarding your questions:

> 1. Did a previous image work OK? 

We had no such problems with 1.6.x and previous versions for years (using influx since 2014)
>     Was this an upgrade?

No, setup from scratch
> 3. You mention that restart helps.  When you restart, is that a manual or auto restart?

Manual restart, the container didn't crash, only influx became unusable.
> 4. After a restart, does it work for a while, then become nonresponsive again?

As it happens only randomly / sporadically in the course of weeks, I really don't know yet. 
> 5. Have you tried using 1.7.5 outside of the Docker image?

No, usually not.
> 2. Is the nonresponsiveness still an issue?

Today we upgrade one system to 1.7.6, let's see what happens.
We will keep you informed.

**Comment by ThomasKurz** [comment]
only some guesswork:
- [this issue](https://github.com/uber-go/zap/issues/703) in _uber-go/zap_ shows a similar deadlock as you find in my goroutine dump above.
- And influx'  issue #8500 also seems not finally fixed, and contains one goroutine stopped at zapcore's mutex.

Perhaps the troublemaker sits outside of influx codebase...

**Comment by ThomasKurz** [comment]
so this morning we upgraded the docker image to 1.7.6 (kept the databases), 
and just now i realized that this time it had even stopped after some minutes only
with the semaphores blocked in a similar way to before:

[influx-stack-1556283944.txt](https://github.com/influxdata/influxdb/files/3121412/influx-stack-1556283944.txt)

we restarted again now, and after 10 min it is still running.

so definitely the deadlock is not fixed by using 1.7.6, but it still could be depending on 
database or runtime environment, therefore over the weekend we will try and wipe the database
and start refilling it to rule out spurious disk problems.

**Comment by ThomasKurz** [comment]
I just found this in the goroutine stackdumps, which must be the cause for the deadlock:
```
goroutine 594089 [syscall, 300 minutes]:
syscall.Syscall(0x1, 0x2, 0xc0009cd000, 0xc7, 0xc002da4140, 0x12c5253, 0x5)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.write(0x2, 0xc0009cd000, 0xc7, 0x400, 0xc002da4101, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1005 +0x5a
syscall.Write(0x2, 0xc0009cd000, 0xc7, 0x400, 0x0, 0xe, 0x47b2f2)
	/usr/local/go/src/syscall/syscall_unix.go:191 +0x49
internal/poll.(*FD).Write(0xc0000e00c0, 0xc0009cd000, 0xc7, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:268 +0x15c
os.(*File).write(0xc0000de010, 0xc0009cd000, 0xc7, 0x400, 0xc04cf8da50, 0x769653, 0xc0460621e0)
	/usr/local/go/src/os/file_unix.go:266 +0x4e
os.(*File).Write(0xc0000de010, 0xc0009cd000, 0xc7, 0x400, 0x0, 0xc04386e020, 0x1456342955)
	/usr/local/go/src/os/file.go:145 +0x6f
github.com/influxdata/influxdb/vendor/go.uber.org/zap/zapcore.(*lockedWriteSyncer).Write(0xc00000d9c0, 0xc0009cd000, 0xc7, 0x400, 0x21ab3e0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/go.uber.org/zap/zapcore/write_syncer.go:66 +0x66
github.com/influxdata/influxdb/vendor/go.uber.org/zap/zapcore.(*ioCore).Write(0xc000280f00, 0x0, 0xbf28ccd53a3800fd, 0x1456342955, 0x21ab3e0, 0x0, 0x0, 0x12d0187, 0xf, 0x0, ...)
	/go/src/github.com/influxdata/influxdb/vendor/go.uber.org/zap/zapcore/core.go:90 +0x106
github.com/influxdata/influxdb/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc05bf400b0, 0xc05a0ea400, 0x1, 0x1)
	/go/src/github.com/influxdata/influxdb/vendor/go.uber.org/zap/zapcore/entry.go:215 +0xe9
github.com/influxdata/influxdb/vendor/go.uber.org/zap.(*Logger).Info(0xc0002f4a20, 0x12d0187, 0xf, 0xc05a0ea400, 0x1, 0x1)
	/go/src/github.com/influxdata/influxdb/vendor/go.uber.org/zap/logger.go:187 +0x7f
github.com/influxdata/influxdb/query.(*Executor).executeQuery(0xc0001abf80, 0xc02a731e80, 0xc0117692cf, 0xa, 0x0, 0x0, 0x15c2d20, 0x21c9300, 0x2710, 0x0, ...)
	/go/src/github.com/influxdata/influxdb/query/executor.go:330 +0x870
created by github.com/influxdata/influxdb/query.(*Executor).ExecuteQuery
	/go/src/github.com/influxdata/influxdb/query/executor.go:236 +0xc9
```
thus the problem could stem from our docker runtime environment,
in the sense that the log output filedescriptor (which is stdio or stderr) 
somehow becomes blocked by the system.

I could imagine we have hit [this](https://github.com/docker/compose/issues/6018) docker bug...
which would be fixed with [a single change in docker's python files](https://github.com/docker/docker-py/pull/2300).

For now we simply reduced the amount of logging, as next step we could try redirecting stderr to /dev/null inside the container where influxd ist started.

Next week we will also check how to update the docker engine on this machine, which is currently at 
```
isolar@iSolarServer2:~$ docker version
[...]
Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by ummarbhutta** [comment]
We have been using `influx version 1.7.3` in docker for quite a while and it worked fine on following configurations of docker

```
$ sudo docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

$ sudo docker-compose version
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

And since I have upgraded docker to following configurations

```
$ sudo docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$ sudo docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

I am facing same issue. Influx goes in non responding state (No Db operation works even `select`) every now and then. `docker-compose down` even failed with a timeout error. Only solution is to restart host OS.

OS is

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

Any help is highly appreciated.

**Comment by ThomasKurz** [comment]
We recently had similar problems with two different non-influx containers, so there are even more reasons to think that it is more or less a docker-, docker-compose- or container-configuration problem.

Unfortunately docker/compose#6018 doesn't seem to match on python3.

We will perhaps next try with non-blocking logging in docker and see if that helps.

**Comment by ummarbhutta** [comment]
Right now what I did is to redirect the output to **/dev/null**, seems to be working fine after that since many days.

Its coming from docker for sure.
