### ISSUE TITLE
Replace MergeFromGroupRule with new RPC based rules

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#13623]
We have switched over to using the new planner rules that use a single RPC call per physical operation. We need to finish replacing the existing rules, specifically the MergeFromGroupRule was removed and its replacement needs to be created.

**Comment by jlapacik** [comment]
This requires a new physical planner operation `ReadGroup` with a corresponding `ReadGroup` RPC call exposed by storage.

**Comment by stuartcarnie** [comment]
This depends on #13723
