### ISSUE TITLE
Create a way to set per-query and per-server memory limit for queries

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#13637]
We can either do an environment variable, a CLI flag for `influxd`, or both.

See also this issue, which is to determine what the defaults should be:
https://github.com/influxdata/influxdb/issues/13642

**Comment by BondAnthony** [comment]
We probably still need this. I have a dashboard that looks pretty sad once I hit the 1hr timeframe. I have to refresh the dashboard a few times before all the panels are populated. My instance has plenty of cpu and  memory to run more than 10 queries.

**Comment by aanthony1243** [comment]
related+possible dupe here:  https://github.com/influxdata/influxdb/issues/17089

**Comment by ElieLiabeuf** [comment]
@BondAnthony Same problem here. I have a grafana dashboard with more than 40 queries. On refresh all queries are run reaching the QueueSize / concurrencyQuota (https://github.com/influxdata/influxdb/blob/6c28938201d71f1daac0129526d1d66e7160d2f0/cmd/influxd/launcher/launcher.go#L503). Is there any way to configure that ?

**Comment by BondAnthony** [comment]
@ElieLiabeuf unfortunately, it's hardcoded. I think the issue @aanthony1243 linked above will address this and a number of other query settings.

**Comment by Eraac** [comment]
> @BondAnthony Same problem here. I have a grafana dashboard with more than 40 queries. On refresh all queries are run reaching the QueueSize / concurrencyQuota
> 
> https://github.com/influxdata/influxdb/blob/6c28938201d71f1daac0129526d1d66e7160d2f0/cmd/influxd/launcher/launcher.go#L503
> 
> Is there any way to configure that ?

I've the same problem, any update on this?

**Comment by BondAnthony** [comment]
Hey @Eraac, the latest version of the beta fixes this issue.

Here are the new flags.

```
      --query-concurrency int            the number of queries that are allowed to execute concurrently (default 10)

      --query-initial-memory-bytes int   the initial number of bytes allocated for a query when it is started. If this is unset, then query-memory-bytes will be used

      --query-max-memory-bytes int       the maximum amount of memory used for queries. If this is unset, then this number is query-concurrency * query-memory-bytes

      --query-memory-bytes int           maximum number of bytes a query is allowed to use at any given time. This must be greater or equal to query-initial-memory-bytes (default 9223372036854775807)

      --query-queue-size int             the number of queries that are allowed to be awaiting execution before new queries are rejected (default 10)
```

https://github.com/influxdata/influxdb/blob/master/cmd/influxd/launcher/launcher.go#L750:L758

**Comment by BondAnthony** [comment]
@wolffcm I'm going to close this issue since we can now tune the query tier.

**Comment by BondAnthony** [comment]
@wolffcm do these query flags address your concerns or you thinking further into specific queries having different limits?

**Comment by wolffcm** [comment]
@BondAnthony No, I created this issue just for limits on queries globally. It's okay to close this issue.
