### ISSUE TITLE
schema collision detected: column ""_value"" is both of type float and int

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13660]
In OSS, i can't load the measurements for my bucket. It is returning the error: "schema collision detected: column ""_value"" is both of type float and int` and happens from a bucket that only has telegraf data flowing into it.

![image](https://user-images.githubusercontent.com/4805997/56818924-9246a180-67fd-11e9-9a58-ad9a303a041e.png)

version: 191c16c

query causing the error:
```
from(bucket: "telegraf")
  |> range(start: -1h, stop: now())
  |> filter(fn: (r) => true)
  |> group(columns: ["_measurement"])
  |> distinct(column: "_measurement")
  |> keep(columns: ["_value"])
  |> limit(n: 200)
  |> sort()
```

**Comment by jlapacik** [comment]
@russorat Do you get the same error if you use the `v1.measurements()` flux function?

**Comment by russorat** [comment]
i do not see the same error with `v1.measurements()`

**Comment by russorat** [comment]
@jlapacik we are blocked from using those meta queries in the UI until they support absolute time ranges: https://github.com/influxdata/flux/issues/1071

**Comment by jlapacik** [comment]
@russorat can I close this issue then?

**Comment by jlapacik** [comment]
Just to be clear, meta queries should be defined as they are here:

https://github.com/influxdata/flux/blob/master/stdlib/influxdata/influxdb/v1/v1.flux

An update to the implementation of `tagValues` was recently made, which caused the former query not be pushed down to storage anymore, and a known error occurred on the Flux side.

**Comment by russorat** [comment]
@jlapacik i'm happy to mark this as not blocking. Not urgent, but i'd like to understand why the following query would give this error:
```
from(bucket: "telegraf")
  |> range(start: -1h, stop: now())
  |> group(columns: ["_measurement"])
```

**Comment by jsternberg** [comment]
@russorat if you remove the optimization, you are saying you want to group all of the series with the same measurement into the same table. So if any of the series have conflicting types for their `_value` column, this isn't possible.

**Comment by russorat** [comment]
@jsternberg so it worked before. was that a bug?

**Comment by jsternberg** [comment]
Yes. It was a logic bug because that pattern would trigger an optimization that never ran into the code that would produce the error. So now that the optimization is removed, the code is returning an error because it returns an error during normal execution.

**Comment by russorat** [comment]
ok thanks!
