### ISSUE TITLE
Import from template for dashboards not visible when there are no dashboards

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13680]
the option to import from template is available in the upper right of the screen, but not from the button when there are no dashboards in the center of the screen.

**Comment by ebb-tide** [comment]
fixed in commit: https://github.com/influxdata/influxdb/commit/3ebc2fd4538bf7cd8fd8b746a5418b98c2442373

<img width="749" alt="Screen Shot 2019-05-13 at 4 31 39 PM" src="https://user-images.githubusercontent.com/10937678/57660691-9c59f580-759c-11e9-9f0f-212092d68e1d.png">
