### ISSUE TITLE
Save as variable from Data Explorer doesn't keep current query

### ISSUE THREAD

**Issue by sanderson** [influxdata/influxdb#13682]
When saving a query as a variable from the Data Explorer, the current query doesn't get pulled into the modal.

Also, the form in the save as variable modal includes a type dropdown. In this context, I wouldn't expect to be able to select a variable type since I'm in the process of saving a query as a variable.

**Comment by desa** [comment]
@sanderson I just tried to reproduce this myself. At first it seemed like I was able to reliably reproduce the issue, but as of a2a44067b it seems like everything now works as expected.

Can you verify that this is still an issue?

**Comment by desa** [comment]
Looks like this was solved in https://github.com/influxdata/influxdb/commit/ceb7247ae793f8a0929efca214d22a9865dfabd2
