### ISSUE TITLE
cardinality of tsm level labels too high

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#13688]
https://github.com/influxdata/influxdb/issues/11969 was not quite implemented correctly in https://github.com/influxdata/influxdb/pull/13353

We should not have a level label for any TSM level as that could significantly increase the cardinality for that metric, and not add a huge amount of value.

Instead, as stated in the ticket, we should have levels `{1, 2, 3, 4+}`.

**Comment by tmgordeeva** [comment]
Fix in https://github.com/influxdata/influxdb/pull/13698 and one more in https://github.com/influxdata/influxdb/pull/14181
