### ISSUE TITLE
When I submit a long-running query, results of a previous query are immediately displayed

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/influxdb#13685]
It's not immediately clear that these are prior results -- I originally concluded that my query completed quickly, and that I was viewing a new result set.

![Kapture 2019-04-26 at 17 55 24](https://user-images.githubusercontent.com/1438089/56842671-b1b8eb00-684c-11e9-9c79-4afcb3b154a1.gif)

**Comment by mark-rushakoff** [comment]
This has burned me many times as well. Thanks for filing an issue about it -- it's a frustrating user experience.

**Comment by lukevmorris** [comment]
I think this is important to keep open
