### ISSUE TITLE
Deactivated tasks are still running

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13681]
Noticed while working with @timhallinflux's instance. He had deactivated a task in the UI, but the task was still running. Not sure if this is a result of some of the recent changes to Tasks

**Comment by lyondhill** [comment]
in oss? my tasks stop when I deactivate them. But I did notice that when a task is reactivated it currently back fills all task run's that would have happened while deactivated. I can fix the issue I mentioned. Can you give a little more detail about the tasks staying claimed?

**Comment by lyondhill** [comment]
I found a minor issue fixed here: https://github.com/influxdata/influxdb/pull/13700 related but I have not reproduced the issue.

**Comment by timhallinflux** [comment]
This was in Cloud.  I had deactivated the task in the early morning.  I came back in the afternoon and the task appeared to have been executing....at least the task run logs were showing that it had run.

**Comment by lyondhill** [comment]
fixed by https://github.com/influxdata/influxdb/pull/13721
