### ISSUE TITLE
Include series type in series index queries

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#13693]
This issue proposes changes to TSI index APIs to return `SeriesIDTyped` rather than `SeriesID`. The type information can then be reused to improve performance significantly when reading TSM data. Over a large number of series this may be a double-digit percentage of CPU time.

```
     0.01s  0.14%  0.14%      3.97s 55.14%  github.com/influxdata/influxdb/storage/reads.(*resultSet).Cursor
     0.01s  0.14%  0.28%      3.96s 55.00%  github.com/influxdata/influxdb/storage/reads.(*multiShardArrayCursors).createCursor
     0.02s  0.28%  0.56%      3.92s 54.44%  github.com/influxdata/influxdb/tsdb/tsm1.(*arrayCursorIterator).Next
     0.04s  0.56%  1.11%      2.73s 37.92%  github.com/influxdata/influxdb/storage/readservice.(*indexSeriesCursor).Next
         0     0%  1.11%      2.47s 34.31%  github.com/influxdata/influxdb/tsdb.(*SeriesFile).SeriesIDTypedBySeriesKey
```
## Background

The `seriesCursor` issues an index request to retrieve a candidate set of `SeriesID` values:

https://github.com/influxdata/influxdb/blob/fb39ac39ce4a2ad275d1a7d046232d70df9eb62b/storage/series_cursor.go#L126

These should return `SeriesIDTyped` and rather than throwing them away, they should be included in the `SeriesRow`:

https://github.com/influxdata/influxdb/blob/fb39ac39ce4a2ad275d1a7d046232d70df9eb62b/storage/series_cursor.go#L44-L47

The `SeriesRow` is ultimately used to construct a request to read TSM data for a specific series via the `arrayCursorIterator`. This starts here:

https://github.com/influxdata/influxdb/blob/d73d73c0d4b708462ef58c8851577486aeb3de56/storage/reads/array_cursor.go#L119

and the `arrayCursorIterator.Next` is called here:

https://github.com/influxdata/influxdb/blob/d73d73c0d4b708462ef58c8851577486aeb3de56/storage/reads/array_cursor.go#L133

Finally, that results in determining the series type here, which constitutes a double-digit percentage of the total read request time:

https://github.com/influxdata/influxdb/blob/fdae1ae5ea83423b5f88a126fbe67db52c927d58/tsdb/tsm1/array_cursor_iterator.go#L37

**Comment by jacobmarble** [comment]
PR to add 64 bit support to roaring:

https://github.com/RoaringBitmap/roaring/pull/245

**Comment by benbjohnson** [comment]
Update: I investigated what would be required to do this and I think it's a lot of effort. We'd need to test Jacob's 64-bit roaring PR extensively and then we'd need to add support to TSI to support both 32-bit & 64-bit serialization. Once we have that, we'd still need to check series types for historical index files unless we wanted to mass convert on upgrade.

I'm looking into simpler options instead. Since Flux requires the same type for all series in a cursor, I'm investigating if we can just check the type once and reuse it for subsequent series. Another option is to pull the type data directly from tsm1 instead of the series file.

**Comment by benbjohnson** [comment]
Update: Sidetracked with some EAR & error reporting work; just getting back into this.

**Comment by 8none1** [comment]
@benbjohnson do you think that there is still benefit in spending time on this one?

**Comment by benbjohnson** [comment]
@8none1 No, with IOx coming out I don't think it's worth the effort to integrate 64-bit roaring encoding in TSI.
