### ISSUE TITLE
influxd backup only states "connection reset by peer"

### ISSUE THREAD

**Issue by dennisjac** [influxdata/influxdb#13706]
I'm trying to test the backup command but it doesn't seem to work. I used the official docker image influxdb:1.7.4 for the server and make both ports 8086 and 8088 available on the host.
The client can connect to influxdb fine:
```
[dennis@nexusm Downloads]$ ./influxdb-1.7.4-1/usr/bin/influx
Connected to http://localhost:8086 version 1.7.4
InfluxDB shell version: 1.7.4
Enter an InfluxQL query
> show databases
name: databases
name
----
test
_internal
```
but when I try to create a backup I only get "connection reset by peer":
```
[dennis@nexusm Downloads]$ ./influxdb-1.7.4-1/usr/bin/influxd  backup ./influxbackup/
2019/04/29 23:46:20 backing up metastore to influxbackup/meta.00
2019/04/29 23:46:20 Download shard 0 failed copy backup to file: err=read tcp 127.0.0.1:43446->127.0.0.1:8088: read: connection reset by peer, n=0.  Waiting 2s and retrying (0)...
2019/04/29 23:46:22 Download shard 0 failed copy backup to file: err=read tcp 127.0.0.1:43452->127.0.0.1:8088: read: connection reset by peer, n=0.  Waiting 2s and retrying (1)...
2019/04/29 23:46:24 Download shard 0 failed copy backup to file: err=read tcp 127.0.0.1:43458->127.0.0.1:8088: read: connection reset by peer, n=0.  Waiting 2s and retrying (2)...
```
The docker logs show no ouput when I start the backup command.

**Comment by dennisjac** [comment]
I just tried this with 1.7.6 and see the same issue. What is interesting is that I only see this when using the docker container. When I install influxdb directly on my system it seems to work and when I install it via kubernetes and use `kubectl port-forward` it works as well.

**Comment by dennisjac** [comment]
I finally figured out what the issue was. Apparently influxdb binds port 8086 to the docker ip however it only bind port 8088 to 127.0.0.1 and as a result a port binding of `127.0.0.1:8088:8088` in the docker-compose file does not work. I assume the "connection reset by peer" (instead of "cannot connect") comes from the proxied nature of the connection i.e. the connection to the docker proxy succeeds but its connection to the container fails so it responds with a reset.
The fix is to set an ENV variable `INFLUXDB_BIND_ADDRESS=:8088` so the port is properly available to the docker proxy.

**Comment by JulianSchneider** [comment]
Where did you set the ENV variable? Setting it in the host doesn't work. I forwarded 8086 and 8088 from the docker container.
