### ISSUE TITLE
Dashboard Template Registry 

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#13726]
__Proposal:__
There should be a registry of dashboard templates to be created when new organizations are created.

__Current behavior:__
Currently, dashboard templates' created by us are stored on the front end and then added to a system when an organization is created or a user is onboarded.

__Desired behavior:__
It would be nice if these templates were stored elsewhere so that other applications (like quartz) that need to create the templates did not need to create the contents of the template as well.

__Alternatives considered:__
Formally, there were the concept of `protos` which were essentially dashboard templates that were stored on the back end. something like this could be done too so that the influxdb ui and quartz would not have to have separate logic to create these templates nor would they have to worry about storing the contents of the templates in separate applications.

__Use case:__
Why is this important (helps with prioritizing requests)?
Creating dashboard templates in cloud (the right way)

**Comment by ebb-tide** [comment]
This should be extensible to a "dashboardLand" where users can upload templates, and download templates created by influxDB or by other users.
