### ISSUE TITLE
Some functions in the script editor shouldn't have pipe-forwards

### ISSUE THREAD

**Issue by sanderson** [influxdata/influxdb#13727]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open the Data Explorer
2. Switch to the Script Builder
3. Search for and click the `math.abs` function

__Expected behavior:__
The `math.abs` function and many others are not pipe-forwardable (they don't accept input tables `<-` as one of their parameters) so they should not be put in the script with a pipe-forward operator `|>`.

__Actual behavior:__
The UI puts a pipe-forward on non-pipeforwardable functions.

Most of these are for transforming single values and should therefore be used inside of a row function (functions that operate on one row at a time such as filter, map, or reduce). Here's the list of current functions that are non-pipe-forwardable:

- bool
- csv.from
- duration
- from
- int
- intervals
- join
- math.NaN
- math.abs
- math.acos
- math.acosh
- math.asin
- math.asinh
- math.atan
- math.atan2
- math.atanh
- math.cbrt
- math.ceil
- math.copysign
- math.cos
- math.cosh
- math.dim
- math.erf
- math.erfc
- math.erfcinv
- math.erfinv
- math.exp
- math.exp2
- math.expm1
- math.float64bits
- math.floor
- math.frexp
- math.gamma
- math.hypot
- math.ilogb
- math.isInf
- math.isNaN
- math.j0
- math.j1
- math.jn
- math.ldexp
- math.lgamma
- math.log
- math.log10
- math.log1p
- math.log2
- math.logb
- math.m_inf
- math.m_max
- math.m_min
- math.mod
- math.modf
- math.nextafter
- math.pow
- math.pow10
- math.remainder
- math.round
- math.roundtoeven
- math.signbit
- math.sin
- math.sincos
- math.sinh
- math.sqrt
- math.tan
- math.tanh
- math.trunc
- math.y0
- math.y1
- math.yn
- string
- strings.title
- strings.toLower
- strings.toUpper
- strings.trim
- strings.trimPrefix
- strings.trimSpace
- strings.trimSuffix
- systemTime
- time
- uint
- union
- v1.measurementTagKeys
- v1.measurementTagValues
- v1.measurements
- v1.tagKeys
- v1.tagValues

**Comment by desa** [comment]
Simple solution here is to simply no longer include the `|>` operation when appending the results.
