### ISSUE TITLE
Link in `cell--header-bar`/`markdown-cell--contents` is unclickable

### ISSUE THREAD

**Issue by glinton** [influxdata/influxdb#13745]
__Steps to reproduce:__

1. Open the pre-generated `System` dashboard
2. Attempt to click on `Telegraf Documentation`

__Expected behavior:__
Go to documentation

__Actual behavior:__
Moves the cell

__Environment info:__
```
> uname -srm
Linux 5.0.0-13-generic x86_64
> ~/src/influxdb_2.0.0-alpha.9_linux_amd64/influxd version
Error: unknown command "version" for "influxd"
Run 'influxd --help' for usage.
```

![cellHeaderLink](https://user-images.githubusercontent.com/2653109/57045015-9a517780-6c29-11e9-94b6-0df8d3c14800.gif)

**Comment by glinton** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/2653109/62225869-790e3d80-b376-11e9-8e6e-59d753869b67.png)

The only way to follow the link is to edit the note:
![image](https://user-images.githubusercontent.com/2653109/62225958-9e9b4700-b376-11e9-832b-101fae2e2466.png)

**Comment by glinton** [comment]
bump

**Comment by glinton** [comment]
bump

**Comment by russorat** [comment]
we fixed that with a redesign of the headers:
![image](https://user-images.githubusercontent.com/4805997/72481288-e1c76600-37ae-11ea-965b-b637ab4adffa.png)
