### ISSUE TITLE
Variable rename overlay has two titles and x's

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#13777]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. go to variables tab in org settings
2. hover over variable and click rename
3. click i understand, lets rename

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
![Screen Shot 2019-05-03 at 1 36 40 PM](https://user-images.githubusercontent.com/5751863/57164353-b0d20d00-6da8-11e9-8057-2a1d661bbcaf.png)

__Environment info:__
oss

**Comment by alexpaxton** [comment]
Overlayception!!
