### ISSUE TITLE
Cannot change retention policy on bucket

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#13776]
Via the UI I do the following:

* Navigate to "Settings" -> "Buckets"
* Click on the name of my bucket
* Click on "periodically"
* Type "30" into Days
* Click save changes

Behavior:

I get an error `Failed to update bucket: "telegraf"`

Expected:

The retention policy is changed

Notes:

The error text is not selectable so I could not copy paste it. In this case the error was easy enough to type out but it would be nice to be able to copy paste error messages.

**Comment by russorat** [comment]
@nathanielc i am unable to reproduce. was this OSS or cloud?

**Comment by nathanielc** [comment]
This was against prod cloud.

**Comment by Palakp41** [comment]
I was not able to reproduce the same error. We have updated retention policy to 72hrs and was able to successfully update buckets.
