### ISSUE TITLE
ScheduleFor time is before StartedAt time

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#13798]
I have noticed the following behavior on open source platform (I have not yet checked the idpe). 
- I have created the task with `every=15s`, where the task created  time was `17:47:49`.
- My understanding that first task run is supposed to happen between `17:47:49` and `17:48:04`.
- Time is being aligned for the first run (in my case):
   - reset the time to `17:47:00` (since we are dealing with `every` seconds)
   - keep adding the `15` seconds interval starting with `17:47:00` until time goes over `17:47:49`, which, in this case, will be `17:48:00`
   - first run is scheduled to run at `17:48:00`
- In reality the first run happened at `17:48:04`, which is exactly in 15 seconds.
- But `scheduleFor` is set to `17:48:00`, so there is a `4 seconds` gap in this case. If i understand correctly, the query with use `17:48:00` for start time in `(start: -x)`

**Comment by gshif** [comment]
All following runs are aligned to `17:48:00`

**Comment by docmerlin** [comment]
ScheduledFor should always be before or equal to StartedAt.  The system doesn't prove guarantees as to the latency between when a run is scheduled for and the time it executes.  However, 4 seconds is a really long time, much longer than I would expect.  There could be something wrong in there, possibly with the cron code.

**Comment by lyondhill** [comment]
@docmerlin The first run after a task is created doesnt have a latest_completed time to base its first NextDueAt time so it uses created_at. After the first one it knows the latest_completed. I think this is behaving as expected but we could make it a little smarter about what time stamp it uses for its first NextDueAt time.

**Comment by lyondhill** [comment]
I believe this was fixed by https://github.com/influxdata/influxdb/pull/14668
