### ISSUE TITLE
Flux CSV responses contain duplicate and invalid rows

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#13822]
1. Go to the Data Explorer
2. Throttle network to "Fast 3G"
3. Run the following query

   ```
   from(bucket: "telegraf")
     |> range(start: -7d)
     |> filter(fn: (r) => r._measurement == "net")
     |> filter(fn: (r) => r._field == "bytes_recv" or r._field == "bytes_sent")
     |> derivative(unit: v.windowPeriod, nonNegative: false)
     |> yield(name: "derivative")
   ```
4. Download the CSV results

The results contains duplicate rows, and mangled output such as

```
,,0,2019-04-30T16:49:23.999371Z,2019-05-07T16:49:23.999371Z,2019-04-30T16:54:30Z,0#group,false,false,true,true,false,false,true,true,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string,string
#default,derivative,,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,host,interface
,,0,2019-04-30T16:49:23.999371Z,2019-05-07T16:49:23.999371Z,2019-04-30T16:49:40Z,0,bytes_sent,net,oox4k.local,awdl0

```

The CSV that comes back from Flux does not contain these issues—this seems related to our client side processing of the Flux CSV only.

Seems to be the cause of https://github.com/influxdata/influxdb/issues/13819 as well.

Current hypothesis is that the callback here is being run concurrently, though exactly one process needs to be running at a time:

https://github.com/influxdata/influxdb-client-js/blob/dev/src/utils/request/browser.ts#L26

**Comment by mark-rushakoff** [comment]
The error message "write after end" in a dashboard cell may be another symptom of this issue.

**Comment by russorat** [comment]
is this the same issue?

![image](https://user-images.githubusercontent.com/4805997/57318840-17f50780-70b0-11e9-9ac6-38c54498b4dc.png)

[2019-05-07-10-09 Chronograf Data.csv.zip](https://github.com/influxdata/influxdb/files/3153752/2019-05-07-10-09.Chronograf.Data.csv.zip)

**Comment by chnn** [comment]
@russorat Yes, same issue.

**Comment by russorat** [comment]
ok, also this might be related: https://github.com/influxdata/influxdb/issues/13814

**Comment by chnn** [comment]
Fix merged into InfluxDB master, a deploy to acceptance is in progress now.
