### ISSUE TITLE
Add function type ahead into the Flux editor

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13839]
as a user
with admin
when i type a `|>` into the script editor
then i would like to see the list of available functions i can use

Can we re-use anything from the 1.x flux editor?

**Comment by dominiclapointe** [comment]
This would be a major improvement and make the adoption easier! learning a new language without 'intellisense' is quite a pain!

+1

**Comment by sanderson** [comment]
Related to #13727

**Comment by russorat** [comment]
bump. 
this is being addressed by the monaco issue
https://github.com/influxdata/influxdb/issues/15614
https://github.com/influxdata/influxdb/issues/15954

**Comment by russorat** [comment]
this has been added! yay! thanks @ebb-tide !
