### ISSUE TITLE
Enable viewing time series data in Cypress e2e tests

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#13848]
Our [Cypress](https://www.cypress.io/) based e2e tests are essential for testing the API and UI, yet their utility is severely limited since we cannot create test cases containing time series data.  

We should investigate whether it is possible to expose an in-memory storage backend for time series data, that can be seeded with data before each test and cleared after each test (see the `--e2e-storage` and `--store` flags of the `influxd` binary).

**Comment by 121watts** [comment]
@e-dard how do we make this a reality?
