### ISSUE TITLE
Chronograf fails to update task labels

### ISSUE THREAD

**Issue by davidgs** [influxdata/influxdb#13857]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a task in Chronograf, set the internal and offset
2. Edit the task in Chronograf and remove the offset

__Expected behavior:__
The label should show no offset after its removed.
__Actual behavior:__
Label never changes
__Environment info:__
[davidgs@whm ~]$ uname -srm
Linux 3.10.0-862.14.4.el7.x86_64 x86_64
[davidgs@whm ~]$
* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here -- It's 2.0 alpha OSS built from source. 
[davidgs@whm ~]$ ./influxd version
Error: unknown command "version" for "influxd"
Run 'influxd --help' for usage.
[davidgs@whm ~]$
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
No config file for 2.0

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by davidgs** [comment]
![tasks](https://user-images.githubusercontent.com/2071898/57414639-92ac4880-71be-11e9-995b-c2ed02339f6d.gif)

**Comment by ebb-tide** [comment]
An empty offset is conveyed to backed as 'no change', so not surprised by this behavior. I wonder if it would be appropriate behavior for empty string to be replaced with zero offset. I wonder if we should just not allow an empty string- one way to do that would be a number input component with up/down arrows that defaults to zero

**Comment by bthesorceror** [comment]
@ebb-tide not sure a number input will work here because we need the unit as well as the number, I think we should just replace empty string with `0s`

**Comment by jademcgough** [comment]
Sending an offset of `0` should delete the offset for a task.
