### ISSUE TITLE
Tasks after skips the first task

### ISSUE THREAD

**Issue by lyondhill** [influxdata/influxdb#13861]
when listing tasks with a `after` taskID that is not on the list, we skip the first task. 
This has been fixed but only in boltdb. We need this fix https://github.com/influxdata/influxdb/pull/12103 to be applied to the kv/task.go as well.

**Comment by lyondhill** [comment]
We should also add a test in task/servicetest/servicetest.go

**Comment by lyondhill** [comment]
@zhulongcheng Are you interested in picking this up? If not I can do it. It's basically the same thing you did in bolt but in the kv system.

**Comment by zhulongcheng** [comment]
Yes. 💯

**Comment by lyondhill** [comment]
closed by #12103
