### ISSUE TITLE
Fix npm lockfile flapping

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#13864]
Most times the UI is built, the npm lockfile (`package-lock.json`) is modified with irrelevant changes. These changes introduce noise into our diffs, and can be confusing for engineers not familiar with `package-lock.json`.

We should find a way to avoid modifying the `package-lock.json` file unless necessary (i.e. unless dependencies have actually changed).

Relevant:

- https://npm.community/t/package-lock-json-changes-from-one-npm-install-to-the-next/1454/5
- https://github.com/npm/npm/issues/18613
- https://github.com/npm/npm/issues/20926#issuecomment-397372131
- https://npm.community/t/package-lock-json-keeps-changing-between-platforms-and-runs/1129
- https://npm.community/t/package-lock-json-is-not-complete-on-first-run-for-some-modules/1817

**Comment by chnn** [comment]
Can think of two solutions:

1. Enforce everyone uses a particular `npm` version (need to verify this works)

2. Switch back to `yarn`

I'm in favor of (2) it brings other benefits in addition to solving lockfile flapping:

- Quicker no-op runs
- Nicer CLI output
- No `npm audit` noise by default
- Easier to read lockfile diffs (YAML rather than JSON)
- Doesn't set modified time on lockfile during no-op runs, so easier to integrate with make

But I recognize these are personal preferences and I don't feel strongly so long as we can solve this issue and https://github.com/influxdata/idpe/issues/3477

**Comment by chnn** [comment]
Fixed by switch to yarn.

**Comment by ohjames** [comment]
We are seeing this constantly where I work. We have to run `npm install` three times to get `package-lock.json` to stabilise. Very annoying. Also going to switch to yarn.
