### ISSUE TITLE
Strip yields on tasks.

### ISSUE THREAD

**Issue by docmerlin** [influxdata/influxdb#13868]
__Proposal:__
Strip out yields in flux tasks, and replace with a comment on task creation.  We can do this before the formatting on task creation and on updating the flux.  This is to keep resource usage low for query, and allow people to easily cut and paste their queries into tasks.
 
__Current behavior:__
yield sends back data to tasks.  That data is thrown away.  This wastes bandwidth, query resources, and a task socket.
__Desired behavior:__
Strip out yields in flux tasks, and replace with a comment on task creation.  
__Alternatives considered:__
Considered a parameter to tell query to not send back data.  @nathanielc recommended this instead.

__Use case:__
This makes cutting and pasting in queries you wish to be tasks easier, and saves query (and task) resources, while making UX a bit nicer.

**Comment by nathanielc** [comment]
@docmerlin Would it make sense to expose this behavior via the UI, meaning maybe its a one time modification to the script during the `send to task` action by the user? This doesn't solve the issue of users adding new yields after they created the task, but it might help make the edits more visible and explicit to the user so they are not surprised.

**Comment by docmerlin** [comment]
I think that would solve about half the issue, but not the other half.
