### ISSUE TITLE
How to learn the TSM storage engine

### ISSUE THREAD

**Issue by smallnine9** [influxdata/influxdb#13878]
__Proposal:__
I am a college student and I just want to implement a TSM tree by myself but I found influxdb is so huge so I want to know if I can get some advice

__Current behavior:__
now I have read docs in website of influxdb and I have downloaded the whole code from github
__Desired behavior:__
I want to know which code should I read and learn? If I want to write a TSM tree code

__Alternatives considered:__
any docs or guide would be appreciate

__Use case:__
Sorry to ask a question which seem to be unimportant, I have found many blogs on the internet but I do not get enough details, so I only can ask this question to developers.

**Comment by dgnorton** [comment]
@smallnine9 happy that you're interested in InfluxDB. The best place to ask questions is on the [InfluxData community site](https://community.influxdata.com/). We use GitHub issues for bugs and feature requests.

Here are a few links into the repo that may get you started:
* [TSM design doc](https://github.com/influxdata/influxdb/blob/master/tsdb/tsm1/DESIGN.md)
* The TSM code is in the [tsm1 package](https://github.com/influxdata/influxdb/tree/master/tsdb/tsm1).
* When data is written, it starts with the [tsm1.WritePoints](https://github.com/influxdata/influxdb/blob/master/tsdb/tsm1/engine.go#L585) function. You can trace through the code from there.
