### ISSUE TITLE
InfluxDB 2.0: There is now way how to get version of InfluxDB from API [area/api] 

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#13907]
The InfluxDB 1.7.x has defined [`/ping`](https://docs.influxdata.com/influxdb/v1.7/tools/api/#ping-http-endpoint) endpoint with `X-Influxdb-Version` header but in the API 2.0 there is no such thing.

The `/health` endpoint will be useful for that.

**Comment by bednar** [comment]
Related to https://github.com/influxdata/influxdb/issues/13747

**Comment by bednar** [comment]
+1

**Comment by sranka** [comment]
InfluxDB 1.8 "/health" endpoint already returns version:
```js
{
"checks": [],
"message": "ready for queries and writes",
"name": "influxdb",
"status": "pass",
"version": "1.8.0"
}
```
Whereas the InfluxDB2.0 now returns
```js
{
"name": "influxdb",
"message": "ready for queries and writes",
"status": "pass",
"checks": []
}
```
Adding a version string to 2.0 will fix this issue and make the health endpoint consistent with 1.8.
