### ISSUE TITLE
Static Templates

### ISSUE THREAD

**Issue by bthesorceror** [influxdata/influxdb#13938]
Given I am a user
When I go to the templates list
Then I see a list of templates that are pulled from the templates json
And I can instantiate a dashboard from these static templates

**Comment by bthesorceror** [comment]
The JSON for these templates lives in https://github.com/influxdata/influxdb-templates. These templates are not modifiable from the UI.

**Comment by ebb-tide** [comment]
Perhaps this could be taken care of as part of this work: https://github.com/influxdata/influxdb/issues/14098
