### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13947]
Saw this while testing: https://github.com/influxdata/influxdb/pull/13823

I added two variables to my dashboard, and then saw this error.

![image](https://user-images.githubusercontent.com/4805997/57893168-be4eb480-77f6-11e9-96f0-2aa1c40b18e6.png)

**Comment by 121watts** [comment]
I created a few variables to try and recreate the issue.  Could not reproduce.  Unfortunately, the snapshot shows the minified stack trace.  So, I don't know where the code is breaking.  Closing this for now.
