### ISSUE TITLE
Clicking on bucket name causes a full page reload before showing the overlay

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#13958]
__Steps to reproduce:__

![bucket_page_reloading](https://user-images.githubusercontent.com/5751863/57945195-053bb900-788e-11e9-9743-cbb1005920e2.gif)

__Expected behavior:__
It should look closer to Templates.
![correct_loading_overlay](https://user-images.githubusercontent.com/5751863/57945332-78452f80-788e-11e9-9ca8-5c480fe4ec40.gif)

__Actual behavior:__
It seems to do a full page reload.

__Environment info:__
OSS

**Comment by desa** [comment]
Task is to go through app and search for anchor tags and prevents default click. @121watts

**Comment by hoorayimhelping** [comment]
No longer an issue - the default behavior is being prevented.
