### ISSUE TITLE
On small dashboard cells errors cannot be read

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#13957]
![Screen Shot 2019-05-17 at 10 06 20 AM](https://user-images.githubusercontent.com/2433762/57945138-e9d0ae00-788d-11e9-95bc-6185fa2741c7.png)

**Comment by chnn** [comment]
How about this for a less scrollbar-y design?

![error messages](https://user-images.githubusercontent.com/638955/59312145-dc2a0080-8c60-11e9-800c-7ae144d12b73.gif)
