### ISSUE TITLE
Support tableFind in InfluxDB REPL

### ISSUE THREAD

**Issue by affo** [influxdata/influxdb#13976]
If `tableFind` gets a transformation of `influxdb.from(...)` as pipe argument, it tries to execute the function in the client side.

It should send the piece of query that it gets as an input to the `QueryService` in the REPL.

This is something difficult to do, because we have no means now to translate a `TableObject` into an AST (that we cannot use the Spec anymore).

**Comment by affo** [comment]
Still relevant and should be fixed.

**Comment by affo** [comment]
Relevant

**Comment by jsternberg** [comment]
We're doing some work for the REPL that should cause this to be fixed because the REPL won't be special anymore. See #2498 for details. I'm going to leave this open until we confirm that the changes work.

**Comment by russorat** [comment]
We have removed the REPL from the cli so this is no longer valid.
