### ISSUE TITLE
Mismatch between influxDB and grafana timestamps

### ISSUE THREAD

**Issue by qbic22562** [influxdata/influxdb#13993]
Hi everyone!

I was searching for similar issue but I couldn't find anything.
I have influx database which is linked with grafana. On the grafana dashboard everything seems to be fine but sometimes there's situation that I want to check if data is accurate. To do so I used `precision rfc3339` and I realized that everything is accurate despite timestamps. I have correct timestamp on grafana, but on influx every data point is ~2 hours earlier than it should be.
Has anyone forced similar problem?

Regards :)

**Comment by izkasi** [comment]
Did you set the proper tz() in your query?
