### ISSUE TITLE
Aggregate Integral Function

### ISSUE THREAD

**Issue by gesquive** [influxdata/influxdb#1400]
A function we use often in graphite is [integral](http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.integral). It's pretty self explanitory. We really want to completely replace graphite with influxdb and this would really help our case.

**Comment by balistof** [comment]
Provide also an aggreate Integral Average function. So that you not take the Mean (sum of values divided by count) but instead use the time as the weight. Basically like Integral but dividing the Integral value by the group by time() range.

**Comment by C4ptainCrunch** [comment]
Any update on this ?

**Comment by martinpallmann** [comment]
I also like to know if there is happening something regarding this ticket. We're using influx right know and the missing integral function is a big problem for us.

**Comment by beckettsean** [comment]
@martinpallmann it is not yet scheduled for a particular release, so it is 6+ weeks away. Watch this issue for updates to the Milestone. That's out backlog.

**Comment by michaelsproul** [comment]
I've implemented an integration aggregation function in #3344 and would appreciate feedback and help getting it merged :smile:

**Comment by hotsnow77** [comment]
+1

**Comment by enavarro222** [comment]
+1
This will be very useful to get energy consumption (Kwh) from power logging (W)

**Comment by markusr** [comment]
@enavarro222 
We use:  ``` SELECT sum(power)/count(power) FROM "data" WHERE $timeFilter GROUP BY time(1h) ```
to calculate the energy consumption in [kWh]. power is [W]

**Comment by carlosandroni** [comment]
@enavarro222 
Your solution works only if you have a constant sample time.

**Comment by pakozm** [comment]
I'm also interested in this feature... Is it planed to be introduced in InfluxDB?

**Comment by oluies** [comment]
+1

**Comment by sischnei** [comment]
+1: Would allow to count the amount of events processed!!

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by lukecyca** [comment]
+1

**Comment by lbuchy** [comment]
+1

**Comment by JarrettR** [comment]
+1

**Comment by uprial** [comment]
+1

**Comment by dstreppa** [comment]
+1

**Comment by lukyad** [comment]
+1

**Comment by dongshu2013** [comment]
+1

**Comment by hurtstotouchfire** [comment]
+1

**Comment by AndreJacomeSilva** [comment]
+1

**Comment by stettix** [comment]
+1

**Comment by bkdspanning** [comment]
+1

**Comment by jwasys** [comment]
+1

**Comment by Elphick** [comment]
+1

**Comment by tnn24** [comment]
+1

**Comment by t-pfaff** [comment]
+1

**Comment by villaRob** [comment]
+1

**Comment by StasGoshtein** [comment]
+1

**Comment by micbuh** [comment]
+1

**Comment by ot3** [comment]
+1

**Comment by hl68fx** [comment]
+1

**Comment by cantino** [comment]
+1

Has anyone found a workaround for this? I need this for calculating power use with a variable power sampling rate, as mentioned by @enavarro222 and @carlosandroni.

**Comment by JarrettR** [comment]
https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md

Looks like it's in 1.3.0 (Still unreleased)

**Comment by popey456963** [comment]
It has since been released, this issue should probably be closed?

It would be useful to update the documentation [here](https://docs.influxdata.com/influxdb/v0.9/query_language/functions/#integral)
