### ISSUE TITLE
One should be able to see if/all the alerts defined on any individual flux query.

### ISSUE THREAD

**Issue by nisley** [influxdata/influxdb#14005]
[Alerts & Notifications RFC](https://community.influxdata.com/t/what-is-my-scraper-status-and-other-scraper-options/10110)

__Proposal:__
One should be able to see if/all the alerts defined on any individual flux query.

__Use case:__
As a user, it would be nice to know if someone else has done some work on the query I am working on.  This notification could prevent a lot of duplicate work with this awareness.

**Comment by desa** [comment]
no longer relevant
