### ISSUE TITLE
User selects token for task

### ISSUE THREAD

**Issue by bthesorceror** [influxdata/influxdb#14020]
In Data Explorer Save As:

Given I am a user creating a task and a list of my existing tokens
When I create a task I can select a token from a dropdown
Then the created task will be run with that token

**Comment by bthesorceror** [comment]
Selecting a token from the dropdown should add the token's id to the request to create a token. A task should not be able to be made without a token.

**Comment by lukevmorris** [comment]
- Display input and output buckets
- Display only the relevant tokens for this task
