### ISSUE TITLE
Cloud v2.0: Changing Time in Custom Time Range (Data Explorer/Dashboard)

### ISSUE THREAD

**Issue by ewendai** [influxdata/influxdb#14042]
Trying to change the time by typing under the custom time range option does not work.
Note: Changing the date by typing DOES work. 

Specifically, the original chosen custom time range was 11:00 to 12:00. Selected "Custom Time Range" under the "Time Range" options and tried typing in 11:30 instead of 11:00. Hit "Apply Time Range". Expected to see the new custom time range change to 11:30 to 12:00, but the change was not reflected and remained 11:00 to 12:00. 

Also tried typing in 10:00 instead of 11:00. Time range remained the same. 

<img width="527" alt="before" src="https://user-images.githubusercontent.com/31293435/58734922-b58cdf80-83ad-11e9-8910-bfc0bd3210df.PNG">
<img width="303" alt="after" src="https://user-images.githubusercontent.com/31293435/58734921-b58cdf80-83ad-11e9-94a1-6e9ff7445f13.PNG">

**Comment by russorat** [comment]
i don't think this is an issue anymore. if you're still seeing this with the latest release, please reopen.  thanks!
