### ISSUE TITLE
[UI] -- Cell Visualizations - Graph w Stat - Base color dropdown does not expand on first click

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#14056]
N.B. Writing a Cypress Test to cover this component.  Need to work around with a second click.  However, if this will be fixed, second click will then close the dropdown as already happens with other dropdown controls... and test will fail. 

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a dashboard
2. Create a cell with data and save
3. Open the configure cell menu item 
4. Click the settings cog wheel
5. Set Graph type to Graph + Single Stat
6. Scroll to Colorized Thresholds 
7. Click the "Base" Color dropdown.  

The dropdown fails to expand on the first click. 

__Expected behavior:__
Since other dropdowns on the page expand with one click, expected this one will expand with 1 click as well. 

__Actual behavior:__
Dropdown failed to expand.  Had to Click a second time. 

__Environment info:__

* System info: Run `uname -srm` and copy the output here `Linux 4.4.0-148-generic x86_64`

* InfluxDB version: Run `influxd version` and copy the output here
This is a local build. Last commit from master. 
`c786b0a69fa74a83c39e84f82ffa01996865de62`

* Other relevant environment details: Container runtime, disk info, etc
Browser: Chrome 74, Electron 59

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Boot command
`./bin/linux/influxd --store=memory --e2e-testing=true --log-level debug 2>&1 > ~/var/log/influxd.log &`

__Screenshots__ 

![ThresholdNeedsSecondClick01](https://user-images.githubusercontent.com/25881301/58889493-497de480-86e9-11e9-9ab7-5b0562eceb70.png)

**Comment by desa** [comment]
@karel-rehor is this still an issue?
