### ISSUE TITLE
[UI] -- Cell Visualzation - Graph w Stat - Threshold input has incomplete increment and decrement controls

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#14057]
N.B. I'm preparing a cypress test for this feature.  I can skip this part of the test until this is fixed. 

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a Dashboard
2. Create a cell
3. Click the Configure Item of the cell menu
4. Open the settings cogwheel 
5. Click Graph type 'Graph + Single Stat'
6. Click 'Add Threshold'.  A new Threshold Item is added with an input labeled 'Value is <=='.  To the right of the input is a green check mark. 
7. Click the green check mark.  The value in the input decreases by 1. 

__Expected behavior:__
Describe what you expected to happen.

Didn't know what to expect.  I was trying to understand why is there a green check mark. 

However, if this is to have a decrement control....

* The icon for the control should not be a green check mark 
* It should have a complimentary increment control 

__Actual behavior:__
Describe What actually happened.

Could decrement using the unintuitive green checkmark.  There is no increment control. 

__Environment info:__

* System info: Run `uname -srm` and copy the output here `Linux 4.4.0-148-generic x86_64`
* InfluxDB version: Run `influxd version` and copy the output here.  
This is a local build.  Latest commit from master. 
`c786b0a69fa74a83c39e84f82ffa01996865de62`
* Other relevant environment details: Container runtime, disk info, etc
Browser: Chrome 74

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Boot Command: 
```
./bin/linux/influxd --store=memory --e2e-testing=true --log-level debug 2>&1 > ~/var/log/influxd.log &
```

__Screenshots__
![ThresholdDecrIncr01](https://user-images.githubusercontent.com/25881301/58893065-ad0b1080-86ef-11e9-8867-92f2eabfe9f1.png)
![ThresholdDecrIncr02](https://user-images.githubusercontent.com/25881301/58893066-ada3a700-86ef-11e9-8c3c-cd62ec1e51c9.png)

**Comment by desa** [comment]
no longer an issue
