### ISSUE TITLE
Map variable type should show the keys in the dropdown not the values

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#14054]
__Steps to reproduce:__

1. Open Data explorer
2. Click variables
3. Hover over map variable
4. See values rather than keys

__Expected behavior:__
Should see keys instead of values.
![Screen Shot 2019-06-03 at 1 35 19 PM](https://user-images.githubusercontent.com/5751863/58832756-7f956880-8604-11e9-9c74-379c5ac2a188.png)

__Actual behavior:__
![Screen Shot 2019-06-03 at 1 32 02 PM](https://user-images.githubusercontent.com/5751863/58832711-6096d680-8604-11e9-9ec3-ce5d58df7f3a.png)

**Comment by desa** [comment]
The component should display they keys from the map
