### ISSUE TITLE
Add create task from template option

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#14067]
Tasks are fully template-able, and can be saved as a template. 

- [x] Add create from template option to add task dropdown 
- [x] Enable create from template option to the empty state in task list page
- [x] Add create from template overlay to task list page which displays only task templates (see https://github.com/influxdata/influxdb/issues/14116)

- [x] This issue might need us to converge upon a method to differentiate template types when we only have their summaries available. currently "type" is in the template data and not meta. We had discussed using labels for this purpose previously. @jademcgough @OfTheDelmer. Currently we are displaying all templates regardless of their type- so user may see a task template when they are trying to create a dashboard from template. not great. See https://github.com/influxdata/influxdb/issues/14081 for discussion

**Comment by OfTheDelmer** [comment]
In the UI labels are mostly used as a filtering term. If it isn’t too prohibitive to filter labeled resources in the API by label name(s) I think it could work for template type filtering. 

However, I don’t think the label names need to be the only way to filter resources. Having a template type in the template meta feels less surprising than putting it into a label.

**Comment by ebb-tide** [comment]
all templates are now created with their type information available in the meta parameter. This issue is straightforward and ready to go

**Comment by desa** [comment]
seems done
