### ISSUE TITLE
Decide on strategy for tracking which template a resource was created from. ie "templates as code"

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#14082]
Currently there is no link between a resource and the template it was created from. We need some method of tracking this relationship in order to:

1. Allow users to manage their templates as code and version control a template. Q: Would we expose a way for them to auto update the resources that have been instantiated from the template? 
1. Potentially display an alert on a resource (ie dashboard) when the template it was created from has a new version available
1. Potentially be able to determine whether a resource (ie dashboard) has already been instantiated from a template and avoid re-creating it when adding the same telegraf plug-in for example. 
1. Potentially give user option of removing linked resources when deleting a primary resource that was created from a template. (delete dashboard with templateID:2 can give user option of deleting variable/ labels that were also created with templateID:2)

Concerns/Requirements:
- There needs to be an ID on resources which indicates the template they have been created from. This id can't be linked to the name of the template as that can be changed by user, it can't be the resource ID of the template since that is unique to the system the template exists on. can be empty/null if resource was not created from a template. 
- I can't think of a way for us to 'update' a resource with updated template. We may need to delete stale resource, then re instantiate the template. Q: what do we do with associated resources? can we confidently delete the variables / labels that were instantiated with a dashboard template knowing that they will be re created with the new template? What if the re-creation fails and the deleted resources were being used in other resources? Perhaps this can be solved by exposing an "are you sure?" warning which exposes the list of resources that will be effected by update.

**Comment by ebb-tide** [comment]
I see one way of accomplishing this: 
- add new `templateID` field to template meta, 
- every resource (labels, variables, tasks, dashboard..) that is instantiated from this template is assigned this templateID. 
- templateID is a queryable parameter- and FE can make a request for all resources which have a specific templateID.

**Comment by bthesorceror** [comment]
Infomation that I think that would be help for a template
- `templateID` we generate that is unique to the template
- `version` which we already have

Information that should be stored on the dashboard
- `templateID` points to the template it originated from, if any
- `templateVersion` point to the template version at time of creation

With this information I think we can provide effective lineage and this also give us the ability to provide a upgrade path for template, especially static templates.

**Comment by ebb-tide** [comment]
We should also be upgrading template versions as we make changes to templates going forward.

**Comment by ebb-tide** [comment]
This strategy will be implemented by : 
https://github.com/influxdata/influxdb/issues/14100
https://github.com/influxdata/influxdb/issues/14101
https://github.com/influxdata/influxdb/issues/14102
