### ISSUE TITLE
Slow query builder reload on date change

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#14096]
It seems weird to hide all the selections and show loading again for the query builder after changing a time range. It's nice that it remembers my selection but it still looks weird.

![query_builder_time_change_reload](https://user-images.githubusercontent.com/5751863/59216838-66933700-8b71-11e9-8399-d4bc9a19b904.gif)

**Comment by chnn** [comment]
We do need to reload each filter card when the date range is changed, since the date range is used in the metaqueries for each card.

Perhaps there is a less noisy loading state we can use.
