### ISSUE TITLE
Notes Display wrong in gauges 

### ISSUE THREAD

**Issue by davidgs** [influxdata/influxdb#14110]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a gauge
2. add a note
3. make sure there is no data for the gauge.

__Expected behavior:__
Describe what you expected to happen.
Should be able to read the note.
__Actual behavior:__
Note text and title of the gauge overlap. Most noticeable if you have no formatting, but even with heading level 1 and bold text, it overlaps.
__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Influx 2.0 alpha 11
![Gauge-note](https://user-images.githubusercontent.com/2071898/59288188-2ac7a280-8c41-11e9-9097-3c94b7c7ae92.gif)

![gauge-note2](https://user-images.githubusercontent.com/2071898/59288284-74b08880-8c41-11e9-933c-4474585fada7.gif)

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by desa** [comment]
not an issue anymore
