### ISSUE TITLE
Upgrade clockface

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#14125]
I tried to upgrade @influxdata/clockface from 0.0.13 to 0.0.14 to make use of the new checkbox input, but experienced some visual oddities:

![clockface](https://user-images.githubusercontent.com/638955/59392691-68095e80-8d2d-11e9-9e02-660087c608af.gif)

The scrollbars in the query builder are in the wrong place and the checkbox appears to be using some sort of absolute positioning. I'm not sure what else throughout the UI needs attention.

**Comment by alexpaxton** [comment]
Some of the funkiness comes from conflicts between local styles and clockface styles

**Comment by chnn** [comment]
@alexpaxton what do you think about prefixing all the clockface styles (either the influxdb or clockface repo ones) with a special namespace so that we don't have to upgrade all at once?

**Comment by alexpaxton** [comment]
@chnn dude that’s genius!!

**Comment by alexpaxton** [comment]
Closed via https://github.com/influxdata/influxdb/pull/14458
