### ISSUE TITLE
influxdb2 unauthorized error 

### ISSUE THREAD

**Issue by DemoLiang** [influxdata/influxdb#14127]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. I'm used influxdb v2.0.0 and org=prometheus; bucket=prometheus; token=XXXXX
2. prometheus v2.7.0
I'm config the prometheus remote_write and remote_read:
remote_write:

url: "http://30.23.4.174:9999/api/v2/write?org=prometheus&bucket=prometheus&precision=s"
bearer_token: "XXXXX"
remote_read:

url: "http://30.23.4.174:9999/api/v2/read?org=prometheus&bucket=prometheus&precision=s"
bearer_token: "XXXXX"
3. but prometheus log is :
err="server returned HTTP status 401 Unauthorized:{"code":"unauthorized","message":"unauthorized access"}"

4. I'm try it by curl ,that token is ok
curl "http://30.23.4.174:9999/api/v2/write?org=prometheus&bucket=prometheus&precision=s" --header "Authorization: Token XXXXX" --data "mem,host=host1 used_percent=23 1560324751"

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by DemoLiang** [comment]
because prometheus use bearer token not "Authorization: Token XXXXX"  ,So now prometheus can no longer use influxdb2

**Comment by sanderson** [comment]
@DemoLiang Our API team is in the process of vetting the potential for supporting both the Bearer and Token auth schemas.

**Comment by rhajek** [comment]
We have prepared pull request https://github.com/micrometer-metrics/micrometer/pull/1423 to micrometer.io framework with InfluxDB 2 support. Before it will be merged we need to be sure that authorization API (using proprietary “token” header) will be supported in future.

**Comment by russorat** [comment]
Even if we added the Bearer support, I think Prometheus would need to be updated to understand the new data format for reading and writing to InfluxDB 2.0.

**Comment by aeciopires** [comment]
Hello

I have the same problem. I used InfluxDB 2.0.0 beta and Prometheus 2.15.x.

I would like a prevision for this solution. :-)

Thank you for job with InfluxDB 2... The interface web is beautiful.

**Comment by timhallinflux** [comment]
The remote write API has not yet been implemented.

**Comment by mveroone** [comment]
> The remote write API has not yet been implemented. We are discussing our Q2 plans at the moment. There is an outstanding issue that we are aware of, even if we enable the remote write API...which is related to NaN and +/- INF. These will not be initially supported.
> 
> We are looking for feedback about how big an issue this is for our user base. I'm sure for some users/use cases it will be an issue given #4089 But, looking for some pointers about how pervasive this issue is for the community.

Hi.
We were about to look into the use of InfluxDB as a downscaling-capable remote storage for prometheus.
The inability of using remote write/read capabilities with InfluxDB 2.0 prevents us from moving towards this goal.

So I'd say it's a pretty useful feature.

**Comment by timhallinflux** [comment]
@mveroone use InfluxDB 1.8.x in the meantime?

**Comment by mveroone** [comment]
Sure, that's my plan, but you seemed to ask for use cases to decide whether it was worth the effort, so I thought I'd chip in.
And I gotta say, whether it's its GUI or its CLI, InfluxDB 2.0 is way sexier than 1.x. (Congrats on that !)

**Comment by hildebrandttk** [comment]
> > The remote write API has not yet been implemented. We are discussing our Q2 plans at the moment. There is an outstanding issue that we are aware of, even if we enable the remote write API...which is related to NaN and +/- INF. These will not be initially supported.
> > We are looking for feedback about how big an issue this is for our user base. I'm sure for some users/use cases it will be an issue given #4089 But, looking for some pointers about how pervasive this issue is for the community.
> 
> Hi.
> We were about to look into the use of InfluxDB as a downscaling-capable remote storage for prometheus.
> The inability of using remote write/read capabilities with InfluxDB 2.0 prevents us from moving towards this goal.
> 
> So I'd say it's a pretty useful feature.

I have a similar setup. Prometheus for alerting based on now and aggregations over the last week. InfluxDB for Dashboards and long term analysis.

**Comment by cheatmenot** [comment]
Hello, we are experimenting with influxdb2 and prometheus. +1 to implement remote write api.

**Comment by mveroone** [comment]
(Note : since our main reason to use influx was to use its Downsampling features, we moved to using Thanos.io instead)

**Comment by timhallinflux** [comment]
our plan is to add prometheus remote write support to Telegraf: https://github.com/influxdata/telegraf/issues/9165

**Comment by prab2014** [comment]
+1, why Prometheus is not able to do remote write to influxdb2.0?
How come a new version have not feature the existing flow. 
correct me if we still can use prometheus remote read/write with influx 2.0.

**Comment by xxj123go** [comment]
can use remote_write with influxdb2.0,but some error in influxdb's log ,like this(and no data in measurement):
```sh
2021-06-03T14:21:24.235355Z     error   Error parsing points    {"error": "unable to parse '\ufffd\t\ufffd^': missing fields\nunable to parse '\ufffd\u0001': missing fields\nunable to parse '4': missing fields\nunable to parse '\u0008__name__\u0012(prometheus_engine_query_duration_seconds': missing fields\nunable to parse '\u0015': missing fields\nunable to parse '\u0004host\u0012\r10.204.11.124': missing fields\nunable to parse '\u001e': missing fields\nunable to parse '\u0008instance\u0012\u00121.
```

**Comment by lesam** [comment]
Prometheus remote_write now works with influxdb2.0, see https://github.com/influxdata/influxdb/issues/17958 and [this blog post](https://www.influxdata.com/blog/prometheus-remote-write-support-with-influxdb-2-0/).

There is an open issue for remote_read: https://github.com/influxdata/influxdb/issues/20519

Closing this issue as a duplicate. @xxj123go if you are still seeing errors on the latest influxdb I recommend opening a new issue for that specifically.
