### ISSUE TITLE
InfluxDB 2 - Telegraf Config URL should be configurable

### ISSUE THREAD

**Issue by ShakataGaNai** [influxdata/influxdb#14122]
__Proposal:__
The InfluxDB2 GUI generates URL's for Telegraf configs. The base URL should be configurable.

__Current behavior:__
InfluxDB2 generates a URL based on some magic.

__Desired behavior:__
Generate based on magic OR generate URL based on passed configuration/environmental variable.

__Alternatives considered:__
None

__Use case:__
The current assumption in design is that InfluxDB2 will be "access(ed) over local ip". We should be able to provide our own information as the InfluxDB2 instance may be behind a proxy. It may be behind a loadbalancer. The user may prefer using DNS resolution. The automagic detection may fail.

**Comment by nisley** [comment]
I just confirmed that the http-bind-address startup option should achieve what you're looking for.
On my mac:
>bin/darwin/influxd --http-bind-address "MBP13-NISELY.local:9999"

https://v2.docs.influxdata.com/v2.0/reference/config-options/#http-bind-address
