### ISSUE TITLE
Indian Time zone (IST)

### ISSUE THREAD

**Issue by rguptarg** [influxdata/influxdb#14137]
We are using below query but time is showing in UTC, 

influx -precision rfc3339 -execute="SELECT last("Percent_Idle_Time") FROM "win_cpu" WHERE (time >= now() - 15d) GROUP BY IP,host,customer" -database=telegraf -format=csv

How can i get output in Indian Timezone (GMT+5:30)

If We have used another precision, it's give error.

**Comment by vineetvdubey** [comment]
Not tested, but I think you need to add something like **TZ('Asia/Kolkata')** after the group by:

`influx -precision rfc3339 -execute="SELECT last("Percent_Idle_Time") FROM "win_cpu" WHERE (time >= now() - 15d) GROUP BY IP,host,customer TZ('Asia/Kolkata')" -database=telegraf -format=csv`

**Comment by rguptarg** [comment]
Thanks 
its helpful

**Comment by nisley** [comment]
Closing for now as it looks like the tip solved your issue. Let us know if I'm incorrect.
