### ISSUE TITLE
Create simple controller for 1.x Flux

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#14161]
The controller was removed from Flux. This means that we need to create a simple implementation of the controller for 1.x

See this branch `chore/update-flux-0.33.0` for a starting point.

**Comment by nathanielc** [comment]
See https://github.com/influxdata/influxdb/commit/0f997d53c0b839fbb7655555b3070875135f5f87 for what needs to change in part.

**Comment by jsternberg** [comment]
I think the decision was just to compile the program and call start on it so I'm going to close this issue since that is done now.
