### ISSUE TITLE
BUG : Tags and Series does not create

### ISSUE THREAD

**Issue by StephaneDci** [influxdata/influxdb#14172]
## Tag and series creation issues on InfluxDb 1.5.2
It seems to be a bug on tag and series Creation:

**Comment by StephaneDci** [comment]
### Another Metric exemple

```
system,environnement=DEMO1,host=DDM-DEMO1-ORA1,projet=DDM,role=ORA uptime=755101i 1561110840000000000
```

### Data are indexed

```
select count(*) from system where projet='DDM' and role='ORA' and environnement='DEMO1' and time > now() - 30m

{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "system",
                    "columns": [
                        "time",
                        "count_load1",
                        "count_load15",
                        "count_load5",
                        "count_n_cpus",
                        "count_n_users",
                        "count_uptime",
                        "count_uptime_format"
                    ],
                    "values": [
                        [
                            "2019-06-21T10:01:05.852317023Z",
                            29,
                            29,
                            29,
                            29,
                            29,
                            29,
                            29
                        ]
                    ]
                }
            ]
        }
    ]
}
```

### Tags: ORA is missing  :

```
show tag values on telegraf WITH KEY IN (projet, role, environnement)  WHERE projet = 'DDM' 

     (....)
                {
                    "name": "system",
                    "columns": [
                        "key",
                        "value"
                    ],
                    "values": [
                        [
                            "environnement",
                            "DEMO1"
                        ],
                        [
                            "projet",
                            "DDM"
                        ],
                        [
                            "role",
                            "WBS"
                        ],
                        [
                            "role",
                            "WEB"
                        ]
                    ]
                }
	(....)				

```

### Series : ORA is missing

```
 show series  from system where projet = 'DDM'

{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "columns": [
                        "key"
                    ],
                    "values": [
                        [
                            "system,environnement=DEMO1,host=DDM-DEMO1-WBS1,projet=DDM,role=WBS"
                        ],
                        [
                            "system,environnement=DEMO1,host=DDM-DEMO1-WEBSPHERE1,projet=DDM,role=WEB"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by StephaneDci** [comment]
[SHOW DIAGNOSTIC.txt](https://github.com/influxdata/influxdb/files/3320338/SHOW.DIAGNOSTIC.txt)

**Comment by StephaneDci** [comment]
I am not sure if this is a good new but after restarting the InfluxDB's service, series have been created.
Not sure where the bug could be ...

```
 show series  from system where projet = 'DDM'
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "columns": [
                        "key"
                    ],
                    "values": [
                        [
                            "system,environnement=DEMO1,host=DDM-DEMO1-ORA1,projet=DDM,role=ORA"
                        ],
                        [
                            "system,environnement=DEMO1,host=DDM-DEMO1-WBS1,projet=DDM,role=WBS"
                        ],
                        [
                            "system,environnement=DEMO1,host=DDM-DEMO1-WEBSPHERE1,projet=DDM,role=WEB"
                        ],
                        [
                            "system,environnement=PERF1,host=DDM-PERF1-ORA1,projet=DDM,role=ORA"
                        ],
                        [
                            "system,environnement=SINT1,host=DDM-SINT1-ORA1,projet=DDM,role=ORA"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by StephaneDci** [comment]
By the way no error in the log, no message saying that 100 000 series have been reached.
Nothing strange in the SHOW STATS output.

**Comment by Judunet** [comment]
Hi, 
I think i have a similar problem. 
I don't get all hostname tag in a measurement when i launch a SHOW TAG VALUE query:

SHOW TAG VALUES from system WITH KEY IN (host) WHERE environnement = 'PROD' AND projet = 'MSM'
   
>               
                       [
                            "host",
                            "MSM-PROD-CCH1"
                        ],
                        [
                            "host",
                            "MSM-PROD-CCH2"
                        ],
                        [
                            "host",
                            "MSM-PROD-CCH3"
                        ],
                        [
                            "host",
                            "MSM-PROD-CCH4"
                        ]

Here, i have 4 host.


But when i launch a select query to get all results:
select last(*) from system where time > (now() - 1h) and projet = 'MSM' AND role = 'CCH' AND environnement = 'PROD' GROUP BY host

>
                {
                    "name": "system",
                    "tags": {
                        "host": "MSM-PROD-CCH1"
                    },
                    "columns": [
                        "time",
                        "last"
                    ],
                    "values": [
                        [
                            "2019-06-28T08:18:00Z",
                            29708390
                        ]
                    ]
                },
                {
                    "name": "system",
                    "tags": {
                        "host": "MSM-PROD-CCH2"
                    },
                    "columns": [
                        "time",
                        "last"
                    ],
                    "values": [
                        [
                            "2019-06-28T08:18:00Z",
                            29706524
                        ]
                    ]
                },
                {
                    "name": "system",
                    "tags": {
                        "host": "MSM-PROD-CCH3"
                    },
                    "columns": [
                        "time",
                        "last"
                    ],
                    "values": [
                        [
                            "2019-06-28T08:18:00Z",
                            29706536
                        ]
                    ]
                },
                {
                    "name": "system",
                    "tags": {
                        "host": "MSM-PROD-CCH4"
                    },
                    "columns": [
                        "time",
                        "last"
                    ],
                    "values": [
                        [
                            "2019-06-28T08:18:00Z",
                            29706426
                        ]
                    ]
                },
                {
                    "name": "system",
                    "tags": {
                        "host": "MSM-PROD-CCH5"
                    },
                    "columns": [
                        "time",
                        "last"
                    ],
                    "values": [
                        [
                            "2019-06-28T08:18:00Z",
                            29706342
                        ]
                    ]
                },
                {
                    "name": "system",
                    "tags": {
                        "host": "MSM-PROD-CCH6"
                    },
                    "columns": [
                        "time",
                        "last"
                    ],
                    "values": [
                        [
                            "2019-06-28T08:18:04Z",
                            29708398
                        ]
                    ]

I have 6 hosts.
