### ISSUE TITLE
tsm.bad files after restart

### ISSUE THREAD

**Issue by pfory** [influxdata/influxdb#14180]
Hi,
after restart influx many of tsm files are renamed to tsm.bad and data from this files is missing. 
If I renamed the file back to .tsm and run influx_inspect report -detailed file it seems to be ok.

DB       RP      Shard   File                    Series  New (est) Min Time             Max Time             Load Time
telegraf autogen 82      000002394-000000002.tsm 451     451       2018-08-27T00:00:00Z 2018-09-02T23:59:52Z 34.773045ms

Summary:
  Files: 1
  Time Range: 2018-08-27T00:00:00Z - 2018-09-02T23:59:52Z
  Duration: 167h59m52s

Statistics
  Series:
     - telegraf (est): 451 (100%)
  Total (est): 451

  Measurements (est):
    - cpu: 20 (4%)
    - disk: 14 (3%)
    - diskio: 72 (15%)
    - dns_query: 7 (1%)
    - kernel: 5 (1%)
    - maximalni_teplota_1d: 1 (0%)
    - mem: 12 (2%)
    - minimalni_teplota_1d: 1 (0%)
    - mqtt: 114 (25%)
    - net: 92 (20%)
    - net_response: 5 (1%)
    - ping: 80 (17%)
    - processes: 11 (2%)
    - prumerna_teplota_1d: 1 (0%)
    - prumerna_teplota_30m: 1 (0%)
    - srazky_1d: 1 (0%)
    - srazky_1h: 1 (0%)
    - swap: 6 (1%)
    - system: 7 (1%)

  Fields (est):
    - cpu: 10
    - disk: 7
    - diskio: 9
    - dns_query: 2
    - kernel: 5
    - maximalni_teplota_1d: 1
    - mem: 12
    - minimalni_teplota_1d: 1
    - mqtt: 1
    - net: 92
    - net_response: 3
    - ping: 8
    - processes: 11
    - prumerna_teplota_1d: 1
    - prumerna_teplota_30m: 1
    - srazky_1d: 1
    - srazky_1h: 1
    - swap: 6
    - system: 7

  Tags (est):
    - cpu: 2
    - device: 2
    - domain: 1
    - fstype: 2
    - host: 1
    - interface: 2
    - mode: 1
    - name: 8
    - path: 2
    - port: 1
    - protocol: 1
    - record_type: 1
    - result: 3
    - server: 3
    - topic: 114
    - url: 10
Completed in 44.785089ms

Regards Peter

**Comment by dgnorton** [comment]
@pfory what version of InfluxDB?

**Comment by pfory** [comment]
1.7.6 run on Raspberry Pi model B Plus Rev 1.3

**Comment by pfory** [comment]
Any news?

**Comment by pfory** [comment]
I tried install influx on W10 machine and copy data files to this installation and it works well. No bad tsm files anymore.
I think problem on Raspberry is caused by insufficient memory. But influx have run there for months without problems.

**Comment by dgnorton** [comment]
@pfory thanks for the extra info. Were you running an older version of InfluxDB before for months that did not experience this problem? If so, what version?

**Comment by pfory** [comment]
Influx run on same version for a few month. No HW change, no SW change.

**Comment by dgnorton** [comment]
@pfory you mentioned that you think it might be caused by insufficient memory.
* How much RAM does it have?
* Are you using `inmem` or `tsi` index? If you're currently using `inmem`, maybe try `tsi`.

**Comment by pfory** [comment]
It has 1GB RAM
I tried index-version="tsi1" but same result.

**Comment by jeronimo** [comment]
Just noticed that about a month worth of data is missing from one of databases.

<img width="451" alt="Screenshot 2022-04-11 at 09 18 12" src="https://user-images.githubusercontent.com/88912/162774416-b3f1fcf0-b4cb-44bc-a844-e26c9b9e7f66.png">

Running on `Raspberry Pi 4 4GB`
`Raspbian GNU/Linux 10 (buster)`
`InfluxDB shell version: 1.6.4`

Shards are there:
```name: smartshunt
id  database   retention_policy shard_group start_time           end_time             expiry_time          owners
--  --------   ---------------- ----------- ----------           --------             -----------          ------
356 smartshunt autogen          356         2021-11-08T00:00:00Z 2021-11-15T00:00:00Z 2021-11-15T00:00:00Z 
360 smartshunt autogen          360         2021-11-15T00:00:00Z 2021-11-22T00:00:00Z 2021-11-22T00:00:00Z 
370 smartshunt autogen          370         2021-11-22T00:00:00Z 2021-11-29T00:00:00Z 2021-11-29T00:00:00Z 
380 smartshunt autogen          380         2021-11-29T00:00:00Z 2021-12-06T00:00:00Z 2021-12-06T00:00:00Z 
390 smartshunt autogen          390         2021-12-06T00:00:00Z 2021-12-13T00:00:00Z 2021-12-13T00:00:00Z 
400 smartshunt autogen          400         2021-12-13T00:00:00Z 2021-12-20T00:00:00Z 2021-12-20T00:00:00Z 
410 smartshunt autogen          410         2021-12-20T00:00:00Z 2021-12-27T00:00:00Z 2021-12-27T00:00:00Z 
420 smartshunt autogen          420         2021-12-27T00:00:00Z 2022-01-03T00:00:00Z 2022-01-03T00:00:00Z 
430 smartshunt autogen          430         2022-01-03T00:00:00Z 2022-01-10T00:00:00Z 2022-01-10T00:00:00Z 
440 smartshunt autogen          440         2022-01-10T00:00:00Z 2022-01-17T00:00:00Z 2022-01-17T00:00:00Z 
450 smartshunt autogen          450         2022-01-17T00:00:00Z 2022-01-24T00:00:00Z 2022-01-24T00:00:00Z 
460 smartshunt autogen          460         2022-01-24T00:00:00Z 2022-01-31T00:00:00Z 2022-01-31T00:00:00Z 
470 smartshunt autogen          470         2022-01-31T00:00:00Z 2022-02-07T00:00:00Z 2022-02-07T00:00:00Z 
480 smartshunt autogen          480         2022-02-07T00:00:00Z 2022-02-14T00:00:00Z 2022-02-14T00:00:00Z 
490 smartshunt autogen          490         2022-02-14T00:00:00Z 2022-02-21T00:00:00Z 2022-02-21T00:00:00Z 
500 smartshunt autogen          500         2022-02-21T00:00:00Z 2022-02-28T00:00:00Z 2022-02-28T00:00:00Z 
510 smartshunt autogen          510         2022-02-28T00:00:00Z 2022-03-07T00:00:00Z 2022-03-07T00:00:00Z 
520 smartshunt autogen          520         2022-03-07T00:00:00Z 2022-03-14T00:00:00Z 2022-03-14T00:00:00Z 
530 smartshunt autogen          530         2022-03-14T00:00:00Z 2022-03-21T00:00:00Z 2022-03-21T00:00:00Z 
540 smartshunt autogen          540         2022-03-21T00:00:00Z 2022-03-28T00:00:00Z 2022-03-28T00:00:00Z 
550 smartshunt autogen          550         2022-03-28T00:00:00Z 2022-04-04T00:00:00Z 2022-04-04T00:00:00Z 
560 smartshunt autogen          560         2022-04-04T00:00:00Z 2022-04-11T00:00:00Z 2022-04-11T00:00:00Z 
570 smartshunt autogen          570         2022-04-11T00:00:00Z 2022-04-18T00:00:00Z 2022-04-18T00:00:00Z
```


But went to files directly it was like that:
```
-rw-r--r--  1 influxdb influxdb 15667654 Mar 20 23:10 000000003-000000002.tsm.bad
-rw-r--r--  1 influxdb influxdb      109 Apr 11 10:19 fields.idx
```

Any way to fix it?
