### ISSUE TITLE
Flux endpoint does not require authentication

### ISSUE THREAD

**Issue by xPaw** [influxdata/influxdb#14192]
Version: 1.7.1

I was playing around with the new flux endpoint and it appears to not require authentication even though it is enabled.

```
  flux-enabled = true
  auth-enabled = true
```

It responds with `no database` when I specify an invalid database, and hangs the request (I probably didn't write a correct query) when I request an existing database.

It's also parsing the queries in it's entirely and returns any errors in the parsing, even though it should check the authentication as the first thing and drop the request.

I did verify that `/query` and `/write` endpoints do actually need authentication: `{"error":"unable to parse authentication credentials"}`

EDIT: I probably should have created this issue in influxdb repo.

**Comment by nathanielc** [comment]
@stuartcarnie I believe this is fixed in recent 1.x versions? Can you confirm?

**Comment by stuartcarnie** [comment]
According to changelog, version 1.7.3 https://github.com/influxdata/influxdb/blob/1.7/CHANGELOG.md
