### ISSUE TITLE
Cannot create an auth associated with another user

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb#14202]
__Steps to reproduce:__

```
	m.adminService := http.NewService(host, adminToken)

	// Get or create authorization
	authorizations, _, err := m.adminService.FindAuthorizations(ctx, influxdb.AuthorizationFilter{OrgID: &org.ID, UserID: &user.ID})
	if isErrNotFound(err) || len(authorizations) == 0 {
		err = m.adminService.CreateAuthorization(ctx, &influxdb.Authorization{
			Description: "capacity planning authorization",
			OrgID:       org.ID,
			UserID:      user.ID,
			Permissions: []influxdb.Permission{
				{
					Action: influxdb.WriteAction,
					Resource: influxdb.Resource{
						Type:  influxdb.BucketsResourceType,
						OrgID: &org.ID,
					},
				},
				{
					Action: influxdb.ReadAction,
					Resource: influxdb.Resource{
						Type:  influxdb.BucketsResourceType,
						OrgID: &org.ID,
					},
				},
			},
		})
```

__Expected behavior:__

I expect a new authorization (orgID, userID, permissions) where userID is the one I pass via `influxdb.Authorization.UserID`

__Actual behavior:__

I get a new authorization with the userID associated with `adminToken` (the token used for the request). The userID is [overwritten here](https://github.com/influxdata/influxdb/blob/c35c15f54da6278642b87fd6f6f0f9903d52f50c/http/auth_service.go#L197)

__Environment info:__

* System info: MacOS recent
* InfluxDB version: alpha 13

__Config:__
"all access user" created with `influx setup`

**Comment by jademcgough** [comment]
Users can't create authorizations for other users, currently. That `userID` is meant to be read-only, and set from the token passed in the request.

It should be fine to allow org owners to create authorizations for their org members.

**Comment by jacobmarble** [comment]
To clarify, the "admin user" (referring to the user created with `influx setup`) should be allowed to create an auth for any org in the influxdb instance.
