### ISSUE TITLE
Read data from one DB and insert it into another DB

### ISSUE THREAD

**Issue by hackertron** [influxdata/influxdb#14214]
How can one read data from one database and export/write it to another database ? 

for example : i have a database from where i read the data and i get the results in JSON **( using HTTP API )** like this
```JSON
{
    "results": [
        {
            "series": [
                {
                    "name": "temperature",
                    "columns": [
                        "time",
                        "country",
                        "humidity",
                        "value",
                        "zipcde"
                    ],
                    "values": [
                        [
                            1561641363358993903,
                            "usa",
                            10,
                            75,
                            "94107"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

how can i use this JSON result and import/read it into another database

**Comment by russorat** [comment]
could you add the influxdb version you are using?

**Comment by hackertron** [comment]
i am using inlfux 1.7.x

**Comment by toni-moreno** [comment]
Hi @hackertron , perhaps "syncflux" could help you.

https://github.com/toni-moreno/syncflux#run-as-a-database-replication-tool

You can copy data from one db to another online both online, choosing measurements if you need only a subset of your data.
