### ISSUE TITLE
Ensure comma character is escaped when producing file for by "Download CSV"

### ISSUE THREAD

**Issue by nisley** [influxdata/influxdb#14236]
https://github.com/influxdata/chronograf/issues/5170

Fields containing comma character should be escaped in the file produced by "Download CSV"

**Comment by ebb-tide** [comment]
flux correctly wraps string fields that contain commas in quotes, which allows inline commas to be differentiated from delimiter commas, the UI downloads flux responses as they are returned.  I'm adding a test to ensure we prevent this behavior from breaking
