### ISSUE TITLE
Memory leak on submitting flux script without time unit

### ISSUE THREAD

**Issue by R290** [influxdata/influxdb#14251]
__Steps to reproduce:__

1. Setup docker container of `Version 2.0.0 (1e461ad)` and create user, org and bucket
2. Choose quick-start option so default scraper is created
3. Submit the following flux query with a missing time unit via the Data Explorer:
```
from(bucket: "testBucket")
  |> range(start: -1)
  |> filter(fn: (r) => r._measurement == "influxdb_buckets_total")
  |> aggregateWindow(every: 1m, fn: mean)
```

Without the `aggregateWindow` no memory leak occurs.

__Expected behavior:__
An error regarding the missing time unit or similar to without using `aggregateWindow` and no significant increase in memory usage.

__Actual behavior:__
Rapid increase in memory usage requiring container restart.

__Environment info:__

* System info: `Linux 4.15.0-54-generic x86_64` (Docker container)
* Docker image version:
```
"RepoDigests": [
            "quay.io/influxdb/influxdb@sha256:bda1192d1a3bbf1c37254019e55fcd85a0486fe50a812196f334cc111a8b6c1f"
        ],
```

__Config:__
Default config.

__Logs:__
No errors in log.

__Performance:__
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/3355095/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/influxdb/files/3355096/vars.txt)
Let me know if `iostat` is needed.

**Comment by sanderson** [comment]
This issue should probably be transferred to or mentioned in an issue on the [Flux repo](https://github.com/influxdata/flux).

I believe what's happening is that the start parameter expects a duration or an absolute time and it's parsing `-1` as an absolute time (`1969-12-31T23:59:59.999999999Z`). So the range you're pulling is actually quite large and windowing everything will consume a lot of memory.

I'm not sure what the best solution is here. Maybe some type of warning about large time ranges?

**Comment by R290** [comment]
To confirm your hypothesis I ran the same script with a different `aggregateWindow`of `1y`:

```
from(bucket: "testBucket")
  |> range(start: -1)
  |> filter(fn: (r) => r._measurement == "influxdb_buckets_total")
  |> aggregateWindow(every: 1y, fn: mean)
```

The memory usage is negligible and the time domain does indeed start at `1969-12-31T23:59:59Z`.
No unit seems to default to absolute seconds.

Similarly setting `createEmpty: false` also avoids the issue:

```
from(bucket: "testBucket")
  |> range(start: -1)
  |> filter(fn: (r) => r._measurement == "influxdb_buckets_total")
  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)
```

From the Flux repo the related issue seems to be: https://github.com/influxdata/flux/issues/1243
I'm closing this issue since it's unrelated to this repo.
