### ISSUE TITLE
Double string quote ("") in csv response

### ISSUE THREAD

**Issue by vspinu** [influxdata/influxdb#14275]
Quotes within strings are duplicated in csv responses.

__Steps to reproduce:__

1. 

```
create database tmp
use database tmp
insert metric value="contain a quote \"."
```
2. 
```
~$ curl -H "Accept: application/csv" --data-urlencode "q=select * from tmp..metric" -G "http://localhost:8086/query"
name,tags,time,value
metric,,1562534134557951956,"contain a quote ""."
```

__Environment info:__

```
~$ uname -srm
Linux 4.18.0-25-generic x86_64
~$ influxd version
InfluxDB v1.7.6 (git: 1.7 01c8dd416270f424ab0c40f9291e269ac6921964)
```

**Comment by lovasoa** [comment]
I don't think this is a bug. This is the standard way to represent double quotes in [CSV](https://en.wikipedia.org/wiki/Comma-separated_values#Standardization).

> If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.
> [RFC 4180](https://tools.ietf.org/html/rfc4180)

**Comment by vspinu** [comment]
Thanks. That means it's my parser's bug then.
