### ISSUE TITLE
Add new alerting routes

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#14288]
Add Alerting section to left nav panel, and associated routes that render an (empty for now)alerting page. 
Ensure that Nav Panel is highlighted as expected when user is on alerting page. 

![Screen Shot 2019-07-09 at 11.04.05 AM.png](https://images.zenhubusercontent.com/5cfab3d5b261421fbae0e39b/c100c3f7-ebaa-42e9-8f5b-e335ddf65c62)

**Comment by chnn** [comment]
We should make sure to feature flag this, so that we can still deploy the UI while this epic is in progress.
