### ISSUE TITLE
Do not highlight invalid comment blocks

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#14294]
C style multi-line comments `/* */` are not valid in Flux, the UI editor highlights them as if they were causing confusion.

**Comment by russorat** [comment]
Something we might be able to fix when we switch to the monaco editor.

**Comment by desa** [comment]
Remove comment style from regex in code mirror

**Comment by russorat** [comment]
bump. this might be fixed with the move to monaco? #16003

**Comment by desa** [comment]
looks fixed to me
