### ISSUE TITLE
Line protocol RAW socket

### ISSUE THREAD

**Issue by vit1251** [influxdata/influxdb#14300]
I write simple C/C++ application with reporting some data and use HTTP protocol in that case a big overhead to implementation. Could you please specify how to enable Line protocol on RAW TCP socket?

**Comment by russorat** [comment]
This question would be better for https://community.influxdata.com. We like to keep github issues for bugs or feature requests.

**Comment by vit1251** [comment]
@russorat you may it cast to feature request. Right now I does not have any way to send metric without HTTP and it totally big deal for simple controller and embedded device. Another one is using OPenTSDB is not a good way (i.e. I meet with low timestamp quantity over OpenTSDB and does not implemented OpenTSDB 2.3 where timestamp may be represented as microsecond). 

I write now Golang transformation application but it take another one VM to processing metric and it totally does not good solution bcz world populate a thausend small solution for small application (I have it a lot of)
