### ISSUE TITLE
when a check is created, it generates a task

### ISSUE THREAD

**Issue by jademcgough** [influxdata/influxdb#14331]

**Comment by ebb-tide** [comment]
when a new check is created :
- [x] create check
- [ ] generate the complete flux query from check parameters
- [ ] create a new task with the complete flux query

**Comment by desa** [comment]
When looking into `create a new task with the complete flux query` I noticed that we currently don't have a reference to the task that is generated from a check. As a result I decided to split the work I did on the AST generation into a separate PR.
