### ISSUE TITLE
Text highlighting in variables modal overlaps

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14349]
Notice how the highlighted lines overlap.

![image](https://user-images.githubusercontent.com/4805997/61254415-4d098000-a719-11e9-9dc9-352da7d0aa69.png)

**Comment by desa** [comment]
Time box task to `1h`. If the issue is more involved, then punt until we get off code mirror.

**Comment by ebb-tide** [comment]
Deprioritizing awaiting switch to Monaco

**Comment by russorat** [comment]
fixed using monaco
