### ISSUE TITLE
Update map function documentation in the UI

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14350]
The example from the Map function documentation needs to be updated to work with the new flux lib: https://v2.docs.influxdata.com/v2.0/reference/flux/functions/built-in/transformations/map/

![image](https://user-images.githubusercontent.com/4805997/61254708-521aff00-a71a-11e9-8175-ba44c47e65ae.png)

**Comment by sanderson** [comment]
Ah, right. They removed the implicit column name mapping.

```js
// This old syntax:
map(fn: (r) => r._value * r._value)

// Would get parsed as:
map(fn: (r) => ({ r._value: r._value * r._value }))
```

Flux doesn't do this any more, so the example function should be updated to use the 2nd form above.
