### ISSUE TITLE
Upgrade Clockface Dependency

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#14359]
Upgrading to Clockface 0.0.16 causes some funkiness in the UI.

The presence of locally defined dropdown and dapper scrollbars components conflict with the styles coming from Clockface. The only solution I can think of is to do a sweep through the UI and ensure that all instances of Dropdowns and Dapper Scrollbars are importing from Clockface so the local components can be deleted.

**Comment by desa** [comment]
Dupe
