### ISSUE TITLE
system template dashboard queries do not include bucket

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/influxdb#14376]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. start a fresh influxdb
2. complete onboard
3. create a templated system dashboard
4. view cells are broken
5. open network tab to verify that request payload does not include `bucket`

__Expected behavior:__
See system dashboard metrics

__Actual behavior:__
![Screen Shot 2019-07-18 at 10 52 15 AM](https://user-images.githubusercontent.com/4994741/61470231-b4f4dc00-a94e-11e9-9ecf-9fb9209d83e3.png)
![Screen Shot 2019-07-18 at 11 19 00 AM](https://user-images.githubusercontent.com/4994741/61470712-86c3cc00-a94f-11e9-9226-ce8e5cece6a4.png)

__Environment info:__
- Cloud 
- local mac Darwin

**Comment by russorat** [comment]
i think this was fixed by https://github.com/influxdata/influxdb-templates/issues/4

**Comment by OfTheDelmer** [comment]
Resolved
