### ISSUE TITLE
Incorrect behavior with `SHOW SERIES EXACT CARDINALITY` / `SHOW SERIES CARDINALITY FROM ...`

### ISSUE THREAD

**Issue by adamperlin** [influxdata/influxdb#14386]
On 1.x with `tsi1`, `SHOW SERIES EXACT CARDINALITY`, as well as `SHOW SERIES CARDINALITY FROM <measurement>` returns the sum of the number of unique series for each shard, as opposed to the number of unique series __across__ all shards. This issue is actively being discussed and was filed mainly for documentation.

**Comment by ix-dev** [comment]
This would be a possible explanation why I get such high values for my series cardinality.
The command 'SHOW SERIES EXACT CARDINALITY' return 1,350,888. In contrast the command 'SHOW SERIES' return just 37,791 series. If I simply multiply the tag value count of all tags, then I get a value pretty close to the number of series returned by the 'SHOW SERIES' command. Therefore, the command 'SHOW SERIES EXACT CARDINALITY' does not return the expected value.

**Comment by adamperlin** [comment]
Update: Missed this in the first comment, but `SHOW SERIES CARDINALITY FROM <measurement>` (without the `EXACT`) also has this bad behavior.

**Comment by adamperlin** [comment]
This issue was addressed by https://github.com/influxdata/influxdb/pull/14444.
