### ISSUE TITLE
[UI - Data Explorer] Script editor - generate quantile function contains invalid parameters

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#14445]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Connect Telegraf
2. Open Data Explorer
3. Build a Query to filter a measurement e.g. CPU 
4. Open Script Editor
5. Filter for the function 'quantile'
6. Click the end of the pipeline and then click on 'quantile' - the function is added to the query 
7. (As a preliminary check ) Click submit - An error is returned 

```
error in evaluating AST while starting program: type error 6:6-6:95: function does not take a parameter ""quantile""
```
The `quantile` parameter should be `q`.  

8. After fixing the parameter click submit again. -- a second error is returned 

```
error in evaluating AST while starting program: type error 6:6-6:88: float != int
```
The compression value should be of type float 

__Expected behavior:__

That generated functions added to the pipeline should not lead to errors based on parameter naming or type mismatch. 

__Actual behavior:__
The generated function contains two errors.  The parameter 'quantile' should be 'q' and the type of the `compression` parameter should be `float`

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 4.4.0-157-generic x86_64

* InfluxDB version: Run `influxd version` and copy the output here
This is from the docker image of the nightly build.  From the docker log. 

```
ts=2019-07-25T08:08:48.943050Z lvl=info msg="Welcome to InfluxDB" log_id=0Gr2eIBl000 version=nightly commit=986f2eaa7 build_date=2019-07-23T07:13:26Z
```

* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
This is from the nightly image and uses the default config only. 

__Screenshots__
![QuantileFunctionWrongParam01](https://user-images.githubusercontent.com/25881301/61861571-85088400-aecc-11e9-860f-3ace930d6486.png)
![QuantileFunctionWrongParam02](https://user-images.githubusercontent.com/25881301/61861573-85088400-aecc-11e9-9c39-db9e7adee860.png)

**Comment by russorat** [comment]
this has been fixed.
