### ISSUE TITLE
Save as Task make To bucket optional

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14459]
as a user
when i write a flux script that already has a `to` function in it and try to save it as a task
then i would like the ability to not have the `to` function appended to the task

**Comment by desa** [comment]
Detect if there is a `to` in the flux script. If there is allow save. If not, prevent save.

**Comment by russorat** [comment]
bump

**Comment by kristinarobinson** [comment]
won't fix.  implementing flows.
