### ISSUE TITLE
Add the ability to recall the last N queries executed wherever you can write a flux query

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14456]
as a user
when i'm triaging an issue by iteratively writing queries
then i would like access to the queries that i have previously run

Users would be able to see a history of previously run queries, and be able to insert those queries in the current editor, or as a new tab. Only queries executed by the user would show up, not background meta queries. If the same query is run multiple times, it should not be inserted into the history again (even if the dates or variables are different).

This query history should be stored in the user's browser's local storage, and should only be available to that user.

See the example workflow from a user from: https://github.com/influxdata/chronograf/issues/4187#issuecomment-514805856

> To give you a sense of how much I'm looking forward to this - I was actually expecting queries to be graphed separately in a data explorer and being able to combine them into a single graph to be by exception. When I'm exploring data I generally want to run a bunch of separate queries - some saved for future use, some ad hoc - so I can understand what's appearing in various formats across various measurements in various time slices. Only once I've finished exploring would I generally bother creating a graph, let alone one that combines multiple queries. I fully realise I could be the exception here!

**Comment by jsteenb2** [comment]
would be cool to have this history in influxdb itself. Would give users some great insight into how the application is being hit without trapsing through a bunch of UI clicks 🤷‍♂

**Comment by kristinarobinson** [comment]
Will implement as part of flows.
