### ISSUE TITLE
Spike: Integrate monaco editor into Data Explorer

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#14483]
Replace codemirror with [Monaco](https://microsoft.github.io/monaco-editor/) in the UI.

This will help us integrate with the Flux language (better syntax highlighting, autocomplete etc.) more efficiently.

**Comment by alexpaxton** [comment]
I can help transition some of the styles over to work with Monaco

**Comment by russorat** [comment]
will this solve this? https://github.com/influxdata/idpe/issues/3404

**Comment by russorat** [comment]
i'd like to see this editor used anywhere there is a multi-line text box in the app including importing template text, loading line protocol, writing variables, save as variable, etc.

**Comment by russorat** [comment]
also the code examples in the client libraries page

**Comment by ebb-tide** [comment]
cons:

> The Monaco editor is not supported in mobile browsers or mobile web frameworks.

**Comment by russorat** [comment]
@ebb-tide that seems like a pretty big con. are there ways around it? maybe we fallback to a standard text box on mobile or something?

**Comment by ebb-tide** [comment]
learnings from spike here: https://hackmd.io/GnEUjoT7QyuYdCc-qlrXmQ

**Comment by russorat** [comment]
this is being tracked here: https://github.com/influxdata/influxdb/issues/15614
