### ISSUE TITLE
Create a separate view resource to hold check visualization properties

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#14512]
Checks are visualized in the VEO/Time machine even when they are not in a dashboard and attached to a cell. @chnn suggested that it might be a good idea to have a separate resource where we manage visualization specific properties associated with a check, or we will end up placing these properties on the check itself. An example of this is the dashboard query- in the original spec I had thought a check ought to have query parameter of type DashboardQuery (which contains builder config which is a visualization type concern). In this schema the view could hold Dashboard Query, and the query parameter on check could contain simply the text of the query. 
todo: 
- add ability to create a view independent from a dashboard or cell. we do not currently have a dashboard and cell independent `/views` endpoint.
- add viewID parameter to check
- create view before creating check and pass viewID to check
- if no viewID on check, revert to default view properties for check

**Comment by chnn** [comment]
👍 I for sure think we'll need this.

> - add viewID parameter to check

I think the view should have a `checkID`, not the other way around. This reflects that a check can exist without a check view, but a check view cannot exist without a check.

I think that would also invert this requirement:

> - create view before creating check and pass viewID to check
