### ISSUE TITLE
Issuing generic flux query for too much data causes error

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#14511]
We're currently hitting https://github.com/influxdata/influxdb-client-js/blob/845de2538ce0cb8dce8fe8b0fa6bf22206badcee/src/wrappers/queries.ts#L83-L85
whenever users issue a query for a very large amount of data. Ideally we should be able to handle this situation gracefully.
![russ error](https://user-images.githubusercontent.com/1477539/61905181-7636c700-aef6-11e9-9271-2bfc9657361c.png)

**Comment by chnn** [comment]
After talking with @russorat, here's the plan:

- In the cloud environment, set the limit for data received to 10MB (after decompression)
- In OSS, set the limit to be much higher (say, 150MB)
- When the limit is hit, display the partial response and a help text letting the user know they can avoid the limit by aggregating their data or selecting a smaller time window

**Comment by chnn** [comment]
Closed by #14529—let's follow up any UX polish we want in another issue.
