### ISSUE TITLE
Task structure needs to use less ambiguous time values

### ISSUE THREAD

**Issue by lyondhill** [influxdata/influxdb#14522]
We built the task system on the task struct as defined for the api:
```

type Task struct {
	ID              ID     `json:"id"`
	OrganizationID  ID     `json:"orgID"`
	Organization    string `json:"org"`
	AuthorizationID ID     `json:"authorizationID"`
	Name            string `json:"name"`
	Description     string `json:"description,omitempty"`
	Status          string `json:"status"`
	Flux            string `json:"flux"`
	Every           string `json:"every,omitempty"`
	Cron            string `json:"cron,omitempty"`
	Offset          string `json:"offset,omitempty"`
	LatestCompleted string `json:"latestCompleted,omitempty"`
	CreatedAt       string `json:"createdAt,omitempty"`
	UpdatedAt       string `json:"updatedAt,omitempty"`
}
```
Although this structure works well for the front end I believe using `string` as a timestamp makes it difficult to reason about what is actually stored in the field (unix, utc based time stamps, microseconds, nanoseconds). 
I believe we would benefit by changing all time based values to time.Time and then translating to something api friendly in http/task_service.go instead of using strings for these values on the backend.

**Comment by ebb-tide** [comment]
The frontend also struggles with enforcing a type on duration strings and timestamp strings. I for one would be open to splitting durations in to two parameters one being a number and another being one of "d"/"h"/"s"/"ns". That way we could describe it in the swagger and generated client as well.
