### ISSUE TITLE
v.windowPeriod not properly taking changes in dashboard refresh rates

### ISSUE THREAD

**Issue by samhld** [influxdata/influxdb#14535]
When doing an `every: v.windowPeriod` in a `window()`/`aggregatWindow()` function, the value is always 15 seconds, whether or not you changed the query's refresh rate.  This is true for both OSS Alpha 16 and Cloud2.0.

Image of what's happening:
![Screen Shot 2019-08-01 at 10 26 49 AM](https://user-images.githubusercontent.com/4852912/62314130-2cdefe00-b447-11e9-922f-c11c636dd93f.png)

**Comment by robcowart** [comment]
I would argue that using refresh rate to modify the duration of a window is also a problem. In addition to being completely illogical to me, it also means that the longest window is only 60s. That is still too granular for looking at something like the last 7 days.

What I would really want to see here is something like a max number of windows, as well as a minimum window duration. I could then specify a max number of 300 windows, and a minimum window duration of 30 secs. This still give me some granularity when looking at a short timespan like last 15 minutes, but is also useful a longer timespans like last 7 or 30 days.

**Comment by desa** [comment]
@robcowart really good point. I didn't notice that that was the refresh button. @samhld I think that might be the expected behavior. Although, I'm not sure how we determine window size currently. It might be using the canvas side that we use to draw the series.

**Comment by samhld** [comment]
@desa if that's the expected behavior, how would one programmatically (not hard-coded) change the group by time interval (the `windowPeriod`)?

Also, if that is somehow the expected behavior, docs say otherwise.

**Comment by chnn** [comment]
@samhld We don't use the refresh rate to determine `v.windowPeriod`, but rather the duration of time queried by the Flux script.

For example when I run this Flux script, I am querying 5 minutes of data:

```
from(bucket: "telegraf")
  |> range(start: -5m)
  |> filter(fn: (r) => r._measurement == "mem")
  |> filter(fn: (r) => r._field == "active")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
```

And so `v.windowPeriod` is substituted as `833ms`. If I change that script to query the last day of data instead:

```
from(bucket: "telegraf")
  |> range(start: -1d)
  |> filter(fn: (r) => r._measurement == "mem")
  |> filter(fn: (r) => r._field == "active")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
```

then `v.windowPeriod` is substituted as `240000ms`.

Eventually we want to take into account the size of the graph to determine how large this variable should be, but for now we are just assuming that we want ~360 points per graph.

**Comment by samhld** [comment]
@chnn fair enough but I'm still not seeing the interval change in the response data.  It's always a 15 second difference.

**Comment by chnn** [comment]
@samhld Ah, now that's definitely a bug. Thanks for catching that, it appears to have broken some time ago 😬 

Will be fixed by https://github.com/influxdata/influxdb/pull/14551.
