### ISSUE TITLE
Should update authorization be able to update permissions?

### ISSUE THREAD

**Issue by kelwang** [influxdata/influxdb#14543]
Current update authorization api only allow update status and description.

Since now we have more resource types like check, notification rule, notification end, and possible more resource types in future. Shall we allow update permissions through the API?

**Comment by russorat** [comment]
my understanding is that tokens are immutable. I will have to check with @goller when he is back what he thinks the best way to handle this would be.

**Comment by goller** [comment]
@kelwang this seems like a migration more than adding permissions via the API.

Do you think it is more than that?

**Comment by kelwang** [comment]
> @kelwang this seems like a migration more than adding permissions via the API.
> 
> Do you think it is more than that?

Yeah, i really like the migration idea.

**Comment by kelwang** [comment]
reference https://github.com/influxdata/influxdb/issues/14546
14546 is about real time session creation without migration, i feel like we have to do both.

**Comment by jademcgough** [comment]
Desa brought up a good point about this last week - it's potentially a security concern for us to add permissions without users' consent.

I think the one situation I'd be comfortable with us adding permissions post-creation is for the "superadmin" token that should have access to everything. Maybe our current permissions model is insufficient if we actually want permission roles.

**Comment by SomniVertix** [comment]
Hi - wanted to loop back on this:

Can we use @imogenkinsman 's suggestion and allow it to be updatable from the super admin user / token? We have a case where we'd like to add and remove permissions from certain tokens as the different buckets grow
