### ISSUE TITLE
Flux e2e tests with big input datasets are too slow

### ISSUE THREAD

**Issue by affo** [influxdata/influxdb#14574]
Tests with big `inData` run slow. This seems to be due to the `to` transformation.

Even if https://github.com/influxdata/influxdb/pull/14547 got merged. They still run slow.

**Comment by stuartcarnie** [comment]
@affo could you provide a specific test that demonstrates slow performance and that without `to` it is faster?

**Comment by stuartcarnie** [comment]
I've figured out the issue; PR coming that we can discuss
