### ISSUE TITLE
Memory gradually grows and some data in a static table/collection is lost.

### ISSUE THREAD

**Issue by aliberatcetin** [influxdata/influxdb#14571]
Influx version 1.7.7
Ubuntu 18.04

I am logging http responses of ~50 api endpoints with a cron job. It checks healths of urls.
5 columns in table, time and request_url is tag. 
Start up ram usage is 300mb but after ~5 hours ram usage become 5gb and more. 

I think, because of this problem, Influx is randomly deleting some data in table where i store urls.

**Comment by dgnorton** [comment]
@aliberatcetin can you post logs?
