### ISSUE TITLE
API call for shutting down influxdb instance

### ISSUE THREAD

**Issue by esperrer** [influxdata/influxdb#14588]
__Proposal:__
Adding a new administrative command for gracefully shutting down a running database instance.

__Current behavior:__
Currently to shutdown the database a CTRL-C signal has to be sent to the database process.
This is problematic if the database is controlled by another process (especially under Windows). 

__Desired behavior:__
It would be more suitable, to have some administrative command (e.g. SHUTDOWN) and not to depend on signals for process control of the database (as most other database products provide such functionality).  

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Currently we have an application that manages (startup/shutdown/restart) the influxd process, i.e. influxd is started when our application starts and is stopped when our application stops. Whereas the startup is straight forward, the shutdown is problematic due to signal handling issues (especially under Windows). This is not a problem with other databases. 
We are currently using version 1.7 of InfluxDB.

Thanks in advance for your consideration. 
Ewald Sperrer

**Comment by romen-h** [comment]
I also have a need for this functionality on Windows.

I am starting influxd.exe using a `Process` in C#, the `Process.CloseMainWindow()` function is the correct way to gracefully shut down a child process used this way but influxd.exe does not listen to any windows-specific signal/event to close the process gracefully. I must use the `Kill()` function instead which immediately stops the process and very likely not safe for the database.

Even if influxd.exe was being run as a service I would be skeptical that it would be possible to use the "Stop" or "Restart" action in the Windows service management to gracefully shut down this process.
