### ISSUE TITLE
[UI - Dashboards] when dashboards listing is empty, there is no central button in listings area to create one

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#14590]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Onboard a new user
2. Sign in 
3. Open the dashboards page

__Expected behavior:__

That there should be a message that no dashboards exist and that the user should be encouraged to create one with a dashboards button in the center of the listings area of the page. 

N.B. This behaviour exists for example with telegraf and tasks.

__Actual behavior:__
There is no message and no button in the listings area (though there is such a button in header)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 4.4.0-157-generic x86_64
* InfluxDB version: Run `influxd version` and copy the output here
This was tested on the docker image of the latest nightly build. 
```
ts=2019-08-07T08:18:44.587106Z lvl=info msg="Welcome to InfluxDB" log_id=0H6nOKvl000 version=nightly commit=6f14174c3 build_date=2019-08-07T07:15:40Z
```
* Other relevant environment details: Container runtime, disk info, etc
Started with the following params
```
--e2e-testing=true
```

__Screenshot__
![DefaultButtonForDashboards01](https://user-images.githubusercontent.com/25881301/62638526-f1a86780-b93d-11e9-93f3-822b21b73a7d.png)

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

**Comment by russorat** [comment]
This is still an issue.

![image](https://user-images.githubusercontent.com/4805997/66786041-e0c32780-ee93-11e9-8d2f-76117ec5c042.png)

**Comment by corriganjohn** [comment]
![Screen Shot 2020-01-10 at 10 00 08 AM](https://user-images.githubusercontent.com/48359266/72167041-032fe880-3390-11ea-838d-1bf532c767af.png)

It looks like this was fixed at some point
