### ISSUE TITLE
Add giraffe status/notification-event layer to visualizations.  

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#14618]
This issue is not required for alerts mvp. 
When a user views a cell with a check- they currently see data from the query the check is running on, and the thresholds defined on the check.
We would like to add a vis layer that displays vertical lines indicating check status events.
Perhaps on hover on these lines, the legend displays information about the check that produced the status and a link to the status history page for that check? 
We should create this visualization layer that it might be used in the upcoming annotations feature.

**Comment by chnn** [comment]
I think this should go through a design iteration first.
