### ISSUE TITLE
Add requirements to flux queries that can be used for checks

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#14629]
Check queries must have:
1 query
1 aggregate function 
1 field selection  
query must be assigned to `data` <-- Back end does this now. 

As a user if my query does not match the criteria above, Alerting Button should be disabled, and hovering on Alerting button should inform me the criteria I am violating. Saving or Updating check and check view from editor overlay should check for ^^ criteria and prevent user from advancing. 

Additionally: 
- after view is converted to check view, disable + query button in query builder. 
- when user switches to alerting view for first time, auto populate check.every with aggregate function window interval. ON THE FE so the view is correct
- When user changes check.every change aggregate function window interval. (and re-query?)
- user can go back to query builder and change window interval without making changes to check.

**Comment by chnn** [comment]
What happens if a user creates a query with the builder, then adds a check to the cell, but their query isn't a valid check query?

**Comment by ebb-tide** [comment]
They will not be able to add a check to a cell that has an invalid check query.And we will have to restrict them from saving and exiting

**Comment by ebb-tide** [comment]
We have removed checks from cells, so solving these issues are restricted to CheckEditorOverlay
https://github.com/influxdata/influxdb/issues/14758
