### ISSUE TITLE
/metrics endpoint should only record /api/v2 endpoints

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14623]
ensure that only urls that start with /api/v2 are recorded in the /metrics endpoint.

we should also track `/` and `/metrics` endpoints.

**Comment by russorat** [comment]
bump

**Comment by russorat** [comment]
bump

**Comment by wbaker85** [comment]
Closing this based on the changes made in https://github.com/influxdata/influxdb/pull/21958, per discussion with @russorat
