### ISSUE TITLE
Monitoring & Alerting Copy Updates

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14642]
<img width="1389" alt="Screen Shot 2019-08-13 at 1 02 35 PM" src="https://user-images.githubusercontent.com/4805997/62973769-9eb23280-bdcb-11e9-981b-eebd3a2c8cc5.png">

1. "Monitoring & Alerting"
2. "Check Statuses", add "Notifications" Link
3. "Notification Endpoints"
4. Two sentence descriptions of what they are instead of "Looks like" @pauldix to provide

<img width="1388" alt="Screen Shot 2019-08-13 at 1 13 35 PM" src="https://user-images.githubusercontent.com/4805997/62974036-2a2bc380-bdcc-11e9-9cd7-0ce711861e25.png">

1. "Add a Check" with tooltip: "Add a check to monitor this data"

<img width="1393" alt="Screen Shot 2019-08-13 at 1 14 05 PM" src="https://user-images.githubusercontent.com/4805997/62974117-5c3d2580-bdcc-11e9-97e6-855f9dbb6eae.png">

1. @pauldix to provide copy

<img width="1405" alt="Screen Shot 2019-08-13 at 1 15 35 PM" src="https://user-images.githubusercontent.com/4805997/62974574-67448580-bdcd-11e9-8604-8cb2de580738.png">

1. "Configure a Check"
2. "Properties"
3. Add examples for the template language. Similar to the Alert Rule builder in 1.x Chrono
![image](https://user-images.githubusercontent.com/4805997/62974498-349a8d00-bdcd-11e9-91a9-6dd81995b6d6.png)
4. User should not have to scroll to see the CRIT option
5. Red X  

<img width="1395" alt="Screen Shot 2019-08-13 at 1 22 58 PM" src="https://user-images.githubusercontent.com/4805997/62974758-c3a7a500-bdcd-11e9-8540-3020ab707b6d.png">

1. add Org Name to match other pages, rename "Check Statuses"
2. Remove the ability to select, just use 50.

<img width="1417" alt="Screen Shot 2019-08-13 at 1 25 31 PM" src="https://user-images.githubusercontent.com/4805997/62975045-56484400-bdce-11e9-9e19-58a67c4667e7.png">

1. Add "Any" as an option
2. Add "and" between each section
3. Label should just be When, placeholder text should be Tag
4. Tag Filter
5. Notification Endpoint
6. Add similar template help text for template, add "Template" to the end of each field label where a template can be used.

**Comment by pauldix** [comment]
## Copy for the Monitoring and Alerting page
### Check
A **Check** is a periodic query that the system performs against your time series data that will generate a status based on criteria you set. The status is written to a measurement named `statuses` in the `_montitoring` bucket. Statuses generated by a check have a level (OK, INFO, WARN, CRIT) and carry the same tags as the source data the Check was looking at. You can read a more detailed getting started guide and documentation here.

### Notification Rule
A **Notification Rule** will query statuses written by checks to determine if a notification should be sent to a third party system like Slack, PagerDuty, or a generic HTTP POST. Notification Rules and Checks are loosely coupled, which means that a rule can pick up statuses from a single check or many checks. When a notification is sent, the event will be logged to the `notifications` measurement in the `_monitoring` bucket (the same bucket where statuses are logged). You can read more detailed documentation on Notification Rules here.

### Notification Endpoint
A **Notification Endpoint** stores the information to connect to a third party service that can receive notifications like Slack, PagerDuty, or an HTTP server that will accept a POST. You can read more detailed documentation on Notification Endpoints here.

## Copy for the Alerting Note Tab
Dashboard Cells can visualize the data that a Check evaluates to generate statuses. A **Check** is a periodic query that the system performs against your time series data that will generate a status based on criteria you set. The status is written to a measurement named `statuses` in the `_montitoring` bucket. Statuses generated by a check have a level (OK, INFO, WARN, CRIT) and carry the same tags as the source data the Check was looking at. You can read a more detailed getting started guide and documentation here.

You can also edit Checks on the [Monitoring and Alerting] page.

**Comment by alexpaxton** [comment]
I broke some of these issues out into separate issues:

https://github.com/influxdata/influxdb/issues/14681
https://github.com/influxdata/influxdb/issues/14683
