### ISSUE TITLE
Add example template strings to template message fields

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#14683]
- [ ] Message field in check builder "Properties" card
- [ ] Message field in notification rule builder overlay

@russorat can you find a legit example we can stick in here? I'm not sure what the proper syntax is

**Comment by desa** [comment]
Values that will always be available https://github.com/influxdata/idpe/blob/master/docs/content/rfcs/alerts_and_notifications.md#bucket-data-model

**Comment by russorat** [comment]
the text when creating a check:
`${r._check_name} is at level ${r._level}`

Text in a slack message:
`${r._notification_rule_name} triggered by check ${r._check_name}`

**Comment by goller** [comment]
Set `Content-Type` to "application/json"

Behind the scenes we would create these:

```json
{
  "version": 1,
  "rule_name": ${r._notification_rule_name},
  "rule_id": ${r._notification_rule_id},
  "endpoint_name": ${r._notification_endpoint_name},
  "endpoint_id": ${r._notification_endpoint_id},
  "check_name": ${r._check_name},
  "check_id": ${r._check_id},
  "check_type": ${r._type},
  "source_measurement": ${r._source_measurement},
  "source_timestamp": ${r._source_timestamp},
  "level": ${r._level},
  "message": ${r._message}
}
```

**Comment by goller** [comment]
See #14994 for the realz impl
