### ISSUE TITLE
influx cli shell - ability to suspend and resume using ctrl+z

### ISSUE THREAD

**Issue by mdevy-influxdata** [influxdata/influxdb#14685]
__Proposal:__
The ability to suspend, resume, and to put into background the influx cli shell.

__Current behavior:__
Currently the ctrl+z input is ignored.  Ctrl+c is handled, but no response from ctrl+z.

__Desired behavior:__
As follows:
[root@ac01 ~]# tail -f /var/log/messages
Aug  5 09:01:01 ac01 systemd: Started Session 86 of user root.
...
Aug  5 10:01:01 ac01 systemd: Removed slice User Slice of root.
^Z
[1]+  Stopped                 tail -f /var/log/messages
[root@ac01 ~]# bg
[1]+ tail -f /var/log/messages &
[root@ac01 ~]#

Ability to run a task, suspend it (ctrl+z), resume it (fg) or background it (bg).

__Alternatives considered:__
none

__Use case:__
system administration
This is a crucial part of overall system administration.

**Comment by gsauthof** [comment]
I already reported this issue in 2017: #8200

It even got the 1.x label assigned in early 2019.

However, stale bot also closed my issue.

**Comment by jeromegit** [comment]
I would love to have this feature!

**Comment by hackery** [comment]
Why is this even prevented in the first place? It should be normal application behaviour.
