### ISSUE TITLE
Add back in the vertical hover line to graphs

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14691]
as a user
with admin
when i hover over a line graph
then i would like to see a vertical line corresponding to the time on each graph in view. 

also, a possible enhancement to this would be to be able to "lock" the line so that i could view related points on other graphs without having to keep my mouse there. See design-in-progress slack channel for an example.

**Comment by russorat** [comment]
this would be so handy!

**Comment by philjb** [comment]
dupe of https://github.com/influxdata/influxdb/issues/16612 I believe.

**Comment by kristinarobinson** [comment]
Fixed.  Hover line implemented in one graph in edit mode and in dashboard mode.  Will work on implementing shared hover line in issue above.
