### ISSUE TITLE
Points duplicated in Flux query causing incorrect aggregates

### ISSUE THREAD

**Issue by kennyjwilli** [influxdata/influxdb#14717]
My Flux query is returning duplicate points which causes the windowed aggregates to have their _values doubled. Below are two queries: one unwindowed and one windowed. 

**Unwindowed**
```flux
from(bucket:"vm-scaler_5d02d799-f16f-49e9-b6a1-a31bc344b4e0_9aab6790-40a1-46bf-8647-8df1aa4c7755")
|> range(start:2019-08-19T15:20:00Z,stop:2019-08-19T18:20:00Z)
|> filter(fn: (r) => r["_measurement"] == "vm-price")
```

**Windowed**
```flux
from(bucket:"vm-scaler_5d02d799-f16f-49e9-b6a1-a31bc344b4e0_9aab6790-40a1-46bf-8647-8df1aa4c7755")
|> range(start:2019-08-19T15:20:00Z,stop:2019-08-19T18:20:00Z)
|> filter(fn: (r) => r["_measurement"] == "vm-price")
|> aggregateWindow(every:60000ms,fn:sum)
```

I have uploaded the query results [here](https://gist.github.com/kennyjwilli/6f6e8b3b79e19b8c813a7db6844ef882). The unwindowed results are stored in `raw.csv` and windowed results in `windowed.csv`. The problem area is 2019-08-19T17:59:00Z to 2019-08-19T18:01:00Z. In `raw.csv` the following rows are duplicated (have the same columns and _value): 
- 163, 166
- 164, 167
- 165, 168

In `windowed.csv`, rows 163-165 have exactly double the `_value` that they should have (`-11.424` instead of `-5.712`).

For some icing on the cake, these duplicated rows disappear after about 1 hour. Though, the problem does occur pretty consistently (with no obvious pattern of when it is occurring -- it doesn't appear to be correlated with the start of a new hour).

Possibly related: This particular data set will only ever emit points directly on the minute -- no sub-minute points. 

The attached CSVs are generated from Chronograf hosted on InfluxDB Cloud v2. This problem is not isolated to Chronograf though. Our app queries the API directly and still gets these duplicated points.

**Comment by jsternberg** [comment]
It is possible that this is related to influxdata/flux#1427 but I don't remember the details of that issue well enough.

There's some similarities though. `aggregateWindow` is being used the same way, the query has start and stop on minute boundaries, and the results mysteriously have different values when running the same query.

**Comment by jsternberg** [comment]
I took a look this morning to see if the problem above had been deployed to our cloud v2 production and it should be so I am going to look for other potential causes. I'll be updating this issue with the various things I am trying and notes I am taking regarding this issue.

**Comment by jsternberg** [comment]
I ran a few tests and it seems that this bug is likely not in flux and is possibly the storage engine. I am seeing this in the raw data:

```
,,0,2019-08-19T15:20:00Z,2019-08-19T18:20:00Z,2019-08-19T17:58:00Z,-5.7120000000000015,value,vm-price
,,0,2019-08-19T15:20:00Z,2019-08-19T18:20:00Z,2019-08-19T17:59:00Z,-5.7120000000000015,value,vm-price
,,0,2019-08-19T15:20:00Z,2019-08-19T18:20:00Z,2019-08-19T18:00:00Z,-5.7120000000000015,value,vm-price
,,0,2019-08-19T15:20:00Z,2019-08-19T18:20:00Z,2019-08-19T17:58:00Z,-5.7120000000000015,value,vm-price
,,0,2019-08-19T15:20:00Z,2019-08-19T18:20:00Z,2019-08-19T17:59:00Z,-5.7120000000000015,value,vm-price
,,0,2019-08-19T15:20:00Z,2019-08-19T18:20:00Z,2019-08-19T18:00:00Z,-5.7120000000000015,value,vm-price
```

@kennyjwilli do you know what query you used to get the raw data? @e-dard do you have an idea what the cause of this might be?

**Comment by kennyjwilli** [comment]
@jsternberg The raw data was retrieved using the "unwindowed" query: 

```
from(bucket:"vm-scaler_5d02d799-f16f-49e9-b6a1-a31bc344b4e0_9aab6790-40a1-46bf-8647-8df1aa4c7755")
|> range(start:2019-08-19T15:20:00Z,stop:2019-08-19T18:20:00Z)
|> filter(fn: (r) => r["_measurement"] == "vm-price")
```

Another thing I forgot to mention that feels relevant here is that the service that emits these points will often emit the same point twice. The below example is similar to how the service emits points (where a "point" is defined as [epoch-timestamp, field-value]).
```
time1: [0, 10], [1, 15], [2, 20]
time2: [1, 15], [2, 20], [3, 30]
time3: [2, 20], [3, 30], [4, 40]
```

Because this problem is causing confusion for our customers, I have updated this particular service to minimize the likelihood of emitting a duplicate point. I'm hoping that will reduce the number of doubled points. I'll let you know if it does. This is definitely still a relevant problem though.

**Comment by jsternberg** [comment]
Thank you. That information was very helpful. One more question I have is if you are using the `to()` method to write any data and I would just like to reconfirm that you found this using our v2 cloud product.

Also, do you run any tasks?

**Comment by kennyjwilli** [comment]
I am not using the to() method. Yes, I am using the v2 cloud product. No tasks.

**Comment by jacobmarble** [comment]
I have reproduced the bad behavior just as @kennyjwilli describes. Write duplicate data, read duplicate data. Will pick up work on this Monday.
