### ISSUE TITLE
Should be able to replace a failed server

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#1472]
There should be a query command to replace a downed server with one that has recently joined the cluster.

```
replace "downedhost.foo.com" with "newhost.foo.com"
```

That command should copy any shards that existed on "downedhost.foo.com" from other servers in the cluster to "newhost.foo.com"

Once all the shards have been copied over, newhost should be marked as up and ready to answer queries. downedhost should be forcibly removed from the cluster.

Obviously, this will only work if their replication factor is > 1 and the other servers have copies of those shards. The brokers will also have to log the data for each shard as it is copied from that time so that it can pick up any writes that happened while it was copying the shard.

**Comment by corylanou** [comment]
This should be done after #1471

**Comment by corylanou** [comment]
Also, I think the syntax should have to drop a server by `ID`, which is what you get when you do a `show servers`.

**Comment by jsternberg** [comment]
We no longer support clustering in the open source version so I'm going to close this.
