### ISSUE TITLE
[Quantile] is it possible to query multiple quantile in flux query using quantile function. 

### ISSUE THREAD

**Issue by catprmoh** [influxdata/influxdb#14764]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

I need to produce multiple quantile data for the latency data we are measuring. For each quantile type, I have to call a different query and consolidate the value in code. Is there a way I can call multiple quantile value at once. 

from(bucket:"Trident/autogen") |> range(start: 2019-08-23T04:09:37Z, stop: 2019-08-23T04:10:37Z) |> filter(fn: (r) => r._measurement == "Latency" and r._field == "Latency") |> filter(fn: (r) => r._measurement == "Latency" and r._field == "Status" and r._value == 200.00) |> window(every: 1s)|> quantile( q: .9999, method: "estimate_tdigest", compression: 1000.0)|> group(columns: ["LatencyType"]) |> yield()

from(bucket:"Trident/autogen") |> range(start: 2019-08-23T04:09:37Z, stop: 2019-08-23T04:10:37Z) |> filter(fn: (r) => r._measurement == "Latency" and r._field == "Latency") |> filter(fn: (r) => r._measurement == "Latency" and r._field == "Status" and r._value == 200.00) |> window(every: 1s)|> quantile( q: .99, method: "estimate_tdigest", compression: 1000.0)|> group(columns: ["LatencyType"]) |> yield()

from(bucket:"Trident/autogen") |> range(start: 2019-08-23T04:09:37Z, stop: 2019-08-23T04:10:37Z) |> filter(fn: (r) => r._measurement == "Latency" and r._field == "Latency") |> filter(fn: (r) => r._measurement == "Latency" and r._field == "Status" and r._value == 200.00) |> window(every: 1s)|> quantile( q: .75, method: "estimate_tdigest", compression: 1000.0)|> group(columns: ["LatencyType"]) |> yield()

from(bucket:"Trident/autogen") |> range(start: 2019-08-23T04:09:37Z, stop: 2019-08-23T04:10:37Z) |> filter(fn: (r) => r._measurement == "Latency" and r._field == "Latency") |> filter(fn: (r) => r._measurement == "Latency" and r._field == "Status" and r._value == 200.00) |> window(every: 1s)|> quantile( q: .50, method: "estimate_tdigest", compression: 1000.0)|> group(columns: ["LatencyType"]) |> yield()

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__

I needed to run the above queries from the code and consolidate the data for the given window of the window in the code. It will be great if I can pass the desired quantile values in a list and get the result as a part of the single I/0.

__Environment info:__
Linux 4.18.0-1024-azure x86_64
InfluxDB v1.7.7 (git: 1.7 f8fdf652f348fc9980997fe1c972e2b79ddd13b0)

**Comment by nathanielc** [comment]
@catprmoh 

Flux has first class support for functions. Something like this can be achieved by defining a function with the parameters you wish to vary and then calling the function.

```
do = (q) =>
    from(bucket:"Trident/autogen")
        |> range(start: 2019-08-23T04:09:37Z, stop: 2019-08-23T04:10:37Z)
        |> filter(fn: (r) => r._measurement == "Latency" and r._field == "Latency")
        |> filter(fn: (r) => r._measurement == "Latency" and r._field == "Status" and r._value == 200.00)
        |> window(every: 1s)
        |> quantile(q:q, method: "estimate_tdigest", compression: 1000.0)
        |> set(key: "quantile", value: string(v:q))
        |> group(columns: ["LatencyType","quantile"])

union(tables[
    do(q:0.9999),
    do(q:0.99),
    do(q:0.75),
    do(q:0.50),
])
```

**Comment by catprmoh** [comment]
@nathanielc  
Thanks for the pointer it's amazing. But when I run from the chronograph all I get is [object Object]. Is there a way I can get it in a tabular representation, which I can parse it later? How to invoke the functions using the rest query?

This is how I am calling the api from the .net core application 

if (!(String.IsNullOrWhiteSpace(InfluxDBUserName) && String.IsNullOrWhiteSpace(InfluxDBPassword)))
                    _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic",
                        Convert.ToBase64String(Encoding.UTF8.GetBytes($"{InfluxDBUserName}:{InfluxDBPassword}")));
                _client.DefaultRequestHeaders.ConnectionClose = false;
                _client.DefaultRequestHeaders.TryAddWithoutValidation("accept", "application/csv");

 var querybaseUrl = new Uri(InfluxUrl);
            var builder = new UriBuilder(querybaseUrl);
            builder.Path += "api/v2/query";
            string _ContentType = "application/vnd.flux";
 var endPoint = new Dictionary<string, string>() { { "db", dbName } };
               // endPoint.Add("precision", "ms");
              //  endPoint.Add("rp", "autogen");
            requestContent.Headers.ContentType = new MediaTypeHeaderValue(_ContentType); 

            builder.Query = await new FormUrlEncodedContent(endPoint).ReadAsStringAsync();
            try
            {
                HttpResponseMessage response = await _client.PostAsync(builder.Uri, requestContent);
