### ISSUE TITLE
Add view page for Check

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#14782]
This issue will require that we create separate routes for check statuses/notifications/endpoints, which render a version of AlertingHistoryPage that doesn't allow user to delete the `check=checkID` search parameter in the search box. So that user can not make choices that make the visualization irrelevant. 

Adding status indicators to the visualization is not part of this issue, but part of https://github.com/influxdata/influxdb/issues/14618

**Comment by desa** [comment]
Should be a page that contains the union of the alert history page for a check and the visualization of the graph associated with a check

![view-check](https://user-images.githubusercontent.com/1477539/68607503-c07c8d80-047e-11ea-9700-0b88a7e746d3.gif)
