### ISSUE TITLE
Check resourcelimits for checks/rules/endpoints and display appropriate errors to user

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#14805]
Free tier cloud users will have limits on the # of checks/rules/endpoints they can create. We should wrap `<AlertingIndex>` in a` <AssetLimitAlert> `

Consider joining this work with work on https://github.com/influxdata/influxdb/issues/14893

**Comment by desa** [comment]
@jademcgough what is the status of the api work for this?
