### ISSUE TITLE
influx CLI doesn't add user to org

### ISSUE THREAD

**Issue by gitirabassi** [influxdata/influxdb#14823]
```shell
$ influx org members add --name=alternative -o=0460a4b4b22c8000                                                                                                           acceptance:(ingress)
Error: Failed to add member: unknown resource type for permission.` 
```

**Comment by gitirabassi** [comment]
@kelwang I'm not sure what i'm doing wrong:

- started the influxdb server
- `influx setup` and create the root token
- `influx user create --name foo`
- `influx org create --name bar`
- `influx org members add -n bar -o <user_id>` and fails with error `Error: Failed to add member: unknown resource type for permission.` 

Other problem, how to I make a user to be an org owner?

**Comment by kelwang** [comment]
@gitirabassi , before you make sure both your influx and influxd are the newest of master. If it is the old cli or old influxd, it won't work.

For the add owners, could you create a new issue?
