### ISSUE TITLE
Influx Cli support alternatives verbs

### ISSUE THREAD

**Issue by gitirabassi** [influxdata/influxdb#14820]
It would be awesome for `influx {org,user,bucket}` to support
- `find,ls,list`
- `create,add`
- `delete,remove,rm`

Also there is an inconsistency: for `influx org members` where there verbs are not `create,find,delete` but `add,list,remove`... very confusing!!

**Comment by gitirabassi** [comment]
I believe this is still relevant

**Comment by gitirabassi** [comment]
@jsteenb2 I believe this has been fixed

**Comment by jsteenb2** [comment]
awesome 👍
