### ISSUE TITLE
cannot get version of influx CLI

### ISSUE THREAD

**Issue by gitirabassi** [influxdata/influxdb#14821]
Probably is hidden in the code but neither `influx --version`, `influx version`, `influx -v` and when executing `influx --help` there is no mention on how to output a version

**Comment by kelwang** [comment]
@gitirabassi you are talking about the influxdb version, not the cli version, right?

**Comment by gitirabassi** [comment]
I was asking for the CLI, but both would be awesome. When I was running it, i wasn't sure if running the v1 or v2 version of the client.

My primary concern is with people migrating from v1

Also, would be cool to have, other then the version of the server, some metadata of it: if cloud, enterprise or OSS. 

These down here are docker and kubernetes examples. I would be fine with a 2 liner to start with
```sh
bash-3.2$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-30T12:22:52Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
bash-3.2$ docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by gitirabassi** [comment]
I don't think this should be closed yet!

**Comment by jsteenb2** [comment]
agreed!

**Comment by jademcgough** [comment]
A version command was added for `influxd` by #15629, but it would still be good to have a version command for the CLI (which would display the version of the client).

**Comment by jsteenb2** [comment]
@gitirabassi ws talking with @russorat about our versioning.  We can do something similar to clickhouse, where you run version, it reaches out to the server in the config, and lets the user see both the client version and the server version.  WDYT?

reference: https://clickhouse.tech/docs/en/interfaces/cli/#command-line-client
