### ISSUE TITLE
[UI Onboarding] First key stroke in settings > Initial Bucket Name causes controls to disappear

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#14833]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Start the docker nightly image
2. Open the onboarding wizard 
3. In the initial user setup page add basic values.
4. Click on or tab to the field Initial Bucket Name and add the first letter. 

All controls suddenly disappear and the *Continue* button is activated 

__Screencast__
![onboardingIssue02](https://user-images.githubusercontent.com/25881301/63857082-5b4aed00-c9a3-11e9-8a2c-18acd4874942.gif)

__Expected behavior:__

Expected to be able to enter the full bucket name and to be able to review all field values before continuing. 

__Actual behavior:__
All the text fields and their labels disappeared. 

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 4.4.0-159-generic x86_64

* InfluxDB version: Run `influxd version` and copy the output here
This is a test of the docker image created from the nightly build.  From the docker log: 
`ts=2019-08-28T11:44:28.138920Z lvl=info msg="Welcome to InfluxDB" log_id=0HY0VuvW000 version=nightly commit=876624347 build_date=2019-08-28T07:17:43Z`
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with the flag `--e2e-testing=true`

*Browser*: Chrome 76

__Regression:__

This was not happening roughly three weeks ago, before I went on holiday and before focusing attention on another set of tasks. 

__Logs:__
Include snippet of errors in log.
Nothing reported to console logs.  

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

**Comment by hoorayimhelping** [comment]
@karel-rehor I just tried this with the latest from master (`f096605327574cdfe2166fb1bc7e278ab547e29d`) and I couldn't reproduce it. Is it still happening on your end?

**Comment by karel-rehor** [comment]
@hoorayimhelping 

Checked this on the latest nightly build 

```
ts=2019-10-17T07:53:26.952187Z lvl=info msg="Welcome to InfluxDB" log_id=0IYB9lf0000 version=nightly commit=f09660532 build_date=2019-10-17T07:29:43Z
```

It's no longer happening and I can continue with onboarding normally. 

Closing

**Comment by karel-rehor** [comment]
closed
