### ISSUE TITLE
Cell notes visual jank

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#14847]
![Screen Shot 2019-08-28 at 1 06 05 PM](https://user-images.githubusercontent.com/2433762/63889697-5af82500-c996-11e9-97f6-2385ee6204e4.png)

- Note icon off-center
- Should use `Popover` component from Clockface
- The tooltip has ugly scrollbars

**Comment by desa** [comment]
Check to see if this is still a thing
