### ISSUE TITLE
single point disappears in graph

### ISSUE THREAD

**Issue by goller** [influxdata/influxdb#14877]
![disappearingpoint](https://user-images.githubusercontent.com/1922921/63972540-95cd8c00-ca6e-11e9-9d95-757287274e37.gif)

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. display a graph with a single point
2. hover in graph and point appears
3. however out of graph and point disappears

**Comment by russorat** [comment]
i think this would be fixed with this issue: https://github.com/influxdata/giraffe/issues/54
