### ISSUE TITLE
Add the ability to view the influxdb_v2 output for telegraf

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14924]
many people already have telegraf configured for writing data in and they just need to add a new output for influxdb_v2. We need to add a way for the user to view just the output config for telegraf instead of having to create a new config and just pulling the output section.

Maybe just a new button next to the create configuration button that just shows the output section and gives the user the option to copy or download. the name of the downloaded file should be `outputs.influxdb_v2.conf`

![image](https://user-images.githubusercontent.com/4805997/64269840-719b0080-ceef-11e9-90c1-15782e1a0e29.png)

![image](https://user-images.githubusercontent.com/4805997/64269944-9becbe00-ceef-11e9-894f-130c640565e3.png)

**Comment by desa** [comment]
@alexpaxton which project board should this issue be on?

**Comment by alexpaxton** [comment]
@desa I think monitoring is the correct spot

**Comment by russorat** [comment]
- There should be a comment in the modal letting users know that `The USER_TOKEN can be generated on the Tokens tab.` with a link to the tokens tab.
- The output config can be pulled from the telegrafs API i believe
- The button to create this should be prominent and distinguishable from the `Create Configuration` button. FYI @alexpaxton

**Comment by russorat** [comment]
connect https://github.com/influxdata/influxdb/issues/15521 (would be nice to synchronize the naming)

**Comment by drdelambre** [comment]
i can't find the api endpoint for this in the swagger docs. I'll take a link if anyone has one, or we could scope this under monaco work (code folding), or we can make a fragile (but maybe still ok) solution and just remove everything above the `[[outputs.influxdb_v2]]` keyword.

**Comment by desa** [comment]
> i can't find the api endpoint for this in the swagger docs.

I don't think that any such endpoint exists.

>  or we can make a fragile (but maybe still ok) solution and just remove everything above the [[outputs.influxdb_v2]] keyword.

I think this should be a good first pass. I'd imagine that section of the config is pretty stable. Might be good to do this as a first iteration and to open up an issue that does it genericly using an API endpoint in the future.

**Comment by russorat** [comment]
this is the api: https://github.com/influxdata/influxdb/blob/master/http/swagger.yml#L9077

**Comment by desa** [comment]
@russorat there's not an endpoint you can get that value without creating a telegraf.

**Comment by russorat** [comment]
if there's no api, let's hardcode for now.
use an env var for $INFLUX_TOKEN and one for $INFLUX_BUCKET 
let's add a comment to the config explaining that they should replace those values with the token and bucket they want to use for writing data.

**Comment by drdelambre** [comment]
got here today:
![Kapture 2019-10-30 at 17 31 50](https://user-images.githubusercontent.com/1434802/67909081-3574cc80-fb3b-11e9-95a9-9bcb0f0d84bc.gif)
I'm already chasing down an example of a label with a dropdown, but open to more feedback
