### ISSUE TITLE
notificationRules "When status is equal to LEVEL" alter flux query

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14954]
when a user chooses something like this:
![image](https://user-images.githubusercontent.com/4805997/64304598-548f1d80-cf41-11e9-80db-77eb08b89e16.png)

Then the flux query should be something like this:
```
...
statuses = monitor.from(start: -31s) 
any_to_crit = statuses
	|> filter(fn: (r) => r._level == "crit")
...
```

**Comment by desa** [comment]
closed by https://github.com/influxdata/influxdb/pull/14960

**Comment by desa** [comment]
@russorat can we close this?
