### ISSUE TITLE
Display the proper error message in the Query explorer

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14951]
Flux is returning error messages in a nested "message" field. We should display those messages in the UI.

![image](https://user-images.githubusercontent.com/4805997/64299777-42a47f00-cf2f-11e9-8cbf-db39dd71bd65.png)

**Comment by chnn** [comment]
Looks like this is a result of the API returning a funky error response.

Closing in favor of https://github.com/influxdata/influxdb/issues/14974
