### ISSUE TITLE
Deleted tag? "Unknown revision v1.7.8"

### ISSUE THREAD

**Issue by plo-** [influxdata/influxdb#15006]
Hello,

Has the tag v1.7.8 been created and then deleted?!

I've got several projects using the version v1.7.8 after having upgraded all my modules and my builds are now broken with go1.12 because the v1.7.8 has vanished... However it's working with go1.13 (I use both) because the version v1.7.8 is available on the default Go Module Mirror (https://proxy.golang.org/). For more information about Module downloading and verification in go1.13, please read https://tip.golang.org/cmd/go/#hdr-Module_downloading_and_verification.

The versions list is available on the default proxy: https://proxy.golang.org/github.com/influxdata/influxdb/@v/list

My guess is the v1.7.8 has existed before but has been deleted after being cached by the proxy.golang.org. So the proxy.golang.org is continuing to serve that version...

Should I considered that version as broken?

**Comment by stuartcarnie** [comment]
Hi @plo- and thanks for the report. 

We have pushed tag `v1.7.8` to mark the release. We investigated GitHub logs, but unfortunately those did not provide any information on how or when this tag may have been removed.
