### ISSUE TITLE
Allow the user to delete all characters from numeric input

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15024]
A user should be able to delete the last character in this component. If they leave the component without a number, then it should be highlighted in red.

![image](https://user-images.githubusercontent.com/4805997/64453948-95507900-d09e-11e9-9a97-3b2f8d69fd03.png)

**Comment by desa** [comment]
@alexpaxton which project board should this issue be on?

**Comment by alexpaxton** [comment]
@desa monitoring!

**Comment by 121watts** [comment]
Looks like the culprit is [this](https://github.com/influxdata/clockface/blob/master/src/Components/Inputs/Input.tsx#L142) line in clockface.

**Comment by alexpaxton** [comment]
I did some investigation for about 2 days into this, was very frustrating but here's my conclusions:

1. It is possible to have a fully controlled input of type `number` without this delete problem, there are many in the UI. If it were a clockface issue you'd see this same bug in multiple places

2. The way check editing state is stored is super strict and does not allow an invalid value to be set in state, this forcing the input to have a value value at all times. It so happens that empty string is not a valid value, so it forces it to be `0`

3. I'd propose creating a type called `DraftCheck` that offers more flexibility. This way we can have more options for showing validation to the user. Also the `Draft` pattern is present in other editing overlays in the UI, not sure why `Check` does not follow that

**Comment by desa** [comment]
Just checked and this appears to be fixed, but I'm not certain

**Comment by TCL735** [comment]
There are 2 issues:

- clockface does not handle NaN correctly: it does not update type, status, and value
- Input change handlers avoid passing in NaN

My approach would be to ameliorate both points.
