### ISSUE TITLE
invalid check type when editing check name

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15022]
To repro, try editing the name of a check from the main M&A page.

PUT ```{"id":"046df46a09bd2000","name":"Stock Price Changing Else"}```

![image (28)](https://user-images.githubusercontent.com/4805997/64453256-fb3c0100-d09c-11e9-9b3b-934182755a56.png)

**Comment by kelwang** [comment]
I think this one has to be patch. We only want put in the edit page

**Comment by desa** [comment]
@kelwang the issue is that PATCH doesn't allow us to update all fields. I'd prefer to use just a single method PUT/PATCH for all API updates

**Comment by kelwang** [comment]
> @kelwang the issue is that PATCH doesn't allow us to update all fields. I'd prefer to use just a single method PUT/PATCH for all API updates

We should use PUT for the editing page save. and use PATCH for the browsing page edit.
