### ISSUE TITLE
Include tags coming from result when querying for matching notification rules

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#15041]
Currently, matching notification rule querying is querying only for tags that the user has added to the check. We should also be querying for tags that the query response is returning.

**Comment by russorat** [comment]
So this is the expected behavior from the API:

Given the following:
```
check
t1 = v1
t2 = v2

notification rule 1
not tags

notification rule 2
t1 = v1

notification rule 3
t1 = v1
t2 = v2

notification rule 4
t1 = v1
t2 = v3
```

Then the api should return the following notification rules
```
notification rule 1
notification rule 2
notification rule 3
```

**Comment by desa** [comment]
- [ ] Empty rule should match all checks
- [ ] Frontend should grab all tags and submit them to the rules matching API

**Comment by desa** [comment]
Closing in favor of https://github.com/influxdata/influxdb/issues/15806
