### ISSUE TITLE
Inside and outside flux logic incorrect

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15065]
inside range should be AND and outside range should be OR
```
crit = (r) =>
	(r.changePercent < -0.005 and r.changePercent > 0.005)
ok = (r) =>
	(r.changePercent < 0.005 and r.changePercent > -0.005)
```

![image](https://user-images.githubusercontent.com/4805997/64557046-97604500-d2f5-11e9-975e-6a0f5fa9869e.png)

**Comment by desa** [comment]
Specifically inside range should be AND and outside range should be OR
