### ISSUE TITLE
Save as Task not working

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15061]
I think the flux needs to be updated.

![image](https://user-images.githubusercontent.com/4805997/64553586-7d6f3400-d2ee-11e9-9e11-31c181a34cfa.png)

**Comment by desa** [comment]
@russorat can you verify that this is still an issue? I've tried it locally and in prod without issue

**Comment by ebb-tide** [comment]
save as task does not work if flux contains variable.

**Comment by ebb-tide** [comment]
was not a regression, user defined variables were never included in the task.
