### ISSUE TITLE
Should be some indication of notification rule task fails

### ISSUE THREAD

**Issue by nisley** [influxdata/influxdb#15080]
Related to https://github.com/influxdata/influxdb/issues/15069

My notification task was failing but I had no idea that it had even run.

**Comment by russorat** [comment]
blocked until we have https://github.com/influxdata/influxdb/issues/15158

**Comment by russorat** [comment]
bump

**Comment by russorat** [comment]
@nisley so we added this to the UI. does this work for you?

![image](https://user-images.githubusercontent.com/4805997/72548533-bcd10280-3843-11ea-95d9-952a1da8d9d9.png)

**Comment by desa** [comment]
I think this is done
