### ISSUE TITLE
InfluxDB 2.0 does not listen 

### ISSUE THREAD

**Issue by natejgardner** [influxdata/influxdb#15081]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ... Run influxd --http-bind-address 0.0.0.0:9999
2. ... Run netstat -l | grep 9999
3. ... Notice it's not listening.

__Expected behavior:__
Describe what you expected to happen.

InfluxDB listens for requests from 0.0.0.0

__Actual behavior:__
Describe What actually happened.

InfluxDB doesn't actually listen.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 3.10.0-957.12.2.el7.x86_64 x86_64
* InfluxDB version: Run `influxd version` and copy the output here
InfluxDB 2.0.0-alpha.17_linux_amd64
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

influxd --http-bind-address 0.0.0.0:9999

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by jademcgough** [comment]
Hi @natejgardner.

Netstat does not show sockets used by server processes unless you use a `-a` flag. It also interprets addresses and attempts to display them symbolically (on my machine, from the  /etc/services file), so it might not show up anyways if you're trying to grep the port.

Try this:
`netstat -lna | grep 9999`

Or check the port directly with:
`lsof -i:9999`

**Comment by natejgardner** [comment]
Thanks @jademcgough, I re-ran with the `-a` flag and can now see InfluxDB listening, but only on tcp6., It doesn't seem to be respecting `0.0.0.0`. When I try accessing it from a different machine (e.g. `http://myserver:9999/health`) the connection times out. 

Running `influx ping` returns OK from localhost and `curl localhost:9999/health` is fine, so it seems the issue is just with accessing InfluxDB from remote clients.

**Comment by mikecaat** [comment]
Hi, @natejgardner 

Since in my environment InfluxDB 2.0 can be accessed from remote clients,
I think the problem is not related to influxdb, but another issue such as network reachability, dns, firewall and so on.

**Steps to reproduce:**
1. downaload InfluxDB 2.0(influxdb_2.0.0-alpha.17_linux_amd64) and start influxd.
```sh
[root@192.168.33.10 admin]# wget https://dl.influxdata.com/influxdb/releases/influxdb_2.0.0-alpha.17_linux_amd64.t
ar.gz
[root@192.168.33.10 admin]# tar xvfz influxdb_2.0.0-alpha.17_linux_amd64.tar.gz
[root@192.168.33.10 admin]# cd influxdb_2.0.0-alpha.17_linux_amd64
[root@192.168.33.10 admin]# ./influxd --http-bind-address 0.0.0.0:9999
```
2. access from remote client
```sh
[root@192.168.33.1 admin]# curl  "http://192.168.33.10:9999/health"
{"name":"influxdb", "message":"ready for queries and writes", "status":"pass", "checks":[]}
```
**Environment info:**
```sh
[root@myserver admin]# uname -a
Linux vagrant 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**netstat result:**

> I re-ran with the -a flag and can now see InfluxDB listening, but only on tcp6.

I checked netstat and the result same as you did.

```sh
[root@myserver admin]# netstat -lna | grep 9999
tcp6       0      0 :::9999                 :::*                    LISTEN
```
Although I'm not familiar with the IPv6, the man page of IPv6 said that there is a v4-mapped-on-v6 function. I think this is the reason why I can access from a remote client using ipv4.

Ref: http://man7.org/linux/man-pages/man7/ipv6.7.html
>  IPv4 connections can be handled with the v6 API by using the  v4-mapped-on-v6 address type; thus a program needs to support only  this API type to support both protocols. This is handled transparently by the address handling functions in the C library.

Although this function can be restricted to sending and receiving IPv6 packets only, the default is disabled.

> IPV6_V6ONLY (since Linux 2.4.21 and 2.6)
> The default value for this flag is defined by the contents of the file /proc/sys/net/ipv6/bindv6only.  The default value for that file is 0 (false)

I'm sorry that I don't know what is your problem exactly, but as above, I think your problem is not related to influxd. I assume your problem is such as network reachability, dns, firewall and so on.

**Comment by jademcgough** [comment]
Thanks for the reply @mikecaat!

@natejgardner Are you able to access that server externally on other ports? If 9999 isn't open, you can configure the port with `influxd --http-bind-address <port>`.

**Comment by natejgardner** [comment]
@mikecaat @jademcgough thanks!

If I change the port to any value below 9937, it's reachable. Any value over 9937 times out. I checked through iptables and firewall and didn't find anything blocking that port. It may be worth checking if this is the default behavior on other RHEL systems. Since I'm using a VM, I don't know much about the network environment of the host server; it's possible that's where the issue lies.
