### ISSUE TITLE
Client URL should be optional for PagerDuty

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15104]
Client URL is not required for pagerduty and that field should be optional in the UI.

**Comment by zoesteinkamp** [comment]
This issue is currently blocked by the backend changes in issue #15117

**Comment by kelwang** [comment]
fixed with https://github.com/influxdata/influxdb/pull/15117

**Comment by zoesteinkamp** [comment]
This issue was fixed by the backend change, im not going to add a test for it then close it out
