### ISSUE TITLE
Update title of create a check page

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15108]
- [x] ~~remove title (it's set in the next page)~~
 - [x] Update text for toggle
 - [x] Remove name editing from Checks form

![image (31)](https://user-images.githubusercontent.com/4805997/64643736-e7a6d800-d3c5-11e9-80ac-f3a7cf9ac2bd.png)

**Comment by kelseiv** [comment]
@russorat @alexpaxton 
Can we keep the title on this page? It seems right to name it first thing...

**Comment by desa** [comment]
Remove Name editing from checks form.

**Comment by TCL735** [comment]
So, just to be clear:
- We will change the text of the toggle, but keep the title (including being editable)
- We will remove the name editing in the Checks form (bottom left card)

It now looks like this:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/10736577/68724946-c99a5700-0571-11ea-9fb8-6ed47e6f4619.png">
