### ISSUE TITLE
Move flux parsing to outside the KV STM

### ISSUE THREAD

**Issue by docmerlin** [influxdata/influxdb#15106]
Right now flux parsing for options and task validation are inside the KV STM.  This can cause errors that are unrecoverable when flux panics.  This can also add unnecessarily long lock times to KV.

We need to move the flux parsing from inside the stm to outside the stm in kv/task.go

**Comment by docmerlin** [comment]
The panics have been fixed (and wrapped with recovers), so this issue isn't as urgent.

The solution suggested here was becoming very ugly, and @goller suggested a deeper refactor, so that the KV layer wasn't parsing flux.  I agree with him, the current solution is ugly.  As this would touch other pieces, when we have the time,  @lyondhill @stuartcarnie and I should talk this over.

**Comment by aanthony1243** [comment]
@docmerlin  is this being resolved by the current refactor?

**Comment by docmerlin** [comment]
@aanthony1243  I don't believe so, it is more a KV issue than a task issue, in general. The problem is that KV locks are fairly broad during a transaction and slow things that happen inside the transactions between reads and writes or whatever, are rather expensive. One way around it would be to implement optimistic concurrency control, to detect races and reject (or retry) them, instead of the harder locking that KV does now.

**Comment by docmerlin** [comment]
@aanthony1243 after speaking at length with @goller, and @stuartcarnie  we can close this.
