### ISSUE TITLE
Granting READ permission revokes WRITE.

### ISSUE THREAD

**Issue by Igor-Toropov** [influxdata/influxdb#15126]
Scenario:
* Grant WRITE to a user on a database.
* Show grants for user - shows WRITE
* Grant READ to the same 
* Show grants - shows only READ. Not READ,WRITE or ALL - just READ.

Granting permissions should be additive.

**Comment by dgnorton** [comment]
@Igor-Toropov agree that it should have been additive from the start. The concern with changing it at this point would be users that rely on the current behavior. E.g., some users may be downgrading WRITE to READ by granting READ. Changing it to be additive would break that.

**Comment by Igor-Toropov** [comment]
OK, then Maybe update documentation, noting that granting actually SETs access level, rather than granting individual read/write permissions. This will avoid confusion for new users. Thank you.
