### ISSUE TITLE
Feature Request: FFT

### ISSUE THREAD

**Issue by natejgardner** [influxdata/influxdb#15122]
__Proposal:__
Create a function that provides local frequency given a series of oscillating data.
__Current behavior:__
There's not an easy way to estimate the component frequencies/amplitudes of an oscillating series.

__Desired behavior:__
There's an easy way to estimate the component frequencies/amplitudes of an oscillating series.
 
__Alternatives considered:__
Oof. Pretty much just running the data through R or Python.

__Use case:__
Lots of data oscillates. Any time control system data is being recorded to InfluxDB, these metrics are very handy to understand how quickly and how severely sensor values are oscillating.

**Comment by goller** [comment]
I'm all for this _FOR_SURE_

**Comment by goller** [comment]
@natejgardner 	Do you imagine you'd also want various frequency filter types as well?  

what about inverse after filtering?

**Comment by Jervelund** [comment]
FFT would be really nice to have! But it's not as clear cut as implementing other aggregation functions. For example: `mean(value)` only outputs one value at a specific timestamp, while the output for this function is a whole other domain - It should return Hz instead of chronological time.

How should the output for this function look?
Should FFT bucket size be input as a parameter somehow?
I guess you could just return the Hz bucket value as time, to also allow it to be plotted in Chronograf.

**Comment by natejgardner** [comment]
I'm not familiar enough with the internals of InfluxDB to know whether it's possible to return multiple series from a single function, but I imagine it would return a quantized list of frequencies and their 
respective amplitudes for every time window (a spectrogram). This could then be easily filtered in flux for frequencies over a given amplitude threshold to isolate interesting patterns. The new visualizations available in InfluxDB 2 include a heatmap, so perhaps it would even possible to visualize spectrograms natively in Influx with this feature.

Alternatively, the function could also just return the highest-amplitude frequency for every point in time- it'd be less useful, but still useful.

**Comment by generic-humanoid** [comment]
I actually really need this. Taking data out and putting in back into InfluxDB is too expensive. I really only need to do it to compute an FFT. It doesn't seem like this will ever get implemented but, is this possible with flux? I might even venture to try it if I know it's even possible.

**Comment by ddileo** [comment]
@generic-humanoid 
We are kind of "on the same boat"... ;-)
Are you willing to have a word?

**Comment by generic-humanoid** [comment]
@ddileo sure, how though?

**Comment by ddileo** [comment]
@generic-humanoid
I just now generated the following temporary email address.
zbzvftln@hi2.in
Shall you send over a mobile number of yours for Telegram/WhatsApp?
(this is just a proposal, I'm open to alternatives)

**Comment by ddileo** [comment]
@generic-humanoid
Thanks for returning my message.
You should find my reply (from Gmail) in your Gmail mailbox.
Looking forward to meet you. :-)

**Comment by HeinzBenjamin** [comment]
Hello there @ddileo @generic-humanoid ,
I wonder if this conversation led you somewhere?
We're interested in using Influx on a large scale, but server-side FFT is the core feature we need.

**Comment by ddileo** [comment]
> Hello there @ddileo @generic-humanoid ,
> I wonder if this conversation led you somewhere?
> We're interested in using Influx on a large scale, but server-side FFT is the core feature we need.
Shall we have a quick word? 📞🙂
The same old temporary email address still works (I just now tested it.).
zbzvftln@hi2.in
Shall you send over a mobile number of yours for Telegram/WhatsApp?
(this is just a proposal, I'm open to alternatives)

**Comment by FredCyr** [comment]
Interested how interested people found sulotion for their FFT needs? I wish to collect acceleration on a bucket keeping data for 2 days but keeping the FFT results for longer in another bucket in influxdb. Any thoughts?

**Comment by Jervelund** [comment]
I ended up doing aggregation in Python, then inserting the calculated FFT results again. I suppose that could work for you as well (keep source data in your 2day retention bucket, then make a new bucket for FFT results, that has a different retention period).

**Comment by FredCyr** [comment]
Good idea! The problem is my lack of Python knowledge. Would you be willing to share your code as a starting point?
