### ISSUE TITLE
High memory usage (leak?)

### ISSUE THREAD

**Issue by katsil** [influxdata/influxdb#15135]
Hey. Im new into influxdb, but have important question. 
I have cluster full from vm with 2vcpu, 4gam... 
And netdata&influxdb service for store netdata mertics (installed using this guide: https://computingforgeeks.com/monitor-linux-server-with-netdata-and-grafana/), for this im using opentsdb. But most or ram on vm is used for influxdb (really, like more than 2GB (50%) ram is using for influxdb).

Is there any way to decrease memory usage for influxdb, because its very important for me?

Thanks. 
---
My opentsdb config:

```    [[opentsdb]]
      enabled = true
      bind-address = ":4242"
      database = "opentsdb"
      # retention-policy = ""
      # consistency-level = "one"
      # tls-enabled = false
      # certificate= "/etc/ssl/influxdb.pem"
      # Log an error for every malformed point.
      # log-point-errors = true

      # These next lines control how batching works. You should have this enabled
      # otherwise you could get dropped metrics or poor performance. Only points
      # metrics received over the telnet protocol undergo batching.

      # Flush if this many points get buffered
      # batch-size = 1000

      # Number of batches that may be pending in memory
      # batch-pending = 5

      # Flush at least this often even if we haven't hit buffer limit
      # batch-timeout = "1s"
```
---
Influxdb memory usage from one vm`s
![image 1](https://aws1.discourse-cdn.com/business4/uploads/influxdata/original/2X/d/d79f51e9b5951bf026dd81d8cc7efc160e79c0e9.png)
Influxdb usage when i restart it 
![image 2](https://img.share.superhub.xyz/j1kfct.png)

**Comment by katsil** [comment]
can someone help?

**Comment by dgnorton** [comment]
@katsil 
- What version of InfluxDB?
- inmem or TSI index?
- How many series?
