### ISSUE TITLE
Monitoring, Failed to create check: invalid options, function "to" is not implemented

### ISSUE THREAD

**Issue by StefanSa** [influxdata/influxdb#15133]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ... Create a new query
2. ... Create a new check
3. ... Try to save the check

__Expected behavior:__
Describe what you expected to happen.

The newly created check should be saved.

__Actual behavior:__
Describe What actually happened.

Error message pops up.
Failed create check: invalid options; Error calling function "check":
error calling function "write": error calling fanaction "to":
function "to" is not implemented

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 3.10.0-957.27.2.el7.x86_64 x86_64
* InfluxDB version: Run `influxd version` and copy the output here
  InfluxDB 2.0.0-alpha, self-compiled, Git: a90786d 
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```
![Error](https://user-images.githubusercontent.com/6105075/64862036-cfd38c00-d631-11e9-8248-798df4f0942a.png)

**Comment by victor-trx** [comment]
same issue `Error: error calling function "to": function "to" is not implemented` on this query:
```
from(bucket: "prices/") 
|> range(start: -5s)
|> filter(fn: (r) => r._measurement == "btc") 
|> to(bucket: "bucket1/")
Error: error calling function "to": function "to" is not implemented
```

**Comment by priamai** [comment]
I am still seeing this, my configuration is influx InfluxDB v1.8.3 (git: 1.8 563e6c3d1a7a2790763c6289501095dbec19244e).
I am getting exactly the same error.
