### ISSUE TITLE
for each client library, show an example of setting up the client, writing data, and a link to the github repo

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15159]
as a developer
when i view the load data part of the app and look at client libraries
then i would like to see an example of how to set up the client
then i would like to see an example of how to write data
then i would like to have a link to the github repo for the client lib

**Comment by alexpaxton** [comment]
@russorat I got overlays in place to display all the content, but so far I have only copied over content for the node library

**Comment by alexpaxton** [comment]
Looks like this is mostly complete, just needs the content for Go?
