### ISSUE TITLE
display lastRunMessage and lastRunStatus in the UI

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15158]
as a user
when my tasks are failing to run
then i would like an indication in the UI
then i would like to view the last error message returned.

this will be enabled after https://github.com/influxdata/influxdb/issues/15153 is complete.

**Comment by alexpaxton** [comment]
Status should be straightforward, that was in the original design for the feature. I'll have to play around with it and see what the best way to display the message is

**Comment by russorat** [comment]
@desa this is unblocked

**Comment by desa** [comment]
I believe this is done
