### ISSUE TITLE
DELETE does not support renention policies

### ISSUE THREAD

**Issue by hanynowsky** [influxdata/influxdb#15180]
Following: https://github.com/influxdata/influxdb/issues/8088
- It is impossible to DELETE series by specifying the retention policy when using a DELETE statement:
``` 
DELETE FROM "mydb"."my_rp"."my_measurement" WHERE "device" = 'CIS-DSZ-IDE' AND "label" = '038FHJEDF8' AND time >= 1568725200000ms AND time <= 1568737800000ms
ERR: error parsing query: retention policy not supported at line 1, char 1
```

**Comment by bcutter** [comment]
Oh dear, would love to have found a solution for this... :-(

**Comment by ipower-cc** [comment]
You've got to love how the documentation says this is possible, but its not. 
https://docs.influxdata.com/influxdb/v1/query_language/manage-database/#delete-series-with-delete

> Delete all data associated with the measurement h2o_feet in retention policy one_day:

> DELETE FROM "one_day"."h2o_feet"

Maybe there is some secret enterprise build out there where the above statement can work?
