### ISSUE TITLE
Set threshold values to the midpoint of yDomain at initialization

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#15187]
Currently thresholds are initialized to 20, which is totally arbitrary, midpoint of yDomain makes more sense

**Comment by desa** [comment]
![Screenshot 2019-10-21 13 44 27](https://user-images.githubusercontent.com/1477539/67229245-eaefa380-f408-11e9-87bf-7c581f463861.png)

Initial marker should be placed at midpoint of yDomain
