### ISSUE TITLE
TaskExecutor: Add concurrency limit functionality

### ISSUE THREAD

**Issue by lyondhill** [influxdata/influxdb#15194]
The new scheduler needs to be able to limit how many of a specific task can be executed at the same time. 

The task coordinator already know's how to take a limit function but doesn't really know what kind of limit's it can expect. On creation of the executor it expects to receive a `type LimitFunc func(*influxdb.Run) error`. So we need to be able to write a limit function for the executor that allow's us to limit task concurrency.

**Comment by stuartcarnie** [comment]
Lyon will investigate and propose a design for this and update issue

**Comment by lyondhill** [comment]
I propose we look at a list of "currently running" run's in the system. Then just determine how many current run's are `ScheduledFor` in front of the current run. If the number of run's scheduled ahaid of our's is greater then the current run's we have reached our limits. This could allow us to add to a run's log's messages so its clear when we have hit the limit. We could eventually even add a "you are x in queue to run" type messages. This should also work even when we switch to a different type of worker system.
