### ISSUE TITLE
Fix confusing LastScheduled/LatestCompleted naming

### ISSUE THREAD

**Issue by AlirieGray** [influxdata/influxdb#15207]
The new Scheduler contains methods `LastScheduled` and `UpdateLastScheduled`, which respectively return and update the `LatestCompleted` property on the Task struct. 

This confusing naming is tech debt from the old scheduler, which needed the KV store to do some of its scheduling work. Once the new Scheduler is in effect and the KV store no longer needs to do scheduling work, this naming system can be simplified.

**Comment by stuartcarnie** [comment]
Confirmed this is now updating `LastScheduled` via

https://github.com/influxdata/influxdb/blob/bb6aa1df3bef661353961814dc75b6719d0f9c9c/task/backend/schedulable_task_service.go#L29-L39
