### ISSUE TITLE
Add JWT Support to Gateway

### ISSUE THREAD

**Issue by GeorgeMac** [influxdata/influxdb#15229]
OSS now allows for JWT token validation in http API. We need to update to this latest version and wire in a signing key in order to validate tokens from future `to()` transformations.

## Steps

1. Update to version of OSS which support `jsonweb` package.
2. Create implementation of `jsonweb.KeyStore` which provides a signing key from an environment var.
3. Create suitable environment variable for signing key (e.g. `GATEWAY_JWT_SIGNING_KEY`).
4. Configure AuthenticationHandler with a `jsonweb.TokenParser` which uses env var KeyStore implementation.

## Success Criteria

With the appropriate signing key a token can be generated and access authorized via gateway.

**Comment by russorat** [comment]
fyi @pierwill
