### ISSUE TITLE
Dashboard cell contents disappear after canceled edit, require page refresh to view

### ISSUE THREAD

**Issue by glinton** [influxdata/influxdb#15239]
__Steps to reproduce:__

1. Open dashboard in cloud2
1. Select "Configure" from blue pencil icon in dashboard cell (graph, etc...)
1. Choose the "X" in the top right (next to green checkmark)
1. Observe missing cell contents

__Expected behavior:__
Cell contents, same behavior as selecting the green check in cell configuration mode.

__Actual behavior:__
Contents disappear until a page refresh is executed.

__Environment info:__

* System info: `Linux 5.0.0-27-generic x86_64`
* InfluxDB version: ?? `cloud2.influxdata.com`
* Other relevant environment details: `Chrome Version 77.0.3865.75 (Official Build) (64-bit)`

**Comment by desa** [comment]
@russorat is currently unable to reliably reproduce.
