### ISSUE TITLE
Debug level logging dumps user session key

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15258]
In a number of places in the codebase we print the users session key in debug level logs.

https://github.com/influxdata/influxdb/blob/master/http/check_service.go#L237

This happens in a number of different places. Ideally, we should not dump the HTTP request as is done there. At the very least, we should be scrubbing any potentially sensitive data.

**Comment by jsteenb2** [comment]
@jademcgough and @desa feels like we could just drop these debug logs. Is there some background on why they were added originally?

**Comment by desa** [comment]
Seems like we could drop them to me

**Comment by jademcgough** [comment]
I think the idea was to provide a paper trail for requests / user actions.

If we do want to filter out sensitive data:
- headers contain auth tokens
- so do responses from auth creation
- notification endpoints are created with security keys
- /onboarding returns a token
- `/users/:id/password` is logging the password

If no one cares, we can just drop the debug logs in the http layer.

**Comment by desa** [comment]
Good points. They can definitely be useful for debugging. I think we should
just scrub the logs of sensitive data.
