### ISSUE TITLE
system bucket migration

### ISSUE THREAD

**Issue by immykins** [influxdata/influxdb#15256]
We need to generate system buckets for existing organizations, and port data over from the old fixed id buckets to the new buckets.

This will require coordination with @e-dard and @stuartcarnie, and testing our plan on acceptance.

**Comment by jademcgough** [comment]
We need to figure out how to create system buckets for existing organizations when we deploy this in gateway.

**Comment by e-dard** [comment]
@jademcgough is there a workable plan for this yet, or is it on the back-burner?

**Comment by jademcgough** [comment]
We'd like to know how many existing users are still on old buckets. If we've had high enough attrition, it may impact little to no users to just switch this over without having to spend significant effort on a zero-down-time approach.

For initial work for this story: find out who this would impact, then re-evaluate with the tool team.

**Comment by russorat** [comment]
I don't think this is still an issue, but please reopen if it is.
