### ISSUE TITLE
InfluxDB TSM compactions cause temporary write timeouts

### ISSUE THREAD

**Issue by jaapz** [influxdata/influxdb#15271]
We’re running InfluxDB 1.7.7 and ever since migrating from 1.3.x to 1.7.x, and moving to TSM and TSI, we’ve started seeing problems during TSM compactions.

Whenever a TSM compaction occurs, InfluxDB sometimes becomes momentarily unavailabe, leading to a dip and then a peak in writes to to database:

![](https://aws1.discourse-cdn.com/business4/uploads/influxdata/original/2X/4/4e16effc0bc46b88a8010458380e4ed51bdb5cef.png)

As you can see compactions are run every half an hour, but they sometimes are force to be run earlier by InfluxDB and sometimes they also don’t seem to have the dip-peak effect (see 07:30 in the graph).

Our system has one very large measurement containing (building) sensoric data. Each value is tagged with a sensor ID. We log data for each sensor about every 5-10 seconds, for a few thousand sensors.

Could the single large measurement be the source of our problems?

Can we tune our database so these compactions will have less effect?

(PS: i posted this same question on the forums but got no response)

**Comment by tmgordeeva** [comment]
I don't see recent changes that I suspect could cause this issue, but 1.3.x to 1.7.x and an index change is quite a jump to make. There are also options to tune your compactions as Katy mentioned in the forum, but I agree you shouldn't be seeing writes blocking like this. A very large measurement could be an issue if you have large series cardinality though something on the order of thousands should still be fine. Do you also have a large number of shards?

Are you blocking on CPU, io, or gc-ing while compactions happen? If you could collect profiles off of `/debug/pprof` during a peak, we can take a closer look at what's happening (you should be able to capture profiles more or less continuously without much performance impact).

**Comment by jaapz** [comment]
Thanks for your reply!

I've [posted in the forum](https://community.influxdata.com/t/influxdb-tsm-compactions-cause-temporary-write-timeouts/11318/6?u=jaapz) some more information that I gathered during some testing.

>  A very large measurement could be an issue if you have large series cardinality though something on the order of thousands should still be fine.

```
> show series cardinality;
cardinality estimation
20291
```

Not sure if that's too large?

> Do you also have a large number of shards?

Not sure what constitutes as "large". We have data ranging back to the end of 2014, with the following retention policies:

```
name,duration,shardGroupDuration,replicaN,default
four_weeks,672h0m0s,24h0m0s,1,true
forever,0s,168h0m0s,1,false
```

> Are you blocking on CPU, io, or gc-ing while compactions happen? If you could collect profiles off of /debug/pprof during a peak, we can take a closer look at what's happening (you should be able to capture profiles more or less continuously without much performance impact).

Would you have any info on how I would collect a profile like this? Could I just use curl to get that endpoint?

**Comment by tmgordeeva** [comment]
That doesn't seem like an unreasonable number of shards or too high cardinality.

Yes, you can curl to get profiles - some examples are in https://docs.influxdata.com/influxdb/v1.7/tools/api/. This won't include io information - you'll want to watch `iostat` to check for that.

**Comment by e-dard** [comment]
Hi @jaapz could you tell us more about your hardware setup? How many IOPS do you have available on your disk?

Would you be willing to run some of this debugging/profile tooling on your instance? Ideally when the system is going through a period of difficulty. 


```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

Logs would also be helpful as it lets us see what operations the db is carrying out.

**Comment by jacobmarble** [comment]
@jaapz are you still seeing the bug?

**Comment by jaapz** [comment]
I'm sorry for not replying earlier, I've been away on vacation.

Since I'm back I haven't seen it happen yet, but when I was away one of our bigger projects lost their internet connection and our throughput dropped a bit. It seems that there is a threshold  of writes per second that, when exceeded, triggers the behavior.

Before I left on vacation I did some more research into possible problems in parts of the system that we built ourselves, but so far anything I did change didn't make a difference.

> could you tell us more about your hardware setup? How many IOPS do you have available on your disk?

The VPS reports:
* 4 cores, 2.4Ghz
* 8GB RAM (4GB swap)

According to our host we should have 3500/2500 IOPS and a throughput of 700mb/550mb. According to my monitoring we're way below that on both.

The project that lost its connection should be up and running again in the next couple of days, I'll run the profiling tools. Thanks for your help so far!

**Comment by jacobmarble** [comment]
Possibly related to #9636

**Comment by jaapz** [comment]
I haven't been able to reliably see these problems again since I've been back from vacation, even after our throughput was restored back to what it originally was. We haven't changed anything in our system, so I'm not sure why this is.

I'll keep monitoring and if/when it comes back I'll run the profiles and reply here again.

I'm kinda bummed that I can't reproduce it anymore because we've spent a significant amount of time trying to track this down, and also because you guys have spent time in figuring out where it came from as well... Sorry about that.
