### ISSUE TITLE
Add a Windows System plugin bundle to the Telegraf config builder

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15279]
as a windows user
when i need to run a telegraf agent to monitor a windows machine
then i would like the ability to select a windows specific system bundle from the UI

The input plugins that are enabled in this config: https://github.com/influxdata/telegraf/blob/master/etc/telegraf_windows.conf

should be enabled in the Windows System bundle.

**Comment by Tadas** [comment]
Would this allow you to add custom perfmon counters? Providing some sane defaults is nice, but ultimately there's an infinite number of things to monitor with perfmon. You need the ability to easily collect any perfmon counter.

**Comment by russorat** [comment]
bump

**Comment by russorat** [comment]
Example of this can be found here: https://github.com/influxdata/community-templates/tree/master/windows_system

**Comment by timhallinflux** [comment]
The Telegraf config UI is being overhauled to allow for configuration of all plug-ins.  This should address this issue.
