### ISSUE TITLE
Undefined in date (data explorer and dashboard graphs)

### ISSUE THREAD

**Issue by Bacto** [influxdata/influxdb#15283]
__Steps to reproduce:__
Simply go to data explorer and display a graph

__Expected behavior:__
A graph with the date, without "undefined" suffix

__Actual behavior:__
The date is displayed with an "undefined" suffix.
![Screenshot 2019-09-26 at 14 23 03](https://user-images.githubusercontent.com/1188497/65687247-52643e80-e069-11e9-868d-c6f15275dc4c.png)

When selecting "UTC" as timezone, it shows "UTC".
![Screenshot 2019-09-26 at 14 23 14](https://user-images.githubusercontent.com/1188497/65687257-5c863d00-e069-11e9-900c-bcaf5fb0764a.png)

__Environment info:__

* InfluxDB 2.0.0-alpha-17
* Tested with the last version of Firefox and Chrome, both on macOS.

**Comment by palstek** [comment]
I have the same here also in recent InfluxDB 2.0.0-alpha-20.
The server is running the official docker image from quay.io/influxdb/influxdb:2.0.0-alpha.
I tested it with the following browsers: Firefox on Ubuntu 18.04 and Chrome on Win10.
My timezone is CET (Europe/Berlin),

**Comment by TCL735** [comment]
This has been fixed.
