### ISSUE TITLE
Delete dead promql-e2e test suite

### ISSUE THREAD

**Issue by affo** [influxdata/influxdb#15294]
```
make test-promql-e2e
```

**Comment by affo** [comment]
This is still relevant

**Comment by danxmoran** [comment]
I noticed while refactoring some test helpers that the promql submodule no longer builds on `master`, it'll need to be fixed before / as part of enabling the tests in CI.

**Comment by danxmoran** [comment]
Changed the title to reflect our decision to delete this test suite, since flux/cloud have decided to move away from promQL transpilation
