### ISSUE TITLE
PUT api/v2/checks doesn't return error message

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15303]
The UI expects the error response to have a `message` field but the error from PUT /checks does not:

`{"code":"internal error","error":"loc 25:13-31:65: expected RPAREN, got EOF"}`

It should according to the swagger.

**Comment by ducnt114** [comment]
I can work on this issue for my first open source contribution

**Comment by jademcgough** [comment]
@ducnt114 That would be great :)

**Comment by russorat** [comment]
bump

**Comment by kelwang** [comment]
Hey @russorat 

I think it will return a message now no matter. But the code should be an user error, instead of internal. Do you have any context what caused this error?

**Comment by jademcgough** [comment]
@kelwang I'd try testing this out by creating a check with a flux script that's missing a right parenthesis.

**Comment by russorat** [comment]
i just tried to repro and now i see an error:
```
{
    "code": "internal error",
    "message": "An internal error has occurred"
}
```

so i guess thats ok? at least the original issue is fixed.
