### ISSUE TITLE
InfluxDB.write(BatchPoint) is getting "partial write" error

### ISSUE THREAD

**Issue by coolvipool** [influxdata/influxdb#15307]
Hi Dev Team,

I'm using InfluxDB Java client for writing data into the database. I've recently encountered one 
 error while inserting data into influxDB.
We are using retention policy of 1 month duration (720 hours).

The code is a simple insert to a influxDB measurement as follows:

BatchPoints batchPoints = BatchPoints.database(dBName).retentionPolicy(retentionPolicy).build();

Point point = Point.measurement(measurement)
                    .time(System.currentTimeMillis(), **TimeUnit.MILLISECONDS**)
                    .tag("EventType", String.valueOf(eventMetaData.getType()))
                    .tag("Produced", Boolean.toString(eventMetaData.isProduced()))
                    .tag("TriggerType", eventMetaData.getTriggerType().getValue())
                    .build();

batchPoints.point(point);	

influxDB.write(batchPoints);

But influxDB.write method gives following error quite frequently (earlier, we didn't see this error)
Error while writing data to influxDB. Error Message: {"error":"partial write: points beyond retention policy dropped=4"}

I'm not sure why it's throwing partial write error. As per my analysis, I thought of two possibilities>>

1. While writing to DB, some old records might be getting expired beyond retention policy (30 days), so it might be possible that db is inserting new records + removing old records. Ideally it should not throw error for new insert. (I doubt about this possibility)

2. I checked in the class InfluxDBImpl class inside the jar (influxdb-java-2.5.jar)

  @Override
  public void write(final BatchPoints batchPoints) {
    this.batchedCount.addAndGet(batchPoints.getPoints().size());
    RequestBody lineProtocol = RequestBody.create(MEDIA_TYPE_STRING, batchPoints.lineProtocol());
    execute(this.influxDBService.writePoints(
        this.username,
        this.password,
        batchPoints.getDatabase(),
        batchPoints.getRetentionPolicy(),
        **TimeUtil.toTimePrecision(TimeUnit.NANOSECONDS)**,
        batchPoints.getConsistency().value(),
        lineProtocol));
  }

In my code the point is storing time in milliseconds, but the influxDBImpl class provided uses time precision of nanoseconds. And there is no way if I can choose to change the time precision in the jar.

I tried to change in my code to change time value as nanoseconds, but it goes beyond max values of Integer.

Can you please suggest me what is the true root cause of this error and how to fix this. I'm forced to use JDK1.7 in my code, due to which I'm not able to use higher version than 2.5 of influxDB java client jar.

@jwilder Can you please suggest me how to address this issue? No one is assigned to it yet.

**Comment by hardiksondagar** [comment]
#15050
