### ISSUE TITLE
Combine LAST with DISTINCT or GROUP BY?

### ISSUE THREAD

**Issue by mstinglin** [influxdata/influxdb#15310]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

I have a simple time series like this:
time                    id         area
2019-09-25T17:21:00Z    1          us
2019-09-25T17:22:00Z    1          uk
2019-09-25T17:23:00Z    2          canada
2019-09-25T17:24:00Z    3          us
2019-09-25T17:25:00Z    1          canada

I want to get count the areas for last point of each distinct id, so the result should be something like this:
area      count        
us        1
canada    2

Since the last point for id 1 is canada, i want to ignore all previous points for id 1. 

How do I query for only the most recent point for each distinct id? Is this possible?

Edit: Here is the actual data I am working with.
name: click3
time                area   id       value
----                ----   --       -----
1569480689926885700 travel session1 1
1569480693527591500 travel session2 1
1569480699951799900 vtc    session3 1
1569480706416720700 health session1 1
1569480713265800900 claim  session4 1
1569480719882312600 health session3 1

area and id are indeed tags. When I do a simple select LAST(value) with a GROUP BY, I get the following:
> select last(value) as value, area, id from click3 group by id
name: click3
tags: id=session1
time                value area   id
----                ----- ----   --
1569480706416720700 1     health session1

name: click3
tags: id=session2
time                value area   id
----                ----- ----   --
1569480693527591500 1     travel session2

name: click3
tags: id=session3
time                value area   id
----                ----- ----   --
1569480719882312600 1     health session3

name: click3
tags: id=session4
time                value area  id
----                ----- ----  --
1569480713265800900 1     claim session4

which is correct - the last point for each unique session id. When I select * from this query as a subquery, the result is
> select * from (select last(value) as value, area, id from click3 group by id)
name: click3
time                area   id       id_1     value
----                ----   --       ----     -----
1569480693527591500 travel session2 session2 1
1569480706416720700 health session1 session1 1
1569480713265800900 claim  session4 session4 1
1569480719882312600 health session3 session3 1

When I add an aggregate like COUNT(*) or SUM(value), I see the number 4 as expected:
> select count(*) from (select last(value) as value, area, id from click3 group by id)
name: click3
time count_value
---- -----------
0    4

But if I then add a GROUP BY area to this query, I expect to see travel have a value of 1, health have a value of 2, and claim to have a value of 1. For some reason, it seems like the full original set of data points is used and not reduced set from the subquery, so I end up with this:
> select count(*) from (select last(value) as value, area from click3 group by id) group by area
name: click3
tags: area=claim
time count_value
---- -----------
0    1

name: click3
tags: area=health
time count_value
---- -----------
0    2

name: click3
tags: area=travel
time count_value
---- -----------
0    2

name: click3
tags: area=vtc
time count_value
---- -----------
0    1

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by DaveSlinn** [comment]
Here is the original StackOverflow for this question. https://stackoverflow.com/questions/58106620/combine-last-with-distinct-or-group-by/58115239

It really seems like either a serious limitation, or a serious misunderstanding on our part, that you cannot group by a TAG in a subquery and then group by another tag in the outer query using influxQL.

**Comment by mstinglin** [comment]
I honestly think influx was not built to achieve what we are trying to do. It is very time series focused.

Sent from my iPhone

On Oct 4, 2019, at 5:03 PM, Dave Slinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is the original StackOverflow for this question. https://stackoverflow.com/questions/58106620/combine-last-with-distinct-or-group-by/58115239

It really seems like either a serious limitation, or a serious misunderstanding on our part, that you cannot group by a TAG in a subquery and then group by another tag in the outer query using influxQL.
