### ISSUE TITLE
Unable to re-add bucket to a scoped token after re-creating it

### ISSUE THREAD

**Issue by wojciechka** [influxdata/influxdb#15316]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a bucket
2. Create a token to read/write scoped to that bucket
3. Verify that the token works
4. Delete and create a new bucket with the same name
5. The previously created token does not work ; there is no way to re-add new bucket to the existing token

__Expected behavior:__
Be able to edit buckets that token can read from / write to, or at least be able to re-use token for a bucket with same name.

__Actual behavior:__
No option to perform it in the UI.

__Environment info:__
Version 2.0.0 (732c0cc)

__Config:__
N/A

__Logs:__
N/A

__Performance:__
N/A

**Comment by russorat** [comment]
Tokens are immutable after they are created in the system today.  Could you describe the use case for this?

**Comment by wojciechka** [comment]
I forgot to mention one thing in step 4 - what I was doing was ot delete and re-create the bucket. I was pushing incorrect data to the bucket, so I wanted to delete all data and start over.

I did not find a way to delete all measurements for a bucket, so I only thought of deleting and creating the bucket.

I've just updated the description for this issue.

I think this use case could be fulfilled by either being able to delete some or all data from a bucket - either using API or flux and a function to delete records - or having an option to re-create a bucket and still be able to use the token.

Otherwise every time I need to resend data, I'd need to re-create a scoped token.

**Comment by russorat** [comment]
Thanks for the update! keep an eye on this PR for deleting within a bucket: https://github.com/influxdata/influxdb/pull/15255

**Comment by wojciechka** [comment]
Hi Russ,

I'm sorry for responding to this so late.

I agree that what I really wanted was to delete old/erroneous data, so if there would be a way to delete all data or data wihtin specific ranges, that would be more suitable than re-creating tokens.

I think it would be best to be able to delete data from Flux - such as `|> delete()`. Perhaps it would only work if I did not process the data in any way (i.e. did not aggregate it in any way). I am not sure how well that fits the language concepts, but given there is documentation about `to()` function, so it seems Flux should be able to apply changes in general. Perhaps deletion could also be one of the changes it can apply.

I believe that unless you want to move forward with this, you can close the issue.

**Comment by russorat** [comment]
@wojciechka thanks for the update! i believe the `/delete` endpoint will do what you need. You can manually call it now, but look for a way to do it in the UI coming in a few weeks.
