### ISSUE TITLE
[UI - Settings > Labels ] Color Swatch in Color Input covers part of input value

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#15311]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open Settings > Labels
2. Click create label.  The create label poup loads 
3. Clear the color input.  The preview swatch disappears and a warning notice appears indicating the format for the string required by the input. 
4. Input a new string value "e.g. #FFC0CB"

__Expected behavior:__
Expected that the full value would remain visible and that a color swatch sample would appear BESIDE the input.  

__Actual behavior:__
A color swatch sample appears on top of the input to the leftt.  It covers first two to three characters of the input value.  

__Screencast__
![CreateLabelColorInput01](https://user-images.githubusercontent.com/25881301/66053204-2d247400-e532-11e9-92db-a088503d068f.gif)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 4.4.0-165-generic x86_64
* InfluxDB version: Run `influxd version` and copy the output here
This is tested on the docker image of the nightly build.  From the docker log. 
```
commit=4f7e147e2 build_date=2019-10-02T07:13:49Z
```
```
ts=2019-10-02T07:37:56.185935Z lvl=info msg="Welcome to InfluxDB" log_id=0IErJOrG000 version=nightly commit=4f7e147e2 build_date=2019-10-02T07:13:49Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: **Chrome 77**

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled. 
```
--e2e-testing=true
```

**Comment by ahmedaabouzied** [comment]
@karel-rehor , Hey I'd like to work on this

**Comment by ahmedaabouzied** [comment]
The same problem appears in the [clockface color picker component docs](https://influxdata.github.io/clockface/?path=/story/components-color-picker-examples--custom-color-palette)
