### ISSUE TITLE
403s from the API should log out user

### ISSUE THREAD

**Issue by Palakp41** [influxdata/influxdb#15312]
As a user who is cancelled, anytime the api endpoint comes back with 403 error, the user should be logged out automatically.

We return a 401 for when a user is not authorized to access a resources and 403 when they are disabled. So we should log them out on 403 and not on 401.

**Comment by hoorayimhelping** [comment]
Confirmation from Brandon: All 403s from the API should log the user out of the UI. 401s can be sent for specific resources, but a 403 will always mean forbidden. This applies to all endpoints, even /me.
