### ISSUE TITLE
build production docker image of FE on any change to ui and http/swagger.yml

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15338]

**Comment by drdelambre** [comment]
after talking to @mark-rushakoff, we're going to take some immediate shortcuts to prove out an MVP first before optimizing, and track those optimizations as follow up tasks.
the initial shape of this thing will be two images being generated on _any change_ to influxdb; a dev image and a prod image. A dev image is the basic build environment required to create prod assets. A prod image is an nginx image serving some static files on it that were generated from the dev image. these images will be named `ui_dev:${GIT_SHA}` and `ui:${GIT_SHA}` respectively.

potential follow up tasks:
- [ ] spin out a test image
- [ ] file watch on the code base and only build the appropriate image when things have changed
    - [ ] ui/yarn.lock for `ui_dev_base`
    - [ ] webpack.*, tsconfig.json, and a few others for `ui_dev_env`
    - [ ] the testing files / folders for `ui_dev_test`
    - [ ] ui/src/* and http/swagger.yml for `ui_dev`
- [ ] CDN hooks to ensure static files are in the cdn before the new tagged `ui` image is pushed to the registry

**Comment by drdelambre** [comment]
follow up tasks have been spun out into `monitor-ci`. The image still needs to be verified in acceptance (see successful deploy message in chronografd channel for a link) before we push to production, but the image is being built regularly and pushed out into quay.
We are kind of in a weird place, at the end of jenkinsfile based builds and the beginning of argo based builds, so i'm unclear how much focus should be put on pushing this through (requires a couple of days with SRE to modify permissions and a big thumbs up from russ and desa signifying we are comfortable with it), or rewriting the whole thing in argo (unknown time to complete, unknown resources available immediately, but needs to be done eventually).
