### ISSUE TITLE
Comments are not saved in Tasks

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15367]
as a user
when i add comments to my task to explain what's going on
then i would like those comments to be saved for the next time i view the task

![Kapture 2019-10-09 at 11 54 59](https://user-images.githubusercontent.com/4805997/66511475-d962df00-ea8b-11e9-8354-ac5568b6b0b8.gif)

**Comment by nathanielc** [comment]
This is related to https://github.com/influxdata/flux/issues/1959

**Comment by russorat** [comment]
bump

**Comment by russorat** [comment]
this has been fixed in cloud
