### ISSUE TITLE
InfluxDb 2.0 Data not visible in Data Explorer after adding via client library

### ISSUE THREAD

**Issue by pvpkiran** [influxdata/influxdb#15377]
I am running Influx Db2 as a docker container. (quay.io/influxdb/influxdb:2.0.0-alpha). I tried to connect to it using my springboot application. I am using the java client librabry [influxdb-client-java](https://github.com/influxdata/influxdb-client-java).  

I am able to successfully add and query the data through the API. However after adding the data through the client library, If I go to my web console and try to browse data in Data Explorer tab, I do not see anything. This is strange  since I can retrieve data using my java code.   

Lastly If I add the data using webconsole line protocol option, I can immediately see the data in Data Explorer. Not sure the issue is with client librabry or the InfluxDb itself

**Comment by pvpkiran** [comment]
@bednar Here is the link to the project https://github.com/pvpkiran/influx2springboot  I have only one organization. I tried all possible filters Past 1H, past 1D... Nothing works.

**Comment by bednar** [comment]
The problem is in timestamp precision. You are mixing milliseconds and nanoseconds:

```java
Point point = Point.measurement("order")
                        .addTag("type", randomElement)
                        .addTag("brand", brand)
                        .addField("location", city)
                        .addField("price", price)
                        .time(**instant.toEpochMilli()**, WritePrecision.**NS**);
```

 ```.time(instant.toEpochMilli(), WritePrecision.NS)``` should be ```.time(instant.toEpochMilli(), WritePrecision.MS)``` or ```.time(instant, WritePrecision.NS);```.

see: https://github.com/pvpkiran/influx2springboot/blob/39a1fecb561734f5b93c7e0d83602845a1ba87ff/src/main/java/in/phani/infludb/influx2springboot/utils/RandomPointsGenerator.java#L168

![image](https://user-images.githubusercontent.com/455137/66647285-c6d1dc80-ec28-11e9-8276-b82fcfd24517.png)

**Comment by pvpkiran** [comment]
@bednar  thanks for the hint. I can confirm that it works now. However it is bit difficult to debug or even guess what is the issue here, since there is no error and data comes back using the client library.

**Comment by bednar** [comment]
The issue was in selected time range in the Data explorer. Try `Script Editor` with query: `from(bucket:"online-store") |> range(start: 0)`
