### ISSUE TITLE
InfluxDB2.0 line protocol - Cannot Upload file with multiple lines from Windows OS

### ISSUE THREAD

**Issue by pvpkiran** [influxdata/influxdb#15376]
I am using InfluxDb 2.0. I am trying to load data through line protocol. I am doing it using the web console. If my uploaded file has only one line, then the upload works. If it has multiple lines, then I get an error message like this

`Unable to Write DataError: unable to parse '....': invalid number unable to parse '....': invalid number  `
My text file looks like this

```
order,brand=mercedes,typ=car loc="newyork",totalprice=200000
order,brand=vw,typ=car loc="shanghai",totalprice=100000  
```
Not sure If I am getting Invalid Number error message because my last field has value as integer.

But I can confirm that If I have only one line, then it works perfectly fine.

May be there is some issue with new line character.  

I am running Influx Db through docker container. This is the image I am using(as specified in the docs) **quay.io/influxdb/influxdb:2.0.0-alpha**

**Comment by karel-rehor** [comment]
@pvpkiran 

I just tested this manually on a container from the docker nightly build (quay.io/influxdb/influx:nightly). 
```
ts=2019-10-10T08:42:10.110541Z lvl=info msg="Welcome to InfluxDB" log_id=0IPDA7FW000 version=nightly commit=be28de8fb build_date=2019-10-10T07:19:57Z
``` 
I'm working in an Ubuntu 16 linux environment with Chrome 77. 

I copied your lines above. Both entering the values manually with multiple lines and uploading from file worked for me.  

The file I used to upload is attached. 

[test-lpt.txt](https://github.com/influxdata/influxdb/files/3712615/test-lpt.txt)

**Comment by pvpkiran** [comment]
I am using windows 10 and chrome. Let me try with the nightly build once

**Comment by karel-rehor** [comment]
I tried your file and ran into the same error:

```
Unable to Write DataError: unable to parse 'order,brand=mercedes,typ=car loc="newyork",totalprice=200000 ': invalid number unable to parse 'order,brand=vw,typ=car loc="shanghai",totalprice=100000 ': invalid number
```
Here's a hexdump of your file 
```
$ hexdump -C lpt-win.txt 
00000000  6f 72 64 65 72 2c 62 72  61 6e 64 3d 6d 65 72 63  |order,brand=merc|
00000010  65 64 65 73 2c 74 79 70  3d 63 61 72 20 6c 6f 63  |edes,typ=car loc|
00000020  3d 22 6e 65 77 79 6f 72  6b 22 2c 74 6f 74 61 6c  |="newyork",total|
00000030  70 72 69 63 65 3d 32 30  30 30 30 30 0d 0a 6f 72  |price=200000..or|
00000040  64 65 72 2c 62 72 61 6e  64 3d 76 77 2c 74 79 70  |der,brand=vw,typ|
00000050  3d 63 61 72 20 6c 6f 63  3d 22 73 68 61 6e 67 68  |=car loc="shangh|
00000060  61 69 22 2c 74 6f 74 61  6c 70 72 69 63 65 3d 31  |ai",totalprice=1|
00000070  30 30 30 30 30 0d 0a                              |00000..|

```
And a hexdump of the file I sent 
```
$ hexdump -C test-lpt.txt 
00000000  6f 72 64 65 72 2c 62 72  61 6e 64 3d 6d 65 72 63  |order,brand=merc|
00000010  65 64 65 73 2c 74 79 70  3d 63 61 72 20 6c 6f 63  |edes,typ=car loc|
00000020  3d 22 6e 65 77 79 6f 72  6b 22 2c 74 6f 74 61 6c  |="newyork",total|
00000030  70 72 69 63 65 3d 32 30  30 30 30 30 0a 6f 72 64  |price=200000.ord|
00000040  65 72 2c 62 72 61 6e 64  3d 76 77 2c 74 79 70 3d  |er,brand=vw,typ=|
00000050  63 61 72 20 6c 6f 63 3d  22 73 68 61 6e 67 68 61  |car loc="shangha|
00000060  69 22 2c 74 6f 74 61 6c  70 72 69 63 65 3d 31 30  |i",totalprice=10|
00000070  30 30 30 30 20 20 0a                              |0000  .|
```
The difference is in the Windows CRLF at the end of the line - `0d 0a`.  In the linux file it is only `0a`.  

_This is an issue_, as I think the UI should be able to upload files regardless of the system encoding of end-lines.  

If your text editor has an option for saving text files with a linux type encoding '\n' instead of windows idiom '\r\n' try saving the data file that way and then uploading the file. 

Note: I also attempted to simply add a space at the end of the line, but the \r in the windows encoding was then interpreted as the start of a time stamp.

```
Unable to Write DataError: unable to parse 'order,brand=mercedes,typ=car loc="newyork",totalprice=200000 ': bad timestamp unable to parse 'order,brand=vw,typ=car loc="shanghai",totalprice=100000 ': bad timestamp
```

**Comment by pvpkiran** [comment]
thanks for confirming. My initial gues was the same, something to do with end of line(newline)

**Comment by desa** [comment]
Closing issue as all submitted data must conform to the [line protocol syntax](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/#syntax).

**Comment by bcherb2** [comment]
I am confused why this was closed, it still does not work on Windows.  I tested the above linked files that were generated from Linux and they work fine.

**Comment by tolligderf** [comment]
In NotPad++ you can specify the line endings to be linux LF for new document. What worked for me :

1. Install the latest notpad++ 

2. Go to Preferences | New Doc and check Line ending Unix (LF)

3. Go to Encoding and choose UTF-8

4. Open a new doc

5. Add as many line protocols according to influxdb doc [here](https://docs.influxdata.com/influxdb/cloud/get-started/write/)

6. Don't put anything at the end of each line, no \n, no \r\n, just nothing (cf attachment)
![Screenshot 2024-04-01 213214](https://github.com/influxdata/influxdb/assets/165713951/9ca07543-0365-44b5-b855-87912c00b735)

7. Save as .line file 

8. Try uploading it in influxdb client UI after selecting your bucket, click on "Write Data" and you should be good (cf attachment)
![Screenshot 2024-04-01 213035](https://github.com/influxdata/influxdb/assets/165713951/253931e8-d04a-44c2-8313-34ed660a0a1d)
![Screenshot 2024-04-01 213808](https://github.com/influxdata/influxdb/assets/165713951/485aa5de-d183-4ea3-8716-3745f44d19da)
![Screenshot 2024-04-01 213614](https://github.com/influxdata/influxdb/assets/165713951/dcdbe595-93a5-4b57-b2ed-96cee04163fc)

Hope it helps
Fred
