### ISSUE TITLE
FloatIterator finalized by GC - panic:runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bhavesh2177** [influxdata/influxdb#15380]
We are running the Influxd version 1.7.3 on CentOS 7.6.

While running the "SELECT last(service_type) AS service_type, mean(*) INTO \"db2\".autogen.:MEASUREMENT FROM \"db1\".autogen./.*/ GROUP BY time(5m), *" continuous query, getting the below error.

#### ERROR ####
[panic:runtime error: invalid memory address or nil pointer dereference]
Oct 10 16:35:00 ifb01-a influxd[24544]: ts=2019-10-10T11:05:00.556453Z lvl=error msg="SELECT last(service_type) AS service_type, mean(*) INTO \"db2\".autogen.:MEASUREMENT FROM \"db1\".autogen./.*/ WHERE time >= '2019-10-10T10:50:00Z' AND time < '2019-10-10T10:55:00Z' GROUP BY time(5m), * [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 46287 [running]:\nruntime/debug.Stack(0xc01788a720, 0xc05375a000, 0xd3)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/influxdata/influxdb/query.(*Executor).recover(0xc0003ca6f0, 0xc01788a720, 0xc0172d3080)\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:394 +0xaf\npanic(0x108d400, 0x1d707c0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/influxdata/influxdb/query.Iterators.Close(0xc0684a6000, 0xb9c, 0x1114, 0xc029b5e690, 0x13a0f80)\n\t/go/src/github.com/influxdata/influxdb/query/iterator.go:48 +0x50\ngithub.com/influxdata/influxdb/coordinator.(*LocalShardMapping).CreateIterator(0xc0172b34c0, 0x1396480, 0xc039ff0510, 0xc029b5e690, 0x1393180, 0xc031805350, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/coordinator/shard_mapper.go:202 +0x2b6\ngithub.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator.func1(0xc02c9f6e98, 0x1396480, 0xc039ff0510, 0xc02c9f5cf8, 0xc02c9f5cb0, 0xc031805350, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:581 +0x13a\ngithub.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator(0xc02c9f6e98, 0x1396480, 0xc039ff0510, 0xc031805350, 0x1393180, 0xc031805350, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:605 +0xd5\ngithub.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator.func1(0xc031805350, 0x1396480, 0xc039ff0510, 0xc02c9f6e98, 0xc02c9f6378, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:513 +0xd0\ngithub.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator(0xc02c9f6e98, 0x1396480, 0xc039ff0510, 0xc031805350, 0x1386320, 0xc0448506c0, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:557 +0xd41\ngithub.com/influxdata/influxdb/query.buildExprIterator(0x1396480, 0xc039ff0510, 0x1393180, 0xc031805350, 0x7fbef4609138, 0xc0172b34c0, 0xc0179dbbb0, 0x1, 0x1, 0x1393180, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:154 +0x1f4\ngithub.com/influxdata/influxdb/query.buildFieldIterator(0x1396480, 0xc039ff0510, 0x1393180, 0xc031805350, 0x7fbef4609138, 0xc0172b34c0, 0xc0179dbbb0, 0x1, 0x1, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:851 +0x44b\ngithub.com/influxdata/influxdb/query.buildCursor(0x1396480, 0xc039ff0510, 0xc01ec3b900, 0x7fbef4609138, 0xc0172b34c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:736 +0xc7c\ngithub.com/influxdata/influxdb/query.(*preparedStatement).Select(0xc03ebdc000, 0x1396480, 0xc039ff0510, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:119 +0x180\ngithub.com/influxdata/influxdb/query.Select(0x1396640, 0xc01c5640c0, 0xc01ec3b500, 0x137fc80, 0xc00000cc60, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:96 +0xfe\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).createIterators(0xc000273420, 0x1396640, 0xc01c5640c0, 0xc01ec3b500, 0xc000399790, 0xa, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:638 +0x113\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc000273420, 0xc01ec3b500, 0xc01c5640c0, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:542 +0x99\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc000273420, 0x13973c0, 0xc01ec3b500, 0xc01c5640c0, 0x1, 0x1)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:64 +0x2400\ngithub.com/influxdata/influxdb/query.(*Executor).executeQuery(0xc0003ca6f0, 0xc01788a720, 0xc000399790, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:334 +0x355\ncreated by github.com/influxdata/influxdb/query.(*Executor).ExecuteQuery\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:236 +0xc9\n" log_id=0IPKb9M0000 service=query

**Comment by yves-bourgeois** [comment]
Influx version 1.8.3
OS: Ubuntu

We had the same issue today, with the following tracing:


ts=2021-01-14T11:31:54.661726Z lvl=error msg="FloatIterator finalized by GC" log_id=0Q~GYcvl000 engine=tsm1
ts=2021-01-14T11:31:54.661764Z lvl=error msg="FloatIterator finalized by GC" log_id=0Q~GYcvl000 engine=tsm1
ts=2021-01-14T11:31:54.661772Z lvl=error msg="FloatIterator finalized by GC" log_id=0Q~GYcvl000 engine=tsm1
ts=2021-01-14T11:35:46.150134Z lvl=error msg="SELECT value_num FROM looms.autogen./G.*_connected/ WHERE time > now() - 5m [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 5386583948 [ru
ts=2021-01-14T11:40:16.365147Z lvl=error msg="SELECT value_num FROM looms.autogen./G.*_connected/ WHERE time > now() - 5m [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 5386586768 [ru
ts=2021-01-14T11:40:05.949498Z lvl=error msg="SELECT value_num FROM looms.autogen./G.*_connected/ WHERE time > now() - 5m [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 5386587238 [ru
ts=2021-01-14T11:41:23.261924Z lvl=error msg="SELECT value_num FROM looms.autogen./G.*_connected/ WHERE time > now() - 5m [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 5386586253 [ru
ts=2021-01-14T11:44:28.985628Z lvl=error msg="SELECT value_num FROM looms.autogen./G.*_connected/ WHERE time > now() - 5m [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 5386589923 [ru
ts=2021-01-14T11:46:52.945328Z lvl=error msg="FloatIterator finalized by GC" log_id=0Q~GYcvl000 engine=tsm1
ts=2021-01-14T11:46:29.601605Z lvl=error msg="FloatIterator finalized by GC" log_id=0Q~GYcvl000 engine=tsm1


Influx was running for about 40 days straight.  First occurrence.

**Comment by shaileshngit** [comment]
Hi All,

I am also facing same issue for influxdb.

OS version :- CentOS-7
InfluxDb Version :- 1.7

error - 
PM2022-08-11T15:20:59.337882Z	error	FloatIterator finalized by GC	{"log_id": "0cFI8RwG000", "engine": "tsm1"}
