### ISSUE TITLE
Rebuild Flux Function tooltip using Clockface Popover

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#15419]
Located in `ToolbarFunction.tsx`

![image](https://user-images.githubusercontent.com/2433762/66850609-01d85680-ef2e-11e9-9454-646ffedd3d08.png)

**Comment by Asalem1** [comment]
@alexpaxton I assume that this should also encompass the `VariableItem` `<VariableTooltipContents>` too, correct?

**Comment by alexpaxton** [comment]
@Asalem1 yes!
