### ISSUE TITLE
Add TLS support to InfluxDB 2.0

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#15436]
Currently the 2.0 alpha does not support serving connections over TLS. This is something InfluxDB 1.x can do, and something we need to support in 2.0.

At a minimum we should provide the following to the user:

 - [ ] the ability to provide a certificate and private key via cli flags;

We should ensure that when provided TLS is enabled on the HTTP server, and that all resources are served over an established TLS transport.

When using the UI, we need to verify how a browser will handle backend API communication with the server is self-signed certificates have been used...

Some features that are currently in InfluxDB 1.x, which would be nice to carry over to 2.x are described in #15437

**Comment by rawkode** [comment]
I'll close #12976 in favour of this issue with more information :+1:

**Comment by rawkode** [comment]
Closed by #15411
