### ISSUE TITLE
Add ability to specify minimum and maximum acceptable TLS version

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#15437]
In https://github.com/influxdata/influxdb/issues/15436 we will add TLS support to InfluxDB 2.0.

There are some features we have in InfluxDB 1.7.x that would be nice to carry over to the 2.x line. Specifically:

```
[tls]
  # Determines the available set of cipher suites. See https://golang.org/pkg/crypto/tls/#pkg-constants
  # for a list of available ciphers, which depends on the version of Go (use the query
  # SHOW DIAGNOSTICS to see the version of Go used to build InfluxDB). If not specified, uses
  # the default settings from Go's crypto/tls package.
  # ciphers = [
  #   "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
  #   "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  # ]

  # Minimum version of the tls protocol that will be negotiated. If not specified, uses the
  # default settings from Go's crypto/tls package.
  # min-version = "tls1.2"

  # Maximum version of the tls protocol that will be negotiated. If not specified, uses the
  # default settings from Go's crypto/tls package.
  # max-version = "tls1.2"
```

That is: 

 - the ability to specify which TLS ciphers that you are willing to support;
 - a minimum version of the TLS protocol that a client and the server may negotiate; and
 - a maximum version of the TLS protocol that a client and the server may negotiate.

**Comment by rawkode** [comment]
@e-dard Should we perhaps, at least for the initial release, lock this down to "best practice"; then on a subsequent release, aim for configuration?

```
&tls.Config{
        MinVersion:               tls.VersionTLS12,
        CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
        PreferServerCipherSuites: true,
        CipherSuites: []uint16{
            tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
            tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
            tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
            tls.TLS_RSA_WITH_AES_256_CBC_SHA,
        },
    }
```

This comes from https://github.com/denji/golang-tls, which suggests it passes the security tests with perfect score.

**Comment by e-dard** [comment]
@rawkode yeah I think we just land #15436 first

**Comment by rawkode** [comment]
@e-dard Now that #15436 has landed, what should the plan be to adopt best practice?

**Comment by timhallinflux** [comment]
TLS 1.3 is out now.
