### ISSUE TITLE
Ease of use: Display Org ID in the Org Profile page

### ISSUE THREAD

**Issue by nisley** [influxdata/influxdb#15442]
As a user trying to use the API, I search around for the Org ID

If you are in the know, you know the org id is in the URL.  But lots of folks don't know that and may end up in the Org Profile.  It would be nice if the Org Profile listed the name of the org and the org ID - right now it just offers an org rename:

![image](https://user-images.githubusercontent.com/1389799/66963468-9f17b580-f028-11e9-8785-94fb91742b3c.png)

**Comment by alexpaxton** [comment]
Seems like low hanging fruit, I could tackle this one

**Comment by russorat** [comment]
should this be in the CLient Libs page?

**Comment by russorat** [comment]
bump

**Comment by russorat** [comment]
We now display org and user id in this page.
