### ISSUE TITLE
query() does not return data if backslash character exists in tag value

### ISSUE THREAD

**Issue by michalspondr** [influxdata/influxdb#15449]
I need to use backslash character in my InfluxDB query. I am able to write the point to database, but I am not able to read it.

Here is the example of code (using influxdb-5.2.3 package):

```python
#!/usr/bin/python3
from influxdb import InfluxDBClient
client = InfluxDBClient('influxdb', 8086)
client.switch_database('test')
points = [{"measurement": "mytest",
           "tags": {"mytag": "x"},
           "fields": {"value": "foo"}
           }]
client.write_points(points)

# Here's the problem
res = client.query("SELECT * FROM mytest WHERE mytag=$tag",
                   bind_params={"tag": "\\"})

# Prints [] :-(
print(list(res.get_points()))
```

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run the code on running InfluxDB database
2. Note that tag value with \ character is inserted in database

__Expected behavior:__
ResultSet returns data with inserted row

__Actual behavior:__
ResultSet is empty

__Environment info:__

* System info: Linux 5.2.18-200.fc30.x86_64 x86_64
* InfluxDB version: InfluxDB v1.7.8 (git: 1.7 ff383cdc0420217e3460dabe17db54f8557d95b6)
* Influxdb package from Pip: 5.2.3

**Comment by tompropst** [comment]
I would like to reopen this issue. This seems to happen with forward slashes too. In my case, I have a key that contains MQTT topics. I am unable to use bind parameters as a topic filter.
