### ISSUE TITLE
Update 1.x to Flux v0.50.0

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#15453]
We need to update the 1.x line to use Flux v0.50.0

**Comment by nathanielc** [comment]
Note Dependency injection changed so that will need to be updated. We expect other things to be straightforward.

**Comment by jsternberg** [comment]
Just need to do this for 1.8 now. It was done for 1.7 in #15524.

**Comment by jsternberg** [comment]
This is done now.
