### ISSUE TITLE
Add the ability to filter long lists of variables in the dashboard

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15458]
as a user
when i have a long list of values for a variable in my dashboard
then i would like the ability to filter those values instead of having to scroll

![Kapture 2019-10-17 at 13 55 34](https://user-images.githubusercontent.com/4805997/67046818-dc8e4880-f0e5-11e9-9dc0-8e2c0d1a6bbe.gif)

**Comment by desa** [comment]
Closing in favor https://github.com/influxdata/idpe/issues/3406
