### ISSUE TITLE
Refactor 'Create Organization' Overlay

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#15462]
This is a subset of https://github.com/influxdata/influxdb/issues/15456

This overlay is currently tied to a route, which causes it to be "blank" underneath. Instead of being tied to a route this overlay should be handled solely via the overlay show action. This should not affect our tracking data since `Create Org` is not available to cloud users

![Screen Shot 2019-10-17 at 2 49 00 PM](https://user-images.githubusercontent.com/2433762/67050537-9a690500-f0ed-11e9-9279-5406a9175f9b.png)

**Comment by russorat** [comment]
bump

**Comment by russorat** [comment]
The UI has changed a lot since 2019, so closing this for now.
