### ISSUE TITLE
simple8b: fails pointer alignment check

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#15509]
New in go tip is a checkptr flag: https://groups.google.com/forum/#!msg/golang-dev/SzwDoqoRVJA/IvtnBW5oDwAJ

If you use [golang.org/dl/gotip](https://godoc.org/golang.org/dl/gotip) or otherwise build from source, and run `GO111MODULE=on gotip test -gcflags=all=-d=checkptr ./tsdb/tsm1/` you will get a panic like this, indicating incorrect pointer alignment:

```
--- FAIL: TestIntegerArrayEncodeAll_Compare (0.00s)
panic: (runtime.ptrAlign) (0x1a275c0,0xc0001f8200) [recovered]
	panic: (runtime.ptrAlign) (0x1a275c0,0xc0001f8200)

goroutine 31 [running]:
testing.tRunner.func1(0xc0001f4700)
	/Users/mr/gotip/src/github.com/golang/go/src/testing/testing.go:874 +0x3a3
panic(0x1a275c0, 0xc0001f8200)
	/Users/mr/gotip/src/github.com/golang/go/src/runtime/panic.go:679 +0x1b2
github.com/influxdata/influxdb/pkg/encoding/simple8b.DecodeBytesBigEndian(0xc000166008, 0x3e7, 0x3e7, 0xc00016e589, 0x530, 0x577, 0xc00016e580, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdata/influxdb/pkg/encoding/simple8b/encoding.go:493 +0x7e
github.com/influxdata/influxdb/tsdb/tsm1.integerBatchDecodeAllSimple(0xc00016e580, 0x539, 0x580, 0x0, 0x0, 0x3e8, 0x539, 0x539, 0xc00012c008, 0xc00012c000, ...)
	/Users/mr/go/src/github.com/influxdata/influxdb/tsdb/tsm1/batch_integer.go:212 +0x204
github.com/influxdata/influxdb/tsdb/tsm1.IntegerArrayDecodeAll(0xc00016e580, 0x539, 0x580, 0x0, 0x0, 0x0, 0xc00016e580, 0x539, 0x580, 0x0, ...)
	/Users/mr/go/src/github.com/influxdata/influxdb/tsdb/tsm1/batch_integer.go:150 +0x95
github.com/influxdata/influxdb/tsdb/tsm1.testIntegerArrayEncodeAll_Compare(0xc0001f4700, 0xc00012c000, 0x3e8, 0x3e8, 0xd2b6601)
	/Users/mr/go/src/github.com/influxdata/influxdb/tsdb/tsm1/batch_integer_test.go:105 +0x508
github.com/influxdata/influxdb/tsdb/tsm1.TestIntegerArrayEncodeAll_Compare(0xc0001f4700)
	/Users/mr/go/src/github.com/influxdata/influxdb/tsdb/tsm1/batch_integer_test.go:61 +0x13a
testing.tRunner(0xc0001f4700, 0x1b29868)
	/Users/mr/gotip/src/github.com/golang/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/Users/mr/gotip/src/github.com/golang/go/src/testing/testing.go:960 +0x351
FAIL	github.com/influxdata/influxdb/tsdb/tsm1	0.113s
```

The failure is in this method: https://github.com/influxdata/influxdb/blob/aa34444df439a7649554f1e80eee032ca70c0f38/pkg/encoding/simple8b/encoding.go#L483-L498

and it appears to also be present in the 1.8 branch.

If you run all of our tests, there are other failed checks in go-cmp and bbolt, so we should plan on upgrading those dependencies once appropriate fixes land. There are also some failed checks in arrow, but I am not yet sure if those are a mistake on our end or a bug in arrow.

**Comment by jacobmarble** [comment]
My IDE tells me that `DecodeBytesBigEndian` isn't called in master. Also IDPE doesn't call it, so maybe we can remove it.

1.x does make use of `DecodeBytesBigEndian`, however.

**Comment by tmgordeeva** [comment]
In master, I see `simple8b.DecodeBytesBigEndian` called in https://github.com/influxdata/influxdb/blob/master/tsdb/tsm1/batch_integer.go#L212

Running `checkptr` on the `1.8` branch I also get an error in roaring bitmaps at https://github.com/influxdata/roaring/blob/master/bitmapcontainer.go#L536

**Comment by jacobmarble** [comment]
> In master, I see `simple8b.DecodeBytesBigEndian` called in https://github.com/influxdata/influxdb/blob/master/tsdb/tsm1/batch_integer.go#L212

@tmgordeeva I see this as well. Can you port #15885 to the master branch.
