### ISSUE TITLE
Fix event markers jitter

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#15518]
- Event markers tooltip has a jitter that needs to be fixed. it blinks on and off.

**Comment by desa** [comment]
* CheckPlot in CheckEditorOverlay

**Comment by desa** [comment]
Initial design should only display crit and warn. ok status events should be ignored.

**Comment by desa** [comment]
This feature requires you to enabled the `eventMarkers` feature flag

```
influx.toggleFeature('eventMarkers')
```

Status markers will then be visible in the Edit check page.

![Screenshot 2019-10-21 14 04 09](https://user-images.githubusercontent.com/1477539/67230680-b3cec180-f40b-11e9-87dd-abcea636e399.png)


@ebb-tide what are the steps to trigger the jitter?

**Comment by ebb-tide** [comment]
The jitter happens when user hovers over the rectangular bars above the graph

**Comment by Asalem1** [comment]
Blocked by Issue #15554
