### ISSUE TITLE
Add filtering to event markers

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#15520]
We need to be able to filter event markers by status. Needs design input on where the filtering goes.

**Comment by desa** [comment]
@ebb-tide Which page should this be on?

**Comment by ebb-tide** [comment]
Time machine displaying checkPlot

![Screen Shot 2019-10-21 at 11 36 28 AM](https://user-images.githubusercontent.com/10937678/67232877-0e115780-f3f7-11e9-9b49-0ca98365ca5e.png)

**Comment by ebb-tide** [comment]
Closed in https://github.com/influxdata/influxdb/pull/15874
