### ISSUE TITLE
Fetching task gives `Uncaught TypeError: Cannot destructure property `name` of 'undefined' or 'null'.`

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15534]
This happens in master commit: 804f0b012596ed36be102d7c739dc5ab54acecc3

when i try to view a task that was created a few weeks ago

![image](https://user-images.githubusercontent.com/4805997/67316715-d02b3680-f4bd-11e9-853e-4b066f408a63.png)

**Comment by Asalem1** [comment]
I think @121watts is unintentionally working on this

**Comment by Asalem1** [comment]
In addition to bug mentioned, the edit task page is failing to load the task option data on the left-hand side of the page once it is set:

![task](https://user-images.githubusercontent.com/19984220/67334962-d75f3e00-f4d7-11e9-9b95-4abca228f270.gif)

**Comment by Asalem1** [comment]
The `every` data should also persist when toggling between the scheduled tasks:

![edit_task](https://user-images.githubusercontent.com/19984220/67339089-599f3080-f4df-11e9-8972-c661bf8f8979.gif)
