### ISSUE TITLE
[UI - Templates] user templates list is not updating reliably after import template

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#15530]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

This issue is showing up intermittently, so try the following steps maybe a dozen times.  It shows up in one out of every five or six runs of import template tests. 

1. open settings > templates
2. click "user templates"
3. click import template in the list header (top right)
4. in the system dialog browse to a valid template.json file and upload it
5. click the submit button (page reloads to static templates - issue #15514)
6. click "user templates" again (work around for #15514)

__Expected behavior:__
Expect to see reliably (99.9% of the time) the template just uploaded. 

__Actual behavior:__
About one in six times the newly uploaded template fails to appear in the list of user templates. 

Clicking the browser refresh button seems to work to solve this manually, however in the automated tests "refresh()" has not proven a reliable solution. 

__Screencast__
![ImportTemplateStaleList01](https://user-images.githubusercontent.com/25881301/67302642-7a708180-f4f1-11e9-8243-338ae763956f.gif)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.4.0-166-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly build docker image 
```
ts=2019-10-22T08:09:53.872645Z lvl=info msg="Welcome to InfluxDB" log_id=0Idd5Bp0000 version=nightly commit=1e69c517b build_date=2019-10-22T07:28:00Z
```
* Other relevant environment details: Container runtime, disk info, etc
browser: __Chrome 77__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled. 

```
--e2e-testing=true
```

**Comment by TCL735** [comment]
TemplatesPage does not refresh when user successfully imports first template after visiting /orgs/[id]/settings/templates

It requires another successful import to see the previous (but not the current) user-imported template. Or a hard refresh will show all user-imported templates.

**Comment by TCL735** [comment]
Another issue: after a successful import of a user defined template, the page goes back to the tab for "Static Templates" rather than staying on the "User Templates" tab.
