### ISSUE TITLE
UI making requests with `undefined` bucket when switching back to explorer

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15533]
So i am seeing that when i switch back to the data explorer from another page, there is a query that is being run but cancelled where the bucket is "undefined". See the animated gif below.

![Kapture 2019-10-22 at 10 39 40](https://user-images.githubusercontent.com/4805997/67314249-3c576b80-f4b9-11e9-8f4b-dbfb6582d319.gif)

**Comment by russorat** [comment]
bump

**Comment by drdelambre** [comment]
apparently there's nothing lower than a sev-4?
