### ISSUE TITLE
UI: things not sorted in the UI

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15544]
- ~List of dashboards on homepage~ [16919](https://github.com/influxdata/influxdb/pull/16919)
- variables list in the script editor
- dashboard list in the Save As... dashboard option from data explorer
- ~buckets list in save as task from data explorer~ [15769](https://github.com/influxdata/influxdb/pull/15769)
- List if Notification Endpoints
- List of Notification Rules
- List of Checks

**Comment by russorat** [comment]
this would be sooooo nice

**Comment by desa** [comment]
stale

**Comment by russorat** [comment]
not stale
