### ISSUE TITLE
Task name in options form does not update

### ISSUE THREAD

**Issue by AlirieGray** [influxdata/influxdb#15552]
When I click on one task to edit it, the first time I go to edit another task the name that shows up in the options form on the left does not change. Then if I go to the same task again, it does update the name.

![2019-10-23 11 48 27](https://user-images.githubusercontent.com/15273162/67424494-113d4c80-f58b-11e9-8c95-e9064527a4f0.gif)

**Comment by Asalem1** [comment]
I can't seem to reproduce this error:

![cannot_reproduce](https://user-images.githubusercontent.com/19984220/67903024-cb9ef780-fb27-11e9-9e5c-804c43bb0c36.gif)

I'll write up some UI tests to make sure that this should function correctly, but in the meantime I would love if another @influxdata/monitoring-team member could try and reproduce this
