### ISSUE TITLE
Task edit page crashes 

### ISSUE THREAD

**Issue by AlirieGray** [influxdata/influxdb#15551]
InfluxDB master
Clicked on a task name to edit and got a crash screen with this error in console:

<img width="657" alt="Screen Shot 2019-10-23 at 11 40 11 AM" src="https://user-images.githubusercontent.com/15273162/67423934-0209cf00-f58a-11e9-8709-e2d048bc59ac.png">

**Comment by desa** [comment]
@AlirieGray Just tried to reproduce this myself, but was unable to. Do you have the task that caused this issue?
