### ISSUE TITLE
Query builder cannot express common queries

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15563]
Related https://github.com/influxdata/influxdb/pull/15545

1. See #15984 

2. Get last value across all series for a time range

![last](https://user-images.githubusercontent.com/1477539/67504754-013f6e80-f658-11e9-8bfd-b2ebeeb9d8f6.gif)

More of less the query we want to express is

```
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "disk")
  |> filter(fn: (r) => r._field == "used_percent")
  |> last()
  |> group()
```

**Comment by desa** [comment]
@r1ckbrown cc

**Comment by desa** [comment]
Plan is to add special functions to functions window.

**Comment by hoorayimhelping** [comment]
related: https://github.com/influxdata/influxdb/issues/16076

**Comment by kristinarobinson** [comment]
Will solve with flows.
