### ISSUE TITLE
/users endpoint should have a reference to /users/{id}/password in the links

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15576]
I believe this endpoint should have a link to /password in the links section.

The swagger should also be updated: https://github.com/influxdata/influxdb/blob/master/http/swagger.yml#L7215

GET /api/v2/users/03c920f546729000
```json
{
    "links": {
        "logs": "/api/v2/users/03c920f546729000/logs",
        "self": "/api/v2/users/03c920f546729000"
    },
    "id": "03c920f546729000",
    "name": "russ",
    "status": ""
}
```

**Comment by jademcgough** [comment]
My understanding of our hypermedia api design is that links in responses only document urls that respond to GET requests (whereas `/password` is POST only). Not sure if this is documented anywhere so I could be wrong.
