### ISSUE TITLE
Orgs list is missing from UI Nav

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15587]
![wheres-the-orgs-list](https://user-images.githubusercontent.com/1477539/67603587-5c03c380-f747-11e9-80df-fbeb409f140c.gif)

**Comment by desa** [comment]
cc @alexpaxton 

Link https://github.com/influxdata/influxdb/issues/14849

**Comment by karel-rehor** [comment]
Also noticed this in nightly build
```
ts=2019-10-29T08:34:24.073719Z lvl=info msg="Welcome to InfluxDB" log_id=0ImfGznG000 version=nightly commit=c912ee3fc build_date=2019-10-29T07:22:57Z
```
