### ISSUE TITLE
[UI - Homepage] Account section missing logout button

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#15622]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Onboard and create new user and organization
2. Complete onboarding to quick start - open homepage 

__Expected behavior:__
Expected to find logout button in the Account panel of the homepage. 

__Actual behavior:__
There is no logout button in the Account panel. 

__Screenshot__ 

![HomepageLogoutMissing01](https://user-images.githubusercontent.com/25881301/67753657-55ba6380-fa35-11e9-8cf7-9e9a92352fce.png)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.4.0-166-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly build docker image. 
```
ts=2019-10-29T08:34:24.073719Z lvl=info msg="Welcome to InfluxDB" log_id=0ImfGznG000 version=nightly commit=c912ee3fc build_date=2019-10-29T07:22:57Z
```
* Other relevant environment details: Container runtime, disk info, etc
browser: __Chrome 77__

__Config:__
Started with debug flush enabled. 
```
--e2e-testing=true
```

**Comment by ebb-tide** [comment]
Closed by https://github.com/influxdata/influxdb/pull/15612
