### ISSUE TITLE
[Monaco] Describe grammar for syntax highlighting

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#15639]
Implement syntax highlighting for keywords, brackets and symbols. 

Monaco uses Monarch format for grammar definition. 
https://microsoft.github.io/monaco-editor/monarch.html

might want to refer to the native tokenizer for flux: https://github.com/influxdata/flux/blob/master/internal/scanner/scanner.rl

VSCode uses textmate format. monarch vs textmate grammar sadness: 
https://news.ycombinator.com/item?id=14259463
https://stackoverflow.com/questions/37936919/writing-visual-studio-code-syntaxes-in-monarch

**Comment by desa** [comment]
I came across https://github.com/NeekSandhu/monaco-textmate, not sure if this helps us at all.

**Comment by desa** [comment]
Tools team is maintaining a textmate compatible syntax highlighter and we should use that.

**Comment by desa** [comment]
cc @kelwang ^^

**Comment by sanderson** [comment]
@desa @kelwang Is the syntax highlighter specific to Flux? Is it public?

**Comment by desa** [comment]
@sanderson Monaco has support for multiple formats that are prebuilt into the library. The tools team has been working on a syntax highligher for vscode using the textmate format (which has become the standard format for text editors.

**Comment by kelwang** [comment]
https://github.com/influxdata/vsflux/blob/master/syntaxes/flux.tmLanguage.json
