### ISSUE TITLE
[Monaco] Implement scrollbars

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#15638]
Make monaco scrollbars match current scrollbars.

**Comment by desa** [comment]
cc @alexpaxton  / consider if native monaco scroll bars are ok?

**Comment by alexpaxton** [comment]
@desa can I see a screenshot or maybe do a quick call with someone and have them show me how it looks live?

**Comment by desa** [comment]
@drdelambre ^^

**Comment by drdelambre** [comment]
we have chatted and demo'd and paxton is taking a look at it

**Comment by drdelambre** [comment]
@alexpaxton  says it looks good enough to ship and get more eyes on it
