### ISSUE TITLE
visual jank on transition to telegraf settings overlay

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#15644]
There is a strange momentary loading state in the transition to the telegraf settings overlay

![Kapture 2019-10-29 at 13 26 54](https://user-images.githubusercontent.com/10937678/67806851-f10d0200-fa50-11e9-9085-f1949c481725.gif)
![Screen Shot 2019-10-29 at 1 28 52 PM](https://user-images.githubusercontent.com/10937678/67806857-f36f5c00-fa50-11e9-80d2-5ab0a8d66da5.png)

**Comment by desa** [comment]
I think this is no longer an issue
