### ISSUE TITLE
ctrl + enter to submit a query doesn't update the "submit" button icon

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15668]
as a user
when i use ctrl + enter to submit a query
then i would like some indication that the query is executing

in the gif below, i am hitting ctrl+enter to submit the query. if i didn't have my network tab open, i wouldn't have any indication that the query was running.

![Kapture 2019-10-30 at 13 54 06](https://user-images.githubusercontent.com/4805997/67898138-fafc3700-fb1c-11e9-881a-ef09b6efc662.gif)

**Comment by TCL735** [comment]
Needs design input. What sort of indication is stylistically appropriate? @alexpaxton

**Comment by russorat** [comment]
@TCL735 no design input needed. it should look the same as if a user clicks the submit button.

**Comment by Asalem1** [comment]
After speaking with @russorat about the original issue - it seems like it may have been addressed by a different UI modification. Put simply, this PR was meant to address an issue where users didn't have sufficient feedback to their actions whenever using the hot keys to submit queries. However, recent UI changes indicate that the data is reloading, and therefore renders these changes unnecessary
