### ISSUE TITLE
`Click to Add` Styling bug when hovering over Data Explorer/functions

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#15680]
`Click to Add` text is condensed and goes beyond the line height. Need clarity on whether this is the intended functionality or whether the helper text should be modified to fit the screen (i.e. be spliced rather than wrap, increase the line height whenever a text wraps, etc...)

**Comment by Asalem1** [comment]
@russorat what should be the best way to handle this moving forward?

<img width="584" alt="Screen Shot 2019-10-31 at 6 05 44 AM" src="https://user-images.githubusercontent.com/19984220/67949456-fa0ee800-fba4-11e9-893c-c0386fce1d14.png">

**Comment by russorat** [comment]
Maybe it should just me a plus icon? or the word Add.

**Comment by russorat** [comment]
bump

**Comment by desa** [comment]
no longer an issue
