### ISSUE TITLE
Stop skipping flux pre-check tests

### ISSUE THREAD

**Issue by gavincabbage** [influxdata/influxdb#15688]
[This test](https://github.com/influxdata/influxdb/blob/master/ui/cypress/e2e/tasks.test.ts#L28-L29) has been temporarily skipped pending resolution of [flux#2085](https://github.com/influxdata/flux/issues/2085).

When the above issue is resolved, the skipped test should be reevaluated and either reenabled or removed completely if no longer necessary.

**Comment by jlapacik** [comment]
The type system refactor will make it so that a `to()` call that doesn't specify a bucket will not compile. This test should be re-enabled as part of https://github.com/influxdata/flux/issues/1943.

**Comment by gavincabbage** [comment]
Closing this issue as we've opted to revert the change that introduced the skipped test, removing this issue for now. We will still want to consume the output of the flux work described in influxdata/flux#1943.
