### ISSUE TITLE
Empty Builder Configs make flux queries throw exception in dashboard show page

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#15708]
I expect the page to render, and with all dropdowns when providing the dashboard view with a valid flux query. 

Steps to reproduce: 

- create a dashboard with a cell that contains a single stat view (2 api calls). Provide the single stat view a valid flux query but no builder config data.
- load up show page of dashboard, should see somethign like the following:

![image](https://user-images.githubusercontent.com/17263167/67991715-6f0b0d80-fbf7-11e9-85b7-051a14c63d2d.png)
![image](https://user-images.githubusercontent.com/17263167/67991795-aed1f500-fbf7-11e9-94b6-25de6b72b7f2.png)

when the builder config has a tag provided like the following it will render the chart:
![image](https://user-images.githubusercontent.com/17263167/67991746-877b2800-fbf7-11e9-8ceb-2dfcced1addf.png)
![image](https://user-images.githubusercontent.com/17263167/67991808-c0b39800-fbf7-11e9-9bae-b3ee35e3b8d6.png)

**Comment by drdelambre** [comment]
@jsteenb2 idk how to repro this, but we just refactored a bunch of code in here. could you verify it's still an issue?

**Comment by jsteenb2** [comment]
I don't see the issue that I had before. this looks to have been addressed.

fwiw, standing up a dashboard through the api is as simple as

```sh
influx pkg -f $PWD/pkger/testdata/dashboard_single_stat_plus_line.yml
```

there are numerous pkgs within the `pkger/testdata` dir that you can use to stand things up
