### ISSUE TITLE
Date Selector errors in delete with predicate UI

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15716]
![date-selector errors](https://user-images.githubusercontent.com/1477539/68040760-5f4a0280-fca5-11e9-8435-4cd9c752c4af.png)

**Comment by Asalem1** [comment]
Should also refactor the DateSelector to be in a Popover:

https://github.com/influxdata/influxdb/issues/15420

See previous PR for refactor tips:

https://github.com/influxdata/influxdb/pull/15613
