### ISSUE TITLE
Measurement remains even if no data points are present

### ISSUE THREAD

**Issue by mdevy-influxdata** [influxdata/influxdb#15718]
InfluxDB version: v1.6.5

It has been observed that measurements are not being dropped, even though there are no more data points for that specific measurement.  Data is being evicted using retention policy, so no manual intervention is taking place.  

The expected/desired behavior is that once the last data point has been evicted via retention policy, that the measurement (which is then empty), is also dropped to recover any system resources.

**Comment by e-dard** [comment]
Can you try and reproduce on the latest release? (1.7.8) Happy to look at this after that.

**Comment by e-dard** [comment]
Please feel free to file another issue if there is a reproducible defect on the latest 1.7.x release.
