### ISSUE TITLE
Implement policy if data written to RP's end-time plus period

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#1571]
It is possible for data to be written to a time that is earlier than the retention policy make sensible. We need to either block the write, or silently drop the data. This is because the data is effectively inaccessible once the retention check kicks in.

**Comment by beckettsean** [comment]
RFC: What should the behavior be when writing points to a retention policy that exceed the retention period? For example, if I write points with a timestamp 2 years in the past to a retention policy that retains data for 30 days, as soon as the retention check runs the data will be silently dropped.

Should the write succeed? If so, should it also return a warning? If not, what should the error message say? What if only some points in a batch exceed the retention period?

**Comment by otoolep** [comment]
It is relatively easy to detect if points are destined for a retention policy, such that the timestamps of the data will (almost) immediately be deleted. Continually writing data into the past like this puts unnecessary load on the system as shards will be created, and then (almost) immediately deleted. 

@pauldix once mentioned to me that writing into the past like this is something that does happen in the field, and people get confused when the data quickly disappears. Defaulting to rejecting the write may be the right thing to do.

Individual points in a batch can fail for many reasons, even if others go through (downed nodes for example). If we agree that writes far into the past should be rejected, the error handling would be similar to those other types of failures.

**Comment by jsternberg** [comment]
Closing this in favor of the newer #6708.
