### ISSUE TITLE
panic in 1.7.8 while executing localintersect2by2 function

### ISSUE THREAD

**Issue by pen1120** [influxdata/influxdb#15729]
When using the 1.7.8 version of influxdb, the process exits abnormally, the stack information is as follows。

unexpected fault address 0x7f09a0df2bcb
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f09a0df2bcb pc=0x98680d]

goroutine 12026712526 [running]:
runtime.throw(0x12f8512, 0x5)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc37a5b4a48 sp=0xc37a5b4a18 pc=0x42df92
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:397 +0x275 fp=0xc37a5b4a98 sp=0xc37a5b4a48 pc=0x443845
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.localintersect2by2(0x7f09a0df2bcb, 0x1, 0x64fab0, 0x7f09a45276b6, 0x1, 0xd4b104, 0xc6a8714586, 0x0, 0x1, 0xc6a8714586)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/setutil.go:330 +0x2d fp=0xc37a5b4aa8 sp=0xc37a5b4a98 pc=0x98680d
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.intersection2by2(0x7f09a0df2bcb, 0x1, 0x64fab0, 0x7f09a45276b6, 0x1, 0xd4b104, 0xc6a8714586, 0x0, 0x1, 0x1)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/setutil.go:255 +0x121 fp=0xc37a5b4b08 sp=0xc37a5b4aa8 pc=0x986531
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.(*arrayContainer).andArray(0xc249c2c380, 0xc31d138c60, 0x1681cc0, 0xc150bf6380)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/arraycontainer.go:807 +0x109 fp=0xc37a5b4b80 sp=0xc37a5b4b08 pc=0x9588e9
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.(*arrayContainer).and(0xc249c2c380, 0x1681cc0, 0xc31d138c60, 0x1681cc0, 0xc150bf6380)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/arraycontainer.go:506 +0x22a fp=0xc37a5b4bc8 sp=0xc37a5b4b80 pc=0x956dfa
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.And(0xc43775e230, 0xc4eb829490, 0xc30af35960)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/roaring.go:1005 +0x122 fp=0xc37a5b4c58 sp=0xc37a5b4bc8 pc=0x969922
github.com/influxdata/influxdb/tsdb.(*SeriesIDSet).And(0xc41b4a4500, 0xc30af35960, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_set.go:160 +0xba fp=0xc37a5b4c88 sp=0xc37a5b4c58 pc=0x9b64ba
github.com/influxdata/influxdb/tsdb.IntersectSeriesIDIterators(0x7eeeb1ff6b40, 0xc6080e5440, 0x7eeeb1ff6b40, 0xc31cd01780, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:527 +0x18c fp=0xc37a5b4d00 sp=0xc37a5b4c88 pc=0x99831c
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc867b18320, 0x1, 0x1, 0xc0006f6aa0, 0x0, 0x0, 0x0, 0xc1677412f0, 0x21, 0x30, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:1970 +0x258 fp=0xc37a5b4db8 sp=0xc37a5b4d00 pc=0x9a22a8
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc867b18320, 0x1, 0x1, 0xc0006f6aa0, 0x0, 0x0, 0x0, 0xc1677412f0, 0x21, 0x30, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:1960 +0x19d fp=0xc37a5b4e70 sp=0xc37a5b4db8 pc=0x9a21ed
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc867b18320, 0x1, 0x1, 0xc0006f6aa0, 0x0, 0x0, 0x0, 0xc1677412f0, 0x21, 0x30, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:1960 +0x19d fp=0xc37a5b4f28 sp=0xc37a5b4e70 pc=0x9a21ed
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc867b18320, 0x1, 0x1, 0xc0006f6aa0, 0x0, 0x0, 0x0, 0xc1677412f0, 0x21, 0x30, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:1960 +0x19d fp=0xc37a5b4fe0 sp=0xc37a5b4f28 pc=0x9a21ed
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc867b18320, 0x1, 0x1, 0xc0006f6aa0, 0x0, 0x0, 0x0, 0xc1677412f0, 0x21, 0x30, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:1960 +0x19d fp=0xc37a5b5098 sp=0xc37a5b4fe0 pc=0x9a21ed
github.com/influxdata/influxdb/tsdb.IndexSet.measurementSeriesByExprIterator(0xc867b18320, 0x1, 0x1, 0xc0006f6aa0, 0x0, 0x0, 0x0, 0xc1677412f0, 0x21, 0x30, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:1893 +0xb1 fp=0xc37a5b5158 sp=0xc37a5b5098 pc=0x9a1851
github.com/influxdata/influxdb/tsdb.IndexSet.MeasurementSeriesByExprIterator(0xc867b18320, 0x1, 0x1, 0xc0006f6aa0, 0x0, 0x0, 0x0, 0xc1677412f0, 0x21, 0x30, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:1875 +0xe0 fp=0xc37a5b51e8 sp=0xc37a5b5158 pc=0x9a1730
github.com/influxdata/influxdb/tsdb.(*seriesCursor).readSeriesKeys(0xc3c4253b00, 0xc1677412f0, 0x21, 0x30, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_cursor.go:126 +0xe9 fp=0xc37a5b52f0 sp=0xc37a5b51e8 pc=0x9aa609
github.com/influxdata/influxdb/tsdb.(*seriesCursor).Next(0xc3c4253b00, 0xc00003e0f0, 0xc3ed2ba298, 0xc37a5b5400)
	/go/src/github.com/influxdata/influxdb/tsdb/series_cursor.go:108 +0x79 fp=0xc37a5b5348 sp=0xc37a5b52f0 pc=0x9aa3d9
github.com/influxdata/influxdb/services/storage.(*indexSeriesCursor).Next(0xc353bf3680, 0x15d332929ff9d701)
	/go/src/github.com/influxdata/influxdb/services/storage/series_cursor.go:166 +0x415 fp=0xc37a5b5418 sp=0xc37a5b5348 pc=0xe0d625
github.com/influxdata/influxdb/storage/reads.(*resultSet).Next(0xc56696eea0, 0x166d798)
	/go/src/github.com/influxdata/influxdb/storage/reads/resultset.go:50 +0x41 fp=0xc37a5b5440 sp=0xc37a5b5418 pc=0xe000a1
github.com/influxdata/influxdb/services/httpd.(*Handler).servePromRead(0xc00004ae00, 0x7eefaf4e3100, 0xc3848a3400, 0xc5662baa00, 0x166d720, 0xc4e28ad350)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1109 +0x3ed fp=0xc37a5b5710 sp=0xc37a5b5440 pc=0xe32a9d
github.com/influxdata/influxdb/services/httpd.(*Handler).servePromRead-fm(0x7eefaf4e3100, 0xc3848a3400, 0xc5662baa00, 0x166d720, 0xc4e28ad350)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:190 +0x5c fp=0xc37a5b5750 sp=0xc37a5b5710 pc=0xe4564c
github.com/influxdata/influxdb/services/httpd.authenticate.func1(0x7eefaf4e3100, 0xc3848a3400, 0xc5662baa00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1667 +0x97 fp=0xc37a5b57c8 sp=0xc37a5b5750 pc=0xe42d17
net/http.HandlerFunc.ServeHTTP(0xc000631400, 0x7eefaf4e3100, 0xc3848a3400, 0xc5662baa00)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc37a5b57f0 sp=0xc37a5b57c8 pc=0x7170f4
github.com/influxdata/influxdb/services/httpd.(*Handler).responseWriter.func1(0x165f760, 0xc3848a33e0, 0xc5662baa00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1764 +0xab fp=0xc37a5b5838 sp=0xc37a5b57f0 pc=0xe43eab
net/http.HandlerFunc.ServeHTTP(0xc000631420, 0x165f760, 0xc3848a33e0, 0xc5662baa00)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc37a5b5860 sp=0xc37a5b5838 pc=0x7170f4
github.com/influxdata/influxdb/services/httpd.gzipFilter.func1(0x165f760, 0xc3848a33e0, 0xc5662baa00)
	/go/src/github.com/influxdata/influxdb/services/httpd/gzip.go:23 +0x29d fp=0xc37a5b58b8 sp=0xc37a5b5860 pc=0xe4229d
net/http.HandlerFunc.ServeHTTP(0xc000631440, 0x165f760, 0xc3848a33e0, 0xc5662baa00)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc37a5b58e0 sp=0xc37a5b58b8 pc=0x7170f4
github.com/influxdata/influxdb/services/httpd.cors.func1(0x165f760, 0xc3848a33e0, 0xc5662baa00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1706 +0xf3 fp=0xc37a5b5a40 sp=0xc37a5b58e0 pc=0xe435a3
net/http.HandlerFunc.ServeHTTP(0xc000631460, 0x165f760, 0xc3848a33e0, 0xc5662baa00)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc37a5b5a68 sp=0xc37a5b5a40 pc=0x7170f4
github.com/influxdata/influxdb/services/httpd.requestID.func1(0x165f760, 0xc3848a33e0, 0xc5662baa00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1737 +0x179 fp=0xc37a5b5ad0 sp=0xc37a5b5a68 pc=0xe439c9
net/http.HandlerFunc.ServeHTTP(0xc000631480, 0x165f760, 0xc3848a33e0, 0xc5662baa00)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc37a5b5af8 sp=0xc37a5b5ad0 pc=0x7170f4
github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1(0x1664560, 0xc428da7340, 0xc5662baa00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1801 +0x147 fp=0xc37a5b5b90 sp=0xc37a5b5af8 pc=0xe44407
net/http.HandlerFunc.ServeHTTP(0xc0006314a0, 0x1664560, 0xc428da7340, 0xc5662baa00)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc37a5b5bb8 sp=0xc37a5b5b90 pc=0x7170f4
github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc000630f40, 0x1664560, 0xc428da7340, 0xc5662baa00)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat/mux.go:117 +0x155 fp=0xc37a5b5cf8 sp=0xc37a5b5bb8 pc=0xc94e55
github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0xc00004ae00, 0x1664560, 0xc428da7340, 0xc5662baa00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:392 +0x247 fp=0xc37a5b5d48 sp=0xc37a5b5cf8 pc=0xe2c167
net/http.serverHandler.ServeHTTP(0xc33f5748f0, 0x1664560, 0xc428da7340, 0xc5662baa00)
	/usr/local/go/src/net/http/server.go:2741 +0xab fp=0xc37a5b5d78 sp=0xc37a5b5d48 pc=0x719ddb
net/http.(*conn).serve(0xc3bb7a8960, 0x1666020, 0xc66baae980)
	/usr/local/go/src/net/http/server.go:1847 +0x646 fp=0xc37a5b5fc8 sp=0xc37a5b5d78 pc=0x716156
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc37a5b5fd0 sp=0xc37a5b5fc8 pc=0x45d971
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5

[panic.log](https://github.com/influxdata/influxdb/files/3802956/panic.log)

**Comment by foobar** [comment]
still seen on v1.8.x 
please re-open

**Comment by kannan-rafay** [comment]
we are experiencing the same issue ? @foobar how do you mitigate it ?

**Comment by lesam** [comment]
This is likely caused by doing a query during a compaction. We mmap some series data directly into memory from a file - if the backing store (the TSI file) is deleted during a query, the query can crash. See `func (e *TagBlockValueElem) SeriesIDSet() (*tsdb.SeriesIDSet, error)`.

We have locks to prevent deleting series files while there are open queries that require them - this logic was recently tightened to prevent this kind of bug, see e.g. #22040 .

@kannan-rafay are you seeing this on 2.x? Are you able to upgrade to 2.x?

**Comment by lesam** [comment]
See also issue at https://github.com/influxdata/influxdb/issues/22000

**Comment by kannan-rafay** [comment]
Hi Sam , thank you for the information , we are lagging in the upgrades , still in 1.7.10 , planning to upgrade to 1.8.x , could you recommend  the minor version of 1.8.x to upgrade or can we migrate to 2.x  skipping other releases , please note we want to use  influxQL for sometime , but then can we do mapping as is detailed  @ https://docs.influxdata.com/influxdb/v2.1/query-data/influxql/ ? please guide. 

I believe this issue is fixed  in  [v2.0.8](https://docs.influxdata.com/influxdb/v2.1/reference/release-notes/influxdb/#v208-2021-08-13)  ,  was this back-ported to 1.8.x release ? I think no , am i correct ?

**Comment by lesam** [comment]
The issue I linked may be the one you're seeing - hard to say, there's been a lot of change since 1.7 and our team is currently focussed on getting OSS 2.2 finished.

I always recommend the latest version (currently OSS 2.1.1). If anyone sees this issue on 2.x (or even better, has a reliable reproduction on any version) we can re-open this issue and look at it.

Definitely 2.x releases will continue to support InfluxQL as described in the doc you linked.

**Comment by ZeroSean** [comment]
still seen on v2.7.1
please re-open
