### ISSUE TITLE
go build fails in github.com/influxdata/flux/stdlib/runtime/runtime.go

### ISSUE THREAD

**Issue by redmark-alt** [influxdata/influxdb#15782]
__Steps to reproduce:__

1. git clone https://github.com/influxdata/influxdb.git
2. git checkout 1.8
3. go get -d ./...
4. go build ./...
# github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/stdlib/runtime
vendor/github.com/influxdata/flux/stdlib/runtime/runtime.go:18:31: cannot use Version (type func() (values.Value, error)) as type func(context.Context, values.Object) (values.Value, error) in argument to values.NewFunction

__Expected behavior:__
Expect code to compile and build target

__Actual behavior:__
go build ./...
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/stdlib/runtime
vendor/github.com/influxdata/flux/stdlib/runtime/runtime.go:18:31: cannot use Version (type func() (values.Value, error)) as type func(context.Context, values.Object) (values.Value, error) in argument to values.NewFunction

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by mark-rushakoff** [comment]
What version of Go are you running? How did your vendor directory get populated if you did a fresh `git clone` and a fresh `go get`?

**Comment by redmark-alt** [comment]
I'm using `go version go1.11.13` on Red Hat UBI linux. I tried both 'git clone` and 'go get`.  The last try was...

```
git clone https://github.com/influxdata/influxdb.git
git checkout 1.8
go get -d -u ./...
go build ./...
# github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/stdlib/runtime
vendor/github.com/influxdata/flux/stdlib/runtime/runtime.go:18:31: cannot use Version (type func() (values.Value, error)) as type func(context.Context, values.Object) (values.Value, error) in argument to values.NewFunction
```

I'm going to try the same steps on my Mac with go 1.13.4

**Comment by mark-rushakoff** [comment]
We do not expect influxdb 1.8 to build properly with `go get` to retrieve dependencies. Use `dep ensure` as instructed in CONTRIBUTING.md: https://github.com/influxdata/influxdb/blob/1.8/CONTRIBUTING.md#build-and-test

**Comment by redmark-alt** [comment]
No joy using `dep ensure` same error. I can say that these steps did work 15 days back.

```
$ git clone https://github.com/influxdata/influxdb.git
$ cd influxdb
$ git checkout 1.8
$ dep ensure
$ go clean ./...
b$ go install ./...
# github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/stdlib/runtime
vendor/github.com/influxdata/flux/stdlib/runtime/runtime.go:18:31: cannot use Version (type func() (values.Value, error)) as type func(context.Context, values.Object) (values.Value, error) in argument to values.NewFunction
```

**Comment by dgnorton** [comment]
@redmark-alt  make sure `GOPATH` is set correctly and  try `dep ensure --vendor-only`

I tested locally with:
```
❯ git clone https://github.com/influxdata/influxdb
Cloning into 'influxdb'...
remote: Enumerating objects: 122, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (103/103), done.
remote: Total 243778 (delta 50), reused 42 (delta 18), pack-reused 243656
Receiving objects: 100% (243778/243778), 115.77 MiB | 26.15 MiB/s, done.
Resolving deltas: 100% (177076/177076), done.
/tmp/src/go/src/github.com/influxdata

❯ cd influxdb 

❯ goenv    (NOTE: goenv is a custom script I use to set GOPATH)
GOPATH set to /tmp/src/go
Appended /tmp/src/go/bin to PATH
On branch master

❯ git checkout 1.8
Branch '1.8' set up to track remote branch '1.8' from 'origin'.
Switched to a new branch '1.8' 

❯ dep ensure --vendor-only

❯ go install ./...

❯ ls $GOPATH/bin 
influx  influxd  influx_inspect  influx_stress  influx_tools  influx_tsm  stress_test_server  test_client
```

**Comment by redmark-alt** [comment]
I guess it's a GO version issue... it worked when I ran the steps on my Mac with GO `1.13.4`

```
bash-4.2$ go version go1.11.13
bash-4.2$ git clone https://github.com/influxdata/influxdb
Cloning into 'influxdb'...
remote: Enumerating objects: 128, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 243783 (delta 53), reused 44 (delta 19), pack-reused 243655
Receiving objects: 100% (243783/243783), 115.80 MiB | 15.44 MiB/s, done.
Resolving deltas: 100% (177079/177079), done.

bash-4.2$ cd influxdb
bash-4.2$ pwd
/opt/app-root/src/go/src/github.com/influxdata/influxdb

bash-4.2$ cd $GOPATH/src/github.com/influxdata/influxdb
bash-4.2$ pwd
/opt/app-root/src/go/src/github.com/influxdata/influxdb

bash-4.2$  git checkout 1.8
Branch 1.8 set up to track remote branch 1.8 from origin.
Switched to a new branch '1.8'

bash-4.2$ dep ensure --vendor-only

bash-4.2$ go install ./...
# github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/stdlib/runtime
vendor/github.com/influxdata/flux/stdlib/runtime/runtime.go:18:31: cannot use Version (type func() (values.Value, error)) as type func(context.Context, values.Object) (values.Value, error) in argument to values.NewFunction
```

**Comment by redmark-alt** [comment]
The Contributing Guide states GO 1.12 so I'll close the issue... thanks.
