### ISSUE TITLE
Mobile display not working on devices - missing <meta> tag

### ISSUE THREAD

**Issue by corriganjohn** [influxdata/influxdb#15780]
Steps to reproduce:
Either 
-- open the Cloud app in a mobile device and navigate to any page OTHER than usage/billing
-- open in a desktop browser, using browser tools, set to mobile device display

Expected behavior:
Mobile device settings should be triggered (mobile slideout menu, responsive layout)

Actual behavior:
Mobile layout is seen in browser, when in desktop mode, and the browser width is reduced --- but NOT when viewing on a device (or simulating a device). Screen is being displayed full-screen, but scaled to fit.

Suggested Solution:
It appears that monitoring pages don't have the appropriate <meta> tags to trigger display for mobile devices
Sample:  <meta name="viewport" content="width=device-width, initial-scale=1">
These tags are being used for the ecomm/quartz pages, and when I copied over the meta tag to the browser session, it corrected the issue

**Comment by corriganjohn** [comment]
<img width="1228" alt="mobile - no meta" src="https://user-images.githubusercontent.com/48359266/68315278-2337e880-007d-11ea-8f4e-7c5b1c45b23c.png">
<img width="1153" alt="mobile display - with meta" src="https://user-images.githubusercontent.com/48359266/68315279-23d07f00-007d-11ea-994f-e6bec62009f5.png">

**Comment by drdelambre** [comment]
the mobile browsing experience isn't triggered by the meta tag, but by a breakpoint set at an 800px width.
I cleaned up the tag anyways in the name of constancy
