### ISSUE TITLE
Auto increment field/column

### ISSUE THREAD

**Issue by fbiletsiou** [influxdata/influxdb#15794]
After a short research I think the solution I am looking for it is not supported yet. 
Is there any way to add a auto-incerement column in my measurements when I insert new records?
I know that the "primary key" , which is getting the measurements indexed , is the timestamp , but I don't want my records to get overwritten if it happens to be at the same second , I want to keep both in my measurement.
This would be achived if we had a "id" column created automatically and incrementally , and used as a tag. 
Any ways that I can have the same result without an id column?

**Comment by russorat** [comment]
InfluxDB does not support auto increment columns.
