### ISSUE TITLE
Corrupt TSM files not always skipped

### ISSUE THREAD

**Issue by tmgordeeva** [influxdata/influxdb#15804]
When we initially open TSM files, if we get an error we skip the file and rename it for future reference. However, future reads don't do the same check so a corrupt block can cause errors. One place we've hit this recently is during compaction, which is convenient because we can set aside the bad file right there. I'm not clear yet if that's sufficient to solve this issue in general.

**Comment by tmgordeeva** [comment]
CC @dgnorton let me know if this roughly makes sense to you.

**Comment by dgnorton** [comment]
@tmgordeeva Makes sense. I think if compaction encounters a corrupt file, it should do the same, log it and move the file aside.

**Comment by tmgordeeva** [comment]
PR waiting for one more review at https://github.com/influxdata/influxdb/pull/15885 and backport (clean cherry-pick) at https://github.com/influxdata/influxdb/pull/16221

**Comment by Elbehery** [comment]
@dgnorton I think @tmgordeeva  should not work on this anymore, shall I take it over ?

**Comment by Elbehery** [comment]
@dgnorton I think this one is already **done**, #15885 and #16221 are `merged`, or
