### ISSUE TITLE
bad error message the comes from failed check create

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15819]
We currently return the flux error from the flux we generate.

```
{
  "code": "invalid",
  "message": "invalid options; Err: loc 24:3-24:15: expected an operator between two expressions: loc 24:3-24:15: expected an operator between two expressions"
}
```

This error is not useful to the end user.

**Comment by desa** [comment]
This should open up honeybadger issue

**Comment by ebb-tide** [comment]
- [ ] Send error message to honeybadger. 
- [ ] Improve error message from backend "could not create task from check, or could not validate flux"
- [ ] Validate that check parameters that we need for a valid check are set on check and error if not. 
- [ ] Don't allow user to save if parameters are incomplete/invalid. or if input fields are in error state.
