### ISSUE TITLE
checks don't support prometheus style metrics

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15818]
Creating a check that uses the field `0.9` fails because the flux we generate looks like

```
package main
import "influxdata/influxdb/monitor"
import "influxdata/influxdb/v1"

data = from(bucket: "apps")
    |> range(start: -15m)
    |> filter(fn: (r) =>
        (r._measurement == "task_scheduler_run_queue_delta"))
    |> filter(fn: (r) =>
        (r._field == "0.9"))
    |> filter(fn: (r) =>
        (r.env == "prod01-eu-central-1"))
    |> aggregateWindow(every: 15m, fn: median, createEmpty: false)

option task = {name: "Latency Threshold Exceeded", every: 15m, offset: 0s}

check = {
    _check_id: "",
    _check_name: "Latency Threshold Exceeded",
    _type: "threshold",
    tags: {},
}
warn = (r) =>
    (r.0.9 > 60.0)
crit = (r) =>
    (r.0.9 > 300.0)
messageFn = (r) =>
    ("Check: ${ r._check_name } is: ${r._level }")

data
    |> v1.fieldsAsCols()
    |> monitor.check(
        data: check,
        messageFn: messageFn,
        warn: warn,
        crit: crit,
    )
```

Specifically the issue is
```
warn = (r) =>
    (r.0.9 > 60.0)
crit = (r) =>
    (r.0.9 > 300.0)
```

We should switch to do lookups using `r["0.9"]` style of references

**Comment by desa** [comment]
all happens in the package `notifcation/check/...`

**Comment by nwneisen** [comment]
I've been taking a look at this and I wanted to see if what I've found sounds correct.

The threshold lookups are stored as an AST node struct, specifically the `ast.MemberExpression` type. The node structure is traversed, formatted, and output using `ast.Format()` which is part of the flux package.

So in order to change the style of references, the change will need to be made in the flux library and the version used by Influxdb will need to be updated from the current 0.55.1.

**Comment by desa** [comment]
@nwneisen I believe we can use `r["foo"]` style look ups which should be supported by flux currently. I believe it will no longer be a member expression though. We'll have to use whatever `["foo"]` is and I'm uncertain what it is off-hand.

Are you still looking into this?

**Comment by nwneisen** [comment]
@desa I would still like to take a look at this. Just trying to get familiar with the code and have a plan so I don't go too far into the wrong solution.

**Comment by desa** [comment]
@nwneisen I just realized that we have someone else looking into this issue. We have another issue that will be in the same area of the code base: https://github.com/influxdata/influxdb/issues/15308. If you're interested, I can assign the issue to you so that we don't have this kind of mix up again.

**Comment by desa** [comment]
@nwneisen We had a mixup and someone else was working on the issue. I just removed them and assigned the issue to you so that that doesn't happen again. Let me know if there's anything I can do to help.

**Comment by e-dard** [comment]
I ran into this again today. Same measurement.

**Comment by desa** [comment]
closing in favor of https://github.com/influxdata/influxdb/issues/17129
