### ISSUE TITLE
When dashboard builder config is not provided, cannot configure dashboard view

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#15812]
When creating a dashboard through the API, I can leave out the builder config fields (zero values to nil in go become null in JS) and an exception is thrown when trying to configure a dashboard view.

Exception when loading trying to access the view configuration: 
![image](https://user-images.githubusercontent.com/17263167/68497602-cae22180-0209-11ea-814a-78f2d3750979.png)

steps to reproduce:

1. create a view on a dashboard cell, that does not provide a builder config
2. navigate to ui and click the configure button  for the view you just created

Note: if this is part of the API contract, then I'm thinking this should be remedied in the dash service.

**Comment by drdelambre** [comment]
@jsteenb2 idk how to repro this, but we just refactored a bunch of code in here. could you verify it's still an issue?

**Comment by jsteenb2** [comment]
the issue seems to have been resolved in my local testing just now.

fwiw, standing up a dashboard through the api is as simple as

```sh
influx pkg -f $PWD/pkger/testdata/dashboard.yml
```
