### ISSUE TITLE
Not able to add members in influx cloud UI

### ISSUE THREAD

**Issue by marklu2018** [influxdata/influxdb#15825]
Not able to add members (invite users into this trial account)
https://us-west-2-1.aws.cloud2.influxdata.com/orgs/<org_id>/settings/members

![image](https://user-images.githubusercontent.com/43967355/68537941-513d5700-0321-11ea-8be1-42fab126201b.png)

How can I invite a new user into this trial account?

**Comment by russorat** [comment]
this is no longer relevant. we've updated the way we handle users in cloud.
