### ISSUE TITLE
influx write will mess up the input when it is sufficiently long

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#15829]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Download a slightly modified version of the NOAA data. Most likely the NOAA data used for 1.x examples works, but I wasn't sure if the escape sequence for strings was the same so it was easier to remove it. It is attached below.
2. Use `influx write` and have it read from the file using `@`.
3. The write will probably fail with very strange error messages.

__Expected behavior:__
The write should have just succeeded.

__Actual behavior:__
Strange errors and it told me that I was writing invalid line protocol that isn't present in the file.

```
2019-11-11T14:20:52.987325Z     error   Error parsing points    {"log_id": "0J2hGz90000", "handler": "write", "org": "97aa81cc0e247dc4", "b
ucket": "b76b31ef2f0341e0", "error": "unable to parse 'h2o_quality,location=coyoteh2o_quality,location=coyote_creek,randtag=2 index=32 1439
870040': duplicate tags\nunable to parse 'h2o_quality,location=coyote_creek,randtag=1 index=63 1439915760h2o_quality,location=coyote_creek,
randtag=3 index=64 1439893080': bad timestamp"}
```

__Environment info:__

* System info: `Darwin 19.0.0 x86_64`
* InfluxDB version: Revision a64b976561c798f9aeeb771c4f48fb5d3141ad5f.

[NOAA_data.txt](https://github.com/influxdata/influxdb/files/3831757/NOAA_data.txt)

**Comment by jsternberg** [comment]
I think this is just because the writer seems to use `bufio.Scanner` for scanning the input and then it sends the byte buffer to another goroutine. This doesn't seem safe. Byte buffers generally aren't valid to send across channels unless you are careful that it is not being used as a slice buffer and `bufio.Scanner` doesn't allow the buffer to be valid after the next call to `Scan()`.

**Comment by jsternberg** [comment]
As an easy hack to make this work temporarily, this works which likely confirms the comment above:

```go
jsternberg:[~/g/s/g/i/influxdb] $ (master *$=) git diff
diff --git a/write/batcher.go b/write/batcher.go
index e494742f3..cabdb0a35 100644
--- a/write/batcher.go
+++ b/write/batcher.go
@@ -68,8 +68,10 @@ func (b *Batcher) read(ctx context.Context, r io.Reader, lines chan<- []byte, er
        scanner.Split(ScanLines)
        for scanner.Scan() {
                // exit early if the context is done
+               buf := make([]byte, len(scanner.Bytes()))
+               copy(buf, scanner.Bytes())
                select {
-               case lines <- scanner.Bytes():
+               case lines <- buf:
                case <-ctx.Done():
                        errC <- ctx.Err()
                        return
```

**Comment by tmalaher** [comment]
> As an easy hack to make this work temporarily, this works which likely confirms the comment above:
> ...

This fixed it for me, once I figured out how to compile from source.

**Comment by russorat** [comment]
The acceptance criteria here is that `influx write` should be able to handle LP files > 1GB.

**Comment by kelwang** [comment]
verified fixed by https://github.com/influxdata/influxdb/pull/16891

**Comment by kelwang** [comment]
can be still reproduced by 
```
curl https://raw.githubusercontent.com/influxdata/influxdb2-sample-data/master/bird-migration-data/bird-migration.line --output ./tmp-data
influx write -b buck1 @./tmp-data
```
