### ISSUE TITLE
Custom queries for checks

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15839]
At the moment, we require users to use the check builder to create checks, but we'd like to allow users to create checks using custom queries. It is unclear how difficult this will be. It will likely require a bit of backend work.

UI should also support switching to the flux editor here
![Screenshot 2019-11-11 11 43 11](https://user-images.githubusercontent.com/1477539/68604467-87d9b580-0478-11ea-9702-fed8adc7b6f7.png)

**Comment by desa** [comment]
Result of spike should be  set of tasks for UI and API

**Comment by ebb-tide** [comment]
Closed by https://github.com/influxdata/influxdb/pull/16350
