### ISSUE TITLE
preview of data to be deleted with predicate

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15835]
Before the user confirms a delete we should display the following

* How many points they are going to delete
* Small sample of the data that will be deleted 

This will likely be done using a flux query.

**Comment by desa** [comment]
Check with storage/flux teams about the idea for implementation

**Comment by Asalem1** [comment]
@desa this has since parsed into several different tickets based on the current specs, would you be opposed to be submitting a non-breaking PR to master that we can work off to sort the following issues?

#16080 
#16081 
#16082 
#16083 
#16084 
#16085 
#16086

**Comment by desa** [comment]
@Asalem1 works for me.
