### ISSUE TITLE
Replace cloud navigation item with split Application and Account navigation

### ISSUE THREAD

**Issue by mavarius** [influxdata/influxdb#15843]
__Proposal:__
Replace cloud navigation item with split Application and Account navigation:
- Add a top-level navigation bar that houses the account navigation
- Add an ever-present Upgrade button to the top-level navigation bar
- Add a logo to the top-level navigation that acts as a home button
- Remove the logo and cloud from the application navigation bar.

![image.png](https://images.zenhubusercontent.com/5cffe8c638b9052bc7e6b150/f6694cc4-f2d3-4e5e-b1ca-e1222f25dd5b)

__Current behavior:__
Users are currently unable to find the option to upgrade to a usage-based payment plan or their account settings in the application.

__Desired behavior:__
Users are able to easily find the upgrade option. Users are easily able to find their account settings.

__Alternatives considered:__
- Adding an upgrade button below the existing navigation bar
- Adding the current subscription level next to the org name subtitle with a popover upgrade option
- Adding an ever-present upgrade button next to the org name

__Use case:__
A free teir cloud user is prompted to upgrade and is easily able to find the option.

**Comment by desa** [comment]
cc @alexpaxton  when we tried this, we got a few weird artifacts in the UI

**Comment by desa** [comment]
@drdelambre what was the issue that you ran into specifically?
