### ISSUE TITLE
Firefox: Cannot scroll to see all items in query builder

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#15852]
![in](https://user-images.githubusercontent.com/146112/68627030-92ed0f80-0491-11ea-8695-ff9336e0e85f.gif)

__Steps to reproduce:__

1. Go to Data Explorer
1. Select your telegraf local bucket
1. Select `cpu`
1. Try to scroll to all the fields in the `Filter` panel

__Expected behavior:__
All the fields are selectable

__Actual behavior:__
There is a problem with the scrolling where I can't see the bottom of the list

__Environment info:__
Latest master

**Comment by zoesteinkamp** [comment]
I worked on something similar, im going to take a look at it

**Comment by zoesteinkamp** [comment]
<img width="736" alt="Screen Shot 2019-11-14 at 3 00 06 PM" src="https://user-images.githubusercontent.com/6667389/68899741-8b2aa680-06ef-11ea-99ba-07c3fdf0e90b.png">


Can not seem to recreate, browser possibly? Im on chrome for this

**Comment by zoesteinkamp** [comment]
@hoorayimhelping  Can you confirm this is still an issue?

**Comment by hoorayimhelping** [comment]
@zoesteinkamp thanks for looking into this. Confirmed it's a Firefox issue.

**Comment by zoesteinkamp** [comment]
This issue is closed with this branch in the react scrollbars library, 
https://github.com/malte-wessel/react-custom-scrollbars/pull/335

Im working on getting it deployed now
