### ISSUE TITLE
Data image fails to start with existing influxdb.conf

### ISSUE THREAD

**Issue by wgj** [influxdata/influxdb#15867]
Hello, I'm attempting to patch the Helm chart [`stable/influx`](https://github.com/helm/charts/tree/master/stable/influxdb) to use Enterprise. When deploying the chart with the `influxdb:data` image, it fails to start up, with Hinted Handoff attempting to use empty string as its path. Expected behavior is using a default of `/var/lib/influxdb/hh`, or complaining that `hinted-handoff.dir` doesn't exist in `influxdb.conf`, instead of attempting to start Hinted Handoff with an empty string path. [Documentation](https://docs.influxdata.com/enterprise_influxdb/v1.7/install-and-deploy/production_installation/data_node_installation/) doesn't mention or imply the need for the `Hinted-handoff` section.

I recognize there are a few projects being touched here (`helm/charts`, `influxdata/influxdata-docker`, `influxdata/influxdb`). I'm taking it upon myself to "fix" the Helm chart `stable/influxdb`, but I would expect this to be resolved within InfluxDB too.

__Steps to reproduce:__
1. Run container image `influxdb:data`
2. Deploy with a `influxdb.conf` that previously worked with InfluxDB OSS.
3. Observe that Hinted Handoff attempts to start with empty path
```shell script
ts=2019-11-12T16:58:07.977696Z lvl=info msg="Using data dir" log_id=0J48epWW000 service=handoff path=
```

__Environment info:__
Using Docker hub image`influxdb:data`.

__Config:__
Command used to deploy container image:
```shell script
$ helm install -f influxdb.yaml ~/repos/wgj/charts/stable/influxdb --namespace influxdb -n influxdb

$ cat influxdb.yaml
image:
  tag: data
env:
  - name: INFLUXDB_ENTERPRISE_LICENSE_KEY
    value: beef-babe
```
If you're not familiar with Helm and Kubernetes, the above is boilerplate to deploy the `influxdb:data` to a Kubernetes cluster. If you were to change the image tag from `data` to `latest` and make no other changes, the container will deploy successfully.

`~/repos/wgj/charts/stable/influxdb` is a fork of [helm/charts](https://github.com/helm/charts). The only edit, shown below, is adding the `[hinted-handoff]` section. 
```shell script
$ git diff ~/repos/wgj/charts/stable/influxdb
diff --git a/stable/influxdb/templates/config.yaml b/stable/influxdb/templates/config.yaml
index 2cc83da80..14a39a3d9 100644
--- a/stable/influxdb/templates/config.yaml
+++ b/stable/influxdb/templates/config.yaml
@@ -13,6 +13,10 @@ data:
     reporting-disabled = {{ .Values.config.reporting_disabled | default false }}
     bind-address = ":{{ .Values.config.rpc.bind_address }}"

+    [hinted-handoff] # TODO wgj File bug, as HH will intuit null directory if not specified.
+      enabled = true
+      dir = "/var/lib/influxdb/hh"
+
     [meta]
       dir = "{{ .Values.config.storage_directory }}/meta"
       retention-autocreate = {{ .Values.config.meta.retention_autocreate }}
```

__Logs:__
This is the log output when `[hinted-handoff]` is _not_ added explictly.
```shell script
$ kubectl logs -n influxdb influxdb-0
ts=2019-11-12T16:58:07.873969Z lvl=info msg="InfluxDB starting" log_id=0J48epWG000 version=1.7.8-c1.7.8 branch=1.7 commit=ab724c8917878a758f1a6d753cb25abb41485c17
ts=2019-11-12T16:58:07.873992Z lvl=info msg="Go runtime" log_id=0J48epWG000 version=go1.10.3 maxprocs=6
ts=2019-11-12T16:58:07.874022Z lvl=info msg="Loading configuration file" log_id=0J48epWG000 path=/etc/influxdb/influxdb.conf

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

ts=2019-11-12T16:58:07.977413Z lvl=info msg="Connecting to meta service" log_id=0J48epWW000
ts=2019-11-12T16:58:07.977616Z lvl=info msg="Starting hinted handoff service" log_id=0J48epWW000 service=handoff
ts=2019-11-12T16:58:07.977672Z lvl=info msg="Registered diagnostics client" log_id=0J48epWW000 service=monitor name=hh
ts=2019-11-12T16:58:07.977696Z lvl=info msg="Using data dir" log_id=0J48epWW000 service=handoff path=
run: open server: open hinted handoff: mkdir all: mkdir : no such file or directory
```

**Comment by russorat** [comment]
@wgj thanks for opening this. I've reached out to the person who has been working on our helm charts to see what his thoughts are. 

I've also reached out to the docs team to check on the hinted handoff directory question.

**Comment by gunnaraasen** [comment]
If a required directory is not specified in the config then InfluxDB will default to a path in the user's `$HOME` directory ([equivalent code for OSS InfluxDB](https://github.com/influxdata/influxdb/blob/1.7/cmd/influxd/run/config.go#L109-L111)).

I suspect the `hh` directory is a blank in this case due to the Alpine-based Docker image, which has no user and no `$HOME` directory. Though it's better to explicitly set all directory paths (`data`, `wal`, `meta`, `hh`).

> Deploy with a influxdb.conf that previously worked with InfluxDB OSS.

An OSS config is not equivalent to an Enterprise config. A better option would be to generate a new config file for Enterprise using the values in the OSS config as a base with `influxd config -config oss-influxdb.conf`.

**Comment by rawkode** [comment]
@wgj We've recently migrated the InfluxData product charts out of `helm/charts` (which is being deprecated) into `influxdata/helm-charts`. I dropped you an email regarding this due to your contribution to the repository. Please let me know if you did not receive it.

Hopefully @gunnaraasen's answer helps you with your issue

**Comment by wgj** [comment]
@rawkode & @gunnaraasen Sounds good. 

We're no longer exploring InfluxDB at this time, so I'm not in a position to try out @gunnaraasen's suggestions, but they seem reasonable enough to be shared in a more conspicuous place for anyone else using these images for Enterprise (presuming that's a supported use case).
