### ISSUE TITLE
Column order resets when editing a table

### ISSUE THREAD

**Issue by sjwang90** [influxdata/influxdb#15891]
1. Used Column Settings to rearrange column order
2. In Dashboard View, columns successfully reorder
3. When go back to edit the Table, columns reset 

Browser: Chrome

![column_order_resets](https://user-images.githubusercontent.com/32681364/68800518-20a23980-060f-11ea-88c0-103d3a17ad76.gif)

**Comment by desa** [comment]
@zoesteinkamp might be good to keep in mind the changes coming with https://github.com/influxdata/influxdb/pull/15944

**Comment by zoesteinkamp** [comment]
@desa  im going to watch this issue go out and check to see if it fixes this problem

**Comment by drdelambre** [comment]
just tried it. fixed by #15944
