### ISSUE TITLE
Make the dashboard endpoints document based

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#15898]
Pain point: when reading/updating dashboards, its very chatty. When exporting a local dev environments it is very chatty. Each view/cell combo requires a call to read and another to udpate. In testing there was over 240 calls just to add/update 10 dashboards. Would be ideal to extend the current dashboard update to allow for the entire document to be updated at once. In that same light, it would be nice to read the entire dashboard in one call as well.  

I'd recommend starting with the read on dashboards to include the nested views for the cell. Then extending the dashboard update to take the entire list of views (not individual), and upsert them over the existing ones. If a `nil` is provided for charts to the update, then its does nothing, if it is set to a non nil val, it will update, including a non nil empty slice.

this pain became noticeable during work for pkger. feels like a good tech debt candidate.

**Comment by dearyhud** [comment]
pairing with deniz on the swagger part of this later today, should have this reviewed and merged by EOD

**Comment by jademcgough** [comment]
this is donezo
