### ISSUE TITLE
Graph time range should be based on query time range not returned data

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15908]
![Screenshot 2019-11-14 09 44 59](https://user-images.githubusercontent.com/1477539/68867233-7cc69580-06c3-11ea-9236-c08b7532a440.png)

Note how I've queries for the last 5m, but the domain of the x axis only spans the last 2m. This is because I did not have any data for 3 of the last 5 minutes. This can be confusing when you have graphs where you expect the domains to be similar.

Ideally I could specify whether I'd like the domain to span the entire range queried or the range or the data returned.

**Comment by Asalem1** [comment]
EDIT: This is incomplete as the `now()` selections don't return the correct data
