### ISSUE TITLE
Table thresholds are not functional

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15904]
1. Threshold colors are not applied to table

![no-threshold-coloring](https://user-images.githubusercontent.com/1477539/68864885-d75df280-06bf-11ea-82ba-ace2f18a246d.gif)

2. Threshold settings do not persist

![threshold-settings-dont-persist](https://user-images.githubusercontent.com/1477539/68865055-260b8c80-06c0-11ea-8912-038596369a73.gif)

**Comment by desa** [comment]
cc @r1ckbrown

**Comment by desa** [comment]
Link https://github.com/influxdata/influxdb/issues/15803

**Comment by Asalem1** [comment]
@desa should the threshold colors be set on the `_value` column text? Background? The entire row?

**Comment by sjwang90** [comment]
My suggestion would be the threshold colors on the entire row.  If something is critical, I would want to follow the entire row to see what time/field info that critical point occurred.  The user could toggle if they wanted the color on the background or text similar to the single stat.

**Comment by r1ckbrown** [comment]
This is how it's working in v1
<img width="426" alt="image" src="https://user-images.githubusercontent.com/27981402/70364465-a919a000-1884-11ea-820e-dc5d12f09113.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/27981402/70364512-c2bae780-1884-11ea-8cff-b16d5883dca5.png">

**Comment by Asalem1** [comment]
<img width="1394" alt="Screen Shot 2019-12-09 at 10 47 48" src="https://user-images.githubusercontent.com/19984220/70463231-5e10b000-1a71-11ea-8f63-e036c2715fae.png">

@r1ckbrown & @sjwang90 here's what I've got for it so far, should we go ahead and commit to this UI or refactor it so that the entire row is the same color?
