### ISSUE TITLE
No horizontal scroll on Data Explorer Filter

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#15902]
![Screenshot 2019-11-14 11 38 10](https://user-images.githubusercontent.com/501993/68854164-69232b00-06d3-11ea-8992-0844113647fe.png)

It is not possible in my browser (**Firefox, macOS**) to scroll the filter selection window horizontally. This means I can't read the tag values properly.

**Comment by e-dard** [comment]
It looks like this is a bug. When I use Chrome I can see the scroll bar. Further, in Firefox I can scroll using the horizontal scroll wheel on my mouse, so it's just the UI component that's missing.

**Comment by e-dard** [comment]
Yeah I would expect the width of the list would be adjusted according to the widest element in the list.

**Comment by desa** [comment]
looks like this has been fix by adding a horizontal scroll
