### ISSUE TITLE
Cannot specify time format in graphs

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15906]
![Screenshot 2019-11-14 09 32 29](https://user-images.githubusercontent.com/1477539/68865979-b1395200-06c1-11ea-9f05-44b2dd3a54d0.png)

There isn't an option to specify the format of the time in the x-axis

**Comment by desa** [comment]
cc @r1ckbrown

**Comment by desa** [comment]
Selecting time format should use same component as https://github.com/influxdata/influxdb/issues/15905

**Comment by r1ckbrown** [comment]
I want to use h:mma for that cell (eg: 3:21pm), but whatever other time format is relevant for the visualization would be most useful, so it’s really the ability to have custom date/time formats rather than just adding support for HH:mm

**Comment by r1ckbrown** [comment]
I was showing visualisations to a colleague today, and we noticed that "h:mm a" isn't working.
<img width="397" alt="image" src="https://user-images.githubusercontent.com/27981402/84405135-aa46d380-abff-11ea-951d-1e5919c1ea78.png">

**Comment by desa** [comment]
@r1ckbrown I think that might be a distinct issue from this one.
