### ISSUE TITLE
Delete With Predicate Panics

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#15916]
Steps to reproduce:

1. Set the featureFlag for deleteWithPredicate to true:
2. Navigate to the dashboard
3. `delete data` button in the header options
4. Select a bucket that has the tag key `cpu`
4. Set filter to `cpu = cpu1 AND cpu != cpu2`
5. Submit delete request

```
panic: runtime error: index out of range [1] with length 1

goroutine 4525 [running]:
github.com/influxdata/influxdb/tsdb/tsm1.(*predicateState).Set(...)
	/Users/asalem/go/src/github.com/influxdb/tsdb/tsm1/predicate.go:325
github.com/influxdata/influxdb/tsdb/tsm1.(*predicateMatcher).Matches(0xc001bca260, 0x16104ce5, 0x1e, 0x1eb8df, 0x3500b00)
	/Users/asalem/go/src/github.com/influxdb/tsdb/tsm1/predicate.go:123 +0x2ca
github.com/influxdata/influxdb/tsdb/tsm1.(*Engine).DeletePrefixRange.func3(0x352bc80, 0xc0005ea800, 0x0, 0x0)
	/Users/asalem/go/src/github.com/influxdb/tsdb/tsm1/engine_delete_prefix.go:145 +0x546
github.com/influxdata/influxdb/tsdb/tsm1.(*FileStore).Apply.func1(0xc001a71680, 0xc0009f3aa0, 0xc0006da100, 0x352bc80, 0xc0005ea800)
	/Users/asalem/go/src/github.com/influxdb/tsdb/tsm1/file_store.go:535 +0x102
created by github.com/influxdata/influxdb/tsdb/tsm1.(*FileStore).Apply
	/Users/asalem/go/src/github.com/influxdb/tsdb/tsm1/file_store.go:529 +0x114
exit status 2```

__Expected behavior:__
Delete data with predicate

__Actual behavior:__
Panic

**Comment by e-dard** [comment]
Thanks @Asalem1. I’ll take a look tomorrow, but couldn’t the cause of this panic be that we haven’t integrated != into the API yet? Maybe @kelwang has some thoughts too?

**Comment by e-dard** [comment]
Reproduced on master. @kelwang `!=` isn't currently supported yet is it. How did this get past the parser?

**Comment by e-dard** [comment]
It looks like the `cpu != cpu2` predicate is being removed, but some indexes are not being updated for the valid predicate (in this case `cpu = cpu1`). Then, when this predicate code is hit:

https://github.com/influxdata/influxdb/blob/93c9189a49920050a4d70d06d7597e85c3330963/tsdb/tsm1/predicate.go#L320-L328

`p.locs` hold an index that's out of bounds of the slice. The index should have been adjusted when items were removed from the valid predicates.

**Comment by e-dard** [comment]
OK, I drank enough coffee to realise that this filter is logically invalid 😆. @Asalem1 there is a bug in the predicate matcher.

My earlier comment was slightly incorrect. The `predicateState` will simplify the expression down to `cpu = cpu1`, but it's forgetting to adjust the indexes as I said. I'll see if I can fix it.
