### ISSUE TITLE
Duplicate variables being created

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15914]
to repro, delete your existing `bucket` variable, then create a new telegraf configuration containing both system and docker, configure docker (doesn't matter what you put in as long as it's something), then click create + verify. Close the verify modal and check the variables page, and you will see two `bucket` variables.

![image](https://user-images.githubusercontent.com/4805997/68879393-2f93f500-06be-11ea-95d9-9b631424ad3a.png)

![image](https://user-images.githubusercontent.com/4805997/68879452-476b7900-06be-11ea-950e-0ea9ec47885a.png)

**Comment by desa** [comment]
@russorat which environment are you seeing this in?

**Comment by Asalem1** [comment]
@russorat I'm not able to reproduce this

**Comment by desa** [comment]
@russorat I've tried to reproduce this as well and have been unable to. Can you confirm that this is still an issue?

**Comment by drdelambre** [comment]
i think we confirmed that it was still happening as of ~ 6 days ago, but that a fix to the api has been deployed that is enforcing uniqueness (rca/2020-01-22-invalid-variable-indices.md)
