### ISSUE TITLE
Clicking on column in table settings scrolls to top

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15910]
![clicking-on-column-scrolls](https://user-images.githubusercontent.com/1477539/68867867-856b9b80-06c4-11ea-8ed3-f86158adb4dd.gif)

**Comment by desa** [comment]
cc @r1ckbrown

**Comment by russorat** [comment]
probably a dupe of https://github.com/influxdata/influxdb/issues/15633

**Comment by desa** [comment]
Closing in favor of https://github.com/influxdata/influxdb/issues/15633
