### ISSUE TITLE
Does InfluxDB have auto increment field?

### ISSUE THREAD

**Issue by ZhouZhaoJi** [influxdata/influxdb#15927]
Hello! 

There are two programs.

The first program inserts some points to the database every time and every point uses the timestamp that I input not the mechine generates automatically. 

The second program will read these points in the insert order of the first program to do somethings.

But because the timestamp in every point is that I input and the timestamps in these points not be equal to the insert order, I can't use the timestamps to sure the next point that the second program handles.

I wanted use auto increment field like sql to sure the next point that the second program handles, but there are not auto increment fields in InfluxDB.

 I don't know how to do this. Could you help me?

**Comment by russorat** [comment]
InfluxDB does not support auto increment fields. For help with custom applications, please check out our community Slack https://influxdata.com/slack .
