### ISSUE TITLE
2.0 alpha version can not explore data 

### ISSUE THREAD

**Issue by prafliewen** [influxdata/influxdb#15929]
I can't look at the buckets data in DataExplore when i install influx2.0 version.
the api uri is /api/v2/query?orgID=5bf6631850049b4c,
response :  {code: "unauthorized", message: "unauthorized access"}
what can i do  ?

**Comment by prafliewen** [comment]
install question

**Comment by russorat** [comment]
@prafliewen sorry for not responding sooner. I recommend you upgrade to the latest beta-14 release and trying again. Make sure you are passing the `Authorization: Token <token>` header as described here: https://v2.docs.influxdata.com/v2.0/query-data/execute-queries/#influxdb-api
