### ISSUE TITLE
write RFC proposal for changing dashboards to document-based storage

### ISSUE THREAD

**Issue by jademcgough** [influxdata/influxdb#15922]
Deniz has written a proposal on this, worth taking a look at that first.

**Comment by dearyhud** [comment]
chatted with deniz earlier last week, and decided to move forward with this spec https://docs.google.com/document/d/1N_NkwPXv5nyi_z8xmPmcCiKFkW-pzVGnWiI8dg12hII/edit

ideally, none of these additions to the existing endpoints should be breaking changes.
