### ISSUE TITLE
Cached Single Stat When Cloning Cell

### ISSUE THREAD

**Issue by rawkode** [influxdata/influxdb#15931]
__Steps to reproduce:__
When you clone a cell and edit the Flux query, the single stat on the dashboard view is cached as the previous query

1. Clone Cell
2. Edit Query
3. View Dashboard

__Expected behavior:__
Updated single stat

__Actual behavior:__
Cached single stat

**Comment by blegesse-git** [comment]
No longer a bug. Couldn't reproduce
