### ISSUE TITLE
Cloning a cell on a dashboard doesn't clone size

### ISSUE THREAD

**Issue by rawkode** [influxdata/influxdb#15930]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a cell
2. Resize cell
3. Clone cell

__Expected behavior:__
Cloned cell should be same size as original

__Actual behavior:__
Cloned cell is the default cell size

**Comment by rawkode** [comment]
When I reloaded the page, cloning worked as expected. So perhaps this is only an issue if you don't refresh the page.

**Comment by rawkode** [comment]
@russorat So the size is fixed - but cloning a cell puts the new cell in the dashboard at a random location ...

https://imgur.com/a/PDN1vod

**Comment by russorat** [comment]
thanks! tracked in https://github.com/influxdata/influxdb/issues/17630
