### ISSUE TITLE
[2.0 alpha-19] Data Explorer Filters - Telegraf Inputs

### ISSUE THREAD

**Issue by MartynKeigher** [influxdata/influxdb#15953]
__Proposal:__

Remove (or separate) OOTB filters from those that are specified in Telegraf (input) configs.

__Current behavior:__

OOTB filtering options are shown in addition to those specified in Telegraf configs.

__Desired behavior:__

The ability to separate those would be a huge help and make it easier\quicker for me to create the 'pods' on the dashboard.

__Alternatives considered:__

Add an additional dropdown to the FILTER pane named 'Telegraf Inputs'. The results being the _measurements that are in the database that are provided via Telegraf agents.

__Use case:__

Currently I have just one Telegraf agent setup and sending data. The 'inputs' I have coming in from this agent are '**diskio mem net processes swap system cpu disk**'. Not very many, just the defaults, but when it comes to visualizing those metrics on a board, they get lost in the list of '_measurements' available in the filterers. While they are easy to find, and navigate.. it would just be cleaner if the OOTB filters, such as '**go_metrics_<something>, http_,##, influxdb_, & query_control, etc..**, were able to be separated.

**Comment by russorat** [comment]
@MartynKeigher this would be cool. It might be tricky since technically Telegraf users can overwrite measurement names if they like. Would a workaround be to have a different bucket for each telegraf config?
