### ISSUE TITLE
Error when creating InfluxDB Output Plugin without Bucket

### ISSUE THREAD

**Issue by nwneisen** [influxdata/influxdb#15962]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Delete all buckets
2. Select the purple "InfluxDB Output Plugin" button on the Telegraf page
3. Error

__Expected behavior:__
A warning notifying the user that a bucket is needed to generate a configuration

__Actual behavior:__
An error asking to report the issue

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 4.15.0-64-generic x86_64
* InfluxDB version: Run `influxd version` and copy the output here
Master branch
InfluxDB cloud

**Comment by russorat** [comment]
@nwneisen thanks for reporting!
