### ISSUE TITLE
Add explicit auth for allowing backup

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15961]
we need to add an additional authorization that can be added to a token that allows the user to run a backup.

We will also need to migrate all master tokens to have this authorization.

**Comment by kelwang** [comment]
related to https://github.com/influxdata/influxdb/issues/16120

**Comment by lesam** [comment]
2.0 backups currently require the root token, per the docs: https://docs.influxdata.com/influxdb/v2.0/backup-restore/backup/

Is the intention still to have this requirement?

**Comment by lesam** [comment]
i.e. the point of this issue is that instead of the root token, we should also allow a token with a new 'backup' permission to perform backup and/or restore?

**Comment by lesam** [comment]
I believe this is a dup of https://github.com/influxdata/influxdb/issues/21092 - @russorat can we close this one?
