### ISSUE TITLE
Automate changelogs

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#15999]
Automate changelog generation.

### Considerations:

Automate per commit? Or per tag/release?

>One of the alchemy dreams was to automatically update the change log as part of please merge.
[-mark](https://influxdata.slack.com/archives/CLHATC50E/p1574295449246500)

**Comment by codyshepherd** [comment]
Closing in favor of #19645. @hoorayimhelping please re-open if I'm missing something and have judged these issues duplicates in error
