### ISSUE TITLE
Highlight "What is Telegraf" Box & information

### ISSUE THREAD

**Issue by sjwang90** [influxdata/influxdb#15990]
Objective: Make "What is Telegraf?" information more noticeable for new users
Reason: Many new users of Cloud 2 aren't aware of what Telegraf is

Changes: 
Text box a different color & bigger
Larger Text

![image](https://user-images.githubusercontent.com/32681364/69270943-d67a0480-0b88-11ea-9f11-f06a9e19c348.png)

**Comment by desa** [comment]
Center beneath `Create Config` button.

**Comment by desa** [comment]
cc @alexpaxton
