### ISSUE TITLE
Add links to Telegraf Docs in "Create a Telegraf Config" 

### ISSUE THREAD

**Issue by sjwang90** [influxdata/influxdb#15992]
Summary: Under list of automatic Telegraf configuration, link to Docs for 1) Telegraf Plugins 2) Manually Getting Started

"Looking for other things to monitor? Check out our 200+ other [Telegraf Plugins](https://v2.docs.influxdata.com/v2.0/reference/telegraf-plugins/#input-plugins) and how to [Configure these Plugins](https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/manual-config/)"

![Screen Shot 2019-11-19 at 3 45 37 PM](https://user-images.githubusercontent.com/32681364/69275472-49877900-0b91-11ea-95d1-ede1e737388b.png)

**Comment by desa** [comment]
cc @alexpaxton

**Comment by drdelambre** [comment]
<img width="1185" alt="Screen Shot 2019-11-26 at 9 48 06 AM" src="https://user-images.githubusercontent.com/1434802/69658871-e9ca1b80-1031-11ea-92d0-8ef8a1761e0c.png">
is this prominent enough @sjwang90 ?
