### ISSUE TITLE
how to parse from lnfluxdb line proctol  to structure data?

### ISSUE THREAD

**Issue by wuguanyu** [influxdata/influxdb#16036]
__Proposal:__
Short summary of the feature.

__Current behavior:__
Describe what currently happens.

__Desired behavior:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Why is this important (helps with prioritizing requests)?

**Comment by russorat** [comment]
@wuguanyu thank you for the issue. This conversation would be better for our community slack. https://influxdata.com/slack
