### ISSUE TITLE
Spike: Add dry run to monitor.check

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#16037]
As we go to implement [custom queries in checks](https://github.com/influxdata/influxdb/issues/15839) we will want the ability to see what data would have been written to the monitoring bucket, without actually writing that data to the monitoring bucket. We should extend flux to allow for this.

**Comment by desa** [comment]
cc @goller @stuartcarnie

**Comment by desa** [comment]
Maybe would it be good to solve this at the `queryd` level and support a dry run flag that can be passed that will prevent the execution of any `to` functions`.

**Comment by goller** [comment]
In digging into the code, if we are able to identify functions with the `HasSideEffects` boolean we may be able to remove them to produce functions that only yield.

**Comment by goller** [comment]
Ok, my suggestion is to use

```javascript
option monitor.write = yield
```

This would override this line:

https://github.com/influxdata/flux/blob/f69125f7a8c7fbefa240ef27742409b1e46b687f/stdlib/influxdata/influxdb/monitor/monitor.flux#L10

(here is an example of overriding the monitor.write in a flux test: https://github.com/influxdata/flux/blob/master/stdlib/influxdata/influxdb/monitor/check_test.flux#L9)
