### ISSUE TITLE
Telegraf token label failing to be created

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16059]
To repro, try creating a new bucket, then selecting load data, configure telegraf, select system, click through to the verify step.

![image](https://user-images.githubusercontent.com/4805997/69750712-4563da00-1102-11ea-9e3c-4726e16e2979.png)

**Comment by russorat** [comment]
To fix this, we need to remove the automatic token creation for telegraf configs in the ui, and add the ability for the user to select a token to use. We should show the list of tokens that have the right permissions. If no token exists, we should allow the user to create a new one (one click).

**Comment by Asalem1** [comment]
This seems like a dup of #15730

**Comment by russorat** [comment]
yes it is
