### ISSUE TITLE
Creating a Telegraf Config and refreshing the page / navigating directly to the url doesn't display the system settings

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#16060]
### How to Reproduce

1. Navigate directly to:

`/orgs/{orgID}/load-data/telegrafs/new`

*OR*

1. Select `Create Configuration` on the telegrafs tab
2. Refresh the page

### Problem

This bug fails to load the presets for creating a Telegraf Configuration, potentially leaving users in a bad place if they try to access the configuration directly via an external url. 

![create-telegraf](https://user-images.githubusercontent.com/19984220/69762126-2d9a4f00-111e-11ea-8509-2ebe40476376.gif)

**Comment by drdelambre** [comment]
i'm closing this in favor of waiting for the new telegraf editor being released
