### ISSUE TITLE
unexpected fault address 0x7f94fe51b33c

### ISSUE THREAD

**Issue by threesquared** [influxdata/influxdb#16064]
I am running infludb from the `latest` docker container which reports version `1.7.9`. It used to run fine but now every so often when I visit grafana and it runs some queries it crashes out with the following:

```
unexpected fault address 0x7f94fe51b33c
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f94fe51b33c pc=0x114636b]
goroutine 246855 [running]:
runtime.throw(0x151e28d, 0x5)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00064a760 sp=0xc00064a730 pc=0x42f482
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:387 +0x47e fp=0xc00064a790 sp=0xc00064a760 pc=0x4447ae
github.com/influxdata/influxdb/tsdb/engine/tsm1.DecodeFloatBlock(0x7f94fe51b33c, 0xa3, 0xbb6b65, 0xc006578890, 0x40, 0x40, 0x142a3c0, 0x59, 0x7f950244d45a)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:401 +0x4b fp=0xc00064a8a8 sp=0xc00064a790 pc=0x114636b
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*mmapAccessor).readFloatBlock(0xc005a14060, 0xc00007e350, 0xc006578890, 0x8, 0xc00064a980, 0xc00015ce00, 0x7f95208f86d0, 0x0)
...
```
[crash.txt](https://github.com/influxdata/influxdb/files/3902794/crash.txt)

**Comment by nkondratyk** [comment]
I have the same issue. Mostly every night at 12:00 UTC Influx crashes with the similar stack trace.
Log has been attached.

Do you have some workaround for it?

[influx_crash.txt](https://github.com/influxdata/influxdb/files/4009352/influx_crash.txt)

**Comment by threesquared** [comment]
I have a feeling this was happening as I was mounting a nfs share as the data volume in my influxdb docker container. I switched to using a normal host volume mount pointed to a 9p volume mounted on the host and this seems to have been much more stable.

**Comment by nkondratyk** [comment]
I am not using NFS share. So, in my case it`s not the reason

**Comment by benbjohnson** [comment]
@threesquared Sorry for the long delay. NFS is likely the issue. We've had issues with it in the past (https://github.com/influxdata/influxdb/issues/9047) and it's not a supported configuration for us.

@nkondratyk It looks like your issue is a `SIGSEGV` (instead of a `SIGBUS`) and is likely the same issue as https://github.com/influxdata/influxdb/issues/14455.
