### ISSUE TITLE
DWP: Prepopulate predicates based on data explorer selections

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#16085]
DWP: When deleting data in the data explorer, the selected tag-key value pairs automatically prepopulate the predicates.

*NOTE* If the user selects multiple values for the given key, the user should be prompted a warning that their selections aren't supported by DWP (since we don't support OR queries). 

*NOTE* This should only happen when the user is in the `query builder` and not in the `script editor`

**Comment by russorat** [comment]
For the warning, basically, i want to make sure that if a user opens the modal, and the filters in the modal do not match the filters they have already selected (for any reason), we should display a message letting them know. This should happen most often when the user selects multiple values in the DE but may also happen if the user selects delete after writing a custom query. 

When the user is in the visual builder, and they select an aggregate, this warning should probably also display. For example, if the user selects "last" as an agg function, they should know that the delete will run against all of their data, not just the "last point in the window".

Does this make sense?

**Comment by Asalem1** [comment]
@russorat we aren't going to support custom query conversion will we?

**Comment by russorat** [comment]
no, you don't have to do custom query support. and after thinking about it, if they have a custom query, click delete, it should be pretty obvious that nothing is configured for them, so we probably don't need a warning there.

**Comment by Asalem1** [comment]
Closing this since there doesn't seem to be any progress on this feature
