### ISSUE TITLE
DWP: Tag Keys should be limited based on previous selections

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#16081]
Delete With Predicate: Tag-Key value pairs should behave like in the query builder, where selecting previous keys should limit the next filterable keys.

Currently, the keys are available based on the bucket name that is selected. We should revise our key availability based on the results of the previous key selected

**Comment by ebb-tide** [comment]
my PRhttps://github.com/influxdata/influxdb/pull/16130 breaks tag key and value setting, I did not fix it because it will be refactored here.

**Comment by hoorayimhelping** [comment]
When implementing this, if it's feasible to create a utility or engine function that the UI can use to remain consistent, I think that would be much preferable to similar / copy pasta logic in multiple places

**Comment by Asalem1** [comment]
Closing this since there doesn't seem to be any progress on this feature
