### ISSUE TITLE
DWP: Preview Data should be in Raw Data format

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#16086]
DWP: The preview data should return the raw data form of the incoming data that is trimmed.

Users should have the ability to preview all the raw data

**Comment by desa** [comment]
> Users should have the ability to preview all the raw data

this isn't going to be possible for very large data sets

**Comment by russorat** [comment]
@desa we should be able to build a flux query that returns no more than a fixed number of results. If we cannot, we should look to add that capability into flux. Please work with the flux team to determine the correct query to run.

**Comment by desa** [comment]
we can show a subset of the data, but not all of the data

**Comment by russorat** [comment]
yes a subset is ok.

**Comment by Asalem1** [comment]
Closing this since there doesn't seem to be any progress on this feature
