### ISSUE TITLE
DWP: disable bucketname dropdown

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#16082]
Delete With Predicate: Bucketnames should not be selectable in the dropdown

**Comment by russorat** [comment]
I would like the bucket drop down to be disabled when the user opens this modal from the bucket list page. I think it still makes sense to have a selectable bucket when the modal is opened in the data explorer.

**Comment by Asalem1** [comment]
Closing this since there doesn't seem to be any progress on this feature
