### ISSUE TITLE
DWP: Add an `all time` delete for the delete with predicate dropdown

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#16080]
Delete with Predicate Timerange:

Currently, delete with predicate allows for users to select dates to delete based on a timerange datetimepicker. We should also allow users to permanently delete all data.

**Comment by Asalem1** [comment]
@russorat anything to add?

**Comment by russorat** [comment]
@Asalem1 this looks good.

**Comment by Asalem1** [comment]
Closing this since there doesn't seem to be any progress on this feature
