### ISSUE TITLE
DWP: remove system buckets from the bucketname list

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#16083]
DWP: remove system buckets from the delete with predicate bucket list until the API allow for deletion of the system bucket data

Currently, the delete with predicate dropdown allows for users to delete data from default system buckets. Even though this should be available to users, the API is not currently setup to deal with this

**Comment by desa** [comment]
For this issue I'd prefer to see the API for this fixed. System buckets should be treated just like any other bucket.

**Comment by russorat** [comment]
@jademcgough is there an issue for adding support for DWP to system buckets?

**Comment by russorat** [comment]
this issue is stale and we will need to rethink DWP.
