### ISSUE TITLE
Retain user input when JSON parsing fails

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#16099]
The fix for [the app crashing when parsing invalid JSON](https://github.com/influxdata/honeybadger-errors/issues/3) revealed an issue whereby the JSON that was just parsed is removed from the form, but the form remains and empty.

![template](https://user-images.githubusercontent.com/146112/70089801-c6711480-15cd-11ea-9a40-7b62f52e5a44.gif)

Rather than clearing the form, we want to retain user input when JSON parsing fails.

**Comment by TCL735** [comment]
Additional side effects that should be added:

- the text area should give an indication that the input is wrong. we can achieve this with ComponentStatus
- when the user attempts to correct the invalid input, the text area should no longer indicate that the input is wrong, and the notification should be dismissed

**Comment by TCL735** [comment]
Dismissing the notification automatically when the user changes invalid input might not be necessary or desirable. The notification has details which might be useful for the user to reference while editing. An accidental edit would dismiss this potentially useful information.

As is, the notification will expire in 10 seconds. So, we'll go with that. The user can also manually dismiss the notification.
