### ISSUE TITLE
Expired certificate for https://influxdata.com

### ISSUE THREAD

**Issue by groenlid** [influxdata/influxdb#16108]
The certificate to https://influxdata.com expired 25 November 2019.

![Screenshot 2019-12-04 at 10 23 18](https://user-images.githubusercontent.com/639035/70130049-258f6180-1680-11ea-897a-b104fcafa7b8.png)

There is a couple of links to this page from this repository:

![Screenshot 2019-12-04 at 10 24 27](https://user-images.githubusercontent.com/639035/70130254-7f902700-1680-11ea-878a-5547f4fc9ce5.png)

Just wanted to let you guys know about it :)

**Comment by russorat** [comment]
@groenlid thanks for reporting.  @tkyocum is working on it.

**Comment by tkyocum** [comment]
This has been fixed. Thanks for reporting it.
