### ISSUE TITLE
Selecting UTC vs Local time in DE messes up the x axis

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16122]
To repro, try a query with a fixed time range, and change the time to UTC and then back to Local.

```
package main
from(bucket: "telegraf")
	|> range(start: 2019-12-04T18:45:32.467804001Z, stop: 2019-12-04T19:45:32.467803999Z)
	|> filter(fn: (r) =>
		(r._measurement == "cpu" and r._field == "usage_user"))
	|> filter(fn: (r) =>
		(r["cpu"] == "cpu-total"))
  |> aggregateWindow(every: 1m, fn: mean)
```

![Kapture 2019-12-04 at 12 24 49](https://user-images.githubusercontent.com/4805997/70178534-54fa9a00-1691-11ea-943e-52c25e4cde2d.gif)

**Comment by TCL735** [comment]
This a giraffe issue. giraffe will calculate the number of points ("ticks") of each axis based on how long the unit label is for that axis.

The problem here is that the UTC label is actually longer (according to giraffe) than what is actually displayed, thus there are fewer x-axis ticks when UTC is displayed versus when Local is displayed.

**Comment by TCL735** [comment]
@russorat there are a couple of ways to address this:

1. Normalize the number of x-axis ticks that gets displayed regardless of the time label length. This number will be limited by the longest possible label.

2. Introduce an option in the UI to allow the user to choose the number of time ticks to display. The user will be limited by the maximum number of time ticks that giraffe can get from the using UTC scale on the x domain.

Please advise on which option we should proceed with.

**Comment by russorat** [comment]
> The problem here is that the UTC label is actually longer (according to giraffe)

So "Local Time" is 12 hr and ends with AM/PM, and "UTC time" is 24 hr and ends with UTC. But why? I would expect the user to be able to choose 24hr time or 12hr(AM/PM) time regardless of Local/UTC.

So, for the quick fix, we should do option 1. and the longer term fix is to allow the user to choose their preferred time format in their user settings (which we don't have yet) and probably override them on each cell if they want.

**Comment by TCL735** [comment]
Local Time shows 12 or 24 based on the user's settings and locale. UTC shows 24 hour by default and can show 12 hour format under the Time Format option by selecting `HH:mm a` with the `a` flag forcing the 12 hour format.

Okay, we will change giraffe to use the same number of time ticks for Local and UTC time.

**Comment by TCL735** [comment]
After further analysis, the real issue is the UI date format selector is not following the convention used by the underlying library. Date format must follow: https://www.npmjs.com/package/intl-dateformat

We will fix the text in the date format selector and also giraffe's time format handlers.
