### ISSUE TITLE
Grafana showing weird encoding in measurment selection dropdown

### ISSUE THREAD

**Issue by thorian93** [influxdata/influxdb#16135]
The guys over at [Grafana](https://github.com/grafana/grafana/issues/20791) suggested, that this might an InfluxDB issue, so I headed over here.

As nothing obvious changed in my environment apart from Grafana I am out of ideas so I am opening this issue. Any help is much appreciated.

__Steps to reproduce:__
As I suspect this could be due to a Grafana upgrade and I am on a production system, so I can not reproduce the problem currently.

__Expected behavior:__
Proper encoding after an upgrade.

__Actual behavior:__
Apparently after an upgrade from version 6.4.3 to 6.4.4 Grafana shows weird encodings in the measurement drop down in the query editor.

![grafana-encoding](https://user-images.githubusercontent.com/12239876/70214592-fe966580-173b-11ea-8e42-38164424e8ee.png)

__Environment info:__
* System info: Linux 4.19.0-6-amd64 x86_64, Debian 10.2
* InfluxDB version: InfluxDB v1.7.9 (git: 1.7 23bc63d43a8dc05f53afa46e3526ebb5578f3d88)
* Grafana version: 6.4.4 (commit: 092e514, branch: HEAD)
* Data Source: Icinga 2 (r2.11.2-1)

**Comment by russorat** [comment]
@thorian93 thanks for the issue. Is there anyway you can query the InfluxDB instance directly via the CLI or the API? Is there anything you can do to help us figure out if it's Grafana or InfluxDB?

**Comment by thorian93** [comment]
Hi @russorat and thanks for the reply. I have all the access necessary but zero knowledge on InfluxDB. If you can give me guidance I will gladly provide all necessary information.

**Comment by russorat** [comment]
@thorian93 no problem.

You'll need to install the `influx` tool by following the instructions here: https://docs.influxdata.com/influxdb/latest/introduction/installation/#installing-influxdb-oss

after installing, you should be able to call the following command:
`influx --help` which will show you the options.

The easiest way to send queries to your DB is to connect with the following command:
`influx -database '<YOUR DATABASE NAME>' -host '<YOUR HOST NAME (localhost)>' -port '<YOUR PORT (8086)>'`

then, you should be able to run `SHOW MEASUREMENTS` query (https://docs.influxdata.com/influxdb/v1.7/query_language/spec/#show-measurements)

If the list is garbled, that means you have something that is writing junk data into your influx instance. if that comes back correctly, then that means the issue might be in Grafana.

**Comment by thorian93** [comment]
Great instructions @russorat, thanks!  
I can verify that there are scrambled measurements, so the issue seems to be our Icinga instance, which sent scrambled data.  Is it possible somehow, that there still is an InfluxDB issue anyways?

And can you point me to how to remove this scrambled measurements in case they were just send once? Thanks in advance!

**Comment by russorat** [comment]
@thorian93 great! you can delete the measurements using this command, but be careful! 

https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#delete-measurements-with-drop-measurement

I'll close this for now, and if you discover a bug, please open a new issue. for community support requests, check out our community slack (https://influxdata.com/slack) and our forum (https://community.influxdata.com).

**Comment by thorian93** [comment]
@russorat: As this encoding issue also persists at the CLI I seem to be unable to delete the scrambled measurements. Can you give me any advice on that, as I can not find anything on the internet or does that require a new issue?

**Comment by russorat** [comment]
@thorian93 ah sorry, i steared you in the wrong direction. I believe the tool you need is `./influx_inspect deletetsm -sanitize` : https://docs.influxdata.com/influxdb/v1.7/tools/influx_inspect/#examples-1

**Comment by thorian93** [comment]
Awesome, that did the job! Thanks a lot! :)
