### ISSUE TITLE
QueryBuilder: valid queries with invalid BuilderConfigs cause wonky tab behavior

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16169]
when you have an editor, with multiple tabs for queries, deleting a tab that you are not currently viewing deletes all the queries.

![Kapture 2019-12-09 at 9 57 26](https://user-images.githubusercontent.com/4805997/70460205-a24c8200-1a6a-11ea-82db-763af926bbd0.gif)

**Comment by TCL735** [comment]
Unable to reproduce

**Comment by TCL735** [comment]
@russorat Can you please try to reproduce this and confirm if this is still an issue?

**Comment by russorat** [comment]
@TCL735 use the attached dashboard to repro. Notice that the JSON has 3 queries, the UI only shows 1, the other two don't show up. 

[website_monitor (1).json.zip](https://github.com/influxdata/influxdb/files/3958471/website_monitor.1.json.zip)

**Comment by desa** [comment]
@TCL735 I've just re-tried this with the dashboard @russorat provided and I have the same issue. I however, do not have the issue when I build a dashboard myself. I think there might be something else going on here.

**Comment by alexpaxton** [comment]
I ran into this using on a dashboard I imported that @russorat gave me. Looks like some of the dashboard cells show up as having 2 tabs, but when I switch tabs or kill one, the script disappears.

**Comment by hoorayimhelping** [comment]
can reproduce on an existing graph by editing the query and adding a new tab:

![in](https://user-images.githubusercontent.com/146112/71855386-bdc0a200-3095-11ea-9eb6-13eaec587109.gif)
