### ISSUE TITLE
Can I insert historic data with a timestamp relative to now?

### ISSUE THREAD

**Issue by arnolde** [influxdata/influxdb#16166]
I am building a battery powered IOT sensor which buffers sensor readings, i.e. once per minute, and then should bulk upload the collected values, i.e. 60 values every hour, to a cloud influxDB. But the sending device has no accurate clock and I would need to NTP synchronize it (wasting processing time, energy, and bandwidth) just to calculate timestamps to insert into the historic data.

It would be easy if I could insert the data with timestamps such as "now() - 59 minutes", "now() - 58 minutes", etc.

Is there a way to do this?

EDIT: I just tried a few things but, as feared, none of the timestamps were recognized:

```arnolde@mail00:~$ curl -XPOST 'http://localhost:8086/write?db=esp-sensors' --data-binary "TEST2 t=0.00,v=0.00 now() - 1m"
{"error":"unable to parse 'TEST2 t=0.00,v=0.00 now() - 1m': bad timestamp"}
arnolde@mail00:~$ curl -XPOST 'http://localhost:8086/write?db=esp-sensors' --data-binary "TEST2 t=0.00,v=0.00 now()-1m"
{"error":"unable to parse 'TEST2 t=0.00,v=0.00 now()-1m': bad timestamp"}
arnolde@mail00:~$ curl -XPOST 'http://localhost:8086/write?db=esp-sensors' --data-binary "TEST2 t=0.00,v=0.00 'now() - 1m'"
{"error":"unable to parse 'TEST2 t=0.00,v=0.00 'now() - 1m'': bad timestamp"}
arnolde@mail00:~$ curl -XPOST 'http://localhost:8086/write?db=esp-sensors' --data-binary "TEST2 t=0.00,v=0.00 'now()-1m'"
{"error":"unable to parse 'TEST2 t=0.00,v=0.00 'now()-1m'': bad timestamp"}
arnolde@mail00:~$ curl -XPOST 'http://localhost:8086/write?db=esp-sensors' --data-binary "TEST2 t=0.00,v=0.00 now()"
{"error":"unable to parse 'TEST2 t=0.00,v=0.00 now()': bad timestamp"}
```

**Comment by russorat** [comment]
@arnolde thanks for the issue. Line Protocol doesn't support that type of syntax as far as I know. 

I'm not sure what your script looks like, but you need to either process it on the device (which sounds like you might not have the processing power to do) or on the influxdb server before sending it into the DB (effectively using the server time as the `now()`).

We don't have any plans to add this support into LP, but I will leave this open for now in case someone would like to contribute.

**Comment by arnolde** [comment]
I could process it on the device, but since it's designed to run remotely for years on a battery, every millisecond of processing time (=not sleeping) is valuable, so I would like to avoid any timekeeping overhead if possible.
Your suggestion to add another buffer script between the device and the influxDB to preprocess the data might be an option, although I'd prefer to keep the server side as simple as possible. Thanks for the idea!

**Comment by markusr** [comment]
We implemented a solution in which we get the time from the influx server (using the HTTP header date field from the server response). 

The first request in the writer script gets the absolute time from the influx endpoint and then timestamps for the measurements points are calculated. So, it is a single additional HTTP request.

Please note that the absolute timing information is not very accurate. Maybe ~2s accuracy.

Example code in node.js
```
var http = require('http');
var options = {method: 'HEAD', host: 'localhost', port: 8086, path: '/query'};
var req = http.request(options, function(res) {
    // console.log(JSON.stringify(res.headers));
    console.log(res.headers["date"]);
    console.log(Date.parse(res.headers["date"]));
  }
);
req.end();
```

**Comment by arnolde** [comment]
@markusr Thats a good idea :-) a few seconds deviation from realtime is fine for my application. Thank you!

**Comment by russorat** [comment]
@markusr thank you for the suggestion. I'm going to close this since it is something we don't have plans to support in LP and it looks like it solves this issue.
