### ISSUE TITLE
[UI - Dashboard] Resized cell not saved consistently

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#16180]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

This is happening intermittently, so steps may need to be repeated a few times to reveal issue. 

1. Create a dashboard 
2. Create an initial cell for the dashboard and add data
3. Resize the cell 
4. Open the home page 
5. Return to the dashboards page and then open the dashboard 

To verify the 201 update of the dashboard cell, follow network calls in developer tools and also verify the REST document at `/api/v2/dashboards` before and after resizing.

__Expected behavior:__
That when the cell is resized and snapped to grid so that it is larger/smaller than its original size, that it should consistently be updated on the backend, so that when the user leaves and then returns to the dashboard, the cell is at the size to which it was last set.  

__Actual behavior:__
Frequently the call to the backend updating the cell size does not seem to be made. 

(N.B. this makes automated testing of this feature impractical)

__Screencast__

![ResizeCellNotUpdating01](https://user-images.githubusercontent.com/25881301/70535680-c341cf80-1b5d-11ea-8c14-4c2d175802db.gif)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.4.0-170-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly builds docker image.  From docker log. 
```
ts=2019-12-10T08:51:13.934227Z lvl=info msg="Welcome to InfluxDB" log_id=0Jckv~ZW000 version=nightly commit=c24137d9e build_date=2019-12-10T07:26:08Z
```
* Other relevant environment details: Container runtime, disk info, etc

Browser: __Chrome 78__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled. 
```
--e2e-testing=true
```

**Comment by desa** [comment]
@karel-rehor I've been unable to reproduce this. Is this still an issue?
