### ISSUE TITLE
Update repo for Ubuntu 19.10 (eoan)

### ISSUE THREAD

**Issue by Thumpxr** [influxdata/influxdb#16198]
Currently there is no repo for Ubuntu 19.10 (eoan), but the 19.04 (disco) repo still works fine. Would be great, if you could update the repo so that 19.10 works without any hacks.

**Comment by russorat** [comment]
@Thumpxr thanks for opening this. I will find someone to help with this.

**Comment by russorat** [comment]
@Thumpxr i think it might be there now. could you check?

**Comment by Thumpxr** [comment]
@russorat Works now, thank you!
