### ISSUE TITLE
Table sort is not working

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#16200]
Sorting a table in the UI is not working.

See attached screenshots:

![image](https://user-images.githubusercontent.com/3771906/70645783-d8246e80-1c02-11ea-9b02-eb84fb2540f4.png)
![image](https://user-images.githubusercontent.com/3771906/70645834-f25e4c80-1c02-11ea-982b-f5d391b18b82.png)

The raw data comes back sorted:

![image](https://user-images.githubusercontent.com/3771906/70645904-1588fc00-1c03-11ea-968d-e99915a8b65b.png)

Notice the data is an integer type, maybe that is part of the issue?

**Comment by russorat** [comment]
connect https://github.com/influxdata/influxdb/issues/15980

**Comment by desa** [comment]
@nathanielc which environment was this in?

**Comment by nathanielc** [comment]
@desa In the tools cluster.
