### ISSUE TITLE
CQ doesn't work

### ISSUE THREAD

**Issue by Meruem94** [influxdata/influxdb#16211]
Hi,

I use Grafana to display data trafic of my servers. But the query in Grafana is very slow due to hard aggregations and transformations. I think the best way to solve this problem is to create CQ (continuous query) in InfluxDB.

I create RP and CQ, but de CQ doesn't work. Can you help me please.

In Grafana my query is like that :

> SELECT non_negative_derivative(sum("A"), 1s) FROM "bind" WHERE ("type" =~ /^$filter$/) AND $timeFilter GROUP BY time(1m)

$filter is a variable return all my servers name

> SHOW TAG VALUES WITH KEY = $dc

Below my CQ 

> CREATE CONTINUOUS QUERY "CQBIND10" ON "telegraf" BEGIN SELECT non_negative_derivative(sum(A)) INTO "telegraf"."rp_1_min".:MEASUREMENT FROM bind WHERE type='ABO' GROUP BY time(1m),* END

I don't see error in InfluxDB log file.

My RP

> show retention policies
> name     duration shardGroupDuration replicaN default
> ----     -------- ------------------ -------- -------
> autogen  0s       168h0m0s           1        true
> rp_1_min 168h0m0s 168h0m0s           1        false
> rp_5_min 168h0m0s 168h0m0s           1        false

Why de CQ seems not working and I can't see error ?

Thnaks

**Comment by Meruem94** [comment]
I correct my CQ with and I have a result, but not what is expected

> CREATE CONTINUOUS QUERY "CQ_BIND40" ON "telegraf" BEGIN SELECT non_negative_derivative(sum(A),1s) AS A_sum INTO CQBIND40 FROM bind WHERE type ='ABO' GROUP BY time(1m),* END

The resultt below (not expected)
select * from CQBIND50
name: CQBIND50
time                 A_sum                host			 **type**          
2019-12-12T10:28:00Z  **5099.466666666666**   ***********09 **ABO**
2019-12-12T10:28:00Z  **4655.833333333333**   ***********40 **ABO**
2019-12-12T10:28:00Z  **4429.266666666666**   ***********51 **ABO**
...

Something is wrong with my query. I want the sum of A_sum of every hosts servers.  Something like this
select * from CQBIND50
name: CQBIND50
time                 A_sum                      
2019-12-12T10:28:00Z **14186**(5099+4655+4429)

**Comment by risechen** [comment]
same problem

**Comment by Meruem94** [comment]
> same problem

I add my tag after group by

CREATE CONTINUOUS QUERY "CQ_BIND40" ON "telegraf" BEGIN SELECT non_negative_derivative(sum(A),1s) AS A_sum INTO CQBIND40 FROM bind WHERE type ='ABO' GROUP BY time(1m), **type**
