### ISSUE TITLE
consistently apply env vars in CLI

### ISSUE THREAD

**Issue by jademcgough** [influxdata/influxdb#16214]
see #16048 for a list of env vars we use.

We use `viper.BindEnv` to access env vars for the CLI tool, but it isn't used in all places where it should be.

Investigate where env vars aren't being used in our CLI and add support in those places.
- the tasks cli commands don't use env vars at all
- the users cli commands also don't use env vars
- possibly other places

**Comment by dearyhud** [comment]
did a quick ack around `cmd` and found these files not using `viper.BindEnv` in places where it should

cmd/influx/bucket.go
cmd/influx/authorization.go
cmd/influx/organization.go
cmd/influx/pkg.go
cmd/influx/setup.go

@jademcgough
