### ISSUE TITLE
Convert the QUERY_TRACING env var switch into a feature flag

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/influxdb#16220]
influxdata/flux#1992 and #15459 added query tracing via opentracing to flux and influxdb.
The addition will allow OSS to capture much more detailed, per source/transformation level statistics.

At the time of those work being done, we did not have the feature flagging framework we are using now, so we put the work behind an environment variable `QUERY_TRACING`. The detailed tracing is on if  `QUERY_TRACING` is set to `1`.

We need to remove this environment variable and convert that to be a feature flag,

**Comment by jsteenb2** [comment]
hi @yzhang1991, I saw this mentioned in the `influxd` main.go file. Is this considered stable? Can we remove the if block now and just leave it on?

https://github.com/influxdata/influxdb/blob/0ae8bebd755cf4aa579b9c38e6ea4792dfdbe53a/cmd/influxd/main.go#L54-L57

**Comment by yzhang1991** [comment]
@jsteenb2 I think I hand this off to @aanthony1243 early this year and since then I do not know if `QUERY_TRACING` is ever enabled in production. Since we have feature flagging mechanisms now I think we should convert this to a feature flag and maybe that can be a permanent feature flag because the performance overhead of this tracing being enabled is still unknown to me.

**Comment by nathanielc** [comment]
DOD:

- Query traces get collected via the normal tracing system
- Feature flag that exists that enables query traces for org/user
- This does not mean that all queries for an org/user are traced on that if the query is being traced that we also trace the query spans
