### ISSUE TITLE
Support raw bytes as type

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#1623]
The system needs to support an input type of "raw bytes". It will work as follows: attempt to base64 decode all strings that enter the system. If decoding is successful, then interpret the resultant bytes as raw bytes. If decoding fails, then interpret the value as a string.

**Comment by pauldix** [comment]
It should only attempt to do this decoding if it is either a field that has already been typed as a raw bytes field or if it's a new field that hasn't been seen yet.

**Comment by otoolep** [comment]
Agreed @pauldix -- if the field already exists, the pre-existing type takes precedence.

**Comment by jsternberg** [comment]
I'm going to close this for now and we can make a new issue or reopen when this gets back on the roadmap.

If you are interested in this feature, please use a 👍 reaction on the issue.
