### ISSUE TITLE
Better Error Handling - handle and log errors closer to failing context

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#16232]
### Problem

Currently, error handling / reporting is not uniform in the way errors are reported to us or the user. Uncaught errors are caught via the error boundary (and are inevitably reported via honeybadger) with limited context on the error's origins. Errors that are caught (meaning they are ingested in the error handling process via a `catch`) then the current reporting mechanism will not work since the error won't bubble up to the `ErrorBoundary`

### Solution

Report errors to HoneyBadger closer to the failing context and let the Error Boundary be more of a last line of defense.

Use the [`reportError`](https://github.com/influxdata/influxdb/blob/master/ui/src/shared/utils/errors.ts#L17) function wherever errors are currently being caught to give us greater context on where/when/why errors are happening, and perhaps give an indication to the user that an error has occurred **AND** has been reported to us (rather than giving them the option of writing up a generic issue).

**Comment by Asalem1** [comment]
@hoorayimhelping mentioned putting together a doc on how best to integrate the error handling rather than approaching it from a wholesale reporting. Gonna put this on hold until that doc is available

**Comment by desa** [comment]
I've created an epic for this. We'll handle this over the next quarter.

**Comment by drdelambre** [comment]
testing strategy has moved this in a slightly different direction after initial exploration of this implementation.
