### ISSUE TITLE
Telegraf config bug

### ISSUE THREAD

**Issue by caitlincroft** [influxdata/influxdb#16254]
"Copy to Clipboard" seems to be missing under step 2. It shows up for Samantha, but not on mine. 
![image (1)](https://user-images.githubusercontent.com/54153319/71039609-656f3380-20d9-11ea-81fd-3f826362be8e.png)
<img width="1250" alt="Screen Shot 2019-12-17 at 2 19 08 PM" src="https://user-images.githubusercontent.com/54153319/71039619-6902ba80-20d9-11ea-8248-2c0d7fb09adb.png">

**Comment by Asalem1** [comment]
@caitlincroft do you happen to have any additional information regarding this bug? Which OS are you using? Which browser? I can't seem to recreate it locally

**Comment by caitlincroft** [comment]
MacOS Mojave 10.14.6

**Comment by Asalem1** [comment]
@caitlincroft sorry for the delay on this. I can't seem to reproduce this bug - can you let me know if it's still an issue for you before closing this out?
