### ISSUE TITLE
Check fails to create without notifying user

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#16251]
[Screen Recording 2019-12-17 at 2.00.05 PM.zip](https://github.com/influxdata/influxdb/files/3975668/Screen.Recording.2019-12-17.at.2.00.05.PM.zip)

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. open up checks UI
2. select offset equal to that of schedule
3. create valid labels on the right
4. click submit
5. UI is silent about error

__Expected behavior:__
Expected to not be able to put in an invalid entry to the input. When I did, expected to get feedback of what i done wrong.

__Actual behavior:__
Nothing, fails silent.

**Comment by ebb-tide** [comment]
Closed by #16333
