### ISSUE TITLE
UI for checks, the check lines boucing around for range options

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#16250]
[Screen Recording 2019-12-17 at 1.50.01 PM.zip](https://github.com/influxdata/influxdb/files/3975655/Screen.Recording.2019-12-17.at.1.50.01.PM.zip)

__Steps to reproduce:__

1. Go to the checks create UI and fill out the necessary deets in the query
2. select the configure check
3. on the right, create the checks for crit/warn and then select a range option for info and now start moving the bars around above as seen in the video.

__Expected behavior:__
Lines not to bounce around

__Actual behavior:__
Lines bouncing around

**Comment by Asalem1** [comment]
Closing this since I can't repro
