### ISSUE TITLE
Decimal Places table option does not work

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#16277]
I have set the decimal places to `2` for the table. The table _value column renders with all decimal places present on the raw data.

![image](https://user-images.githubusercontent.com/3771906/71118610-b17fae00-2195-11ea-9957-8815c1d8a37b.png)

**Comment by Arrgg** [comment]
This does not appear to be resolved in 2.2
![TableRounding](https://user-images.githubusercontent.com/69089596/172497972-2eb72093-caac-4852-ba1f-629085208754.png)
