### ISSUE TITLE
Add line numbers to import overlay when importing using JSON

### ISSUE THREAD

**Issue by TCL735** [influxdata/influxdb#16272]
Add line numbers to the import overlay used wherever JSON can be used for importing such as Dashboards, Variables, Tasks, and Templates.

**Comment by TCL735** [comment]
Here is an example of the import overlay showing an error message that references a line number while the overlay itself does not have any line number labels

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/10736577/71116936-f867a680-2189-11ea-80ea-1246b135f152.png">

**Comment by kristinarobinson** [comment]
Make generic to any multi-line input, should have error line number reference.

**Comment by jrenee42** [comment]
not an issue anymore, the 'import' button doesn't exist anymore.  templates have changed.  as advised by @TCL735
