### ISSUE TITLE
feat: Increase maximum flux response payload for cloud 2 free tier to 50MB

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/influxdb#16284]
__Proposal:__
In the cloud 2 free tier rate plan, allow flux response payload to be up to 50MB.
__Current behavior:__
Flux response payload is limited to a maximum of 10MB.

__Desired behavior:__
Flux response payload may be up to 50MB (to match the limit in our OSS product).

__Use case:__
There are two parts to this - first investigate whether the UI performance is acceptable if a flux response is 50MB. If it is acceptable, change the limit. If it is not acceptable, do not make the change, and instead we will track this as a future lower priority enhancement.

**Comment by kristinarobinson** [comment]
Solved.
