### ISSUE TITLE
Spike: Selective query response

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/influxdb#16285]
__Proposal:__
Optimize query responses to minimize re-reading the same data

__Current behavior:__
We are incurring large data charges in our clouds, because we re-fetch all the data, rather than just the recent data, on each dashboard refresh.

__Desired behavior:__
Optimize the query to only fetch the newer data, and merge it in with the previously fetched data.

__Alternatives considered:__
Need to research whether this is better done in the query engine, or in the UI, or in some mix of both.

__Use case:__
This is important to save money on data access.

**Comment by kristinarobinson** [comment]
Will be addressed by flux and delorean.
