### ISSUE TITLE
Table thresholding should be deactivated my default

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#16309]
<img width="1680" alt="Screenshot 2019-12-20 11 19 27" src="https://user-images.githubusercontent.com/1477539/71285679-a609bf80-231a-11ea-9719-47fb5f3ee615.png">

By default no thresholds or base colors should be applied until a threshold has been added. Alternatively the base color should be the same as the tables base color.

**Comment by desa** [comment]
cc @alsargent

**Comment by russorat** [comment]
the default behavior should be to change the text of the cell with the threshold value, not the background.

this is the feature request for adding the ability to select text or background: https://github.com/influxdata/influxdb/issues/16359
