### ISSUE TITLE
-0 displayed in single stat for -0.001 with truncated decimals

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#16306]
![image](https://user-images.githubusercontent.com/1477539/71285012-fda72b80-2318-11ea-9edd-33d24cecf227.png)

We should special case 0 so that we don't have `-0` displayed for `-0.000...`.

**Comment by desa** [comment]
cc @alsargent

**Comment by TCL735** [comment]
To add additional context, JavaScript has two different zeroes: +0 and -0
