### ISSUE TITLE
CONTRIBUTING.md is missing Rust and Typescript information

### ISSUE THREAD

**Issue by 8none1** [influxdata/influxdb#16302]
The [contribution guide](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md) is missing information detailing Rust and Typescript.

**Comment by russorat** [comment]
@desa you want to take a crack at the Typescript stuff?

**Comment by wolffcm** [comment]
The query team needs to update the README and/or CONTRIBUTING with Rust info, so I filed an issue for it: https://github.com/influxdata/influxdb/issues/16372

**Comment by russorat** [comment]
Rust is added, but not typescript.

**Comment by russorat** [comment]
Ui has moved out of this repo so i'm closing this for now.
