### ISSUE TITLE
PUT  to /checks/{checkID} should not require ownerID

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#16317]
currently a PUT to `/checks/{checkID}` with a check missing an ownerID returns a 400 with error:`{"code":"invalid","message":"Check OwnerID is invalid"}`, but PUT should not require an owner ID.

**Comment by ebb-tide** [comment]
The UI is currently handling this by first getting check by check id and then resubmitting, should refactor saveCheckFromTimeMachine when resolved.

**Comment by bm-hyfi** [comment]
I'm still getting this error. Has then been solved? How do we handle this error?
