### ISSUE TITLE
Use clean window period variables

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#16354]
Currently, when we calculate window period we do

https://github.com/influxdata/influxdb/blob/a2071478c804fdbaf8dbefdbdc013f63bd326973/ui/src/variables/utils/getWindowVars.ts#L66-L68

The result is that we end up sending a lot more data to the client than what we would expect.

We should have pre-defined bucket sizes like `10s`, `30s`,` 1m`, `5m`, `10m`, `30m`, `60m`, etc and round to the nearest depending on the duration of the query.

**Comment by ebb-tide** [comment]
currently the duration to window period relationship is
 
| duration | window period |
|---|---|
|  5m | 0.83s |
| 15m  |  2.5s | 
| 1h  |  10s | 
| 6h  | 60s   | 
| 12h  | 120s  | 
| 24h  | 240s  | 
| 2d  | 480s  | 
... 

what would be a more appropriate relationship do you think?

**Comment by ebb-tide** [comment]
waiting for https://github.com/influxdata/influxdb/pull/16385/files
