### ISSUE TITLE
UI should be more explicit with errors - Chronograf

### ISSUE THREAD

**Issue by affo** [influxdata/influxdb#16355]
When an error is reported during query execution it is part of the result and its message is listed in a separate table.

It would be nice if Chronograf could be more explicit when such errors happen.

Graph view:

![image](https://user-images.githubusercontent.com/4246582/57145144-da982d80-6dc2-11e9-966e-145dbc90d662.png)

Raw data view:

![image](https://user-images.githubusercontent.com/4246582/57145161-e4ba2c00-6dc2-11e9-84b6-a0b3e62e15a9.png)

**Comment by desa** [comment]
I think this is no longer an issue
