### ISSUE TITLE
Query disappears in data explorer when changing time range

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#16369]
![disapearing-query](https://user-images.githubusercontent.com/1477539/71627011-fac3fa80-2ba4-11ea-9ddc-828df3da5d07.gif)

To reproduce

1. switch to data explorer
2. enter the query
 ```
from(bucket: "_monitoring")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "statuses" and r._field == "_message")
  |> keep(columns: ["_time", "_value", "_check_id", "_check_name", "_level"])
  |> window(every: 1s, timeColumn: "_time", startColumn: "_start", stopColumn: "_stop")
  |> group(columns: ["_start", "_stop"])
  |> filter(fn: (r) => r["_check_id"] == "undefined")
  |> rename(columns: {"_time": "time",
                      "_value": "message",
                      "_check_id": "checkID",
                      "_check_name": "checkName",
                      "_level": "level"})
```
3. change the time range

**Comment by desa** [comment]
It seems like it resets to the state of the query builder
![defaults-to-de-state](https://user-images.githubusercontent.com/1477539/71627608-3dd39d00-2ba8-11ea-8184-dd4b2bef402b.gif)

**Comment by Asalem1** [comment]
This seems to have been broken with this PR:

https://github.com/influxdata/influxdb/pull/16226

Currently investigating why
