### ISSUE TITLE
Dates are squished to the left for graphs

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#16395]
<img width="1678" alt="Screenshot 2020-01-02 16 40 22" src="https://user-images.githubusercontent.com/1477539/71701549-fce1b100-2d7e-11ea-939b-ccc38b2ecaab.png">

**Comment by TCL735** [comment]
Might be the same issue as https://github.com/influxdata/giraffe/issues/135

We will keep both for now and ensure they are resolved together.

**Comment by TCL735** [comment]
giraffe uses d3 to determine the number of time ticks. d3 takes a **_suggestion_** on the number of ticks desired but will often ignore the suggestion and return the number of ticks based on its own algorithm.

giraffe's estimate of the number of ticks is very conservative, using the width of 'W' for the average width of a character. This leads to many cases where giraffe is underestimating the amount of available space on the axis.

In a battle of wills, giraffe truncates the array of time ticks when d3's length is longer than its own estimate. But d3 has already scaled the axis, leading to empty space at the end of the axis.

Short of giving the user control over the number of time ticks on the x-axis, giraffe should not override d3's algorithm. The simple fix is simply to remove the _if_-block at https://github.com/influxdata/giraffe/blob/master/giraffe/src/utils/getTicks.ts#L45

**Comment by TCL735** [comment]
There is one case where it is appropriate to override d3. When the actual length of the time tick label is longer than what d3.scaleUtc would create, such as this one:

`dddd, MMMM D, YYYY HH:mm:ss`

which is another way of saying for example: `Friday, January 3, 2020 17:07:18`

d3 would overlap these labels making them unreadable.
