### ISSUE TITLE
Can we execute fill(linear) function after group by?

### ISSUE THREAD

**Issue by MrKingHH** [influxdata/influxdb#16409]
Through executing InfluxQL，our original data shows below:
```bash
>SELECT host,value FROM testmetric107 WHERE time >=1483200000000000000 AND time <= 1483200013000000000 GROUP BY host
name: testmetric107
tags: host=189.120.205.136
time                host            value
----                ----            -----
1483200000000000000 189.120.205.136 0
1483200001000000000 189.120.205.136 1
1483200003000000000 189.120.205.136 3
1483200005000000000 189.120.205.136 5
1483200007000000000 189.120.205.136 7
1483200009000000000 189.120.205.136 9
1483200011000000000 189.120.205.136 11
1483200013000000000 189.120.205.136 13

name: testmetric107
tags: host=189.120.205.137
time                host            value
----                ----            -----
1483200000000000000 189.120.205.137 0
1483200001000000000 189.120.205.137 1
1483200002000000000 189.120.205.137 2
1483200003000000000 189.120.205.137 3
1483200004000000000 189.120.205.137 4
1483200005000000000 189.120.205.137 5
1483200006000000000 189.120.205.137 6
1483200007000000000 189.120.205.137 7
1483200008000000000 189.120.205.137 8
1483200009000000000 189.120.205.137 9
1483200010000000000 189.120.205.137 10
>
```
Now, we want to do linear interpolation for each group after group by. The **expected results** just like below:
```bash
>SELECT host,value FROM testmetric107 WHERE time >=1483200000000000000 AND time <= 1483200013000000000 GROUP BY host fill(linear)
name: testmetric107
tags: host=189.120.205.136
time                host            value
----                ----            -----
1483200000000000000 189.120.205.136 0
1483200001000000000 189.120.205.136 1
1483200002000000000 189.120.205.136 2 **
1483200003000000000 189.120.205.136 3
1483200004000000000 189.120.205.136 4 **
1483200005000000000 189.120.205.136 5
1483200006000000000 189.120.205.136 6 **
1483200007000000000 189.120.205.136 7
1483200008000000000 189.120.205.136 8 **
1483200009000000000 189.120.205.136 9
1483200010000000000 189.120.205.136 10 **
1483200011000000000 189.120.205.136 11
1483200012000000000 189.120.205.136 12 **
1483200013000000000 189.120.205.136 13

name: testmetric107
tags: host=189.120.205.137
time                host            value
----                ----            -----
1483200000000000000 189.120.205.137 0
1483200001000000000 189.120.205.137 1
1483200002000000000 189.120.205.137 2
1483200003000000000 189.120.205.137 3
1483200004000000000 189.120.205.137 4
1483200005000000000 189.120.205.137 5
1483200006000000000 189.120.205.137 6
1483200007000000000 189.120.205.137 7
1483200008000000000 189.120.205.137 8
1483200009000000000 189.120.205.137 9
1483200010000000000 189.120.205.137 10
1483200011000000000 189.120.205.137 
1483200012000000000 189.120.205.137 
1483200013000000000 189.120.205.137 
>
```
But the InfluxDB dosen't seem to support this operation. 
I think this is a goog feature to finish some industry tasks. 
So can we consider to support this feature in the future?
@evanphx @alexpaxton @121watts @otoolep @jwilder @jvshahid @jaredscheib @goller @corylanou
Look forward to your reply!
Thanks!

**Comment by MrKingHH** [comment]
Is there anyone to answer this question?

**Comment by MrKingHH** [comment]
@hoorayimhelping

**Comment by MrKingHH** [comment]
@jademcgough @Asalem1 @randycoulman @AlirieGray @jacobmarble @jsteenb2

**Comment by jademcgough** [comment]
@MrKingHH most influxers don't work on weekends. Please respect that by not tagging every current and former employee you can find.

If you want more immediate answers on a weekend, I'd recommend asking questions on our community slack: https://www.influxdata.com/slack

**Comment by MrKingHH** [comment]
OMG......So sorry, i forgot it was the weekend.

**Comment by jademcgough** [comment]
No problem! Sorry for the curt reply 😅

**Comment by MrKingHH** [comment]
Now, is there anyone to answer this question? >_<

**Comment by jacobmarble** [comment]
Have you tried using a subquery? Something like this:
```
SELECT * FROM (
SELECT host,value FROM testmetric107 WHERE time >=1483200000000000000 AND time <= 1483200013000000000 GROUP BY host
) FILL(linear)
```

**Comment by MrKingHH** [comment]
> Have you tried using a subquery? Something like this:
> 
> ```
> SELECT * FROM (
> SELECT host,value FROM testmetric107 WHERE time >=1483200000000000000 AND time <= 1483200013000000000 GROUP BY host
> ) FILL(linear)
> ```
I have tired this subquery, but it doesn't work. Because the **fill(linear) must be used with a function.** 
And the query details are as follows：
![image](https://user-images.githubusercontent.com/22386359/71943068-4ce6ca80-31fa-11ea-9da0-97d54f96f88d.png)
So, what i thinking about is why fill(linear) must used with a function? Is that reasonable?
Can we support a  function, e.g **none(*)**, so that we can make interpolation for the original data without any function operation, such as sum, mean, max, min etc.

**Comment by SebastianFilip** [comment]
I am not dev but it looks like your data are aligned in 1s intervals therefore you could you group by time(10s). Try this:
```
SELECT host, value FROM (
SELECT host,mean(value) AS value FROM testmetric107 WHERE time >=1483200000000000000 AND time <= 1483200013000000000 GROUP BY host, time(1s) FILL(linear)
) GROUP BY host
```
note that this should work just fine if there is expected only 1 record within 1 sec interval

**Comment by MrKingHH** [comment]
> I am not a dev but it looks like your data are aligned in 1s intervals therefore you could you group by time(1s). Try this:
> 
> ```
> SELECT host, value FROM (
> SELECT host,mean(value) AS value FROM testmetric107 WHERE time >=1483200000000000000 AND time <= 1483200013000000000 GROUP BY host, time(1s) FILL(linear)
> ) GROUP BY host
> ```
> 
> note that this should work just fine if there is expected only 1 record within 1 sec interval for each host

Yup, if our data is regular, it can work. But if not regular, it doesn't work. So, i think this suggestion is not an universal solution.

**Comment by evanphx** [comment]
I came over here to tell @MrKingHH to please not add random people to an issue just to ping them. It's rude.

**Comment by SebastianFilip** [comment]
> > I am not a dev but it looks like your data are aligned in 1s intervals therefore you could you group by time(1s). Try this:
> > ```
> > SELECT host, value FROM (
> > SELECT host,mean(value) AS value FROM testmetric107 WHERE time >=1483200000000000000 AND time <= 1483200013000000000 GROUP BY host, time(1s) FILL(linear)
> > ) GROUP BY host
> > ```
> > 
> > 
> > note that this should work just fine if there is expected only 1 record within 1 sec interval for each host
> 
> Yup, if our data is regular, it can work. But if not regular, it doesn't work. So, i think this suggestion is not an universal solution.

Sorry for trying to help, will not happen again I swear! Just think about what you want. How this linear interpolation should work if it does not know the time interval where value should be? So for irregular data it is IMO impossible...
