### ISSUE TITLE
Add Development Guide

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#16407]
There is currently no real guide to setting up Influx locally.

Here is some feedback from a user in the community slack channel:

---

Sure,  I think you need a doc that describes setting up to build Influx and have it run in debug mode (I couldn't see one).

I interpreted most of the environment from the docker file for Flux, and reading the make file / fixing errors.   (Rust for example).

The main confusion starts with the online doc for the Alpha version, which states that it is all running on Port 9999,  which works just fine for that binary. Chronograf is there etc.  The initial setup works fine.   But things fell apart after cloneing the repo and trying a build.

Parts that confused me and req support were:

* Needs Yarn, and the Yarn Install / Yarn Start for the JS  {Shouldn't this be in the Makefile ?  or at least check its up and warn ?} 
* The Port for UI being different than the 9999 default for V2 - which works fine in downloaded binary
* The 500-Internal Server error, with no corresponding error on server log when I hit the 9999 endpoint. (The API is there, but not chronograf)   ZERO info as to problem.
* The 404 Errror on same endpoint after yarn was running.  - Again, no info as to why
* Tracing the handlers in the code is 'challenging'  I found the chronograf handler eventually, but even after putting a breakpoint on every instance of http.StatusInternalServerError  still couldn't see where it was failing to load Chronograf.  

NOTE: The server itself appears to be running fine, my task is running,  telegraf is delivering, it was just the UI that was borked.

[here is the slack convo.](https://influxcommunity.slack.com/archives/CH8RV8PK5/p1577997979103700?thread_ts=1577987613.093500&cid=CH8RV8PK5)

**Comment by Wang9876543210** [comment]
okok

**Comment by pikitemplates** [comment]
great
