### ISSUE TITLE
Add keyboard shortcuts back to Monaco

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16415]
the ctrl+/ keyboard shortcut doesn't work in Monaco. We should add that back and verify the other ones work as well.

? above query editor verify that those work

**Comment by russorat** [comment]
fyi: @ebb-tide

**Comment by russorat** [comment]
maybe this could also be fixed as part of this: https://github.com/influxdata/influxdb/issues/15668

**Comment by drdelambre** [comment]
commenting is being done in here: #16615
