### ISSUE TITLE
Hovering over vertical markers is flickering

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16424]
this was supposed to be fixed in https://github.com/influxdata/influxdb/issues/15518 but it is still happening.

![Kapture 2020-01-06 at 15 51 39](https://user-images.githubusercontent.com/4805997/71857537-bea90200-309c-11ea-93e0-f7ae5217926b.gif)

**Comment by zoesteinkamp** [comment]
Im closing out this issue with #18052, they are related, it gets spazy like this when the tooltip width is too short
