### ISSUE TITLE
Dashboards & Variables pages are slow when there are a lot of them

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#16431]
![slow](https://user-images.githubusercontent.com/1477539/71912453-64568280-312a-11ea-8c16-9d6e7133fc56.gif)

**Comment by drdelambre** [comment]
to set this up, there is a magic yml file in the monitoring-team slack channel, i also have a local copy, and then you should run:
`influx pkg -o <org name> -f dashboards.yml`
to import it

**Comment by drdelambre** [comment]
closed by #16521
