### ISSUE TITLE
An InfluxDB error has occurred when trying to save a Data Explorer query as a Task

### ISSUE THREAD

**Issue by nisley** [influxdata/influxdb#16454]
Build a query and try o save it as a task:

An InfluxDB error has occurred 

![image](https://user-images.githubusercontent.com/1389799/72015432-98a76d00-3216-11ea-8fc4-4d78e05db568.png)

**Comment by nisley** [comment]
Experienced in both Cloud 2 and OSS beta

**Comment by russorat** [comment]
dupe of #16452
