### ISSUE TITLE
InfluxDB 2.0 crash when operate with ChecksAPI

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#16462]
[Java](https://github.com/influxdata/influxdb-client-java/) and [C#](https://github.com/influxdata/influxdb-client-csharp/) has support for `ChecksApi`. In our tests we create/update/delete Checks, but InfluxDB 2 in latest builds crash by unpredictable way. 

It's happen during testing ChecksAPI  - [ITChecksApi](https://github.com/influxdata/influxdb-client-java/blob/master/client/src/test/java/com/influxdb/client/ITChecksApi.java) 

__Environment info:__

* System info: Darwin 19.2.0 x86_64
* InfluxDB version: latest nightly build and first beta
* Run in docker container

__Logs:__
```
ts=2020-01-09T08:24:17.428278Z lvl=info msg=Listening log_id=0KEMJRnl000 service=http transport=http addr=:9999 port=9999
panic: assertion failed: tx closed

goroutine 563 [running]:
github.com/coreos/bbolt._assert(...)
        /go/pkg/mod/github.com/coreos/bbolt@v1.3.1-coreos.6/db.go:1133
github.com/coreos/bbolt.(*Cursor).Next(0xc000512400, 0xc0008fa768, 0xc000a77ee4, 0xc0001a3800, 0xc000a77f88, 0xc000842840, 0xc0008427e0)
        /go/pkg/mod/github.com/coreos/bbolt@v1.3.1-coreos.6/cursor.go:74 +0x169
github.com/influxdata/influxdb/bolt.(*Cursor).Next(0xc0014b5bc0, 0xc000a77ee0, 0x2, 0x1, 0x7fb8115b7500, 0x10, 0x10)
        /go/src/github.com/influxdata/influxdb/bolt/kv.go:292 +0xd5
github.com/influxdata/influxdb/kv.(*iterator).seek.func1(0xc0008427e0, 0xc0014b5c20, 0x2b6b600, 0xc0006ba900)
        /go/src/github.com/influxdata/influxdb/kv/store_base.go:598 +0xf4
created by github.com/influxdata/influxdb/kv.(*iterator).seek
        /go/src/github.com/influxdata/influxdb/kv/store_base.go:595 +0x9f
```

cc @jsteenb2

**Comment by jsteenb2** [comment]
@bednar which test is failing?

**Comment by bednar** [comment]
@jsteenb2 Thanks it works perfectly
