### ISSUE TITLE
Switching to Task tab on Save dashboard causes an error

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#16465]
### Steps to reproduce
1. go to Data Explorer
1. Click Save As
1. Switch to Task tab

https://app.honeybadger.io/projects/61122/faults/59389453

https://reactjs.org/docs/error-decoder.html/?invariant=185

```Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.```

**Comment by ebb-tide** [comment]
Confirm this is still an issue

**Comment by hoorayimhelping** [comment]
No longer an issue, fixed with: 71c875171176af8179bcd6f91559d12fae00dc95
