### ISSUE TITLE
 Make Makefiles make again

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#16468]
Our Makefiles are a bit of a mess. They need to be cleaned up and the main guidelines are:

* They should be the main and official interface into the app's building, testing and scripting processes
* They shouldn't be recursive, one makefile is enough for the whole project
* User friendliness and clear messaging is ideal. Someone unfamiliar with the project should be able to run `make` and go from there

**Comment by drdelambre** [comment]
ask: can we silence `yarn install` on this one? Gunnar gave feedback that the output of that command (with all of its unactionable warnings) gives an unclear picture into the process from a user's perspective (not FE dev).

**Comment by russorat** [comment]
we moved the UI to it's own repo. the current make command works in this repo.
