### ISSUE TITLE
Data with column error should not result in UI error screen

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#16474]
![error-column](https://user-images.githubusercontent.com/1477539/72099754-1e3e2200-32d6-11ea-8f8e-481046c63fee.gif)

This happens as we use the simply check for a column called `error` on the csv returned.

We should check for the exact schema returned when there is a runtime error and only display the error screen on that condition. See https://github.com/influxdata/flux/blob/master/docs/SPEC.md#errors

**Comment by desa** [comment]
cc @nathanielc

**Comment by desa** [comment]
Link https://github.com/influxdata/idpe/issues/5152

**Comment by docmerlin** [comment]
If as a result of this, the error column is no longer treated as an error, tasks will need to be changed to reflect this as well.

**Comment by Asalem1** [comment]
Quick update on this. This looks like it's an issue with the way Tasks are handling Threshold Checks in particular, and not Deadman Checks. To reproduce, you can use the following line protocol to add data with a space to your Bucket:

`weather,location=us-midwest tempe\ rature=82`

Once that data has been inserted, you can try to create a Threshold Check with the following:

```
from(bucket: "Test")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
|> filter(fn: (r) => r._measurement == "weather")
|> filter(fn: (r) => r._field == "tempe rature")
|> filter(fn: (r) => r.location == "us-midwest")
|> aggregateWindow(every: 1m, fn: mean)
|> yield(name: "mean")
```

Creating this as a `Deadman Check` should be successful.
This query should be successful when written in the Data Explorer using the Query Builder & Script Editor

**PROBLEM**

This query is **NOT** successful when creating a `Threshold Check`

**Comment by Asalem1** [comment]
@desa there's a PR for this, just need to see whether there's a way to reproduce an error being sent back from the API without explicitly setting `error` as the column name:

https://github.com/influxdata/influxdb/pull/17350

Let's sync up tomorrow to talk about an example we can set to do this

**Comment by desa** [comment]
@nathanielc for the data that comes back with a flux error, is it valid? Should we display this to the user, or only display the error.?

**Comment by nathanielc** [comment]
The data is coming back with a column named `error` its not a Flux error just a  column named error that could contain anything. The UI is however treating it as if the Flux query itself had an error which is incorrect.

For example this query should run without error, but the UI will present it as if it had errored because of the presence of the `error` column:

```
buckets()
 |> set(key:"error", value:"anything")
```


From my comment here https://github.com/influxdata/idpe/issues/5152#issuecomment-549540273 

>This appears to be a bug with the parser. The parser should check for the existence of the _result column as the first column and treat it as a normal result regardless of what other columns it has.

**Comment by desa** [comment]
@nathanielc what about in the case when flux has returned some amount of time series data and then an error table? Is that data valid? Should it be displayed to the user, or should we only display the error from the error table?

**Comment by nathanielc** [comment]
That case is very rare and I would display the error to the user and not the data. This way its super clear to the user that an error occurred as a result of their query.

**Comment by desa** [comment]
Closing in favor of https://github.com/influxdata/influxdb/issues/17262
