### ISSUE TITLE
Add the ability to manage secrets from the CLI

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16475]
as a user, i would like to manage my secrets via the cli. something like `./influx secrets -h`

list, create, update, delete should be supported.

**Comment by kelwang** [comment]
reopen for production suggestions.

```
Russ  31 minutes ago
1. remove the confirm. if they mess it up, just set it again? 2. Allow for scriptability so people can automate.
```
For security concern, user could use https://linux.die.net/man/1/expect and env for auto scripting
