### ISSUE TITLE
Pkger ability to provide user/env references for name/association fields

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#16472]
As a user, I'd like to provide dynamic data at run time, so that I can reuse templates without touching a file and/or editor.

```yaml
apiVersion: 0.1.0
kind: Package
meta:
  pkgName:      pkg_name
  pkgVersion:   1
  description:  pack description
spec:
  resources:
    - kind: Bucket
      name:
        envRef:
          key: "bucket_name"
```

When a user dry runs the package they'll get notified of env/user data that is needed. The package apply API would now be extended by the following:

```go
// ReqApplyPkg is the request body for a json or yaml body for the apply pkg endpoint.
type ReqApplyPkg struct {
	DryRun  bool              `json:"dryRun" yaml:"dryRun"`
	OrgID   string            `json:"orgID" yaml:"orgID"`
	Pkg     *pkger.Pkg        `json:"package" yaml:"package"`
	Secrets map[string]string `json:"secrets"`

   EnvReferences map[string]string `json:"envReferences"` // <---- NEW HERE
}

// RespApplyPkg is the response body for the apply pkg endpoint.
type RespApplyPkg struct {
	Diff    pkger.Diff    `json:"diff" yaml:"diff"`
	Errors []pkger.ValidationErr `json:"errors,omitempty" yaml:"errors,omitempty"`

	Summary pkger.Summary `json:"summary" yaml:"summary"` // <---- UPDATED
}

// Summary is a definition of all the resources that have or
// will be created from a pkg.
type Summary struct {
	Buckets               []SummaryBucket               `json:"buckets"`
	Checks                []SummaryCheck                `json:"checks"`
	Dashboards            []SummaryDashboard            `json:"dashboards"`
	NotificationEndpoints []SummaryNotificationEndpoint `json:"notificationEndpoints"`
	NotificationRules     []SummaryNotificationRule     `json:"notificationRules"`
	Labels                []SummaryLabel                `json:"labels"`
	LabelMappings         []SummaryLabelMapping         `json:"labelMappings"`
	MissingSecrets        []string                      `json:"missingSecrets"`
	Tasks                 []SummaryTask                 `json:"summaryTask"`
	TelegrafConfigs       []SummaryTelegraf             `json:"telegrafConfigs"`
	Variables             []SummaryVariable             `json:"variables"`

       EnvReferences []string `json:"missingEnvReferences"` //<---- This is new
}
```

When a user does a dry run, the API will respond with missing env references. I envision us being able to programmatically ask users for input to suit there own needs (org specific stuffs and what not). Now you can reuse a package without having to edit a file and make the contents dynamic.

Acceptance Criteria:

- [x] all resource names have envVal field
- [x] all resource associations have envVal field
- [x] extends HTTP API with dry run of missing env refs
- [x] cli provides interface for providing env refs
- [x] applying a pkg without all env vals specified will result in failed application of pkg
- [x] add documentation

**Comment by russorat** [comment]
this looks really promising. The interactive part is nice when users are exploring and learning, but pretty soon they would probably want to script this and provide the required params as a `values.yaml` file or something.

**Comment by jsteenb2** [comment]
@russorat totally agree. We can include that hereh if you'd like. There will be an accompanying flags for env references, I'm thinking something similar to how we did secrets

```sh
influx pkg --envRef=$REF_KEY_1=$REF_VAL_1 --envRef=$REF_KEY_2=$REF_VAL_2
```

does that scratch the itch?

**Comment by russorat** [comment]
this would be super helpful!
