### ISSUE TITLE
Stacked line graph type gives unexpected results

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16489]
See the gif attached. When i switch between stacked vs overlayed, i lose a few lines from the legend and i'm not sure if the graph is displaying the right information.

Issues:
1. Stacked should show the same data in the legend as overlayed.

2. Sorting in the tooltip should be applied. The hovered points from top to bottom should match, in color, to the tooltip rows from top to bottom. Negative y-axis values which can affect the vertical ordering should also be considered in this sorting.

![Kapture 2020-01-09 at 21 14 38](https://user-images.githubusercontent.com/4805997/72127673-4d2fb480-3325-11ea-9d1f-388e3748aaa5.gif)

**Comment by TCL735** [comment]
This is not an issue with the calculation of the data values for "Stacked" functionality.

It is an issue with the hover when stacked lines are very similar in measurement values (y-axis) when there are very few x-axis time ticks. The hover, which brings up the legend with the line data, is not differentiating between similar lines.
