### ISSUE TITLE
Update all access token creation to include new resources

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16492]
Right now, creating an all access token in the UI does not give you access to everything. We should update the request to truly create a token with access to all the resources in the org.

most glaringly, it is missing all the notification and alerting resources like checks, endpoints, and notificationRules.

**Comment by ebb-tide** [comment]
Quickfix- add the resources we know about today like checks / endpints / notification Rules
@goller - what is a long term solution to new resources?
