### ISSUE TITLE
windows: influx repl history isn't visible

### ISSUE THREAD

**Issue by immykins** [influxdata/influxdb#16507]
For windows users, after entering the influxdb repl and entering a flux query, no history (or the response from the query) is visible, just a flux dropdown:

![image](https://user-images.githubusercontent.com/1147449/72197104-75292180-33d2-11ea-9074-a20b0c6575a6.png)

Tested and confirmed with windows 10 and `influxdb:2.0.0-beta` docker image.

**Comment by russorat** [comment]
the repl command has been removed from the cli: https://github.com/influxdata/influxdb/pull/19040
