### ISSUE TITLE
Move Helm chart to new influxdata/helm-charts

### ISSUE THREAD

**Issue by Aisuko** [influxdata/influxdb#16508]
__Proposal:__
Short summary of the feature.

Keep influxdb Helm charts accessible for end users, and also improving maintainability of the chart(s) moving forward.

__Current behavior:__
Describe what currently happens.

The stable and incubator Helm chart repositories, currently listed on the [Helm Hub](https://hub.helm.sh/), have begun a 1 year deprecation timeline. After 6 months they will be de-listed from the Hub. See helm/charts > [Status of the Project](https://github.com/helm/charts#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts#deprecation-timeline).

Ths impact for end users is in 6 months the stable/influxdb will no longer be listed on the Helm Hub. Additionally, since [Helm 3 was released](https://helm.sh/blog/helm-3-released/), new versions of helm do not even include the `stable` repo by default. This means after 6 months, if the Influxdb charts are not moved to a new home and listed on the Hub, new users will not have a direct way to discover or install them.

__Desired behavior:__
Describe what you want.

Move influxdb charts to prepare for stable charts repo deprecation timeline.

1. Create a influxdb Helm charts github project, such as https://github.com/influxdata/tick-charts,  to be used as a Helm repository for Influxdb chart.
2. Move `stable/influxdb` from https://github.com/helm/charts/tree/master/stable/influxdb to the new GitHub project. Note that retaining git history from the beginning is much easier than trying to splice it in later (see goharbor/harbor-helm#48)
3. Include disclaimer README similar to https://github.com/elastic/helm-charts#elastic-stack-kubernetes-helm-chart. Also note these charts are community maintained, and add a basic statement about how to get involved (because it will be your own GitHub repo, you no longer need to rely on the helm/charts OWNERS file, but can add collaborators directly to the repo, if per-chart access is desired use GitHub native CODEOWNERS, etc). This all helps keep the burden low for the Influxdb team, and and shows support for Influxdb Helm Charts without adding additional liability.
4. Add automation for chart linting, testing, and releasing chart versions to the Helm Repository using GitHub pages.
5. Add new Influxdb Charts repository to the Helm Hub. See https://github.com/helm/hub#how-to-add-your-helm-charts
6. Deprecate the `stable/influxdb` charts in helm/charts. See https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart

__Alternatives considered:__
Describe other solutions or features you considered.

* About the step 4, there be demo address https://github.com/helm/charts-repo-actions-demo, I try to test these GitHub actions on my own repo, It's can work very well. 
* I'm, so happy to help on these steps above.
* Please add me and @naseemkullah as the maintainer of the new GitHub repo(The maintainer two at least). Currently listed owners:
   * stable/influxdb OWNERS: @aisuko @ jackzampolin (But jackzampolin was no longer interst in maintain the chart)
* I saw the issue [Repo Revival](https://github.com/influxdata/tick-charts/issues/115). I can confirm that `stable/influxdb` and `influxdata/tick-charts` can both exist. For me, I have responsibility for keeping the chart accessible for end-user or helm community. For `tick-charts` that can be an optional for the end-user who want try some thing different. 
* I believe the chart hosting by `influxdata` organization can make the chart more official, it better for end-user and Helm community.

Reference issue: https://github.com/jaegertracing/jaeger/issues/1976 

__Use case:__
Why is this important (helps with prioritizing requests)?

**Comment by Aisuko** [comment]
@zoesteinkamp Sorry to bother you. I saw you merged the latest of PR of the `influxdb`. May you please give some advice. Any feedback on this issue would be good.

**Comment by naseemkullah** [comment]
I think we should work with @rawkode and whoever else concerned to consolidate efforts in one repo. Be it revival `tick` repo or a new one as done with jaegertracing/jaeger#1976 .... I do think it would be nice that influx create a new github group for helm maintainers that could consist of influx + community members to maintain the charts (and be admins of the charts repo).

**Comment by naseemkullah** [comment]
Starting fresh may be better than reviving tick charts perhaps, in particular if influx agree to make this a community effort and we get @scottrigby involved in setting us up with github workflows and such.

**Comment by rawkode** [comment]
Thanks for your interest in this. I've started putting together a plan for this with my colleagues. We'll be reaching out to all the active maintainers that were doing such a great job with the official Helm repo 

Speak soon 😀
