### ISSUE TITLE
500 Internal Server Error for mean() and sum() Flux operations on 1.7.9 (arm32) and 2.0-Beta(aarch64)

### ISSUE THREAD

**Issue by dhruvsgarg** [influxdata/influxdb#16563]
__Steps to reproduce:__

1. Create new influxdb container on Raspberry Pi using the latest docker image for 1.7.9  (OR install Influxdb on Raspberry Pi 4 using .arm64 zip package for 2.0-Beta)
2. Insert few rows of data into a measurement in a bucket
3. Run sum() and mean() queries on the measurement

__Expected behavior:__
Should correctly calculate the sum/mean result as it does for the 1.7.9 or 2.0-Beta amd64 installations.

__Actual behavior:__
Error: unknown server error: 500 Internal Server Error (on 1.7.9 docker)
Error: panic: runtime error: invalid memory address or nil pointer dereference (on 2.0-Beta)

__Environment info:__
OS: Raspbian GNU/Linux 10 (buster)
*First Raspberry Pi
* System info (arm32): Linux 4.19.57-v7l+ arm7l
* InfluxDB version: InfluxDB v1.7.9 (git: 1.7 23bc63d43a8dc05f53afa46e3526ebb5578f3d88)
* Installation type: Docker, latest image (1.7.9)

*Second Raspberry Pi
* System info (aarch32): Linux 4.19.93-v8+ aarch64
* InfluxDB version: InfluxDB 2.0.0-beta.1 (git: 128b9ee9c) build_date: 2020-01-16T11:47:41Z
* Installation type: Using pre-built package downloaded from the getting started page

__Config:__
Modified influxdb.conf to enable flux. (for version 1.7.9 docker)
[http]
  flux-enabled = true

**Comment by russorat** [comment]
@dhruvsgarg thanks for the issue.

@nathanielc, should this move into the Flux repo?

**Comment by p0wertiger** [comment]
I'm having this issue as well. This is on an old ODroid C1+ and I was about to confirm on RPi3 but it seems it's architecture-specific. InfluxQL query works fine with sum(). Also affects Flux aggregateWindow(). Without these aggregations the data is returned properly.

**Comment by dhruvsgarg** [comment]
Thank you @russorat for acknowledging the issue. I was hoping that it would be addressed soon, or if there is a quick fix that I can try, I'd be happy to help!

**Comment by russorat** [comment]
@dhruvsgarg @p0wertiger So i chatted with the Flux team and it looks like Flux doesn't yet support the ARM architecture. I've opened a feature request in the Flux repo. Please follow the progress there: https://github.com/influxdata/flux/issues/2505

I'm going to close this for now. Please join us in the community Slack channel if you have more questions about running on ARM. https://influxdata.com/slack
