### ISSUE TITLE
default true options in pkger options

### ISSUE THREAD

**Issue by jademcgough** [influxdata/influxdb#16578]
When using `pkg -h` I see:

`-c, --color Enable color in output, defaults true (default true)`
`--table-borders Enable table borders, defaults true (default true)`

This feels awkward to have options that, when specified, do nothing unless explicitly set as false. Let's change these to `--disable-color` and `--disable-borders` and default to false.

**Comment by jsteenb2** [comment]
so glad you brought this up, forgot to come back and touch this up 🤦‍♂
