### ISSUE TITLE
Refactor Flux types to use new semantic.MonoType

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#16594]
With the introduction of Algo W we have new semantic.MonoType that should be used in place of any semantic.Type instances.

**Comment by wolffcm** [comment]
I was going to keep this open until we have the `feat/use-algo-w` passing in CI in influxdb.

Currently there are two failures:
- the integration tests for downstream projects
- there's issues with the Flux queries issued by the notification package, which is this issue: https://github.com/influxdata/influxdb/issues/16809

**Comment by wolffcm** [comment]
@jsternberg got the pkg-config build working, so I'm closing this.
https://github.com/influxdata/influxdb/pull/17036
