### ISSUE TITLE
Dashboard explore UI broken by bad query

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#16591]
![image](https://user-images.githubusercontent.com/17263167/72640251-58ce3d00-391c-11ea-94fe-4ef21a4a08d3.png)

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. load up dashboard explorer
2. watch the drop

__Expected behavior:__
Expected to see options and so forth come up from successful query response.

__Actual behavior:__
Error (not found) from bucket name being undefined.

req `http://localhost:8080/api/v2/query?orgID=bacbc10d8e1c6b4d` body: 

```json
{"query":"from(bucket: \"undefined\")\n  |> range(start: -1h, stop: now())\n  |> filter(fn: (r) => true)\n  |> keep(columns: [\"undefined\"])\n  |> group()\n  |> distinct(column: \"undefined\")\n  |> limit(n: 200)\n  |> sort()","dialect":{"annotations":["group","datatype","default"]}}
```

**note**: there multiple `undefined` values stringifed here

resq from query for list of buckets `http://localhost:8080/api/v2/query?orgID=bacbc10d8e1c6b4d`:

```json
{"query":"buckets()\n  |> sort(columns: [\"name\"])\n  |> limit(n: 200)","dialect":{"annotations":["group","datatype","default"]}}
```

resp: 

```csv
#group,false,false,false,false,true,false,false
#datatype,string,long,string,string,string,string,long
#default,_result,,,,,,
,result,table,name,id,organizationID,retentionPolicy,retentionPeriod
,,0,_monitoring,000000000000000b,,,604800000000000
,,0,_tasks,000000000000000a,,,259200000000000
,,0,bucket1,5ac79b7affae96ce,bacbc10d8e1c6b4d,,0
```

could be related to the following: https://github.com/influxdata/influxdb/pull/16559

**Comment by drdelambre** [comment]
cannot reproduce on latest master build. keeping around for context until it goes stale or reappears

**Comment by drdelambre** [comment]
NOTE: this might be expressed while opening up the data explorer while under load. could try to load the page while simulating a flaming computer with dev tools to repro

**Comment by desa** [comment]
@jsteenb2 are you still able to reproduce this?
