### ISSUE TITLE
Fix telegraf tokens

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#16609]
To fix this, we need to remove the automatic token creation for telegraf configs in the ui, and add the ability for the user to select a token to use. We should show the list of tokens that have the right permissions. If no token exists, we should allow the user to create a new one (one click).

We should also run a migration to remove all the labels that "connect" the tokens to the telegraf configs

_Originally posted by @russorat in https://github.com/influxdata/influxdb/issues/16059#issuecomment-561775757_

**Comment by desa** [comment]
I think we did this
