### ISSUE TITLE
max-select-point >0 still returns full query result

### ISSUE THREAD

**Issue by ulikl** [influxdata/influxdb#16604]
__Steps to reproduce:__

List the minimal actions needed to reproduce the behavior.

#8083 still not fixed.

1. restrict the query execution by the "max-select-point" parameters:

verfied by `show diagnostics`
```
...
name: config-coordinator
log-queries-after max-concurrent-queries max-select-buckets max-select-point max-select-series query-timeout write-timeout
----------------- ---------------------- ------------------ ---------------- ----------------- ------------- -------------
0s                0                      0                  100              0                 0s            10s
```
2. execute queries on a metric with cardinatity > 100. 
 e.g.
```
> select value from "project:memory_usage:request" where container='alarm-collector' and time > now() - 4h

> select count(*) from "project:memory_usage:request" where time > now() - 2h group by time(15s), container, "job"  
```

Which return more than 400 results per group.

__Expected behavior:__

according to https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.7/troubleshooting/query_management.md the Queries should be aborted with
 "ERR: max number of points reached"

__Actual behavior:__

All results are shown.
Sometime the Error message e.g.
 "ERR: max-select-point limit exceeed: (99956/100)"
is additionaly returned.

__Environment info:__

-   System info:
    docker-image influxdb:1.7.9-alpine

-  InfluxDB version:
    1.7.9

__Config:__

Only config parameter max-select-point set to 100.

**Comment by russorat** [comment]
@ulikl thank you for the issue. The only thing i can think of is that your queries are returning too fast for the check for max-select-point to be triggered. According to this PR from a few years ago, it was changed to check every 1 second: https://github.com/influxdata/influxdb/pull/8480/files

If your query executes faster than that, it might be missing that check, which would also explain why the error message only shows up sometimes. 

what do you think?

**Comment by russorat** [comment]
I also opened an issue with the docs team to add that: https://github.com/influxdata/docs.influxdata.com/issues/2608

**Comment by ulikl** [comment]
@russorat:
yes, my test queries where probably usually below 1 second response time. I went for large results, not resource intensive queries.
This timed checking is rather unexpected.

The addition of this behaviour to the Docs would be awesome.

**Comment by russorat** [comment]
@ulikl great to hear! I'll close this for now and you can follow this docs update for resolution: https://github.com/influxdata/docs.influxdata.com/issues/2608

If you have more questions, feel free to join us on Slack: https://influxdata.com/slack
