### ISSUE TITLE
Counting grouped query: unexpected behaviour

### ISSUE THREAD

**Issue by yiev** [influxdata/influxdb#16644]
**Steps to reproduce:**

1. Fill a InfluxDB measurement with values and several tags, e.g. `valuename`, `devicename`, `someflag`
2. Try to count all values of a grouped select statement by using this query: 
`SELECT COUNT(value) AS "count" FROM
(SELECT MEAN(value) AS "value" FROM measurement
WHERE time >= now()-1h AND time <= now()
GROUP BY time(1m), "valuename", "devicename", "someflag"
fill(0))`

**Expected behavior:**
Should return in my case `2684` as count.

**Actual behavior:**
Returns `77348`

On the other hand if I run this query 
`SELECT COUNT(*) FROM (SELECT MEAN(value) AS "value" FROM measurement
WHERE time >= now()-1h AND time <= now()
GROUP BY time(1m), "valuename", "devicename", "someflag"
fill(0)) GROUP BY "valuename", "devicename", "someflag"`

I get as result `44` groups with each a count value of `61`. So that are the exprected 2684 values.

But then again, if I try to sum these 44 counts together with this query, then I get again `77104` as result instead of the expected `2684` (44 * 61)
`SELECT SUM("count_value") FROM (
SELECT COUNT(*) FROM (SELECT MEAN(value) AS "value" FROM measurement
WHERE time >= now()-1h AND time <= now()
GROUP BY time(1m), "valuename", "devicename", "someflag"
fill(0)) GROUP BY "valuename", "devicename", "someflag")`

Is this a bug or am I doing something wrong?

**Comment by russorat** [comment]
@yiev thanks for opening this issue. It looks like this might be the same issue happening here: https://github.com/influxdata/influxdb/issues/9317

Seems to be a bug in the way `fill` works. I've pinged that team and they have added it to review in an upcoming maintenance release. Please follow that issue for resolution.

**Comment by yiev** [comment]
Thanks for the response, I'll follow the issue you mentioned! 👍
