### ISSUE TITLE
Can't add a new label to a variable (cloud 2)

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/influxdb#16643]
__Steps to reproduce:__
1. Go into the variables screen.
2. Select a variable, and click on + to create a new label.  
3. Create the label. 
4. The label will be created, but you'll get an error message "Failed to add label to variables".
5. Select the variable again, and select the label you just created, and now you will be able to add the label to the variable.

__Expected behavior:__
Should be able to create a new label and add it to the variable in one step.

__Actual behavior:__
Got an error message.

**Comment by drdelambre** [comment]
this was identified as a corrupted etcd store and should be resolved

**Comment by barbaranelson** [comment]
I noticed this issue after the corrupted etcd store was resolved, and I still see it today, so reopening.

**Comment by drdelambre** [comment]
many apologies, i misread this. seems to be related #15547
