### ISSUE TITLE
Pkger support multiple pkg import

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#16657]
As a user, I want to provide multiple pages for inserting, so that I can create resources and maintain my sanity when my pkgs get very large.

I can see something like:

```
my_pkgs_dir/
  - labels.yml
  - buckets.yml
```

**AC**

- should be able to reference associations in other files
- errors should include which pkg had the issue and where in it the issue happened specifically
- should support a directory structure
- shoudl be supported via the CLI like following:

```sh
influx pkg -f labels.yml -f buckets.yml -f endpoints.yml -f telegrafs.yml

# should see that it is a directory and then run all pkgs
influx pkg -f my_pkg_dirs
```

__Use case:__
This would help provide easier organization of pkgs and easier composition of pkgs together and have them all be part of the same application/dry run.

Acceptance criteria

- [x] support multiple file uploads via cli
- [x] support dir upload via cli
- [x] support multiple url upload svia cli
- [ ] support multiple pkgs via HTTP API
- [ ] support multiple urls via HTTP API
- [ ] both cli and HTTP API should support both urls and pkgs together

**Comment by russorat** [comment]
awesome! could we have the cli work like `kubectl apply -f <directory>`? https://kubernetes.io/docs/reference/kubectl/overview/#examples-common-operations

**Comment by jsteenb2** [comment]
sure @russorat add it to the AC 👍
