### ISSUE TITLE
Dashboards are broken in IE

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#16667]
## Issue

Dashboards don't render on ~Microsoft Edge~ Internet Explorer. There are console errors and it just shows a black screen.

## Steps to reproduce

Load a dashboard in ~Microsoft Edge~ Internet Explorer.

```
Error importing `index.tsx`: ChunkLoadError: Loading chunk 1 failed. (missing: https://us-west-2-1.aws.cloud2.influxdata.com/1.a686083811.js)
```
```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
```

![brokeninie](https://user-images.githubusercontent.com/146112/73087572-8caee280-3e87-11ea-8382-6aeecd8a5df8.png)

**Comment by TCL735** [comment]
This works in Edge version 80.

It does not work in IE 11.
