### ISSUE TITLE
Debug endpoints not available before TSDB is open

### ISSUE THREAD

**Issue by ayang64** [influxdata/influxdb#16664]
__Steps to reproduce:__

1. start influxd
2. attempt to access `/ping` immediately after starting -- you should not be able to until the TSDB is opened.

__Expected behavior:__
Describe what you expected to happen.

When we start influxd, we expect to be able to get results from the `/ping`, `/status`, and `/debug/*` (profiling etc.) immediately before the TSDB files are opened.

Before the TSDB files are opened, we should NOT be able to access the `/read`, `/write`, and other endpoints that depend on an active data store.

__Actual behavior:__

Debug endpoints are not available until TSDB is loaded.

__Environment info:__

* System info: Run `uname -srm` and copy the output here

Linux 5.4.0-9-generic x86_64 -- but this should affect all operating systems and architectures.

* InfluxDB version: Run `influxd version` and copy the output here

1.7.x

**Comment by dgnorton** [comment]
This should be fixed once https://github.com/influxdata/influxdb/pull/16836 merges.
