### ISSUE TITLE
Add Client Libraries to the Add Data option in buckets

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16661]
We should add the option to add data from a client library and drop the user on the client libraries tab when that happens.

![image](https://user-images.githubusercontent.com/4805997/73030525-b405a100-3dee-11ea-8eba-04a1a855933a.png)

**Comment by drdelambre** [comment]
what description would you like on it?

**Comment by russorat** [comment]
How about `Write data easily from your own application.`
