### ISSUE TITLE
InfluxDB2 does not load buckets (and data) when changing browser or ip

### ISSUE THREAD

**Issue by g-wolter** [influxdata/influxdb#16683]
__Steps to reproduce:__

1. `wget https://dl.influxdata.com/influxdb/releases/influxdb_2.0.0-beta.2_linux_amd64.tar.gz`
2. `tar xvfz influxdb_2.0.0-beta.2_linux_amd64.tar.gz`
3. `cp influxdb_2.0.0-beta.2_linux_amd64/{influx,influxd} /usr/local/bin/`
4. `influxd --reporting-disabled`
5. Setup the DB
6. Stop the DB (Ctrl-c)
7. `mv ~/.influxdbv2/ /opt/influx/`
8. `influxd --engine-path=/opt/influx/.influxdbv2/engine --reporting-disabled  --bolt-path=/opt/influx/.influxdbv2/influxd.bolt  --log-level=debug &> /var/log/influx/influxd &`
9. `disown %1`
10. Open the UI on one device/browser and log in (everything works)
11. Open the UI on a second device/browser and log in (no data loads)

__Expected behavior:__
To log in from another device/browser/IP and see data.

__Actual behavior:__
I am able to log in, but cannot view any buckets/data in dashboards. The data explorer shows "Failed to load buckets" and the panels in a dashboard are showing "unauthorized access" and "This dashboard doesn't have any cells with defined variables." while being logged in.

__Environment info:__

* System info: Linux 3.10.0-1062.9.1.el7.x86_64 x86_64
* InfluxDB version: InfluxDB 2.0.0-beta.2 (git: 455d40e0c) build_date: 2020-01-28T08:47:51Z
* Other relevant environment details: Moved .influxdbv2 to /opt/influx/

__Config:__
n/a

__Logs:__
ts=2020-01-28T10:13:03.429804Z lvl=debug msg=Request log_id=0KbqoABl000 service=http method=POST host=SERVERNAME:9999 path=/api/v2/query query="orgID=bae615f8be3f74ce" proto=HTTP/1.1 status_code=401 response_size=55 content_length=130 referrer=http://SERVERNAME:9999/orgs/bae615f8be3f74ce/data-explorer remote=CLIENTIP:7789 user_agent=Firefox took=0.132ms error=unauthorized error_code=X-Platform-Error-Code body=

**Comment by russorat** [comment]
@g-wolter thanks for this issue. Not sure what's going on there but I will pass it to the UI team to investigate.

**Comment by glinton** [comment]
@g-wolter Can you ensure you clear the cache/cookies/local data/etc on the second device? Though, while trying to reproduce this, I didn't clear mine and it worked just fine. I tested this with the same version you linked above and can see dashboards and explore data from a browser on the device running `influxd` (`ubuntu 19.10`), an android phone, as well as another pc (`win 10`).

Is this still an issue for you and is it still reproducible for you using your instructions? I doubt it's a firewall issue as the log you posted seems to be from `influxd` itself meaning the request from the other client made it. I tried changing the ownership and permissions of `/opt/influx` as well, but cannot get influxd to start if they are too strict, and again haven't been able to reproduce this when it does start.

If this is still not working for you after trying again, i'll install centos 7 to see if it's platform specific.

**Comment by g-wolter** [comment]
The issue persists after clearing the cache. I will update to the latest version as the release notes state: 
> his release resolves a regression discovered in InfluxDB 2.0.0 Beta 3 where for some users, after logging in, not all of their dashboards, tasks, or other assets in the UI would be shown

**Comment by g-wolter** [comment]
The update has resolved the issue. I guess this is fixed.
