### ISSUE TITLE
Unable to parse [] : Invalid Number 

### ISSUE THREAD

**Issue by Tatya-winchu** [influxdata/influxdb#16692]
Hello,
 I am trying to write data into Db but getting following error.
`'MSMT_NAME,TAG1=manual,Tag2_Type=[object Object],Tag_id=5e33ef7235c3cb755b6c56ee,Tag_2_id=-1,name=GVV2000,service=someservice,status=STATUS_TESTING _id="5e33ef727b5c952se3386e5c4",address.ipv4="SomeIp",enabled=true,busy=false,online=true,status="STATUS_TESTING",docked=true,held=false,deleted=false,inZone=false,type="SOMETYPE",some.0.id="5e33ef727b5c952se3386e5c4",some.0.name="locTop",some.0.sha="1amkdwwdw,x2773ß3407xnjd",some.0._id="5e33ef727b5c95756486e5c5",version="Version:some0.001",someVersion="some1",tcuVersion="some1",someReference="111111111111111111111111",curTask="test",someReference="5ba4c104d638ec66e84086bf",dirty=true': invalid number`

Library I use is influxdb-node -v 3.0.1
InfluxDb Version.- 1.4.7
Please guide.

**Comment by russorat** [comment]
@Tatya-winchu thank you for the issue. I think you have an issue with whatever is generating that line protocol. Your second tag is `Tag2_Type=[object Object]` but tags can only be string values. If you post a snippet of the code creating the line protocol to insert, i will take a look.

**Comment by Tatya-winchu** [comment]
@russorat Hey! Thanks for pointing out the mistake :) the issue is resolved

**Comment by russorat** [comment]
Great! join us in Slack if you have more questions! https://influxdata.com/slack
