### ISSUE TITLE
Develop a ragel-based line protocol parser for use in filtering applications

### ISSUE THREAD

**Issue by adrian-thurston** [influxdata/influxdb#16717]
At the all hands it was discussed with @GeorgeMac that a ragel-based line protocol parser for use in filtering applications would be welcome, with the goal of speeding up parsing and getting a better filtering throughput.

Some context here:

https://github.com/influxdata/influxdb/pull/16412

**Comment by GeorgeMac** [comment]
cc @stuartcarnie as using Ragel for this was his idea first :D

**Comment by adriandt** [comment]
@goller points out one exists already here:

https://github.com/influxdata/telegraf/blob/master/plugins/parsers/influx/machine.go.rl

**Comment by danielnelson** [comment]
There is currently some work on a streaming interface for this parser in the influxdb-listener-refactor branch.  We plan to use this to parse request bodies without loading the full request into memory.  One potential issue with the parser I should mention is that it does not do any unicode validation.

**Comment by adrian-thurston** [comment]
Closing, as this exists already in telegraf.
