### ISSUE TITLE
InfluxDB 1.8 should use Go modules

### ISSUE THREAD

**Issue by ayang64** [influxdata/influxdb#16718]
__Proposal:__
Short summary of the feature.

__Current behavior:__
Describe what currently happens.

__Desired behavior:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Why is this important (helps with prioritizing requests)?

**Comment by dgnorton** [comment]
Closed by https://github.com/influxdata/influxdb/pull/16944
