### ISSUE TITLE
Backup and Restore OSS: If Credentials file doesn't exist, then the User with the correct permissions receives a 500 error when running the `influx backup` command

### ISSUE THREAD

**Issue by stephanie-engel** [influxdata/influxdb#16723]
**Issue:**
Within my OSS instance, when I attempt to run `influx backup` (with the default user account that has read and write permissions to everything), the following error is returned: `Error: An internal error has occurred`.

**Steps:**
1) Go to the `influxdb` repo and pull latest from `master`
2) If exists, remove your local `.influxdbv2` directory so that a new setup is allowed
3) Start influxd: `bin/$(uname -s | tr [:upper:] [:lower:])/influxd`
4) Create a new org, bucket, and user via the following request:
`curl -X POST \
  http://localhost:9999/api/v2/setup \
  -d '{
    "username": "my-user",
    "password": "password",
    "org": "my-org",
    "bucket": "my-bucket"
}'`

5) Copy the token that is generated from the previous request and, using the influx CLI, run the following command (make sure to replace the directory name and token values with your own values):
`influx backup -p directoryNameForNewBackup -t copiedTokenValue`

**Results:**
- The org, bucket, and user are all successfully created
- Per the `influxd` logs, the Cache snapshot is started and the Snapshot for path written
- The `influx backup` command returns the message: `Error: An internal error has occurred`

**Additional Troubleshooting:**
- I confirmed that the above created user token can be successfully used with the command `influx org find -t copiedTokenValue` and correctly returns the org ID and Name
- I created 2 additional super users at the org, and when I attempted to start a backup with those tokens, I correctly received the following error: `Error: read:authorizations is unauthorized` since user permissions are not fully implemented.

**Comment by stephanie-engel** [comment]
I assume this issue will also happen when running the `influx restore` command too.

**Comment by Hoiy** [comment]
Having exactly the same issue with

1. `docker run --name influxdb -p 9999:9999 quay.io/influxdb/influxdb:2.0.0-beta`
2. browse to `localhost:9999` to setup
3. `docker exec -it influxdb bash`
4. `influx backup -t <tokens> -p /tmp` > `Error: An internal error has occurred`

Unable to do any backup
