### ISSUE TITLE
[Dashboard - Cell Edit] Edit query of existing cell and then switch to Query builder puts graphs out of sync with queries

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#16731]
__Steps to reproduce:__

1. Generate two sets of test data
2. Create a dashboard and add a cell to that dashboard
3. Define the query for the cell using query builder and one set of data and save the cell 
4. Open the cell configuration again and switch to Script editor and redefine the query using the second set of data.  Save the cell query. 
5. Open the cell configuration again and switch to Query Builder, accepting the warning. 

__Expected behavior:__

Expected that Query Builder would either reflect the script that was in the editor, or would reset to a state offering the bucket selector and an initial tag selector and that the preview graph would reflect the query builder selections or be blank. 

__Actual behavior:__

The Query builder reflects the old query and the graph both the old (from step 3) and the new query ( from step 4).

6. Click on Script editor again and it reflects neither what was in query builder, nor the query from step 4, nor the contents of the preview area. 
7. Click save.  The cell shows the graph from the preview area and does not reflect the last query in the script editor. 

__Screencast__

![CellEditSwitchToQueryBuilder](https://user-images.githubusercontent.com/25881301/73843673-58d8a300-481f-11ea-90a3-b6184be941bb.gif)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-76-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly build
```
ts=2020-02-05T08:53:17.304795Z lvl=info msg="Welcome to InfluxDB" log_id=0Km8hTU0000 version=nightly commit=64c870759 build_date=2020-02-05T08:53:17Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 79__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with end to end testing enabled. 

```
--e2e-testing=true
```

**Comment by drdelambre** [comment]
@hoorayimhelping i did some poking around and got this working, but it is caused by the field `aggregateFunctionType` not existing on the the draftQueries builderConfig, which is used to build the queryBuilder after you come out of the other side of this button. Seems like you added that concept for the groupBy feature. what does that field mean? is there a reason it doesn't exist on the view? why don't types break?

**Comment by hoorayimhelping** [comment]
>is there a reason it doesn't exist on the view?

we mentioned this in a Slack conversation, but repeating here: Having not looked at it, I'd guess it's because I forgot to add the `aggregateFunctionType` to the draftQueries builderConfig.

`aggregateFunctionType` represents the type of function to perform - either filter or group

**Comment by hoorayimhelping** [comment]
No longer an issue. Unable to reproduce
