### ISSUE TITLE
Jump row on select

### ISSUE THREAD

**Issue by fvgarcia** [influxdata/influxdb#16780]
I do the following query, but I want to jump the 18:00:00 row. How do I do that?
`SELECT (last("field") - first("field")) as ETC FROM "db" WHERE "topic" = 'test/devices/[[var_topic]]/up' AND $timeFilter GROUP BY time(3h) fill(linear)`
![image](https://user-images.githubusercontent.com/20287680/74049846-c0275c00-49b3-11ea-8417-59bb474084f5.png)

**Comment by russorat** [comment]
@fvgarcia thanks for opening this issue. I'm not sure what you mean by "jump to" the specific timestamp. You can use limit and offset to adjust your results: https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#the-offset-and-soffset-clauses

This question is better suited for our community sites, either https://community.influxdata.com or Slack https://influxdata.com/slack. I'm going to close this and look forward to your questions there.
