### ISSUE TITLE
Confusing message after clicking "Copy to clipboard" in UI for access token

### ISSUE THREAD

**Issue by wojciechka** [influxdata/influxdb#16781]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create an access token (reproducible for any type of token)
2. Open the new token
3. Click "Copy to Clipboard"

__Expected behavior:__
Seeing a message "Token has been copied to clipboard" or similar

__Actual behavior:__
Script '(token)' has been copied to clipboard.

Screenshot:
![image](https://user-images.githubusercontent.com/683972/74051752-dabffc00-49d8-11ea-8307-50c120406185.png)

__Environment info:__
InfluxDB Cloud 2.0, US West 2 region.

**Comment by russorat** [comment]
the component is reused throughout the app anytime we display code in the UI (see also the client libs page). Just keep that in mind when updating this.
