### ISSUE TITLE
Client: Write() shouldn't allow a write without a single parameter

### ISSUE THREAD

**Issue by d2g** [influxdata/influxdb#1679]
Currently you can call the write function on the client without any parameters. 
i.e.
	c, err := client.NewClient(config)
	if err != nil {
		t.Fatalf("unexpected error.  expected %v, actual %v", nil, err)
	}

	_, err = c.Write()
	if err == nil {
		t.Fatalf("unexpected error.  expected %v, actual %v", nil, err)
	}
will not error

I can' think of an instance where you would want to allow zero writes.

Can I suggest the function is changed to:
func (c *Client) Write(w Write, ws ...Write) (*Results, error)

**Comment by corylanou** [comment]
I think the signature is fine, but we should check for `len(writes) > 0` and if not, throw an error.

**Comment by jsternberg** [comment]
It looks like this was fixed in #1868. I'm closing this since it doesn't seem to be relevant anymore. Please reopen if this is still an issue. Thanks.
