### ISSUE TITLE
TELEGRAF PROBLEM

### ISSUE THREAD

**Issue by Daly123456** [influxdata/influxdb#16791]
i'am using grafana + influxdb - telegraf for 2 months now i suddenly had a problem like this :
![image](https://user-images.githubusercontent.com/46686877/74139188-38c82b80-4bf3-11ea-8019-380237062c83.png)
![image](https://user-images.githubusercontent.com/46686877/74139212-42ea2a00-4bf3-11ea-94a9-260baa757b72.png)

some help please :(

**Comment by davidgs** [comment]
This would be a great question to post in our community slack, or our community forums.

**Comment by russorat** [comment]
my guess is your influxdb server is down. i'm closing this for now. please reopen if you still have this issue.
