### ISSUE TITLE
Test failure scenarios

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#168]
Some scenarios to try:
- Write in many millions of points with single server failure
- Recover server after many millions of writes
- Send queries to server right after it comes up
- Replacing a node while cluster is under load
- Kill the raft leader and make sure continuous queries still work
- Network partition 1-n servers

**Comment by jamtur01** [comment]
@pauldix Curious if any Jepsen (or -esque) tests got run? Thanks!

**Comment by pauldix** [comment]
@jamtur01 Not yet, it's definitely on our todo list. Have to finish the other parts of clustering first.

**Comment by contra** [comment]
@pauldix Shouldn't this be reopened if it wasn't fixed?

**Comment by pauldix** [comment]
@contra clustering is now a closed source feature so this isn't relevant any more to the OSS InfluxDB.
