### ISSUE TITLE
Enable "error reporting" capability on errored lines

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#16801]

**Comment by ebb-tide** [comment]
LSP reports syntax errors in the response to onChange events, currently Monaco is not receiving/displaying these messages. 
It is possible that the monaco client will handle displaying the errors in the appropriate line, but this issue may include monaco work if it does not. 
Use this issue to scope out communicating generically with the LSP server to estimate the rest of the work in this epic.

**Comment by jademcgough** [comment]
Closed by #17343
