### ISSUE TITLE
InfluxQL tests failing in algo W branch

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#16811]
There are two InfluxQL transpiler tests failing in the `feat/use-algo-w` branch:
- `ors.influxql`
- `ands.influxql`

They are failing with the message:
```
failed to run query: could not get handle from JSON AST: recursion limit exceeded at line 1 column 8056
```

The tests have been commented out with this issue URL.

**Comment by jlapacik** [comment]
In the case of `ands.influxql`, the test case involves transpiling and then evaluating a simple `SELECT` query with 200 conjunctive predicates in the `WHERE` clause. `ors.influxql` is symmetrical.

The issue occurs in the evaluation of the transpiled flux AST. The initial AST resides in Go. It is then serialized as JSON where Rust is invoked to deserialize it and perform the rest of semantic analysis. In JSON the `WHERE` predicate is expressed as 200 nested JSON objects, and the recursion limit is exceeded when `serde_json` is deserializing the object into a Rust AST.

It is possible to remove `serde_json`s recursion limit, however care would need to be taken to ensure we did not explode the stack. A more permanent solution is to remove JSON serialization from the parsing process entirely. That is outlined [here](https://github.com/influxdata/flux/issues/2365).

I'm going to keep these tests skipped at this time and move this issue to the backlog. `serde_json` has a default recursion depth of 128 https://github.com/serde-rs/json/blob/master/src/de.rs#L48 which seems reasonable for now.
