### ISSUE TITLE
Client config struct should be replaced with functional options

### ISSUE THREAD

**Issue by d2g** [influxdata/influxdb#1681]
By using functional options adding new parameters like the recent user agent becomes easier.

The advantages are explained better in the following blog post:

http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

**Comment by jsternberg** [comment]
We're not going to make any changes to the official go client at the moment. Feel free to make your own and comment on this issue with a link. If it's fully functional, we can put it as an alternative on our website.

Thank you for your interest.
