### ISSUE TITLE
[Dashboard - UI] - add function to existing cell query loses tags 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#16816]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

Generate two sets of test data based on various tags.  

1. Create a dashboard and add a cell 
2. Define the cell query using Query Builder with one or more tags
3. Save the cell 
4. Click configure on the cell - Cell Editor opens - Verify in dev tools the request payload query
5. Add a function to the query, e.g. mean 
6. Click submit 

__Expected behavior:__
Describe what you expected to happen.

That the preview would show the graph using the tags already selected and the mean of the values over the time window. 

__Actual behavior:__
Describe What actually happened.

Preview shows two curves. 

Inspecting the request payload shows:  

Request Payload query on opening Cell Editor 

```
"from(bucket: "qa")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "beat")
  |> filter(fn: (r) => r._field == "pulse")"
```

Request Payload after adding function and clicking submit 

```
"from(bucket: "qa")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")"
```

The tags, which are still shown in the query builder as selected, are not in the payload query. 

__Related__
#16731

__Screencast__

![QueryBuilderLosesTags01](https://user-images.githubusercontent.com/25881301/74254369-a3ab5c80-4cf0-11ea-8bee-e7a5fa3dfb6d.gif)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-76-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly builds. 
```
ts=2020-02-11T12:41:31.547135Z lvl=info msg="Welcome to InfluxDB" log_id=0Ku48vbl000 version=nightly commit=7188363c2 build_date=2020-02-11T12:41:31Z
```
* Other relevant environment details: Container runtime, disk info, etc

Browser: __Chrome 79__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled. 

```
--e2e-testing=true
```

**Comment by desa** [comment]
@karel-rehor can you confirm that this is still the case? I've been unable to reproduce this.

**Comment by karel-rehor** [comment]
@desa Works for me in latest nightly build. 

```
version=nightly commit=bdc882f6ce build_date=2020-05-12T07:41:12Z
```

Query in payload after adding function `mean()` and then submitting:

```
from(bucket: "qa")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "foo")
  |> filter(fn: (r) => r["_field"] == "signal")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```

No longer an issue.
