### ISSUE TITLE
Cmd-Ctrl shortcut to submit query broken

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#16848]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. open up script editor and write a query
2. press `cmd-enter` | `ctrl-enter`

__Expected behavior:__
Expected query to submit

__Actual behavior:__
Nada

__Environment info:__

Firefox browser

**Comment by drdelambre** [comment]
@ebb-tide i remember a discussion around this during last planning meeting. is this a dupe or regression?
