### ISSUE TITLE
Refactor tasks dependency on the Flux parser

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#16844]
The root package for `influxdb` makes use of the Flux parser, which will mean that any client code including this package will have a dependency on Rust:

https://github.com/influxdata/influxdb/blob/a5f508de771c6383729baa9f634b5518fedf2ed7/task.go#L297

We should remove this dependency.

The root `influxdb` package also depends on `influxdb/task/options` which also needs the Flux parser.  The root package `influxdb` should not depend on `influxdb/task/options` either.

In addition, the very commonly-used packages `influxdb/http`, `influxdb/kv` and `influxdb/authorizer` require the `influxdb/task/backend` package, which ultimately also requires the Flux parser.  These three commonly used packages should not import `influxdb/task/backend`.  (Perhaps the types declared in `backend` can be moved up into the `influxdb` root package)

**Comment by jsternberg** [comment]
I can't find any usage of the parser in `influxdb/task/backend`. I am seeing the dependency in the root `influxdb/task.go`. I attempted to grep for `parser` in the package and couldn't find it. I do see that `influxdb/task/backend` depends on the root package so I am hoping removing it from the root will eliminate that requirement.

I might be missing something though.

**Comment by wolffcm** [comment]
The dependency is not direct, here it is (I should have included these charts for everything):
![task_backend_deps](https://user-images.githubusercontent.com/7902964/75925976-7dc03600-5e1e-11ea-81e2-2dcec401ca82.png)

**Comment by jsternberg** [comment]
Ah so it is because of the `task/options` dependency. That makes sense.
