### ISSUE TITLE
Refactor read service dependency on Flux parser

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#16850]
The storage read service indirectly depends on the Flux parser.  We should remove this dependency so that storage does not need Rust to build.

Maybe we can invert the dependency between `stdlib/influxdata/influxdb` and `storage/reads`.  Or maybe there's a better or simpler solution.

Here is the relevant dependency graph:
![graph](https://user-images.githubusercontent.com/7902964/74388305-f009a180-4daf-11ea-9bd2-8b542856d1a0.png)

**Comment by jsternberg** [comment]
It looks like the only dependency on the parser is using the internal go parser to parse the time in type conversion. If we switch the type conversion function to use the internal pure go parser which it is already using anyway, we break this dependency.

That seems to be the only direct dependency.
