### ISSUE TITLE
go module for v2 needs to end in "v2".

### ISSUE THREAD

**Issue by mildebrandt** [influxdata/influxdb#16872]
When attempting to `go get` the influxdb v2 code, I get the following error:
```
$ go get github.com/influxdata/influxdb@v2.0.0-beta.3
go: finding github.com/influxdata/influxdb v2.0.0-beta.3
go: finding github.com v2.0.0-beta.3
go: finding github.com/influxdata v2.0.0-beta.3
go: finding github.com/influxdata/influxdb v2.0.0-beta.3
go get github.com/influxdata/influxdb@v2.0.0-beta.3: github.com/influxdata/influxdb@v2.0.0-beta.3: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

This is because the `go.mod` file is missing a `v2` at the end of the module name. It should be:
```
module github.com/mildebrandt/influxdb/v2
```

See for additional information: https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

**Comment by russorat** [comment]
@mildebrandt thanks for opening this. I'll find someone to help fix.

**Comment by mark-rushakoff** [comment]
We have had some internal discussion about this but haven't yet taken any action.

Right now, in our internal dependencies on influxdb we either `go get github.com/influxdata/influxdb@master` or at a specific SHA.

Are we at the point where we need to fix this now @jsternberg?

**Comment by jsternberg** [comment]
I think it would be good to fix it. We just need to decide on a time and do an announcement because it will cause a merge conflict and require an update for every PR.

**Comment by nikgibbens** [comment]
I'm having the same issue.

**Comment by russorat** [comment]
@jsternberg @rickspencer3 any update on the PR to fix this?

**Comment by jsternberg** [comment]
This should be good now. Please tell me if you have any problems with it.
