### ISSUE TITLE
SHOW MEASUREMENTS syntax inconsistency with documentation

### ISSUE THREAD

**Issue by Igor-Toropov** [influxdata/influxdb#16870]
As per https://docs.influxdata.com/influxdb/v1.7/query_language/schema_exploration/#show-measurements
SHOW MEASUREMENTS syntax is
SHOW MEASUREMENTS [ON <database_name>] [WITH MEASUREMENT <regular_expression>] [WHERE <tag_key> <operator> ['<tag_value>' | <regular_expression>]] [LIMIT_clause] [OFFSET_clause]

When I submit 
SHOW+MEASUREMENTS+WITH+MEASUREMENT+/c/
I get error 
{
    "error": "error parsing query: found /, expected =, =~ at line 1, char 36"
}

InfluxDB version 1.7.9

It appears that now not only regular expressions are supported but also exact match, wich probably return 1 or 0 results, so somewhat useless.
If documentation is not updted, it shoud show
 < operator> ['<tag_value>' | <regular_expression>]
instead of just
<regular_expression>

Thank you very much
--
Igor Toropov

**Comment by russorat** [comment]
@Igor-Toropov thanks for opening. We will get the docs updated.

**Comment by sanderson** [comment]
Thanks for pointing this out @Igor-Toropov. This has been updated and will be deployed some time today.

**Comment by Igor-Toropov** [comment]
Thank you very much for quick turnaround, Russ and Scott.
Just a minor suggestion:
  May measurement-name be replaced with measurement_name for consistency?
Thank you very much.

**Comment by sanderson** [comment]
@Igor-Toropov done
