### ISSUE TITLE
Backup failure

### ISSUE THREAD

**Issue by flopp999** [influxdata/influxdb#16873]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. change bind-adress from 127.0.0.1:8088 to 127.0.0.1.8087, in influxdb.conf
2. restart Influxd
3. try to make a backup

__Expected behavior:__
get a full back

__Actual behavior:__
it reports that "Download shard 0 failed
see here https://community.influxdata.com/t/backup-not-working/12985

__Environment info:__

* System info: Debian 10
* InfluxDB version: 1.7.10

I had something that runs on port 8088 so I changed to 8087 after this the backup function is not working.
When I closed the other program that was using port 8087, when I then run the backup is says that is cannot access port 8088!!! WHAT, I have change port to 8087 in influxdb.conf, but it doesn't seems to make any change.

After I change to port 8088 in influxdb.conf it worked fine.

**Comment by russorat** [comment]
@flopp999 thanks for opening this. We will investigate.

**Comment by russorat** [comment]
Could you add the command you were using to run the backup?

**Comment by flopp999** [comment]
> Could you add the command you were using to run the backup?

“influxd backup influxbackup”

The answer is available in the link to your community

**Comment by davidby-influx** [comment]
When you change the port in influxdb.conf, you have to change the port in the backup command to match that.  See the documentation here:

https://docs.influxdata.com/influxdb/v1.8/administration/backup_and_restore/#online-backup-and-restore-for-influxdb-oss

Would you be able to try with the 8087 port specified as described in the link above and let us know if that works?  Thank you for your help!

**Comment by davidby-influx** [comment]
No response from user.  Closing.
