### ISSUE TITLE
Add variables values to URL

### ISSUE THREAD

**Issue by gitirabassi** [influxdata/influxdb#16884]
__Proposal:__
I'd like to be able to share a dashboard with the variables defined in the url

__Current behavior:__
Right now, if I have a dashboard with one or more variables and I want to share the dashboard with a collegue or a friend. I have to share the link of the dashboard and tell them to set the variables to the value I require

__Desired behavior:__
The value of the variables should be url paramethers much lilke in Chronograf

__Use case:__
Why is this important (helps with prioritizing requests)? We all know that sharing is caring, the easier we make the sharing of information the better. For better debugging of issues and postmortems

**Comment by drdelambre** [comment]
this is in prod now.. closed with #17522
