### ISSUE TITLE
can't undo changes in query editor

### ISSUE THREAD

**Issue by jademcgough** [influxdata/influxdb#16917]
When using `ctrl-z` to undo changes in the query editor, I can only go back one change. Pressing ctrl-z again just reverts to the original state.

![undo](https://user-images.githubusercontent.com/1147449/74791717-22177980-5270-11ea-8bed-d3c148603fd5.gif)

**Comment by drdelambre** [comment]
cannot reproduce after 31cfbde3809eb60387b8ac8a532b0ba8a1446b82

**Comment by jademcgough** [comment]
@drdelambre awesome, I'll close :)
