### ISSUE TITLE
[ Settings > Variables ] Able to create variables with names that will cause flux errors 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#16921]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open Settings > Variables 
2. Click Create Variable > New Variable
3. Name the variable "test" or "My-Var"
4. Proceed to define the type and keys or a query and save. 
5. Open a dashboard cell script editor and add the variable to the script. 
6. Click submit, or otherwise refresh the preview 

__Expected behavior:__
Describe what you expected to happen.

When creating the variable, expected that a variable named using a keyword (e.g. "test","import") or one using characters that can be interpreted in flux as mathematical or other operators, would be flagged with a warning or prohibited. 

__Actual behavior:__
Describe What actually happened.

I am able to create such variables and, when they are added to a flux script, result in 500 backend internal server errors, some of which are quick to understand, others less so (e.g. did not know that 'test' is a reserved keyword. 

__Screenshots__ 

![UnsuitableVarNames01](https://user-images.githubusercontent.com/25881301/74837288-73337600-5321-11ea-8829-74f532ac80e2.png)

__Screencasts__ 

![UnsuitableVarNames00](https://user-images.githubusercontent.com/25881301/74837313-85151900-5321-11ea-89f0-8e1a74625a5b.gif)
![UnsuitableVarNames01](https://user-images.githubusercontent.com/25881301/74837317-85adaf80-5321-11ea-85c8-5c9ecac82592.gif)
![UnsuitableVarNames02](https://user-images.githubusercontent.com/25881301/74837319-86464600-5321-11ea-90bb-c48d56eff499.gif)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-88-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly build. 
```
ts=2020-02-19T09:11:11.599024Z lvl=info msg="Welcome to InfluxDB" log_id=0L3BI9wl000 version=nightly commit=b24be19b5 build_date=2020-02-19T09:11:11Z
```
* Other relevant environment details: Container runtime, disk info, etc

Browser: __Chrome 80__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled. 

```
--e2e-testing=true
```

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by russorat** [comment]
maybe we need validation at the api to only allow values that fit this definition: https://github.com/influxdata/flux/blob/master/docs/SPEC.md#identifiers

**Comment by mark-rushakoff** [comment]
I created a variable that had a space in the name (`foo bar`), and when I clicked in the UI to use that variable, it input `v.foo bar`. I expected the UI to understand that it needed to insert `v["foo bar"]`.

**Comment by russorat** [comment]
this is the root cause of #17564 . @bthesorceror can give more details.
