### ISSUE TITLE
Links in table graphs not working correctly with highlights

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16924]
i noticed this on the Github Stats Dashboard. I couldn't click any of the links.

![Kapture 2020-02-19 at 9 14 37](https://user-images.githubusercontent.com/4805997/74857674-e4126800-52f8-11ea-8d86-59c9ce44d591.gif)

**Comment by drdelambre** [comment]
this only happens when there is a single column in the table graph. and i have no idea what chooses that formatting when it does:

![Kapture 2020-02-19 at 16 12 39](https://user-images.githubusercontent.com/1434802/74888861-18efe080-5334-11ea-8569-facfaf731fd4.gif)

**Comment by desa** [comment]
There might be dragons here
