### ISSUE TITLE
Add test coverage in httpd package for headers

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#1692]
We currently have no test coverage on the following header values from some of the httpd endpoints:

`X-InfluxDB-Version` (all end user endpoints)
`X-InfluxDB-Index` (write endpoint only)

**Comment by beckettsean** [comment]
@corylanou fix or close?

**Comment by corylanou** [comment]
Index is deprecated, but we should still add a test for the version.  Might be a good community PR as it's fairly simple.
