### ISSUE TITLE
Cloud2 UI: After upgrading/adding payment info, the website still prompts for upgrade

### ISSUE THREAD

**Issue by l85m** [influxdata/influxdb#16946]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create an account at https://cloud2.influxdata.com/
2. Upgrade / add credit card
3. View main page and billing page

__Expected behavior:__
After upgrading, the upgrade prompts go away.

__Actual behavior:__
The upgrade prompts remain both on the header:
![image](https://user-images.githubusercontent.com/858027/74923242-ba2c7480-53d0-11ea-8ac7-4edc67585e7b.png)

And on the billing page:
![image](https://user-images.githubusercontent.com/858027/74923410-07a8e180-53d1-11ea-85c8-f1c138bea36d.png)

__Environment info:__
Not applicable

__Config:__
Not applicable

**Comment by russorat** [comment]
@l85m thanks for opening this. We are working internally to fix this and will update this once we do.

**Comment by russorat** [comment]
We believe this has been addressed.
