### ISSUE TITLE
Annotations are missing in InfluxDB 2.0

### ISSUE THREAD

**Issue by afausti** [influxdata/influxdb#16954]
__Proposal:__

Add the annotations feature back in InfluxDB 2.0

__Current behavior:__

Currently, in InfluxDB 2.0 it is not possible to make annotations on charts like we use to do in Chronograf 1.x

__Desired behavior:__

It would be great to have feature parity with Chronograf 1.x. Also, an HTTP API for annotations would be very useful.

__Use case:__

I summarize here our use cases for annotations:

1. _Application monitoring_

We monitor the impact of code changes on our science quality metrics, we annotate changes on the time series when we see a metric excursion, we usually add the ticket number and some description of what happened.  

We use to say that "annotations are more important than the data".  For this use case, in particular, you can always repeat the test and reproduce the data, but the insight as to what happened, you can't necessarily remember it if the annotation is gone.

2. _Engineering Facilities Database (EFD)_

The EFD records data from our sensors at the Observatory. Annotations are useful to correlate features we observe in one chart with other charts across multiple dashboards. We control the telescope hardware from Jupyter notebooks, and currently, we can add annotations from the notebook.

Having a mechanism to turn "events" automatically into annotations would be very useful.

3. _Observer log_

This is a new use case. Astronomers working in the observatory need to log what they see in the form of comments. That's just another example of time series data, right? and if it goes to InfluxDB it would be easy to correlate with other data and display them as annotations in the UI. 

For that, an HTTP API to create annotations would be better than our current method to add annotations programmatically. We would also like to associate the current user and organization in Chronograf with the annotations automatically.

__Wish list__

Below, we list the functionalities we would like to have. We came up with this "importance scale":

0 - we cannot use InfluxDB without this feature
1 - this feature would make InfluxDB even more useful
2 - it would be nice to have
3 - not really important

_UI_

- Existing annotations functionality as in Chronograf 1.8 (0)
- Add an optional field for "comments" in addition to the annotation "name" (1)
- Color code annotations by tag (similar to "labels" in InfluxDB 2.0) (3)
- Search annotations by name (1)
- Per-user annotations. We feel that some users would like to make private annotations (2)
- Local and global annotations. By default, annotations are local, i.e. visible in the current Chronograf organization if the annotation is set as global then it is visible across all Chronograf organizations. (2)
- Display the name of the user that made the annotation, if the annotation is global display the name of the organization as well. (2)
- Associate events with point annotations. Incoming events would be automatically added as annotations. That would require a UI to select the database, measurement and field key that has the annotation name. (2)
- Allow HTML/Markdown content in the annotation name and comment (for clickable links) (1)
- Display the annotation name for multiple annotations simultaneously (2)

_HTTP API_

- Create and read annotations programmatically (1)
- Update and remove annotations (2)
- Filter annotations by tag (1)

_Othe design considerations_

- Associate the current user and organization to the annotation, perhaps as default tags? 
- If comments (see above) are stored as fields the 64KB size limit seems enough
- It should be easy to backup annotations

**Comment by afausti** [comment]
An example of how we use annotations in Chronograf 1.x. This dashboard shows functional tests of the telescope secondary mirror, this is happening this week in Chile :) 
<img width="1775" alt="Screen Shot 2020-03-06 at 8 41 33 AM" src="https://user-images.githubusercontent.com/13968086/76098867-78322f80-5f87-11ea-9c15-358c3fe127b2.png">

**Comment by afausti** [comment]
@desa nice to meet you virtually at the Town Hall today. To follow up on my question about annotations in 2.x I would like to point you to this issue where I describe our use case in more detail. Thank you!

**Comment by afausti** [comment]
We had a user session with @russorat @alexpaxton and @frossie yesterday where we discussed Annotations in 2.0. That was a really nice chat, thank you guys for organizing that. @frossie started by telling why Annotations are so important for us and how we use them. Then @russorat and @alexpaxton presented their initial porposal for adding annotations in 2.0. My take a way was that "annotations are promoted to time-series data" in 2.0.  In 1.x they were "special entities"  they were recorded in a special database (the `_chronograf` database) and followed a rigid schema.  There are clearly advantages in treating annotations as time-series data. First they can live in any bucket and instead of having a rigid schema, you can use the UI to query/transform annotations, and select the field that corresponds to the annotation "text". For each point in the result set you might construct a point annotation, but if you have a field that represents "duration" you might be able to construct annotation windows. This way one can use the existing InfluxDB HTTP API to write and query annotations. That makes total sense. We already see direct application for some of the use cases we have. For example, we have points that represent "events". Following the proposed design we could overlay those events on our time-series.  We also discussed the ability of adding annotations "manually"  when you see features in the data. That is particularly useful for us and is like we use annotations in 1.x now.

**Comment by afausti** [comment]
After realizing all that, perhaps a possible path for Annotations is to treat them as another visualization type in the UI! For example, in the Explore UI we already have the ability to overlay visualizations (the "+" button), we already have the place to write the query, and in the panel where we configure the visualization we could select the fields that represent the annotation text, the duration (for window annotations), have an option to display or hide the annotation text, select colors, etc. It feels very natural that way!

**Comment by hoorayimhelping** [comment]
finished with #20180
