### ISSUE TITLE
Keyboard shortcuts no longer work

### ISSUE THREAD

**Issue by alsargent** [influxdata/influxdb#16978]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open web UI for influxdb 2.0 beta 4. 
2. Go into an existing Dashboard
3. For one of the click on gearbox and then configure
4. Click on a line of the code in your query
5. Press ctrl-/ 
6. Note that the line of code does not turn into a comment. That's a regression bug. It worked previously, in influxdb 2.0 alpha 21.
7. Press ctrl-enter
8. Note that the query is not submitted. That's a regression. It worked previously in alpha 21

__Expected behavior:__

Toggle commenting on and off when pressing ctrl-/.

Submit query when pressing ctrl-enter.

__Actual behavior:__
Nothing happens:

Pressing ctrl-/ doesn't comment the line.

Pressing ctrl-enter doesn't submit the query.

__Environment info:__

* System info: Run `uname -srm` and copy the output here

Darwin 19.3.0 x86_64 

Aka macOS Catalina 10.15.3 (19D76)

* InfluxDB version: Run `influxd version` and copy the output here

InfluxDB 2.0.0-beta.4 (git: 3e054aaca) build_date: 2020-02-23T02:09:22Z   

* Other relevant environment details: Container runtime, disk info, etc

Browser: Firefox 73.0.1 (64-bit)

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

**Comment by Asalem1** [comment]
@alsargent, firstly thank you for the thorough issue - it's great appreciated. I'm currently trying to reproduce this issue and can't seem to reproduce part of it. 

Selecting `control + /` does not comment out the line, but `command + /` does. The `command + /` is a typical commenting command in many IDEs, so I'm not sure if it's an issue that this commands triggers a comment / uncomment  

As for pressing `control + enter`, this does seem to submit the query. I'm going to verify that this is in fact still an issue or see whether we can close this out

**Comment by FliegenKLATSCH** [comment]
@Asalem1 Does it work for you? I am also on macOS and I have a german keyboard layout, where `/` is either on numblock or on `shift+7`. Using the key on numblock nothing happens. Using `shift+7` the (macOS top menu) help menu opens.
