### ISSUE TITLE
Data explorer should "look" for the right time range when a user selects a bucket

### ISSUE THREAD

**Issue by StarpTech** [influxdata/influxdb#16977]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run `docker run --name influxdb -p 9999:9999 -p 8086:8086 quay.io/influxdb/influxdb:2.0.0-beta`
2. Open `localhost:9999`
3. Setup initial user `Name: test`, `Passsword: test1234`, `Org: test`, `Bucket: test`
3. Click on step 2 `Advanced`
4. Go to `test` bucket and click on `Add data` -> `line-protocol`
5. Add data
````
mem,host=host1 used_percent=23.43234543 1556892576842902000
cpu,host=host1 usage_user=3.8234,usage_system=4.23874 1556892726597397000
mem,host=host1 used_percent=21.83599203 1556892777007291000
````

6. I get the result `Data Written Successfully`

__Expected behavior:__
I can see my imported data in the data-explorer

__Actual behavior:__
I can't find any data in the data-explorer of my bucket `test`

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 5.3.0-40-generic x86_64
* InfluxDB version: Run `influxd version` and copy the output here
version=2.0.0-beta.4 commit=3e054aaca build_date=2020-02-22T10:28:29Z
* Other relevant environment details: Container runtime, disk info, etc
Docker version 19.03.6, build 369ce74a3c

**Comment by drdelambre** [comment]
those timestamps are around `May 03, 2019 07:09:36 GMT-0700`. If you change the time range in the data explorer to around those times, the data starts to show up.

@russorat (product): it is strange to be dropped into an invalid time range for your data right off the bat!

We'll start ruminating on that over here, but does this unblock you in the mean time?

**Comment by russorat** [comment]
@StarpTech thank your for reporting! Yes, ideally the data explorer should "look" for the right time range when a user selects a bucket. We will add this to the list of data explorer enhancements we want to make.

**Comment by StarpTech** [comment]
Hi, @drdelambre thanks for the hint. This solved all my issues. What a pity mistake.

**Comment by russorat** [comment]
@StarpTech thanks for confirming. I will leave this open so we can look into improving the data explorer experience.

**Comment by russorat** [comment]
Not the perfect solution, but we did add a noter about tags in a time range. We don't have a performant way to "guess" the time range, so i'm going to close this for now.

![image](https://user-images.githubusercontent.com/4805997/119042218-665e6180-b96c-11eb-8520-ef8fd17bd083.png)
