### ISSUE TITLE
Scatter plot dashboard cell doesn't render

### ISSUE THREAD

**Issue by alsargent** [influxdata/influxdb#16984]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a dashboard cell with the Flux code below, type = **graph**
2. Close configuration view
3. Mouse over the dashboard cell; no issues.
4. Open the configuration view
5. Change type to **scatter**
6. Close configuration view
7. Mouse over the dashboard cell; you get message _An InfluxDB error has occurred._

Here's the flux code behind that dashboard cell; it's taking data from the http telegraf plugin, hitting public aws endpoints. I'm wondering if the fact that I'm removing `_value` is an issue.

```
from(bucket: "initial")
  // Although we just want the last measurement, 
  // collect the last 60 minutes of to ensure we have something to report.
  |> range(start: -60m)
  |> filter(fn: (r) => r._measurement == "http_response")
  |> filter(fn: (r) => r.company == "Amazon")
  |> filter(fn: (r) => r.service == "AWS")
  |> filter(fn: (r) => r._field == "result_code") 
  // You need to put these filters later for some reason.
  |> filter(fn: (r) => r.subservice == "DynamoDB")
  |> filter(fn: (r) => r.region == "us-east-2")
  |> group()
  |> sort(columns: ["_time"], desc: true)
  // If the result field is success, then return "Up", else "Down".
  |> map(fn: (r) => ({
  // Create a new column called Availability.
    r with Availability: 
      if (r.result != "success" or int(v: r.status_code) >= 500) then (0)
      else (1)
    }))
   // Drop all columns except Availability and _time.
   // If we don't keep _time, we can get the message that "not latest value found".
   // If we don't drop _value, we'll display the result code (a number).
   |> keep(columns: ["Availability", "_time"])
```
__Expected behavior:__
You should be able to mouse over a scatter cell in a dashboard and not have issues.

__Actual behavior:__
The dashboard cell displays an error when you mouse over it.

![InfluxDB 2 bug - dashboard cells error out 2020-02-24 at 9 16 24 AM 3](https://user-images.githubusercontent.com/20701/75179210-6a122280-56ee-11ea-9525-93facc1d386f.png)
![InfluxDB 2 bug - dashboard cells error out 2020-02-24 at 9 16 24 AM 2](https://user-images.githubusercontent.com/20701/75179212-6d0d1300-56ee-11ea-8db1-c395657ba58f.png)
![InfluxDB 2 bug - dashboard cells error out 2020-02-24 at 9 16 24 AM](https://user-images.githubusercontent.com/20701/75179213-6da5a980-56ee-11ea-82d3-8c95f3c5b004.png)

Here's a video showing of happens:
https://www.dropbox.com/s/n7gkidfvuj3tpg3/InfluxDB%202%20bug%20-%20dashboard%20cells%20error%20out%202020-02-24%20at%209.16.24%20AM.mov?dl=0

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

uname -srm
Darwin 19.3.0 x86_64                                                                    

influxd version
InfluxDB 2.0.0-beta.4 (git: 3e054aaca) build_date: 2020-02-24T18:12:53Z                

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by cmd-influx** [comment]
![image](https://user-images.githubusercontent.com/49156476/75264200-13274e80-57bd-11ea-9b73-88142d1b6a31.png)

I have something similar.  When I touch the cells in this scatter plot, I get the error that something is wrong.  Mine can be found in tools, under "Log File Studies V1.x" and I am trying to show the four services as scatter plots over time.

**Comment by Asalem1** [comment]
This seems to be a prod issue that was introduced in the following PR:

https://github.com/influxdata/giraffe/commit/f8920cf9097a9eb21097dd72fd6a178afd0bbe1e

I still haven't managed to narrow it down, but it might have something to do with the Tooltip additions since the `ScatterHoverLayer` component makes use of it. More specifically, it looks like the issue is that the `ScatterHoverLayer` doesn't have the `lineData` property that is required for getting the correct sort order:

https://github.com/influxdata/giraffe/commit/f8920cf9097a9eb21097dd72fd6a178afd0bbe1e#diff-91b5987f198cda42b904bbfe44f6dc9fR31

A potential solution would be to refactor the implementation to consider undefined parameters

**Comment by kubark42** [comment]
I'm having this identical issue with InfluxDB 2.0 Cloud.
