### ISSUE TITLE
Cannot export template

### ISSUE THREAD

**Issue by alsargent** [influxdata/influxdb#16990]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Go into **Dashboards** screen
2. For one of the dashboards, click on **gear**, then **Export**
3. You get an error message

This video shows more:

https://www.dropbox.com/s/4hesgek83orzzd0/Bug%20-%20cannot%20export%20template%20-%20Screen%20Recording%202020-02-24%20at%202.10.38%20PM.mov?dl=0

__Expected behavior:__

Export the dashboard

__Actual behavior:__

Error message

__Environment info:__

* System info: Run `uname -srm` and copy the output here

Darwin 19.3.0 x86_64  

* InfluxDB version: Run `influxd version` and copy the output here

InfluxDB 2.0.0-beta.4 (git: 3e054aaca) build_date: 2020-02-24T22:08:07Z

**Comment by drdelambre** [comment]
this has been closed by #16949, we just haven't deployed it yet
