### ISSUE TITLE
Add the ability to configure the quoting when importing csv via the influx cli

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17007]

**Comment by sranka** [comment]
CSV format now expects RFC4180 quoting, which wraps the value between double-quotes and escapes a double-quote in the wrapped value with two double-quotes. This is already supported via the built-in https://golang.org/pkg/encoding/csv/ reader. All the tabular processors, I know, follow the RFC these days. @russorat Isn't it good enough?

Note that a separator between columns is currently customizable using an Excel-like first row "sep=;".

**Comment by russorat** [comment]
sounds good!
