### ISSUE TITLE
Add the ability to import a simple csv file via the influx cli

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17004]
#17398 introduces CSV data to `influx write` command. As a next step, we should not require (and reduce the need) to change CSV data on input.

_Enhancements in CSV data processing_ 

- `--header` option in `influx write` command let your add annotation or header rows without changing the data on input (supplied via `--file` or stdin)
   - you can supply more `--header` options, new CSV rows will be prepended in the order as they appear on the command line, you can also supply more`--file` options, files follow headers
- the header row (i.e. the row that define column names) can also define column data types when supplied as `name|datatype`; for example `cpu|tag` defines a tag column named _cpu_
  - moreover, it can also specify a default value when supplied as `name|datatype|default`; for example, `count|long|0` defines a field column named _count_ of _long_ data type that will not skip the field if a column value empty, but uses '0' as the column value
- a new `#constant` annotation adds a constant column to the data, so you can set measurement, time, field or tag of every row you import independently on the data you passed in
   - the format of a constant annotation row is `#constant,datatype,name,value`, so you specify a supported datatype, a column name, and a constant value
   - `column` can be omitted for _dateTime_ or _measurement_ columns, so the annotation can be simply `#constant,measurement,cpu`
   - note that you can add constant annotations to existing data using `--header` option of `influx write` cli
- a time column can be of `dateTime:format` datatype to use a custom _format_ to parse column values
   - the format follows the layout described in https://golang.org/pkg/time layout, for example `dateTime:2006-01-02` parses 4-digit-year , '-' , 2-digit month ,'-' , 2 digit day of the month
   - the following formats are predefined:
      - `dateTime:RFC3339` format is 2006-01-02T15:04:05Z07:00
      - `dateTime:RFC3339Nano` format is 2006-01-02T15:04:05.999999999Z07:00
      - `dateTime:number` represent UTCs time since epoch in nanoseconds
   - if the time format includes a time zone, the parsed date time respects the time zone; otherwise the timezone dependends on the presence of `#timezone` annotation; if there is no #timezone annotation, UTC is used
      - `#timezone` annotation specifies time zone using an offset , which is either `+hhmm` or `-hhmm` or `Local` to use the local/computer time zone. Examples:  _#timezone,+0100_  _#timezone -0500_ _#timezone Local_
          
- a _double_ field column can be supplied with `format` as `double:format`
   - the `format`'s first character is used to separate integer and fractional part (usually `.` or `,`), second and next format's characters (such as as `, _`) are removed  from the column value, these removed characters are usually used to visually separate large numbers into groups
   - for example a Spanish locale value `3.494.826.157,123` is of `double:,.` type; the same `double` value is  _3494826157.123_
   - _long_ or _unsignedLong_ data types also support format, everything after and including a fraction character is ignored
   - note that you have to quote column delimiters whenever they appear in a CSV column value, for example:
      - `#constant,"double:,.",myColumn,"1.234,011"`
- a _boolean_ field column can be supplied with `format` as `boolean:truthy:falsy`
   - `truthy` are `falsy` are comma-separated lists of values that are separated by `:` , they can be empty to assume other values as truthy/falsy
   - a  `boolean` without format parses columns values that start with any of _tTyY1_ as `true` values, _fFnN0_ as `false` values and fails on other values
   - a column with an empty value is excluded in the protocol line, setup `#default` annotation for such a column define default value 
   - for example `boolean:sí,yes,ja,oui,ano,да:no,nein,non,ne,нет` 
- a CSV file can start with a line `sep=;` to inform about a character that is used to separate columns in data rows, by default `,` is used as a column separator
- `--skipHeader` flag skips the first line from the input data (the last file or stdin); the optional value of this flag specifies the number of lines to remove; for example `skipHeader=2` removes the first 2 lines
- `--debug` and `--continueOnError` options help with troubleshooting of CSV conversions
   - `--debug` prints (to stderr) metadata about columns that are used to create protocol lines out of CSV data rows
   - `--skipRowOnError` prints CSV data conversion error to stderr, skips the failing row and continues with CSV processing
      - any error stops the processing without this option specified

**Comment by sranka** [comment]
@russorat @ivankudibal I updated the description herein to further specify of what I think is 'simple CSV'
