### ISSUE TITLE
Variable maps aren't working

### ISSUE THREAD

**Issue by drdelambre** [influxdata/influxdb#17026]
when you create a variable of type 'map', and you try to use it in a query (add `v.varname`, and then select which key to substitute in the dropdown on the right), it is substituting the key of the map instead of the value

**Comment by bpalani** [comment]
I have used this before and it was working before. Not really sure when it broke down.

**Comment by karel-rehor** [comment]
Noticed this when preparing automated tests for variables. 

Dashboard>Variable>Map test waiting for this to be merged.
