### ISSUE TITLE
Paused auto refresh no longer has an update button

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17037]
this is how the auto refresh dropdown on a dashboard behaved in beta-1:
![Kapture 2020-02-27 at 13 38 15](https://user-images.githubusercontent.com/4805997/75489201-a94aa880-5966-11ea-8afe-d8005fb4a92d.gif)

This is how it behaves in the latest master: 7761c99818b31bb596914a848208fb1317545957
![Kapture 2020-02-27 at 13 39 26](https://user-images.githubusercontent.com/4805997/75489233-b5cf0100-5966-11ea-944f-e6141ee96ec6.gif)

**Comment by Asalem1** [comment]
Is this issue happening only in the Dashboard Header?
