### ISSUE TITLE
Query does not update after change

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#17041]
![monaco-no-work](https://user-images.githubusercontent.com/1477539/75496161-3bf24400-5975-11ea-9927-de3f2270d15b.gif)

**Comment by desa** [comment]
![Screenshot 2020-02-27 15 29 46](https://user-images.githubusercontent.com/1477539/75496495-292c3f00-5976-11ea-9c24-8b4fd53784a9.png)

**Comment by desa** [comment]
![after-paste-no-submit](https://user-images.githubusercontent.com/1477539/75496503-347f6a80-5976-11ea-881d-b30cb4dbddbe.gif)

**Comment by drdelambre** [comment]
work around is to add a `Z` to the end of your dates

**Comment by desa** [comment]
Minimal steps to reproduce issues is pasting the following into monaco
```
import "influxdata/influxdb/monitor"

monitor.from(start: 2020-02-26T10:16:00, stop: 2020-02-26T16:15:05)
```

**Comment by drdelambre** [comment]
the order of operations was changed in #17043 to ensure that the frontend is updated even during a parsing error. should this issue be changed to reflect the lsp changes to handle the error, or would closing it out on that PR satisfy the requested changes?
