### ISSUE TITLE
InfluxDB restore error : updating metadata on influxd service failed

### ISSUE THREAD

**Issue by reyjo** [influxdata/influxdb#17054]
I am having a restore problem with InfluxDB (v 1.7.10). I did a backup on an ubuntu 18.04 machine to be able to export it to another machine with another instance of InfluxDB.

__Steps to reproduce:__
The backup process is OK using the command:

`influxd backup -portable -database db_to_backup /mnt/backup`

After that, I tried to import the database again with the command:

`influxd restore -portable -db db_to_backup -newdb db_test_import /mnt/backup`

I launched this on the same machine and also on the other machine which both have ubuntu 18.04. I get this error:

`restore: updating metadata on influxd service failed: err = read tcp 127.0.0.1:33328->127.0.0.1:8088: read: connection reset by peer, n = 16`

I also launched this restore command on an Ubuntu 16.04 machine and the restore is good.

The "ufw" is disabled and I have exactly the same Influx configuration files on all machines.

**UPDATE 1:**

It is possible to make a backup from the Ubuntu 18 and to import in Ubuntu 16. It is also possible to make a backup from the Ubuntu 16 and to import to an Ubuntu 18 but when I make a backup from the Ubuntu 18 to an Ubuntu 18 version this is where the error occurs.

__Expected behavior:__
Need to transfer an influx database from a dev server to a prod server

__Actual behavior:__
cannot transfer a backup from an Ubuntu 18 machine to another Ubuntu 18 machine

__Environment info:__
* System info: Linux 4.15.0-88-generic x86_64
* InfluxDB version: InfluxDB v1.7.10 (git: 1.7 f46f63d4e2d9684a2dd716594ab609ccd32f0a5b)
* Other relevant environment details: Ubuntu 18.04.4 LTS

**Comment by russorat** [comment]
@reyjo thanks for the issue. Since the backup works on other versions / machines of ubuntu, my initial guess is that there is some sort of firewall or port blocking happening on the ubuntu 18 machine. That's where I would dig in first.

**Comment by reyjo** [comment]
@russorat thanks for your answer. 

the firewall on my Ubuntu 18 and 16 are inactive (ufw) and my iptables accept all for test

I did a netcat on my machines and the port is open for the 8088 (backup and restore port)
`Connection to 127.0.0.1 8088 port [tcp/omniorb] succeeded!`

And all good too for the port 8086 (communication with influxdb)
`Connection to 127.0.0.1 8086 port [tcp/*] succeeded!`

So I don't understand why this is possible to make a backup under the 8088 port but impossible to restore?

**Comment by gaomin6** [comment]
i have the same problem, and now i use centos7...

**Comment by bomerzz** [comment]
Is there any work around for this? Currently facing the same issue on Ubuntu 18.04 and version 1.8.

**Comment by aerosadegh** [comment]
I have this problem too on windows 10 version.  (Influxdb 1.8.0-1)

**Comment by dajose** [comment]
I am also impacted by this, I see this on the influxdb logs when I try to apply a restore

```
ts=2020-06-29T22:31:04.780368Z lvl=info msg="failed to decode meta: proto: meta.ShardGroupInfo: illegal tag 0 (wire type 0)" log_id=0NhYk0Ol000 service=snapshot
```

**Comment by philippevidal80** [comment]
Any news on this topic? I'm facing the same issue during restore on 1.7.10 both for server container and client container (which manages restore process) in the same AKS cluster. Occasionally, restore succeeds 10% of the time, often it fails 90% of the time. I use the `-portable` option. No problem for client outside AKS cluster so far (with port-forward).

**Comment by AdrieVanDijk** [comment]
I had this error on a Raspberry Pi with Ubuntu 20.04 when I was moving the /var/lib/influxdb directory from de SD card to a USB stick. After making a backup, I stopped influxd, mounted the ext4-formatted stick on /var/lib/influxdb and started influxd again. 

Everything seemed to work fine, but when I tried to restore the backup I got the messages:
`2021/01/21 20:37:42 error updating meta: updating metadata on influxd service failed: err=read tcp 127.0.0.1:41198->127.0.0.1:8088: read: connection reset by peer, n=16`
`restore: updating metadata on influxd service failed: err=read tcp 127.0.0.1:41198->127.0.0.1:8088: read: connection reset by peer, n=16`
and in the run log:
`Jan 21 20:37:42 pi3 influxd[6161]: ts=2021-01-21T19:37:42.221194Z lvl=info msg="failed to decode meta: proto: meta.ShardGroupInfo: illegal tag 0 (wire type 0)" log_id=0Rqby49l000 service=snapshot`

The solution in my case: During formatting the stick, a directory named `lost+found` had been created on it and I thought I didn't do any harm, but after deleting it, the restore succeeded. 

Very strange that the restore gets confused by a superfluous file, I expected it would just look the data, meta and wal directories.

**Comment by lesam** [comment]
I think this is a dup of https://github.com/influxdata/influxdb/issues/9968#issuecomment-544488680, with the 'wire type 0' : `influxd[18547]: ts=2019-10-21T10:51:26.281478Z lvl=info msg="failed to decode meta: proto: meta.ShardGroupInfo: illegal tag 0 (wire type 0)" log_id=0IcUppUW00` .

After that issue was reported the snapshotter code was rewritten to be clearer not have this bug: 

https://github.com/influxdata/influxdb/pull/17495

https://github.com/influxdata/influxdb/issues/9968#issuecomment-606316990

**Comment by lesam** [comment]
#9968 is now fixed, closing.

The bug in InfluxDB depended on the chunking behaviour of network calls during the restore, so it makes sense that different OS versions could either show or not show the bug for a specific dataset.
