### ISSUE TITLE
Setup Command Cannot be Called with -f Flag

### ISSUE THREAD

**Issue by rawkode** [influxdata/influxdb#17073]
Introduced by 80751314bc98f49ce3851041975932a432e48f2b

`influx setup --org org --bucket bucket --token token --username user --password pass`

works fine and prompts for confirmation

`influx setup -f --org org --bucket bucket --token token --username user --password pass`

returns:

```
Error: The instance at "http://localhost:9999" has not been setup. Please run `influx setup` before issuing any additional commands.
See 'influx setup -h' for help
```

**Comment by rawkode** [comment]
I can confirm this is a bug with the Docker image for 2.0.0-beta

I cannot reproduce on InfluxDB master when building locally

**Comment by rawkode** [comment]
@jsteenb2 I don't know if this was recently fixed and hasn't hit the Docker image yet, or if this is a bug with "remote" InfluxDBs.

Would appreciate your guidance.

**Comment by jsteenb2** [comment]
Hmmm that's odd. WHen you are running this, is everything run inside the container, or are you hitting the docker image from your local? I didn't see a `--host` flag above 🤔

**Comment by russorat** [comment]
see also https://github.com/influxdata/influxdb/issues/16649

**Comment by jsteenb2** [comment]
@rawkode is this still an issue? Looking at the command it looks like hte issue wehre we swallowed the actual error. Here hte issue is password being to short.
