### ISSUE TITLE
PKG: Cannot 'update' bucket in OSS with 'newer' all-access token

### ISSUE THREAD

**Issue by nisley** [influxdata/influxdb#17071]
I created a new all-access token with the UI.  I used the new token with a simple yml template:
[testBucket.copy.yml.txt](https://github.com/influxdata/influxdb/files/4278447/testBucket.copy.yml.txt)

Since the bucket did not exist in OSS, when I first ran the pkg/template it DID create the bucket.
The second time I run pkg it errors with:
```
>bin/darwin/influx pkg --org-id 03ed7f40b511a000 -f ../templateExport/testBucket.yml -t "***=="
Error: Read:buckets/fea260040a1fd613 is unauthorized.
```

Curious, I tried an old all-access token from ? two months ago.  Running pkg with that token successfully runs the 'update'

**Comment by nisley** [comment]
STDOUT in terminal:

```
2020-03-02T23:28:50.122443Z	error	failed to dry run pkg	{"log_id": "0LJMteI0000", "service": "pkger", "orgID": "03ed7f40b511a000", "userID": "03ed7f40a1d1a000", "error": "read:buckets/fea260040a1fd613 is unauthorized", "took": "0.439ms"}
2020-03-02T23:28:50.122476Z	error	api error encountered	{"log_id": "0LJMteI0000", "handler": "pkger", "error": "read:buckets/fea260040a1fd613 is unauthorized"}
```

**Comment by glinton** [comment]
Can you paste the relevant output from the equivalent of 
```sh
curl https://SOMEPLACE.SOMEWHERE.cloud2.influxdata.com/api/v2/authorizations \
   -H 'cookie: session=your-session-token-from-your-cookie=='
```

There will be sensitive information (tokens) in the output, so redact as needed. Example:
```json
{
  "authorizations": [
    {
      "id": "053c445dc52b3000",
      "token": "***",
      "status": "active",
      "description": "sharedReadTokenLocalUser1",
      "permissions": [
        {
          "action": "read",
          "resource": {
            "type": "buckets",
            "id": "03cf84c6d664e000",
            "name": "Bucket",
            "org": "organization"
          }
        }
      ]
    },
    {
      "id": "053d7ca7e4cca000",
      "token": "***",
      "status": "active",
      "description": "you can read from my bucket",
      "permissions": [
        {
          "action": "read",
          "resource": {
            "type": "buckets",
            "id": "03cf84c6d664e000",
            "name": "Bucket",
            "org": "organization"
          }
        }
      ]
    }
  ]
}
```

**Comment by nisley** [comment]
This is a local temp OSS instance, so no redaction required:
[pkgTokenInvestigation.txt](https://github.com/influxdata/influxdb/files/4278728/pkgTokenInvestigation.txt)

**Comment by glinton** [comment]
Guessing which two tokens you are using, old and new, it looks like there is a difference in permissions (apart from the newer created one including checks/notifications grants).  The newer permissions are org specific to org `03ed7f40b511a000` whereas the old permissions on oss are for everything, this was likely fallout from the original pr to clean this up that also caused the all-access token issues the other day. There is also a missing write orgs permission in the new token vs one created in the past. None of this should have any affect on the original issue though, as the token you are using has permission to read buckets on the org you are using. This definitely seems like an issue deeper in the authentication layer.
```json
{
  "action": "read",
  "resource": {
    "type": "buckets",
    "orgID": "03ed7f40b511a000",
    "org": "nisley"
  }
}
```

**Comment by nisley** [comment]
New Token - l3fejkXWSe9WHf2AOKo3Z4TlYnpEkxaPc-IVbOFKEP5wjx6KRd6jTUrXLtqg6JB5sVLk3j9ZdF18PyGGOGoCiw==

Old Token that worked - zx-xrxmnD92Z6gUE-GSlIVqTV0KXxXJFO4_qPapWG-cxkVPaJJwg0A2nicJsNIrotwKPlDDnTbey1Piqof2fZQ==
