### ISSUE TITLE
Standardize influx CLI '--retention' type and accepted duration units

### ISSUE THREAD

**Issue by sanderson** [influxdata/influxdb#17107]
Right now, two `influx` commands accept a `--retention` flag when creating a bucket.

- `influx setup`
- `influx bucket create`

`influx setup`'s `--retention` flag expects an integer that represents the retention period in nanoseconds. `influx bucket create` expects a duration, but only in units up to hours.

__Proposal:__
Both commands should expect the same data type for the bucket retention period. We should also accept day and week duration units.

__Current behavior:__
Retention flags expect different input types. The one that does expect a duration value only accepts `ns`, `us`, `ms`, `s`, and `h`. 

__Desired behavior:__
Retention flags should expect the same input type. In addition to the duration units already supported, they should also support days `d`, and potentially even weeks `w`. 

__Use case:__
Better UX

**Comment by jsteenb2** [comment]
@sanderson do you have any suggestion for what the description of retention period should read? While we got the hood open...

**Comment by sanderson** [comment]
@jsteenb2 Duration bucket will retain data

**Comment by sanderson** [comment]
@jsteenb2 from `influx setup -h`:

```
-r, --retention duration   Duration bucket will retain data. 0 is infinite. Default is 0. (default -1ns)
```
Is the default for retentions `0` or `-1ns`?

**Comment by jsteenb2** [comment]
0 will default to infinite retention period
