### ISSUE TITLE
offset option in Task isn't preserving the original time range

### ISSUE THREAD

**Issue by Bharathebt** [influxdata/influxdb#17100]
I’ve created a task that will run everyday 2:00 Am which will query and give me the data from last 1 day. Also I’ve kept a 2hr offset, so Task runs at 4:00 AM instead of 2:00 AM which is right. So when task runs, I should get the data from last day 2:00 AM to current day 2:00 AM, but I’m getting data from last day 4:00 AM to current day 4:00 AM.

But as per the documentation https://v2.docs.influxdata.com/v2.0/process-data/task-options/#offset, offset doesn’t change the original time range.

This is the offset def: Delays the execution of the task but preserves the original time range. For example, if a task is to run on the hour, a 10m offset will delay it to 10 minutes after the hour, but all time ranges defined in the task are relative to the specified execution time. A common use case is offsetting execution to account for data that may arrive late.

And my Task looks similar as below:

option task = {
	name: “Task1”,
	cron: “0 2 * * *“,
	retry: 3,
	offset: 2h,
}
from(bucket: “Bucket1”)
	|> range(start: -1d, stop: 0s)
	|> to(bucket: “Bucket2")

**Comment by docmerlin** [comment]
@Bharathebt Is your data UTC time zone format?

**Comment by Bharathebt** [comment]
@docmerlin Yes, we log the data with timestamp which is UTC.
And the system timezone which sends data to influxDB is Pacific East

**Comment by Bharathebt** [comment]
Thanks, this is working now with the fix given for https://github.com/influxdata/influxdb/issues/17323
