### ISSUE TITLE
"Error exhausting result iterator" on Task

### ISSUE THREAD

**Issue by teeling** [influxdata/influxdb#17116]
I have a Task that I run to downsample data every minute. It's stock price data, so in the downsample I calculate open, high, low and close prices for the time window, as well as the sum of the volume traded.
However, any time I use the "sum" function I get an error:

`ts=2020-03-06T12:29:01.672606Z lvl=info msg="Error exhausting result iterator" log_id=0LNu1hFG000 service=task-executor error="unknown field type for volume: \u0005\ufffd3u>\ufffd\ufffdjQ9:I\u0003[\ufffd\ufffd,\u0000=tick_data,asset=8TRA.ST,\ufffd=volume volume= 1583497740000000000" name=to52`

By just changing the aggregate function from "sum" to "max" or "min" I can get the task to run, but with "sum" or even "mean" the Task fails and produces the error above in the log.

The task itself looks like this:

```
option task = {name: "tickToMinute", every: 1m}
open = from(bucket: "tickData")
	|> range(start: -10m)
	|> filter(fn: (r) => (r._measurement == "tick_data"))
	|> filter(fn: (r) => (r._field == "price"))
	|> aggregateWindow(every: 1m, fn: first)
	|> map(fn: (r) => ({r with _field: "open"}))
	|> yield(name: "first")

high = from(bucket: "tickData")
	|> range(start: -10m)
	|> filter(fn: (r) => (r._measurement == "tick_data"))
	|> filter(fn: (r) => (r._field == "price"))
	|> aggregateWindow(every: 1m, fn: max)
	|> map(fn: (r) => ({r with _field: "high"}))
	|> yield(name: "high")

low = from(bucket: "tickData")
	|> range(start: -10m)
	|> filter(fn: (r) => (r._measurement == "tick_data"))
	|> filter(fn: (r) => (r._field == "price"))
	|> aggregateWindow(every: 1m, fn: min)
	|> map(fn: (r) => ({r with _field: "low"}))
	|> yield(name: "low")

close = from(bucket: "tickData")
	|> range(start: -10m)
	|> filter(fn: (r) => (r._measurement == "tick_data"))
	|> filter(fn: (r) => (r._field == "price"))
	|> aggregateWindow(every: 1m, fn: last)
	|> map(fn: (r) => ({r with _field: "close"}))
	|> yield(name: "last")

volume = from(bucket: "tickData")
	|> range(start: -10m)
	|> filter(fn: (r) => (r._measurement == "tick_data"))
	|> filter(fn: (r) => (r._field == "volume"))
	|> aggregateWindow(every: 1m, fn: sum)
	|> map(fn: (r) => ({r with _field: "volume"}))
	|> yield(name: "volume")

union(tables: [open, high, low, close, volume])
	|> to(bucket: "minuteData", org: "myOrg")
```

Running the query in the Data explorer seems to work just fine.
Is this a bug, or am I doing something incorrectly?

**Comment by drdelambre** [comment]
since it's working in data explorer, suggesting a backend / task specific issue, i'm going to shuffle this to the compute team for a better analysis. feel free to give it back if i'm wrong!

**Comment by gueluelue** [comment]
Hey, I'm having the exact same issue and it blocks any kind of aggregation mechanism, as `sum` is quite central/default for aggregations, right? Any idea when this will be fixed? I'm happy to help out but I could use some support pointing me in the right direction.

Side question: What does the `severity/sev-3` label mean? Is 3 more severe than 4 or less?

**Comment by gueluelue** [comment]
This seems to be resolved in beta9

**Comment by gueluelue** [comment]
I finally solved this issue by getting rid of the null values that may appear when using `aggregateWindow` for timeseries that didn't produce any data point in this window. The solution that worked for me was to add 

```
	|> fill(value: 0.0)
```

After the `aggregateWindow` statement.

**Comment by aanthony1243** [comment]
sometimes a task will get back nil values periodically during off peak times, etc.  these may not be noticed during testing.  @gueluelue has the right approach.
