### ISSUE TITLE
Telegraf Config Defaults to System Bucket

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#17118]
### Problems

1. When creating a telegraf config and a bucket is available, the default selection for the bucket dropdown is defaulted to a system bucket. When I selected a bucket I've created, the system bucket is no longer available. Should system buckets be configurable with a telegraf config? 
2. Creating a telegraf config successfully generates an API token, but when selecting the `Setup Instructions` link, the token returns an `Unknown Token` message. 

![create_telegraf_bugs](https://user-images.githubusercontent.com/19984220/76101448-4c14af80-5f83-11ea-8e41-774ab4f72c9b.gif)

**Comment by russorat** [comment]
for 2, see https://github.com/influxdata/influxdb/issues/16609
