### ISSUE TITLE
Can't add threshold check in Cloud 2 where field has a space in the name

### ISSUE THREAD

**Issue by robansaldo** [influxdata/influxdb#17129]
When creating a threshold check in cloud 2, selecting a field with a space in the name prevents that check from being saved. An error message is displayed similar to:

`Failed to create check: Could not create task from check: invalid options; Err loc 20:3-20:27 expected an operator between two expressions: loc 20:3-20:27:`

The numbers referenced can vary depending on the field name selected.

**Comment by russorat** [comment]
@robansaldo thanks for opening this! We will take a look.

**Comment by desa** [comment]
I think this is likely similar to https://github.com/influxdata/influxdb/issues/15818

**Comment by Asalem1** [comment]
Quick follow-up here - this issue is specifically when creating a check and **NOT** when creating a query in the data explorer

**Comment by Asalem1** [comment]
Quick update on this. This looks like it's an issue with the way Tasks are handling Threshold Checks in particular, and not Deadman Checks. To reproduce, you can use the following line protocol to add data with a space to your Bucket:

weather,location=us-midwest tempe\ rature=82

Once that data has been inserted, you can try to create a Threshold Check with the following:

from(bucket: "Test")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
|> filter(fn: (r) => r._measurement == "weather")
|> filter(fn: (r) => r._field == "tempe rature")
|> filter(fn: (r) => r.location == "us-midwest")
|> aggregateWindow(every: 1m, fn: mean)
|> yield(name: "mean")
Creating this as a Deadman Check should be successful.
This query should be successful when written in the Data Explorer using the Query Builder & Script Editor

PROBLEM

This query is NOT successful when creating a Threshold Check

**Comment by Asalem1** [comment]
@desa let's meet tomorrow to try and verify whether this is a UI bug or not
