### ISSUE TITLE
Can't change selected field in existing monitor and alerting check on Cloud 2

### ISSUE THREAD

**Issue by robansaldo** [influxdata/influxdb#17130]
If you have an existing threshold check in cloud 2 and try to change the field filter to use a different field, the GUI displays your new choice, but the query actually has selected all the existing fields.

To reproduce, create a new alert check where there are multiple fields to select from, for example "voltage", "current" and "penguins" - pick one of those for your check (say "voltage"), set a threshold and save the check. Open the saved check, deselect "voltage" and select "penguins" instead. Submit the query and examine the raw data returned. It will contain data as if you had selected all the fields even though the GUI shows one selected. You can get around this by deselecting all the filters, picking a different bucket and then select the original bucket and add your filters anew.

**Comment by russorat** [comment]
@robansaldo thanks for this one as well!

**Comment by Asalem1** [comment]
Reopening this issue since it seems like it either:

1. Didn't resolve the issue
2. Hasn't been deployed successfully onto production

**Comment by Asalem1** [comment]
After speaking with @robansaldo on Slack, it seems like this a specific issue that could be linked to malformed data since updating a check now works when a new check is created. I'm going to mark this bug as resolved
