### ISSUE TITLE
[UI - Dashboard / Flux Query Editor] Hover variable fails to reliably fetch values in popover 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#17146]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create some variables
2. Create a dashboard and a cell with a flux query 
3. Open the Script editor to edit the query and add a variable 
4. Click the variables tab
5. Hover over a variable name

__Expected behavior:__
Expected the value dropdown to contain the values declared for the variable. 

__Actual behavior:__
There is a warning message "Failed to load."

If I click on the variable and add it to the script and then click submit, the graph disappears and is replaced by the message "No Results".

If I click submit a second time, the graph loads.  Now, when hovering over the variable, the dropdown contains values.

The values appear also once the popover is hovered.  However, for testing purposes, it would be helpful if they were fetched when the popover is generated.   

__Screencast__

![VariableDropdownValuesFailToLoad01](https://user-images.githubusercontent.com/25881301/76232807-8a31fd80-6227-11ea-911c-d454256ba899.gif)

__Related__ 
#17101 

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-88-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly builds. 
```
ts=2020-03-09T09:23:38.563108Z lvl=info msg="Welcome to InfluxDB" log_id=0LReZ3ll000 version=nightly commit=8bfe05e55 build_date=2020-03-09T09:23:38Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 80__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started withe e2e testing enabled. 

```
--e2e-testing=true
```

**Comment by drdelambre** [comment]
this is an interim state caused while fixing a bug where non map variables would crash the interface. turning all of this back on is being tracked in #17101.
