### ISSUE TITLE
storage: series file read performance opportunity

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb#17143]
From @stuartcarnie's [comment](https://github.com/influxdata/influxdb/pull/17053#discussion_r388602824):

## Performance Opportunity

I have spoken about this one before, as I've see `SeriesIDTypedBySeriesKey` come up in performance profiles.

There is a big performance opportunity here if we didn't have to make this call, which is necessary to get `id.Type()` further down.

When we fetch the series keys with the seriesCursor:

https://github.com/influxdata/influxdb/blob/1facad82dd8d14c479eeb033acf1f87f0253a6f6/storage/series_cursor.go#L47

It returns a `SeriesRow`:

https://github.com/influxdata/influxdb/blob/1facad82dd8d14c479eeb033acf1f87f0253a6f6/storage/series_cursor.go#L41-L44

Unfortunately, the `SeriesID` in `elem` here:

https://github.com/influxdata/influxdb/blob/1facad82dd8d14c479eeb033acf1f87f0253a6f6/storage/series_cursor.go#L138

Has been stripped of the type information, so we have to look it up again using the `SeriesIDTypedBySeriesKey` here. 

The win is to not strip it when returning the `sitr`:

https://github.com/influxdata/influxdb/blob/1facad82dd8d14c479eeb033acf1f87f0253a6f6/storage/series_cursor.go#L122

And storing the either the full series ID or the type in the `SeriesRow`. We are going to use this for InfluxQL too.

### Implementation

1) We should do some benchmarking to clarify how significant this performance opportunity is.

2) The series file code could be refactored to (mostly) handle `SeriesIDTyped` only.

3) That ^^ refactor runs into a problem with `SeriesIDSet`, which is used to do set operations (union, intersection, difference) between sets of series. `SeriesIDSet` depends on [RoaringBitmaps](https://github.com/roaringBitmap/roaring), whose golang implementation only supports 32 bit values. `SeriesID` (untyped) requires 32 bits, so things work fine today, but `SeriesIDTyped` needs 64 bits.

https://github.com/influxdata/influxdb/blob/8bfe05e5541bb1aa7342ac913ec41bb4e76bb30a/tsdb/series_set.go#L11-L15

[An issue exists](https://github.com/RoaringBitmap/roaring/issues/136) to add support for 64 bit values to the Golang impl. The C and Java RoaringBitmaps implementations have 64 bit support.

The Java 64 bit implementation is conceptually simple. Where the 32 bit impl is a mapping from (key) high 16 bits to (value) containers of low 16 bits, the 64 bit roaring bitmap is a mapping from (key) high 32 bits to (value) low 32 bit roaring bitmaps. There are details to solve, of course.

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java#L28-L31

### About Roaring Bitmap

An implementation of set, as in, an unordered bag of unique values. The values are 32 or 64 bit integers, usually unsigned, and the implementation includes set operations such as contains, union, intersection, etc. Roaring bitmap is special because it is (1) fast and (2) space efficient.

http://roaringbitmap.org/

Original design (two container types): https://arxiv.org/pdf/1402.6407.pdf

Improved design (add third container type): https://arxiv.org/pdf/1603.06549.pdf

**Comment by stuartcarnie** [comment]
@jacobmarble apparently I did some benchmarking for you here 🤣  #13693

**Comment by jacobmarble** [comment]
Duplicate of #13693
