### ISSUE TITLE
[UI - Cell Edit (clkfc)] Hide query icon no longer visible with multiple queries 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#17167]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a dashboard 
2. Create a Cell
3. Build a first query for the cell - submit
4. Build a second query for the cell - submit
5. Now try and hide the second query

__Expected behavior:__
Previously there was an eye-icon that could be clicked to toggle visibility of the curve created by the query.

__Actual behavior:__
The eye-icon is no longer visible.  It exists in the DOM but has dimensions 0x0. 

__Screenshot__

![HideQueryIconNotVisible01](https://user-images.githubusercontent.com/25881301/76314363-ebfd7080-62d6-11ea-9350-ffff66101e2a.png)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-88-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly builds. 
```
ts=2020-03-10T09:18:14.484272Z lvl=info msg="Welcome to InfluxDB" log_id=0LSwdiq0000 version=nightly commit=f3d871fff build_date=2020-03-10T09:18:14Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 80__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled. 
```
--e2e-testing=true
```

**Comment by drdelambre** [comment]
@alexpaxton is this expected behavior?
