### ISSUE TITLE
Confusing click actions when adding a read/write token.

### ISSUE THREAD

**Issue by lifengbo** [influxdata/influxdb#17179]
Version:  2.0.0 (2295247)

when add a read/write token, when click the button[Select All] then Save
![image](https://user-images.githubusercontent.com/7694869/76140520-5e334280-6096-11ea-836c-b0a02ba12ab6.png)
the token's  has other's buckets permissions.
![image (1)](https://user-images.githubusercontent.com/7694869/76140515-583d6180-6096-11ea-8b6b-45276ad1e0ff.png)

when add a read/write token ,click the bucket then save, the result is correct.

**Comment by desa** [comment]
I believe that this is due to system buckets.

**Comment by russorat** [comment]
The UI should be updated to reflect what is actually happening in the API call here.

So when a user selects an individual bucket, the token is given explicit access to that bucket. when a user selects all, the token is give * permissions to any bucket.
