### ISSUE TITLE
User has no tokens in new org

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#17183]
This one is confusing to me, but I'm pretty sure that user is meant to have an a token in a new org that they create (@desa could you verify? )
Creating new org creates same issue with tokens as I reported previously with dashboards. 
https://github.com/influxdata/influxdb/issues/17180
But also user actually has no tokens in new org.

**Comment by desa** [comment]
> This one is confusing to me, but I'm pretty sure that user is meant to have an a token in a new org that they create 

I don't think this is the case.
