### ISSUE TITLE
Tokens tab looks gray and blank if user has no tokens

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#17181]
![Kapture 2020-03-10 at 12 15 14](https://user-images.githubusercontent.com/10937678/76350356-d5e8b380-62c8-11ea-9a4f-a67af0d311f6.gif)

**Comment by Asalem1** [comment]
Might be a good place to integrate into the Add Graphics epic (#17152) @alexpaxton

**Comment by desa** [comment]
dupe of https://github.com/influxdata/influxdb/issues/17635
