### ISSUE TITLE
Listen for Data reports success even though no telegrafs are running and no data is written

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#17184]
To reproduce: 
Nuke your db resources. 
Create user as usual. 
Create new telegraf config (I'm trying system)
Do not start the telegraf. 
Click `Listen for Data` button.
UI reports: Connection found! [bucketname] is receiving data loud and clear!
but it isn't. 

![Kapture 2020-03-10 at 14 20 07](https://user-images.githubusercontent.com/10937678/76360640-a2168980-62da-11ea-989b-f18e357af6f5.gif)

**Comment by desa** [comment]
@ebb-tide it looks like it is writing data to the `_monitoring` bucket

**Comment by ebb-tide** [comment]
same for new org, brand new empty bucket, and selecting the new bucket to create telegraf config. 
![Kapture 2020-03-10 at 15 41 43](https://user-images.githubusercontent.com/10937678/76365918-be6bf380-62e5-11ea-9d5e-e0c1ada14e50.gif)

**Comment by desa** [comment]
seems like a bug

**Comment by ChitlangeSahas** [comment]
closed via influxdata/ui#1108
