### ISSUE TITLE
influxdb v2 binaries for Windows

### ISSUE THREAD

**Issue by adiroiban** [influxdata/influxdb#17192]
__Proposal:__
Have WIndows binaries as part of the standard release.

I have created this GitHub issue to have it for the record.

__Current behavior:__
Right now, influxdb beta only has Linux and macOS binaries.

__Desired behavior:__
It would be nice to also have Windows binary available for download as part of each future v2 release.

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
I was able to build influxdb v2 from source on Linux and the current documentation is OK.

I was not able to find documentation on how to build it on Windows, and I guess that setting up the WIndows build is a bit more complicated.

I run most of inflluxdb on Linux, but I also have a use case in which I need to run influxdb directly on Windows.

Thanks!

**Comment by russorat** [comment]
@adiroiban thank you for the issue. the current beta does not support building on windows yet, but we plan to add the option before the release a GA. It will most likely be experimental though, similar to the support for building on windows in 1.x.

**Comment by mhall119** [comment]
Accidentally grabbed this issue when assigning all the Linux packaging tasks to myself.

Something to look into is the new `winget` package manager that Microsoft released: https://docs.microsoft.com/en-us/windows/package-manager/winget/

**Comment by rawkode** [comment]
@mhall119 it's all yours :+1:

**Comment by gemron** [comment]
What is the planned release date for Windows binaries?

**Comment by doivosevic** [comment]
@russorat has there been any progress with this? You mentioned GA

**Comment by russorat** [comment]
@doivosevic thanks for asking! this is in active development. We need to extract the tooling from the influxd binaries before we can complete it though. It's blocked by https://github.com/influxdata/influxdb/issues/20855 at the moment.

**Comment by danxmoran** [comment]
An update: @lesam figured out the piece of the windows cross-build I'd been stuck on, so this isn't blocked on #20855 any longer. We're still working through some problems with Flux on Windows.

**Comment by luismedicina23** [comment]
I’ll lanch


Em seg., 22 de mar. de 2021 às 14:03, Daniel Moran ***@***.***>
escreveu:

**Comment by alexmc1510** [comment]
Hello, do you have an estimated date for Windows release? I am waiting impatiently for it.
Thanks in advance
