### ISSUE TITLE
Password Policy

### ISSUE THREAD

**Issue by rawkode** [influxdata/influxdb#17200]
I've put together a PR that proposes centralising password policy management and has set some defaults (#17199)

- Minimum length of 8 chars (unchanged)
- Minimum of 3 character classes

@docmerlin shared the NIST requirements on Slack:

https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf

With that doc saying:

> No other complexity requirements for memorized secrets SHOULD be imposed. A rationale for this is presented in Appendix A Strength of Memorized Secrets.

So it's better not to enforce minimum classes, and instead focus on larger passwords.

So a discussion around what we wish to adopt should happen here

**Comment by gunnaraasen** [comment]
I think visual feedback on password strength should be provided by default and there should be options to configure passwords policies.

However, by default, I think InfluxDB shouldn't enforce any password policy. If users wish to make crappy passwords or no password, then we should let them. Many InfluxDB instances are deployed locally or behind VPNs or internal networks where requiring a password is unnecessary.
