### ISSUE TITLE
Type error on system dashboard in algo-w branch

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#17203]
It's unclear to me what the problem is, here's the screenshot:
<img width="522" alt="Screen Shot 2020-03-11 at 10 11 25 AM" src="https://user-images.githubusercontent.com/7902964/76444191-cc228700-6380-11ea-8ff1-7ada48678f29.png">

**Comment by jlapacik** [comment]
Is `_value` a string perhaps?

**Comment by wolffcm** [comment]
Steps to reproduce:
- Start `influxd` from the `feat/use-algo-w` branch.
- From the web UI, load the default "System" dashboard
- The `System Uptime` panel seems to have a type error in its query

**Comment by wolffcm** [comment]
@jlapacik `_value` appears to be an int. Oddly if I comment out the `map`, the query can succeed.

**Comment by rockstar** [comment]
Does this query work fine run as a script, i.e. via the command line and a file? It's just running in the system dashboard that the problem exists?

**Comment by wolffcm** [comment]
@rockstar Good catch, if I run that query in the REPL, then it succeeds, so it's specific to the UI.  I wonder if the UI is altering the query somehow before it's sent to the server?
