### ISSUE TITLE
Bucket variable list doesn't refresh automatically

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/influxdb#17209]
I installed OSS 2.0, and created my initial bucket.  I then selected 'quickstart' to get the OSS 2.0 dashboards and metrics. I noticed they were reading from my initial bucket, which I didn't want. I created a new bucket and changed the scraper to write to the new bucket.  When I go into the dashboards, the bucket dropdown list won't show the new bucket. I navigated away from the page many times, even left it running overnight, and it never updated with the new bucket.  Finally, I hit reload on the dashboard page and the bucket list updated.

**Comment by hoorayimhelping** [comment]
I had trouble reproducing this

## Steps I took
1. Navigate to Load Data -> Buckets
1. Reload the page
1. Create a new bucket
1. Go to dashboards
1. View a dashboard
1. View buckets dropdown. the new bucket is there

**Comment by barbaranelson** [comment]
I reproduced it (see attached video).
1. Navigate to dashboards.
2. Select a dashboard that uses variables (e.g. the System dashboard).
3. Navigate to Load Data -> Buckets
4. Create a new bucket.
5. Go back into the System dashboard.
6. The new bucket will not appear in the dropdown list until you refresh the page.
