### ISSUE TITLE
promote chronograf migrator to CLI

### ISSUE THREAD

**Issue by immykins** [influxdata/influxdb#17221]
The chronograf migrator tool (https://github.com/influxdata/influxdb/blob/master/cmd/chronograf-migrator/main.go) isn't accessible without building the project from scratch. We should either promote it to the main CLI, or (probably better) to a separate project. The key thing is that it needs to be easy to install and use.

(Also - it could really benefit from testing)

**Comment by jademcgough** [comment]
@jsteenb2 has opinions on how to go about doing this

**Comment by russorat** [comment]
We've decided not to pursue the migrator at this time.
