### ISSUE TITLE
Long hover legends push values offscreen with no way to see them

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17227]
It's impossible to see the value of this legend since it is pushed offscreen. We need a way to limit the width of the hover legend. the styling issue is in #17226 

![image](https://user-images.githubusercontent.com/4805997/76550526-81237500-644f-11ea-9789-3dd737a0ce8e.png)

**Comment by alexpaxton** [comment]
Aren't the legend styles in Giraffe?

**Comment by desa** [comment]
Ran into this with a customer during a call.

**Comment by TCL735** [comment]
PR in Giraffe: https://github.com/influxdata/giraffe/pull/281

**Comment by TCL735** [comment]
Do we want to allow the user to persist the tooltip orientation for each cell? If so, we will need more work in the UI to complete the next step in consuming **Giraffe version 0.33.0** which has rotatable tooltips allowing for vertical tooltips.
