### ISSUE TITLE
[UI - Dashboard/Cell Editor] Variable selector value dropdown not showing values consistently 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#17223]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create variables of type CSV, MAP and Query
2. Create a Dashboard and then a cell
3. In the cell edit view open Script Editor
4. Open variables.
5. Hover over the different variables.  A popover loads with a dropdown for the variable values
6. Click on the variable values dropdown in the popover

__Expected behavior:__
Expected to see the values for the variables as they are displayed when inspecting variables in Settings > Variables 

__Actual behavior:__
In the CSV case the dropdown contains 1 item "None Selected" and no values are shown. 
In the Map case the currently selected item is "No Results", however clicking on the drop down reveals the values. 

__Screencast__

![VariableValuesOddBehaviour01](https://user-images.githubusercontent.com/25881301/76522427-df0f8700-6466-11ea-93f6-ef23d2ea945a.gif)

__Related__
#17146 
#17101 

This is similar to the closed issue #17146, in which it is mentioned that this feature was in process and being tracked from #17101 

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-88-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly builds 
```
ts=2020-03-12T09:13:10.573725Z lvl=info msg="Welcome to InfluxDB" log_id=0LVW92gG000 version=nightly commit=88a6a693f build_date=2020-03-12T09:13:10Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 80__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled 
```
--e2e-testing=true
```

**Comment by drdelambre** [comment]
closed by #17360
