### ISSUE TITLE
Flux: cannot read from csv file in OSS

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17238]
```
import "csv"

csv.from(file: "/path/to/data-file.csv")
```

```
failed to initialize execute state: filesystem service uninitialized in dependencies
```

![image](https://user-images.githubusercontent.com/4805997/76574307-1edf6a00-6479-11ea-9e82-da24da79b0f0.png)

**Comment by rickspencer3** [comment]
@adriandt thinks this is because you are still running on a server, and the server does not have access to the local file system. This would work on the REPL.

We have just added experimental support for csv.from(url: " "), perhaps that would be a better solution?

**Comment by rickspencer3** [comment]
So, I think this is by design. from() on a local file system should only work in the REPL, using Flux outside the context of InfluxDB. Within InfluxDB, we should block, access to local file system.

**Comment by russorat** [comment]
Thanks for the information. We will update the documentation to reflect these changes.
