### ISSUE TITLE
[2.x] Dashboard tooltip values shift when not all measurements share the same labels

### ISSUE THREAD

**Issue by ziebelje** [influxdata/influxdb#17253]
__Steps to reproduce:__
1. Create a bucket
2. Add various measurements to it
3. Some measurements need labels, others don't. I was using a scraper, so here's my example:
```
# HELP users_active_hour_total Total number of active users in the past hour.
# TYPE users_active_hour_total gauge
users_active_hour_total 40
# HELP api_calls_total Number of API calls made in the past hour.
# TYPE api_calls_total gauge
api_calls_total{source="app",error="false"} 1980
api_calls_total{source="app",error="true"} 6
api_calls_total{source="cron",error="false"} 704
api_calls_total{source="cron",error="true"} 11
api_calls_total{source="external",error="false"} 12
api_calls_total{source="external",error="true"} 0
```
4. Create a cell with the following query or similar.
```
from(bucket: "app")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
```

__Expected behavior:__
When selecting all of the data on a dashboard, all of the data in the tooltip should line up.

__Actual behavior:__
The labels from the measurements that did have labels got shifted up onto the labels that didn't have measurements. The colors match but the positioning does not.
![image](https://user-images.githubusercontent.com/3288812/76616821-3fe89f00-64fb-11ea-9190-3c4d0f71210e.png)

__Environment info:__

* System info: Linux 4.15.0-66-generic x86_64
* InfluxDB version: InfluxDB 2.0.0-beta.5 (git: 2295247a5) build_date: 2020-03-13T11:22:29Z

__Config:__
It's a fresh installation; haven't changed anything.

**Comment by russorat** [comment]
THis has been addressed in the latest release. please upgrade and open a new issue if this is still a problem.

**Comment by TCL735** [comment]
Yes, it was fixed here: https://github.com/influxdata/giraffe/pull/283
