### ISSUE TITLE
Ensure migrated buckets have correct retention policy

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#17257]
Currently the `influxd migrate` tool assumes all retention policies are forever, which is not the case in reality.

We should ensure the retention policy duration gets migrated too. This can be done by reading the `meta.db` file in the OSS 1.x `.influxdb/meta` directory, and checking what the retention policy values should be. Then, when creating the bucket in OSS 2.x using that value for the retention interval.

One thought is if the target bucket already exists but has a different retention period? Perhaps emit a warning or ask the operator what they want to do...

**Comment by patriczek** [comment]
Hi, are you working on this issue or can i try fix it?

**Comment by e-dard** [comment]
@patriczek please feel free to work on it! I can try and provide some guidance on this ticket if you have any questions.

**Comment by patriczek** [comment]
@e-dard i think it works properly, but i'm not sure, if i did it by proper way.
I don't know how to get properly retention policy from meta.db. For now i used code from influxdb v1 and cut code which parsing data as much as possible.
