### ISSUE TITLE
Handle fields with conflicting types when migrating 1.x data to 2.x

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#17251]
Currently the `influxd migrate` tool will fail if the 1.x data contains fields for the same series that have differing types across shards, and both those shards are migrated as part of the process.

For example, in 1.x you could have the following:

```
// shard 1
cpu,server=a value=12.2

// shard 2
cpu,server=a value=33i
```

This would be fine in 1.x but is not allowed in 2.x.

The migration process needs to be able to handle this situation.

We will update this issue when we have more concrete ideas about how we want to approach this. There are a few schools of thoughts currently:

1) we log any data that conflicts and ignore it;
2) we accept the most recent version of a field type - that is, in the example above `shard 2` would have later data than `shard 1` so we would accept that but reject the float series in `shard 1`.
3) we would attempt to do type conversions of conflicting data and fall back to (1) or (2) when that's not possible.

Tackling this issue is not easy. The tricky part is that we first migrate all TSM data, then we rebuild series afterwards (which is the stage where type conflicts would become apparent). One way to implement the ticket would be to setup a temporary series file to track the data that's migrated, and add the series keys for a file to the temporary series file before actually migrating the TSM data. That way you could interrogate errors and determine which keys and blocks need to be dealt with in the TSM file being imported.

**Comment by 8none1** [comment]
@sebito91 is this a candidate for migrate-o-tron?

**Comment by e-dard** [comment]
This is fixed since we moved back to the 1.x storage engine.
