### ISSUE TITLE
[2.x] Graph tooltip value is missing if data point exceeds Y Axis Domain

### ISSUE THREAD

**Issue by ziebelje** [influxdata/influxdb#17265]
I think this explains it well enough:

![influx](https://user-images.githubusercontent.com/3288812/76647851-f6687600-6533-11ea-9e59-2d57332bb0a8.gif)

__Environment info:__

* System info: Linux 4.15.0-66-generic x86_64
* InfluxDB version: InfluxDB 2.0.0-beta.5 (git: 2295247a5) build_date: 2020-03-13T11:22:29Z

__Config:__
It's a fresh installation; haven't changed anything.

**Comment by russorat** [comment]
@ziebelje thanks for opening. I agree the value should be shown. Is this blocking you from doing something?

**Comment by ziebelje** [comment]
Nope, just happened to notice it since I like to set a static domain for context. Not a major issue at all.

**Comment by russorat** [comment]
Thanks!

**Comment by russorat** [comment]
The legend is calculated based on the supplied domain, so values outside of the domain are excluded. This is how it has been designed. I'm going to close this for now since it was opened against a pre-release version of influx and hasn't come up for other users.
