### ISSUE TITLE
cryptic error for non unique check name

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#17267]
![Screen Shot 2020-03-13 at 2 51 01 PM](https://user-images.githubusercontent.com/1477539/76651580-0a0ae100-6522-11ea-90ea-49805438a4a3.png)

Error message should read something along the lines of `There already exists a check named "..."`

**Comment by desa** [comment]
cc @rickspencer3

**Comment by rickspencer3** [comment]
Another option would be to increment the default name, like "untiled 2" kind of thing
