### ISSUE TITLE
Telegraf configuration generator doesn't work with "system" bucket

### ISSUE THREAD

**Issue by VVilaplana** [influxdata/influxdb#17287]
Steps to reproduce:

1) I installed latest nighty build (2020/Mar/16) of influxdb2.0 (same behaviour with beta3, 4 5 and 6.
2) I run ./influxd
3) I open a browser to :9999
4) I create a user/password and an initial bucket named "system".
5) Load your data -> Telegraf -> Create configuration
6) Bucket dropdown doesn't show "system". It only shows "_tasks". If I repeat the whole process but I use "metrics", "systems", "bare" or any other name for initial bucket, the bucket name appears here.

**Comment by russorat** [comment]
@VVilaplana thanks for opening this! yes that is a bug. I was able to repro.

![Kapture 2020-03-16 at 16 18 18](https://user-images.githubusercontent.com/4805997/76807502-cc1bf000-67a1-11ea-8fc4-1fc8ddc94b95.gif)

**Comment by VVilaplana** [comment]
... so? it's been two months... any progress?

**Comment by desa** [comment]
@VVilaplana I've been unable to reproduce this issue. I believe it has been fixed. Can you confirm that you are still experiencing the issue?

**Comment by VVilaplana** [comment]
Yes.  I confirm it's fixed.  This issue can be successfully closed.
