### ISSUE TITLE
Clicking on a function inserts it directly where the cursor is, breaking the query

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17282]
in previous versions, when clicking a function in the functions list to insert it into the script, it would insert it on the next line without breaking the script. now it inserts it directly where the cursor is, breaking the script. Most likely related to https://github.com/influxdata/influxdb/pull/17028

![Kapture 2020-03-15 at 15 09 26](https://user-images.githubusercontent.com/4805997/76711674-2ac46980-66cf-11ea-86c7-c451192f1cfc.gif)

**Comment by Asalem1** [comment]
@russorat I'd argue that this isn't a regression since that's the intended functionality. Unfortunately this issue exists before the PR that was linked up since we were never determining the placement of the cursor and how it should handle function inserts

**Comment by russorat** [comment]
this is a regression. this is not intended behavior.

**Comment by russorat** [comment]
For reference:

The correct behavior in Alpha 21:
![Kapture 2020-03-17 at 10 06 44](https://user-images.githubusercontent.com/4805997/76882071-595d5400-6837-11ea-93a6-14db91a81d99.gif)

The incorrect behavior in current master:
![Kapture 2020-03-17 at 10 08 21](https://user-images.githubusercontent.com/4805997/76882114-6aa66080-6837-11ea-923a-164b7c435f0b.gif)
