### ISSUE TITLE
Infludb2 cloud - can add data to bucket but cannot see it or  query it

### ISSUE THREAD

**Issue by cshashank** [influxdata/influxdb#17322]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Log into infludb2 cloud
2. Select bucket
3. Select "+Add data"
4. Select line protocol
5. Select enter manually
6. Enter row 
        mem,host=host1 used_percent=24.43234543 1556896326' // Line protocol string
7. Click "write data"
8. Query bucket but data is not there

__Expected behavior:__
Should be able to see data

__Actual behavior:__
Cannot see  any data.

__Environment info:__
Cloud

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by Asalem1** [comment]
Good morning. That's a great question. Just so I can get a better idea of where the issue might be, when you were adding data via the line protocol, what did you have the precision set to in the dropdown? I've attached an image for context:

![Screen Shot 2020-03-18 at 06 34 04](https://user-images.githubusercontent.com/19984220/76966065-9df1f980-68e2-11ea-94ec-17911b485f37.png)

**Comment by cshashank** [comment]
Yes, that is the default.
I specifically tried with that again but still no joy

**Comment by Asalem1** [comment]
@cshashank can you try changing the `precision` to `seconds` to see if that changes the way the data is stored? Since the default is based on `nanosecond` precision,  the timestamp you provided `1556896326` would default to the earliest year possible (1970)

**Comment by russorat** [comment]
This feature would solve this: https://github.com/influxdata/influxdb/issues/15370

**Comment by cshashank** [comment]
Hello
  Thanks for your help,
  With this data
   mem,host=host1 used_percent=23.43234543 1584549864
  and precision set to 'seconds'
  I can see the data.

**Comment by Asalem1** [comment]
@cshashank if you have any more questions regarding InfluxDB feel free to join our community slack here:

https://influxcommunity.slack.com/
