### ISSUE TITLE
Loss and duplicate entries while downsampling data using influx task

### ISSUE THREAD

**Issue by Bharathebt** [influxdata/influxdb#17323]
I’ve created an influx task with for downsampling data with below configuration,
option task = {name: “Task”, cron: “0 4 * * *“, retry: 3}

This task will run everyday at 4.00 UTC timezone and downsample the last 1 day data from the source bucket to destination bucket by aggregating window of 1 hr.

But on one day(let say on 17th), the task ran almost 30min delay(aroung 4:24) than the scheduled time, because of that we lost data of previous day from 4:00 to 4:24) and also got an entry point in the destination bucket for this 30 min window data as well(since aggregate window takes _stop column time as _time column, we got entry at 4:24 UTC for the data occurred between 4:00 to 4:24).
And when the next day(let say on 18th) task ran on correct time at 4:00, data for last data(17th) 4:00 to 5:00 includes the data occurred(17th) b/w 4:00 to 4:24 also, i.e. there are two entries in destination bucket one at 17th 4:24 and at 17th 5:00, where both includes the data of 17th b/w 4:00 to 4:24.

Since this issue occurs every-time when there is a delay between scheduled time and start time of the task, how to solve the issue of 
1. losing data, 
2. prevent duplicate data
3. remove the delay between scheduled and starting time of the task.

**Comment by stuartcarnie** [comment]
@aanthony1243 this appears scheduler related

**Comment by docmerlin** [comment]
@Bharathebt can you post your query?

**Comment by aanthony1243** [comment]
It may be complicated to prevent this data loss in all cases.   Because you are aggregating 24 hours of data every 24 hours it's not possible for a task to be late without data loss.  Without knowing more about your use case I would recommend refactoring your task to run once per hour instead of once per day.

**Comment by Bharathebt** [comment]
@aanthony1243 we don't want task to be late, we scheduled the task to run at 4:00, but it's not getting started at 4:00 every-time, there is a delay between the scheduled time and started time. Because of this delay, we're losing some data and duplicating some data as mentioned above.

@docmerlin Below is the similar query, we are trying to create task.

option task = {name: "Task", cron: “0 4 * * *“, retry: 3}
from(bucket: "flowEvents")
	|> range(start: -24h, stop:now())
	|> aggregateWindow(fn: sum, every: 1h, createEmpty: false)

Issue occurs with the way aggregateWindow works. It windows the data for 1 hr and for the last window which doesn't fit into the exact 1hr window _time will be the now() timestamp. 

Let say Task ran at 4:30 despite scheduling at 4:00, then aggregate function windows the data from last day 4:30 to current day 4:30, so we loss yesterday's data which occurred between 4:00 to 4:30 and also there will be an entry for todays 4:30(now() timestamp) for the data occurred between 4:00 to 4:30. And this data can be duplicated when the next day, task ran at 4:00 i.e. this'll again pick the data occurred between today 4:00 to 5:00, where 4:00 to 4:30 data is already logged when today's task ran.

**Comment by docmerlin** [comment]
@Bharathebt 

When you run a task, the task treats now() not as when the task ran, but when it was supposed to run.

That means it should aggregate the data between 4:00 AM and 4:00 AM the next day based on your start and stop. (assuming your retention is longer than 24 hours)

If for some reason it isn't doing that then there is a bug, which we can try to fix.

**Comment by Bharathebt** [comment]
@docmerlin No, it's not taking the task schedule time, it's taking the task run time. 
And also if I manually run the task, then also now() is the current task run time and not the task scheduled time. Hence I couldn't run the task manually also.

**Comment by aanthony1243** [comment]
@nathanielc can someone on the query team look at this?  we suspect a problem with `now()` not getting the task-dependent value.

**Comment by brettbuddin** [comment]
Howdy, @Bharathebt. I've been investigating this issue. Are these tasks running on a self-hosted InfluxDB instance or are these running in InfluxData's InfluxDB Cloud offering?

We've identified an issue with `now()` being reported as the incorrect time in our cloud offering, which I'm shipping a fix for soon. However, in open-source, `now()` is reporting correctly.

**Comment by Bharathebt** [comment]
Hey @brettbuddin we're using InfluxDB Cloud.

**Comment by brettbuddin** [comment]
Oh that's great. Could you look-over your recent runs to see if the issue has been corrected on your end?

**Comment by Bharathebt** [comment]
Hey @brettbuddin I have checked the recent task runs, its working as expected for scheduled runs, i.e. now() is taking the scheduled time and not task start time.

But I've another doubt, when I run the task manually, then now() is the time when task started, is this expected? If yes, we have to make sure we don't run this task manually.

**Comment by brettbuddin** [comment]
@Bharathebt Awesome to hear about the scheduled execution of the task. For your manual task runs, that's the expected behavior, because there is no scheduler driving the execution in that case.
