### ISSUE TITLE
Remove required '@' prefix for file paths in 'influx' CLI

### ISSUE THREAD

**Issue by sanderson** [influxdata/influxdb#17356]
__Proposal:__
Remove the required `@` prefix when specifying file paths in the `influx` CLI. It breaks any shell's native tab-completion.

__Desired behavior:__
I want to be able to use my shell's native tab-completion to quickly type file paths when using the `influx` CLI.

__Use case:__
Ease of use.

**Comment by jsteenb2** [comment]
toooootally agree, we should support piping everywhere as well withou the arcane `-` requirement

**Comment by jademcgough** [comment]
As part of the story I think it's important to understand why it's designed this way and if there are any implications for changing it, because I don't have context on that right now.

**Comment by kelwang** [comment]
my guess is @ means a file to parse

**Comment by sranka** [comment]
#17398  introduces a new  --file (or -f ) flag that let the user specify the file to write

**Comment by sanderson** [comment]
@sranka does your PR only introduce it to the `write` command? This change also needs to happen with all commands that accept a file as input.:

```
influx write
influx query
influx task create
```

_There may be others_

**Comment by sranka** [comment]
Only the write command

**Comment by kelwang** [comment]
this is fixed by https://github.com/influxdata/influxdb/pull/17398

**Comment by sanderson** [comment]
@kelwang #17398 only address the `write` command. The `query` and `task create` commands still need to be updated with the `--file` flag.
