### ISSUE TITLE
Table Cell editor overlay doesn't respect cell options

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#17364]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a dashboard cell that is a `table` visualization
1. Add custom names to the columns in the `Customize` section
1. Save the cell
1. Observe the correct cell name in dashboard
1. Edit the cell again
1. Observe the incorrect cell names in the overlay

__Expected behavior:__
The custom column names are preserved

__Actual behavior:__
The custom column names are gone and the names revert back to the names in the returned data when editing.

__Environment info:__

* This was in the cloud product
* currently happening in `master`

**Comment by desa** [comment]
Looked into this a bit more and it seems like the settings are not persisted at all

**Comment by russorat** [comment]
cc @timhallinflux
