### ISSUE TITLE
Can't type in Query Builder

### ISSUE THREAD

**Issue by davidgs** [influxdata/influxdb#17372]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Using Cloud2
2. Browser is Safari
3. ...

__Expected behavior:__
Describe what you expected to happen.
Should be able to change to the query builder and type in to add/change the query

__Actual behavior:__
Describe What actually happened.

Can't type or select anything in the query builder
[Kapture 2020-03-20 at 13.55.50.mp4.zip](https://github.com/influxdata/influxdb/files/4361207/Kapture.2020-03-20.at.13.55.50.mp4.zip)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by Asalem1** [comment]
Confirmed that this bug is not occurring on Chrome or Firefox

**Comment by Asalem1** [comment]
Closing in favor of:

https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/idpe/5962
