### ISSUE TITLE
Safe Mode for Influxdb startup

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/influxdb#17375]
__Proposal:__
If the database has some overwhelming processes such as a bad task or a compaction on an over-sized bucket, it may prevent influxdb from starting up properly.  We should have a safe mode that turns off all `automatic` processes so that we can inspect the application and trouble shoot.  

__Current behavior:__
The DB, in an unstable state, will not start.  

__Desired behavior:__
the DB should create minimal state during startup so that a user can evaluate resources.

**Comment by aanthony1243** [comment]
some process we should disable: 
1.  tasks, checks, notifications
2.  compactions.

**Comment by jacobmarble** [comment]
I'm having second thoughts about compaction. "safe mode" implies that things are broke and we can fix in safe mode. I'm not sure compaction is something that breaks and fixes in this fashion. In fact, safe mode could be a good time to give space to compaction.

**Comment by aanthony1243** [comment]
@jacobmarble I think we have latitude to design this how we see fit.   My imagination is if you wrote 1BN series to a bucket that disabling compactions would give you enough time to properly delete that bucket.  I think `safe mode` would/should by default disable all automated processes.

**Comment by mark-rushakoff** [comment]
Some previous discussion of a read-only mode at https://github.com/influxdata/influxdb/issues/7737 (which was stalebotted).

**Comment by russorat** [comment]
Why wouldn't all these diagnostic functions just be available in the `influxd` command? `influxd doctor` for example? what is an example of something we need the database running in order to fix?

**Comment by brettbuddin** [comment]
Based on the discussion around this, I've introduced a `--no-tasks` flag to disable task scheduling specifically. What is everyone's thoughts on that?

**Comment by jacobmarble** [comment]
@brettbuddin sounds great. Do you have a PR?

**Comment by brettbuddin** [comment]
@jacobmarble https://github.com/influxdata/influxdb/pull/17462
