### ISSUE TITLE
Provide API's for accessing and modifying options in a Flux script

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#17386]
The packager needs to extract information from Flux script via the options. The current method for doing this is via some regexp and string concatenation see https://github.com/influxdata/influxdb/blob/2d1186a696cbfe7f9c4f9999388604ae16b40723/pkger/clone_resource.go#L905-L924 and https://github.com/influxdata/influxdb/blob/74dd8397d3abcd0bbef3113f18f77ee71ad92030/pkger/models.go#L1875-L1903 

The Flux API needs to instead provide an easy consume method for extracting options from a Flux script and modifying the options within a script.

@jsteenb2 Can you clarify how the pkger needs to modify the Flux script? Is it replacing the task name etc? Or is it more complicated than that?

DOD

* The above code consumes the new Flux API for interacting with options.

**Comment by jsteenb2** [comment]
right now I have to use it to pull out existing task options and add them back in on export. Your description feels spot on 👍

**Comment by barbaranelson** [comment]
It would be great to also be able to pull out variables.  We have use cases in the UI (for templates) where we need to know if a flux script references a variable, and the UI code is doing regex to try to figure it out.

**Comment by nathanielc** [comment]
@barbaranelson Thanks for the heads up, Can you or maybe @jsteenb2 provide some more details on that? 

Are you saying that the UI is looking for things like  this in a Flux script?

```

foo = "my stirng"
threshold = 5

data = from(bucket:"telegraf')
    |> range(start: -1d)
    |> filter(fn: (r) => r._measurement == "mem")

```

And the UI wants to know about `foo`, `threshold` and `data`? What does the UI want to know?

I think we can make this happen just looking for clarity on what is being asked.

**Comment by nathanielc** [comment]
OK I had a chat with @jsteenb2 and I have the clarity I needed.

There are two issues at play, this issue about options in tasks and another issue about variables defined via the `v` option. I have created https://github.com/influxdata/influxdb/issues/17430 for the option `v` variable API.

>  Can you clarify how the pkger needs to modify the Flux script? Is it replacing the task name etc? 

I can confirm that a method to extract the task options and then to replace then with something else is all that is needed. 

This means functions with signatures like this are a good starting point:

```
func ExtractTaskOption(script string) Options

func ReplaceTaskOptions(script string, opts Options) string
```

Where the `Options` type can be mutated as needed. As an aside the value.Object is a good candidate for implementing the Options type as it is a mutable object implementation but with a concrete type. Using a concrete type works in this case because the task option's type is known.

**Comment by nathanielc** [comment]
NOTE:

This code will necessarily consume the libflux Rust code to parse and format the code. This means we should not add this new API to a package that does not already have a dependency on libflux.

**Comment by nathanielc** [comment]
After some disucssion we have decided that options API should operate purely on the AST of the options. This means the API does not need to interact with the interpreter in anyway. This also means that the utility of putting this API inside of the Rust code is low compared to the cost of passing serialized AST across the boundary. As such we have decided it is best to implement this API directly in the languages that need to consume it, in this case Go and TypeScript.

We expect the implementation to be small and we explicitly support AST as part of the public API for Flux so it seems most natural to implement the logic that each use case needs directly in the host language.

Here is an API proposal that both implementations should follow. I'll create a separate issue for each implementation and refer back to this one.


```go
// GetOption finds and returns the AST node for the option value.
func GetOption(pkg *ast.Package, name string) (ast.Node, error)

// SetOption adds or replaces an existing option definition with the provided option node.
// The pkg AST is mutated in place.
func SetOption(pkg *ast.Package, name string, opt ast.Node) error

// DeleteOption removes an option if it exists. The pkg AST is mutated in place.
func DeleteOption(pkg *ast.Package, name string) error

// SetProperty will add or replace an existing property in an object expression with the provided value. 
// The object AST is mutated in place.
func SetProperty(obj *ast.ObjectExpression, key string, value ast.Node) error

// DeleteProperty removes a property if it exists from the object expression. The object AST is mutated in place.
func DeleteProperty(obj *ast.ObjectExpression, key string) error
```

Example usage to change the name of a task
```go

pkg, _ : = Parse(fluxSource)

taskOption, _ := GetOption(pkg, "task")
SetProperty(taskOption.(*ast.ObjectExpression), "name", ast.StringLiteral{Value:"newname"})

SetOption(pkg, "task", taskOption)

newFluxSource := Format(pkg)
```

The tasks code would also benefit from some helper methods to convert from basic values and their AST representation. This API would only need to exist on the Go side.

See https://github.com/influxdata/influxdb/issues/18834 for the TypeScript specific issue.

**Comment by nathanielc** [comment]
Heads up something similar to this already exists https://github.com/influxdata/flux/blob/master/ast/edit/option_editor.go

**Comment by aanthony1243** [comment]
Can we also have a `GetProperty(obj *ast.OjbectExpression, key) error`  function?  Perhaps I'm overthinking how complex the AST could be.

**Comment by brettbuddin** [comment]
I realize this wasn't fully cross linked. Here's how I'm doing it under a feature flag for a customer right now in production: https://github.com/influxdata/influxdb/blob/14db46c1a028255e611c82cb647c16e9f8c07b18/kv/task.go#L1769-L1800

I'm extracting the options statement and passing that into the evaluation directly. Of course any bound variables won't be covered here.
