### ISSUE TITLE
how to access influxdb2.0 use influx cli？

### ISSUE THREAD

**Issue by lddlww** [influxdata/influxdb#17393]
influx  --host ip:port
error return: Use "influx [command] --help" for more information about a command.

**Comment by sanderson** [comment]
@lddlww, when you say "access," what exactly do you mean? Do you want to query the database? Open an interactive shell (Flux REPL in 2.0)? Write to the database?

**Comment by danxmoran** [comment]
Closing this as I believe the answer is covered by existing docs & the `--help` output

**Comment by struggle-t** [comment]
Unfortunately, the Influx Shell was removed, In my opinion, this change was poorly documented. 

Now, the thousands of pages online saying 'open influx shell' are all useless for everyone on v2.x and higher. 

I recommend switching to Elasticsearch ELK monitoring for a more user-friendly monitoring solution.

**Comment by RangeOfGlitching** [comment]
Use version1.8 instead of version2.x if you want to use Influx Shell like below. 
```
$ influx
Connected to http://localhost:8086 version 1.8.10
InfluxDB shell version: 1.8.10
```
I assume Shell is different in influxdb2.0
check [2.6 cli doc](https://docs.influxdata.com/influxdb/v2.6/tools/influx-cli/)
For example, if you want to query data
```
influx query '
from(bucket: "my_bucket")
    |> range(start: 2023-01-02T08:00:00Z, stop: 2023-01-02T20:00:01Z)
'
```

**Comment by wind57** [comment]
I can't believe I am still googling how to make ONE SIMPLE query for a influxdb2 container that I run locally. To say that this si poorly documented, including this CLI, is to say the least :|

**Comment by samar40288** [comment]
with influxdb2, document is very poor.. wasted 2-3 days of my time writing from influx-java client to influxdb2. Ideally this should be decommissioned which can save developer's potential time.

**Comment by samar40288** [comment]
ya.. this is poorly written ..lot of time waste.

**Comment by birosz** [comment]
any plans on revamping the documentation? it feels like this project is drifting away from the objective reality and becoming a magic voodoo comprehensible only by its creators ....
