### ISSUE TITLE
Influx Migrate 1.x to 2.x: When the CLI options for `--db` or `--rp` are invalid, there is no error handling

### ISSUE THREAD

**Issue by stephanie-engel** [influxdata/influxdb#17407]
**Steps**
1) Setup a 1.x instance
2) Setup a 2.x instance
3) Stop both instances
4) Making sure the following command references the 2.x influxd binary (within the `influxdb` repo), run `influxd migrate --org-id {2xOrgId} --db fjshfkjsdhfkj`

**Results**
- The command will successfully run and display output similar to:
```
2020-03-24T20:33:41.395370Z	info	Resources opened	{"log_id": "0LkZrQ3l000", "service": "kvstore-bolt", "path": "/Users/sengel/.influxdbv2/influxd.bolt"}
Building TSI index
Removed existing TSI index at "/Users/sengel/.influxdbv2/engine/index"
```

**Now run the command again but, this time, with a valid database name but invalid retention policy**. 
Example:
`influxd migrate --org-id 9a487831c22a21ec --db 1xdb.autogen --rp fkldsfjsdfjsf`
- The output will also appear to be successful when it displays:
``````
2020-03-24T20:33:41.395370Z	info	Resources opened	{"log_id": "0LkZrQ3l000", "service": "kvstore-bolt", "path": "/Users/sengel/.influxdbv2/influxd.bolt"}
Building TSI index
Removed existing TSI index at "/Users/sengel/.influxdbv2/engine/index"
``````

**Expected Results:**
- The error message should be similar to the error message that displays when an invalid value is passed to `--influxdb-2x-path` (as an example): 

**Bad path entered in command:**
`influxd migrate --org-id 9a487831c22a21ec --influxdb-2x-path fsd/fs/fsdf`
**Output**:
```
2020-03-24T20:48:34.716988Z	info	Resources opened	{"log_id": "0Lk_hwbW000", "service": "kvstore-bolt", "path": "fsd/fs/fsdf/influxd.bolt"}
Error: open fsd/fs/fsdf/engine/data: no such file or directory
Usage:
  influxd migrate [flags]

Flags:
      --db string                 only import the provided 1.x database
      --dry-run                   simulate migration without running it
      --from string               earliest point to import
  -h, --help                      help for migrate
      --influxdb-1x-path string   path to 1.x InfluxDB (default "/Users/sengel/.influxdb")
      --influxdb-2x-path string   path to 2.x InfluxDB (default "/Users/sengel/.influxdbv2")
      --migrate-hot-shards        migrate all shards including hot ones. Can leave unsnapshotted data behind
      --org-id string             destination 2.x organization id (required)
      --rp string                 only import the provided 1.x retention policy. --db must be set
      --to string                 latest point to import
      --verbose                   enable verbose logging
```

**Comment by russorat** [comment]
we removed the `migrate` command from the influxd binary. https://github.com/influxdata/influxdb/pull/19004

**Comment by stephanie-engel** [comment]
Closing this issue since it is no longer relevant.
