### ISSUE TITLE
OSS 2.0 GA final packaging: GPG signing

### ISSUE THREAD

**Issue by pierwill** [influxdata/influxdb#17433]
As we approach the GA release of 2.0, we should implement GPG signing of binaries and other artifacts in the build process.

This has been mentioned before (https://github.com/influxdata/influxdb/issues/16649#issuecomment-588285349). Creating this issue to discuss and track progress.

**Comment by mark-rushakoff** [comment]
Why are we choosing GPG signing as opposed to any other method?

**Comment by pierwill** [comment]
For consistency: we use GPG to sign other binaries and provide documentation on verification.

**Comment by mhall119** [comment]
Is this issue for signing the binary executables themselves, or the linux distro packages containing them?

**Comment by rawkode** [comment]
I'd like to see us discourage the use of GPG too, in favour of something like minisign:

https://jedisct1.github.io/minisign/

**Comment by pierwill** [comment]
> Is this issue for signing the binary executables themselves, or the linux distro packages containing them?

For 2.0, I'm thinking the priority should be to make sure we're signing the binary files themselves when it goes GA. We could then tackle the Linux packages.

**Comment by pierwill** [comment]
Closing in favor of #19372.
