### ISSUE TITLE
Missing buckets after beta upgrade

### ISSUE THREAD

**Issue by lxms** [influxdata/influxdb#17441]
__Steps to reproduce:__

1. Create buckets under version prior to v2.0.0 beta 6 (preferably beta4 or beta5)
2. upgrade to beta 6
3. Log in and navigate to "Load data" > "buckets" (http:...:9999/orgs/.../load-data/buckets)

__Expected behavior:__
List of created buckets

__Actual behavior:__
- No buckets are shown
- Buckets with same name cannot be created
- Buckets are showned in "data explorer" and can be searched

__Environment info:__

* System info: Linux 4.15.0-1063-aws x86_64
* InfluxDB version: InfluxDB 2.0.0-beta.5 (git: 2295247a5) build_date: 2020-03-26T14:21:11Z (starting version). Afterwards  (acd09bf)

__Config:__
starting service with 
` /usr/local/bin/influxd --bolt-path=/data/.influxdbv2/influxd.bolt`

**Comment by desa** [comment]
@lxms Would it be possible for you to share you influxdb database?

**Comment by lxms** [comment]
Hello @desa,
unfortunately even the test data might have to many sensible information :-/.
Is there a simple way to remove data and provide you enough information about the DB?

**Comment by lxms** [comment]
@desa I think we can close this issue. We just updated to beta 7 (a3ff52d) and the buckets are now visible under "…/load-data/buckets"
