### ISSUE TITLE
"failed to initialize execute state: nil bounds passed to window" error from Flux REPL

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#17458]
When I execute this query in the Flux REPL on OSS, I get an error:
```
> from(bucket: "telegraf") 
  |> range(start: -5m) 
  |> filter(fn: (r) => r._measurement == "diskio" and r._field == "read_bytes") 
  |> window(every: 1m)
Error: failed to initialize execute state: nil bounds passed to window
```
The same query works fine in the web UI.

I think the planner tries to propagate bounds provided to `range` statically through the plan graph, and the way the REPL breaks up the query so part of it can be executed remotely is messing with this.

**Comment by jsternberg** [comment]
I probably forgot to implement the range bounds on the client version of the influxdb source. Since the REPL uses that implementation and `window()`, it messes up. We will also need to update the client to push down `window()` and `group()` calls just like it does for `filter()`.
