### ISSUE TITLE
Add thousands separators for numbers in table view

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#17456]
Currently, numbers like `1000000` display as such. Ideally, we'd be able to allow users to specify the formatting of the number to have thounand delimited commas like `1,000,000`.

**Comment by desa** [comment]
cc @rbetts

**Comment by Hallicopter** [comment]
Hi, I am new around here. This seems like an issue that I can tackle. Can anybody give me pointers to where in the code base should I look for this?

**Comment by desa** [comment]
@Hallicopter Awesome!

It's going to be in https://github.com/influxdata/influxdb/tree/master/ui/src/shared/components/tables likely in this specific file https://github.com/influxdata/influxdb/blob/master/ui/src/shared/components/tables/TableCell.tsx

Let me know if there's anything I can do to help.

**Comment by jrenee42** [comment]
for thousands:  in normal table; (don't wait for the simple table!)
see how single stat does it (be locale-aware!)
