### ISSUE TITLE
Add indexer to the tenant service

### ISSUE THREAD

**Issue by lyondhill** [influxdata/influxdb#17464]
Indexer was added to the urm service in the kv system and we need to roll it in to the tenant urm's to avoid a regression.

**Comment by GeorgeMac** [comment]
1. We need the index definition: https://github.com/influxdata/influxdb/blob/master/kv/service.go#L69-L81 the result of this is used to insert, delete and read the index.
2. Insert into index when creating a URM https://github.com/influxdata/influxdb/blob/master/kv/urm.go#L220-L223
3. Delete from index when deleting a URM https://github.com/influxdata/influxdb/blob/master/kv/urm.go#L390-L393
4. When reading by user ID walk the index https://github.com/influxdata/influxdb/blob/master/kv/urm.go#L129-L148 the visit func will get called for each thing in the index.

Finally, reading just returns nothing until https://github.com/influxdata/influxdb/blob/master/kv/service.go#L113 this option is passed to the index on creation. Or called explicitly.
