### ISSUE TITLE
Keep NSFW words out of API tokens

### ISSUE THREAD

**Issue by alsargent** [influxdata/influxdb#17503]
__Proposal:__
Please ensure that obscenities aren't in API tokens.
 
__Current behavior:__
I was on a customer call today, and his token was:

uT-kGVDuHEJ62dBi1ivXGb84HZ3gvuKLsN7FjY86kM7RqcB5dlBX__1Ts0NlJqfnkv**SUCk**K-Re81NxCufoQ8EQ==

Note the "SUCk" in the token above. We were one character away from an embarrassing situation.

__Desired behavior:__
When an API token is generated, please see if there's an embedded substring that's an offensive word. If there is, regenerate token and check again.

__Use case:__
Why is this important (helps with prioritizing requests)?

This is a classic papercut: not a huge priority but perhaps not a huge amount of time to fix, either.

**Comment by alsargent** [comment]
Adding "good first issue" tag, since it seems relatively easy to iterate through a list of NSFW words, and for each, check if it's contained in the token. Perhaps a good one for an intern to work on? Feel free to remove this tag.

**Comment by hoorayimhelping** [comment]
I removed the good first issue labels. We use those internally after prioritizing work and being sure that it's not too difficult.

**Comment by russorat** [comment]
this isn't something we are going to address.
