### ISSUE TITLE
Editor: red squigglies showing up on text from Zoom chat copy/paste, using Safari

### ISSUE THREAD

**Issue by alsargent** [influxdata/influxdb#17504]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Compose the code below (or similar) on VS Code on a Mac (Catalina):

from(bucket: "DECENTLAB")
  |> range(start: -100y)
  |> filter(fn: (r) => r._measurement == "mem")
  |> filter(fn: (r) => r.host == "host1")
  |> filter(fn: (r) => r._field == "used_percent") 

2. Copy that text, and paste into a Zoom chat window (running on Mac Catalina)
3. On another machine, running Zoom on macOS Mojave, copy the text from the Zoom window
4. In Safari (on macOS Mojave), go to cloud2.influxdata.com, log into an AWS Frankfurt account.
5. Go into the Data Explorer
6. Go into the code editor
7. Paste the text
8. You'll see red squigglies, as shown in the screenshot below:

![image (17)](https://user-images.githubusercontent.com/20701/78050337-ee307900-7330-11ea-8e09-c848759b2e86.png)

__Expected behavior:__
No red squigglies.

__Actual behavior:__
Red squigglies in the Flux code whitespace

__Environment info:__

The steps above are what I encountered when I was working with a customer. There might be some red herrings. For instance, I don't know if Mojave makes a difference or not, or if Safari makes a difference or not, or if Zoom makes a difference or not.

**Comment by rickspencer3** [comment]
@bthesorceror can you please take a look and let me know what you think?

**Comment by jademcgough** [comment]
This is almost certainly the same as #17564, and will be closed when #16921 is fixed.

**Comment by russorat** [comment]
i believe this is fixed with #16921 . Please reopen if this is still an issue.
