### ISSUE TITLE
Checks `View History` option returns `Failed to load :(` error message

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/influxdb#17516]
![Screen Shot 2020-03-31 at 12 46 15 PM](https://user-images.githubusercontent.com/35741033/78083648-ee4d6a80-736a-11ea-9819-500ec8031f1c.png)

On the Alerts page in the UI, when you click the `View History` option by an existing check, it displays the above error page. 

This was consistent for me in both tools and oss and regardless of whether the threshold check had recently succeeded or failed.

**Comment by ebb-tide** [comment]
it looks like the error is `message: "rename error: column "_check_id" doesn't exist"`

**Comment by StefanSa** [comment]
had the same problem #17569
