### ISSUE TITLE
Variables on dashboards messed up in Safari

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17513]
I'm able to reproduce on cloud2.
![image](https://user-images.githubusercontent.com/4805997/78079800-bbeb3f80-7361-11ea-8f2b-defb9169a1e6.png)

**Comment by timhallinflux** [comment]
In Cloud 2:
I have a dashboard where I defined a variable (in firefox) and then when I open the same dashboard in Safari, the variable definition does not appear AND therefore the cells which use the variable show no results. 

Firefox:
![dashb-covid-19](https://user-images.githubusercontent.com/23535264/78079959-12587e00-7362-11ea-8f12-86589361ecb4.png)

Safari:
https://files.slack.com/files-pri/T02GAR81Y-F0115NM91TP/screen_shot_2020-03-31_at_3.07.46_pm.png

**Comment by drdelambre** [comment]
two different issues here:
1) it's loading all of the variables, not just the ones you're using (what russ is seeing?)
and
2) this has to do with the way we store order. not important. finishing up tests now on this one. (for tim's problem)

**Comment by drdelambre** [comment]
@russorat im adding the filter back that limits the variables you see to the ones used in the dashboard, but does this also require a design ticket for all that.... squishing?

**Comment by timhallinflux** [comment]
In production, logged into a new account with variables embedded in a dashboard.
Receiving this error: 
![variables](https://user-images.githubusercontent.com/23535264/78176231-04ae0180-7411-11ea-99ee-fc12b6c86af0.png)

Is this issue related?

**Comment by drdelambre** [comment]
no idea what that might be..... prod works when you have no variables, and i can't get that condition to show up when i wipe the db + application cache for an OSS build, so that points to an api error. making a user in prod now....

**Comment by drdelambre** [comment]
i can't repro! can i get a console log, maybe some network requests?

**Comment by drdelambre** [comment]
turns out that there might be a state migration issue here. if we get a user experiencing this, an immediate bandaid is to have them clear their local storage.

**Comment by timhallinflux** [comment]
clearing local storage worked.

**Comment by russorat** [comment]
i'm now also seeing this issue in Chrome: 
![image](https://user-images.githubusercontent.com/4805997/78190521-02f03800-7429-11ea-9426-07bc8990a926.png)
