### ISSUE TITLE
[InfluxDB 2.0]Help me to investigate influxdb performance drop

### ISSUE THREAD

**Issue by hellvesper** [influxdata/influxdb#17526]
I have 1 bucket with 180+ measurements (currency pairs), each contains ~18M records without tags, only measurement and 8 fields like high, low, vol, sell_price etc.

InfluxDB ver. 2.0.0 beta 7 running under FreeBSD 12.1-release amd64 2vCPU 8G RAM SSD

I have simple python script which runs queries like:
```
from(bucket: "pairs")
  |> range(start: 0, stop: now())
  |> filter(fn: (r) => r._measurement == "btc_usd")
  |> last()
```

The problem is some times it goes fast form 200ms to few sec, but then it spends minutes for each query, and I don't know why. CPU using near 0% and disc I/O also with process state `uwait`.
```
[2020-04-01 13:19:21.416581] Working on table ada_btc [1/187]

Querying last record from pair ada_btc [1/187]

=== results ===

max avg   = 4.45e-06
max buy_price = 4.41e-06
max high  = 4.54e-06
max last_trade = 4.42e-06
max low   = 4.38e-06
max sell_price = 4.44e-06
max vol   = 767930.0
max vol_curr = 3.39425


[2020-04-01 13:19:24.191167] Working on table ada_eth [2/187]
...
[2020-04-01 13:19:26.636766] Working on table ada_usd [3/187]
...
[2020-04-01 13:19:32.136428] Working on table atmcash_btc [4/187]
...
[2020-04-01 13:19:32.453187] Working on table bch_btc [5/187]
...
[2020-04-01 13:23:35.534243] Working on table bch_eth [6/187]
...
[2020-04-01 13:26:41.863748] Working on table bch_eur [7/187]
...
[2020-04-01 13:26:44.044259] Working on table bch_rub [8/187]
```
<img width="1679" alt="Screenshot 2020-04-01 at 13 19 54" src="https://user-images.githubusercontent.com/2809330/78126819-c9650000-741b-11ea-9877-e3aff152484d.png">

Also it uses a huge amount of RAM which I'd like to avoid.

**Comment by russorat** [comment]
this issue was opened against a pre-release of influxdb. tons of changes to the storage engine and flux have happened since then. if this is still an issue, please open a new issue with the details.
