### ISSUE TITLE
[UI - time machine] queries failing to retrieve data 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#17536]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Flush the database so that it is in zeroed state 
2. Generate some test data
3. Sign in 
4. Open Data Explorer
5. Set time range to 30d 

__Expected behavior:__
In the past there would be a call to the organizational buckets to get measurements to list in the next panel of query builder. 

__Actual behavior:__
A call is made but the response is empty.  

The UI shows briefly a filter control and then the message. 

```
No tag keys found 
in the current time range
```
_even for a 30d time range_?

__Screencast__

![TimeMachineNotFetchingMeasurements01](https://user-images.githubusercontent.com/25881301/78161033-288b3a80-7445-11ea-84d6-d6c8c5daca34.gif)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-91-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly build docker image
```
ts=2020-04-01T07:40:49.073487Z lvl=info msg="Welcome to InfluxDB" log_id=0LuAo_CG000 version=nightly commit=91d632ea5c build_date=2020-04-01T07:40:49Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 80__

__Note on WAL check__

I dumped the contents of the wal file after generating the data an saw fragments of what was generated. 

e.g.
```
,=bar,test=generic,�=beat#!~#,c
```

So, I'm fairly certain the data was written.  The data generator has been working for months now.  

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled 
```
--e2e-testing=true
```

__Sample Network Log__
```
Request URL: http://localhost:9999/api/v2/query?orgID=42bfa52f6efd12d6
Request Method: POST
Status Code: 200 OK
Remote Address: [::1]:9999
Referrer Policy: no-referrer-when-downgrade

Response headers
Access-Control-Allow-Headers: Accept, Content-Type, Content-Length, Accept-Encoding, Authorization
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin: http://localhost:9999
Content-Type: text/csv; charset=utf-8
Date: Wed, 01 Apr 2020 15:05:32 GMT
Transfer-Encoding: chunked
Vary: Accept-Encoding

Request headers
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,cs;q=0.8,fr;q=0.7,sk;q=0.6,de;q=0.5
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 381
Content-Type: application/json
Cookie: session=g2sisE4uGMkRaW_2Bhvo_ssdBS9JSwFlQMVhA5JTxMRjEqI8ayhiATc90Pv4rxL-5pFrhNtbIg41dHR1H-NdJA==; _ga=GA1.1.1121740276.1581584697; _gcl_au=1.1.824801961.1581584698
Host: localhost:9999
Origin: http://localhost:9999
Pragma: no-cache
Referer: http://localhost:9999/orgs/42bfa52f6efd12d6/data-explorer
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.149 Chrome/80.0.3987.149 Safari/537.36

Query string parameters
orgID: 42bfa52f6efd12d6

Request Payload
{"query":"from(bucket: \"qa\")\n  |> range(start: -1h, stop: now())\n  |> filter(fn: (r) => true)\n  |> keys()\n  |> keep(columns: [\"_value\"])\n  |> distinct()\n  |> filter(fn: (r) => r._value != \"_time\" and r._value != \"_start\" and r._value !=  \"_stop\" and r._value != \"_value\")\n  |> sort()\n  |> limit(n: 200)","dialect":{"annotations":["group","datatype","default"]}}

Response (is empty):
```

**Comment by drdelambre** [comment]
we had a bug where time was defaulting to 1h windows, as you can see in the request payload. it was fixed this morning with #17528
