### ISSUE TITLE
Color Scheme starting with Red

### ISSUE THREAD

**Issue by davidgs** [influxdata/influxdb#17546]
__Proposal:__
Short summary of the feature.

It would be great to have a color scheme for graphs that *begins* with red. 

__Current behavior:__
Describe what currently happens.
None of the color schemes for graphs *begin* with red, so you can't default a graph to a red line. 

__Desired behavior:__
Describe what you want.

Being able to default a graph line to red.
__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Why is this important (helps with prioritizing requests)?
Can't color coordinate the graphs. 
![Screen Shot 2020-04-01 at 1 47 22 PM](https://user-images.githubusercontent.com/2071898/78169564-96247000-741f-11ea-9717-b7c7e7bb52d2.png)

**Comment by alexpaxton** [comment]
I made this PR to Giraffe: https://github.com/influxdata/giraffe/pull/174 which adds a handful of single-color options
