### ISSUE TITLE
check status " Failed to load :( "

### ISSUE THREAD

**Issue by StefanSa** [influxdata/influxdb#17569]
Hi there,
with Version `(3f3074e)`, i now get the following error message with check status `Failed to load :( `

**Comment by StefanSa** [comment]
short Info
after increasing  `--query-memory-bytes`, was the bug has been fixed.

**Comment by StefanSa** [comment]
seems the same problem #17594

**Comment by glinton** [comment]
@StefanSa, I'm assuming this has been resolved already. If you are able to reproduce with a build from the latest commit on master or a nightly, can you comment with steps to repro and I'll re-open this. Thanks.
