### ISSUE TITLE
Move Org Tab Items

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#17578]
In our recent round of user testing every user expected to find the items currently in the `Organization` tab to be in the user widget.

This issue **_must_** be done with https://github.com/influxdata/quartz/issues/2408

- [x] Move `members` page link into `UserWidget`
- [x] Move `about` page link into `UserWidget`
- [x] Replace all instances of `members` with `users`
- [x] Remove `Organization` item from tree nav

**Comment by russorat** [comment]
Can we also fix this issue with this work? https://github.com/influxdata/influxdb/issues/15964

**Comment by mavarius** [comment]
No, #15964 is a very different piece of work. There's similar work that needs to be done for cloud as well but we'll likely be making another version of this page in Quartz for cloud. There are designs that were created for a new version of this page.

**Comment by russorat** [comment]
ok, i'll bump the priority of #15964 separately
