### ISSUE TITLE
Scatter Plot X-axis is unreadable

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/influxdb#17585]
I've got a scatter plot which uses days as the x-axis (starting from day 0).  However, the x-axis has no controls over how many "ticks" to display.  There is no data in the (x.5) day tick, yet these are being displayed and the number of x-axis "ticks" essentially make it unreadable as a result.
![scatter-dash](https://user-images.githubusercontent.com/23535264/78301506-0699c280-74ee-11ea-9d06-e122d3c48e21.png)

In the query builder/script editor mode, the x-axis is readable, but somehow this doesn't translate to the dashboard once saved.

![scatter-config](https://user-images.githubusercontent.com/23535264/78301517-0a2d4980-74ee-11ea-9b64-38c88744ff2c.png)

**Comment by TCL735** [comment]
The spacing between ticks made an assumption that `_time` would always be on the horizontal axis and `_value` would always be on the vertical axis. In practice, either axis can be `_time` or `_value` or even both.

The spacing between ticks is subject to design considerations. So, the ultimate solution would be a feature request to allow user to control the tick generation: allow both the step (difference between each tick) and also the number of ticks marked on the axes.

As a default, we will apply minimum spacing with these rules:

- when there are less than 4 ticks:
  for each tick, spacing is one-quarter of the length of a tick
  thusly: 0.25, 0.50, 0.75 of a tick's length as spacing for 1, 2, and 3 ticks respectively
- when there are 4 to 10 ticks:
  sum of all tick lengths is shorter than total available space by at least one tick's length
-  when there are more than 10 ticks:
  for every group of up to 10 ticks there is spacing equal at least 1 tick's length
- length of a tick is:
    vertically: average of the height and width of a span that wraps the formatted last tick in the range
    horizontally: the width of a span that wraps the formatted last tick in the range
