### ISSUE TITLE
InfluxDB cloud - unable to create token with permission to delete data

### ISSUE THREAD

**Issue by shimpler** [influxdata/influxdb#17613]
I am not able to generate an all permission token (delete permission) on the InfluxDB 2.0 Cloud. If I choose generate "all access token" all seems fine but if I try to delete with that token I receive 403. If I look the permissions in detail it is only read/write. 

https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2/delete?orgID=XXXX&bucket=test

I use the token which I generated in the UI where I choose the option "generate all access token"

the request answers:
{
    "code": "forbidden",
    "message": "insufficient permissions for delete"
}

**Comment by russorat** [comment]
@shimpler thanks for the issue. Just shoot an email to support@influxdata.com and we will get it enabled for you.
