### ISSUE TITLE
Empty Run Logs looks gray

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#17635]
Related to: #17181 

Creating a task and checking the empty run logs has a grey background that's a bit too deep a contrast.

![task-background](https://user-images.githubusercontent.com/19984220/78613483-d9684f80-7820-11ea-9499-c14c60870cb7.gif)

**Comment by TCL735** [comment]
This is a clockface issue. Both the background-color and text color are the same for an empty state index body.

**Comment by alexpaxton** [comment]
https://github.com/influxdata/clockface/issues/488

**Comment by TCL735** [comment]
This is now fixed in clockface. Now waiting on a new release for the UI to consume.
