### ISSUE TITLE
[UI - Onboarding] Password length or well formed check no longer applies

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#17642]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open the onboarding page
2. Add a user name
3. Input a short initial password, e.g. 'aa' and confirm it

__Expected behavior:__
Expected to be warned about using a short or easy to guess password.  In the past the minimum length was 8 chars. 

__Actual behavior:__
The continue button is highlighted and no warning is given. 

__Screenshot__
![NoPasswordLengthCheck01](https://user-images.githubusercontent.com/25881301/78651045-0e77af00-78c0-11ea-864a-cae4dab7a173.png)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-96-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly builds
```
version=nightly commit=bd91a81123 build_date=2020-04-07T07:57:22Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 80__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
Started with end to end testing enabled. 
```
--e2e-testing=true
```

**Comment by desa** [comment]
@karel-rehor Is this a UI specific issue or does the API prevent you from being able to submit if the password is too short?

**Comment by karel-rehor** [comment]
@desa In the past, when onboarding a new user/organization, the UI checked the password length as a basic security measure.  It would reject passwords shorter than 8 characters.  This check has been turned off.  However, there is an assertion in the tests that it should occur.

**Comment by 121watts** [comment]
backend validation was removed for password length because quartz...

i've added frontend only validation.  :sad_panda:
