### ISSUE TITLE
Create Prototype build with New Flux

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#17663]
We want to rapidly prototype the new Flux syntax. For that we have used the colm project to translate the new Flux syntax to existing syntax. See for details on the new syntax and features https://github.com/influxdata/flux/pull/2617 

This is not the final implementation rather a way to prototype what using the new syntax would feel like. 

We need a build of OSS that embeds the colm program and translates Flux on the fly so users can try it out.

**Comment by adrian-thurston** [comment]
Prototype merged to master in https://github.com/influxdata/flux/pull/2744. Enabling it causes table flux to be transformed to flux in the main entry point.

Binaries available:

https://s3.amazonaws.com/dl.influxdata.com/experimental/influxd-2.0.0-tableflux.0_darwin_amd64.tar.gz
https://s3.amazonaws.com/dl.influxdata.com/experimental/influxd-2.0.0-tableflux.0_linux_amd64.tar.gz
