### ISSUE TITLE
error in task editor when using tableFind()

### ISSUE THREAD

**Issue by Bharathebt** [influxdata/influxdb#17666]
I've created a task with the below query and getting error when using tableFind().Attaching the screenshot of the error. Shouldn't be tableFind() used in task?

data = from(bucket: "flowEvents_1hr")
	|> range(start: -5h, stop: -4h)
	|> tableFind(fn: (key) => key._field == "c")

![image](https://user-images.githubusercontent.com/8435616/78757479-30ddfb00-799a-11ea-88e3-01e3d82e9f26.png)

**Comment by Bharathebt** [comment]
And since tableFind() isn't working, I've used first() / last() so that it'll give me only one table and used getRecord() to get the first record of the table, but getting error 'missing object properties'. Attaching the screenshot of the error.

![image](https://user-images.githubusercontent.com/8435616/78767065-bd42ea80-79a7-11ea-8d33-ff43a8078f72.png)


Actually, my use-case is that I've a task, which will  downsample the data to destination bucket. I need this without failure, hence I want to run this task twice a day, I need a logic such that it should check the data from destination bucket for the last 24 hr, if there is any data present then skip the processing else do the processing. 

Hence I'm trying to check whether destination bucket has data for the past 24hr. How can I achieve this?

**Comment by ddemin** [comment]
I have same problem. Is there any solution or workaround ?

**Comment by abalone23** [comment]
I only get this error in OSS 2.0.3. It works fine in InfluxDB Cloud.

**Comment by danxmoran** [comment]
The code to fix this was already in OSS, but it was hidden behind a feature flag. PR to remove the flag and make the corrected behavior the default is incoming.

**Comment by beyond-code-github** [comment]
Thanks for the update @danxmoran! If I want to enable this feature flag (I'm running the docker container) today can you tell me how would I do it?

**Comment by danxmoran** [comment]
As a CLI option you'd pass `--feature-flags simpleTaskOptionsExtraction=true`. In a `config.yml` I think it'd be:
```yaml
feature-flags:
  simpleTaskOptionsExtraction: true
```

**Comment by beyond-code-github** [comment]
Fantastic thanks, will give it a go 👍

**Comment by beyond-code-github** [comment]
@danxmoran Despite reading through https://github.com/influxdata/influxdb/pull/17851, I've not been able to get the feature flags to work. 

I am happy to open an issue, but is there anything else you would suggest I read first just to make sure I've got the correct understanding? 

Have been through

**Comment by danxmoran** [comment]
@beyond-code-github I'm honestly not that familiar with the feature-flag setup (it was added before I joined Influx, and hasn't been used heavily since). I'll poke at it myself and report back

**Comment by danxmoran** [comment]
@beyond-code-github how are you trying to pass in the flags? They seem to be working for me via CLI option:
```
# Using the 2.0.4 binary

# This server fails to save the task from the issue description
$ ./influxd

# This server allows saving the task
$ ./influxd --feature-flags simpleTaskOptionsExtraction=true
```

**Comment by beyond-code-github** [comment]
I've tried all three options... if I use the CLI:

```
docker run -d -p 8086:8086 --name influxdb2 \
	-v $PWD:/root/.influxdbv2 \
	-e INFLUXD_CONFIG_PATH=/root/.influxdbv2 \
	quay.io/influxdb/influxdb:nightly \
	influxd --feature-flags simpleTaskOptionsExtraction=true
```

`ts=2021-03-06T13:59:48.493305Z lvl=info msg="Running with feature flag overrides" log_id=0SiyEiqW000 overridesError="unsupported value type"`


If I use the config file:

```
log-level: info
feature-flags:
  simpleTaskOptionsExtraction: true
```

```ts=2021-03-06T14:05:35.489355Z lvl=error msg="Failed to configure feature flag overrides" log_id=0SiyZuzl000 error="configured overrides for non-existent flags: simpletaskoptionsextraction" overridesError="unsupported value type"

Error: configured overrides for non-existent flags: simpletaskoptionsextraction

See 'influxd -h' for help```


Using the environment variable:

```docker run -d -p 8086:8086 --name influxdb2 \
        -v $PWD:/root/.influxdbv2 \
        -e INFLUXD_FEATURE_FLAGS="{\"simpleTaskOptionsExtraction\": true}" \
        quay.io/influxdb/influxdb:nightly```

No error messages but not discernable effect, task creation still fails.

In the first and third cases, if I GET http://localhost:8086/api/v2/flags then the output is:

`{"appMetrics":false,"bandPlotType":false,"communityTemplates":true,"frontendExample":42,"mosaicGraphType":false,"notebooks":false,"timeFilterFlags":false}`

In the second case the service fails to start.

**Comment by danxmoran** [comment]
The feature flag will be removed in 2.0.5, and the behavior it was guarding will be the default
