### ISSUE TITLE
Can't drop measurement as though user has all privileges on database

### ISSUE THREAD

**Issue by lafrech** [influxdata/influxdb#17671]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

- Create user myuser
- Create database mydb
- Grant all privileges to myuser on mydb
- Push data to mymeasurement in mydb
- Log in CLI, auth as myuser
- Drop measurement mymeasurement

__Expected behavior:__
Measurement dropped.

__Actual behavior:__

    ERR: error authorizing query: myuser not authorized to execute statement 'DROP MEASUREMENT "mymeasurement"', requires admin privilege

__Environment info:__
* Linux 4.19.0-8-amd64 x86_64
* InfluxDB v1.7.10 (git: 1.7 f46f63d4e2d9684a2dd716594ab609ccd32f0a5b)

**Comment by Igor-Toropov** [comment]
According to https://docs.influxdata.com/influxdb/v1.7/administration/authentication_and_authorization/#user-types-and-privileges
DROP MEASUREMENT is only allowed for admin users.
Granting ALL permissions only grants READ and WRITE.

There is a workaround to drop data for all series one by one which will effectively result in measurement being dropped when last data point in the last series is deleted.

**Comment by lafrech** [comment]
Thanks for the pointer and the workaround.

Seems strange to me, but that's the way it is, I guess. Maybe it's obvious for someone more familiar with the auth management in InfluxDB.

Sorry for the noise.
