### ISSUE TITLE
Add InfluxDB v2 to Homebrew

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17673]
once we go GA, we need to publish the new binaries to Homebrew for mac users.

We may need to update this as well: https://github.com/Homebrew/homebrew-core/blob/master/Formula/influxdb.rb

**Comment by alsargent** [comment]
This issue might have been a "nice to have" in April 2020 when it was first filed. However, in December '20, now that OSS 2.0 is GA, it can start to cause problems. People generally assume that Homebrew installs the latest GA version of a piece of software, which is not the case here.

`brew install influxdb` installs influxdb-1.8.3

![image](https://user-images.githubusercontent.com/20701/102643306-e8bfcc80-4113-11eb-8ebe-3ffba528f8a8.png)

**Comment by danxmoran** [comment]
One of the Homebrew maintainers started a PR (homebrew/homebrew-core#66837). I added some comments about V1/V2 compatibility and the upgrade process, will keep an eye on it.

**Comment by russorat** [comment]
this is completed.
