### ISSUE TITLE
All queries running out of memory

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17696]
I pulled the latest master, and dashboards that used to work.

336644a

![image](https://user-images.githubusercontent.com/4805997/78934520-ede65b00-7a5f-11ea-9293-16554d5e4067.png)

**Comment by wolffcm** [comment]
Seems to be a result of this PR: https://github.com/influxdata/influxdb/commit/13fc4f335deb419473d6a54b7d740a6bea87c3d8

There used to be no per-query memory limit in OSS, now it's 10MB.

@affo Any reason not to put it back to no limit, or raise it to something higher?

**Comment by russorat** [comment]
connect https://github.com/influxdata/influxdb/issues/17594

**Comment by russorat** [comment]
I didn't realize there were new CLI options to configure those. 

I definitely think 10MB for OSS users is too low. but hard to say what the right number is tbh.

**Comment by russorat** [comment]
Let's set these limits to unlimited by default for OSS.

**Comment by russorat** [comment]
closed by https://github.com/influxdata/influxdb/pull/17706
