### ISSUE TITLE
"credentials" file seems to not work; File is removed after use?

### ISSUE THREAD

**Issue by sgnl** [influxdata/influxdb#17693]
While I was trying to export a dashboard from my local Influxdb instance, I encountered an issue with the TOKEN and authentication.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Have an instance of InfluxDB running locally and all set-up
1. Generate a new token
1. Create a dashboard (I was trying to export a dashboard when I encountered this issue)
1. Create a file at `~/.influxdbv2/credentials`
1. In that new file, add `export INFLUX_TOKEN=oOooYourAuthTokenOoooOoOO==` and replace `oOooYourAuthTokenOoooOoOO==` with your token
1. Open a terminal and run the command `influx pkg export all -o [organization name here]`

__Expected behavior:__
I expected to connect to my influx instance without using the `-t` flag

__Actual behavior:__
I get an error log on the db server that says:

`2020-04-09T02:12:09.840928Z	info	Unauthorized	{"log_id": "0M37Sdzl000", "error": "authorization not found"}`

I also notice that the file, `~/.influxdbv2/credentials`, was removed from my system. Not sure if this is intended but it wasn't mentioned in the documentation.

__Environment info:__

* System info: Darwin 18.7.0 x86_64
* InfluxDB version: InfluxDB 2.0.0-beta.7 (git: a3ff52d13) build_date: 2020-04-09T09:39:39Z

__Config:__
The dashboard I was working on: https://github.com/influxdata/community-templates/pull/51

__Logs:__
`2020-04-09T02:12:09.840928Z	info	Unauthorized	{"log_id": "0M37Sdzl000", "error": "authorization not found"}`

**Comment by russorat** [comment]
@sgnl thanks for this! the `credentials` file has been replaced with profiles in the cli. https://v2.docs.influxdata.com/v2.0/reference/cli/influx/config/

the creds file should be automatically converted to a profile, but if not, you can create one.

**Comment by timhallinflux** [comment]
the new config setup via the CLI is the way to go here for sure.  let us know how this works for you!

**Comment by russorat** [comment]
This was opened against a pre-release version of influx. if this is still a problem, please open a new issue with the details.
