### ISSUE TITLE
numeric values should be "trimmed" before conversion when importing CSV

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17699]
trying to load a file and I get the error:

`Error: failed: line 41203: column 'duration_sec': strconv.ParseFloat: parsing "2631600  ": invalid syntax`

csv files are pretty messy, so we might just want to trim the string values before trying to convert them to a numeric type.

**Comment by sranka** [comment]
Can you pls also share the CSV data? I could take it as an example for a unit test.

**Comment by russorat** [comment]
Sure!

`influx write -f /Users/rsavage/Downloads/ufo-sightings/error_on_line_31.csv --skipHeader=1 --header "#constant measurement,ufos" --header "t|dateTime:1/2/2006 15:04,city|tag,state|tag,country|tag,shape|tag,duration_sec|double,duration_str|string,comments|string,date_posted|ignored,latitude|double,longitude|double" -b ufo_data`

[error_on_line_31.csv.zip](https://github.com/influxdata/influxdb/files/4458849/error_on_line_31.csv.zip)

**Comment by sranka** [comment]
The code that originally fixed the issue (4f1d20b) is now part of pkg/csv2lp library, the functionality is validated by a unit test in https://github.com/influxdata/influxdb/blob/master/pkg/csv2lp/data_conversion_test.go#L255 .
