### ISSUE TITLE
Table cells not exported/imported correctly in Packager

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17708]
This is the view of the dashboard before I exported it. Notice all the Table cells have two columns:
![image](https://user-images.githubusercontent.com/4805997/79021115-92839e00-7b2f-11ea-9af5-f06e50552a3e.png)

This is the file what was created when i called `influx pkg export --dashboard id`:
https://raw.githubusercontent.com/russorat/community-templates/master/ufo-sightings/ufo_data.yml

When i imported the dashboard, all the table cells only showed a single column.
![image](https://user-images.githubusercontent.com/4805997/79021083-7aac1a00-7b2f-11ea-8d19-b3d2f5df8ce0.png)

**Comment by jsteenb2** [comment]
@russorat can you provide the raw data for this dashboard?

**Comment by russorat** [comment]
[2020-04-11-13-42_chronograf_data.csv.zip](https://github.com/influxdata/influxdb/files/4465381/2020-04-11-13-42_chronograf_data.csv.zip)

**Comment by jsteenb2** [comment]
@russorat I was asking for the json payload of the dashboard the UI retrieved in that first picture 😬
