### ISSUE TITLE
UI crash when editig notification rule condition "When status changes from"

### ISSUE THREAD

**Issue by mellanon** [influxdata/influxdb#17718]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open an existing Notification Rule ("Edit this Notification Rule")
2. Click on the drop down to change from "is equal to" to "changes from"
3. Status is set to OK

__Expected behavior:__
Drop-down menu to change from is equal to to changes from

__Actual behavior:__
The UI crash and asks me to log a bug.
Creating a new rule works using the changes from condition.

__Environment info:__
I'm running the quay.io/influxdb/influxdb:2.0.0-beta released 2 days ago.

* System info: Linux 4.15.0-1054-aws x86_64
* InfluxDB version: InfluxDB 2.0.0-beta.8 (git: 41a23242ea) build_date: 2020-04-13T04:22:13Z

**Comment by Asalem1** [comment]
I can't seem to reproduce this. @mellanon can you confirm that this is still an issue? If not I'll go ahead and close it
