### ISSUE TITLE
UI: Check threshold == 0 impossible

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb#17729]
### Problem
Create a check.
Set the threshold to "is above 0"
Click the green checkbox.
Wait "schedule every".
Notice that the check has warning "Last run status: Completed(failed)".
Open check.
Notice that the threshold is empy.

### Workaround
Set the threshold to 0.00001.
Save the check.
Wait "schedule every".
Warning clears, threshold not empty.

### Also
It would be nice to have more info than "Completed(failed)". I don't know why it failed.

**Comment by karel-rehor** [comment]
Noticed as well cannot set threshold === n.  Have a local craps simulator and wanted to be warned on roll===7.  Keep me posted.
