### ISSUE TITLE
Cannot Save Custom Alerts/Querys

### ISSUE THREAD

**Issue by Ayrdrie** [influxdata/influxdb#17749]
The SRE team is asking each team to move their alerts to the tools instance.  With my experience I've learned that custom alerts can't be saved, I think having that capability would be extremely helpful for many teams since I know many of my own alerts needed customization. 

Right now a few people are writing tasks to work around the issue because those can be customized.  However, I think being able to use the full functionality of alerts would be a better use of our product. 

When I click the checkmark to save an alert after editing it in the `custom check query` page this message shows 
<img width="359" alt="Screen Shot 2020-04-07 at 4 03 37 PM" src="https://user-images.githubusercontent.com/29029574/79314223-56956380-7eb6-11ea-8cb0-95c630314b47.png">
 and the edits to the custom alert fail to save.  I know that my alert works because if I save it without ever entering into the `custom check query` feature It saves and alerts just fine.  But if I make no changes and try to save it through the `custom check query` it doesn't work and I see the above error.  

Here is an example of an alert that works and has the ID defined but cannot be edited for customizations. 
``` 
package main
import "influxdata/influxdb/monitor"
import "experimental"
import "influxdata/influxdb/v1"

check = {
  _check_id: "05710fd46ea78000",
  _check_name: "kube-scheduler",
  _type: "custom",
  tags: {owner: "team-sre"},
  every: 10m
}

option task = {
  name: "kube-scheduler",
  every: 10m, // expected to match check.every
  offset: 10s
}

crit = (r) => (r.dead)

messageFn = (r) =>("Deadman: ${ r._check_name } is: ${ r._level }  
env:${r.env} | ns: ${r.namespace} | pod:${r.pod} | node:${r.nodename}

This indicates that no data has been returned from a `kube_scheduler` pod in 10 minutes. 

This pod should be investigated and documented here: URL

Test: no result in ${ r._value} |  ${string(v: r._value)} | ${ r.value} minutes
")

data = from(bucket: "infra")
  |> range(start: -25m)
  |> filter(fn: (r) => r._measurement == "kube_pod_status_phase")
  |> filter(fn: (r) => r.phase == "Running")
  |> filter(fn: (r) => r.namespace == "kube-system")
  |> filter(fn: (r) => r.pod == "kube-scheduler-ip-180-12-0-57.ec2.internal")
  |> filter(fn: (r) => r._field == "gauge")

data
  |> v1.fieldsAsCols()
  |> monitor.deadman(t: experimental.subDuration(from: now(), d: 10m))
  |> monitor.check(data: check, messageFn: messageFn,crit:crit)
```

**Comment by Ayrdrie** [comment]
With the above alert it would be helpful to change the line to filter for non-specific pods like 
```|> filter(fn: (r) => r.pod =~ /kube-scheduler-ip/)``` But I can't do that without customization.

**Comment by tkyocum** [comment]
Hey @desa and perhaps @russorat or @mnorriswalker, would it be helpful to do a quick zoom with Air to see what we're trying to do? It seems like we are trying to set up relatively straightforward customized alerts, but it's not translating well from a user experience level. 

This might be a good time to get some usability feedback since this type of alerting is a really common use case.

If anyone mentioned here would be interested in a quick zoom to see what we're trying to do and offer help/alternatives/get some real-world feedback I'm very happy to set it up - please chime in?

**Comment by desa** [comment]
@tkyocum yup. I think that would be good. I'll put this on our backlog and get some time for us to talk scheduled.
