### ISSUE TITLE
Syntax highlighting broken when comment is on same line as a regular expression literal

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#17755]
![Screen Shot 2020-04-15 at 11 41 02 AM](https://user-images.githubusercontent.com/290647/79375849-25488200-7f0e-11ea-9a66-69eda2deb3d5.png)

The query containing this snippet executes fine, but the syntax highlighting appears to break when there is a regular expression literal.

**Comment by russorat** [comment]
I'm also seeing this highlighting issue:

![image](https://user-images.githubusercontent.com/4805997/80824929-3b07a980-8b94-11ea-83b9-272cf5b248b6.png)

```
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart)
  |> filter(fn: (r) => r["_field"] =~ /time_(user|idle|nice|system)/)
  |> filter(fn: (r) => r["cpu"] =~ /cpu[0-9]+/)
  |> last()
  |> drop(columns: ["_start", "_stop"])
```
