### ISSUE TITLE
Org members don't have permissions? / Weird HTTP codes

### ISSUE THREAD

**Issue by DSpeichert** [influxdata/influxdb#17780]
Organization members added via influx CLI can't create dashboards or tasks.
There does not seem to be any way to give them any permissions, at least not one I could find.
The permission errors aren't handled by UI and 401/500 response codes are used where 403 should be used.

__Steps to reproduce:__
1. Add a user to the org
2. Use it

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Creating new dashboard:

> write:orgs/9cf4d69e26ee2d4b/dashboards is unauthorized

Sent with 401 response code (should be 403).
UI does not show this error, it shows generic "failed to create dashboard"

Creating new task:
> failed to create task: unauthorize

UI actually shows this.
Sent with HTTP 500 internal error code.

__Environment info:__

* System info: N/A
* InfluxDB version: InfluxDB 2.0.0-beta.7 (git: a3ff52d13) build_date: 2020-04-17T02:48:09Z
* Other relevant environment details: Official docker image

**Comment by russorat** [comment]
@DSpeichert thanks for this issue. 

There are two types of users in OSS, an Owner (admin, full perms) and a Member (read only perms). To add a new user to the system, you need to follow these steps:

1. Add the new user using either the api or the `influx user create` command in the cli
2. Add that user as an Owner or a Member to your organization. We have [an issue](https://github.com/influxdata/influxdb/issues/17996) to make this easier, but the best way is to use the API.  To add as an owner: https://v2.docs.influxdata.com/v2.0/api/#operation/PostOrgsIDOwners or to add as a member: https://v2.docs.influxdata.com/v2.0/api/#operation/PostOrgsIDMembers

**Comment by russorat** [comment]
Closing this as i assume the commands given worked.

**Comment by Harleyzheng** [comment]
Sorry to comment on this closed issue. I encountered the same issue but the API `https://v2.docs.influxdata.com/v2.0/api/#operation/PostOrgsIDOwners` don't seem to work for me. I've tried to call POST `localhost:8086/api/v2/orgs/${orgId}/owners` to add new owners. I provided a new 16 Bytes ID and a new username. But the responses are always stuck in the following three error messages. 

```
Request Body
{
     "name": "cw", "id": "0945ssssccccvvvv"
}

Response
{
	"code": "invalid",
	"message": "invalid ID"
}
```
or 
```
Request Body
{
     "name": "cw", "id": "0946c8eae7947999"
}

Response
{
	"code": "not found",
	"message": "user not found"
}
```
or when I provided an existing user:
```
Request Body
   --data '{
     "name": "cw", "id": "0946c8eae7947000"
}'

Response
{
	"code": "internal error",
	"message": "Unexpected error when assigning user to a resource: mapping for user 0946c8eae7947000 already exists"
}
```

Can someone validate that `https://v2.docs.influxdata.com/v2.0/api/#operation/PostOrgsIDOwners` actually works?

**Comment by Harleyzheng** [comment]
@russorat @DSpeichert sorry to at you here again in case this is missed.

**Comment by James-O2** [comment]
was able to get this to work by removing the user as a member THEN adding as an owner
