### ISSUE TITLE
Adding a new Query to a new dashboard cell fails

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#17787]
__Steps to reproduce:__
1. go to explore
1. reload the page **this is critical**
1. create a new query
1. save the query to a dashboard and create a new cell
1. failure, undefined variables

**Comment by desa** [comment]
Note that this does not always happen, but does with some amount of regularity.
The error seen is 
```
cellGetters.ts:61 Uncaught (in promise) TypeError: Cannot read property 'w' of undefined
    at cellGetters.ts:61
    at Array.map (<anonymous>)
    at cellGetters.ts:61
    at thunks.ts:96
    at Object.dispatch (index.js:8)
    at dispatch (<anonymous>:1:28545)
    at redux.js:449
    at SaveAsCellForm.tsx:192
    at Array.forEach (<anonymous>)
    at handleSubmit (SaveAsCellForm.tsx:185)
```

**Comment by hoorayimhelping** [comment]
https://github.com/influxdata/influxdb/blob/master/ui/src/dashboards/utils/cellGetters.ts#L53-L59

`cells` is passing the `cells.length` check because it's an array of `undefined`:

```
[undefined, undefined]
```
