### ISSUE TITLE
[v2.0] Telegraf configs created without input plugins

### ISSUE THREAD

**Issue by saiyam1814** [influxdata/influxdb#17795]
__Steps to reproduce:__
Run influx 2.0 using docker command 

`docker run --name influxdb -p 9999:9999 quay.io/influxdb/influxdb:2.0.0-beta`

Go to Telegraf > create configuration > select kubernetes > continue > create and verify 
Paste the token and then try to tun telegraf --config  file generated 
you would see the error :
`2020-04-20T06:21:35Z I! Starting Telegraf 1.14.1
2020-04-20T06:21:35Z E! [telegraf] Error running agent: Error: no inputs found, did you provide a valid config file?`

__Expected behavior:__
having kuberentes input plugin in the config file generated
__Actual behavior:__
the config file generated without any input plugin and same behaviour for Docker as well
__Environment info:__
* InfluxDB version: 2.0 Beta

**Comment by desa** [comment]
@saiyam1814 When you say `Go to telegraf` do you mean in the UI? Just checking to be sure. Also, can you share the config?

**Comment by saiyam1814** [comment]
Yes from the UI

**Comment by effitient** [comment]
Same issue here, using official Docker image for version [2.0.4](https://hub.docker.com/layers/influxdb/library/influxdb/2.0.4/images/sha256-30d2b24b36c0d763de6be494e4caacc9f7c32f99a50a359569bc52aa51f0da03?context=explore).
Start it with
`docker run --name influxdb -d -p 8086:8086 -v influxdb-data:/var/lib/influxdb2 -v influxdb-config:/etc/influxdb2 influxdb:2.0.4`

Open the GUI in Browser (http://localhost:8086) and perform initial configuration (username, password, ...). Then select Data on the left -> Telegraf -> Create Configuration. Select Docker -> Continue -> Give it a name -> Create and Verify.
"Listen for Data" states "Connection found" as though no Telegraf is running, yet, providing any data.
Browse to the provided Telegraf-Config location, e.g. for me it is http://localhost:8086/api/v2/telegrafs/076add70d0b41000

Following content here, no input section:
```
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## For failed writes, telegraf will cache metric_buffer_limit metrics for each
  ## output, and will flush this buffer on a successful write. Oldest metrics
  ## are dropped first when this buffer fills.
  ## This buffer only fills when writes fail to output plugin(s).
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Logging configuration:
  ## Run telegraf with debug log messages.
  debug = false
  ## Run telegraf in quiet mode (error log messages only).
  quiet = false
  ## Specify the log file name. The empty string means to log to stderr.
  logfile = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
[[outputs.influxdb_v2]]	
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ## urls exp: http://127.0.0.1:8086
  urls = ["http://localhost:8086"]

  ## Token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "testing"

  ## Destination bucket to write into.
  bucket = "monitoring"
```
