### ISSUE TITLE
Immediately notify the user that we are loading measurements in DE

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17816]
When clicking on a bucket in the UI, there is a multi-second delay until the UI is updated to tell me that it is loading measurements.

When a user clicks the bucket in the UI, the measurements card should immediately update to tell the user that we are querying for measurements.

![Kapture 2020-04-21 at 9 46 49](https://user-images.githubusercontent.com/4805997/79891011-2d446e00-83b5-11ea-8b57-06e97cc3dbae.gif)

**Comment by desa** [comment]
A few other optimizations we could do always assume that the first two columns will be `_measurement` and `_field`. 

The slowest part of the query builder is fetching the list of columns, returning the values is actually pretty quick.

* fetching columns in a large bucket took ~2-3s, whereas fetching the values took ~0.5-1s
