### ISSUE TITLE
There's no indication that a query is running when using ctl+enter

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17820]
When using the flux editor, there is no indication that a query is actually running when using ctl-enter. When you click the "submit" button, there is a spinner on the button.

We need a clear way to indicate to the user that their query is currently being executed.

**Comment by russorat** [comment]
Looks like there used to be an indicator, so marking this as a regression: https://github.com/influxdata/influxdb/issues/15668

**Comment by drdelambre** [comment]
code shows that there hasn't been an indicator since this button was added (15mo ago or so), so removing regression
