### ISSUE TITLE
Not deleted {num}.tmp dir after backup is complete

### ISSUE THREAD

**Issue by BruceJo** [influxdata/influxdb#17829]
__Steps to reproduce:__
influxd backup -portable -database {db_name} {backup_path}

__Expected behavior:__
When backup is complete, tmp should be deleted.

__Actual behavior:__
When performing backup, a number of "{num} .tmp" directories are created in the "data/{dbname}/{rpname}/{shard}/" path.
![image](https://user-images.githubusercontent.com/37362789/79939202-740b9400-8499-11ea-9319-fdbf3c065d6d.png)

In {num} .tmp, it consists of a tsm snapshot.
![image](https://user-images.githubusercontent.com/37362789/79939272-9dc4bb00-8499-11ea-817a-57ee66f28e07.png)

**This problem takes up a lot of disk space.**
When DB is restarted, it is deleted.

__Environment info:__
win10 64-bit, InfluxDB 1.8.0 

__Config:__
index-version = "tsi1"

**Comment by BruceJo** [comment]
#16289

**Comment by dgnorton** [comment]
Closing: should be fixed by:
`master-1.x` - https://github.com/influxdata/influxdb/pull/18710
`1.8` - https://github.com/influxdata/influxdb/pull/18826
