### ISSUE TITLE
Standardize keyboard shortcuts

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17821]
right now, you use ctl+enter to submit and cmd+/ to comment out the lines.

We need to standardize them and update the documentation in the ? to reflect the correct shortcuts.

This is a regression because before monaco, these keyboard shortcuts were standardized.

**Comment by desa** [comment]
@russorat what does standardize mean? Does it mean document?

**Comment by russorat** [comment]
@desa it means use only cmd+key or ctl+key (or both) and fix the documentation in the ? app. right now, commenting out uses cmd+/ and execute uses ctl+enter

**Comment by desa** [comment]
investigate if there's a way to get system level (ctrl/cmd/meta) command usage.

**Comment by hoorayimhelping** [comment]
be sure to update the keyboard shortcut question mark, here it is on dashboards:

![Screen Shot 2020-04-27 at 10.07.49 AM.png](https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/55ac540b-5f53-455d-bf80-598d01bff7ad)
