### ISSUE TITLE
Raspberry Pi 4 (arm64) Image

### ISSUE THREAD

**Issue by ck-pgtrebacz** [influxdata/influxdb#17840]
__Proposal:__
Official Image of InfluxDB 2.0.0 for AArch64 architecture

__Current behavior:__
To run InfluxDB2.X on Raspberry PI 4 with aarch64 Ubuntu Image I had to compile my own image from sources and publish it to [my public dockerhub](https://hub.docker.com/r/voidborn/rpi_influxdb2) for further use.

__Desired behavior:__
Pulling ready and working docker image from your **official** docker repository.

__Alternatives considered:__
Everybody compiling their sources and creating unofficial docker images.

__Use case:__
I found [this fresh case](
https://community.influxdata.com/t/newbie-installing-influx2-0-on-raspberry-pi-3-model-b-exec-format-error/12046/8) that described the same problem, but for different Raspberry Pi model (arch32). I followed the instructions to create minimal, ready docker image, but I believe it lacks global solution. As this quarantine is going many hobbyist are buying and playing with new Raspberry PI :) would be nice to save their time and headache.

**Comment by russorat** [comment]
connect https://github.com/influxdata/influxdb/issues/18627

**Comment by danxmoran** [comment]
@ck-pgtrebacz we're still working on setting up official Docker images for ARM64, but in the meantime...

The InfluxDB 2.0.3 release includes an updated ARM64 build. You can download the binaries and use them to build your own image: https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.3_linux_arm64.tar.gz

Please let me know how it goes if you try it out!

**Comment by danxmoran** [comment]
@ck-pgtrebacz I'm testing out our Docker cross-build and manifest setup. If you're still interested, could you try pulling `quay.io/influxdb/influxdb:nightly` on your arm64 machine and let me know how it goes?

**Comment by ck-pgtrebacz** [comment]
@danxmoran I've pulled the image you specified to my arm64 machine and it went up. I've open the browser windows and continued to set an clear instance. Did not see any issues. Great work! Thank you! 

ATM I cannot give you more in-depth runway for testing this build, but hopefully I will be able to come back to you later, when my work schedule will calm down.

**Comment by danxmoran** [comment]
`quay.io/influxdb/influxdb:v2.0.4` is now live. It should resolve correctly to the ARM64 build when you `docker pull`

**Comment by patoarvizu** [comment]
@danxmoran Do you have an example of what liveness/readiness probes we can use on that image if I'm running it in Kubernetes? I'm using the Bitnami influxdb Helm [chart](https://github.com/bitnami/charts/tree/master/bitnami/influxdb), which uses `command` [probes](https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/influxdb/deployment-standalone.yaml#L194-L212), but they don't seem to be working for this image.
To clarify: the image is scheduled and it seems to be running properly, at least from looking at the logs, but since the readiness probe never passes, the pod gets restarted over and over every few minutes. Any advice is appreciated!

**Comment by danxmoran** [comment]
The server exposes `/health` and `/ready` endpoints that could be used in HTTP probes (though I'm honestly not sure what the effective difference is between the two or what their implementations are checking, I'm not familiar with that piece of the system). There is also `/ping` which doesn't return a body, but gives you a return code.

**Comment by patoarvizu** [comment]
Ah that sounds great. I'll give it a try, thanks!
