### ISSUE TITLE
[UI - Popovers ] - Hitting escape key fails to close popovers 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#17853]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a new Alerts Check - A Card is created in the Alerts page for the new Check
2. Click "Add a Label" - the Add Labels popover appears
3. Hit the ESC key to dismiss the popover

__Expected behavior:__
The popover should be easy to dismiss, if for example a control was clicked by accident, or user changes his/her mind. 

__Actual behavior:__
The popover was not dismissed.  Need to click elsewhere in the UI for the popover to disappear. 

_Intention was to use ESC in automated tests, since it is a cleaner approach to dismissing the popover than clicking elsewhere, and it should be supported_

__Related Issue__
#16422 - This is from January and is more a feature request than a bug.  

__Regression__ 

I see there is a test for dismissing with ESC in Dashboards, which was added back in December.  It is no longer working

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-96-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly build. 
```
version=nightly commit=69bdae7f7d build_date=2020-04-24T07:59:09Z
```
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with end to end testing enabled 

```
--e2e-testing=true
```

**Comment by ebb-tide** [comment]
This may be due to changes I made in https://github.com/influxdata/influxdb/pull/18524
