### ISSUE TITLE
Pagination + Advanced queries for checks

### ISSUE THREAD

**Issue by nathanshiaulam** [influxdata/influxdb#17864]
__Proposal:__
Short summary of the feature.

__Current behavior:__
Describe what currently happens.
If I make more than 20 checks I can't view them in the UI. In addition, advanced queries aren't yet available for checks.
__Desired behavior:__
Describe what you want.
Pagination for checks + advanced queries
__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Why is this important (helps with prioritizing requests)?
I can't view or edit any checks > 20 without making an API call to get the check ID and hitting the URL for the check directly. Also hard to get a quick overview of the status of my checks.

**Comment by russorat** [comment]
@nathanshiaulam thanks for the issue. I believe in the latest release is limit has been increased to 100 (kicking the can down the road while we work on a broader solution). 

Advanced queries are not yet available for checks, but you can use a task to do the same thing. If you're interested in the structure of the Check task, grab the underlying flux from the `/checks/check_id/query` endpoint and create a task with the same structure.

**Comment by nathanshiaulam** [comment]
Sounds good, thanks for the quick follow up. I'm also noticing a few checks occasionally failing, but not sure what's causing the problem on that front. I currently have around 60 checks and two notification rules set to run every minute. Is that expected to back up the task queues?

**Comment by nathanshiaulam** [comment]
Also sorry if it's obvious, but what are the steps to upgrade to the latest release? I followed the installation instructions for linux here: https://v2.docs.influxdata.com/v2.0/get-started/

Any pointers greatly appreciated. Thanks

**Comment by sjwang90** [comment]
@nathanshiaulam I'm going to close this since it's a known issue and has been brought up again in #20048 and currently looking to improve pagination.

Let me know if you had any issues upgrading as well. OSS 2.0 GA was released last week if you haven't yet upgraded.
