### ISSUE TITLE
influxdb 2.0.0-beta.9 setup wrong confirrmation of retention

### ISSUE THREAD

**Issue by poulhs** [influxdata/influxdb#17862]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. `./influxdb_2.0.0-beta.9_linux_amd64/influxd`
2. `./influxdb_2.0.0-beta.9_linux_amd64/influx  setup --org bug --bucket bug --retention 1h --username bug --password buggy`

__Expected behavior:__
Welcome to InfluxDB 2.0!

You have entered:
  Username:          bug
  Organization:      bug
  Bucket:            bug
  Retention Period:  **1 hrs**
Confirm? (y/n): 
__Actual behavior:__
Welcome to InfluxDB 2.0!

You have entered:
  Username:          bug
  Organization:      bug
  Bucket:            bug
  Retention Period:  **3600000000000 hrs**
Confirm? (y/n): 
__Environment info:__
* System Info: Linux x86_64
* InfluxDB version: InfluxDB 2.0.0-beta.9 (git: eb6a5520df) build_date: 2020-04-24T20:14:53Z

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

Time matters....

**Comment by russorat** [comment]
@poulhs thanks for the issue. yeah this is a bug. we will take a look.

**Comment by jsteenb2** [comment]
@poulhs thanks for filing this bug! fix is in and should land in the next release 👍

**Comment by poulhs** [comment]
but it was such a nice bug.... :wink:
