### ISSUE TITLE
1.8.0 - Databases not loading but present on disk

### ISSUE THREAD

**Issue by DB-CL** [influxdata/influxdb#17876]
Hi,

__Steps to reproduce:__
I have no idea how to reproduce this, but this is what happened :

1. InfluxDB got killed by accident
2. I restarted InfluxDB
3. The databases are not showing up, although I can see them in `/var/lib/influxdb/data`

To be more precise, 2 databases (1 empty and 1 _internal) are there, and the 3 databases with data are not there.

__Expected behavior:__
See my databases when I type `SHOW DATABASES` as admin

__Actual behavior:__
I can only see the database `_internal` and one empty database I created when I was testing the daemon. My 3 databases with actual data are not showing up.

In the logs, I can see a lot of "Opened file" and "Opened shard" with the name of my missing databases. But no errors nor warnings at all.

__Environment info:__
* System info: Linux 4.19.84-coreos x86_64
* InfluxDB version: InfluxDB v1.8.0 (git: 1.8 781490de48220d7695a05c29e5a36f550a4568f5)
* Other relevant environment details: It's on a kubernetes cluster, the `/var/lib/influxdb/data` is in a persistent volume.

__Config:__
As far as I remember it's 100% default conf

__Additionnal informations__
- There is approx 10GB of data, splitted in 3 bases : 7.5GB, 1.5GB and 1GB
- The database was up and running for about 6 months
- Some users I created have also disappeared ( the one linked to the missing DB )
- I've digged into this issue but it did not helped me : https://github.com/influxdata/influxdb/issues/10100

Feel free to ask for additionnal informations, 

Thank you for your time

**Comment by rawkode** [comment]
Hi @DB-CL ,

Can you provide the logs from when InfluxDB is started, please?

**Comment by DB-CL** [comment]
Hi, 

Thank you for your answer, 

I'm not sure about good practices to share logs in github posts, so here is a pastebin link. If its better to put the logs here, I'll do it. Let me know.

https://pastebin.com/raw/3T3wmw6G

**Comment by rawkode** [comment]
Thank you, @DB-CL 

Are you also on our community Slack, incase we have follow up questions?

If not, that's OK too. I'll continue our conversation here.

**Comment by DB-CL** [comment]
I just joined the slack channel, under DBCL name.

**Comment by DB-CL** [comment]
Long story short : I was mounting `/var/lib/influxdb/data` into a PVC but not the rest of this folder (`/var/lib/influxdb/meta` and `/var/lib/influxdb/wal`)

I'm currently trying to recover thank to this post : https://github.com/influxdata/influxdb/issues/9413

It would be great if the logs could state why a parsed folder located in `/var/lib/influxdb/data` is not properly mounted.

I'm also currently seeing an odd behaviour : an empty database is properly restored without the metadata. I don't know if it's normal, but I think it's worth mentioning it.

Thank you @rawkode for your assitance.
