### ISSUE TITLE
The UTC / Local dropdown does not work

### ISSUE THREAD

**Issue by riccardotommasini** [influxdata/influxdb#17877]
__Steps to reproduce:__

List the minimal actions needed to reproduce the behavior.

1. add an event at 2020-01-01 12:00:00 UTC
```
test,sometag=t somefield=1 1577880000 
```

2.  search for it in flux
```
from(bucket: "test")
  |> range(start: 2020-01-01T11:50:00Z, stop: 2020-01-01T12:10:00Z)
```

__Actual behavior:__
I find it

![Screenshot 2020-04-27 at 15 17 11](https://user-images.githubusercontent.com/2592465/80492612-f1894580-896c-11ea-98d2-fbae991e7eb9.jpeg)

3. in the UI,  select UTC in the dropdown and use the calendar field to run the same query
![Screenshot 2020-04-27 at 15 20 59](https://user-images.githubusercontent.com/2592465/80492691-11206e00-896d-11ea-8039-984596635c7e.jpeg)

__expected behavior:__
I find it as before

__Actual behavior:__
Not getting any result

![Image 27-04-2020 at 15 22](https://user-images.githubusercontent.com/2592465/80492720-1a113f80-896d-11ea-9d1d-a1250e195ed8.jpeg)

4) do the same assuming that the data point has a local time. Look for it between 13:00 and 14:00 (but the selector is on UTC)

__Actual behavior:__
![Image 27-04-2020 at 15 25](https://user-images.githubusercontent.com/2592465/80492859-4462fd00-896d-11ea-8422-09a06639f58c.jpeg)

NOTE: I obtain the same result even if I switch to local
![Screenshot 2020-04-27 at 15 25 53](https://user-images.githubusercontent.com/2592465/80492900-517fec00-896d-11ea-9277-d90904419e1d.jpeg)

**CONCLUSION**: the UTC / Local dropdown does not work

__Environment info:__

* System info: version 8e8cfc7 and 5c00430

**Comment by Asalem1** [comment]
I'm gonna reopen this since it doesn't seem to be working for users who's current timezone is GMT, but are offset due to DST
