### ISSUE TITLE
[UI - Alerting] Check editor fails to load bucket in query builder - intermittently

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#17879]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a new check and save.  The new check is listed as a card in the Alerts page
2. Clone the new check. 
3. Click on the clone to edit it 
4. Click the Define Query toggle 

OR 

3. Click Create > threshold check 

__Expected behavior:__

Expected Query Builder to fetch the organization buckets and display them in the first query builder card. 

__Actual behavior:__

Sometimes the first card is empty with the message "No buckets matched your search".  But additional filter cards, in the case of the clone, are displayed with valid values. 

It might be a caching issue. 

__Screencasts__
Edit Issue
![CheckQEFailsToGetBucker01](https://user-images.githubusercontent.com/25881301/80508217-0e774600-8978-11ea-8659-0af7316af157.gif)

Create Issue
![CreateNewCheckNoBucket01](https://user-images.githubusercontent.com/25881301/80508206-0ae3bf00-8978-11ea-8339-2d66b539f5a7.gif)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-96-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly build
```
version=nightly commit=d56966face build_date=2020-04-28T08:16:30Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 80__
__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled. 

```
--e2e-testing=true
```

**Comment by Asalem1** [comment]
This was probably due to some sort of failure to load up the buckets from the API / reducer. Looks like it was resolved and is no longer an issue
