### ISSUE TITLE
v1.measurementTagValues missing a few values.

### ISSUE THREAD

**Issue by GF-Huang** [influxdata/influxdb#17891]
I'm sorry, I don't know if I should post the question here, but I tried posting this question at https://community.influxdata.com, but they restricted new users to only put one image in a post, so I had to come here to post the question.

---

I use the following script to count all values of a specific tag:
```js
import "influxdata/influxdb/v1" 

v1.measurementTagValues(
  bucket: "finance_data",
  measurement: "ticker_changes",
  tag: "ticker"
)
|> count()
```
Then I get result:

![image](https://user-images.githubusercontent.com/4510984/80599142-07763380-8a5d-11ea-89fe-8b5c1c84bd38.png)

It result me total `7640` values. But it should be `7797`.

---

And I had try to get all the values by the following script:
```js
import "influxdata/influxdb/v1" 

v1.measurementTagValues(
  bucket: "finance_data",
  measurement: "ticker_changes",
  tag: "ticker"
)
```
Then download the result as CSV by click 
![image](https://user-images.githubusercontent.com/4510984/80599181-1ceb5d80-8a5d-11ea-8e14-111372805d0f.png)
 

No result in the CSV file by searching `AGBAU`

![image](https://user-images.githubusercontent.com/4510984/80599263-41473a00-8a5d-11ea-9eac-91a98d23b6ea.png)

But I can see `AGBAU` at here:

![image](https://user-images.githubusercontent.com/4510984/80599279-47d5b180-8a5d-11ea-8d52-e37af10d76c4.png)

So, I think `v1.measurementTagValues` results missing a few values.

---

InfluxDB `Version 2.0.0 (a3ff52d)` in docker `quay.io/influxdb/influxdb:2.0.0-beta`

**Comment by sanderson** [comment]
@GF-Huang `v1.measurementTagValues` uses `v1.tagValues` as a primitive which is scoped by default to the last 30 days. You could just `v1.tagValues` with a different time range:

```
v1.tagValues(
  bucket: "example-bucket",
  tag: "host",
  predicate: (r) => r._measurement == "measurement-name",
  start: -60d
)
```

**Comment by GF-Huang** [comment]
How can I use `1970-01-01` for `start` parameter?

**Comment by GF-Huang** [comment]
Thank you! I got the correct result!

![image](https://user-images.githubusercontent.com/4510984/80624372-2afda600-8a7e-11ea-8da5-62f6f4d37537.png)
