### ISSUE TITLE
Create Planner Rule for Grouped Count Aggregate Push Down

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#17892]
This issue is to create a planner rule that pushes down aggregates when the aggregate applies to a different grouping than just the `group by *` default of ReadWindowAggregate.

This issue is not about pushing down group aggregates that are also windowed. That is a separate issue and planner rule.

Example query that would match this push down:

```
from(bucket:"apps")
   |> range(start: -1h)
   |> filter(fn: (r) => r._measurement == "query_log" and r._field == "totalDuration")
   |> group(columns:["env"])
   |> count()
```

The push down rule should use the ReadGroup storage RPC method and specify the aggregate `count`.

DOD:

 * Grouped Count aggregates are pushed down
* Unit tests that show planner rule is correctly modified

**Comment by adrian-thurston** [comment]
WIP: https://github.com/influxdata/influxdb/tree/feat/group-aggregate-rewrite

**Comment by wolffcm** [comment]
Note: I found an issue with how aggregates are evaluated in `ReadGroup`, so we can't enable this rule until this is fixed: https://github.com/influxdata/influxdb/issues/18098
