### ISSUE TITLE
Add Flux End to End test for pushing down ReadGroup Count Aggregate

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#17897]
In #17892 we detail adding planner rules to push down group aggregates without windows. 

We want to create specific end to end tests for this behavior. 

DOD
 * End to End Flux tests exist that show the results are the same when the with or without the push down using the `_test.flux` kind of end to end test.

**Comment by fchikwekwe** [comment]
The consensus was that if we find a bug while writing tests, we should finish writing the test, skip the test and file a new issue to fix the bug and unskip the test.

**Comment by wolffcm** [comment]
This seems to have been fixed by https://github.com/influxdata/flux/pull/2843
