### ISSUE TITLE
Create Planner Rule to push down Window Group Count Aggregate

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#17893]
We need to be able to push down aggregates when the aggregate is grouped by specific dimensions and over a windowed tie range.

Example query:

```
from(bucket:"apps")
    |> range(start: -1h)
    |> filter(fn: (r) => r._measurement == "query_log" and r._field == "totalDuration")
    |> group(columns:["env"])
    |> aggregateWindow(every: 1m, fn: count)
```

The storage RPC layer does not have a ReadGroupWindowAggregate method. This is intentional because grouping + windowing on the storage side of things is an unbounded operation that would require storage to carefully manage the order for which it opens cursors and closes them to align itself with group boundaries and window boundaries. This complexity is not needed on the storage side as it will be equivalent to making multiple ReadGroup calls one for each window period with the aggregate specified. That is something the planner can figure out.

As such we need a planner rule that can create a plan that understands how to do the windowing on the Flux side, and make multiple calls into ReadGroup for each window. This would mean that we make an RPC call per window. 

Alternatively we could make a ReadAggregateWindow call for all the windows and regroup and reapply the aggregate on the Flux side. This would require understand how to safely re-aggregate if possible. This seems more complex and not as likely to faster. Therefore this issue is solely focused on the planner rule to push down multiple ReadGroup calls.

Some open questions:

What about windows that would mean thousands or more requests to storage? Is this common, do we need to protect against it? Something like create a max number of windows and if its over that limit then do not apply the planner rule?

Should this rule be a cost based rule? Do we want to measure the cost of the overhead of an RPC call and weight that against the potential savings. Then if the cost is too high we do not apply the rule? This is basically the same thing as applying a limit to the number of windows except it _should_ be tied to some empirical data .

DOD

 * We have a planner rule that can push down group + window + aggregate queries, using ReadGroup for each window
* Tests for the planner rule
* Answers to the cost based questions.

**Comment by wolffcm** [comment]
When I saw "cost-based questions" I thought we might need to understand characteristics of the data, like cardinality of tag values per field or something like that.  But for this we just need to understand the overhead of a roundtrip to storage.

The bullet points for DOD seem right to me.  As long as we understand the overhead of calling in to storage to avoid doing something totally pathological we are fine.

I see three issues here:
- Create the rule to push down Window Group Count Aggregate (this issue #17893) with a call to Read Group Aggregate for each window. Include a guard against a large number of calls into storage (maybe limit it to 100). If the limit is exceeded, don't apply any change to the plan
- Update the rule to make a single call to Read Aggregate Window with re-grouping and aggregation performed on the Flux side (that's issue #17895).  That can be done if the number of calls into storage would be exceeded.
- Create a separate issue to understand the cost of calling into storage to tweak the limit.

**Comment by wolffcm** [comment]
I just filed https://github.com/influxdata/influxdb/issues/17945 to capture the work needed to understand storage overhead and make it available to the planner.

**Comment by nathanielc** [comment]
Thinking more on this it seems like we are still missing some information in order to create this rule effectively.

Given that we have measured and encoded the overhead of an RPC call (see #17945) what do we compare the value to?

For example say the overhead of an RPC call is 1ms. Say we also have a plan rewrite rule that can generate two plans. One that makes 1000 RPC calls but transfers 1KB of data over the RPC layer and the other that makes only one RPC call but transfers 10MB of data over the RPC layer. How do we compare those two options? It seems we would need two more bits of information: first a rough estimate for the amount of data that would be returned over the RPC layer and second the overhead of transferring bytes of data over the network. Then you could compare the _cost_ (overhead) of one option vs the other.

Do we think we can just use a hard-coded heuristic value for the transfer overhead part of the comparison? We could assume that the transfer savings is always around 10x and so long as the RPC overhead is not 10x then we apply the rule?

Thoughts? I'd like to start with something simple but getting an estimate of the total data transfer an RPC call would create is not something we can do now nor is it simple to add.

**Comment by adrian-thurston** [comment]
Just for my understanding ... please correct me if I'm wrong on any of this. Generally, it doesn't matter if you apply a group then a window, or a window then a group, the end result is the same

```
    |> group(columns:["cpu"])
    |> window( every: 45s )
    |> count()
```
is identical to ...
```
    |> window( every: 45s )
    |> group(columns:["_start", "_stop", "cpu"])
    |> count()
```
This fact leads to the two approaches.

1. Flux iterates through the windows and asks storage to do GroupAggregate operations, once for each window that it computes. Flux unions the output. This is easier because flux can compute the windows ahead of time, based entirely on what it matches in the pattern.

2. Flux iterates through grouping values and asks storage to do WindowAggregate operations. Flux unions the output. The challenge with this approach is that flux doesn't know ahead of time what grouping values to iterate through. Possibly it could ask storage for the n-th grouping value, and stop when it's empty. Would storage need to maintain a cursor, or recompute the grouping list on each call? Not clear. Probably more expensive.

**Comment by wolffcm** [comment]
@adrian-thurston The first approach you describe seems to be the work described in this issue.

The second one:

> Flux iterates through grouping values and asks storage to do WindowAggregate operations.

I don't think this is feasible for the reasons you state, we don't know the group key values, and we don't currently have a mechanism to discover them.  

A similar approach to what you describe is in #17895 but in that case, we push down `window |> agg` to storage, and then on the Flux side we would re-group the data, and aggregate again.

So in the case of your example:
```
    |> window( every: 45s )
    |> group(columns:["_start", "_stop", "cpu"])
    |> count()
```
Storage would window by 45s, and produce a count for each window of each series.  Then on the Flux side, we would would sum up the count for all the groups that have the same value for `cpu`.

**Comment by wolffcm** [comment]
@nathanielc 

I was thinking of doing something really simple, like if we know that the overhead of an RPC call is 10ms, we would just say that if we're spending more than 1s of time just in overhead of RPC calls, that's too much.  So we would not take the one-rpc-call-per-window approach if there are more than 100 windows.

Is that the same as what you are saying, more or less?

It seems to me that even if we hardcode a 10x savings, we still don't know the point where some number of RPC calls is too much, since we don't know what the relative cost of data transfer to RPC call overhead. (unless I'm missing something)

**Comment by nathanielc** [comment]
That makes sense to me, basically measure the overhead and put an upper limit on the amount of overhead we will tolerate.

**Comment by wolffcm** [comment]
This rule should match the pattern
```
count
window
ReadGroup
```
(See #18050 for a rule that will reorder `group` and `window` to help match this pattern)

And the rule should have logic that ensures we don't spend more than a fixed amount of time in the overhead of `ReadGroup` calls. (This can be a fixed number of calls at first, and when available can be informed by the empirically determined RPC overhead from #17945)

There are at least two ways to implement the behavior we want:

## Use a `union` plan node

Rewrite the pattern with multiple ReadGroup (with `count` aggregate) nodes succeeded by a single `union` plan node. This makes use of our plan representation and would be a relatively easy rule to write.

One pitfall of this approach (as @adrian-thurston has noted) is that it would make our execution engine issue several calls into storage concurrently, whereas currently the typical request would only issue one, or maybe two for the vast majority of queries.  This might be a dramatic increase in read load for storage.

One way around that would be to enforce a limit on the number of concurrent RPC calls into storage allowed per request. It could be a configurable number set either by an environment variable/CLI option or possible a feature flag.

Doing this work now could also be useful later on.

## Create a new Source that issues multiple RPC calls itself

This approach would get around the issue of concurrent RPC calls.

The current `Source` interface is here:
https://github.com/influxdata/influxdb/blob/master/query/stdlib/influxdata/influxdb/source.go#L32

It's oriented around wrapping a single call into storage, so it would need to be refactored a bit.

**Comment by wolffcm** [comment]
We determined that the overhead of calling `ReadGroup` was high (not RPC overhead, but sorting series is expensive), so issuing one RPC call per window is not a good optimization to make:
https://github.com/influxdata/influxdb/issues/18064
If storage's implementation of ReadGroup changes, we could revisit this, but closing for now.
