### ISSUE TITLE
InfluxDB v2 - Telegram - Notification Endpoint

### ISSUE THREAD

**Issue by xe-nvdk** [influxdata/influxdb#17899]
__Proposal:__
Add Telegram as Endpoint Notification. 

__Current behavior:__
No exist this option currently

__Desired behavior:__
I want to enable notifications of alerts and send them to a Telegram group. 

__Alternatives considered:__
No alternatives are considered so far. 

__Use case:__
This feature exists in Cronograf and I use it. That be great have in InfluxDB v2.

**Comment by ssoroka** [comment]
The screen in question:
![Screen Shot 2020-04-29 at 11 51 47 AM](https://user-images.githubusercontent.com/7130/80617678-65c8f500-8a10-11ea-967f-36c79c8999fd.png)

**Comment by sranka** [comment]
This feature depends on influxdata/flux#2857, then it has to wait on a flux release with #2866 and updated flux dependency in influxdata/influxdb

**Comment by erkexzcx** [comment]
I still don't see Telegram endpoint :thinking: How am I supposed to alert to Telegram then?

**Comment by sranka** [comment]
Telegram alert notifications are disabled in OSS, they can be active in the Cloud version depending on the subscription type. You can still [create a task](https://docs.influxdata.com/influxdb/cloud/process-data/get-started/) and use [telegram](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/telegram/endpoint/) destination in the flux script.

**Comment by dmgeurts** [comment]
Is there a reason why Telegram notifications are disabled in OSS?

**Comment by hardwareadictos** [comment]
> Is there a reason why Telegram notifications are disabled in OSS?

That would be nice to know... This is a total regression coming form the old Kapacitor....

**Comment by coldnfire** [comment]
> Is there a reason why Telegram notifications are disabled in OSS?
Money ;)

**Comment by coldnfire** [comment]
Here is an example of working script to send alert in telegram endpoint:

On container image: influxdb:2.7-alpine

```
import "influxdata/influxdb/secrets"
import "influxdata/influxdb/monitor"
import "influxdata/influxdb/v1"
import "contrib/sranka/telegram"

option task = {name: "[Alert] Disk used is GT 92%", every: 1m, offset: 0s}

token = secrets.get(key: "atom")
endpoint = telegram.endpoint(token: token)

data =
    from(bucket: "telegraf/telegraf")
        |> range(start: -1m)
        |> filter(fn: (r) => r["_measurement"] == "disk")
        |> filter(fn: (r) => r["_field"] == "used_percent")
        |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)

check = {_check_id: "0b4faa49ae497000", _check_name: task.name, _type: "threshold", tags: {}}

crit = (r) => r["used_percent"] > 92.0
messageFn = (r) => "${r._check_name} is ${r._level}: ${r.path}"

data
    |> v1["fieldsAsCols"]()
    |> monitor["check"](data: check, messageFn: messageFn, crit: crit)
    |> filter(fn: (r) => r["_level"] == "crit")
    |> endpoint(mapFn: (r) => ({channel: "xxxxx", text: "${messageFn(r)}", silent: true}))()
```
