### ISSUE TITLE
Queue limit exceeded

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#17912]
I recently experienced a `queue limit exceeded` error when viewing a dashboard on an OSS instance. I don't have any other reproducers at the moment. It resolved itself in less than a minute when the dashboard attempted to rerun the queries.

This issue is for further investigation to figure out why that error may have shown up.

**Comment by sanderson** [comment]
Likely related community post: https://community.influxdata.com/t/queue-length-exceeded/13974

**Comment by ElieLiabeuf** [comment]
This issue seems related to: https://github.com/influxdata/influxdb/issues/13637

**Comment by ravz** [comment]
bump, also getting this issue

**Comment by phanostech** [comment]
Experiencing the same issue. 
The only solution is to wait a few seconds and try again. Why can't we increase the queue length? Is this set somewhere in the config?

**Comment by ivanscattergood** [comment]
I assumed it was this setting: 

https://docs.influxdata.com/influxdb/v2.0/reference/config-options/#query-queue-size

We have worked around it by implementing a back off an retry in our client

**Comment by donalod** [comment]
Hitting this frequently with a dashboard with more than 10 elements.  Version 2.0.4 (4e7a59b).
![image](https://user-images.githubusercontent.com/4045949/112836916-1f05d400-9093-11eb-9695-f845082833c3.png)

**Comment by meghanareddy59** [comment]
Hi,
Getting this Queue length exceeded error in Version 2.0.4 (4e7a59b).... any idea to resolve this?

![influxdb_error](https://user-images.githubusercontent.com/58840769/116390358-93bb6200-a83b-11eb-8a24-551408b1cbcb.png)

**Comment by danxmoran** [comment]
[v2.0.5](https://github.com/influxdata/influxdb/releases/tag/v2.0.5) (released yesterday) includes changes to concurrency settings that should help with this problem. After upgrading, you can set `query-concurrency` and `query-queue-size` to 0 in config to allow an unlimited number of concurrent queries. The defaults for those settings have also been changed to 0, so if you aren't using a custom config file you should see the new behavior as soon as you upgrade.

**Comment by pyriand3r** [comment]
Just for the records. For tests with InfluxDB i just created 500 simple Tasks/Checks in InfluxDB 2. All tasks have an intervall of 1m and a jitter of 30s.

 Approximately 1/4 of the checks are returning this "queue limit exceeded" error.

I will try to play around with the settings mentioned by @danxmoran

**Comment by michalspondr** [comment]
> [v2.0.5](https://github.com/influxdata/influxdb/releases/tag/v2.0.5) (released yesterday) includes changes to concurrency settings that should help with this problem. After upgrading, you can set `query-concurrency` and `query-queue-size` to 0 in config to allow an unlimited number of concurrent queries. The defaults for those settings have also been changed to 0, so if you aren't using a custom config file you should see the new behavior as soon as you upgrade.

Is that true? In documentation https://docs.influxdata.com/influxdb/v2.6/reference/config-options/#query-concurrency I can see default value = 10. Same for https://docs.influxdata.com/influxdb/v2.6/reference/config-options/#query-queue-size (also 10). No mention about setting to 0.

**Comment by jeffreyssmith2nd** [comment]
That is correct, they are both defaulted to 0. I have opened a PR to address the documentation https://github.com/influxdata/docs-v2/pull/4685
