### ISSUE TITLE
[2.0] Backward compatibility with InfluxQL Query

### ISSUE THREAD

**Issue by Derek-K** [influxdata/influxdb#17922]
__Proposal:__
Backward compatibility with InfluxQL Query

__Current behavior:__
According to 2.0 document, if I understanding correctly, the API could take InfluxQL query
https://v2.docs.influxdata.com/v2.0/api/#operation/PostQuery

However, I can't seem to come across any examples of how to use **InfluxQL** with this API with curl. And the error returned is not too helpful.

```
x-platform-error-code: internal error

{"code":"internal error","message":"An internal error has occurred"}
```

I was able to find an example and use the **flux** with this API with curl and it works, but it is different from the document :thinking:

__Desired behavior:__
A better explanation of the "internal error" to ease troubleshooting.

Perhaps some curl examples on how to use InfluxQL with 2.0. I understand InfluxDB wants to move away from InfluxQL to flux. However, I think most programmers are familiar with the SQL-like language. Some examples will ease the upgrade [1.x->2.0] process without too much resistance.

__Alternatives considered:__
Continue to support 1.x type API?

__Use case:__
As stated above, the change from InfluxQL to flux is a steep learning curve when most programmers are familiar with the SQL like query... This may be a slow down (or show stopper) for 1.x->2.0 upgrade.

**Comment by sanderson** [comment]
@Derek-K Thanks for the issue. InfluxDB 2.0 does not support InfluxQL directly. In the future, InfluxDB will ship with an optional InfluxQL transpiler that will transpile an InfluxQL query into Flux before sending it to the query engine. The transpiler is not available yet, but the `type=influxql` option in the API is stubbed out for it when it does land.

The transpiler is still under development, but you can manually use it in its current state with the [2.0 `influx transpile` command](https://v2.docs.influxdata.com/v2.0/reference/cli/influx/transpile/). It takes an InfluxQL query and returns a Flux query.

**Comment by Derek-K** [comment]
I see... no wonder it doesn't work when I try to query influxdb cloud with influxql always fails with 500... thanks!

**Comment by sanderson** [comment]
@Derek-K Quick follow-up – **InfluxDB Cloud** will support InfluxQL natively. I don't know exactly when it will land, but I know it's close.
