### ISSUE TITLE
Tasks remove comments in Flux code

### ISSUE THREAD

**Issue by alsargent** [influxdata/influxdb#17937]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. In InfluxdB Cloud 2, create a task with a comment denoted by `//`
2. Save your task
3. Reopen your task. Your comment will be gone.

__Expected behavior:__
Don't remove my comments.

__Actual behavior:__
My comments are removed.

**Comment by hardincm2** [comment]
+1 - would be super convenient if saved Tasks would both respect whitespace, and also preserve comments.

**Comment by grapearc** [comment]
The behaviour of this bug is soul-destroying. I commented out my prototype code to try and eliminate an error. My code was eliminated, not the error.
Please fix this ASAP.

**Comment by isorin** [comment]
We need to be able to comment our code. Please don't remove them.
Also if you could leave empty lines alone - you are removing some of them and inserting others and in some cases this makes the code less readable.
I'm ok with the other features like tabulation and spacing inside the lines of code.

**Comment by russorat** [comment]
Sorry this took so long to address. This has been fixed in InfluxDB Cloud. Thank you!
