### ISSUE TITLE
Add storage request overhead to execution dependencies

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#17945]
In order to provide more optimal plans, the planner should understand what the overhead is to make a read request of storage.  This should be the amount of time it takes to make the request and receive the response, taking the volume of data out of the equation.

This belongs in the execution dependencies because it may be different depending on the environment.  In OSS it would be very small, maybe in the nanosecond range.  In other environments, it involves the overhead of a network roundtrip.

**Comment by wolffcm** [comment]
This will likely involve doing some manual experimentation to determine the correct values.

**Comment by nathanielc** [comment]
To make sure I follow, the intent here is that by knowing the fixed overhead to make an RPC call to the storage layer we can begin to weight that cost against any potential gains of making lots of calls vs fewer calls.

With this being a field on the dependencies struct we can tune it for the both OSS and cloud.

Does that sound about right?

**Comment by wolffcm** [comment]
@nathanielc Yes, that's what I was thinking.

**Comment by wolffcm** [comment]
This was intended to help inform planner behavior for the optimization described here:
https://github.com/influxdata/influxdb/issues/17893
However, benchmarking shows that optimization is not worth making.
