### ISSUE TITLE
Behavior of batch write on field value type conflict different between influxdb v1 and v2

### ISSUE THREAD

**Issue by timburke** [influxdata/influxdb#17953]
__Question:__
We noticed a difference in behavior between influxdb v1 and v2 and wanted to know if it was intentional and will be kept in the production influx v2 release.   

In influxdb v1, if you wrote a batch of 5000 points to influxdb and 1 of the points had a field with a type conflict, you would get a 400 error with a "partial write" and the 4999 correct points would written.  This behavior was discussed and fixed (from previous behavior of discarding the entire batch of points) in this PR in 2017:
https://github.com/influxdata/influxdb/pull/7836

In influxdb v2 (`2.0.0-beta.9 commit=eb6a5520df build_date=2020-05-04T20:21:50Z`), the behavior seems to have regreessed to the pre-2017 behavior.  A 400 error is returned and **the entire batch of 5000 points is rejected.**  From the influxdb v2 api docs at https://v2.docs.influxdata.com/v2.0/api/#operation/PostWrite:
![image](https://user-images.githubusercontent.com/2424759/81012838-1834f980-8e0f-11ea-8b6d-68928c8f5544.png)

We are basing this conclusion on:
- writing data points by hand using Chronograf in v2 and manually writing a batch with 1 valid and one type-conflicted point, verifying that the valid point is not committed.
- reading the above linked API documentation that specified that no data is committed during this failure mode.

__Current behavior:__

Influxdb v2 handles batched writes with a type conflict on a single point differently than influxdb v1.  In v1 correct points were committed and points with a type conflict were dropped.  In v2, all points are dropped.

__Desired behavior:__

The v1 behavior where correct points are written and points with a field value type conflict are dropped.

__Use case:__

We collect data from many IOT sensors and other machines and then write it to influxdb for efficient long-term storage.  Since influxdb needs batched writes in batch sizes of 5-10k for high performance, we have a queuing layer in front of influxdb built on top of rabbitmq that receives new data from thousands of sensors and then commits it in batches of 5k.  

The issue is that some sensors can be misconfigured.  For example, a given sensor may initially send a field as an `int` but then the developer changes it and sends it as a `float`.  This results in a field value type conflict.  

In influxdb v1, this is not a problem because that sensor's data will be rejected as type-conflict but it will not harm the rest of the batch that we're committing (from hundreds of unrelated sensors whose data came it at the same time).  However, as we investigated moving to influxdb v2, we see a huge issue because a single field type error from any sensor could block data from all sensors from reaching influxdb since the entire 5k data point batch would be rejected.  

A compounding issue is that we only get an error from influxdb for the first incorrect point so even if we try to manually remove that point and repost, we don't know how many points were invalid so if we had say, 50 readings out of 10k that had a type conflict from a single sensor, we would have to post the 10k points 50 times, removing one point at a time before we succeeded or we would need to drop the entire batch of 10k points.

The only workaround we can see for influxdb v2 is to add a schema management tool into our batching system that stores the types of all fields to know if one changes so we can drop the point before posting a batch to influxdb that would fail due to a conflict.

**Questions**
- Was it an explicit design decision to move to this new behavior in influxdb v2 or should this be categorized as a regression?  
- If it was an explicit design decision, is there any guidance on how to safely batch data writes from multiple sources in influxdb v2?

**Comment by russorat** [comment]
@timburke thanks for the detailed issue. I will find someone to help here.

**Comment by timburke** [comment]
> thanks for the detailed issue. I will find someone to help here.

@russorat Understood.  If there is anything we can do to clarify the use case further, please let me know.  We are happy to provide as much assistance as possible since we have a vested interest in ensuring we can move to Influxdb v2.

**Comment by timburke** [comment]
@russorat I was wondering if there has been a decision made on whether this behavior will be fixed or kept?  If it will be kept, what is the recommendation for batching writing points to influxdb in case a single point could be corrupted, (see use case comment above).

**Comment by russorat** [comment]
@timburke sorry for not replying sooner. We plan to move OSS 2.0 to have the same write behavior as 1.x in the coming months. We will update this ticket when it is available. Thanks!

**Comment by russorat** [comment]
As part of the GA process, we swapped the storage engine to be the same as 1.x, so i think this should have the same behavior as 1.x.
