### ISSUE TITLE
InfluxDB2, Prometheus, remote_write

### ISSUE THREAD

**Issue by rljoia** [influxdata/influxdb#17958]
__Proposal:__
The proposal is to include in the influxdb 2.x version API all necessary endpoints to provide the support for Prometheus remote_write feature. 

__Current behavior:__
I'm analyzing update influxdb to version 2, but I found [this issue](https://github.com/prometheus/prometheus/issues/5657) and [this post](https://community.influxdata.com/t/prometheus-remote-write/12706), which can prevent any other analysis. 

__Desired behavior:__
The same behaviour from the 1.x version for the API feature "/api/v1/prom/ *".

__Alternatives considered:__
If version 2 of InfluxDB doesn't provide this feature in the future, we will evaluate other TSDB solutions.

__Use case:__
My team developed a distributed monitor solution for docker containers using prometheus, grafana and influxdb. All data collected from prometheus instances are stored and centralized on influxdb 1.8.x. We are evaluating update influxdb 1.x to influxdb 2.x, but I heard about influxdb 2.x doesn't have support for Prometheus remote_write.

**Comment by CarlosEssun** [comment]
I have the same problem, hoping to get support,thx

**Comment by ssmiller25** [comment]
+1 as we were planning to use this feature to use InfluxDB for long term metric storage.  We'd like to also see support for remote_read, as we have a lot of dashboards in Grafana that leverage the PromQL query language, and would like them to continue to work.  We've tested this successfully on InfluxDB 1.8.

**Comment by timhallinflux** [comment]
@rljoia -- what mechanism are you using for reading the metrics back out?  Telegraf 1.17 just introduced a Prometheus Remote Write Serializer.  That means it can spit metrics out in that format.  What is missing is the Prometheus Remote Write Parser.  However, if we introduced that... it would be missing the remote_read that @ssmiller25 is also requesting.  So, we are eager to understand if there is a use case for remote_write only.... which folks would find utility in having?   Or does this only make sense once we have a way to perform both the remote_write AND remote_read?

**Comment by rljoia** [comment]
> @rljoia -- what mechanism are you using for reading the metrics back out? Telegraf 1.17 just introduced a Prometheus Remote Write Serializer. That means it can spit metrics out in that format. What is missing is the Prometheus Remote Write Parser. However, if we introduced that... it would be missing the remote_read that @ssmiller25 is also requesting. So, we are eager to understand if there is a use case for remote_write only.... which folks would find utility in having? Or does this only make sense once we have a way to perform both the remote_write AND remote_read?

Hi @timhallinflux,
Yes, there are use cases for remote_write only. For example, my use case (see the description).  

Actually, there are other TSDB solutions that provide support for remote_read or remote_write only. In this link you can see a complete list here: https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage

**Comment by ssmiller25** [comment]
@timhallinflux  Let me know if I should split off a new issue to highly my use case, which does involve both remote_read and remote_write endpoints.

**Comment by sjwang90** [comment]
Thanks for clarifying @rljoia, that gives us more understanding on pushing for a Prometheus remote_write Telegraf parser influxdata/telegraf#8682 to at least address the use cases for remote_write only. 

@ssmiller25 Let's open another issue for remote_read since a Telegraf parser for Prometheus remote_write would be able to address this issue but not both read + write.

**Comment by sjwang90** [comment]
We have recently merged a [Prometheus remote write parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/prometheusremotewrite) into Telegraf that will allow you to read in your prometheus remote write metrics. This is not yet included in a general release of Telegraf but can be used if you build off of master or download the [nightlies](https://github.com/influxdata/telegraf#nightly-builds)

Please note that alignment with [InfluxDB 1.x prom remote write](https://docs.influxdata.com/influxdb/v1.8/supported_protocols/prometheus/#how-prometheus-metrics-are-parsed-in-influxdb) will require to add a processor to the Telegraf config. It is covered at the bottom of the readme and should be a simple addition. 

Please test it out and provide feedback about the parser itself or any issues you may run into.

**Comment by sjwang90** [comment]
The [Prometheus remote write parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/prometheusremotewrite) has been included in the release of Telegraf 1.19. Check out [this blog](https://www.influxdata.com/blog/prometheus-remote-write-support-with-influxdb-2-0/) on how you can use it for InfluxDB OSS 2.x.

**Comment by jesayafn** [comment]
> The [Prometheus remote write parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/prometheusremotewrite) has been included in the release of Telegraf 1.19. Check out [this blog](https://www.influxdata.com/blog/prometheus-remote-write-support-with-influxdb-2-0/) on how you can use it for InfluxDB OSS 2.x.

Doesn't this require additional configuration for Prometheus to read data from influxdb? I read that blog just explain about Prometheus remote write, not Prometheus remote read.
