### ISSUE TITLE
InfluxDB1.8.x, create Users or Tokens via API

### ISSUE THREAD

**Issue by rljoia** [influxdata/influxdb#17960]
__Proposal:__
Since probably InfluxDB2 may not support some features present in InfluxDB1.x, like remote_write for Prometheus, preventing the adoption of this versions for some specific scenarios, like of us, InfluxDB1.8.x API could support some features present InfluxDB2.0, like create/manage users via API.

__Current behavior:__
Today, the only alternative to manage users is using influxdb CLI tool.

__Desired behavior:__
Use manage users via API (like in InfluxDB2).

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
We need to improve the security in remote_write feature in order to avoid expose the same usernames and passwords to all hosts that we are monitoring.

**Comment by lesam** [comment]
We will not be backporting user management to 1.x - our focus is on moving forward and improving the 2.x experience, and user management is well outside what might come as a maintenance release for 1.8.

`remote_write` is available as a telegraf plugin and can be used with 2.x - see https://github.com/influxdata/influxdb/issues/17958 and [this blog post]( https://www.influxdata.com/blog/prometheus-remote-write-support-with-influxdb-2-0/)
