### ISSUE TITLE
influx cli: add option to specify path for configs file

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17979]
from: #17813 

> I suggest adding a command-line option to influx setup that allows the user to specify the destination path for this file, so that it can be more easily integrated with existing container volume mounts.

**Comment by miken32** [comment]
This isn't just about Docker; in a traditional install, configuration files for a service should absolutely not be living in `/home`. I was able to move data files to `/var/lib/` but I'm unable to start the server as a system user without a home directory. Looking forward to this feature being added so we can try 2.0 again.
