### ISSUE TITLE
[UI - Nav Menu] Org item missing from nav menu

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#17991]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Onboard new user and organization 
2. Click quick start at end of wizard

__Expected behavior:__
Expected to find an item "Org" in the left side navigation menu

__Actual behavior:__
No item "Org" was found in the left side navigation menu. 

__Question__ 
Has this been removed intentionally?

Its presence is expected in basic acceptance tests. 

__Screenshots__

![NavMenuOrgMissing01](https://user-images.githubusercontent.com/25881301/81273618-6e907b00-904f-11ea-9bb4-07028b7848b0.png)
![NavMenuOrgMissing02](https://user-images.githubusercontent.com/25881301/81273621-6fc1a800-904f-11ea-870c-57577a251b7a.png)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-99-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly build debian image. 
```
version=nightly commit=33f77d7fea build_date=2020-05-07T08:02:51Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 81__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
Started with e2e testing enabled. 

```
--e2e-testing=true
```

**Comment by desa** [comment]
wont fix
