### ISSUE TITLE
Create planner rule for pushing down bare aggregates

### ISSUE THREAD

**Issue by adrian-thurston** [influxdata/influxdb#17994]
This issue is to create a planner rule that pushes down aggregates over bare range-filters (no grouping or windowing)

Example query that would match this push down:

```
from(bucket:"apps")
   |> range(start: -1h)
   |> filter(fn: (r) => r._measurement == "query_log" and r._field == "totalDuration")
   |> count()
```

The push down rule should use the ReadWindowAggregate storage RPC method where there is only one window and specify the aggregate count.

DOD:

Ungrouped/Unwindowed Count aggregates are pushed down
Unit tests that show planner rule is correctly modified

**Comment by wolffcm** [comment]
This addresses issue https://github.com/influxdata/influxdb/issues/17994

**Comment by wolffcm** [comment]
Created a rule for this: https://github.com/influxdata/influxdb/pull/18144
Also added a test: https://github.com/influxdata/flux/pull/2852
All that remains is to update a pipeline test to verify that we actually push down bare aggregates.
