### ISSUE TITLE
Misaligned cursor/selection position in Flux query editor

### ISSUE THREAD

**Issue by DSpeichert** [influxdata/influxdb#18026]
__Steps to reproduce:__

1. Create a dashboard in UI
2. Edit a chart writing a query manually
3. Click somewhere in the query and start typing or press END key and start typing

__Expected behavior:__
Cursor should show cursor position.
Selection should show selection.

__Actual behavior:__
Visible cursor position is shifted to the left.
Typing shows that characters are entered in the intended position, not where cursor appears to be.
When selecting text, wrong portion is shown as selected but correct text is actually selected.

![image](https://user-images.githubusercontent.com/1254971/81490767-15ddff80-9254-11ea-9833-92d529564421.png)
1: Click here
2: Cursor shows up here
3. New text will show up here

__Environment info:__

* System info: `Linux 5.3.18-3-pve x86_64`
* InfluxDB version: `InfluxDB 2.0.0-beta.10 (git: d00706dea8) build_date: 2020-05-10T04:07:34Z`
* Web browser: Chrome v81 on Windows

**Comment by desa** [comment]
@Asalem1 do we believe this is currently fixed?

**Comment by Asalem1** [comment]
For anyone that plans on working on this, this might be a helpful comment:

https://stackoverflow.com/a/58349818/7963795

**Comment by hoorayimhelping** [comment]
@DSpeichert I can't reproduce this on Firefox or Chrome on Windows 10.`end` and `home` both worked as expected as did highlighting text

Is this still happening for you?

**Comment by DSpeichert** [comment]
Yes, still happening but i'm running the v2.0.0-beta image that hasn't been updated for a while (d00706d).

**Comment by hoorayimhelping** [comment]
@DSpeichert 

That makes sense. I haven't gone through and figured out when this was fixed, but I'm about 90% certain was fixed sometime between the Beta-10 image you're running and the current version. We are currently in the process of deploying Beta-12, which has a bunch of new features and bug fixes if you're interested in upgrading.

I'm going to close this since I can't reproduce it and it seems fixed in our most recent release. If you update to the latest version and still find this happening, please re-open this and tag me and I'll look into it.

**Comment by desa** [comment]
@DSpeichert let us know if you're still experiencing the issue after upgrade

**Comment by DSpeichert** [comment]
@desa are there any plans to release beta-11 or beta-12 image on quay?
If `v2.0.0-beta` is beta-10 and `nightly` is InfluxDB1, there is no docker image to update to.

**Comment by desa** [comment]
@russorat has the new beta landed?

**Comment by russorat** [comment]
beta-12 released Friday, so the image on quay should be updated.

**Comment by russorat** [comment]
tracking down whats going on in https://github.com/influxdata/influxdb/issues/18502

**Comment by russorat** [comment]
the docker image should be updated now. thank you

**Comment by DSpeichert** [comment]
I was able to pull latest image (Version 2.0.0 (ff62078)) and after thoroughly cleaning the browser cache, the issue is now gone.
Thanks!
