### ISSUE TITLE
Dashboards: Variable values are truncated

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18021]
the issue here is that the important part of this value is the very end, that is truncated.

- When the drop down is opened, we should expand the list horizontally to show the full value of the the variable.

![image](https://user-images.githubusercontent.com/4805997/81453399-50ee0f00-913e-11ea-9a8d-0ec160eb1401.png)

**Comment by desa** [comment]
@alexpaxton is this a clockface change or can we do this entirely in influxdb?

**Comment by alexpaxton** [comment]
Should be doable entirely in InfluxDB

**Comment by desa** [comment]
* Fixed width menu
* Dropdown should expand to size of items contained
