### ISSUE TITLE
[2.x] icons show as blocks

### ISSUE THREAD

**Issue by gotjoshua** [influxdata/influxdb#18037]
__Steps to reproduce (and fix):__

1. load influx v2 (running in a docker container - using Google Chrome Canary) and notice that often (but not always) the icons show as blocks
2. open inspector by right clicking on an icon
3. On this line:
 ` .cf-icon {  font-family:icomoon!important; `
add a space before the !important
 ` .cf-icon {  font-family:icomoon !important; `

apparently Chrome Canary Version 84.0.4142.0 (Official Build) canary (64-bit)
doesn't tolerate the lack of a space !?!

__Expected behavior:__
The icons always show

__Actual behavior:__
~9/10 loads the icons show as blocks, and when i add that space they show immediately.
![InfluxIcons](https://user-images.githubusercontent.com/8686454/81597746-1d211c80-93be-11ea-86c1-40cadf5b18dc.gif)

__Environment info:__

* System info: Mac OSX 10.13.6 - Chrome Canary Version 84.0.4142.0 (Official Build) canary (64-bit)
* InfluxDB version: 2.0.0 beta 10

**Comment by TCL735** [comment]
Chrome version 81.0.4044.138 does not strip the space. And I also double checked the style sheet, which has not updated that particular piece of CSS in over a year--the space is intact.

This might be a Chrome Canary bug, as it is an experimental version of Chrome.
