### ISSUE TITLE
Date formats have stopped working

### ISSUE THREAD

**Issue by r1ckbrown** [influxdata/influxdb#18033]
InfluxDB Cloud v2. I just tried to change the date format in a cell from the default to any of the other options. On clicking the tick and returning to the dashboard, the date is still in the default format
<img width="345" alt="image" src="https://user-images.githubusercontent.com/27981402/81589298-3b345000-93b1-11ea-90c0-04dbd8a87806.png">
<img width="170" alt="image" src="https://user-images.githubusercontent.com/27981402/81589412-52733d80-93b1-11ea-8d54-02c7a0e9e330.png">

**Comment by Asalem1** [comment]
@r1ckbrown for some additional context, what was the:

- Original format of the timestamp
- The new format of the timestamp
- The timezone you're setting things to? If you're timezone UI is set to UTC, can you see if the issue exists when it's set to local?

**Comment by r1ckbrown** [comment]
Original format: the default
New format: any of the others
Timezone: Both local and UTC
I've been testing it in-depth, and it specifically has this behaviour in the graph type "Graph + Single Stat". A graph on its own works fine.

**Comment by Asalem1** [comment]
That's interesting that it's specifically Graph + Single Stat. Let me take a look

**Comment by Asalem1** [comment]
Great find on this @r1ckbrown - it seems like this wasn't being handled by the API for quite some time (not sure if this ever was). Just gonna add a quick validation test and make sure that everything is all set
