### ISSUE TITLE
Add legend to cells

### ISSUE THREAD

**Issue by r1ckbrown** [influxdata/influxdb#18035]
__Proposal:__
Add the ability to permanently see which field relates to which line in a graph

__Current behavior:__
No legends are available. I need to highlight a cell and hope that the tooltip shows the information I want
<img width="968" alt="image" src="https://user-images.githubusercontent.com/27981402/81590466-bf3b0780-93b2-11ea-9f50-0686320d899d.png">

__Desired behavior:__
The option to have a static legend under the graph to indicate what is being shown in the graph

__Alternatives considered:__
None

__Use case:__
As can be seen in the image I've uploaded, it's not always possible to see what the graph lines are measuring.

**Comment by Kungitoo** [comment]
Any progress on this? This is a big quality of life thing

**Comment by yianisn** [comment]
Dear influxDB team, I see the static legend option in the dashboard tips but have not figured out how to enable them :-/
Am I missing something?
![image](https://user-images.githubusercontent.com/3265150/113514005-84166980-956c-11eb-9e1f-be0c0875e91d.png)

(Version 2.0.4 (4e7a59b))

**Comment by doivosevic** [comment]
Any update on this?

**Comment by russorat** [comment]
closing this in favor of this issue: https://github.com/influxdata/ui/issues/14
