### ISSUE TITLE
[UI - Event History] Hover event message in popover overruns edge of popover frame

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#18052]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a check with a medium length message and wait for events to be generated
2. Open the event history for the check 
3. Activate event markers in the graph
4. Hover over the head of a marker bar. 

__Expected behavior:__
Expected the event popover information to be contained within the event popover frame. 

__Actual behavior:__
The message overflows the frame. 

__Screenshot__
![EventMarkerMessageOverflow01](https://user-images.githubusercontent.com/25881301/81713482-38e7f980-9476-11ea-8768-00c77cdfc618.png)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-99-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly build. 
```
version=nightly commit=bdc882f6ce build_date=2020-05-12T07:41:12Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 81__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
Started with End2End testing enabled. 
```
--e2e-testing=true
```

**Comment by desa** [comment]
reach out to @alexpaxton when you grab this issue to work through ideas of what to do.
