### ISSUE TITLE
Problem counting values of subquery

### ISSUE THREAD

**Issue by MichaelP89** [influxdata/influxdb#18079]
Hello,

i have a timeseries where all values are 0.

When i run:
SELECT COUNT(value) AS value FROM ...
i get the right number of values.

When i run:
SELECT MEAN(value) AS value FROM ... GROUP BY time(60000ms) ... fill(none)
i get the right values, 0 for every minute.

But when i run:
SELECT COUNT(value) AS value FROM (SELECT MEAN(value) AS value FROM ... GROUP BY time(60000ms) ... fill(none)) ...
i get no count!

I am running influxdb 1.7.7 on Windows.

Greetings
Michael

**Comment by russorat** [comment]
@MichaelP89 thanks for the issue. could you try renaming your fields so they have unique names? 

`SELECT COUNT(inner_value) AS outer_value FROM (SELECT MEAN(value) AS inner_value`

**Comment by MichaelP89** [comment]
Hello,

I'm sorry that  I have bothered you.

There was a problem in my where clause, but renaming the fields helped me to find the problem.

Greetings
Michael
