### ISSUE TITLE
Support the `createEmpty` parameter in ReadWindowAggregate storage

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/influxdb#18091]
Currently, we only push down window aggregate if the `createEmpty` parameter is `false`.
We need to enable pushdown when `createEmpty` is true.

There are two ways to accomplish this:

1. Pushdown the creation of empty window to storage
2. Have the client inject the empty windows into the response it receives

Its not clear without digging into the code which method is best. We should explore both and arrive at a decision

DOD
 - Queries that set `createEmpty` to true are pushed down to storage
 - Pipeline test validate the query is pushed down
 - Test validate the correctness of pushed down vs non pushed down results. This is a Flux end to end test `_test.flux`.

**Comment by fchikwekwe** [comment]
Pipeline test for `aggregateWindow()` pushdowns will already exist. Just need to add additional test cases.

**Comment by jsternberg** [comment]
Fixed by #18288.
