### ISSUE TITLE
Influxdb high CPU and crashes, only way to fix is to delete .tsm files

### ISSUE THREAD

**Issue by viktorsmari** [influxdata/influxdb#18113]
I have been running influxdb for ~4 years and a had this ongoing issue for about a year, where CPU is high and `influxdb` eventually crashes.

Load on the server goes up to 4 while `influxdb` is misbehaving, but is normally around 0.1.

* I am running it in a container which auto restarts but it never recovers fully unless I delete files.
* I update to the latest version every month.

The only way to fix the problem is to **delete** the files it crashed on.
Then I can access the data with Grafana again.

My temp solution is to delete the files causing it to crash, last I had to delete ~ 20 files.

    rm /var/lib/influxdb/data/mydb/autogen/1272/000000169-000000002.tsm
    rm /var/lib/influxdb/data/mydb/autogen/1173/000000378-000000002.tsm 
    rm /var/lib/influxdb/data/mydb/autogen/1200/000000390-000000002.tsm
    rm /var/lib/influxdb/data/mydb/autogen/1191/000000383-000000002.tsm
    ...

And that fixes the problem, but I loose my data.

After that the load goes down to 0.1 on the server.

How can I debug this?

### Server:
4GB RAM, 2 CPUs
Running in a Docker container, now on version 1.7
Docker version 19.03.8, build afacb8b7f0
Debian 9

**Comment by superbool** [comment]
Hello viktorsmari, I'm using Influxdb too,but  it not crash very often. According to my experience,
Influxdb used many memory and CPUs only when you query a lot of series. Like long time data or too large points. 
You can try to add your docker resources ,more RAM and more CPUs. And [update TSM to TSI](https://docs.influxdata.com/influxdb/v1.8/administration/upgrading/#switch-between-tsm-and-tsi-indexes).

[Hardware sizing guidelines](https://docs.influxdata.com/influxdb/v1.8/guides/hardware_sizing/)

**Comment by viktorsmari** [comment]
Thanks @superbool , I updated from 1.7 -> 1.8 and it looks like it's behaving better now.

Instead of deleting the files again, I updated to 1.8 and ran the `influx_inspect buildtsi ...` and afterwards I did not have to delete any files.
