### ISSUE TITLE
UI notifications audit

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#18122]
In the UI, when a user performs a create, update, or delete of a resource (dashboard, bucket, task, etc.), a notification should fire in the UI and let the user know that their operation was successful. 

The goal of this issue is to audit the areas in the app where these actions are performed on resources and determine if notifications are being fired in the UI for them. It would also be useful to understand the text and length of time the notifications are displayed.

#### Acceptance Criteria

- [ ] Is there a notification
- [ ] What does the text say
- [ ] How long is it active

**Buckets**
  * Create - No notification
  * Edit
    * Rename
    * Change Retention Period
  * Delete - No notification

**Telegraf**
  * Create - There is a notification (fill in details here)
  * Add a label
  * Delete - No notification

**Scraper**
  * Create - there is a notificatoin
  * Rename
  * Delete

**Tokens**
  * Generate
  * Rename
  * Toggle
  * Delete

**Client Libraries**
  * Copy to clipboard - there is a notification

**Comment by hoorayimhelping** [comment]
Rose is interested in taking a look at this

**Comment by reparker837** [comment]
**Buckets** 
* Create - No notification
* Delete - No notification
* Copy to clipboard – There is a notification (“Bucket ID ‘[bucket ID]’ has been copied to clipboard.” for 5 sec)
* Settings
    * Rename – There is a notification (“Bucket was successfully renamed “[bucket name]”” for 5 sec)
    * Change Retention Period – There is a notification (“Bucket “[bucket name]“ was successfully updated” for 5 sec)
* Labels
    * Add a label - No notification
    * Delete label  – No notification

**Telegraf**
* Create - There is a notification (“Your configurations have been saved”  for 5 sec)
    * If System selected: There is a notification – (“Successfully created dashboards for telegraf plugin: system.” for ~5 sec, pops up a beat after the create one, stacked). Else, there is no second notification.
* Delete - No notification
* Rename - No notification
* Edit description – No notification
* Labels
    * Add a label - No notification
    * Delete label  – No notification
* Setup Instructions
    * Copy to clipboard – There is a notification (“Script 'export INFLUX_TOKEN=<INFLUX_TO...' has been copied to clipboard.” for 5 sec)
    * Generate new token - No notification
* InfluxDB Output Plugin
    * Copy to clipboard – There is a notification (“Script ' [[outputs.influxdb_v2]] ##...' has been copied to clipboard.” for 5 sec)
    * Download Config - No notification 

**Scraper**
* Create – There is a notification (“Scraper was created successfully” for 5 sec)
* Rename – There is a notification (“Scraper “[scraper name]“ was updated successfully” for 5 sec)
* Delete – There is a notification (“Scraper “[scraper name]“ was successfully deleted” for 5 sec)

**Tokens**
* Generate – There is a notification (If a token is created, “Token was created successfully” for 5 sec. If you don’t select buckets for Generate Read/Write Token, “Failed to create tokens” for 10 sec)
* Rename – There is a notification (“Token was updated successfully” for 5 sec)
* Toggle – There is a notification (“Token was updated successfully” for 5 sec) 
* Delete – There is a notification (“Token was deleted successfully” for 5 sec)

**Client Libraries**
* Copy to clipboard - there is a notification (“Script 'http://localhost:8080...' has been copied to clipboard.” for 5 sec)
* Copy to clipboard inside a client library – there is a notification (“Script 'Install-Package InfluxDB.Clien...' has been copied to clipboard.” for 5 sec) Note: The message will last until it times out or you manually delete the notification, and until it is gone a new notification will not be displayed (ex. If you copy two things to clipboard one after another, the notification will still read the first thing is copied to clipboard, even though the second one is what’s actually on your clipboard)

**Summary**
* Create –  Buckets does not have a notification
* Delete – Buckets and Telegrafs do not have notifications
* Rename – Telegrafs does not have a notification
* Copy to clipboard – There is always a notification, but some confusion if you copy several different values to clipboard in a row (they don’t stack)
* Labels – There is never a notification
* Toggles – There is always a notification, but they seem unnecessary
* Stacking – All notifications that have stacked disappear 5 sec after the first one appeared & copy to clipboard notifications don’t stack
* Length – the notification for when generating a token fails is 10 sec, all others are 5 sec
