### ISSUE TITLE
Add implementation of Sum aggregate

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#18134]
We now have a count aggregate, we need to implement the sum aggregate for ReadWindowAggregate RPC method.

DOD
 - Sum aggregate implementation exists
 - Sum aggregates are pushed down
 - Add sum capability to server both implementations (OSS and IDPE)
 - End to end tests shows it exists.

**Comment by nathanielc** [comment]
Once the refactor to reuse aggregates  https://github.com/influxdata/flux/issues/2855 is complete the aggregate implementation should be complete.

**Comment by wolffcm** [comment]
Fixed by https://github.com/influxdata/influxdb/pull/18484
