### ISSUE TITLE
UI Issue: Table scrollbars in dashboard / data explorer are not tracking dataset

### ISSUE THREAD

**Issue by nisley** [influxdata/influxdb#18148]
Table scrollbars in dashboard / data explorer are not tracking dataset.

Of the three tables I have on a dashboard, two are 'infinity' scrolling, and one doesn't scroll but the scrollbar indicates it should.

![ScrollbarsNotWorkingMay18](https://user-images.githubusercontent.com/1389799/82268520-10ec1080-9924-11ea-87f4-87f5cb5d3ad6.gif)

**Comment by nisley** [comment]
@lukevmorris's observation: 
it's that the window is truncating the data set and renders most of the table as a blank area
if i zoom out, it renders more data. seems like the table renders only as much data as needed to fill the height of the window, and no more

**Comment by desa** [comment]
quick fix is to revert of https://github.com/influxdata/influxdb/pull/18016 with https://github.com/influxdata/influxdb/pull/18150.
