### ISSUE TITLE
connect to influx 2.0 url

### ISSUE THREAD

**Issue by kubalo90** [influxdata/influxdb#18160]
Hi All!

I'm trying to change the address of InfluxDB, that I'm connecting to using a terminal on Mac. The default host is 8086, but I need to access the database (influx 2.0), that is set up under certain url. How can I change the default host to a url?

**Comment by sanderson** [comment]
@kubalo90 Are you connecting using the `influx` CLI? How exactly are you trying to connect?

**Comment by kubalo90** [comment]
> @kubalo90 Are you connecting using the `influx` CLI? How exactly are you trying to connect?

yes, I'm accessing influxdb through Mac terminal. I have previously set up a database on my localhost, however now I need to connect to a db that I'm usually accessing through url (a company database on influx db 2.0). Is that possible in order to see e.g. databases etc?

**Comment by sanderson** [comment]
You need to use the 2.0 `influx` CLI that you [download with InfluxDB 2.0](https://v2.docs.influxdata.com/v2.0/get-started/#start-with-influxdb-oss). Once you've downloaded the 2.0 `influx` CLI, you have a couple of options for defining the host:

- Use the `-h`, `--host` flag
- Set the `INFLUX_HOST` environment variable
- Use the [`influx config` command](https://v2.docs.influxdata.com/v2.0/reference/cli/influx/config/) to configure profiles to use to connect

**Comment by danxmoran** [comment]
Closing this as it looks like the question was answered
