### ISSUE TITLE
 Can’t install InfluxDB from repos.influxdata.com on Ubuntu 20.04 

### ISSUE THREAD

**Issue by rpthms** [influxdata/influxdb#18178]
Since I didn't get any response on the community forums (https://community.influxdata.com/t/cant-install-influxdb-from-repos-influxdata-com-on-ubuntu-20-04/14213), I figured I might as well create a bug report here.

I added InfluxData’s repository for Ubuntu packages using the instructions given at docs.influxdata.com/influxdb/v1.8/introduction/install/. I added the repo on a Ubuntu 20.04 installation, so my sources.list entry looks like this:

```
# InfluxData Repository
deb https://repos.influxdata.com/ubuntu focal stable
```

But when I tried to install InfluxDB, I couldn’t do so. The only package that I’m able to install from that repository is Telegraf.

I visited the repos.influxdata.com site on my browser and noticed that the Packages file for Ubuntu 20.04 under binary-amd64 was only showing the Telegraf package, but the Packages file for the previous Ubuntu version (Eoan) under binary-amd64 is showing all the other packages. Could someone at InfluxData get the repository for Focal Fossa updated as well?

Here’s the Packages file for Ubuntu 20.04 (Focal): https://repos.influxdata.com/ubuntu/dists/focal/stable/binary-amd64/Packages

And here’s the Packages file for Ubuntu 19.10 (Eoan): https://repos.influxdata.com/ubuntu/dists/eoan/stable/binary-amd64/Packages

Thanks

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Add the Focal Fossa repository from repos.influxdata.com
2. Try to install influxdb

__Expected behavior:__
InfluxDB should be installed

__Actual behavior:__
InfluxDB is missing from the repo and can't be installed

__Environment info:__

* OS: Ubuntu 20.04 LTS (Focal Fossa)

**Comment by salvatorelionetti** [comment]
You are not alone

**Actual Behavior:**
A very old version has been installed.

> (base) slionetti@milumnand04:~$ dpkg -l | grep influx
> ii  influxdb                                   1.6.4-1build1                       amd64        Scalable datastore for metrics, events, and real-time analytics
> 

** Expected behavior: **
A more recent version should be installed
I'm just having troubles with missing tags...

**Steps to reproduce:**
> wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
> source /etc/lsb-release
> echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
> 

** Environment info: **
I'm using Ubuntu 20.04 LTS (Focal Fossa) on amd64 platform.


Thanks for your attention

**Comment by salvatorelionetti** [comment]
I've the installed manually 'https://dl.influxdata.com/influxdb/releases/influxdb_1.8.0_amd64.deb'.
Unfortunately users are not recognized at all.
I've cancelled all the data and started with a clean installation, now grafana is working fine.

**Comment by rpthms** [comment]
I can see that the repo has been updated and now kapacitor and chronograf can be installed on Ubuntu 20.04 along with telegraf, but influxdb is still missing: https://repos.influxdata.com/ubuntu/dists/focal/stable/binary-amd64/Packages. Kapacitor and chronograf started showing up as soon as a new version of those applications were released.

So it looks like influxdb will eventually show up in the repo when a new version of influxdb is released. Unless of course someone from InfluxData manually edits their repository and allows Focal users to download influxdb before a new release. They don't even have to build a new package because AFAICT, all Debian and Ubuntu releases are using the same DEB package for all InfluxData software.

**Comment by mark-rushakoff** [comment]
FYI @russorat @mhall119

**Comment by russorat** [comment]
@rpthms i believe influxdb 1.8.0 is now ready for focal. can you confirm? https://repos.influxdata.com/ubuntu/dists/focal/stable/binary-amd64/Packages

**Comment by rpthms** [comment]
Yes, influxdb is now showing up in the Focal repo!! Thanks @russorat and @mark-rushakoff.

**Comment by russorat** [comment]
can we close this?

**Comment by rpthms** [comment]
Yep, the issue is resolved. It can be closed now.
