### ISSUE TITLE
Customizing a large bin size for heatmap crashes the app

### ISSUE THREAD

**Issue by TCL735** [influxdata/influxdb#18182]
When customizing a heatmap, a large number for bin size causes a crash. User can recover by refreshing the page.

![heatmap_crash](https://user-images.githubusercontent.com/10736577/82511133-57c33d00-9ac1-11ea-96c9-c05299fc8fdc.gif)

**Comment by zoesteinkamp** [comment]
![Screen Shot 2020-05-27 at 4.32.27 PM.png](https://images.zenhubusercontent.com/5e42e20611e3ce3816a90441/31595927-6695-40fe-aae2-0fd3f60faa3f)

This is actually a giraffe issue. Not something we should fix in influxdb per say.
