### ISSUE TITLE
Create a test to verify in OSS that window aggregate query was indeed pushed down to storage

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/influxdb#18184]
Similar to https://github.com/influxdata/idpe/issues/6999, we want to have a verification test in OSS. 
We can still read the `query_influxdb_source_read_request_duration_seconds` metric, it's set in influxdb: query/stdlib/influxdata/influxdb/metrics.go

**Comment by nathanielc** [comment]
I believe you can use the `launcher` to standup the testing framework in order to run a query and get metrics.
