### ISSUE TITLE
Error with using the 'influx write' command

### ISSUE THREAD

**Issue by sanderson** [influxdata/influxdb#18195]
Whenever I try to use the `influx write` command and specify a bucket, for example:

```
influx write -b test 'test something=2i'
```

It returns the following error:

```
Error: Failed to retrieve buckets: invalid bucket list action, call should be GetBucketByName.
```

On a side note, if I don't provide a bucket, the command _appears to be successful_. It doesn't return an error, but it doesn't write the data (which it shouldn't).

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Build 2.0 from source
2. Create a `test` bucket
3. Run `influx write -b test 'test something=2i`

__Expected behavior:__
Data to write successfully to the bucket.

__Actual behavior:__
I got the error above.

__Environment info:__
* InfluxDB version: InfluxDB dev (git: bf13e339fe) build_date: 2020-05-21T23:12:56Z

**Comment by wuzhc** [comment]
I have the same problem,how can i do
