### ISSUE TITLE
Alert Checks - 1. Define Query step unusable after importing manifest

### ISSUE THREAD

**Issue by mdevy-influxdata** [influxdata/influxdb#18196]
After importing a manifest, an Alert check can not be modified.  
The 1. Define Query step is not functioning properly.

The following has been verified using influxdb 2.0 beta 10, using various community-templates based manifests, on multiple instances and workstations.

__Steps to reproduce:__

1. Import a community template.  
`./influx pkg -f ~/community-templates/docker/docker.yml`
2. Using browser, click on any of the newly created "Checks" in the "Alerts" configurations, such as "Container Mem Usage Pct"
3. Click to "1. Define Query" 
<img width="1456" alt="config-check" src="https://user-images.githubusercontent.com/53542066/82615395-1ee99d80-9b7f-11ea-966d-7e8e0c1fea7d.png">

__Expected behavior:__
The ability to modify the query.  Able to browse the schema.

__Actual behavior:__
Query not editable.  (image above)
The UI is complaining about missing field and aggregate functions.  
<img width="327" alt="config-check-alert" src="https://user-images.githubusercontent.com/53542066/82615389-1a24e980-9b7f-11ea-9277-7f01157ee408.png">

**Comment by desa** [comment]
@jsteenb2 have you seen this one before?

**Comment by zoesteinkamp** [comment]
Ive determined the problem to be from the lack of tags, at this moment our code does not allow for zero tags. 

![Screen Shot 2020-06-11 at 11.44.18 PM.png](https://images.zenhubusercontent.com/5e42e20611e3ce3816a90441/f2fa81e1-40de-4bf9-9158-1c555a7b9a67)

Im going to talk to mike devy further about this problem

**Comment by jsteenb2** [comment]
@desa I don't recall this one. However, I didn't spend a ton of time in the UI for checks.
