### ISSUE TITLE
Swagger.yml: Add Backup endpoint

### ISSUE THREAD

**Issue by stephanie-engel** [influxdata/influxdb#18220]
Now that this [epic](https://github.com/influxdata/influxdb/issues/15417) is implemented in 2.x OSS, we need to add the `backup` endpoint to the swagger doc.

**Comment by danxmoran** [comment]
This was done as part of reimplementing `backup` in the new CLI, see the swagger doc here: https://github.com/influxdata/openapi/blob/master/contracts/oss.yml#L6639-L6754
