### ISSUE TITLE
Template Installer Modal

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#18235]
# Background
As a user, I want to see what resources my template needs and the readme of the template

# Acceptance Criteria
* In the default tab, show a list of resources / mappings included in the template
  * secrets
  * environment variables
  * buckets should come later (we're punting on implementation)
* In a secondary tab, show the github readme
* Template name should come from the template url until we have a way to specify it explicitly.
  * Name should be human readable (e.g. convert underscores to spaces)

**Comment by rickspencer3** [comment]
For the mappings, I assume that there will be some generated UI, but that UI will not be annotated, but, rather, the user will be instructed to refer to the readme to understand each parameter? This makes sense to me.

**Comment by jsteenb2** [comment]
There is backend work that this card depends on. The envRefs and secrets I'd like to revisit so that they are not returned as a root lvl parameter but instead provided within the summary of the resources within the template.  I'll make a card for it right meow.

here: #18407

**Comment by jsteenb2** [comment]
can there be a screenshot of the mockup for this added? Is the ability to select/unselect the resources involved in this?
