### ISSUE TITLE
Lookup Template Mappings

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#18237]
Stack name: should default to url name, but be an option to provide in the future

_"mappings"_ will be blocked by the following spike: https://github.com/influxdata/influxdb/issues/18240

**Comment by jsteenb2** [comment]
What is this card trying to convey? I'm lost in this title/description

**Comment by alexpaxton** [comment]
@jsteenb2 if I had to guess I think it has to do with the view in which you can tell a template what bucket to read/write from (for example)

**Comment by jsteenb2** [comment]
ah ok cool. The description left my confused on this story. Think we're confusing template name, with stack name here. Hopefully all that will be clear after my talk.

**Comment by jsteenb2** [comment]
card is unblocked now. We have the ability to update the name of a stack now. Unblocked by: https://github.com/influxdata/influxdb/pull/18560
