### ISSUE TITLE
Good First Issue - HoneyBadger error handling

### ISSUE THREAD

**Issue by Asalem1** [influxdata/influxdb#18249]
### Problem

HoneyBadger is currently reporting a lot of noise. Lost amongst the noise is genuine bugs that are cause for concern. In order to increase confidence in our HB errors, it's our goal to remove the unnecessary noise from our HB alerts. Below is a list of good first issues that can be addressed in order to remove excessive noise from our system and give us more confidence in our error reporting:

- [ ]  #18261
- [ ]  #18262
- [ ]  #18263

**Comment by russorat** [comment]
@Asalem1 is this epic still valid?

**Comment by russorat** [comment]
I'm closing this for now. please reopen if this is still relevent.
