### ISSUE TITLE
Backend: Inspecting for variables

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#18241]

**Comment by hoorayimhelping** [comment]
depends on flux team

**Comment by rickspencer3** [comment]
Was there not an existing issue for this with considerably more detail? Can we give the Flux team something more actionable if they don't already have it?

**Comment by jsteenb2** [comment]
@rickspencer3 there is one, I cannot find it for the life of me...

**Comment by jsteenb2** [comment]
@rickspencer3 found it here https://github.com/influxdata/influxdb/issues/17430, closing this one in light of that
