### ISSUE TITLE
Community Templates UI

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#18245]
https://www.figma.com/proto/rlE38WapRMBEfi6DjiXMu8/Templates-Prototype-v4?node-id=1%3A3&viewport=25%2C323%2C0.17564575374126434&scaling=min-zoom

**Comment by rickspencer3** [comment]
Why are we using the community templates repo for this? Shouldn't we rather, as a first step, replace the existing templates?

**Comment by rickspencer3** [comment]
At what point in the plan do we replace the existing templates feature in the UI with packager-based templates? Does this have implications for users of those templates?

**Comment by jsteenb2** [comment]
@rickspencer3 the plan moving into this MVP, is to feature flag the new templates workflow. When that bit is flipped, the old templates will disappear and the new will be left standing. 

It was discussed at the dev inception, the number of people using existing templates is very low.

**Comment by kristinarobinson** [comment]
Community Templates feature implemented.
