### ISSUE TITLE
Wire up DIFFERENCE aggregate

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#1825]
If the query is like this:

```sql
SELECT DIFFERENCE(value)
FROM cpu
WHERE time > now() - 4h
```

It will return a series with the difference between each value.

If the query is like this:

```sql
SELECT DIFFERENCE(MIN(value))
FROM cpu
WHERE time > now() - 4h
GROUP BY time(5m)
```

It will return the difference of the min value for each 5 minute window of time.

**Comment by Gibheer** [comment]
From (tsdb/executor.go#L443)[https://github.com/influxdb/influxdb/blob/master/tsdb/executor.go#L443] this seems to be implemented now, is that correct?

**Comment by jchauncey** [comment]
Any news on when this might come?

**Comment by Vebryn** [comment]
I don't see this issue on 9.5 changelog https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md

**Comment by beckettsean** [comment]
@Vebryn it hasn't been completed, so it is not on the CHANGELOG.

**Comment by Vebryn** [comment]
Ok, thank you, let's wait and see

**Comment by superdump** [comment]
Looking forward to this.

**Comment by corylanou** [comment]
The query engine is undergoing heavy refactoring.  Removing help wanted label for now.

**Comment by superdump** [comment]
@corylanou - what kind of heavy refactoring? Are you intending to support joins, more complex multi-measurement queries, etc?

**Comment by mirath** [comment]
We use collectd to collect metrics from all our infrastructure. For A LOT of metrics sends the total cumulative values up until a certain point (CPU time for example). Without difference we have no way to show this values in a meaningfull way correctly. When will this be implemented in the 0.9 line?

**Comment by marcinpraczko** [comment]
Hi, Are there any ETA for this when it will be released?
Or what is other way of displaying bandwidth usage? We know that linux increases this number over and over: `/sys/class/net/eth0/statistics/rx_bytes`, so is there any way to do difference on InfluxDB level, or so far I have to do that differently by "collector"?

**Comment by pauldix** [comment]
What about `non_negative_derivative`?

**Comment by tothandor** [comment]
Could you please add a shorter alias for this function, like "diff" or "delta" instead of "non_negative_derivative"!

**Comment by jazdw** [comment]
Is there currently anyway to define different grouping functions for time and between series? So we can do mean_series(last("value") - first("value")).

**Comment by beckettsean** [comment]
@jazdw no, there are no composite functions yet. That specific case is an interesting feature request, can you open a new issue to track it?

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by jsternberg** [comment]
I'm beginning to work on this.

**Comment by Placinta** [comment]
I know this is an old closed issue, but it still pops up when googling.
As requested by some previous commenters, the solution for computing bandwidth usage for a specific time period (or disk usage increase / decrease) is described in the final comments of https://github.com/influxdata/influxdb/issues/7076 and involves the usage of difference and cumulative_sum.
