### ISSUE TITLE
Arduino Client Lib examples

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/influxdb#18278]
Similar to this PR https://github.com/influxdata/influxdb/pull/18198

We should add the [Arduino client library](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino) and examples once the query capabilities have been merged.  

logo:
![arduino-logo](https://user-images.githubusercontent.com/23535264/83204138-f4a85a80-a0ff-11ea-8017-d51fdc851c9f.jpg)

**Comment by vlastahajek** [comment]
Added in #18396
