### ISSUE TITLE
Update group+agg pushdown planner rule to add "re-aggregation"

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#18304]
Currently our push down aggregate [rule](https://github.com/influxdata/influxdb/blob/d304f920dc6f71dd1ba743c082bb0b1ac3efade0/query/stdlib/influxdata/influxdb/rules.go#L829) will get a wrong answer due to this bug:
https://github.com/influxdata/influxdb/issues/18098
To summarize that issue, storage currently will do aggregation only per-series, not per group.

That bug might take a while to fix, and in the meantime we want to be able to push down different kinds of aggregates, so we should workaround this bug with an update to the planner rule.

We want to update this rule for plans like this where `aggFn` is one of `count`, `sum`, `first` or `last`:
```
ReadGroup(bucket, range, filter, groupColumns: [...])
  |> aggFn
```
they should get transformed to
```
ReadGroup(bucket, range, filter, groupColumns: [...], agg: aggFn)
  |> reaggFn
```
Where `reaggFn` does re-aggregation based on the aggregate function:
- `count` should be re-aggregated in Flux with `sum`
- `sum` should be re-aggregated in Flux with `sum`
- `first` should be re-aggregated in Flux with `min(column: "_time")`
- `last` should be re-aggregated in Flux with `max(column: "_time")`

Note that `group` doesn't preserve the time-ordered property of its input tables, so we just use `min` or `max` on the `_time` column instead. Also note: we are *not* proposing to support `min` or `max` as pushdowns to storage.

DOD:
  - Rule is updated to produce re-aggregation nodes
  - Complete test coverage in the unit test exists
  - Create new feature flags for `first` and `last` support in `ReadGroup`, defaulted to false

**Comment by jlapacik** [comment]
Closed via https://github.com/influxdata/influxdb/pull/18342
