### ISSUE TITLE
Cell fails to show properly after creation

### ISSUE THREAD

**Issue by NULLx76** [influxdata/influxdb#18312]
__Steps to reproduce:__
1. Create a new query under Explore
2. Save it to a specific dashboard

__Expected behavior:__
I expect it to show the cell properly

__Actual behavior:__
It shows an error message saying I should report a bug. After refreshing it shows up fine though.

This behaviour is consistent over the few times I've tested it.

__Environment info:__

* System info: `Linux 4.18.0-147.8.1.el8_1.x86_64 x86_64`
* InfluxDB version: `InfluxDB 2.0.0-beta.10 (git: d00706dea8) build_date: 2020-05-31T19:20:37Z`
* Browser: Firefox on Linux

__Logs:__
From the browser console:
```
Empty string passed to getElementById(). 235 Popover.tsx:217:35
Empty string passed to getElementById(). Overlay.tsx:60:33
Empty string passed to getElementById(). 2 Popover.tsx:217:35
Empty string passed to getElementById(). Overlay.tsx:60:33
Empty string passed to getElementById(). 11 Popover.tsx:217:35
TypeError: can't access property "map", t.queries is undefined
    no TimeSeries.tsx:317
    Redux 7
    React 11
    Redux 11
    u queryStringConfig.ts:9
    o resizeLayout.ts:9
    Redux 3
    B thunks.ts:355
    Redux 2
    getResourceDetails GetResource.tsx:51
    componentDidMount GetResource.tsx:43
    componentDidMount GetResource.tsx:42
    React 3
    unstable_runWithPriority scheduler.production.min.js:18
    React 7
    _unlisten Router.js:103
    r createTransitionManager.js:228
    c createTransitionManager.js:83
    b AsyncUtils.js:74
    b AsyncUtils.js:80
    k getComponents.js:6
    k getComponents.js:30
    b AsyncUtils.js:79
    b AsyncUtils.js:78
    k getComponents.js:29
    c createTransitionManager.js:77
    r TransitionUtils.js:74
    runEnterHooks TransitionUtils.js:107
    l createTransitionManager.js:70
    r TransitionUtils.js:74
    runChangeHooks TransitionUtils.js:131
    l createTransitionManager.js:67
    u createTransitionManager.js:45
    l AsyncUtils.js:41
    y AsyncUtils.js:51
    j matchRoutes.js:231
    u createTransitionManager.js:41
    r createTransitionManager.js:222
    g useQueries.js:75
    d useBasename.js:67
    y createHistory.js:55
    y createHistory.js:54
    C createHistory.js:115
    w createHistory.js:90
    l AsyncUtils.js:51
    loopAsync AsyncUtils.js:55
    w createHistory.js:80
    C createHistory.js:100
    t BrowserProtocol.js:53
    ___hb honeybadger.js:466
    t honeybadger.js:633
    addEventListener DOMUtils.js:5
    startListener BrowserProtocol.js:56
    y createBrowserHistory.js:68
    _ createBrowserHistory.js:84
    d useBasename.js:66
    g useQueries.js:74
    1 index.tsx:172
    Webpack 5
react-dom.production.min.js:198:194
Context that would have been sent to HoneyBadger: errors.ts:50:4
console.table() errors.ts:51:4
(index)
Values
user_id
05c1c665600a9000
orgID
05c1c66578ca9000
deleteWithPredicate
false
downloadCellCSV
false
telegrafEditor
false
customCheckQuery
false
matchingNotificationRules
false
demodata
false
fluxParser
false
frontendExample
42
component
Connect(withRouter(to))
```

Screenshot of the error:
![image](https://user-images.githubusercontent.com/1809198/83360845-ad7ecb80-a384-11ea-92eb-18234a5e8c6a.png)

**Comment by desa** [comment]
@NULLx76 Would it be possible for you to provide the JSON of your dashboard. This should be available by opening your network tab in your browser and viewing the dashboard(s) response.

**Comment by NULLx76** [comment]
This is the response from a get request to `/api/v2/dashboards`
[get_dashboard.json.txt](https://github.com/influxdata/influxdb/files/4738443/get_dashboard.json.txt)

and this is the exported dashboard: 
[export.json.txt](https://github.com/influxdata/influxdb/files/4738449/export.json.txt)

**Comment by Asalem1** [comment]
@NULLx76 it doesn't seem like there were any errors in the logs you linked through to us. Do you happen to know if the issue still exists / whether the issue went away after rerendering the dashboard? I'm also curious as to whether you were referencing any variables in that cell's query?
