### ISSUE TITLE
Dashboard: Can't modify "Graph+Single stat" time format

### ISSUE THREAD

**Issue by jpillora** [influxdata/influxdb#18339]
Firstly, awesome work with influxdb 2, I haven't used influxdb in a few years and all the changes look great :)

```sh
$ docker images | grep influx
quay.io/influxdb/influxdb        2.0.0-beta          71a7ac91d210        3 weeks ago         225MB
$ docker exec influxdata uname -srm
Linux 5.3.0-40-generic x86_64
$ docker exec influxdata influxd version
InfluxDB 2.0.0-beta.10 (git: d00706dea8) build_date: 2020-06-02T21:09:12Z
```

I have a "Single stat +Graph" cell and whenever I change the time format, it previews correctly, but doesn't save when I hit the little green tick

1.

![image](https://user-images.githubusercontent.com/633843/83570131-df508780-a568-11ea-98fa-8a094afa8486.png)

2.

![image](https://user-images.githubusercontent.com/633843/83570640-c2688400-a569-11ea-887b-0fb5f06ad797.png)

3.

![image](https://user-images.githubusercontent.com/633843/83570667-cdbbaf80-a569-11ea-9577-9ace2e6d528d.png)

**Comment by desa** [comment]
@TCL735 thoughts on what is happening here?

**Comment by desa** [comment]
might be related to https://github.com/influxdata/influxdb/issues/18031

**Comment by Asalem1** [comment]
This looks like it should've been addressed here:

https://github.com/influxdata/influxdb/pull/18066

Should be out with the next Beta12 release. I'll leave this open until then

**Comment by desa** [comment]
@jpillora I believe beta12 has been released. Can you confirm that this behavior no longer exists there.

**Comment by jpillora** [comment]
Fixed. Though I did notice another bug in the same place. I believe `hh:mm` should be 12 hour time, however the x-axis still shows 24 hour time, with an AM/PM:
![image](https://user-images.githubusercontent.com/633843/85914371-65b66b80-b880-11ea-8373-4120879d9376.png)
![image](https://user-images.githubusercontent.com/633843/85914383-723ac400-b880-11ea-8e42-0c900fe1431d.png)

**Comment by Asalem1** [comment]
@TCL735
