### ISSUE TITLE
Server should disallow tags with name "time"

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#1834]
Those fields have special meaning to the database. Currently if a series has a tag named "id", the output of `show series` has two columns named "id":

```
{
    "results": [
        {
            "series": [
                {
                    "name": "random_measurement_0",
                    "columns": ["id","foo","host","id","region","time"],
                    "values": [
                        [1293,"bar6","server6","id_9","west","time_2"]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by pauldix** [comment]
I would expand this to say it should disallow tags and fields with those names. Also, it should disallow a field named `tags`

**Comment by nemesisdesign** [comment]
:+1: ran into an issue for this

**Comment by jsternberg** [comment]
I don't think this is an issue for "id" anymore, but it's definitely still an issue for "time". Any entry for "time" is unqueryable.
