### ISSUE TITLE
Write data from a URL

### ISSUE THREAD

**Issue by sanderson** [influxdata/influxdb#18349]
__Proposal:__
Extend the `influx write` command with the ability to write data from a URL.

__Current behavior:__
Right now you can only write line protocol or csv data from files or stdin.

__Desired behavior:__
Add a `-u`, `--url` parameter to the `influx write` command that grabs line protocol or csv from a remote HTTP endpoint.

__Use case:__
Easily write data from HTTP endpoints. For example, easily write CDC Covid-19 CSV data to InfluxDB:

```sh
influx write \
  -u https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/ecdc/full_data.csv \
  --header="#datatype dateTime:2006-01-02,tag,long,long,long,long"
```

**Comment by sranka** [comment]
I think that
```
curl -f https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/ecdc/full_data.csv | influx write --format csv ...
```
already works fine, doesn't it?

**Comment by sanderson** [comment]
When I try, I get the following error from `curl`:

```
curl: (23) Failed writing body (0 != 1371)
```

This indicates that `influx write` is closing the read pipe before `curl` is done piping data into it. This may be unique to macOS, but it's still an issue.

It would also be nice to support writing from URLs without an external dependency on `curl` or `wget`. The `influx pkg` (now `influx apply`) command supports this already with the `-u`/`--template-url` flag. @jsteenb2, could the URL fetching implementation be reused here?

**Comment by jsteenb2** [comment]
I think it'd be nice to separate them, I'm not sure what all the `-f` flag looks at the system only from what I can tell.  Identifying the URL as HTTP would have to be done here.  The stuff `pkger` does is not super useful to copy paste into this situation. I'd wager that having a separate `--url` flag would be more explorable 🤔.  If you want to use the `-f` flag to take remote in addition to local files you can check out the pkger implementation here:

https://github.com/influxdata/influxdb/blob/bc9b69b96f4d17b8658b62576cc38b0110188f49/pkger/service.go#L2870-L2901

**Comment by sanderson** [comment]
@jsteenb2 

> If you want to use the -f flag to take remote in addition to local files...

No, the [original proposal](#issue-630108262) is to introduce a `-u`/`--url` flag to the write command, not to allow the `-f` flag to handle both local and remote files. I was wondering if the mechanism for reading files from a remote http endpoint could be reused here to quickly add the `-u` flag.

**Comment by jsteenb2** [comment]
ahh gotcha. All pkger does it make an http request. Its the following:

https://github.com/influxdata/influxdb/blob/9ab44476170a651a46672f8338f01e72e94c4e29/pkger/parser.go#L116-L138

**Comment by sranka** [comment]
@sanderson thank you for sharing the motivation for doing this, there is no problem to enhance influx write with this

just FYI, the pipe failed because `influx write` encountered an error and stopped reading the data. If I run `curl` in the silent mode, I can better see what is wrong

```bash
$curl -f -s https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/ecdc/full_data.csv | ./influx write  --header="#datatype dateTime:2006-01-02,tag,long,long,long,long"
Error: Failed to write data: line 2: no measurement column found.
```

After I add measurement, it works fine.
```bash
curl -f https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/ecdc/full_data.csv | ./influx write  --header="#datatype dateTime:2006-01-02,tag,long,long,long,long" --header="#constant measurement, covid"
```

The pipe is a better solution comparing to what is now used in pkger, since it does not cache the whole CSV data in memory. Anyway, the implementation is easy.

**Comment by sanderson** [comment]
Ah, nice catch @sranka. Thanks for the follow-up.
