### ISSUE TITLE
Scatter Plot Graphs Need Y Axis Domain Padding

### ISSUE THREAD

**Issue by rawkode** [influxdata/influxdb#18360]
When using the scatter plot graph and "Auto" for "Y Axis Domain", the min and max are very specifically the min and max values within the data.

This can make regular data with consistent values very difficult to read.

I've attached 2 scatter plots, one with a yearly look at our products release cadence, and another with monthly.

In the yearly, due to the consistency of our releases, it's very difficult to read the points.

With the monthly, where things get a little more scattered, it's difficult to find the edge cases (when there are only a few)

![scatter-needs-padding](https://user-images.githubusercontent.com/145816/83741385-0b930380-a650-11ea-807e-e63f5c01e8e9.png)
![scatter-needs-padding-2](https://user-images.githubusercontent.com/145816/83741389-0c2b9a00-a650-11ea-9c52-e2eecc6940b1.png)

I think allowing for padding on the X Axis and enlarging the Y axis by a couple of points would safely allow all the points to fit in the graph in a way that can be explored more easily.

**Comment by drdelambre** [comment]
@TCL735 just triaging here... do you know if this is handled in giraffe or influxdb?
