### ISSUE TITLE
Don't reload query when opening a cell

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18401]
We should not refresh the query when opening a cell. We already have the results so we should just display them and not re-run the query or any dependent queries.

**Comment by ebb-tide** [comment]
@russorat one concern with the behavior this issue implies- 
Let's say we query the dashboard at time t for the past five minutes. and wait one minute before clicking 'configure cell'. 
The time dropdown in VEO will say "past five minutes" but will actually be displaying data between t-5 and t.
Is this what you would expect? or should we refetch data if data is 'too stale'

**Comment by russorat** [comment]
The x-axis will still display the correct time range. the user will know better than we will what "stale" is.
