### ISSUE TITLE
Cannot paste into flux editor in Safari

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#18422]
<img width="489" alt="Screen Shot 2020-06-09 at 5 02 14 PM" src="https://user-images.githubusercontent.com/1477539/84201040-8303d100-aa5c-11ea-8dd9-068b9db4f515.png">

The paste here does not work. In Chrome is it not available.

**Comment by desa** [comment]
cc @rbetts

**Comment by drdelambre** [comment]
desired outcome: we dont want the paste option to show up in the menu on safari

**Comment by zoesteinkamp** [comment]
![Screen Shot 2020-07-19 at 10.48.19 PM.png](https://images.zenhubusercontent.com/5e42e20611e3ce3816a90441/b2563da3-b89e-4e3a-8856-eea8fc329edb)![Screen Shot 2020-07-19 at 10.48.42 PM.png](https://images.zenhubusercontent.com/5e42e20611e3ce3816a90441/19a87e0f-6a06-49d1-918c-dec2420cbb7a)

This is going to be more hassle then its worth to fix. The big thing is safari seems to have the paste in the menu. But Chrome has it in the dropdown menu, and both allow you to do control+V and paste.
