### ISSUE TITLE
Wrong result after sort

### ISSUE THREAD

**Issue by cced-ats** [influxdata/influxdb#18433]
### Initial situation:
**Flux query**
from(bucket:"smarttool/rp_31d") |> range(start: 2020-06-07T23:00:00.000Z, stop: 2020-06-07T23:59:59.999Z) |> filter(fn: (r) => r._measurement == "AirTemperature")

**Result**
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string
#group,false,false,true,true,false,false,true,true
#default,_result,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement
,,0,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:05:07.693Z,11.5,temp,AirTemperature
,,0,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:15:30.503Z,11.7,temp,AirTemperature
,,0,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:30:23.246Z,12.2,temp,AirTemperature
,,0,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:40:22.597Z,11.9,temp,AirTemperature
,,0,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:50:22.855Z,12.1,temp,AirTemperature

### Then I want to mark one value as bad by write 'isBad=true' at time 2020-06-07T23:30:23.246Z
**Flux write**
AirTemperature isBad=true 1591572623246000000

### When I run the first query again the result looks fine
**Flux query**
from(bucket:"smarttool/rp_31d") |> range(start: 2020-06-07T23:00:00.000Z, stop: 2020-06-07T23:59:59.999Z) |> filter(fn: (r) => r._measurement == "AirTemperature")

**Result**
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string
#group,false,false,true,true,false,false,true,true
#default,_result,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement
,,0,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:05:07.693Z,11.5,temp,AirTemperature
,,0,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:15:30.503Z,11.7,temp,AirTemperature
,,0,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:30:23.246Z,12.2,temp,AirTemperature
,,0,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:40:22.597Z,11.9,temp,AirTemperature
,,0,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:50:22.855Z,12.1,temp,AirTemperature

#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,boolean,string,string
#group,false,false,true,true,false,false,true,true
#default,_result,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement
,,1,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,2020-06-07T23:30:23.246Z,true,isBad,AirTemperature

### Also when using the pivot function everything looks fine:
**Flux query**
from(bucket:"smarttool/rp_31d") |> range(start: 2020-06-07T23:00:00.000Z, stop: 2020-06-07T23:59:59.999Z) |> filter(fn: (r) => r._measurement == "AirTemperature") |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") 

**Result**
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,string,double,boolean
#group,false,false,false,true,true,true,false,false
#default,_result,,,,,,,
,result,table,_time,_start,_stop,_measurement,temp,isBad
,,0,2020-06-07T23:05:07.693Z,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,AirTemperature,11.5,
,,0,2020-06-07T23:15:30.503Z,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,AirTemperature,11.7,
,,0,2020-06-07T23:30:23.246Z,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,AirTemperature,12.2,true
,,0,2020-06-07T23:40:22.597Z,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,AirTemperature,11.9,
,,0,2020-06-07T23:50:22.855Z,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,AirTemperature,12.1,

### But if I add a sort then it goes wrong:
**Flux query**
from(bucket:"smarttool/rp_31d") |> range(start: 2020-06-07T23:00:00.000Z, stop: 2020-06-07T23:59:59.999Z) |> filter(fn: (r) => r._measurement == "AirTemperature") |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") |> sort(columns: ["_time"], desc: true)

**Result**
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,string,double,boolean
#group,false,false,false,true,true,true,false,false
#default,_result,,,,,,,
,result,table,_time,_start,_stop,_measurement,temp,isBad
,,0,2020-06-07T23:50:22.855Z,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,AirTemperature,12.1,
,,0,2020-06-07T23:40:22.597Z,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,AirTemperature,11.9,false
,,0,2020-06-07T23:30:23.246Z,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,AirTemperature,12.2,
,,0,2020-06-07T23:15:30.503Z,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,AirTemperature,11.7,
,,0,2020-06-07T23:05:07.693Z,2020-06-07T23:00:00Z,2020-06-07T23:59:59.999Z,AirTemperature,11.5,false

**InfluxDB version 1.8.0**

**Comment by jsternberg** [comment]
I'm closing this because we merged a fix, but this fix is going to be in v0.72.0 of Flux and we're going to try to get that version into the 1.x line of influxdb in the near future.

Fixed by influxdata/flux#2956.
