### ISSUE TITLE
Don't reload query when closing a cell

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18455]
similar to https://github.com/influxdata/influxdb/issues/18401

we already have the results, so there's no need to re-run the query when closing a dashboard cell editor modal.

**Comment by Asalem1** [comment]
@russorat more specifically, did you want us to not reload the one cell that was closed, or did you want to not reload all the queries when closing a cell?

**Comment by russorat** [comment]
@Asalem1 We should definitely not rerun every query on the dashboard when they close a cell in most cases.

At a high level, we should only re-run queries automatically when absolutely needed. If there is larger re-work in patterns to accomplish this instead of a bandaid, let's consider it.

 - User made changes to their query in the cell editor but did not re-run the query before closing
  - We need to re-run the query when they save & close the cell to reflect their changes
  - If they clicked the red x to cancel their changes, we should display the previous result prior to opening the cell, so there shouldn't be a re-query in this case.
 - User made change to the variables or time range in the cell editor
  - In this case, we probably automatically re-ran their query for them in the cell editor (we do so when they change time range or variable values), but when they close the cell, those changes to variable values and time range are changed for the entire dashboard. That would mean we need to refetch all the visible cells on the dashboard EXCEPT the one they were editing (since we already ran that one).

Are there other scenarios we should consider here?

**Comment by Asalem1** [comment]
I think you just about covered it. I'll post more here if I can think of any other use cases

**Comment by Asalem1** [comment]
This should be addressed in #19010 (given that the configuration event is within the valid time range of cache validation)
