### ISSUE TITLE
h:mm a time format is not a 12-hour time

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#18458]
Link https://github.com/influxdata/influxdb/issues/15906#issuecomment-642732574

I was showing visualisations to a colleague today, and we noticed that "h:mm a" isn't working.
<img width="397" alt="image" src="https://user-images.githubusercontent.com/27981402/84405135-aa46d380-abff-11ea-951d-1e5919c1ea78.png">
You'll notice that, although it has PM, it's still 24-hour time instead of 12-hour time

**Comment by desa** [comment]
cc @r1ckbrown

**Comment by Asalem1** [comment]
@desa I think the issue here is that JS relies upon the browser's locale for time format. We have some logic in giraffe to handle this, but I am curious to know if the timezone dropdown was set to `local` or `UTC` since I can't seem to reproduce this with an `en-US` locale

**Comment by r1ckbrown** [comment]
Unfortunately, it's both local and UTC time zones:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/27981402/84430704-00c50980-ac22-11ea-942e-8f05d5798ee6.png">
<img width="439" alt="image" src="https://user-images.githubusercontent.com/27981402/84430731-0de1f880-ac22-11ea-8583-92b5b6957745.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/27981402/84430763-19cdba80-ac22-11ea-98ae-e56831e36d64.png">

I'm running Firefox on Mac, in case it helps.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/27981402/84430885-441f7800-ac22-11ea-9708-b896d742b883.png">
