### ISSUE TITLE
Cloning tasks makes actions shared in task list view

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#18478]
![task_clone_bug](https://user-images.githubusercontent.com/17263167/84475885-24984780-ac42-11ea-9eb4-458832dbd842.gif)

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. create a task
2. clone the task
3. hit slider on the new task clone

__Expected behavior:__
To have individual slider moving, not as a collective.

__Actual behavior:__
Both clone and origin are moving

__Environment info:__

System: Darwin 18.7.0 x86_64
Browser: FF

**Comment by drdelambre** [comment]
seems to clone the entire object locally, including the id of the original.
frontend only issue, as the behavior doesn't survive a refresh
