### ISSUE TITLE
How to bind json response to object

### ISSUE THREAD

**Issue by psclkhoury** [influxdata/influxdb#18500]
The response from a query has the form

```json
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "name",
                    "columns": [
                        ...
                    ],
                    "values": [
                        ...
                    ]
                }
            ]
        }
    ]
}
```
Is there a way to change the returned format so that it can be easily deserialized into a typed object? If not then what is the recommended way to achieve this?

I am using c# with newtonsoft and usually I can just deserialize the json into a class.

**Comment by russorat** [comment]
@psclkhoury your best bet is to use one of the client libs: https://github.com/influxdata/influxdb-client-csharp
