### ISSUE TITLE
Docker tag

### ISSUE THREAD

**Issue by qm3ster** [influxdata/influxdb#18502]
[`v2.0.0-beta.12`](https://github.com/influxdata/influxdb/releases/tag/v2.0.0-beta.12) release mentions `docker pull quay.io/influxdb/influxdb:2.0.0-beta`, but that still points to d00706d([beta.10](https://github.com/influxdata/influxdb/releases/tag/v2.0.0-beta.10))

**Comment by mildebrandt** [comment]
Happy Tuesday! Can we get some eyes on this one? Maybe @russorat can help?

**Comment by russorat** [comment]
investigating

**Comment by russorat** [comment]
We have updated the docker image to point to the latest release. thank you for letting us know!
