### ISSUE TITLE
InfluxDB Cloud: single stat stopped working for non-numeric data

### ISSUE THREAD

**Issue by melanchall** [influxdata/influxdb#18501]
__Steps to reproduce:__

1. Have a meausurement with string tag
2. Create dashboard cell with Single Stat visualization
3. Use query to select that string tag

__Expected behavior:__

Single string value displayed.

__Actual behavior:__

**NaN** displayed.

__Additional info:__

It worked fine yesterday (June 13) but today Single Stat for string is suddenly broken.

I use this query:

```
from(bucket: "XXX")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "yyyy" and r["_field"] == "zzz")
  |> group(columns: [])
  |> map(fn: (r) => ({ version: r.version }))
  |> sort(columns: ["version"])
  |> last(column: "version")
```

If we use Table visualization, we'll see:

![image](https://user-images.githubusercontent.com/26361185/84575400-70b7c900-adb5-11ea-841c-d9ffc8480432.png)

All looks fine.

Then switch to Single Stat:

![image](https://user-images.githubusercontent.com/26361185/84575448-b1174700-adb5-11ea-9cee-55f282fa3bc3.png)

**Comment by russorat** [comment]
@melanchall thanks for the issue. I think this should be fixed now if you'd like to confirm.

**Comment by melanchall** [comment]
Yes. now it's fixed.
