### ISSUE TITLE
Influx client should handle line continuation or statement termination

### ISSUE THREAD

**Issue by cogitaria-admin** [influxdata/influxdb#18533]
__Proposal:__
Accept a line continuation character or statement terminator.

__Current behavior:__
The shell tries to parse and execute incomplete statements when the user hits the Enter key, usually resulting in an error.

__Desired behavior:__
Accept a line continuation character or require a statement terminator such that newlines do not trigger evaluation of incomplete commands. 

__Alternatives considered:__
There are no reasonable alternatives. This is clearly an issue that exists with any command line input parser/interpreter since the dawn of terminals.

__Use case:__
This is important because virtually every user is frustrated when starting to use the Influx shell when they enter a clearly documented query, for example, and the shell displays an error when the user hits the Enter key.  Next, they will try line continuation \ which is standard.  When that fails, they will google the reason since it seems rather intuitive that it should work, so perhaps there's another way.  In fact there isn't, so you finally end up taking your query examples and joining together all of the lines into an illegible mess, then paste the result into the shell.

**Comment by russorat** [comment]
@cogitaria-admin this makes a ton of sense. thank you.

**Comment by longtian** [comment]
googling "influxdb multiline" for hours and just ended here like @cogitaria-admin  predicted

> 
> **Use case:**
> This is important because virtually every user is frustrated when starting to use the Influx shell when they enter a clearly documented query, for example, and the shell displays an error when the user hits the Enter key. Next, they will try line continuation \ which is standard. When that fails, they will google the reason since it seems rather intuitive that it should work, so perhaps there's another way. In fact there isn't, so you finally end up taking your query examples and joining together all of the lines into an illegible mess, then paste the result into the shell.

**Comment by DStrand1** [comment]
This issue is fixed as of our new CLI tool, located here: https://github.com/influxdata/influx-cli. It accepts `\` for a line continuation character as expected
