### ISSUE TITLE
Add the ability to update stack metadata

### ISSUE THREAD

**Issue by sanderson** [influxdata/influxdb#18548]
__Proposal:__
Add the ability to update stack metadata such as name and description. Something like:

```sh
influx stacks update --stack-id=xxxxx -n stack-name -d 'stack description'
```

__Current behavior:__
Currently you can only add a name and description when manually initializing a stack. There's no way to update them after a stack is created.

__Desired behavior:__
The ability to update stack metadata.

__Use case:__
- Providing a name and description for an auto-initialized stack
- Correcting mistakes in a stack name or description

**Comment by jsteenb2** [comment]
ohhh gimme gimme. This is the last missing bits for stacks 👍
