### ISSUE TITLE
cancel query button flashes on fast queries

### ISSUE THREAD

**Issue by drdelambre** [influxdata/influxdb#18543]
![Kapture 2020-06-16 at 13 05 39](https://user-images.githubusercontent.com/1434802/84823344-067c6f80-afd3-11ea-93e0-24a295d85e7d.gif)

for queries that resolve quickly, this happens ^^^

maybe we could address it with something like this?
https://github.com/influxdata/influxdb/pull/18447

**Comment by desa** [comment]
Add additional state so that the button will be disabled before transitioning into cancel for some number of milliseconds
