### ISSUE TITLE
Query builder giving strange results

### ISSUE THREAD

**Issue by drdelambre** [influxdata/influxdb#18567]
No idea how to scope the scale of this issue, as it seems we just have one in a bad state, but it's a pretty bad state.

when we have a query that looks like this:
```
[
  {
    "text": "from(bucket: \"project\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)",
    "editMode": "builder",
    "name": "",
    "builderConfig": {
      "buckets": [
        "project"
      ],
      "tags": [
        {
          "key": "_measurement",
          "values": [
            "pressure"
          ],
          "aggregateFunctionType": ""
        },
        {
          "key": "_field",
          "values": [
            "value"
          ],
          "aggregateFunctionType": ""
        }
      ],
      "functions": [],
      "aggregateWindow": {
        "period": "auto"
      }
    }
  }
]
```
data explorer is only sending something that looks like the raw query text above, and not the query that should be assembled from the builder options. Makes the user download their whole bucket just to have the graph crash

**Comment by drdelambre** [comment]
reset the user's local instance by completely rebuilding the query in builder mode
interesting note, on returning to the dashboard from a save, the cell crashed on into an error boundary.

**Comment by Asalem1** [comment]
@drdelambre which cluster is this happening in? Any chance it's related to variable hydration?

**Comment by drdelambre** [comment]
@Asalem1 it was happening in a user's production instance (eu cluster iirc). shouldn't be related, and if it is, it shouldnt be related
