### ISSUE TITLE
LSP crashes on tag auto complete

### ISSUE THREAD

**Issue by drdelambre** [influxdata/influxdb#18575]
when any kind of latency is introduced to the page (network speed, network load, overloaded ui thread, server load, large number of measurements, etc) the LSP will stop working until a page refresh because of a timeout within Rust expiring. The error code looks a bit like this:

<img width="623" alt="Screen Shot 2020-06-17 at 11 50 40 AM" src="https://user-images.githubusercontent.com/1434802/84939352-1065a780-b093-11ea-8c67-8db3268afdb8.png">

related: influxdata/idpe#7664

**Comment by desa** [comment]
@bthesorceror any thoughts on what we can do here?

**Comment by drdelambre** [comment]
closing in favor of https://github.com/influxdata/influxdb/issues/18638
