### ISSUE TITLE
Separate the CLI tooling from the main influx repo

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18609]
The `influx` tool is growing to a state where it makes sense to treat it as its own product with the goal of supporting the entire InfluxDB 2.0 API running anywhere.

Moving the CLI to its own repo will make it easier to keep it up to date with our cloud apis as well as the OSS APIs. It will also open up the option to version it separately from OSS.

**Comment by rbetts** [comment]
If other implementations (other than a new repo) solve the worklfow and versioning issues, they are also of course open for consideration. 

I don't understand the dependency graph for the CLI - though naively - it wouldn't seem _too_ different from any other client. Which is maybe a good argument for separating into a repo, as that's how the clients are organized.

**Comment by danxmoran** [comment]
I'd give a :+1: to separating out the client.

Code-wise, the biggest "benefit" I see to having the 2 binaries in one repo is that it's easy for the CLI to reuse server-side model definitions. Unfortunately that often causes us to miss differences between our Swagger API and actual implementation. Moving the client out and switching it to use models/HTTP clients codegen'd from Swagger would help us stay honest.

**Comment by danxmoran** [comment]
The work to split out the CLI has completed, see the new stand-alone implementation at https://github.com/influxdata/influx-cli/
