### ISSUE TITLE
influx CLI: invalid flags are simply ignored; no error/warning given

### ISSUE THREAD

**Issue by wfjm** [influxdata/influxdb#18629]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. `docker run ... quay.io/influxdb/influxdb:2.0.0-beta`
2. `docker exec -it influxdbv2 bash`
3. `influx ping --badflag`

__Expected behavior:__
When _influx_ is called with invalid flags the command should be abort with a proper error message.

__Actual behavior:__
The invalid flag is simply ignored
```
influx ping --badflag  
OK
```
__Environment info:__

* System info: Run `uname -srm`: Linux 5.3.0-51-generic x86_64
* InfluxDB version: Run `influxd version`: Influx CLI 2.0.0-beta.12 (git: ff620782eb)
* Other relevant environment details: Container runtime: docker

**Comment by jsteenb2** [comment]
hi @wfjm thanks for the issue 👍. Can you share the exact error message you are receiving?

**Comment by wfjm** [comment]
The point is that _no error message_ is given, invalid flags are simply ignored.
This is a bit unusual for CLI tools, usually they complain about invalid flags.
Good practice to catch typos.

**Comment by jsteenb2** [comment]
that's fair, we've had user requests to explicitly remove the error when providing flags that aren't expected. They basically get ignored silently.
