### ISSUE TITLE
Influx CLI - allow bucket creation RP in 'd' units (days)

### ISSUE THREAD

**Issue by abalone23** [influxdata/influxdb#18639]
__Proposal:__
Allow for buckets to be created with a retention policy in days "d" units. Note that in 1.x, duration units include days **d** and weeks **w** as well:
https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#durations

__Current behavior:__
```
./influx bucket create -n testbucket -r 10d
Error: invalid argument "10d" for "-r, --retention" flag: time: unknown unit d in duration 10d
```

__Desired behavior:__
I would like for the "d" unit to be recognized when creating a bucket since it's typical to create RP in days, like 7d, 30d etc.

__Alternatives considered:__
Convert days to hours and use 'h' unit instead.

__Use case:__
Since most people create RPs in terms of days, this would eliminate having to convert to hours and be less confusing.

**Comment by jsteenb2** [comment]
I went ahead and added weeks as well to the CLI durations supported. Weeks will land in this PR: https://github.com/influxdata/influxdb/pull/18659
