### ISSUE TITLE
Add ability to associate net new resources with stack-id on export

### ISSUE THREAD

**Issue by samhld** [influxdata/influxdb#18646]
__Proposal:__
Add the ability to associate newly created resources while exporting them.  This could look like:
`influx export --dashboards <dash id> --labels <label id> <label id> --stack-id <stack id>`

__Current behavior:__
Imagine a scenario where a user has already applied a template and associated the contained resources to a stack.  Now they want to add a new resource (not update an existing one).  They want to then export these new resources and add them to their already-created template manifest file as well as the associated stack.

Currently, even with a stack already initialized, the user must run `influx apply <manifest> --stack-id` to associate new resources with a particular stack.  

This seems like strange behavior for two reasons:
1) The user must first export the new resources (created in the instance) and *then* apply them to the stack.
2) These resources are already present in the UI because they were created there.  It seems redundant to `influx apply` when there is nothing new to add or update in the target instance.

__Desired behavior:__
To be able to associate the output of an export to a stack in the same command.  This will go hand-in-hand with being able to simply update a manifest file as opposed to having to append to it manually.

**Comment by jsteenb2** [comment]
in addition, we'll add a flag that does the actual updating of the association with the stack.

```
influx export --update-stack --stack-id $STACK_ID --dashboard $DASH_ID
```

behavior without flag is to just export the stack and the dashboard as a single output. The flag is provided and then the stack is updated to include the dashboard and its new metadata.name/resource ID mapping.
