### ISSUE TITLE
Platform variable selected scoping

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#18668]
__Proposal:__

The ability to scope variable's selected values at different levels.

To illustrate some limitations, an example:

* I create a variable in a dashboard and select value foo as the default
* i then create a task that utilizes said variable and is relying on the selected value as it were
* I then update the variable selected value (via API atm) to be bar
* Now tasks are looking at the wrong thing
* Also, the dashboard view is changed to use bar

The proposed change's impact on the scenario above:

* I create a variable in a dashboard and select value `foo`
   * the global variable is updated with `foo` as the selected value
   * the dashboard selected value (stored on dashboard/or query/perhaps both) is set to `foo`
* i then create a task that utilizes said variable and is relying on the selected value as it were
   * the task selected value (stored on dashboard/or query/perhaps both) is set to foo
* I then update the variable selected value (via API atm) to be bar in the dashboard
  * the dashboards local selected value is updated to `foo`
  * global var selected fields are unchanged
  * task is unchanged

To maintain backwards compatibility with existing functionality, global changes affect everything:
* add ability to update selected value on global variable and cascade changes to all associated 

__Current behavior:__
Changing variable selected valeu in one palce affects all places

__Desired behavior:__
Selecting values independent locals

__Alternatives considered:__
I'm not sure 🤔 

__Use case:__
A big place where this comes up is Templates. There are a lot of common variables like `bucket` variable, that has shared values of buckets, but we want to provide different selected values. This collision happens a fair bit b/c of bucket variable specifically.

**Comment by russorat** [comment]
A few comments here:

> Now tasks are looking at the wrong thing

Tasks do not support variables from the UI today.

> I then update the variable selected value (via API atm) to be bar

I don't understand the value of doing this. if a variable changes and no one is looking at the dashboard, who cares?

> the dashboard selected value (stored on dashboard/or query/perhaps both) is set to foo

I do not believe variable values are stored with the dashboard today. I believe they are stored in the user's browser cache.

**Comment by jsteenb2** [comment]
@russorat correct on all accounts. Templates can set the selected values for a variable. I was trying to illustrate a scenario that didn't involve templates per say, but that failed miserably...
