### ISSUE TITLE
only displaying 20 notification rules

### ISSUE THREAD

**Issue by harel-ecoplant** [influxdata/influxdb#18684]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create 21 notification rules
2. ...
3. ...

__Expected behavior:__
be able to view / edit / delete all the notification rules

__Actual behavior:__
can view / edit only 20 notification rules, also filter only works o
<img width="958" alt="NOTIFICATIONRULES2" src="https://user-images.githubusercontent.com/62518155/85528803-0ef92980-b615-11ea-9ad4-a69b5db41a58.png">
n the displayed 20

**Comment by russorat** [comment]
@harel-ecoplant thanks for the issue. We will take a look.
