### ISSUE TITLE
Filtering/grouping by time of day -- possible?

### ISSUE THREAD

**Issue by aldanor** [influxdata/influxdb#1871]
Sorry if this has been asked before but I couldn't find a particular issue on github and couldn't find anything in the docs.

Does influxdb support queries of a kind "select all events between 2am and 4am on each day in the time range"? This is a very common use case in time series analysis (particularly so when dealing with market data).

**Comment by nlsrchtr** [comment]
This would be really great to answer simple questions like: which is the busiest hour of the day, day of the month or month of the year. I would really like to see a support of this. Thanks for your reconsideration.

**Comment by beckettsean** [comment]
folding into https://github.com/influxdata/influxdb/issues/6723 which is a bit more detailed
