### ISSUE TITLE
Flows: User can run Flow without saving out results to system

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#18719]
As an early access user of Flows, I can run a Flow with an input/output and see results without executing that resource so that I can preview what I'm building in Flows.

Scenario: Ability side-effects in flowbooks

GIVEN: I have a Flow with a valid input cell (bucket, tag, etc)
AND a valid output cell (write to bucket, run a task)
WHEN: `Run Flow`
THEN: replace `TO` function with a `YIELD`
AND: I see the results of the Flow

**Comment by alexpaxton** [comment]
Closing this issue after discussing it with @mnorriswalker - it's a good idea but not essential for early access
