### ISSUE TITLE
Influxdb 2.0.0-beta.12 with nginx reverse proxy

### ISSUE THREAD

**Issue by jaysnm** [influxdata/influxdb#18716]
First and foremost I thank Influxdata team for their sparkling products, in particular influxdb and telegraf. While trying the beta version of influxdb I encountered an error creating dashboard. I repeated *create dashboard from template* three times. All failed with service unavailable errors. I logged out, cleared browser data and logged back. Cards of the the three dashboards I created showed. Opening any of them printed below errors. My Telegraf is properly configured for both input and outputs.
**Nginx access logs**
 ```
 [25/Jun/2020:00:29:54 +0300] "PATCH /api/v2/dashboards/05e60e8889e70000/cells/05e60e88a4670000/view HTTP/1.1" 444 0 "http://localhost/orgs/05e4e658012e8000/dashboards" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" "-"
102.68.77.26 - - [25/Jun/2020:00:29:54 +0300] "PATCH /api/v2/dashboards/05e60e8889e70000/cells/05e60e889ba70000/view HTTP/1.1" 444 0 "http://localhost/orgs/05e4e658012e8000/dashboards" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" "-"
```
**Browser UI and logs** 
![image](https://user-images.githubusercontent.com/20385376/85633911-f0ca1280-b682-11ea-97c6-18ef4912ba2a.png)

I'm using  quay.io/influxdb/influxdb:2.0.0-beta image `Influx CLI 2.0.0-beta.12 (git: ff620782eb) build_date: 2020-06-24T21:45:25Z`  

**Telegraf logs**
```
Starting Telegraf 1.14.4
2020-06-24T22:02:48Z I! Using config file: /etc/telegraf/telegraf.conf
2020-06-24T22:02:48Z I! Loaded inputs: system docker postgresql nginx cpu disk mem swap diskio net processes docker_log influxdb
2020-06-24T22:02:48Z I! Loaded aggregators: 
2020-06-24T22:02:48Z I! Loaded processors: 
2020-06-24T22:02:48Z I! Loaded outputs: influxdb_v2
2020-06-24T22:02:48Z I! Tags enabled: host=e00cbbd3c2d4
2020-06-24T22:02:48Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"e00cbbd3c2d4", Flush Interval:10s
```

I also wonder milestones made towards [ issue #15721 ](https://github.com/influxdata/influxdb/issues/15721). I followed [issue #5352](https://github.com/influxdata/influxdb/issues/5352) which led me to [this gist](https://gist.github.com/mvadu/5fbb7f5676ce31f2b1e6). Using the gist, I configured the server as below resolving all requests to /influxdb/.
``` 
http {
  [....]
  map ... [ ...]
}
location /influxdb/ {
        proxy_pass http://localhost:9999/;
        [.....]
  }
```
{I think} all static files resolved and /api/v2/flags. I expected to see api/v2, api/v2/setup and /signin in network logs.

![image](https://user-images.githubusercontent.com/20385376/85633694-6d102600-b682-11ea-89be-6cda78bdca50.png)

What could I be doing wrong here? **My working set-up uses / and not /influxdb/**
Thanks in advance.

**Comment by russorat** [comment]
@jaysnm thanks for the issue. Sorry for the delay in responding. Is this still an issue with beta-15?

**Comment by jaysnm** [comment]
Thank @russorat for reverting. It's no longer and issue.
