### ISSUE TITLE
 Provide ability to export by name for all resources

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#18733]
as a user,
I want to export resources by name to a template,
so I don't have to juggle UUIDs myself

**Acceptance Criteria**

- [ ] ability to export via CLI by name and or id

```sh
$ influx export --label=UUID --label="Name of label" ...
```

- [ ] support through the API by extending the `POST /api/v2/packages` with the following:

```json
{
   ...existing,
   "resources": [
       {
            "kind": KIND,
            "resourceID": UUID,
            "resourceName": RES_NAME,
            "rename": NEW_NAME_IN_TEMPLATE
       }
    ]
}
```

resourceName will be the identifer to match by. If an ID and or Name is provided it will match on that. At least 1 of resourceID or resourceName will be required

**Comment by desa** [comment]
If a resource has a duplicate name, both resources with that name should be exported.
