### ISSUE TITLE
Variable lookups with bracket lookups don't work on dashboards

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#18739]
To reproduce try viewing

```
bucket = v["bucket"]

from(bucket: bucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
```

in a dashboard. While the query builder the query will execute just fine.

The root cause here is that the variable matcher we have today only detects variables described by `v.<varname>` and do not catch `v["<varname>"]`

**Comment by drdelambre** [comment]
postponing this one to wait for better support by the flux wasm in this issue
https://github.com/influxdata/influxdb/issues/18834
