### ISSUE TITLE
import csv: add the option to fail the import if datatype is a long and a float is in the data

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18744]
```
t,f
my_tag,1
my_tag,1.9
```

right now, both of these work:
```
➜  influxdb git:(master) ./bin/darwin/influx write dryrun -f ~/Downloads/float.csv --header "t|tag,f|long" --header "#constant measurement,m" --skipHeader
m,t=my_tag f=1i
m,t=my_tag f=1i
➜  influxdb git:(master) ./bin/darwin/influx write dryrun -f ~/Downloads/float.csv --header "t|tag,f|double" --header "#constant measurement,m" --skipHeader
m,t=my_tag f=1
m,t=my_tag f=1.9
```

as a user, I would like a way to fail the import if i have a column marked as a long and a float value is truncated. possibbly via a `--strict` flag? Also, in all cases, I would expect a warning printed similar to the case of multiple date fields indicating a loss of precision.

**Comment by sranka** [comment]
#18779 let you specify the strict mode in a dataFormat part, the example then fails when using `--header "t|tag,f|long:strict"`
