### ISSUE TITLE
import csv: add ability to extract data from comment lines

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18743]
Here is an example CSV file that contains a set of comments at the top of the file with additional information.

```
#,widget,identifier,234234234
#,widget,name,My name
#,Start,date,2020-05-22
#,End,date,2020-06-22

timestamp,tag,value
2020-05-22 00:00:00,my_tag,0
2020-05-22 00:05:00,my_tag,1
2020-05-22 00:10:00,my_tag,2
```

As a user, I would like a way to extract information from those comments at the top of the file into a field or a tag in an automated way.  currently, these would need to be hardcoded like so:

```
influx write -f my.csv --skipHeader=6 --header "#constant tag,identifier,234234234" --header "#constant tag,name,My name" --header "#constant string,start,2020-05-22" --header "#constant string,end,2020-06-22"
```

I could imagine the use of regexp matching groups to extract meaningful information, or providing an extraction template of some sort for a given header line, but open to other ideas.

**Comment by sranka** [comment]
This request is entering a wide area of file pre-processing/transformations. I tend to believe that we should better rely on other tools (sed, awk, csvkit, csvtk, ... ) to compose/automate a solution from multiple independent steps. Even the existing tabular processors (excel, libreoffice write, google sheets) might be a better choice in many cases, they contain the scripting capabilities that help to create new sheets from existing sheets in a WYSIWYG way.

Supplying regexp or script is a way much harder to debug when compared to replacing the whole headers :thinking: I have to think this over.

**Comment by sranka** [comment]
@russorat I still think that we should better rely upon 3rd party tools to transform such CSV files, they have better overall support (documentation, existing examples, community, tutorials etc.). Can you please provide a rationale/context/situation in which a new solution in `influx write` would be better?

**Comment by russorat** [comment]
I'm ok with that solution. Could you add an example of how you would do that for the data provided and we can add it to our documentation? fyi @sanderson

**Comment by sranka** [comment]
The example (stored as data.csv) can be processed using [sed](https://en.wikipedia.org/wiki/Sed) to create an input that is then piped to influx write:

```
sed --posix -E \
 -e 's/#,widget,([^,][^,]*)(..*)/#constant tag,\1\2/' \
 -e 's/#,Start,date,(.*)/#constant string,start,\1/' \
 -e 's/#,End,date,(.*)/#constant string,end,\1/' \
 -e '5i\#constant measurement,my-measurement' \
 -e '6s/.*/timestamp|dateTime:2006-01-02 15:04:05,tag|tag,value|double/' \
 data.csv \
| influx write dryrun --format csv
```

produces:
```
my-measurement,identifier=234234234,name=My\ name,tag=my_tag value=0,start="2020-05-22",end="2020-06-22" 1590105600000000000
my-measurement,identifier=234234234,name=My\ name,tag=my_tag value=1,start="2020-05-22",end="2020-06-22" 1590105900000000000
my-measurement,identifier=234234234,name=My\ name,tag=my_tag value=2,start="2020-05-22",end="2020-06-22" 1590106200000000000
```

Sed breefly explained:
  - -e add an expression command (*s* - regexp replacement or every matching line, *5i* - insert to line 5,*6s* replace matching regexp on line 6)
 - -E turns on extended regular expressions, these are required for back-references (\1 and \2)
 - --posix was added for portability between various editions of sed; it can be omitted and _[^,][^,]*_ could be simply =[^,]+= in the most sed distributions

The intermediate results of sed is:
```
#constant tag,identifier,234234234
#constant tag,name,My name
#constant string,start,2020-05-22
#constant string,end,2020-06-22
#constant measurement,my-measurement

timestamp|dateTime:2006-01-02 15:04:05,tag|tag,value|double
2020-05-22 00:00:00,my_tag,0
2020-05-22 00:05:00,my_tag,1
2020-05-22 00:10:00,my_tag,2
```
