### ISSUE TITLE
import csv: add the ability to construct a timestamp from multiple columns

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18741]
Here is an example CSV:

```
Date,Time,Tag,Value
2020-05-22,00:00:00,test,0
2020-05-22,00:05:00,test,1
2020-05-22,00:10:00,test,2
```

I would like a way to combine multiple time columns into a single timestamp to be used on the import. In this case, the resulting line protocol timestamps would combine the `Date` and the `Time` column to produce:

```
1590105600000000000
1590105900000000000
1590106400000000000
```

other example CSVs that should be able to be parsed with this solution:
```
Year,Month,Day,Hour,Minute,Second,Tag,Value
2020,05,22,00,00,00,test,0
2020,05,22,00,05,00,test,1
2020,05,22,00,10,00,test,2
```

the current behavior prints a warning:
`2020-06-25T21:47:08.731185Z	info	WARNING: at most one dateTime column is expected, 'date' column is ignored`

**Comment by sranka** [comment]
The same thoughts as in https://github.com/influxdata/influxdb/issues/18743#issuecomment-650491417 apply herein. I am thinking of adding another annotation that would add a computed column from existing columns (and constant values) as a solution. Something like
```
#computed,date|dateTime:dateTime:2006-01-02|"{{row ""Year""}}-{{row ""Month""}}-{{row ""Day""}}"
```
The original columns can be then ignored during csv import.
