### ISSUE TITLE
Edit this notification rule condition will cause "An InfluxDB error has occurred. Please report the issue"

### ISSUE THREAD

**Issue by gomazu** [influxdata/influxdb#18770]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Cloud2 (edit "this notification rule) > (condition)
2. ...
3. ...

__Expected behavior:__
The condition would change

__Actual behavior:__
"An InfluxDB error has occurred. Please report the issue" error message. 

__Environment info:__
cloud2 
browser safari 
Mac OS build 10.15.5
* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by gomazu** [comment]
![Screen Shot 2020-06-28 at 1 40 24 AM](https://user-images.githubusercontent.com/63891737/85942861-fc1a7980-b8e0-11ea-88a4-f511ac62cbd8.png)

**Comment by Asalem1** [comment]
@gomazu are you still experiencing this issue? I can't seem to reproduce it locally or on production. Do you happen to have any specifics on the notification rule you are trying to edit? Are there any console errors that are showing up? Any additional information would be really helpful in trying to tackle this issue ASAP

**Comment by Asalem1** [comment]
After talking with Marc about this, it doesn't seem like it's an issue. It could be that the issue was data-related, but Marc had since deleted the relevant bucket so he can't reproduce it at this time. I'm gonna mark this issue as closed but will be monitoring the situation in case it crops up again
