### ISSUE TITLE
Cache queries made in dashboard and VEO

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#18791]
writing to the cache
- [x] On dashboard page, when query is issued for cell, query results should be cached in redux store. cache is keyed by externs and query text. 
- [x] On dashboard page, when VEO is visible, when query is issued in VEO, query results should be cached in redux store.  queries cached in VEO should 'expire' after a few minutes. 
---
invalidating cache:
- [x] When user navigates away from a dashboard, the query cache should be invalidated/cleared so that when user navigates to the same dashboard again, cells are re-queried.
- [x] When a dashboard loads for the first time, all queries must query the database directly and not the cache
- [x] On dashboard Page, when viewing cells, the `reload` button should invalidate the cache and re-query for all cells. 
- [ ] In Autoreload(OSS)
- [ ] When user clicks submit. 

--- 
reading from cache:
- [x] On dashboard page, when user clicks on `configure` to edit cell query, the VEO should load and display query results from the cache. (this is already done) 
- [x] On dashboard page, when user clicks 'cancel' on VEO, background dashboard cells should attempt to query, but results should resolve from the cache, user should see dashboard as it was before they launched VEO even if they had selected a different time range or variable value in the VEO. 
- [x] On dashboard page, when user clicks 'save' on VEO without having ever submitting the query in the VEO (by clicking submit or changing variable value/time range), background dashboard cells should attempt to query, but results should resolve from the cache, user should see dashboard as it was before they launched VEO. 
- [x] On dashboard page, when VEO is visible, background dashboard cells should not attempt to query, even when time windows/variable values change.  (in PR)
- [x] On dashboard page, when user clicks 'save' on VEO, if user had resubmitted query in VEO, either by clicking submit, or changing query/variables/timeRange- all cells on dashboard should re-query. The edited cell should receive results from cache if it has not expired.

**Comment by Asalem1** [comment]
Here's the first issue I figured we could tackle:

#18929

**Comment by Asalem1** [comment]
Need to reset query's based on IDs when a query is submitted in the VEO

**Comment by russorat** [comment]
> Need to invalidate the cached data after 5s

this should be easy to change.

**Comment by Asalem1** [comment]
> > Need to invalidate the cached data after 5s
> 
> this should be easy to change.

Famous last words 😃 

Those were just mental notes that are already addressed in the PR linked to this:

#19010
