### ISSUE TITLE
a way to specify the number of datapoints to return over a given time interval

### ISSUE THREAD

**Issue by m-mcgowan** [influxdata/influxdb#188]
When plotting a graph (on a remote client), ideally the data would have as many data points defined as the display resolution. 

While at present data can be fetched by time range (start/end) and aggregated over a given time interval (s, m etc.), this can give less than ideal rendering in a graph due to the number of data points not exactly matching the display resolution.

In some cases it's possible to compute the required aggregation interval so that the range requested ends up producing exactly the number of points needed. E.g. if we have a time range of 1 hour and want to get 240 points for display, then the aggregation interval would be 0.25s.   But my concern is that in some cases rounding errors may mean we get one data point too few or too many. (Of course, this can be coded around by artificially increasing the number of points 1 or 2 beyond what is required and discarding any extra. so there is always sufficient points for the graph.)

I'm airing this to see what you think. Maybe I'm approaching this from the wrong end?

In psudo-syntax, something like:

`select avg(value) from events group by count(60) where time>start && time<end`

**Comment by mitar** [comment]
This was closed, but then @230 was closed. Can we reopen then this back?
