### ISSUE TITLE
swagger_gen.go compile Segfault ARM64

### ISSUE THREAD

**Issue by antmurph** [influxdata/influxdb#18822]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ... Pull Master branch on Ubuntu 19.10 ARM64
2. ... Run Make with all listed dependencies installed(Rust, Go, Node, etc)

__Expected behavior:__
Makefile should proceed through all folders and compile successfully

__Actual behavior:__
Gets to influxdb/http and hangs on swagger_gen.go 

__Environment info:__

Ubuntu 19.10
ARM64
influxdb 2.0 Beta 13

__Logs:__
Full pastebin here. https://pastebin.com/khqNq5eM

**Comment by russorat** [comment]
@antmurph thanks! we don't currently have an arm build for 2.0: https://github.com/influxdata/influxdb/issues/18627

**Comment by danxmoran** [comment]
I believe this is now fixed, I was able to pull & build the `master` branch inside an `arm64v8/ubuntu` image (it took a long time to build, but it completed).
