### ISSUE TITLE
Single Stat doesn't render dates

### ISSUE THREAD

**Issue by drdelambre** [influxdata/influxdb#18837]
when the `_value` of a query result is a date, single stat will convert it to what looks like an epoch timestamp, then add `.00` to it. we should probably show a string representation instead.

**Comment by gomazu** [comment]
![Screen Shot 2020-07-01 at 4 40 19 PM](https://user-images.githubusercontent.com/63891737/86301013-99afca80-bbb9-11ea-92c4-729ef5517474.png)
![Screen Shot 2020-07-01 at 4 37 38 PM](https://user-images.githubusercontent.com/63891737/86301019-9caabb00-bbb9-11ea-98c9-3f0a8761806e.png)
![Screen Shot 2020-07-01 at 4 37 18 PM](https://user-images.githubusercontent.com/63891737/86301022-9d435180-bbb9-11ea-8ac8-57ca89586fa9.png)
![Screen Shot 2020-07-01 at 4 36 52 PM](https://user-images.githubusercontent.com/63891737/86301024-9ddbe800-bbb9-11ea-83c5-a2281c4f30c0.png)
![Screen Shot 2020-07-01 at 4 36 30 PM](https://user-images.githubusercontent.com/63891737/86301026-9e747e80-bbb9-11ea-81e2-2c3e8803b23e.png)

RAW Data and Table view show the date correctly, changing to Single stat will presents epoch time.

**Comment by ChitlangeSahas** [comment]
closed via influxdata/ui#1133
