### ISSUE TITLE
Deleting colorized Thresholds and trying to re-add will kill the session window (see screenshots)

### ISSUE THREAD

**Issue by gomazu** [influxdata/influxdb#18840]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open a dashboard / customize cell
2. delete one of the existing threshold. (all threshold are removed...)
3. try to add one back, session terminates 

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.
see screenshot
__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```
![Screen Shot 2020-07-01 at 5 26 03 PM](https://user-images.githubusercontent.com/63891737/86303416-9a982a80-bbc0-11ea-888e-64a885a5bf2c.png)
![Screen Shot 2020-07-01 at 5 25 38 PM](https://user-images.githubusercontent.com/63891737/86303420-9d931b00-bbc0-11ea-92bd-4ca3505cfdf2.png)
![Screen Shot 2020-07-01 at 5 24 40 PM](https://user-images.githubusercontent.com/63891737/86303422-9e2bb180-bbc0-11ea-9474-19f21426ab93.png)

**Comment by Asalem1** [comment]
Spoke to @gomazu about this and it doesn't seem like it's an issue anymore. I couldn't reproduce this, I'm gonna mark this as closed
