### ISSUE TITLE
Influx2 beta Flux: distinct() not working as expected

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb#18858]
__Steps to reproduce:__

Run simple query to produce unique list of tags for use as template variable:

    from(bucket: "evcc")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => exists r["loadpoint"])
    |> distinct(column: "loadpoint")
    |> keep(columns: ["loadpoint"])
    |> rename(columns:{"loadpoint":"_value"})

__Expected behavior:__
Single result row with 1 value (there is only one unique tag in the db).

__Actual behavior:__
Got 4 non-distinct rows:

    #group,false,false,true
    #datatype,string,long,string
    #default,_result,,
    ,result,table,_value
    ,,0,lp1
    ,,0,lp1
    ,,0,lp1
    ,,0,lp1

I have also tried changing the order of queries:

    from(bucket: "evcc")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => exists r["loadpoint"])
    |> keep(columns: ["loadpoint"])
    |> rename(columns:{"loadpoint":"_value"})
    |> distinct(column: "_value")
    
or

    from(bucket: "evcc")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => exists r["loadpoint"])
    |> keep(columns: ["loadpoint"])
    |> distinct(column: "loadpoint")
    |> rename(columns:{"loadpoint":"_value"})
    
both result in `internal error` in influx ui

__Environment info:__

* InfluxDB version: Version 2.0.0 (86796dd)

**Comment by russorat** [comment]
@andig thanks for the issue! I think the internal error is coming from trying to rename a column to a name that already exists.

Have you tried: https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/influxdb-v1/measurementtagvalues/ ? That might be an easier way to get the values for a variable.

**Comment by andig** [comment]
Thanks @russorat `measurementtagvalues` is working fine.

Can I leave it up to you if this can be closed or there is something to be done about the `distinct` behavior?

**Comment by russorat** [comment]
i'm going to close this for now since it was opened against a pre-release version of influxdb. if you are still facing this problem, please open a new issue with the details.

**Comment by andig** [comment]
@russorat could you please reopen? Still exactly the same issue on 2.0.6. No point in opening a new issue to report exactly the same ;)

**Comment by russorat** [comment]
Sounds good. thanks!

**Comment by sanderson** [comment]
@andig, I have an assumption, but I may be wrong. I don't think this is an issue with `distinct()`. I think it's an issue with the order of your operations.

What I believe is happening is that (using your example query and data from the top of this issue) the following:

```js
from(bucket: "evcc")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => exists r["loadpoint"])
```

...returns 4 separate tables. By default, InfluxDB returns results grouped by series (common measurement, tag set, and field key). So the `loadpoint` tag exists in 4 different series and you get a separate table for each. Then...

```js
|> distinct(column: "loadpoint")
```

...operates on each table, returning a single row output table for each input table with the distinct tag value. But when you drop the other columns with...

```js
|> keep(columns: ["loadpoint"])
```

It removes all the columns in the group key except for `loadpoint`, so all the rows with the same value for `loadpoint` are grouped into a single table, so you get one table with 4 rows.

To fix the issue, you just need to reorder your query functions:

```js
from(bucket: "evcc")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => exists r["loadpoint"])
  |> keep(columns: ["loadpoint"])
  |> rename(columns:{"loadpoint":"_value"})
  |> distinct()
```

**Comment by andig** [comment]
> What I believe is happening is that (using your example query and data from the top of this issue) the following: ...returns 4 separate tables.

Ahhhhhrrrrrggh. Bang head against wall. Thank you, much appreciated!
