### ISSUE TITLE
one bucket isn't visible from the UI interface anymore

### ISSUE THREAD

**Issue by nroypf** [influxdata/influxdb#18851]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a bucket name checkpoints
2. Performed this query 
```
import "csv"

option task = 
{ 
  name: "custom-task",
  every: 1m,
  offset: 30s  
}

csvData = "
#group,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string,string
#default,_result,,,,,,,,,
,result,table,_start,_stop,_time,_value,AssetPath,Layer,_field,_measurement
,,0,2020-07-02T17:20:48.443108002Z,2020-07-02T18:20:48.443108002Z,2020-07-02T17:20:52.079Z,1701.400024,BLK01.PAD01.INV01,raw,Value,AC_CURRENT_A
"

csv.from(csv: csvData)
    |> map(fn: (r) => ({ r with _value: r._value }))
    |> to(bucket: "checkpoints", org: "nroy@pfdrive.com")
```

__Expected behavior:__
The bucket should be visible if it still exists

__Actual behavior:__
Now the bucket isn't visible from the UI, neither when I scroll or if I do a search

If I try to recreate the bucket I receive an error telling that it already exists

However I can see it when I run this query 
```
buckets() |> filter(fn: (r) => r.name == "checkpoints")
```

__Environment info:__
Running on a PAYG InfluxDb Cloud account

userId: 058a8b1a21fc6000
ordId: 6e78532d0b34a495

__Config:__

__Logs:__

__Performance:__

**Comment by desa** [comment]
@nroypf just tried to reproduce this issue myself and everything seems to be working as I would expect it to. If you are still experiencing this issue, please open a support ticket and we can follow up there.

**Comment by nroypf** [comment]
No I cannot reproduce it either anymore.  You can close it
