### ISSUE TITLE
missing instructions for persisten volume in influxdb2.0 docker

### ISSUE THREAD

**Issue by vilinski** [influxdata/influxdb#18856]
can you please provide a instructions how to provide a path for persistent volume in influxdb2.0 ? 
especially for connection strings and dashboard configurations, which I have already lost during container restart )
thanks

**Comment by russorat** [comment]
@vilinski thanks! I believe this PR has an example of how to do it. https://github.com/influxdata/influxdb/pull/17946/files

If you can give the command you are running now, i might be able to provide more direction.

**Comment by danxmoran** [comment]
Docs are staged for merge to DockerHub at docker-library/docs#1871

**Comment by vilinski** [comment]
thanks!
 then you can add `fixes #18856` into description of the merge request to autoclose this issue when it merged ;)
