### ISSUE TITLE
manual minimum y-axis value not rendering in dashboard

### ISSUE THREAD

**Issue by sebito91** [influxdata/influxdb#18853]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create chronograf dashboard that includes any value that would cause the y-axis not to start at 0 (e.g. memory consumption, etc)
2. Edit the dashboard and set the y-axis manually to start at 0 (don't specify a max)
3. The y-axis doesn't change

__Expected behavior:__
The steps above would be nice so we can force the dashboard to start the y-axis at zero, but NOT have to specify a maximum for it. With metrics like network rx/tx, memory consumption, etc it's nice to let the tool visualize the changes at the top-end on our behalf while we set the minimum possible value.

__Actual behavior:__
Graph doesn't change even when setting manual y-axis min.

![zero_axis](https://user-images.githubusercontent.com/3159454/86410550-90d5fc00-bc80-11ea-951c-3ab46478ecc2.png)

**Comment by TCL735** [comment]
The issue is: y-axis min does work but it just doesn't obey 0 as the min. Choosing something close to 0, say 0.1, gives a good approximation for what 0 should do.

**Comment by desa** [comment]
@jacobmarble seems to still be running into this issue

**Comment by jacobmarble** [comment]
This bug is back in Cloud 2. I'm certain that it was working just 2h ago.

**Comment by TCL735** [comment]
This is working fine now.
![Kapture 2020-07-22 at 13 47 06](https://user-images.githubusercontent.com/10736577/88227147-026eed80-cc22-11ea-8690-fd8807893ea0.gif)
