### ISSUE TITLE
Add mean capability, feature flag, and planner rule for aggregate window

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#18860]
Add the mean capability, feature flag, and the planner rule for aggregate window.

This does not involve adding any tests for the functionality or enabling the feature flag or capability.

**Comment by wolffcm** [comment]
No tests for functionality, but there should be a test for the planner rule.

**Comment by yzhang1991** [comment]
mean capability, feature flag, and planner rule for aggregate window are actually all already in place.
