### ISSUE TITLE
Implement mean in aggregate window

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#18861]
Implement the mean functionality for aggregate window. This involves updating the store to support the mean aggregate and writing launcher and reader tests for the mean functionality.

**Comment by wolffcm** [comment]
This case is easier because we are computing a (windowed) mean over a single series, and not merging data from different series.

**Comment by jsternberg** [comment]
There shouldn't be any client work needed for this but a test should be added to `storage/flux/table_test.go` to verify the functionality from the client.
