### ISSUE TITLE
"failed to create tokens" when creating a token 

### ISSUE THREAD

**Issue by anwar6953** [influxdata/influxdb#18887]
If I use `Select All` to specify the read and write scopes then it fails.
If I select them individually, then it works fine.

![image](https://user-images.githubusercontent.com/2440977/86957277-58667000-c10f-11ea-9f2e-6d636aa6dbee.png)

![image](https://user-images.githubusercontent.com/2440977/86957386-7fbd3d00-c10f-11ea-8a40-ba99ef1d99fb.png)

**Comment by desa** [comment]
@anwar6953 we believe that this issue should be fixed. Can you confirm that you are no longer seeing this behavior?

**Comment by anwar6953** [comment]
I tested it again just now; it still failed for me.

**Comment by anwar6953** [comment]
Note that it is not a blocker, since I could easily select the buckets individually, but I just wanted surface the broken functionality.

**Comment by desa** [comment]
@anwar6953 is this a local installation or in our cloud product?

**Comment by anwar6953** [comment]
It's the cloud product.

If you click "All Buckets", it works. But if you click "Select All", then it fails.
https://imgur.com/a/LZbtqr3

**Comment by desa** [comment]
@anwar6953 awesome! Just reproduced this myself. Thank you for reporting!

**Comment by TCL735** [comment]
Unable to reproduce, per @ShmuelLotman 

Closing this.
