### ISSUE TITLE
cannot change the x-axis for line graph

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18884]
As a user, if there is an option to select a different column for the x-axis, then i would like to be able to select that column.

![Kapture 2020-07-08 at 9 20 59](https://user-images.githubusercontent.com/4805997/86944275-5e068a80-c0fc-11ea-8d2c-75be03246288.gif)

**Comment by drdelambre** [comment]
possibly introduced with
https://github.com/influxdata/influxdb/pull/18787

**Comment by sjwang90** [comment]
Fix looks good but I can't edit the x-axis range. it's defaulted to be huge (looks like 0-15,000) so all my points which are <100 get squished the side

![image](https://user-images.githubusercontent.com/32681364/88420864-64536280-cd9c-11ea-81ae-173031d551f1.png)

**Comment by zoesteinkamp** [comment]
@sjwang90 
im not sure where the problem is located, where do you normally access the x-axis range? Im not familiar with this functionality

**Comment by sjwang90** [comment]
Don't quite remember where it was prior but would be similar to how there is a y-axis range.  This is a for a scatterplot but I see similar missing x-axis ranges for a line graph as well.

![image](https://user-images.githubusercontent.com/32681364/88443120-e5761e00-cdcb-11ea-8188-4a6366f61025.png)

**Comment by zoesteinkamp** [comment]
I see, so this functionality is supposed to exist
<img width="887" alt="Screen Shot 2020-07-28 at 12 38 58 PM" src="https://user-images.githubusercontent.com/6667389/88707372-5fa9e980-d0cf-11ea-8ac2-7ecc201d9cf6.png">
 for the x axis as well? Like we used to see the exact same ui but it was obviously all X-axis

**Comment by russorat** [comment]
min/max on the x axis doesn't make sense for graph types where time is on the x-axis, as the min/max is defined by the dataset returned.

For graphs like scatter or histogram, where x-axis isn't time, then the X-axis domain should be configurable.

That seems different than this issue though, so let's open a new one for this.
