### ISSUE TITLE
Flux last() wrong answer when last point is equal to range start

### ISSUE THREAD

**Issue by rhajek** [influxdata/influxdb#18897]
Python, Java client library build failed on latest InfluxDB 2.0.0-beta
* https://circleci.com/gh/influxdata/influxdb-client-python/1101 
* https://circleci.com/gh/influxdata/influxdb-client-java/1518

__Steps to reproduce:__
insert LP 
```
h2o_feet,location=coyote_creek level=1.0 1
```
execute query 
```
from(bucket: "my-bucket") |> range(start: 1970-01-01T00:00:00.000000001Z) |> last()
```
Result is empty, but the query should return 1 record.

If the date is changed from 1970-01-01T00:00:00.00000000**1**Z to 1970-01-01T00:00:00.00000000**0**Z result correctly contains 1 record. 

__Environment info:__
Latest docker build:
https://quay.io/repository/influxdb/influxdb?tag=2.0.0-beta&tab=tags

**Comment by rhajek** [comment]
This issue is related only to 2.0.0-beta, https://circleci.com/gh/influxdata/influxdb-client-python/1117 that runs on quay.io/influxdb/influx:nightly is not affected by this bug.

**Comment by jlapacik** [comment]
So far it appears this bug only happens in the specific case of `from |> range |> last` where the call to range only returns a single point that that point has `_time == start`. Still investigating the cause.
