### ISSUE TITLE
v.windowPeriod is not consistently calculated

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18907]
This one is tough to describe, but here goes.

The behavior I see is that submitting the same queries, with the same time range, and same screen size, yields different values for `v.windowPeriod` which results in different graphs.

```
from(bucket: "telegraf")
  |> range(start: -5m)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_user")
  |> filter(fn: (r) => r["cpu"] == "cpu-total")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")

from(bucket: "telegraf")
  |> range(start: -5m)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_user")
  |> filter(fn: (r) => r["cpu"] == "cpu-total")
  |> yield(name: "raw")
```
![Kapture 2020-07-09 at 13 36 46](https://user-images.githubusercontent.com/4805997/87088383-85875100-c1e9-11ea-8d80-bbd24aded075.gif)

Notice in the gif below, there is one time hitting submit where one of the graphs changes dramatically. But when I look at the request made from the UI, all of the previous requests use a value of 10000ms for `v.windowPeriod` while the one with the strange graphs uses a value of 833ms.

![image](https://user-images.githubusercontent.com/4805997/87090259-879edf00-c1ec-11ea-9b96-275f88fc84a1.png)

![image](https://user-images.githubusercontent.com/4805997/87090198-6f2ec480-c1ec-11ea-8481-6caed46e13b6.png)

**Comment by philjb** [comment]
In general the predefined variable v.windowPeriod is opaque to the user. It should be displayed in the variable selection bar just like any other variable so the user can know what value is being used to produce the plot and tell if it is taking on some strange value. (Same for v.timeRangeStart/Stop)

**Comment by Asalem1** [comment]
Closing for this:

https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/18907
