### ISSUE TITLE
Getting started no longer shows up after initial user setup

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18931]
this is in beta-14: c8af0f3

after setting the username, password, org, bucket, there should be a getting started page that says "quickstart" "load data" etc. This is probably related to router changes.

![Kapture 2020-07-13 at 9 17 34](https://user-images.githubusercontent.com/4805997/87328141-e8c6fb00-c4e9-11ea-8a45-c0ca455b2838.gif)

**Comment by russorat** [comment]
![Kapture 2020-07-13 at 9 17 34](https://user-images.githubusercontent.com/4805997/87330365-56285b00-c4ed-11ea-9b66-e1615a58fb3c.gif)

**Comment by xe-nvdk** [comment]
I can confirm the issue in Linux build running in Ubuntu Server 20.04

![Screenshot from 2020-07-13 13-49-10](https://user-images.githubusercontent.com/64545348/87336398-25115000-c518-11ea-86a9-f72550f51a56.png)

**Comment by drdelambre** [comment]
just for my notes, I could not reproduce with these version numbers:
backend:
```
root@67eb898c839a:/# influx version
Influx CLI dev (git: 696790efff) build_date: 2020-07-28T21:33:53Z
root@67eb898c839a:/# influxd version
InfluxDB dev (git: 696790efff) build_date: 2020-07-28T21:34:06Z
```

frontend:
```
git: a7273f89d755bc1ac2725c691e18410caa418797
```

**Comment by russorat** [comment]
i am able to repro on a7273f8.
