### ISSUE TITLE
Dashboard has no cells

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#18958]
#### Background
Clicking a dashboard from the dashboard index page while the page is still loading results in the Dashboard showing a message that says, "Please add Cells"

![Screen Shot 2020-07-14 at 4.59.56 PM.png](https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/173135b3-a2f7-431f-b567-b3592351be18)

#### To Reproduce
1. Open a dashboard index page with data on it (the tools one is a great example https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards-list)
1. Before the dashboard index page is finished loading, click a link to a dashboard
1. Observe the page lying directly through its teeth by saying there aren't any dashboard cells (reload to prove the lying page wrong)

**Comment by desa** [comment]
As I started to repro this, I noticed additional weird behavior. Sometimes I see the cells flash for a second and then disappear and other times they appear after multiple seconds of waiting.

**Comment by Asalem1** [comment]
This should be resolved with:

https://github.com/influxdata/influxdb/pull/19166
