### ISSUE TITLE
Flows: User starts flow with metric selector cell

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#18953]
As a flows early access user I can start building a flow without having to start from scratch

GIVEN I am on the flows index
WHEN I click `Create Flow`
THEN I am taken to a new flow page with a Metric Selector cell already created

GIVEN I only have 1 non-system bucket
THEN select the 1 non-system bucket automatically in the Metric Selector cell

### Design Notes
https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=885%3A6

### Technical Notes
Metric Selector: https://github.com/influxdata/ui/tree/master/src/notebooks/pipes/Data

**Comment by drdelambre** [comment]
this is missing the context of the future "templated workflow" idea, where the user can click a button, and a notebook can be initialized in an arbitrary state. talking about it offline, just doing this task removes the instructional text bit for the user that exists within an empty notebook state. To get that back, while addressing the intent of this ticket, while looking forward, here's a better ticket: https://github.com/influxdata/ui/issues/112

**Comment by drdelambre** [comment]
after chatting, closing in favor of the other ticket
