### ISSUE TITLE
POST 'api/v2/write' on InfluxDB2 writes all columns as strings

### ISSUE THREAD

**Issue by masonhuemmer** [influxdata/influxdb#18970]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Posting to api/v2/write with two integers as Tags and a string field

__Expected behavior:__
InfluxDB to recognize the columns that are integers and setting the data type as an integer. 

__Actual behavior:__
InfluxDB writes all tags / fields to the measurement and sets the data type field as strings.

![image](https://user-images.githubusercontent.com/49791141/87618275-17f28d80-c6df-11ea-8ec9-513f0df766a0.png)

![image](https://user-images.githubusercontent.com/49791141/87618278-1a54e780-c6df-11ea-9ead-9d302a302aa7.png)

![image](https://user-images.githubusercontent.com/49791141/87618344-3ce70080-c6df-11ea-886b-5fc6b1ae2227.png)

I tried writing the payload as a byte literal, but unfortunately, I was not able to post. I received the following error. 

![image](https://user-images.githubusercontent.com/49791141/87618492-9cdda700-c6df-11ea-9476-7405218c4f26.png)

I tried to switch to the python-client, but I had an issue where I would receive a 204 response, but the measurement was not getting updated with my input. I have a ticket open currently for the issue. 

https://github.com/influxdata/influxdb-client-python/issues/133

I tried to mimick the payload that was from the debug log in the screenshot below using the Influx-Client-Python, but again, kept getting an error. 

![image](https://user-images.githubusercontent.com/49791141/87618581-d31b2680-c6df-11ea-8ef6-baa1cc4d8198.png)

As a work around, I am using the float() function, to convert the string column to a double. 

__Environment info:__

* System info: Linux 4.19.104-microsoft-standard x86_64
* InfluxDB version: InfluxDB 2.0.0-beta.14 (git: c8af0f35be) build_date: 2020-07-08T20:42:23Z

**Comment by russorat** [comment]
@masonhuemmer thanks for the issue. in line protocol, tag values are always strings: https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#tag-value

If you need to perform calculations on them, you will need to convert them at query time.

**Comment by russorat** [comment]
Closing this for now since line protocol treats all tags as strings.
