### ISSUE TITLE
Refactor initial app state to parallel API requests

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#18986]
The  UI is architected in a pattern that does not issue API calls until previous API calls have been resolved. 
```
<Component#1>
    <Component#2 />
</Component#1>
```
and component#1 does not render component#2 until after all the API calls it makes are resolved. 
The biggest culprit here is the use of SpinnerContainer. which blocks the render of its children while it is loading. What happens is that we show one container's Spinner and then its child's spinner, and then its child's spinner.

**Comment by 121watts** [comment]
Currently app state is bootstrapped thusly: Me => Flags => Orgs => the rest of the app.  Look into how we can flatten that request to behave more like [me, flags, orgs].  All at once.
