### ISSUE TITLE
Query should not be reissued when user switches from script editor to query builder

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#18983]
Switching from script editor mode to query builder mode might need to reissue queries needed to populate the query builder, but the main query does not need to reload, and the visualization does not need to refresh either.

**Comment by desa** [comment]
May be fixed by #18791

**Comment by Asalem1** [comment]
Need to verify that this is resolved with the cache and whether or not we will want to expand the cache to the data explorer
