### ISSUE TITLE
InfluxDB 2.0: Switch organization produces invalid URL

### ISSUE THREAD

**Issue by antongocode** [influxdata/influxdb#18992]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. InfluxDB 2.0 Beta 14
2. Create two organizations
3. Use Web interface to switch organizations

__Expected behavior:__
Interface should switch to selected organization.

__Actual behavior:__

1. Current URL: http://{host}:9999/orgs/{org-id-A}
2. Select "Switch Organizations" and select org B
3. New URL: http://{host}:9999/orgs/{org-id-A}**/orgs/{org-id-B}**
4. Would Expect: http://{host}:9999/orgs/{org-id-B}

**Comment by FrankStienhans2** [comment]
Can you please explain how this could have happened?
Do you have automated testing in place?

**Comment by 121watts** [comment]
Thanks for reporting @antongocode!  Fix is up awaiting review.
