### ISSUE TITLE
Tenant service can generate harmful org and bucket IDs

### ISSUE THREAD

**Issue by GeorgeMac** [influxdata/influxdb#19017]
While investigating flaky tests @adrian-thurston bisected a fault down to the following commit:
https://github.com/influxdata/influxdb/commit/d720661e77564105bfe371a392deff165ce49562

It introduced the new tenant service, which in turn introduced a new implementation for the bucket and organizations services.
He observed that the pattern in IDs generated for buckets had changed. Now the IDs being generated were very similar to one another.

This led us to note that the tenant service was using a different `influxdb.IDGenerator` implementation:
- Using `snowflake` now: https://github.com/influxdata/influxdb/blob/master/tenant/storage.go#L24
- Used to use `rand` implementation : https://github.com/influxdata/influxdb/blob/master/kv/service.go#L62

The `rand` implementation sanitized away some potentially harmful characters:

- `\`
- ` `
- `,`

Further investigation showed that this is problematic when the following sequences occur in either a bucket or org ID:

- `\ ` (`5c20`)
- `\"` (`5c22`)
- `\=` (`5c3b`)
- `\,` (`5c2c`)

Since organization and bucket IDs are concatenated to generate the measurement used in the storage engine. This causes an issue within TSI. Which presents itself as empty responses when querying data that was written to the bucket in question.
Data writes successfully, however, it cannot be retrieved again. As it has been stored at an unreachable location.

We need to go back to the original `rand.OrgBucketID` generator:
https://github.com/influxdata/influxdb/blob/master/rand/id.go#L34

**Comment by nathanielc** [comment]
To clarify, is it the sanitation or the lack of sanitation that caused the issue?

**Comment by GeorgeMac** [comment]
@nathanielc lack of sanitation that caused the issue
