### ISSUE TITLE
Dashboard export fails with OSS beta 14

### ISSUE THREAD

**Issue by darinfisher** [influxdata/influxdb#19027]
__Steps to reproduce:__
1. Create Dashboard
2. Attempt to export

__Expected behavior:__
Should be directed to the export window in order to choose the method for export.

__Actual behavior:__
The dashboard loaded just like when selecting the name

__Environment info:__

* System info: Run `uname -srm` and copy the output here
`Linux 5.4.0-42-generic x86_64`
* InfluxDB version: Run `influxd version` and copy the output here
`InfluxDB 2.0.0-beta.14 (git: c8af0f35be) build_date: 2020-07-08T20:42:23Z`
* Other relevant environment details: Container runtime, disk info, etc
Nothing special

__Config:__
All is default and no config file.
Command line to start it:
`nohup /home/darinf/work/influxdb/influxdb-runtime/influxd &>influx.out &`

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by desa** [comment]
This has been fixed in prod
