### ISSUE TITLE
Replace github.com/nats-io/gnatsd with github.com/nats-io/nats-server

### ISSUE THREAD

**Issue by eclipseo** [influxdata/influxdb#19042]
Please update github.com/nats-io/gnatsd with the new official import path github.com/nats-io/nats-server

**Comment by wallyqs** [comment]
Some other imports that would have to be updated:

- go-nats: nats.go
- go-nats-streaming: stan.go
-github.com/nats-io/gnatsd => github.com/nats-io/nats-server/v2

I will see if I can send a PR for this...

**Comment by danxmoran** [comment]
We intend to remove our dependency on NATS entirely, so I'm going to close this.
