### ISSUE TITLE
Queries taking ages with lots of data.

### ISSUE THREAD

**Issue by ZakShearman** [influxdata/influxdb#19067]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. Have masses of data in your bucket for the specific filter/time used.
2. Query the database with, not sure if relevant, the sum option.

__Expected behavior:__
Would be resolved in a small amount of time.

__Actual behavior:__
https://zak.pink/2020/07/Favorite-Axolotl-8487.jpg (took 23 seconds this time, others have taken minutes)
Sometimes just doesn't resolve, taking at least 20 seconds, up to 40 seconds (therefore grafana times out on the request).
The task is only set onto one core and that one core is maxed.

__Environment info:__

* System info: Linux 4.15.0-112-generic x86_64
* InfluxDB version: InfluxDB 2.0.0-beta.15 (git: f54848f443) build_date: 2020-07-23T18:27:19Z

__Performance:__
https://zak.pink/2020/07/iostat.txt
https://zak.pink/2020/07/profiles.tar.gz
https://zak.pink/2020/07/vars.txt

If you need any more info or there's something I might be doing wrong, please let me know.

**Comment by russorat** [comment]
i'm going to close this for now since it was opened against a pre-release version of influxdb. Flux performance has improved dramatically since then and continues to be an area of focus. if you are still facing this problem, please open a new issue with the details.
