### ISSUE TITLE
influxd inspect should skip non-exists tsm file

### ISSUE THREAD

**Issue by STRRL** [influxdata/influxdb#19083]
__Proposal:__
Make `influxd inspect` could running on-the-flight.

__Current behavior:__
`influxd inspect` will exit when some file not exist:

```
error: /data1/influxdb/engine/data/000000000232006-000000001.tsm: open /data1/influxdb/engine/data/000000000232006-000000001.tsm: no such file or directory. Exiting.
Error: open /data1/influxdb/engine/data/000000000232006-000000001.tsm: no such file or directory
```

__Desired behavior:__
Just skip these file, or refresh tsm file list.

__Alternatives considered:__
Disable influxd compaction temporarily during `influxd inspect`.

__Use case:__
Analyze tsm file on-the-flight.

**Comment by russorat** [comment]
@STRRL thanks for the issue. Could you add what version of influxd you are running?

**Comment by STRRL** [comment]
@russorat  2.0.0-beta.14 
```
#influxd version
InfluxDB 2.0.0-beta.14 (git: c8af0f35be) build_date: 2020-07-08T20:42:23Z
```

**Comment by danxmoran** [comment]
Something to keep in mind while implementing #20273

**Comment by danxmoran** [comment]
This was fixed in `influxd inspect export-lp`, added in v2.0.4
