### ISSUE TITLE
dep init is failing while building influxdb with branch-1.8 and git tag v1.8.1 (golang version- 1.13.14)

### ISSUE THREAD

**Issue by fti-cneve** [influxdata/influxdb#19084]
Steps to reproduce:
- git checkout 1.8
- git pull origin
- git checkout --detach v1.8.1
HEAD is now at af0237819 Update changelog
- dep init -v

After the above operations dep init is failing, following are the logs with verbose mode:
---------------------------------------------------------------------------------------------------------------
Getting direct dependencies...
Checked 179 directories for packages.
Found 36 direct dependencies.
Root project is "github.com/influxdata/influxdb"
 137 transitively valid internal packages
 66 external packages imported from 36 projects
(0)   ✓ select (root)
(1)	? attempt github.com/bmizerany/pat with 1 pkgs; 1 versions to try
(1)	    try github.com/bmizerany/pat@master
(1)	✓ select github.com/bmizerany/pat@master w/1 pkgs
(2)	? attempt github.com/dgryski/go-bitstream with 1 pkgs; 1 versions to try
(2)	    try github.com/dgryski/go-bitstream@master
(2)	✓ select github.com/dgryski/go-bitstream@master w/1 pkgs
(3)	? attempt github.com/xlab/treeprint with 1 pkgs; 2 versions to try
(3)	    try github.com/xlab/treeprint@v1.0.0
(3)	✓ select github.com/xlab/treeprint@v1.0.0 w/1 pkgs
(4)	? attempt github.com/influxdata/usage-client with 1 pkgs; 2 versions to try
(4)	    try github.com/influxdata/usage-client@master
(4)	✓ select github.com/influxdata/usage-client@master w/1 pkgs
(5)	? attempt golang.org/x/sync with 1 pkgs; 1 versions to try
(5)	    try golang.org/x/sync@master
(5)	✓ select golang.org/x/sync@master w/1 pkgs
(6)	? attempt github.com/paulbellamy/ratecounter with 1 pkgs; 3 versions to try
(6)	    try github.com/paulbellamy/ratecounter@v0.2.0
(6)	✓ select github.com/paulbellamy/ratecounter@v0.2.0 w/1 pkgs
(7)	? attempt github.com/golang/snappy with 1 pkgs; 3 versions to try
(7)	    try github.com/golang/snappy@v0.0.1
(7)	✓ select github.com/golang/snappy@v0.0.1 w/1 pkgs
(8)	? attempt github.com/jwilder/encoding with 1 pkgs; 2 versions to try
(8)	    try github.com/jwilder/encoding@master
(8)	✓ select github.com/jwilder/encoding@master w/1 pkgs
(9)	? attempt github.com/peterh/liner with 1 pkgs; 6 versions to try
(9)	    try github.com/peterh/liner@v1.2.0
(9)	✓ select github.com/peterh/liner@v1.2.0 w/1 pkgs
(10)  ? attempt github.com/retailnext/hllpp with 1 pkgs; 2 versions to try
(10)      try github.com/retailnext/hllpp@v1.0.0
(10)  ✓ select github.com/retailnext/hllpp@v1.0.0 w/1 pkgs
(11)  ? attempt golang.org/x/time with 1 pkgs; 1 versions to try
(11)      try golang.org/x/time@master
(11)  ✓ select golang.org/x/time@master w/1 pkgs
(12)  ? attempt github.com/influxdata/influxql with 1 pkgs; 8 versions to try
(12)      try github.com/influxdata/influxql@v1.1.0
(12)  ✓ select github.com/influxdata/influxql@v1.1.0 w/2 pkgs
(13)  ? attempt github.com/spf13/cast with 1 pkgs; 7 versions to try
(13)      try github.com/spf13/cast@v1.3.1
(13)  ✓ select github.com/spf13/cast@v1.3.1 w/1 pkgs
(14)  ? attempt golang.org/x/sys with 1 pkgs; 7 versions to try
(14)      try golang.org/x/sys@master
(14)  ✓ select golang.org/x/sys@master w/2 pkgs
(15)  ? attempt github.com/BurntSushi/toml with 1 pkgs; 8 versions to try
(15)      try github.com/BurntSushi/toml@v0.3.1
(15)  ✓ select github.com/BurntSushi/toml@v0.3.1 w/1 pkgs
(16)  ? attempt github.com/davecgh/go-spew with 1 pkgs; 4 versions to try
(16)      try github.com/davecgh/go-spew@v1.1.1
(16)  ✓ select github.com/davecgh/go-spew@v1.1.1 w/1 pkgs
(17)  ? attempt github.com/jsternberg/zap-logfmt with 1 pkgs; 4 versions to try
(17)      try github.com/jsternberg/zap-logfmt@v1.2.0
(17)  ✓ select github.com/jsternberg/zap-logfmt@v1.2.0 w/1 pkgs
(18)  ? attempt github.com/opentracing/opentracing-go with 1 pkgs; 33 versions to try
(18)      try github.com/opentracing/opentracing-go@v1.2.0
(18)  ✓ select github.com/opentracing/opentracing-go@v1.2.0 w/2 pkgs
(19)  ? attempt github.com/mattn/go-isatty with 1 pkgs; 14 versions to try
(19)      try github.com/mattn/go-isatty@v0.0.12
(19)  ✓ select github.com/mattn/go-isatty@v0.0.12 w/1 pkgs
(20)  ? attempt github.com/prometheus/client_golang with 2 pkgs; 32 versions to try
(20)      try github.com/prometheus/client_golang@v1.7.1
(20)  ✓ select github.com/prometheus/client_golang@v1.7.1 w/3 pkgs
(21)  ? revisit golang.org/x/sys to add 1 pkgs
(21)    ✓ include 2 more pkgs from golang.org/x/sys@master
(21)  ? attempt github.com/prometheus/client_model with 1 pkgs; 6 versions to try
(22)      try github.com/prometheus/client_model@v0.2.0
(22)  ✓ select github.com/prometheus/client_model@v0.2.0 w/1 pkgs
(22)  ? attempt collectd.org with 2 pkgs; 6 versions to try
(23)      try collectd.org@v0.5.0
(23)  ✓ select collectd.org@v0.5.0 w/4 pkgs
(23)  ? attempt golang.org/x/text with 2 pkgs; 12 versions to try
(24)      try golang.org/x/text@v0.3.3
(24)  ✓ select golang.org/x/text@v0.3.3 w/9 pkgs
(24)  ? attempt github.com/beorn7/perks with 1 pkgs; 7 versions to try
(25)      try github.com/beorn7/perks@v1.0.1
(25)  ✓ select github.com/beorn7/perks@v1.0.1 w/1 pkgs
(25)  ? attempt github.com/boltdb/bolt with 1 pkgs; 8 versions to try
(26)      try github.com/boltdb/bolt@v1.3.1
(26)  ✓ select github.com/boltdb/bolt@v1.3.1 w/1 pkgs
(26)  ? attempt go.uber.org/zap with 3 pkgs; 34 versions to try
(27)      try go.uber.org/zap@v1.15.0
Importing configuration from glide. These are only initial constraints, and are further refined during the solve process.
(27)  ✓ select go.uber.org/zap@v1.15.0 w/7 pkgs
(27)  ? attempt github.com/golang/protobuf with 1 pkgs; 17 versions to try
(28)      try github.com/golang/protobuf@v1.4.2
(28)  ✓ select github.com/golang/protobuf@v1.4.2 w/1 pkgs
(28)  ? attempt github.com/gogo/protobuf with 3 pkgs; 31 versions to try
(29)      try github.com/gogo/protobuf@v1.3.1
(29)  ✓ select github.com/gogo/protobuf@v1.3.1 w/5 pkgs
(29)  ? attempt github.com/klauspost/pgzip with 1 pkgs; 12 versions to try
(30)      try github.com/klauspost/pgzip@v1.2.4
(30)  ✓ select github.com/klauspost/pgzip@v1.2.4 w/1 pkgs
(30)  ? attempt github.com/prometheus/common with 2 pkgs; 17 versions to try
(31)      try github.com/prometheus/common@v0.10.0
(31)  ✓ select github.com/prometheus/common@v0.10.0 w/3 pkgs
(31)  ? attempt github.com/pkg/errors with 1 pkgs; 17 versions to try
(32)      try github.com/pkg/errors@v0.9.1
(32)  ✓ select github.com/pkg/errors@v0.9.1 w/1 pkgs
(32)  ? attempt github.com/dgrijalva/jwt-go with 1 pkgs; 21 versions to try
(33)      try github.com/dgrijalva/jwt-go@v3.2.0
(33)  ✓ select github.com/dgrijalva/jwt-go@v3.2.0 w/1 pkgs
(33)  ? attempt google.golang.org/grpc with 2 pkgs; 107 versions to try
(34)      try google.golang.org/grpc@v1.30.0
(34)  ✓ select google.golang.org/grpc@v1.30.0 w/40 pkgs
(34)  ? revisit github.com/golang/protobuf to add 1 pkgs
(35)    ✓ include 1 more pkgs from github.com/golang/protobuf@v1.4.2
(34)  ? attempt golang.org/x/crypto with 2 pkgs; 4 versions to try
(36)      try golang.org/x/crypto@master
(36)  ✓ select golang.org/x/crypto@master w/3 pkgs
(35)  ? attempt google.golang.org/protobuf with 1 pkgs; 8 versions to try
(37)      try google.golang.org/protobuf@v1.25.0
(37)  ✓ select google.golang.org/protobuf@v1.25.0 w/27 pkgs
(36)  ? revisit go.uber.org/zap to add 1 pkgs
(38)    ✓ include 1 more pkgs from go.uber.org/zap@v1.15.0
(36)  ? attempt github.com/apache/arrow with 3 pkgs; 38 versions to try
(39)      try github.com/apache/arrow@master
(39)  ✓ select github.com/apache/arrow@master w/8 pkgs
(37)  ? attempt github.com/mattn/go-runewidth with 1 pkgs; 11 versions to try
(40)      try github.com/mattn/go-runewidth@v0.0.9
(40)  ✓ select github.com/mattn/go-runewidth@v0.0.9 w/1 pkgs
(38)  ? revisit github.com/golang/protobuf to add 2 pkgs
(41)    ✓ include 5 more pkgs from github.com/golang/protobuf@v1.4.2
(38)  ? attempt github.com/google/go-cmp with 2 pkgs; 11 versions to try
(42)      try github.com/google/go-cmp@v0.5.1
(42)  ✓ select github.com/google/go-cmp@v0.5.1 w/6 pkgs
(39)  ? attempt google.golang.org/genproto with 1 pkgs; 1 versions to try
(43)      try google.golang.org/genproto@master
(43)  ✓ select google.golang.org/genproto@master w/1 pkgs
(40)  ? revisit github.com/golang/protobuf to add 1 pkgs
(44)    ✓ include 1 more pkgs from github.com/golang/protobuf@v1.4.2
(40)  ? attempt github.com/cespare/xxhash with 1 pkgs; 17 versions to try
(45)      try github.com/cespare/xxhash@v2.1.1
(46)  ✗   github.com/cespare/xxhash at v2.1.1 has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@v2.1.0
(46)  ✗   github.com/cespare/xxhash at v2.1.0 has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@v2.0.0
(46)  ✗   github.com/cespare/xxhash at v2.0.0 has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@v1.1.0
(46)  ✗   github.com/cespare/xxhash at v1.1.0 has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@v1.0.0
(46)  ✗   github.com/cespare/xxhash at v1.0.0 has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@master
(46)  ✗   github.com/cespare/xxhash at master has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@base-for-ongardie-ebay-allocs
(46)  ✗   github.com/cespare/xxhash at base-for-ongardie-ebay-allocs has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@bench-module
(46)  ✗   github.com/cespare/xxhash at bench-module has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@digest
(46)  ✗   github.com/cespare/xxhash at digest has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@ongardie-ebay-allocs-followup
(46)  ✗   github.com/cespare/xxhash at ongardie-ebay-allocs-followup has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@sse
(46)  ✗   github.com/cespare/xxhash at sse has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@uninline
(46)  ✗   github.com/cespare/xxhash at uninline has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@v2
(46)  ✗   github.com/cespare/xxhash at v2 has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@v2-binary-marshaler
(46)  ✗   github.com/cespare/xxhash at v2-binary-marshaler has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@v2-cleanup
(46)  ✗   github.com/cespare/xxhash at v2-cleanup has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@v2-remove-18-fallback
(46)  ✗   github.com/cespare/xxhash at v2-remove-18-fallback has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)      try github.com/cespare/xxhash@writeBlocks-slice-pointer
(46)  ✗   github.com/cespare/xxhash at writeBlocks-slice-pointer has problem subpkg(s):
(46)    	github.com/cespare/xxhash/v2 is missing; required by github.com/prometheus/client_golang@v1.7.1.
(45)    ← no more versions of github.com/cespare/xxhash to try; begin backtrack
(44)  ← backtrack: popped 1 pkgs from github.com/golang/protobuf
(43)  ← backtrack: no more versions of google.golang.org/genproto to try
(42)  ← backtrack: no more versions of github.com/google/go-cmp to try
(41)  ← backtrack: popped 5 pkgs from github.com/golang/protobuf
(40)  ← backtrack: no more versions of github.com/mattn/go-runewidth to try
(39)  ← backtrack: no more versions of github.com/apache/arrow to try
(38)  ← backtrack: popped 1 pkgs from go.uber.org/zap
(37)  ← backtrack: no more versions of google.golang.org/protobuf to try
(36)  ← backtrack: no more versions of golang.org/x/crypto to try
(35)  ← backtrack: popped 1 pkgs from github.com/golang/protobuf
(34)  ← backtrack: no more versions of google.golang.org/grpc to try
(33)  ← backtrack: no more versions of github.com/dgrijalva/jwt-go to try
(32)  ← backtrack: no more versions of github.com/pkg/errors to try
(31)  ← backtrack: no more versions of github.com/prometheus/common to try
(30)  ← backtrack: no more versions of github.com/klauspost/pgzip to try
(29)  ← backtrack: no more versions of github.com/gogo/protobuf to try
(28)  ← backtrack: no more versions of github.com/golang/protobuf to try
(27)  ← backtrack: no more versions of go.uber.org/zap to try
(26)  ← backtrack: no more versions of github.com/boltdb/bolt to try
(25)  ← backtrack: no more versions of github.com/beorn7/perks to try
(24)  ← backtrack: no more versions of golang.org/x/text to try
(23)  ← backtrack: no more versions of collectd.org to try
(22)  ← backtrack: no more versions of github.com/prometheus/client_model to try
(21)  ← backtrack: popped 2 pkgs from golang.org/x/sys
(20)  ← backtrack: no more versions of github.com/prometheus/client_golang to try
(19)  ← backtrack: no more versions of github.com/mattn/go-isatty to try
(18)  ← backtrack: no more versions of github.com/opentracing/opentracing-go to try
(17)  ← backtrack: no more versions of github.com/jsternberg/zap-logfmt to try
(16)  ← backtrack: no more versions of github.com/davecgh/go-spew to try
(15)  ← backtrack: no more versions of github.com/BurntSushi/toml to try
(14)  ← backtrack: no more versions of golang.org/x/sys to try
(13)  ← backtrack: no more versions of github.com/spf13/cast to try
(12)  ← backtrack: no more versions of github.com/influxdata/influxql to try
(11)  ← backtrack: no more versions of golang.org/x/time to try
(10)  ← backtrack: no more versions of github.com/retailnext/hllpp to try
(9)	← backtrack: no more versions of github.com/peterh/liner to try
(8)	← backtrack: no more versions of github.com/jwilder/encoding to try
(7)	← backtrack: no more versions of github.com/golang/snappy to try
(6)	← backtrack: no more versions of github.com/paulbellamy/ratecounter to try
(5)	← backtrack: no more versions of golang.org/x/sync to try
(4)	← backtrack: no more versions of github.com/influxdata/usage-client to try
(3)	← backtrack: no more versions of github.com/xlab/treeprint to try
(2)	← backtrack: no more versions of github.com/dgryski/go-bitstream to try
(1)	← backtrack: no more versions of github.com/bmizerany/pat to try
  ✗ solving failed

Solver wall times by segment:
     b-list-versions: 41.747452837s
              b-gmal:  3.397047701s
         b-list-pkgs:  2.480033678s
  b-deduce-proj-root:   2.08313095s
         select-atom:   34.244289ms
         select-root:   27.372799ms
             satisfy:   19.970903ms
            unselect:   16.880829ms
            new-atom:     865.361µs
           backtrack:      205.93µs
               other:      77.007µs
     b-source-exists:      53.037µs
            add-atom:       27.65µs

  TOTAL: 49.807362971s

init failed: unable to solve the dependency graph: Solving failure: No versions of github.com/cespare/xxhash met constraints:
	v2.1.1: Could not introduce github.com/cespare/xxhash@v2.1.1, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	v2.1.0: Could not introduce github.com/cespare/xxhash@v2.1.0, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	v2.0.0: Could not introduce github.com/cespare/xxhash@v2.0.0, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	v1.1.0: Could not introduce github.com/cespare/xxhash@v1.1.0, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	v1.0.0: Could not introduce github.com/cespare/xxhash@v1.0.0, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	master: Could not introduce github.com/cespare/xxhash@master, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	base-for-ongardie-ebay-allocs: Could not introduce github.com/cespare/xxhash@base-for-ongardie-ebay-allocs, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	bench-module: Could not introduce github.com/cespare/xxhash@bench-module, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	digest: Could not introduce github.com/cespare/xxhash@digest, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	ongardie-ebay-allocs-followup: Could not introduce github.com/cespare/xxhash@ongardie-ebay-allocs-followup, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	sse: Could not introduce github.com/cespare/xxhash@sse, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	uninline: Could not introduce github.com/cespare/xxhash@uninline, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	v2: Could not introduce github.com/cespare/xxhash@v2, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	v2-binary-marshaler: Could not introduce github.com/cespare/xxhash@v2-binary-marshaler, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	v2-cleanup: Could not introduce github.com/cespare/xxhash@v2-cleanup, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	v2-remove-18-fallback: Could not introduce github.com/cespare/xxhash@v2-remove-18-fallback, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
	writeBlocks-slice-pointer: Could not introduce github.com/cespare/xxhash@writeBlocks-slice-pointer, as its subpackage github.com/cespare/xxhash/v2 is missing. (Package is required by github.com/prometheus/client_golang@v1.7.1.)
----------------------------------------
[ ERROR(1) ]
--------------------------------------------------------------------------------------------------------------------------------

__Expected behavior:__
dep init should be passed and Gopkg.toml file should be created at appropriate location.
__Actual behavior:__
dep init failed with abive ERROR
__Environment info:__

* System info: Run `uname -srm` and copy the output here
out put of `uname -srm` -> Linux 4.19.0-9-amd64 x86_64

* InfluxDB version: Run `influxd version` and copy the output here
InfluxDB shell version: 1.4.3

**Comment by russorat** [comment]
@fti-cneve thanks for the issue. you can follow the steps here for building locally: https://github.com/influxdata/influxdb/blob/1.8/CONTRIBUTING.md#build-and-test

**Comment by dgnorton** [comment]
@fti-cneve InfluxDB >= 1.8.0 uses Go modules for dependency management. https://github.com/influxdata/influxdb/pull/16944
