### ISSUE TITLE
keyValues() doesn't work if keyColumns order doesn't match column order

### ISSUE THREAD

**Issue by markddavidoff** [influxdata/influxdb#19134]
__Expected behavior:__
`|> keyValues(keyColumns: ["stat3", "stat2", "stat1"])`  returns rows for each of those stats no matter what order the columns are in.

__Actual behavior:__
if columns are ordered "stat1", "stat2", "stat3"
`|> keyValues(keyColumns: ["stat3", "stat2", "stat1"]) `
only returns a row for stat3

__Environment info:__
Influx db cloud 2.0

**Comment by nathanielc** [comment]
@markddavidoff Thanks for the clear bug report, we will take a look.
