### ISSUE TITLE
Cannot access object using a variable key

### ISSUE THREAD

**Issue by markddavidoff** [influxdata/influxdb#19145]
__Expected behavior:__
IDToName = {
  "1234": "something"
}
IDToName[r._value] returns "something"

__Actual behavior:__
IDToName = {
  "1234": "something"
}
IDToName[r._value] raises  type error @8:42-8:54: `expected [t4999] but found {1234:string | {}}`
when converting the _value to a string using interpolation or the string function to be safe, we get: ` expected int but found string`

**Comment by nathanielc** [comment]
@markddavidoff Flux does not support dynamic lookup of values in its objects. From the name in the example it looks like you are trying to map an `id` value to a `name`, this can be accomplished using either a `join` or if the data is static a set of `if else` statements. If you provide some more context on the use case I can help point you in the Flux way to accomplish the task.

**Comment by markddavidoff** [comment]
you can maybe bump this to a feature request as it would really simplify some things, i ended up with a function with a long if else block.

**Comment by nathanielc** [comment]
@markddavidoff Yes we are looking into it. Here is the issue if you want follow along https://github.com/influxdata/flux/issues/2765

**Comment by rickspencer3** [comment]
since influxdata/flux#2765 is being implemented, I'm going to go ahead and close this. However, please feel free to reopen it if I am mistaken.
