### ISSUE TITLE
Welcome to the InfluxDB community icon is not showing

### ISSUE THREAD

**Issue by navnit0707** [influxdata/influxdb#19147]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...go to https://www.influxdata.com/developer-jobs/
2. ... all logo is loading but influxdb community logo is not loading
3. ... tried in all browser

__Expected behavior:__
to be shown like others

__Actual behavior:__
not showing logo

![Screenshot (411)](https://user-images.githubusercontent.com/40719341/88858590-d5b86880-d215-11ea-8023-99f978afd9a6.png)
![Screenshot (410)](https://user-images.githubusercontent.com/40719341/88858602-da7d1c80-d215-11ea-9798-6b4133bea424.png)

**Comment by navnit0707** [comment]
\claim

**Comment by danxmoran** [comment]
Seems fixed now, closing this
