### ISSUE TITLE
In a dashboard, changing the time range with an existing query loading should cancel the existing query. Right now it doesn’t.

### ISSUE THREAD

**Issue by philjb** [influxdata/influxdb#19142]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. In as dashboard with at least one cell query that takes some time (>10s) to load.
1. Load the dashboard and while the slow cell is loading, change the time range of the dashboard (such as making it very short so queries load fast).
1. The existing cell query will continue loading the previous request and won't start loading the new time range until the previous is finished.

__Expected behavior:__

Queries should cancel loading on new load requests. A cancel button would be nice too or perhaps clicking the seconds load hourglass cancels slow queries.

__Actual behavior:__
Slow queries never stop until hard page refresh, timeout, or the query finishes on it's own.

__Environment info:__

C2 UI

__Config:__

NA

**Comment by philjb** [comment]
Changing a variable should also cancel an existing query that is still loading (if the variable is involved in the query).

**Comment by Asalem1** [comment]
@philjb can you confirm whether this is still an issue? Checking the network tab now and I can't seem to reproduce it. With the network tab open, it looks like both changing the timerange and the variable will cancel the query and trigger a new set of queries

**Comment by philjb** [comment]
Yes! I agree! It seems much improved now. Thanks for the efforts.

I also see in the network tab that earlier queries are cancelled (they show as having an "Error") and the new queries load. It also feels/appears to work this way too when I click around in my dashboards and adjust variables and time ranges.
