### ISSUE TITLE
InfluxDb with MQTT The Things Network

### ISSUE THREAD

**Issue by Hircus** [influxdata/influxdb#19168]
Hi! This is my first request so i hope i am writing it right:

Proposal:
Connecting The Things Network devices to InfluxData with mqtt plugin and then visualize data in Grafana

Current behavior:
There is a connection but no data from TTN is available in _measurement or _field, as shown in the image below
![Influx](https://user-images.githubusercontent.com/48201861/89042136-bd943680-d346-11ea-80fa-c86438a77595.png)

Desired behavior:
Under My Bucket should be some data from TTN

If need in some other info please contact me,
Thank you for the support

**Comment by russorat** [comment]
@Hircus thanks for the issue. is there any way you can verify that data is being sent to mqtt from TTN? Can you check with another mqtt consumer client that you are familiar with?

**Comment by Hircus** [comment]
@russorat No, actually i am just starting to work with these technologies. Any advice?

**Comment by timhallinflux** [comment]
@Hircus -- have you gone through this? https://thethingsstack.io/integrations/cloud-integrations/influxdb-cloud/influxdb-cloud-setup/

**Comment by Hircus** [comment]
@timhallinflux thanks for the replay but in the end I found out that was easier than i thought. I should close this topic
