### ISSUE TITLE
Community Templates UI: Unit Tests

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#19174]
#### Background
Unit tests. They're good for simple functions. We'll want to write them against the utils and api functions, and maybe the reducers and actions.

#### Acceptance Criteria
- [x] We have tests for the util functions that handle filename and github url manipulation
  - `getTemplateDetails`
    - There are three exit conditions from this function (including a `throw`), all based on the value of `source`, the argument passed in. I want you to write code that triggers those three exit conditions, then describe the behavior of the functions in each case through jest assertions. You'll have to look up how to assert that an error was thrown in `jest` most likely.
  - `getGithubUrlFromTemplateDetails`
    - This returns a string built from the arguments passed in. A couple of different examples of the string being built the way we expect would be helpful. 
- [x] We have tests for the api functions that make calls to the templates API
  - If we mock the network / API request to the pkgr API, we should be able to make these simple unit tests
  - Bucky can help you out with the mocking
  - `reviewTemplate`, `installTemplate`, `fetchStacks`, `deleteStack`, `updateStackName`
- [x] We have tests for the community templates reducers
  - `SET_COMMUNITY_TEMPLATE_TO_INSTALL`, `TOGGLE_TEMPLATE_RESOURCE_INSTALL`, `SET_STACKS`, `DELETE_STACKS`
  - These will be simple tests of the form: make a call to a redux action, inspect the state, assert it matches the value we expect based on what we called into the action
- ~We have tests for the community templates action creators~
  - ~These will be similar to the redux tests: make a call to a redux action and assert that the state matches what we expect - it might make sense to combine these~
- [ ] We have tests for the community templates thunks
  - A single thunk: `fetchAndSetStacks`, which fetches stacks from the api, then sets them into redux in one function call
  - This is another example of where we'll need to mock API calls to make these unit tests

**Comment by desa** [comment]
finished
