### ISSUE TITLE
Quotation marks (and likely other special characters) in bucket name is accepted on bucket creation but queries fail for all data

### ISSUE THREAD

**Issue by Mierpo** [influxdata/influxdb#19179]
List the minimal actions needed to reproduce the behavior.

1. Create a bucket called ["Foobar" 2020-08-03 12:07:40.409 uuid-of-an-experiment] with quotation marks without [ and], with a couple of tags
2. Go to influxdb data explorer UI and try to load the tag list
3. Notice "Failed to load tag keys" in UI and in browser HTTP debugger Network request: 400 - error @1:yy-1:xx: undefined identifier Foobar

__Expected behavior:__
Invalid bucket name shouldn't even be accepted if the queries cannot work for it. Sanitize the bucketname requested or fail the request immediately, with a descriptive error message like "Invalid character \" detected".

Alternatively, support special characters like questions marks in the queries being performed by the explorer so that the identifier attempted is "Foobar" not Foobar.

__Actual behavior:__
Bucket is created, but querying tags and showing data fails. In UI it looks like a problem with the tags or data, but in reality the problem is the bucket name.

__Environment info:__

influxdb running as a linux container

Image: quay.io/influxdb/influxdb:2.0.0-beta
Image ID: c25b1da9b9cc (I believe this is beta 15?)

**Comment by russorat** [comment]
@Mierpo thanks for the issue. We will take a look.
