### ISSUE TITLE
Cant clone dashboard cell

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#19192]
![cant-clone-cell](https://user-images.githubusercontent.com/1477539/89236510-a43cf580-d5a5-11ea-89ee-0b38ac4b8619.gif)

**Comment by desa** [comment]
we suspect https://github.com/influxdata/influxdb/commit/4a410559115ba9246ff7c859cc6f73f4afef97ae is the issue

**Comment by Asalem1** [comment]
Gonna mark this one as closed since this was resolved with the revert
