### ISSUE TITLE
insert with specified time silently fails if time is in the future

### ISSUE THREAD

**Issue by m-mcgowan** [influxdata/influxdb#192]
My app is intended to use UTC time, but I had a failing test case that wasn't inserting any 
test data.  

[...snip...  hours of debugging and playing with http://hurl.it to try to figure out why no rows were inserted]

Long story short: if the specified time is in the future, the insert silently fails, but returns HTTP response 200.  

In my case, the time used in the test was created in my time-zone which is UTC+1, and so in the future compared to UTC time.  

Possible resolutions of this bug could be either an explicit failure message, or support for future times. For example, for simulation/planning work, storing a computed/predicted time series would be useful.

**Comment by litchfield** [comment]
Just ran into this too :frowning:

**Comment by beckettsean** [comment]
@litchfield on 0.8 or 0.9? If 0.9, what exact version? 

This issue references an 0.8 problem, and I know from experience that submitting points in the future works just fine in 0.9.0-0.9.3.

**Comment by julienvienne** [comment]
Hello,
In my experience, the problem still there in the 0.12 release.
I'm simply unable to write points in the future.

Date in future : 
$ date -d '@1460738281'
vendredi 15 avril 2016, 18:38:01 (UTC+0200)

$ curl  -X POST 'http://server01:8086/write?db=test_database' --data-binary 'measurement_test value=68.67 **1460738281**000000000'
-> Result : No measurement saved in test_database

Any workaround would be appreciated

Best regards,

**Comment by julienvienne** [comment]
Oops, adding  **time < now() + 5d**criteria in select did the job.
Sorry for the noise.

**Comment by beckettsean** [comment]
For future reference: http://docs.influxdata.com/influxdb/v0.12/troubleshooting/frequently_encountered_issues/#querying-after-now

**Comment by geordie-dostal-qxbranch** [comment]
This page has the incorrect values for max and min long:
Smallest valid timestamp: -9023372036854775808 (approximately 1684-01-22T14:50:02Z)
Largest valid timestamp: 9023372036854775807 (approximately 2255-12-09T23:13:56Z)

Should be 92... not 90...

**Comment by beckettsean** [comment]
@geordie-dostal-qxbranch can you [open an issue](https://github.com/influxdata/docs.influxdata.com/issues/new) on the Docs repo, please?
