### ISSUE TITLE
I'm still seeing Bug #18026 exhibited on the InfluxDB Cloud 2.0 interface

### ISSUE THREAD

**Issue by gefaila** [influxdata/influxdb#19202]
This is identical to the bug
https://github.com/influxdata/influxdb/issues/18026

I won't describe it again. 

Just to confirm it still exists on InfluxDB 2.0 Cloud interface.  I'm using both Chrome and Firefox.

I do note that a workaround is to refresh the editing page in the browser.
e.g. the one like https://xxx.aws.cloud2.influxdata.com/orgs/xxxxxx/dashboards/xxxxxx/cells/xxxxxx/edit

However this issue prevents the use of the editor for editing which is fundamental

Can we re-open the previous issue?
Or confirm when it's coming through on Cloud 2.0?

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by desa** [comment]
@gefaila which OS are you using?

**Comment by gefaila** [comment]
Windows 10

**Comment by gefaila** [comment]
> Just to confirm it still exists on InfluxDB 2.0 Cloud interface. I'm using both Chrome and Firefox.

**Comment by Asalem1** [comment]
@gefailia, are you still experiencing this issue?

**Comment by fipso** [comment]
Having the same issue in the latest docker image
