### ISSUE TITLE
Grouping in query builder persists a `group()` function in query even if decision is reversed

### ISSUE THREAD

**Issue by samhld** [influxdata/influxdb#19216]
When selecting the `Group` option in a query builder "card"(?) and then unselecting it (changing back to filter because...maybe you decided not to group), a `group()` function is injected into the generated query anyways.  This yields unexpected results.

![in mp4](https://user-images.githubusercontent.com/146112/89354762-8f786480-d66e-11ea-9b92-cb491c407e59.gif)

**Comment by Palakp41** [comment]
Moving this issue back to backlog. I tried fixing this with this pr: https://github.com/influxdata/ui/pull/347 but fixing the group selection breaks other parts of the data explorer like `imports`. The code is very complicated around data explorer's state management. Will need to take a look at this again with fresh eyes.
