### ISSUE TITLE
Proposal: Fix for legacy buckets in bucket list APIs

### ISSUE THREAD

**Issue by GeorgeMac** [influxdata/influxdb#19226]
Related: #19189

The current implementations for listing / reading legacy system buckets leave something to be desired. It also frequently breaks pagination.

-  `kv`: https://github.com/influxdata/influxdb/blob/fe5e57934ede3019936b4ec98d455f772b9ccb07/kv/bucket.go#L353-L381
- `tenant`: https://github.com/influxdata/influxdb/blob/fe5e57934ede3019936b4ec98d455f772b9ccb07/tenant/service_bucket.go#L139-L169

This is a proposal to address it (mostly) once and for all. Or at least until we actually create a migration strategy for legacy data (from old buckets to new).

The proposal is to add a quick lookup in the name index for these buckets before listing.

## Implementation

1. On an org scoped call to find buckets:
2. Do a lookup for `bucketsindexv1/<orgID>/_tasks` if not present set `needsLegacyTasks := true`.
3. Do a lookup for `bucketsindexv1/<orgID>/_monitoring` if not present set `needsLegacyMonitoring := true`.
4. (a) If request is for first page, then add respective legacy system buckets to beginning of response and adjust `offset` and `limit` accordingly.
4. (b) if request is for non-first page then decrement offset based on number of legacy buckets.
5. Request page based on adjusted offset.

## Success Criteria

- a request for up to 20 buckets returns no more than 20 buckets. Sometimes it returns 22 for legacy accounts.
- given an account where their non-legacy buckets do not exist in the first page, the legacy buckets are not wrongfully added to the response.
- everything continues to work, but not broken like it is today.

**Comment by stuartcarnie** [comment]
@GeorgeMac / @AlirieGray I'm going to recommend we only land this fix after the split, as I can simply remove this check from OSS given we're about to restart users running existing OSS 2.x versions

**Comment by GeorgeMac** [comment]
Good shout @stuartcarnie
