### ISSUE TITLE
Operator precedence for exponents

### ISSUE THREAD

**Issue by JamesJeffryes** [influxdata/influxdb#19236]
Standard [order of operations](https://en.wikipedia.org/wiki/Order_of_operations) gives exponentiation precedence over multiplication and division. The [current operator precedence documentation](https://v2.docs.influxdata.com/v2.0/reference/flux/language/operators/#operator-precedence) does contain exponents but it appears to treat them as the same precedence as multiplication.

__Steps to reproduce:__

There's probably a better way to test this but I used a map function in the data explorer like so:
```
from(bucket: "demo")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "go_info")
  |> filter(fn: (r) => r["_field"] == "gauge")
  |> map(fn: (r) => ({r with _value: 5.0 * 1.0 ^ 5.0}))
```

__Expected behavior:__
Exponents should should be evaluated before multiplication or division.
5 * 1 ^ 5 = 25
1 ^ 5 * 5 = 25

__Actual behavior:__
Exponents seem to be evaluated on the same precedence level as multiplication or division.
5 * 1 ^ 5 = 3125
1 ^ 5 * 5 = 25

__Environment info:__

Linux 4.15.0-76-generic x86_64 (Docker)
InfluxDB 2.0.0-beta.14 (git: c8af0f35be) build_date: 2020-07-08T20:42:23Z

**Comment by nathanielc** [comment]
@JamesJeffryes Thanks for the bug report, our specification of the language states that exponentiation should be above multiplication/division but is seems that we have a bug. https://github.com/influxdata/flux/blob/master/docs/SPEC.md#operators-1 

We will get this fixed.

**Comment by Bolladeen** [comment]
I am going to close this issue given that PR: https://github.com/influxdata/flux/pull/3197 fixes this bug.
