### ISSUE TITLE
[UI - Create Check] - Window period input disabled 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#19249]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open Alerts > "+ Threshold Check"
2. Define a query with query builder
3. Change the default Window Period

__Expected behavior:__
Expected to be able to set a default window period.  Either with a custom tab, as now exists in time machine for dashboard cells, or by clicking on and activating the edit field as in the past. 

The reason is that some data represent events that occur much quicker or much slower than what might be suitable for a ten second data window.  New data points might be generated only once a minute, or might be generated every few nanoseconds, in which case a finer or coarser window frame would be desired. 

__Actual behavior:__
Window period input is disabled. 

The question is whether this behavior is by design, or whether it is a side effect from recent time machine changes made elsewhere. 

__Screenshot__

![CreateCheckWindowPeriodDurationDisabled](https://user-images.githubusercontent.com/25881301/89657998-458db980-d8ce-11ea-9aa0-a98e565bded5.png)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-112-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly builds 
```
ts=2020-08-07T07:40:54.782532Z lvl=info msg="Welcome to InfluxDB" log_id=0OTygvVW000 version=2.0.0-beta.15 commit=65d9b2c088 build_date=2020-08-07T05:20:47Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: **Chrome 84**

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled. 

```
--e2e-testing=true
```

**Comment by ebb-tide** [comment]
This is expected behavior as part of the auto aggregation 👍
