### ISSUE TITLE
influxdb_client_2.0.0-beta.15_darwin_amd64 task run list not working as expected

### ISSUE THREAD

**Issue by markddavidoff** [influxdata/influxdb#19247]
Hi! I’m having some issues with the influx cli on mac, seems like the filters for influx task run list do not function as expected. 

- a) it does not seem the `--after` or `--before` args are respected as the returned data is outside of those bounds
- b) the`--limit` argument is required even though the documentation does not specify that. Omitting it errors with ` run limit is out of bounds, must be between 1 and 500.` whereas i would expect a default

Running on mac with 
influxdb_client_2.0.0-beta.15_darwin_amd64

**Comment by markddavidoff** [comment]
perhaps my after/before args are incorrect, here is what i passed:
`--after 2020-08-06T17:30:00Z --before 2020-08-06T18:00:00Z `

**Comment by markddavidoff** [comment]
seems like the api doesn't work either?
`https://<host>/api/v2/tasks/<task id>/runs?afterTime=2020-08-06T17:30:00Z&beforeTime=2020-08-06T18:00:00Z` returns data outside of the time as well?

**Comment by rickspencer3** [comment]
@RohanSreerama5 I'm 90% certain that this regarding Cloud 2.0

**Comment by markddavidoff** [comment]
Yes, sorry, forgot to specify the influx version its cloud 2.0

**Comment by russorat** [comment]
I can confirm that `beforeTime` and `afterTime` seem to have no effect on the run results returned.
