### ISSUE TITLE
Query bucket to get schema in background and cache it

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#19255]
The goal of this issue is to enable more experimentation around schema exploration and query building experiences. Since the schema does not change often our assumption is that it is safe to cache it on a regular interval (maybe every 24hrs?). For users with high cardinality this query will be extremely slow, but we aim to create a good UX for most users before the power users.

```
import "influxdata/influxdb/v1"
from(bucket: "<foo>")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> first()
  |> v1.fieldsAsCols()
```

Talk to @desa about the query here

- [ ] Store the schema in a shape that is easy to navigate and display in a component like the query builder

**Comment by Asalem1** [comment]
Here is what the current iteration of the schema for the flows query builder should look like:
```
{
  [measurement]: {
    type: [measurement_type],
    fields: [ ...field_names],
    tags: {
      [tag_name]: [...tag_values as string[]],
      ...
    },
  },
 ...
}
```

**Comment by desa** [comment]
what does `measurement_type` mean?

**Comment by alexpaxton** [comment]
@desa I believe that's `string` | `int` etc. but might not be necessary since they are all strings

**Comment by Asalem1** [comment]
This should be done once this PR gets merged into the UI repo:

https://github.com/influxdata/ui/pull/32
