### ISSUE TITLE
Additional visualization types

### ISSUE THREAD

**Issue by bckeene** [influxdata/influxdb#19259]
__Proposal:__
Alongside the current visualization types (Graph, Graph + Single Stat, Heatmap, Histogram, Singles Stat, Gauge, Table, and Scatter), InfluxDB's UI should contain additional options.

__Current behavior:__
As of August 2020, the following visualization types are supported:

![Screen Shot 2020-08-07 at 2 45 50 PM](https://user-images.githubusercontent.com/3768387/89691117-fb500c80-d8bc-11ea-88fa-c622a532deef.png)

__Desired behavior:__
Additional visualization types.

__Alternatives considered:__
Other visualization tools such and Grafana offer a more complete selection of visualization types. 

__Use case:__
I'd recommend users add comments to request a specific new visualization type. Demand can then be measured via likes.

**Comment by bckeene** [comment]
Request for Pie Chart visualization type.

**Comment by totkeks** [comment]
Adding single text based on value to the list.

E.g. green OK or red NOK for a server/container status cell.

**Comment by bckeene** [comment]
Closing issue as requests for UI additions should be filed as individual issues.
