### ISSUE TITLE
do not use v.windowPeriod in the derivative unit param

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19256]
right now, clicking on `derivative` or `non negative derivative` in the UI inserts 
```
 |> derivative(unit: v.windowPeriod, nonNegative: false)
```

but the unit isn't a window period.

most likely, they want something like this:
```
  |> aggregateWindow(every: v.windowPeriod, fn: max)
  |> derivative(unit: 1s, nonNegative: false)
```

~~We may need to update the label in the UI but i'm not sure.~~

### Acceptance Criteria
- Hard code derivative to 1 second in the UI. And also the nonNegative derivative as well.

**Comment by kristinarobinson** [comment]
Hard code derivative to 1 second in the UI.  And also the nonNegative derivative as well.

**Comment by russorat** [comment]
fixed in https://github.com/influxdata/influxdb/pull/19776, but it needs to get added to the UI repo
