### ISSUE TITLE
We should enforce the identifier requirement on the variable name

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/influxdb#19263]
It is currently possible to create a variable with a name that is not a valid identifier.
The variable later will be included in a prelude file and sent to the Flux LSP for language diagnostics. Those invalid names will mess with the parsing and cause weird behaviors like the one described in https://github.com/influxdata/influxdb/issues/18965.

We should enforce the identifier requirement on the variable name so that this kind of problem won't show up again.

**Comment by desa** [comment]
@yzhang1991 awesome. Great find. Any idea what we do about clusters that have invalid identifiers already?

**Comment by yzhang1991** [comment]
I guess you probably can convert them into snake case?
