### ISSUE TITLE
Duplicate data in DB 

### ISSUE THREAD

**Issue by fxfactorial** [influxdata/influxdb#19262]
I saw this open issue and it seems there is still an issue with duplicate data, or perhaps I'm querying incorrectly https://github.com/influxdata/influxdb/issues/13989

This is my query kicked off via the golang sdk , on 1.8 , but i confirmed the results on the chronograf 

```
from(bucket: "pairs/")
	  |> range(start: -7d)
	  |> filter(fn: (r) =>
       r._measurement == "ETH-USD" and
       (r._field == "price" and r.side == "buy")
    )
	  |> toFloat()
	  |> timedMovingAverage(every: 12h, period: 1d)
    |> sort(columns: ["_time"])
```

printing out the golang map, I get

```
map[_field:price _measurement:ETH-USD _start:2020-08-01 22:36:23.400033863 +0000 UTC _stop:2020-08-08 22:36:23.400033863 +0000 UTC _time:2020-08-08 22:36:23.400033863 +0000 UTC _value:389.40864406779684 exchange:coinbase result:_result side:buy table:0]
map[_field:price _measurement:ETH-USD _start:2020-08-01 22:36:23.400033863 +0000 UTC _stop:2020-08-08 22:36:23.400033863 +0000 UTC _time:2020-08-08 22:36:23.400033863 +0000 UTC _value:389.40864406779684 exchange:coinbase result:_result side:buy table:0]
```

and the chronograf duplicate 
![Screenshot from 2020-08-08 18-42-31](https://user-images.githubusercontent.com/3036816/89721065-d8415d80-d98d-11ea-899a-2a7b4fb13e7a.png)

today is my first day every touching flux so its possible I'm writing the query wrong, but I am def surprised to see two exact same rows produced

**Comment by russorat** [comment]
@fxfactorial sorry for the delay here. did you ever figure out what was happening here? 

if not, is it possible to narrow the time frame and provide sample data?

**Comment by fxfactorial** [comment]
no, didn't figure out , have since stopped using influxdb, can close if like
