### ISSUE TITLE
protobuf dependency needs to be updated

### ISSUE THREAD

**Issue by rockstar** [influxdata/influxdb#19269]
When trying to update influxdb to flux v0.78.0, the protobuf dependency was updated from `1.3.1` to `1.4.2`. This raised a deprecation issue where github is no longer the authoritative source, and also requires some API changes to influxdb. The upgrade also _appears_ to change the marshalling format for protobufs, so wasn't an easy change to make. This is all captured in #19264 

In flux, support for BigTable merged (influxdata/flux#2925), which brought updated dependencies, forcing the protobuf update. That PR will be reverted temporarily, and its changes will be blocked until this issue can be addressed.

**Comment by timhallinflux** [comment]
@rockstar -- ready to re-review this?

**Comment by rockstar** [comment]
This was just merged.
