### ISSUE TITLE
GET /api/v2/dashboards doesn't respect limit and offsets

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/influxdb#19274]
I called /api/v2/dashboards?descending=false&limit=5&offset=0&orgID=844910ece80be8bc, expecting to only get the first 5 dashboards, but I got all the dashboards in the organization.

**Comment by KevinSmile** [comment]
Yes. I found that if you specify `orgID`, then this API will ignore your `limit`, `offset`, etc. (without specifying `orgID`, it works fine)
BTW,  it seems that the swagger document does not expose params like `limit`, `offset` now.
https://v2.docs.influxdata.com/v2.0/api/#operation/GetDashboards

I'm trying to fix it.
