### ISSUE TITLE
flux cannot query all data with retention policy 1d

### ISSUE THREAD

**Issue by ciys** [influxdata/influxdb#19275]
__Steps to reproduce:__
detail is here https://github.com/influxdata/influxdb-client-go/issues/172
first i think it is client bug,but i try in chronograf still not work,and after restart influxdb everything is ok...

__Expected behavior:__
query all data

__Actual behavior:__
query part data

__Environment info:__

* System info: linux 3.10.0-862.el7.x86_64 x86_64
* InfluxDB version: 1.8.0
* Other relevant environment details: 

__Config:__
fflux-enabled = true

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by russorat** [comment]
@ciys sorry for the delay here. is this still an issue?

**Comment by ciys** [comment]
@russorat ,it is not issue now.i insert local time zone into inflxdb,but the influxdb think it is utc time zone.so when query with flux,the time range is not right.
