### ISSUE TITLE
Legend format on line graph is incorrect when not all series have values for every tag

### ISSUE THREAD

**Issue by andyflatt** [influxdata/influxdb#19282]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. I am using Influx Cloud 2.0
1. Use this input:
```
temperature,sensor_id=weatherstation,room=outside temperature=31.629999999999995
temperature,sensor_id=28-0301a279571e,room=office,position=toptank temperature=33.75
temperature,sensor_id=28-0301a27981fd,room=office,position=bottomtank temperature=28.625
temperature,sensor_id=28-0301a279822c,room=office,position=air temperature=31.937
```
2. Create a graph cell on a dashboard with the query:
```
from(bucket: "andflatt's Bucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "temperature")
  |> filter(fn: (r) => r["_field"] == "temperature")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```
3. Hover over the values and the legend does not handle the empty space.

__Actual behavior:__
![Screenshot 2020-08-11 at 18 16 21](https://user-images.githubusercontent.com/8034630/89927836-d500d880-dbfe-11ea-8843-d80b651e4b07.png)

__Expected behavior:__
I would expect it to render correctly.  If I refresh the page so the empty series is at the bottom it formats correctly.
![Screenshot 2020-08-11 at 18 15 46](https://user-images.githubusercontent.com/8034630/89927881-e8ac3f00-dbfe-11ea-8a15-432f59d90a76.png)

__Environment info:__

Using Influx Cloud 2.0, please let me know the details you need from this.

**Comment by russorat** [comment]
@andyflatt thanks for opening this. I've seen it as well. we are investigating.
