### ISSUE TITLE
UI Polish: Make it clear that yaml / json files should be uploaded

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#19286]
#### User Story
As a user, I want to know what I should be pasting into the Lookup Template input field

#### Background
The file upload module has the ability to whitelist file types and show errors when they are not provided.

#### Acceptance Criteria
- There are instructions that make it clear that yaml / json / jsonett files are needed by the form

**Comment by desa** [comment]
no longer relevant
