### ISSUE TITLE
OSS 2.x TSM migration tool

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#19289]
## What

Users of OSS 2.x alphas will have TSM data in an incompatible format once https://github.com/influxdata/influxdb/tree/sgc/tsm1 is merged. 

To ease their transition to newer builds, a tool would be required to convert the existing TSM data back to the original TSM 1.x format. This tool should replace the existing implementation of the `influxd migrate` command.

See PR #17016 as a template for the original conversion tool, which sets expectations accordingly.

### Line Protocol

It is possible for a user to export and re-import all their data as line protocol, but this approach will be intolerable for most data sets. For example, Edd noted he had 12MB of on-disk TSM data that expands to 7.5GB of line protocol.

**Comment by 8none1** [comment]
@sebito91 please roll this in to the plans for Migrate-o-tron.

**Comment by sebito91** [comment]
Sure thing, good time as any!

**Comment by 8none1** [comment]
@benbjohnson I feel like this could be closed, since we now have the ability to import tsm.  If you agree please close this.
