### ISSUE TITLE
Upgrade Flux to latest version

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#19302]
## What

Upgrade Flux to latest version in OSS 2.0

### Success

OSS 2.0 is running the latest version of Flux and all tests are passing

**Comment by stuartcarnie** [comment]
This represents a significant amount of work as it is 0.66.2, which is the version used by OSS 1.x. I do not have a sense of whether it could be completed in a single sprint, as it requires introducing Rust, and potentially a number of other changes to the API.

**Comment by russorat** [comment]
tracking in https://github.com/influxdata/influxdb/issues/19468

**Comment by stuartcarnie** [comment]
Closed #19569
