### ISSUE TITLE
Add InfluxQL and V1 query API

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#19304]
## What

Add support for InfluxQL and `/query` API

**Comment by stuartcarnie** [comment]
I estimate this will take 3-4 weeks, to bring all the InfluxQL code and re-connect the DB/RP mapping service.

**Comment by stuartcarnie** [comment]
This support landed with 8a7dcc21fb482deb1ea7f873278e6850545f617f

**Comment by pauldix** [comment]
Wait, estimated at 3-4 weeks 3 days ago, landed and closed 15 hours ago? ;)

**Comment by stuartcarnie** [comment]
I was mostly concerned that the abstractions for mapping and interfacing with storage would required heavy refactoring. It turns out our abstractions were just right ;-)
