### ISSUE TITLE
cli: ability to specify a config profile as a flag

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19318]
when working across instances, sometimes you would like to pull from one and write to another. it would be great if you could do something like:

`influx query "from" --config dev | influx write --config prod`

or 

`influx export stack $STACK_ID | influx apply --active-config us-west`

**Comment by jsteenb2** [comment]
I'm largely in favor of `--active-config` with a `-c` short. The `--active-config` makes it very clear. And it disambiguates with the places where we have existing `--config` flags (`influx config [cmd]` commands)
