### ISSUE TITLE
Add -pps argument to influx write CLI

### ISSUE THREAD

**Issue by abalone23** [influxdata/influxdb#19335]
It would be convenient if the influx 2.0 CLI write command had a `-pps` argument to throttle points in order to alleviate write rate limit errors.

**Comment by sranka** [comment]
@abalone23 I am not much familiar with overall clients' POV, but I guess that the rate limits are specified in megabytes per minute. Wouldn't be better to specify --limitRate=number to specify max written megabytes per minute? 

The cost of the implementation is the same independently on the chosen units (lines/second MB/minute).

**Comment by abalone23** [comment]
@sranka I based it on the (1.x CLI](https://docs.influxdata.com/influxdb/v1.8/tools/shell/#influx-arguments):
> -pps How many points per second the import will allow. By default, pps is zero and influx will not throttle importing. Use with -import.

Your idea for `limitRate` would be better I agree.
