### ISSUE TITLE
Double display wrong

### ISSUE THREAD

**Issue by GF-Huang** [influxdata/influxdb#19361]
__Steps to reproduce:__
1. Add a batch of very small `double` into influxdb, such as `0.00123`, `0.00234`, `0.00345`...
2. Display it in Data Explorer.

### The actual data:

![image](https://user-images.githubusercontent.com/4510984/90540898-6f8b8980-e1b4-11ea-8a81-48d7aefc8b53.png)

### But display:

![image](https://user-images.githubusercontent.com/4510984/90541043-a1045500-e1b4-11ea-9fc0-d8d98025ab66.png)

__Expected behavior:__
It should display same as actual data like `0.00123456`.

__Actual behavior:__
But it display `1.12m`, what the `m` meaning?

__Environment info:__

* System info: `Windows 10 1909`
* InfluxDB version: `Version 2.0.0 (a3ff52d)`
* Other relevant environment details: `docker image quay.io/influxdb/influxdb:2.0.0-beta`

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/91884286-5c021780-ecb8-11ea-9def-bdecd127046e.png)

**Comment by russorat** [comment]
I'm not able to repro. Are there other details you can add to help?

Here's the LP i'm inserting:

```
a,t=t1 v=0.00123
a,t=t2 v=0.00234
a,t=t3 v=0.00345
```

```
from(bucket: "test")
  |> range(start: -1h)
  |> filter(fn: (r) => r["_measurement"] == "a")
```

![image](https://user-images.githubusercontent.com/4805997/91886047-95497180-ec3d-11ea-85e5-0d372dec56b5.png)
[2020-09-01-10-26_chronograf_data.csv.zip](https://github.com/influxdata/influxdb/files/5157867/2020-09-01-10-26_chronograf_data.csv.zip)

**Comment by GF-Huang** [comment]
I think the query does not matter, if all your `_value` are very small double number (such as `0.001 0.002 0.003`), it will duplicate.

**Comment by GF-Huang** [comment]
> ![image](https://user-images.githubusercontent.com/4805997/91886047-95497180-ec3d-11ea-85e5-0d372dec56b5.png)

Turn off the `View Raw Data` please, then hover your mouse on value curves.

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/91886981-b7360900-ecbc-11ea-983e-95dec621eeb2.png)

![image](https://user-images.githubusercontent.com/4510984/91887004-c321cb00-ecbc-11ea-8185-aae1d628ca57.png)

**Comment by russorat** [comment]
![image](https://user-images.githubusercontent.com/4805997/91886730-a181fe80-ec3e-11ea-876a-0d2e1a4cfce2.png)

ok, my apologies, i think i understand now. the data is coming back, this request is to display them in the legend differently. 

the `m` is for milli, so you would divide the values by 1000 to get the original numbers. But i agree, our legend should attempt to display more digits without manipulation.

**Comment by GF-Huang** [comment]
Understood, thank you.

**Comment by GF-Huang** [comment]
Still not change in `2.0-RC`?

**Comment by russorat** [comment]
This is being worked on for https://github.com/influxdata/giraffe/issues/208 and then we will incorporate it. thanks!

**Comment by russorat** [comment]
i believe this has been fixed.

i'm going to close this for now since it was opened against a pre-release version of influxdb. if you are still facing this problem, please open a new issue with the details.
