### ISSUE TITLE
Remove pkg/flux

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#19398]
## What

Once Flux is upgraded to the latest, the [`pkg/flux`](https://github.com/influxdata/influxdb/blob/f86fcd24d52a5c2b95ada3da09b98e8df00f7e5e/pkg/flux/README.md#L4) package can be removed and existing dependencies forward to `influxdata/flux`. This package was added to include APIs used by updates to options and tasks to ensure code continued to build.

**Comment by danxmoran** [comment]
I believe this was completed in #19569
