### ISSUE TITLE
Port rejected commits after Flux has been upgraded

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#19444]
## What 

Certain commits were rejected as they are incompatible with Flux 0.66 or the 1.x storage engine. 

These will need to be evaluated as to whether they will need to be ported again. The conflicts that require the latest Flux will be dependent on #19302.

revert(tasks): Revert fix(task/executor): Use correct name for last success time extern (#19435) via fde2129 cc/ @brettbuddin 
revert(tasks): Revert feat(task): Inject Task's LatestSuccess Timestamp In Flux Extern (#19402) via 1ae2541 cc/ @brettbuddin 
revert(flux): Revert feat: flux query profiler (#19359) via 6f805cb cc/ @yzhang1991
revert(flux): Revert Flux v0.82 upgrade via df41d42 cc/ @rockstar 
revert(storage): Revert feat(influxql): Implement DELETE & DROP MEASUREMENT 1501351 cc/ @benbjohnson 
revert(query): Revert feat: allow a metadata key to be required for a query to be logged (#19200) via 08cfb3f cc/ @adrian-thurston 
revert(flux): Revert feat(query/stdlib): add min and max to ReadGroup (#19158) via d48dc69 cc/ @fchikwekwe

**Comment by wolffcm** [comment]
Let's treat this as a checklist. Once we've upgraded Flux in OSS, let's make sure that all of these commits have been reapplied.

It seems like there will be build issues, etc, that mean all of these are needed for the upgrade.

**Comment by stuartcarnie** [comment]
Closed #19569
