### ISSUE TITLE
Remove "Save As Template" and "Import from Template" from the UI

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19447]
### Background 

We should remove Save as Template and From Template in the UI when working with Dashboards, Tasks, and Variables.

![image](https://user-images.githubusercontent.com/4805997/91341469-68551480-e78e-11ea-9d9a-0b2aec6f14cb.png)

![image](https://user-images.githubusercontent.com/4805997/91341500-730fa980-e78e-11ea-94e1-d88ab0699ccb.png)

### Acceptance Criteria
- Dashboards no longer have Save as Template and Import from template
- Tasks no longer have Save as Template and Import from template
- Variables no longer have Save as Template and Import from template

**Comment by hoorayimhelping** [comment]
https://github.com/influxdata/influxdb/pull/19300
