### ISSUE TITLE
influx write csv should ignore _start, _stop columns

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19452]
I have the following csv:

[sample.csv.zip](https://github.com/influxdata/influxdb/files/5133094/sample.csv.zip)

and when i run the following command:
`influx write dryrun -c default --format csv -f sample.csv`

it outputs LP with the _start and _stop columns:
```
smart_attribute,_start=2020-08-26T22:59:23.598653Z,_stop=2020-08-26T23:00:23.598653Z,device=disk1s3,host=ip-192-168-86-25.ec2.internal,model=APPLE\ SSD\ AP0512N,name=Host_Write_Commands,serial_no=C020245003DP9LF1T raw_value=127349468i 1598482780000000000
```

Those should be treated the same way that the `result` and `table` columns are and not written to the database.

i'm trying to enable the flow of 
`influx query -r -c prod 'from |> range' | influx write --format csv -b new_bucket`

**Comment by sranka** [comment]
It happens when the datatype annotation precedes the group annotation.
