### ISSUE TITLE
can not write csv data to influxdb2.0, get a error message that data type 'float' is not supported.

### ISSUE THREAD

**Issue by x-dongzi** [influxdata/influxdb#19474]
The version of influxdb is **influxdb_2.0.0-beta.16_linux_amd64**, the version of system is **CentOS Linux release 7.7.1908 (Core)**.
I follow the guide _Write CSV data to InfluxDB_ from https://v2.docs.influxdata.com/v2.0/write-data/developer-tools/csv/.
The example.csv is
```
#datatype measurement,tag,float,dateTime:RFC3339
m,host,used_percent,time
mem,host1,64.23,2020-01-01T00:00:00Z
mem,host2,72.01,2020-01-01T00:00:00Z
mem,host1,62.61,2020-01-01T00:00:10Z
mem,host2,72.98,2020-01-01T00:00:10Z
mem,host1,63.40,2020-01-01T00:00:20Z
mem,host2,73.77,2020-01-01T00:00:20Z
```
The write command is
`/influx write -o bbb -b ccc -f example2.csv -t hvHv0-X1wzouUe-qU-1IBInE5xU9DNJpxElnpC0GK4MxDraV5wvS_Qo9GqLinqnDGh3t-RShOALy-CdIMmNFFQ== --host http://localhost:9999`
Then I got the Error.
```
Error: Failed to write data: line 3: column 'used_percent': data type 'float' is not supported.
See 'influx write -h' for help
```
Below is the example.csv.
[example.csv.txt](https://github.com/influxdata/influxdb/files/5153197/example.csv.txt)

However, if I change the data type from 'float' to 'string'. It works. I can write the data into influxdb. Why is the 'float' not supported?
```
./influx write -o bbb -b ccc -f example.csv -t hvHv0-X1wzouUe-qU-1IBInE5xU9DNJpxElnpC0GK4MxDraV5wvS_Qo9GqLinqnDGh3t-RShOALy-CdIMmNFFQ== --host http://localhost:9999
[dong@centos-master influxdb_2.0.0-beta.16_linux_amd64]$ cat example.csv 
#datatype measurement,tag,string,dateTime:RFC3339
m,host,used_percent,time
mem,host1,64.23,2020-01-01T00:00:00Z
mem,host2,72.01,2020-01-01T00:00:00Z
mem,host1,62.61,2020-01-01T00:00:10Z
mem,host2,72.98,2020-01-01T00:00:10Z
mem,host1,63.40,2020-01-01T00:00:20Z
mem,host2,73.77,2020-01-01T00:00:20Z
```

**Comment by sanderson** [comment]
@x-dongzi The example in the documentation is incorrect and needs to be updated. Sorry about that. The correct way to specify a float column is with “double”, not “float”. I’ll make sure the documentation gets updated.

**Comment by x-dongzi** [comment]
> @x-dongzi The example in the documentation is incorrect and needs to be updated. Sorry about that. The correct way to specify a float column is with “double”, not “float”. I’ll make sure the documentation gets updated.

Thanks. Another question. If I want to write the integer into the influxdb. Which type I should set? I tried the type 'integer', but it did not work. Do we use the type 'double' as 'float' and 'integer'?

**Comment by sanderson** [comment]
@x-dongzi `long` is how you specify an integer. Annotated CSV data types are covered in the [Annotated CSV documentation](https://v2.docs.influxdata.com/v2.0/reference/syntax/annotated-csv/#data-types).
