### ISSUE TITLE
Community Templates UI: Only fetch readme one time

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#19470]
### Background
Currently, every time the the readme tab is mounted, it re-fetches the readme from github. We should only fetch it once and store the readme in redux.

### Acceptance Criteria:
- When the readme is initially fetched, it is stored in redux state
  - probably best to store it as an object with the key being the template directory: (here's an example, no meant to be prescriptive)
  - ```
      stagedCommunityTemplateReadmes: {
        'docker': '### Setup Instructions...',
        'csgo': '### Installation Instructions'...
      }
     ```
- Before the readme is fetched, the store is checked to see if the readme already exists in redux. If it does, just render that instead of re-fetching

**Comment by zoesteinkamp** [comment]
Closed by https://github.com/influxdata/ui/pull/45
