### ISSUE TITLE
Please stop publishing v9.9.9 releases

### ISSUE THREAD

**Issue by animedbz16** [influxdata/influxdb#19481]
__Proposal:__
Please stop publishing the v9.9.9 tag.

__Current behavior:__
We have set up monitoring of GitHub Releases via the RSS feed (https://github.com/influxdata/influxdb/releases.atom) and everytime a v9.9.9 release is published we receive a notification into our Slack Channel.

We set up monitoring of GitHub releases in this way so that we can easily be notified when various projects that we want to monitor are updated so we can review release notes and keep up to date.

So which this project, it appears that a v9.9.9 tag is continually updated overtime and is not a true release, but we receive many notifications saying that a new v9.9.9 tag is updated.

See attached image where we received 5 notifications just from today where v9.9.9 was published many times. Only 4 show up in the screenshot, but there is another one that occurred at 7:31 PM as well.

__Desired behavior:__
Stop publishing v9.9.9 tag

__Alternatives considered:__
N/A

__Use case:__
By not reusing published tags / releases, it will allow those that subscribe to the GitHub projects Release RSS feed to be notified when actual releases occur.

![software-rss-influx-releases](https://user-images.githubusercontent.com/2822632/91918512-1a11ab00-ec91-11ea-9487-33d15f28a2fb.png)

**Comment by gshif** [comment]
Thank you for pointing this out @animedbz16. I was testing the new release process and was not aware of a different way to do that. As of right now I have made changes that would not let me test the changes without sending notification when `fake` release is published.
