### ISSUE TITLE
Standardize the ENV variable for providing a config to influxdb

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19486]
According to this, it's INFLUX_CONFIG https://github.com/influxdata/influxdb/blob/81490d660482934d362783c3c09e5a107ef654ba/kit/cli/viper.go#L70

According to this, it's INFLUXD_CONFIG_PATH
https://github.com/influxdata/influxdb/blob/5e22e0101d8de7e0ee0836be96f778c3357f4a0f/cmd/influxd/launcher/launcher.go#L109

According to the docs, it's also INFLUXD_CONFIG_PATH
https://v2.docs.influxdata.com/v2.0/reference/config-options/#influxdb-configuration-file

This issue is to track down the right env var and ensure it works as indicated.

**Comment by stuartcarnie** [comment]
I can confirm this is not an issue and correctly loads a config file using the `INFLUXD_CONFIG_PATH` environment variable.

The file is read from here, noting that viper automatically prefixes the `CONFIG_PATH` with `INFLUXD`:

https://github.com/influxdata/influxdb/blob/81490d660482934d362783c3c09e5a107ef654ba/kit/cli/viper.go#L70

This was validated using the following environment variable:

```
INFLUXD_CONFIG_PATH=/some/path/to/config.yaml
```

where the config.yaml file contained the following:

```yaml
influxql-max-select-point: 500
storage-shard-precreator-check-interval: "10s"
```
