### ISSUE TITLE
Backup and Restore tests are failing 2.0 storage engine replacement 

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#19491]
Backup and restore tests started to fail after PR replacing storage 2.0 engine with one that is compatible with InfluxDB 1.x was merged into master.
Here is the link to failing backup and restore tests: https://app.circleci.com/pipelines/github/influxdata/influxdb/12400/workflows/272ca4f9-0bd6-4512-8c51-e5f93734dc61/jobs/146530

**Comment by stephanie-engel** [comment]
Created issue #19496

**Comment by stephanie-engel** [comment]
This is a known issue that Stuart documented here #19316
