### ISSUE TITLE
Building Influxdb 2.0 on Windows 64 bit

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#19526]

**Comment by danxmoran** [comment]
Duplicate of #17192

**Comment by Kungitoo** [comment]
This would def be nice. What are known issues? I tried doing a naive git clone -> build and see the syscalls need to be swapped to platform agnostic ones among other things like they did here I guess https://github.com/revel/revel/issues/1376

**Comment by danxmoran** [comment]
Closing this as a duplicate, please track #17192 for progress
