### ISSUE TITLE
iFrame has 401 error when set to valid Dashboard URL

### ISSUE THREAD

**Issue by jamesyu0725** [influxdata/influxdb#19524]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. In an HTML file, create a simple HTML file: 
```
<html>
<body>
    <iframe src="https://us-west-2-1.aws.cloud2.influxdata.com/orgs/{org Id}/dashboards/{dashboardId}?present=true&lower=now%28%29%20-%207d
    />
</body>
</html>

```

2. Open the HTML file. 

__Expected behavior:__
This was working properly, where the dashboard was embedded in the html page. 
![image](https://user-images.githubusercontent.com/28798702/92616998-7d4ca000-f284-11ea-85e6-2765872b4009.png)

__Actual behavior:__
Today, I am getting a 401 error with the same code? 
![image](https://user-images.githubusercontent.com/28798702/92617188-a3724000-f284-11ea-826b-e9d8d602ea5f.png)

__Environment info:__

* Environment: https://us-west-2-1.aws.cloud2.influxdata.com/
* InfluxDB version: 0b16127

__Config:__
N/A

__Logs:__
Include snippet of errors in log.
2.31d7fceab5.js:2 GET https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/me 401
(anonymous) @ 2.31d7fceab5.js:2
_e @ 2.31d7fceab5.js:2
Te @ 2.31d7fceab5.js:2
Promise.then (async)
Me.request @ 2.31d7fceab5.js:2
(anonymous) @ 2.31d7fceab5.js:2
(anonymous) @ 2.31d7fceab5.js:2
t.getMe @ 2.31d7fceab5.js:2
(anonymous) @ 2.31d7fceab5.js:2
(anonymous) @ 2.31d7fceab5.js:2
(anonymous) @ 2.31d7fceab5.js:2
(anonymous) @ 2.31d7fceab5.js:2
a @ 2.31d7fceab5.js:2
e.me @ 2.31d7fceab5.js:2
AD.checkForLogin @ 3.1f1209168b.js:1
componentDidMount @ 3.1f1209168b.js:1
za @ 2.31d7fceab5.js:2
Va @ 2.31d7fceab5.js:2
(anonymous) @ 2.31d7fceab5.js:2
t.unstable_runWithPriority @ 2.31d7fceab5.js:2
Rs @ 2.31d7fceab5.js:2
Ns @ 2.31d7fceab5.js:2
Es @ 2.31d7fceab5.js:2
ks @ 2.31d7fceab5.js:2
es @ 2.31d7fceab5.js:2
enqueueSetState @ 2.31d7fceab5.js:2
_.setState @ 2.31d7fceab5.js:2
componentDidMount @ 3.1f1209168b.js:1
async function (async)
componentDidMount @ 3.1f1209168b.js:1
za @ 2.31d7fceab5.js:2
Va @ 2.31d7fceab5.js:2
(anonymous) @ 2.31d7fceab5.js:2
t.unstable_runWithPriority @ 2.31d7fceab5.js:2
Rs @ 2.31d7fceab5.js:2
Ns @ 2.31d7fceab5.js:2
Es @ 2.31d7fceab5.js:2
ks @ 2.31d7fceab5.js:2
es @ 2.31d7fceab5.js:2
Ws @ 2.31d7fceab5.js:2
Hs @ 2.31d7fceab5.js:2
qs.render @ 2.31d7fceab5.js:2
(anonymous) @ 2.31d7fceab5.js:2
js @ 2.31d7fceab5.js:2
Us @ 2.31d7fceab5.js:2
render @ 2.31d7fceab5.js:2
(anonymous) @ 3.1f1209168b.js:1
o @ fab6b50869.js:1
Promise.then (async)
(anonymous) @ fab6b50869.js:1
o @ fab6b50869.js:1
(anonymous) @ fab6b50869.js:1
(anonymous) @ fab6b50869.js:1
2.31d7fceab5.js:2 Uncaught (in promise) Error: Request failed with status code 401
    at me (2.31d7fceab5.js:2)
    at 2.31d7fceab5.js:2
    at XMLHttpRequest.o.onreadystatechange (2.31d7fceab5.js:2)

__Performance:__
N/A

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by jamesyu0725** [comment]
I'm still debugging, but how I think if you can help me understand how to authenticate my iframe session. Then this would be resolved.

**Comment by russorat** [comment]
@jamesyu0725 thanks for the issue. embedding dashboards in an iframe isn't really something we support right now, but we want to enable the use case for setting this up in the future.

Can you describe your setup and we can make sure it makes it into the designs for this feature?

**Comment by jamesyu0725** [comment]
We can close this request. I'm going to use the giraffe solution, so that I dont need iFrames. Thanks. Sent from a mobile device. Please forgive any typos. 
James Yu
(e) jamesyu0725@gmail.com 
(c) 832.603.1572
-------- Original message --------From: Russ Savage <notifications@github.com> Date: 9/18/20  2:17 PM  (GMT-06:00) To: influxdata/influxdb <influxdb@noreply.github.com> Cc: James Yu <jamesyu0725@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [influxdata/influxdb] iFrame has 401 error when set to valid Dashboard URL (#19524) 
@jamesyu0725 thanks for the issue. embedding dashboards in an iframe isn't really something we support right now, but we want to enable the use case for setting this up in the future.
Can you describe your setup and we can make sure it makes it into the designs for this feature?

**Comment by jamesyu0725** [comment]
I found this github library very helpful around how to get around iFrame. https://github.com/influxdata/giraffe
