### ISSUE TITLE
Macos Catalina 10.15.6 start failed...

### ISSUE THREAD

**Issue by wzlee** [influxdata/influxdb#19556]
install influxdb successful, but start failure...
![image](https://user-images.githubusercontent.com/4182865/93063826-63a6c080-f6a9-11ea-86d5-bdbfe003d673.png)
Macos Catalina 10.15.6

**Comment by russorat** [comment]
@wzlee does the same happen when you upgrade to 1.8.2?

**Comment by wzlee** [comment]
brew need to update, run 'brew update' to resolve this problem。
