### ISSUE TITLE
Flux end-to-end test failing with "field type conflict"

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#19565]
The Flux end-to-end test `chronograf/aggregate_window_median_test.flux` is failing post-split with Flux upgraded to v0.83.1, with this error:
```
   --- FAIL: TestFluxEndToEnd/testing/chronograf/aggregate_window_median (0.14s)
            end_to_end_test.go:226: error calling function "inspect" @0:0-0:0: error calling function "case" @testing.flux|20:10-20:16: error calling function "loadStorage" @aggregate_window_median_test.flux|105:11-105:43: error calling function "chain" @9:9-12:3: field type conflict
```
This error message is not present in the `flux` repo and seems to be coming from storage.

The test will be skipped in `influxdb/query/stdlib/testing/testing.go`.

**Comment by nathanielc** [comment]
Could this be a field type conflict of the input data to the test case? If so then we should update the input data to be valid, so that the field has a consistent type.
