### ISSUE TITLE
Variable as URL argument (vars[]=) uses wrong variable

### ISSUE THREAD

**Issue by paulfirstimpression** [influxdata/influxdb#19563]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a 'master dashboard' with a table with links to a 'detail dashboard' using a variable argument in the URL
2. Example: https://eu-central-1-1.aws.cloud2.influxdata.com/orgs/e7cef85952bb6aef/dashboards/05e6fdd75a78a000?vars%5BNOC_Player_ID%5D=D5E89W002233
3. The detail dashboard that uses vars[NOC_Player_ID]=D5E89W002233 uses the wrong (previously uses) variable

__Expected behavior:__
Every time you open a dashboard with vars in URL

__Actual behavior:__
The wrong variable is being used

__Environment info:__

* System info: Win10, Chrome
* InfluxDB version: Cloud 2.0 Version (b24ed87)
* Refreshing the page solves the problem. 
* The problem has been patched before, but the bug is back now

**Comment by Palakp41** [comment]
This issue has been fixed by one of these: https://github.com/influxdata/idpe/issues/7700#issuecomment-697933856. Closing this issue.
