### ISSUE TITLE
Scatter does not adjust to time range after a data time gap

### ISSUE THREAD

**Issue by paulfirstimpression** [influxdata/influxdb#19573]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. [A] Post data every x minutes for a while (in my case every 1 minute)
    [B] stop posting data for a while (in my case 5 days)
    [C] start posting every x minutes (in my case every 1 minute)
2. If A and C are within the time range, scatter shows the correct time range.
3. If B and C are in the time range, only C is shown and stretched over the full width of the scatter view.
4. Switching to Graph shows the correct time range, raw data is correct,  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
5. Settings: X Column = _time | Y Column = _value | X and Y Axis Domain = Auto

__Expected behavior:__
Time range of scatter view is as selected (Past 1h/...), like it did before and like graphs do

__Actual behavior:__
The shown time range is a stretched view of the data timestamps (start=first measurement instead of start of selected time range, end=last measurement)

__Environment info:__

* System info: Win 10, Chrome
* InfluxDB version: V2 Cloud - Version (2ce6d66)

![2020-09-16 Scatter not adjusted to time range - Graph ok, scatter ok](https://user-images.githubusercontent.com/65596790/93335378-a80b9b00-f826-11ea-988d-444ee2c69e1a.png)
![2020-09-16 Scatter not adjusted to time range - Graph ok, scatter wrong](https://user-images.githubusercontent.com/65596790/93335382-a93cc800-f826-11ea-8d7f-673b273bdebc.png)

**Comment by Palakp41** [comment]
@paulfirstimpression So it looks like we have added the ability to customize the x-axis via the config panel for scatter plot. does this address your issue?

![github_issue_19573](https://user-images.githubusercontent.com/26464594/96488073-532abe00-11f2-11eb-8b08-d6369a10bb47.png)

**Comment by paulfirstimpression** [comment]
Hi,

Thanks for your reply. Unfortunately that didn’t  solve it:


  *   I have a dashboard with a few graphs and a scatter, all the same width, placed above each other for comparison in time
  *   In my scatter, X-Column is set to _time
  *   My dashboard’s time range is set to 7 days
  *   Say I only have measurements on day 3,4 and 5
  *   Graphs show day 1-7, as set in the time range
  *   Scatters only show day 3,4 and 5 (not the full time range)
  *   This way you can’t compare data between graphs and scatters

Is it possible to let a scatter have the time range as set in the dashboard?

Best regards,

Paul Notebaart
Technical Developer
[cid:image001.png@01D6A6C2.704C1970]
First Impression audiovisueel
Maidstone 24, 5026 SK Tilburg

[Icon_Telefoon]      +31 13 523 4180
[Icon_Mobiel]      +31 6 1233 22 38
[Icon_Mail]      p.notebaart@firstimpression.nl<mailto:p.notebaart@firstimpression.nl>
[Icon_Web]      www.firstimpression.nl<http://www.firstimpression.nl/>
[Lijn_Rechthoek_02]

Van: Palakp41 <notifications@github.com>
Verzonden: maandag 19 oktober 2020 19:04
Aan: influxdata/influxdb <influxdb@noreply.github.com>
CC: Paul Notebaart <P.Notebaart@firstimpression.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [influxdata/influxdb] Scatter does not adjust to time range after a data time gap (#19573)


@paulfirstimpression<https://github.com/paulfirstimpression> So it looks like we have added the ability to customize the x-axis via the config panel for scatter plot. does this address your issue?

[github_issue_19573]<https://user-images.githubusercontent.com/26464594/96488073-532abe00-11f2-11eb-8b08-d6369a10bb47.png>

**Comment by Palakp41** [comment]
I have created an issue to track the development work to fix this bug: https://github.com/influxdata/ui/issues/192

**Comment by Palakp41** [comment]
@paulfirstimpression We have added a fix for this issue. You should be able to compare the line graph with the scatter plot. Can you test and let us know if it is working for you?

**Comment by paulfirstimpression** [comment]
Hi @Palakp41 , thank you very much, scatters seem to be in line again with the set time range, I'm able again to compare scatters and graphs.
