### ISSUE TITLE
influx setup allows creating passwords shorter than 8 chars, but cannot login. 

### ISSUE THREAD

**Issue by danielr1996** [influxdata/influxdb#19585]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. create a fresh install of influxdb and start the service
2. run `influx setup --bucket default --org admin --password adminadmin --username admin --force`
3. go to http://localhost:9999 and login with user admin and password admin

__Expected behavior:__
`influx setup` refuses password not meeting the password policy

__Actual behavior:__
I get the `Could not sign in` popup. and cannot login 

I tried to reset the admin password with `influx user password --id 0653c03959f02000` and I got `Password too short - minimum length is 8 characters!`. After choosing a password longer than 8 chars I could login in the webinterface. 

__Environment info:__

* System info: Linux 5.4.0-1018-raspi aarch64
* InfluxDB version: InfluxDB 2.0.0-beta.16 (git: 50964d732c) build_date: 2020-08-07T20:18:22Z
* Influx CLI version: Influx CLI 2.0.0-beta.16 (git: 50964d732c) build_date: 2020-08-07T20:09:20Z

**Comment by glinton** [comment]
closed by https://github.com/influxdata/influxdb/pull/19593
