### ISSUE TITLE
Enable Pushdowns in OSS 2.0

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#19582]
With updating 2.0 OSS to use the 1.x storage engine, many of the pushdowns that used to work need to be reimplemented. This epic encapsulates the work needed to make that happen.

**Comment by nathanielc** [comment]
Closing this epic as all pushdowns have been ported to OSS. See https://github.com/influxdata/influxdb/issues/19814 for the remaining work to make OSS honor time ranges.
