### ISSUE TITLE
Timestamps not working with Influxdb2 OSS

### ISSUE THREAD

**Issue by cryptokni8** [influxdata/influxdb#19594]
OS: Mac Catalina v10.15.6
Influxdb: influxdb_2.0.0-beta.16_darwin_amd64 (pre-built image)

Steps to reproduce:

# write data is successful with timestamp
curl -XPOST "http://localhost:9999/api/v2/write?org=YOUR_ORG&bucket=YOUR_BUCKET&precision=ns" \
  --header "Authorization: Token YOURAUTHTOKEN" \
  --data-raw "test_v2,tag1=foo fieldKey=1 1596779400000000000"

# query data
# Bug: expected it to return data, but no data comes back.
curl http://localhost:9999/api/v2/query?org=YOUR_ORG -XPOST -sNS \
  -H 'Authorization: Token YOURAUTHTOKEN' \
  -H 'Accept: application/csv' \
  -H 'Content-type: application/vnd.flux' \
  -d 'from(bucket:"YOUR_BUCKET")
    |> range(start:-1000h)
    |> filter(fn: (r) => r["_measurement"] == "test_v2")
    '

Test case:
# write data is successful without timestamp and defaults to NOW
curl -XPOST "http://localhost:9999/api/v2/write?org=YOUR_ORG&bucket=YOUR_BUCKET&precision=ns" \
  --header "Authorization: Token YOURAUTHTOKEN" \
  --data-raw "test_v2,tag1=foo fieldKey=2"

# query data
# Expected it to return data with default timestamp and this works ok
curl http://localhost:9999/api/v2/query?org=YOUR_ORG -XPOST -sNS \
  -H 'Authorization: Token YOURAUTHTOKEN' \
  -H 'Accept: application/csv' \
  -H 'Content-type: application/vnd.flux' \
  -d 'from(bucket:"YOUR_BUCKET")
    |> range(start:-1000h)
    |> filter(fn: (r) => r["_measurement"] == "test_v2")
    '

This shows the same behaviour with java client library

**Comment by dericdesta** [comment]
Same/related issue here. If I write a point without a timestamp it gets inserted into the bucket/measurement. If I specify a timestamp it silently fails (HTTP 204), nothing is inserted. I've tested it with the Python client as well as Postman. So I thinks this is not a client issue. I'm on Docker (quay.io/influxdb/influxdb:2.0.0-rc), MacOS 10.15.6. The logs are the same for both cases:

```
Without timestamp: 
influxdb_1  | ts=2020-11-10T19:50:36.471579Z lvl=debug msg="user find by ID" log_id=0QOthjVl000 store=new took=0.177ms
influxdb_1  | ts=2020-11-10T19:50:36.471883Z lvl=debug msg="org find" log_id=0QOthjVl000 store=new took=0.070ms
influxdb_1  | ts=2020-11-10T19:50:36.472024Z lvl=debug msg="bucket find" log_id=0QOthjVl000 store=new took=0.093ms
influxdb_1  | ts=2020-11-10T19:50:36.480891Z lvl=debug msg=Request log_id=0QOthjVl000 service=http method=POST host=localhost:8086 path=/api/v2/write query="bucket=crypto2&org=crypto" proto=HTTP/1.1 status_code=204 response_size=0 content_length=55 referrer= remote=192.168.96.1:39776 user_agent=PostmanRuntime took=9.855ms



With timestamp:
influxdb_1  | ts=2020-11-10T19:44:39.215178Z lvl=debug msg="user find by ID" log_id=0QOthjVl000 store=new took=0.070ms
influxdb_1  | ts=2020-11-10T19:44:39.215850Z lvl=debug msg="org find" log_id=0QOthjVl000 store=new took=0.293ms
influxdb_1  | ts=2020-11-10T19:44:39.216006Z lvl=debug msg="bucket find" log_id=0QOthjVl000 store=new took=0.096ms
influxdb_1  | ts=2020-11-10T19:44:39.227666Z lvl=debug msg=Request log_id=0QOthjVl000 service=http method=POST host=localhost:8086 path=/api/v2/write query="bucket=crypto2&org=crypto" proto=HTTP/1.1 status_code=204 response_size=0 content_length=59 referrer= remote=192.168.96.1:39776 user_agent=PostmanRuntime took=12.814ms
```

Best, Frederic

**Comment by timhallinflux** [comment]
Cannot reproduce with the GA.  @cryptokni8 -- Please retry with 2.0.x.

**Comment by gorootde** [comment]
Same problem here using the official docker image in version `sha256:0b35e4d071ad0eef0771f7f0679276407a728b8388f98a2d3232f32179ed25fe`

**Comment by timhallinflux** [comment]
Is it possible that the timestamp of the write is beyond the retention policy of the bucket you are writing to?

**Comment by danxmoran** [comment]
@timhallinflux's suggestion could also be the cause in other situations: when points are written outside of the target bucket's retention policy, the points are dropped and a 204 response is sent. This behavior is new as of 2.0.4.
