### ISSUE TITLE
Community Templates UI Readme: Update relative links

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#19599]
### Background

Relative links from the community-templates repo are broken in the app. We need to properly prefix them.

Example [this template's link is broken in the ui](https://github.com/influxdata/community-templates/blob/master/InfluxDBv2_Covid19_SouthAmerica/covid.yml)

https://github.com/influxdata/community-templates/blob/master/InfluxDBv2_Covid19_SouthAmerica/readme.md#setup-instructions

### Acceptance Criteria
- Outbound relative links are not broken

**Comment by zoesteinkamp** [comment]
fixed by https://github.com/influxdata/ui/pull/105
