### ISSUE TITLE
Flows: As a user I can export a Task from a Flow

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#19603]
As a early access flows user I can export a task from a flow so that I can have the task running on a schedule

GIVEN I have a flow with a `Output to Bucket` cell
WHEN I click the green `Export as Task` button in the cell header
THEN I see an overlay with export options and a preview of the generated flux

##### Export option 1: New Task
WHEN I click the tab labeled "Create New"
THEN I see an input prefilled with the name of my flow and an input for schedule prefilled with the global time range from my flow
AND I can edit both inputs

[Design Mockup](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=944%3A8114)

##### Export option 2: Update Existing
WHEN I click the tab labeled "Update Existing"
AND I already have at least 1 Task
THEN I see a dropdown with a list of my tasks
AND the first Task in the list is selected

[Design Mockup](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=944%3A8867)

##### Schedule Input
WHEN I see the export overlay
THEN I see an input labeled "Run every"
AND I can type in a time interval as a number ending in `d`,`h`, `m`, or `s`

##### Empty State
GIVEN I don't have any existing Tasks
WHEN I click the `Update Existing` tab
THEN I see an [EmptyState](https://influxdata.github.io/clockface/?path=/story/components-empty-states-examples--no-dashboards) with text "You haven't created any Tasks yet"

[Design Mockup](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=1070%3A10205)

##### Errors
WHEN I click the `Export Task` button
AND there are missing values in `every` and/or `name` inputs
THEN I see an [error below the input](https://influxdata.github.io/clockface/?path=/story/components-forms-standard--formelement) with text "This field cannot be empty"

WHEN I click the `Export Task` button
AND there are is an invalid value in the `every` input
THEN I see an [error below the input](https://influxdata.github.io/clockface/?path=/story/components-forms-standard--formelement) with text "Invalid Time"

[Design Mockup](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=1070%3A10683)

##### Completion

WHEN I click the `Export Task` button
AND the values in `every` and `name` are valid
THEN I see a notification appear with message `[taskname] published successfully`
AND a new task is created or an existing task is updated
AND I see a button inside the notification labeled `Go to Task` that links to the tasks index
AND the export overlay closes

[Design Mockup](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=944%3A9770)

### Technical Notes

- Scope down to send some meta data to the existing API Tasks endpoint
    OR alternatively,
    perhaps we could use Stacks (JSON object to generate resources)
- We should research how Stacks would solve all this. 
- We are explicitly not adding cron option to the ui
- We will not store any reference to the task created (one-way only)

**Comment by drdelambre** [comment]
note: this one is being scaled back to one way resource generation without an update cycle (export only)

**Comment by alexpaxton** [comment]
Just to capture, we are not adding `offset` or `cron` for this first version in the interest of simplicity. By default `offset` should be `0s`.
