### ISSUE TITLE
Add grace-daily build to InfluxDB CircleCi config.yml

### ISSUE THREAD

**Issue by stephanie-engel** [influxdata/influxdb#19614]
**grace repo:** https://github.com/influxdata/grace
- OSS tests are located under `test/oss`
- WIP PR for creating grace-daily build: influxdata/influxdb#19559

@gshif @psteinbachs 
Just some background, I've gotten the grace tests to the point in which they are:
- running the grace `oss` tests every night with the `influx:nightly` build
- the grace `cloud` tests are running for every IDPE PR and
- the grace `pdt` tests are running on each cloud 2 cluster after a deployment

However, we still need to get the grace `oss` tests to run in a daily build for each InfluxDB PR. I started the work, but I don't fully understand how to run the specific InfluxDB version (for the code changes in the InfluxDB PR) within circleci. Most of my confusion / concern is stemming from the fact that the test repo and the circleci jobs are configured in such a way that one change could break another grace job (either the grace-nightly job or the cloud 2 jobs).

This project is in a state in which I think this task should be handed off to someone on your team. What are your thoughts?

**Comment by danxmoran** [comment]
Done in #20210
