### ISSUE TITLE
private/public keys are needed for signing packages

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#19633]
https://github.com/influxdata/idpe/issues/8461

**Comment by codyshepherd** [comment]
We are [signing debs and rpms](https://dl.influxdata.com/influxdb/releases/influxdb_1.8.5_amd64.deb.asc) today. @psteinbachs @danxmoran I'm closing this, please reopen if there's something I'm missing about this issue.

**Comment by codyshepherd** [comment]
[Here is a link](https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.4-amd64.deb.asc) to the latest 2.x deb signature -- this seems in order
