### ISSUE TITLE
cli write command should not require read permissions on a token

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19643]
i was trying to write data to a bucket using the CLI and a token that had `write` permission only to that bucket. the cli complained that the bucket didn't exist.

https://github.com/influxdata/influxdb/blob/master/cmd/influx/write.go#L288

i think the cli is trying to read the bucket, before writing to it, but it shouldn't need to. we should remove that constraint.

**Comment by glinton** [comment]
The cli is looking up the bucket prior to writing to it so it can get the bucket and org id. This lookup can be removed but writing to a bucket would only work if the user specifies the bucket and org id. Writing by bucket/org name would no longer be supported.

Alternatively, we could re-evaluate the permissions to allow getting the bucket if the requestor has permission to read or write from/to that bucket. This should not allow them to read from the bucket, just read the bucket.

**Comment by kristinarobinson** [comment]
I'm super uncomfortable removing that check.  Especially if it removes the "writing by bucket/org name" functionality".  

I do like Greg's proposal that says, if a token (or user) has read or write permission, then allow them access to read the list of buckets, but still constrain the reading _from the buckets_ by using the READ permission granted.

**Comment by russorat** [comment]
@glinton @kristinarobinson i don't think that's the case.

Telegraf can use the same write only token in the `influxdb_v2` output, with an org name and a bucket name, and successfully write data into influxdb. no ids are needed for the config, and the data is still written.

**Comment by glinton** [comment]
Yes, telegraf hits the api directly with it's own client and is more flexible in the values that can be used as the org/bucket ([here](https://github.com/influxdata/telegraf/blob/edd83381803119836ad678f0335c2692e4cfab32/plugins/outputs/influxdb_v2/http.go#L331-L334)). The cli uses the influx http client to write, which [only takes ids for org and bucket](https://github.com/influxdata/influxdb/blob/master/http/write_handler.go#L284) before setting them as [query parameters](https://github.com/influxdata/influxdb/blob/master/http/write_handler.go#L327-L329)
I'm all for extending that client with a new write method that handles either org/bucket name or id, should be pretty straightforward.

**Comment by russorat** [comment]
What's strange is that it is looking for ids, but it is using the name parameters: https://github.com/influxdata/influxdb/blob/master/http/write_handler.go#L327

Anyway, from a user perspective, a write only token should be able to write to the specific bucket using the CLI, so i would support updating the client (or using the influxdb-client-go) in our CLI.
