### ISSUE TITLE
influxd outputs legacy profiles

### ISSUE THREAD

**Issue by ayang64** [influxdata/influxdb#19681]
influxdb uses the built-in Go http handlers for `/debug/pprof/heap` etc. but we have a custom endpoint that bundles profiles in a tar file at `/debug/pprof/all`.

`/debug/pprof/all` uses `pprof.Lookup()` to fetch profiles by name then uses `pprof.WriteTo()` to send the profile to a writer.

`pprof.WriteTo()` takes two parameters: an `io.Writer` and an integer.  The integer dictates if `WriteTo()` writes to the new zip protobuf -- which includes all of the data needed to examine using `go tool pprof` -- or if `WriteTo()` should use the "legacy" format which requires an accompanying binary.

At the moment, `influxd` is set to only generate legacy profiles using this endponit.

The impact of this problem is that:

* It causes confusion.  Profiles inconsistently required binaries.
* It takes significant time to find the same binary as the build we're debugging.

**Comment by dgnorton** [comment]
Closed by PR https://github.com/influxdata/influxdb/pull/19655
