### ISSUE TITLE
Influx_inspect (on windows) - error "at least one path required"

### ISSUE THREAD

**Issue by Trovalo** [influxdata/influxdb#19686]
I'm trying to use the *influx_inspect* utility to get some data about my database files using the [*dumptsi* command](https://docs.influxdata.com/influxdb/v1.8/tools/influx_inspect/#dumptsi).

Note that I'm using Windows, so I know there is no official support, nevertheless, I was expecting a different error, and not to be unable to run the command at all.

I run the command (as specified in the docs), I've tried to use both PowerShell and cmd
```
Influx_inspect.exe dumptsi -series-file "<PathToDataFolder>\_series"
```
The output is always the same:
"at least one path required"

I had a look at the code, the path itself is valid otherwise I would get a "series file path required" error, but then looks like the path variable has length is 0, which returns "at least one path required" error.
https://github.com/influxdata/influxdb/blob/1fc403337e1ba0f1bd9347691e3ad58d3f83aa0d/cmd/influx_inspect/dumptsi/dumptsi.go#L97

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Use the influx_inspect.exe utility on Windows (not sure if the same happens on Linux)
2. try to run the command ```Influx_inspect.exe dumptsi -series-file "<PathToDataFolder>\_series"```

__Expected behavior:__
In the best case, I expect the command to work, or at least to return me an error due to incompatibility with windows.
(in the past I used some commands, they worked almost fine, meaning that I had to do some operations manually, like replacing files because the script wasn't doing that on windows)

__Actual behavior:__
The command does not even validate the passed input (or better, it validates part of it and then something else goes wrong), error "at least one path required"

__Environment info:__

* System info: Windows Server 2016
* InfluxDB version: InfluxDB v1.8.3
* Other relevant environment details:

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

**Comment by Trovalo** [comment]
The docs do not state anything about passing additional paths, but I think I just need to pass the path to the .tsi file I want to read. (that way the command actually tries to do something)
That said, on windows, I get several go errors, probably because the utility is not supported on Windows.

**Comment by in-fke** [comment]
Also, the wildcard specification for "deletetsm" under Windows apparently does not work.
Tried relative and absolute paths, tried forward slashes and backward slashes, always get
`deletetsm: open *\*.tsm: The filename, directory name, or volume label syntax is incorrect.`
