### ISSUE TITLE
Flows: As an early access user I can run a flow

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#19694]
As an early access flows user I want to run my flow and have it actually write data to a bucket in addition to seeing results.

GIVEN I have at least 1 flow with at least 1 output
AND I am looking at my flow
WHEN I click the caret button next to `Preview`
THEN I see a dropdown menu with 2 options: `Preview` and `Run`

WHEN I select `Run` from the dropdown menu
THEN I see a `Run` button instead of a `Preview` button

WHEN I click the `Run` button
THEN I see results populated in every cell
AND I expect data to get written to the bucket(s) I specified in my `Output to Bucket` cell(s)

[Design Mock](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=940%3A1117)

Click the caret next to `Preview` to see the interaction

**Comment by drdelambre** [comment]
the work here is scoped based on and assumption that the work will look kinda like:
create a dropdown button element in clockface
run flows in "with outputs" or "default" mode as defined in influxdata/ui#75, based on the dropdown setting
keep that setting scoped to the page / memory

**Comment by mnorriswalker** [comment]
Double check layout of controls @mnorriswalker @alexpaxton

**Comment by alexpaxton** [comment]
@Asalem1 @drdelambre feel free to update the point estimate of this story
