### ISSUE TITLE
Latency of influx insert calls has done up significantly

### ISSUE THREAD

**Issue by psverkada** [influxdata/influxdb#19690]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

Insert any event

__Expected behavior:__
Describe what you expected to happen.

Inserts have historically taken about 725ms.  I would expect the latency to be about that on average.

__Actual behavior:__

Since about 7pm, the average latency is about 15s, and the p99 is about 45s.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 4.14.193-149.317.amzn2.x86_64 x86_64
* InfluxDB version: Run `influxd version` and copy the output here
Using 2.0 cloud
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by russorat** [comment]
@psverkada are you still seeing this issue in cloud?

**Comment by rickspencer3** [comment]
@russorat they reported directly that they are not.
