### ISSUE TITLE
Duplicate notifications seen when notifying on state changes in Alerting UI

### ISSUE THREAD

**Issue by adrian-thurston** [influxdata/influxdb#19711]
Users are expecting one continuous stream of state change notifications, however duplicates show up, disrupting the natural flip back and forth between mutually exclusive states. 

Mentioned by users here and also observed locally.

https://community.influxdata.com/t/notification-when-status-changes-from-ok-crit/13847/11

__Steps to reproduce:__

1. Write some CPU data using telegraf.
2. Create a check with an interval of 10s.
3. Create a CRIT threshold that is easy to cross by a spinner `bash -c "while true; do echo > /dev/null; done"`
4. Create an OK threshold that complements the CRIT (below the same value)
5. Create `goes_ok` and `goes_crit` notification endpoints. Target HTTP on the localhost.
6. Create notification rules for CRIT -> OK and OK -> CRIT, calling the corresponding `goes_ok` and `goes_crit` endpoints. Use an interval of 1m.
7. Cross the threshold back and forth every 10 seconds.
8. Observe notifications in simple HTTP server. 

__Expected behavior:__
Expect a continuous stream of above and below that corresponds to the state changes observable in the "View History" page.

__Actual behavior:__
Extra notifications are present.

__Environment info:__

*    System info: `Linux jasper 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/LinuxRun`
*    InfluxDB version: 8763bb1af9e31896aaf9caef7658e3b6d3ad05a0
*    Other relevant environment details: Container runtime, disk info, etc

**Comment by aanthony1243** [comment]
hi @adrian-thurston   what is the interval on the notification rule?

**Comment by adrian-thurston** [comment]
Hi @aanthony1243 sorry I left that detail out. The interval on the notification rules are 1m.

**Comment by adrian-thurston** [comment]
@aanthony1243 I'm seeing now that when I make the check interval and the rule intervals the same I get what I was expecting: a continuous stream of flip flops, without any duplicates.

The user was stating this didn't work, but I suspect now, and after talking with @brettbuddin that it was due a configuration error in the notification endpoints, combined with a previous bug that required a resave to update the notification rules. In actuality it works fine when the intervals are identical.

**Comment by adrian-thurston** [comment]
Closing this as I have confirmed that expected behaviour can be achieved by using identical intervals. I have suggested this on the community question.
