### ISSUE TITLE
Showing the help for influxd is very slow

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#19714]
## What

Per a comment from Russ, listing the help for `influxd` 2.0 is very slow, consuming considerably CPU resources.

```sh
$ influxd -h
...
bin/darwin/influxd -h  3.04s user 0.08s system 101% cpu 3.062 total
```

The issue has been traced to eagerly initializing the Flux runtime.

**Comment by stuartcarnie** [comment]
@wolffcm / @russorat for reference

**Comment by adrian-thurston** [comment]
Flux changes are now in idpe, changes made there, and they are also included in a release, which can get pushed out to influxdb. What's left is to upgrade flux in influxdb and make the necessary changes there.

**Comment by stuartcarnie** [comment]
Awesome news, @adrian-thurston 💯

**Comment by stuartcarnie** [comment]
I can confirm `influxd` and `influx` `--help` switches are now instantaneous.
