### ISSUE TITLE
RHEL 7 Yum Repo has wrong path

### ISSUE THREAD

**Issue by zlark** [influxdata/influxdb#19717]
Reviewing https://repos.influxdata.com/rhel/7/x86_64/stable/repodata/ it looks like new artifacts were created this morning, however the RHEL 7 yum repo is still pointing at older artifacts that no longer exist.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Follow directions at https://docs.influxdata.com/telegraf/v1.15/introduction/installation/ to create Yum repo
2. Run `yum install telegraf` as root user

__Expected behavior:__
telegraf is installed on machine

__Actual behavior:__
`https://repos.influxdata.com/rhel/7/x86_64/stable/repodata/2cc236e28fae3579aecc943c0249fb16c44e11ad-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found`

__Environment info:__

* System info: Darwin 18.7.0 x86_64
* InfluxDB version: N/A

**Comment by compermisos** [comment]
same as #19716

**Comment by zlark** [comment]
Closing at duplicate.
