### ISSUE TITLE
Add config option to set NATS max payload size

### ISSUE THREAD

**Issue by Herr-Sepp** [influxdata/influxdb#19713]
Yes i know that the scraper are currently broken in RC0 but i think this is a other issue.

__Steps to reproduce:__

1. start 2.0rc0 Docker-Image: quay.io/influxdb/influxdb:2.0.0-rc
2. add an new Scraper with Target URL to a cadvisor endpoint "/metrics" (https://github.com/google/cadvisor)

the endpoint sends 139kb (3,5mb not compressed)

__Expected behavior:__
Metrics are scraped into bucket
(prometheus has no problem with these endpoints)

__Actual behavior:__
No data is stored

__Config:__
default docker image config

__Logs:__
Include snippet of errors in log.

ts=2020-10-09T11:43:32.602125Z lvl=error msg="Unable to publish scraper metrics" log_id=0PkFudAG000 error="nats: maximum payload exceeded"
ts=2020-10-09T11:43:42.633417Z lvl=error msg="Unable to publish scraper metrics" log_id=0PkFudAG000 error="nats: maximum payload exceeded"
ts=2020-10-09T11:43:52.609966Z lvl=error msg="Unable to publish scraper metrics" log_id=0PkFudAG000 error="nats: maximum payload exceeded"
ts=2020-10-09T11:44:02.663961Z lvl=error msg="Unable to publish scraper metrics" log_id=0PkFudAG000 error="nats: maximum payload exceeded"
ts=2020-10-09T11:44:12.659194Z lvl=error msg="Unable to publish scraper metrics" log_id=0PkFudAG000 error="nats: maximum payload exceeded"
ts=2020-10-09T11:44:22.643043Z lvl=error msg="Unable to publish scraper metrics" log_id=0PkFudAG000 error="nats: maximum payload exceeded"
ts=2020-10-09T11:44:32.658815Z lvl=error msg="Unable to publish scraper metrics" log_id=0PkFudAG000 error="nats: maximum payload exceeded"
...

**Comment by wallyqs** [comment]
Default Maximum Payload for NATS is 1MB, but this can be tuned in the config of the NATS Server `max_payload: 5mb` for example

**Comment by Herr-Sepp** [comment]
@wallyqs thanks a lot for your answer.
Do you know where the configuration file is located in the Influxdb container?

Unfortunately I cannot find the configuration on my own.

**Comment by spiegela** [comment]
Is this parameter configurable through influxdb?  I've also searched through the Docker container, and kind find any reference to `max_payload` or to NATS.  I also don't see any reference to this parameter in the docs: https://docs.influxdata.com/influxdb/v2.0/reference/

**Comment by danxmoran** [comment]
@spiegela looks like it's not currently configurable... I'll use this issue to track adding a new config parameter for it
