### ISSUE TITLE
Influxdb 2.0.0 RC restarts every minute because of insufficient memory (OOM)

### ISSUE THREAD

**Issue by semmel87** [influxdata/influxdb#19738]
I have been running a data import script which wrote a lot of points into influxdb over the last several days. It stopped working today. I realized it when I found the server not responding. So I had to force a reboot of the VM. Looking at the logs showed some errors about "too many open files in system" before I forced the reboot.

Since then the influxd process is restarting every minute because of problems with allocating memory ("cannot allocate memory"). It takes about 1min until influx reaches the limit of 32GB and crashs.

Please see the attached log file [influxdb_crash.log](https://github.com/influxdata/influxdb/files/5372026/influxdb_crash.log). To be honest I don't know what influx is doing.

__Steps to reproduce:__
Unknown

__Environment info:__

* System info: Linux 5.4.0-48-generic x86_64
* InfluxDB version: InfluxDB 2.0.0-rc.0 (git: df47ec7bb2) build_date: 2020-09-29T22:08:57Z

__Config:__
engine-path: /var/lib/influxdb/engine
bolt-path: /var/lib/influxdb/influxd.bolt

__Logs:__
[influxdb_crash.log](https://github.com/influxdata/influxdb/files/5372026/influxdb_crash.log)

__Performance:__
Can't connect to the debug resource with curl
[iostat.txt](https://github.com/influxdata/influxdb/files/5372022/iostat.txt)

**Comment by stuartcarnie** [comment]
* Can you provide a complete listing of your `~/.influxdbv2/engine` path. 
* How much data are you importing and over what time range?
* What is the cardinality of the data (how many fields, series)

**Comment by semmel87** [comment]
I'm evaluating influxdb because we are searching for alternatives to our current time series database. So basically I tried to import everything we have in our current db to be able to make realistic tests.

We wanted to separate our customers data using organizations. So there are 63 orgs in total. Each org contains 4 buckets (for different types of time series). The biggest bucket contains around 90k time series. The amount of measurements per bucket is 100 to a few thousand. We use a single field value with 2 to 4 tags per time series. The covered time range is different, but may up to 7 years in some orgs.

This is a listing of the storage engine files you asked for: [engine_files.txt](https://github.com/influxdata/influxdb/files/5376450/engine_files.txt)

**Comment by semmel87** [comment]
I have seen that a new RC was released (2.0.0-rc.1 (git: 5304b77577) build_date: 2020-10-14T21:54:15Z). I tried it just now but the behavior is still the same.

**Comment by stuartcarnie** [comment]
@semmel87 thanks for providing the information! 

I've examined your data, and as anticipated, importing such a vast history resulted in a huge number of shards. A shard is how the InfluxDB storage engine partitions data on disk, at predetermined time intervals, to allow for a number of optimizations, including retention policy enforcement, memory management and increased write performance for hot shards.

The default shard group duration is 7 days for a bucket set to an infinite retention policy. Assuming you write at least one point per 7-day interval, that means that importing 7 years of data for a single bucket would create about 365 shards, each covering a 7-day period. Multiply that by 4 (number of buckets per org) and then 63 (number of orgs) and it could result in 91,980 shards. Each shard comes with an expected overhead, including 8 files to manage the time-series index and an arbitrary number of TSM files (compressed time-series data) depending on the amount of data for a given shard.

In InfluxDB 1.x, we provide an option to the `CREATE DATABASE` statement to specify the shard group duration, so in your case you could extend this to a much larger value, resulting in fewer shards (for example 1-year). We don't expose this option in 2.x, however, I'm bringing this back to the team to discuss options.

**Comment by semmel87** [comment]
@stuartcarnie thanks for your answer.
I will try to continue my evaluation with a smaller database for now and import only a single organization.

**Comment by cgfoed** [comment]
I was stumbling across this issue and was hoping to geht some clarification.

My first test so far with Influx were very promising so I just recently wrote a python script to import all our data to the influxdb test instance. After a while I got the infamous   "too many open files" - error.

Do I understand it correctly, that I need 9 open files times buckttimelengh in weeks times overall buckets? But it's regardless of any count of tags, measurements or datapoints? 

E.g.:
2 buckets over 12 weeks  in Org A with 200.000 entries in total
5 buckets over 150 weeks in Org B with 60.000 entries in total
3 buckets over 100 weeks in Or C with 1.000.000 entries in total
1 bucket over  250 weeks in Orga A with 10.000 entries in total

every bucket is set to unlimited retention and has min. 1 datapoint each week

(2 b * 12 w + 5 b * 150 w + 3 b * 100 w + 1 b * 250w ) * 9 Files per shard = 11.700 files opened by startup

-> ulimit must be set to **AT LEAST** that number 

did I summarized this more or less correctly?

**Comment by timhallinflux** [comment]
#19764 -- would allow for the shard duration to be changed, thus reducing the number of files required.

**Comment by angelademarco** [comment]
Some guidelines on how to still using influx with a limited hardware without suffering crashes ?

**Comment by seikobu** [comment]
is your system crashing because of a high number of shards to open?

**Comment by angelademarco** [comment]
I don't know, it just crashes with the default configuration. I'm validating timescaledb on the same machine, so far I can load 100x more metrics on timescale without any performance degradation. For sure it is something going on with the version 2

**Comment by dgnorton** [comment]
@angelademarco do you still have the influxdb setup and would you be able to provide some information?
* What version of InfluxDB are you using?
* How much CPU, RAM, and what type of disk (SSD)?
* How many shards?

@semmel87 are you still experiencing this issue? If so, have you tried 2.0.8?

**Comment by semmel87** [comment]
The issue was solved by adjusting the shard size. See https://github.com/influxdata/influxdb/issues/19764
