### ISSUE TITLE
Error writing to outputs.influxdb_v2: 500 Internal Server Error

### ISSUE THREAD

**Issue by duanshuaimin** [influxdata/influxdb#19779]
__Expected behavior:__
send telegraf collect data to influxdb and view on explore

__Actual behavior:__
Error writing to outputs.influxdb_v2: 500 Internal Server Error: internal error: unexpected error writing points to database: partial write: field type conflict: input field "uptime" on measurement "system" is type integer, already exists as type unsigned dropped=32

__Environment info:__
influxd oss 2.0 rc1
telegraf version 1.15.3
OS:Linux 4.18.0-193.el8.x86_64 x86_64

telegraf console log :
Error writing to outputs.influxdb_v2: 500 Internal Server Error: internal error: unexpected error writing points to database: partial write: field type conflict: input field "uptime" on measurement "system" is type integer, already exists as type unsigned dropped=32
influxdb console log 
Request	{"log_id": "0PyfmWkl000", "service": "http", "method": "POST", "host": "192.168.1.55:8086", "path": "/api/v2/write", "query": "bucket=default&org=zonli", "proto": "HTTP/1.1", "status_code": 500, "response_size": 228, "content_length": -1, "referrer": "", "remote": "192.168.1.251:38468", "user_agent": "Telegraf", "took": "25.058ms", "error": "internal error", "error_code": "internal error"}

**Comment by duanshuaimin** [comment]
the same config works well on beta 16

**Comment by russorat** [comment]
So we changed storage backends between beta 16 and rc1 so the behavior you are seeing would be the same issue you would have in influxdb 1.x. They only way to fix this is to resolve the field type conflict for uptime by either droping your existing data or possibly adding a converter processor in telegraf.

I'm closing this issue, since this isn't a bug.
