### ISSUE TITLE
remote read: regular expression handling not consistent with Prometheus

### ISSUE THREAD

**Issue by foobar** [influxdata/influxdb#19831]
Prometheus handles regular expression in a special, sort of counterintuitive way that it adds  begin/end boundaries automatically for users. But influxdb does not follow this way to process remote read RPC. 

Example PromQL: 
`go_gc_duration_seconds{quantile=~"0"}`

native prometheus shows:

```
go_gc_duration_seconds{instance="localhost:9090",job="prometheus",quantile="0"} | 0.000080217
```

influxdb as remote read storage:

```
go_gc_duration_seconds{instance="localhost:9090",job="prometheus",quantile="0"} | 0.000080217
go_gc_duration_seconds{instance="localhost:9090",job="prometheus",quantile="0.25"} | 0.000084891
go_gc_duration_seconds{instance="localhost:9090",job="prometheus",quantile="0.5"} | 0.000098008
go_gc_duration_seconds{instance="localhost:9090",job="prometheus",quantile="0.75"} | 0.000126765
```

**Comment by foobar** [comment]
and fyi, the discussion on anchored regexp back in 2015 https://github.com/prometheus/prometheus/issues/1200

**Comment by davidby-influx** [comment]
@danxmoran
