### ISSUE TITLE
How to add a task through the API?

### ISSUE THREAD

**Issue by doivosevic** [influxdata/influxdb#19844]
The docs don't provide an example and the testing code does not seem to have a single positive example.
https://github.com/influxdata/influxdb/blob/e405398ac1095248f6ac7a281156f850f70caf28/http/task_service_test.go

How are we supposed to escape the string which is passed in?

**Comment by russorat** [comment]
thanks! if you are using the raw api, here are the docs to add it: https://docs.influxdata.com/influxdb/v2.0/api/#operation/PostTasks

if you are using a client lib, let me know which one and we can figure it out.

**Comment by russorat** [comment]
closing this for now as this is better for the community slack channel.

**Comment by doivosevic** [comment]
As I have said, the docs don't provide any examples. I'm using the raw API as I have a service in Rust which doesn't have a proper client lib. I tried to pose this as a doc issue since the docs are lacking examples for a complex query like this but I agree I should have posted this on stackoverflow. The community slack channel is way worse than stackoverflow since people can easily miss that someone asked a similar question and if there is no one there right when you ask the question you probably wont get an answer later

**Comment by russorat** [comment]
@doivosevic thanks for the follow up. here's an issue for the docs with an example: https://github.com/influxdata/docs-v2/issues/2540

**Comment by doivosevic** [comment]
thank you very much for being proactive and constructive!
