### ISSUE TITLE
influx write line format file inserts quotes to string values

### ISSUE THREAD

**Issue by brt-alexei** [influxdata/influxdb#19847]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. make file (out.line) with content:
status,device="0a" monotonic_event_time=70248923420600 1599257703709266794

2. write it to database using influx CLI
influx write --file out.line

3. device tag with value ""0a"" will be inserted

__Expected behavior:__
to filter measurements by device:
filter(fn: (r) => r.device == "0a")

__Actual behavior:__
to filter measurements by device:
filter(fn: (r) => r.device == "\\"0a\\"")

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 5.4.0-52-generic x86_64

* InfluxDB version: Run `influxd version` and copy the output here
Influx Cloud 
Influx CLI 2.0.0-rc.0 (git: df47ec7bb2) build_date: 2020-09-29T22:08:57Z

**Comment by russorat** [comment]
You do not need double quotes around tag values. see https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/#quoting-special-characters-and-additional-naming-guidelines for more details.
