### ISSUE TITLE
The createsnapshot() of backup() will be executed repeatedly when err is nil

### ISSUE THREAD

**Issue by zddr** [influxdata/influxdb#19841]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Analysis code Engine.Backup()

__Expected behavior:__
Jump out of the loop when err is nil

__Actual behavior:__
no break when err is nil

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by lesam** [comment]
This was fixed by https://github.com/influxdata/influxdb/pull/20527 in master and https://github.com/influxdata/influxdb/pull/19869 in master-1.x
