### ISSUE TITLE
InfluxDB v2 compatibility endpoint /query not working after mapping unmapped buckets

### ISSUE THREAD

**Issue by eaglejohn81** [influxdata/influxdb#19845]
Creating an InfluxQL datasource in Grafana to InfluxDB 2.0 (2.0.0-beta.16) failed with error:

`can't assign to property "executedQueryString" on "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>InfluxDB 2.0</title><base href=\"/\"><link rel=\"shortcut icon\" href=\"/favicon.ico\"></head><body><div id=\"react-root\" data-basepath=\"\"></div><script src=\"/5e93c5f5aa.js\"></script></body></html>": not an object`

I followed the procedure to map unmapped buckets on https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/#map-unmapped-buckets and tried to create the datasource in Grafana using https://docs.influxdata.com/influxdb/v2.0/tools/grafana/#configure-grafana-to-use-influxql

Using postman, I'm getting the same output when querying the InfluxDB v1 compatible endpoint:

```
curl --location --request GET 'http://54.226.129.163/query?db=db-35days&rp=rp-35days' \
--header 'Authorization: Token VuLd01YvgyBNnWQlzFXDgDT08DFGdfgr4et6456HzrNpHqKF4q8VvQUZrMLLoyUUpJbdSU0mwUPYISV1LdjQ==' \
--data-urlencode 'q=select * from ping'
```

```
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>InfluxDB 2.0</title>
    <base href="/">
    <link rel="shortcut icon" href="/favicon.ico">
</head>

<body>
    <div id="react-root" data-basepath=""></div>
    <script src="/5e93c5f5aa.js"></script>
</body>

</html>
```

I verified the database retention policy mapping is available using:
```

curl --location --request GET 'http://my-influxdb/api/v2/dbrps/06868db0219ad000?org=PBC' \
--header 'Authorization: Token VuLd01YvgyBNnWQlzFXDgDT08DFGdfgr4et6456HzrNpHqKF4q8VvQUZrMLLoyUUpJbdSU0mwUPYISV1LdjQ=='


{
    "content": {
        "id": "06868db0219ad000",
        "database": "db-35days",
        "retention_policy": "rp-35days",
        "default": true,
        "organization_id": "218adfcaf421474d",
        "bucket_id": "9fd165c106e5f962"
    }
}
```

According the documentation on https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/dbrp/ a new database/retention-policy bucket is automatically created with a DBRP mapping, and data is written to the bucket if no matching bucket is found. I tried this as well using an "all access token", but got the same wrong response:

```
curl --location --request POST 'http://my-influxdb/write?db=testdb&rp=testrp' \
--header 'Content-Type: application/json' \
--header 'Authorization: Token VuLd01YvgyBNnWQlzFXDgDT08DFGdfgr4et6456HzrNpHqKF4q8VvQUZrMLLoyUUpJbdSU0mwUPYISV1LdjQ==' \
--data-raw 'measurement,host=host1 field1=2i,field2=2.0 1577836800000000000'
```

```

<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>InfluxDB 2.0</title>
    <base href="/">
    <link rel="shortcut icon" href="/favicon.ico">
</head>

<body>
    <div id="react-root" data-basepath=""></div>
    <script src="/5e93c5f5aa.js"></script>
</body>

</html>
```

I can query the v2 endpoint without issues using Flux:

```
curl --location --request POST 'http://my-influxdb/api/v2/query?org=PBC' \
--header 'Content-Type: application/vnd.flux' \
--header 'Accept: application/csv' \
--header 'Authorization: Token VuLd01YvgyBNnWQlzFXDgDT08DFGdfgr4et6456HzrNpHqKF4q8VvQUZrMLLoyUUpJbdSU0mwUPYISV1LdjQ==' \
--data-raw 'from(bucket: "35days")
  |> range(start: -12h)
  |> filter(fn: (r) => r["_measurement"] == "ping")
  |> yield(name: "mean")'


,result,table,_start,_stop,_time,_value,_field,_measurement,account
,mean,0,2020-10-27T22:52:58.644679856Z,2020-10-28T10:52:58.644679856Z,2020-10-28T08:49:35Z,0.
```

Also posted the issue on stackoverflow: https://stackoverflow.com/q/64573431/14535147

**Comment by ftibi93** [comment]
Something similar is happening to me, too. 
Except I am on 1.8.3.
I was running influxdb natively as a service and wanted to switch to Docker container (same version). 
I didn't want to migrate any data, so I started from scratch. 
The dockerized influxdb is running fine, telegraf is able to send data to it, I can run queries like this:
`192.168.50.59:8086/query?db=telegraf&q=SELECT * FROM cpu WHERE time > now() - 30s`
from Postman and I get back the right answer.

What I noticed is that grafana is getting back completely wrong responses from influxdb.
I get back html pages instead of data in JSON for every request sent to influxdb. 

The sent requests' urls look like this:
`http://192.168.50.59:3000/192.168.50.59:8086/query?u=telegraf&p=password&db=telegraf&q=SHOW RETENTION POLICIES on "telegraf"&epoch=ms`

I am not entirely sure what a request towards influxdb supposed to look like because I never checked it before but I don't think the first part (http://192.168.50.59:3000) should be there. Without it the request executes successfully.

**Comment by russorat** [comment]
@eaglejohn81 please try again with the latest RC build.

**Comment by eaglejohn81** [comment]
@russorat That solved the issue! Thank you for your help!

**Comment by darroyod** [comment]
Hello. 
I'm experiencing the same issue with influxdb 2.0.3 in ARM64.

In my case the dbrp mapping is configured and I can query succesfully using v2 api. Unfortunately, when I choose the /query endpoint I've got this error:

`can't assign to property "executedQueryString" on "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>InfluxDB 2.0</title><base href=\"/\"><link rel=\"shortcut icon\" href=\"/favicon.ico\"></head><body><div id=\"react-root\" data-basepath=\"\"></div><script src=\"/4140302b79.js\"></script></body></html>": not an object
`

Any advise about how to solve this issue?

Thanks in advance for your help.
