### ISSUE TITLE
support email notification endpoint for infludb 2.0 ？

### ISSUE THREAD

**Issue by duanshuaimin** [influxdata/influxdb#19843]
__Proposal:__
Hope support email method

__Current behavior:__
Email is not in Notification end points for influxdb 2.0 rc2

__Desired behavior:__
Email is in notification end points

__Use case:__
Why is this important (helps with prioritizing requests)?

**Comment by russorat** [comment]
Thanks! we are investigating how to support this better natively, but if you want to use email for alerts, you can configure it using these docs: https://docs.influxdata.com/influxdb/v2.0/monitor-alert/send-email/
