### ISSUE TITLE
influxdb 2.0 rc2 linux SIGSEGV tsm1.(*KeyCursor).Next

### ISSUE THREAD

**Issue by joeroback** [influxdata/influxdb#19858]
Running influxd 2.0-rc2 from binary @ https://dl.influxdata.com/influxdb/releases/influxdb-2.0.0-rc.2_linux_amd64.tar.gz on Debian 10. Debian is an VM in Proxmox hypervisor, and influxd is the only service running in VM. Currently it has only 1 client (testing), a pfSense VM running Telegraf.

```
Oct 29 14:57:03 laconia influxd[108]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 29 14:57:03 laconia influxd[108]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x123abc2]
Oct 29 14:57:03 laconia influxd[108]: goroutine 871931 [running]:
Oct 29 14:57:03 laconia influxd[108]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*KeyCursor).Next(0x0)
Oct 29 14:57:03 laconia influxd[108]:         /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.go:1286 +0x22
Oct 29 14:57:03 laconia influxd[108]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*floatArrayAscendingCursor).nextTSM(0xc004744a00, 0x16427e44bd87fe00)
Oct 29 14:57:03 laconia influxd[108]:         /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/array_cursor.gen.go:153 +0x2f
Oct 29 14:57:03 laconia influxd[108]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*floatArrayAscendingCursor).Next(0xc004744a00, 0x1f40)
Oct 29 14:57:03 laconia influxd[108]:         /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/array_cursor.gen.go:102 +0x193
Oct 29 14:57:03 laconia influxd[108]: github.com/influxdata/influxdb/v2/storage/reads.(*floatMultiShardArrayCursor).Next(0xc00013efd8, 0x1)
Oct 29 14:57:03 laconia influxd[108]:         /go/src/github.com/influxdata/influxdb/storage/reads/array_cursor.gen.go:220 +0x37
Oct 29 14:57:03 laconia influxd[108]: github.com/influxdata/influxdb/v2/storage/flux.(*floatTable).advance(0xc000f80f00, 0xc00181b4f0)
Oct 29 14:57:03 laconia influxd[108]:         /go/src/github.com/influxdata/influxdb/storage/flux/table.gen.go:82 +0x3e
Oct 29 14:57:03 laconia influxd[108]: github.com/influxdata/influxdb/v2/storage/flux.(*table).do(0xc000f80f00, 0xc00180daa0, 0xc004e05e98, 0x0, 0x0)
Oct 29 14:57:03 laconia influxd[108]:         /go/src/github.com/influxdata/influxdb/storage/flux/table.go:84 +0x1d4
```

Telegraf.conf
```
# This file is automatically generated by pfSense #
[agent]
        interval = "10s"
        round_interval = true

[[inputs.cpu]]
        percpu = true
        totalcpu = true
        fielddrop = ["time_*"]

[[inputs.disk]]
        ignore_fs = ["tmpfs", "devtmpfs"]

[[inputs.diskio]]

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.net]]

[[inputs.processes]]

[[inputs.swap]]

[[inputs.system]]

[[inputs.pf]]

# Additional Raw Options
[[outputs.influxdb_v2]]
  urls = ["http://192.168.42.53:8086"]
  token = "<omitted>"
  organization = "The Expanse"
  bucket = "pfSense"
[[inputs.exec]]
  name_override = "speedtest"
  interval = "7200s"
  commands = ["/usr/local/bin/speedtest --server=30511 --csv"]
  timeout = "120s"
  data_format = "csv"
  csv_column_names = ["ServerID","Sponsor","ServerName","Timestamp","Distance","Ping","Download","Upload","Share","IP Address"]
  csv_column_types = ["int","string","string","string","float","float","float","float","string","string"]
  csv_delimiter = ","
[[inputs.ping]]
    interval = "60s"
    urls = ["1.1.1.1","8.8.8.8","9.9.9.9"]
    deadline = 0
```

**Comment by stuartcarnie** [comment]
@aanthony1243 this looks like storage – not sure whether this is to fall on the storage or edge team?

**Comment by 8none1** [comment]
AFAICT this would be on the edge team.  Removing the team/storage label.  Please let me know if anyone needs storage help here.

**Comment by danxmoran** [comment]
@joeroback I'm not able to reproduce this using the RC2 binaries. There have been some nontrivial changes to the code generating the stack trace between the RC and the latest GA releases; if you're still seeing the problem, could you try 2.0.2 (or 2.0.3 after this week) and see if the issue is resolved?

If the problem still occurs, would you mind sharing the flux query you're running when the panic happens?

**Comment by joeroback** [comment]
sure, no problem, i just have a grafana dashboard with many queries, is there an easy way or some debug mode i can turn on to figure that out? I didn't see any query backtrace in any log last time.

**Comment by danxmoran** [comment]
Not that I know of, panics like this are a pain 🙁 if you send me all the queries (or even the full JSON definition of your grafana dashboard) I can do a first pass of narrowing down which is causing problems.

**Comment by joeroback** [comment]
ok attached is my dashboard json and i've updated to 2.0.3 and have that running now.
[dashboard.zip](https://github.com/influxdata/influxdb/files/5705545/dashboard.zip)

**Comment by danxmoran** [comment]
Still no luck reproducing on my end. Have you seen the panic when running 2.0.3?

If so, could you point me at how to install the program you have at `/usr/local/bin/speedtest`? All the queries in your dashboard run fine for me, but the one with `filter(fn: (r) => r._measurement == "speedtest")` isn't a full test since I don't have any data in the measurement.

**Comment by joeroback** [comment]
it has not reproduced with 2.0.3 yet. I am setting up a computer to keep the dashboard open 24/7 now, so basically hit it with more queries. maybe its very rare and not reproducible at this point. it certainly happens :)

speedtest is the python version, its installed on my pfSense router (FreeBSD), so just did, `pkg install py37-speedtest-cli` but on systems like Debian and Ubuntu I think its available through apt via `speedtest-cli` debian package or one can install via `pip install speedtest-cli`

**Comment by joeroback** [comment]
I have been running dashboard now 24/7 and no issue with 2.0.3, maybe its rare, maybe its been fixed, but probably ok to close this. If I ever see it again, I can re-open. Thanks all!

**Comment by danxmoran** [comment]
Awesome, glad to hear it's working better than before! Thanks for the help in double-checking.
