### ISSUE TITLE
Why is there both a tag and a branch name for v1.8.3?

### ISSUE THREAD

**Issue by anonymouse64** [influxdata/influxdb#19866]
This is confusing a CI system I have which checks out influxdb and builds a [snap package](https://snapcraft.io/influxdb-ijohnson) out of it. It ends up checking out the branch and not the tag and gets confused. AFAIK, this is considered "not advised" for git repositories.

**Comment by dgnorton** [comment]
There was some internal discussion about the reason/history of this branch. It may have been created accidentally. I've created `old-v1.8.3-branch` and deleted the `v1.8.3` branch. Assuming nothing breaks and no one complains, the `old-v1.8.3-branch` will be deleted in a week or so.

Going on the assumption that deleting the branch was the correct thing to do and closing this issue.

**Comment by anonymouse64** [comment]
Thanks, looks fixed now.
