### ISSUE TITLE
Change in Scatterplot axes auto-range-adjust behavior

### ISSUE THREAD

**Issue by rgatkinson** [influxdata/influxdb#19867]
Up until this morning, when I Explored a series using Scatter

![image](https://user-images.githubusercontent.com/111943/97662426-48fb9180-1a34-11eb-8a33-464728c5d7ad.png)

both the X and the Y axes automatically adjusted their ranges to just cover the data in that series. This was perfect, exactly what I need; I look at all my data using this feature, hundreds of series.

This morning, when I looked at my data, the Y axis was crazy! It was auto-adjusting to a rediculoulsy huge range. Clearly a bug, but I'd figure you'd catch it soon.

And, I guess you did: this evening, the Y axis is back to yesterday's behavior, but now the _X axis_ no longer auto-adjusts its range. Which makes your tool significantly less useful to me, so much so that I'd need to find another vendor.

Please, put the auto-range-scaling back the way it was yesterday! Or give me a button to click to zoom in the Time Range to just cover the data plotted. Or something similar.

Thank you.

**Comment by 121watts** [comment]
may have been fixed by influxdata/influxdb#19573. @Palakp41 to verify

**Comment by Palakp41** [comment]
@rgatkinson The x-axis was deliberatly changed to fix influxdata/influxdb#19573. The range on the x-axis can be customized using the customize button on the top left. If you are using a value for x-axis, you can select xColumn as value and select the min and max. Or you can customize the time for x-axis using the time range dropdown.

**Comment by rgatkinson** [comment]
There is no optoin on the customization that will auto-select the min and max based on the data. Having me manually select the min and max makes the UI far, far too tedious.

**Comment by TCL735** [comment]
Hi @rgatkinson we will look into adding a button or toggle that will auto-select the min and max based on the data. This will be a tagged as a feature request and we will provide updates in the future.
