### ISSUE TITLE
InfluxDB throws exception when rendering graph in web interface on Raspberry Pi 3 B+ running Ubuntu 20.04.1 LTS Focal Fossa ARM 64-bit (aarch64)

### ISSUE THREAD

**Issue by pcgeek86** [influxdata/influxdb#19874]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Obtain a Raspberry Pi 3 B+
1. Install Ubuntu Server 20.04.1 LTS ARM 64-bit `aarch64` 
1. Install Docker
1. Install InfluxDB ARM 64-bit package on `arm64v8/ubuntu` base container image
1. Run an InfluxDB container from the new container image
1. Try to build a graph under the **Explore** view

Here's the Dockerfile I used to build the container image.

```Dockerfile
FROM arm64v8/ubuntu

ENV INFLUX_URL=https://dl.influxdata.com/influxdb/releases/influxdb_2.0.0-rc.3_arm64.deb
ENV INFLUX_FILE=influxdb_2.0.0-rc.3_arm64.deb

RUN apt-get update && apt-get upgrade --yes \
  && apt-get install wget --yes \
  && wget -nv --show-progress --progress=bar:force:noscroll $INFLUX_URL \
  && dpkg --install $INFLUX_FILE

EXPOSE 8086

ENTRYPOINT ["influxd", "run"]
```

__Expected behavior:__

InfluxDB renders a graph 

__Actual behavior:__

```
panic: runtime error: invalid memory address or nil pointer dereference
```

![image](https://user-images.githubusercontent.com/466713/97766664-12c61c80-1add-11eb-8440-b04cdbab8e38.png)

InfluxDB engine throws the following error message, obtained from Docker container logs.

```
2020-10-31T00:13:52.245460Z     info    Dispatcher panic        {"log_id": "0QAyTKMl000", "service": "storage-reads", "component": "dispatcher", "error": "panic: runtime error: invalid memory address or nil pointer dereference"}
goroutine 153047 [running]:
runtime/debug.Stack(0x4001f7a4e0, 0x3714000, 0x248efba)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0x4001f7a540)
        /go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/dispatcher.go:81 +0x18c
panic(0x20db140, 0x48c10b0)
        /usr/local/go/src/runtime/panic.go:969 +0x15c
github.com/apache/arrow/go/arrow/math.Float64Funcs.Sum(...)
        /go/pkg/mod/github.com/apache/arrow/go/arrow@v0.0.0-20200923215132-ac86123a3f01/math/float64.go:38
github.com/influxdata/flux/stdlib/universe.(*MeanAgg).DoFloat(0x4000f3ae70, 0x4001e62a80)
        /go/pkg/mod/github.com/influxdata/flux@v0.91.0/stdlib/universe/mean.go:144 +0x140
github.com/influxdata/flux/execute.(*aggregateTransformation).Process.func1(0x3789ba0, 0x4001e57450, 0x400137ed98, 0x4000f3ae70)
        /go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/aggregate.go:143 +0x38c
github.com/influxdata/flux/execute.(*ColListTable).Do(0x4001e57450, 0x400137edc0, 0x6, 0x4)
        /go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/table.go:1410 +0x90
github.com/influxdata/flux/execute.(*aggregateTransformation).Process(0x4001f7a5a0, 0x875396876a568399, 0x95033836fa25b980, 0x376c780, 0x4001e57450, 0x5, 0x0)
        /go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/aggregate.go:128 +0x3ec
github.com/influxdata/flux/execute.processMessage(0x3764000, 0x4001fa1aa0, 0x377cbc0, 0x4001f7a5a0, 0x373a400, 0x4001e60b00, 0x4003027501, 0x0, 0x0)
        /go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/transport.go:243 +0x24c
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0x4001f5cfc0, 0x3764000, 0x4001fa1aa0, 0xa)
        /go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/transport.go:191 +0xb0
github.com/influxdata/flux/execute.(*poolDispatcher).run(0x4001f7a540, 0x3764000, 0x4001fa1aa0)
        /go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/dispatcher.go:132 +0x48
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0x4001f7a540, 0x3764000, 0x4001fa1aa0)
        /go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/dispatcher.go:86 +0x90
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
        /go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/dispatcher.go:63 +0x74
```

__Environment info:__

```
Linux 5.4.0-1022-raspi aarch64

ubuntu@hostname:~$ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

root@3fc4d183f532:/# influxd version
InfluxDB 2.0.0-rc.3 (git: f46a3bd91e) build_date: 2020-10-29T22:17:55Z
```

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__

No special InfluxDB configuration applied.

**Comment by pcgeek86** [comment]
This issue is preventing the configuration of metric alerts. Why is that, you ask? Well, the metric alerting section doesn't have an option to switch over to the Flux editor. The generated query presumably includes a reference to the `aggregateWindow()` function, which causes queries to break on ARM 64-bit. Hence, the error appears and prevents setting up metric alerts. Well, it lets you create the alert, but it fails to execute the query on the defined schedule. See screenshot for details.

![image](https://user-images.githubusercontent.com/466713/98141912-69887900-1e84-11eb-8f38-c7a70625a293.png)

**Comment by danxmoran** [comment]
@pcgeek86 our 2.0.3 release includes an updated ARM64 build which we hope will address issues like this. You can download the binaries here: https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.3_linux_arm64.tar.gz

Please let me know how it goes if you try it out!

**Comment by danxmoran** [comment]
Closing this as I've seen enough successful reports about the new ARM builds to be confident things work in general, but please do open new issues if you hit any problems!

**Comment by pcgeek86** [comment]
Sorry for the delay. I reported back to Tim Hall in the InfluxDB Slack team, that it seems to be working pretty well!

Thanks for fixing this and making it work properly!
