### ISSUE TITLE
InfluxDB 2.0 cloud: invalid: memory allocation limit reached: limit 10000000 bytes, allocated: 9999952, wanted: 64

### ISSUE THREAD

**Issue by paulfirstimpression** [influxdata/influxdb#19877]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Use a dashboard in Grafana that has been running for weeks without problems
2. Refresh
3. Get random memory allocation limit errors

__Expected behavior:__
No errors, just measurements

__Actual behavior:__
I've got a Grafana dashboard with 7 graphs/tables that query InfluxDB 2.0 Cloud . Since this weekend, sometimes randomly I get _invalid: memory allocation limit reached_ errors on random queries. Refreshing the dashboard solves is, or sometimes makes other graphs give messages like these:
invalid: memory allocation limit reached: limit 10000000 bytes, allocated: 9999952, wanted: 64

3 out of 7 queries take a bit longer, about 1-2 seconds, but ran without problems the last couple of weeks. 

Has something changed in InfluxDB 2.0 cloud over the last couple of days? Might it be that InfluxDB 2.0 can't handle the 7 queries simultaneously (dashboard refresh) anymore?

__Environment info:__

* InfluxDB 2.0 cloud
* Grafana 7.2.1 ( and later 7.3.1 to test any difference, but no difference)

**Comment by aanthony1243** [comment]
hi @paulfirstimpression do your dashboards use influxql or flux?  We can take a closer look at this.

**Comment by paulfirstimpression** [comment]
Hi @aanthony1243, thanks! We're using Flux on InfluxDB 2.0 cloud (https://eu-central-1-1.aws.cloud2.influxdata.com).
I can send you one of the queries and organization id if you'd like.

**Comment by jeffsw** [comment]
I'm experiencing this as well, whether querying Influx Cloud directly through its web UI, or using Grafana.  Our DB has a bit of a cardinality problem, however, the error happens even when filtering for low-cardinality series.  The default System dashboard in Influx Cloud sometimes exhibits this symptom; it appears unrelated to the particulars of the query.
![Screen Shot 2021-01-22 at 8 51 04 AM](https://user-images.githubusercontent.com/22875260/105504223-84a1a280-5c95-11eb-9856-49021e9aa670.png)

**Comment by AndreasFurster** [comment]
I'm having the same issue on InfluxDB 2.0 Cloud (https://westeurope-1.azure.cloud2.influxdata.com) using Flux. It randomly occurs around 15% of the time. 

![image](https://user-images.githubusercontent.com/7996369/107200280-ca7d9b00-69f7-11eb-9708-af5b278ddcc4.png)

**Comment by mattgaviota** [comment]
Same problem here on influxDB 2.0 Cloud (https://eastus-1.azure.cloud2.influxdata.com/) using Flux as well.

**Comment by angadsingh** [comment]
same here. using influxdb 2.0 (https://eu-central-1-1.aws.cloud2.influxdata.com/) and flux.

**Comment by HarveyAtwal** [comment]
The queries were working earlier today, but i'm running into same memory allocation limit reached error. As a cloud provider it makes me worry about the stability of the product.

Query:
from(bucket: "xxxx")
    |> range(start: -7d, stop: now())
    |> drop(columns: ["_field", "_measurement"])
    |> aggregateWindow(every: 3h, fn: count, column: "_value", createEmpty: true)
    |> drop(columns: ["_start", "_stop"])
    |> map(fn: (r) => ({ r with _time: int(v: uint(v: r._time)) / 1000 / 1000 / 1000 }))


I can't imagine it's actually hitting a 10mb limit, but I could be wrong. Starting the range from -6d is roughly ~200kb of compressed data.

**Comment by raymond4entrak** [comment]
Same problem here. Any update after 6 months?

**Comment by aanthony1243** [comment]
We believe that the inconsistent memory allocation errors in cloud2 should be resolved.  They have not been eliminated, but the new system behavior is that the query will either always succeed, or always run out memory, consistently.  If you continue to get memory allocation errors, this would be a separate issue around query usage and a new issue should be opened.
