### ISSUE TITLE
Graph display bug in using influxdata cloud v2 Data Explorer 

### ISSUE THREAD

**Issue by shf0328** [influxdata/influxdb#19883]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

I’m a new user who just start to use influxDB cloud v2. And I have met a bug when using the Data Explorer.

1. create a bucket named `test`

2. insert 1 point into that bucket by following commands:
`curl --request POST "https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/write?org=<YOUR_ORG>&bucket=test&precision=s" --header "Authorization: Token <YOUR_TOKEN>" --data-raw 'my_measure height=100 1604181600'`

I expect I insert 1 data point at unix time stamp 1604181600 at precision second. So that is 2020-10-31 and at 10pm UTC time (google any unix time converter to check it).

3. view the data in data explorer

So here is the problem, when I view data in past 7 days, the point shows in the graph says 2020-10-31 and at 10:30pm UTC time (check my uploaded image 1)

Then I change the timerange to view data in past 30 days, the point shows in the graph says the point shows in the graph says 2020-10-31 and at 11:00pm UTC time (check my uploaded image 2)

![1](https://user-images.githubusercontent.com/8691651/97920268-0d9be400-1d0e-11eb-9cd9-ab2d7e2e1639.JPG)
![2](https://user-images.githubusercontent.com/8691651/97920271-0e347a80-1d0e-11eb-8b29-01e303097e9c.JPG)

__Expected behavior:__

Expect to see daily data on 2020-10-31 and at 10:00pm UTC time

__Actual behavior:__

when I view data in past 7 days, the point shows in the graph says 2020-10-31 and at 10:30pm UTC time (check my uploaded image 1)

Then I change the timerange to view data in past 30 days, the point shows in the graph says the point shows in the graph says 2020-10-31 and at 11:00pm UTC time (check my uploaded image 2)

__Environment info:__

I'm using the influxdata cloud v2 in Chrome 86.0.4240.111, win 10. 

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by russorat** [comment]
@shf0328 thanks for the report. you are seeing this because we are grouping the data into 30 min windows in the UI for a 7 day time range. Flip over to the Script editor, remove the aggregate function, and you will see your single point at the correct time.

![image](https://user-images.githubusercontent.com/4805997/97924293-42ab3500-1d14-11eb-8067-f4a135d7f5d5.png)

**Comment by shf0328** [comment]
Oh, I see, thanks very much, remove the aggregation works.

But then I guess that is still confusing? data point at 22:00 is grouped to 22:30 window instead of 22:00 window when using half hour slot?

**Comment by russorat** [comment]
@shf0328 yeah, for a single point it is a little confusing, i agree. When you have many points, and you are aggregating them, it gets slightly less confusing. Flux uses `[start, stop)` as the boundaries for the ranges.
