### ISSUE TITLE
"influx setup" against v2.0.0-rc.3 fails validation for non-infinite retention period

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#19884]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run `influx setup` against a fresh instance of InfluxDB 2.0
2. Enter a number when prompted `Please type your retention period in hours`
3. Confirm when asked:
```
Welcome to InfluxDB 2.0!
Please type your primary username: test

Please type your password:

Please type your password again:

Please type your primary organization name: test

Please type your primary bucket name: test

Please type your retention period in hours.
Or press ENTER for infinite.: 72


You have entered:
  Username:          test
  Organization:      test
  Bucket:            test
  Retention Period:  72 hrs
Confirm? (y/n): y
```

__Expected behavior:__
I expect the setup command to successfully complete, and write default configs into the home directory.

__Actual behavior:__
The command exits with:
```
Error: failed to setup instance: retention policy duration must be at least 1h0m0s
See 'influx setup -h' for help
```
Initial config files aren't written into the home directory, but something is initialized within the DB because running `influx setup` again fails with:
```
Error: instance at "<host>" has already been setup
See 'influx setup -h' for help
```

__Environment info:__

* System info: `Linux 4.19.76-linuxkit x86_64`
* InfluxDB version: `InfluxDB 2.0.0-rc.3 (git: f46a3bd91e) build_date: 2020-10-29T22:17:55Z`
* Running both `influxd` and `influx` within Docker for Mac

__Logs:__
Within the `influxd` logs, I see:
```
2020-11-02T21:23:46.592132Z     error   api error encountered   {"log_id": "0QEiLRDG000", "error": "retention policy duration must be at least 1h0m0s"}
```

**Comment by danxmoran** [comment]
I also tried entering `72h` when prompted, but that gets rejected by the CLI upfront.

**Comment by stuartcarnie** [comment]
Something else that looks suspicious in the onboarding code:

https://github.com/influxdata/influxdb/blob/d965225136ea2ecc2841265e3dbc9e70cf5eb288/tenant/service_onboarding.go#L125

`req.RetentionPeriod` is already a `time.Duration`, so multiplying it again is incorrect.

**Comment by stuartcarnie** [comment]
The debugger shows that

1. The `req.RetentionPeriod` looks correct (259200000000000 ns) == 259200000000000 ÷ 1e9 ÷ 60 ÷ 60 = 72 hours

2. Multiplying again causes the value to overflow 👎 

![image](https://user-images.githubusercontent.com/52852/97924110-5bb7e400-1d1c-11eb-93d2-d314b9000401.png)
