### ISSUE TITLE
JS Perf

### ISSUE THREAD

**Issue by 121watts** [influxdata/influxdb#19898]
Make Lighthouse performance green.  Currently at a score of 20/100.  Just adding code-splitting brings it up to ~60.

Production Lighthouse Report from tools: [https://app.zenhub.com/files/13124802/0dcaa034-83cf-4c62-b0ec-22ce9bfd18fc/download](https://app.zenhub.com/files/13124802/0dcaa034-83cf-4c62-b0ec-22ce9bfd18fc/download)

Local prod build Lighthouse Report: [https://app.zenhub.com/files/13124802/c8b568bf-748b-4a21-8613-46a850d25ca5/download](https://app.zenhub.com/files/13124802/c8b568bf-748b-4a21-8613-46a850d25ca5/download)

**Comment by drdelambre** [comment]
audit the bundle

**Comment by drdelambre** [comment]
finish up query parsing / cache work.
one function to call, gets cached based on magic, returns fromFluxResult

**Comment by drdelambre** [comment]
use scoped reducers for transient data

**Comment by drdelambre** [comment]
fix error boundaries:
make it not look like shit
never let navigation disappear
define sli level boundaries so we can answer questions like "how many times did a user not see a dashboard cell because of an error"

**Comment by drdelambre** [comment]
make this work: https://securityheaders.com/?q=https%3A%2F%2Fus-west-2-1.aws.cloud2.influxdata.com%2Fhttps%3A%2F%2Fus-west-1.influxdata.com%2F&followRedirects=on

**Comment by drdelambre** [comment]
misc: https://github.com/influxdata/ui/issues/256

**Comment by 121watts** [comment]
im going to close this issue now that we have a web perf epic
