### ISSUE TITLE
Error Boundary Audit

### ISSUE THREAD

**Issue by 121watts** [influxdata/influxdb#19907]
fix error boundaries:

make it not look like 💩..  if a page error boundary gets triggered have a nice page wide error display.  if it's a leaf node, have a reasonable default.

never let navigation disappear

define sli level boundaries so we can answer questions like "how many times did a user not see a dashboard cell because of an error"

**Comment by russorat** [comment]
@joelfried was this completed? if so, could you link to a pr an close?

**Comment by joelfried** [comment]
This was completed in https://github.com/influxdata/ui/pull/364.
