### ISSUE TITLE
upgrade process generates a file named config.toml but default used by 2.x is config.yaml

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19929]
according to the influxd 2.0 help:
```
	A config file can be provided via the INFLUXD_CONFIG_PATH env var. If a file is
	not provided via an env var, influxd will look in the current directory for a
	config.yaml file. If one does not exist, then it will continue unchanged.
```

yet the upgrade process generates a file named `config.toml` and i don't see a reason why (there's no explicit toml syntax)

**Comment by danxmoran** [comment]
@russorat it looks like the config-parser will handle either `config.yaml` or `config.toml`. Do we want to modify the `upgrade` command to produce YAML, or just update the help text to match the current behavior?

**Comment by russorat** [comment]
The name of the file generated should match the default name we look for when starting 2.0. Specifically: `influxd will look in the current directory for a config.yaml file`

you are saying it will find either a config.toml or a config.yaml by default? if that's the case, we can simply update the text in the help message,
