### ISSUE TITLE
V1 write API doesn't handle buckets that don't fit the "db/rp" pattern

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#19949]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a `test` bucket using `influx setup`
2. Create a `test-user` V1 token using `influx v1 auth create`, granting write access on the bucket
3. Attempt to write data using the `test-user` token and the write API:
```
curl -u test-user:${TEST_PWD} localhost:8086/write\?db=test -d "cpu foo=10,bar=11"
```

__Expected behavior:__
The write should succeed

__Actual behavior:__
The write fails with a permissions error. Running `influx bucket list` shows a new `test/autogen` bucket has been created.

By stepping through the code, I was able to find that the V1 API:
1. Checks if an RP was given in the command, and uses "autogen" if not
2. Checks for the presence of the bucket named "db/rp", creating it if not found
3. Attempts to write into the new bucket

Step 3 fails the auth check because the user is authorized to write into "test", not "test/autogen"

**Comment by stuartcarnie** [comment]
@danxmoran I believe this will be resolved with #19945

**Comment by danxmoran** [comment]
If not by that, then I'd expect by #19954

**Comment by stuartcarnie** [comment]
This is no longer an issue, as we're not auto-creating buckets and DB/RP mappings. We have verified that writes are now working after mappings are setup.
