### ISSUE TITLE
Automate (semi-automate) InfluxDB OSS 1.x upgrade to InfluxDB 2.0

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#19957]
TBD

**Comment by gshif** [comment]
##### Setup:
---

- Get the latest released InfluxDB OSS 1.x
- Enable authentication. If deploying using `pcl`, then environment variable(s) can be used to enable certain configuration parameters. Example of how it is done can be seen in performance query/inch tests.
- Setup `ADMIN` user (has all of the privileges) and restart the cluster.
- As as an ADMIN user create 3 more users:
   - `a` user with `READ` permission for a database `A`
   - `b` user with `WRITE` permission for a database `A`
   - `c` user with `READ/WRITE` permissions for a database `A`
- Have the latest telegraf configured to write into database `A` as a user `b`

##### Upgrade
---

- Install the latest InfluxDB 2.x
- Run the upgrade from 1.x to 2.x (could be the default flags/params)

##### Verifications
---
__Scenario 1__
- Telegraf should be successfully writing into migrated database `A` with the same user `b`
- Writing into migrated database `A` using `/write` (v1) endpoint as a migrated user with `WRITE` permissions and `READ/WRITE` permissions should be successful. Example:
   ```
   curl -vv -u b:b -X POST http://localhost:8086/write?db=test_db_1 --data-binary "m,r=1 f=1
   ```
- Writing into migrated database `A` using `/api/v2/write` (v2) endpoint as a newly created 2.x user with `WRITE` permissions

__Scenario 2__
- Read from a migrated database `A`(bucket)  as a migrated user `a` with `READ` permissions using `/query` (v1) endpoint
- Read from a migrated database `A`(bucket) as newly created 2.x user with `READ` permissions using `api/v2/query` (v2) endpoint.

**Comment by psteinbachs** [comment]
2.x supports multiple ways to upgrade per https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/
