### ISSUE TITLE
Flows: UX Clean Up

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/influxdb#19977]
### Misc
- On the List Page, empty state label should say "`Create Flow` to get started" & Create Flow is a button to create flow.
- Insert Cell: Change labels to Input, Pass-through, Output

### All Cells
Given: I see a cell that hasn't been previewed/ran
When: I see "Run Flow to See Results"
Then: It says "Run" or "Preview to see results" depending on what button is selected at the top-level of the notebook (also note text change)
And: the icon is a Play caret not a lightening bolt to visually connect to the button above

### Metric Selector
1. Check to see why the Parser is so slow to load

2. On the Metric selector decapitalize the nouns in the search field to: field, measurement, tag

3. Metric Selector always shows schema for loading state even after a metric is selected.
GIVEN: I have selected _n_ metrics
WHEN: I click back into the Search field
THEN: I see all available metrics in the dropdown

4. Metric Select schema loading takes a long time, perhaps infinite scroll in the metric selector. What can be done to improve load time?

5. Strings in Metric Selector
Given: I have selected a string
And:  any aggregate is selected by default
When: I hit run/preview
Then: First is selected by default

6. Change error message when a string doesn't work with selected aggregate {"code":"invalid","message":"unsupported input type for mean aggregate: string"}
change to "String is unsupported input type for mean aggregate: change to first or last." <-- something a bit more helpful
7. In the Metric Selector schema, Label the value not the tag, otherwise everything is a string because tags are strings
8. Show window period of the aggregation even though it's not changeable

### Visualization Cell
1. Visualization cell update text to: "This cell will display results from the previous cell"

### Flux Script
2. Flux Script Cell: Switch Line 1 & Line 2 defaults so that  "Use __Previous_Result__ to continue building from previous cell" is line 1 and
"Enter Flux Script here" is line 2

### Export As Task
1. In the overlay panel, `Export Task` button should be enabled by default & the input fields have required asterisk
Given: I do not have `Name` or `Run Every`
When: I click `Export Task`
Then: `Name` & `Run Every` are highlighted as an error state

2. "Export to Task" generates a notification with the name of the Task you just created, and I stay on the Notebook 

### Run
When: I click Run
Then: The data tables reload with spinner
And: I get confirmation a notification that the data written "Run successful. {BucketName} updated."

**Comment by mnorriswalker** [comment]
CC @noramullen1 add your text changes to this Issue, please. 

@barbaranelson see "All Cells" section above the label `Preview` or `Run `will change depending on the button selection (`Preview` is default.) We could also link the text `Preview` and `Run` to complete the action but the concern was that it runs/previews the entire notebook not just the cell and the placement doesn't make that clear. So we're going to stick to the top-level control and research further before making it clickable.

**Comment by barbaranelson** [comment]
Could we default to Run instead of Preview? Preview feels like a fairly advanced concept and is only applicable if I have defined an output bucket.  That would address my concern for the first-time user.

**Comment by mnorriswalker** [comment]
Issue moved to [influxdata/ui #302](https://github.com/influxdata/ui/issues/302) via [**ZenHub**](https://www.zenhub.com/)
