### ISSUE TITLE
Data race in tsi1 package [backport 2.0.x]

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#19981]
Backport the fix for #19664 to the `2.0` branch

**Comment by psteinbachs** [comment]
This looks like a dupe of https://github.com/influxdata/influxdb/issues/19664

**Comment by danxmoran** [comment]
Ah good catch, closing this one then

**Comment by danxmoran** [comment]
Reopening to track the backport to 2.0.x

**Comment by danxmoran** [comment]
Closed in #20072
