### ISSUE TITLE
[Question] Interactive shell after upgrade to 2.0.1

### ISSUE THREAD

**Issue by kakila** [influxdata/influxdb#19986]
Dear all,

After the upgrade to Influx CLI 2.0.1 (git: 37cc047133) build_date: 2020-11-11T03:53:31Z
I cannot access anymore the interactive client that the previous influx offered.

Is there an equivalent interactive prompt?

Can one send InfluxQL queries with the new client? I cannot find a way. If it is not possible, is there a way to have the old client also runnning to be ale to query db that did not have Flux activated?

Thanks

**Comment by evanalexandre** [comment]
I am experiencing the same issue.

Before, the "influx" command in the terminal returned the Influx CLI prompt.

After upgrade to Influx CLI 2.0.1 (git: 37cc047133), the same "influx" command returns the same output as "influx --help".

**Comment by sanderson** [comment]
@kakila @evanalexandre You can use the Flux REPL as an interactive shell to query InfluxDB 2.0 or InfluxDB Cloud. You have to build the Flux REPL from source (the Flux repo), but it's pretty simple to do. These links might prove useful:

- https://docs.influxdata.com/influxdb/v2.0/tools/repl/
- https://github.com/influxdata/flux/#getting-started

**Comment by evanalexandre** [comment]
Thank you, @sanderson. Flux REPL will resolve this issue for me.

It was not clear that the old influx interface would be removed during the upgrade from 1.x to 2.0. Is there a good place to add this to the documentation? Perhaps [here](https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/), although maybe this does not qualify as an important consideration.

**Comment by cosmo86** [comment]
Is there a build guide for Windows OS？

**Comment by cosmo86** [comment]
In the https://github.com/influxdata/flux/#getting-started link, there are only Linux and Mac OS instructions.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/51028745/178139413-adfafcac-7500-4972-a905-d5ac0a561229.png">

**Comment by spearman** [comment]
Why isn't this part of the influxdb cli?
