### ISSUE TITLE
Port test pipeline and InfluxQL test suite

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#19998]
## What

Port the Cloud implementation of the InfluxQL test suite to OSS

- [ ] `tests` package to provide the `Pipeline` framework
- [ ] `influxql/_v1Tests` package, which provides extensive coverage of the InfluxQL query engine
- [ ] `influxql/_v1Validation` package, which provides a configuration framework for additional test coverage

**Comment by danxmoran** [comment]
"Helpfully" closed by GitHub on PR 1 of 3, reopening!

**Comment by danxmoran** [comment]
@stuartcarnie is this a dup of #19430?

**Comment by stuartcarnie** [comment]
Thanks!

**Comment by stuartcarnie** [comment]
@danxmoran yes, we can close that one 👍
