### ISSUE TITLE
v2.x.x release documentation for binary (particularly for the Docker image)

### ISSUE THREAD

**Issue by mkarlesky** [influxdata/influxdb#19997]
__Proposal:__
An up-to-date Readme for v2 builds, particularly discussing details of the Docker image.

__Current behavior:__
Currently, the only readily available documentation appears to be that which has been previously published for the v1 product. v1 and v2 have diverged on issues such as storage location (e.g. `/var/lib/influxdb` vs. `/root/.influxdbv2/`) and user / group IDs. This has direct impact on Docker container usage and has led to unexpected behaviors and much troubleshooting.

It's entirely possible I've missed what I'm asking for, but all kinds of searching hasn't unearthed it.

__Desired behavior:__
A regularly updated Readme similar to that published with the v1 Docker image available for the v2 product. While I've concentrated on Docker in this discussion, a regularly updated source of information that discusses environment variables, storage locations, runtime permissions, etc. for the v2 product is the general request here.

**Comment by tgallacher** [comment]
💯   percent this. 

The challenge I've faced is that the [online docs](https://docs.influxdata.com/influxdb/v2.0/) default to `v2` (OSS), with a banner on the `v1` docs calling out that `v2` is the latest stable release. However, 

- the Docker docs for this version don't provide enough context/detail to be able to run v2 beyond a simple preview;
- the online docs don't provide enough detail/reference to a Docker-based setup (only the influx CLI): Thinking particularly around Telegraf set up
- The v2 Docker image is stored on the Redhat registry, not Docker hub -- does this indicate anything around the release being the "mainline"?
- The `influxdb:latest` tag points to `v1.8`; There is a note on the README, but I think this should be made clearer that the hub version is currently `v1.x` only.
- The v2 Docker image has no README: what are the storage requirements, config params, etc
- The `v1` -> `v2` upgrade path for Docker setups notes for admins to "wait", as it isn't documented yet

As I am new to influxdb, I don't have the mental model of how the related components (Telegraf, Chronograf, etc) fit together. While I have managed to get some of this from the `v1` docs, I'm not sure of how much of this is related to v2, as I understand that the `v2` architecture has changed, with most being pre-bundled together within the Docker image / influx binary. 

I would love to use this tool; initial review of the UI and capabilities is exactly what I am looking for. However, at the minute I am burning too much time trying to reverse engineer how to set up and configure v2 as there doesn't appear to be enough docs on this. 

As the Docker set up isn't fully documented-- or (possibly) fully supported-- yet, is the official recommendation to use `v1.8` instead in this case?

**Comment by mkarlesky** [comment]
@tgallacher I can help you out with a couple things:

- In InfluxDB v2, there is no Chronograf or Kapacitor. The visualization features of InfluxDB v2 replace the former, and the Flux engine + Tasks basically replace the latter. In the latest version of the platform there's only InfluxDB and either Telegraf or client libraries for ingesting data.
- I don't know this for a fact, but I believe InfluxData uses RedHat's quay.io Docker registry for its publicly available development work. I don't know when InfluxDB v2 will be available on DockerHub. My experience has been that quay.io is a stepping stone towards more “regular” releases available on DockerHub, and I wouldn't expect a whole lot of support for the Docker image while it lives here. That said, my request was for a handful of basic details for those of us who are well familiar with the platform and can make our way with these still early releases of InfluxDB v2 and the Flux language. A tiny bit more release documentation would go a long way until InfluxDB v2 is ready for primetime.
- Telegraf set up doesn't actually require a whole lot. You can use all of the current documentation for Telegraf to get it working with InfluxDB v2. It's a data processing tool with a variety of input, transformation, and output plugins. To work with InfluxDB v2, all you need is to set up the InfluxDB v2 output plugin configuration per the documentation and ensure your Telegraf instance and InfluxDB instance can talk given the particulars of the two applications. Obviously, you also need some sort of data source configured as an input.

I hope this is helpful.

**Comment by tgallacher** [comment]
Thanks @mkarlesky ! This is helpful. 

* I was thinking that Chronograf + Kapacitor wasn't likely to play much in v2. Although I hadn't actually got that far yet; have been largely figuring out Telegraf
* Makes sense. I think it would be helpful if there were some notes on the OSS v2 doc website to call out for Docker users this sentiment: The fact that it is v2 stable, but the Docker deployment isn't yet fully supported. I think that would help steer folks in the right direction (e.g. v1.x) -- or at least set the expectation that the Docker set up isn't fully ready yet. 
* Thanks. I had gotten to the point of saving the Telegraf config in the influxDB, but wasn't sure if I still needed the separate Telegraf agent -- wasn't sure if v2 would auto kick-off a Telegraf instance when the configuration was saved. I'll setup an agent and see how I get on

Maybe one question you can possibly help with: Data persistence within Docker setup. 

During my investigations with my set up (Docker compose) I had to stop and restart the container. In doing so, I lost my default user, org, and bucket which I configured during the previous install; I had to repeat the user setup. Influx had somehow lost it. 

For data storage, I am currently mounting a Docker volume (created externally to the compose setup) into `/var/lib/influxdb`, but my default user, org etc still got lost. Is there another dir I should be saving somewhere, or have you encountered this?

Thanks again for helping out.

**Comment by mkarlesky** [comment]
@tgallacher Your question is spot on. That specific problem is what inspired this issue! (See my original message up top.) You're doing the correct thing with your volume; you're just using the wrong path on this inside of the container for the InfluxDB instance. You're correctly assuming it should be `/var/lib/influxdb` as that's what it's always been. Turns out it's actually `/root/.influxdbv2/`, but this is not documented.

**Comment by tgallacher** [comment]
> You're correctly assuming it should be /var/lib/influxdb as that's what it's always been. Turns out it's actually /root/.influxdbv2/,

Magic thanks!

**Comment by danxmoran** [comment]
@mkarlesky @tgallacher as part of the upcoming 2.0.4 release, we're going to resume pushing releases to DockerHub with proper docs. It looks like it might be too little too late for both of you (sorry!), but if you have time / interest I'd be interested in your feedback on a preview of the new DockerHub build & docs.

I've pushed an RC0 build to `quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0`, and pasted the Markdown for the new docs below. Please let me know if you get time to take a look; even if you don't have time to run the image, I'd appreciate feedback on the details in the docs.

New docs:

# InfluxDB

InfluxDB is a time series database built from the ground up to handle high write and query loads. InfluxDB is meant to be used as a backing store for any use case involving large amounts of timestamped data, including DevOps monitoring, application metrics, IoT sensor data, and real-time analytics.

[InfluxDB Documentation](https://docs.influxdata.com/influxdb/latest/)

## `latest` updated to 2.0

The `latest` tag for this image now points to the latest released implementation of InfluxDB 2.0. If you are using the `latest` tag and
would like to stay on the 1.x line, please update your environment to reference the `1.8` tag.

## Using this Image - 2.x

### Running the container

The InfluxDB image exposes a shared volume under `/var/lib/influxdb2`. You can mount a host directory to that point to access persisted container data. A typical invocation of the container might be:

```console
$ docker run -p 8086:8086 \
      -v $PWD:/var/lib/influxdb2 \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

Modify `$PWD` to the directory where you want to store data associated with the InfluxDB container.

You can also have Docker control the volume mountpoint by using a named volume.

```console
$ docker run -p 8086:8086 \
      -v influxdb2:/var/lib/influxdb2 \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

### Exposed Ports

The following ports are important and are used by InfluxDB.

- 8086 HTTP UI and API port

The HTTP port will be automatically exposed when using `docker run -P`.

Find more about API Endpoints & Ports [here](https://docs.influxdata.com/influxdb/v2.0/reference/api/).

### Configuration

InfluxDB can be configured using a mix of a config file, environment variables, and CLI options. To mount a configuration file and use it with the server, you can use this command to generate the default configuration file:

```console
$ docker run --rm quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0 \
      influxd print-config > config.yml
```

Modify the default configuration, which will now be available under `$PWD`. Then start the InfluxDB container:

```console
$ docker run -p 8086:8086 \
      -v $PWD/config.yml:/etc/influxdb2/config.yml:ro \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

Modify `$PWD` to be the directory where you want to store the configuration file.

Individual config settings can be overridden by environment variables. The variables must be named using the format `INFLUXD_${SNAKE_CASE_NAME}`. The `SNAKE_CASE_NAME` for an option will be the option's name with all dashes (`-`) replaced by underscores (`_`), in all caps.

Examples:

```console
# Config setting: bolt-path
INFLUXD_BOLT_PATH=/root/influxdb.bolt
# Config setting: no-tasks
INFLUXD_NO_TASKS=true
# Config setting: storage-wal-fsync-delay
INFLUXD_STORAGE_WAL_FSYNC_DELAY=15m
```

Finally, all config options can be passed as CLI options:

```console
$ docker run -p 8086:8086 \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0 --storage-wal-fsync-delay=15m
```

CLI options take precedence over environment variables.

Find more about configuring InfluxDB [here](https://docs.influxdata.com/influxdb/v2.0/reference/config-options/).

### Database Setup

InfluxDB 2.0 requires authentication. A special API exists to bootstrap the first super-user in the database, along with an initial organization and bucket. It's possible to access this API manually, or to run it automatically via environment variables.

#### Manual Setup

If your InfluxDB container is running locally (or on a host exposed to the network), you can perform initial setup from outside the container using either the UI or the `influx` CLI. Find more about setting up InfluxDB using these methods [here](https://docs.influxdata.com/influxdb/v2.0/get-started/#set-up-influxdb).

It's also possible to perform manual setup from within the container using `docker exec`. For example, if you start the container:

```console
$ docker run -d -p 8086:8086 \
      --name influxdb2 \
      -v $PWD:/var/lib/influxdb2 \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

You can then run the `influx` client in the container:

```console
$ docker exec influxdb2 influx setup \
      --username $USERNAME \
      --password $PASSWORD \
      --org $ORGANIZATION \
      --bucket $BUCKET
```

Running setup from within the container will cause CLI configs to be written to `/etc/influxdb2/influx-configs`. You can then use the `influx` CLI from within the container to extract the generated admin token:

```console
# Using table output + cut
$ docker exec influxdb2 influx auth list \
      --user $USERNAME \
      --hide-headers | cut -f 3

# Using JSON output + jq
$ docker exec influxdb2 influx auth list \
      --user $USERNAME \
      --json | jq -r '.[].token'
```

Alternatively, you could configure your initial InfluxDB run to mount `/etc/influxdb2` as a volume:

```console
$ docker run -d -p 8086:8086 \
      --name influxdb2 \
      -v $PWD/data:/var/lib/influxdb2 \
      -v $PWD/config:/etc/influxdb2 \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

This will make the generated CLI configs available to the host.

#### Automated Setup

The InfluxDB image contains some extra functionality to automatically bootstrap the system. This functionality is enabled by setting the `INFLUXD_INIT_MODE` environment variable to the value `setup` when running the container. Additional environment variables are used to configure the setup logic:

* `INFLUXD_INIT_USERNAME`: The username to set for the system's initial super-user (**Required**).
* `INFLUXD_INIT_PASSWORD`: The password to set for the system's inital super-user (**Required**).
* `INFLUXD_INIT_ORG`: The name to set for the system's initial organization (**Required**).
* `INFLUXD_INIT_BUCKET`: The name to set for the system's initial bucket (**Required**).
* `INFLUXD_INIT_RETENTION`: The duration the system's initial bucket should retain data. If not set, the initial bucket will retain data forever.
* `INFLUXD_INIT_ADMIN_TOKEN`: The authentication token to associate with the system's initial super-user. If not set, a token will be auto-generated by the system.

Automated setup will generate metadata files and CLI configurations. It's recommended to mount volumes at both paths to avoid losing data.

For example, a minimal invocation of automated setup is:

```console
$ docker run -d -p 8086:8086 \
      -v $PWD/data:/var/lib/influxdb2 \
      -v $PWD/config:/etc/influxdb2 \
      -e INFLUXD_INIT_MODE=setup \
      -e INFLUXD_INIT_USERNAME=my-user \
      -e INFLUXD_INIT_PASSWORD=my-password \
      -e INFLUXD_INIT_ORG=my-org \
      -e INFLUXD_INIT_BUCKET=my-bucket \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

And an example using all available options is:

```console
$ docker run -d -p 8086:8086 \
      -v $PWD/data:/var/lib/influxdb2 \
      -v $PWD/config:/etc/influxdb2 \
      -e INFLUXD_INIT_MODE=setup \
      -e INFLUXD_INIT_USERNAME=my-user \
      -e INFLUXD_INIT_PASSWORD=my-password \
      -e INFLUXD_INIT_ORG=my-org \
      -e INFLUXD_INIT_BUCKET=my-bucket \
      -e INFLUXD_INIT_RETENTION=1w \
      -e INFLUXD_INIT_ADMIN_TOKEN=my-super-secret-auth-token \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

**NOTE:** Automated setup will not run if an existing boltdb file is found at the configured path. This behavior allows for the InfluxDB container to reboot post-setup without encountering "DB is already set up" errors.

### Upgrading from 1.x

InfluxDB 2.0 provides a 1.x-compatible API, but expects a different storage layout on disk. To bridge this mismatch, the InfluxDB image contains extra functionality to migrate 1.x data and config into 2.x layouts automatically before booting the `influxd` server.

The automated upgrade process also bootstraps an initial admin user, organization, and bucket in the system, so it uses the same set of environment variables as the automated setup process described above:
* `INFLUXD_INIT_USERNAME`: The username to set for the system's initial super-user (**Required**).
* `INFLUXD_INIT_PASSWORD`: The password to set for the system's inital super-user (**Required**).
* `INFLUXD_INIT_ORG`: The name to set for the system's initial organization (**Required**).
* `INFLUXD_INIT_BUCKET`: The name to set for the system's initial bucket (**Required**).
* `INFLUXD_INIT_RETENTION`: The duration the system's initial bucket should retain data. If not set, the initial bucket will retain data forever.
* `INFLUXD_INIT_ADMIN_TOKEN`: The authentication token to associate with the system's initial super-user. If not set, a token will be auto-generated by the system.

It also requires extra volumes to be mounted into the 2.x container:
* Data from the 1.x instance
* Custom config from the 1.x instance (if any)

The upgrade process searches for mounted 1.x data / config in this priority order:
1. A config file referred to by the `INFLUXDB_INIT_UPGRADE_V1_CONFIG` environment variable
2. A data directory referred to by the `INFLUXDB_INIT_UPGRADE_V1_DIR` environment variable
3. A config file mounted at `/etc/influxdb/influxdb.conf`
4. A data directory mounted at `/var/lib/influxdb`

Finally, the `INFLUXD_INIT_MODE` environment variable must be set to `upgrade`.

Automated upgrade will generate both data and config files, by default under `/var/lib/influxdb2` and `/etc/influxdb2`. It's recommended to mount volumes at both paths to avoid losing data.

**NOTE:** Automated upgrade will not run if an existing boltdb file is found at the configured path. This behavior allows for the InfluxDB container to reboot post-upgrade without overwriting migrated data.

Find more about the InfluxDB upgrade process [here](https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/). See below for examples of common upgrade scenarios.

#### Upgrade Example - Minimal

Assume you've been running a minimal 1.x deployment:

```console
$ docker run -p 8086:8086 \
      -v influxdb:/var/lib/influxdb \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0:1.8
```

To upgrade this deployment to 2.x, stop the running 1.x container, then run:

```console
$ docker run -p 8086:8086 \
      -v influxdb:/var/lib/influxdb \
      -v influxdb2:/var/lib/influxdb2 \
      -e INFLUXD_INIT_MODE=upgrade \
      -e INFLUXD_INIT_USERNAME=my-user \
      -e INFLUXD_INIT_PASSWORD=my-password \
      -e INFLUXD_INIT_ORG=my-org \
      -e INFLUXD_INIT_BUCKET=my-bucket \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

#### Upgrade Example - Custom 1.x Config

Assume you've been running a 1.x deployment with customized config:

```console
$ docker run -p 8086:8086 \
      -v influxdb:/var/lib/influxdb \
      -v $PWD/influxdb.conf:/etc/influxdb/influxdb.conf:ro \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0:1.8
```

To upgrade this deployment to 2.x, stop the running container, then run:

```console
$ docker run -p 8086:8086 \
      -v influxdb:/var/lib/influxdb \
      -v influxdb2:/var/lib/influxdb2 \
      -v $PWD/influxdb.conf:/etc/influxdb/influxdb.conf:ro \
      -e INFLUXD_INIT_MODE=upgrade \
      -e INFLUXD_INIT_USERNAME=my-user \
      -e INFLUXD_INIT_PASSWORD=my-password \
      -e INFLUXD_INIT_ORG=my-org \
      -e INFLUXD_INIT_BUCKET=my-bucket \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

#### Upgrade Example - Custom Paths

Assume you've been running a 1.x deployment with data and config mounted at custom paths:

```console
$ docker run -p 8086:8086 \
      -v influxdb:/root/influxdb/data \
      -v $PWD/influxdb.conf:/root/influxdb/influxdb.conf:ro \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0:1.8 -config /root/influxdb/influxdb.conf
```

To upgrade this deployment to 2.x, first decide if you'd like to keep using custom paths, or use the 2.x defaults. If you decide to use the defaults, you'd stop the running 1.x container, then run:

```console
$ docker run -p 8086:8086 \
      -v influxdb:/root/influxdb/data \
      -v influxdb2:/var/lib/influxdb2 \
      -v $PWD/influxdb.conf:/root/influxdb/influxdb.conf:ro \
      -e INFLUXD_INIT_MODE=upgrade \
      -e INFLUXD_INIT_USERNAME=my-user \
      -e INFLUXD_INIT_PASSWORD=my-password \
      -e INFLUXD_INIT_ORG=my-org \
      -e INFLUXD_INIT_BUCKET=my-bucket \
      -e INFLUXDB_INIT_UPGRADE_V1_CONFIG=/root/influxdb/influxdb.conf \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

To retain your custom paths, you'd run:

```console
$ docker run -p 8086:8086 \
      -v influxdb:/root/influxdb/data \
      -v influxdb2:/root/influxdb2/data \
      -v $PWD/influxdb.conf:/root/influxdb/influxdb.conf:ro \
      -e INFLUXD_INIT_MODE=upgrade \
      -e INFLUXD_INIT_USERNAME=my-user \
      -e INFLUXD_INIT_PASSWORD=my-password \
      -e INFLUXD_INIT_ORG=my-org \
      -e INFLUXD_INIT_BUCKET=my-bucket \
      -e INFLUXDB_INIT_UPGRADE_V1_CONFIG=/root/influxdb/influxdb.conf \
      -e INFLUXD_CONFIG_PATH=/root/influxdb2/config.toml \
      -e INFLUXD_BOLT_PATH=/root/influxdb2/influxdb.bolt \
      -e INFLUXD_ENGINE_PATH=/root/influxdb2/engine \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

### Custom Initialization Scripts

The InfluxDB image supports running arbitrary initialization scripts after initial system setup, on both the `setup` and `upgrade` paths. Scripts must have extension `.sh` and be mounted inside of the `/docker-entrypoint-initdb.d` directory. When multiple scripts are present, they will be executed in lexical sort order by name.

As a convenience for script-writers, the image will export a number of variables into the environment before executing any scripts:
* `INFLUX_CONFIGS_PATH`: Path to the CLI configs file written by `setup`/`upgrade`
* `INFLUX_HOST`: URL to the `influxd` instance running setup logic
* `INFLUXDB_INIT_USER_ID`: ID of the initial admin user created by `setup`/`upgrade`
* `INFLUXDB_INIT_ORG_ID`: ID of the initial organization created by `setup`/`upgrade`
* `INFLUXDB_INIT_BUCKET_ID`: ID of the initial bucket created by `setup`/`upgrade`

For example, if you wanted to grant write-access to a 1.x client on your initial bucket, you'd first create the file `$PWD/scripts/setup-v1.sh` with contents:

```bash
#!/bin/bash
set -e

influx v1 dbrp create \
  --bucket-id ${INFLUXDB_INIT_BUCKET_ID} \
  --db ${V1_DB_NAME} \
  --rp ${V1_RP_NAME} \
  --default \
  --org ${INFLUXDB_INIT_ORG}

influx v1 auth create \
  --username ${V1_AUTH_USERNAME} \
  --password ${V1_AUTH_PASSWORD} \
  --write-bucket ${INFLUXDB_INIT_BUCKET_ID} \
  --org ${INFLUXDB_INIT_ORG}
```

Then you'd run:

```console
$ docker run -p 8086:8086 \
      -v $PWD/data:/var/lib/influxdb2 \
      -v $PWD/config:/etc/influxdb2 \
      -v $PWD/scripts:/docker-entrypoint-initdb.d \
      -e INFLUXD_INIT_MODE=setup \
      -e INFLUXD_INIT_USERNAME=my-user \
      -e INFLUXD_INIT_PASSWORD=my-password \
      -e INFLUXD_INIT_ORG=my-org \
      -e INFLUXD_INIT_BUCKET=my-bucket \
      -e V1_DB_NAME=v1-db \
      -e V1_RP_NAME=v1-rp \
      -e V1_AUTH_USERNAME=v1-user \
      -e V1_AUTH_PASSWORD=v1-password \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

**NOTE:** Custom scripts will not run if an existing boltdb file is found at the configured path (causing `setup` or `upgrade` to be skipped). This behavior allows for the InfluxDB container to reboot post-initialization without encountering errors from non-idempotent script commands.

**Comment by danxmoran** [comment]
Docs are staged for merge to DockerHub at docker-library/docs#1871

**Comment by mkarlesky** [comment]
@danxmoran This is incredible. (A) I had no idea all these nice options were available. (B) From a quick read I'd say this documentation is quite thorough and well organized. Very nice work. I've seen much more mature Docker images with far poorer documentation.

Nothing jumped out at me as missing or problematic. The hierarchy of information and organization works well. I suspect that any meaningful feedback will come from actually referencing this in real use. For me that will come soon enough. I'd say you've laid a very good base for any feedback and tweaks we users might have to offer in the near future.

**Comment by eloparco** [comment]
@danxmoran I tried with the following:
```
$ docker run -d -p 8086:8086 \
      -v $PWD/data:/var/lib/influxdb2 \
      -v $PWD/config:/etc/influxdb2 \
      -e INFLUXD_INIT_MODE=setup \
      -e INFLUXD_INIT_USERNAME=my-user \
      -e INFLUXD_INIT_PASSWORD=my-password \
      -e INFLUXD_INIT_ORG=my-org \
      -e INFLUXD_INIT_BUCKET=my-bucket \
      -e INFLUXD_INIT_RETENTION=1w \
      -e INFLUXD_INIT_ADMIN_TOKEN=my-super-secret-auth-token \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```
but when I navigate to localhost:8086 it's still asking for an initial setup. How can I solve this? Thanks

**Comment by danxmoran** [comment]
@eloparco argh, the env variables in the docs I pasted above are all wrong (they should start with `INFLUXDB_` instead of `INFLUXD_`. Thank you so much for trying the build out early and flagging the issue!

This should work for you:
```
$ docker run -d -p 8086:8086 \
      -v $PWD/data:/var/lib/influxdb2 \
      -v $PWD/config:/etc/influxdb2 \
      -e INFLUXDB_INIT_MODE=setup \
      -e INFLUXDB_INIT_USERNAME=my-user \
      -e INFLUXDB_INIT_PASSWORD=my-password \
      -e INFLUXDB_INIT_ORG=my-org \
      -e INFLUXDB_INIT_BUCKET=my-bucket \
      -e INFLUXDB_INIT_RETENTION=1w \
      -e INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token \
      quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0
```

**Comment by eloparco** [comment]
Thanks, I should have noticed!
I was trying using ```quay.io/influxdb/influxdb:v2.0.4``` as image, but there it doesn't work. Which is the latest stable version in which I can use these env variables?

**Comment by danxmoran** [comment]
The DockerHub build will have the functionality, it's currently in review at docker-library/official-images#9594

**Comment by eloparco** [comment]
Any idea on how to persist data when using docker? I read in the [docs](https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/#docker-users) and tried with ```-v influxdb2-data:/root/.influxdbv2``` but it doesn't seem to work.
I'm still referring to the image ```quay.io/influxdb/influxdb-dockerhub-rcs:v2.0.4-rc0```.
