### ISSUE TITLE
Is there a way/query to detect a Influxdb 2.0 comared to a 1.x?

### ISSUE THREAD

**Issue by Apollon77** [influxdata/influxdb#20009]
I maintain a plugin for influxdb for the smart home system ioBroker and I think about preparing comatibility. We already noticed that several command like SHOW DATABASES are not availabel in influxdb-1-compatibility-mode.

So the question is: How can I detect that a influxdb 2.0 is "on the other side" when I connect to it? Is there a "query command" where I can get a versionnumber? Or is it basically "SHOW DATABASE delivers an error" (but that could also be other reasons ... 

Any idea?

**Comment by danxmoran** [comment]
Hi @Apollon77, the response body of the `/health` endpoint includes version information, I think it would be helpful for your use-case.

For example, if I `curl` the endpoint when running v2.0.1 locally, I get back:
```
{"name":"influxdb", "message":"ready for queries and writes", "status":"pass", "checks":[], "version": "2.0.1", "commit": "37cc047133"}
```
It should work for 1.x as well, if I curl a local 1.8.3 I see:
```
{"checks":[],"message":"ready for queries and writes","name":"influxdb","status":"pass","version":"1.8.3"}
```

**Comment by Apollon77** [comment]
I think this can help a lot.
