### ISSUE TITLE
Only 100 buckets shown in InfluxDB UI

### ISSUE THREAD

**Issue by jsimomaa** [influxdata/influxdb#20048]
__Steps to reproduce:__

1. Create over 100 buckets
2. Open InfluxDB UI > Load Data > Buckets

__Expected behavior:__

See and apply filter to all buckets.

__Actual behavior:__
Only 100 buckets are shown and no UI for pagination.

__Environment info:__
```sh
$ uname -srm
Linux 4.15.0-112-generic x86_64
```
```sh
$ influxd version
InfluxDB 2.0.1 (git: 37cc047133) build_date: 2020-11-11T03:53:31Z
```

**Comment by docmerlin** [comment]
I'm able to reproduce this only I get a lot less than 100 buckets when I made 203 buckets.

**Comment by docmerlin** [comment]
Ok, seems there are two issues here.  The limit of 100 is with the api a limit of 20 is with the CLI, I'll make a separate issue for the CLI.

**Comment by timhallinflux** [comment]
we can up these limits in the short run while we look to address this via pagination.

**Comment by jsimomaa** [comment]
> we can up these limits in the short run while we look to address this via pagination.

Any news regarding the short run solution i.e. up the limits? 

This issue seems to happen also when running a flux-query to the API endpoint:

```
curl 'https://influxdb.example.com/api/v2/query?org=25b42d4a7678c59d' \
  -H 'authorization: Token xx' \
  -H 'content-type: application/json; encoding=utf-8' \
  -H 'accept: */*' \
  --data-binary '{"query":"from(bucket:\"c5ffcf95-823c-4a2d-ad4d-786cf313e41b\") \n      |> range(start:0) \n      |> filter(fn:(r) => true)\n      |> sample(n:4, pos:0)","dialect":{"header":true,"delimiter":",","quoteChar":"\"","commentPrefix":"#","annotations":["datatype","group","default"]},"type":"flux"}' \
  --compressed
{"code":"not found","message":"failed to initialize execute state: could not find bucket \"c5ffcf95-823c-4a2d-ad4d-786cf313e41b\""}
```

**Comment by drdelambre** [comment]
@russorat tried to make it 200 once. the short version of that story is that this requires an api fix to work

@jsimomaa try and send this flux, and let me know if it is any better
```
buckets()
  |> filter(fn: (r) => r.name !~ /^_/)
  |> rename(columns: {name: "_value"})
  |> keep(columns: ["_value"])
  ```

**Comment by russorat** [comment]
This PR adds a limit option to the CLI for this. https://github.com/influxdata/influxdb/pull/20847

it should be improved to add offset and limits to all list commands in the CLI.

**Comment by russorat** [comment]
@jsimomaa i don't see how this issue would impact the flux query you provided. are you trying to say the bucket exists but the flux query is failing?

**Comment by kristinarobinson** [comment]
Can't fix until pagination is in place. Resource pagination is limited to 100 on the back-end.
