### ISSUE TITLE
Config file is missing on Influx DB v2 (/etc/influxdb/influxdb.conf )

### ISSUE THREAD

**Issue by breadum** [influxdata/influxdb#20044]
Hello,

I am using Influx DB v2 and CentOS 7.6.

I was trying to run daemon on system boot, but couldn't find any default config file, 

/etc/influxdb/influxdb.conf, which seemed to exist on v1.x.

The problem is that there are several flags or environment variables I want to set,

but things get messy without system-wide config file.

When system starts services on boot, the environment variables are not available except a few, such as PATH.

Automatically sourcing environment variable for configuration such as INFLUXD_ENGINE_PATH when it starts is needed.

Is this intentional behavior that user  manually runs whenever system boots or

is there a proper way that I missed?

I tried to write some environment variables on /etc/default/influxdb and/or /etc/default/influxd,

but it seems like didn't work.

Thank you.

**Comment by cmackenzie1** [comment]
Hi @breadum , take a look at https://docs.influxdata.com/influxdb/v2.0/reference/config-options/

It looks like the config was changed to any of `config.[toml|yaml|json]`. The environment variable version is also listed on this page.

**Comment by breadum** [comment]
> Hi @breadum , take a look at https://docs.influxdata.com/influxdb/v2.0/reference/config-options/
> 
> It looks like the config was changed to any of `config.[toml|yaml|json]`. The environment variable version is also listed on this page.

Thank you for the response and apologies for the poor question.

What I asked was "How can I set configurations for the service which is to be run by user 'influxdb'?".

As far as I understood, personal configuration file can be set by what you suggested 

but system-wide configuration could be set in other ways. 

What I did was modifying service script.

> vi /etc/systemd/system/influxd.service

...
[Service]
...
ExecStart=/usr/bin/influxd \   # change this command with flags
  --engine-path ~~ \
  # other options...
...

It seems to work well without just a thing. 

I couldn't create new user, which I don't know whether this problem is related to the config I set.

> influx user create -n user_name -p password -o org_name
Error: Unauthorized access.

I tried this with my tokens set, but I couldn't figure out why.

Thank you.

**Comment by gurzelai** [comment]
> Hi @breadum , take a look at https://docs.influxdata.com/influxdb/v2.0/reference/config-options/
> 
> It looks like the config was changed to any of `config.[toml|yaml|json]`. The environment variable version is also listed on this page.

Hi, I have installed version 2 of Influxdb. I can't find any configuration file anywhere.
Do I have to create it manually? Where can I find an sample?
