### ISSUE TITLE
InfluxDB 2.0.1 OSS, config.* file is not loading during service start

### ISSUE THREAD

**Issue by akalikin1** [influxdata/influxdb#20050]
Installed fresh InfluxDB 2.0.1 under Debian 10
Created config file in working directory, but influx don't load it during start

* checked **working dir** by typing: **pwd** command
* tried different syntaxes **yml, toml, json**
* running influxd with flags works ok

__Environment info:__
Linux 5.4.65-1-pve x86_64
InfluxDB 2.0.1 (git: 37cc047133) build_date: 2020-11-11T03:53:31Z

**Comment by psteinbachs** [comment]
@gshif Please repro.

**Comment by gshif** [comment]
Hi @akalikin1,
Would you please provide the following info:
- Attach or provide the contents of the config file you used
- command you used to run `influxd`

Thank You

**Comment by gshif** [comment]
I have tried a `config.toml` with two flags:
- bolt-path = "/home/admin/.db2/influxd.bolt"
- engine-path = "/home/admin/.db2/engine"

After starting `influxd` process, I was able to see that the values from `config.toml` files were used:
```
2020-11-16T18:12:15.012893Z	info	Welcome to InfluxDB	{"log_id": "0QWZy890000", "version": "2.0.1", "commit": "37cc047133", "build_date": "2020-11-11T03:53:31Z"}
2020-11-16T18:12:15.018271Z	info	Resources opened	{"log_id": "0QWZy890000", "service": "bolt", "path": "/home/admin/.db2/influxd.bolt"}
```

**Comment by akalikin1** [comment]
> Hi @akalikin1,
> Would you please provide the following info:
> 
> * Attach or provide the contents of the config file you used
> * command you used to run `influxd`
> 
> Thank You

Hi @gshif , just tested once more after clean install under root user, everything is working OK!

Seems it was my fault, because I created user for systemctl service running, but do it with `useradd -rs /bin/false influxdb` command, in this case, as I understand now no home folder actually created for user, that was the mistake.
