### ISSUE TITLE
InfluxDB 2.0.1 OSS; duplicated error message

### ISSUE THREAD

**Issue by tara-influxdata** [influxdata/influxdb#20055]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a threshold alert
2. Change bucket name
3. Go back to alerts page
4. Hover over red triangle with ! on it

__Expected behavior:__
I hover over the red triangle and the error message is rendered once, not twice.

__Actual behavior:__
```
Last Run Status: Error exhausting result iterator; Err: failed to initialize execute state: could not find bucket "test": failed to initialize execute state: could not find bucket “test"
```

__Environment info:__

* System info: Darwin 18.7.0 x86_64
* InfluxDB version: InfluxDB 2.0.1 (git: 37cc047133) build_date: 2020-11-11T03:53:31Z

**Comment by danxmoran** [comment]
Reproduced on `master` (post-2.0.3)

**Comment by danxmoran** [comment]
Looks like it's not a UI issue, the duplicate message is included in the `lastRunError` field returned by the API
