### ISSUE TITLE
[v2.0] Telegraf config is created without inputs

### ISSUE THREAD

**Issue by ivanflux** [influxdata/influxdb#20062]
Steps to reproduce:
1. Install InfluxDB OSS 2.0.1 in Kubernetes https://docs.influxdata.com/influxdb/v2.0/get-started/#use-telegraf
2. Install Telegraf 1.16.1
3. Create Telegraf API Token
4. Run 

```
telegraf --config http://localhost:8086/api/v2/telegrafs/06a0d92b21a0e000

2020-11-17T01:31:48Z I! Starting Telegraf 1.16.1
2020-11-17T01:31:48Z E! [telegraf] Error running agent: Error: no inputs found, did you provide a valid config file?
```

Expected behavior:
Telegraf should work

__Actual behavior:
Error: no inputs found

Environment info:

System info: Darwin 19.6.0 x86_64
InfluxDB version: Influx CLI 2.0.1 (git: 37cc047133) build_date: 2020-11-11T03:53:31Z

Config:

[test.txt](https://github.com/influxdata/influxdb/files/5550725/test.txt)

<img width="690" alt="Screen Shot 2020-11-16 at 8 37 05 PM" src="https://user-images.githubusercontent.com/62263616/99329459-48dcfd80-284c-11eb-9169-92f75b6e55d5.png">

**Comment by danxmoran** [comment]
Hi @ivanflux I'm not able to reproduce using OSS 2.0.2 and Telegraf 1.16.2. Do you still hit the issue if you try with those versions?

**Comment by ivanflux** [comment]
@DanielMorsing OSS  2.0.2 and Telegraf 1.16.2 doesn't have this issue.
