### ISSUE TITLE
ID-related errors in v1 auth commands are confusing

### ISSUE THREAD

**Issue by yangvipguang** [influxdata/influxdb#20084]
Version: 2.0.1
Deployement: Helm Install
I am so confused.
I have configured admin user with random password。And, I can login the  ui with admin user, But it does't work in the telegraf agent .
![image](https://user-images.githubusercontent.com/11416887/99470798-52678200-2980-11eb-8c35-0226e1f35d87.png)

**Comment by yangvipguang** [comment]
and  I set up a different password with flux command 。But the result is same
![image](https://user-images.githubusercontent.com/11416887/99476841-4a154400-298c-11eb-843b-93e89a6916ad.png)

**Comment by su600** [comment]
用InfluxDB生成的Token连接试试

**Comment by danxmoran** [comment]
Hi @yangvipguang, apologies for the confusion, we have an open issue to clarify our docs around V1 auth. You'll need to create a V1 compatibility token to use with the V1 `influxdb` telegraf output. The command you want is `influx v1 auth create`, you can see reference docs [here](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/v1/auth/create/).

**Comment by yangvipguang** [comment]
@danxmoran  But  I do't know what‘s wrong with this
![image](https://user-images.githubusercontent.com/11416887/100339705-2ea5db00-3015-11eb-855e-662088e8700f.png)

**Comment by danxmoran** [comment]
@yangvipguang the `read-bucket` and `write-bucket` args should also be IDs, not names. `influx bucket list` will show you the ID for your `monitoring` bucket.

I have an open task to improve our validation errors so it's clear which arg is the problem, I'll add this case to the list.

**Comment by danxmoran** [comment]
@yangvipguang I've updated the title of this issue to reflect the problem with the latest error message you posted

**Comment by yangvipguang** [comment]
@danxmoran  thanks it works。 But，the error message is indeed confusing for anyone not familiar with influxdb。one more question ： 
Is the bucket the same as the database?

**Comment by yangvipguang** [comment]
@danxmoran  But  I have a new qustion:
![image](https://user-images.githubusercontent.com/11416887/100691888-a03eaa00-33c4-11eb-909f-c9c14f4cf890.png)

**Comment by danxmoran** [comment]
You're receiving 404 responses from the server (not a connection refused error), so I think the k8s networking is set up properly. Have you created a DBRP mapping for your target bucket? If not, you'll need to:
1. Use `influx v1 dbrp create` to init a new DBRP mapping, pointing at your target bucket
2. Configure telegraf to use the DB/RP pair you used in step 1

**Comment by danxmoran** [comment]
I've merged a change that will (hopefully) make the error messages easier to understand in the future.

@yangvipguang I'm happy to keep helping, but for our tracking purposes I'm going to close this issue. For general questions, you can use one/both of:
* Our community [Slack space](https://influxdata.com/slack)
* Our community [forum](https://community.influxdata.com/)

Feel free to open more issues for specific bugs / feature requests as they come up.
