### ISSUE TITLE
DBRP server implementation does not match swagger specification

### ISSUE THREAD

**Issue by GeorgeMac** [influxdata/influxdb#20087]
See: https://docs.influxdata.com/influxdb/v2.0/api/#operation/PostDBRP

https://github.com/influxdata/influxdb/blob/d93560fdc85f21d8a4720a7882698f38c5be28b2/dbrp/http_server_dbrp.go#L58-L65

The API docs states:
- `org` 
- `orgID`
- `bucketID`

But we shorten organization to org, and we use camel-case in the docs / API spec.
Since the docs are the shared source of truth, we should update the implementation.

**Comment by danxmoran** [comment]
@GeorgeMac I've seen a few people in the community Slack posting `curl` examples for using this API, I'm wary about changing the implementation and breaking them. It looks like IDPE is in the same situation (swagger [here](https://github.com/influxdata/idpe/blob/3b282e3e8d4ea1868efd359d5721272398fa3fe5/influxdbv2/http/swagger.yml#L11707-L11712), and struct [here](https://github.com/influxdata/idpe/blob/3b282e3e8d4ea1868efd359d5721272398fa3fe5/influxdbv2/dbrp/http_server_dbrp.go#L60-L67)). If Swagger is just used for documentation (no codegen), I'd feel better about fixing it to match the current behavior.

**Comment by danxmoran** [comment]
Some more data points / bugs:
* The generated API docs show both `org` and `orgID` as both required, when (I believe) it's really one-or-the-other. Code [here](https://github.com/influxdata/influxdb/blob/master/dbrp/http_server_dbrp.go#L79-L92).
* The `DBRP` model definition in the API spec is reused for the `list` endpoint. The model used by the implementation of that endpoint matches the implementation of the `create` endpoint, so the mismatch occurs there as well:
https://github.com/influxdata/influxdb/blob/d93560fdc85f21d8a4720a7882698f38c5be28b2/dbrp_mapping.go#L28-L38
