### ISSUE TITLE
kv Index.Walk function matches the foreign key by prefix only

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#20096]
## What

When the kv store searches the index, it utilises a forward cursor matching by prefix:

https://github.com/influxdata/influxdb/blob/15b95312736f1ea651d2e14ba8343e483d5cd92a/kv/index.go#L192-L193

The cursor will return all keys that have a matching prefix, in the following loop, including those keys which are longer:

https://github.com/influxdata/influxdb/blob/15b95312736f1ea651d2e14ba8343e483d5cd92a/kv/index.go#L206-L208

For example, if the `foreignKey` is `hello` and the index contains the keys `hello`, `hello-world` and `hello-there`, the loop will gather them all.

In most cases, the index is typically the result of combining 16-byte IDs, so this is not a problem. However, for `dbrp`, it creates an additional `orgID` + `database` foreign key:

https://github.com/influxdata/influxdb/blob/b274e15eacb2cf6c8915a9f75caf63d69fb2aac1/dbrp/service.go#L70-L76

### Creation of DBRPs fail:

1. Create `bucket1`
2. Create a dbrp mapping for `bucket1` with db `jenkins-aws`, rp `never`:

    ```sh
    curl -H 'Content-type: application/json' --header "Authorization: Token $INFLUX_TOKEN" -XPOST "$INFLUX_HOST/api/v2/dbrps" --data-binary '{"bucket_id": "<BUCKET1_ID>","database": "jenkins-aws","default": true, "organization_id": "<org-id>", "retention_policy": "never"}'
    ```

3. Create `bucket2`
4. Attempt to create a dbrp mapping for `bucket2` with db `jenkins`, rp `never`:

    ```sh
    curl -H 'Content-type: application/json' --header "Authorization: Token $INFLUX_TOKEN" -XPOST "$INFLUX_HOST/api/v2/dbrps" --data-binary '{"bucket_id": "<BUCKET2_ID>","database": "jenkins","default": true, "organization_id": "<org-id>", "retention_policy": "never"}'
    ```

    Fails with the following error:

    ```
    another DBRP mapping with same orgID, db, and rp exists
    ```

**Comment by GeorgeMac** [comment]
Hey @stuartcarnie 👋 

Sorry, definitely a gap in the documentation here. This index is currently a non-unique many to one secondary index.

```
resource >- association
dashboard >- org
```

And so the index is structured like so:

```
indexprefix/foreign_key/primary_key -> primary_key

bucketsbyorgv1/org_foo/bucket_one -> bucket_one
bucketsbyorgv1/org_foo/bucket_two -> bucket_two
bucketsbyorgv1/org_foo/bucket_three -> bucket_three
bucketsbyorgv1/org_foo/bucket_four -> bucket_four
```

Such that we can have multiple entries per foreign key. Meaning we could retrieve the many resources for a particular foreign key in a single range / cursor with a prefix lookup.

As this was originally designed around creating a URM by User index.

The Walk function visits each key / value pair in the `source` bucket. Not the `index` bucket. You are effectively walking the `source`, based on entries in the `index`:
https://github.com/influxdata/influxdb/blob/15b95312736f1ea651d2e14ba8343e483d5cd92a/kv/index.go#L218-L229

I have thought about adding support for a secondary index with a uniqueness constraint. In that scenario walk should find one item. Or perhaps a better name might be `Find` or similar. Infact it could just be another type which also consumes the `IndexMapping` type. The mapping type describe a source and index bucket name and a function for retrieving the associated index foreign key, for sure when backfilling and unpopulated index.

**Comment by stuartcarnie** [comment]
@GeorgeMac thanks for the reply! I do understand the many to one feature. There is a bug or unexpected behaviour, as described in the issue, that because it matches the foresight key using a _prefix_ match, it will find any keys with that prefix. 

So, back to the dbrp example, if a user adds a mapping to a database named jenkins-aws, the indexes foreign key would be <OrgID>Jenkins-aws. The next trying to add a mapping to a database named jenkins fails as the lookup (a prefix match) for jenkins finds <OrgID>jenkins-aws. 

It seems it is expected behaviour as a number of other tests fail when I fix that issue. It seems we might need a WalkExact API to match the foreign key exactly.

**Comment by GeorgeMac** [comment]
ooooooh I seee 😂 now I am with you. Took me long enough. I added a comment to your draft PR.
