### ISSUE TITLE
performance test suite 

### ISSUE THREAD

**Issue by duanshuaimin** [influxdata/influxdb#20114]
if exists  test suite toolset to loadtest influxdb 2.0

**Comment by danxmoran** [comment]
Hi @duanshuaimin, I'm not sure what you're asking here, could you clarify?

**Comment by duanshuaimin** [comment]
what I mean is to find a load test tool ,for example jmeter etc

**Comment by danxmoran** [comment]
The [influx-stress](https://github.com/influxdata/influx-stress) project could be what you're looking for, I'd recommend trying it and opening issues on its repo if you hit any problems. You could also ask in the [community forum](https://community.influxdata.com/), in case a 3rd party has created their own tool.

**Comment by danxmoran** [comment]
There is also [inch](https://github.com/influxdata/inch/)
