### ISSUE TITLE
Improvements to variable drop down lists

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/influxdb#20113]
@cmd-influx commented on [Thu Mar 26 2020](https://github.com/influxdata/chronograf/issues/5432)

I am using the tag shard_id as a variable in v2.0.  Shard Id for most buckets is 20-30 items but depending on the data set it is also likely it is 1000 to 2000 integers in the list.  Continuous Query names are another example of a variable and these lists can be 50 to 200 names long.

The following features would help me use the variable drop-down lists better:

Allow a setting for the variable drop down such that I could type the number or name.  This setting could validate the input based on the list but avoid me scrolling through long lists.  It could also auto scroll as I type.

Allow the variable to display a tooltip when the number or name is too large for the variable field dropdown.  Currently, drop-down fields are limited to about the 10 leftmost characters.   By the way, you have the same problem in "v.bucket" which I heavily use.

---

@timhallinflux commented on [Thu Nov 19 2020](https://github.com/influxdata/chronograf/issues/5432#issuecomment-730820688)

This is an 2.0 UI specific request.  Ability to type into template variable fields....to filter the list.  This was the behavior in Chronograf 1.x.  Seems to have been lost in the move to Clockface?

**Comment by kristinarobinson** [comment]
Fixed.
