### ISSUE TITLE
[2.0.x] Users migrated from 1.8.3 are not manageable in the UI or CLI

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/influxdb#20133]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Perform 1.8 > 2.0 upgrade
2. influx user list or in the UI will have no users except the admin created during the process

__Expected behavior:__

Being able to manage users and ideally to move them from password based to token based or at minium being able to delete them once migration to a V2 token configuration for users.

__Actual behavior:__

Users are migrated but we can't manage them from CLI or UI.

__Environment info:__

* InfluxDB version: 2.0.2

**Comment by danxmoran** [comment]
Hi @nsteinmetz, V1 users get migrated to a separate space from V2 users. In the CLI you should be able to manage v1 users via commands under `influx v1 auth -h`. Can you let me know if there are specific capabilities you'd expect to see there that are missing?

**Comment by nsteinmetz** [comment]
@danxmoran thanks !! - I didn't think it was in the `v1` subcommands. Seems I have all I need to finalize my migration.

Maybe it should be added somewhere in the [upgrade docs](https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/) ?
