### ISSUE TITLE
[2.0.x] Debian package does not read /etc/influxdb/config.toml file

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/influxdb#20132]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Install InfluxDB 2.x OSS
2. Provide /etc/influxdb/config.toml file
3. Starts it with service

__Expected behavior:__

`/etc/influxdb/config.toml` file should be read as default config file.

__Actual behavior:__

file ignored and influx will start in `/var/lib/influxdb/.influxdbv2`

__Fix suggestion__

As systemd service file contains:

```
EnvironmentFile=-/etc/default/influxdb
``` 

We could have for `/etc/default/influxdb` instead of empty file:

``` 
INFLUXD_CONFIG_PATH=/etc/influxdb/config.toml
```

**Comment by danxmoran** [comment]
This should be fixed in the 2.0.3 release for systemd installations (please let me know if you see otherwise). We found a parallel problem in the package's init.d script that will be fixed in 2.0.4.
