### ISSUE TITLE
[2.0.x] Debian package still contains /etc/influxdb/influxdb.conf

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/influxdb#20131]
__Steps to reproduce:__

```
dpkg -l influxdb
ii  influxdb       2.0.2        amd64        Distributed time-series database.
```

```
dpkg -L influxdb
/usr
/usr/bin
/usr/bin/influx
/usr/bin/influxd
/usr/lib
/usr/lib/influxdb
/usr/lib/influxdb/scripts
/usr/lib/influxdb/scripts/influxdb.service
/usr/lib/influxdb/scripts/init.sh
/etc
/etc/logrotate.d
/etc/logrotate.d/influxdb
/etc/influxdb/influxdb.conf
```

__Expected behavior:__

InfluxDB 2.0 should not deploy influxdb 1.x configuration file.

__Actual behavior:__

InfluxDB 1.x configuration file is deployed : `/etc/influxdb/influxdb.conf`

It's confusing

There should be only a /etc/influxdb/config.toml file

**Comment by danxmoran** [comment]
This appears to be fixed in v2.0.3, using the `influxdb2` package.
