### ISSUE TITLE
Email invitations filtered out due to incorrect SPF record

### ISSUE THREAD

**Issue by deanasheehan** [influxdata/influxdb#20140]
On behalf of an existing user:

We have attempted to invite a number of people to our Influx Cloud account and the invites have not been received.
On investigation with our IT department we have discovered that the invitation email is being filtered out due to an invalid SPF record.

Please see the example below:

For example:
 Date   2020-11-12
 Time   10:19:54
 Message   SPF=FAIL: (header from: support@influxdata.com) indicates that MTA (209.61.151.245) is not permitted to send email for influxdata.com
 Session ID   0AC9JpeV002695-0AC9JpeX002695
 Log ID   0300002696
 From   bounce+cb3e99.0fa21-<REDACTED EMAIL ADDRESS>@mailgun.influxdata.com
 To   <REDACTED EMAIL ADDRESS>
 Subject   You're invited.

**Comment by danxmoran** [comment]
@deanasheehan I see a closed support request from the day this issue was opened, describing the same problem. Assuming the SRE fix covered both problems (or that they were the same problem, reported twice) I'm going to close this issue.
