### ISSUE TITLE
Migrate DBRPs from old KV schema to new on startup

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#20167]
EDIT: Updated to reflect new knowledge

In 2.0.2 we changed the implementation of our DBRP API to match the spec. As part of the change, we modified the JSON tags for a DBRP struct. This unknowingly resulted in a breaking change to `influxd`'s KV metadata store, which persists DBRP mappings as JSON. Any DBRP objects created pre-2.0.2 will fail to fully deserialize from JSON after an upgrade to 2.0.2, causing their bucket and organization IDs to be zeroed out. This currently causes panics on the V1 write path, and even with a fix for the panic we see the DBRPs are inaccessible when cut off from their org / bucket.

A [work-around](https://github.com/influxdata/influxdb/issues/20121#issuecomment-731403423) exists to repair the mappings from the outside using the API, but it's fairly complex. We should use a KV migration to automatically rewrite any DBRP mappings using the old schema on startup.

**Comment by stuartcarnie** [comment]
@danxmoran we should be able to validate and fix these with a DB migration. We have infrastructure to handle this very case:

1. Create a new migration using the `kvmigrate` internal command:

    ```sh
    go run internal/cmd/kvmigrate/main.go create <name of migration>
    ```

    This will generate an empty Go migration file in the `kv/migration/all` folder

2. Implement an `UpOnlyMigration` such as:

https://github.com/influxdata/influxdb/blob/8ca2989717bb3db9e0bfcafe4e2d1e367826f285/kv/migration/all/0011_populate-dashboards-owner-id.go#L13
