### ISSUE TITLE
Docker doesn't have 2.0 latest image

### ISSUE THREAD

**Issue by tagyoureit** [influxdata/influxdb#20178]
__Steps to reproduce:__

I'm trying to setup Influx 2.0 on my Synology NAS.  However, Synology pulls from https://registry.hub.docker.com/_/influxdb/ which only has the 1.8 version.  

__Expected behavior:__
Be able to pull 2.0 into Synology.

__Actual behavior:__
Can't.  :)

__Environment info:__

Synology NAS.

**Comment by justinturpin** [comment]
They seem to use Quay now, per the docs here: https://docs.influxdata.com/influxdb/v2.0/get-started/ however the docs point to `influxdb:2.0.0-rc` and the tags `2` or `2.0.2` do not exist.

**Comment by danxmoran** [comment]
The images on Quay started to have a `v` prefix in their versions starting with RC4 (honestly not sure why), so the full 2.0.2 image is: `quay.io/influxdb/influxdb:v2.0.2`

**Comment by LukasA83** [comment]
But there are no arm64 images on quay, is there any reason?

**Comment by su600** [comment]
Where can we get **arm64** docker images? v2.0

**Comment by tagyoureit** [comment]
I was able to successfully connect to Quay on my Synology NAS with the help of Synology support.  I'll post the resolution here and close this issue.  I suggest others open a new case for other Docker related image questions.

> Hello,
I understand you cannot access the Quay docker registry.
I did some testing and it appears you need to register for an account on Quay.io, and then enter the username and password for your Quay account into the registry settings--you may also need to configure a password for docker login in your Quay account settings, as well. Once that was done I was able to successfully pull images from Quay:

![unnamed](https://user-images.githubusercontent.com/1646840/101123737-5b746800-35aa-11eb-8906-923aaaf8cd85.png)

My issue, sure enough, was needing an account on Quay.  Thanks Synology!
