### ISSUE TITLE
[2.0]  failed to initialize execute state: failed to look up bucket

### ISSUE THREAD

**Issue by ivanflux** [influxdata/influxdb#20184]
Steps to reproduce:

1. follow https://docs.influxdata.com/influxdb/v2.0/reference/sample-data/#noaa-water-sample-data

Expected behavior:
Data loaded into the bucket

Actual behavior:
"failed to initialize execute state: failed to look up bucket "noaa" in org "INFLUX""

Environment info:
InfluxDB version: Influx CLI 2.0.1 (git: 37cc047133) build_date: 2020-11-11T03:53:31Z

influx org list
ID			Name
59bb84e7fe155935	INFLUX

influx bucket ls
ID			Name		Retention	Organization ID
0d91cf3ebfa957cf	nooa		0s		59bb84e7fe155935

![Screen Shot 2020-11-26 at 2 13 22 AM](https://user-images.githubusercontent.com/62263616/100319093-19856980-2f8d-11eb-9fd4-6d72ed151f7f.png)

**Comment by timhallinflux** [comment]
is this a typo?  bucket name for ID `0d91cf3ebfa957cf` in list above the image is `nooa`....and it should be noaa. ??

**Comment by ivanflux** [comment]
I'll double-check.

**Comment by ivanflux** [comment]
yes, it was a typo.
