### ISSUE TITLE
Kinesis integration with InfluxDB 2.0 not working

### ISSUE THREAD

**Issue by ravi7248** [influxdata/influxdb#20187]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ... Installed InfluxDB 2.0 docker Image
2. ... Installed Telegraf docker image
3. ... Configured the telegraf.conf file

__Expected behavior:__
It should be no error and data should come to InfluxDB 2.0

__Actual behavior:__
No data is coming is in InfluxDB 2.0

__Environment info:__

* System info: Ubuntu 19.02 
* InfluxDB version: quay.io/influxdb/influxdb:2.0.0-rc
* Telegraf version: 1.15.2
__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
```
[[outputs.influxdb_v2]]
   ## urls exp: http://127.0.0.1:8086
   ##urls = ["http://influxdb:8086"]
   urls = ["http://14.206.177.28:8086"]
   token = "$INFLUX_TOKEN"
   organization = "org_name"
   bucket = "logs"
[[inputs.kinesis_consumer]]
   region = "provided"
    access_key ="provided"
    secret_key = "provided"
    profile = "arn:aws:iam::666268854852:instance-profile/ec2_to_aws_admin"
    streamname = "new_stream"
    shard_iterator_type = "TRIM_HORIZON"
   data_format = "csv"
  csv_header_row_count = 1
  csv_tag_columns = ["node","operatorName","type"]
  csv_timestamp_column = "datetime"
  csv_timestamp_format = "2006-01-02T15:04:05" 
[[outputs.file]]
files = ["/tmp/metrices.out"]
data_format = "influx"
```

__Logs:__
[agent] Error writing to outputs.influxdb_v2: Post "http://influxdb:8086/api/v2/write?bucket=bucket_name&org=org_name": dial tcp 172.20.0.3:8086: connect: connection refused

I tried inserting the data of internal metrics of InfluxDB using telegraf plugin, I am getting proper data in influxdb. I tried pushing data of the system using [[inputs.cpu]] and I am getting this data as well in Influxdb properly. 
To verify that my data is coming from kinesis or not, I tried pushing this data into the file, and Kinesis data is also coming in the file. 
I also put two inputs in telegraf.conf, one is  [[inputs.cpu]] and the second one is [[inputs.kinesis_consumer]], then I am getting data from the [[inputs.cpu]] but not from the [[inputs.kinesis]].

**Comment by duanshuaimin** [comment]
Take a consider of firewall open for 8086,token,orgname  parameter

**Comment by ravi7248** [comment]
I am getting data in influxdb except when I am using [[inputs.kinesis]], it means everything is working fine and the firewall is also open. The firewall will be the same whether the is [[inputs.cpu]], [[inputs.kinesis]] and influxdb internal metrics.
