### ISSUE TITLE
[2.0] Scrapping fails when Content-Type header is not set on endpoint, should default to text/plain

### ISSUE THREAD

**Issue by mgcrea** [influxdata/influxdb#20193]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Add a scrapper for a resource that does not properly reply with a `content-type` header:

eg.

```
http -h http://172.17.0.1:5054/metrics
HTTP/1.1 200 OK
content-length: 40138
date: Sun, 29 Nov 2020 19:45:14 GMT
server: Lighthouse/v1.0.2-f7183098e/x86_64-linux
```

1. Check logs and witness error:

```
ts=2020-11-29T19:47:10.200547Z lvl=error msg="Unable to gather" log_id=0QmNfc70000 error="mime: no media type"
```

__Expected behavior:__
Properly parse metrics and default to text/plain

__Actual behavior:__
Fails to scrape

__Environment info:__

docker v2.0.2

**Comment by russorat** [comment]
Looks like the issue is here: https://github.com/influxdata/influxdb/blob/master/gather/prometheus.go#L58

**Comment by L1Cafe** [comment]
Hi, this happens for https://github.com/MindFlavor/prometheus_wireguard_exporter as well. It appears the exporter doesn't declare a Content-Type.

I'm curious on why this is still open. Why is it required a Content-Type be specified?

**Comment by L1Cafe** [comment]
I provided a patch. Happy to receive any comments. Thanks!
