### ISSUE TITLE
Add ability to type variables into variable dropdowns in UI

### ISSUE THREAD

**Issue by samhld** [influxdata/influxdb#20195]
__Proposal:__
Title

__Current behavior:__
When a dashboard has variables, they are dropdown menus across the top of the dashboard.  These are useful for low cardinality variables but become more and more difficult to use the higher the cardinality of that variable.  If I know the variable value I want to inject (i.e., `usage_email` in the Org Drilldown dashboard/s), I have to scroll through sometimes 10,000+ values, which isn't viable.  I could also manually URL-encode that email value into the URL of the dashboard but that requires memorization and is generally clunky and error-prone.  

__Desired behavior:__
In cases where I know the variable I want to inject into each relevant dashboard cell, I should be able to type or copy/paste that value into the dropdown so I avoid endless scrolling and URL-encoding.

**Comment by jrenee42** [comment]
fixed in: https://github.com/influxdata/ui/pull/652
