### ISSUE TITLE
Group by time needs to be wrapped in the time function

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#2020]
Currently, this passes the parser:

```sql
SELECT field1, field2 ,field3 AS field_x FROM myseries WHERE host = 'hosta.influxdb.org' GROUP BY 10h ORDER BY ASC LIMIT 20 OFFSET 10
```

It should be:

```sql
SELECT field1, field2 ,field3 AS field_x FROM myseries WHERE host = 'hosta.influxdb.org' GROUP BY time(10h) ORDER BY ASC LIMIT 20 OFFSET 10
```

**Comment by pauldix** [comment]
@corylanou the tricky part is that `10h` is a valid tag name, thus it's actually a valid query even though the user most likely meant to group by the time interval.

I'm a fan of supporting `group by time(10h)` or `group by 10h` and if the user happens to have a tag that starts with a number, then they will need to wrap the tag key in quotes.

**Comment by pauldix** [comment]
Actually, if it's a tag they should have to double quote it as an identifier. Otherwise we should assume it's a time.

**Comment by jsternberg** [comment]
It looks like this was fixed at some point so I'm going to close this:

```
> select mean(value) from cpu group by 1h
ERR: error parsing query: only time and tag dimensions allowed
```
