### ISSUE TITLE
Implement authorization with JWTs

### ISSUE THREAD

**Issue by glinton** [influxdata/influxdb#20223]
The annotationd service will need to authenticate outbound requests to gateway external write.
This is in order to write annotations to the target bucket.

See prior work: https://github.com/influxdata/idpe/blob/master/client/writer/writer.go#L75-L82

## Definition of Done

- We unblock https://github.com/influxdata/idpe/issues/9311 (ability to write annotations)

**Comment by GeorgeMac** [comment]
@glinton just a heads up I updated the description of this issue.
