### ISSUE TITLE
Remove APGL and Chronograf references from OSS 2.x

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/influxdb#20226]
This file currently contains stale references to the Chronograf name and original license used by Chronograf. 
This should be modified/changed. I believe this was simply an artifact of code handling that we should clean-up.

https://github.com/influxdata/influxdb/blob/master/ui/package.json

License is now: MIT
Name: InfluxDB UI
Repository: "url": "github:influxdata/ui"

https://github.com/influxdata/influxdb/blob/master/chronograf/README.md
This Readme should also be cleaned-up as well.

**Comment by danxmoran** [comment]
@timhallinflux looks like the UI repository has the [same problem](https://github.com/influxdata/ui/blob/master/package.json#L2-L9), should I update there as well?

**Comment by timhallinflux** [comment]
yessir. thanks
