### ISSUE TITLE
2.0 API missing X-version and X-Build Headers

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#20224]
Per previous guidance: influxdata/influxdb#6756

To aid with troubleshooting, the X-Influxdb-Version and X-Influxdb-Build header should be set on all responses, even for unhandled routes.

Proposal from @timhallinflux:
Build = "OSS" (as opposed to "Cloud")
Version = release version

**Comment by russorat** [comment]
this is a good idea IMO.

until then, we know the urls for our cloud clusters, so we could guess really well :)
