### ISSUE TITLE
Portable backup can fail with data corruption on high-latency networks [forward-port 1.x]

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#20231]
Forward-port the patch from #20115 to the `master-1.x` branch.

**Comment by lesam** [comment]
this went to:

master-1.x: #21978
1.9: #21993
1.8: #21991

**Comment by lesam** [comment]
`git grep 'io.Read[^A-Za-z]'` shows no similar usages in 2.x

**Comment by lesam** [comment]
Closing, this is ported everywhere
