### ISSUE TITLE
There are hidden users in our influxdb 2 server

### ISSUE THREAD

**Issue by wiebeytec** [influxdata/influxdb#20264]
After migrating from Influxdb 1 to 2, there are hidden users. 

This authorizes:

```
curl "http://influx.example.nl:8086/query?db=telegraf&u=nagios3&p=$PASSWORD&q=SELECT+%2A+FROM+bla+ORDER+BY+DESC+LIMIT+1&epoch=s"
{"results":[{"statement_id":0,"error":"database not found: telegraf"}]}
```

But when I change the user or password:

```
curl "http://influx.example.nl:8086/query?db=telegraf&u=nagios3&p=${PASSWORD}suffix&q=SELECT+%2A+FROM+bla+ORDER+BY+DESC+LIMIT+1&epoch=s"
{"code":"unauthorized","message":"Unauthorized"}
```

```
curl "http://influx.example.nl:8086/query?db=telegraf&u=nagios3z&p=$PASSWORD&q=SELECT+%2A+FROM+bla+ORDER+BY+DESC+LIMIT+1&epoch=s"
{"code":"unauthorized","message":"Unauthorized"}
```

But I can't find the 'nagios3` user:

```
influx user list|grep -Fi nagios || echo "nothing"
nothing
```

```
influx auth list|grep -Fi nagios || echo "nothing"
nothing
```

Also can't find it with v1:

```
influx v1 auth list
Error: Authorization not found.
See 'influx v1 auth list -h' for help
```

__Expected behavior:__

Be able to manage all authorizations.

__Actual behavior:__

You can authorize with hidden users.

__Environment info:__

* Linux 4.15.0-72-generic x86_64
* Ubuntu 18.04
* Installed from deb https://repos.influxdata.com/ubuntu bionic stable
* Influx version: Influx CLI 2.0.1 (git: 37cc047) build_date: 2020-11-11T03:53:31Z
* aptitude show influxdb: 2.0.1

__Logs:__

Only during `influx v1 auth list` I see something:

```
dec 07 14:29:07 spire influxd[9525]: ts=2020-12-07T13:29:07.177993Z lvl=error msg="api error encountered" log_id=0QwI7bB0000 error="authorization not found"
```

**Comment by danxmoran** [comment]
Hi @wiebeytec, thanks for the report. I'd expect the `nagios3` user to appear in the output of `influx v1 auth list`. Can you try a few things for me?
1. What's the output of `influx v1 auth list` on its own?
2. Does the problem reproduce if you use 2.0.2 instead of 2.0.1?

**Comment by wiebeytec** [comment]
I had posted the output of `influx v1 auth list`. But, the fault seems our own. We had `INFLUX_USERNAME` and `INFLUX_PASSWORD` in our Bash environment. We noticed because one team member uses Fish, not Bash.

Removing those env vars made everything work.
