### ISSUE TITLE
Ability to export line protocol data from OSS

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#20273]
__Proposal:__
Users need a way to export data from an OSS instance in line-protocol format.

__Current behavior:__
`influx backup` supports exporting all data in the DB, but not in line-protocol

__Desired behavior:__
The 1.x line had a few options to handle this case:
* `influx backup` supported a `-portable` flag which caused data to be written a compressed format which could be `restored` to either Enterprise or OSS.
* `influx_inspect` included an `export` subcommand which would dump the raw LP based on the parameters supplied

Either or both of these options could work.

__Alternatives considered:__
Users have tried using query APIs / Flux to scrape all data out of their DBs into CSVs. This works ok for small datasets, but at scale it runs into problems with quotas and rate-limits.

__Use case:__
This will help with data migration from OSS to Cloud.

**Comment by timhallinflux** [comment]
CSV improvements to handle rate limits are either being worked or a pending a merge.

**Comment by danxmoran** [comment]
@timhallinflux in the short-term, would it be enough to restore the old `influx_inspect export` command as a new subcommand of `influxd inspect`? Or do we need an API extension & addition to the `influx` CLI?
