### ISSUE TITLE
Update swagger doc with new dictionary expressions

### ISSUE THREAD

**Issue by jlapacik** [influxdata/influxdb#20299]
https://github.com/influxdata/flux/pull/3387 adds dictionary literals to the flux language. We will need to update the swagger doc with this new AST node.

**Comment by nathanielc** [comment]
See https://github.com/influxdata/flux/pull/3387/files#diff-9dcefbf65d58a909b6cc7332b7985d070382bf920a4b13c7acea4ee91ecdf5acR1271 and https://github.com/influxdata/flux/pull/3387/files#diff-9dcefbf65d58a909b6cc7332b7985d070382bf920a4b13c7acea4ee91ecdf5acR1300
