### ISSUE TITLE
Is there a headless influxdb2 option?

### ISSUE THREAD

**Issue by doivosevic** [influxdata/influxdb#20304]
After some googling I didn't manage to find this so I'm asking here. We are writing some unit tests which are integrating through influxdb in our stack and the tests are running relatively slowly (I know it's subjective). Is there an option to use influxdb2 as a library to run it when the test[s] start, input that relatively low amount of data, run 2-3 queries and shut it down? This would also be great in out CI later

**Comment by danxmoran** [comment]
Hi @Kungitoo, we don't offer an "official" solution for this use-case, but if your testing infrastructure is using / could use Go you can roll your own setup by adding `github.com/influxdata/influxdb/v2` as a dependency in your `go.mod`. You could then spin up an instance of `influxd` (or a sub-component) programmatically. The `_test.go` files in [this directory](https://github.com/influxdata/influxdb/tree/master/cmd/influxd/launcher) show how we do it for our own integration testing.

**Comment by timhallinflux** [comment]
https://docs.influxdata.com/influxdb/v2.1/reference/config-options/#ui-disabled
