### ISSUE TITLE
500 error on writing data out of policy range

### ISSUE THREAD

**Issue by ssoroka** [influxdata/influxdb#20359]
Writing data outside of policy range should result in a 4xx error that the client can understand not to retry sending the data. It's expected behavior that 5xx errors received by clients should result in the client re-transmitting the same data to avoid data loss.

This issue was raised by a customer here https://github.com/influxdata/telegraf/issues/8571

__Steps to reproduce:__

I've configured a bucket with a retention policy of 2 weeks. When I write some measurements that are older than those two weeks, influxdb response with an 500 error. 

1. setup influxdb v2 
2. create bucket with a retention policy of N weeks
3. send some data to this bucket that is older than N weeks. E.g. via curl.

__Expected behavior:__

server responds with an error indicating client error, eg 4xx. such as. `406 Not Acceptable`  or `422 Unprocessable Entity`

__Actual behavior:__

Server responds with 500 Internal Server Error

__Environment info:__

* InfluxDB version: 2.x

__Logs:__
see logs from https://github.com/influxdata/telegraf/issues/8571

**Comment by psteinbachs** [comment]
Added @danxmoran for tracking what we'll need to add for OSS.

**Comment by StacieClark** [comment]
this is the set of default errors allowed by the swagger definition `enum:
            - internal error
            - not found
            - conflict
            - invalid
            - unprocessable entity
            - empty value
            - unavailable
            - forbidden
            - too many requests
            - unauthorized
            - method not allowed`
    422: Unprocessable Entity should be used rather that 406: unacceptable, as unacceptable is not on our list

**Comment by ssoroka** [comment]
@StacieClark do we have any timeline for this?

**Comment by StacieClark** [comment]
I'm looking at it today. I'll let you know when I know what the fix is

**Comment by StacieClark** [comment]
I configured a bucket to have a 1 hr retention policy.

`curl -i -XPOST 'http://localhost:8080/api/v2/write?org=dev&bucket=1hr&precision=s' --header "Authorization: Token $INFLUX_TOKEN" --data-raw "note mod=13 1234567" 

HTTP/1.1 204 No Content
Date: Tue, 22 Dec 2020 15:31:45 GMT
Server: Caddy
`
The content does not get inserted. No timestamp or a timestamp within the hour do get inserted.

So this is incorrect as well.

**Comment by StacieClark** [comment]
Looks like an OSS isse

**Comment by ssoroka** [comment]
why are you getting `Server: Caddy` in the response? seems like you're not getting a response from the right server.

**Comment by StacieClark** [comment]
That is local cluster. From an AWS cluster:

curl -i -XPOST 'https://us-east-1-1.aws.cloud2.influxdata.com/api/v2/write?org=sclark@influxdata.com&bucket=dev&precision=s' --header "Authorization: Token $INFLUX_TOKEN" --data-raw "note mod=15 12345"

HTTP/2 204 
date: Mon, 04 Jan 2021 19:29:57 GMT
strict-transport-security: max-age=15724800; includeSubDomains

**Comment by StacieClark** [comment]
Is this an OSS issue and not cloud?

**Comment by danxmoran** [comment]
I can confirm this is a problem on OSS `master`, I can prioritize working on a fix for the upcoming 2.0.4 release. I'm unclear about the desired behavior change, though: do we want OSS to match cloud and return a 204, or do its own thing and return some 4xx code? My main concern about returning a 4xx is that users might think all of their data was rejected, but in reality any of the points that fell inside the RP will have been accepted & stored.

**Comment by psteinbachs** [comment]
@danxmoran In general, we should always be staying in sync with cloud.  We can have a deeper discussion if there are aspects that aren't applicable to one or the other.
