### ISSUE TITLE
Influx CLI 2.03 not work ,because org or username password

### ISSUE THREAD

**Issue by twkk** [influxdata/influxdb#20420]
__Expected behavior:__
no error and import data to buckets.

__Actual behavior:__
$ influx write -b test4 -f MyGeneration_Data.csv

Error: Must specify org-id, or org name.

$ influx write -b test4 -f MyGeneration_Data.csv org “my-org”

Error: accepts at most 1 arg(s), received 2

export INFLUX_TOKEN=myauthtoken
same result ..

__Environment info:__

*  OS centos 8
*  Software influxdb Version 2.03
*  Influx CLI 2.0.3 (git: fe04d346df) build_date: 2020-12-15T01:00:16Z
   remove influxdb 1.8.3-1 
   then install influxdb Version 2.03
* And there is no " $HOME/.influxdbv2" only get data in /root/.influxdbv2
there is no file  $HOME/.influxdbv2/credentials
there is no file  /root/.influxdbv2/credentials

**Comment by danxmoran** [comment]
You're missing the `--` prefix to your org flag, so the CLI parser is viewing it as a bare arg. This should work:
```
influx write -b test4 -f MyGeneration_Data.csv --org “my-org”
```
