### ISSUE TITLE
InfluxDB v2.0.3 Linux x86_64 build missing from downloads

### ISSUE THREAD

**Issue by ryo0ka** [influxdata/influxdb#20437]
__Steps to reproduce:__

1. Go to https://portal.influxdata.com/downloads/
2. See `Linux Binaries (64-bit)` and `Linux Binaries (ARM 64-bit)` point to the same link (of ARM)

__Expected behavior:__
Expecting a link to a build for Linux x86_64

__Actual behavior:__
Both (x86 and ARM) point to the ARM build's download link

**Comment by danxmoran** [comment]
@ryo0ka I see separate links on the downloads page:
1. x86_64 points to https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.3_linux_amd64.tar.gz
2. ARM64 points to https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.3_linux_arm64.tar.gz

**Comment by ryo0ka** [comment]
@danxmoran Oh you're right. Thanks for your support haha...
