### ISSUE TITLE
Influxdb2: armhf build for armv6 chips: early Raspberry Pis and Pi zeros

### ISSUE THREAD

**Issue by philjb** [influxdata/influxdb#20431]
__Proposal:__

Please provide a build of Influxdb2 for `armhf` `armv6` targets such are early RPis (A, B) and Pi Zero.

__Current behavior:__

There is no build available for this architecture requiring the user to build from source.

__Desired behavior:__

https://repos.influxdata.com/debian/dists/buster/stable/binary-armhf/Packages provides packagers for Debian/Raspbian. Others have labeled build for this target with a `-rpi` suffix since `armhf` isn't specific enough on it's own. Both `armv7` and `armv6` are `armhf`. 

For example: https://grafana.com/grafana/download?platform=arm

__Alternatives considered:__

Build Influxdb2 from source.

__Use case:__

RPI Zero's are lower power Pi's that are perfect for edge devices running the latest Influxdb version. This is also useful for individuals with older Pis.

**Comment by philjb** [comment]
related: https://github.com/influxdata/influxdb/pull/20260

**Comment by danxmoran** [comment]
Context for the final state of the linked PR, and for anyone thinking to build from source: I was able to produce static builds of `influx` / `influxd` for both arm32v6 and arm32v7, but both builds failed some of our acceptance tests w/ panics. The root errors looked like overflows from code that assumes a 64-bit architecture. I didn't dig in to see how extensive the assumptions are in the codebase.

**Comment by brevilo** [comment]
> This is also useful for individuals with older Pis

Erm, no, it's not just that. Even the latest RPi v4 sports 32-bit `armv7` using the standard Raspberry Pi OS (formerly known as Raspbian). So an `armhf` build should still be considered the norm for RPis, not just a nice-to-have edge case, IMHO...

Thanks!

**Comment by JSAnyone** [comment]
Is it really not possible to use Influxdb 2.0 in Docker with Raspberry Pi OS on RPi4?
That would be really disappointing!

**Comment by danxmoran** [comment]
Correct, the default install of Raspberry Pi OS isn't supported (because it runs 32-bit as @brevilo mentioned). The RPi4 hardware is 64-bit, so you can install either the 64-bit Raspberry Pi OS beta or another linux distro (i.e. Ubuntu) to get things working.

**Comment by danxmoran** [comment]
At InfluxDays EMEA we officially announced that InfluxDB v2 won't support 32-bit architectures (see the blog post with more context [here](https://www.influxdata.com/blog/influxdb-oss-and-enterprise-roadmap-update-from-influxdays-emea/)), so I'm going to close this issue as a "won't fix."
