### ISSUE TITLE
Password flag missing for 'influx v1 auth set-password' command

### ISSUE THREAD

**Issue by ved-pal** [influxdata/influxdb#20447]
In influxdb v2.0.2 , password setting for v1 authentication is missing the flag "--password" , althought in the official documentation this flag is there.

#-----
root@monitoring-influxdb-8fd4884f9-lcvzf:/# influx version
Influx CLI 2.0.2 (git: 84496e507a) build_date: 2020-11-19T03:59:35Z

root@monitoring-influxdb-8fd4884f9-lcvzf:/# influx v1 auth set-password -h
Set a password for an existing authorization

Usage:
  influx v1 auth set-password [flags]

Flags:
  -c, --active-config string   Config name to use for command; Maps to env var $INFLUX_ACTIVE_CONFIG
       --configs-path string    Path to the influx CLI configurations; Maps to env var $INFLUX_CONFIGS_PATH (default 
                                             "/root/.influxdbv2/configs")
  -h, --help                            Help for the set-password command
       --host string                  HTTP address of InfluxDB; Maps to env var $INFLUX_HOST
       --id ID                            The ID of the authorization; Maps to env var $INFLUX_ID
       --skip-verify                   Skip TLS certificate chain and host name verification.
  -t,  --token string                Authentication token; Maps to env var $INFLUX_TOKEN
      --username string           The username of the authorization; Maps to env var $INFLUX_USERNAME

#----------------

**Comment by danxmoran** [comment]
Hi @ved-pal, this is expected, `--password` was added as an option in v2.0.3

**Comment by ved-pal** [comment]
ok, then i think i should pull v2.0.3. Thanks for update !!
Closing this issue.
