### ISSUE TITLE
Enable query tracing

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#2044]
We should have a logging option for query-tracing. It should output detailed information at every level of the query, from the planning stage, to the execution. There should be info in the iterators in `tx.go` and info output in the execution in `engine.go`. Although I don't think it's needed or wise to put anything into the mappers or reducers.

**Comment by arobinsongit** [comment]
Paul, thanks for the new issue on this.  One suggestion I would make in the march to make this solution more production ready is to be able to flip these trace bits on and off at run time.  While I know we should be running as a cluster it seems this would be much more friendly that forcing a restart of a node after updating the configuration.  Unless you force a reread of the config every time you see it change.  I know some applications will do this but I don't know if Influx does it.

**Comment by pauldix** [comment]
Sure, that's something we want to do. Logged #2047 to track it.
