### ISSUE TITLE
Should be able to enable trace logging on a running process

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#2047]
A user should be able to invoke a command to enable each of the trace logging options in the config against a running process.

I guess this could be an HTTP endpoint. If auth is enabled then the user would need to be an admin to enable anything.

Maybe the better thing to do would be to have it be something that is done through the `influxd` CLI.

**Comment by corylanou** [comment]
All http endpoints support the REQUEST_ID tracer bullet, we just need to fire that through all the requests as well once we enable the logging.
