### ISSUE TITLE
Wrong Content-Type in v1 query API response

### ISSUE THREAD

**Issue by nyren** [influxdata/influxdb#20514]
__Steps to reproduce:__

1. Setup default DBRP for bucket
2. Run "SHOW MEASUREMENTS" query or any SELECT statement

For example:
```sh
curl -i --request POST 'http://localhost:8086/query?db=mybucket' --header 'Authorization: Token <token>' --header 'Accept: application/json' --data-urlencode 'q=SHOW MEASUREMENTS'
```
gives the following response from InfluxDB 2.0.3:
```
HTTP/1.1 200 OK
Date: Thu, 14 Jan 2021 09:51:36 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 120
Connection: keep-alive

{"results":[{"statement_id":0,"series":[{"name":"measurements","columns":["name"],"values":[["mymeasurement"]]}]}]}
```

__Expected behavior:__
The Content-Type header should indicate **application/json** encoding.

The same query towards InfluxDB 1.x correctly sets **application/json** content type.

__Actual behavior:__
The Content-Type header is **text/plain** while body is JSON.

__Environment info:__

* InfluxDB 2.0.3 (git: fe04d346df) build_date: 2020-12-15T01:00:16Z

**Comment by danxmoran** [comment]
To be sure we don't miss anything, I cross-checked the documentation/implementation for 1.x and 2.x:

| `Accept` Header | Implemented in 1.x? | Documented in 1.x? | Implemented in 2.x? | Documented in 2.x? |
| ----------------- | -------------------- | ------------------- | -------------------- | ---------------------|
| `application/json` (default) | Yes | Yes | Yes | Yes |
| `application/csv` | Yes | Yes | Yes | No |
| `text/csv` | Yes | No | Yes | No |
| `text/plain` | No | No | Yes | No |
| `application/x-msgpack` | Yes | No | Yes | No |

AFAICS from reading the implementation, the `Content-Type` is wrong in all 2.x responses.

**Comment by danxmoran** [comment]
Early reactions on our end were to treat the 1.x implementation as the source of truth. Under that impression, my thought is to:
1. Delete the `text/plain` implementation from the 2.x code
2. Fix the remaining 2.x implementations to set the correct `Content-Type` header
3. Update the 2.x swagger API to document the `Accept` header, and to include all possible response `Content-Type`s

**Comment by stuartcarnie** [comment]
Everything looks good in your approach.

`text/plain` was added for debugging InfluxQL responses using `curl` when the `influx` client is not available, as it returns a human-readable response in a tabular format. I don't see a problem removing it.
