### ISSUE TITLE
Http request probllems of influxdb2.X

### ISSUE THREAD

**Issue by chuck199202104** [influxdata/influxdb#20515]
when i start the influxd, the  linux teminal prints log "no authorization found".
And then,i use the Http Api to write data to influxdb,also has the problem above.
Compare the config file 1.x and 2.x,there seems that 2.x has no Http configuration modules,so how can i start the Http function or it has been start in default?

best regards
thx!

**Comment by danxmoran** [comment]
Hi @chuck199202104, auth is required in 2.x, so you need to set it up before you can interact with the HTTP APIs. You can use `influx setup` to configure the initial admin user.

**Comment by chuck199202104** [comment]
Thx very much DM, it seems that the configuration file differs between 1.x and 2.x. And After I set up again, it works.thxs again!


 
---Original---

**Comment by danxmoran** [comment]
Good to hear!
