### ISSUE TITLE
aggregate value by the same timestamp

### ISSUE THREAD

**Issue by guluglu** [influxdata/influxdb#20532]
time     tag1    tag2   field1  field2
  10s         v1       v2        3     5
  10s         v1       v3        4     8
  11s        v1        v2       4      8

for example, i want to aggregate field with sum  for every timestamp.
time    sum(field1)  sum(field2)
10s           7               13
11s            4                8

how can i get the result besides  select group by time(1s).

**Comment by sanderson** [comment]
@guluglu You can do this with Flux. You'll need to truncate the timestamps to seconds, then pivot your data by field:

```js
from(bucket: "example-bucket")
  |> range(start: -1m)
  |> filter(fn: (r) => r._field == "field1" or r._field == "field2")
  |> truncateTimeColumn(unit: 1s)
  |> group(columns: ["_time", "_field"])
  |> sum()
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
```

**Comment by mohammadali-seifkashani** [comment]
Where the function should be implemented?
