### ISSUE TITLE
authorization problem Influx 2.0

### ISSUE THREAD

**Issue by Connz21** [influxdata/influxdb#20540]
hi guys,
he database team has created the InfluxDB 2.0
they have also created a user <Influxadmin> with administartion rights.
we need also two aother users with admin rights, but the DB team don´t know, how they can create such a user.
they have created a Admin token, assigned this token to the my userid, but I get always the same error.
what is going wrong?

best regards

Conny

**Comment by lesam** [comment]
This is essentially https://github.com/influxdata/influxdb/issues/22510, closing as work will be tracked on that issue.
