### ISSUE TITLE
log timestamp of last ingested data during graceful pod shutdown

### ISSUE THREAD

**Issue by Joe-Blount** [influxdata/influxdb#20557]
For debugging problems such as entropy, it would be useful to have a (per pod?) log of major events.  Then if we suspect an issue occurred at a specific time (e.g. from the timestamp of data involved in entropy), such a log would provide a ready answer to the question: was this pod doing anything interesting at that time?

To that end, it would be helpful to have storage pods log the timestamp of the last data ingested during a graceful shutdown.
Also, it is useful to log the timestamp of the first data ingested when a pod starts.

Note that if we get a "last timestamp" followed by a "first timestamp" that implies a graceful shutdown (and when it happened, and the data potentially vulnerable to mishandling).  If we just get a "first timestamp" that implies a non-graceful shutdown.

It would be nice to get these values into the tools cluster, possibly in a pod_log measurement in the StorageMetricsDownsampled bucket for long term retention.

key goal here: getting first/last timestamp into the tools cluster, as a starting point for an activity log.

**Comment by philjb** [comment]
related to https://github.com/influxdata/idpe/pull/11555 which was reverted because of an unexpected data race showing up in tests.

**Comment by 8none1** [comment]
Closing this via 11555
