### ISSUE TITLE
when passing variables to a dashboard in the url, some of the variables are not properly selected in the dropdowns

### ISSUE THREAD

**Issue by jimmejardine** [influxdata/influxdb#20571]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. create a dashboard with two query variables
2. create two URLs where the 2nd parameter is set to different values
3. open the dashboard via each url

__Expected behavior:__
The variables for the dash should reflect their setting in the URL.

__Actual behavior:__
Only the 1st variable consistently is reflected correctly.  The 2nd hardly ever.

__Environment info:__

* System info: Run `uname -srm` and copy the output here Linux 5.8.0-36-generic x86_64
* InfluxDB version: Run `influxd version` and copy the output here InfluxDB 2.0.3 (git: fe04d346df) build_date: 2020-12-15T01:00:16Z
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by ChitlangeSahas** [comment]
@jimmejardine I'm unable to reproduce this, would you mind posting the URL you are using, with the variables embedded in it? 

`&vars%5Bbucket%5D=defbuck&vars%5Bname%5D=mean` [the end part of what I used to test, and worked fine looks like this, if this is any help. :) ]


Thanks!

**Comment by jrenee42** [comment]
if the variable values are valid, then they do get set/change with the url
if the second value is invalid, then an error message shows up and the previous value remains set.

so, cannot reproduce.
