### ISSUE TITLE
improve RP enforcement with long intervals

### ISSUE THREAD

**Issue by Joe-Blount** [influxdata/influxdb#20594]
Motivation: observing how much more resources are used in toolsus1 after changing RP enforcement from 12H to 1H (it's hard to be precise here, but somewhere in the neighborhood of +80% CPU and IOPs use).

This has caused some thoughts around: what's so bad about 12h enforcement? / how can we make 12h enforcement acceptable for wide use?

E.g.
- Scheduling enforcement based on pod start time doesn’t work well with long intervals and frequent deployments (so look at scheduling enforcement based on a specific wall clock time rather than relative to pod start).
- Long enforcement periods make it more important to not skip a scheduled time (so detect if RP enforcement didn’t happen at desired time due to pod roll)
- It would be nice (from a resource perspective) if the various partitions on a pod applied their RP at different times, to diffuse the activity spike within the pod. (this may not happen due to current RP enforcement code path not acting on individual partitions)

Additional caveats discussed were: the need to have consistent RP enforcement times across the replicas of a given partition.

**Comment by 8none1** [comment]
Closing  this for now while we work out what needs to be changed on the billing side in order to account properly.
