### ISSUE TITLE
Nightly builds report a confusing version

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#20638]
The metadata packaged with our nightly builds say it's version `2.0.0~rc.4`. This causes confusion when installing a nightly over an "official" release, because tools like `dpkg` report it as a downgrade.

Ideally, our nightly builds could report a realistic version (i.e. `2.0~nightly-${date}`) without requiring significant grunt work on our part to keep the goreleaser configs up-to-date.

**Comment by codyshepherd** [comment]
deb and rpm metadata is potentially still incorrect
