### ISSUE TITLE
Continuous, real-time query execution feature

### ISSUE THREAD

**Issue by anaray** [influxdata/influxdb#2063]
label: feature_request
A feature like Percolator in ElasticSearch (elastic) will be quite useful. A capability to register certain real-time queries and to receive a call back upon the matching upon data insertion.
This would help to create a near real-time user interfaces .

**Comment by srikara** [comment]
+1

**Comment by jsternberg** [comment]
I think this can be done through subscriptions and with Kapacitor. @nathanielc is this something we can close?

**Comment by nathanielc** [comment]
@jsternberg @anaray I am not very familiar with the all the capabilities of the Percolator feature in ElasticSearch, but being able to trigger near real-time call backs on matching data is some thing Kapacitor can do.

**Comment by jsternberg** [comment]
I'm going to close this then since the feature request is old and we don't currently have any plans to implement this within the database itself. If this feature is still desired within InfluxDB for something like continuous queries, please open a new feature request.
