### ISSUE TITLE
'influx user create' cmd without -p flag misleading

### ISSUE THREAD

**Issue by ondrej-ivanko** [influxdata/influxdb#20645]
When running the **`influx user create command -n user_name -o org`** the CLI shows this error message: **`Error: Passwords must be at least 8 characters long.`**

Which is misleading or it's a bug. Im not sure what was the intention here. 

The reason for reporting this is because user is still created even after not supplying the -p flag. 
It's also not mentioned in help or documentantion that -p flag is required, so I assume this error msg must have been overlooked and should not be displayed on `influx user create`

https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/user/create/ 
This documentation also mentions that -p flag and -o/--org flag are mutually exclusive, which is not the case. User can still be create with both flags.

![Screenshot from 2021-01-29 09-51-01](https://user-images.githubusercontent.com/44980578/106253244-88926f00-6217-11eb-936b-39a91a3f4ba1.png)

**Comment by danxmoran** [comment]
Documentation fix reported at influxdata/docs-v2#2111. Fixing the CLI help text & parser should (hopefully) be straightforward.
