### ISSUE TITLE
Log query text for POST requests

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#20653]
Currently, the HTTP handler for `/query` logs query text for `GET` requests but not for `POST`. The handler should be changed to log query text for both.

**Comment by gegen07** [comment]
Hey, I'd like to contribute to this issue. There are any points that I have to know before tackling this issue?

**Comment by davidby-influx** [comment]
Proposed new format for POST:

```
2021-03-18T01:48:38.057192Z	info	Executing query	{"log_id": "0SxlABN0000", "service": "query", "query": "SELECT * FROM TestData.autogen.a"}
[httpd] 127.0.0.1 - - [17/Mar/2021:18:48:38 -0700] "POST /query?pretty=true HTTP/1.1" {"db": "[TestData]", "q": "[SELECT * FROM a]"} 200 1217 "-" "curl/7.68.0" 0eedc737-878c-11eb-8001-002b67685b12 1349
```
