### ISSUE TITLE
query caching mechanism for influxdb?

### ISSUE THREAD

**Issue by piaoyuankui** [influxdata/influxdb#207]
Cube - an other time series database base on mongo
http://square.github.io/cube/

Cube caching aggregate queries in mongo collections for multiple querying.
How Influxdb deal with same queries now?

**Comment by andhikasaja** [comment]
> i solved it with nginx
> 
> ```
> proxy_cache_path /var/cache/nginx-influxdb levels=2:2 keys_zone=influxdb:6m max_size=300m inactive=2d;
> 
> server {
>     listen 8088;
>     server_name {{ grains['fqdn'] }};
> 
>     set $cbypass 0;
>     set $mycc "public, max-age=20s";
> 
>     location / {
>         add_header Cache-Control $mycc;
>         proxy_pass http://acc2mfcfads.salt.xxx.ca:8086/;
>         proxy_cache_use_stale timeout updating error invalid_header;
> 
>         proxy_cache influxdb;
>         # proxy_cache_valid any 5m;
>     }
> }
> ```
> 
> grafana can use the cached datasource or the direct one.
> 
> ```
>     datasources: {
>         'graphite': {
>             type: 'influxdb',
>             url: 'http://acc2mfcfads.salt.xxx.ca:8086/db/graphite',
>             username: 'root',
>             password: 'root',
>         },
>         'graphite-cache': {
>             type: 'influxdb',
>             url: 'http://acc2mfcfads.salt.xxx.ca:8088/db/graphite',
>             username: 'root',
>             password: 'root',
>         },
>         'grafana': {
>             type: 'influxdb',
>             url: 'http://acc2mfcfads.salt.xxx.ca:8086/db/grafana',
>             username: 'root',
>             password: 'root',
>             grafanaDB: true,
>         },
>     }
> ```

where did you put this code on nginx? and how do you specify which database on influxdb you are querying?
