### ISSUE TITLE
Add support for disabling /metrics endpoint

### ISSUE THREAD

**Issue by lephisto** [influxdata/influxdb#20755]
Hello,

i want to bring one question to dicuss: Is it really wise to have the /metrics endpoint exposed without any kind auf authentication to the public if you run a InfluxDB 2.0 OSS default install on a public IP (or behind a reverseproxy - doesn't mattter)?

To be safe I limited access to https://myinfluxhost/metrics to ::1/127.0.0.1 to be sure. Probably not a sensitive Information, but still gives some info about the machine / vm / container details.

Do I totally miss something here?

br

**Comment by danxmoran** [comment]
Duplicate of #13413
