### ISSUE TITLE
Flux returning only 6000 raw records

### ISSUE THREAD

**Issue by agariaw** [influxdata/influxdb#20771]
I want to find the integral of a previous day whose raw data has 9000+ records. When using InfluxQL it returns all records, 
But when I use the same time range in Flux its uses the first 6000 raw records & perform integral() on it which is obviously wrong value.

Is there any limit in Flux to parse data?

**Comment by danxmoran** [comment]
@agariaw to help me diagnose:
* What version of InfluxDB?
* Can you paste your InfluxQL & Flux queries here?

**Comment by agariaw** [comment]
InfluxDB version is : **1.8.1**

InfluxQL query:
`SELECT integral("value") / 3600 FROM "autogen"."table_name" WHERE "value" > 0 AND time >= 1613502000000ms and time <= 1613588399000ms`

Flux:
```
from(bucket: "bucketName")
  |> range(start: 1613502000, stop: 1613588399) 
  |> filter(fn: (r) => r._measurement == "table_name" and r._value > 0 and (r._field == "value"))
  |> integral()
  |> map(fn:(r) => ({ _value: r._value / 3600.00 / 1000.00}))
```

**Comment by agariaw** [comment]
I figured it out. When I filter the value by -0 it works properly not with 0

Don't know how it is working, but it is solved now.

```
from(bucket: "bucketName")
  |> range(start: 1613502000, stop: 1613588399) 
  |> filter(fn: (r) => r._measurement == "table_name" and r._value > -0 and (r._field == "value"))
  |> integral()
  |> map(fn:(r) => ({ _value: r._value / 3600.00 / 1000.00}))
```
