### ISSUE TITLE
cannot add team member with existing account - influxdb cloud

### ISSUE THREAD

**Issue by AlexSzczepaniak** [influxdata/influxdb#20807]
__Steps to reproduce:__
1. add team member who has existing account to influx db
2. invite fails and recieve error message

__Expected behavior:__
Expect to have team member added and be given access to my buckets. 

__Actual behavior:__
Team member not added and receive error message. 

__Environment info:__
* InfluxDB version: influx db cloud

**Comment by russorat** [comment]
@AlexSzczepaniak thanks for the issue. this is frustrating right now, but we have a limitation in cloud today (which we are actively working to address) that you can only have 1 account per email. I recommend using a different email to invite the new user. 

Don't hesitate to reach out to support if you have any additional issues.
