### ISSUE TITLE
Influx delete: bad behaviour leads to data loss

### ISSUE THREAD

**Issue by jennerwein** [influxdata/influxdb#20825]
Running influx delete with only a small syntax error in the --predicate flag deletes ALL data with timestamps between the specified --start and --stop times in the specified bucket.

__Steps to reproduce:__
Put a small syntax error in the last `--predicate` flag of the following delete command:

```
influx delete \
  --bucket finanz-test \
  --org 'privat' \
  --start '2020-01-01T00:00:00Z' \
  --stop '2021-03-01T16:00:50Z' \
  --predicate '_measurement="zugriffsliste" '
```

__Expected behavior:__
A syntax error in the--predicate flag or an other part of the delete command should cancel the whole delete command and not just ignore the --predicate flag. Ignoring only the --predicate flag leads to this massive data loss.

__Actual behavior:__
ALL data in the specified bucket were deleted. (I don’t have data before 2020 in the bucket.)

__Environment info:__
I use influxdb:v2.0.4 running in docker.

**Comment by danxmoran** [comment]
@jennerwein can you be more specific about the error in your predicate that caused this behavior? I tried:
1. Using `AN` instead of `AND`
2. Forgetting a closing `"` on a string

Both returned errors and didn't delete data in my tests

**Comment by jennerwein** [comment]
I have now also tested the command once again with another bucket and found no error. The deletion of my data described above probably had another cause. Sorry for the circumstances.
