### ISSUE TITLE
API InfluxDB 2.0: Auth. problem deleting time series data

### ISSUE THREAD

**Issue by jennerwein** [influxdata/influxdb#20823]
The Influx API works fine when I retrieve data. However, when I want to delete data via the API, I get an authentication error message.

__Steps to reproduce:__
The following API request results in an authetication error message:

```
curl --request POST \
  http://0.0.0.0:8086/api/v2/delete/?org=privat&bucket=finanz-test   \
  --header "Authorization: Token $TOKEN" \
  --header 'Content-Type: application/json' \
  --data '{ "start": "2021-02-21T15:48:06.270251807Z", "stop": "2021-02-21T15:50:11.267979687Z" }'
```

__Expected behavior:__
Deletion of bucket`s points in the specified period.

__Actual behavior:__
I get the message `{"code":"unauthorized","message":"unauthorized access"}`. 
Although, retrieving data - instead of deleting - with the same token and bucket works fine. No authentication error.

__Environment info:__

I use influxdb:v2.0.4 running in docker.

**Comment by wbaker85** [comment]
Hi @jennerwein - I'm having a hard time reproducing this locally. Running `influxdb:v2.0.4` in Docker, I am able to issue an identical request as yours to the `api/v1/delete` endpoint successfully.

Do you have an example of the data retrieval request you are able to successfully make with the same bucket and token? Also any other info you can share might be helpful. Thanks!

**Comment by russorat** [comment]
I think the issue here is the trailing slash on the delete url (http://0.0.0.0:8086/api/v2/delete/ <- this slash)

For example: http://localhost:8086/api/v2 works just fine, but http://localhost:8086/api/v2/ fails with an unauthorized error.
