### ISSUE TITLE
error 401 when trying to run influxdb commands in shell

### ISSUE THREAD

**Issue by ElliotTanIIT** [influxdata/influxdb#20858]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. start commandline terminal in folder with influxdb executables
2. run 'influxd' for server
3. run 'influx' for client

additionally, I also tried changing the port number for http to 8087, but when I ran 'influxd' the port number that came up in the log was still 8086. I ran "influxd.exe -config influxdb.conf 2>logfile.log" but the config did not update.

__Expected behavior:__
Expected server to run and be able to run commands in influx shell

__Actual behavior:__
log of influxd shown below

tried to run some commands in influxdb shell but got these responses:
WARN: Connected to http://localhost:8086, but found no server version.
Are you sure an InfluxDB server is listening at the given address?
InfluxDB shell version: 1.8.4
> show databases
ERR: received status code 401 from server
> exit

__Environment info:__

* System info: Run `uname -srm` and copy the output here
CYGWIN_NT-10.0 3.1.7(0.340/5/3) x86_64
* InfluxDB version: Run `influxd version` and copy the output here
InfluxDB v1.8.4 (git: 1.8 bc8ec4384eed25436d31045f974bf39f3310fa3c)
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
only edited directory for data, meta, and wal

__Logs:__
ts=2021-03-04T06:43:29.572810Z lvl=info msg="InfluxDB starting" log_id=0Sf~U4dG000 version=1.8.4 branch=1.8 commit=bc8ec4384eed25436d31045f974bf39f3310fa3c
ts=2021-03-04T06:43:29.573806Z lvl=info msg="Go runtime" log_id=0Sf~U4dG000 version=go1.13.8 maxprocs=8
ts=2021-03-04T06:43:29.680034Z lvl=info msg="Using data dir" log_id=0Sf~U4dG000 service=store path="C:\\Users\\Elliot\\Desktop\\IIT\\2021\\Spring\\CS 550\\term project\\InfluxDB\\data"
ts=2021-03-04T06:43:29.680034Z lvl=info msg="Compaction settings" log_id=0Sf~U4dG000 service=store max_concurrent_compactions=4 throughput_bytes_per_second=50331648 throughput_bytes_per_second_burst=50331648
ts=2021-03-04T06:43:29.681036Z lvl=info msg="Open store (start)" log_id=0Sf~U4dG000 service=store trace_id=0Sf~U54G000 op_name=tsdb_open op_event=start
ts=2021-03-04T06:43:29.681036Z lvl=info msg="Open store (end)" log_id=0Sf~U4dG000 service=store trace_id=0Sf~U54G000 op_name=tsdb_open op_event=end op_elapsed=0.000ms
ts=2021-03-04T06:43:29.681036Z lvl=info msg="Opened service" log_id=0Sf~U4dG000 service=subscriber
ts=2021-03-04T06:43:29.681036Z lvl=info msg="Starting monitor service" log_id=0Sf~U4dG000 service=monitor
ts=2021-03-04T06:43:29.681036Z lvl=info msg="Registered diagnostics client" log_id=0Sf~U4dG000 service=monitor name=build
ts=2021-03-04T06:43:29.682034Z lvl=info msg="Registered diagnostics client" log_id=0Sf~U4dG000 service=monitor name=runtime
ts=2021-03-04T06:43:29.682034Z lvl=info msg="Registered diagnostics client" log_id=0Sf~U4dG000 service=monitor name=network
ts=2021-03-04T06:43:29.682034Z lvl=info msg="Registered diagnostics client" log_id=0Sf~U4dG000 service=monitor name=system
ts=2021-03-04T06:43:29.682034Z lvl=info msg="Starting precreation service" log_id=0Sf~U4dG000 service=shard-precreation check_interval=10m advance_period=30m
ts=2021-03-04T06:43:29.682034Z lvl=info msg="Starting snapshot service" log_id=0Sf~U4dG000 service=snapshot
ts=2021-03-04T06:43:29.682034Z lvl=info msg="Starting continuous query service" log_id=0Sf~U4dG000 service=continuous_querier
ts=2021-03-04T06:43:29.682034Z lvl=info msg="Starting HTTP service" log_id=0Sf~U4dG000 service=httpd authentication=false
ts=2021-03-04T06:43:29.683112Z lvl=info msg="opened HTTP access log" log_id=0Sf~U4dG000 service=httpd path=stderr
ts=2021-03-04T06:43:29.682034Z lvl=info msg="Storing statistics" log_id=0Sf~U4dG000 service=monitor db_instance=_internal db_rp=monitor interval=10s
run: open server: open service: listen tcp :8086: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by danxmoran** [comment]
@ElliotTanIIT is auth enabled in your `influxdb.conf`? If so, have you set up users and configured your CLI to use them (docs [here](https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/))?

**Comment by ElliotTanIIT** [comment]
i tried

> @ElliotTanIIT is auth enabled in your `influxdb.conf`? If so, have you set up users and configured your CLI to use them (docs [here](https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/))?

I tried following the instructions for setting up the inital admin but got the same error
![image](https://user-images.githubusercontent.com/42819771/110003058-a2721680-7cdb-11eb-9d0b-e50ab44c0c53.png)

Are all the lines in the config file supposed to begin with '#'? Or should I remove those?

**Comment by LLThomas** [comment]
I have the same problem while my influxd was compiled from source code.

**Comment by ElliotTanIIT** [comment]
I found that it was a firewall issue. I had to allow influxd firewall access.

**Comment by danxmoran** [comment]
Sounds like the original issue was resolved, so closing this
