### ISSUE TITLE
no matching manifest for linux/arm/v7

### ISSUE THREAD

**Issue by KS-HTK** [influxdata/influxdb#20857]
On the Raspberry Pi 3B (Raspbian Lite GNU/ Linux 10 buster) the latest version of influxdb results in `no matching manifest for linux/arm/v7 in the manifest list entries`

__Steps to reproduce:__
On the Raspberry Pi 3B:
1. install docker
2. run `docker pull influxdb`
3. look at output

__Expected behavior:__
Pull succedfull

__Actual behavior:__
output is
```
Using default tag: latest
latest: Pulling from library/influxdb
no matching manifest for linux/arm/v7 in the manifest list entries
```

__Environment info:__

* System info: Linux 5.10.11-v7+ armv7l

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
none

**Comment by netweaver1970** [comment]
same error when doing a pull (using docker-compose) on a Raspberry 4, on aarch64.

**Comment by danxmoran** [comment]
The failure on `armv7` is expected, InfluxDB 2.x doesn't support 32-bit architectures.

@netweaver1970 what OS are you running? I've seen failures to pull on RPi 4 when running the default OS, because Raspbian is 32-bit even when the hardware is 64-bit.

**Comment by netweaver1970** [comment]
@danxmoran 
Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64

This is the exact message when doing the docker-compose up:

Pulling influxdb (influxdb:)...
latest: Pulling from library/influxdb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by danxmoran** [comment]
@netweaver1970 yes, looks like it's trying to pull the 32-bit manifest even though it's a 64-bit machine. You could also run `uname -a` to confirm.

We aren't producing 32-bit builds at this point (and don't have plans to), so your only option would be to install a 64-bit OS on the machine. There is some info [here](https://www.raspberrypi.org/software/operating-systems/), I think most people go with Ubuntu but Raspbian OS 64-bit is also available in beta.

**Comment by netweaver1970** [comment]
on my Raspberry Pi 3B I'm getting the same error, this is the uname -a result from that one, running same OS ... 
both Buster, updated/upgrade and switched to 64 bit kernel.

Linux IOTstack 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux

**Comment by tablatronix** [comment]
hmm I installed last night on raspbian 64bit and it worked, of course it complained about setup and auth was broken migration not tested yet, i reverted

**Comment by peterxmon** [comment]
If Docker, MySQL, or MariaDB do not support the Armv7 architecture, you must install Ubuntu or Linux that meets the preceding requirements.

To fix it, you have to install Ubuntu Arm64. Go to the Ubuntu website and type in "Ubuntu for Raspberry Pi (versions 4, 3, or 2) Arm64." then use raspberry pi imager and ** select your "ubuntu-amd64-brabra-i-dont-know-what-is-your-file-name-but-it-must-has-Amd64.img" Create a boot SD card or your primary storage device. then re-setup your Pi machine.
