### ISSUE TITLE
Fix CI release build for 1.9 with Rust dependency

### ISSUE THREAD

**Issue by lesam** [influxdata/influxdb#20854]
We expect the merge of https://github.com/influxdata/influxdb/pull/20767 to break the 1.x release build process as we will need rust installed for cross-compiling. This issue is to fix the release build procedure.

**Comment by luismedicina23** [comment]
@Guys 

Plz in need a pdf rules about merge issues etc

**Comment by lesam** [comment]
Closed by https://github.com/influxdata/influxdb/pull/21002
