### ISSUE TITLE
Cannot create a task in UI that includes task options in the code

### ISSUE THREAD

**Issue by sanderson** [influxdata/influxdb#20887]
__Steps to reproduce:__

1. Create a new task in the UI.
2. Include a `options task` assignment in the task code. For example:

    ```js
    options task = { name: "example-task", every: 1h}
    ```

3. The task will fail to save with the following error:

    ```
    Failed to create new task: invalid options: @6:9-6:49: variable "task" conflicts with option of same name
    ```

__Expected behavior:__
I would expect the UI to see that the script already includes the `options task` assignment and not inject another one using data from the form on the left.

The question here is what takes precedence if both the form is filled out and the script already includes an `options task` assignment? This doesn't occur on subsequent saves of a task after it's been created. In that process, changes to `options task` assignment in the code are ignored and the form fields are honored.

__Actual behavior:__
On save, the UI injects a `options task` assignment using the data from the form on the left which results in a duplicate variable assignment.

* InfluxDB version: Cloud and OSS 2.0.4

**Comment by TCL735** [comment]
@sanderson - this is only reproduceable for me with the singular `option` and not the plural `options`.

@ChitlangeSahas has a fix for this will address the singular `option`.
