### ISSUE TITLE
influxQL query regex condition rewrite not working in subquery

### ISSUE THREAD

**Issue by yujiahaol68** [influxdata/influxdb#20881]
__Proposal:__
Also rewrite subquery regex conditions into static OR query for better series look up performance.
Not just rewrite regex for root query condition

__Current behavior:__
Currently, for example this query can be convert to multi string literal condition after compile

```sql
SELECT mean(usage) FROM cpu WHERE id =~ /^(foo|bar)$/ GROUP BY host
=> SELECT mean(usage) FROM cpu WHERE id = 'foo' OR id = 'bar' GROUP BY host
```

This is helpful in faster series key looking up in index.
However, if this query is subquery, the compiler won't convert the regex into multi string literal OR condition, for example

```sql
SELECT TOP(mean, 10), host FROM (SELECT mean(usage) FROM cpu WHERE id =~ /^(foo|bar)$/ GROUP BY host)
```

Because it is not root query condition so that the rewrite logic is not apply to subquery. So the subquery above will not benefit from the regex rewrite. WHAT a pity...

The code below in MARK 1 only rewrite its own condition. In subquery case, the subquery is identify as sources. So the rewrite is not working for subquery!

```go
func Compile(stmt *influxql.SelectStatement, opt CompileOptions) (Statement, error) {
	c := newCompiler(opt)
	c.stmt = stmt.Clone()
	if err := c.preprocess(c.stmt); err != nil {
		return nil, err
	}
	if err := c.compile(c.stmt); err != nil {
		return nil, err
	}
	c.stmt.TimeAlias = c.TimeFieldName
	c.stmt.Condition = c.Condition

	// Convert DISTINCT into a call.
	c.stmt.RewriteDistinct()

	// Remove "time" from fields list.
	c.stmt.RewriteTimeFields()

	// Rewrite any regex conditions that could make use of the index.
	c.stmt.RewriteRegexConditions()  // ====== MARK 1 ======

	return c, nil
}
```

__Desired behavior:__
We expect that the subquery can also be benefit from the regex rewrite. DEAD simple.

__Use case:__
Why is this important (helps with prioritizing requests)?
Subquery regex can also be formatted into a better AST tree for better query performance. Especially in grafana multi values query.

**Comment by Jeff885** [comment]
it likes good!
