### ISSUE TITLE
How to provision dashboard automatically?

### ISSUE THREAD

**Issue by jo-me** [influxdata/influxdb#20884]
Hi,
how can I provision a dashboard automatically after setting up influxdb 2.0?

Ideally, I would create & export a dashboard as JSON on my local dev machine and somehow import that dashboard in a new influx instance provisioned e.g. in a docker container or on a VM.
The CLI apparently only offers listing existing dashboards (https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/dashboards/)

Via CLI I can do the initial setup with "influx setup" which ​createas a new bucket as well.
How can I add / import the dashboard after the setup?

Is there a file/folder that would automatically be picked up?

Thanks
Jochen

**Comment by sanderson** [comment]
@jo-me This is what [InfluxDB templates](https://docs.influxdata.com/influxdb/v2.0/influxdb-templates/) are for. You create the dashboard, then export it as a template. You can then programmatically apply that template to any other InfluxDB instance.

**Comment by jo-me** [comment]
Ahhh, that piece was missing. Thanks!
