### ISSUE TITLE
unable to parse ~invalid number

### ISSUE THREAD

**Issue by leeyesang** [influxdata/influxdb#20895]
Hello
I am using InfluxDB rest API v2 and I am not using InfluxDB.client library. because unity3D assembly conflict so,  in http way  tryed but i don't know what to do this problem ( i want write data in Influxdb rest API (UI) using c#)

<problem >
{"code":"invalid","message":"unable to parse '\"mem,host=host1 used_percent=23\"': invalid number"}
UnityEngine.Debug:Log(Object)

and add timestemp(1556896326) ==> error message (bad timestemp)

<and my code >

          const string url = "http://localhost:8086/api/v2/write? 
          org=DT_navigator&bucket=test_bk&precision=s";

         async System.Threading.Tasks.Task WriteDataAsync()
        {
        var json = JsonConvert.SerializeObject("mem,host=host1 used_percent=23");
        var data = new StringContent(json, Encoding.UTF8, "application/json");

        HttpClient client = new HttpClient();
        client.DefaultRequestHeaders.Add("Authorization", "Token " + token);

        var response = await client.PostAsync(url, data);

        string result = response.Content.ReadAsStringAsync().Result;
        Debug.Log(result);
}

**Comment by danxmoran** [comment]
@leeyesang if you're still hitting this issue, I think it's likely a problem with your client-side code. If I use the `influx` CLI to write the same data it works fine:
```bash
influx write -b test_bk 'mem,host=host1 used_percent=23'
```

I have some guesses for what's going wrong in your code:
1. I think the `JsonConvert.SerializeObject` call is unnecessary, and is probably adding an extra set of quotes that might be confusing the parser
2. The content-type for your request data should be `text/plain`, not `application/json`

I'm going to close this for now. If you continue to hit problems, I'd recommend posting in our [community forum](https://community.influxdata.com/); there are many C# users there who could help you out 😄
