### ISSUE TITLE
Run make influx fails without error

### ISSUE THREAD

**Issue by ogarcia** [influxdata/influxdb#20942]
__Steps to reproduce:__
1. Download latest tagged release source code ([2.0.4 at this moment][1]).
2. Uncompress it.
3. Go to uncompressed directory an run `make influx`.
4. Wait for error.

[1]: https://github.com/influxdata/influxdb/archive/v2.0.4.tar.gz

__Expected behavior:__
After finish compilation have a `bin/linux/influx` binary.

__Actual behavior:__
Simply an error without more info

```
% make influx         
env GO111MODULE=on go build -tags 'assets' -ldflags "-s -w  -X main.commit=9b8546d" -o bin/linux/influx ./cmd/influx
# github.com/influxdata/influxdb/v2/chronograf/canned
chronograf/canned/bin.go:20:11: undefined: AssetNames
chronograf/canned/bin.go:23:18: undefined: Asset
# github.com/influxdata/influxdb/v2/chronograf/dist
chronograf/dist/dist.go:39:13: undefined: AssetInfo
chronograf/dist/dist.go:59:18: undefined: Asset
chronograf/dist/dist.go:74:11: undefined: Asset
chronograf/dist/dist.go:83:14: undefined: AssetDir
chronograf/dist/dist.go:84:14: undefined: AssetInfo
make: *** [Makefile:97: bin/linux/influx] Error 2
```

__Environment info:__

* System info: Linux 5.11.5-arch1-1 x86_64
* Other relevant environment details: go version go1.16.1 linux/amd64 and cargo/rust 1.50.0

**Comment by danxmoran** [comment]
@ogarcia as a work-around, running `make generate` before `make influx` should fix the issue. You could also run `make build`.

**Comment by ogarcia** [comment]
@danxmoran Ok, but `make generate` builds a lot of things (like ui). I'm looking for the minimal and faster mode to build influx binary.

**Comment by danxmoran** [comment]
@ogarcia unfortunately the current layout of the `influxdb` repository makes it difficult to build only the CLI code. For example, the error you originally hit was caused because UI-related files hadn't been generated. We're working on a plan to fix this problem by decoupling the CLI and server codebases.

**Comment by ogarcia** [comment]
@danxmoran ok, no problem, I can wait for it :wink:

**Comment by lindacorbett** [comment]
Yes I believe it will pick up after Easter is finished linda c

**Comment by lindacorbett** [comment]
Onwards and upwards

**Comment by russorat** [comment]
this is in progress. check out https://github.com/influxdata/influx-cli

**Comment by danxmoran** [comment]
We've finished moving the CLI code over to the linked repository, closing this.
