### ISSUE TITLE
Log query text for POST requests [Port to 2.X]

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influxdb#21001]
Port https://github.com/influxdata/influxdb/issues/20653 to 2.X

**Comment by danxmoran** [comment]
Confirmed 2.x currently logs request bodies for both `/api/v2/query` and `/query` requests. The logs are leveled as `debug` instead of `info`.

Closing this as I believe there are separate issues around making 2.x logging more consistent with 1.x logging in general.
