### ISSUE TITLE
InfluxDB Cloud CSV upload seems to be broken

### ISSUE THREAD

**Issue by idea--list** [influxdata/influxdb#21011]
__Steps to reproduce:__

1. Log into InfluxDB Cloud account
2. Create a bucket
3.  Click "+Add Data" button
4.  Select CSV Upload option and try to upload a CSV file
5. It will tell: "Please make sure that CSV was in Annotated Format and try again"

I copy&pasted the content of my csv from [here](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/), so i am pretty sure that it is in annotated CSV format.

__Expected behavior:__
I expected the above method to import annotated CSV files without any error.

__Actual behavior:__
The above method fails to import annotated CSV files.

__Environment info:__

InfluxDB Cloud deployment in Frankfurt on AWS.
CSV file written with Notepad on a Win10 x64 machine
Using Chrome V89.0.4389.90

**Comment by russorat** [comment]
@idea--list thanks for the issue. The csv upload tool in the UI only works with a fully annotated csv output from flux. it's useful for downloading the results from a flux query and loading them to another bucket, or sending them to another user.

the docs link you referenced is for loading data via the influx CLI tooling. that tool is flexible enough to load any csv data format imaginable, but requires much more configuration not available in the UI.

**Comment by idea--list** [comment]
@russorat 
By fully annotated csv output from flux you mean Extended annotated CSV documented [here](https://docs.influxdata.com/influxdb/cloud/reference/syntax/annotated-csv/extended/#)?

**Comment by kristinarobinson** [comment]
Now fixed.
