### ISSUE TITLE
Comments form doesnt work on blog pages

### ISSUE THREAD

**Issue by Nex-Otaku** [influxdata/influxdb#21110]
Trying to post any comment on blog page, got error "405 Method not Allowed"

For example, this page: https://www.influxdata.com/blog/running-influxdb-2-0-and-telegraf-using-docker/#respond

**Comment by Asalem1** [comment]
Hey @Nex-Otaku thanks for reporting this. Just raised some flags, will hopefully get this sorted ASAP
