### ISSUE TITLE
InfluxDB 2.0.4 version missing "plist" files via "brew" installation

### ISSUE THREAD

**Issue by Istorn** [influxdata/influxdb#21122]
I'm currently using MacOS Big Sur 11.0.1 version and following the installation tutorial on your website.

Installation works:

`brew install influxdb`

The second step, to have `launchd` command:

`ln -sfv /usr/local/opt/influxdb/*.plist ~/Library/LaunchAgents`

Won't work, because there's not a single "plist" type file into the folder, indeed:

`ls /usr/local/opt/influxdb/*.plist      `                  

`no matches found: /usr/local/opt/influxdb/*.plist`

The problem persists even if I delete everything and launch `brew reinstall influxdb`.

**Comment by danxmoran** [comment]
The `influxdb` formula is community-maintained. I'd open an issue against [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core)
