### ISSUE TITLE
InfluxDB "-config" flag is not recognized on MacOS CLI

### ISSUE THREAD

**Issue by Istorn** [influxdata/influxdb#21123]
I'm currently using MacOS Big Sur 11.0.1 and InfluxDB 2.0.4.

If I try to launch the following command:

`influxd -config /usr/local/etc/influxdb.conf`

Here it comes output:

`Error: unknown shorthand flag: 'c' in -config`

**Comment by danxmoran** [comment]
The CLI options supported by `influxd` (and `influx`) are very different in 2.0. See our 2.x reference doc sections on [configuring influxd](https://docs.influxdata.com/influxdb/v2.0/reference/config-options/) and the [CLI options in general](https://docs.influxdata.com/influxdb/v2.0/reference/cli/).
