### ISSUE TITLE
Regarding 2.0.5 nightly

### ISSUE THREAD

**Issue by gtr32x** [influxdata/influxdb#21135]
Hi there, as a previous thread here I've asked where shard group duration will be supported in v2 and I received a positive answer. It was previously mentioned that the stable version would be due by the end of last month. However since it's still not there I've attempted to download the nightly to give this a try. I'm wondering what's the appropriate command to use to set shard group duration during bucket creation? Thanks.

**Comment by danxmoran** [comment]
@gtr32x you can pass `--shard-group-duration <duration>` to `influx bucket create` to set the value. Durations are specified using the same format as `--retention`, i.e. `1w` or `12h`. The same flag works with `influx bucket update`.

The official 2.0.5 release should be coming soon. We discovered a tricky Flux bug late last month and were waiting for a fix to land before releasing; the PR with the fix just went up today.

**Comment by gtr32x** [comment]
Gotcha, thank you.
