### ISSUE TITLE
Flux query: timestamps out of sequence

### ISSUE THREAD

**Issue by holmesb** [influxdata/influxdb#21147]
Expanding timeframe for this Flux query to > 12 hours:
```
from(bucket: "primary")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["host"] == "server01")
  |> filter(fn: (r) => r["_field"] == "last_offset")
  |> drop(columns:["_field", "_measurement", "leap_status", "stratum", "reference_id"])
```
gives [this data](https://gist.github.com/holmesb/59c6bce7bbf9a892ff2b698391fb2f8c).  Notice times in lines 107 and 108 look like this:
```
2021-04-05T13:30:40Z
2021-04-05T07:12:50Z
```
Line 108 has reversed time by ~ six hours.  This results in the corruption in the chart:
![image](https://user-images.githubusercontent.com/5072156/113671370-27bb6300-96ae-11eb-9c89-6f902230f3cd.png)
Notice there is a stray line at the start of the graphed period.  This happens to all time series with this Chrony query, and occurs for all periods longer than 12 hours.  Has occurred over several days, so this is not a one-off with this specific timeframe.

__Steps to reproduce:__
Type the above following query and use a period longer than 12 hours.

__Expected behavior:__
No out-of-sequence timestamps & corrupt\stray lines

__Environment info:__
* System info: Linux 5.4.0-42-generic x86_64
* InfluxDB version: InfluxDB 2.0.4 (git: 4e7a59bb9a) build_date: 2021-02-08T17:47:02Z
* Other relevant environment details: Kubernetes

__Logs:__
Nothing is logged when this problem occurs

__Performance:__
Has plenty of memory & CPU

**Comment by holmesb** [comment]
Adding aggregateWindow() line to query fixed

**Comment by alexcolpitts96** [comment]
I am having the same issue with Influx 2.0.8 except aggregateWindow and window are causing the problem.

Without a windowing function I do not have the issue, but using a windowing function I get the data out of order.

The values of the data points aren't changing, only the order.
