### ISSUE TITLE
I just updated from v1.7 to 2.0.4 not able to find the Shell

### ISSUE THREAD

**Issue by dnsoumik** [influxdata/influxdb#21177]
Can anyone help me with how to get the Terminal/shell working?

**Comment by dnsoumik** [comment]
Does it even have a shell?

**Comment by danxmoran** [comment]
@dnsoumik no, the shell/REPL has been removed in 2.x

**Comment by dnsoumik** [comment]
Why? Is there any other way to use it. 
I can't use the UI for some specific reasons. 
Not having the shell will break our entire workflow.
Is there anything you can help me with?

**Comment by timhallinflux** [comment]
https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/query/
