### ISSUE TITLE
Keep comments in InfluxDB tasks

### ISSUE THREAD

**Issue by snenkov** [influxdata/influxdb#21176]
__Proposal:__
Keep the lines with comments inside the Task (in the Influx UI).

__Current behavior:__
Once a task is created, the comments are deleted.

__Desired behavior:__
I would like if a comment exists, to be kept there.

__Alternatives considered:__
None really.

__Use case:__
 This will allow for more complicated code to be stored.

**Comment by ChitlangeSahas** [comment]
This is Flux work, track here: https://github.com/influxdata/flux/issues/3474

**Comment by kristinarobinson** [comment]
Now fixed, as per influxdata/flux#3474 status.
