### ISSUE TITLE
Restoring InfluxDB apk on Mac

### ISSUE THREAD

**Issue by im-asad** [influxdata/influxdb#21188]
When I try to restore a backup influxdb file provided to me by senior, I am somehow not able to pass the right path. 

When I place the backup db file in `/usr/local/influxdb`, I get the following error:
`restore: backup path should be a valid directory: usr/local/influxdb/db.apk`

Similarly, when trying to pass absolute path `/Users/username/Downloads`, I still get the same error:
`restore: backup path should be a valid directory: /Users/asadawan/Downloads/db.apk`

The backup db is placed in both the locations.

Can somebody help me to pass the right path? I am using InfluxDB 1.8

**Comment by timhallinflux** [comment]
not sure where you are getting the .apk file format, but that isn't supported by the restore process.
