### ISSUE TITLE
get start

### ISSUE THREAD

**Issue by yanhongwangg** [influxdata/influxdb#21202]
when i use command go build ./cmd/influxd
![image](https://user-images.githubusercontent.com/67779101/114647765-3dfd9a80-9d10-11eb-82b8-d7531db8a7bc.png)

**Comment by danxmoran** [comment]
@yanhongwangg a standard `go build` doesn't work because of the Rust pieces in our Flux dependency. See [this section](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#building-from-source) of `CONTRIBUTING.md` for instructions on building from source.
