### ISSUE TITLE
InfluxDB UI returns 500 Internal Server Error on initial setup 

### ISSUE THREAD

**Issue by SandmanFL** [influxdata/influxdb#21223]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Install InfluxDB on macOS using homebrew (after homebrew update)
2. Start InfluxDB (enter 'influxd' in terminal window)
3. Open Chrome or FireFox browser and enter http://localhost:8086 in browser url input

__Expected behavior:__
Expected the InfluxDB UI to appear

__Actual behavior:__
500 Internal Server Error is shown in browser body

__Environment info:__

* System info: Run `uname -srm` and copy the output here : Darwin 20.3.0 x86_64
* InfluxDB version: Run `influxd version` and copy the output here : InfluxDB 2.0.4 (git: none) build_date: 2021-04-15T15:32:23Z
* Other relevant environment details: Container runtime, disk info, etc : macOS Big Sur (version 11.2.3)

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by samsieber** [comment]
This also happens to me. I think this issue is a duplicate of https://github.com/influxdata/influxdb/issues/21133

**Comment by SandmanFL** [comment]
I uninstalled the brew install of InfluxDB, and manually installed InfluxDB and it is now working. Thanks to @samsieber for the workaround.

**Comment by SandmanFL** [comment]
Closing as this is a duplicate of #21133
