### ISSUE TITLE
Prohibit writes with precision, but without an explicit timestamp

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#2124]
This should be blocked in 0.9.

**Comment by gst** [comment]
Probably useful to give the link to the discussion that lead to this : https://groups.google.com/forum/#!topic/influxdb/yWpv_WJ6-uU

**Comment by jsternberg** [comment]
This never got done before the 1.0 freeze and I think this is a breaking change so I'm going to make a PR to add this to the v2 TODO list so we can remember this exists and close out this issue.

**Comment by jsternberg** [comment]
Added this to the TODO list for v2. Might become part of the new line protocol too.
