### ISSUE TITLE
Not able to send data from Krakend API gateway to influx DB

### ISSUE THREAD

**Issue by go4sachin007** [influxdata/influxdb#21278]
I have Krakend API gateway which provide provision to push data to influx DB. Here below is the configuration
`{
  "version": 2,
  "extra_config": {
		"github_com/devopsfaith/krakend-opencensus": {
		  "exporters": {
			"influxdb": {
				"address": "http://10.10.3.80:8086",
				"db": "krakend",
				"timeout": "1s"
			}
		  }
		}
   },
  "name": "My lovely gateway",
  "timeout": 10,
  "host": [
        "http://10.10.3.80"
   ],
  "endpoints": [
    {
      "endpoint": "/foo",
      "method": "POST",
      "headers_to_pass": [
              "Content-Type"
      ],
      "querystring_params": [
         "a_data",
         "check_user_name",
         "master_key"
      ],
      "backend": [
        {
          "url_pattern": "/user_info-cas/services/rest.php/bebonetUser/checkUserName",
          "host": [
            "http://10.10.2.109"
          ]
        }
      ],
      "concurrent_calls": "1",
      "max_rate": 100000
    }
  ],
  "oauth": {
    "disable": true
  },
  "cache_ttl": "5m",
  "timeout": "5s"
}`

I have created krakend bucket on influxdb 2.0
Created config as 

`influx config create --config-name local-config1 \
  --host-url http://10.10.3.80:8086 \
  --org krakend\
  --token lYwRs0dSUyeM37JSPpG-b-h2QujlJSKepUxEa-i52UZI5rsGZ7UFwu1yiDDma9H2I3I662lmFn9jPX6d9g57tg== \
  --active`

Provided read/write access

`influx auth create \
  --read-bucket 1acfbb3a1912882d \
  --write-bucket 1acfbb3a1912882d `

But when run the krakend and hit API it give following error
`Error when uploading stats to Influx: {"code":"unauthorized","message":"unauthorized access"}`

Please help me I really need to fix this

Thanks
Sachin

**Comment by sanderson** [comment]
@go4sachin007 It looks like the KrackenD InfluxDB integration is built for InfluxDB 1.x and doesn't provide a way to pass authentication credentials. InfluxDB 2.0 requires authentication. Do you know of a way to pass either a username/password combination or an API token? If KrackenD doesn't provide a way, then you may need to create an issue on their end.

The CLI config you created only provides authentication credentials to `influx` CLI commands.

**Comment by go4sachin007** [comment]
Hi Sanderson,

Thanks for the reply.
I am confirming this from Krakend side

Thanks a lot is really helpful

Thanks
Sachin

**Comment by kpacha** [comment]
yes, both influxdb exporters for KrakenD (one for the custom metrics collector and other for the opencensus collector) support all the config options exposed by the influxdb v1.x client (such as username and password)

**Comment by russorat** [comment]
based on the linked issue, this has been resolved. Thanks!
