### ISSUE TITLE
Mismatch version in WEB UI

### ISSUE THREAD

**Issue by Bacto** [influxdata/influxdb#21354]
Hi,

When starting InfluxDB 2.0.6, the version displayed in WEB UI is 2.0.5
Tested with InfluxDB sources and docker image (docker run -p 8086:8086 influxdb:2.0.6)

<img width="1598" alt="Screenshot 2021-05-03 at 14 38 15" src="https://user-images.githubusercontent.com/1188497/116876791-4c5b1a00-ac1d-11eb-9ee3-59883fef1e4c.png">

**Comment by danxmoran** [comment]
Duplicate of influxdata/influxdata-docker#484

See the explanation there. I'll leave this one open for others to find.

**Comment by wbaker85** [comment]
Closed by #21564
