### ISSUE TITLE
2.0.6: geo.strictFilter() - panic: attempting to access non-existant value "ST_Contains"

### ISSUE THREAD

**Issue by abalone23** [influxdata/influxdb#21352]
In 2.0.6 OSS `geo.strictFilter()`  result in a panic. It works fine in InfluxDB Cloud (Flux v0.113.2-0.20210428163201-b47eeb0678b8)
__Steps to reproduce:__
```
import "experimental/geo"
import "csv"

data="
#group,false,false,false,true,false,false,false
#datatype,string,long,dateTime:RFC3339,string,string,double,double
#default,_result,,,,,,
,result,table,_time,_measurement,id,lat,lon
,,0,2021-05-02T11:37:40Z,the_measurement,us7000dzhg,-30.133,-71.5399
"

csv.from(csv: data)
  |> filter(fn: (r) => r["_measurement"] == "the_measurement")
  |> geo.strictFilter(region: { lat: -30.000, lon: -71.0000, radius: 100.0 })
```
__Expected behavior:__
One record should be returned.

__Actual behavior:__
> panic: attempting to access non-existant value "ST_Contains"

__Environment info:__
2.0.6 OSS
Flux: v0.113.0

**Comment by lesam** [comment]
As a workaround, it is possible to add this to a flux script:

```
import "planner"
option planner.disableLogicalRules = ["MergeFiltersRule"]
```

#21356 does this across all flux scripts until we can fix the underlying bug, and adds a test for this broken case.
