### ISSUE TITLE
InfluxQL Time Selection not working with Group By Clause

### ISSUE THREAD

**Issue by ChristianKuenne** [influxdata/influxdb#21366]
__Steps to reproduce:__

I have a measurement ("machine") with two values ("temp", "humidity") and one tag ("batch_no").
How can I get the temperature, humidity and the time at the start of each batch? Ideally I want to be able to select first("time"), but that's not possible. The time is returned anyway, but not as expected:

```
SELECT first("temp") AS "Temperature", first("humidity") AS "Humidity"
FROM "machine"
WHERE time > now()-1h
GROUP BY "batch_no"
ORDER BY time
```

__Expected behavior:__

I expect the following results:

Time  | batch_no      | Temperature        | Humidity  |
------|---------------|--------------------|-----------|
10:00 | 1             | 80                 | 39        |
10:12 | 2             | 78                 | 40        |
10:23 | 3             | 81                 | 40        |

__Actual behavior:__

I am getting the following results:

Time  | batch_no      | Temperature        | Humidity  |
------|---------------|--------------------|-----------|
10:28 | 1             | 80                 | 39        |
10:28 | 2             | 78                 | 40        |
10:28 | 3             | 81                 | 40        |

The time is the current time and not the time of each group. It works when I select one value only:

```
SELECT first("temp") AS "Temperature"
FROM "machine"
WHERE time > now()-1h
GROUP BY "batch_no"
ORDER BY time
```

Time  | batch_no      | Temperature        |
------|---------------|--------------------|
10:00 | 1             | 80                 |
10:12 | 2             | 78                 |
10:23 | 3             | 81                 |

I might be missing something, but this behaviour seems strange.

Is it really not possible to get the first time (and the last time) for each group?

__Environment info:__

* System info: Linux 5.4.0-1045-aws aarch64
* InfluxDB version: InfluxDB v1.8.4 (git: 1.8 bc8ec4384eed25436d31045f974bf39f3310fa3c)

**Comment by Yussef77** [comment]
SELECT *
FROM "machine"
WHERE time > now()-1h
GROUP BY "batch_no"
ORDER BY time asc
limit 1

**Comment by ChristianKuenne** [comment]
Perfect, thanks very much!
