### ISSUE TITLE
influx DB fails to start. Error: listen tcp :8086: bind: address already in use

### ISSUE THREAD

**Issue by bincegeorge** [influxdata/influxdb#21384]
List the minimal actions needed to reproduce the behavior.

The influx DB fails to start. Getting an error while trying to open in mac OS.

Error: listen tcp :8086: bind: address already in use

If I check for what's running on 8086, I can see influxd is already running.

lsof -i:8086

COMMAND    PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
influxd  23322 i322910   21u  IPv6 0xa12fa8803a2eeb93      0t0  TCP *:8086 (LISTEN)
influxd  23322 i322910   32u  IPv6 0xa12fa8803022a533      0t0  TCP localhost:8086->localhost:60702 (ESTABLISHED)
telegraf 29367 i322910   12u  IPv6 0xa12fa88030229ed3      0t0  TCP localhost:60702->localhost:8086 (ESTABLISHED)

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Environment info:__

* System info: Darwin 20.3.0 x86_64
* InfluxDB version: InfluxDB 2.0.6 (git: none) build_date: 2021-05-06T06:14:51Z
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Error: listen tcp :8086: bind: address already in use

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by wbaker85** [comment]
Are you able to access the `influxd` process that is already running on port `8086`? And if you stop all the processes that show up in the `lsof -i:8086` output, do you still get the same error when trying to start `influxd`?

**Comment by wbaker85** [comment]
Closing this for now since running influxd on the standard port is widely known to work or the port is available
