### ISSUE TITLE
Add pagination support to find/list GET APIs

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#21391]
Some of our APIs hard-code a limit parameter / don't allow specifying an offset, making it impossible for users to see all of their resources. Other APIs don't use pagination at all, presenting the risk of a runtime bomb from too-large response bodies.

Add pagination parameters to all find/list GET APIs, using a consistent pattern.

**Comment by russorat** [comment]
The parameters needed for pagination at a minimum are: `limit`, `offset`, and `filter`. 

Filter would return only the results where the filter is in the name of the resource.
