### ISSUE TITLE
Add pagination support to `/telegrafs` API

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#21407]
Add support for `limit`/`after`/`descending` to the `GET /telegrafs` API.

**Comment by Kevinjil** [comment]
Are these features planned to be implemented? I currently cannot get the IDs of any Telegraf instances beyond the default pagination (20) using the API or CLI.

**Comment by lesam** [comment]
After discussing with @hoorayimhelping , I think the right answer here is to just remove the pagination limits.

**Comment by lesam** [comment]
Note we never supported changing the pagination via the API, so after the linked PR we will just return all the values always instead of limiting to 20.
