### ISSUE TITLE
Add pagination support to `/users` API

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#21402]
Add support for `limit`/`after`/`descending` to the `GET /users` API.

**Comment by bednar** [comment]
@danxmoran, what do you think about https://github.com/influxdata/influxdb/issues/21402? The #21402 closes this issue.

**Comment by bednar** [comment]
@danxmoran, what do you think about https://github.com/influxdata/influxdb/issues/21367? The #21367 closes this issue.
