### ISSUE TITLE
Add bucket cardinality information to the /metrics endpoint

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#21471]
__Proposal:__
Add counters to the /metrics endpoint that report the cardinality of each bucket in the oss instance

__Current behavior:__
There is no cardinality information stored there

__Desired behavior:__
Similar to the https://docs.influxdata.com/platform/monitoring/influxdata-platform/tools/measurements-internal/#nummeasurements and https://docs.influxdata.com/platform/monitoring/influxdata-platform/tools/measurements-internal/#numseries information in 1.x, adding this information to the /metrics endpoint would allow users to monitor for runaway cardinality issues

**Comment by lesam** [comment]
Closed by https://github.com/influxdata/influxdb/pull/22938

**Comment by lesam** [comment]
Specifically:

```
# HELP storage_bucket_series_num Gauge of series cardinality per bucket
# TYPE storage_bucket_series_num gauge
storage_bucket_series_num{bucket=“b7da63cc2f6d922f”} 85
storage_bucket_series_num{bucket=“d2dc443f48b2c910"} 25
```
