### ISSUE TITLE
influxd (1.x) backup -portable does not delete uncompress shard archives on Windows

### ISSUE THREAD

**Issue by jla** [influxdata/influxdb#21470]
__Steps to reproduce:__
1. influxd backup --database test_db -portable C:\backup

__Expected behavior:__
.meta and .manifest files plus some .tar.gz files on the backup destination folder

__Actual behavior:__
also the all the uncompress .tar.gz files (.autogen.xxxxx.00) remain on the folder

__Environment info:__

* System info: Windows 10
* InfluxDB version: 1.7

----

Maybe this should be the other way around:

https://github.com/influxdata/influxdb/blob/c8da9bafbf4121898fd68fdc1ade1d6f0246c4af/cmd/influxd/backup/backup.go#L269-L270

On linux you can delete a file before closing it, but windows does not allow it

**Comment by lesam** [comment]
See also https://github.com/influxdata/influxdb/issues/16289
