### ISSUE TITLE
how to query localhost influxdb(1.7) database remotely from another computer using python

### ISSUE THREAD

**Issue by r-puneet** [influxdata/influxdb#21536]

**Comment by sanderson** [comment]
@r-puneet You must make your localhost available on a network, whether that be the public network or a private network. Configuring that kind of network level access it outside the scope of InfluxDB and wholly depends on your architecture. With network access configured, you can use the [InfluxDB Python client](https://github.com/influxdata/influxdb-python) to query InfluxDB.
