### ISSUE TITLE
`influxd upgrade` with `-f` and missing options prints unhelpful error message

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#21566]
See [this example](https://github.com/influxdata/influxdb/issues/21534#issuecomment-848503180). When running `influxd upgrade` with the `-f` option, users must provide:
* `--username`
* `--password`
* `--bucket`
* `--org`

If they don't, the onboarding request to the server will fail with the very unhelpful message:
```
Error: onboarding error: onboard failed, missing value
```

We should beef up validation for force-mode to print something more useful.

**Comment by PeggyFree** [comment]
I confirm the following parameters are mandatory under windows for the migration to work : 

.\influxd.exe upgrade  **--config-file** influxdb.conf **--username** 'usr' **--password** 'pwd' **-f --bucket** 'buck' **--org** 'corp'
