### ISSUE TITLE
Allow for running a backup without gzip'ing the result in tar

### ISSUE THREAD

**Issue by wbaker85** [influxdata/influxdb#21576]
A community user asked about running a backup without having the resutling tar file Gzip'd: https://community.influxdata.com/t/disable-gzip-for-database-backups/20110

It doesn't look like this is currently possible to do in either `2.x` or `1.x`, but it might be beneficial for use-cases like these.

**Comment by danxmoran** [comment]
I split the 2.x piece of this to influxdata/influx-cli#113

**Comment by lesam** [comment]
This is solved in 2.x , will not be fixed in 1.x OSS.
