### ISSUE TITLE
Prometheus not doing remote write to InfluxDB OSS v2.0

### ISSUE THREAD

**Issue by prab2014** [influxdata/influxdb#21586]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.
Trying to do prometheus remote write in influxdbv2.0 
1. ...   
remote_write:
       - url: http://localhost:8086/api/v1/prom/write?db=prometheus&u=****&p=*****
         basic_auth:
          password: ********
2. ...
3. ...

__Expected behavior:__
Prometheus remote write should happen in influxdb2.0 and can see the measurements

__Actual behavior:__
Describe What actually happened.
No data getting created at influxDB

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by sjwang90** [comment]
duplicate: https://github.com/influxdata/influxdb/issues/17958
