### ISSUE TITLE
Annotations: visually announce how to annotate 

### ISSUE THREAD

**Issue by daviddkkim** [influxdata/influxdb#21591]
### Background

We've introduced the gesture for range annotation as Shift + Drag. This isn't something that is self-explanatory for most users. 

We will need documentation to carry the weight here but we could also do something from in-app to educate users.

We could do this with the annotation bar:

![Screen Shot 2021-06-02 at 5.35.37 PM.png](https://images.zenhubusercontent.com/604f76d7b2c0ce7a06471654/9439ba9a-a3f7-42d2-8ec5-a27162c2acb5)

Acceptance Criteria
- As a user, when I click on annotation button to turn it on, the annotations write and read modes are turned on. Also, the annotation bar appears with text indicating how I may add an annotaton/ ranged annotation. 
- As a user, when I click on annotation button to turn it off, the annotations write and read modes are turned off. The annotation bar disappears as well.
-The tooltip on the annotations button (on hover) , reflect the state of the annotations mode and how the user can turn on/off annotations. (I.E, Annotations mode is turned on. Click the annotations button to turn it off")

**Comment by daviddkkim** [comment]
Thought about banner as well but I think this might be a little too disruptive

 ![Screen Shot 2021-06-02 at 6.02.19 PM.png](https://images.zenhubusercontent.com/604f76d7b2c0ce7a06471654/1d6d8934-62c5-402a-aaa5-9d73ca0e32e1)

Any thoughts?

**Comment by jrenee42** [comment]
this also *implements* the new changes above (removes the buttons from the annotations control bar, makes a range annotation need to have the shift key down)

and fixes the tests to compensate as well.
