### ISSUE TITLE
Rewriting fields.idx is a bottleneck with many new fields and measurements [port to 1.9 branch]

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influxdb#21597]
https://github.com/influxdata/influxdb/issues/21577 port to 1.9 branch for 1.9.2

**Comment by lesam** [comment]
Reopening as I have reverted from 1.9 since it should be in 1.9.3, not 1.9.2

**Comment by lesam** [comment]
See https://github.com/influxdata/influxdb/compare/master...lesam:1.9-reset?expand=1
