### ISSUE TITLE
Authorization Header, User:Pw and Token. From curl to Postman

### ISSUE THREAD

**Issue by yonglizhong** [influxdata/influxdb#21654]
I am currently attempting to reproduce what I have done via Curl to write data into my influxDB 2.0 Server with Postman

Example: 

curl -XPOST "https://randomwebsite.com/api/v2/write?org=myORG&bucket=myTestBucket" -u user:pasword --header "Authorization: Token randomtokenvalue" --data-raw "mem,host=host1 value=123"

Unfortunately by importing the curl command directly into Postman shows that I have a duplicate Authorization Header. One for User:Password and one for Token. This naturally gives me Error code of 401 unauthorized access. Wonder if anyone has attempted such feat and could share their experience. Is it possible to do so? The Curl command does work for me, so I'm wondering how to replicate such.

I will of course continue to attempt and hope to share if I have managed to achieve something.

Thanks for your time and attention.

**Comment by danxmoran** [comment]
@yonglizhong dropping the `-u user:password` should fix things for you, basic auth isn't recognized by the v2 API. I'm not sure why it's working with curl (Setting `Authorization: Token` might be overriding it somehow).

**Comment by yonglizhong** [comment]
> @yonglizhong dropping the `-u user:password` should fix things for you, basic auth isn't recognized by the v2 API. I'm not sure why it's working with curl (Setting `Authorization: Token` might be overriding it somehow).

Hi @danxmoran , you're right. Somehow by dropping the -u user:password and only using token authorization worked for me. This applies to both Curl and Postman. Thanks for the tip. Will close this topic now.
