### ISSUE TITLE
Incorrect version displayed when I build docker image manually

### ISSUE THREAD

**Issue by mnsmithuk** [influxdata/influxdb#21663]
HI,

Is the a setting I need to use when building a docker image manually.

I'm currently using the command docker build --target influx --tag influxdb:v2.0.7 .

Once built the login displays

![Screenshot 2021-06-11 at 12 53 01](https://user-images.githubusercontent.com/30718438/121682444-03b43d80-cab4-11eb-853a-e21603d3450b.png)

However when I download and use the official image the login displays

![Screenshot 2021-06-11 at 12 54 51](https://user-images.githubusercontent.com/30718438/121682640-3cecad80-cab4-11eb-8340-3798bf673719.png)

The server id is the same but the version label is different and also the frontend details are missing from the manually built one.

Any ideas ?

**Comment by danxmoran** [comment]
@mnsmithuk it looks like the process you're using to build your image is pulling old UI assets. `make ui/build` in the project root should get you the latest UI, I'd add it to your build process.

**Comment by mnsmithuk** [comment]
Thanks.  That was the problem.
