### ISSUE TITLE
How to export data from database in influxdb to csv using python?

### ISSUE THREAD

**Issue by sudopedia** [influxdata/influxdb#21711]
Hi all, 
So I'm new to the influx environment.
I wrote a python script to create and store values in a database. I'm able to view this db in my influx ctl. Is there any way to export that data in csv format and is it possible to enable the same in my python script?
TIA.

**Comment by wbaker85** [comment]
You should be able to use the python client library to get the results of a flux query as a csv iterator: https://github.com/influxdata/influxdb-client-python#queries

**Comment by wbaker85** [comment]
Closing this based on my reply above!
