### ISSUE TITLE
short write error keeps appearing in 1.8.5 while everything goes well in 1.6.6

### ISSUE THREAD

**Issue by chengshiwen** [influxdata/influxdb#21712]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

I don't know how to reproduce. If a measurement is dropped and a large amount of data of the measurement is written suddenly, it is possible

__Expected behavior:__
Describe what you expected to happen.
Bug fixed

__Actual behavior:__
Describe What actually happened.

![image](https://user-images.githubusercontent.com/4902714/122361185-9871dc00-cf89-11eb-8692-7b82fc3ac5e3.png)
![image](https://user-images.githubusercontent.com/4902714/122360997-6f514b80-cf89-11eb-8f05-9b21aab8aac4.png)
![image](https://user-images.githubusercontent.com/4902714/122361265-aa537f00-cf89-11eb-84ab-af14cc85e55d.png)
![image](https://user-images.githubusercontent.com/4902714/122361272-acb5d900-cf89-11eb-82ce-e91870917024.png)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

InfluxDB 1.8.5, Docker

If I downgrade to 1.6.6, everything goes well

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

```
INFLUXDB_DATA_INDEX_VERSION=tsi1
INFLUXDB_DATA_WAL_FSYNC_DELAY=10ms
```

**Comment by lifeibo** [comment]
It maybe a bug while DropMeasurement.

--- a/tsdb/index/tsi1/log_file.go
+++ b/tsdb/index/tsi1/log_file.go
@@ -1121,8 +1121,6 @@ func (f *LogFile) seriesSketches() (sketch, tSketch estimator.Sketch, err error)
 }

 func (f *LogFile) ExecEntries(entries []LogEntry) error {
-       f.mu.Lock()
-       defer f.mu.Unlock()
        for i := range entries {
                entry := &entries[i]
                if err := f.appendEntry(entry); err != nil {
@@ -1134,6 +1132,9 @@ func (f *LogFile) ExecEntries(entries []LogEntry) error {
 }

 func (f *LogFile) Writes(entries []LogEntry) error {
+       f.mu.Lock()
+       defer f.mu.Unlock()
+
        if err := f.ExecEntries(entries); err != nil {
                return err
        }

	// Flush buffer and sync to disk.
	return f.FlushAndSync()

**Comment by chengshiwen** [comment]
@lifeibo Yes! I did execute `drop measurement` first!

**Comment by altery** [comment]
We also experience these short write errors from time to time. We have to restart influxdb to recover from that situation.

**Comment by altery** [comment]
Is it known, if influxdb 2.x is also affected by this problem?
