### ISSUE TITLE
InfluxDB 2: "influx v1 auth create" ends in authorization not found

### ISSUE THREAD

**Issue by Ogoku** [influxdata/influxdb#21732]
Hi there,

can't create a auth token via V1 API.

```
c:\influxdb>influx v1 auth create --read-bucket 27a172c10690b671 --write-bucket 27a172c10690b671 --username admin
←[36mPlease type your password←[0m:
```

When I insert a password and push enter/return the "Please type your password again" input will be directly skipped and the "Passwords do not match" output is displayed. I can continue this all day until I abort it with ctrl+c.
(And yes, the inputs of the passwords are displayed like this)

```
←[36mPlease type your password again←[0m:

←[31mPasswords do not match.
←[0m←[36mPlease type your password←[0m:

←[36mPlease type your password←[0m:
```

When I run the command I see the following entry in the log:
```
2021-06-22T14:00:17.952961Z     error   api error encountered   {"log_id": "0UtzbGxG000", "error": "authorization not found"}
```

Need help ;)

**Comment by danxmoran** [comment]
Same root cause as #21441 

In this case, you can avoid the bug by passing the `--password` flag to the command over the CLI

**Comment by Ogoku** [comment]
That solved the problem! Thank you.
