### ISSUE TITLE
last() issue in influxdb cloud

### ISSUE THREAD

**Issue by vaibhavsonu** [influxdata/influxdb#21734]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...I have run a query using the last(). As expected it has to send me only 1 result but it is sending me two. As there is no data for 3 days in between.
2. ...
3. ...

__Expected behavior:__
As expected it has to send me only 1 result

__Actual behavior:__
it is sending me two. As there is no data for 3 days in between.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by russorat** [comment]
the `last` function operates per table or group key for flux. my guess here is that you have the "last value for 2 groupings of data" which you can confirm by looking at the `_result` column in the raw data returned. it will have a unique value for each row returned.

consider grouping your data before adding the call to last:

```
 data
 |> group()
 |> last()
```

this will give you a single result, but it might not be what you want if you are selecting multiple series.

**Comment by vaibhavsonu** [comment]
No, I am not grouping data. I am getting 2 values for last from a single table. 
Let me explain to you in detail. I have entered financial data with the stock name as a table. 
I have entered data using pandas till 4th, June. As I have sync data for the next few days. So I sync data agon on 21st June, again using pandas. 

The issue is that when I want to query using last() and range 30d, It is considering data till 4th June(or previously data entered) and 21st June data(new data ) as separate. Query giving me last data enter on 4th June(previous data) and 21st June(new data). 

Hope it is clear now

**Comment by russorat** [comment]
please add the full query and the output so we can take a look.

**Comment by vaibhavsonu** [comment]
from(bucket:"{bucket}") |> range(start:-30d) |> filter(fn: (r) =>  r["_field"] == "{field_close}" and  r["interval"] == "{interval[i]}") |> last()

**Comment by vaibhavsonu** [comment]
> please add the full query and the output so we can take a look.

I am waiting for your reply.

**Comment by russorat** [comment]
@vaibhavsonu what output did you get? and what did you expect to get?

**Comment by vaibhavsonu** [comment]
> @vaibhavsonu what output did you get? and what did you expect to get?

I am expecting only one last value of each measurement but currently I am getting two last value( as I upload data in different dates using pandas)

**Comment by russorat** [comment]
sorry, i need you to post the raw flux response please.

**Comment by vaibhavsonu** [comment]
> sorry, i need you to post the raw flux response please.

See I am getting 2 results for the same measurement. 


{'result': '_result', 'table': 710, '_start': datetime.datetime(2021, 6, 13, 5, 31, 31, 305578, tzinfo=tzutc()), '_stop': datetime.datetime(2021, 7, 13, 5, 31, 31, 305578, tzinfo=tzutc()), '**_time': datetime.datetime(2021, 6, 6, 6, 45, tzinfo=tzutc())**, '_value': 61.95, '_field': 'close', '_measurement': 'GINISILK', 'exchange': 'BSE', 'interval': '5minute', 'listing_date': 'nan'}

{'result': '_result', 'table': 711, '_start': datetime.datetime(2021, 6, 13, 5, 31, 31, 305578, tzinfo=tzutc()), '_stop': datetime.datetime(2021, 7, 13, 5, 31, 31, 305578, tzinfo=tzutc()), '**_time': datetime.datetime(2021, 6, 22, 6, 35, tzinfo=tzutc())**, '_value': 59.95, '_field': 'close', '_measurement': 'GINISILK', 'exchange': 'BSE', 'interval': '5minute', 'listing_date': 'nan'}

**Comment by russorat** [comment]
@vaibhavsonu thanks!

notice that the `table` column is different in your results (710 vs 711). The `last` function operates per table, so because your data is coming back as two different tables, you get the last value of each table, in this case two.

if you truly wanted the last value for a specific measurement, you should try the following:

```
from(bucket:"{bucket}") 
  |> range(start:-30d) 
  |> filter(fn: (r) => r["_field"] == "{field_close}" and r["interval"] == "{interval[i]}")
  |> group(columns: ["_measurement"])
  |> last()
```

i recommend reading https://docs.influxdata.com/influxdb/v2.0/query-data/flux/group-data/ for more information about how grouping works in Flux.

**Comment by vaibhavsonu** [comment]
> @vaibhavsonu thanks!
> 
> notice that the `table` column is different in your results (710 vs 711). The `last` function operates per table, so because your data is coming back as two different tables, you get the last value of each table, in this case two.
> 
> if you truly wanted the last value for a specific measurement, you should try the following:
> 
> ```
> from(bucket:"{bucket}") 
>   |> range(start:-30d) 
>   |> filter(fn: (r) => r["_field"] == "{field_close}" and r["interval"] == "{interval[i]}")
>   |> group(columns: ["_measurement"])
>   |> last()
> ```
> 
> i recommend reading https://docs.influxdata.com/influxdb/v2.0/query-data/flux/group-data/ for more information about how grouping works in Flux.
> 

But why it is coming as two different table when measurement name is same.

Doesn't it increase usage or bill?

**Comment by russorat** [comment]
seems like you might be doing some processing of the results prior to what you posted via a client library or something.

i suggest taking your raw query with the values filled in and running them either in our web UI and viewing the raw data or via the cli using the `influx query` command with the `--raw` flag and seeing the results. That might help you figure out what tag is different across your data: 

![image](https://user-images.githubusercontent.com/4805997/125492766-caea47d8-4da6-4108-9267-2cf2248761c5.png)

**Comment by vaibhavsonu** [comment]
> seems like you might be doing some processing of the results prior to what you posted via a client library or something.
> 
> i suggest taking your raw query with the values filled in and running them either in our web UI and viewing the raw data or via the cli using the `influx query` command with the `--raw` flag and seeing the results. That might help you figure out what tag is different across your data: 
> 
> ![image](https://user-images.githubusercontent.com/4805997/125492766-caea47d8-4da6-4108-9267-2cf2248761c5.png)
> 
> 

OK thanks

**Comment by timhallinflux** [comment]
@vaibhavsonu ok to close this?

your query returns 2 series... grouping all results by measurement collapses the results into a 1 table...which then you extract last.

**Comment by vaibhavsonu** [comment]
> @vaibhavsonu ok to close this?
> 
> your query returns 2 series... grouping all results by measurement collapses the results into a 1 table...which then you extract last. 

Yes definitely close it.. I have already solved issue by that approach.
Thanks.

**Comment by yang953** [comment]
i have the same issue
![image](https://user-images.githubusercontent.com/43697164/172079221-01fee8e3-19eb-4301-a781-27b983449728.png)
