### ISSUE TITLE
Add tag parameter in schema.measurements() function

### ISSUE THREAD

**Issue by mwaldmueller** [influxdata/influxdb#21744]
__Proposal:__
Allow searching for tags in schema.measurements() function (https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/measurements/)

__Current behavior:__
Unable to search for specific tags in schema.measurements() function

Version: InfluxDB 2.0.7

**Comment by russorat** [comment]
There are other functions in the schema package that allow you to search for tags: https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/

You can also see the function definitions in the docs if you want to explore different ways to solve your use case with flux: https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/tagkeys/#function-definition

**Comment by mwaldmueller** [comment]
Thanks for your answer!

I solved it with:

> from(bucket: "icinga")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
|> filter(fn: (r) => r.hostname == "agent.example.com"
)
|> keyValues(keyColumns: ["_measurement"])
|> group()
|> keep(columns: ["_measurement"])
|> distinct(column: "_measurement")
