### ISSUE TITLE
Unable to delete data-points

### ISSUE THREAD

**Issue by Shadow505** [influxdata/influxdb#21753]
I am unable to delete data-points. 

It appears that there are issues when using a custom field in `predicate`  (issue #20399), but even without it, I am unable to delete the data. 

It always shows:  **Error: Failed to delete data: Not implemented.**

I tried:

`influx delete --org myOrg --bucket sensors --start '2021-06-20T18:56:00Z' --stop '2021-06-25T19:04:00Z' --predicate '_measurement="temp" AND device="d1"' --host https://localhost:8086 --skip-verify -t xyz`
	
`influx delete --org myOrg --bucket sensors --start '2021-06-20T18:56:00Z' --stop '2021-06-25T19:04:00Z' --predicate '_measurement="temp"' --host https://localhost:8086 --skip-verify -t xyz`
  
`influx delete --org myOrg --bucket sensors --start '2021-06-20T18:56:00Z' --stop '2021-06-25T19:04:00Z' --host https://localhost:8086 --skip-verify -t xyz`

Influx version: 2.0.7

This is a major issue.

Is there something wrong with my query or is this in fact not implemented?

**Comment by danxmoran** [comment]
@Shadow505 can you confirm that the `version` key in the JSON object returned by this command is `2.0.7`?
```
curl -k https://localhost:8086/health
```
A blanket "Not implemented" response was returned by the delete API in early 2.0.x releases. I wouldn't expect you to ever hit it on newer versions.

**Comment by Shadow505** [comment]
@danxmoran Yes, it indeed return 2.0.7.

`{"name":"influxdb", "message":"ready for queries and writes", "status":"pass", "checks":[], "version": "2.0.7", "commit": "2a45f0c037"}`

**Comment by danxmoran** [comment]
@Shadow505 thank you for confirming, I'm sorry you're hitting this strange behavior... can you restart your `influxd` process with `--log-level debug`? Nothing comes to mind for what you might be hitting on the server-side, I'm hoping we can get some clues from the logs there.

**Comment by Shadow505** [comment]
@danxmoran 

I have attached the log output.

[influxdb.log](https://github.com/influxdata/influxdb/files/6735529/influxdb.log)

**Comment by danxmoran** [comment]
@Shadow505 did you try re-running the `delete` commands when the server was booted with debug logging? Looking through the logs you sent I don't see any HTTP request/response lines, which I would expect to see if the server was receiving the requests from the CLI

**Comment by Shadow505** [comment]
No, you have not told me to do so :P

I just tried and.. Oddly enough, it works now.. Not sure why that is. I ran the health command again and it outputting exactly the same as before. Strange.. But at least it works now

**Comment by danxmoran** [comment]
Yes, I should have been more specific the first time around 😄 glad to hear it's working, though agreed it's strange...

I'm going to close this for now, but feel free to comment if you start seeing the problem again and I'll reopen it.

**Comment by Shadow505** [comment]
Thanks, will do! :)
