### ISSUE TITLE
query on Boolean fields got no data!

### ISSUE THREAD

**Issue by aerosadegh** [influxdata/influxdb#21770]
__Steps to reproduce:__

1. Write some fields in type of integer, float, and **boolean** in a measurement.
2. Query on measurement like this:
```
from(bucket: "pt")
  |> range(start: 2021-06-26T04:08:39Z, stop: 2021-06-26T16:21:13Z)
  |> filter(fn: (r) => r["_measurement"] == "zn")
  |> filter(fn: (r) => r["_field"] =~ /(BTTI1_2A|Hyd_Rtch1_88HR_CMD_OFF)/)
  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)
  |> drop(columns: ["_start", "_stop", "_measurement"])
```
that
- BTTI1_2A is float
- Hyd_Rtch1_88HR_CMD_OFF is bool
I use Influxdb_client(python) for inject data.

Note: List of fields got in query like this:
```
import "influxdata/influxdb/schema"
schema.measurementFieldKeys(bucket: "pt", measurement: "zn")
```

__Expected behavior:__
according to each field has a value, I Expected to get some result for each of them, but result only contain float/int fields and got no result for bool field.

__Actual behavior:__
I got only float field in the result:
![image](https://user-images.githubusercontent.com/5039032/124063475-35cc1600-da48-11eb-8d39-58510adc56c2.png)

__Environment info:__

* System info: Linux 3.10.0-1160.25.1.el7.x86_64 x86_64 (Docker Container)
* InfluxDB 2.0.6 (git: 4db98b4c9a) build_date: 2021-04-29T16:48:12Z

__Config:__
Default Config

**Comment by russorat** [comment]
could you post the raw flux response from the query that is missing the bool values? otherwise, i'm inclined to think this is an issue with how the grafana cell is configured.

**Comment by aerosadegh** [comment]
> could you post the raw flux response from the query that is missing the bool values? otherwise, i'm inclined to think this is an issue with how the grafana cell is configured.

I got the same result in the influxdb Data Explorer. My first attempt was in that tool.
Additionally, Boolean fields are not displayed in the `_field` filter (in the Query Builder), but the list of fields (include Boolean) is displayed in the query below:

```
import "influxdata/influxdb/schema"
schema.measurementFieldKeys(bucket: "pt", measurement: "zn")
```

Did that mean this field is empty?
When I injected data into the InfluxDB there was no error.

**Comment by russorat** [comment]
@aerosadegh the data in the query builder are limited by time, so it could be that the boolean data is for an older timestamp than the other fields.

what do you see when you run something like this in the data explorer script editor?

```
from(bucket: "pt") |> range(start: 0) |> filter(fn: (r) => r._measurement == "zn")
```

**Comment by aerosadegh** [comment]
> @aerosadegh the data in the query builder are limited by time, so it could be that the boolean data is for an older timestamp than the other fields.
> 
> what do you see when you run something like this in the data explorer script editor?
> 
> ```
> from(bucket: "pt") |> range(start: 0) |> filter(fn: (r) => r._measurement == "zn")
> ```

Thank You. I found my problem.
My injector has an error and injected only 1 point for boolean fields.

The InfluxDB has No Problem! 👍
