### ISSUE TITLE
New Task: every "week" does not work

### ISSUE THREAD

**Issue by Herr-Sepp** [influxdata/influxdb#21842]
**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Create Task
2. Set "every" to "1w"
3. Save

**Expected behavior:**
Task is saved

**Actual behavior:**
Failed to create new task: failed to create task: error in parsing at char 6, ''
![image](https://user-images.githubusercontent.com/10489458/125453365-35d525f9-1411-4553-b948-267d1b922d5b.png)

**Environment info:**

- System info: Ubuntu 20.04 LTS
- InfluxDB version: 2.0.7
- Other relevant environment details: Docker

**Comment by wbaker85** [comment]
Transferred this to `influxdb` since it is a backend problem.
