### ISSUE TITLE
Task Scheduler Test Failing on Intervals > 1hr Due to DST

### ISSUE THREAD

**Issue by wbaker85** [influxdata/influxdb#21883]
On certain architectures (MacOS), the test `TestSchedule_Next/@every_fires_on_appropriate_boundaries` started to fail recently. This is due to differences in time being calculated based on local time rather than UTC. Linux does time comparisons based on UTC so the test was not failing in our Linux CI environment, but on Mac the time difference is apparently calculated from local time, which was causing a discrepency for the `@1 week` interval.

The test code initializes a mock schedule using `time.Now()` - a fix for this would be to use a fixed time which does not include a DST change in the 16 week time window that the tasks are triggered during the test.

**Comment by davidby-influx** [comment]
Saw this on my Linux machine, as well...
