### ISSUE TITLE
SHOW TAG VALUES not respecting WHERE clause time predicate

### ISSUE THREAD

**Issue by abalone23** [influxdata/influxdb#21984]
Query tests show `SHOW TAG VALUES` statement with time predicate in WHERE clause:
https://github.com/influxdata/influxdb/blob/540bb66e1381a48a6d1ede4fc3e49c75a7d9f4af/influxql/query/statement_rewriter_test.go#L264

__Expected behavior:__
`SHOW TAG VALUES` should only return tag values that exist within the specified time range.

__Actual behavior:__
All tag values from database are returned.

**Reproduction**
```
> create database tagtest
> use tagtest
Using database tagtest
>INSERT m1,country=US id=1
 // Wait 2 minutes
>INSERT m1,country=MX id=2
> show tag values on tagtest with key="country" where time > now() - 1m
```
It should only return `country MX` but it returns all tag values:
```
name: m1
key     value
---     -----
country MX
country US
```

**Comment by davidby-influx** [comment]
Possible cause, @abalone23:
https://docs.influxdata.com/enterprise_influxdb/v1.9/query_language/explore-schema/#filter-meta-queries-by-time

Can you check the shards being queried underneath?

**Comment by abalone23** [comment]
Thanks @davidby-influx, I confirmed it works as described above by adding a new value to the `hosts` tag to a point in the `disk` measurement in the `telegraf` database:
```
> INSERT disk,host=blah used_percent=8.8
```

I checked that the latest shard started yesterday:
```
25  telegraf   autogen           2                 15           2021-07-26T00:00:00Z  2021-08-02T00:00:00Z                        [{ID:4 TCPAddr:data3:8088} {ID:5 TCPAddr:data4:8088}]
34  telegraf   autogen           2                 21           2021-08-02T00:00:00Z  2021-08-09T00:00:00Z                        [{ID:4 TCPAddr:data3:8088} {ID:5 TCPAddr:data4:8088}]
```

The following InfluxQL query with a time predicate older than 2 days doesn't show the new tag value:
```
> show tag values on "telegraf" from disk with key="host" where time < now() - 2d
name: disk
key  value
---  -----
host data3
host data4
```

Removing the time predicate displays all tag values:
```
> show tag values on "telegraf" from disk with key="host"
name: disk
key  value
---  -----
host blah
host data3
host data4
```

**Comment by davidby-influx** [comment]
@abalone23 - Do you want to close this, or do you want to put it in as an enhancement request? I don't know what the priority of the latter would be.
