### ISSUE TITLE
tagValues doesn't behave like its given function definition

### ISSUE THREAD

**Issue by Beetix** [influxdata/influxdb#22063]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Using builtin function
```import "influxdata/influxdb/schema"

schema.tagValues(
  bucket: "mybucket",
  tag: "mytag",
  predicate: (r) => r._measurement == "mymeasurement",
  start: -1h
)
```
2. Using function definition
```
from(bucket: "mybucket")
    |> range(start: -1h)
    |> filter(fn: (r) => r._measurement == "mymeasurement")
    |> group(columns: ["mytag"])
    |> distinct(column: "mytag")
    |> keep(columns: ["_value"])
```

__Expected behavior:__
Same output from both command.

__Actual behavior:__

- The builtin returns values that does not match the start specified (no actual entry with the given tag in the last hour)
- The function definition fails with the error `distinct: schema collision: cannot group float and string types together` apparently because my measurement has a field which is a string and the other are floats. The things is I don't care about the fields, I only want the tags...

__Environment info:__

* System info: Linux 4.19.0-12-amd64 x86_64
* InfluxDB version: InfluxDB 2.0.6 (git: 4db98b4c9a) build_date: 2021-04-29T16:48:12Z

**Comment by sanderson** [comment]
@Beetix The definition of the `tagValues()` function changed to take advantage of newly added [pushdown optimizations](https://docs.influxdata.com/influxdb/v2.0/query-data/optimize-queries/#start-queries-with-pushdowns). This is the current definition:

```js
tagValues = (bucket, tag, predicate=(r) => true, start=-30d) => from(bucket: bucket)
    |> range(start: start)
    |> filter(fn: predicate)
    |> keep(columns: [tag])
    |> group()
    |> distinct(column: tag)
```

Because `keep` comes before `group()`, you drop the `_value` column before grouping and there is no schema collisions.

I'll update the documentation to show the updated definition for this function.

**Comment by Beetix** [comment]
> ```js
> from(bucket: bucket)
>     |> range(start: start)
>     |> filter(fn: predicate)
>     |> keep(columns: [tag])
>     |> group()
>     |> distinct(column: tag)
> ```

Thanks! I can confirm that I get the same behaviour with the function you gave.

I still have an issue with the start. There has been no recording I the last hour but I am still getting tags in the query result. Should I open another issue?
