### ISSUE TITLE
Replace use of InfluxQL transpiler with native execution in `/api/v2/query`

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#22143]
Currently:
* Requests to `/api/v2/query` with `type: influxql` get transpiled to flux and executed on the flux controller
* Requests to `/query` are executed natively using a copy/port of the engine from 1.8

The transpiler is known to be buggy, and has worse performance than native execution. Refactor the logic in the `/api/v2/query` handler to reuse the native influxql engine, and delete the transpilation code.

**Comment by lesam** [comment]
The transpiler has since been deleted, closing.
