### ISSUE TITLE
Investigate flux vs. influxql performance with multiple measurement filters

### ISSUE THREAD

**Issue by wbaker85** [influxdata/influxdb#22156]
In https://www.reddit.com/r/influxdb/comments/mq08og/upgrading_influxdb_from_v1x_to_v2x_is_it_even/, it was noted that flux queries are much slower than influxql when there is an OR condition in the filter statement. There aren't any more specifics available, but it should be possible to use our existing benchmark dataset and design a query (or use an existing query) to determine if this is still an issue.

**Comment by wbaker85** [comment]
Thanks for the detailed information @markkvdb! This will really help me set up some benchmarks. Quick follow-up question: Does your data include any tags? Or is it just the measurement names and fields that you mentioned?

**Comment by markkvdb** [comment]
> Thanks for the detailed information @markkvdb! This will really help me set up some benchmarks. Quick follow-up question: Does your data include any tags? Or is it just the measurement names and fields that you mentioned?

There are no tags in this database. The measurements are coordinates and the fields are time series for these coordinates.

**Comment by wbaker85** [comment]
Thanks for the additional info @markkvdb. I've been able to reproduce this locally and am looking into an optimization.

**Comment by wbaker85** [comment]
Also related: https://community.influxdata.com/t/why-this-multiple-measurements-query-needs-10-seconds/21541
