### ISSUE TITLE
Extend replication-stream APIs to set up a durable queue

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#22168]
Extend the implementation from #22167 to include this logic:

When the server processes a replication-stream creation request, it should:
1. Initialize a durable queue with the requested size
2. Start running a scanner on the queue to write points to the requested remote instance
3. Save the stream's metadata to sqlite

When the server processes a deletion request, it should:
1. Close the stream's durable queue
2. Delete the stream's metadata from sqlite
3. Delete any enqueued, un-flushed data for the queue on disk

When the server processes an update request, it should:
1. Check if the max queue size has changed. If so, update the durable queue with the new size
2. Check if the connection details for the target bucket have changed. If so, update the queue's remote-writer with the new info.
3. Update the stream's metadata in sqlite

**Note:** Steps above related to the scanner/request writer have been split into a separate issue due to complexity. See #22733 for this new issue

**Comment by lesam** [comment]
How many queues do we intend to be setting up? One per replication destination? One per bucket?

**Comment by dgnorton** [comment]
I think `dir` should be configurable, with a default like @lesam described. Some users will be replicating a lot of data and may need the option to locate it separately.

**Comment by mcfarlm3** [comment]
> @dgnorton @mcfarlm3 - If we allowed configuration of WAL and TSM write locations separately I'd probably agree that replication should be configurable as well. But as is, there's only one knob to configure where 'heavy disk usage stuff' lives at the moment (the 'engine' directory location is configurable), and it seems like replication streams should fit into that pattern.

I'll go ahead with default path only then (non-configurable for now), unless you have strong objections @dgnorton?
