### ISSUE TITLE
UI hasn't been updated to 2.0.8

### ISSUE THREAD

**Issue by szerwi** [influxdata/influxdb#22210]
I have just made an update of InfluxDB from 2.0.7 to 2.0.8 version using apt (```apt-get install influxdb2```)
I have noticed that UI hasn't got updated to 2.0.8 and it is still on 2.0.7 version.
```influx version``` command result:
```
Influx CLI 2.0.8 (git: e91d41810f) build_date: 2021-08-13T18:22:30Z
```
UI version:
![image](https://user-images.githubusercontent.com/19311511/129452688-4a1fc758-b85f-4a83-abc7-15234bb6f212.png)

I have also tried to disable UI in ```/etc/influxdb/config.toml``` by putting ```ui-disabled = true``` at the end of the file but it did not worked. I believe it is because the UI is still on 2.0.7 version.

__Environment info:__

```Linux 5.4.0-1041-raspi aarch64```

**Comment by wbaker85** [comment]
What is your output from `influxd version`? The version number displayed on the login page is dynamically reported from the `influxd` server, and the `ui-disabled` flag is also independent of the static UI files, so it looks like your `influxd` is still running 2.0.7.

**Comment by szerwi** [comment]
@wbaker85 ```influxd version``` also shows 2.0.8:
```InfluxDB 2.0.8 (git: e91d41810f) build_date: 2021-08-13T18:22:30Z```

When I run ```apt-get install influxdb2``` again it shows that Influxdb 2.0.8 is already the newest version.

**Comment by danxmoran** [comment]
@szerwi double-checking: did you restart the influxd process/service after upgrading the package & changing the config?

**Comment by szerwi** [comment]
@danxmoran Yes, I restarted the influxd process. To be completly sure I also restarted the whole system, but the UI was still on 2.0.7 version.

**Comment by danxmoran** [comment]
I think this might be a problem with caching on the browser side... I just saw the same behavior when testing the Homebrew formula for 2.0.8, but if I viewed the page in a new incognito window then the UI displayed the correct version & commit.

**Comment by szerwi** [comment]
@danxmoran You're right, on icognito mode there is a 2.0.8 version! However, I am pretty sure that I've checked the incognito mode before posting the issue and it hadn't worked that time.
Maybe it is worth changing the behaviour so the browser won't cache that much of the page (Although I'm not sure if it's possible from the InfluxDB's side)?

**Comment by wbaker85** [comment]
@szerwi if you log out via the UI the version number should update as well. The number is cached in the browser local storage, so the UI doesn’t ask the server for the version number every time. I’ll look into changing that caching behavior to avoid this situation in the future.
