### ISSUE TITLE
csv encoder error & broken pipe

### ISSUE THREAD

**Issue by benberlin7** [influxdata/influxdb#22212]
Getting _broken pipe_ and _csv encoder error_ when trying to transmit data to the docker influx db.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Start influxDB via Docker via http://localhost:8086
2. Initialize influxDB client in VisualStudio/C# via
```
var influxOptions = InfluxDBClientOptions.Builder.CreateNew().Url(url).Org(org).Bucket(bucket).AuthenticateToken(Token).LogLevel(InfluxDB.Client.Core.LogLevel.None).Build();
                var influxDBClient = InfluxDBClientFactory.Create(influxOptions);
```

3. Try to write data to the database via 
`                            const string data = "mem,host=host1 used_percent=13.43234543";
                            using (var writeApi = influxDBClient.GetWriteApi())
                            {
                                writeApi.WriteRecord(bucket, org, WritePrecision.Ns, data);
                            }`

__Expected behavior:__
successful data transmission

__Actual behavior:__
See Docker logs with Error message : lvl=info msg="Error writing response to client" log_id=0VztEJpl000 handler=flux error="csv encoder error: write tcp X.X.X.X:8086->X.X.X.X:42344: write: broken pipe"

No new datapoints in the browser-ui seeable

__Environment info:__

win10 
InfluxDB 2.0.7
VS: influxdbclient v 2.0.0
VS: influxdbclient.core v 2.0.0

**Comment by danxmoran** [comment]
@benberlin7 the log you've provided is from the query API, not the write API. Are you getting unsuccessful HTTP status codes back from your write requests?

I suspect the `write: broken pipe` errors you're seeing are from the UI's queries, and that's why you aren't seeing any data.
