### ISSUE TITLE
InfluxDB - create database via CURL command is failing

### ISSUE THREAD

**Issue by 100josearun** [influxdata/influxdb#22255]
Hi Team,

I'm trying to setup InfluxDB - **2.0.8** using Docker image. I was able to spin-up InfluxDB but not able to create database using following CURl command.

**CURL command:**

```
curl -i -XPOST http://localhost:8086/query --header "Authorization: Token MY_INFLUX_TOKEN" --data-urlencode "q=CREATE DATABASE selenium"
```
**Error:**
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 18 Aug 2021 17:41:43 GMT
Content-Length: 76

{"results":[{"statement_id":0,"error":"not implemented: CREATE DATABASE"}]}
```

How to resolve this error?

**Comment by sanderson** [comment]
@100josearun InfluxDB 2.0 does not support creating a database from a query. "Databases" and "retention policies" have been replaced by "buckets." The following link provides information about creating a bucket:

- [Create a bucket](https://docs.influxdata.com/influxdb/v2.0/organizations/buckets/create-bucket/)

You can use InfluxQL to query data from InfluxDB 2.0, but InfluxQL is read-only (mostly) in 2.0, so you can't perform any administrative tasks like creating databases (buckets) or managing users. InfluxQL in 2.o also requires a bit of setup. Here are some links related to InfluxDB that may help:

- [Query data with InfluxQL](https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/)
- [/query 1.x compatiblity API](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/query/)
