### ISSUE TITLE
/api/v2/authorizations/?user query parameter does not filter authorizations

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/influxdb#22261]
__Steps to reproduce:__
1. Add a user, .e.g. username = "myusername".
2. Add authorizations for the user.
3. Repeat for additional users.
4. Send a GET request with `?user=myusername` to the http://localhost:8086/api/v2/authorizations/ [endpoint](https://docs.influxdata.com/influxdb/v2.0/api/#operation/GetAuthorizations). 

__Expected behavior:__
According to the [API docs](https://docs.influxdata.com/influxdb/v2.0/api/#operation/GetAuthorizations) and [authorization/http_client.go](https://github.com/influxdata/influxdb/blob/master/authorization/http_client.go#L43),  queryparameter `user` should filter authorizations to only myusername's auths.

__Actual behavior:__
The API returns all authorizations without filtering. See attached curl request and response.
[api-v2-user-auths.log](https://github.com/influxdata/influxdb/files/7015800/api-v2-user-auths.log)

__Environment info:__

* System info: Run `uname -srm` and copy the output here

> Darwin 20.6.0 x86_64

* InfluxDB version: Run `influxd version` and copy the output here

> InfluxDB 2.0.8 (git: e91d41810f) build_date: 2021-08-13T17:55:41Z

**Comment by wbaker85** [comment]
I was able to reproduce this...seems that using a string for `user` doesn't apply any filters, but providing a `userID` parameter does work. Similarly, `org` as a string does not work, but `orgID` does.
