### ISSUE TITLE
Race condition(s) in TSI

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#22337]
Now that compaction runs periodically in TSI, we've found a few race conditions. For example, in these cases the `RLock()` calls should probably be `Lock()` calls, otherwise we can modify the TSL `modTime` at the same time that periodic compaction is reading it:
* [DeleteMeasurement](https://github.com/influxdata/influxdb/blob/master-1.x/tsdb/index/tsi1/partition.go#L661)
* [DropSeries](https://github.com/influxdata/influxdb/blob/master-1.x/tsdb/index/tsi1/partition.go#L679)
* [DropSeriesList](https://github.com/influxdata/influxdb/blob/master-1.x/tsdb/index/tsi1/partition.go#L692)

There might be other cases in `partition.go`, these are just the few that jumped out at me as I was debugging.

**Comment by lesam** [comment]
See race detected in https://app.circleci.com/pipelines/github/influxdata/influxdb/23432/workflows/c6283e97-8a98-46e3-9786-79afc20bc165/jobs/209701
