### ISSUE TITLE
Install InfluxDB as a service with systemd

### ISSUE THREAD

**Issue by mriepe-lab** [influxdata/influxdb#22383]
I'm unable to download influxdb2-2.0.8-linux-amd64.deb

ubuntu@ubuntu:/tmp$ wget https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.8-linux-amd64.deb
--2021-09-03 01:55:24--  https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.8-linux-amd64.deb
Resolving dl.influxdata.com (dl.influxdata.com)... 13.226.101.92, 13.226.101.63, 13.226.101.129, ...
Connecting to dl.influxdata.com (dl.influxdata.com)|13.226.101.92|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-03 01:55:25 ERROR 404: Not Found.

I get an error message 
HTTP request sent, awaiting response... 404 Not Found
2021-09-03 01:55:25 ERROR 404: Not Found.

**Comment by nsteinmetz** [comment]
Correct link is:

```
https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.8-amd64.deb
```

**Comment by Houssem12-ai** [comment]
@nsteinmetz  thank you for proving this correct link:  https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.8-amd64.deb
The issue is that the link provided in the documentation is incorrect, how can we manage to correct it ?

**Comment by jeffreyssmith2nd** [comment]
Closing this in favor of #24008
