### ISSUE TITLE
Bug in `schema.tagValues` function

### ISSUE THREAD

**Issue by peske** [influxdata/influxdb#22385]
__Steps to reproduce:__

The bug is actually very easy to understand and reproduce. (Actual measurement names are not important.)

When I execute:

```
import "influxdata/influxdb/schema" 
schema.tagValues(bucket: "raw", tag: "exchange", predicate: (r) => (r._measurement == "TRADE") and (r.category == "SPOT"))
```

I'm getting certain number (greater than zero) results. But when I add just one more condition **with OR operator**, and execute:

```
schema.tagValues(bucket: "raw", tag: "exchange", predicate: (r) => (r._measurement == "TRADE") and (r._measurement == "GLOBAL_VOLUME" or r.category == "SPOT"))
```

I'm getting zero results. This doesn't make sense because the new condition is added **with OR operator**, meaning that even it is false, it should not have any effect (`x or false == x`)

Note: one may ask why I need to add such obviously false condition, and why I have few extra parentheses - the answer is that this query is dynamically generated in code, thus looking bit weird, but still it's a valid query.

__Expected behavior:__

The second query should return **at least the same number of results** as the first one, because the first one is simply more restrictive.

__Actual behavior:__

Explained above.

__Environment info:__

* System info: `Linux 5.11.0-27-generic x86_64`
* InfluxDB version: `InfluxDB 2.0.8 (git: e91d41810f) build_date: 2021-08-13T18:22:30Z`
* Other relevant environment details: Official image from Docker Hub, `influxdb:2.0.8`

__Config:__

N/A

__Additional info:__

The following three queries all return the same number of results (greater than zero):

```
schema.tagValues(bucket: "raw", tag: "exchange", predicate: (r) => (r._measurement == "TRADE") and (r.category == "SPOT"))
schema.tagValues(bucket: "raw", tag: "exchange", predicate: (r) => (r._measurement == "TRADE") and (r.anything == "OTHER_ANYTHING" or r.category == "SPOT"))
schema.tagValues(bucket: "raw", tag: "exchange", predicate: (r) => (r._measurement == "TRADE") and (false or r.category == "SPOT"))
```

The query that fails (that returns no results) is:

```
schema.tagValues(bucket: "raw", tag: "exchange", predicate: (r) => (r._measurement == "TRADE") and (r._measurement == "GLOBAL_VOLUME" or r.category == "SPOT"))
```

This indicates that only condition with **`r._measurement`** causes problems, so you're probably treating it differently (and wrongly).

**Comment by wbaker85** [comment]
I reproduced this locally using a bucket called "bucket" and by creating a scraper to populate some data.

The following two queries are equivalent and illustrate the behavior you saw:
```javascript
import "influxdata/influxdb/schema" 
schema.tagValues(
    bucket: "bucket",
        tag: "status", 
        predicate: (r) => (r._measurement == "http_api_request_duration_seconds") and (r._measurement == "anythingElse" or r.method == "GET")
    )
```
```javascript
from(bucket: "bucket") 
    |> range(start: 0) 
    |> filter(fn: (r) => (r["_measurement"] == "http_api_request_duration_seconds"))
    |> filter(fn: (r) => (r["_measurement"] == "anythingElse" or r["method"] == "GET"))
    |> keep(columns: ["status"])
    |> group()
    |> distinct(column: "status")
    |> limit(n: 200)
    |> sort()
```

The AST for this query is shown below. `Op 27` means "and", `Op 28` means "or", and `Op 29` means "equal".

```json
{
	"Op": 27,
	"LHS": {
		"Op": 29,
		"LHS": {
			"Val": "_tagKey",
			"Type": 0
		},
		"RHS": {
			"Val": "status"
		}
	},
	"RHS": {
		"Expr": {
			"Op": 27,
			"LHS": {
				"Op": 29,
				"LHS": {
					"Val": "_name",
					"Type": 7
				},
				"RHS": {
					"Val": "http_api_request_duration_seconds"
				}
			},
			"RHS": {
				"Op": 28,
				"LHS": {
					"Op": 29,
					"LHS": {
						"Val": "_name",
						"Type": 7
					},
					"RHS": {
						"Val": "anythingElse"
					}
				},
				"RHS": {
					"Op": 29,
					"LHS": {
						"Val": "method",
						"Type": 7
					},
					"RHS": {
						"Val": "GET"
					}
				}
			}
		}
	}
}
```

This gets reduced to the following [here](https://github.com/influxdata/influxdb/blob/279c23a0c62f7fbdf65499e8345b3258c969d4c7/tsdb/store.go#L1694-L1706):

```json
{
	"Op": 27,
	"LHS": {
		"Op": 29,
		"LHS": {
			"Val": "_name",
			"Type": 7
		},
		"RHS": {
			"Val": "http_api_request_duration_seconds"
		}
	},
	"RHS": {
		"Op": 29,
		"LHS": {
			"Val": "_name",
			"Type": 7
		},
		"RHS": {
			"Val": "anythingElse"
		}
	}
}
```

The reduction, which basically removes everything but measurement names for the purpose of getting a list of measurement names from the index, ends up simplifying the expression incorrectly to something like `_measurement = "http_api_request_duration_seconds" AND _measurement = "anythingElse"`

To fix this, I think we'll need to modify the code path used by the Flux pushdown to utilize something more along the lines of [this](https://github.com/influxdata/influxdb/blob/279c23a0c62f7fbdf65499e8345b3258c969d4c7/tsdb/shard.go#L808) to properly handle getting measurement names by a flux predicate. This kind of query is not possible in InfluxQL so using the InfluxQL code path results in the wrong answer as it is currently.

Also we should be able to use the same algorithm as in https://github.com/influxdata/influxdb/pull/22301 to efficiently get the appropriate measurement names via static analysis of the query when possible to avoid using the slower `MeasurementNamesByPredicate` method unless absolutely necessary.
