### ISSUE TITLE
[2.0.x OSS] Dashboards > Shared cross-hair is missing 

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/influxdb#22386]
With chronograf, on a dashboard, you could define a point in a chart and see the same point in all other charts. Which would ease correlation and/or debug.

Seems it no longer exists in 2.x

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open a dashboard in chronograf
2. Open same dashboard in InfluxDB 2.0.x
3. Select a point in time in a given cell

__Expected behavior:__

On a given cell, when I select a point in time, a white line show the same point in all other cells

<img width="1440" alt="Capture d’écran 2021-09-03 à 16 57 08" src="https://user-images.githubusercontent.com/33180/132027449-defca18a-e877-48e0-b0ec-ba7e818602c5.png">

__Actual behavior:__

The line is visible only for the given cell

<img width="1440" alt="Capture d’écran 2021-09-03 à 16 58 32" src="https://user-images.githubusercontent.com/33180/132027458-026801af-1763-4752-91d2-0a1bfe00ce9d.png">

__Environment info:__

* InfluxDB version:  2.0.8 OSS

**Comment by wbaker85** [comment]
I'm not sure if there is anything in the works for this as a feature for the 2.x UI, but I've tagged it under `area/ui` so it can be considered if not!

**Comment by TCL735** [comment]
While a shared crosshair is indeed a feature, we're going to convert this to a bug and address the issue of having a single crosshair in individual cells, which should already be available. The bug is that the crosshair in individual cells is not visible.

**Comment by nsteinmetz** [comment]
You have it more or less once "shaded" feature  is enabled.

So there are 2 bugs and therefore there should be 2 issues (and not the original issue changed for what you aim to fix):
* one issue for shared cross-hair missing
* one issue visibility improvements for a single cross-hair

This issue is for the former.

**Comment by NonLogicalDev** [comment]
This seems to be the same underlying issue/request as #16612 which has not seen an update in a while.
I hope that this feature will eventually be implemented as cross-correlating events is very difficult without it.

**Comment by kristinarobinson** [comment]
Closing bug with PR https://app.zenhub.com/workspace/o/influxdata/giraffe/issues/674.  Enhancement to be tracked as https://github.com/influxdata/influxdb/issues/16612.
