### ISSUE TITLE
Allow HTTPS scrapers

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb#22512]
When creating a new scraper with `https://` prefix in the UI, an error is displayed:

    Target url must begin with "http://"

IMHO there is no reason not to allow https here?

**Comment by wbaker85** [comment]
The error message is misleading, but the logic is there that should allow for `https://` scrapers to be created: https://github.com/influxdata/ui/blob/2b5db102af95048107611b52c2ea3e4e6a083ec5/src/scrapers/components/CreateScraperForm.tsx#L132-L145

I was able to create a scraper starting with `https://` successfully on influxdb version 2.0.8. The URL checking is pretty crude and just verifies that it starts with either `http://` or `https://` - if it doesn't start with either of those, the message `Target url must begin with "http://"` is displayed.

I can see that when you start typing a URL into the box it will display the error message until you get to the point of having fully entered `http://` or `https://`. If you enter `https://` into the input, are you still seeing the error message? I will definitely update the error message to be more accurate, but just want to confirm if you are still seeing the error even after inputing `https://` fully.

**Comment by andig** [comment]
Thank you confirmed. The error message got me side-tracked. I was always suspicious due to my scraper not updating the data but that is probably due to a rogue redirect that I need to investigate.
