### ISSUE TITLE
Changelog automation should use a pre-built `git-cliff` package

### ISSUE THREAD

**Issue by codyshepherd** [influxdata/influxdb#22529]
Currently, the changelog automation requires installing rust and compiling the `git-cliff` source every run, which takes a long time.

To save cycles, we should use a pre-built git-cliff artifact, either a [tarball](https://github.com/orhun/git-cliff/releases) or a [Docker image](https://github.com/orhun/git-cliff/pkgs/container/git-cliff%2Fgit-cliff) (either of which we verify first) from the project's GitHub page.

**Comment by lesam** [comment]
@wbaker85 confirms this is also done for 2.x, so closing.
