### ISSUE TITLE
Import of csv with value 0 does not work

### ISSUE THREAD

**Issue by lukasbrun** [influxdata/influxdb#22550]
**Steps to reproduce:**

List the minimal actions needed to reproduce the behavior.

1. Open the InfluxDB Web GUI
2. Navigate to Data -> Buckets
3. On a bucket, select Add Data -> CSV Upload
4. Upload this CSV file: [2021-08-11_11 29_influxdb_data.csv](https://github.com/influxdata/ui/files/6967306/2021-08-11_11.29_influxdb_data.csv)

**Expected behavior:**

The data is imported into the bucket

**Actual behavior:**

The following error message is displayed
![grafik](https://user-images.githubusercontent.com/53816889/129006027-83677a45-a16f-4485-9d38-e480f97a3f26.png)

**Environment info:**

- System info: Linux 5.10.25-linuxkit x86_64
- InfluxDB version: InfluxDB 2.0.7 (git: 2a45f0c037) build_date: 2021-06-04T19:17:40Z
- Other relevant environment details: Containerized on Docker for Windows

**Debug info**

Using the browser dev tools, i found that the generated Line Protocol seems to be incorrect
![grafik](https://user-images.githubusercontent.com/53816889/129007922-108a5a9a-306c-4544-b0eb-234718187fe5.png)

![grafik](https://user-images.githubusercontent.com/53816889/129007761-5264c4df-9f64-4c85-9e16-ae1d5c6784d5.png)

**Comment by lukasbrun** [comment]
I tested this again with InfluxDB 2.1.0 (Server: 435907d, Frontend: cc65325)
The first file ([2021-08-11_11 29_influxdb_data.csv](https://github.com/influxdata/ui/files/6967306/2021-08-11_11.29_influxdb_data.csv), value is 0) works as intended, the second one ([empty_value_test_data.csv](https://github.com/influxdata/ui/files/7208159/empty_value_test_data.csv), value is empty string) does not write any points to the bucket.
If this is the intended behavior, this issue can be closed.

**Comment by wbaker85** [comment]
Thanks for the update @lukasbrun - I've verified that the behavior with InfluxDB 2.1 is the same as the cloud UI now, so I am closing this out.
