### ISSUE TITLE
Invalid json structure when Mapping unmapped buckets influx DB

### ISSUE THREAD

**Issue by mbc99** [influxdata/influxdb#22553]
So I come from the Influxdb comunity: https://community.influxdata.com/t/invalid-json-structure-when-mapping-unmapped-buckets-influx-db/21796
With no success. So I'm going to assume that I did not make an stupid mistake (or so someone would have said something).
I want to be able to use influx QL on my v2 database. I tried to follow this documentation: https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/?t=InfluxDB+API

I viewed the DBRP mappings succesfully:
> {
>         "content": []
> }
I suppose it's blank because there are none, which makes sense.

Then I tried to create a DBRP mapping with: 
c
```
curl --request POST "http://192.168.1.223:8089/api/v2/dbrps" --header "Authorization: Token -my_token" --header "Content-type: application/json" --data "{"bucketID": "someID", "database": "ambientQuality", "default": true, "orgID": "3ea1813c523490d1", "retention_policy": ""}"

```
But I always get the same response:
> {
>         "code": "invalid",
>         "message": "invalid json structure: invalid character 'b' looking for beginning of object key string"
> }

I have also tried doing the same thing using python requests:

```
import requests
import logging


logging.basicConfig(level=logging.DEBUG)

url = 'http://192.168.1.223:8089/api/v2/dbrps'
myobj = {"bucketID": "c26f45b24dbd038b", "database": "ambientQuality", "default": True, "orgID": "someID", "retention_policy": ""}
header1={"Authorization":"Token -someToken",  "Content-type": "application/json"}

x = requests.post(url, data = myobj, headers=header1)

print(x.text)
```
> DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.223:8089
> DEBUG:urllib3.connectionpool:http://192.168.1.223:8089 "POST /api/v2/dbrps HTTP/1.1" 400 114
> {
> 	"code": "invalid",
> 	"message": "invalid json structure: invalid character 'b' looking for beginning of value"
> }

The problem seems to be that the json response is not correctly formated.

PS: the port is 8089. I did it because port 8086 is being used by Influxdb v1.8

I'm running InfluxDB 2.0.8

__Logs:__
The logs say the same thing as the response:

ts=2021-09-22T17:27:54.897844Z lvl=error msg="api error encountered" log_id=0WgyXmCl000 error="invalid json structure: invalid character 'b' looking for beginning of value"

**Comment by mbc99** [comment]
No one? 

Is this a known issue?

Am I doing something wrong?

**Comment by danxmoran** [comment]
@mbc99 I don't see anything obvious in your requests. Do you have access to the `influxd` deployment you're sending requests to? Could you restart it with `--log-level debug` and paste the logs that are generated when you hit this error?

**Comment by mbc99** [comment]
> @mbc99 I don't see anything obvious in your requests. Do you have access to the `influxd` deployment you're sending requests to? Could you restart it with `--log-level debug` and paste the logs that are generated when you hit this error?

Hi @danxmoran,

Any idea how to enable it in Docker? (Docker-compose specifically) 
I found this: https://community.influxdata.com/t/trying-to-run-influxdb-in-debug-mode-using-docker/10008
But it doesn't seem to work although the InfluxDB container seems to have picked up the configuration through Docker-Compose:

![image](https://user-images.githubusercontent.com/44815501/135913138-48dfa60c-cf8d-4526-9a33-dd74a25b7ced.png)

**Comment by danxmoran** [comment]
Setting `INFLUXD_LOG_LEVEL=debug` in your container environment should do it.

**Comment by mbc99** [comment]
> Setting `INFLUXD_LOG_LEVEL=debug` in your container environment should do it.

That's what I did:
![image](https://user-images.githubusercontent.com/44815501/135913764-1573a050-e982-4b92-8afc-7027d8c3d94d.png)

But still, even for the fact that it is in error I still see info messages.

I tried putting it in error because when I set it to debug it didn't show any debug info. And it kept me wondering wether there was no debug log or that something was wrong (it seems like it's the latest)

**Comment by mbc99** [comment]
> Setting `INFLUXD_LOG_LEVEL=debug` in your container environment should do it.

Setting the parameter in debug yields the same log as error:
![image](https://user-images.githubusercontent.com/44815501/135914143-246178cf-d3b0-48c9-8485-f82eacaff295.png)

**Comment by danxmoran** [comment]
(Unless I'm missing something) The env var you're using isn't correct. You're setting `INFLUXDB_LOGGING_LEVEL`, but the correct var is `INFLUXD_LOG_LEVEL`.

`debug` is the level we want for this because it'll cause the full request payload to be printed in the server logs.

**Comment by mbc99** [comment]
> INFLUXD_LOG_LEVEL

You should really be given an award for your patience. Really thank you

![image](https://user-images.githubusercontent.com/44815501/135914660-2e3b0eb3-7353-4e41-86bd-a6cf35892b84.png)
It says invalid body.
Maybe it doesn't like the blank retetion policy?

**Comment by danxmoran** [comment]
So yes, looking deeper into the code I can see that the blank retention policy is invalid (the name you use doesn't affect anything in the system, it's just for bookkeeping; you can use "default" or "autogen" or any other alphanumeric string). The system isn't getting that far, though... it looks like the request body might be missing the closing `"` for the empty `retention_policy` field. I could see that happening in a `curl` call because of quoting edge-cases, but I'm confused why it'd happen in a Python `requests` call.

All that said, I'd try setting the `retention_policy` and see if that happens to fix both problems 🙂

**Comment by mbc99** [comment]
> So yes, looking deeper into the code I can see that the blank retention policy is invalid (the name you use doesn't affect anything in the system, it's just for bookkeeping; you can use "default" or "autogen" or any other alphanumeric string). The system isn't getting that far, though... it looks like the request body might be missing the closing `"` for the empty `retention_policy` field. I could see that happening in a `curl` call because of quoting edge-cases, but I'm confused why it'd happen in a Python `requests` call.
> 
> All that said, I'd try setting the `retention_policy` and see if that happens to fix both problems 🙂

Although I have changed the retention policy to Default I still get the same error. I've switched back from curl to python to ensure I don't miss any "
import requests
import logging


logging.basicConfig(level=logging.DEBUG)

```
#%%add DBRP mapping
url = 'http://192.168.1.223:8089/api/v2/dbrps'
myobj = {"bucketID": "c26f45b24dbd038b", "database": "ambientQuality", "default": True, "orgID": "3ea1813c523490d1", "retention_policy": "Default"}
header1={"Authorization":"Token -SomeHighSecretToken",  "Content-type": "application/json"}
x = requests.post(url, data = myobj, headers=header1)
print(x.text)
```


```
ts=2021-10-04T20:09:47.361222Z lvl=error msg="api error encountered" log_id=0W~DEFaW000 error="invalid json structure: invalid character 'b' looking for beginning of value",
ts=2021-10-04T20:09:47.361308Z lvl=debug msg=Request log_id=0W~DEFaW000 service=http method=POST host=192.168.1.223:8089 path=/api/v2/dbrps query= proto=HTTP/1.1 status_code=400 response_size=114 content_length=110 referrer= remote=192.168.1.122:54321 user_agent=python-requests took=0.397ms error=invalid error_code=invalid body="bucketID=c26f45b24dbd038b&database=ambientQuality&default=True&orgID=3ea1813c523490d1&retention_policy=Default"
```

**Comment by danxmoran** [comment]
Looks like requests is setting the parameters in the URL instead of sending them as JSON. I think it might work if you use `json=myobj` instead of `data=myobj` in your `requests.post` call.

**Comment by mbc99** [comment]
> Looks like requests is setting the parameters in the URL instead of sending them as JSON. I think it might work if you use `json=myobj` instead of `data=myobj` in your `requests.post` call.

**It worked!!!!**

Thank you, really. It was a silly mistake that I wouldn't have figured out.

I'm going to leave the python script for anyone in the same situation:
```
import requests
import logging


logging.basicConfig(level=logging.DEBUG)

#%%add DBRP mapping
url = 'http://192.168.1.223:8089/api/v2/dbrps'
myobj = {"bucketID": "InsertBucketID", "database": "InsertDB", "default": True, "orgID": "InsertID", "retention_policy": "Default"}
header1={"Authorization":"Token -SomeHighSecretToken",  "Content-type": "application/json"}
x = requests.post(url, json = myobj, headers=header1)
print(x.text)

#%%check mappings
url='http://192.168.1.223:8089/api/v2/dbrps?orgID=InsertID'
header1={"Authorization":"Token -SomeHighSecretToken"}
x = requests.post(url, headers=header1)
print(x.text)
```

**Comment by danxmoran** [comment]
🎉 glad we got it sorted out!
