### ISSUE TITLE
Aggregation with time zone support

### ISSUE THREAD

**Issue by dsilletti** [influxdata/influxdb#22655]
__Proposal:__
Timezone support for the aggregation, to be able to aggregate data (e.g. daily) based on timezone (also hourly for the Half Hour and 45-Minute Time Zones: https://www.timeanddate.com/time/time-zones-interesting.html)
E.g.
|> aggregateWindow(every: 1d, fn: mean, createEmpty: false, timeZone="Europe/Rome", timeSrc: "_start")

__Current behavior:__
There is no timezone support, the daily aggregation is based on UTC time (0-24 UTC)

__Desired behavior:__
Aggregation (e.g. daily) based on timezone.
E.g.
|> aggregateWindow(every: 1d, fn: mean, createEmpty: false, timeZone="Europe/Rome", timeSrc: "_start")

__Alternatives considered:__
At the moment I am using MongoDB for this purpose.

__Use case:__
Without this feature is impossible to aggregate the data in day, month, year for different timezones.
For some timezones is also impossible to aggregate the data hourly because there is a 30 min or 45min shift: https://www.timeanddate.com/time/time-zones-interesting.html

**Comment by ANIKET0956** [comment]
Open Issue: https://github.com/influxdata/flux/issues/406
Seems it will be supported soon.  (as location param in flux query)

**Comment by XiaoXin101** [comment]
I hope it will be repaired soon

**Comment by dsilletti** [comment]
Option location with timezone support it's available since influxdb v2.1.0, flux v0.139.0.
I can close this issue.
Thanks

**Comment by mpenn0** [comment]
@dsilletti Do you have an example of how to use is in an aggregateWindow query?

**Comment by mpenn0** [comment]
@dsilletti Do you have an example of how to use is in an aggregateWindow query?

**Comment by Bond246** [comment]
Hello,

i have the same problem in Europe/Berlin with grafana.

My daily bar-graph with power consumtion data starts everyday on 01:00 and it should be 00:00.

![grafik](https://user-images.githubusercontent.com/8534418/144056893-90b0ab8a-db34-4136-b863-b7d83e64d717.png)

I found that in documentation:
https://docs.influxdata.com/flux/v0.x/stdlib/timezone/location/
But i have no idea where to use it.

My grafana query is:
```
from(bucket: "40_tage")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "Verbrauch")
  |> filter(fn: (r) => r["location"] == "Beamer")
  |> filter(fn: (r) => r["_field"] == "gesamt")
  |> aggregateWindow(every: 1d, fn: spread, createEmpty: false)
  |> yield(name: "spread")
```

InfluxDB is in docker with version 2.1.1 so i think flux is latest.

Thanks for help,
Bond

**Comment by mpenn0** [comment]
I answer myself once. :-)
Thanks to the hints from here:
[https://github.com/influxdata/flux/issues/406#issuecomment-984605045](url)
and
[https://github.com/influxdata/flux/issues/4312#issuecomment-985514836](url)

I have tried it again and tested successfully (at least for Europe / Berlin) with the following query.
Here is the representation without "location parameters":
![grafik](https://user-images.githubusercontent.com/56229993/144643631-5b3c10e1-bc88-4908-9bd9-7b5a621571ee.png)

And here with the "location parameter":
![grafik](https://user-images.githubusercontent.com/56229993/144643889-8a12f26d-c1e9-4023-88b2-6e3f332760dc.png)

The input for this is as follows:
`import "timezone"
option location = timezone.location(name: "Europe/Berlin")
from(bucket: "iobroker")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "alias.0.Messwerte.Temperatur.Außen")
  |> filter(fn: (r) => r._field == "value")
  |> aggregateWindow(every: v.windowPeriod, fn: min)
  |> set(key: "_field", value: "Nachttemperatur")`
