### ISSUE TITLE
Charts have some strange patterns appearing on mouse-over

### ISSUE THREAD

**Issue by gefaila** [influxdata/influxdb#22742]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.
Mousing over any chart

__Expected behavior:__
The hover legend appears

__Actual behavior:__
Hover legend appears alongside a shaded shape that continues from a previous line section.
![image](https://user-images.githubusercontent.com/69196723/138710620-8cf0bf17-fa83-475a-9283-66fd1c5ef0e9.png)

__Environment info:__

* InfluxDB cloud 2.0 UI

**Comment by wbaker85** [comment]
@gefaila are you still seeing this behavior on the Cloud 2.0 UI? It has recently been updated quite a bit.

**Comment by gefaila** [comment]
Not seen it for a while to be honest.
Shall we consider it fixed until I observe it again.
We've got plenty of new bugs to be dealing with !
https://github.com/influxdata/ui/issues/4255
https://github.com/influxdata/ui/issues/4256
https://github.com/influxdata/ui/issues/4257
https://github.com/influxdata/ui/issues/4258
https://github.com/influxdata/ui/issues/4259
