### ISSUE TITLE
what is the primary org and primary bucket used for?

### ISSUE THREAD

**Issue by wangshuang0220** [influxdata/influxdb#22766]
__Proposal:__

Describe what currently happens.

what is the primary org and primary bucket that created by setup process used for?

Describe what you want.
May I know when i delete the primary org or primary bucket what will happen ? Will instances be affected?
 

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Why is this important (helps with prioritizing requests)?

**Comment by danxmoran** [comment]
It should be safe to delete the initial bucket, it's only created as a convenience.

I would advise against deleting the initial org, since it encapsulates the initial super-user token created by `setup`.
