### ISSUE TITLE
Read-Only Token allows to run DROP MEASUREMENT and DELETE

### ISSUE THREAD

**Issue by SianBrumm** [influxdata/influxdb#22799]
Hello everyone,

I am currently running influxdb OSS version 2.0 and I am using grafana version 8.2.1 to visualize my data.

My problem is that while using InfluxQL in grafana I am able to drop or delete measurements/ data although I am only using a read-only token for this bucket. 

I tested everything with the 1.8 version of Influx yesterday. And it works as it should. A user with just read permission is blocked from performing “DROP MEASUREMENT” or “DELETE” queries.

However i cant get it work with 2.0 and this new token system. I created a new user and created a read-only token for this user only with read access to this specific bucket. Still I am able to delete data by running those queries in the raw query mode of grafana.

I am using the token in the custom http header section with the value: token “myToken” as described in many blogs and tried every combination in the auth details and below in the user and password area. Nothing worked yet.

I’m new to influxdb and would like to know if there is a possibility to prohibit those commands or restrict users rights so that a grafana user cant delete my data.

Thank you!

**Comment by sinspiral** [comment]
I am also in the same situation... is there any news or way of creating API tokens to prevent writing or deleting data?

**Comment by jdstrand** [comment]
I can confirm the behavior with `/query`. `/api/v2/delete` is not affected and is correctly enforcing. FYI, authorization is being performed on /query which can be seen by providing a non-existent token and getting back `{"code":"unauthorized","message":"Unauthorized"}`.
