### ISSUE TITLE
Issue with operating on multiple subqueries

### ISSUE THREAD

**Issue by elangela** [influxdata/influxdb#22791]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Check that value1 exists in measurement1: SELECT SUM("value1") AS num FROM measurement1 WHERE host =~ /host1/GROUP BY time(15m)
2. Check that value2 exists in measurement2: > SELECT SUM("value2") AS den1 FROM measurement2 WHERE host =~ /host1/ GROUP BY time(15m)
3. Do a full query with both 1) and 2): SELECT num,den1 FROM (SELECT SUM("value1") AS num FROM measurement1 WHERE host =~ /host1/ GROUP BY time(15m)),(SELECT SUM("value2") AS den1 FROM measurement2 WHERE host =~ /host1/ GROUP BY time(15m)) GROUP BY host
4. If you do the same full query for two values within the same measurement, the the result is successful: SELECT num,den1 FROM (SELECT SUM("value1") AS num FROM measurement1 WHERE host =~ /host1/ GROUP BY time(15m)),(SELECT SUM("value2") AS den1 FROM measurement1 WHERE host =~ /host1/ GROUP BY time(15m)) GROUP BY hos

__Expected behavior:__
The expected behavior is that both values num and den1 is presented in the output. 

__Actual behavior:__
Only the first variable num is returned. den1 is not returned in the full query.

__Environment info:__
centos-release-7-9.2009.1.el7.centos.x86_64
InfluxDB shell version: 1.8.9

The reported bug seem to be identical to issue #9988:
https://github.com/influxdata/influxdb/issues/9988

**Comment by timhallinflux** [comment]
InfluxQL is limited to querying from a single measurement.  However, selecting values from multiple measurements is something that you can do with Flux.  Take a look at InfluxDB v2.1.1 and use Flux to do this.

Rough example based on what you outlined
```from(bucket: "your_bucket")
  |> range(start: -24h)
  |> filter(fn: (r) => r["_measurement"] == "measurement1" or  r["_measurement"] == "measurement2" )
  |> filter(fn: (r) => r["_field"] == "value1" or r["_field"] == "value2")
  |> filter(fn: (r) => r["host"] =~ /host1/ )
  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)```

**Comment by elangela** [comment]
> InfluxQL is limited to querying from a single measurement. However, selecting values from multiple measurements is something that you can do with Flux. Take a look at InfluxDB v2.1.1 and use Flux to do this.
> 
> Rough example based on what you outlined
> 
> ```
> from(bucket: "your_bucket")
>   |> range(start: -24h)
>   |> filter(fn: (r) => r["_measurement"] == "measurement1" or  r["_measurement"] == "measurement2" )
>   |> filter(fn: (r) => r["_field"] == "value1" or r["_field"] == "value2")
>   |> filter(fn: (r) => r["host"] =~ /host1/ )
>   |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)
> ```

If I could I would .. We just have to live with the Influxdb 1.x limitations. Unfortunately moving users to learn a new query language once they 'just' have mastered InfluxQL is not an option. Migrating to Influxdb 2x might be an option when it supports both InfluxQL and Flux in parallel. Will this happen at some point?

**Comment by timhallinflux** [comment]
InfluxDB v2 already supports both InfluxQL (via compatibility API) and Flux. See: https://docs.influxdata.com/influxdb/v2.1/query-data/get-started/
