### ISSUE TITLE
I write the data into influxdb, and it return 3 errors at the beginning:

### ISSUE THREAD

**Issue by ybina** [influxdata/influxdb#22801]
```
influxdb2client E! Write error: Post "http://127.0.0.1:8086/api/v2/write?bucket=binaBucket&org=workspace&precision=ns": EOF
Batch kept for retrying
```

after that, all the writes are right

So what's the matter with it when write the data at the beginning?

**Comment by wbaker85** [comment]
Would you mind providing which version of InfluxDB you are using, which client you are trying to write with, and if possible a sample of the data you are trying to write that is resulting in this error?

**Comment by ybina** [comment]
server2.0.9，golang client to write

**Comment by StarpTech** [comment]
I can reproduce it as well. We use Influxdb cloud with `github.com/influxdata/influxdb-client-go/v2 v2.7.0`

```
2022/02/06 21:04:20 influxdb2client E! Write error: Post "https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2/write?bucket=redacted&org=redacted&precision=ns": dial tcp: i/o timeout
Batch kept for retrying

```

**Comment by bai-charisu** [comment]
Hello, I have the same problem here. Has the problem solved?

**Comment by vlastahajek** [comment]
In case you use default settings, it seems that default InfluxDB Go client timeouts are sometimes too small. Try increasing them.
Timeouts  can be completely customized via setting a custom `http.Client`:
```go

**Comment by liuyang0716** [comment]
> In case you use default settings, it seems that InfluxDB Go client's default timeouts are sometimes too small. Try increasing them. Timeouts can be completely customized via setting a custom `http.Client`:
> 
> ```go
>     httpClient := &http.Client{
> 		Timeout: time.Second * 100,
> 		Transport: &http.Transport{
> 			DialContext: (&net.Dialer{
> 				Timeout: 30 * time.Second, 
> 			}).DialContext,
> 			TLSHandshakeTimeout: 30 * time.Second,
> 			MaxIdleConns:        100,
> 			MaxIdleConnsPerHost: 100,
> 			IdleConnTimeout:     90 * time.Second,
> 		},
> 	}
> 	token := `token`
> 	opts := influxdb2.DefaultOptions().SetHTTPClient(httpClient)
> 	client := influxdb2.NewClientWithOptions("https://eu-central-1-1.aws.cloud2.influxdata.com", token, opts)
> ```
> 
> `http.Client.Timeout` is an overall time limit, from dialing till reading the response body. Too short timeout leads to error: _context deadline exceeded (Client.Timeout exceeded while awaiting headers)_
> 
> `DialContext.Timeout` defines a time limit for establishing a connection. Small values lead to error: _dial tcp: i/o timeout_
