### ISSUE TITLE
events.duration() fails after 1000 rows

### ISSUE THREAD

**Issue by Ogoku** [influxdata/influxdb#22831]
Hi all and @tomhollingworth,

I have a strange behaviour using events.duration( )

Every 1000th row events.duration(unit: 1m, stopColumn: "_stop" ) is not calculating current row with the next one. Instead it is calculating the differences to the given stop time.

![image](https://user-images.githubusercontent.com/11227196/140527426-6feea419-fcc3-47f2-9ce7-5a13a8822d5f.png)
(1222min ~20h which is _time to _stop)

When I export my query via csv I can see that every 1000th entry the result ist _time to _stop.

__Steps to reproduce:__
Whole query:

`
import "contrib/tomhollingworth/events"

from(bucket: "statistik_daten")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "opc_ua_mes_2")
  |> filter(fn: (r) => r["maschinen_name"] == "${Maschinen_Name}")
  |> events.duration(unit: 1ms, stopColumn: "_stop" )
`

Read more than 1000 entries 

__Expected behavior:__
Except the last row, events.Duration() should always calculates the difference between current record with the next one

__Actual behavior:__
After 1000 rows events.Duration() calculates difference between current record and _stop value

__Environment info:__
Running on a Windows OS
* InfluxDB version: InfluxDB 2.0.7 (git: 2a45f0c037) build_date: 2021-06-04T19:17:40Z

**Comment by wbaker85** [comment]
This should be fixed by https://github.com/influxdata/flux/pull/4064 with flux v0.139.0.  This version of flux will go out with our next minor release, influxdb `2.1`, which should be coming out in a few days. Would you be able to upgrade to `2.1` when it's available? If so it would be nice to see if the bug you are seeing is indeed fixed with the latest version of flux.

**Comment by Ogoku** [comment]
Hey @wbaker85. Updated Influxdb to 2.1 this morning. Problem solved!
