### ISSUE TITLE
how to reset influxdb initial user without losing data

### ISSUE THREAD

**Issue by wangshuang0220** [influxdata/influxdb#22841]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. forget the initial user‘s password and token
2. there no config file in ~/.influxdbv2/configs

__Expected behavior:__
i can reset the influxdb initial user without losing data.

__Actual behavior:__
Describe What actually happened.
May I know how to recovery initial user when forgot the initial password or operator token.
__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by wbaker85** [comment]
This was not possible to do prior to InfluxDB `v2.1`, but the latest InfluxDB `v2.1.1` now includes functionality that should allow you to do what you want: https://docs.influxdata.com/influxdb/v2.1/reference/cli/influxd/recovery/

Feel free to go ahead and open another issue if you find problems with the `influxd recovery` commands.
