### ISSUE TITLE
cannot remove members from org via CLI

### ISSUE THREAD

**Issue by wangshuang0220** [influxdata/influxdb#22851]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.
**influxdb version2.1.0**
**influxdb CLI version 2.2.0**
1. remove member from one org with CLI "influx org members remove -m 086682f574d98000 -i 3e1ac922bf07955f "
2. server log 
![image](https://user-images.githubusercontent.com/8791900/140884408-302ed2f3-b682-41d0-9e52-1023fb9dfbb8.png)
it seems like members id and orgId reversed

__Expected behavior:__
remove members from org successfully via CLI
__Actual behavior:__
Describe What actually happened.
cannot remove members from org via CLI
__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by danxmoran** [comment]
I believe this is influxdata/influx-cli#317, so closing this one as a duplicate.
