### ISSUE TITLE
The \n divider in the lineprotocol seems to be broken or needs better documentation

### ISSUE THREAD

**Issue by noontz** [influxdata/influxdb#22874]
According to the documentation (as I read it) the influx line protocol accepts \n to separate points.

I have not been able to find any examples with multiple lines using \n explicit in the body content

I have a request in Postman on Windows 10 http://127.0.0.1:8086/api/v2/write?precision=ms&bucket=Test&org=Test with required headers that works just fine with this ONE line in the Body:

tag,id=87 value=17855 1636735893871

So I would naturally expect something like this to work for multiple points:

tag,id=87 value=17855 1636735893871 \n tag,id=87 value=17856 1636736594952
tag,id=87 value=17855 1636735893871\ntag,id=87 value=17856 1636736594952
tag,id=87 value=17855 1636735893871 \ntag,id=87 value=17856 1636736594952
tag,id=87 value=17855 1636735893871\n tag,id=87 value=17856 1636736594952

Unnecessary to say I tried this as well:

tag,id=87 value=17855 1636735893871
tag,id=87 value=17856 1636736594952

Seems like postman inserts a \r from the response

Even tried forward slashes just for sport. 

I am recieving either a "bad timestamp" or "point is invalid" error in the response

This is a duplet of [https://stackoverflow.com/questions/69947081/how-do-i-insert-multiple-points-in-influx-with-the-lineprotocol-and-api](url), but since no answers have arrived to a rather trivial question I am posting it here ;)

I am creating the body as a string in C# on windows and using Postman to check

**Comment by wbaker85** [comment]
This postman quest works fine for me on Windows 10:

![image](https://user-images.githubusercontent.com/55118525/141652919-6def1a53-a840-43bb-a19b-b3df878e21b3.png)

You should be able to post multi-line requests like that, as in your second example:

```
tag,id=87 value=17855 1636735893871
tag,id=87 value=17856 1636736594952
```

Are you using raw -> text for the type of body?

**Comment by noontz** [comment]
Yes..  My request with two lines looks exactly like your screenshot (save bucket and org name). In that case I am recieving an '\r' in the error response. I also tried to explicitly set the content-type to text/plain; charset=utf-8 in Postman, but that did not change anything. Since my request is working with one line I would expect the headers to be valid. 
I should probably add that I am calling the API with Postman on a hosted VPS windows server 2019 and the InfluxDB is hosted in Docker on the same server.

**Comment by cesuper** [comment]
I have exactly the same problem as @noontz! Looking forward for any solution.

**Comment by noontz** [comment]
![InfluxLineProtocolError](https://user-images.githubusercontent.com/7408674/141785949-abe73386-82e6-42f4-9c65-cf362f8b8e5a.png)

Just to show that this issue is not related to Postman

**Comment by noontz** [comment]
Seems like this all boils down to a windows End Of Line implementation. Postman, Devtools, whatever editor running on windows will write a lineshift as \r\n, (hex 0A 0D) that currently is not supported by the lineprotocol although it seems like a trivial implementation (skip 0D).  As for my own problem coding in C# adding a (char)10 between points solved the problem instead of using Environment.NewLine.  I understand (now) that this is what the documentation is saying, but maybe do a hint on the issue.  There is a couple of developers on windows out there ;)

**Comment by dafegit** [comment]
Hi,

@noontz I was also having the same problem. I tried this workaround to remove the \r

In Pre-request Script:

```
var body = `bgp_table_version,router=PCE1RRIP1,addr_family="ipv4" value=100 1638446949000\n bgp_table_version,router=PCE1RRIP2,addr_family="ipv6" value=100 1638446949000`.replace(/\r/g, '');

pm.variables.set('body', body);
```
![image](https://user-images.githubusercontent.com/40767571/144455516-9e2cf418-9c92-409e-a8eb-7f240be16eac.png)

in body:

`{{body}}`

![image](https://user-images.githubusercontent.com/40767571/144455670-88ed0c32-88d8-4e43-adab-8ba6bc7caef0.png)

Multiple lines have been correctly added to BD:

```
root@b59a5be9a1af:/# influx query 'from(bucket:"network-info-db") |> range(start: -7d) |> filter(fn: (r) => r._measurement == "bgp_table_version")'
Result: _result
Table: keys: [_start, _stop, _field, _measurement, addr_family, router]
                   _start:time                      _stop:time           _field:string     _measurement:string      addr_family:string           router:string                      _time:time                  _value:float
------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  ----------------------  ------------------------------  ----------------------------
2021-11-25T15:38:29.957149365Z  2021-12-02T15:38:29.957149365Z                   value       bgp_table_version                  "ipv4"               PCE1RRIP1  2021-12-02T12:09:09.000000000Z                           100
Table: keys: [_start, _stop, _field, _measurement, addr_family, router]
                   _start:time                      _stop:time           _field:string     _measurement:string      addr_family:string           router:string                      _time:time                  _value:float
------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  ----------------------  ------------------------------  ----------------------------
2021-11-25T15:38:29.957149365Z  2021-12-02T15:38:29.957149365Z                   value       bgp_table_version                  "ipv6"               PCE1RRIP2  2021-12-02T12:09:09.000000000Z                           100
```

**Comment by HomeLH** [comment]
I have exactly the same problem, when I commit `\r\n` log data.
