### ISSUE TITLE
backup data then restore it in another server failed

### ISSUE THREAD

**Issue by ybina** [influxdata/influxdb#22894]
I backup the database of my influx server  A and want to restore it in my influx instance B
I read the official Documentation and set "influx setup --token “A server rootToken”" with cmd in server B
But Cli returns an error: 
Error: instance at “http://localhost:8086” has already been setup
So how to restore the data in a different influx instance?
influxdb 2.0.9
Thank you

**Comment by aleksrosz** [comment]
You probably set it up earlier . Using just "influx setup" with username and password. 
Login to server and copy data from this directory  .influxdbv2/ from one instance to another.  
Here is documentation.
https://docs.influxdata.com/influxdb/v2.0/reference/internals/file-system-layout/
