### ISSUE TITLE
Display run-time configuration in use by `influxd`

### ISSUE THREAD

**Issue by wangshuang0220** [influxdata/influxdb#22917]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. use [influxd print-config] command to get runtime configs

__Expected behavior:__
i want to get the correct runtime configs ,for example：my instance bolt path is /var/lib/influxdb/influxd.bolt. but the command result is :bolt-path: /root/.influxdbv2/influxd.bolt
![image](https://user-images.githubusercontent.com/8791900/142955922-a1845344-d851-4bcb-a997-2f8bb9dae7bb.png)

__Actual behavior:__
Describe What actually happened.
got the configs are not runtime.
__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by wbaker85** [comment]
The present version of the `print-config` command does not output the config of the running server. Rather, it is able to evaluate the current environment, config file, and _flags passed to the print-config command_ itself. The last part is maybe not ideal - for example, if you run `influxd print-config --bolt-path /some/path` you will see the different bolt path in the printed configuration. If you have run the daemon with the `--bolt-path` flag separately, the `influxd print-config` command is unable to to pick up that flag.

Are you running `influxd` with flags in that way?

**Comment by wangshuang0220** [comment]
tks for reply, i just want to know how to get configs from the running server, any good idear?

**Comment by wbaker85** [comment]
I don't believe there's a way to do that currently. I can see how it would be useful though, as in a troubleshooting scenario like you describe. I'll mark this as a feature request since it would require some new capabilities.

**Comment by wangshuang0220** [comment]
like redis, it can use `config get` command to get the runtime configs.

**Comment by lesam** [comment]
@timhallinflux @davidby-influx I think we should prioritize this one and deprecate `print-config`. Using `print-config` is too complicated to get right.

**Comment by lesam** [comment]
See also https://influxcommunity.slack.com/archives/CH8RV8PK5/p1637859587021100?thread_ts=1637837703.020000&cid=CH8RV8PK5

**Comment by lesam** [comment]
## Proposal:

* Add a new, OSS-only `api/v2/config` endpoint, and an `influx config ls` in the CLI to read it. It should require operator permissions, similar to backup/restore.

* Mark `influxd print-config` as deprecated (emit a message pointing users to `influx config ls` for the usual case).

**Comment by lesam** [comment]
@dgnorton - meant to @ you earlier. I think this one should be an OSS priority.
