### ISSUE TITLE
how to using Python-API writes the data with blank space to influxdb

### ISSUE THREAD

**Issue by liyongchao911** [influxdata/influxdb#22959]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. using python-api wrote data to influxdb
2. organize the data as line protocol, like "temp,EQP_ID=AMAT-0001,MODEL_ID=QMO_2DCP1,Recipe=RFDDS TEST value=4.79,
attention that the recipe tag value is 'RFDDS TEST', with a blank space in between. and this value is from equipment, can not change.
3. when write this data to influxdb, get a error: message":"unable to parse '. 
4. how to deal with this kind of value ?

Thanks!

**Comment by wbaker85** [comment]
I would try escaping the space - see https://docs.influxdata.com/influxdb/v2.1/reference/syntax/line-protocol/#special-characters

**Comment by liyongchao911** [comment]
Thanks！I follow the instruction and using "\" solving this issue!
