### ISSUE TITLE
Flaky tests in replications service

### ISSUE THREAD

**Issue by mcfarlm3** [influxdata/influxdb#22969]
Quite a few tests related to replications service failed on recent merge to master branch. Failures were only on `test-darwin` job.

Link to CircleCI: https://app.circleci.com/pipelines/github/influxdata/influxdb/26230/workflows/21429efe-83b1-40ec-92b3-6df41a968d0f/jobs/235294 

Failed tests:
![Screen Shot 2021-12-07 at 11 04 36 AM](https://user-images.githubusercontent.com/58636946/145128580-14e3df2f-7870-41ea-8c18-0c6a9d9242ba.png)

Relevant Output:
![Screen Shot 2021-12-07 at 11 05 21 AM](https://user-images.githubusercontent.com/58636946/145128591-7754950e-bc22-4c24-a956-cd7c09e83368.png)

**Comment by wbaker85** [comment]
Saw this fail on the linux tests just now also: https://app.circleci.com/pipelines/github/influxdata/influxdb/26261/workflows/9a658099-c510-40e2-8c2d-8810ed127a32/jobs/235651
