### ISSUE TITLE
Unable to open boltdb file invalid database on s390x

### ISSUE THREAD

**Issue by srajmane** [influxdata/influxdb#22968]
__Steps to reproduce:__
Following [these](https://github.com/influxdata/influxdb/blob/v2.1.1/CONTRIBUTING.md#testing) steps:
Facing issue while running `make test` command

__Expected behavior:__
Testcases should pass on s390x.

__Actual behavior:__
`Test_Auth_Basic , Test_Org_Basic and Test_User_Basic` tests are failing.

__Environment info:__

* System info: s390x
* InfluxDB version: 2.1.1
* Other relevant environment details: Container runtime, disk info, etc

__Logs:__
`Test_Auth_Basic , Test_Org_Basic and Test_User_Basic` tests are failing with the below issue:
```
testboltdb.go:44:
                Error Trace:    testboltdb.go:44
                                                        auth_test.go:17
                Error:          Received unexpected error:
                                unable to open boltdb file unable to open boltdb file invalid database
```

Not able to access `influxd.bolt.testdata` file on s390x.

Could you please elaborate on this issue? 
It would be great if you can share the steps with us to generate influxd.bolt.testdata on s390x.

**Comment by srajmane** [comment]
Could you please have a look?

**Comment by zoesteinkamp** [comment]
Alright so i have talked to some coworkers and unfortunately  we do not currently support s390x. But we do accept PR's and i encourage you if you fix this issue to submit the solution in a PR for our next release. 

I am sorry i did not have better news on this issue

**Comment by srajmane** [comment]
@zoesteinkamp 
Sure, It would be great if you can share the steps with us to generate influxd.bolt.testdata on s390x. 
I will try those steps on s390x platform.

**Comment by dgnorton** [comment]
@srajmane the file is in the same directory with `testboltdb.go`. Maybe it's a permissions issue, the file got corrupted, or maybe there's an issue with bolt on s390x?

**Comment by srajmane** [comment]
@dgnorton I tried to access `influxd.bolt.testdata` file on intel and s390x.
Tried some bbolt commands on intel:
```
bbolt check ./cmd/influxd/recovery/testhelper/influxd.bolt.testdata
OK

bbolt stats ./cmd/influxd/recovery/testhelper/influxd.bolt.testdata
Aggregate statistics for 51 buckets

Page count statistics
        Number of logical branch pages: 0
        Number of physical branch overflow pages: 0
        Number of logical leaf pages: 2
        Number of physical leaf overflow pages: 0
Tree statistics
        Number of keys/value pairs: 37
        Number of levels in B+tree: 1
Page size utilization
        Bytes allocated for physical branch pages: 0
        Bytes actually used for branch data: 0 (0%)
        Bytes allocated for physical leaf pages: 8192
        Bytes actually used for leaf data: 6051 (73%)
Bucket statistics
        Total number of buckets: 51
        Total number on inlined buckets: 49 (96%)
        Bytes used for inlined buckets: 3216 (53%)
```
on s390x:
```
bbolt check ./cmd/influxd/recovery/testhelper/influxd.bolt.testdata
invalid database

bbolt buckets ./cmd/influxd/recovery/testhelper/influxd.bolt.testdata
invalid database
```

Is the `influxd.bolt.testdata` file is arch-specific?

**Comment by srajmane** [comment]
@dgnorton @zoesteinkamp Do you have any updates on the above issue?

**Comment by srajmane** [comment]
@dgnorton @zoesteinkamp 
Gentle ping, any updates for this issue? Thanks :)

**Comment by dgnorton** [comment]
@srajmane I suspect it is arch specific (i.e., when it serializes data to disk, it's probably favoring performance over file portability). Our team doesn't have access to s390x hardware or expertise since it's not one of our officially supported platforms. We're happy to review PRs but our ability to help debug is extremely limited.

**Comment by srajmane** [comment]
@dgnorton Thank you for the update this really helps!!
Could you please share the steps to generate influxd.bolt.testdata file? We'll look into it on s390x platform.

**Comment by mhall119** [comment]
@vivkong I remember that you were working towards s390x support in InfluxDB at one point last year, do you have something that might help @srajmane ?

**Comment by vivkong** [comment]
@mhall119 Sorry I'm not actively looking at InfluxDB currently.

Looking at the issue, are instructions available on how to create`influxd.bolt.testdata`?  @srajmane can generate the binary on s390x since it seems to be arch specific.

**Comment by srajmane** [comment]
@mhall119 Thanks! Vivian and me are from the same team. Currently, I'm looking into these test case failures observed for s390x in InfluxDB. To exit our port/validation, we always try to make sure our s390x test results are at par with intel, that's why we asked for steps to build testdata. If it's not simple, we might skip this test for now.
