### ISSUE TITLE
Failed to create user with permissions using CLI

### ISSUE THREAD

**Issue by victorlmh** [influxdata/influxdb#23001]
After running influxdb (version 2.1.1) and trying to create a user with read and write permission to some buckets using CLI (2.2.1) (https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/v1/auth/create/), the created user does not have the necessary permissions.

![error](https://user-images.githubusercontent.com/1843456/146258575-bfeee68c-3a71-476e-8dfb-ca5e65038b55.png)

command executed:  influx v1 auth create --username github --password github_pw --token token_influxdb --read-bucket 742a8eb3969cdf13 --read-bucket 742a8eb3969cdf13 --read-bucket fdc924dc99d5b18f --write-bucket fdc924dc99d5b18f

Step by step:

1- Create a  database with more than one bucket.
2- Check the ID for each bucket
3- Create an user using the CLI ((https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/v1/auth/create/)) for more than one bucket
4- Check the permissions for the created user

**Comment by Fantaztig** [comment]
Same here, this is a major issue! We cannot create v1 auths with permissions for multiple buckets, the result is as reported: multiple permission entries for the same bucket.

**Comment by DStrand1** [comment]
Fixed by https://github.com/influxdata/influx-cli/pull/328, and will be included in the next release

**Comment by victorlmh** [comment]
@DStrand1,  do you have any plans to create a new release version with this bug fix?
