### ISSUE TITLE
Add a demo data bucket : does not exists

### ISSUE THREAD

**Issue by Productivix** [influxdata/influxdb#23021]
in page : https://docs.influxdata.com/influxdb/cloud/query-data/execute-queries/query-demo-data/#add-a-demo-data-bucket

__Proposal:__
Short summary of the feature.
"Click Add Demo Data, "

__Current behavior:__
There is no button "add demo data"

__Desired behavior:__
have it if possible 

__Alternatives considered:__
Describe other solutions or features you considered.
may be the doc is not uptodate

__Use case:__
Why is this important (helps with prioritizing requests)?
if you want we start easily !
![Capture_load](https://user-images.githubusercontent.com/6737060/147400286-061a1d07-29a9-4699-a3e6-7550d522e186.JPG)

**Comment by felipeschneider88** [comment]
I'm facing the same issue. It used to be the button but not it's gone:
![image](https://user-images.githubusercontent.com/32371298/149147765-a8731ecc-5a22-4e81-a4da-aadb2a80faf1.png)

**Comment by felipeschneider88** [comment]
Just saw the RN from November, they [remove the feature](https://github.com/influxdata/docs-v2/blob/f725b1ad436747d85ee50ac0ccf6eb1de22b4bdf/content/influxdb/cloud/reference/release-notes/cloud-updates.md)

It would be nice to have something like the NOAA with a small amount of info and we can create a task to pull the info if we want more :)
