### ISSUE TITLE
write-only token able to access /query v1 endpoint

### ISSUE THREAD

**Issue by frankvdbh** [influxdata/influxdb#23110]
__Steps to reproduce:__
1. Create API token with limited scope, e.g. only "write" on specific bucket
2. Submitting a "SELECT" query to the /query endpoint with this token

This is the actual request:
`curl --location --request GET 'http://influxdb:8086/query?q=select * from cpu where time >= now()-5h&db=metrics' \
--header 'Authorization: Token abc<redacted>=='`

__Expected behavior:__
403 Forbidden as the scope of the token does not grant read

__Actual behavior:__
Able to see returned series

__Environment info:__

* System info: Docker
* InfluxDB version:  InfluxDB OSS 2.1.1
* Other relevant environment details: Default docker image

Influx auth list shows the correct permissions, e.g.
[write:orgs/b8dfd15dbd8d4123/buckets/2121beaa0940a123]

**Comment by frankvdbh** [comment]
Same behavior is observed when using the legacy auth mechanism and providing username password in query parameters.  On influxDB 1.8 this correctly results in :
`   "error authorizing query: writeuser not authorized to execute statement 'SELECT * FROM cpu WHERE time >= now() - 5h', requires READ on metrics"`

**Comment by timhallinflux** [comment]
Please confirm the process:
1.  started with InfluxDB 1.8.x
2. user with specific read-only permissions to a specific database
3. upgraded to InfluxDB 2.x
4. token generated which represents the legacy user now has broader permissions than expressed in 1.8

**Comment by frankvdbh** [comment]
That is correct..  The user had "write-only" permissions on a database before the upgrade, not possible to read data.
After the upgrade this was no longer enforced and user could also read data. 
Created a new API Token with only Write permissions, used this token in Authorization: Token xyz header and it is still possible to Read data. When modifying some bits of the token the authorization is denied.. So tokens are validated but a scope limited to Write permission is not working

**Comment by jdstrand** [comment]
I can confirm the behavior with `/query`. `/api/v2/query` is not affected and is correctly enforcing.

**Comment by jdstrand** [comment]
FYI, authorization is being performed on `/query` which can be seen by providing a non-existent token and getting back `{"code":"unauthorized","message":"Unauthorized"}`. I'm going to adjust the title accordingly.
