### ISSUE TITLE
influx client needs more test coverage

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#2313]
This issue was exposed by PR #2306. `main_test.go` in `influx` should not be importing main packages, as this is not a valid operation. 

Relevant links:

https://github.com/influxdb/influxdb/pull/2306
https://github.com/golang/go/issues/4210

**Comment by otoolep** [comment]
@corylanou

**Comment by beckettsean** [comment]
@otoolep @corylanou fix or close?

**Comment by corylanou** [comment]
I think keep it open.  The real fix is to move most of the actual "work" to another package (or sub package) and the `main` package becomes just a shell that basically calls into the sub package with a `New` and then `Runs` it, etc.  This will allow us to test without a main package and put these tests back in place.

You can look at the `cmd/influxd/run` package to get an idea about how we are outside of `main` from `cmd/influxd`

I would say this is a beginner to medium task if the community wanted to take a pass at it.

**Comment by pires** [comment]
I'm willing to own this after #4711 #4710 #4704 and #4702 are either merged or closed. I'd like to:
* Refactor history, i.e. don't write to file at all times but only when commands are valid ones
* Improve command parsing including...
* Use `parser` to validate (at least some) statements before sending to server

**Comment by corylanou** [comment]
That sounds awesome!  +1 from me on doing those things.  I'll work on getting the rest of those PR's reviewed today as well so we can get them merged.

**Comment by pires** [comment]
**Attention**: this issue is placeholder for ideas, suggestions or comments related to the aforementioned refactor. I will probably move it to the proper issue when #4711 #4710 #4704 and #4702 are reviewed.

As per @corylanou comments:
> It would be nice in the test to understand if these commands selected the correct "code branch". I understand it isn't possible with the way the current method is written. I'm only bringing it up as it may be something to think about when you refactor the cli main package going forward.

**Comment by corylanou** [comment]
@pires ok, I reviewed them.  Notified the core team we need one more +1 from another core team member and then we will merge.  Thanks for all the hard work!

**Comment by pires** [comment]
Thank you @corylanou.

**Comment by jsternberg** [comment]
I'm closing this since it doesn't have any specific value such as "achieve 80% code coverage". I'm also closing all client related issues and taking those into account for a new client that will be at influxdata/influxdb-client when it's done.
