### ISSUE TITLE
Invalid import path types

### ISSUE THREAD

**Issue by lukasvida** [influxdata/influxdb#23153]
Hello, when I want to use function `types.isType()`, I'm getting this error: `invalid import path types`. 

__Steps to reproduce:__

1. Open influxdb Data explorer
2. Type `import "types"`
3. (optional) Make any query with that function, for example `types.isType(v: 12, type: "int")` as specified in docs.
4. Submit query

__Expected behavior:__
Query gets executed without error.

__Actual behavior:__
Query returns error `invalid import path types`.

__Environment info:__

* System info: Linux 4.19.0-18-amd64 x86_64  - Debian Buster
* InfluxDB version: InfluxDB 2.1.1 (git: 657e1839de) build_date: 2021-11-09T03:03:48Z
* Other relevant environment details: using influxdb for docker,  container uptime: 6 days

**Comment by adamtenhoeve** [comment]
+1 to this topic. We are also having this issue.

**Comment by sanderson** [comment]
@lukasvida @adamtenhoeve The `types` package was introduced in Flux 0.140.0. InfluxDB 2.1.1 ships with 0.139.0. To get a newer version of Flux that supports the `types` package, you have the following options:

- [Build InfluxDB from source](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#building-from-source])
- Wait for the InfluxDB 2.2 release
- Use [InfluxDB Cloud](https://www.influxdata.com/products/influxdb-cloud/)
