### ISSUE TITLE
Credentials redeeming issue

### ISSUE THREAD

**Issue by ai3ansari** [influxdata/influxdb#23158]
Hi,
I am using InfluxDB for the first time for a university research project.
I created a user along with adding organization, password and bucket. Unfortunately, I was not able to use it again for a few days. Now, I wanted to hop onto it again, but I have forgotten my credentials. Every time I try to open, it brings me to this page: http://localhost:8086/signin
Here, I can neither make a request about Forgot Password, nor can I create a new user. I tried to consult InfluxDB Slack Community, but I am getting response of using Token Management either through CLI or API environments which I have no clue of.
I also tried to connect with a customer care rep by setting up a meeting via Chatbot, but they do not appear at the time of meeting.

So, I am creating a new request here in order to get any legit response.

Cheers!

**Comment by lesam** [comment]
So, in the current version you can use `influxd recovery` to[ create a new user,](https://docs.influxdata.com/influxdb/v2.1/reference/cli/influxd/recovery/) give yourself a new auth token, and get back in business. Especially, you'll want to give that new user an operator token with https://docs.influxdata.com/influxdb/v2.1/reference/cli/influxd/recovery/auth/create-operator/ .

**Comment by lesam** [comment]
But ideally we should allow changing a password with this method as well
