### ISSUE TITLE
difference() does not support argument initialZero

### ISSUE THREAD

**Issue by lukasbrun** [influxdata/influxdb#23160]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open the InfluxDB Web GUI
2. Go to Explore and open the Script Editor
3. Post the following query:  
    ```
    import "sampledata"
    
    data = sampledata.int()
      |> yield(name: "raw")
    
    data
      |> difference(nonNegative: true, initialZero: true)
      |> yield(name: "diff")
    ```

__Expected behavior:__
The query is run successfully.

__Actual behavior:__
The following error message is displayed
![grafik](https://user-images.githubusercontent.com/53816889/156568235-5d2cc8d2-a074-46ff-8790-24040bbad3e4.png)

__Environment info:__

* System info: Windows 10 Pro Version 21H2
* InfluxDB version: InfluxDB 2.1.1  
Server: [657e183](https://github.com/influxdata/influxdb/tree/657e1839de)  
Frontend: [cc65325](https://github.com/influxdata/ui/tree/cc65325)
* Other relevant environment details: Containerized on Docker Desktop for Windows  
Container Image: sha256:201d069e915cd2ad945281fc9aafc5d3b3add1c954eb55b40541926c2b01126e

**Comment by sanderson** [comment]
@lukasbrun The `initialZero` parameter was added to `difference()` in Flux v0.143.0. The version of Flux in InfluxDB 2.1.1 is 0.139.0, so it doesn't include this new parameter.

To use a newer version of Flux, you can [build InfluxDB from source](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#building-from-source), wait for the 2.2.0 release, or use InfluxDB Cloud.
