### ISSUE TITLE
User defined flux libraries

### ISSUE THREAD

**Issue by wz2b** [influxdata/influxdb#23179]
__Proposal:__
Create a safe but easy method that allows influxdb administors and developers to add local libraries of flux functions.

__Motivation__
Increasingly I have small (usually) flux functions (as lambdas) that I create then reuse in multiple queries.  Because I do not know of a way to import these functions from an external source I copy and pasting these functions in every query.  This is not desirable for a number of reasons including code maintenance.

__Desired behavior:__
My preferred way to approach this would be to add a 'custom functions' page to the UI to allow users to write their own functions.  Some basic syntax checking would be useful.  These functions would be stored somewhere local - a good candidate might be the influxdb metadata database.

Functions could be created individually, or in packages.  It might be easier to use packages because then they could be named and imported in regular queries explicitly.  I think in the simplest implementation it could be almost like an #include - in fact, it's possible this whole thing could be implemented as 'include' rather than 'import' though importing a user-defined package seems more elegant to me.

__Alternatives considered:__
I considered the idea of having a file specified in config.toml that contains user defined packages, but thinking this through I'm not really in favor of that any longer.  The reason is that when I'm creating/updating this user defined library I really don't want to be stopping and restarting the server.

__Use case:__
I think DRY is the real driver here.  The reason to allow user-defined rather is to avoid polluting the flux ecosystem with a bunch of packages that aren't likely to be used by many query developers.  In some cases, though, I can see the need for shared/community libraries, to leverage community creativity without necessarily having to commit to making changes to the standard flux libraries or forcing more functionality into 'experimental.'

__Security:__
I was initially a little worried that this might cause a security concern but the user defined functions wouldn't use any capabilities that a user couldn't do in a single query.

**Comment by Jayclifford345** [comment]
@nathanielc what are your thoughts on this? To me, this would allow users to clean up a lot of their Flux queries and increase the usability of commonly used common functions.

**Comment by nathanielc** [comment]
This is a great idea, we have captured some similar proposals here https://github.com/influxdata/flux/issues/4296 

This is on our roadmap

**Comment by wz2b** [comment]
Oh boy I'm sorry for the dup ... I searched but didn't use the word 'registry' or I would have found it.

**Comment by nathanielc** [comment]
No worries, glad to see your independent proposal aligns well with what we were already thinking. Closing this and will continue tracking the issue in https://github.com/influxdata/flux/issues/4296

**Comment by rwb196884** [comment]
Is this done now? This _issue_ is all I can find. Pretty sick of copying my function code about.

**Comment by rPraml** [comment]
It seems that there isn't a solution for this... or does anyone has a workaround for this?
My use case: I want to reuse a dictionary in several grafana dashboards
