### ISSUE TITLE
Window influx.exe Passing FLUX via stdin, ctrl-d does not submit stream.

### ISSUE THREAD

**Issue by RobertLivermore** [influxdata/influxdb#23178]
The Influx 2.0 [documentation](https://docs.influxdata.com/influxdb/cloud/query-data/execute-queries/influx-query/#pass-raw-flux-via-stdin-pipe) describes how to enter a FLUX query using standard in pipe. When you complete the query and _ctrl-d_  to submit the query then nothing happens. Expecting to exit the stream and see the results.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Download the CLI [Client 2.2.0](https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.2.0-windows-amd64.zip) and Unzip
2. Create a FLUX query using standard in Pipe
```powershell
.\influx.exe query -
from(bucket: "simlog")
  |> range(start: -1d)
  |> filter(fn: (r) => r["_field"] == "message" or r["_field"] == "summary")
  |> yield()
```
3. _ctrl-d_ 

__Expected behavior:__
Expecting to exit  standard in pipe and see the results.

__Actual behavior:__
Cannot exit the stream

__Environment info:__

- Using Windows 10 - 21H2 build 19044.1586
- [Powershell 7.2.1](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.1)
- CLI 2.2.0
-  Welcome to InfluxDB     {"log_id": "0_7pn5A0000", "version": "2.1.1", "commit": "657e1839de", "build_date": "2021-11-09T03:03:48Z"}

__Config:__
```powershell
.\influxd.exe run `
--engine-path E:\temp\grafana\db\engine `
--bolt-path E:\temp\grafana\db\influxd.bolt `
--sqlite-path E:\temp\grafana\db\influxd.sqlite `
--tls-cert E:\temp\grafana\certs\STAR_actcosys_com.crt `
--tls-key E:\temp\grafana\certs\STAR_actcosys_com.key `
--tls-min-version=1.2
```

**Comment by ypnos** [comment]
Your problem is unrelated to influx cli. What is expected on stdin is EOF. On Windows the mechanism to produce EOF is different to the sane operating systems.
See https://www.devdungeon.com/content/windows-eof-ctrl-d-equivalent for an explanation.

**Comment by RobertLivermore** [comment]
Thanks the _ctrl-z_ with _enter_ worked. 

There is still a bug here. Either the documentation is wrong or the coding is not meeting the _ctrl-d_ requirement.

**Comment by Nick135** [comment]
Problem still present in actual version 2.5 and also no info in the documentation from influxdata.
