### ISSUE TITLE
Flux to() function not caught in replication feature

### ISSUE THREAD

**Issue by samhld** [influxdata/influxdb#23183]
The new remote replication feature seems to intercept new incoming writes but not writes from the Flux `to()` function. In other words, the replication feature only replicates new raw data. Any use cases for replicating downsampled data, event/notification data, etc., are unsupported.

I was not aware that `to()` wrote through a different path but it seems it does. Idk if the "right thing" here is to address this in `to()` or in the replication feature but this use case is likely going to be common if not the most common use case for replicating data from OSS to "remote" (most often Cloud) so we should get a fix for this in as early as possible.

**Comment by lesam** [comment]
`to()` writes to a lower level of the stack, it doesn't go in through the front door of the HTTP API.

Looks like a simple fix though, we just need to pass the right points writer object to flux so it knows where to write.

**Comment by lesam** [comment]
To clarify, `to(host: somehost, ...)` does write through the front door on the remote host. But local writes with `to()` are optimized, we don't have to take a serialize/deserialize through HTTP.
