### ISSUE TITLE
Influx inspect export bug under multiple retention policies in same database

### ISSUE THREAD

**Issue by chengshiwen** [influxdata/influxdb#23196]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a database named `db2`：`CREATE DATABASE db2`
2. Create a rp named `rp2` on `db2`: `CREATE RETENTION POLICY rp2 ON db2 DURATION 0s REPLICATION 1 SHARD DURATION 168h`
3. Write some data into `db2+autogen` and `db2+rp2` separately
4. Now export the data of `db2` with `influx_inspect export`
 - The export file will contain the following lines:
```
# INFLUXDB EXPORT: 1677-09-21T08:18:26+08:05 - 2262-04-12T07:47:16+08:00
# DDL
CREATE DATABASE db2 WITH NAME rp2
CREATE DATABASE db2 WITH NAME autogen
# DML
```
6. Then import the file with `influx -import`, and the following error will occur:
```
retention policy conflicts with an existing policy
```

The reason:

`CREATE DATABASE "db2" WITH NAME "autogen"` will create a database called `db2` with a new **DEFAULT** retention policy and specify the name of that retention policy

__Expected behavior:__
Describe what you expected to happen.

Fix the bug: The correct lines should be:

```
# DDL
CREATE DATABASE db2 WITH NAME autogen
CREATE RETENTION POLICY rp2 ON db2 DURATION 0s REPLICATION 1
```

__Environment info:__

InfluxDB 1.8

**Comment by DStrand1** [comment]
Fixed by #23197
