### ISSUE TITLE
Emailed reset password link sends me to login screen, with "type email to recover password" which Emails me reset password link which sends me to sends me to login screen...

### ISSUE THREAD

**Issue by devjolt** [influxdata/influxdb#23205]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1.
![image](https://user-images.githubusercontent.com/50411536/158588871-196f59b5-c476-4439-8909-166f22f5aefd.png)
https://support.influxdata.com/_nc_external/identity/ui/login/ForgotPasswordInterstitial?r=00D37000000JQwH0051S000007N2UXCjwKMwoPMDBEMzcwMDAwMDBKUXdIEg8wMkczNzAwMDAwMFUwenAaDzAwNTFTMDAwMDA3TjJVWBiSp7KV-S8SEBZ-a0r5yzvxJ_KzC_s8DK8aDCwD9tIFPzhkQR3UaCI5LqUgjdivtCDPJu_E_6OGA8NmN7dhC7hyoHnOPanA0_LCqhA_85W4sXlxrLt3ywLYy81yCCiYgHNO&display=page&fpot=0215b7d5-4e18-423a-b6a5-1d7715f643699d754157-66fc-4455-bad3-4290ad3b68ae

2. 
![image](https://user-images.githubusercontent.com/50411536/158588478-cd353b32-b062-4f85-ace4-b62b92845b04.png)

3. 
![image](https://user-images.githubusercontent.com/50411536/158588584-b4905bdd-f4e4-4dfc-a926-16f3998e5df9.png)

4.
![image](https://user-images.githubusercontent.com/50411536/158588701-d108dda3-9f4d-4f74-9cd4-108414e869ff.png)

5. 
![image](https://user-images.githubusercontent.com/50411536/158589636-b27a5eff-12ca-4a74-bd14-ce474fb477bf.png)

__Expected behavior:__
I expected to get a link to reset my password, click the link, type my well thought out, strong password in twice, click to confirm and then have a new password. 

__Actual behavior:__
I recursively click a link to reset my password, which takes me to a page where I can get a link emailed to me to reset my password as above. It's fun, but just not resetting my password. 

__Environment info:__
Firefox 98.0.1 (64-bit)

**Comment by devjolt** [comment]
So I got this email and somehow clicking this link:
![image](https://user-images.githubusercontent.com/50411536/158595991-d63edf90-5784-401a-a2c8-a7b177b00bf2.png)
worked and got me here:
![image](https://user-images.githubusercontent.com/50411536/158596075-60973e8b-9fd3-444a-9c6c-8e52a7a98a43.png)

This is where I was expecting the other links in the original post to take me. Are the cookies misbehaving?

**Comment by samhld** [comment]
@devjolt this issue has been addressed on our Support side. Will close this out.
