### ISSUE TITLE
Add user-defined token parameter to setup API

### ISSUE THREAD

**Issue by samhld** [influxdata/influxdb#23230]

**Comment by lesam** [comment]
@samhld this already exists - https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/setup/#:~:text=%2Dt,INFLUX_TOKEN

**Comment by coxifred** [comment]
> I think we should close this issue.

No, you're referencing setup option (for the first user [admin], this works)
But we are talking about specify a token value when creating an auth from influx client.

Example;

Just create previously a KingKong user, now i want to create an auth but i want to use a specific token, look what's happening.
The token argument is the API request for this operation, not the final token value.

```sh
influx.client auth create --org gorillaCompany --all-access -d gorillaCompanyClientToken -t JhXtLWDao-xO_lkfrzTOWrqlQEVdi-hOAc59h77YfrYJOKR6feyDOaRUGcdn1t8SdFhdxD1fXgWbeFoJZ728Ew== -u KingKong
ID      Description      Token                                                         User Name        User ID          Permissions
09be98b1fa4a6000        gorillaCompanyClientToken       1cGIkLSmiYOCDwPnIIuvEBotNYjaafavJbVEwYhk4V_KM3xHSMT3slZuqa5tlgfl5p4W1YwAvCu8oyz5BQpL4g==       KingKong 09be988cb68a6000 [read:orgs/0864c388a912f3f8/aut
```

Influx generates a random token.

IDK if it's more clear now.

Fred

**Comment by samhld** [comment]
Yes, sorry, this is meant to say "auth" API @lesam. Will create a new issue so @lesam 's comments don't look weird with a new title.
