### ISSUE TITLE
Can't see or access operator token of new instance

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#23235]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Build from `master`
2. Run `influxd`
3. Go to http://localhost:8086
4. Create the first user

__Expected behavior:__
At some point during this process, the operator of the new instance should be given the opportunity to view / save the operator token. Under the previous version of the UI, there was a page that allowed viewing tokens.

__Actual behavior:__
The operator token is created behind the scenes with no chance for the operator to record it. It can be recovered using command line tools by stopping the instance but this is a bad UX.

__Cause and fix__
This is caused by an upstream change in the UI that is picked up by the OSS during build. As a quick fix for the 2.2 release, we should try pinning the UI to a slightly older version. We'll make the long term fix in 2.3.

**Comment by samhld** [comment]
Closed by #23241
