### ISSUE TITLE
Scraper fails on prometheus NaN metrics

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb#23287]
__Steps to reproduce:__

1. Add a scrape target the has `NaN` values
2. Scrape it

__Expected behavior:__
No errors 

__Actual behavior:__
Log file:

    ts=2022-04-21T06:05:39.347453Z lvl=error msg="Unable to marshal json" log_id=0_zV5qh0000 error="json: unsupported value: NaN"

At this point, no metric is collected.

It seems this behaviour has recently been introduced with the prometheus golang library in 1.12.1: https://github.com/prometheus/client_golang/issues/981. According to spec (see that issue), `NaN` is a value.

A previous issue for `Inf` values was fixed in https://github.com/influxdata/influxdb/issues/10490.

__Environment info:__

InfluxDB 2.0.9
Server: [d1233b7](https://github.com/influxdata/influxdb/tree/d1233b7951)
Frontend: [9c89e22](https://github.com/influxdata/ui/tree/9c89e22)

May be related to https://github.com/influxdata/influxdb/issues/4089

**Comment by andig** [comment]
No feedback? This would impact anyone scraping prometheus metrics produced by a recent prometheus library?

**Comment by Sniper91** [comment]
influxdb don't support NaN  by design.
When encoding float value, it uses NaN as  a sentinel to mark the end of data block. 
https://github.com/influxdata/influxdb/blob/master/tsdb/engine/tsm1/float.go

**Comment by andig** [comment]
> influxdb don't support NaN by design.

...and that exactly is the problem when using Influx to scrape prometheus. It seems though, that prometheus has reverted the change for enabling NaNs.
