### ISSUE TITLE
TLS HTTPS not working in v2.2.0 with systemd script

### ISSUE THREAD

**Issue by michaelbaisch** [influxdata/influxdb#23317]
__Steps to reproduce:__

1. Follow https://docs.influxdata.com/influxdb/v2.2/security/enable-tls/

__Expected behavior:__
InfluxDB API should be served from HTTPS.

__Actual behavior:__
InfluxDB API is served from HTTP.

__Environment info:__

This happened on upgrade from v2.1.1 to v2.2.0. The problem seems to be that the `influxd-systemd-start.sh` is using the `print-config` command that now also outputs a deprecation warning, the script doesn't parse this warning correctly, which means the environment variables needed for TLS HTTPS are not set correctly. See:

https://github.com/influxdata/influxdb/blob/master/scripts/influxd-systemd-start.sh#L8

```bash
$ influxd print-config --key-name http-bind-address
Command "print-config" is deprecated, use the influx-cli command server-config to display the configuration values from the running server
:8086
```

**Comment by michaelbaisch** [comment]
With further investigation I realized that the mentioned lines in `influxd-systemd-start.sh` shouldn't have an effect on influxd launching with or without TLS HTTPS. The problem was that the upgrade wrote a `config.toml` next to my `config.yml` file, which took precedence.

The mentioned lines in `influxd-systemd-start.sh` are nonetheless not working as expected, but this is mostly a problem because it writes confusing things into the influxdb log.

**Comment by felisuco2001** [comment]
i have the same problem, now I'm trying to update the config.toml file, this is the actual look:
bolt-path = "/var/lib/influxdb/influxd.bolt"
engine-path = "/var/lib/influxdb/engine"
tls_cert = "/etc/influxdb/influx.crt"
tls_key = "/etc/influxdb/influx.key"

the syntax looks good, cause when a restart influxd demon, it starts correctly, but the tls is disabled
