### ISSUE TITLE
Show booleans and strings in Dashboards

### ISSUE THREAD

**Issue by JustPrints** [influxdata/influxdb#23329]
__Proposal:__
- Show booleans in a Dashboard (Like a Single Stat) Maybe with a optional history (With a graph)
- Show strings in a Dashboard (Like a Single Stat)

__Current behavior:__
Errors:
-  unsupported input type for mean aggregate: string
-  unsupported input type for mean aggregate: boolean

__Desired behavior:__
A way to display strings and booleans

__Use case:__
Display a machines status with booleans in a Dashboard
Display a error as a string in a Dashboard

**Comment by sanderson** [comment]
@JustPrints The single stat visualization does support string values, but it doesn't support boolean values. However, you can cast your booleans to strings with [`toString()`](https://docs.influxdata.com/flux/v0.x/stdlib/universe/tostring/).

The errors you're getting aren't actually related to the visualization, they're related to the way the data is being downsampled/aggregated. I believe the default aggregate function is `mean`, but you can't calculate and average of string or boolean values. If you change the aggregate function to `last`, it will work.
