### ISSUE TITLE
Building against latest flux fails with `read-only segment has dynamic relocations`

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#23335]
In trying to upgrade OSS to the latest flux, I get this when trying to build `linux-arm64`:
```
/go/pkg/tool/linux_amd64/link: running /usr/local/bin/xcc.sh failed: exit status 1
/usr/local/musl-cross/bin/../lib/gcc/aarch64-unknown-linux-musl/9.2.0/../../../../aarch64-unknown-linux-musl/bin/ld: read-only segment has dynamic relocations
collect2: error: ld returned 1 exit status


Exited with code exit status 2
```

Link to PR where I tried this:
https://github.com/influxdata/influxdb/pull/23331

Link to CI page with error(might go stale):
https://app.circleci.com/pipelines/github/influxdata/influxdb/28346/workflows/0f34a8a1-3e85-45ed-890b-953d62aede10/jobs/254818

**Comment by jeffreyssmith2nd** [comment]
I believe this was resolved with the newer Flux issue in https://github.com/influxdata/influxdb/pull/23348.
