### ISSUE TITLE
Geo temporal flux have error calling function filterRows

### ISSUE THREAD

**Issue by efenaty** [influxdata/influxdb#23334]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1.  Create a bucket (my_bucket in this case) and save usgs data to the bucket using 
```
import "influxdata/influxdb/sample"

sample.data(set: "usgs")
  |> to(
      bucket: "my_bucket"
  )
```
2. Query using 

```
import "experimental/geo"
from(bucket: "my_bucket")
  |> range(start: 2019-11-01T00:00:00Z)
  |> filter(fn: (r) => r["_measurement"] == "earthquake")
  |> filter(fn: (r) => r["_field"] == "lon" or r["_field"] == "lat")
  |> geo.filterRows(region: {minLat: 40.51757813, maxLat: 40.86914063, minLon: -73.65234375, maxLon: -72.94921875})
```

__Expected behavior:__
I was expecting to see a table

__Actual behavior:__
Returned this error 

> error calling function "filterRows" @6:6-6:116: error calling function "gridFilter" @geo.flux|850:24-856:22: error calling function "tableFind" @geo.flux|496:16-496:61: no table found

__Environment info:__

* System info: `Darwin 20.6.0 x86_64`
* InfluxDB version: `InfluxDB 2.2.0 (git: a2f8538837) build_date: 2022-03-29T21:09:26Z`
* Other relevant environment details: `running this query on Influxdb UI. `

__Logs:__

![Screenshot 2022-05-10 at 7 16 14 PM](https://user-images.githubusercontent.com/62544319/167685644-cb588f81-ba99-4459-8c80-afff0b7f988b.png)

**Am I doing something wrong on the queries?**

I used this template for getting started from the documentation.

**Comment by badrbouslikhin** [comment]
I'm running into the same issue.

**Comment by sanderson** [comment]
When using the `usgs` sample data set, `lat` and `lon` are stored as separate fields (as they should be) and, by default, fields are returned in separate tables where each row only has one field value. For `geo.filterRows` to work, each row must have a `lat` and `lon` column. You can use [`geo.shapeData()`](https://docs.influxdata.com/flux/v0.x/stdlib/experimental/geo/shapedata/) to shape your queried data so it will meet the [requirements](https://docs.influxdata.com/flux/v0.x/stdlib/experimental/geo/#geo-schema-requirements) to work with functions in the `geo` package. The code examples in the [referenced blog post](https://www.influxdata.com/blog/exploring-geo-temporal-flux/) are missing this step.

```js
import "experimental/geo"

from(bucket: "blabla")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => r._measurement == "earthquake")
    |> filter(fn: (r) => r._field == "lat" or r._field == "lon")
    |> geo.shapeData(latField: "lat", lonField: "lon", level: 10)
    |> geo.filterRows(region: {...})
```

You can find detailed information about working with geotemporal data in the documentation:

- [Work with geotemporal data](https://docs.influxdata.com/influxdb/v2.4/query-data/flux/geo/)
- [Experimental `geo` package](https://docs.influxdata.com/flux/v0.x/stdlib/experimental/geo/)

**Comment by badrbouslikhin** [comment]
@sanderson thanks for the quick feedback.
In my case, I'm already using `geo.shapeData()`:
```
import "experimental/geo"

from(bucket: "pimule") |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "telemetry")
  |> filter(fn: (r) => r["_field"] == "latitude" or r["_field"] == "longitude")
  |> geo.shapeData(latField: "latitude", lonField: "longitude", level: 24)
  |> group()
  |> sort(columns: ["_time"], desc: false)
  |> geo.filterRows(region: {lat: 50.8384044, lon: 4.3533031, radius: 10.0})
```
I just figured out that `group()` is the cause of the issue.

**Comment by sanderson** [comment]
@badrbouslikhin Ah, gotcha. That makes sense. For `geo.filterRows()` to work, the `s2_cell_id` column has to be part of the group key (noted in the [documentation](https://docs.influxdata.com/flux/v0.x/stdlib/experimental/geo/filterrows/)).
