### ISSUE TITLE
Where is my index directories

### ISSUE THREAD

**Issue by trdmm** [influxdata/influxdb#23345]
**Version: InfluxDB v1.8.3 (git: 1.8 563e6c3d1a7a2790763c6289501095dbec19244e)**
I want to switch inmem to tsi1, i found this doc [https://docs.influxdata.com/influxdb/v1.8/administration/rebuild-tsi-index/#3-remove-all-index-directories](https://docs.influxdata.com/influxdb/v1.8/administration/rebuild-tsi-index/#3-remove-all-index-directories),
```
3. Remove all index directories
Remove all index directories. By default, index directories are stored at /data/<dbName/<rpName>/<shardID>/index.
```
But, the directory only has `xxx.tsm` and `fields.idx`, i can't find `index` directory.
What shoud i do next?

**Comment by IrvingYuanStu** [comment]
I got the same problem.

**Comment by jeffreyssmith2nd** [comment]
If you do not have any index directories, then you are free to just run the `build-tsi` command. The linked guide is specifically for **rebuilding** existing indexes that may have issues. In-Mem doesn't use index files, so if you are switching from that to TSI then that would explain the lack of the `index` folder.
