### ISSUE TITLE
Replications not replicating after remote node failure

### ISSUE THREAD

**Issue by samhld** [influxdata/influxdb#23397]
Multiple community issues have been raised about this: https://community.influxdata.com/t/influxdb-2-2-replication/24841

Reproduce:
1) Start two OSS nodes with access to another
2) Shut down remote note (one being replicated to) or disconnect them in another way for a few minutes
*queue should build up*
3) Start remote note or re-establish connection
4) Data written during queue build-up not replicated to remote node

**Comment by SkyMoCo** [comment]
I am happy to help test this.   I have two instances located about 1000 miles apart.   I have setup replication between the two and see a number of issues.   I can provide any details or changes.   It's non-production so I can run unstable code.
1.   The replication just seems to stop at times, but the "influx replication find" reports a 203 error code.  The queue just keeps growing.
2. Maybe I don't know where to look, but I don't see any details logging as to what is really going on.
3. I don't see any way to pause replication and restart it.

**Comment by samhld** [comment]
@SkyMoCo we have a fix out if you'd like give it a run?

**Comment by SkyMoCo** [comment]
Thanks I love to test it out

**Comment by samhld** [comment]
@SkyMoCo Originally I was thinking you just build from source to get it before the release. We will release within the next 10-16 hours, I would think.
