### ISSUE TITLE
After runinng influxd upgrade command successfully I still see Get Started page 

### ISSUE THREAD

**Issue by Aramayis12** [influxdata/influxdb#23403]
__Steps to reproduce:__
1. sudo apt install influxdb2
2. influxd upgrade --username='admin' --password='adminpass1234' --org='Rudik' --bucket='Kubik' --force"

Upgrade successfully completed. Start the influxd service now, then log in\",\"login_url\":\"http://127.0.0.1:8086\

__Expected behavior:__
I should see influxdb dashboard page

__Actual behavior:__
When I open http://127.0.0.1:8086 link I see Welcome page and there is a button "Get Started". After clicking on the button it redirects me to the "Setup Initial User" page where I need to fill all data again which was already provided in this command `influxd upgrade --username='admin' --password='adminpass1234' --org='Rudik' --bucket='Kubik' --force"` .

__Environment info:__
* Linux 4.9.0-9-amd64 x86_64
* Old version: influxdb InfluxDB v1.8.10 (git: 1.8 688e697c51fd)
* New version: InfluxDB version: InfluxDB v2.2.0 (git: a2f8538837) build_date: 2022-04-06T17:36:40Z

__Config:__
```
bolt-path = "/var/lib/influxdb/influxd.bolt"
engine-path = "/var/lib/influxdb/engine"

http-bind-address = "127.0.0.1:8086"
reporting-disabled = true
```

**Comment by NamSandStorm** [comment]
I have the same issue, any advice / resolution?

**Comment by applicationSPS** [comment]
Some here when do we resolve this, can we get triage on that?

**Comment by NamSandStorm** [comment]
We have found a solution that resolved it for us here:

https://community.influxdata.com/t/data-lost-after-upgrade/21686

**Comment by jeffreyssmith2nd** [comment]
Closing in favor of the community forum solution, please file a new issue if there are any further issues. Thanks!
