### ISSUE TITLE
Do an official build of cmd/influx_tools for internal use only

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influxdb#23411]
We want  a canonical binary version of influx_tools available for internal use by the Support team .

**Comment by davidby-influx** [comment]
@bnpfeife Probably should create a matching backport issue to get this in 1.10 and master-1.x

**Comment by bnpfeife** [comment]
Hey, these PRs should resolve this issue:
https://github.com/influxdata/plutonium/pull/4082 (1.10)
https://github.com/influxdata/plutonium/pull/4083 (1.11)
https://github.com/influxdata/plutonium/pull/4084 (1.x)
