### ISSUE TITLE
lost TSI reference / close TagValueSeriesIDIterator in error case [port to influxdb]

### ISSUE THREAD

**Issue by Joe-Blount** [influxdata/influxdb#23460]
In cloud2 an issue with `TagValueSeriesIDIterator` losing a reference in an error case was fixed via [14876](https://github.com/influxdata/idpe/pull/14876).

This issue is to evaluate the need of backporting the fix to appropriate OSS versions.

**Comment by davidby-influx** [comment]
Ported to master, master-1.x, 1.10, and 1.9 branches.
