### ISSUE TITLE
influx backup missing bucket data

### ISSUE THREAD

**Issue by ZeroSean** [influxdata/influxdb#23480]
**Background:**
  I want to verify `influx backup --bucket xxx`. In testing, the output only is `xxx.bolt.gz、xxx.manifest、xxx.sqlite.gz files` for some bucket,  but on my influxdb instance, there is points on the bucket;

**Steps to reproduce:**
  I dont know how to reproduce

**Expected behavior:**
  Bucket data can be normally backup and restore.

Environment info:
  System info: Linux 4.19.0-10-amd64 Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
  InfluxDB version: InfluxDB 2.2.0
  Influx version: Influx CLI 2.3.0 (git: 88ba3464cd) build_date: 2022-03-18T22:21:12Z

**Comment by jeffreyssmith2nd** [comment]
Hey @ZeroSean can you make sure that when you specify `--bucket` you are providing the bucket name? If you want to provide the id, use `--bucket-id`. 

I was able to reproduce the issue when incorrectly supplying the name to `--bucket` and verified it behaves as expected with the correct flags. Closing as fixed, but feel free to respond if this was not the error.

**Comment by sainipulkit12** [comment]
i am using influxdb 2.0x version ,whic has bucket instead of database. how to backup and restore backup
