### ISSUE TITLE
influxd inspect export-lp doesn't work inside docker

### ISSUE THREAD

**Issue by ivanscattergood** [influxdata/influxdb#23499]
I'm trying to export line protocol data from an influxdb instance running inside docker. 

I'm on windows running Influx inside a docker container using your standard 2.2 distribution: 
(I first discovered this in version 2.3 but the Influx version number had a snapshot suffix, so I wasn't sure if it was really a stable version so I rolled back to 2.2 to confirm it wasn't that)

`docker run -d -p 8086:8086 --name influxdb -v /C/Temp:/var/lib/influxdb2 influxdb:2.2`

**NB** I am binding the output directory to my local c/temp so that the data is not lost during restarts

I can interact with the instance of influx by getting to a bash shell on the container: 

`docker exec -it influxdb bash`

I can see there is a TSM file generated (there is nothing in WAL as I have not written data recently):

 `root@26935d7f5870:/# ls -ltra /var/lib/influxdb2/engine/data/bf21e446eb6d90a9/*/*/*.tsm`

`-rw-r--r-- 1 influxdb influxdb 6862421 Jun 23 02:21 /var/lib/influxdb2/engine/data/bf21e446eb6d90a9/autogen/12/000000010-000000002.tsm`

However if i use the `influxd inspect export-lp` command no data is exported

`root@26935d7f5870:/# influxd inspect export-lp   --bucket-id bf21e446eb6d90a9   --engine-path /var/lib/influxdbv2/engine --log-level debug  --output-path /tmp/export.lp
{"level":"debug","ts":1656399026.1079266,"caller":"export_lp/export_lp.go:213","msg":"searching for TSM files","file_pattern":"/var/lib/influxdbv2/engine/data/bf21e446eb6d90a9/*/*/*.tsm"}
{"level":"info","ts":1656399026.1080494,"caller":"export_lp/export_lp.go:219","msg":"exporting TSM files","tsm_dir":"/var/lib/influxdbv2/engine/data/bf21e446eb6d90a9","file_count":0}
{"level":"debug","ts":1656399026.1081095,"caller":"export_lp/export_lp.go:296","msg":"searching for WAL files","file_pattern":"/var/lib/influxdbv2/engine/wal/bf21e446eb6d90a9/*/*/*.wal"}
{"level":"info","ts":1656399026.1081803,"caller":"export_lp/export_lp.go:315","msg":"exporting WAL files","wal_dir":"/var/lib/influxdbv2/engine/wal/bf21e446eb6d90a9","file_count":0}
{"level":"info","ts":1656399026.108233,"caller":"export_lp/export_lp.go:204","msg":"export complete"}`

**NB** Although there is a tsm file inside the directory mentioned, the filecount is zero and the export.lp file generated in empty. 

What am I doing wrong?

**Comment by robkamp** [comment]
I have the same issue. 

My docker is deployed on TrueNAS Scale
