### ISSUE TITLE
Support v1 dbrp names as bucket IDs in replications API

### ISSUE THREAD

**Issue by samhld** [influxdata/influxdb#23550]
v1 does not support the concept of a bucket ID and replications currently require bucket IDs (with a length of 16 bytes). This makes replications to v1 currently impossible. 

So far I can think of two options:
 - Have v1 treat dbrps like dbrp == bucket name == bucket ID. Replications would need to allow for "ID"s of different length than 16 bytes.
 - Have replications accept a `--remote-bucket-name` flag for these cases. We could simply document that this isn't as safe as using an ID (for v2 users that have the option)

**Comment by lesam** [comment]
I think what makes the most sense is doing both. Enterprise already accepts bucket name == bucket id == dbrp for deletes IIRC, so that makes sense. And allowing people to give a bucket name instead of an id for replications also seems like good UX.
