### ISSUE TITLE
Authorization not found when running influxdb 2.x in compose

### ISSUE THREAD

**Issue by pushc6** [influxdata/influxdb#23589]
Everything seems to start fine, I can log in, but when trying to create API tokens, I am never presented with the token, but it says it was created successfully. 

Looking at the logs I see:

ts=2022-07-27T16:30:01.250710Z lvl=info msg=Unauthorized log_id=0bx7jsPW000 error="session not found"
ts=2022-07-27T16:30:05.854053Z lvl=info msg=Unauthorized log_id=0bx7jsPW000 error="authorization not found"
ts=2022-07-27T16:30:08.060165Z lvl=info msg=Unauthorized log_id=0bx7jsPW000 error="authorization not found"
ts=2022-07-27T16:30:09.173151Z lvl=info msg=Unauthorized log_id=0bx7jsPW000 error="authorization not found"
ts=2022-07-27T16:30:11.393559Z lvl=info msg=Unauthorized log_id=0bx7jsPW000 error="authorization not found"
ts=2022-07-27T16:31:06.948966Z lvl=info msg=Unauthorized log_id=0bx7jsPW000 error="authorization not found"
ts=2022-07-27T16:31:09.170845Z lvl=info msg=Unauthorized log_id=0bx7jsPW000 error="authorization not found"

Here is my docker-compose.yml

 influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    privileged: true
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=hlab-influxdb
      - DOCKER_INFLUXDB_INIT_USERNAME=labuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=pw
      - DOCKER_INFLUXDB_INIT_ORG=home-lab
      - DOCKER_INFLUXDB_INIT_RETENTION=365d
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

**Comment by jeffreyssmith2nd** [comment]
Are you creating the token through the UI? If so, once it is created you need to click on the name of the token to actually be able to see it.

**Comment by pushc6** [comment]
> Are you creating the token through the UI? If so, once it is created you need to click on the name of the token to actually be able to see it.

Oh mother lover, I clicked ALL the things except the actual name of the token. I was looking at examples online and it looked like it displayed it right away and you captured it then and then it was never retrievable again. I figured that was the case with the banner text warning you could only access them once. This resolved my issue, thank you very much @jeffreyssmith2nd

**Comment by sezanzeb** [comment]
> Tokens are found under the Load Data menu item under API tokens.

ah, thanks

**Comment by sezanzeb** [comment]
shouldn't this be "forbidden" 403 then?

**Comment by jeffreyssmith2nd** [comment]
I would say not, because in your case you are currently missing authentication entirely.

```
This status is similar to [401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401), but for the 403 Forbidden status code, re-authenticating makes no difference. The access is tied to the application logic, such as insufficient rights to a resource.
```

**Comment by RuTpasswd** [comment]
I am facing the same issue. deployed a helm chart and also created a user with a password inside the pod. but i'm getting "authorization not found", "session not found"
