### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by Conyboy** [influxdata/influxdb#23595]
data write error.
I wirte the same data to influxdb with different time.
2022-01-02 23:45:00 is OK, 2022-01-03 00:00:00 reports the error as follows.
=============================================================
ts=2022-08-01T09:00:13.829576Z lvl=error msg="a panic has occurred" log_id=0c1kFSR0000 handler=panic error="/api/v2/write?bucket=wind-power&org=wlw&precision=ns: runtime error: integer divide by zero" stacktrace="goroutine 643103 [running]:
runtime/debug.Stack()
/home/circleci/.tools/go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/influxdb/v2/http.baseHandler.panic({{0x4058600, 0xc0082a9620}}, {0x4077400, 0xc02551a100}, 0x6, {0x3c52600, 0x53e34a0})
/home/circleci/go/src/github.com/influxdata/influxdb/http/router.go:96 +0x1b3
github.com/influxdata/httprouter.(*Router).recv(0xc01871b9e0, {0x4077400, 0xc02551a100}, 0xd)
/home/circleci/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:361 +0x5e
panic({0x3c52600, 0x53e34a0})
/home/circleci/.tools/go/src/runtime/panic.go:1038 +0x215
github.com/influxdata/influxdb/v2/v1/services/meta.(*ShardGroupInfo).ShardFor(...)
/home/circleci/go/src/github.com/influxdata/influxdb/v1/services/meta/data.go:1439
github.com/influxdata/influxdb/v2/v1/coordinator.(*PointsWriter).MapShards(0xc000342680, 0xc00fec8658)
/home/circleci/go/src/github.com/influxdata/influxdb/v1/coordinator/points_writer.go:237 +0x678
github.com/influxdata/influxdb/v2/v1/coordinator.(*PointsWriter).WritePointsPrivileged(0xc000342680, {0x40a6bc0, 0xc02d742510}, {0xc0498765b0, 0x415f07}, {0x238fa4a, 0x3eadf80}, 0x1, {0xc01174c000, 0x21e2, ...})
/home/circleci/go/src/github.com/influxdata/influxdb/v1/coordinator/points_writer.go:361 +0x189
github.com/influxdata/influxdb/v2/v1/coordinator.(*PointsWriter).WritePoints(0xc00fec8748, {0x40a6bc0, 0xc02d742510}, {0xc0498765b0, 0x203009}, {0x238fa4a, 0x10100c02551a380}, 0x7f9804db8fa8, {0x40b92c8, 0xc02d742990}, ...)
/home/circleci/go/src/github.com/influxdata/influxdb/v1/coordinator/points_writer.go:340 +0x5c
github.com/influxdata/influxdb/v2/storage.(*Engine).WritePoints(0xc00026e300, {0x40a6bc0, 0xc02d742510}, 0xc02551a380, 0x0, {0xc01174c000, 0x21e2, 0x21e3})
/home/circleci/go/src/github.com/influxdata/influxdb/storage/engine.go:265 +0x204
github.com/influxdata/influxdb/v2/storage.(*LoggingPointsWriter).WritePoints(0xc06d5fafc0, {0x40a6bc0, 0xc02d742510}, 0x7484ec425f9b341a, 0xc01da74d3a, {0xc01174c000, 0x21e2, 0x21e3})
/home/circleci/go/src/github.com/influxdata/influxdb/storage/points_writer.go:38 +0xd1
github.com/influxdata/influxdb/v2/http.(*WriteHandler).handleWrite(0xc09a7580e0, {0x4077400, 0xc02551a100}, 0x10000c01c56bc28)
/home/circleci/go/src/github.com/influxdata/influxdb/http/write_handler.go:192 +0x54b
net/http.HandlerFunc.ServeHTTP(0x100000000000000, {0x4077400, 0xc02551a100}, 0x90)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/influxdata/httprouter.(*Router).Handler.func1({0x4077400, 0xc02551a100}, 0x3c4d440, {0x0, 0x3b69c00, 0xc06d830cb0})
/home/circleci/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:325 +0x2c4
github.com/influxdata/httprouter.(*Router).ServeHTTP(0xc01871b9e0, {0x4077400, 0xc02551a100}, 0xc0505e6f00)
/home/circleci/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:453 +0x4c3
github.com/influxdata/influxdb/v2/http.(*WriteHandler).ServeHTTP(0xd, {0x4077400, 0xc02551a100}, 0x6f5a6f)
/home/circleci/go/src/github.com/influxdata/influxdb/http/write_handler.go:135 +0x27
github.com/go-chi/chi.(*Mux).Mount.func1({0x4077400, 0xc02551a100}, 0xc0505e6f00)
/home/circleci/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298 +0x13b
net/http.HandlerFunc.ServeHTTP(0x3c2d5a0, {0x4077400, 0xc02551a100}, 0xc049876140)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc008396360, {0x4077400, 0xc02551a100}, 0xc0505e6f00)
/home/circleci/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x1f9
net/http.HandlerFunc.ServeHTTP(0xc0835cbdd0, {0x4077400, 0xc02551a100}, 0xc00fec90b8)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/influxdata/influxdb/v2/kit/transport/http.SetCORS.func1({0x4077400, 0xc02551a100}, 0xc0505e6f00)
/home/circleci/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:36 +0x308
net/http.HandlerFunc.ServeHTTP(0x0, {0x4077400, 0xc02551a100}, 0x203009)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/go-chi/chi/middleware.StripSlashes.func1({0x4077400, 0xc02551a100}, 0xc0505e6f00)
/home/circleci/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/middleware/strip.go:25 +0x102
net/http.HandlerFunc.ServeHTTP(0xc0835cbdd0, {0x4077400, 0xc02551a100}, 0x30)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/influxdata/influxdb/v2/kit/transport/http.SkipOptions.func1({0x4077400, 0xc02551a100}, 0xc0505e6f00)
/home/circleci/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:81 +0xb9
net/http.HandlerFunc.ServeHTTP(0xc0835cbe90, {0x4077400, 0xc02551a100}, 0xc00fec9238)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/influxdata/influxdb/v2/http.panicMW.func1.1({0x4077400, 0xc02551a100}, 0xc00fec92f0)
/home/circleci/go/src/github.com/influxdata/influxdb/http/router.go:126 +0x9b
net/http.HandlerFunc.ServeHTTP(0x90, {0x4077400, 0xc02551a100}, 0x1000000023dd680)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc008396360, {0x4077400, 0xc02551a100}, 0xc0505e6f00)
/home/circleci/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:70 +0x40e
github.com/influxdata/influxdb/v2/kit/feature.(*Handler).ServeHTTP(0xc04d9277c0, {0x4077400, 0xc02551a100}, 0xc0505e6e00)
/home/circleci/go/src/github.com/influxdata/influxdb/kit/feature/middleware.go:43 +0x3c2
github.com/influxdata/influxdb/v2/http.(*AuthenticationHandler).ServeHTTP(0xc09386de30, {0x4077400, 0xc02551a100}, 0xc0505e6d00)
/home/circleci/go/src/github.com/influxdata/influxdb/http/authentication_middleware.go:127 +0x467
github.com/influxdata/influxdb/v2/kit/transport/http.SetCORS.func1({0x4077400, 0xc02551a100}, 0xc0505e6d00)
/home/circleci/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:36 +0x308
net/http.HandlerFunc.ServeHTTP(0xc0835cbdd0, {0x4077400, 0xc02551a100}, 0xc049876141)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/influxdata/influxdb/v2/kit/transport/http.SkipOptions.func1({0x4077400, 0xc02551a100}, 0xc0505e6d00)
/home/circleci/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:81 +0xb9
net/http.HandlerFunc.ServeHTTP(0x33d8a90, {0x4077400, 0xc02551a100}, 0xc)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/influxdata/influxdb/v2/http.(*PlatformHandler).ServeHTTP(0xc03f3fa040, {0x4077400, 0xc02551a100}, 0xc0505e6d00)
/home/circleci/go/src/github.com/influxdata/influxdb/http/platform_handler.go:81 +0x1d2
github.com/go-chi/chi.(*Mux).Mount.func1({0x4077400, 0xc02551a100}, 0xc0505e6d00)
/home/circleci/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298 +0x13b
net/http.HandlerFunc.ServeHTTP(0x203009, {0x4077400, 0xc02551a100}, 0xc02551a0e0)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/influxdata/influxdb/v2/kit/transport/http.Metrics.func1.1({0x407c1d0, 0xc00c8f8620}, 0xc0505e6d00)
/home/circleci/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:66 +0x1e2
net/http.HandlerFunc.ServeHTTP(0xc0044c1830, {0x407c1d0, 0xc00c8f8620}, 0x702dc5)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/influxdata/influxdb/v2/kit/transport/http.Trace.func1.1({0x407c1d0, 0xc00c8f8620}, 0x1)
/home/circleci/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:106 +0x30c
net/http.HandlerFunc.ServeHTTP(0xc0388698c0, {0x407c1d0, 0xc00c8f8620}, 0xc050272c78)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0x3c2d5a0, {0x407c1d0, 0xc00c8f8620}, 0xc01da74d25)
/home/circleci/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/chain.go:31 +0x2c
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0083f4cc0, {0x407c1d0, 0xc00c8f8620}, 0xc0505e6c00)
/home/circleci/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x1f9
net/http.HandlerFunc.ServeHTTP(0x88, {0x407c1d0, 0xc00c8f8620}, 0x90)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/influxdata/influxdb/v2/http.(*AddHeader).Middleware.func1({0x407c1d0, 0xc00c8f8620}, 0x53c4e01)
/home/circleci/go/src/github.com/influxdata/influxdb/http/handler.go:102 +0x77
net/http.HandlerFunc.ServeHTTP(0x40a6b18, {0x407c1d0, 0xc00c8f8620}, 0x53c4e90)
/home/circleci/.tools/go/src/net/http/server.go:2046 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0083f4cc0, {0x407c1d0, 0xc00c8f8620}, 0xc0505e6a00)
/home/circleci/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:86 +0x3c2
github.com/influxdata/influxdb/v2/http.(*Handler).ServeHTTP(0xc01da74d33, {0x407c1d0, 0xc00c8f8620}, 0x40)
/home/circleci/go/src/github.com/influxdata/influxdb/http/handler.go:166 +0x2f
net/http.serverHandler.ServeHTTP({0x4072558}, {0x407c1d0, 0xc00c8f8620}, 0xc0505e6a00)
/home/circleci/.tools/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0006412c0, {0x40a6bc0, 0xc04f73a150})
/home/circleci/.tools/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
/home/circleci/.tools/go/src/net/http/server.go:3033 +0x4e8
"

**Comment by Conyboy** [comment]
there is OK when i create a new bucket. 
old bucket has writen the data, that time is before 2022-01-03 00:00:00 and after 2022-01-03 00:00:00.

**Comment by Conyboy** [comment]
my influxdb version is 2.1 docker verison.

**Comment by Conyboy** [comment]
Finally, a solution was found.

If you have less historical data, you can do this:
step 1: create new bucket.
step 2: execute follows command. starttime: the begin of your all data, endtime: the time of error
`influx query 'from(bucket: "old-bucket") |> range(start: 1970-01-01T00:00:00Z, stop: 2022-01-02T23:59:59Z) |> to(bucket: "new-bucket", org: "org") > null'`  

then you can execute your write command.

If you have big historical data, you can do this:
step 1: backup your bucket. `influx backup --bucket example-bucket /path/to/backup/dir/`
step 2: open the file named 'XXXXXXXXTXXXXXXZ.manifest', find the shardGroups item, delete all sub_item after the sub_item that shards item is empty array. 
step 3: restore the backup to new bucket, `influx restore  --bucket example-bucket  --new-bucket new-example-bucket   /path/to/backup/dir/`

then you can execute your write command.

**Comment by jjungo** [comment]
I'm encountering the same issue with versions 2.7.4 (19e5c0e) and 2.7.3 (ed645d9). Copying data into a fresh bucket seems to make the problem disappear. However, I'm uncertain if this is a wise long-term solution.

**Comment by jjungo** [comment]
There is my stack trace:
```ts=2023-11-22T09:32:41.724095Z lvl=error msg="a panic has occurred" log_id=0leaq9V0000 handler=panic error="/api/v2/write?org=my_org&bucket=my_bucket&precision=s: runtime error: integer divide by zero" stacktrace="goroutine 4791173 [running]:

runtime/debug.Stack()
	/go/src/runtime/debug/stack.go:24 +0x65

github.com/influxdata/influxdb/v2/http.baseHandler.panic({{0x7f30893964c0?, 0xc002c5d680?}}, {0x7f30893a4c50, 0xc0012eb800}, 0x7f3088eef2e0?, {0x7f3088fe0240, 0x7f308a5aa870})
	/root/project/http/router.go:96 +0x1a5

github.com/influxdata/httprouter.(*Router).recv(0xc002dae1b0, {0x7f30893a4c50, 0xc0012eb800}, 0x15645a?)
	/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:361 +0x5e

panic({0x7f3088fe0240, 0x7f308a5aa870})
	/go/src/runtime/panic.go:884 +0x213

github.com/influxdata/influxdb/v2/v1/services/meta.(*ShardGroupInfo).ShardFor(...)
	/root/project/v1/services/meta/data.go:1439

github.com/influxdata/influxdb/v2/v1/coordinator.(*PointsWriter).MapShards(0xc0018d5200, 0xc002014660)
	/root/project/v1/coordinator/points_writer.go:260 +0x8db
github.com/influxdata/influxdb/v2/v1/coordinator.(*PointsWriter).WritePointsPrivileged(0xc0018d5200, {0x7f30893aa238?, 0xc0088ad6b0}, {0xc0062ffb30, 0x10}, {0x7f30880fe47b, 0x7}, 0xc0062ffb01?, {0xc0064dc000, 
0xbb8, ...})
	/root/project/v1/coordinator/points_writer.go:384 +0x1ab
github.com/influxdata/influxdb/v2/v1/coordinator.(*PointsWriter).WritePoints(0xc4?, {0x7f30893aa238?, 0xc0088ad6b0?}, {0xc0062ffb30?, 0xedcefc1b9?}, {0x7f30880fe47b?, 0xc007dc6450?}, 0xc00694ab40?, 
{0x7f30893b7428, 0xc0088ada70}, ...)
	/root/project/v1/coordinator/points_writer.go:364 +0x5c

github.com/influxdata/influxdb/v2/storage.(*Engine).WritePoints(0xc0018fc600, {0x7f30893aa238, 0xc0088ad6b0}, 0x55d78?, 0x29be7d31?, {0xc0064dc000, 0xbb8, 0xbb8})
	/root/project/storage/engine.go:278 +0x20b

github.com/influxdata/influxdb/v2/replications.(*service).WritePoints(0xc001791cb0, {0x7f30893aa238?, 0xc0088ad6b0}, 0xe618a1f2fe58b871, 0x8f6617f79025e16b, {0xc0064dc000?, 0xbb8, 0xbb8})
	/root/project/replications/service.go:341 +0xf7

github.com/influxdata/influxdb/v2/storage.(*LoggingPointsWriter).WritePoints(0xc002d526c0, {0x7f30893aa238, 0xc0088ad6b0}, 0xe618a1f2fe58b871, 0xc003aa960a?, {0xc0064dc000, 0xbb8, 0xbb8})
	/root/project/storage/points_writer.go:38 +0xd1

github.com/influxdata/influxdb/v2/http.(*WriteHandler).handleWrite(0xc0000abc00, {0x7f30893a4c50?, 0xc0012eb800}, 0x7f3089210060?)
	/root/project/http/write_handler.go:192 +0x526

net/http.HandlerFunc.ServeHTTP(0x7f3089342320?, {0x7f30893a4c50?, 0xc0012eb800?}, 0x7f308585d108?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/influxdata/httprouter.(*Router).Handler.func1({0x7f30893a4c50?, 0xc0012eb800?}, 0x7f3088fdb440?, {0x0?, 0x7f3088eefee0?, 0xc0053b8820?})
	/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:325 +0x196

github.com/influxdata/httprouter.(*Router).ServeHTTP(0xc002dae1b0, {0x7f30893a4c50, 0xc0012eb800}, 0xc00490e900)
	/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:453 +0x375

github.com/influxdata/influxdb/v2/http.(*WriteHandler).ServeHTTP(0xc0062ff900?, {0x7f30893a4c50?, 0xc0012eb800?}, 0x7f3086aeb279?)
	/root/project/http/write_handler.go:135 +0x27

github.com/go-chi/chi.(*Mux).Mount.func1({0x7f30893a4c50, 0xc0012eb800}, 0xc00490e900)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298 +0x172

net/http.HandlerFunc.ServeHTTP(0x7f3088fc3e40?, {0x7f30893a4c50?, 0xc0012eb800?}, 0xc0062ff900?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/go-chi/chi.(*Mux).routeHTTP(0xc002d80660, {0x7f30893a4c50, 0xc0012eb800}, 0xc00490e900)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x1f9

net/http.HandlerFunc.ServeHTTP(0xc0088ad290?, {0x7f30893a4c50?, 0xc0012eb800?}, 0x110?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/influxdata/influxdb/v2/kit/transport/http.SetCORS.func1({0x7f30893a4c50, 0xc0012eb800}, 0xc00490e900)
	/root/project/kit/transport/http/middleware.go:48 +0x308

net/http.HandlerFunc.ServeHTTP(0x5?, {0x7f30893a4c50?, 0xc0012eb800?}, 0x80?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/go-chi/chi/middleware.StripSlashes.func1({0x7f30893a4c50, 0xc0012eb800}, 0xc00490e900)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/middleware/strip.go:25 +0x102

net/http.HandlerFunc.ServeHTTP(0xc0088ad290?, {0x7f30893a4c50?, 0xc0012eb800?}, 0xc0018d2c00?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/influxdata/influxdb/v2/kit/transport/http.SkipOptions.func1({0x7f30893a4c50, 0xc0012eb800}, 0xc00490e900)
	/root/project/kit/transport/http/middleware.go:93 +0xb9

net/http.HandlerFunc.ServeHTTP(0x0?, {0x7f30893a4c50?, 0xc0012eb800?}, 0x7f3088fc69c0?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/influxdata/influxdb/v2/http.panicMW.func1.1({0x7f30893a4c50?, 0xc0012eb800?}, 0x7f30893c3c40?)
	/root/project/http/router.go:126 +0x92

net/http.HandlerFunc.ServeHTTP(0xc00490e900?, {0x7f30893a4c50?, 0xc0012eb800?}, 0x7f3089342320?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/go-chi/chi.(*Mux).ServeHTTP(0xc002d80660, {0x7f30893a4c50, 0xc0012eb800}, 0xc00490e900)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:70 +0x2dc

github.com/influxdata/influxdb/v2/kit/feature.(*Handler).ServeHTTP(0xc002dc29c0, {0x7f30893a4c50, 0xc0012eb800}, 0xc00490e800)
	/root/project/kit/feature/middleware.go:43 +0x29b

github.com/influxdata/influxdb/v2/http.(*AuthenticationHandler).ServeHTTP(0xc0000ab1f0, {0x7f30893a4c50, 0xc0012eb800}, 0xc00490e700)
	/root/project/http/authentication_middleware.go:127 +0x336

github.com/influxdata/influxdb/v2/kit/transport/http.SetCORS.func1({0x7f30893a4c50, 0xc0012eb800}, 0xc00490e700)
	/root/project/kit/transport/http/middleware.go:48 +0x308

net/http.HandlerFunc.ServeHTTP(0xc0088ad290?, {0x7f30893a4c50?, 0xc0012eb800?}, 0xc0062ff900?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/influxdata/influxdb/v2/kit/transport/http.SkipOptions.func1({0x7f30893a4c50, 0xc0012eb800}, 0xc00490e700)
	/root/project/kit/transport/http/middleware.go:93 +0xb9

net/http.HandlerFunc.ServeHTTP(0x7f30885aa540?, {0x7f30893a4c50?, 0xc0012eb800?}, 0xc?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/influxdata/influxdb/v2/http.(*PlatformHandler).ServeHTTP(0xc002dc2b00, {0x7f30893a4c50, 0xc0012eb800}, 0xc00490e700)
	/root/project/http/platform_handler.go:84 +0x1d2

github.com/go-chi/chi.(*Mux).Mount.func1({0x7f30893a4c50, 0xc0012eb800}, 0xc00490e700)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298 +0x172

net/http.HandlerFunc.ServeHTTP(0x16?, {0x7f30893a4c50?, 0xc0012eb800?}, 0xbf?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/influxdata/influxdb/v2/kit/transport/http.Metrics.func1.1({0x7f30893a7ce0?, 0xc001c3a8c0}, 0xc00490e700)
	/root/project/kit/transport/http/middleware.go:78 +0x1d0

net/http.HandlerFunc.ServeHTTP(0xc002015850?, {0x7f30893a7ce0?, 0xc001c3a8c0?}, 0x0?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/influxdata/influxdb/v2/kit/transport/http.Trace.func1.1({0x7f30893a7ce0, 0xc001c3a8c0}, 0x1?)
	/root/project/kit/transport/http/middleware.go:118 +0x312

net/http.HandlerFunc.ServeHTTP(0xc002dc69c0?, {0x7f30893a7ce0?, 0xc001c3a8c0?}, 0xc002552f78?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0x7f3088fc3e40?, {0x7f30893a7ce0?, 0xc001c3a8c0?}, 0xc003aa95e5?)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/chain.go:31 +0x2c

github.com/go-chi/chi.(*Mux).routeHTTP(0xc002daafc0, {0x7f30893a7ce0, 0xc001c3a8c0}, 0xc00490e600)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x1f9

net/http.HandlerFunc.ServeHTTP(0x7f3089342320?, {0x7f30893a7ce0?, 0xc001c3a8c0?}, 0x7f308585d108?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/influxdata/influxdb/v2/http.(*AddHeader).Middleware.func1({0x7f30893a7ce0, 0xc001c3a8c0}, 0x7f308a597a01?)
	/root/project/http/handler.go:102 +0x77

net/http.HandlerFunc.ServeHTTP(0x7f30893aa190?, {0x7f30893a7ce0?, 0xc001c3a8c0?}, 0x7f308a597a90?)
	/go/src/net/http/server.go:2122 +0x2f

github.com/go-chi/chi.(*Mux).ServeHTTP(0xc002daafc0, {0x7f30893a7ce0, 0xc001c3a8c0}, 0xc00490e500)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:86 +0x296

github.com/influxdata/influxdb/v2/http.(*Handler).ServeHTTP(0xc003aa95f3?, {0x7f30893a7ce0?, 0xc001c3a8c0?}, 0x7f30864115b4?)
	/root/project/http/handler.go:166 +0x2f

net/http.serverHandler.ServeHTTP({0x7f30893a0438?}, {0x7f30893a7ce0, 0xc001c3a8c0}, 0xc00490e500)
	/go/src/net/http/server.go:2936 +0x316

net/http.(*conn).serve(0xc0046eb7a0, {0x7f30893aa238, 0xc002dc7800})
	/go/src/net/http/server.go:1995 +0x612

created by net/http.(*Server).Serve
	/go/src/net/http/server.go:3089 +0x5ed
```

I'm very not familiar with go and I am not confident but I think this [line](https://github.com/influxdata/influxdb/blob/19e5c0e1b7c40f95fd9d70d51c72281d2d4b4b6b/v1/services/meta/data.go#L1439-L1440) is raising a panic.
