### ISSUE TITLE
API: allow upload of telegraf.conf config file via API

### ISSUE THREAD

**Issue by Space2Man** [influxdata/influxdb#23596]
__Proposal:__
Currently it's only possible to upload a telegraf.conf via influx CLI. It would be nice to have an option to upload / update a telegraf.conf file API as well.

__Current behavior:__
No option to upload/update telegraf.conf file via API

__Desired behavior:__
Use API to upload / update telegraf.conf file.

__Alternatives considered:__
Currently only possible via influx CLI

__Use case:__
For automation purposes we would like to upload a telegraf.conf which we pre-generate by our orchestration service. All other steps (bucket creation, token creation, etc.) can be done via API but not the upload of an existing telegraf.conf file.

**Comment by jeffreyssmith2nd** [comment]
Does this endpoint meet your needs? https://docs.influxdata.com/influxdb/v2.3/api/#operation/PostTelegrafs

**Comment by Space2Man** [comment]
Well, I have seen that endpoint. But how can I upload a whole telegraf.conf file via that API? To me it's not clear how I could create e.g. an input.http_response plugin with *lots* of parameters via this API. Or do I only have to convert the telegraf.conf to some kind of json?

**Comment by jeffreyssmith2nd** [comment]
I believe you can just give it the following 4 fields properly filled out, where the config is just the string of the entire telegraph config file. That is what the cli is doing when you call `influx telegraf create`
```
Name:        "",
Description: "",
Config:      "",
OrgID:       "",
```

**Comment by Space2Man** [comment]
Ah, thanks! I will test that tomorrow morning! Thanks!

**Comment by Space2Man** [comment]
Hi, Thanks for that hint ... I had tried that but to get it working you need to replace each " in the config file with \" and also replace newlines with \n. Then it's working fine!
