### ISSUE TITLE
API (cloud) /dbrps POST: parameter 'default' is always set to true.  

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#23600]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Using the API send a POST request to `/dbrps` with the property `default` set to false

example from grace tests. 

```javascript
  describe.only('troubleshoot', () => {
    it('creates a dbrps with default=false', async () => {

      let resp = await request(url)
        .post('/dbrps')
        .set('Authorization', `Token ${alt.getAuth().token}`)
        .set('Content-Type', 'application/json')
        .send(
          JSON.stringify({
            orgID: alt.getOrg().id,
            bucketID: alt.getBucket().id,
            database: 'foo',
            retention_policy: 'bar',
            default: false,
            links: {},
          })
        )

      await log.cout(log.level.debug, `resp ${log.objFmt(resp)}`)
      await log.cout(log.level.debug, `resp.body ${log.objFmt(resp.body)}`)
      expect(resp.body.default).to.be.false

    })
  })
```

__Expected behavior:__
That the created DBRP mapping would have the default value set as defined in the request object.

__Actual behavior:__

From running the above test.  

<pre>
...
 DEBUG: resp {
  ...
   "status": 201,
  ...
}
 DEBUG: resp.body {
   "id": "09c3aa0dbdbe1000",
   "database": "foo",
   "retention_policy": "bar",
   <b>"default": true,</b>
   "orgID": "2b83f4fbef22236f",
   "bucketID": "0fd507409b6bc01f"
}
      1) creates a dbrps with default=false
 ...

  0 passing (10s)
  1 failing

  1) Dbrps
       troubleshoot
         creates a dbrps with default=false:

      AssertionError: <b>expected true to be false</b>
      + expected - <b>actual</b>

      <b>-true</b>
      +false
      
      at Context.<anonymous> (test/beta/dbrps.test.js:827:38)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
...
</pre>

__Environment info:__
Testing against K8SIDPE remocal 

latest K8SIDPE commit 

```
commit 64130b73dc7942115ec1a57147ee8fdf26d7ce58 (HEAD -> master, origin/master, origin/HEAD)
Author: influx-acs[bot] <107396960+influx-acs[bot]@users.noreply.github.com>
Date:   Tue Aug 2 07:24:50 2022 +0000

    chore: apply new influxdb_iox images for fec6b18d80 (#9288)
    
    Autocommit-INFLUXDB_IOX-SHA: fec6b18d80d60ae54c1336d42eaff364202c0b92
    Autocommit-Reason: new images published
    
    Co-authored-by: Hercules Mango Churchill <alchemy@influxdata.com>
```

**N.B. /dbrps/{dbrpID} PATCH**

When patching the parameter `default` to be *false*, the request is accepted and the response object shows `default` is in fact _false_.  So why does POST always return `{..., default:true}`?

**Comment by alespour** [comment]
This is correct behavior. If there is no DBRP mapping, newly created one is automatically set as default. Since 2.5.0, there are virtual mapping provided by default, so the behavior is: if there no non-virtual mapping for given bucket, newly created one is set as default.
