### ISSUE TITLE
InfluxDB 2 bug: record is missing label timeRangeStart/timeRangeStop

### ISSUE THREAD

**Issue by matas3logytech** [influxdata/influxdb#23624]
__General background about the setup:__

- There is an MQTT network sending IoT data to a raspberry Pi
- Raspberry pi runs a python script to upload data to influxdb (in real time)
- Currently uploading data every 3s
- Each upload is a list of lines, each line being measurement/tag_set/field_set/timestamp format
- Upload method is by using python paho mqtt, and line protocol

Essentially, this setup now works, data is at the database, and it is being visualized in a dashboard. However, when the dashboard is running and displaying real-time sensor data, it works for a bit and then shows these errors. Every time. After the crash, when I go inside a widget, I cannot submit a new query and cannot see any raw data anymore… It’s like a timerangestart and timerangestop data goes missing…
The dashboard works once again after the page is refreshed. So I am really confused on why that happens, what caused it, and how to fix it.

Note: I now realize that refreshing every 1s gives this error in a couple of minutes, refreshing every 5s gives the error within ~20 minutes, refreshing every 10s gives the error within less than an hour… It’s almost as if some limit is reached, and refreshing the page is the temporary fix. While refreshing the page is a good temporary solution to display data, I cannot keep refreshing this page every few minute when it breaks, at the moment this dashboard looks unstable and unreliable.

Please refer to the screenshots to better understand the issue:
1. Working at 12:54 12/08/2022
https://ibb.co/XZYNwbm

2. Crashed at 12:55 12/08/2022
https://ibb.co/1sDyVMr

Please recommend how to fix this :D 

---------------------------------

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Send IoT data to InfluxDB every 3s, via Python
2. Create a dashboard on InfluxDB
3. Set dashboard auto-refresh to refresh every 1s
3. All the widgets displaying data break within minutes 

__Expected behavior:__
Dashboard updates and displays current data

__Actual behavior:__
All widgets display the error message:
error @2:19-2:20: record is missing label timeRangeStart
error @2:43-2:44: record is missing label timeRangeStop

__Flux sample code:__
```
from(bucket: "windows-test")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "B1")
  |> filter(fn: (r) => r["_field"] == "RSSI")
  |> filter(fn: (r) => r["gatewayID"] == "2224750077" or r["gatewayID"] == "2224766301" or r["gatewayID"] == "2224822273")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

<img width="960" alt="12-08-2022-crashed" src="https://user-images.githubusercontent.com/10736577/185242859-f365be5f-a208-436a-b0ef-5b955f513202.png">

**Comment by sorrowed** [comment]
I'm having the same problem, setup is a bit different though:
- InfluxDB, MQTT broker (mosquitto) and Telegraph running on the same system
- InfluxDB v2.5.1 (git: 5b6fdbf05d) build_date: 2022-11-02T18:06:28Z
- Telegraf 1.24.3 (git: HEAD@ff7323e1)
- Linux 5.15.0-52-generic x86_64 (Ubuntu 22.04.1)

This happens every time and pretty soon after opening the dashboard.

**Comment by kamlane** [comment]
I'm running into the exact same issue.
InfluxDB v2.5.1 docker container on Linux
Telegraf 1.24.3 Windows 11

I purge the database, restart the agent and the dashboard loads and then after a minute I can no longer query anything in the Data Explorer or use any dashboards.

 error @7:29-7:30: record is missing label windowPeriod error @2:19-2:20: record is missing label timeRangeStart error @2:43-2:44: record is missing label timeRangeStop

**Comment by aerogus** [comment]
Same here, with Debian 11.5, InfluxDB v2.5.1.
It was ok with InfluxDB 2.4 ...

**Comment by marekpow** [comment]
Same here, with 22.04.1 LTS (GNU/Linux 5.15.0-1017-raspi aarch64), InfluxDB v2.5.1.

**Comment by aserraric** [comment]
Around the same time this issue occurs, my browser console gets spammed with these errors:

SyntaxError: Unexpected token '', ""... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.D (flux-lsp-browser_bg.js:342:22)
    at __wbindgen_json_parse (bootstrap:64:48)
    at d7851238fb.wasm:0x209310
    at d7851238fb.wasm:0x157715
    at x (flux-lsp-browser_bg.js:225:17)
    at r (index.ts:13:12)
    at i (astim.ts:24:11)
    at filterUnusedVars.ts:57:42
    at Array.map (<anonymous>)

astim.ts:26 TypeError: Failed to execute 'decode' on 'TextDecoder': The encoded data was not valid.
    at s (flux-lsp-browser_bg.js:18:30)
    at Object.D (flux-lsp-browser_bg.js:342:28)
    at __wbindgen_json_parse (bootstrap:64:48)
    at d7851238fb.wasm:0x209310
    at d7851238fb.wasm:0x157715
    at x (flux-lsp-browser_bg.js:225:17)
    at r (index.ts:13:12)
    at i (astim.ts:24:11)
    at TimeSeries.tsx:388:39
    at Array.map (<anonymous>)

**Comment by aokholm** [comment]
I have a similar issue.

Amazon Linux e2c, Docker, influxdb:2.5.1 and 2.5.1. Didn't have this issue at 2.4.0 

Dashboards causes a lot of queries to run: and eventually similar errors.

I also noted that one of my standard dashboard were sending
~ 174 html requests in 10 second.

![image](https://user-images.githubusercontent.com/1473900/202310505-84b96ef4-3756-445c-8da9-7d93db98b910.png)

**Comment by aserraric** [comment]
I have another datapoint: The issue appears relatively quickly on webkit-based browsers (tested with Chromium and Opera). 
On the other hand, I couldn't get it to reproduce on Firefox.

**Comment by marekpow** [comment]
I have this issue on Microsoft Edge 107.0.1418.42 (64 bit)

**Comment by andig** [comment]
Same issue on Safari. Browser console has these:

<img width="583" alt="Screenshot 2022-11-20 at 11 31 23" src="https://user-images.githubusercontent.com/184815/202897243-cc077d91-abb2-4a71-a0a7-9a7f5b16ac55.png">

I've only seen this error message sind 2.5.

**Comment by andig** [comment]
BTW: using the `COPY` button on the error message doesn't do anything either and the UI becomes unresponsive. On iPad it's not usable at all.

**Comment by marekpow** [comment]
When I saw this error I turned on the Chrome browser and entered into the same endpoint and surprise, it worked! So I returned to Microsoft Edge and the next surprise, it started to work. I did the same action next time but whiteout the same result, so I think it is a race in InfluxDB.

**Comment by nagelp** [comment]
I also see this bug with Firefox 107 on Linux. When I reload the page, everything is fine again. But still feels buggy and so I went looking whether this is a known issue.

I'm running influxdb 2.5.1 from Docker influxdb:latest (8edfd8e8) on x86_64. CPU load and memory usage are minimal.

Let me know if there is any other info that I can provide for debugging.

**Comment by edanidzerda** [comment]
I'm seeing this error, too.  I just started experimenting with sending data directly from a "Feather" ESP32 microprocessor board.  I thought I had corrupted my InfluxDB, so I am glad to see it was only related to the browser.  For me, it appears to happen if I leave a Dashboard up for several hours.

I'm running influxdb:2.5.1 in Docker (8edfd8e887ea) too.

I can provide more information if needed, I see many of these errors in my Chromium (Brave) console:

astim.ts:26 RuntimeError: memory access out of bounds
    at d7851238fb.wasm:0x1e848d
    at d7851238fb.wasm:0x2960d8
    at d7851238fb.wasm:0x27c02c
    at g (flux-lsp-browser_bg.js:80:15)
    at x (flux-lsp-browser_bg.js:223:18)
    at r (index.ts:13:12)
    at i (astim.ts:24:11)
    at filterUnusedVars.ts:57:42
    at Array.map (<anonymous>)
    at o (filterUnusedVars.ts:57:29)
i @ astim.ts:26
4astim.ts:26 RuntimeError: memory access out of bounds
    at d7851238fb.wasm:0x1e848d
    at d7851238fb.wasm:0x2960d8
    at d7851238fb.wasm:0x27c02c
    at g (flux-lsp-browser_bg.js:80:15)
    at x (flux-lsp-browser_bg.js:223:18)
    at r (index.ts:13:12)
    at i (astim.ts:24:11)
    at TimeSeries.tsx:388:39
    at Array.map (<anonymous>)
    at Function.mapToProps (TimeSeries.tsx:388:26)

**Comment by barchstien** [comment]
Same for me
I just updated my docker image, and all dashboard suddenly stop working with the same error :

` error @2:19-2:20: record is missing label timeRangeStart error @2:43-2:44: record is missing label timeRangeStop`

**Comment by imerr** [comment]
Running into this exact same error too

**Comment by marekpow** [comment]
I think I have a scenario to reproduce this bug. 
1. Open any dashboard
2. Leave this dashboard open until the session ends
3. Login again a go to the same dashboard
4. Crash...

**Comment by nagelp** [comment]
> I think I have a scenario to reproduce this bug.
> [...]

Yes, I observed the same.

**Comment by LeSpocky** [comment]
Running InfluxDB 2.5.1 (OSS) in Docker Container here. Data is fed through different Telegraf containers. Browser is Firefox on Debian GNU/Linux, but it also happens in Chromium (however later in Chromium). Happens with different dashboards, on the dashboard with 10 cells earlier than on different dashboards for other buckets with fewer cells. Usually you can get it running again by refreshing the whole page through hitting F5 key. Screenshots attached.
![Screenshot_20221208_083658](https://user-images.githubusercontent.com/661636/206392604-f434634e-f44c-48f5-869e-d5472cca097c.png)
![Screenshot_20221208_083801](https://user-images.githubusercontent.com/661636/206392624-92a8281e-7cf5-4180-8578-08485ed2265f.png)
![Screenshot_20221208_083819](https://user-images.githubusercontent.com/661636/206392638-ef89b59d-0b8c-42c0-b23f-ee2be6fc0b1c.png)

**Comment by jeffreyssmith2nd** [comment]
Please see the update provided [here](https://github.com/influxdata/ui/issues/5062#issuecomment-1341338023).

**Comment by jeffreyssmith2nd** [comment]
We have identified the Dashboard stability issue and rolled the UI back to a more stable version in the recent 2.6.0 release. Due to the number of issues related to this, I'm going to close all of these issues as Completed. Please open a new issue if you are still seeing the Dashboard stability problems on 2.6.0.
