### ISSUE TITLE
InfluxDB API unavailable after X attempts...

### ISSUE THREAD

**Issue by thoduh** [influxdata/influxdb#23639]
Suddenly InfluxDB 1.8.10 does not run anymore :-(

Everything I have found here so far has unfortunately not helped.
What can I do?

<img width="1589" alt="Bildschirm­foto 2022-08-18 um 17 37 25" src="https://user-images.githubusercontent.com/22728076/185436381-fa82045e-7973-40dd-9551-37ecd23e14b5.png">

**Comment by tarundixitravi** [comment]
Hi  same issue,

Did able to solve it ?

**Comment by thoduh** [comment]
Upgrade to Version 2.4…

**Comment by nocturno66** [comment]
Hi, I am in the same situation. 
Is the upgrade the solution?

Thanks

**Comment by thoduh** [comment]
Yes, so it worked for me 😉

**Comment by nocturno66** [comment]
Ok, thanks. I will try

**Comment by ahpnils** [comment]
I recently came across the same issue, following a simple reboot of an InfluxDB instance I manage. This is a fairly large instance I think, our influx data directory is about 150GB. It turned out our instance needed more than 24 minutes to start. With a workmate, we ended up overriding some systemd settings, especially a timeout value :

```
$ cat /etc/systemd/system/influxdb.service.d/override.conf
[Service]
TimeoutStartSec=45m
```
Our file contains more than that, but this is the only setting that matters in this case. And a previous colleague had set this up with 15 minutes. After this override file creation or update, don't forget to run `systemctl daemon-reload` as root or with sudo for changes to be applied.

Hope this helps !

**Comment by AnnaWojciechowska** [comment]
In some cases it can be avialble RAM. I had a machine with 2 GB and when I added data suddenly influx needed 2.5 and it would just fail to restart, got timeout errors, but actually adding memory helped - works now, but consumes 2.5 GB - I run old 1.8 influxd,  hopefully newer versions are less memory greedy

**Comment by masterbzchief** [comment]
I am running influxdb and storing mqtt data from a node-red flow. I've tried commenting out the Type=forked, ran daemon-reload and it did not fix this issue. What did work, was going in /etc/systemd/system and ensuring that the node-red service start after influxdb (After=influxdb.service).

**Comment by averter** [comment]
> I recently came across the same issue, following a simple reboot of an InfluxDB instance I manage. This is a fairly large instance I think, our influx data directory is about 150GB. It turned out our instance needed more than 24 minutes to start. With a workmate, we noticed that even with those "InfluxDB API unavailable after X attempts" lines, we could see database files still being loaded. We also saw that after a loooong time, either the service started, either systemd killed it.
> 
> We ended up overriding some systemd settings, especially a timeout value :
> 
> ```
> $ cat /etc/systemd/system/influxdb.service.d/override.conf
> [Service]
> TimeoutStartSec=45m
> ```
> 
> Our file contains more than that, but this is the only setting that matters in this case. And a previous colleague had set this up with 15 minutes. After this override file creation or update, don't forget to run `systemctl daemon-reload` as root or with sudo for changes to be applied.
> 
> Hope this helps !

Thank you very much for this helpful tip. For my RPI3 I had to add that line in a different file using `sudo nano /etc/systemd/system/influxd.service` and then `sudo systemctl status influxdb` after the `sudo systemctl daemon-reload`. Worked like a charm.

**Comment by melroy89** [comment]
For anybody, including my self. I enabled socket file in InfluxDB and this require that the service has access to `/var/run/influxdb`.

Every time I update influxdb, I need to add the following 2 lines again to the `influxdb.service` under Ubuntu server:

```ini
[Service]
....

RuntimeDirectory=influxdb
RuntimeDirectoryMode=0755
```

**Comment by SEGELBERT** [comment]
> For anybody, including my self. I enabled socket file in InfluxDB and this require that the service has access to `/var/run/influxdb`.
> 
> Every time I update influxdb, I need to add the following 2 lines again to the `influxdb.service` under Ubuntu server:
> 
> ```ini
> [Service]
> ....
> 
> RuntimeDirectory=influxdb
> RuntimeDirectoryMode=0755
> ```

Good hint, i did the following changes:

```
RuntimeDirectory=/var/lib/influxdb
RuntimeDirectoryMode=0755
```

**Comment by melroy89** [comment]
> > For anybody, including my self. I enabled socket file in InfluxDB and this require that the service has access to `/var/run/influxdb`.
> > Every time I update influxdb, I need to add the following 2 lines again to the `influxdb.service` under Ubuntu server:
> > ```ini
> > [Service]
> > ....
> > 
> > RuntimeDirectory=influxdb
> > RuntimeDirectoryMode=0755
> > ```
> 
> Good hint, i did the following changes:
> 
> ```
> RuntimeDirectory=/var/lib/influxdb
> RuntimeDirectoryMode=0755
> ```

That is not how RuntimeDirectory should be used.

Also the reason I created this issue is. Just changing this service is not really persistent. After each influxdb update, the file is overwritten and often put back to their defaults. Causing my instance to fail to start.
