### ISSUE TITLE
Change fields.idx format to updatable for performance.

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influxdb#23653]
The `fields.idx` file, which contains a list of fields per measurement in a shard, is rewritten in its entirety on every field creation.  This, despite optimizations, is a bottleneck for measurements with large numbers of fields. Customers would like to use significantly more fields per measurement than are currently performant (~300), including one request for 150,000 fields in a measurement.

To support this, the `fields.idx` format has to support increment updates, one entry per field creation or deletion.  Since the file is only used to load the in-memory copy against which all lookups are done, an incremental format will not have performance implications after startup.

@dgnorton & @lesam were in the discussion of this optimization.

**Comment by davidby-influx** [comment]
Initial thoughts on design:

Protobuf doesn't support streaming messages, but the developers [suggest](https://developers.google.com/protocol-buffers/docs/techniques#streaming) a simple length prefix to messages in the stream.

Using this technique, define a new protobuf message, to add or remove a field to a measurement.  These messages will be appended to a file of deltas opened in exclusive mode (also protected by mutexes in Influxdb) whenever the in-memory MeasurementFieldSet is updated.

On startup, these deltas will be applied to the MeasurementFieldSet created by reading `fields.idx` (or created by reading TSM files for InMem installations missing `fields.idx`). 

The reader will iterate through the messages in the file, reading the length of each message, then using `io.ReadAtLeast` to pick one message at a time. 

The completed object will be persisted to `fields.idx` as normal, and the file of deltas deleted. This will allow rollbacks to earlier versions (assuming the new version can get that far in the initialization).

Variants:
- A directory of deltas, one file per delta.  Applied in order of create time.  Seems fragile, more prone to corruption and confusion
- Regenerate `fields.idx` on shutdown as well as startup.  Slightly more robust scenario for rollbacks, but slows shutdown.
- Regenerate `fields.idx` by schedule or count of changes as well as on start-up. Could still lead to pathological load in some circumstances.

**Comment by lesam** [comment]
Rather than the current batching behaviour, could we batch on cache->disk flushes?

i.e., when we only have a field in the WAL and in-memory, we will be reprocessing it at startup (I think - if we don't already, we could add that), and so we don't really need it in fields.idx. Once it is in a TSM file, that's when we need it in `fields.idx`.

So the process would be:

- on write path:
  - write to cache (in-memory), write to WAL, no write to fields.idx
- on cache flush
  - ensure all fields are present in fields.idx, if any are missing then create them (maybe keep a list of fields that need persisting from the write path)
   - flush the cache as normal
 - on startup
   - ensure any 'new' fields from the WAL are added to in-memory state
 
 The WAL (or any delta log, like what you're suggesting here) is a lot more prone to issues as we need to update the file, and recover from any possible errors with those updates, instead of a process like TSM files where every file can be written once immutably to a tmp file and then we just have to deal with `os.Rename` success/failure.
 
 We could add something like your variant "A directory of deltas, one file per delta. Applied in order of create time." - if we're just flushing fields.idx on cache flushes, there would be a lot less 'extra' files to keep track of and so I think it would be less prone to corruption.

**Comment by davidby-influx** [comment]
I'm concerned that this is a major change in how and when we persist fields on disk. If you like the immutable fields over the appended delta log, than I would prefer the directory of one file per change to tying the field persistence to the WAL operation.

**Comment by davidby-influx** [comment]
In particular, the `fields.idx` is handled by the shard, not the engine, whereas the engine handle the cache and the WAL.  We would have to break that modularization to catch the cache write.

**Comment by davidby-influx** [comment]
Currently, the persistence of `fields.idx` happens roughly like this:
- A `write` or `delete` adds fields or removes measurements, respectively
- The MeasurementFieldSet is updated
- At the end of the write or delete, a save request is put on a channel monitored by a go proc to write out to the file system. The save request only contains an error channel to return the result
- That go proc starts the writing process, but collects all pending save requests and returns the success or error to each of them on their own channel

My proposed change is that
- A `write` or `delete` adds fields or removes measurements, respectively. The changes are stored in a slice as they happen
- The `MeasurementFieldSet` is updated as before.
- The save request issues at the end of a `write` or `delete` with field changes now includes the slice of changes and an error return channel. 
- The monitoring Go proc aggregates all the changes on the channel into one change file. This will be at least the changes from one `write` or `delete`, and possibly more. depending on load.
- On startup, all the change files are applied to the in-memory `MeasurementFieldSet`, and it is written out as `fields.idx` 

I prefer this to linking the file system writes to the WAL/cache flushes. It preserves the current cadence of writes but minimizes their size, it keeps the current modularization of concerns, and correctly returns errors on persisting field change back to the originating operation.

**Comment by lesam** [comment]
I agree that this looks good, and tying to WAL/cache flushes is too much effort - I had forgotten that the indexing all ignores the WAL / cache cadence of TSM.

**Comment by dgnorton** [comment]
Sounds like a good approach to me. Read through here and had a discussion with @lesam to catch up on a few of the details.

**Comment by lesam** [comment]
Bikeshedding: maybe `fields.idxl` as the delta log file name?

**Comment by lesam** [comment]
We'll need to document that downgrades need an index rebuild (to make sure no `fields.idxl` files stick around)

**Comment by davidby-influx** [comment]
@lesam - if the system is brought up and takes no writes or deletes, the `fields.idx` will be backward compatible, obviating the index rebuild necessity.

**Comment by lesam** [comment]
> if the system is brought up and takes no writes or deletes
 
 Easier to require an index rebuild on downgrades than telling users to make sure they do a restart without writes, since any write could mess things up.
