### ISSUE TITLE
Default token can not create a new all-access token

### ISSUE THREAD

**Issue by yikuo123** [influxdata/influxdb#23668]
__Steps to reproduce:__

1. yum install influxdb2 influxdb2-cli
2. systemctl start influxdb
3. influx setup
4. influx auth create --all-access

__Expected behavior:__

Create a token successfully

__Actual behavior:__

Error: could not write auth with provided arguments: 403 Forbidden: permission read:orgs/96754d13b3875421/instance is not allowed: read:orgs/96754d13b3875421/instance is unauthorized

__Environment info:__

Linux 3.10.0-957.21.3.el7.x86_64 x86_64

influx version
Influx CLI 2.4.0 (git: 5c7c34f) build_date: 2022-08-18T19:26:48Z

influxd version
InfluxDB v2.4.0 (git: de247bab08) build_date: 2022-08-18T19:41:15Z

__It works fine with old version:__

influx version
Influx CLI 2.2.1 (git: 31ac783) build_date: 2021-11-09T21:24:22Z

influxd version
InfluxDB 2.1.1 (git: 657e1839de) build_date: 2021-11-09T03:03:48Z

**Comment by jeffreyssmith2nd** [comment]
Thanks for reporting @yikuo123. This is a bug in the CLI introduced in 2.4. The workaround until a bug fix is released would be to use the command below. 

```
influx auth create --read-authorizations          \
                      --write-authorizations         \
                      --read-buckets                 \
                      --write-buckets                \
                      --read-dashboards              \
                      --write-dashboards             \
                      --read-orgs                    \
                      --write-orgs                   \
                      --read-tasks                   \
                      --write-tasks                  \
                      --read-telegrafs               \
                      --write-telegrafs              \
                      --read-users                   \
                      --write-users                  \
                      --read-variables               \
                      --write-variables              \
                      --read-secrets                 \
                      --write-secrets                \
                      --read-labels                  \
                      --write-labels                 \
                      --read-views                   \
                      --write-views                  \
                      --read-documents               \
                      --write-documents              \
                      --read-notificationRules       \
                      --write-notificationRules      \
                      --read-notificationEndpoints   \
                      --write-notificationEndpoints  \
                      --read-checks                  \
                      --write-checks                 \
                      --read-dbrp                    \
                      --write-dbrp                   \
                      --read-annotations             \
                      --write-annotations            \
                      --read-sources                 \
                      --write-sources                \
                      --read-scrapers                \
                      --write-scrapers               \
                      --read-notebooks               \
                      --write-notebooks              \
                      --read-remotes                 \
                      --write-remotes                \
                      --read-replications            \
                      --write-replications
```

**Comment by HolgerHees** [comment]
same happens with when I want to create new operators like

`influx auth create --description "testuser1's Token" --user testuser1 --org default-org --operator`

here I get the following error message

`Error: could not write auth with provided arguments: 403 Forbidden: permission read:instance is not allowed: read:instance is unauthorized`

**Comment by jeffreyssmith2nd** [comment]
Slight correction. For the equivalent of an all-access token, the above command also needs the `--org-id` or `--org` flag set.

For an operator token, you can use the above command with the `--read-orgs` and `--write-orgs` flags added.

Both of these bugs should be addressed in the next CLI release.
