### ISSUE TITLE
Convert to 2x version.

### ISSUE THREAD

**Issue by josephthanaraja** [influxdata/influxdb#23688]
__Proposal:__
We are using InfluxDb1x and planning to move to 2x.

__Current behavior:__
We are using InfluxDb1x and planning to move to 2x.

__Desired behavior:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Do we have any documentation for this migraiton -  InfluxDb1x  to 2x.

**Comment by sanderson** [comment]
@josephthanaraja Here is the documentation you're looking for: [Upgrade from InfluxDB 1.x to 2.x](https://docs.influxdata.com/influxdb/latest/upgrade/v1-to-v2/)
