### ISSUE TITLE
How to update influxdb server in Centos7.9?

### ISSUE THREAD

**Issue by ybina** [influxdata/influxdb#23710]
I want to update my influxdb from 2.1.1 to 2.4.0 in my centos7.9,
How to update it in my centos7.9? and if I update it, will the previouse data lost?

**Comment by ybina** [comment]
will my influxdb service abort or interrupt when updating?

**Comment by kbensch** [comment]
There will be a short period of interruption while the service is updated and specifically while it is restarted. As for data loss, I constantly upgrade and have not lost any data yet.

**Comment by ybina** [comment]
@kbensch Thank you so much!
