### ISSUE TITLE
Limit and Sort in flux is not working as expected. Its Returning the complete data

### ISSUE THREAD

**Issue by gksk** [influxdata/influxdb#23768]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by Nandan-unni** [comment]
@gksk did u got it solved?

**Comment by dongjun111111** [comment]
I had encountered the same problem. 

from(bucket: "bucket_name")
     |> range(start: start_time, stop: stop_time)
     |> filter(fn: (r) => r._measurement == "inclinometer" )
     |> group(columns: ["batch_id","_time","_value")
     |> pivot(rowKey:["batch_id"], columnKey: ["_field"], valueColumn: "_value")
     |> sort(columns: ["batch_id"], desc: true)
     |> limit(n: 2)
     
     
     It's returning all completed datas, more than two pieces of data.

**Comment by dongjun111111** [comment]
I had encountered the same problem. 

from(bucket: "bucket_name")
     |> range(start: start_time, stop: stop_time)
     |> filter(fn: (r) => r._measurement == "inclinometer" )
     |> group(columns: ["batch_id","_time","_value")
     |> pivot(rowKey:["batch_id"], columnKey: ["_field"], valueColumn: "_value")
     |> sort(columns: ["batch_id"], desc: true)
     |> limit(n: 2)
     
     
     It's returning all completed datas, more than two pieces of data.

**Comment by sanderson** [comment]
`sort()` and `limit()` operate on each table in your stream of tables, not the dataset as a whole. Each table represents a group. @dongjun111111, where you're grouping by `batch_id`, `_time`, and `_value`, you have a table for each unique combination of these columns and `sort() |> limit()` operates on each individual table.

To sort and limit all data in a stream of tables, you need to group all data into a single table (also known as ungrouping) using `group()`:

```javascript
data
    |> group()
    |> sort(columns: [...])
    |> limit(n: 2)
```

@dongjun111111 in your case, the grouping isn't really doing anything. You can just do this to get what you want:

```javascript
from(bucket: "bucket_name")
    |> range(start: start_time, stop: stop_time)
    |> filter(fn: (r) => r._measurement == "inclinometer" )
    |> group()
    |> pivot(rowKey:["batch_id"], columnKey: ["_field"], valueColumn: "_value")
    |> sort(columns: ["batch_id"], desc: true)
    |> limit(n: 2)
```

**Comment by dongjun111111** [comment]
> ```js
>     |> group()
>     |> pivot(rowKey:["batch_id"], columnKey: ["_field"], valueColumn: "_value")
>     |> sort(columns: ["batch_id"], desc: true)
>     |> limit(n: 2)
> ```

Thx so much! It's working!    I learned!  It's so amazing !  Thx again!

**Comment by dongjun111111** [comment]
> `sort()` and `limit()` operate on each table in your stream of tables, not the dataset as a whole. Each table represents a group. @dongjun111111, where you're grouping by `batch_id`, `_time`, and `_value`, you have a table for each unique combination of these columns and `sort() |> limit()` operates on each individual table.
> 
> To sort and limit all data in a stream of tables, you need to group all data into a single table (also known as ungrouping) using `group()`:
> 
> ```js
> data
>     |> group()
>     |> sort(columns: [...])
>     |> limit(n: 2)
> ```
> 
> @dongjun111111 in your case, the grouping isn't really doing anything. You can just do this to get what you want:
> 
> ```js
> from(bucket: "bucket_name")
>     |> range(start: start_time, stop: stop_time)
>     |> filter(fn: (r) => r._measurement == "inclinometer" )
>     |> group()
>     |> pivot(rowKey:["batch_id"], columnKey: ["_field"], valueColumn: "_value")
>     |> sort(columns: ["batch_id"], desc: true)
>     |> limit(n: 2)
> ```

@sanderson   Thx so much! It's working! I learned! It's so amazing ! Thx again!
