### ISSUE TITLE
Data with timestamp in the future

### ISSUE THREAD

**Issue by tomrozb** [influxdata/influxdb#23777]
__Steps to reproduce:__
Try to write data using CLI with timestamp in the future

```
influx write --bucket test "test,host=manual value=10" 1664987160000000000
influx write --bucket test "test,host=manual value=15" 1764987160000000000
influx write --bucket test "test,host=manual value=20" 1864987160000000000
```

__Expected behavior:__
The data has correct timestamp

__Actual behavior:__
Data is saved with current system time stamp. Seems there's no way to insert data with future timestamp

__Environment info:__
Influx CLI 2.4.0 (git: 5c7c34f) build_date: 2022-08-18T19:26:48Z
Linux 5.15.61-v8+ aarch64

Is that expected behavior? Is this feature not supported by the database, or is it a bug?

**Comment by sanderson** [comment]
@tomrozb The timestamp needs to be inside of the line protocol string. As is, these points are being written without a time stamp and are defaulting to the server time.

```sh
influx write --bucket test "test,host=manual value=10 1664987160000000000"
influx write --bucket test "test,host=manual value=15 1764987160000000000"
influx write --bucket test "test,host=manual value=20 1864987160000000000"
```
