### ISSUE TITLE
Scraper reads same url for all requests

### ISSUE THREAD

**Issue by blieb** [influxdata/influxdb#23802]
Hi,

I've upgraded to the latest docker container of influxdb. But since the upgrade the scraper functionality is broken. 

I've 5 scrapers. But I see that it only requests the last added metrics url that I've added. It requests the same url 5 times per 10 seconds. When I remove a scraper that goes down to 4 times the same url per 10 seconds. 

did something go wrong in the latest upgrade?

I tried to downgrade to 2.3 but that does not work even when I've run "downgrade 2.3" and start the 2.3 it still says it has a unknown migration. Hope this issue can be fixed

**Comment by hh1414** [comment]
Hello I also experience trouble configuring multiple scrapers with InfluxDB OSS 2.4.0. I saw only data being added from the last Prometheus scraper that I configured. When I dropped the last one, I saw the data coming in again from the second last one I configured.
Not sure if the data of the last configured scraper was added to the bucket multiple times.

**Comment by blieb** [comment]
> Hello I also experience trouble configuring multiple scrapers with InfluxDB OSS 2.4.0. I saw only data being added from the last Prometheus scraper that I configured. When I dropped the last one, I saw the data coming in again from the second last one I configured.
> 
> Not sure if the data of the last configured scraper was added to the bucket multiple times. 

Yes I checked the logs of the metrics server and see multiple requests coming in. And the other no requests anymore. It always uses the newest url you added.

**Comment by jeffreyssmith2nd** [comment]
I've replicated this, I see it happening on versions before 2.4 as well.
