### ISSUE TITLE
Date add/sub not working in InfluxDB 2.4.0 OSS (docker image)

### ISSUE THREAD

**Issue by hh1414** [influxdata/influxdb#23803]
I tried to use the date.add / date.sub functions. However in both cases I got the warning:

```
import "date"
t = date.add(d: 1h, to: now())
```

`record is missing label add`

I verified the version of the Flux language. This was v0.179.0 so the functions are expected to be supported (as also written in the release notes of 2.4.0).

It seems that the experimental method addDuration is still working.

**Comment by jeffreyssmith2nd** [comment]
This seems to be a UI bug. The script editor gives a warning, however if you actually execute the query it succeeds.

**Comment by kristinarobinson** [comment]
Checking for repro in Cloud UI.

**Comment by nathanielc** [comment]
I tried this locally using the docker image and I got this query to work without issue

```
import "date"
import "array"

array.from(rows:[{_time: date.add(to: now(), d: 1h)}])
```

steps:

```
$ docker pull influxdb:2.4.0
$ docker run -p 8086:8086 influxdb:2.4.0
```

Then navigate to `localhost:8086` and complete setup.
```

**Comment by jeffreyssmith2nd** [comment]
Just tested in 2.5.1 (which has an updated UI commit) and it no longer shows this error. I think we can probably close this out.
