### ISSUE TITLE
Missing data points with Backup & Restore

### ISSUE THREAD

**Issue by Nick135** [influxdata/influxdb#23817]
__Steps to reproduce:__
1. Backup DB with influx
2. Restore DB on new device with influx
3. querry data

__Expected behavior:__
All Data should be restored from backup

__Actual behavior:__
Backup is from 11.10.2022, but only data until 08.10.2022 are present.

__Environment info:__
* System info: Win10 x64
* InfluxDB version: InfluxDB v2.3.0+SNAPSHOT.090f681737 (git: 090f681737) build_date: 2022-06-16T19:34:12Z
* Influx version: Influx CLI 2.3.0 (git: 88ba346) build_date: 2022-04-06T19:30:53Z

__Config:__
influx backup "myBackup" -t Token
influx restore "myBackup " --full -t Token

![image](https://user-images.githubusercontent.com/14072733/196382458-d375ea73-0800-4a16-83ee-ffc3ad2e7b29.png)

**Comment by jeffreyssmith2nd** [comment]
How many buckets do you have that you tried to backup?

**Comment by Nick135** [comment]
I only have one bucket.

I made another backup yesterday. Now I have more data.
However, this time the last 14 hours are missing.
Can it be that the backup does not save the last shard?

**Comment by jeffreyssmith2nd** [comment]
The CLI asks influxdb to generate a manifest and then simply iterates over that manifest to download each of the shards. Can you look at the `<datetimeofbackup>.manifest` file in your backup directory and verify if it has all the expected shards or not?

**Comment by Nick135** [comment]
![image](https://user-images.githubusercontent.com/14072733/196752845-6a3502db-e09d-409a-acbd-8e16fb1ebcd1.png)


### 20221017T141708Z.manifest:
![image](https://user-images.githubusercontent.com/14072733/196752961-55347fe0-4f03-40ff-a841-1c391f0ed064.png)

### I´m on UTC+2 so maybe the last shard is missing.



![image](https://user-images.githubusercontent.com/14072733/196753663-374135b7-9613-4e3f-9588-4f927aa29722.png)

**Comment by jeffreyssmith2nd** [comment]
The size in that manifest for shard 53 seems to match up with what is on disk right? But yeah you can clearly see the cutoff of the time between the previous shard and 53. That makes me think that it may be the restore that is failing. Is there a directory for shard 53 in your engine folder?

**Comment by Nick135** [comment]
![image](https://user-images.githubusercontent.com/14072733/196878109-daf86352-8086-4760-ac95-e805ee53af6c.png)

**Comment by jeffreyssmith2nd** [comment]
Ah I missed something in the manifest generation, we don't actually set this size in the manifest until after we download the shard (so of course its going to match). So backup is not out of the picture then.

Is the latest screenshot from the instance you are backing up, or the one you are restoring to?

When you do a backup, do you see any logs/errors from the influxdb instance that you're backing up?

**Comment by Nick135** [comment]
Latest screenshot is from the instance I backing up to.

**Comment by jeffreyssmith2nd** [comment]
Ah okay so the tsm files are there but you just can't query them?

Can you run `influxd inspect report-tsm` and `influxd report-tsi -b <bucket-id>` and see if those report any errors/odd info especially for shard 53?

**Comment by Nick135** [comment]
### influxd inspect report-tsm
```
PS C:\_Projekt\InfluxData\influxdb> .\influxd inspect report-tsm
DB               RP      Shard   File                    Series  New (est) Min Time                     Max Time                     Load Time
2fb771c726b0e96f autogen 1       000000017-000000003.tsm 1353    1354      2022-07-22T14:14:23.4429731Z 2022-07-24T23:59:53.4359428Z 0s
2fb771c726b0e96f autogen 2       000000071-000000002.tsm 1800    447       2022-07-25T00:00:03.4359492Z 2022-07-31T23:59:59.9665Z    4.3037ms
2fb771c726b0e96f autogen 6       000000099-000000002.tsm 1854    95        2022-08-01T00:00:00.0065Z    2022-08-07T23:59:59.9865Z    9.5207ms
2fb771c726b0e96f autogen 14      000000094-000000002.tsm 1904    54        2022-08-08T00:00:00.0185Z    2022-08-14T23:59:59.9665Z    18.8405ms
2fb771c726b0e96f autogen 22      000000091-000000002.tsm 1958    54        2022-08-15T00:00:00.0145Z    2022-08-21T23:59:59.9945Z    3.7924ms
2fb771c726b0e96f autogen 30      000000096-000000004.tsm 2096    133       2022-08-22T00:00:00.0265Z    2022-08-28T23:59:59.96625Z   10.473ms
2fb771c726b0e96f autogen 38      000000065-000000002.tsm 2102    65        2022-08-29T00:00:00.01025Z   2022-09-04T23:59:59.963Z     13.357ms
2fb771c726b0e96f autogen 40      000000058-000000002.tsm 1099    57        2022-09-05T00:00:00.003Z     2022-09-11T23:59:59.9555Z    6.0224ms
2fb771c726b0e96f autogen 41      000000054-000000002.tsm 1131    64        2022-09-12T00:00:00.0435Z    2022-09-18T23:59:59.993Z     10.3789ms
2fb771c726b0e96f autogen 42      000000067-000000002.tsm 1398    146       2022-09-19T00:00:00.005Z     2022-09-25T23:59:59.9755Z    3.6521ms
2fb771c726b0e96f autogen 43      000000075-000000002.tsm 1391    75        2022-09-26T00:00:00.0555Z    2022-10-02T23:59:59.986Z     43.5629ms
2fb771c726b0e96f autogen 44      000000056-000000002.tsm 1600    219       2022-10-03T00:00:00.054Z     2022-10-08T10:23:33.32975Z   35.6179ms
2fb771c726b0e96f autogen 45      000000066-000000004.tsm 1512    246       2022-10-10T06:58:40.0400112Z 2022-10-16T23:59:59.9855Z    33.0263ms
2fb771c726b0e96f autogen 53      000000010-000000002.tsm 2209    794       2022-10-17T00:00:00.0255Z    2022-10-18T22:56:08.8904203Z 20.0493ms
2fb771c726b0e96f autogen 53      000000018-000000002.tsm 1420    0         2022-10-18T22:56:18.8868093Z 2022-10-20T00:27:40.1738602Z 11.0901ms
2fb771c726b0e96f autogen 53      000000026-000000002.tsm 1420    0         2022-10-20T00:27:50.1738451Z 2022-10-21T01:55:00.1803082Z 0s
2fb771c726b0e96f autogen 53      000000027-000000001.tsm 1420    0         2022-10-21T01:55:10.1734598Z 2022-10-21T05:07:00.1804655Z 0s
2fb771c726b0e96f autogen 53      000000028-000000001.tsm 1420    0         2022-10-21T05:07:10.1853646Z 2022-10-21T08:20:40.1807088Z 0s

Summary:  Files: 18
  Time Range: 2022-07-22T14:14:23.4429731Z - 2022-10-21T08:20:40.1807088Z
  Duration: 2178h6m16.7377357s

Statistics
  Series:
     - 2fb771c726b0e96f (est): 3803 (100%)
  Total (est): 3803
Completed in 753.7385ms
```

### influxd report-tsi -b <bucket-id>

```
PS C:\_Projekt\InfluxData\influxdb> .\influxd report-tsi -b 2fb771c726b0e96f
Error: unknown shorthand flag: 'b' in -b
```

**Comment by jeffreyssmith2nd** [comment]
Yeah there's clearly something wrong there with shard 53. The best way to move forward with this issue now would be a repro case. If we provided a private ftp, would you be willing to share the backup directory (and preferably the original influxdb directory too) to attempt to debug what's going on here?

**Comment by Nick135** [comment]
Currently the original influxdb is on work.
Is it possible to copy the ".influxdbv2" folder to another pc and modify it there?
Change password etc

If possible I can modify and upload the package next week.

**Comment by jeffreyssmith2nd** [comment]
You can use the [boltdbweb tool](https://github.com/evnix/boltdbweb) to edit any values in the influxd.bolt file. And you can copy to another machine, you will just want to stop the process before doing the copy.

Whenever you're ready to share, send me an email at the one linked in my profile and I'll get you that information. Thanks for your help!

**Comment by Nick135** [comment]
I made a packet with the data. Also this time the current Day are missing in the restore.
Copy the ".influxdbv2" folder to other pc works fine.
I will send you a mail.

**Comment by Nick135** [comment]
Looks like v2.5 fix the problem.
