### ISSUE TITLE
V2.3,How to view the server log and where the log is stored?

### ISSUE THREAD

**Issue by mdjs147** [influxdata/influxdb#23830]
V2.3,How to view the server log and where the log is stored?.

**Comment by sanderson** [comment]
@mdjs147 Information about managing logs was added to the 2.4 documentation, but it should still apply to 2.3: https://docs.influxdata.com/influxdb/v2.4/admin/logs/

**Comment by mdjs147** [comment]
@sanderson How to configure under Windows？

**Comment by sanderson** [comment]
The same principles in that doc apply to windows. `influxd` outputs all logs to stdout, so the output of the `influxd` process is the server log stream. Redirecting stdout to a file depends on how you're starting `influxd`. If you're doing it in PowerShell, it'd be something like:

```powershell
C:\Program Files\InfluxData\influxdb 1> /path/to/influxdb.log
```

You can find more information about redirecting Windows log output in the [Microsoft documentation](https://learn.microsoft.com/en-US/troubleshoot/developer/visualstudio/cpp/language-compilers/redirecting-error-command-prompt).

**Comment by mdjs147** [comment]
thank you
