### ISSUE TITLE
Upgrade to Go 1.19 for GOMEMLIMIT

### ISSUE THREAD

**Issue by andrewchellis** [influxdata/influxdb#23862]
__Proposal:__
Upgrade Go to 1.19 for `GOMEMLIMIT` support - this will be a game changer for tuning influx memory usage.

__Current behavior:__
Bursty workloads and expensive queries require tuning `GOGC` - a guessing game to ensure the application does not OOM. If you have some bad luck, like a spike of ingest + queries + compaction, a previously stable instance to crash.

__Desired behavior:__
Go abides by the memory limits in our cgroups or `GOMEMLIMIT` envvar and calls the GC rather than dieing OOM.

If this is pulled from the cgroup it would be good to multiply by some factor to allow headroom, say `0.9`

(Similarly, it would be nice to set `GOMAXPROCS` from cgroups (https://github.com/uber-go/automaxprocs))

__Use case:__
This is important to anyone who wants a stable influx instance with predictable memory peaks.

[Respecting Memory Limits in Go](https://opensourcelive.withgoogle.com/events/go-day-2022/watch?talk=talk4)

**Comment by andrewchellis** [comment]
I see https://github.com/influxdata/influxdb/pull/23676 which has not seen any recent updates

**Comment by jeffreyssmith2nd** [comment]
Thanks for bringing this up @andrewchellis, its on our radar to finish the upgrade.

**Comment by andrewchellis** [comment]
Covered in https://github.com/influxdata/influxdb/releases/tag/v2.7.0

Thanks
