### ISSUE TITLE
Browser tab becomes unresponsive when trying to load dashboard in Safari (Mac/iPad)

### ISSUE THREAD

**Issue by fluxor99232** [influxdata/influxdb#23870]
__Steps to reproduce:__
Try to load a dashboard in Safari on macOS or on iPad.

__Expected behavior:__
Dashboard loads.

__Actual behavior:__
Dashboard does not fully load and browser tab becomes unresponsive.

__Environment info:__

* System info: macOS Ventura 13.0 (Safari 16.1), 3.8 GHz Quad-Core Intel Core i5, 16 GB RAM, Radeon Pro 580 8 GB,  or iPad Air (iPad OS 16.1)
* InfluxDB version: InfluxDB v2.5.1, Server: [5b6fdbf](https://github.com/influxdata/influxdb/tree/5b6fdbf05d), Frontend: [822e216](https://github.com/influxdata/ui/tree/822e216)

**Comment by dgnorton** [comment]
@fluxor99232 did you upgrade from a prior version of InfluxDB or is this a new install?

**Comment by fluxor99232** [comment]
@dgnorton I installed InfluxDB a couple of months ago on my Ubuntu server via Docker. It may have auto-updated in the meantime. Has been working fine in Safari until maybe a couple of weeks ago (last time I checked was before the recent macOS and iPad OS updates). Firefox on macOS is still working fine. On iPad OS Firefox becomes unresponsive as well (naturally, since all browsers there are Safari based).

**Comment by bjoas** [comment]
I am seeing the same or a very similar issue with Safari on iOS, and really bad performance in Safari on macOS. I upgraded to 2.5.0 (server 6fc66ac, frontend 822e216)

It did work fine in 2.2.0

**Comment by fluxor99232** [comment]
I don't know if related or not, but even in Firefox, once I try to refresh my dashoard, all cells show the following error:

> record is missing label timeRangeStart error @2:43-2:44: record is missing label timeRangeStop

**Comment by koitsu** [comment]
I'm not using Safari, but in https://github.com/influxdata/ui/issues/6307 I've discovered extremely poor UI performance in the Dashboards area (though viewing an individual dashboard seems fine), which seems to correlate with the 2.5.0 release.  Details are in that ticket.

Can folks here try rolling back to 2.4.0 and see if functionality is restored?  You will need to use `influxd downgrade 2.4` (run from 2.5.0 or 2.5.1) to downgrade the metadata format (so make a backup of your DB first!).

**Comment by fluxor99232** [comment]
> Can folks here try rolling back to 2.4.0 and see if functionality is restored? You will need to use `influxd downgrade 2.4` (run from 2.5.0 or 2.5.1) to downgrade the metadata format (so make a backup of your DB first!).

Tried to but running the downgrade command inside the Docker container gives me an error (something about a wrong path to a .bolt-file. Ans pulling the 2.4.0 image without running the command first won’t let the container start… 🤷‍♂️

**Comment by koitsu** [comment]
> > Can folks here try rolling back to 2.4.0 and see if functionality is restored? You will need to use `influxd downgrade 2.4` (run from 2.5.0 or 2.5.1) to downgrade the metadata format (so make a backup of your DB first!).
> 
> Tried to but running the downgrade command inside the Docker container gives me an error (something about a wrong path to a .bolt-file. Ans pulling the 2.4.0 image without running the command first won’t let the container start… man_shrugging

Not sure about the bolt file, but that's usually based on the config file directive `bolt-path`.

I provided full shell commands to roll back from 2.5.1 to 2.4.0 in the https://github.com/influxdata/ui/issues/6307 ticket, but everyone's environments and feature use differs.

**Comment by fluxor99232** [comment]
So are there any plans to restore support for Safari browsers and iOS devices? Haven't been able to access my dashboards for more than a month now.

**Comment by fluxor99232** [comment]
Btw, the freezes InfluxDB dashboards cause in Safari (Mac) are now so bad, they even affect all other tabs in the same window and persist even after the dashboard tab is closed.

**Comment by jeffreyssmith2nd** [comment]
We have identified the Dashboard stability issue and rolled the UI back to a more stable version in the recent 2.6.0 release. Due to the number of issues related to this, I'm going to close all of these issues as Completed. Please open a new issue if you are still seeing the Dashboard stability problems on 2.6.0.

**Comment by koitsu** [comment]
For other readers: https://github.com/influxdata/ui/issues/6307#issuecomment-1354806165 says this was caused by https://github.com/influxdata/ui/pull/5233

**Comment by koitsu** [comment]
Also for other readers: I can confirm that 2.6.0 resolves this problem. (Specifics: since I use Docker, I'm using `influxdb:latest`, which right now is image ID `df1c226db87e`.  `influxdb:2.6.0` also points to this image ID as of this writing).
