### ISSUE TITLE
add type conflict checker to influx_inspect [port to master]

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influxdb#23894]
Port this PR to master https://github.com/influxdata/influxdb/pull/23616

**Comment by jeffreyssmith2nd** [comment]
As currently implemented, this line requires that the directory passed to `check-schema` be reachable from the "./" prefix. Is this intended @davidby-influx? https://github.com/influxdata/influxdb/blob/be9a3d4a078fe2b36cea685839d24a3c6b53a592/cmd/influx_inspect/type_conflicts/type_conflicts.go#L68

**Comment by davidby-influx** [comment]
That was deliberate, based on the other commands in `influx_inspect`
