### ISSUE TITLE
Dashboard slow and unusable

### ISSUE THREAD

**Issue by cliffjao** [influxdata/influxdb#23927]
__Steps to reproduce:__
1. Login to InfluxDB
2. Load my dashboard which has several widgets (have tried both 1 day and 1 hour setting)

__Expected behavior:__
All graphs loaded quickly

__Actual behavior:__
Loads extremely slowly, some graphs never load, UI often becomes unresponsive. Hear my CPU fans cycling like crazy.

__Environment info:__

* System info: Linux 5.15.74-1-pve x86_64
* InfluxDB version: InfluxDB v2.5.1 (git: 5b6fdbf05d) build_date: 2022-11-02T18:06:28Z
* Other relevant environment details: Using Chrome Version 107.0.5304.110 (Official Build) (x86_64) on Mac OS X

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by rchac** [comment]
Experiencing this as well since the 2.5 upgrade.

**Comment by cliffjao** [comment]
> Reloading the entire page via the browser's reload button results in a working page though.

This doesn't work for me. It's still pretty unusable.

**Comment by rchac** [comment]
> > Reloading the entire page via the browser's reload button results in a working page though.
> 
> This doesn't work for me. It's still pretty unusable. UI remains very unresponsive.

Same, it only works briefly as a workaround for me before the same thing happens again.

**Comment by StGoebel** [comment]
Same here. I installed Grafana instead, which works much faster.

**Comment by nated099** [comment]
Upgrading from 2.4 to 2.5.0 and 2.5.1 has made the UI unusable for query submission across 2 instances.

**Comment by gasagna** [comment]
I have this issue too. I have found this to be an issue on several browsers. Looking at the syslog, it looks like the UI is repeatedly querying the database.

**Comment by dmitry-vychikov** [comment]
Vote for everything said above.

In addition, the dashboard refreshes itself automatically every 1 minute even if I configure autorefresh to be 1 hour. The setting is completely ignored.

Absolutely unusable.

**Comment by cliffjao** [comment]
The solution I'm pursuing is moving to Grafana. Given how little traction this issue has gotten, it seems like InfluxDB's priorities are elsewhere and dashboarding/visualization isn't one of them.

**Comment by gasagna** [comment]
> The solution I'm pursuing is moving to Grafana. Given how little traction this issue has gotten, it seems like InfluxDB's priorities are elsewhere and dashboarding/visualization isn't one of them.

I have set up grafana on my private web server and it runs smoothly, but I was surprised that it does not have the ability to zoom in the y-axis only, as we can do in the influxdb dashboard (see [here](https://github.com/grafana/grafana/issues/9457)).

**Comment by jeffreyssmith2nd** [comment]
We have identified the Dashboard stability issue and rolled the UI back to a more stable version in the recent 2.6.0 release. Due to the number of issues related to this, I'm going to close all of these issues as Completed. Please open a new issue if you are still seeing the Dashboard stability problems on 2.6.0.
