### ISSUE TITLE
Missing tsm file causing snapshot to fail

### ISSUE THREAD

**Issue by davidhemp** [influxdata/influxdb#23957]
Influxdb seems to be complaining it can't snapshot a file that doesn't exist. 

[root@grafana 59]# journalctl -u influxdb -r | head
Nov 29 11:24:43 grafana.rcs.ic.ac.uk influxd-systemd-start.sh[59665]: ts=2022-11-29T11:24:43.423086Z lvl=info msg="Cache snapshot (start)" log_id=0eSirn5l000 service=storage-engine engine=tsm1 op_name=tsm1_cache_snapshot op_event=start
Nov 29 11:24:43 grafana.rcs.ic.ac.uk influxd-systemd-start.sh[59665]: ts=2022-11-29T11:24:43.423077Z lvl=info msg="Error writing snapshot" log_id=0eSirn5l000 service=storage-engine engine=tsm1 error="sync /var/lib/influxdb/engine/data/5929c235312b76a8/autogen/59/000018566-000000001.tsm.tmp: input/output error"
Nov 29 11:24:43 grafana.rcs.ic.ac.uk influxd-systemd-start.sh[59665]: ts=2022-11-29T11:24:43.423065Z lvl=info msg="Cache snapshot (end)" log_id=0eSirn5l000 service=storage-engine engine=tsm1 op_name=tsm1_cache_snapshot op_event=end op_elapsed=990.353ms

Checking the data directory, no such file seems to be present. 
/var/lib/influxdb/engine/data/5929c235312b76a8/autogen/59
[root@grafana 59]# ls
000000128-000000004.tsm  000000392-000000002.tsm  000000409-000000001.tsm  000000412-000000001.tsm  000000415-000000001.tsm  000014539-000000001.tsm  index
000000256-000000004.tsm  000000400-000000002.tsm  000000410-000000001.tsm  000000413-000000001.tsm  000000416-000000001.tsm  000014733-000000001.tsm
000000384-000000004.tsm  000000408-000000002.tsm  000000411-000000001.tsm  000000414-000000001.tsm  000000417-000000001.tsm  fields.idx

[root@grafana 59]# influxd version
InfluxDB v2.5.1 (git: 5b6fdbf05d) build_date: 2022-11-02T18:06:28Z

The database is running a high load and caught in a loop trying to complete this task.

**Comment by jeffreyssmith2nd** [comment]
> sync /var/lib/influxdb/engine/data/5929c235312b76a8/autogen/59/000018566-000000001.tsm.tmp: input/output error

Part of the process is writing to a temp file, and then finalizing all the data to a regular file when everything is complete. The `input/output error` sounds like it could be a lower level issue, do you have plenty of disk space available? I assume the permissions are fine on that dir since you have other files there, but I would double check that as well.

**Comment by davidhemp** [comment]
Issue was with hypervisor not being able to allocate space to the vm. Solved by increasing storage.
