### ISSUE TITLE
influx secret delete fails with "405 Method Not Allowed:"

### ISSUE THREAD

**Issue by andrewbierbaum** [influxdata/influxdb#23964]
<!--

Thank you for reporting a bug in InfluxDB. 

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. create a secret and then try to delete it immediately after
```
18:06 andrewbierbaum@jng4m1influxdb2:~$ sudo influx secret update -k testing -v asdf
Key	Organization ID
testing	335d31413785462f
18:06 andrewbierbaum@jng4m1influxdb2:~$ sudo influx secret delete -k testing
Error: failed to delete secret with key "testing": 405 Method Not Allowed:
```

__Expected behavior:__
The secret should delete and not return a `405 Method Not Allowed:`

__Actual behavior:__
returns a `405 Method Not Allowed:`

__Environment info:__

* System info: `Linux 4.15.0-192-generic x86_64`
* InfluxDB version: `InfluxDB v2.4.0 (git: de247bab08) build_date: 2022-08-18T19:41:15Z` and `
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
18:14 andrewbierbaum@tuk5r1influxdbts2:~$ sudo cat /root/.influxdbv2/configs
[default]
  url = "http://localhost:8086"
  token = "REACTED"
  org = "REACTED"
  active = true

**Comment by jeffreyssmith2nd** [comment]
Duplicates #23965
