### ISSUE TITLE
GitHub releases have busted Markdown

### ISSUE THREAD

**Issue by elyscape** [influxdata/influxdb#23981]
The GitHub releases for both [influxdb][influxdb-v2.6.0] and [influx-cli][influx-cli-v2.6.0] have a notice at the top that reads as follows:

> In addition to the list of changes below, please also see the [official release notes](https://docs.influxdata.com/influxdb/v2.6/reference/release-notes/influxdb/) for other important information about this release.

Unfortunately, whatever's generating the markdown is incorrectly inserting a space between the bracketed link text and the parenthesized URL, resulting in it being rendered like this:

> In addition to the list of changes below, please also see the [official release notes] (https://docs.influxdata.com/influxdb/v2.6/reference/release-notes/influxdb/) for other important information about this release.

This appears to have been broken sometime between the releases of versions [2.4.0][influxdb-v2.4.0] and [2.5.0][influxdb-v2.5.0].

[influxdb-v2.4.0]: https://github.com/influxdata/influxdb/releases/tag/v2.4.0
[influxdb-v2.5.0]: https://github.com/influxdata/influxdb/releases/tag/v2.5.0
[influxdb-v2.6.0]: https://github.com/influxdata/influxdb/releases/tag/v2.6.0
[influx-cli-v2.6.0]: https://github.com/influxdata/influx-cli/releases/tag/v2.6.0

**Comment by elyscape** [comment]
As an aside, one option that might help with this is that you can format Markdown links like this:

```markdown
In addition to the list of changes below, please also see the [official release notes] for other important information about this release.

Other text can go here, including [another way to do this][official release notes].

[official release notes]: https://docs.influxdata.com/influxdb/v2.6/reference/release-notes/influxdb/
```
This will render like so:

> In addition to the list of changes below, please also see the [official release notes] for other important information about this release.
> 
> Other text can go here, including [another way to do this][official release notes].
> 
> [official release notes]: https://docs.influxdata.com/influxdb/v2.6/reference/release-notes/influxdb/

**Comment by jeffreyssmith2nd** [comment]
Thanks for catching this, we switched to a new tool for generating notes in 2.5. I've manually fixed it in influxdb and influx-cli, and added a fix to the internal tooling to my backlog.
