### ISSUE TITLE
the link provided in the documentation to download influxdb on linux is incorrect

### ISSUE THREAD

**Issue by Houssem12-ai** [influxdata/influxdb#24008]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. enter the download page : https://docs.influxdata.com/influxdb/v2.6/install/?t=Linux
2.execute the download command : wget https://dl.influxdata.com/influxdb/releases/influxdb2-2.6.0-xxx.deb

__Expected behavior:__
HTTP request sent, awaiting response... 200 OK
Length: 103762892 (99M) [application/octet-stream]
Saving to: ‘influxdb2-2.0.8-amd64.deb’

influxdb2-2.0.8-amd64.deb                          100%[================================================================================================================>]  98,96M  7,36MB/s    in 23s     

__Actual behavior:__
Resolving dl.influxdata.com (dl.influxdata.com)... 52.85.96.73, 52.85.96.123, 52.85.96.129, ...
Connecting to dl.influxdata.com (dl.influxdata.com)|52.85.96.73|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-24 16:18:09 ERROR 404: Not Found.

___solution___

i solved the issue by specifying another link which is : https://dl.influxdata.com/influxdb/releases/influxdb2-2.6.0-amd64.deb
instead of this wrong link : https://dl.influxdata.com/influxdb/releases/influxdb2-2.6.0-xxx.deb

I believe that it's importing to notify the user that he has to specify the cpu architecture type at the end of the command (amd64 in my case)

**Comment by jeffreyssmith2nd** [comment]
Upon further inspection, the documentation does warn to download the correct path.

```
Use the exact filename of the download of .rpm package (for example, influxdb2-2.6.1-amd64.rpm).
```

I believe this should be sufficient to provide people with the correct documentation. Feel free to open an issue against https://github.com/influxdata/docs-v2 or submit a PR if there is a way to improve the documentation further.
