### ISSUE TITLE
API Token

### ISSUE THREAD

**Issue by rics81** [influxdata/influxdb#24005]
Steps to reproduce:
1. Follow the steps to workaround on https://github.com/influxdata/influxdb/issues/23668
2. ...
3. ...

__Expected behavior:__
Create a token successfully

__Actual behavior:__
Error: could not find user with name "": 401 Unauthorized: unauthorized access

__Environment info:__

* System info: Linux 5.4.17-2136.314.6.3.el8uek.x86_64 x86_64
* InfluxDB version: InfluxDB v2.6.0 (git: 24a2b621ea) build_date: 2022-12-15T18:47:00Z

**Comment by jeffreyssmith2nd** [comment]
This sounds like you are not logged in on the CLI when attempting to create the all access token. However, 2.6.1 was just released and should allow you to create all access tokens through the UI again.

**Comment by rics81** [comment]
> This sounds like you are not logged in on the CLI when attempting to create the all access token. However, 2.6.1 was just released and should allow you to create all access tokens through the UI again.

Thank you very much! :)
