### ISSUE TITLE
Anti brute force protection

### ISSUE THREAD

**Issue by fthiery** [influxdata/influxdb#24016]
Hello; i looked everywhere but did not find anything in the docs or by searching, so i thought i should ask here.

Does influxdb2 support some form of anti-brute force protection, like Grafana (https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#disable_brute_force_login_protection) ?

If not, how can this be achieved (which logs should contain authentication errors, how should they look like, how to create a fail2ban configuration...) ?

**Comment by jeffreyssmith2nd** [comment]
There are no builtin provisions for brute force protection. The unauth'd logs should look like the one below.
```
2023-01-05T15:19:06.991609Z     info    Unauthorized    {"log_id": "0fCcBaFG000", "error": "token required"}
```

**Comment by fthiery** [comment]
Which log is that supposed to be ? The influx2 binary (e.g. in journald if run using systemd) ?

Unfortunately, this log does not include any IP address that could be used to ban the offending IP.

Any advice on how to protect an influxdb instance against such attacks ?

**Comment by fthiery** [comment]
Taking the liberty to add the comment from someone in the Influx team i got on the community slack: "with regards to the UI login currently not. You can either disable the UI entirely. Enterprise and Cloud handle these risks with greater consideration. The API is all token based so would be extremely hard to brute force login".

I guess that for the OSS version, the solution is:
- disable the web UI when unused (https://docs.influxdata.com/influxdb/v2.0/reference/config-options/#ui-disabled)
- monitor/supervise request rate on e.g. nginx frontend
