### ISSUE TITLE
No bucket found in organization

### ISSUE THREAD

**Issue by fsime** [influxdata/influxdb#24013]
If I add a new bucket to my influxdb organization with new custom api token with rw permission,
when query from grafana or curl I get "not found: no buckets found in organization a142823013a8b3c9 error reading buckets"
How can I further troubleshoot ?

influx auth list
0a8213fabcec2000        stmapi                          bhdfuwefbuwefhweuhfuwehfweufhuewfewfewfewfwdbhdfuwefbuwefhweuhfuwehfweufhuewfewfewfewf==        admin           09d083af5f589000        [read:orgs/a142823013a8b3c9/buckets/bb8d28431b21722e write:orgs/a142823013a8b3c9/buckets/bb8d28431b21722e]

influx bucket list -o XXX
bb8d28431b21722e        stm                             infinite        168h0m0s                a142823013a8b3c9        implicit

not found: no buckets found in organization a142823013a8b3c9 error reading buckets

__Environment info:__

* System info: Linux 5.15.0-56-generic x86_64
* InfluxDB version: InfluxDB v2.6.0 (git: 24a2b621ea) build_date: 2022-12-15T18:47:00Z

thx

**Comment by fsime** [comment]
Now It's working.

**Comment by ducna96** [comment]
Hi, how to fix this error ?

**Comment by ducna96** [comment]
> Now It's working.
Hi bro, how to fix this error  ?
