### ISSUE TITLE
 Influxdb2 does not start - error: “InfluxDB API at http://localhost:8086/ready unavailable after 219 attempts…” 

### ISSUE THREAD

**Issue by olikra** [influxdata/influxdb#24024]
After a poweroutage on my Mac, the influxdb2 in virtualbox does not start anymore. in syslog many messages → “InfluxDB API at http://localhost:8086/ready unavailable after 219 attempts…” appear.

OS: Ubuntu 22.04.1 LTS
influxDB2: 2.6.1-1

Already tried removing "Type=forking” without success.

Any ideas?

**Comment by DonKingMat** [comment]
Same from here on a RasPi CM4 which means "after one power outage" and also having
OS: Ubuntu 22.04.1 LTS
influxDB2: 2.6.1-1

**Comment by jeffreyssmith2nd** [comment]
Do you have any logs from influx other than that? If you set the log level to debug, it should show what its trying to do at startup.
