### ISSUE TITLE
 data race between test and product code in partition compaction [Port to 1.11 branch]

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influxdb#24041]
Port https://github.com/influxdata/influxdb/issues/24040 to 1.11 branch

**Comment by davidby-influx** [comment]
This should go in 1.11.7

**Comment by devanbenz** [comment]
Branch has been merged. Closing issue.

**Comment by devanbenz** [comment]
reopening to track: https://github.com/influxdata/influxdb/pull/25338

**Comment by devanbenz** [comment]
Closing
