### ISSUE TITLE
Retention of bucket data

### ISSUE THREAD

**Issue by LukasTr1980** [influxdata/influxdb#24043]
__Steps to reproduce:__

1. sudo systemctl restart influxdb.service
2. sudo reboot

__Expected behavior:__
No changes on the retention policy!

__Actual behavior:__
I have bucket where i need retention policy "infinite". After i execute the commands above, the retention policy gets set to 365 days.
Sorry, but, event if the software is free, this is some insane behaviour.

__Environment info:__

* System info: Linux 5.4.0-137-generic x86_64
* InfluxDB version: InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:07Z
* Other relevant environment details: Nothing, direct install

**Comment by jeffreyssmith2nd** [comment]
Does this happen every time or did this only happen once? Do you have any logs from the process at shutdown/startup that you can share?

**Comment by LukasTr1980** [comment]
Unfortunately not on systemctl restart. Did not reboot my server recently.
But it happend today after i execuded a big query. Attached logs from syslog.

[syslog.log](https://github.com/influxdata/influxdb/files/10469666/syslog.log)

**Comment by LukasTr1980** [comment]
Imagine if you log a temperature over a long time period. This would cause a irretrievable data loss.

**Comment by jeffreyssmith2nd** [comment]
Looks like it OOM'd before it happened this time, has that happened in the past when the retention policy has changed?

**Comment by LukasTr1980** [comment]
Yes.
Yesterday I tried to delete a bucket from UI. No reaction, hang up. Retention policy set to 365 days instead of infinite.
I had to restart the influxd service, and then, from CLI, I could delete the bucket. Otherwise, there was no chance.

Personally, I don't use the UI anymore. It is too buggy. I would consider to add a "retention lock" because this behavior in my opinion is critical.

Thank you for your replies.
Greetings

**Comment by Spectrum1981** [comment]
Same her. After a reboot of my pi the retention poliys of my buckets are shuffled.

Her are my buckets:

ID                      Name                    Retention       Shard group duration    Organization ID         Schema Type
ff2f152dc319148b        _monitoring             168h0m0s        24h0m0s                 21f0b502b5f67e75        implicit
455da0b29b6e2d04        _tasks                  72h0m0s         24h0m0s                 21f0b502b5f67e75        implicit
d531e1fd58e686b5        iobroker_30Tage         720h0m0s        168h0m0s                21f0b502b5f67e75        implicit
8690121889bd8009        iobroker_7Tage          168h0m0s        168h0m0s                21f0b502b5f67e75        implicit
dad20e2e5b786be5        iobroker_forever        infinite        168h0m0s                21f0b502b5f67e75        implicit


Sorry, i dont have a screen where the error can be seen.

**Comment by ikmd** [comment]
Hi, I'm having the same issue. Using v2.6.1 as well.
My main bucket is always reset to 365 days after stopping and starting the influxdb service - which for me happens every night during backup.
It was created in a previous version of influxdb 2.
I only have a second bucket with downsampled data where this doesn't happen. I don't know if this second bucket was created in 2.6.1 though.

My main bucket is too big if not retained, so it's not as critical as for others who lose data.

I tried to change the retention period via UI and CLI:
`influx bucket update -id BUCKETID --retention 7d --token TOKEN`
Both update the retention, but after stop/start it's back to 365 days.

As workaround I've now set up a cron job to set it every night (after backup), but that only works if you want to reduce the retention period.

**Comment by LukasTr1980** [comment]
> Same her. After a reboot of my pi the retention poliys of my buckets are shuffled.
> 
> Her are my buckets:
> 
> ID Name Retention Shard group duration Organization ID Schema Type ff2f152dc319148b _monitoring 168h0m0s 24h0m0s 21f0b502b5f67e75 implicit 455da0b29b6e2d04 _tasks 72h0m0s 24h0m0s 21f0b502b5f67e75 implicit d531e1fd58e686b5 iobroker_30Tage 720h0m0s 168h0m0s 21f0b502b5f67e75 implicit 8690121889bd8009 iobroker_7Tage 168h0m0s 168h0m0s 21f0b502b5f67e75 implicit dad20e2e5b786be5 iobroker_forever infinite 168h0m0s 21f0b502b5f67e75 implicit
> 
> Sorry, i dont have a screen where the error can be seen.

My friend, i found the problem, especially if i read iobroker. In the settings of the influxdb instanz in iobroker, go to standard settings. There is a setting called "Retention Period". By default it is set to 365 days. Check if that is your case.
So in my case, it was not a probelm of influxdb, but indeed this setting.

Greetings

**Comment by ikmd** [comment]
Thanks for the quick reply.
Yes, using iobroker, so this is actually not an influxdb issue but an iobroker setting.
I guess this issue can be closed?

**Comment by jeffreyssmith2nd** [comment]
Good to hear this was resolved for you!
