### ISSUE TITLE
data race between test and product code in partition compaction [Port to master-1.x]

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influxdb#24042]
Port https://github.com/influxdata/influxdb/issues/24040 to master branch

**Comment by devanbenz** [comment]
Closing - branch has been merged!

**Comment by devanbenz** [comment]
reopen for new pr

**Comment by devanbenz** [comment]
https://github.com/influxdata/influxdb/pull/25338 Using this Ticket to track
