### ISSUE TITLE
FR - Jupysql Integration

### ISSUE THREAD

**Issue by idomic** [influxdata/influxdb#24056]
## Description
It'd be great to see a tutorial or documentation of the 2 frameworks.
Probably a user working locally via a jupyter notebook and [jupysql](https://github.com/ploomber/jupysql) to query and perform EDA/modeling work.

## Motivation
Please provide the following for the desired feature or change:

A detailed explanation on querying via SQL.
Plotting via sql.
Using Jupyter notebooks to query.

Happy to work on the PR!

**Comment by jeffreyssmith2nd** [comment]
Hey @idomic thanks for the interest! Just to clear things up, the current 2.x line of InfluxDB does **not** support querying via standard SQL. It supports InfluxQL (a custom language with SQL like semantics) and Flux.

The upcoming storage engine [IOX](https://www.influxdata.com/blog/intro-influxdb-iox/) supports querying via standard SQL. If you'd like to request documentation for that/submit a PR, I would suggest starting a discussion over at https://github.com/influxdata/docs-v2 to see what needs to be done.
