### ISSUE TITLE
Linux package signing key rotation

### ISSUE THREAD

**Issue by jdstrand** [influxdata/influxdb#24060]
We're rotating our Linux package signing key on 2023-01-26. Please see https://www.influxdata.com/blog/linux-package-signing-key-rotation/ for details.

**Comment by RoyKas** [comment]
Just attempted to update the key as per above referenced instructions.
First line is not working, wget command is incorrect. Also the URL (https://repos.influxdata.com/influxdata-archive_compat.key) results in 404 error.

**Comment by jdstrand** [comment]
FYI, we're in the process of moving the new files into place now. This will be the correct URL but the roll-over is only partially done now. We'll update the blog post when the process is complete.

cc @bnpfeife and @dgnorton

**Comment by jdstrand** [comment]
FYI, the current progress is that the DEB archive is done, the RPM is in progress and the regeneration of the index.html and files at the top of https://repos.influxdata.com (ie, the new keys) will be after that.

**Comment by jdstrand** [comment]
> FYI, the current progress is that the DEB archive is done, the RPM archive is in progress and the regeneration of the index.html and files at the top of https://repos.influxdata.com/ (ie, the new keys) will be after that. We apologize for the interruption and appreciate your patience while the roll-over is in progress.

The roll-over is completed and the blog post migration procedure should now work.

**Comment by jdstrand** [comment]
Fyi, now that everything has been signed with the new key since January and nothing should be using the new key, we have revoked the previous signing key (ie, https://repos.influxdata.com/influxdb.key (`05CE 1508 5FC0 9D18 E99E FB22 684A 14CF 2582 E0C5`)) and updated the keyservers. We're in the process of updating https://repos.influxdata.com/influxdb.key now to contain the updated revoked key.

**Comment by jdstrand** [comment]
> We're in the process of updating https://repos.influxdata.com/influxdb.key now to contain the updated revoked key.

This is now done.
