### ISSUE TITLE
missing gpg key on repos.influxdata.com

### ISSUE THREAD

**Issue by underley** [influxdata/influxdb#24066]
__Steps to reproduce:__

```
# http get https://repos.influxdata.com/influxdb.key
HTTP/1.1 404 Not Found
Age: 7
Connection: keep-alive
Content-Length: 347
Content-Type: text/html; charset=utf-8
Date: Thu, 26 Jan 2023 19:51:36 GMT
Server: AmazonS3
Via: 1.1 f1e707a645d1b585e3b6fc5ef39d2e56.cloudfront.net (CloudFront)
X-Amz-Cf-Id: VNl6Uis29fgUQB4G5seZW8DhqrQ1Txg8Ewo5fHTuYXgoaQVFmnf7zw==
X-Amz-Cf-Pop: WAW51-P1
X-Cache: Error from cloudfront

<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: influxdb.key</li>
<li>RequestId: KXFTHXE1SVEH27TY</li>
<li>HostId: z/u4O2ohPBpN58z3aFzpSmXg3N7yw3LSElvqgWBs7eZEJx3R2xzDeO4YOt3phTPv6j0bI4iJ3pc=</li>
</ul>
<hr/>
</body>
</html>

```

__Expected behavior:__
according to documentation, a valid gpg key should be available with this url

__Actual behavior:__
http 404 instead of gpg key

**Comment by cvick** [comment]
[According to their blog post on Jan 24](https://www.influxdata.com/blog/linux-package-signing-key-rotation/) they've rotated their signing keys. [But the key at the new URL](https://repos.influxdata.com/influxdata-archive_compat.key) 404s as well.

**Comment by underley** [comment]
wget https://repos.influxdata.com/influxdata-archive_compat.key
--2023-01-26 22:02:00--  https://repos.influxdata.com/influxdata-archive_compat.key
Resolving repos.influxdata.com (repos.influxdata.com)... 18.66.233.127, 18.66.233.6, 18.66.233.15, ...
Connecting to repos.influxdata.com (repos.influxdata.com)|18.66.233.127|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-26 22:02:00 ERROR 404: Not Found.

**Comment by underley** [comment]
and docs still point to old url

**Comment by tubemeister** [comment]
Keys are back online here. 

Both the old key and the new key, this is going to get confusing for people. ;-)

**Comment by Starfoxfs** [comment]
On my Raspberry Pi 4B Debian Bullseye 11 (64bit)

The `wget` command don´t work anymore. 

I have the Install Instructions from here:
https://portal.influxdata.com/downloads/

Ubuntu & Debian ARM64

`# influxdata-archive_compat.key GPG fingerprint:
#     9D53 9D90 D332 8DC7 D6C8 D3B9 D8FF 8E1F 7DF8 B07E
wget -q https://repos.influxdata.com/influxdata-archive_compat.key
echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
`
It works only with Root:
`sudo wget -q https://repos.influxdata.com/influxdata-archive_compat.key`

previously it worked without root.

**Comment by Starfoxfs** [comment]
This part doesn´t work on Rpi4B 64bit Raspian OS latest updates.

`wget -q https://repos.influxdata.com/influxdata-archive_compat.key`

only works with:

`sudo wget -q https://repos.influxdata.com/influxdata-archive_compat.key`

**Comment by jeffreyssmith2nd** [comment]
@Starfoxfs Are you running that command inside a directory that is root owned? There is nothing server side that would know if you are running under `sudo` or not.

**Comment by Starfoxfs** [comment]
Hi,
no in /home directory

**Comment by Joulinar** [comment]
> no in /home directory

You need to be within user home directory and not within `/home`

```
cd
wget -q https://repos.influxdata.com/influxdata-archive_compat.key
```

**Comment by Starfoxfs** [comment]
Ah thanks @Joulinar 

That was the Problem, /home is also root owned /home/user isn´t.

**Comment by jeffreyssmith2nd** [comment]
This all appears to be working and properly documented, please open a new issue if further issues arise.
