### ISSUE TITLE
panic in "cursors.(*IntegerArray).Len(...)"

### ISSUE THREAD

**Issue by pespin** [influxdata/influxdb#24069]
__Steps to reproduce:__

I am porting the contents of a mariadb containing electrical power meter measurements to influxdb.
The data is coming in statsd and is still being fed to mariadb currently. I then set another statsd exporter  in parallel which sends data to telegraf with statsd plugin which in turn feeds it to influxdb v2.6.1. I use both influxdb UI and grafana to see the measurements over time.
This all goes well in principle. The bucket is set to never delete data.

I also wrote a script (attached here: [convert_mariadb_influxdb.py.gz](https://github.com/influxdata/influxdb/files/10539345/convert_mariadb_influxdb.py.gz)) to push the ~2 years of measurements (of around 1 point per minute) of 2 different devices from mariadb to influxdb.
For that, I stopped telegraf, cleaned the bucket, and run the script until it was done, and then started telegraf again.
This works all great: all data is now in influxdb (the one from the script and current ones fed from telegraf), I can see it using infxludb UI and grafana.

The system runs for several days, all fine. Then I decided to restart influxd service (systemctl restart influxdb).
Intermediately after the db is restarted (correctly), grafana and influxdb UI show correctly data up to 12h ago, but fails to show data properly if I set the graph to show data 24h or older.

Every time I try to get the larger timespan of data (let's say show me data for last month), it fails in both grafana nd influxdb UI, and I see this panic of influxdb in journald:
```
Jan 30 19:09:27 localhost influxd-systemd-start.sh[2287937]: ts=2023-01-30T19:09:27.554914Z lvl=info msg="Execute source panic" log_id=0fi0xAqW000 service=storage-reads error="panic: runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 7425 [running]:
runtime/debug.Stack()
	/go/src/runtime/debug/stack.go:24 +0x68
github.com/influxdata/flux/execute.(*executionState).recover(0x400687a6c0)
	/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/recover.go:32 +0x1e0
panic({0xffff97a41260, 0xffff98f587f0})
	/go/src/runtime/panic.go:838 +0x204
github.com/influxdata/influxdb/v2/tsdb/cursors.(*IntegerArray).Len(...)
	/root/project/tsdb/cursors/arrayvalues.gen.go:227
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*integerArrayAscendingCursor).reset(0x400474cf50, 0x173e8ea8e718340b, 0x40038fd290?, {0x0?, 0x40065f1590?, 0x67?}, 0x40056a8cf0)
	/root/project/tsdb/engine/tsm1/array_cursor.gen.go:333 +0xf4
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*arrayCursorIterator).buildIntegerArrayCursor(_, {_, _}, {_, _, _}, {_, _, _}, {_, ...}, ...)
	/root/project/tsdb/engine/tsm1/array_cursor_iterator.gen.go:46 +0x35c
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*arrayCursorIterator).Next(0x4006a06e70, {0xffff97e00858, 0x40038fd290}, 0x400573e250)
	/root/project/tsdb/engine/tsm1/array_cursor_iterator.go:67 +0x210
github.com/influxdata/influxdb/v2/storage/reads.(*multiShardArrayCursors).createCursor(0x400573e240, {{0x0, 0x0, 0x0}, {0xffff652118a0, 0xb, 0x3ff760}, {0x40065f1590, 0x5, 0x5}, ...})
	/root/project/storage/reads/array_cursor.go:118 +0x158
github.com/influxdata/influxdb/v2/storage/reads.(*windowAggregateResultSet).createCursor(0x40065f13b0, {{0x0, 0x0, 0x0}, {0xffff652118a0, 0xb, 0x3ff760}, {0x40065f1590, 0x5, 0x5}, ...})
	/root/project/storage/reads/aggregate_resultset.go:100 +0x8c
github.com/influxdata/influxdb/v2/storage/reads.(*windowAggregateResultSet).Next(0x40065f13b0)
	/root/project/storage/reads/aggregate_resultset.go:84 +0xf4
github.com/influxdata/influxdb/v2/storage/flux.(*windowAggregateIterator).handleRead(0x40057b0200, 0xffff97e00858?, {0xffff97e0ca58, 0x40065f13b0})
	/root/project/storage/flux/reader.go:742 +0x340
github.com/influxdata/influxdb/v2/storage/flux.(*windowAggregateIterator).Do(0x40057b0200, 0xffff97cadfc0?)
	/root/project/storage/flux/reader.go:688 +0x2b0
github.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*Source).processTables(0x400393d600, {0xffff97e00858?, 0x40038fd290}, {0xffff97df4188, 0x40057b0200}, 0x0?)
	/root/project/query/stdlib/influxdata/influxdb/source.go:69 +0xb8
github.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*readWindowAggregateSource).run(0x400393d600, {0xffff97e00858, 0x40038fd290})
	/root/project/query/stdlib/influxdata/influxdb/source.go:303 +0xd4
github.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*Source).Run(0x400393d600, {0xffff97e00858, 0x40038fd290})
	/root/project/query/stdlib/influxdata/influxdb/source.go:50 +0x7c
github.com/influxdata/flux/execute.(*executionState).do.func2({0xffff97e028b8?, 0x400393d600})
	/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/executor.go:535 +0x310
created by github.com/influxdata/flux/execute.(*executionState).do
	/go/pkg/mod/github.com/influxdata/flux@v0.191.0/execute/executor.go:515 +0x398
"
```

So it seems restarting the process is breaking something in the state ot database or god knows.

__Expected behavior:__

Data to be displayed fine after process restart, as it did before I restarted the process.

__Actual behavior:__

After process restart, data older than 24h seems to be failing to be shown, influxdb panics.

__Environment info:__

The host holding the database is a RPI4 with btrfs disks in RAID to have duplicate data.
```
# uname -srm
Linux 5.10.0-18-arm64 aarch64
```

```
# influxd version
InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:52:06Z
```

**Comment by davidby-influx** [comment]
Fixed: https://github.com/influxdata/influxdb/pull/24787
