### ISSUE TITLE
Requests to sentry.io after disabling telemetry

### ISSUE THREAD

**Issue by ollie-campbell** [influxdata/influxdb#24071]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. Install influx
2. Set the '--reporting-disabled' flag
3. Install grafana
4. Setup a dashboard
5. Use your browsers developer console to look at network requests

__Expected behavior:__
No external contact even telemetry.

__Actual behavior:__
Requests to "https://o1313669.ingest.sentry.io/api/XXXXXX/XXXXXXX/XXXXXX" seen.

__Environment info:__

* System info: Linux 5.15.0-58-generic x86_64
* InfluxDB version: InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:07Z

__Config:__
/usr/lib/influxdb/scripts/influxd-systemd-start.sh
line 3 has been changed to read: /usr/bin/influxd --reporting-disabled &

Screenshot:
![image](https://user-images.githubusercontent.com/43950743/215844201-763e7f18-6270-45ae-863e-bf81d1616cbe.png)

**Comment by jeffreyssmith2nd** [comment]
You're seeing these in your browser console while in the Grafana dashboard? This is coming from Grafana and not from InfluxDB. We do not send telemetry requests to sentry.io, they are sent to telemetry.influxdata.com and are sent by the server process not in browser.

**Comment by ollie-campbell** [comment]
> You're seeing these in your browser console while in the Grafana dashboard? This is coming from Grafana and not from InfluxDB. We do not send telemetry requests to sentry.io, they are sent to telemetry.influxdata.com and are sent by the server process not in browser.

My mistake. Thank you for the clarification.
