### ISSUE TITLE
All Access Token cannot create new users within an org

### ISSUE THREAD

**Issue by BrimStoneGit** [influxdata/influxdb#24079]
Link to the influx community thread: https://community.influxdata.com/t/users-scope-no-longer-in-all-access-token/28375

In my understanding, the All Access Token of an org should be able to create new users in that org. But it seems like this is not the case.

__Steps to reproduce:__

1. Log into the InfluxDB UI via Credentials of an owner account
2. Go to the "API Token" Section
3. Click on "+ Generate API Token" --> "All Access Token"
4. Copy new token 
5. Run the command `influx user create -n <name> -o <org> -p <password> -t <newly created All Access Token>` on the machine influx is running on
6. Get the Error: `Error: failed to create user "<name>": 401 Unauthorized: write:users is unauthorized`

__Expected behavior:__
The user creation should return with a success message with the new user name and id.

__Actual behavior:__
`Error: failed to create user "<name>": 401 Unauthorized: write:users is unauthorized`

__Environment info:__

* System info: Linux 5.10.0-21-amd64 x86_64
* InfluxDB version: InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:07Z
* Other relevant environment details: Docker Engine and Server on v.23.0.0

**Comment by jeffreyssmith2nd** [comment]
Closing, responded in the community forums.
