### ISSUE TITLE
Can not output default config file to customize it

### ISSUE THREAD

**Issue by cedricfranke28** [influxdata/influxdb#24084]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Output the default config file does not work

- I use the current version: InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:06Z
- Also the current CLI version: Influx CLI 2.6.1 (git: 61c5b4d) build_date: 2022-12-29T15:41:09Z
- I wanted to output the default config to customize the data location folder

-->  influx.exe config > influxdb_custom.config
This command gave me the following config 
![image](https://user-images.githubusercontent.com/62056776/217498653-953a731b-4de5-47c6-98df-bb3428ae7c5c.png)

according to different websites like this one: https://thesqldump.code.blog/2019/11/13/install-configure-and-run-influxdb-on-windows/
My default config is not what i expected.

Is there any instructions to get the default config file and edit. And how the config file should look like?  

__Expected behavior:__
I expected to get an default config file which i can customize to change the data location folder

__Environment info:__

* InfluxDB version:  InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:06Z
* operating system: Windows 10 

```

**Comment by jeffreyssmith2nd** [comment]
That blog is referencing the `influxd config` command that existed in 1.x. Since you are using 2.6.1, you can use the `influxd print-config` command. Note you need to run the `influxd` command and not the `influx` command.

**Comment by cedricfranke28** [comment]
Thank you but i want know to run the influxd.exe with the config.toml file which i got from your command. But it throws me this error.

![image](https://user-images.githubusercontent.com/62056776/217561831-e61b0039-d3ad-4fd0-b1c9-1acdb594c04e.png)
