### ISSUE TITLE
Operator token does not show after setup.

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [influxdata/influxdb#24082]
In 2.5.0 we brought the UI up to speed with the latest available at the time. This introduced the behavior where tokens are only shown once immediately after creation. This is acceptable on the token creation screen.

However, OSS has the concept of an operator token. This is a special token created when the instance is setup that has superuser privileges. Right now, there is no way to see this token.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Startup a clean OSS instance
2. Go through setup
3. Go to the token page and notice you cannot see the operator token (and that it was not presented after setup).

__Expected behavior:__
A user can see their operator token. I think it would be perfectly acceptable for it to show once after setup using the same dialog that shows after a token is created from the token page.

**Comment by sanderson** [comment]
@jeffreyssmith2nd I totally agree with the expected behavior. Another workflow to consider is setting up InfluxDB through the `influx` CLI and providing the operator token in that workflow.

**Comment by jeffreyssmith2nd** [comment]
Thanks for the reminder @sanderson, the current workarounds are:

1. Setup using `influx setup` via the influx CLI. This will auto populate the created config with the operator token.
2. Clone the operator token in the UI and use the cloned token the same way you would use the original operator token.
3. Login to the influx CLI using `influx config create --username-password ...` with the operator's credentials, and all CLI commands will be authorized as an operator.
