### ISSUE TITLE
Task create returns error 400 due to file name? 

### ISSUE THREAD

**Issue by snoopiedoom** [influxdata/influxdb#24104]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Created flux task file called [cq-1m.flux](https://gist.github.com/snoopiedoom/7ea361f36533e549953072211bbc59ed)

2. Tried adding task to influx: `influx task create --org Symbiot -f .\cq-1m.flux`, get the following error: `Error: 400 Bad Request: invalid options: loc 1:1-1:4: invalid statement @1:1-1:4:`

3. Created an identical file called tmp.flux, task creation succeeds.

__Expected behavior:__
Creates a task from file

__Actual behavior:__
Fails to create a task from a file with a dash in its name?
```
PS C:\sw\Main\Symbiot\Setup\Release\Symbiot\Symbiot Monitor> influx task ls
ID      Name    Organization ID Organization    Status  Every   Cron    ScriptID
PS C:\sw\Main\Symbiot\Setup\Release\Symbiot\Symbiot Monitor> influx task create --org Symbiot -f .\cq-1m.flux
Error: 400 Bad Request: invalid options: loc 1:1-1:4: invalid statement @1:1-1:4: ﻿
PS C:\sw\Main\Symbiot\Setup\Release\Symbiot\Symbiot Monitor> influx task create --org Symbiot -f .\tmp.flux
ID                      Name            Organization ID         Organization    Status  Every   Cron    ScriptID
0accbb2e23ee2000        cq_eve_1m       1ce011d23a3e88ee        Symbiot         active  1m
PS C:\sw\Main\Symbiot\Setup\Release\Symbiot\Symbiot Monitor> compare-object (get-content .\tmp.flux) (get-content .\cq-1m.flux)
PS C:\sw\Main\Symbiot\Setup\Release\Symbiot\Symbiot Monitor> uname -srm
CYGWIN_NT-10.0-19044 3.3.6-341.x86_64 x86_64
```

__Environment info:__

* System info: CYGWIN_NT-10.0-19044 3.3.6-341.x86_64 x86_64
* InfluxDB version: InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:06Z
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
```
# v2 InfluxDB config file

# storage engine, includes data and wal
engine-path = "C:/Program Files/InfluxData/InfluxDB/engine/"

# boltdb, file-based key-value store for non-time series data
bolt-path = "C:/Program Files/InfluxData/InfluxDB/influxd.bolt"

# sqlite
sqlite-path = "C:/Program Files/InfluxData/InfluxDB/influxd.sqlite"

# v1 name: series-id-set-cache-size
storage-series-id-set-cache-size = 100

# bind address
http-bind-address = ":8086"

# Disable the InfluxDB user interface (UI). The UI is enabled by default.
ui-disabled = false
```

**Comment by jeffreyssmith2nd** [comment]
I was unable to reproduce this in Cygwin, CMD, or Powershell. Is there anything else that could be going on like file permissions, etc that might be different between the two files?

**Comment by snoopiedoom** [comment]
Not sure, I'm unable to replicate it again. Thought the main culprit would be tfvc but its working fine, using the file in question as the task script works fine as well ¯\_(ツ)_/¯. It probably is file permission issues, I guess I'll be restarting windows more often.
Thanks for the help.
