### ISSUE TITLE
Cannot select empty tag for deletion

### ISSUE THREAD

**Issue by juwiefer-btc** [influxdata/influxdb#24106]
__Steps to reproduce:__

```
yesterday="$(date --rfc-3339 ns -d yesterday | sed "s/ /T/")"
tomorrow="$(date --rfc-3339 ns -d tomorrow | sed "s/ /T/")"

function influx () {
    docker exec influxdb2 influx "$@"
}


docker run -d -p 8086:8086 --name influxdb2 influxdb:2.6.1
sleep 3   # wait for container to be ready...
influx setup \
      --username admin \
      --password dummypassword123 \
      --org ORG \
      --bucket bucket1 \
      --force

# two data points, one with tag2 empty.
influx write --bucket bucket1 --precision s 'measurement1,tag1=val,tag2=xxx  field1=1'
influx write --bucket bucket1 --precision s 'measurement1,tag1=val           field1=2'

influx query -r --org ORG 'from(bucket: "bucket1") |> range(start: -10y) |> group(columns: ["tag1"])'
influx query -r --org ORG 'from(bucket: "bucket1") |> range(start: -10y) |> filter(fn: (r) => r.tag2 == "") |> group(columns: ["tag1"])'
# result: two data points


# want to delete the series with tag2 being absent/empty.
influx delete --bucket bucket1 --start $yesterday --stop $tomorrow --predicate 'tag2=""'
sleep 1
influx query -r --org ORG 'from(bucket: "bucket1") |> range(start: -10y) |> group(columns: ["tag1"])'
```

__Expected behavior:__

I would have expected `influx delete ... --predicate 'tag2=""'` to delete time series data with absent or empty `tag2`, similar to `delete` in InfluxDB 1.x / InfluxQL. Alternatively, I would expect to specify a corresponding predicate with another syntax.

__Actual behavior:__
No data point is deleted.

__Environment info:__

Docker image influxdb:2.6.1

__Config:__

None

**Comment by juwiefer-btc** [comment]
Additionally. --stop is inclusive, which comes as a surprise...

**Comment by jeffreyssmith2nd** [comment]
`delete` only supports deleting in the positive (by `==` not `!=` and only for values that exist). As a workaround, you could use flux to filter the values you want to keep into a new bucket, delete the old bucket and then rename the new bucket.

**Comment by juwiefer-btc** [comment]
So there is no requirement that I can delete a specific time series without rewriting some other time series. That's somewhat surprising. But if so, this issue can be closed.
--
Thanks a lot for such a great product!
