### ISSUE TITLE
Document page doesn't show text in dark mode

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/influxdb#24113]
There is a styling issue on the document site when the page is in dark mode for OSS 2.6 DBRP page

https://user-images.githubusercontent.com/14298407/222003692-b1f4a5a1-1eba-4751-a78e-d0147f258332.mov

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Go to the page https://docs.influxdata.com/influxdb/v2.6/query-data/influxql/dbrp/#list-dbrp-mappings
2. Turn on dark mode 

__Expected behavior:__
Can see text on the page

__Actual behavior:__
Cannot see most of the text on the page because of the dark background color

**Comment by sanderson** [comment]
This was a bug in one of the helper methods we use in the docs source code. I just pushed a fix. You may need a hard refresh to flush the cache and load the updated page.
