### ISSUE TITLE
After influx restore 500 Internal Server Error: durable queue not found for replication ID 

### ISSUE THREAD

**Issue by EBS2324** [influxdata/influxdb#24120]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. In an influxdb with a remote an a replication do a full backup
influx backup \
--compression gzip  \
--org wsha \
-t  <token> \
<backup_directory> 
2. Restore the information
influx restore \
<backup_directory>  \
--full \
-t    <token>
3.  List the replication
influx replication list -t <token>
4.  An erro it is display
Error: failed to get replication streams: 500 Internal Server Error: durable queue not found for replication ID "0ad465db9bb23000"
__Expected behavior:__
The replication must be display

__Actual behavior:__
Whe you do a nflux replication list there are an error
Error: failed to get replication streams: 500 Internal Server Error: durable queue not found for replication ID "0ad465db9bb23000"

__Environment info:__
1. influx in docker

2. uname -srm
Linux 3.10.0-1160.el7.x86_64 x86_64

3. influx version
Influx CLI 2.6.1 (git: 61c5b4d) build_date: 2022-12-29T15:41:09Z

__Config:__

#Disable the HTTP /metrics endpoint which exposes internal InfluxDB metrics.
metrics-disabled: true
#Disable the InfluxDB user interface (UI). The UI is enabled by default.
ui-disabled: true
#Path to the BoltDB database. InfluxDB uses BoltDB to store data including organization and user information,
#UI data, REST resources, and other key value data.
bolt-path: /var/lib/influxdb2/influxd.bolt
#Path to persistent storage engine files where InfluxDB stores all Time-Structure Merge Tree (TSM) data on disk.
engine-path: /var/lib/influxdb2/engine
#Path to the SQLite database file. The SQLite database is used to store metadata for notebooks and annotations.
sqlite-path: /var/lib/influxdb2/influxd.sqlite

**Comment by EBS2324** [comment]
Also there are an error in the replication delete
influx replication delete  --id 0ad465db9bb23000 -t <token>

**Comment by jeffreyssmith2nd** [comment]
Hey @EBS2324, there's a PR that should address this issue. In the meantime, you can edit the sqlite table and remove the replication, then recreate it.
