### ISSUE TITLE
 Search all InfluxData sources Curl add data to influxdb says {“error”:”unable to parse invalid field format”}

### ISSUE THREAD

**Issue by samkhamk** [influxdata/influxdb#24153]
Hello Team,

I am trying to add data with below curl command but it gives error

echo -e “usage,host=influxdb,cluster=louis,pl_instance_name=2i-retegas,gitlabusage=“Thu Oct 20 13:48:02 2022”,jenkinsusage=“Fri Jan 20 06:52:05 2023”,sonarqubeusage=“Mon Oct 17 11:52:20 2022”,nexususage=“Not Use 00 00:00:00 0000” lastused=averagetime” | curl -X POST --data-binary @- https://influxdb-.com/write?db=usage

error
{“error”:“unable to parse ‘usage,host=influxdb,cluster=louis,pl_instance_name=2i-retegas,gitlabusage=Thu Oct 20 13:48:02 2022,jenkinsusage=Fri Jan 20 06:52:05 2023,sonarqubeusage=Mon Oct 17 11:52:20 2022,nexususage=Not Use 00 00:00:00 0000 lastused=averagetime’: invalid field format”}

can you please guide what I am missing here I tried to escape space with \ but no luck

Regards,
SAM

**Comment by jeffreyssmith2nd** [comment]
I believe you need to escape every space in each of the tag values. The following LP inserts fine for me:
```
usage,host="influxdb",cluster="louis",pl_instance_name="2i-retegas",gitlabusage="Thu\ Oct\ 20\ 13:48:02\ 2022",jenkinsusage="Fri\ Jan\ 20\ 06:52:05\ 2023",sonarqubeusage="Mon\ Oct\ 17\ 11:52:20\ 2022",nexususage="Not\ Use\ 00\ 00:00:00\ 0000" lastused="averagetime"
```

**Comment by samkhamk** [comment]
Thank you @jeffreyssmith2nd  I have corrected it,
