### ISSUE TITLE
InfluxDB autogen creating MANIFEST files that are world-writeable

### ISSUE THREAD

**Issue by IPvFletch** [influxdata/influxdb#24162]
InfluxDB is ignoring UMASK settings for the system/users.
We are seeing MANIFEST files like this appear on the filesystem:
```-rw-rw-rw-. 1 influxdb influxdb 442 Mar 29 04:08 /data/influxdb/engine/data/65fccd707293dca4/autogen/579/index/3/MANIFEST```
It appears this is the Go cmd which writes the file (as a Tempfile): https://github.com/influxdata/influxdb/blob/903d30d65894cd282eae91c4026e39fe57a7b538/tsdb/index/tsi1/partition.go#L1454
Is there no way to set permissions here?
I know Go also has a Chmod cmd which could be exec'd after this write.
Otherwise it would be ideal if it did not set world-writeable, or honored a configurable UMASK.
Thanks!

**Comment by cryptoball7** [comment]
It looks like the file mode is set here:

https://github.com/influxdata/influxdb/blob/903d30d65894cd282eae91c4026e39fe57a7b538/tsdb/index/tsi1/partition.go#L1469

**Comment by IPvFletch** [comment]
Is it possible for this to be configurable? Doesn't seem like optimal permissions for all use cases.

**Comment by jeffreyssmith2nd** [comment]
Thanks @IPvFletch and @cryptoball7 for the investigation into this. I agree that I don't believe there is a strong reason to change the permissions on this file so I've added a PR to remove that.
