### ISSUE TITLE
influxdb2-client rpm (Version 2.7.1) obsoletes influxdb 1.8.0

### ISSUE THREAD

**Issue by lukasertl** [influxdata/influxdb#24185]
We have influxdb 1.8.0 installed (and no influxdb2 packages), and when running "yum upgrade" we are informed that the influxdb2-client will be installed, which obsoletes influxdb 1.8.0.

Is this intended?

**Comment by jeffreyssmith2nd** [comment]
This is not intended, thanks for the report. We will look into this.

**Comment by sweharris** [comment]
Also spotted here.  Fortunately the package was signed with a different key so it failed to install!

**Comment by jeffreyssmith2nd** [comment]
This should be resolved now. You may need to do a `yum clean metadata` if it is still showing. This will remove the cached metadata for the package. Please comment/reopen if you are still having issues.
