### ISSUE TITLE
Slow queries

### ISSUE THREAD

**Issue by Sergio9777** [influxdata/influxdb#24213]
Hello guys,
I would like to know if there are configurations or strategies to improve the time that spends some querys. For example, im executing this easy query:

from(bucket: "bucket1")
  |> range(start: -10h)
  |> filter(fn: (r) => r["alias"] == "filter")
  |> aggregateWindow(every: 5m, fn: sum, createEmpty: false)
  |> yield(name: "sum")

But the time that it needs is about 6s. It seems too much time for 5MB of data. For this reason im interested in something that allow me spend less time executing the query. It's possible that I need use InfluxQL or add some configuration at the file configuration ( my file configuration has the default values)  or whatever, i dont know .

**Comment by Jayclifford345** [comment]
We discussed this within the community @Sergio9777 did any of the methods advised help?

**Comment by Sergio9777** [comment]
Ooh, right!
Using InfluxQL, the time improve a lot.
Thank you!
