### ISSUE TITLE
InfluxDB's New Data Explorer Does not generate Flux code in 2.7 

### ISSUE THREAD

**Issue by Jayclifford345** [influxdata/influxdb#24215]
The new data explorer in InfluxDB 2.7 currently does not generate flux like its cloud counterpart. This has been alerted to by two of our community members:
https://influxcommunity.slack.com/archives/CH8RV8PK5/p1682416539481229
https://influxcommunity.slack.com/archives/CH8RV8PK5/p1682418278552259

<img width="1786" alt="Screenshot 2023-04-25 at 11 45 06" src="https://user-images.githubusercontent.com/45856600/234253964-896eaae4-a48e-474e-8148-d2c8728a681b.png">

It appears the toggle generate flux code also appears to be missing.

**Comment by jeffreyssmith2nd** [comment]
This has been reverted in 2.7.1, it was not intended to ship with 2.7.0.

**Comment by DaveSprague** [comment]
I believe I'm seeing the same issue (missing toggle and flux code not being generated) in the latest version of the influxdb UI.

Version 2.7.8

If I revert back to the old version of data explorer it works as expected.
