### ISSUE TITLE
scientific notation query

### ISSUE THREAD

**Issue by i-xiaobao** [influxdata/influxdb#24258]
__Steps to reproduce:__
I have a scientific notation query: 
`select time,value from "table" where value != 4.9e-324`

__Expected behavior:__
Hope to filter some data that is not equal to 4.9e-324

__Actual behavior:__
error parsing query: found E, expected ; at line 1, char 67

__Environment info:__
* InfluxDB version: 1.8

**Comment by sanderson** [comment]
@i-xiaobao InfluxQL does not currently support exponents, i.e. scientific notation: https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#floats
