### ISSUE TITLE
cannot switch to new data explorer (script editor)

### ISSUE THREAD

**Issue by szmcdull** [influxdata/influxdb#24300]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. open web console and click "Data Explorer"

__Expected behavior:__
"Switch to old Data Explorer" is shown and can switch between old and new Data Explorer

__Actual behavior:__
"Switch to old Data Explorer" is not shown

__Environment info:__

* System info: Linux 3.10.0-1160.53.1.el7.x86_64 x86_64
* InfluxDB version: InfluxDB v2.7.1 (git: 407fa622e9) build_date: 2023-04-28T13:24:27Z
* Other relevant environment details: none

![image](https://github.com/influxdata/influxdb/assets/2098590/9a953147-7a2c-431d-aaf8-6f0d1097dedd)

**Comment by jeffreyssmith2nd** [comment]
This is expected behavior. The new data explorer UI remains a Cloud 2 only feature at this time.
