### ISSUE TITLE
mqtt.publish and mqtt.to are broken

### ISSUE THREAD

**Issue by anon8675309** [influxdata/influxdb#24329]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Log into InfluxDB 2.x web UI, go to Tasks and run the following example

```
import "experimental/mqtt"

mqtt.publish(
    broker: "tcp://localhost:8883",
    topic: "alerts",
    message: "wake up",
    clientid: "alert-watcher",
    retain: true,
)
```

Feel free to change the port and use a different host. `tcpdump` can be used to quickly verify no packets are being sent to the destination port. This allows other to reproduce the error without having to set up an MQTT broker.

Note: This example is taken directly from [the documentation on mqtt.publish](https://docs.influxdata.com/flux/v0.x/stdlib/experimental/mqtt/publish/#send-a-message-to-an-mqtt-endpoint).

It's also worth noting that people have reported problems with getting data from InfluxDB to MQTT on the Influx Community site since at least 2020.

1. https://community.influxdata.com/t/mqtt-producer-influxdb-to-mqtt/12674 
3. https://community.influxdata.com/t/error-with-mqtt-to-and-mqtt-publish/25353
4. https://community.influxdata.com/t/how-to-use-the-mqtt-publish-task/30268

__Expected behavior:__
A TCP connection should be attempted to be made to the MQTT broker, then it should publish the message.

If an error occurs, the error messages indicate what went wrong and tries to point the user to how to fix it.

This feature was originally implemented in 2019 and announced in this [blog post](https://www.influxdata.com/blog/how-to-output-data-from-flux-to-mqtt-natively/) with a copy posted on the [community forum](https://community.influxdata.com/t/how-to-output-data-from-flux-to-mqtt-natively/10911).  I expected it to function as described there and in the doumentation for [publish()](https://docs.influxdata.com/flux/v0.x/stdlib/experimental/mqtt/publish/) and [to](https://docs.influxdata.com/flux/v0.x/stdlib/experimental/mqtt/to/).

__Actual behavior:__
No TCP connection is attempted to be made to the MQTT broker. No useful error message is provided.

When using mqtt.publish, the query fails with this error:

> error exhausting result iterator: error calling function “publish” @5:1-13:2: Dialer.Dial called on an error dependency

When using mqtt.to, the query claims that it succeeded, but does not actually attempt to reach out to

__Environment info:__

* System info: Linux 5.10.0-21-amd64 x86_64
* InfluxDB version: InfluxDB v2.7.1 (git: 407fa622e9) build_date: 2023-04-28T13:24:27Z
* Other relevant environment details: n/a

According to the documentation, this API has been supported since InfluxDB 1.7.

__Config:__
Configuration is the default.

**Comment by ajohnson1117** [comment]
Has this been acknowledged by Influx? I'm having problems with mqtt.publish and mqtt.to

**Comment by davidby-influx** [comment]
This feature only works in Cloud, not in OSS.  A documentation update request has been filed.
