### ISSUE TITLE
no matching manifest for linux/arm/v8 in the manifest list entries (Raspbian Bullseye Pi4)

### ISSUE THREAD

**Issue by dukeofnukem815** [influxdata/influxdb#24330]
`docker pull influxdb:latest`
`latest: Pulling from library/influxdb`
`no matching manifest for linux/arm/v8 in the manifest list entries`

Huh - last time I checked I was running 64bit raspian on my Pi 4:
`uname -a`
`Linux fluxcompensator 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`

`docker manifest inspect influxdb`
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2415,
         "digest": "sha256:1838836254a474d10f8400e15c562ca5f832c1073270a7cf79fd7454d9ebc014",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2415,
         "digest": "sha256:a7ce35b71b89218687209d08387415c6fd46fcab2cf2e88d3565bb743b15f0d7",
         "platform": {
            "architecture": "**arm64**",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}
`

checking the dockerfile... ah: `RUN case "$(dpkg --print-architecture)" in \`

So let's go there:

`dpkg --print-architecture`
`armhf`

erm... according to [this](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/) that would be 32bit Pi 2 stuff?!?

I can't get my head around the naming conventions - is raspian messing up with dpkg returning armhf or docker by mapping aarch64 to arm instead of arm64 or am I missing something?

How do I "correctly" pull influxdb:latest?

**Comment by dukeofnukem815** [comment]
I may have to check whether I actually am running on 64bit - shame on me

**Comment by Paraphraser** [comment]
Perhaps try running:

```
$ lscpu
```

If you see "CPU op-mode(s): *32-bit, 64-bit" then your Pi is full 64-bit.

If you **don't** see that string, then run:

```
$ uname -m
```

If the result is "aarch64" then your system is running mixed 32-bit user mode with a 64-bit kernel. If not, your system is full 32-bit.

Basically, if you go to [raspberrypi.com](https://www.raspberrypi.com/software/operating-systems/) and select one of the images in the "Raspberry Pi OS" grouping, that starts out as full 32-bit but you can change `/boot/config.txt` to fire up the 64-bit kernel and run in mixed mode. If, instead, you select one of the images in the "Raspberry Pi OS (64-bit)" grouping, it's full 64-bit out-of-the-box.

Another thing you *might* want to consider is whether you want to pull InfluxDB 2.x or 1.8? By pulling "influxdb:latest" you're getting 2.x and that only runs on full 64-bit. If you pull "influxdb:1.8" then you get an older version of InfluxDB that runs on all the full 32-bit, mixed mode and full 64-bit permutations.

Hope this helps.

**Comment by piotrek2555** [comment]
root@raspberrypi:/home/pi/docker/influxdb2# docker run --rm alpine uname -m
aarch64
root@raspberrypi:/home/pi/docker/influxdb2#  lscpu
Architecture:            aarch64
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Cortex-A72
    Model:               3
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r0p3
    CPU(s) scaling MHz:  100%
    CPU max MHz:         1800,0000
    CPU min MHz:         600,0000
    BogoMIPS:            108,00
    Flags:               fp asimd evtstrm crc32 cpuid
Caches (sum of all):     
  L1d:                   128 KiB (4 instances)
  L1i:                   192 KiB (4 instances)
  L2:                    1 MiB (1 instance)
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Vulnerable
  Srbds:                 Not affected
  Tsx async abort:       Not affected
