### ISSUE TITLE
InfluxDB OSS v2.70 unresponsive, eventually crashing with OOM.

### ISSUE THREAD

**Issue by johnhoughton-v** [influxdata/influxdb#24406]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.
 
* Normal production loads for 3-10 days.
* No apparent changes in query behaviors
* No deletions being performed
* We are unaware of what triggers the event. 

__Expected behaviour:__
InfluxDB should accept and process data without stopping.

__Actual behaviour:__
We have recently experienced approximately weekly cases that, if left unaddressed, result in an "Out of Memory" error. Restarting the Linux service restores the database. 

During the preceding hour or two, the health check endpoint responds "OK," but queries and inserts are rejected. The api/write and /query endpoints return HTTP errors during an episode (through an nginx proxy, we see a 499). 

The primary symptoms we observe forensically are:
* The compaction processes stop logging, 
* There are shard write requests time outputs, 
* WAL failed write attempts.
* The application memory gradually consumes all the available instance memory. 
* Finally, InfluxDB reports an OOM error.

During one of these episodes, the  "influx ping" responds with "OK" so we can't proactively restart the InfluxDB server.

__Environment info:__

* System info: Linux 4.14.301-224.520.amzn2.x86_64 x86_64
* InfluxDB version: InfluxDB v2.7.0 (git: 85f725f8b9) build_date: 2023-04-05T15:32:25Z

Other relevant environment details:

### database cardinality 

about 80 million as determined by "influxd inspect report-db"

### lscpu

    Architecture:        x86_64
    CPU op-mode(s):      32-bit, 64-bit
    Byte Order:          Little Endian
    CPU(s):              4
    On-line CPU(s) list: 0-3
    Thread(s) per core:  2
    Core(s) per socket:  2
    Socket(s):           1
    NUMA node(s):        1
    Vendor ID:           GenuineIntel
    CPU family:          6
    Model:               106
    Model name:          Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
    Stepping:            6
    CPU MHz:             3505.131
    BogoMIPS:            5799.90
    Hypervisor vendor:   KVM
    Virtualization type: full
    L1d cache:           48K
    L1i cache:           32K
    L2 cache:            1280K
    L3 cache:            55296K
    NUMA node0 CPU(s):   0-3
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear flush_l1d arch_capabilities

### free
                   total        used        free      shared  buff/cache   available
     Mem:       32406932     2975796     1646572         484    27784564    28967912
     Swap:             0           0           0

### lsblk
     NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
     nvme0n1       259:0    0   10G  0 disk
     ├─nvme0n1p1   259:1    0   10G  0 part /
     └─nvme0n1p128 259:2    0    1M  0 part
     nvme1n1       259:3    0  250G  0 disk /data  <<<--- dedicated InfluxDB volumes, range from 250GB-2TB, depending on env

### influx bucket list (redacted slightly)

    ID			Name		Retention	Shard group duration	Organization ID		Schema Type
     f3cdd07deec373bd	_monitoring	168h0m0s	24h0m0s			9af610aaa0f3ae3b	implicit
     d0fad729d2d23daa	_tasks		72h0m0s		24h0m0s			9af610aaa0f3ae3b	implicit
     e1565b5a660ee455	metrics		infinite	168h0m0s		9af610aaa0f3ae3b	implicit

__Config:__
### influx server-config

    {
        "assets-path": "",
        "bolt-path": "/data/influxdbv2/boltdb/bolt",
        "e2e-testing": false,
        "engine-path": "/data/influxdbv2/engine",
        "feature-flags": null,
        "flux-log-enabled": false,
        "hardening-enabled": false,
        "http-bind-address": ":18086",
        "http-idle-timeout": 180000000000,
        "http-read-header-timeout": 10000000000,
        "http-read-timeout": 0,
        "http-write-timeout": 0,
        "influxql-max-select-buckets": 0,
        "influxql-max-select-point": 0,
        "influxql-max-select-series": 0,
        "instance-id": "",
        "log-level": "info",
        "metrics-disabled": false,
        "nats-max-payload-bytes": 0,
        "nats-port": 0,
        "no-tasks": false,
        "pprof-disabled": false,
        "query-concurrency": 1024,
        "query-initial-memory-bytes": 0,
        "query-max-memory-bytes": 0,
        "query-memory-bytes": 0,
        "query-queue-size": 1024,
        "reporting-disabled": false,
        "secret-store": "bolt",
        "session-length": 60,
        "session-renew-disabled": false,
        "sqlite-path": "/data/influxdbv2/boltdb/influxd.sqlite",
        "storage-cache-max-memory-size": 1073741824,
        "storage-cache-snapshot-memory-size": 26214400,
        "storage-cache-snapshot-write-cold-duration": "10m0s",
        "storage-compact-full-write-cold-duration": "4h0m0s",
        "storage-compact-throughput-burst": 50331648,
        "storage-max-concurrent-compactions": 0,
        "storage-max-index-log-file-size": 1048576,
        "storage-no-validate-field-size": false,
        "storage-retention-check-interval": "30m0s",
        "storage-series-file-max-concurrent-snapshot-compactions": 0,
        "storage-series-id-set-cache-size": 0,
        "storage-shard-precreator-advance-period": "30m0s",
        "storage-shard-precreator-check-interval": "10m0s",
        "storage-tsm-use-madv-willneed": false,
        "storage-validate-keys": false,
        "storage-wal-fsync-delay": "0s",
        "storage-wal-max-concurrent-writes": 0,
        "storage-wal-max-write-delay": 600000000000,
        "storage-write-timeout": 10000000000,
        "store": "disk",
        "testing-always-allow-setup": false,
        "tls-cert": "",
        "tls-key": "",
        "tls-min-version": "1.2",
        "tls-strict-ciphers": false,
        "tracing-type": "",
        "ui-disabled": false,
        "vault-addr": "",
        "vault-cacert": "",
        "vault-capath": "",
        "vault-client-cert": "",
        "vault-client-key": "",
        "vault-client-timeout": 0,
        "vault-max-retries": 0,
        "vault-skip-verify": false,
        "vault-tls-server-name": "",
        "vault-token": ""
    }

__Logs:__
No errors are listed in log when the event is triggered.  After an hour or two, when the available memory is consumed the following message is written, followed by various stacks. 
```
Aug 21 04:01:09 <redacted instance name> influxd-systemd-start.sh[3287]: fatal error: runtime: out of memory
```
__Attachments:__

Attaching a file that contains
* profiles and traces gathered at 10-minute intervals.
* Screenshot of Grafana dashboard the renders most of the metrics gathered from the /metrics endpoint
* the output of the ping and extended ping commands
* the output of iostats at the beginning of each 10-minute interval
* the shell script that was used to gather the data

[20231006 - InfluxDB profile and trace info 2.zip](https://github.com/influxdata/influxdb/files/12849040/20231006.-.InfluxDB.profile.and.trace.info.2.zip)

**_NOTE: the error captured in these files was triggered around 05:07 UTC on Oct 6._**

**Comment by johnhoughton-v** [comment]
Another episode involving another server. Restarting service restored functionality. Attaching more profile and trace info

[20231010 - InfluxDB profile and trace info.zip](https://github.com/influxdata/influxdb/files/12870652/20231010.-.InfluxDB.profile.and.trace.info.zip)

**_NOTE: the error captured in these files was triggered around 09:55 UTC on Oct 10._**

**Comment by davidby-influx** [comment]
@johnhoughton-v - Do you have logs for these incidents?  Logs, particularly at the `debug` level, would be very helpful.

Also, what format are your `...trace.out` files in? Linux is not helping me with those:
```
> file *.out
20231006-043001_iostat.out: ASCII text
20231006-043001_trace.out:  data
```

**Comment by davidby-influx** [comment]
20231006
[heap_450.pdf](https://github.com/influxdata/influxdb/files/12886196/heap_450.pdf)
[cpu_450.pdf](https://github.com/influxdata/influxdb/files/12886198/cpu_450.pdf)
[heap_500.pdf](https://github.com/influxdata/influxdb/files/12886239/heap_500.pdf)
[heap_510.pdf](https://github.com/influxdata/influxdb/files/12886286/heap_510.pdf)
[heap_520.pdf](https://github.com/influxdata/influxdb/files/12886444/heap_520.pdf)
[heap_530.pdf](https://github.com/influxdata/influxdb/files/12886455/heap_530.pdf)

**Comment by davidby-influx** [comment]
20231010

[heap_950.pdf](https://github.com/influxdata/influxdb/files/12887667/heap_950.pdf)
[heap_1000.pdf](https://github.com/influxdata/influxdb/files/12887669/heap_1000.pdf)
[heap_1010.pdf](https://github.com/influxdata/influxdb/files/12887671/heap_1010.pdf)
[heap_1020.pdf](https://github.com/influxdata/influxdb/files/12887676/heap_1020.pdf)

**Comment by davidby-influx** [comment]
@johnhoughton-v - you wrote above 

> No errors are listed in log when the event is triggered. After an hour or two, when the available memory is consumed the following message is written, followed by various stacks.

and

> - There are shard write requests time outputs,
> - WAL failed write attempts.

We definitely would like to see the stack traces, those are golden for debugging, as well as all the logs leading up to the crash that contain the WAL write failures and shard write requests timeouts, etc.  Log level `debug` would be the most informative if you can generate those for the next incident.  `info` level logs for the two incidents recorded here will be better than nothing, though, especially with the stack traces in them.

I am seeing the big memory usage being series creation at the beginning of both incidents, followed by what may be the triggering incident, a roughly 0.5 GB read of points from a write.  This is the `io.ReadAll` call consuming about 23% of the memory in use in the two final profiles.

Once I have those logs and stack traces, we can see if it is the `ReadAll` running out of memory, which would indicate that you are writing in too large  a batch for your RAM, or if it is the series creation and validation operations from your very high cardinality which is causing the problem (i.e., if the `io.ReadAll` is not on the stack in the crash because it succeeded, despite its transient high memory usage), or if it is some other problem not obvious from the information you have provided so far.

In any event, I look forward to further communication from you.  Thanks.

**Comment by davidby-influx** [comment]
FYI: @Jayclifford345

**Comment by johnhoughton-v** [comment]
Thank you for your response, @davidby-influx.  (+ @Jayclifford345 ) 

I'm not positive that you haven't already answered some of your own questions, so please excuse any redundancy here.

> Do you have logs for these incidents? Logs, particularly at the debug level, would be very helpful.

This incident occurs on production systems. I'm concerned enabling debugging would likely overwhelm the system, so it would be a tough "sell" internally. Let me know if that information is critical, and I'll work to make that happen.  

> Also, what format are your ...trace.out files in?

Expecting that there may be related questions, I'll point you to the script, influx_diag.sh, that I included with the first zip file: **20231006 - InfluxDB profile and trace info 2.zip** I provided that script, based on various forum posts, is an attempt to I collected the necessary diagnostic information and to show how it was collected.

iostat: 

    iostat -xdy 1 30 >  "$folder/$now"_iostat.out

influx_ping.txt, influx_ping_http_debug.txt:

    influx ping --http-debug

trace.out

    curl --show-error --silent "http://localhost:18086/debug/pprof/trace" --output "$folder/$now"_trace.out

profile.tar.gz

    curl --show-error --silent "http://localhost:18086/debug/pprof/all?cpu=30s" --output "$folder/$now2"_profiles.tar.gz

ref: https://docs.influxdata.com/influxdb/v2/reference/internals/runtime/

I'm a Mac user, and below is the way I was able to read the traces and profile that were generated:

    # ref https://pkg.go.dev/net/http/pprof
     
    # to view trace on mac
    brew install graphviz
    brew install go
 
     # run the trace tool to view data - it launches a GUI the trace
    cd $HOME/Downloads/influxdb_diag_1545
    go tool trace *trace.out
     
    # to view the profile output, you need to uncompress the *profiles.tar.gz file and cd into the resulting folder
    # when you run the pprof tool, it will launch your browser to localhost:9000 and show the graph of the profile data
    cd $HOME/Downloads/influxdb_diag_1545/profiles 
    go tool pprof -http=localhost:9000 cpu.pb.gz
    go tool pprof -http=localhost:9000 mutex.pb.gz

As a kindness, fewer spaces in your filename will make my command-line tools easier to operate.

Ooops, my bad. I thought I had cleaned those up better.

> Once I have those logs and stack traces...

Would you confirm that what I've provided is insufficient now? If so, what do you want to see. The conversational latency is not our friend.

The only time I've seen go process stack has been when we let the machine run to failure and trigger the OOM. That takes a few hours and as mentioned elsewhere, the system is unresponsive during that time. As a production system, we prefer to recover the functionality as quickly as possible.

That is why I collected the profiles and traces every 10 minutes so you could see the process before, during (sorta), and after the event. I've tried to say when the episode commenced in each of my postings of zip files.

> This is the io.ReadAll call consuming about 23% of the memory in use in the two final profiles.

I can easily adjust the system, e.g., slow down the write batches, increase the instance size, etc. But I see no excessive memory use during these episodes. (See dashboard screenshot) Indeed, earlier, we increased batch sizes to address our throughput needs, but we could tweak those as well. But these symptoms are new, and I've attempted to leave the system alone to assist in the diagnostic process.

Symptomatically, I notice that the file compressors just...stop. This is visible in the dashboard screenshot I provided. Then WAL and shard writes throw errors, and...  Possibly related to cardinality? Sure, but I'm not connecting those dots just yet.

If you would like to interact in real-time, please PM me, and I'll be glad to discuss and provide ANY information you need.

**Comment by davidby-influx** [comment]
@johnhoughton-v - What I need to see are the logs preceding the incident and the stack traces that are written therein. You mention WAL errors, and stack traces appearing in the logs. That period in the logs is where the clues I need are most likely to be found.

If you can't or don't want to run to failure on a production system the logs from the two incidents for which you have provided profiles will still be helpful.   They may contain enough information. If you have purged those logs, we will probably have to wait for the next incident, and send me the logs preceding that particularly any stack traces, though I also want the logs from when you first see problems and memory growth. 

 The profiles were helpful, and as you can see, I posted visualizations of the heap profiles. I will be looking more at the CPU profiles today. 

Compaction stops because the system is having trouble. InfluxDB prioritizes ingest first and compaction second: it is more important to not drop incoming data than it is to save disk space. 

A stack trace in the logs looks something like this:
```
influxd fatal error: runtime: out of memory 
influxd runtime stack: 
influxd runtime.throw(0x186b21b, 0x16) 
influxd 	/usr/local/go/src/runtime/panic.go:774 +0x72 
influxd runtime.sysMap(0xdc14000000, 0x4000000, 0x3835878) 
influxd 	/usr/local/go/src/runtime/mem_linux.go:169 +0xc5 
influxd runtime.(*mheap).sysAlloc(0x381c820, 0x5a000, 0x1071977, 0x1d8008b4767) 
influxd 	/usr/local/go/src/runtime/malloc.go:701 +0x1cd 
influxd runtime.(*mheap).grow(0x381c820, 0x2d, 0xffffffff) 
influxd 	/usr/local/go/src/runtime/mheap.go:1255 +0xa3 
influxd runtime.(*mheap).allocSpanLocked(0x381c820, 0x2d, 0x3835888, 0x0) 
influxd 	/usr/local/go/src/runtime/mheap.go:1170 +0x266 
influxd runtime.(*mheap).alloc_m(0x381c820, 0x2d, 0x7f06fc600100, 0x7f074dc2c2e0) 
influxd 	/usr/local/go/src/runtime/mheap.go:1022 +0xc2 
influxd runtime.(*mheap).alloc.func1() 
influxd 	/usr/local/go/src/runtime/mheap.go:1093 +0x4c 
influxd runtime.(*mheap).alloc(0x381c820, 0x2d, 0xc000010100, 0x7f06fc6013c0) 
influxd 	/usr/local/go/src/runtime/mheap.go:1092 +0x8a 
influxd runtime.largeAlloc(0x59fd0, 0x450001, 0x7f06fc6013c0) 
influxd 	/usr/local/go/src/runtime/malloc.go:1138 +0x97 
influxd runtime.mallocgc.func1() 
influxd 	/usr/local/go/src/runtime/malloc.go:1033 +0x46 
influxd runtime.systemstack(0x0) 
influxd 	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66 
influxd runtime.mstart() 
influxd 	/usr/local/go/src/runtime/proc.go:1146 
influxd goroutine 947965186 [running]: 
influxd runtime.systemstack_switch() 
influxd 	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xd13e6ba750 sp=0xd13e6ba748 pc=0x45d2d0 
influxd runtime.mallocgc(0x59fd0, 0x16e9f00, 0x40c201, 0xca876bdb40) 
influxd 	/usr/local/go/src/runtime/malloc.go:1032 +0x895 fp=0xd13e6ba7f0 sp=0xd13e6ba750 pc=0x40c7a5 
influxd runtime.newarray(0x16e9f00, 0x449, 0xc3dd5022ff) 
influxd 	/usr/local/go/src/runtime/malloc.go:1173 +0x63 fp=0xd13e6ba820 sp=0xd13e6ba7f0 pc=0x40cbe3 
influxd runtime.makeBucketArray(0x15a1860, 0xc00054e00a, 0x0, 0x0, 0x13a) 
influxd 	/usr/local/go/src/runtime/map.go:362 +0x183 fp=0xd13e6ba858 sp=0xd13e6ba820 pc=0x40dad3 
influxd runtime.hashGrow(0x15a1860, 0xc4b0098e70) 
influxd 	/usr/local/go/src/runtime/map.go:1033 +0x89 fp=0xd13e6ba8a8 sp=0xd13e6ba858 pc=0x40f749 
influxd runtime.mapassign_faststr(0x15a1860, 0xc4b0098e70, 0xca88b6c500, 0x13a, 0xca88b6c500) 
influxd 	/usr/local/go/src/runtime/map_faststr.go:272 +0x122 fp=0xd13e6ba910 sp=0xd13e6ba8a8 pc=0x413182 
influxd github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).WritePointsWithContext(0xc2feb05b80, 0x2794980, 0xc0000ee130, 0xc016b5a000, 0x444, 0x444, 0x0, 0x0) 
```

**Comment by johnhoughton-v** [comment]
@davidby-influx - Thanks for explaining the compaction - makes sense. I'll stop "noticing" that.

The two episodes I posted in the previous files, Oct 8 and 10, represent instances where we identified that the system was unresponsive and restarted the InfluxDB service quickly. As a result, it never got to an OOM condition that dumped the stacks. From the profiles and traces provided, I hoped you could reconstitute those. (I'm no go expert...)

BUT, we DID had two OTHER occurrences, on Aug 7 and Aug 21, where we did get to the OOM. From those, I picked out the stack traces. The Aug 21 one contains more thread information than the Aug 7.  Please see attached.

Since InfluxDB writes to the journal, I can reconstitute the logs. But as a result, they are essentially, the entire system's logs. I can't redact those such that we would be comfortable sending them in a public forum without mangling them to the point they were not diagnostically useful. Let me know if you want to see them on a web conference. Or, perhaps you can provide a secure way to transfer them.

[20231013-crash-stacks.zip](https://github.com/influxdata/influxdb/files/12900275/20231013-crash-stacks.zip)

**Comment by davidby-influx** [comment]
@johnhoughton-v - Thank you for the crash stacks. Here are a few points about them:
Both failures to allocate were in the data structure that InfluxDB uses to maintain the Series IDs (a [roaring bitmap](https://roaringbitmap.org/)).  Apologies if you already familiar with this: a series is a set of points within a measurement that all have the same tag set, but different time stamps.  They are a key part of how `WHERE` clauses efficiently search.

In the example below, the tags are `color`, `name`, and `surface`, while the fields are `temperature` and `pressure`.  The Series ID is not actually represented in the data; I have merely prepended it for explanatory purposes here.
|series|color|name|surface|temperature|pressure|time|
|---|---|---|---|---|---| ---|
|1 |green|fred|rough|32.5|54|1|
|1 |green|fred|rough|33.2|52|2|
|1 |green|fred|rough|34.0|51|3|
|2|green|julie|rough|33.9|52|4|
|2|green|julie|rough|33.1|52|5|
|3|green|julie|smooth|33.4|52|6|
|4|red|julie|smooth|33.0|52|7|

Series 1 is all data points with tags `green, fred, rough`
Series 2 is all data points with tags `green, julie, rough`
Series 3 is all data points with tags  `green, julie, smooth`
Series 4 is all data points with tags  `red, julie, smooth`

Your database is dying in `tsdb.(*SeriesIDSet).Merge` which is in turn called when opening a shard and counting the series in that shard.

My assessment is the same as @Jayclifford345's; your cardinality is too high for the equipment you are running on.  There are many ways to reduce cardinality in shards: the best is to rework your schema if possible (changing tags into fields to prevent cardinality explosion when values differ), etc.  

The first thing I always look for is tags that shouldn't be tags; are you storing unique-ish things like timestamps or UUIDs as tags? Their uniqueness will explode cardinality counts. Do you have tags that are floating point numbers? Do you have tags you are not using in `WHERE` clauses, and don't need to index by? 

Tags are designed to be small sets of values with which you want to preferentially query or divide your data. They are more expensive than fields, as they are indexed for efficient querying, and it is this indexing which is running out of memory for you.

A last option is to switch from the OSS product to our paid offerings (on-premise or in the cloud). They have much more capability to scale up for these sorts of workloads, and they pay my dental bills, as well.  Two huge advantages, in my mind.  

Often, but not always, the tricks above will let the OSS product work for you, though (by which statement you can tell I am in Engineering, not Sales).  Here's a handy guide to reducing cardinality:
https://docs.influxdata.com/influxdb/v2/write-data/best-practices/resolve-high-cardinality/#Copyright

Let us know how you get on, and I'm happy to answer more questions on schema design and suchlike if the documentation isn't clear or complete enough. 

Regards, 
David

**Comment by johnhoughton-v** [comment]
**Thank you** @davidby-influx for your reply that ties the stack details directly to cardinality. That information will give me some leverage and assist in my addressing the issue.

Your analysis indicates shard-level cardinality, but the tools we users have available show overall cardinality. As I craft a plan to address this issue, I need additional information to fill in some gaps in my understand that I've not been able to divine from the published information or the communities I've found.

**Given:**

1. To simplify the question domain, assume a single-bucket implementation with an unlimited retention policy. 
2. The default shard interval for unlimited RP: 1 week.
3.  I shall refer to the current week as  W1, and the week that is one year old as W52
4. A daily run of the command "influxd inspect report-db --detailed ..."  gathers the measurement and tag cardinalities. This is rendered on a dashboard at the bucket and measurement level. (we know high-cardinalities measurements)
5. influxd inspect report-db shows cardinality at the "overall" level. It does not show data the shard level.
6. The error occurs when opening a shard that contains high-cardinality data.

**Questions:**

1. stop-gap: As a temporary stop-gap-fix, would increasing the memory on the instance by 2-8x be of any value? I've never seen any memory pressure, e.g., usage-user says below 25%, but can easily increase that resource.
2. stop-gap: Would reducing the shard duration from 1 week to 1 day impact the issue you observed? Queries tend to use the last 1-2 days.
3. shard-vs-overall cardinality: Is it sufficient to delete data from W51, or is it also necessary to delete data from W1?
4. shard-vs-overall cardinality: Is it sufficient to delete data from just the "currently active" shards, i.e., W1-10? Deleting active shard data would not lower the overall cardinality significantly. Or is it necessary to delete data from all weeks to significantly lower measurement cardinality?
5. deleting-vs-removing: In v2, using tsi1, does deleting points leave the shards in a "sparse" state? Are deleted points removed or marked for deletion? My understanding in v1 is that the latter was the case. (We are using v2.7.0).
7. deleting-vs-removing: Is it sufficient to delete the points from a measurement, or is it necessary for the shards be removed, i.e., by a retention policy? I understood in v1 that deleting was insufficient, but it seems to be sufficient in v2.
8. tooling: Is influxd inspect report-db a sufficient measure of cardinality?
9. tooling: verify that the following command would be sufficient for removing cardinality by deleting older points (variables allow me to walk back week-by-week, and pause in-between to allow the compaction time to run):

        influx delete --bucket "metrics" \
            --org "veevacrm" \
            --start ''$start'' \
            --stop ''$end'' \
            --predicate ''_measurement="$meas"''

+ @Jayclifford345

**Comment by davidby-influx** [comment]
@johnhoughton-v 

1. Increasing the memory might help, but I don't know how much is needed, merely that you don't have enough.  One other thing to check is the available file handles; running out of file handles appears as a memory issue to the Go runtime because of the way memory-mapping is implemented in Linux. This should be the first thing you check: how many files handles are available to InfluxDB?
2. Series index files are for whole databases; the failure is on opening a shard, but I believe the series index files opened contain information for the entire database (because series can span shards, so this reduces duplicate information).  Thus, I do not believe shortening shard lengths will affect the amount of memory required. I would have to dig deeper into the code to verify this for certain.
3. Deleting data shrinks the series index files only if the deletion entirely encompasses a series, i.e., leaving no points in that series in any shard. 
4. In other words, deleting data may or may not delete a series, depending on the existence of points in that series which exist outside of the deletion predicate's span.
5. Deleting writes tombstones to a shard, indicating that the data has been removed. When the shard is compacted, the data and the tombstones which refer to that data are removed.  However, the memory problem you are having is not in the TSM file where data and tombstones are stored; it is in the series index files, which are not tombstoned.  
6. As I read the code, deleting is sufficient _if you delete all the points in a series_.  
7. `influxd inspect report-db` has two modes; estimated and exact. I suspect running it in exact mode would fail on your system given your immense cardinality, as exact mode takes much more memory. 
8. hether that command is sufficient depends on whether all points in a series are within `start` and `end`

**Comment by johnhoughton-v** [comment]
@davidby-influx Thanks again for the quick response.  I have a LOT of homework to do!  I'll let you know if I have any other questions.

@Jayclifford345

**Comment by Jayclifford345** [comment]
Hi @johnhoughton-v, I am glad you managed to work through alot of this with @davidby-influx. If you are still struggling with the cardinality issue let me know and I can always arrange for you to talk to one of our AM and SE's about a clustered option. Though it is completely up to you which path you go the option is there :)

**Comment by johnhoughton-v** [comment]
@Jayclifford345, thanks for the assist on this one. We understand the issue and are crafting a plan to address is.  I've got some follow-up questions, more administrative in nature, that I'll follow up with you separately so as to maintain this ticket. 

This one can be closed.

**Comment by davidby-influx** [comment]
Closing per customer request
