### ISSUE TITLE
feature request for archiving retention policy

### ISSUE THREAD

**Issue by dashesy** [influxdata/influxdb#2442]
It is a valid assumption that relevance of data decrease as time pass, thus retention policy is a great feature about InfluxDB. Sometimes we want to keep data for ever (it could be an expensive process to recalculate), but can accept larger delay when querying older data-points. It would be great to move data to a low-end backed when retention period pass (instead of deleting them), then we could set up the db on fast SSD backends while data is hot, but move it to a slower but bigger cloud after a month when it gets cold.

**Comment by madshall** [comment]
+1 for this

**Comment by madshall** [comment]
There will be also great to be able to downsample that data so that let's say the most accurate data is available for 1 week, then it goes to an archive with only 5 minutes averages stored, after a month it goes to next level of compression with 1 day average values stored.

**Comment by beckettsean** [comment]
@madshall what you describe is already possible, except for the ability to use different mount points for different retention policies, which is what this feature request covers.

**Comment by andre** [comment]
+1 for this. We'd like to use faster storage for initial data, and CQs to roll it up to longer-term slower storage.
