### ISSUE TITLE
Unexpected time range behavior when querying data [2.7.1 OSS]

### ISSUE THREAD

**Issue by daguirrem** [influxdata/influxdb#24433]
__Steps to reproduce:__

1. Create a new bucket named "test"
2. Write specific data to bucket on specific date (it could be any day) (2023-09-01). (line protocol, presicion: seconds):
   admin,config=configTest,type=testingType,farm=testingFarm,shed=testingShed testingType=20000 1693526400
3. Write new some data with more recent date (This case 2023-10-10) with a .flux file query (influx-cli or notebook)

    ```flux
    import "array"
    import "timezone"
    
    option location = timezone.fixed(offset: -5h)
    
    array.from(
        rows: [
            {
                _time: 2023-10-10T00:00:00Z,
                _measurement: "admin",
                _field: "testingType",
                _value: 0,
                config: "configTest",
                type: "testingType",
                farm: "testingFarm",
                shed: "testingShed"
            },
        ],
    ) |>to(bucket: "test")
    ```

4. Query data with time range started at 2023-09-01 and ends at 2023-10-11:
    ```
    from(bucket: "test")
      |> range(start: 2023-09-01, stop: 2023-10-11)
      |> filter(fn: (r) => r["_measurement"] == "admin")
      |> filter(fn: (r) => r["_field"] == "testingType")
    ```
__Expected behaviour:__

The query should return to me a series with 2 points at 2023-09-01 with _value: 20000, and another at 2023-10-10 with _value: 0 like:

| _time                   | _measurement | _field      | _value | config     | type        | farm        | shed        |
|-------------------------|--------------|-------------|--------|------------|-------------|-------------|-------------|
| 2023-09-01 00:00:00 UTC | admin        | testingType | 20000  | configTest | testingType | testingFarm | testingShed |
| 2023-10-10 00:00:00 UTC | admin        | testingType | 0      | configTest | testingType | testingFarm | testingShed |

__Actual behaviour:__

Only returns to me the first point:

| _time                   | _measurement | _field      | _value | config     | type        | farm        | shed        |
|-------------------------|--------------|-------------|--------|------------|-------------|-------------|-------------|
| 2023-09-01 00:00:00 UTC | admin        | testingType | 20000  | configTest | testingType | testingFarm | testingShed |

__Unexpected behaviour:__

-  If modify the flux query adding |> last() at end returns to me the second point (actually the last point):

    ```
    from(bucket: "test")
      |> range(start: 2023-09-01, stop: 2023-10-11)
      |> filter(fn: (r) => r["_measurement"] == "admin")
      |> filter(fn: (r) => r["_field"] == "testingType")
      |> last()
    ```
    
    | _time                   | _measurement | _field      | _value | config     | type        | farm        | shed        |
    |-------------------------|--------------|-------------|--------|------------|-------------|-------------|-------------|
    | 2023-10-10 00:00:00 UTC | admin        | testingType | 0      | configTest | testingType | testingFarm | testingShed |

- If modify the range start to 2023-09-02 returns **nothing** (It should return point at 2023-10-10):

    ```
    from(bucket: "test")
      |> range(start: 2023-09-02, stop: 2023-10-11)
      |> filter(fn: (r) => r["_measurement"] == "admin")
      |> filter(fn: (r) => r["_field"] == "testingType")
    ```
    
    | _time                   | _measurement | _field      | _value | config     | type        | farm        | shed        |
    |-------------------------|--------------|-------------|--------|------------|-------------|-------------|-------------|
 
- If modify the range start to 2023-09-04 (and any recent date after that day) returns the point at 2023-10-10:

    ```
    from(bucket: "test")
      |> range(start: 2023-09-04, stop: 2023-10-11)
      |> filter(fn: (r) => r["_measurement"] == "admin")
      |> filter(fn: (r) => r["_field"] == "testingType")
    ```
    
    | _time                   | _measurement | _field      | _value | config     | type        | farm        | shed        |
    |-------------------------|--------------|-------------|--------|------------|-------------|-------------|-------------|
    | 2023-10-10 00:00:00 UTC | admin        | testingType | 0      | configTest | testingType | testingFarm | testingShed |
__Environment info:__

InfluxDB 2.7.1 OSS running on windows 11 x86_64  VM  (8 vcores 8 GB RAM).
InfluxDB 2.7.1 OSS running on Ubuntu 20.04LTS VM (8 vcores 8 GB RAM).

__Logs:__
If you need logs, how can I generate them in Windows?

__Notebook Result:__
<img src="https://onedrive.live.com/embed?resid=C339667F6DE2A5A0%2123847&authkey=%21AOSuJrKnJqV5xaA&width=1796&height=4064" width="1796" height="4064" />

**Comment by friebi** [comment]
I have a similar issue w.r.t. relative time ranges using relative time ranges.
**Observed behavior:**
![grafik](https://github.com/influxdata/influxdb/assets/6443912/96b7ec4d-75b7-46ec-8643-9316a62af8a4)

**Expected behavior (from Grafana):**
![grafik](https://github.com/influxdata/influxdb/assets/6443912/e0d3f947-35f4-4559-891b-000e6f0edc1c)
=>
![grafik](https://github.com/influxdata/influxdb/assets/6443912/3c4d3bef-17a9-4ba1-b067-76ee7baf8f73)
It even respects the timeshift from CEST to CET happened two weeks ago :sunglasses: 

Similar error occurs using -1y
**Observed behavior:**
![grafik](https://github.com/influxdata/influxdb/assets/6443912/91758448-122d-46ce-93f5-ce97f4358413)
Expected behavior (from Grafana):
![grafik](https://github.com/influxdata/influxdb/assets/6443912/98e1972a-7ccb-486f-91a2-554451b00bcd)

When I use timeshifts smaller than 1mo, it kinda works except that InfluxDB still does not respect the timeshift correctly like Grafana does.

The following query also works, yet still not respecting the timeshift:
![grafik](https://github.com/influxdata/influxdb/assets/6443912/d6212bcb-42d3-409b-8cae-c4bb1e6fa21d)

I'm not sure if this is the same or a different issue. Let me know if I should create a separate one.

**Comment by daguirrem** [comment]
@friebi I thing is different behaviour, but i thing that is related to timezone. I dont't sure, but Grafana time range windows respect your local timezone (you can check administrator/user/organization configurtation -> timezone). Otherwise influx always use UTC timezone as [default](https://docs.influxdata.com/flux/v0/stdlib/timezone/)

> timezone.utc is the default location with a completely linear clock and no offset. It is used as the default for location-related options.

To fix this you can explicit especify the timezone query with timezone package from flux with [fixed](https://docs.influxdata.com/flux/v0/stdlib/timezone/fixed/) or [location](https://docs.influxdata.com/flux/v0/stdlib/timezone/location/)

Something like this should be enought:
```flux
import "timezone"

option location = timezone.location(name: "TZ_Identifier like America/LosAngeles")

from(bucket: "power_meter")
   ...
```

Read the timezone documentation from flux and [TZ Indetifier of your country](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

Let me know if this solve your problem :)

**Comment by friebi** [comment]
Thanks @daguirrem for your reply. Indeed setting the timezone to my local one fixes the second, but smaller issue.

So using `-1mo` it now looks like this:
![grafik](https://github.com/influxdata/influxdb/assets/6443912/72301e27-99fc-4dd9-9c6d-9e53bb27341f)
So still a faulty offset of 14 hours.

Using `date.sub(d: 1mo, from: now())` it is now fully correct:
![grafik](https://github.com/influxdata/influxdb/assets/6443912/2bbc56de-2067-4cc7-92a2-de8cfed05e38)

**Comment by daguirrem** [comment]
The error apparent to be an datatype conflict, If change the step 2 of "steps to reproduce" to write an int (long) like:
admin,config=configTest,type=testingType,farm=testingFarm,shed=testingShed testingType=**20000i** 1693526400
The error is solved.

Also if keep the step 2 to write a float, and change step 3 to explicit write a float the error also is solved.
