### ISSUE TITLE
After the disk is insufficient, WAL cannot write normally. After the disk is released, WAL still cannot write.How to resolve it without restarting

### ISSUE THREAD

**Issue by aeasylife** [influxdata/influxdb#24460]
The event steps are as follows:
1. Insufficient disk, resulting in logs 
```
ts=2023-11-13T01:37:42.723336Z lvl=info msg="Error writing snapshot" log_id=0lMCdVO0000 service=storage-engine engine=tsm1 error="error opening new segment file for wal (1): write D:\\influxdbv2\\engine\\wal\\89bc60b40078d26b\\autogen\\9\\_00481.wal: There is not enough space on the disk."
```
2. Adjust expiration policy to complete disk release
3. The log still appears and cannot be written normally

Restarting Influxdb can solve the problem,But is there any other way?

I couldn't find the relevant problem description and configuration

**Comment by davidby-influx** [comment]
Restarting is the solution.
