### ISSUE TITLE
GitHub release for 2.7.4

### ISSUE THREAD

**Issue by pavelzw** [influxdata/influxdb#24476]
It seems like the GitHub release for 2.7.4 is missing, the only thing for 2.7.4 that I could find was the tag in dockerhub and the git tag. 
Would be nice to have a changelog for 2.7.4 as it appears that there could be breaking changes (see #24467).

**Comment by ThomasFOC** [comment]
I really  would have appreciated some documentation about the release 2.7.4. Thanks to this GitHub issue (and https://github.com/influxdata/influxdb/issues/24536, https://github.com/influxdata/influxdb/issues/24467) I was able to see this new version as dangerous.

Maybe even the maintainers were unsure and removed the release but not before it was announced on the [docs](
https://docs.influxdata.com/influxdb/v2/reference/release-notes/influxdb/) and on [Docker Hub](https://hub.docker.com/_/influxdb/tags).

I support the question for feedback about the Release 2.7.4.

**Comment by pavelzw** [comment]
there seems to be a github release now

https://github.com/influxdata/influxdb/releases/tag/v2.7.4
