### ISSUE TITLE
The special query will make influxd.exe crash

### ISSUE THREAD

**Issue by Cricle** [influxdata/influxdb#24535]
With default config run.

The 90 query join will make influxd.exe crash, here is stack trace.

[stacktrace.txt](https://github.com/influxdata/influxdb/files/13782725/stacktrace.txt)

**Comment by gwossum** [comment]
@Cricle Are you still experiencing this issue? If so, can you can provide a full stack trace including the panic as well as what the query is?

**Comment by davidby-influx** [comment]
Closing because of no response
