### ISSUE TITLE
Two-way replication causes an endless loop

### ISSUE THREAD

**Issue by omerts** [influxdata/influxdb#24550]
__Steps to reproduce:__
1. Create two instances of influxdb2
2. Setup up each instance as a remote of the other instance
3. Setup replications for each remote, so now instance A replicates to instance B, and instance B replicates to instance A

__Expected behaviour:__
I expect the replication to only replicate data that was actually written to disk, aka do not replicate duplicate rows. If we want it to be a little bit smarter, it can also detect the data came from the remote and safely presume there is not reason to replicate it back to it. Nevertheless, if that is not possible I would expect the loop to end once the data already exists in the db.

__Actual behaviour:__
A single write operation starts an endless loop of back and forth replications.

__Environment info:__
Using docker image influxdb:2.7.1

* System info: Linux 4.18.0-372.53.1.el8_6,x86_64 x86_64

**Comment by harry91** [comment]
I met the same problem today. It little bit smarter would be better.

**Comment by gwossum** [comment]
The Edge Data Replication feature is designed to be one-way only. A common use-case would be to replicate data from an IoT gateway up to cloud services. Setting up two instances to replicate to each will result in a loop exactly like you're seeing.

**Comment by omerts** [comment]
@gwossum That really breaks the ability to use this feature for redundancy and creating multiple node clusters.
