### ISSUE TITLE
Create WalImpl for Buffer

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24557]
This WAL implementation will be separate from other WAL implementation, which contains a bit of complexity and cruft that are unnecessary for the Edge product. The wal will be initialized with a directory. The basic interface is already sketched out here: https://github.com/influxdata/influxdb/blob/5831cf8cee706302d39d2f15b271a344dc3eda44/influxdb3_write/src/lib.rs#L140-L169

Ops will be written into the WAL on each request, but they will be sent into a channel so that they can be batched together for a single fsync. We'll default to a 50ms collection time (i.e. first write in starts a timer, which runs for 50ms at which point any writes batched will get sent to the WAL in a single write).

The wal will be organized into segments, each of which will be a file. Segments will be identified with a monotonically increasing u32, with only one segment open at a time. Within each segment file each batch of writes will have a sequence number, a monotonically increasing u32. The logic for numbering segments and closing them off will be in the Buffer, not in the WAL itself.

There will be a reader for a segment file that will yield the individual batches.

**File Format**
* The segment file will start with a version identifier, the string `idb3.001`, indicating what version of the wal file encoding is used.
* The wal batch entries follow, encoded as:
  * u32 checksum
  * u32 length
  * snappy compressed JSON blob of `WalOpBatch`

For now we'll just use the Rust objects and Serde for the encoding/decoding, but as we get farther along we may want to change this. Until we get to the beta, we don't have to worry about backward compatibility or fixing things.

Once we're in Beta, every forward version of 3.x will need to be able to read previous versions of the WAL. So we'll just need to make sure we have tests on this and that when we do update the WAL format, we're able to read both the new and old versions of it.

**Comment by shaeqahmed** [comment]
@pauldix I am evaluating using InfluxDB 3 and its ingest API for extremely high throughput ingestion (100TB+/day) where data loss cannot be tolerated. Is there an ability (or planned) to configure the Edge/OSS product to have higher durability and no chance of data loss. The idea would be to have an option to disable the WAL completely, and persisting directly from the in-memory buffer to object storage (e.g flush every 1 second or x bytes) before acknowledging writes, instead of after an fsync to an unreplicated WAL. For our use case, using disks or incurring inter-AZ costs to replicate the WAL (like Kafka) would be too expensive.

**Comment by pauldix** [comment]
@shaeqahmed for that use case I'd say you should just have your replicated log in front of the InfluxDB server (Kafka could be used and you could have it within a single AZ). Waiting for data to be posted in realtime to object storage would be ruinously expensive or come with very long delays. InfluxDB will be configurable to flush to object storage down to every five minutes, but not less than that.

Our commercial version of InfluxDB will have the ability to replicate and make writes durable on at least 2 disks (in advance of persisting to object storage), but that won't be available until end of this year/early next.

**Comment by shaeqahmed** [comment]
Single AZ Kafka would not meet the durability requirements we have. As long as small files (e.g. not writing a file per table/small custom partitions) aren't being written (S3 PUT costs) I do not think object storage would be ruinously expensive, in fact it is significantly cheaper than replicating across availability zones. 

This is one of the driving principles behind Apache Iceberg replacing Kafka in near real time (few seconds) processing use cases like Flink. A more direct example is WarpStream, a startup that's building a Kafka implementation on object storage by buffering writes to a batch written directly to object storage every 250ms and it still works out to be much cheaper than replication across AZs: https://www.warpstream.com/blog/kafka-is-dead-long-live-kafka#kafka-nomics

**Comment by pauldix** [comment]
@shaeqahmed yes, I've read about WarpStream, but in our case we don't have 1 flow of data that gets written. We have as many as we have tables and frequently there are thousands of them. Then you also have to think about the economics of compacting that data. A distributed WAL doesn't have this problem.

You'd be better off using WarpStream for your distributed WAL and then Influx for the query/Parquet persistence. That kind of optimization is something we're not likely to look at for quite some time. There's little value to us implementing a distributed WAL when there are already many that exist and do it well.
