### ISSUE TITLE
no dashboard button

### ISSUE THREAD

**Issue by Gerd90** [influxdata/influxdb#24589]
Hello,

I cannot create a dashboard because I don't have the button on the navigation bar on the left side.
I had it once but after changing the organization name and log out an back in it is lost.
![Unbenannt](https://github.com/influxdata/influxdb/assets/130140316/e596edc4-a100-4fed-ac5c-45f902c66d19)

**Comment by philjb** [comment]
Hi - thank you for your issue: without steps to reproduce, it is difficult to help. We would welcome a PR to fix a bug if you find it. Please reopen if you have more information.
