### ISSUE TITLE
InfluxDB yum repo forbidden for repomd.xml

### ISSUE THREAD

**Issue by dmsquires** [influxdata/influxdb#24607]
failure: repodata/repomd.xml from influxdb: [Errno 256] No more mirrors to try.
https://repos.influxdata.com/rhel/7/aarch64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden

example /etc/yum.repos.d/influxdb.repo

[influxdb]
name = InfluxDB Repository - RHEL $releasever
baseurl = https://repos.influxdata.com/rhel/7/aarch64/stable/
enabled = 1
gpgcheck = 0
gpgkey = https://repos.influxdata.com/influxdb.key

Have tried this on x86_64 and aarch64 as well with the following setup:

example /etc/yum.repos.d/influxdata.repo

[influxdata]
name = InfluxData Repository - Stable
baseurl = https://repos.influxdata.com/stable/\$basearch/main
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdata-archive_compat.key

[Errno 14] HTTPS Error 403 - Forbidden

These setups were working a day or two ago, and a curl command works, eg:

curl https://repos.influxdata.com/rhel/7/aarch64/stable/repodata/repomd.xml

<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
  <revision>1705678989</revision>
  <data type="primary">
    <checksum type="sha256">4769b255bfa2cefcc603420f1fc6eb06daf566a1d46a7d31cbaa08dd1c2f01ca</checksum>
    <open-checksum type="sha256">3eba6da88a4758de75b7749adab492d614e13968b68f1590a6846c9429ee5625</open-checksum>
    <location href="repodata/4769b255bfa2cefcc603420f1fc6eb06daf566a1d46a7d31cbaa08dd1c2f01ca-primary.xml.gz"/>
    <timestamp>1705678989</timestamp>
    <size>14101</size>
    <open-size>169328</open-size>
  </data>
  <data type="filelists">
    <checksum type="sha256">a09273e7fd2ce61cda5e239b0161cc7c58268a89a09f8b6c77055d36425c3ff0</checksum>
    <open-checksum type="sha256">0249b21120a6b595d541ed025926a331ad3546a7ed1c0c21fe32f92b8d721ad4</open-checksum>
    <location href="repodata/a09273e7fd2ce61cda5e239b0161cc7c58268a89a09f8b6c77055d36425c3ff0-filelists.xml.gz"/>
    <timestamp>1705678989</timestamp>
    <size>7016</size>
    <open-size>73780</open-size>
  </data>
  <data type="other">
    <checksum type="sha256">88512dbea6de907bebbe2854d3ff5d23f6eec144272ab9376b7b9ec8fb182fa7</checksum>
    <open-checksum type="sha256">dd0a189e7686cfd37a7eaf4ae93ed2e53c5751c02660b2e943d2f47e3eb4b65b</open-checksum>
    <location href="repodata/88512dbea6de907bebbe2854d3ff5d23f6eec144272ab9376b7b9ec8fb182fa7-other.xml.gz"/>
    <timestamp>1705678989</timestamp>
    <size>5336</size>
    <open-size>19767</open-size>
  </data>
  <data type="primary_db">
    <checksum type="sha256">18844b28e6675b014e5687bc17503d5e58745910efa09b027f16f8a1e1880504</checksum>
    <open-checksum type="sha256">d06c173b92a352385ff3d1aba067e0408669c7d0f106314a18dff3c7ba1a702b</open-checksum>
    <location href="repodata/18844b28e6675b014e5687bc17503d5e58745910efa09b027f16f8a1e1880504-primary.sqlite.bz2"/>
    <timestamp>1705678989</timestamp>
    <size>32240</size>
    <open-size>237568</open-size>
    <database_version>10</database_version>
  </data>
  <data type="filelists_db">
    <checksum type="sha256">8b40e4c4ec55b4b81ec2fb702114f8fa2c817c0c96d76fb4894dc637116571f0</checksum>
    <open-checksum type="sha256">7a9d78b1f46edfb1e459bea6b7929ff067141fe554cb9ff1d282cc176d834e8e</open-checksum>
    <location href="repodata/8b40e4c4ec55b4b81ec2fb702114f8fa2c817c0c96d76fb4894dc637116571f0-filelists.sqlite.bz2"/>
    <timestamp>1705678989</timestamp>
    <size>17769</size>
    <open-size>106496</open-size>
    <database_version>10</database_version>
  </data>
  <data type="other_db">
    <checksum type="sha256">d2a7e1671bb01f24e154372bff6825551da091c70331af759c4f95f6e127bacc</checksum>
    <open-checksum type="sha256">d74c6e1ee5c0bb326e27057861aec1fe3b989e014e45b8a3ff53566ca39e3e0e</open-checksum>
    <location href="repodata/d2a7e1671bb01f24e154372bff6825551da091c70331af759c4f95f6e127bacc-other.sqlite.bz2"/>
    <timestamp>1705678989</timestamp>
    <size>7343</size>
    <open-size>49152</open-size>
    <database_version>10</database_version>
  </data>
</repomd>

**Comment by bnpfeife** [comment]
Hi, thanks for reporting this!

We tuned our firewall to be a bit too aggressive and we've reverted those changes. Could you verify that everything now works on your systems? Thanks!

**Comment by dmsquires** [comment]
Our systems now have no issues pulling down via yum, thanks much.

**Comment by dgnorton** [comment]
Closing because be believe this is fixed.
