### ISSUE TITLE
Make `Persister` Download Snapshot Files from Object Store Concurrently or in Parallel

### ISSUE THREAD

**Issue by mgattozzi** [influxdata/influxdb#24604]
_See https://github.com/influxdata/influxdb/issues/24604#issuecomment-2470717551 below_

In #24588 I had created the initial implementation of the persister to read and write Segment Info Files, the Catalog, and Parquet data to the Object Store. However, one flaw is that we download the Segment Info Files one at a time as seen here:

https://github.com/influxdata/influxdb/blob/001a2a6653c6e3a7b6e074b07893bf63431a80dd/influxdb3_write/src/persister.rs#L187-L190

If the network is slow this could really slow down any time we need to acquire the segment data.

In the PR I had tried to make it concurrent and while the code in theory should have been successful this was thwarted by the lifetimes created with the `#[async_trait]` proc macro. Getting it to use Rayon's `par_iter()` method also did not work. While async fn in traits is now stable it has it's own issues as well that were hard to untangle with the codebase at this time.

This is a known bottleneck currently and so to make sure we keep track of it I've opened up this issue to keep track of it and to keep track of any progress made addressing it.

**Comment by hiltontj** [comment]
Although things have changed a fair bit since this was opened - we now have snapshots instead of segments - we are still loading the snapshot files in sequence here: https://github.com/influxdata/influxdb/blob/35e29d14087b26a8433c8c24240cb5c2cb494d18/influxdb3_write/src/persister.rs#L231-L234

**Comment by pauldix** [comment]
This is definitely something we'll want to do. We'll also want to fetch WAL files in parallel as well. Maybe we should create an epic around optimizing startup time?

**Comment by hiltontj** [comment]
I created an epic here: https://github.com/influxdata/influxdb/issues/25533
