### ISSUE TITLE
Add retries to buffer persistence

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24657]
The ClosedSegmentBuffer doesn't currently retry if it hits errors on persist. It should retry on errors from the object store.

**Comment by hiltontj** [comment]
We are now attempting persist forever, see: https://github.com/influxdata/influxdb/blob/35e29d14087b26a8433c8c24240cb5c2cb494d18/influxdb3_write/src/write_buffer/queryable_buffer.rs#L508-L536

So I am going to close this.
