### ISSUE TITLE
range() and aggregateWindow() with right stamps is producing time shifts when using multiple times

### ISSUE THREAD

**Issue by werjo** [influxdata/influxdb#24664]
__Steps to reproduce:__

Its not a runtime bug, its a conceptual problem. The problem is that the range filter is always including the start parameter and excluding the stop paramters (`time >= start && time < stop`). This query is not working with right stamped aggrgeates. The query must be (`time > start && time <= stop`) for right stamped data. But range() has no parameter to change the behavior. and aggregateWindow() is right stamped by default. 

Let me explain the problem with some example. Lets say we have some raw data and we have aggregates for 1min resolution and the average. This will lead to the following time series:

```
...
01:00:00 -> (data for 00:59:00 - 01:00:00)
01:01:00 -> (data for 01:00:00 - 01:01:00)
01:02:00 -> (data for 01:01:00 - 01:02:00)
01:03:00 -> (data for 01:02:00 - 01:03:00)
01:04:00 -> (data for 01:03:00 - 01:04:00)
01:05:00 -> (data for 01:04:00 - 01:05:00)
...
```

Everything is fine until now. But what if we have another aggregate on this data, also right stamped with the normal usage of range(). And lets say 15min resolution:

```
...
01:00:00 -> (data for 00:44:00 - 00:59:00)
01:15:00 -> (data for 00:59:00 - 01:14:00)
01:30:00 -> (data for 01:14:00 - 01:29:00)
...
```

Now we have a timeshift of 1min. Every record is not representing the time range of (time-resolution until time) its 1 Minute off.

Lets now use the same query again (we aggregate 15min again to a 15 resolution). Just to show the problem. I had this problem because my raw data was sometimes pre aggregated, sometimes not. 

```
...
01:00:00 -> (data for 00:29:00 - 00:44:00)
01:15:00 -> (data for 00:44:00 - 00:59:00)
01:30:00 -> (data for 00:59:00 - 01:14:00)
...
```

Now we have a time shift of 16 minutes

The reason of this problem ist that if you want to aggregate data with right stamps (and you are assuming all aggregates are right stamped) you have to use a range filter like this: `time > start && time <= stop`. If you are only using left stamped aggregates the filter must be `time >= start && time < stop`. 

**Workaround**

There are two workaround: 
1. Use left stamped aggregates allways `timeSrc` must be set to `_start` in the aggregateWindow() function
2. add one nanosecond to start and stop in the range() filter

**Comment by davidby-influx** [comment]
https://www.influxdata.com/blog/the-plan-for-influxdb-3-0-open-source/#heading4
