### ISSUE TITLE
Influxdb-client for Rust

### ISSUE THREAD

**Issue by evanzhang87** [influxdata/influxdb#24680]
__Use case:__
I'm trying to use Rust to do some downsample jobs with metrics.

__Proposal:__

__Current behaviour:__
https://docs.rs/influxdb/0.7.2/influxdb/  I'm using this client, but it's hard for me to use, especially I used to use golang, it's used like a SQL client.

__Desired behaviour:__

__Alternatives considered:__

**Comment by mgattozzi** [comment]
Despite the name this crate is not maintained by us. Please file an issue [on their repo here](https://github.com/influxdb-rs/influxdb-rust). I think they would find it helpful if you include what you're struggling with and a code example. Just saying I'm having a hard time without the code you're struggling with means they will not be able to help you either.

I'm going to close this issue as this is not our code.
