### ISSUE TITLE
v1 InfluxQL query API

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#24740]
Support the v1 InfluxQL query API in Edge. Documentation for this API can be found [here](https://docs.influxdata.com/influxdb/v1/tools/api/#query-http-endpoint).

### Requirements

- [x] Support only `SELECT` and `SHOW` type queries, i.e., `GET` HTTP requests, and stream their output in JSON using the v1 response structure (see example below) #24746
- [x] #24754
- [x] Handle the `epoch` parameter, which has timestamps returned as a UNIX epoch, with specified precision #24746
- [ ] #24770
- [ ] #24771

#### Example JSON response

```json
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "mymeas",
                    "columns": [
                        "time",
                        "myfield",
                        "mytag1",
                        "mytag2"
                    ],
                    "values": [
                        [
                            "2017-03-01T00:16:18Z",
                            33.1,
                            null,
                            null
                        ],
                        [
                            "2017-03-01T00:17:18Z",
                            12.4,
                            "12",
                            "14"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

### Notes / other considerations

* `chunked` parameter is a boolean, despite what the docs say, and can be accompanied by the `chunk_size` parameter if the user wants to specify an alternate chunk size; when chunking the response, the chunks are split on the chunk size, or on the time series, whichever comes first; with the way that the InfluxQL planner streams record batches for queries that span measurements, this will be possible, as they are streamed one measurement after the other.
* The original API supported basic authentication, or the `p`/`u` query parameters; as per discussion below, we can accept the new v3 token in the `p` parameter, which will give existing clients a means to authorize without any changes.
* The v1 API supports multiple statements in the query, as per [this example](https://docs.influxdata.com/influxdb/v1/tools/api/#send-multiple-queries), which is where the `statement_id` in the response becomes relevant.

**Comment by pauldix** [comment]
We should support the `p`/`u` parameters, but I think we can just use the `p` and have that be the token. Ignore whatever they pass in for the `u`. That will give existing 1.x API clients the ability to still use an authenticated method and hit the API without having to change client code to support bearer token auth.

**Comment by hiltontj** [comment]
A note on the behaviour of the `chunked` parameter...

```bash
curl "http://localhost:8086/query?db=foo&q=select+*+from+cpu&chunked=true&chunk_size=1"
```

Will give a streamed response, like so:

```jsonl
{"results":[{"statement_id":0,"series":[{"name":"cpu","columns":["time","host","tag","usage"],"values":[["2016-05-19T18:37:55Z","s1",null,0.9]],"partial":true}],"partial":true}]}
{"results":[{"statement_id":0,"series":[{"name":"cpu","columns":["time","host","tag","usage"],"values":[["2016-05-19T18:37:56Z","s1",null,0.9]],"partial":true}],"partial":true}]}
{"results":[{"statement_id":0,"series":[{"name":"cpu","columns":["time","host","tag","usage"],"values":[["2016-05-19T18:37:57Z","s1",null,0.9]],"partial":true}],"partial":true}]}
"..."
```

**Comment by hiltontj** [comment]
@pauldix - with the two issues I spun off of this (#24770 and #24771), I think this can be closed, and then we can decide if either of those belongs in the alpha.

**Comment by pauldix** [comment]
Sounds good, I'll have a read through your InfluxQL PR today just to make sure all the behavior looks good (although I assume it is given it works with Grafana )
