### ISSUE TITLE
Delete Timeouts on 2.7.4

### ISSUE THREAD

**Issue by srychlik-capsher** [influxdata/influxdb#24768]
After some inconsistent duration of time, delete operations will start to time out and the CPU usage will gradually increase.

__Steps to reproduce:__

1. Execute various delete operations on Influx
2. Eventually things start to time out

__Expected behaviour:__

Delete performance stays consistent.

__Actual behaviour:__

Delete requests time out in the web client.
CPU usage gradually increases.
Query operations appear to still function properly.

![Screen Shot 2024-03-14 at 2 12 28 PM](https://github.com/influxdata/influxdb/assets/89943655/4ae2cef8-e968-485c-b8f0-14ea4e6f54d9)

Since request duration metrics are written after the web request response is written, it leads me to believe the timeouts are delete requests that somehow get stuck internally in Influx and never get back to the web layer, and then consume more CPU as something internal to the system is babysitting more and more stuck requests / goroutines.

Our only workaround right now is to periodically restart influx, but this doesn't mitigate the problem entirely.

__Environment info:__

Ubuntu VM
Influx 2.7.4

__Logs:__
> http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/delete",response_code="204",status="2XX",user_agent="unknown",le="0.025"} 105993
> http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/delete",response_code="204",status="2XX",user_agent="unknown",le="0.05"} 117921
> http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/delete",response_code="204",status="2XX",user_agent="unknown",le="0.1"} 120840
> http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/delete",response_code="204",status="2XX",user_agent="unknown",le="0.25"} 122566
> http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/delete",response_code="204",status="2XX",user_agent="unknown",le="0.5"} 122990
> http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/delete",response_code="204",status="2XX",user_agent="unknown",le="1"} 123320
> http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/delete",response_code="204",status="2XX",user_agent="unknown",le="2.5"} 123394
> http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/delete",response_code="204",status="2XX",user_agent="unknown",le="5"} 123396
> http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/delete",response_code="204",status="2XX",user_agent="unknown",le="10"} 123396
> http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/delete",response_code="204",status="2XX",user_agent="unknown",le="+Inf"} 123396

**Comment by davidby-influx** [comment]
Deletion is an expensive operation in InfluxDB. If possible, it is better to have data age out through the retention policy than to deliberately delete it.  If you are deleting data explicitly, only one deletion will run at a time, so do not submit a new deletion until the previous one completes.
