### ISSUE TITLE
Fix FlightSQL queries from Grafana

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#24772]
When testing out the InfluxDB Grafana plugin with the v1 query API in Edge (v3), I found that when using SQL to query the target server does not work.

`hyper` is rejecting the request with an _"invalid HTTP method"_ error.

You can see this error in the logs here:
```
2024-03-14T18:45:59.267691Z TRACE hyper::proto::h1::conn: Conn::read_head
2024-03-14T18:45:59.267793Z TRACE hyper::proto::h1::io: received 232 bytes
2024-03-14T18:45:59.268304Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=232
2024-03-14T18:45:59.268633Z TRACE hyper::proto::h1::conn: State::close_read()
2024-03-14T18:45:59.268659Z DEBUG hyper::proto::h1::conn: parse error (invalid HTTP method parsed) with 232 bytes
2024-03-14T18:45:59.268743Z DEBUG hyper::proto::h1::role: sending automatic response (400 Bad Request) for parse error
2024-03-14T18:45:59.268989Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=400, body=None, req_method=None
2024-03-14T18:45:59.269576Z DEBUG hyper::proto::h1::io: flushed 84 bytes
2024-03-14T18:45:59.269609Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled, error: hyper::Error(Parse(Method)) }
2024-03-14T18:45:59.269653Z TRACE hyper::proto::h1::conn: shut down IO complete
2024-03-14T18:45:59.269724Z DEBUG hyper::server::server::new_svc: connection error: invalid HTTP method parsed
```

**Comment by hiltontj** [comment]
The issue appears to be that Grafana is attempting a TLS handshake when establishing the connection, and because I am running my `influxdb3` server locally, I am not serving TLS.

This is the error showing in Grafana:
```
ERROR: flightsql: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
```
I attempted to disable all manner of TLS in my local Grafana, to no avail.

As it turns out, there was recently an [issue](https://github.com/grafana/grafana/issues/83732) opened for this very thing, and a [PR](https://github.com/grafana/grafana/pull/83834) that closes it. So, once that is released, we can try this out again with TLS properly disabled.

**Comment by m0kr4n3** [comment]
I'm using the latest version and I have the same issue here, is there any solution ?

**Comment by hiltontj** [comment]
Hey @m0kr4n3!

> I'm using the latest version [...]

To be clear, do you mean that you are using the latest version of `influxdb` of latest version of Grafana?

In either case, can you verify the version of `influxdb` that you are using? This issue is specifically for the `v3` version of `influxdb` that is still under development, so I just want to make sure that you aren't using a previous major version, e.g., `v1.x` or `v2.x`.

It looks like the change to allow insecure gRPC connections from Grafana's InfluxDB plugin will be part of the 11.0.0 release, which is still [in preview](https://github.com/grafana/grafana/releases/tag/v11.0.0-preview). Unless you are willing to try out the `11.0.0-preview` version of Grafana, you will need to wait for its official release.

**Comment by hipibo** [comment]
I'm using `grafana/grafana:11.0.0` with `docker compose` to test it. The problem still seems to exist.

Is there anyone else like that?

![Xnip2024-05-29_16-46-06](https://github.com/influxdata/influxdb/assets/1525018/0ca5bebf-adae-49c5-b523-11cc871bb8b5)
![Xnip2024-05-29_16-57-07](https://github.com/influxdata/influxdb/assets/1525018/272cdea0-af33-4de7-ad42-d4c7b843ec32)

**Comment by m0kr4n3** [comment]
Hello,

I solved the problem by updating to the latest version of Grafana ( [grafana/grafana:11.0.0-preview](https://hub.docker.com/layers/grafana/grafana/11.0.0-preview/images/sha256-9cfaf3ec1f54708ae15cc186d51aae04db693fba619631ef786b0a63a682e036?context=explore) ) as yours, and building InfluxDB V3 from the base repository. Here is the configuration of the data source that I'm using:

![image](https://github.com/influxdata/influxdb/assets/56729892/c09d96b0-2544-48c7-a524-42faa28e1d79)
and here's the result:

![image](https://github.com/influxdata/influxdb/assets/56729892/d7b6b1f8-b856-4963-93c9-637f5a181ebe)

Note: It is necessary to create a database first for it to work.

Thanks to @hiltontj for the help, I appreciate it.

**Comment by hiltontj** [comment]
Glad you got it to work @m0kr4n3 - thanks for verifying!

@hipibo - I think the key, as @m0kr4n3 pointed out, is to add the `insecureGrpc: true` to the datasource configuration for your InfluxDB plugin. That configuration was the feature added in [the PR](https://github.com/grafana/grafana/pull/83834) that is part of the `11.0.0` release. Sorry that I didn't make that clear... only upgrading to `11.0.0` without adding the configuration won't resolve the issue.

I plan to leave this open until I get time to verify that it works on the stable `11.0.0` version of Grafana.

**Comment by hiltontj** [comment]
After downloading the latest version of Grafana on MacOS (11.3.0), I was able to configure the InfluxDB datasource to allow for a SQL connection to work. See this screenshot of the configuration I am using, to point at a local running InfluxDB:
<img width="1359" alt="Screenshot 2024-11-12 at 12 36 49" src="https://github.com/user-attachments/assets/584a85cd-a365-480b-8be9-351e5dbba7a6">

I will close this issue out for now.

**Comment by tushgaurav** [comment]
> After downloading the latest version of Grafana on MacOS (11.3.0), I was able to configure the InfluxDB datasource to allow for a SQL connection to work. See this screenshot of the configuration I am using, to point at a local running InfluxDB (commit SHA used was `814eb31309d9e85c4363ad3d29a90424abfba579 `): <img alt="Screenshot 2024-11-12 at 12 36 49" width="1359" src="https://private-user-images.githubusercontent.com/6188834/385397142-584a85cd-a365-480b-8be9-351e5dbba7a6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM3OTk0MjQsIm5iZiI6MTc2Mzc5OTEyNCwicGF0aCI6Ii82MTg4ODM0LzM4NTM5NzE0Mi01ODRhODVjZC1hMzY1LTQ4MGItOGJlOS0zNTFlNWRiYmE3YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMjJUMDgxMjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFmZTE2YjRjOGRiZGI4NDU1Zjc2ZjZlOTNjZTY1MDNmNTI5OTUwOTEzNTlmOTZhZmNiMzdiZmQ0NGNkMjg2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.X9iJ6KjfI78HWU69dmTGlOIE88IPCmCyAM2uyQN8d1w">
> 
> I will close this issue out for now.

After allowing "Insecure Connections", I am getting this error:

<img width="1367" height="880" alt="Image" src="https://github.com/user-attachments/assets/3ea51fe8-4e20-4914-8b24-a822bfe8007d" />

Any solutions?
