### ISSUE TITLE
Delete where value > 6000 not working on v2.7.4

### ISSUE THREAD

**Issue by jeroenst** [influxdata/influxdb#24783]
I want to delete bogus values from a table, but the delete where is (still) not working.

```
# influx v1 shell
InfluxQL Shell dev
Connected to InfluxDB OSS v2.7.4
> use "nodered_0002"
> DELETE FROM "solar.grid.watt" WHERE value > 6000
Error: shard 1591: fields not supported in WHERE clause during deletion
No results
```

**Comment by davidby-influx** [comment]
`DELETE` supports `WHERE` filtering with tags, but not with fields.  See documentation [here](https://docs.influxdata.com/influxdb/v2/query-data/influxql/manage-data/#delete-series-with-delete)

**Comment by jeroenst** [comment]
Can this be implemented? It is a mandatory functionality for many users.
