### ISSUE TITLE
Select into not working on v2.7.4

### ISSUE THREAD

**Issue by jeroenst** [influxdata/influxdb#24782]
I wan't to copy all values < 6000 into a new table but it doesn't work in 2.7.4:

```
InfluxQL Shell dev
Connected to InfluxDB OSS v2.7.4
> use "nodered_0002"
> SELECT * FROM "solar.grid.watt" INTO "solar.grid.watt.clean" WHERE value < 6000
ERR: 400 Bad Request: failed to parse query: found INTO, expected ; at line 1, char 33
> SELECT * INTO "solar.grid.watt.clean" FROM "solar.grid.watt" WHERE value < 6000 
Error: not implemented: SELECT INTO
No results

```

Why is this not working?

**Comment by davidby-influx** [comment]
`SELECT INTO` is deliberately [not supported](https://docs.influxdata.com/influxdb/v2/query-data/influxql/#unsupported-influxql-queries) in OSS 2.x.

**Comment by jeroenst** [comment]
Can this be implemented? This functionality is pretty mandatory.
