### ISSUE TITLE
Support parameterized queries in `/api/v3/query_sql`

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#24801]
With recent work in core, should be able to make use of the [`iox_query_params`](https://github.com/influxdata/influxdb3_core/tree/main/iox_query_params) crate to support parameterized queries in the `/api/v3/query_sql` API.

### Design Considerations

* How to pass the parameter values? (e.g., URL parameters, in request body)
* How are parameters represented in query strings? (Datafusion supports numbered, e.g., `$1`, and named parameters, e.g., `$foo`, see [here](https://docs.rs/datafusion/latest/datafusion/common/enum.ParamValues.html))

**Comment by pauldix** [comment]
A single URL param named `params` that is a flat JSON blob of key = name and value = value? Or if it's an array it would be positional params like `$1` in the query itself. But I very much prefer named params from a readability point of view.

**Comment by hiltontj** [comment]
> A single URL param named params that is a flat JSON blob of key = name and value = value?

I think that works, is there an advantage to going with `key = name` + `value = value` vs. just `name = value`?

> But I very much prefer named params from a readability point of view.

+1 for named parameters and readability, and it looks like what we have in `iox_query_params` is intended for named parameters.

---

We might also consider accepting a `POST` request with the parameters as JSON in the body. I find that this is a bit nicer to work with when playing around with an API from something like Postman or other HTTP clients that have native JSON support for request bodies, vs. having to wrangle a JSON string in the URL parameters.

**Comment by pauldix** [comment]
Ahhh, I mean that it's `{"name" : "a value here"}`. Meaning the JSON key is the name of the parameter and the JSON value is the value of the parameter.

+1 for supporting POST. We ended up having to support this in the InfluxQL API because some queries that people wanted to send went over the GET request params limit. So we should support sending the query in the POST body as part of that.

**Comment by hiltontj** [comment]
We can extend the [`QueryParams`](https://github.com/influxdata/influxdb/blob/a2984cdc17816d1fc18f2b4f96e59ea55cf81ab3/influxdb3_server/src/http.rs#L620) with the [`iox_query_params::StatementParams`](https://github.com/influxdata/influxdb3_core/blob/fd238811b995ddf949a4c7546f4c59f25bd451cf/iox_query_params/src/params.rs#L48) directly, i.e.,

```rust
use iox_query_params::StatementParams;

#[derive(Debug, Deserialize)]
pub(crate) struct QueryParams<D, F> {
    #[serde(rename = "db")]
    pub(crate) database: D,
    #[serde(rename = "q")]
    pub(crate) query_str: String,
    pub(crate) format: F,
    pub(crate) params: StatementParams, // <- add this
}
```

It should _just work_ in the body using `serde_json`; not sure about in the URL with `serde_urlencoded`, may need an extra step to deserialize there.

Then, I believe we just need to pass them through to here: https://github.com/influxdata/influxdb/blob/a2984cdc17816d1fc18f2b4f96e59ea55cf81ab3/influxdb3_server/src/query_executor.rs#L120-L133
