### ISSUE TITLE
500 Internal Server Error and Unresponsiveness in InfluxDB v2

### ISSUE THREAD

**Issue by fitz123** [influxdata/influxdb#24802]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. Operate InfluxDB v2.7.4 normally.
2. After about a week of uptime, observe the onset of errors.

__Expected behaviour:__
The InfluxDB instance should handle write and read requests without errors and without needing periodic restarts.

__Actual behaviour:__
Approximately once a week, the InfluxDB instance stops accepting new data with a `500 Internal Server Error` and read queries from Grafana result in `400` errors. Restarting the InfluxDB service resolves the issues temporarily.

__Environment info:__

* InfluxDB version: InfluxDB v2.7.4 (git: 19e5c0e1b7) build_date: 2023-11-08T17:07:39Z
* Operating System: Ubuntu 22.04.3 LTS
* All configuration settings are default.
* 6.7GB database 

__Config:__
Default configuration settings are in use.

__Logs:__
Client application log showing internal server error:

    2024-03-21T11:45:31.684521Z  WARN sink{component_kind="sink" component_id=influx_metrics component_type=influxdb_metrics component_name=influx_metrics}:request{request_id=275296432}: vector::sinks::util::retries: Retrying after response. reason=500 Internal Server Error: {"code":"internal error","message":"unexpected error writing points to database: timeout"} internal_log_rate_limit=true

InfluxDB logs around the time when client starts receiving 500 errors:

    ts=2024-03-21T11:45:31.671859Z lvl=info msg="index opened with 8 partitions" log_id=0nnSYNTl000 service=storage-engine index=tsi
    ts=2024-03-21T11:45:31.672109Z lvl=info msg="loading changes (start)" log_id=0nnSYNTl000 service=storage-engine engine=tsm1 op_name="field indices" op_event=start
    ts=2024-03-21T11:45:31.672152Z lvl=info msg="loading changes (end)" log_id=0nnSYNTl000 service=storage-engine engine=tsm1 op_name="field indices" op_event=end op_elapsed=0.045ms
    ts=2024-03-21T11:45:31.681728Z lvl=info msg="Reindexing TSM data" log_id=0nnSYNTl000 service=storage-engine engine=tsm1 db_shard_id=254
    ts=2024-03-21T11:45:31.681762Z lvl=info msg="Reindexing WAL data" log_id=0nnSYNTl000 service=storage-engine engine=tsm1 db_shard_id=254
    ts=2024-03-21T11:45:31.683315Z lvl=info msg="saving field index changes (start)" log_id=0nnSYNTl000 service=storage-engine engine=tsm1 op_name=MeasurementFieldSet op_event=start
    ts=2024-03-21T11:45:31.683824Z lvl=info msg="saving field index changes (end)" log_id=0nnSYNTl000 service=storage-engine engine=tsm1 op_name=MeasurementFieldSet op_event=end op_elapsed=0.525ms
    <...additional logs...>

There are no explicit error messages in the InfluxDB logs. However, the service stops receiving any new data, and all read queries from Grafana are unsuccessful. The database and memory utilisation are ok.

_monitoring database has logged a series of write timeout errors. These timeout events suggest that the database is occasionally unable to write data.

```
    Interactive Table View (press q to exit mode, shift+up/down to navigate tables):
    Name: write_errors
    ┏━━━━━━━┳━━━━━━━━━━━━━━━━━━━━
    ┃ index ┃              time              ┃  error  ┃
    ┣━━━━━━━╋━━━━━━━━━━━━━━━━━━━━
    ┃      1┃  1711021531659790848.0000000000┃timeout  ┃
    ┃      2┃  1711021531659791104.0000000000┃timeout  ┃
    ...
    ┃     20┃  1711021542687108864.0000000000┃timeout  ┃
    ┃     21┃  1711021542687116288.0000000000┃timeout  ┃
    ┣━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━
```

__Additional Info:__
- The issue occurs without any identifiable pattern but happens approximately once per week.
- Retention policy is also set to 1 week.
- Restarting the InfluxDB service resolves the issue temporarily.
- Look like this error is not recoverable.

__Next Steps:__
- Please advise on any additional data that should be collected to help diagnose the issue.
- I've updated server to v2.7.5
- debug logging is enabled now

__Screenshots:__
- A screenshot of resource utilization around the time of the incident is attached.
<img width="1127" alt="Screenshot 2024-03-21 at 15 18 27" src="https://github.com/influxdata/influxdb/assets/10243861/78c88aa7-6d9c-4ccc-b3a1-0ad6d29afef0">

**Comment by fitz123** [comment]
It happened again.
First detected 500 response from Influx 
```
2024-04-25T14:11:49.356604Z  WARN sink{component_kind="sink" component_id=influx_metrics component_type=influxdb_metrics component_name=influx_metrics}:request{request_id=476192647}: vector::sinks::util::retries: Retrying after response. reason=500 Internal Server Error: {"code":"internal error","message":"unexpected error writing points to database: timeout"} internal_log_rate_limit=true
```

Unfortunately debug logs were suppressed by journald. 
```
    influxd-systemd-start.sh[623]: ts=2024-04-25T14:11:31.228375Z lvl=debug msg="user find by ID" log_id=0o4rFXuG000 store=new took=0.019ms
    systemd-journald[231]: Suppressed 18511 messages from influxdb.service
    influxd-systemd-start.sh[623]: ts=2024-04-25T14:11:59.478295Z lvl=debug msg="user find by ID" log_id=0o4rFXuG000 store=new took=0.021ms
```

**Comment by fitz123** [comment]
I adjusted the batch size from 1 to 1024 and have not encountered the error since making this change. It appears that the issue may have been tied to I/O starvation.

**Comment by michalgruca** [comment]
@fitz123 - I'm facing the same issue, as the one you described. Could you tell something more about the chanes you made?
Was it only changing batch size on influxdb client in your app, or something more?
