### ISSUE TITLE
>influx org create with token returns '401 Unauthorized: write:orgs is unauthorized.'

### ISSUE THREAD

**Issue by RickZhang77** [influxdata/influxdb#24817]
Hey there,

I attempted to execute the following command using InfluxDB OOS v2.7.5:
influx org create -t [my API Token] -n ra8
However, I encountered an error:
Error: failed to create org "ra8": 401 Unauthorized: write:orgs is unauthorized.

Upon inspection, I verified that [my API Token] was generated via [Custom API Token] and granted both [Read] and [Write] access.
Could you assist in resolving this issue?

**Comment by RickZhang77** [comment]
Attached the API Token access
![Capture](https://github.com/influxdata/influxdb/assets/88818317/f92c9383-4c3c-49d9-9907-82cf69b76e59)

**Comment by sanderson** [comment]
Thanks for reporting @RickZhang77. The action of creating an organization requires an operator token. This detail is missing from the documentation, but I have a change in progress to fix it.

**Comment by hinst** [comment]
Can someone please tell me what is the solution here? I have to restore a backup from a folder, but I cannot do it because of the error:

`401 Unauthorized: write:orgs is unauthorized`

How to generate a token for `influx restore` ?
