### ISSUE TITLE
[InfluxDB v2.7.1] Why the bucket retention period do not working?

### ISSUE THREAD

**Issue by lzl82891314** [influxdata/influxdb#24816]
I have an InfluxDB bucket for storing some of my system log data. 

Initially, the retention period was set to `28 days`, but later, due to some business requirements, I changed it to `48 hours`. 

![image](https://github.com/influxdata/influxdb/assets/9321017/6e478729-2666-4c97-9a1d-d5ab8ca984d8)

However, I've noticed that, after making this change, the previous data has not been cleared, and I am still able to query data from **7 days ago**. 

![image](https://github.com/influxdata/influxdb/assets/9321017/8b37e8be-cb52-4417-b16c-7b8c9b1f10a2)

Could you please explain why this is happening?

**Comment by davidby-influx** [comment]
Retention policy changes do not affect past data, by design.
