### ISSUE TITLE
Set parameters for query request with `influxdb3` Client using a collection

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#24812]
Following discussion on #24806

Currently, when using the `influxdb3_client::Client` to send a query request, if setting the parameters on a `QueryRequestBuilder` using a collection, we need to do something like this:
```rust
let client = Client::new("http://localhost:8181")?;
let mut req_builder = client
    .api_v3_query_sql("db_name", "SELECT * FROM foo WHERE bar = $bar AND baz > $baz");

for (key, val) in params {
    req_builder = req_builder.with_try_param(key, value)?;
}

let response_bytes =  req_builder
    .send()
    .await
    .expect("send query_sql request");
```

It would be useful to have a method on `QueryRequestBuilder` that accepts an iterator of `Into<StatementParam>` so that we can do the above in a single call without the need for the hand-crafted loop.

For example, the above would be reduced to something like:
```rust
let response_bytes = client
    .api_v3_query_sql("db_name", "SELECT * FROM foo WHERE bar = $bar AND baz > $baz")
    .with_params_from(params)
    .send()
    .await
    .expect("send query_sql request");
```

**Comment by jbajic** [comment]
Can I take this one?
