### ISSUE TITLE
nfluxdb 2.7.1 “TSM compaction”generate  multiple tsm.tmp suffix file, rd/s 400M for 15 minutes

### ISSUE THREAD

**Issue by junshiya** [influxdata/influxdb#24810]
### Steps to reproduce:

2. Once the following files appear, disk IO is fully utilized (limited to 400m/s) and the application hangs.

-rw-r--r--  1 root root 2152978201 Mar 23 20:45 000033564-000000005.tsm.tmp
-rw-r--r--  1 root root 2154677387 Mar 23 20:47 000033564-000000006.tsm.tmp
-rw-r--r--  1 root root 2152138278 Mar 23 20:49 000033564-000000007.tsm.tmp
-rw-r--r--  1 root root 2151254455 Mar 23 20:50 000033564-000000008.tsm.tmp
-rw-r--r--  1 root root 2151256966 Mar 23 20:52 000033564-000000009.tsm.tmp
-rw-r--r--  1 root root 2151239035 Mar 23 20:53 000033564-000000010.tsm.tmp
-rw-r--r--  1 root root 2151096964 Mar 23 20:55 000033564-000000011.tsm.tmp
-rw-r--r--  1 root root 2151180547 Mar 23 20:56 000033564-000000012.tsm.tmp
-rw-r--r--  1 root root 2151203949 Mar 23 20:58 000033564-000000013.tsm.tmp
-rw-r--r--  1 root root 2150162694 Mar 23 21:00 000033564-000000014.tsm.tmp
-rw-r--r--  1 root root 2148404294 Mar 23 21:02 000033564-000000015.tsm.tmp
-rw-r--r--  1 root root  159383552 Mar 23 21:06 000033564-000000016.idx.tmp
-rw-r--r--  1 root root 1173356544 Mar 23 21:06 000033564-000000016.tsm.tmp
3. Last for about 15 minutes until the tmp file processing is completed

## Hardware Environment:

- Package: ... 
- CPU cores / RAM: 16Core / 64GB RAM
- Data 120G  total   Retention: 90 days
- 500MBytes per minute
- Linux XXX 4.19.90-25.29.x86_64 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
- conifg.yam
       storage-cache-max-memory-size: 10737418240
	storage-cache-snapshot-memory-size: 52214400
	storage-cache-snapshot-write-cold-duration: 30m0s
	storage-compact-full-write-cold-duration: 4h0m0s
	storage-max-concurrent-compactions: 1
	storage-compact-throughput-burst: 335544320
	storage-max-index-log-file-size: 8388608
	storage-series-id-set-cache-size: 100

## Build Environment:

[ ] I'm using sccache

**Comment by davidby-influx** [comment]
If your disk bandwidth is inadequate for the compaction cycle, you can limit the rate with this parameter:
https://docs.influxdata.com/influxdb/v2/reference/config-options/#storage-compact-throughput-burst

**Comment by davidby-influx** [comment]
Closing because of no response.
