### ISSUE TITLE
Report the CPU, RAM, Disk, and Network I/O of the `influxdb3` process during load generation

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24829]
When running the load generator it should have an optional parameter to collect system metrics for the influxdb3 process running on the box. This assumes in this case that the load generator is running on the same system as the influxdb3 process.

Ideally we'd collect CPU, RAM, Disk, and Network metrics every second during the test run and write that data out to csv files. Since each of these have different schemas, it probably makes sense to have each one output its own csv file. In addition to the reported metric, include `test_time_ms` and `wall_time` in the results.

CPU and RAM are the most important here, we can start with those if it's easier.

**Comment by hiltontj** [comment]
@pauldix - Here are is what we could grab using the [`sysinfo`](https://docs.rs/sysinfo/latest/sysinfo/struct.Process.html#) crate from the running `influxdb3` process:

- [`cpu_usage`](https://docs.rs/sysinfo/latest/sysinfo/struct.Process.html#method.cpu_usage): total CPU usage, may be greater than 100 for multi-core
- `normalized_cpu_usage`: may calculate this as `cpu_usage` / `num_cpus`
- [`disk_written_bytes`/`disk_read_bytes`](https://docs.rs/sysinfo/latest/sysinfo/struct.DiskUsage.html): these can be grabbed incrementally, or in total from when the process started
- [`memory_bytes`](https://docs.rs/sysinfo/latest/sysinfo/struct.Process.html#method.memory)
- [`virtual_memory_bytes`](https://docs.rs/sysinfo/latest/sysinfo/struct.Process.html#method.virtual_memory)

I aim to start with these. Beyond that, i.e., for network stats, we will need to look for alternatives. I have not yet found a crate that can fill that gap.

**Comment by pauldix** [comment]
That's a great start. RAM and CPU are the most important for our purposes with disk third and network a very distant fourth. I'd say skip network for now and we can come back to it if we find it's something we need.
