### ISSUE TITLE
Add a `series_id` accessor to `ParsedLine`

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#24821]
Add a `series_id` accessor to `ParsedLine` that is a sha256 of the lexicographically ordered tagset.

**Comment by hiltontj** [comment]
@pauldix - looks like we would be able to compute the `_series_id` from the full tag set when performing `ParsedLine` validation/conversion here:
https://github.com/influxdata/influxdb/blob/f4cfae37d85fe1ac05b6b6db17a952a0258ed8ff/influxdb3_write/src/write_buffer/mod.rs#L566-L574

Will likely also need to add the `_series_id` column to the schema on new table creation in the preceding `match` logic in that function, similar to how is done for the `time` column.

My understanding is that we want to compute the SHA256 of the ordered tag keys _and_ values. So, for the tag set:
```
a=foo,b=bar,c=baz
```
* the order is based on tag key, i.e., this is in the correct order
* the input to the SHA256 is the literal `"a=foo,b=bar,c=baz"`, preserving `=` and `,` to prevent collisions

**Comment by pauldix** [comment]
Correct on the ordering and preserving the `=` and `,`. Well behaved InfluxDB clients will send line protocol with the tags already correctly sorted (we've mentioned that as best practices for years). So in the ideal case, you'd be able to hash that string without constructing one in the correct order. If they don't order them correctly, then fallback to doing the work.

**Comment by hiltontj** [comment]
The series ID should also be generated off of the measurement name. So, for the line:
```
cpu,a=1,b=2,c=3 usage=0.5
```
The input to generate the series ID hash should be `"cpu,a=1,b=2,c=3"`.

**Comment by pauldix** [comment]
Actually, the series id is going to be scoped by the table/measurement so that doesn't need to be a part of the hash. It only needs to be a unique identifier within the table. Having it be common across tables might actually be an asset later on if there are different measurements with the same tagset that you want to join across using the series id.

**Comment by hiltontj** [comment]
@pauldix my concern was measurements with no tag set, but I guess in that case, their series ID would just be the SHA of an empty string.
