### ISSUE TITLE
Add basic query spec and runner implementation to load generator

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24828]
Add a query specification to the load generator and implement the runner to perform queries as specified during load generation. Once defined, the [`BuiltInSpec`](https://github.com/influxdata/influxdb/blob/main/influxdb3_load_generator/src/specs/mod.rs#L14-L17) should be extended to include a query specification.

### Query Specification

The query specification should define the following:

- The query with params in the string
- Params that can get filled
    - Will need one to pair with tags that have cardinality, so we can select a specific series. e.g. fill the param with a cardinality number (could be random, could rotate through each number)
    - Random int or float so that we can do comparisons, equals vs. some number (not sure how useful this one is given we want repeatable tests and matching criteria to pull back various numbers of rows might just create noise)

### Runner Implementation

The runner should be able to specify the number of concurrent queriers, which specification to run, and should collect results into a CSV.

For results we should keep

- `test_time_ms` - elapsed time since the load test began
- `response_ms` - response time of the query in ms
- `rows` - the count of rows in the response*
- `querier_id` - ID of querier that produced result
- `wall_time` - timestamp of when query was performed
- `response` - HTTP `2xx`/`4xx`/`5xx`

_[*] hopefully this is cheap enough to compute, but if too expensive, remove_

**Comment by hiltontj** [comment]
@pauldix - what were you referring to by `query_number` in the results?

**Comment by pauldix** [comment]
Oh, queries should be specified by a short name. I meant that to be `querier_id` since you'll be able to launch N concurrent queriers.

**Comment by hiltontj** [comment]
Most of this was covered by #24854 - I left this open because I did not address the second bullet for params that can be filled, i.e.,
> Random int or float so that we can do comparisons, equals vs. some number (not sure how useful this one is given we want repeatable tests and matching criteria to pull back various numbers of rows might just create noise)

**Comment by pauldix** [comment]
I think we can close this out and hold off on that part for now. Not sure if it's useful, so let's just not build it 😄
