### ISSUE TITLE
Add command to load generator to kick-off `write` and `query` at the same time

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24832]
We'll want to run write and query load testing at the same time as one can have a significant impact on the other. Running both we should be able to specify a write spec and query spec and run both at the same time writing results for each based on the spec name and configuration name.

**Comment by hiltontj** [comment]
Here is the current state of the command configurations for the `query` and `write` load generation commands:

  | Common | Query | Write
-- | -- | -- | --
Host URL | -h, —host |   |  
Database Name | -d, —dbname |   |  
Auth Token | —token |   |  
Spec Path | -s, —spec |   |  
Built-in Spec | —builtin-spec |   |  
Print Spec | —print-spec |   |  
Results Dir | -r, —results-dir |   |  
Configuration Name | —config-name |   |  
System Stats | —system-stats |   |  
Query Sampling Interval |   | -I, —query-interval |  
Querier Count |   | -Q, —querier-count |  
Query Response Format |   | -F, —query-format |  
Write Sampling Interval |   |   | -i, —interval
Writer Count |   |   | -w, —writer-count
Dry Run |   |   | —dry-run
Start |   |   | —start
End |   |   | —end

I would like to propose the following changes:
* Remove the **Query Sampling Interval**; as per [this discussion](https://github.com/influxdata/influxdb/pull/24854#discussion_r1544561041), a query interval is not relevant, as queries just get run one after the other.
* Short form for **Querier Count** can just be `-q`, originally I made `query` args upper-case to not collide with `write` args, but there seems little reason to do this.
* Remove the short form for **Query Response Format**, as I don't believe this will be used much.
* Remove Spec Path in favour of `query`/`write`-specific spec path args

This would result in the following:

  | Common | Query | Write
-- | -- | -- | --
Host URL | -h, —host |   |  
Database Name | -d, —dbname |   |  
Auth Token | —token |   |  
Built-in Spec | —builtin-spec |   |  
Print Spec | —print-spec |   |  
Results Dir | -r, —results-dir |   |  
Configuration Name | —config-name |   |  
System Stats | —system-stats |   |  
Querier Count |   | -q, —querier-count |  
Querier Spec Path |   | —querier-spec |  
Query Response Format |   | —query-format |  
Write Sampling Interval |   |   | -i, —interval
Writer Count |   |   | -w, —writer-count
Writer Spec Path |   |   | —writer-spec
Dry Run |   |   | —dry-run
Start |   |   | —start
End |   |   | —end

This should make unifying to run in a single command fairly painless.

**Comment by pauldix** [comment]
Makes sense to me, thanks for the really clear presentation of it! 😀
