### ISSUE TITLE
Create notebook or some unified view for reporting

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24833]
Once the load generator is able to run write and query at the same time and write results into standardized names, we'll want a single script to run to show an analysis. Given a results directory, spec name, and configuration name it should read the write, query, cpu, mem, disk, and network results files and show useful information with it (everything has test time in seconds on the x axis). Graphs:

* Lines per second, grouped in 10s intervals
* MB per second of ingest in 10s intervals
* Min, max, and median write response times in 1s intervals (all lines on a single graph)
* Queries per second in 10s intervals
* Min, max and median query response times in 1s intervals
* Query result rows per second grouped in 1s intervals

Should also be able to run with two configuration names and have both configurations drawn on each graph for easy comparison.

**Comment by hiltontj** [comment]
Closed by #24889
