### ISSUE TITLE
Add query by `_series_id`

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24861]
Update the query spec to have an option that will query by `_series_id`. For specs that have a single tag, or if the query has all tags specified in its criteria, have the load generator calculate the `_series_id` for that query by computing the hash of the tags in the where clause and use that in the resulting query. For example with the one_mil spec, it has only one tag so queries that specify to use that tag should be able to be converted to query on the _series_id instead.

This probably won't be a feature we'll need in the future, but it's useful for some testing in the near term related to #24863

**Comment by hiltontj** [comment]
Given that we dropped the `_series_id` concept, I am going to close this issue.
