### ISSUE TITLE
`heappy` and `pprof` feature flags are not implemented in `influxdb3_server`

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#24865]
The `influxdb3_server` crate makes use of the `heappy` and `pprof` feature flags, but they are not included as features in the `Cargo.toml`. Furthermore, the code in `influxdb3_server/src/http.rs` that is gated by those feature flags would not compile, because it is referring to private members of the `ioxd_common` core crate, and also uses the `heappy` and `pprof` crates directly, which are not included as dependencies of `influxdb3_server`.

Either the respective members in `ioxd_common` need to be made public, or the functionality therein needs to be re-implemented in `influxdb` directly.

**Comment by pauldix** [comment]
These are getting removed upstream so we won't need to support it. First one already up at influxdata/influxdb_iox#10875

**Comment by mgattozzi** [comment]
I haven't needed to use em so I think removing them would be fine.
