### ISSUE TITLE
Update get_table_chunks to return buffer chunks based on _series_id if present in filter

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24867]
One of the ideas I have for optimizing for single series is to have the buffer able to return data for individual series very quickly. To test this out, one place to insert this would be in the `get_table_chunks` function of the write buffer. Currently, it just sends back whatever record batches are in the segments.

The idea here is to send back record batches that only contain data for the _series_ids listed in the passed Exprs. If that isn't present, then just return the record batches as normal. For queries that hit this optimization, it'll just hide all data from the buffer that isn't relevant.

**Comment by alamb** [comment]
I think the code is here https://github.com/influxdata/influxdb/blob/e0465843bee6763f2141ffdb94fa4ea41b57ee80/influxdb3_write/src/write_buffer/segment_state.rs#L111

**Comment by pauldix** [comment]
no longer relevant
