### ISSUE TITLE
Proposal for Dynamic Time Range Variables Based on Database Tags in InfluxDB Flux Queries

### ISSUE THREAD

**Issue by madhurimarawat** [influxdata/influxdb#24877]
__Use case:__
I am currently using InfluxDB for time-series data storage and Flux for querying. In my workflow, there is a need for a feature that enables the setting of time ranges as dynamic variables, which can be fetched using tags in our database. This is important for scenarios where the time range needs to be adjusted dynamically based on the data's characteristics or conditions.

__Proposal:__
I propose the implementation of a feature that allows users to set time ranges as dynamic variables, which can be fetched using tags in the database. This would provide greater flexibility and control over data retrieval, allowing users to adjust time ranges dynamically based on specific conditions or parameters.

__Current behaviour:__
Currently, time ranges in Flux queries are typically set as static values, defined within the query itself or specified in the Time Range section of the user interface. This limits flexibility, as the time range cannot be adjusted dynamically based on the data.

__Desired behaviour:__
The desired behaviour is for users to be able to define time ranges as dynamic variables, which can be fetched using tags in the database. This would allow for the dynamic adjustment of time ranges based on the data's characteristics or conditions, improving the usability and flexibility of InfluxDB for time-series data analysis.

__Alternatives considered:__
One alternative solution considered is to manually specify time ranges in Flux queries based on external factors. However, this approach can be cumbersome and less efficient, especially in scenarios where time ranges need to be adjusted frequently or based on complex conditions. Additionally, this method often results in errors and is not fully supported, leading to difficulties in query execution and data retrieval. Introducing dynamic variables for time ranges based on database tags would provide a more elegant and scalable solution, offering greater flexibility and reliability in querying time-series data.

Additionally, the static variables currently used for time ranges could be replaced with a dynamic option that fetches the time range from the specified timestamp in the database, further enhancing the flexibility and usability of the feature.

**Comment by philjb** [comment]
Have you tried the "query" type variables that are available in oss v2 ui? 

See the docs here: https://docs.influxdata.com/influxdb/v2/visualize-data/variables/variable-types/

I think they will do what you want. 

Also, I believe you can define a variable in flux (a flux variable - not a ui variable) that is based on the output of an earlier query- then the variable can be used in the range of a subsequent query. 

Please note the message about flux: https://github.com/influxdata/influxdb#flux

**Comment by madhurimarawat** [comment]
start_time = from(bucket: "motifs_timestamp")
  |> filter(fn: (r) => r["sensor_name"] == "[3:25]")
  |> filter(fn: (r) => r["timestamp"] == "start")
  |> map(fn: (r) => ({
      _time: r._time
  }))
  |> first()

end_time = from(bucket: "motifs_timestamp")
  |> filter(fn: (r) => r["sensor_name"] == "[3:25]")
  |> filter(fn: (r) => r["timestamp"] == "end")
  |> map(fn: (r) => ({
      _time: r._time
  }))
  |> first()


from(bucket: "motifs_timestamp")
  |> range(start: start_time, stop: end_time)
  |> filter(fn: (r) => r["_measurement"] == "motifs_per_signal")
  |> filter(fn: (r) => r["_field"] == "sensor_reading")
  |> filter(fn: (r) => r["sensor_name"] == "[3:25]")
  |> filter(fn: (r) => r["motif_name"] == "Motifs_1")
