### ISSUE TITLE
`unwrap` in `TableBuffer::record_batches` causing panics

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#24880]
While working on the load generator, I came across some `unwrap` errors from the table buffer implementation.

Specifically, this function: https://github.com/influxdata/influxdb/blob/main/influxdb3_write/src/write_buffer/table_buffer.rs#L186-L196

The panic error:
```
thread 'tokio-runtime-worker' panicked at influxdb3_write/src/write_buffer/table_buffer.rs:191:47:
called `Option::unwrap()` on a `None` value
```
So, the call to get the field from the `TableBuffer` by the schema's field name is returning `None`.

I extended the panic message to see what field was causing the panic, and found that it is a field that is contained in the catalog on disk, so there may be something off with how the table buffer is initializing from the catalog.

**Comment by pauldix** [comment]
Ah, the buffer only creates columns for data that it sees as you're writing rows in. It doesn't actually have access to the Catalog at all. So this just needs to be fixed when getting the record batch data out of the table. It will either need to create that column filled with nulls, or do projection on the schema to remove the columns that don't appear in its buffer and use that projection in the record batches it creates.

**Comment by hiltontj** [comment]
It is not clear if this issue is still present, but in the current table buffer code, there are no unwraps when producing record batches [here](https://github.com/influxdata/influxdb/blob/35e29d14087b26a8433c8c24240cb5c2cb494d18/influxdb3_write/src/write_buffer/table_buffer.rs#L71) or [here](https://github.com/influxdata/influxdb/blob/35e29d14087b26a8433c8c24240cb5c2cb494d18/influxdb3_write/src/write_buffer/table_buffer.rs#L109), so I think this can be closed.
