### ISSUE TITLE
InfluxDB 1.8.10 Not Responding, Too many open files Error

### ISSUE THREAD

**Issue by Satish2007** [influxdata/influxdb#24883]
Hi All and @davidby-influx 

I am observing below issue for my InfluxDB 1.8.10.

**Issue**: InfluxDB not responding and stopping. Getting too many open files error.

**Influxdb.conf** : every thing is default except cache_max_memory: 32GB

System Environment:
Operating System: Ubuntu 22.04 on Azure
InfluxDB Version: 1.8.10
CPU: 32vCPU
RAM: 128GB
Disk Type: SSD
cache-max-memory: 32GB
Index Type: TSM

**ulimit -a**
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 515580
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 515580
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

 **sysctl -p**
vm.max_map_count = 262144
fs.file-max = 524288

**cat /etc/security/limits.conf**
* soft  nproc           65535
* hard  nproc           65535
* soft  nofile          65535
* hard  nofile          65535
root soft  nofile          65535
root hard  nofile          65535

**Error in Logfile**:

Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.565072Z lvl=info msg="Error writing snapshot from compactor" log_id=0o1m93RG000 engine=tsm1 trace_id=0oM7wUN0001 op_name=tsm1_cache_snapshot error="compaction in progress: open /data/influx-data/data/Datastore2623/autogen/121662/000005994-000000001.tsm.tmp: too many open files"
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.565104Z lvl=info msg="Cache snapshot (end)" log_id=0o1m93RG000 engine=tsm1 trace_id=0oM7wUN0001 op_name=tsm1_cache_snapshot op_event=end op_elapsed=0.181ms
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.565113Z lvl=info msg="Error writing snapshot" log_id=0o1m93RG000 engine=tsm1 error="compaction in progress: open /data/influx-data/data/Datastore2623/autogen/121662/000005994-000000001.tsm.tmp: too many open files"
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.565415Z lvl=info msg="Cache snapshot (start)" log_id=0o1m93RG000 engine=tsm1 trace_id=0oM7wUNG000 op_name=tsm1_cache_snapshot op_event=start
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.565439Z lvl=info msg="Cache snapshot (end)" log_id=0o1m93RG000 engine=tsm1 trace_id=0oM7wUNG000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=0.027ms
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.565444Z lvl=info msg="Error writing snapshot" log_id=0o1m93RG000 engine=tsm1 error="error opening new segment file for wal (1): close /data/influx-data/wal/Datastore2623/autogen/121589/_00001.wal: file already closed"
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.566183Z lvl=info msg="failed to store statistics" log_id=0o1m93RG000 service=monitor error="engine: error rolling WAL segment: error opening new segment file for wal (2): close /data/influx-data/wal/_internal/monitor/120287/_12279.wal: file already closed"
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.566190Z lvl=info msg="Cache snapshot (end)" log_id=0o1m93RG000 engine=tsm1 trace_id=0oM7wU3W000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=80.186ms
.
.
.
pr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.633456Z lvl=info msg="failed to store statistics" log_id=0o1m93RG000 service=monitor error="engine: error rolling WAL segment: error opening new segment file for wal (2): close /data/influx-data/wal/_internal/monitor/120287/_12279.wal: file already closed"
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.633502Z lvl=info msg="Terminating storage of statistics" log_id=0o1m93RG000 service=monitor
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.633530Z lvl=info msg="Terminating precreation service" log_id=0o1m93RG000 service=shard-precreation
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.633549Z lvl=info msg="Terminating continuous query service" log_id=0o1m93RG000 service=continuous_querier
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.642937Z lvl=info msg="Closing retention policy enforcement service" log_id=0o1m93RG000 service=retention
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.686959Z lvl=info msg="TSM compaction (start)" log_id=0o1m93RG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=0oM7wUqW000 op_name=tsm1_compact_group db_shard_id=106896 op_event=start
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.686992Z lvl=info msg="Beginning compaction" log_id=0o1m93RG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=0oM7wUqW000 op_name=tsm1_compact_group db_shard_id=106896 tsm1_files_n=2
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.687011Z lvl=info msg="Compacting file" log_id=0o1m93RG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=0oM7wUqW000 op_name=tsm1_compact_group db_shard_id=106896 tsm1_index=0 tsm1_file=/data/influx-data/data/Datastore2518/autogen/106896/000000001-000000001.tsm
Apr  4 15:17:21 influx-opc influxd-systemd-start.sh[2478]: ts=2024-04-04T09:47:21.687017Z lvl=info msg="Compacting file" log_id=0o1m93RG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=0oM7wUqW000 op_name=tsm1_compact_group db_shard_id=106896 tsm1_index=1 tsm1_file=/data/influx-data/data/Datastore2518/autogen/106896/000000003-000000001.tsm

Any help/suggestions are appreciated in advance.

With Regards

**Comment by Satish2007** [comment]
Not sure if following is applicable to me too : #22824

Anyway i will try this too, but any suggestions/help is appreciated 

below is [monitor] setting: 
[monitor]
  # Whether to record statistics internally.
  # store-enabled = true

  # The destination database for recorded statistics
  # store-database = "_internal"

  # The interval at which to record statistics
  # store-interval = "10s"

###
### [http]

**Comment by Satish2007** [comment]
Issue has been resolved by increasing fs.file-max,  nofile, nr_open and LimitOnFile. Thank you @davidby-influx  once again.

**Comment by matzeeg3** [comment]
how can i change this in docker?
