### ISSUE TITLE
Task downsampling sets wrong timestamp

### ISSUE THREAD

**Issue by overlinden** [influxdata/influxdb#24899]
Hi Team,

I am using influx and grafana for my iot stack at home.
Sensor data is written from several sources to a "Livedaten" bucket. I a hourly task the data is aggregated and enhanced and written to a "1hDaten" bucket. On this bucket all reporting based on grafana is implemented.

__Steps to reproduce:__
1. Create a bucket with multiple data points
2. Impelmetn a task to downsample the first bucket into a second bucket
3. Check the timestamp of the second bucket data points

__Expected behaviour:__
The downsampling in influx is "backwards". This is ok. E.g. Data from the first bucket between 2024-04-08T04:00:00.000Z and 2024-04-08T05:00:00.000Z is written to a downsampled datapoint at 2024-04-08T04:00:00.000Z. I expect this to be exactly 2024-04-08T04:00:00.000Z and not after.
When I execute the task code in the query editor the timestamps are correct:
![2024-04-08_08h37_02](https://github.com/influxdata/influxdb/assets/5543041/1106cd90-af2d-4456-8d6c-497e216b4057)

__Actual behaviour:__
I recognized that the tasks seem to set a new timestamp to the aggregated meassurement. The new timestamp seems to be the rounded minute of the task execution. Following the example above the downsampled datapoint is written to 2024-04-08T04:01:00.000Z instead of 2024-04-08T04:00:00.000Z.

![2024-04-08_08h31_35](https://github.com/influxdata/influxdb/assets/5543041/0f590b72-0502-4ae6-9520-bc12d5abd6da)

This does not look like a big deal but in combination with grafana where the aggregation is done "forwards" the datapoint is assigned to the next full hour --> 2024-04-08T05:00:00.000Z in this example.
Therefore all visualizations are shifted by one hour what is quiet confusing.

__Environment info:__
* I use InfluxDB v2.7.5 as docker image
* Timezone of the docker host is UTC+2
* TImezone if the influx container is UTC

__Config:__
I use the default configuration.

__Logs:__
Here is a run log of one of the task executions.

> 2024-04-08 08:00:00 | Started task from script: "option task = {name: \"Raumklima Downsample 1h\", every: 1h}\n\n// Datenquelle\ndata =\n    from(bucket: \"Livedaten\")\n        \|> range(start: -task.every)\n        \|> filter(fn: (r) => r[\"_measurement\"] == \"Raumklima\")\n\n// Berechnung Mittelwerte\ndata\n    \|> filter(\n        fn: (r) =>\n            r[\"_field\"] == \"RelLuftfeuchtigkeit\" or r[\"_field\"] == \"TemperaturInC\" or r[\"_field\"]\n                ==\n                \"TaupunktInC\" or r[\"_field\"] == \"Schimmelneigung\",\n    )\n    \|> aggregateWindow(every: task.every, fn: mean, createEmpty: false)\n    \|> to(bucket: \"1hDaten\", org: \"Organization\")\n"
> 2024-04-08 08:00:00 | Completed(success)

The task code is:
```
option task = {name: "Raumklima Downsample 1h", every: 1h}

// Datenquelle
data =
    from(bucket: "Livedaten")
        |> range(start: -task.every)
        |> filter(fn: (r) => r["_measurement"] == "Raumklima")

// Berechnung Mittelwerte
data
    |> filter(
        fn: (r) =>
            r["_field"] == "RelLuftfeuchtigkeit" or r["_field"] == "TemperaturInC" or r["_field"]
                ==
                "TaupunktInC" or r["_field"] == "Schimmelneigung",
    )
    |> aggregateWindow(every: task.every, fn: mean, createEmpty: false)
    |> to(bucket: "1hDaten", org: "Verlinden")
```

**Comment by sanderson** [comment]
@overlinden By default, `aggregateWindow()` uses the window `_stop` time as the new timestamp for the aggregated data. To use the `_start` time of the window instead, set the `timeSrc` parameter in `aggregateWindow()` to `_start`:

```javascript
option task = {name: "Raumklima Downsample 1h", every: 1h}

// Datenquelle
data =
    from(bucket: "Livedaten")
        |> range(start: -task.every)
        |> filter(fn: (r) => r["_measurement"] == "Raumklima")

// Berechnung Mittelwerte
data
    |> filter(
        fn: (r) =>
            r["_field"] == "RelLuftfeuchtigkeit" or r["_field"] == "TemperaturInC" or r["_field"]
                ==
                "TaupunktInC" or r["_field"] == "Schimmelneigung",
    )
    |> aggregateWindow(every: task.every, fn: mean, timeSrc: "_start", createEmpty: false)
    |> to(bucket: "1hDaten", org: "Verlinden")
```

**Comment by overlinden** [comment]
@sanderson Thank you for your quick reply and suggestion of the `timeSrc` parameter. I will check this out today in the afternoon.
To have a clean downsampling I will set the `_stop` parameter in the `range()` statement to `now()` and also set the  `timeSrc` parameter within the `aggregateWindow()` statement.

But what I do not understand why the behavior in the query explorer seems to be different than in the task script?

**Comment by sanderson** [comment]
>To have a clean downsampling I will set the `_stop` parameter in the `range()` statement to `now()` and also set the `timeSrc` parameter within the `aggregateWindow()` statement.

The `_stop` parameter in `range()` defaults to `now()`, so you don't really need to explicitly set it.

> But what I do not understand why the behavior in the query explorer seems to be different than in the task script?

What different behavior are you seeing between the task execution and running the query in the Data Explorer?

**Comment by sanderson** [comment]
> Can you explain why it is set to 2024-04-08T04:01:00.000Z instead of 2024-04-08T04:00:00.000Z? As the task is executed hourly it should have 2024-04-08T04:00:00.000Z as `__start` and 2024-04-08T05:00:00.000Z and `__stop`.

I'm not sure. This aggregation is happening on the Grafana side.

**Comment by overlinden** [comment]
No, it is not on grafana side. It is purely influx.
The task is executed every 1h:
```
option task = {name: "Raumklima Downsample 1h", every: 1h}

// Datenquelle
data =
    from(bucket: "Livedaten")
        |> range(start: -task.every)
        |> filter(fn: (r) => r["_measurement"] == "Raumklima")

// Berechnung Mittelwerte
data
    |> filter(
        fn: (r) =>
            r["_field"] == "RelLuftfeuchtigkeit" or r["_field"] == "TemperaturInC" or r["_field"]
                ==
                "TaupunktInC" or r["_field"] == "Schimmelneigung",
    )
    |> aggregateWindow(every: task.every, fn: mean, timeSrc: "_start", createEmpty: false)
    |> to(bucket: "1hDaten", org: "Verlinden")
```

As is use `timeSrc: "_start"` now I expect the aggregated values to be written each hour. But if I query the 1hDaten bucket the aggregated values are written with one minute offset:
![Bildschirmfoto vom 2024-04-09 19-18-14](https://github.com/influxdata/influxdb/assets/5543041/9da1ae9d-aa90-4dc2-a110-e85ba54b6c12)

When I execute the aggregation query in the data explorer the `__time` column is correctly aligned to full hours:
![Bildschirmfoto vom 2024-04-09 19-24-03](https://github.com/influxdata/influxdb/assets/5543041/0bb800cc-5b35-48c8-b64a-5a0e76b1a60a)

**Comment by overlinden** [comment]
@sanderson do you have any idea?

**Comment by rgerrits** [comment]
> No, it is not on grafana side. It is purely influx. The task is executed every 1h:
> 
> 
> As is use `timeSrc: "_start"` now I expect the aggregated values to be written each hour. But if I query the 1hDaten bucket the aggregated values are written with one minute offset

Which query were you using to confirm the data in 1hDaten?
If that was just a quick query builder view, then it would have added aggregateWindow line, that could alter the _time that you see.

I thought I had the same issue, until I used the Script Editor to change my viewing query and removed the aggregateWindow
