### ISSUE TITLE
Unable to Connect Grafana to InfluxDB Instance After Update to v2.7.6

### ISSUE THREAD

**Issue by tsfuchs** [influxdata/influxdb#24934]
Since the update to v2.7.6, the connection from Grafana to the InfluxDB instance for my ioBroker is no longer functional. Prior to this update, there were no issues. Grafana displays the following error message:
"InfluxDB returned error: error reading influxDB"

In the InfluxDB log, the following entries are recorded:

```
Apr 22 03:02:31 grafana grafana[316]: logger=tsdb.influxdb endpoint=checkHealth pluginId=influxdb dsName=InfluxDB dsUID=B1v47qAnz uname=admin t=2024-04-22T03:02:31.565181942+02:00 level=warn msg="Error performing influxdb healthcheck" err="InfluxDB returned error: "
Apr 22 03:02:31 grafana grafana[316]: logger=context userId=1 orgId=1 uname=admin t=2024-04-22T03:02:31.565273858+02:00 level=info msg="Request Completed" method=GET path=/api/datasources/uid/B1v47qAnz/health status=400 remote_addr=192.168.55.61 time_ms=81 duration=81.57891ms size=79 referer=http://192.168.55.14:3000/connections/datasources/edit/B1v47qAnz handler=/api/datasources/uid/:uid/health status_source=server
```

After downgrading to v2.7.5, everything works perfectly again.

## Questions
- Has anything changed in this context that could cause these issues?
- Does anyone have any ideas on what the problem might be?

## Additional Information
- InfluxDB version: v2.7.6
- Grafana version: v10.4.2
- Operating System: Debian 12.5

**Comment by davidby-influx** [comment]
- Perhaps the upgrade invalidated your token.  If you recreate your data source in 2.7.6, do you get the same error?
- Can you reach the health endpoint via `curl`?

**Comment by tsfuchs** [comment]
As far as I understand it, Grafana uses the v1 API with basic auth without token for connecting to InfluxDB via the InfluxQL protocol. At least, there is no way to pass a token anywhere. In the how-to guide for ioBroker/Grafana/InfluxDB from a year ago, it was explained that there is a dedicated v1 user who authenticates from Grafana to InfluxDB without a token.

**Comment by Debilski** [comment]
I am using an older version of https://github.com/sensu/sensu-influxdb-handler (I suppose I must have activated the influx v1 layer for this at some point) to submit metrics to influxdb and it also failed on v2.7.6:

    Error: {"code":"unauthorized","message":"Unauthorized"}

Not sure if and how this error originates in influxdb though. Downgrading to v2.7.5 ‘solved’ the problem here as well.

**Comment by Debilski** [comment]
Update: As the only big change in v2.7.6 was new password rules, I updated the password (the old one was only internally used and weak) and now it runs without problem.

**Comment by tsfuchs** [comment]
how do i change the "old" users?
when I make a `influx user list` then I see only the admin user, not the v1 user which I use for connecting from grafana.

**Comment by Debilski** [comment]
`influx v1 auth list` and then update it with `influx v1 auth set-password --id XXX` with the ID according to the first column.

**Comment by tsfuchs** [comment]
ah, thank you very much.
After setting a newer more secure password, the new 2.7.6 now also works with grafana.

**Comment by davidby-influx** [comment]
This is, at heart, a Grafana issue, because it is not displaying the error from InfluxDB that the password length is too short.

**Comment by Jalle19** [comment]
Don't know why this was closed, it's clearly a bug. All existing weak passwords stopped working after upgrading to 2.7.6. I only found out by chance after I tried to change the password to the same as it was and got an error message about it having to be minimum 8 characters.

**Comment by tsfuchs** [comment]
Above all, the changelog states, as far as I remember, that an option has been added to require strong passwords. Although I hadn't enabled this option, strong passwords were still secretly enforced. Silently invalidating valid passwords without any notification is, in my opinion, very poor programming practice. But it's free, so what can you expect. Of course, as a company, I certainly wouldn't pay license fees for software that finds such behavior acceptable.

**Comment by Jalle19** [comment]
The new optional strong passwords feature seem to be related to enforcing certain complexity rules in addition to a minimum length.

Either way, absolutely nowhere does it say that existing passwords will be invalidated.

**Comment by tsfuchs** [comment]
Okay, even worse. I couldn't find any mention of an adjustment to the minimum length in the changelogs at all. And the fact that valid passwords suddenly become invalid from one version to the next is unacceptable to me.
