### ISSUE TITLE
"influx delete" on Serverless: No feedback from CLI and HTTP API about unsupported operation

### ISSUE THREAD

**Issue by NorbNorb** [influxdata/influxdb#24947]
## Describe Development Experience Issue:

I'm using InfluxDB Serverless, booked via AWS. It took me a long time to find out that I can't delete data from my Serverless instance. It's described somewhere in the Serverless documentation but I got a non-negative feedback when executing my _delete_ commands via the CLI and HTTP endpoint.

### Steps to reproduce:

1. Use a Serverless instance. (In my case from AWS)
2. Define a bucket and put in some test measurements, like _temperature_.
3. Execute the following command in your Terminal (or use the CLI command):

```
  curl --request POST 'https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2/delete?bucket=MYBUCKET' \
  --header 'Authorization: Token MYVERYLONGTOKEN' \
  --header 'Content-Type: application/json' \
  --data '{
    "start": "2024-01-01T00:00:00.000Z",
    "stop": "2024-02-01T00:00:00.000Z",
    "predicate": "_measurement=\"temperature\""
  }'

```

### Desired result:

**Really desired: Successful execution, even on Serverless!**
Not desired but causing a lot less frustration: React with the appropriate HTTP error code and include some error message, like saying this operation is not supported on Serverless.

### Actual result:
The HTTP endpoint responds with HTTP code 204 (No Content). In case you put in an error like a wrong bucket name or a wrong token, you will receive an error. So the non-negative result implies to me that the command should have been executed successfully.

## Hardware Environment:
https://eu-central-1-1.aws.cloud2.influxdata.com

**Comment by philjb** [comment]
Commenting with docs links for future readers: 

On the docs landing page, it explains new serverless accounts are v3 https://docs.influxdata.com/influxdb/cloud-serverless/.

Here are the docs about delete being disabled in v3: https://docs.influxdata.com/influxdb/cloud-serverless/write-data/delete-data

**Comment by philjb** [comment]
Thanks for your report: this has been fixed with an internal pr; the change should be out by tomorrow, if not already.

**Comment by NorbNorb** [comment]
Thanks for the quick response and the fix. I can confirm that the CLI now provides understandable feedback as expected.
