### ISSUE TITLE
fill(previous) does not really get previous value

### ISSUE THREAD

**Issue by paaland** [influxdata/influxdb#2496]
fill(previous) works only on the current time span (the where statement). I expected it to use the previously logged value at or before the current time span.

Say I have the value 100 logged at 2014-12-31
And the value 50 logged at 2015-01-02

The I perform the query:

select value from someSeries where time > '2015-01-01' group by time(24h) fill(previous)

It returns
2015-01-01 null
2015-01-02 50
2015-01-03 50
2015-01-04 50
and so on

I would expect it to return 100 as the value for 2015-01-01 when specifying fill(previous) even though the value 100 was logged outside of the time scope.

In other historian db's you have the notion of "include bounds" which will include the last value before as well as the first value after your specified time range. These can be used to fill in manually.

Very useful when working with devices that only logs new data points on actual change. It can be quite large gaps without any data logged. When viewing the data I don't want "holes" in the series.

**Comment by beckettsean** [comment]
Ported from comment on #1925. Thanks, @paaland!,

**Comment by jsternberg** [comment]
Closing this in favor of the more recent #5943.
