### ISSUE TITLE
Unable to gather

### ISSUE THREAD

**Issue by sfs325** [influxdata/influxdb#24993]
Dear Indluxdb,

I do not know how to reporduce this error in a different computer but you can see it in the next picture.

![image](https://github.com/influxdata/influxdb/assets/11979894/af96bdeb-d3be-47c0-9324-0d89290f613b)

System works perfectly but this errors bothers me as it is gennerated every minute polluting me my logs.

**Comment by philjb** [comment]
You have a failing "scraper" - the log message gives the scraper name. I'd guess the full error gives more detail about why it is failing. here are the scraper docs: https://docs.influxdata.com/influxdb/v2/write-data/no-code/scrape-data/
