### ISSUE TITLE
Write data from a long time ago into TSM

### ISSUE THREAD

**Issue by yjant** [influxdata/influxdb#25024]
Hello, I hava some questions about write and query TSM.
 `To efficiently compact and store data, the storage engine groups field values by series key, and then orders those field values by time` 
So the data in  TSM files ordered by time, my confusion is  what happens if a data with a timestamp from a long time ago
 write to influxdb, it will cause the TSM file reorder to put this data to current position ?  or just append to the TSM file, and if so, how to find this data  efficiently,

**Comment by lifei64** [comment]
如果是删除分片中的数据，会执行很慢，应该是在做重排序吧，你们的环境是啥样的啊？有空交流下，我碰见了内存占用的问题

**Comment by davidby-influx** [comment]
Data with past dates  will be indexed when written, and compaction will eventually merge TSM files.
