### ISSUE TITLE
Replace use of `std` `HashMap` with `hashbrown`

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#25088]
There are several places throughout the code where [`hashbrown`](https://docs.rs/hashbrown/latest/hashbrown/)'s [`HashMap`](https://docs.rs/hashbrown/latest/hashbrown/struct.HashMap.html) would benefit us. Namely, for its [`entry_ref` API](https://docs.rs/hashbrown/latest/hashbrown/struct.HashMap.html#method.entry_ref) which provides the same as the standard `entry` API, but allows passing the key by reference.

Here are a couple of examples:

https://github.com/influxdata/influxdb/blob/2ddef9f8da1a0e23106bc190c641458af049435d/influxdb3_write/src/write_buffer/buffer_segment.rs#L345-L361

https://github.com/influxdata/influxdb/blob/2ddef9f8da1a0e23106bc190c641458af049435d/influxdb3_write/src/write_buffer/table_buffer.rs#L463-L468

https://github.com/influxdata/influxdb/blob/2ddef9f8da1a0e23106bc190c641458af049435d/influxdb3_write/src/write_buffer/buffer_segment.rs#L394-L415

**Comment by LorrensP-2158466** [comment]
can i try this one?

**Comment by hiltontj** [comment]
Hey @LorrensP-2158466 - sure! You are welcome to try this one. Please keep in mind, you will need to [read, understand, and sign InfluxData's CLA](https://www.influxdata.com/legal/cla/) in order for your PR to be accepted.

**Comment by LorrensP-2158466** [comment]
Yes, I did! Do I need to prove I did it in my PR, or do you guys check that?

**Comment by hiltontj** [comment]
> Do I need to prove I did it in my PR

Nope! There is a checkbox in the default PR template as a reminder for you and for you to indicate that you signed it, but we will check it in the back-end.

**Comment by LorrensP-2158466** [comment]
I also have some questions:
- should every occurrence of `std::HashMap` be replaced with `hashbrown::HashMap` or only where the `entry_ref` API can be used?
- you're last example shows `!self.data.contains_key(...)` but this is a BTreeMap, should I replace every `BTreeMap` with `hashbrown::HashMap`?

**Comment by hiltontj** [comment]
> Should every occurrence of std::HashMap be replaced with hashbrown::HashMap or only where the entry_ref API can be used?

I would stick to the places where the `entry_ref` API is needed for now.

> You're last example shows !self.data.contains_key(...) but data is a BTreeMap. Should I also replace every BTreeMap with hashbrown::HashMap where we can use the entry_ref API?

Ah, thanks for catching that. I will remove that from the description. We definitely don't want to replace `BTreeMap`s with `HashMap`s.
