### ISSUE TITLE
verifying module: checksum mismatch

### ISSUE THREAD

**Issue by Shnitzelil** [influxdata/influxdb#25129]
Trying to run go mod download and I'm getting this error
C:\scm\my\pro>go mod download
go: github.com/influxdata/influxdb@v1.11.5: verifying module: checksum mismatch
        downloaded: h1:no0nKPSzKkrmEbR6hAsw2JMye9Q0AIrlyR9sxj0M8ro=
        sum.golang.org: h1:+em5VOl6lhAZubXj5o6SobCwvrRs3XDlBx/MUI4schI=

Any idea?

**Comment by darren-bell-optiva** [comment]
Hi @Shnitzelil 
How did you handle this? I am having a similar issue.
Thanks

**Comment by Shnitzelil** [comment]
> Hi @Shnitzelil How did you handle this? I am having a similar issue. Thanks

I think I ran this command line
`go clean -modecahce`
