### ISSUE TITLE
Unable to create database in influxDB v3

### ISSUE THREAD

**Issue by anshul-raman** [influxdata/influxdb#25130]
## Describe Development Experience Issue:

 I want to test some functionality in influxdb v3 however i'm not able to create a database. The query command expects a dbname flag, however database is not present.

**Comment by hiltontj** [comment]
@anshul-raman - InfluxDB is schema-on-write, so you first need to use the `influxdb3 write` command to write some lines of line protocol from a file into the server. This will create the database which you can then query from using the `influxdb3 query` command.
