### ISSUE TITLE
Write without using file in influxdbv3

### ISSUE THREAD

**Issue by anshul-raman** [influxdata/influxdb#25135]
Hi, I want to do some performance tests in influxdb3. To write data in influxdb3, write command only supports --file flag. The max size of the file can be 10485760bytes. 
How can I insert data one record at a time from the client ? Or is this functionality not supported yet ?

**Comment by hiltontj** [comment]
@anshul-raman - the project is still in an early development phase, so there are options, but they are not well documented yet:
* use the `influxdb3 write` command, with a file that has a single line in it
* use the Rust client in some custom Rust code, i.e., [`influxdb3_client`](https://github.com/influxdata/influxdb/tree/2609b590c93309890fcf53b9637ecb9329f75c0b/influxdb3_client)
* use the HTTP API directly, by sending `POST /api/v3/write_lp`

Note, that there is also a load generation tool in [`influxdb3_load_generator`](https://github.com/influxdata/influxdb/tree/2609b590c93309890fcf53b9637ecb9329f75c0b/influxdb3_load_generator) which is a separate binary that can be used to run a write and/or query load against a running `influxdb3` server, and record the write/query performance, as well as system stats to a set of CSV files, which can then be analyzed using a provided [python application](https://github.com/influxdata/influxdb/tree/2609b590c93309890fcf53b9637ecb9329f75c0b/influxdb3_load_generator/analysis).

**Comment by pauldix** [comment]
I should mention that it's quite premature to run performance tests at this time. I'm not sure how much value you or we would derive from them as there are many things that are going to change between now and whenever we release the alpha build.

**Comment by anshul-raman** [comment]
@hiltontj Got it, thanks for the response.
