### ISSUE TITLE
Where clause does not return any rows in influxDB v3

### ISSUE THREAD

**Issue by anshul-raman** [influxdata/influxdb#25145]
## Describe Development Experience Issue:

Hi, I have added some data to the influxDB v3, however when I try to query it, influxDB does not return any rows. 

Here you can see two records are present, but when I query using where clause, no rows are returned. 

![image](https://github.com/user-attachments/assets/bbf2cd3f-4d33-4db9-b541-c5c722d10a01)

**Comment by hiltontj** [comment]
@anshul-raman - I believe that the qualified syntax you are using in the where clause is not valid InfluxQL, i.e., `transactions.receiverID`. You should either just use `receiverID`, or change the query language to `--lang sql`.
