### ISSUE TITLE
Can not start 3.3.0.0 on Amazon Linux 2023, but 2.6 works fine.

### ISSUE THREAD

**Issue by eric-yq** [influxdata/influxdb#25179]
Hi all,

I am user of AWS cloud, my instance type is **c7g.4xlarge(Graviton3 CPU, aarch64)** with OS **Amazon Linux 2023**.

I can build 2.6.0.34 version successfully , taosBenchmark runs well.
<img width="1376" alt="image" src="https://github.com/user-attachments/assets/d7d58bc9-20ec-49dd-a70e-0e6b2ba46dc1">

When I build 3.3.0.0 on the same instance type and OS, it shows successfully.
But failed to start taosd: 
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/0faf30eb-53cc-48f7-b3e8-f3feb9235ced">

I check logs, it show:
......
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/1a1477bf-1e91-4ad5-adf5-1f4e1c3d7057">

Can you check what should I do ?

Thanks.

**Comment by pauldix** [comment]
Looks like you're trying to build TDEngine, not InfluxDB. Might want to check there.
