### ISSUE TITLE
Add required object store prefix for hostname or other identifier

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#25216]
Data written into the object store should all be prefixed by a unique value for the host writing the data. This should be given as an argument on startup and can be any string.

Right now, data lands in the following paths:

```
/catalogs/<wal sequence number (counting back from u64::MAX).json
/wal/<wal sequence number>.wal
/snapshots/<wal sequence number (counting back from u64::MAX).json
/dbs/<db name>/<table name>/<YYYY-MM-DD>/<HH-MM>/<wal sequence number>.parquet
```

Those paths should all start with some prefix that uniquely identifies the host writing that data in. So:

```
<host identifier prefix>/catalogs/<wal sequence number (counting back from u64::MAX).json
<host identifier prefix>/wal/<wal sequence number>.wal
<host identifier prefix>/snapshots/<wal sequence number (counting back from u64::MAX).json
<host identifier prefix>/dbs/<db name>/<table name>/<YYYY-MM-DD>/<HH-MM>/<wal sequence number>.parquet
```

**Comment by hiltontj** [comment]
Did you have any thoughts on how the identifier is managed? i.e., by the binary itself or externally.

It would be easy to have the identifier passed in as an arg to the binary (externally managed).

The binary could generate a UUID, a name using the [`names` crate](https://github.com/fnichol/names), or in the cloud use meta data API to get an instance ID (internally managed). In the UUID/name case you would then need to re-attach to that value on restart, so I guess an arg to the binary is necessary either way.

**Comment by pauldix** [comment]
With the open source build, it'll just be an arg to the binary on startup. Without the argument, there'd be no way to look up the name. With Pro, it could be tied to the license that they're issued so the license they provide on startup would have it. Either way, the identifier is coming from an external source.
