### ISSUE TITLE
Writes can be lost during snapshot process

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#25277]
I found an issue with the snapshotting process where writes that land in a WAL file containing a snapshot are lost on server restart.

There is a reproducer for this here: https://github.com/influxdata/influxdb/pull/25276

## TL;DR

I think the snapshot tracker is taking the wrong number of WAL periods in the snapshot when the condition for doing a snapshot is met.

## Investigation

What seems to be happening is: a write comes in, the WAL gets flushed, and the conditions are met to trigger a snapshot here: https://github.com/influxdata/influxdb/blob/3f7b0e655c29fa6dfcdd2db22c813a7fba9f920b/influxdb3_wal/src/object_store.rs#L192-L200
i.e., `snapshot` is `Some((SnapshotInfo, OwnedSemaphorePermit))` where `SnapshotInfo` contains the `WalPeriod` that is being created on the current flush interval.

The logic for producing the `SnapshotInfo` in the `SnapshotTracker` is taking _all_ of the tracker's WAL periods here (see line 79): https://github.com/influxdata/influxdb/blob/3f7b0e655c29fa6dfcdd2db22c813a7fba9f920b/influxdb3_wal/src/snapshot_tracker.rs#L66-L90

I think that it should only be taking _all but the last WAL period from the tracker_.

Where the problem then arises is, after the WAL file is saved to object store, the `WalFileNotifier` is notified [here](https://github.com/influxdata/influxdb/blob/3f7b0e655c29fa6dfcdd2db22c813a7fba9f920b/influxdb3_wal/src/object_store.rs#L257), which ultimately calls the `QueryableBuffer::buffer_contents_and_persist_snapshotted_data` method: https://github.com/influxdata/influxdb/blob/3f7b0e655c29fa6dfcdd2db22c813a7fba9f920b/influxdb3_write/src/write_buffer/queryable_buffer.rs#L139-L183

This is where data in the buffer is separated out for persistence to parquet data. Because it does that separation before buffering the current WAL period's content, the writes in the current WAL period's content end up getting buffered in memory, but do not get persisted to Parquet at that time. Therefore, although those writes would get persisted on a subsequent snapshot interval, because their WAL periods were produced by the snapshot tracker previously, then their WAL files get deleted after the snapshot is taken. So, if the server stops before that next snapshot interval, the writes are no longer durable and get lost.

**Comment by hiltontj** [comment]
**Update**: this seems to be fixed on the reproducer PR (https://github.com/influxdata/influxdb/pull/25276).

**Comment by pauldix** [comment]
Ah, yes that's definitely a bug. But I believe only in the situation where it isn't able to take a snapshot of data that isn't the entire WAL. Ideally, we have some snapshot period where we have many WAL files and we're able to snapshot roughly half of them, leaving a bunch of data in the queryable buffer because those 10m windows of time are still receiving writes.

However, if we have snapshotting set very low, we're not able to actually buffer up 10m of data so it keeps telling it we can't snapshot until the tracker forces it because we have too many WAL files backed up.

I'll look through the PR now to see if it all makes sense.

**Comment by hiltontj** [comment]
I filed https://github.com/influxdata/influxdb/issues/25282 as a follow-up to add some more realistic test scenarios.
