### ISSUE TITLE
Bug: backup failed: expected database, retention policy, and shard id in path from Linux on Windows

### ISSUE THREAD

**Issue by chengshiwen** [influxdata/influxdb#25361]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. On Windows, run `influxd backup` to backup the remote influxdb on Linux 

__Expected behaviour:__
Describe what you expected to happen.

The path is parsed correctly without error.

__Actual behaviour:__
Describe What actually happened.

```text
backup failed: expected database, retention policy, and shard id in path: rqeh6000/autogen/15
```

__Environment info:__

InfluxDB 1.x

![image](https://github.com/user-attachments/assets/949f3897-bde7-41b6-ab61-f8d6e63e8978)

**Comment by davidby-influx** [comment]
Closed by https://github.com/influxdata/influxdb/pull/25362
