### ISSUE TITLE
Send telemetry report for cpu usage and memory usage

### ISSUE THREAD

**Issue by praveen-influx** [influxdata/influxdb#25371]
This issue will cover sending cpu/memory usage to the server, along with static values covered in [issue](https://github.com/influxdata/influxdb/issues/25370)

```javascript
{
  // other values
  "cpuUtilizationPercent": 89,
  "memoryUsage": 240,
  "memoryUsagePercent": 23,
}
```

**Comment by pauldix** [comment]
For `memoryUsage` put the units at the end like `memoryUsageMB` or something like that. Given it happens once per hour, it'll need to be either a sample or an average over the hour. Could opt for a min/avg/max over the period with measurements taken every minute, but the report sent once per hour.

**Comment by praveen-influx** [comment]
```rust
    // cpu
    pub cpu_utilization_percent_min: f64,
    pub cpu_utilization_percent_max: f64,
    pub cpu_utilization_percent_avg: f64,
    // mem
    pub memory_used_mb_min: u64,
    pub memory_used_mb_max: u64,
    pub memory_used_mb_avg: u64,
```

That is what has been captured as part of [PR](https://github.com/influxdata/influxdb/pull/25380) that's been merged.
