### ISSUE TITLE
Send telemetry report for reads and writes

### ISSUE THREAD

**Issue by praveen-influx** [influxdata/influxdb#25372]
This issue should cover specifically the reads and writes and also establish the JSON payload that would have to be reported. Reporting stats like min, max, avg for a period (say 1h) sampled at 1 min interval is preferable.

TODO: sample JSON

**Comment by pauldix** [comment]
We'll want to capture:
* writeRequestsPerMin
* writeLinesPerMin
* writeMBPerMin
* queryRequestsPerMin

And the min and max. The ones above would be the average over the hour long report interval.

**Comment by praveen-influx** [comment]
@pauldix - Should a write request that fails validation be included in the counts? I'm guessing not, but I can capture them as well if needed.

**Comment by pauldix** [comment]
probably not
