### ISSUE TITLE
Make the parquet cache configurable from the CLI

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#25395]
The parquet cache should have the following configuration option in the `influxdb3 serve` CLI:
* `--parquet-memory-cache-size`: memory capacity of the cache in bytes (default 1GB)

Other possible options could include:
* `--prune-percent`: number from 0-100 indicating how many cache entries are evicted during a prune (default 10)
* `--prune-interval`: interval on which cache is checked and pruned if it exceeds capacity (default 10ms)

However, I am hesitant to expose these to the user for now, since the cache implementation may change and these become irrelevant. Might be reasonable for us to hard-code defaults for now, and if these turn out to be the correct tuning knobs, then we can include them in the CLI.

**Comment by hiltontj** [comment]
@pauldix - would the cache be enabled by default?

After https://github.com/influxdata/influxdb/pull/25411, the cache is optional in the write buffer, so it is easy to turn it on (or off) by default.

My thinking is that we could either:
1. turn it on by default and either give it some arbitrary size (1GB), or calculate based on available memory, with a `--disable-cache` option to turn it off
2. turn it off by default and turn it on only if the user specifies the capacity, e.g., `--parquet-cache-size` option

**Comment by pauldix** [comment]
Maybe on by default with 1GB? Then an option to disable it makes sense.
