### ISSUE TITLE
https service not starting after enabling tls strict ciphers

### ISSUE THREAD

**Issue by wargamez** [influxdata/influxdb#25401]
lvl=error msg="Failed https service" log_id=0rroPim0000 error="http2: TLSConfig.CipherSuites is missing an HTTP/2-required AES_128_GCM_SHA256 cipher (need at least one of TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 or TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256)."

**Comment by philjb** [comment]
I think you may be running an older version of influxd and/or built it yourself with modified list of ciphers. Please upgrade and the error should resolve.

The error is from http2

https://github.com/golang/net/blob/f88258d67e0f0f144c79964ca05bb81d51ee8411/http2/server.go#L271-L286

but influxd 2.7 includes the required ciphers in its list here: 
https://github.com/influxdata/influxdb/blob/f302d9730c3c66577bea7bc7199cfae773bf308e/cmd/influxd/launcher/launcher.go#L1156-L1166
