### ISSUE TITLE
cannot find the file directory for a certain  bucket.

### ISSUE THREAD

**Issue by citizen-z1** [influxdata/influxdb#25402]
system version: centos 7
influxdb version: OSS v2.7.6
I created a new bucket called "measurement_test" on a web page, 
![image](https://github.com/user-attachments/assets/972f4ee2-54f1-46fb-a40f-868a2c93f3ce)

but the "bucket" directory on the server does not show this new bucket. It can normally display other buckets.
![image](https://github.com/user-attachments/assets/89b1e52e-5de4-4cb1-a182-a36aa2d0993a)

And I can also query it using an HTTP request to /api/v2/buckets, and it returns the bucket normally. I can also write data to this bucket normally.

**Comment by philjb** [comment]
what was the resolution @citizen-z1? In case someone else encounters this issue?
