### ISSUE TITLE
Add option to influxd to flush WALs on shutdown

### ISSUE THREAD

**Issue by gwossum** [influxdata/influxdb#25422]
Introduce a new CLI argument that specifies influxd should flush or snapshot all its WALs prior to completing shutdown. When this flag is set, influxd will perform cache snapshots on shutdown, which will result in the WAL files being written to TSM files and then deleted.

**Comment by davidby-influx** [comment]
Closed by PR on 9 October 2024

**Comment by michalsykora** [comment]
does this mean, when the config contains: storage-wal-flush-on-shutdown: true

systemctl stop influxdb will stop the daemon gracefully after saving the WAL first?

**Comment by davidby-influx** [comment]
The cache will be flushed to a TSM file, and the WAL, which contains the same data as the cache, will be deleted.

See here for more explanation of the cache, WAL, and their relationship to one another: [WAL](https://docs.influxdata.com/influxdb/v2/reference/internals/storage-engine/#write-ahead-log-wal)
