### ISSUE TITLE
UI: cannot change retention policy to forever 

### ISSUE THREAD

**Issue by wolfgangr** [influxdata/influxdb#25467]
__Steps to reproduce:__

1. create a Bucket in the UI with 7 days retention
2. try test write with old data by api, get "points beyond retention policy"
3. try to chage retention policy in UI: select "never" and hit "save"

__Expected behaviour:__
- Displayed retention policy changes to "forever"  
- I can write old data

__Actual behaviour:__
- After "save", it still displays "retention 7 days"  
- cannot write old data
- reopening "Settings" dialogue, it still displays 7 days
- I can, however, change e.g. to 360 days, just not to forever
- delete and recrate bucket, spoils api-token

__Environment info:__

* 2.7.10-1 Installation from repo 
* `uname -srm` : `Linux 6.1.0-23-amd64 x86_64`
* OS: plain debian 12.7
* Browser: Firefox 102.8.0esr 

__Config:__
no change I'm aware of

**Comment by philjb** [comment]
I think your report is the same as this one: https://github.com/influxdata/influxdb/issues/23049

* https://github.com/influxdata/influxdb/issues/23049

**Comment by wolfgangr** [comment]
yes, sorry, did not find that in my search

**Comment by philjb** [comment]
no worries - thanks for commenting and closing this one.
