### ISSUE TITLE
Switch field in the influxdb3_wal crate to use ColumnId instead of a Arc<str>

### ISSUE THREAD

**Issue by mgattozzi** [influxdata/influxdb#25461]
This is a follow up to #25388. We want to use ColumnIds instead of Arc<str>. This is the relevant line to change, with any tests and code that need to be changed as a result.

https://github.com/influxdata/influxdb/blob/219fc168ead075cebe64b7559345e497340d0b12/influxdb3_wal/src/lib.rs#L574

**Comment by mgattozzi** [comment]
@pauldix this is turning out to not be a simple change and has far reaching implications. For instance:

- The [BufferIndex](https://github.com/influxdata/influxdb/blob/ead6d27c5f10720d09f8c8e7e63cbcba592fcd03/influxdb3_write/src/write_buffer/table_buffer.rs#L475-L478) depends on the name of the column, especially when working with [Exprs](https://github.com/influxdata/influxdb/blob/ead6d27c5f10720d09f8c8e7e63cbcba592fcd03/influxdb3_write/src/write_buffer/table_buffer.rs#L500-L519) which are from Datafusion
- A lot of the times we need names, it's because of Datafusion
- LastCache expects names for lookups, especially when interfacing with, you guessed it, the Datafusion Schema type

I think we'd spend more time doing a conversion lookup then just having an Arc<str> everywhere. I'm not sure the ColumnId makes as much sense compared to just using the name of the field. We'd end up having to pass the ColumnId and the name around in many places.

We could still try to make it work, but this is not a single day task like I had originally hoped for and I'll likely need to pick this up after vacation or we reconsider the value of ColumnId at all. Even the wrapper TableSchema is proving hard to pass around, when so much of the code really only cares about a schema::Schema type. I'm worried we're adding a lot of overhead for very little gain here.

**Comment by pauldix** [comment]
I think it's worth doing mainly because that goes into the wal constantly, many more times than you'd do the lookup for queries. Ideally the last cache and queryable buffer would keep the data indexed by ID too. Just doing conversion on the read side when pulling data out.

Definitely not urgent so it can wait a while.

**Comment by mgattozzi** [comment]
Okay I'll pick this up when I get back from vacation then!
