### ISSUE TITLE
Confusion regarding InfluxDB v1 OSS (1.8.10 vs 1.11.7) - which version is currently released?

### ISSUE THREAD

**Issue by florianwgnr** [influxdata/influxdb#25496]
I am using InfluxDB v1 OSS on Debian 11, with the repository set to https://repos.influxdata.com/debian

Since InfluxDB v1 OSS is discontinued, i´ve been using version v1.8.10 from 2021 for the last few years - checkout the [OSS changelog.](https://docs.influxdata.com/influxdb/v1/about_the_project/release-notes/)

Some days ago, an update to version 1.11.7 was published to the [InfluxDB OSS repository ](https://repos.influxdata.com/debian/packages/)
![grafik](https://github.com/user-attachments/assets/216c7df0-8342-4d0b-a81e-927efeb1b4bd)

and i went on to install it. It successfully updated v1.8.10 and is now running the new version: 

![grafik](https://github.com/user-attachments/assets/257c90fe-da30-4859-adf0-066e0f710137)

But this version seems to be an enterprise version, checkout the latest [enterprise changelog](https://docs.influxdata.com/enterprise_influxdb/v1/about-the-project/release-notes/)

Also, the InfluxData Downloads page shows 1.8.10 as the lastest v1 OSS version: https://www.influxdata.com/downloads/#influxdb 

This confusion leads to my question: What version am i currently running??

**Comment by sanderson** [comment]
@florianwgnr InfluxDB OSS 1.11.7 packages have been released and that is the version you’re running. The release notes and InfluxData downloads page will be updated Monday morning to reflect the release. For a preview of the release notes, you can view [this PR](https://github.com/influxdata/docs-v2/pull/5648/files#diff-f25ebe93888e98f135310a16244ddfec87d7011df6239b4d1a52a9b49595c46c) in the documentation repository.
