### ISSUE TITLE
Write validator should produce `Row` for the WAL directly

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#25512]
See https://github.com/influxdata/influxdb/pull/25495#discussion_r1826188340

That PR changed the validator to produce a `QualifiedLine` which is basically just a `Row` that hasn't had the timestamp set yet. This extra abstraction can be removed and just have the validation step produce a row directly.

**Comment by pauldix** [comment]
No reason we can't set the timestamp during validation, yeah?

**Comment by hiltontj** [comment]
Yes we can just move that step up to the validate part. It is the only special thing that is being done with the `QualifiedLine`
