### ISSUE TITLE
Issues installing debian package for influxdb 1.11.8 release

### ISSUE THREAD

**Issue by crypt1d** [influxdata/influxdb#25571]
The official images repo does not allow opening issues, so I'm reporting here. Apologizes if this is not the right place.

__Steps to reproduce:__
- Add repository `deb https://repos.influxdata.com/debian stable main` to apt sources
- Update apt cache
- Try to install influxdb

__Expected behaviour:__
Influxdb installs without issues as it does with the previous version (1.11.7)

__Actual behaviour:__
Installation throws an error related to `useradd` syntax:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  influxdb
0 upgraded, 1 newly installed, 0 to remove and 29 not upgraded.
Need to get 0 B/26.6 MB of archives.
After this operation, 115 MB of additional disk space will be used.
(Reading database ... 65788 files and directories currently installed.)
Preparing to unpack .../influxdb_1.11.8-1_amd64.deb ...
useradd: invalid user ID '-m'
dpkg: error processing archive /var/cache/apt/archives/influxdb_1.11.8-1_amd64.deb (--unpack):
 new influxdb package pre-installation script subprocess returned error exit status 3
Errors were encountered while processing:
 /var/cache/apt/archives/influxdb_1.11.8-1_amd64.deb
```

__Environment info:__

Ubuntu 22.04.5 LTS
Linux 6.8.0-1015-aws x86_64

**Comment by pandafy** [comment]
The `preinst` script has the following difference:

```diff
# diff influxdb-1.11.7/preinst influxdb-1.11.8/preinst 
8c8
<     useradd --system -U -M influxdb -s /bin/false -d "${DATA_DIR}"
---
>     useradd --system -u -m influxdb -s /bin/false -d "${data_dir}"
```

The `-u` option specifies the user ID (`uid`) of the user, while the `-U` option creates a group with the same name as the user.

Is this change intentional? It seems all the uppercase variable names have been switched to lowercase, which might suggest it was unintentional.

**Comment by devanbenz** [comment]
> I extracted the control information of `influxdb-1.11.7` and `influxdb-1.11.8` packages using `dpkg -e`
> 
> The `preinst` script has the following difference:
> 
> ```diff
> # diff influxdb-1.11.7/preinst influxdb-1.11.8/preinst 
> 8c8
> <     useradd --system -U -M influxdb -s /bin/false -d "${DATA_DIR}"
> ---
> >     useradd --system -u -m influxdb -s /bin/false -d "${data_dir}"
> ```
> 
> The `-u` option specifies the user ID (`uid`) of the user, while the `-U` option creates a group with the same name as the user.
> 
> Is this change intentional? It seems all the uppercase variable names have been switched to lowercase, which might suggest it was unintentional.

Hi @pandafy this is not intentional. We are looking in to what caused this change. This release is not a major release and as thus please feel free to continue operating with 1.11.7. We will be sure to update this thread once the resolution is in place. Thank you.

**Comment by bnpfeife** [comment]
@crypt1d @pandafy @devanbenz 

Hey, I can confirm that those changes were unintentional. I've uploaded 1.11.8-2 packages that revert this change.
