### ISSUE TITLE
feat performance: upgrade cespare/xxhash to v2; refactor Cache.storer.write() to accept a string key instead of []byte

### ISSUE THREAD

**Issue by philjb** [influxdata/influxdb#25607]
Tasks

* upgrade cespare/xxhash from v1 to v2 which includes some performance changes (when working with the go complier) and assembly versions of Sum64
* The Cache storer interface has a `write` method that wants a byte slice key, but the key is only ever read in all implementations. When engine.WriteMulti calls into the cache to write, it has a string key already but is converting it to a byte slice to do the write. This byte slice allocates when we don't need to if a string was used all the way down that call path. The ask is to change that to avoid unnecessary allocations. It will need a new `getPartitionStringKey` method like below. All the storer interface methods could be updated to use string keys instead of byte slices but the main value is in the write method as it is the most used. 
    * see https://github.com/influxdata/influxdb/blob/c433342830a51839a8fd38e41201a1825114d16f/tsdb/engine/tsm1/cache.go#L150-L149

```
func (r *ring) getPartitionStringKey(key string) *partition {
	return r.partitions[int(xxhash.Sum64String(key)%uint64(len(r.partitions)))]
}
```

**Comment by devanbenz** [comment]
Closing this - cherry picks are in to 1.x/2.x
