### ISSUE TITLE
Remove /api/v3/write 

### ISSUE THREAD

**Issue by mgattozzi** [influxdata/influxdb#25611]
Problem
-----
Currently we have the write API with v3 but with the changes in https://github.com/influxdata/influxdb/pull/25596, there's no real advantage to having this API for now.

Proposed solution
-----
We want to just remove this for now ahead of our first public release as we don't want to be committed to this API and have users depend on it. We can add this API back later if we want to do something that's not line protocol oriented or we want something else.

Alternatives
-----
None as we've discussed in #25596 that we want to get rid of this

Additional context
-----
The entry point for this API is here:
https://github.com/influxdata/influxdb/blob/f23aa0d4601225cd1f0e95521cbcd894fd75ceb1/influxdb3_server/src/http.rs#L1379

This line will need to be removed as well as the function itself:
https://github.com/influxdata/influxdb/blob/f23aa0d4601225cd1f0e95521cbcd894fd75ceb1/influxdb3_server/src/http.rs#L432-L436

There shouldn't be much else needed beyond fixing up some tests/removing them possibly and the compiler should guide that pretty easily.

**Comment by hiltontj** [comment]
We will need upstream issues in IOx to remove the related code from `influxdb3_core` as well. Namely,
* the [`v3` module](https://github.com/influxdata/influxdb3_core/blob/6fcbb004232738d55655f32f4ad2385523d10696/influxdb_line_protocol/src/v3.rs) in the `influx_line_protocol` crate along with the `"v3"` feature flag in that crate
* the `"v3"` related features in the [`schema` crate](https://github.com/influxdata/influxdb3_core/tree/6fcbb004232738d55655f32f4ad2385523d10696/schema)

I think that is the extent of it, but anything used for this API is behind a `"v3"` feature flag so should be easy to root out if not included above. I am happy to go and open that issue upstream.

**Comment by hiltontj** [comment]
Related issue in IOx: https://github.com/influxdata/influxdb_iox/issues/12971
