### ISSUE TITLE
Influx 2.7.11 - Not able to log in / connect after restart

### ISSUE THREAD

**Issue by dieterlind** [influxdata/influxdb#25628]
Today my watchtower updated my influxdb installation.

Since this time neither iobroker is not able to connect nor I can connect via port 8086.
I see an error in the log file:
`error Unable to gather {"log_id": "0tLkRzyW000", "service": "scraper", "scraper-name": "new target", "error": "Get \"http://192.xxx.xxx.14:8086/metrics\": dial tcp 192.xxx.xxx.14:8086: connect: connection refused"}
`
This is somehow strange as my installation is actually running on .11:8086
Nothing running on .14.

How can I fix this issue?

Thanks!

**Comment by philjb** [comment]
hi @dieterlind - you can create a new scraper that uses the ip and port you want.

**Comment by dieterlind** [comment]
Hi! Thanks for the information. But I wasn't able to connect at all and on the CLI I wasn't able to do so.
What I did was creating a new docker and copying the data to a new volume. This worked. Afterwards I deleted the old docker and volume.
