### ISSUE TITLE
Support table creation via REST API and CLI

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#25641]
### Problem statement

Currently, `influxdb3` only supports table creation by performing a write via [one of the write APIs](https://github.com/influxdata/influxdb/blob/3a66fe0ec38ecf504c6bfa2e823804dee6515f59/influxdb3_server/src/http.rs#L1361-L1378).

This is useful and allows quick time-to-awesome; however, there may be users that would like to create their tables explicitly via a REST API or CLI command, providing the desired schema for that table.

#### Add the following REST API:
```
POST /api/v3/configure/table

{
  "db_name": <database name>,
  "table_name": <table name>,
  "tags": [
    {"name": <tag name>},
    ...
  ],
  "fields": [
    {"name": <tag name>, "type": <data type>},
    ...
  ]
}
```

* The order of `tags` is important and will be the table's series key
* The `type` for fields is one of: `int64`, `uint64`, `float64`, `utf8`, `bool`
* The database with `db_name` will be created if it does not exist

#### Add the following CLI command that leverages the above REST API:
```
influxdb3 table create --dbname <database name> --table-name <table name> --tags <comma separated list --fields <comma separated list of "name:type">
```

#### Additional requirements

* Utilize the WAL to ensure the catalog operation for creating the table (and database if relevant) is durable
* Abide by the limitations on the number of tables (and databases) that are allowed

### Alternatives considered

N/A

### Additional context

Recently, we added support to delete tables in  https://github.com/influxdata/influxdb/issues/25561. The changes needed here will be very similar to those made for that issue (https://github.com/influxdata/influxdb/pull/25572).

**Comment by pauldix** [comment]
For type, I think we should keep it specific like the underlying types: `int64`, `uint64`, `float64`, `string`, `bool`

**Comment by hiltontj** [comment]
> For type, I think we should keep it specific like the underlying types: int64, uint64, float64, string, bool

Agreed, I updated the issue description.
