### ISSUE TITLE
Should series keys always have a value?

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#25674]
#25673 fixed an issue where buffered data would cause an error if one of the series key columns wasn't present. It creates the column in the schema and then fills that column with nulls.

The question is whether we should have nulls, or if we should fill with empty strings? I believe downstream consumers of Parquet (like Iceberg) won't allow nulls in columns that are part of the primary key.

So should we always have series keys fill with empty strings? We'd also need to update the part that buffers in rows to have them fill with empty string rather than null.

#25648 reports that null values causes an error (but this might be fixed by #25673).

**Comment by hiltontj** [comment]
I think that it would be ideal if we could enforce `NOT NULL` by requiring every tag have a value in the written LP. It looks like empty strings are not allowed for tag values, since the parser uses `take_while1` (see [here](https://github.com/influxdata/influxdb3_core/blob/7eefba96954bdfb6fe69b26cd6d1fc9acd8e9160/influxdb_line_protocol/src/lib.rs#L724-L727)). So, users would not be able to write empty strings to tags that were included in the first write to the table, or in the definition on table creation.

This is a clear change from how tags are supported in previous versions of the product though, so is likely to cause frustration/push back; but we have an answer: use fields for string values that might be `NULL`.

**Comment by pauldix** [comment]
We can easily inject an empty string in the TableBuffer when the rows get put into it. We don't need to enforce it in the LP.

**Comment by hiltontj** [comment]
> We can easily inject an empty string in the TableBuffer when the rows get put into it. We don't need to enforce it in the LP.

I get that its easy to do that, I'm just wondering why not enforce the `NOT NULL` constraint during write? (and guide users to use tags as a primary key and fields for everything else).

The main reason I can think of to not enforce `NOT NULL` is that doing so would be disruptive to users who are accustomed to how tags worked in previous versions and that could be considered a breaking change for the `/api/write` and `/api/v2/write` APIs. So, maybe we would only be able to do such enforcement in the `/api/v3/write_lp` API, if at all.

Replacing `NULL` with `""` may also be unexpected and have unintended consequences for some users. In which case, it may be better to make tags nullable, and then do any `NULL` to `""` conversion downstream, as needed, for e.g., iceberg etc.

**Comment by pauldix** [comment]
There were nullable before, weren't they?

**Comment by hiltontj** [comment]
> There were nullable before, weren't they?

I believe so. The changes in #25596, specifically [here](https://github.com/influxdata/influxdb/pull/25596/files#diff-4388378be02f8ec64c1eb84d79f5befce8d2722c94ed0b15c7726169ec6c6754L809-R822), made tags part of the series key, which in turn makes them non-nullable in the IOx/Arrow Schema via [this method](https://github.com/influxdata/influxdb3_core/blob/7eefba96954bdfb6fe69b26cd6d1fc9acd8e9160/schema/src/builder.rs#L58-L70).

**Comment by pauldix** [comment]
So would there be a drawback to making it so that fields in the series key could be nullable?

**Comment by pauldix** [comment]
I put up a fix that injects `""` in #25680. I think that's the right fix for now because we're really dealing with the v1 and v2 write endpoints receiving tags.

I think when we're ready to do the real v3 write API and new data model, we'll have series key, and the members will be non-nullable, and we'll enforce that on ingest.

**Comment by pauldix** [comment]
Closing this one out now that #25680 is in.
