### ISSUE TITLE
Add metrics to track ingest

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#25689]
### Problem statement

There are no prometheus metrics to track the rate of ingest to the write buffer.

### Proposed solution

Add the following metrics:
* Lines written (`influxdb3_write_lines_total`): counter that tracks total lines written, with attributes `db` and `table` to track at individual DB/table level
* Bytes written (`influxdb3_write_bytes_total`): counter that tracks total bytes written, with attributes `db` and `table` to track at the individual DB/table level

### Alternatives considered

N/A

### Additional context

We don't need to calculate the rate in our code, as Prometheus can do that for us via the [`rate()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate).

**Comment by pauldix** [comment]
I'd also add `influxdb3_write_requests_per_second`

**Comment by hiltontj** [comment]
What level are you thinking at for that metric, the `WriteBuffer::write_lp` method, or at the HTTP router level?

**Comment by pauldix** [comment]
Ah, the existing http metrics should be enough for writes.

For the lines, the typical thing to do with Prometheus metrics is to have a counter for `influxdb3_write_lines_total` and `influxdb3_write_bytes_total` and then use the Prometheus `rate` function to calculate the rate.

**Comment by hiltontj** [comment]
> Ah, the existing http metrics should be enough for writes.
> 
> 
> 
> For the lines, the typical thing to do with Prometheus metrics is to have a counter for `influxdb3_write_lines_total` and `influxdb3_write_bytes_total` and then use the Prometheus `rate` function to calculate the rate.

Oh nice, thanks. I was kind of wondering about that... I will edit the issue.
