### ISSUE TITLE
Default config dir & data-dir

### ISSUE THREAD

**Issue by FGRibreau** [influxdata/influxdb#26]
I don't think it's a great idea to use `/tmp` as a datadir. I personally used a VM to try influxdb and could not understand why my data was going away after each reboot. Then I found the configuration file (which was not inside /etc/influxdb/ as usual in Debian/Ubuntu) and understood my mistake -__-'.

```
  "DataDir":        "/tmp/influxdb/development/db",
  "RaftDir":        "/tmp/influxdb/development/raft"
```

**Comment by kamrankausar** [comment]
Default config dir & data-dir
