### ISSUE TITLE
Capture os signal for exiting in CLI and do proper cleanup

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#2609]
Currently, if you `ctrl` + `c` to exit the CLI, it will leave the terminal in a messed up state as we didn't properly shut down liner.  We can easily capture this and shut down gracefully.

**Comment by Galser** [comment]
The same again. rigjht now with versio 0.9.6.1 under CentOS 6.7 64bit : 
> SHOW DIAGNOSTICS;
name: build                                                                                                          
-----------                                                                                                          
Branch  Build Time                      Commit                                          Version                      
0.9.6   2015-12-10T23:40:23+0000        6d3a8603cfdaf1a141779ed88b093dcc5c528e5e        0.9.6.1

**Comment by jsternberg** [comment]
This seems to work. It looks like it was fixed by 81658de.
