### ISSUE TITLE
improvement to error message for GROUP BY with too many points

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#2702]
```
> select count(value) from system_load5 where time > now() - 100w group by time(10m)
ERR: too many points in the group by interval. maybe you forgot to specify a where time clause?
```

I specified a `WHERE time` clause, but it was 100 weeks vs 10 minute buckets. I suggest updating the error message to something like:

```
ERR: too many points in the group by interval. maybe you forgot to specify a where time clause or your group by intervals are too short compared to the where time range?
```

**Comment by beckettsean** [comment]
Perhaps also some help on what is too much for the time interval.

This returns a series of aggregated points:
```
> select count(value) from system_load5 where time > now() - 99w - 1d group by time(10m)
name: system_load5
------------------
time			count
2013-07-04T22:30:00Z	
2013-07-04T22:40:00Z	
2013-07-04T22:50:00Z	
2013-07-04T23:00:00Z	
...
2015-05-29T21:50:00Z	43
2015-05-29T22:00:00Z	18
2015-05-29T22:10:00Z	43
2015-05-29T22:20:00Z	43
2015-05-29T22:30:00Z	8
```

whereas going back one extra day is too much:

```
> select count(value) from system_load5 where time > now() - 99w - 2d group by time(10m)
ERR: too many points in the group by interval. maybe you forgot to specify a where time clause?
```

694 days of 10m buckets is fine, and equates to 99,936 buckets. 695 days of 10m buckets is 100,080 buckets. Looks like 100k is the bucket limit.

Verifying:

```
> select count(value) from system_load5 where time > now() - 99w - 1d - 10h - 39m group by time(10m)
name: system_load5
------------------
time			count
2013-07-04T12:00:00Z	
2013-07-04T12:10:00Z	
...
2015-05-29T22:20:00Z	43
2015-05-29T22:30:00Z	39
```

```
> select count(value) from system_load5 where time > now() - 99w - 1d - 10h - 40m group by time(10m)
ERR: too many points in the group by interval. maybe you forgot to specify a where time clause?
```

99 weeks plus 1 day plus 10 hours plus 40 minutes is 1,000,000 minutes, which is 100k buckets of 10 minutes each. Remove one minute and the number of buckets drops to 99,999 and the query executes.

With that I propose something like the following error message:

```
 ERR: too many points in the group by interval. adjust the where clause or the group by interval to return fewer than 100k buckets.
```

**Comment by corylanou** [comment]
You are correct, 100k is the limit. https://github.com/influxdb/influxdb/blob/de77ee18969e56b447988c25c3bdc37347e3df0c/influxql/engine.go#L20

**Comment by mjdesa** [comment]
Just noticed that the query

```sql
SELECT count(value)
FROM heartrate
WHERE time < now()
GROUP BY time(1m)
```
yields

```
name: heartrate
----------------
time			count
1970-01-01T00:00:00Z
```

whereas the query

```sql
SELECT count(value)
FROM heartrate
WHERE time > now() - 99w - 2d
GROUP BY time(10m)
```

yields

```
ERR: too many points in the group by interval. maybe you forgot to specify a where time clause?
```

I would expect the first query to give a similar response. Is this incorrect?

**Comment by jsternberg** [comment]
I'm closing this since it doesn't seem valid with the new query engine. The bucket limit has a different error message and is an optional flag that people can pass to the config.

Please reopen if there's more we need to do on this. Thanks.
