### ISSUE TITLE
[0.9-R31] CLI - column and CSV output need better delineation of DISTINCT values

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#2705]
Clearly three distinct values returned on the 2nd line:
```
> select distinct(value) from myseries
{"results":[{"series":[{"name":"myseries","columns":["time","distinct"],"values":[["1970-01-01T00:00:00Z",
["1422568543","1422568543702900257 n","none"]]]}]}]}
```
It's clear in the JSON output that the distinct values over the time range are `1422568543`, `1422568543702900257 n`, and `none`

However, in the CSV or column formats the DISTINCT values are space-delimited, making it unclear that the `n` is part of the middle distinct value, not a distinct value of its own.

Three distinct values or four?
```
> format csv
> select distinct(value) from myseries
name,time,distinct
myseries,1970-01-01T00:00:00Z,[1422568543 1422568543702900257 n none]
```
Three distinct values or four?
```
> format column
> select distinct(value) from myseries
name: myseries
--------------
time			distinct
1970-01-01T00:00:00Z	[1422568543 1422568543702900257 n none]
```

**Comment by corylanou** [comment]
ah, yes.  Looks like when I detect an array I might need to "quote" things.  Good catch!

**Comment by corylanou** [comment]
@pauldix I feel like this should get re-written (flattened) like we do for the `TOP` function.  Thoughts?

**Comment by jsternberg** [comment]
I don't think this is an issue anymore now. The output of distinct has now been changed to return a row per value instead of the array it returned previously, so the output now looks like this:

```
> select distinct value from cpu
name,time,distinct
cpu,0,3
cpu,0,5
```

I'm going to close this since I don't think we need to do anything now with the new query engine.
