### ISSUE TITLE
Make DROP and DELETE queries work in cluster

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#2755]
Currently the query executor only executes these queries against the local store. They should be updated to call out to the remote data nodes to get executed in addition to the local store.

**Comment by otoolep** [comment]
Part of the work for https://github.com/influxdb/influxdb/issues/3009

**Comment by beckettsean** [comment]
@otoolep is this done?

**Comment by otoolep** [comment]
No, this is the work @dgnorton is on.

**Comment by otoolep** [comment]
@dgnorton -- this won't make 0.9.3, right? I'll push out to 0.9.4.

**Comment by dgnorton** [comment]
@otoolep no, push it to 0.9.4

**Comment by panovodv** [comment]
are you guys still working on a fix for this?
