### ISSUE TITLE
should we create a database if other parts of the statement fail?

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#2759]
```
> create database bar grant all to me
ERR: user not found
> create database bar 
ERR: database exists
```

Since the `grant` clause failed, I am not certain the database should have been created. However, when the clause is a `revoke` I would definitely expect the creation to fail. Otherwise I've made a database unintentionally less secure than intended.

```
> show users
user			admin
cluster_admin	true
foo			false
write_mydb	false

> create database foobar revoke all from foo
```
No errors and the db now exists, so this is syntactically correct.

```
> create database foobar1 revoke all from me
ERR: user not found
> show databases
name: databases
---------------
name
bar
foobar
foobar1
mon
mydb
telegraf
tivan
```
In this case the `foobar1` database was created although it shouldn't have been, at least in my expectations.

**Comment by corylanou** [comment]
I think it would be fair game in this scenario to check if the user exists BEFORE the database is attempted to be created.  This will prevent the need for us having transactions and rolling back part of a statement.

I would expect the behavior to be:

```sql
> create database foo grant all to me
ERR: user not found
```

And no database is created.

**Comment by beckettsean** [comment]
+1 for that behavior

**Comment by jsternberg** [comment]
I don't see this syntax in the parser. It appears this was possible because of the semi-colon error that has now been fixed. Since the two commands are separate, I don't think there's a reasonable way to implement this so I'm going to close this issue.

Please reopen if you feel we should still look into this.
