### ISSUE TITLE
[0.9.0-rc31] exceeding max retention policy duration gives incorrect error message

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#2762]
I'm not sure what the max allowable retention policy is (other than INF), but when trying to make an RP with a duration of 100,000 weeks I got a silly error:

```
> alter retention policy foo on mydb duration 1000000w
ERR: retention policy duration needs to be at least 1h0m0s
```
Seems like we should tell the user they've exceeded the max discrete RP rather than lie and say 100k weeks is shorter than an hour.

Note that 10,000 weeks works just fine:

```
> alter retention policy foo on mydb duration 10000w
> show retention policies mydb
name	duration	replicaN	default
default	0		1		true
foo	1680000h0m0s	1		false
```

**Comment by beckettsean** [comment]
Looks like the max RP duration is stored as a signed 64-bit integer, so the max is defined by 2^63-1 nanoseconds, which works out to ~54,000 weeks

**Comment by corylanou** [comment]
It overflows the int64:

http://play.golang.org/p/t7roIGTSiV

So it is probably erring out that it couldn't parse the int, and assumes you didn't provide a valid int.  I think clarifying the error message is the right fix.
