### ISSUE TITLE
Some services should be able to have multiple instances

### ISSUE THREAD

**Issue by renan-** [influxdata/influxdb#2785]
Hi,

I've implemented timing data harvesting for my company's website. I'm using InfluxDB and Grafana to store and display the collected data.
The data is sent over UDP and here comes the problem: with the recent refactoring, database and retention policy are service-instance-specific and cannot be specified via the new line protocol. I'd need to be able to send data to multiple databases or to the same one with a different retention policy.
This feature could be applied to other services (like collectd for instance) as it only requires some (very) minor modifications.

Thanks for your time,
Renan.

**Comment by neonstalwart** [comment]
agree.  this is part of what i was implying with https://github.com/influxdb/influxdb/issues/2278#issuecomment-101030975.  the config i was suggesting there was trying to make it possible to specify multiple instances of any of the services (http, udp etc).

**Comment by KiNgMaR** [comment]
:+1:

**Comment by jgerschk** [comment]
+ 10000 ( is that enough votes? ) -- in all seriousness though, this can be very useful, especially for udp, but I can see others being useful for others.

**Comment by beckettsean** [comment]
@otoolep isn't this fixed now that we support multiple plugin definitions?

**Comment by otoolep** [comment]
We now support multiple services for most plugins, but not for HTTP. I'm not sure this is high-priority, and doubt it will be addressed before 1.0.

**Comment by mengelmann** [comment]
I would love to be able to use multiple Collectd plugin listeners. 

Use case:
- multiple groups of servers that use Collectd to report statistics to Influxdb
- use Grafana as a dashboard, and there is an organization for each of servers' group, and each of organization has a different data source: separated Influxdb database
- each group of servers should save statistics to a separated Influxdb database

The workaround is to use graphite plugin. It allows using a different database per listener but is not aware of Collectd's typesdb.conf and requires defining templates by hand to keep Collectd measurements structure.

Maybe it will be useful to change Influxdb plugin architecture to allow multiple instances for each of them, not only selected (like graphite, udp)?

**Comment by mengelmann** [comment]
@otoolep I think that this feature is quite useful, and my PR #6090 is ready to merge. How can I help to get it merged into master?

**Comment by otoolep** [comment]
You need to chat to @jwilder now.

**Comment by mengelmann** [comment]
@jwilder we're using custom build with this PR merged and it works just fine.

**Comment by jsternberg** [comment]
I'm going to close this and rely on #6333 to track the progress for finishing this issue. Thanks.
