### ISSUE TITLE
Support for prepared statements and bound parameters

### ISSUE THREAD

**Issue by aaronjwood** [influxdata/influxdb#2926]
Hi,

Please correct me if I'm wrong but I don't see any support for prepared statements and bound parameters. I'm trying to figure out a way to prevent SQL injection when using the Go client library.

Your README talks about doing something like this:

```
q := fmt.Sprintf("select count(%s) from %s", "value", MyMeasurement)
res, err := queryDB(con, q)
``` 

My understanding is that fmt.Sprintf does not protect against SQL injection at all. Is there a way to use Go's built-in prepare http://golang.org/pkg/database/sql/#DB.Prepare or query http://golang.org/pkg/database/sql/#DB.Query so that I can bind parameters to a query?

Thanks!

**Comment by manuel-huez** [comment]
+1

**Comment by mjibson** [comment]
+1

**Comment by etcinit** [comment]
+1

**Comment by 5outh** [comment]
+1

**Comment by vikrant6** [comment]
+1

**Comment by aaronjwood** [comment]
Is this the right way to address this issue now? https://docs.influxdata.com/influxdb/v1.7/tools/api/#bind-parameters
