### ISSUE TITLE
dont penalize entire payload of points for single bad point

### ISSUE THREAD

**Issue by davidbirdsong** [influxdata/influxdb#2937]
Through process of elimination, it appears that a payload of points delivered as line protocol over both HTTP and UDP endpoints will be rejected if a single point contains a value that is an incorrect type for the measurement. This encourages me to send single points per datagram or POST which I'm sure is not good for performance.

**Comment by otoolep** [comment]
Thanks @davidbirdsong -- would rather that the offending point be dropped? Even though it would be lost?

**Comment by otoolep** [comment]
@jwilder

**Comment by davidbirdsong** [comment]
It's a tough call. With the UDP endpoint, there's no feedback to the caller, so yes.

With the HTTP endpoint, there is feedback which a silent drop would lose.

After articulating, a silent drop would bring parity between the two write endpoints, so yes?

**Comment by otoolep** [comment]
I think a URL query param option would be best, allowing the client to choose the behaviour. E.g.

`?ignoreTypeConficts=true`

**Comment by davidbirdsong** [comment]
Sounds good to me.

**Comment by jwilder** [comment]
@otoolep type conflicts are not detected until the write hits the shard so the shard would have to skip that specific error.  The parser could skip bad lines fairly easily though.  This idea sounds similar to `autocommit` mode in other databases.

**Comment by otoolep** [comment]
Ignoring conflicts could be a system-wide setting ala elasticsearch. So the shards could ignore those errors if they occur.

**Comment by jwilder** [comment]
HTTP handler was fixed via 7d6d23e.  Not sure about UDP.

**Comment by jsternberg** [comment]
I'm closing this since the HTTP handler is fixed. If there are still any places where this is still an issue, please open a new issue so we can fix it. Thanks.
