### ISSUE TITLE
Allow users to specify schemas for retention policies

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#3006]
This is something other systems support, and we may to consider it sometime in the future, or rule it out.

InfluxDB is schemaless in the sense that the system does not need to be told the schema up-front. However once data is written to a shard, the schema is inferred and any data destined for that shard which violates this schema results in write-errors. It can also result in unexpected query results across shards, as the schema may vary between shards.

Advanced users may wish to specify the schema up-front, for a given retention policy. This would allow the system to a) attempt to convert data to the required type (floats to ints would be possible, but precision would be lost), or just reject the data outright (converting strings to ints). But supporting something like this would prevent data of the wrong type setting the schema incorrectly in the first place, if the user knows exactly what they want.

This would give the user more control, at the cost of flexibility.

**Comment by dashesy** [comment]
is it possible to distinguish between integer types, also between 32 vs 64 bit floating point? I think that cannot be inferred but with a schema one can use it. For most applications that I have 32 bit floating point is enough for example, and it does make difference when doing heavy math.

**Comment by beckettsean** [comment]
@dashesy InfluxDB doesn't currently support any data types other than `string`, `boolean`, `float64`, and `int64`. It would introduce non-trivial ongoing complexity to add 32-bit types. What would be the gain?

**Comment by dashesy** [comment]
@beckettsean it will need half as much for space requirements and doing arithmetic will be faster too (for floating point definitely), also it requires less memory doing operations. BTW, in schema it might help to be able to specify the number of decimal points for any floating point type, to reduce the size of the returned text in json.

**Comment by beckettsean** [comment]
I'm not convinced that the gains are meaningful compared to the cost of complexity, in light of the other low-hanging fruit for performance. While it might be relevant to version 2.5, it seems like pre-optimization for 1.0. More data types certainly complicate all functions that do math, making it harder to add new functions or support custom functions. I think while we're still adding basic features it's better to opt for simplicity of design over incremental performance gains.

We have discussed whether there should be a limitation on the returned precision for time, although not for the stored values. Are you seeing `float64`s coming back with lots of trailing zeros?

**Comment by dashesy** [comment]
makes sense, also `float64` trailing zeros are fine, but limiting precision can help with trailing decimal points in general not just zeros.

**Comment by beckettsean** [comment]
@otoolep is this still relevant/feasible given the new raft implementation?

**Comment by otoolep** [comment]
Yes.

The idea is to give users who know their schema up-front the ability to then lock it down, thereby avoiding all the problems of writing data as the wrong type. If we ever do it, it would be post 1.0.

**Comment by jsternberg** [comment]
I'm closing this to help clear up our issue queue. We'll reopen or make a new feature if we're going to do this post-1.0.
