### ISSUE TITLE
CI failure in TestStatementExecutor_ExecuteStatement_ShowGrantsFor 

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#3028]
https://circle-artifacts.com/gh/influxdb/influxdb/3540/artifacts/1/tmp/circle-artifacts.5bWlkni/test_logs_race.txt

shows in a failure in this test. Only 1 container failed, the change made to trigger this build had nothing to grants. Perhaps this is a sorting issue. @n1tr0g -- any idea what happened here? What does this test failure tell us?

**Comment by otoolep** [comment]
@dgnorton 

This change went in here: https://github.com/influxdb/influxdb/pull/2650/files

**Comment by otoolep** [comment]
Test disabled in:

https://github.com/influxdb/influxdb/commit/c73ae8b845ca7201c96b2cf05e1c82240265aa3a

**Comment by otoolep** [comment]
Test failure:
```
=== RUN TestStatementExecutor_ExecuteStatement_ShowGrantsFor
--- FAIL: TestStatementExecutor_ExecuteStatement_ShowGrantsFor (0.00s)
	statement_executor_test.go:110: unexpected rows: (influxql.Rows) (len=1 cap=1) {
		 (*influxql.Row)(0xc20803a660)({
		  Name: (string) "",
		  Tags: (map[string]string) <nil>,
		  Columns: ([]string) (len=2 cap=2) {
		   (string) (len=8) "database",
		   (string) (len=9) "privilege"
		  },
		  Values: ([][]interface {}) (len=2 cap=2) {
		   ([]interface {}) (len=2 cap=2) {
		    (string) (len=5) "golja",
		    (string) (len=5) "WRITE"
		   },
		   ([]interface {}) (len=2 cap=2) {
		    (string) (len=5) "dejan",
		    (string) (len=4) "READ"
		   }
		  },
		  Err: (error) <nil>
		 })
		}
=== RUN TestStatementExecutor_ExecuteStatement_ShowServers
```

**Comment by otoolep** [comment]
@n1tr0g -- can you please check if the output from the production code sorts its results before emitting them? That way tests can be written to expect data in a certain order.

Not sure if this is the problem, but we hit the sorting issue all the time, when it comes to testing.

**Comment by n1tr0g** [comment]
Sure, but that's weird because it only happens sometimes. I will have a look.

**Comment by beckettsean** [comment]
@otoolep is this still relevant?

**Comment by otoolep** [comment]
Unfortunately yes, the test is still skipped.

**Comment by jsternberg** [comment]
This test function no longer seems to exist. It was probably removed as part of the query engine refactor. I'm going to close this issue.
