### ISSUE TITLE
Downsample by number of points instead of time

### ISSUE THREAD

**Issue by malaakso** [influxdata/influxdb#3099]
I'd like to downsample points by their count instead of time, e.g.

```
select mean(value) from series group by count(10)
```

to get averages of 10 consecutive points. Is something like this possible to implement?

**Comment by beckettsean** [comment]
There is no way to do this, currently. It is more of a relational database query than a time-series query, as time is not involved at all.

**Comment by SupermanScott** [comment]
Actually StatusWolf for OpenTSDB does this with Largest-Triangle-Three-Buckets

http://blackops.io/blog/2014/05/time-series-graphs-and-downsampling/

**Comment by malaakso** [comment]
My use case would be the drawing of control charts, where I'd like to average always over a fixed number of samples to get closer to normally distributed data. Throughput of the process varies a lot, so averaging over time leaves me sometimes with too few samples in a bucket. Obviously I can handle all this afterwards in my application code, but having a suitable (continuous) query would be useful.

**Comment by mitar** [comment]
Still interested in this.

**Comment by yayitazale** [comment]
Now that influxDB is being sold as a tool for manufacturing use cases, this should be implemented as in many areas of production and quality departments, being able to aggregate by unit produced, batch, and so is much more useful than by grouping by time. I know this can be done in a SQL database, but storing all the production data in the same DB is easier and lighter. 

Example: a glass industry where quality team wants a mean value of the wall thickness windowed by every 10 bottles to monitor trends, where bottles are not being produced with a fixed rate over time.
