### ISSUE TITLE
[0.9.3] aggregate functions with distinct function returns no result 

### ISSUE THREAD

**Issue by markuspatrick** [influxdata/influxdb#3171]
We use in our application a specific rate of error (type) based on unique values.  The statement below is just a example to clarify the problem. 
Using the distinct functions with count works fine, using sum and count together works fine. 
But using sum and count with distinct function fails. 

For example: 
`select sum(value)/ count(distinct value2) from cpu`
or
`select sum(value)/ count(distinct(value2)) from cpu`

returns
```
time			
1970-01-01T00:00:00Z
```
value is a float.
value2 is a string (i tried also with float - same result)

I tried in 0.9.0 (ubuntu and OS X 10.10.3) and 0.9.1 rc-1(ubuntu)

**Comment by beckettsean** [comment]
@markuspatrick what are the results of `select sum(value) from cpu` and `select count(distinct(value2)) from cpu`?

**Comment by markuspatrick** [comment]
@beckettsean: Below you see what I was trying:
```
> select * from cpu
name: cpu
tags: host=A
time				value	value2
----				-----	------
2015-07-15T06:59:10.388781057Z	2.3	1
2015-07-15T06:59:29.156098195Z	2.1	1
2015-07-15T06:59:34.115838982Z	2.4	2

> select sum(value) from cpu
name: cpu
---------
time			sum
1970-01-01T00:00:00Z	6.800000000000001

> select count(distinct(value2)) from cpu
name: cpu
---------
time			count
1970-01-01T00:00:00Z	2

> select sum(value)/count(distinct(value2)) from cpu
name: cpu
---------
time			
1970-01-01T00:00:00Z	
```

**Comment by beckettsean** [comment]
Thanks for the data @markuspatrick. I'm pretty sure this is a special case of https://github.com/influxdb/influxdb/issues/3000, since your denominator is always an integer. Closing in favor of that issue.

**Comment by markuspatrick** [comment]
@beckettsean: Sorry the problem stays the same in 0.9.3 :(

**Comment by beckettsean** [comment]
Looks like it's something to do with DISTINCT in the denominator (using `curl` to show the `null` returns):

the `SUM` and `COUNT(DISTINCT)` queries run fine on their own (with a little integer math weirdness):

```
$ curl ...  "q=select sum(value) from funcmath"; echo
{"results":[{"series":[{"name":"funcmath","columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",6.800000000000001]]}]}]}

$ curl ...  "q=select count(distinct(value2)) from funcmath"; echo
{"results":[{"series":[{"name":"funcmath","columns":["time","count"],"values":[["1970-01-01T00:00:00Z",2]]}]}]}
```

But dividing one by the other fails:

```
$ curl ...  "q=select sum(value) / count(distinct(value2)) from funcmath"; echo
{"results":[{"series":[{"name":"funcmath","columns":["time",""],"values":[["1970-01-01T00:00:00Z",null]]}]}]}

$ curl ...  "q=select count(distinct(value2)) / sum(value) from funcmath"; echo
{"results":[{"series":[{"name":"funcmath","columns":["time",""],"values":[["1970-01-01T00:00:00Z",null]]}]}]}
```

It appears to be isolated to the `COUNT(DISTINCT)` composite function. These all work:

```
$ curl ...  "q=select sum(value) / 2 from funcmath"; echo
{"results":[{"series":[{"name":"funcmath","columns":["time",""],"values":[["1970-01-01T00:00:00Z",3.4000000000000004]]}]}]}

$ curl ...  "q=select distinct(value2) from funcmath"; echo
{"results":[{"series":[{"name":"funcmath","columns":["time","distinct"],"values":[["1970-01-01T00:00:00Z",[1,2]]]}]}]}

$ curl ...  "q=select sum(value) / count(value2) from funcmath"; echo
{"results":[{"series":[{"name":"funcmath","columns":["time",""],"values":[["1970-01-01T00:00:00Z",2.266666666666667]]}]}]}
```

but these fail:

```
$ curl ...  "q=select 6.8 / count(distinct(value2)) from funcmath"; echo
{"results":[{"series":[{"name":"funcmath","columns":["time",""],"values":[["1970-01-01T00:00:00Z",null]]}]}]}

$ curl ...  "q=select count(distinct(value2)) / 2 from funcmath"; echo
{"results":[{"series":[{"name":"funcmath","columns":["time",""],"values":[["1970-01-01T00:00:00Z",null]]}]}]}
```

**Comment by jsternberg** [comment]
I think this is fixed in the latest version. As long as both of the variables are fields, I get an output. It appears like `count(distinct(host))` where `host` is a tag doesn't work, but that query doesn't seem to work normally.

I'm going to close this as fixed. Please reopen if you have trouble with the latest version so we can resolve this issue if it still exists. Thanks.
