### ISSUE TITLE
Errors not returning with multiple queries

### ISSUE THREAD

**Issue by 121watts** [influxdata/influxdb#3181]
Influx Version  5b764cfc016b56e5add0d874b772a273bdb4bc79
OS X Yosemite 10.10.3
Built from source

When making a single request to Influx with multiple queries, if a query which should produce an error is not first the error does not return:

![screen shot 2015-06-27 at 1 49 16 pm](https://cloud.githubusercontent.com/assets/7582765/8415062/18fc521a-1e51-11e5-8ee9-56f313b66a21.png)

![screen shot 2015-06-27 at 1 48 35 pm](https://cloud.githubusercontent.com/assets/7582765/8415068/1afa1b06-1e51-11e5-8b87-b1db954f72b1.png)

**Comment by beckettsean** [comment]
@121watts please learn to copy/paste rather than taking screenshots :)

**Comment by jsternberg** [comment]
This seems to work now in 0.12. Please reopen if this is still an issue. Thanks.
