### ISSUE TITLE
[CLI feature request] process input file in non-interactive mode

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3185]
Allow the CLI to process a file of queries, e.g.

`influx -execute @filename`

Where `filename` is a file containing valid InfluxDB queries, one per line, and ideally also `insert` statements.

**Comment by codeb2cc** [comment]
I hope this feature would be implemented soon. I deploy InfluxDB in different data centers and there're quite a few setup(db, user, cq, etc) to be done. For now I have to use a workaround:
```
cat influxql.txt | influx -username "xxx" -password "XXX"
```

**Comment by phemmer** [comment]
Passing the file through STDIN seems like the most intuitive way to do this to me. It's supported nearly universally (by other tools). A path to a file as an argument is nowhere near as common.

**Comment by jsternberg** [comment]
I believe this is fixed by #6896.
