### ISSUE TITLE
[0.9.1] aggregate functions different from sum and count do not work in CQs

### ISSUE THREAD

**Issue by markuspatrick** [influxdata/influxdb#3225]
Still very annoying bug in 0.9.1.
Using aggregate function like max, min , count(distinct()) ,... in CQ Queries still kills influxdb.
See Issues  https://github.com/influxdb/influxdb/issues/3171 and https://github.com/influxdb/influxdb/issues/3158

* Create a CQ with such aggregate functions
* try insert at least 500 data points (within the interval of the CQ)
* Insert data results in timeout-error (always 5s timeout - maybe in correlation with issue https://github.com/influxdb/influxdb/pull/3218 ?)
* hard reset of influxdb is required, to work further

**Comment by eminden** [comment]
I am having the same, hope to get fixed soon.

**Comment by kevinsteger** [comment]
I am experiencing this issue with a SUM CQ on only a few thousand data points.  My CQ:

create continuous query profit_1m on traffic BEGIN select sum(value) as value into profit_1m from profit group by time(1m),* END

**Comment by hiepsikhokhao** [comment]
Hi,

Timeout problem still happens on verision 0.9.6-nightly-9637446. I must always restart influxdb for work arround

[http] 2015/12/07 15:24:34 ::1 - mecdn [07/Dec/2015:15:24:24 +0700] POST /write?db=cdn_raw_log&p=%5BREDACTED%5D&precision=s&u=mecdn HTTP/1.1 500 44 - Ruby ec9d3460-9cbb-11e5-aef9-000000000000 10.002499869s
[http] 2015/12/07 15:24:42 ::1 - mecdn [07/Dec/2015:15:24:32 +0700] POST /write?db=dns_raw_log&p=%5BREDACTED%5D&precision=s&u=mecdn HTTP/1.1 500 44 - Ruby f1628bdc-9cbb-11e5-aefa-000000000000 10.003647506s
[http] 2015/12/07 15:24:54 ::1 - mecdn [07/Dec/2015:15:24:44 +0700] POST /write?db=cdn_raw_log&p=%5BREDACTED%5D&precision=s&u=mecdn HTTP/1.1 500 44 - Ruby f837b259-9cbb-11e5-aefb-000000000000 10.002384296s
[http] 2015/12/07 15:25:27 ::1 - mecdn [07/Dec/2015:15:25:17 +0700] POST /write?db=dns_raw_log&p=%5BREDACTED%5D&precision=s&u=mecdn HTTP/1.1 500 44 - Ruby 0c24327c-9cbc-11e5-aefc-000000000000 10.003236462s

**Comment by beckettsean** [comment]
@hiepsikhokhao your report does not look like it is related to Continuous Queries, as the write timeouts are coming from a Ruby client.

**Comment by hiepsikhokhao** [comment]
HI @beckettsean ,

Yes, i use fluent-plugin-influxdb. i use influxdb to store nginx access log & use CQ to calculate.
To keep point not be overwritten , i add a random number as tags. This makes Influxdb performance too bad so i try another way ( calculate data first, then push to Influxdb, not use CQ ) . And now everything's good. Thanks

**Comment by jsternberg** [comment]
This bug was filed against the old query engine. Since we have completely changed the query engine since then, please try again with the latest InfluxDB. If this is still an issue, please reopen this issue.

Thanks!
