### ISSUE TITLE
[0.9.1] Incremental Backup Error

### ISSUE THREAD

**Issue by jhorwit2** [influxdata/influxdb#3239]
I was trying out the commands found [here](https://influxdb.com/docs/v0.9/administration/backup_and_restore.html) and the first time I ran `influxd backup /tmp/snapshot` everything worked as expected. Unless I'm mistaken, if I ran that same command again it should create a new snapshot file with `.0`; however, I get the following error:

```
[influxdb]$ ./influxd backup /tmp/snapshot
2015/07/05 20:19:01 influxdb backup
backup: read file snapshot: manifest: manifest: idx=0, err=snapshot header: EOF```

**Comment by beckettsean** [comment]
backups are due for significant reworking, there are bound to be rough edges until then, thanks for the report and we'll address it eventually.

**Comment by jsternberg** [comment]
I'm going to close this. Please try again with a more recent version and tell us if it still doesn't work. Thanks.
