### ISSUE TITLE
[feature request] Implement fill(mean)

### ISSUE THREAD

**Issue by pdf** [influxdata/influxdb#3273]
Tracking issue for implementation of `fill(mean)`, this is the default interpolation used in some other time series DBs, and pretty important.

**Comment by beckettsean** [comment]
@pdf can you point to the documentation for this feature in another TSDB? We're not quite sure what `mean` would be in the absence of data. Trailing average of some sort?

**Comment by pdf** [comment]
Here's what OpenTSDB does: http://opentsdb.net/docs/build/html/user_guide/query/aggregators.html#interpolation

It's necessary to do rate calculation shorter than your sample period.

**Comment by pdf** [comment]
I think the PR for this does the right thing now, but it doesn't appear to solve the problem I wanted to.  I think derivative may be calculated before the fill is performed?

**Comment by desa** [comment]
Called `fill(linear)`
