### ISSUE TITLE
cannot use OR with absolute time in where clause

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3290]
```
> select * from system_load1 where time = '2015-07-10T17:34:13.960621663Z'
name: system_load1
tags: host=catalyst
time				value
----				-----
2015-07-10T17:34:13.960621663Z	1.93

> select * from system_load1 where time = '2015-07-10T17:33:59.955702621Z'
name: system_load1
tags: host=catalyst
time				value
----				-----
2015-07-10T17:33:59.955702621Z	1.31

> select * from system_load1 where time = '2015-07-10T17:34:13.960621663Z' or time = '2015-07-10T17:33:59.955702621Z'
name: system_load1
tags: host=catalyst
time	value
----	-----

> 
```

**Comment by jsternberg** [comment]
The problem here is that the `TimeRange` function will only return one time range while this one effectively has multiple time ranges. I can modify it to use multiple time ranges, but it does bring up a pretty important question. If a time range doesn't have a start or end, what's the default? For the end, we've used `now()`, but what should be used for the beginning? If you do this:

```
SELECT mean(value) FROM cpu WHERE time < '2000-01-01T00:00:00Z' OR time >= now() - 10m GROUP BY time(1m)
```

While a bit nonsensical, it will give a very rude awakening when it tries to fill in every 1 minute interval from 1970 until 2000 along with the last 10 minutes.

**Comment by beckettsean** [comment]
@jsternberg to date, the assumed lower bound has always been epoch 0 unless otherwise specified. There are errors which fire on any query that has a `GROUP BY` clause but no `WHERE time` clause. There are also errors which fire if the number of `GROUP BY` buckets exceeds 99999.

Did we rip out those behaviors with the new query engine?

**Comment by jsternberg** [comment]
We don't currently have anything stopping queries from going out of control. I'd also argue that 99999 seems very high to begin with.

What kind of restrictions should we put on this?

**Comment by beckettsean** [comment]
@jsternberg I think this is a larger discussion to have with @jwilder and more of the team.

**Comment by jwilder** [comment]
This may be a option we should add to #6024

**Comment by jlennox** [comment]
This issue would be a good candidate for "Frequently Encountered Issues"

**Comment by beckettsean** [comment]
Thanks for the suggestion, @jlennox.

I created https://github.com/influxdata/docs.influxdata.com/issues/526 to get this into the docs.

**Comment by jwilder** [comment]
`OR` with multiple time ranges is not currently supported.  This should return an error, but returning an error would be a breaking change to the query language.  Fixing this needs to be done with care to not break the API.

**Comment by jsternberg** [comment]
I'm going to close this in favor of #7530. That includes the reason why this is an issue and includes the proposed fix in a way that I think is easier to understand.
