### ISSUE TITLE
Allow graphite templates to select database

### ISSUE THREAD

**Issue by gdlx** [influxdata/influxdb#3329]
Would it be possible to add to the graphite input the ability to select the target database (and ideally retention policy too) for each template ?

**Comment by beckettsean** [comment]
would be mitigated enough by #2785 for now

**Comment by adrianlzt** [comment]
+1

**Comment by dcasa** [comment]
+1

**Comment by gauthier-delacroix** [comment]
It's already possible to select the database for a single Graphite input. It's just not documented.

**Comment by adrianlzt** [comment]
But will be great that each template writes to a different database. If not, is not possible to handle permissions with that data. Everyone with access to the graphite database could read data of other projects.
