### ISSUE TITLE
Provide an API  to get snapshot data streams

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#3338]
I would like a standard way to get a stream of the snapshot data. What I mean by this is be able to run a command like `influxd backup` and have it output the data to STDOUT or to make a TCP connection to a defined end point to download the snapshot data. The motivation for this is we have a backup system that likes to consume backups in a stream so that is can compress, encrypt, etc the data without it even having to touch disk. Currently the `backup` command expects a file path and does some file renaming for you. While this is a nice feature its pretty specific to a particular use case. It would be trivial to refactor the backup command to remain the same but just consume this generic endpoint for the data.

Thoughts?

Essentially I am proposing making the `download`  method (https://github.com/influxdb/influxdb/blob/master/cmd/influxd/backup/backup.go#L125) part of the influxdb core API or something along those lines.

**Comment by rbetts** [comment]
Related to the concept of writing backups to s3, for example.

**Comment by danslu** [comment]
Hello, I would be very nice feature. Is it implemented? How can I find it?
