### ISSUE TITLE
[0.9.1] Admin UI does not display boolean values

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/influxdb#3348]
Results with boolean values are not displayed. See screenshot below. Regular queries with boolean fields also display as empty.

![screen shot 2015-07-16 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/628831/8732567/31906fd6-2bb3-11e5-923d-5f27e4e63a73.png)

**Comment by toddboom** [comment]
I think this is fixed in the current admin interface.

**Comment by zstyblik** [comment]
@toddboom actually, `SHOW USERS` doesn't work in v0.10 at all. However, it's being tracked in https://github.com/influxdata/influxdb/issues/4688.
