### ISSUE TITLE
read lock is missing in the tsdb/meta.go:223?

### ISSUE THREAD

**Issue by runner-mei** [influxdata/influxdb#3378]
read lock is missing in the tsdb/meta.go:223?

````go
func (db *DatabaseIndex) Measurements() Measurements {
	measurements := make(Measurements, 0, len(db.measurements))
	for _, m := range db.measurements {
		measurements = append(measurements, m)
	}
	return measurements 
}
````
DatabaseIndex.Measurements is used by QueryExecutor.executeShowMeasurementsStatement

If the lock is unnecessary, so not to export the function.

**Comment by jsternberg** [comment]
It looks like this got fixed in 3f4c5a55. I'm going to close this.

Thanks for your contribution.
