### ISSUE TITLE
[0.9.2] 3-node cluster: One of the nodes seems to get stuck in leader election 

### ISSUE THREAD

**Issue by hectorj2f** [influxdata/influxdb#3422]
I am using `v0.9.2-rc1` to setup a 3-node cluster with replication factor 3. I can see that not all the nodes are available some of them seems to get stuck into the leader election process, in particular only 2 out of 3 seem to be operative. I can even run operations against them on ports 8086 and 8083 (getting after a while `retention policy shard deletion check commencing`). However, one of the node seems to get stuck in to the leader election and for an unknown reason cannot perform any operation against it. I verified there is connectivity, the connection is dropped from the container itself.

In one of my tests, I tried to restart such a node and then everything seemed to work smoothly. But in another test, this issue persisted

Output of the node stuck into the leader election (I manually restarted and it worked) in my first test:
```
Jul 21 00:09:56 0c0496114e32e3c2 bash[31093]: [metastore] 2015/07/21 00:09:56 [DEBUG] raft: Failed to contact 10.0.4.25:8088 in 3.326423317s
Jul 21 00:09:56 0c0496114e32e3c2 bash[31093]: [metastore] 2015/07/21 00:09:56 [WARN] raft: AppendEntries to 10.0.4.25:8088 rejected, sending older logs (next: 1)
Jul 21 00:09:57 0c0496114e32e3c2 bash[31093]: [metastore] 2015/07/21 00:09:57 [WARN] raft: Failed to contact 10.0.4.25:8088 in 500.170297ms
Jul 21 00:09:59 0c0496114e32e3c2 bash[31093]: [metastore] 2015/07/21 00:09:59 [INFO] raft: pipelining replication to peer 10.0.4.25:8088
```

This output represents the log of my second test:
```
Jul 21 23:39:38 0c0496114e32e3c2 bash[5553]: [metastore] 2015/07/21 23:39:38 [DEBUG] raft: Node 10.0.4.37:8088 updated peer set (2): [10.0.4.27:8088 10.0.4.25:8088 10.0.4.40:8088]
Jul 21 23:39:38 0c0496114e32e3c2 bash[5553]: [metastore] 2015/07/21 23:39:38 [DEBUG] raft: Node 10.0.4.37:8088 updated peer set (2): [10.0.4.25:8088 10.0.4.37:8088 10.0.4.40:8088]
Jul 21 23:39:38 0c0496114e32e3c2 bash[5553]: [metastore] 2015/07/21 23:39:38 [DEBUG] raft: Node 10.0.4.37:8088 updated peer set (2): [10.0.4.25:8088 10.0.4.37:8088 10.0.4.40:8088]
Jul 21 23:39:38 0c0496114e32e3c2 bash[5553]: 2015/07/21 23:39:38 [DEBUG] raft-net: 10.0.4.37:8088 accepted connection from: 172.17.42.1:47715
```

How can we avoid this kind of issues that require manual work ? 
Shouldn't it be a good idea to have a retry to try to join the cluster after a while? 
Why don't I get a log entry like `Listening on port [::8086]` ?

**Comment by skynet** [comment]
:+1:

**Comment by beckettsean** [comment]
@hectorj2f @skynet the latest 0.9.3 nightlies have much better cluster configuration. Can you try to repro with the latest?

**Comment by hectorj2f** [comment]
@beckettsean Thanks for the update, but as long as cadvisor doesn't support a newer version of Influxdb api. I won't move to a newer version.

**Comment by skynet** [comment]
Similar situation here. Need influxdb php sdk to support 0.9.3. https://github.com/influxdb/influxdb-php/issues/13#issuecomment-132484255

**Comment by toddboom** [comment]
Closing this out because it's no longer applicable.
