### ISSUE TITLE
[0.9.2-rc1] (regression) comparison operator giving bad results when coupled with fill(0)

### ISSUE THREAD

**Issue by Jhors2** [influxdata/influxdb#3446]
After upgrading from 0.9.1 to 0.9.2-rc1 it appears that the ```< > = ```operators partially work in queries.

Specifically, I am doing a query like:

select sum(value) from input_bps where hostname =~ /web/ AND value > 10000 group by time(1m),hostname fill(0)

What returns is a grouped measurement for ALL possible "series" that exist, however it 0 fills any values below 10000.  Previously, the measurement was not even returned at all if it was below my value operator.

I'm not entirely sure where in the query engine this is evaluated, however for performance reasons we do this in a lot of places, so it seems like the sooner this assessment can be made, and the query engine can bypass returning the result, the better.

**Comment by beckettsean** [comment]
@Jhors2 can you provide some sample output from that query, just to make sure we're understanding the issue you describe?

It sounds like you're saying that the query runs as expected, but the `fill(0)` is being applied to all points that match `where hostname =~ /web/ `, including ones that fail `value > 10000 `. Is that correct?

**Comment by Jhors2** [comment]
the fill(0) is applying to all points that fail value > 10000.  It is NOT being applied to points that pass my criteria, these return properly.  The previous experience was that nothing would be returned at all if that condition had failed.  I'll provide sample outputs as soon as I can.

**Comment by ecables** [comment]
Seeing this in 0.9.3 as well...

**Comment by jsternberg** [comment]
The new query engine seems to do this correctly. The values are filtered before reaching the aggregate function so if you do something like this:

```
> insert cpu value=20 1257894000000000000
> insert cpu value=10 1257894060000000000
```

If you then do this:

```
> SELECT mean(value) FROM cpu WHERE time >= '2009-11-10T23:00:00Z' AND time < '2009-11-10T23:02:00Z' AND value > 10 GROUP BY time(1m) FILL(0)
name: cpu
---------
time                    mean
2009-11-10T23:00:00Z    20
2009-11-10T23:01:00Z    0
2009-11-10T23:02:00Z    0
```

Since it will filter out the 10 value, it will then fill in that interval since there are no valid points in that interval.

Please reopen if this is wrong and there's still an issue on the latest version. Thanks!
