### ISSUE TITLE
[feature request] SHOW FIELD KEYS should give field type(s)

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3451]
`SHOW FIELD KEYS` should give the associated data type(s) reported from each shard.

**Comment by adrianlzt** [comment]
+1

**Comment by ozansener** [comment]
+1

**Comment by BrannonKing** [comment]
+1

**Comment by Asoul** [comment]
+1

**Comment by bbinet** [comment]
Having `SHOW FIELD KEYS` to return the field type is important when creating dynamic query editor interface.

For example in grafana influxdb editor we need to now about the field type to be able to automatically add quotes around string values: https://github.com/grafana/grafana/pull/4719#issuecomment-215725256
