### ISSUE TITLE
[feature request] admin UI should show results of all queries, not just the first

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3503]
In the admin UI, when chaining queries with a semi-colon (`;`), only the first query's results are shown. All results are returned, we just need to parse and display them.

![screen shot 2015-07-29 at 11 50 19](https://cloud.githubusercontent.com/assets/6537329/8966764/0259afe0-35e8-11e5-9412-4cda3e300865.png)

**Comment by toddboom** [comment]
it makes me really happy to finally see screenshots of the new interface!

**Comment by jsternberg** [comment]
It appears that this works in the latest version. I'm going to close this issue as fixed.
