### ISSUE TITLE
[0.9.3-rc2] Unable to stop service while editing config file

### ISSUE THREAD

**Issue by andreyp1986** [influxdata/influxdb#3524]
I start editing config file:
vi /etc/opt/influxdb/influxdb.conf

From other terminal I try to restart influxdb service:
root@zip:~# service influxdb restart
influxd process is not running [ OK ]
Starting the process influxd [ OK ]
influxd process failed to start [ FAILED ]

root@zip:~# service influxdb version
InfluxDB v0.9.3-nightly-401f1b2 (git: 401f1b2843d32bcc4c9abe596c2dd44e14b0ae75)

**Comment by juddgaddie** [comment]
What is the log output? 

Did you make any changes to the configuration?

**Comment by dalibor** [comment]
Same here on InfluxDB v0.9.2 (git: 6c0a91f775f9fc0e625d17ffa04a3fe86945ba09) (Ubuntu 14.04). InfluxDB fails to stop and start while config file is opened (i just open it in terminal with vim without editing anything).

**Comment by beckettsean** [comment]
@andreyp1986 @dalibor there's another bug regarding `restart`: https://github.com/influxdb/influxdb/issues/3548 that might be confusing the issue. Can you try with explicit `stop` and `start` rather than `restart`?

**Comment by dalibor** [comment]
@beckettsean `stop` works while config file is open and `start` not.

**Comment by beckettsean** [comment]
For me on 14.04 with 0.9.3-rc2 `/etc/init.d/influxdb stop` has no effect if `vi` has the config file open. If the file is not open, `stop` will shut down the process.

`/etc/init.d/influxdb start` works just fine if `vi` has the config file open. 

@dalibor my experience was the exact opposite of yours. `start` works regardless but `stop` fails if the config file is open. Can you repro the test on 0.9.3-rc2?

**Comment by otoolep** [comment]
I have a feeling this may be fixed by https://github.com/influxdb/influxdb/pull/4010

**Comment by rossmcdonald** [comment]
Fixed with #4227
