### ISSUE TITLE
[feature request] Implement query returning size of measurement, series

### ISSUE THREAD

**Issue by adamwalach** [influxdata/influxdb#3532]
In reference to my previous question:  https://groups.google.com/forum/#!msg/influxdb/SLU2Lmaefmg/7MVaKApsMAAJ
Use case: 
My database is growing and I need information about size of measurements and series.
Right now the only information I can obtain is database size ( and even for that I have to use external tool and check directory size).
I would expected to get list containing measurements/series and number of blocks/bytes it consumes.
I have no experience with InfluxDB internals, so its hard for me to provide any suggestions about implementation.

**Comment by jcassel** [comment]
+1 on the general idea of querys that show us details related to the space and size of the data in an instance/cluster.

This request seems very closely related to one that pauldix opened.
Should be able to show shards #3562

**Comment by gunnaraasen** [comment]
Returning the disk size of shards with `SHOW STATS` would also be useful.

**Comment by otoolep** [comment]
The fundamental issue that makes this non-trivial is that only nodes themselves know the size of shards. The node receiving the query i.e. `SHOW SHARDS` can only check its local filesystem, and determine shards local to it.

To solve this issue, each node in the cluster needs to be prepared to serve information about the shards local to it, and then the node receiving the query from the use needs to collate the data from across the cluster.

Eminently doable, but not trivial. I just want to give some background on why this is not a one line change.

**Comment by toddboom** [comment]
I think this is mostly covered in the latest release, mostly implemented in #5816.
