### ISSUE TITLE
[feature request] make RAM Limit, CPU cores, LRU cache configurable

### ISSUE THREAD

**Issue by SiriusHu** [influxdata/influxdb#3537]
as the title says, if so, how to set, 3q

**Comment by Jhors2** [comment]
LRU cache size would be awesome to have.  Considering my hosts have 64G of memory to burn, I would almost like to to cache the whole DB in memory.

**Comment by syepes** [comment]
This would be a crucial and very interesting functionality.

In my seek to replace Graphite, I tested InfluxDB and its a really memory killer/eating app compared with its alternatives Graphite, Cyanite, Prometheus.

**Comment by pauldix** [comment]
@Jhors2 the database files are memory mapped so the OS will handle all of that for you. There is no LRU.

@syepes what are you seeing for memory usage? Because the db files are memory mapped, the reported memory usage will be inaccurate.

**Comment by jsternberg** [comment]
Since there's been no response to this in awhile, I'm going to close this. If you are still having issues with the latest version of InfluxDB and still need something related to this ticket, please file a new one that references this one so that we can figure out what you need. Thanks.
