### ISSUE TITLE
[0.9.2] Backup restore --> Panic "cannot free page"

### ISSUE THREAD

**Issue by consense** [influxdata/influxdb#3555]
influxdb v. 0.9.2, only one node:
backup script (against running influxdb service) completes with a 78MB backup file.
restore (against stopped service) finishes with 

    restore complete using /opt/influxdb/backup/influx-backup-2015-08-04_23-06-43

subsequent start of the service reports a success 

    Starting the process influxd [ OK ]
    influxd process was started [ OK ]

but influxdb panics right after start:

    [metastore] 2015/08/05 08:23:46 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
    [metastore] 2015/08/05 08:23:46 read local node id: 1
    [shard] 2015/08/05 08:23:46 flush 38 points in 0.008s
    [shard] 2015/08/05 08:23:46 flush 74 points in 0.005s
    [shard] 2015/08/05 08:23:46 flush 38 points in 0.010s
    [shard] 2015/08/05 08:23:46 flush 74 points in 0.010s
    [shard] 2015/08/05 08:23:46 flush 37 points in 0.010s
    [shard] 2015/08/05 08:23:46 flush 3 points in 0.010s
    [shard] 2015/08/05 08:23:46 flush 48 points in 0.010s
    [shard] 2015/08/05 08:23:46 flush 9 points in 0.014s
    [shard] 2015/08/05 08:23:46 flush 39 points in 0.021s
    [shard] 2015/08/05 08:23:46 flush 40 points in 0.021s
    [shard] 2015/08/05 08:23:46 flush 44 points in 0.019s
    [shard] 2015/08/05 08:23:46 flush 48 points in 0.011s
    [shard] 2015/08/05 08:23:46 flush 68 points in 0.031s
    [shard] 2015/08/05 08:23:47 flush 147 points in 0.033s
    [shard] 2015/08/05 08:23:47 flush 61 points in 0.021s
    [metastore] 2015/08/05 08:23:47 [WARN] raft: Heartbeat timeout reached, starting election
    [metastore] 2015/08/05 08:23:47 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
    [metastore] 2015/08/05 08:23:47 [DEBUG] raft: Votes needed: 1
    [metastore] 2015/08/05 08:23:47 [DEBUG] raft: Vote granted. Tally: 1
    [metastore] 2015/08/05 08:23:47 [INFO] raft: Election won. Tally: 1
    [metastore] 2015/08/05 08:23:47 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
    [metastore] 2015/08/05 08:23:47 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    [metastore] 2015/08/05 08:23:47 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
    [metastore] 2015/08/05 08:23:47 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
    panic: cannot free page 0 or 1: 0
    
    goroutine 1 [running]:
    github.com/boltdb/bolt.(*freelist).free(0xc208e25350, 0xc97a, 0x7f3fc3e30000)
            /root/go/src/github.com/boltdb/bolt/freelist.go:109 +0x15d
    github.com/boltdb/bolt.(*Tx).Commit(0xc208e2cc30, 0x0, 0x0)
            /root/go/src/github.com/boltdb/bolt/tx.go:162 +0x314
    github.com/boltdb/bolt.(*DB).Update(0xc208e04680, 0xc30ae0, 0x0, 0x0)
            /root/go/src/github.com/boltdb/bolt/db.go:554 +0x169
    github.com/influxdb/influxdb/tsdb.func·010(0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:132 +0x1b1
    github.com/influxdb/influxdb/tsdb.(*Shard).Open(0xc208e022c0, 0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:152 +0x6f
    github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0xc20800c540, 0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/tsdb/store.go:240 +0xa2a
    github.com/influxdb/influxdb/tsdb.(*Store).Open(0xc20800c540, 0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/tsdb/store.go:266 +0x19a
    github.com/influxdb/influxdb/cmd/influxd/run.func·003(0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:310 +0x961
    github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc2080aa0e0, 0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:332 +0x5e
    github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc208011c00, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:97 +0x7ab
    main.(*Main).Run(0xc20808fa80, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:76 +0x3bc
    main.main()
            /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:38 +0xdc
    
    goroutine 6 [syscall]:
    os/signal.loop()
            /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
    created by os/signal.init·1
            /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35
    
    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
            /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1
    
    goroutine 8 [IO wait]:
    net.(*pollDesc).Wait(0xc208010370, 0x72, 0x0, 0x0)
            /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
    net.(*pollDesc).WaitRead(0xc208010370, 0x0, 0x0)
            /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
    net.(*netFD).accept(0xc208010310, 0x0, 0x7f3fda3e4cc8, 0xc2080f4000)
            /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
    net.(*TCPListener).AcceptTCP(0xc2080388f8, 0x0, 0x0, 0x0)
            /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
    net.(*TCPListener).Accept(0xc2080388f8, 0x0, 0x0, 0x0, 0x0)
            /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
    github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080c1a10, 0x7f3fda3e7478, 0xc2080388f8, 0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
    created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
            /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:298 +0x7a8
    
    goroutine 9 [chan receive]:
    github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038900, 0x0, 0x0, 0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
    github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080c1a40, 0x0, 0x0, 0x0, 0x0)
            /root/go/src/github.com/influxdb/influxdb/meta/store.go:1855 +0x64
    github.com/hashicorp/raft.(*NetworkTransport).listen(0xc2080103f0)
            /root/go/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
    created by github.com/hashicorp/raft.NewNetworkTransport
            /root/go/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4
    
    goroutine 10 [select]:
    github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080be1c0)
            /root/go/src/github.com/hashicorp/raft/raft.go:807 +0xc7c
    github.com/hashicorp/raft.(*Raft).runLeader(0xc2080be1c0)
            /root/go/src/github.com/hashicorp/raft/raft.go:779 +0x74e
    github.com/hashicorp/raft.(*Raft).run(0xc2080be1c0)
            /root/go/src/github.com/hashicorp/raft/raft.go:576 +0xc9
    github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
            /root/go/src/github.com/hashicorp/raft/raft.go:241 +0x27
    github.com/hashicorp/raft.func·011()
            /root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
    created by github.com/hashicorp/raft.(*raftState).goFunc
            /root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3

Full stacktrace here:
https://gist.github.com/consense/7c645943230a4c2ff5ee#file-influxdb-log_backup-restore-panic-log

**Comment by jwilder** [comment]
This code in the trace no longer exists.  Please open a new issue with steps to reproduce if you still see this panic.
