### ISSUE TITLE
[feature request] allow WHERE clause binary expressions on non-column values

### ISSUE THREAD

**Issue by joshuawarner32** [influxdata/influxdb#3558]
I've been trying to do various queries of the form `SELECT * FROM the_series WHERE column1 / column2 > 0.5`.  Influxdb consistently gives me an "invalid expression" error.  The particulars of the table and column layout aren't important; this happens everywhere I've tried queries of that form.

In fact, it happens for every `WHERE` clause expression in the form of a binary expression where neither side is itself a column reference.  Digging around in the code, I can see this is the likely culprit: https://github.com/influxdb/influxdb/blob/master/tsdb/meta.go#L633

My questions are these: Is there a plan to remove that restriction?  Would it be difficult?  Would a PR be accepted?  Where do I start?

Thanks.

**Comment by beckettsean** [comment]
@joshuawarner32 I can't say how challenging it would be, but PRs are always welcome.

@dgnorton or @otoolep any thoughts on whether this is a reasonable thing for a community PR?

**Comment by otoolep** [comment]
The specific problem with this is that @joshuawarner32 must want to perform division on tags. But tags are always stored as strings. Performing math is not possible.

**Comment by otoolep** [comment]
I might be mistaken actually, I guess `column1` and `column2` refer to fields in the data?

**Comment by otoolep** [comment]
If the references in the `WHERE` are fields in the values, it would be in principle possible to do this. It would not be  trivial change and would ripple throughout much of the code.

**Comment by joshuawarner32** [comment]
@otoolep - yes, `column1` and `column2` are numeric fields in the data - though, I confess, I'm very fuzzy on exactly what a "tag" is.  I don't _think_ I'm accidentally inserting data in string form, but I can't rule it out at this point.

> [That] would ripple throughout much of the code.

Hmm.  That doesn't sound promising.  I may still take a stab at it, depending on what else I find on my plate.

**Comment by jsternberg** [comment]
I think this should currently be possible and the error is probably validation being too strict. I'm going to try it for a bit.

Throwing this into the 0.13 milestone temporarily. If it turns out to be more difficult than I originally expected, we may have to push it back, but I think it should be easily feasible with the new query engine.
