### ISSUE TITLE
Include cache headers in query responses

### ISSUE THREAD

**Issue by pkaeding** [influxdata/influxdb#356]
It would be great if Influx could include caching headers with query responses. Here are some thoughs I had:

1. Presumably, once data is loaded, queries on past date ranges won't change, so queries with a time boundary in the past could be cached for a long time (if not indefinitely).  For this, the cache time should probably be configurable.
2. Alternatively, I'm not sure if it would be cheap to calculate an `etag` value for a query (perhaps based on a last modified attribute of the shards that would service the query?), but that might also enable caching queries.

**Comment by jsternberg** [comment]
I'm going to close this issue due to inactivity. Please comment on the issue if you are still interested in this feature and we will look at it again to see if we should reopen and prioritize it for a future release. I don't think this feature would be able to get in before 1.0 though.

Thanks.
