### ISSUE TITLE
[feature request] run expanded Go Benchmarks for each package

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#3576]
We need to expand the Go benchmarks written for each package.  Then we can start running automated scripts after each point release (or even each build) and log them to history to compare the results.  This should help us catch any major deviations that aren't acceptable as we continue to work on the code.

**Comment by ecables** [comment]
+1

**Comment by beckettsean** [comment]
@mark-rushakoff is this something that can be folded into the automated testing pipeline?

**Comment by mark-rushakoff** [comment]
@beckettsean Yes, that makes sense. We're not quite ready to tackle that yet, but I'll add it to the internal tracker.

**Comment by jsternberg** [comment]
I'm going to close this issue since it's very vague so it doesn't necessarily have a resolution. We should absolutely do this, but I'm not sure we need an issue for it. We can reopen though if you think this issue has some value.
