### ISSUE TITLE
[feature request] Allow queries to have wildcards and fields

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#3582]
This PR https://github.com/influxdb/influxdb/pull/3580 imposes a restriction to not allow queries as follows:

```
select *, foo from bar
select foo, * from bar
select *, * from bar
select * from bar group by time(1m), *
```

As the query engine does not currently support them.

We should add support for those types of queries and remove this restriction.

**Comment by otoolep** [comment]
I opened a ticket about this months ago, but @pauldix closed it. I still think it's a good idea though.

https://github.com/influxdb/influxdb/issues/1634

**Comment by jsternberg** [comment]
This wildcard functionality is now supported in the new query engine so I'm going to close this.

**Comment by botzill** [comment]
Sorry to ask this here, but do we allow things like?

``select *_field from bar``
