### ISSUE TITLE
[feature request] Parse query math values as correct type rather than casting all to float64

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#3614]
Started with PR https://github.com/influxdb/influxdb/pull/3611.

If a query such as `SELECT value * 2` is executed `2` should be parsed as an `int64` so that if `value` is also an `int64` then true integer math is performed. With PR 3611 merged, precision may be lost for integer values greater than 2^53.

**Comment by jsternberg** [comment]
#5744 should take care of this. Closing this one since we have another ticket for this.
