### ISSUE TITLE
[0.9.3-nightly-9ece632] SELECT returns different data depending on which node in cluster was queried

### ISSUE THREAD

**Issue by mjdesa** [influxdata/influxdb#3619]
Added nodes one at a time, starting with a single node. A total of 4 nodes were added. When I query each node individually I get different results. One server seems to get all the data, but each other server has incomplete data.

**Server A**
```
time	value
2015-08-10T22:54:33.05446861Z	100
2015-08-10T22:58:10.784645976Z	10432
2015-08-10T22:58:14.913099954Z	1043
```

**Server B**
```
test
place:gym

time	value
2015-08-10T22:55:00.890690866Z	104
test
place:home

time	value
2015-08-10T22:54:33.05446861Z	100
2015-08-10T22:58:10.784645976Z	10432
2015-08-10T22:58:14.913099954Z	1043
2015-08-10T23:31:33.92784854Z	19
test
place:work

time	value
2015-08-10T22:54:48.406966337Z	102
2015-08-10T22:57:50.743234314Z	105
2015-08-10T22:57:56.783246731Z	1043
```

**Server C**
```
test
place:gym

time	value
2015-08-10T22:55:00.890690866Z	104
test
place:home

time	value
2015-08-10T23:31:33.92784854Z	19
test
place:work

time	value
2015-08-10T22:54:48.406966337Z	102
2015-08-10T22:57:50.743234314Z	105
2015-08-10T22:57:56.783246731Z	1043
```

**Server D**
```
Couldn't connect to host (http://54.176.52.24:8086): error
```

Also `show servers` returns this

```
id	cluster_addr	raft
1	"B:8088"	true
2	"C:8088"	true
3	"D:8088"	false
```

**Comment by beckettsean** [comment]
@mjdesa I don't think that's a healthy cluster. The output of `show servers` looks wrong, in that there are three nodes, not four, and only two are participating in the raft consensus. What led you to believe that all four nodes had joined the cluster?

**Comment by mjdesa** [comment]
I can connect to a database that I create on any one of them.

All the data that I wrote was available in **Server B**, and I wrote data to each node.

**Comment by otoolep** [comment]
I worked with @mjdesa on some of this, and asked him to open a ticket. I'll take a look during the 0.9.4 cycle to see if we do have an issue.

**Comment by otoolep** [comment]
Not going to look into this before 0.9.4 -- pushing out.

**Comment by pauldix** [comment]
Is this still an issue?

**Comment by otoolep** [comment]
Actually, there were quite a few fixes around these types of issues recently. I have not tested it, but I wouldn't be surprised if it was fixed.

Perhaps @mjdesa could retest with latest master code, and close if it looks fixed?

**Comment by jwilder** [comment]
This is possible while writes are queued up in hinted handoff.  If a query is executed on a node that has a shard locally, but it's not fully up to date, it will use the local shard.  We don't have any way of determining (at a cluster level) how up to data local vs remote shards are.

One way to avoid this now would be to use a write concern of `ALL` to ensure all nodes accepted a write.

**Comment by toddboom** [comment]
Closing this out because it's no longer applicable.
