### ISSUE TITLE
[feature request] keep last value or fill(previous) without a group by

### ISSUE THREAD

**Issue by timgriffiths** [influxdata/influxdb#3633]
I understand we have the fill(previous) option available to me, but this only applies if i am using a group by.

I currently trying to store and graph exchange market data and we don't want to use any sort of aggregation we just want to give influxdb a time range and get back the raw data, and with out the last value it's harder to see what's going on, graphite has this very nice function called keepLastValue which will give you the last value before your time range you selected starts and also sets the last value at the end of your time window (if there is not a data point at the start and end of your time windows)

for example, if i ask for a time window between 13:45:33 and 13:45:43 

and your data looked like this

13:45:32 - 4
13:45:35 - 5
13:45:40 - 6

keep last would give you a data set that looked like

13:45:33 - 4
13:45:35 - 5
13:45:40 - 6
13:45:43 - 6

making plotting a step graph very easy and shows the user what really happening with their dataset.

**Comment by pauldix** [comment]
It doesn't make sense to use `fill` for this since fill works in the context of a time series with regular intervals. This is more like putting a data point at the start time and at the end time of the query.

I think it would be some sort of new function that works with raw queries only. Will have to address this at some point in the future.

**Comment by jsternberg** [comment]
I don't think this issue makes any sense in the context of how fill currently works so I'm going to close this for now. Something related, but different enough to actually be feasible, would be #7216. I think that one is a request to have fill create points for timestamps where other auxiliary fields have points and that is feasible.
