### ISSUE TITLE
[feature request] allow for mixed units when specifying retention policy durations

### ISSUE THREAD

**Issue by olivierHa** [influxdata/influxdb#3634]
Hello, 

On Influxdb version 0.9.2, when creating a policy retention like : 

```
create RETENTION POLICY "1w" ON test DURATION 1w REPLICATION 1 DEFAULT
```

It creates :

```
/opt/influxdb/influx -execute 'show  RETENTION POLICIEs ON test'
name		duration	replicaN	default
default		0		1		false
1w		168h0m0s	1		true
```

So 1w has been converted to 168h0m0s. Ok this seems legit :)

But we can't create policy retention with this value :(

```
/opt/influxdb/influx -execute 'create RETENTION POLICY "1w" ON test DURATION 168h0m0s REPLICATION 1 DEFAULT'
ERR: error parsing query: found 0m, expected REPLICATION at line 1, char 52
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".

/opt/influxdb/influx -execute 'create RETENTION POLICY "1w" ON test DURATION "168h0m0s" REPLICATION 1 DEFAULT'
ERR: error parsing query: found 168h0m0s, expected duration at line 1, char 48
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```

"168h" works, but we should be able to give the same exact "duration" as shown in "show retention policy"

A side effect (I guess) is that you can't give '24h30m' as a duration

```
/opt/influxdb/influx -execute 'create RETENTION POLICY "test2" ON test DURATION "168h45m" REPLICATION 1 DEFAULT'
ERR: error parsing query: found 168h45m, expected duration at line 1, char 47
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".

/opt/influxdb/influx -execute 'create RETENTION POLICY "test2" ON test DURATION 168h45m REPLICATION 1 DEFAULT'
ERR: error parsing query: found 45m, expected REPLICATION at line 1, char 51
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```

Regards

Olivier

**Comment by beckettsean** [comment]
The fairly easy workaround is to provide the retention policy duration in a single unit rather than mixed units.

**Comment by olivierHa** [comment]
It is easy to workaround, but we should be able to give the same 'value' given by the "show" command when creating a retention policy :

```
/opt/influxdb/influx -execute 'create RETENTION POLICY "testmix" ON test DURATION 10125m REPLICATION 1 DEFAULT'
``` 

gives :

```
oliv@oliv-laptop ~ $ /opt/influxdb/influx -execute 'show retention policies on test'
name	duration	replicaN	default
default	0		 1		false
tesmix 	168h45m0s	1	true
```

But we can't create a policy with "168h45m0s" as value for duration .... 

Olivier

**Comment by beckettsean** [comment]
@olivierHa I do understand your point. I'm not disputing whether it's useful, I'm merely saying it's not a bug, just slightly annoying behavior with a trivial workaround. Please notice I left the issue open and changed it into a feature request to deliver the functionality you requested.

**Comment by olivierHa** [comment]
Thanks.
I am developing a puppet module to install influx, that's why i was looking for "reusable" value for idempotency. As a workaround on my side, i am converting everything to seconds.

**Comment by lmx1989219** [comment]
why me set my custom retetion policy default then i can not cross cli query series?So i set default to default and the series i can query too.

**Comment by beckettsean** [comment]
@lmx1989219 your question is unclear, and I do not believe it relates in any way to specifying retention policy durations in mixed units. Please send a note to the mailing list influxdb@googlegroups.com if oyu have questions.

**Comment by lmx1989219** [comment]
@beckettsean 
thanks for your suggest,and now the reason is that i write data with influxdbAPI without specify the retention name.

**Comment by beckettsean** [comment]
@jsternberg this is fantastic! I assume that the change is universal within InfluxQL, and not just for retention policy durations?

**Comment by jsternberg** [comment]
It should be universal.
