### ISSUE TITLE
[feature request] grouping on fields

### ISSUE THREAD

**Issue by eminden** [influxdata/influxdb#3637]
influxdb supports grouping on tags but not fields, is there any plan to support grouping on fields?

I am asking this to decide how to write data to influxdb, this way by supporting grouping on fields I can choose to write values as fields which may cause high tag cardinality problems in case the value is written as a tag.

**Comment by otoolep** [comment]
No, this is not on the roadmap right now. If the cardinality is that high, such it would be a problem to store the value as a tag, a GROUP BY that same cardinality wouldn't make much sense, right?

**Comment by jsternberg** [comment]
I don't think we're going to do this since that is supposed to be a central feature of tags. I don't believe it would be feasible in terms of performance to also do this with fields.
