### ISSUE TITLE
multiple instances of the same function confuses CQ output

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3643]
From https://github.com/influxdb/influxdb/issues/3469#issuecomment-130420280.

A CQ like `SELECT MEAN(value1), MEAN(value2) FROM...` writes a single column to the result series, called `mean`. If an `AS` alias is used both values are successfully written.

We could throw a parser error when multiple identical functions are used without an explicit alias, or we could write the values into the new series as `mean_value1`, `mean_value2`. Not sure if there are other fixes that make sense.

**Comment by jwilder** [comment]
Fixed via #5742
