### ISSUE TITLE
Wire up HISTOGRAM transformation

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3674]

**Comment by tisba** [comment]
I know, +1 is kind of stupid, but this is actually one of the major points, why we still run on 0.8.9 :-/

**Comment by alexisvapillon** [comment]
Is there an ETA for this feature?

**Comment by The-Nik** [comment]
Would love to have this feature, +1

**Comment by comcomservices** [comment]
+1

**Comment by garymcleanhall** [comment]
+1

**Comment by The-Nik** [comment]
+1 for Milestone 0.9.6

**Comment by bluemonk3y** [comment]
+1 pls!

**Comment by ogrant** [comment]
+1

**Comment by sainathadapa** [comment]
+1

**Comment by aadrian** [comment]
+1

**Comment by aseure** [comment]
+1

**Comment by kunapuli09** [comment]
+1

**Comment by mitar** [comment]
That would be really great! I would suggest that there are three functions:
* frequencies: for each value number of occurrences in all datapoints in the interval
* most often: the most often occurring value of all datapoints in the interval
* least often: the least often occurring value of all datapoints in the interval

The good thing is that those operations can be nicely defined also on non-numeric values. So one can store state value of some sensor and then for example aggregate the interval into which state was the most common inside the interval (mean does not have really any meaning when values are just state indexes).

**Comment by enviroeye** [comment]
+1

**Comment by mynameisdaniil** [comment]
+1, if it helps

**Comment by tux-00** [comment]
+1

**Comment by darkcrawler01** [comment]
+1

**Comment by bmironenko** [comment]
+1

**Comment by adrianlzt** [comment]
+1

**Comment by bcavagnolo** [comment]
+1

**Comment by runner-mei** [comment]
+1

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by sidgod** [comment]
+1

**Comment by sikadiamond** [comment]
+1

**Comment by AsyDemo** [comment]
+1 Would love this to make nice heatmaps (a.k.a histograms over time).

**Comment by jkschneider** [comment]
Critical feature. +1

**Comment by rayNymous** [comment]
why so fuckin slow?
