### ISSUE TITLE
Think about how to resolve identifier/keyword confusion

### ISSUE THREAD

**Issue by DanielMorsing** [influxdata/influxdb#3745]
Right now we have a lot of keywords that people might use unintentionally. Examples include default, read, write, from, duration etc.

I tried doing a fix for #3654, where if we expected an identifier but found a keyword, we would use the keyword as an identifier, but this gets confusing in the case where you forget an identifier. The following keyword would then be interpreted as the identifier and mess up any error reporting.

One way of fixing this is to keep track of the potential follow set for the rule currently being produced, but this has a huge impact on the number of functions in the parser, since we then have to have a special function for each context in which a production can exist that is followed by a keyword

My preferred way of fixing this would be to trim the number of keywords heavily and rely on predeclared identifiers in a typechecking pass done after the parse. It seems like the typechecker is needed anyway, since we do a lot of ad hoc verification right now which could be more rigorously done in a separate pass.

**Comment by pauldix** [comment]
@DanielMorsing can you do more investigation on this? What would be the impact of your preferred way of doing things? We still have a ton of keywords and I'm guessing that the number is going to go up a bit over time.

**Comment by DanielMorsing** [comment]
It's mostly a case of defining all the scopes for where we expect a keyword now and putting in predeclared identifiers. Shouldn't be too hard.

**Comment by DanielMorsing** [comment]
@beckettsean could you unassign me from this issue and #3654?

**Comment by jsternberg** [comment]
I'm going to close this since I don't think we're going to have any further changes to the query language before 1.0. We will put in a notice that bare identifiers (those not surrounded by double quotes) may conflict with keywords and that clients should always surround identifiers with double quotes for the best compatibility.

Maybe we'll revisit this if we decide to make a change to the query language after 1.0.
