### ISSUE TITLE
Explicitly SELECTing time as non-first field returns wrong columns

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#3779]
The following query:

`SELECT value,time FROM db0.rp0.cpu`

results in incorrectly-ordered columns:

```
{"results":[{"series":[{"name":"cpu","columns":["value","time"],"values":[["2015-08-20T23:57:35.973310065Z",1]]}]}]}
```

**Comment by otoolep** [comment]
Will try to get this into 0.9.3, but time is passing.

**Comment by otoolep** [comment]
cc @corylanou

**Comment by jsternberg** [comment]
This doesn't seem to be relevant anymore since we remove `time` from the select query automatically now.

Closing this unless someone else thinks it's still relevant.
