### ISSUE TITLE
[0.9.2] no error on timestamp that exceeds maximum time rage

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3789]
The write returns a 204

```
curl -i -XPOST 'http://localhost:8086/write?db=mydb&precision=s' -d 'ts value=0.64 14401794881'
HTTP/1.1 204 No Content
Request-Id: 2ecf5a9e-482e-11e5-858e-000000000000
X-Influxdb-Version: 0.9.2
Date: Fri, 21 Aug 2015 17:58:09 GMT
```

but there are no points in the measurement:

```
> select * from ts where time > now()
> 
```

The timestamp of 14,401,794,881 seconds exceeds the max value for InfluxDB: https://influxdb.com/docs/v0.9/guides/troubleshooting.html#time-ranges. Presumably we should return an error on the write.

**Comment by pauldix** [comment]
We should accept the write. Instead we should change the default query end time. Logged #5047 to track

**Comment by jsternberg** [comment]
Closing this since it seems like we should implement #5047 as @pauldix said instead.
