### ISSUE TITLE
[Configuration] Limit the memory usage of influxdb

### ISSUE THREAD

**Issue by FGRibreau** [influxdata/influxdb#38]
Hi guys!

I don't see any configuration option to limit the memory usage of influxdb, how can I achieve that? 

If it's currently not configurable, it's definitely my first concern right now (in order to use it as a shadow-slave in production).

**Comment by guruprasadar** [comment]
I am using latest influxdb (0.10). Influxdb size id around 1.5 GB. Memory it is consuming more than 6GB. Is any issue with this. My db size will grow continuously now i am worried may be i will get out of memory. 

Below is the top output for influx db
11222 influxdb  20   0 9593m 6.8g 343m S  0.7 44.0  24:59.95 influxd

du -sh influxdb
1.5G	 influxdb

**Comment by DavidSoong128** [comment]
what is the result now about the question? , if someone know that,please tell me, thank you

**Comment by pistonsky** [comment]
I had the same issue with memory overload.

I was using influxdb in a docker container from tutum/influxdb, the version was 0.9.6.1. Whenever I ran a query with GROUP BY time(1h) for the period of 7 days (it is about 10K points to process), my influxdb container consumed all available memory (~4GB) and got killed by linux kernel.

Then I switched to `influxdb` container (not `tutum/influxdb`), which had the version 1.0.1. Let me test it and I will tell you if that solved the memory issue.

**Comment by pistonsky** [comment]
Unfortunately, I have to update this.

The new influxdb `1.0.1` also fails. After working more or less stable for couple hours, sometimes even lowering memory to ~400MB, after some bigger query with larger timeframe in GROUP BY clause, it finally failed again, being killed by kernel just like `0.9.6.1`.

Please suggest a solution!

**Comment by psinghsp** [comment]
Same problem here with latest 1.2. I can only use this product if it can restrain itself within the limits of the memory I allocate to it. I should be able to trade off "time" for "memory" consumption instead of influxd just getting killed by the Linux kernel.

May be I am not configuring influxd properly. Can someone please comment?

**Comment by tau0** [comment]
<img width="1374" alt="screen shot 2017-05-26 at 22 35 50" src="https://cloud.githubusercontent.com/assets/6191905/26509942/b363ef06-4263-11e7-8268-62e25e1e989c.png">

**Comment by helwodlrol** [comment]
how did you solve this problem?

**Comment by lukaszgryglicki** [comment]
What is the status of this?
I have `influxd` process consuming 29G of 32G RAM and it failed to copy one database to another due to lack of memory recently...
Is there a way to limit `influxd` RAM usage?

**Comment by kevinpattison** [comment]
I'll add a 2018 entry to this 2013 serious bug report. Please can this be addressed. InfluxDB crashing during the night, I wake up and restart it but I've lost 8 hours data forever.

Ridiculous that process this mature cannot manage it's own memory usage or recover from a query going OOM.

**Comment by kevinpattison** [comment]
Just to clarify, the original query is still valid. This was closed by pauldix when a memory leak was resolved, but that was not the original request.

**Comment by Alexadra** [comment]
What is the status of this issue? We still experience the same for the latest version

**Comment by guruprasadar** [comment]
I also faced same issue long back. After fixing the schema never faced the
issue.

**Comment by SniperCZE** [comment]
Hello, we're facing same problem - influx consumes all available memory and OOM shot it. Please reopen and implement some maximal limit.

**Comment by xiandong79** [comment]
facing the problem~

**Comment by iBug** [comment]
My `influxd` is constantly dying of OOM. I worked around this issue by modifying the Systemd config for InfluxDB and added the following content:

```
[Service]
MemoryMax=131072K
```

This way the InfluxDB daemon has its memory limited to 128 MiB and OOM should kick in when it exceeds the limit.

Still only a workaround, not a solution, but the above trick does at least prevent other important services from being killed by killing `influxd` early.

Note that you should set the value according to your own configuration. My `influxd` typically uses less than 40 MB of RAM so setting a death limit to 128 MiB seems reasonable.

**Comment by Doc999tor** [comment]
Any updates with this issue?

**Comment by Ardeshir81** [comment]
+1

**Comment by DanS123** [comment]
Having the same issue here. 
Small cardinality on the database in question.
Using Grafana to query, and any response that returns a lot of values will quickly ramp RAM up to 100% and then crash the container.
Worse still, when InfluxDB crashes it doesn't cause the container to crash, so our restart=always does not cause a reboot of the container. Whenever this happens a simple restart of the container will get everything back to normal.

**Comment by amiryeshurun** [comment]
I am facing this issue as well.
Using influxdb for monitoring (with Prometheus) is very powerful, but limiting the memory is necessary. Monitoring the monitoring infrastructure is ridiculous. Please help.

**Comment by Fantaztig** [comment]
InfluxDB OSS 2.0 seems to include memory limits for containers.
My guess is we have to wait for the release as the value of fixing it for the current version seems kinda low.

**Comment by dimisjim** [comment]
@Fantaztig are you referring to https://docs.influxdata.com/influxdb/v2.0/reference/config-options/#query-max-memory-bytes ?

**Comment by Fantaztig** [comment]
@dimisjim yes, I only glanced over the config options and took it for a total memory limit
So the problem remains open I guess 😅

**Comment by Jongy** [comment]
Adding myself to the party... Would also be happy to see a solution for this.

**Comment by fkusei** [comment]
InfluxDB memory usage is becoming a major concern here. It's currently using about 44GB of memory (having a database of around 650GB).

**Comment by oliviertm** [comment]
I have the same problem, but after some tests including stop, start, version update (1.7.6, 1.8.3) of influxdb and database drop and import, I came to the conclusion that this doesn't looks like a memory leak, but a consequence of the database structure.
This is quite well explain in this post : https://help.aiven.io/en/articles/1640634-influxdb-series-cardinality and also in this documentation https://docs.influxdata.com/influxdb/v1.4/guides/hardware_sizing/#when-do-i-need-more-ram

**Comment by JackThird** [comment]
The first question was never resolved and ticket was closed, can I understand why?
Since 2013, there is no way to limit influxdb memory, right?
