### ISSUE TITLE
Should be able to do deletes as a cluster admin

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#381]
This returns an insufficient permissions currently. A cluster admin should be able to do EVERYTHING

**Comment by dmeytin** [comment]
Is this issue is back again?
I'm using InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)

**Comment by gunnaraasen** [comment]
@dmeytin There is no longer any development being done on the 0.8.8 branch. There is a new 0.8.9 version, but that just includes some export code to support migrations to 0.9.
