### ISSUE TITLE
[0.9.2] Format of JSON response differs based on value of 'time' parameter in WHERE clause

### ISSUE THREAD

**Issue by erikriverson** [influxdata/influxdb#3821]
I am running two queries, only changing the value of the 'time' parameter in my WHERE clause. I am trying to get a simple count of records for a certain measurement. My database contains no data for either yesterday or today, but the format of the resulting JSON differs depending on which day I ask for. 

For yesterday (i.e., 2015-08-23 at the time of this note), I receive the following structure in the return value, including a 'series' name and 'values'. 

````
bash-3.2$ curl -G "https://<influx_url>:8086/query" -u influxdb:***  --data-urlencode "q=SELECT count(x) from accelerometer WHERE time > '2015-08-23 00:00:00' AND time < '2015-08-23 00:01:00' fill(0)" --data-urlencode "db=production"

{
  "results": [
    {
      "series": [
        {
          "name": "accelerometer",
          "columns": [
            "time",
            "count"
          ],
          "values": [
            [
              "2015-08-23T00:00:00.000000001Z",
              0
            ]
          ]
        }
      ]
    }
  ]
}
````

Next, I change the date portion of the 'time' parameter to today (2015-08-24). In the resulting JSON, the "results" component is now an array containing only an empty object. 

````
bash-3.2$ curl -G "https://<influx_url>:8086/query" -u influxdb:***  --data-urlencode "q=SELECT count(x) from accelerometer WHERE time > '2015-08-24 00:00:00' AND time < '2015-08-24 00:01:00' fill(0)" --data-urlencode "db=production" 

{
  "results": [
    {}
  ]
}
````

**Comment by beckettsean** [comment]
@erikriverson which version of InfluxDB are you running?

**Comment by erikriverson** [comment]
@beckettsean This is a hosted instance, which the web admin tool is reporting as InfluxDB v0.9.2

**Comment by erikriverson** [comment]
Since this seems to be a time-based issue, just wanted to follow-up to see if I can reproduce today. 

Currently, I can run the query and obtain results with values (i.e., a count of 0, like in the first case above) for values up to and including 2015-08-30. When I run the query with 2015-08-31 or later, I get JSON with empty results. 

The behavior does not necessarily appear to relate to the 'current day' as the initial report might imply. But by extending the date 'far enough' into the future, I can reproduce the empty results response.

**Comment by beckettsean** [comment]
Pulling the queries out of the log so they are easier to compare:

`SELECT count(x) from accelerometer WHERE time > '2015-08-23 00:00:00' AND time < '2015-08-23 00:01:00' fill(0)` correctly returns COUNT of 0.

`SELECT count(x) from accelerometer WHERE time > '2015-08-24 00:00:00' AND time < '2015-08-24 00:01:00' fill(0)` returns empty results. With a `fill(0)` in the query that should be a `0`.

**Comment by jsternberg** [comment]
This doesn't seem to be an issue anymore. Fill values only apply to aggregate queries with a `GROUP BY time(...)` in the query so the fill shouldn't be applied in these queries. Aggregates with no points in the range will not return a value, but you can use a `GROUP BY` and a time range for a specific bucket with `FILL(0)` to get the zero value.

Please reopen if you think this hasn't been fixed in the latest version. Thanks!
