### ISSUE TITLE
[0.9.3] InfluxDB log password redaction leaves query mangled, but not redacted

### ISSUE THREAD

**Issue by brettdh** [influxdata/influxdb#3883]
Password redaction isn't quite doing its job:
```
[http] 2015/08/28 16:47:52 ::1 - admin [28/Aug/2015:16:47:52 +0000] GET /query?[REDACTED]
q[REDACTED]=[REDACTED]C[REDACTED]R[REDACTED]E[REDACTED]A[REDACTED]T[REDACTED]E[REDACTED]+
[REDACTED]U[REDACTED]S[REDACTED]E[REDACTED]R[REDACTED]+
[REDACTED]r[REDACTED]e[REDACTED]a[REDACTED]d[REDACTED]e[REDACTED]r[REDACTED]+
[REDACTED]W[REDACTED]I[REDACTED]T[REDACTED]H[REDACTED]+
[REDACTED]P[REDACTED]A[REDACTED]S[REDACTED]S[REDACTED]W[REDACTED]O[REDACTED]R[REDACTED]D
[REDACTED]...
```

Which is something like `'[REDACTED]'.join("q=CREATE+USER+reader+WITH+PASSWORD+[etc]")`

Not quite what you had in mind, I imagine. ;-)

**Comment by otoolep** [comment]
@gunnaraasen ?

**Comment by jsternberg** [comment]
Does this still exist and how can we reproduce this issue?

**Comment by gunnaraasen** [comment]
This issue still exists and needs to be fixed. The HTTP response logger simply replaces any strings in the query params that match the password right now. This exposes info about the password value itself and can lead to the situation above, where the password is set as a space.
