### ISSUE TITLE
Edge browser caching responses really screws up the admin UI

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3893]
See https://github.com/influxdb/influxdb/issues/3834#issuecomment-135772064 for the results from admin UI in Edge vs. https://github.com/influxdb/influxdb/issues/3834#issuecomment-135922575 from the CLI.

From @mvadu:

"Looks like Edge caches ajax responses (even when there is no cache header in the response), and it messes up what is shown on UI. I could not recreate the issue on Edge after I opened Developer console, and set "Always refresh from server" option."

Any way we can force cache expiry or disable caching for the admin UI?

**Comment by mvadu** [comment]
I think if the Ajax responses have a `cache-control: private, no-cache` will firce any sane browser to not to cache the responses. I am not sure how to do that in golang though.
