### ISSUE TITLE
[0.9.3] invalid timestamp format should throw parser error, not be ignored

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3932]
When giving explicit timestamps in queries they must be single-quoted:

```
> select count(value) from cpu_idle where time >= '2015-08-25T20:00:00Z' and time <= '2015-08-25T21:00:00Z'  group by time(10m)
name: cpu_idle
--------------
time			count
2015-08-25T20:00:00Z	8
2015-08-25T20:10:00Z	144
2015-08-25T20:20:00Z	688
2015-08-25T20:30:00Z	688
2015-08-25T20:40:00Z	688
2015-08-25T20:50:00Z	680
2015-08-25T21:00:00Z	688
```

Double-quoting returns results as if there were no time restriction at all:

```
> select count(value) from cpu_idle where time > "2015-08-25T20:00:00Z" and time < "2015-08-25T21:00:00Z"  group by time(10m)
name: cpu_idle
--------------
time			count
1970-01-01T00:00:00Z	618464

> select count(value) from cpu_idle
name: cpu_idle
--------------
time			count
1970-01-01T00:00:00Z	618464
```

**Comment by corylanou** [comment]
We should specifically return an error if we detected a literal (double quotes instead of single) and error with something like `time literals need to be single quoted, not double quoted`.

**Comment by beckettsean** [comment]
Per Paul, in a `WHERE time` clause, first try to parse the double-quoted value as a timestamp, not an identifier. If that fails fall back to parsing it as an identifier.

**Comment by jsternberg** [comment]
The reason for this problem is because the function that retrieves the time range doesn't send back an error when it finds an objectionable time comparison like was done here.

The function that needs to be changed is `influxql.TimeRange()`. I can probably do this one with #3290.
