### ISSUE TITLE
[feature request] select distinct data point times from database

### ISSUE THREAD

**Issue by jeremyVignelles** [influxdata/influxdb#3945]
Hi,
It would be nice to have a syntax like this one:

```
SELECT DISTINCT(time) FROM measurement
```

or this one

```
SELECT time FROM measurement GROUP BY time
```

to select the data point times, in order to show a timeline to the user, on which he can click to show the data at this time point.

See #3902

**Comment by jeremyVignelles** [comment]
@beckettsean any updates on this?

**Comment by beckettsean** [comment]
@jeremyVignelles no updates. I would not expect this to be implemented soon.
