### ISSUE TITLE
[feature request] ORDER BY tag values

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3954]

**Comment by Jhors2** [comment]
+1, would love this.  Would also like to pass more than 1 tag to the order by operation so they are alpha sorted first by tag1 then by tag2, etc.

**Comment by muratcorlu** [comment]
Will that issue meet our needs like that?:

```
select count(values) from events group by event_type order by count desc
```

**Comment by beckettsean** [comment]
@muratcorlu no, that is a separate request. This is only for ordering by tag values, not by function return values.

**Comment by timgriffiths** [comment]
+1

**Comment by groblus** [comment]
+1
plus order by <field>

**Comment by dstreppa** [comment]
very useful
+1

**Comment by envintus** [comment]
:+1:

**Comment by martinschuberts** [comment]
Hi influxers, 
any update on this issue? Anything planned?

**Comment by gerrickw** [comment]
Any workaround for this?  For some reason influxdb decides tag values return should be sorted 100,101,102,...,198,199,001,002,003.  As grafana writes whatever is returned by the database I have a large drop down menu of template values with a whacky sort that makes people confused how it even determined that is the correct sort.

**Comment by haidaraM** [comment]
Any update ?

**Comment by dominic-miglar** [comment]
+1

**Comment by tabeyti** [comment]
+1

**Comment by JamesGalt** [comment]
Hi, Would be great especially if we use the tag to avoid overriding when 2 points with same tags values and same timestamp are written.
Thanks

**Comment by NateZimmer** [comment]
So if someone is using influxDB to track device diagnostics naturally one would wish to sort by value. For example, if one is investigating device resets, one would wish to sort a list and prioritize the devices that are resetting the most. Without this... metrics that target problematic units are nearly impossible.

**Comment by jcsdatera** [comment]
+1

**Comment by dannybeeckman** [comment]
+1

**Comment by JulienChampseix** [comment]
@beckettsean we are now in August 2018 (issue created in 2015)  any update on it or plan in influx roadmap ? (order by part capability is really a strong functionnality missing to influx)

**Comment by umatomba** [comment]
we are now in Mar 2019 :) I will take clickhouse soon

**Comment by laudukang** [comment]
+1

2019

**Comment by imohidul** [comment]
what are you doing guys please do something about this matter, irritating sort system group by tag it is 2019 now

**Comment by debmalyapan53** [comment]
+1

**Comment by Vanderlan** [comment]
+1

**Comment by matheusnicolas** [comment]
+1

**Comment by GersonSales** [comment]
+1

**Comment by RamonSalem** [comment]
+1

**Comment by cybermax** [comment]
+1

**Comment by antegulin** [comment]
+1, super basic feature for a database

**Comment by jkalnik** [comment]
+1, we hit that problem too. It would be very nice to have this function.

**Comment by slachtar** [comment]
+1, any announcement on this issue?

**Comment by fionera** [comment]
+1, please <3

**Comment by windkh** [comment]
+1000

**Comment by ahgit101** [comment]
Any update in this issue. Even a statement to say if it's in scope or there are no plans for this?

**Comment by wurmrobert** [comment]
+1

**Comment by shkarimpour** [comment]
+1

**Comment by chopchopjames** [comment]
+1

**Comment by thomas-tf** [comment]
+1

**Comment by valerioformato** [comment]
+1

**Comment by Vebryn** [comment]
+1

**Comment by eRudy** [comment]
+1

**Comment by ouinouin** [comment]
any plan to add this feature ?

**Comment by sanderson** [comment]
Support for sorting by tags will likely not be added to InfluxQL, but it is already supported in Flux.

**Comment by VytasMule** [comment]
+1

**Comment by gabzim** [comment]
> Support for sorting by tags will likely not be added to InfluxQL, but it is already supported in Flux.

I would buy this, the problem is that flux is orders of magnitude slower than influxql.

**Comment by Styx13** [comment]
+1

**Comment by gabzim** [comment]
> > Support for sorting by tags will likely not be added to InfluxQL, but it is already supported in Flux.
> 
> I would buy this, the problem is that flux is orders of magnitude slower than influxql.

I was on influx 1.x, I've noticed that Influx 2.x has much better performance for flux, so I take that back.

**Comment by AlexHeylin** [comment]
+1

**Comment by riteshs-cashify** [comment]
+1

**Comment by rijenkii** [comment]
> Support for sorting by tags will likely not be added to InfluxQL, but it is already supported in Flux.

What about influx 3.0, where flux is basically deprecated?

**Comment by pauldix** [comment]
@rijenkii InfluxDB 3.0 has a fully featured SQL query engine so this is supported in that language. InfluxQL is also supported, but doesn't support sorting by tags.
