### ISSUE TITLE
[0.9.2] inconsistent results for SHOW MEASUREMENTS query

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3961]
From a support ticket (1183)

----------------
I am getting strange results when using show measurements while using "where tag-key = tag-value"

for example 
SHOW MEASUREMENTS WHERE node = 'ABSFU' AND system = 'LB301'

If I run 
SHOW SERIES WHERE node = 'ABSFU' AND system = 'LB301'

It gives a result that looks like this

MV 
_keybuildingnodeorig_tagroomsystem 
MV,building=A0095048,node=ABSFU,orig_tag=A0095048_LB301_GM201_ABSFU_MV,room=GM201,system=LB301"A0095048""ABSFU""A0095048_LB301_GM201_ABSFU_MV""GM201""LB301" 
MV,building=A0095048,node=ABSFU,orig_tag=A0095048_LB301_GM401_ABSFU_MV,room=GM401,system=LB301"A0095048""ABSFU""A0095048_LB301_GM401_ABSFU_MV""GM401""LB301"

But the Show measurements query only sometimes shows MV as a result and returns blank most of the time.

I would expect it to always return the MV as result, or am I doing it wrong?

-----------------

I can verify that the user's database returns `{"results":[{}]}` more than half the time, but sometimes returns `{"results":[{"series":[{"name":"measurements","columns":["name"],"values":[["MV"]]}]}]}` for the same query. No change except repeatedly submitting the same query from the Admin UI:

![screen shot 2015-09-02 at 15 38 57](https://cloud.githubusercontent.com/assets/6537329/9646475/ec7ca314-5188-11e5-9186-b8c922565b55.png)
![screen shot 2015-09-02 at 15 39 08](https://cloud.githubusercontent.com/assets/6537329/9646476/edd15840-5188-11e5-9742-9a4edbf6d83f.png)

**Comment by beckettsean** [comment]
Single node cluster.

**Comment by beckettsean** [comment]
@dgnorton I will get you the customer details via email, and I'll see if we can get a copy of the data.

**Comment by jsternberg** [comment]
The query engine had a complete refactor in 0.11. If anybody runs into this issue using the newer version, please make a new ticket. Thank you.
