### ISSUE TITLE
[feature request] Support month and year as duration unit

### ISSUE THREAD

**Issue by ghost** [influxdata/influxdb#3991]
For example: 
- 1M for 1 month
- 1y for 1 year

Its useful for me when i want to query the data last month and year...

**Comment by beckettsean** [comment]
@diiidiii the challenge with supporting `month` or `year` durations is that they are not regular. It requires InfluxDB to be aware of things like variable month lengths, leap years, etc. This is a potential feature but certainly not a short-term one.

**Comment by diiidiii** [comment]
> they are not regular
Yes thats the reason why i need it. I know it isn't easy to implement but i just want to notify you that this will maybe a good feature. A workaround is 720h or 30d what i use at the moment.

**Comment by daviesalex** [comment]
Anybody that comes across this because Grafana is sending queries that have ''1y'' in them, see https://github.com/grafana/grafana/issues/2874

The workaround to that bug is to set a minimum span on the grafana pane.

**Comment by dstreppa** [comment]
+1

**Comment by jaapz** [comment]
Would be great to have this. It's not a trivial problem, but then again, InfluxDB is a *time*-series database, so it should have a good notion of what certain time durations are, right?

**Comment by Stibbons** [comment]
Agree, I would like to be able to group by month or year and have grafana at least handle all subtilities automatically

**Comment by stantonk** [comment]
👍

**Comment by ryanmills** [comment]
+1 need ability to group by time(1M) or time(1y)

**Comment by Wolfgang1966** [comment]
I would also like to have the ability to group by month and year.

Thanks a lot

Wolfgang

**Comment by Wolfgang1966** [comment]
@beckettsean By the way, days are not regular also ... thinking of DST switches, leap seconds a.s.o. :)

**Comment by tyhunt99** [comment]
+1 need ability to group by time(1M) (month) or time(1y) (year)

**Comment by ale91x** [comment]
+1 need ability to group by time(1M(month)), (1y(year))

**Comment by xsherlockpl** [comment]
I cant get solar production for the last month with just one query without that.   +1

**Comment by olro** [comment]
+1 in general it is nice to have e.g. consumption data for water, electricity, gas on a per month/year basis

**Comment by m-tymchyk** [comment]
+1 need ability to group by time(1M) (month) or time(1y) (year)

**Comment by smalenfant** [comment]
+1 We derive bandwidth capacity by month, this makes it a little hard. Currently using 4w or 30d. Data not far off, just not exactly what the report viewer expects.

**Comment by mkren** [comment]
+1

**Comment by gtt116** [comment]
+1 need ability to group by time(1M) (month) or time(1y) (year)

**Comment by lcarsos** [comment]
+1 grouping by 30d only gets you so far, and frustrates users when they compare against previous results and numbers for finished months change.

**Comment by cicciopizza** [comment]
+1 need ability to group by  month / year. ex. 1M / 1Y

**Comment by mikegroot** [comment]
+1

**Comment by chfumero** [comment]
+1

**Comment by zandacw** [comment]
+1

**Comment by zopyx** [comment]
+100

**Comment by zopyx** [comment]
My workaround for grouping rows by year+month is by adding a tag "ym=YYYY-MM" to each row.
Then you can "GROUP BY ym".

**Comment by Codelica** [comment]
Which is fine if you have relatively low series series cardinality or lots of RAM.   But otherwise the 12x annual multiplier is too heavy for measurements like ours.  I'm hoping Influx will provide the ability natively, or potentially provide some timestamp functions as a workaround similar to what people do for groupings like this on SQL servers.

**Comment by SilentButeo2** [comment]
+1
Used influxdb because it was described as a time series database. So grouping /month, /year, was something I thought was implemented by default. My mistake it seems. I know dates can be difficult, but with things like tzdata, you can do great stuff.
Keep up the good work guys!

**Comment by grydstedt** [comment]
+1

**Comment by ADahmani** [comment]
+1

**Comment by Oxydros** [comment]
+1

**Comment by mythfish** [comment]
+1

**Comment by MThomassen** [comment]
+1

**Comment by patrickvallet** [comment]
+1, really important for me too.

**Comment by lqjing** [comment]
+1

**Comment by matyunin** [comment]
+1

**Comment by steveseeger** [comment]
+1.. couldn't believe this didn't make 1.0 priority. Even a low performance solution. It requires setting the relative timezone, is that the complexity issue?  I assumed this would be here before switching over our platform from MySQL.  Have to change to loop and query per month and manually construct results..

**Comment by chywwq** [comment]
+1

**Comment by pgayvallet** [comment]
+1. Blocker for our usages.

**Comment by SR-G** [comment]
Also +1, would definitely be very usefull.

**Comment by aguiraf** [comment]
+1

**Comment by KlonD90** [comment]
+1

**Comment by g-k-r** [comment]
+1 
and while you are at it you might want to consider adding Q for quarter, so 'timestamp/Q' translates to time frame of the quarter the timestamp is in. i.e. 2017-10-12/Q -> 2017-10-01 >= t < 2018-01-01] and Group By time (1Q) aggregates by these time frames.

thanks for a great tool

**Comment by dietert** [comment]
+1

**Comment by akarakotov** [comment]
+1
grafana+influxdb is the best solution for real-time monitoring and alerting, but we can't right now detect problems within calendar month period because of this feature absense.

**Comment by codingheld** [comment]
+1
This is a blocker for production use...

**Comment by martinschuberts** [comment]
+1

**Comment by zopyx** [comment]
Hard to believe how ignorant and arrogant the Influx-DB team is here on this issue.

**Comment by dgomes** [comment]
+1

**Comment by pauldix** [comment]
This will be included as part of our new query engine, [IFQL](https://github.com/influxdata/ifql). This would be something added to the `window` function in the new language.

Unfortunately, handling this in our existing query engine would be very difficult. Addressing many long standing query feature requests are exactly why we set out to create a new query engine and language with it.

**Comment by Wolfgang1966** [comment]
Dear Paul, that's great news!

Thank you very much!

**Comment by kylethebaker** [comment]
@pauldix That sounds promising, do you have an example of what an IFQL query will look like for doing doing a month-to-day aggregate for every month in a year? For example, selecting the sum of some value between the 1st and 15th day of the month, grouped by month and year?

**Comment by Tux12Fun** [comment]
+1 

Would like to see this for a business case, and for a private case.

**Comment by patrickcat** [comment]
+1

**Comment by Scott-St** [comment]
+1

**Comment by patrickvallet** [comment]
Hi,
It will be available in future 1.5 version then?
Many thanks
Regards

**Comment by Pirx99** [comment]
would be really great for me to get 'month' supported soon!

**Comment by HoshangCharania** [comment]
Any update on this issue?

**Comment by mkontula** [comment]
Since it comes up as an additional layer beside actual db there's no way of getting your shard durations nor CQ's to run with calendar intervals. This will probably make some enterprisish customers look elsewhere.  Perhaps you should consider renaming the product Fixed-Interval-Timeseries-DB. Would reflect the reality way better. Also state on your product description: We are a timeseries db, but we don't understand anything about calendars.

**Comment by mr-varga** [comment]
+1

**Comment by kukudemajia** [comment]
+1

**Comment by dlanza1** [comment]
+1

**Comment by marine1988** [comment]
+1

**Comment by michielhub** [comment]
+1

**Comment by yihaozhadan** [comment]
+1

**Comment by Pirx99** [comment]
After waiting too long for this important feature I now moved to a different DB. Sorry guys but without it you can't call it "time-series DB".

**Comment by gsemet** [comment]
We also moved to prometheus.

**Comment by cicciopizza** [comment]
we are also doing tests to migrate on prometheus...
shame because it was a good project...

**Comment by Pirx99** [comment]
I moved to PostgreSQL

**Comment by scmod** [comment]
+1 
from a large amount  of data in timeunit of second, I have to draw the minutely, quarterly, half-hourly, hourly, daily, weekly, monthly or even yearly k-line chart, so I think group by month or year is really
powerful to do these things

**Comment by TheEggi** [comment]
Any update on this one?

**Comment by scmod** [comment]
> Any update on this one?

currently not...

**Comment by aigr** [comment]
+1

**Comment by eraelpeha** [comment]
+1

**Comment by decaillet** [comment]
+1

**Comment by samreaves** [comment]
+1

**Comment by douglasg14b** [comment]
Would very much like to see this as a feature. It's not really possible to create any sort of month-by-month view in grafana for InfluxDB sources..... Unless the month is manually added as a tag.

**Comment by timhallinflux** [comment]
Re-iterating @pauldix comment from above: This will be included as part of our new query engine, `Flux`. This would be something added to the window function in the new language.

Unfortunately, handling this in our existing query engine would be very difficult. Addressing many long standing query feature requests are exactly why we set out to create a new query engine and language with it.

This won't appear in the Flux 0.7 technical preview forthcoming -- but it is very much on our radar to include for GA of Flux.

**Comment by blankroom** [comment]
+1 hope for the feature

**Comment by AleksBelytskyi** [comment]
+1
I need this as well

**Comment by gkatzioura** [comment]
+1 It will be an awesome feature

**Comment by yysyp** [comment]
+1

**Comment by thatguydan** [comment]
+1

**Comment by murelli146** [comment]
+1
GROUP BY time(1Y)

**Comment by frnandu** [comment]
+1

**Comment by robinostlund** [comment]
+1

**Comment by robcowart** [comment]
After discussions with a number of users in the energy sector, "quarterly" is also a valuable option. So...
`GROUP BY time(1q)`

**Comment by Hurleyking** [comment]
+1
GROUP BY time(1Y)
GROUP BY time(1M)
GROUP BY time(1q) "quarterly"

**Comment by throrin19** [comment]
Any news for this request ?

For the month and the year case, I think it's interrested to group on real month and year (ex : For february, group on 1 to 28 february)

**Comment by r2xud** [comment]
+1 Would be very useful.

**Comment by DerMika** [comment]
+1 this is a must-have for us

**Comment by jpldev** [comment]
+1

**Comment by timhallinflux** [comment]
https://github.com/influxdata/influxdb/issues/3991#issuecomment-434127684

**Comment by bussyjd** [comment]
+1

**Comment by kdub454** [comment]
+1

**Comment by pmiddend** [comment]
+1

**Comment by blackw1ng** [comment]
+1
```
GROUP BY time(1Y)
GROUP BY time(1M)
```

**Comment by xsherlockpl** [comment]
It was supposed to be included in the new flux language?
Anyone can confirm that flux 0.12 that is included  with influx_db 1.7.x  has that capability ?
I need to compare month by month  2016-2018 solar production but that can't be done easily with current query language.

**Comment by DerMika** [comment]
I haven't tried it yet, but Flux seems to support months [according to these docs](https://docs.influxdata.com/flux/v0.12/language/lexical-elements#date-and-time-literals)

**Comment by timhallinflux** [comment]
It is not yet supported in any version of Flux.  We will update this issue once it does. But, this is still in plan for us to incorporate support for months, years and other human scale time ranges.  We are working hard to move this forward.

**Comment by polcape** [comment]
+1

**Comment by pantlavanya** [comment]
Hi All,
I am new to influx, What if we create 2 columns with month, year and then do a group by on month and year.? Then we can do monthly and yearly aggregation.

**Comment by Codelica** [comment]
@pantlavanya, you could.  But it will (endlessly) increase your [series cardinality](https://docs.influxdata.com/influxdb/v1.7/concepts/glossary/#series-cardinality).  Depending on your current tags, it could be a drastic or even unworkable option.  As a time-series database, it's the job of Influx to handle time related functionality, at least IMO.

**Comment by kylethebaker** [comment]
@pantlavanya, another limitation to this is that you would need to use tags for your `month` and `year` fields in order to do the grouping, and tags are strings only. So if you wanted to a month-to-date for some day in the month (say the 15th) for years passed 2015, you wouldn't be able to do something like `select sum("some_field") where day_of_month < 15 and year > 2015 group by month, year` because of the string vs int comparison.

**Comment by timhallinflux** [comment]
https://github.com/influxdata/flux/blob/master/docs/SPEC.md#duration-literals

**Comment by RedShift1** [comment]
I've written some seriously hacky code on NodeJS to have aggregation windows of months and years, [you can find it here](https://github.com/RedShift1/influx-fixes). Would not recommend you run this in production, it's terrible.

**Comment by mfernand0** [comment]
+1
GROUP BY time(1M)
GROUP BY time(1Y)
GROUP BY time(1q) "quarterly"

order by priority

**Comment by eelyaj** [comment]
+1
GROUP BY time(1M)
GROUP BY time(1Y)
GROUP BY time(1q) "quarterly"

**Comment by cmolitor** [comment]
+1
GROUP BY time(1M)
GROUP BY time(1Y)

**Comment by eraelpeha** [comment]
> It was supposed to be included in the new flux language?
> Anyone can confirm that flux 0.12 that is included with influx_db 1.7.x has that capability ?
> I need to compare month by month 2016-2018 solar production but that can't be done easily with current query language.

Tried it two days ago, and it worked for me.

**Comment by xsherlockpl** [comment]
Can you share a flux query that does that?

**Comment by eraelpeha** [comment]
> Can you share a flux query that does that?
> […](#)
> On April 28, 2019 00:25:34 eraelpeha ***@***.***> wrote: It was supposed to be included in the new flux language? Anyone can confirm that flux 0.12 that is included with influx_db 1.7.x has that capability ? I need to compare month by month 2016-2018 solar production but that can't be done easily with current query language.Tried it two days ago, and it worked for me. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Of course. For example, I have a counter value and this gives me the total amount of bytes received by month in a grafana table:

```
from(bucket: "sensordata/autogen")
|> filter(fn: (r) => r._measurement == "monitoring" and r.device == "fb01" and r.network == "TotalBytesReceived" and r._field == "bytes")
|> range($range)
|> window(every: 1mo)
|> increase()
```

**Comment by RedShift1** [comment]
We can't replace every influxql query with flux, it appears to be more than 10 times slower:

`# time influx -database db -execute $'SELECT max("OIL_PRESSURE") FROM "db"."autogen"."main_plc" WHERE time > now()-7d AND "deviceId"=\'xx\' GROUP BY time(1d) FILL(null)'`
*output omitted*

real    **0m2.097s**
user    0m1.591s
sys     0m0.093s
```
# time influx -database db -type 'flux' -execute 'from(bucket: "db")
>   |> range(start: -7d)
>   |> filter(fn: (r) => r._measurement == "main_plc" and r._field == "OIL_PRESSURE" and r.deviceId == "xx")
>   |> window(every: 1d)
>   |> max()'
```
*output omitted*

real    **0m27.127s**
user    0m1.587s
sys     0m0.084s

**Comment by xsherlockpl** [comment]
Holy shit, that's slow.... how granular is your oil_pressure data? What 
hardware?
  My infuxdb holds now 3y of solar power power generation @ 1Hz  and 
still grafana will pull the year graph within 5s for 2 solar generators. 
But at 10x that would put a lot of stress on my VM.

**Comment by RedShift1** [comment]
> Holy shit, that's slow.... how granular is your oil_pressure data? What hardware?  My infuxdb holds now 3y of solar power power generation @ 1Hz  and still grafana will pull the year graph within 5s for 2 solar generators. But at 10x that would put a lot of stress on my VM.

Hardware: 2 x Intel Xeon E5-2643v2 (6C/12T, 3.5 GHz), 128 GB RAM, data stored on Intel D3-S4510 SSD's in RAID 10
Database size: 84 GB
Granularity is 10 Hz (one datapoint every 100 ms).

**Comment by timhallinflux** [comment]
We haven't been focused on performance at this time.  We are focused driving towards feature complete at the moment.  Performance work is planned to begin soon.

**Comment by cmolitor** [comment]
I am trying the new possibility to "group by month" with flux.

I have values of a cumulated energy meter for every day and want to get the monthly energy consumption. Thus I would like to take the value at the end of the month and subtract the value of the beginning of the month.

I managed to setup the following script but face still a problem:
```
from(bucket: "smartfarm/autogen")
  |> range(start: -1y)
  |> filter(fn: (r) => r._measurement == "E_real_con") 
  |> window(every: 1mo, period: 1mo)
  |> last()
  |> group()
  |> difference()
```
The resulting data is not grouped by calendaric month but different time intervals which you see in the screenshot (I could not copy the data from chronograf).
<img width="1125" alt="Bildschirmfoto 2019-04-30 um 15 07 08" src="https://user-images.githubusercontent.com/8420080/56963631-ad951200-6b59-11e9-9c89-254147581927.png">

Is it possible to group by calendaric month (e.g. 2019-01-01 to 2019-01-31)?

Thanks!

**Comment by mfernand0** [comment]
same here, does the new version allow to group by month? (calendar)

**Comment by timhallinflux** [comment]
No.  This hasn't been implemented yet.  It is on our backlog...and the plan is to include this with Flux (as we've stated in this thread).  We absolutely understand the value and importance of getting this done.

**Comment by mfernand0** [comment]
Thanks @timhallinflux 

Is there any workaround to this issue? or do we know when is going to be implemented (aprox... a year, 6 months ) ?

**Comment by cmolitor** [comment]
Thanks @timhallinflux for the clarification.

Furthermore: 
Is the intervals feature already implemented. I always get an error message if I try the following:
```
from(bucket: "smartfarm/autogen")
  |> range(start: -1y)
  |> filter(fn: (r) => r._measurement == "E_real_con") 
  |> window(intervals: intervals(every: 1mo, period: 1mo))
  |> last()
  |> group()
  |> difference()
```

I get the following error message: 
<img width="741" alt="Bildschirmfoto 2019-04-30 um 21 05 10" src="https://user-images.githubusercontent.com/8420080/56986646-91aa6400-6b8b-11e9-8806-4074b306e8cc.png">

**Comment by timhallinflux** [comment]
Two things to look at:
https://docs.influxdata.com/flux/v0.24/functions/built-in/misc/intervals/
and 
https://docs.influxdata.com/flux/v0.24/functions/built-in/transformations/window/

I think you can simplify the `window()` function as:
`|> window(every: 1mo, period: 1mo)`

**Comment by RedShift1** [comment]
> I am trying the new possibility to "group by month" with flux.
> 
> I have values of a cumulated energy meter for every day and want to get the monthly energy consumption. Thus I would like to take the value at the end of the month and subtract the value of the beginning of the month.
> 
> I managed to setup the following script but face still a problem:
> 
> ```
> from(bucket: "smartfarm/autogen")
>   |> range(start: -1y)
>   |> filter(fn: (r) => r._measurement == "E_real_con") 
>   |> window(every: 1mo, period: 1mo)
>   |> last()
>   |> group()
>   |> difference()
> ```
> 
> The resulting data is not grouped by calendaric month but different time intervals which you see in the screenshot (I could not copy the data from chronograf).
> <img alt="Bildschirmfoto 2019-04-30 um 15 07 08" width="1125" src="https://user-images.githubusercontent.com/8420080/56963631-ad951200-6b59-11e9-9c89-254147581927.png">
> 
> Is it possible to group by calendaric month (e.g. 2019-01-01 to 2019-01-31)?
> 
> Thanks!

What if you floor the start time down to the beginning of the first month instead of specifying a relative time description?

**Comment by Pruxis** [comment]
Any updates on this? It's been like four years since the initial request.

**Comment by RedShift1** [comment]
@Pruxis don't count on it being fixed in a reasonable amount of time... You'll have to use the influx-fixes I posted earlier or decompose the aggregation by months into days, query influx, and then recompose the data into months.

**Comment by konstantinblaesi** [comment]
@RedShift1 What about the changes in @Anaisdg's PR ? Will those allow to group by month and aggregate using e.g. sum ?

**Comment by Anaisdg** [comment]
@konstantinblaesi That's the idea.

**Comment by gaardiolor** [comment]
> We can't replace every influxql query with flux, it appears to be more than 10 times slower:

I'm seeing something similar.. flux is 6 times slower doing a sum of 150k records, unworkable. 6x more hardware to finally get `group by time (1mo)` and `group by time (1y)` in a _time_ series database (in which the `group by time(1w)` week starts on Thursday 😕).. 

Tried tagging months myself in the data, I think similar to the workaround of @Anaisdg . But then in Grafana I have to use X-Axis mode Series and stacking no longer works (https://github.com/grafana/grafana/issues/7949), so that doesn't work for me.

**Comment by antipooh** [comment]
+1

**Comment by s4ndst0rm** [comment]
> @konstantinblaesi That's the idea.
@Anaisdg How can i use your Plugin? Is it in 2.0 alpha?
Is it possible to update past measurements, so that all data has this tags?

**Comment by konstantinblaesi** [comment]
@s4ndst0rm https://github.com/influxdata/telegraf/commit/3e5cfad2b051b454c50e248e544791d1aecd6586 says it's in
* 1.12.2
* 1.12.1
* 1.12.0
* 1.12.0-rc1

right?

**Comment by mabnz** [comment]
+1
GROUP BY time(1M)
GROUP BY time(1Y)

**Comment by krtschmr** [comment]
:sad:

**Comment by s4ndst0rm** [comment]
@RedShift1 I tried flux too. When i window by month and aggregate with max function the results are little bit strange:

This is my query:
```
from(bucket: "openhab/autogen")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r._measurement == "Heizung_Total" and (r._field == "value"))
  |> aggregateWindow(every: 1mo, fn: max)
  |> group(columns: ["_time", "_start", "_stop", "_value"], mode: "except")
```
result:


```
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string |  
-- | --
#group,false,false,false,false,false,false,true,true |   |   |   |   |  
#default,_result,,,,,,, |   |   |   |   |   |   |  
,result,table,_start,_stop,_time,_value,_field,_measurement |   |   |   |  
,,0,2019-08-01T06:19:00Z,2019-10-26T06:36:41.0575593Z,2019-08-08T00:00:00Z,20402.2945,value,Heizung_Total
,,0,2019-08-01T06:19:00Z,2019-10-26T06:36:41.0575593Z,2019-09-05T00:00:00Z,20567.5373,value,Heizung_Total
,,0,2019-08-01T06:19:00Z,2019-10-26T06:36:41.0575593Z,2019-10-03T00:00:00Z,20851.7778,value,Heizung_Total
,,0,2019-08-01T06:19:00Z,2019-10-26T06:36:41.0575593Z,2019-10-26T06:36:41.0575593Z,21150.6156,value,Heizung_Total


```

But these are not the max values for the listed months. Why is the time field not at last day of month?

**Comment by nathanielc** [comment]
@s4ndst0rm The current implementation of Flux months is equivalent to 30d which is why its not behaving as expected. That said we are currently updating the implementation to use real calendar months. See https://github.com/influxdata/flux/pull/2067 to follow our progress.

**Comment by OFark** [comment]
With regard to the months and years not always being the same what I would expect would be to knock x off the year or month and take the first existing date BEFORE that.
so: 2019-03-30 - 1M = 2019-02-28
and similarly: 2020-02-29 - 1y = 2019-02-28

**Comment by krtschmr** [comment]
@OFark  do it as ruby does

```
 a = Date.parse("2019/03/30") - 1.month
=> Thu, 28 Feb 2019



Date.parse("2020/02/29") - 1.year
=> Thu, 28 Feb 2019

```

**Comment by nikoladsp** [comment]
+1
GROUP BY time(1Y)
GROUP BY time(1M)
GROUP BY time(1q) "quarterly"

Thanks!

**Comment by agolovenko** [comment]
5 years ago this was opened...

**Comment by timhallinflux** [comment]
This is available in Flux now.

**Comment by s4ndst0rm** [comment]
> @s4ndst0rm The current implementation of Flux months is equivalent to 30d which is why its not behaving as expected. That said we are currently updating the implementation to use real calendar months. See [influxdata/flux#2067](https://github.com/influxdata/flux/pull/2067) to follow our progress.

Hey @nathanielc 

I saw that you merged your code to master last year. 
I've updated to InfluxDB 1.7.10 but the results are the same. Is your change not available in this version?

**Comment by konstantinblaesi** [comment]
@s4ndst0rm I assume this is only in influxdb 2.x

**Comment by timhallinflux** [comment]
Yes, it's available in InfluxDB 2.0 OSS Beta and InfluxDB Cloud.
This will ALSO be in the 1.8 InfluxDB release.  Testing is wrapping up now.  Expect an update next week.

**Comment by tparvais** [comment]
+1, hope it will be delivered soon with 1.8
GROUP BY time(1Y)
GROUP BY time(1M)

**Comment by kwu83tw** [comment]
+1, same thing here to see it be delivered in v1.8

**Comment by sanderson** [comment]
To clarify, year and month duration units are supported in the version of Flux that will ship with 1.8. They will not be available in InfluxQL.

**Comment by timhallinflux** [comment]
InfluxDB 1.8 is available now.  You must use Flux to leverage this capability.
https://docs.influxdata.com/flux/v0.65/guides/windowing-aggregating/#windowing-data

**Comment by RedShift1** [comment]
What about performance? Is it the same as CQL?

**Comment by mabnz** [comment]
> To clarify, year and month duration units are supported in the version of Flux that will ship with 1.8. They will not be available in InfluxQL.

Will aggregateWindow support 'offset'?

**Comment by polcape** [comment]
Hi, I try with aggregate function but what id the duration for month? 1M? Seems not work...

**Comment by sanderson** [comment]
`1mo` is for month. `1m` is for minute.

**Comment by gaardiolor** [comment]
@RedShift1 
> What about performance? Is it the same as CQL?

192176 total records, both queries have the same output, piped to /dev/null to suppress.

```
time ./influx.sh 'SELECT sum("TEST") FROM "test" WHERE time >= 1512345600000000000 GROUP BY time(4w,4d)' > /dev/null

real    0m0.132s
user    0m0.009s
sys     0m0.004s

time ./flux.sh 'from(bucket: "test") |> range(start: 2017-12-03T00:00:00.000000001Z) |> filter(fn: (r) => r._measurement == "test" and r._field == "TEST") |> group() |> window(every: 4w, period: 4w) |> sum()' > /dev/null
real    0m7.149s
user    0m5.763s
sys     0m0.080s
```

Really hammering the CPU. So, I only need **54x** more hardware to do the same thing in flux. Hooray.

**Comment by castillo92** [comment]
+1
GROUP BY time(1M)
GROUP BY time(1Y)


In this moment Flux is not the solution. If we have to change everything to have 1M we should move our data to another database

**Comment by hiei17** [comment]
+1

**Comment by vbenhur** [comment]
+1

**Comment by nanhao1986** [comment]
+1

**Comment by aolaria** [comment]
+1

**Comment by adiantek** [comment]
+1

**Comment by tonioa** [comment]
+1

**Comment by FohlenAFK** [comment]
+1

**Comment by miky-boy** [comment]
+1

**Comment by nanicpc** [comment]
this shoudn't have being close since is not available in influxql

**Comment by timhallinflux** [comment]
We don't plan to offer this functionality in InfluxQL.  The functionality is available in Flux and performance optimizations will be introduced shortly to address the concerns raised above.

**Comment by castillo92** [comment]
> We don't plan to offer this functionality in InfluxQL. The functionality is available in Flux and performance optimizations will be introduced shortly to address the concerns raised above.

Flux is InfluxDB? We will be able to query data grouping by time "month" or "year" ?

**Comment by timhallinflux** [comment]
We introduced Flux in InfluxDB 1.8.  It exists side-by-side with InfluxQL.
https://docs.influxdata.com/influxdb/v1.8/flux/installation/

Yes, if you fundamentally need these capability today, it is there to take advantage of.  In many cases, using 30d as a mechanism is good enough, but there are use cases where the strict month and year boundaries are desired.  

https://docs.influxdata.com/influxdb/v1.8/flux/guides/window-aggregate/#windowing-data

**Comment by castillo92** [comment]
> We introduced Flux in InfluxDB 1.8. It exists side-by-side with InfluxQL.
> https://docs.influxdata.com/influxdb/v1.8/flux/installation/
> 
> Yes, if you fundamentally need these capability today, it is there to take advantage of. In many cases, using 30d as a mechanism is good enough, but there are use cases where the strict month and year boundaries are desired.
> 
> https://docs.influxdata.com/influxdb/v1.8/flux/guides/window-aggregate/#windowing-data

Great functionality!

So... Flux is a new way of querying data using it's new language?

**Comment by timhallinflux** [comment]
Yes.  Think of it as a domain specific language which provides the power you need to move beyond simple dashboarding.

As we release InfluxDB 2.0 OSS, planned for end of Oct/early Nov, we have both Flux and InfluxQL present as languages for accessing data. 1.x READ and WRITE compatibility APIs will be present (starting with the 1st release candidate -- coming soon) allowing for ease of upgrade from 1.x to 2.x.   

Flux can be used to build interactive queries such as dashboard cells AND it also powers a task system.  You can write Flux-based tasks which execute on a schedule.  We'll also look to introduce "triggers" for task execution in subsequent releases.

If you want to learn more about Flux, I'd highly suggest diving into some primers like: https://www.influxdata.com/resources/introduction-to-flux-and-functional-data-scripting/

**Comment by dcolley** [comment]
I find it really frustrating that month is not supported in influxQL.

I guess technically, grouping by month could mean anything. Where to start is not obvious (e.g. if your 1st month is incomplete), however simple assumptions could make the implementation straightforward. e.g. simply lop off the day part and group by year/month parts.

At the time the OP requested this, flux was not an option. Implementing it in flux and not influxQL seems contrived. 

Do you need more time? Are you deprecating influxQL?

**Comment by kptkip** [comment]
I am using Grafana to read data from influxDB.

I am wondering, how to use the feature with grouping by month.

**Comment by pportelaf** [comment]
> We don't plan to offer this functionality in InfluxQL. The functionality is available in Flux and performance optimizations will be introduced shortly to address the concerns raised above.

But no timezone feature :(

**Comment by sauvant** [comment]
...and now Flux, the long awaited solution for the ever wanted calendar grouping feature, gets deprecated. Hard to believe. So please reopen this issue, we need the functionality in InfluxQL as it seems. 

See my comment in the influx forum:

https://community.influxdata.com/t/i-am-lost-which-query-language-to-use/32866

**Comment by RedShift1** [comment]
> ...and now Flux, the long awaited solution for the ever wanted calendar grouping feature, gets deprecated. Hard to believe. So please reopen this issue, we need the functionality in InfluxQL as it seems.
> 
> See my comment in the influx forum:
> 
> https://community.influxdata.com/t/i-am-lost-which-query-language-to-use/32866

Don't count on this getting fixed. Instead, put your summaries in a different database like MySQL or PostgreSQL. Yes it's annoying having to use two different databases but we are limited by the technology of our time.

**Comment by castillo92** [comment]
For me Influx started like a rocket.... but pass 2 or 3 years and see the same problems...

**Comment by cesaroni** [comment]
how to calculate how long is a month:

`
isLeapYear = (currentYear) => {
  leapYear = if  currentYear % 4 == 0 and ( currentYear % 100 != 0 or currentYear % 400 == 0)  then 
    true
  else 
    false

  return leapYear
}

daysOfMonth = (currentYear,currentMonth) => {
  days = if  contains(value: currentMonth, set: [4,6,9,11]) then 30 
  else if currentMonth == 2 and isLeapYear(currentYear) == true then 29
  else if currentMonth == 2 and isLeapYear(currentYear) == false then 28
  else 31

  return days
}


daysOfMonth(currentYear: 2024, currentMonth: 2)  // 29

`

**Comment by Endocipher7** [comment]
Does the model apply for suspension of durability in terms of contraction in cycling practice in 1000 year loops?

**Comment by krtschmr** [comment]
@cesaroni 

```
isLeapYear = (currentYear) => {
  return currentYear % 4 == 0 && ( currentYear % 100 != 0 || currentYear % 400 == 0) 
}
```

had to fix it :P

**Comment by cesaroni** [comment]
@krtschmr 

flux operators...

```
isLeapYear = (currentYear) => {
  return currentYear % 4 == 0 and ( currentYear % 100 != 0 or currentYear % 400 == 0)
}
```

**Comment by krtschmr** [comment]
Haaa, terrible. you're right :P
