### ISSUE TITLE
[0.9.3] NaN value breaks json response

### ISSUE THREAD

**Issue by everflux** [influxdata/influxdb#3994]
I use the tail plugin that produces NaN when a value is not present. When querying influxdb I get the result as response payload (along with http 200)

```
json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: NaN
```

**Comment by beckettsean** [comment]
@everflux what version of InfluxDB are you using? I'm unfamiliar with the tail plugin, can you link to it?

**Comment by everflux** [comment]
Version: 0.9.3
The description was inaccurate, sorry: Actually I am using collectd with the tail plugin producing the data which is giving the problem with influxdb.
Collectd is shipping the data to influx using the udp collectd endpoint
Plugin: https://collectd.org/wiki/index.php/Plugin:Tail

**Comment by beckettsean** [comment]
Thanks, @everflux 

@otoolep thoughts?

**Comment by otoolep** [comment]
Hmmmm. Looks like some values we can't marshall can get into the database via collectd.

We could try to catch this in the software and suppress the value.

**Comment by kalidasya** [comment]
see comments in  https://github.com/influxdb/influxdb/issues/3539 
probably caused by: https://github.com/golang/go/issues/3480

**Comment by nonsenz** [comment]
running into this with influx 0.9.4.1 and collectd's ping plugin on a machine where local ping has interface issues and does not collect any data.

**Comment by namgk** [comment]
I am issuing a very simple select query and get this error too. The same select query works on other measurements, but for some, it failed miserably. 

>curl -G 'https://localhost:8086/query?pretty=true' --data-urlencod "db=<db_name>" --data-urlencode "q=SELECT * FROM lt WHERE time > now() - 1h" -k -u <user:pass>
>json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: NaN

**Comment by gilgamezh** [comment]
Same issue here:
influxdb 9.4.1 - debian jessy
```
json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: NaN 
```

Any Idea on how to delete the NaN values?

**Comment by beckettsean** [comment]
I don't know of any way to delete just the NaNs unless you know something else about the points. The value is unqueryable, so we can't build a query to remove them that relies on finding NaN.

It's a tough bug, because the database assumes these values cannot exist, but some of the plugins were able to create them.

**Comment by hughescr** [comment]
The database has no problem at all inserting NaNs.  I've run into this now too:

```
station,mode=test TEMP=NaN,HUM=NaN,BARO=NaN,WDIR=NaN,WSPD=NaN,WSHI=NaN,RF_DAY=NaN,BATT=NaN,CHILL=NaN 1444633200000
station,mode=test TEMP=74,HUM=32,BARO=29.36,WDIR=180,WSPD=0,WSHI=0,RF_DAY=0,BATT=6.51,CHILL=74 1441500660000
```
Sensor returned no data for a data point, and my client software inserted NaNs; now any query covering the time period of that point either errors out, or frequently will just hang the server at 100% CPU.

**Comment by kalidasya** [comment]
@beckettsean would not be the solution to implement a custom json.Marshaler for floats and convert the NaNs to 0/null? https://github.com/golang/go/issues/3480#issuecomment-66066041 so NaN can exist in the database and it is returnable.

**Comment by hughescr** [comment]
@kalidasya I wouldn't convert to 0, since that's irreversible -- you want to be able to distinguish NaN from 0 which is not the same thing.  null isn't that great if you also want to deal with +/-Infinity, which would be nice to add if you're special-casing NaN anyway.

**Comment by kalidasya** [comment]
@hughescr yes, you are right, I would not convert it to 0, but NaN --> null seems ok to me. +/- Inf, I would leave it for now, as I probably will not appear in reporting.

**Comment by hughescr** [comment]
@kalidasya Not sure I agree about +/- Inf; those would be useful values for "above sensor range" and "below sensor range" data points.

**Comment by rajeshmurali** [comment]
Please adjust your query to fetch only values for those timestamps where a value exists.
For eg:
station,mode=test TEMP=NaN,HUM=NaN,BARO=NaN,WDIR=NaN,WSPD=NaN,WSHI=NaN,RF_DAY=NaN,BATT=NaN,CHILL=NaN 1444633200000
station,mode=test TEMP=74,HUM=32,BARO=29.36,WDIR=180,WSPD=0,WSHI=0,RF_DAY=0,BATT=6.51,CHILL=74 1441500660000
Adjust your query such that value of TEMP is >= 0,HUM>=0,BAR>=0,WDIR>=0,WSPD>=0,WSHI>=0,RF_DAY>=0,BATT>=0,CHILL>=0
Line protocol query cannot understand what is NaN but it can understand the field with values

**Comment by hughescr** [comment]
@rajeshmurali what about timestamps that have some values, but not all values?  eg BARO is NaN but TEMP is a number, etc?  Also, NaN is not >= 0, at least in IEEE that comparison is un-ordered, ie the expression (NaN >= x) is undefined, and could have any value; it is generally a bad idea to compare NaN to anything; pretty much the only thing reliable to do with them is assess the result of isNaN(x).

**Comment by rajeshmurali** [comment]
select * from measurement where TEMP>=0 works
It returns those valid values other than NAN from TEMP column

**Comment by rajeshmurali** [comment]
@hughescr Queries which are based only on field values as filters will have to compare with all other values to match with the conditions in the query, so it will take more time. In addition field values are not indexed but tags are indexed so if someone is looking for a performance oriented query it is better to make use of tags. Further it is better to look into your schema and redesign it for better usage.
 The first value corresponding to a field in the measurement defines the field type for the rest of the field values in the measurement series. 
To query for values which have large float values in exponent please make use of the function power.
Example: 
select Temp from measurement where Temp=-1.7976931348623157*Power(10,308) 
works fine for me.

**Comment by Falc** [comment]
Any news on this issue?

**Comment by beckettsean** [comment]
@Falc the database will not accept `NaN` as a numeric value. If you have a system where `NaN` snuck in via one of the plugins before the loophole was closed, you need to explicitly overwrite that point with a different value or even a different field set.

There is an open feature request for `NaN` support: https://github.com/influxdata/influxdb/issues/4089

**Comment by Falc** [comment]
Thank you for the info @beckettsean. My scenario is a collectd instance sending NaN values, so I will try to catch and ignore/transform those NaN values before sending them to InfluxDB.

**Comment by rajeshmurali** [comment]
Hi All,
I was looking for a work around till we get support from InfluxDB on NaN and +-Inf. I am attaching the result which i got. I ignored those NaN field values and field keys.InfluxDB line protocol insisted that atleast one field with a valid value must be present.
![testoutput](https://cloud.githubusercontent.com/assets/14906667/13004718/6cf2723e-d17d-11e5-9766-2892b24105f5.JPG)

**Comment by jsternberg** [comment]
Is this still an issue? The new TSM engine doesn't take NaN values to my knowledge so I think this can't be done anymore.

**Comment by beckettsean** [comment]
@jsternberg the old system wouldn't accept `NaN` via the API, but the collectd endpoint did let some sneak through. Are you certain that TSM would refuse to even store the value? I think it's good to have some error handling in the query engine just in case a non-digit number value somehow sneaks through.

**Comment by jsternberg** [comment]
I haven't heard of this as still an issue. TSM cannot accept a `NaN` value according to @jwilder. If anybody runs into this issue with the latest version of InfluxDB, please open a new issue so we can fix it. Thanks.
