### ISSUE TITLE
TestServer_Query_DropAndRecreateSeries in racy

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#3998]
--- FAIL: TestServer_Query_DropAndRecreateSeries (0.82s)
panic: open meta store: initialize raft: set raft peers: node is the leader [recovered]
	panic: open meta store: initialize raft: set raft peers: node is the leader

goroutine 42 [running]:
testing.tRunner.func1(0xc820083560)
	/tmp/workdir/go/src/testing/testing.go:450 +0x1f5
github.com/influxdb/influxdb/cmd/influxd/run_test.OpenServer(0xc82013b080, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:49 +0xda
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_Query_DropAndRecreateSeries(0xc820083560)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:246 +0x7e
testing.tRunner(0xc820083560, 0x132a630)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 1 [chan receive]:
testing.RunTests(0xfec6f0, 0x132a5a0, 0x37, 0x37, 0x1355701)
	/tmp/workdir/go/src/testing/testing.go:582 +0x64b
testing.(*M).Run(0xc820425f00, 0xfecc60)
	/tmp/workdir/go/src/testing/testing.go:494 +0xe5
main.main()
	github.com/influxdb/influxdb/cmd/influxd/run/_test/_testmain.go:164 +0x210

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 18 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x26
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x45

goroutine 36 [chan receive]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc82038a1e0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:347 +0x1177
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc82038a1e0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:372 +0x3f
github.com/influxdb/influxdb/cmd/influxd/run_test.OpenServer(0xc82013adc0, 0x0, 0x0, 0x10)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:48 +0x65
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_DatabaseCommands(0xc8200833b0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:29 +0x6e
testing.tRunner(0xc8200833b0, 0x132a5e8)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 43 [chan receive]:
testing.RunTests.func1(0xc8201082a0, 0xc820083560)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 68 [chan receive]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc82038aa50, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:347 +0x1177
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc82038aa50, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:372 +0x3f
github.com/influxdb/influxdb/cmd/influxd/run_test.OpenServer(0xc820534840, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:48 +0x65
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_Write_LineProtocol_Float(0xc820083830)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:564 +0x7e
testing.tRunner(0xc820083830, 0x132a6a8)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 47 [chan receive]:
testing.RunTests.func1(0xc8201082a0, 0xc820083680)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 52 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820100170, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x94
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc82019f5f0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:2054 +0x74
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc820115650)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/net_transport.go:346 +0xa0
created by github.com/hashicorp/raft.NewNetworkTransport
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/net_transport.go:138 +0x3e6

goroutine 45 [chan receive]:
testing.RunTests.func1(0xc8201082a0, 0xc8200835f0)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 46 [chan receive]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc82038a780, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:347 +0x1177
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc82038a780, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:372 +0x3f
github.com/influxdb/influxdb/cmd/influxd/run_test.OpenServer(0xc820534000, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:48 +0x65
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_DatabaseRetentionPolicyAutoCreate(0xc820083680)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:411 +0x6e
testing.tRunner(0xc820083680, 0x132a660)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 66 [chan receive]:
github.com/hashicorp/raft.(*deferError).Error(0xc8205b50e0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/future.go:56 +0x134
github.com/hashicorp/raft.(*logFuture).Error(0xc8205b50e0, 0x0, 0x0)
	<autogenerated>:14 +0x58
github.com/influxdb/influxdb/meta.(*localRaft).apply(0xc820467cc0, 0xc82084e920, 0xa, 0x10, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/state.go:251 +0xbb
github.com/influxdb/influxdb/meta.(*Store).apply(0xc820118c80, 0xc82084e920, 0xa, 0x10, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:1501 +0x8c
github.com/influxdb/influxdb/meta.(*Store).exec(0xc820118c80, 0xc800000003, 0x1327c20, 0xdbab40, 0xc8204cfde0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:1494 +0x43f
github.com/influxdb/influxdb/meta.(*Store).CreateDatabase(0xc820118c80, 0xe58858, 0x3, 0xe5c060, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:858 +0x16f
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Server).CreateDatabaseAndRetentionPolicy(0xc8203f1840, 0xe58858, 0x3, 0xc8208277c0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:90 +0x84
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_Write_JSON(0xc8200837a0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:542 +0x1da
testing.tRunner(0xc8200837a0, 0x132a690)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 54 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc8201ae380)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/raft.go:502 +0x16d8
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/raft.go:246 +0x2e
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8201ae380, 0xc8201452d0)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/state.go:152 +0x52
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/state.go:153 +0x5b

goroutine 67 [chan receive]:
testing.RunTests.func1(0xc8201082a0, 0xc8200837a0)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 44 [chan receive]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc82038a3c0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:347 +0x1177
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc82038a3c0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:372 +0x3f
github.com/influxdb/influxdb/cmd/influxd/run_test.OpenServer(0xc82013b340, 0x0, 0x0, 0x8)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:48 +0x65
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_RetentionPolicyCommands(0xc8200835f0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:337 +0xa0
testing.tRunner(0xc8200835f0, 0x132a648)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 37 [chan receive]:
testing.RunTests.func1(0xc8201082a0, 0xc8200833b0)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 49 [chan receive]:
testing.RunTests.func1(0xc8201082a0, 0xc820083710)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 48 [chan receive]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc82038a5a0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:347 +0x1177
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc82038a5a0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:372 +0x3f
github.com/influxdb/influxdb/cmd/influxd/run_test.OpenServer(0xc82013b8c0, 0x0, 0x0, 0xc800000076)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:48 +0x65
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_UserCommands(0xc820083710)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:445 +0x8e
testing.tRunner(0xc820083710, 0x132a678)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 53 [runnable]:
runtime.Gosched()
	/tmp/workdir/go/src/runtime/proc.go:166 +0x14
time.NewTimer(0x436cc40, 0xc8200147e0)
	/tmp/workdir/go/src/time/sleep.go:74 +0x7a
time.After(0x436cc40, 0xc820331ec0)
	/tmp/workdir/go/src/time/sleep.go:110 +0x2f
github.com/hashicorp/raft.randomTimeout(0x2faf080, 0xc820331ec0)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/util.go:37 +0x6a
github.com/hashicorp/raft.(*Raft).runCandidate(0xc8201ae380)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/raft.go:658 +0x1b1
github.com/hashicorp/raft.(*Raft).run(0xc8201ae380)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/raft.go:593 +0xd2
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/raft.go:245 +0x2e
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8201ae380, 0xc8201452c0)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/state.go:152 +0x52
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/state.go:153 +0x5b

https://circle-artifacts.com/gh/influxdb/influxdb/5568/artifacts/2/tmp/circle-artifacts.ng7hj3X/test_logs_race.txt

**Comment by otoolep** [comment]
@benbjohnson @jwilder

**Comment by jwilder** [comment]
Havent seen this fail in a long while.  Closing.
