### ISSUE TITLE
[feature request] better error message when restoring a backup causes OOM

### ISSUE THREAD

**Issue by abhishekchoudhary** [influxdata/influxdb#4027]
I'm running InfluxDB 0.9.2 on two servers, independently. Both 64 bit 14.04 Ubuntu (Quad core, 15GB RAM). I took a backup from one and tried to restore to the other.

Restored the backup, changed ownership of dirs to influxdb, and tried to start the server.

Here's the weird behaviour in the terminal:
 - 'Failed to start' when I try to start the server
 - Says 'stopping the server' when I issue the command again, indicating that it was probably running after the first one
 
>ubuntu:~/ $ sudo /etc/init.d/influxdb restart                                                                                                                          [10:14:10]
>influxd process is not running [ OK ]
>Starting the process influxd [ OK ]
>influxd process failed to start [ FAILED ]
>ubuntu:~/ $ sudo /etc/init.d/influxdb restart                                                                                                                          [10:14:14]
>influxd process was stopped [ OK ]
>Starting the process influxd [ OK ]
>influxd process was started [ OK ]
>ubuntu:~/ $

Now, I try to go to the influxd shell,

`> show databases`
`ERR: Get http://localhost:8086/query?db=&q=show+databases: dial tcp 127.0.0.1:8086: connection refused`

This looks like the InfluxDB server is not running. If I run the start command now,

>ubuntu:influxdb/ $ sudo /etc/init.d/influxdb restart                                                                                                                    [5:07:35]
>influxd process is not running [ OK ]
>Starting the process influxd [ OK ]
>influxd process failed to start [ FAILED ]

This is the state of the last 50 lines of the log file during this process. No major indicators of a problem here:
>metastore] 2015/09/07 06:30:46 [INFO] raft: Disabling EnableSingleNode (bootstrap)
>[metastore] 2015/09/07 06:30:46 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 06:30:46 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 06:30:46 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 06:30:46 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 06:30:46 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 06:30:46 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:14:15 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
>[metastore] 2015/09/07 10:14:15 read local node id: 1
>[metastore] 2015/09/07 10:14:17 [WARN] raft: Heartbeat timeout reached, starting election
>[metastore] 2015/09/07 10:14:17 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
>[metastore] 2015/09/07 10:14:17 [DEBUG] raft: Votes needed: 1
>[metastore] 2015/09/07 10:14:17 [DEBUG] raft: Vote granted. Tally: 1
>[metastore] 2015/09/07 10:14:17 [INFO] raft: Election won. Tally: 1
>[metastore] 2015/09/07 10:14:17 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
>[metastore] 2015/09/07 10:14:19 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
>[metastore] 2015/09/07 10:14:19 read local node id: 1
>[metastore] 2015/09/07 10:14:20 [WARN] raft: Heartbeat timeout reached, starting election
>[metastore] 2015/09/07 10:14:20 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
>[metastore] 2015/09/07 10:14:20 [DEBUG] raft: Votes needed: 1
>[metastore] 2015/09/07 10:14:20 [DEBUG] raft: Vote granted. Tally: 1
>[metastore] 2015/09/07 10:14:20 [INFO] raft: Election won. Tally: 1
>[metastore] 2015/09/07 10:14:20 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
>[metastore] 2015/09/07 10:14:20 [INFO] raft: Disabling EnableSingleNode (bootstrap)
>[metastore] 2015/09/07 10:14:20 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:14:20 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:14:20 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:14:20 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:14:20 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:14:20 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:14:20 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:14:20 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:17:44 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
>[metastore] 2015/09/07 10:17:44 read local node id: 1
>[metastore] 2015/09/07 10:17:45 [WARN] raft: Heartbeat timeout reached, starting election
>[metastore] 2015/09/07 10:17:45 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Votes needed: 1
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Vote granted. Tally: 1
>[metastore] 2015/09/07 10:17:45 [INFO] raft: Election won. Tally: 1
>[metastore] 2015/09/07 10:17:45 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
>[metastore] 2015/09/07 10:17:45 [INFO] raft: Disabling EnableSingleNode (bootstrap)
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): >[127.0.0.1:8088]
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
>[metastore] 2015/09/07 10:17:45 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]

**Comment by beckettsean** [comment]
This is a known bug in 0.9.2 and is fixed in 0.9.3. If you are unable to upgrade, use `stop` and `start` rather than `restart`, and wait for the service to actually stop before issuing the `start` command.

**Comment by abhishekchoudhary** [comment]
I've tried using `stop` + `start` in place of `restart`. My primary problem is that the server crashes a minute after the start, and even when the process is running, I receive 'connection refused' on requests, meaning I cannot access the old database backup at all.

Is this a known issue too?

**Comment by beckettsean** [comment]
> My primary problem is that the server crashes a minute after the start

That doesn't sound like a known problem. To be clear, you're saying that the server to which you restored the backup crashes a minute or two after launch, every time? The log files in your initial comment are from that server?

> , and even when the process is running, I receive 'connection refused' on requests, meaning I cannot access the old database backup at all.

There is a period during startup when the HTTP service is not yet listening and writes and queries cannot be processed. It sounds as though the process is dying before the HTTP service starts up.

Failing on start has nothing to do with backups, as far as I know. Did you copy over any other data other than the backup? Can you try removing the `peers.json` file from the `/meta` directory?

**Comment by abhishekchoudhary** [comment]
Yes, the server on which I'm restoring the backup crashes on restart, every time. The log files are from that server.

That was my first instinct too, that the process is exiting before the HTTP service becomes available. So far, that looks like the case.

No other data was copied other than the db dump.

I've deleted the `peers.json` file, did not help.

**Comment by abhishekchoudhary** [comment]
So I think I've identified the problem. My server was running out of memory when it tried to run the influxdb process. It works fine on a more powerful machine.

I can't decide if I want to recommend a message in the Influx process logs.

**Comment by beckettsean** [comment]
Thanks for the follow up @abhishekchoudhary. I'll ask the team if there's a reasonable error message we can throw.

**Comment by beckettsean** [comment]
backup and restore has been fully reimplemented in 0.10+.

**Comment by Sahasrara** [comment]
I'm having a similar issue using 0.13.  After a restore, the server starts up, exhausts the 12gb of ram available, and then dies with no error.
