### ISSUE TITLE
[feature request] SHOW TAG VALUES should respect time boundaries

### ISSUE THREAD

**Issue by marouanehassani** [influxdata/influxdb#4029]
Following issue 3040
In influx db 0.9.2

First I insert some values

```
> insert foo,key1=val0 value=0
> insert foo,key1=val1 value=1
> insert foo,key1=val2 value=2
```

```
> select * from foo;
name: foo
tags: key1=val0
time                value
----                -----
2015-09-07T16:44:03.366Z    0


name: foo
tags: key1=val1
time            value
----            -----
2015-09-07T16:45:04.02Z     1


name: foo
tags: key1=val2
time                value
----                -----
2015-09-07T16:46:04.167Z    2
```

values are correctly inserted.

Now I try to get tag values filtered by time boundaries

```
> show tag values from foo with key=key1 where time<='2015-09-07T16:43:00.000Z'
name: key1TagValues
-------------------
key1
val0
val1
val2
```

-> it should return empty according to the where time clause

**Comment by beckettsean** [comment]
You can accomplish the same thing with `SELECT * FROM foo WHERE time <= '2015-09-07T16:43:00.000Z'` and then just throw away the fields in the result. The tag keys and values are indexed, but the time range in which they appear is not. Implementing it as a stand-alone query won't make it any more performant.

**Comment by Codelica** [comment]
Curious if this is still on the roadmap?  I realize you can select * and filter the results (when you have control), but for applications like Grafana this would be the ticket to more powerful template variables.  Or is there some alternate way to have show tag values exclude values that no longer have any associated data?  Thanks..

**Comment by timhallinflux** [comment]
Yes... this is still on our roadmap.  It is in our backlog.  The solution for this is really not straightforward -- in order to remain performant.
