### ISSUE TITLE
should not be able to use "true" or "false" as identifiers

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4037]
In order to parse booleans properly we need to be able to assume that the strings `true,True,TRUE,false,False,FALSE` are always booleans, never identifiers.

**Comment by corylanou** [comment]
Normally I would say they should be treated just like identifiers, but I can't think of a use case where you would want to name your measurement, field, tag, rp, or database `true` or `false` so +1 :-).

**Comment by apriendeau** [comment]
So I played around with this, I receive an error when I try all the variants of the boolean syntax and receive this `ERR: unable to parse 'hamlet true=b': invalid boolean`.  

@beckettsean do you have an example of where this succeeds?

**Comment by corylanou** [comment]
You have the syntax backwards.  Line protocol requires `field=value` syntax.

```
> create database ham
> use ham
Using database ham
> insert hamlet b=true
> select * from hamlet
name: hamlet
------------
time                            b
2015-09-24T22:50:05.980055963Z  true

> format json
> select * from hamlet
{"results":[{"series":[{"name":"hamlet","columns":["time","b"],"values":[["2015-09-24T22:50:05.980055963Z",true]]}]}]}
```

**Comment by apriendeau** [comment]
Okay. I could see that being useful as if you wanted to flag something as a friendly version to 0 or 1. 

Is there a reason that it can't be parsed as Boolean when its a value like that? It also looks like its coming back as a boolean as well from your example @corylanou. Still digging and learning a new codebase so I want to make sure that I understand completely.

**Comment by corylanou** [comment]
@beckettsean can you provide an example either via query or insert that this isn't the case?  Via the cli, I couldn't get it to recognize any of those as anything BUT booleans.  I'm not sure where the actual bug/feature request is without further context.

**Comment by beckettsean** [comment]
@corylanou @apriendeau I didn't test this or encounter any behavior, I just opened the issue after a long discussion about booleans. We decided that booleans shouldn't be valid identifiers, so as to simplify parsing. It appears that might already be done, but someone should check the code to be sure.

**Comment by apriendeau** [comment]
According to the code, if it parses as anything but an `IDENT`, it will error. 

https://github.com/influxdb/influxdb/blob/d02817ca6dbd9523902517e408435b2b954ee197/influxql/parser.go#L459

**Comment by jsternberg** [comment]
I'm not entirely sure what this issue is. `true` and `false` are parsed as boolean literals (I think), but they can also be used as an identifier if double quotes are used. Since double quoted values are always treated as identifiers, I think this is fine. I'm going to close this unless it causes some specific issue where we have to restrict the input.
