### ISSUE TITLE
parser should throw error on WHERE time clauses with "now" instead of "now()"

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4044]
I suppose it is possible that some day some person will want to compare a timestamp to a column named `now`, but in that case we can just require them to double-quote `now`. 

Meanwhile, I think any `WHERE time` clause that mentions `now` is most likely an oversight, and the user intended to have `now()` instead. As it is, the query returns just fine but the entire `WHERE time` clause is ignored.

**Comment by jsternberg** [comment]
This seems to work in 0.13.
