### ISSUE TITLE
Add aggregate function top

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#409]
A use case I've heard from multiple people is that they have a bunch of points and they want the top N values from the series. For instance, say we're tracking `cpu` load on many hosts. We feed in data like this:

``` json
[
  {
    "name" : "cpu",
    "columns" : ["host", "value"],
    "points": [
      ["serverA", 23.5]
    ]
  }
]
```

If we want to see the hosts with the highest CPU utilization we should be able to do a query like this:

``` sql
select top(10, value) from cpu where time > now() - 10m
```

We would then get the 10 highest values for the last 10 minutes. Or we could add more arguments to the call like this:

``` sql
select top(10, value, host) from cpu where time > now() - 10m
```

With that we'd get the 10 hosts with the highest values from the last 10 minutes. Note that with additional arguments they act like a distinct. For example, if serverA reported 10 times in the last 10 minutes with the highest values, we'd still only see serverA in the result set once.

Feedback appreciated. I think this will accomplish what people have been asking for with this type of query.

**Comment by oublackberry** [comment]
select top(10, value, host) from cpu where time > now() - 10m 
does not work. You can only do one value, not two.
