### ISSUE TITLE
Unable to connect to Influx CLI when using self-signed certificate

### ISSUE THREAD

**Issue by victorhooi** [influxdata/influxdb#4090]
This is related to this discussion:

https://groups.google.com/d/topic/influxdb/onlhVW9WJ-A/discussion

I have setup an InfluxDB server with a self-signed certificate.

I am able to insert data using influxdb-python, since my default verify_ssl is set to False (although it does print annoying warnings, which can't be suppressed (see https://github.com/influxdb/influxdb-python/issues/240).

However, if I try to use the Influx CLI to connect, I get the following error message:
```
victorhooi@thadeus ~/t/CS-22748> influx --ssl
Connected to https://localhost:8086 version
InfluxDB shell 0.9.4-HEAD
> show databases
ERR: Get https://localhost:8086/query?db=&q=show+databases: x509: certificate signed by unknown authority 
```
There does not seem to be any way to overrride this, or even connect at all.

**Comment by rkuchan** [comment]
@toddboom

**Comment by linroics** [comment]
+1

**Comment by brewneaux** [comment]
Hey all.

So, in shell version 0.12.1, they added a totally undocumented feature, 'unsafeSsl'.  It appears to work.

**Comment by AnthIste** [comment]
+1 is there an override for this?

**Comment by rossmcdonald** [comment]
This has been resolved with https://github.com/influxdata/influxdb/pull/5284, where you can now use the `-unsafeSsl` CLI flag.

**Comment by natemurthy** [comment]
I'm having a similar issue connecting to InfluxDB server (running `0.13.0`) when `https-enabled = true` in my config. I generated a self-signed certificate following these instructions: http://dst.lbl.gov/~boverhof/openssl_certs.html, and concatenated my server key and server cert into one PEM file. I could successfully connect using the CLI with `influx -ssl -unsafeSsl`, but when I used a cURL I would get this error:

```
$ curl -i --cacert client.pem -GET 'https://host:8086/query?pretty=true&db=mydb' --data-urlencode "q=SELECT * FROM measurement;"
curl: (58) unable to use client certificate (no key found or wrong pass phrase?)
```

I've tried `-k` to force a connection as well as all sorts of combinations of client keys and client certs passed into `curl` using the `--certs` and `--cacerts` option. When using a self-signed server key and cert, what exactly does InfluxDB server expect from the client making a HTTPS request?

**Comment by natemurthy** [comment]
Looks like I was just passing the wrong flags to curl, what I needed was:
```
$ curl -k --key client.key --cert client.pem 'https://host:8086/query?pretty=true&db=mydb' --data-urlencode "q=SELECT * FROM measurement;"
```
to force an unsafe SSL/TLS connection.

**Comment by ilario** [comment]
To skip the certification verification is a solution, but it is not a safe solution. An option for indicating the path of the .crt file would be nice. A prompt asking if the fingerprint is the correct one would be great.
