### ISSUE TITLE
Add something to the query language to limit the run time for a query

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#411]
Maybe something like this
```sql
select count(value) from some_series
maxRunTime(300)
```
Where the run time is the number of seconds that the query will be allowed to run. Each shard involved in the query can monitor this and stop the query if it goes over.

It would be good to have this as a cluster wide setting. So by default enforce this on all queries. And then they can override it by simply including `maxRunTime` in any query.

**Comment by jwilder** [comment]
Fixed via #6081
