### ISSUE TITLE
Queries that compare time against fields do not work

### ISSUE THREAD

**Issue by philip-wernersbach** [influxdata/influxdb#4113]
I have a series named `Foo` that contains a field `bar` that is a timestamp in milliseconds. This does not work:
`SELECT count(bar) FROM Foo WHERE time >= bar AND time < bar;`

By definition, this should return nothing, but in my test environment it returns all of the entries in `Foo`.

I also tried to convert the timestamp to nanoseconds like this:
`SELECT count(bar) FROM Foo WHERE time >= (bar * 1000000) AND time < (bar * 1000000);`

But it still returns everything.

**Comment by philip-wernersbach** [comment]
I'll add that the same comparison using literals works, and returns nothing as expected:

`SELECT count(bar) FROM Foo WHERE time >= 0 AND time < 0;`

**Comment by beckettsean** [comment]
@philip-wernersbach `time` is a special object in the system and in general not a valid operand for functions or mathematical operators. I've changed this into a feature request to allow for those comparisons.

**Comment by philip-wernersbach** [comment]
Okay, that's a shame. For more context: we're looking into switching from MySQL to InfluxDB at our business for our time series data going forward. About 50% of our use case involves comparing the time with non-static fields, so the inability to do this makes InfluxDB a non-starter for us, and I imagine this is pretty normal for business applications. We love everything else about the database though!

**Comment by dgnorton** [comment]
@philip-wernersbach in this use case, does it need to compare the current time `now()` with the value in a field?  Or, compare the timestamp `time` of each point with one of its field values?

**Comment by philip-wernersbach** [comment]
The latter, it needs to compare the timestamp `time` of each point with one of its field values.

**Comment by dgnorton** [comment]
@philip-wernersbach Can you give more details on the specific use case.  Maybe we can recommend an alternate schema to accomplish the same thing.

Comparing timestamps of each point to one of its fields would always be an unbounded query (time range unknown at query planning phase) and wouldn't perform well on large data sets.  It would have to look at every point from the beginning of time.

**Comment by philip-wernersbach** [comment]
We have a set of tasks, and these tasks are created on-the-fly and the number of tasks is unbounded. When each task completes, we put an entry into a series in InfluxDB, where the entry's timestamp is the task's completion time, and the task's due-by time is stored in the `due_by` field of the entry, in unix epoch format. We then want to separately query back the entries for the tasks that completed below their due-by time, and query back the entries for the tasks that completed above their due-by time, so that we can compare these two numbers for a certain time period.

**Comment by dgnorton** [comment]
You could add an ontime=true or ontime=false tag to each entry.  The actual
completion times can still be stored in a field if needed.

**Comment by philip-wernersbach** [comment]
Good idea, this will work fine as workaround for now. It creates a redundancy in the database (`time` will be redundant with `completion_time`), but that's okay for now.

**Comment by dgnorton** [comment]
If `completion_time` is always going to be the same as the timestamp of the point, then there's no need to store it in a separate field.  What I meant to say in my previous comment is that `due_by` time could still be stored in a field, but you should only do that if you need to calculate how early or late task completion time was.  However, that calculation would have to be performed in the client app because `time` can't be used in a calculation in the query language.
