### ISSUE TITLE
0.9.4 WAL death spiral

### ISSUE THREAD

**Issue by kev009** [influxdata/influxdb#4119]
Hi,

Trying to see if Influx can replace a TSDB cluster.  Right now, just one decently spec'd hw system and no clustering.

The wal starts growing, then RAM usage goes up until swapping and it's unusable.  ZFS and the disks are bored.  It looks like one 'shard' is being overused but I haven't looked into how WAL and boltdb work/dont't work together yet.

I'm wondering if we could perhaps skip things like compression and compaction on filesystems like ZFS?

```
root@influx-1:/data/influxdb/data/llnw-phx7-move/default # ls -lh /data/influxdb/data/llnw-phx7-move/default/16 
-rw-r--r--  1 influxd  influxd    12G Sep 15 18:19 /data/influxdb/data/llnw-phx7-move/default/16
```

```
[opentsdb] 2015/09/15 18:38:30 failed to write point batch to database "llnw-phx7-move": write failed: engine: write points: write throughput too high. backoff and retry
[write] 2015/09/15 18:38:30 write failed for shard 16 on node 1: engine: write points: write throughput too high. backoff and retry
[opentsdb] 2015/09/15 18:38:30 failed to write point batch to database "llnw-phx7-move": write failed: engine: write points: write throughput too high. backoff and retry
```

```
[data]
  dir = "{{ datadir }}"

  # The following WAL settings are for the b1 storage engine used in 0.9.2. They won't
  # apply to any new shards created after upgrading to a version > 0.9.3.
  max-wal-size = 104857600 # Maximum size the WAL can reach before a flush. Defaults to 100MB.
  wal-flush-interval = "10m" # Maximum time data can sit in WAL before a flush.
  wal-partition-flush-delay = "2s" # The delay time between each WAL partition being flushed.

  # These are the WAL settings for the storage engine >= 0.9.3
  wal-dir = "{{ waldir }}"
  wal-enable-logging = true

  # When a series in the WAL in-memory cache reaches this size in bytes it is marked as ready to
  # flush to the index
  # wal-ready-series-size = 25600

  # Flush and compact a partition once this ratio of series are over the ready size
  # wal-compaction-threshold = 0.6

  # Force a flush and compaction if any series in a partition gets above this size in bytes
  # wal-max-series-size = 2097152

  # Force a flush of all series and full compaction if there have been no writes in this
  # amount of time. This is useful for ensuring that shards that are cold for writes don't
  # keep a bunch of data cached in memory and in the WAL.
  # wal-flush-cold-interval = "10m"

  # Force a partition to flush its largest series if it reaches this approximate size in
  # bytes. Remember there are 5 partitions so you'll need at least 5x this amount of memory.
  # The more memory you have, the bigger this can be.
  # wal-partition-size-threshold = 20971520

[opentsdb]
  enabled = true
  # bind-address = ""
  database = "llnw-phx7-move"
  # retention-policy = ""
```
```

**Comment by kev009** [comment]
Looks very similar to https://github.com/influxdb/influxdb/issues/4096, except I can assert that I have gobs of I/O to spare.

**Comment by otoolep** [comment]
What are your input data rates? Check out 'SHOW STATS' for counts on your openTSDB input.

**Comment by kev009** [comment]
batches_tx |batches_tx_fail|connections_active|connections_handled|http_connections_handled |points_tx | tl_bad_float |tl_bad_line |tl_bytes_rx |tl_connections_active |tl_connections_handled | tl_points_rx |tl_read_err |
-----|------|------|-------|------|------|------|------|-----|-----|------|------|-----|
18312 | 119097 | 10823 | 200101 | 141 | 18312000 | 1136205 | 6 | 11149264986 | 10807 | 199944 | 138551149 | 6

**Comment by christianchristensen** [comment]
Adding some color: Looks to be stuck around 11k/s on `mean(connections_active|tl_connections_active)`; some spikes to 25k/s (which sustaining that would be more ideal...).

That's "visible" with `_internal` using `opentsdb`.

**Comment by kev009** [comment]
I can offer to arrange a time for you to login since this may be an interesting scale test system

**Comment by otoolep** [comment]
Thanks for the numbers.

I'll leave it to @pauldix since he made the latest changes to the WAL.

**Comment by kev009** [comment]
Just watching system during WAL recovery, something is amiss in this release.  It's using around 30GB RSS without any metrics coming in (the services are not even up yet) for 8GB in the data dir.

**Comment by xmj** [comment]
Working on the same cluster with @kev009 and @christianchristensen.

Today: Trying to tune the WAL settings (reducing them by an order of magnitude) so that disk writes occur earlier, the memory usage is up to 40G.

Likewise, the system is mostly idle -- and processing the ~70MB (!) WAL takes >15 minutes, even when there's a decent amount of memory to spare, the CPUs and disks are mostly idle.

How does one make WAL processing at startup faster at the expense of system resources?

**Comment by pauldix** [comment]
@xmj how are you getting into this state? How many points are you writing across how many series? Do you know what the total throughput is?

I'm shocked that the WAL is getting up to 70MB if you have the memory settings low. With the new code it should start failing writes and putting pressure on the clients well before it gets to that size.

Any extra info you can give would be helpful.

**Comment by pauldix** [comment]
@xmj also, what kind of hardware are you running on? Particularly the disks and their IOPS.

**Comment by xmj** [comment]
the CPUs are two Intel(R) Xeon(R) CPU E5620  @ 2.40GHz, 96MB RAM.

Disk space is provided by a 32 disk-array on ZFS as striped mirror (RAID10 if you will), with to SSDs for slog (ZIL) purposes.
Disk I/O is in the low single digits, and it looks like there's 370/630 r/w operations per seconds.

As for total throughput -- see @kev009's post from earlier. Given that InfluxDB just came up again the load isn't at full capacity yet.

**Comment by xmj** [comment]
@pauldix I've changed the memory settings before restarting, but even now WAL is growing. 27MB and counting.

That's with 
```
[data]
  dir = "/data/influxdb/data"

  # The following WAL settings are for the b1 storage engine used in 0.9.2. They won't
  # apply to any new shards created after upgrading to a version > 0.9.3.
  max-wal-size = 1048576 # Maximum size the WAL can reach before a flush. Defaults to 100MB.
  wal-flush-interval = "30s" # Maximum time data can sit in WAL before a flush.
  wal-partition-flush-delay = "2s" # The delay time between each WAL partition being flushed.

  # These are the WAL settings for the storage engine >= 0.9.3
  wal-dir = "/data/influxdb/wal"
  wal-enable-logging = true

  # When a series in the WAL in-memory cache reaches this size in bytes it is marked as ready to
  # flush to the index
  wal-ready-series-size = 4096

  # Flush and compact a partition once this ratio of series are over the ready size
  wal-compaction-threshold = 0.1

  # Force a flush and compaction if any series in a partition gets above this size in bytes
  wal-max-series-size = 1048576

  # Force a flush of all series and full compaction if there have been no writes in this
  # amount of time. This is useful for ensuring that shards that are cold for writes don't
  # keep a bunch of data cached in memory and in the WAL.
  wal-flush-cold-interval = "1m"

  # Force a partition to flush its largest series if it reaches this approximate size in
  # bytes. Remember there are 5 partitions so you'll need at least 5x this amount of memory.
  # The more memory you have, the bigger this can be.
  wal-partition-size-threshold = 1048576
```

**Comment by pauldix** [comment]
It's growing and still accepting writes? That doesn't seem right. Can you
verify the version by checking a response header?

**Comment by xmj** [comment]
I've patched the FreeBSD port to use 0.9.4 -- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=202981. 
If I'm not mistaken it should be at d81618c

**Comment by kev009** [comment]
@pauldix here is the block and heap output from pprof https://gist.github.com/kev009/cbe1323cbeb71c70926b

**Comment by christianchristensen** [comment]
Just for good measure: `X-Influxdb-Version: 0.9` and `SHOW DIAGNOSTICS` returns "0.9"

**Comment by toddboom** [comment]
Closing this out since it's for a version of InfluxDB that's no longer being actively maintained. Please feel free to open a new issue if you find an error with the current version.
