### ISSUE TITLE
return parse error for expressions with `<>` operator

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#4132]
It was reported in issue #4118 that operator `<>` does not cause a parse error.  The InfluxQL parser should return a parse error telling the user to use `!=` instead.

**Comment by jsternberg** [comment]
The `<>` operation should be seen the same as `!=` by the scanner and parser. I think we also started documenting its use lately.

I'm going to close this since I don't think we should remove this alias since people seem to be using it and it doesn't harm the parsing or scanning code to have it.
