### ISSUE TITLE
[0.9.4.1] Could not add 2nd data node in a cluster

### ISSUE THREAD

**Issue by pnpritchard** [influxdata/influxdb#4177]
I was able to add and run 3 raft nodes + 1 data node, however when I was trying to add the second data node (which is the 5th node in the cluster), the node could not start up and had the following error in the log :

```
2015/09/17 22:31:48 InfluxDB starting, version 0.9.4.1, branch 0.9.4, commit c4f85f84765e27bfb5e58630d0dea38adeacf543
2015/09/17 22:31:48 Go version go1.5, GOMAXPROCS set to 1
2015/09/17 22:31:48 Using configuration at: /config/config.toml
[retention] 2015/09/17 22:31:48 retention policy enforcement terminating
[monitor] 2015/09/17 22:31:48 shutting down monitor system
run: open server: open meta store: too many peers; influxdb v0.9.0 is limited to 3 nodes in a cluster
```

Original discussion: https://groups.google.com/forum/#!topic/influxdb/LWWrdJRt3kc
cc: @imlk

**Comment by otoolep** [comment]
CC @jwilder @corylanou 

@jwilder - should adding a 2nd data-only node work?

**Comment by jwilder** [comment]
Yes

**Comment by jsternberg** [comment]
Closing this since clustering is no longer supported in the open source version.
