### ISSUE TITLE
[0.9.4.1] Optimize LIMIT

### ISSUE THREAD

**Issue by jeremyVignelles** [influxdata/influxdb#4192]
Hi,
As the points stored in the database increase, the query
```SELECT * FROM measurement LIMIT 1```
is getting longer and longer. Is it possible to optimize this, since we told the interpreter that we are interested in only one point.

The idea behind this is to make queries like
```SELECT * FROM measurement GROUP BY tag ORDER BY time DESC LIMIT 1```
to get the last value for each tag.

**Comment by otoolep** [comment]
cc @DanielMorsing @dgnorton

**Comment by jeremyVignelles** [comment]
Hi,
Any update on this?

**Comment by otoolep** [comment]
The query engine is currently being refactored to improve performance in many areas. This may or may not impact `LIMIT`. Either way, what you experiencing does need improvement and we hope to get to it soon.

**Comment by beckettsean** [comment]
@benbjohnson is this something you are also looking into as part of the query engine refactoring? It does appear that `SELECT * FROM foo` and `SELECT * FROM foo LIMIT 1` are equivalently expensive queries, which doesn't make sense. It seems that each node should only return one point for this query, and the `ORDER BY` clause would determine if it should be the first or last point in the time range. 

@toddboom

**Comment by benbjohnson** [comment]
@beckettsean Yes, the refactoring will pull out a small number of points when a LIMIT is attached. I'm not sure if the current engine can preempt a query which would explain the growing execution time.
