### ISSUE TITLE
[0.9.5-nightly] query of CQ data hangs CLI

### ISSUE THREAD

**Issue by brunohass** [influxdata/influxdb#4203]
First, I did not know how to name this ticket correctly, feel free to rename it.

There is something strange going on in our influxdb. We have some CQs to downsample our data.

The model follows:
raw < 5m < 1h < 12h < 1d < 1w < 4w

Everything works fine until 12h measurement. After that I cannot even see data in the "next" measurement (1d).

I suspected it might be because of data throughput (we have peaks of 20k w/s), then I installed influxdb on my machine and created a test scenario.

I ran the following commands in the influx:

```
create database logs

use logs

create retention policy _45d on logs duration 45d replication 1
create retention policy _90d on logs duration 90d replication 1
create retention policy _1y on logs duration 366d replication 1
create retention policy _2y on logs duration 750d replication 1
create retention policy padrao on logs duration 30d replication 1 default

insert log_geral,tag_local=Brazil|BR|RioGrandedoSul|PortoAlegre,tag_latlng=-2.23332|4.12343 miss_time=0.00013,ttfb=0.0000024,bytes=16544
insert log_geral,tag_local=UnitedStates|US|NewYork|NewYorkCity,tag_latlng=-22.23332|44.12343 miss_time=0.0003,ttfb=0.000005,bytes=15654
insert log_geral,tag_local=Japan|JP|Tokyo|Tokyo,tag_latlng=22.452|74.2343 miss_time=0.004403,ttfb=0.003005,bytes=31654

CREATE CONTINUOUS QUERY h_l5m ON logs  BEGIN SELECT percentile(ttfb, 90) AS ttfb, percentile(miss_time, 90) AS miss INTO "logs"."_45d".hl_5m  FROM "logs"."padrao".log_geral GROUP BY time(5m), *  END
CREATE CONTINUOUS QUERY h_l1h ON logs  BEGIN SELECT percentile(ttfb, 90) AS ttfb, percentile(miss, 90) AS miss      INTO "logs"."_45d".hl_1h  FROM "logs"."_45d".hl_5m       GROUP BY time(1h), *  END
CREATE CONTINUOUS QUERY h_l12h ON logs BEGIN SELECT percentile(ttfb, 90) AS ttfb, percentile(miss, 90) AS miss      INTO "logs"."_45d".hl_12h FROM "logs"."_45d".hl_1h       GROUP BY time(12h), * END
CREATE CONTINUOUS QUERY h_l1d ON logs  BEGIN SELECT percentile(ttfb, 90) AS ttfb, percentile(miss, 90) AS miss      INTO "logs"."_90d".hl_1d  FROM "logs"."_45d".hl_12h      GROUP BY time(1d), *  END
CREATE CONTINUOUS QUERY h_l1w ON logs  BEGIN SELECT percentile(ttfb, 90) AS ttfb, percentile(miss, 90) AS miss      INTO "logs"."_1y".hl_1w   FROM "logs"."_90d".hl_1d       GROUP BY time(1w), *  END
CREATE CONTINUOUS QUERY h_l4w ON logs  BEGIN SELECT percentile(ttfb, 90) AS ttfb, percentile(miss, 90) AS miss      INTO "logs"."_2y".hl_4w   FROM "logs"."_1y".hl_1w        GROUP BY time(4w), *  END

CREATE CONTINUOUS QUERY h_b5m ON logs  BEGIN SELECT sum(bytes) AS total INTO "logs"."_45d".hb_5m  FROM "logs"."padrao".log_geral GROUP BY time(5m), *  END
CREATE CONTINUOUS QUERY h_b1h ON logs  BEGIN SELECT sum(total) AS total INTO "logs"."_45d".hb_1h  FROM "logs"."_45d".hb_5m       GROUP BY time(1h), *  END
CREATE CONTINUOUS QUERY h_b12h ON logs BEGIN SELECT sum(total) AS total INTO "logs"."_45d".hb_12h FROM "logs"."_45d".hb_1h       GROUP BY time(12h), * END
CREATE CONTINUOUS QUERY h_b1d ON logs  BEGIN SELECT sum(total) AS total INTO "logs"."_90d".hb_1d  FROM "logs"."_45d".hb_12h      GROUP BY time(1d), *  END
CREATE CONTINUOUS QUERY h_b1w ON logs  BEGIN SELECT sum(total) AS total INTO "logs"."_1y".hb_1w   FROM "logs"."_90d".hb_1d       GROUP BY time(1w), *  END
CREATE CONTINUOUS QUERY h_b4w ON logs  BEGIN SELECT sum(total) AS total INTO "logs"."_2y".hb_4w   FROM "logs"."_1y".hb_1w        GROUP BY time(4w), *  END
```

All right here.

I can query the data:

```
> select * from "logs"."_45d".hl_12h
name: hl_12h
------------
time                 miss      tag_latlng          tag_local                             ttfb
1442923200000000000  0.00013   -2.23332|4.12343    Brazil|BR|RioGrandedoSul|PortoAlegre  2.4e-06
1442923200000000000  0.004403  22.452|74.2343      Japan|JP|Tokyo|Tokyo                  0.003005
1442923200000000000  0.0003    -22.23332|44.12343  UnitedStates|US|NewYork|NewYorkCity   5e-06

>
```

But if I try to check the data to be grouped in one day (select * from "logs"."_90d".hb_1d), the command-line simply hangs. 

For this example I used the 0.9.5-nightly-07c9d40 version, with the default settings. On production we use the latest stable (0.9.4 c4f85f84765e27bfb5e58630d0dea38adeacf543 0.9.4.1).

Am I doing something wrong or this is really a bug?

**Comment by markuspatrick** [comment]
I have a similar behavior (See #3158 ). I suspect that the CQs hang after a while, if you have  a lot of CQs or other read or write queries. Have you restart the DB and checked if your raw data measurements have lags? Do you see lags in the 5m or 1h measurements? Do you have timeouts in your write job, which ist filling the influxdb?

**Comment by brunohass** [comment]
@markuspatrick:
Above is just a test server. To reproduce the error I'm talking is very easy: just start a brand new server and copy/paste the commands. You don't even need to write more data, just the 3 points makes queries to 1d data hang :(

Our production server stores varnish requests statistics (we have a CDN service). This gave us about 5k w/s (sustained)  with peaks of 20~25k w/s. Our service is in beta phase, we expect to have 200k req/s in December, so ~200k w/s to influxdb.

Asking your questions:
- Yes, if I restart the production server some raw points are missing;
- Yes, sometimes I see lags in measurements generated by CQs.
- No write timeouts, but query timeouts after few hours.


Yesterday I make some changes in production server (only log requests to our website) and reduced writes to ~500w/s. Resulting in no more missing data on server restart, measurements lags are gone, no more query timeouts. 



Our production server hardware:
Dell PowerEdge R730
2x Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
320GB RAM DDR4
16x Dell SSD (RAID6)

**Comment by brunohass** [comment]
Hi, CLI doesn't hang anymore in 0.9.5-nightly-6f80d69 using tsm1 and same scenario above. Still needs tests with production workload.

**Comment by jsternberg** [comment]
I'm going to close this due to the issue probably being fixed between when this was filed and the latest version. If you have any issues similar to this one, please file a new issue so we can track it. Thank you.
