### ISSUE TITLE
Continuous queries can potentially be lost or run more than once.

### ISSUE THREAD

**Issue by DanielMorsing** [influxdata/influxdb#4210]
At https://github.com/influxdb/influxdb/blob/master/services/continuous_querier/service.go#L198, we check whether we are the leader of the raft algorithm or not and use that to decide if we should run the continuous query.

More than one node can consider itself leader at the same time and all nodes can consider themselves candidates at the same time. This leaves a potential for a CQ to be executed more than once or missed.

**Comment by jsternberg** [comment]
I'm closing this because it's an older issue that I don't believe is an issue anymore since clustering was removed from the open source version.
