### ISSUE TITLE
Add Windows binaries to nightly build

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#4219]
With go 1.5, it's trivial to generate binaries for windows now:

```
GOOS=windows GOARCH=386 go build ./cmd/influxd
GOOS=windows GOARCH=386 go build ./cmd/influx
```

I would like to see them added to the nightly builds scripts as a simple zipped file for download.  No packager required and we can label it `experimental`.

**Comment by corylanou** [comment]
@otoolep  thoughts?

**Comment by otoolep** [comment]
Thanks @corylanou.

Couple of questions -- why are you building 386 binaries? Are these 32-bit images? We already have a note on our downloads page that we are not providing 32-bit binaries:

https://influxdb.com/download/index.html

Also, the Downloads page will need to be updated. The last question is how much support we provide for this software, which @beckettsean will need to weigh in on. If we provide these images, we'll need to answer questions on the mailing list.

**Comment by corylanou** [comment]
So good point on no 32 bit binaries, we can do just 64bit.

Per @pauldix 
```
+1 for putting out Windows binaries.
```

**Comment by beckettsean** [comment]
I have no blocking concerns about Win64 binaries

**Comment by otoolep** [comment]
@rossmcdonald is reworking our entire build infrastructure, so I'll pass to him, to let him know what he thinks.

**Comment by rossmcdonald** [comment]
Waiting on #4788. The work for this is done through the `build.py` script, we just need `influxd` to compile on Windows.

**Comment by binary132** [comment]
@jwilder, why has this been removed from the 0.10.0 milestone?  Do you know what milestone Windows releases will be available in?

**Comment by jwilder** [comment]
@binary132 `0.10.0` has already been released.   We don't officially support windows and the TSM engine currently is not working on windows (although community members have been contributing fixes to get it working).  We're evaluating windows support and soliciting feedback in #5359.

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
