### ISSUE TITLE
Fully-replicated clusters accessing remote shards

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#4223]
Fully replicated clusters -- clusters where all retention policies have a replication factor equal to the number of nodes in the cluster -- are occassionally accessing shards remotely, even though the query could be served completely by local shards.

This can be seen via the `cluster` diagnostics, which have non-zero counts for remote accesses. It is not clear at this time why this happens.

@jwilder @benbjohnson @corylanou

**Comment by otoolep** [comment]
This started with issue #4170

**Comment by otoolep** [comment]
Example diagnostics output:
```
name: cluster
-------------
map_shard_req	map_shard_resp	write_shard_points_req	write_shard_req

102                        102                      1090857                            1451
```

**Comment by jsternberg** [comment]
Clustering is no longer supported in the open source version so I'm going to close this.
