### ISSUE TITLE
[0.9.4.1] wildcard series search results in "panic: runtime error: slice bounds out of range"

### ISSUE THREAD

**Issue by jbothma** [influxdata/influxdb#4231]
`SELECT * FROM "riemann"../.*/ LIMIT 1` causes influxdb 0.9.4.1 to die with the following.

I have around 500 series fed from riemann

`SELECT * FROM "riemann"../riemann.*/ LIMIT 1` works fine

```
panic: runtime error: slice bounds out of range

goroutine 33399 [running]:
github.com/influxdb/influxdb/tsdb.(*FieldCodec).DecodeFields(0xc826b4be00, 0x7f6624944159, 0x40, 0x7fffffee, 0x9bd300, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/shard.go:654 +0x979
github.com/influxdb/influxdb/tsdb.(*FieldCodec).DecodeFieldsWithNames(0xc826b4be00, 0x7f6624944148, 0x51, 0x7fffffff, 0xc8357f2f80, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/shard.go:669 +0x69
github.com/influxdb/influxdb/tsdb.(*tagSetCursor).decodeRawPoint(0xc8201b7260, 0xc8272dc510, 0xc821dd6a80, 0xc, 0xc, 0x1021428, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/mapper.go:817 +0x89
github.com/influxdb/influxdb/tsdb.(*tagSetCursor).Next(0xc8201b7260, 0x0, 0x140742cca2028547, 0xc821dd6a80, 0xc, 0xc, 0x1021428, 0x0, 0x0, 0x2, ...)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/mapper.go:781 +0x193
github.com/influxdb/influxdb/tsdb.(*SelectMapper).nextChunkRaw(0xc8208f50e0, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/mapper.go:351 +0x13b
github.com/influxdb/influxdb/tsdb.(*SelectMapper).NextChunk(0xc8208f50e0, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/mapper.go:333 +0x286
github.com/influxdb/influxdb/tsdb.(*StatefulMapper).NextChunk(0xc820819500, 0xc823d5f6b0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:49 +0x4d
github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeRaw(0xc823d5f6e0, 0xc822b95260)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:213 +0x167c
created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:94 +0xa1

goroutine 1 [chan receive, 4 minutes]:
main.(*Main).Run(0xc820913f10, 0xc82000a190, 0x2, 0x2, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0xa16
main.main()
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, 4 minutes]:
os/signal.loop()
        /home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f6673cb2ad8, 0x72, 0xc820012130)
        /home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82000d6b0, 0x72, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82000d6b0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82000d650, 0x0, 0x7f6673cb3390, 0xc8358b6180)
        /home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026160, 0xc820039ec8, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820026160, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc820102bc0, 0x7f6673cb2c60, 0xc820026160, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x4b
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:345 +0xae9
```

**Comment by beckettsean** [comment]
Are the results any different if you run `SELECT * FROM /.*/ LIMIT 1` against the `riemann` database but without explicitly naming it in the query string?

How many measurements do not match `/riemann.*/`?

How much RAM on the box?

**Comment by jbothma** [comment]
Same result without naming the database in the query.
```
cat /proc/meminfo 
MemTotal:        3789688 kB
```

**Comment by jbothma** [comment]
I think it's around 1000 measurements. it's about 510 series anyway and some have one measurement, some have 5.

On my prod machine with 8G RAM, `SELECT * FROM /.*/ LIMIT 1` has been sitting working for about 10 minutes now, so it might still fail or eventually succeed. This machine has around 1000 series and probably around 2000 measurements.

**Comment by beckettsean** [comment]
> This machine has around 1000 series and probably around 2000 measurements.

I don't quite follow. A measurement is a container of series. Does each of the 2000 measurements have 1000 series? See the [glossary](https://influxdb.com/docs/v0.9/concepts/glossary.html) for more on the specific meaning of these terms in InfluxDB.

I can verify the slow behavior of the wildcard with a limit. I have about 20 million points across a few dozen series, and `SELECT * FROM /.*/ LIMIT 1` took over a minute to return.

`[http] 2015/09/28 11:05:49 ::1 - - [28/Sep/2015:11:04:41 -0700] GET /query?db=telegraf&q=SELECT+%2A+FROM+%2F.%2A%2F+LIMIT+1 HTTP/1.1 200 1021 - InfluxDBShell/0.9.4.1 645965d9-660b-11e5-8029-000000000000 1m7.451914355s`

It appears that the system has to pull every point off disk to return the query, which seems like a place we could optimize.

**Comment by jbothma** [comment]
Ah right - I think I confused them and didn't read the glossary as well as I should have before. The query `show series` makes me think "uptime/uptime" is a series and it's being rather verbose in showing what's inside - but it all makes sense now with `show measurements` being what I thought I was doing with `show series`

So I have about 500 measurements, some of them for single hosts, some of them for several hosts. Uptime obviously more all hosts in the environment. It looks a bit like

```
name: uptime/uptime
-------------------
_key						host
uptime/uptime,host=beta-web-feb15		beta-web-feb15
uptime/uptime,host=core-01.sandbox		core-01.sandbox.net
uptime/uptime,host=core-02.sandbox		core-02.sandbox.net
```

This crash means I can't downsample all (or perhaps groups of) measurements in one continuous query - I have to generate hundreds or thousands of continuous queries - one per measurement. This doesn't feel right - especially when riemann (or whatever clients are the authorities of what series are being created over time) start checking if series exist or opportunistically trying to create them, perhaps failing.

It feels like I'm missing something and this is waaaaaay more complex than it needs to be. In graphite I think it was one line of config? Obviously this is very powerful but it's also so much work to get a basic metrics database setup right.

**Comment by beckettsean** [comment]
> This crash means I can't downsample all (or perhaps groups of) measurements in one continuous query - I have to generate hundreds or thousands of continuous queries - one per measurement. 

This is partially true. It is not possible to aggregate across measurements, so any downsampling must take place per measurement. However, you can use a regex backreference character to write one continuous query that downsamples all matching measurements. We're still working on the documentation, but you can see the feature described in https://github.com/influxdb/influxdb/pull/3876.

>  start checking if series exist or opportunistically trying to create them, perhaps failing.

A series exists when the first point is written to it, and not before. It cannot be pre-created. If a series cannot be created for whatever reason, the write for that point will fail.

**Comment by jbothma** [comment]
>  series exists when the first point is written to it, and not before. It cannot be pre-created. If a series cannot be created for whatever reason, the write for that point will fail.

Yeah what I meant was every time riemann or whatever starts up or thinks it sees a new measurement, it could either try and create its downsampling continuous query, or it could check if it exists and create it if it doesn't.

The backreference sounds really nice - would that then start working on new measurements when they arrive?

**Comment by beckettsean** [comment]
> would that then start working on new measurements when they arrive?

I honestly don't know. I'll be testing it soon and we'll publish the downsampling guide when that's all documented.

**Comment by jbothma** [comment]
Thanks for the help on this sidetrack :)

**Comment by jsternberg** [comment]
While the function that panics is different, this error seems to be related to #4907.

@jbothma are any of the fields written to `reimann` strings?

**Comment by jsternberg** [comment]
I think this is an error in the bz1 engine. Now that tsm is the default and the new query engine is out, please update to a newer version and try this again. If you still have an issue, please reopen this issue.

Thanks!
