### ISSUE TITLE
[0.9.4.1] WAL Flushing issue

### ISSUE THREAD

**Issue by jhorwit2** [influxdata/influxdb#4240]
I have noticed that the WAL just doesn't flush since 0.9.3.

```
This is a subset of results after running `du -h` in the `/var/opt/influx/wal` directory

2.5K	./watch_v3/default/5830
2.5K	./watch_v3/default/5827
75M	./watch_v3/default/5833
2.0K	./watch_v3/default/5831
2.5K	./watch_v3/default/5813
2.0K	./watch_v3/default/5832
2.5K	./watch_v3/default/5814
75M	./watch_v3/default
75M	./watch_v3
```

I started to get the write throughput errors in my log so I disabled writing to this database over 24hrs ago, yet the WAL doesn't flush to bolt. This means whenever I turned on this database it instantly has issues unless i `rm -rf` that WAL directory which means i lose data I noticed. 

Also, why is it that in all of my databases only 1 shard gets used? Is there some magic I can do to make it more distributed? Even when databases have multiple measurements (sometimes over 20) it still only gets wrote to 1 shard.

**Comment by jhorwit2** [comment]
To me it seems like the WAL has issues, not the underlying storage engine? (related to #4086 )

**Comment by jhorwit2** [comment]
I had to restart before it cleared. Definitely not ideal behavior. 

```
2.0K	./watch_v3/default/5830
2.0K	./watch_v3/default/5827
2.0K	./watch_v3/default/5833
2.0K	./watch_v3/default/5831
2.0K	./watch_v3/default/5813
2.0K	./watch_v3/default/5832
2.0K	./watch_v3/default/5814
16K	./watch_v3/default
17K	./watch_v3
````

**Comment by jsternberg** [comment]
Please try this again with a newer version of the software. There have been a lot of changes since then and this may have been fixed since then. If you find the issue is still happening, please comment on this issue or open a new issue. Thanks.
