### ISSUE TITLE
Client should not support uint64

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#4249]
We don't support it on the server so the go client should throw an error on it. Looks like it got added in #3033

**Comment by arussellsaw** [comment]
+1 on this issue, just ran into it whilst deploying influxdb 0.9

**Comment by jsternberg** [comment]
I don't think this issue applies anymore. Someone else merged in a change awhile ago and the section of code this references has been changed many times since then, so I'm going to close this issue.
