### ISSUE TITLE
feature request: tag index stats

### ISSUE THREAD

**Issue by parisholley** [influxdata/influxdb#4255]
not sure how the new storage engine work will impact this, but i had problems getting started with influx because my tag cardinality was too high (was tagging geo data along side other tags like country, region, state, postal) and it was causing memory usage to go to the roof. I have since limited it to country/region and put the rest as fields.

if tag index stats were available, it would probably be easier to dig into why writes were timing out etc, and could probably be used for some type of capacity dashboard in future to determine if node is tapped out

**Comment by brunohass** [comment]
+1

**Comment by Zolmeister** [comment]
+1

**Comment by boynet** [comment]
+1
