### ISSUE TITLE
Simple select crashes Influx after upgrading from 0.9.2 to 0.9.4

### ISSUE THREAD

**Issue by jstelwag** [influxdata/influxdb#4261]
Dropping and recreating the measurement does not help.

[query] 2015/09/28 21:16:06 SELECT * FROM "nijswiller"."default".room_b
panic: runtime error: slice bounds out of range

goroutine 114 [running]:
github.com/influxdb/influxdb/tsdb.(*FieldCodec).DecodeFields(0xc820412060, 0x7fc26d014438, 0x2, 0x7fffffff, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/shard.go:641 +0x569
github.com/influxdb/influxdb/tsdb.(*FieldCodec).DecodeFieldsWithNames(0xc820412060, 0x7fc26d014438, 0x2, 0x7fffffff, 0x1, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/shard.go:669 +0x69
github.com/influxdb/influxdb/tsdb.(*tagSetCursor).decodeRawPoint(0xc8202f1140, 0xc82046b050, 0xc820382420, 0x2, 0x2, 0x1021428, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/mapper.go:817 +0x89
github.com/influxdb/influxdb/tsdb.(*tagSetCursor).Next(0xc8202f1140, 0x0, 0x140840d586dd757d, 0xc820382420, 0x2, 0x2, 0x1021428, 0x0, 0x0, 0xffffffffffffffff, ...)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/mapper.go:781 +0x193
github.com/influxdb/influxdb/tsdb.(*SelectMapper).nextChunkRaw(0xc8201ed200, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/mapper.go:351 +0x13b
github.com/influxdb/influxdb/tsdb.(*SelectMapper).NextChunk(0xc8201ed200, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/mapper.go:333 +0x286
github.com/influxdb/influxdb/tsdb.(*StatefulMapper).NextChunk(0xc8202cecc0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:49 +0x4d
github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeRaw(0xc82046a330, 0xc8203234a0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:213 +0x167c
created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:94 +0xa1

goroutine 1 [chan receive, 1 minutes]:
main.(*Main).Run(0xc82003ff10, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0xa16
main.main()
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, 1 minutes]:
os/signal.loop()
        /home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7fc27e4b0b78, 0x72, 0xc82000e150)
        /home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200473a0, 0x72, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200473a0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820047340, 0x0, 0x7fc27e4b11c8, 0xc82041fa00)
        /home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820020158, 0xc820033ec8, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820020158, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc820128a80, 0x7fc27e4afbf8, 0xc820020158, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x4b
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:345 +0xae9

goroutine 9 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820020160, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc82012d800, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:2059 +0x51
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc8200473b0)
        /tmp/build/src/github.com/hashicorp/raft/net_transport.go:346 +0x79
created by github.com/hashicorp/raft.NewNetworkTransport
        /tmp/build/src/github.com/hashicorp/raft/net_transport.go:138 +0x284

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc8200881c0)
        /tmp/build/src/github.com/hashicorp/raft/raft.go:849 +0xcce
github.com/hashicorp/raft.(*Raft).runLeader(0xc8200881c0)
        /tmp/build/src/github.com/hashicorp/raft/raft.go:821 +0x936
github.com/hashicorp/raft.(*Raft).run(0xc8200881c0)
        /tmp/build/src/github.com/hashicorp/raft/raft.go:602 +0xbb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
        /tmp/build/src/github.com/hashicorp/raft/raft.go:252 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200881c0, 0xc820132ac0)
        /tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 11 [select, 1 minutes]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc8200881c0)
        /tmp/build/src/github.com/hashicorp/raft/raft.go:509 +0x10eb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
        /tmp/build/src/github.com/hashicorp/raft/raft.go:253 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200881c0, 0xc820132ad0)
        /tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 12 [select, 1 minutes]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc8200881c0)
        /tmp/build/src/github.com/hashicorp/raft/raft.go:1636 +0x493
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
        /tmp/build/src/github.com/hashicorp/raft/raft.go:254 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200881c0, 0xc820132ae0)
        /tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 13 [select, 1 minutes]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc82000ba40)
        /tmp/build/src/github.com/influxdb/influxdb/meta/state.go:187 +0x4f5
created by github.com/influxdb/influxdb/meta.(*localRaft).open
        /tmp/build/src/github.com/influxdb/influxdb/meta/state.go:177 +0x1344

goroutine 14 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820020168, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc8200788c0)
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:622 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:239 +0x364

goroutine 15 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820020170, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc8200788c0)
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:726 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3b6

goroutine 23 [select, 1 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc8201150e0, 0xc82000c9c0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:491 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:351 +0xc67

goroutine 31 [select, 1 minutes]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc8201d8960, 0xc8203222a0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 30 [select, 1 minutes]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc8201d8780, 0xc820280a20)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 28 [select, 1 minutes]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc8201d8500, 0xc8201dd800)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 25 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820082700, 0xc8201dd080)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 29 [select, 1 minutes]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc8201d86e0, 0xc8201ddc20)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 32 [select, 1 minutes]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc8201d8a00, 0xc820322de0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 33 [select, 1 minutes]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc8201d8aa0, 0xc8203239e0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 34 [select, 1 minutes]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc8201d8b40, 0xc820323e00)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 38 [select, 1 minutes]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc8201d8be0, 0xc82046c420)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 39 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc82006e5a0)
        /tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:103 +0x314
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:67 +0x210

goroutine 40 [select, 1 minutes]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc82006e5a0)
        /tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:121 +0x2d1
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:68 +0x232

goroutine 41 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820020178, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc8200472d0)
        /tmp/build/src/github.com/influxdb/influxdb/cluster/service.go:84 +0xdb
created by github.com/influxdb/influxdb/cluster.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/cluster/service.go:61 +0x135

goroutine 42 [select, 1 minutes]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc820128700)
        /tmp/build/src/github.com/influxdb/influxdb/services/precreator/service.go:75 +0x44f
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/precreator/service.go:53 +0x21f

goroutine 43 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820020180, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc82000b360)
        /tmp/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:75 +0xa9
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:48 +0x130

goroutine 44 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820020188, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/services/copier.(*Service).serve(0xc820128780)
        /tmp/build/src/github.com/influxdb/influxdb/services/copier/service.go:78 +0xa9
created by github.com/influxdb/influxdb/services/copier.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/copier/service.go:51 +0x130

goroutine 45 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7fc27e4b0938, 0x72, 0xc82000e150)
        /home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203d3640, 0x72, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203d3640, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8203d35e0, 0x0, 0x7fc27e4b11c8, 0xc82046f0c0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820021108, 0x455470, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820021108, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc82046cf60, 0x7fc27e4afbf8, 0xc820021108, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7fc27e4afbf8, 0xc820021108, 0x7fc27e4bab90, 0xc82048e230, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1765 +0x85
github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc82000b450)
        /tmp/build/src/github.com/influxdb/influxdb/services/admin/service.go:107 +0x12f
created by github.com/influxdb/influxdb/services/admin.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/admin/service.go:70 +0x491

goroutine 46 [select]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc82006e6c0)
        /tmp/build/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:192 +0x565
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:126 +0x2a4

goroutine 47 [IO wait]:
net.runtime_pollWait(0x7fc27e4b0878, 0x72, 0xc82000e150)
        /home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203d36b0, 0x72, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203d36b0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8203d3650, 0x0, 0x7fc27e4b11c8, 0xc82041efe0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820021110, 0xc82002fdc0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820021110, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc82046d020, 0x7fc27e4afbf8, 0xc820021110, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7fc27e4afbf8, 0xc820021110, 0x7fc27e4babb8, 0xc82007d280, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1765 +0x85
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc82000ce40)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/service.go:133 +0x6e
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/service.go:101 +0x6ca

goroutine 48 [IO wait]:
net.runtime_pollWait(0x7fc27e4b07b8, 0x72, 0xc82000e150)
        /home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203d3720, 0x72, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203d3720, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readFrom(0xc8203d36c0, 0xc82029e000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x7fc27e4aa050, 0xc82000e150)
        /home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:259 +0x2a5
net.(*UDPConn).ReadFromUDP(0xc820021118, 0xc82029e000, 0x10000, 0x10000, 0x10000, 0x10000, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/udpsock_posix.go:61 +0x117
github.com/influxdb/influxdb/services/udp.(*Service).serve(0xc82006e750)
        /tmp/build/src/github.com/influxdb/influxdb/services/udp/service.go:140 +0x14c
created by github.com/influxdb/influxdb/services/udp.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/udp/service.go:94 +0x93a

goroutine 49 [select]:
github.com/influxdb/influxdb/services/udp.(*Service).writePoints(0xc82006e750)
        /tmp/build/src/github.com/influxdb/influxdb/services/udp/service.go:104 +0x50b
created by github.com/influxdb/influxdb/services/udp.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/udp/service.go:95 +0x95f

goroutine 50 [select, 1 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc82000b630)
        /tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:69 +0x351
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x1b4

goroutine 51 [select, 1 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc82000b630)
        /tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:102 +0x7a0
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:46 +0x1d9

goroutine 52 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc8201150e0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:442 +0x1eb
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:378 +0x1265

goroutine 53 [select, 1 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc82007c380)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:138 +0x2c5
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:120 +0xeeb

goroutine 54 [select, 1 minutes, locked to thread]:
runtime.gopark(0xd19ec8, 0xc820489f28, 0xbd5940, 0x6, 0x431018, 0x2)
        /home/philip/.gvm/gos/go1.5/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820489f28, 0x0, 0x18)
        /home/philip/.gvm/gos/go1.5/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820489f28)
        /home/philip/.gvm/gos/go1.5/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /home/philip/.gvm/gos/go1.5/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 55 [select]:
github.com/influxdb/influxdb/tsdb.(*PointBatcher).Start.func2(0xc82000d080, 0xc82046f120, 0xc82046f140, 0xc820021130, 0xc820021128)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/batcher.go:72 +0x522
created by github.com/influxdb/influxdb/tsdb.(*PointBatcher).Start
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/batcher.go:107 +0x17e

goroutine 113 [chan receive]:
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeSelectStatement(0xc82000b0e0, 0x0, 0xc8204ba300, 0xc8203233e0, 0x2710, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/query_executor.go:285 +0xeb
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery.func1(0xc8202ce9c0, 0xc8203e82e5, 0xa, 0xc82000b0e0, 0xc8203233e0, 0x2710)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/query_executor.go:159 +0x757
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/query_executor.go:213 +0x9b

goroutine 97 [chan receive]:
github.com/influxdb/influxdb/services/httpd.(*Handler).serveQuery(0xc82007d280, 0x7fc27e4be398, 0xc8202ce8e0, 0xc8200820e0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:286 +0xc2c
github.com/influxdb/influxdb/services/httpd.(*Handler).(github.com/influxdb/influxdb/services/httpd.serveQuery)-fm(0x7fc27e4be398, 0xc8202ce8e0, 0xc8200820e0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:98 +0x48
github.com/influxdb/influxdb/services/httpd.authenticate.func1(0x7fc27e4be398, 0xc8202ce8e0, 0xc8200820e0)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:673 +0x70
net/http.HandlerFunc.ServeHTTP(0xc820131b40, 0x7fc27e4be398, 0xc8202ce8e0, 0xc8200820e0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.gzipFilter.func1(0x7fc27e4be128, 0xc8202ce860, 0xc8200820e0)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:734 +0x2af
net/http.HandlerFunc.ServeHTTP(0xc820131b60, 0x7fc27e4be128, 0xc8202ce860, 0xc8200820e0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.versionHeader.func1(0x7fc27e4be128, 0xc8202ce860, 0xc8200820e0)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:743 +0xc0
net/http.HandlerFunc.ServeHTTP(0xc820131b80, 0x7fc27e4be128, 0xc8202ce860, 0xc8200820e0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.cors.func1(0x7fc27e4be128, 0xc8202ce860, 0xc8200820e0)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:776 +0x328
net/http.HandlerFunc.ServeHTTP(0xc820131ba0, 0x7fc27e4be128, 0xc8202ce860, 0xc8200820e0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.requestID.func1(0x7fc27e4be128, 0xc8202ce860, 0xc8200820e0)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:786 +0x15d
net/http.HandlerFunc.ServeHTTP(0xc820131bc0, 0x7fc27e4be128, 0xc8202ce860, 0xc8200820e0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.logging.func1(0x7fc27e4be128, 0xc8202ce840, 0xc8200820e0)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:794 +0x10b
net/http.HandlerFunc.ServeHTTP(0xc820131be0, 0x7fc27e4be128, 0xc8202ce840, 0xc8200820e0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.recovery.func1(0x7fc27e4be0f0, 0xc8200ba9a0, 0xc8200820e0)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:804 +0x114
net/http.HandlerFunc.ServeHTTP(0xc820131c00, 0x7fc27e4be0f0, 0xc8200ba9a0, 0xc8200820e0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc820020118, 0x7fc27e4be0f0, 0xc8200ba9a0, 0xc8200820e0)
        /tmp/build/src/github.com/bmizerany/pat/mux.go:109 +0x244
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc82007d280, 0x7fc27e4be0f0, 0xc8200ba9a0, 0xc8200820e0)
        /tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:172 +0x357
net/http.serverHandler.ServeHTTP(0xc82046d020, 0x7fc27e4be0f0, 0xc8200ba9a0, 0xc8200820e0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200ba000)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1910 +0x3f6

**Comment by jwilder** [comment]
This code no longer exists.  Please open a new issue with steps to reproduce if you still see this panic.
