### ISSUE TITLE
Confusion around aggregation/derivatives and intervals smaller than data-point interval?

### ISSUE THREAD

**Issue by victorhooi** [influxdata/influxdb#4312]
_This is based on discussions on https://github.com/grafana/grafana/issues/2802 with @jwilder_

I'm attempting to use the `derivative` function with InfluxDB, via Grafana, and hitting some issues.

I have a data-set with data at 1-second intervals. Here is an aggregation using `mean`, using a `GROUP BY` of 1 second:
```
> SELECT mean("opcounters_query") AS "opcounters_query" FROM "serverstatus" WHERE "hostname" = 'mongo101prsm' AND time > 1443824700s and time < 1443824704s GROUP BY time(1s)
name: serverstatus
------------------
time                    opcounters_query
1443824700000000000     1.230985e+06
1443824701000000000     1.231294e+06
1443824702000000000     1.231655e+06
1443824703000000000     1.232368e+06
```

If I change the GROUP BY to `100ms`, I get values at every 100ms with what I think is `nil`, and values in between:
```
> SELECT mean("opcounters_query") AS "opcounters_query" FROM "serverstatus" WHERE "hostname" = 'mongo101prsm' AND time > 1443824700s and time < 1443824704s GROUP BY time(100ms)
name: serverstatus
------------------
time                    opcounters_query
1443824700000000000
1443824700100000000
1443824700200000000
1443824700300000000     1.230985e+06
1443824700400000000
1443824700500000000
1443824700600000000
1443824700700000000
1443824700800000000
1443824700900000000
1443824701000000000
1443824701100000000
1443824701200000000
1443824701300000000     1.231294e+06
1443824701400000000
1443824701500000000
1443824701600000000
1443824701700000000
1443824701800000000
1443824701900000000
1443824702000000000
1443824702100000000
1443824702200000000
1443824702300000000     1.231655e+06
```

My first question is - InfluxDB isn't interpolating between each 1-second value - is this something that would be on the roadmap? The closest I could find is:

https://github.com/influxdb/influxdb/issues/3273

It sounds like it's something that would solve a lot of the confusion and issues around GROUP BY and intervals smaller than your data frequency, or around sparse data/missing points. Would you agree?

Now, I try the `derivative` function. If I use a `GROUP BY` of 1-second again, it all seems to work:
```
> SELECT derivative(mean("opcounters_query")) AS "opcounters_query" FROM "serverstatus" WHERE "hostname" = 'mongo101prsm' AND time > 1443824700s and time < 1443824704s GROUP BY time(1s)
name: serverstatus
------------------
time                    opcounters_query
1443824701000000000     309
1443824702000000000     361
1443824703000000000     713
```

However, if I change the `GROUP BY` to 100ms, I just get a bunch of nils - no values at all even at the 1-second intervals
```
> SELECT derivative(mean("opcounters_query")) AS "opcounters_query" FROM "serverstatus" WHERE "hostname" = 'mongo101prsm' AND time > 1443824700s and time < 1443824704s GROUP BY time(100ms)
name: serverstatus
------------------
time                    opcounters_query
1443824700100000000
1443824700200000000
1443824700300000000
1443824700400000000
1443824700500000000
1443824700600000000
1443824700700000000
1443824700800000000
1443824700900000000
1443824701000000000
etc.
```

I'm not really sure why this is?

The problem is - Grafana picks the GROUP BY interval based on your zoom - so as you zoom into points, it will shrink the interval accordingly. So it's quite easy to end up with a `GROUP BY` interval of say, 100ms, as you zoom into your data-points.

Any thoughts on the best way to resolve this?

**Comment by jwilder** [comment]
@victorhooi 
1. The database does not interpolate values when down sampling currently.
2. Yes, #3273 might help derivatives in this case.
3. You get `nils` with the derivative when grouped by `100ms` because all the points have a `nil` as it's previous value so we can't compute the derivative.  A `fill(previous)` or `fill(0)` might be the only option here currently.  We might also be able to update the derivative to interpolate the `nil`s that fall in between valid points though.

**Comment by jsternberg** [comment]
I'm going to close this due to it being old. If the questions haven't been answered, please direct your questions to the [mailing list](https://groups.google.com/forum/#!forum/influxdb). Thank you.
