### ISSUE TITLE
[feature request] Add function chaining syntax

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4327]
See the comments on https://github.com/influxdb/influxdb/issues/4187, particularly

https://github.com/influxdb/influxdb/issues/4187#issuecomment-142207099
https://github.com/influxdb/influxdb/issues/4187#issuecomment-144782271
https://github.com/influxdb/influxdb/issues/4187#issuecomment-145275844

**Comment by pauldix** [comment]
Updated this issue to change the name and adding more context. In our query language we have three concepts: aggregators, transformations, and selectors. Aggregations are functions like count and mean, transformations are things like derivative or moving average, selectors are things like min and max that map to a specific data point.

Often, users want to combine a bunch of these and the basic SQL syntax leaves much to be desired if you want to do a bunch of complicated stuff. We should expand our query syntax to have a function chaining style. This would clean up a bunch of things in the query language and should be additive (non-breaking).

Here's an example:

```
SELECT 
   mean(value).derivative(1s).movingAverage(10).scale(100).alias('mvg_avg')
FROM measurement
WHERE time > now() - 4h
GROUP BY time(1m)

-- or using the D3 style
SELECT 
   mean(value)
     .derivate(1s)
     .movingAverage(10)
     .scale(100)
     .alias('mvg_avg')
FROM measurement
WHERE time > now() - 4h
GROUP BY time(1m)
```

The `FROM`, `WHERE`, and `GROUP BY` clauses are applied across the board to the functions in the select clause. Taking it further we can do multiple fields or math:

```sql
SELECT
  mean(value),
  percentile(90, value),
  max(value) * 100
FROM measurement
WHERE time > now() - 4h
GROUP BY time(10m)
```

Or math operations can be represented as a function:

```SQL
SELECT
  mean(value).math(* 100)
FROM measurement
WHERE time > now() - 4h
GROUP BY time(10m)
```

Then we can take it even further and move the trailing clauses into functions in the `SELECT``. Here's an example where `FROM` is specified via the functions.

```sql
SELECT
  from("errors").count(value) /
  from("requests").count(value) * 100 AS error_percentage
WHERE time > now() - 4h
GROUP BY time(10m)
```

The work @benbjohnson is doing on the query engine will need to be completed before this is possible. What you think Ben?

Feedback welcome!

**Comment by benbjohnson** [comment]
@pauldix First of all, JavaScript-related examples should be removed from any issue in this repo. :)

What's the benefit of using chaining instead of wrapping? e.g.

```
scale(movingAverage(derivative(mean(value),1s), 10), 100) AS mvg_avg
```

**Comment by pauldix** [comment]
Chaining is much easier to read and understand. Just ask anyone who's tried to make Lisp popular ;)

**Comment by benbjohnson** [comment]
Don't make me CC Rick Hickey on this issue...

**Comment by benbjohnson** [comment]
From a technical standpoint, there's nothing preventing us from doing function chaining. The functions produce an `iterator` and that can be passed as the first argument to the next function.

As for the `FROM` in the `SELECT` clause, that's a much bigger change in the parser. Why not do the SQL style prefixing:

```
SELECT count(errors.value) / count(requests.value) * 100 AS error_percentage
FROM errors, requests
WHERE time > now() - 4h
GROUP BY time(10m)
```

**Comment by pauldix** [comment]
Sure, that `FROM` syntax works for me. Also makes it easier to represent merges across measurements.

**Comment by beckettsean** [comment]
+1 for keeping the SQL-like syntax over the JavaScript inspired syntax. JS might be intuitive for devs but a lot of sysadmins, data analysts, and other likely InfluxDB users don't know or care about it. SQL is ubiquitous.
