### ISSUE TITLE
make Go HTTP client configurable

### ISSUE THREAD

**Issue by aybabtme** [influxdata/influxdb#4343]
How opposed would you be to making this:

https://github.com/influxdb/influxdb/blob/master/client/influxdb.go#L114

... configurable, so that one be able to pass their own `*http.Client` with, for instance, custom transport? The change I'd see would be to take an `*http.Client` in the `type Config struct` instead of a `Timeout time.Duration`, but that would break existing users.

**Comment by ernestoalejo** [comment]
This is important for App Engine where you have to use a custom transport:
https://godoc.org/google.golang.org/appengine/urlfetch#Transport

**Comment by nchiring** [comment]
+1

**Comment by jsternberg** [comment]
See influxdata/influxdb-client#2 where we are working on a new API for the client and separating it from the current repository.
