### ISSUE TITLE
[0.9.5-nightly-23fb7e2] Memory leak on SELECT/aggregation query

### ISSUE THREAD

**Issue by mastor** [influxdata/influxdb#4346]
I'm running influxdb installed from the nightly package on a Ubuntu 14.04 server.

The dataset is pretty small, 3000 daily points from 2005-01-01:

    4,0K    influxdb/hh
    308K    influxdb/meta
    12M     influxdb/data
    2,0M    influxdb/wal
    15M     influxdb

and the query

    SELECT mean(value) FROM "test" WHERE time > timestamp and time < now() GROUP BY time(1d)

raise the memory usage to

     995M  Virtual
     570M Resident

that is almost 100 times the dataset size.

How to reproduce:

    # create database
    curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

    # write data
    WHEN=`date -u -d "2005-01-01" +"%s"`
    for i in $(seq 1 3000); do
            curl -X POST http://localhost:8086/write?db=mydb --data-binary "value1,test=1 value=$i ${WHEN}000000000"
            let "WHEN+=86400"
    done

    # query
    curl -G http://localhost:8086/query?db=mydb --data-urlencode 'q=SELECT mean(value1) FROM "value1" WHERE time > 1104534000s and time < now() GROUP BY time(1d)'

**Comment by jwilder** [comment]
I'm seeing the same thing locally with `tsm1` and `bz1` engines using your repro steps.  I think this is due to each shard being mmap'd and open .  There are about 450 shards created by this script and they are all mmap'd and open.  I'm seeing about 455M RSS.  If I change the script to create fewer shards (~218), RSS is around 240M.  

After the query runs, there are some mapper allocations still hanging around but they do get garbage collected.  RSS does not go back down though, but I can't really get it to increase indefinitely after it gets to a reasonable size to handle the query load.   This may just be the behavior of the go runtime after allocating a lot of memory during a query as well as the just overhead for lots of shards open and mmap'd.

@DanielMorsing @otoolep maybe you have some idea?

**Comment by otoolep** [comment]
Yeah, I don't have any particular insights apart what you offered. I suggest @mastor start looking at the internal Go runtime stats if more information is required.

https://influxdb.com/blog/2015/09/22/monitoring_internal_show_stats.html

**Comment by DanielMorsing** [comment]
Linux counts mmap pages as being in RSS, even if they can be evicted. I don't think there's a memory leak here.

Given that we have to expand the SSTables again when we read them, would it make more sense to have a cache of the result in memory rather than just the blocks on disk?

**Comment by mastor** [comment]
The query:

    select * from value1

does not raise the memory usage and yet it should read all the series points and therefore mmap all the shards. 

Alloc | Frees | HeapAlloc | HeapIdle | HeapInUse | HeapObjects | HeapReleased | HeapSys | Lookups | Mallocs | NumGC | NumGoroutine | PauseTotalNs | Sys | TotalAlloc
------|-------|-----------|----------|-----------|-------------|--------------|---------|---------|---------|-------|--------------|--------------|-----|----------
41,523,328 | 2,089,855 | 41,523,328 | 10,182,656 | 42,672,128 | 225,948 | 0 | 52,854,784 | 5,335 | 2,315,803 | 27 | 469 | 14,703,209 | 60,184,824 | 297,764,192

While the aggregated version increase the memory usage:

Alloc | Frees | HeapAlloc | HeapIdle | HeapInUse | HeapObjects | HeapReleased | HeapSys | Lookups | Mallocs | NumGC | NumGoroutine | PauseTotalNs | Sys | TotalAlloc
------|-------|-----------|----------|-----------|-------------|--------------|---------|---------|---------|-------|--------------|--------------|-----|----------
458,321,128 | 19,839,745 | 458,321,128 | 49,152 | 547,012,608 | 9,500,059 | 0 | 547,061,760 | 5,432 | 29,339,804 | 46 | 469 | 33,275,400 | 591,008,320 | 1,450,997,240

However, I also believe there is fundamental problem on how the shards are created, since 6 or 7 points per shard is a waste of resources. Maybe it should allocate shards dynamically based on some kind of usage pattern. Or maybe a configuration option to define the shard size in days could give more flexibility.

**Comment by otoolep** [comment]
The code paths for aggregated queries vs others are very different. I am
not sure why you think memory usage should necessarily be the same.

**Comment by mastor** [comment]
I'm not saying it should be necessarily the same, but it's suspicious why running two pure functions (group and mean) on a subset of the data causes a 10x memory footprint increase, when, in theory, pure functions don't have side effects.

**Comment by jsternberg** [comment]
I'm going to close this issue because we completely replaced the query engine and the engine between 0.9.x and 0.13. Please try the new version and open a new issue if you believe the issue persists. Thank you.
