### ISSUE TITLE
Add cross compile checks to continuous build (circle)

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#4359]
We should add all cross-compile checks for all platforms we compile to in our scripts.  This will help prevent breaking platform changes moving forward.

**Comment by jsternberg** [comment]
I know we have a separate build for Windows at the moment. Do we build against Mac OS X on Circle? @rossmcdonald

**Comment by rossmcdonald** [comment]
Not in Circle, but we do have Darwin nightly builds which would notify us to any build issues. I've never heard of a breaking compilation change between Linux and Darwin, though, so I'm not sure how much value would be added. It would also increase the Circle turnaround times, which may get annoying after a while.

**Comment by jsternberg** [comment]
I'm going to close this then.
