### ISSUE TITLE
Corruption detected during bz1 WAL unit testing

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#4382]
https://circle-artifacts.com/gh/influxdb/influxdb/6494/artifacts/2/tmp/circle-artifacts.fO26rJZ/test_logs_race.txt

```
=== RUN   TestWAL_CorruptDataBlock
[wal] 2015/10/09 03:31:49 corrupt compressed block in file: snappy: corrupt input /tmp/wal-test147508374/01.000001.wal
--- PASS: TestWAL_CorruptDataBlock (0.13s)
=== RUN   TestWAL_CompactAfterTimeWithoutWrite
--- FAIL: TestWAL_CompactAfterTimeWithoutWrite (1.90s)
	wal_test.go:330: expected first data point but got one with key: 4
```

**Comment by otoolep** [comment]
Hit this again on Circle.

https://circle-artifacts.com/gh/influxdb/influxdb/6538/artifacts/1/tmp/circle-artifacts.z65xUVj/test_logs_i386.txt

**Comment by otoolep** [comment]
Hit it again today:
https://circle-artifacts.com/gh/influxdb/influxdb/6618/artifacts/2/tmp/circle-artifacts.0RyS5MY/test_logs_race.txt

**Comment by jwilder** [comment]
This test is for `bz1` WAL.  I'm seeing it fail locally from time to time as well.

**Comment by otoolep** [comment]
Ah yes, you are right @jwilder -- not sure why I interpreted at `tsm1`.

**Comment by jsternberg** [comment]
The `bz1` engine is now gone so I'm going to close this since I think it's no longer relevant.
