### ISSUE TITLE
[0.9.4.1] very minor bug with SHOW MEASUREMENTS and empty measurements

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4395]
`SHOW MEASUREMENTS` returns nothing if all measurements in the database are empty, even if they exist.

I accidentally deleted all points in the database when I hit this (fixed) bug: https://github.com/influxdb/influxdb/issues/4276. As such I have a database with defined measurements but no points. `SHOW MEASUREMENTS` returns nothing until I write the first point to any measurement, and then it returns the right list of measurements.

```
> use mydb
Using database mydb
> show measurements
> insert foo value=12
> show measurements
name: measurements
------------------
name
foo
h2o_feet
ifHCInUcastPkts
math

> select * from /.*/
name: foo
---------
time				a	b	location	status!	value	water_level
2015-10-10T00:41:54.213966399Z						12	

> 
```

**Comment by beckettsean** [comment]
The other columns in the `SELECT * FROM /.*/` output are from the other measurements.

**Comment by jsternberg** [comment]
@beckettsean I think the measurement itself might be removed if you delete all points from the measurement. If this is the case, you wouldn't expect to see the measurement anymore if you called `SHOW MEASUREMENTS`.

**Comment by beckettsean** [comment]
this is an 0.9 bug anyway, I vote we close until someone sees it with 0.13+

**Comment by jsternberg** [comment]
I tested it before commenting. It still happens, but I think it's intended.
