### ISSUE TITLE
[Feature request] Being able to select Encoding for fields in new storage engine

### ISSUE THREAD

**Issue by RobMcZag** [influxdata/influxdb#4407]
With the introduction of the new engine we have different encodings (and more could be added) that could be applied to values of a certain kind. 
Currently fields get type and encoding at creation time, i.e. when you first write a field, but that can be sub-optimal.
Would be useful to be able to set and maybe even change (could need to rewrite all the column data) the type / encoding of a certain field or of a set of fields, actually partially specifying the schema.

As an example I could say an integer field encoding a status reading: the statuses are quite few and most of the time the status is the same for hours or days (before a battery is changed or a repair performed) or for months if everything is OK. In this case RLE (Run Length Encoding) could be used with great advantage: with 4-8 bytes you could represent a full day where the status has not changed (86.400 values if sampled every second), actually storing that value almost for free.

This idea started commenting the issue #4086, regarding the new engine.

**Comment by jwilder** [comment]
I think there is some mis-information in that original thread that might be causing confusion.  Fields have a type defined the first time they are written, but how they are encoded on disk is not defined statically for the field or series.  The encoding is selected per block, based on the data in the block and the type of field.  Within a given shard, there are multiple blocks that, contain up to 1000 points.  Each block can be encoded differently if the shape of the data changes over time.  The `tsm1` engine will combine blocks over time too.  

Timestamps do actually use RLE for the block if the times for all the points are equally spaced.  If the block happens to have irregular timestamp intervals, we'd use the next best format which is a delta-encoded, bit-packed format.  We do this for the value types as well although most just have one or two encodings to choose from currently.

**Comment by fg2it** [comment]
I don't think this is a reasonable feature : it is quite low level; would probably requires benchmarking to choose the right parameter value; easy to use wrong; adaptative choice would probably perfom better on average.
If some influence on the compression method is wanted, I feel that what you really want to do is not choosing the compression method but influence the compression ratio/cpu load trade-off. For this, a coarser setting telling where your preference goes would be better, eg high compression/high cpu, balanced, low compression/low cpu whatever these could mean. If some compression choice is to be made, let the engine do it based on this setting.

**Comment by jsternberg** [comment]
I'm going to close this since I don't think we are currently considering doing this. If this is a feature you really need, please comment and we can look at potentially doing this for sometime post-1.0.

Thank you.
