### ISSUE TITLE
[feature] Authentication with JWT tokens

### ISSUE THREAD

**Issue by jonasfj** [influxdata/influxdb#4448]
Currently influxdb has users with `username` and `password` which is sent in plain text as `authentication` header or as query-string parameters. We all know this is bad :)

I suggest that we add support for authentication with JWT tokens in `authentication` header or as query-string parameters. We let the JWT token contain `username` along with `start` and `expiry` timestamps, and authorize the JWT token if it is HMAC-SHA256 signed with users `password`.

The signed JWT payload would look like this:
```js
{
  user: "myUserName",
  start: "2015-10-14T17:13:58.006Z",
  expiry: "2015-10-14T17:15:58.006Z"
}
```

This is very easy to validate and doesn't require additional configuration, but dramatically increases the security and allows users to grant temporary access someone by issuing them a JWT token.
Go libraries for validation of JWTs should be readily available too.

This is a huge feature as dashboards may wish to grant web users direct access to call influxdb, so that calls doesn't have to be proxied. And yet the web client doesn't access to the secret and only use the JWT until it expires.

**Comment by gunnaraasen** [comment]
JWT authentication would be a nice option and more secure.

That said, query strings and headers are encrypted when HTTPS is enabled.

**Comment by jonasfj** [comment]
Yeah, https makes it sane.. But still makes it very hard to delegate access. Ideally, most of my micro services should never have permanent credentials instead they should call a gatekeeper service that grants them temporary credentials. This is how I deal with AWS and Azure access, gatekeeper service grants temporary credentials. 

I just dived into the code, looking to make a PR assuming this would be easy. But it seems the actual passwords aren't stored, but only the bcrypt hash of the password. I guess an easy hack would be to sign the JWT with the bcrypt hash of the password, but this would be obscure for users.

Ideal would be to store the raw password, as people could then set their password to an RSA or ECDSA base64 encoded public key :)
And config options could be used to limit what authentication mechanisms and signature algorithms are allowed.

I guess that would result in a temporary security reduction for people already sending their passwords over the wire. As the real password would exist in the database, but getting a solid auth mechanism might be worth it. Thoughts?
(It would certainly be easier for me to fix influx than write a service that rotates passwords on influxdb)

**Comment by beckettsean** [comment]
@jonasfj we are working on products to better connect the authorization component of the database with actual enterprise needs. The authorization complexity will reside in the service, however, not in the InfluxDB database code.

**Comment by jonasfj** [comment]
> we are working on products to better connect the authorization component of the database with actual enterprise needs

You are planning to do a product? I would think that userId/secretToken model that aws and azure uses is sufficient. Ideally with the ability to make temporary credentials (like aws STS or azure SAS).
Granted all of this comes for free with JWT :) 

> The authorization complexity will reside in the service, however, not in the InfluxDB database code.

By service you mean, `services/httpd/...` right? (just curious)

**Comment by dgnorton** [comment]
added in #6609
