### ISSUE TITLE
Enhancement : Package Windows binaries in Zip along with current msi package

### ISSUE THREAD

**Issue by mvadu** [influxdata/influxdb#4452]
Thank you for finally adding Windows to your officially supported OSs. However msi has some problems in enterprise world
1. Downloads to .msi are usually blocked
2. Running msi requires admin rights

Influx for its purposes does not need admin rights, and will happily run with a normal user token. Please create zip file containing CLI and server executable (.exe), and make that available under downloads.

**Comment by mvadu** [comment]
@otoolep pls consider along with #4219 Nightly will be good candidate for not having msi, but just a zip with exes.

**Comment by rossmcdonald** [comment]
Just to update this issue, with https://github.com/influxdata/influxdb/pull/6111 Windows zip contents now look like:

```
Archive:  influxdb-nightly_windows_amd64.zip
influx.exe
influx_inspect.exe
influx_stress.exe
influx_tsm.exe
influxd.exe
influxdb.conf
```

**Comment by mvadu** [comment]
@rossmcdonald awesome! Will these be part of nightly builds, so that we (Windows users) can give it a try more frequently?

**Comment by rossmcdonald** [comment]
@mvadu Yes, Windows is now part of the nightly build process. Link to download is:

https://s3.amazonaws.com/influxdb/influxdb-nightly_windows_amd64.zip

Let me know if you run into any issues with them.

**Comment by mvadu** [comment]
:+1: Superb!! Are you guys planning to add tests on windows as well? That way core team will know if any commits to master are breaking on Windows.

**Comment by rossmcdonald** [comment]
@mvadu No, we don't have plans to test on Windows at this time, so all of the Windows builds should be considered _very_ experimental until it is officially supported.

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by ftdgeri** [comment]
I am very new with influxdb.  and I am trying to install the influxdb 1.3.2 in the windows. but the http://localhost:8086 doesn't work.  Could anyone give some idea what I should change in the config file? so confused.
