### ISSUE TITLE
[feature request] change default time boundaries

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4461]
To address https://github.com/influxdb/influxdb/issues/2703, https://github.com/influxdb/influxdb/issues/3369, https://github.com/influxdb/influxdb/issues/3789, and to clear up confusion about https://influxdb.com/docs/v0.9/troubleshooting/frequently_encountered_issues.html#querying-after-now, it would make sense to change the default lower bound from `epoch 0` to the smallest timestamp and the default upper bound from `now()` to the largest possible timestamp.

I believe the smallest is -9023372036854775808, although https://github.com/influxdb/influxdb/issues/3367 means that's not valid right now. The largest timestamp is 9023372036854775807. These were derived from testing, not from parsing code.

**Comment by gunnaraasen** [comment]
Some more context, we only store timestamps as the nanoseconds in `int64` from the epoch. This means the earliest (minimum) time we can store is
```
time.Unix(0, -int64(1<<63-1))
-9223372036854775807
1677-09-21 00:12:43.145224193 +0000 UTC
```
and the latest (maximum) time is
```
time.Unix(0, int64(1<<63-1))
9223372036854775807
2262-04-11 23:47:16.854775807 +0000 UTC
```

**Comment by DanielMorsing** [comment]
The main reason we have `now` as a boundary is because we don't want to generate time buckets until the end of time for aggregate queries.

We could probably do something where we check whether it's an aggregate query or not and only bound by now if it is.

**Comment by beckettsean** [comment]
related to #5089

**Comment by beckettsean** [comment]
@pauldix @jwilder I assume we aren't changing the default time boundaries for 1.0, but wanted to get verification of that.

**Comment by jsternberg** [comment]
I don't think we're going to do this so I'm closing this issue.

**Comment by beckettsean** [comment]
@jsternberg I agree we aren't doing this for 1.0, but are we making a conscious choice that we will never do this? It definitely still leads to some confusion for users, so I'd love to have an actual discussion of the tradeoffs.

**Comment by jsternberg** [comment]
I can add this to `TODO.md` if we want to come back to it in the future.

**Comment by beckettsean** [comment]
I do think it's worth making a considered choice on it, rather than the evolved default we have now. Thanks, Jonathan.

**Comment by jsternberg** [comment]
I ran into an issue where I'm not sure what the answer should be. So if you don't specify an end time, we're supposed to implicitly not fill in ending values. But what happens when we have something like this? (assume that all times are in seconds, not nanoseconds)

```
cpu,host=server01 value=1 10
cpu,host=server02 value=2 10
cpu,host=server02 value=3 20

> SELECT mean(value) FROM cpu WHERE time >= 10 GROUP BY host, time(10s)
name: cpu
tags: host=server01
time    value
----    -----
10      1

name: cpu
tags: host=server02
time    value
----    -----
10      2
20      3
```

Should the first one return a row for 20?

**Comment by jsternberg** [comment]
Never mind. We're just going to do what Daniel said and make the end time `now()` when there is a `GROUP BY time(...)` and the end time otherwise. We're overthinking this.
