### ISSUE TITLE
[feature request] Flag or mode in InfluxDB CLI to show field type? (e.g. quotation marks around strings)

### ISSUE THREAD

**Issue by victorhooi** [influxdata/influxdb#4468]
Would it make sense to have a mode/flag in the InfluxDB CLI that showed you what data-type a field was - for example, wrapping strings in quotation marks (")?

I got bitten before (#3240) where I thought I was inserting ints, but they were actually being stored as strings - when I queried in the CLI, there was no way to tell that they were actually strings.

Then in #4415 there seems to be an issue where some timestamps are being reported as a string (e.g. "2015-10-14T20:06:54Z"). In the HTTP API, these are quoted, but not in the CLI.

Obviously this doesn't need to be the default, but may some kind of flag or mode you can explicitly enable?

**Comment by beckettsean** [comment]
related to https://github.com/influxdb/influxdb/issues/3451.

**Comment by mark-rushakoff** [comment]
This should have been addressed by https://github.com/influxdata/influxdb/pull/6592 (`SHOW FIELD KEYS` in 1.0).
