### ISSUE TITLE
[feature request] Go client cluster api

### ISSUE THREAD

**Issue by derailed** [influxdata/influxdb#4478]
Hi,

   Context: InfluxDB clustering situation
 
   Unless I am missing something, the client (0.9.4) can only connect to one url. 
   Can one specify a connection string ie influxdb://h1:p1,h2:p2/database_name and have the client api connect to the next available node? I currently have to front my app client with a proxy in order to connect to the next available node. What is the recommended strategy in this situations?

Thank you!

**Comment by beckettsean** [comment]
Most clustering setups have a load balancer in front of the cluster that distributes write and read requests across the nodes.

**Comment by jsternberg** [comment]
I'm going to close this since I don't believe we have any future plans for it. If you want to add multiconnection client support to our library or a create a third party library for InfluxDB, we would love to hear about it. Thank you.
