### ISSUE TITLE
TestServer_Query_LimitAndOffset is racy

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#4487]
--- FAIL: TestServer_Query_LimitAndOffset (9.62s)
	server_test.go:3946: limit + offset equal to the  number of points with group by time: unexpected results
		query:  select mean(foo) from "limited" WHERE time >= '2009-11-10T23:00:02Z' AND time < '2009-11-10T23:00:06Z' GROUP BY TIME(1s) LIMIT 3 OFFSET 3
		exp:    {"results":[{"series":[{"name":"limited","columns":["time","mean"],"values":[["2009-11-10T23:00:05Z",5]]}]}]}
		actual: {"results":[{"series":[{"name":"limited","columns":["time","mean"],"values":[["2009-11-10T23:00:05Z",null]]}]}]}

https://circle-artifacts.com/gh/influxdb/influxdb/6789/artifacts/2/tmp/circle-artifacts.kTEx1tI/test_logs_race.txt

**Comment by jsternberg** [comment]
This no longer appears to be failing so I'm going to close this.
