### ISSUE TITLE
[0.9.4.2] inconsistent responses on show grants query

### ISSUE THREAD

**Issue by Kindrat** [influxdata/influxdb#4511]
OS: Xubuntu 15.04
InfluxDB : 0.9.4.2
InfluxDB installation: tutum/influxdb:0.9 docker image

Could someone explain me, why responses differs? When user does not have any permissions for db, empty response is returned:
`{"results":[{"series":[{"columns":["database","privilege"]}]}]}`
After granting and revoking privileges, influx returns:
`{"results":[{"series":[{"columns":["database","privilege"],"values":[["DatabaseName","NO PRIVILEGES"]]}]}]}`

And the other thing: privilege requests require `ALL` keyword for all privileges, but responses contain `ALL PRIVILEGES`. `READ` and `WRITE` do not have such mutation in responses.  Isn't it better to have some defined convention?

**Comment by beckettsean** [comment]
Thanks for the report, @Kindrat. I didn't quite follow what you meant by 

> READ and WRITE do not have such mutation in responses.

Can you give some example output that shows this?

**Comment by Kindrat** [comment]
`READ` only response: `{"results":[{"series":[{"columns":["database","privilege"],"values":[["DatabaseName","READ"]]}]}]}`
`WRITE` only response: `{"results":[{"series":[{"columns":["database","privilege"],"values":[["DatabaseName","WRITE"]]}]}]}`

As you see, responses contain single privilege keyword - the same as in request. But when you have ALL permissions, response will additionally include `PRIVILEGES`:
`{"results":[{"series":[{"columns":["database","privilege"],"values":[["DatabaseName","ALL PRIVILEGES"]]}]}]}`

**Comment by beckettsean** [comment]
Gotcha, thanks for the clarification, @Kindrat.

**Comment by babilen** [comment]
A consistent interface that uses `ALL`, `READ`. `WRITE` for `REVOKE`/`GRANT` and `SHOW GRANT` would simplify library design tremendously.

Right now it is rather tricky to implement checks if certain privileges have been granted as one has to normalise the `SHOW GRANT` data:

1. `ALL PRIVILEGES` has to be changed to `ALL`
2. If values contains `NO PRIVILEGES` that entry has to be removed

It would be a lot easier if InfluxDB were to not add ` PRIVILEGES` when showing `ALL` and if the removal of all interfaces would result in the same response you get if no privilege had been granted in the first place.

That means, please ensure that:

1. `{"results":[{"series":[{"columns":["database","privilege"]}]}]}` is returned whenever a user has no privileges, regardless of the fact if it had privileges before
2. `REVOKE`/`GRANT` and `SHOW GRANT` use `ALL`, `READ` and `WRITE` as input and in returned data to clearly and unambiguously refer to these privileges.

Thank you!
