### ISSUE TITLE
load metadata index: read block error -  0.9.4.2

### ISSUE THREAD

**Issue by pfischermx** [influxdata/influxdb#4515]
Hello,

We were using influxdb for the last few days, all of it was perfect, but today we started seeing timeouts (from grafana) when trying to read data from it. After looking at the influxdb I noted that influxdb was crashing/restarting. The following is a copy-paste of the log:

[wal] 2015/10/20 20:12:27 WAL writing to /var/influxdb/wal/metrics/one_day/240
[wal] 2015/10/20 20:12:29 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/10/20 20:12:29 WAL writing to /var/influxdb/wal/metrics/one_day/241
[wal] 2015/10/20 20:12:30 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/10/20 20:12:30 WAL writing to /var/influxdb/wal/metrics/one_day/242
[wal] 2015/10/20 20:12:30 reading WAL files to flush to index
[retention] 2015/10/20 20:12:30 retention policy enforcement terminating
[monitor] 2015/10/20 20:12:30 shutting down monitor system
[monitor] 2015/10/20 20:12:30 terminating storage of statistics
run: open server: open tsdb store: failed to open shard 242: load metadata index: read block: EOF

I'd write the STATS but sadly port 8086 (HTTP port) is not able to start/open because influxdb crashes before.

Our config:

reporting-disabled = true

[meta]
  dir = "/var/influxdb/meta"
  hostname = "influxdb-mon101.flickr.bf1.yahoo.com"
  bind-address = ":8088"
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"
  cluster-tracing = false

[data]
  dir = "/var/influxdb/data"
  engine = "bz1"
  max-wal-size = 104857600
  wal-flush-interval = "10m0s"
  wal-partition-flush-delay = "2s"
  wal-dir = "/var/influxdb/wal"
  wal-logging-enabled = true
  wal-ready-series-size = 30720
  wal-compaction-threshold = 0.5
  wal-max-series-size = 1048576
  wal-flush-cold-interval = "5s"
  wal-partition-size-threshold = 20971520

[cluster]
  force-remote-mapping = false
  write-timeout = "5s"
  shard-writer-timeout = "5s"
  shard-mapper-timeout = "5s"

[retention]
  enabled = true
  check-interval = "30m0s"

[shard-precreation]
  enabled = true
  check-interval = "10m0s"
  advance-period = "30m0s"

[admin]
  enabled = true
  bind-address = ":8083"
  https-enabled = false
  https-certificate = "/conf/influxdb/ssl/influx.pem"

[monitor]
  store-enabled = true
  store-database = "_internal"
  store-interval = "60s"

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/conf/influxdb/ssl/influx.pem"

[collectd]
  enabled = false
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "10s"
  typesdb = "/usr/share/collectd/types.db"

[opentsdb]
  enabled = false
  bind-address = ":4242"
  database = "opentsdb"
  retention-policy = ""
  consistency-level = "one"
  tls-enabled = false
  certificate = "/conf/influxdb/ssl/influx.pem"
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "1s"

[continuous_queries]
  log-enabled = true
  enabled = true
  recompute-previous-n = 2
  recompute-no-older-than = "10m0s"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m0s"

[hinted-handoff]
  enabled = true
  dir = "/var/influxdb/hh"
  max-size = 1073741824
  max-age = "168h0m0s"
  retry-rate-limit = 0
  retry-interval = "1s"

[[udp]]
enabled = true
bind-address = ":4340"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4341"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4342"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4343"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4344"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4345"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4346"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4347"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4348"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4349"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4440"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4441"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4442"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4443"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4444"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4445"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4446"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4447"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4448"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

[[udp]]
enabled = true
bind-address = ":4449"
database = "metrics"
batch-size = 1000
batch-pending = 5
batch-timeout = "1s"

**Comment by otoolep** [comment]
I am curious why you are running so many UDP inputs. Can you enlighten us? It's fully supported, but I am wondering.

**Comment by pfischermx** [comment]
Sure. Our main monitoring is ganglia, so we have a process (it is been running for a while) that reads from our ganglia clusters, gets the "Summary" info of each cluster and injects the data into influxdb. We also do the same for other monitoring systems we have.

We do this via UDP because of the amount of data and it is fairly convenient to "fire and forget" thing that with HTTP is not that easy (unless you do HTTP async calls).

Now, why we have so many ports. This is mostly a 0.6/0.7 thing (not sure if it is still a thing for 0.9), but we do some hashing on the metrics we get from ganglia and other monitoring systems and based on that hash we send the data to a given UDP port. Originally we had a single port but it was dropping too many metrics (guess too much data).

**Comment by otoolep** [comment]
So you're load-balancing via all these ports?

There have been other reports of throughput issues with UDP, but as you can see, the system can ingest the load when spread across ports. You could try increasing the batch size.

Perhaps this is a network settings issue, and with every port in service a new buffer in the kernel is created.

**Comment by otoolep** [comment]
cc @pauldix  on the shard message in the initial comment.

**Comment by pfischermx** [comment]
Yep, load-balancing with hashing. 

One thing that I *just* found out. All our hosts are single-cluster (aka not shared via raft), and all of them are in rotation but only one of them has this error. The rest of the hosts have the same load (sometimes even more load) for reads and writes.

One question:

[wal] 2015/10/20 20:12:30 WAL writing to /var/influxdb/wal/metrics/one_day/242
[wal] 2015/10/20 20:12:30 reading WAL files to flush to index
[retention] 2015/10/20 20:12:30 retention policy enforcement terminating
[monitor] 2015/10/20 20:12:30 shutting down monitor system
[monitor] 2015/10/20 20:12:30 terminating storage of statistics

1. I note that the WAL writing happens almost every second. Is that a reasonable rate for it? I mean, if our configuration says so it will write that often but not quiet sure if that needs some tuning.

**Comment by pfischermx** [comment]
One more host having problems, tho this time I also see a backtrace:

[wal] 2015/10/21 17:32:09 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/10/21 17:32:09 WAL writing to /var/influxdb/wal/_internal/monitor/116
[wal] 2015/10/21 17:32:09 reading WAL files to flush to index
[wal] 2015/10/21 17:32:09 writing 28 series from WAL file /var/influxdb/wal/_internal/monitor/116/01.000001.wal to index
panic: assignment to entry in nil map

goroutine 14 [running]:
github.com/influxdb/influxdb/tsdb.(*Store).CreateShard(0xc82019e000, 0xc820162160, 0x9, 0xc820eb2730, 0x7, 0x74, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/store.go:97 +0x7a1
github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard.func1(0xc82012d100, 0xc820162160, 0x9, 0xc820eb2730, 0x7, 0xc83741e180, 0x1, 0x74, 0x1, 0xc848b60c00, ...)
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x1d5
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:299 +0x1c5

goroutine 1 [sleep]:
time.Sleep(0x4c4b40)
	/home/philip/.gvm/gos/go1.5/src/runtime/time.go:59 +0xf9
github.com/hashicorp/raft.(*shutdownFuture).Error(0xc85e7ec598, 0x0, 0x0)
	/tmp/build/src/github.com/hashicorp/raft/future.go:101 +0x4d
github.com/influxdb/influxdb/meta.(*localRaft).close(0xc82011f450, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/state.go:216 +0xcf
github.com/influxdb/influxdb/meta.(*Store).close(0xc82013e280, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:462 +0x8f
github.com/influxdb/influxdb/meta.(*Store).Close(0xc82013e280, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:430 +0x75
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Close(0xc820174fc0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:422 +0x186
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc820174fc0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:385 +0x55
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc82012c180, 0xc82000a220, 0x2, 0x2, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:114 +0xd7e
main.(*Main).Run(0xc820119f00, 0xc82000a220, 0x2, 0x2, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x67e
main.main()
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 98 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc820174fc0, 0xc8201306c0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:492 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:352 +0xc67

goroutine 43 [runnable]:
sync.runtime_Semacquire(0xc82019e004)
	/home/philip/.gvm/gos/go1.5/src/runtime/sema.go:43 +0x26
sync.(*Mutex).Lock(0xc82019e000)
	/home/philip/.gvm/gos/go1.5/src/sync/mutex.go:82 +0x1c4
sync.(*RWMutex).Lock(0xc82019e000)
	/home/philip/.gvm/gos/go1.5/src/sync/rwmutex.go:82 +0x30
github.com/influxdb/influxdb/tsdb.(*Store).CreateShard(0xc82019e000, 0xc820162160, 0x9, 0xc820eb2730, 0x7, 0x74, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/store.go:68 +0x50
github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard.func1(0xc82012d100, 0xc820162160, 0x9, 0xc820eb2730, 0x7, 0xc82aaca180, 0x1, 0x74, 0x1, 0xc82ae6d700, ...)
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x1d5
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:299 +0x1c5

**Comment by pfischermx** [comment]
One thing, we use:

[data]
  dir = "/var/influxdb/data"
  engine = "bz1"
  max-wal-size = 104857600
  wal-flush-interval = "10m0s"
  wal-partition-flush-delay = "2s"
  wal-dir = "/var/influxdb/wal"
  wal-logging-enabled = true
  wal-ready-series-size = 30720
  wal-compaction-threshold = 0.5
  wal-max-series-size = 1048576
  wal-flush-cold-interval = "5s"
  wal-partition-size-threshold = 20971520

We are using:

2015/10/21 17:42:41 InfluxDB starting, version 0.9.4.2, branch 0.9.4, commit da1b59e7d7764d36786253b2db13b97f42ed4e1d

I'm perfectly fine in re-creating the DBs if there is a better storage engine that we can use, is there another engine that is for use with this version? I'm partially ok in testing another version (0.9+) if it is stable-ish.

**Comment by otoolep** [comment]
The `tsm1` engine is currently available for testing, but there are known issues with it. You can try it and we would be interested in any feedback you have. Our development is now focused on getting the `tsm1` engine to production-quality so bugs in `bz1` are unlikely to be as high-priority right now.

**Comment by pfischermx** [comment]
I assume that tsm1 is available on the nightly builds?

So far for bz1 and our configs, is there any tweaking we could do to avoid this problem (or somehow, reduce it?).

**Comment by otoolep** [comment]
Yes, `tsm1` is available on nightly builds.

**Comment by pfischermx** [comment]
Thanks. I'll let it bake (the nightly one) on our busiest hosts.

**Comment by pfischermx** [comment]
Just wanted to report back that so far the nightly build  v0.9.5-nightly-ff997a7 has been running smoothly. It stopped on one of the hosts but that is because I forgot to set the right ulimit so it ran out of open files. On the other host that has the right ulimit value it has been doing great. I'll let it bake another day and if no issues are found I'll upgrade all our hosts.

Thanks!

Btw, any ETA on when 0.9.5 will be stable?

**Comment by otoolep** [comment]
Thanks for the feedback @pfischermx -- is this with the `tsm1` engine? If so, please remember that engine is still in development and you may have to blow away your data between upgrades until we address all the issues.

**Comment by pfischermx** [comment]
Yep. The hosts running the nightly build are with tsm1. I'm fine in wiping the data since it populates pretty fast.
