### ISSUE TITLE
Conversion utility to go from b1/bz1 to tsm1

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#4517]
Users with data written using the `b1` or `bz1` engine will want a utility to migrate that data to the new `tsm1` engine.

**Comment by beckettsean** [comment]
@dgnorton a few thoughts:

- it would be great if the migration can be incremental, not all or nothing. For example, declare a time range for the migration, or give shard IDs from the path names. That way users can control the load on their systems, or if it has to happen offline, space out the downtime if they wish. They can also minimize the disk scratch space needed if shards migrate individually.
- presumably instances will need to be already using the `tsm1` engine in the config before migrating old shards?
- `SHOW SHARDS` must show the engine type or there's no good way for users to be certain things are working. https://github.com/influxdb/influxdb/issues/4535

**Comment by vladlopes** [comment]
I developed this [migration tool](https://github.com/vladlopes/influxdb-migrate) a while back and, not sure there would be a migration tool this time, included the migration from `b1` and `bz1` engine. On version 0.9.2 the shards were changed to have a `format` field to indicate the engine, although, by this version, it was always `b1`. So, to migrate from 0.9.2-4, you would pass to the tool `-fromversion=092`.

I used this tool, with the limitations stated on the project page, in production to migrate from all the versions it implements.

It is a all or nothing migration. If you run it twice it should only update the already inserted points.

You can run It only display on stdout the points that would be written for a cold test before the real migration.

Maybe this can help someone.

**Comment by srikara** [comment]
+1

**Comment by jwilder** [comment]
Fixed by #5226
