### ISSUE TITLE
Inconsistent time duration in config file

### ISSUE THREAD

**Issue by daviesalex** [influxdata/influxdb#4527]
Within the config file, som entries use toml.Duration and some time.Duration. This means that a value like "2m" isnt valid, and a int (120) has to be passed. This feels like something that should be cosnistent.

e,g.
```
        WALPartitionFlushDelay toml.Duration `toml:"wal-partition-flush-delay"`
```

vs
```
        IndexCompactionAge time.Duration `toml:"index-compaction-age"`
```

Other examples we hit that dont take a duration (there may be others) are index-min-compaction-interval and index-compaction-full-age

**Comment by jsternberg** [comment]
I don't see any configuration values that do this anymore. I'm going to close this, but if you can find any configuration options that still use `time.Duration` instead of `toml.Duration`, please comment here so I can reopen the issue. Thanks.
