### ISSUE TITLE
[feature request] SHOW TAG VALUES should accept regex

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4532]
Right now the syntax is `SHOW TAG VALUES WITH KEY IN (<tag_key1>, <tag_key2>,...)` which is not congruent with our other queries and doesn't support regular expressions.

How about `SHOW TAG VALUES WHERE KEY [=,=~,!=,!~] <tag_key_regex>`

**Comment by jsternberg** [comment]
Should we also modify this to support `!=` and `!~`? It looks like the current code doesn't support any operator except `=`.

**Comment by beckettsean** [comment]
@jsternberg I would say yes, this should support the full equals, not-equals, matches, and not-matches operators, just like the `WHERE` clause. That's what most users would expect.

Is there a tradeoff, other than more complex code, for supporting all of them? Does it impact the query speed?

**Comment by jsternberg** [comment]
It shouldn't affect the query speed although there's another ticket for improving `SHOW TAG VALUES` performance. The actual code that executes the query already executes the expression. This would be completely about how we parse the syntax. Should we allow this?

```
SHOW TAG VALUES WITH KEY = 'region' OR key = 'host'
```

I would lean towards no personally.

**Comment by gunnaraasen** [comment]
I agree support for `OR` or `AND` doesn't really make sense in this context. A single binary expression should be sufficient for most cases.

Filtering tag values with a `WHERE` clause could be useful, e.g.

```
SHOW TAG VALUES WITH KEY = 'region' WHERE customer = 'bob'
```

Although I imagine that may be significantly harder to implement and similar results could be obtained by running a `SELECT value FROM /.*/ WHERE customer = 'bob' GROUP BY region limit 1`.

**Comment by beckettsean** [comment]
@jsternberg any limitations will end up frustrating someone, but since the workaround for that is to just run two queries and consolidate the results I can live with `OR` being illegal in the `WITH` clause. In fact, that could be stated as regex: `SHOW TAG VALUES WITH KEY =~ /['region','host]/`.

I would be okay with `SHOW TAG VALUES` only allowing a single operator, and then using regex most problems can still be solved. We'll see if any of the edge or corner cases are significant.

**Comment by jsternberg** [comment]
The PR has been modified to support all of those now. In the future, we might want to support `NOT IN`, but I don't think it's a priority right now. I also tried to model things so it would be easier to include set support in the future for normal queries.
