### ISSUE TITLE
[0.9.5-nightly] very long string field value accepted for write, but read panics the database

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4556]
Also happens with 0.9.4.1.

I am doing boundary testing and submitted a single field with a 64KB long string.

`curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary @string.txt` where `string.txt` contains `fieldlong value="<a string 65531 bytes long>"`

https://gist.github.com/beckettsean/507d113f13fdf5f92937 has the 65531 byte long string as a valid line protocol statement.

When the string is 65531 bytes in length or fewer, the insert succeeds and the results can be queried. 

If the string is longer than 65531 bytes it will still be accepted on write:

```
curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary @string.txt 
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Request-Id: 1da6f331-79bb-11e5-8032-000000000000
X-Influxdb-Version: 0.9.4.1
Date: Fri, 23 Oct 2015 19:20:26 GMT
```

but any queries against the point cause `panic: runtime error: slice bounds out of range`

```
query] 2015/10/23 15:09:26 SELECT * FROM "mydb"."default".fieldlong
panic: runtime error: slice bounds out of range

goroutine 102 [running]:
github.com/influxdb/influxdb/tsdb.(*FieldCodec).DecodeByID(0xc820190520, 0xc82052e701, 0xc82020400c, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/shard.go:735 +0xa31
github.com/influxdb/influxdb/tsdb.(*FieldCodec).DecodeByName(0xc820190520, 0xc8201904d0, 0x5, 0xc82020400c, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/shard.go:757 +0x13c
github.com/influxdb/influxdb/tsdb/engine/wal.DecodeKeyValue(0xc820191bf0, 0x1, 0x1, 0xc820190520, 0xc820204000, 0x8, 0x1000c, 0xc82020400c, 0x10000, 0x10000, ...)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1600 +0x1b9
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Cursor).read(0xc820285880, 0xc820143500, 0x0, 0x0)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:817 +0x229
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Cursor).SeekTo(0xc820285880, 0x0, 0xffffffffffffffff, 0x0, 0x0)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:699 +0x2b9
github.com/influxdb/influxdb/tsdb.(*multiCursor).SeekTo(0xc82050fe00, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/cursor.go:46 +0x16c
github.com/influxdb/influxdb/tsdb.(*TagsCursor).SeekTo(0xc820290dc0, 0x0, 0x10ca938, 0x0, 0x0)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/cursor.go:364 +0x85
github.com/influxdb/influxdb/tsdb.(*TagSetCursor).Init(0xc820409e80, 0x0)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/cursor.go:192 +0xbd
github.com/influxdb/influxdb/tsdb.(*RawMapper).openMeasurement(0xc82007e820, 0xc8205293b0, 0x0, 0x0)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/raw.go:879 +0x6f6
github.com/influxdb/influxdb/tsdb.(*RawMapper).Open(0xc82007e820, 0x0, 0x0)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/raw.go:824 +0x43d
github.com/influxdb/influxdb/tsdb.(*RawExecutor).execute(0xc82052f110, 0xc820492ba0)
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/raw.go:69 +0xeb
created by github.com/influxdb/influxdb/tsdb.(*RawExecutor).Execute
        /tmp/tmp.kvLu2bJaVO/src/github.com/influxdb/influxdb/tsdb/raw.go:59 +0x5d

```

On 0.9.5-nightly, field values that are longer than 65535 bytes are still accepted for writes, but the query returns an empty field rather than panicking the database:

```
http] 2015/10/23 15:22:22 127.0.0.1 - - [23/Oct/2015:15:22:22 -0400] POST /write?db=mydb HTTP/1.1 204 0 - curl/7.35.0 626ff362-79bb-11e5-8003-000000000000 59.923651ms
[query] 2015/10/23 15:22:43 SELECT * FROM "mydb"."default".fieldlong
[http] 2015/10/23 15:22:43 127.0.0.1 - - [23/Oct/2015:15:22:43 -0400] GET /query?db=mydb&epoch=ns&q=select+%2A+from+fieldlong HTTP/1.1 200 115 - InfluxDBShell/0.9.5-nightly-827c513 6f20e073-79bb-11e5-8004-000000000000 21.45606ms


> select * from fieldlong
name: fieldlong
---------------
time			value
1445628142242760741	

```
Fields with length between 65531 and 65535 bytes are accepted as writes by 0.9.5-nightly but queries cause the same stack trace as above.

In summary:

Both 0.9.4.1 and 0.9.5-nightly accept writes and return `204` for fields of lengths up to and exceeding 65531 bytes (64KB is 65535), including field values that are substantially larger than 65535 bytes (and thus should not succeed as writes.)

For 0.9.4.1, queries for points of any field value length above 65531 panic the db with `slice bounds out of range`.

For 0.9.5-nightly, queries for points with a field value length above 65535 return an empty value for the field

```
 curl -iG 'http://localhost:8086/query?db=mydb' --data-urlencode 'q=select * from fieldlong'; echo
HTTP/1.1 200 OK
Content-Type: application/json
Request-Id: de18f5e4-79bc-11e5-8005-000000000000
X-Influxdb-Version: 0.9.5-nightly-827c513
Date: Fri, 23 Oct 2015 19:32:59 GMT
Content-Length: 122

{"results":[{"series":[{"name":"fieldlong","columns":["time","value"],"values":[["2015-10-23T19:28:32.32629434Z",""]]}]}]}
```

For both versions, queries against points with fields of 65532, 65533, 65534, or 65535 bytes panic the database with the `slice bounds out of range` stack trace.

Two issues:
1. we should reject writes for points with a field that exceeds our maximum length
2. we should determine if our maximum field value length is `64KB` or `64KB - 4 bytes` and document as such

TODO: test other strings with long values, mostly the identifiers.

**Comment by pauldix** [comment]
The TSM1 storage engine won't have this limitation so I'm not sure we want to put it in. Will be resolved in 0.9.5 when TSM1 becomes the storage engine that is default.

**Comment by jsternberg** [comment]
@beckettsean I'm having a hard time reproducing the panic. I can reproduce the empty value. Here's a list of what I tried.

```
$ vagrant init ubuntu/trusty64
$ vagrant up
$ vagrant ssh
$ wget https://s3.amazonaws.com/influxdb/influxdb_0.9.4.1_amd64.deb
$ sudo dpkg -i influxdb_0.9.4.1_amd64.deb
$ sudo service influxdb start
$ curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
# download the attached gist and modify so the string is greater than 65535 characters
$ curl -i -XPOST http://localhost:8086/write?db=mydb --data-binary @string.txt
$ curl -G http://localhost:8086/query?db=mydb --data-urlencode "q=SELECT * FROM fieldlong"
{"results":[{"series":[{"name":"fieldlong","columns":["time","value"],"values":[["2015-12-16T20:37:16Z",""]]}]}]}
```

This should panic with the version I downloaded, but I seem to get the 0.9.5 nightly behavior you described instead. Can you try this on your machine again to see if it still happens?

**Comment by beckettsean** [comment]
I no longer have an 0.9.4 machine. Given that it was `bz1` I kinda don't care about it, as long as it behaves well in `tsm`

**Comment by beckettsean** [comment]
closing, as this was specific to `bz1`
