### ISSUE TITLE
feature request: white listing

### ISSUE THREAD

**Issue by roobert** [influxdata/influxdb#4568]
Hi,

I would be interested in contributing a feature to influxdb: white listing. I have a few questions I was hoping could be answered before starting to implement such a feature:
1. is this a feature that has been considered?
2. has an equivalent or similar feature been considered that would obviate/supersede this feature?
3. I haven't looked too much at the code yet but I'm hoping a white list feature would be listener agnostic
4. How should discarded metrics be stored in the stats tables?

My use case is that everyone read the Etsy article on [measure anything, measure everything](https://codeascraft.com/2011/02/15/measure-anything-measure-everything/) and went hog-wild with throwing metrics at our time series databases which means we end up with a load of data that no one ever looks at that consumes a lot of disk resource. We would prefer to be more selective in what we store.

Thanks,

**Comment by otoolep** [comment]
We have not discussed the feature, but it would mean that the whitelist would be comprised of a <measurement,tag key-values pairs> basis. This information would need to be consulted whenever a point was received by the system. This may, or may not, have a significant impact on performance. Any change should be accompanied by benchmarking test cases.

This information would, either need to be supplied either a config file underneath each node, or in Raft consensus. I think the latter may be preferable.

I would caution you about the approach of discarding metrics. One never knows ahead of time which metric might be needed, and it may prevent ad-hoc analysis.

**Comment by aadrian** [comment]
What about finer grained data retention policy instead?
Data that you describe as NOT-"white listed" to have a much shorter retention policy? This way one still gets the chance to analyze it if it's potentially interesting.

**Comment by otoolep** [comment]
@aadrian - 0.9 has specifically moved away from determining retention policy on metric name. 0.8 did that and it was really awkward to use in practise.
