### ISSUE TITLE
One of the nodes in the cluster not coming up after restarting

### ISSUE THREAD

**Issue by priyadarsh** [influxdata/influxdb#4573]
I have restarted one of the 3 nodes in the cluster set up and after restarting one of the nodes I see the below log for a while and the server dies.

Build : 0.9.5-nightly-827c513

[monitor] 2015/10/26 17:53:57 failed to store statistics: timeout
[monitor] 2015/10/26 17:54:07 failed to store statistics: timeout
[monitor] 2015/10/26 17:54:17 failed to store statistics: timeout
[monitor] 2015/10/26 17:54:27 failed to store statistics: timeout
[monitor] 2015/10/26 17:54:37 failed to store statistics: timeout
[monitor] 2015/10/26 17:54:47 failed to store statistics: timeout
[monitor] 2015/10/26 17:54:57 failed to store statistics: timeout
[monitor] 2015/10/26 17:55:07 failed to store statistics: timeout
[monitor] 2015/10/26 17:55:17 failed to store statistics: timeout
[monitor] 2015/10/26 17:55:27 failed to store statistics: timeout
[monitor] 2015/10/26 17:55:37 failed to store statistics: timeout
[monitor] 2015/10/26 17:55:47 failed to store statistics: timeout
[monitor] 2015/10/26 17:55:57 failed to store statistics: timeout
[monitor] 2015/10/26 17:56:07 failed to store statistics: timeout
[monitor] 2015/10/26 17:56:17 failed to store statistics: timeout
[monitor] 2015/10/26 17:56:27 failed to store statistics: timeout
[monitor] 2015/10/26 17:56:37 failed to store statistics: timeout
[monitor] 2015/10/26 17:56:47 failed to store statistics: timeout
[monitor] 2015/10/26 17:57:03 failed to store statistics: timeout
[monitor] 2015/10/26 17:57:08 failed to store statistics: timeout
[tsm1wal] 2015/10/26 17:57:14 failed to flush to index: snappy: corrupt input
[registration] 2015/10/26 17:57:14 registration service terminating
[retention] 2015/10/26 17:57:14 retention policy enforcement terminating
[monitor] 2015/10/26 17:57:14 shutting down monitor system
[monitor] 2015/10/26 17:57:14 terminating storage of statistics
[subscriber] 2015/10/26 17:57:14 closed service
run: open server: open tsdb store: failed to open shard 5: open engine: snappy: corrupt input

And in the other 2 nodes, I see the below logs(masked IPs). The  I am trying to restart is on XXX.XX.11.54

handoff] 2015/10/26 18:03:57 remote write failed: read message type: read tcp XXX.XX.11.55:58491->XXX.XX.11.54:8088: i/o timeout
[monitor] 2015/10/26 18:03:59 failed to store statistics: timeout
[handoff] 2015/10/26 18:04:03 remote write failed: read message type: read tcp XXX.XX.11.55:58496->XXX.XX.11.54:8088: i/o timeout
[handoff] 2015/10/26 18:04:09 remote write failed: read message type: read tcp XXX.XX.11.55:58498->XXX.XX.11.54:8088: i/o timeout
[monitor] 2015/10/26 18:04:09 failed to store statistics: timeout
[handoff] 2015/10/26 18:04:15 remote write failed: read message type: read tcp XXX.XX.11.55:58501->XXX.XX.11.54:8088: i/o timeout
[monitor] 2015/10/26 18:04:19 failed to store statistics: timeout
[handoff] 2015/10/26 18:04:21 remote write failed: read message type: read tcp XXX.XX.11.55:58504->XXX.XX.11.54:8088: i/o timeout
[handoff] 2015/10/26 18:04:27 remote write failed: read message type: read tcp XXX.XX.11.55:58506->XXX.XX.11.54:8088: i/o timeout
[

handoff] 2015/10/26 18:04:15 remote write failed: read message type: read tcp XXX.XX.11.56:52218->XXX.XX.11.54:8088: i/o timeout
[handoff] 2015/10/26 18:04:21 remote write failed: read message type: read tcp XXX.XX.11.56:52221->XXX.XX.11.54:8088: i/o timeout
[monitor] 2015/10/26 18:04:21 failed to store statistics: timeout
[handoff] 2015/10/26 18:04:27 remote write failed: read message type: read tcp XXX.XX.11.56:52225->XXX.XX.11.54:8088: i/o timeout
[monitor] 2015/10/26 18:04:31 failed to store statistics: timeout
[handoff] 2015/10/26 18:04:33 remote write failed: read message type: read tcp XXX.XX.11.56:52228->XXX.XX.11.54:8088: i/o timeout
[handoff] 2015/10/26 18:04:39 remote write failed: read message type: read tcp XXX.XX.11.56:52230->XXX.XX.11.54:8088: i/o timeout
[monitor] 2015/10/26 18:04:41 failed to store statistics: timeout
[handoff] 2015/10/26 18:04:45 remote write failed: read message type: read tcp XXX.XX.11.56:52233->XXX.XX.11.54:8088: i/o timeout

**Comment by priyadarsh** [comment]
I restarted all the nodes and now all the nodes are not coming up and throwing the same error.

**Comment by otoolep** [comment]
cc @benbjohnson @pauldix  -- can you guys comment on the snappy error?

**Comment by pauldix** [comment]
Sounds like one of the WAL files had a partial write. Maybe the server got killed in the middle of a write? Removing the WAL files will let you bring it back up, but it should recover from a corrupt WAL file without failing out.

What does the directory for shard 5 look like?

**Comment by priyadarsh** [comment]
@pauldix I tried restarting after clearing hh folder. Then I have cleared all the folders and started the cluster afresh. I won't be able to provide the mentioned info. If I encounter this error again, what else you need to further debug this issue?

**Comment by pauldix** [comment]
Ideally a zip of your entire influxdb directory including `meta`, `data`, and `wal` directories.

**Comment by beckettsean** [comment]
@priyadarsh if you encounter the issue again, please upload the gzip to http://cwok.me/cu/gh4573

**Comment by priyadarsh** [comment]
@beckettsean sure

**Comment by jwilder** [comment]
Nothing to do here.  Closing.
