### ISSUE TITLE
CQ current interval start time calculated wrong

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#4574]
When a CQ is run, the start time of the current interval is:
```
interval, err := cq.q.GroupByInterval()
startTime := now.Round(interval)
```
Half way through an interval, the current interval gets rounded up (into the future) to the next interval.  It should use `now.Truncate(interval)` instead.

**Comment by li-ang** [comment]
I agree with dgnorton.

**Comment by dgnorton** [comment]
@li-ang truncating gives a different result because it will align with an interval boundary.  `now - interval` shifts the starting point so that it's not in the future but it may not be aligned with an interval boundary.
