### ISSUE TITLE
[feature request] Rolling Continuous Query Feature

### ISSUE THREAD

**Issue by ericjmiller** [influxdata/influxdb#4575]
Is there a feature that allows Continuous Queries to be Grouped By a time that is different than how often the downsample is queried.

For example, can I 'Group by' 30 second intervals every 5 seconds?  So every 5 seconds, a 30 second 'Group by' is used?

**Comment by beckettsean** [comment]
Currently, no.

**Comment by beckettsean** [comment]
closing in favor of more detailed newer issue: https://github.com/influxdata/influxdb/issues/6921
