### ISSUE TITLE
Server no longer writes locally after a restart in a cluster

### ISSUE THREAD

**Issue by khalaan** [influxdata/influxdb#4578]
After forceful restarting the "master" node of a cluster that node no longer writes locally. No logs indicate error and the slaves to that cluster are still receiving and writing data to their data storage locations. Querying for new data on the slaves results in the expected metrics where as querying on the master results in no results found for new entries after restart.

**Comment by beckettsean** [comment]
Run `SHOW SERVERS` from each node and see if all three agree. The simplest explanation (although unlikely) is that the node did not join the cluster on restart.

Is hinted handoff enabled in the config for each node?

**Comment by beckettsean** [comment]
Also, what version of InfluxDB are you running?

**Comment by jsternberg** [comment]
Clustering is no longer supported in the open source version and there has been no response on this issue in a long time, so I'm going to close this.
