### ISSUE TITLE
query parser should throw error on nested functions with tag arguments

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4618]
`userId` is a tag, not a field. As such, the following queries properly fail with errors.

```
> select distinct(userId) from "event.btn.click02" 
ERR: statement must have at least one field in select clause
> select count(userId) from "event.btn.click02" 
ERR: statement must have at least one field in select clause
```

However, the nested `COUNT(DISTINCT(userId))` query does not throw a parser error and incorrectly returns zero.

```
> select count(distinct(userId)) from "event.btn.click02" 
name: event.btn.click02
-----------------------
time            count
1970-01-01T00:00:00Z    0
```

**Comment by emitle** [comment]
I think there is no need for `count(distinct(TagName))` to return a parse error. 
It seems that right now there is no practical way to count the unique number of a certain tag, and `count(distinct(TagName))` happens to be able to fit that role.

**Comment by beckettsean** [comment]
@emitle if it worked, `COUNT(DISTINCT(tagKey))` would be an excellent way to count the distinct tags on a measurement.

However, tags are not valid arguments to functions, so that should throw a parser error, just as `COUNT(tagKey)` and `DISTINCT(tagKey)` do.

Once https://github.com/influxdb/influxdb/issues/3880 is implemented the parser error would be removed.

**Comment by jsternberg** [comment]
We might be able to do this finally with the addition of the casting syntax PR. I'll keep this in mind for post-1.0.
