### ISSUE TITLE
[feature request] internal query ID for log correlation

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4637]
When there are thousands of queries in a log it is very tough to correlate the `[query]` submission with the `[http]` query return. An internal ID would be useful for matching the two, and looking for queries that never returned.

**Comment by corylanou** [comment]
We already have `request_id` in the system, we just don't pass it around.  Every time a query get's issued, we manufacture a `uuid` for it.  This _should_ get passed to each call it makes.  It just hasn't been implemented yet.  Then when you consolidate logs across nodes, you can quickly see which node's participated in that actual query for debugging.

Here is the line that manufactures the `uuid`:

https://github.com/influxdb/influxdb/blob/master/services/httpd/handler.go#L804

**Comment by corylanou** [comment]
It get's logged here as well: https://github.com/influxdb/influxdb/blob/master/services/httpd/response_logger.go#L104

**Comment by beckettsean** [comment]
@corylanou I don't see any evidence of that line in the logs. It might be in the HTTP header, but we don't log those.

**Comment by corylanou** [comment]
It does log.  Here is a line from my log:

```
[http] 2015/11/02 14:50:06 127.0.0.1 - - [02/Nov/2015:14:50:06 -0600] GET /query?db=monitor&epoch=ns&q=select+%2A+from+monitor HTTP/1.1 200 40 - InfluxDBShell/0.9 4c270eac-81a3-11e5-8004-000000000000 2.722988ms
```

`4c270eac-81a3-11e5-8004-000000000000` is the `Request-Id`

**Comment by beckettsean** [comment]
Thanks for the clarification, @corylanou. 

The header UUID doesn't correlate to the initial `[query]` entry, so there's no way to find orphaned queries except by matching the actual query.

```
[query] 2015/11/02 13:41:17 SHOW DATABASES
[http] 2015/11/02 13:41:17 ::1 - - [02/Nov/2015:13:41:17 -0800] GET /query?db=mydb&q=show+databases HTTP/1.1 200 111 - InfluxDBShell/0.9.4.1 72d46b3d-81aa-11e5-bbfa-000000000000 1.47088ms
```

My logs are clean because there's only ad hoc load on this server, so I know those two are the submission and the return of the same query. In a normal prod instance, however, there are dozens of `[query]` logs with interleaved `[http]` returns, and no good way to verify they match up.

**Comment by corylanou** [comment]
That is part of what I was stating isn't `wired up`.  Everything to do with that statement executing should log with the `Request-Id`.  Otherwise, I agree, it is impossible to track through the log.
