### ISSUE TITLE
[0.9.4.2] CPU 100%

### ISSUE THREAD

**Issue by clanstyles** [influxdata/influxdb#4639]
I have a 3 node cluster. Each are m4.Large on Amazon. the CPU is 100%. 

Each request I batch write all analytics when the request closes. There are usually 2-3 types of analytics I log.

```
tags := map[string]string{
		"id":    imp.ID,
		"country":   imp.IPAddress.Country,
		"ipaddress": imp.IPAddress.Address,
		"os": imp.OS,
	}

	fields := map[string]interface{}{
		"value": 1,
	}

	batchPoints.AddPoint(client.NewPoint(
		"impressions",
		tags,
		fields,
		time.Now().UTC(),
	))
```

Query times are ~1 second (through the web interface). To load balance the requests, I've hooked up elastic load balancer to all the nodes and allow them to rotate that way (not sure if this causes issues?).

I'm running influx 0.9.4.

**Comment by beckettsean** [comment]
How many batches are you writing per second? 
How many points per batch?
What queries are running and how many?

**Comment by ClanStyles** [comment]
I'm running no queries. Only writing.
A batch consists of either 1 or two points. Initially a flood of two points.
I can't tell how many I'm writing per second. We see an average of 2M requests a day. It's spread out pretty evenly (from the CDN). This does NOT mean all these hit the web server. At this moment, I can't tell because the latency is causing timeouts. I'll be removing the influx stats recording to see if I can track requests via ELB and go from there.

If I can provide anymore data, please let me know.

**Comment by jackzampolin** [comment]
@ClanStyles What volume are you using to back the m4.large? A SSD?

**Comment by ClanStyles** [comment]
Took influxdb out of rotation, no requests, still 100% CPU.

**Comment by beckettsean** [comment]
@ClanStyles if you are writing a million points per day in batches of 1 or 2 points each, that's tens of thousands of http requests per second to InfluxDB. That's too much HTTP overhead for the server.

Batch the writes into 100+ points per batch, ideally 5k points or so, for best performance. Alternately use UDP for the writes.

The high CPU load is likely because the system is trying to drain the WAL (write ahead log), which can accept points faster than the database can persist them to the permanent storage engine.

**Comment by ClanStyles** [comment]
@beckettsean at this moment, there are no writes happening the CPU is still idle at 100%. The current issue with batching points is the need to write a batch writer.

Since Influx's client doesn't support multiple go-routines, this instantly limits us to a "per context" write. In the event that the server is shutting down, you'll need to gracefully write any remaining logs. There are various steps that will have to be implemented that I felt the influx client should do, and doesn't.

I monitored the influx disk IO on the drives, and it's next to nothing.

Watching the logs, I don't understand how this is even possible:

```
[monitor] 2015/11/03 01:33:59 failed to store statistics: timeout
[wal] 2015/11/03 01:33:59 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:34:02 write to index of partition 1 took 3.197536498s
[wal] 2015/11/03 01:34:10 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:34:10 write to index of partition 1 took 5.159944ms
[wal] 2015/11/03 01:34:19 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:34:19 write to index of partition 1 took 3.162219ms
[wal] 2015/11/03 01:34:27 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:34:27 write to index of partition 1 took 2.518651ms
[wal] 2015/11/03 01:34:39 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:34:40 write to index of partition 1 took 1.605196271s
[wal] 2015/11/03 01:34:54 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:34:56 write to index of partition 1 took 747.790113ms
[monitor] 2015/11/03 01:35:01 failed to store statistics: timeout
[wal] 2015/11/03 01:35:02 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:35:04 write to index of partition 1 took 1.579186636s
[wal] 2015/11/03 01:35:09 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:35:10 write to index of partition 1 took 1.566484512s
[wal] 2015/11/03 01:35:19 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:35:22 write to index of partition 1 took 1.638281477s
[wal] 2015/11/03 01:35:30 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:35:30 write to index of partition 1 took 2.431985ms
[wal] 2015/11/03 01:35:41 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:35:41 write to index of partition 1 took 2.17642ms
[wal] 2015/11/03 01:35:48 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:35:51 write to index of partition 1 took 2.540024959s
[wal] 2015/11/03 01:35:59 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:36:01 write to index of partition 1 took 1.58264594s
[wal] 2015/11/03 01:36:06 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:36:11 write to index of partition 1 took 5.009611341s
[wal] 2015/11/03 01:36:18 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:36:19 write to index of partition 1 took 1.557241405s
[wal] 2015/11/03 01:36:30 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:36:30 write to index of partition 1 took 2.475459ms
[wal] 2015/11/03 01:36:36 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:36:40 write to index of partition 1 took 3.262602201s
[wal] 2015/11/03 01:36:48 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:36:53 write to index of partition 1 took 5.099431167s
[wal] 2015/11/03 01:36:59 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
[wal] 2015/11/03 01:37:02 write to index of partition 1 took 3.122957098s
[monitor] 2015/11/03 01:37:07 failed to store statistics: timeout
[wal] 2015/11/03 01:37:07 Flush due to idle. Flushing 3 series with 3 points and 195 bytes from partition 1
```

**Comment by otoolep** [comment]
That looks like the internal stats being written to storage.

We need to surpress those log messages as they are too verbose in default mode.

Are you running InfluxDB as a service?

**Comment by ClanStyles** [comment]
Yes on the standard AMI from Amazon following your guide.

**Comment by otoolep** [comment]
At this stage it's pretty difficult to work out why, so a restart is probably best. However, we can run with profiling enabled to see if it re-occurs.

https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#profiling

Add `-cpuprofile /tmp/influxd.prof` to `/etc/default/influxdb`, which will enable profiling data to that file. So if it hits 100% we'd like that file, plus you need to tell us exactly which version you are running.

**Comment by ClanStyles** [comment]
I'll do that. 

Just to update, we're seeing about 1200 /requests a second we want to record stats for.

**Comment by otoolep** [comment]
Any continuous queries in effect?

**Comment by ClanStyles** [comment]
No, at the time it started to write, I didn't see more than 6 requests through ELB before the system went 100% CPU and died.

**Comment by ClanStyles** [comment]
So after the restart, it seems like influx isn't spiking anymore on any of the 3 nodes.

**Comment by otoolep** [comment]
OK, thanks @ClanStyles -- if you are up for it, we can run with profiling enabled in case it re-occurs.

**Comment by ClanStyles** [comment]
Ah I think I figured out a trigger. Try to delete a large amount of data -> CPU spikes -> http times out.

**Comment by otoolep** [comment]
Can you show use your query?

**Comment by ClanStyles** [comment]
DELETE FROM foo WHERE time > '2014-06-30' 
since drop series doesn't seem to work.

I'm trying to truncate data from the table.

**Comment by ClanStyles** [comment]
Now the daemon is crashing. How do I upload the prof file?

**Comment by beckettsean** [comment]
`DELETE` is not a valid query. You're hitting a combination of that not being valid https://github.com/influxdb/influxdb/issues/1647 and the error not being thrown https://github.com/influxdb/influxdb/issues/4404. 

I will escalate #4404 for the next release, I honestly forgot we hadn't fixed that.

`DROP SERIES` is a valid command and will cause high load for a while. InfluxDB [assumes deletes are infrequent](https://influxdb.com/blog/2015/06/03/InfluxDB_clustering_design.html) and usually in bulk, e.g. `DROP MEASUREMENT` or retention policy expiration. `DROP SERIES` is not as performant.

**Comment by jwilder** [comment]
Closing this since it's related to the `b1` storage engine which has been replaced by the `tsm` engine in `0.10`.
