### ISSUE TITLE
Add log messages for shard lifecycle

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#4640]
Every shard needs to be traceable in the system -- when it came into existence, and when it is deleted.

**Comment by otoolep** [comment]
Shards are created by the code in the `meta` package. They are also deleted there, in response to retention policy enforcement. We need comprehensive, consistent, logging added for each, so we can trace the lifecycle of every shard. Log messages should include the shard ID.

**Comment by gianarb** [comment]
@otoolep about this quote

>  I think it might be best to hold off on this for now. Obviously this is not as simple as I thought, and need to think a bit more about how best to track shard lifecycles.

Would you change the difficult label? :construction_worker:
