### ISSUE TITLE
HH should correctly handle writes to dropped shards

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#4673]
It is possible that HH data contains writes for shards that have been subsequently dropped. The system should handle this condition sensible.

**Comment by jwilder** [comment]
It does currently handle this case on the receiving side.  This can waste resources when a lot of queued writes are still transferred over the network and we could have determined that they would have failed before sending them.

The HH senders should drop the writes before sending them to multiple receivers if the shard no longer exists.

**Comment by otoolep** [comment]
Yes, exactly my thinking. It is handled, but it is not optimal. Something like you suggest is what I have in mind.

**Comment by jsternberg** [comment]
Hinted handoff is no longer in the open source version now that clustering has been removed.
