### ISSUE TITLE
[0.9.4.2] derivative is broken with order by desc

### ISSUE THREAD

**Issue by poelzi** [influxdata/influxdb#4675]
When using order by, the derivative function gives strange results:

```
SELECT DERIVATIVE(value) from net_bytes_recv where host='influxdb' and interface='eth0'  order by desc

2015-11-05T15:47:20Z    0
2015-11-05T15:47:10Z    0
2015-11-05T15:47:00Z    0
2015-11-05T15:46:50Z    0
2015-11-05T15:46:40Z    0
2015-11-05T15:46:30Z    0
2015-11-05T15:38:20Z    0
```

vs

```
SELECT DERIVATIVE(value) from net_bytes_recv where host='influxdb' and interface='eth0'  order by asc

ame: net_bytes_recv
--------------------
time                    derivative
2015-11-05T15:38:30Z    146904.2
2015-11-05T15:38:40Z    151736.9
2015-11-05T15:38:50Z    127525.5
2015-11-05T15:39:00Z    124495.7
2015-11-05T15:39:10Z    143187.3
2015-11-05T15:39:20Z    151087
[...]
```

**Comment by jackzampolin** [comment]
@poelzi What Influx version are you running?

**Comment by poelzi** [comment]
Connected to http://localhost:8086 version 0.9.4.2
InfluxDB shell 0.9.4.2

**Comment by jackzampolin** [comment]
@poelzi `derivative( field_key, [unit] )` returns the rate of change for the values in a single [field](https://influxdb.com/docs/v0.9/concepts/glossary.html#field) in a [series](https://influxdb.com/docs/v0.9/concepts/glossary.html#series). InfluxDB calculates the difference between chronological non-NAN field values and converts those results into the rate of change per unit. The unit argument is optional and, if not specified, defaults to one second (`1s`). 

What does the the data look like between `2015-11-05T15:47:20Z` and `2015-11-05T15:38:20Z `?

**Comment by poelzi** [comment]
It seems that it calculates the change after sorting which messes up the values. I would expect the results just in opposite direction so limit can be used for the last n values and I think thats the user expected behaviour.

**Comment by jackzampolin** [comment]
@poelzi We have documentation coming out to explain the derivative behavior soon. While this is expected behavior, it is not what most users expect.

**Comment by beckettsean** [comment]
@jackzampolin I tend to agree with @poelzi on this. `ORDER BY` should operate on the outputs, not the inputs. With or without documentation it is a bug if `ORDER BY` applies to the inputs.

**Comment by jsternberg** [comment]
I think this should just take the derivative in reverse and that's what I would expect if I were using it. Does this look like what others would expect?

```
> select derivative(value) from cpu
name: cpu
---------
time                            derivative
2016-04-07T15:50:26.595722704Z  0.970136522680435
2016-04-07T15:51:17.199127238Z  0.039523032460320275

> select derivative(value) from cpu order by desc
name: cpu
---------
time                            derivative
2016-04-07T15:50:26.595722704Z  -0.039523032460320275
2016-04-07T15:50:24.534157189Z  -0.970136522680435
```
