### ISSUE TITLE
[feature request] ADD / DROP SHARD

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#4682]
Occasionally, the need arises to perform low-level shard operations such as adding / dropping a shard and listing dropped (orphaned) shards.

* New DROP SHARD query that would remove a shard from the RP but not delete the file from disk.  This would turn it into an orphaned shard.  The data is still intact on disk but no longer accessible by a SELECT query.

* New ADD SHARD query for adding an existing shard.  It would have to verify that the time range of the data in the shard file matched the RP it was being added to.  Not exactly sure what that syntax would look like.  Maybe...
```
ADD SHARD mydb.someRP.234
```
would add ~/.influxdb/data/mydb/someRP/234 back to someRP.  Or,
```
ADD SHARD mydb.someRP.234 TO mydb.otherRP
```
which would move the file to the otherRP directory and add it to that RP.

* Modify SHOW SHARDS to list orphaned shards and possibly allow filtering by owners and date / time ranges.  Currently, it just looks through RPs and their shard groups to find all the shards.  This change would require it to also look on disk for shards the metastore doesn't know about and it would have to examine the data in those shards to find the period of time covered.

**Comment by otoolep** [comment]
I am on the hook for `DROP SHARD`.

**Comment by pauldix** [comment]
Closing this one out in favor of #5935. Add shard shouldn't be necessary since what's on disk should be the ultimate representation of what shards a server has.
