### ISSUE TITLE
[0.10] admin UI doesn't display results for some SHOW queries

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4688]
For instance `SHOW CONTINUOUS QUERIES` returns JSON in the payload but the results area is blank.

tested with 0.9.4.2

![screen shot 2015-11-05 at 13 42 35](https://cloud.githubusercontent.com/assets/6537329/10984279/2992c690-83cd-11e5-9ec1-a4e6c600dc1a.png)

**Comment by daviskirk** [comment]
This happens in 0.9.6 and 0.10 also (a UI warning "Query returned no results!" is shown instead).  Works fine using the CLI.

**Comment by zstyblik** [comment]
@beckettsean more [commands](https://github.com/influxdata/influxdb/blob/master/QUERIES.md) than just `SHOW CONTINUOUS QUERIES` might not be supported by Web UI, eg. `SHOW USERS`.

**Comment by beckettsean** [comment]
@jwilder anyone giving love to the Admin UI soon?

**Comment by jwilder** [comment]
@beckettsean Not currently.  PRs to improve/fix it are welcome though.

**Comment by Vidhuran** [comment]
Can i work on this item if nobody else is working on it currently ?

**Comment by Vidhuran** [comment]
`SHOW CONTINUOUS QUERIES` when executed from Admin UI actually returns the result for _internal table as well. 

![capture](https://cloud.githubusercontent.com/assets/1607713/13051840/1a5456ee-d404-11e5-83c8-c72141d3757b.PNG)

So it fails in the line https://github.com/influxdata/influxdb/blob/master/shared/admin/js/admin.js#L184 and displays that the query returned no results. 

LIkewise for `SHOW USERS`, if you have added some users then it would show in the results, if not the condition check for `values.length` pasted above would fail and the error is displayed.

**Comment by Vidhuran** [comment]
![show_users](https://cloud.githubusercontent.com/assets/1607713/13051936/a364926e-d404-11e5-84b4-fc95fd7d47fb.png)

**Comment by zstyblik** [comment]
@Vidhuran awesome!

**Comment by Vidhuran** [comment]
Now that this has been merged to the master will i be eligible for a t-shirt :smile:
