### ISSUE TITLE
rows discarded by `fill(none)` still eats up `limit`

### ISSUE THREAD

**Issue by edokan** [influxdata/influxdb#4714]
I have following query

`select mean(value) as value from "dummy" where time > '2015-01-01' group by time(1d) fill(none)`

it successfuly retrieves 17 rows starting june. This is expected situation bause I only have 17 days of information. 

When I want to limit my resultset to 10 rows I add `limit 10` to my query and no result returns. If I change my query limit to 1000 I get my 17 rows again. I believe rows discarded by `fill(none)` statement are still considered a part of resultset and counted. 

My system details
Windows 10 x64.
Go 1.5.1 windows/amd64
InfluxDB 0.9.3 (Build from source, patched to compile on Windows)

**Comment by beckettsean** [comment]
@jackzampolin can you repro?

**Comment by jackzampolin** [comment]
@beckettsean Will do!

**Comment by jackzampolin** [comment]
Unable to repro with master.  `fill()` works as intended.

**Comment by jackzampolin** [comment]
Successfully reproduced on master.

**Comment by arthurc** [comment]
Seems to be fixed in master
