### ISSUE TITLE
[feature request] CLI should preserve commas in DISTINCT output

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4718]
DISTINCT() returns a comma-separated array in the JSON, but the CLI presents it with whitespace delimiters. That can make it very hard to determine the actual distinct values for strings.

Ideally the CLI would preserve the separating commas in the array.

```
> select string from array
name: array
-----------
time				string
2015-11-09T22:31:47.375193342Z	this is string   1
2015-11-09T22:31:49.038457534Z	this is string   2
2015-11-09T22:31:50.462632687Z	this is string   3

> select distinct(string) from array
name: array
-----------
time			distinct
1970-01-01T00:00:00Z	[this is string   1 this is string   2 this is string   3]
```

**Comment by otoolep** [comment]
@corylanou -- what do you think? Sound like a good one for the community, assuming you agree with what @beckettsean  is proposing. How would you rank its difficultly?

**Comment by corylanou** [comment]
The real fix is to unwrap it like many of the other selectors now do, so that it would show as rows instead of an array in a column.

You would get this as a result:

```

time                string
1970-01-01T00:00:00Z  this is string
1970-01-01T00:00:00Z  this is string
1970-01-01T00:00:00Z  this is string
```

**Comment by flisky** [comment]
Is @corylanou's suggestion the final decision?

**Comment by beckettsean** [comment]
I'm fine with @corylanou's suggestion. It should be unambiguous regardless of the string content, which is a big plus.

**Comment by aneshas** [comment]
Hi, I would like to take this one

**Comment by corylanou** [comment]
I think @benbjohnson is refactoring the query engine right now, and this should likely wait on some of his changes to be completed.

**Comment by aneshas** [comment]
@corylanou oh, ok np :)

**Comment by mnlabs** [comment]
Any news about it? Unwrapping DISTINCT output as @corylanou said would be much appreciated.

**Comment by aneshas** [comment]
@corylanou If @benbjohnson has finished refactoring the query engine I'm still up for this one

**Comment by benbjohnson** [comment]
The results are unwrapped in v0.11.0 with the new query engine.

**Comment by mnlabs** [comment]
Excellent. Waiting for v0.11.0 then :)

**Comment by beckettsean** [comment]
0.11 returns each DISTINCT result on a new line, so this is now irrelevant.
