### ISSUE TITLE
TestCluster_Restart regularly failings (mostly under race)

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#4723]
https://circle-artifacts.com/gh/influxdb/influxdb/7310/artifacts/3/tmp/circle-artifacts.0LjCyAh/test_logs_race.txt

is an example. But it's making us care less about red builds. Skipping the test for now.

**Comment by otoolep** [comment]
cc @corylanou

**Comment by jwilder** [comment]
Test no longer exists.
