### ISSUE TITLE
Build up of deleted Shard Group and Shard info in Raft

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#4726]
Started with https://github.com/influxdb/influxdb/issues/4709

Due to the way our system works, deleted shard group and shard info stays in the Raft data forever. It's never removed. This is not a huge deal, but is wasteful of RAM and will cause retention enforcement to run slower and slower over time. Again, not a huge difference, but will happen.

The reason the system does soft-deletes of shard groups is so that the rest of the system can be absolutely sure that the associated shards should be deleted (as opposed to the associated shard group simply being missing, implying that the shards should be deleted).

Ideally the system would eventually clean-up all this soft-deleted resources.

**Comment by jsternberg** [comment]
Clustering [has been removed](https://influxdata.com/blog/update-on-influxdb-clustering-high-availability-and-monetization/) from the open source version so I'm going to close this issue.
