### ISSUE TITLE
[feature request] add simple stress test options to CLI for quick dataset generation

### ISSUE THREAD

**Issue by SamuelToh** [influxdata/influxdb#4733]
Hi there,

well done on Influx's query language guide found here. https://influxdb.com/docs/v0.9/query_language/index.html  It is very comprehensive and is certainly very useful.

Just a thought here.
I was thinking the guide can maybe be even better by having a sample data pack (a tar ball or something?) that contains:

1) an influxdb data file with probably around 100~200 rows of data?
2) a data pumper utility (maybe a shell script or something) that can allow newbie users like me to load sample data into my new influx installation.

Why? This is so that I can experiment/play around with those wonderful example queries found on the guide page using different values and parameters to further educate myself.

Cheers,
Sam

**Comment by otoolep** [comment]
Thanks @SamuelToh 

This is not a bad idea. Perhaps, instead, we add a new command to the CLI (`influx`). This command could be simply:

```
$ ./influx 
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9
InfluxDB shell 0.9
> demo
.....generated data inserted...
>
```
which would pump in the demo data.

Thoughts @corylanou @beckettsean ?

**Comment by dgnorton** [comment]
Would the existing `influx_stress` tool work for this?

**Comment by otoolep** [comment]
It technically would, but for a built in demo I thought the CLI itself
might be more user-friendly.

Also, in its default mode the stress tool will pump in much more data. It
would take much longer than a second. So then you would need a stress
config....

**Comment by dgnorton** [comment]
Fair enough about the stress tool.

`CLI` import might be a good solution though.  We could ship a plain text file which the `CLI` already knows how to read.  200 points would take less than a second.

`influx -import -path=influxdb_demo_data.txt`

**Comment by otoolep** [comment]
A big part of me really likes the idea of a built-in demo. Where does the file live? What if they built from source? Etc etc. 

That said I can see some drawbacks with adding demo stuff into the production CLI. It requires a code change anytime we want different data sets. That would be a pain.

**Comment by corylanou** [comment]
Couldn't we refactor something from the stress tool that we could call from the cli package?  This way we know the code always stays up to date, and they we an actually have it do some things like:

`demo` - inserts 1k rows of basic data
`demo 100000` would insert 100,000 random rows
`demo 100000 1000` would insert 100,000 rows with a cardinality of 1,000, etc.

Basically give it the same type of functionality the stress tool has but share the package.

**Comment by gunnaraasen** [comment]
@rkuchan and @mjdesa are working on a telegraf plugin that generates regular sinusoidal data.

**Comment by oiooj** [comment]
+1

**Comment by beckettsean** [comment]
@rkuchan is also working on uploading the sample data to S3 so it can be downloaded and injected via the CLI. It should release along with 0.9.5 final.

**Comment by beckettsean** [comment]
Closing in favor of https://github.com/influxdb/influxdb.com/issues/463

**Comment by beckettsean** [comment]
and also https://github.com/influxdb/influxdb.com/issues/464

**Comment by beckettsean** [comment]
@mjdesa assigning to you for the CLI/stress combination

**Comment by desa** [comment]
Exists, but not apart of the CLI.

https://github.com/influxdata/influx-stress
