### ISSUE TITLE
Query: disable the persistence of the WAL

### ISSUE THREAD

**Issue by ivanscattergood** [influxdata/influxdb#4734]
from https://influxdb.com/docs/v0.9/concepts/storage_engine.html

>It’s possible to disable the persistence of the WAL, instead relying on a regular flush to the index. This would result in the best possible performance at the cost of opening up a window of data loss for unflushed writes.

How do you do this? 

At the moment I don't have access to fast disk, BUT I do have access to more memory than I am using. If I can move the WAL completely into memory then I will be able to keep pace with bursts of updates. 

I am currently using 0.9.4.2 and the bz1 engine. I cannot move to 0.9.5 yet due to #4701

**Comment by beckettsean** [comment]
@pauldix I don't see a way to disable the WAL in the 0.9.4.2 config. 

```
[data]
  dir = "/Users/sean/.influxdb/data"
  max-wal-size = 104857600
  wal-flush-interval = "10m0s"
  wal-partition-flush-delay = "2s"
  wal-dir = "/Users/sean/.influxdb/wal"
  wal-enable-logging = true
  wal-ready-series-size = 30720
  wal-compaction-threshold = 0.5
  wal-max-series-size = 1048576
  wal-flush-cold-interval = "5m0s"
  wal-partition-size-threshold = 20971520
```
I wondered if any of the following would disable WAL persistence to disk?
- `max-wal-size=0`
- `wal-dir=''`
- ` wal-max-series-size=0`

Would any of those work to disable the WAL going to disk, or is that an old piece of advice that no longer applies?

**Comment by pauldix** [comment]
@beckettsean you can't disable the WAL going to disk. However, you could put the WAL directory on a RAM Disk
