### ISSUE TITLE
[0.9.5-nightly] Filtering by parameter which is not specified at the SELECT

### ISSUE THREAD

**Issue by varche1** [influxdata/influxdb#4736]
Hi! 
Find out unxpected behavior (0.9.5-nightly-ef84e33): InfluxDB do not filters by parameter which is not specified at the `SELECT` (on 0.9.2 works well).

How to reproduce:
* Create a database `issues_db10`: `/opt/influxdb/influx -execute "create database issues_db10"`
* Run python script https://gist.github.com/varche1/9ad6360637db87b9613f (use Python client `influxdb==2.8.0` for InfluxDB 0.9.2; use Python client `influxdb==2.9.2` for InfluxDB 0.9.4.2)
* Check your output with mine https://gist.github.com/varche1/8ad52c1fc5cfb1f128f0

There is the solition to query like `select count(processed_by), sum(profit) from /leads/ where time > '2010-01-01T00:00:00.000000+00:00' and time < '2010-01-01T11:00:00.000000+00:00' and processed_by = 1 group by time(1h)` but such query seems strange to me. Using `count(processed_by)` at `select` is weird.

**Comment by beckettsean** [comment]
@jackzampolin a good one to try and repro

**Comment by jackzampolin** [comment]
:+1:

**Comment by jackzampolin** [comment]
Successfully reproduced with `0.9.5-nightly-7d4bdc1`

**Comment by jackzampolin** [comment]
So to 'sum' this up: 
```
# WORKING
select sum(value) from "measurement" where time > N and time < M group by time(1h)

# NOT WORKING
select sum(value) from "measurement" where time > N and time < M and tag = tag_value group by time(1h)
``` 
The addition of a tag filter with an `AND` statement breaks this query.  The issue is present in `master` but not in 0.9.2.  Is that correct @varche1?

**Comment by varche1** [comment]
@jackzampolin Example I showed is little bit different:

# NOT WORKING
select sum(value) from /measurement/ where time > N and time < M and field_a = field_value group by time(1h)

# WORKING
select count(field_a), sum(value) from /measurement/ where time > N and time < M and field_a = field_value group by time(1h)

So, if I do not use field_a in SELECT, I can't filter on it.

Both of examples above work well at 0.9.4.2

**Comment by jsternberg** [comment]
This is an issue from before we did the query engine refactor and I don't think this issue exists anymore. Please try this with 0.13 and comment if it still isn't working properly. Thank you.
