### ISSUE TITLE
Graphite and UDP config not part of 'config' output

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#4752]
Started with https://github.com/influxdb/influxdb/commit/4f8b0aca9a563977e5024ea5e3ae63fe2e4118fe

which meant this was raised:

https://github.com/influxdb/influxdb/issues/4745

Until https://github.com/BurntSushi/toml/pull/68 is fixed, we cannot address this issue.

**Comment by otoolep** [comment]
@nkatsaros -- if you can find a way to address this issue without hitting the toml bug, we'd be happy to merge a new PR.

**Comment by titilambert** [comment]
Hello !
I just reworked the PR, the workaround is now smaller.

**Comment by titilambert** [comment]
Hello @otoolep !
I just reworked the PR, the workaround is now smaller.

**Comment by titilambert** [comment]
@corylanou any news for this one https://github.com/influxdata/influxdb/pull/5255 ?
