### ISSUE TITLE
Incorrect results while using a where clause(a string condition) against a field that has boolean values

### ISSUE THREAD

**Issue by saravapally** [influxdata/influxdb#4765]
Example:

I have a measurement called "m1" with field called "fault" that is a boolean. There are two points, one with fault = true, and another with fault = false.

Now, when I run the query : select * from m1 where fault = 'something'
it returns those rows where the value for "fault" is false. Shouldn't it return 0 rows as there are no rows where the value of "fault" is "something" ?

**Comment by otoolep** [comment]
Comparing a boolean field with a non-boolean value is currently undefined. You are mixing types, so there is ambiguity here. What are you trying to do?

**Comment by beckettsean** [comment]
Strings evaluate to 0 in a Boolean context, which is equivalent to False. It's not ideal behavior but it is expected behavior. Since the type of a field is fixed only per-shard, the query cannot throw a parser error at runtime.

**Comment by jsternberg** [comment]
This works correctly in 0.13.
