### ISSUE TITLE
InfluxDB - Admin Interface advertising InfluxDB v0.9.3

### ISSUE THREAD

**Issue by skynet** [influxdata/influxdb#4780]
![capture](https://cloud.githubusercontent.com/assets/139233/11139185/4789e296-899a-11e5-9109-3e5b849635de.PNG)

I have a nightly 0.9.5 installed. Is this by design or just a mere oversight.

Also, Admin Interface is using Bootstrap v3.3.4 while Bootstrap v3.3.5 is already available since June.

**Comment by gunnaraasen** [comment]
It's an oversight. The version string will be updated by PR https://github.com/influxdb/influxdb/pull/4776. 

The bootstrap version still needs to be updated so leaving this issue open for now.

**Comment by skynet** [comment]
Would you be ok with a pull request. I can help with the Admin UI. There are a few things that can be improved.

**Comment by otoolep** [comment]
Absolutely. See your name in the CHANGELOG!

Larger changes should be discussed on a ticket first.
