### ISSUE TITLE
[feature request] ORDER BY function return values.

### ISSUE THREAD

**Issue by gam-phon** [influxdata/influxdb#4794]
This is the same request as #3954 but this feature request to be ordered by count.
Example:

```
select count(values) from events group by event_type order by count desc
```

**Comment by mvadu** [comment]
+1 Allowing this with `limit` clause will allow for lot of interesting queries on the time series. It can be a dirty fix for #5345 for `Top` as well.

Something like below should give the worst performing transaction for an hour. 
`SELECT percentile(ResponseTime,90) FROM "Application_Transaction_Metrics" WHERE "State" =~ /California$/ AND time > 1452623400s and time < now() GROUP BY time(1h), "State", BusinessTransaction Order By percentile desc limit 1`

**Comment by max3163** [comment]
+1

This function is rly a most have !

**Comment by ptitou** [comment]
+1

**Comment by ericx10ng** [comment]
+1

**Comment by groblus** [comment]
+1

**Comment by mebrunet** [comment]
+1 This would be really useful!

**Comment by sebastian-azeti** [comment]
+1, definitely a must

**Comment by consense** [comment]
is there any update on the roadmap position for this?

**Comment by bfgoodrich** [comment]
It is now 2018, any update on this at all?

**Comment by NateZimmer** [comment]
Generally one wishes to target problematic devices. One can't target the most problematic devices if one cannot sort a long list by those values... this is kinda an embarrassing feature not to have.

**Comment by nathanielc** [comment]
Added difficulty/high as arbitrary sorting on the results is not possible nor is there a current easy place to hook in such behavior in InfluxQL. Flux is already capable of sorting the results by an arbitrary value.

**Comment by CanuckMarc** [comment]
2021 and still can't order by anything other than time.
