### ISSUE TITLE
GeoHash and GeoSpatial Support :: Feature Request 

### ISSUE THREAD

**Issue by ywadi** [influxdata/influxdb#4799]
Hi, 
A very heavy use case I am facing using a time series database is the ability to tag it with a location (GeoLocation) especially for remote sensing and sensor positions globally. In our case at a weather company almost everything is a spatiotemporal set of data. 
We are doing it on influx by simply adding a GeoHash string with the data and then query it back with Regex to get all points in time at a certain location. 

I would be great if this could be done out of the box, the ability to add a measure with a time and geohash and then simply query them back. Since geohash as a concept solves for the big issue of how to index and lookup data it should be fairly simple with what influx already has. 

Leaving it to you guys, and great job with the 0.9 release, amazing difference in performance.

**Comment by bencevans** [comment]
+1

**Comment by pauldanckaert** [comment]
This would be a great help! +1

**Comment by jeremyforan** [comment]
+1 sems natural

**Comment by jpdias** [comment]
+1

**Comment by ankushb** [comment]
+1

**Comment by chopj** [comment]
+1

**Comment by kaushikkapil** [comment]
+1

**Comment by pietermarsman** [comment]
+1

**Comment by justb4** [comment]
+1

**Comment by cholmes** [comment]
+1

**Comment by ehames** [comment]
This feature is very handy for IoT projects.

**Comment by whitetigle** [comment]
+1

**Comment by igledaniel** [comment]
+1

**Comment by sclausen** [comment]
+1

**Comment by IvanVas** [comment]
+1

**Comment by gandavar** [comment]
+1

**Comment by jcr1984** [comment]
+1

**Comment by lrolsen** [comment]
+1

**Comment by rbetts** [comment]
Those up-voting, it would be helpful to hear more specifics on use cases.

1. What problem are you trying to solve? 
2. Would geohash / S2 / space-filling-curves solve your problem? 
3. Or, do you need more precision? 
4. Are there specific geo functions you need to solve the problem?
5. What are the queries you expect to require? (points in poly? points in radius? ...)
6. What types of charts / graphs would need to be rendered?
7. What types of alerts would need to be triggered?

**Comment by lrolsen** [comment]
We have a number of geographically distributed sensors. We would like to be able to perform aggregations on the readings made by these sensors based on their geographical location. So for us, being able to tag each series with a geographical location and then query the series using one or more polys to aggregate on the series in those polys would do the trick for us. 

With regards to precision, a 5 decimal geohash would be enough for our use cases.

**Comment by nfroidure** [comment]
We have the same requirement and we found the ES geo-distance implementation very convenient: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geodistance-aggregation.html

Would be nice to have something similar on InfluxDB.

**Comment by whitetigle** [comment]
It seems this have been addressed meanwhile with geo time series like warp10.

**Comment by timhallinflux** [comment]
This is available via Flux...in the InfluxDB 1.8 release.
https://docs.influxdata.com/flux/v0.65/guides/geo/
