### ISSUE TITLE
[0.9.5-rc3] DERIVATIVE on aggregation function does not default to 1s rate of change

### ISSUE THREAD

**Issue by mahadeva604** [influxdata/influxdb#4819]
Why result is different?

```
> SELECT non_negative_derivative(mean(in_octets)) FROM "other_interface" WHERE "type" = 'ethernet' AND "cm_mac" =~ /001311a6edc6/ AND time > now() - 1h GROUP BY time(5m)
name: other_interface
---------------------
time                    non_negative_derivative
1447761300000000000
1447761600000000000     2.700182e+06
1447761900000000000     1.597755e+06
1447762200000000000     3.3451055e+06
1447762500000000000     5.7093755e+06
1447762800000000000     1.494687e+06
1447763100000000000     6.504519e+06
1447763400000000000     4.725501e+06
1447763700000000000     1.5185836e+07
1447764000000000000
1447764300000000000
1447764600000000000

> SELECT non_negative_derivative(mean(in_octets),1s) FROM "other_interface" WHERE "type" = 'ethernet' AND "cm_mac" =~ /001311a6edc6/ AND time > now() - 1h GROUP BY time(5m)
name: other_interface
---------------------
time                    non_negative_derivative
1447761300000000000
1447761600000000000     9000.606666666667
1447761900000000000     5325.85
1447762200000000000     11150.351666666667
1447762500000000000     19031.251666666667
1447762800000000000     4982.29
1447763100000000000     21681.73
1447763400000000000     15751.67
1447763700000000000     50619.45333333333
1447764000000000000
1447764300000000000
1447764600000000000
```

**Comment by beckettsean** [comment]
It does default to 1s rate for the `DERIVATIVE` and `NON_NEGATIVE_DERIVATIVE` functions. I can't explain the output you show, however.

@mahadeva604 can you provide a sample of the data being queried so we can try to reproduce this locally?

@rkuchan can you construct some similar derivative queries and see if you can repro the behavior, or confirm that in your testing there is no difference between `[NON_NEGATIVE_]DERIVATIVE(mean(value))` and `[NON_NEGATIVE_]DERIVATIVE(mean(value), 1s)`?

**Comment by rkuchan** [comment]
@sean, I'm able to repro:

Data:
```
> SELECT * FROM mymeas
name: mymeas
------------
time			        source
2015-09-18T21:12:00Z	1
2015-09-18T21:18:00Z	12
2015-09-18T21:24:00Z	2
2015-09-18T21:30:00Z	16
2015-09-18T21:36:00Z	3
```

As expected, without an aggregation function and a `GROUP BY time()` clause `NON_NEGATIVE_DERIVATIVE()` returns the same result when I don't specify `1s` and when I do specify `1s` in the query:
```
> SELECT NON_NEGATIVE_DERIVATIVE(source) FROM mymeas WHERE time >= '2015-09-18T21:12:00Z' AND time <= '2015-09-18T21:36:00Z'
name: mymeas
------------
time			        non_negative_derivative
2015-09-18T21:18:00Z	0.030555555555555555
2015-09-18T21:30:00Z	0.03888888888888889

> SELECT NON_NEGATIVE_DERIVATIVE(source,1s) FROM mymeas WHERE time >= '2015-09-18T21:12:00Z' AND time <= '2015-09-18T21:36:00Z'
name: mymeas
------------
time			        non_negative_derivative
2015-09-18T21:18:00Z	0.030555555555555555
2015-09-18T21:30:00Z	0.03888888888888889
```

When I add in an aggregation function and a `GROUP BY time()` clause, `NON_NEGATIVE_DERIVATIVE()` does not return the same result when I don't specify `1s` and when I do specify `1s` in the query:
```
> SELECT NON_NEGATIVE_DERIVATIVE(MEAN(source)) FROM mymeas WHERE time >= '2015-09-18T21:12:00Z' AND time <= '2015-09-18T21:36:00Z' GROUP BY time(12m)
name: mymeas
------------
time 		            non_negative_derivative
2015-09-18T21:24:00Z	2.5

> SELECT NON_NEGATIVE_DERIVATIVE(MEAN(source),1s) FROM mymeas WHERE time >= '2015-09-18T21:12:00Z' AND time <= '2015-09-18T21:36:00Z' GROUP BY time(12m)
name: mymeas
------------
time 		            non_negative_derivative
2015-09-18T21:24:00Z	0.003472222222222222
```

When I don't specify `1s` in the query it looks like InfluxDB calculates the difference between the aggregated values and doesn't convert that difference to the rate of change per one second.

Finally, `DERIVATIVE()` exhibits that same behavior when combined with a function and a `GROUP BY time()` clause:
```
> SELECT DERIVATIVE(MEAN(source)) FROM mymeas WHERE time >= '2015-09-18T21:12:00Z' AND time <= '2015-09-18T21:36:00Z' GROUP BY time(12m)
name: mymeas
------------
time			        derivative
2015-09-18T21:24:00Z	2.5
2015-09-18T21:36:00Z	-6

> SELECT DERIVATIVE(MEAN(source),1s) FROM mymeas WHERE time >= '2015-09-18T21:12:00Z' AND time <= '2015-09-18T21:36:00Z' GROUP BY time(12m)
name: mymeas
------------
time			        derivative
2015-09-18T21:24:00Z	0.003472222222222222
2015-09-18T21:36:00Z	-0.008333333333333333
```

**Comment by mahadeva604** [comment]
I think data from @rkuchan enough to find bug.

**Comment by beckettsean** [comment]
@mahadeva604 the workaround is fairly trivial, just explicitly include the `1s` rate of change parameter.

@jwilder perhaps we should make the rate parameter required? That would also avoid confusion from those users that assume the `GROUP BY` time interval is the default rate unit.

**Comment by jsternberg** [comment]
If an aggregate and `GROUP BY time(...)` are used, the default for the derivative interval becomes the group by interval. So the interval for your query is 5 minutes because `GROUP BY time(5m)` is in the query.

It looks like the documentation isn't clear about this. I'll open an issue so it's more clear.
