### ISSUE TITLE
Continuous Query Every Minute grouped by 5m

### ISSUE THREAD

**Issue by sundarv85** [influxdata/influxdb#4820]
We are developing an alerting system, which checks whether the threshold is crossed in the last 5 minutes. However, we want to test this every minute whether the last five minutes has crossed a specific interval.

Currently this is not possible in continuous queries.

Even when we give "group by time(5m)", and have *compute-runs-per-interval* as 10 and *compute-no-more-than* set to 1m, even though it would run every minutes, it would only store once in 5 minutes. ie. we will find 01:05 and then 01:10.

Our requirement is to have five entries

01:05 (this has avg of 01:01 till 01:05)
01:06 (this has avg of 01:02 till 01:06)
01:07 (this has avg of 01:03 till 01:07)
...
01:10 (this has avg of 01:06 till 01:10)

Such a feature would be very helpful.

[Refer discussion at google groups](https://groups.google.com/forum/#!topic/influxdb/6zwYutM5K5k)

**Comment by davidbirdsong** [comment]
+1

I have a few examples where I'd like to calculate info on the previous hour storing the result into another measurement.

- rolling averages response body sizes
- distinct items

An explicit CQ interval would make this possible instead of deriving it off of group by time.

**Comment by kevinbeck** [comment]
+1

**Comment by nathanielc** [comment]
This short of thing is now possible with Kapacitor. Example TICKscript to compute the mean of the last 5 minutes every minute

```go
batch
    |query(' SELECT mean(value) FROM mymeasurement')
        .period(5m)
        .every(1m)
    |influxDBOut()
        .database('mydb')
        .retentionPolicy('myrp')
        .measurement('anothermeasurement')
        .precision('s')
```

The alerting piece is also possible see https://docs.influxdata.com/kapacitor/latest/nodes/alert_node/ for more info

**Comment by beckettsean** [comment]
This is now possible with InfluxDB CQs, but does require multiple CQs.

In 0.13, the [offset of GROUP BY time intervals](https://docs.influxdata.com/influxdb/v0.13/query_language/data_exploration/#group-by-time-intervals) can be set, so you would have five CQs (paraphrasing):

```
SELECT ... INTO ... FROM ... GROUP BY time(5m), *
SELECT ... INTO ... FROM ... GROUP BY time(5m, 1m), *
SELECT ... INTO ... FROM ... GROUP BY time(5m, 2m), *
SELECT ... INTO ... FROM ... GROUP BY time(5m, 3m), *
SELECT ... INTO ... FROM ... GROUP BY time(5m, 4m), *
```
