### ISSUE TITLE
[feature request] Add InfluxQL syntax to explicitly declare an identifier as a tag or field key

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/influxdb#4823]
One solution is to allow an identifier to be prepended with `tag` or `field` followed by a period (`.`).

E.g.
```
SELECT tag.ambiguous_key, field.ambiguous_key FROM measurement WHERE tag.ambiguous_key = 'something' AND field.ambiguous_key =~ /something.*/
```

Identifiers without `tag` or `field` would be evaluated the same way as they are now, which is the field key is used if it exists.

**Comment by gunnaraasen** [comment]
This would solve https://github.com/influxdb/influxdb/issues/4630, obviate the need for https://github.com/influxdb/influxdb/issues/2615, and offer an alternative to `RENAME FIELD` and `RENAME TAG` when dealing with the same field and tag keys.

**Comment by pauldix** [comment]
Yes, great idea. Should also include in this the ability to do `select field.* from foo`

**Comment by jwilder** [comment]
Postgres has a cast syntax `select foo::date from ...` that is kind of similar to this idea.  As an alternative, for comparison:

```
SELECT ambiguous_key::tag, ambiguous_key::field 
FROM measurement 
WHERE ambiguous_key::tag = 'something' 
AND ambiguous_key::field =~ /something.*/
```
http://stackoverflow.com/questions/5758499/double-colon-notation-in-sql

**Comment by pauldix** [comment]
That's interesting too. I'm not sure I have a strong preference for one over the other.

**Comment by corylanou** [comment]
I like the `::` notation a lot.  Since fields can have periods in them already, it will make the parsing rules really easy to implement.  @dgnorton thoughts?

**Comment by dgnorton** [comment]
I think `::` will be easy to parse.
* Add a `Type` field to `type Measurement` and `type VarRef` in ast.go
* `parseSegmentedIdents()` already exits when it sees`:` so...
* modify `parseSource()` to check for `::` and parse value for the new `Type` field.  See `parseTarget()` for example of parsing `::<something>`
* modify `parseVarRef()` to check for `::` and parse value for new `Type` field

**Comment by jsternberg** [comment]
I'm in the process of coming up with a prototype to demonstrate this type of functionality. I've chosen to use the sigil `@` at least temporarily because I think it will look the best syntactically and will also be the easiest to implement.

I'll push a branch and comment again when I finish.

**Comment by jsternberg** [comment]
Closing this in favor of #6519.
