### ISSUE TITLE
[ 0.9.6-nightly-43a4201] continuous queries don't run

### ISSUE THREAD

**Issue by ivanscattergood** [influxdata/influxdb#4829]
I have a (large number) of continuous queries configured to run, based on an hourly cycle. 

However if I check the log the continuous query has not run since this morning: 
[visedge@RBC-visual-edge ~]$ date
Tue Nov 17 21:52:29 GMT 2015
[visedge@RBC-visual-edge ~]$ cat  /var/log/influxdb/influxd.log  | grep continuous_querier
[continuous_querier] 2015/11/17 06:29:51 Starting continuous query service
[continuous_querier] 2015/11/17 06:29:52 executing continuous query metric_mdoe_ny_dev_solny_GEqa2_ManEnt_Processes_hour_CQ

I have modified the default settings, but I'm still expecting this process to run several times an hour. 

[continuous_queries]
  log-enabled = true
  enabled = true
  recompute-previous-n = 2
  recompute-no-older-than = "5h"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m"

Could this be due to the either the number of continuous queries I have defined (1700) or the names of them (they are quite long to make them unique as they are dynamically generated)?

**Comment by ivanscattergood** [comment]
I have now moved the continuous queries logic into the Java code that I am using to record the original raw data. 

I can see that writing the data from the queries is frequently causing timeouts, so I suspect this is the root cause of the continuous queries failing

I am using the tsm1 data format.

**Comment by beckettsean** [comment]
@ivanscattergood what is the largest and smallest `GROUP BY` interval for your CQs?

**Comment by beckettsean** [comment]
what are your machine specs?

**Comment by ivanscattergood** [comment]
All of them are 1 hour

its a 64GB 4vCPU machine

**Comment by beckettsean** [comment]
@ivanscattergood I suspect this is due to the large number of queries defined. We hope to repro this soon.

**Comment by beckettsean** [comment]
@mjdesa here's one for the test suite, > 1000 CQs defined on a single db.

**Comment by otoolep** [comment]
You can see stats on continuous queries via `SHOW STATS for 'cq'`.

**Comment by jsternberg** [comment]
I'm going to close this since it was filed against an older version of InfluxDB. We have made a lot of changes and fixes since then. Please try the newest version and comment here if this problem still isn't resolved. Thank you.
