### ISSUE TITLE
TCP Support

### ISSUE THREAD

**Issue by manishjain002** [influxdata/influxdb#4838]
Like UDP, I would request to have TCP options also available. I know HTTP is there, but the overheads in TCP are much lesser than HTTP.

**Comment by manishjain002** [comment]
As per my understanding, batch write is when the collector collects the
data (irrespective of communication interface) and write in a batch.
In our case, we want to optimize the network usage/bandwidth by our field
sensors. Thus TCP will help in providing assurance of delivery at the same
time less overhead.

**Comment by FPurchess** [comment]
+1 it would also really help to be able to read over TCP! We currently ran into performance problems due to known limitations (HTTP is slow + connects for every request; packing multiple queries into one request is hard due to concatenation rules + missing JOINS).

**Comment by treystout** [comment]
+1 Came here for this issue. If you have several high speed sensors attempting to write, buffering at the source gets more and more susceptible to data loss. For everything Influx gets right (which is so much!), it's surprising that the recommended interface is a stateless text based protocol.

Is there any buy-in or plan from the team to enable a TCP endpoint similar to the UDP endpoint? Has testing been done to prove that HTTP overhead is slowing down performance enough to get rid of it? What would be involved in porting the UDP handler to a TCP option?

**Comment by wojciechszela** [comment]
+1

**Comment by mocchidesu** [comment]
+1

**Comment by dokie** [comment]
👍
