### ISSUE TITLE
make rate parameter required for DERIVATIVE and NON_NEGATIVE_DERIVATIVE

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4839]
This would clear up confusion around the rate of change units, as thjey would have to be explicitly supplied for all derivative queries. Would also mitigate https://github.com/influxdb/influxdb/issues/4819, since the parameter would always be required.

This also seems more future proof, since there's only one valid syntax and calculation path for DERIVATIVE.

**Comment by jsternberg** [comment]
@pauldix should we make this change or not?

**Comment by beckettsean** [comment]
If https://github.com/influxdata/docs.influxdata.com/issues/343 is correct that the default is now to use the GROUP BY interval and not `1s`, then the need for this change is less dire. However, it is more future-proof, since all behavior is explicitly declared.
