### ISSUE TITLE
Should be able to sample points

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#484]
Multiple users have asked for the ability to sample points from a series. They'd like to do something  like

```sql
select min(value) from temperatures sample by time(1d) where time > now() - 30d
```

The idea being that instead of doing the group by and having the resulting ticks have their timestamp set, instead the raw ticks that are sampled should be returned. So that query would actually just return all columns for each of the min datapoints for each day.

This wouldn't make sense for every aggregate function, but for things like `first`, `last`, `min`, `max` it would work. And we could add something later like `random` or other sampling methods I'm not thinking of.

Thoughts and feedback on this are welcome. There are probably scenarios in which you want to do sampling that maybe this won't make sense. So let us know!

**Comment by jbclements** [comment]
+1, sigh

**Comment by marcuswestin** [comment]
+1

**Comment by marcuswestin** [comment]
Nevermind: `AVG(value)` and `GROUP BY` time does what I need. Cheers :)

**Comment by xiic** [comment]
+1, including the proposed syntax (keep it the same as `GROUP BY`, just with a different keyword) and the `RANDOM` aggregate function. Are there any plans for this?

**Comment by XingxiaoLu** [comment]
+1

**Comment by LLFourn** [comment]
+1
I don't get why sample can't be an function.

```
SELECT SAMPLE(temp,10s) FROM mydata # samples spaced 10 seconds apart
SELECT SAMPLE(temp,10) FROM mydata # 10 uniformly sampled points
SELECT SAMPLE(temp,10,'random') FROM mydata # 10 random sampled points
```
