### ISSUE TITLE
over-aggressive aggregation with aggregate function and duplicate measurement in a query

### ISSUE THREAD

**Issue by mbell697** [influxdata/influxdb#4842]
Not sure if this is a bug or intended behavior but it was quite unexpected. If intended it could use a warning in the docs.

When duplicating a series in an aggregate query, the aggregate function appears to be used to 'merge' the duplicate series. 

`select sum(value) as value from "series1", "series1" where <stuff> group by <stuff>`

Will return a single series, `series1`, with all values doubled. Similarly if "series1" appears 3 times, the resulting series will have the values tripled, etc. The same query with `mean` as the aggregate returns the expected values, but it's unclear if the `mean` calculation is still happening between duplicate series under the hood.

**Comment by beckettsean** [comment]
@mbell697 This is a bug, I think. The query language treats each provided measurement as an independent thing, so repeating a measurement in a query should call it twice. However, results cannot span measurements, and aggregation functions should return a single value per measurement. In this case the query should return two identical results, not a single doubled one.

What version of InfluxDB are you running?

**Comment by mbell697** [comment]
`0.9.4`

**Comment by beckettsean** [comment]
Verified on 0.9.4.2:

```
> select * from doublesum
name: doublesum
---------------
time				value
2015-11-20T23:36:00.001314725Z	50

> select sum(value) from doublesum
name: doublesum
---------------
time			sum
1970-01-01T00:00:00Z	50

> select sum(value) from doublesum, doublesum
name: doublesum
---------------
time			sum
1970-01-01T00:00:00Z	100
```

**Comment by mbell697** [comment]
Checked via `curl` as well as confirmed the behavior.

**Comment by jsternberg** [comment]
Still happens in 0.13.
