### ISSUE TITLE
[0.9.4] DROP MEASUREMENT stops wal flushes

### ISSUE THREAD

**Issue by sysadmin1139** [influxdata/influxdb#4850]
I've managed to reproduce this a couple of times now. When dropping measurements with some data in them, it seems that WAL flushes stop. You can see the impact here:

    [wal] 2015/11/20 00:44:11 Flush due to idle. Flushing 11 series with 11 points and 655 bytes from partition 1
    [wal] 2015/11/20 00:44:11 write to index of partition 1 took 5.42853ms
    [wal] 2015/11/20 00:44:21 Flush due to idle. Flushing 11 series with 11 points and 655 bytes from partition 1
    [wal] 2015/11/20 00:44:21 write to index of partition 1 took 4.472542ms
    [query] 2015/11/20 00:44:23 DROP MEASUREMENT daniels_internal_cpu_idle
    [wal] 2015/11/20 00:44:23 Flush due to idle. Flushing 688 series with 1008992 points and 17152864 bytes from partition 1
    [wal] 2015/11/20 00:44:24 write to index of partition 1 took 556.749234ms

After the big flush, the regular every 10 seconds flush message stops. After a while, we start getting log-entries like this:

    [write] 2015/11/20 00:04:25 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [graphite] 2015/11/20 00:04:25 failed to write point batch to database "graphite": write failed: engine: write points: write throughput too high. backoff and retry

Which suggests something is getting gummed up. New data does come in, and is queryable, but there are no logged flushes. Watching the `wal` directory-tree, I can see that the files are increasing in size, but the `data` directory sizes do not increase.

**Comment by beckettsean** [comment]
@sysadmin1139 does a restart clear the issue?

**Comment by sysadmin1139** [comment]
A restart does clear the issue, and it reads in the backed up WAL file.

**Comment by sysadmin1139** [comment]
Will try updating to 0.9.5.1 and see if #4913 fixes this.

**Comment by sysadmin1139** [comment]
Changing the version to 0.9.5.1 did not change this behavior.

**Comment by jwilder** [comment]
This issue is related to the `b1` storage engine which was replaced by the `tsm` engine.
