### ISSUE TITLE
Allow querying only for time

### ISSUE THREAD

**Issue by nornagon** [influxdata/influxdb#4862]
I'd like to write a query that only returns the time of the last value for a given series. e.g.

```
SELECT time
FROM temperature
WHERE time > now() - 1d
GROUP BY deviceId
ORDER BY time DESC
LIMIT 1
```

Barring the fact that `ORDER BY time DESC` doesn't work (#4861), InfluxDB also refuses to execute a query that only returns `time` (not, say, `value`).

My use case for this is building an alerting system that will tell you if a sensor stops reporting data. The above query should return the timestamp of the latest data point for any sensor that has reported data in the last day, grouped by sensor ID.

It's possible to get around this limitation by querying the data directly (`SELECT value`), but it doesn't seem like it ought to be necessary.

**Comment by samhatchett** [comment]
+1 

and not just for the `LIMIT 1` case - my application sometimes needs to know times but not values for a series, and this would I assume cut down the communication overhead a bit
