### ISSUE TITLE
[0.9.4-0.9.5] cannot use backslash then space in an identifier name

### ISSUE THREAD

**Issue by Griesbacher** [influxdata/influxdb#4865]
- Debian 8 x64
- InfluxDB 0.9.4(Source) + 0.9.5(Package)

I'm not sure if I missunderstood the escapesyntax, if so it would be nice to help me out.
I want to  achieve a tablename like this: a\ z
The only tablename I can create is: a \z

Below are some queries I have tested, in my opinion the one with value=2 or 3 should be the query to solve the problem but I get an error or anything...

If I use just one specialchar in the tablename it works, but two in a row breaks it. Does someone have encounterd a similar problem?

I also think case: value=3 is a Bug, because it returnes OK but it does not appear in the database!?
The logs says something like this after the query: "Flushing 1 series with 1 points and 17 bytes from partition 1" which is one byte more than the "lost" query.

curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE test"

curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'a\z value=0 1'
-> HTTP/1.1 204 No Content

curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'a\ z value=1 1'
-> HTTP/1.1 204 No Content

curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'a\\ z value=2 1'
-> HTTP/1.1 400 Bad Request
unable to parse 'a\ z value=2 1': invalid field format

curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'a\\\ z value=3 1'
-> HTTP/1.1 204 No Content

curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'a\ \z value=4 1'
-> HTTP/1.1 204 No Content

0.9.4:
name: a \z
time                value
1970-01-01T00:00:00.000000001Z   4

name: a z
time                value
1970-01-01T00:00:00.000000001Z 1

name: a\z
time                value
1970-01-01T00:00:00.000000001Z 0

0.9.5:
name: a \z
time    value
1   4

name: a z
time    value
1   1

name: a\z
time    value
1   0

**Comment by beckettsean** [comment]
Closely related to https://github.com/influxdb/influxdb/issues/3682 I suspect.

**Comment by beckettsean** [comment]
@Griesbacher it's not that there are two special characters, it's that one of them is the backslash character, which is also the escape character for the line protocol, and the other is whitespace, which has syntactical meaning in the line protocol (when not escaped). Any other two special characters should work, it's only the backslash and the space that are invalid.

Not saying this isn't a bug, it's just much more narrow that originally reported.

**Comment by Griesbacher** [comment]
The 'influx_inspect info' command lists the "lost" dataseries(value=3). It looks like that the data is stored, but can't be queried, due to the fact 'select * from /.*/' returns nothing.

influx_inspect info:
Shard           DB              Measurement     Tags [#K/#V]    Fields [Name:Type]              Series
2               test            a\ z            0/0             1 [value:float]                 0

Not sure if this is useful or if I read this tool the right way.
