### ISSUE TITLE
[feature request] collectd service: Add ability to set several typesdb files

### ISSUE THREAD

**Issue by AndrejKorshikov** [influxdata/influxdb#4873]
In `collectd.conf` file we can set one **or more** files that contain the data-set descriptions:
`TypesDB "/usr/share/collectd/types.db" "/etc/collectd/my_types.db"`

There is need for ability to set multiple typesdb files in `[collectd]` section of `influxdb.conf`.

**Comment by otoolep** [comment]
I believe this will get you what you want: https://github.com/influxdb/influxdb/pull/4740

**Comment by AndrejKorshikov** [comment]
@otoolep -- exactly. Thanks a lot!

**Comment by mark-rushakoff** [comment]
Should be fixed by https://github.com/influxdata/influxdb/pull/6908, present in 1.0 and newer.
