### ISSUE TITLE
[0.9-5-rc3] [feature-request] Graphite Greedy Field Template

### ISSUE THREAD

**Issue by lskillen** [influxdata/influxdb#4880]
Hello!  We're currently evaluating InfluxDB as a replacement for Graphite/Whisper, and are utilising (with success mostly) 0.9.5-rc3 to do so.  Everything has been fantastic so far, but one of the hitches that we've encountered with the Graphite input is that it would be extremely useful to perform greedy matching on fields in addition to templates.  For example, to use a template like this:

`collectd.*.processes.* agent.host.measurement.process.field*`

In order to match against an input such as:

`collectd.myhost.processes.influxd.ps_disk_octets.read 20726.262918 1448269462`
`collectd.myhost.processes.influxd.ps_disk_octets.write 142.1334334 1448269462`

To produce a field break down like:

timestamp | agent | host | plugin | process | ps_disk_octets_read | ps_disk_octets_write
-------------- | -------- | ----- | -------- | ----------- | --------------------------- | ------------------
23/112015@09:04:22 | collectd | myhost | processes | influxd | 20726.262918 | 142.1334334

Unfortunately this isn't possible at the moment because support for greediness is only built-in to `measurement`, as we can see in [`parser.go`](https://github.com/influxdb/influxdb/blob/b1c5a36b0ded080f181f3bb1116fb5bc0150c8b3/services/graphite/parser.go#L229-L242).  I'm not typically a Go developer so apologies if the analysis is way off the mark here!

This feature would be extremely useful for us and, I'm assuming, others who may want to migrate from Graphite to InfluxDB.  Thank you in advance for any assistance (don't worry, I'll be back to shower more thanks if this is implemented) - In the meantime I think I need to brush up on Go development in order to consider submitting pull requests instead of just feature requests. ;-)

**Comment by xaniasd** [comment]
this would be great :+1:

**Comment by jwilder** [comment]
Looks like #5562 may address this.

**Comment by gunnaraasen** [comment]
As Jason mentioned, as of 0.11 it's possible to use `field*` to capture the remainder of a metric path thanks to https://github.com/influxdata/influxdb/pull/5562.
