### ISSUE TITLE
[0.9.5] CQ with multiplication and no alias causes 100% CPU spike

### ISSUE THREAD

**Issue by jyoung15** [influxdata/influxdb#4882]
This is somewhat related to issue #3838 and #3643.  The following causes a spike in CPU on the influxd process the first time the CQ runs. This basically hangs the process and requires a restart.

`CREATE CONTINUOUS QUERY test ON db BEGIN SELECT 8.000 * non_negative_derivative(mean(value), 1s) INTO testcq FROM bytes_in GROUP BY time(30s), * END`

However the same query with an alias does not cause any problems:

`CREATE CONTINUOUS QUERY test ON db BEGIN SELECT 8.000 * non_negative_derivative(mean(value), 1s) AS bps INTO testcq FROM bytes_in GROUP BY time(30s), * END`

Of course you will need to modify the query for your environment, but it appears the problem is due to using an operator (+,-,*,/) in the select causes a null column name.

Reproducible on 0.9.5

**Comment by jsternberg** [comment]
The query engine now makes sure to produce a non-nil name for all of the columns. If you find a column that still isn't getting the proper name, please open another issue so we can fix that.

Thanks!
