### ISSUE TITLE
[0.9.5] Milestone out of date

### ISSUE THREAD

**Issue by ivanscattergood** [influxdata/influxdb#4894]
Hi Guys, 
I was trying keep pace with all of the changes you have made, and I noticed that the milestone for 0.9.5: 

https://github.com/influxdb/influxdb/milestones/0.9.5

Is NOT in sync with the Change log and the Downloads page

https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md
https://influxdb.com/download/index.html

Ivan

**Comment by pauldix** [comment]
sure, will try to get to this soon!

**Comment by jsternberg** [comment]
Milestones are currently being used correctly in the project for 0.13 and we'll try to continue doing that for every version after that. Closing this since I don't think there's anything more we can do.
