### ISSUE TITLE
[feature request] Allow User-specific options via ~/.influxdb.conf

### ISSUE THREAD

**Issue by descrepes** [influxdata/influxdb#4895]
Hi,

It would be awesome if we can set User-specific options (username, password, database, format, ...) via a file (~/.influxdb.conf, ~/.influxrc or whatever in the home directory) like the ~/.my.cnf MySQL does.

Regards

**Comment by jsternberg** [comment]
I think this is the same as #5840 so I'm going to close this in favor of that issue instead. Thank you for your feature request.
