### ISSUE TITLE
Runtime out of memory 0.9.5-stable

### ISSUE THREAD

**Issue by panda87** [influxdata/influxdb#4896]
Hi

3 days ago I upgraded my influx cluster to the latest stable version 0.9.5 from 0.9.4.2
Yesterday one of the servers in the cluster got 'out of memory' panic error, and I wanted to ask your help with the investigation.

The complete error (1400~ lines )listed on the gist file: https://gist.github.com/panda87/0c9be1092034f6971189

The second problem that this outage caused was that all the data from this server become unavailable, I've made a short test for that and `COUNT(value)` one of the measurements, in 2 servers I got high number (number of times the value in the measurements exists in the DB) and in the outage server I got number that closed to 0.
When I logged in to the outage server I found that it created new shard that doesn't exist in the other servers.

1. What do you think could be the reason, and how we can solve it?
2. How can I fix the problem in the outage server? and why this happened?

Thanks

**Comment by beckettsean** [comment]
@panda87 what are the results of `SHOW SERVERS` for each node in the cluster? What are the contents of `influxdb/meta/peers.json` on each node?

**Comment by rossmcdonald** [comment]
Closing due to new architectural changes with the clustering meta service. Please try recreating a cluster with version `0.10.0`, and create a new issue if you run into any problems.
