### ISSUE TITLE
Race condition for joining servers becoming Raft nodes when creating new cluster

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#4910]
1. Start a node in a docker container.
2. Then start 6 other nodes in docker containers at the same time pointed at the first server.
3. Run show servers

You will sometimes end up with more than 3 of the 7 servers in the cluster in the Raft consensus group.

**Comment by corylanou** [comment]
Significant changes in the way the nodes now start up no longer allow for this.  Each node is now explicitly configured for meta, data, or both.
