### ISSUE TITLE
Problem on continuous query with small group by

### ISSUE THREAD

**Issue by jeanpralo** [influxdata/influxdb#4914]
Hi there,

I have tried to find a similar problem but I want to avoid hijacking a thread if this is not related.

I have a database with quite a lot of metrics sent from riemann, I am using CQ to downsample my metrics which are pretty easy:
```
_1h
"CREATE CONTINUOUS QUERY _1h ON db1 BEGIN SELECT mean(value) AS "value" INTO "db1"."_1h".:MEASUREMENT FROM "db1"."default"./.*/ GROUP BY time(1m), host END"
_1d
"CREATE CONTINUOUS QUERY _1d ON db1 BEGIN SELECT mean(value) AS "value" INTO "db1"."_1d".:MEASUREMENT FROM "db1"."default"./.*/ GROUP BY time(5m), host END"
_1w
"CREATE CONTINUOUS QUERY _1w ON db1 BEGIN SELECT mean(value) AS "value" INTO "db1"."_1w".:MEASUREMENT FROM "db1"."default"./.*/ GROUP BY time(30m), host END"
_4w
"CREATE CONTINUOUS QUERY _4w ON db1 BEGIN SELECT mean(value) AS "value" INTO "db1"."_4w".:MEASUREMENT FROM "db1"."_1d"./.*/ GROUP BY time(2h), host END"
_24w
"CREATE CONTINUOUS QUERY _24w ON db1 BEGIN SELECT mean(value) AS "value" INTO "db1"."_24w".:MEASUREMENT FROM "db1"."_1d"./.*/ GROUP BY time(12h), host END"
_52w
"CREATE CONTINUOUS QUERY _52w ON db1 BEGIN SELECT mean(value) AS "value" INTO "db1"."_52w".:MEASUREMENT FROM "db1"."_1w"./.*/ GROUP BY time(1d), host END"
```
I am running influxdb 0.9.5.1, when I check the logs I can see that the CQ are correctly executed.

The problem I am facing is that inside the _1h retention policy I am missing series for some hosts. It seems to have happened since I have more and more hosts sending data, hence more metrics.

I have tried to play around with the variables of [continuous_queries] but I have trouble to understand their role. 

What I think is happening is that they are too much data to compute for that CQ to run all at once and everything is not computed at the same time. So next time the CQ runs it tries to go and have a look at what is not computed but it is considered as lagged and not treated ?

Could I be correct?

Thanks for your help.

**Comment by jeanpralo** [comment]
Something that I do not seem to understand is that when I take the query from the logs (CQ), and run it manually, it returns all the data it is supposed in a timely fashion.

**Comment by beckettsean** [comment]
Possibly another case of https://github.com/influxdb/influxdb/issues/4803. I will try to analyze my test results tomorrow.

**Comment by beckettsean** [comment]
> What I think is happening is that they are too much data to compute for that CQ to run all at once and everything is not computed at the same time. 

How many points are written per day? The `_52w` CQ is likely running every 2.4 hours, sampling all points from the day so far, per measurement. If that gets into the millions of points, which it easily could, that might be too much for the system to handle before timeouts happen.

> So next time the CQ runs it tries to go and have a look at what is not computed but it is considered as lagged and not treated ?

CQs do not track what points they have already collected. It's just an automated batcher, like cron for queries. If a prior CQ timed out or missed data, the next run would not know that. For `GROUP BY` intervals longer than 2 minutes the CQ is calculated multiple times, but each result silently overwrites the previous one and there is no sanity checking.

> Something that I do not seem to understand is that when I take the query from the logs (CQ), and run it manually, it returns all the data it is supposed in a timely fashion.

So `SELECT mean(value) AS "value" FROM "db1"."_1w"./.*/ GROUP BY time(1d), host` returns in a reasonable time frame? How long does it take to execute? (The logs show the query time at the end of the return statement log, e.g. `[http] 2015/12/01 18:11:04 ::1 - - [01/Dec/2015:18:11:04 -0800] GET /query?db=mydb&epoch=ns&q=select+last%28value%29+as+foo+from+graph HTTP/1.1 200 115 - InfluxDBShell/0.9.5 f10d6e4b-9899-11e5-9fbc-000000000000 5.040343ms`)

**Comment by jeanpralo** [comment]
Hi,

Thanks for your answert @beckettsean 

>How many points are written per day? The _52w CQ is likely running every 2.4 hours, sampling all points from the day so far, per measurement. If that gets into the millions of points, which it easily could, that might be too much for the system to handle before timeouts happen.

Well it depends on the number of servers I have writing to the influxdb but at the moment in the default database there is around 300 data points written every 20 seconds. So around 881280 data points per day. But yeah could be a little bit more than that. At the moment though I do not see any problem with _52w CQ.

>So SELECT mean(value) AS "value" FROM "db1"."_1w"./.*/ GROUP BY time(1d), host returns in a reasonable time frame? How long does it take to execute?

[http] 2015/12/08 16:01:29 120.138.23.30 - - [08/Dec/2015:16:01:29 +1300] GET /query?q=SELECT+mean(value)+AS+%22value%22+FROM+%22chv2%22.%22_1w%22.%2F.*%2F+WHERE+time+%3E%3D+%272015-12-07T00%3A00%3A00Z%27+AND+time+%3C+%272015-12-08T00%3A00%3A00Z%27+GROUP+BY+time(1d)%2C+host&db=chv2 HTTP/1.1 200 10872 https://influxdb.sitehost.co.nz:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 fa6494ae-9d57-11e5-b28b-000000000000 272.816562ms


As I said I don't see any problem with the _52w CQ, it is only the CQ that runs every hour when I seem to be loosing data.

**Comment by beckettsean** [comment]
@jeanpralo the crazy thing is I see the exact opposite behavior in my long running test. My `1h` CQ doesn't miss a point, but my `1d` CQ consistently misses ~660 points a day. See https://github.com/influxdb/influxdb/issues/4803#issuecomment-164942746 for more details.

Here's my setup, with the `1h` created before the `1d`:

```

> show continuous queries
name: telegraf
--------------
name	query
hourfoo	CREATE CONTINUOUS QUERY hourfoo ON telegraf BEGIN SELECT count(value) AS "count" INTO "telegraf"."default"._cpu_usage_guest_hour FROM "telegraf"."default".cpu_usage_guest WHERE cpu = 'cpu-total' GROUP BY time(1h) END
dayfoo	CREATE CONTINUOUS QUERY dayfoo ON telegraf BEGIN SELECT count(value) AS "count" INTO "telegraf"."default"._cpu_usage_guest_day FROM "telegraf"."default".cpu_usage_guest WHERE cpu = 'cpu-total' GROUP BY time(1d) END
```

Can you share your `SHOW CONTINUOUS QUERIES` output? I'm wondering if order of insertion or execution is affecting which CQ "drops" points?

**Comment by scripter-v** [comment]
I encountered the same problem:
```
> select count(process_time) FROM "gate:inbox:requests" where time >= '2015-12-25 7:00:00' and time < '2015-12-25 7:05:00' and provider='prov_1' group by time(60s);
name: gate:inbox:requests
-------------------------
time                    count
1451026800000000000     40
1451026860000000000     58
1451026920000000000     40
1451026980000000000     53
1451027040000000000     46

> select * from "gate.inbox.reqs_count_by_provider.60s" where time >= '2015-12-25 7:00:00' and time < '2015-12-25 7:05:00' AND provider='prov_1';
name: gate.inbox.reqs_count_by_provider.60s
-------------------------------------------
time                    count   provider
1451026800000000000     40      prov_1
1451026860000000000     55      prov_1
1451026920000000000     40      prov_1
1451026980000000000     48      prov_1
1451027040000000000     46      prov_1
```
Data are written by fluentd every 10s.

CQ:
```
gate:inbox:reqs_count_by_provider       CREATE CONTINUOUS QUERY "gate:inbox:reqs_count_by_provider" ON smsonline BEGIN SELECT count(process_time) INTO smsonline."default"."gate.inbox.reqs_count_by_provider.60s" FROM smsonline."default"."gate:inbox:requests" GROUP BY time(1m), provider END
```

**Comment by jeanpralo** [comment]
@beckettsean  sorry about the long delay

I have upgraded my influxdb to 0.10 and here is the output of the show continuous queries:

```
_1h	"CREATE CONTINUOUS QUERY _1h ON chv2 BEGIN SELECT mean(value) AS value INTO chv2._1h.:MEASUREMENT FROM chv2."default"./.*/ GROUP BY time(1m), host END"
_1d	"CREATE CONTINUOUS QUERY _1d ON chv2 BEGIN SELECT mean(value) AS value INTO chv2._1d.:MEASUREMENT FROM chv2."default"./.*/ GROUP BY time(5m), host END"
_1w	"CREATE CONTINUOUS QUERY _1w ON chv2 BEGIN SELECT mean(value) AS value INTO chv2._1w.:MEASUREMENT FROM chv2."default"./.*/ GROUP BY time(30m), host END"
_4w	"CREATE CONTINUOUS QUERY _4w ON chv2 BEGIN SELECT mean(value) AS value INTO chv2._4w.:MEASUREMENT FROM chv2._1d./.*/ GROUP BY time(2h), host END"
_26w	"CREATE CONTINUOUS QUERY _26w ON chv2 BEGIN SELECT mean(value) AS value INTO chv2._26w.:MEASUREMENT FROM chv2._1d./.*/ GROUP BY time(12h), host END"
_52w	"CREATE CONTINUOUS QUERY _52w ON chv2 BEGIN SELECT mean(value) AS value INTO chv2._52w.:MEASUREMENT FROM chv2._1w./.*/ GROUP BY time(1d), host END"
```


I am really struggling at finding a pattern here, but from what it seems to happen:

- some CQ works ( _52w, _1w )
- the others stop from generating new datapoints and eventually my retention policies becomes empty ( _1h,  _1d, ...). 

What is strange is the fact that those CQ ( at least _1h and _1d ) were working when I first created them, also in the logs I can see they are being executed:

```
continuous_querier] 2016/02/22 06:50:00 executing continuous query _1h (2016-02-22 06:49:00 +1300 NZDT to 2016-02-22 06:50:00 +1300 NZDT)
[continuous_querier] 2016/02/22 06:50:01 executing continuous query _1d (2016-02-22 06:45:00 +1300 NZDT to 2016-02-22 06:50:00 +1300 NZDT)
[continuous_querier] 2016/02/22 06:51:00 executing continuous query _1h (2016-02-22 06:50:00 +1300 NZDT to 2016-02-22 06:51:00 +1300 NZDT)
[continuous_querier] 2016/02/22 06:52:00 executing continuous query _1h (2016-02-22 06:51:00 +1300 NZDT to 2016-02-22 06:52:00 +1300 NZDT)
[continuous_querier] 2016/02/22 06:53:00 executing continuous query _1h (2016-02-22 06:52:00 +1300 NZDT to 2016-02-22 06:53:00 +1300 NZDT)
[continuous_querier] 2016/02/22 06:54:00 executing continuous query _1h (2016-02-22 06:53:00 +1300 NZDT to 2016-02-22 06:54:00 +1300 NZDT)
[continuous_querier] 2016/02/22 06:55:00 executing continuous query _1h (2016-02-22 06:54:00 +1300 NZDT to 2016-02-22 06:55:00 +1300 NZDT)
[continuous_querier] 2016/02/22 06:55:01 executing continuous query _1d (2016-02-22 06:50:00 +1300 NZDT to 2016-02-22 06:55:00 +1300 NZDT)
```

Could it be that my server is not set in UTC  timezone ?

Cheers,

**Comment by jeanpralo** [comment]
@beckettsean 

Well something that I did not realize but my server was drifting and ntp was not configured.

Now that I fixed that issue I have data coming back again in my retention policies so I will probably wait an other couple of days to see if that fixed the problem.

**Comment by jeanpralo** [comment]
I have writtent this small and ugly script to test influxdb CQ and RP https://github.com/jeanpralo/influxdbcheck

**Comment by beckettsean** [comment]
The RESAMPLE...FOR syntax will address delayed points that arrive with older timestamps. I'm unable to repro any CQ data issues with the latest query engine and code.
