### ISSUE TITLE
Multiple operation within query was working in 0.9.4 but not in 0.9.5

### ISSUE THREAD

**Issue by manishjain002** [influxdata/influxdb#4935]
When I used to run on 0.9.4 : `select (max(kvah) - min(kvah)) from PWR where time > now() - 2h group by time(30m)`
I used to get the result,(though I did not check the accuracy of the result)
But in 0.9.5 it does not work at all.

Moreover I want to some more operation like this: 
`select (max(kvah) - min(kvah))/(max(kwh) - min(kwh)) from PWR where time > now() - 2h group by time(30m)`

Can we have some plugin architecture in order to support the operation we want to be executed on the server. Eg, I may wish to get Sin(angle) Or Sqrt(Vol) etc. If the user can write their own plugins for the operation, these plugins will be called if these operations are used in the query.

**Comment by beckettsean** [comment]
@manishjain002 there is already an open issue for custom functions: https://github.com/influxdb/influxdb/issues/68.

> But in 0.9.5 it does not work at all.

Can you give more details? There is no return? There is an error? 

Please copy/paste a `curl` or CLI session showing the issue.

**Comment by otoolep** [comment]
Can you try 0.9.6? We made multiple fixes in this area.

**Comment by jsternberg** [comment]
This works in 0.13 so I'm going to close this. Please try it and comment here if it doesn't work correctly. Thanks.
