### ISSUE TITLE
[0.9.5] Pre-installation script overwrites configuration if it already exists

### ISSUE THREAD

**Issue by aderumier** [influxdata/influxdb#4938]
Hi,

the current pre-install.sh
https://github.com/influxdb/influxdb/blob/master/scripts/pre-install.sh

always overwrite /etc/influxdb/influxdb.conf if an old /etc/opt/influxdb/influxdb.conf exist.

This script should test if /etc/opt/influxdb/influxdb.conf exist and /etc/influxdb/influxdb.conf don't exist before do the cp.

**Comment by rossmcdonald** [comment]
@aderumier Thank you for opening. I'll be adding a fix for this later today.

**Comment by rossmcdonald** [comment]
This was fixed with commit:

https://github.com/influxdata/influxdb/commit/560f691096083cce002097260bc1a205087a940e

Closing.
