### ISSUE TITLE
[0.9.4] "select * " query and certain other queries fail after sometime.

### ISSUE THREAD

**Issue by letitcrash** [influxdata/influxdb#4953]
I use influxdb 0.9.4 and we are facing issues with the queries through the UI as well as test client (influxdb-java). After a DB instance is created and after sometime using it , we face issues.

1) The "select * from " query which used to work early, starts to fail and errors out saying "need to have at least one field to query"
2) We have certain columns created with field value as a long timestamp (for eg: 1448855626000). We have queries which check this value for (>= or <=). Even this stop working and results in ZERO records. Can you please help us understanding the issue here.

**Comment by otoolep** [comment]
@letitcrash -- can you upgrade to 0.9.5.1? An enormous number of bug fixes went into 0.9.5 relative to 0.9.4. I suggest you then retest.

**Comment by beckettsean** [comment]
@letitcrash please share the actual queries and responses from the system. What you describe so far is too vague for us to investigate.

Upgrading to 0.9.5.1 is a good idea, also.

**Comment by letitcrash** [comment]
The queries which fail are as follows
1) select * from <mesurement1>
2) select sum(field1) from <measurement2> where tag1= 'tag1value' and tag2= 'tagvalue2' and tag3= 'tagvalue3' and tag4 <= 1449097779000 and tag5 >= 1448924979000 group by tag6.

Here tag4 and tag5 are Long type timestamps which is entered through the java client influxdb-java. 
The above queries worked earlier but suddenly stopped working. I am not sure what was the trigger that caused them not to work. I suspect it could be with the retention values that I set through the UI and when I use the retention policy through the .retentionPolicy("policy1") using the influxdb-java client. I have no clue beyond this which is causing the above issues. Can you please let us know the issue. I already opened another issue on influxdb-java (https://github.com/influxdb/influxdb-java/issues/125)

**Comment by beckettsean** [comment]
@letitcrash 

`select * from ` is an incomplete query. There is no way it can succeed. "Please give me all points from" is not an answerable question. What did you expect that to do? I am shocked you can even submit it, since I know the query parser will reject it:

```
> select * from 
ERR: error parsing query: found EOF, expected identifier at line 1, char 15
```

`select sum(field1) from where tag1= 'tag1value' and tag2= 'tagvalue2' and tag3= 'tagvalue3' and field1<= 1449097779000 and field2>= 1448924979000 group by tag6`

All tag keys and all tag values are strings. You cannot use `>=` and `<=` with string values. The query returns an empty set because the conditions are impossible to meet, therefore there are no matching points.

**Comment by letitcrash** [comment]
I think you misinterpreted my queries. My bad.

1) I mean select * from <measurement>. This stopped working.
2) The >= and <= are applied on the Long values which are Objects and not Strings. The tags take a map<String, String> and fields take the map<String, Object> 

Like I said above. These were working earlier and stopped suddenly.
Hope I made things clear

**Comment by beckettsean** [comment]
@letitcrash You are correct that markdown hid the `<measurement>` from your post. I recommend putting all code in backticks (`) so that markdown ignores it. I also recommend pasting in actual code rather than retyping, so that there is less ambiguity.

I did miss that your comparison operators are running on fields, that should be valid. 

However, there is no actual input or output in this issue for us to examine. Your description of the problem is not specific enough for us to investigate or attempt to reproduce. Can you please provide more actual hard data as to what is happening?

Please paste in the actual query in the CLI or with curl, returning the exact syntax of the error.

> These were working earlier and stopped suddenly.

Working for how long? On what version? What else happened around the time they stopped working? What's in the logs from when they stopped working? 

> I suspect it could be with the retention values that I set through the UI and when I use the retention policy through the .retentionPolicy("policy1") using the influxdb-java client.

What are the results of `SHOW RETENTION POLICIES`?

**Comment by letitcrash** [comment]
@beckettsean . The scenario is, we collect data from a measurement and persist that to a different measurement and then query on top of it. We pull from a measurement which has a retention policy of about an hour to the measurement which has a retention policy of 1 year. The 1 hour RP is default. While writing to the 1 year RP measurement, the data is not getting written just because it is not default. I wont be able to paste the exact query due to compliance issue, but the Query I gave below is exactly what we do except the field/tag names.

select sum(field1) from where tag1= 'tag1value' and tag2= 'tagvalue2' and tag3= 'tagvalue3' and field1<= 1449097779000 and field2>= 1448924979000 group by tag6.

I am now not sure if it is the DB issue or the influxdb-java client.

**Comment by letitcrash** [comment]
SHOW RETENTION POLICIES

name	       duration	           replicaN	     default
default		"0"			       1		       false
one_hour	        "1h0m0s"		       1		       true
one_day	        "24h0m0s"	       1		       false
one_month	"720h0m0s"	       1		       false
one_year	        "8760h0m0s"	       1		       false

I upgraded to the 0.9.5.1 version and the 2.0 version of the influxdb-java client. I still see the issue. 
I have 2 measurements with two different retention policies namely "one_hour" and "one_year" respectively. We are able to insert data into measurement 1 and the "select * from measurement1" works. Now we pull SOME data from measurement 1 through influxdb-java client and persist into measurement 2 which is on a different retention policy (one_year). when we do a select * from measurement 2, it returns ZERO records and while inserting there is no EXCEPTIONS being thrown. 

Now when I put the retention policy of one_hour to the measurement 2, it starts working. 
Here one_hour RP is the default.
Looks like all measurements should be on one RP and it should be the default policy. 

This is the issue. Can you please help resolving it ?? I am on the latest influxdb version 0.9.5.1 and latest influxdb-java client 2.0

**Comment by mnuessler** [comment]
@letitcrash You wrote above that you are using a query such `select * from measurement2` when trying to read data that is on a retention policy other than the default one. Did you just forget to mention it or did you miss to specify the retention policy when doing the query? Shouldn't you use a query like `select * from one_year.measurement2` in that case?

**Comment by letitcrash** [comment]
@mnuessler : I am updating the retention policy to one_year through the influxdb-java client before calling measurement 2. Do I still need to mention it as one_year.measurement2 before making the call ?? Why is that necessary ?

**Comment by mnuessler** [comment]
@letitcrash What exactly do you mean by "updating the retention policy to one_year through the influxdb-java client". Can you write what you are doing exactly?

**Comment by letitcrash** [comment]
Ok.
Retention policy, as far as I know is set for the data being inserted. Therefore I used influxDB java client to set the two RPs (one_hour & one_year) for the two measurement (M1 and M2) respectively. I used influxClient.retentionPolicy("one_hour") and influxClient.retentionPolicy("one_year") in code.

 ### For Insertion :
       ..1.  Default RP (one_hour) for M1 works.
       ..2.  RP (one_year) for M2 works when I use "one_year.M2" in the select query to see what is      inserted. But this was not the case with 0.9.4.1. Was this fixed in 0.9.5.1 ?? I am assuming all select queries to query data which was inserted with a NON-default RP should have the RP prefixed to the measurement name. Can you please clarify ?

**Comment by jsternberg** [comment]
I think this issue no longer exists in the newest version of InfluxDB. Please try it and comment here if it doesn't work for you. Thank you.

**Comment by letitcrash** [comment]
Looks like the issue is fixed in the later versions of influx. Please close it. Thanks for the support.
