### ISSUE TITLE
[0.9.4] CREATE DATABASE IF NOT EXISTS has inconsistent error responses in a cluster

### ISSUE THREAD

**Issue by kelchm** [influxdata/influxdb#4962]
Running a `CREATE DATABASE IF NOT EXISTS foo` query results in an error on two out of three servers in the cluster.  However, the output of `SHOW SERVERS` appears normal on *all three* servers in the cluster.  This seems to indicate to me that clustering has failed in some way.  We're currently running version 0.9.4.1.  While we plan to update, I'd like to determine the root cause here so we can take efforts to prevent it from happening in the future if possible.

```
#curl -G 'http://192.168.1.14:8086/query?pretty=true' --data-urlencode "db=internal" --data-urlencode "q=SHOW SERVERS"
{
    "results": [
        {
            "series": [
                {
                    "columns": [
                        "id",
                        "cluster_addr",
                        "raft"
                    ],
                    "values": [
                        [
                            1,
                            "192.168.1.13:8088",
                            true
                        ],
                        [
                            2,
                            "192.168.1.14:8088",
                            true
                        ],
                        [
                            3,
                            "192.168.1.15:8088",
                            true
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by beckettsean** [comment]
`CREATE DATABASE` is a statement that must pass through raft consensus. It is entirely possible for the cluster to respond to normal writes and queries, which do not pass through raft, and still be unable to create a database, if the raft group isn't fully functional.

Do you see the same errors for `CREATE USER` or `CREATE RETENTION POLICY`?

Are there any raft messages in the logs?

**Comment by otoolep** [comment]
Error handling in clusters has some significant fixes in 0.9.5. You should
definitely upgrade.

**Comment by kelchm** [comment]
It's worth mentioning that these servers were likely impacted by network issues immediately before this issue started.  

>Do you see the same errors for CREATE USER or CREATE RETENTION POLICY?

`CREATE USER` is working as expected.  I should note that I _can_ use `CREATE DATABASE` it's just that the results of running the query don't make sense.  To give a more detailed example:

**Query**: `SHOW DATABASES`
S1: `{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["test"]]}]}]}`
S2: `{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["test"]]}]}]}`
S3: `{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["test"]]}]}]}`

**Query**: `CREATE DATABASE IF NOT EXISTS test2`
S1: {"results":[{}]}

**Query**: `SHOW DATABASES`
S1: `{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["test"],["test2"]]}]}]}`
S2: `{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["test"],["test2"]]}]}]}`
S3: `{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["test"],["test2"]]}]}]}`

**Query**: `CREATE DATABASE IF NOT EXISTS test2`
S1: {"results":[{"error":"exec failed: apply: database already exists"}]}[
S2: {"results":[{"error":"exec failed: apply: database already exists"}]}
S3: {"results":[{}]}

Am I correct in saying that `CREATE DATABASE IF NOT EXISTS foo` should never return `exec failed: apply: database already exists`?

>Are there any raft messages in the logs?

No raft messages in the logs that I was able to find.  Is greping for 'raft' sufficient?

>Error handling in clusters has some significant fixes in 0.9.5. You should definitely upgrade.

I Figured as much.  I'll be upgrading, but I didn't want to proceed with upgrading before I understood the issue.

**Comment by beckettsean** [comment]
This sounds like a case where the `CREATE DATABASE IF NOT EXISTS` works for a single node but has issues in a cluster. 

Are the results consistent across the nodes if you do a simple `CREATE DATABASE test2` on each node?

**Comment by beckettsean** [comment]
@kelchm to clarify, nothing except the title of the issue suggests the cluster is unhealthy. Everything is working as expected, there's just an incorrect error response to the `CREATE DATABASE IF NOT EXISTS` statement from 2 of 3 nodes.

**Comment by kelchm** [comment]
>This sounds like a case where the CREATE DATABASE IF NOT EXISTS works for a single node but has issues in a cluster.

For what it's worth, it was definitely working correctly for me before today.

Here's the results of `CREATE DATABASE test2`:
S1: `{"results":[{"error":"exec failed: apply: database already exists"}]}`
S2: `{"results":[{"error":"exec failed: apply: database already exists"}]}`
S3: `{"results":[{"error":"database already exists"}]}`

**Comment by beckettsean** [comment]
@kelchm thanks for the update. That's very interesting that even with the simple case the error messages differ. 

`SHOW SERVERS` will indicate which node is the raft leader. I suspect it is `S3`. Can you verify?

**Comment by kelchm** [comment]
@beckettsean,

You can see the output I received from `SHOW SERVERS` in the original message.  I didn't have a column which indicated the raft leader -- is that something that is new in 0.9.5.x?  

I've since updated to 0.9.5.1.

**Comment by beckettsean** [comment]
Sorry, @kelchm I missed that. I'm so used to seeing it in CLI column format I didn't even recognize it in JSON.

It does seem that the `raft-leader` column is new with 0.9.5. 

After the update are you still seeing the same behavior with the `CREATE DATABASE` queries?

**Comment by kelchm** [comment]
@beckettsean, so far so good with 0.9.5.

**Comment by jsternberg** [comment]
Closing this since the last comment indicates it worked in the past and clustering is no longer supported in the open source version anyway.
