### ISSUE TITLE
Collectd parse error: Unsupported packet : please improve error message

### ISSUE THREAD

**Issue by ymettier** [influxdata/influxdb#4986]
Hello,

When you get the error message `[collectd] 2015/12/03 16:21:30 Collectd parse error: Unsupported packet`, it seems that there is more than one possible cause.

Possible known causes : 
- something wrong on `types.db` file (see discussion on https://groups.google.com/d/msgid/influxdb/b3cbd9ef-d497-4456-a570-f363898fe9e2%40googlegroups.com for more info)
- `MaxPacketSize` set to something else than 1452 (as described in https://github.com/influxdb/influxdb/blob/master/services/collectd/README.md#large-udp-packets)

Suggestion : could you improve the error message in order to help the user to find the cause and fix it ?

Regards,
Yves

**Comment by otoolep** [comment]
I'm open to suggestions, but our error messages must be short -- including every possible reason for the error in the logs is not possible.

**Comment by beckettsean** [comment]
@ymettier I don't KNOW that the types.db mismatch could lead to this. I was making an educated guess, and asking the user to verify there wasn't a mismatch.

Unless we have evidence that mis-matched types.db files leads to this error, I don't think we should update the error message just yet.

This seems more like a docs issue right now. I've updated https://github.com/influxdb/influxdb.com/issues/100 to include this when the page exists.

**Comment by ymettier** [comment]
Hello,

I opened this issue because @beckettsean asked for it.
My first thought was that the issue I was describing in https://groups.google.com/d/msgid/influxdb/b3cbd9ef-d497-4456-a570-f363898fe9e2%40googlegroups.com had already 2 issues (both fixed and closed), so no need to open a new issue for that.

However, Tanel has a problem that does shows the same message as my issue. And it is hard for him to fix it.

So I imagined that an error message would have 2 functions. 1/ alert on something wrong. This works already well. No issue. 2/ give clues on what is going wrong. And this issue #4986 would not exist if Sean and I had the same suggestions on how to fix the problem.

This is why I opened the issue. In my mind, there is no real problem. Only a talk about how to improve a little more InfluxDB and help users to fix their problems more easily and faster. Feel free to close it when you think that all has been said :)

Regards,
Yves

**Comment by octaviang** [comment]
Hello. I had the same problem, "unsupported packet". Debian 8.2, collectd 5.4.1, tutum/influxdb:0.9. The  issue was caused by the collectd config file. Inside the <Plugin network> I have a <Server> section. I specify the influxdb IP, port, user and pass. The issue was caused in my case by the presence of a "SecurityLevel Encrypt" line.

**Comment by gsueur** [comment]
Hi,
The same problem just occurred for me and it was definitely the same origin that @octaviang pointed out. Disabling the default SecurityLevelEncrypt Line immediately solved the issue. 
Best regards
Guillaume
