### ISSUE TITLE
[feature request] entry in SHOW STATS or SHOW DIAGNOSTICS for series cardinality

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4994]
Series cardinality has a significant effect on RAM usage, and second order effects on write performance. It's an important number to be able to know, and yet there is no reasonable way to get it from the database.

Given that the series cardinality = the number of series IDs in the in-RAM index, can we make it so that there's a single place to get this number?

@otoolep is there something already in the output that we can use to calculate it? I tried `select sum(seriesCreate) from _internal..shard` but that returns a number that seems way too high. I think each series is created for each shard, more or less, and I don't see any way to calculate the unique number of series.

**Comment by otoolep** [comment]
Hmmm, this will need some thinking.

**Comment by beckettsean** [comment]
Do we really not have a way to count the total index entries? Even if we just reported the max series ID, that gives an upper bound on the number of series, does it not? Or do we use randomly generated series IDs instead of monotonically increasing IDs?

**Comment by otoolep** [comment]
Sure we do -- we can just ask each shard, and combine at the querying node. Is that what you mean?

**Comment by benbjohnson** [comment]
@beckettsean I'm exposing some of the internals as databases as part of the new query engine. It shouldn't be difficult to expose a series count as well.

**Comment by beckettsean** [comment]
@otoolep yeah, I'm talking about a single, simple number: how many series exist in the system? If we want to get fancy we could group it by database.

@benbjohnson thanks! this will make it much easier to characterize customer systems.

**Comment by beckettsean** [comment]
Perhaps makes sense to return a `COUNT` for any `SHOW SERIES` query, as well.

**Comment by kfitzpatrick** [comment]
+1 to this idea. We could really use it in managed hosting to spot problems earlier.

**Comment by beckettsean** [comment]
`SELECT SUM(numSeries) FROM _internal.."database" WHERE time > now() - 10s` if the default `_internal` sample rate of `10s` is still in effect.

Otherwise, `SELECT LAST(numSeries) FROM _internal.."database" GROUP BY "database"`
