### ISSUE TITLE
write logging for UDP

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4995]
We can enable write-tracing for HTTP but not for UDP.

**Comment by jhhayden** [comment]
+1

**Comment by trent** [comment]
+1. very difficult to trouble shoot writing errors without any way to see the body...

**Comment by otoolep** [comment]
Don't forget there are full diagnostics and stats available for UDP:

https://github.com/influxdb/influxdb/blob/master/services/udp/service.go#L30

Execute `SHOW STATS` and `SHOW DIAGNOSTICS`.

**Comment by trent** [comment]
@beckettsean is there a way to enable write-tracing for HTTP now?
