### ISSUE TITLE
[0.9.5.1] SELECT returns both int and float for the same field

### ISSUE THREAD

**Issue by AxelVoitier** [influxdata/influxdb#5004]
Hello,

When doing a query like `SELECT value FROM test GROUP BY authority, path ORDER BY time DESC` I get this kind of results (both with curl and influxdb-python):
```
{
    "results": [
        {
            "series": [
                {
                    "name": "test",
                    "tags": {
                        "authority": "isac_cmd",
                        "path": "/test/test1"
                    },
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "2015-12-06T01:02:12.142Z",
                            36.5
                        ],
                        [
                            "2015-12-06T00:57:30.342Z",
                            36
                        ]
                    ]
                }
            ]
        }
    ]
}
```

What tickles me is that on one side, when writing, InfluxDB restricts me to send two points that do not have the same type for the same measurement. Fair enough, I avoid sending a mix of types (I pick float in this case, but another measurement could have another type).

But when I read data back, I get both floats and ints when the original float value happen to be an integer (in the "value" field in the example above).

It causes type error in case I load data, do something (or nothing) with it and write it again with a new timestamp.
For me measurements can have any type. So, I can't forcibly recast everything to one data type :S.

Cheers,
Axel

**Comment by mark-rushakoff** [comment]
FWIW, this is the default behavior of Go's JSON decoder: https://play.golang.org/p/kP9sa9yGwJ

```go
b, _ := json.Marshal(map[string]interface{}{
	"f10": 1.0,
	"f15": 1.5,
})
println(string(b)) // {"f10":1,"f15":1.5}
```

I'm having trouble finding a definitive source on it, but there's a lot of people online who say that JSON officially does not differentiate between ints and floats.  [This discussion on the IETF mailing list](https://www.ietf.org/mail-archive/web/json/current/msg01534.html) describes this issue as an "interpretation problem" rather than an "implementation problem."

**Comment by otoolep** [comment]
Thanks @mark-rushakoff

**Comment by jsternberg** [comment]
Confirming this is because JSON does not differentiate between a float or an integer. Closing this since there's nothing we can do about this.
