### ISSUE TITLE
[repo] Add support for Amazon Linux

### ISSUE THREAD

**Issue by skynet** [influxdata/influxdb#5035]
```
https://repos.influxdata.com/centos/latest/x86_64/stable/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
```

**Comment by otoolep** [comment]
@rossmcdonald

**Comment by rossmcdonald** [comment]
@skynet Your yum `$releasever` variable is set to `latest`, which is not valid for RHEL or CentOS. For example, the CentOS 6 URL should be:

https://repos.influxdata.com/centos/6/latest/x86_64/stable/repodata/repomd.xml

Are you using Amazon Linux or some other derivative of CentOS?

**Comment by skynet** [comment]
yes, using AWS Linux.

**Comment by rossmcdonald** [comment]
@skynet Okay, thank you for clarifying. We'll be adding support for Amazon Linux at some point, but the repo is currently only configured for RHEL and CentOS. For the time being, I believe you should be able to hard-code the URL to point to the `6` repo by modifying the InfluxDB repo settings like so:

```
[influxdb]
name = InfluxDB Repository
baseurl = https://repos.influxdata.com/centos/6/\$basearch/stable
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdb.key
```

I'll update this issue when official support is added.

**Comment by skynet** [comment]
Thanks @rossmcdonald. How about a beta channel, since I am already using 0.9.6-0.1.rc1

**Comment by rossmcdonald** [comment]
@skynet We do have an `unstable` channel, which is currently pointing to 0.9.6rc1. Just swap `stable` in the snippet above with `unstable`.

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
