### ISSUE TITLE
[feature request] Add function to interpolate series

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#5040]
We need an aggregate to fill in gaps in series if they exist. For example we have this:

``` sql
SELECT mean(value)
FROM cpu
WHERE time > now() - 24h
GROUP BY time(10m)
```

Assume that we have `host` as a tag on those series and they're collected every `10s`. That means we'd expect 60 values per host in each group by window. If we wanted to fill in any missing values we'd use the interpolate function:

``` sql
SELECT interpolate(value, 10s, mean).mean(value)
FROM cpu
WHERE time > now() - 24h
GROUP BY time(10m)
```

That specifies that we'd fill in any missing values in 10s intervals with whatever the mean is for the group by window. We could also use `previous` or a specific value as an interpolation value. For instance if we did:

``` sql
SELECT
  interpolate(value, 10s, 0).count(value)
FROM cpu
WHERE time > now() - 24h
GROUP BY time(10m)
```

We would just get `60 * number_of_hosts` in each `10m` group by window.

To support this kind of syntax we'd need to complete #4327 first. The other option is to have it at the trailing end as clause, but then that would make it apply to all fields in the select clause:

``` sql
SELECT mean(value)
FROM cpu
WHERE time > now() - 24h
GROUP BY time(10m)
INTERPOLATE(10s, previous)
```

**Comment by srikara** [comment]
+1

**Comment by samhatchett** [comment]
+1 
Interpolation is tricky - it will really depend on what you want to get out the other side. For my own cases, I like to have access to previous (we call it "step" resampling), linear (along the line connecting points before/after), and lowess (locally weighted least-squares fitted polynomial) which can be great for upsampling and also act to downsample/smooth while retaining more of the character of first-order discontinuities. Obviously the lowess interpolation needs more parameters like either a fixed time window or fixed number of points to fit.

**Comment by sslupsky** [comment]
+1

We also need to be able to resample a series.  For instance when you have two series sampled at different rates, it is necessary to resample one or both of them to the same rate so you can do additional signal processing on them.

**Comment by GeoffreyOnRails** [comment]
+1 for the need for interpolation. 

However, I see interpolation a little bit differently. For consistency with others functions, I'd prefer that the GROUP BY time would be with time(10s) if we want one point every 10seconds, and the way to interpolate (last-previous, mean over a 10 minute window) to be parameters of the INTERPOLATION function. Therefore, the interpolation function would return the interpolate if there is no point on the time group, and an aggregate given in parameter if there are 1 or more points on the time group.

Syntax would be : 
`SELECT interpolate(<field_key>,<function (if there are multiple points in time group)> FROM <measurement_name> WHERE <time_range> GROUP BY time(<time_interval>[,<offset_interval>])`

Suppose I have the following points : 

> time -> value
> 10:02 -> 3
> 10:09 -> 5
> 10:21 -> 7

```
SELECT interpolate(value, mean)
FROM cpu
WHERE time > now() - 24h
GROUP BY time(10m)
```

Would return : 

> For 10:00 -> 4 (doing the mean of 3 and 5 because we have multiple (2) values)
> For 10:10 -> 6 computing the interpolation at 10:15, which is 6.
> For 10:20 -> 7 (the mean of a single value)

Therefore, there is no need to chain functions and wait for function chaining in #4327 

Simple remark : for the second query you mentioned, I think adding a point with the mean of the grouping window and doing a mean will provide exactly the same result as just taking the mean. ;-)

**Comment by dstreppa** [comment]
+1

**Comment by sclausen** [comment]
+1
