### ISSUE TITLE
Continuous queries stop computing after some time

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#5041]
From the mailing list there's a report that CQs stop computing after some given time. Perhaps the goroutine is exiting?

https://groups.google.com/forum/#!topic/influxdb/KoYOw2KH9HU

@beckettsean, can you have someone on your team investigate?

**Comment by aaronknister** [comment]
If there's any additional data I can provide, please shoot me an e-mail to aaron.s.knister@nasa.gov.

**Comment by beckettsean** [comment]
@pauldix from the rest of the thread, this doesn't happen with the `bz1` engine, so I'm tagging this `tsm`. Do you still need one of my team to investigate?

**Comment by pauldix** [comment]
@beckettsean No need to investigate for the moment. I think there's some work we'll do for CQs that may resolve this, but that's a few weeks out.

**Comment by jsternberg** [comment]
@pauldix is this still an open issue with the work that's been done on CQs that's in the 0.10 beta?

**Comment by pauldix** [comment]
@jsternberg probably not. Closing.
