### ISSUE TITLE
Metastore error handling is brittle

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#5044]
The function `lookupError` at https://github.com/influxdb/influxdb/blob/v0.9.6-rc1/meta/errors.go#L121

is very brittle and now does not function. This is because it no longer looks up the right types.

**Comment by otoolep** [comment]
@corylanou

**Comment by corylanou** [comment]
Agreed.  We may need to institute concrete types so they can marshal real data about the error across json.  Will require further research for a fix.  Comparing strings is not ok.

**Comment by dgnorton** [comment]
I think we should delete `lookupError` and not attempt to marshal custom error types.  Add a specific function to the API instead and only marshal the error text.

**Comment by corylanou** [comment]
I agree that `lookupError` has to go away.  Especially as it isn't `cluster safe` anyway.  If the error happened on another node, this node won't even have the error regardless.

**Comment by jsternberg** [comment]
I think this code was removed at some point because I can't find the function any longer, so I'm going to close this issue as I don't think it's relevant any longer.
