### ISSUE TITLE
The data from one of measurments got completely mixed up

### ISSUE THREAD

**Issue by ZhukovAlexey** [influxdata/influxdb#5065]
Hello. I have an 0.9.5 version running on RedHat 7.1

I have a measurment GC_LOG which contains two tags: "jvm" and "server" and five fields "old_after_mb", "old_capacity_mb", "perm_after_mb", "perm_capacity_mb", "total_stw_sec"

As yo can see it is a java garbage collector log.

perm_capacity_mb is always 512
old_capacity_mb is always 6144

perm_capacity_mb is value between 290 and 310
old_capacity_mb is value between 1500 and 2500

This morning it was OK. but now field "old_after_mb" contains data from "perm_after_mb" field, field "total_stw_sec" contains data from "old_capacity_mb", etc.

All the data got mixed up.

Tha last value is the normal value as it should be. And all new values seems OK. The problem applies only to old data.

Before that I did "DROP MEASURMENT GC_LOG" from another database. Maybe it had an influence somehow.

![default](https://cloud.githubusercontent.com/assets/1679467/11686544/575f23f4-9e92-11e5-9775-67a4564e859b.png)

**Comment by otoolep** [comment]
Hmmm.

What engine are you running? Can you please check the queries through the CLI? It's important that we check that this isn't a UI issue.

**Comment by ZhukovAlexey** [comment]
I have a default fresh 0.9.5 installation without any changes in .conf file.

And unfortunately this is not an UI issue because I found it out from incorrect Grafana graphic which uses this measurement.

**Comment by otoolep** [comment]
Can you replicate using `curl`?

**Comment by beckettsean** [comment]
> Before that I did "DROP MEASURMENT GC_LOG" from another database. Maybe it had an influence somehow.

There's a known bug where dropping a measurement on one DB drops them on all DBs: https://github.com/influxdb/influxdb/issues/4303

**Comment by ZhukovAlexey** [comment]
When I tried to replicate it I got the same behaviour as in #4303 bug. I couldnt reproduce conditions when tha data getting mixed up. But if there's a known bug and it even fixed I think we can close this issue.
