### ISSUE TITLE
[0.9.6] CREATE DATABASE [...] new-rp-name  should throw error if NAME missing

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#5077]
As expected, when I create a new database, specify a new retention policy, and don't include a name for the new retention policy, the rp is called `default`:
```sh
> CREATE DATABASE santa WITH DURATION 3d REPLICATION 1
> SHOW RETENTION POLICIES ON santa
name	 duration	 replicaN	default
default	 72h0m0s     1		    true
```

Unexpectedly, when I do the same thing and include a name for the rp, the rp is still called `default`:
```sh
> DROP DATABASE santa
> CREATE DATABASE santa WITH DURATION 3d REPLICATION 1 presents
> SHOW RETENTION POLICIES ON santa
name	duration	replicaN	default
default	72h0m0s		1		    true
```

**Comment by otoolep** [comment]
Looks like a bug. Thanks @rkuchan 

@pires ?

**Comment by otoolep** [comment]
@rkuchan - actually I think you need the keyword NAME.

**Comment by rkuchan** [comment]
Oops, yes. Misread the syntax. Sorry!

**Comment by otoolep** [comment]
@rkuchan -- that command should have still thrown a parser error.

@pires -- any chance you could take a look why?

**Comment by pires** [comment]
The syntax was implemented as follows:
```
CREATE DATABASE [IF NOT EXISTS] NOAA_water_database
  [WITH
    [DURATION 24hr]
    [REPLICATION 1]
    [NAME something_other_than_default]
  ]
```

`NAME` must be present, otherwise the policy will be named `default`.

Anything beyond that, like the identifier `presents` is simply ignored. Should it be otherwise @otoolep?

**Comment by otoolep** [comment]
@pires - I think the parsing code could be enhanced to see if there is another token, and if there is one AND it is not NAME, an error should be thrown.

**Comment by otoolep** [comment]
In other words, let's try to help people not fall in this trap.

**Comment by pires** [comment]
@otoolep how would we deal with `CREATE DATABASE santa WITH presents`? I understand what you want, I just don't see a way of ignoring the `NAME` attribute (not the value) when using `WITH`. Or should we drop `WITH`?

**Comment by otoolep** [comment]
I don't follow you.

`CREATE DATABASE santa WITH DURATION 3d REPLICATION 1 presents`

has a trailing string after the replication value. It is not the token `NAME` i.e. the command should be:

`CREATE DATABASE santa WITH DURATION 3d REPLICATION 1 NAME presents`

why can't we detect this problem and return an error to the user, telling them that we saw something, but it wasn't the token `NAME`.

To be clear, this command should be fine:

`CREATE DATABASE santa WITH DURATION 3d REPLICATION 1`

**Comment by pires** [comment]
@otoolep it seems I misunderstood. I was under the impression you wanted to enable defining a replication policy name without` NAME.

I will look into this on Saturday and report back.

**Comment by pires** [comment]
@otoolep so to be clear:

The following is fine:
> CREATE DATABASE santa WITH DURATION 3d REPLICATION 1

Now, the following:
> CREATE DATABASE santa WITH DURATION 3d REPLICATION 1 presents

Ignores `presents`.

So this begs the question, where in the code are you validating arguments in excess? Can't seem to find similar use-cases.

**Comment by otoolep** [comment]
Can't the code check for another token after `1` and if it's not `NAME` throw an error?

**Comment by pires** [comment]
@otoolep yes, it can throw a parser error. I was just looking for another place where this happens so I could follow any existing pattern.
