### ISSUE TITLE
Restoring from snapshot/ Empty db/ Hangs on [metastore] 2015/12/10 22:28:33 temporary accept error: listener closing...

### ISSUE THREAD

**Issue by shjohnson** [influxdata/influxdb#5091]
CentOS release 6.7 (Final)
InfluxDB 0.9.5.1

Process:-
```wget http://influxdb.s3.amazonaws.com/influxdb-0.9.5.1-1.x86_64.rpm ```
``` sudo yum localinstall influxdb-0.9.5.1-1.x86_64.rpm ```

Alter config to allow snapshots..(although when i did this without it still seemed to work?)

Created a DB
Created retention policy
Created some fake data
Check data is present
Create snapshot:-
``` 
influxd backup /tmp/mysnapshot-06
 2015/12/10 22:27:31 influxdb backup
 2015/12/10 22:27:31 backup complete 
```
Deleted the ```db_name```
Stopped influx
Restored influx:-
```
influxd restore -config /etc/influxdb/influxdb.conf /tmp/mysnapshot-06
unpacking: _internal/monitor/1 (516096 bytes)
unpacking: meta (200 bytes)
[metastore] 2015/12/10 22:28:31 Using data dir: /var/lib/influxdb/meta
[metastore] 2015/12/10 22:28:31 Node at 127.0.0.1:8088 [Follower]
[metastore] 2015/12/10 22:28:33 Node at 127.0.0.1:8088 [Leader]. peers=[]
[metastore] 2015/12/10 22:28:33 Created local node: id=1, host=127.0.0.1:8088
[metastore] 2015/12/10 22:28:33 spun up monitoring for 1
[metastore] 2015/12/10 22:28:33 temporary accept error: listener closing
[metastore] 2015/12/10 22:28:33 temporary accept error: listener closing
```
While waiting for this i managed to restart influx successfully and noticed the db had been created but with no data?

Has this been solved as found this issue below:-

 [[0.9.5-nightly] Restore functionality hangs forever](https://github.com/influxdb/influxdb/issues/4806)

**Comment by oiooj** [comment]
fixed in 0.9.6 #4918
