### ISSUE TITLE
[0.9.6] Derivative (max) & math of max

### ISSUE THREAD

**Issue by discoduck2x** [influxdata/influxdb#5093]
Having some issues visualizing a "rate" measurment (cisco interface in/out octets pulled by snmp).
Using grafana - already posted this Q there but got pointed to you guys.

If i do a derivative with mean: 
SELECT 8 * derivative(mean("value"),1s) AS "value" FROM "ifHCInOctets" WHERE "column" = 'Gi1/11' AND $timeFilter GROUP BY time($interval) fill(none)
..im getting data allright, but as i zoom out timewise it "shrinks" the value - expected i guess as a mean over time , fine.

Problem is that I really want to see the MAX value over any timebucket so trying to use derivative(max(value)) .. but that faces the same issue,, as i expand the timewindow the max value shrinks... which it really shouldnt ? Or am i thinking the wrong way round here ?

Also, i cannot do math on derivative(max) ,, , i want to convert those bytes to bits.

Saw alot of old derivative issues but cant see if this is already a dupe or not
https://github.com/influxdb/influxdb/issues/4849
https://github.com/influxdb/influxdb/issues/4312

**Comment by etlweather** [comment]
Oh, just noticed this is a few months old! I am also unable to convert the bytes to bits...

This works:
```
SELECT non_negative_derivative(max("ifHCInOctets"), 1s) FROM "ifHCInOctets" WHERE "host" = '$switch' AND "instance" = '$port' AND $timeFilter GROUP BY time($interval) fill(none)
```

But this doesn't:
```
SELECT 8 * non_negative_derivative(max("ifHCInOctets"), 1s) FROM "ifHCInOctets" WHERE "host" = '$switch' AND "instance" = '$port' AND $timeFilter GROUP BY time($interval) fill(none)
```

**Comment by etlweather** [comment]
But this works:
```
SELECT 8 * non_negative_derivative(mean("ifHCInOctets"), 1s) FROM "ifHCInOctets" WHERE "host" = '$switch' AND "instance" = '$port' AND $timeFilter GROUP BY time($interval) fill(none)
```

Only thing is `mean` isn't quite right.

**Comment by jwilder** [comment]
Closing this since the query engine has changed substantially from `0.9.6` and this should be working now.  Please open a new issue if this is still occurring in the latest stable release.
