### ISSUE TITLE
Meta - Refactor Service

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#5099]
The meta `service` represents the http endpoint that a meta `client` will connect to and make `consensus` requests.  The meta service will currently have a raft node embedded within it, but would allow us to at a future point replace it with something else.

### Design Requirements

- Use internal index to indicate changes to the store.  Not the raft index like the current implementation.
- HTTP api to CP store
  - Use HTTP redirect to find the current leader when making requests.
- CP store currently houses the following:
  - Database Info
    - Retention Policy Info
      - Shard Group Info
        - Shard Info
    - Continuous Queries
  - User Info
- Support a `meta only node` to allow for running a meta service cluster on dedicated resources not shared with the data nodes.
- Update shard calculations to only use data nodes for distribution, not all nodes.
- Update retention policy validation to prevent replication factor from being larger than data nodes, not all nodes.

### Architecture Overview
 
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                ┃
┃  ┌───────────────────────────┐ ┃
┃  │   ┌──────────────────┐    │ ┃
┃  │   │       Raft       │    │ ┃
┃  │   │                  │    │ ┃
┃  │   └──────────────────┘    │ ┃
┃  │                           │ ┃
┃  │       Meta Service        │ ┃
┃  └─────────────▲─────────────┘ ┃
┃                │               ┃
┃                │  HTTP         ┃
┃                └──────┐        ┃
┃  ┌────────────────────┼──────┐ ┃
┃  │                    │      │ ┃
┃  │                    ▼      │ ┃
┃  │ ┌────────┐    ┌─────────┐ │ ┃
┃  │ │        │    │         │ │ ┃
┃  │ │        │    │         │ │ ┃
┃  │ │  Meta  │    │  Meta   │ │ ┃
┃  │ │ Cache  │◀──▶│ Client  │ │ ┃
┃  │ │        │    │         │ │ ┃
┃  │ │        │    │         │ │ ┃
┃  │ │        │    │         │ │ ┃
┃  │ └────────┘    └─────────┘ │ ┃
┃  │                    ▲      │ ┃
┃  │             ┌──────┘      │ ┃
┃  │             ▼             │ ┃
┃  │  ┌─────────────────────┐  │ ┃
┃  │  │     Data Engine     │  │ ┃
┃  │  │                     │  │ ┃
┃  │  └─────────────────────┘  │ ┃
┃  │       Data Service        │ ┃
┃  └───────────────────────────┘ ┃
┃                                ┃
┃         InfluxDB Node          ┃
┃                                ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

related: #5097 #5098

**Comment by toddboom** [comment]
This will be completed in the upcoming v0.10.0 release.
