### ISSUE TITLE
Feature request : configuration option to enable/disable core file

### ISSUE THREAD

**Issue by ymettier** [influxdata/influxdb#5107]
Hello,

I crashed InfluxDB. Here is the last line in the log file :
```
Killed (core dumped)
```

I wanted to help and provide information about the core file, but there is no core file.

```
$ ulimit -c
0
```

### Feature request :
Could you provide a mechanism that would allow to configure ulimit in order to have a core file for those who want to, and to disable it for those who do not want to fill their disk with core files ?

This could be an option in `/etc/default/influxdb`, exactly the same as you do with `OPEN_FILE_LIMIT` in `/usr/lib/influxdb/scripts/init.sh`.

**Comment by otoolep** [comment]
@ymettier -- why not do exactly what you say, and add the directive yourself to `/etc/default/influxdb`? That is what that file is for -- to allow users to customize settings. Am I missing something?

**Comment by ymettier** [comment]
Hello,

Yes, I could write a `ulimit -c unlimited` in `/etc/default/influxdb`.

I did not think about it because I usually use `/etc/default/*` files to set environment vars like `OPEN_FILE_LIMIT`. And because you provided a mechanism for `ulimit -n $OPEN_FILE_LIMIT`, I thought you could provide one for `ulimit -c`.

That's OK for me. You can close this ticket if you think that all was said. Thanks for the answer.

**Comment by otoolep** [comment]
Makes sense @ymettier -- just wanted to be sure I understood the request. I agree it's clearest to use a variable.
