### ISSUE TITLE
Query with order by time DESC fail with WAL

### ISSUE THREAD

**Issue by PierreF** [influxdata/influxdb#5108]
When doing a query like "SELECT value FROM cpu_load_short ORDER BY time DESC LIMIT 1", I don't always get the last value.

From what I see, I get the last value from data dir, not the one in WAL. There is a special case, when data dir is empty, WAL is effectively used.

To reproduce this issue, I just need to write fast enough to keep data in WAL:

1) rm -fr ~/.influxdb
2) ./usr/bin/influxd (I used standalone binary, 0.9.6, 0.9.6.1 and 0.10.0-nightly-4f65dc0)
3) Run the following
```
count=1
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

while true; do curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary "cpu_load_short,host=server01,region=us-west value=$count ${count}000000000"; echo; sleep 0.1;count=$(($count + 1));done
```
4) Keep the loop running, "SELECT value FROM cpu_load_short ORDER BY time DESC LIMIT 1" will return the last entry (we only write in WAL)
5) Stop the loop for about 5 seconds, WAL get flushed. Restart the loop, now the previous select return the last value flushed, not the one in WAL.

I wasn't able to test TSM1 storage because I wasn't able to get WAL data being flushed with TSM1 storage.

**Comment by aaliddell** [comment]
Also seeing this issue on the 0.9.4.2 Windows build

**Comment by aaliddell** [comment]
As a follow up to this: removing the LIMIT 1 from the query shows the records sorted as expected, with the exception of the first record. This is the record we are seeing when the LIMIT 1 is in place and is not sorted chronologically, hence giving the anomalous results explained above. When running the sort, is the first record somehow getting missed?

**Comment by jsternberg** [comment]
Please try this again with the latest version of InfluxDB and the TSM engine. I'm going to close this since I don't think it's an issue any longer, but please comment if you find this is still happening and I'll reopen the issue. Thanks.
