### ISSUE TITLE
Put [snapshot] section into default configuration file

### ISSUE THREAD

**Issue by zstyblik** [influxdata/influxdb#5109]
Hello,

please, can you add `[snapshot]` section into default/sample configuration file[1]?

```
[snapshot]
enabled = true
```

Commented or uncommented, just to be aware such thing exists.

Thank you.

[1] https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml

**Comment by otoolep** [comment]
Why do you think it's a valid config block @zstyblik ?It's no longer output by the command `influxd config`.

**Comment by zstyblik** [comment]
> Why do you think it's a valid config block @zstyblik ?It's no longer output by the command influxd config.

Because [influxdb v0.9 documentation](https://influxdb.com/docs/v0.9/administration/backup_and_restore.html) says so? :)

**Comment by otoolep** [comment]
Ok. We need to check, I wonder if that doc is out of date.

**Comment by zstyblik** [comment]
@otoolep - sure. I mean, all kidding aside, there are issue(s), eg. https://github.com/influxdb/influxdb/issues/3923,  here at github which reference this pieces of config/attribute/switch. That's how I came by to it, more or less.

**Comment by beckettsean** [comment]
made https://github.com/influxdb/docs.influxdata.com/pull/98 to address the docs for now

**Comment by jsternberg** [comment]
Closing this because of the documentation change.
