### ISSUE TITLE
[0.9.6.1] DROP MEASUREMENT - out of memory

### ISSUE THREAD

**Issue by OndroNR** [influxdata/influxdb#5110]
Hi, we are running InfluxDB 0.9.6 on docker (ubuntu 14.04 host). When we try to drop whole measurement (~500 000 points, 20 tag keys), InfluxDB consumes all available memory (8GB machine) and crashes. We have tried this on two measurements with same result. Log https://gist.github.com/OndroNR/6e0efc38c3260df94a7a

**Comment by seyoonhan** [comment]
I experienced same thing on 0.9.5.
When I dropped measurement influxDB stuck and unresponsive for a while.

**Comment by RadoBuransky** [comment]
+1

**Comment by OndroNR** [comment]
Same result with 0.9.6.1. It is also crashing on queries, which worked fine with 0.9.4.2.

**Comment by OndroNR** [comment]
It is possible we have too many series. We are already working on reducing tag set. Upgrade to 16GB RAM made possible dropping measurements.

**Comment by beckettsean** [comment]
@kostasb looks related to ZD1943, might give you some info to tackle that ticket.

**Comment by jwilder** [comment]
This code no longer exists as it has been replaced by the TSM engine.  Please log a new issue if the problem still exists in the latest release.
