### ISSUE TITLE
Aggregation doesn't work correctly when time series crosses 0 epoch time

### ISSUE THREAD

**Issue by peetonn** [influxdata/influxdb#5113]
With the data points like this (first 10 points printed):

<pre>
select * from data limit 10
name: data 
---------- 
time data_type frame frame_type segment value 
0 data 85 key 0 1 
794000000 data 86 key 0 1 
797000000 data 86 key 2 1 
798000000 parity 86 key 0 1 
798000000 data 86 key 4 1
1203000000 data 2494 delta 0 1 
1207000000 data 2495 delta 0 1 
1208000000 data 2496 delta 0 1 
1212000000 parity 2494 delta 1 1 
1212000000 data 2497 delta 0 1
</pre>

Aggregation query does not work correctly:

<pre>
select count(value) from data where time >= 0 and time <= 500s group by time(1s)
name: data
----------
time count
0 1577
</pre>

Expected: data will be grouped by 1-second intervals.

**Comment by beckettsean** [comment]
This is a special case of https://github.com/influxdb/influxdb/issues/2703. Leaving this open so we make sure to handle both the raw and aggregated query results properly.
