### ISSUE TITLE
:MEASUREMENT backreference should allow for arbitrary pre- and -postfixes on the generated measurement name

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#5128]
Currently a CQ like this is valid:

```
CREATE CONTINUOUS QUERY foo ON mydb BEGIN
  SELECT MEAN(value) INTO new_rp.:MEASUREMENT FROM foo GROUP BY time(1m)
END
```

but this CQ is not valid:

```
CREATE CONTINUOUS QUERY foo ON mydb BEGIN
  SELECT MEAN(value) INTO new_rp._1m_:MEASUREMENT FROM foo GROUP BY time(1m)
END
```

Basically, the measurement into which the data is written must have the same name as the original measurement. There is no way to add a string to the beginning or end of the backreference.

**Comment by zachaller** [comment]
+1

**Comment by zstyblik** [comment]
@beckettsean I was wondering about this one yesterday. :)

**Comment by cyberflow** [comment]
+1
