### ISSUE TITLE
Go HeapAlloc slowing increasing

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#5144]
During 500K EPS write load of the TSM engine, internal metrics show the HeapAlloc profile slowly increasing. There was also query load on the system during this time, but not that significant.

See attached graph. This was with https://github.com/influxdb/influxdb/commit/a6cdb5229d2bf183ca9ee29a50ef4e061dd981ab

**Comment by otoolep** [comment]
![heap](https://cloud.githubusercontent.com/assets/536312/11849170/55065ab6-a3db-11e5-9737-310ac097b171.png)

**Comment by otoolep** [comment]
cc @jwilder @pauldix @mjdesa 

@mjdesa -- we need to get the Go runtime stats into Grafana for our test beds. Telegraf has an outstanding PR by @mark-rushakoff that will help.

**Comment by otoolep** [comment]
37K queries had been executed in total on this node.

**Comment by jwilder** [comment]
Would be good to run a test w/ `b1` or `bz1` to see if we see the same profile.

**Comment by mjdesa** [comment]
Added a task to track go runtime stats into Grafana to Tracker.

**Comment by pauldix** [comment]
Any chance the heap growth is tied to the growing number of tsm files? All of those indexes are kept on the heap.

Would be good to run a test at this scale (5M unique series posted every 10s) without queries and see if the heap growth changes.

**Comment by otoolep** [comment]
Yeah, @pauldix -- that sounds feasible. Heap usage growth was pretty slow, we just noticed it and so I thought we should capture it. It the write load was taken off, perhaps it would flatline.

**Comment by mark-rushakoff** [comment]
The PR that @otoolep mentioned is https://github.com/influxdb/telegraf/pull/449. Not merged yet but I think we're close. It should work fine now if you need it and you're willing to build telegraf from that branch.

**Comment by jwilder** [comment]
Tests run #4977 indicate this issue is resolved.
