### ISSUE TITLE
[0.9.6.1] Nth percentile for derivative series

### ISSUE THREAD

**Issue by enigmapsi** [influxdata/influxdb#5150]
Hi,

It seems that currently calculating Nth percentile for a `DERIVATIVE()` series is not possible, as `PERCENTILE()` only supports one `field_key` as an argument, and not another function.

It would be really useful to have `PERCENTILE()` accept a function as an argument, e.g. `SELECT percentile(derivative(mean(value), 1s), 95) FROM [...]`

**Use case**: calculating Nth percentile of bandwidth used (in bits/sec) when the database actually stores COUNTER type data, i.e. the bytes transferred since a device is powered up (this is what SNMP pollers usually get from network devices). Calculating the Nth percentile of the COUNTER type data is useless.

This is probably a feature request, but I think it's quite essential for a time-series database. If there is a way to do this currently, please let me know.

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by mrmike1** [comment]
The query SELECT percentile(derivative(mean(value), 1s), 95) FROM xx where xx

gives me the error

{
  "error": "error parsing query: expected field argument in percentile()",
  "message": "error parsing query: expected field argument in percentile()"
}

Im trying to calculate 95th percentile for bandwidth

**Comment by beckettsean** [comment]
@mrmike1 `PERCENTILE()` does not support nested functions: https://docs.influxdata.com/influxdb/v1.0/troubleshooting/frequently-asked-questions/#which-influxql-functions-support-nesting

**Comment by mrmike1** [comment]
Why are people trying it?

https://github.com/influxdata/influxdb/issues/6428

**Comment by beckettsean** [comment]
@mrmike1 presumably for the same reason you did, because they want it to work. 

If you read that issue and the associated PR, the fix was that running a query with nested functions inside `PERCENTILE()` no longer panics the database. Instead, it gives the correct error.
