### ISSUE TITLE
[0.9.6] Query with where filter by field value and tag output incorrect results

### ISSUE THREAD

**Issue by spamik** [influxdata/influxdb#5152]
Simple example, I push these values to measurement (two fields, one tag with two values):

bugtest,varname=a vala=1000
bugtest,varname=a vala=2000
bugtest,varname=a vala=200000
bugtest,varname=b valb=500
bugtest,varname=b valb=600
bugtest,varname=b valb=700

Now, these queries runs OK:
select * from bugtest where varname <> 'a' (results only 3 rows with varname=b)
select * from bugtest where vala < 10000 (results only 2 rows with varname=a)

Now I want to combine it to get all varname=b and varname=a where vala < 10000:
select * from bugtest where vala < 10000 or varname <> 'a'

I believe that this should work (returns 5 rows) but i gets me all 6 rows in measurement. I believe that this is bug because I think, that row varname=a vala=200000 shouldn't pass this condition. Tested on v0.9.6.

**Comment by jackzampolin** [comment]
Reproduced:

```
> create database mydb
> use mydb
Using database mydb
> insert bugtest,varname=a vala=1000
> insert bugtest,varname=a vala=2000
> insert bugtest,varname=a vala=200000
> insert bugtest,varname=b vala=500
> insert bugtest,varname=b vala=600
> insert bugtest,varname=b vala=700
> select * from bugtest where varname <> 'a'
name: bugtest
-------------
time			vala	varname
1450476630737016697	500	b
1450476635641078835	600	b
1450476638321128276	700	b

> select * from bugtest where vala < 10000
name: bugtest
-------------
time			vala	varname
1450476599190718038	1000	a
1450476605648166045	2000	a
1450476630737016697	500	b
1450476635641078835	600	b
1450476638321128276	700	b

> select * from bugtest where vala < 10000 or varname <> 'a'
name: bugtest
-------------
time			vala	varname
1450476599190718038	1000	a
1450476605648166045	2000	a
1450476622072554912	200000	a
1450476630737016697	500	b
1450476635641078835	600	b
1450476638321128276	700	b
```

**Comment by beckettsean** [comment]
Possibly related to https://github.com/influxdb/influxdb/issues/4917, although not an exact duplicate, since the `vala=200000 varname=a` point shouldn't match either OR clause.
