### ISSUE TITLE
[0.9.6.1] metadata incorrectly persisted when points rejected due to field type conflict

### ISSUE THREAD

**Issue by bigKS** [influxdata/influxdb#5155]
Hi,

I'm getting no data returned (tried CLI, and direct GET using CURL and the golang v2 client api... all 3 methods) even though I wrote points/series into a db (see the "show series" output for proof? that there was data written):

```
[ksengal@csdev-ksengal influxdb]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
%> show databases
name: databases
---------------
name
systemstats
cs

%> use cs
Using database cs
%> show series
name: cpu_usage
---------------
_key            cpu
cpu_usage,cpu=cpu-total cpu-total


name: fakeMeasurementName
-------------------------
_key                                        fakeTagLabel1   fakeTagLabel2
fakeMeasurementName,fakeTagLabel1=fakeTagValue1,fakeTagLabel2=fakeTagValue2 fakeTagValue1   fakeTagValue2

%> select * from fakeMeasurementName
%>
```

CurlGET:

```
[ksengal@csdev-ksengal influxdb]$ curl -G 'http://localhost:8086/query' --data-urlencode "db=cs" --data-urlencode "q=SELECT * FROM fakeMeasurement"
{"results":[{}]}
```

How do I debug this further?  As far as I know, points without fields are impossible to create?

HOW did I write this into DB? using the "v2" golang client api... part of the code:

```
106     // specify tags and fields to create a point
107     tags := map[string]string{"fakeTagLabel1": "fakeTagValue1", "fakeTagLabel2": "fakeTagValue2"}
108     fields := map[string]interface{}{
109         "fakeFieldLabel1": 2032.23,
110         "fakeFieldLabel2": 23234.2,
111     }
112     point, err := influx.NewPoint("fakeMeasurementName", tags, fields, time.Now())

116 
117     // create second point, which only differs in the value of the fields
118     fields = map[string]interface{}{
119         "fakeFieldLabel1": 1.2,
120         "fakeFieldLabel2": 2.3,
121     }
122     point2, err := influx.NewPoint("fakeMeasurementName", tags, fields, time.Now())
```

(Above creates 2 points, which then you add to a "batch" and write via an HTTPclient ).
( Yes, in real code I'm checking "err" returned from all methods against nil )

Any special debug commands and such that I can use to investigate this deeper?

**Comment by trent** [comment]
I'm seeing this same behavior when creating points in 0.9.6.1.  I POST data and the series is created, but the data does not exist.  I've checked logs and the POST was received, but I can't find any way to see the content of the POST to know if the data was accurate.  That said, the client shows the expected data was posted correctly.

**Comment by otoolep** [comment]
I suggest two approaches, or it will be slow for us to debug this:

- repro your problem using just `curl`, as described here: https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#bug-reports
- provide the entire Go program you have wrote as a gist (or a simpler one showing the same problem), and we can take a look. Debugging a snippet of Go is not really something that we can do.

**Comment by beckettsean** [comment]
@bigKS in the CLI example, you show that the `fakeMeasurementName` measurement exists. In the `curl` example, you query the `fakeMeasurement` measurement. They aren't the same thing. Even if that's just a typo, that's an example of why re-typed data is nearly useless for syntax debugging. Please provide pure copy/paste repro steps if you can.

**Comment by beckettsean** [comment]
@bigKS is it possible your inserted point has a timestamp in the future? https://docs.influxdata.com/influxdb/v0.9/troubleshooting/frequently_encountered_issues/#querying-after-now

**Comment by bigKS** [comment]
@beckettsean,  yes you are right, my cli output above does not really show the problem (though the curl does).  

But that was just a copy paste mistake.  Here I've encountered the situation again.
After writing 2 batched points, I cannot retrieve data:

[ksengal@csdev-ksengal influxdb]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
> use cs
Using database cs
> show series
name: cpu_usage
---------------
_key			cpu
cpu_usage,cpu=cpu-total	cpu-total

> select * from cpu_usage
> 
> 
> 
As for the possibility of timestamp in future, that is not true because influxdb and the go program I'm using to write to it are running on same machine, and I'm writing with time.Now() as the timestamps.

**Comment by bigKS** [comment]
Ok while writing a program to deliver to this thread that can reproduce the issue, I figured out the problem.

It's a mixture of things:
1) [DOC ISSUE / MY FAULT]  Notice in the golang client api for the main Write function here: https://godoc.org/github.com/influxdb/influxdb/client/v2#Client
and here: https://godoc.org/github.com/influxdb/influxdb/client/v2#example-Client--Write1000

It shows things as if Write does not return any error signal (and this was "okay" with me I was assuming it was really hard to tell if a real error happened on a Write - e.g., UDP write drops on Influx 0.8).

Also, there really is no documentation for the Write method there in that page.
 
(Note: I just decided to go into the actual client code to check if Write did return error, and it does, so I used it now... )

2) [There is still a problem beyond DOC issue, which is what confused me] So the problem I was seeing and can be reproduced like this:
A) Write a batch of 2 points into same database, with measurement name, tags, fields all the same (and timestamp as current timestamp in nanocseconds), except vary one field like this:

POINT: LineProtocolString=<TABLENAME,FAKETAG1=F1,FAKETAG2=F2 FIELD1=123i,FIELD2=321i 1450582360991409151>
POINT: LineProtocolString=<TABLENAME,FAKETAG1=F1,FAKETAG2=F2 FIELD1=123i,FIELD2=12.3 1450582360991447782>

( Notice above, FIELD2 is a float in second point... and I'm printing the Point object using Println and I notice the "i" on the fields that are inferred as integer ).

Then query "show tags" , "show fields" and "show series" :+1: 

Response when doing command <SHOW TAGS> is <&{[] <nil>}>
Response when doing command <SHOW FIELDS> is <&{[] <nil>}>
Response when doing command <SHOW SERIES> is <&{[{[{TABLENAME map[] [_key FAKETAG1 FAKETAG2] [[TABLENAME,FAKETAG1=F1,FAKETAG2=F2 F1 F2]] <nil>}] <nil>}] <nil>}>
Response when doing command <SELECT * FROM TABLENAME> is <&{[{[] <nil>}] <nil>}>


(( Notice, "show series" is returning the series as if it was created ... even though the write to an empty/new database apparently failed )).


Btw, now I'm printing error returned in these cases, and this is the error message:
2015/12/19 22:31:38 write failed: field type conflict

**Comment by beckettsean** [comment]
@bigKS I think this issue has boiled down to the following:

If there is a field type conflict in a single batch of points, the metadata (tag set) for both points persists, even though one of the points is rejected due to the type conflict.

A simple file with two points that have a field type mismatch:

```
root@sean-0:~# cat points.influx 
fieldconflict value=1.2 1450736998000000000
fieldconflict value=3i  1450736998000000001
```

On the first write there's a generic error message. On the second write attempt the message is more detailed since one of the field types has already "won":

```
root@sean-0:~# curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary @points.influx
HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: af06423e-a832-11e5-805e-000000000000
X-Influxdb-Version: 0.9.6.1
Date: Mon, 21 Dec 2015 22:32:14 GMT
Content-Length: 46

{"error":"write failed: field type conflict"}
root@sean-0:~# curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary @points.influx
HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: d86003d1-a832-11e5-8069-000000000000
X-Influxdb-Version: 0.9.6.1
Date: Mon, 21 Dec 2015 22:33:23 GMT
Content-Length: 146

{"error":"write failed: field type conflict: input field \"value\" on measurement \"fieldconflict\" is type int64, already exists as type float"}
```

However, neither point was persisted to the database:

```
> select * from fieldconflict
> 
```

but the series was added to the metadata (foo was the only other measurement on this clean server):

```
> show measurements
name: measurements
------------------
name
fieldconflict
foo
```
```
> show series
name: fieldconflict
-------------------
_key
fieldconflict


name: foo
---------
_key
foo

> 
```

I tend to agree that if the point isn't going to persist, the metadata should not, either. It's strange that the field type is set even without a point being successfully written. Seems like a bug somewhere in the conflict code that tosses both even though the metadata assumes one has already won.

**Comment by jwilder** [comment]
Still occurs in 1.0 and 1.1 nightlies.
