### ISSUE TITLE
UDP database routing

### ISSUE THREAD

**Issue by schen59** [influxdata/influxdb#5156]
Right now influxdb stores everything from UDP into a single database named like "udp". Is it possible and reasonable to add some routing based on the metrics tag, so that we can route different metrics to different databases instead of put everything in a single database?

**Comment by otoolep** [comment]
It is possible, but I am not sure if and when we'll do it. However there is nothing stopping you running multiple UDP services, and routing traffic from each to different databases. Perhaps that would work?

**Comment by otoolep** [comment]
PRs for your proposed feature welcome, of course.

**Comment by schen59** [comment]
Thanks. Multiple UDP services would work if I have limited and defined number of databases. Maybe I will think about making a PR.

**Comment by JimHagan** [comment]
For resource management we'd love a feature where we can setup a UDP config that allows us to route certain metric names (via regexp) to a specific DB.  This would give us good insights into resource requirements downstream and I think it will also make accessing Influx from Grafana more controlled in that we can allow certain users to access certain DBs depending upon the type of metrics they are working with.

**Comment by acmnu** [comment]
I am wonder what was a reason to tie udp and database? Why I can't use fully qualified name (database."rp".measurement) in line protocol?

**Comment by saboteurkid** [comment]
@acmnu [https://github.com/influxdata/influxdb/issues/6037#issuecomment-234143545](Here) is the reason.
Disclaimed: It's issue #6037
