### ISSUE TITLE
Inconsistent version numbers being reported

### ISSUE THREAD

**Issue by zstyblik** [influxdata/influxdb#5160]
Hello,

I see what could be perceived as inconsistent or confusing version numbers being reported by InfluxDB or InfluxDB tools.

* InfluxDB web interface says v0.9.6 despite the fact version is 0.9.6.1
* if I connect to the remote InfluxDB instance, I get:

```
influx -host 10.0.3.2 -port 8086
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://10.0.3.2:8086 version 0.9.6.1
InfluxDB shell 0.9.6
> exit
```

Since the host I'm connecting from has InfluxDB 0.9.6 installed, I presume `InfluxDB shell 0.9.6` is related to the version of local binary and not the version of remote shell?

Thank you.

**Comment by zstyblik** [comment]
> I presume InfluxDB shell 0.9.6 is related to the version of local binary

Yes, it is.

**Comment by toddboom** [comment]
I think this was a byproduct of version numbering that should be fixed with v0.10.0, so I'm closing this out.

**Comment by zstyblik** [comment]
@toddboom may be somebody forgot to increase version number somewhere in the code. Also, I've seen issue for Web UI and `/ping` which should improve this. Anyway, I agree this issue is not relevant any more.

**Comment by janantala** [comment]
@toddboom the admin version numbering still doesn't work.
