### ISSUE TITLE
[golang client api]  Clarification on "Err" member of Response and Result structs [compile errors]

### ISSUE THREAD

**Issue by bigKS** [influxdata/influxdb#5179]
I'm struggling with some client api issues with respect to the "Err" variables that are part of the Response and Result structs (see below for more details).  

Please see client api doc for these key query result structures:

https://godoc.org/github.com/influxdb/influxdb/client/v2#Response

Notice:
```
type Response struct {
    Results []Result
    Err     string `json:"error,omitempty"`  <~~~ SEE
}


type Result struct {
    Series []models.Row
    Err    string `json:"error,omitempty"`  <~~~ SEE
}
```

Both "Err" variables in these structs are presented as having a type of string.
Confirmed by clicking into and looking at code in github: https://github.com/influxdb/influxdb/blob/master/client/v2/client.go#L420

But my code does not compile when I treat these as strings:
```
[ksengal@csdev-ksengal influxdb]$ go test -v client.go client_test.go dsn.go dsn_test.go stats.go timeseries.go reportCommon.go
./client.go:121: invalid operation: res.Err != "" (mismatched types error and string)
./client.go:122: cannot use res.Err (type error) as type string in argument to errors.New
./client.go:134: invalid operation: result.Err != "" (mismatched types error and string)
```
So it would seem that these are actually of type error, not type string.

When did this API change?
My local influxdb client api code has these as type error:
```
[ksengal@csdev-ksengal v2]$ pwd
/home/ksengal/work/src/github.com/influxdb/influxdb/client/v2
[ksengal@csdev-ksengal v2]$ egrep -r 'type[ \t]*(Response|Result)' -A2 *
client.go:type Response struct {
client.go-	Results []Result
client.go-	Err     error  

client.go:type Result struct {
client.go-	Series []models.Row
client.go-	Err    error  

[ksengal@csdev-ksengal v2]$ git remote -v
origin	https://github.com/influxdb/influxdb (fetch)
origin	https://github.com/influxdb/influxdb (push)
```

Did these variable change to type string in latest client api code for a reason (see below)?
https://github.com/influxdb/influxdb/blob/master/client/v2/client.go

**Comment by jsternberg** [comment]
I'm not sure about the answer to the specific question, but we're trying to remove older issues from the issue tracker and keep it to just features and bugs. If you are still having trouble with this issue and haven't found an answer, feel free to ask the question on our [mailing list](https://groups.google.com/forum/#!forum/influxdb). Thanks.
