### ISSUE TITLE
SHOW DATABASES shows one non-existing database

### ISSUE THREAD

**Issue by pires** [influxdata/influxdb#5185]
```
$ influx -host 192.168.99.100
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://192.168.99.100:8086 version 0.9.6.1
InfluxDB shell 0.9
> show databases
name: databases
---------------
name
_internal
```

`name` is a non-existing database.

Refs #5183

**Comment by otoolep** [comment]
"Name" is the name of the column.

**Comment by pires** [comment]
We have _two_ `name` identifiers there. I'm good with the label but as a user, I'm confused by the entry just above `_internal`.

**Comment by otoolep** [comment]
I agree, I've never liked it either. It could do with improvement.

**Comment by pires** [comment]
@otoolep not sure how to follow from here. Change the formatting? Split `SHOW DATABASES` from all other `SHOW` commands (which are actually queries)?

**Comment by otoolep** [comment]
I'd need to take a look at the code. Ideally we'd implement a general solution, that would add formattting to make it clear they are column names.

**Comment by pires** [comment]
@otoolep agreed. I have no idea if changing how the query responses are formatted would be a breaking change but am glad to own it if everyone agrees it's the correct step into fixing this.

**Comment by beckettsean** [comment]
@pires as I clarified in another comment, the `name` in the return isn't the name of a database, it's the name of the column in the return. Since there's only one column returned it seems like it's part of the results.

**Comment by pires** [comment]
@beckettsean yes I had figured it out before but want you guys to (help) decide what the solution would be here. I provided two possible ways to fix it but the one me and @otoolep (and probably everyone) agree upon may be a breaking change, even if just an aesthetic one.

**Comment by otoolep** [comment]
Simply improving the output of the CLI such that the column names somehow are underlined would be fine a solution. It's not a breaking change since the CLI output is not part of the API.

E.g.:

```
> SHOW DATABASES
name: databases
---------------
name
----
_internal
```

**Comment by otoolep** [comment]
Then again, perhaps this is not that clear either. :-( But you get my point.

**Comment by beckettsean** [comment]
@otoolep I like that suggestion. I think it improves readability across the board.

**Comment by mark-rushakoff** [comment]
It's still a little funny looking that `name` shows up twice but I think it's pretty clear that `name` isn't the name of a particular database in the current output:

```
> show databases
name: databases
name
----
stress
test
```

Closing this issue.
