### ISSUE TITLE
[0.9.6.1] CQ not being executed, misconfiguration?

### ISSUE THREAD

**Issue by zstyblik** [influxdata/influxdb#5190]
Hi,

I have the following CQs:

```
CREATE CONTINUOUS QUERY cq_1m_avg_tdb2 ON testdb2 BEGIN SELECT mean(value) INTO testdb2."1m".:MEASUREMENT FROM testdb2."1s"./.*/ WHERE time > now() - 10m GROUP BY time(1m), * END
CREATE CONTINUOUS QUERY cq_5m_avg_tdb2 ON testdb2 BEGIN SELECT mean(value) INTO testdb2."1h".:MEASUREMENT FROM testdb2."1m"./.*/ WHERE time > now() - 25m GROUP BY time(5m), * END
CREATE CONTINUOUS QUERY cq_15m_avg_tdb2 ON testdb2 BEGIN SELECT mean(value) INTO testdb2."1d".:MEASUREMENT FROM testdb2."1h"./.*/ WHERE time > now() - 55m GROUP BY time(15m), * END
```

with the following settings in `config.toml`:
```
[continuous_queries]
  log-enabled = true
  enabled = true
  recompute-previous-n = 2
  recompute-no-older-than = "10m"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m"
```

First CQ is being executed just fine, although it yields inconsistent results. However, the other two CQs aren't being executed at all since there is no data. I wonder, is it because of `recompute-no-older-than = "10m"` or is it a bug?
I sort of understand lower boundary of CQs, but I'm really not clear at all on the upper boundary. Also, what happens if you change those `WHERE` constrains to something `- 7d, -24w, -52w`?

Observed with 0.9.6.1.

Thank you for clarification.

**Comment by beckettsean** [comment]
@zstyblik the `WHERE time` clause is invalid for continuous queries. Can you DROP and recreate the continuous queries without that clause?

**Comment by zstyblik** [comment]
@beckettsean that's not exactly a good news, but I will try tomorrow :) btw strange enough, the first CQ works despite `WHERE time` is present. The other two are being scheduled as well (now), but no values. Anyway, I will try tomorrow and report back. Thanks.

**Comment by beckettsean** [comment]
@zstyblik I actually don't expect that removing the `WHERE time` will solve the problem, but I want to make sure we're starting with a clean test case before we start exploring solutions.

> The other two are being scheduled as well (now), but no values. 

If they are being scheduled then the CQ portion is working as expected. If you see entries like this in your logs for each CQ then the CQ stuff is working:

```
[continuous_querier] 2015/12/21 12:55:41 executing continuous query daily
[query] 2015/12/21 12:55:41 SELECT count(value) AS "count" INTO "telegraf"."other".cpu_idle_count_day FROM "telegraf"."default".cpu_usage_idle WHERE time >= '2015-12-21T00:00:00Z' AND time < '2015-12-22T00:00:00Z' GROUP BY time(1d), *
```

The fact that no results are returned when you query those measurements to which the CQs write could be any number of possible explanations, some of which have nothing to do with the CQ itself.

I notice that the second two CQs write to different retention policies. Are you explicitly providing those when querying the results? If not, the CQ is returning the results for the default retention policy, which may not have any points at all.

**Comment by zstyblik** [comment]
@beckettsean just to show you that CQs with time limit do get executed and all.

```
Dec 22 09:18:01 coreos01 docker[22357]: [continuous_querier] 2015/12/22 09:18:01 executing continuous query cq_1m_avg_tdb2
Dec 22 09:18:01 coreos01 docker[22357]: [query] 2015/12/22 09:18:01 SELECT mean(value) INTO testdb2."1m".:MEASUREMENT FROM testdb2."1s"./.*/ WHERE time >= '2015-12-22T09:18:00Z' AND time < '2015-12-22T09:19:00Z' GROUP BY time(1m), *
Dec 22 09:18:01 coreos01 docker[22357]: [query] 2015/12/22 09:18:01 SELECT mean(value) INTO testdb2."1m".:MEASUREMENT FROM testdb2."1s".wave WHERE time >= '2015-12-22T09:17:00Z' AND time < '2015-12-22T09:18:00Z' GROUP BY time(1m), *
Dec 22 09:18:01 coreos01 docker[22357]: [query] 2015/12/22 09:18:01 SELECT mean(value) INTO testdb2."1m".:MEASUREMENT FROM testdb2."1s".wave WHERE time >= '2015-12-22T09:16:00Z' AND time < '2015-12-22T09:17:00Z' GROUP BY time(1m), *
Dec 22 09:18:02 coreos01 docker[22357]: [continuous_querier] 2015/12/22 09:18:02 executing continuous query cq_5m_avg_tdb2
Dec 22 09:18:02 coreos01 docker[22357]: [query] 2015/12/22 09:18:02 SELECT mean(value) INTO testdb2."1h".:MEASUREMENT FROM testdb2."1m"./.*/ WHERE time >= '2015-12-22T09:15:00Z' AND time < '2015-12-22T09:20:00Z' GROUP BY time(5m), *
Dec 22 09:18:02 coreos01 docker[22357]: [query] 2015/12/22 09:18:02 SELECT mean(value) INTO testdb2."1h".:MEASUREMENT FROM testdb2."1m".wave WHERE time >= '2015-12-22T09:10:00Z' AND time < '2015-12-22T09:15:00Z' GROUP BY time(5m), *
Dec 22 09:18:02 coreos01 docker[22357]: [query] 2015/12/22 09:18:02 SELECT mean(value) INTO testdb2."1h".:MEASUREMENT FROM testdb2."1m".wave WHERE time >= '2015-12-22T09:05:00Z' AND time < '2015-12-22T09:10:00Z' GROUP BY time(5m), *
Dec 22 09:18:03 coreos01 docker[22357]: [http] 2015/12/22 09:18:03 10.0.3.1 - - [22/Dec/2015:09:18:03 +0000] POST /write?db=testdb2&precision=s HTTP/1.1 204 0 - python-requests/2.4.3 CPython/2.7.9 Linux/4.3.0-040300-generic e718443a-a88c-11e5-b4e8-000000000000 10.034717ms
Dec 22 09:18:06 coreos01 docker[22357]: [continuous_querier] 2015/12/22 09:18:06 executing continuous query cq_15m_avg_tdb2
Dec 22 09:18:06 coreos01 docker[22357]: [query] 2015/12/22 09:18:06 SELECT mean(value) INTO testdb2."1d".:MEASUREMENT FROM testdb2."1h"./.*/ WHERE time >= '2015-12-22T09:15:00Z' AND time < '2015-12-22T09:30:00Z' GROUP BY time(15m), *
Dec 22 09:18:06 coreos01 docker[22357]: [query] 2015/12/22 09:18:06 SELECT mean(value) INTO testdb2."1d".:MEASUREMENT FROM testdb2."1h"./.*/ WHERE time >= '2015-12-22T09:00:00Z' AND time < '2015-12-22T09:15:00Z' GROUP BY time(15m), *
```

I think know what the problem is and it's a stupid one :)

**Comment by zstyblik** [comment]
As suspected. The problem was missing `AS value` in those continuous queries. You see, `:MEASUREMENT` references `value`. And if you do `mean(value)` it's stored as a `mean` and won't be referenced/picked up by `:MEASUREMENT` despite the fact it's the only measurement in there. That's why the first CQ worked, but others didn't. There was nothing to select.

I believe this issue can be closed, unless you want to document this use-case more which would be great including short-hands like `:MEASUREMENT`.

Thanks for the support.

**Comment by zstyblik** [comment]
The new CQs, although still with `WHERE time`:

```
cq_1m_avg_tdb2  CREATE CONTINUOUS QUERY cq_1m_avg_tdb2 ON testdb2 BEGIN SELECT mean(value) AS "value" INTO testdb2."1m".:MEASUREMENT FROM testdb2."1s"./.*/ WHERE time > now() - 10m GROUP BY time(1m), * END
cq_5m_avg_tdb2  CREATE CONTINUOUS QUERY cq_5m_avg_tdb2 ON testdb2 BEGIN SELECT mean(value) AS "value" INTO testdb2."1h".:MEASUREMENT FROM testdb2."1m"./.*/ WHERE time > now() - 25m GROUP BY time(5m), * END
cq_15m_avg_tdb2 CREATE CONTINUOUS QUERY cq_15m_avg_tdb2 ON testdb2 BEGIN SELECT mean(value) AS "value" INTO testdb2."1d".:MEASUREMENT FROM testdb2."1h"./.*/ WHERE time > now() - 55m GROUP BY time(15m), * END
```

**Comment by zstyblik** [comment]
I see some confusion related to `AS value` in https://github.com/influxdb/influxdb/issues/3221. It might really be a good idea to document this.
