### ISSUE TITLE
Repository for Ubuntu 15.10 Wily

### ISSUE THREAD

**Issue by francisdb** [influxdata/influxdb#5199]
The blog post at https://influxdb.com/blog/2015/12/04/introducing_repos_influxdata.html mentions support for 12.04 (Precise), 14.04 (Trusty), 14.10 (Utopic), and 15.04 (Vivid) but 15.10 (Wily) is missing.

**Comment by rossmcdonald** [comment]
@francisdb Support for Ubuntu Wily has now been added to the repos.influxdata.com repository:

```
deb https://repos.influxdata.com/ubuntu wily stable
```

Let me know if you run into any issues!

**Comment by francisdb** [comment]
@rossmcdonald works fine now

I did however had to disable multi-arch setup. Not sure why this was set up by default on my digitalocean ubuntu server.

```
W: Failed to fetch https://repos.influxdata.com/ubuntu/dists/wily/InRelease  Unable to find expected entry 'stable/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

fix was the following:

```
# dpkg --print-foreign-architectures
i386
# sudo dpkg --remove-architecture i386
```

**Comment by rossmcdonald** [comment]
@francisdb Thanks for letting me know. I've seen a few other users report that error, so I'll dig into it a little bit more to see if I can determine the cause.

**Comment by d0t101101** [comment]
Same issue here on Trusty (x64) - apt-get update returned errors:
  ```Unable to find expected entry 'stable/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)```

The dpkg remove architecture command above fixed it...

Thanks!
