### ISSUE TITLE
[0.10.0_nightly_308cab0-1] panic: runtime error: index out of range

### ISSUE THREAD

**Issue by ivanscattergood** [influxdata/influxdb#5202]
```
[cacheloader] 2015/12/22 18:17:41 reading file /var/lib/influxdb/wal/open_access_db/detail/14/_02984.wal, size 0
[tsm1wal] 2015/12/22 18:26:19 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2015/12/22 18:26:19 tsm1 WAL writing to /var/lib/influxdb/wal/open_access_db/detail/16
panic: runtime error: index out of range

goroutine 23 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*indirectIndex).UnmarshalBinary(0xc9b03dd040, 0x7f9cf7950b0c, 0x8403003e, 0x84030046, 0x0, 0x0)
        /tmp/tmp.MmCxSXUQt9/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/reader.go:614 +0xd03
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*mmapAccessor).init(0xccfd040460, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.MmCxSXUQt9/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/reader.go:842 +0x57c
github.com/influxdb/influxdb/tsdb/engine/tsm1.NewTSMReaderWithOptions(0x0, 0x0, 0xc9b09a32f0, 0xece0b87ae, 0x0, 0x0)
        /tmp/tmp.MmCxSXUQt9/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/reader.go:139 +0x2d8
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*FileStore).Open.func1(0xcad77e6af0, 0xcabf598a20, 0x3, 0xc9b09a32f0)
        /tmp/tmp.MmCxSXUQt9/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/file_store.go:251 +0x8f
created by github.com/influxdb/influxdb/tsdb/engine/tsm1.(*FileStore).Open
        /tmp/tmp.MmCxSXUQt9/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/file_store.go:261 +0x6bb
```

**Comment by beckettsean** [comment]
@ivanscattergood can you give some context as to what was happening? Was this during startup? Did this happen during normal load? Does it recover on restart?

**Comment by ivanscattergood** [comment]
Hi, 

Sorry, I realise now in isolation that error message is useless! 

I have been running the 0.9.6.1 binary for just about a week and saving collecting 0.5 million datapoints (over 1 million series) every 10 minutes. 

I wanted to upgrade to the nightly after advice from @pauldix (in ticket #4977). When I upgraded to the new binary, this was the error I got on startup. 

I have rolled back to 0.9.6.1 and it works fine. 

Will I need to start with a Fresh database to use the nightly?

**Comment by otoolep** [comment]
@jwilder -- any thoughts?

**Comment by jwilder** [comment]
If you have existing `tsm1` files created by the `tsm1` engine in `0.9.6.1`, you will need to start with a fresh DB to use the nightlies.  The `tsm1` engine in `0.9.6.1` uses a different file format than the current nightly version which is likely causing the panic you are seeing.

**Comment by otoolep** [comment]
Please wipe your tsm database and try again.

**Comment by pauldix** [comment]
I think there's some confusion here. There shouldn't be any breaking changes between the 0.9.6.1 TSM format and master. Would you be able to send us the TSM file that it's crashing on?

**Comment by jwilder** [comment]
@ivanscattergood Also, could you attach the output of an `ls` on your shards for that DB?

**Comment by ivanscattergood** [comment]
The raw data is getting saved in a shard called detail: 

[root@visual-edge detail]# pwd
/ext_data/influxdb/data/open_access_db/detail

[root@visual-edge detail]# ls -ltrah
total 12G
drwx------.  4 influxdb influxdb 4.0K Dec 11 00:00 ..
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 14 00:03 7
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 15 00:05 9
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 16 00:05 12
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 17 00:12 14
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 18 16:59 16
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 19 20:28 18
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 20 00:07 20
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 21 00:15 22
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 21 23:25 27
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 22 00:17 24
drwx------. 14 influxdb influxdb 4.0K Dec 23 00:00 .
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 23 01:02 29
-rw-r--r--.  1 influxdb influxdb 2.0G Dec 23 18:32 2
-rw-r--r--.  1 influxdb influxdb  10G Dec 23 19:31 4
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 23 22:38 31

And the offending directory 16: 
total 9.3G
-rw-r--r--.  1 influxdb influxdb 2.1G Dec 16 09:45 000000143-000000004.tsm
-rw-r--r--.  1 influxdb influxdb 2.2G Dec 16 18:29 000000302-000000004.tsm
-rw-r--r--.  1 influxdb influxdb 2.2G Dec 16 22:35 000000377-000000004.tsm
-rw-r--r--.  1 influxdb influxdb 2.9G Dec 18 16:59 000000400-000000003.tsm
drwxr-xr-x.  2 influxdb influxdb 4.0K Dec 18 16:59 .
drwx------. 14 influxdb influxdb 4.0K Dec 23 00:00 ..

**Comment by ivanscattergood** [comment]
Here are the contents of the Directory 16

**Comment by ivanscattergood** [comment]
I found that if I remove Directory 18 (files attached) I can get the Database started

**Comment by jwilder** [comment]
@ivanscattergood If you are still seeing this issue, #5264 may have fixed it.  That fix should be in tonights nightly build.

**Comment by jwilder** [comment]
Fixed via #5264

**Comment by zstyblik** [comment]
@jwilder close then?

**Comment by ivanscattergood** [comment]
I'm Happy to close this issue

**Comment by jwilder** [comment]
Thanks! Forgot to close.
