### ISSUE TITLE
influxdb 0.9.6.1 rpm update will remove startup scripts

### ISSUE THREAD

**Issue by huhongbo** [influxdata/influxdb#5228]
update from influxdb 0.9.6 to 0.9.6.1 at centos 7
[root@test1 ~]# rpm -Uvh influxdb-0.9.6.1-1.x86_64.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:influxdb-0.9.6.1-1               ################################# [ 50%]
Cleaning up / removing...
   2:influxdb-0.9.6-1                 ################################# [100%]
rm '/etc/systemd/system/multi-user.target.wants/influxdb.service'
rm '/etc/systemd/system/influxd.service'

**Comment by jsternberg** [comment]
I'm able to reproduce it. It appears this behavior doesn't happen on Ubuntu 14.04 (and likely doesn't happen on any Debian based system).

**Comment by Galser** [comment]
Happened for all 3 nodes to me on CentOS 6.7

**Comment by rossmcdonald** [comment]
@Galser Thanks for letting us know. Are you running systemd on your CentOS 6.7 instances?

**Comment by Galser** [comment]
Nope, regular init.d style scripts.
29 груд. 2015 4:07 пп "Ross McDonald" <notifications@github.com> пише:

**Comment by mgresser** [comment]
When I upgraded to it I had to uninstall and reinstall and then restore my configs but the upgrade path definitely removed the init.d scripts for me on a number of nodes. I observed this on CentOS 7.1 as well as CentOS 6.7 so it also was happening with systemd startup scripts.

**Comment by mhiller** [comment]
any word on this ? this definitely was a suprise when i took this update this morning.

**Comment by rossmcdonald** [comment]
This was resolved with #4948, which is in the nightlies and will be included in the next release
