### ISSUE TITLE
[0.9.4.2] RESTORE DATA - open server: open tsdb store: failed to open shard 54: load metadata index: read block: EOF

### ISSUE THREAD

**Issue by mrow4a** [influxdata/influxdb#5230]
For a longer period of time I have been storing measurements using influxdb 0.9

However, recently I observed this, and my node is crashing on that: 

```
....
[wal] 2015/12/28 15:11:47 WAL writing to /data/wal/smashbox/default/45
[wal] 2015/12/28 15:12:02 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/12/28 15:12:02 WAL writing to /data/wal/smashbox/default/54
[wal] 2015/12/28 15:12:02 reading WAL files to flush to index
[retention] 2015/12/28 15:12:02 retention policy enforcement terminating
[monitor] 2015/12/28 15:12:02 shutting down monitor system
[monitor] 2015/12/28 15:12:02 terminating storage of statistics
run: open server: open tsdb store: failed to open shard 54: load metadata index: read block: EOF
```
Refering to https://github.com/influxdb/influxdb/issues/4566, i know that I have corruption there. However, is it possible to recover the data which is sitting on the database? How to make the database functioning again?

**Comment by beckettsean** [comment]
@mrow4a what specific version are you running, and do you know what storage engine is set? `b1`, `bz1`, or `tsm`?

**Comment by mrow4a** [comment]
2015/12/28 19:54:48 InfluxDB starting, version 0.9.4.2, branch 0.9.4, commit da1b59e7d7764d36786253b2db13b97f42ed4e1d

About the engine, I have not been setting anything else than that set by default.

**Comment by beckettsean** [comment]
Thanks, @mrow4a. InfluxDB 0.9.4.2 uses the `bz1` engine by default.

I don't think it is likely there is any way to recover the lost data. @otoolep is there a way to remove the corrupted data so that the system can continue to function without full data loss?

**Comment by mrow4a** [comment]
So what is basically this database corruption? Is there any way to recover measurement points which were correct, till the corruption?

**Comment by beckettsean** [comment]
@mrow4a I don't know what the corruption is. We have utilities that might be able to recover some of the data from that shard.

@dgnorton does your shard recovery tool work on `bz1` shards from 0.9.4?

**Comment by dgnorton** [comment]
@beckettsean  it's been a while and I can't remember if it works with `bz1` but it should be pretty easy to try.  The code is on the `shard-dump` branch (based off of `0.9.4 ish` code).  It's a hacked version of Jason's `inspect` tool, so it only requires building `cmd/inspect`.  I'll email you the binary...maybe there's a convenient place we can put it for download?

**Comment by dgnorton** [comment]
@beckettsean shard dump tool usage...
```
$ ./inspect -help
Usage of ./inspect:
  -cpuprofile string
    	name of CPU profile file to generate
  -o string
    	output file name
  -p string
    	Root storage path. [$HOME/.influxdb] (default "/home/dgnorton/.influxdb")
```
If you don't want to dump all shards in the database, create a directory structure in `/tmp` matching the database and copy the shard(s) you want to dump.  Then use the `-p string` command line argument to point it to the database in `/tmp`.  As I recall, it will dump all shards into one file, which may not be desirable if the shards are large.

**Comment by beckettsean** [comment]
@rossmcdonald can you create an upload link for @mrow4a to upload the corrupted shard?

**Comment by beckettsean** [comment]
@mrow4a how big is shard 54 on disk?

**Comment by mrow4a** [comment]
du -h -d 1 /data/wal/
>> 60K	/data/wal/smashbox

**Comment by beckettsean** [comment]
Thanks @mrow4a at only 48KB that will be quite easy to parse.

**Comment by mrow4a** [comment]
Great, for me it is enough to have some text file with measurement data, in any form. I have scripts which will load the missing data to the new instance (or I will modify them).

**Comment by mrow4a** [comment]
@dgnorton What do you mean by "create a directory structure in /tmp matching the database"?

**Comment by dgnorton** [comment]
@mrow4a for example, I currently have a database named `foo1`.  The path to shard 1 is `~/.influxdb/data/foo1/default/1`.  If I wanted to dump only shard 1, I would do something like
```
mkdir -p /tmp/influxdb/data/foo1/default
cp ~/.influxdb/data/foo1/default/1 /tmp/influxdb/data/foo1/default
inspect -p /tmp/influxdb
```

**Comment by rossmcdonald** [comment]
@mrow4a You can upload the shard using the link here:

https://www.cloudwok.com/w/o9M5

Let me know if you have any issues!

**Comment by mrow4a** [comment]
@rossmcdonald As I understand, if I make a copy of whole /data/ directory, i will make a backup of whole the database? I have around 20GB of data there, an the corrupted shard is small. Will removal or "recreation" of that shard solve my problem? I am not sure about touching there anything, not to break sth. 

@rossmcdonald I will upload my broken shard in few minutes.

**Comment by beckettsean** [comment]
@mrow4a to back up the actual database, you need to shut down the process and copy `/data` and `/meta`, and possibly `/wal` if you are writing to the db right up until shutdown.

For our purposes, I believe you only need to upload the corrupted shard. If we need anything else I'll let you know.

**Comment by mrow4a** [comment]
Actually, what I meant is that, what folder would I need to copy to another influxdb instance to have exact copy of that system and play with that?

**Comment by mrow4a** [comment]
@beckettsean broken shard uploaded.

**Comment by beckettsean** [comment]
@mrow4a if you backup the entire `/influxdb` directory that contains `/data` and `/wal` and `/meta`. The only other thing to grab is the config file, which is somewhere in `/etc`. I apologize I haven't given full paths for the default install, they changed recently and I can't recall the older ones, and I no longer have an 0.9.4 server handy. @rossmcdonald what are the default file paths for the `/influx` directory and config file in 0.9.4?

@mrow4a we have the file, thanks! We'll let you know how recovery goes.

**Comment by rossmcdonald** [comment]
@mrow4a @beckettsean To back up an entire InfluxDB 0.9.4 instance (assuming the default directory locations), you will need to capture both `/var/opt/influxdb` (the data) and `/etc/opt/influxdb` (the configuration) while the service is stopped. An entire backup workflow would look similar to:

```
service influxdb stop
tar -cvzf influxdb_backup.tgz /var/opt/influxdb /etc/opt/influxdb
service influxdb start
```

**Comment by mrow4a** [comment]
Ok, backuping to other machine works, but you forgot to mention one thing. You need to modify the "hostname" of the new machine to match the one from the instalation place. Otherwise its lost. Hope it could be usefull for someone. 

I am waiting now for your recovery to get the data back.

**Comment by beckettsean** [comment]
@mrow4a the tarball you uploaded appears to have nothing in the `/data` directory. There are two `/wal` files, but those aren't in the same format as the persistent data store.

Does the `/data` directory have any shard named `54`?

**Comment by mrow4a** [comment]
@beckettsean I think I will leave without that data. Because of the sharding and some kind of retention policies, the data which I was needing was on the other shard, in 100%. The one corrupted is not relevant and could dissapear. You can close the topic, is sth will happen, I will give you notice. If you want, I can send you a shard 54.

**Comment by beckettsean** [comment]
Thanks, @mrow4a we will close this issue. The system will move to the `tsm` engine with the 0.10 release, so investigating potential corruption causes in the `bz1` shards is a very low priority.
