### ISSUE TITLE
[Feature Request] CQ * Fields or Standard Rollup method support

### ISSUE THREAD

**Issue by zachaller** [influxdata/influxdb#5234]
Part of needing to do rollups for performance with grafana we ran into an issue that makes managing the CQ's for the rollups extremely inconvenient. We need to be able to do something like this.

```
CREATE CONTINUOUS QUERY one_min ON telegraf BEGIN SELECT mean(*) INTO telegraf.\"1min_rollup\".:MEASUREMENT FROM telegraf.\"default\"./.*/ GROUP BY time(1m), * END"
```

This kind of explains it a bit more also https://github.com/influxdb/influxdb/issues/3756#issuecomment-166880333

If this is not done I feel there should be some way to do standard rollups of set time intervals either using CQ or something else. This would also be another workaround https://github.com/influxdb/influxdb/issues/5128 possibly but seems to be more of a hack for the rollup use case where it makes more sense to be able to send rollups to different retention policies.

**Comment by beckettsean** [comment]
related to #5750

**Comment by beckettsean** [comment]
Can probably close in favor of https://github.com/influxdata/influxdb/issues/6910. @zachaller @pauldix you concur?

**Comment by pauldix** [comment]
yep
