### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by ikrush** [influxdata/influxdb#5244]
I have a Windows Service reading data from some sensors every second, aggregating this data every ten minutes and inserting it on InfluxDB.

[InfluxDB_crash_20151230.txt](https://github.com/influxdb/influxdb/files/74734/InfluxDB_crash_20151230.txt)

It's a single node instance of InfluxDB v.0.9.6.1 (tsm1) compiled with Go v.1.4.3 running on a machine with Windows Server 2012 R2 and 32GB of RAM.

**Comment by jackzampolin** [comment]
@ikrush Was the server under query load at the time of the crash? What was the volume of write load?

**Comment by ikrush** [comment]
I was inserting about 10.000 points every 5 seconds. No one was querying the server, only inserts.

**Comment by ikrush** [comment]
I got the same error today.

[InfluxDB_crash_20151231.txt](https://github.com/influxdb/influxdb/files/75443/InfluxDB_crash_20151231.txt)

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/5265 may address this issue.

**Comment by ikrush** [comment]
Thank you, in that case I will use BZ1 engine for now.

**Comment by rossmcdonald** [comment]
As referenced from #5433, removing Windows from the title as this affects Linux as well. This issue also seems to occur with the 0.10.0 beta releases, and is not 0.9.6 specific.

**Comment by markusr** [comment]
I have the same problem under Ubuntu 14.04.

My influx version is:
`version 0.10.0, branch 0.10.0, commit b8bb32ecad9808ef00219e7d2469514890a0987a, built 2016-02-04T17:06:04.850564`

I can provide a log file if needed.

**Comment by rossmcdonald** [comment]
@markusr Thanks, could you send us the logs as well?

**Comment by markusr** [comment]
I think I hit another bug / problem. After going through the log file I found:
`[retention] 2016/02/08 13:01:17 retention policy shard deletion check commencing`
`[retention] 2016/02/08 13:01:18 failed to delete shard ID 556 from database _internal, retention policy monitor: remove /var/lib/influxdb/data/_internal/monitor/556/000000001-000000001.tsm: permission denied
`

I converted the shards yesterday from v0.9 format to the new tsm. I could resolve the panic by running:
`sudo chown influxdb:influxdb -R /var/lib/influxdb/data`

Here is however the full log:
[influxd_2016-02-08.txt](https://github.com/influxdata/influxdb/files/121783/influxd_2016-02-08.txt)

Now the system is running fine. I'll report if the error occurs again.

**Comment by rossmcdonald** [comment]
@markusr Thank you for the update. I ran into this issue as well, which ended up being a permissions issue.

@ikrush Looking at the pasted logs from before I found:

```
[retention] 2016/01/23 08:06:41 failed to delete shard ID 42 from database _internal, retention policy monitor: remove /var/lib/influxdb/data/_internal/monitor/42/000000001-000000001.tsm: permission denied
```

So this may just be a permissions issue.

**Comment by markusr** [comment]
I just want to add that this bug did not run occur again. So from my side the issue can be closed.

**Comment by rossmcdonald** [comment]
@markusr Thanks for the update. Closing as a permissions issue for now.
