### ISSUE TITLE
[0.9.6] Using an NFS remote directory for data storage causes pthread error on Raspberry Pi

### ISSUE THREAD

**Issue by jheyman** [influxdata/influxdb#5259]
Hi,
I am using InfluxDB 0.9.6 compiled with Go 1.5.2 on a raspberry pi model B (512MB RAM).
My usecase is extremely basic: logging ~ 10 parameters everything 5 minutes.
Everything works fine with the default configuration, but if I change the data and WAL directories to a network directory (mounted with NFS), after a few minutes I systematically get this error:

<pre><code>
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0xb6e37cdc m=0
</code></pre>
followed by 300+ goroutine stack traces similar to this one:
<pre><code>
goroutine 108 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0x10f494a0, 0x111027c0)
	/home/pi/.gvm/pkgsets/go1.5.2/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x470
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/home/pi/.gvm/pkgsets/go1.5.2/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x524
</code></pre>

Since I do not want to use /var/lib as the storage location (which lives in the flash memory on the Raspberry), for now I modified the data and WAL location to point to a local external USB drive, which works fine.

I understand that the Raspberry has limited resources and this NFS storage usecase requires more system resources (e.g. sockets) than local storage does, but I am curious as to why so many threads are required that an internal limit is reached, and whether there is something I could change to avoid reaching this limit. I already tried increasing various ulimit values, to no avail.

Regards,
Julien

**Comment by zstyblik** [comment]
I wonder, could `nolock` option help? Locking at NFS seems to be somewhat troublesome. Before you ask - yes, this is a guess.

**Comment by jheyman** [comment]
Mmmh, interesting, it used to crash in about 5 minutes, and it has now been running fine for two hours with nolock NFS option. I'll check tomorrow morning if it survived the night, but in any case thanks for the pretty good guess !

**Comment by zstyblik** [comment]
Cool! Fingers crossed :)

**Comment by kureikain** [comment]
@zstyblik  great tip. Confirmed the nolock option. Worked on my side as well

**Comment by jheyman** [comment]
Yep, fixed confirmed: 24+ hours and still no trace of the issue. Thanks again.

**Comment by zstyblik** [comment]
@jheyman @kureikain I'm glad I could help with my ... guess :)
