### ISSUE TITLE
[feature request] support for HAVING clause

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#5266]
Allow results to be restricted by a calculated or derived value:

```
SELECT MEAN(foo) FROM measurement 
GROUP BY time(10m)
HAVING COUNT(foo) > 10 
```

See old 0.8 issues https://github.com/influxdb/influxdb/issues/183 and https://github.com/influxdb/influxdb/pull/611 for further discussion.

**Comment by ollijm** [comment]
+1

**Comment by faxm0dem** [comment]
:+1:

**Comment by max3163** [comment]
+1

**Comment by cxreg** [comment]
+1

**Comment by arthurgeek** [comment]
This is exactly what we need!

**Comment by sischnei** [comment]
+1

**Comment by zapient** [comment]
+1

**Comment by nordewal** [comment]
+1

**Comment by sischnei** [comment]
+1

**Comment by cnelissen** [comment]
+1

**Comment by franklinkim** [comment]
+1

**Comment by juhakuu** [comment]
+1

**Comment by malaki12003** [comment]
+1

**Comment by maberle** [comment]
+1

**Comment by mrecht** [comment]
+1

**Comment by TechBK** [comment]
+1

**Comment by anazia** [comment]
👍

**Comment by Apollon77** [comment]
+1

**Comment by phemmer** [comment]
Can we avoid the "+1" spam? Github has a feature specifically for this: 
![image](https://cloud.githubusercontent.com/assets/1826947/19889619/3cf1f06a-a00c-11e6-89fa-00cd556ffed6.png)

You can also use the "subscribe" button on the right if you want to receive updates.

**Comment by faxm0dem** [comment]
while @phemmer is right, it seems this github feature is missing on mobile css

**Comment by akuma** [comment]
+1

**Comment by syahagi** [comment]
+1

**Comment by aurimasplu** [comment]
Hi,
Is there any news on this feature?

**Comment by abusizhishen** [comment]
this is real useful for query and filter useless data
