### ISSUE TITLE
[0.9.6.1] ERR: unexpected end of JSON input on distributed aggregative query.

### ISSUE THREAD

**Issue by just2d** [influxdata/influxdb#5269]
version:0.9.6.1 release

3 raft servers 1 data server.
```
select * from accessdb._5w_rp.key_access_per_30m where time >= 1451379388000000000 and time <= 1451901436000000000 and u_key = 'f0f577c0b97d416f142fed74e8bbd3d7';
name: key_access_per_30m
------------------------
time			sum	u_key					u_uri
1451566800000000000	50	f0f577c0b97d416f142fed74e8bbd3d7	/v3/distance
1451566800000000000	48	f0f577c0b97d416f142fed74e8bbd3d7	/v3/assistant/intention
1451566800000000000	50	f0f577c0b97d416f142fed74e8bbd3d7	/v3/place/text
1451566800000000000	50	f0f577c0b97d416f142fed74e8bbd3d7	/v3/place/polygon
```

but the following query fails everytime.
```
select sum(sum) from accessdb._5w_rp.key_access_per_30m where time >= 1451379388000000000 and time <= 1451901436000000000 and u_key = 'f0f577c0b97d416f142fed74e8bbd3d7';
ERR: unexpected end of JSON input
```

any quick solutions to get cluster work properly? because this cluster is about to be on production. is this the db's data too big or the cluster problem?  Is there a parameter can optimize this?

If this is the cluster's problem, I can use single server,  but can I switch to cluster some days later when 0.10 come out without no data lost?
Thanks.

**Comment by just2d** [comment]
temporarily, it works. 

```
select sum(sum) from accessdb._5w_rp.key_access_per_30m where time >= 1451379388000000000 and time <= 1451901436000000000 and u_key = 'f0f577c0b97d416f142fed74e8bbd3d7';
name: key_access_per_30m
------------------------
time			sum
1451379388000000000	198
```

**Comment by beckettsean** [comment]
@just2d `sum` is a reserved keyword in InfluxQL, since it is the name of a function. It appears that in the single-node environment the parser properly handles it in this case, but it is possible that when the query is decomposed for distribution to the other nodes it causes syntax issues.

What happens in the cluster if you issue the query as `select sum("sum") from accessdb._5w_rp.key_access_per_30m where ...`

**Comment by seyoonhan** [comment]
I think there's a bug using CQ on cluster mode. Try setting your replication count on retention policy exactly same as number of cluster nodes.

**Comment by just2d** [comment]
@beckettsean 
it doesn't help using sum("sum"):
```
> show servers;
id	cluster_addr		raft	raft-leader
1	10.178.96.65:8088	true	true
2	10.180.17.150:8088	true	false
3	10.180.21.243:8088	true	false
4	10.180.25.46:8088	false	false

> select sum("sum") from accessdb._5w_rp.key_access_per_30m where time >= 1451379388000000000 and time <= 1451901436000000000 and u_key = 'f0f577c0b97d416f142fed74e8bbd3d7';
ERR: unexpected end of JSON input
```

**Comment by just2d** [comment]
@seyoonhan thanks for the tips.
are you sure it's about the replication count?
I do has the replication count 3,not the all of the 4 nodes.

**Comment by seyoonhan** [comment]
@just2d Yes, I had same problem and solved it as described. Running CQ on cluster has problem, obviously.

**Comment by jsternberg** [comment]
Closing this as clustering is no longer supported in the open source version.
