### ISSUE TITLE
Per Database Disk Space Usage

### ISSUE THREAD

**Issue by miketonks** [influxdata/influxdb#5271]
We need to monitor and report on database size (disk space usage per database).

I've looked through the options in SHOW STATS / DIAGNOSTICS / DATABASES / SHARDS and cannot find anything suitable.

Only option right now seems to be a disk level 'du influx/data/....' type query, but this poses security problems and does not fit well into our (docker based) stack.  Ideally we'd like to read this info from the server by a standard api call not some file system hack.  It seems like the server should know what disk space it is using, and if it's necessary to account for multiple nodes in a cluster then the server should also be aware of this.

Similar feature, for reference: in ElasticSearch, the indices stats API reports index size out of the box.  https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html

Could this be added to SHOW DATABASES / SHOW DIAGNOSTICS or similar?

**Comment by jwilder** [comment]
Fixed via #5758 and #5810
