### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by PsychoSid** [influxdata/influxdb#5273]
Hello,

Using 9.6.1 with a single graphite and collectd input all seems OK but seemingly after an issue is logged CPU skyrockets. This is a single node whilst we kick the tyres on a cacti replacement

$ top -b -u influxdb
top - 15:14:26 up 215 days, 23:11,  1 user,  load average: 6.12, 6.94, 7.02
Tasks: 306 total,   3 running, 303 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.6 us,  0.1 sy,  0.0 ni, 99.2 id,  0.1 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 32722572 total,  8218176 free,  1778748 used, 22725648 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used. 28986260 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
30824 influxdb  20   0 2776580 1.202g  26012 R 729.4  3.9 440:19.95 influxd
30823 influxdb  20   0  120724   1652   1420 S   0.0  0.0   0:00.00 sh

top - 15:14:29 up 215 days, 23:11,  1 user,  load average: 6.19, 6.94, 7.02
Tasks: 306 total,   1 running, 305 sleeping,   0 stopped,   0 zombie
%Cpu(s): 54.3 us,  1.0 sy,  0.0 ni, 44.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 32722572 total,  8218160 free,  1778764 used, 22725648 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used. 28986244 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
30824 influxdb  20   0 2776580 1.202g  26012 S 886.1  3.9 440:46.80 influxd
30823 influxdb  20   0  120724   1652   1420 S   0.0  0.0   0:00.00 sh

You get the idea.. It doesn't seem to recover.

An error logged is:-
[graphite] 2016/01/05 15:34:15 unable to parse line: servers.<redacted>

Not a huge amount of data going in here right now.
InfluxDB shell 0.9.6.1
> show stats
name: collectd
tags: bind=:25826
batchesTx       bytesRx         pointsRx        pointsTx
---------       -------         --------        --------
464             25641023        598748          598068

name: graphite
tags: bind=:2003, proto=tcp
batchesTx       bytesRx         connsActive     connsHandled    pointsParseFail pointsRx        pointsTx
---------       -------         -----------     ------------    --------------- --------        --------
3181            129029296       1               1               20              1302136         1302027

This is a little worrying and I don't remember this happening on previous versions.

Anything I can check, or provide further ?

Thanks
Paul

**Comment by sebito91** [comment]
If you're using the binary provided on the webpage, it's most likely compiled with go1.5.2. We've seen some load issues with this version and reverted to go1.4.2 (see https://github.com/influxdata/influxdb/issues/5217).

I would recommend you try to compile HEAD using go1.4.2 and re-test your config. Load has been significantly reduced since we reverted go version (build instructions here: https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md)

**Comment by PsychoSid** [comment]
Hi,

Thanks for the suggestion and (https://github.com/influxdata/influxdb/issues/5217) seems interesting and a good fit. But compiling HEAD under 1.4.2 on this RHEL7 box didn't resolve the issue and the high CPU spins up after a few seconds of running.

Thanks
Paul

**Comment by PsychoSid** [comment]
Looks to have been caused by previous data that was not cleaned on upgrade. Luckily this is just a test instance so wiped all the data and restarted and the issue has not re-occured,
