### ISSUE TITLE
Cannot write boolean points

### ISSUE THREAD

**Issue by leorossi** [influxdata/influxdb#5274]
I'm struggling with this issue. I'm trying to save a boolean tag when writing a point
The command is: `curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'sample,global=true,region=IT value=11234 1434055562000000000'`
The `global` value is stored as string rather than boolean.

```
> format json
> select * from sample
{"results":[{"series":[{"name":"sample","columns":["time","global","region","value"],"values":[[1434055562000000000,"true","IT",11234]]}]}]}
```

I have tried with other accepted values, like `T`, `1`, `t`, `True`, `TRUE` but I always get the string value ( I always drop the measurements before writing the new point).

InfluxDB Version: 0.9.6.1, downloaded as binary
```
2016/01/05 15:55:01 InfluxDB starting, version 0.9.6.1, branch 0.9.6, commit 6d3a8603cfdaf1a141779ed88b093dcc5c528e5e, built 2015-12-10T23:40:23+0000
2016/01/05 15:55:01 Go version go1.4.2, GOMAXPROCS set to 8
```
OS: Ubuntu Linux running on a Vagrant Box
`Linux vagrant-ubuntu-trusty-64 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by gunnaraasen** [comment]
@leorossi All tag keys and values are strings. Booleans are only supported for field values.

**Comment by beckettsean** [comment]
Reference "Data Types" on https://docs.influxdata.com/influxdb/v0.9/write_protocols/write_syntax/. Only field values can be anything other than strings.
