### ISSUE TITLE
Slow write data from WAL to index

### ISSUE THREAD

**Issue by pmagos00** [influxdata/influxdb#5285]
After receiving several messages:

=================

[monitor] 2016/01/06 08:55:22 failed to store statistics: timeout
[monitor] 2016/01/06 08:55:32 failed to store statistics: timeout
[monitor] 2016/01/06 08:55:42 failed to store statistics: timeout
[monitor] 2016/01/06 08:55:52 failed to store statistics: timeout
[monitor] 2016/01/06 08:56:02 failed to store statistics: timeout
[monitor] 2016/01/06 08:56:12 failed to store statistics: timeout

=================

We restarded the influxdb and now is taking a lot of time to write data from WAL to index, how we can improve that?

This is the log for the restart:

=================

2016/01/06 09:27:48 InfluxDB starting, version 0.9.6.1, branch 0.9.6, commit 6d3a8603cfdaf1a141779ed88b093dcc5c528e5e, built 2015-12-10T23:40:23+0000
2016/01/06 09:27:48 Go version go1.4.2, GOMAXPROCS set to 32
2016/01/06 09:27:48 Using configuration at: /etc/influxdb/influxdb.conf
[metastore] 2016/01/06 09:27:48 Using data dir: /var/lib/influxdb/meta
[metastore] 2016/01/06 09:27:49 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2016/01/06 09:27:49 Node at localhost:8088 [Follower]
[metastore] 2016/01/06 09:27:50 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2016/01/06 09:27:50 spun up monitoring for 1
[store] 2016/01/06 09:27:50 Using data dir: /var/lib/influxdb/data
[metastore] 2016/01/06 09:27:50 Updated node id=1 hostname=localhost:8088
[wal] 2016/01/06 09:27:50 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/06 09:27:50 WAL writing to /var/lib/influxdb/wal/_internal/monitor/10
[wal] 2016/01/06 09:27:50 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/06 09:27:50 WAL writing to /var/lib/influxdb/wal/_internal/monitor/11
[wal] 2016/01/06 09:27:50 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/06 09:27:50 WAL writing to /var/lib/influxdb/wal/_internal/monitor/12
[wal] 2016/01/06 09:27:50 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/06 09:27:50 WAL writing to /var/lib/influxdb/wal/_internal/monitor/13
[wal] 2016/01/06 09:27:50 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/06 09:27:50 WAL writing to /var/lib/influxdb/wal/_internal/monitor/14
[wal] 2016/01/06 09:27:50 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/06 09:27:50 WAL writing to /var/lib/influxdb/wal/_internal/monitor/16
[wal] 2016/01/06 09:27:50 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/06 09:27:50 WAL writing to /var/lib/influxdb/wal/_internal/monitor/18
[wal] 2016/01/06 09:27:50 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/06 09:27:50 WAL writing to /var/lib/influxdb/wal/_internal/monitor/9
[wal] 2016/01/06 09:28:08 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/06 09:28:08 WAL writing to /var/lib/influxdb/wal/carbon/default/15
[wal] 2016/01/06 09:28:27 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/06 09:28:27 WAL writing to /var/lib/influxdb/wal/carbon/default/17
[wal] 2016/01/06 09:28:27 reading WAL files to flush to index
[wal] 2016/01/06 09:28:28 writing 115660 series from WAL file /var/lib/influxdb/wal/carbon/default/17/01.000004.wal to index
[wal] 2016/01/06 09:54:58 writing 116007 series from WAL file /var/lib/influxdb/wal/carbon/default/17/01.000005.wal to index
[wal] 2016/01/06 10:47:05 writing 115835 series from WAL file /var/lib/influxdb/wal/carbon/default/17/01.000006.wal to index

=================

**Comment by pmagos00** [comment]
Thanks a lot for the hard work in InfluxDB

**Comment by pmagos00** [comment]
The version is:

InfluxDB v0.9.6.1 (git: 0.9.6 6d3a8603cfdaf1a141779ed88b093dcc5c528e5e, built 2015-12-10T23:40:23+0000)

In Red Hat Enterprise Linux Server release 6.5 (Santiago)

**Comment by otoolep** [comment]
This behavior will not be addressed. If possible you should switch to the tsm1 engine, though it is still considered experimental. But it will be production ready in the near future.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L53 is where you switch the engine.

**Comment by pmagos00** [comment]
Thanks Philip, let me switch.

**Comment by pmagos00** [comment]
I switched to tsm1 engine, and increased the size of some of the attributes in the conf file, but i'm still getting the same previous behavior.

[influxdb.conf (2).txt](https://github.com/influxdata/influxdb/files/80228/influxdb.conf.2.txt)

:(

**Comment by jwilder** [comment]
@pmagos00 Your old shards are still using `bz1` as they would need to be converted to `tsm` shards manually.  You could try the convertor in the current nightlies by following the instructions [here](https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm).   

Going forward, your new shards should be `tsm` shards and you should not see that issue with them.

**Comment by pmagos00** [comment]
Thanks @jwilder, let me try now.
