### ISSUE TITLE
_internal keeps growing

### ISSUE THREAD

**Issue by francisdb** [influxdata/influxdb#5290]
We have a non-clustered instance of influxdb. The `_internal` database keeps growing over time. In about a month it has grown to 6G

InfluxDB 0.9.6.1 installed with apt-get on ubuntu 15.10 (gradually upgraded from older versions)

```
InfluxDB shell 0.9.6.1
> SHOW RETENTION POLICIES on _internal
name	duration	replicaN	default
monitor	168h0m0s	1		true
> use _internal
Using database _internal
> show measurements
name: measurements
------------------
name
engine
httpd
runtime
shard
subscriber
wal
write
````

```
sudo du -hs /var/lib/influxdb/data/_internal/
5.9G	/var/lib/influxdb/data/_internal/
```

partial show stat output
```
name: engine
tags: path=/var/lib/influxdb/data/_internal/monitor/4170, version=bz1
blksWrite       blksWriteBytes  blksWriteBytesC pointsWrite     pointsWriteDedupe
---------       --------------  --------------- -----------     -----------------
90342           280727184       77226437        4636360         4636360

name: engine
tags: path=/var/lib/influxdb/data/_internal/monitor/4355, version=bz1
blksWrite       blksWriteBytes  blksWriteBytesC pointsWrite     pointsWriteDedupe
---------       --------------  --------------- -----------     -----------------
120803          280119294       76451891        4473105         4473105

name: engine
tags: path=/var/lib/influxdb/data/_internal/monitor/4496, version=bz1
blksWrite       blksWriteBytes  blksWriteBytesC pointsWrite     pointsWriteDedupe
---------       --------------  --------------- -----------     -----------------
111069          279954378       75574847        4442394         4442394

name: engine
tags: path=/var/lib/influxdb/data/_internal/monitor/4572, version=bz1
blksWrite       blksWriteBytes  blksWriteBytesC pointsWrite     pointsWriteDedupe
---------       --------------  --------------- -----------     -----------------
1997029         96337659        92246865        1997645         1997395

name: shard
tags: engine=bz1, id=4572, path=/var/lib/influxdb/data/_internal/monitor/4572
fieldsCreate    seriesCreate    writePointsOk   writeReq
------------    ------------    -------------   --------
0               725             1998370         4520


```

**Comment by beckettsean** [comment]
@francisdb are there files in `/var/lib/influxdb/data/_internal/` older than two weeks? It is possible the retention policy isn't working for some reason.

Can you share the results of `SHOW SERIES` on the `_internal` database? It might be easier to put into a gist.

**Comment by francisdb** [comment]
@beckettsean Here is the (anonymised) output from `SHOW SERIES`
https://gist.github.com/francisdb/5bea588a3c42bd611fbd

**Comment by francisdb** [comment]
@beckettsean what reasons could there be for the retention not working?
Would deleting the _internal database possibly fix this issue permanantly?

**Comment by zstyblik** [comment]
@francisdb there was an issue with stale FDs with TSM1. As a result, retention policy ceased to work(https://github.com/influxdata/influxdb/issues/5207). I'm not sure when this was introduced. May be you're hitting this issue?

**Comment by francisdb** [comment]
@zstyblik is there a way to fix this? Can put server offline if needed and don't mind losing _internal.

**Comment by zstyblik** [comment]
@francisdb sorry, but devs will have to give you the answer. as I've said, I don't know when the issue was introduced or whether it's relevant to your version and/or storage engine etc. and whether it's actually fixed. I'm quite confused by the last comment in the issue I've referenced :)

**Comment by beckettsean** [comment]
@francisdb I know of no reason retention policies would not operate. I've not seen a failure in RPs before. I was simply speculating aloud on possible causes.

Dropping the `_internal` database would certainly reclaim the disk space, but I believe it will be recreated. You could try disabling internal metrics collection or change the database to which it writes. See https://docs.influxdata.com/influxdb/v0.9/administration/config/#monitor for more on the available configuration options for the monitoring system.

**Comment by francisdb** [comment]
@beckettsean thanks for the pointers, switched to `__internal`and did `drop database _internal`

will reopen ticket if I again see the database growing infinitely

**Comment by francisdb** [comment]
After 5 days we have our internal database passing 1G

```
$ sudo du -hs __internal/
1.2G	__internal/
```

the monitor section in config looks like this
```
[monitor]
  store-enabled = true # Whether to record statistics internally.
  store-database = "__internal" # The destination database for recorded statistics
  store-interval = "10s" # The interval at which to record statistics
```

**Comment by francisdb** [comment]
We still have this issue but I'l wait for a next release as it could be related to #5207

**Comment by zstyblik** [comment]
@francisdb I'm not seeing this issue with 0.10.0-beta1

```
# du -sh _internal/
4.7M    _internal/
```
