### ISSUE TITLE
[feature request] Add option to query parser to require specific clauses when executing queries

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#5292]
Until queries are able to be killed/stopped, it would be great if administrators could require the use (or forbid the use) of specific clauses in queries to prevent users from accidentally running very long-lived or wild-carded queries.

Example:

```
> select * from /.*/
Error: forbidden use of wildcard in measurement name

> select * from measurement
Error: "WHERE" clause required
```

**Comment by toddboom** [comment]
After talking about this at the Core Weekly, there are enough additions to the query engine and query manager that the underlying issues driving this are no longer relevant. Closing it out!
