### ISSUE TITLE
[0.10.0-nightly-d9ed54c] Data node reporting different raft-leader than raft nodes after leader change

### ISSUE THREAD

**Issue by sarat-k** [influxdata/influxdb#5293]
Hi,

I noticed this few times. I have 3 raft nodes and 1 data node. Initially, when the cluster was up and running, all nodes reported same node as raft-leader. I left the setup in that state for sometime and later when I checked, I see that all raft-nodes report different server as leader now (don't know when/why it switched) but data node is still showing the same old leader node as current raft leader.

All nodes are running with default configuration except for "tsm1" storage engine setting.

Thanks,
Sarat

**Comment by rossmcdonald** [comment]
@sarat-k Are you still seeing this behaviour with the 0.10.0 release or the nightlies?

**Comment by jsternberg** [comment]
Closing this issue since clustering is no longer supported in the open source version.
