### ISSUE TITLE
[feature request] Add configuration option to disable the `/debug/vars` HTTP API endpoint

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#5305]
Currently the `/debug/vars` endpoint is not protected by HTTP authentication, which could expose inadvertent debug information to anyone with network access to the InfluxDB instance. Adding the ability to disable this endpoint via configuration would prevent this issue.

**Comment by francisdb** [comment]
This is a serious issue:
https://www.shodan.io/search?query=influxdb

Is there a way to set up authentication for this resource?

**Comment by rossmcdonald** [comment]
Currently the only way to restrict access to the `/debug/vars` resource is by putting InfluxDB behind a proxy and enforcing authentication (or simply disallowing requests to `/debug`) at the proxy level.

**Comment by alekseyp** [comment]
I would love to see authentication here too.

**Comment by russorat** [comment]
this was added via https://github.com/influxdata/influxdb/pull/15222
