### ISSUE TITLE
Graphite: Values not accessible immediately after inserting

### ISSUE THREAD

**Issue by rkubik** [influxdata/influxdb#5312]
Hi there,

I am using the Graphite listener to receive data in a certain format. After writing a few lines to the graphite port I query the InfluxDB instance but don't receive and numeric values for the data I just inserted. I notice that if I leave my application overnight (writing to InfluxDB) after a certain period period InfluxDB will then report its values???

Versions: 0.9.6.1, 0.9.2.1

```
[[graphite]]
  enabled = true
  bind-address = ":2003"
  protocol = "tcp"
  name-separator = "."
  database = "bench"
  tags = []
  templates = [
    "host.measurement.metric"
  ]
```

```
SHOW MEASUREMENTS
Nothing
<write data to TCP port>
SHOW MEASUREMENTS
cpu
SHOW TAG KEYS FROM cpu
host
metric
SHOW TAG VALUES FROM cpu WITH KEY = metric
temp
load
SELECT * FROM cpu
Nothing
SELECT value FROM cpu WHERE host = "192_168_1_120" AND metric = "temp"
Nothing
```

This is an example of my graphite formatted data:

```
192_168_1_120.cpu.temp 45.5 1452212870
```

**Comment by beckettsean** [comment]
@rkubik this sounds very much like your timestamps are in the future when you initially query them. See https://docs.influxdata.com/influxdb/v0.9/troubleshooting/frequently_encountered_issues/#querying-after-now for more context on that.

If that is not the case, please include an example write and query from the same command line session, if possible.

**Comment by rkubik** [comment]
That was it, was missing the NTP package.
