### ISSUE TITLE
Valid values for "wal-flush-cold-interval"?

### ISSUE THREAD

**Issue by pootzko** [influxdata/influxdb#5317]
Hi,

what are valid valuse for `wal-flush-cold-interval` from `influxdb.conf`? _1s_ works fine but for example _5s_, _10s_, _15s_, _1m_ don't seem to work..

I migrated all the data from v0.8.7 to v0.9.6 and we don't have too much incoming data at the moment. Maybe ~100 50-character messages per minute which is not a lot but this will grow significantly in the future as more embedded devices get rolled out into production. 

One thing that's different with 0.9 is that I wasn't able to read/query the latest data from Influx. After a bit of playing around I realized that the data would become queryable as soon as the influxdb daemon would get restarted. 

Then I did a bit of research and found out about WAL. I played a bit with `wal-flush-cold-interval` and for now I guess it doesn't need to have a high time interval, but only the _1s_ seemed to work anyway. 

We need this because some of our screens poll the data and refresh graphs every 20 seconds so that's semi-realtime and waiting for the data to become available is not a good option. Setting `wal-flush-cold-interval` to `1s` however also seems like not the best idea.

Do you have any suggestions for this?

Thanks

**Comment by pootzko** [comment]
There is one more thing that I noticed.

We have a few .net console apps which gather data from the embedded devices. These listener apps and then send the data off to the influxdb. I noticed that when I shut down all the listeners, the data sometimes becomes queryable within a few seconds.

It feels almost as if the fact that the listeners are sending the data somehow keeps the TCP connection open and that that affects the influxdb. Could that be possible?

 I am using [InfluxData.Net](https://github.com/pootzko/InfluxData.Net) (which I'm maintaining) and this is the method that ultimately makes the HTTP request:

```cs

private async Task<HttpResponseMessage> RequestInnerAsync(
    TimeSpan? requestTimeout,
    HttpCompletionOption completionOption,
    CancellationToken cancellationToken,
    HttpMethod method,
    string path,
    HttpContent content = null,
    IDictionary<string, string> extraParams = null,
    bool includeAuthToQuery = true)
{
    HttpClient client = GetHttpClient();

    if (requestTimeout.HasValue)
    {
        client.Timeout = requestTimeout.Value;
    }

    StringBuilder uri = BuildUri(path, extraParams, includeAuthToQuery);
    HttpRequestMessage request = BuildRequest(method, content, uri);

    return await client.SendAsync(request, completionOption, cancellationToken);
}
```

I understand this is a third party library and you're not .net developers but it might give you some insight into what's happening here. The `HttpClient` comes from the .net (`System.Net.Http` namespace) framework and I did a bit of research on it - it should run the `.Dispose()` internally and that part is apparently handled by the framework itself. Could it be possible that a lingering TCP connection might be causing the behavior I am experiencing?

**Comment by pootzko** [comment]
Anyone please? :)

**Comment by jsternberg** [comment]
This config option no longer seems to exist in 0.13 so I'm going to close this. Please upgrade to the latest version. Thank you.

**Comment by pootzko** [comment]
I don't want to sound ungrateful for all the work you guys have done, but not replying for 5 months and then simply start closing cases and telling us to "update" is in my opinion not really a proper way to get rid of issues. During the last two days the same thing happened to a few issues I reported. I understand that we're getting this cool database with various tools for free and that we can't really expect anything besides to take what you're giving us as-is, but you can't expect everyone to spend a few days upgrading and fixing everything that broke because the upgrade didn't go smooth. I had to upgrade influxdb 3 times so far, and not once did it go smooth and without me having to spend a few days patching it up. You are not making a fade-in/out jquery plugin where nothing significant happens if it breaks. You're creating a quite serious piece of software and people rely on it. I understand you need to make money so a subscription would probably be the way to go but if you hide all the issues under the carpet and get bad rep as a result of that, people probably won't choose your software in the first place. I sincerely hope that this kind of issue 'resolving' won't become a common practice. Thanks again for all you're giving us, I imagine you're also very busy, but please also consider our perspective as well. Cheers.
