### ISSUE TITLE
[feature request] ability to flush the WAL as part of shutdown to prevent a pause on restart

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#5320]
It would be great if there was a shutdown command that told the database to stop accepting writes but continue to flush the WAL. That way the WAL could be emptied before shutdown so that the process restarted in a more predictable time frame.

**Comment by toddboom** [comment]
Are you seeing this take a long time on a particular setup? It seems to me that the new storage engine doesn't require a WAL flush on startup - it just reloads it into the cache, which is relatively quick. Maybe that will make it a non-issue?

**Comment by beckettsean** [comment]
@toddboom totally possible. Was a request from a support subscriber who just went from 0.9.4 to 0.9.6. Could very well be moot with `tsm`.

**Comment by jwilder** [comment]
Closing as this is not an issue in TSM.
