### ISSUE TITLE
Server crash: failed to store statistics: timeout

### ISSUE THREAD

**Issue by caligula1989** [influxdata/influxdb#5327]
I got this error message in the influxdb log, after which the server did not accept anything. There was no stack trace.

```
[monitor] 2016/01/08 11:42:03 failed to store statistics: timeout
runtime/cgo: pthread_create failed: Resource temporarily unavailable
```

**Comment by beckettsean** [comment]
@caligula1989 what version of the database are you running, and do you know if you're using the `bz1` or the `tsm` storage engine?

**Comment by beckettsean** [comment]
Did queries and writes timeout? Return an error?

Did the system recover after a process restart?

**Comment by caligula1989** [comment]
I use 0.9.6.1 with TSM.
I never actually waited long enough to get an error - but I pretty much waited a long time, so I assume timeouts.
After a process restart it worked.

**Comment by easyrasta** [comment]
same error

**Comment by e-dard** [comment]
Closing as no longer relevant to current InfluxDB version.

**Comment by franklsm1** [comment]
@e-dard  I am seeing this same error after upgrading from v0.13 to influx v1.1 with a shared volume that holds the data.

```
[query] 2016/12/19 22:59:25 SELECT * FROM test."default"./apim.*/ ORDER BY time DESC LIMIT 1
[monitor] 2016/12/19 22:59:41 failed to store statistics: timeout
```

writes still continue to work fine, but I get this same error over and over for multiple different read requests.

**Comment by e-dard** [comment]
@franklsm1 can you open a new issue with as much information as possible, please? There are tips in the issue template to suggest things to include.
