### ISSUE TITLE
0.9.6 is whisper like data retention possible

### ISSUE THREAD

**Issue by mhiller** [influxdata/influxdb#5335]
what i would like to do is be able to down sample data over time to the same measure similar to how whisper db works.

ie
< 5 days: keeps raw data

> 5 < 30d : downsample by 1min 
> 30d <6M :down sample to 5 min
> 6M drop

retention policy seem to allow me to simple create a max age on all the data.
I think i can accomplish the above scheme with multiple measures and use continious queries to manage it but that doesn't seem very scalable.

please advise.

**Comment by zachaller** [comment]
I agree something like this is needed #5234

**Comment by Galser** [comment]
Voting up. Especially for some capacity planning ..

**Comment by Madhu1512** [comment]
+1  Looking for this feature.

**Comment by qqren** [comment]
+++++1

**Comment by qqren** [comment]
when use Grafana as webUI, this feature is very useful.

**Comment by dmzaytsev** [comment]
+1
