### ISSUE TITLE
GROUP BY with COUNT returns 0

### ISSUE THREAD

**Issue by scottheckel** [influxdata/influxdb#5336]
I'm running InfluxDB v0.9.5 on OS X installed via homebrew.

I'm seeing behaviour that seems non-standard for a SQL-like language. It could definately be aided by having support for "having" #5266.  When I do a GROUP BY I expect doing a COUNT on a value should always be > 0 (unless maybe that value is always null).  The following is an explanation of my data where IP Address 1 and IP Address 2 are InfluxDB tags.

time|IPAddress1 | IPAddress2 | Packets
-----|-----------------|-----------------|--------------
10-01-2015|10.1.1.100 | 10.1.1.101 | 5
11-01-2015|65.2.3.4 | 97.2.3.4 | 10
01-01-2016|10.1.1.100 | 97.2.3.4 | 21

When I run `SELECT COUNT(Packets) FROM MyMeasurement WHERE time > '2015-12-01' GROUP BY IPAddress1, IPAddress2` I would expect only the last record to be returned (10.1.100 & 97.2.3.4 with a count of 1). Instead, all three combinations would be returned, but the first two will have a count of 0.

**Comment by beckettsean** [comment]
This is behaving as designed, and although it might not be intuitive for everyone, I don't think there's anything ambiguous or confusing about the output.

**Comment by scottheckel** [comment]
@beckettsean say I have millions of combinations of IPAddress1 and IPAddress2 in InfluxDB. That would mean I would get millions of results returned to me. That would be a *huge* bottleneck when it comes to bandwidth.

**Comment by beckettsean** [comment]
@scottheckel yes, it would, but that's a different problem. This is an architectural decision/limitation that we won't revisit unless there's significant widespread desire from the community. It is better addressed by implementing the `HAVING` clause (https://github.com/influxdata/influxdb/issues/5266), which would allow the query to toss results failing `HAVING COUNT(value) > 0`.

**Comment by scottheckel** [comment]
Once you know this behavior #5266 is a great fix. Another workaround would be a continuous query and then use a `WHERE` to weed it out, which is what I will probably do until `HAVING` is available.
