### ISSUE TITLE
Fix overflow for Counter32 counters

### ISSUE THREAD

**Issue by DatanoiseTV** [influxdata/influxdb#5337]
On SNMPv1/2c Hardware, when using influxsnmp - Counters with the type Counter32 will overflow. This results in peaks being generated. I think this should be fixed, but I have no solution for this myself.

Influxsnmp has closed this issue - https://github.com/paulstuart/influxsnmp/issues/10 and reported it as an influxdb issue.

**Comment by mjdesa** [comment]
@DatanoiseTV I'm

**Comment by DatanoiseTV** [comment]
If a SNMP v1/v2c device uses Counter32 for example for Ethernet Bytes Transmitted or Received etc., the coutner will overflow at some point. This causes influxsnmp to draw negative values.

**Comment by mjdesa** [comment]
What version of InfluxDB are your running?

**Comment by micw** [comment]
@DatanoiseTV , just use NON_NEGATIVE_DERIVATIVE from InfluxDB 0.10: https://docs.influxdata.com/influxdb/v0.10/query_language/functions/#non-negative-derivative
