### ISSUE TITLE
Influxdb knobs to control logging severity

### ISSUE THREAD

**Issue by sarat-k** [influxdata/influxdb#5339]
Hi,

Are there any knobs to control influxd logging ? I see lot of events are logged (GET/POST etc.). When millions of data points are added continuously, this will fill up logs and effect performance as well. Is there a way to set different logging levels ? If not, is there any planned enhancement ?

Thanks,
Sarat

**Comment by beckettsean** [comment]
The [configuration documentation](https://docs.influxdata.com/influxdb/v0.9/administration/config/) lists the logging configuration settings for each portion of the database.
