### ISSUE TITLE
Go imports not updated after migrating influxdb to influxdata

### ISSUE THREAD

**Issue by Myzie** [influxdata/influxdb#5347]
This is an issue for those of us that don't already have the old, now removed, `github.com/influxdb/influxdb` repository already present in our $GOPATH/src.

Seems like all influxdb subpackage imports need to be updated. For example:
https://github.com/influxdata/influxdb/blob/master/client/influxdb.go#L16

`github.com/influxdb/influxdb/models` --> `github.com/influxdata/influxdb/models`

Or am I missing something? Thanks!

**Comment by mschenk42** [comment]
I ran into this today, deleted the old github.com/influxdb/influxdb src and did a go get github.com/influxdata/influxdb.  The client package is still importing the old github.com/influxdb packages.

**Comment by rossmcdonald** [comment]
Closing in favor of #5388. We were waiting for the 0.10.0 release to resolve the import path issue, so this should be fixed soon.
