### ISSUE TITLE
[0.10.0-nightly-72c6a51] backup not working for TSM1

### ISSUE THREAD

**Issue by zstyblik** [influxdata/influxdb#5348]
Hello,

it seems like backup of TSM1 is not working despite being ticked off in https://github.com/influxdata/influxdb/issues/4977.

```
root@builder:~# influxd backup -host localhost:8086 /tmp/
2016/01/13 17:06:44 influxdb backup
2016/01/13 17:06:44 backing up metastore to /tmp/meta.00
2016/01/13 17:06:44 backup complete
root@builder:~# cat /tmp/meta.00 
HTTP/1.1 400 Bad Request

root@builder:~#
Connected to http://localhost:8086 version 0.10.0-nightly-72c6a51
InfluxDB shell 0.10.0-nightly-8fc4cbe
>
```

This is a newly spun up InfluxDB instance with no database created. However, the same thing happens with a "long" running one which has data and so on.
Yes, snapshot is enabled.

**Comment by joelegasse** [comment]
It looks like you are hitting the HTTP service, and not the database itself. If you are using the default ports, then the host should be set to `127.0.0.1:8088`. If that is the case, you can also just run `influxd backup <DEST>` as `127.0.0.1:8088` is the default value for the `-host` parameter.

You can also look at `influxd backup --help` for more options and their defaults.

#5349 will take care of detecting and reporting this error back to the user.

**Comment by zstyblik** [comment]
@joelegasse I see.
