### ISSUE TITLE
InfluxDB 500 timeout errors when ingesting data into InfluxDB

### ISSUE THREAD

**Issue by lostz** [influxdata/influxdb#5354]
Here is log 

[http] 2016/01/14 17:30:11 172.25.73.1 - root [14/Jan/2016:17:29:55 +0800] POST /write?consistency=&db=taishan&precision=s&rp= HTTP/1.1 500 44 - InfluxDBClient 5f247e30-baa1-11e5-8001-000000000000 16.310609716s

version 0.9.6

**Comment by lostz** [comment]
add more info  after i start monitor 

[monitor] 2016/01/14 17:37:18 failed to store statistics: timeout
[wal] 2016/01/14 17:37:20 Flush due to memory. Flushing 293 series with 1560941 points and 64512541 bytes from partition 1
[wal] 2016/01/14 17:37:23 Flush due to memory. Flushing 293 series with 1974560 points and 81626692 bytes from partition 1

**Comment by beckettsean** [comment]
@lostz this is expected behavior if you are writing too many points for the available resources. What are your machine specs and how many points per second are you writing?

**Comment by lostz** [comment]
about 6000

**Comment by lostz** [comment]
sorry about 


[wal] 2016/01/15 10:20:42 Flush due to memory. Flushing 293 series with 1880782 points and 77732201 bytes from partition 1
[wal] 2016/01/15 10:20:43 Flush due to memory. Flushing 293 series with 1974560 points and 81626692 bytes from partition 1

ok , I reduce the points one time .:)

**Comment by francisdb** [comment]
Should the body of the 500 not be a bit more specific than `{"error":"timeout"}`?

**Comment by jwilder** [comment]
Closing this as this is the expected behavior with `0.9.6` and the `bz1` engine.  The write timeout issue related to `b1` and `bz1` engines has been fixed in `0.10` by using the `tsm` engine.
