### ISSUE TITLE
[0.9.6.1] (Windows) panic: error writing the wal to the index

### ISSUE THREAD

**Issue by ikrush** [influxdata/influxdb#5355]
I have a Windows Service reading data from some sensors every second, aggregating this data every ten minutes and inserting it on InfluxDB.

[InfluxDB_crash_20160114.txt](https://github.com/influxdata/influxdb/files/90446/InfluxDB_crash_20160114.txt)

It's a single node instance of InfluxDB v.0.9.6.1 (bz1) compiled with Go v1.5.2 running on a machine with Windows Server 2012 R2 and 32GB of RAM.

**Comment by jwilder** [comment]
Windows is not an officially supported deployment platform currently.  See #5359.

**Comment by ikrush** [comment]
It is a pity because almost all the time-series databases only have support for Linux and this was (in my opoiniom) a key feature over them.

**Comment by jwilder** [comment]
@ikrush Please comment on #5359.  Understanding your use case will definitely help us figure out what we need to do to support windows.
