### ISSUE TITLE
[0.10.0-beta1] : debian jessie package: systemd unit file removed on upgrade

### ISSUE THREAD

**Issue by aderumier** [influxdata/influxdb#5356]
Hi, 

I have upgrade from 0.9.6 to 0.10.0-beta1, and the influxdb.service systemd unit file has been removed.

The problem seem to be in postinst script

elif [[ -f /etc/lsb-release ]]; then
    # Debian/Ubuntu logic

I don't have any /etc/lsb-release file on my debian jessie.
I think it's only available on ubuntu.

I could be better to use /etc/debian_version to test if it's  debian/ubuntu
Hi, 

I have upgrade from 0.9.6 to 0.10.0-beta1, and the influxdb.service systemd unit file has been removed.

The problem seem to be in postinst script

elif [[ -f /etc/lsb-release ]]; then
    # Debian/Ubuntu logic

I don't have any /etc/lsb-release file on my debian jessie.
I think it's only available on ubuntu.

I could be better to use /etc/debian_version to test if it's  debian/ubuntu

**Comment by rossmcdonald** [comment]
Fixed with #5357
