### ISSUE TITLE
New operators to do trending

### ISSUE THREAD

**Issue by sbouchex** [influxdata/influxdb#5358]
A nice to have would be to have some operators to estimate a value based on previous ones by using different algorithms (Moving average, Weighted moving average, least-square or Moving median)

see https://en.wikipedia.org/wiki/Moving_average
see https://en.wikipedia.org/wiki/Linear_trend_estimation

Operators can be:
linear: trend(serie, nb points)
least square: lstrend(serie, nb points)

**Comment by sslupsky** [comment]
Moving median would be a nice one to have.  Presently, to apply a median filter requires that you downsample your data.
