### ISSUE TITLE
Error building 0.9.6.1 from source

### ISSUE THREAD

**Issue by smebberson** [influxdata/influxdb#5384]
I've received the following error when building `0.9.6.1`:

```
package github.com/influxdb/influxdb/snapshot: cannot find package "github.com/influxdb/influxdb/snapshot" in any of:
	/usr/lib/go/src/github.com/influxdb/influxdb/snapshot (from $GOROOT)
	/go/src/github.com/influxdb/influxdb/snapshot (from $GOPATH)
```

I'm building this on Alpine Linux, in a Docker container with the following command:

```
RUN export GOPATH=/go && \
    echo "http://dl-2.alpinelinux.org/alpine/latest-stable/community" >> /etc/apk/repositories && \
    apk add --update go=1.5.2-r0 git musl-dev curl && \
    go get github.com/influxdb/influxdb && \
    cd $GOPATH/src/github.com/influxdb/influxdb && \
    git checkout -q --detach "v${INFLUXDB_VERSION}" && \
    go get -v -u -f -t ./... && \
    go clean -v ./... && \
    go install -v ./... && \
    chmod +x $GOPATH/bin/* && \
    mv $GOPATH/bin/* /bin/ && \
    apk del go git musl-dev && \
    rm -rf /var/cache/apk/* $GOPATH && \
    addgroup influxdb && \
    adduser -D -G influxdb influxdb && \
    mkdir -p /etc/influxdb /data/influxdb /data/influxdb/meta /data/influxdb/data /var/tmp/influxdb/wal /var/log/influxdb
```

The strange thing is, this has only just started happening recently. Here is a link to a recent build that worked https://hub.docker.com/r/smebberson/alpine-influxdb/builds/brxnfxyavpi8ktfxhnygu5c/

**Comment by smebberson** [comment]
Any ideas on this one?

**Comment by rossmcdonald** [comment]
@smebberson Do you get the same error if you change:

```
    git checkout -q --detach "v${INFLUXDB_VERSION}" && \
    go get -v -u -f -t ./... && \
```

To be:

```
    go get -v -u -f -t ./... && \
    git checkout -q --detach "v${INFLUXDB_VERSION}" && \
```

With the order reversed?

The `github.com/influxdb/influxdb/snapshot` package is a part of the 0.9.6.1 branch, but is no longer in master. I believe what's happening is that the second `go get` is bringing you back to `master`, which is causing the error.

**Comment by rossmcdonald** [comment]
Also, from your link above:

```
[91m# cd /go/src/github.com/influxdb/influxdb; git symbolic-ref HEAD
fatal: ref HEAD is not a symbolic ref
[0m
[91m/go/src/github.com/influxdb/influxdb on detached head; repairing
```

I believe `go get` was bringing you back to `master`, so you may have actually been building from master in your previous runs. It was just the removal of `snapshot/` that caused an error.

**Comment by smebberson** [comment]
@rossmcdonald, that solved my problem! Thanks for that. I can't believe I've been building against HEAD this whole time :(
