### ISSUE TITLE
Change default retention policy value

### ISSUE THREAD

**Issue by dbellantuono** [influxdata/influxdb#5386]
It is possible to change the default value of "default" retention policy?
I didn't find any documentation about it.

**Comment by bwolf** [comment]
Clarifying default vs. DEFAULT

default: The name of the RP that InfluxDB automatically generates when you create a new database. It has an infinite duration and a replication factor set to the number of nodes in the cluster. It is initially the DEFAULT RP as well, but that can be altered.

DEFAULT: The RP that InfluxDB writes to if you do not supply an explicit RP in the write.

Source https://docs.influxdata.com/influxdb/v0.9/guides/downsampling_and_retention/

**Comment by toddboom** [comment]
If changing the values are what's in question, the link above covers the required steps. If changing the name is the question, this is being discussed in #3733.
