### ISSUE TITLE
Fields from one retention policy transpire into other RPs with TSM

### ISSUE THREAD

**Issue by zstyblik** [influxdata/influxdb#5389]
Hello,

if CQ creates new fields eg. due to some kind of transformation and insert them into different RP in the same database, then these fields will transpire(show up) in other retention policies as well. They're empty, of course. Is this expected behaviour?

InfluxDB 0.10.0-beta, "ba7fc7d54802a777f345a583e1e3306947cf447b"
Storage engine is TSM1

Thanks.

**Comment by jwilder** [comment]
Yes. This is the expected behavior.  In the future, questions like this are better suited for the [mailing group](https://groups.google.com/forum/#!forum/influxdb).
