### ISSUE TITLE
utc conversion issue

### ISSUE THREAD

**Issue by Advoskr** [influxdata/influxdb#5392]
Hi again!

I have an issue writing points with specified timestamp to IDB. In my applications i form points using utc timestamp. For example, i'm in GMT +3 (Moscow), and so do my server with InfluxDb. I form a write query like this:
`Test Value=1i 1453210675551269000`

and then, in database, i get a point with timestamp `2016-01-19T10:37:55.551269Z` and i expected `2016-01-19T13:37:55.551269Z`

What am i doing wrong? Do i need to set unix clock or some parameters in influxdb configuration? This seems very bad for me.

**Comment by e-dard** [comment]
@Advoskr as per [the docs](https://influxdb.com/docs/v0.9/guides/writing_data.html#writing-data-using-the-http-api) all times in Influx are UTC, and expected to be given in UTC.

Therefore, when converting your local time to a numerical unix time, you should make sure you're converting your time to `UTC` before you do that. Likewise, when you fetch a point out it will be in `UTC`, so you'll need to convert it back if you want it in local time.

**Comment by Advoskr** [comment]
I already have done conversion to utc. For example, in my python code i make a timestamp like this:
`int(datetime.datetime.utcnow().timestamp()*1e+9)`. This gives me a timestamp, mentioned in my question, which is saved incorrectly to Influx (it's saved with -3 hours, as if GMT conversion was made on influx side implicitly). Maybe we misunderstood each other?

**Comment by rossmcdonald** [comment]
@Advoskr If you don't specify a timestamp when writing a point into the database, do you still see incorrect results? Your `1453210675551269000` timestamp is correct, which makes me believe the system time (which is used when no timestamp is provided) might be off.

**Comment by Advoskr** [comment]
@rossmcdonald Nope, when i doesn't use timestamp, everything works great. Here is a simple test i made right now. First, i made a write w/o timestamp:
`Test Value=1i`
Then, i made a write from python code:
`Test Value=1i 1453293503393879808`
and here is what i see:
![image](https://cloud.githubusercontent.com/assets/12170766/12453663/4e709c80-bfa5-11e5-876e-a0a7839cc1e1.png)

**Comment by rossmcdonald** [comment]
@Advoskr The `1453293503393879808` timestamp is `Wed, 20 Jan 2016 12:38:23 GMT`, which looks to be displaying correctly in your screenshot.

Are you sure that your Python timestamps are correct? Also, what do you get if you run `date -u` from your system terminal?

**Comment by Advoskr** [comment]
@rossmcdonald 
We've fully checked our python code and found an error. We form timestamp incorrectly and so the problem is not on influx side. Now everything is going to work OK. Thank you very much for your help
