### ISSUE TITLE
OOM durring compaction

### ISSUE THREAD

**Issue by mmoulton** [influxdata/influxdb#5397]
I am regularly getting an out of memory exception from influx during compaction events.

We have about 15 days of data where we are ingesting ~24k points every 10s from 6 telegraf sources (standard mem / cpu / net / plus docker with 100's of containers).

I am attaching screenshots from grafana of a compaction event that did not cause a OOM so you can see the spike from the event. I am also attaching a stack trace from an OOM event as well as the output from `show stats` and `show diagnostics`.

I am running InfluxDB 0.10.0-beta1 on a dedicated EC2 c4.2xlarge with 2 separate SSD EBS volumes.

Any idea if this is this a bug, configuration issue or a resource issue?

<img width="1574" alt="screen shot 2016-01-19 at 4 13 19 pm" src="https://cloud.githubusercontent.com/assets/571772/12435157/f20b9346-bec8-11e5-8c86-3694a1dfdb19.png">
<img width="1577" alt="screen shot 2016-01-19 at 4 13 32 pm" src="https://cloud.githubusercontent.com/assets/571772/12435160/f20e654e-bec8-11e5-8f71-661e9d8d3af1.png">
<img width="1180" alt="screen shot 2016-01-19 at 4 16 22 pm" src="https://cloud.githubusercontent.com/assets/571772/12435159/f20cc18a-bec8-11e5-8ffc-3fedabd3416e.png">
<img width="1481" alt="screen shot 2016-01-19 at 4 16 50 pm" src="https://cloud.githubusercontent.com/assets/571772/12435158/f20c67b2-bec8-11e5-8ef7-32d007bbc3dd.png">
[influxdb-oom-stack.txt](https://github.com/influxdata/influxdb/files/96707/influxdb-oom-stack.txt)
[influxdb-conf.txt](https://github.com/influxdata/influxdb/files/96719/influxdb-conf.txt)

**Comment by jwilder** [comment]
That panic occurred trying to write to the WAL.  From the stack traces, no compactions were running and one finished about 6 seconds before that panic.  There are some known issues where queries can cause OOM if there a many series being queried.

**Comment by mmoulton** [comment]
Interesting.

This happens multiple times a day and throughout the night. We have done test where we make sure no queries are running, only ingestions from telegraf and we still get an OOM.

Here is another stack trace from a bit before the last one I sent that shows the OOM just after the compaction event with no queries being executed.

[influxdb-oom-stack-2.txt](https://github.com/influxdata/influxdb/files/96744/influxdb-oom-stack-2.txt)

Anything I can do to better debug this @jwilder?

**Comment by jwilder** [comment]
@mmoulton That one occurred during a compaction.  It looks like you might not have enough RAM for your usage.  Those two panics occurred in different places that just happen to try and allocate memory.  I'd suggest bumping up the RAM on that server and see if that helps.

**Comment by mmoulton** [comment]
We are going to change the instance out for a `r3.xlarge` with 30GB RAM and see how that performs. I'll let you know once we have more data.

**Comment by jwilder** [comment]
@mmoulton Did upgrading your server resolve this issue?

**Comment by mmoulton** [comment]
Yes it has solved our problem for now. Over the last 7 days, this is our memory usage pattern:

![screen shot 2016-02-04 at 1 00 08 pm](https://cloud.githubusercontent.com/assets/571772/12827967/6924ddca-cb3f-11e5-819c-6b52c5419fcd.png)

I will close this issue now. Thanks for your help.
