### ISSUE TITLE
Influx 0.9.6.1 crashes intermittently during startup

### ISSUE THREAD

**Issue by lagergren** [influxdata/influxdb#5399]
Hello

We have an influx docker image deployed on an Amazon EC2 machine. Usually it starts flawlessly, but maybe one time in 100 we get crashes in startup. I've attached the trace log from influx, and it seems like the influxdb process crashes. There are go stack traces around. It is hard to reproduce, but should it somehow be easier for you, I can try to provide you with the docker image, that rarely crashes though

**Comment by lagergren** [comment]
[influx-fail.txt](https://github.com/influxdata/influxdb/files/97155/influx-fail.txt)

**Comment by lagergren** [comment]
[deployment.log.txt](https://github.com/influxdata/influxdb/files/97156/deployment.log.txt)

**Comment by lagergren** [comment]
Here is additional log which produces a similar stack trace after some load tests.

**Comment by lagergren** [comment]
[influx.err2.txt](https://github.com/influxdata/influxdb/files/117187/influx.err2.txt)

**Comment by jwilder** [comment]
Panic looks similar to #5303.

**Comment by jwilder** [comment]
Fixed in 0.11.
