### ISSUE TITLE
Binary package on the download area is not tar.gz

### ISSUE THREAD

**Issue by giganteous** [influxdata/influxdb#5402]
The **Standalone Binary** downloaded from https://influxdata.com/downloads/#download is the correct checksum, but it is not a tar.gz but a .zip file.

**Comment by rossmcdonald** [comment]
@giganteous Which link is serving a zip?

**Comment by rossmcdonald** [comment]
@giganteous Nevermind, found it. I'll get that updated shortly.

**Comment by rossmcdonald** [comment]
This has now been fixed with the latest beta release.
