### ISSUE TITLE
Multi tenancy in InfluxDB

### ISSUE THREAD

**Issue by krishnakanthpps** [influxdata/influxdb#5405]
Hi.. I have a few questions regarding my requirement with InfluxDB

Can I update the config file during runtime and have the settings configured with doing a influxdb restart?
Can I have multiple InfluxDB setups so as to overcome the issue of having multiple datasources not working?

**Comment by mjdesa** [comment]
@krishnakanthpps this is neither an issue or a feature request. Please use the [mailing list](https://groups.google.com/forum/#!forum/influxdb) for these kinds of issues.
