### ISSUE TITLE
Invalid line protocol format crashes influxdb 0.9.6.1

### ISSUE THREAD

**Issue by acobaugh** [influxdata/influxdb#5407]
This write is coming from graphios (which needs to be fixed to escape backslashes). This shouldn't crash influxd, though.

```
[http] 2016/01/20 14:52:15 172.24.28.254 - graphios [20/Jan/2016:14:52:15 -0500] POST /write?p=%5BREDACTED%5D&u=graphios HTTP/1.1 204 0 - Python-urllib/2.6 4e5de0a5-bfaf-11e5-b736-000000000000 3.140773ms
[cluster] 2016/01/20 14:52:16 close remote connection from 172.24.28.206:34321
panic: failed to parse point: `Disk,check=C:\,host=lp-admin-t01.lionpath.psu.edu,nagios_location=Shields value=52.45 1453319535802451556`: unable to parse 'Disk,check=C:\,host=lp-admin-t01.lionpath.psu.edu,nagios_location=Shields value=52.45 1453319535802451556': invalid tag format
```

**Comment by phalenor** [comment]
Reading the documentation, I shouldn't have to escape the backslash. The problem is likely because the backslash is the last character in the tag value, immediately proceeded by a comma.

**Comment by jwilder** [comment]
#5382 looks like it should prevent the panic, but it's still not parseable.  Looks like `\` needs to be escapable as well because it's escaping the `,` and causing the tag format to become invalid.

**Comment by e-dard** [comment]
As @jwilder mentions, this won't panic as of `master`, but it's not currently possible to have a tag value ending in a literal slash if there are tags after it (#5231).

Unfortunately the only workaround at the moment is to add another character to the tag value (which could be an escaped space, say), e.g., like this:  `Disk,check=C:\\ ,host=....`. Of course this means querying on that tag value would involve having to specify the space too, so it's not really a good alternative I'm afraid.

**Comment by phalenor** [comment]
Hmm, agreed. How easy would it be possible to either allow backslash to be escaped? Or would it be preferable to handle the backslash-as-last-character case?

Should I file a new issue or just re-purpose this one?

**Comment by jwilder** [comment]
@e-dard @phalenor I think the line protocol would need to handle `\\` to make this work.  You would need to write in `Disk,check=C:\\,host=lp-admin-t01.lionpath.psu.edu,nagios_location=Shields value=52.45 1453319535802451556`

**Comment by e-dard** [comment]
Yep, makes sense. I would be happy to look at this, if you like.

**Comment by jwilder** [comment]
@e-dard If you have time to look at it that would great.  Thanks!
