### ISSUE TITLE
Upgrade from 0.9.5.1 to 0.9.6

### ISSUE THREAD

**Issue by bovy89** [influxdata/influxdb#5420]
Hi,
I need to upgrade influxdb from 0.9.5.1 to 0.9.6 but "CHANGELOG" says that I need to start with a fresh database.

There is any chance to upgrade without wipe out my databases?

Can you suggest some way to migrate?

Thanks

**Comment by jwilder** [comment]
If you were using the `tsm1` engine, then yes, you would need to wipe your DB as that engine was experimental in those releases.  If you were not using `tsm1` engine, then you can upgrade without wiping your DB.

**Comment by bovy89** [comment]
How can i check my engine version?
Probably I'm using tsm1, but I need to be sure.

**Comment by jwilder** [comment]
It would be in your config:
```
[data]
engine = "tsm1"
```

If `engine` is not there, `bz1` is the current default.
