### ISSUE TITLE
Querying the same measurement name across retention policies and across databases seems to merge results

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#5421]
[0.10 as of b3058e8]

The first database `first` has two retention policies: `oneday` and `default`.
The second database `second` has only the `default` retention policy.
- Querying the same measurement name across retention policies in the same database:  

Data in `first`:

```
> SELECT * FROM first."default".cats
name: cats
----------
time                              value
2016-01-21T19:27:59.403171611Z  500
2016-01-21T19:28:01.843087149Z  500

> SELECT * FROM first."oneday".cats
name: cats
----------
time                              value
2016-01-21T19:27:40.388308857Z  100
2016-01-21T19:27:43.644166253Z  100

> SELECT * FROM first."default".dogs
name: dogs
----------
time                              value
2016-01-21T19:28:16.098437146Z  600
2016-01-21T19:28:18.658116246Z  600
```

Calculating mean `cats` for the different RPs with two queries:

```
> SELECT mean(value) FROM first."default".cats
name: cats
----------
time                    mean
1970-01-01T00:00:00Z    500

> SELECT mean(value) FROM first."oneday".cats
name: cats
----------
time                    mean
1970-01-01T00:00:00Z    100
```

Calculating mean `cats` for the different RPs with one query:

```
> SELECT mean(value) FROM first."default".cats,first."oneday".cats
name: cats
----------
time                    mean
1970-01-01T00:00:00Z    300
```

I expected (maybe incorrectly) two results, one for each rp, kind of like this:

```
> SELECT mean(value) FROM first."default".cats,first."default".dogs
name: cats
----------
time                    mean
1970-01-01T00:00:00Z    500


name: dogs
----------
time                    mean
1970-01-01T00:00:00Z    600
```

Finally, it looks like the average of `first."default".cats` and `first."oneday".cats` shows up when I calculate the mean `first."default".dogs` and `first."oneday".cats` in one query:

```
> SELECT mean(value) FROM first."oneday".cats,first."default".dogs
name: cats
----------
time    mean
0      300


name: dogs
----------
time    mean
0      600
```

That happened even when I made `oneday` the default RP for `first`.
- Querying the same measurement name across databases:

Data in `second`:

```
> SELECT * FROM second."default".cats
name: cats
----------
time                              value
2016-01-21T19:46:34.871854129Z  800
2016-01-21T19:46:35.566794753Z  800

> SELECT mean(value) FROM second."default".cats
name: cats
----------
time                    mean
1970-01-01T00:00:00Z    800
```

When I calculate the mean `cats` across databases (and across databases and RPs), I get one result. I (maybe incorrectly) expected two results:

```
> SELECT mean(value) FROM first."default".cats,second."default".cats
name: cats
----------
time                    mean
1970-01-01T00:00:00Z    650

> SELECT mean(value) FROM first."oneday".cats,second."default".cats
name: cats
----------
time                    mean
1970-01-01T00:00:00Z    450
```

Interestingly, the average of `first."default".cats` and `second."default".cats` shows up instead of the average of just `second."default".cats` when I calculate the mean `cats` in `second` and the mean `dogs` in `first`:

```
> SELECT mean(value) FROM first."default".dogs,second."default".cats
name: cats
----------
time                    mean
1970-01-01T00:00:00Z    650


name: dogs
----------
time                    mean
1970-01-01T00:00:00Z    600
```

I know there's a lot going on here and some of it might be intended behavior, but it seems like the last queries under each bullet are an issue.

**Comment by rossmcdonald** [comment]
Verified that this occurs on 0.10.0 as well.

**Comment by rbetts** [comment]
Closing this won't fix.
