### ISSUE TITLE
Fails to revert to .bak databases after failed upgrade 0.9.6stable>0.10beta

### ISSUE THREAD

**Issue by discoduck2x** [influxdata/influxdb#5422]
failed to convert my 200gb databases with 0.10 convertion tool so
im copying the .bak database folder back into the /data folder  (which is specified in /etc/influxdb/influxdb.conf as dir = "/var/lib/influxdb/data") without the .bak extension and reverting to 0.9.6.1 stabble version

starting up 0.9.6 and going into the CLI "show databases" only shows _internal ,, if i do "use mydbname" then i CAN do "show series" but if i do "show measurements" it says "database not found" 

am i fubard and need to start fresh or is there anything worth trying?

**Comment by mjdesa** [comment]
@discoduck2x can you walk me through the steps you did when you were upgrading.

**Comment by discoduck2x** [comment]
@mjdesa 

1. was sitting on 0.9.4.2
2. upgraded to 0.9.6.1 stable ,, checked some queries all seemd fine
3. upgraded to 0.10beta , upgrade went well no problems encountered.
4. decied to convert the bz1 databases to tsm
5. followed the convert instructions, ran influx_tsm tool,,, took forever, asked here if i should be able to abort but just got told that the .bak folder is a full plain copy which should work to revert to.
6. aborted convertion and simply renamed the .bak folder 
7. unable to query the databases but could still see something as described in op.

decided to start fresh,, but after inserting 2-3 days of server metrics into 0.10beta and tested grafana against it i got too long query respones so went back to 0.9.6.1,, but same thing,, so stepped back to 0.9.4.2 but without any history. (still got the .bak data if i get time to test again)

performance issue feels like #5429

**Comment by mjdesa** [comment]
when you say you decided to start fresh, did you spin up a new instance, or just replace the version on the machine?

**Comment by discoduck2x** [comment]
@mjdesa just uninstalled and installed fresh on same machine

**Comment by mjdesa** [comment]
To uninstall you ran `dpkg -r ...`

**Comment by discoduck2x** [comment]
@mjdesa On centos 7,yum remove influxdb

**Comment by jwilder** [comment]
There was an issue w/ the backup files that should be fixed via #5472 and #5454.
