### ISSUE TITLE
RPM packages doesn't create /var/log/influxdb directory

### ISSUE THREAD

**Issue by dennisjac** [influxdata/influxdb#5425]
After installing the latest RPM package on my Fedora system the influxdb service cannot be started because /var/log/influxdb hasn't been created during the installation.

"mkdir /var/log/influxdb && chown influxdb /var/log/influxdb" fixes this and after that I can start the service successfully.

**Comment by rossmcdonald** [comment]
This may have been fixed already, as `/var/log/influxdb` is a part of the nightlies:
```
rpm -qpl influxdb-nightly.x86_64.rpm
/etc/influxdb/influxdb.conf
/etc/logrotate.d/influxdb
/usr/bin/influx
/usr/bin/influx_inspect
/usr/bin/influx_stress
/usr/bin/influx_tsm
/usr/bin/influxd
/usr/lib/influxdb/scripts/influxdb.service
/usr/lib/influxdb/scripts/init.sh
/var/lib/influxdb
/var/log/influxdb
```
