### ISSUE TITLE
Upgrade `0.9` Cluster to `0.10` Cluster

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#5426]
This issue will cover the necessary steps required to make the server upgradable.  This is currently WIP while I collect more data.

## `0.9x` directory structure
```
├── data
│   └── _internal
│       └── monitor
│           └── 1
├── hh
├── meta
│   ├── id
│   ├── peers.json
│   ├── raft.db
│   └── snapshots
└── wal
    └── _internal
            └── monitor
                └── 1
	                └── _00001.wal

```

`id` content:
```
1
```

`peers.json` content:
```
["localhost:8088"]
```

`SHOW SERVERS`

```
> show servers
id      cluster_addr    raft    raft-leader
1       localhost:8088  true    true
```

## `0.10` directory structure

```
├── data
│   └── _internal
│       └── monitor
│           └── 1
├── hh
├── meta
│   ├── node.json
│   ├── peers.json
│   ├── raft.db
│   └── snapshots
└── wal
    └── _internal
            └── monitor
                └── 1
	                └── _00001.wal
```

`node.json` content:
```
{"ID":2,"MetaServers":["Corys-MacBook-Pro.local:8091"]}
```

`peers.json` content:
```
["Corys-MacBook-Pro.local:8088"]
```

`SHOW SERVERS`

```
> show servers
name: data_nodes
----------------
id      http_addr                       tcp_addr
2       Corys-MacBook-Pro.local:8086    Corys-MacBook-Pro.local:8088


name: meta_nodes
----------------
id      http_addr                       tcp_addr
1       Corys-MacBook-Pro.local:8091    Corys-MacBook-Pro.local:8088
```

## Starting an `0.10` instance after an `0.9` instance:

```
├── data
│   ├── _internal
│   │   └── monitor
│   │       └── 1
├── hh
├── meta
│   ├── id
│   ├── node.json
│   ├── peers.json
│   ├── raft.db
│   └── snapshots
└── wal
    ├── _internal
        └── monitor
            └── 1
                ├── _00001.wal
                └── _00002.wal
```

`id` content:
```
1
```

`node.json` content:
```
{"ID":3,"MetaServers":["Corys-MacBook-Pro.local:8091"]}
```

`peers.json` content:
```
["Corys-MacBook-Pro.local:8088"]
```

`SHOW SERVERS`

```
> show servers
name: data_nodes
----------------
id      http_addr                       tcp_addr
2       localhost:8088                  localhost:8088
3       Corys-MacBook-Pro.local:8086    Corys-MacBook-Pro.local:8088


name: meta_nodes
----------------
id      http_addr                       tcp_addr
1       Corys-MacBook-Pro.local:8091    Corys-MacBook-Pro.local:8088
```

**Comment by fxstein** [comment]
After the 0.8.x to 0.9.x upgrade issues (I finally gave up and dumped a year of historical data) I surely hope that 0.9 to 0.1 will get managed much better and automated to a much higher degree.

**Comment by corylanou** [comment]
@fxstein This is only for the `cluster` part of the upgrade.  Upgrading a single node from `0.9` to `0.10` only requires converting your shards to the new TSM format, which we have a tool for here: https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm.

We wrote an exporter for the `0.8` to `0.9` but it did require that you followed very specifically the recommended structure.  I understand that was very limited in scope though, and likely many people were unable to follow that format.  Our goal is to make sure that all upgrades are much easier going forward.

Can you elaborate on what issues you encountered in the `0.8` to `0.9` upgrade?  Were you able to use the exporter?  Any feedback would be appreciated.
