### ISSUE TITLE
[0.10] A query with math resulting in infinity returns a non-JSON error

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#5427]
```
$ curl -G --data-urlencode 'q=SELECT flushDuration/0 FROM wal LIMIT 1' --data-urlencode 'db=_internal' localhost:8086/query
json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: +Inf
```

The response headers indicate the content type is `application/json`, but the response is clearly not valid JSON. 

Tested against 865b267eb0119af04f97226cde36e1d02487e1e3.

**Comment by jsternberg** [comment]
I think we now handle division by zero by returning zero instead of `NaN`. If this is still happening in 0.13, please reopen. Thanks.
