### ISSUE TITLE
Extra functions

### ISSUE THREAD

**Issue by ocdogan** [influxdata/influxdb#5435]
There is a need for functions:
1. Math "Round", "Min", "Max"
2. Oracle's "NVL" or MySql's "IFNULL"

**Comment by toddboom** [comment]
@ocdogan We already have functions for `MIN()` and `MAX()`, and there's no concept of null values in InfluxDB, so neither `NVL` nor `IFNULL` are really applicable.

Moving the request for `ROUND()` to #3691. Thanks!
