### ISSUE TITLE
delete old data points in v0.9.6

### ISSUE THREAD

**Issue by mingzhou** [influxdata/influxdb#5439]
I would like to use influxdb as a time-series db for storing tick position infomation. For example, I insert the following record yesterday:

|time | tick | volume|
|---| --- | --- |
| 123456 | "GOOG" | 100 |
| 123456 | "MSFT" | 200 |
| 123456 | "AAPL" | 300 |

Today, I find that I made a big mistake, I should change the record into:

|time | tick | volume|
|---| --- | --- |
| 123456 | "GOOG" | 100 |
| 123456 | "AAPL" | 200 |

Since there's no delete clause in v0.9.6, how could I  `DELETE` the old record and insert the new correct record?
I can replace the "AAPL" record. But I cannot delete the "MSFT" record.
Thanks.

**Comment by mjdesa** [comment]
@mingzhou unfortunately there's no way to delete a point from InfluxDB, however you can rewrite the point you'd like to delete to have a null value.

```
insert stock,tick=MSFT volume=200 123456
````

you could nullify the value by rewriting the point

```
insert stock,tick=MSFT deleted=true 123456
```

This wont work for 0.10.0+, but it will for 0.9.6-

**Comment by mingzhou** [comment]
@mjdesa Why this wont work for 0.10.0+?

**Comment by max3163** [comment]
And what is the solution for 0.10.0+ ?

**Comment by mjdesa** [comment]
@mingzhou in 0.10.0 we're changing the underlying storage engine. Instead of storing all of the fields for a point together like a row, we'll be storing each field for a point in its own column.

@max3163 I don't know that we have a work around yet, I'll look into it.

**Comment by mingzhou** [comment]
@mjdesa Thanks. Influxdb is CRUd now. I understand delete operation should be as less as better. But we still have a solution to delete specific data points.

**Comment by mjdesa** [comment]
@mingzhou you're welcome. Let me know if there's anything else I can help with.
