### ISSUE TITLE
[0.9.6] InfluxDB Replication Super Slow

### ISSUE THREAD

**Issue by ChromoX** [influxdata/influxdb#5444]
I have a 3 computer cluster of InfluxDB servers. They are correctly clustered together as the `SHOW SERVERS` command notes all members in the cluster.

Two of the nodes(the one I write to, and another) will be almost automatically consistent with each other. The third takes days sometimes.

Is there a command I can use to force a sync between all servers?

I'm using the default retention policy.

**Comment by mjdesa** [comment]
@ChromoX what version of InfluxDB are you using?

**Comment by ChromoX** [comment]
`2016/01/16 07:19:06 InfluxDB starting, version 0.9.6.1, branch 0.9.6, commit 6d3a8603cfdaf1a141779ed88b093dcc5c528e5e, built 2015-12-10T23:40:23+0000`

**Comment by mjdesa** [comment]
@ChromoX can you confirm that this is no longer an issue with `0.10.0beta1`?

If you could test the replication against the new version it would be greatly appreciated. If you are to do so, please set up the `0.10.0beta1` as its own cluster. It is possible that upgrading from `0.9.6` to `0.10.0` will lead to data loss.

https://s3.amazonaws.com/influxdb/influxdb-0.10.0-0.beta1.x86_64.rpm
https://s3.amazonaws.com/influxdb/influxdb_0.10.0-0.beta1_amd64.deb

**Comment by ChromoX** [comment]
Yeah I can do that. I'll get to it tomorrow.

**Comment by mjdesa** [comment]
Awesome. Thank you.

**Comment by ChromoX** [comment]
Installed and loaded most of my data back into InfluxDB. Replication seems to be fine. I'll post here again, or open a new ticket(If you close this one) if I start to see super slow replication again.

**Comment by mjdesa** [comment]
@ChromoX closing this issue for now. If you see any problems in the future I can reopen it.
