### ISSUE TITLE
[feature request] Expand functionality of the query language

### ISSUE THREAD

**Issue by tokudan** [influxdata/influxdb#5450]
I do have a big issue with the way influx aggregates data.
Here's some example data I have to work with a lot.

```
name: current_clients_online
time      node     value
12:00     srv01     7
12:00     srv02     2
12:01     srv01     5
12:01     srv02     2
12:02     srv01     9
12:02     srv02     4
13:01     srv01     1
13:01     srv02     5
```

Now I want to know how many total clients (srv01+srv02) I had at each minute.

```
SELECT sum(value) FROM current_clients_online WHERE $timeFilter GROUP BY time(1m) fill (null)
```

That's easy and yields the expected results.
Now a couple of weeks later I'm not interested at the numbers I had each minute and just want the maximum number of the total connected clients (srv01+srv02) for each hour.

```
SELECT max(sum(value)) FROM current_clients_online WHERE $timeFilter GROUP BY time(1h) fill (null)
```

Obviously this does not work, it sums up all values it can get ahold of:

```
time      value
12:00     29
13:00     6
```

This is obviously wrong, I would have expected influx to sum up srv01+srv02 for each timestamp and then return me the max value encountered during the timespan of 12:00 – 12:59, for example:

```
time      value
12:00     13
13:00     6
```

The real problem I have with the current implementation is that I have to analyze the data stored in influx first, see how often it updates (currently 1m), work out a reasonable GROUP BY time clause and hope that this update cycle never changes to less than 1m. Also the client application needs to read all data and then calculate the max itself, when influxdb should be able to do that on its own.
This gets more complicated if I want to display multiple series through grouping by additional tags.

I think Influxdb needs to make a clear distinction between functions that aggregate data only over time and functions that aggregate only over series. For example graphite has sumSeries (sums up all series at each timestamp) and integral (sums up all timestamps for each series) and grouping by time can be done e.g. through summarize.
Does influxdb have a similar function set?

**Comment by markgoffin** [comment]
+1
It would be great to be able to specify different aggregate functions for each `GROUP BY`.

Say I have a measurement called `bytes_recv` with tags `eth0`, `eth1`. There doesn't seem to be a way to get a sensible measure of the total received over both interfaces when using a `GROUP BY time`. Ideally, I would want to take `last` or `mean` over the time interval for each series, and then `sum` over those results.

**Comment by mjdesa** [comment]
@tokudan I'm not sure I follow exactly. Can you send me a data set you're working with and the results of what you think the queries should be.

**Comment by mjdesa** [comment]
@tokudan If I'm not mistaken, you could use a `continuous query` or and `into` query to achieve the functionality you're looking for.

```
CREATE CONTINUOUS QUERY sum_srv01_srv02_per_min ON mydb BEGIN
  SELECT sum(value), as value INTO sum_srv01_srv02 FROM current_clients_online
  GROUP BY time(1m) fill (null)
END
```
If you simply wanted to do this in an ad-hoc fashion you could run the query

```
 SELECT sum(value), as value INTO sum_srv01_srv02 FROM current_clients_online
  WHERE $timeFilter GROUP BY time(1m) fill (null)
```

then to get the `max` value over that hour you could issue the query

```
SELECT max(sum(value)) FROM sum_srv01_srv02 WHERE $timeFilter GROUP BY time(1h) fill (null)
```

**Comment by mjdesa** [comment]
it seems like what you're asking for is a way to have different aggregate functions apply to different `group by` intervals.

**Comment by tokudan** [comment]
@mjdesa:
> If I'm not mistaken, you could use a continuous query or and into query to achieve the functionality you're looking for.
`CREATE CONTINUOUS QUERY sum_srv01_srv02_per_min ON mydb BEGIN
  SELECT sum(value), as value INTO sum_srv01_srv02 FROM current_clients_online
  GROUP BY time(1m) fill (null)
END`

A continuous query suffers from the same problem: I have to know the update cycle of the data. If this changes from 1m to e.g. 15s, then the query will give me ((srv01+srv01+srv01+srv01)+(srv02+srv02+srv02+srv02)) instead of (mean(srv01,srv01,srv01,srv01)+mean(srv02,srv02,srv02,srv02)). In this example I'm using mean, but  min or max would be sensible requests as well, it depends on the data.
It's irrelevant if I run this as a continuous query or when trying to use the data.

> it seems like what you're asking for is a way to have different aggregate functions apply to different group by intervals.

That would be one possible implementation. Another would be to provide another function set that does not aggregate over time, which is what graphite offers.

If it's still relevant, here is some example data. "value" represents the number of currently connected clients
```
SELECT value FROM "connected.clients" WHERE (time > (now() - 5m)) AND (node = 'VHW21-2' OR node = 'VHW21-3' OR node = 'DeepThought') GROUP BY node
name,tags,time,value
connected.clients,node=DeepThought,1453923482,1
connected.clients,node=DeepThought,1453923542,1
connected.clients,node=DeepThought,1453923602,1
connected.clients,node=DeepThought,1453923661,1
name,tags,time,value
connected.clients,node=VHW21-2,1453923482,0
connected.clients,node=VHW21-2,1453923542,0
connected.clients,node=VHW21-2,1453923602,0
connected.clients,node=VHW21-2,1453923661,0
connected.clients,node=VHW21-2,1453923722,0
name,tags,time,value
connected.clients,node=VHW21-3,1453923482,2
connected.clients,node=VHW21-3,1453923542,2
connected.clients,node=VHW21-3,1453923602,2
connected.clients,node=VHW21-3,1453923661,1
connected.clients,node=VHW21-3,1453923722,1

```

**Comment by mjdesa** [comment]
@tokudan 
>((srv01+srv01+srv01+srv01)+(srv02+srv02+srv02+srv02)) instead of (mean(srv01,srv01,srv01,srv01)+mean(srv02,srv02,srv02,srv02)).

do you mean `mean((srv01+srv01+srv01+srv01)+(srv02+srv02+srv02+srv02))`?

**Comment by mjdesa** [comment]
And is this the query you want to run and what you'd expect it to output?

>SELECT value FROM "connected.clients" WHERE (time > (now() - 5m)) AND (node = 'VHW21-2' OR node = 'VHW21-3' OR node = 'DeepThought') GROUP BY node
name,tags,time,value
connected.clients,node=DeepThought,1453923482,1
connected.clients,node=DeepThought,1453923542,1
connected.clients,node=DeepThought,1453923602,1
connected.clients,node=DeepThought,1453923661,1
name,tags,time,value
connected.clients,node=VHW21-2,1453923482,0
connected.clients,node=VHW21-2,1453923542,0
connected.clients,node=VHW21-2,1453923602,0
connected.clients,node=VHW21-2,1453923661,0
connected.clients,node=VHW21-2,1453923722,0
name,tags,time,value
connected.clients,node=VHW21-3,1453923482,2
connected.clients,node=VHW21-3,1453923542,2
connected.clients,node=VHW21-3,1453923602,2
connected.clients,node=VHW21-3,1453923661,1
connected.clients,node=VHW21-3,1453923722,1

**Comment by tokudan** [comment]
> And is this the query you want to run and what you'd expect it to output?

No, that was only the query I ran to get the example data.


> do you mean mean((srv01+srv01+srv01+srv01)+(srv02+srv02+srv02+srv02))?

No sorry, that was unclear from my side.
What I want is (using my example data):
(square brackets show what I want influxdb to calculate):
time                  value
1453923482     3 [DeepThought + VHW21-2 + VHW21-3]
1453923542     3 [DeepThought + VHW21-2 + VHW21-3]
1453923602     3 [DeepThought + VHW21-2 + VHW21-3]
1453923661     2 [DeepThought + VHW21-2 + VHW21-3]
1453923722     1 [VHW21-2 + VHW21-3]
And I want to be able to give influxdb a "GROUP BY time(X)" phrase where X is not necessarily the update cycle of the data. After a couple of hours I might only be interested in seeing data for an average over 2 minutes, so the output should then be:
time                  value
1453923480     3 [((timestamp 1453923482: DeepThought + VHW21-2 + VHW21-3) + (timestamp 1453923542: DeepThought + VHW21-2 + VHW21-3)) / 2]
1453923600     2.5 [((timestamp 1453923602: DeepThought + VHW21-2 + VHW21-3) + (timestamp 1453923661: DeepThought + VHW21-2 + VHW21-3)) / 2]
1453923720     1 [VHW21-2 + VHW21-3]

So influxdb should
1. Go to each timestamp
2. sum up all values within that timestamp (DeepThought + VHW21-2 + VHW21-3)
3. Look at each 2m window and give me the average of the sums.

Right now the data is updated once per minute, but that might change anytime to a smaller or bigger update cycle, so I cannot rely on a (continuous) query that relies on a "sum(value) GROUP BY time(1m)" to generate a measurement that I can then average over.

**Comment by mjdesa** [comment]
I think I follow. Correct me if I'm wrong, but you'd like to be able to apply a function for each point with a specific timestamp, and then run some aggregate function across some time range.

Which version of Influx are you using?

I cant think of a way to do this in versions before `0.9.6`, but I believe there is a way to do this in `0.10.0`.

**Comment by tokudan** [comment]
Yes, I want one aggregate function over all values with the same timestamp and then be able to group by the time range that currently makes sense (e.g. when I look at a year's data I probably care only about one or two averaged, min or max datapoints per day).
I'm using the debian unstable package 0.9.6.1+dfsg1-4, which seems to be the most recent non-beta release.

**Comment by mjdesa** [comment]
In your 0.9.6 are you using tsm or bz?

**Comment by tokudan** [comment]
I'm using the tsm1 engine.

**Comment by mjdesa** [comment]
This should work with tsm1.

If you chance your schema from

```
current_clients_online,node=srv01 value=7 1234
current_clients_online,node=srv02 value=9 1234

current_clients_online,node=srv01 value=3 1235
current_clients_online,node=srv02 value=8 1235

current_clients_online,node=srv01 value=3 1236
current_clients_online,node=srv02 value=2 1236

current_clients_online,node=srv01 value=8 1237
current_clients_online,node=srv02 value=1 1237
```

to

```
current_clients_online srv01=7 1234
current_clients_online srv02=9 1234

current_clients_online srv01=3 1235
current_clients_online srv02=8 1235

current_clients_online srv01=3 1236
current_clients_online srv02=2 1236

current_clients_online srv01=8 1237
current_clients_online srv02=1 1237
```

then the queries

`SELECT (srv01 + srv02) as value INTO sum_current_clients_online FROM current_clients_online WHERE $timeFilter`

followed by

`SELECT mean(value) FROM sum_current_clients_online WHERE $timeFilter GROUP BY time(15m)`

should work. The only problem with this is if either `srv01` or `srv02` is null then `value` in `sum_current_clients_online` will be null for the timestamp when that occurred.

**Comment by tokudan** [comment]
Using the tag name as a field name... I would have to use wildcards for field names then. If that's supported...
I'm gathering statistics for about 1500 nodes right now and if I have to enter them manually in the queries it won't work, as pretty much every day a handful of new nodes register and others drop out.

> The only problem with this is if either srv01 or srv02 is null then value in sum_current_clients_online will be null for the timestamp when that occurred

I think this will be a problem. A single null value will be in there at every timestamp. On average only about 90% of the nodes are online and send statistics.

I need to give this some more thought tomorrow as its midnight for me right now.

**Comment by markgoffin** [comment]
It could also be considered the other way around. Currently the discussion is around summing the individual field values at each timepoint, and then taking a mean over the time group. This is fine if the field values are all at the same timepoint but this is probably the rare case as opposed to the usual case (though you could interpolate the values between time points if desired). Instead, the aggregate function (such as mean, min or max) could be applied for each field of interest (number of clients on a node) over the time group first, this would provide the mean/min/max number of clients for each node (~1500 values) for each time group. Then a sum over these 1500 mean values for each time group could be performed to get a measure of the total number of clients (across all nodes) over each time group.

I think the key point is that when merging series which have the same field key but different tag values, the same aggregate function is applied to group the values by time **and** to combine the values from the different series. Whereas having a different function for each process would be nice.

As mentioned above I'm not sure that changing the schema type is viable because I don't think it is possible to sum over field keys using a regex. Hopefully this makes sense I'm not off-track.

**Comment by tokudan** [comment]
@markgoffin
> This is fine if the field values are all at the same timepoint but this is probably the rare case as opposed to the usual case

It doesn't really matter, if they all have the same timestamp. The important function that influxdb is currently missing is that I can specify a precision (e.g. 1h) and specify how influx should aggregate the data within that time range.

@mjdesa:
I'm sorry, but that solution does not seem to work for me. As I mentioned the node tag does not have a fixed set of values but is very dynamic.
```
> insert test,group='abc' srv01=5 1454006625
> insert test,group='abc' srv02=20 1454006625
> select * from test
name: test
----------
time            group   srv01   srv02
1454006625      'abc'   5       20

> select sum(*) from test
ERR: error parsing query: expected field argument in sum()
```

**Comment by mjdesa** [comment]
@tokudan I updated the name of the issue and labeled it as a feature request.

**Comment by thunderstumpges** [comment]
I just wanted to chime in here also and give my +1, as well as mention that I agree with @markgoffin that the elegant way to solve this (at least from a usability point of view) is to have an option of specifying a different aggregation for each field in the group-by. This solves the specific issue here as well as many others. It is not always just multiple servers in a single dimension like this, but could be an arbitrary number of dimensions.

We are really anxious for this, as currently making any kind of cross-cluster metrics is nigh impossible (unless you use mean for everything, or make darn sure you group by exactly the same time as your reporting interval, and use sum)

I am completely stuck with absolute counters which require a derivative.. there is no way I can figure to then combine that later because the derivative needs to be computed on each series for the time interval, then aggregated again to get the total across servers (or whatever other dimension)

I do really like influxdb, but I am really feeling the limitations of the query language.

**Comment by xaniasd** [comment]
@mjdesa any new insights on this one?

**Comment by mjdesa** [comment]
@pauldix

**Comment by jsternberg** [comment]
I think this issue is now solvable with subqueries. I'm not entirely certain the exact query that would be needed, but you can run one aggregate using a subquery and then run another aggregate using the top level query.

So maybe something like this:

```
SELECT max(sum) FROM (SELECT sum(value) FROM current_clients_online GROUP BY time(1m)) WHERE $timeFilter GROUP BY time(1h)
```

If you need any help putting together a query like this, please create a topic on our new community forum at https://community.influxdata.com. I'm going to close this issue since I think this functionality is implemented now.
