### ISSUE TITLE
[0.10.0-beta] Backup restores **ALL** the metadata not just the one in question

### ISSUE THREAD

**Issue by zstyblik** [influxdata/influxdb#5451]
Hello,

I've backed up one database like so:

```
influxd backup -host localhost:8088 -database telegraf /root/tmp/telegraf-backup
```

And then restored it (somewhat) like so:

```
influxd restore -datadir /data/db -metadir /data/db -database telegraf /whatever/path/to/backup
```

However, now InfluxDB instance shows all databases from previous(source) instance of InfluxDB. This is because of `raft.db` holds all of this information.
This doesn't feel right, does it?

I have tried to omit `-metadir`. However, presence of `/data/db` and absence of `/data/meta` really confuses InfluxDB which feels like another issue completely.

**Comment by zstyblik** [comment]
"Of course", this is with 0.10.0-beta1/2 and TSM1 engine.

**Comment by zstyblik** [comment]
Also, It leads me to the question whether just metadata backup, `%  influxd backup -host localhost:8088 /backup/path;`, makes sense, resp. is it necessary for anything? Perhaps in a Cluster?

**Comment by pauldix** [comment]
Closing this in favor of #7758
