### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by eminden** [influxdata/influxdb#5455]
Having following panic at startup on latest nightly(version 0.10.0.n1453660386, branch master, commit 58e0eed9cb166e0b004e6b41a4d64c39d24b40f4), attaching full stack trace.
[influxdb.log.txt](https://github.com/influxdata/influxdb/files/105413/influxdb.log.txt)

This happened after getting 500 errors while writing data from last november till today using the following retention policy and then restarting,

CREATE RETENTION POLICY "raw" ON "delivery" DURATION 60d REPLICATION 1 DEFAULT;

[cacheloader] 2016/01/26 16:17:07 reading file /var/lib/influxdb/wal/delivery/raw/50/_00023.wal, size 901330
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*WriteWALEntry).UnmarshalBinary(0xc267408090, 0xc26cf20000, 0x50d9eb, 0x50d9eb, 0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:497 +0xb5d
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*WALSegmentReader).Next(0xc27f0b2100, 0xc264d4d000)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:677 +0x743
github.com/influxdb/influxdb/tsdb/engine/tsm1.func·003(0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cache.go:354 +0x3a1
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*CacheLoader).Load(0xc25c50b520, 0xc24e1b40a0, 0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cache.go:376 +0x10f
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).reloadCache(0xc2555cbf40, 0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:602 +0xe2
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Open(0xc2555cbf40, 0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:130 +0x1da
github.com/influxdb/influxdb/tsdb.func·027(0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/tsdb/shard.go:123 +0x3a9
github.com/influxdb/influxdb/tsdb.(*Shard).Open(0xc2797098c0, 0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/tsdb/shard.go:133 +0x5e
github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0xc2080e6420, 0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/tsdb/store.go:349 +0xc49
github.com/influxdb/influxdb/tsdb.(*Store).Open(0xc2080e6420, 0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/tsdb/store.go:417 +0x334
github.com/influxdb/influxdb/cmd/influxd/run.func·003(0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:426 +0xda9
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc2080e0180, 0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:464 +0x5e
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc208074510, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:119 +0xdd2
main.(*Main).Run(0xc20803b700, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdata/influxdb/cmd/influxd/main.go:86 +0x422
main.main()
	/tmp/tmp.cRBI1lQ7kg/src/github.com/influxdata/influxdb/cmd/influxd/main.go:46 +0xdc

**Comment by jwilder** [comment]
@eminden Would be able to send me your `/var/lib/influxdb/wal/delivery/raw/50/_00023.wal` file by chance?  jason@influxdb.com?
