### ISSUE TITLE
HTTP logging logs the date twice

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#5456]
Currently, the HTTP endpoint will log the date twice:

```
[http] 2016/01/26 20:35:24 133.70.1.215 - - [26/Jan/2016:20:35:24 +0000] POST /write?db=stress&precision=n HTTP/1.1 204 0 - Go 1.1 package http 53749428-c46c-11e5-a742-00000000000
0 289.465276ms
```

The second date is unneeded and adds unneeded noise to the logs.

**Comment by sczk** [comment]
It looks like the response_loggers for httpd and meta both pass their own formatted dates here:

[/services/httpd/handler.go] =>(https://github.com/influxdata/influxdb/blob/58e0eed9cb166e0b004e6b41a4d64c39d24b40f4/services/httpd/handler.go#L819-L844)
[/services/httpd/response_logger.go(https://github.com/influxdata/influxdb/blob/ce8cf05b0e7da643df1abeec2916edbe7687754c/services/httpd/response_logger.go#L104)

[/services/meta/handler.go] =>(https://github.com/influxdata/influxdb/blob/58e0eed9cb166e0b004e6b41a4d64c39d24b40f4/services/meta/handler.go#L425-L450)
[/services/meta/response_logger.go](https://github.com/influxdata/influxdb/blob/58e0eed9cb166e0b004e6b41a4d64c39d24b40f4/services/meta/response_logger.go#L104)

If the logger is going to be prepending it's own timestamp no matter what, these may want to be removed. I'm not sure what the plans for the logger are.
