### ISSUE TITLE
[0.10.0-beta2] Creating a cluster is now hardly automatable

### ISSUE THREAD

**Issue by PierreF** [influxdata/influxdb#5461]
To achieve a cluster with 0.10.0-beta2 (and nightly 0.10.0.n1453881635) I have to:

* Edit /etc/influxdb/influxdb.conf and add or change:
```
[meta]
  bind-address = "influxdb01.example.com:8088"
  http-bind-address = "influxdb01.example.com:8091"
[http]
   bind-address = "influxdb01.example.com:8086"
```
* Run one node "normally" (e.g. influxdb -config /etc/influxdb/influxdb.conf)
* Run the other node with "-join" option (e.g. influxdb -config /etc/influxdb/influxdb.conf -join influxdb01.example.com:8091)

Now, if node need to be restarted, we need to omit the "-join" option.

With 0.9.x, we could use the same configuration file for all node by specifying "-hostname $HOSTNAME"  to command line.
Also with 0.9.x, we could keep "-join" option, it was only used the first time.

It would be very great if "-join" option behave as in 0.9.x. It allow to easily start a new cluster/add new node without manual action to start the new node for the FIRST time.
For the configuration file and hostname, wouldn't be a good idea to use the server hostname instead of "localhost" as default value ? It would allow to create a cluster without tunning configuration file.

**Comment by stepanstipl** [comment]
+1
- It would be very helpful to be able to start all servers with same `-join nodeA:8091,nodeB:8091,nodeC:8091` config.
I would suggest that in the long term, it might be desirable to have behaviour like for example Cassandra. You provide set of nodes (seeds) and starting node will try to connect to these and read the topology of the cluster.

- Also all started nodes join both as data_nodes and meta_nodes... is this expected? The output from `show servers` is slightly different than described in docs, so it doesn't show who's member of raft cluster, but seems like all of them? (`[metastore] 2016/01/27 23:56:42 [DEBUG] raft: Node 10.32.47.5:8088 updated peer set (2): [10.32.47.5:8088 10.32.63.4:8088 10.32.89.4:8088 10.32.55.5:8088 10.32.46.2:8088]`) I would expect just first 3, based on docs. Right now if I start five servers, I'll end up with all 5 being meta. (Btw. I'm not completely sure here, meta component == raft member?)

- Is there any way how to see more detailed info about nodes than just `SHOW SERVERS`?

- When I stop node, it never disappears from `SHOW SERVERS` listing.

- Config behaviour is not consistent, when using bind-address in port only form, such as `:9091`, it'll end-up behaving differently for different components - some of them will listen on localhost only, some on all interfaces:

  - meta http will become `127.0.0.1:9091`
  - meta raft will become `localhost:9088`
  - admin http will become `[::]:9083`
  - httpd will become ` [::]:9086`

(running `v0.10.0-beta2`)

Thanks guys for good work btw., InfluxDB's really exciting, and if I can help testing/debugging these, I would be more than happy to.

**Comment by jsferrei** [comment]
I noticed the config behavior too. It appears that if you do not include a hostname/ip in your bind-address, it will just use "localhost" as that is the default hostname and the ability to set hostname in config was removed. 

Looking at history, it looks like it was removed to make way for code that detects the hostname, but that never made it to this build.

**Comment by pauldix** [comment]
You can set the bind addresses through environment variables as well. I think that will make automated deploys easier. For example set `INFLUXDB_META_BIND_ADDRESS=hostname:8091`.

Options set through the environment variables will be used over those specified in the config file.

**Comment by sebito91** [comment]
Stepan's description is the same thing we're seeing on our "cluster".

If we want to segregate raft from data nodes it doesn't appear we can do
that, it seems all nodes join as both meta and data servers for the whole
cluster.

If we start to fail nodes to test resiliency, the so-called raft nodes that
are specified in the -join command aren't actually the only ones managing
the cluster as ALL nodes get added to peers.json.

On Monday, February 1, 2016, Paul Dix <notifications@github.com> wrote:

> You can set the bind addresses through environment variables as well. I
> think that will make automated deploys easier. For example set
> INFLUXDB_META_BIND_ADDRESS=hostname:8091.
>
> Options set through the environment variables will be used over those
> specified in the config file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdata/influxdb/issues/5461#issuecomment-178267403>
> .
>


-- 

Sebastian Borza
---------------
PGP: EDC2 BF61 4B91 14F2 AAB4  06C9 3744 7F3F E411 0D3E

**Comment by zstyblik** [comment]
@pauldix is it possible to set/over-ride all configuration file variables through ENV like that? Is this documented somewhere? Because I've missed this and it really is useful thing, if true. Thanks!

**Comment by ashb** [comment]
@pauldix Setting that env doesn't appear to work in 0.10.0:

```
root@2b6afb2b117c:/# INFLUXDB_META_BIND_ADDRESS=2b6afb2b117c:8091 influxd --config /etc/influxdb/influxdb.conf
...
2016/02/13 16:59:23 InfluxDB starting, version 0.10.0, branch 0.10.0, commit b8bb32ecad9808ef00219e7d2469514890a0987a, built 2016-02-04T17:06:04.850564
2016/02/13 16:59:23 Go version go1.4.3, GOMAXPROCS set to 2
2016/02/13 16:59:23 Using configuration at: /etc/influxdb/influxdb.conf
[meta] 2016/02/13 16:59:23 Starting meta service
[meta] 2016/02/13 16:59:23 Listening on HTTP: 127.0.0.1:8091
```

**Comment by ashb** [comment]
For anyone following along at home make sure you get the ports the right way round!:

```
INFLUXDB_META_BIND_ADDRESS=$(hostname -i):8088 \
INFLUXDB_META_HTTP_BIND_ADDRESS=$(hostname -i):8091 \
influxd ...```

(The example above had me confused as 8091 is the default http meta service port.)

**Comment by jwilder** [comment]
Improved in `0.11`.  Closing as this issue since it is no longer applicable after `0.11`.
