### ISSUE TITLE
After upgrade 0.9 -> 0.10 derivative functions returns empty result

### ISSUE THREAD

**Issue by emanuelis** [influxdata/influxdb#5466]
```
SELECT non_negative_derivative(mean(value))*0.01666 FROM "freeradius_value" WHERE "type_instance" = 'Access_Requests' AND $timeFilter GROUP BY time(1m), "host"
```
I have this query in Grafana and it worked with InfluxDB 0.9
But after upgrade to 0.10 it returns empty set.

How should I change the query to make it work?

**Comment by jwilder** [comment]
Closing since this is very likely a dup of #5474.  @emanuelis see the workaround in that issue. You may need to manually edit your `meta/node.json`.
