### ISSUE TITLE
ERR: dial rcp: missing address (0.9.6.1 -> 0.10.0-0.beta2)

### ISSUE THREAD

**Issue by lassizci** [influxdata/influxdb#5473]
After converting from bz1 -> tsm following the steps in https://github.com/influxdata/influxdb/blob/master/cmd/influx_tsm/README.md I'm no longer able to read any measurements. I stopped influxdb, upgraded and run the conversion and after that it starts, but when I try to query measurements, I get:

```
InfluxDB shell 0.10.0
> use telegraf
Using database telegraf
> show measurements
ERR: dial tcp: missing address
```

also there are these in the log:
```
[write] 2016/01/28 20:13:34 write failed for shard 30 on node 1: factory is not able to fill the pool: dial tcp: missing address
[monitor] 2016/01/28 20:13:34 failed to store statistics: write failed: factory is not able to fill the pool: dial tcp: missing address
```

I had only one node when I started and now `show servers` says:
```
InfluxDB shell 0.10.0
> show servers
name: data_nodes
----------------
id	http_addr	tcp_addr
1	localhost:8088	
3	localhost:8086	localhost:8088


name: meta_nodes
----------------
id	http_addr	tcp_addr
2	localhost:8091	localhost:8088
```

I also tried to rollback to bz1 and 0.9.6.1 but the server no longer starts. It just pukes go stacktrace like this: https://gist.github.com/lassizci/4a895e7900bb65f0a0d5 when I have restored .bak data dirs and wals.

I'm using the default configuration shipped with 0.10.0-0.beta2, except these bind addresses:

```
[admin]
  bind-address = "0.0.0.0:8083"

[http]
  bind-address = "0.0.0.0:8086"
```

And just because I had those in 0.9.6.1

So, is there anything to do to save the existing data?

**Comment by jwilder** [comment]
Unfortuantely, this was an issue with `beta2` that should be resolved with #5447 which is now in `beta3`.

**Comment by lassizci** [comment]
Looks like it didn't resolve by upgrading to rc1

**Comment by corylanou** [comment]
Was this a single node instance?  I see 2 data nodes, and I suspect that was part of the bug we fixed in RC1.  However, upgrading to RC1 won't fix it, as you have already found out.  @dgnorton wrote an inspect tool that used to be able to write out the raw shard data to an import script, but I don't think it's been tested with this new release.  That might be something we should look into as we are likely going to have a few people fall into this scenario.

**Comment by lassizci** [comment]
@corylanou, yes, a single node. I've never had more than one node.

**Comment by jwilder** [comment]
@lassizci You may need to manually fix your `node.json` file so that your `ID` is `1`.  See #5474.
