### ISSUE TITLE
Failed to store statistics: error fetching meta data : no leader detected during fetchMetaData

### ISSUE THREAD

**Issue by 2sbsbsb** [influxdata/influxdb#5480]
Version - 0.9.5.1
Influx set up on aws with 4 nodes cluster on aws

Steps - 
1. Created DB ,created retention policy of 1H, 1 week, 1 month, 3 month, 6 month and 1 year. 
2. Changed 3 months retention policy to 6 years in values to put historical data. 
3. Created continuous query to roll up the original measurement to 1 minute data. 

Periodically kept checking the original measurement and the query was returning the values.
However after a day it stopped returning me values. I checked the logs and this is what is getting printed over and again. 

no leader available for reporting timeout
Failed to store statistics: error fetching meta data : no leader detected during fetchMetaData
Failed to store statistics: error fetching meta data : no leader detected during fetchMetaData

**Comment by rossmcdonald** [comment]
@2sbsbsb Those error messages mean that the cluster doesn't have an active leader, which can prevent writes and distributed queries from successfully completing. The `0.10.0` release has a re-architected clustering mechanism that should avoid issues like this. 

Can you try upgrading and let us know if the issue persists? For the `0.10.0` upgrade you'll have to recreate your cluster. Documentation [here](https://docs.influxdata.com/influxdb/v0.10/guides/clustering/).

**Comment by jsternberg** [comment]
Clustering [has been removed](https://influxdata.com/blog/update-on-influxdb-clustering-high-availability-and-monetization/) from the open source version so I'm going to close this issue. If you need an open source solution for high availability, please try the [relay](http://docs.influxdata.com/influxdb/latest/high_availability/relay/). Thanks.
