### ISSUE TITLE
[0.9.6.1] CLI doesn't throw error on invalid USE command

### ISSUE THREAD

**Issue by botmayank** [influxdata/influxdb#5484]
OS: Ubuntu 15.04 64 bit
Installed using pre built .deb package

I just started with InfluxDB and I thought it's weird that the CLI says "using database xyz" on calling USE xyz even if xyz hasn't been created and only throws an error once you try to insert an entry into the database. I think reporting an error while calling USE might help prevent typos.

**Comment by toddboom** [comment]
I believe this was fixed with #5183.
