### ISSUE TITLE
Continuous query don't create appropriate field

### ISSUE THREAD

**Issue by r0bj** [influxdata/influxdb#5491]
Influxdb version: 0.10.0-0.beta2
OS: Ubuntu 15.10

Continuous query:

```
CREATE CONTINUOUS QUERY op_time ON telegraf BEGIN SELECT read_time/reads AS read_time_per_op INTO diskio FROM diskio END
```

```
> show continuous queries
name: _internal
---------------
name    query


name: telegraf
--------------
name    query
op_time CREATE CONTINUOUS QUERY op_time ON telegraf BEGIN SELECT read_time / reads AS read_time_per_op INTO telegraf."default".diskio FROM telegraf."default".diskio END
```

There is no effect in `diskio` measurement, no additional field `read_time_per_op`.

**Comment by zstyblik** [comment]
@r0bj I don't think this is going to work. However, you can try to execute CQ by hand. What happens if you do?

**Comment by r0bj** [comment]
It seems that running by hand works ok:
```
> SELECT read_time / reads AS read_time_per_op INTO telegraf."default".diskio FROM telegraf."default".diskio
name: result
------------
time	written
0	77028
```

**Comment by zstyblik** [comment]
@r0bj and have the new values been inserted/updated into diskio? What does log have to say? Did you check - `[continuous_querier]` and `[query]`? Anything there?

**Comment by r0bj** [comment]
@zstyblik yes, new values are inserted into diskio.
In logs there is:
```
[continuous_querier] 2016/02/01 20:19:10 error executing query: CREATE CONTINUOUS QUERY op_time ON telegraf BEGIN SELECT read_time / reads AS read_time_per_op INTO telegraf."default".diskio FROM telegraf."default".diskio END: err = continuous queries must be aggregate queries
```

So it looks like it wont work anyway.
I'm looking for a way of divide two series somehow without luck.
