### ISSUE TITLE
User managment with provisioning tools

### ISSUE THREAD

**Issue by dmke** [influxdata/influxdb#5496]
Hi,

what is the recommended way to manage users and databases using automated provisioning tools (like Ansible)?

I'm currently working on a provisioning script, which does the following (in an idempotent matter):

- create admin user
- for each user:
  - create database with same name
  - create user or set password
  - grant all privileges to user

Prior to execution of each step I have to query whether the thing-to-be-created already exists (by grep'ing through the output of, eg. `show users`). This, of course, is error prone and fails apart when the output format changes (even if that output was generated via `influx ... -format csv`).

Overall, this doesn't feel nice. Is there a better way?

—Dominik

**Comment by rossmcdonald** [comment]
@dmke I think your best option would be to use the `influx` commands JSON-formatted output. For example, you can get a JSON-formatted response with the users in the system by running:

```
influx -execute 'show users' -format json
```

And then throwing the output into whatever tool you are using (or just use [jq](https://stedolan.github.io/jq/)) to extract what you need. The JSON output is not always pretty, but it will definitely beat attempting to scrape CSV or unformatted output.

**Comment by dmke** [comment]
Yeah, JSON would indeed be the format of choice, but when provisioning a database server (on any machine for that matter) i'd like to keep the complexity low (i.e. less dependencies = smaller attack surface), although this means that I usually have to resort bash scripts (I really need to improve my Python-fu, as Python is already present as dependency for Ansible...)

Ideally, I'd like to use some "`influxdb_{user,db,priv}`" modules, just like I could do with [`postgres_*`](https://github.com/ansible/ansible-modules-core/tree/devel/database/postgresql). Do you know if something like that already exists?

**Comment by rossmcdonald** [comment]
@dmke No, unfortunately there aren't any Ansible plugins for InfluxDB available at the moment. That being said, I don't think it would be too hard to put one together since we already have a [Python client](https://github.com/influxdata/influxdb-python) available. I'm not familiar with what it would take to create an Ansible module with the existing Python client, but I'm assuming (maybe incorrectly) that it wouldn't be too difficult.

**Comment by dmke** [comment]
I see. Well, time to amp up my Python, I guess :-)

Just another question: Given `http.auth-enabled` set to true in the `influxdb.conf`, how can I create an admin user with a local shell (i.e. on the machine running the `influxd` binary), when the package was just installed?

I've encountered #2278 but that ticket seems to be stale.

**Comment by rossmcdonald** [comment]
@dmke You'll need to create a user prior to enabling authentication. The workflow should look like:

- Install InfluxDB with default configuration
- Start InfluxDB
- Create admin with the `influx` CLI: 
`influx -execute 'CREATE USER admin WITH PASSWORD 'changeme' WITH ALL PRIVILEGES'` (you can also use the HTTP API)
- Enable authentication through the config
- Restart the service
- Authenticate with credentials above

It's not as ideal as the proposed solution in #2278, but it will work.

**Comment by dmke** [comment]
Well, thank you, anyway :-)
