### ISSUE TITLE
Add stats and diagnostics to TSM engine

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#5499]
TSM engine needs stats and diagnostics about compactions, file counts, cache size, etc..

Original item listed in #4977

**Comment by jonseymour** [comment]
I plan to start work on adding cache related statistics to the shard statistics sets. This is my plan at this point which I am documenting here to solicit feedback from others.

The statistics I plan to capture are the following counters and levels.

(A counter always increases, a level measures a point in time quantity).

- **snapshotPreparedBytes**

This counter is the total number of bytes that have been transferred from the cache to a snapshot. This is updated during the preparation of a snapshot.

- **snapshotCommittedBytes**

This counter is the total number of bytes in snapshots that have been fully committed to TSM files.This is updated when a committed snapshot is released from the cache.

The difference between **snapshotCommittedBytes** and **snapShotPreparedBytes** is the number of bytes held in the snapshot at the time of the stat sample.

- **snapshotsPrepared**

This counter is the number of snapshots that have been created. 

- **snapshotsCommitted**

This counter is the number of snapshots that have been fully committed to disk.

The difference between these two numbers is the number of active snapshots. In a healthy system this number should be between 0 and 1. A system experiencing transient write errors might expect to see this number rise.

- **cacheAge**

This is a level, in milliseconds, which represents the cache was last snapshotted. This number is an indication of how busy the cache is. Large numbers indicate a cache which is idle with respect to writes.

- **commitTime**

This is a counter which counts the number of seconds that the commit lock is held. 

The expression **snapshotCommittedBytes** / **commitTime** provides an indication off how fast the WAL logs are being committed to TSM files.

/cc @jwilder

**Comment by jonseymour** [comment]
Mmm. One issue becomes apparent immediately. The current shard statistics measure quantities at the level of the shard without reference to the underlying storage engine.

The statistics I am proposing are very TSM specific. Does this imply that I need to introduce a new statistic set specifically for TSM?

**Comment by jwilder** [comment]
@jonseymour The `committed`/`prepared` naming seems like it's building on top of implementation details in #5689 which is not currently in master.  Instead, can you add stats based on the current functionality in master?

I think adding a `tsm` stats set makes sense.  I would add a tag for the shard ID to each stat so we can view stats per shard or in aggregate.

**Comment by jonseymour** [comment]
Makes sense. I've updated the document above to use terms that are not implementation specific. The semantics haven't really changed. I'll certainly prepare the commits for this change with reference only to master only.

**Comment by jwilder** [comment]
#5758 adds some disk related stats to tsm.

**Comment by jonseymour** [comment]
@jwilder Thanks for the heads up

**Comment by jonseymour** [comment]
Added revision #5 to take account of statistics captured in #5758. The **snapshotCapturedBytes** statistic used here is intended to allow calculation of cache throughput between any two instances of time.

**Comment by jonseymour** [comment]
Screen shot that demonstrates how to calculate "CompactedBytesPerSecond"

`SELECT (last(cachedBytes) - first(cachedBytes)) / (last(WALCompactionTimeMs) - first(WALCompactionTimeMs)) * 1000.000 as CompactedCacheBytesPerSecond FROM _internal.monitor.tsm1_cache WHERE time > now() - 1h GROUP BY time(5m), path`

![compacted bytes per second](https://www.dropbox.com/s/2tpqyzscx5hn42s/Screenshot%202016-02-22%2016.05.30.png?dl=0&raw=1)

This is a measure of how fast influx can write bytes our of a WAL snapshot log into a new TSM file.
