### ISSUE TITLE
Logging options for TSM engine

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#5500]
TSM engine needs more configurable logging options related to snapshots, WAL, compactions, filestore, etc.. (including turning logging off) 

Original issue from #4977

**Comment by corylanou** [comment]
@jwilder do we have specifics on what?  Are we talking additional logs (prefixes), or most options to turn on/off the logging?

**Comment by jwilder** [comment]
@corylanou This issue was for about having a config option to turn on more logging.  Basically, a `TraceEnabled` type config option.

**Comment by e-dard** [comment]
Fixed via #6980.
