### ISSUE TITLE
Add checksum verification to TSM inspect tool

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#5502]
TSM files contain a checksum per block.  The `inspect_tsm` tool should be updated to be able to verify and report any blocks that fail verification.

Original issue from #4977

**Comment by seiflotfy** [comment]
I am working on this, these are my steps:
* [ ] implement validate on block in tsm1 reader
* [ ] expose to inspect_tool

**Comment by seiflotfy** [comment]
What is the expected behaviour here? https://github.com/influxdata/influxdb/blob/master/tsdb/engine/tsm1/reader.go#L910
Return error?

**Comment by jwilder** [comment]
@seiflotfy It should not validate there.  That `TODO` and others can be removed.  The `influx_inspect` tool should be able to _report_ the issue.

**Comment by toddboom** [comment]
Agreed. I think for now, the only goal is to have the tool run the verification. The database itself won't do any checksum enforcement yet.

**Comment by seiflotfy** [comment]
OK on it!
