### ISSUE TITLE
Process termination

### ISSUE THREAD

**Issue by Tangerino** [influxdata/influxdb#5509]
After importing some data, when I browse the database with Grafana, the influxd process stops.
I confess that I can't interpret the log, but I have attached it anyway.
Best regards
[influxd.log.txt](https://github.com/influxdata/influxdb/files/113968/influxd.log.txt)

**Comment by rossmcdonald** [comment]
@Tangerino The error you hit was:

```
fatal error: runtime: out of memory
```

Which means the process ran out of memory when attempting to pull the results for your query. You may need to bump the memory on the InfluxDB server or modify your query/schema to be more efficient. I'd also recommend you try upgrading to 0.10.0 (currently in pre-release with RC1) assuming this is a test database. The new storage engine (tsm) is much more memory efficient than it's 0.9.6.1 predecessor (the bz1 engine).
