### ISSUE TITLE
(Client) Database(name string) and Databases() both return redundant error as second value

### ISSUE THREAD

**Issue by seiflotfy** [influxdata/influxdb#5516]
https://github.com/influxdata/influxdb/blob/master/services/meta/client.go#L301
and
https://github.com/influxdata/influxdb/blob/master/services/meta/client.go#L314

Both return errors although not needed, since both are always nil. Would it not be better to get rid of them? :question: 

* [x] Remove error from the return in (Client) Database(name string) 
* [x] Remove error from the return in (Client) Databases()

**Comment by corylanou** [comment]
My vote would be to remove the errors.  

For `Database`, If the caller needs to check for a nil response, that would be more appropriate IMO.

The `Databases` one simply can't return an error.  It's a slice...  checking `len` or for `nil` is appropriate for any caller and would work fine.

**Comment by seiflotfy** [comment]
Agree. That is my intention

**Comment by jwilder** [comment]
Yeah, does not need to return an error.
