### ISSUE TITLE
Continuous query downsample on all measurements very very flaky

### ISSUE THREAD

**Issue by normanuber** [influxdata/influxdb#5521]
Hey guys, it appears that influxdb doesn't actually execute this query consistently:
SELECT mean(value) AS value INTO network.ten_sec.:MEASUREMENT FROM network."default"./.*/ WHERE time >= '2016-02-02T21:45:00Z' AND time < '2016-02-02T21:45:10Z' GROUP BY time(10s), \* fill(previous)

It is originally generated by my continuous query: CREATE CONTINUOUS QUERY ten_sec_res ON network BEGIN SELECT mean(value) AS value INTO network.ten_sec.:MEASUREMENT FROM network."default"./.*/ GROUP BY time(10s), \* fill(previous) END

The whole idea is to downsample all points in a database. I assume this is supported given I followed it from https://influxdata.com/blog/continuous-queries-in-influxdb-part-i/

Is fill recommended in a continuous query? I'm going to keep playing around with this until something sticks. Maybe I have to create separate individual queries instead as it appears to take forever (7m 28s according to log) when running this:

> SELECT mean(value) AS value INTO network.ten_sec.:MEASUREMENT FROM network."default"."bgp_accepted-prefix-count", network."default"."bgp_active-prefix-count", network."default"."bgp_received-prefix-count", network."default".agent_failures, network."default".agent_queue_dequeued_cumulative, network."default".agent_queue_enqueued_cumulative, network."default".agent_queue_enqueued_current, network."default".agent_successes, network."default".bgp_down_peers, network."default".bgp_total_peers, network."default".collector_failures, network."default".collector_successes, network."default".cpu_avg_utilization, network."default".cpu_load_1, network."default".cpu_load_15, network."default".cpu_load_5, network."default".disk_used, network."default".disk_used_pct, network."default".interfaces_input_bps, network."default".interfaces_input_bytes, network."default".interfaces_input_bytes_broadcast, network."default".interfaces_input_bytes_multicast, network."default".interfaces_input_bytes_unicast, network."default".interfaces_input_discards, network."default".interfaces_input_errors, network."default".interfaces_input_pps, network."default".interfaces_input_unknown_protos, network."default".interfaces_output_bps, network."default".interfaces_output_bytes, network."default".interfaces_output_bytes_broadcast, network."default".interfaces_output_bytes_multicast, network."default".interfaces_output_bytes_unicast, network."default".interfaces_output_discards, network."default".interfaces_output_errors, network."default".interfaces_output_pps, network."default".interfaces_speed, network."default".memory_used_pct, network."default".metrics_queue_dequeued_cumulative, network."default".metrics_queue_enqueued_cumulative, network."default".metrics_queue_enqueued_current, network."default".routes_active, network."default".routes_active_routes, network."default".routes_count, network."default".routes_total_destinations, network."default".routes_total_routes, network."default".sensor_temperature, network."default".system_memory_active_pct, network."default".system_memory_cache_pct, network."default".system_memory_free_pct, network."default".system_memory_inactive_pct, network."default".system_memory_reserved_pct, network."default".system_memory_wired_pct, network."default".task_memory_total_avail, network."default".task_memory_total_avail_pct, network."default".task_memory_total_used WHERE time >= '2016-02-02T22:31:20Z' AND time < '2016-02-02T22:31:30Z' GROUP BY time(10s), \* fill(previous)
> ## name: result
> 
> time    written
> 0   406345

I'm using the nighty downloaded today: InfluxDB 0.10.0.n1454400035.
The server hardware has 2 processors and 6 cores each with Hyperthreading with 128GB of ram.
There are less than 70 measurements with (572 \* 2500) total data points coming in at a rate of 1m.

**Comment by normanuber** [comment]
Looks like the continuous query times out if it runs too long? I think I will do this kind of aggregation outside of influxdb then. I tried the above statment with an hours worth of data (as well as group by 1h) and that took 12 minutes. It is odd to me then that it takes 7 minutes to do 10 seconds worth of data with group by 10s.

If you want to keep the ticket open and investigate any optimization in this area feel free to keep it or else close it.

**Comment by zstyblik** [comment]
> Looks like the continuous query times out if it runs too long?

@normanuber, I wonder, how did you come to this conclusion? Was there an error in log? Please, could you copy-paste it here? Thanks.

**Comment by normanuber** [comment]
This conclusion comes from me being able to run the query that the continuous query runs in the shell (like the above) and not seeing the data points at all in the retention policy. If the issued query ran (via continuous query) then there should be at least 7 min lag for seeing that data points in that retention policy, which is fine in my case.

There are no error messages to show, just little to no data points being returned from the query to that retention policy.

**Comment by zstyblik** [comment]
@normanuber you should check log file to see whether CQ(s) is being scheduled and executed.

**Comment by normanuber** [comment]
The two reasons it must be executing are the only thing that would write to the retention policy is the continuous query and I got the large sql statement above from the logs. There are hardly any points in the retention policy meaning that it must be timing out/giving up/or whatever is happening that causes points not to show up. I'm absolutely sure this is can be replicated on your server.

**Comment by normanuber** [comment]
I decreased the rate of ingestion (10*2500) data points to see if these queries would be consistently executed and it appears not.

Here are log messages saying they are being executed:
[continuous_querier] 2016/02/04 18:47:18 executing continuous query ten_sec_res (2016-02-04 18:23:30 +0000 UTC to 2016-02-04 18:23:40 +0000 UTC)
[continuous_querier] 2016/02/04 18:49:30 executing continuous query ten_sec_res (2016-02-04 18:23:20 +0000 UTC to 2016-02-04 18:23:30 +0000 UTC)
[continuous_querier] 2016/02/04 18:51:47 executing continuous query ten_sec_res (2016-02-04 18:23:10 +0000 UTC to 2016-02-04 18:23:20 +0000 UTC)

... so where is the queries for this time period? and are they supposed to be out of order?

[continuous_querier] 2016/02/04 18:54:09 executing continuous query ten_sec_res (2016-02-04 18:53:50 +0000 UTC to 2016-02-04 18:54:00 +0000 UTC)
[continuous_querier] 2016/02/04 18:56:17 executing continuous query ten_sec_res (2016-02-04 18:53:40 +0000 UTC to 2016-02-04 18:53:50 +0000 UTC)
[continuous_querier] 2016/02/04 18:58:28 executing continuous query ten_sec_res (2016-02-04 18:53:30 +0000 UTC to 2016-02-04 18:53:40 +0000 UTC)
[continuous_querier] 2016/02/04 19:02:55 executing continuous query ten_sec_res (2016-02-04 18:53:10 +0000 UTC to 2016-02-04 18:53:20 +0000 UTC)
[continuous_querier] 2016/02/04 19:07:25 executing continuous query ten_sec_res (2016-02-04 18:52:50 +0000 UTC to 2016-02-04 18:53:00 +0000 UTC)

**Comment by normanuber** [comment]
Okay, so my conclusion of timing out? Not exactly, why can we say it times out? The default retention policy is 1 hour for all points unless the points go to other policies, so CQs that request for points outside one hour will not return points.

Can we conclude it is lagging heavily? Yes, look below.

[continuous_querier] 2016/02/04 21:09:19 executing continuous query ten_sec_res (2016-02-04 19:34:00 +0000 UTC to 2016-02-04 19:34:10 +0000 UTC)

I dropped the continuous query and here it is still executing (there's another ticket for that from someone else).
