### ISSUE TITLE
no leader detected during proxyLeader 

### ISSUE THREAD

**Issue by kornpro** [influxdata/influxdb#5526]
i have a problem. 
i started influxdb service(ex. service influxdb start) but it appear like this : 

------------------------------------------------------------------------------------------------------------------
created by net.(*singleflight).DoChan
        /usr/local/go/src/net/singleflight.go:84 +0x42b
2016/02/03 14:47:06 InfluxDB starting, version 0.9.6.1, branch 0.9.6, commit 6d3a8603cfdaf1a141779ed88b093dcc5c528e5e, built 2015-12-10T23:40:23+0000
2016/02/03 14:47:06 Go version go1.4.2, GOMAXPROCS set to 1
2016/02/03 14:47:06 Using configuration at: /etc/influxdb/influxdb.conf
[metastore] 2016/02/03 14:47:06 Using data dir: /var/lib/influxdb/meta
[metastore] 2016/02/03 14:47:06 Joining cluster at: [node1.test.com:8088]
[metastore] 2016/02/03 14:47:06 Node at node1.test.com:8088 [Follower]
[metastore] 2016/02/03 14:47:06 Join node node1.test.com:8088 failed: rpc Error failed: no leader detected during proxyLeader: retrying...
[metastore] 2016/02/03 14:47:07 Join node node1.test.com:8088 failed: rpc Error failed: no leader detected during proxyLeader: retrying...
[metastore] 2016/02/03 14:47:08 Node at node1.test.com:8088 [Leader]. peers=[node1.test.com:8088]
panic: cannot apply command: 8a082a0a0e6c6f63616c686f73743a38303931120e6c6f63616c686f73743a3830383818a0dae3c4efa2e2df0b081d

goroutine 11 [running]:
github.com/influxdb/influxdb/meta.func·031(0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:1865 +0x1f3
github.com/influxdb/influxdb/meta.(*storeFSM).Apply(0xc20807a140, 0xc20808b280, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:1867 +0x2f4
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080641c0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/raft.go:564 +0xdfc
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
        /tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/raft.go:253 +0x27
github.com/hashicorp/raft.func·011()
        /tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 1 [sleep]:
github.com/influxdb/influxdb/meta.(*Store).joinCluster(0xc20807a140, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:392 +0x69d
github.com/influxdb/influxdb/meta.(*Store).Open(0xc20807a140, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:254 +0x3df
github.com/influxdb/influxdb/cmd/influxd/run.func·003(0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:364 +0x9e7
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc208001560, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:410 +0x5e
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc20805e000, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:124 +0xe1b
main.(*Main).Run(0xc20802f680, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/main.go:86 +0x434
main.main()
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0xdc
------------------------------------------------------------------------------------------
what is this solution ?

**Comment by e-dard** [comment]
Hi @kornpro,

Could you provide some more information on how to reproduce this issue? There is some tips and advice [here](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md)

Also, once you can reproduce, the full stacktrace would be useful.

**Comment by jwilder** [comment]
@kornpro Can you try `0.10`?  This code has change quite a bit in `0.10`.

**Comment by jwilder** [comment]
Closing as this code no longer exists.
