### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by olivierHa** [influxdata/influxdb#5528]
Hello, 

I am writing a puppet module, and I need some infos about configuration in 0.10 : 

Default configuration show that ' reporting-disabled' is available in the "top scope" of the configuration file.

In the documentation, I can see a specific section "reporting" : https://docs.influxdata.com/influxdb/v0.10/administration/config/

Which one is the truth ? where this parameter should be ?

How about the "snapshot" section ? The documentation https://docs.influxdata.com/influxdb/v0.10/administration/backup_and_restore/

says that there is a "snapshot" section. This section isn't present  in the administration documentation, nor in the config example, and not in the output of the "influxd config" .

Which one is the "truth" ? :)

Regards

Olivier

**Comment by rossmcdonald** [comment]
@olivierHa Thanks for letting us know. The `reporting-disabled` variable should be global scope. I'll open an issue against the docs to make that more clear.

And the `snapshot` section was removed with 0.10.0, I believe. The docs are obviously outdated, so I'll open an issue for that as well.

When in doubt, use whatever is in the example configuration for the branch/version you are running. The config tracks with development, so it should (ideally) always be up to date.
