### ISSUE TITLE
[Question] Master down in a Cluster

### ISSUE THREAD

**Issue by AleDanish** [influxdata/influxdb#5529]
Influxdb version: 0.9.6.1

Hi all,

I created a cluster with 1 Master and 1 Slave. When the Master goes down and is unavailable for some reason, I cannot query the Slave until the Master returns available again. Is it correct or I'm missing something?

I would like to move data from one influxDB instance (Master) to another (Slave), switching off the first instance (Master) at the end.
Is there a way to turn the Slave into Master automatically, when the Master is no more reachable? Or it's only possible to do that turning Slave configuration into Master configuration and restart it?

**Comment by jwilder** [comment]
@AleDanish There is no concept of a master/slave setup in an InfluxDB cluster.  The clustering requires  a quorum of healthy nodes in order to operate.  With two nodes, you can't get a quorum so the cluster will be down.  You need to run 3 nodes to be able to handle one node being down.
