### ISSUE TITLE
[0.9.5] Running out of memory with tsm1 engine

### ISSUE THREAD

**Issue by bischofs** [influxdata/influxdb#5534]
We are importing historical data in batches to influx ( one file at a time with 20 series having ~2000 points each)  - our data is structured as having ~50 tags ( a lot of meta information) for each data point, but a limited amount of series . The data that does make it into influx has a lot of keys - because each file is basically a key being that all the tags are the same for each file. 

We tried running our importer which is using the Python pandas client to send one series at a time and the influx process ate up our 8GB of memory after about 200 files and then crashed.

Is this a function of having too many tags for each point? Or is this a problem with how we are importing data into influx?

(note: we are running on an old commodity PC with a spinning drive)

**Comment by toddboom** [comment]
@bischofs 50 tags is actually a pretty large number. The underlying cardinality is a combination of the measurements and all of the tag keys/values, so you could end up with a pretty large number very easily.

Additionally, the version of TSM that's included in v0.10.0 is more performant than the one that shipped with 0.9.5. I'd recommend trying v0.10.0-rc2 and letting us know how that looks.

Would it be possible to share a sample of your data? I'm curious how you're using the tags and whether or not it might make sense for some of those to be simple fields instead.

**Comment by bischofs** [comment]
Here you go...

[sample.zip](https://github.com/influxdata/influxdb/files/116400/sample.zip)

Yeah so this is one file of the 200 that is in csv form.  The top two rows are the tags ( meta info )  we are using and the third row is the name of the series.

**Comment by jwilder** [comment]
@bischofs Can you provide some sample line protocol formatted strings that you are inserting?  I don't understand how the CSV data you attached translates to tags and fields.

**Comment by toddboom** [comment]
I haven't seen this come back up with InfluxDB v0.10.0 or higher, so I'm going to assume it's fixed. Please reopen if it's still happening on the latest release (v0.11.0).
