### ISSUE TITLE
tsm on 0.9.6: Running out of memory when running a GROUP BY time(100ms) 

### ISSUE THREAD

**Issue by rburchell** [influxdata/influxdb#5540]
(InfluxDB starting, version 0.9.6.1, branch 0.9.6, commit 6d3a8603cfdaf1a141779ed88b093dcc5c528e5e)

I'm using the tsm engine, first up. I was using bz1 (the default at the time as I understand it), but it fell apart completely under the write load of this testing. tsm seems to do quite a bit better, but is OOMing at *read* time. At least it isn't corrupting the database like bz1 eventually did. The RAM available on this machine is pretty extensive (4gb). I find this quite worrying.

With that introduction out of the way about the setup, some more details: I'm playing around with importing a rather large dataset into Influx. I haven't yet gotten the time of my points correct in the import tool yet, so they're all clustered around a _really_ close time range for now. So, essentially, consider this test as just having imported a bunch of random values with really close together timestamps. There are about 5 different tags per point, but I don't think they differ all that much (is there any quick way I can verify that?).

I haven't even imported all that much so far:

```
SELECT COUNT("Duration") FROM qt."default".qt_test_durations
name: qt_test_durations
-----------------------
time	count
0	58058
```

However, with this dataset, I'm already running into an OOM running the following query:

```
SELECT mean("Duration") FROM qt."default".qt_test_durations WHERE time > now() - 5m GROUP BY time(100ms)
```

from dmesg:
```
[ 5947.021652] [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
...
[ 5947.080329] [ 4869]   996  4869  1230489   880417    2218   202480             0 influxd
...
[ 5947.083181] Out of memory: Kill process 4869 (influxd) score 880 or sacrifice child
[ 5947.084804] Killed process 4869 (influxd) total-vm:4921956kB, anon-rss:3521668kB, file-rss:0kB
[ 5947.384626] influxd: page allocation failure: order:0, mode:0x200da
```

Is this to be expected with such a low point count? Is there a limit to how close together my points are without things exploding?

**Comment by rburchell** [comment]
Worth noting that if I remove the GROUP BY, then performance is just fine.

**Comment by rburchell** [comment]
Also interesting (though perhaps a seperate issue) is that even if all my data is outside that 5 minute range, the GROUP BY still slows the query down massively, but it does eventually complete. Is filtering somehow not being applied before the GROUP BY?

**Comment by e-dard** [comment]
> There are about 5 different tags per point, but I don't think they differ all that much (is there any quick way I can verify that?).

If you run `show series` you should be able to see the measurement in question, and all the different keys (measurement and tag combinations) for it).

**Comment by rburchell** [comment]
Ah, thanks. I had a bad tag which lead to an explosive number of series. I'm perplexed why that caused problems for the grouping on time, though.

**Comment by jwilder** [comment]
@rburchell I'd suggest trying 0.10.  There was a fix related to this type of query that might help.

**Comment by rburchell** [comment]
Thanks, I just noticed the release (by seeing the 0.9 docs start to say "this is outdated!") :). Assuming there's an update to the CentOS RPM, I'll give it a shot tomorrow.

**Comment by rburchell** [comment]
After removing the bad tag, performance seems quite acceptable, so I guess there isn't much point keeping this open as-is.
