### ISSUE TITLE
aggregate functions return 0

### ISSUE THREAD

**Issue by ralidousti** [influxdata/influxdb#5549]
version 0.10.0, stm, non-cluster mode
happens with all the aggregate functions:

```
> SELECT max("bytes") FROM "incoming_traffic" WHERE time > 1454684406000000000 group by time(10m)

name: incoming_traffic
----------------------
time	max
1454684400000000000	0
1454685000000000000	0
1454685600000000000	0
1454686200000000000	0
1454686800000000000	0
1454687400000000000	0
1454688000000000000	0
1454688600000000000	0
1454689200000000000	0
1454689800000000000	0
1454690400000000000	0
1454691000000000000	0
```
while there is definitely non zero values in the data set:

```
> SELECT "bytes" FROM "incoming_traffic" WHERE time > 1454684406000000000 limit 5
name: incoming_traffic
----------------------
time	bytes
1454684409000000000	9334
1454684409000000000	932
1454684409000000000	1567
1454684409000000000	220634207
1454684409000000000	66799

```

**Comment by t-orb** [comment]
I bet your problem is what I experienced, those non-zero values are stored as strings not integers.

I was using the python library to write data and had to add an int() around my variables holding the values, then it got better.

**Comment by beckettsean** [comment]
Almost certainly the field values were strings. Closing until there is a reply from @ralidousti

**Comment by ralidousti** [comment]
My apologies for not updating this ticket earlier. Yes, the values were mistakenly inserted as strings. But on the same note would that not warrant an error message WRT some of the aggregate functions that are not defined for string type?

**Comment by beckettsean** [comment]
@ralidousti there's an open issue to add that error: https://github.com/influxdata/influxdb/issues/3818
