### ISSUE TITLE
Can't run in alpine linux - __vfprintf_chk: symbol not found/Static binary is dynamically linked

### ISSUE THREAD

**Issue by ashb** [influxdata/influxdb#5554]
I tried downloading the Standalone Binary v0.10 release and when I tried to run it you get odd behaviour:

```
bash-4.3# /usr/bin/influx
bash: /usr/bin/influx: No such file or directory
bash-4.3# ls -l /usr/bin/influx
-rwxr-xr-x 1 root root 11611184 Feb  5 19:05 /usr/bin/influx
```

Odd. `ldd` to the rescue:

```
bash-4.3# ldd /usr/bin/influx
        /lib64/ld-linux-x86-64.so.2 (0x55fc22b32000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x55fc22b32000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x55fc22b32000)
Error relocating /usr/bin/influx: __vfprintf_chk: symbol not found
```

I'm not sure if this is intended, but the static binary still links against libc?

This from my OSX machine: 
```
(themisto tmp/influx :*+)% curl -fsSL https://s3.amazonaws.com/influxdb/influxdb-0.10.0-1_linux_amd64.tar.gz | tar x
(themisto tmp/influx :*+)% file influxdb-0.10.0-1/usr/bin/influx
influxdb-0.10.0-1/usr/bin/influx: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped
```

A quick google reveal [Chromium Issue 572417 – PPAPI not compatible with musl libc on linux](https://code.google.com/p/chromium/issues/detail?id=572417) which is the same libc that Alpine Linux is based on. No fix, but other people have reported similar problems.

I think I remember reading something about go 1.4 not really producing static binaries -- could this be the cause?

**Comment by ashb** [comment]
I found this post http://blog.hashbangbash.com/2014/04/linking-golang-statically/ which says that if anything is using cgo (which seems plausible) then you have to specify other flags to actually get a static binary out (reproduced here):

```
$> go build ./code-cgo.go
$> file ./code-cgo
./code-cgo: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped
```

vs

```
$> go build --ldflags '-extldflags "-static"' ./code-cgo.go
$> file ./code-cgo
./code-cgo: ELF 64-bit LSB  executable, x86-64, version 1 (GNU/Linux), statically linked, not stripped
$> ldd ./code-cgo
        not a dynamic executable
$> ./code-cgo
hello, world!
```

**Comment by arthurgeek** [comment]
Any news on that? Would like to use the static binary, without any linked dependencies.

**Comment by ashb** [comment]
So I manged to get it work:

```diff
diff --git a/build.py b/build.py
index 144bbe9..abba133 100755
--- a/build.py
+++ b/build.py
@@ -423,9 +423,10 @@ def build(version=None,
             build_command += "-race "
         go_version = get_go_version()
         if "1.4" in go_version:
-            build_command += "-ldflags=\"-X main.version {} -X main.branch {} -X main.commit {}\" ".format(version,
-                                                                                                           get_current_branch(),
-                                                                                                           get_current_commit())
+            build_command += "-a -installsuffix nocgo -ldflags=\"-s -extldflags \"--static\" -X main.version {} -X main.branch {} -X main.commit {}\" ".format(version,
+                                                                                                                                       get_current_branch(),
+                                                                                                                                       get_current_commit())
+            build_command = "CGO_ENABLED=0 " + build_command
         else:
             # With Go 1.5, the linker flag arguments changed to 'name=value' from 'name value'
             build_command += "-ldflags=\"-X main.version={} -X main.branch={} -X main.commit={}\" ".format(version,
```

The thing that worries me is that `CGO_ENABLE=1` -- I have no idea if this has an impact on performance. Do we have an easy way to test it?

**Comment by rossmcdonald** [comment]
@ashb We have not tested the performance impact of static binaries, which is one of the reasons why we have not been offering them. I am working on a few changes to the build script to enable static binaries, so we are going to start testing on them more over the next few weeks. I'll send out updates on this thread if we encounter any noticeable performance issues, but for now I would say use at your own risk.

**Comment by dz0ny** [comment]
Test build https://hub.docker.com/r/niteoweb/docker-influxdb/ (alpine+nightly), works without problems atm
