### ISSUE TITLE
[0.11.0] Mean returns very slowly when profiling against default influx_stress dataset

### ISSUE THREAD

**Issue by mjdesa** [influxdata/influxdb#5557]
Using a dataset generated by `influx_stress` with the [default configuration](https://github.com/influxdata/influxdb/blob/master/cmd/influx_stress/examples/template.toml).

Query: `SELECT mean(value) from cpu`

0.9.6
```
Average Reponse Time: 10.809494927s
Standard Deviation: 296.268314ms
Median Reponse Time: 10.781657653s
```

0.10.0
```
Average Reponse Time: 15.096902086s
Median Reponse Time: 15.064464137s
```

0.11.0
```
Average Reponse Time: 34.441655159s
Median Reponse Time: 34.413132986s
```

Additionally, memory consumption on the box where the query is running increases dramatically

![unspecified](https://cloud.githubusercontent.com/assets/1477539/12861962/0e889a68-cc1c-11e5-823d-22651ace950f.png)

**Comment by seiflotfy** [comment]
I played with this a bit an noticed the the biggest time is spent inside
https://github.com/influxdata/influxdb/blob/bc312ceb14f5ef0d07f73a5113abfbdd8804f30a/tsdb/aggregate.go#L823
I'll see what I can do

**Comment by gunnaraasen** [comment]
@seiflotfy There's a new query engine in the works (PR https://github.com/influxdata/influxdb/pull/5196). It should be merged in the next few days, but all query engine work should be done on that branch for now.

**Comment by seiflotfy** [comment]
@gunnaraasen thanks looking into it more, since its even slower on that branch

**Comment by seiflotfy** [comment]
Ok I think I got a fix for this. No promises though. Hopefully up later tomorrow

**Comment by seiflotfy** [comment]
So here is my current status:

* Running it on a stress ```SELECT mean(value) from cpu```  (with 2.475e+06 values) ==> 7.963996353s
```
[http] 2016/02/10 15:02:30 ::1 - - [10/Feb/2016:15:02:22 -0600] GET /query?db=stress&epoch=ns&q=SELECT+mean%28value%29+from+cpu HTTP/1.1 200 108 - InfluxDBShell/0.9 942ecd01-d039-11e5-800a-000000000000 7.963996353s
```

* Narrowing down where most time is spent in the query is 5.816169297s in https://github.com/influxdata/influxdb/blob/29c2dbc6239f98a2777ed742641c1cfcfb704308/influxql/iterator.gen.go#L651 where specifically https://github.com/influxdata/influxdb/blob/29c2dbc6239f98a2777ed742641c1cfcfb704308/influxql/iterator.gen.go#L664 4.90669319s (calling time.Now and duration also use some time in the measuring but once can see where most time is spent)

I'll dig further later..
@benbjohnson any ideas? I have a hunch that we are spending too much time reading from ReadFloatBlockAt in reader.go

**Comment by benbjohnson** [comment]
@seiflotfy The issue with this one is that `mean()` uses `reduceSliceIterator` as a temporary stop gap solution until we can make an iterator that specifically handles the intermediate `struct { Sum float64; Count int64 }` point value.

**Comment by jwilder** [comment]
#5658 should fix this.

**Comment by mjdesa** [comment]
Performance with https://github.com/influxdata/influxdb/pull/5658/commits
```
Query: SELECT mean(value) from cpu
Average Reponse Time: 5.405960233s
Standard Deviation: 84.320639ms
Median Reponse Time: 5.365194029s
Point Per Second: 1849810
```

```
Query: SELECT mean(value) from cpu group by host
Average Reponse Time: 8.104964169s
Standard Deviation: 220.868929ms
Median Reponse Time: 8.191883971s
Point Per Second: 1233811
```

**Comment by jsternberg** [comment]
This got merged so this should be done.
