### ISSUE TITLE
[0.10.0] HTTP API error response inconsistencies

### ISSUE THREAD

**Issue by MikaelGRA** [influxdata/influxdb#5563]
Hello,

Since 0.10.0 it seems to be difficult to differentiate between error responses and successfully responses, as long as the query being executed itself, is not malformed.

For example, when I execute the following two queries:

```bash
# create database
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

# create database again (should fail)
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
```

The first one is successful, as expected. However, the second one is as well, and the response is the exact same, so there is no way of knowing that it actually failed. It is as though you actually used the query "CREATE DATABASE IF NOT EXISTS" instead.

The same thing is also true for retention policies (and maybe also other types of queries?).

If this is what is supposed to happen, could someone point me to the documentation for error responses? In general I feel it is fairly difficult to come up with the correct documentation for these scenarios on your documentation pages.

**Comment by jwilder** [comment]
The behavior seems to have changed from `0.9.6` to `0.10.0`, but I don't think it was intentional.

`0.9.6` returned:
```
$ curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
{"results":[{"error":"database already exists"}]}
```

@corylanou @dgnorton

**Comment by jsternberg** [comment]
After talking with @pauldix, this change was intentional. We are going to remove this syntax in 0.12, but the syntax will be accepted and ignored for 0.10 through 0.11.

Thank you for reporting this issue. I'll open up an issue with the documentation to make this clear.

**Comment by MikaelGRA** [comment]
Hey.

Just a small followup. I can understand the reasoning behind this change, but as I mentioned in the initial issue, this is not just an issue for the "CREATE DATABASE" command. The same sort of behaviour is present for the CREATE RETENTION POLICY command (and probably other commands too?).

Is it also intentional for these commands? If it is, then what happens? Do you replace the retention policy/database? Does the command simply do nothing?

In the client library I am making, I would like to be able to give the user some feedback on what is actually happening in the database, however, as the commands are defined right now, I am unable to do so, because no matter what happens, the exact same result (for both commands) is always returned.

**Comment by pauldix** [comment]
If it's already there and the arguments are the same it should just be a no-op. If already there and the arguments are different, it should throw an error. If not present, then the create should create.
