### ISSUE TITLE
Question about data distribution

### ISSUE THREAD

**Issue by amancevice** [influxdata/influxdb#5568]
I have a data set that I can distribute one of two ways: A small number of measurements each with a large number of series, or a greater number of measurements with a smaller set of series in each. Are there any tradeoffs to each methodology?

If the data is distributed as a small number of measurements, I would expect users to query a large number of series from one or more measurements at once using `OR` expressions to build-out the result set. It would be possible that a user is only concerned with one measurement at a time but it's probably a safe bet that data would be fetched from multiple/all measurements at once.

If the data is distributed as a greater number of measurements, each with a smaller set of series, I would still expect users to query across multiple measurements and series at once for data, but perhaps not all measurements at once.

Is there a clear answer given my use case?

**Comment by mjdesa** [comment]
@amancevice this is neither a bug report or a feature request please ask your question on the mailing list. https://groups.google.com/forum/#!forum/influxdb
