### ISSUE TITLE
Parser can't handle various keywords

### ISSUE THREAD

**Issue by djMax** [influxdata/influxdb#5576]
I have a data set that has a tag named "duration". I can select * fine:

```
SELECT * FROM request
```

shows duration just fine. But I can't ask for it:

```
SELECT duration FROM request
```

```
Server returned error: error parsing query: found DURATION, expected identifier, string, number, bool at line 1, char 8
```

If that's not a valid tag it should not allow me to create a bazillion points with it. :)

**Comment by jwilder** [comment]
@djMax `duration` is a keyword.  You need to surround it with double-quotes in this case.  

```
SELECT "duration" FROM request
```

See: https://docs.influxdata.com/influxdb/v0.10/query_language/data_exploration/

**Comment by djMax** [comment]
Ah - single quote didn't work but indeed double quote does. Thanks.
