### ISSUE TITLE
[0.10.0] Unable to drop corrupted series using WHERE statement.

### ISSUE THREAD

**Issue by groblus** [influxdata/influxdb#5577]
I'm trying do flush some wrong data from my measurements. I'm trying to use :
`DROP SERIES FROM "net" where "bytes_recv"=0`
Problem is that:
`Server returned error: DROP SERIES doesn't support fields in WHERE clause`
How can I flush some wrong data from my measurement - I don't want to drop my measurement, but only remove some wrong data that got pumped by telegraf. Is it possible ?

**Comment by mjdesa** [comment]
@groblus what version are you using?

**Comment by groblus** [comment]
0.10 But I'm beginning to think that's a design flaw not a bug :(

pon., 8 lut 2016, 21:05 Michael Desa użytkownik <notifications@github.com>
napisał:

**Comment by mjdesa** [comment]
@groblus ah yeah, to my knowledge you cannot delete points based on fields.

**Comment by groblus** [comment]
So there is no way of deleting corrupt data, except dropinh the whole measurement?

**Comment by mjdesa** [comment]
@groblus at the moment we only allow dropping series using tags.

**Comment by groblus** [comment]
@mjdesa Are there any plans on improving it ? There used to be delete by timeframe option but it was dropped. Without the ability to remove certain records it's impossibile to sanitize corrupt data.

**Comment by mjdesa** [comment]
@groblus there are plans to improve this functionality.
