### ISSUE TITLE
Modeling downsampling for complex data sets

### ISSUE THREAD

**Issue by djMax** [influxdata/influxdb#5578]
I'm trying to understand how I'm supposed to downsample some data. I have a list of payment attempts. The values are an amount and the duration the request took to process. Tags include the currency, the data center, the error code (or none) and the type of payment (e.g. cash, credit card, check). In the end, I would like a measurement that has some time period (say 10 minutes) and sum(amount), sum(duration), count() for various cuts on the data - by currency, by data center, by payment type... But there's no "CASE" in influxQL, so it seems my only choice would be to have one measurement PER currency (for example). This will make the grafana side annoying because there would be lots of joins. Am I missing an approach here?

**Comment by mjdesa** [comment]
@djMax this is neither a bug report or a feature request. Please ask your question on the mailing list. https://groups.google.com/forum/#!forum/influxdb

**Comment by djMax** [comment]
I think it's a polite request for "case/when" support, but ok.

**Comment by mjdesa** [comment]
@djMax sorry for the harshness of my previous reply. We've been trying to cut down a lot of the noise in our issues by removing closing anything that isn't a bug report or a feature request.

**Comment by zstyblik** [comment]
@mjdesa but this really has been common request and could be considered as a bug. Perhaps not bug against InfluxDB repo, but may be against InfluxDB Docs. Because it'd be really great to provide some examples of down-sampling strategies and use-cases. To say it bluntly, you want people to use InfluxDB, right?

**Comment by mjdesa** [comment]
@zstyblik opened an issue on the docs repo https://github.com/influxdata/docs.influxdata.com/issues/224

**Comment by zstyblik** [comment]
@mjdesa Thanks. I'm sure it will be appreciated by many people.

**Comment by beckettsean** [comment]
@djMax I replied in some depth to your question on the mailing list, which is the appropriate place for open-ended "how do i?" questions.

@zstyblik and @djMax can you please elaborate on https://github.com/influxdata/docs.influxdata.com/issues/224 what specifically the [Downsampling Guide](https://docs.influxdata.com/influxdb/v0.10/guides/downsampling_and_retention/) in the docs doesn't cover?

In this case I think the difficulty was not understanding how to use tags. That's well covered elsewhere in the docs. I'm not trying to pull an RTFM, but the info is all there and makes sense to us, so we need you to tell us HOW it needs to be more clear, not just say "make an example of all possible use cases so I don't need to think through mine in particular."
