### ISSUE TITLE
Cluster Meta-Queries

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#5581]
This issue is for tracking the overall status of meta-queries for clustering. A tick means the command has been manually tested on a local cluster.

A green tick means it works, or that there was an issue which has been resolved, a grey tick means there is an outstanding issue.

|Command|Checked|Issue?|Verified|
|---|---|---|---|
|`CREATE CONTINUOUS QUERY`|:white_check_mark:|https://github.com/influxdata/influxdb/issues/5574||
|`SHOW CONTINUOUS QUERY`|:white_check_mark:|||
|`DROP CONTINUOUS QUERY`|:white_check_mark:|||
|`SHOW DATABASES`|:white_check_mark:|||
|`CREATE DATABASE`|:white_check_mark:|||
|`DROP DATABASE`|:white_check_mark:|https://github.com/influxdata/influxdb/issues/5612||
|`SHOW FIELD KEYS`|:white_check_mark:|https://github.com/influxdata/influxdb/issues/5579|||
|`GRANT`|:white_check_mark:|||
|`SHOW GRANTS`|:white_check_mark:|||
|`INSERT`|:white_check_mark:|https://github.com/influxdata/influxdb/issues/5610||
|`SHOW MEASUREMENTS`|:white_check_mark:|||
|`DROP MEASUREMENTS`|:white_check_mark:|#5573 | |
|`SET PASSWORD`|:white_check_mark:|https://github.com/influxdata/influxdb/issues/5532||
|`ALTER RETENTION POLICY`|:white_check_mark:|||
|`CREATE RETENTION POLICY`|:white_check_mark:|||
|`DROP RETENTION POLICY`|:white_check_mark:|https://github.com/influxdata/influxdb/issues/5653||
|`SHOW RETENTION POLICIES`|:white_check_mark:|||
|`REVOKE`||||
|`SHOW SERIES`|:ballot_box_with_check:|https://github.com/influxdata/influxdb/issues/5580||
|`DROP SERIES`|:white_check_mark:|https://github.com/influxdata/influxdb/issues/5518| |
|`SHOW SHARDS`|:white_check_mark:|||
|`SHOW SHARD GROUPS`|:white_check_mark:|||
|`CREATE SUBSCRIPTION`|:white_check_mark:|||
|`DROP SUBSCRIPTION`|:white_check_mark:|https://github.com/influxdata/influxdb/issues/5590||
|`SHOW SUBSCRIPTIONS`|:white_check_mark:|||
|`SHOW TAG KEYS`|:white_check_mark:|https://github.com/influxdata/influxdb/issues/5591||
|`SHOW TAG VALUES`|:white_check_mark:|https://github.com/influxdata/influxdb/issues/5593||
|`SHOW USERS`|:white_check_mark:|||
|`CREATE USER`|:ballot_box_with_check:|#5835||
|`DROP USER`|:white_check_mark:|||

cc @e-dard @joelegasse

**Comment by jsternberg** [comment]
`SHOW TAG KEYS` now works as mentioned in #5591.

**Comment by jsternberg** [comment]
`SHOW FIELD KEYS` now works as of #5815.
