### ISSUE TITLE
Allow for cluster healing

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#5583]
In the event of a cluster node dying, provide a way for administrators to create a replacement of the lost node (with a full re-synchronization of any shards that were there originally).

**Comment by stepanstipl** [comment]
+1

Any idea how is this supposed to be handled at the moment? Currently if one of my nodes dies, it's pretty much listed in `SHOW SERVERS` forever.

Also is there some way how to get info about cluster health? In terms of shards and their replication? Currently I don't know any way how to get good visibility about what's happening with the cluster.

**Comment by rossmcdonald** [comment]
@stepanstipl You should be able to drop the server from the cluster using the commands:

- `drop meta server <ID>`
- `drop data server <ID>`

Using the server ID's from the output of a `SHOW SERVERS` command. This should prevent it from showing up in further output, though I don't believe you will be able to add a new server with the same hostname from that point onward.

Regarding:

> Also is there some way how to get info about cluster health? In terms of shards and their replication? 

Unfortunately not at the moment, which is why I created #5584. There is some information in the `_internal` database, but it's a bit hard to make sense of.

**Comment by stepanstipl** [comment]
@rossmcdonald thanks, will give that a try :)

**Comment by supershal** [comment]
+1

**Comment by rossmcdonald** [comment]
Now that clustering has been removed from open-source InfluxDB, this issue will now be closed.
