### ISSUE TITLE
Provide method for determining cluster synchronization status

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#5584]
Provide a method or endpoint that displays the internal metrics about a cluster's internal synchronization process, such as:
- WAL replication
- General latency
- System load
- Percentage of data in/out of sync

As well as being able to refresh a status check, and force a re-synchronization.

**Comment by stepanstipl** [comment]
+1

**Comment by jsternberg** [comment]
Clustering is now removed from the open source version so I'm closing this.
