### ISSUE TITLE
Expansion function capabilities TOP

### ISSUE THREAD

**Issue by jurijshevtsov** [influxdata/influxdb#5588]
There is evidence
```
timing,server=1,IP=10.13.71.10,service=create time_nginx=1,session="kvitka_n4_552aaecfd8b248c17f81" 1455017946405688471
timing,server=1,IP=10.13.71.10,service=create time_nginx=2,session="kvitka_n4_552aaecfd8b248c17f82" 1455017946405688472
timing,server=1,IP=10.13.71.10,service=create time_nginx=3,session="kvitka_n4_552aaecfd8b248c17f83" 1455017946405688473
timing,server=1,IP=10.13.71.10,service=create time_nginx=4,session="kvitka_n4_552aaecfd8b248c17f84" 1455017946405688474
timing,server=1,IP=10.13.71.10,service=create time_nginx=5,session="kvitka_n4_552aaecfd8b248c17f85" 1455017946405688475
timing,server=1,IP=10.13.71.10,service=create time_nginx=5,session="kvitka_n4_552aaecfd8b248c17f86" 1455017946405688476


> select TOP(time_nginx,3) from timing
name: timing
------------
time			top
1455017946405688474	4
1455017946405688475	5
1455017946405688476	5
```

It lacks the ability to display the value of the maximum values for "session" time_nginx
(не хватает возможности вывести значение сессии для максимальных значений time_nginx)
```
time			top  session
1455017946405688474	4    kvitka_n4_552aaecfd8b248c17f84
1455017946405688475	5    kvitka_n4_552aaecfd8b248c17f85
1455017946405688476	5    kvitka_n4_552aaecfd8b248c17f86
```

**Comment by rossmcdonald** [comment]
@jurijshevtsov I'm not sure I follow. The results look correct to me. Can you provide another example of the issue?

**Comment by jurijshevtsov** [comment]
TOP command values are displayed correctly. But I get only the maximum values "time_nginx" parameter. To find the log files do I need to know the value of the parameter "session". Is it possible to modify the function top so she could return to the value of "session"?

(Значения команды ТОP отображаются верно. Но я получаю только максимальные значения параметра "time_nginx" . Для нахождения логов мне нужно знать значения параметра "session". Можно ли доработать функцию ТОP,  чтобы она могла вернуть  значение "session"?)

for example, write a query
>select TOP(time_nginx,3),session from timing
name: timing
------------
time			top	session
1455017946405688474	4
1455017946405688475	5
1455017946405688476	5

A need 

time            top  session
1455017946405688474 4    kvitka_n4_552aaecfd8b248c17f84
1455017946405688475 5    kvitka_n4_552aaecfd8b248c17f85
1455017946405688476 5    kvitka_n4_552aaecfd8b248c17f86

**Comment by jsternberg** [comment]
This should be possible now or, if it isn't, will be available in 0.11 with the release of the new query engine.

**Comment by jsternberg** [comment]
Closing this in favor of #5597.
