### ISSUE TITLE
[0.10.0] SHOW TAG KEYS doesn't work on partially-replicated cluster

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#5591]
`SHOW TAG KEYS` does not work correctly when running on a partially replicated cluster. I've tested this on a 3-node cluster with a replication factor of 1. 

Weirdly, even the node with the shard on it isn't able to return the tag keys.

Node 1:

```
> create database db
> use db
Using database db
> alter retention policy default on db REPLICATION 1
> insert cpu,tk=tv value=1
> show tag keys
ERR: write message type: write tcp [::1]:53109->[::1]:8288: use of closed network connection
> show measurements
name: measurements
------------------
name
cpu

>
```

Node 2 (after all commands on node 1 have completed):

```
> show tag keys
ERR: write message type: write tcp [::1]:53118->[::1]:8188: use of closed network connection
> show series
name: cpu
---------
_key		tk
cpu,tk=tv	tv

>
```

Node 3 (after all commands on node 1 have completed):
```
> show tag keys
ERR: write message type: write tcp [::1]:53193->[::1]:8288: use of closed network connection
> show series
> show measurements
name: measurements
------------------
name
cpu

>
```

Logs attached (no panics).

[n1.txt](https://github.com/influxdata/influxdb/files/123111/n1.txt)
[n2.txt](https://github.com/influxdata/influxdb/files/123113/n2.txt)
[n3.txt](https://github.com/influxdata/influxdb/files/123112/n3.txt)

**Comment by jsternberg** [comment]
This should work as soon as #5811 gets merged since this command is already converted to the new query engine.

**Comment by jsternberg** [comment]
This works now that remote execution works since #5811, #5842, and #5843 have been merged.
