### ISSUE TITLE
[0.10.0] SHOW TAG VALUES does not work on cluster

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#5593]
`SHOW TAG VALUES` does not return the correct results from all nodes in a fully replicated cluster (default config values).

Node 1:

```
> create database db
> use db
Using database db
> insert cpu,tk=tv value=1
> show tag values with key = "tk"
name: tkTagValues
-----------------
tk
tv

>
```

Node 2 (after all commands on node 1 have completed):

```
> show tag values with key = "tk"
name: tkTagValues
-----------------
tk
tv

>
```

Node 3 (after all commands on node 1 have completed):

```
> show tag values with key = "tk"
>
```

**Comment by jsternberg** [comment]
I'm going to start converting this to use the new query engine. It will depend on #5811 being merged first though.
