### ISSUE TITLE
[0.10.0] InfluxDB refuses to listen on some ports

### ISSUE THREAD

**Issue by schlunz** [influxdata/influxdb#5599]
Today I have stored 3.2gb of journalctl logs into InfluxDB. After the transfer was finished the db seems to have some **performance problems**.

- when I start/restart influxdb it takes a while until it listen on port _8083_ / _8086_ and cuts up the connection after queries were send out
- ` SELECT` queries entered via the InfluxDB shell / web admin interface never return a result

I am using version `0.10.0` on an ubuntu distro.

**Comment by rossmcdonald** [comment]
@schlunz Can you provide the logs from when these issues are occurring?

**Comment by BGraco** [comment]
I think I am seeing similar problem, though I took it as possibly an issue with the python client as I can CURL the requests with no issue.

[https://github.com/influxdata/influxdb-python/issues/293](url)

Python client works flawless on 0.9.x, on 0.10.0 I can query without issue, but I can only write once then the requests session disconnects and never recovers.

**Comment by schlunz** [comment]
sorry @rossmcdonald! i lost the logs for the described influxDB session.

I figured out this might be an performance issue, since I wrote lots of **strings**, as **tag sets** (I think between 15 and **25**) for each write request to influxDB. And this around **3,6 million times** (but batched).

My hardware and/or influxDB might not like that amount of data in a short period of time.  :snail: :dizzy_face: 

By the way, I used the ruby client I think it did a good job!

**Comment by rossmcdonald** [comment]
@schlunz Yes, tags should be reserved for non-unique items with ideally a somewhat low level of cardinality (though it depends on the specs on your machine). Unique tags (even over a relatively short period of time) will cause the in-memory index to explode in size, causing all sorts of memory and performance issues and should be avoided.

I'm going to close this issue for now, but respond here if you're able to reproduce the issue.
