### ISSUE TITLE
Benchmark different storage engines

### ISSUE THREAD

**Issue by sschepens** [influxdata/influxdb#56]
Some possible engines to try:
Sophia - http://sphia.org/
RocksDB - http://rocksdb.org/
Tokutek - http://www.tokutek.com/
HyperDex - http://hyperdex.org/
Symas LMDB - http://symas.com/mdb/

Add others in the comments.

**Comment by KrishnaPG** [comment]
The documentation [here](https://influxdb.com/docs/v0.9/concepts/storage_engine.html) is saying, InfluxDB now uses BoltDB- is that correct?

**Comment by gunnaraasen** [comment]
@KrishnaPG yes, InfluxDB version 0.9 uses BoltDB.
