### ISSUE TITLE
[0.10.0] Clustering is not working as expected

### ISSUE THREAD

**Issue by anuvdas** [influxdata/influxdb#5614]
Followed the documentation in the site however i am not able to run "influx". getting this error
```
# influx
Failed to connect to http://localhost:8086
Please check your connection settings and ensure 'influxd' is running.

# ps -ef | grep influx
influxdb  3932     1  0 07:53 ?        00:00:00 /bin/sh -c /usr/bin/influxd -config /etc/influxdb/influxdb.conf  >>/dev/null 2>>/var/log/influxdb/influxd.log
influxdb  3933  3932  0 07:53 ?        00:00:00 /usr/bin/influxd -config /etc/influxdb/influxdb.conf
root      3949  3569  0 07:54 pts/0    00:00:00 grep --color=auto influx
```

**Comment by rossmcdonald** [comment]
@anuvdas If you followed the clustering guide, then `influxd` is most likely not listening on `localhost` anymore. If you run `influx -host <ip>`, where `<ip>` is set to whatever the bind address is in your configuration, do you get the same error?

**Comment by anuvdas** [comment]
@rossmcdonald That was a good pointer,but still eventhough in the config file the entry is
bind-address = "influx301:8086"
when i do influx -host influx301 
```
> SHOW SERVERS
name: data_nodes
----------------
id	http_addr	tcp_addr
1	localhost:8086	influx301:8088

name: meta_nodes
----------------
id	http_addr			tcp_addr
1	influx301:8091	influx301:8088
```
In this output it still shows localhost and i don't see other member servers in the cluster.

**Comment by rossmcdonald** [comment]
@anuvdas The `no route to host` error leads me to believe it could be a network issue. From the server that generated the log output:

```
[metaclient] 2016/02/11 03:49:13 failure getting snapshot from influx301:8091: Get http://influx301:8091?index=0: dial tcp <ip>:8091: no route to host
```

Can you successfully run a `telnet influx301 8091` and have it connect successfully?

Regarding the `localhost:8086` issue, did you erase everything under the `/var/lib/influxdb/*` directory when changing the `[http]` `bind-address` setting to `influx301`? Note that this will erase all of your data, so only remove that folder when setting up a cluster for the first time.

**Comment by anuvdas** [comment]
@rossmcdonald Thank you so much, after removing everything from /var/lib/influxdb/* localhost problem got resolved. Now what i see is 
```
# influx -host influx301
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://influx301:8086 version 0.10.0
InfluxDB shell 0.10.0
> show servers
name: data_nodes
----------------
id	http_addr			tcp_addr
1	influx301:8086	influx301:8088

name: meta_nodes
----------------
id	http_addr			tcp_addr
1	influx301:8091	influx301:8088
```

But my telnet to port 8091 fails and other cluster members are not showing up.

**Comment by rossmcdonald** [comment]
@anuvdas Being unable to telnet over port 8091 is a sign of a network issue, as the hosts are unable to communicate with each other. Does the telnet command work if you substitute the IP address of the machines instead of the hostname?

**Comment by anuvdas** [comment]
telnet is not working with influx301 hostname or IP address.

**Comment by rossmcdonald** [comment]
@anuvdas If you run a `netstat -tlupn | grep influxd` on `influx301`, what is displayed?

**Comment by anuvdas** [comment]
@rossmcdonald 
```
tcp        0      0 influx301 IP address:8086        0.0.0.0:*               LISTEN      6598/influxd        
tcp        0      0 influx301 IP address:8088        0.0.0.0:*               LISTEN      6598/influxd        
tcp        0      0 influx301 IP address:8091        0.0.0.0:*               LISTEN      6598/influxd        
tcp6       0      0 :::8083                 :::*                    LISTEN      6598/influxd        
```

**Comment by rossmcdonald** [comment]
@anuvdas It looks like the service is up and listening on port `8091`, so it has to be something to do with your network. Do you maybe have a firewall enabled?

**Comment by anuvdas** [comment]
@rossmcdonald Firewall is there but at least it should connect to localhost right ?
```
[root@influx301 ~]# netstat -tlupn | grep influxd
tcp        0      0 influx301IP:8086        0.0.0.0:*               LISTEN      974/influxd         
tcp        0      0 influx301IP:8088        0.0.0.0:*               LISTEN      974/influxd         
tcp        0      0 influx301IP:8091        0.0.0.0:*               LISTEN      974/influxd         
tcp6       0      0 :::8083                 :::*                    LISTEN      974/influxd         
[root@influx301 ~]# telnet localhost 8091
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
```

**Comment by rossmcdonald** [comment]
@anuvdas No, if you bind to a specific IP/hostname, then InfluxDB will no longer be listening on localhost. What is the `bind-address` set to in your configuration?

**Comment by anuvdas** [comment]
bind-address is hostname only. So i am trying to get help from network team for port opening.

**Comment by anuvdas** [comment]
@rossmcdonald Now telnet is connecting and i get the below one. Can you please tell me why meta_nodes are only one instead of 3 ?
```
[root@influx301 ~]# influx -host influx301
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://influx301:8086 version 0.10.0
InfluxDB shell 0.10.0
> show servers
name: data_nodes
----------------
id	http_addr			tcp_addr
1	influx301:8086	influx301:8088
2	influx302:8086	influx302:8088
3	influx303:8086	influx303:8088

name: meta_nodes
----------------
id	http_addr			tcp_addr
1	influx301:8091	influx301:8088

> 
```

**Comment by rossmcdonald** [comment]
@anuvdas Are there any details in the logs? Have you tried restarting the services on the other two nodes to see if they come up?

**Comment by anuvdas** [comment]
@rossmcdonald Nothing in logs. So once again i removed everything from /var/lib/influxdb and started the influxdb service in the order influx301,302 and 303. Now i see the below output.
```
> show servers
name: data_nodes
----------------
id	http_addr			tcp_addr
1	influx301:8086	influx301:8088
3	influx302:8086	influx302.:8088
5	influx303:8086	influx303.:8088

name: meta_nodes
----------------
id	http_addr			tcp_addr
1	influx301:8091	influx301:8088
2	influx302:8091	influx302:8088
4	influx303:8091	influx303:8088
```
Thank you so much !. Since my problem got resolved i think this thread can be closed. Once again thank you so much

**Comment by rossmcdonald** [comment]
@anuvdas Thanks for the update!
