### ISSUE TITLE
[documentation] _internal values

### ISSUE THREAD

**Issue by exeral** [influxdata/influxdb#5616]
Hello,

I would like to have some stats about the DB

the only documentation ressource I found is: https://influxdata.com/blog/how-to-use-the-show-stats-command-and-the-_internal-database-to-monitor-influxdb

Can you please describe the values for each measurement.

there are some self-explanatory values like (batchesTx, batchesTxFail, pointsRx, queryFail, queryOk, ....)

but becomes more complicated with
engine:
pointsWrite, pointsWriteDedupe ?, blksWriteBytes, blksWriteBytesC ?
what's the difference ?

and most of the runtime, wal, write values

This may be time consuming. but at least few words for the most complicated ones

thank you !

**Comment by mjdesa** [comment]
@exeral I opened an issue on the docs repo for you. Closing in favor of that issue.
