### ISSUE TITLE
apt upgrade from .9.6.1 to .10.0 breaks single node

### ISSUE THREAD

**Issue by lucask13** [influxdata/influxdb#5618]
The influxdb service is running, but is not listening on 8088, 8086, 8083 as it is configured to do as was working before the upgrade(checked with netstat --inet). This error is filling up the influxdb log:

[metaclient] 2016/02/10 12:05:15 failure getting snapshot from localhost:8088: Get http://localhost:8088?index=0: read tcp 127.0.0.1:8088: connection reset by peer
[tcp] 2016/02/10 12:05:16 tcp.Mux: handler not registered: 71

it worked right after the upgrade and restarting the service then broke while I was using grafana.

When the upgrade occurred I kept my old config file. When the issue occurred I tried creating a fresh new one and adding back in any changes and still see this issue.

**Comment by jwilder** [comment]
Can you show your config and full startup log?

cc @rossmcdonald

**Comment by lucask13** [comment]
[influx_log_excerpt.txt](https://github.com/influxdata/influxdb/files/125321/influx_log_excerpt.txt)
[influxdb.conf.txt](https://github.com/influxdata/influxdb/files/125324/influxdb.conf.txt)

**Comment by jwilder** [comment]
@lucask13 It looks like the wrong address is getting used for:
```
[metaclient] 2016/02/10 13:45:02 failure getting snapshot from localhost:8088: Get http://localhost:8088?index=0: read tcp 127.0.0.1:8088: connection reset by peer
[tcp] 2016/02/10 13:45:03 tcp.Mux: handler not registered: 71
```

What does your `meta/node.json` contents look like and are you passing in `-join` URLs anywhere?

**Comment by lucask13** [comment]
/var/lib/influxdb/meta/node.json:

{"ID":1,"MetaServers":["localhost:8088"]}

When it was working before the upgrade I believe it was just 

[":8088"]

I can change to whatever you would like for testing.

I'm not aware of any -join URLs in use. I don't use that feature. I am using Grafana on the same server if that matters.

**Comment by jwilder** [comment]
@lucask13 Ah.  Try changing that to:
```
{"ID":1,"MetaServers":["localhost:8091"]}
```

**Comment by lucask13** [comment]
@jwilder 

{"ID":1,"MetaServers":["localhost:8091"]}

Changed to this setting and influxdb service started up correctly. Seeing graphs in Grafana now. 

Anything I should have done differently to prevent this? 

Do I need to change start using the new .10.0 base config file and add my settings from .9.6.1 back in?

**Comment by jwilder** [comment]
@lucask13 Not quite sure what happened in your case.  Single node upgrade should have handled this, but didn't for you for some reason.  The config file has changed in `0.10` somewhat so you may need to review your changes.

@rkuchan @rossmcdonald Might need to add this to any upgrade troubleshooting docs we have in cases someone else runs into it.
