### ISSUE TITLE
cannot built influxdb cluster

### ISSUE THREAD

**Issue by rbrutas** [influxdata/influxdb#5619]
part of my config;

[meta]
  dir = "/mnt/.influxdb/meta"
  hostname = "localhost"
  bind-address = "192.168.1.100:8088"
  http-bind-address = "192.168.1.100:8091"

when starting influxdb, i am seeing this on the logs;
```
2016/02/10 17:49:45 InfluxDB starting, version 0.10.0, branch 0.10.0, commit b8bb32ecad9808ef00219e7d2469514890a0987a, built 2016-02-04T17:06:04.850564
2016/02/10 17:49:45 Go version go1.4.3, GOMAXPROCS set to 4
2016/02/10 17:49:45 Using configuration at: /etc/influxdb/influxdb.conf
[meta] 2016/02/10 17:49:45 Starting meta service
[meta] 2016/02/10 17:49:45 Listening on HTTP: 192.168.1.100:8091
[metastore] 2016/02/10 17:49:45 Using data dir: /mnt/.influxdb/meta
[metastore] 2016/02/10 17:49:45 Node at 192.168.1.100:8088 [Follower]
[metastore] 2016/02/10 17:49:46 Node at 192.168.1.100:8088 [Leader]. peers=[192.168.1.100:8088]
[metaclient] 2016/02/10 17:49:46 failure getting snapshot from :8091: Get http://:8091?index=0: dial tcp :8091: connection refused
[metaclient] 2016/02/10 17:49:47 failure getting snapshot from localhost:8091: Get http://localhost:8091?index=0: dial tcp 127.0.0.1:8091: connection refused
[metaclient] 2016/02/10 17:49:48 failure getting snapshot from :8091: Get http://:8091?index=0: dial tcp :8091: connection refused
[metaclient] 2016/02/10 17:49:49 failure getting snapshot from localhost:8091: Get http://localhost:8091?index=0: dial tcp 127.0.0.1:8091: connection refused
```
other nodes is showing the same issue and all are trying to start as Leader.

**Comment by rbrutas** [comment]
also http is not running;

# influx
Failed to connect to http://localhost:8086
Please check your connection settings and ensure 'influxd' is running.

# influx -host 192.168.1.100
Failed to connect to http://192.168.1.100:8086
Please check your connection settings and ensure 'influxd' is running.

# netstat -a |grep 8086
#

**Comment by mjdesa** [comment]
@rbrutas you're missing `enabled = true` in your `[meta]` section. In fact, it looks like you have the older configuration file. Your config file should look something like this:

```
...
[meta]
  enabled = true
  ...
  bind-address = "192.168.1.100:8088"
  http-bind-address = "192.168.1.100:8091"
  ...

[data]
  enabled = true
  ...

...
[http]
  ...
  bind-address = "192.168.1.100:8088"

...
```

**Comment by rbrutas** [comment]
thank you, let me make the change.

btw the config was generated by running `influxd config > influxdb.generated.conf` per the doc and the clustering part didn't mention that.

**Comment by mjdesa** [comment]
@rbrutas was the config file generated with the binary from `0.10.0` release? There was a configuration change for clustering with the new version.
