### ISSUE TITLE
InfluxDB Version 0.9.5 (Delete Query not working)

### ISSUE THREAD

**Issue by subhashv** [influxdata/influxdb#5625]
InfluxDB Delete query is not working. It says Invalid Query. Select query is working.

> delete from cpu_percent where time < now() - 1h;
ERR: invalid query
> delete from cpu_percent where time > 1455148800000000000;
ERR: invalid query
> delete from cpu_percent where time > '2016-02-09 00:00:00.000' and time <= '2016-02-09 23:59:59.999';
ERR: invalid query

Thanks & Regards
Subhash Vinnakota

**Comment by rossmcdonald** [comment]
Per #5654, the `DELETE FROM` query is currently not wired up, and has been removed from the query spec.
