### ISSUE TITLE
[0.10.0] Skipping shards in docker when stopping and starting container

### ISSUE THREAD

**Issue by scarhand** [influxdata/influxdb#5627]
### Description
When influx is run inside a docker container with a mounted volume for data storage it skips shards when the container is stopped and started again. Everything seems to work fine if the container is kept running. Data can be inserted and retrieved. But if the container stops for some reason and restarts, no data is restored.

The influx startup log shows the following messages:
```
[store] 2016/02/11 09:44:50 Using data dir: /data
[store] 2016/02/11 09:44:50 Skipping retention policy dir: node.json. Not a directory
[store] 2016/02/11 09:44:50 Skipping retention policy dir: peers.json. Not a directory
[store] 2016/02/11 09:44:50 Skipping retention policy dir: raft.db. Not a directory
[tsm1wal] 2016/02/11 09:44:50 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/02/11 09:44:50 tsm1 WAL writing to /data/wal/testdb/default/1
[cacheloader] 2016/02/11 09:44:50 reading file /data/wal/testdb/default/1/_00001.wal, size 114
[cacheloader] 2016/02/11 09:44:50 reading file /data/wal/testdb/default/1/_00002.wal, size 0
[tsm1wal] 2016/02/11 09:44:50 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/02/11 09:44:50 tsm1 WAL writing to /data/wal/testdb/default/2
[cacheloader] 2016/02/11 09:44:50 reading file /data/wal/testdb/default/2/_00001.wal, size 67
[cacheloader] 2016/02/11 09:44:50 reading file /data/wal/testdb/default/2/_00002.wal, size 0
[store] 2016/02/11 09:44:50 Skipping shard: testdb. Not a valid path
```

### Steps to reproduce
I've created a repository with a set of scripts to reproduce the issue. [https://github.com/scarhand/influx-skipping-shard](https://github.com/scarhand/influx-skipping-shard).
To reproduce, check out the repo and run make.sh.
```
$ git clone git@github.com/scarhand/influx-skipping-shard.git
$ cd influx-skipping-shard
$ ./make.sh
```

### Software versions

Influx: 
- Installed from apt repository
- version 0.10.0
- branch 0.10.0
- commit b8bb32ecad9808ef00219e7d2469514890a0987a
- built 2016-02-04T17:06:04.850564

Host:
- Ubuntu 15.10
- Linux 4.2.0-27-generic x86_64

Docker:
- version 1.6.2
- build 7c8fca2

Docker image:
- debian:jessie

**Comment by jwilder** [comment]
Thanks for making this easy to reproduce.  It looks like your `[data].Dir` config path is slightly off:

https://github.com/scarhand/influx-skipping-shard/blob/master/influxdb.conf#L51

Should be:

```
dir = "/data/data"
```

I don't get the shard skipped message when the path is changed.

**Comment by scarhand** [comment]
@jwilder you are absolutely correct. 
Thanks for the insight, this is clearly a configuration issue on my behalf.
