### ISSUE TITLE
Intermittent Test Failure - TestRunCLI

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#5631]
There are two separate paths in the code that will both close the `Quit` channel.  Since on is from can be from a system signal, and hence really in a go routine, this has the potential to cause this panic.  Only one spot in the code should try to close that channel.  I would suggest a func that anyone calls to close the channel, and either do a `sync.Once` or track some other way it has been closed to avoid this.

Here are the two areas that both try to close the same channel:

https://github.com/influxdata/influxdb/blob/master/cmd/influx/cli/cli.go#L184
https://github.com/influxdata/influxdb/blob/master/cmd/influx/cli/cli.go#L213

```
--- PASS: TestParseCommand_Quit (0.00s)
panic: close of closed channel

goroutine 8 [running]:
github.com/influxdata/influxdb/cmd/influx/cli_test.TestRunCLI.func1(0xc820080780)
    /root/go/src/github.com/influxdata/influxdb/cmd/influx/cli/cli_test.go:51 +0x28
created by github.com/influxdata/influxdb/cmd/influx/cli_test.TestRunCLI
    /root/go/src/github.com/influxdata/influxdb/cmd/influx/cli/cli_test.go:52 +0x257
```

**Comment by corylanou** [comment]
Also, I'm not sure why the `Quit` channel is public either.  You should not be able to reach inside of it and close the channel imo.

**Comment by seiflotfy** [comment]
Yeah I can help with that

**Comment by s1m0** [comment]
same error with 0.10.1-1, recently converted from bz1 to tsm1.

[retention] 2016/02/29 06:41:02 retention policy shard deletion check commencing
panic: close of closed channel
...followed by 100's of lines of goroutine details. let me know if you want me to upload the rest of the output...

**Comment by s1m0** [comment]
influxdb has crashed 3 times so far today, same panic string.

**Comment by jwilder** [comment]
@s1m0 This issue is related to a panic in the `influx` cli when running the test suite... not the server.  

Can you open a new issue and include the full stack trace in a gist?

**Comment by timhallinflux** [comment]
closing due to age.
