### ISSUE TITLE
How to backup and restore properly

### ISSUE THREAD

**Issue by undera** [influxdata/influxdb#5634]
I'm using InfluxDB 0.10.0-1 on Ubuntu 14.04. What is the right process for backup one database on one machine and restore it on another?

I tried backing up on machine1 like this: `influxd backup -database Loadosophia /tmp/ls3`
Got the dir with many files in it, one "meta.00" and a lot of "Loadosophia.default.****.00"
Then, stopped influx on machine2, copied whole dir `ls3` onto machine2, ran `influxd restore -database Loadosophia -datadir /var/lib/influxdb/data/ /tmp/ls3`
Then started influxdb. The log shows that files are in use by WAL and filestore:
```
[tsm1wal] 2016/02/11 18:42:30 tsm1 WAL writing to /var/lib/influxdb/wal/Loadosophia/default/499
[filestore]2016/02/11 18:42:30 /var/lib/influxdb/data/Loadosophia/default/499/000000004-000000003.tsm (#0) opened in 274.6µs
```

But trying to query server says that there's no database "Loadosophia".

What am I doing wrong? The doc is pretty empty and says something about single dump file, not whole directory with many files. It all looks so strange... Is version 0.10 in beta stage?

**Comment by zstyblik** [comment]
@undera you need `-metadir` as well.

**Comment by undera** [comment]
What is it? What should I specify there? Why restore command do not fail without it?

**Comment by undera** [comment]
Okay, I guessed myself to point onto /var/lib/influxdb/meta/, seems it worked now. Thanks for a tip.

PS. Having this documented on docs site would be great...

**Comment by rossmcdonald** [comment]
This will be documented once https://github.com/influxdata/docs.influxdata.com/pull/228 is merged, which should hopefully be later today.

**Comment by undera** [comment]
Awesome news

**Comment by zstyblik** [comment]
@undera sorry, but I'm using custom path for meta dir, therefore I couldn't be of more help nor I had much of a free time at that time.

**Comment by retorquere** [comment]
Is the backup format specced somewhere? I'm looking for a way to dump my database to csv/mat and there's too much data in influxdb to do it via the API.
