### ISSUE TITLE
[0.10.0] "show measurements" capped by 10000

### ISSUE THREAD

**Issue by undera** [influxdata/influxdb#5635]
I have more than 10000 measurements in database. For case of maintenance, I need to get full list of measurements. 

I found no way to receive full list, it is always capped by 10000. How can I disable this capping?

**Comment by undera** [comment]
I'm using InfluxDB 0.10.0-1 on Ubuntu 14.04

**Comment by zstyblik** [comment]
@undera it's probably capped in the code. Therefore, find the cap, increase it, recompile InfluxDB, deploy your own version. My guess based on similar question I had. Might not be true at all.

**Comment by undera** [comment]
I believe there's some option to increase the limit. Having it hard-capped in the code could be strange in 21st century...

**Comment by danielsand** [comment]
any news on this ? on grafana this is really a big problem with the query editor.

**Comment by pauldix** [comment]
This should be fixed in 0.11.0 and in the current nightly build. Please re-open if you see it's still there.

**Comment by andyleslie81** [comment]
@pauldix Hi Paul we've just upgraded to 0.11.1 and have found the limit of 10000 is still in place. FYI this was for a database using the graphite plugin.

Thanks,

Andrew
