### ISSUE TITLE
[0.10] Backup stop working

### ISSUE THREAD

**Issue by mizalewski** [influxdata/influxdb#5648]
I upgraded Influxdb from 0.9.6 to 0.10.0 from APT repository and backup stop working.
When I tried to create backup I got message:

```
Invalid metadata blob, ensure the metadata service is running (default port 8088)
backup failed: invalid metadata received
backup: invalid metadata received
```

After that I tried to restart Influx and try to do backup again. This time I got below messages:

```
 backing up metastore to snapshot1/meta.00
 backup complete
```

But when I look on snapshot1 directory I saw only meta.00 file with 2,5 KB size (before backups has about 1,3 GB).

System: Ubuntu 14.04
I attached my Influx configuration:
[influxdb.zip](https://github.com/influxdata/influxdb/files/127801/influxdb.zip)

Please let me known if you more information.

**Comment by zstyblik** [comment]
@mizalewski it'd help to provide the commands you've issued. Also, I'm not sure if "backup all" really works. In other words, you've only backed up meta data. You have to pass `-database mydatabase` to backup specific database.

**Comment by rossmcdonald** [comment]
@mizalewski In addition to the commands you've tried. Did you convert the 0.9.6 shards to tsm using the `influx_tsm` conversion tool? There are instructions on how to do this [here](https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm).

**Comment by mizalewski** [comment]
@zstyblik  I can't backup single database, I got few empty files in directory.
@rossmcdonald You have right, I have old bz1 format, but when I tried to convert to tsm I got below error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x68f211]

goroutine 20 [running]:
github.com/boltdb/bolt.(*Tx).Rollback(0x0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/tx.go:231 +0x31
github.com/influxdb/influxdb/cmd/influx_tsm/bz1.(*Reader).Close(0xc208156090, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/bz1/reader.go:178 +0x3e
main.convertShard(0xc208039d00, 0xc20802efc0, 0x7f38ae6a0bc0, 0xc2080ee8c0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:329 +0x591
main.func·007()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:91 +0x1e8
main.ParallelGroup.Do(0xc20805dce0, 0xc20801cba0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:366 +0x86
created by main.(*tracker).Run
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:95 +0x4ef

goroutine 1 [select]:
main.(*tracker).Run(0xc20802efc0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:106 +0x717
main.main()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:214 +0x1867

goroutine 6 [syscall]:
os/signal.loop()
        /root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:27 +0x35

goroutine 18 [runnable]:
github.com/boltdb/bolt.flock(0xc208182000, 0xc208182001, 0x3b9aca00, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/bolt_unix.go:38 +0x1b7
github.com/boltdb/bolt.Open(0xc20815c0f0, 0x26, 0xc2000001b6, 0xc20812eab0, 0xc20815c0f0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/db.go:180 +0x257
github.com/influxdb/influxdb/cmd/influx_tsm/bz1.(*Reader).Open(0xc20817c000, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/bz1/reader.go:55 +0x9b
main.convertShard(0xc208039a80, 0xc20802efc0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:328 +0x3f1
main.func·007()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:91 +0x1e8
main.ParallelGroup.Do(0xc20805dce0, 0xc20801cb60)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:366 +0x86
created by main.(*tracker).Run
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:95 +0x4ef

goroutine 17 [runnable]:
github.com/boltdb/bolt.flock(0xc20810c0e0, 0xc20810c001, 0x3b9aca00, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/bolt_unix.go:38 +0x1b7
github.com/boltdb/bolt.Open(0xc2080f13b0, 0x26, 0xc2000001b6, 0xc2080fcab0, 0xc2080f13b0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/db.go:180 +0x257
github.com/influxdb/influxdb/cmd/influx_tsm/bz1.(*Reader).Open(0xc20810afc0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/bz1/reader.go:55 +0x9b
main.convertShard(0xc208039980, 0xc20802efc0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:328 +0x3f1
main.func·007()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:91 +0x1e8
main.ParallelGroup.Do(0xc20805dce0, 0xc20801cb40)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:366 +0x86
created by main.(*tracker).Run
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:95 +0x4ef

goroutine 19 [runnable]:
main.convertShard(0xc208039bc0, 0xc20802efc0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:329 +0x499
main.func·007()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:91 +0x1e8
main.ParallelGroup.Do(0xc20805dce0, 0xc20801cb80)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:366 +0x86
created by main.(*tracker).Run
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:95 +0x4ef

goroutine 21 [runnable]:
github.com/boltdb/bolt.flock(0xc208182008, 0xc208182001, 0x3b9aca00, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/bolt_unix.go:38 +0x1b7
github.com/boltdb/bolt.Open(0xc20815c270, 0x26, 0xc2000001b6, 0xc208134ab0, 0xc20815c270, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/db.go:180 +0x257
github.com/influxdb/influxdb/cmd/influx_tsm/bz1.(*Reader).Open(0xc20817c090, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/bz1/reader.go:55 +0x9b
main.convertShard(0xc208039dc0, 0xc20802efc0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:328 +0x3f1
main.func·007()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:91 +0x1e8
main.ParallelGroup.Do(0xc20805dce0, 0xc20801cbc0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:366 +0x86
created by main.(*tracker).Run
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:95 +0x4ef

goroutine 22 [runnable]:
github.com/boltdb/bolt.flock(0xc208160000, 0xc208160001, 0x3b9aca00, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/bolt_unix.go:38 +0x1b7
github.com/boltdb/bolt.Open(0xc208148030, 0x26, 0x1b6, 0xc2080f8ab0, 0x4444488cc4484401, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/db.go:180 +0x257
github.com/influxdb/influxdb/cmd/influx_tsm/bz1.(*Reader).Open(0xc208156000, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/bz1/reader.go:55 +0x9b
main.convertShard(0xc208039ec0, 0xc20802efc0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:328 +0x3f1
main.func·007()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:91 +0x1e8
main.ParallelGroup.Do(0xc20805dce0, 0xc20801cbe0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:366 +0x86
created by main.(*tracker).Run
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:95 +0x4ef

goroutine 23 [runnable]:
github.com/boltdb/bolt.flock(0xc208180000, 0xc208180001, 0x3b9aca00, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/bolt_unix.go:38 +0x1b7
github.com/boltdb/bolt.Open(0xc208172030, 0x26, 0x1b6, 0xc2080fdab0, 0x4444488cc4484401, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/db.go:180 +0x257
github.com/influxdb/influxdb/cmd/influx_tsm/bz1.(*Reader).Open(0xc208176000, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/bz1/reader.go:55 +0x9b
main.convertShard(0xc208039f80, 0xc20802efc0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:328 +0x3f1
main.func·007()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:91 +0x1e8
main.ParallelGroup.Do(0xc20805dce0, 0xc20801cc00)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:366 +0x86
created by main.(*tracker).Run
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:95 +0x4ef

goroutine 24 [running]:
        goroutine running on other thread; stack unavailable
created by main.(*tracker).Run
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:95 +0x4ef

goroutine 25 [semacquire]:
sync.(*WaitGroup).Wait(0xc20802f080)
        /root/.gvm/gos/go1.4.3/src/sync/waitgroup.go:132 +0x169
main.func·008()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:100 +0x42
created by main.(*tracker).Run
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:102 +0x5da
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x68f211]

goroutine 24 [running]:
github.com/boltdb/bolt.(*Tx).Rollback(0x0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/boltdb/bolt/tx.go:231 +0x31
github.com/influxdb/influxdb/cmd/influx_tsm/bz1.(*Reader).Close(0xc208184000, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/bz1/reader.go:178 +0x3e
main.convertShard(0xc2080e6040, 0xc20802efc0, 0x7f38ae6a0bc0, 0xc20816e060)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:329 +0x591
main.func·007()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:91 +0x1e8
main.ParallelGroup.Do(0xc20805dce0, 0xc20801cc20)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:366 +0x86
created by main.(*tracker).Run
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cmd/influx_tsm/tracker.go:95 +0x4ef

**Comment by rossmcdonald** [comment]
@mizalewski Can you provide the verbatim commands you used to produce the panic?

/cc @jwilder

**Comment by mizalewski** [comment]
Sure, sorry, I forget to put command.
I used two commands (both ends with panic):
influx_tsm -backup ~/influxdb_backup -parallel /var/lib/influxdb/data/
influx_tsm -backup ~/influxdb_backup -dbs "mydb" -parallel /var/lib/influxdb/data/

**Comment by jwilder** [comment]
Created a new isssue #5656 for the panic seen in the conversion tool.

**Comment by zstyblik** [comment]
@jwilder, since #5656 has been closed, can this issue be closed too?

**Comment by mizalewski** [comment]
I closed this issue because it was related to very old version.
