### ISSUE TITLE
[0.10.0] DROP RETENTION POLICY does not clean up data.

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#5653]
It's not implemented on the `tsdb.Store`, so data is not cleaned up after the retention policy is removed.

**Comment by zstyblik** [comment]
I wonder, once fixed, is it going to cleanup/free the data from RPs that have been dropped in the past/before fix?

**Comment by e-dard** [comment]
@zstyblik unfortunately not.

**Comment by zstyblik** [comment]
@e-dard :-\ Is there any trick how to achieve that? How about backup and restore? Could it  do the trick?

**Comment by e-dard** [comment]
@zstyblik doing "cleanup" automatically can be problematic, and lead to the loss of data if there are bugs etc. My suggestion would be to manually check for any retention policy you don't want and remove the data that way. 

Retention policies are stored as follows:

```
├── _internal
│   └── monitor
│       ├── 3
│       │   └── 000000002-000000002.tsm
│       └── 7
│           ├── 000000004-000000003.tsm
│           └── 000000006-000000002.tsm
├── db0
│   ├── default
│   │   └── 8
│   └── other_rp
│       └── 9
└── foo
    └── default
        └── 4
            └── 000000001-000000001.tsm
```

In this case there are two databases (`db0` and `foo`) and the database `db0` has two retention policies `default` and `other_rp`.

If you dropped the `other_rp` retention policy and because of this bug the data is still there, you can shutdown `influxd` and remove the `other_rp` folder.

**Comment by zstyblik** [comment]
@e-dard I see. Alright then, I'll keep it in mind. Although, with other fixes related to TSM, backup & restore might be worth of trying first. Thanks.
