### ISSUE TITLE
Please add 'retention policy' to graphite endpoint configuration

### ISSUE THREAD

**Issue by sysadmin1139** [influxdata/influxdb#5655]
It would be great if we could specify a retention-profile to associate with a given graphite listener. Here is the use-case:

We use [StatsD](https://github.com/etsy/statsd/) to collate some metrics. Due to the nature of our data-flows, we want to run statsd dumping at two different intervals. One for every 10 seconds, and a second one for every 60s. The 10s granularity data would be kept for 7 days, and the 60s granularity data kept for 60 days. We could use Continuous Queries to roll-up this data, but there is one data-type that doesn't fit well with a roll-up policy, uniques-per-time-interval.

Using the StatsD concept of [sets](https://github.com/etsy/statsd/blob/master/docs/metric_types.md#sets), we can track incoming IP addresses. With the default flush interval of 10 seconds, we can tell that N address were unique in that period. With CQs, the best we can do is derive the min/median/max uniques during that period, but not the actual uniques in the time-interval.

Alternately, we can write the 60s data to a different field, and write the CQs to extract from there. However, it would be more efficient on Influx if the external service could do the aggregations. By writing directly to the Retention Policy for that interval, we can tell that there were M unique IP addresses in the wider interval and not add complexity to our CQs.

Such a config would look like this:

```
[[graphite]]
  enabled = true
  bind_address = ":2003"
  protocol = "tcp"
  # Unspecified retention_policy, so will use "default" policy

[[graphite]]
  enabled = true
  bind_address = ":2009"
  protocol = "tcp"
  retention_policy = "60day"
```

We would then point the statsd instances aggregating on 60-second flush-times to dump data to the `:2009` port

**Comment by jsternberg** [comment]
It seems like the current version of our TOML parser doesn't support nested tables so I can't currently make it so you can specify all of the options for setting a retention policy. I also don't want to only allow the graphite endpoint to only use the default retention policy.

Is it ok if the config option is this:

```
retention-policy = "policy-name"
```

Then it will use that retention policy. You can then either create the database ahead of time along with the retention policy (which it will use) or you can use `ALTER RETENTION POLICY`. Is this an OK alternative?

**Comment by sysadmin1139** [comment]
My assumption was that I would pre-create the database and retention policies, and then set up the additional endpoints. Influx is not exactly a mayfly service, so persistence is something we can count on. The option you suggest works for me.
