### ISSUE TITLE
Add gossip protocol for determining node addresses

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#5672]
We currently store address information in the meta store.  We should remove all address information and only store the node ID's.  Then, using a gossip protocol, we should determine addresses as needed.  This will also allow for us to determine if a node is reachable or not and could be displayed in the `SHOW SERVERS` command.

- [ ] Remove address info from meta.Data
- [ ] Cluster gossip/topology service

**Comment by jsternberg** [comment]
Clustering is removed from the open source version so I'm closing this.
