### ISSUE TITLE
cannot start or restart InfluxDB 

### ISSUE THREAD

**Issue by genagain** [influxdata/influxdb#5676]
Hello,

I am currently running InfluxDB version 0.9.4.2 on a RHEL 7.2 VM. I am pretty we installed InfluxDB from a prebuilt package, however I am not sure because I didn't install it.

I tried restarting InfluxDB it keeps on repeating the same set of logs, fails and does this on repeat. To cause this issue I ran ```sudo systemctl restart influxdb``` because I figured it would start up again. There was a large amount of monitoring data from Sensu in InfluxDB so this may be part of the reason it cannot start or restart. Unfortunately, there were no logs prior to me restarting it.

This is the output from running ```sudo systemctl status influxdb -l```

```
Feb 12 17:55:59 moc-sensu.moc.ne.edu influxd[3676]: [wal] 2016/02/12 17:55:59 WAL writing to /var/opt/influxdb/wal/sensu_db/default/88
Feb 12 17:55:59 moc-sensu.moc.ne.edu influxd[3676]: [wal] 2016/02/12 17:55:59 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
Feb 12 17:55:59 moc-sensu.moc.ne.edu influxd[3676]: [wal] 2016/02/12 17:55:59 WAL writing to /var/opt/influxdb/wal/sensu_db/default/89
Feb 12 17:56:00 moc-sensu.moc.ne.edu influxd[3676]: [wal] 2016/02/12 17:56:00 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
Feb 12 17:56:00 moc-sensu.moc.ne.edu influxd[3676]: [wal] 2016/02/12 17:56:00 WAL writing to /var/opt/influxdb/wal/sensu_db/default/90
Feb 12 17:56:00 moc-sensu.moc.ne.edu influxd[3676]: [wal] 2016/02/12 17:56:00 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
Feb 12 17:56:00 moc-sensu.moc.ne.edu influxd[3676]: [wal] 2016/02/12 17:56:00 WAL writing to /var/opt/influxdb/wal/sensu_db/default/91
Feb 12 17:56:00 moc-sensu.moc.ne.edu influxd[3676]: [wal] 2016/02/12 17:56:00 reading WAL files to flush to index
Feb 12 17:56:00 moc-sensu.moc.ne.edu influxd[3676]: [retention] 2016/02/12 17:56:00 retention policy enforcement terminating
Feb 12 17:56:00 moc-sensu.moc.ne.edu influxd[3676]: [monitor] 2016/02/12 17:56:00 shutting down monitor system
```

Then after a while this is the output when it fails.
```
Feb 12 18:07:07 moc-sensu.moc.ne.edu systemd[1]: influxdb.service: main process exited, code=exited, status=1/FAILURE
Feb 12 18:07:07 moc-sensu.moc.ne.edu systemd[1]: Unit influxdb.service entered failed state.
Feb 12 18:07:07 moc-sensu.moc.ne.edu systemd[1]: influxdb.service failed.
```
And then it repeats.

Could someone please help me with this?

**Comment by rossmcdonald** [comment]
@genagain Is there any extra information in syslog or maybe `dmesg`? It's possible that it keeps running out of memory when attempting to read in the WAL cache from disk, but it's hard to tell without more information.

I would also recommend upgrading if possible.

**Comment by genagain** [comment]
@rossmcdonald Thank you for your reply. Apparently one of the shards was corrupted, which is why it wasn't working. I'll close this issue because the problem is now solved.
