### ISSUE TITLE
How do i compute percentage ?

### ISSUE THREAD

**Issue by deepujain** [influxdata/influxdb#5684]
I have two queries below, how do i write a query that can compute percentage across these two series

(Q2/Q1)*100 = 3/4 * 100 = 75

Inner queries is not supported and threw me syntax error.

Q1:
> select totalExperiments as total from experiment where dataDate='2/13/16'
name: experiment
----------------
time			total
1455350400000000000	4

Q2:
> SELECT sum("count") as count FROM "dataquality"  where alertId='5' and (time >='2016-02-13T00:00:00Z' AND time <'2016-02-14T00:00:00Z')   
name: dataquality
-----------------
time			count
1455321600000000000	3

>

**Comment by deepujain** [comment]
> SELECT sum("count") / (select totalExperiments as total from experiment where dataDate='2/13/16') as count FROM "dataquality"  where alertId='5' and (time >='2016-02-13T00:00:00Z' AND time <'2016-02-14T00:00:00Z')   
ERR: error parsing query: found SELECT, expected identifier, string, number, bool at line 1, char 24
>

**Comment by rossmcdonald** [comment]
@deepujain Unfortunately nested/inner queries are currently not supported. There is a feature request to add support for them here: #4619. The same applies for math across measurements, which would also help solve your problem. The feature request for that is here: #3552.
