### ISSUE TITLE
tsm: snapshots leak and data may disappear on restart if a compaction fails due transient write errors

### ISSUE THREAD

**Issue by jonseymour** [influxdata/influxdb#5686]
This issue is based on a code review, rather than something I have seen in the wild. If my analysis is incorrect, then feel free to close the issue.

It seems to me that if the periodic snapshotting and compaction fails (perhaps because of a temporary shortage of disk space on the database's file system) a snapshot will be retained in memory and never be released. If such transient disk space shortages were to occur regularly, "abandoned" snapshots could accumulate in memory, eventually resulting in an OOM condition.

A fix might be to handle this case by registering the snapshot associated with a failed compaction in the cache and then when Cache.ClearSnapshot runs after the next successful compaction, clearing these snapshots as well.

**Comment by jonseymour** [comment]
As noted in the pull request, currently if a snapshot isn't written properly on the first attempt, the contents will never make it into TSM files unless the server is restarted prior to the next successful compaction attempt. The problem here is that writes into TSM files always occur directly out of the snapshot and never from the WAL segment and currently, the snapshot write is tried at most once. If the write error that caused the snapshot write to fail is transient, then the next successful write attempt will result in all the current WAL segments being deleted from disk. The data will still appear to be in the database (because it is still in the cache) but on subsequent restart, the data will no longer be accessible.

The proposed series fixes this issue by retrying (on each compaction cycle) failed snapshot writes (in order) until they succeed.

**Comment by jwilder** [comment]
@jonseymour I think you are right that there is a possibility of a leak/wal segment getting lost due to the way wal segments are removed.  I need to take a closer look at the code and this change though.

**Comment by jonseymour** [comment]
@jwilder - this shows how the new cache statistics from #5499 can be used to detect leaking snapshots due to transient write errors. In this case, I caused them by removing write permissions from the shard's TSM directory.

![demonstrate](https://www.dropbox.com/s/almqydv9h68m3g7/Screenshot%202016-02-22%2016.36.49.png?dl=0&raw=1)
