### ISSUE TITLE
High memory usage - too much shard active ?

### ISSUE THREAD

**Issue by easyrasta** [influxdata/influxdb#5687]
thank's @jonseymour. 

My influxdb server consume 16 Go and I only write 2k-5k serie /s
On previous version (not TSM engine) I consume between 2Go-4Go of memory

I open new issue ( i writed in #5685)
https://gist.github.com/easyrasta/e8166c3e8aab6c05e2e7

(In given svg prof it's only marke 6 Go ?)

How I could reduce shard ?  cache ?

**Comment by jwilder** [comment]
It's really helpful to include some basic information in a bug report in order for us to understand the problem.  We have a [document](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#bug-reports) explaining some of these things and it would be great if you could add those details.

Is there an error or panic you're seeing?  If so, can you add the full trace in a gist?

Could you share some example data that your are writing?  If you are using tags, how do the values vary?  What range of time are you writing data against?

**Comment by easyrasta** [comment]
I closed issue, I couldnt add data. It's comsumer data. I use tag, may be it's due too much cardinality (one tag is an uuid) even if I have few tags.
If you think there isn't any memory problem. 
But it would ne nice to have doc on configuration, specially about cache tuning.

**Comment by jwilder** [comment]
@easyrasta One of the tag values is a uuid?  If you have many distinct uuid values then that will create a new series which incurs more RAM.
