### ISSUE TITLE
Sort by aggregated field (or any field)

### ISSUE THREAD

**Issue by pribiswas** [influxdata/influxdb#5688]
Suppose, There are following points in site_visits series of InfluxDb:
{account_id: 1, user_id: 2, value: 1.0}
{account_id: 1, user_id: 3, value: 1.0}
{account_id: 2, user_id: 1, value: 1.0}

I want total visits grouped by account id in descending order:
SELECT COUNT(value) as visits FROM site_visits GROUP BY account_id ORDER BY visits desc

But influxdb v10.0.0 complains that only order by time has been supported. 

Can you please provide the ability to sort by any field, otherwise I need to do the sorting in my app end which hampers the performance ?

**Comment by umatomba** [comment]
Hello, do you have any progress since 2016?

**Comment by laudukang** [comment]
+1

**Comment by jasonturner** [comment]
+1
