### ISSUE TITLE
Add monthly and yearly interval support to time function

### ISSUE THREAD

**Issue by pspeybro** [influxdata/influxdb#569]
Currently, the time function documentation states:

The time function takes the time interval which can be in microseconds, seconds, minutes, hours, days or weeks. To specify the units you can use the respective suffix u, s, m, h, d and w.

When producing "something", reporting often contains monthly averages or totals. 
This is currently not possible due to the irregular number of days per month.

I suggest to add extra suffixes for month and year: mo & y respectively.
Or perhaps another letter for month if this is assumed to be one letter.

The yearly interval is probably less used, but again, not all years have the same number of days so specifying 365d is not correct when aggregating over several years.

select count(type) as number_of_types group by time(1mo);

**Comment by mvadu** [comment]
@pauldix #387 was closed without actually adding year or monthly grouping constructs. In prior builds (e.g. influxdb-1.2.4-1) I was able to use the `Group By time(1M)` and get the results properly. But in latest version (influxdb-1.3.7-1) same query throws an error about `invalid duration`. Was it a regression miss or explicitly removed?

**Comment by rbetts** [comment]
@mvadu The parser used to accept durations like `1M` but produced an invalid result. This was a defect that was resolved in 1.3.0 (https://github.com/influxdata/influxdb/issues/8181).  InfluxQL 1.2 didn't support grouping by months.

We're tracking support for these operators here: https://github.com/influxdata/influxdb/issues/2071

**Comment by mvadu** [comment]
Thanks @rbetts #2071 is long time in making :) For my business case monthly grouping is mission critical, and for now I have reverted back to 1.2.4.

**Comment by jsternberg** [comment]
@mvadu I think you may have misunderstood. We have never had monthly grouping support. You may want to check your existing queries as they are likely not doing what you think they are doing. If you did `GROUP BY time(1M)` it is actually doing `GROUP BY time(0s)`.

**Comment by mvadu** [comment]
@jsternberg you are right!! In my grafana panel, I have the time column hidden, and old version returns series with `1969-12-31T19:00:00-05:00`. But with the `GROUP BY time(0s)` entire time window gets collapsed into one, and grafana kind of takes care of outer time boundaries to first and last of the month. So net result is my panel shows only one entry/series for the entire month. 

Changing it to `30d` spoils it by splitting to one for `2017-08-21T20:00:00-04:00` and `2017-09-20T20:00:00-04:00`, which spoils the display.
