### ISSUE TITLE
[0.9.6] disable Raft consensus group / port 8088

### ISSUE THREAD

**Issue by GalaxyGorilla** [influxdata/influxdb#5690]
Hi, for security reasons I need to disable as many ports as possible for InfluDB. In my thinking I just need one port for metrics consumption (8086 for http in my case) and thats it. But I don't get the port for the Raft consensus group closed in the 'meta' section of the configuration (by default it is 8088). Is it possible to close this port too? 

EDIT: I just  have a single InfluxDB instance.

**Comment by jwilder** [comment]
No.  In a single server mode, you need to have raft running as well.  You can bind it to your loopback interface though and not expose it over your network.
