### ISSUE TITLE
negation

### ISSUE THREAD

**Issue by bechampion** [influxdata/influxdb#5692]
Hi guys.

Is there any way to do something like

select * from /.*(?!Dogs).*test.*/  where etc=1 ;

sort of give me collection with .*test.* in it but NOT "Dogs" in the name?

Is that even possible yet?

Thanks!

**Comment by rossmcdonald** [comment]
@bechampion Not at this time. InfluxQL only supports regex syntax supported by the `regexp` Go package. Looking at the supported syntax [here](https://github.com/google/re2/wiki/Syntax), it doesn't look like the negative lookahead assertion is currently supported.
