### ISSUE TITLE
re-CREATE DATABASE with default duration deletes old data!

### ISSUE THREAD

**Issue by dkerwin** [influxdata/influxdb#5696]
Hi,

when a database and associated measurements already exist and you run "CREATE DATABASE IF NOT EXISTS x WITH DURATION..." **the data is gone**. Example:

```
> use dkn
Using database dkn

> select count(value) from processed_by_client
name: processed_by_client
-------------------------
time	count
0	213

> CREATE DATABASE IF NOT EXISTS dkn WITH DURATION 90d REPLICATION 1

> select count(value) from processed_by_client
> show measurements
>
```

If i skip "WITH DURATION..." everything behaves as expected. From my perspective "IF NOT EXISTS" should never ever delete data! Looks like a pretty bad bug to me.

Cheers :beers: 
Daniel

**Comment by jsternberg** [comment]
This issue has two problems that cause it.

The first problem is that `CREATE DATABASE` no longer seems to throw an error when recreating a database. The second is that the create database statement doesn't catch that error so fixing only `CREATE DATABASE` would cause `IF NOT EXISTS` to be ignored.

The second part is easy to fix and the first part is related to #5563.

**Comment by jsternberg** [comment]
After talking with others on the team, I've learned that the behavior has changed so `IF NOT EXISTS` is the default. I'm looking into why this seemingly drops an existing database as that is definitely a very large problem.

**Comment by dkerwin** [comment]
Awesome :clap:
