### ISSUE TITLE
Remove IF NOT EXISTS from create database command

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#5707]
The `IF NOT EXISTS` syntax for `CREATE DATABASE` is now the default and only behavior. This ticket is to remove the syntax from the parser.

The earliest this should be done is 0.12. The syntax will be ignored in 0.10 and 0.11.

Related to #5563.

**Comment by toddboom** [comment]
For 'v0.13.0', this should log a warning message telling the user that `IF NOT EXISTS` queries are now default and will be removed in `v1.0.0`.

Also, we should make sure that any other queries used to support `IF NOT EXISTS` have this same warning.
