### ISSUE TITLE
Error - testing Cluster setup on Windows

### ISSUE THREAD

**Issue by mvadu** [influxdata/influxdb#5715]
I am trying to test cluster setup on Windows, and cross platform with RaspberryPi.
I have made changes to the config file 

```go
[meta]
  bind-address = "<host name>:8088"
  http-bind-address = "<host name>:8091"
[http]
 bind-address = "<host Name>:8086"
```

Then I startup first node in Windows, and trying to join it from a node running in another PC. I keep getting `[metastore] 2016/02/17 11:21:04 waiting for join peers to match config specified. found [<host1>:8088 <host2>:8088], config specified [<host1>:8091]` error (added as part of #5602, in [store.go](https://github.com/influxdata/influxdb/blob/cd568548fda669f268c6a2e299e9a9fefb7eb720/services/meta/store.go#L97)) 

I tried joining from a node running on raspberry pi, and got same result. My question is, is it specific to Windows? Any pointers where to start debugging?

**Comment by mvadu** [comment]
@rossmcdonald I tried that, now I am getting different type of errors..

```go
[meta] 2016/02/20 00:02:31 192.168.22.15 - - [20/Feb/2016:00:02:31 +0530] POST /join HTTP/1.1 500 25 - Go 1.1 package http 22d98646-d737-11e5-804d-000000000000 2.0032ms
[meta] 2016/02/20 00:02:31 store not open

[meta] 2016/02/20 00:02:31 192.168.22.15 - - [20/Feb/2016:00:02:31 +0530] POST /join HTTP/1.1 503 25 - Go 1.1 package http 22d91825-d737-11e5-8047-000000000000 1.9989ms
[meta] 2016/02/20 00:02:31 no leader

[metastore] 2016/02/20 00:25:11 [ERR] raft: Failed to make RequestVote RPC to Batman-G750:8088: dial tcp 192.168.22.15:8088: ConnectEx tcp: i/o timeout
[metastore] 2016/02/20 00:25:12 [WARN] raft: Election timeout reached, restarting election
[metastore] 2016/02/20 00:25:12 [INFO] raft: Node at WIN-RSQ0FRMKUTB:8088 [Candidate] entering Candidate state
[metastore] 2016/02/20 00:25:12 [DEBUG] raft: Votes needed: 2
[metastore] 2016/02/20 00:25:12 [DEBUG] raft: Vote granted from WIN-RSQ0FRMKUTB:8088. Tally: 1
[metastore] 2016/02/20 00:25:12 [ERR] raft: Failed to make RequestVote RPC to Batman-G750:8088: dial tcp 192.168.22.15:8088: ConnectEx tcp: i/o timeout
[meta] 2016/02/20 00:25:13 no leader
```

**Comment by rossmcdonald** [comment]
@mvadu What do your `-join` parameters look like for each node?

**Comment by mvadu** [comment]
I have this `influxd.exe -config influxdb.conf -join WIN-RSQ0FRMKUTB:8091,Batman-G750:8091` on both hosts. Using conf file with respective host names.

**Comment by mvadu** [comment]
I think #5706 is not working on Windows. Setting top level hostname is not propagating to down levels. This leads to below set of errors on Windows, even without any cluster setup. Just `influxd.exe -config influxdb.conf` is giving me these errors:


```go
2016/02/20 20:04:44 InfluxDB starting, version 0.9, branch unknown, commit unknown, built unknown
2016/02/20 20:04:44 Go version go1.4.3, GOMAXPROCS set to 8
2016/02/20 20:04:44 Using configuration at: influxdb.conf
[meta] 2016/02/20 20:04:44 Starting meta service
[meta] 2016/02/20 20:04:44 Listening on HTTP: [::]:8091
[metastore] 2016/02/20 20:04:44 Using data dir: ./influxdb/meta
[metastore] 2016/02/20 20:04:45 Node at BATMAN-G750:8088 [Follower]
[metastore] 2016/02/20 20:04:47 Node at BATMAN-G750:8088 [Leader]. peers=[BATMAN-G750:8088]
[metaclient] 2016/02/20 20:04:47 failure getting snapshot from :8091: Get http://:8091?index=0: dial tcp :8091: ConnectEx tcp: The requested address is not valid in its context.
```

**Comment by jsternberg** [comment]
Clustering [has been removed](https://influxdata.com/blog/update-on-influxdb-clustering-high-availability-and-monetization/) from the open source version so I'm going to close this issue. If you need an open source solution for high availability, please try the [relay](http://docs.influxdata.com/influxdb/latest/high_availability/relay/). Thanks.
