### ISSUE TITLE
[0.10] show tag keys failing with ERR: write message type: use of closed network connection

### ISSUE THREAD

**Issue by SkyRocknRoll** [influxdata/influxdb#5717]
ii  influxdb                      0.10.0-1            amd64               Distributed time-series database.
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.10.0
InfluxDB shell 0.10.0
> use telegraf
Using database telegraf
> show tag keys
ERR: write message type: use of closed network connection

**Comment by SkyRocknRoll** [comment]
the same version of influxdb in my local machine returning proper output.

**Comment by jwilder** [comment]
I tried `0.10` and current master and `show tag keys` works as expected.
