### ISSUE TITLE
InfluxDB CQ resample

### ISSUE THREAD

**Issue by jadbox** [influxdata/influxdb#5727]
Does the CQ resample perform a full scan of the originating data or is it an incremental build based on new entries since last sample?

Docs are not clear on it:
https://docs.influxdata.com/influxdb/v0.10/query_language/continuous_queries/

**Comment by jsternberg** [comment]
To my knowledge, it's a full scan of the originating data.

**Comment by jsternberg** [comment]
Closing this since there is a ticket to update the documentation.

**Comment by jadbox** [comment]
@jsternberg Should there be a feature for incremental build? If so, should this ticket be reopened? We process a huge amount of data into rollups and would benefit from rolling sumations.

**Comment by jsternberg** [comment]
No idea if we can do the actual feature yet or not, but please either open a new issue or modify this one to be a feature request with `[feature request]` in the title. Make sure to describe your workflow and exactly what you want so we can look into it and hopefully get back to you soon. At the least, we'll be able to look at it when deciding on what features we're going to work on for 0.12.
