### ISSUE TITLE
Semi-colon is (for the most part) completely ignored as part of the syntax

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#5728]
If you run the following query, there is no error.

```
> create database mydb create database mydb2
```

This is supposed to be:

```
> create database mydb; create database mydb2
```

This also does not cause an error. This one does cause an error:

```
> create database mydb;; create database mydb2
```

**Comment by jsternberg** [comment]
The documentation seems to indicate that the semi-colon is required: https://docs.influxdata.com/influxdb/v0.10/query_language/spec/#queries

@pauldix @jwilder I can fix this to make the semi-colon required, but that will make this query not valid:

```
create database mydb
create database mydb2
```

I'm thinking it would be nice if this was valid so that text files don't have to use semi-colons when being uploaded using something like curl, but that would require adding newline support into the scanner and parser. Are there any objections to me doing that?

**Comment by minollo** [comment]
From what I see, this fix seems to have broken something: when I try running two queries separated by semicolon, only the first one is actually processed.

**Comment by jsternberg** [comment]
@minollo can you post a reproducer for that in #6220? That issue seems to reference two things. One is the semi-colon parse issue which is likely going to stay the way it is from this fix as the previous only worked because of a bug. The second problem mentioned would be a bug if that is happening, but a reproducer would be really helpful to investigate it.

**Comment by minollo** [comment]
The reproducer I have is equivalent to the one mentioned by the original 
poster in 6220.
When I submit two queries separated by semicolon (as required by the 
syntax fix), only one query is executed - and only one [query] logging 
line, specifying the first SELECT expression, is output (even if the 
HTTP communication does contain both queries).

**Comment by jsternberg** [comment]
Unfortunately, I'm not able to reproduce that behavior. Can you show me the command you use to make the query and the logged output from the influxd process?

**Comment by minollo** [comment]
OK, I have been digging deeper. And I believe you are right; this is a 
Grafana problem, not an InfluxDB one. It looks like when I specify a 
semicolon Grafana submits a bogus query:

[http] 2016/04/06 13:53:50 131.239.31.200 - minollo 
[06/Apr/2016:13:53:50 -0400] OPTIONS
/query?%0ASELECT+mean%28%22value%22%29+FROM+%22temperature%22+WHERE+%22location%22+%3D+%27Fifer+Lane%27+AND+%22device%22+%3D+%27Garage%27+AND+time+%3E+now%28%29+-+48h+GROUP+BY+time%2830m%29%2C+%22device%22+fill%28null%29=
&db=SmartThings
&epoch=ms
&p=%5BREDACTED%5D
&q=SELECT+mean%28%22value%22%29+FROM+%22temperature%22+WHERE+%22location%22+%3D+%27Fifer+Lane%27+AND+%22device%22+%3C%3E+%27Garage%27+AND+time+%3E+now%28%29+-+48h+GROUP+BY+time%282m%29%2C+%22device%22+fill%28null%29
&u=minollo

InfluxDB ignores the first query following /query?, and it's honoring 
only the q parameter. As I said, this looks like a Grafana issue after all.

**Comment by steverweber** [comment]
was traced down to an issue in angular.js..
https://github.com/grafana/grafana/issues/4533
