### ISSUE TITLE
influxdb collectd typesdb for ceph_rate working incorrectly

### ISSUE THREAD

**Issue by Jameznz** [influxdata/influxdb#5729]
Using collectd 5.5 network plugin to send ceph stats to influxdb 0.9.6.1, I have a problem in the way that the ceph_rate statistics are recorded.

I have set up influxdb to use the correct collectd types.db file that contains:

> ...
> ceph_bytes              value:GAUGE:U:U
> ceph_latency            value:GAUGE:U:U
> ceph_rate               value:DERIVE:0:U
> ...

The ceph_bytes and ceph_latency statistics are correct, but any ceph_rate value seems to be a overall total rather than a counter for any point in time, in this case filestore ops. It doesn't matter what I change it to (GUAGE, DERIVE etc etc) or if I change the max from U to 100000, the numbers for the following are always in the millions rather than say for example, 100-1000 ops.

> SELECT mean("value") FROM "ceph_value" WHERE "type_instance" = 'Filestore.ops' AND "host" =~ /$Servers$/ AND "type" = 'ceph_rate' AND $timeFilter GROUP BY time($interval), "instance"

I am using grafana to graph the metrics which is where the above what taken from, but I am a at a bit of a loss on how to proceed.

**Comment by kamsz** [comment]
This is because collectd returns the total value from Ceph start (as Ceph JSON does). Trick is to use derivative transformation.

**Comment by Jameznz** [comment]
It seems to be the same for the Disk plugin when looking at disk_ops, with it set as the following in the types.db:

> disk_ops		read:DERIVE:0:U, write:DERIVE:0:U

What else can be done?
