### ISSUE TITLE
Query with math returns field with no name

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#5730]
Using math on a field returns a field with an empty name.  If this used used in a continuous query or select into, it the points can't be inserted and causes some of the issues seen in #5697.

To repro:

```
> select value from cpu
name: cpu
---------
time			value
1455686412499134533	1
1455686413602752226	2
1455686415066866003	3
```

```
> select value * 10 from cpu
name: cpu
---------
time
1455686412499134533	10
1455686413602752226	20
1455686415066866003	30
```

Notice the second example is missing a `value` column header.

Selecting multiple columns doesn't fix it.
```
> select value * 10, value * 2 from cpu
name: cpu
---------
time
1455686412499134533	10	2
1455686413602752226	20	4
1455686415066866003	30	6
```

Using an `as` alias does work though:
```
> select value * 10 as scaled from cpu
name: cpu
---------
time			scaled
1455686412499134533	10
1455686413602752226	20
1455686415066866003	30
```

**Comment by jwilder** [comment]
@jsternberg

**Comment by jsternberg** [comment]
I found where the error is coming from. What should the column name be where there are multiple fields in the binary expression?

**Comment by jwilder** [comment]
For something like?

```
select user / total from cpu
```

Maybe concatenate the fields w/ `_`?  So that query would return `user_total`.

**Comment by jsternberg** [comment]
Sure! Should we remove duplicates? If we have `SELECT (user + total) / total FROM cpu` should it be `user_total_total`, `total_user`, or maybe `user_total`?

**Comment by jwilder** [comment]
I would probably go with `user_total_total` or `user_total` since they are in the order that they were defined in the query.  No strong opinion though.

**Comment by jsternberg** [comment]
I'll go with `user_total_total` for now since the implementation is much easier.
