### ISSUE TITLE
An alternative for clustering influxdb

### ISSUE THREAD

**Issue by dengliu** [influxdata/influxdb#5731]
@pauldix @toddboom 
I am considering an alternative that makes influxdb a distributed system.
The basic idea is to use influxdb as a embedded db running on each individual node (w/o inter-communication between influxdb nodes)
In the meantime, create a cluster layer that manage the shard placement, topology change (i.e. expanding/shrinking cluster). And a coordinator layer to proxy write/read traffic to the corresponding influxdb node. 

A very naive approach for distributing data points across shard is to hash the "db name +  measurement name" and map it to a shard. Or hash "db name + measurement + labels".

The later hash approach "db name + measurement + labels" seems to be able to yield better balance but it may results in cardinalities of the same measurement be placed into two different shard. In a query that needs a combined results of two cadinalities that come from two different shard. Coordinator will need to aggregate the results before return. 

Would you like to through some lights on this design?
In the meantime, I would like to learn your existing design of distributing measurements across shards?
Thank you!

Dennis Liu

**Comment by jsternberg** [comment]
Hello @dengliu,

We generally try to keep the issue tracker related to specific features or bugs with InfluxDB. Usability questions should be directed to the [mailing list](https://groups.google.com/forum/#!forum/influxdb).

Thank you.
