### ISSUE TITLE
[0.10.1]Influx only display entries in past

### ISSUE THREAD

**Issue by The-Nik** [influxdata/influxdb#5739]
Hi,

I build and installed influxdb on my raspberry pi 2 model B. Everything works fine. I fill the database with the python client v2.1.0

Oddly enough, if I send a query like "SELECT * FROM myMeasurement", I only get the entries of the past. If I saved entries where the time value is in future (UTC), they aren't displayed until I arrived in "reallife" at this special time. I tried the HTTP API, the python client and the CLI.

Is there any hidden setting which I didn't detect yet?

Thanks, Niklas

**Comment by rossmcdonald** [comment]
@The-Nik If you don't specify an time upper-bound on a query, then I believe it defaults to `now()`. Do you see the same issue if you explicitly set the upper bound on time? For example:

```
select * from mymeasurement where time < now() + 1w and time > now() - 1w
```

**Comment by The-Nik** [comment]
@rossmcdonald 

select * from mymeasurement where time < now() + 1w

works for me :) Thank you.

- Niklas
