### ISSUE TITLE
[0.11 / master] Querying against a nonexistent field results in an iterator type error

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#5740]
Sample query is `SELECT writeError / req FROM _internal.."write" WHERE time > now() - 15s` against an InfluxDB instance that has never recorded a write error.

Master as of 7479584afd856ca45768c36efeffe781b1e29d57:

```
$ curl -G http://localhost:8086/query --data-urlencode 'q=SELECT writeError / req FROM _internal.."write" WHERE time > now() - 15s'
{"results":[{"error":"error constructing iterator for field 'writeError / req': type mismatch, expected lhs to be FloatIterator, got *influxql.integerChanIterator"}]}
```

0.10.0 handled this much more gracefully by returning null for that column:

```
$ curl -G http://192.168.1.240:8086/query --data-urlencode 'q=SELECT writeError / req FROM _internal.."write" WHERE time > now() - 15s'
{"results":[{"series":[{"name":"write","columns":["time",""],"values":[["2016-02-18T17:18:30Z",null],["2016-02-18T17:18:32Z",null]]}]}]}
```

**Comment by jsternberg** [comment]
@mark-rushakoff is `writeError` the field that's missing or is it an integer? What about `req`? I think this may be a bug with mixed integer/float math.

**Comment by mark-rushakoff** [comment]
@jsternberg Yes, `writeError` is the field that is missing (i.e. has never been written due to never hitting [this line](https://github.com/influxdata/influxdb/blob/e3b4b71c13db844686eb7092dec8acccf266681a/cluster/points_writer.go#L369)). `req` is present and an integer.

There might be a separate issue that the statMaps should be initialized with an explicit zero for these stats that don't exist until they get incremented. Not sure what other implications that would have.
