### ISSUE TITLE
Searching for first/last time values

### ISSUE THREAD

**Issue by deeplook** [influxdata/influxdb#5747]
I don't see a way to define and execute a query that returns the first and last timestamp for which there is some data? I know there are the functions first(:fieldname) and last(:fieldname), but these will return the data values and not their respective timestamps. But I want to determine the time span during which a device produced some data.

**Comment by jwilder** [comment]
You could use `limit 1` queries and order by time `asc` and `desc`.

```
select value from cpu order by time asc limit 1
select value from cpu order by time desc limit 1
```
