### ISSUE TITLE
bind IP and IP presented to cluster should be separately configured

### ISSUE THREAD

**Issue by XANi** [influxdata/influxdb#5752]
Or: it should be possible to send "10.100.100.1" as host IP but still bind to "0.0.0.0"

Especially for http bind-address (altho I dont understand why it have to be binded to certain IP when setting up clustering)

Problem arises when you have box with more than one IP for example one used for management (ssh, downloading updates etc) and other is dedicated and isolated network just for influxdb traffic.

for example on our production boxes it looks like that:

    6: bond0.300@bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
        link/ether 00:00:00:00:33:f0 brd ff:ff:ff:ff:ff:ff
        inet 10.100.100.1/24 brd 10.100.100.255 scope global bond0.300
    7: bond0.500@bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
        link/ether 00:00:00:00:33:f0 brd ff:ff:ff:ff:ff:ff
        inet 172.16.100.31/24 brd 172.16.100.255 scope global bond0.500

bond0.300 is between influxdb servers and data sources while bond0.500 is management vlan

so if I set up bind-address to 10.100.100.1 management interface stops working and vice versa

Other DBs solved it by splitting, for example elasticsearch have `bind_host` and `publish_host` (and 3rd one to set both at same time) options to distinguish between what it uses for bind and what it announces to other hosts.

Another reason:

    # influx
    Failed to connect to http://localhost:8086
    Please check your connection settings and ensure 'influxd' is running.

**Comment by rossmcdonald** [comment]
I believe this may have been fixed already in master with https://github.com/influxdata/influxdb/pull/5706

**Comment by jwilder** [comment]
Fixed via #5706.  You'll want to set the `hostname` option in you config.  This change is only in current master.
