### ISSUE TITLE
[0.10.0] Backfill setting time to 0

### ISSUE THREAD

**Issue by vopnijam** [influxdata/influxdb#5755]
#5715 When running the following backfill:

```
    SELECT
      FIRST(val) AS open,
      MAX(val) AS high,
      MIN(val) AS low,
      LAST(val) AS close,
      LAST(val) AS val,
      SUM(vol) AS vol
    INTO "prices_52w"
    FROM "prices_backfill"
    WHERE time >= '2000-01-01'
    GROUP BY time(52w), api, code
```

the time column is being set to 0. 

Using influxdb 0.10.0

**Comment by jsternberg** [comment]
I cannot reproduce this and it appears to have happened on a very old version of the database. If you still have issues with this on a more recent version of the database, please open a new issue and we will address it as soon as possible.
