### ISSUE TITLE
something like graphite's maximumAbove

### ISSUE THREAD

**Issue by cxreg** [influxdata/influxdb#5760]
I apologize if this is already possible but I haven't found a way to do it.  If I select a large number of series using a multi-key GROUP BY, I may only want to see series in which one of the sampled datapoints exceeds a threshold.  I am able to do this in Graphite by using the maximumAbove function.

One way to support this would be to allow aggregate functions in the WHERE clause, like "WHERE max(field) > 100"

**Comment by cxreg** [comment]
This looks maybe related to https://github.com/influxdata/influxdb/issues/1819

**Comment by cxreg** [comment]
and/or https://github.com/influxdata/influxdb/issues/5266

**Comment by nakagawa-atsushi** [comment]
Graphite's `maximumAbove()`, if written like SQL would be more like a nested GROUP BY HAVING inside an outer WHERE clause, or a query involving two steps.

i.e.

```sql
CREATE TEMPORARY TABLE plot AS
SELECT time_interval, series_name, value
FROM data
WHERE time_filter
GROUP BY time_interval, series_name;

SELECT *
FROM plot
WHERE series_name IN (
    SELECT series_name
    FROM plot
    GROUP BY series_name
    HAVING max(value) > 100
)
```

**Comment by mathieulongtin** [comment]
+1. I really miss this from Graphite.
