### ISSUE TITLE
[master] change in influx UI behaviour with respect to GROUP BY tags

### ISSUE THREAD

**Issue by jonseymour** [influxdata/influxdb#5770]
Prior to the integration of the new query engine (e.g. on v0.10.0) influx would remove the tags specified in the GROUP BY spec from columns displayed for the result set in the UI.

After integration of the new query engine, the tags are included in the columns of the result set displayed by the UI. 

Is this an intended change or an oversight? Personally, I preferred the previous behaviour.

/cc @benbjohnson

**Comment by jonseymour** [comment]
Old behaviour:

![Old behaviour](https://dl.dropboxusercontent.com/content_link/YxiDE27YPsWkjg1p8qghWs0V1FKTPFAHAYdC526WbBV8Tj1cCzUDI17ZnEw0qiUi/file)

Current behaviour

![Current behaviour]
(https://dl.dropboxusercontent.com/content_link/ri8I0GKLNuWRQDHcUNAgSJCZMri61yMGstwIiWfm9pG8pBOntqwxi39ZRXqSs46g/file)

**Comment by jsternberg** [comment]
I believe this is intended. If you group by the host, you would presumably want to know the host.

**Comment by benbjohnson** [comment]
@jonseymour That change was not intended. We removed some code that deduplicated fields (e.g. `SELECT value, value FROM cpu` used to return `value` and now it returns `value`, `value`) and I believe this filtering was mixed in with that. We should return this to the previous behavior. The data is already returned in the result grouping.
