### ISSUE TITLE
Compressing queries result

### ISSUE THREAD

**Issue by matwey** [influxdata/influxdb#5779]
Hello,

InfluxDB uses HTTP to provide results of queries. It would be great if InfluxDB supported ```Accept-Encoding: gzip, deflate``` as described in HTTP protocol standard.
I think this feature may be optional for use-cases where output bandwidth has priority over server CPU usage.

**Comment by sbouchex** [comment]
gzip is already supported as it is written in the response headers...

**Comment by matwey** [comment]
Hm, not in my headers. Thanks for response, maybe I need to find out how to enable it.

**Comment by sbouchex** [comment]
In direct or proxied modes, both are gzipped (of course, with the latest versions of influxdb and grafana)

**Comment by jsternberg** [comment]
I'm closing this since gzip is already supported. Be sure to include `Accept-Encoding: gzip` in your request to use this feature.
