### ISSUE TITLE
DROP RETENTION POLICY "rp_name" is missing the ON "db_name"

### ISSUE THREAD

**Issue by sbouchex** [influxdata/influxdb#5780]
When using the web gui to drop a retention policy, the template is invalid, it's missing the ON "db_name"

We should get : 
DROP RETENTION POLICY "rp_name" ON "db_name"

**Comment by rossmcdonald** [comment]
It looks like this has already been added with [this](https://github.com/influxdata/influxdb/commit/f0ce949dee64fecd9f1aa9ccd9114611747fab1f) commit, though I'm not sure why it's not updated in the UI.

@gunnaraasen Do you know what the problem could be here? Does the static filesystem need to be recreated?

**Comment by gunnaraasen** [comment]
Yeah, it looks like the admin assets were not regenerated after that change was made.

https://github.com/influxdata/influxdb/pull/5710 adds support to rebuild the static filesystem with `go generate` which we should enable in [the build script](https://github.com/influxdata/influxdb/blob/master/build.py#L130). Until then, `go generate` needs to be manually committed every time there's an update to the admin UI.

**Comment by jsternberg** [comment]
It looks like this was implemented and it works in 0.13.
