### ISSUE TITLE
[0.10]  Each node returns different 'show series' result.

### ISSUE THREAD

**Issue by fayizk1** [influxdata/influxdb#5781]
I have a 3 node cluster and created a db with replication factor 3, but when I execute 'SHOW SERIES', each node returns different result.

More details.

OS: CentOS release 6.7 (Final)
Version: 0.10
Binary source: https://s3.amazonaws.com/influxdb/influxdb-0.10.1-1.x86_64.rpm

```
[root@metric1 ~]# influx -host metric1 -database graphitedb -execute 'show series' |grep "name:"|wc -l
543610
[root@metric2 ~]# influx -host metric2 -database graphitedb -execute 'show series' |grep "name:"|wc -l
570914
[root@metric3 ~]# influx -host metric3 -database graphitedb -execute 'show series' |grep "name:"|wc -l
526849

> show retention policies on graphitedb ;
name		duration	replicaN	default
default		0		3		false
graphite	0		3		true

>
```

**Comment by e-dard** [comment]
@fayizk1 this is a known issue #5580 and is being actively worked on for the `0.11` release.

**Comment by fayizk1** [comment]
Thanks @e-dard .

Closing as this is duplicate of #5580.
