### ISSUE TITLE
[0.10.0] ERR: write message type: use of closed network connection

### ISSUE THREAD

**Issue by wgrcunha** [influxdata/influxdb#5783]
Hello,

I have a cluster with 3 servers and everything working fine, i added a new server and when i try to do queries on that server i receive this error:

SHOW TAG KEYS FROM DATABASE."default".MEASUREMENT

ERR: write message type: use of closed network connection

The command: show measurements works fine.

The version is the 0.10 stable.

Thanks

**Comment by zstyblik** [comment]
@wgrcunha, please, give a look to https://github.com/influxdata/influxdb/issues/5538, although it's lengthy. What's the output of `SHOW SERVERS`? Are all ports necessary for clustering reachable/available/exposed, eg. `:8088`, `:8091`?

**Comment by wgrcunha** [comment]
Hi @zstyblik i removed the server from the cluster, i will create another cluster and try to simulate the same error and back here. Thanks

**Comment by lqx302** [comment]
influxdb 0.10.3 
clutering node number is 4,all node : Server returned error: write message type: use of closed network connection 
![image](https://cloud.githubusercontent.com/assets/9473278/13912324/c25b950e-ef76-11e5-8bb8-ea9d0795d95a.png)
![image](https://cloud.githubusercontent.com/assets/9473278/13912337/e2b69682-ef76-11e5-837b-04c0eb9bb41a.png)

**Comment by mark-rushakoff** [comment]
Closing this as we no longer support the 0.10 releases.
