### ISSUE TITLE
Last is returning only single value as result.

### ISSUE THREAD

**Issue by goyalr41** [influxdata/influxdb#5796]
As per InfluxDB documentation a point is defined only by its **measurement, tag set, and timestamp**.

I wrote multiple points as:
```bash
curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'Revenue_daily,firstTag=yes price=6666 
Revenue_daily,secondTag=no price=7777'
```

The data in influx gets written with same timestamp as expected:
```bash
> SELECT * from Revenue_daily
name: Revenue_daily
-------------------
time			firstTag	price	secondTag
1456229169944624586	yes		6666	
1456229169944624586			7777	no
```

Now when performing "last" it is only returning one result, **shouldn't it be returning both the results as they have same timestamp**? And shouldn't this be valid for all the functions? 

```bash
> SELECT last(price) from Revenue_daily
name: Revenue_daily
-------------------
time	last
0	    7777
```

**Comment by jsternberg** [comment]
What version are you running against?

The `last()` call should only return one result. If you use `GROUP BY host`, it will return one point per host. So `SELECT last(price) from Revenue_daily` will return only one value.

@beckettsean can we clarify the documentation for `last()` to say that it will only return one point if timestamps are the same? We also don't guarantee any specific ordering in these circumstances.

**Comment by goyalr41** [comment]
The version is 0.10.1.
Ok the documentation doesn't explicitly mentioned that, if the timestamps are same I thought all the values will be returned irrespective of using `GROUP BY`

**Comment by beckettsean** [comment]
@rkuchan can you please make a docs issue to clarify what LAST() returns if there are more than one matching points with the same timestamp?

@jsternberg for all docs issues, @rkuchan is the person to at-mention, now, thanks!

**Comment by jsternberg** [comment]
@goyalr41 if you want to include things like tags inside of a column you can do something like this:

```
SELECT last(value), firstTag FROM cpu
```

I think you can also use a wildcard and it might do what you want.

```
SELECT last(value), * FROM cpu
```

I'm going to close this since the docs were updated and I think we've answered your question. If you feel that there's something we've missed, please reopen. Thanks for your contribution!
