### ISSUE TITLE
Optimising Median Aggregation

### ISSUE THREAD

**Issue by seiflotfy** [influxdata/influxdb#5813]
Looking at the code, a normal floatReduceSliceIterator is being used for median aggregation, which is passing over to floatMedianReduceSlice.
It ends up [sorting](https://github.com/influxdata/influxdb/blob/50753de03285ec5b3cf38d4ae532971d73c8e583/influxql/call_iterator.go#L362) to get the median. Best case O(n) complexity. 
A better complexity can be achieved for calculating the median and get it down to O (log n):
- Using a AVL or b+ tree you just insert and its self balancing.
- In both cases once balanced the root will be the median (for odd number of elements) or  the root or the root + right|left / 2 (for even number of elements).
- This could also work for both continuous queries with window_size == unlimited or limited. :D

For a continous query you would never need to resort, all you do is:
- keep a second queue based on the window size and keep track of what was taken out and what inserted.
  So this way you can operate those adds and removes in the tree-struct,  no need to ever calculate. does this make sense?

If you like it i can start the surgery!

**Comment by e-dard** [comment]
Given `n` will often be small, it's really worth benchmarking an alternative approach to figure out if it's worth doing that way.

Go's `sort` package uses either Quicksort or ShellSort, so the average case is `O(n log n)`. To build the B-tree each element needs to be inserted, which is `O(log n)` each time, i.e., `O(n log n)`.

I guess for CQs though you're saying that the tree can be kept around, which makes sense as opposed to re-sorting.

I'm not that familiar with this bit of the code-base but sure someone will chip in with some thoughts. :smile:

**Comment by seiflotfy** [comment]
Yeah you have a point it might not be worth it for one time queries.
But defiantly for CQ. Will look into it now

**Comment by e-dard** [comment]
Closing this, but if you revisit it @seiflotfy let us know!
