### ISSUE TITLE
[0.10] can't run CQs with the same name but scoped to different databases

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#5814]
From mailing list: https://groups.google.com/d/msgid/influxdb/7b74ce6c-d841-43f5-aeca-39fb860cdeec%40googlegroups.com

If multiple CQs exist with the same name but on different databases, only one CQ is actually executed.

**Comment by jsternberg** [comment]
It looks like the map storing the last run doesn't include the database name, so the CQ name isn't scoped there.

Preparing a fix for this. Do we need to backport this and do a bugfix release for 0.10 or can this just go directly into master and wait for 0.11?

**Comment by beckettsean** [comment]
@jsternberg this is a pretty minor issue with a simple workaround, so I see no need to backport to 0.10. Thanks!
