### ISSUE TITLE
Database hang up after simple query

### ISSUE THREAD

**Issue by pga23** [influxdata/influxdb#5824]
I use InfluxDB database with 18 different measurements.
Almost no data (below 100k data records total).
Only simple telemetry data (temperature, humidity, pulse etc.) - just
a few columns plus one 16-char tag in every measurement.

Simple query SELECT * FROM /.*/ LIMIT 1 made by using web UI
hang up whole database in about 2 minutes (every time).
During this time there is no way to make another query and CPU
load and memory usage is very high.

Additionally getting example all data (just 6.5k records) from single measurement
takes about 5 sec. It is a little bit too slow - much slower than my old MySQL...

I haven't noticed this kind of problems in previous versions of InfluxDB.

I use Python 3.4, innfluxdb 2.12.0 Python library with InfluxDB 0.10.1 with TSM on the single node
development server. It is single core, 2GB RAM virtual machine with installed 64-bit Ubuntu 14.04.3.
Host machine has AMD FX-6100 six core CPU and 24GB RAM.

**Comment by cxreg** [comment]
is this the same issue as https://github.com/influxdata/influxdb/issues/5553 ?

**Comment by pga23** [comment]
It looks related.

When RAM of my machine was 2GB, the influxdb process has been killed in about 2 min.
When I increased RAM into 8GB, the process hasn't killed but the system was
overloaded with 95% of RAM usage (with basically empty database).

**Comment by jackzampolin** [comment]
Closing duplicate issue in favor of #5553
