### ISSUE TITLE
InfluxDB unable to write data (localhost)  with 25 tags and 300 fields.

### ISSUE THREAD

**Issue by deepujain** [influxdata/influxdb#5826]
One day of data: 74 files, 1000 points in each file,  Each point has 25 tags and 300 fields

I was able to ingest 1 file correctly without any syntax errors.
However write of all files started to throw  {"error":"timeout"}

InfluxD : 
After a while it started to go crazy
Logs: http://pastebin.com/b2wJwFHT

I was planning to load 30 days of data. It did with speed and no errors on Druid + Imply, wanted to compare that with InfluxDB + Grafana. All of this installation is on local machine (Mac, with 24 GB RAM)

**Comment by jonseymour** [comment]
How were you loading the data?  How many points in each batch? How many batches in parallel?

**Comment by jonseymour** [comment]
Ah, I see you were using curl. So, one curl command per file? How many curl commands in parallel?

**Comment by deepujain** [comment]
All in sequence in a for loop. Am not testing write part now. I can afford
that to be slow but I want correct ingestion and fast query

**Comment by deepujain** [comment]
In addition that above question, how can i recover. InfluxDB wont start now.

filestore]2016/02/24 20:00:06 /Users/dvasthimal/.influxdb/data/mydb/default/28/000000003-000000002.tsm (#2) opened in 123.004398ms
[filestore]2016/02/24 20:00:14 /Users/dvasthimal/.influxdb/data/mydb/default/28/000000002-000000002.tsm (#0) opened in 8.452389905s
[filestore]2016/02/24 20:00:15 /Users/dvasthimal/.influxdb/data/mydb/default/28/000000003-000000001.tsm (#1) opened in 8.57616921s
[cacheloader] 2016/02/24 20:00:15 reading file /Users/dvasthimal/.influxdb/wal/mydb/default/28/_00025.wal, size 29333172
[cacheloader] 2016/02/24 20:00:17 reading file /Users/dvasthimal/.influxdb/wal/mydb/default/28/_00026.wal, size 22579152
[cacheloader] 2016/02/24 20:00:18 reading file /Users/dvasthimal/.influxdb/wal/mydb/default/28/_00027.wal, size 14073637.

.
...
...

**Comment by jonseymour** [comment]
How big is each file? 300 fields per point seems quite high and it possible this might be a factor. How many of these are numeric, how many strings?

**Comment by deepujain** [comment]
All fields (metrics) are numeric. (doubles mostly). dimensions (tags) are strings.

One day of data: 74 files, 1000 points in each file, Each point has 25 tags and 300 fields

**Comment by jonseymour** [comment]
Could you post the output of:

    find '/Users/dvasthimal/.influxdb/' -ls 

I am interested to see the total size of all the .wal files.

There is a possibility that you have run out of RAM. 

I'll leave it for the influx guys to advise on a recovery approach.

**Comment by jonseymour** [comment]
How big - in bytes - is each file?

**Comment by deepujain** [comment]
10MB

**Comment by jonseymour** [comment]
How many files are processed before you start seeing errors?

**Comment by deepujain** [comment]
20

**Comment by jonseymour** [comment]
Ok, here is a guess at what the problem is and perhaps a workaround, depending on whether you are in a position to rewrite the point tags.

This line of code:

https://github.com/influxdata/influxdb/blob/master/models/points.go#L331

use an insertion sort to sort tags. If your tags are not in go sort order, then there is a potentially O(n^2) sort for each point. If the tags were in go sort order then the cost of this sort will be ~ O(n). For n = 25, the difference between O(n^2) and O(n) is quite a lot.

(I am not 100% sure about this diagnosis - it is  possible that something prior to write path in this code normally sorts the tag in go sort order and so this isn't a factor, but it is worth testing if you are in position to do so).

**Comment by deepujain** [comment]
What you mean by go sort ?
Do you want each row (point) to be sorted by multiple tags ? How can I do
that ?

**Comment by jonseymour** [comment]
Actually, it isn't going to help anyway because of the way influx makes points.

Are you in a position to build your own version of influx, or are you using a packaged version?

**Comment by deepujain** [comment]
O/p of the command:
find '/Users/dvasthimal/.influxdb/' -ls 

http://pastebin.com/QL6ZcKnw

**Comment by deepujain** [comment]
I am using packaged version.

**Comment by deepujain** [comment]
What is the maximum tested data ? # of tags, # of  fields in a given measurement ?

**Comment by jonseymour** [comment]
When you say it doesn't start, does it fail with an error message or do you kill it. How long do you wait? Can you paste the tail of the log file at the point the restart fails/is terminated? Is the system showing any evidence of high memory or CPU usage at the point the start fails/is terminated?

Are all the timestamps in the 74 files within one calendar day or do they refer to events from a wider time period?

I'll have to defer to the influx support team regarding what they consider to be a reasonable number of tags and fields.

**Comment by jonseymour** [comment]
@deepujain The O(n^2) issues I were worried about with point construction don't actually exist, verified both by closer inspection of the code and some actual unit tests. Still 300 fields is a lot of fields, so it could still be a factor.

**Comment by jonseymour** [comment]
The number of wal logs seems quite high. How much disk space do you have free in your home directory?

**Comment by jonseymour** [comment]
@deepujain According to this line:

https://github.com/influxdata/influxdb/blob/v0.10.1/tsdb/shard.go#L490-L492

influx only supports up to 255 fields per point. Perhaps violating this restriction is a contributing factor to your issues?

**Comment by deepujain** [comment]
I reduced number of fields to ~200. This times 95% of files got ingested. Rest has same error

Client Side: {"error":"timeout"}

Server Side:
[http] 2016/02/25 07:41:05 ::1 - - [25/Feb/2016:07:41:04 -0800] POST /write?db=ppw HTTP/1.1 204 0 - curl/7.43.0 2dfdca80-dbd6-11e5-805a-000000000000 1.394094614s
[http] 2016/02/25 07:41:11 ::1 - - [25/Feb/2016:07:41:05 -0800] POST /write?db=ppw HTTP/1.1 500 20 - curl/7.43.0 2ed6337a-dbd6-11e5-805b-000000000000 5.132936465s
[http] 2016/02/25 07:41:16 ::1 - - [25/Feb/2016:07:41:11 -0800] POST /write?db=ppw HTTP/1.1 500 20 - curl/7.43.0 31ea6c52-dbd6-11e5-805c-000000000000 5.171391369s
[http] 2016/02/25 07:41:20 ::1 - - [25/Feb/2016:07:41:16 -0800] POST /write?db=ppw HTTP/1.1 204 0 - curl/7.43.0 3506b06d-dbd6-11e5-805d-000000000000 4.353095492s


Is there a limit on number of fields (metrics) and what is tsm / b1 / bz1 ?
This is only 1 day of data. What

**Comment by deepujain** [comment]
Influx QL is dead slow and disk starts spinning like crazy.

> select * from ppw limit 10

Never saw the output

**Comment by deepujain** [comment]
Better question:

I have a time series db that is updated once every day. It has around 30 dimensions (used as filters, that will match to tags) and 175 to 200 metrics (to perform aggregate functions and this will map to fields). 

Each day around 100 to 150 files each with 1000 points will be ingested.

Ingestion time can take few minutes, but query time has to be order of few seconds.

I was able to do this with Druid (backend) and Imply (front end) but I like Grafana better, hence what to try out influxDB
Can influx DB support this kind of data ?

**Comment by jackzampolin** [comment]
With 25 tags I would be surprised if your [series cardinality](https://docs.influxdata.com/influxdb/v0.10/concepts/glossary/#series-cardinality) was under 10 million. Influx should be able to handle this data given proper schema design.

**Comment by deepujain** [comment]
What do you mean by proper schema design ? I will have one measurement with
25 tags and rest 200 as fields ?

Please share details on proper schema design

**Comment by deepujain** [comment]
Any suggestions here ? This issue was closed
