### ISSUE TITLE
How to store the timestamp in influxdb ?

### ISSUE THREAD

**Issue by rfyiamcool** [influxdata/influxdb#5828]
I am very curious, How to store the timestamp in influxdb ? 

I know influxdb' rocksdb or leveldb engine all is  KV database . only save  key value .

**Comment by jwilder** [comment]
I'm not exactly sure I understand your question, but I'll point you to some reference docs.  There are several ways to write data to InfluxDB.  I would suggest taking a look at the [write protocols](https://docs.influxdata.com/influxdb/v0.10/write_protocols/) we support.

If you are asking about how the data is physically stored on disk, there is a [blog post](https://docs.influxdata.com/influxdb/v0.10/concepts/storage_engine/) describing the TSM engine, some lower level [design docs](https://github.com/influxdata/influxdb/blob/master/tsdb/engine/tsm1/DESIGN.md) as well as documentation in the [code](https://github.com/influxdata/influxdb/tree/master/tsdb/engine/tsm1). RocksDB and LevelDB were used in older versions of InfluxDB, but are not used currently any more.
