### ISSUE TITLE
ERROR: {"error":"write failed: field overflow"}

### ISSUE THREAD

**Issue by are007** [influxdata/influxdb#5831]
Hello,

after enabling mysql plugin in telegraf i've got in logs:

Feb 25 15:47:10 influxdb telegraf[21898]: 2016/02/25 15:47:10 Gathered metrics, (10s interval), from 9 inputs in 36.230172ms
Feb 25 15:47:10 influxdb telegraf[21898]: 2016/02/25 15:47:10 ERROR: {"error":"write failed: field overflow"}
Feb 25 15:47:10 influxdb telegraf[21898]: 2016/02/25 15:47:10 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster

telegraf version: 0.10.4.1-1
influxdb versionb: 0.10.1-1 (stand alone server)

telegraf plugin configuration:
[plugins]
[[plugins.mysql]]
  servers = [
   "telegraf_mon:XXXXXXXXXXXXX@tcp(mysql02:3306)/?tls=false" ]

**Comment by jonseymour** [comment]
It looks like you are tripping this condition:

https://github.com/influxdata/influxdb/blob/v0.10.1/tsdb/shard.go#L490-L492

Apparently influx only supports 255 fields per point. Does that situation apply to you?

**Comment by jonseymour** [comment]
It looks like this condition only applies to b1 and bz1 shards. If you are using b1 and bz1 shards, then you may want investigate migrating those shards to the tsm1 storage engine.

**Comment by jwilder** [comment]
Yes, that is a limitation on `b1` and `bz1` shards.  Looks like that restriction is still in place for `0.11`, but it's not necessary with `tsm` anymore and should be removed.

**Comment by are007** [comment]
Yes, shard was bz1, forgot to change after upgrade. Thanks.

**Comment by morganics** [comment]
It would be useful to have a more helpful error message - rather than field overflow, perhaps a mention of the limitation!
