### ISSUE TITLE
Proposal: Query Logging

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#5838]
Query logging is an important, missing diagnostic feature of InfluxDB. There have been some internal discussions about what would be important to have, but I wanted to open a public-facing issue to solicit more feedback from the community.

By _query logging_, we mean having first-class InfluxDB support for recording information about queries as the queries are executed.

Query logging would enable InfluxDB users and operators to:
- Benchmark and profile query performance
- Easily identify queries that cause server panics, even if many queries are running concurrently
### Considerations

Depending on system load, logging queries may have a non-negligible performance impact. There must be a configuration option to disable query logging.

The query log probably belongs in the `_internal` database, although there may be valid arguments to put it in its own database. Either way, the default retention policy for the query log should be very short by default, perhaps one hour.

In the event of a system crash, users should be able to search for queries that were active at that time and never completed.
#### Information to be logged with a query
- Must have:
  - Text content of query
  - Whether query was completed
  - If query was completed, the duration of execution
- Nice to have:
  - HTTP request GUID
  - Username of requester, if supplied
  - Whether query was a select statement, and if so:
    - Database targeted
    - Number of points scanned while executing query
    - Number of shards scanned while executing query
    - Number of points returned
### Implementation details

For the purposes of this proposal, let's keep the discussion focused on the _what_, not the _how_. 

/cc @pauldix @jwilder @benbjohnson @beckettsean @gunnaraasen @mjdesa @jackzampolin

**Comment by jonseymour** [comment]
Excellent idea!

I am assuming that this log ends up (or could end up) in a timeseries

Features I'd like to see:

- the text of the query with the time qualifications removed (tag)
- a hash of that text for use as a grouping criteria (tag)
- the time range of the query as separate (fields)
- an order of magnitude time range classifier (e.g. second, minute, hour, day, week, month) to allow grouping of queries by time range (tag)
- count of active queries and writes when query is received (field)
- the time spent executing the query (field)

I can explain the rationale for each if it isn't clear.

**Comment by toni-moreno** [comment]
+1

**Comment by jackzampolin** [comment]
+1

**Comment by zstyblik** [comment]
http://doodle.com/poll/eu8gphyn5s83qb53

**Comment by russorat** [comment]
we have no plans to implement this RFC in the 1.x line.
