### ISSUE TITLE
Selecting multiple last() values returns incorrect data when one of them is null

### ISSUE THREAD

**Issue by phalenor** [influxdata/influxdb#5845]
Please observe the difference in results. It seems like when one value (min) is null, the result is the value of the one selected after it. Not quite sure how to explain it. This is with 0.9.6.1. I don't want to upgrade to 0.10.x at the moment unless I know this is definitely fixed in a newer version.

```
SELECT last(uom) as uom, last(min) as min, last(warn) as warn FROM "check_nrpe" WHERE host_name = 'smith.ait.psu.edu' AND service_description= 'Memory' AND metric = 'MemUsed' AND nagios_host = 'smith.ait.psu.edu'
name: check_nrpe
----------------
time    uom     min     warn
0       %       90      90
```
```
SELECT last(uom) as uom, last(min) as min  FROM "check_nrpe" WHERE host_name = 'smith.ait.psu.edu' AND service_description= 'Memory' AND metric = 'MemUsed' AND nagios_host = 'smith.ait.psu.edu'
name: check_nrpe
----------------
time    uom     min
0       %
```

**Comment by phalenor** [comment]
Just updated to 0.10.1. This bug is still present.

**Comment by jsternberg** [comment]
This appears to be fixed in the new query engine that's going to be released in 0.11.

```
> create database mydb
> use mydb
Using database mydb
> insert cpu value=2 10
> insert cpu extra=3 20
> select last(value) as value, last(extra) as extra from cpu
name: cpu
---------
time    value   extra
0       2       3
```

Can you try it out from master?

**Comment by phalenor** [comment]
This is still a problem running  0.11.0~n1457424040:

```
> SELECT last(uom) as uom, last(min) as min, last(warn) as warn FROM "check_nrpe" where host_name = 'smith.ait.psu.edu' and service_description = 'Memory' and metric = 'MemUsed' 
name: check_nrpe
----------------
time    uom     min     warn
0       %       90      90

> SELECT last(uom) as uom, last(min) as min FROM "check_nrpe" where host_name = 'smith.ait.psu.edu' and service_description = 'Memory' and metric = 'MemUsed' 
name: check_nrpe
----------------
time    uom     min
0       %
```

To be clear, min is null in the database. The second command returns the expected results. It's when one of the field values is null that we have a problem.

**Comment by jsternberg** [comment]
Can you give me a way to reproduce the issue on a clean database along with the actual and expected outputs? I don't understand your current example. Also, are you using the bz1 or tsm engine for storing data?

**Comment by beckettsean** [comment]
@phalenor Given that this might be a formatting issue, let's not use the column format from the CLI. Can you provide output in JSON or CSV format so there is no ambiguity in the results? 

Also, can you provide an example write statement so we can get a feel for what data is in `uom`, `min`, and `warn`? Can you verify all three are numeric fields? Most functions are invalid on strings.

**Comment by phalenor** [comment]
I get the same behavior with bz1 and tsm1.

Here is the simplest example I could come up with:

```
> create database test
> use test
> insert cpu one=10,two=20
> select last(one), last(three), last(two) from cpu
name: cpu
---------
time    last    last    last
0       10      20      20
```

Here's the same thing in json:
```JSON
{"results":[{"series":[{"name":"cpu","columns":["time","last","last","last"],"values":[["1970-01-01T00:00:00Z",10,20,20]]}]}]}
```
I'll have to dig around for a clear write example. Basically, some points have null as a field value, and I need to know if something is null.

**Comment by beckettsean** [comment]
InfluxDB does not store null values, and it is not possible to query for them. It's possible to query for negative matching of anything, e.g. `WHERE foo != /.*/` but that's it. If there are no values to return the query response should be empty for that column. 

I confirm the repro case does show the issue with 0.10.1:

```
> insert cpu one=10,two=20
# correctly returns empty value for last(three):
> select last(three) as bar from cpu
name,time,bar
cpu,0,
> select last(one) as foo, last(two) as baz, last(three) as bar from cpu
name,time,foo,baz,bar
cpu,0,10,20,
# somehow copies the last(two) value as last(three)
> select last(one) as foo, last(three) as bar, last(two) as baz from cpu
name,time,foo,bar,baz
cpu,0,10,20,20
> 
```

**Comment by phalenor** [comment]
@beckettsean Right, I know null values aren't stored. For some series, there simply are no values for a particular field. I would just expect influxdb to return an empty column for those fields, and not give me the value for a different field.

**Comment by beckettsean** [comment]
Appears fixed in the most recent nightly:

```
Connected to http://localhost:8086 version 0.11.0~n1457424040
InfluxDB shell 0.11.0~n1457424040
> insert cpu one=10,two=20
> format csv
> select last(one), last(two), last(three) from cpu
name,time,last,last_1,last_2
cpu,0,10,20,
> select last(one), last(three), last(three) from cpu
name,time,last,last_1,last_2
cpu,0,10,,
> select last(one), last(three), last(two) from cpu
name,time,last,last_1,last_2
cpu,0,10,,20
> select * from cpu
name,time,one,two
cpu,1457467857852673989,10,20
> format column
> select last(one), last(three), last(two) from cpu
name: cpu
---------
time	last	last_1	last_2
0	10		20

> 

```

**Comment by phalenor** [comment]
@beckettsean Yeah, you're right. The RPM package apparently doesn't restart influxd on upgrade, so influxd was still 0.10.1. Ugh.

We should consider this resolved. Sorry for the confusion, everyone!

**Comment by jsternberg** [comment]
Glad we could resolve this for you!
