### ISSUE TITLE
Apparently multiple identically named measurements

### ISSUE THREAD

**Issue by pbooth** [influxdata/influxdb#5851]
Hello,

I am noticing an apparent issue in both 0.9.6.1 and in 0.10 influxdb instances.

When I connect to a DB and issue SHOW MEASUREMENTS then I see a list that appears to include a series multiple times:

    > use prism
    Using database prism
    > show measurements
    name: measurements
    ------------------
    name
**latency_micros**

     hom
    latency
    latency_micros
    latency_per_min
    ll
    ll_micros
    ma
    mal
    xfm

    >

The first appearance of latency_micros it appears highlighted in red.

These measuremenst were created by uploading a file that was created programatically soem time ago.

**Comment by pbooth** [comment]
So I can see that the cause of this "issue" was that I had uploaded data that contained escape sequences. I can't begin to guess what the correct behavior is in this scenario. As an English speaking NYC resident it's probably arrogant and ethnocentric to suggest that influxdb should only handle ascii.



-bash-4.1$ zcat  bamlx22cp.gz | tail
amps_latencies,instance=ampsimemain1,env=prod,src=HR_BAMLX22,sink=imegrp19 value=21.298000000000002 1451919796597114290
amps_latencies,instance=ampsimemain1,env=prod,src=HR_BAMLX22,sink=imegrp19 value=21.298000000000002 1451919796597114290
amps_latencies,instance=ampsimemain1,env=prod,src=HR_BAMLX22,sink=imegrp19 value=23.929 1451919796597184511

is actually:

-bash-4.1$ od -a aa
0000000 esc   [   0   1   ;   3   1   m esc   [   K   a   m   p   s   _
0000020   l   a   t   e   n   c   i   e   s esc   [   m esc   [   K   ,
0000040   i   n   s   t   a   n   c   e   =   a   m   p   s   i   m   e
0000060   m   a   i   n   1   ,   e   n   v   =   p   r   o   d   ,   s
0000100   r   c   = esc   [   0   1   ;   3   1   m esc   [   K   H   R
0000120   _   B   A   M   L   X   2   2 esc   [   m esc   [   K   ,   s
0000140   i   n   k   =   i   m   e   g   r   p   1   9  sp   v   a   l
0000160   u   e   =   2   1   .   2   9   8   0   0   0   0   0   0   0
0000200   0   0   0   0   2  sp   1   4   5   1   9   1   9   7   9   6
0000220   5   9   7   1   1   4   2   9   0  nl esc   [   0   1   ;   3
0000240   1   m esc   [   K   a   m   p   s   _   l   a   t   e   n   c
0000260   i   e   s esc   [   m esc   [   K   ,   i   n   s   t   a   n
0000300   c   e   =   a   m   p   s   i   m   e   m   a   i   n   1   ,
0000320   e   n   v   =   p   r   o   d   ,   s   r   c   = esc   [   0
0000340   1   ;   3   1   m esc   [   K   H   R   _   B   A   M   L   X
0000360   2   2 esc   [   m esc   [   K   ,   s   i   n   k   =   i   m
0000400   e   g   r   p   1   9  sp   v   a   l   u   e   =   2   1   .
0000420   2   9   8   0   0   0   0   0   0   0   0   0   0   0   2  sp
0000440   1   4   5   1   9   1   9   7   9   6   5   9   7   1   1   4
0000460   2   9   0  nl esc   [   0   1   ;   3   1   m esc   [   K   a
0000500   m   p   s   _   l   a   t   e   n   c   i   e   s esc   [   m
0000520 esc   [   K   ,   i   n   s   t   a   n   c   e   =   a   m   p
0000540   s   i   m   e   m   a   i   n   1   ,   e   n   v   =   p   r
0000560   o   d   ,   s   r   c   = esc   [   0   1   ;   3   1   m esc
0000600   [   K   H   R   _   B   A   M   L   X   2   2 esc   [   m esc
0000620   [   K   ,   s   i   n   k   =   i   m   e   g   r   p   1   9
0000640  sp   v   a   l   u   e   =   2   3   .   9   2   9  sp   1   4
0000660   5   1   9   1   9   7   9   6   5   9   7   1   8   4   5   1
0000700   1  nl esc   [   0   1   ;   3   1   m esc   [   K   a   m   p
0000720   s   _   l   a   t   e   n   c   i   e   s esc   [   m esc   [
0000740   K   ,   i   n   s   t   a   n   c   e   =   a   m   p   s   i
0000760   m   e   m   a   i   n   1   ,   e   n   v   =   p   r   o   d

**Comment by joelegasse** [comment]
@pbooth There are two active discussions around both restricting names and updating/improving the line protocol. Please join the discussion over at #6011 and #6037.
