### ISSUE TITLE
Variations in MEAN function accuracy

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#5852]
There are differences in the precision of MEAN function results on the exact same data set between 0.10.1 and the latest nightly build (0.11.0~n1456430217  /  c6f5aa038f7c17836081b49cdfff276daf93d65e ).

E.g. 

Using [NOAA sample data](https://s3-us-west-1.amazonaws.com/noaa.water.database.0.9/NOAA_data.txt)

v.0.10.1
select mean(pH) from h2o_pH 
6.993773758028575

v0.11.0~n1456430217  /  c6f5aa038f7c17836081b49cdfff276daf93d65e
select mean(pH) from h2o_pH
6.99377375802858

@jsternberg Any idea?

**Comment by jsternberg** [comment]
I'll put up a branch using the math in here: https://math.stackexchange.com/questions/106700/incremental-averageing

Maybe that will lead to less floating point imprecision.

**Comment by jsternberg** [comment]
Can you calculate what the real mean value is supposed to be with a calculator or by hand? Floating point imprecision makes it impossible for me to know if I'm getting closer or further from the target by modifying the floating point operations.

Potential tool to help reduce floating point accuracy problems: http://herbie.uwplse.org/demo/

Not sure how well it works, but it's worth a try.

**Comment by kostasb** [comment]
@jsternberg  

Mean value calculations:

sum of field values in h2o_pH:  106711
number of points in the measurement : 15258

15 decimal precision Mean value = 6,993773758028575

Using Python's Decimal type (high precision): 6.99377375802857503828136032097972929477691650390625

Looks like the calculation in v0.10.1 is closer to the real mean value.

**Comment by jsternberg** [comment]
@kostasb in order to prevent this from happening again, is there a reasonable test case that we can include to run into this situation? I would prefer if we didn't have to read the NOAA sample database file for running this test, but I don't know enough about the necessary required precision to ensure we don't have this regression again.

**Comment by kostasb** [comment]
@jsternberg We have a regression test case running against the latest build. Currently it uses the NOAA data set but we can also add more sample data sets to it.

**Comment by kostasb** [comment]
Integration test case passed as well.
