### ISSUE TITLE
[0.10.0rc1] panic in tsm1.Values.Deduplicate

### ISSUE THREAD

**Issue by fffw** [influxdata/influxdb#5857]
Not sure if it's fixed on newer version because it didn't recur after I upgraded to 0.10.1, but might worth to have a quick check. I didn't find relevant previous issue.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x7ffdc1]

goroutine 671991 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.Values.Deduplicate(0xc2c56ba000, 0x20054b, 0x20054b, 0x0, 0x0, 0x0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/encoding.go:207 +0xf1
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Cache).merged(0xc25f12e460, 0xc2422e2690, 0x2c, 0x0, 0x0, 0x0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cache.go:280 +0x6f5
github.com/influxdb/influxdb/tsdb/engine/tsm1.func·002(0x0, 0x0, 0x0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cache.go:216 +0x8a
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Cache).Values(0xc25f12e460, 0xc2422e2690, 0x2c, 0x0, 0x0, 0x0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cache.go:217 +0x178
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*tx).Cursor(0xc2595e7880, 0xc2186e3c50, 0x21, 0xc23d2fa260, 0x1, 0x1, 0xc213a0dac0, 0xc23d2fa201, 0x0, 0x0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:645 +0x147
github.com/influxdb/influxdb/tsdb.(*AggregateMapper).openMeasurement(0xc24b8ad950, 0xc20810fc00, 0x0, 0x0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/aggregate.go:690 +0x551
github.com/influxdb/influxdb/tsdb.(*AggregateMapper).Open(0xc24b8ad950, 0x0, 0x0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/aggregate.go:646 +0x6fb
github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).openMappers(0xc24cfc0100, 0x0, 0x0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/aggregate.go:205 +0x9b
github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).execute(0xc24cfc0100, 0xc2a24eb4a0, 0xc2a24eb3e0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/aggregate.go:70 +0x1ab
created by github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).Execute
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/aggregate.go:48 +0x64
```

**Comment by jonseymour** [comment]
@fffw I haven't seen a report with that exact symptom. Did it happen more than once?

I did some work on a thread safety fix (#5701) that might explain the root cause of this issue since there were circumstances where a values slice servicing a query could be subject to unsynchronized updates from the compactor. It is just possible that issue might have resulted in memory being returned to the heap while it was still being accessed by a query and that could cause a symptom like the one you have reported.

This fix is in master but isn't in 0.10.1 so there is a possibility that this issue  could occur again.

Having said that, though, I don't think I have seen this particular stack trace before, so it could be a different issue.

**Comment by fffw** [comment]
I've seen 3 occurrences before upgraded to 0.10.1, so it could possibly recur. Oh 0.10.1 hasn't come up for 24 hours so it's too early to say if it will recur. I'll comment once that happens.

```
2016/02/26 17:37:56
2016/02/27 00:19:32
2016/02/28 03:36:47
```

From logs, the panic always followed below CQ (I turned off HTTP log so I don't know if there're writes in between), so I'll not be surprised if it's a thread safety issue.

```
[query] 2016/02/26 17:37:56 SELECT count(service) AS requests, min(service) AS resp_min, mean(service) AS resp_mean, percentile(service, 95.000) AS resp_95_percent, max(service) AS resp_max INTO heroku."1_year"."1s_router" FROM heroku."default".router WHERE time >= '2016-02-26T22:17:19Z' AND time < '2016-02-26T22:17:20Z' GROUP BY time(1s), app, status fill(none)
```

**Comment by jonseymour** [comment]
Was there any evidence of TSM compaction activity at around the time of the crash? e.g. a tsm.tmp in a subdirectory of data/ ?

**Comment by fffw** [comment]
Thanks @jonseymour ! No such entry shown in the log file. I'll check the .tsm.tmp files if it crashes the next time.

**Comment by jonseymour** [comment]
@fffw - would you happen to have the full stack trace of one of these events available? If so, I can probably tell from that whether the issue I was concerned about was a factor. Also, if you are in a position to build your own version of influx, I am happy to back port the thread safety fix onto the 0.10.1 maintenance branch, if you like.

**Comment by fffw** [comment]
@jonseymour Sent full trace to your gmail. Unfortunately I don't have a chance to build manually ATM.

**Comment by jonseymour** [comment]
@fffw - the existence of this stack trace is highly consistence with an occurrence of the thread safety issue I fixed with #5701. I am happy to back port the fix onto 0.10.1 so that if influxdata decide to push a 0.10.2 it can go in there. If you can tell me what platform you are running on, I am happy to build a binary influxd for that platform. Of course, this would be completely unsupported in anything other than a buy me a beer next time you are in Sydney sense :-)

```
goroutine 612868 [runnable]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Values).Less(0xc23c481be0, 0x8204, 0x84f9, 0x8d00)
        <autogenerated>:19
sort.doPivot(0x7f0741ed4cb8, 0xc23c481be0, 0x8204, 0x99a6, 0x13, 0x8204)
        /root/.gvm/gos/go1.4.3/src/sort/sort.go:129 +0x434
sort.quickSort(0x7f0741ed4cb8, 0xc23c481be0, 0x8204, 0x99a6, 0x21)
        /root/.gvm/gos/go1.4.3/src/sort/sort.go:173 +0xa9
sort.quickSort(0x7f0741ed4cb8, 0xc23c481be0, 0x0, 0x99a6, 0x24)
        /root/.gvm/gos/go1.4.3/src/sort/sort.go:180 +0x178
sort.quickSort(0x7f0741ed4cb8, 0xc23c481be0, 0x0, 0x23749, 0x25)
        /root/.gvm/gos/go1.4.3/src/sort/sort.go:177 +0x104
sort.quickSort(0x7f0741ed4cb8, 0xc23c481be0, 0x0, 0x6b3fa, 0x26)
        /root/.gvm/gos/go1.4.3/src/sort/sort.go:177 +0x104
sort.quickSort(0x7f0741ed4cb8, 0xc23c481be0, 0x0, 0xf365a, 0x27)
        /root/.gvm/gos/go1.4.3/src/sort/sort.go:177 +0x104
sort.Sort(0x7f0741ed4cb8, 0xc23c481be0)
        /root/.gvm/gos/go1.4.3/src/sort/sort.go:200 +0x7b
github.com/influxdb/influxdb/tsdb/engine/tsm1.Values.Deduplicate(0xc2b00ee000, 0xf365b, 0x12fc00, 0x0, 0x0, 0x0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/encoding.go:215 +0x3e1
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*entry).deduplicate(0xc232ca1f40)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cache.go:61 +0x4a
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Cache).Deduplicate(0xc236025450)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cache.go:155 +0x76
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).WriteSnapshot(0xc2a5bb0000, 0x0, 0x0)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:417 +0xde
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).compactCache(0xc2a5bb0000)
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:460 +0x10f
created by github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Open
        /tmp/tmp.WXyOm7f2Na/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:135 +0x24e
```

**Comment by fffw** [comment]
You are so kind @jonseymour. It's running on 64bit Ubuntu but I probably want to stick on 0.10.1 and see if it will crash again ^_^

**Comment by jonseymour** [comment]
@fffw ok, so I have done the back port. I have no idea if it will be accepted into an 0.10.2 branch and there may be good reasons not to. But, the code is there if anyone wants to use it.

**Comment by fffw** [comment]
Bang! Now I hit the bug on 0.10.1. Let me see if I can build a linux64 binary tomorrow. @jonseymour if you by chance is very convenient to build one, that would be very thankful!

**Comment by jonseymour** [comment]
@fffw ok, you have options:

1. wait until I have created a fix-only variant of #5858 which it looks might be accepted into 0.10.x
2. take the actual version I am running production myself (https://github.com/jonseymour/influxdb/commits/stable) that also contains some other fixes and the cache statistics enhancements.

**Comment by jonseymour** [comment]
@fffw the fixes have now been merged into the 0.10.0 branch, so I suspect you now have a 3rd option which is to wait some non-negative number of days for a 0.10.2 release.

**Comment by fffw** [comment]
@jonseymour Thank you for all the help and suggestions! I probably need to allocate more time to keep track of the progress in the future. I'll close this case if it doesn't recur for a few days after applying one of the options on my production environment.

**Comment by andybrier** [comment]
I have the same issue too. It happened even everyday.  InfluxDB 0.10.1 is installed on centos 6.5   . The stack is as below:

[retention] 2016/03/01 14:42:12 retention policy shard deletion check commencing
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x800ec1]

goroutine 13652003 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.Values.Deduplicate(0xc270538000, 0x152a, 0x152a, 0x0, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/encoding.go:207 +0xf1
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Cache).merged(0xc20e08a6e0, 0xc213d542a0, 0x6d, 0x0, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cache.go:280 +0x6f5
github.com/influxdb/influxdb/tsdb/engine/tsm1.func·002(0x0, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cache.go:216 +0x8a
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Cache).Values(0xc20e08a6e0, 0xc213d542a0, 0x6d, 0x0, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cache.go:217 +0x178
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*tx).Cursor(0xc2205a3908, 0xc20821bb90, 0x67, 0xc2fd66e9c0, 0x1, 0x1, 0xc20de80980, 0xc2fd66e901, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:645 +0x147
github.com/influxdb/influxdb/tsdb.(*AggregateMapper).openMeasurement(0xc2356520f0, 0xc208bee7e0, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/aggregate.go:690 +0x551
github.com/influxdb/influxdb/tsdb.(*AggregateMapper).Open(0xc2356520f0, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/aggregate.go:646 +0x6fb
github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).openMappers(0xc335830960, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/aggregate.go:205 +0x9b
github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).execute(0xc335830960, 0xc21d13cc00, 0xc213b77ce0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/aggregate.go:70 +0x1ab
created by github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).Execute
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/aggregate.go:48 +0x64

goroutine 1 [chan receive, 1264 minutes]:
main.(*Main).Run(0xc20803b700, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cmd/influxd/main.go:96 +0x7a1
main.main()
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0xdc

goroutine 6 [syscall, 1264 minutes]:
os/signal.loop()
	/root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:27 +0x35

goroutine 35 [IO wait, 393 minutes]:
net.(*pollDesc).Wait(0xc208010370, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.3/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010370, 0x0, 0x0)
	/root/.gvm/gos/go1.4.3/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010310, 0xc208166000, 0x1000, 0x1000, 0x0, 0x7f3fec17dee8, 0xc313154df0)
	/root/.gvm/gos/go1.4.3/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c020, 0xc208166000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.3/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f3fec186c38, 0xc20802c020, 0xc20806a108, 0xc208166000, 0x1000, 0x1000, 0xa6fdc0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.3/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20813a100, 0xc208166000, 0x1000, 0x1000, 0xc2080c8000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20805d140)
	/root/.gvm/gos/go1.4.3/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20805d140, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.3/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20806a0b0)
	/root/.gvm/gos/go1.4.3/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/root/.gvm/gos/go1.4.3/src/net/http/transport.go:660 +0xc9f

**Comment by jonseymour** [comment]
@andybrier The fix for this #5858 has been merged into the 0.10.0 so I would expect that it will end up in a 0.10.2 release at some point in the not too distant future - I can't say when because I am not privy to that kind of detail. 

If you would like an experimental build (completely unsupported by anyone but me!) that contains just the #5858 let me know by e-mail and I can send you a link where you can download the amd64 binary. Alternatively, just checkout the influxdb source tree at the relevant commit and build it yourself - it is pretty easy to do if you have docker installed.

**Comment by andybrier** [comment]
@jonseymour  Thanks a lot.  I will send you an email for downloading the amd64 binary.  That's very kind of you :+1:

**Comment by fffw** [comment]
Run for 4 days without seeing panicking. Closing. Thanks for all the help @jonseymour

**Comment by semihalev** [comment]
I got panic on same function many time. Starting influx service everyday.

OS: Linux
Tested versions: 1.3.5-stable, 1.3.6-stable

Panic:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80000ebc450 pc=0x9b14d9]

goroutine 2977573 [running]:
runtime.throw(0xb8a60b, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc429aa05f0 sp=0xc429aa05d0
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc429aa0640 sp=0xc429aa05f0
github.com/influxdata/influxdb/tsdb/engine/tsm1.Values.Deduplicate(0xc4222fc000, 0xae8, 0xe00, 0xc42e9ca000, 0xc421341058, 0xc42a16ef60)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.gen.go:66 +0x99 fp=0xc429aa06c0 sp=0xc429aa0640
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*entry).deduplicate(0xc420339a80)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:125 +0x86 fp=0xc429aa0700 sp=0xc429aa06c0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Cache).Deduplicate.func1(0xc423d1a080, 0x72, 0xc420339a80, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:431 +0x2b fp=0xc429aa0718 sp=0xc429aa0700
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*ring).apply.func1(0xc421e676b0, 0xbb0a58, 0xc426cbdec0, 0xc42055a600)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/ring.go:160 +0xed fp=0xc429aa07c0 sp=0xc429aa0718
