### ISSUE TITLE
InfluxDB v0.10.1 panic: close of closed channel

### ISSUE THREAD

**Issue by s1m0** [influxdata/influxdb#5866]
Since upgrading to v0.10.1 and converting from bz1 to tsm1 I have seen this 4 times;
```
[retention] 2016/02/29 06:41:02 retention policy shard deletion check commencing
panic: close of closed channel
```

**Comment by s1m0** [comment]
<script src="https://gist.github.com/s1m0/a6f0c83f4532e43407c1.js"></script>

**Comment by rossmcdonald** [comment]
@s1m0 I think this is a permissions issue (and a duplicate of https://github.com/influxdata/influxdb/issues/5244), most likely caused by the shard conversion. Can you try running a:

```
chown -R influxdb:influxdb /var/lib/influxdb/data
```

And let us know if you see it again?

**Comment by s1m0** [comment]
the ownerships of the shard directories were root:root - as a result of the tsm conversion process I assume. Since changing to influxdb:influxdb, I haven't see the crash again - approximately 3 hours. Closing this issue, thanks for the help.
