### ISSUE TITLE
Collectd plugin is not storing data and is stopping the influxdb service

### ISSUE THREAD

**Issue by gabrieljames** [influxdata/influxdb#5867]
Hi Influx,

This is my first time configuring log collection, time series databases and reporting tools, we are evaluating the InfluxDB TICK and Elasticsearch ELK stacks.
 
I'm having problems getting InfluxDB to work with collectD

The documentation is pretty limited at Influx and lacks of example configuration files for input services and collectD. There seems to be a lot of syntax changes in the configuration files between versions of InfluxDB. 

With the lack of documentation at InfluxDB, this forces you to look at third party websites to find documentation on how other users have implemented this configuration and there are big differences out in the user community. So right now, i'm feeling pretty frustrated with InfluxDB, which is a shame, because it looks like a good product.
   
Ubuntu 14.0 LTS

**This influxdb.conf file causes the service to fail a few seconds after starting**
/etc/influxdb/influxdb.conf
```
[collectd]
enabled = true
bind-address = "127.0.0.1"
database = "collectd"
typesdb = "/usr/share/collectd/types.db`
```

**This influxdb.conf file starts the service but no data is stored within the collectd database**
```
[collectd]
enabled = true
# bind-address = "127.0.0.1"
# database = "collectd"
# typesdb = "/usr/share/collectd/types.db
```

It would be great if you provide some support and even examples in your documentation of valid [collectd] section in influxdb.conf 

1. What are valid names and entries for bind-address? 
- hostname
- ip address
- localhost? 
- 127.0.0.1? 
- TCP ports?
- UDP ports? 

Gabe

**Comment by rossmcdonald** [comment]
Closing, as most questions have been answered through https://github.com/influxdata/influxdb/issues/5836. I've also filed a PR [here](https://github.com/influxdata/docs.influxdata.com/pull/282) to help address the lack of documentation (and at least link to the service readme in the repo).

Sorry for the issues. Let us know if you have any other questions!

**Comment by lin-credible** [comment]
@rossmcdonald  #8140  ❤️
