### ISSUE TITLE
Best practices for HA/load balancing

### ISSUE THREAD

**Issue by sofixa** [influxdata/influxdb#5868]
Hello, everybody.

I have read the docs and i've Googled, but most of the results i've found are about older version of InfluxDB(mostly 0.8.x and 0.9.x) and I think a lot has changed.

I need to create an InfluxDB cluster that should, eventually, be able to handle ~1000 servers running Telegraf collecting metrics every 10s and flushing them every 30s or so on AWS.
I was thinking of starting with 3 m4.xlarge instances in hybrid roles, with separate EBS volumes for data,meta and hh, which should be enough for the start, and then i'll add extra m4.xlarges if there's the need.

However, i have a few questions - how do i handle the write/reads:
Do i setup a load balancer(an ELB) that would send the writes randomly to any InfluxDB or would that create too much of traffic and thinking inbetween the Influxes trying to sync? Ot do i handle that by randomizing the list of InfluxDB outputs in Telegraf, so that it writes (more or less) equally to every InfluxDB? And do i need the replication factor to be equal to the number of data nodes? Wouldn't 2 be enough in most cases for failover, maintaining data integrity in case of a failed instance, but without too much data replication(which means network traffic, processor time, hard drive occupation, etc.)?
As for the writes, what would be better - a Grafana/Chronograf that reads from a dedicated InfluxDB node or randomly with a load balancer?
And if i do end up using a load balancer, do i need sticky sessions(i don't think so, but i saw a post on the web for Influx 0.8.x that mentioned sticky sessions as a must-have).

Thanks in advance,
Kind regards,
Adrian

PS: You may consider this as a feature request to update your doc with more info on this matter :)

**Comment by pbooth** [comment]
Here's one datapoint- I'm writing a few GB of wire format influxbd data every hour. My instances are on a mix of Westmere and Sandy Bridge dual socket servers with FusionIO. Initially my write performance was abysmal an di ended up concluding that the sweet spot, in my environment is to write batches of 200,000 measurements at a time to each influxdb instance. So I am using curl to upload files that are 10 to 30MB in size, which is  a lot larger than I would have expected.

I was waiting for a rock solid 0.10 before beginning to experiment with clustering. Most of the time my instances are running a range of different versions

**Comment by joelegasse** [comment]
@sofixa We now have a page talking about [HA](https://influxdata.com/high-availability/) with InfluxDB, and should have some code in (influxdb-relay)[https://github.com/influxdata/influxdb-relay] next week.

I'm going to close this issue, but feel free to open issues in the influxdb-relay project for any further questions about HA and InfluxDB.

**Comment by Komalgupta22722** [comment]
I am working on HA for influx, have implemented load balanncer as well as relay but How to send data to loadbalancer ?
