### ISSUE TITLE
[0.11.0~n1456732833] Previously worked, now receiving query error when selecting measurement starting with '_'

### ISSUE THREAD

**Issue by gerrickw** [influxdata/influxdb#5870]
Summary:
In a master branch version of influxdb about 2-3 weeks ago I was writing measurements with the starting character _ and able to select the measurement to get data back.  After pulling the latest I now receive an error of, "Server returned error: unknown system source: _this_metric_is_not_working".

Steps to Reproduce:
1. Send _this_metric_is_not_working through line protocol. 
2. Notice: No errors.
3. Query: show measurements
4. Notice: Response shows _this_metric_is_not_working
5. Query: show series
6. Notice: Response shows _this_metric_is_not_working
7. SELECT mean(value) FROM _this_metric_is_not_working  where time > now() - 1h GROUP BY time(10s)
8. Notice: Server returned error: unknown system source: _this_metric_is_not_working

This is a single server with no clustering.

**Comment by gerrickw** [comment]
If it is now expected to not support a measurement starting with '_' is there a way I could move the data to a new name?

Mostly just looking for a workaround -- Thanks.

**Comment by gerrickw** [comment]
I was looking through the source for this error and it seems the error was recently touched around the time I noticed the problem happening on pull #5811.  

@benbjohnson Is this something you might have better understanding why starting with a '_' measurement would now cause the default case statement to trigger?

return nil, fmt.Errorf("unknown system source: %s", m.Name)

**Comment by gerrickw** [comment]
As a note, I rolled back to 0.10.3 stable and it started working again with measurements starting with '_'.  Hopefully this can be fixed before cutting a new stable branch.

**Comment by benbjohnson** [comment]
We've used the `_` prefix for internal tables (such as statistics). We can change the functionality to only restrict system series evaluation for known internal tables instead of all `_` prefixed series. However, we don't guarantee that we won't possibly add a conflicting internal series in the future.

**Comment by gerrickw** [comment]
This is extremely helpful, was starting to feel the dread of possibly trying to convince people to rename their metrics.  Thanks a bunch.
