### ISSUE TITLE
Have GROUP BY respect time in the WHERE clause when COUNTing

### ISSUE THREAD

**Issue by petterbrodin-goodtech** [influxdata/influxdb#5872]
Referring to [this mailing list discussion](https://groups.google.com/forum/#!topic/influxdb/ADzfdrscuPU), is it possible to have influxdb only include values that are present in the time range being queried?

Example: you have a series where you log currently active error codes. If you want to see active error codes within the past five minutes, you 

For example, the following query will return 0 for error codes that haven't been active within the time period and may not even be applicable anymore:

SELECT COUNT(errorcode)
FROM errorSeries
WHERE time > now() - 5m
GROUP BY errorcodeTag

I don't know if this is expected behaviour, but MIN, MAX, FIRST, LAST, SUM, etc. only return results relevant to the specified time period.

**Comment by jwilder** [comment]
I think the query you show returns the results as desired as of 1.1 now.  Let us know if not.
