### ISSUE TITLE
derivative returning high first value

### ISSUE THREAD

**Issue by smalenfant** [influxdata/influxdb#5873]
I'm using telegraf to send data to our InfluxDB cluster. I'm using this query to get the bitrates in bits/sec

`SELECT non_negative_derivative(sum("bytes_sent"), 10s) /60*8 FROM "net" WHERE time > now() - 1h GROUP BY time(1m), "cachegroup" fill(null)`

Although the returns is fine, the first value is wrong and our graphs looks flat. Can't seem to find out why the first value is always high.

```
net
cachegroup:us-ga-test

time	
2016-03-01T12:19:00Z	25978789352032.887
2016-03-01T12:20:00Z	480273222.625
2016-03-01T12:21:00Z	471934727.2447917
2016-03-01T12:22:00Z	481183072.2864583
2016-03-01T12:23:00Z	474883115.0885417
2016-03-01T12:24:00Z	458046972.84375
```

**Comment by cxreg** [comment]
This is probably a dupe of https://github.com/influxdata/influxdb/issues/5821 and https://github.com/influxdata/influxdb/pull/5733

**Comment by smalenfant** [comment]
Same issue.
