### ISSUE TITLE
Dropping a node and adding new node does not rebalance no of shard owners

### ISSUE THREAD

**Issue by supershal** [influxdata/influxdb#5881]
Similar to #5680 @e-dard @benbjohnson @jwilder 
 
we are testing the few clustering scenario in our EC2 cluster. I created 3 node cluster and a retention policy with 3 replicas. 
We are testing a scenario where AWS remove existing node for maintenance and we have to provision new one with different IP. We are testing the same with containers too so we dont have sticky hostnames for nodes.
Initial owners of the shard group was node 1,2,3
```
> show shards
name: telegraf
--------------
id	database	retention_policy	shard_group	start_time		end_time		expiry_time		owners
3	telegraf	default			3		2016-02-29T00:00:00Z	2016-03-07T00:00:00Z	2016-03-07T00:00:00Z	1,2,3
```
When we dropped a node 3 the owners of the shard group reduced to 1,2

```
 > drop data server 3
> show shards
name: telegraf
--------------
id	database	retention_policy	shard_group	start_time		end_time		expiry_time		owners
3	telegraf	default			3		2016-02-29T00:00:00Z	2016-03-07T00:00:00Z	2016-03-07T00:00:00Z	1,2
```
We brought up another node with different ip which got id of 4:
```
> show servers
name: data_nodes
----------------
id	http_addr		tcp_addr
1	192.168.0.137:8086	192.168.0.137:8088
2	192.168.0.202:8086	192.168.0.202:8088
4	192.168.0.203:8086	192.168.0.203:8088


name: meta_nodes
----------------
id	http_addr		tcp_addr
1	192.168.1.87:8091	192.168.1.87:8088
```
However, the new node with ID = 4 was not added as a new owner to the shard group despite the replicas set to 3 for the retention policy.
```
 > show shards
name: telegraf
--------------
id	database	retention_policy	shard_group	start_time		end_time		expiry_time		owners
3	telegraf	default			3		2016-02-29T00:00:00Z	2016-03-07T00:00:00Z	2016-03-07T00:00:00Z	1,2
```

what should be expected behavior here?
Should the no of owner recovered as data node added to the cluster?
Is data are still replaced 3 times as per the policy between two owners? If so, How to confirm it?

I am also going to test the same with attached EBS volumes by preserving meta and data volumes between node rebuilds and create new node with different ip and existing node id (stored in meta/node.json). If anyone have already tested this usecase is already tested then please share results.

**Comment by e-dard** [comment]
Hi @supershal, 

What version of Influx are you using? (I think you're using head based on the behaviour when dropping a node)?

I don't think that we currently check that shards are re-replicated onto new data nodes if they have lost an owner. Could be useful to do that.

**Comment by supershal** [comment]
I am using v 0.10.1.

**Comment by e-dard** [comment]
@supershal sorry, I hadn't had my coffee at that point this morning. :smile: 

So yeah, the expected behaviour at the moment is that the group loses an owner for the shard, and a new owner will not be put in to bring the owners back up to the replication factor. 

I'm going to open a new issue so we can keep track of the need for this. I'll close this one once I've done that, if that's OK with you?

**Comment by supershal** [comment]
Thanks @e-dard 
Looks like a feature request is already filed for this #5583 
Btw, I also tried to bring new node with existing meta and data dirs that were mounted on EBS. The node starts fine (no errors) but does not register as data node. 
I guess the ID to hostname/ip is immutable.
ex. Even if I drop data node 3
 > add new node with meta info of node 3, it does not register as data node.
> add new node without meta info of 3, it assigned as node Id 4.
In any case, my understanding is that once a node is dropped using `drop data server <id>`, It cant be brought back up with the same id even though its data is recoverable.

**Comment by jsternberg** [comment]
Clustering [has been removed](https://influxdata.com/blog/update-on-influxdb-clustering-high-availability-and-monetization/) from the open source version so I'm going to close this issue.
