### ISSUE TITLE
golang influxdb client can't write data using "n" as time Precision

### ISSUE THREAD

**Issue by bmeboy** [influxdata/influxdb#5884]
influxdb 0.10.0:
1. I download influxdb 0.10.0's standalone Binary from https://influxdata.com/downloads/#influxdb
and then unzip it 
2. when i went to the dir influxdb-0.10.0-1/usr/bin, use ./influxd to start influxdb

**golang **influxdb client 0.10.0:
i just use the ExampleClient_Write in dir github.com\influxdata\influxdb\client，it worked ok， can write data to influxdb。
however, when is changed Precision's value at the 100th line from 's' to 'n' or 'ns', it did not work well, in other words, it can not write data to influxdb.

details：
func main() {
	host, err := url.Parse(fmt.Sprintf("http://%s:%d", "172.31.18.137", 8086))
	if err != nil {
		log.Fatal(err)
	}
	con, err := client.NewClient(client.Config{URL: *host})
	if err != nil {
		log.Fatal(err)
	}

	var (
		shapes     = []string{"circle", "rectangle", "square", "triangle"}
		colors     = []string{"red", "blue", "green"}
		sampleSize = 5
		pts        = make([]client.Point, sampleSize)
	)

	rand.Seed(42)
	for i := 0; i < sampleSize; i++ {
		pts[i] = client.Point{
			Measurement: "shapes",
			Tags: map[string]string{
				"color": strconv.Itoa(rand.Intn(len(colors))),
				"shape": strconv.Itoa(rand.Intn(len(shapes))),
			},
			Fields: map[string]interface{}{
				"value": rand.Intn(sampleSize),
			},
			Time:      time.Now(),
			Precision: "u", **_//if the value here was u, ms, s, m, or h, data can be inserted; if used n or ns, data can not be inserted_**
		}
	}

	bps := client.BatchPoints{
		Points:          pts,
		Database:        "BumbeBeeTuna",
		RetentionPolicy: "default",
	}
	_, err = con.Write(bps)
	if err != nil {
		log.Fatal(err)
	}

	q := client.Query{
		Command:  "select * from shapes ",
		Database: "BumbeBeeTuna",
	}
	if response, err := con.Query(q); err == nil {

		//&& response.Error() == nil
		if response.Error() == nil {
			log.Println(response.Results)
		} else {
			log.Println(response.Error())
		}

	}

	if err != nil {
		log.Fatal(err)
	} else {
		log.Println("over")
	}
}

**Comment by joelegasse** [comment]
@bmeboy Please use version 2 of the client for now: https://godoc.org/github.com/influxdata/influxdb/client/v2

I'm going to close this issue since we recommend the v2 client. If you have trouble using the updated client, please file another issue.
