### ISSUE TITLE
influxd not binding to all required ports on restart

### ISSUE THREAD

**Issue by kemra102** [influxdata/influxdb#5885]
Yesterday we restarted the `influxd` service on one of our InfluxDB boxes but when it came back up it only bound to port 8088 (meta) instead of all the configured ports; which should be:
- 8083 (admin)
- 8086 (http)
- 25826 (collectd)
- 2003 (graphite)

This was on InfluxDB `0.9.5` on CentOS 7.

The logs had the following content (nothing immediately helpful):

``` sh
[wal] 2016/03/01 17:15:59 WAL writing to /var/lib/influxdb/wal/_internal/monitor/124
[wal] 2016/03/01 17:15:59 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/03/01 17:15:59 WAL writing to /var/lib/influxdb/wal/collectd/default/103
[wal] 2016/03/01 17:15:59 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/03/01 17:15:59 WAL writing to /var/lib/influxdb/wal/collectd/default/112
[wal] 2016/03/01 17:15:59 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/03/01 17:15:59 WAL writing to /var/lib/influxdb/wal/collectd/default/121
[wal] 2016/03/01 17:15:59 reading WAL files to flush to index
[wal] 2016/03/01 17:15:59 writing 3438 series from WAL file /var/lib/influxdb/wal/collectd/default/121/01.012614.wal to index
[tcp] 2016/03/01 17:16:01 tcp.Mux: handler not registered: 71
```

I killed off the process, ensure it wasn't running, checked nothing was bound to any of the ports InfluxDB needed and started it again - but we got the same issue.

I decided to start via the CLI to see if we got some info that wasn't logged (I accidently did this as root instead of the `influxdb` user):

``` sh
# /usr/bin/influxd -config /etc/influxdb/influxdb.conf

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

2016/03/01 17:24:45 InfluxDB starting, version 0.9.5, branch 0.9.5, commit 770b0ecf9f1f61a9d3a97136d5b6d7dd21afea1e, built 2015-11-20T15:30:37+0000
2016/03/01 17:24:45 Go version go1.4.2, GOMAXPROCS set to 2
2016/03/01 17:24:45 Using configuration at: /etc/influxdb/influxdb.conf
[metastore] 2016/03/01 17:24:45 Using data dir: /var/lib/influxdb/meta
[metastore] 2016/03/01 17:24:45 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2016/03/01 17:24:45 Node at localhost:8088 [Follower]
[metastore] 2016/03/01 17:24:46 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2016/03/01 17:24:46 spun up monitoring for 1
[store] 2016/03/01 17:24:46 Using data dir: /var/lib/influxdb/data
[metastore] 2016/03/01 17:24:46 Updated node id=1 hostname=localhost:8088
[wal] 2016/03/01 17:24:46 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/03/01 17:24:46 WAL writing to /var/lib/influxdb/wal/collectd/default/103
[wal] 2016/03/01 17:24:46 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/03/01 17:24:46 WAL writing to /var/lib/influxdb/wal/collectd/default/112
[wal] 2016/03/01 17:24:47 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/03/01 17:24:47 WAL writing to /var/lib/influxdb/wal/collectd/default/121
[wal] 2016/03/01 17:24:47 reading WAL files to flush to index
[wal] 2016/03/01 17:24:47 writing 3438 series from WAL file /var/lib/influxdb/wal/collectd/default/121/01.012614.wal to index
^C
```

No error, it just seems to simply not start anything other than the meta part of InfluxDB.

At this point I was at a loss so I updated to the latest release (`0.10.1`) and restarted `influxd`.

Same issue but with one minor difference, we now have `influxd` listening on an address/port we don't have configured:

``` sh
tcp        0      0 127.0.0.1:8091          0.0.0.0:*               LISTEN      54657/influxd
```

**Comment by kemra102** [comment]
So the above InfluxDB instance seems to be working now, so I would assume a VERY long start-up time.

Looking at Grafana it looks like it took ~2 hours to start up and start recording data sent to it again (we have collectd pumping data in roughly once every second).

**Comment by toddboom** [comment]
@kemra102 Can you tell us a little bit more about the data you had stored on disk when it took so long to start up?

**Comment by kemra102** [comment]
Very little, we're still finding our feet with InfluxDB.

There was just shy of 80GB  (collected over a period of about 2.5 months) of data total. It is mostly stats from collectd running across our estate and talking to Influx's fake collectd server. We also had Icinga forwarding information it collected to Influx's fake Graphite server backend.

We haven't done anything with the format of that data before it was sent or after it was received by Influx (other than graphing it in Grafana), so it should be in the native format one would expect from those components.

**Comment by e-dard** [comment]
@kemra102 regarding `8091` on `0.10`: that port is used by a meta node to bootstrap communication with other nodes in a cluster. It's currently needed even for single node clusters.

**Comment by e-dard** [comment]
Issue no longer relevant to current InfluxDB version
