### ISSUE TITLE
[0.11] Nesting DISTINCT() in COUNT() with string field values returns an error (unlike 0.10)

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#5886]
When my field values are floats, nesting `DISTINCT()` in `COUNT()` works:
```
> SELECT mynum FROM mymeas
name: mymeas
------------
time				            mynum
2016-03-02T17:43:18.978582468Z	1
2016-03-02T17:43:21.08920201Z	1
2016-03-02T17:43:22.7130337Z	3
2016-03-02T17:43:23.984634459Z	4

> SELECT COUNT(DISTINCT(mynum)) FROM mymeas
name: mymeas
------------
time			        count
1970-01-01T00:00:00Z	3
```
When my field values are strings, nesting `DISTINCT()` in `COUNT()` returns an error:
```
> SELECT mystring FROM mymeas
name: mymeas
------------
time				            mystring
2016-03-02T17:39:05.162187294Z	and miles
2016-03-02T17:39:13.256191Z	    to go before
2016-03-02T17:39:22.407710146Z	i sleep
2016-03-02T17:39:28.023493995Z	and miles

> SELECT COUNT(DISTINCT(mystring)) FROM mymeas
ERR: unsupported count iterator type: *influxql.stringReduceSliceIterator
```
This last query doesn't return an error in 0.10.

**Comment by jsternberg** [comment]
I have a feeling there are some others like this such as `first()` and `last()` too. Can you also tell me if `min()` and `max()` are supposed to work for strings and/or booleans?

**Comment by rkuchan** [comment]
In the docs we specify that min() and max() only work with floats and ints. 

In 0.10, if I try taking the min() of a string I just get 0, so:
```
> select min("level description") from h2o_feet
name: h2o_feet
--------------
time			        min
2015-08-18T00:00:00Z	0
```

**Comment by jsternberg** [comment]
We've changed the behavior to returning an error. @jwilder @benbjohnson is the current behavior ok or do we need to change `min()` and `max()` to return zero for strings and booleans?

**Comment by rkuchan** [comment]
Confirming that I get similar errors with `first()` and `last()` in 0.11:
```
> SELECT first("level description") from h2o_feet
ERR: unsupported first iterator type: *influxql.stringMergeIterator
> SELECT last("level description") from h2o_feet
ERR: unsupported last iterator type: *influxql.stringMergeIterator
```

**Comment by benbjohnson** [comment]
@jsternberg We should add string and bool support for min/max/first/last. They seem pretty trivial.

**Comment by jsternberg** [comment]
first/last get added as part of this PR. min/max I don't know if those make sense. Maybe for strings, but I don't think it makes sense for bools.

**Comment by jwilder** [comment]
If we treat a bool as `0` or `1` in this context then I think it makes sense for min/max too.
