### ISSUE TITLE
WHERE clause on aggregate results and SELECT AS results not working

### ISSUE THREAD

**Issue by sischnei** [influxdata/influxdb#5898]
Maybe I'm wrong but I think something like the following query should be possible:
`SELECT DERIVATIVE("Frees") AS "result" FROM runtime WHERE time >= now() - 10m AND "result" >= 0`

However, I don't get a single result whereas I would expect all entries where the "result" column is greater than 0 (which you'll see are quite a few when you run the query without the AND "result" >= 0)

Furthermore, I would expect a query like this to work:
`SELECT "Frees" AS "result" FROM runtime WHERE time >= now() - 10m AND "result" >= 9`
Again no output! If you change it to something like this:
`SELECT "Frees" AS "result" FROM runtime WHERE time >= now() - 10m AND "Frees" >= 9`
it does work!

Version: InfluxDB 0.10.1

**Comment by rossmcdonald** [comment]
@sischnei Aliasing only affects the output columns, but does not change how the data is referenced from within the query itself. That's why your second query:

```
SELECT "Frees" AS "result" FROM runtime WHERE time >= now() - 10m AND "Frees" >= 9
```

Works as expected, but the first:

```
SELECT "Frees" AS "result" FROM runtime WHERE time >= now() - 10m AND "result" >= 9
```

Does not. In the second query, InfluxDB is looking for a "result" tag/field in the original data set (not within the query itself), of which there probably is none.

Regarding your original query:

```
SELECT DERIVATIVE("Frees") AS "result" FROM runtime WHERE time >= now() - 10m AND "result" >= 0
```

You can change it to:

```
SELECT DERIVATIVE("Frees") AS "result" FROM runtime WHERE time >= now() - 10m AND "Frees" >= 0
```

Which should work, but I don't think that's what you want. As far as I'm aware, I don't think there's a way to limit the result of the `derivative()` function in the `where` clause, so you may have to perform some post-processing on the results to get the desired effect.

**Comment by rossmcdonald** [comment]
@sischnei Now that I think about it, there is a way to do what you want using multiple queries. For example, you can store the derivative results into another measurement (either ad-hoc or using a CQ), and then use `"result" >= 0` to query the resulting measurement. Similar to:

```
SELECT derivative("Frees") AS "result" INTO deriv_runtime FROM runtime WHERE time >= now() - 10m
SELECT result FROM deriv_runtime WHERE "result" >= 0
```

I'd recommend using a CQ to do this on a set interval. Documentation [here](https://docs.influxdata.com/influxdb/v0.10/query_language/continuous_queries/)

**Comment by sischnei** [comment]
@rossmcdonald Thanks for the valuable tip on how to to do this. For now I'll go with that. I still think though that this would be a very nice feature to have and also not that complex to implement in InfluxDB!?

Regarding the aliasing query: I thought a query like this was valid in standard SQL (or at least dialects) but I have since learned, that this is not supported in standard SQL either, so I guess it ok the way it is!

**Comment by rossmcdonald** [comment]
@sischnei I agree, I think what you would really need is support for a `HAVING` clause. There is a feature request for it [here](https://github.com/influxdata/influxdb/issues/5266). Then you could say:

```
SELECT DERIVATIVE("Frees") AS "result" FROM runtime WHERE time >= now() - 10m HAVING derivative("Frees") >= 0
```

**Comment by jsternberg** [comment]
I'm going to close this in favor of #5266 so it's easier to track the progress of this feature.

**Comment by dandv** [comment]
@sischnei I ran into the same issue, and the solution was to [use a subquery](https://community.influxdata.com/t/solved-how-to-find-gaps-in-my-data/2982/3?u=dandv).
