### ISSUE TITLE
InfluxDB cluster.

### ISSUE THREAD

**Issue by deepujain** [influxdata/influxdb#5904]
I am unable to understand https://docs.influxdata.com/influxdb/v0.10/clustering/cluster_node_config/ . Is there any other documentation that explains 

How does a cluster architecture look like, What nodes do what and communicate to which nodes and which nodes serves queries  and what nodes should be scaled when data increases ?

Something like this : http://druid.io/docs/img/druid-dataflow-3.png 

Cluster Setup
1. What does a influx db cluster look like ?
2. What are types of nodes and what is the function of each node ?
Is there is  master node (like HDFS Namenode) and multiple data nodes (like data nodes in HDFS). 
And what is single point of failure ? (And how can it be replicated to avoid single point of failure).

Query Execution Time

1. - How do i speed up query execution ? 
2. - Is there a way to implement cache ?
3. - If my data changes once every day, having a cache can speed up queries.
4. - 

Data Scaling 

1. When data nodes go down how do i avoid loss of data ?
2. 

Data Loss ?

1. What nodes should i add when my data ingestion size keeps on increasing ?
2.

**Comment by deepujain** [comment]
Query Execution Time
How do i speed up query execution ? 
Is there a way to implement cache ?
If my data changes once every day, having a cache can speed up queries.


What nodes should i add when my data ingestion size keeps on increasing ?

**Comment by sebito91** [comment]
InfluxDB clustering is based on the raft protocol, and it's currently under active development. To date, you can separate nodes into meta vs data nodes (or a hybrid), but distributed queries are not fully developed nor is active fault tolerance.

To understand the approach, required reading includes the following:

https://raft.github.io/
http://ramcloud.stanford.edu/raft.pdf

**Comment by deepujain** [comment]
So today, influxDB is only 1 node installation ? 
What happens when data size grows ? 
How do you handle growth ?
How do you implement caching (this can speed up query performance)

**Comment by sebito91** [comment]
Hehe, very valid questions...best answer to be honest is that "it depends".

InfluxDB is currently a single-node solution with the eventual option to pay for clustering services. I would encourage you to _really_ read the documentation they have on this, here are a few more links:

https://influxdata.com/high-availability/
https://github.com/influxdata/influxdb-relay
https://docs.influxdata.com/influxdb/v0.10/guides/hardware_sizing/

**Comment by toddboom** [comment]
@sebito91 I agree - thanks for jumping in!

@deepujain The mailing list is also a good resource for general questions about InfluxDB: https://groups.google.com/forum/#!forum/influxdb
