### ISSUE TITLE
[0.10] WebUI documentation link is outdated

### ISSUE THREAD

**Issue by kirillkovalenko** [influxdata/influxdb#5906]
I'm running 0.10.2.
At the WebUI interface screen (port 8083) there is link to documentation. It is https://docs.influxdata.com/influxdb/v0.9/introduction/getting_started. It should be https://docs.influxdata.com/influxdb/v0.10/introduction/getting_started I guess.

**Comment by zstyblik** [comment]
Indeed it should. Hopefully, this will get fixed by https://github.com/influxdata/influxdb/pull/5862. At least it should.
