### ISSUE TITLE
DIsappearing data with default retention policy

### ISSUE THREAD

**Issue by pbooth** [influxdata/influxdb#5907]
Hello. I have a few influx instances that simply use the default retention policy , and I am seeing data disappear after I insert more data

> select count(value) from prism_latencies where time > now() - 2d
> ## name: prism_latencies
> 
> time                    count
> 1456924319006500360     4.263355e+06
> 
> select count(value) from prism_latencies where time > now() - 2d
> ## name: prism_latencies
> 
> time                    count
> 1456924581862548266     3.43473e+06

I'm not seeing anything logged that explains this.

**Comment by jonseymour** [comment]
@pbooth This only shows that the number of points inserted in the 48 hours immediately preceding each query is different. A better query for demonstrating that a loss has occurred is to use a fixed date in both queries. So:

`select count(value) from prism_latencies where time > '2016-03-03 00:00:00'`

That said, @jwilder did fix a point deduplication issue in #5719 which may also be relevant. This fix was delivered in v0.10.2 which was released today.

**Comment by pbooth** [comment]
You can see from the time delta that the two queries were entered in close proximity. 

I'll see if I can reproduce in a standalone fashion. This keeps occurring so shouldn't be too difficult.

 I do know that my upload method can cause points to be double entered and entered out of order. On related point, when moving Data between DB with SELECT INTO I had repeatedly seen this until I created explicit retention policies.

 QN: Is there an upper limit on the number of points in a series?

**Comment by joelegasse** [comment]
@pbooth The only technical limit on points per series should be the available disk space.

Were you able to come up with a set of steps to reproduce losing data, or is this just a case of double-counted points getting removed by deduplication?
