### ISSUE TITLE
Documentation: backup and restore section should mention that backing up needs tsm1 engine.

### ISSUE THREAD

**Issue by temmihoo** [influxdata/influxdb#5910]
The documentation is not mentioning that backing up only works in certain specific database engines. Reading through search engine hits suggest using 'tsm1': #3923 

Proper place for this information would be at least the backup/restore section[1], possibly also upgrading[2].

Currently the upgrading does mention how to transform the databases for tsm1 engine but does not tell you that backing up does not work with bz1.

  [1]: https://docs.influxdata.com/influxdb/v0.10/administration/backup_and_restore/
  [2]: https://docs.influxdata.com/influxdb/v0.10/administration/upgrading/

**Comment by joelegasse** [comment]
@temmihoo As of the 0.11 release candidate, and all future releases, the `b1` and `bz1` storage engines will not be supported. That being said, we should probably update the 0.10 documentation to make it clear that TSM is required for backup/restore functionality. I went ahead and created a ticket in the documentation repo for this: https://github.com/influxdata/docs.influxdata.com/issues/331
