### ISSUE TITLE
influxdb apt/yum repository available versions

### ISSUE THREAD

**Issue by n1tr0g** [influxdata/influxdb#5913]
Hello,

would be great that you do not remove old influxdb releases from the apt/yum repository so that environments with config management tools like chef, puppet, ansible, etc where you pin the version you want to install doesn't break.

**Comment by zstyblik** [comment]
@n1tr0g, from my experience, you shouldn't rely on 3rd party repositories and make a "local copy". My $0.02USD.

**Comment by n1tr0g** [comment]
true, however if they can provide at least a reliable place from where to sync would be great :)

**Comment by rossmcdonald** [comment]
@n1tr0g The yum repo does contain historical releases, but the apt repo does not. All releases are available on S3, though (going back several years). For example, the `0.10.0` deb and rpm are here:

https://s3.amazonaws.com/influxdb/influxdb_0.10.0-1_amd64.deb
https://s3.amazonaws.com/influxdb/influxdb-0.10.0-1.x86_64.rpm

Where the naming convention is `influxdb_<version>-1_amd64.deb` for debs and `influxdb-<version>-1.x86_64.rpm` for rpms.

**Comment by n1tr0g** [comment]
Hmm I see. If I could choose I would stick to one official repository as other open source projects. 

This makes it hard to have a coherent automation process how to install influxdb. For example now I need to know which one is the last stable version and based on that make a decision if i should use the official repos or some hacks which uses curl/bash to install the packages.

If I use only the s3 packages I loose all the native types to manage packages provided by configuration management tools.

**Comment by cgunther** [comment]
I'd like to see the apt repo contain old versions too. I'm currently using v0.9.4.2 and using chef to provision my servers via installing the package, so I'd have to pin the version to avoid unintentionally upgrading to a non-backwards compatible version, but without the apt repo having old versions, chef fails for me once a new version of influx is released and the version I'm using is no longer available as a package.

**Comment by freeseacher** [comment]
i have the same problem. 
currently repos for debian/ubuntu contains only latest version of database. 
but i need 0.10.3 
Repos for rhel contains older releases. 
could you please return old versions of database to the debian repos. thx!

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by Vish17agr** [comment]
https://repos.influxdata.com/ url doesn't have windows older version.
I am working on inserting data into influx using statsD, but the latest version available 1.3.7 of influx doesn't have the compatibility with latest version of statsD.
Can anyone provide any help on this. Is there any repo where i can find the influx 0.9 version for windows.

**Comment by HogeBlekker** [comment]
Any updates on this, specifically concerning the APT repository? I find the last updated info from April 2016... almost 2 years ago.
