### ISSUE TITLE
[v0.10.2] InfluxDB OOM & long time query

### ISSUE THREAD

**Issue by WuZixing** [influxdata/influxdb#5914]
**Problem of OOM**

hi, guys, I am experiencing a similar problem like #5687 with influxdb v0.10.2, and influxdb got an OOM panic. Influxdb is hosted under the standalone mode by a server with:
OS: CentOS 6.5
CPU: 4
RAM: 14G
InfluxDB: v0.10.2.x86_64, installed from the yum repository stated in the influxdocs web site.

I was doing a stress test on influxdb. It started with nearly empty data, and then ~6k points / sec were writing into influxdb for about 3 hours before influxdb got the OOM panic. After that, I stopped the writing routine, and restarted influxdb service. Even without writing load, the RAM consumed by influxdb raised rapidly after restart, and influxdb continued to panic because of OOM.

Here is the related logs: [influxd.oom.log.tar.gz](https://www.ablecloud.cn/download/influxdb/influxd.oom.log.tar.gz)
And here is the data files: [influxdb.data.tar.gz](https://www.ablecloud.cn/download/influxdb/influxdb.data.tar.gz)
And here is the influxdb.conf: [influxdb.conf](https://www.ablecloud.cn/download/influxdb/influxdb.conf). It was the legacy conf from the previous version influxdb.

**Problem of time consuming query**

During and after the stress test mentioned above, any query targeting the measurement "developer_232_service_0_version_0_log", which was in the ac_logs database and was the target measurement of the writing test, took minutes to get response. Even a query like this: 

*select * from developer_232_service_0_version_0_log limit 5*

could take ~4 minutes to get response. While queries targeting other measurements returned soon.

Thanks for your attention and suggestions.

**Comment by jonseymour** [comment]
@WuZixing is the stress test writing data with the current timestamp or is it writing historical data?

**Comment by jonseymour** [comment]
Also, could you post a listing of the influxdb tree. So:

`find  /var/lib/influxdb -ls`

**Comment by WuZixing** [comment]
@jonseymour data are labeled with current timestamp. And here is the file list of influxdb: 
[tree.txt](https://github.com/influxdata/influxdb/files/161081/tree.txt)

**Comment by jonseymour** [comment]
@WuZixing reviewing the materials you have sent there doesn't seem to be any good reason why influx would be running out of memory on 14GB machine. Is there any chance you could make available a tgz of the entire influxdb directory, including the meta and wal directories? It sounds like the OOM on startup should be easily reproducible with that.

**Comment by jwilder** [comment]
@WuZixing This sounds like a schema design issue.  If you have high cardinality tags, your RAM usage will be higher.  If you are writing distinct tag values for every write, your RAM usage will continuously increase until it OOMs.

Can you provide some sample writes you are sending in line protocol format?

**Comment by WuZixing** [comment]
@jonseymour all directories under influxdb have been included in this tgz: [influxdb.data.tar.gz](https://www.ablecloud.cn/download/influxdb/influxdb.data.tar.gz).

@jwilder I am sure tags were not in a high cardinality. As to the database ac_logs, which was the target database of the stress test, it got tow kinds of measurements: developer_xxx_service_xxx_version_xxx_log, and majorDomain_xxx_service_xxx_version_xxx_container. For the former one, there was one tag key named *level*, and it's value could be one of *DEBUG*, *INFO*, *WARN*, *ERROR*, and *FATAL*. For the later one, there was one tag key named *action*, and it's value could be *exit* or *start*. During the test, all writes were directed into the measurement *developer_232_service_0_version_0_log* with a constant tag value of *level=INFO*.

There were 5 databases, and I got series number for each of the database with SHOW SERIES:

|Database|Number of Series| |
|---|---|---|
|ac_logs|12|ac_logs was the database being involved in the stress test.|
|ac_metrics|0| |
|ac_service_logs|39| |
|ac_trace_logs|5| |
|event_logs|3| |

All points were written through the API of the golang client from influxdb repository:

func (c \*Client) Write(bp BatchPoints) (\*Response, error)

And a sample bp is like this:

```javascript
{
  "Points":[
    {
      "Measurement": "developer_232_service_0_version_0_log",
      "Tags": {"level":"INFO"},
      "Fields":{
        "content":"Test log message.",
        "instance": "AAAABBBBCCCCDDDD"
      },
      "Time":1457407090580558597,
      "Precision":"n"
    },
    {
      "Measurement": "developer_232_service_0_version_0_log",
      "Tags": {"level":"INFO"},
      "Fields":{
        "content":"Test log message.",
        "instance": "AAAABBBBCCCCDDDD"
      },
      "Time":1457407133418643977,
      "Precision":"n"
    },
    {...}
  ],
  "Database":"ac_logs",
  "Precision": "n",
  "RetentionPolicy": "default"
}
```

Thanks again for your attention.

**Comment by jonseymour** [comment]
@WuZixing - just to let you know, I haven't had much luck downloading the .tgz - the download is truncated before it completes.

**Comment by WuZixing** [comment]
@jonseymour could you please retry following links:
all directories under influxdb: [influxdb.data.tar.gz](http://47.88.138.132/influxdb/influxdb.data.tar.gz)
influxdb conf: [influxdb.conf](http://47.88.138.132/influxdb/influxdb.conf)
influxdb OOM log: [influxd.oom.log.tar.gz](http://47.88.138.132/influxdb/influxd.oom.log.tar.gz)

**Comment by jonseymour** [comment]
Thanks @WuZixing - I was able to transfer the data.tar.gz file. I'll have a look at it tonight.

**Comment by jonseymour** [comment]
@WuZixing 

So, I tried starting the influx server against the unpacked tgz. I initially used v0.10.2 but then I tried one built from master.

I was running on OSX.

I noticed that it was trying to compact ac_logs shard 202. If I ran this query:

```select count(instance) from "developer_232_service_0_version_0_log"```

while the compaction was running the memory use did balloon quite (up to 17GB in the HeapInUse metric reported in the runtime stats) and OSX reported a lot of swap in use. The Real Mem in use by the influxd process wasn't that high (around 2 GB). I tried this several times and each time I never got a result from the query.

I killed the influxd process with QUIT and observed that there was an active query and an active compact.

I noticed that if I let the compact finish and then ran the query, the query completed in reasonable time and reported the number of points as 45954720.

All these points only contain two string fields: content and instance and one tag level containing a single value INFO.

My take is that you are observing the cost of executing queries against a single series containing very large number of points specifically in the case that most of the points being queried are still in the cache and have not yet been compacted to their read optimised form. One might argue that this query should perform more efficiently and that perhaps there is an issue to fix (@jwilder, your thoughts?) however the way that you are trying to use influxdb is, I think, is not really what it was designed for. 

Certainly 45,000,000 points logged to a single series over a relatively short period (~3 hours in this case) isn't how influx is typically intended to be used. I am not sure that storing the text of log entries is an ideal use of influxdb which is better suited to numeric data which can be reduced at varying time scales by use of numerical aggregation functions. For example, influxdb doesn't index fields, so you can't easily or efficiently query all log entries matching a given string, for instance so you aren't really getting a whole lot of value from storing your log data inside influx.

**Comment by jonseymour** [comment]
Some other notes: I didn't observe an actual OOM condition in my testing, although perhaps if I had waited longer I may have. That said, I also wasn't running the system under any write load so it is possible that this was a factor that caused an OOM in the OP's case.

**Comment by WuZixing** [comment]
Thanks @jonseymour , swap was disabled on the computer that took my test, so I guess this gave me an OOM panic. 

As you mentioned that it may be not an ideal use of influxdb to store my timing log texts, do you have any recommendation for some proper tools?

**Comment by jonseymour** [comment]
@WuZixing specifically for text-oriented log data tools like Splunk and Logstash are probably a better way to go.

**Comment by WuZixing** [comment]
Thank you @jonseymour , and also thanks to @jwilder.
