### ISSUE TITLE
ORDER BY time DESC not working properly with data in the WAL

### ISSUE THREAD

**Issue by maniac103** [influxdata/influxdb#5915]
I'm using influxdb 0.10.2 with data written by 0.10.1, that is, purely TSM data. The measurement in question is low volume (written once per minute) and thus takes some time to migrated from the WAL into the TSM files. With that setup, I noticed an inconsistency in the processing of 'order by time desc':

> select * from energy_total
```
name: energy_total
----------------------
time			value
[...]
1456703580933000000	1455.392295617
1456703640942000000	1455.394712617
1456703701267000000	1455.3971176169998
1456703760991000000	1455.399518617
1456703821004000000	1455.401912617
1456703881042000000	1455.404306617
1456703941044000000	1455.407229617
1456704001475000000	1455.410381617
1456704061127000000	1455.413522618
1456704121137000000	1455.416641618
1456704181173000000	1455.419754618
1456704241173000000	1455.422858618
1456704301591000000	1455.425956618
1456704361257000000	1455.429048618
1456704421266000000	1455.432131619
1456704481321000000	1455.434883619
[...]
1457183820989000000	1500.533080761
1457183880984000000	1500.539801761
1457183941043000000	1500.547601761
1457184001327000000	1500.555117762
1457184061047000000	1500.562591762
1457184121065000000	1500.570063762
1457184181116000000	1500.577502763
1457184241097000000	1500.584927763
1457184301422000000	1500.5923377640001
1457184361157000000	1500.599740764
1457184421193000000	1500.607042764
1457184481178000000	1500.613694765
1457184541246000000	1500.621216765
```

> select * from energy_total where time <= 1457184181116000000 order by time desc limit 1
```
name: energy_total
----------------------
time			value
1457184181116000000	1500.577502763
```

> select * from energy_total where time < 1457184181116000000 order by time desc limit 1
```
name: energy_total
----------------------
time			value
1456703941044000000	1455.407229617
```

As you can see, the <= operator works correctly, while the < operator returns data from almost a week ago.

show shards for the respective DB looks like this:
```
name: openhab
-------------
id	database	retention_policy	shard_group	start_time		end_time		expiry_time		owners
7	openhab		default			7		2016-02-22T00:00:00Z	2016-02-29T00:00:00Z	2016-08-29T00:00:00Z	1
12	openhab		default			12		2016-02-29T00:00:00Z	2016-03-07T00:00:00Z	2016-09-05T00:00:00Z	1
```

The end time of shard 7 corresponds to the data point returned by the < operator mentioned above. I don't think the query result should depend on the internal DB structuring though.

(Please let me know if I'm missing something)

**Comment by joelegasse** [comment]
@maniac103 This sounds similar to an issue solved by #5996. Can you try this with the 0.11 release candidate and see if the problem still exists?

**Comment by maniac103** [comment]
@joelegasse Are there deb packages of the RC available by any chance?

**Comment by joelegasse** [comment]
Yes, they are available on the download site: https://influxdata.com/downloads/

**Comment by maniac103** [comment]
Thanks, I missed the 'sections' selector. I'll give it a test and let you know.

**Comment by maniac103** [comment]
Looks like it's working. I get the correct data point now even with recent data.
