### ISSUE TITLE
InfluxDB - Admin interface showing different version number.

### ISSUE THREAD

**Issue by bugcy013** [influxdata/influxdb#5919]
Hi Guys,

Have installed influxdb 0.10.2 version installed via, debian package.

After installation, Admin interface show different version number [ InfluxDB v0.10.0 ], also Documentation links pointing to version version [ https://influxdb.com/docs/v0.9/introduction/getting_started.html ]

dhana013@HP-ProBook-4430s ~> dpkg -l |grep influx
ii  influxdb                                                    0.10.2-1                                            amd64        Distributed time-series database.
dhana013@HP-ProBook-4430s ~>

can you please check.

-Dhanasekaran.

**Comment by zstyblik** [comment]
Documentation link has been reported in #5906. PR for UI version is/was in https://github.com/influxdata/influxdb/pull/5901.

**Comment by jsternberg** [comment]
I'm going to use #5906 to track this.
