### ISSUE TITLE
InfluxDB binds on 127.0.0.1 only when using a custom hostname

### ISSUE THREAD

**Issue by sofixa** [influxdata/influxdb#5920]
Hello everybody.

When trying to setup a cluster, i found that my second and third node fail to connect to the first one. At first i thought it's a networking issue, but after running netstat, i noticed that InfluxDB binds only on 127.0.0.1:
```
root@mon.aws-eu-central-1-influxdb-01 ~ # netstat -nlpt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8091          0.0.0.0:*               LISTEN      16509/influxd
tcp        0      0 0.0.0.0:41343           0.0.0.0:*               LISTEN      5242/rpc.statd
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      5014/rpcbind
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      17462/nginx -g daem
tcp        0      0 127.0.0.1:8083          0.0.0.0:*               LISTEN      16509/influxd
tcp        0      0 127.0.0.1:8086          0.0.0.0:*               LISTEN      16509/influxd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      13947/sshd
tcp        0      0 127.0.0.1:8088          0.0.0.0:*               LISTEN      16509/influxd
tcp6       0      0 :::43074                :::*                    LISTEN      5242/rpc.statd
tcp6       0      0 :::111                  :::*                    LISTEN      5014/rpcbind
tcp6       0      0 :::80                   :::*                    LISTEN      17462/nginx -g daem
tcp6       0      0 :::22                   :::*                    LISTEN      13947/sshd
```

In my config file i have the following:

```
bind-address = "mon.aws-eu-central-1-influxdb-01.adm:8088"
  http-bind-address = "mon.aws-eu-central-1-influxdb-01.adm:8091"
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"
  cluster-tracing = false

[admin]
  enabled = true
  bind-address = "mon.aws-eu-central-1-influxdb-01.adm:8083"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

[http]
  enabled = true
  bind-address = "mon.aws-eu-central-1-influxdb-01.adm:8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
```

.adm is an internal resolvable zone that is properly configured. 

Is there any reason why InfluxDB is doing this or am i missing something in the configuration?

Thanks in advance,
Adrian

**Comment by e-dard** [comment]
@sofixa Hi, what version of Influx are you using, and what options are you passing to `influxd` when you start it on each node?

**Comment by sofixa** [comment]
I am using the latest version, 0.10.2.
I am not passing any options other than the default ones, here's the results of a ps faux | grep influx:

influxdb 20709  0.0  0.0  13224  2904 ?        Ss   12:38   0:00 /bin/sh -c /usr/bin/influxd -config /etc/influxdb/influxdb.conf  >>/dev/null 2>>/var/log/influxdb/influxd.log
influxdb 20713  0.2  0.2 290296 20048 ?        Sl   12:38   0:00  \_ /usr/bin/influxd -config /etc/influxdb/influxdb.conf

**Comment by e-dard** [comment]
@sofixa you need to provide the join args for all nodes.

For example:

```
$ influxd -join mon.aws-eu-central-1-influxdb-01.adm:8091,mon.aws-eu-central-1-influxdb-02.adm:8091,mon.aws-eu-central-1-influxdb-03.adm:8091 -config /etc/influxdb/influxdb.conf
$ influxd -join mon.aws-eu-central-1-influxdb-01.adm:8091,mon.aws-eu-central-1-influxdb-02.adm:8091,mon.aws-eu-central-1-influxdb-03.adm:8091 -config /etc/influxdb/influxdb.conf
$ influxd -join mon.aws-eu-central-1-influxdb-01.adm:8091,mon.aws-eu-central-1-influxdb-02.adm:8091,mon.aws-eu-central-1-influxdb-03.adm:8091 -config /etc/influxdb/influxdb.conf
```

**Comment by sofixa** [comment]
I know that, but my second and third node say "Connection refused". While trying to debug that i noticed that on my first node InfluxDB is binding to 127.0.0.1, which explains the connection refused.

**Comment by sofixa** [comment]
Otherwise, for node 2 and 3 i have /etc/default/influxdb with the following contents:

`INFLUXD_OPTS="-join mon.aws-eu-central-1-influxdb-01.adm:8091"`

**Comment by e-dard** [comment]
@sofixa you need to have all nodes listed in the join option.

**Comment by sofixa** [comment]
Okay, i will fix that.

But either way my first node(as well as the other two) bind on 127.0.0.1 and they are unaccessible from the others. 

This is the message i get in the influxdb.log, and telnet fails with "Connection refused".

[metaclient] 2016/03/07 12:38:39 failure getting snapshot from mon.aws-eu-central-1-influxdb-01.adm:8091: Get http://mon.aws-eu-central-1-influxdb-01.adm:8091?index=14: dial tcp 10.255.144.17:8091: connection refused

**Comment by jackzampolin** [comment]
@sofixa This sounds like the port is being blocked by an AWS [security group](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html). Closing this issue.
