### ISSUE TITLE
show continuous query returns no results in web admin.

### ISSUE THREAD

**Issue by michalg42** [influxdata/influxdb#5922]
Hello
I think I found one small bug in Web admin. :)
I created continuous query in web admin and then I wanted to display it. Unfortunetely when I execute query "show continuous query" I got "Query returned no results!", yet when executed in terminal it showed mi three different results, so I guess there is something wrong with Web admin.

**Comment by zstyblik** [comment]
I'd say this is a duplicate of https://github.com/influxdata/influxdb/issues/4688.

**Comment by jsternberg** [comment]
This appears to be fixed with the new query engine and with the issue mentioned above.
