### ISSUE TITLE
Mean if_octets from multiple hosts

### ISSUE THREAD

**Issue by kamsz** [influxdata/influxdb#5923]
I'm trying to receive mean from all hosts if_octets field feeded from collectd with an example Grafana query:

```
SELECT non_negative_derivative(mean("value"), 1s) FROM "interface_rx" WHERE "instance" = 'br-mgmt' AND "type" = 'if_octets' AND "host" =~ /node-[1-7]/ AND $timeFilter GROUP BY time($interval)
```

This results in very big values that are not real... When I add host to the GROUP BY clause, it works fine.

**Comment by kamsz** [comment]
any update on this issue?

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list.

Thanks.
