### ISSUE TITLE
show measurement limit?

### ISSUE THREAD

**Issue by flyersa** [influxdata/influxdb#5927]
Hello,

grafana doesnt show me all series after upgrading from 0.8 to 0.10. Seems that "show measurements" does not return all series. Is this so, why and how to fix it? ;)

**Comment by bergquist** [comment]
Hi folks! I'm also curious if this is a change in the API that we have to address or a bug.

Br
Carl

**Comment by toddboom** [comment]
@flyersa With v0.9.x and higher, underlying series are composed of measurements with tags. Issuing `SHOW MEASUREMENTS` will show you the base listing without the tags. Grafana should be pulling back the measurement list and allow you to filter by tags to get the same level of detail you would have seen in v0.8.x.

This doc should also help with differences between the versions:
https://docs.influxdata.com/influxdb/v0.9/concepts/08_vs_09/
