### ISSUE TITLE
Continuous Query no output on 1m

### ISSUE THREAD

**Issue by faisalusuf** [influxdata/influxdb#5931]
**Hi,**
I have a CQ which pulls bytes_sent and Bytes_recv for two NICs from net (using telegraf). The existing CQ is working fine and saving the measurements separately.

When im trying to extract data group by 1m then no output is show but > 1m works well

No Output:
select bytes_sent_em1, bytes_recv_em2 FROM bytes_math where time > now() -*\* 1m**

**2m Worked:**

> select bytes_sent_em1, bytes_recv_em2 FROM bytes_math where time > now() - **2m**
> ## name: bytes_math
> 
> time                    bytes_sent_em1          bytes_recv_em2
> 1457415600000000000     1.0582505365666666e+10
> 1457415600000000000                             7.287051383666667e+09

Thanks

**Comment by zstyblik** [comment]
@faisalusuf, could it be there are no data for `time > now() - 1m`? I mean, such query works just fine for me. Although on different dataset, of course.

**Comment by faisalusuf** [comment]
But it is showing data with time > now() - 2m:
name: bytes_math
----------------
time                    value
1457426442913217136     3.341223074666667e+09

**Comment by zstyblik** [comment]
```
[ 2m, data are here ( ... 1m, no data here...)]
```

Then `time - now() - 2m` would return data, but `time - now() - 1m` wouldn't. That was my point. Have you inspected timestamps of the data points?

**Comment by faisalusuf** [comment]
how to check that?

**Comment by zstyblik** [comment]
`select bytes_sent_em1, bytes_recv_em2 FROM bytes_math where time > now() - 2m` and check the timestamps?

**Comment by faisalusuf** [comment]
Here is the output:
> select bytes_sent_em1, bytes_recv_em2 FROM bytes_math where time > now() - 2m

name: bytes_math
----------------
time                    bytes_sent_em1          bytes_recv_em2
1457787960000000000     1.5610961183333334e+08
1457787960000000000                             4.632437011666667e+08

> select bytes_sent_em1, bytes_recv_em2 FROM bytes_math where time > now() - 2m

name: bytes_math
----------------
time                    bytes_sent_em1          bytes_recv_em2
1457787960000000000     1.5610961183333334e+08
1457787960000000000                             4.632437011666667e+08
