### ISSUE TITLE
Continuous Query no another Continuous Query

### ISSUE THREAD

**Issue by faisalusuf** [influxdata/influxdb#5932]
Hi,
I have the following two CQs, when i try to create another CQ the query creates but i cannot see any measurement nor any output:

**CQ1:** CREATE CONTINUOUS QUERY bytes_sent_1min_em1 ON telegraf BEGIN SELECT mean("bytes_sent") as bytes_sent_em1 INTO bytes_math FROM net WHERE "interface" = 'em1' GROUP BY time(1m), \* END
**CQ2:** CREATE CONTINUOUS QUERY bytes_recv_1min_em2 ON telegraf BEGIN SELECT mean("bytes_recv") as bytes_recv_em2 INTO bytes_math FROM net where "interface" = 'em2' GROUP BY time(1m), \* END

The above CQ is working fine and i can see measurement:

> show measurements
> ## name: measurements
> 
> name
> **bytes_math**

When i created another CQ:

**CQ3:** CREATE CONTINUOUS QUERY bytes_save_1min ON telegraf BEGIN SELECT mean("bytes_sent_em1") - mean("bytes_recv_em2") as bytes_saved INTO bytes_saving FROM bytes_math GROUP BY time(2m), \* END

There is no measurement with name "bytes_saving" nor any output:

> show measurements
> ## name: measurements
> 
> name
> bytes_math
> cpu
> disk
> diskio
> mem
> net
> swap
> system
> 
> select mean(value) from bytes_saving where time > now() - 5m group by time(60s)
> 
> No errors in the influxDB logs. What happened to the query then?

Thanks
f.

**Comment by zstyblik** [comment]
@faisalusuf, have you tried to execute:

```
SELECT mean("bytes_sent_em1") - mean("bytes_recv_em2") as bytes_saved FROM bytes_math GROUP BY time(2m), *
```

from web interface? What version of InfluxDB are you using? Do you see CQ `bytes_save_1min` being scheduled and executed in logs? Does it show up in `SHOW CONTINUOUS QUERIES`?

**Comment by faisalusuf** [comment]
Im using CLI not the web interface. The query you have suggested is failed.

> SELECT mean("bytes_sent_em1") - mean("bytes_recv_em2") as bytes_saved FROM bytes_math GROUP BY time(2m), *
ERR: error parsing query: aggregate functions with GROUP BY time require a WHERE time clause

Worked Query:
> SELECT mean("bytes_sent_em1") - mean("bytes_recv_em2") as bytes_saved FROM bytes_math WHERE time > now() - 2m
name: bytes_math
----------------
time                    bytes_saved
1457426636308110338     3.341568537666666e+09

**Comment by faisalusuf** [comment]
Any update on this ?

**Comment by faisalusuf** [comment]
Some please guide me how to perform the desired calculation?

**Comment by 26huitailang** [comment]
I got the same problem.

CQ:
```
> show continuous queries
name: testdb
------------
name	query
cq_30m	CREATE CONTINUOUS QUERY cq_30m ON testdb BEGIN SELECT sum(value) INTO testdb.autogen.org_stream30m FROM testdb.autogen.org_stream GROUP BY time(30m) END
cq_1h	CREATE CONTINUOUS QUERY cq_1h ON testdb RESAMPLE EVERY 3m BEGIN SELECT sum(value) INTO testdb.autogen.org_stream1h FROM testdb.autogen.org_stream GROUP BY time(1h) END
```

I created 2 cqs, but I can't see the new measurements.
```
> show measurements

name: measurements
------------------
name
org_stream
```
