### ISSUE TITLE
Query Management Support

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#5939]
This is a tracking issue for discussion related to query management.  See #655 #654 #5838.

**Comment by jsternberg** [comment]
I've gotten support for displaying running queries with `SHOW QUERIES` and modified the query language to allow saying `KILL QUERY <number>`, but the second isn't fully implemented in a way that works well.

First, in the current query engine, the interrupt will only take place after the first row gets emitted (name/tag combination). It also will not interrupt in the middle of calculating a query. We might have to add interrupt points inside of the iterator to get this functionality to interrupt a count in the middle of calculation, but that may result in slower aggregations.

I'll have to benchmark some attempts to see what happens.

**Comment by jwilder** [comment]
Related to query limits: #6024
