### ISSUE TITLE
query data with future date

### ISSUE THREAD

**Issue by FlorianLudwig** [influxdata/influxdb#5940]
Influx seems to not return data in queries that are in the future.  Having the database depend on the servers clock is unexpected behavior.

```
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE test"

curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64 1581508800000000000'

curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=test" --data-urlencode "q=SELECT value FROM cpu_load_short WHERE time > now()"
```

**Comment by rossmcdonald** [comment]
@FlorianLudwig If an upper bound is not specified, then InfluxDB assumes you mean `time < now()`. Are you still not getting results if you specify an upper bound in the future? For example:

```
SELECT value FROM cpu_load_short WHERE time > now() and time < now() + 1d
```

(assuming your point is less than one day in the future)

**Comment by FlorianLudwig** [comment]
@rossmcdonald indeed that works.  This is unexpected though.  Maybe this should be documented - or did I just miss it reading the docs?

**Comment by rossmcdonald** [comment]
@FlorianLudwig Querying values in the future is not a typical use-case, so you have to be explicit about the upper bounds.This is documented [here](https://docs.influxdata.com/influxdb/v0.10/troubleshooting/frequently_encountered_issues/#querying-after-now).
