### ISSUE TITLE
0.10.1 cluster failed when it's binding address configured to listen on all interfaces.

### ISSUE THREAD

**Issue by jeyan123** [influxdata/influxdb#5941]
I have installed influxdb on 3 servers(a,b,c) and configure the binding address to listening on particular IP-Address, It formed the cluster and worked without any issue.

[meta]
  # Controls if this node should run the metaservice and participate in the Raft group
  enabled = true
  # Where the metadata/raft database is stored
  dir = "/var/lib/influxdb/meta"
  bind-address = "192.168.34.3:8088"
  http-bind-address = "192.168.34.3:8091"

[http]
  enabled = true
  bind-address = "192.168.34.3:8086"

I have changed the binding address to listen on all the interfaces
[meta]
  # Controls if this node should run the metaservice and participate in the Raft group
  enabled = true
  # Where the metadata/raft database is stored
  dir = "/var/lib/influxdb/meta"
  bind-address = ":8088"
  http-bind-address = ":8091"

[http]
  enabled = true
  bind-address = ":8086"

It could't form the cluster and failed. Is there a way to configure to listen on all interfaces.

**Comment by rossmcdonald** [comment]
@jeyan123 The only way I know how to bind to all interfaces is to modify your `/etc/hosts` file so that the hostname of the machine is pointing to `0.0.0.0`. For example, if your hostname is `influx1`, your `/etc/hosts` file should look like:

```
127.0.0.1 localhost localhost.localdomain
0.0.0.0 influx1
```

And then update the configuration to use the hostname instead of the IP address for every `bind-address`, so:

```
[meta]
# Controls if this node should run the metaservice and participate in the Raft group
enabled = true
# Where the metadata/raft database is stored
dir = "/var/lib/influxdb/meta"
bind-address = "influx1:8088"
http-bind-address = "influx1:8091"

[http]
enabled = true
bind-address = "influx1:8086"
```

**Comment by jeyan123** [comment]
Thanks rossmcdonald,
Cluster is partially working now. 
Issues
1) Query(data read) fails sometimes, if one of the node goes down. ( checking for meta service from 'Not running node' ) -dial tcp 172.16.96.16:8088: connection refused
2) fail to start services sometimes (::8083, ::8091, ::8086, ::8088)
3) 'Data Write' waits, if one of the node goes down.

**Comment by rossmcdonald** [comment]
@jeyan123 What does the output of a `SHOW SERVERS` look like? It sounds like the IP's are still being used for some reason.

**Comment by jeyan123** [comment]
> show servers;
name: data_nodes
----------------
id	http_addr	tcp_addr
1	influxdb1:8086	influxdb1:8088
3	influxdb2:8086	influxdb2:8088
5	influxdb3:8086	influxdb3:8088


name: meta_nodes
----------------
id	http_addr	tcp_addr
1	influxdb1:8091	influxdb1:8088
2	influxdb2:8091	influxdb2:8088
4	influxdb3:8091	influxdb3:8088

=====
influxdb1 - 172.16.96.16

**Comment by jsternberg** [comment]
Clustering [has been removed](https://influxdata.com/blog/update-on-influxdb-clustering-high-availability-and-monetization/) from the open source version so I'm going to close this issue.
