### ISSUE TITLE
[0.10.2] Point not queryable from other nodes once written to cluster

### ISSUE THREAD

**Issue by eivindsarto** [influxdata/influxdb#5942]
Configuring influxdb-0.10.x to listen on all interfaces does not work correctly:
[http]
    bind-address = ":8086"

However, certain operations work and others do not.
A "CREATE DATABASE mydb" works and querying "SHOW DATABASES" from all nodes in cluster shows that the database has been created.

But, when writing a point to one of the nodes, the point cannot be queried from any other node than where it was written.  The point is not getting replicated.

If I configure http.bind-address = "node1:8086", "node2:8086", "node3:8086" for each node in cluster, everything works as expected.  But, I can then only query influxdb on a single interface.

Ubuntu 14.04 and influxdb-0.10.[012]

**Comment by rossmcdonald** [comment]
There seem to be two issues here, the binding on all interfaces issue is a dupe of #5941. Regarding the points not being queryable from different instances, that sounds like a bug. Have you checked the logs for any cluster-related messages or failures?

**Comment by eivindsarto** [comment]
This is not exactly a dupe of #5941.
#5941 attempts to configure meta-service (port 8088 and 8091) to listen on all interfaces, which fails to form a cluster.

This bug only configures port 8086 to listen on all interfaces.  The difference between listening on the [meta] ports and the [http] port, is that your meta-config-code will substitute a blank hostname with localhost. Meta.bind-address=":8088" gets translated to net.Listen("tcp", "localhost:8088").  (That is why the cluster fails to form in #5941.)   But, http.bind-address=":8086" will pass along a blank hostname  to net.Listen("tcp", ":8086), which indeed causes the http-API to listen on all interfaces.

After digging a bit deeper, I think I have found the source of the problem.  When configuring [http].bind-address with a blank hostname, the default retention policy is 1.  When specifying a  hostname, the default retention policy is 3.  And that exxplains why my points are not being replicated.

This shows the difference when configuring without and with a hostname:

[http].bind-address = ":8086"
# influx -host node0
Connected to http://node0:8086 version 0.10.2
InfluxDB shell 0.10.2
> CREATE DATABASE mydb
> SHOW RETENTION POLICIES ON mydb
name    duration        replicaN        default
default 0               1               true


[http].bind-address = "node0:8086"
# influx -host node0
Connected to http://node0:8086 version 0.10.2
InfluxDB shell 0.10.2
> CREATE DATABASE mydb
> SHOW RETENTION POLICIES ON mydb
name    duration        replicaN        default
default 0               3               true

Why would the default retention policy be different depending on how I configure [http].bind-adddress?
