### ISSUE TITLE
how to implement query caching ?

### ISSUE THREAD

**Issue by deepujain** [influxdata/influxdb#5946]
My data changes once everyday, how do i implement caching ?

**Comment by BrannonKing** [comment]
You need a lot more description here. Your data changes or your query changes? And by "changes"
 you mean that you want to right new values, right?

**Comment by deepujain** [comment]
I ingest new data into system every 24 hours. In that 24 hour period my dashboard does multiple groupBy queries that take 10 seconds to show up the result from a single node influxDB server.

If the results could be cached over 24 hours then it can speed up the dashboards. After 24 hours the cache should be invalid.

Cache should go invalid after 24 hours irrespective if the data changed or not.

**Comment by jwilder** [comment]
@deepujain This question is better to ask on the [mailing list](https://groups.google.com/forum/#!forum/influxdb).
