### ISSUE TITLE
[0.10.1] panic when using MEAN on bool series

### ISSUE THREAD

**Issue by njoyard** [influxdata/influxdb#5947]
Running 0.10.1 on Windows 2008 Server R2, home built. Query executed:

```sql
SELECT mean(value) AS value FROM faults
WHERE device = '1' AND value_id = 'analog_in1'
AND time > '2016-03-09T14:53:48Z' AND time <= '2016-03-09T14:54:48Z'
GROUP BY time(300ms) fill(none)
```

Log output:
```
panic: unsupported mean iterator type: *influxql.booleanMergeIterator
```

Stack traces that follow are available [here on pastebin](http://pastebin.com/sQinP0a3).

I know doing MEANs on a boolean series is not supposed to return anything meaningful, however I think InfluxDB should not panic when it happens, but return a HTTP error response instead.

**Comment by jsternberg** [comment]
Looks like this is fixed in the upcoming 0.11.

```
> insert bools value=t
> select mean(value) from bools
ERR: unsupported mean iterator type: *influxql.booleanMergeIterator
```

Can you try it out from the 0.11 or master branch?

**Comment by njoyard** [comment]
Thanks, I will as soon as I have some time.

**Comment by jsternberg** [comment]
Ok, I'm going to close this for now as it appears to be fixed. Please reopen if you find this is still a problem.

**Comment by curry684** [comment]
It seems this has returned in 1.2?  Just a different exception now:

> unsupported mean iterator type: *influxql.booleanInterruptIterator

**Comment by ricco24** [comment]
Any advance here?
