### ISSUE TITLE
[0.10.0] - Single quote on SELECT 'value' causes panic

### ISSUE THREAD

**Issue by sstarcher** [influxdata/influxdb#5949]
Single quotes around SELECT 'blah' causes a panic.

`SELECT 'available_percent' FROM "mem" WHERE time > now() - 5m`

https://gist.github.com/sstarcher/ae57e3c405fb12251ab7

**Comment by e-dard** [comment]
Thanks for the report @sstarcher 

/cc @benbjohnson
