### ISSUE TITLE
[0.10.2] Continuous queries slowly 'fading away'

### ISSUE THREAD

**Issue by KiNgMaR** [influxdata/influxdb#5951]
Hi everyone,

we suffer from the following issue in a single-node setup. Some meta information:

* 2016/03/09 07:37:12 InfluxDB starting, version 0.10.2, branch 0.10.0, commit 845ce867189724762a6637f17da742f2ca0a9625, built 2016-03-03T22:05:35.507486
* 2016/03/09 07:37:12 Go version go1.4.3, GOMAXPROCS set to 8
* CentOS 6.7
* 8 CPU Cores
* 16 GB RAM

I wiped all meta data and data this morning and performed a clean install of 0.10.2. After that, I created 7 continuous queries as follows:

* cq_xxx_rows_per_minute_total	"CREATE CONTINUOUS QUERY cq_xxx_rows_per_minute_total ON xxx_prod RESAMPLE EVERY 30s FOR 1m BEGIN SELECT sum(num_xxxs) INTO xxx_prod."default".cq_xxx_rows_per_minute_total FROM xxx_prod."default".xxx_requests GROUP BY time(1m) END"
* cq_yyy_requests_per_minute_method	"CREATE CONTINUOUS QUERY cq_yyy_requests_per_minute_method ON xxx_prod RESAMPLE EVERY 30s FOR 1m BEGIN SELECT count("duration") INTO xxx_prod."default".cq_yyy_requests_per_minute_method FROM xxx_prod."default".yyy_requests GROUP BY time(1m), method END"
* cq_xxx_requests_per_minute_server	"CREATE CONTINUOUS QUERY cq_xxx_requests_per_minute_server ON xxx_prod RESAMPLE EVERY 30s FOR 1m BEGIN SELECT count("duration") INTO xxx_prod."default".cq_xxx_requests_per_minute_server FROM xxx_prod."default".xxx_requests GROUP BY time(1m), "server" END"
* cq_xxx_requests_mean_duration_15s	"CREATE CONTINUOUS QUERY cq_xxx_requests_mean_duration_15s ON xxx_prod RESAMPLE EVERY 15s FOR 30s BEGIN SELECT mean("duration") INTO xxx_prod."default".cq_xxx_requests_mean_duration_15s FROM xxx_prod."default".xxx_requests WHERE error = '0' GROUP BY time(15s) END"
* cq_xxx_requests_min_duration_15s	"CREATE CONTINUOUS QUERY cq_xxx_requests_min_duration_15s ON xxx_prod RESAMPLE EVERY 15s FOR 30s BEGIN SELECT min("duration") INTO xxx_prod."default".cq_xxx_requests_min_duration_15s FROM xxx_prod."default".xxx_requests WHERE error = '0' GROUP BY time(15s) END"
* cq_xxx_requests_max_duration_15s	"CREATE CONTINUOUS QUERY cq_xxx_requests_max_duration_15s ON xxx_prod RESAMPLE EVERY 15s FOR 30s BEGIN SELECT max("duration") INTO xxx_prod."default".cq_xxx_requests_max_duration_15s FROM xxx_prod."default".xxx_requests WHERE error = '0' GROUP BY time(15s) END"
* cq_xxx_requests_95pct_duration_15s	"CREATE CONTINUOUS QUERY cq_xxx_requests_95pct_duration_15s ON xxx_prod RESAMPLE EVERY 15s FOR 30s BEGIN SELECT percentile("duration", 95.000) INTO xxx_prod."default".cq_xxx_requests_95pct_duration_15s FROM xxx_prod."default".xxx_requests WHERE error = '0' GROUP BY time(15s) END"

For the first few minutes, all queries have been executing as desired:

* [continuous_querier] 2016/03/09 07:42:30 executing continuous query cq_xxx_requests_95pct_duration_15s (2016-03-09 07:42:15 +0100 CET to 2016-03-09 07:42:30 +0100 CET)
* [continuous_querier] 2016/03/09 07:42:30 executing continuous query cq_xxx_requests_95pct_duration_15s (2016-03-09 07:42:00 +0100 CET to 2016-03-09 07:42:15 +0100 CET)
* [continuous_querier] 2016/03/09 07:42:45 executing continuous query cq_xxx_requests_mean_duration_15s (2016-03-09 07:42:30 +0100 CET to 2016-03-09 07:42:45 +0100 CET)
* [continuous_querier] 2016/03/09 07:42:45 executing continuous query cq_xxx_requests_mean_duration_15s (2016-03-09 07:42:15 +0100 CET to 2016-03-09 07:42:30 +0100 CET)

As we can see, the timestamps in the log and the time spans for the query execution line up nicely.

Fast-forward 5 hours.

* [continuous_querier] 2016/03/09 12:42:22 executing continuous query cq_xxx_requests_95pct_duration_15s (2016-03-09 12:41:15 +0100 CET to 2016-03-09 12:41:30 +0100 CET)
* [continuous_querier] 2016/03/09 12:42:24 executing continuous query cq_xxx_requests_95pct_duration_15s (2016-03-09 12:41:00 +0100 CET to 2016-03-09 12:41:15 +0100 CET)
* [continuous_querier] 2016/03/09 12:42:26 executing continuous query cq_xxx_requests_95pct_duration_15s (2016-03-09 12:40:45 +0100 CET to 2016-03-09 12:41:00 +0100 CET)
* [continuous_querier] 2016/03/09 12:42:28 executing continuous query cq_xxx_requests_95pct_duration_15s (2016-03-09 12:40:30 +0100 CET to 2016-03-09 12:40:45 +0100 CET)
* [continuous_querier] 2016/03/09 12:42:32 executing continuous query cq_xxx_rows_per_minute_total (2016-03-09 12:42:00 +0100 CET to 2016-03-09 12:43:00 +0100 CET)
* [continuous_querier] 2016/03/09 12:42:34 executing continuous query cq_xxx_rows_per_minute_total (2016-03-09 12:41:00 +0100 CET to 2016-03-09 12:42:00 +0100 CET)

We can observe that the timestamps in the log and the timestamps for the execution have drifted apart.

Fast-forward another 5 hours.

* [continuous_querier] 2016/03/09 17:13:12 executing continuous query cq_xxx_requests_min_duration_15s (2016-03-09 16:25:00 +0100 CET to 2016-03-09 16:25:15 +0100 CET)
* [continuous_querier] 2016/03/09 17:13:18 executing continuous query cq_xxx_requests_min_duration_15s (2016-03-09 16:24:45 +0100 CET to 2016-03-09 16:25:00 +0100 CET)
* [continuous_querier] 2016/03/09 17:13:24 executing continuous query cq_xxx_requests_max_duration_15s (2016-03-09 16:49:00 +0100 CET to 2016-03-09 16:49:15 +0100 CET)
* [continuous_querier] 2016/03/09 17:13:29 executing continuous query cq_xxx_requests_max_duration_15s (2016-03-09 16:48:45 +0100 CET to 2016-03-09 16:49:00 +0100 CET)

Now the timestamps are completely out of sync. InfluxDB appears to be recalculating data from 50 minutes ago.

Now let's check the frequency of log entries like:

     [meta] 2016/03/09 16:49:15 127.0.0.1 - - [09/Mar/2016:16:49:15 +0100] GET /lease?name=continuous_querier&nodeid=1 HTTP/1.1 200 108 - Go 1.1 package http 79bb3505-e60e-11e5-bd7d-000000000000 327.56µs

A command like `grep lease /var/log/influxdb/influxd.log | grep -oP ' \d\d:\d\d:\d\d 127' | cut -d ':' -f 1-2 | sort | uniq -c` shows the following output (full here: https://gist.github.com/KiNgMaR/c44a86b9b534e49ee00b):

     25  07:41
     66  07:42
     84  07:43
     59  07:44
     59  07:45
     59  07:46
     59  07:47
     59  07:48
     59  07:49
     59  07:50
     59  07:51
     59  07:52
     59  07:53
     58  07:54
     59  07:55
     58  07:56
    ...
      1  14:55
      1  14:58
      1  15:02
      1  15:05
      1  15:09
      1  15:13
      1  15:17
      1  15:22
      1  15:28
      1  15:34
      1  15:40
      1  15:48
      1  15:57
      1  16:09
      1  16:25
      1  16:49

I presume this is related to the issue.

Please let me know what I can do to assist in tracking this very inconvenient problem down.

Thanks!

**Comment by zstyblik** [comment]
I'd say this is a duplicate of https://github.com/influxdata/influxdb/issues/5415

**Comment by KiNgMaR** [comment]
Any news on this? I can't possibly be the only one having this issue :(

**Comment by KiNgMaR** [comment]
Name        : influxdb                     Relocations: /
        Version     : 0.13.0~n201604270800              Vendor: InfluxData
        Release     : 0                             Build Date: Wed 27 Apr 2016 10:04:20 AM CEST
        Install Date: Wed 27 Apr 2016 02:35:19 PM CEST      Build Host: 1702ebdb06c8
        Group       : default                       Source RPM: influxdb-0.13.0~n201604270800-0.src.rpm
        Size        : 55012905                         License: MIT

This issue persists ... #6462 apparently did not fix it:

    [continuous_querier] 2016/04/28 07:26:23 executing continuous query cq_xxx_requests_min_duration_15s (2016-04-28 04:53:00 +0200 CEST to 2016-04-28 04:53:15 +0200 CEST)

(look at the timestamps)

**Comment by KiNgMaR** [comment]
:8ball: Apparently fixed in 0.13!

**Comment by KiNgMaR** [comment]
It's back (still running 0.13) - but now only seems to appear under high(er) load :cry: 

    [continuous_querier]
    2016/06/09 10:16:03 executing continuous query cq_xxx_requests_max_duration_15s
    (2016-06-08 13:36:45 +0200 CEST to 2016-06-08 13:37:00 +0200 CEST)

**Comment by KiNgMaR** [comment]
Still happening in the latest nightly:

    [continuous_querier] 2016/06/16 07:54:54 executing continuous query cq_xxx_rows_per_minute_total (
    2016-06-16 01:48:00 +0200 CEST to 2016-06-16 01:49:00 +0200 CEST)

**Comment by beckettsean** [comment]
@KiNgMaR Isn't this a system resource issue? The CQs are scheduled, but cannot complete before the next batch runs, and thus the system is slowly falling behind?

**Comment by KiNgMaR** [comment]
Hey Sean, I can tell you once #6909 is implemented. :) When executed manually, each of the queries takes less than the interval time though.

**Comment by jiamc** [comment]
I encountered the exact same issue. I'm running a single node. System infos:
- InfluxDB version 0.14.0~n201605040800, branch master, commit f2bb9db1c59817fe6ada4b63a41c777dcb5e9369
- 24 CPU cores
- 32G RAM
- CentOS 7.2

The CQ definition is: `CREATE CONTINUOUS QUERY "cq_30s.errcode.ok" ON coreserver BEGIN SELECT count(proctm) AS "errcode.ok" INTO coreserver.rp_7d."errcode.ok.7d" FROM coreserver."default".cmd WHERE errcode = '0' GROUP BY time(30s) END`

From the CQ log. schedule time and execution time differ a lot, and the time gap gets larger as time goes by(not shown here). It happens for busy databases only(around 20k writes/s in my case)
```
[continuous_querier] 2016/07/13 17:48:38 executing continuous query cq_30s.errcode.ok (2016-07-13 17:00:00 +0800 SGT to 2016-07-13 17:00:30 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:39 executing continuous query cq_30s.errcode.ok (2016-07-13 16:59:30 +0800 SGT to 2016-07-13 17:00:00 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:39 executing continuous query cq_30s.errcode.ok (2016-07-13 16:59:00 +0800 SGT to 2016-07-13 16:59:30 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:39 executing continuous query cq_30s.errcode.ok (2016-07-13 16:58:30 +0800 SGT to 2016-07-13 16:59:00 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:40 executing continuous query cq_30s.errcode.ok (2016-07-13 16:58:00 +0800 SGT to 2016-07-13 16:58:30 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:40 executing continuous query cq_30s.errcode.ok (2016-07-13 16:57:30 +0800 SGT to 2016-07-13 16:58:00 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:41 executing continuous query cq_30s.errcode.ok (2016-07-13 16:57:00 +0800 SGT to 2016-07-13 16:57:30 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:41 executing continuous query cq_30s.errcode.ok (2016-07-13 16:56:30 +0800 SGT to 2016-07-13 16:57:00 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:42 executing continuous query cq_30s.errcode.ok (2016-07-13 16:56:00 +0800 SGT to 2016-07-13 16:56:30 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:43 executing continuous query cq_30s.errcode.ok (2016-07-13 16:55:30 +0800 SGT to 2016-07-13 16:56:00 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:43 executing continuous query cq_30s.errcode.ok (2016-07-13 16:55:00 +0800 SGT to 2016-07-13 16:55:30 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:44 executing continuous query cq_30s.errcode.ok (2016-07-13 16:54:30 +0800 SGT to 2016-07-13 16:55:00 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:44 executing continuous query cq_30s.errcode.ok (2016-07-13 16:54:00 +0800 SGT to 2016-07-13 16:54:30 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:45 executing continuous query cq_30s.errcode.ok (2016-07-13 16:53:30 +0800 SGT to 2016-07-13 16:54:00 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:45 executing continuous query cq_30s.errcode.ok (2016-07-13 16:53:00 +0800 SGT to 2016-07-13 16:53:30 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:46 executing continuous query cq_30s.errcode.ok (2016-07-13 16:52:30 +0800 SGT to 2016-07-13 16:53:00 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:46 executing continuous query cq_30s.errcode.ok (2016-07-13 16:52:00 +0800 SGT to 2016-07-13 16:52:30 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:47 executing continuous query cq_30s.errcode.ok (2016-07-13 16:51:30 +0800 SGT to 2016-07-13 16:52:00 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:47 executing continuous query cq_30s.errcode.ok (2016-07-13 16:51:00 +0800 SGT to 2016-07-13 16:51:30 +0800 SGT)
[continuous_querier] 2016/07/13 17:48:47 executing continuous query cq_30s.errcode.ok (2016-07-13 16:50:30 +0800 SGT to 2016-07-13 16:51:00 +0800 SGT)
```

@beckettsean I don't think CQ can't finish before next scheduled run. Reasons:
1. By directly executing the query `SELECT count(proctm) AS "errcode.ok" FROM coreserver."default".cmd WHERE errcode = '0' AND time > now() - 30s GROUP BY time(30s)`, it only takes 100ms.  
2. You may check the logs. Within a few seconds, all CQ scheduled between 16:50:30 and 17:00:30 are finished, and bizarrely in reverse order.

**Comment by jiamc** [comment]
Update: I upgraded to 1.0.0beta2, and CQ is normal now. I'll update again if the issue shows up again. Thanks!

**Comment by KiNgMaR** [comment]
Been running 1.0.0betaX for two weeks without any problems! Looks very good to me now!
