### ISSUE TITLE
[0.10.1] During heavy write load "panic: close of closed channel"

### ISSUE THREAD

**Issue by balopat** [influxdata/influxdb#5952]
We are experiencing every hour a panic under heavy write load. 

**Load:** 5-10/s single point HTTP writes
**Version:** 0.10.1
**Operating System:** RHEL 7.2

We will change to batching - still, this behaviour is unexpected. 
Also - not sure if related but this DB ended up having ~480 shards, which is unusually high! 
Due to the thousands of goroutines (is that normal?) the panic stacktrace is very long, so this is just a part of it, the full trace is attached:

[panic_extract.txt](https://github.com/influxdata/influxdb/files/165589/panic_extract.txt)

````
[http] 2016/03/09 09:07:30 10.31.19.98 - - [09/Mar/2016:09:07:30 -0500] POST /write?db=mfi&precision=ms HTTP/1.1 204 0 - - 434ea03f-e600-11e5-bcfc-000000000000 12.321949ms
[http] 2016/03/09 09:07:30 10.31.19.95 - - [09/Mar/2016:09:07:30 -0500] POST /write?db=mfi&precision=ms HTTP/1.1 204 0 - - 434f9dd3-e600-11e5-bcfd-000000000000 14.007668ms
[http] 2016/03/09 09:07:30 10.31.19.98 - - [09/Mar/2016:09:07:30 -0500] POST /write?db=mfi&precision=ms HTTP/1.1 204 0 - - 4354e0cd-e600-11e5-bcfe-000000000000 4.236114ms
[http] 2016/03/09 09:07:30 10.31.19.95 - - [09/Mar/2016:09:07:30 -0500] POST /write?db=mfi&precision=ms HTTP/1.1 204 0 - - 43679743-e600-11e5-bcff-000000000000 5.2858ms
[http] 2016/03/09 09:07:31 10.31.19.95 - - [09/Mar/2016:09:07:31 -0500] POST /write?db=mfi&precision=ms HTTP/1.1 204 0 - - 436c5a86-e600-11e5-bd00-000000000000 4.719698ms
[http] 2016/03/09 09:07:31 10.31.19.98 - - [09/Mar/2016:09:07:31 -0500] POST /write?db=mfi&precision=ms HTTP/1.1 204 0 - - 43b107b6-e600-11e5-bd01-000000000000 6.299786ms
[retention] 2016/03/09 09:07:31 retention policy shard deletion check commencing
panic: close of closed channel

goroutine 3985 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Close(0xc2083061e0, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:147 +0x3e
github.com/influxdb/influxdb/tsdb.(*Shard).close(0xc2083e9b80, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/shard.go:150 +0x54
github.com/influxdb/influxdb/tsdb.(*Shard).Close(0xc2083e9b80, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/shard.go:145 +0x89
github.com/influxdb/influxdb/tsdb.(*Store).DeleteShard(0xc20812c160, 0x247, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/store.go:134 +0xe4
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc2080f1f20)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/services/retention/service.go:130 +0x8ab
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x1b8

goroutine 1 [chan receive, 59 minutes]:
main.(*Main).Run(0xc20802d700, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cmd/influxd/main.go:96 +0x7a1
````

**Comment by joelegasse** [comment]
Hi @balopat. The panic should be fixed once https://github.com/influxdata/influxdb/pull/5514 gets merged.

Several compaction goroutines get created for each shard, and if you have 480 shards, then you'll have a few thousand goroutines.

Do you have an example point that you're writing? I notice you are setting the precision to `ms` in your writes. If you send over microseconds or nanoseconds, that could cause the timestamps to be off by a factor of 1000 or 1000000, which would explain the large number of shards being created.

**Comment by e-dard** [comment]
Fixed via #5514

**Comment by balopat** [comment]
Hey @joelegasse, thank you, looking forward to 0.11! (when is it planned for releasing?). re precision: good point, there were times we wrote at bad precision, now it's okay. I cleaned up the shards and will see if they grow back again - probably they won't.

**Comment by e-dard** [comment]
@balopat we're currently testing `0.11`. Expect a release soon!
