### ISSUE TITLE
Calculate derivative over intervals in which counters wrap

### ISSUE THREAD

**Issue by deathsoverture** [influxdata/influxdb#5954]
Possibly a duplicate to #549, but requires an enhancement to non_negative_derivative.  The current behavior (see #1477) is to drop negative values after calculating the derivatives between successive points.  Would it be possible actually calculate the diff using a known or provided maximum counter value?

The functionality should be similar to graphite's nonNegativeDerivative and openTSDB's counterMax  parameters for rate calculations.

There's also the question of how to handle counter resets.  OpenTSDB provides the resetValue option for rate calculations, and for graphite you can work around the issue with the removeAboveValue parameter.

Maybe there should be a way to store measurements as encoded ASN.1 types?  The maximum value for rate calculations on counters could be determined with the spec rather than manually provided.  Sorry if that is impossible, I am just throwing ideas out there.

**Comment by deathsoverture** [comment]
Please allow me to describe the use case.  I am currently storing snmpget results at 15-second intervals for IF-MIB::ifInOctets and IF-MIB::ifOutOctets for ROS hosts with tens of Mbps throughput on their network interface.  The Counter32 types reset reset a few times per hour, meaning if we are trying to display a throughput graph using these measurements, the data points at which the intervals reset will be missing.  The missing data is noticeable for 1-hour graphs divided into 15-second intervals.

![Octets Count](https://cloud.githubusercontent.com/assets/12052422/13792501/7fc607e0-eac8-11e5-90fd-5c0d7e4e8adf.png)
![Throughput](https://cloud.githubusercontent.com/assets/12052422/13792499/7cd44682-eac8-11e5-8669-48603903556f.png)

**Comment by joriws** [comment]
There are two most common options
- host reboot = counter starts again from 0
- counter wrap

Counter wrap can be determined if earlier derivate + most recent non-wrapped counter would go over 2**32-1. Counter wrap in derivate/difference is easy to adjust, add (2**32-1)-counter_value_before_wrap+counter_value_after_wrap and you have the difference of two measures 100% accurate and divide difference by time to get derivate.

host-reboot which makes counter restart from zero is only partially fixable. For difference the resetted counter value you go is not very accurate but only option is add new counter value to old value before the reset. If normal rate is 1000units/s and you get counter reset a second before new value is read you might get 1unit/s which is totally bad spike when around two 1000units/s. Interpolation is one option but for invoicing purposes not recommended.

**Comment by geoffgarside** [comment]
You'd need to know if it was a 32 bit counter or a 64 bit counter as well for correctly handling the counter wrap situation.

**Comment by joriws** [comment]
I know that's why MAX_COUNTER should be optional parameter for DIFFERENCE aggregator. With this I presume DERIVATE uses DIFFERENCE as a helper call
