### ISSUE TITLE
TLS Handshake Error

### ISSUE THREAD

**Issue by JauntyWard** [influxdata/influxdb#5958]
When attempting to use SSL on the api or admin interface I am unable to successfully negotiate a TLS connection. The server logs the following error:

2016/03/09 20:33:53 http: TLS handshake error from <IP>:<PORT>: tls: oversized record received with length <SIZE>

This occurs when attempting to connect to the admin interface via a web browser or when attempting to connect to the api using the Go and Python clients.

I receive no errors regarding the certificate or indeed any other errors of any type.

Steps to reproduce:
1) Set https-enabled=true in [admin] and [http]
2) Set https-certificate to custom certificate
3) start server and attempt to connect

**Comment by joelegasse** [comment]
@JauntyWard Are you including "https" at the beginning of the URL? I've seen that error in the past when an unencrypted HTTP connection is attempted on the secure port.

**Comment by JauntyWard** [comment]
Yes, that includes https in the URL.

**Comment by jsternberg** [comment]
The admin interface has been deprecated and removed. I am sorry we never addressed this, but I am going to close this since we are not going to work on it.
