### ISSUE TITLE
[0.11.0] Combining Selectors and Aggregators yields unexpected results

### ISSUE THREAD

**Issue by mjdesa** [influxdata/influxdb#5959]
To reproduce, use the data generated by `influx_stress` and insert one additional point into the `stress` database `cpu value=10000`.

Then run the following:

```
> select count(value) from cpu
name: cpu
---------
time	count
0	10000001
```

```
> select top(value,10) from cpu
name: cpu
---------
time			top
1136160010000000000	999
1136160010000000000	999
1136160010000000000	999
1136160010000000000	999
1136160010000000000	999
1136160010000000000	999
1136160010000000000	999
1136160010000000000	999
1136160010000000000	999
1457555935465088825	10000
```

```
> select count(value) + top(value,10) from cpu
name: cpu
---------
time	count_top
0	1.0001e+07

```

The result I expected was something along the lines of

```
> select count(value) + top(value,10) from cpu
name: cpu
---------
time	count_top
0	1.0001e+07
...
0	1.0001e+07
0	1.0001001e+07
```

or a parse error.

**Comment by mjdesa** [comment]
@benbjohnson @jsternberg thoughts?

**Comment by jsternberg** [comment]
I'm not sure you can use `top()` like that... An initial thought of what's happening is that `top()` is returning 10 points per interval while count is returning 1. If there are 10 intervals, that means the top iterator is returning 100 points while count is returning 10 at most. The counts for all 10 are going to be added to the top 10 points from the first interval and then the other 90 points from top will get cut off because that's how I designed the binary expression operators.

What's the expected output of this kind of query? What would the expected output of something like `top(value, 10) + top(value, 5)` be? We may just want to forbid this type of query.

**Comment by mjdesa** [comment]
@jsternberg I expected an error.

Other than simply forbidding this type of query, the only thing I can think of that is reasonable is treating the results of `top(value,n)` as a vector and allow for the usual things in a vector space. So `top(value,n)+top(value,m)` should yield an error for `m≠n` and `k * top(value,n)` is only valid for scalars `k`.

**Comment by jsternberg** [comment]
I think I'll make it into an error for now and we can talk about the other ones at a later time if there's demand.

**Comment by mjdesa** [comment]
:+1:

**Comment by jsternberg** [comment]
There may be another problem when it comes to any of the math functions. When doing the math, I assumed that both of the inputs would be returning the same times and values. This isn't true in a lot more cases than I realized. While `top()` and `bottom()` add a lot of complication to this and should likely just be forbidden, can you test a situation where you perform math on two different fields with one of those fields being missing from one of the points?

**Comment by mjdesa** [comment]
@jsternberg should I still test this?

**Comment by jsternberg** [comment]
Please do and verify that it isn't allowed. I've also got a few more PR's up for some issues with binary expressions.

**Comment by mjdesa** [comment]
There's some weirdness.  It seems like if the first field in a binary expression is null, the the result of the expression is null.

```
> insert cpu other_value=19,value=1
> insert cpu other_value=19
> insert cpu value=20
> insert cpu other_value=200,value=230
```

```
> select * from cpu
name: cpu
---------
time				other_value	value
2016-03-11T19:07:58.422857052Z	19		1
2016-03-11T19:08:06.070676215Z	19
2016-03-11T19:08:16.743569309Z			20
2016-03-11T19:08:31.928718324Z	200		230
```

```
> select value + other_value from cpu
name: cpu
---------
time				value_other_value
2016-03-11T19:07:58.422857052Z	20
2016-03-11T19:08:06.070676215Z
2016-03-11T19:08:16.743569309Z	20
2016-03-11T19:08:31.928718324Z	430
```

```
> select other_value + value from cpu
name: cpu
---------
time				other_value_value
2016-03-11T19:07:58.422857052Z	20
2016-03-11T19:08:06.070676215Z	19
2016-03-11T19:08:16.743569309Z
2016-03-11T19:08:31.928718324Z	430
```

**Comment by jsternberg** [comment]
I'm fixing that in #5990. Can you try out that PR to see if the result is more sane?

**Comment by mjdesa** [comment]
:+1:  

```
> select * from cpu
name: cpu
---------
time				other_value	value
2016-03-11T19:07:58.422857052Z	19		1
2016-03-11T19:08:06.070676215Z	19
2016-03-11T19:08:16.743569309Z			20
2016-03-11T19:08:31.928718324Z	200		230

> select other_value + value from cpu
name: cpu
---------
time				other_value_value
2016-03-11T19:07:58.422857052Z	20
2016-03-11T19:08:06.070676215Z	19
2016-03-11T19:08:16.743569309Z	20
2016-03-11T19:08:31.928718324Z	430

> select other_value + value from cpu
name: cpu
---------
time				other_value_value
2016-03-11T19:07:58.422857052Z	20
2016-03-11T19:08:06.070676215Z	19
2016-03-11T19:08:16.743569309Z	20
2016-03-11T19:08:31.928718324Z	430
```

**Comment by mjdesa** [comment]
Good to see that addition commutes :)
