### ISSUE TITLE
Continuous query may lose points with external timestamp

### ISSUE THREAD

**Issue by gl-works** [influxdata/influxdb#5966]
Based on my observations, influxdb fires a new query *IMMEDIATELY* when a new time range for a `CQ` rolls out. And for any given time range, the query fires just once - i.e., the time range is considered  closed for update after query is fired. This should work well as soon as no new points will be inserted into the time range later. And this is the case for measurements with influx's internal timestamp.

However, in case of measurements with external timestamp, it's not rare for points to arriving at a *closed* time range. The late points thus will never be touched by `CQ`.

Does the `CQ` support some 'latency' option to let the time range calm down before fires a new query?

**Comment by gl-works** [comment]
A further study shows this shoudn't be a problem as `CQ` already has supports for *resample*. Thanks for this good design. Owesome!

**Comment by dugwood** [comment]
A full example: https://github.com/influxdata/influxdb/issues/6932#issuecomment-383429731 (as I wander how to do it at first, got the same feeling of losing data!)
