### ISSUE TITLE
Tags are not returned in the result of query 

### ISSUE THREAD

**Issue by alifirat** [influxdata/influxdb#5967]
Hi guys, 

I have a simple set of data with 3 columns : time, channel (tag), value (field). What I'm trying to group the value by her channel tag. It's working well but I cannot understand why I didn't have the channel value in the query result. Here's the ouput : 

```
> show tag keys;
name: titi
----------
tagKey
channel
```

```
> select channel,value from titi where time > 1215525755000000000 and time < 1215525855000000000 GROUP BY channel limit 5;
name: titi
tags: channel=C3
time			value
----			-----
1215525755003906000	27.060000000000002
1215525755007813000	26.235000000000003
1215525755011719000	27.225
1215525755015625000	25.245
1215525755019531000	29.535

```

As you can see, the channel value C3 is not included in the query result. How I can fix that ?

**Comment by jsternberg** [comment]
The query you used is correct and seems to work in master.

```
> create database mydb
> use mydb
Using database mydb
> insert cpu,host=server01 value=1
> select value, host from cpu group by host
name: cpu
tags: host=server01
time                    value   host
----                    -----   ----
1457622148340454977     1       server01
```

This fix will be in 0.11 when it's released. Can you try it out to verify that it fixes your problem?

**Comment by jwilder** [comment]
Closing since this should be fixed in the current nightlies and 0.11 when released.

**Comment by alifirat** [comment]
@jwilder I try to install manually from the source but I met some problems when I execute the build script. As you said, it will be fixed so I will wait the next release. Thank you for your time !

**Comment by jwilder** [comment]
@alifirat You can download a nightly build as well and test that: https://influxdata.com/downloads/

**Comment by alifirat** [comment]
@jwilder I use the version 0.10.3, it should works as I excepted ?

**Comment by alifirat** [comment]
Hi, it's still not working. 

```
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.10.3
InfluxDB shell 0.11.0~n1458028842
```

```
> show tag keys;
name: t100000102_1215529325000000
---------------------------------
tagKey
channel
```

```
> select value, channel from t100000102_1215529325000000 group by channel limit 1
name: t100000102_1215529325000000
tags: channel=T6
time			value
----			-----
1215529325000000000	-1.155
```

Is it normal ?

**Comment by jsternberg** [comment]
Are you sure you're using either the nightly or compiling from master?

**Comment by alifirat** [comment]
From this link [https://influxdata.com/downloads/], there is a tab called "InfluxDB - Database Nightly Build" and I follow the instructions to install it.

**Comment by jsternberg** [comment]
You may need to restart your server. I don't know if that's done automatically. You can see from the output of `influx` this right here:

```
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
--> Connected to http://localhost:8086 version 0.10.3
InfluxDB shell 0.11.0~n1458028842
```

The server is still running 0.10.3.

**Comment by alifirat** [comment]
Thank you very much for you time ! It's works now ! I restarted the server and now I have the channels on the request.
