### ISSUE TITLE
Support math in aggregate calls

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#5971]
In #5968 the following query was tried and caused a panic:

```
SELECT non_negative_derivative(mean(created_tmp_tables - created_tmp_disk_tables), 1m) FROM tg_udp."default".mysql WHERE host = 'mysql02' AND time > 1457443029s AND time < 1457609873s GROUP BY time(1m)
```

We don't support this currently and #5970 forbids using anything other than a variable reference so the panic doesn't happen. But, this is a legitimate workflow and we should allow this kind of math for at least some calls such as mean.

**Comment by maded2** [comment]
any chance to put this on the roadmap so we know this is being considered

**Comment by rydeng** [comment]
How is it going now?

**Comment by jsternberg** [comment]
This can be worked around by using subqueries. I'm going to keep this open for now though because implementing it this way can potentially have a positive performance impact.

**Comment by jcmcken** [comment]
@jsternberg I'm not sure this is exactly the same situation. I'll create a separate issue if it's not.

In my case, I'm trying to graph the average NTP offset for some hosts. The offset can be both negative and positive, but I only care about the absolute value. Therefore I'd like to do something like:

```
select mean(abs("offset")) from "ntp" where time > now() - 3h group by time(5m) fill(null)
```

I've tried various permutations of subqueries and I don't get sensible results. I understand that doing ``abs(mean("offset"))`` is valid, but this isn't a useful computation in my case (half the measurements have negative values and half have positive values, so a straight average renders the data un-usable for measuring NTP offset)
