### ISSUE TITLE
[0.11.0] Match points between two iterators for binary math

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#5973]
Binary math is currently done by just reading each iterator and adding the next point from each one to the other. This kind of approach worked for one iterator against a literal because the literal never changed, but it doesn't work for two iterators because they could return different points from each other and become out of sync very easily.

Fix the binary math between two iterators to match the two sides with each other and handle skipped or mismatched points.

Related to #5959.

**Comment by jsternberg** [comment]
After thinking this over, I don't think this is an issue. I think if we just fix how the transform iterator handles nil points we'll be fine, but I do think we need to put an additional restriction on binary math.

1. Binary math between two aggregates is OK. They should have the same intervals and the same fill options so they should line up with each other.
2. Binary math with `top()`/`bottom()` is not OK (see #5959 for why).
3. Binary math with a non-existent value will return nil for all points and is OK. This currently needs to be fixed since it will just end early.
4. Mixing aggregates and fields in a binary expression is not OK since for similar reasons as why `top()` and `bottom()` is not OK.

@mjdesa does this sound OK? I'll put up a fix for 3 and 4 if it is. @pauldix when we have a non-existent value for a field in binary math, should that point be skipped or just treated as zero?

**Comment by pauldix** [comment]
@jsternberg do you have an example of the non-existent value you're talking about? I'm guessing it would be something like this:

```sql
select val1, val2 + 23 as vv2 from foo
```

Then if you have data like:

```
foo va1=1,val2=2 10
foo val1=3 20
```

I would expect the results to be:

```
1, 25, 10
1, nil, 20
```

**Comment by jsternberg** [comment]
Your example is what I was referring to. I implemented it to be the zero value, but I can change it to produce nil instead. So in your example, the output right now is:

```
1, 25, 10
1, 23, 20
```

**Comment by pauldix** [comment]
I think nil makes more sense. @jwilder, you have thoughts on this?

**Comment by jwilder** [comment]
I think `nil` would make it more clear that one of the values was missing.  I could go either way though.

**Comment by pauldix** [comment]
`nil` it is! :)
