### ISSUE TITLE
InfluxDB query costs

### ISSUE THREAD

**Issue by JavadMajidi** [influxdata/influxdb#5977]
Hi everyone, 
i need to calculate the query time cost on InfluxDB to compare it with other databases.
but i found nothing on influx log or anywhere.
can anyone please help me with that?

**Comment by zstyblik** [comment]
```
[http] 2016/03/05 02:48:46 172.17.0.1 - - [05/Mar/2016:02:48:46 +0000] GET /query?q=SHOW+FIELD+KEYS+FROM+cpu&db=telegraf HTTP/1.1 200 175 - python-requests/2.6.0 CPython/2.7.5 Linux/4.3.0-coreos c82e7bc1-e27c-11e5-a823-000000000000 690.896µs
```

**Comment by JavadMajidi** [comment]
but how should i have such output as result, i mean what was the command to get this result?

**Comment by zstyblik** [comment]
@JavadMajidi it's logged into log after response is sent to the client ;)

**Comment by JavadMajidi** [comment]
@zstyblik you mean influx log file, because my log file is empty, or i look at wrong location

**Comment by JavadMajidi** [comment]
@zstyblik i found it :)

**Comment by zstyblik** [comment]
@JavadMajidi cool! If your original question/issue has been resolved, please, close the issue. Thanks.

**Comment by z1q1q7** [comment]
i can't find the log file position, could you please tell me,,

**Comment by JavadMajidi** [comment]
for me it was in LOG directory in Linux, there is a Influx Log text file there. @z1q1q7
