### ISSUE TITLE
how to do 'SELECT LAST(*) FROM Msr GROUP BY time(1s) fill(previous)'?

### ISSUE THREAD

**Issue by BrannonKing** [influxdata/influxdb#5978]
I would like a query that dumps me all fields into CSV with every cell filled. I have a lot of fields (300-ish). I can write a program to query the list of fields and then generate the query. That just doesn't seem ideal.

**Comment by jsternberg** [comment]
I think it's reasonable to allow the wildcard syntax for some function calls like `last()`, but as a workaround, you can do something like this in the upcoming if you know at least one of the field names:

```
SELECT last(value), * FROM cpu
```

You'll have to remove the `last` column or ignore it, but it will get you what you want.

**Comment by BrannonKing** [comment]
Your usage of the * works as long as you don't put a limit on the query. It seems that adding limit (and also group by) causes some kind of infinite loop.

**Comment by beckettsean** [comment]
related to #5750, probably a dupe

**Comment by jsternberg** [comment]
Duplicate of #5750. Closing this since that's now implemented.
