### ISSUE TITLE
no data replicated in a cluster

### ISSUE THREAD

**Issue by lgarciaaco** [influxdata/influxdb#5987]
Hi guys,

I have a 3 nodes cluster, all hybrid. I see al nodes joined the cluster:

```
lgarciaac@influxdbbroker46-1:~$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.10.0
InfluxDB shell 0.10.0
> show servers;
name: data_nodes
----------------
id      http_addr       tcp_addr
1       localhost:8086  influxdbbroker46-1:8088


name: meta_nodes
----------------
id      http_addr               tcp_addr
1       influxdbbroker46-1:8091 influxdbbroker46-1:8088
2       influxdbbroker46-2:8091 influxdbbroker46-2:8088
3       influxdbbroker46-3:8091 influxdbbroker46-3:8088
```

Yet it is very strange that the only data node is the first node. I set the same config in all nodes enabling data.

```
[data]
  enabled = true
```

```
lgarciaac@influxdbbroker46-2:~$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.10.0
InfluxDB shell 0.10.0
> show servers;
name: data_nodes
----------------
id      http_addr       tcp_addr
1       localhost:8086  influxdbbroker46-1:8088


name: meta_nodes
----------------
id      http_addr               tcp_addr
1       influxdbbroker46-1:8091 influxdbbroker46-1:8088
2       influxdbbroker46-2:8091 influxdbbroker46-2:8088
3       influxdbbroker46-3:8091 influxdbbroker46-3:8088
```

The problem is, if I write the data in one node, I dont see it from the other. I played around different retention policies with replicaN equal to 1, 2 and 3, it didnt help.

**Comment by tsunam** [comment]
I tested with both 10.0-1 and 10.3-1 and both instances seem to not add the data_nodes correctly. Like the user above I add the enabled = true. Under both versions with a clean /var/lib/influxdb/[wal,data,meta] I create the environment on the first host, and then have the other two join after that. I see that the nodes are being added as meta_nodes but not as data_nodes.

**Comment by tsunam** [comment]
Hmm for some reason...and this isn't entirely clear but all three nodes are getting their ID set to 1 even when they are started at different times. I confirmed on a different cluster that each node is getting a different node.json ID number. In this cluster..each server is getting ID:1.

cat /var/lib/influxdb/meta/node.json
{"ID":1,"MetaServers":["influxdb-p18091","influxdb-p2:8091","influxdb-p3:8091"]}

**Comment by tsunam** [comment]
And just as oddly upgrading to 0.11.1 solved the issue in my case. Course this ticket is probably a bit null and void since per blog there's been a move away from the raft cluster method as the general clustering and most folks will go to the relay approach.
