### ISSUE TITLE
[0.10.0] Include tag values in response of last()

### ISSUE THREAD

**Issue by The-Nik** [influxdata/influxdb#5988]
Hi community,

sience the last updates of influxdb, I don't know how to solve this problem:

I want to create a query which repeats the last value of a series and its tag values. I don't want to have the tag values as seperated columns. I need them in the header to use them in Grafana as alias.

```
SELECT last("value"), max, min FROM airtemp
--> returns the tag values as columns.
```

```
SELECT last("values") FROM airtemp GROUP BY max, min
--> returns multiple series if there are more than one max/min-value in the whole airtemp-serie.
```

Can you give me a hint, whether this is possible with a influx query or whether I have to change Grafana code?
If you need more examples, please ask me.

Thanks,
Niklas

**Comment by BrannonKing** [comment]
+1. I've been struggling with this too.

**Comment by jsternberg** [comment]
@The-Nik can you give me an example of the output you want or expect?

**Comment by jsternberg** [comment]
I'm going to close this since more information hasn't been given about what is needed. Please reopen if you have more information. Thanks.
