### ISSUE TITLE
tcp.Mux: cannot read header byte: EOF?

### ISSUE THREAD

**Issue by lqx302** [influxdata/influxdb#5998]
version:0.10.1
cluster:4
two node log:
[tcp] 2016/03/12 11:09:41 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:09:56 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:10:11 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:10:26 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:10:41 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:10:56 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:11:11 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:11:26 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:11:41 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:11:56 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:12:11 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:12:26 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:12:41 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:12:56 tcp.Mux: cannot read header byte: EOF
[tcp] 2016/03/12 11:13:11 tcp.Mux: cannot read header byte: EOF

**Comment by lcrenix** [comment]
I got the same error after upgraded to V10.3.

[monitor] 2016/03/14 19:23:53 failed to store statistics: write failed: read message type: EOF
[write] 2016/03/14 19:23:53 write failed for shard 187 on node 3: read message type: EOF
[write] 2016/03/14 19:23:53 write failed for shard 188 on node 4: read message type: read tcp 10.44.87.160:10780->10.44.87.158:8088: read: connection reset by peer
[write] 2016/03/14 19:23:53 write failed for shard 190 on node 6: read message type: read tcp 10.44.87.160:45476->10.100.26.55:8088: read: connection reset by peer
[write] 2016/03/14 19:23:53 write failed for shard 193 on node 2: read message type: EOF
[write] 2016/03/14 19:24:03 write failed for shard 188 on node 4: read message type: read tcp 10.44.87.160:10819->10.44.87.158:8088: read: connection reset by peer
[monitor] 2016/03/14 19:24:03 failed to store statistics: write failed: read message type: read tcp 10.44.87.160:10819->10.44.87.158:8088: read: connection reset by peer
[write] 2016/03/14 19:24:03 write failed for shard 190 on node 6: read message type: EOF
[write] 2016/03/14 19:24:03 write failed for shard 187 on node 3: read message type: EOF
[write] 2016/03/14 19:24:03 write failed for shard 193 on node 2: read message type: EOF
[write] 2016/03/14 19:24:03 write failed for shard 191 on node 7: read message type: read tcp 10.44.87.160:27303->10.100.25.37:8088: read: connection reset by peer

with another errors:
[monitor] 2016/03/14 19:23:42 failed to store statistics: write failed: read message type: EOF
[write] 2016/03/14 19:23:42 write failed for shard 191 on node 7: read message type: read tcp 10.99.89.40:14490->10.100.25.37:8088: read: connection reset by peer
[write] 2016/03/14 19:23:42 write failed for shard 187 on node 3: read message type: EOF
[write] 2016/03/14 19:23:42 write failed for shard 190 on node 6: read message type: read tcp 10.99.89.40:27275->10.100.26.55:8088: read: connection reset by peer
[write] 2016/03/14 19:23:42 write failed for shard 188 on node 4: read message type: read tcp 10.99.89.40:55641->10.44.87.158:8088: read: connection reset by peer
[monitor] 2016/03/14 19:24:42 failed to set default retention policy on '_internal', failed to create internal storage: meta service returned 503 Service Unavailable
[write] 2016/03/14 19:24:42 write failed for shard 190 on node 6: read message type: read tcp 10.99.89.40:27494->10.100.26.55:8088: read: connection reset by peer
[monitor] 2016/03/14 19:24:42 failed to store statistics: write failed: read message type: read tcp 10.99.89.40:27494->10.100.26.55:8088: read: connection reset by peer
[write] 2016/03/14 19:24:42 write failed for shard 187 on node 3: read message type: EOF
[write] 2016/03/14 19:24:42 write failed for shard 193 on node 2: read message type: read tcp 10.99.89.40:38941->10.95.22.38:8088: read: connection reset by peer
[write] 2016/03/14 19:24:42 write failed for shard 191 on node 7: read message type: read tcp 10.99.89.40:14713->10.100.25.37:8088: read: connection reset by peer
[write] 2016/03/14 19:24:42 write failed for shard 188 on node 4: read message type: read tcp 10.99.89.40:55864->10.44.87.158:8088: read: connection reset by peer

**Comment by lcrenix** [comment]
And also found these:
[tcp] 2016/03/14 19:24:13 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:24:23 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:24:33 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:24:35 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:24:42 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:24:43 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:24:48 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:24:53 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:25:03 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:25:13 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:25:23 tcp.Mux: handler not registered: 2
[tcp] 2016/03/14 19:25:33 tcp.Mux: handler not registered: 2

**Comment by supershal** [comment]
@lqx302 do you have load balancer in front of your influxdb instances? I noticed those errors when my load  balancer was doing health check on port 8086 over TCP. 
OR You have some node sending empty data over 8086 over TCP.

If thats the case, please use health check url to HTTP ":8086/ping" .
Unfortunately this returns status code 204. The amazon ELB HTTP health check point only understands 200 ok. So if your load balancer can understand, use ":8086/ping".

**Comment by lcrenix** [comment]
@supershal Yes, I have a load balance server (nginx) in front of my influxdb instance. Now I know the reason, thank you !

**Comment by joelegasse** [comment]
This issue appears to have been resolved, with the cause being external to InfluxDB. If this is incorrect, please let me know and we can re-visit this issue.

**Comment by lqx302** [comment]
Thanks！restart the clustering this issue not appear again.

**Comment by garimallac** [comment]
> @supershal Yes, I have a load balance server (nginx) in front of my influxdb instance. Now I know the reason, thank you !

what is the reason for ''tcp.Mux: cannot read header byte: EOF''

**Comment by cgarimelladev** [comment]
> This issue appears to have been resolved, with the cause being external to InfluxDB. If this is incorrect, please let me know and we can re-visit this issue.

@joelegasse i am facing same issue, what is the reason for this issue?

did you find any resolution for this?
