### ISSUE TITLE
handoff always say failed to determine if node X is active

### ISSUE THREAD

**Issue by lcrenix** [influxdata/influxdb#6014]
I have a 7-nodes cluster, after upgraded to the 10.3, I always got some errors in the log, say:
 [handoff] 2016/03/15 14:45:02 failed to determine if node 9 is active: node not found
[handoff] 2016/03/15 14:45:02 failed to determine if node 13 is active: node not found
[handoff] 2016/03/15 14:45:02 failed to determine if node 11 is active: node not found

the show servers command shows only 7 boxes, so why it try to find 9,11 and 13? How can I fix this (by change some configs or run some tools)?

**Comment by jwilder** [comment]
@lcrenix Did you remove any nodes via a `drop server` command?  That message is reported when a server is dropped and there are still hinted handoff queued messages on other nodes.  Hinted handoff queues are not currently deleted so those message will continue to be logged.

On the server logging those errors. you can delete the numeric sub-directory under your hinted handoff dir (default "hh") corresponding to the node ID.

**Comment by lcrenix** [comment]
@jwilder yes, I removed some nodes by using `drop meta server` and `drop data server`,  I'll try to manually delete these folders from the hh folder, thank you!

**Comment by jwilder** [comment]
Closing this is as this is a known issue an won't be fixed in 0.11 or later.  Hinted handoff code no longer exists in master.
