### ISSUE TITLE
Influxdb 0.11 - certain queries give unexpected behaviour

### ISSUE THREAD

**Issue by Madhu94** [influxdata/influxdb#6016]
I recently downloaded the 64-bit nightly release binary of influxdb 0.11. Certain queries give unexpected results, different from the previous versions.

#Problem 1 :For example say I have a field "x" and x takes values from 1 to 100. If I run the query ' select distinct("x") from "my_measurement" ' I should get an array(or some data structure) containing the values 1 to 100, something like this  [1,2,3...100].
But I get instead [(1,"2016-01-01T00:00:00Z"),(2,"2015-09-12T00:00:00Z"),......]

#Problem 2: The query ' Show tag values with key="foo" ' returns 'foo' with each record.
That is, if foo takes values 1,2,3,4,5 I want the query to return [("foo",(1,2,3,4,5))] or some similar data structure. But it returns [("foo",1),("foo","2").....]

Grafana has an auto-complete feature which basically uses this second query. So using version 0.11 influxdb with Grafana is confusing.  

Will this behaviour be fixed in the stable build of 0.11?

**Comment by BrannonKing** [comment]
It seems to me that you should never return a column that wasn't specified. At the same time, you should always be able to specify a tag or time column name and get that included, even if you don't specify an aggregate for it (maybe default it to LAST).

**Comment by Madhu94** [comment]
I would like the tag to be included somehow. But isn't it redundant to have the tag along with every request.?  I would prefer something like ["foo",(1,2,3,4,5)]. NOT [("foo",1),("foo",2)...].
Plus the timestamp included along with each record in the distinct() operation (I assume this is the time at which each distinct value was FIRST logged) doesn't even make sense.

**Comment by jsternberg** [comment]
The change to `SHOW TAG VALUES` is in the release notes. The change to `distinct()` is also expected, but needs to be added to the release notes.

/cc @pauldix

**Comment by pauldix** [comment]
@jsternberg any chance you remember the PR where distinct was done? I'd like to link to it in the release notes

**Comment by jsternberg** [comment]
It was done in the large PR for the query engine refactor in #5196. I'm guessing the output was changed because the new query engine doesn't have a way of representing arrays.

**Comment by Madhu94** [comment]
Thanks a lot!
