### ISSUE TITLE
CSV output should not contain repeated column titles

### ISSUE THREAD

**Issue by BrannonKing** [influxdata/influxdb#6017]
When I run this command:

<pre>
influx -format csv -database MyLog -execute "show tag keys"
</pre>

I get this output:

<pre>
name,tagKey
Commands,Command
Commands,EmergencyStop
Commands,Fingerprint
Commands,UserName
Commands,Vehicle
name,tagKey
Vehicles,EmergencyStop
Vehicles,Fingerprint
Vehicles,Vehicle
</pre>

`name,tagKey` should not exist down yonder. Most CSV tools (I'm using MS Excel and Qlik Sense) don't expect repeated titles down inside the data. They expect the titles to be on the first row only. Hence, I end up with a name named "name", etc. I'm using a recent 0.11 nightly build.

**Comment by jsternberg** [comment]
Closing this in favor of #6603. While this one is older, it looks like the other one has comments and it's not on a later page so it's less likely to get lost.

Sorry for the lack of a prompt response. We are trying to go through the issues so we can more efficiently respond to bug reports like this in the future.
