### ISSUE TITLE
[0.11.0-beta] builds from the last two days fail with meta.db copy/rename

### ISSUE THREAD

**Issue by BrannonKing** [influxdata/influxdb#6030]
When I try to run builds from the last few days I get this error:

<pre>
[monitor] 2016/03/16 09:50:17 failed to create database '_internal', failed to create storage: 
rename C:\ProgramData\MyServer\InfluxDB\Meta\meta.dbtmp C:\ProgramData\MyServer\InfluxDB\Meta\meta.db: 
Cannot create a file when that file already exists.
</pre>

That's after deleting all existing database files. When I run it again after that, I get this error: 

<pre>
run: create server: 
rename C:\ProgramData\MyServer\InfluxDB\Meta\meta.dbtmp C:\ProgramData\MyServer\InfluxDB\Meta\meta.db: 
Cannot create a file when that file already exists.
</pre>

**Comment by jwilder** [comment]
Fixed via #6051
