### ISSUE TITLE
select * from <measurement> limit 1 can make the database not responding (v.0.9, 0.10.3)

### ISSUE THREAD

**Issue by dvorobiov** [influxdata/influxdb#6032]
Hi,

We have an instance of InfluxDb 0.9 with about 45 GB of data, new data is also coming (about 200-500 points per second), and couple continuous queries running to calculate means. Yesterday it just got frozen at some point and needed restarting. After skimming through the log we found a query to blame: ```select * from some_measurement limit 1```. Today I reproduced it on 0.10.3 instance that doesn't have new data coming, and its size is also about 45 GB, the result was a very long response with the result: ```ERR: Get http://localhost:8086/query?db=<db>&epoch=ns&q=SELECT+%2A++FROM+<mesurement>+LIMIT+1: EOF```.  Any next call returns "connection refused".

Thanks!

**Comment by jsternberg** [comment]
Can you try this out with the 0.11 release candidate? The 0.11 release candidate contains a completely refactored query engine that should handle limit queries much better.

**Comment by vlinevich** [comment]
This issue seems to be fixed in 0.11.0rc1

**Comment by jsternberg** [comment]
I'm going to close this @dvorobiov. Please reopen if you're still having trouble with this.
