### ISSUE TITLE
Line Protocol V2

### ISSUE THREAD

**Issue by joelegasse** [influxdata/influxdb#6037]
The current line protocol has a few quirks and strange behaviors because of the way the parser was implemented. Unfortunately those quirks were just documented and developed around, rather than discussing whether or not the protocol should be better defined and made slightly more uniform. Here is my attempt at a slightly more formal definition...
## Uniform Line Protocol

This would be a breaking change to current line protocol, where each component had different rules as to what had to be escaped (e.g. measurement names didn't need to escape equal signs, but tag keys did), but I think it would provide a simpler ruleset for library maintainers and people writing directly to the API.

```
Key:
    () -> Grouping
    {} -> Zero or more
    [] -> Optional
    "" -> Literal value (case insensitive)
    '' -> Literal character (using common escape sequences)
    |  -> Alternate values
    .  -> End Definition
    ** -> Plain-language description

Batch         = { Comment } [ ParameterLine ] { Line } .
Comment       = "#" *UTF-8 string except '\n'* '\n' .
ParameterLine = "=" { " " String "=" String } '\n' .
Line          = Comment | Point .

Point         = Measurement [ "," TagSet ] " " FieldSet [ " " Time ] '\n' .
Measurement   = String .
TagSet        = Tag { "," Tag } .
FieldSet      = Field { "," Field } .
Time          = Digits [ Unit ] .
Unit          = [ "n" | "u" | "m" ] "s" .
Tag           = String "=" String .
Field         = String "=" Value .

Value         = QuotedString | Boolean | Integer | FloatingPoint .
Boolean       = "t" | "true" | "f" | "false" .
Integer       = [ "-" ] Digits 'i' .
Digits        = Digit { Digit } .
Digit         = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' .
FloatingPoint = [ "-" ] [ [ Digits ] "." ] Digits [ Exponent ] .
Exponent      = ( "e" | "E" ) [ "+" | "-" ] Digits .

String        = QuotedString | SimpleString .
QuotedString  = '"' *non-empty UTF-8 string with limited escaped characters* '"' .
SimpleString  = *non-empty UTF-8 string with special characters escaped* .

Within Strings, a backslash must be followed by a valid escape character:

For all Strings:
- Backslash       (U+005C, '\')
- Quotation Mark  (U+0022, '"', double quote)
- Lowercase N     (U+006E, 'n') [represents Line Feed (U+000A, '\n')]

For SimpleString only:
- Space           (U+0020, ' ')
- Equal Sign      (U+003D, '=')
- Comma           (U+002C, ',')

It should be noted that as a special case, '\n' is only ever a control
character, and must never appear in a string. This means that for
QuotedString, a literal newline character would appear as "\n"
```

There are a few things I'd like to point out as "features" of this proposal:
- Names, keys, and values aren't restricted by these definitions, that's up for discussion in another issue (#6011),
- String field values must be quoted (as they are currently)
- The timestamp now has an optional unit (removing the minutes/hours options)
- The `ParameterLine` allows for key=value pairs to be sent with a batch, which would allow the database, retention policy, and default precision to be set in the batch, making UDP point writing more flexible than it currently is.
- Strings can either be quoted or unquoted in measurement names, tags and field keys, allowing for flexibility in formatting. Users with spaces, equals, or commas in their tags can just use quoted strings and only escape backslashes, quotes, and newlines

There is one feature that was requested in the other issue that I think is worth discussing here: setting a per-batch custom escape character. This could be done via the `ParameterLine`, meaning the line  

```
file_stats dir="C:\\windows\\uses\\backslash",file="Important document!.docx",size=18923i
```

could instead be written

```
= escape=!
file_stats dir="C:\windows\uses\backslash",file="Important document!!.docx",size=18923i
```

As for a possible roll-out strategy, this new format could be selected at the write endpoint by setting a custom HTTP Header, or enabling a new UDP listener in the config. That way, all current clients would still work and have the chance to migrate/upgrade before the new version becomes the only available version some number of releases in the future. At that point, the custom header would be ignored, and the old UDP listener would be removed.

I've probably written enough at this point, and have most likely missed something here or there. Please leave your feedback here. Keep in mind this is just an idea, and mostly a means to begin a discussion around a "better" and well-defined line protocol that helps every level of the TICK stack (and other tools) that read/write points in our line protocol.

**Comment by sparrc** [comment]
could you provide some more concrete examples like at https://docs.influxdata.com/influxdb/v0.10/write_protocols/line/?

**Comment by sparrc** [comment]
```
Time          = Digits [ Unit ] .
Unit          = [ "n" | "u" | "m" ] "s" .
```

does this mean that line protocol will default to seconds now?

**Comment by sparrc** [comment]
```
Point         = Measurement TagSet " " FieldSet [ " " Time ] '\n' .
```

by your definitions, shouldn't this be:

```
Point         = Measurement [ "," TagSet ] " " FieldSet [ " " Time ] '\n' .
```

**Comment by mark-rushakoff** [comment]
I like this proposal overall. I agree with @sparrc that more examples would make this all easier to grok (especially examples around strings and what does or does not need to be escaped).

I dislike the inclusion of comments into the line protocol. While that may make life slightly easier for those creating points by hand, I think we should discourage including irrelevant data in line protocol batches.

I also think the feature of overriding the escape character is too costly to implement, for line protocol readers.

**Comment by jsternberg** [comment]
I would like to propose that either strings in the line protocol are surrounded by single quotes or we modify InfluxQL to let strings be surrounded by double quotes. There's a weird lack of parity between these two currently.

```
> insert cpu name="foo",value=3
> select value from cpu where "name" = 'foo'
```

The single quotes are required and I think they confuse a lot of people (at the least, they confused me). Double quotes are for variable names and are mostly used when a variable name conflicts with a reserved keyword.

**Comment by joelegasse** [comment]
I will definitely work on some examples, and add them to the original post. As far as a few points to be addressed:

- Tags would be defined as they currently are: comma separated from the measurement name. It's a subtle difference in the definition of `TagSet` and `FieldSet`. The difference is that technically each tag is preceded by a comma, and you can have zero or more directly following the measurement name. The empty string is a valid `TagSet`, which is why is doesn't need to be optional when defined in `Point`.
- The default precision would still be server-specific (probably still nanoseconds if there is no unit, and to `precision` parameter has not been set). The unit definition would change from `n`, `u`, `ms` and `s` to `ns`, `us`, `ms`, and `s`, always including the `s`.
- I'll leave the comment discussion to the wider group, it's trivial to ignore the extra information, and would only incur the cost of actually transferring the bytes from the client to the server.
- I don't like speculation on "cost" of implementing features unless we actually try them and do some benchmarks. But if we're going to speculate... As long as the parser is written to use a variable for the escape character rather than hardcoding `\` in the source, changing the character to reduce the burden on heavily-backslashed strings shouldn't be too difficult or "costly", I would think.
- I'm all for making sure that InfluxQL and the line protocol use the same quoting for strings.

**Comment by sparrc** [comment]
got it, thanks Joe,

but by the logic that an empty string is a valid TagSet, doesn't that also mean that an empty timestamp is a valid timestamp?

also-- how is an empty string a valid tag if this is true:

```
Tag           = String "=" String .
```

**Comment by joelegasse** [comment]
A timestamp is defined as Digits, which is at least one digit. Although we
should specify that strings have a minimum length of 1

**Comment by e-dard** [comment]
Generally I like this. The escaping rules look inline with the  version of the line-protocol parser I implemented in [er-escape-backslash](https://github.com/influxdata/influxdb/tree/er-escape-backslash), so they get the :+1:  from me.

```
Comment       = "#" *UTF-8 string except '\n'* '\n' .
```
I agree with Mark on the comments; I don't see the real advantage to accepting them.

```
Point         = Measurement TagSet " " FieldSet [ " " Time ] '\n' .
```
Does a `Point` needs to end in a newline?

**Comment by sparrc** [comment]
so this is valid?:

```
cpu_usage,= idle=100
```

or should this be Tag:

```
Tag           = String [ "=" ] String .
```

**Comment by gunnaraasen** [comment]
I'm not a huge fan of requiring the `s` at the end of the timestamp. It feels unnecessary and it's not something I've seen people get tripped up on.

Instead, I would propose changing the default precision to seconds. Most other tools use second precision and it's a common beginner mistake to use seconds (resulting in a bunch of 1970 points that trip people up). Compression is also much better when using seconds as the precision.

**Comment by mark-rushakoff** [comment]
> Does a Point needs to end in a newline?

I think so. A newline indicates that the point is complete. Without it, you may not know if the line was unexpectedly truncated.

**Comment by sparrc** [comment]
@gunnaraasen the unit is optional: `Time          = Digits [ Unit ] .`

**Comment by e-dard** [comment]
@sparrc @joelegasse  maybe it should be something like the following?

```
Point         = Measurement [ , TagSet ] " " FieldSet [ " " Time ] '\n' .
Measurement   = String .
TagSet        = Tag { "," Tag } .
Tag           = String "=" String .
```

**Comment by gunnaraasen** [comment]
@sparrc Whoops, my bad. I read @joelegasse's comment, "always including the `s`", and didn't think to check the spec.

**Comment by joelegasse** [comment]
@e-dard your proposed grammar is equivalent to what is currently there.

**Comment by joelegasse** [comment]
@gunnaraasen The default precision could be set in the parameter line, and handled by the client library. We could try to do some guessing if no precision has been set anywhere, and pick the time that seems closest in terms of order of magnitude. Although that is a separate concern from the line protocol itself.

**Comment by jsternberg** [comment]
I also don't think we need to have customized escape characters. I think most, if not all, people will just be fine with a backslash. It adds more difficulty to have a custom escape character and I don't know what benefit it offers.

I think we should just focus on getting escaping to be more consistent and it so single quoted strings are allowed (we can allow both double and single quotes for strings).

**Comment by e-dard** [comment]
@joelegasse you're right, and now I can't think what I was trying to get at, at the time...

**Comment by sparrc** [comment]
Personally I prefer @e-dard's grammar, I think it feels more consistent, also with the current grammar this is technically valid:

```
cpu_usage,= idle=100
```

**Comment by joelegasse** [comment]
It would only be valid if we allow the `SimpleString` to be length zero, but that was certainly not intended. Since it's equivalent, I'll use @e-dard's grammar, and add a note that the UTF-8 strings must have at least one character. Sorry about the confusion.

**Comment by sparrc** [comment]
okay @joelegasse thanks for clarifying :+1: :relaxed:

**Comment by gunnaraasen** [comment]
Agree it's a separate issue. I opened up https://github.com/influxdata/influxdb/issues/6041 to discuss it.

**Comment by mark-rushakoff** [comment]
I have a can of worms I'd like to open.

On the one hand, I personally place a high value on simplicity in the specification. It reduces surface area for bugs and it with less code, it should be faster to write your own implementation (e.g. writing a line-protocol-writer in a new programming language or writing it in assembly for a sensor device).

Nonetheless, I was thinking about whether it would be useful to support integers in hexadecimal.

Pros:
* Simpler to write code for printing hexadecimal than it is for decimal, if working with low-level or space-constrained code
* Can potentially save a byte or two per line – i.e. **100** is 3 characters while 0x**64** is only 2.

Cons: 
* Would need to bikeshed on how to represent a hexadecimal integer in a way that doesn't make detecting other types more complicated
* Introduces complexity to parsing line protocol

Even if we don't add support for hex, I'd like to be able to point back to this thread if/when someone else asks about it.

**Comment by gunnaraasen** [comment]
@mark-rushakoff If we add hexadecimal support (which sounds useful), we should consider how to extend the line protocol for additional types in the future. Eventually, adding native support for decimal, geohash, and other types in InfluxDB will be much easier if there's an easy way to easy built-in way to add them to the line protocol.

**Comment by joelegasse** [comment]
I don't see introducing other types adding too much complexity at the line protocol level, but anything other than the currently supported types of integer, float, boolean, and string will add complexity in both the storage engine and query language.

As far as adding an alternate representation of integers in the line protocol, we could switch to prefix flags, rather than the current suffix for decimal integers:

Currently, possible numbers are:
- `100i` - integer
- `100` - float
- `100.0` - float
- `1e2` - float
- `0x64` - error
- `x64` - error

Possible change:
- `i100` - integer
- `100` - float
- `100.0` - float
- `1e2` - float
- `0x64` - integer
- `x64` - integer (NEW)

Making the leading `0` optional (saving one character), means just prefixing the value with an `x` would signify that the value should be interpreted as a hexadecimal encoded integer. We could also require the `i` to precede a decimal integer, rather than follow it.

That really isn't much different that what currently happens with the other two value types: strings must start with `"`, and booleans either start with `t` or `f` (case-insensitive).

From a parsing perspective, this change would mean checking the first character (or two in the case of `0x`) of a value would allow us to know its type immediately (as we do currently for strings and booleans), avoiding the current "scanNumber" function that has to wait to see a decimal, exponent, or the (lack of) trailing `i` to differentiate between a float and an integer.

As far as expanding to additional types in the future, the first character would be available: `g` could be used for geohash, etc.

What do other people think?

**Comment by beckettsean** [comment]
I believe comments in a batch is a very useful thing to support. Not at all for production use cases, but explicitly for tutorial and example cases. We can very easily publish self-documenting batches of data for the getting started guides, for webinars, etc. We can accomplish a lot of the same goal by talking about the batch, but it's always nicer, more portable, and less error-prone to have the comments in the file itself.

```
# these points are part of the exercises described on https://docs.influxdata.com/influxdb/v0.10/query_language/data_exploration/
...
```

It also makes it easier for customers to submit steps to recreate, since they can directly mark up the data files.

**Comment by beckettsean** [comment]
I like very much the idea of using leading characters for data types. It's easily extensible and echoes the hex/ascii/octal pattern that is very familiar.

Would it still be possible to submit timestamps in minutes or hours precision using the `precision=[h,m]` query parameter? I don't know if it's a killer use case, but it seems cleaner to support consistent time units for writes and reads. (Note that it is not possible to query by nanoseconds intervals, so there is precedent for the two not being entirely equivalent.)

**Comment by joelegasse** [comment]
If we are going to continue to support "minutes since epoch" and "hours since epoch", then I would say that we should support them in both the in-line timestamps as well as the `precision` parameter. I left them out initially because I don't know of any other software that measures time in those units.

Supporting the extra units is trivial, so if they are useful for something other than just saying we support them, I'm not opposed to adding them back in.

As for the leading characters for field values, what do you think about floats? The idea I mentioned about would leave floating point values as bare numbers. Part of me would like the consistency of adding an `f` to the front to truly have every value be declared with a type... but the other side thinks that floats are probably more common, and shouldn't need the extra character, as a digit, dash, or decimal would be enough to signify a float value.

**Comment by joelegasse** [comment]
In browsing recent issues, I came across #5976, where it appears carriage returns are being sent in the payload. If there is no strong opposition, I think we should add an optional `'\r'` before the newline characters. This would mean example files could be saved/created/uploaded by windows users without getting errors about invisible characters they have no control over. Or, as was the case in the issue, point data being generated by a powershell script.

**Comment by mark-rushakoff** [comment]
I ran into a nasty bug involving the Content-Type header in https://github.com/influxdata/influxdb/issues/6061. When sending line protocol over HTTP, do we need [a custom MIME type](https://tools.ietf.org/html/rfc6838)? Would a recommendation of `text/plain` suffice?

**Comment by joelegasse** [comment]
I noticed we are using `FormValue()`, which we really shouldn't be, since we only ever want the URL query parameters. `FormValue`, I believe, attempts to parse the request body if it is declared as a URL-encoded form... `text/plain` is probably the appropriate `Content-Type` for our write endpoint.

When I mentioned "custom header", I meant `InfluxData-Line-Version: 2`, or something similar. Although setting `Content-Type: application/influxdb-line` would work for the transition as well. Requiring either of those long-term (when the current format is deprecated/removed) would probably be an annoyance to new users trying to submit sample data. The custom header/type would just be required during the transition phase, when both formats are supported.

**Comment by gunnaraasen** [comment]
Requiring a header to use the new version of the line protocol would be very annoying to use. Will we be supporting both line protocol versions at once? If not, we can be very vocal about mentioning the change when people are upgrading. Most existing line protocol should work with the new version so I don't think it will be a huge disruption as long as we add support for the new protocol to the popular client libs.

**Comment by joelegasse** [comment]
I was trying to avoid talking too much about the transition here, but I guess I should probably explain what I had in mind a bit more:

Step 1 (current): Only current line protocol supported
Step 2: Add support for new line format via header
Step 3: Make new format default, old version available via header
Step 4: Only support new format

We could be more aggressive with the transition and skip Step 2. If we switch to prefixed values (`i` before the number to declare integer) then most current clients won't be compatible for integer values.

I understand that requiring a header to use the new version might be considered bothersome, but I think it would be worse to break every client in a single release without giving them time to transition. Ideally we would be setting that header anyway, and Step 3 would just change the default value if it isn't specified. Once we hit Step 4, `InfluxDB-Line-Version: 1` would return an error.

Another option would be to use path elements to declare the version (`/write/v2`), but that gets ugly long-term, in my opinion.

**Comment by gunnaraasen** [comment]
I also prefer using a header over changing the path.

In Step 3, client libs would need to be updated to support the old version header. Since the client already needs to be updated, we should incentivize people to simply add support for the v2 protocol instead of essentially committing to using an old version.

In that context, I think skipping Step 3 and keeping Step 2 would allow client libs to be updated to the new v2 protocol. Then dropping support for the v1 protocol would draw a clear line to transition, by which time most clients will hopefully have already been updated to v2.

**Comment by jsternberg** [comment]
I think we need all of the steps for transitioning and I don't really think it's going to be too big of a deal. Supporting multiple write protocols isn't very difficult for us as long as we say, "When the new write protocol exists, we will not fix bugs in the old one." The only time it ends up being a potential problem is for security fixes.

I fully approve of reading `\r` before a newline for Windows compatibility.

I'm not sure I see the value of supporting hours and minutes as the precision. I also can't think of a reason not to. I think as long as it's extensible so we can add support for those precisions in the future.

Comments are fine as long as it's not the customizable comment character idea. Something really simple like "if the line starts with `#` and only then" works well.

I don't think prefix values for data types really does anything. From a scanning and parsing perspective, I don't think there's any difference between them. I think suffix values for some things is more user-friendly for things like durations and integers while prefix values is better for things like hexadecimal. We should use whatever is most appropriate.

I am strongly recommending we have support for single quotes with strings. I mentioned it in my first comment but it keeps being lost from the RFC. If we want to make single quotes different from double quotes (like single quotes do not escape characters, similar to Ruby), then I also think that's a good improvement. We absolutely need to have support for single quotes.

While the query language has been modified to have integer support without any kind of suffix, I think the write protocol still should default to floats. I think most people will want to write floats (and the query language assumes that by commonly casting things to floats).

**Comment by gunnaraasen** [comment]
As mentioned in https://github.com/influxdata/influxdb/issues/6041#issuecomment-205067182, we could allow precision to be set per point without an explicit timestamp. 

```
Time          = [ Digits ] [ Unit ] .
# if a blank timestamp is given could still include the precision
disk_free,tag=t  value=1  [s,ms,us,ns]
```

This would probably be useful for allowing variable precision on points without timestamps sent to a UDP input.

**Comment by joelegasse** [comment]
I'm not sure I see the benefit of per-point precision without a timestamp. The currently proposed update would allow precision to be set per-batch. If using UDP, you could just send one batch per precision, and have no timestamps.

In general, I would prefer to see timestamps be required, otherwise the client has no guarantee what time the point will be tagged with in the database. For example, if an application is emitting points once every second, and the database is slightly bogged down, two points without timestamps for the same series could end up being processed by the server in the same second, overwriting one of the points and creating a "gap" in the data.

I'd like to see a better use case of "per-point precision without timestamp" that isn't easily handled by per-batch precision without timestamp

**Comment by nathanielc** [comment]
>The ParameterLine allows for key=value pairs to be sent with a batch, which would allow the database, retention policy, and default precision to be set in the batch, making UDP point writing more flexible than it currently is.

Just want to publicly voice that this is a very important change for Kapacitor as having multiple UDP ports for each different database retention policy is difficult to manage.

**Comment by bfgoodrich** [comment]
It would be nice if Telegraf could have tag support for metric that was stored with the type of unit that was chosen in the line protocol (whatever that happens to be)

**Comment by saboteurkid** [comment]
> Point         = Measurement [ "," TagSet ] " " FieldSet [ " " Time ] '\n' .
How about:
>Point         = [RetentionPolicy "." ] Measurement [ "," TagSet ] " " FieldSet [ " " Time ] '\n' .
>RetentionPolicy   = String .
Would it be nice if I can put my data to specific retention policy instead of default one?

**Comment by beckettsean** [comment]
@saboteurkid With the system now you can write any given batch of points to an [explicit retention policy](https://docs.influxdata.com/influxdb/v0.13/write_protocols/write_syntax/#query-string-parameters-for-writes) (RP), but there's no way to mix RPs in a single write batch. There are write path optimizations that we can do because each batch is going to only one database and retention policy. If it becomes possible to write points to different RPs in the same batch that will eliminate all of those optimizations. I suspect the trade-off wouldn't be worth it.

What's your use case where writing batches to a single RP doesn't work well?

**Comment by saboteurkid** [comment]
@beckettsean thank for your response.
I think I've had misused the CQs and RPs.

**Comment by MikeSchroll** [comment]
@beckettsean Responding to your call for use-case for writing to multiple retention policies via UDP:

I'm sending three lines per data point:
1. infinite retention policy: about 10 fields, 1 tag, low cardinality; keeping record of data for long-term reference.
2. Select fields of #1 as tags, very high cardinality - so using 2d retention policy. Many continuous queries coming off this to summarize this data via grouping tags; eventually using top() to get the data out of tags; and have long-term summarization without cardinality issues.
3. real-time data related to #1 - low cardinality, few continuous queries summarizations; really only care about it for looking for performance issues in the moment. Would prefer to use a 1 hour retention policy.

**Comment by stevenh** [comment]
Any news on this?

I ask as we go bitten by this, as breaks the php unexpectedly if tags or field values happen to end in backslash, which is far from ideal as it means everyone has to implement their own filtering for this special case.

**Comment by rbetts** [comment]
@stevenh I don't have much to update - apologies.  At the moment, we do not have plans to ship this RFC.

**Comment by natejgardner** [comment]
Any hopes of bringing this back?
