### ISSUE TITLE
[0.9.6.1] Second node is returning single series when using pattern in FROM

### ISSUE THREAD

**Issue by deathsoverture** [influxdata/influxdb#6039]
```
InfluxDB shell 0.9.6.1
> show servers
id	cluster_addr				raft	raft-leader
1	vm-influxdb-1.example.com:8088	true	false
2	vm-influxdb-2.example.com:8088	true	true
```

For using the data source vm-influxdb-1:8088, I see a series for inbound and outbound:
![inbound-series-1](https://cloud.githubusercontent.com/assets/12052422/13830488/54043380-eba3-11e5-8ded-d71c7f1b2b75.png)

But when I use the data source vm-influxdb-2:8088 I see the data points for both series but they are all in 'inbound' series.
![inbound-series-2](https://cloud.githubusercontent.com/assets/12052422/13830367/92f85c98-eba2-11e5-9d17-44ba3070a9f0.png)

When I query the inbound and outbound series individually on vm-influxdb-2 I can get the correct data points.

Here is the query
```
SELECT "value" FROM /system.interfaces.eth0.(in|out)bound/ WHERE "host" = 'localhost' AND "serial" = '00000fig1eef' AND time > now() - 1h
```

**Comment by e-dard** [comment]
What version of `influxd` are you running? From the look of that `SHOW SERVERS` output, it seems to be pretty old.

**Comment by deathsoverture** [comment]
I am using 0.9.6.1 which seems to be the version provided with "tutum/influxdb:0.9"

I could try a newer version though 0.9.x seems to be the latest "officially" supported by Grafana 2.6.0

**Comment by jackzampolin** [comment]
@deathsoverture Clusters in 0.9.6 require 3 machines to function properly. Closing.
