### ISSUE TITLE
[0.11 / master] Unable to query distinct against boolean field

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#6040]
```
> insert b ok=T
> insert b ok=F
> insert b ok=F
> insert b ok=F
> select count(distinct(ok)) from b
ERR: unsupported distinct iterator type: *influxql.booleanSortedMergeIterator
> select distinct(ok) from b
ERR: unsupported distinct iterator type: *influxql.booleanSortedMergeIterator
```

Confirmed on a recent 0.11 nightly build and on master at 6a461d8a3458154510ce321c74c82ece04df123c.

**Comment by jsternberg** [comment]
I think we decided not to implement this for boolean. @benbjohnson @pauldix does distinct need to work on booleans?

**Comment by mark-rushakoff** [comment]
`SELECT distinct(ok)`, of course, isn't useful to me. I really was interested in knowing how many Trues and how many Falses were in a particular field in a measurement.

In hindsight I could have done two calls to `count`, although I didn't want to execute two queries:

```
> select count(ok) from b where ok=true
name: b
-------
time	count
0	1

> select count(ok) from b where ok!=true
name: b
-------
time	count
0	3
```

**Comment by jsternberg** [comment]
Hm, that seems like a reasonable enough reason. I can implement distinct for booleans so that this is possible.

**Comment by jsternberg** [comment]
I was working on this, finished it, and tested it out, but the end result won't do what you want. `count(distinct())` will count how many distinct entries there are in an interval so it won't give you a row for true and a row for false, but it will give you the answer 0, 1, or 2 (depending on if there are no entries, only entries for `true` or `false`, or entries for both `true` and `false`).

This seems to be consistent with what the iterator does for the other types, so I think we're going to need an alternate syntax if we want to support the query you tried to use when opening this issue.

I'm going to submit it anyway along with a change to normalize the time entry, but just an FYI.
