### ISSUE TITLE
Expose shard group setting to pack more data in one shard

### ISSUE THREAD

**Issue by psilons** [influxdata/influxdb#6053]
Hi,

We have a lot of daily data, one data point per day. When we load them in InfluxDB, the database size in the file system is large since the data is kind of sparse in time. So we need to adjust shard group setting to pack more data in one shard.

Thanks,
Rick
(I discussed our usage with Jason Wilder and Sean Beckett)

**Comment by e-dard** [comment]
Hi @psilons I think this will be satisfied in `0.12`. As of `0.12` you'll be able to do similar to the following:

```
CREATE RETENTION POLICY rp0 ON db0 WITH SHARD DURATION 86m
```

There will be support in the other commands that take a retention policy too. Let me know if this is what you're after and I'll close out this issue.

**Comment by psilons** [comment]
Yes, Jason Wilder informed me of this change. Let's close this one.

Thanks a lot for the quick turn around.
Rick
