### ISSUE TITLE
data lost on influxdb 0.10.3 udp

### ISSUE THREAD

**Issue by gzliudan** [influxdata/influxdb#6057]
I write a c language program to test the performance of influxdb.  The running enviroment is oracle linux 7.2, gcc 4.8.5, influxdb 0.10.3. net.core.rmem_max is 8388608. Other config of influxdb use default value. The test program submits a record through udp which is 92 bytes in a loop. In the loop, if write a record to udp port and usleep(1), then the program can write 12000 records per second without data loss. But without usleep, some records will be lost if loop count exceed 550.

**Comment by joelegasse** [comment]
@gzliudan You can try setting the `read-buffer` setting for the UDP service in the configuration file for InfluxDB to match `rmem_max`. What is `net.core.rmem_default` set to?

You said each each payload is only 92 bytes, are you only sending one point per packet? If you have a special use case where you can guarantee smaller packets, then you can try setting `udp-payload-size` to something smaller, maybe 256? The current default is to allocate the maximum allowed UDP payload size of 64K, which would add a lot of overhead.

If neither of those settings help, I would recommend batching your points when submitting them to InfluxDB. For higher reliability, I would also recommend using the HTTP endpoint.

**Comment by BrannonKing** [comment]
The OS itself is allowed to drop UDP packets when its buffers (or its NIC driver's buffers) are full.

**Comment by gzliudan** [comment]
Thank all very much!
I set udp below parameters in linux:
sysctl -w net.core.rmem_max=33554432
sysctl -w net.core.wmem_max=33554432

And I set below parameters influxdb.conf:
batch-size = 1024
batch-pending = 256
read-buffer = 33554432
udp-payload-size = 128

After restart influxdb, my test program can submits 400000 records in 1.58 seconds through udp protocol without data loss. But influxdb need 3-4 seconds to flush all data to disk.

**Comment by joelegasse** [comment]
250K points/sec sounds about right. InfluxDB has to do some processing on all that data, so it won't be able to flush to the disk instantly. It sounds like you've got everything sorted out, so I'm going to close this ticket. If you run in to any other issues, please let us know.
