### ISSUE TITLE
how to check field type ?

### ISSUE THREAD

**Issue by haowells** [influxdata/influxdb#6063]
any command can show the field type info like int, float etc  ?

**Comment by jwilder** [comment]
There is no way to show the field type currently.  By default, all numeric values are stored as floats unless you are explicitly sending them as integers.

In the future, questions like this should be sent to the mailing list.  Please take a look at our [contributing guidelines](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#bug-reports).
