### ISSUE TITLE
Graphite server not listening on port 2003

### ISSUE THREAD

**Issue by sirkubax** [influxdata/influxdb#6066]
Graphite server not listening on port 2003. It did just 'stopped working' :/

As You can see - it was working before:

	[handoff] 2016/02/23 15:30:48 Starting hinted handoff service
	[handoff] 2016/02/23 15:30:48 Using data dir: /influxdb/influxdb/hh
	[tcp] 2016/02/23 15:30:48 Starting cluster service
	[shard-precreation] 2016/02/23 15:30:48 Starting precreation service with check interval of 10m0s, advance period of 30m0s
	[snapshot] 2016/02/23 15:30:48 Starting snapshot service
	[admin] 2016/02/23 15:30:48 Starting admin service
	[admin] 2016/02/23 15:30:48 Listening on HTTP: [::]:8083
	[continuous_querier] 2016/02/23 15:30:48 Starting continuous query service
	[httpd] 2016/02/23 15:30:48 Starting HTTP service
	[httpd] 2016/02/23 15:30:48 Authentication enabled: false
	[httpd] 2016/02/23 15:30:48 Listening on HTTP: [::]:8086
	[retention] 2016/02/23 15:30:48 Starting rentention policy enforcement service
	[graphite] 2016/02/23 15:30:48 Starting graphite service, batch size 1000, batch timeout 1s
	[http] 2016/02/23 15:30:49 172.16.4.87 - root [23/Feb/2016:15:30:49 +0000] POST /write?consistency=&db=so1influxdb&precision=&rp= HTTP/1.1 500 60 - sysinfo_influxdb v0.5.6 6a73591f-da42-11e5-8001-000000000
	000 3.02867ms
	[metastore] 2016/02/23 15:30:49 Node at 172.16.4.216:8088 [Leader]. peers=[172.16.4.216:8088]
	[metastore] 2016/02/23 15:30:49 Updated node id=1 hostname=172.16.4.216:8088
	[graphite] 2016/02/23 15:30:49 Listening on TCP: [::]:2003
	2016/02/23 15:30:49 InfluxDB starting, version 0.9.3, branch 0.9.3, commit 5d42b212fca8facfe9db0c83822f09b88be643ec
	2016/02/23 15:30:49 GOMAXPROCS set to 2
	[run] 2016/02/23 15:30:49 Listening for signals

Now

	[handoff] 2016/03/21 10:29:51 Starting hinted handoff service
	[handoff] 2016/03/21 10:29:51 Using data dir: /influxdb/influxdb/hh
	[tcp] 2016/03/21 10:29:51 Starting cluster service
	[shard-precreation] 2016/03/21 10:29:51 Starting precreation service with check interval of 10m0s, advance period of 30m0s
	[snapshot] 2016/03/21 10:29:51 Starting snapshot service
	[admin] 2016/03/21 10:29:51 Starting admin service
	[admin] 2016/03/21 10:29:51 Listening on HTTP: [::]:8083
	[continuous_querier] 2016/03/21 10:29:51 Starting continuous query service
	[httpd] 2016/03/21 10:29:51 Starting HTTP service
	[httpd] 2016/03/21 10:29:51 Authentication enabled: false
	[httpd] 2016/03/21 10:29:51 Listening on HTTP: [::]:8086
	[retention] 2016/03/21 10:29:51 Starting rentention policy enforcement service
	2016/03/21 10:29:51 InfluxDB starting, version 0.9.3, branch 0.9.3, commit 5d42b212fca8facfe9db0c83822f09b88be643ec
	2016/03/21 10:29:51 GOMAXPROCS set to 2
	[run] 2016/03/21 10:29:51 Listening for signals

The logs does not indicate anything.
I did not change the config.

I did try with influxdb config > /tmp/test.config 
But it did not start either....

My config is:

	/etc/opt/influxdb# less /etc/opt/influxdb/influxdb.conf
	reporting-disabled = true

	[meta]
	  dir = "/influxdb/influxdb/meta"
	  hostname = "172.16.4.216"
	  bind-address = ":8088"
	  retention-autocreate = true
	  election-timeout = "1s"
	  heartbeat-timeout = "1s"
	  leader-lease-timeout = "500ms"
	  commit-timeout = "50ms"
	  cluster-tracing = false

	[data]
	  dir = "/influxdb/influxdb/data"
	  max-wal-size = 104857600
	  wal-flush-interval = "10m0s"
	  wal-partition-flush-delay = "2s"
	  wal-dir = "/influxdb/influxdb/wal"
	  wal-enable-logging = true
	  wal-ready-series-size = 30720
	  wal-compaction-threshold = 0.5
	  wal-max-series-size = 1048576
	  wal-flush-cold-interval = "5m0s"
	  wal-partition-size-threshold = 20971520

	[cluster]
	  force-remote-mapping = false
	  write-timeout = "5s"
	  shard-writer-timeout = "5s"
	  shard-mapper-timeout = "5s"

	[retention]
	  enabled = true
	  check-interval = "10m0s"

	[shard-precreation]
	  enabled = true
	  check-interval = "10m0s"
	  advance-period = "30m0s"

	[admin]
	  enabled = true
	  bind-address = ":8083"
	  https-enabled = false
	  https-certificate = "/etc/ssl/influxdb.pem"

	[http]
	  enabled = true
	  bind-address = ":8086"
	  auth-enabled = false
	  log-enabled = true
	  write-tracing = false
	  pprof-enabled = false
	  https-enabled = false
	  https-certificate = "/etc/ssl/influxdb.pem"

	[[graphite]]
	  bind-address = ":2003"
	  database = "graphite"
	  enabled = false
	  protocol = "tcp"
	  batch-size = 1000
	  batch-timeout = "1s"
	  consistency-level = "one"
	  separator = "."

	[collectd]
	  enabled = false
	  bind-address = ":25826"
	  database = "collectd"
	  retention-policy = ""
	  batch-size = 5000
	  batch-timeout = "10s"
	  typesdb = "/usr/share/collectd/types.db"

	[opentsdb]
	  enabled = false
	  bind-address = ":4242"
	  database = "opentsdb"
	  retention-policy = ""
	  consistency-level = "one"
	  tls-enabled = false
	  certificate = "/etc/ssl/influxdb.pem"

	[monitoring]
	  enabled = false
	  write-interval = "1m0s"

	[continuous_queries]
	  log-enabled = true
	  enabled = true
	  recompute-previous-n = 2
	  recompute-no-older-than = "10m0s"
	  compute-runs-per-interval = 10
	  compute-no-more-than = "2m0s"

	[hinted-handoff]
	  enabled = true
	  dir = "/influxdb/influxdb/hh"
	  max-size = 1073741824
	  max-age = "168h0m0s"
	  retry-rate-limit = 0
	  retry-interval = "1s"

What can I debug?

**Comment by sirkubax** [comment]
Invalid? Somehow it was enabled = false

enabled = true

now it is working again

**Comment by Tohtig** [comment]
What does you do for running?

**Comment by Svastikkka** [comment]
Hello @sirkubax can u share the steps of sharing graphite metrics to influxdb. Please
