### ISSUE TITLE
systemd service should "wait" until influxdb has finished starting up

### ISSUE THREAD

**Issue by anlutro** [influxdata/influxdb#6068]
Currently, using a configuration management tool, whenever the InfluxDB configuration file gets modified, InfluxDB gets restarted. The `systemctl restart` seems to complete immediately, but InfluxDB doesn't seem to be fully restarted - because some subsequent commands that check if an InfluxDB user exists and creates it if it doesn't, fails with a "Connection refused" message. If I run the configuration manager again right afterwards (<5 sec delay), it works just fine.

I know systemd has a concept of notifications to help solve this problem: https://www.freedesktop.org/software/systemd/man/systemd-notify.html

Alternatively, the script that launches the daemon shouldn't exit until the forked process is done starting up InfluxDB.

I'm not sure if this is an issue in other init systems, I've only tested in Debian 8.

**Comment by rossmcdonald** [comment]
@anlutro I think what you're seeing is the HTTP listener not being up immediately after the service starts (which is expected). The [systemd unit file](https://github.com/influxdata/influxdb/blob/master/scripts/influxdb.service) simply calls the `influxd` binary directly, so there is no extra script being called when using systemd. 

When InfluxDB starts, it does a few different things that take time (start internal plugins and services, flush the WAL to disk, load the shard indices, etc), so the startup time can vary depending on a few different environmental factors, namely:

- The size of the WAL when the service was stopped
- The number of shards and the number of series in each shard (that have to be loaded into memory)
- The number of plugins and services you have enabled
- Whether you are running a cluster

Everything above can typically be done rather quickly, but, for larger systems, it can end up taking a few minutes to complete before the database will be ready to serve requests.

As a workaround, I would recommend putting some wait logic into your configuration management tool to wait for port `8086` to become active before creating users, databases, etc. For example, in Ansible you can use the `wait_for` module to pause execution until the service binds to port `8086`. I'm not super familiar with the config management tools, but I'm sure there is something similar in each one.

**Comment by anlutro** [comment]
Sure, I can definitely hack something together, and probably will until this gets resolved. I still think it's a problem worth solving though - I haven't had to implement this type of workaround for any services other than InfluxDB and, to a lesser extent, Kapacitor.

**Comment by steverweber** [comment]
If you use Salt.
https://www.lutro.me/posts/wait-for-a-port-to-be-listening-in-salt

**Comment by anlutro** [comment]
Another similar and annoying issue is that the `service start` call doesn't fail if influxdb fails to start up - for example, I was upgrading to 0.12 and influxdb exited saying `/var/lib/influxdb/meta/raft.db` needed to be removed, but the service start command was still successful. Maybe do these sorts of sanity checks before forking the process.

**Comment by steverweber** [comment]
and that also got me! +1

**Comment by phemmer** [comment]
A simple fix would be adding the following to the `influxdb.service` unit file:

    ExecStartPost=/bin/sh -c 'while ! influx </dev/null >/dev/null 2>&1; do sleep 0.2; done'

But as mentioned mentioned a notification would be a better solution.
And the perfect solution would be if influxdb supported systemd socket passing.

**Comment by fnoop** [comment]
This is a major flaw in influxdb startup, as it means other services that depend on influxdb then fail (for example, collectd using influxdb backend).  influxdb should support systemd Notify.
@phemmer Good workaround, can use that technicque in ExecStartPre for collectd startup.

**Comment by mark-rushakoff** [comment]
We're currently using [fpm](https://github.com/jordansissel/fpm) to generate our packages. I've scoured through the documentation and code, and I haven't been able to find any suggestion that we can use systemd notifications or hook into systemd sockets or easily modify the service script to add ExecStartPost. Tomorrow, I will investigate whether we can use the "drop-in `.d` directories" as explained in [the systemd.unit docs](https://www.freedesktop.org/software/systemd/man/systemd.unit.html), to apply the `ExecStartPost` trick suggested above.

**Comment by jordansissel** [comment]
for folks following along, @mark-rushakoff and I are improvements to fpm and pleaserun to make possible whatever notifications are necessary -- https://github.com/jordansissel/fpm/issues/1412

**Comment by steverweber** [comment]
a little hack i created for another project,

basically let  `influx` startup for 10 seconds before sending a `notify --ready`
if `influx` failed before the 10 seconds the service returns an error.

```
[Service]
Type=notify
TimeoutStartSec=15
ExecStart=/bin/sh -c '(sleep 10; systemd-notify --ready)& influx --foreground'
...

kinda surprised this is not already possible in systemd without the hack.

**Comment by bbobrov** [comment]
ExecStartPost is not the best solution, because influxd doesn't always listen at localhost and it would require putting the ip to the .service file.

**Comment by guillemj** [comment]
Just in case this was not clear, what others meant with systemd notification support is what is described on the [sd_notify(3)](https://www.freedesktop.org/software/systemd/man/sd_notify.html) man page. And indeed any notification at the packaging level would not be very satisfactory. :)

**Comment by akors** [comment]
Here's an updated workaround for newer influxdb versions:

```
mkdir -p /etc/systemd/system/influxdb.service.d/
cat > /etc/systemd/system/influxdb.service.d/override.conf << EOF
[Service]
ExecStartPost=/bin/sh -c 'while ! /usr/bin/influx -execute exit >/dev/null 2>&1; do sleep 0.2; done'
EOF

```

**Comment by guillemj** [comment]
This issue is still relevant. This stale bot is rather annoying, and does it mean from now on we'll need to reply every time after it has tagged issues as stale, to undo that? :/

**Comment by nicolas17** [comment]
Can we reopen this never-fixed issue? (I'm so glad stalebot is gone)

**Comment by daef** [comment]
+bump for reopen

**Comment by mark-rushakoff** [comment]
@russorat who should own this issue now?
