### ISSUE TITLE
CLI History Error on ARM

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#6070]
When running the InfluxDB CLI on ARM Linux (specifically Raspbian), the command history returns the error:

```
There was an error writing history file: open : no such file or directory
```

Even though the user is set appropriately. Based on [this](https://github.com/influxdata/influxdb/issues/5112#issuecomment-198695157) comment, it seems like the file history path isn't being set correctly.

**Comment by drdran** [comment]
Hi I have the same problem.

**Comment by jonseymour** [comment]
FWIW: i can reproduce the same symptom on linux/amd64 if I compile the influx binary with CGO_ENABLED=0 set in the environment. In this case, the reason is that user.Current() then fails with the error: 'Current not implemented on linux/amd64.'

This causes the branch in this [block](https://github.com/influxdata/influxdb/blob/master/cmd/influx/cli/cli.go#L171-L179) to be skipped, which then results in the reported symptom after a command is run (since the history path is never initialised properly).

So, I suspect the reason this is occurring on arm systems is either that the ARM build of the influx binary was done with CGO_ENABLED=0 for some reason or go has not implemented user.Current() for ARM systems for some different reason.

**Comment by jonseymour** [comment]
Based on a quick review of the go source, it seems more likely that the arm influx binary was compiled with CGO_ENABLED=0.

**Comment by xmoulin** [comment]
same problem:
_uname -a_
`Linux Nas-XMN 3.2.40 #7321 SMP Wed Mar 23 11:47:17 CST 2016 armv7l GNU/Linux synology_armada375_ds215j`

_influx -version_
`InfluxDB shell 0.12.1`

**Comment by jorgebonilla** [comment]
Same issue on a beaglebone (arm based).

root@beaglebone:~# uname -a
Linux beaglebone 4.1.15-ti-rt-r43 #1 SMP PREEMPT RT Thu Jan 21 20:13:58 UTC 2016 armv7l GNU/Linux
root@beaglebone:~# influx --version
InfluxDB shell 0.12.0
root@beaglebone:~# influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.12.0
InfluxDB shell 0.12.0
> create database snmp
There was an error writing history file: open : no such file or directory
>

**Comment by marthjod** [comment]
Same here :(.

- installed on `Linux pi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux`
- downloaded from https://s3.amazonaws.com/influxdb/influxdb_0.12.1-1_armhf.deb
```
~# influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.12.1
InfluxDB shell 0.12.1
> create database foo;
There was an error writing history file: open : no such file or directory
```

**Comment by nobrick** [comment]
Same issue on ubuntu 14.04.
```
 ~ uname -a
Linux ubuntu 3.19.0-31-generic #36~14.04.1-Ubuntu SMP Thu Oct 8 17:59:01 UTC 2015 i686 i686 i686 GNU/Linux
 ~ influx --version
InfluxDB shell 0.12.1
 ~ influx
> create database foo;
There was an error writing history file: open : no such file or directory
```

**Comment by joernroeder** [comment]
same here on a fresh rPi3

**Comment by Wolfgang1966** [comment]
0.12.2, Banana Pi, same problem:

$ uname -a
Linux bananapi 3.4.108-bananian #2 SMP PREEMPT Thu Aug 13 06:08:25 UTC 2015 armv7l GNU/Linux
$ influx --version
InfluxDB shell 0.12.2

**Comment by gena01** [comment]
I am seeing this on x86_64 running the 0.12.2 static linux binaries (inside an alpine docker container)

**Comment by BrannonKing** [comment]
On the latest Windows builds I get this after every command in the the influx.exe terminal: "There was an error writing history file: open : The system cannot find the file specified."

**Comment by vitcozzolino** [comment]
Same error on CubieTruck:

```
mirage@cubietruck:~$ uname -a
Linux cubietruck 3.16.0-00124-g6b6dcc2-dirty #2 SMP Wed Feb 3 14:27:34 GMT 2016 armv7l armv7l armv7l GNU/Linux
mirage@cubietruck:~$ influx --version
InfluxDB shell 0.12.2
> create database test
There was an error writing history file: open : no such file or directory
```

**Comment by BrannonKing** [comment]
I still see this issue in the latest (Windows) nightly on 8 July 2016. It seems to slow the influx.exe client a little too -- maybe it has some timeout where it tries to right to the file.

**Comment by runner-mei** [comment]
Same error on Windows

**Comment by BrannonKing** [comment]
This is a high-priority issue for me. I'm glad to see progress. Thanks.

**Comment by phemmer** [comment]
The original issue this was opened for is actually fixed. The code no longer uses `user.Current()`.
However it instead uses `$HOME` which now errors on windows, and on *nix when `$HOME` is unset.

**Comment by JackUkleja** [comment]
On Windows 10, doing `SET HOME=<path to exe location>` seems to fix this for me.

**Comment by sinedsem** [comment]
Adding environment variable `HOME` with value `<path to exe location>` solved problem for me either, OS Windows 7. But that's doesn't looks like a fix, just a workaround. Look forward to an appropriate fix.

**Comment by dnafication** [comment]
Adding environment variable HOME with value <path to exe location> solved for me in Win7

**Comment by Kortenbach** [comment]
How did anyone come up with the idea to use SET HOME=<path to exe location> ? I didn't find "HOME" in the config file or in the Influx docs...
For less experienced Windows users: Use the configuration screen tot set this environment variable. Using SET wil only change the environment variable once for that instance of the command prompt...

**Comment by e-dard** [comment]
@rossmcdonald is this still a problem?

**Comment by rossmcdonald** [comment]
@e-dard It looks like the error still occurs if the `HOME` environment variable is not set correctly. It looks like the [client code](https://github.com/influxdata/influxdb/blob/master/cmd/influx/cli/cli.go#L195) should handle this correctly, though, so this may be Windows-specific.

**Comment by seanvree** [comment]
was there ever a resolution to this?

**Comment by amoghskulkarni** [comment]
I am facing the same issue with freshly installed influxdb on Windows 10 system. Is adding an environment variable HOME to the path a recommended solution for this problem?

**Comment by LycanStack** [comment]
This issue persists on Windows.

This batch file wraps influx.exe in the fix given by @JackUkleja. Save to `influx.bat` in the same directory as your influx executable and run the batch file instead:

```winbatch
@ECHO OFF
SETLOCAL
SET HOME=%~dp0
"%~dp0\influx.exe" %*
ENDLOCAL
```

Temporary shim but it works. Some details:
* Sets environment variable `HOME` to the directory containing the batch file.
* Localizes the environment variable setting so it won't interfere with other things.
* Passes all command line arguments on to influx.

The culpable feature seems to be command history logging. Once `HOME` is set up right influx will create `.influx_history` in the HOME directory. It contains a history of commands you've entered at the influx shell.

**Comment by Renato-Correa** [comment]
Very good LycanStack!!

**Comment by AndrewClarke** [comment]
The windows build should use HOMEPATH (trust MS to use something slightly different from the 45 year old UNIX convention). In the meantime, I am "shimming" my environment with set HOME=%HOMEPATH% - much simpler than playing with %~ business.

**Comment by khaebler** [comment]
Hello, I'm new to influxdb, am getting this error and am quite confused about to solve it. I've read the above posts, but where specifically should I write "set home=file_path"? In the configuration file I take it? Where specifically in the configuration file, and do I need to make a new header? Thank you very much
