### ISSUE TITLE
Max group by buckets - Prevent queries that would create too many buckets (e.g. group by time(1s) over 1y of points)

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#6078]
#6024

**Comment by BrannonKing** [comment]
I believe that this bespeaks a design issue. I cannot understand why you would need more buckets in RAM than the number of columns being reported x2. You have your current row plus the previous row data that may be necessary to pull from. The data should be streaming out after it's processed. What is the reason that "over 1y" would make a difference? I don't think it should.
