### ISSUE TITLE
Query language coverage for authorization shim

### ISSUE THREAD

**Issue by CamJN** [influxdata/influxdb#6084]
Can someone look at my authorization code for influxdb & grafana and let me know if I'm missing a feature of the query language that would allow someone to bypass my checks?

code is here: https://github.com/grafana/grafana/pull/4344/files

**Comment by jsternberg** [comment]
Hello @CamJN. Sorry that nobody has responded, but we use the issue tracker to track features and bugs related to InfluxDB. This kind of question should be sent to the [mailing list](https://groups.google.com/forum/#!forum/influxdb) and there's a better chance of it possibly being answered. Even then, I don't know if we do code reviews of other people's code for other projects. If you have a more specific question that doesn't involve reading code, I'm sure someone on the mailing list will be willing to help.
