### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by CamJN** [influxdata/influxdb#6086]
From what I can tell the current spec given at: https://docs.influxdata.com/influxdb/v0.10/query_language/spec/ is incomplete, for example it doesn't cover regex literals in the from clause of a select statement. Is there a complete and correct spec somewhere?

**Comment by jwilder** [comment]
@CamJN This repo doesn't actually contain the documentation you linked to.  Documentation issues and PRs can be logged [here](https://github.com/influxdata/docs.influxdata.com/issues).
