### ISSUE TITLE
Got invalid 'H' when backing up a db

### ISSUE THREAD

**Issue by lcrenix** [influxdata/influxdb#6088]
I got an error when backing up a database, can any one help?
I'm using v0.11, build from the master branch and sure with the host and port.

usr/bin/influxd backup -host xxxx:8096 -database cibc -retention default -since 2016-01-01T00:00:00Z ./backup 
2016/03/22 18:55:13 backing up rp=default since 2016-01-01 00:00:00 +0000 UTC
2016/03/22 18:55:13 backup failed: **invalid character 'H' looking for beginning of value**
backup: invalid character 'H' looking for beginning of value

**Comment by e-dard** [comment]
@lcrenix what version of Influx are you using?

**Comment by jwilder** [comment]
@lcrenix I think you are using the wrong port.  By default, the backup command connects to port `8088`.  If you have changed that port in your config, you should use that port for your `-host` option.

I get the error you logged because I'm trying to connect to `8086` and not `8088`.

```
$ influxd backup -host localhost:8086 -database foo -retention bar /tmp/foo
2016/03/22 13:56:32 backing up rp=bar since 0001-01-01 00:00:00 +0000 UTC
2016/03/22 13:56:32 backup failed: invalid character 'H' looking for beginning of value
backup: invalid character 'H' looking for beginning of value
```

**Comment by lcrenix** [comment]
@jwilder Yes, you are right. I think I should connect to 8086 (which has been changed to 8096 in my config) port like what I did for the Admin page, but I'm wrong, it should connect to 8088, not 8086. Thank you!
