### ISSUE TITLE
Counting distinct rows Influxdb query?

### ISSUE THREAD

**Issue by MartinSbs** [influxdata/influxdb#6098]
Good Morning

I have 10 rows and for each one I have a line number.
x x x x 154
y y y y 10
z z z z 200 (etc)

And I have a script that send to influx the next row and a random line (0-200). I want to count for my 10 rows how often a line is the same.
If I have x x x x 154 and the next time I get the same line, count 2 for my row x and the line 154.
When I try to aggregate this on grafana I can have the list of my 200 lines and a count for each one. But i would like to have on the same table my row x x x x | y y y y| ... which doesn't change and only the line and the counter change. On the pictures you can see that I have 3 time the same line and I want to have just one and refresh the line and the counter. Is it possible to do it with influx and then put it on grafana?

(I'm using Influxdb 0.10 and grafana 3.0)

![screenshot from 2016-03-22 10-26-54 1](https://cloud.githubusercontent.com/assets/17618554/13981074/24ddd810-f0e2-11e5-9a36-3df8e54b5a8d.png)

**Comment by jsternberg** [comment]
Can you try this with 1.0? I'm going to close this since I think it was probably just a storage engine bug in 0.10, but please comment if you still see the issue and I'll reopen the issue.
