### ISSUE TITLE
influx_tsm fails 11.0.1 and 0.9.6 failed: unsupported value type *tsdb.Value

### ISSUE THREAD

**Issue by pbooth** [influxdata/influxdb#6100]
I have an influxdb instance that had been upgraded from 0.94 to 0.9.6 to 0.10.0 to 0.11.1 
I attempted to convert the bz shard s but find that I consistently get (for all shards) the error
failed: unsupported value type *tsdb.Value

FWIW - I have about seven influxdb instance sranging from 0.9.4 though 0.11.1. This is the first time I've seen this error.

I don't know if this is relevant but I realized that my upload scripts, which write line protocol, didn't enforce that all measurement names were ascii. On some occasions some measuremenst were created with embedded control characters in their names

**Comment by gunnaraasen** [comment]
@pbooth Which version did you use to convert the shards? Version 0.10 is the only release that will convert `b1` and `bz1` shards to `tsm` format.

**Comment by pbooth** [comment]
Ahha - I was trying v 0.11

**Comment by gunnaraasen** [comment]
0.10.3 was the latest 0.10 release and should be used for converting shards when upgrading from 0.9.

Sounds like converting the shards with 0.10 worked so closing this out. Please comment if that's not the case.

**Comment by lukecyca** [comment]
I ran into this problem too while attempting to upgrade from 0.9.6.1 to 0.11.0 at once.

I downgraded to 0.10.0 temporarily and ran the `influx_tsm` conversion process, and it worked as expected. Then I upgraded to 0.11.0 and all seems well.

**Comment by FlorianLudwig** [comment]
@gunnaraasen Shouldn't upgrading a 0.9 database with 0.11 be supported?

**Comment by gunnaraasen** [comment]
@FlorianLudwig we may be cutting a 0.11.1 release with a fix to `influx_tsm` to allow direct 0.9 to 0.11 upgrades. I'll make sure this issue is referenced if/when that happens.
