### ISSUE TITLE
rename influx_tsm in 0.11+

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6104]
In InfluxDB 0.10, the `influx_tsm` binary was capable of converting `b1`/`bz1` shards to `tsm` shards, in addition to the other shard inspection functions.

In InfluxDB 0.11+ the `influx_tsm` binary is no longer capable of converting shards.

This is very likely to lead to user confusion during upgrades from 0.9 to 0.11+, as all upgrades from 0.9 reference the tool as the way to convert the existing shards to the `tsm` format.

To mitigate that, can we rename `influx_tsm` in 0.11+?

**Comment by jwilder** [comment]
This is a regression.  `influx_tsm` should still be able to convert those shards in later versions.
