### ISSUE TITLE
influxdb crash after create CQ

### ISSUE THREAD

**Issue by haowells** [influxdata/influxdb#6107]
create cq below:

create continuous query bandwidth_max_min on cdn resample every 2m for 30d begin select provider, max(value) into bandwidth_min_max from bandwidth group by time(24h) END

influxdb crash and logs show:

meta] 2016/03/24 10:37:46 127.0.0.1 - - [24/Mar/2016:10:37:46 +0800] GET /lease?name=continuous_querier&nodeid=0 HTTP/1.1 200 110 - Go 1.1 package http 64cc786f-f169-11e5-8653-000000000000 460.471µs
[continuous_querier] 2016/03/24 10:37:46 executing continuous query bandwidth_max_min (2016-03-24 08:00:00 +0800 CST to 2016-03-25 08:00:00 +0800 CST)
[query] 2016/03/24 10:37:46 SELECT provider, max(value) INTO cdn."default".bandwidth_min_max FROM cdn."default".bandwidth WHERE time >= '2016-03-24T00:00:00Z' AND time < '2016-03-25T00:00:00Z' GROUP BY time(1d)
panic: runtime error: index out of range

goroutine 21766 [running]:
github.com/influxdb/influxdb/tsdb.convertRowToPoints(0xc20ec017c0, 0x11, 0xc2084427e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/into.go:33 +0x769
github.com/influxdb/influxdb/tsdb.(_QueryExecutor).writeInto(0xc20805c4e0, 0xc2084427e0, 0xc20808c180, 0x0, 0x0)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/query_executor.go:770 +0x177
github.com/influxdb/influxdb/tsdb.(_QueryExecutor).executeStatement(0xc20805c4e0, 0x0, 0x7f11b02d5938, 0xc20808c180, 0xc208609d63, 0x3, 0xc208442660, 0x0, 0xc208442600, 0x0, ...)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/query_executor.go:721 +0x221
github.com/influxdb/influxdb/tsdb.func·024()
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/query_executor.go:168 +0xa07
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/query_executor.go:225 +0x242

goroutine 1 [chan receive, 1023 minutes]:
main.(*Main).Run(0xc20803b700, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cmd/influxd/main.go:96 +0x7a1
main.main()
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0xdc

goroutine 6 [syscall, 1023 minutes]:
os/signal.loop()
        /root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:27 +0x35

goroutine 116 [sleep]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(_Engine).compactTSMLevel(0xc208398f00, 0x1, 0x1)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:495 +0x17e
created by github.com/influxdb/influxdb/tsdb/engine/tsm1.(_Engine).Open
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:137 +0x296

**Comment by seiflotfy** [comment]
thanks for the report! Which version of influx is this so i can try to replicate it?

**Comment by haowells** [comment]
version is 0.10.1. tks

**Comment by jwilder** [comment]
Closing this since 0.10 is old and no longer maintained. If this is still occurring in 1.1, please open a new issue.
