### ISSUE TITLE
Equivalent continuous query not working on v0.11.0 but working on  0.10.3, CQ on v0.11 appears to be broken

### ISSUE THREAD

**Issue by ianlutzeigen** [influxdata/influxdb#6108]
Hi, I have the same query on two different versions, and the query should be supported by both versions. 

This works on v0.10.3:

when I do SHOW CONTINUOUS QUERIES... on both versions i get:
## name: testdb

name            query
down_sample     CREATE CONTINUOUS QUERY down_sample ON testdb BEGIN SELECT mean(value) INTO "testdb_down"."default".:MEASUREMENT FROM "testdb"."default"./testsim*/ GROUP BY time(1m) END

But the very same query on v0.11 (stable) does not work.

No CQ query that I can form works for with v0.11.

By "not working" i mean the CQ on v0.11 is NOT running, although it appears in SHOW CONTINUOUS QUERIES

**Comment by guanxudong** [comment]
the same issue to #6096

**Comment by e-dard** [comment]
@ianlutzeigen please upgrade to `1.1` and let us know if there is an issue.
