### ISSUE TITLE
yum update influxdb on CentOS 7 broke influxdb

### ISSUE THREAD

**Issue by willemdh** [influxdata/influxdb#6110]
Tried updating from 0.9.5.1 to 0.11.0-1 on CentOS 7. So I configure /etc/yum.repos.d/influxdb.repo as listed in https://docs.influxdata.com/influxdb/v0.11/introduction/installation/ and execute:

    yum update influxdb

Installation seemes successfully. Then I try to start the service, which fails.

    systemctl start influxdb
    Failed to start influxdb.service: Unit influxdb.service failed to load: No such file or directory.

Luckily I have a snapshot to which I reverted, so what can I do to make my upgrade work with yum?

**Comment by rossmcdonald** [comment]
@willemdh Thanks for letting us know. I'll test this locally to see if I can reproduce the issue.

**Comment by rossmcdonald** [comment]
@willemdh This turns out to be an issue with the upgrade path from 0.9 straight to 0.11. There was some logic in the 0.10 packages that corrected for this issue, but it was removed for the 0.11 release. 

The way to bypass the problem is to re-install the unit file:

```
$ sudo cp /usr/lib/influxdb/scripts/influxdb.service /etc/systemd/system/
$ sudo systemctl enable influxdb
```

Which should restore all service commands.

**Comment by willemdh** [comment]
@rossmcdonald It worked. Ithink I upgraded successfully now. Yum syas I'm on version  0.11.1-1, but the gui stillsyas 0.9.5. Is this a known issue?

![image](https://cloud.githubusercontent.com/assets/6462991/14206966/3a708826-f817-11e5-8ad2-b7e11e234f7f.png)

Did a shift refresh, still 0.9.5..

Just noticed InfluxDB service stops afetr 10 seconds since the upgrade. Still looking why, but I'll make a new thread for that..
