### ISSUE TITLE
Empty commands results after create retention policy

### ISSUE THREAD

**Issue by cesaroni** [influxdata/influxdb#6124]
Hi 
I'm running InfluxDB 0.11 on ubuntu server and telegraf
some commands like
SHOW SERIES and SHOW MEASUREMENTS 
give empty result after new default retention policy creation
Do I miss something?

> create database telegraf
# start telegraf ($ telegraf -config test.conf)
> SHOW SERIES LIMIT 1
key
cpu,cpu=cpu-total,host=myhost

> drop database telegraf
> create database telegraf
> CREATE RETENTION POLICY two_hours ON telegraf  DURATION 2h REPLICATION 1 DEFAULT
> show retention policies on telegraf
name            duration        replicaN        default
default         0               1               false
two_hours       2h0m0s          1               true

# start telegraf ($ telegraf -config test.conf)

all the commands SHOW SERIES, SHOW MEASUREMENTS 
give empty result

> SHOW SERIES FROM "telegraf"."default"."cpu"
empty result

**Comment by mark-rushakoff** [comment]
```
> show retention policies on _internal
name	duration	replicaN	default
monitor	168h0m0s	1		true
```

https://docs.influxdata.com/influxdb/v0.11/query_language/schema_exploration/#explore-retention-policies-with-show-retention-policies
