### ISSUE TITLE
Cluster Downgrading

### ISSUE THREAD

**Issue by jgerschk** [influxdata/influxdb#6130]
With the decision to remove clustering from the "free" version (for a lack of better terms at the moment) in the near future, is there an easy way to downgrade a current cluster to a single instance without data loss? 

Is there going to be support?

**Comment by jwilder** [comment]
There are [upgrading instructions](https://docs.influxdata.com/influxdb/v1.0/administration/upgrading/#upgrading-from-0-10-or-0-11-to-1-0) on the documentation site.
