### ISSUE TITLE
startup fails after upgrade from 0.10.0-0.beta1 to 0.10.0-1

### ISSUE THREAD

**Issue by j3ffrw** [influxdata/influxdb#6133]
Hi,
 After I upgraded from 0.10.0-0.beta1 to 0.10.0-1 influxd now fails to start w/ the ff error. Rolling back to 0.10.0-0.beta1 does makes it start again. I'm running a 3 node cluster.

2016/03/22 06:58:59 InfluxDB starting, version 0.10.0, branch 0.10.0, commit b8bb32ecad9808ef00219e7d2469514890a0987a, built 2016-02-04T17:06:04.850564
2016/03/22 06:58:59 Go version go1.4.3, GOMAXPROCS set to 2
2016/03/22 06:58:59 Using configuration at: /config/config.toml
run: create server: to upgrade a cluster, please contact support at influxdata

Here's my config file.
[meta]
  dir = "/data/influxdb/meta"
  hostname = "localhost"
  bind-address = ":8088"
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"

[data]
  dir = "/data/influxdb/db"
  max-wal-size = 104857600 # Maximum size the WAL can reach before a flush. Defaults to 100MB.
  wal-flush-interval = "10m0s" # Maximum time data can sit in WAL before a flush.
  wal-partition-flush-delay = "2s" # The delay time between each WAL partition being flushed.
  wal-dir = "/data/influxdb/wal"
  wal-enable-logging = true

[cluster]
  write-timeout = "5s" # The time within which a write operation must complete on the cluster.
  shard-writer-timeout = "5s" # The time within which a shard must respond to write.

[retention]
  enabled = true
  check-interval = "10m0s"

[admin]
  enabled = true
  bind-address = ":8083"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

[[graphite]]
  enabled = false
  bind-address = ":2003"
  protocol = "tcp"
  consistency-level = "one"
  separator = "."
  database = "graphitedb"
  batch-size = 1000
  batch-timeout = "1s"
  templates = [
     "instance.profile.measurement*"
 ]

[collectd]
  enabled = false

[opentsdb]
  enabled = false

[[udp]]
  enabled = false
  bind-address = ":4444"
  database = "udpdb"

[monitoring]
  enabled = false
  write-interval = "24h"

[continuous_queries]
  log-enabled = true
  enabled = true
  recompute-previous-n = 2
  recompute-no-older-than = "10m0s"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m0s"

[hinted-handoff]
  enabled = true
  dir = "/data/influxdb/hh"
  max-size = 1073741824
  max-age = "168h"
  retry-rate-limit = 0
  retry-interval = "1s"

Thanks in advance.

**Comment by jwilder** [comment]
@j3ffrw Upgrading a cluster does not work in the `0.10` release.  The [release notes](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#v0100-2016-02-04) state that you would need help help from support.
