### ISSUE TITLE
influx_tsm is not working correctly with relative paths

### ISSUE THREAD

**Issue by sbouchex** [influxdata/influxdb#6134]
I want to use influx_tsm to convert my db.

Source folder: /data/source
Backup folder: /data/source_bck

I'm using the following command from the /data folder : influx_tsm -backup source_bck source

And I'm getting an error : backup directory cannot be contained within data directory

This is due to the line "if strings.HasPrefix(o.BackupPath, o.DataPath) {" at line 123 in influxdb/cmd/influx_tsm/main.go which is not handling relative path correctly.

**Comment by jwilder** [comment]
@sbouchex You can't store your backup directory under your data directory.  You need to store your backups outside of the data directory.

**Comment by sbouchex** [comment]
@jwilder, my testcase is not the one you mention : Both folders are *different* and have 2 different full paths (/data/source and /data/source_bck)

The issue is in the code : The test is matching strings coming from the options instead of matching full file path based on the relative path.
A better code would detect if paths passed in the options are relative, if so rebuild a full path based on the current directory and the relative path, to get a full path before doing some matching.

**Comment by jwilder** [comment]
@sbouchex What does your config specify for:
```
[data]
dir = ?
```

**Comment by sbouchex** [comment]
dir = "/var/lib/influxdb/data"

But I did not want to migrate the database running ion a server but a backup of another production database running elsewhere. So I zipped the "data" folder and unzip in the /data_source folder
