### ISSUE TITLE
unsupported value type *tsdb.Value returned by influx_tsm

### ISSUE THREAD

**Issue by sbouchex** [influxdata/influxdb#6135]
I'm converting my database and I'm the following error:

`2016/03/28 16:17:18.630797 Failed to convert /root/arrondine/data/sondes/default/2: Conversion of /root/arrondine/data/sondes/default/2 failed: unsupported value type *tsdb.Value`

If needed, I can send you the db (in private message only)

Currently, my migration to 0.11 is on hold

**Comment by jwilder** [comment]
@sbouchex I believe you need to first upgrade to 0.10 and migrate your shards, then upgrade to 0.11.

**Comment by sbouchex** [comment]
OK, it works but how comes that I need to install an intermediary release in order to  migrate my database ? influx_tsm from any version should be able to migrate data from any version below the install one.

**Comment by jwilder** [comment]
@sbouchex It's a regression in 0.11.  The tool should work in 0.11, but currently does not.  We're investigating why.  The workaround is to upgrade to 0.10, migrate, then to upgrade 0.11.

**Comment by sbouchex** [comment]
OK thanks
