### ISSUE TITLE
InfluxDB v0.10 does not do a full restore

### ISSUE THREAD

**Issue by finneysm7** [influxdata/influxdb#6139]
Hi,

Currently, I am running a restore of the following databases and meta directories for my influxDB. I had around 3 weeks worth of data stored via influxDB before my instance went down. Fortunately, I performed a backup of my database right before my instance went down and put the backup files into s3. After pulling all of the files from s3 into my instance and running a restore, I only see about an hours worth of the data restored in grafana. The restore is very costly and takes around 30 minutes to run. At this point, it seems like the restore functionality simply does not work. 

Here is my backup command:

`influxd backup -database graphite /root/snapshots`

Here are my restore commands:

`rm -rf /var/lib/influxdb/meta/*
rm -rf /var/lib/influxdb/data/*
influxd restore -metadir /var/lib/influxdb/meta /root/snapshots/
influxd restore -database graphite -datadir /var/lib/influxdb/data /root/snapshots/`

As a side note, I am running influxdb in a docker container and I restore everytime I start the container.

The docker logs show about 102 lines of unpacking shards like so:
`unpacking /var/lib/influxdb/data/graphite/default/1/000000001-000000001.tsm
unpacking /var/lib/influxdb/data/graphite/default/2/000000211-000000002.tsm
unpacking /var/lib/influxdb/data/graphite/default/2/000000211-000000002.tsm`

So I assume that the restore is actually happening, but for whatever reason any data older than an hour (pretty much any data collectd from the other instance/container) gets thrown out. 

Any help that you could give me on this would be much appreciated.

Thanks,

Sean

**Comment by finneysm7** [comment]
Hi, it seems no one has checked or commented on this ticket since I posted it 15 days ago. This is still a prevalent issue that I am dealing with and it seems like InfluxDB simply does not have restore functionality. I would really like help on this. Thanks.

**Comment by timhallinflux** [comment]
This was fixed in v1.0.
https://docs.influxdata.com/influxdb/v1.0/administration/backup_and_restore/
