### ISSUE TITLE
Update Admin UI to retain previous queries

### ISSUE THREAD

**Issue by mindnuts** [influxdata/influxdb#6145]
Hi

Would it be possible to retain the previous history of queries run (HTML5 local storage?) on the Admin UI. It becomes tedious after a while if we need to repeat the query.![alt text](https://grammio.com/static/images/emoji/D83DDE4F.png "Pray folded hands")

**Comment by gunnaraasen** [comment]
Pressing the up arrow when focused on the query window should display previous queries in the admin UI. If that doesn't work, can you provide OS and browser info?

**Comment by mindnuts** [comment]
@gunnaraasen Thanks...i didn't knew it existed. BTW it was Chrome on Ubuntu 14.04. Closing the issue.
