### ISSUE TITLE
Upgrading from V0.9 to V0.11

### ISSUE THREAD

**Issue by lance5107B** [influxdata/influxdb#6156]
Form reading through some issues it appear that i need to upgrade to V0.10 before gong to V0.11

I cannot find a V0.10 deb package however.

Where can I find previous versions?

**Comment by rossmcdonald** [comment]
Here is a link to the latest 0.10 deb release:

https://s3.amazonaws.com/influxdb/influxdb_0.10.3-1_amd64.deb
