### ISSUE TITLE
influx_tsm panics with index out of range error.

### ISSUE THREAD

**Issue by symal29** [influxdata/influxdb#6169]
### Bug report

__System info: InfluxDB v 0.10.3 , CentOS 6.6

__Steps to reproduce:__

1. First upgraded from InfluxDB 0.9.5.1 - rpm -Uvh ./influxdb-0.9.5.1

2. Started influxdb service. Log file shows influxdb exited during startup with error "opentsdb+store:+failed+to+open+shard+4:+new+engine:+cannot+allocate+memory"

3. Run influx_tsm -backup /archive_data/backup/second_attempt -parallel /data/influxdb/

```
b1 and bz1 shard conversion.
-----------------------------------
Data directory is:        /data/influxdb
Backup directory is:      /data/backup/second_attempt
Databases specified:      all
Database backups enabled: yes 
Parallel mode enabled:    yes 4

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/boltdb/bolt.Open(0x1890a4b0, 0x27, 0x1b6, 0x18985c10, 0x0, 0x0, 0x0)
    /tmp/influxdb/src/github.com/boltdb/bolt/db.go:216 +0x57e
github.com/influxdb/influxdb/cmd/influx_tsm/tsdb.shardFormat(0x1890a4b0, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0)
    /tmp/influxdb/src/github.com/influxdb/influxdb/cmd/influx_tsm/tsdb/database.go:204 +0x15b
github.com/influxdb/influxdb/cmd/influx_tsm/tsdb.(*Database).Shards(0x1891c558, 0x0, 0x0, 0x0, 0x0, 0x0)
    /tmp/influxdb/src/github.com/influxdb/influxdb/cmd/influx_tsm/tsdb/database.go:172 +0x432
main.collectShards(0x1893b250, 0x2, 0x2, 0x0, 0x0, 0x0)
    /tmp/influxdb/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:242 +0x1c9
main.main()
    /tmp/influxdb/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:183 +0xb20

goroutine 6 [syscall]:
os/signal.loop()
    /root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.init·1
    /root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:27 +0x34

```

__Expected behavior:__ I expect influx_tsm to convert the 0.9.5.1 bz1 files to TSM as documented in the 0.10 upgrade document.

**Comment by jwilder** [comment]
@benbjohnson @joelegasse

**Comment by benbjohnson** [comment]
@symal29 A couple questions:

1. Does this happen consistently every time you run it?
2. How much RAM do you have on the machine?
3. Is this a 64-bit or 32-bit machine?

**Comment by symal29** [comment]
Yes it happens every time it run. The system is 64bit and have 20GB of ram. It seems it errors out while trying to open a particular file...

`strace -f -e open influx_tsm -backup ./tmpback ./data/influxdb
[ Process PID=7599 runs in 32 bit mode. ]
Process 7600 attached
Process 7601 attached
[pid  7599] open("/proc/sys/net/core/somaxconn", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
Process 7606 attached (waiting for parent)
Process 7606 resumed (parent 7599 ready)
Process 7607 attached (waiting for parent)
Process 7607 resumed (parent 7599 ready)
[pid  7599] open("/dev/urandom", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
[pid  7599] open("/data/backup/data/influxdb", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 4

b1 and bz1 shard conversion.
-----------------------------------
Data directory is:        /data/backup/data/influxdb
Backup directory is:      /data/backup/tmpback
Databases specified:      all
Database backups enabled: yes 
Parallel mode enabled:    no 1

[pid  7599] open("/data/backup/data/influxdb/_internal", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 4
[pid  7599] open("/data/backup/data/influxdb/_internal/monitor", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 5
[pid  7599] open("/data/backup/data/influxdb/_internal/monitor/94", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 6
[pid  7599] open("/data/backup/data/influxdb/_internal/monitor/95", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 6
[pid  7599] open("/data/backup/data/influxdb/_internal/monitor/101", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 6
[pid  7599] open("/data/backup/data/influxdb/_internal/monitor/96", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 6
[pid  7599] open("/data/backup/data/influxdb/_internal/monitor/97", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 6
[pid  7599] open("/data/backup/data/influxdb/_internal/monitor/93", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 6
[pid  7599] open("/data/backup/data/influxdb/_internal/monitor/100", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 6
[pid  7599] open("/data/backup/data/influxdb/_internal/monitor/99", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 6
[pid  7599] open("/data/backup/data/influxdb/mydb", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
[pid  7599] open("/data/backup/data/influxdb/mydb/default", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 7
[pid  7599] open("/data/backup/data/influxdb/mydb/default/42", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 8
[pid  7599] open("/data/backup/data/influxdb/mydb/default/74", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 4
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/boltdb/bolt.Open(0x18934280, 0x3b, 0x1b6, 0x18989c10, 0x0, 0x0, 0x0)
	/tmp/influxdb/src/github.com/boltdb/bolt/db.go:216 +0x57e
github.com/influxdb/influxdb/cmd/influx_tsm/tsdb.shardFormat(0x18934280, 0x3b, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/influxdb/src/github.com/influxdb/influxdb/cmd/influx_tsm/tsdb/database.go:204 +0x15b
github.com/influxdb/influxdb/cmd/influx_tsm/tsdb.(*Database).Shards(0x1891ca10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/influxdb/src/github.com/influxdb/influxdb/cmd/influx_tsm/tsdb/database.go:172 +0x432
main.collectShards(0x18938fe0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/tmp/influxdb/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:242 +0x1c9
main.main()
	/tmp/influxdb/src/github.com/influxdb/influxdb/cmd/influx_tsm/main.go:183 +0xb20

goroutine 6 [syscall]:
os/signal.loop()
	/root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.init·1
	/root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:27 +0x34`

If I move 74 out of the way then I get the following error:
`influx_tsm -backup ./tmpback ./data/influxdb

b1 and bz1 shard conversion.
-----------------------------------
Data directory is:        /data/backup/data/influxdb
Backup directory is:      /data/backup/tmpback
Databases specified:      all
Database backups enabled: yes 
Parallel mode enabled:    no 1

2016/03/31 17:05:59.790633 Failed to access shards for database mydb: file size too small`

How can I convert my bz2 files to tsm1? Even though I moved out that file shard that is not really a option because I don't want to lose data.

**Comment by symal29** [comment]
Never mind .. I downloaded the 32 bit by mistake. Trying with the 64bit rpm helped. Thanks for pointing this out,.
