### ISSUE TITLE
Reaching ulimit

### ISSUE THREAD

**Issue by sstarcher** [influxdata/influxdb#6185]
### Bug report

**System info:** 
- AWS r3.2xlarge - 64gb ram, 8 cpus
- Docker
- CoreOS 991.2.0 - beta
- InfluxDB 0.11.0
- Initial started with a clean DB at version 0.10.0

**Steps to reproduce:**
1. Send data via HTTP and Telegraf
2. Watch ulimit creep
3. reaches ulimit and AWS takes the server out due to an unreachable network

__Expected behavior: Server not crashing
__Actual behavior: Server crashing

**Additional info:** 
- The server sits around 30gb of RAM usage
- 80 serves running Telegraf 0.10.x
- A few other servers POSTing data via HTTP, but not in high volume
- Querying CPU, Memory, Diskspace from 1 server every 5 mins this spikes CPU load to 30% before dropping back down
- While sending all data influx lasts about 4 hours before reaching it's ULIMIT
- We turned off telegraf on all servers and the ULIMIT did not exceed 42k after 12 hours

**Comment by mark-rushakoff** [comment]
`ulimit` affects many resources. Which resource limit are you running into?

**Comment by sstarcher** [comment]
@mark-rushakoff I was seeing 42k + sockets open

**Comment by sstarcher** [comment]
My server has been running for about an hour so far.  This is with version 0.11.1
* lsof | wc -l = 26662
* lsof | grep socket | wc -l = 26315

**Comment by sstarcher** [comment]
After almost 2 hours I'm up to 
* lsof | wc -l = 52315
* lsof | grep socket | wc -l = 52047

**Comment by sstarcher** [comment]
I upgraded telegraf to 0.11.1 and the issue seems to have lessened. It ran for 12 hours last run, before hitting the ulimit and it has currently been up for 6 hours and `lsof | wc -l` is up to 32k

**Comment by sstarcher** [comment]
I dropped the telegraf database afterwards 40% of my memory was reclaimed.  Over the past 2 days the server has not crashed and has crept up 10%.  I'm wondering after the amount of data increases if that will put pressure back on the ulimit.

**Comment by krogon-intel** [comment]
Seems like sockets are not closed after sending data. I suppose this defer might not work
https://github.com/influxdata/influxdb/blob/e2cf94e62c680de60ecdb314a8f8f3ccea4be39a/client/influxdb.go#L299

**Comment by mark-rushakoff** [comment]
@krogon-intel [this commit to add a Connection: Close header](https://github.com/influxdata/influxdb/commit/8bdd44107fd870902f76f6fe2893efbdf1ec8e76) which is on master and the nightlies, due to be in 0.13, may address this socket leak.

**Comment by kamsz** [comment]
@mark-rushakoff Issue is still present in nightly.

**Comment by jwilder** [comment]
This may be a bug on the client side.  Telegraf was not able to close connections, but has been fixed.  See #6449.  

The intel snap plugin also looks like it might not be closing client connections.  See this [thread](https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/issues/51#issuecomment-215491810)
