### ISSUE TITLE
[0.11.1]: admin UI does not provide any feedback for successful but empty queries

### ISSUE THREAD

**Issue by jonseymour** [influxdata/influxdb#6193]
### Bug report

__System info:__

influxdb: 0.11.1 (local build)
operating systemn: ubuntu 14.04.4

__Steps to reproduce:__

1. execute a query that is expected to have no results: `select * from "database" where numSeries < 0`

__Expected behavior:__ [What you expected to happen]

A success message should be displayed, indicating that the query was accepted and processed successfully but no results were returned.

__Actual behavior:__ [What actually happened]

No results are displayed and no feedback is available to indicate to the user that the query was even accepted. Previously a green success message was displayed.

Other examples include:

`CREATE DATABASE foobar`
`DROP DATABASE foobar`
`SHOW SUBSCRIPTIONS`   # when there are no subscriptions

The `CREATE DATABASE` and `DROP DATABASE` cases also fail to report an error if the database already exists (or does not already exist, respectively).

__Additional info:__ 

- when testing different versions, ensure that you have used shift-F5 to ensure the browser reloads the JavaScript resources from the server
- the issue appears to have been introduced between v0.10.3 and v0.11.1

**Comment by jonseymour** [comment]
I bisected the commit that caused this issue down to 0cd440ea5c. /cc @toddboom

**Comment by jonseymour** [comment]
Fixed by #6194.

**Comment by toddboom** [comment]
@jonseymour Thanks for taking care of this! I've merged your PR into `master` and `0.12`, so future releases off of those branches will have this. I'll go ahead and merge it into the `0.11` branch, but we don't currently have any plans to cut another point release in the 0.11.x line.
