### ISSUE TITLE
Package should detect if its running in a container so it can install the correct service script

### ISSUE THREAD

**Issue by bdangit** [influxdata/influxdb#6198]
### Feature Request

**Proposal:** Package should detect if its running in a container so it can install the correct service script.

**Current behavior:** When I install influxdb inside of a Debian 8.2 or Ubuntu with SystemD, the package wants to install the systemd service. 

**Desired behavior:**  It should instead install the init.d script.  Or otherwise if the binary supports daemon mode.

**Use case:** We want to be able to setup the influxdb service with any predefined configs like user/password and tables at build time.
## 

cc: @sergioasantiago / @rennhak

**Comment by bdangit** [comment]
FYI,

There are 2 ways for a process to detect if its in a container or not: 

1. `cat /proc/1/cgroups`
2. `ls -al /.dockerinit`

**Comment by rossmcdonald** [comment]
Regarding the use case:

> We want to be able to setup the influxdb service with any predefined configs like user/password and tables at build time.

What prevents you from doing this when using systemd?

**Comment by bdangit** [comment]
in order to this, you need to run your container in priveledged mode and run the container at /sbin/init for access to systemd

**Comment by bdangit** [comment]
btw I can submit the PR for this if the authors agree with this feature.

**Comment by rennhak** [comment]
+1

**Comment by sergioasantiago** [comment]
:+1:

**Comment by fishnix** [comment]
:+1:

**Comment by majormoses** [comment]
> There are 2 ways for a process to detect if its in a container or not:
>
> 

> 1. cat /proc/1/cgroups
> 1. ls -al /.dockerinit

@bdangit I would think the first is more appropriate as its vendor agnostic.

**Comment by e-dard** [comment]
@rossmcdonald can you confirm if this is still an issue, and close this if it's been resolved?
