### ISSUE TITLE
Changing time control in Grafana brings down influxDB

### ISSUE THREAD

**Issue by ningxie1991** [influxdata/influxdb#6200]
I restarted influxDB, created datasource for my Grafana and imported the dashboards, but when I tried to change the time on the top right of Grafana, influxDB goes down for no reason. Any suggestions? I never happened before and I used the same query which is a selective query to the raw data (not open ended).

**Comment by gunnaraasen** [comment]
@ningxie1991 we do not have nearly enough information to attempt to debug this issue.

- What version of InfluxDB and Grafana are you using?
- What are some examples of the queries being run?
- Are there any errors in the logs? A gist of the stack trace would be extremely helpful.
