### ISSUE TITLE
v0.10 : SHOW MEASUREMENTS return 'no results to display'

### ISSUE THREAD

**Issue by sguilly** [influxdata/influxdb#6204]
Hi,

I use the tutum/influxdb:0.10 image to run influxdb.

I follow the documentation to update database to the new format tsm.

I use the command : influx_tsm -backup /tmp/influxdb_backup -parallel /data

The update seems to be correctly done : 

Summary statistics
========================================
Databases converted:                 3
Shards converted:                    44
TSM files created:                   44
Points read:                         166798889
Points written:                      166748443
NaN filtered:                        50446
Inf filtered:                        0
Points without fields filtered:      0
Disk usage pre-conversion (bytes):   4645847040
Disk usage post-conversion (bytes):  61156048
Reduction factor:                    98%
Bytes per TSM point:                 0.37
Total conversion time:               2m41.929137274s

I restart the docker container and try : 

SHOW SHARDS

timeseries
id	database	retention_policy	shard_group	start_time	end_time	expiry_time	owners
129	"timeseries"	"default"	129	"1780-02-07T00:00:00Z"	"1780-02-14T00:00:00Z"	"1780-02-14T00:00:00Z"	"1"
28	"timeseries"	"default"	28	"1969-12-29T00:00:00Z"	"1970-01-05T00:00:00Z"	"1970-01-05T00:00:00Z"	"1"
27	"timeseries"	"default"	27	"1970-01-12T00:00:00Z"	"1970-01-19T00:00:00Z"	"1970-01-19T00:00:00Z"	"1"
109	"timeseries"	"default"	109	"2015-06-08T00:00:00Z"	"2015-06-15T00:00:00Z"	"2015-06-15T00:00:00Z"	"1"
2	"timeseries"	"default"	2	"2015-10-12T00:00:00Z"	"2015-10-19T00:00:00Z"	"2015-10-19T00:00:00Z"	"1"
5	"timeseries"	"default"	5	"2015-10-19T00:00:00Z"	"2015-10-26T00:00:00Z"	"2015-10-26T00:00:00Z"	"1"
13	"timeseries"	"default"	13	"2015-10-26T00:00:00Z"	"2015-11-02T00:00:00Z"	"2015-11-02T00:00:00Z"	"1"
24	"timeseries"	"default"	24	"2015-11-02T00:00:00Z"	"2015-11-09T00:00:00Z"	"2015-11-09T00:00:00Z"	"1"
35	"timeseries"	"default"	35	"2015-11-09T00:00:00Z"	"2015-11-16T00:00:00Z"	"2015-11-16T00:00:00Z"	"1"
46	"timeseries"	"default"	46	"2015-11-16T00:00:00Z"	"2015-11-23T00:00:00Z"	"2015-11-23T00:00:00Z"	"1"
51	"timeseries"	"default"	51	"2015-11-23T00:00:00Z"	"2015-11-30T00:00:00Z"	"2015-11-30T00:00:00Z"	"1"
58	"timeseries"	"default"	58	"2015-11-30T00:00:00Z"	"2015-12-07T00:00:00Z"	"2015-12-07T00:00:00Z"	"1"
67	"timeseries"	"default"	67	"2015-12-07T00:00:00Z"	"2015-12-14T00:00:00Z"	"2015-12-14T00:00:00Z"	"1"
76	"timeseries"	"default"	76	"2015-12-14T00:00:00Z"	"2015-12-21T00:00:00Z"	"2015-12-21T00:00:00Z"	"1"
89	"timeseries"	"default"	89	"2015-12-21T00:00:00Z"	"2015-12-28T00:00:00Z"	"2015-12-28T00:00:00Z"	"1"
98	"timeseries"	"default"	98	"2015-12-28T00:00:00Z"	"2016-01-04T00:00:00Z"	"2016-01-04T00:00:00Z"	"1"
107	"timeseries"	"default"	107	"2016-01-04T00:00:00Z"	"2016-01-11T00:00:00Z"	"2016-01-11T00:00:00Z"	"1"
118	"timeseries"	"default"	118	"2016-01-11T00:00:00Z"	"2016-01-18T00:00:00Z"	"2016-01-18T00:00:00Z"	"1"
127	"timeseries"	"default"	127	"2016-01-18T00:00:00Z"	"2016-01-25T00:00:00Z"	"2016-01-25T00:00:00Z"	"1"
137	"timeseries"	"default"	137	"2016-01-25T00:00:00Z"	"2016-02-01T00:00:00Z"	"2016-02-01T00:00:00Z"	"1"
146	"timeseries"	"default"	146	"2016-02-01T00:00:00Z"	"2016-02-08T00:00:00Z"	"2016-02-08T00:00:00Z"	"1"
155	"timeseries"	"default"	155	"2016-02-08T00:00:00Z"	"2016-02-15T00:00:00Z"	"2016-02-15T00:00:00Z"	"1"
164	"timeseries"	"default"	164	"2016-02-15T00:00:00Z"	"2016-02-22T00:00:00Z"	"2016-02-22T00:00:00Z"	"1"
173	"timeseries"	"default"	173	"2016-02-22T00:00:00Z"	"2016-02-29T00:00:00Z"	"2016-02-29T00:00:00Z"	"1"
182	"timeseries"	"default"	182	"2016-02-29T00:00:00Z"	"2016-03-07T00:00:00Z"	"2016-03-07T00:00:00Z"	"1"
191	"timeseries"	"default"	191	"2016-03-07T00:00:00Z"	"2016-03-14T00:00:00Z"	"2016-03-14T00:00:00Z"	"1"
200	"timeseries"	"default"	200	"2016-03-14T00:00:00Z"	"2016-03-21T00:00:00Z"	"2016-03-21T00:00:00Z"	"1"
209	"timeseries"	"default"	209	"2016-03-21T00:00:00Z"	"2016-03-28T00:00:00Z"	"2016-03-28T00:00:00Z"	"1"
218	"timeseries"	"default"	218	"2016-03-28T00:00:00Z"	"2016-04-04T00:00:00Z"	"2016-04-04T00:00:00Z"	"1"
227	"timeseries"	"default"	227	"2016-04-04T00:00:00Z"	"2016-04-11T00:00:00Z"	"2016-04-11T00:00:00Z"	"1"
79	"timeseries"	"default"	79	"2026-09-14T00:00:00Z"	"2026-09-21T00:00:00Z"	"2026-09-21T00:00:00Z"	"1"
80	"timeseries"	"default"	80	"2026-09-21T00:00:00Z"	"2026-09-28T00:00:00Z"	"2026-09-28T00:00:00Z"	"1"
81	"timeseries"	"default"	81	"2026-10-05T00:00:00Z"	"2026-10-12T00:00:00Z"	"2026-10-12T00:00:00Z"	"1"
82	"timeseries"	"default"	82	"2026-10-12T00:00:00Z"	"2026-10-19T00:00:00Z"	"2026-10-19T00:00:00Z"	"1"
40	"timeseries"	"default"	40	"2192-10-29T00:00:00Z"	"2192-11-05T00:00:00Z"	"2192-11-05T00:00:00Z"	"1"

but if i try : 

SHOW MEASUREMENTS

Success! (no results to display)

The TSM conversion tool find 166798889 points

Where are these points?

How i can access to the raw data ?

Thanks for your help.

**Comment by sguilly** [comment]
influxd start with the wrong influxd.conf

**Comment by kaoruu** [comment]
Also happened to me. Some database migrated properly but the biggest database I have does not show any measurements. I think this is not a configuration issue.
