### ISSUE TITLE
continuous queries are padding with 0 and nulls by default v0.11.1, order by DESC broken as well

### ISSUE THREAD

**Issue by ianlutzeigen** [influxdata/influxdb#6206]
Hi

I am running a bunch of CQs on "testdb" that downsample into a separate db called "testdb_downsampled"

What i am observing is that there are both "nulls" and "0s" for the sections of data where there is no data to be downsampled. Some CQs have zero some have none. I have not specified a fill type so it should be "null". These zeros are wrong....

note DESC is broken as well: what is with those time stamps ? 

(note i have tested all this agains v.10.3 and that behaves as I would expect)
<img width="1440" alt="screen shot 2016-04-05 at 09 16 00" src="https://cloud.githubusercontent.com/assets/18043069/14266924/4c9ced00-fb0f-11e5-84f1-5a62e4cf74b7.png">

<img width="1440" alt="screen shot 2016-04-05 at 09 11 38" src="https://cloud.githubusercontent.com/assets/18043069/14266811/6e479ce4-fb0e-11e5-8dc1-1a47e352fc40.png">

<img width="1440" alt="screen shot 2016-04-05 at 09 09 02" src="https://cloud.githubusercontent.com/assets/18043069/14266788/2d1024b2-fb0e-11e5-8fc3-9545ae04d293.png">

**Comment by ericremoreynolds** [comment]
Hello, I have noticed a similar issue, I think it might be related.

Steps to reproduce:

1) `CREATE DATABASE "x"`
2) Write following data to db
```
y a=1 1212105600000000000
y b=2 1212019200000000000
```
3) `SELECT * FROM y`

![image](https://cloud.githubusercontent.com/assets/5197585/14288911/f33927ac-fb58-11e5-9afd-501dbdddd44e.png)

b gets padded with 0, a gets padded with null

Seems inconsistent, in particular padding with default value 0 is annoying because 0 means that a value is present and equal to zero, whereas null means value is not present.

**Comment by ericremoreynolds** [comment]
Note I am running 0.11.1, only just noticed new version is now available. Will upgrade and check if bug is still present.

**Comment by jsternberg** [comment]
I'm able to reproduce the bug. Thanks @ericremoreynolds.

**Comment by ericremoreynolds** [comment]
Confirm that it didn't happen with 0.10.3

**Comment by jsternberg** [comment]
@ianlutzeigen can you give me a way to reproduce the `ORDER BY desc` bug? I'm able to reproduce the zeroes bug and have a fix ready for it, but I want to try and get both of those fixes in case we decide to do a patch release.

**Comment by jsternberg** [comment]
I think I managed to reproduce the `ORDER BY desc` bug using the same input @ericremoreynolds gave me. I've made a PR for fixing `ORDER BY desc` and the default value bug as part of #6222.
