### ISSUE TITLE
Build in anomaly detection function in influxdb

### ISSUE THREAD

**Issue by dengliu** [influxdata/influxdb#6208]
### Feature Request

__Proposal:__ Build in anomaly detection in influxdb

__Use case:__ 
It would be nice to see holt-winter and some build-in time series anomaly detection functions in influx QL.
E.g. https://blog.twitter.com/2015/introducing-practical-and-robust-anomaly-detection-in-a-time-series
http://robjhyndman.com/hyndsight/yahoo-data/

With this support, people should be able to see visualize  anomalies that happened in the history and be able to set the alert rule more accurately. 

Kapacitor for sure is able to integrate with UDF to detect anomaly. However it just reports the results with predefined rule and doesn't give user a good experience of visualizing the anomalies levels over a continuous  time span.
having buildin anomaly detection in InfluxDB allows people to visualize the anomaly status via viz tools (e.g, Grafana), and thus have a better idea of tunning the anomaly detection system.
An example of visualizing anomalies like visualizing regular metric is as below
![figure_localglobal_anomalies](https://cloud.githubusercontent.com/assets/5108773/14290218/0ab8baa0-fb13-11e5-8e9d-dca7b61a76cf.png)

**Comment by rossmcdonald** [comment]
I believe the next release of [Kapacitor](https://github.com/influxdata/kapacitor) is going to have a built-in anomaly detection function, so I wouldn't expect this to be added to InfluxDB. Kapacitor also has support for [User-Defined Functions](https://docs.influxdata.com/kapacitor/latest/nodes/u_d_f_node/) (UDF's), so custom anomaly detection functionality can be written if needed.

**Comment by dengliu** [comment]
Kapacitor for sure is able to integrate with UDF to detect anomaly. However it is just report the results with predefined rule and doesn't give user a good experience of visualizing the anomalies levels over a continuous  time span.
having buildin anomaly detection in InfluxDB allows people to visualize the anomaly status via viz tools (e.g, Grafana), and thus have a better idea of tunning the anomaly detection system.
An example of visualizing anomalies like visualizing regular metric is as below
<img width="1426" alt="screen shot 2016-04-05 at 12 25 59 am" src="https://cloud.githubusercontent.com/assets/5108773/14290204/f3059b44-fb12-11e5-8f8c-8653c6d4983b.png">

**Comment by e-dard** [comment]
@dengliu InfluxDB shouldn't be responsible for things like this. The pipeline should be that other tools (e.g., Kapacitor) take InfluxDB data  and perform the anomaly detection analysis, and then optionally feed that data back into InfluxDB, which can then be visualised using whatever visualisation tool is in play.
