### ISSUE TITLE
Failure to run on Windows

### ISSUE THREAD

**Issue by mvadu** [influxdata/influxdb#6223]
This is a repeating pattern with InfluxDB, every now and then a PR will introduce a `os.rename` which breaks the Windows compatibility due to the way OS works. Latest example being https://github.com/influxdata/influxdb/commit/a961ff9ebf1c5d944ce2a8856f03519d8988d70c broke the Windows version as it removed the `f.Close()` and tried to rename. 

Now we are getting 
```go
[monitor] 2016/04/05 23:12:55 failed to create retention policy 'monitor', failed to create internal storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: The process cannot access the file because it is being used by another process.
[monitor] 2016/04/05 23:12:55 failed to store statistics: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: The process cannot access the file because it is being used by another process.
[monitor] 2016/04/05 23:13:05 failed to create retention policy 'monitor', failed to create internal storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: The process cannot access the file because it is being used by another process.
```

**Comment by mvadu** [comment]
If mods are okay, I would like to keep this issue open as its a reoccurring issue with Influx due to the nature of the project, and its heavy *nix orientation.

**Comment by gunnaraasen** [comment]
Sounds like this would be best solved by running continuous integration tests on Windows builds.

**Comment by joelegasse** [comment]
I do not think keeping this issue open will solve anything. We already have #5359 to track windows support. Windows is still not officially supported, so until that time, we'll have to rely on bug reports like this when changes cause issues due to quirks in windows.
