### ISSUE TITLE
can no longer re-assign bind address "8088" for v12

### ISSUE THREAD

**Issue by ianlutzeigen** [influxdata/influxdb#6230]
Hi I have multiple versions of influxdb running on one machine. In order to do this, i have given each its own set of ports more or less with prefix {versionnumber}port...

E.G: for v.10.3
web-admin: 10383
http-thingy:10386
etc (i have changed other ports)

ianlutz@influxdb-test:/opt/influxdb-0.10.3-1/etc/influxdb$ cat influxdb.conf | grep "address ="
  bind-address = ":10388"
  http-bind-address = ":10391"
  bind-address = ":10383"
  bind-address = ":10386"
  # bind-address = ":2003"
  # bind-address = ""
  # bind-address = ":4242"
  # bind-address = ""
ianlutz@influxdb-test:/opt

despite a few differences in config/layout/omissions for all the versions:
ianlutz@influxdb-test:/opt/influxdb-0.10.3-1/etc/influxdb$ ls /opt/
influxdb-0.10.3-1  influxdb-0.11.0-1  influxdb-0.12.0-1  influxdb_0.9.6

I am able to change all the ports that these guys (except v12) to use to a different port so they don't collide...

Now, I am unable to get v12 to change its port
..under the [meta] section i have added:
  bind-address = ":1288"
  http-bind-address = ":1291"

as with the other versions of influxdb

[meta]
  # Where the metadata/raft database is stored
  dir = "/opt/influxdb-0.12.0-1/var/lib/influxdb/meta"

  retention-autocreate = true

  bind-address = ":1288"
  http-bind-address = ":1291"

  # If log messages are printed for the meta service
  logging-enabled = true
  pprof-enabled = false

  # The default duration for leases.
  lease-duration = "1m0s"

------

now for v12 it is still evidently using :8088 instead of 1288:

ianlutz@influxdb-test:/usr/lib/systemd/system$ /opt/influxdb-0.12.0-1/usr/bin/influxd -config /opt/influxdb-0.12.0-1/etc/influxdb/influxdb.conf

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

[run] 2016/04/06 01:39:02 InfluxDB starting, version 0.12.0, branch 0.12, commit 4f29ba4013f6f46efeaa948bb7e0fd561cac5e95
[run] 2016/04/06 01:39:02 Go version go1.4.3, GOMAXPROCS set to 4
[run] 2016/04/06 01:39:02 Using configuration at: /opt/influxdb-0.12.0-1/etc/influxdb/influxdb.conf
run: open server: listen: listen tcp :8088: bind: address already in use

(yes I could shutdown another instance of influxdb using the default port but that doesnt solve the problem)

**Comment by tony-brewerio** [comment]
Also got bit by this while updating influxdb today, had to check the source code.
Apparently, they moved this setting to the top level of config, so just put your bind-address line before any [] blocks.

**Comment by ianlutzeigen** [comment]
excellent thanks! doing just that now :)

**Comment by e-dard** [comment]
@ianlutzeigen that's right (thanks @tony-brewerio). You can run `influxd config` to see an appropriate sample configuration file.
