### ISSUE TITLE
I/O Behaviour after Upgrade to 0.12.0-1

### ISSUE THREAD

**Issue by mnietz** [influxdata/influxdb#6238]
Today i have updated InfluxDB from Version 0.11.1 to 0.12.0-1 on a Debian 8.4 Box. My Dataset is pretty small (500MB Data, 100 Points per Second). Upon now only 12 Systems uses Influx to fill Data from Collectd

I'm a bit surpised about the I/O Behaviour after the Upgrade. With the previous version i had about 70 Write IOPS (300 KiB) now i have 300 IOPS (1.34 Mib).  

Is this an expected behaviour ?

![bildschirmfoto vom 2016-04-06 16 09 07](https://cloud.githubusercontent.com/assets/8960791/14319848/0e4f2ff4-fc13-11e5-82c5-77252bd1959f.png)

![bildschirmfoto vom 2016-04-06 16 08 36](https://cloud.githubusercontent.com/assets/8960791/14319853/12c9d7be-fc13-11e5-8018-4ee2f05c0ebf.png)

I have another Setup with a much larger Dataset and i'm worried about upgrading this one.

**Comment by simnv** [comment]
I also have this problem. strace shows that it is a constant writing to meta/meta.dbtmp file. It's funny how such small file responsible for a most of disk io.

**Comment by simnv** [comment]
My adventures with influxdb I/O: #6058

**Comment by toddboom** [comment]
@mnietz This should be resolved in `v0.12.1`. Let me know if you still see problems after upgrading and I can reopen this issue.

**Comment by mnietz** [comment]
yes, indeed it is. Thanks for the fix!

![bildschirmfoto vom 2016-04-16 09 51 10](https://cloud.githubusercontent.com/assets/8960791/14579830/c8d53344-03b8-11e6-83a1-3a9eeeceda88.png)
