### ISSUE TITLE
v0.10 - Too many CQ's cause backup in system

### ISSUE THREAD

**Issue by jhorwit2** [influxdata/influxdb#6242]
System: centos7 w/ 32gb ram and 16 cores. 

I noticed that enough continuous queries (around 10) cause backups where the queries cannot execute in time. Each CQ does a group by with a cardinality of around 2-10 depending on the CQ. This ultimately causes loss of data in CQ output because of how the code is written. 

I guess a feature request is to make the CQ service more resilient by using more than one goroutine to execute the CQs.

**Comment by jonseymour** [comment]
Can I ask what period your CQs are designed to execute at?

**Comment by jhorwit2** [comment]
They are all 1m buckets.

**Comment by jonseymour** [comment]
Could you give an example of one of your CQs?

**Comment by jsternberg** [comment]
Please try 1.0. We improved CQ performance a lot since 0.10. Thanks.
