### ISSUE TITLE
[0.12.0] Higher heap usage

### ISSUE THREAD

**Issue by ljagiello** [influxdata/influxdb#6243]
Shortly after upgrade InfluxDB from 0.11.1 -> 0.12.0 (official deb packages, Ubuntu 14.04) I've noticed higher memory usage and higher heap usage (metrics from _internal):

![Heap InUse/Idle](http://i.imgur.com/MRK61w9.png)
![Heap Alloc/Sys](http://i.imgur.com/TJaZ09w.png)

**Comment by jpereira** [comment]
@ljagiello Hi! how was the scheme to add the influx into the grafana? appreciate any kind of help.

**Comment by ljagiello** [comment]
@jpereira `_internal` database and queries like: 
```
SELECT last("HeapAlloc") FROM "runtime" WHERE "hostname" =~ /$server$/ AND $timeFilter GROUP BY time($interval), "hostname" fill(null)
```

**Comment by hgfischer** [comment]
I have the felling there there is some memory leak going on:

![screenshot 2016-04-15 13 07 43](https://cloud.githubusercontent.com/assets/120860/14559820/b1a860a4-030b-11e6-9b23-97d3a3b70bcb.png)

**Comment by whitelynx** [comment]
I wonder if #5169 would help alleviate this.

**Comment by jwilder** [comment]
@ljagiello Can you grab a heap and goroutine snapshot when your system heap is growing?

```
curl -o heap.txt http://localhost:8086/debug/pprof/heap?debug=1
curl -o goroutine.txt http://localhost:8086/debug/pprof/goroutine?debug=1
```

**Comment by ljagiello** [comment]
Sure I will.

**Comment by ljagiello** [comment]
@jwilder I was able to catch such crash:
- https://www.dropbox.com/s/ehwab8kogusq4yb/goroutine.txt.bz2
- https://www.dropbox.com/s/p18ra5k7006u6pj/heap.txt.bz2

**Comment by jwilder** [comment]
@ljagiello It looks like you have a bunch of writes getting blocked validating field types for measurements.  

* How many measurements do you have?
* How many fields for each measurement?  
* How big are your batches for each write?
* How many concurrent writers do you have?

**Comment by ljagiello** [comment]
> * How many measurements do you have?

```
:~# influx -database 'telegraf' -execute 'SHOW MEASUREMENTS' | wc -l
259
:~# influx -database 'telegraf' -execute 'SHOW SERIES' | wc -l
59018
:~# influx -database 'services' -execute 'SHOW MEASUREMENTS' | wc -l
12
:~# influx -database 'services' -execute 'SHOW SERIES' | wc -l
20509
```
> * How many fields for each measurement?

```
:~# influx -database 'telegraf' -execute 'SHOW FIELD KEYS' -pretty | wc -l
90323
```
where few are a pretty big:
```
httpjson_solrcore1 - 30928
httpjson_solrcore2 - 50481
```
> * How big are your batches for each write?

- telegraf - default for 0.12
- services - 1000

> * How many concurrent writers do you have?

![graph1](http://i.imgur.com/3Qa1Eih.png)

**Comment by ljagiello** [comment]
Ok after some changes in telegraf I was able to reduce fields
```
:~# influx -database 'telegraf' -execute "SHOW FIELD KEYS" | wc -l
5074
```
so it's x18 times less fields.

**Comment by jwilder** [comment]
@ljagiello Let me know if that has any effect on your heap.  The code from the profile you grabbed could be tuned to reduce locking in that spot as well.

Also, am I reading this correctly that you have two measurements with 30k & 50k fields each?

```
httpjson_solrcore1 - 30928
httpjson_solrcore2 - 50481
```

**Comment by ljagiello** [comment]
So without any solr metrics today there was another crash unfortunately I wasn't around to dump heap but I will wait for another one.

My another ticket is basically duplicate of this one (https://github.com/influxdata/influxdb/issues/6526).

**Comment by ljagiello** [comment]
https://www.dropbox.com/s/67ao48g1dfbjo9j/heap-graph-s5-2016-05-07-06-15.txt.bz2?dl=0
https://www.dropbox.com/s/xsh8l3l8pglrm3k/heap-graph-s5-2016-05-07-06-10.txt.bz2?dl=0
https://www.dropbox.com/s/tkw5bm7kg7e25pm/heap-graph-s5-2016-05-07-06-05.txt.bz2?dl=0
https://www.dropbox.com/s/1s85ec84hcv8imv/goroutine-graph-s5-2016-05-07-06-15.txt.bz2?dl=0
https://www.dropbox.com/s/jjhjk92fl10pglq/goroutine-graph-s5-2016-05-07-06-10.txt.bz2?dl=0
https://www.dropbox.com/s/thq750htaoandyj/goroutine-graph-s5-2016-05-07-06-05.txt.bz2?dl=0

Crash happen randomly but always after new shard was created. Above links provides goroutine/heap dumps 5/10/15min past shard creation, after next 15min InfluxDB crashed.

I see this problem every ~24-30h. All those huge measurements are off now and they're not in any new indexes. The biggest measurements is mysql with 329 fields, all others are below 20.
```
:~# influx -execute "SHOW SERIES" -database "telegraf" | sed '/name: .*/d' | sed '/\-\-/d' | sed '/_key/d' | sed '/^$/d' | wc -l
59290
```

**Comment by jwilder** [comment]
Is this still occuring w/ the latest nightlies?

**Comment by pbek** [comment]
Thank you for the hint, I will test that first thing in the morning!

**Comment by ljagiello** [comment]
@jwilder since 0.13 it's super stable.

**Comment by jwilder** [comment]
Thanks @ljagiello

**Comment by intelfx** [comment]
@hgfischer Sorry for off-topic and necro-posting, but could you please share your influxdb metric dashboard?
