### ISSUE TITLE
High CPU usage and slow query with DISTINCT

### ISSUE THREAD

**Issue by paolo-ran** [influxdata/influxdb#6261]
### Bug report

__System info:__ 
InfluxDB 0.12 (single node, no cluster)
Ubuntu 14.04.2 LTS 
[m3.large EC2 instance](https://aws.amazon.com/ec2/instance-types/)

__Steps to reproduce:__

1. Create a database and a table with 7.415.120 floating point values (from 0 to 1 with max 2 decimals);
2. Execute the query SELECT count(distinct(value)) FROM 'table' and measure the time it takes.

__Expected behavior:__

Excellent response time (~1s) due to the relatively small dataset and simple query.

__Actual behavior:__

In the m3.large instance I am using to test InfluxDB the query above takes 16 seconds and the CPUs spike and stay at 100% throughout that time.

RAM: max 39%.
Uptime: 2 days.

__Additional info:__ 

The actual behavior does not match my expectation and it has disappointed me. However, I am actually wondering if it matches yours and such of performance is legit and expected by the architect.

I am willing to share additional information or support by profiling this issue under your supervision, if needed.

**Comment by jsternberg** [comment]
@paolo-ran can you try building from the branch `js-6261-optimize-distinct` and telling me if this improves the performance at all?

I've tried modifying distinct to not require as much memory as it previous did. Initial testing with our stress tool brings `select distinct(value) from cpu` down to 17 seconds from 31 seconds.

**Comment by paolo-ran** [comment]
Hi jsternberg.

I have tried the same query on the same dataset with the branch you have mentioned:
- CPU: > 100%;
- response time: 9 seconds

For the record, there are 57 distinct values within the set of 7.415.120.

**Comment by jsternberg** [comment]
Well at least that's a better response time. @benbjohnson would some of the memory allocation improvements to the query engine be relevant to this issue?

**Comment by benbjohnson** [comment]
@jsternberg The distinct implementation is naive and we need to change it to something more memory efficient. It's using the slice reducer which means it's collecting all 7M points in a slice (since there's no `GROUP BY`).

We need a specific map-based implementation of the distinct iterator and then we should see performance numbers of 1-2 seconds. We can get subsecond once we parallelize the iterators. We could also special case a distinct implementation at the tsm cursor level which would be really fast.

**Comment by paolo-ran** [comment]
Those are the answers I was expecting. Thanks @jsternberg, @benbjohnson.

**Comment by jsternberg** [comment]
@paolo-ran @benbjohnson recently merged his commit to reduce allocations. I just rebased the branch I mentioned before to include that and my changes. Can you try it? In my own local testing, I didn't see a lot of change between them, but I'm curious how it works on your data set.

Also, how many distinct values do you have?
