### ISSUE TITLE
cannot escape the keyword "tag" for various queries, some queries it works sometimes it doesnt 

### ISSUE THREAD

**Issue by ianlutzeigen** [influxdata/influxdb#6265]
Hi All
this query is good: SELECT units, "tag", description FROM METADATA
this query is good: SELECT "tag", description FROM METADATA
 this query is good: SELECT "tag", units FROM METADATA

this query is bad: SELECT "tag" FROM METADATA

returns no data on v12.0
on v96 i get an error

This is the schema:

METADATA
time	                                  tag	            units	description
1970-01-01T00:00:00Z	"egtesta-a3"	""	"egtesta-a3"
1970-01-01T00:00:00Z	"egtestd-a1b"	""	"egtestd-a1b"
1970-01-01T00:00:00Z	"egtesta-c2"	""	"egtesta-c2"
...
.

Thanks!

**Comment by jsternberg** [comment]
You must select at least one field as part of a SELECT query. It's not possible to select only a tag. Is "tag" a tag or a field?

**Comment by ianlutzeigen** [comment]
METADATA  is the name of the measurement
It has 4 columns, and these are the column headers: time, tag, units, description
I would call the columns tag, units, description "fields" of the measurement METADATA


in this example there is no difference between the columns "tag" and "description", they are either both tags (by influx definitio ) or by fields (by influx definition), the only difference is the colomn header (field key). I can return data from "description" column but not the "tag" column.

I dont see where one defines a column to be a field or otherwise, except that perhaps its going on the data itself..

thanks!

**Comment by jsternberg** [comment]
Can you show me how the data is inserted using the line protocol?

**Comment by ianlutzeigen** [comment]
METADATA,tag=NewTag description="Bar",units="Foo" 0


the above string is http-posted to my influxdb instance...and it creates an entry into the METADATA "table"


METADATA
time	description	tag	units
1970-01-01T00:00:00Z	""	"generated-tag1"	""
1970-01-01T00:00:00Z	"Bar"	"NewTag"	"Foo"


Thanks! :)

**Comment by jsternberg** [comment]
In the line protocol you just showed me, the `tag` seems to be a tag. You can't select tags by themselves. You can only select a tag as part of also selecting a field. So you can do one of these:

```
SELECT description, tag FROM METADATA;
SELECT units, tag FROM METADATA;
```

One of those will work, but selecting only tag will not work.

**Comment by ianlutzeigen** [comment]
OK thanks very much for your help.

In the context of my company, a tag is a measurement and a field is..well..a field. In our context there is no other meaning of tag, so hence I was getting a little confused.

Clearly we need to not use a the keyword tag...

Thanks

**Comment by jsternberg** [comment]
Ok. I'm going to close this then since I think I've clarified the behavior of that query. If you have any other questions, please use the [email list](https://groups.google.com/forum/#!forum/influxdb).
