### ISSUE TITLE
Influxdb 0.10/ 0.1x -- C library ?

### ISSUE THREAD

**Issue by MartinSbs** [influxdata/influxdb#6267]
Good morning
I have found the C library for influx < 0.9, and I'm looking for one working with influx 0.10. Does someone has any idea or has already been working on that?

**Comment by jsternberg** [comment]
Hello @MartinSbs 

You'll likely get an answer much faster on the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb). The issue tracker is mostly for bugs and features related to InfluxDB.

Thanks!
