### ISSUE TITLE
DropSubscription() null pointer panic

### ISSUE THREAD

**Issue by datastream** [influxdata/influxdb#6274]
### Bug report

__System info:__ 
InfluxDB version: v0.10.0, branch HEAD, commit b8bb32ecad9808ef00219e7d2469514890a0987a
os: debian 7 amd64

__Steps to reproduce:__

1. run drop subscription

> DROP SUBSCRIPTION "kapacitor-23b8d82b-a399-4166-a711-1456643fed49" ON "xxx"."default"

`
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0x5aace1]

goroutine 5 [running]:
github.com/influxdb/influxdb/services/meta.(*Data).DropSubscription(0xc8222a6ab0, 0xc821115dc1, 0x9, 0xc821115ff0, 0x7, 0xc823218450, 0x2e, 0x0, 0x0)
        /home/datastream/gopackages/src/github.com/influxdb/influxdb/services/meta/data.go:606 +0xc1
github.com/influxdb/influxdb/services/meta.(*storeFSM).applyDropSubscriptionCommand(0xc820016090, 0xc82326db90, 0x0, 0x0)
        /home/datastream/gopackages/src/github.com/influxdb/influxdb/services/meta/store_fsm.go:404 +0x1b1
github.com/influxdb/influxdb/services/meta.(*storeFSM).Apply.func1(0xc82326db90, 0xc820016090, 0xc820016090, 0xc822d0dcc0, 0x0, 0x0)
        /home/datastream/gopackages/src/github.com/influxdb/influxdb/services/meta/store_fsm.go:66 +0x6c5
github.com/influxdb/influxdb/services/meta.(*storeFSM).Apply(0xc820016090, 0xc822d0dcc0, 0x0, 0x0)
        /home/datastream/gopackages/src/github.com/influxdb/influxdb/services/meta/store_fsm.go:29 +0x2b7
github.com/hashicorp/raft.(*Raft).runFSM(0xc8201f81c0)
        /home/datastream/gopackages/src/github.com/hashicorp/raft/raft.go:564 +0xeb1
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
        /home/datastream/gopackages/src/github.com/hashicorp/raft/raft.go:253 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8201f81c0, 0xc82000e420)
        /home/datastream/gopackages/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /home/datastream/gopackages/src/github.com/hashicorp/raft/state.go:153 +0x4d
`

**Comment by e-dard** [comment]
@datastream thanks for the report. This bug was fixed in #5861, and was part of the `0.10.2` release.
