### ISSUE TITLE
Link to docs in Admin UI out-of-date

### ISSUE THREAD

**Issue by dmke** [influxdata/influxdb#6280]
### Bug report

__System info:__ InfluxDB 0.12, Debian Jessie

__Steps to reproduce:__

1. open [Admin UI](http://localhost:8083)
2. click on "Documentation" in the header

![image](https://cloud.githubusercontent.com/assets/327411/14428708/7bcd2e1a-fffa-11e5-8068-acd43d1d5b72.png)

__Actual behavior:__ Documentation links to 0.10 docs

![image](https://cloud.githubusercontent.com/assets/327411/14428868/37d91984-fffb-11e5-9687-2ccae6911f7d.png)

__Expected behavior:__ Documentation should either link to:

1. Server version (as denoted in the footer)
2. Client version (i.e. Admin UI version; as denoted in the footer)
3. "current" version (via symlink/redirect on docs.influxdata.com)

![image](https://cloud.githubusercontent.com/assets/327411/14428716/8fbd0c1a-fffa-11e5-925b-e7b5d7575d6a.png)

__N.B.__ The Admin UI of InfluxDB 0.11 also linked to 0.10 docs.

**Comment by dmke** [comment]
This seems to be related: influxdata/docs.influxdata.com#340

**Comment by toddboom** [comment]
@dmke Starting with `v0.12.1`, we'll use a `latest` link for the docs so this doesn't happen anymore. PR #6221 is already merged in. Thanks!
