### ISSUE TITLE
How to disable 8088 port usage?

### ISSUE THREAD

**Issue by vitali-ausianik** [influxdata/influxdb#6286]
Hello Guys,

I installed the latest release on my ubuntu machine and see that it listen port 8088. How could i change/disable it? I checked every line in config - it doesn't contain such port in any option.

Thanks!

**Comment by ZhukovAlexey** [comment]
8088 was a default port for cluster wide communication.

http://docs-prod-lb-247556002.us-west-1.elb.amazonaws.com/influxdb/v0.11/clustering/cluster_setup/

influxdb.conf

```
[meta]
  enabled = true
  ...
  bind-address = "<IP>:8088"

```
InfluxDB 0.11 was the last open source version that includes clustering.

In the latest 0.12 release there's no such config section. I think it's kind of a rudiment and you can do nothing about it.

**Comment by vitali-ausianik** [comment]
Unfortunately i can't do nothing because i need thi port for other application :( So how could i remove this rudimental from installed 0.12 version ?

**Comment by joelegasse** [comment]
The config option you are looking for is `bind-address` at the top-level of the config file, it's no longer in the `meta` section. You can run `influxd config` to see the latest default config.

```
$ ./usr/bin/influxd config | head -n 12
reporting-disabled = false
bind-address = ":8088"
hostname = ""
join = ""

[meta]
  dir = "/home/user/.influxdb/meta"
  retention-autocreate = true
  logging-enabled = true
  pprof-enabled = false
  lease-duration = "1m0s"

```

It's not just for clustering, that port is also used when doing `influxd backup`.

**Comment by ZhukovAlexey** [comment]
> The config option you are looking for is bind-address at the top-level of the config file, it's no longer in the meta section. 

Hmmm, in the official 0.12 RMP package influxdb-0.12.1-1.x86_64.rpm there's no such a line as `bind-address = ":8088"` in influxdb.conf

Maybe it still works when adding its manually.
