### ISSUE TITLE
Move query result formatting to handler from CLI

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#6289]
### Feature Request

Move results formatting to handler for queries.

**Current behavior:** They query endpoint currently always returns results formatted as `JSON`.  In the CLI, you can specify if you want the results as JSON, CSV, or COLUMN.

**Desired behavior:** Move all formatting to the handler, and specify a content-type to respond with.  

**Use case:** This will allow other clients to get any format desired from the http query endpoint.

**Comment by at15** [comment]
@corylanou is the issue still help wanted? And if so, do you might provide some detail about where to get started? Thanks.
