### ISSUE TITLE
[0.10.3]some duplicate data even

### ISSUE THREAD

**Issue by litianwang** [influxdata/influxdb#6324]
**_## In sql query results , there are some timestamp duplicate records. Details：_**

`Run  command “> select \* from tabreader where bid = '10086' and time > now() - 24h”  on 
InfluxDB shell 0.10.3  to  get results of the last 24 hours.

> select \* from tabreader where bid = '10086' and time > now() - 24h
> ## name: tabreader
> 
> time                    bid             value
> 1460433600000000000     10086       7.2391701e+07
> 1460437200000000000     10086       7.4797216e+07
> 1460440800000000000     10086       7.050559e+07
> 1460444400000000000     10086       7.3961841e+07
> **1460448000000000000     10086       8.18958e+07
> 1460448000000000000     10086       8.18958e+07**
> 1460451600000000000     10086       9.0897983e+07
> 1460451600000000000     10086       9.0897983e+07
> _**1460455200000000000     10086       9.664689e+07
> 1460455200000000000     10086       9.664689e+07**_
> 1460458800000000000     10086       1.07460176e+08
> 1460458800000000000     10086       1.07460176e+08
> 1460462400000000000     10086       1.19158217e+08
> 1460462400000000000     10086       1.19158217e+08
> 1460466000000000000     10086       1.20449333e+08
> 1460466000000000000     10086       1.20449333e+08
> 1460469600000000000     10086       1.05734497e+08
> 1460469600000000000     10086       1.05734497e+08
> 1460473200000000000     10086       7.596843e+07
> 1460473200000000000     10086       7.596843e+07
> 1460476800000000000     10086       5.0364538e+07
> 1460476800000000000     10086       5.0364538e+07
> **1460480400000000000     10086       3.3678488e+07
> 1460480400000000000     10086       3.3678488e+07**
> 1460484000000000000     10086       2.6219215e+07
> 1460487600000000000     10086       2.1534919e+07
> 1460491200000000000     10086       1.8004023e+07
> 1460494800000000000     10086       1.5850347e+07
> 1460498400000000000     10086       1.5455737e+07
> 1460502000000000000     10086       1.6122369e+07
> 1460505600000000000     10086       2.3524346e+07
> 1460509200000000000     10086       3.2968709e+07

In the above results，part of the error rows are bold. eg:
"1460480400000000000"  is the duplicate  timestamp records.

 But,when run  command to get results of the last 12 hours，there is no duplicate data which should appear.

> select \* from tabreader where bid = '10086' and time > now() - 12h
> ## name: tabreader
> 
> time                    bid             value
> 1460476800000000000     10086       5.0364538e+07
> **1460480400000000000     10086       3.3678488e+07**
> 1460484000000000000     10086       2.6219215e+07
> 1460487600000000000     10086       2.1534919e+07
> 1460491200000000000     10086       1.8004023e+07
> 1460494800000000000     10086       1.5850347e+07
> 1460498400000000000     10086       1.5455737e+07
> 1460502000000000000     10086       1.6122369e+07
> 1460505600000000000     10086       2.3524346e+07
> 1460509200000000000     10086       3.2968709e+07`

**Comment by e-dard** [comment]
Hi @litianwang, can you reproduce this on the most recent version of Influx (`0.12.1`)?

**Comment by mark-rushakoff** [comment]
Please open a new issue if you're seeing this in 1.1 or newer.
