### ISSUE TITLE
[Feature Request] Modify/delete series tags

### ISSUE THREAD

**Issue by sbengo** [influxdata/influxdb#6385]
Hi,

I have to modify a tag of several series, becouse group of severs changed their cluster names. 

I thought it could be done selecting all series and backfilling overriding the tag, but as I have seen, there is no way to do it.

There is way to modify an existing tag associated with a serie/measurement?

Thanks!

**Comment by e-dard** [comment]
@sbengo does every series have the same tag value that needs to be changed? If so you could use `DELETE SERIES` (see [here](https://docs.influxdata.com/influxdb/v0.9/query_language/database_management/#delete-series-with-drop-series)) to remove all those series and then reinsert them with new values. However, this would need an external program to manage the manipulation of the tags. As you note, Influx doesn't have support for modifying tags yet.

**Comment by sbengo** [comment]
Hi @e-dard, thanks for answer.
So, if it is not implemented, can I change the title as a feature request?

Thanks

**Comment by e-dard** [comment]
@sbengo Sure.

**Comment by sbengo** [comment]
Hi, following with this thread, would be awesome to implement the posibility to add a tag on the SELECT AS clause, for example with a WITH clause. It may allow the user modify tag values on already existing tag field keys and in case that it doesn't exsit, create new ones.

As an example:
`SELECT value AS value WITH existingtagkey='newtagvalue', newtagkey='newtagvalue2' INTO ... FROM ...`
