### ISSUE TITLE
Continuous queries not running

### ISSUE THREAD

**Issue by davidh-ssec** [influxdata/influxdb#6395]
I mentioned this bug on the mailing list (https://groups.google.com/forum/#!topic/influxdb/7M3XtZB5CqU) and was told to open a bug report. I'll include the information from that post here.

I'm running InfluxDB 0.12.1 on a vagrant Ubuntu VM with a macbook as the host machine. I'm putting meteorological data in to the database and am having trouble getting any CQs to work even with what I see as the simplest case. I'm sending queries/writes to the database via curl and python via requests. I create the database with these queries:

    CREATE DATABASE metobs
    CREATE RETENTION POLICY one_hour ON {dbname} DURATION 3h REPLICATION 1 DEFAULT
    CREATE RETENTION POLICY one_year ON {dbname} DURATION 365d REPLICATION 1
    CREATE CONTINUOUS QUERY one_minute_cq ON {dbname} RESAMPLE EVERY 1s BEGIN SELECT mean(value) INTO pressure_1m FROM pressure GROUP BY time(1m) END

I then write some data by POSTing to /write that make the measurements look like this:

    air_temp,inst=tower,site=aoss       value=<float>
    pressure,inst=tower,site=aoss       value=<float>

If I'm writing a single line the POST looks like this via requests:

    resp = requests.post(
            'http://{host}:{port:d}/write?db={dbname}'.format(host=host, port=port, dbname=dbname),
            data=line
    )

Here's some examples of the lines being written:

    air_temp,inst=tower,site=aoss value=4.0529 1459470965000000000
    dewpoint,inst=tower,site=aoss value=2.8613 1459470965000000000
    rh,inst=tower,site=aoss value=91.699 1459470965000000000
    air_temp_6_3m,inst=tower,site=aoss value=3.999 1459470965000000000
    air_temp_4,inst=tower,site=aoss value=5.6534 1459470965000000000
    air_temp_2,inst=tower,site=aoss value=4.8075 1459470965000000000
    precip,inst=tower,site=aoss value=0.0 1459470965000000000
    box_air_temp,inst=tower,site=aoss value=4.9099 1459470965000000000
    accum_precip,inst=tower,site=aoss value=0.0 1459470965000000000
    paro_air_temp_period,inst=tower,site=aoss value=5.8614 1459470965000000000
    box_pressure,inst=tower,site=aoss value=959.26 1459470965000000000
    pressure,inst=tower,site=aoss value=960.5 1459470965000000000

So once I've written 435 points or so to each series I don't see the CQ's "pressure_1m" series in the "show series" output. I'm able to run the CQs select statement without the INTO clause after adding a "WHERE" time clause and get expected results. I can also run the select statement with the INTO clause and get expected results in the "pressure_1m" series.

Can anyone see something obvious that I'm doing wrong? If you need me to provide a copy of the database or output from some commands I can do that. Thanks.

**Comment by davidh-ssec** [comment]
Here is the output from the select statement. I'm not sure why it continues with the rest of the empty records (I'm guessing that's expected):

> vagrant@precise64:~$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.12.1
InfluxDB shell 0.12.1
> select mean(value) from metobs.one_hour.pressure where time > '2016-04-01' group by time(1m)
name: pressure
--------------
time			mean
1459468800000000000	959.929090909091
1459468860000000000	959.8558333333332
1459468920000000000	959.9291666666667
1459468980000000000	959.975
1459469040000000000	959.9916666666667
1459469100000000000	959.995
1459469160000000000	960.0233333333332
1459469220000000000	960.0225
1459469280000000000	959.9783333333331
1459469340000000000	959.9499999999999
1459469400000000000	960.0191666666666
1459469460000000000	960.0291666666666
1459469520000000000	959.9758333333333
1459469580000000000	959.9891666666666
1459469640000000000	960.0058333333333
1459469700000000000	960.0641666666667
1459469760000000000	960.0808333333333
1459469820000000000	959.9383333333332
1459469880000000000	960.1308333333333
1459469940000000000	960.1300000000001
1459470000000000000	960.1791666666664
1459470060000000000	960.0900000000001
1459470120000000000	960.105
1459470180000000000	960.1958333333336
1459470240000000000	960.1616666666665
1459470300000000000	960.2166666666666
1459470360000000000	960.2375000000002
1459470420000000000	960.2516666666667
1459470480000000000	960.2816666666668
1459470540000000000	960.3591666666666
1459470600000000000	960.3883333333334
1459470660000000000	960.3791666666665
1459470720000000000	960.4625000000002
1459470780000000000	960.4649999999998
1459470840000000000	960.5083333333332
1459470900000000000	960.5208333333334
1459470960000000000	960.5433333333334
1459471020000000000	
1459471080000000000	
1459471140000000000	
1459471200000000000	
1459471260000000000	
1459471320000000000	
1459471380000000000	
...

**Comment by davidh-ssec** [comment]
Ok last piece of information that I could think of, I ran `tail -f`on the log and I can see that the CQ is running, it's just not creating anything.

    [continuous_querier] 2016/04/15 20:38:00 executing continuous query one_minute_cq (2016-04-15 20:37:00 +0000 UTC to 2016-04-15 20:38:00 +0000 UTC)
    [query] 2016/04/15 20:38:00 SELECT mean(value) INTO metobs.one_hour.pressure_1m FROM metobs.one_hour.pressure WHERE time >= '2016-04-15T20:37:00Z' AND time < '2016-04-15T20:38:00Z' GROUP BY time(1m)

**Comment by davidh-ssec** [comment]
Last message for the day. I was able to get the CQ to work when adding new data. I removed the RPs just to be sure they weren't affecting anything. So I recreated the database, added the CQ, inserted data for 15 days ago. The CQ never picked up on this data. After reading the documentation I thought CQs were supposed to analyze newly inserted data, but not look at data inserted before they were created. Right?

After I noticed that the CQ didn't catch this data I reinserted the data but with no timestamp with a 1 second delay in between each insert. The CQ picked up on this since it is **continuously** running. Is there a reason the CQ runs even when there is no data being inserted in to the database?

**Comment by paulstuart** [comment]
I believe I've encountered a similar issue and separately filed a bug: https://github.com/influxdata/influxdb/issues/6401

In my case the CQ is running (shows up in log) but the time range spans a single grouping, so it never has a second point to generate a delta, and since there's no value generated it writes nothing to the backing store.

**Comment by davidh-ssec** [comment]
This may not be a bug and may just be a confusion with the documentation. It is clear from the documentation that CQs do not operate on data *inserted* before they existed, but do they also not operate on data *timestamped* before they were created (even if these data were inserted after the CQ was created)?

Does this also mean that if you insert data out of order and earlier than the CQs sampling that it will never affect the CQ (no recalculation)?

**Comment by jsternberg** [comment]
@davidh-ssec yes, that's correct. CQs will only run against the latest time period. We don't currently have a way to know if a CQ needs to rerun against an old shard when a write is performed against that shard. That's part of the reason why the resample options exist so that you can customize when they get run for what your system expects.

A caveat is there's no way to tell CQs to perform a backfill, but it is possible to just run the backfill yourself. You can also just manually use a `SELECT ... INTO ...` to do that. The only thing different between a new backfill command and what is currently done is we would just grab the command ourselves so you didn't have to copy and paste.

**Comment by davidh-ssec** [comment]
@jsternberg Ok I think that makes sense it just wasn't obvious from the documentation that I was reading.
