### ISSUE TITLE
[0.10.3] where time >= NNNNNN and time <= NNNNNNN seems to exclude last data point

### ISSUE THREAD

**Issue by CDespeaux** [influxdata/influxdb#6396]
### Bug report

__System info:  Influx 0.10.3

__Steps to reproduce:

Note the results of this query which produces a count of 5:

> select count(total) from backend_connections where time >= 1460748191000000000 and time <= 1460748241000000000 and host = 'vdpsproxy203-sfo1'
name: backend_connections
-------------------------
time                    count
1460748191000000000     5

Now, check out the results when performing a simple select * (there are 6 rows):
> select * from backend_connections where time >= 1460748191000000000 and time <= 1460748241000000000 and host = 'vdpsproxy203-sfo1'
name: backend_connections
-------------------------
time                    closed  dropped host                    reset   site    total
1460748191000000000     2981784 94797   vdpsproxy203-sfo1       400     sfo1    2981784
1460748201000000000     2981807 94797   vdpsproxy203-sfo1       400     sfo1    2981807
1460748211000000000     2981836 94797   vdpsproxy203-sfo1       400     sfo1    2981838
1460748221000000000     2981862 94797   vdpsproxy203-sfo1       400     sfo1    2981863
1460748231000000000     2981891 94797   vdpsproxy203-sfo1       400     sfo1    2981891
1460748241000000000     2981912 94797   vdpsproxy203-sfo1       400     sfo1    2981912

Same problem occurs with sum(total):

> select sum(total) from backend_connections where time >= 1460748191000000000 and time <= 1460748241000000000 and host = 'vdpsproxy203-sfo1'
name: backend_connections
-------------------------
time                    sum
1460748191000000000     14909183

The sum is missing the last data point with the time value that is equal to the "time <=" value in the where clause:

bc 1.06.95
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006 Free Software Foundation, Inc.
This is free software with ABSOLUTELY NO WARRANTY.
For details type `warranty'. 
2981784+2981807+2981838+2981863+2981891
14909183

**Comment by jsternberg** [comment]
Can you try this with 0.12? These numbers were interpreted as a floating point number in everything lower than 0.11 which would result in a small amount of inaccuracy. This could lead to either the first or last point being excluded since they weren't in the time range. In 0.12, the parser was improved to read these numbers as integers instead of floating point numbers so it should be accurate.

**Comment by jsternberg** [comment]
For reference, this sounds similar to #5629.

**Comment by jsternberg** [comment]
Closing this as a duplicate. Please reopen if my previous messages were wrong in anyway. Thanks!
