### ISSUE TITLE
Unable to drop series

### ISSUE THREAD

**Issue by imrichardcole** [influxdata/influxdb#6402]
### Bug report

__System info:__

OSX - influxDB 0.9.4.1

__Steps to reproduce:__

Setup new database - 

> create database my_database

Send in sample data using - 

> curl -i -XPOST 'http://localhost:8086/write?db=my_database' --data-binary @sample.txt

where sample.txt is:

> census,location=1,scientist=langstroth butterflies=12,honeybees=23
> census,location=1,scientist=perpetua butterflies=1,honeybees=30 10
> census,location=1,scientist=langstroth butterflies=11,honeybees=28 12
> census,location=1,scientist=perpetua butterflies=3,honeybees=28 13
> census,location=2,scientist=langstroth butterflies=2,honeybees=11 15
> census,location=2,scientist=langstroth butterflies=1,honeybees=10 16
> census,location=2,scientist=perpetua butterflies=8,honeybees=23 18
> census,location=2,scientist=perpetua butterflies=7,honeybees=22 2000

Switch to database using - 

> use my_database

Check data present and as expected - 

> show series
> name: census
> ------------
> _key					location	scientist
> census,location=1,scientist=perpetua	1		perpetua
> census,location=1,scientist=langstroth	1		langstroth
> census,location=2,scientist=langstroth	2		langstroth
> census,location=2,scientist=perpetua	2		perpetua

Attempt to remove data with following - 

> drop series from census where location='2'

__Expected behavior:__ I'd expect the data for location 2 to be removed.

__Actual behavior:__ I get the following error - 

> ERR: open /Users/dev/.influxdb/wal/my_database/default/33/01.000001.wal: no such file or directory

**Comment by e-dard** [comment]
@imrichardcole is this on a fresh install? Can you upgrade to a more recent version? The currently supported version is `0.12.1`, but please check the upgrade instructions for `0.10` and `0.11`.

**Comment by imrichardcole** [comment]
Yes fresh install.  We're stuck on this version for a while because of running it on Windows.  Is this a known issue that's fixed in latter versions then?

**Comment by jwilder** [comment]
This should be working in newer versions.  Closing this as `0.9.4.1` is no longer maintained.
