### ISSUE TITLE
[feature request] Grant RP and CQ CRUD for non-admins per DB

### ISSUE THREAD

**Issue by melor** [influxdata/influxdb#6404]
**Proposal:** Implement GRANT support for retention policies and continuous queries. 

**Current behavior:** Per-database semi-"admin" users are not possible. You either have full admins rights over all databases or you won't be able to modify retention policies and continuous queries. A user resposible for managing the contents of a specific DB is required to contact the admin user every time a RP or a CQ needs to be modified.

**Desired behavior:** Extension to the READ/WRITE/ALL permission system to allow adding retention policy and continuous query modification on a per-user, per-database basis.

**Use case:** Makes it possible to create users who have full control over a specific database. A single InfluxDB instance can contain multiple databases, each "owned" by a specific non-admin user, who is able to fully manage the contents of the database. A normal "admin" user is still responsible of creating these databases and granting access.

**Comment by mschoenlaub** [comment]
Hm. I see two implementation strategies here:

1. Introduce concept of database owners. These could grant READ/WRITE privileges on their database and execute all of the administrative commands on their database (including RP/CQ CRUD)

2. Introduce new privileges for RP/CQ modification.

I suspect the latter one being more cumbersome to implement, plus thre's a chance we could one day end up with quite a few privileges.

I'd like to contribute this feature but would like to gather some opinions on this first.
