### ISSUE TITLE
Some big integers values are displayed in the Admin UI incorrectly

### ISSUE THREAD

**Issue by pga23** [influxdata/influxdb#6405]
### Bug report

**System info**: InfluxDB 0.12.1, Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)

**Steps to reproduce:**

Just insert the following data:

```
example v1=1458207348766210300i,v2=58207348766210300i,v3=8207348766210300i 1458207348766210300
example v1=1458207348766210301i,v2=58207348766210301i,v3=8207348766210301i 1458207348766210301
example v1=1458207348766210302i,v2=58207348766210302i,v3=8207348766210302i 1458207348766210302
example v1=1458207348766210303i,v2=58207348766210303i,v3=8207348766210303i 1458207348766210303
```

**Expected behavior:**

SELECT \* FROM example:

```
time                            v1                  v2                  v3
2016-03-17T09:35:48.7662103Z    1458207348766210300 58207348766210300   8207348766210300
2016-03-17T09:35:48.766210301Z  1458207348766210301 58207348766210301   8207348766210301
2016-03-17T09:35:48.766210302Z  1458207348766210302 58207348766210302   8207348766210302
2016-03-17T09:35:48.766210303Z  1458207348766210303 58207348766210303   8207348766210303
```

**Actual behavior:**

SELECT \* FROM example:

```
time                            v1                  v2                  v3
2016-03-17T09:35:48.7662103Z    1458207348766210300 58207348766210300   8207348766210300
2016-03-17T09:35:48.766210301Z  1458207348766210300 58207348766210300   8207348766210301
2016-03-17T09:35:48.766210302Z  1458207348766210300 58207348766210300   8207348766210302
2016-03-17T09:35:48.766210303Z  1458207348766210300 58207348766210300   8207348766210303
```

**Additional info:**

Default configuration of both InfluxDB and Ubuntu server.

**Comment by pga23** [comment]
Results displayed by Admin UI v0.12.1

**Comment by jsternberg** [comment]
This might be an issue with the Admin UI doing some weird processing of the input. When I use that `SELECT` on the command line, I get back the correct values. When I try it using the Admin UI, I get this in the network traffic:

```
{
    "results": [
        {
            "series": [
                {
                    "name": "example",
                    "columns": ["time", "v1", "v2", "v3"],
                    "values":[
                        [
                            "2016-03-17T09:35:48.7662103Z",
                            1458207348766210300,
                            58207348766210300,
                            8207348766210300
                        ],
                        [
                            "2016-03-17T09:35:48.766210301Z",
                            1458207348766210301,
                            58207348766210301,
                            8207348766210301
                        ],
                        [
                            "2016-03-17T09:35:48.766210302Z",
                            1458207348766210302,
                            58207348766210302,
                            8207348766210302
                        ],
                        [
                            "2016-03-17T09:35:48.766210303Z",
                            1458207348766210303,
                            58207348766210303,
                            8207348766210303
                        ]
                    ]
                }
            ]
        }
    ]
}
```

So this isn't an issue with the server as the returned traffic is correct.

**Comment by jsternberg** [comment]
It looks like this is an issue with using JSON. JSON doesn't really differentiate between floats and integers and treats them both as numbers. The largest integer that can safely be represented is 2^53.

http://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin

@pauldix should we consider adding other formats such as XML for #6289? JSON doesn't seem to be very good at keeping track of types and retaining formatting.

**Comment by e-dard** [comment]
@jsternberg @pauldix this isn't JSON's fault. Since JSON is language-independent, it's up to the language encoding/decoding to make a best-effort with the JSON number type. The RFC for JSON merely states that the number type can use certain notation, e.g., `E` format and can't be `NaN`, but it doesn't say anything about restrictions on the size of the number—you can have arbitrarily large numbers in JSON AFAIK.

The issue here is that unlike a whole bunch of other languages, Javascript doesn't have native support for 64bit integers. A workaround for the JS-based admin UI might be to manually generate the requisite write queries without converting values to JS floating-point numbers.

Similar to #6370.

**Comment by toddboom** [comment]
Possibly fixable by using something like big.js: https://github.com/MikeMcl/big.js
