### ISSUE TITLE
String and Boolean values are returned as NULL if queried together with series of other types

### ISSUE THREAD

**Issue by altery** [influxdata/influxdb#6420]
We upgraded from InfluxDB 0.10.3 to 0.12.1 and experience the following issue:

When reading series of type Boolean or String, all values are returned as NULL if the series is queried together with other series that contain a series/field of the same name but with a different type.

You may reproduce this in the Admin UI:

### Test data (Line Protocol)
```
dp1000 value=42i 1459081130000000000
dp1001 value=3.14 1459081130000000000
dp1002 value="Three Headed Monkey" 1459081130000000000
dp1003 value="Cake" 1459081130000000000
dp1004 value=true 1459081130000000000
dp1005 value=false 1459081130000000000
dp1006 otherDimension=false 1459081130000000000
```

### Queries working properly
`select value from dp1002`
`select value from dp1002,dp1003`
`select value from dp1004,dp1005`
`select value form dp1006,dp1001`

### Queries returning unexpected NULL values
`select value from dp1002,dp1001`
-> `value` of dp1002 is `null` instead of `"Three Headed Monkey"`

`select value from dp1004,dp1001`
-> `value` of dp1004 is `null` instead of `true`

`select value from /.*/`
-> `value` of dp1002,dp1003,dp1004,dp1005 are all `null`

**Comment by jwilder** [comment]
@jsternberg @benbjohnson

**Comment by ianlutzeigen** [comment]
i am getting the same:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/influxdb/h5JKweZCXdM/_RPht5s1BgAJ

**Comment by benbjohnson** [comment]
@altery The new query engine in v0.11 requires that each field is a single data type for performance reasons. Unfortunately we're not able to support multi-typed data for a single field anymore. I added an update to the documentation to clarify:

https://github.com/influxdata/docs.influxdata.com/pull/394

**Comment by altery** [comment]
Thank you for clarifying!
