### ISSUE TITLE
Log slow queries

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#6429]
### Feature Request

The database should be able to log queries that exceed a threshold to assist operators with identifying potential problematic queries.  This setting should log the slow queries even if query logging is disabled.

We currently have a `query-timeout` setting that will kill a long running query.  We also have `show queries` that will report the duration of the query.  These are similar ideas, but solve slightly different use cases.  The `query-timeout` is intended to automatically kill queries to prevent them from consuming too many resources.  The `show queries` statement is useful for interactive monitoring of queries currently running.

The slow query log setting would is useful to identify slow queries retrospectively.

**Comment by jsternberg** [comment]
@jwilder when should the message be printed?

1) After the query completes.
2) While the query is executing.

The first is easier and doesn't require an extra goroutine running, but you may want it to be printed while the query is actively running.

**Comment by jwilder** [comment]
@jsternberg While running.

**Comment by e-dard** [comment]
@jsternberg @jwilder yeah I agree. I think it's more important that you know some query was slower than `x` rather than exactly how much slower than `x` it was.

**Comment by S31121992** [comment]
I have added Custom Headers(X-Request-Id) to keep track of logs for each API request.
Problem is for slow queries (when I enable Log-Queries-After) I do not get this Request Id displayed.
Is there a way how can we make it work, if not request ID then something else to keep track of logs associated with API ?
