### ISSUE TITLE
[0.12] TSM/WAL flush inconsistencies

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#6434]
It seems that cache-snapshot-memory-size is not closely respected.
Tests run with v0.12 and v0.12.1.

-Configuration:
cache-snapshot-memory-size = 21404
cache-snapshot-write-cold-duration = "4m"

-Shard duration:
Retention policy with shard duration set to 2 minutes.

-Schema:
Writing points in a single series with incrementing timestamps.

Sample shard status in WAL:
...

48K    43
72K    44
28K    45

Shard 45 (latest) is repeatedly flushed when it exceeds ~70KB in size while previous shards 43 and 44 are not flushed from the WAL until they reach the cold-duration timer (4 minutes). This repeats consistently when shard 46 is created with some data left unflushed in shard 45 and so on.

Testing again with cache-snapshot-memory-size = 42000 , the latest shard is flushed at 160KB.

Although earlier shards in the WAL exceed the configured cache-snapshot-memory-size only the latest shard's WAL is flushed, and only when reaching a size close to 4 times the configured value.

**Comment by jwilder** [comment]
@kostasb If a shard does not have writes coming in, then it won't push passed the snapshot memory size and won't be flushed until after the cold duration.  

For the sizes, are you using the size of the wal files on disk as a reference?  The size in memory is very different from how the wal segments are stored and are not comparable to the memory settings.

**Comment by kostasb** [comment]
Thanks for the prompt response Jason.

Since the WAL segment size on disk is not the same with in-memory size, and since the configuration file values refer to memory size, then the above observation is invalid.
