### ISSUE TITLE
point updates don't work on 0.12,0 and 0.12.1 - after few hours

### ISSUE THREAD

**Issue by sonneym** [influxdata/influxdb#6439]
update point doesn't work after a few hours  on 0.12.1 stable

example:

(create database:)
```
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb" 
```
(add point:)

```
curl -i -XPOST 'http://localhost:8086/write?db=mydb' -d 'cpu,host=server01 value=0.64'
```

(update it and check. Note: you will have to change the value of timeuid 1461207718937586169 to the one that's correct for you)
```
curl -X POST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu,host=server01 value=0.67 1461207718937586169'

curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=mydb" --data-urlencode "q=select * from cpu" 
```
result is good:
```
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu",
                    "columns": [
                        "time",
                        "host",
                        "value"
                    ],
                    "values": [
                        [
                            "2016-04-21T03:01:58.937586169Z",
                            "server01",
                            0.67
                        ]
                    ]
                }
            ]
        }
    ]

```

(leave if for about 5-8 hrs, then try to update again)
```

curl -X POST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu,host=server01 value=0.70 1461207718937586169'

curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=mydb" --data-urlencode "q=select * from cpu" 
```
result is bad with old value:
```
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu",
                    "columns": [
                        "time",
                        "host",
                        "value"
                    ],
                    "values": [
                        [
                            "2016-04-21T03:01:58.937586169Z",
                            "server01",
                            0.67
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by e-dard** [comment]
@sonneym thanks for the report. Do you have the `influxd` logs for the period?

**Comment by sonneym** [comment]
@e-dard Thanks for checking into this Ed.
I tried it again for you with logs:

```
$curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE chck" 
[query] 2016/04/22 09:38:57 CREATE DATABASE chck
[http] 2016/04/22 09:38:57 ::1 - - [22/Apr/2016:09:38:57 -0700] GET /query?q=CREATE%20DATABASE%20chck HTTP/1.1 200 16 - curl/7.43.0 b5b343b3-08a8-11e6-8001-000000000000 819.915µs

```

```
$ curl -i -XPOST 'http://localhost:8086/write?db=chck' -d 'cpu,host=server01 value=0.64'
[tsm1wal] 2016/04/22 09:39:37 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/04/22 09:39:37 tsm1 WAL writing to /var/opt/influxdb/wal/chck/default/90
[tsm1] 2016/04/22 09:39:37 /usr/local/var/influxdb/data/chck/default/90 database index loaded in 688ns
[http] 2016/04/22 09:39:37 ::1 - - [22/Apr/2016:09:39:37 -0700] POST /write?db=chck HTTP/1.1 204 0 - curl/7.43.0 cdaaa4a3-08a8-11e6-8002-000000000000 4.507227ms

```

```
$ curl -X POST 'http://localhost:8086/write?db=chck' --data-binary 'cpu,host=server01 value=0.68 1461343177941989902'
[http] 2016/04/22 09:43:49 ::1 - - [22/Apr/2016:09:43:49 -0700] POST /write?db=chck HTTP/1.1 204 0 - curl/7.43.0 63bb8b36-08a9-11e6-8009-000000000000 1.003368ms

```
I tried few updates that worked and then after 
...
[retention] 2016/04/22 09:48:20 retention policy shard deletion check commencing
...
```
[retention] 2016/04/22 15:48:20 retention policy shard deletion check commencing
[retention] 2016/04/22 15:58:20 retention policy shard deletion check commencing
[retention] 2016/04/22 16:09:02 retention policy shard deletion check commencing
[retention] 2016/04/22 16:18:20 retention policy shard deletion check commencing
[retention] 2016/04/22 16:28:20 retention policy shard deletion check commencing
[retention] 2016/04/22 16:38:20 retention policy shard deletion check commencing
[metaclient] 2016/04/22 16:39:02 new shard group 91 successfully precreated for database _internal, retention policy monitor
[retention] 2016/04/22 16:48:20 retention policy shard deletion check commencing
[retention] 2016/04/22 16:58:20 retention policy shard deletion check commencing
```
```

$curl -X POST 'http://localhost:8086/write?db=chck' --data-binary 'cpu,host=server01 value=0.88 1461343177941989902'
[http] 2016/04/22 16:58:43 ::1 - - [22/Apr/2016:16:58:43 -0700] POST /write?db=chck HTTP/1.1 204 0 - curl/7.43.0 251597f3-08e6-11e6-805b-000000000000 522.038µs
```
Didn't update to value 0.88

This POST call was after 
"[metaclient] 2016/04/22 16:39:02 new shard group 91 successfully precreated for database _internal, retention policy monitor"
Maybe  after precreation of database _internal, retention policy monitor something gets messed up?

**Comment by e-dard** [comment]
Could you provide the full logs as an attached file? Would be good to just
double check everything that happened before 9:48

On Saturday, 23 April 2016, sonneym <notifications@github.com> wrote:

> @e-dard <https://github.com/e-dard> Thanks for checking into this Ed.
> I tried it again for you with logs:
>
> $curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE chck"
> [query] 2016/04/22 09:38:57 CREATE DATABASE chck
> [http] 2016/04/22 09:38:57 ::1 - - [22/Apr/2016:09:38:57 -0700] GET /query?q=CREATE%20DATABASE%20chck HTTP/1.1 200 16 - curl/7.43.0 b5b343b3-08a8-11e6-8001-000000000000 819.915µs
>
>
> $ curl -i -XPOST 'http://localhost:8086/write?db=chck' -d 'cpu,host=server01 value=0.64'
> [tsm1wal] 2016/04/22 09:39:37 tsm1 WAL starting with 10485760 segment size
> [tsm1wal] 2016/04/22 09:39:37 tsm1 WAL writing to /var/opt/influxdb/wal/chck/default/90
> [tsm1] 2016/04/22 09:39:37 /usr/local/var/influxdb/data/chck/default/90 database index loaded in 688ns
> [http] 2016/04/22 09:39:37 ::1 - - [22/Apr/2016:09:39:37 -0700] POST /write?db=chck HTTP/1.1 204 0 - curl/7.43.0 cdaaa4a3-08a8-11e6-8002-000000000000 4.507227ms
>
>
> $ curl -X POST 'http://localhost:8086/write?db=chck' --data-binary 'cpu,host=server01 value=0.68 1461343177941989902'
> [http] 2016/04/22 09:43:49 ::1 - - [22/Apr/2016:09:43:49 -0700] POST /write?db=chck HTTP/1.1 204 0 - curl/7.43.0 63bb8b36-08a9-11e6-8009-000000000000 1.003368ms
>
>
> I tried few updates that worked and then after
> ...
> [retention] 2016/04/22 09:48:20 retention policy shard deletion check
> commencing
> ...
>
> [retention] 2016/04/22 15:48:20 retention policy shard deletion check commencing
> [retention] 2016/04/22 15:58:20 retention policy shard deletion check commencing
> [retention] 2016/04/22 16:09:02 retention policy shard deletion check commencing
> [retention] 2016/04/22 16:18:20 retention policy shard deletion check commencing
> [retention] 2016/04/22 16:28:20 retention policy shard deletion check commencing
> [retention] 2016/04/22 16:38:20 retention policy shard deletion check commencing
> [metaclient] 2016/04/22 16:39:02 new shard group 91 successfully precreated for database _internal, retention policy monitor
> [retention] 2016/04/22 16:48:20 retention policy shard deletion check commencing
> [retention] 2016/04/22 16:58:20 retention policy shard deletion check commencing
>
>
> $curl -X POST 'http://localhost:8086/write?db=chck' --data-binary 'cpu,host=server01 value=0.88 1461343177941989902'
> [http] 2016/04/22 16:58:43 ::1 - - [22/Apr/2016:16:58:43 -0700] POST /write?db=chck HTTP/1.1 204 0 - curl/7.43.0 251597f3-08e6-11e6-805b-000000000000 522.038µs
>
> Didn't update to value 0.88
>
> This POST call was after
> "[metaclient] 2016/04/22 16:39:02 new shard group 91 successfully
> precreated for database _internal, retention policy monitor"
> Maybe after precreation of database _internal, retention policy monitor
> something gets messed up?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdata/influxdb/issues/6439#issuecomment-213631011>
>


-- 
*Edd Robinson*
InfluxDB Engineer
▼▴

*InfluxData.com <http://influxdata.com/>*

Github <http://www.github.com/e-dard> / LinkedIn
<https://www.linkedin.com/in/eddrobinson> / Personal <http://eddrobinson.io>

**Comment by sonneym** [comment]
I created a new database and did an update at 13:44 
"curl -X POST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu,host=server01 value=0.68 1461423791277243078'"
it didn't update the value to 0.68, it stayed at 0.67
```
[query] 2016/04/23 08:02:45 CREATE DATABASE mydb
[http] 2016/04/23 08:02:45 ::1 - - [23/Apr/2016:08:02:45 -0700] GET /query?q=create+database+mydb&db=_internal HTTP/1.1 200 40 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 6f65db05-0964-11e6-8010-000000000000 2.449128ms
[query] 2016/04/23 08:02:45 SHOW DATABASES
[http] 2016/04/23 08:02:45 ::1 - - [23/Apr/2016:08:02:45 -0700] GET /query?q=SHOW+DATABASES&db=_internal HTTP/1.1 200 136 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 6f66d2e5-0964-11e6-8011-000000000000 360.576µs
[tsm1wal] 2016/04/23 08:03:11 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/04/23 08:03:11 tsm1 WAL writing to /var/opt/influxdb/wal/mydb/default/93
[tsm1] 2016/04/23 08:03:11 /usr/local/var/influxdb/data/mydb/default/93 database index loaded in 663ns
[http] 2016/04/23 08:03:11 ::1 - - [23/Apr/2016:08:03:11 -0700] POST /write?db=mydb HTTP/1.1 204 0 - curl/7.43.0 7ef56d40-0964-11e6-8012-000000000000 3.922993ms
[query] 2016/04/23 08:03:20 SELECT * FROM mydb."default".mydb
[http] 2016/04/23 08:03:20 ::1 - - [23/Apr/2016:08:03:20 -0700] GET /query?q=select+*+from+mydb&db=mydb HTTP/1.1 200 40 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 8469bada-0964-11e6-8013-000000000000 377.945µs
[query] 2016/04/23 08:03:20 SHOW DATABASES
[http] 2016/04/23 08:03:20 ::1 - - [23/Apr/2016:08:03:20 -0700] GET /query?q=SHOW+DATABASES&db=mydb HTTP/1.1 200 136 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 846a5af1-0964-11e6-8014-000000000000 1.821499ms
[query] 2016/04/23 08:03:26 SELECT * FROM mydb."default".cpu
[http] 2016/04/23 08:03:26 ::1 - - [23/Apr/2016:08:03:26 -0700] GET /query?q=select+*+from+cpu&db=mydb HTTP/1.1 200 137 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 8810a454-0964-11e6-8017-000000000000 593.032µs
[http] 2016/04/23 08:04:43 ::1 - - [23/Apr/2016:08:04:43 -0700] POST /write?db=mydb HTTP/1.1 204 0 - curl/7.43.0 b5ae1b50-0964-11e6-8018-000000000000 1.18882ms
[query] 2016/04/23 08:04:51 SELECT * FROM mydb."default".cpu
[http] 2016/04/23 08:04:51 ::1 - - [23/Apr/2016:08:04:51 -0700] GET /query?q=select+*+from+cpu&db=mydb HTTP/1.1 200 137 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 baa50d11-0964-11e6-8019-000000000000 583.938µs
[retention] 2016/04/23 08:08:42 retention policy shard deletion check commencing
[retention] 2016/04/23 09:26:29 retention policy shard deletion check commencing
[retention] 2016/04/23 12:28:26 retention policy shard deletion check commencing
[tsm1] 2016/04/23 12:28:27 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/04/23 12:28:27 compacting level 1 group (0) /usr/local/var/influxdb/data/_internal/monitor/91/000000004-000000001.tsm (#0)
[tsm1] 2016/04/23 12:28:27 compacting level 1 group (0) /usr/local/var/influxdb/data/_internal/monitor/91/000000005-000000001.tsm (#1)
[tsm1] 2016/04/23 12:28:27 compacted level 1 group (0) into /usr/local/var/influxdb/data/_internal/monitor/91/000000005-000000002.tsm.tmp (#0)
[tsm1] 2016/04/23 12:28:27 compacted level 1 group 0 of 2 files into 1 files in 9.273046ms
[retention] 2016/04/23 13:43:17 retention policy shard deletion check commencing
[tsm1] 2016/04/23 13:43:17 beginning level 2 compaction of group 0, 2 TSM files
[tsm1] 2016/04/23 13:43:17 compacting level 2 group (0) /usr/local/var/influxdb/data/_internal/monitor/91/000000002-000000002.tsm (#0)
[tsm1] 2016/04/23 13:43:17 compacting level 2 group (0) /usr/local/var/influxdb/data/_internal/monitor/91/000000005-000000002.tsm (#1)
[tsm1] 2016/04/23 13:43:17 compacted level 2 group (0) into /usr/local/var/influxdb/data/_internal/monitor/91/000000005-000000003.tsm.tmp (#0)
[tsm1] 2016/04/23 13:43:17 compacted level 2 group 0 of 2 files into 1 files in 121.350862ms
[http] 2016/04/23 13:44:39 ::1 - - [23/Apr/2016:13:44:39 -0700] POST /write?db=mydb HTTP/1.1 204 0 - curl/7.43.0 32f22458-0994-11e6-801a-000000000000 2.308939ms
[query] 2016/04/23 13:44:45 SELECT * FROM mydb."default".cpu
[http] 2016/04/23 13:44:45 ::1 - - [23/Apr/2016:13:44:45 -0700] GET /query?q=select+*+from+cpu&db=mydb HTTP/1.1 200 137 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 36794459-0994-11e6-801b-000000000000 41.739935ms
[query] 2016/04/23 13:44:46 SELECT * FROM mydb."default".cpu
[http] 2016/04/23 13:44:46 ::1 - - [23/Apr/2016:13:44:46 -0700] GET /query?q=select+*+from+cpu&db=mydb HTTP/1.1 200 137 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 36db8b28-0994-11e6-801c-000000000000 2.42379ms

```

**Comment by jwilder** [comment]
I'm not able to reproduce this with current master.  @sonneym are you able to test with a nightly build?

**Comment by sonneym** [comment]
i tried on mac "brew install influxdb --HEAD" but unsuccessfully, due to something being off on my computer's proto golang package version installed (variable GoGoProtoPackageIsVersion1 undefined) :
...
go
install
-ldflags
-X main.version=0.13.0-HEAD -X main.branch=master -X main.commit=594f1a5ead69ceb460ebce9962963992bfe961f1
./...

# github.com/influxdata/influxdb/influxql/internal
influxql/internal/internal.pb.go:35: undefined: proto.GoGoProtoPackageIsVersion1

**Comment by CrAsH1101** [comment]
I have the same issue. Update works only for couple of hours (not sure how much exactly).
There is no error on write point, value is simply not updated in the database (v 0.12.1)
