### ISSUE TITLE
The error in the answer

### ISSUE THREAD

**Issue by jurijshevtsov** [influxdata/influxdb#6440]
### Bug report

System info: 
ubuntu 14.04
Influx v0.11.0

### Steps to reproduce:
insert
>
t1,request=delete times=1 1453240800000000000
t1,request=delete times1=1 1453240800000000001
t1,request=delete times1=1 1453240800000000002

wrong answer
>
select * from t1 where times =0

return

>
time  request	times	times
1453240800000000001	delete	0	1
1453240800000000002	delete	0	1

add
>
t1,request=delete times=1 1453240800000000003

It has true

> select * from t1 where times =0

No records

see if all the values in the table
>
 select * from t1

return
>
time			request	times	times1
1453240800000000000	delete	1	_
1453240800000000001	delete	_	1
1453240800000000002	delete	_	1
1453240800000000003	delete	1	0

Formatting spoils response. _  - empty, no value

**Comment by jsternberg** [comment]
Can you fix the formatting and surround it with code blocks? There are a bunch of tabs that GitHub doesn't render well and I can't understand the output.

**Comment by jurijshevtsov** [comment]
return

![2016-04-21 18-05-55](https://cloud.githubusercontent.com/assets/17141611/14713940/d2ed9e84-07eb-11e6-85c8-b3486c3efc06.png)

**Comment by jsternberg** [comment]
Can you also try this with 0.12.1?

By the way, you can use code blocks with three backticks before and after a code block to do formatting on GitHub. This allows you to just copy and paste the output from a terminal and it will show up correctly in the issues.

**Comment by jsternberg** [comment]
This looks something fixed by #6239. 0.12.1 should have the fix.

The reason why the first gives the wrong answer is because it erroneously returns a zero value instead of nil at those times.

Please reopen if you still see the error after upgrading to 0.12.1.
