### ISSUE TITLE
Feature request: Selectors - service level agreement (SLA) 

### ISSUE THREAD

**Issue by jurijshevtsov** [influxdata/influxdb#6441]
Proposal: Selectors - service level agreement (SLA) 

A service-level agreement (SLA) is a contract between a service provider and its internal or external customers that documents what services the provider will furnish.

Use case:

Application response time

t1,request=delete response_times=100 1453240800000000000
t1,request=delete response_times=90 1453240800000000001
t1,request=delete response_times=250 1453240800000000002

The percentage of time that requests exceeded 100 milliseconds

SELECT SLA(response_times,100) FROM t1 

Returns the percentage of requests satisfying 

> 66%

**Comment by jwilder** [comment]
`SLA` seems very domain specific.  Maybe something like `percentageAbove(response_times, 100)`.

You can fake this query using multiple queries and `into` like:
```
> insert t1,request=delete response_times=100 1453240800000000000
> insert t1,request=delete response_times=90 1453240800000000001
> insert t1,request=delete response_times=250 1453240800000000002
> select count(response_times) as sla into temp from t1 where response_times >= 100; select count(response_times) as total into temp from t1; select sla/total from temp; drop measurement temp;
name: result
------------
time	written
0	1

name: result
------------
time	written
0	1

name: temp
----------
time	sla_total
0	0.6666666666666666
```

A better approach would probably be to use a CQ to roll up the data into the same measurement periodically and query that rolled up data to calculate the percentage.
