### ISSUE TITLE
Can't compile tsm1 package

### ISSUE THREAD

**Issue by philips** [influxdata/influxdb#6445]
### Bug report

__System info:__ go version go1.6 darwin/amd64

__Steps to reproduce:__

1. go get -u github.com/influxdata/influxdb/tsdb/engine/tsm1/

__Actual behavior:__

```
# github.com/influxdata/influxdb/tsdb/engine/tsm1
../../../src/github.com/influxdata/influxdb/tsdb/engine/tsm1/int.go:260: cannot use d.values[:] (type []uint64) as type *[240]uint64 in argument to simple8b.Decode
../../../src/github.com/influxdata/influxdb/tsdb/engine/tsm1/timestamp.go:204: cannot use simple8b.NewDecoder(nil) (type *simple8b.Decoder) as type simple8b.Decoder in field value
```

Encountered while building https://github.com/sourcegraph/appdash

**Comment by jwilder** [comment]
We use [gdm](https://github.com/sparrc/gdm) to manage dependencies. You need to run gdm restore to checkout the right versions of dependencies.

**Comment by slimsag** [comment]
This is documented at https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#installing-gdm

I agree this is not a bug in InfluxDB. Certainly an issue in Appdash, but not InfluxDB. I don't think this issue needs to remain open.

**Comment by jwilder** [comment]
#6452 updated our usage to depend on the latest simple8b version as well.
