### ISSUE TITLE
aggregates (first/last) on string values fail to return data if the time is lower-bounded before "2015-11-02" 

### ISSUE THREAD

**Issue by ianlutzeigen** [influxdata/influxdb#6446]
This one has been a real pain to figure out:

I have some STRING values and some NUMERICAL (double) values in two different measurements `generatedTag11_DISCRETE_EIGEN_STRING` & `generatedTag2_ANALOG_EIGEN_NUMERICAL`

In their series "value" they have points written with exactly the same timestamps, but the values are strings in one case and doubles in the other. There is exactly the same number of points, the data is of the same duration.

The data is from "2016-01-01" to "2016-01-03" 

For the string series I get data if I do this:

```
SELECT first(value) FROM "generatedTag20_DISCRETE_EIGEN_STRING" WHERE time >= '2015-11-02' AND time < '2016-01-04' GROUP BY time(600000ms) fill(none)
```

if i decrement the start by one day i get no data (i.e.)

```
SELECT first(value)  FROM "generatedTag20_DISCRETE_EIGEN_STRING" WHERE time >= '2015-11-01' AND time < '2016-01-04' GROUP BY time(600000ms) fill(none)
```

..NO DATA is returned..no date prior to this works, dates after and including '2015-11-02'  produce values.

Now for numerical data i get this:

```
SELECT first(value)  FROM "generatedTag2_ANALOG_EIGEN_NUMERICAL" WHERE time >= '2015-11-01' AND time < '2016-01-04' GROUP BY time(600000ms) fill(none)
```

```
SELECT first(value)  FROM "generatedTag2_ANALOG_EIGEN_NUMERICAL" WHERE time >= '2015-10-01' AND time < '2016-01-04' GROUP BY time(600000ms) fill(none)
```

etc all the way into the past I get values

numerical tags behave as expected

What this also means is if I have string data before this time, and I want to downsample, I can't :(

This also means that down sampling and store queries won't work for string data that operate on the entire DB; such as:

```
SELECT first(value) AS downsampled_7200000ms INTO testdb_downsampled."default".:MEASUREMENT FROM /.*_EIGEN_STRING/ WHERE time >= 315529200000ms AND time < 1483225200000ms GROUP BY time(7200000ms)
```

where the time range exceeds the entire data on the db in order down sample the whole lot

Thanks!!

<img width="1440" alt="discrete agg bug" src="https://cloud.githubusercontent.com/assets/18043069/14728187/00def51a-0876-11e6-96d4-566e2af452f8.png">

**Comment by jsternberg** [comment]
@ianlutzeigen can you try this query on your measurement with strings?

```
SELECT value FROM "generatedTag20_DISCRETE_EIGEN_STRING" WHERE time < '2015-11-02'
```

I have a feeling that you wrote float data to this measurement. The query engine attempts to determine which type it should use and cast values to that type. Each shard can have its own type data. It's possible you wrote floats to an earlier shard. When you set the time boundary to `2015-11-02` and above, it likely doesn't include the shard with a float for that field. When you do include a date lower than that, it includes the shard (but may not include any actual data if there was none written in that time period) and then it tries to cast all of the types to a float. Since strings can't be cast to a float, they get discarded and it appears like you have no data.

Removing any time boundaries will also allow you to see if you potentially have other data in their you didn't realize you had.

**Comment by ianlutzeigen** [comment]
Hi, I am looking at this again.

There has never been any float data written to this measureme (unless of course I screwed up) its  all done programatically

Since the last post I have changed the schema, and the version .12.2 and its still present (albeit my measurement names have changed)

Now; I have got 2 databases, 1 that has loads different measurements, and one the only has 1 measurement (the measurement in question is one that is exhibiting the problem). The problem is on the database with loads of data, but not on the other, even though the data for the measurement in question is the same.

Now I go and load up the rest of the data into database 2, and the problem exhibits itself.

I have dumped all the writelines of this db to file, so you can replicate it. I am pretty sure you have something that will readthough a file full of writelines and dump into a database for your

This is what I mean:

192-168-1-1:projects ianlutz$ head testdat.writelines
METADATA,tag=egtests-b1 description="egtests-b1",type="",units="" 0
METADATA,tag=egtests-b1 description="egtests-b1",type="_EIGSTR",units="" 0
egtests-b1 status="OK",value_EIGSTR="duck curry muppet curry seven twoweeks happy twoweeks happy seven muppet" 1451606400000
egtests-b1 status="OK",value_EIGSTR="muppet curry duck curry seven sad seven duck seven curry goat" 1451606460000

the entire file is about 253m... 

and queries:

SELECT first(value_EIGSTR),  first(status) FROM "egtestd-a1a"  WHERE time >= '2015-01-01' AND time < '2016-01-04' GROUP BY time(600000ms) fill(none)

(returns nothing, ie, the bug)
 when cleanly we have data
SELECT * FROM "egtestd-a1a" ORDER BY ASC limit 10
(returns data instide the range
egtestd-a1a
time	status	value_EIGSTR
2016-01-01T00:00:00Z	"OK"	"UNKNOWN"
2016-01-01T00:00:10Z	"OK"	"UNKNOWN"
2016-01-01T00:00:20Z	"OK"	"TRANSITION
...
)

now to work out how to get this attachment to you...

**Comment by ianlutzeigen** [comment]
nope 10mb limit, shall I share  on google drive ?
