### ISSUE TITLE
client api close() doesn't work?

### ISSUE THREAD

**Issue by adpoint** [influxdata/influxdb#6447]
hi,
    I have a piece of code,but i found c.Close() doesn't work,I didn't use  in accordance with the correct method? I use netstat -anp|grep 8086, I've found that ESTABLISHED has been increasing all the time.

	//influxdb client
	c, err := client.NewHTTPClient(client.HTTPConfig{
		Addr:     "127.0.0.1:8086",
		Username: "username",
		Password: "password",
	})
	if err != nil {
	        fmt.Println("new influx client err:%s", err.Error())
		return
	}

	// create a new point batch
	bp, err := client.NewBatchPoints(client.BatchPointsConfig{
		Database:  "demo",
		Precision: "s",
	})
	if err != nil {
		fmt.Println("new batch points,err:%s", err.Error())
		return
	}

	for k, v := range data {
		fields := map[string]interface{}{
			"value": v,
		}
		pt, err := client.NewPoint(k, nil, fields, timeStamp)
		if err != nil {
			beego.Error("new point,err:%s", err.Error())
			continue
		}

		bp.AddPoint(pt)
		// Write the batch
		c.Write(bp)
	}
        fmt.Println("close")
        err = c.Close()
        if err != nil {
             fmt.Println("close influx:%s", err.Error())
        }

**Comment by jwilder** [comment]
Should be fixed via #6425
