### ISSUE TITLE
Provide ability to manage tags and fields like RDBMS indexes

### ISSUE THREAD

**Issue by andyfeller** [influxdata/influxdb#6455]
**Proposal:** InfluxDB database administrators need the ability to manage indexes to address database performance issues/needs

**Current behavior:** InfluxDB index performance is highly reliant upon data cardinality, which is managed external to InfluxDB itself.  After data has been written to InfluxDB, InfluxDB administrators have no way of transforming existing fields / tags as done in RDBMs. 

**Desired behavior:** InfluxDB administrators would have database management commands similar to add/drop index capabilities of most RDBMs.

**Use case:** Given the ease of flooding InfluxDB with arbitrary tags that can blow memory and cause outages, there is no way for InfluxDB administrators to identify and address database series & cardinality issues without negatively impacting data collected.

**Comment by AvinKumar** [comment]
Any updates on this.?
