### ISSUE TITLE
No all databases backup flag

### ISSUE THREAD

**Issue by danyli78** [influxdata/influxdb#6456]
Can we add a function to allow us to backup all databases?

**Comment by dstarmanhr** [comment]
+1 :)

**Comment by jonathanstrong** [comment]
+1

**Comment by quinox** [comment]
Version 1.5 [supports this](https://www.influxdata.com/blog/new-features-in-open-source-backup-and-restore/), running `influxd backup -portable /path/to/backup` makes a backup of everything.
