### ISSUE TITLE
Return "404 page not found"

### ISSUE THREAD

**Issue by sbhr** [influxdata/influxdb#6466]
### Bug report

__System info:__ 
InfluxDB 0.12.2
Ubuntu server 14.04 LTS

__Steps to reproduce:__

1. ```curl -X POST 'http://localhost:8086/db?u=root&p=root' -d '{"name": "stats"}'```
2. ```404 page not found```

help me please.

**Comment by e-dard** [comment]
Please look at the [documentation](https://docs.influxdata.com/influxdb/v0.12/guides/writing_data/) for writing points over HTTP. You need to use the `/write` endpoint.

**Comment by toddboom** [comment]
@sbhr It looks like you might be trying to use v0.8.x syntax, which is no longer applicable. The link that @e-dard provided above will get you started on the latest version.

**Comment by sbhr** [comment]
I'm sorry not to read the documentation.
Thank you for your answer.
