### ISSUE TITLE
What's the purpose of resample every x m/h/d in continous query?

### ISSUE THREAD

**Issue by ningxie1991** [influxdata/influxdb#6467]
Hi,

I'm using version: 0.11.

So in my db I have a bunch of raw data and I want to group them by day, so I will have aggregated daily data. So the continuous query looks like this:

CREATE CONTINUOUS QUERY myQuery ON my_raw_data RESAMPLE EVERY 1h BEGIN SELECT.....FROM my_raw_data WHERE time > now() - 24h and ..... GROUP BY time(24h) END

Actually do I need to resample every 1 h for this purpose? What is the resample feature for? So at every 1 hour, is the continuous query executed by scanning the entire raw data or is it executed by scanning the existing daily data already aggregated from the previous run? Will this affect performance if I have huge data? 

Thanks!

**Comment by gunnaraasen** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.

That said, the `RESAMPLE EVERY` option will determine how often a continuous query executes a new query and stores this result. It's most useful when partial results are needed before the full `GROUP BY time()` has elapsed. For example,

```
CREATE CONTINUOUS QUERY myQuery ON my_raw_data RESAMPLE EVERY 1h BEGIN SELECT mean(value) INTO new_data FROM my_raw_data WHERE ..... GROUP BY time(24h) END
```
Will calculate a new mean for the current day every hour. That way you could still display a mean for today's value even though the day is not over.

Continuous queries always calculate from source every time they're run. There is no built-in cacheing. Performance could be a concern depending on the frequency of the CQ and the amount of data being aggregated.

Also note, your example continuous query does not have a valid syntax (no `INTO` clause). Check out the [docs](https://docs.influxdata.com/influxdb/v0.12/query_language/continuous_queries/#the-create-continuous-query-statement) for more info.

**Comment by ningxie1991** [comment]
@gunnaraasen Thanks for the response! Also another question, will I still need a "where time > now() - 24h" clause since I have "GROUP BY time(24h)" already?

**Comment by gunnaraasen** [comment]
The `WHERE` clause is not needed. The continuous query will actually generate it's own `WHERE` clause every time the continuous query runs and generates a new query.
