### ISSUE TITLE
wrong http return code when writing to a not existing database

### ISSUE THREAD

**Issue by p0fi** [influxdata/influxdb#6469]
### Bug report

__System info:__ InfluxDB >= v0.12.0, ubuntu 14.0.4
__Steps to reproduce:__

1. try to write to a database which is not existing

__Expected behavior:__ expecting to get a HTTP error code 404 like described in the docs

```
Writing a point to a database that doesn't exist:
 curl -i -XPOST 'http://localhost:8086/write?db=atlantis' --data-binary 'liters value=10'
returns:

 HTTP/1.1 404 Not Found
[...]
database not found: "atlantis"
```

__Actual behavior:__ getting HTTP error code 500

```
[http] 2016/04/26 14:55:29 127.0.0.1 - - [26/Apr/2016:14:55:29 +0200] POST /write?db=atlantis HTTP/1.1 500 75 - - 278aef33-0bae-11e6-8001-000000000000 379.617µs
```
__Additional info:__ -

*Please note, the quickest way to fix a bug is to open a Pull Request.*

**Comment by PatrickWalker** [comment]
Would you want a 404 when trying to query a db that doesn't exist?

Currently I get a 200 with a response
```
{
  "results": [
    {
      "error": "database not found: mydb2"
    }
  ]
}
```
The documentation to me indicates before the examples it should be a 200 response in both cases. So is this a code change or is this a doc change?

**Comment by PatrickWalker** [comment]
Believe this has been resolved by
https://github.com/influxdata/influxdb/commit/ced79acac5ed533f88decbc14a0f428fc0caf298
The removal of the Err from the interface means the nil check happens and follows through as expected to give a 404. That's the current behaviour on master for me

**Comment by jsternberg** [comment]
This appears to have been fixed. I'm going to close this issue.
