### ISSUE TITLE
Influxdb Choking Config help

### ISSUE THREAD

**Issue by gitvegas** [influxdata/influxdb#6473]
The scenario and the issue is similar to whats shown here
https://github.com/influxdata/influxdb/issues/375
Running on Linux Redhat Processor = 3, CPU Core = 4 and Memory = 16GB, Core(s) per socket = 4

However, im unable to find these config parameters to tweak. Im using the version v0.10.0. Please suggest
flush-after = 10000 # the number of writes after which wal will be flushed, 0 for flushing on every write
bookmark-after = 10000 # the number of writes after which a bookmark will be created
index-after = 10000

**Comment by jwilder** [comment]
Those config options no longer exist in `v0.10.0`.  You can take a look at a `v0.10.0` [sample config](https://github.com/influxdata/influxdb/blob/0.10.0/etc/config.sample.toml) or run `influxd config` to generate one.

**Comment by gitvegas** [comment]
Thanks for your reply, but what are the new options which can used for tuning, please advice.

**Comment by gitvegas** [comment]
Jason,
Thanks for your reply, but what are the new options which can used for tuning, please advice.
Cheerssraj
