### ISSUE TITLE
Can't get rid of a stalled connection or long run query in CLI without `kill -9`

### ISSUE THREAD

**Issue by lilydjwg** [influxdata/influxdb#6474]
InfluxDB shell 0.12.0, on Arch Linux x86_64.

I connect to an InfluxDB server, and
* either run a query that takes too long to finish
* or forget to disconnect it before I put my computer into sleep, or my network connection just goes bad

I have a non-responsible influx shell now, <kbd>Ctrl-C</kbd> or <kbd>Ctrl-\\</kbd> doesn't work. The only way to get out is `kill -9`.

I expect <kbd>Ctrl-C</kbd> to abort the current operation and return me a new prompt. I also expect <kbd>Ctrl-\\</kbd> to forcefully exit the influx shell so I can connect again, without searching for its pid and killing it elsewhere.

**Comment by lilydjwg** [comment]
What's worse, the resulting terminal after `kill -9` an influx shell is abnormal, e.g. when I run sudo and have inputted the password, pressing <kbd>Return</kbd> doesn't work. I have to do a `reset` first.

**Comment by e-dard** [comment]
@lilydjwg unfortunately the cli program has special uses for the various control codes, as documented [here](https://github.com/peterh/liner). However, it currently looks like we're catching `syscall.SIGQUIT` and attempting to gracefully exit. We shouldn't be doing that, and should be exiting hard (and dumping the core in the case of `SIGQUIT`).
