### ISSUE TITLE
Influxdb Choking Configuration help

### ISSUE THREAD

**Issue by gitvegas** [influxdata/influxdb#6475]
Sorry, What is the new way to tweak the performance if the below options are old, please suggest. I'm recreating this because the previous issue was closed and i'm not sure how to do it with new config.

The scenario and the issue is similar to whats shown here
#375
Running on Linux Redhat Processor = 3, CPU Core = 4 and Memory = 16GB, Core(s) per socket = 4

However, im unable to find these config parameters to tweak. Im using the version v0.10.0. Please suggest
flush-after = 10000 # the number of writes after which wal will be flushed, 0 for flushing on every write
bookmark-after = 10000 # the number of writes after which a bookmark will be created
index-after = 10000

**Comment by jwilder** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
