### ISSUE TITLE
how write just on sql to show many android version lines?

### ISSUE THREAD

**Issue by ring0li** [influxdata/influxdb#6479]
i use grafana show graph.

```sql
SELECT mean("iPhone OS 9.2.1") FROM "os" WHERE $timeFilter GROUP BY time(1d) fill(null)
SELECT mean("iPhone OS 9.3.1") FROM "os" WHERE $timeFilter GROUP BY time(1d) fill(null)
SELECT mean("iPhone OS 9.2") FROM "os" WHERE $timeFilter GROUP BY time(1d) fill(null)
........
```

just like in mysql ,group by iPhone version ~

how just write one sql?

**Comment by jwilder** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
