### ISSUE TITLE
New version influxdb get  higher CPU  load when searching the larger data

### ISSUE THREAD

**Issue by kengan** [influxdata/influxdb#6482]
I have update to the 0.12.2 version. When I search more than 7,000,000 records, the usage of CPU is higher,  the %Cpu(s) is more than 100%. Can you tell me how to solve this problem.The details about my server and thie records is as following:

My server is a Linux server with  8 nuclear  Intel(R) Xeon(R) CPU E5-2620 V3  (2.40GHZ) and 8G memory.

My records is about the price of  foreign currency  . About   the searching , please see the following text:

```
select * from tick_AUDCAD_ASK  where time>'2013-01-01' and time <'2013-01-31' limit 10
name: tick_AUDCAD_ASK
---------------------
  time                                       p             t
1357059614000000000     1.03295    tick
1357059616000000000     1.0329      tick
1357059620000000000     1.0329      tick
1357059621000000000     1.03285    tick
1357059624000000000     1.03295    tick
1357059625000000000     1.03285    tick
1357059634000000000     1.03295    tick
1357059635000000000     1.0329      tick
1357059674000000000     1.0329      tick
1357059691000000000     1.03279    tick
```

When I search the records in a year , more than 7,000,000 records,  the CPU full load.

Please tell me how to solve this problem .Thank you.

**Comment by jwilder** [comment]
Can you run `show shards`, `show stats` as well as describe the shapes of this data?  How many series?  Do you have writes occuring while your query is running?

`select * ...` may be causing you problems.  How does this perform:

```
select p from tick_AUDCAD_ASK where time>'2013-01-01' and time <'2013-01-31' limit 10
```

**Comment by kengan** [comment]
My db named  tickdb
I run show stats. There are many results return.Please the following:



name: tsm1_cache
tags: database=tickdb, path=/var/lib/influxdb/data/tickdb/default/689, retentionPolicy=default
WALCompactionTimeMs     cacheAgeMs      cachedBytes     diskBytes       memBytes        snapshotCount
-------------------     ----------      -----------     ---------       --------        -------------
0                       209182851       0               0               0               0


name: tsm1_cache
tags: database=tickdb, path=/var/lib/influxdb/data/tickdb/default/69, retentionPolicy=default
WALCompactionTimeMs     cacheAgeMs      cachedBytes     diskBytes       memBytes        snapshotCount
-------------------     ----------      -----------     ---------       --------        -------------
0                       209182864       0               0               0               0


name: tsm1_cache
tags: database=tickdb, path=/var/lib/influxdb/data/tickdb/default/690, retentionPolicy=default
WALCompactionTimeMs     cacheAgeMs      cachedBytes     diskBytes       memBytes        snapshotCount
-------------------     ----------      -----------     ---------       --------        -------------
0                       209182157       0               0               0               0


name: tsm1_cache
tags: database=tickdb, path=/var/lib/influxdb/data/tickdb/default/691, retentionPolicy=default
WALCompactionTimeMs     cacheAgeMs      cachedBytes     diskBytes       memBytes        snapshotCount
-------------------     ----------      -----------     ---------       --------        -------------
0                       209182376       0               0               0               0


Because the return result is too many, I only show a part of the result .After above text, the show stats return the following text

name: tsm1_wal
tags: database=tickdb, path=/var/lib/influxdb/wal/tickdb/default/83, retentionPolicy=default
currentSegmentDiskBytes oldSegmentsDiskBytes
----------------------- --------------------
0                       0


name: tsm1_wal
tags: database=tickdb, path=/var/lib/influxdb/wal/tickdb/default/84, retentionPolicy=default
currentSegmentDiskBytes oldSegmentsDiskBytes
----------------------- --------------------
0                       0


name: tsm1_wal
tags: database=tickdb, path=/var/lib/influxdb/wal/tickdb/default/85, retentionPolicy=default
currentSegmentDiskBytes oldSegmentsDiskBytes
----------------------- --------------------
0                       0

**Comment by kengan** [comment]
**When I run show shards I get the result as following**

749     tickdb          default                 749             2014-09-22T00:00:00Z    2014-09-29T00:00:00Z    2014-09-29T00:00:00Z    1
750     tickdb          default                 750             2014-09-29T00:00:00Z    2014-10-06T00:00:00Z    2014-10-06T00:00:00Z    1
751     tickdb          default                 751             2014-10-06T00:00:00Z    2014-10-13T00:00:00Z    2014-10-13T00:00:00Z    1
752     tickdb          default                 752             2014-10-13T00:00:00Z    2014-10-20T00:00:00Z    2014-10-20T00:00:00Z    1
753     tickdb          default                 753             2014-10-20T00:00:00Z    2014-10-27T00:00:00Z    2014-10-27T00:00:00Z    1
754     tickdb          default                 754             2014-10-27T00:00:00Z    2014-11-03T00:00:00Z    2014-11-03T00:00:00Z    1
755     tickdb          default                 755             2014-11-03T00:00:00Z    2014-11-10T00:00:00Z    2014-11-10T00:00:00Z    1
756     tickdb          default                 756             2014-11-10T00:00:00Z    2014-11-17T00:00:00Z    2014-11-17T00:00:00Z    1
757     tickdb          default                 757             2014-11-17T00:00:00Z    2014-11-24T00:00:00Z    2014-11-24T00:00:00Z    1
758     tickdb          default                 758             2014-11-24T00:00:00Z    2014-12-01T00:00:00Z    2014-12-01T00:00:00Z    1
759     tickdb          default                 759             2014-12-01T00:00:00Z    2014-12-08T00:00:00Z    2014-12-08T00:00:00Z    1
760     tickdb          default                 760             2014-12-08T00:00:00Z    2014-12-15T00:00:00Z    2014-12-15T00:00:00Z    1
761     tickdb          default                 761             2014-12-15T00:00:00Z    2014-12-22T00:00:00Z    2014-12-22T00:00:00Z    1
762     tickdb          default                 762             2014-12-22T00:00:00Z    2014-12-29T00:00:00Z    2014-12-29T00:00:00Z    1
763     tickdb          default                 763             2014-12-29T00:00:00Z    2015-01-05T00:00:00Z    2015-01-05T00:00:00Z    1

**Comment by kengan** [comment]
In db I have many  series, just like following

show series
key
tick_AUDCAD_ASK,t=tick
tick_AUDCAD_BID,t=tick

each  series stand for a  foreign currency  and have the price of each date.


All are the detail about our db ,thank you very much .

**Comment by jwilder** [comment]
@kengan It looks like you have sparse data across a large timespace.  I think using a `SHARD DURATION 52w` for your retention policy might help.  You'll need to re-insert the data into the updated retention policy though.

**Comment by kengan** [comment]
@jwilder  Thank you for your answer . Because I am a beginner for influxdb ,can you tell me how to change the retention policy to SHARD DURATION 52w.

Can I use the following command  and what is the meaning  of 52w.

###  ALTER RETENTION POLICY default    ON mydb   DURATION 52w

Thank you very much.

**Comment by jwilder** [comment]
@kengan Use `ALTER RETENTION POLICY default ON mydb SHARD DURATION 52w`. Run this after re-creating the DB.  After you have alter the retention policy, you'll need to re-insert your data into it.

**Comment by kengan** [comment]
@jwilder  Thank you for your answer. I want to know the meaning of SHARD DURATION 52w and why this setting you think maybe help. Thank you very much

**Comment by jwilder** [comment]
@kengan Shard duration will increase the range of time for a given shard.  By default, the max range is 7d.  Since you have very sparse data, you are likely creating lots of little shards with only a few points each per series.  Increasing the shard duration should reduce the number of shards and increase their density.

**Comment by kengan** [comment]
@jwilder  I have change the retention policy to  SHARD DURATION 52w.  the result please see following

> show retention policies on tickdb_52W
name    duration        shardGroupDuration      replicaN        default
default 0               8736h0m0s               1               true


The result of show shards is following

name: tickdb_52W
----------------
id      database        retention_policy        shard_group     start_time              end_time                expiry_time          owners
880     tickdb_52W      default                 880             2006-02-27T00:00:00Z    2007-02-26T00:00:00Z    2007-02-26T00:00:00Z
882     tickdb_52W      default                 882             2014-02-17T00:00:00Z    2015-02-16T00:00:00Z    2015-02-16T00:00:00Z
881     tickdb_52W      default                 881             2015-02-16T00:00:00Z    2016-02-15T00:00:00Z    2016-02-15T00:00:00Z





I re-creatting a db name tickdb_52W ,I re-insert more than 8,000,000  records into a series. When I query these 8,000,000 records, I also get CPU full load
A series save  the price of the foreign currency, each record stand for a price in  5 seconds

Do have any method to solve this problem thank you

**Comment by jwilder** [comment]
@kengan  Is there a specific problem you are seeing with queries?  

The database will use multiple cores if they are available.  Depending on how you are measuring CPU utilization and how many cores you have, the value can be higher than 100%.  High CPU utilization can be expected depending on background tasks running in the DB as well as the shape of your dataset.

**Comment by kengan** [comment]
Thank you jwilder answer, my  CPU on server has 8 core, I use the 'TOP' a  Linux command to see the CPU usage, I don't think the queries have any problem
I use ' select pa,pb  from tick_EURUSD limit 10' and return the  following result. Each record is the price of  EUR to USD in 5 seconds
name: tick_EURUSD
-----------------
time                                       pa         pb
1420117221000000000     1.21007 1.20965
1420117244000000000     1.21014 1.20972
1420117245000000000     1.21014 1.20972
1420117250000000000     1.20993 1.20977
1420117255000000000     1.21012 1.20962
1420117291000000000     1.2101  1.20963
1420117292000000000     1.21005 1.20968
1420117293000000000     1.2101  1.20963
1420117298000000000     1.21012 1.20962
1420117309000000000     1.21014 1.20964

If I remove the 'limit 10' and use 'select pa,pb from tick_EURUSD ',I can see the usage of CPU more than 200% by TOP command.

Can you help me how to solve this problem. If you need to provide any message, please tell as soon as possibly.. Thank you.

**Comment by mark-rushakoff** [comment]
There have been a lot of query engine changes since 0.12. If you're still having trouble with particular queries on the current release, please open a new issue.
