### ISSUE TITLE
InfluxQL for DROP SERIES, SHOW SERIES needs example

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6487]
https://github.com/influxdata/influxdb/blob/master/influxql/README.md#drop-series

https://github.com/influxdata/influxdb/blob/master/influxql/README.md#show-series

**Comment by JarrettR** [comment]
Also needs am entry in the web interface's Query Template dropdown

**Comment by jwilder** [comment]
Fixed via #7234
