### ISSUE TITLE
Query error with tag named "name" after migration

### ISSUE THREAD

**Issue by jeremyVignelles** [influxdata/influxdb#6489]
### Bug report

__System info:__
InfluxDB v0.12.2 , upgraded from 0.9.x (maybe 0.9.6, but not sure) -> 0.10.3 -> 0.12.2 installed with yum and followed the upgrading guideline
CentOS 7

Reproduced in docker environment based on tutum/influxdb Dockerfile edited with version 0.12.2-1 (ubuntu image)

__Steps to reproduce:__

1. Create database
```curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"```

2. Create the data
```curl -X POST http://localhost:8086/write\?db=mydb --data-binary "cpu,name=test value=61"```

3. Launching the query
```curl -G http://localhost:8086/query --data-urlencode 'db=mydb' --data-urlencode "q=SELECT * FROM cpu WHERE name='test'"```

__Expected behavior:__
The line must be returned

__Actual behavior:__ 
```{"error":"error parsing query: found NAME, expected identifier, string, number, bool at line 1, char 25"}```

**Comment by jeremyVignelles** [comment]
Additional info:
I just tried with a fresh influxDB 0.9.6 install and the issue is there too. I think the issue was not present in the legacy engine I was using, but it showed up after the `tsm1` migration

**Comment by jsternberg** [comment]
Yes, `NAME` is a reserved keyword. Sorry for the confusion. I'll submit a PR to update that file.
