### ISSUE TITLE
Fake stats for database which no longer exists

### ISSUE THREAD

**Issue by rubycut** [influxdata/influxdb#6507]
### Bug report

__System info:__ Linux, influxdb 0.12.2

__Steps to reproduce:__

1. run influx_stress
2. execute in cli: drop database stress

__Expected behavior:__  database: _internal, measurement: database, value: numSeries, it should stop emitting stats for "stress" database since it no longer exists

__Actual behavior:__ continues to emit stress database numSeries

__Additional info:__ This behavior can be fixed by restarting influxdb.

**Comment by jwilder** [comment]
#5830 may fix this.

**Comment by jonseymour** [comment]
@jwilder I think #5830 is part of the solution (particularly the idle stats support) although for precision some additional changes to meta and store will be required to give DatabaseIndex a Close() lifecycle method which will allow the statistics Recorder for the database index to be closed when a database is dropped.
