### ISSUE TITLE
Graphite template to handle ip-address and hostname

### ISSUE THREAD

**Issue by ucrkarthik** [influxdata/influxdb#6520]
Are there any plans to improve the graphite template logic? We are sending graphite data that contains IP address and hostname (hr.abc.com, ops.pentagon.dod.gov, etc ), since those values have dot's in them, it makes it difficult to identify tags for those graphite values. One other issue we are having is identifying multiple tags in the middle of the graphite string to create a measurement.

**Comment by gunnaraasen** [comment]
@ucrkarthik It'll be hard to support dots or multiple tags from the same value within the InfluxDB's current Graphite template language. Would being able to apply a regular expression with subexpressions let you do what you want? E.g.

```
templates = ["measurement./(?P<os>[a-zA-Z]+)\.(?P<arch>[a-zA-Z]+)/.field"]

# Applied to the following metric: "cpu.darwin.amd64.usage_idle 59595"
# measurement: cpu
# tags: os=darwin, arch=amd64
# fields: usage_idle=59595
```

Do you use any other Graphite tool(s) that handle those cases elegantly?

**Comment by jwilder** [comment]
@ucrkarthik Can you provide some specific examples of your graphite metrics and what you would like to see as the final measurements, tags, field and value?

**Comment by ucrkarthik** [comment]
Jason, 

Here are some of the graphite metrics we get from hadoop:

graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.AllocatedContainers
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.AllocatedGB
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.AllocatedVCores
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.AvailableGB
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.AvailableVCores
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.BadLocalDirs
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.BadLogDirs
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.ContainerLaunchDurationAvgTime
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.ContainerLaunchDurationNumOps
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.ContainersCompleted
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.ContainersFailed
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.ContainersIniting
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.ContainersKilled
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.ContainersLaunched
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.ContainersRunning
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.GoodLocalDirsDiskUtilizationPerc
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.GoodLogDirsDiskUtilizationPerc

As you can see Hadoop provides key value pairs and a full hostname. It would be ideal if we can strip the "Context=" and "Hostname=" in the template. Also, the hostname is defined as nid00035.cray.com, is there any way we can keep those together in one tag? 

Thanks,
Karthik

**Comment by rfletcher** [comment]
We have a similar need for more flexible Graphite templates. I don't want to hijack the thread and leave @ucrkarthik without an answer, so if I should open a new issue instead please say so.

In our case dots aren't the problem, but we'd like to extract fields/tags from within one part of the Graphite path. As one example, collectd is sending system metrics (via carbon-relay-ng) like this:

````
collectd.cpu-0.percent-idle 60.1372844466767 1444234982
collectd.cpu-0.percent-system 9.48145662023829 1444234982
collectd.cpu-1.percent-idle 57.0254862508384 1444234982
collectd.cpu-1.percent-system 4.49172576832151 1444234982
````

I'd like to translate that into something like this:

````
> select * from "collectd.cpu"
name: collectd.cpu
-----------------------------------
time                core idle             system
1444234982000000000	0    60.1372844466767 9.48145662023829
1444234982000000000	1    57.0254862508384 4.49172576832151
````

Offered by @gunnaraasen above:

> Would being able to apply a regular expression with subexpressions let you do what you want?

It *would* help in this case, and makes for a good general solution to both problems, IMO. I'd want the ability to choose whether a given match was a tag or field though.

**Comment by mre** [comment]
We have the same issue.

I think this can be resolved adding support for multiple separators.

Here's the example from above:

Metric:
```
graphite.hadoop.yarn.NodeManagerMetrics.Context=yarn.Hostname=nid00035.cray.com.AllocatedContainers
```

Graphite config:

```
[[graphite]]
  separator = "."
  separator = "="
  templates = [ ".service.component.type.=context.=hostname.hostname.hostname.measurement" ]
```

Result:

```
AllocatedContainers,service=hadoop,component=yarn,type=NodeManagerMetrics,context=yarn,hostname=nid00035.cray.com
```

This way we can strip `Context=` and `Hostname=` from the metric.


Additionally it supports cases like the following:

Metric:
```
twemproxy-redis_mypool.gauge-1.2.3.4.6380-server_connections 123
```

Graphite config:

```
[[graphite]]
  separator = "."
  separator = "-"
  separator = "_"
  templates = [ "service-database_pool.field-host-measurement*" ]
```

Result:

```
server_connections,service=twemproxy,database=redis,pool=mypool,host=1.2.3.4.6380 gauge=123
```

This would be backwards-compatible. In addition it would be quicker and easier than full regex support.
The algorithm would be O(n) because we simply iterate over the graphite metric once, splitting at the position of the next *matching* separator in the template.

I could try to create a pull request for that if you think this change will be accepted.·

**Comment by asicoe** [comment]
Is this going to happen at some point?

**Comment by EpiqSty** [comment]
Any news here? 
What are best-practice for such cases, when tag contains IP address or FQDN?
