### ISSUE TITLE
Cannot upload a file that i just downloaded from influxdb

### ISSUE THREAD

**Issue by gitvegas** [influxdata/influxdb#6521]
I used this to get the data into test1.txt
curl -G 'http://localhost:8086/query' --data-binary “db=my_db_get" --data-urlencode "q=select * from \”original_test\" limit 1">test1.txt

Same file i try to upload to another db, but fails with the below error
curl -i -XPOST 'http://localhost:8086/write?db=my_db_post' --data-binary @test1.txt

{"error":"unable to parse '{\"results\":[{\"series\":[{\"name\":\"sample.technology.change\",\"columns\":[\"time\",\"host\",\"value\"],\"values\":[[\"2016-04-29T17:05:27Z\",\"srt1.tre.ret\",0]]}]}]}': missing tag value"}

It all used to be json wonder why we have to now use .txt files?

**Comment by toddboom** [comment]
@gitvegas The output of queries is in JSON format, but input data must be formatted using our line protocol:
http://docs.influxdata.com/influxdb/v0.12/write_protocols/line/

We made this switch about a year ago (in the v0.9.x versions) and officially removed the JSON input a few months ago.

**Comment by gitvegas** [comment]
Thanks for your response, i really need your help here. I have large amounts of data in my_db. I want to split this into multiple dbs with in influx. How can i do this quickly.
I thought i query/download from one and quickly upload to another. But now this format differences is blocking me. Please help.

**Comment by gitvegas** [comment]
Your Help is really appreciated! Please tell me how can i split my data in my_db into multiple dbs (with in influx) my_db1, my_db2, my_db3........my_db100. I have to do this else Grafana is choking.
