### ISSUE TITLE
Random crash soon after shard switch

### ISSUE THREAD

**Issue by ljagiello** [influxdata/influxdb#6526]
InfluxDB - 0.12.2-1 (official package) + telegraf (0.12.0-1)
Ubuntu LTS 14.04 (32cores, 180GB memory, raid10 from ssds), kernel 3.19.0-56-generic

InfluxDB config: https://gist.github.com/ljagiello/7b1f2ad6623259c2c128c188feb73968
Telegraf clients: 1.5k-2.5k 

Multiple times InfluxDB crash just after shard switch.

8:00 at graph is a time when InfluxDB should start write data to new shard (new shard every 3h). Typical shard size ~1.3GB.

```
> SHOW RETENTION POLICIES ON telegraf
name	duration	shardGroupDuration	replicaN	default
default	168h0m0s	3h0m0s			1		true
```

Graphs looks like:
![graph1](http://i.imgur.com/8wgNq5x.png)
![graph2](http://i.imgur.com/WVZZwJN.png)
![graph3](http://i.imgur.com/OtWR0sb.png)
![graph4](http://i.imgur.com/2mmevMM.png)
![graph5](http://i.imgur.com/nCir6Vp.png)
![graph6](http://i.imgur.com/IoSNvgg.png)

**Comment by jwilder** [comment]
Your second graph looks like you are getting big write load coming in from your network at that time.  Are those connections getting blocked/leaked?

**Comment by ljagiello** [comment]
@jwilder I'm not sure why there was such a spike in network (only telegraf is sending data). I will try to catch crash next time and sniff some traffic (it happen again today).

**Comment by ljagiello** [comment]
Since 0.13 it's super stable, closing this issue.

**Comment by jwilder** [comment]
@ljagiello Great!  Fyi... we added a setting for HTTP connection limits that might be useful in this situation: #6601
