### ISSUE TITLE
[Feature Request] Add support for default limit to CLI Influx client

### ISSUE THREAD

**Issue by gena01** [influxdata/influxdb#6528]
### Feature Request

**Proposal:** Would be nice for the CLI to have a default limit when one is not provided in the interactive mode. It could potentially be changed (I think there's also settings that would remember the limit value)

**Current behavior:** If i leave limit out of the query potentially this can pull down a lot of data.

**Desired behavior:** Ideally default limit, something like 25 would provide a way to pull down a screen full (or multiple screens full) of data instead of pulling down lots of rows.

**Use case:** When writing queries using the CLI it would be nice to know that if I make a mistake worst thing that will happen is that the default limit will limit the amount of data I am looking at.

**Comment by viru** [comment]
What if someone wants to fetch all the records using CLI? Adding default limit might be misleading. Should there be some information when default limit triggers and option to bypass default limiting?

**Comment by shaybix** [comment]
In the case where someone wants to pull down all the data, should there be a flag?

**Comment by mammenj** [comment]
can the default be to return all data and introduce a new flag to limit the data?

**Comment by mahekchheda** [comment]
is this feature still needed? I would like to take this and start contributing to this project.
