### ISSUE TITLE
Value is not updated on duplicate write

### ISSUE THREAD

**Issue by brstgt** [influxdata/influxdb#6536]
Influx Version: 0.12
OS: Ubuntu 14.04

In some situations, overwriting a value for the same "point" does not work.
I recognized this behaviour in a real situation when I tried to correct some values on a downsampled measurement. When I tried to override a value on a plain fresh new measurement, everything worked fine, but doing so on a measurement that was in daily usage, it did NOT work.

As an example, i picked a single record in an existing measurement:

This is a kind of a dump what the PHP client lib was really doing:
HTTP Write URL: /write?db=user&precision=s&rp=INF
Payload (Represents lines in Line Protocol)
Array
(
    [0] => user_action-1d-#country#gender#client,country=US,gender=2,client=232 match=10000i,value=1i 1462060800
)

BEFORE:
> SELECT * FROM "user"."INF"."user_action-1d-#country#gender#client" WHERE country='US' AND gender='2' AND client='232' AND time > '2016-04-30'
name: user_action-1d-#country#gender#client
-------------------------------------------
time			became_active	became_inactive	block_received	block_sent	client	country	dislike_received	dislike_repeat	dislike_sent	gender	like_received	like_sent	magic_moment	match	moment_like	moment_upload	photo_upload	visit_received	visit_sent
1462060800000000000	164		281		375		864		232	US	206497			5735		102586		2	184335		23892		131		3522	6555		2072		1052		81332		56839

AFTER:
> SELECT * FROM "user"."INF"."user_action-1d-#country#gender#client" WHERE country='US' AND gender='2' AND client='232' AND time > '2016-04-30'
name: user_action-1d-#country#gender#client
-------------------------------------------
time			became_active	became_inactive	block_received	block_sent	client	country	dislike_received	dislike_repeat	dislike_sent	gender	like_received	like_sent	magic_moment	match	moment_like	moment_upload	photo_upload	value	visit_received	visit_sent
1462060800000000000	164		281		375		864		232	US	206497			5735		102586		2	184335		23892		131		3522	6555		2072		1052		1	81332		56839

Expected:
Field "match" should be "10000". Actually it did not change from 3522 to 10000. The query itself was executed as can be observed by changing the value for field "value".

This example is not bound to a special field nor to a special time-range. It happens on all points on all kind of measurements in our production system. In contrast, just to repeat, it worked on a plain, fresh measurement with only a few test points.

**Comment by jwilder** [comment]
Dup of #6439
