### ISSUE TITLE
[Feature Request] Subscriptions should allow HTTP instead of UDP

### ISSUE THREAD

**Issue by cnelissen** [influxdata/influxdb#6538]
The current CREATE SUBSCRIPTION syntax only allows UDP endpoints however kapacitor can also support HTTP writes. On networks with high latency or virtual host environments where guest VM limitations might prevent reliable UDP communication, or situations where any amount of data loss is unacceptable, HTTP/TCP is much more reliable than UDP.

Example syntax:

CREATE SUBSCRIPTION sub0 ON "mydb"."default" DESTINATIONS ALL 'http://example.com:9090'

**Comment by gunnaraasen** [comment]
HTTP and HTTPS subscriptions are now supported in InfluxDB and Kapacitor versions 1.0.0-beta1+. See https://github.com/influxdata/influxdb/pull/6655.
