### ISSUE TITLE
Add query or API to see what queries are running in the cluster

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#654]
We need visibility into what queries are running in the cluster on which nodes and for how long. This should be a new query type like:

```
list running queries
```

Which return a table of results like:

```json
[
  {
    "name":"running queries",
    "columns": ["id", "start_time", "host", "query", "running_time", "user"],
    "points" : [...]
  }
]
```

**Comment by jsternberg** [comment]
Closing in favor of #5939.
