### ISSUE TITLE
InfluxDB Client /query endpoint: invalid character 'M' looking for beginning of value

### ISSUE THREAD

**Issue by sparrc** [influxdata/influxdb#6540]
Script to reproduce:

```go
package main

import (
	"fmt"

	"github.com/influxdata/influxdb/client/v2"
)

func main() {
	c, _ := client.NewHTTPClient(client.HTTPConfig{
		Addr: "http://localhost:8086",
	})

	database := "telegraf"
	_, err := c.Query(client.Query{
		Command: fmt.Sprintf("CREATE DATABASE \"%s\"", database),
	})

	if err != nil {
		fmt.Println(err)
	}
}
```

this bug began at commit: 6f61c0e

any commit before that returns no error.

cc @jsternberg

**Comment by jsternberg** [comment]
@sparrc can you look at the InfluxDB log and see if a `GET` or `POST` was used?

**Comment by sparrc** [comment]
Neither, it didn't get to the point of making a request:

```
‹6f61c0e› % go run /tmp/foo.go
invalid character 'M' looking for beginning of value
‹6f61c0e› % git checkout HEAD~1
...
 ‹87e531e› % go run /tmp/foo.go
 ‹87e531e› %
```

Only the second `go run` did anything db-side:

```
2016/05/02 19:02:28 Sending anonymous usage statistics to m.influxdb.com
[query] 2016/05/02 19:03:04 CREATE DATABASE telegraf
[http] 2016/05/02 19:03:04 ::1 - - [02/May/2016:19:03:04 -0600] GET /query?db=&q=CREATE+DATABASE+%22telegraf%22 HTTP/1.1 200 40 - InfluxDBClient ca265a20-10ca-11e6-8007-000000000000 431.337µs
```

**Comment by jsternberg** [comment]
Use a newer version of InfluxDB. You're running on a version of InfluxDB that doesn't allow `POST` and using the version of the library that tries to use `POST` requests.

I'm going to close this for now. Do you need some way to customize the v2 library to use `GET` requests?

**Comment by sparrc** [comment]
Got it, I'm using an influx cloud instance and have no control over the InfluxDB version, so I don't need to customize but I'll just stick with tag v0.12.1 for the library

**Comment by sparrc** [comment]
PS: would it be possible to return a more useful error message? `invalid character 'M' looking for beginning of value` is a bit obscure

**Comment by jsternberg** [comment]
Maybe? That seems like one of the weird Go error messages with no context. I'm not sure exactly where it's coming from though and it might be something from within the HTTP library.

**Comment by jchauncey** [comment]
I am seeing this exact error message using Influx `0.12.2`

**Comment by jchauncey** [comment]
THis problem does not show up in the nightly build but is present in all the `0.12.x` releases

**Comment by sparrc** [comment]
@jchauncey the tip of the client library is not compatible with older releases, you'll have to use the 0.12.x tag of the client library for 0.12.x influxdb

**Comment by sparrc** [comment]
@jsternberg will influxdb 0.13 still support the GET requests? it might not be worth changing it until later, when more users have migrated to 0.13 or 1.0+

**Comment by jchauncey** [comment]
ah that makes sense thanks

**Comment by jsternberg** [comment]
@sparrc InfluxDB 0.13 still supports GET requests, but includes a deprecated message that follows along with it. So I changed the Influx CLI to use POST requests to avoid that deprecated message.

Maybe we can have the client library support both and use a flag to determine if it uses GET or POST?

**Comment by kedark3** [comment]
I faced the same error. And I find this error very confusing with no context whatsoever. Whenever I type influx to access cli, I got this error. And I had upgraded from 0.12 to 1.0. @sparrc  I agree with you on changing this error to be more useful.
