### ISSUE TITLE
Support changing group by day to when daylight savings time switches

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#6542]
From a discussion in #2074 and requires #6541 to be implemented.

Adjust the bucket for anything over a day when daylight savings time comes into effect or out of effect when a timezone has been specified.

**Comment by tottote** [comment]
Correct time handling in any software requires just three steps:

1. Do all the time math in local time
2. Convert times to UTC just prior to using them
3. Use UTC time in all time stamps (in databases etc.)

The last one is important in keeping the data portable. The biggest mistake would be to store data with timestamps in local time, but fortunately influxdb is not making this mistake. (Apple propably didn't use these three principles with iPhone alarm clock app some five years ago, and we can only guess how many people slept in).

In the case of adjusting buckets to reflect DST changes, these three principles translate to the following:

1. Keep the bucket start and end pointers in local time, increment them in local time
2. Convert bucket pointers to UTC every time you've adjusted them
3. Use the UTC timestamps to fetch one bucketful of data from the db

That's all there is. This pretty much handles all the time zone requirements, including DST changes in the middle of the `GROUP BY` query.

**Comment by sebastianherp** [comment]
+1

The offset was helpful, but unfortunately my offset changes twice a year (DST).

**Comment by jsternberg** [comment]
I'm just going to merge this with #6541. I now believe the two are inextricably linked. I'll reopen this and do them separately if I turn out to be wrong.
