### ISSUE TITLE
[0.12.2] Tag value query performance problems

### ISSUE THREAD

**Issue by dsw6** [influxdata/influxdb#6549]
Querying tag values for a measurement is slow when there are a few hundred values.

The query below returns 140 results and takes 4.5 seconds when run from the InfluxDB Admin console.

Query:  SHOW TAG VALUES FROM "esf_events" WITH KEY = "client"

It doesn't seem like 140 tag values is a lot.  I'm using these queries to populate template variable lists in Grafana when a dashboard loads.  The long query times result in long delays in loading the dashboard. 

If I use a where clause to filter the results, performance improves dramatically.  The following query takes 160ms and returns 55 results

Query:  SHOW TAG VALUES FROM "esf_events" WITH KEY = "client" where serviceKey = 'MEMBER_SERVICE'

Influx 12.2
Ubuntu 14.04.4 LTS

**Comment by jwilder** [comment]
@dsw6 Can you attach the output of `show stats` and `show diagnostics`?

**Comment by dsw6** [comment]
Attached:

[showDiagnostics.txt](https://github.com/influxdata/influxdb/files/247763/showDiagnostics.txt)
[showStats.txt](https://github.com/influxdata/influxdb/files/247764/showStats.txt)

**Comment by dvenza** [comment]
To me it happens with a SHOW TAG query that returns just two results. Adding a WHERE clause that does not filter anything will not make it faster, while if I set the WHERE clause to filter and return just one result, then it returns instantaneously.

**Comment by srikara** [comment]
We have seen a similar problem as well. It appears that in 0.12.2 (possibly post 0.10) tags are stored in the default retention policy as a measurement (_tags). If you have a custom retention policy that is the default (which we had) and the data set in that retention policy is reasonably large, it apparently impacts the 'show tag values' response time .
We created another retention policy, made it the default and did not use it for our purposes. That seemed to help.

**Comment by adampl** [comment]
@srikara So you recommend to always use a non-default retention policy?

**Comment by jsternberg** [comment]
The `SHOW TAG VALUES` command was optimized and is present in all of the 1.0 beta versions. If there are still issues with this, please file a new issue so we can continue trying to make it faster. Thanks.
