### ISSUE TITLE
Add ability to kill a running query

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#655]
#654 Will add functionality to see which queries are running in the cluster. We should have another query that will allow a user to kill a running query.

```sql
kill query 23 on hosta
```

To kill a query we'll need the host it's running on and the query id.

**Comment by beckettsean** [comment]
Related to https://github.com/influxdb/influxdb/issues/411

**Comment by jwilder** [comment]
Fixed via #5950
