### ISSUE TITLE
influxDB 0.12.2 uses port 8088 but doesn't have a documented way to re-configure

### ISSUE THREAD

**Issue by RichardKorry** [influxdata/influxdb#6550]
I am upgrading from 0.9.5 to 0.12.2 on Centos 6.5

The Hadoop history server uses port 8088 so for 0.9.5 the bind-address was changed in /etc/influxdb.conf from 8088 to 8084.
[meta]
  dir = "/var/lib/influxdb/meta"
  hostname = "localhost"
  # Changing from 8088 to 8084 due to conflict with Hadoop History Server
  bind-address = ":8084"

In 0.12.2 I didn't see this config listed in influxdb.conf. When 0.12.2 influxdb starts it dies when infuxdb tries to listen on 8088. I tried adding bind-address = ":8084" to influxdb.conf but that didn't have any visible effect.
The log shows:
[run] 2016/05/03 17:56:33 InfluxDB starting, version 0.12.2, branch 0.12, commit 383332daed5595926c235f250b11433f67229c35
[run] 2016/05/03 17:56:33 Go version go1.4.3, GOMAXPROCS set to 24
[run] 2016/05/03 17:56:33 Using configuration at: /etc/influxdb/influxdb.conf
run: open server: listen: listen tcp :8088: listen: address already in use

This is a show stopper for me as I am not going to change the port for the Hadoop History Server.

Is there a different config setting I can change to cause influxdb to listen on a different port?

Thanks

**Comment by mingqing** [comment]
I use version 0.12.0:

```
$influxd config | grep :8088
bind-address = ":8088"
```

Now I edit my config file: "/etc/influxdb/influxdb.conf" to change

```
bind-address = "0.0.0.0:8089"
```

It's effective!

You edit configfile path is error? "/etc/influxdb.conf" not " /etc/influxdb/influxdb.conf"?

**Comment by e-dard** [comment]
@RichardKorry the port can be configured in the config file, using the top-level `bind-address` field.

You can also set it with an environment variable, which would be something like:

```
$ INFLUXDB_BIND_ADDRESS=:1234 influxd
```

**Comment by RichardKorry** [comment]
Thanks all for the suggestions.
For 0.9.5 the line setting bind-address was under [meta]. 
I ran `influxd config | less` and saw bind-address was before [meta].
For 0.12.2 I moved it outside of [meta] and it worked.
