### ISSUE TITLE
Provide a tool to upgrade from 0.11

### ISSUE THREAD

**Issue by aviau** [influxdata/influxdb#6552]
Hello,

I am the maintainer for InfluxDB in Debian and I was deceived when I saw that there are no tools in 0.12 to upgrade from 0.11.

Uploading 0.12 forced some Debian users to wipe their databases.

For a distribution, it is not possible nor realistic to include older versions of packages just so that users can perform the backup.

0.12+ should be shipped with a tool that does the influxdb backup command so that users can upgrade without needing to perform an action before upgrading to 0.12.

If you are not willing to do it for 0.12, please consider it for future breaking changes.

**Comment by jwilder** [comment]
0.11 to 0.12 this was not possible.  There are [upgrade instructions](https://docs.influxdata.com/influxdb/v1.1/administration/upgrading/#upgrade-from-0-10-or-0-11-to-1-1) that specify what should be run before upgrading using the older version.
