### ISSUE TITLE
Arithmetic operations with missing data

### ISSUE THREAD

**Issue by BMarvi** [influxdata/influxdb#6553]
### Bug report

__System info:__ [0.12.1-1, linux]

__Steps to reproduce:__

1.

    insert test a=1,b=2,c=3
    insert test a=2,b=3,c=4
    insert test a=2,b=3

2.

    select a+b+c as sum from test
    time                    sum
    1462358149185277772     6
    1462358162745440464     9
    1462358165193353813

3.

    select a+b+c as sum from test fill(0)
    time                    sum
    1462358149185277772     6
    1462358162745440464     9
    1462358165193353813

__Expected behavior:__ [What you expected to happen]

    time                    sum
    1462358149185277772     6
    1462358162745440464     9
    1462358165193353813     5

eventually on the second query where fill(0) is used

__Actual behavior:__ [What actually happened]

    time                    sum
    1462358149185277772     6
    1462358162745440464     9
    1462358165193353813

**Comment by jsternberg** [comment]
The fill directive currently only works with aggregates and is meant to fill in a window where there is no data. So the fill gets ignored with this query (which maybe we should introduce an error message when somebody tries this).

When it comes to arithmetic, instead of using a zero value for a missing value we treat any operation against a null value as equaling null. Does this help clarify what's happening?

**Comment by BMarvi** [comment]
Yes thanks, this clarify. 
Now I know that any aritmetic operation that involves a null value is inteded to return a null value.
But I think that there are situations where a different behavior would be more useful. 
Not always easy to implement, I admit. 
In my case, in a null value in a sum, would be reasonable to treat it as a zero.
My real application consist of a bunch of conditioning machines that refriger a server farm. We store the watts for each of them.
Could happen that a machine is added or removed. So this become a problem when this occours:
adding a new machine (and adding it to the query) would result in a null result for all the previus points. 
A flag could be used to change the beavior, something like the fill(0) I tried. 
Not as easy for other operations... Moltiply for a missing value maybe better to return null or 0? or something else? Don't know how to threat this case for example.

**Comment by jsternberg** [comment]
Closing this in favor of #7216 and this will probably get implemented as part of #3552.
