### ISSUE TITLE
Overwriting points on large series can cause memory spikes during compactions

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#6557]
While investigating a query case that could OOM the server (see #6556), it was discovered that compactions likely have the same problem.

If there are a lot of points on disk for the same series spread across many blocks in TSM files and a point is overwritten near the beginning of the shard's time range, the full series could be loaded into RAM triggering OOMs and huge allocations.

The compaction code uses a similar method as the query path to handle updating points in the past in that it just reads the whole series and deduplicates in memory.  It's very likely that this can cause the server to OOM during compactions if enough data is being compacted.  Compaction code needs to be updated similar to the fix in #6556.

**Comment by andybrier** [comment]
I have the same issure
