### ISSUE TITLE
HTTP Connection Limits

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#6559]
### Feature Request

The HTTP input currently allows an unbounded number of connections and relies on the client to be well-behaved.  This can cause problems in the case where the client is not well-behaved or the system is overloaded and slow to process connections.  

For example, a client that does not close connections correctly can cause the server to hold onto buffers for the connection for long periods of time and potentially OOM the process.  Similarly, if the system has saturated CPU or Disks, connections can pile up waiting to be processed

The database should have config options to mitigate these kinds of issue:

* **Max Connections** - A hard limit where we immediately return an error and close new connections when the limit is exceeded.
* **Max Concurrent Writes** - A hard limit where we immediately return an error and close new `/write` connections when the limit is exceeded.  
* **Max Concurrent Queries** - A hard limit where we immediately return an error and close new `/query` connections when the limit is exceeded.  

The default value for these options should be `0` (disabled) for backwards compatibility.

**Comment by jsternberg** [comment]
@jwilder we already have maximum concurrent queries, but I can add maximum concurrent writers and concurrent connections.

Also, should the overall connection limit apply to any HTTP connection? If so, does that include the debug endpoints and the `/status` endpoint?

**Comment by jwilder** [comment]
@jsternberg The connection limits should be separate for write and query.  Can probably scrap the max connections limit if they are separated.
