### ISSUE TITLE
Continuous query odd performance issue

### ISSUE THREAD

**Issue by ruttosan86** [influxdata/influxdb#6568]
Hi all,
we are evaluating InfluxDb for an internal project, and we came across some odd behavior when evaluating continuous query performance. Here is our setup:

**Server specs:**
CPU: i7 4770 4 core (8 thread)
RAM: 32 GB
Drives: 
sda <- SSD Samsung EVO 850 250GB (OS + swap + influxdb data directory + influxdb meta directory)
sdb <- SSD Samsung EVO 850 250GB (influxdb WAL directory)
OS: Centos 7 x64
InfluxDB:
Version 0.12.2
linux Go 1.4.3 (arch amd64, maxproc 8)
logs disabled
wal directory on dedicated SSD (sdb)
data & meta directory on main disk (sda)
http "max-row-limit" set to 0
**Schema:**
at this moment we have only 2 type of data, a RAW input and its minute aggregation. The RAW data point (measurement "raw") ingested by our system has a nanosecond timestamp, one tag (called "topic") and several fields, of which only 2 are used for the aggregation process (let's call it val1 and val2, both numbers).
The second measurement, "minute", is produced with the CQ by downsampling the data with 1 minute window.
We decided to split this two measurements in two different databases, dbRAW and dbMIN.
The first has as default retention policy "raw_policy", with duration 7d and shard duration 30m, while the second db has as default RP "minute_policy" with duration 90d and shard duration 1w
That said, the query we use to produce the "minute" data is:
SELECT sum(val2) as tot_v2, min(val1) as min_val1, max(val1) as max_val1, first(val1) as in_val1, last(val1) as out_val1, mean(val1) as avg_val1, count(val1) as event_num INTO dbmin.minute_policy.minute FROM dbraw.raw_policy.raw GROUP BY time(1m), topic fill(none)

**Ingestion rate:**
In our tests we tried to simulate the "production" rate. In our case we have a population of "topics" that produces the raw points. This population is divided in 4 categories, called bottom, low, mid and high. The distribution is the following:
Bottom: 98000 topics, producing in total ~27 raw points per second
Low: 8000 topics, producing in total ~347 raw points per second
Mid: 500 topics, producing in total ~417 raw points per second
High: 140 topics, producing in total ~1540 raw point per second
which in total gives an ingestion rate of roughly 2331 raw point/sec and 106640 different series (just for the "raw" measurement). (note: With this ingestion rate the machine "sits" comfortably with very little RAM and CPU taken by the influx process)

**The "Issue":**
Now, we wanted to evaluate how fast the CQ are for the aggregation process, so we created the CQ (with the above select query) and monitored its processing time. With the above ingestion rate, the average CQ execution time was ~26sec, a time which is more than enough to keep up with the data production.That said though, we noticed something odd happening to the server during the CQ execution: during the first 8-9 seconds the CPU was used (1 core @~100%), after which influx starts to write very intensively for the remaining 17-18sec over the WAL directory. We noticed this by using the "iostat" command, which reported 90-95% utilization for the sdb partition (the one containing the WAL partition) with more or less 1000 write requests per second (!!). Take in account that in average the aggregated points are more or less 10000 every minute (~10000 different topics writes at least a raw point per minute), not a huge amount of data!

With this in mind, we wondered what happens if we ask from an external process the aggregated data and then write the result back in the dbmin database (I know, the idea seems odd but the results were more than surprising!).
So, we built a little Java program that every minute:
sends the following query to influxdb: 
SELECT sum(val2) as tot_v2, min(val1) as min_val1, .... (same field as the first query) FROM dbraw.raw_policy.raw WHERE time >= start and time < end GROUP BY topic fill(none)
where "start" and "end" differs for exactly a minute, and end equals to the current minute
uploads the result data in the same influxdb istance, writing the data in dbmin.minute_policy.minute
By doing this, we went from ~26 seconds to ~9!! In particular, we have
~8-9sec for the data retrieval
~400-500ms for the write in influx
"normal" disk usage (no 90-100% spikes)
Are we doing something wrong with the CQ configuration? Why this totally different behavior?  

Thanks for answering,
Davide Soldi

**Comment by jwilder** [comment]
Fixed via #6732
