### ISSUE TITLE
New Nightly Build URL

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#6569]
This is a PSA that we are going to be changing the nightly URL from the existing:
```
https://s3.amazonaws.com/influxdb/<package>
```
To:
```
https://dl.influxdata.com/influxdb/nightlies/<package>
```
All nightly builds will also be removed from the `influxdb` bucket after today to avoid confusion. Let me know if anyone has any questions or concerns!

**Comment by toddboom** [comment]
:+1:
