### ISSUE TITLE
uint64 values are converted to string

### ISSUE THREAD

**Issue by paulstuart** [influxdata/influxdb#6570]
__System info:__ 0.12.2, 0.13-RC1, CentOS 6.7
__Steps to reproduce:__

1. Write a value that is of  type uint64

__Expected behavior:__ The value should be numeric

__Actual behavior:__ The value is a string

__Additional info:__ SNMP counters are (supposed to be) unsigned integers. I'm guessing the engine is treating all integers as int64. Not sure how to handle numbers greater than 2^62.

**Comment by jsternberg** [comment]
Can you give an example of how you are writing and querying the data? Thanks.

**Comment by jsternberg** [comment]
I'm closing this due to a lack of a response. If you are still running into this issue, please respond with more information and I'll reopen the issue so we can resolve the issue. Thanks.
