### ISSUE TITLE
"wrong" time used for inserting result of continuous queries

### ISSUE THREAD

**Issue by dennisjac** [influxdata/influxdb#6573]
I noticed that when a CQ is run with a group by time of 10m and that query runs at 4:20 o'clock then the resulting aggregated value is inserted with a time of 4:10 and not 4:20 as I would expect.
Given that we are talking about aggregated values over a 10m interval I guess neither solution is really correct but using the time of when the CQ was run has the advantage that the calculated values are not older than now()-interval rather than the current now()-(2*interval).

Arguably the best way would be to use the start time of the CQ minus interval/2 to put the time right in the middle of the interval of the aggregated values.

**Comment by jwilder** [comment]
This is just how `group by` time works for queries.  The CQ writes a point at 4:10 with the aggregate value within the interval of 4:10-4:20 (excluding 4:20).  Changing this default behavior would be a breaking change though.
