### ISSUE TITLE
influx_inspect does not handle command line argument correctly

### ISSUE THREAD

**Issue by dennisjac** [influxdata/influxdb#6576]
influx_inspect seems to handle the command line arguments in a rather casual fashion:

```
0 root@nexus influxdb # influx_inspect info /var/lib/influxdb/
Shards: 0, Indexes: 0, Databases: 0, Disk Size: 0, Series: 0

Shard       DB      Measurement Tags [#K/#V]    Fields [Name:Type]  Series
0 root@nexus influxdb # 
```

Notice that I specified "/var/lib/influxdb" instead of "-dir=/var/lib/influxdb" and influx_inspect not only didn't exit with an error message or code but apparently simply proceeded to silently use the default of $HOME/.influxdb which is very deceptive.

The command line parser for influx_inspect (and all other binaries including influxd) should be much more strict in handling arguments and bail with an error if unknown arguments are provided.
Failure to do so might result in either misinforming the user (if i had a datastore under $home/.influxdb I might not even have noticed that I'm getting values for the wrong one) or at worst dataloss.

As a bonus the parse should also use a more standard handling of argument e.g. use double dashes for long arguments ("--dir"), single dashes for short arguments ("-d"). 

I'm not familiar with go but this package seems to provide all this and more:
https://github.com/codegangsta/cli

**Comment by crmejia** [comment]
I’ve been looking at this issue and asking around on the slack channel. @e-dard suggested that we use same flag approach that we use in other tools like  `influxdb/cmd/influx`. I think this is a good idea and at the same time I can implement stricter rules as suggested in the issue. 

How does that sound?

cc @corylanou

**Comment by shaybix** [comment]
@dennisjac There doesn't seem to be an 'info' command when running 'influx_inspect info'?
