### ISSUE TITLE
Odd behaviour of time series containing the ":" char in its name

### ISSUE THREAD

**Issue by Hypfer** [influxdata/influxdb#6583]
### Bug report

**System info:** Default config on Debian Jessie. Influx v0.12.2

**Steps to reproduce:**
1. Install Influx v0.12.2
2. Push data to a time series containing ":" in its name e.g. curl -i -XPOST 'http://localhost:8086/write?db=foo' --data-binary 'HALLO\ : value=0.64'
3. Stop Influx
4. Start Influx
5. Try querying this time series. 

**Expected behavior:** Should work fine

**Actual behavior:** Sometimes it looses all data permanently; sometimes it is empty but if you push again everything is back. Just very odd

**Additional info:** Fresh install. No errors in influxdb.log

**Comment by e-dard** [comment]
@Hypfer `:` is not a special character and does not need to be escaped. There are a couple of issues with using `\` as a literal character, which I think  you may be running into.

**Comment by jasase** [comment]
There is a white space between `HALLO` and `:` that need to be escaped.

**Comment by e-dard** [comment]
@jasase are sorry I missed that. I will look into this more today.

**Comment by jwilder** [comment]
I'm not able to reproduce this with 1.1.
