### ISSUE TITLE
influx_inspect panics

### ISSUE THREAD

**Issue by keep94** [influxdata/influxdb#6596]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

version 0.12.2, 14.04.1 Ubuntu

__Steps to reproduce:__

1. influx_inspect info

__Expected behavior:__ [What you expected to happen]

influx_inspect should print general info about my influx storage.

__Actual behavior:__ [What actually happened]

influx_inspect info panics.

__Additional info:__ [Include gist of relevant config, logs, etc.]

The panic I get is the following:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x497cde]

goroutine 1 [running]:
github.com/influxdata/influxdb/tsdb.(*FieldCodec).Fields(0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:846 +0x4e
main.cmdInfo(0xc20800a520, 0x1b)
	/root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/info.go:65 +0x107e
main.main()
	/root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:51 +0x149a

**Comment by jsternberg** [comment]
This should no longer be an issue as that code has been removed. If the code fails with 1.0.0-beta2, please comment so I can reopen the issue.
