### ISSUE TITLE
CSV export - A more excel friendly csv format

### ISSUE THREAD

**Issue by larrywalker** [influxdata/influxdb#6603]
### Feature Request

CSV format is not easy to import in to Excel or other tools, because of header before each line of data.

Why does exporting to csv generate a header before each data sample?

I can see where this might make sense when you have varying columns between samples, but when you are specifying the columns in the query and all the samples have the same columns, then the headers are just noise and make it difficult to import into other programs (excel).  We have to post process and format the output before sending to excel.

For example.

influx -database 'test' -execute "SELECT count(distinct(a)) as col1, count(distinct(b)) as col2, max(c) as col3 FROM mymsrmt WHERE time > now() - 1d  GROUP BY device" -format 'csv'

name,tags,time,col1,col2,col3
mymsrmt,device=dev1,1462738962827845988,25,1,3
name,tags,time,col1,col2,col3
mymsrmt,device=dev2,1462738962827845988,29,1,3
name,tags,time,col1,col2,col3
mymsrmt,device=dev3,1462738962827845988,29,1,3
name,tags,time,col1,col2,col3
mymsrmt,device=dev4,1462738962827845988,33,1,3
name,tags,time,col1,col2,col3
mymsrmt,device=dev5,1462738962827845988,33,1,3
name,tags,time,col1,col2,col3
mymsrmt,device=dev6,1462738962827845988,25,1,3

Can we get an option to simply the output?

**Comment by opusmagnum** [comment]
You can use _awk_ one-liner as a filter for csv output, as recommended by @mark-rushakoff  in https://github.com/influxdata/influxdb/issues/6415.

**Comment by corylanou** [comment]
I'm not opposed to suppressing headers if they don't change.  This might need to be an option as it could have undesired side affects with different data sets.

**Comment by jsternberg** [comment]
Related to #7099, but we will also have to modify the CLI program to directly output the HTTP response instead of attempting to do its own formatting.
