### ISSUE TITLE
[feature request] Expose series cardinality per measurement

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/influxdb#6608]
### Feature Request

**Proposal:** Record the measurements with the highest cardinality in the `_internal` database.

**Current behavior:** The `_internal` database currently has a `database` measurement with a `numSeries` field, which shows the number of series in that database.

**Desired behavior:** Another measurement called `measurement` (or another suggested name) would also be recorded with a field that contains the names of the measurements with the highest cardinality.

**Use case:** It's almost impossible to find measurements with a high number of series in a busy InfluxDB instance. For example, it is hard to troubleshoot if a poorly written or broken Telegraf plugin is creating an excessive number of series. This could also be expanded functionality for the `SHOW MEASUREMENTS` or `SHOW SERIES` queries.

**Comment by pmenglund** [comment]
👍

**Comment by daniel-hesse** [comment]
👍

**Comment by daviesalex** [comment]
+1

**Comment by endeepak** [comment]
We have hit the issue of max series per database. We need to find out measurements which have highest cardinality and clean them up. 

Currently is there any way or script to figure out which measurement has highest cardinality?

**Comment by davemt** [comment]
+1 is this difficult to implement?

**Comment by endeepak** [comment]
We are using this shell script for now https://gist.github.com/endeepak/3a09d80c58bd732f815f2b25f2adafd7
