### ISSUE TITLE
New version influxdb get  CPU full load when searching the larger data 

### ISSUE THREAD

**Issue by kengan** [influxdata/influxdb#6610]
My question is https://github.com/influxdata/influxdb/issues/6482

Because it is too urgent, can some one help me  ,thank you very much.

**Comment by jwilder** [comment]
Dup of #6482.  

@kengan We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.

**Comment by kengan** [comment]
@jwilder  I have send a e-mail to you,please receive it, thank you.
