### ISSUE TITLE
Queries slow down hundreds times after overwriting points

### ISSUE THREAD

**Issue by kub00n** [influxdata/influxdb#6611]
### Bug report

__System info:__ 
InfluxDB 0.13, InfluxDB 0.12.2
Ubuntu 14.04.1

__Steps to reproduce:__

1. Add some measurements ( 5M points, timerange: 5000 s )
```
...
test_series,tag=tag1 value=2 1462060800001
test_series,tag=tag2 value=3 1462060800002
test_series,tag=tag0 value=4 1462060800003
...
```

2. Run a query
3. Insert exactly the same points again (overwriting old ones)
4. Run a query

__Expected behavior:__ 
Both query return the same results at a similar time

__Actual behavior:__ 
Results are the same, but second query (after overwrite) is almost 500 times slower than the first query. Repeating query after 10s works a bit faster but still far from the first query.

__Additional info:__
I wrote simple python script to reproduce it : [influx_overwrite_bug.py](https://gist.github.com/kub00n/2ef45f6aca7b4b70348343d2cbfed95f) :
```
==CREATING DATABASE==
==INSERTING SERIES==
* inserting 5000000 points: from 1462060800000ms - to 1462065800000ms
==QUERY==
* query: select * from test_series LIMIT 1
* result: {u'tag': u'tag0', u'value': 1, u'time': 1462060800000}
* duration: 0.0093s
==INSERTING SERIES==
* inserting 5000000 points: from 1462060800000ms - to 1462065800000ms
==QUERY==
* query: select * from test_series LIMIT 1
* result: {u'tag': u'tag0', u'value': 1, u'time': 1462060800000}
* duration: 4.4923s
==SLEEP 10s==
==QUERY==
* query: select * from test_series LIMIT 1
* result: {u'tag': u'tag0', u'value': 1, u'time': 1462060800000}
* duration: 3.1518s
==REMOVING DATABASE==
```

**Comment by jwilder** [comment]
@kub00n Thanks for providing the python script.  That made it really easy to reproduce and track down the issue.  The perf issue is fixed in master, but your script highlighted a correctness issue with deduplicating overwritten points.  See #6668 which will fix that issue.
