### ISSUE TITLE
Docker build still in Go 1.4.3

### ISSUE THREAD

**Issue by easyrasta** [influxdata/influxdb#6612]
You upgrade go to 1.6.2. But you didn't update build-docker.sh and you update Dockerfile_build.
So I wonder how to build a docker image:
 - use build-docker.sh
 - or launch build.sh, (copy build/influxd or modify Dockerfile to use build/ and remove dockerignore),  then launch docker build -t influxdb .

**Comment by jwilder** [comment]
There are official images on Docker hub now: https://hub.docker.com/_/influxdb/

**Comment by easyrasta** [comment]
Ok thanks
