### ISSUE TITLE
"Bad timestamp" error with '\n' for multiple write

### ISSUE THREAD

**Issue by jerem21** [influxdata/influxdb#6614]
### Bug report

System info:
influx 0.12.2
centOS 7
node.js 4.4.4
python 3

Steps to reproduce:
1. Create multiple points with more than one tag and values in a node server
2. make a custom timestamp
3. try to write points by API/command line

Additional info:
I know that's have a lot of similar issue but mine already have the '\n'.
Here is an example of a data send:

```
> Instructions,name=WaitUntilCondition,testSuite=XCHECK-SMU,testCase=Test\\ Case,testStep=Test\\ Step,endTestSuite=1970-00-00/00:00:00.000,statusTestSuite=status boarddate=\"1970-00-00/00:00:00.000\",procedure=\"Proc\",instrName=\"WaitUntilCondition\",Zomp=\"1970-00-00/00:00:00.000\",status=\"OK\",beginTestSuite=\"1970-00-00/00:00:00.000\" 60000
```

This return an error 'bad timestamp'

The code used for (nodejs):
```
client.writePoints('Instructions',tmpPoint,function(err) {
            if (err) {
                console.log("Cannot write data : ", err);
                process.exit(1);
            }
        });
```

I also wrote a similar code in python, the same problem appear.

**Comment by mjdesa** [comment]
In the example you've given above, you're escaping the quotes on the string field values. Try doing the following instead:
```
Instructions,name=WaitUntilCondition,testSuite=XCHECK-SMU,testCase=Test\\ Case,testStep=Test\\ Step,endTestSuite=1970-00-00/00:00:00.000,statusTestSuite=status boarddate="1970-00-00/00:00:00.000",procedure="Proc",instrName="WaitUntilCondition",Zomp="1970-00-00/00:00:00.000",status="OK",beginTestSuite="1970-00-00/00:00:00.000" 60000
```

As a side note, while InfluxDB can store strings it is not optimized to do so. AFAIK storing that many strings will eat up a lot of disk.
