### ISSUE TITLE
query-log-enabled in config is ignored

### ISSUE THREAD

**Issue by dpratt** [influxdata/influxdb#6629]
### Bug report

__System info:__ 0.13.0, running in a docker container

__Steps to reproduce:__

1. add query-log-enabled = false to the config file
2. start the server

__Expected behavior:__ No query logging

__Actual behavior:__ All queries are output to stderr

**Comment by dpratt** [comment]
I've verified that the config file is actually being read by running 'influxd config'.

In previous versions of influxdb, this setting eliminated query logging - in 0.13.0, every query is output no matter what the value of the setting is. This causes quite a bit of undesired log spam for us. Sadly, I can't just redirect stderr to /dev/null, since I would like to pick up any errors or other meaningful log messages and get alerts on them.

**Comment by freeseacher** [comment]
i have the same. very annoying bug

**Comment by bacheson** [comment]
wow i've been pull my hair out on this...you'd think something this basic would work flawlessly by now
