### ISSUE TITLE
Doesn't Influxdb support collectd's types.db data source type?

### ISSUE THREAD

**Issue by minkikim89** [influxdata/influxdb#6638]
I am running collectd + influxdb + grafana.
And I read that Influxdb supports collectd.
I defined types.db with type instance and data source type(ex: DERIVE).
But influxdb stored stats just original value, not calculated value.

I know that influxdb has derivate query, but I don't want that logic because of performance.

Doesn't Influxdb support collectd's types.db data source type? Have I to use query? Isn't any other choice?

Thanks for reading :)

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list.

Thanks.
