### ISSUE TITLE
Series confusion

### ISSUE THREAD

**Issue by sofixa** [influxdata/influxdb#6673]
Hello.

I have a question that might be a bit simple, but a Google search didn't help that much.

I'm running Telegraf 0.11 and 0.12 on different servers with a single InfluxDB that was on 0.11.1 until yesterday, when i updated to 0.13.

According to the [InfluxDB documentation](https://docs.influxdata.com/influxdb/v0.13/concepts/glossary/#series), a serie is 
```
The collection of data in InfluxDB’s data structure that share a measurement, tag set, and retention policy.
```
Therefore, a serie is any _unique_ combination of tags, measurement and retention policy(contrary to my initial impression, that every written point is a serie).
 
So, logically, this means that, when running a Telegraf agent with the system input plugins, my series number should stay the same, since the tags will never change(as long as a new network interface/cpu isn't added, or something similar)?

But, on the other hand, in the InfluxDB input plugin there is a measurement influxdb_database with fields numSeries, numMeasurements; I have a Grafana dashboard and i have some conflicting results:
The value in numMeasurements stays static(36), but the value in numSeries mounted extremely violently (from 8.52 Million series to 10.07M yesterday, when i did a cleanup and ended up with 5.89 Millions, and now, after a small pic at 6.103M, i have 5.875, due to a retention policy of 1 week).

Here's a pic of the Grafana graph, which uses the following query
```
SELECT mean("numSeries") FROM "influxdb_database" WHERE $timeFilter GROUP BY time($interval), "database" fill(null)
```
http://imgur.com/JA9qTdd

Logically, per InfluxDB's doc, or at least my understanding of it, that shouldn't have happened, since nothing has changed on the servers or Telegraf and the same set of tags and measurements should have been sent, therefore the number of series should have stayed the same. 

Or is the documentation about "unique series", and the InfluxDB metric numSeries about total series(e.g. total points written)? 

In any case, i think an update to the doc to clarify this would be nice.

Thanks in advance.

**Comment by jsternberg** [comment]
Thank you for your interest in InfluxDB. We try to keep the GitHub issue tracker to only contain features or bugs for InfluxDB. Questions should be redirected to the [mailing list](https://groups.google.com/forum/#!forum/influxdb) where you will get a faster response than the issue tracker. If you find anything wrong or that needs clarity in the documentation, you can also file an issue with the [docs](https://github.com/influxdata/docs.influxdata.com). Thanks.
