### ISSUE TITLE
Sample Configuration Still Contains Clustering Section

### ISSUE THREAD

**Issue by gena01** [influxdata/influxdb#6682]
From reading the Changelog for unreleased 1.0.0 it seems that `[cluster]` section should be renamed to something else in influxdb.conf. Currently static nightly seems to still contain `[cluster]` section.

**Comment by jwilder** [comment]
@rossmcdonald Is the config for the static nightly build generated or stored somewhere?

**Comment by rossmcdonald** [comment]
This is because the sample configuration still includes a `[cluster]` block: 

https://github.com/influxdata/influxdb/blob/73076fa0a3a04eb30061b4ee14c9595fe6306aa4/etc/config.sample.toml#L96

I'll update it.
