### ISSUE TITLE
CQ's don't batch points coming into database

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/influxdb#6685]
See https://github.com/influxdata/influxdb/issues/6588 or https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/influxdb/wOq_2bFtThU/xo3dj8hAAwAJ

This behavior causes stress on the database due to unbatched writes. Batching the writes coming in from CQs should solve this issue.

**Comment by jwilder** [comment]
Fixed via #6732
