### ISSUE TITLE
Wrong query results with "WHERE time" filter

### ISSUE THREAD

**Issue by xiic** [influxdata/influxdb#6691]
### Bug report

Different queries, which should return the same data points, return different results:
```
> SELECT * FROM id1_var1 ORDER BY time DESC LIMIT 3
name: id1_var1
--------------
time                            value
2016-05-20T12:04:03.529Z        226.6934
2016-05-20T12:04:03.429Z        226.5565
2016-05-20T12:04:03.013Z        226.5565
```
```
> SELECT * FROM id1_var1 WHERE time > '2016-05-20T09:22:40Z'
name: id1_var1
--------------
time                            value
2016-05-20T09:22:40.328Z        226.8554
2016-05-20T09:22:40.428Z        226.8038
2016-05-20T09:22:40.844Z        226.8038
2016-05-20T09:22:40.944Z        226.7609
2016-05-20T09:22:41.36Z         226.7609
2016-05-20T09:22:41.46Z         226.9117
```

Specifically, when using a "WHERE time" filter, no measurements after `2016-05-20T09:22:41.46Z` are returned - although they're there, as can be seen with the first query.

How can this be? What can I do to investigate further? I could upload the corresponding .tsm file if this would help.

__System info:__
This happens with 0.13 and the current nightly as well:
```
InfluxDB starting, version 0.14.0~n201605200800, branch master, commit 6b1cc645a0fd58839362483153b933c768176923
Go version go1.6.2, GOMAXPROCS set to 2
```
```
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

# free -h
             total       used       free     shared    buffers     cached
Mem:          3.9G       552M       3.3G        21M        21M       176M
```

**Comment by jsternberg** [comment]
At what time did you run the query? If you don't specify a maximum value, it defaults to the current time.

**Comment by xiic** [comment]
At about `2016-05-20T12:05:00Z` - the measurements from the first query where just inserted. Now, 3 hours later, the second query still returns the same result. Even if specifying a max time, nothing changes:

```
SELECT * FROM id1_var1 WHERE time > '2016-05-20T09:22:40Z' AND time < '2016-05-20T12:04:04Z'
name: id1_var1
--------------
time                            value
2016-05-20T09:22:40.328Z        226.8554
2016-05-20T09:22:40.428Z        226.8038
2016-05-20T09:22:40.844Z        226.8038
2016-05-20T09:22:40.944Z        226.7609
2016-05-20T09:22:41.36Z         226.7609
2016-05-20T09:22:41.46Z         226.9117
```

Current system time:
```
$ date
Fri May 20 16:59:13 CEST 2016
$ date -u
Fri May 20 14:59:17 UTC 2016
```

**Comment by jsternberg** [comment]
If you're capable of uploading the data and meta directories, I can try taking a look locally and identify if this is a query engine or storage engine problem. Thanks.

**Comment by xiic** [comment]
After checking the logs again, this happened after upgrading from 0.12.1 to 0.13 (around 2016-05-20T09:22:00Z).

Interestingly, the default retention policy was changed back from 1d to 7d during the upgrade. Which somehow resulted in new data beeing written to an old shard and let to the inconsistent query behaviour. After a new shard was created, everything was working again. I couldn't reproduce the problem with 0.13.0, so this can be closed from my point of view.

For reference, or if you want to investigate what went wrong during the upgrade process, I've uploaded the database file:
[db.tar.xz](
https://mega.nz/#!d1gwHaLY!UK9cuXJLMrzt7YYRaUQ1ljVRjQd9sPIzcWjnOExWik0
)

**Comment by simcap** [comment]
@xiic I had the same issue of new data not being retrievable on 0.13 (single instance) when increasing the retention policy of our db. Your diagnostic of the "new data being written to an old shard" is interesting and seems right. 

When you say "after a new shard was created" everything was working again do you mean all the new data written (even going into the old shard) was queryable again (i.e. no loss of any data) ?

In my case, I reestablished my data thanks to a backup I had. My shards have a size of one day. Not sure if I want to try again to increase my retention policy if data disappear for one day.

**Comment by jsternberg** [comment]
@xiic is there any chance you have the output of `SHOW SHARDS` after the upgrade, but before it started working correctly? I'm curious if somehow the shards had overlapping times as you mentioned and it was choosing the wrong shard to select from after the upgrade.

**Comment by jsternberg** [comment]
I'm able to reproduce it locally so I'm going to take a look and see if I can figure out why before closing this issue. @xiic thanks for the database files.

**Comment by simonsays881** [comment]
also seeing this issue. writes are occurring, but the data is not being retrieved when queried either by via `curl` or the web ui

**Comment by xiic** [comment]
Any progress on this? This happened again after an upgrade from 1.0.0-beta2 to 1.0.0-rc1, although I'm not totally sure if the upgrade has something to do with it or if it was just triggered by the database restart.

The CLI commands should speak for themselves, after dropping the latest shard I was able to retrieve _newer_ datapoints. If needed, I can provide the data files again.

```
> select * from var1 order by time desc limit 3
name: var1
----------
time				value
2016-08-26T08:44:32.898Z	227.0442
2016-08-26T08:44:32.799Z	227.0736
2016-08-26T08:44:32.389Z	227.0736

> show shards
name: crawler_production
------------------------
id	database		retention_policy	shard_group	start_time		end_time		expiry_time		owners
[...]
18	crawler_production	autogen			18		2016-08-25T18:00:00Z	2016-08-26T00:00:00Z	2016-08-28T17:30:46Z	
19	crawler_production	autogen			19		2016-08-26T00:00:00Z	2016-08-26T06:00:00Z	2016-08-28T23:30:46Z	
21	crawler_production	autogen			21		2016-08-26T06:00:00Z	2016-08-26T12:00:00Z	2016-08-29T05:30:46Z	


name: _internal
---------------
id	database	retention_policy	shard_group	start_time		end_time		expiry_time		owners
[...]	
20	_internal	monitor			20		2016-08-26T00:00:00Z	2016-08-27T00:00:00Z	2016-09-03T00:00:00Z	
22	_internal	monitor			22		2016-08-29T00:00:00Z	2016-08-30T00:00:00Z	2016-09-06T00:00:00Z	

> drop shard 21
> select * from var1 order by time desc limit 3
name: var1
----------
time				value
2016-08-26T10:35:17.058Z	226.9631
2016-08-26T10:35:16.641Z	226.9631
2016-08-26T10:35:16.541Z	227.0699
```

**Comment by jsternberg** [comment]
I think this issue has been resolved with some of the newer code. I can't figure out exactly when it was fixed, but the data works correctly when loading it with master.
