### ISSUE TITLE
Wrong regexp ( only with !~ ) result in SHOW TAG VALUES

### ISSUE THREAD

**Issue by caotic112** [influxdata/influxdb#6694]
### Bug report

System info:[InfluxDB 0.13.0, Centos 6.7]

`SHOW TAG VALUES from <measurement_name> WITH KEY = "<key_name>" WHERE <key_name> !~ /<strig_to_exclude>/`

The regexp works only if there are no match at all for the string you are trying to exclude

**Comment by jsternberg** [comment]
Duplicate of #6607.
