### ISSUE TITLE
Creating duplicate database give no error message in body and 200 return code.

### ISSUE THREAD

**Issue by renrutnosaj** [influxdata/influxdb#6699]
### Bug report

__System info:__ 
Influxdb v 0.13.0
uname -a: Linux deb1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

__Steps to reproduce:__

1.curl -v -POST http://localhost:8086/query -u admin:adminpw --data-urlencode "q=CREATE DATABASE mydb"

HTTP/1.1 200 OK, return body is: {"results":[{}]}

2.  curl -v -G http://localhost:8086/query -u admin:adminpw --data-urlencode "q=SHOW DATABASES"
{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["mydb"]]}]}]}

3. curl -v -POST http://localhost:8086/query -u admin:adminpw --data-urlencode "q=CREATE DATABASE mydb"

HTTP/1.1 200 OK, return body is: {"results":[{}]}
 

__Expected behavior:__ 

I would have expected some indication at Step 3 that I'd tried to create a duplicate database. It could be either a return code or body, but we need something to catch this condition.

If there is and I've missed it, my apologies for missing it in the documentation. Any hints about where to look are welcome.

__Actual behavior:__ 

No indication.

**Comment by jsternberg** [comment]
Thank you for the bug report. This is expected behavior as noted in the [documentation](http://docs.influxdata.com/influxdb/v0.13/query_language/database_management/#create-a-database-with-create-database). If there's any confusion in the documentation or how we can improve the ability to find this information, feedback is welcome and encouraged.

**Comment by renrutnosaj** [comment]
Whoops. My mistake. Thanks for your quick and professional reply. 

I'd been using 0.9 which (I believe) treated this as an error, then switched to 0.13 but had my head stuck in the 0.9 documentation. I'll dig deeper into the relevant documentation next time.
