### ISSUE TITLE
memory run out when query in huge series data and no data response

### ISSUE THREAD

**Issue by falfly** [influxdata/influxdb#6703]
Bug report

System info: InfluxDB 0.12 and higer

Steps to reproduce:

1. create database and measurements in influxdb

2. insert huge series in measurements, in my test db, the show stats 
    name: database
    tags: database=registers
    numMeasurements	numSeries
    ---------------          	---------
    1		                       525599

3.run query on measurements
   select count(value) from device_register
4. the test data is generated by the list c code, and copy to influxdb with import command

```c
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
	int i,j,num;
	int total = 0;
	int deviceid, regaddr, value, timev;
	FILE *fp = fopen("test2.txt", "wb");
	fprintf(fp,"# DML\n");
	fprintf(fp,"# CONTEXT-DATABASE: registers\n");

	for(i=0; i < 1000; i++)
	{
		deviceid = i + 1000;
		if(i < 100)
			num = 50;
		else if(i < 200)
			num = 100;
		else if(i < 300)
			num = 500;
		else if(i < 400)
			num = 1000;
		else if(i < 500)
			num = 2000;
		else if(i < 600)
			num = 4000;
		else if(i < 700)
			num = 8000;
		else if(i < 800)
			num = 10000;
		else if(i < 900)
			num = 20000;
		else if(i < 920)
			num = 40000;
		else if(i < 940)
			num = 60000;
		else if(i < 960)
			num = 80000;
		else if(i < 980)
			num = 100000;
		else if(i < 990)
			num = 1000000;
		else if(i < 995)
			num = 2000000;
		else if(i < 998)
			num = 5000000;
		else
			num = 10000000;
		regaddr = i + 2048;		
		for(j = 0; j < num; j++)
		{
            regaddr = j%(2000 - i*2) + 2048;
			value = j%60000;
			timev = 1439856000  + j;
			fprintf(fp, "device_register,deviceid=%d,regaddr=%d value=%d %d\n",deviceid, regaddr,value, timev);
			total++;
			if(total%1000000 == 0)
				printf("total = %d\n", total);			
		}
		printf("=====%d %d %d\n", i, j, total);		
	}
	fclose(fp);
		
}
```

Expected behavior: response the correct number in a reasonable time interval.

Actual behavior: memory runs from 3% to 95% in my PC with 16G memory without any response. And the memory never fall down to 90% in the last several hours with cpu just < 3%.

**Comment by e-dard** [comment]
@falfly can you provide information on exactly which version of influx you're running? We have put in quite a few improvements recently that may help.

**Comment by e-dard** [comment]
@falfly there may be a fix for your issue in the latest nightly build. Could you try that?

**Comment by jwilder** [comment]
@falfly Your test program looks like it's generating about 65M series.  That is a lot of series for a single server and you will need much more RAM than 16GB.  

The script is generating a unique `deviceid` and `regaddr` for each write which is creating very high series cardinality causing a very large in-memory index.

```
device_register,deviceid=1999,regaddr=2049 value=39999 1449855999
```

**Comment by falfly** [comment]
actually, it only generate about 65M records with about 560K series, the number of register in different deviceid are not the same, the range is 2~~1000

**Comment by jwilder** [comment]
@falfly My mistake.  You are correct, there are about 560k series.  I tested your program locally with 0.12, 0.13 and latest master and was not able reproduce the issue you are seeing.  During the query, memory for the process peaked around 2-3GB depending on the version and returned in 12-20s depending on the version.

**Comment by falfly** [comment]
@e-dard , @jwilder , i just tested with the same data against the latest version , and got the same result, block for about 1.5 hour now...

`2016/05/24 09:22:16 Processed 64900000 lines.  Time elapsed: 21m25.0645805s.  Points per second (PPS): 50503
2016/05/24 09:22:18 Processed 65000000 lines.  Time elapsed: 21m26.885760348s.  Points per second (PPS): 50509
2016/05/24 09:22:20 Processed 65100000 lines.  Time elapsed: 21m28.855387646s.  Points per second (PPS): 50509
2016/05/24 09:22:21 Processed 0 commands
2016/05/24 09:22:21 Processed 65165000 inserts
2016/05/24 09:22:21 Failed 0 inserts
root@server-desktop:~# influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.14.0~n201605230800
InfluxDB shell version: 0.14.0~n201605230800
> use registers
Using database registers
> select count(value) from device_register
` 

**top as :**  

top - 10:55:04 up 39 days, 14:37,  6 users,  load average: 12.43, 11.10, 11.38
Tasks: 311 total,   2 running, 309 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.3 us,  1.2 sy,  0.0 ni, 45.1 id, 52.4 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem:  16322612 total, 16020108 used,   302504 free,     1404 buffers
KiB Swap: 16666620 total, 14893588 used,  1773032 free.    92568 cached Mem
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                             
**29646 root      20   0 28.070g 0.014t    344 S   0.3 89.1  17:01.61 influxd**                                                                                                                             
 2198 server    20   0 1595700  37528  15136 D   0.0  0.2  72:10.46 compiz                                                                                                                              
 2194 server    20   0  554124   7900   4264 S   0.0  0.0   1:43.13 unity-panel-ser                                                                                                                     
 3656 root      20   0   33132   4240   4132 S   0.0  0.0   1:23.94 systemd-journal                                                                                                                     
 1831 proxy     20   0  142700   3136    820 D   0.0  0.0   5:35.67 squid3                                                                                                                              
30370 postgres  20   0  295560   3112   2692 D   0.0  0.0   0:00.00 postgres                                                                                                                            
26557 server    20   0  535664   3088   1956 S   0.0  0.0   1:06.87 unity-panel-ser                                                                                                                     
30368 postgres  20   0  295560   3080   2660 D   0.0  0.0   0:00.00 postgres                                                                                                                            
 1648 postgres  20   0  295692   2640   2328 S   0.0  0.0   1:07.76 postgres                                                                                                                            
       

**and the log as** 

[httpd] 2016/05/24 09:22:21 127.0.0.1 - - [24/May/2016:09:22:21 +0800] POST /write?consistency=any&db=registers&precision=s&rp= HTTP/1.1 204 0 - influxDB importer/0.14.0~n201605230800 f68b7e8f-214d-11e6-b2eb-000000000000 93.337368ms
[httpd] 2016/05/24 09:22:21 127.0.0.1 - - [24/May/2016:09:22:21 +0800] POST /write?consistency=any&db=registers&precision=s&rp= HTTP/1.1 204 0 - influxDB importer/0.14.0~n201605230800 f69a1bd7-214d-11e6-b2ec-000000000000 69.791687ms
[httpd] 2016/05/24 09:22:21 127.0.0.1 - - [24/May/2016:09:22:21 +0800] POST /write?consistency=any&db=registers&precision=s&rp= HTTP/1.1 204 0 - influxDB importer/0.14.0~n201605230800 f6a51978-214d-11e6-b2ed-000000000000 57.99492ms
[httpd] 2016/05/24 09:22:21 127.0.0.1 - - [24/May/2016:09:22:21 +0800] POST /write?consistency=any&db=registers&precision=s&rp= HTTP/1.1 204 0 - influxDB importer/0.14.0~n201605230800 f6ae3525-214d-11e6-b2ee-000000000000 70.541002ms
[httpd] 2016/05/24 09:22:21 127.0.0.1 - - [24/May/2016:09:22:21 +0800] POST /write?consistency=any&db=registers&precision=s&rp= HTTP/1.1 204 0 - influxDB importer/0.14.0~n201605230800 f6b903e5-214d-11e6-b2ef-000000000000 75.148µs
[httpd] 2016/05/24 09:22:42 127.0.0.1 - - [24/May/2016:09:22:42 +0800] GET /ping HTTP/1.1 204 0 - InfluxDBShell/0.14.0~n201605230800 02f65b77-214e-11e6-b2f0-000000000000 81.63µs
[query] 2016/05/24 09:22:42 SHOW DIAGNOSTICS FOR registration
[httpd] 2016/05/24 09:22:42 127.0.0.1 - - [24/May/2016:09:22:42 +0800] POST /query?chunked=true&db=&epoch=ns&q=SHOW+DIAGNOSTICS+for+%27registration%27 HTTP/1.1 200 46 - InfluxDBShell/0.14.0~n201605230800 02f66c14-214e-11e6-b2f1-000000000000 654.762µs
[query] 2016/05/24 09:22:59 SHOW DATABASES
[httpd] 2016/05/24 09:22:59 127.0.0.1 - - [24/May/2016:09:22:59 +0800] POST /query?db=&epoch=ns&q=SHOW+DATABASES HTTP/1.1 200 107 - InfluxDBShell/0.14.0~n201605230800 0d71fd34-214e-11e6-b2f2-000000000000 811.268µs
[query] 2016/05/24 09:23:12 SELECT count(value) FROM registers."default".device_register
[monitor] 2016/05/24 09:26:15 failed to store statistics: timeout
[retention] 2016/05/24 09:29:27 retention policy shard deletion check commencing
[retention] 2016/05/24 09:59:29 retention policy shard deletion check commencing
[monitor] 2016/05/24 10:09:02 failed to store statistics: timeout
[monitor] 2016/05/24 10:09:13 failed to store statistics: timeout
[monitor] 2016/05/24 10:10:57 failed to store statistics: timeout
[monitor] 2016/05/24 10:11:13 failed to store statistics: timeout
[monitor] 2016/05/24 10:11:35 failed to store statistics: timeout
[monitor] 2016/05/24 10:11:47 failed to store statistics: timeout
[tsm1] 2016/05/24 10:22:21 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/05/24 10:22:24 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/4/000000003-000000001.tsm (#0)
[tsm1] 2016/05/24 10:22:24 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/4/000000004-000000001.tsm (#1)
[tsm1] 2016/05/24 10:22:32 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/05/24 10:22:32 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/10/000000001-000000001.tsm (#0)
[tsm1] 2016/05/24 10:22:32 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/10/000000002-000000001.tsm (#1)
[tsm1] 2016/05/24 10:23:02 compacted level 1 group (0) into /var/lib/influxdb/data/registers/default/10/000000002-000000002.tsm.tmp (#0)
[tsm1] 2016/05/24 10:23:03 compacted level 1 group (0) into /var/lib/influxdb/data/registers/default/4/000000004-000000002.tsm.tmp (#0)
[tsm1] 2016/05/24 10:23:05 compacted level 1 group 0 of 2 files into 1 files in 45.354490333s
[tsm1] 2016/05/24 10:23:05 compacted level 1 group 0 of 2 files into 1 files in 31.056042115s
[tsm1] 2016/05/24 10:23:08 beginning level 2 compaction of group 0, 2 TSM files
[tsm1] 2016/05/24 10:23:08 compacting level 2 group (0) /var/lib/influxdb/data/registers/default/4/000000002-000000002.tsm (#0)
[tsm1] 2016/05/24 10:23:08 compacting level 2 group (0) /var/lib/influxdb/data/registers/default/4/000000004-000000002.tsm (#1)
[tsm1] 2016/05/24 10:23:09 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/05/24 10:23:09 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/6/000000001-000000001.tsm (#0)
[tsm1] 2016/05/24 10:23:09 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/6/000000002-000000001.tsm (#1)
[tsm1] 2016/05/24 10:23:28 compacted level 1 group (0) into /var/lib/influxdb/data/registers/default/6/000000002-000000002.tsm.tmp (#0)
[tsm1] 2016/05/24 10:23:28 compacted level 1 group 0 of 2 files into 1 files in 18.592979364s
[tsm1] 2016/05/24 10:23:32 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/05/24 10:23:32 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/7/000000001-000000001.tsm (#0)
[tsm1] 2016/05/24 10:23:32 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/7/000000002-000000001.tsm (#1)
[tsm1] 2016/05/24 10:23:37 compacted level 2 group (0) into /var/lib/influxdb/data/registers/default/4/000000004-000000003.tsm.tmp (#0)
[tsm1] 2016/05/24 10:23:37 compacted level 2 group 0 of 2 files into 1 files in 31.893293246s
[tsm1] 2016/05/24 10:23:40 compacted level 1 group (0) into /var/lib/influxdb/data/registers/default/7/000000002-000000002.tsm.tmp (#0)
[tsm1] 2016/05/24 10:23:40 compacted level 1 group 0 of 2 files into 1 files in 10.879204397s
[tsm1] 2016/05/24 10:23:42 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/05/24 10:23:42 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/8/000000001-000000001.tsm (#0)
[tsm1] 2016/05/24 10:23:42 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/8/000000002-000000001.tsm (#1)
[tsm1] 2016/05/24 10:23:47 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/05/24 10:23:47 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/9/000000001-000000001.tsm (#0)
[tsm1] 2016/05/24 10:23:47 compacting level 1 group (0) /var/lib/influxdb/data/registers/default/9/000000002-000000001.tsm (#1)
[tsm1] 2016/05/24 10:23:50 compacted level 1 group (0) into /var/lib/influxdb/data/registers/default/8/000000002-000000002.tsm.tmp (#0)
[tsm1] 2016/05/24 10:23:50 compacted level 1 group 0 of 2 files into 1 files in 7.905555107s
[tsm1] 2016/05/24 10:23:51 compacted level 1 group (0) into /var/lib/influxdb/data/registers/default/9/000000002-000000002.tsm.tmp (#0)
[tsm1] 2016/05/24 10:23:51 compacted level 1 group 0 of 2 files into 1 files in 3.464795852s
[retention] 2016/05/24 10:29:26 retention policy shard deletion check commencing

**Comment by jwilder** [comment]
Can you grab these profiles while the query is running?  Also, what kind of hardware and disks are you using?

```
curl -o heap.txt "http://localhost:8086/debug/pprof/heap?debug=1"
curl -o block.txt "http://localhost:8086/debug/pprof/block?debug=1"
curl -o goroutine.txt "http://localhost:8086/debug/pprof/goroutine?debug=1"
```

**Comment by falfly** [comment]
@jwilder 
**my system info:**
CPU:Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
OS:Linux server-desktop 3.19.0-51-generic #58-Ubuntu SMP Fri Feb 26 21:22:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux Ubuntu 15.04
DISK: WDC WD5000AADS-0 500GB
 
[block11.txt](https://github.com/influxdata/influxdb/files/278890/block11.txt)
[goroutine11.txt](https://github.com/influxdata/influxdb/files/278891/goroutine11.txt)
[heap11.txt](https://github.com/influxdata/influxdb/files/278892/heap11.txt)

**Comment by jwilder** [comment]
@falfly It looks like your disks do not have enough IOPS.  Your `top` output shows `52.4 wa` which indicates your CPU is waiting on disk IO.  

Can you run `iostat -xnz 1` while the query is running?

**Comment by falfly** [comment]
@jwilder , just select need so much IOPS? io capture as attachment
[io.txt](https://github.com/influxdata/influxdb/files/280783/io.txt)
