### ISSUE TITLE
Problem in writing int value as int, and read int as int

### ISSUE THREAD

**Issue by bharath531** [influxdata/influxdb#6709]
Problem in saving the long value to the series.
I am trying to read the long value from the influxdb series
1.	Firstly I am inserting the long value as shown below to the influxdb series:
> insert ErrorEvent1 description="Array index outofbound exception",elementName="com.abs.autologger.metric.logErrorEvent:run(113)",eventName="autologger.png",errorTime=1463759931281475649
The value is inserting as the exponential value into the database, we would like to insert the value as same way to the series.
 
![12](https://cloud.githubusercontent.com/assets/19540646/15486175/57d6c266-2109-11e6-8e84-8d136e639f98.png)

I also tried reading the value from the java program, we are using the influxdb-java-2.1.jar to read the series from the influxdb. 
2.	Here is the API call we are using to read the results from the series.
public Query(final String command, final String database) {
		super();
		this.command = command;
		this.database = database;
	}
public QueryResult query(final Query query);  
// Execute a query agains a database, @return a List of Series which matched the query.
So here it’s returning the value as same exponential value “1.4637599312814756e+18”, could you please suggest us how this influxdb-java jar works in our scenario we want to insert the long value and read the same value without doing the exponential conversion which is influx doing as of now ? Please assist.

**Comment by jsternberg** [comment]
Hello @bharath531,

Questions about how to use InfluxDB should be asked to the [mailing list](https://groups.google.com/forum/#!forum/influxdb) instead of the issue tracker. It is much more likely you will get a helpful response there than here as we primarily use the issue tracker to track feature requests and bug reports.

Thank you.
