### ISSUE TITLE
drop measurement is not persistent

### ISSUE THREAD

**Issue by dalibort** [influxdata/influxdb#6717]
Hi

nightly build version 0.14.0~n201605230800

I have deleted larger amount of measurements via influx client (-execute drop measurement...) and after it I restarted influxdb daemon due to change in conf file. It looks like all the deleted measurements (10000+) appeared again in show measurement :-(

Before restart show measurements result was short (expected state after the drops)
 
I tried to select from the 'revived' measurements and there were only old timestamps so they were not recreated by some agent IMHO. And some of them contained longer series (if they were recreated by some data collector there should be only one data in serie or so)

> select last(value) from "internet.asr2.snetwork.AS9934.inbytes"
name: internet.asr2.snetwork.AS9934.inbytes
-------------------------------------------
time                    last
2016-05-22T21:08:01Z    574800

> select last(value) from "internet.asr2.snetwork.AS5610.inbytes"
name: internet.asr2.snetwork.AS5610.inbytes
-------------------------------------------
time                    last
2016-05-23T07:23:01Z    426000

**Comment by beckettsean** [comment]
What do the logs show around the restart? Perhaps the DROP queries hadn't completed before the restart?

**Comment by beckettsean** [comment]
As an aside, 10000+ measurements with graphite-style measurement names is definitely an anti-pattern for InfluxDB 0.9+. Metadata should be encoded into key-value tags and measurements should be in the dozens or hundreds.

**Comment by dalibort** [comment]
>What do the logs show around the restart? 
I am not sure what to search in the logs for...

[query] 2016/05/24 18:07:15 DROP MEASUREMENT "internet.asr2.snetwork.AS9934.inbytes"
[httpd] 2016/05/24 18:07:17 ::1 - - [24/May/2016:18:07:15 +0200] POST /query?chunked=true&db=graphite&epoch=ns&q=DROP+MEASUREMENT+%22internet.asr2.snetwork.AS9934.inbytes%22 HTTP/1
[httpd] 2016/05/24 18:07:17 ::1 - - [24/May/2016:18:07:17 +0200] GET /ping HTTP/1.1 204 0 - InfluxDBShell/0.14.0~n201605230800 96661ab7-21c9-11e6-926f-000000000000 66.65µs
[query] 2016/05/24 18:07:17 DROP MEASUREMENT "internet.asr2.snetwork.AS9943.inbytes"
[httpd] 2016/05/24 18:07:22 ::1 - - [24/May/2016:18:07:17 +0200] POST /query?chunked=true&db=graphite&epoch=ns&q=DROP+MEASUREMENT+%22internet.asr2.snetwork.AS9943.inbytes%22 HTTP/1
[httpd] 2016/05/24 18:07:22 ::1 - - [24/May/2016:18:07:22 +0200] GET /ping HTTP/1.1 204 0 - InfluxDBShell/0.14.0~n201605230800 993b39ec-21c9-11e6-9271-000000000000 75.302µs

there are lines mentioning compacting on levels 1,2,3


[run] 2016/05/24 21:00:32 Signal received, initializing clean shutdown...
[run] 2016/05/24 21:00:32 Waiting for clean shutdown...
[run] 2016/05/24 21:00:32 second signal received, initializing hard shutdown
[run] 2016/05/24 21:00:33 InfluxDB starting, version 0.14.0~n201605230800, branch master, commit 39657cd09ffacadea2b880e824e39c7c6cbe3850

>Perhaps the DROP queries hadn't completed before the restart?

maybe. How can I know it from the log?

>10000+ measurements with graphite-style measurement names is definitely 
>an anti-pattern for InfluxDB 0.9+.

measurements were not created intentionally but due to a mistake in graphite template definition.

**Comment by dalibort** [comment]
It seems that the problem with frozen influx CLI ([#6715](https://github.com/influxdata/influxdb/issues/6715)) can be related to the problem with DROP MEASUREMENT. 

When the influx CLI (I am using to drop measurement) hangs and I kill it by kill -9 something wrong happens in influxdb server probably. When I restart it the dropped measurements are back again.
If I send some drop measurements via influx CLI (and it doesn't hang ) then restarting influxdb server doesn't cause that dropped measurements appear again.

**Comment by dalibort** [comment]
I dropped about 30000 measurements (and there was no problem with influx cli) and then issued systemctl restart influxdb. It shut down near immediately and after it started all the dropped measurements are back.

The log file shows this:

[run] 2016/05/26 06:48:17 Signal received, initializing clean shutdown...
[run] 2016/05/26 06:48:17 Waiting for clean shutdown...
[run] 2016/05/26 06:48:17 second signal received, initializing hard shutdown
[run] 2016/05/26 06:48:17 InfluxDB starting, version 0.14.0~n201605230800, branch master, commit 39657cd09ffacadea2b880e824e39c7c6cbe3850
[run] 2016/05/26 06:48:17 Go version go1.6.2, GOMAXPROCS set to 4

it looks like the 'normal' shutdown is longer and shows no 'econd signal received, initializong hard shutdown' line:

[run] 2016/05/25 21:10:26 Signal received, initializing clean shutdown...
[run] 2016/05/25 21:10:26 Waiting for clean shutdown...
[monitor] 2016/05/25 21:10:26 shutting down monitor system
[monitor] 2016/05/25 21:10:26 terminating storage of statistics
[shard-precreation] 2016/05/25 21:10:26 Precreation service terminating
[snapshot] 2016/05/25 21:10:26 snapshot listener closed
[tsm1] 2016/05/25 21:10:38 compacted full group (0) into /var/lib/influxdb/data/graphite/default/15/000000713-000000008.tsm.tmp (#0)
[tsm1] 2016/05/25 21:10:38 compacted full group (0) into /var/lib/influxdb/data/graphite/default/15/000000713-000000009.tsm.tmp (#1)
[tsm1] 2016/05/25 21:10:38 compacted full 2 files into 2 files in 1m50.496293764s
[continuous_querier] 2016/05/25 21:10:52 continuous query service terminating
[retention] 2016/05/25 21:10:52 retention policy enforcement terminating
[graphite] 2016/05/25 21:10:52 graphite TCP listener closed
[collectd] 2016/05/25 21:10:52 collectd ReadFromUDP error: read udp [::]:25826: use of closed network connection
[collectd] 2016/05/25 21:10:52 collectd UDP closed
[run] 2016/05/25 21:10:56 time limit reached, initializing hard shutdown
[run] 2016/05/25 21:10:56 InfluxDB starting, version 0.14.0~n201605230800, branch master, commit 39657cd09ffacadea2b880e824e39c7c6cbe3850
[run] 2016/05/25 21:10:56 Go version go1.6.2, GOMAXPROCS set to 4

**Comment by beckettsean** [comment]
@dalibort the CLI is not connected to the status of the database. All it does is submit the queries. It's just a wrapper around `curl` with some syntactic sugar.

It's my understanding that `DROP MEASUREMENT` can take some time to complete, so if you issued 30000 `DROP MEASUREMENT` commands each might take multiple seconds to complete, depending on how many points are in the measurement. Even at 1 second each and with let's say 16 running in parallel (one per core, assuming a beefy box) that's still going to take half an hour to finish.

Queries do not persist on a restart, so when you restart the system the pending `DROP MEASUREMENT` queries disappear and the data remains.

Please give the system time for the queries to complete before the restart. Let me restate again that the status of the CLI has no bearing on the status of the database. To know if the queries are still running, use the query status queries: https://docs.influxdata.com/influxdb/v0.13/troubleshooting/query_management/#list-currently-running-queries-with-show-queries.

I think there's no actual bug here, just aggressive restarts killing pending queries.
