### ISSUE TITLE
rfc3339 date limit for time bound queries

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#6740]
Summary: Time bound queries with rfc3339 are limited to 2050-01-01T00:00:01Z

Tested with both 0.13 and 0.14.0 head 1d467ab2e3c540c7749a352244cbc752dca1701f

```
> create database test
> use test
Using database test
> insert ametric,region=1 year=2049 2524607999000000000
> precision rfc3339
> select * from ametric where time <= '2050-01-01T00:00:00Z'
name: ametric
-------------
time			region	year
2049-12-31T23:59:59Z	1	2049

> select * from ametric where time <= '2050-01-01T00:00:01Z'
ERR: time 2050-01-01T00:00:01Z overflows time literal

> precision ns
> select * from ametric where time <= 2524608000000000001
name: ametric
-------------
time			region	year
2524607999000000000	1	2049
```

The limit seems to be hardcoded int64(2524608000000000000)
https://github.com/influxdata/influxdb/blob/master/influxql/iterator.go

Querying with RFC3339 should support the same time range boundaries as ns precision.

**Comment by jsternberg** [comment]
The current maximum timestamp was changed to `2262-04-11 23:47:16.854775806 +0000 UTC` at some point so I'm going to close this.
