### ISSUE TITLE
db unable to write since the UTC day starts

### ISSUE THREAD

**Issue by boyxuper** [influxdata/influxdb#6747]
### Bug report

__System info:  [InfluxDB 0.12.2, CentOS 5.11]__

__Steps to reproduce:__

1. installed a lot of telegraf agent 0.13.0
2. installed influxdb 0.12.2

__Actual behavior:__ 
0. following starts at the UTC day start: 2016-05-30T00:00:00Z
1. used memory increased rapidly
2. one on my DBs unable to write
3. NumGoroutine increased rapidly: 144/min 

__Additional info:__ 
1. CREATE RETENTION POLICY "one_month" ON "\_db_name_" DURATION 30d REPLICATION 1 SHARD DURATION 1d DEFAULT

**Comment by thetcc** [comment]
Haha! You must be a Chinese guy，me too!
#6630  It seems somewhat similar.

**Comment by boyxuper** [comment]
Maybe, but I found that the exception always start at the UTC day start.

Here's some log from telegraf:

> 2016/05/30 09:38:10 Gathered metrics, (10s interval), from 9 inputs in 62.396ms
> 2016/05/30 09:38:10 Output [influxdb] buffer fullness: 1053 / 1000 metrics. Total gathered metrics: 4328289. Total dropped metrics: 413206.
> 2016/05/30 09:38:15 ERROR: Post http://\_server_:8086/write?consistency=&db=\_db_name_&precision=s&rp=one_month: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> 2016/05/30 09:38:15 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster

I'll provide the heap dump & profile when the exception occurs again.

**Comment by boyxuper** [comment]
heap dump & profile attached:

[goroutine.txt](https://github.com/influxdata/influxdb/files/290214/goroutine.txt)
[heap.txt](https://github.com/influxdata/influxdb/files/290216/heap.txt)

**Comment by e-dard** [comment]
@boyxuper thanks for the report. 

Could you provide a blocking profile too? 

`curl -o block.txt "http://_server_:8086/debug/pprof/block?debug=1"`

Also, have you tried upgrading to `0.13`? Some locking issues I think were fixed in that version

**Comment by boyxuper** [comment]
I’ll provide `blocking profile` on next UTC day start. 
I‘m not sure about 0.13 because lots of issues opened since people upgrade to 0.13. 
But I think maybe I can help more by upgrading to 0.13, so I think I'll plan to do the upgrade soon.

**Comment by boyxuper** [comment]
[tbz2.txt](https://github.com/influxdata/influxdb/files/294693/tbz2.txt)

goroutine / heap dump / block profile

I've re-dumped the profiles. it's a compressed tbz2 file because original file was too big.

**Comment by junyhu** [comment]
@boyxuper we are facing the similar issue with influxdb v0.12. Have you upgraded to v0.13? We are planning an upgrade but not sure whether it will resolve this issue or not...and we don't want export more new issues as ppl were reporting a lot of issues they observed with v0.13...

**Comment by boyxuper** [comment]
We just upgraded to 1.0.0-beta2 3 days ago, problem solved and memory consumption is greatly reduced. I'm closing this.
