### ISSUE TITLE
0.13 not closing connections, resulting in OOM after certain time

### ISSUE THREAD

**Issue by antst** [influxdata/influxdb#6748]
RHEL6.6, Influxdb 0.13

Summary: clients close connections, but they remain open on server, which results in memory grows and OOM kill.

Home-grown collection tool send reports from few thousands of clients every minute by libcurl with the next code:

```
      headers = curl_slist_append(headers, "Content-Type: text/plain");
      headers = curl_slist_append(headers, "Connection: close");
      curl = curl_easy_init();
      curl_easy_setopt(curl, CURLOPT_URL, url);
      curl_easy_setopt(curl, CURLOPT_POST, 1);
      curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10);
      curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
      curl_easy_setopt(curl, CURLOPT_FORBID_REUSE, 1);
      curl_easy_setopt(curl, CURLOPT_POSTFIELDS, repdata);
      curl_easy_perform(curl);
      curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
      curl_easy_cleanup(curl);
```

After start of influxdb, memory starts to grow and finally results in OOM kill (I limit address space for the process with 200GB).

After investigation I found that influxdb has quite a number of open sockets in CLOSE_WAIT state, while there are no open sockets on the clients. And this number of open sockets grows, although I never exhausted my default 65535 limit, as memory get exhausted first, But I've seen 40K of open sockets.

If I limit maxfile for the process at certain value (5K), then memory grows stops (around 40GB). But, obviously, I often can't even get dashboards in grafana rendered, as there are no available files/sockets anymore.

Is there anything special which has to be done to make sure that server closes connections/sockets?

**Comment by thetcc** [comment]
I remember the server socket connection is no limit, in other words, the server port 8086 can receive connections is not limited, if you set ulimit -n unlimited and  system have enough resources(memory and cpu).

**Comment by antst** [comment]
But this is a problem, there is no need to have unlimited. One client has only or zero connections at the time. It is server just not closing them and exhausting memory because of that.

Anyway, I check with nightly build, and issue seems to be resolved there.
Although, there is still uncontrollable memory grows which results in OOM kill.

**Comment by rmihael** [comment]
We are also experiencing problem of unbounded memory growth. Our use case is write intensive with rare queries. Write intensity is 50-100 points per second through UDP and total number of series is ~150K.
Memory just grow indefinitely until OOM killer comes for reaping.

**Comment by antst** [comment]
In our case, we have a bit less than 100K points per minute, and cardinality is only about 400.
I tried to play with everything, snapshots sizes, cold write timeout etc, no help.

**Comment by e-dard** [comment]
@antst thanks for the report.

I'm not familiar with `libcurl`, so have a couple of questions:

(1) is your client closing its connection after every write? 
(2) if not, then is it supposed to be using a connection pool?

Looking at the amount of data being sent you would probably benefit from a connection pool, but given the number of sockets a connection pool probably isn't being used here.

Do the outstanding `CLOSE_WAIT` sockets change to `CLOSED` given time?

**Comment by jwilder** [comment]
Please upgrade to 1.1 and let us know if this is still occurring.
