### ISSUE TITLE
continuous query RESAMPLE every second results in more than one point of one second

### ISSUE THREAD

**Issue by wqtty** [influxdata/influxdb#6749]
Hi there,
I have a measurement that records call count of my interfaces, the points is sent to influxdb in batch and each call would generate a point. So there could be many points within a second.
Now I wrote a CQ to downsample the data, i.e. sum(count) group by 1s, but it turns out that the down sampled data has more than one point per second( may be 1 or 2). I tried to make the CQ run every 2s or 5 second, the problem is still there.
How can I get only one sum from my original data?
Hope I have explained it clear enough.

**Comment by wqtty** [comment]
Here is my CQ:
show continuous queries
name: _internal
---------------
name	query


name: monitor
-------------
name			query
callCounterDownsample	CREATE CONTINUOUS QUERY callCounterDownsample ON monitor RESAMPLE EVERY 5s BEGIN SELECT sum(count) AS count INTO monitor."default".callCounter_1s FROM monitor."default".callCounter GROUP BY time(1s), module, ip, method END

**Comment by dgnorton** [comment]
@wqtty is this still an issue?

**Comment by russorat** [comment]
closing due to lack of response.
