### ISSUE TITLE
Canceling running query computation by killing HTTP connection?

### ISSUE THREAD

**Issue by m1keil** [influxdata/influxdb#675]
Hi,
I've noticed that if I commit a query to InfluxDB with curl, killing curl process will not kill the query computation on InfluxDB. 

Is it possible to add as a feature the option Influx will follow socket state and stop query in case it went from Established to Close_Wait?

**Comment by jwilder** [comment]
@jsternberg Will #5950 resolve this?

**Comment by jsternberg** [comment]
Yes. In the PR I made, I also fixed a bug where a closed HTTP connection didn't close the interrupt channel correctly.

**Comment by jsternberg** [comment]
The fix for this was merged as part of #5950.
