### ISSUE TITLE
No data written to db

### ISSUE THREAD

**Issue by eppak** [influxdata/influxdb#6750]
Hello,
i have a influx 0.13 installed from deb package on a debian 8.4 64bit os. I put data via curl but and i get a 204 response but i see nothing in the db.

REQUEST:
curl i -XPOST 'http://localhost:8086/write?db=devices' --data-binary 'log,uuid=1234567890,session=56,type=log V1=0.48,V2=0.59,V3=0.68,V4=0.77,V5=0.84,V6=0.9,V7=0.95,V8=0.98,V9=1,V10=1,V11=0.98,V12=0.95,V13=0.9,V14=0.84,V15=0.77,V16=0.68,V17=0.59,V18=0.48,V19=0.37,V20=0.25,V21=0.13,V22=0,V23=-0.13,V24=-0.25,V25=-0.37,V26=-0.48,V27=-0.59,V28=-0.68,V29=-0.77,V30=-0.84,V31=-0.9,V32=-0.95,V33=-0.98,V34=-1,V35=-1 1464623077000000000'

RESPONSE:
HTTP/1.1 204 No Content
Request-Id: 7a63b808-266d-11e6-8622-000000000000
X-Influxdb-Version: 0.13.0
Date: Mon, 30 May 2016 13:50:32 GMT

I think is something with the timestamp: i have a epoch in seconds, i multiply it with 10^9 to get the nano timestamp. I tried with 10^6 and it write, but i get a 1970 timestamp.
Something wrong with the request of with the db?

Thanks

**Comment by e-dard** [comment]
@eppak The timestamp looks fine, but based on the `Date` header, the point you wrote in the request was in the future (`2016-05-30 15:44:37 +0000 UTC`). 

By default InfluxDB only shows data up to [now](https://docs.influxdata.com/influxdb/v0.13/query_language/data_exploration/#time-syntax-in-queries).

Could you provide the queries you issues after you inserted the point?

**Comment by eppak** [comment]
Hello,
so the point was inserted but not displayed? After that i tried to extract data with a simple "select * from log".

Thanks

**Comment by e-dard** [comment]
@eppak Now that we're a few days ahead `select * from log` should work. At the time of the insertion, however, you should have been able to select the point with something like:

```
SELECT * FROM log WHERE time < now() + 1d
```

Can you confirm that's working for you and I'll close out the issue.

**Comment by eppak** [comment]
Yes, is working thanks!
