### ISSUE TITLE
[0.14 nightly] Uncontrollable memory use resulting in OOM kill

### ISSUE THREAD

**Issue by antst** [influxdata/influxdb#6752]
RHEL6, nightly build (0.14.0~n201605250800)

Memory use by influxd grows infinitely resulting in OOM kill even on 256GB host.
We have home-grown collectors which send data with libcurl. On average we send a bit less than 100K metrics to the server per minute, cardinality of database is 8189.

Non-default settings are
cache-snapshot-memory-size = 3276800
cache-snapshot-write-cold-duration = "5m0s"

this is what I see in pprof:

```
(pprof) tree
76967.34MB of 77463.53MB total (99.36%)
Dropped 759 nodes (cum <= 387.32MB)
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context
----------------------------------------------------------+-------------
                                        76940.12MB   100% |   github.com/influxdata/influxdb/tsdb/engine/tsm1.(*WAL).writeToLog
76940.11MB 99.32% 99.32% 76940.12MB 99.32%                | github.com/influxdata/influxdb/tsdb/engine/tsm1.getBuf
----------------------------------------------------------+-------------
                                        76988.10MB   100% |   github.com/influxdata/influxdb/tsdb.(*Shard).WritePoints
   27.10MB 0.035% 99.36% 76988.10MB 99.39%                | github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).WritePoints
                                        76940.47MB   100% |   github.com/influxdata/influxdb/tsdb/engine/tsm1.(*WAL).WritePoints
----------------------------------------------------------+-------------
                                        76940.47MB   100% |   github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).WritePoints
    0.13MB 0.00016% 99.36% 76940.47MB 99.32%                | github.com/influxdata/influxdb/tsdb/engine/tsm1.(*WAL).WritePoints
                                        76940.34MB   100% |   github.com/influxdata/influxdb/tsdb/engine/tsm1.(*WAL).writeToLog
----------------------------------------------------------+-------------
                                        77002.24MB   100% |   runtime.goexit
         0     0% 99.36% 77002.24MB 99.40%                | github.com/influxdata/influxdb/coordinator.(*PointsWriter).WritePoints.func1
                                        77002.24MB   100% |   github.com/influxdata/influxdb/coordinator.(*PointsWriter).writeToShard
----------------------------------------------------------+-------------
                                        77002.24MB   100% |   github.com/influxdata/influxdb/coordinator.(*PointsWriter).WritePoints.func1
         0     0% 99.36% 77002.24MB 99.40%                | github.com/influxdata/influxdb/coordinator.(*PointsWriter).writeToShard
                                        77002.24MB   100% |   github.com/influxdata/influxdb/tsdb.(*Store).WriteToShard
----------------------------------------------------------+-------------
```

**Comment by antst** [comment]
Just in case,

My collectors are sending lines like this:
`metrics_name,host=XXXXX,block=YYYY read_4k=0,read_8k=0,read_16k=0,read_32k=0,read_64k=0,read_128k=0,read_256k=0,read_512k=0,read_1024k=0,write_4k=0,write_8k=0,write_16k=0,write_32k=0,write_64k=0,write_128k=0,write_256k=0,write_512k=0,write_1024k=0 1464682132`

only host and block differs.I tried to keep nonzero fields and tried to omit nonzero fields (report only fields where nonzero numbers), it doesn't make any difference.

**Comment by antst** [comment]
I found the reason of the issue, but it is strange.
If I keep wal directory on md raid0 (6 disks)+ext4 - it can not coop with data (at the same time I see really low iostat and there aren't many read/write calls to walls and they are sequential) and memory jumps through the roof (256GB)

when I move wal directory to /dev/shm - it flies and my memory stays withing 600MB. 

I tried iozone on disk - can deliver why higher IO than influxdb uses when running on /dev/shm

**Comment by jwilder** [comment]
@antst Can you run `iostat -xzd 1` under write load and while memory is increasing?

**Comment by jwilder** [comment]
This is due to slow disks that cause writes to queue up in the WAL while holding larger allocations.  #6752 should fix this when merged.
