### ISSUE TITLE
404 Error on http://localhost:8086/query with version 0.13

### ISSUE THREAD

**Issue by poblabs** [influxdata/influxdb#6755]
### Bug report

__System info:__ InfluxDB 0.13, CentOS 6.8

__Steps to reproduce:__

1. Just trying to do a simple `curl -get` and am getting a 404. Here's the curl I'm trying: `curl -GET 'http://localhost:8086/query' --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM points"`
2. This same query works fine on the web admin webpage. 

__Expected behavior:__ JSON output from mydb showing all data points

__Actual behavior:__ 404 page not found

Further; http://localhost:8086/ping works fine. 

    [root@local ~]# curl http://localhost:8086/ping
    {"status":"ok"}

**Comment by zstyblik** [comment]
@poblabs, I would say the problem is in parameters you gave to curl rather than in InfluxDB. Try `-G` instead of `-GET`. Also, I recommend to add `-vvv` and observe what is being sent and received.

**Comment by zstyblik** [comment]
@poblabs , `curl -vvv -G http://xxx:8086/query --data-urlencode "db=xxx" --data-urlencode "q=SHOW MEASUREMENTS"` works for me.

**Comment by poblabs** [comment]
Thanks @zstyblik, here's the output from the latest test. Still 404

    [root@local html]# curl -G 'http://localhost:8086/query' --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM points" -vvvv
    * About to connect() to localhost port 8086 (#0)
    *   Trying ::1... connected
    * Connected to localhost (::1) port 8086 (#0)
    > GET /query?db=mydb&q=SELECT%20%2A%20FROM%20points HTTP/1.1
    > User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
    > Host: localhost:8086
    > Accept: */*
    >
    < HTTP/1.1 404 Not Found
    < Content-Type: text/plain; charset=utf-8
    < Date: Tue, 31 May 2016 13:30:46 GMT
    < Content-Length: 19
    <
    404 page not found
    * Connection #0 to host localhost left intact
    * Closing connection #0


And your other query:

    [root@local html]# curl -vvv -G http://localhost:8086/query --data-urlencode "db=mydb" --data-urlencode "q=SHOW MEASUREMENTS"
    * About to connect() to localhost port 8086 (#0)
    *   Trying ::1... connected
    * Connected to localhost (::1) port 8086 (#0)
    > GET /query?db=mydb&q=SHOW%20MEASUREMENTS HTTP/1.1
    > User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
    > Host: localhost:8086
    > Accept: */*
    >
    < HTTP/1.1 404 Not Found
    < Content-Type: text/plain; charset=utf-8
    < Date: Tue, 31 May 2016 13:32:55 GMT
    < Content-Length: 19
    <
    404 page not found
    * Connection #0 to host localhost left intact
    * Closing connection #0

**Comment by zstyblik** [comment]
@poblabs, are you sure you're talking to InfluxDB?

```
< HTTP/1.1 200 OK
< Connection: close
< Content-Type: application/json
< Request-Id: e414e623-2733-11e6-8492-000000000000
< X-Influxdb-Version: 0.13.0
< Date: Tue, 31 May 2016 13:30:50 GMT
< Content-Length: 632
```

Notice `X-Influxdb-Version` header in the reply I've received. Although, may be this header isn't included in non-200 replies.

Umm is there anything in the logs? Does `mydb` exist? Umm ... isn't authentication enabled? If so, do you have ACLs to access that DB(although, I would expect 403 in such case)? ...

**Comment by poblabs** [comment]
I'm fairly confident I'm talking to InfluxDB based on the ping status:

    [root@local ~]# curl http://localhost:8086/ping
    {"status":"ok"}

mydb does exist, the query works fine from the admin website on port `8083`. 

ACL was something I was wondering about, but when I add the `-u user:pass` into the command or even the `--data-urlencode "u=user" --data-urlencode "p=pass"` as per the documentation, I get the same 404.

**Comment by poblabs** [comment]
Trying it via the CLI seems to fail too. 

(Of course, I'm substitiuting my credentials for the general "username, password" below)

    [root@energy html]# influx -username username -password password
    Failed to check token: json: cannot unmarshal number into Go value of type struct { Results []client.Result "json:\"results,omitempty\""; Err string "json:\"error,omitempty\"" }

**Comment by zstyblik** [comment]
:\ Is there anything interesting in InfluxDB logs?

**Comment by e-dard** [comment]
@poblabs I can't reproduce this behaviour with influxd `0.13`. Are you _sure_ you're using the `0.13` version of influx? When you boot the server the first line of logs should tell you version, commit etc.

**Comment by mark-rushakoff** [comment]
@poblabs 

> I'm fairly confident I'm talking to InfluxDB based on the ping status:

>     [root@local ~]# curl http://localhost:8086/ping
>     {"status":"ok"}

That's not InfluxDB. Current `master`, and as far back as I can remember, always returned a 204 (No Content) without a body.

```
$ curl  -vvv http://localhost:8086/ping
*   Trying ::1...
* Connected to localhost (::1) port 8086 (#0)
> GET /ping HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 204 No Content
< Request-Id: 50543231-2749-11e6-8002-000000000000
< X-Influxdb-Version: unknown
< Date: Tue, 31 May 2016 16:04:11 GMT
<
* Connection #0 to host localhost left intact
```

**Comment by poblabs** [comment]
@e-dard Well, now I'm not sure I'm using `0.13`, even though it's installed.

Let me catch things up.

I had `0.8` installed via RPM. I installed it so long ago I assumed it was from EPEL or something. Realizing I was many version behind, I decided to download the latest and greatest. 

I'm using CentOS, so I tried `yum update influxdb`. Of course, no new packages found. No problem, follow the InfluxDB download documentation!

    wget https://dl.influxdata.com/influxdb/releases/influxdb-0.13.0.x86_64.rpm
    sudo yum localinstall influxdb-0.13.0.x86_64.rpm

Install went without a hitch. Using it is another problem. 

As to @mark-rushakoff saying Ping isn't valid - I disagree. It *was* valid. 

    [root@local ~]# curl -G http://localhost:8086/ping -vvv
    * About to connect() to localhost port 8086 (#0)
    *   Trying ::1... connected
    * Connected to localhost (::1) port 8086 (#0)
    > GET /ping HTTP/1.1
    > User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
    > Host: localhost:8086
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
    < Access-Control-Allow-Methods: GET, POST, PUT, DELETE
    < Access-Control-Allow-Origin: *
    < Access-Control-Max-Age: 2592000
    < X-Influxdb-Version: InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)
    < Date: Tue, 31 May 2016 16:26:25 GMT
    < Content-Length: 15
    < Content-Type: text/plain; charset=utf-8
    <
    * Connection #0 to host localhost left intact
    * Closing connection #0
    {"status":"ok"}

What's interesting here is the header that confirms it's InfluxDB answering and also gives the version. `X-Influxdb-Version: InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)`

Hmm... `0.8.8`, eh? I thought I removed you. 

    [root@local ~]# rpm -qa | grep influxdb
    influxdb-0.13.0-1.x86_64


So.... bad upgrade from RPM?

**Comment by poblabs** [comment]
More details. Yes, I've restarted the service a few times. CLI shows 0.13, but doesn't work, and API shows 0.8.8

    [root@local ~]# service influxdb restart
    Starting the process influxdb [ OK ]
    influxdb process was started [ OK ]
    
    [root@local ~]# curl -G http://localhost:8086/ping -vvv
    * About to connect() to localhost port 8086 (#0)
    *   Trying ::1... connected
    * Connected to localhost (::1) port 8086 (#0)
    > GET /ping HTTP/1.1
    > User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
    > Host: localhost:8086
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
    < Access-Control-Allow-Methods: GET, POST, PUT, DELETE
    < Access-Control-Allow-Origin: *
    < Access-Control-Max-Age: 2592000
    < X-Influxdb-Version: InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)
    < Date: Tue, 31 May 2016 16:38:07 GMT
    < Content-Length: 15
    < Content-Type: text/plain; charset=utf-8
    <
    * Connection #0 to host localhost left intact
    * Closing connection #0
    {"status":"ok"}

    [root@local ~]# influx -version
    InfluxDB shell version: 0.13.0

    [root@local ~]# influx -username myusername -password mypassword
    Failed to check token: json: cannot unmarshal number into Go value of type struct { Results []client.Result "json:\"results,omitempty\""; Err string "json:\"error,omitempty\"" }

**Comment by zstyblik** [comment]
@poblabs, `ps faux | grep influx` and find the PID, `kill <InfluxDB_PID>`. If, **if**, signals are handled properly in InfluxDB, then it should shut down gracefully. It's possible that init script didn't do its job.

**Comment by poblabs** [comment]
@zstyblik Ok, we're onto something. I killed the pid, and did `service influxdb start` but still having some errors. 

`ps faux | grep influx` doesn't show any process running and some tests below:

    [root@local ~]# % influxd -version
    bash: fg: %: no such job
    
    [root@local ~]# influx -username username -password password database mydb
    Failed to connect to http://localhost:8086
    Please check your connection settings and ensure 'influxd' is running.

Also, `/opt/influxdb/shared/log.txt` doesn't show anything since I killed the pid.

**Comment by rossmcdonald** [comment]
@poblabs I think part of the issue here is that there is no direct upgrade path from InfluxDB v0.8 to v0.13. The entire project was nearly rewritten with InfluxDB v0.9, so upgrading is not straightforward. If you have data in 0.8 that you would like to keep, then there is a small writeup [here](https://github.com/influxdata/influxdb/blob/master/importer/README.md) that covers how you can export your data, but you will also have to upgrade to each minor version after 0.8 (0.9 to 0.10 to ...).

Also the filesystem hierarchy was changed with 0.9.5 (changelog [here](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#v095-2015-11-20)), so for logs you will need to look in `/var/log/influxdb`, configuration is located at `/etc/influxdb/influxdb.conf`, and your data goes into `/var/lib/influxdb` (we no longer use `/opt/influxdb` for anything).

Is there anything in `/var/log/influxdb/`? Also can you run:

```
influxd version
```

Without the `%`?

**Comment by poblabs** [comment]
@rossmcdonald I suppose that's what happens when I install something, then kinda drift away from the project - I miss all the little things like this. 

Thanks for the updated log location, some good info there on how to proceed. 

    [run] 2016/05/31 14:48:24 InfluxDB starting, version 0.13.0, branch 0.13, commit e57fb88a051ee40fd9277094345fbd47bb4783ce
    [run] 2016/05/31 14:48:24 Go version go1.6.2, GOMAXPROCS set to 2
    [run] 2016/05/31 14:48:24 Using configuration at: /etc/influxdb/influxdb.conf
    run: create server: detected /var/lib/influxdb/meta/raft.db. To proceed, you'll need to either 1) downgrade to v0.11.x, export your metadata, upgrade to the current version again, and then import the metadata or 2) delete the file, which will effectively reset your database. For more assistance with the upgrade, see: https://docs.influxdata.com/influxdb/v0.12/administration/upgrading/


Running `influxd version` returns:

    [root@local ~]# influxd version
    InfluxDB v0.13.0 (git: 0.13 e57fb88a051ee40fd9277094345fbd47bb4783ce)

I suppose I have some deep reading to do tonight on how to step my way up to current.

**Comment by rossmcdonald** [comment]
@poblabs InfluxDB has historically had a very fast release cycle, so it's definitely tough to keep up with all of the changes. 

Did you install another version of InfluxDB before 0.13? I'm surprised that you received the `detected /var/lib/influxdb/meta/raft.db` error if not.

And for more information regarding the upgrade paths, I'd recommend installing InfluxDB 0.9.6, and then going through each of these:

- https://docs.influxdata.com/influxdb/v0.10/administration/upgrading/
- https://docs.influxdata.com/influxdb/v0.13/administration/upgrading/

The largest hurdle is importing the data into 0.9 from 0.8, and then converting the shards for the 0.9 to 0.10 upgrade. Everything else should only take a few minutes.

**Comment by zstyblik** [comment]
@poblabs, I'm sorry for not being consistent with my shell commands annotations :(

**Comment by poblabs** [comment]
@rossmcdonald Ok I won't feel too bad then. Yes, I downgraded to `0.9` briefly thinking that would fix it, but it didn't so I rolled back to `0.13`. I've been all over the map today. More reading to do tonight to clean it all up. Appreciate the help

@zstyblik It's no problem! I was lost, so any help was worthwhile!

**Comment by poblabs** [comment]
I'm stepping my way through the installs now. I did the export from `0.8.8` to `0.8.9`, then export and import to `0.9.5` and so far so good. In the interest of disk space, will the old 0.8.8 shards purge themselves or is there something else I need to do?

**Comment by rossmcdonald** [comment]
@poblabs Once the import is completed into `0.9.5`, then the `0.8.9` shards (the ones located in `/opt/influxdb/shared/data`) can be discarded. They will not purge themselves, though, so you will need to either manually remove them or push them to a secondary location to save on space. I'd recommend backing them up for the time being, until you have completed the upgrade path and verified the data is complete.

**Comment by poblabs** [comment]
Thanks everyone for your help. Felt a bit lost there, and this was great help. I guess I was clinging onto `0.8.8` for a while. Glad I'm up to date and everything migrated. 

@rossmcdonald You said `(we no longer use /opt/influxdb for anything).` Can I just delete the whole thing?

**Comment by rossmcdonald** [comment]
@poblabs Yes you can. I'd recommend verifying everything on the 0.9+ instance is as it should be, but, once that's done, everything under `/opt/influxdb` can be removed.

**Comment by poblabs** [comment]
@rossmcdonald So far so good with read/writes. I went all the way to 0.13. Thanks again for the guidance.
