### ISSUE TITLE
No results on SELECT column with underscore in name

### ISSUE THREAD

**Issue by Tim10000** [influxdata/influxdb#6761]
Hi Everybody, 
I just encountered a bug on my local influxdb 0.13 installed on a centOS 6.8 .

In fact if I try a query like this:
`SELECT COLUMN_WITHUNDERSCORE FROM table`
Influxdb return no result. 

But if I do:
`SELECT COLUMN_WITHUNDERSCORE, COLUMNWITHOUTUNDERSCORE FROM table`
Influxdb return results as expected.

**Comment by jsternberg** [comment]
Is `COLUMN_WITHUNDERSCORE` a tag or field?

**Comment by Tim10000** [comment]
Good catch it is a Tag field! And I suppose it's the normal behaviour in this case, sorry I'm learning how to use your product ! Thank you for the answer.
