### ISSUE TITLE
Memory issue on influxDB 0.11.1

### ISSUE THREAD

**Issue by Abhishekpan** [influxdata/influxdb#6762]
Hi,
I am facing memory shoot-up issue at the time of data insertion in InfluxDB.

PFB the configuration ::
Server :: UNIX
DISK type :: HDD
Memory   :: 32GB
CPU :: 16
Node :: Single
RF :: 1

Data insertion rate 23k per sec
Each record having 19 attributes

we tried below combinations but facing memory shoot-up issue
1st one
1 Measurement  1 RP(2d)     1 attribute as TAG(Router IP - 50 distinct value)   18 attributes as Field 

2nd One
1 Measurement  1 RP(2d)     0 attributes as TAG                                               18 attributes as Field

Can you please suggest what's going wrong here?

**Comment by Abhishekpan** [comment]
@jwilder Sorry for late reply ..
Recently we did some schema changes and here is the details
We have 18 attributes in a single record(each record size is 50 bytes) like  
TAG1  (* is mandatory for all measure) (unique values - 250)
TAG2  (unique values - 600)
TAG3 (unique values - 600)
TAG4 (unique values - 100)
TAG5 (unique values - 10)
TAG6 (unique values - 10)
TAG7 (unique values - 1000)
TAG8 (unique values - 1000)
TAG9 (unique values - 5)
TAG10 (unique values - 5)
TAG11 (unique values - 2)
TAG12 (unique values - 64)
TAG13 (unique values - 100)
TAG14 (unique values - 10)
TAG15 (unique values - 10)
TAG16 (unique values - 10)
Field1
Field2

So we re-designed our databases accordingly
DB1 is database name and M stand for measurement, where each measurement have below  attributes
M1 having ( Field1, TAG1  ,TAG2)
M2 having ( Field1, TAG1  ,TAG3)
M3 having ( Field1, TAG1  ,TAG4)
M4 having ( Field1, TAG1  ,TAG5)
M5 having ( Field1, TAG1  ,TAG6)
M6 having (  Field1, TAG1  ,TAG7)
M7 having ( Field1, TAG1  ,TAG8)
M8 having ( Field1, TAG1  ,TAG9)
M9 having ( Field1, TAG1  ,TAG10)
M10 having ( Field1, TAG1  ,TAG11)
M11 having (  Field1, TAG1  ,TAG12)
M12 having ( Field1, TAG1  ,TAG13)
M13 having ( Field1, TAG1  ,TAG14)
M14 having ( Field1, TAG1  ,TAG15)
M15 having ( Field1, TAG1  ,TAG16)

Currently we have 6 databases(In a single server) with different aggregation time and retention policy  like 
DB1 (raw data), DB2(5min aggregation data), DB3(Hourly aggregation data), DB4(Daily aggregation data), DB5(Weekly aggregation data) and DB6 (Monthly aggregation data)
and each database has above measurements.

We tried with 15k records/sec load but its ran only 5 hours and then crashed. In log we found below error
“**write failed for shard 18 on node 1: engine: cache maximum memory size exceeded**”
Sometimes it crashed without any error msg (InfluxDB Memory reached to 98%).

We also noticed that for few shards, WAL files(147 wal files in a shard) were not getting flushed properly ,as a result shard size increase to 1.5 GB before crash.

Here some stats on series cardinality
name: database
tags: database= DB1
numMeasurements numSeries
--------------- ---------
15              785200

name: database
tags: database= DB2
numMeasurements numSeries
--------------- ---------
15              785203

name: database
tags: database= DB3
numMeasurements numSeries
--------------- ---------
15              785203

name: database
tags: database= DB4
numMeasurements numSeries
--------------- ---------
15              785203

name: database
tags: database=DB5
numMeasurements numSeries
--------------- ---------
15              785203

name: database
tags: database= DB6
numMeasurements numSeries
--------------- ---------
15              785203

PFB the server configuration ::
 Server :: UNIX
 DISK type :: HDD
 Memory :: 64GB
 CPU :: 16
 Node :: Single
 RF :: 1
[strace.out.gz](https://github.com/influxdata/influxdb/files/325378/strace.out.gz)
[heap.txt.gz](https://github.com/influxdata/influxdb/files/325383/heap.txt.gz)
[goroutine.txt.gz](https://github.com/influxdata/influxdb/files/325384/goroutine.txt.gz)

Please let me know if anything require from my side..

**Comment by carbolymer** [comment]
This is the same issue: #5440

**Comment by jwilder** [comment]
`0.11` is no longer maintained.  Please upgrade to 1.0.2 and log a new issue if this is still occurring.

There may be several things going here:

* You have high cardinality/schema design issue which causes higher memory usage
* You may be backfilling data which requires different settings to avoid memory being held for too long in shard caches
* The `cache max memory exceeded` error is due to `cache-max-memory-size` being too low for your data set.  You may need to increase this by 2-4x
* HDD will also cause problems as they will not be able to keep up with moderate loads.  SSDs work much better.
