### ISSUE TITLE
influxdb stops accepting writes

### ISSUE THREAD

**Issue by rubycut** [influxdata/influxdb#6770]
### Bug report

__System info:__ 0.13.0, debian wheezy

__Steps to reproduce:__

1. Turn on auth
2. Start writing 10k writepoints per second
3. One user should have wrong password

__Expected behavior:__ influxdb should ignore wrong passwords and keep sustained writing rate (like in 0.12.2)

__Actual behavior:__ influxdb slows down and stops writing anything

__Additional info:__ [Include gist of relevant config, logs, etc.]

```
[httpd] 2016/06/02 07:15:54 xxx.xxx.252.245 - c3474_telegraf [02/Jun/2016:07:15:54 +0000] POST /write?consistency=&db=c3474&precision=s&rp= HTTP/1.1 401 57 - Go-http-client/1.1 d87cd7f1-2891-11e6-81c4-000000000000 115.148576ms
[httpd] 2016/06/02 07:15:55 xxx.xxx.252.245 - c3530_telegraf [02/Jun/2016:07:15:54 +0000] POST /write?consistency=&db=c3530&precision=s&rp= HTTP/1.1 204 0 - Go-http-client/1.1 d887eb19-2891-11e6-81c5-000000000000 50.267684ms
[httpd] 2016/06/02 07:15:55 xxx.xxx.252.245 - c3474_telegraf [02/Jun/2016:07:15:55 +0000] POST /write?consistency=&db=c3474&precision=s&rp= HTTP/1.1 401 57 - Go-http-client/1.1 d89ae81c-2891-11e6-81c6-000000000000 115.046197ms
[httpd] 2016/06/02 07:15:59 xxx.xxx.252.245 - c3474_telegraf [02/Jun/2016:07:15:59 +0000] POST /write?consistency=&db=c3474&precision=s&rp= HTTP/1.1 401 57 - Go-http-client/1.1 db0efb9a-2891-11e6-81c7-000000000000 118.273879ms
```

As you can see, one request every few seconds is processed, in the normal flow, there is 20 requests per second.

Everything works fine in 0.12.2

**Comment by rubycut** [comment]
This is actually relay problem.

**Comment by rubycut** [comment]
Problem is between influxdb 0.13 and influx relay. Relay somehow stops sending data.

**Comment by jwilder** [comment]
Closing this since it's a relay problem.
