### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aderumier** [influxdata/influxdb#6772]
Hi,

I had a crash today:

version : 0.14.0~n201605170800

`[collectd] 2016/06/02 16:32:04 failed to write point batch to database "collectd": timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x64c862]

goroutine 20543184 [running]:
panic(0xb72000, 0xc82000e0c0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/influxdb/tsdb.(*fieldKeysIterator).Next(0xce51f43080, 0xcd52d67800, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:1039 +0x392
github.com/influxdata/influxdb/influxql.(*floatSortedMergeIterator).pop(0xc948532000, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:360 +0x190
github.com/influxdata/influxdb/influxql.(*floatSortedMergeIterator).Next(0xc948532000, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:349 +0x2d
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xcf952b0300, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:750 +0xb5
github.com/influxdata/influxdb/influxql.(*floatDedupeIterator).Next(0xcf952b0320, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1971 +0x5e
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xcf952b0340, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:96 +0x69
github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xd103e04600)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:817 +0x2b
created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:781 +0x35
`

**Comment by jwilder** [comment]
@aderumier There was a fix for this panic in #6754.  Can you run `influxd version` to determine if you have that fix in your build or not?

**Comment by rossmcdonald** [comment]
@aderumier It looks like you're running a nightly from May 17th. Can you retry with the latest nightly to see if the issue persists? #6754 wasn't added until day before yesterday, so it won't be in your build.

**Comment by aderumier** [comment]
Ok, thanks. I'll try lastest nightly.
(Note that I'm not sure to reproduce it, I have hitted this bug once only)

**Comment by jwilder** [comment]
Fixed via #6754
