### ISSUE TITLE
client query is POST not GET

### ISSUE THREAD

**Issue by Belsepubi** [influxdata/influxdb#6775]
### Bug report

__Steps to reproduce:__

1. Run a simple query e.g. `SELECT * FROM my_thing`

__Expected behavior:__ Function should return correct results

__Actual behavior:__ `unable to decode json: received status code 405 err: invalid character 'M' looking for beginning of value`

__Additional info:__ Changing method from `POST` to `GET` in ..v2/client.go made this work like a charm.

**Comment by rossmcdonald** [comment]
@Belsepubi Thank you for the report. This behavior was already changed with https://github.com/influxdata/influxdb/commit/6f61c0ea4a7fd494ec1092554e9ec3309a5d5f29, so you may be using the outdated client code.

**Comment by Belsepubi** [comment]
Hi,

I can see the change from GET to POST. However the POST is not working. If
I change it to GET it works.

Thanks,

 - Belsepubi

On Fri, Jun 3, 2016 at 6:08 PM, Ross McDonald <notifications@github.com>
wrote:

> @Belsepubi <https://github.com/Belsepubi> Thank you for the report. This
> behavior was already changed with 6f61c0e
> <https://github.com/influxdata/influxdb/commit/6f61c0ea4a7fd494ec1092554e9ec3309a5d5f29>,
> so you may be using the outdated client code.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/influxdata/influxdb/issues/6775#issuecomment-223605272>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAQJLauQd9KhUDqb_XyuHBsZ1UI4XxF7ks5qIEN7gaJpZM4ItcWw>
> .
>



-- 

Best regards,
Antti Kokko
Meshmoon developer at Adminotech Ltd.
www.meshmoon.com

**Comment by Belsepubi** [comment]
It seems I´m running too old version of db itself. However installing the
latest fails on ubuntu..:) -> Failed to execute operation: Too many levels
of symbolic links.

On Mon, Jun 6, 2016 at 9:31 AM, Antti Kokko <antti.kokko@adminotech.com>
wrote:

> Hi,
>
> I can see the change from GET to POST. However the POST is not working. If
> I change it to GET it works.
>
> Thanks,
>
>  - Belsepubi
>
> On Fri, Jun 3, 2016 at 6:08 PM, Ross McDonald <notifications@github.com>
> wrote:
>
>> @Belsepubi <https://github.com/Belsepubi> Thank you for the report. This
>> behavior was already changed with 6f61c0e
>> <https://github.com/influxdata/influxdb/commit/6f61c0ea4a7fd494ec1092554e9ec3309a5d5f29>,
>> so you may be using the outdated client code.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/influxdata/influxdb/issues/6775#issuecomment-223605272>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAQJLauQd9KhUDqb_XyuHBsZ1UI4XxF7ks5qIEN7gaJpZM4ItcWw>
>> .
>>
>
>
>
> --
>
> Best regards,
> Antti Kokko
> Meshmoon developer at Adminotech Ltd.
> www.meshmoon.com
>



-- 

Best regards,
Antti Kokko
Meshmoon developer at Adminotech Ltd.
www.meshmoon.com

**Comment by rossmcdonald** [comment]
@Belsepubi Can you paste the full output as well as the commands used to attempt the installation?

**Comment by Belsepubi** [comment]
I had installed a version 0.10.0 .via apt-get last week. During that
installation I didn´t check that it was an old version. Now I had to remove
that and then manually remove every influx -named file. Then I installed
the latest version just like the installation guide told and everything
works fine. First I unmasked the influx service and got a different error
which I cannot get hold of anymore so decided to manually remove everything
and it succeeded.

On Mon, Jun 6, 2016 at 7:09 PM, Ross McDonald <notifications@github.com>
wrote:

> @Belsepubi <https://github.com/Belsepubi> Can you paste the full output
> as well as the commands used to attempt the installation?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/influxdata/influxdb/issues/6775#issuecomment-224006441>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAQJLTDB-KRx6VhBS5l8h36Axo8PJAl2ks5qJEYkgaJpZM4ItcWw>
> .
>



-- 

Best regards,
Antti Kokko
Meshmoon developer at Adminotech Ltd.
www.meshmoon.com
