### ISSUE TITLE
Influx -version returns unknown

### ISSUE THREAD

**Issue by ogarcia** [influxdata/influxdb#6777]
__System info:__ Arch Linux with own compiled latest git tag of influx (v0.13.0)

__Steps to reproduce:__

1. Download latest tag from github
2. Compile and install
3. Execute `influx -version`

__Expected behavior:__ That gives some like `InfluxDB shell version: 0.13.0`.

__Actual behavior:__ Returns: `InfluxDB shell version: unknown`

**Comment by rossmcdonald** [comment]
@ogarcia The version (and commit and branch) is a linker flag set at compile-time. You can see how we set this in the build script here: https://github.com/influxdata/influxdb/blob/master/build.py#L535

I'd recommend using the `build.py` script for future builds, as that includes all of the necessary steps that we use for building the official packages.

**Comment by ogarcia** [comment]
Ok!!! I try to use the build.py ;)

Maybe you could write some build doc for future generations?? :grin: 

Thanks!

**Comment by ogarcia** [comment]
@rossmcdonald There is a problem with `build.py` script. If I download a tagged version from github (for example https://github.com/influxdata/influxdb/archive/v0.13.0.zip) and run the script I give this error:

```
[ERROR] run: Command 'git rev-parse --abbrev-ref HEAD' failed with error: fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

This is normal because not is a git repo. I think that the script must detect tagged versions (maybe adding a version file only in these versions?) cause the package systems prefer use a "unmutable file" that can be checked with a sha1sum (or similar).

**Comment by rossmcdonald** [comment]
@ogarcia Yes, the build script assumes you are running it inside a git directory. Is there a reason you are not cloning the repository and then checking out the version tag you need? You can also use `python build.py --commit <tag>` to build from a specific commit.

Also, is there a reason you are compiling from source instead of using one of the pre-built packages?

**Comment by ogarcia** [comment]
@rossmcdonald The only reason is to build Arch Linux package from source that is "more elegant" than use binary package.

Anyway no problem cause I can do `-ldflags "-X main.version=${pkgver}"` and set the version from tag as I do [here](https://git.connectical.com/aur/influxdb/src/master/PKGBUILD).

Many thanks for your help!

**Comment by dewi-ny-je** [comment]
Same issue here. I'm on Windows 10 and corss-compiling for solaris. 
The steps are:

> set pkgver='1.0.2'
> echo %pkgver%
'1.0.2'
> go get github.com/influxdata/influxdb
> cd %GOPATH%\src\github.com\influxdata
> go get ./...
> go install ./...

The resulting binaries seem to work, but I get no version info.
What is the procedure to obtain said version info when cross-compiling?

**Comment by rossmcdonald** [comment]
@dewi-ny-je You have to include the linker flags mentioned in this issue above. To add the version information, you have to add a `-ldflags="-X main.version=%pkgver%"` to the `go install` command.
