### ISSUE TITLE
Feature request: paginate output of SHOW TAG VALUES

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#6780]
`SHOW TAG VALUES` is often fed into GUIs (i.e. Chronograf and Grafana). It's very easy to end up with far more tag values than a UI can easily represent, so it would be useful to be able to paginate the results (perhaps with LIMIT and OFFSET?).

/cc @pauldix

**Comment by pauldix** [comment]
Yes, definitely. `LIMIT` and `OFFSET` would work well.

**Comment by mark-rushakoff** [comment]
Oops, this already works:

```
> show tag values with key = "xid" limit 4
name: find_sat_writes
---------------------
key	value
xid	efahyulaf9
xid	efai1wu8qd
xid	efai27rl7r
xid	efaibl3xqb

> show tag values with key = "xid" limit 3 offset 1
name: find_sat_writes
---------------------
key	value
xid	efai1wu8qd
xid	efai27rl7r
xid	efaibl3xqb
```
