### ISSUE TITLE
create databases error.

### ISSUE THREAD

**Issue by mslee89** [influxdata/influxdb#6781]
hi.

i should create a database.
but occurred error it.

"ERR: error parsing query: found -, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 25"

create a database to can't use "-"?

help me.

**Comment by mark-rushakoff** [comment]
Use double quotes.

```
> create database db-with-dashes
ERR: error parsing query: found -, expected ; at line 1, char 19
> create database "db-with-dashes"
> show databases
name: databases
---------------
name
_internal
db-with-dashes
```
