### ISSUE TITLE
panic when using go1.6.2

### ISSUE THREAD

**Issue by rubycut** [influxdata/influxdb#6782]
### Bug report

**System info:** 0.13.0, Debian wheezy, 

**Steps to reproduce:**
1. Leave it running with small load 284 WritePointsOk per second.
2. Auth should be on.
3. Create 6 different databases, each custom writes to one database.

**Expected behavior:** It should run without problems

**Actual behavior:** Crashed. Panic.

**Additional info:** 

This happended 2:46 in the morning, so no shard switch was involved. Previously, database was running for about 7 hours.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xf pc=0x410956]

goroutine 97846 [running]:
panic(0xb5b260, 0xc82000e0d0)
        /root/.gvm/gos/go1.6.2/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Cache).entry(0xcace066500, 0xc9df9665a0, 0x4c, 0x1)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:459 +0x71
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Cache).WriteMulti(0xcace066500, 0xca469d1a10, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:207 +0x2b2
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).WritePoints(0xc9a00da790, 0xc91b005800, 0x5b, 0x80, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:356 +0x4c7
github.com/influxdata/influxdb/tsdb.(*Shard).WritePoints(0xcac384eea0, 0xc91b005800, 0x5b, 0x80, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/shard.go:270 +0x2b2
github.com/influxdata/influxdb/tsdb.(*Store).WriteToShard(0xc8201cc0f0, 0x559, 0xc91b005800, 0x5b, 0x80, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/store.go:689 +0x15c
github.com/influxdata/influxdb/cluster.(*PointsWriter).writeToShard(0xc82018b040, 0xca25d0ada0, 0xc9f8a5af9c, 0x5, 0xc82021c1e0, 0xb, 0xc91b005800, 0x5b, 0x80, 0x0, ...)
        /workbench/src/github.com/influxdata/influxdb/cluster/points_writer.go:254 +0xd0
github.com/influxdata/influxdb/cluster.(*PointsWriter).WritePoints.func1(0xca465e1ce0, 0xc82018b040, 0xca25d0ada0, 0xc9f8a5af9c, 0x5, 0xc82021c1e0, 0xb, 0xc91b005800, 0x5b, 0x80)
        /workbench/src/github.com/influxdata/influxdb/cluster/points_writer.go:217 +0x8d
created by github.com/influxdata/influxdb/cluster.(*PointsWriter).WritePoints
        /workbench/src/github.com/influxdata/influxdb/cluster/points_writer.go:218 +0x3d9
```

**Comment by rubycut** [comment]
I can try any ref you want me to, but we use auth, so nothing will work until #6769 is merged. But I can easily apply out patch to any ref.

**Comment by rubycut** [comment]
Another similar failure:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x885dcc]

goroutine 38497 [running]:
panic(0xb5b260, 0xc82000e0d0)
        /root/.gvm/gos/go1.6.2/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*entry).add(0xc85d40ea00, 0xc864c8c1a0, 0x1, 0x1)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:62 +0x1cc
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Cache).WriteMulti(0xc87b148f00, 0xc8598de1b0, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:207 +0x2de
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).WritePoints(0xc87e685d90, 0xc8bbb4a000, 0xfec, 0x1200, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:356 +0x4c7
github.com/influxdata/influxdb/tsdb.(*Shard).WritePoints(0xc85fbbfe60, 0xc8bbb4a000, 0xfec, 0x1200, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/shard.go:270 +0x2b2
github.com/influxdata/influxdb/tsdb.(*Store).WriteToShard(0xc82017c0f0, 0x550, 0xc8bbb4a000, 0xfec, 0x1200, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/store.go:689 +0x15c
github.com/influxdata/influxdb/cluster.(*PointsWriter).writeToShard(0xc820174780, 0xc8b559a040, 0xc820145a50, 0x9, 0xc5a800, 0x7, 0xc8bbb4a000, 0xfec, 0x1200, 0x0, ...)
        /workbench/src/github.com/influxdata/influxdb/cluster/points_writer.go:254 +0xd0
github.com/influxdata/influxdb/cluster.(*PointsWriter).WritePoints.func1(0xc885284a80, 0xc820174780, 0xc8b559a040, 0xc820145a50, 0x9, 0xc5a800, 0x7, 0xc8bbb4a000, 0xfec, 0x1200)
        /workbench/src/github.com/influxdata/influxdb/cluster/points_writer.go:217 +0x8d
created by github.com/influxdata/influxdb/cluster.(*PointsWriter).WritePoints
        /workbench/src/github.com/influxdata/influxdb/cluster/points_writer.go:218 +0x3d9
```

**Comment by jonseymour** [comment]
Is the level of code you are running exactly v0.13.0 or is it v0.13.0 with some other changes. The reason I ask is that I can't make sense of the stack traces (as compared to the code) if this is meant to be exactly v0.13.0

**Comment by rubycut** [comment]
This is the version I am using:
```
commit e57fb88a051ee40fd9277094345fbd47bb4783ce
Author: Jason Wilder <jwilder@users.noreply.github.com>
Date:   Wed May 11 13:37:42 2016 -0600

    Update 0.13.0 release date
```

All the lines match with stack trace:

        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:62 +0x1cc


Line is: 

https://github.com/influxdata/influxdb/blob/v0.13.0/tsdb/engine/tsm1/cache.go#L62

You are writing to e.values

**Comment by rubycut** [comment]
Same goes for first example:

https://github.com/influxdata/influxdb/blob/v0.13.0/tsdb/engine/tsm1/cache.go#L459

Is c.store properly initialized, or there is some kind of race condition?

**Comment by rubycut** [comment]
I otop of that tree, I added only few lines as explained in #6769 but this pull request doesn't touch engine dir.

**Comment by jonseymour** [comment]
Ok. The reason I asked is that  **c.store** is only ever assigned to during initialisation of a Cache so it is strange that line https://github.com/influxdata/influxdb/blob/v0.13.0/tsdb/engine/tsm1/cache.go#L459 can throw a nil pointer exception. More thought required...

**Comment by rubycut** [comment]
Key here is that it doesn't happen in 0.12.2 So, I am going though:

    git log -p v0.12.2..v0.13.0 -- tsdb/engine/tsm1/cache.go

To see if anything looks suspicious.

**Comment by jonseymour** [comment]
Do you have the full stacktraces available from the events above?

**Comment by rubycut** [comment]
Nope, this is everything which appeared in the log, after that, there is influxdb server starting again.

For program-ending panics, the runtime now by default prints only the stack of the running goroutine, not all existing goroutines. Usually only the current goroutine is relevant to a panic, so omitting the others significantly reduces irrelevant output in a crash message. To see the stacks from all goroutines in crash messages, set the environment variable GOTRACEBACK to all or call debug.SetTraceback before the crash, and rerun the program. See the runtime documentation for details.

from https://golang.org/doc/go1.6

I can run it again with GOTRACKBACK value.

**Comment by rubycut** [comment]
https://github.com/influxdata/influxdb/commit/87ceb7426a094c4296f95854bf7dba8a7c0baea4#diff-c8d1b07d0839e4d24dbd73e7d2f5ade6R189

This is the problem I think, mutex is locked in entry() and add() but in between, there is small window of opportunity that some other goroutine will obtain lock and delete this entry we referenced in entry. @jwilder , thoughts?

**Comment by jonseymour** [comment]
The reason I asked about stack trace showing other goroutines is that c.store does get modified during snapshotting. There is a locking pattern that are meant to prevent unsafe access, but perhaps that locking pattern isn't working as intended. Presence of Snapshot() on the stack at the time of failure would be suggestive of this issue.

**Comment by rubycut** [comment]
Yep, I'll do full backtrace. But we might have to wait couple of hours until bug appears again.

**Comment by jwilder** [comment]
#6794 may be related to this.  @rubycut Can you describe your runtime env?  How much RAM, CPU Arch, etc..?

Also, would you be able to test latest master or tonight's nightly to see if it still occurs.

**Comment by jwilder** [comment]
@rubycut Can you include the logs from before the panic?  If you able to run w/ `GOTRACEBACK=all` that would be helpful as well.

**Comment by rubycut** [comment]
@jwilder, as hardware specs go, it's a fire breathing dragon, 64Gb of RAM, we are constantly around 25% usage of RAM, 24 cores, SSD drives, you name it, so resource exhaustion is not issue here.

**Comment by rubycut** [comment]
ok, let me try master now, and I will give you full stack trace in case of any problems.

**Comment by rubycut** [comment]
Arch is 64bit linux, debian.

**Comment by rubycut** [comment]
@jwilder, master branch didn't last for one hour, strace trace is 100 k lines big, how do you want me to give it to you?

**Comment by jwilder** [comment]
@rubycut Can you attach it to this issue?

**Comment by rubycut** [comment]
Here you go.

[error.txt](https://github.com/influxdata/influxdb/files/302986/error.txt)

**Comment by rubycut** [comment]
each entry has a mutex, you obtain entry, through entry() function, and then you pass that pointer to 
add() function:

https://github.com/influxdata/influxdb/blob/b972c220aa0b847428173b8321f1d0f6d7f277e2/tsdb/engine/tsm1/cache.go#L207

ok, that should be save since each entry has mutex, but then, after you obtain pointer to entry, you keep the pointer and unlock main mutex.

in add function, you are not locking main mutex, you are just locking the entry mutex:

https://github.com/influxdata/influxdb/blob/b972c220aa0b847428173b8321f1d0f6d7f277e2/tsdb/engine/tsm1/cache.go#L54

But then here, you are deleting entry completely disregarding if entry mutex is locked or not:

https://github.com/influxdata/influxdb/blob/b972c220aa0b847428173b8321f1d0f6d7f277e2/tsdb/engine/tsm1/cache.go#L348

Hooah?

**Comment by jwilder** [comment]
@rubycut Would you be able to run latest master with the race detector enabled?

```
go install -race ./... && influxd
```

**Comment by jonseymour** [comment]
@rubycut May I play devill's advocate? The delete at line 348 is protected by the cache mutex. It doesn't need to be protected by the entry mutex since it isn't modifying the entry, it is modifying the cache.

**Comment by rubycut** [comment]
@jonseymour, but if we are deleting cache entry, some other routine may obtained pointer to that entry that we are deleting and then we get panic.

**Comment by rubycut** [comment]
@jwilder, running with race detector doesn't show any extra output, everything is same like last time, as if race detector is not running, it should dump info on stderr and it should end up in log file like other output, but there is no race output in log file.

**Comment by jonseymour** [comment]
@rubycut remember that `delete(c.store, k)` on L348 only modifies storage associated with `store` - it does not release the memory associated with the entry stored at index `k', it merely removes a reference to it - there is no thread safety issue with code at line L348.

**Comment by rubycut** [comment]
Ok, you got a point there, back to the drawing board.

**Comment by rubycut** [comment]
Laster master
```
go install -race -ldflags="-X main.version=master -X main.branch=master -X main.commit=256f57a" ./...
```

This doesn't work at all:
```
[cacheloader] 2016/06/08 06:02:06 reading file /home/influxdb/wal/c3148/four_months/1960/_00031.wal, size 0
ThreadSanitizer: DenseSlabAllocator overflow. Dying.
```

**Comment by rubycut** [comment]
ok, without -race it works.

**Comment by rubycut** [comment]
[error2.txt](https://github.com/influxdata/influxdb/files/304390/error2.txt)

This error came after running for 2 hours, 40 minutes.

But, 0.12.2 can run for days without going down.

**Comment by rubycut** [comment]
More fun, was running 40 minutes this time:

```
[httpd] 2016/06/08 09:40:36 x.x.117.142 - c3479_telegraf [08/Jun/2016:09:40:36 +0000] POST /write?consistency=&db=c3479&precision=s&rp= HTTP/1.1 204 0 - InfluxDBClient 0d6eac60-2d5d-11e6-aa44-000000000000 108.518274ms
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x2 addr=0xba46a0 pc=0x4142ac]

goroutine 7011 [running]:
runtime.throw(0xd75920, 0x2a)
        /root/.gvm/gos/go1.6.2/src/runtime/panic.go:547 +0x90 fp=0xca95b3d4c0 sp=0xca95b3d4a8
runtime.sigpanic()
        /root/.gvm/gos/go1.6.2/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xca95b3d510 sp=0xca95b3d4c0
runtime.mallocgc(0x50, 0xa3d560, 0x1, 0x0)
        /root/.gvm/gos/go1.6.2/src/runtime/malloc.go:654 +0x8ec fp=0xca95b3d5e8 sp=0xca95b3d510
runtime.newarray(0xa3d560, 0x49, 0xde4129)
        /root/.gvm/gos/go1.6.2/src/runtime/malloc.go:798 +0xc9 fp=0xca95b3d628 sp=0xca95b3d5e8
runtime.makeslice(0xa25860, 0x49, 0x49, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.6.2/src/runtime/slice.go:32 +0x165 fp=0xca95b3d678 sp=0xca95b3d628
syscall.ByteSliceFromString(0x7f41a8c29040, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.6.2/src/syscall/syscall.go:53 +0x126 fp=0xca95b3d700 sp=0xca95b3d678
syscall.BytePtrFromString(0x7f41a8c29040, 0x48, 0x42, 0x0, 0x0)
        /root/.gvm/gos/go1.6.2/src/syscall/syscall.go:69 +0x3b fp=0xca95b3d740 sp=0xca95b3d700
syscall.Stat(0x7f41a8c29040, 0x48, 0xc8aad30378, 0x0, 0x0)
        /root/.gvm/gos/go1.6.2/src/syscall/zsyscall_linux_amd64.go:1525 +0x40 fp=0xca95b3d7a0 sp=0xca95b3d740
os.Stat(0x7f41a8c29040, 0x48, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.6.2/src/os/file_unix.go:169 +0x6f fp=0xca95b3d7f8 sp=0xca95b3d7a0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Tombstoner).HasTombstones(0xc8a1176fe0, 0x1455f5d35a42965e)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/tombstone.go:83 +0x47 fp=0xca95b3d860 sp=0xca95b3d7f8
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*TSMReader).Stats(0xc82eb4adc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:422 +0x13f fp=0xca95b3d940 sp=0xca95b3d860
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*FileStore).Stats(0xc86ee38700, 0x0, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.go:426 +0x17a fp=0xca95b3da60 sp=0xca95b3d940
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*DefaultPlanner).findGenerations(0xc8e601c800, 0x0, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:390 +0xa4 fp=0xca95b3dc70 sp=0xca95b3da60
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*DefaultPlanner).PlanLevel(0xc8e601c800, 0x2, 0x0, 0x0, 0x0)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:144 +0x4d fp=0xca95b3dea8 sp=0xca95b3dc70
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel(0xc89139e0c0, 0x1, 0x2)
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:743 +0xe5 fp=0xca95b3df98 sp=0xca95b3dea8
runtime.goexit()
        /root/.gvm/gos/go1.6.2/src/runtime/asm_amd64.s:1998 +0x1 fp=0xca95b3dfa0 sp=0xca95b3df98
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).SetCompactionsEnabled
        /workbench/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:139 +0x1ca

```

**Comment by jwilder** [comment]
0.12 was compiled with go 1.4.3.  0.13 uses go 1.6.2.  These errors look more like an issue w/ the go runtime or your particular OS.

Can you run: `uname -a` and `go env`?

Could you try running latest master w/ go 1.4.3?

**Comment by rubycut** [comment]
Production machine is debian wheezy with custom kernel:
```
Linux xxxx 3.10.95xxx #30 SMP Fri Jan 29 11:54:46 CST 2016 x86_64 GNU/Linux
```

I am doing compile on ubuntu:
```
uname -a
Linux xxx1133 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

git:(master) go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/workbench"
GORACE=""
GOROOT="/root/.gvm/gos/go1.6.2"
GOTOOLDIR="/root/.gvm/gos/go1.6.2/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by rubycut** [comment]
Go is compiled by installing go1.4.3 as instructed in https://github.com/moovweb/gvm

**Comment by rubycut** [comment]
I'll try with go1.4.3 and latest master

**Comment by rubycut** [comment]
@jwilder, I will report if it crashes with go1.4.3, however, I don't think there is problem with my particular OS, if you ship influxdb 1.0.0 compiled with go.1.6.2, then I guess many people will have similar issues like me.

**Comment by jwilder** [comment]
@rubycut 0.13 was released and uses go 1.6.2, but this is the first report of an any issue that might be related to the switch to go 1.6.2.  

Your OS in combination with the go runtime _may_ be causing the issue since you are seeing several  errors that don't appear to be related.  You mentioned you are also running a custom kernel which might also be a factor.

These errors are hard to explain and don't seem to be related from the information I have:

* Compiling w/ `-race`, you got a `ThreadSanitizer: DenseSlabAllocator overflow. Dying.` error which does not originate in the `influxdb` source.  It looks like something related to [llvm] (http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20140526/219035.html) and/or the go tool chain.
* `panic: runtime error: invalid memory address or nil pointer dereference` in the `cache` - maybe a race we haven't seen yet.
* `fatal error: unexpected signal during runtime execution` when `stat`ing a TSM tombstone file - Possibly Go runtime/OS combination issue
* `unexpected fault address 0xc3ce6425b0` in `http.Server` - Possibly Go runtime/OS combination issue

While I wouldn't rule out that the root issue is in the influxdb source yet, it looks less likely based on the errors you are seeing.

**Comment by rubycut** [comment]
Yea, we'll see, we are running influxdb with what could be called "realistic loads", we have over 1000 telegraf clients sending data, we use auth, and we currently have 305k series in the db.

So, we want to follow influxdb version and run latest stuff so that we can report additional bugs.

For example, when we had measurements with 60k series, influxdb start dying every midnight UTC, something related with shard switch. We want to report that bug, but to report bug we need to run latest version. In the meantime, this bug disappeared.

So, let's see what happens with running latest master with go1.4.3

**Comment by rubycut** [comment]
influxdb is running normally with go1.4.3 during the last 23 hours, maybe you can put label go1.6 to keep this issue as reference.

I would suggest reverting to compling influxdb with go1.4.3, but that is probably not going to pass in case I am the only one reporting issues. 

We will be compiling our inhouse influxdb with go1.4.3 anyway.

**Comment by jwilder** [comment]
@rubycut would you be able to test with go 1.7? It may be fixed there.

**Comment by jwilder** [comment]
@rubycut We will not be able to revert  to 1.4.3 because that version is now unsupported by the Golang team.  Their [release policy](https://golang.org/doc/devel/release.html#policy) states that security issues will no longer be patched in go 1.4.  

We would like to move to go 1.7 when it's ready.  If this issue still occurs with go 1.7, we'll need to log an issue with the Go project.  Since you are able to reproduce this issue fairly reliably, your help testing and  getting it fixed would be great.

**Comment by rubycut** [comment]
Sure, I'll try golang 1.7, no problem.

**Comment by rubycut** [comment]
@jwilder, tried with golang 1.7beta1, same sha as the last time: 256f57a

Didn't last even half hour, error is:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x82c283]

goroutine 73218 [running]:
panic(0x994180, 0xc4200100b0)
        /root/.gvm/gos/go1.7beta1/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*directIndex).WriteTo(0xc5af1f0420, 0xd78bc0, 0xc6c82b1e00, 0x0, 0x0, 0x0)
        /workbench/influx_on_go1.7/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:331 +0x2a3
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmWriter).WriteIndex(0xc5af1f0510, 0xc50df1dd00, 0x23)
        /workbench/influx_on_go1.7/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:542 +0x7b
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0xc424f5dc20, 0xc5a6b87c70, 0x46, 0xd82ac0, 0xc63d024800, 0x0, 0x0)
        /workbench/influx_on_go1.7/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:647 +0x600
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0xc424f5dc20, 0x221, 0x4, 0xd82ac0, 0xc63d024800, 0xd82ac0, 0xc63d024800, 0x0, 0x0, 0xc424f5def0)
        /workbench/influx_on_go1.7/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:554 +0x280
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).compact(0xc424f5dc20, 0xc66f7b8100, 0xc6c82b1b80, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /workbench/influx_on_go1.7/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:513 +0x52c
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).CompactFull(0xc424f5dc20, 0xc6c82b1b80, 0x4, 0x4, 0x4, 0x4, 0xc516cd3d80, 0xc516cd3df8, 0x5fead2)
        /workbench/influx_on_go1.7/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:526 +0x99
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel.func1(0xc4742e5700, 0xc42472e600, 0x3, 0xecef1f900, 0x0, 0xc6c82b1b80, 0x4, 0x4)
        /workbench/influx_on_go1.7/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:772 +0xa45
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel
        /workbench/influx_on_go1.7/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:791 +0x1de
```

**Comment by rubycut** [comment]
@jwilder, this issue is still not resolved, we are not able to upgrade to influxdb 1.0.

We will try upgrading to 1.1 and see what happens, I will also try to adjust influxstress tool to be able to replicate our issue.
