### ISSUE TITLE
error with 'measurement'

### ISSUE THREAD

**Issue by gregzuro** [influxdata/influxdb#6785]
### Bug report

Echoes of #3467 :

__System info:__ 

Ubuntu 14.04, and:

```
~$ influx version
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.13.0
InfluxDB shell 0.12.1
> 
```

__Steps to reproduce:__

```
> create database test
> use test
Using database test
> insert measurement value=7
> select * from measurement
ERR: error parsing query: found MEASUREMENT, expected identifier at line 1, char 15
> insert m value=8
> select * from m
name: m
-------
time			value
1465177235753816079	8
```

**Comment by jonseymour** [comment]
@gregzuro. measurement  is also a keyword, so if you want to use measurement in a query you need to enclose it with double quotes (e.g. measurement).

**Comment by gregzuro** [comment]
Ah. I see.  Then I guess this issue is related to the web site docs.

```
measurement value=12
measurement value=12 1439587925
measurement,foo=bar value=12
measurement,foo=bar value=12 1439587925
measurement,foo=bar,bat=baz value=12,otherval=21 1439587925
```

( https://docs.influxdata.com/influxdb/v0.13/write_protocols/write_syntax/ )

**Comment by jonseymour** [comment]
Good point. I'll raise a PR against the documentation to fix this.

**Comment by jonseymour** [comment]
PR raised - https://github.com/influxdata/docs.influxdata.com/pull/492
