### ISSUE TITLE
[0.12.2] Too many open files

### ISSUE THREAD

**Issue by zbindenren** [influxdata/influxdb#6786]
### Bug report

__System info:__ [0.12.2], RHEL7.2, amd64

__Steps to reproduce:__

1. Start influxdb
2. Observe how ~1000 telegraf clients post data
3. wait ~2 days

__Expected behavior:__ No errors in log

__Actual behavior:__  A lot of entries:
[run] 2016/06/06 09:00:05 http: Accept error: accept tcp 172.16.240.72:7003: too many open files; retrying in 1s
65k open files

__Additional info:__ [Include gist of relevant config, logs, etc.]

```
$ lsof -p 8103 |wc -l
65625

$ lsof -p 8103 |grep CLOSE_WAIT |wc -l
3986

```

**Comment by jwilder** [comment]
What version of `telegraf` are you running?

**Comment by zbindenren** [comment]
@jwilder we are using telegraf-0.13.1

**Comment by jwilder** [comment]
I'd suggest upgrading `influxdb` to `0.13` as well.

**Comment by zbindenren** [comment]
I tried that.

After upgrading to influxdb 0.13 the db was not usable anymore. I got a %mem_commit of 1000%. The Server has 64GB Memory installed. I got a lot of http 500 errors, I had to switch back to 0.12.2 which has a %mem_commit of ~20%.

**Comment by jsternberg** [comment]
@zbindenren does this still happen with 1.0?

**Comment by zbindenren** [comment]
@jsternberg I didn't try yet. I'll let you know.

**Comment by zbindenren** [comment]
@jsternberg no problems with 1.0. Closing the issue.
