### ISSUE TITLE
posting with CURL returns Method Not Allowed

### ISSUE THREAD

**Issue by Buzut** [influxdata/influxdb#6787]
I'm on Ubuntu 16.04 with InfluxDB 0.13.

When I try to create DB or any other command via curl, as demonstrated in the [docs](https://docs.influxdata.com/influxdb/v0.13/guides/writing_data/), for instance: 

    curl -POST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

I get an `Method Not Allowed` in return. 

Nevertheless, doing the same with get works perfectly:

    curl http://localhost:8086/query?q=CREATE+DATABASE+"db"

**Comment by zstyblik** [comment]
@Buzut, because only `GET` is allowed. It is a good catch and point. I'll create a ticket for docs.

**Comment by Buzut** [comment]
All right. Thank you for the explanation. The docs misleaded me!

**Comment by zstyblik** [comment]
@Buzut, please see https://github.com/influxdata/docs.influxdata.com/issues/493. I'm not an InfluxDB dev/affiliate, but I have a v0.13.0 running and Web UI is doing `GET` to create a new database. So, I presume the documentation is wrong or outdated. Also, I found https://github.com/influxdata/docs.influxdata.com/pull/462 which clarifies documentation, but ... umm ... I actually ended up a bit confused, because it says that `POST` should be used for `CREATE` and a lot of "modify" commands. However, this doesn't seem to work? May be it's in upcoming release?

I guess we will have to wait for developers to clarify.

Thanks.

**Comment by Buzut** [comment]
@zstyblik Thank you for clarifying this. 
At first, I actually had a look at the requests the WebUI was doing to get a glimpse of how I could automate the setup with scripts. Then I saw in the docs that they were using `POST` with curl, which made sense. But in the end, didn't work, si it's kind of puzzling to be misguided by the docs!

**Comment by beckettsean** [comment]
Docs aren't wrong, there's something else going on.

On Ubuntu 14.04 with InfluxDB 0.13.0 I have no issues creating a database using POST or GET:

```
# curl -POST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE foofoo"
{"results":[{}]}
root@sean-stable:~# influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.13.0
InfluxDB shell version: 0.13.0
> show databases
name: databases
---------------
name
telegraf
_internal
mydb
foofoo

> exit

# curl http://localhost:8086/query --data-urlencode "q=CREATE DATABASE fooget"
{"results":[{}]}
> show databases
name: databases
---------------
name
telegraf
_internal
mydb
foofoo
fooget

```

**Comment by Buzut** [comment]
@beckettsean That's really weird… 
After another try, I still have the same error:

    # curl -POST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE foofoo"
    Method Not Allowed

Would you need more input?

**Comment by beckettsean** [comment]
@Buzut We've got a busy Monday but tomorrow I'll test if it's somehow OS-specific. Not sure why 14.04 vs. 16.04 would matter but it's worth investigating.

How did you install InfluxDB? Was this a new installation or an upgraded one?

**Comment by Buzut** [comment]
@beckettsean I installed this server for testing monitoring. So it's a fresh install.
I used apt to install InfluxDB:

    curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
    echo "deb https://repos.influxdata.com/debian jessie stable" | tee /etc/apt/sources.list.d/influxdb.list
    apt-get update
    apt-get install influxdb influxdb-client

**Comment by jonseymour** [comment]
Is -POST a valid curl option? --get is a valid option but there is no --post. You might have been -XPOST.

**Comment by beckettsean** [comment]
@jonseymour thanks, that's right! I just copy/pasted without thinking.

However, it does still work for me with both `curl -XPOST` and `curl`. I can create a database either way. `Method Not Allowed` is the error `curl` throws when given an invalid method switch:

```
$ curl -i -XPOST http://localhost:8086/query --data-urlencode "q=create database curl"
HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Request-Id: 46978adc-2c50-11e6-b1ee-000000000000
X-Influxdb-Version: 0.13.0
Date: Tue, 07 Jun 2016 01:36:37 GMT
Content-Length: 16

{"results":[{}]}

$ curl -i -XPoST http://localhost:8086/query --data-urlencode "q=create database curl"
HTTP/1.1 405 Method Not Allowed
Allow: OPTIONS, GET, POST
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 07 Jun 2016 01:36:44 GMT
Content-Length: 19

Method Not Allowed
```

**Comment by Buzut** [comment]
@beckettsean 

    # curl -i -XPOST http://localhost:8086/query --data-urlencode "q=create database curl"
    HTTP/1.1 405 Method Not Allowed
    Allow: OPTIONS, GET
    Content-Type: text/plain; charset=utf-8
    X-Content-Type-Options: nosniff
    Date: Tue, 07 Jun 2016 09:06:30 GMT
    Content-Length: 19

    Method Not Allowed

But this works:

    # curl -i -XPOST 'http://localhost:8086/write?db=sensu' --data-binary 'cpu_load,host=mn1 value=0.98 1465290632'
    HTTP/1.1 204 No Content
    Request-Id: e57c89d4-2c8f-11e6-a1a9-000000000000
    X-Influxdb-Version: 0.10.0
    Date: Tue, 07 Jun 2016 09:12:02 GMT

Looks like I'm on 10.0.0 by the way…

**Comment by beckettsean** [comment]
@Buzut the methods changed with InfluxDB 0.13. It is expected that for 0.10 all queries to the `/query` endpoint should be `GET`. Also, it has always been the case that connections to the `/write` endpoint should be `POST` connections.

**Comment by Buzut** [comment]
All right. My bad then… I thought I had a 0.13.

**Comment by jacohend** [comment]
Database creation docs are still incorrect, still specify POST: https://docs.influxdata.com/influxdb/v0.13/guides/writing_data/
