### ISSUE TITLE
SHOW MEASUREMENTS needs any data in default retention policy to work

### ISSUE THREAD

**Issue by pga23** [influxdata/influxdb#6789]
### Bug report

__System info:__ 
- Ubuntu Server 16.04
- InfluxDB 0.13

__Steps to reproduce:__

1. create a new database
2. create a few new retention policies and change one into default
4. remove "default" retention policy
3. write any data in a few measurements to non-default retention policy (default rp must be without data)
4. apply `SHOW MEASUREMENTS`

__Expected behavior:__
List of all created measurements.

__Actual behavior:__
No measurements showed.
but `SELECT * FROM my_rp.my_new_measurement` returns data as expected

__Additional info:__
Tested by using CURL with batch files.
After insert data into default RP, SHOW MEASUREMENTS works as expected.

**Comment by jwilder** [comment]
Not reproducible with latest master

**Comment by AutomationEngineer** [comment]
Could be easily reproduced on my Ubuntu 14.04 and InfluxDB 0.13

> CREATE DATABASE mydb
> USE mydb
Using database mydb
> CREATE RETENTION POLICY rp ON mydb DURATION 5d REPLICATION 1
> INSERT INTO rp measure1 value=0
Using retention policy rp
> INSERT INTO rp measure2 value=1
Using retention policy rp
> SELECT * FROM rp.measure1
name: measure1
--------------
time                    value
1470805821590026522     0

> SELECT * FROM rp.measure2
name: measure2
--------------
time                    value
1470805834717781060     1

> SHOW MEASUREMENTS
> INSERT INTO default dummy value=0
Using retention policy default
> SHOW MEASUREMENTS
name: measurements
------------------
name
dummy
measure1
measure2


Or do you mean Unstable v1.0.0-beta3 behave as expected?

**Comment by AutomationEngineer** [comment]
Just installed 1.0.0-beta3 ... and yes it behave as expected.
