### ISSUE TITLE
Can we do arithmetic in side aggregation functions?

### ISSUE THREAD

**Issue by dengliu** [influxdata/influxdb#6793]
Hello,

Is there a way to do arithmetic in side aggregation functions?
E.g. SELECT SUM(field_a * field_b) FROM my_measurement
I am getting "error parsing query: expected field argument in sum()" when I run the above query

Thank you!

**Comment by jsternberg** [comment]
Not yet. Follow issue #5971 to get notifications when we implement this. Thanks.
