### ISSUE TITLE
Large queries cause entire influxdb to die with out of memory

### ISSUE THREAD

**Issue by forsberg** [influxdata/influxdb#6799]
### Bug report

__System info:__ influxdb 0.13.0-1 (Debian package) on Debian Wheezy AMD64, 48G memory in machine.

InfluxDB is configured with graphite listener that takes input from some 120+ Cassandra machines, as well as collectd listener and Influxd protocol listener. It's a test setup evaluating multiple data sources (Cassandra via yammer/graphite, collectd, telegraf).

The "graphite" database have some 185GiB of data. 

__Steps to reproduce:__

1. Start Influxd with our configuration (See [influxdb.conf.txt](https://github.com/influxdata/influxdb/files/302291/influxdb.conf.txt))
2. Wait until it has started.
3. Wait some 5-10 minutes.
4. Crashes with "out of memory"

Disabling graphite input makes process stable, but then we're not collecting much data, so it's pretty useless :-)

__Additional info:__ [Include gist of relevant config, logs, etc.]

I have tried to fiddle with the   cache-snapshot-write-cold-duration  setting as that seems to be a common fix for memory problems, but setting it to "1m" does not help. 

Attaching pprof files captured a few minutes before crash:

[pprof.influxd.cssa06-16.osp-cassandra.osa:8086.inuse_objects.inuse_space.002.pb.gz](https://github.com/influxdata/influxdb/files/302294/pprof.influxd.cssa06-16.osp-cassandra.osa.8086.inuse_objects.inuse_space.002.pb.gz)
[pprof.influxd.cssa06-16.osp-cassandra.osa:8086.inuse_objects.inuse_space.001.pb.gz](https://github.com/influxdata/influxdb/files/302296/pprof.influxd.cssa06-16.osp-cassandra.osa.8086.inuse_objects.inuse_space.001.pb.gz)
[pprof.influxd.cssa06-16.osp-cassandra.osa:8086.inuse_objects.inuse_space.006.pb.gz](https://github.com/influxdata/influxdb/files/302297/pprof.influxd.cssa06-16.osp-cassandra.osa.8086.inuse_objects.inuse_space.006.pb.gz)
[pprof.influxd.cssa06-16.osp-cassandra.osa:8086.inuse_objects.inuse_space.005.pb.gz](https://github.com/influxdata/influxdb/files/302293/pprof.influxd.cssa06-16.osp-cassandra.osa.8086.inuse_objects.inuse_space.005.pb.gz)
[pprof.influxd.cssa06-16.osp-cassandra.osa:8086.inuse_objects.inuse_space.004.pb.gz](https://github.com/influxdata/influxdb/files/302292/pprof.influxd.cssa06-16.osp-cassandra.osa.8086.inuse_objects.inuse_space.004.pb.gz)
[pprof.influxd.cssa06-16.osp-cassandra.osa:8086.inuse_objects.inuse_space.003.pb.gz](https://github.com/influxdata/influxdb/files/302295/pprof.influxd.cssa06-16.osp-cassandra.osa.8086.inuse_objects.inuse_space.003.pb.gz)

Attaching last 2000 lines of influxd.log showing traceback:

[influxd.last-2000-lines.log.txt](https://github.com/influxdata/influxdb/files/302310/influxd.last-2000-lines.log.txt)

Please let me know how I can help figuring out root cause.

**Comment by jwilder** [comment]
Have you tried UDP for graphite listener?   The panic looks like a bunch of TCP connections were blocked trying to flush their batches.  There was a compaction running that tried to allocate and failed causing the OOM.  That might be fixed by #6567.

Can you test w/ `1.0 beta1` or a current nightly?

**Comment by forsberg** [comment]
I have not tried udp. I got a similar OOM after switching to influx protocol over http. Will try 1.0 beta1.

**Comment by forsberg** [comment]
No, 1.0beta1 with influx over http has same behaviour - it starts compacting, then memory grows out of bounds and it crashes with out of memory. I don't have any pprof or log excerpts available right now, but I'll post them tomorrow.

Any knobs I should turn that could help here? 

I would like to be able to use influx over https with authentication for encryption and security, udp doesn't have that, correct?

**Comment by jwilder** [comment]
What queries are you running?  One from the profiles you attached was using about 8GB of RAM.

From your logs and the profiles, it looks like you have a large number tags or possibly high tag cardinality.  What does `show stats` and `show diagnostics` report?

Can you run `influx_inspect dumptsmdev <path/to/tsm/file>` on the larger files that were listed in the logs just before it OOM'd?  Your logs also have some large series keys which might be bumping your memory usage past your memory limits at times.

**Comment by forsberg** [comment]
OK, new attempt. Slightly different configuration this time:

* influxdb 1.0 beta1 running with stock configuration from .deb - only paths to database changed. 
[influxdb.conf.txt](https://github.com/influxdata/influxdb/files/306267/influxdb.conf.txt)
* Collectd input disabled. 
* Database now much smaller, dropped the large one I had before. Now we're talking some 20GiB of data.
* All writes come in via http (Cassandra writing to local telegraf agent which filters and rewrites the graphite-formatted metrics then sends them to InfluxDB). This data goes into the "cassandra_telegraf" database.
* Disabled my grafana, so no queries except for continuous queries running. [cq.txt](https://github.com/influxdata/influxdb/files/306276/cq.txt)
* Diagnostics: [diagnostics.txt](https://github.com/influxdata/influxdb/files/306278/diagnostics.txt)
* Ran a one-second loop that captured 'show stats'. Results: [stats-20160609.tar.gz](https://github.com/influxdata/influxdb/files/306279/stats-20160609.tar.gz) - the last file taken right before Influx stopped responded due to kernel killing it.
* Ran a one-second loop capturing output of "go tool pprof -proto /usr/bin/influx http://<host>:8086/debug/pprof/heap. Results: [pprof-20160609.tar.gz](https://github.com/influxdata/influxdb/files/306281/pprof-20160609.tar.gz)
* Full log file from start of InfluxDB to it being killed: [stats-20160609.tar.gz](https://github.com/influxdata/influxdb/files/306285/stats-20160609.tar.gz)
* Ran dumptsmdev on the largest tsm file I have (2.1Gb): [dumptsmdev-cassandra_telegraf-default-75-000000076-000000003.tsm.txt](https://github.com/influxdata/influxdb/files/306299/dumptsmdev-cassandra_telegraf-default-75-000000076-000000003.tsm.txt)
* I also see some "write failed for shard 75: engine: cache maximum memory size exceeded"

While I was waiting for the dumptsmdev, I had started influxdb again, but blocked incoming traffic. So it started doing some compaction and then died with OOM and a traceback. Here's the complete log file for when that happened: [influxd.log.no-writes-just-compaction-oom.txt](https://github.com/influxdata/influxdb/files/306306/influxd.log.no-writes-just-compaction-oom.txt)

**Comment by forsberg** [comment]
Removing my continuous queries made InfluxDB stable, but that means I get no downsampling.

**Comment by jwilder** [comment]
@forsberg The panic occurred during a query not a compaction.   There were no compactions running according to the trace.  It looks like the continuous queries goroutine was running and waiting for a query to finish.  That query panic'd when the process OOM'd.

You're stats show you have about 4.6M series with 4.5M in the `cassandra_telegraf` database split between ~2000 measurements.  It's likely that your CQ is querying a very high number of series causing the OOM.  You may need refine the query to reduce how many series are pulled back.  

You could try setting a `max-select-series` to help identify the CQ that is problematic:
```
[coordinator]
  log-queries-after = "10s"
  max-select-point = 0
  max-select-series = 100000
  max-select-buckets = 0
```

`max-select-point` would kill the query if it's pulls back too many points.  `max-select-buckets` would kill the query if a group by created too many intervals.

The `write failed for shard 75: engine: cache maximum memory size exceeded` is because the default cache size is probably too low for your write volume and large series keys.  You can could try increasing the max size and lowering the snapshot size with:
```
[data]
cache-max-memory-size = 1073741824
cache-snapshot-memory-size = 16777216
```

Increasing the max size would allow more data to sit in the cache, but may increase snapshot compaction times.  Lowering the snapshot memory size should trigger more frequent snapshot compactions, hopefully offsetting the larger cache size.  You may need to experiment with these to see what helps or not.

I would also look at the tags you are writing into `cassandra_telegraf` DB and measurements and try to reduce the cardinality of them or remove any tags that don't need.

**Comment by forsberg** [comment]
Right. So root cause found. However, I still think this is a bug as my expectation is that a large query should fail with an error message, not kill the entire influx database process. 

I managed to get rid off the `cache maximum memory size exceeded` by increasing cache-max-memory-size. 

When it comes to my queries, I have worked around the problem by programmatically creating one CQ per measurement, which with the different RPs ended up being some 8000 queries. Will Influxdb be able to keep up with that? Can I monitor if I'm falling behind on CQ execution? The other alternative would be to create one CQ per host monitored, which will be fewer but slower queries.

**Comment by jwilder** [comment]
As of current nightlies, you can set a number of limits to cause a large query to be aborted automatically:

```
[coordinator]
  max-concurrent-queries = 0
  query-timeout = "0"
  log-queries-after = "0"
  max-select-point = 0
  max-select-series = 0
  max-select-buckets = 0
```

* `max-concurrent-queries` - limits the number of simultaneous queries that can run at once.  New queries are a rejected until an in-progress one completes.
* `query-timeout` - Kills a query after it has been running longer than some duration
* `log-queries-after` - Logs any queries that have been running longer than some duration
* `max-select-points` - Kills a query after it has select more than some number of values
* `max-select-series` - Kills a query if it would select from more than some number of series
* `max-select-buckets` - Kills a query if would create more than a configured number of group by buckets

**Comment by QuantDevRO** [comment]
Hi,
I'm using the Flux to query the data from Chronograf, and I applied the settings below:

[coordinator]
 query-timeout = "1ns"

All the influxQL queries got blocked. But the Flux query will run for a long time and return a result. May I know if there's a setting to limit the flux query time as well?
