### ISSUE TITLE
Add support for custom functions

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#68]
User should be able to define custom functions written in Lua like in Redis. This will require the addition of a few new endpoints:

```bash
# add a function
curl -X POST http://localhost:8086/db/foo/functions -d \
 '{"name": "square", "arg_count": 1, "map": "...", "reduce": "..."}'

# list functions
curl http://localhost:8086/db/foo/functions

# remove function
curl -X DELETE http://localhost:8086/db/foo/functions/:name

# update function
curl -X PUT http://localhost:8086/db/foo/functions/:name -d '{...}'
```

The name must be alphanumeric or with underscores. The arg count lets us know how many arguments the function takes. The map and reduce arguments are the Lua scripts to run the associated phases of the query.

We'll have to figure out the most efficient way to marshal and unmarshal the data between Go and Lua. That will inform what the underlying API will look like in Lua for writing these scripts.

**Comment by majj** [comment]
+1

**Comment by allertec** [comment]
+1

**Comment by madazone** [comment]
+1

**Comment by lxcid** [comment]
+1

**Comment by inthecloud247** [comment]
+1

**Comment by tobiemh** [comment]
+1

**Comment by thancock14** [comment]
+1

**Comment by bechtoldt** [comment]
+1

**Comment by stephanbuys** [comment]
+1

**Comment by srini-raju** [comment]
+1

**Comment by ruiqi** [comment]
+1

**Comment by nathholf** [comment]
+1

**Comment by TheFlyingCorpse** [comment]
+1

**Comment by cloud-rocket** [comment]
+1

**Comment by timgriffiths** [comment]
+1

**Comment by yuankui** [comment]
+1

**Comment by padcom** [comment]
I have a case where the value of pressure stored in the database is an absolute value as retrieved from the sensor. It'd be a perfect case for a custom function to be able to translate that value to sea-level.

+1

**Comment by toddboom** [comment]
Support for UDFs (User-Defined Functions) will be released within [Kapacitor](https://github.com/influxdata/kapacitor) for the v0.10.0 release in the next couple weeks. It's unlikely that InfluxDB itself will ever re-implement this functionality, so I'm closing this out.

**Comment by yuankui** [comment]
I am forced to use influxdata family...
though I don't think UDFs in Kapacitor will solve the performance problem

**Comment by cxreg** [comment]
this strikes me as a particularly odd "resolution".  kapacitor is just a client of influxdb, correct?

**Comment by mitar** [comment]
The discussion moved here: #6891

Or maybe this issue should just be reopened? It is really strange. It seems this is one of the most wanted features? And it is not even on a roadmap? @beckettsean? @pauldix?
