### ISSUE TITLE
Graphite input dropping on restart

### ISSUE THREAD

**Issue by unixninja92** [influxdata/influxdb#6800]
### Bug report

**System info:** 
Influx 0.13.0
Amazon linux 2016.3.0

**Steps to reproduce:**
1. Start influx in an auto scaling group behind an elb listening for graphite on 2003
2. Start sending graphite input to influx via jmxtrans-agent
3. Restart influxdb
4. influx stops receiving graphite from jmxtrans-agent even though jmxtrans-agent continues to sucessfully send tcp
5. restart jmxtrans-agent to fix

**Expected behavior:**
Influx should continue to receive graphite input.

**Actual behavior:** 
Influx stops receiving graphite input. Jmxtrans-agent continues to successfully send tcp packets of graphite input to the influx elb/instance. This data never gets in the influx database. After restarting jmxtrans-agent, it works again. 

graphite config:
https://gist.github.com/unixninja92/f9e084520e16e2b0c59f074cadfc7a1e

**Comment by jwilder** [comment]
Have you tested w/o the ELB in middle of the request path?  Is the ELB failing health checks and removing the influx server from the available nodes after restart?  Are there any errors in the influx logs?

**Comment by dgnorton** [comment]
Closing since no response in over two years.
