### ISSUE TITLE
binary should have a --version flag

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6804]
### Feature Request

__Proposal:__ 

`influxd --version` outputs the version string for the binary.

__Current behavior:__

```
# influxd --version
flag provided but not defined: -version

# influxd -version
flag provided but not defined: -version

# influxd --v
flag provided but not defined: -v

# influxd -v
flag provided but not defined: -v
```

__Desired behavior:__ 
Should be analogous to the `influx` switch
```
# influx -version
InfluxDB shell version: 0.13.0
```

E.g.

```
# influxd -version
InfluxDB daemon version: 0.13.0
```

__Use case:__ 
Without this flag, the `influxd` binary must be running in order to determine the version of InfluxDB installed.

**Comment by jwilder** [comment]
It's currently a sub-command 
```
# influxd version
InfluxDB v0.13.0 (git: 0.13 e57fb88a051ee40fd9277094345fbd47bb4783ce)
```

**Comment by beckettsean** [comment]
Thanks, Jason, I'm in the process of opening another issue regarding the incomplete CLI help for the command. I'll mention this as an example.

**Comment by beckettsean** [comment]
https://github.com/influxdata/influxdb/issues/6805
