### ISSUE TITLE
influxd binary needs better command-line parameter help

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6805]
### Feature Request

__Proposal:__ [Description of the feature]

Calling `influxd` with an unrecognized switch should point users to the `influxd help` subcommand. 

Also, the current list of switches/flags is partially incorrect.

__Current behavior:__ [What currently happens]

```
# influxd -help
usage: run [flags]

run starts the InfluxDB server. If this is the first time running the command
then a new cluster will be initialized unless the -join argument is used.

        -config <path>
                          Set the path to the configuration file.

        -hostname <name>
                          Override the hostname, the 'hostname' configuration
                          option will be overridden.

        -pidfile <path>
                          Write process ID to a file.

        -cpuprofile <path>
                          Write CPU profiling information to a file.

        -memprofile <path>
                          Write memory usage information to a file.

run: flag: help requested
```

To get the subcommands you must run `influxd help`, no flag:

```
# influxd help
Configure and start an InfluxDB server.

Usage:

	influxd [[command] [arguments]]

The commands are:

    backup               downloads a snapshot of a data node and saves it to disk
    config               display the default configuration
    restore              uses a snapshot of a data node to rebuild a cluster
    run                  run node with existing configuration
    version              displays the InfluxDB version

"run" is the default command.

Use "influxd help [command]" for more information about a command.

```

__Desired behavior:__ [What you would like to happen]

The above switch output mentions `-join`, which in the post 0.12 world is likely deprecated or removed. It also doesn't mention the `help` command, which is the only way to find out about subcommands like `version` or `backup`.

__Use case:__ [Why is this important (helps with prioritizing requests)]

It's impossible to remember every switch and flag to every binary, and naive POSIX users like me rely on being able to get a reminder output from the binary with something like `influxd -?` or `influxd --help`. I get output from those that is incomplete, because instead I must run `influxd help`, which isn't mentioned in the seemingly complete output from `influxd -?`

**Comment by jsternberg** [comment]
I implemented this in a PR, but I would like us to consider using something other than Go's default command line parser in the future. I'm of the opinion that the Go command line parser is very user unfriendly since it uses almost no established standard and instead sets a new standard. The Docker project did something similar when they started getting towards 1.0.

**Comment by mark-rushakoff** [comment]
@jsternberg You're right that the Go flag parser is nonstandard, [as Rob Pike pointed out](https://groups.google.com/d/msg/golang-nuts/3myLL-6mA94/VUkLtSOyS-YJ):

> As the author of the flag package, I can explain [why the Go flag package uses a different convention to the traditional Unix command line flags]. It's loosely based on Google's flag package, although greatly simplified (and I mean greatly). I wanted a single, straightforward syntax for flags, nothing more, nothing less.

I'd be thrilled if we could get on Unix style flags, but is that a breaking change? Can we do that before 1.0 final?

**Comment by jsternberg** [comment]
We can do what Docker did and accept both, but it's more work than I'd like at the moment which is why I haven't done it. I'll mess around with it in my free time to see how difficult it would be.

**Comment by jsternberg** [comment]
The problems mentioned in this issue were fixed with a couple of different PRs. One of them is #6811. I think there are a few other PRs that fixed the help messages and made the formatting consistent, but I can't find the exact PR numbers.

**Comment by jsternberg** [comment]
Also #7052 has an implementation for switching our binaries to use posix flags.
