### ISSUE TITLE
All data tombstoned in database after dropping measurement.

### ISSUE THREAD

**Issue by subhachandrachandra** [influxdata/influxdb#6814]
We are running InfluxDb 0.12.2 and the exact code can be found in our clone at "https://github.com/aristanetworks/influxdb". The only local changes in the repo are in the Arista directory which contain custom packing scripts.
Linux influx101.sjc.aristanetworks.com 4.1.10-200.fc22.x86_64 #1 SMP Mon Oct 5 14:22:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

   We dropped a measurement on June 2nd around 11:00pm and noticed shortly thereafter that no data was being returned by queries to Influxdb. "show measurements" did not show anything either. When we looked at the data directory we saw tombstones in all the sub directories. We saw a couple of tombstones for that time period but also for all the other data with the same timestamp of June 2nd 21:40. Looking at our logs from around the time, we see that a measurement was dropped and shortly thereafter a level2 compaction started and see errors about data being tombstoned from then on. We renamed all the tombstone files and the data was accessible after that. The current state of the data directory is copied below including the renamed tombstone files. Could this be a bug in "drop measurement" or a race between the drop stmt and compaction?

Jun 02 21:40:10 influx101.sjc.aristanetworks.com influxd[10328]: [httpd]2016/06/02 21:40:10 172.24.0.68 - - [02/Jun/2016:21:40:10 -0700] POST /write?consistency=&db=ServerStats&precision=s&rp=default HTTP/1.1\
 204 0 - InfluxDBClient 411de0e8-2945-11e6-89d6-000000000000 4.548135ms
Jun 02 21:40:10 influx101.sjc.aristanetworks.com influxd[10328]: [httpd]2016/06/02 21:40:10 172.20.62.4 - - [02/Jun/2016:21:40:10 -0700] POST /write?consistency=&db=ServerStats&precision=s&rp=default HTTP/1.1\
 204 0 - InfluxDBClient 4120a802-2945-11e6-89d8-000000000000 3.35641ms
Jun 02 21:40:10 influx101.sjc.aristanetworks.com influxd[10328]: [httpd]2016/06/02 21:40:10 172.20.60.6 - - [02/Jun/2016:21:40:10 -0700] POST /write?consistency=&db=ServerStats&precision=s&rp=default HTTP/1.1\
 204 0 - InfluxDBClient 4176baab-2945-11e6-89d9-000000000000 3.649095ms
Jun 02 21:40:11 influx101.sjc.aristanetworks.com influxd[10328]: [query] 2016/06/02 21:40:11 DROP MEASUREMENT cpu_load_short
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 beginning level 2 compaction of group 0, 1 TSM files
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 compacting level 2 group (0) /persist/influxdb/data/data/ServerStats/default/85/000000041-000000002.tsm (#0)
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 error compacting TSM files: init: read tombstones: EOF
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 beginning full compaction of group 0, 1 TSM files
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 compacting full group (0) /persist/influxdb/data/data/ServerStats/default/76/000000040-000000004.tsm (#0)
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 error compacting TSM files: init: read tombstones: EOF
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 beginning level 2 compaction of group 0, 1 TSM files
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 compacting level 2 group (0) /persist/influxdb/data/data/ServerStats/default/141/000000142-000000002.tsm (#0)
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 error compacting TSM files: init: read tombstones: EOF
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 beginning full compaction of group 0, 1 TSM files
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 compacting full group (0) /persist/influxdb/data/data/ServerStats/default/28/000000020-000000004.tsm (#0)
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 error compacting TSM files: init: read tombstones: EOF
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [httpd]2016/06/02 21:40:12 ::1 - - [02/Jun/2016:21:40:11 -0700] GET /query?db=ServerStats&epoch=ns&q=drop+measurement+cpu_load_short HTTP/1.1 2\
00 40 - InfluxDBShell/0.9 421a8d18-2945-11e6-89da-000000000000 267.927725ms
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [httpd]2016/06/02 21:40:12 172.20.58.8 - - [02/Jun/2016:21:40:12 -0700] POST /write?consistency=&db=ServerStats&precision=s&rp=default HTTP/1.1\
 204 0 - InfluxDBClient 423b9d13-2945-11e6-89db-000000000000 52.858123ms
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 beginning level 2 compaction of group 0, 1 TSM files
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 compacting level 2 group (0) /persist/influxdb/data/data/ServerStats/default/2/000000005-000000002.tsm (#0)
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 error compacting TSM files: init: read tombstones: EOF
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 beginning level 3 compaction of group 0, 1 TSM files
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 compacting level 3 group (0) /persist/influxdb/data/data/ServerStats/default/68/000000034-000000003.tsm (#0)
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 error compacting TSM files: init: read tombstones: EOF
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 beginning level 2 compaction of group 0, 1 TSM files
Jun 02 21:40:12 influx101.sjc.aristanetworks.com influxd[10328]: [tsm1] 2016/06/02 21:40:12 compacting level 2 group (0) /persist/influxdb/data/data/ServerStats/default/4/0000

[root@influx101 data]# ls -l ServerStats/default/*
ServerStats/default/101:
total 31548
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000039-000000003.tmb
-rw-r--r-- 1 influxdb influxdb 32297606 May  2 16:59 000000039-000000003.tsm

ServerStats/default/109:
total 403116
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000214-000000003.tmb
-rw-r--r-- 1 influxdb influxdb 412780196 May  9 17:00 000000214-000000003.tsm

ServerStats/default/117:
total 467564
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000240-000000005.tmb
-rw-r--r-- 1 influxdb influxdb 478775847 May 16 17:00 000000240-000000005.tsm

ServerStats/default/12:
total 14896
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000021-000000002.tmb
-rw-r--r-- 1 influxdb influxdb 15248446 Feb 15 16:01 000000021-000000002.tsm

ServerStats/default/125:
total 471404
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000240-000000006.tmb
-rw-r--r-- 1 influxdb influxdb 482705590 May 23 17:00 000000240-000000006.tsm

ServerStats/default/133:
total 476476
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000241-000000002.tmb
-rw-r--r-- 1 influxdb influxdb 487904232 May 30 17:00 000000241-000000002.tsm

ServerStats/default/141:
total 489920
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000096-000000006.tmb
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000128-000000005.tmb
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000132-000000003.tmb
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000136-000000003.tmb
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000140-000000003.tmb
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000142-000000002.tmb
-rw------- 1 influxdb influxdb         4 Jun  2 21:40 000000143-000000001.tmb
-rw------- 1 influxdb influxdb        44 Jun  2 23:01 000000144-000000001.tmb
-rw------- 1 influxdb influxdb        44 Jun  2 23:01 000000145-000000001.tmb
-rw-r--r-- 1 influxdb influxdb 501635648 Jun  6 17:00 000000250-000000002.tsm

ServerStats/default/150:
total 170756
-rw-r--r-- 1 influxdb influxdb 169208292 Jun  7 20:51 000000080-000000006.tsm
-rw-r--r-- 1 influxdb influxdb   5643178 Jun  7 22:06 000000082-000000002.tsm

ServerStats/default/2:
total 3192
-rw------- 1 influxdb influxdb       4 Jun  2 21:40 000000005-000000002.tmb
-rw-r--r-- 1 influxdb influxdb 3262951 Feb  1 16:01 000000005-000000002.tsm

ServerStats/default/20:
total 13892
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000020-000000002.tmb
-rw-r--r-- 1 influxdb influxdb 14218087 Feb 22 16:01 000000020-000000002.tsm

ServerStats/default/28:
total 15336
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000020-000000004.tmb
-rw-r--r-- 1 influxdb influxdb 15696458 Feb 29 16:01 000000020-000000004.tsm

ServerStats/default/36:
total 15464
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000021-000000004.tmb
-rw-r--r-- 1 influxdb influxdb 15827973 Mar  7 16:02 000000021-000000004.tsm

ServerStats/default/4:
total 14580
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000021-000000002.tmb
-rw-r--r-- 1 influxdb influxdb 14923650 Feb  8 16:01 000000021-000000002.tsm

ServerStats/default/44:
total 15476
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000021-000000002.tmb
-rw-r--r-- 1 influxdb influxdb 15842753 Mar 14 17:02 000000021-000000002.tsm

ServerStats/default/52:
total 15984
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000021-000000002.tmb
-rw-r--r-- 1 influxdb influxdb 16361150 Mar 21 17:02 000000021-000000002.tsm

ServerStats/default/60:
total 21656
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000031-000000002.tmb
-rw-r--r-- 1 influxdb influxdb 22168141 Mar 28 17:02 000000031-000000002.tsm

ServerStats/default/68:
total 25648
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000034-000000003.tmb
-rw-r--r-- 1 influxdb influxdb 26256973 Apr  4 17:02 000000034-000000003.tsm

ServerStats/default/76:
total 34032
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000040-000000004.tmb
-rw-r--r-- 1 influxdb influxdb 34843470 Apr 11 17:02 000000040-000000004.tsm

ServerStats/default/85:
total 31684
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000041-000000002.tmb
-rw-r--r-- 1 influxdb influxdb 32436303 Apr 18 17:01 000000041-000000002.tsm

ServerStats/default/93:
total 31460
-rw------- 1 influxdb influxdb        4 Jun  2 21:40 000000041-000000002.tmb
-rw-r--r-- 1 influxdb influxdb 32210539 Apr 25 17:01 000000041-000000002.tsm
[root@influx101 data]# 

Subhachandra

**Comment by jwilder** [comment]
There are were some issues related tombstone files not being able to be loaded that were fixed in #6524 which is in `0.13`.

There is still a race related to deletes and compactions that is not fixed yet.

**Comment by jwilder** [comment]
Fixed via #6671
