### ISSUE TITLE
INNER JOIN or SELECT IN 

### ISSUE THREAD

**Issue by mrcheidel** [influxdata/influxdb#6816]
Hello everyboy
I read about the INNER JOIN between measurements it's no longer supported.
Anybody could be help me? I like know how to filter points for grouds of tag fields:
I need get al points from an measurements where the tag username is in other meas. called suer 

i.e. 1

select a.value1, a.value2 from measurement1 as a inner join groupname b on a.username in (b.username)

i.e. 2
I have a measurement called usergroups with 2 values, usernames and groupname

select a.* from measurement1 a where a.username in (select username from usergroups where groupname = 'mygroup' )  

I found work arround with regexp

select * from measurement1 where userid =~ /^userid1$|^userid2$/ 

But this ins't a good solution, I could be have more than 1000 users in every group.

thanks of lot
Claudio

**Comment by beckettsean** [comment]
You cannot use any data from one measurement as a criteria for querying another measurement. You must construct your schema so that the data is in one measurement.
