### ISSUE TITLE
show tag values - drastically decreased performance on v0.13

### ISSUE THREAD

**Issue by ekini** [influxdata/influxdb#6817]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

1. Centos 7
2. influxdb v0.10.3 and v0.13.0

__Steps to reproduce:__

1. Upgrade from v0.10.3 to v0.13.0
2. Run "show tag values from cpu WITH KEY = host"

__Expected behavior:__ 
Query runs for reasonable time
```
$time influx -database telegraf -execute "show tag values from cpu WITH KEY = host" > /dev/null

real	0m0.106s
user	0m0.017s
sys	0m0.008s
```
(this is on v.0.10.3)
__Actual behavior:__
```
$time influx -database telegraf -execute "show tag values from cpu WITH KEY = host" > /dev/null

real	0m10.514s
user	0m0.018s
sys	0m0.006s
```
(this is on v.0.13.0)
__Additional info:__ 

I have around 3k hosts.
What I did:
1. Backuped meta storage with influxd backup
2. Upgraded influxdb to 0.13.0
3. Restored meta

I use this query in a template variable query in grafana, so dashboard now loads for 10-13 seconds instead of 0.1s.

**Comment by zstyblik** [comment]
Duplicate of https://github.com/influxdata/influxdb/issues/6233?

**Comment by martinseener** [comment]
Already fixed with https://github.com/influxdata/influxdb/pull/6792?

**Comment by ekini** [comment]
Oops,  it should be it, thanks!
