### ISSUE TITLE
Can show tag values support INTO clause

### ISSUE THREAD

**Issue by deepujain** [influxdata/influxdb#6818]
My table: 

> select count(eId) from epdetail
name: epdetail
--------------
time			count
1970-01-01T00:00:00Z	96920

only 96,920 rows (which is very small) when compared to millions of rows that are supported.

show tag values from epdetail1 with key=experimentId  takes more than 12 seconds. Is this expected ?

Currently above query runs on Grafana dashboard and i cannot have it run each time dashboard loads as it slows down the load of dashboard. Hence if #1 query can support INTO clause i can have a simple select query run each time (as this query will be fast) dashboard loads.

**Comment by e-dard** [comment]
Can you provide more detail please, as outlined in the Issue template?

**Comment by jsternberg** [comment]
`SHOW TAG VALUES` performance should be improved at the moment. If this is still an issue, please comment with more information so we can address performance issues. Thanks.
