### ISSUE TITLE
Database unresponsive after DROP MEASUREMENT

### ISSUE THREAD

**Issue by lpalm** [influxdata/influxdb#6819]
### Bug report

__System info:__ Fedora release 22, InfluxDB version 0.13.0

__Steps to reproduce:__

1. Drop a measurement via HTTP
2. Try to write to the database before the DROP MEASUREMENT call returns

__Expected behavior:__ The measurement gets deleted. Everything continues working.

__Actual behavior:__ The HTTP request to delete the measurement often times out after **300** seconds. The entire database is unresponsive while deleting measurements.

We have a use case where measurements need to be periodically deleted. I understand this is not what InfluxDB is optimized for, but cleaning up data and updating measurements is both a legitimate use case and one that is listed in the public API (so presumably supported). How can I delete a measurement completely without rendering the database inoperable for several minutes? We can insert upwards of 100k points/second so not being able to insert for prolonged periods of time can cause significant, contiguous chunks of data to be lost.
The timing of the deletion here isn't super important, we're happy to do it over many hours if need be as long as the database doesn't stop responding to writes for several minutes at a time.

Thanks.

**Comment by e-dard** [comment]
@lpalm thanks for the report. Some profiles would be useful during the `300 seconds` when you're waiting on deleting a measurement and trying to write points. Could you provide `blocking` and `goroutine` profiles?

A simple way to do that is, drop the measurement, try and do some writes, and while everything seems tied up, run:

```
curl -o block.txt "http://localhost:8086/debug/pprof/block?debug=1"
curl -o goroutine.txt "http://localhost:8086/debug/pprof/goroutine?debug=1"
```

**Comment by lpalm** [comment]
Sure, @e-dard . Here you go. I took two batches in case that's more helpful. Attached.
[block_and_goroutine.zip](https://github.com/influxdata/influxdb/files/323320/block_and_goroutine.zip)
