### ISSUE TITLE
[Feature Request] Add retention policy to each Graphite template

### ISSUE THREAD

**Issue by sbengo** [influxdata/influxdb#6827]
Hi,

As the same example on #5655, we have different metrics with different retentions (by default, metrics are sent/recieved each 1m and some of them are at 5m).

After the release of the feature asked on the attached issue, it is a first solution (we are so glad to having this), but it requires to us to set a external soft to control the port of the input metrics or directly change the agent configuration (impossible due to the huge number of host with the installed agent).

Therefore, I want to ask if it's possible make a feature that allows us to set the retention policy in every row on the graphite's config section. If it is not set, they will use the default retention policy set on the config.

As an example:

```
[[graphite]]
   enabled = true
   ...
   templates = [
     # filter + template 
     "*.app.other.* env.service.resource.measurement",

     # filter + template + RP1
     "*.app.1m.* env.service.resource.measurement rp_1m",

     # filter + template + RP2
     "*.app.5m.* env.service.resource.measurement rp_5m",
 ]
```

It will be a good approach to the Graphite's retention behaivor!

Thanks for all!

**Comment by toni-moreno** [comment]
+1
