### ISSUE TITLE
memory consumption after error compacting TSM files

### ISSUE THREAD

**Issue by wqtty** [influxdata/influxdb#6828]
### Bug report

__System info:__ [Include InfluxDB version 0.13.0, operating system name CentOS 6.5, and other relevant details]

__Steps to reproduce:__

the influxd will consume all the memory(literally) of the machine it dwells in when this error message shows up:
`error compacting TSM files: key 'cpu,async=true#!~#idle' exceeds max index entries: 91761 > 65535`

**Comment by jwilder** [comment]
This should be fixed in 1.0beta release.
