### ISSUE TITLE
Feature Request - Continuous Query stats into influx

### ISSUE THREAD

**Issue by balopat** [influxdata/influxdb#6830]
### Feature Request - Continuous Query stats into influx

**Proposal:** CQ's are scheduled jobs. It would be useful to have stats in the **_internal** database about them, including: 
- query time - so that we can spot any trending behaviour 
- failure events - so that we can assess the health of the CQ

**Current behavior:** Currently the only way to assess the situation is by looking at the logs of the continuous_querier and grepping on the name of the CQ, but latency info is not even in the logs. 

**Desired behavior:** This would be an opt-in feature, configurable per instance. The continuous_querier would maintain statistics about each continuous query, in the _internal database, **continouous_queries** measurement, tag keys would be cq_name, db_name, fields: execution_time, result, where execution_time is the execution time in milliseconds, result is a 0 in case of success, 1 in case of error. 

**Use case:** Query performance analsyis, system tuning, alerting, instead of shipping the influxdb logs to somewhere else, the whole analyis could be done out of box. 

Note: this might overlap with https://github.com/influxdata/influxdb/issues/4898, but CQ's are a bit different, as they are named entities.

**Comment by dstreppa** [comment]
+1 
Another status case (2) should be missing data for the CQ calculation

**Comment by jacktang** [comment]
We also want to measure the performance of CQs.
