### ISSUE TITLE
Continuous Query from multiple series

### ISSUE THREAD

**Issue by shannonliu0809** [influxdata/influxdb#6831]
### Feature Request
__Proposal:__ Continuous query (CQ) should be able to aggregate from different series. for example,
we have data from phone sensor information, such as proximeter, GPS, etc., we would like to combine the data from proximeter and GPS together. 

__Current behavior:__ currently, CQ can only aggregate from a single series

__Desired behavior:__ we need the CQ to be able to pull data fields from different series and aggregate them to form a single row

__Use case:__ this would help talking to other databases that have different data model. if CQ can aggregate from multiple series, we can map the InfluxDB series to other databases in the InfluxDB level. Restructuring of influxdb will be much easier.

**Comment by jsternberg** [comment]
@shannonliu0809 can you expand on what you mean by series? Do you mean from multiple sources? Can you show an example of what kind of inserts you would do and what kind of continuous query you would like to create?

**Comment by shannonliu0809** [comment]
Say I have 2 series: GPS and Weather
**GPS** has the following fields: Longitude, Latitude
**Weather** has the following fields: WindSpeed, WindDirection

both of them are writing record every 1 second.

I would like to create a continuous query called **weather_GPS** that take the mean of Longitude, Latitude, WindSpeed, WindAngle for every 15 seconds.

this would allow our database to map more closely to the other existing databases. Database restructuring will also be easier to handle.

**Comment by jsternberg** [comment]
Ok, the words for that are measurements, not series. A series is a unique combination of a measurement and a group of tag keys and values. Series within the same measurement can already be defined.

I think what you're looking for is similar to #3552 and probably requires a new feature which we might call `JOIN` (but we haven't specced it out yet). It would involve some way to combine data from different measurements. Am I getting this correct?

Thanks.

**Comment by shannonliu0809** [comment]
Yes, it is very similar to that request but applied to continuous query, and sorry for the confusion on series/measurement.

**Comment by e-dard** [comment]
@shannonliu0809 I'm going to close this issue, but please feel free to open up a specific feature request issue.
