### ISSUE TITLE
Please provide a way to verify a user password

### ISSUE THREAD

**Issue by babilen5** [influxdata/influxdb#6837]
### Feature Request

There is currently no way to explicitly test if a user password is the same as a given string. This makes it impossible to write code to programmatically manage InfluxDB users for tools such as Saltstack, Ansible, Puppet, ...

One approach would be to simply try to authenticate with a given `user` / `password` credential pair and interpret failure to do so as "password is different". Unfortunately this doesn't allow us to verify a password if the service is still running with `auth-enabled = false` as authentication will always succeed in that case.

**Comment by jsternberg** [comment]
Similar to #4904, but this is more explicit and probably will work better. A returned hash with `SHOW USERS` would likely include a salt that would be a security hazard to reveal as part of `SHOW USERS`, so this wouldn't reveal that information.

**Comment by babilen** [comment]
Yeah, I was simply thinking of a `test_credentials → Bool` kind of function that works regardless of the `auth-enabled` setting.

**Comment by smunier01** [comment]
A few month ago, for our personal use, I added a `SHOW USER "name"` query and a `SHOW USER "name" WITH PASSWORD 'pwd'`query that returns the user if the password is correct. 

If that satisfy your requirements (and nobody has a simpler way) , I could clean it up and send a pull request.

@babilen @jsternberg
