### ISSUE TITLE
Feature Request: Permissions based on Tags

### ISSUE THREAD

**Issue by bischofs** [influxdata/influxdb#6838]
### Feature Request

__Proposal:__ 

A way limit read/write access by tags and fields for users in the database

__Current behavior:__

I think currently you can only limit based on databases 

__Use case:__ 

Our solution has some very important metadata in the tags - being able to use these as filters for who can access the data seems like a common case.

**Comment by jwilder** [comment]
This is a feature we have planned as part of our Enterprise offering.
