### ISSUE TITLE
New nightly build URL not accessible by Ansible due to SNI

### ISSUE THREAD

**Issue by recurser** [influxdata/influxdb#6844]
### Directions

Ansible fails to install packages from dl.influxdata.com with a security error because it uses [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication). Versions of python prior to 2.7.9 don't support ansible downloads over SNI, and the default in ubuntu is 2.7.6.

I've spent most of today trying to update python versions and trying other alternative fixes without success. I'm hosting the package myself for now, but it would make automating installs much easier in the future if the download domain was hosted over non-SNI SSL. 

Is this a possibility?

**Comment by rossmcdonald** [comment]
We currently rely on AWS CloudFront (which uses SNI) for hosting of the dl.influxdata.com domain, so I don't think there's a way to disable it from that side. As a workaround, you can use the S3 links directly (which doesn't use SNI) by prepending `s3.amazonaws.com` to any link. For example, the nightly DEB package can be found here:

https://s3.amazonaws.com/dl.influxdata.com/influxdb/nightlies/influxdb_nightly_amd64.deb

We will most likely migrate away from CloudFront in the future, but, for now, I'd recommend just using the S3 links directly.

**Comment by recurser** [comment]
Thanks @rossmcdonald, the direct S3 link works great 👍
