### ISSUE TITLE
tool to merge config files on upgrade

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6852]
### Feature Request

__Proposal:__ [Description of the feature]
A better way to merge the existing production configuration with the new config in the latest version. 

__Current behavior:__ [What currently happens]
Right now we tell users to manually merge their existing config with a new all-defaults [generated config](https://docs.influxdata.com/influxdb/v0.13/administration/config/#using-configuration-files). There are no tools to help understand what config options are new, what have been dropped, and what are changed. Over time this leads to config files with lots of cruft but no one knows for sure what's cruft, what's a default, and what's critical.

__Desired behavior:__ [What you would like to happen]
Ideally an editor-integrated diff tool, but that's probably too ambitious to start.

As a first step, I propose that the generated configuration highlight which config options are new, which have been altered, and which have been removed from the prior version. That would make it easier for someone merging to know what to do.

For example, here's the partial output of the sample config on 0.13:

```
$ influxd config
reporting-disabled = false
bind-address = ":8088"
hostname = ""
join = ""

[meta]
  dir = "/var/lib/influxdb/meta"
  retention-autocreate = true
  logging-enabled = true
  pprof-enabled = false
  lease-duration = "1m0s"

[data]
  dir = "/var/lib/influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/wal"
  wal-logging-enabled = true
  query-log-enabled = true
  cache-max-memory-size = 524288000
  cache-snapshot-memory-size = 26214400
  cache-snapshot-write-cold-duration = "1h0m0s"
  compact-full-write-cold-duration = "24h0m0s"
  max-points-per-block = 0
  data-logging-enabled = true
```

Which are the new options? If I see an option in my old file and not here, can I just delete it? Where can I go for help with this file?

I believe that we're using some tool that outputs the sample config, but obviously it's very different from the commented sample that ships with the package. Given the way the installers work, users may or may not have the new sample config, so this generated one should be the primary source of truth, I think. As such, it needs some comments and handholding for the user.

__Use case:__ [Why is this important (helps with prioritizing requests)]

This will make the upgrade process more pleasant and less error prone, leading to fewer support issues and a more positive impression on system maintainers.

**Comment by jsternberg** [comment]
@beckettsean I have no idea if this works for what you need, but `influxd config` will read the previous configuration file and modify the defaults. So if your config isn't in a default location, you can do this:

```
influxd config -config influxdb.conf > influxdb.conf.new
mv influxdb.conf.new influxdb.conf
```

(do not write the output file to the file you are reading from otherwise it will erase your configuration file)

One downside is apparently we validate the config file that is read from `-config`, so the configuration file has to be valid for this technique to work.

**Comment by beckettsean** [comment]
@jsternberg I think that method will still move forward the removed config settings, won't it?

**Comment by beckettsean** [comment]
@gunnaraasen this is a good one for the tooling projects

**Comment by jwilder** [comment]
This is something that should be handled the package installation automatically.
