### ISSUE TITLE
Docker run tutum/influxdb:0.12, I got a invalid argument error

### ISSUE THREAD

**Issue by willstudy** [influxdata/influxdb#6854]
when I run this command :
<pre><code>
docker run -d -p 8083:8083 -p 8086:8086 tutum/influxdb:0.12
</code></pre>
And I got this error :
<pre><code>
docker: Error response from daemon: mkdir /home/work/docker/runtime_1.11/overlay/960dc97f7b22c306116ac59e34325b3642e21f792cd102f5b706429cd4d0c01a-init/merged/dev/shm: invalid argument.
See 'docker run --help'.
</code></pre>
Can someone help me?? Thanks very much!!!!

**Comment by jsternberg** [comment]
Hello @willstudy, the tutum image is made by a third-party and isn't officially supported by us. You can either ask them for help at tutumcloud/influxdb or you can try using one of the official docker images made by us.

Your error though seems to be related to docker and not to any specific image. Are you able to run any other image?

**Comment by jsternberg** [comment]
I'm going to close this since it isn't directly related to influxdb. If you respond, I'll try to see where to direct you. There's also the influxdata/influxdata-docker repository for any issues specific to the docker images that are officially supported by influxdb.

Thanks!

**Comment by willstudy** [comment]
it's ok when I  run other images, I will try the official influxdb image .  Thank you @jsternberg
