### ISSUE TITLE
Replication is not working in InfluxDB 0.11

### ISSUE THREAD

**Issue by mohan111raj** [influxdata/influxdb#6857]
Hi,

I've created a cluster with 3 nodes (3 meta & 3 data). I tried to create a DB in the cluster from client machine and I noticed that the **DB is created on one node but not on other two.** 

And then I created a table in the new DB and inserted some records into that table. When I checked in the other two node's default _internal DB it has the newly created table but with no records.

I am really confused how influx DB handles the replication here. 

Also, When I kept the hinted-handoff it acts completely strange. For example, I have created a table in the default _internal DB and inserted some 5000 records from client server. When I checked the record count in all three nodes node 1 has 1678, node 2 has 3338 and node 3 has 1662 records in the table.

So, how is the hinted-handoff works here?

Please help me to setup the clustering with replication enabled.

Thanks in advance..

**Comment by jsternberg** [comment]
Hello @mohan111raj,

We no longer support clustering in the open source version and the last clustering release (0.11, the one you are using) didn't have clustering in a working state yet, so there are likely many bugs in that version. Clustering is now part of our closed source offering. Right now, the only way to get clustering is through [InfluxCloud](https://cloud.influxdata.com/), but there is an early access for the enterprise offering that you can read about [here](https://influxdata.com/blog/influxdb-week-in-review-june-13-2016/).

Sorry that you weren't able to get it working. If you are only using clustering for high availability, we did release a tool called the [relay](https://docs.influxdata.com/influxdb/latest/high_availability/relay/) that you can use with the open source offering to get high availability.

**Comment by mohan111raj** [comment]
Hi jsternberg,

Thanks for your response.

I am now testing the aptness of influxDB in our application. As part of testing I am trying to setup a cluster to test the HA in influxDB. 

I got the same response from "toddboom" for my another query earlier. I completely understand that there's no support for v0.11. If you could give some clue to make clustering work in 0.11 for now that would be really helpful.

Please note that, once we find that HA in influxDB meets our requirements the our next step would be to go for a latest 0.13 enterprise version of influxDB. But before that, I am trying to make sure the influxDB's behavior on our data.

If there's any documentation that you think will help me on this, please let me know.

Thanks,
Mohan

**Comment by jsternberg** [comment]
You might want to try the old 0.11 documentation, but clustering really wasn't ready in v0.11. That release happened about 3 months ago and there have been a lot of changes.

Assuming that everything was working correctly (which is likely not a good assumption as v0.11 was still unstable), my guess is that there's only a replication of 1 for the `_internal` table. The `_internal` table is used by InfluxDB and I don't recommend writing anything there. Create a database and use that one instead. You may also want to see what shards were created and what hosts they are on with `SHOW SHARDS` to verify that those shards were created and assigned to the hosts you think they are. If you only have 1 for replication, I think the shard may only appear on one host and shards are created based on time.

I noticed that node 2 and node 3 seem to add up to 5000 so, just a guess, but node 2 may have the points from one shard and node 3 has the points from another shard (as you likely crossed a time boundary). I have no idea what's going on with node 1.

**Comment by mohan111raj** [comment]
Hi,

The replication size for the newly created database is 3. But then its not replicating the data on all 3 nodes. But the default database _internal is with replication factor 1 and its replicating across all nodes.

It seems little strange to me. Is there any reason that _internal acts good in replication with rep factor 1? Also one more question. How to setup the custom retention policy automatically when creating the new database?

Thanks,.

**Comment by jsternberg** [comment]
The replication factor should be tied to the retention policy and with a replication factor of 3, it should replicate to all of the data nodes. I think the default database of `_internal` only has a replication factor of 1 by default because it's considered internal data about the server and not important to replicate for availability. I don't remember the exact details for 0.11 so whatever you see when showing the retention policies is what is true.

With a replication factor of 1, I think that just means that each shard will only exist on one server.

For setting up the default retention policy when creating the database, you can do this:

```
CREATE DATABASE WITH REPLICATION 3
```
