### ISSUE TITLE
About naming series

### ISSUE THREAD

**Issue by anhldbk** [influxdata/influxdb#6858]
### Bug report

__System info:__ [InfluxDB version: 0.13.0, Ubuntu 16.04]

__Steps to reproduce:__

1. Write data into series `device/led`
2. Query data from that series

__Expected behavior:__ [Can select data from the series]

__Actual behavior:__ [Error in parsin query]

![screenshot from 2016-06-17 10-37-55](https://cloud.githubusercontent.com/assets/3270746/16140063/b91728d2-3477-11e6-8e57-0aaf115d1b71.png)

**Comment by jsternberg** [comment]
Use double quotes.

```
SELECT * FROM "device/led"
```

Single quotes are for strings while double quotes are for identifiers.

**Comment by anhldbk** [comment]
@jsternberg Thank you so much. You made my day.
