### ISSUE TITLE
[master] An invalid CREATE DATABASE statement returns status 200, should be 400

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#6862]
From the CLI:

```
> create database abc with duration -1d
ERR: retention policy duration must be at least 1h0m0s
> show databases
name: databases
---------------
name
_internal
```

The logs show a 200 status returned, even though the database was not created:
```
[query] 2016/06/17 09:57:00 CREATE DATABASE abc WITH DURATION -24h0m0s REPLICATION 1 NAME
[httpd] ::1 - - [17/Jun/2016:09:57:00 -0700] "POST /query?chunked=true&db=junk&epoch=ns&q=create+database+abc+with+duration+-1d HTTP/1.1" 200 99 "-" "InfluxDBShell/unknown" 81fdb8c5-34ac-11e6-82e8-000000000000 984
```

For what it's worth, a *syntactically* invalid CREATE DATABASE statement like `> create database xyz with` correctly returns a 400 status:

```
[httpd] ::1 - - [17/Jun/2016:10:18:26 -0700] "POST /query?chunked=true&db=junk&epoch=ns&q=create+database+xyz+with HTTP/1.1" 400 121 "-" "InfluxDBShell/unknown" 80ce98bc-34af-11e6-837a-000000000000 6712
```

**Comment by jsternberg** [comment]
I think this is expected. A 200 status usually just means it got passed off to the query executor successfully. We return the error message as part of the response instead of through the status code.

**Comment by e-dard** [comment]
Yeah I think this is the case where checking [Result.Err](https://github.com/influxdata/influxdb/blob/master/client/v2/client.go#L529-L532) is used.
