### ISSUE TITLE
[InfluxDB] BUG - Continous Queries - 0.13

### ISSUE THREAD

**Issue by corsoalex-pro** [influxdata/influxdb#6871]
influxDB Version : 0.13

I'm using some retention policies to store my data
```
> SHOW RETENTION POLICIES on ipflow
name		duration	shardGroupDuration	replicaN	default
default		0		168h0m0s		1		false
two_weeks	360h0m0s	24h0m0s			1		true
one_month	744h0m0s	24h0m0s			1		false
two_months	1488h0m0s	24h0m0s			1		false
six_months	4392h0m0s	168h0m0s		1		false
one_year	8760h0m0s	168h0m0s		1		false
five_years	43800h0m0s	168h0m0s		1		false
```

My data is stored into ipflow.two_weeks.mac_src with my python script.

I created 5 continuous queries : 
```
> SHOW CONTINUOUS QUERIES
cq_mac_src_5m	CREATE CONTINUOUS QUERY cq_mac_src_5m ON ipflow BEGIN SELECT mean(bytes) AS avg_bytes, min(bytes) AS min_bytes, max(bytes) AS max_bytes, mean(packets) AS avg_packets, min(packets) AS min_packets, max(packets) AS max_packets INTO ipflow.one_month.mac_src FROM ipflow.two_weeks.mac_src GROUP BY mac_src, time(5m) END
cq_mac_src_30m	CREATE CONTINUOUS QUERY cq_mac_src_30m ON ipflow BEGIN SELECT mean(avg_bytes) AS avg_bytes, min(min_bytes) AS min_bytes, max(max_bytes) AS max_bytes, mean(avg_packets) AS avg_packets, min(min_packets) AS min_packets, max(max_packets) AS max_packets INTO ipflow.two_months.mac_src FROM ipflow.one_month.mac_src GROUP BY mac_src, time(30m) END
cq_mac_src_2h	CREATE CONTINUOUS QUERY cq_mac_src_2h ON ipflow BEGIN SELECT mean(avg_bytes) AS avg_bytes, min(min_bytes) AS min_bytes, max(max_bytes) AS max_bytes, mean(avg_packets) AS avg_packets, min(min_packets) AS min_packets, max(max_packets) AS max_packets INTO ipflow.six_months.mac_src FROM ipflow.two_months.mac_src GROUP BY mac_src, time(2h) END
cq_mac_src_6h	CREATE CONTINUOUS QUERY cq_mac_src_6h ON ipflow BEGIN SELECT mean(avg_bytes) AS avg_bytes, min(min_bytes) AS min_bytes, max(max_bytes) AS max_bytes, mean(avg_packets) AS avg_packets, min(min_packets) AS min_packets, max(max_packets) AS max_packets INTO ipflow.one_year.mac_src FROM ipflow.six_months.mac_src GROUP BY mac_src, time(6h) END
cq_mac_src_1d	CREATE CONTINUOUS QUERY cq_mac_src_1d ON ipflow BEGIN SELECT mean(avg_bytes) AS avg_bytes, min(min_bytes) AS min_bytes, max(max_bytes) AS max_bytes, mean(avg_packets) AS avg_packets, min(min_packets) AS min_packets, max(max_packets) AS max_packets INTO ipflow.five_years.mac_src FROM ipflow.one_year.mac_src GROUP BY mac_src, time(1d) END
```

I have a strange behaviour with my continous queries.

 * On the log file, my continuous query is run later than expected! 
```
[continuous_querier] 2016/06/19 22:00:57 executing continuous query cq_mac_src_5m (2016-06-19 04:00:00 +0200 CEST to 2016-06-19 04:05:00 +0200 CEST)
[continuous_querier] 2016/06/19 22:00:57 executing continuous query cq_mac_src_5m (2016-06-19 03:55:00 +0200 CEST to 2016-06-19 04:00:00 +0200 CEST)
[continuous_querier] 2016/06/19 22:00:58 executing continuous query cq_mac_src_5m (2016-06-19 03:50:00 +0200 CEST to 2016-06-19 03:55:00 +0200 CEST)
[continuous_querier] 2016/06/19 22:00:58 executing continuous query cq_mac_src_5m (2016-06-19 03:45:00 +0200 CEST to 2016-06-19 03:50:00 +0200 CEST)
[continuous_querier] 2016/06/19 22:00:59 executing continuous query cq_mac_src_5m (2016-06-19 03:40:00 +0200 CEST to 2016-06-19 03:45:00 +0200 CEST)
[continuous_querier] 2016/06/19 22:00:59 executing continuous query cq_mac_src_5m (2016-06-19 03:35:00 +0200 CEST to 2016-06-19 03:40:00 +0200 CEST)
```

 * Data is not downsampled : 
```
> SELECT bytes, packets FROM ipflow.two_weeks.mac_src WHERE  mac_src = '80:71:1f:4a:9f:ca' AND time > now() - 30m
name: mac_src
-------------
time			bytes		packets
1466366409000000000	503449297	757021
1466366469000000000	568872489	822624
1466366530000000000	463798800	680596
1466366589000000000	592120378	868822
1466366649000000000	525332412	763937
1466366709000000000	528973824	762057
1466366769000000000	548491264	793751
1466366829000000000	522756700	772465
1466366889000000000	550981564	797847
1466366949000000000	555430895	781865
1466367009000000000	588518920	805434
1466367069000000000	560834459	775486
1466367129000000000	527163123	766757
1466367189000000000	515076968	747284
1466367249000000000	527357649	754335
1466367309000000000	533974838	767630
1466367369000000000	559791255	783343
1466367429000000000	549244995	770518
1466367489000000000	566412741	807247
1466367549000000000	549524798	785559
1466367609000000000	534572048	761117
1466367669000000000	543902803	776695
1466367729000000000	530501094	759102
1466367789000000000	537565083	759572
1466367849000000000	517623606	747687
1466367909000000000	512758968	752186
1466367969000000000	551358799	770920
1466368029000000000	537789490	769175
1466368089000000000	520670157	752321
1466368149000000000	494259619	732982
```

```
> SELECT * FROM ipflow.one_month.mac_src WHERE  mac_src = '80:71:1f:4a:9f:ca' AND time > now() - 30m
>
```

Do you have some tips with continuous queries that can help me we this bug?

Thank you very much for your patience.

Alexandre

**Comment by KiNgMaR** [comment]
Same issue here (#5951). Can't believe that almost everybody else seems to not have these problems :(

Some specifics on my setup:
* writing via UDP only
* all points are written without timestamps (i.e. time stamps are generated by InfluxDB)

Do you have a similar setup, Alexandre?

**Comment by corsoalex-pro** [comment]
I'm writing data with InfluxDB Python (http://influxdb-python.readthedocs.io/en/latest/index.html)
I'm writing my data with a timestamp (I don't think there is a problem with timestamp because I can query my first retention policy with good timestamp)

You are right, it looks like similar but I'm using 0.13 version.

**Comment by corsoalex-pro** [comment]
Hello

Any update from InfluxDB team? 

Kind regards

**Comment by corsoalex-pro** [comment]
![test-influxdb](https://cloud.githubusercontent.com/assets/14127684/16533023/30c987c6-3fd6-11e6-9e02-d5d49e37e091.png)
I attached an example.

**Comment by corsoalex-pro** [comment]
Hello,

I did some test on my production.

Query without INTO : 

Just running the query : 
[query] 2016/07/21 18:42:29 SELECT mean(bytes) AS avg_bytes, min(bytes) AS min_bytes, max(bytes) AS max_bytes, mean(packets) AS avg_packets, min(packets) AS min_packets, max(packets) AS max_packets FROM ipflow.two_weeks.flows WHERE time >= '2016-07-21T16:00:00Z' AND time < '2016-07-21T16:05:00Z' GROUP BY mac_src, mac_dst, etype, time(5m)

[httpd] 2016/07/21 18:42:44 ::1 - - [21/Jul/2016:18:42:29 +0200] POST /query?chunked=.... - InfluxDBShell/0.13.0 1cf9f78e-4f62-11e6-b50a-000000000000 **15.357709322s**

- Query with INTO

[query] 2016/07/21 18:57:18 SELECT mean(bytes) AS avg_bytes, min(bytes) AS min_bytes, max(bytes) AS max_bytes, mean(packets) AS avg_packets, min(packets) AS min_packets, max(packets) AS max_packets INTO ipflow.one_month.flows FROM ipflow.two_weeks.flows WHERE time >= '2016-07-21T16:00:00Z' AND time < '2016-07-21T16:05:00Z' GROUP BY mac_src, mac_dst, time(5m)

[httpd] 2016/07/21 19:07:37 ::1 - - [21/Jul/2016:18:57:18 +0200] POST /query?chunked=.... - InfluxDBShell/0.13.0 2f3a6bfd-4f64-11e6-80be-000000000000 10m18.87625832s

####
name: result
------------
time	written
0	10821
#####

It looks like the continuous query is really slow to write data into InfluxDB. I'm using some python consumers (rabbitMQ to InfluxDB) and I can write ~ 2k points per seconds

Kind regards

**Comment by jsternberg** [comment]
I'm going to start looking into this, but can you try running with the latest beta3 for 1.0? Included in there is a change to how continuous queries are run and it should be much faster since it only runs one query rather than one per interval.

**Comment by corsoalex-pro** [comment]
Hi Jsternberg, 

I updated influxDB to 1.0 Beta 3 and everything looks fine now. Continuous queries are much faster than 0.13. 

Thank you
