### ISSUE TITLE
weighted sum and average

### ISSUE THREAD

**Issue by mrecht** [influxdata/influxdb#6876]
**Proposal:** 
Adding a weighted versions of _sum_ and _mean_ to InfluxSQL. The weight should be the values of another column. This useful for (financial) time series to e.g. calculate the VWAP.

**Current behavior:**
Currently the functionality is not available.

**Desired behavior:** 
_wmean(x, y)_

select wmean(volume, price) as vwap from trades

The formula for wmean: 
sum (volume*price) / sum(volume)

Given the table:
price  volume
1        4
2        5
3        6

select wmean(volume,price) as vwap from trades

should result in:
time  vwap
0       2.1333

The formula for wsum: 
sum (volume*price)

select wsum(volume,price) as s from trades

should result in:
time  s
0       32.0

**Use case:**
The use case is processing financial time series. The most prominent case which comes to mind is VWAP calculation.

**Comment by itzikHagoel** [comment]
+1

**Comment by Kaelten** [comment]
+1 This would be a great way for me to deal with time-sliced p90 aggregations that have variable sample sizes.   I can get close with a median/mean approach, but reading it seems weighted average would be best.  

For me, it'd be something like: ` select mean(latency, count) from tp90_data where time > now() - 24h`

In this idea, latency and count would both be fields on tp90_data.

**Comment by soloradish** [comment]
+1

**Comment by diresquirrel** [comment]
+1

**Comment by adrianluff** [comment]
+1

**Comment by maurodelazeri** [comment]
+1

**Comment by smasuda** [comment]
Has anyone started working on this? Otherwise I'd try.
VWAP is fundamental for financial timeseries and I need that to migrate from mysql to influxdb.

**Comment by RemiSlv** [comment]
I'm doing:
``` 
select sum(pq) / sum(q) as vwap from (select p*q as pq, q from trade where time > now() - 30m) group by time(1m)
```

**Comment by q40603** [comment]
Tried with flux
`from(bucket: "stock")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "2330")
  |> filter(fn: (r) => r["_field"] == "price" or r["_field"] == "vol")
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
//   |> map(fn: (r) => ({ r with sum: float(v: r.vol) * r.price }))
  |> window(every:1m)
  |> reduce(fn: (r, accumulator) => ({
      count: accumulator.count + float(v:r.vol),
      total: accumulator.total + (float(v: r.vol) * r.price),
//       _value: (accumulator.total) / float(v: accumulator.count)
    }),
    identity: {count: 0.0, total: 0.0}
  )
  |> map(fn: (r) => ({ r with _value: float(v: r.total) / r.count }))
  |> keep(columns: ["_start", "_value"])
  |> duplicate(column:"_start", as:"_time")
  |> window(every:inf)`

**Comment by thisiskj** [comment]
Another Flux solution that worked for me

```
import "experimental"

from(bucket: "stock")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => r["_measurement"] == "SPY")
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
    |> drop(columns: ["vwap"])
    |> window(every: 1d)

    // Create a copy of volume and run cumulative sum on it
    |> map(fn: (r) => ({ r with volume_cum: r.volume }))
    |> cumulativeSum(columns: ["volume_cum"])

    // Calculate pv (typical price * volume)
    |> map(fn: (r) => ({ r with pv: (r.high + r.low + r.close)/3.0 * float(v: r.volume) }))

    // Create a copy of pv and run cumulative sum on it
    |> map(fn: (r) => ({ r with pv_cum: r.pv }))
    |> cumulativeSum(columns: ["pv_cum"])

    // Vwap
    |> map(fn: (r) => ({ r with vwap: r.pv_cum / float(v: r.volume_cum) }))

    |> drop(columns: ["pv", "pv_cum", "trades", "volume", "volume_cum"])
    |> experimental.unpivot()
```
