### ISSUE TITLE
Add support for cluster seeding via multicast discovery

### ISSUE THREAD

**Issue by hatt** [influxdata/influxdb#688]
Nodes currently require a seed to join a cluster. In some environments a seed isn't known in advance, so multicast discovery (or even support for subnets instead of hosts) would be pretty great.

**Comment by aviau** [comment]
Should InfluxDB support external discovery systems like etcd or consul? This seems to become the trend for recent distributed systems, and it facilitates administration if everything supports the standard discovery tools.

**Comment by hatt** [comment]
I think that'd be a great idea. Personally I use Consul, and it makes life easier in environments like EC2 where multicast isn't an option.

**Comment by aviau** [comment]
Also, It would be great if InfluxDB supported SRV records all around.

**Comment by jsternberg** [comment]
We no longer support clustering in the open source version.
