### ISSUE TITLE
Support for storing graphs

### ISSUE THREAD

**Issue by mitar** [influxdata/influxdb#6888]
We are storing network topologies into InfluxDB. Currently we simply store a string of JSON of a topology graph (vertices and edges between them). The issue is that InfluxDB does not support any downsampling functions on such strings. (For example, one downsampling "max" would be to just see all vertices and all edges which ever existed during an interval, and that would be the resulting data point. "mean" would be those who existed at leas half of the time. And so on.)

Is something like that planned to support?

Alternatively, would it be possible to provide some way to have custom downsampling functions which we could implement and add to InfluxDB?

**Comment by mitar** [comment]
Related: #6891

**Comment by jwilder** [comment]
This is isn't a good fit for the use cases of InfluxDB.  Going to close this out.
