### ISSUE TITLE
Support for user defined functions

### ISSUE THREAD

**Issue by mitar** [influxdata/influxdb#6891]
From discussion in #5930 it seems there is no way to define user defined functions in InfluxDB. Current proposal is to use Kapacitor to compute such function, but this moves data around instead of computing them inside the database.

It would be great to have a way to define user-defined functions. It might be even by loading an additional module which provides them then to the query language.

**Comment by cxreg** [comment]
Reference to a previous version of this discussion: https://github.com/influxdata/influxdb/issues/68

**Comment by jwilder** [comment]
Consolidated into #5930.

**Comment by dp1140a** [comment]
+1

**Comment by ckatsulis** [comment]
+1

**Comment by AnnapoorniS** [comment]
Is user defined function feature available in influx db? It will of great help if somebody could help me with sample in influxdb, which are similar to stored procedures. Any suggestions? Thanks in advance.
