### ISSUE TITLE
How many metrics we are collecting?

### ISSUE THREAD

**Issue by freeseacher** [influxdata/influxdb#6893]
i have one influxdb instance. the version is 0.12.2. and i am wonder how many metrics do i collect per second ? 
Currently i use telegraf for gathering statistics. 
And i have several candidates for name "metric per second". that is 
pointReqLocal  under influxdb_write
writePointsOk under influxdb_shard
both of them according to count from servers showing different but incorrect value.

**Comment by jsternberg** [comment]
Sorry that it's taken so long to respond to this, but questions like this should go to the [mailing list](https://groups.google.com/forum/#!forum/influxdb) where they will get a more prompt response. GitHub is reserved for feature requests and bug reports.
