### ISSUE TITLE
Frequent compactions and write/read delays

### ISSUE THREAD

**Issue by lpalm** [influxdata/influxdb#6895]
### Bug report

__System info:__ Fedora release 22, InfluxDB version v1.0.0-beta1

__Steps to reproduce:__

1. Drop database
2. Start inserting points (we range at around 30k-100k points per second, in a couple hundred thousand series)

__Expected behavior:__ Points are inserted with acceptable latency

__Actual behavior:__ We have two machines configured near identically, a canary and a production database. In the dev machine (16 CPUs) we see no issues and InfluxDB seems to handle the throughput just fine. In the production machine, under a near identical workload (99% identical points being added), we get long write delays constantly. The logs in prod also show a large number of compaction events. The database is extremely unresponsive to writes (block for up to a full minute), and HTTP queries during these slow periods. The database is in this slow, unresponsive state for perhaps the majority of the time while inserting. 

__Additional info:__ Compaction logs and inserter wait logs (>250ms wait counts bucketed by minute) for each box are attached. We're inserting batches of size up to 4k at most every 400ms. There's ~20 inserters. We tried dropping the database and re-creating it once the drop database command returned, to no avail. We've also tried restarting InfluxDB and temporarily stopping the inserters. Unclear why this only affects the production box. Let me know if I can help with more details.

[compactionLogsProd.txt](https://github.com/influxdata/influxdb/files/328430/compactionLogsProd.txt)
[inserterWaitsProd.txt](https://github.com/influxdata/influxdb/files/328431/inserterWaitsProd.txt)
[compactionLogsDev.txt](https://github.com/influxdata/influxdb/files/328432/compactionLogsDev.txt)
[inserterWaitsDev.txt](https://github.com/influxdata/influxdb/files/328433/inserterWaitsDev.txt)

**Comment by lpalm** [comment]
I've attached the config file we're using for both the dev (working) and prod (problematic) machines.

[config.toml.zip](https://github.com/influxdata/influxdb/files/328881/config.toml.zip)

**Comment by lpalm** [comment]
After trying a bunch of potential solutions, we found that those slow periods seem to be triggered by out-of-order writes. For the dev machine with less CPUs it seems that the insert rate was low enough not to get into the pathologic slow behavior very often.

We have a set up for monitoring system where we allow users to insert new time series into the database. The datapoints for these new series come from individual files broken up by day. We'd like to be able to backtest alerts so we backfill old data, up to a couple months. Backfilling all of those daily files can take time, so we also allow continuous insertion of new points added in real time so we can start monitoring right away.

It looks like the database is sharded in weekly increments. We also have these settings:

  cache-snapshot-write-cold-duration = "1h0m0s"
  compact-full-write-cold-duration = "24h0m0s"

Is it possible that if we end up inserting a point at time T-X, then a point at time T (now) then a point at T-X+1 a compaction would be triggered after the second point was inserted due to the first point being considered a "cold" write by now? X here could be anywhere between a few minutes to several weeks.

Given our use case, are there any tips on avoiding this issue, e.g. by somehow having shards with smaller time increments (e.g. <24hrs) so that the continuous processing and backfilling can take place at the same time? Or perhaps some way to avoid compactions during backfilling for some particular measurement (which should only take a couple of hours at most).
 
Thanks.

**Comment by pkittenis** [comment]
Hi @lpalm,

How long after the DB is restarted before continuous full compactions are seen?

In our setup, we see full compactions and heavy write throughput and IOPS exactly 24hrs after DB is restarted. Unlike in your use case, we do not do any backfill, new data is always for current time.

However, the exact 24hr period before deterioration happens is suspect and to test whether the cold duration full compaction period is the trigger have raised that to 48h.

This is the behaviour we see:

![influxdb_writes_2](https://cloud.githubusercontent.com/assets/1391208/16728129/898875d8-475c-11e6-9c9c-b60ea55cb2b9.png)

Is the same behaviour seen in your case or do full compactions start immediately after the DB is restarted?


Log output is similar to yours, frequent full compactions, per below attachment.

[influxdb_write_logs.txt](https://github.com/influxdata/influxdb/files/356900/influxdb_write_logs.txt)

**Comment by lpalm** [comment]
We start seeing issues easily within an hour of restarting. But we get through several day's worth of data per hour when backfilling. Our previous backfill policy was to start from yesterday and go back in time so we can backtest alerts with the most recent data first. Changing it to fill from the oldest file first seems to have reduced the incidence of the massive slowdowns, despite continuous inserting of real-time data while backfilling takes place.

Still, it would be desirable to be able to backfill somewhat recent data (say, the past 1-2 weeks) quickly but still be able to later fill in historical data if needed without crushing the database. Advice on workarounds (Assuming this is intended behavior in first place) would be much appreciated.

**Comment by pkittenis** [comment]
There is at least one issue with compactions run after `compact-full-write-cold-duration` as per  #6885 

In your case, compactions causing issues are also triggered by out of order inserts but are limited to duration of inserts.

It may be the actual cause for these two compactions issues is the same, cannot say without debugging the code though.

Workarounds for cold duration compactions:

 * Restart DB within cold compaction interval
 * Increase cold compaction interval to a very high number to effectively turn it off

For your case, yes, it would be best to backfill from oldest date to newest. Backfilling in reverse time order is a bad idea with influxdb in general, regardless of any compaction issues - it will never perform well in that use case. Perhaps limit backfilling to maintenance periods when the DB is not serving requests.

Will still need one of the two workarounds above for cold duration compactions issue.

**Comment by lpalm** [comment]
"Backfilling in reverse time order is a bad idea with influxdb in general, regardless of any compaction issues - it will never perform well in that use case"

To clarify, for each day getting backfilled, points are in order, starting from 00:00 all the way through to 23:59. It's just that we were inserting each day in reverse chronological order. Given that, is it possible to configure Influx or insertions such that this won't be a problem? We don't experience issues when backfilling data from a few days ago while simultaneously inserting real-time data for the same series, so there's at least some amount of tolerance for out-of-order insertions already.

What does cold compaction buy us? Is data completely uncompressed until it is compacted? Do queries run faster on compacted data?

**Comment by pkittenis** [comment]
Let me clarify, backfilling in descending *date and/or time* order is ill advised :)

There is no configuration settings that I know of that can be adjusted to change this, [it's part of the DB's design](https://docs.influxdata.com/influxdb/v0.13/concepts/insights_tradeoffs/)

What might be worth trying, however, is setting up a new retention period and backfilling only into that retention period. Your queries will also have to use that retention period for backfilled data while real time queries have to go to default retention as normal. This should in theory, haven't tried it myself, force backfill data to not live in the same files as real time data.

Compacted data takes less space (better compression), queries faster from disk (less files to read from) and uses fewer disk I/O.

Conversely, disk space use, IOPS use and query performance from disk will suffer without cold compactions. How much so depends on your particular work loads.

**Comment by lpalm** [comment]
Splitting backfilled and real time data into different retention periods would be messy, since we'd like to visualize and backtest alerts on time ranges that may straddle the split between real time and backfilled. And the split point would be different for each measurement as they are being continuously added over time.

Ideally, disabling compaction for a given measurement while we backfill might avoid killing the database for everybody else. We could then trigger/enable compaction once backfilling is completed 1-2 hours later to reap the benefits of compaction. Doesn't seem like it, but is it possible to control compaction behavior while running and/or on a per-measurement basis?

**Comment by lpalm** [comment]
During backfilling it is possible in some cases that some data points for the current day get overwritten. We start the real-time inserter from the start of the day to ensure we don't have gaps.
Could this be related to the various issues reported RE: overwriting points?

**Comment by jwilder** [comment]
Is this still occurring w/ 1.0.1?

**Comment by pkittenis** [comment]
Confirmed to be resolved since 1.0.0.

**Comment by lpalm** [comment]
Thank you for confirming.
