### ISSUE TITLE
IO util goes up to 100% with 2000 writes per minute

### ISSUE THREAD

**Issue by shawn11ZX** [influxdata/influxdb#6898]
__System info:__ [InfluxDB 0.13.0, CentOS release 6.6]

__Steps to reproduce:__

We have a log server that receives 6 types of applications statistics and write them to influxdb. 
For each type, we have a separate measurement. 

```
String serviceId;
String timestamp;
String serviceName;
String zooName;
HashMap<String, Object> o2; 
Point p = Point.measurement(serviceName).time(Long.parseLong(timestamp), TimeUnit.MILLISECONDS)
					.tag("serviceId", serviceId)
					.tag("serviceName", serviceName)
					.tag("zooName", zooName)
					.fields(o2).build();
			db.addPoint(p);
```

In the above code snippet, the variable o2 is map that may contain 300 key-value pairs, with keys of type String and values of type Numeric.

The 6 types of applications are:

- logic:305 records per minute
- login:23 records per minute
- race:4 records per minute
- allocation:18 records per minute
- scene:1464 records per minute
- room:235 records per minute

In my opinion, the write pressure is very low, but some how the io util is very high according to iotop:

![image](https://cloud.githubusercontent.com/assets/12724185/16291486/1f1212ac-393a-11e6-9149-9dd1c2354c8d.png)

As you can see the jdb2 process is very busy, I suspect this may have something to do with disc sync strategy.

The config file is:
[influxdb.txt](https://github.com/influxdata/influxdb/files/329188/influxdb.txt)

**Comment by e-dard** [comment]
@shawn11ZX thanks for the report. Could you take some profiles of your system while it's under load? The following would be useful:

```
curl -o block.txt "http://localhost:8086/debug/pprof/block?debug=1"
curl -o goroutine.txt "http://localhost:8086/debug/pprof/goroutine?debug=1"
```

Also, a CPU profile will be useful. Please consider that this profile will take 30 seconds of wall-time to collect. It could also cause some performance impact on your system while it's being collected, but it shouldn't be too dramatic. Again, while under load would be the best time to take it:

```
curl -o cpu.txt "http://localhost:8086/debug/pprof/profile"
```

**Comment by shawn11ZX** [comment]
Below is requested log files. Actually the load is quit stable (always high) as our servers will send reports in fixed interval.

[block.txt](https://github.com/influxdata/influxdb/files/331119/block.txt)
[cpu.txt](https://github.com/influxdata/influxdb/files/331121/cpu.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/331122/goroutine.txt)
[iostat.txt](https://github.com/influxdata/influxdb/files/331120/iostat.txt)

**Comment by jwilder** [comment]
Are your disks SSD?  If they are spinning disks, you'll need to configure them in a RAID setup such that they can support at least 500 IOPS.

**Comment by shawn11ZX** [comment]
It's a spinning disk. I have just tested the iops of the disc, quite low actually, so I will close the bug.
Sorry for the mistake.

```
  read : io=115928KB, bw=1600.8KB/s, iops=400 , runt= 72421msec
  write: io=37624KB, bw=531986 B/s, iops=129 , runt= 72421msec
```

The full report
```
test: (groupid=0, jobs=1): err= 0: pid=33955: Fri Jun 24 17:49:09 2016
  read : io=115928KB, bw=1600.8KB/s, iops=400 , runt= 72421msec
  write: io=37624KB, bw=531986 B/s, iops=129 , runt= 72421msec
  cpu          : usr=0.64%, sys=2.18%, ctx=37527, majf=0, minf=24
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=99.8%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued    : total=r=28982/w=9406/d=0, short=r=0/w=0/d=0

Run status group 0 (all jobs):
   READ: io=115928KB, aggrb=1600KB/s, minb=1600KB/s, maxb=1600KB/s, mint=72421msec, maxt=72421msec
  WRITE: io=37624KB, aggrb=519KB/s, minb=519KB/s, maxb=519KB/s, mint=72421msec, maxt=72421msec
```

**Comment by shawn11ZX** [comment]
sorry, we switch on a new disk, but the io is still high...
At such a low pressure, I suppose it's a little unusual.

iops have impoved:
![image](https://cloud.githubusercontent.com/assets/12724185/16337762/6df16eca-3a4a-11e6-9546-4f2692b82e55.png)

**Comment by jackzampolin** [comment]
@shawn11ZX That kind of performance is expected with spinning disks. While you only have 2k points being written every second, each may have up to 300 values, some of which are strings. That would make the number of values being written, the worse case, up to 600k/sec; a very high write load. SSDs would be required to sustain that kind of write load.

**Comment by shawn11ZX** [comment]
2k points per seconds, but 2k points per minutes……
