### ISSUE TITLE
[0.13.0] Continuous Queries run when dropped

### ISSUE THREAD

**Issue by MatijaB** [influxdata/influxdb#6902]
Hi, I'm having a big problem with the Continuous Query feature on InfluxDB. I am running 0.13.
So first, a week ago, I created ~50 continuous queries over 50 different measurements that each have a sample rate of 10 seconds, to aggregate mean data into a different retention policy, grouping by 1 minute.

And that looked something like this:

```
CREATE CONTINUOUS QUERY system_docker_container_blkio_midterm_cq ON system RESAMPLE EVERY 1m FOR 2m BEGIN SELECT mean("container_id") as "container_id", mean("io_service_bytes_recursive_async") as "io_service_bytes_recursive_async", mean("io_service_bytes_recursive_read") as "io_service_bytes_recursive_read", mean("io_service_bytes_recursive_sync") as "io_service_bytes_recursive_sync", mean("io_service_bytes_recursive_total") as "io_service_bytes_recursive_total", mean("io_service_bytes_recursive_write") as "io_service_bytes_recursive_write", mean("io_serviced_recursive_async") as "io_serviced_recursive_async", mean("io_serviced_recursive_read") as "io_serviced_recursive_read", mean("io_serviced_recursive_sync") as "io_serviced_recursive_sync", mean("io_serviced_recursive_total") as "io_serviced_recursive_total", mean("io_serviced_recursive_write") as "io_serviced_recursive_write" INTO "system"."midterm".docker_container_blkio FROM "system"."default".docker_container_blkio GROUP BY time(1m), * END
```

Logically, what happened was InfluxDB got overrun with these queries and my other CQs (daily ones, more specific, over other measurements) stopped being executed due to (I presume) the small ones always being executed.

Now what I did next was I dropped all these 1 minute CQs and changed them so the resample part now was:
"RESAMPLE EVERY 1h FOR 2h" therefore, they would run every one hour for the last two hours, grouping by minute, instead of running a new query every minute. 

The problem is this:
Even though I dropped and then recreated those queries, and when I do show continuous queries, I see them with the 1-hour sample rate as I should, they are still running by the old configuration, every minute, so my log looks like this (and the daily CQs still never get executed):

...
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_beegfs_midterm_cq (2016-06-23 11:07:00 +0200 CEST to 2016-06-23 11:08:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_beegfs_midterm_cq (2016-06-23 11:06:00 +0200 CEST to 2016-06-23 11:07:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_beegfs_midterm_cq (2016-06-23 11:05:00 +0200 CEST to 2016-06-23 11:06:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_beegfs_midterm_cq (2016-06-23 11:04:00 +0200 CEST to 2016-06-23 11:05:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_beegfs_midterm_cq (2016-06-23 11:03:00 +0200 CEST to 2016-06-23 11:04:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_beegfs_midterm_cq (2016-06-23 11:02:00 +0200 CEST to 2016-06-23 11:03:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_beegfs_midterm_cq (2016-06-23 11:01:00 +0200 CEST to 2016-06-23 11:02:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_beegfs_midterm_cq (2016-06-23 11:00:00 +0200 CEST to 2016-06-23 11:01:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_beegfs_midterm_cq (2016-06-23 10:59:00 +0200 CEST to 2016-06-23 11:00:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_beegfs_midterm_cq (2016-06-23 10:58:00 +0200 CEST to 2016-06-23 10:59:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:04 executing continuous query system_cpu_midterm_cq (2016-06-23 12:56:00 +0200 CEST to 2016-06-23 12:57:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:13 executing continuous query system_cpu_midterm_cq (2016-06-23 12:55:00 +0200 CEST to 2016-06-23 12:56:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:25 executing continuous query system_cpu_midterm_cq (2016-06-23 12:54:00 +0200 CEST to 2016-06-23 12:55:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:36 executing continuous query system_cpu_midterm_cq (2016-06-23 12:53:00 +0200 CEST to 2016-06-23 12:54:00 +0200 CEST)
[continuous_querier] 2016/06/23 13:11:45 executing continuous query system_cpu_midterm_cq (2016-06-23 12:52:00 +0200 CEST to 2016-06-23 12:53:00 +0200 CEST)
... 
(it goes on and on like this for every single one, even though their code says "RESAMPLE EVERY 1h FOR 2h")﻿

**Comment by ckdarby** [comment]
Did you try restarting influxdb to see if this resolved the issue at least?

**Comment by zstyblik** [comment]
This might be the very same issue as in https://github.com/influxdata/influxdb/issues/5417 and all it's duplicates.

**Comment by MatijaB** [comment]
I tried restarting and restarting would help in a sense that already dropped CQs would not start again. But the problem is that no matter what I put in the "RESAMPLE EVERY" part, if the query has a "time(1m)" in the group-by clause, it will run a separate query for every minute.

**Comment by MatijaB** [comment]
Ok, so after going in a bit more and trying some more things, I have come to conclusion that my problem is actually two problems, and yes one is the very same issue as in #5417 whereas the other one is maybe a bit more important (and unfixable to me at the moment)

Let's take this continuous query for example:

`CREATE CONTINUOUS QUERY system_cpu_1minute_cq ON system RESAMPLE EVERY 1h FOR 2h BEGIN SELECT mean("usage_guest") as "usage_guest", mean("usage_guest_nice") as "usage_guest_nice", mean("usage_idle") as "usage_idle", mean("usage_iowait") as "usage_iowait", mean("usage_irq") as "usage_irq", mean("usage_nice") as "usage_nice", mean("usage_softirq") as "usage_softirq", mean("usage_steal") as "usage_steal", mean("usage_system") as "usage_system", mean("usage_user") as "usage_user" INTO "system"."midterm".cpu FROM "system"."default".cpu GROUP BY time(1m), * END`

Now what bugs me, when executing this CQ, influx executes 120 1-minute queries instead of executing 1 120-minute query with "group by time(1m)". And I can see that in the log file. 

However, all this time I thought this was an error caused by the fact I used to have 1 minute instead of 1 hour in the resample clause. Now, having read the code for continuous queries, I understand this is intended behavior.

https://github.com/influxdata/influxdb/blob/master/services/continuous_querier/service.go#L306

But still, I do not understand how this is the more optimal way of doing things, seems to me a lot of time is lost on repeatedly running small queries that could easily be a big one.﻿

**Comment by beckettsean** [comment]
I opened https://github.com/influxdata/influxdb/issues/6928 for the CQ batching behavior. Otherwise the system is behaving as currently designed. One query for each interval, every time the CQ runs.
