### ISSUE TITLE
Crash on big size of data (count 40M points in 1 minutes slices)

### ISSUE THREAD

**Issue by navidnabavi** [influxdata/influxdb#6912]
Influxdb version:  0.13.0
OS: Ubuntu 14.04 server

I ran this query:
`
select * from post_views group by (1m) where time > now()-1d;
`
This query was counting on big size of data and caused a crash on influxdb server (not a timeout or error)

**Comment by ckdarby** [comment]
Probably not an issue with influxdb. I graph much larger than 40M points in 1 minute slices and have never had an issue.

Server probably just ran out of ram and sigkill'ed the process.

**Comment by jackzampolin** [comment]
Please see our technical paper on [performance tuning tips](https://influxdata.com/technical-papers/). This has information on instance sizing.
