### ISSUE TITLE
[0.13.0] DROP SERIES not working properly

### ISSUE THREAD

**Issue by anhldbk** [influxdata/influxdb#6914]
### Bug report

__System info:__ 
Influx v0.13.0
Ubuntu Linux x64

__Steps to reproduce:__

1. Create a retention policy named `rp_mqtt_data` for database `mqtt_data`

	```text
	> SHOW RETENTION POLICIES ON mqtt_data
	name		duration	shardGroupDuration	replicaN	default
	default		0		168h0m0s		1		false
	rp_mqtt_data	4320h0m0s	168h0m0s		1		true
	```

2. Insert a new data point into a series in `mqtt_data`

	```text
	> use mqtt_data
	> drop series from "service/anhld/battery"
	> insert service/anhld/battery value=1001
	```

3. Select data from the series and nothing in return

	```text
	> select * from "service/anhld/battery"
	> 	
	```

__Expected behavior:__ 
Get the inserted data

__Actual behavior:__
Nothing in return

**Comment by anhldbk** [comment]
This issue may be related to #5878

**Comment by jackzampolin** [comment]
Unable to reproduce with `0.13.0`:

```
> show retention policies on foo
name	duration	shardGroupDuration	replicaN	default
bar	672h0m0s	24h0m0s			1		true

> create retention policy baz on foo duration 4320h replication 1 default 
> show retention policies on foo

name	duration	shardGroupDuration	replicaN	default
bar	672h0m0s	24h0m0s			1		false
baz	4320h0m0s	168h0m0s		1		true

> show measurements
> insert service/anhld/battery value=1001
> show measurements
name: measurements
------------------
name
service/anhld/battery

> select * from "service/anhld/battery"
name: service/anhld/battery
---------------------------
time			value
1467051399142565488	1001
```

**Comment by anhldbk** [comment]
@jackzampolin I tested several times and saw that: the issue's randomly occurred. Now I'm using the binaries compiled from the code in the master branch, and it's ok (although I know the next stable version's still not available). 
So I close this issue. Thank you!
