### ISSUE TITLE
Can't create Fanout Continous Queries (v0.13)

### ISSUE THREAD

**Issue by jkahrs** [influxdata/influxdb#6915]
Maybe this is a documentation issue.

I'm using influxdb v0.13 on debian jessie.

Back in Version 0.8 there was a Feature called "Fanout Continous Queries" (https://docs.influxdata.com/influxdb/v0.8/api/continuous_queries/#fanout-continuous-queries)
The corresponding docs entry is missing from the 0.13 docs. The steps described in 0.8 aren't working anymore.

Was this feature dropped?

# Detail

`
> show measurements
name: measurements
------------------
name
requests
`

`
> select * from requests limit 5
name: requests
--------------
time			action	count	protocol	service
1466599216368200230	delete	1	xml		dns
1466599276269816540	delete	1	xml		dns
1466599276269823521	create	1	json		ssl
1466599276269827287	update	1	soap		domain
1466599276269831258	update	1	soap		domain
`

When trying to use the steps described in the v0.8 docs
`
> select * from requests into requests.[protocol];
ERR: error parsing query: found INTO, expected ; at line 1, char 24
`

**Comment by jsternberg** [comment]
I don't think this exists anymore. I would suggest just inserting the point with the appropriate tags. Can you tell me what you are trying to do and I can maybe direct you to where you need to go?

It also may be more efficient to ask this question on the [mailing list](https://groups.google.com/forum/#!forum/influxdb). User questions get monitored and somebody responds to questions on there. We mostly use the issue tracker only for tracking features and bugs.

**Comment by jkahrs** [comment]
Thank you @jsternberg.

I was going to create the fanouts by tag anyways so the data in the new measurement could have been handled by another retention policy and been used to faciliate and maybe speedup some queries.

I guess we'll just go the other way round and use CQs to bundle data when needed.

**Comment by jkahrs** [comment]
moving this to the mailing list if any more questions turn up
