### ISSUE TITLE
Should shard durations be set to a very large time?

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#6923]
Now that we have the ability to truncate the active shard to the current time to force creation of a new shard, I'm not sure that we need to actively keep the shard durations to some short interval like before.

Previously, the goal of having rotating shards was that you could move data around a cluster or expand out to new nodes. With the truncate shards functionality you'd still have all of that ready.

I suppose having cold shards makes backups better, but that could be handled by the system operator as part of their normal backup process. Do incremental backups on whatever shard is hot for writes and when it gets to be too slow, truncate to force creation of a new shard so that they don't have to keep backing up the old ones.

Not sure what reducing the total number of shards might have on query performance, but I'm pretty sure it would improve startup time for very large databases. Might also reduce memory footprint too?

Thoughts @jwilder and @benbjohnson?

**Comment by benbjohnson** [comment]
@pauldix I agree that with truncation we don't need to keep such short intervals. Although, in practice I'm not sure if using dynamic shard truncation will make the shards smaller since we'll still need to truncate for backups.

I think moving the index to an mmap file will have the largest impact on startup time and memory footprint.

**Comment by jsternberg** [comment]
This will also potentially reduce the memory footprint of the query engine since we won't need to create an iterator for each shard. Fewer shards means fewer iterators.
