### ISSUE TITLE
BUG: Serious Data Consistency error [v1.0.0beta2, v.1.0.0beta1 - perhaps older?] 

### ISSUE THREAD

**Issue by jevans121** [influxdata/influxdb#6925]
### Bug report

System Info:
 v1.0.0beta2
 v1.0.0beta1
 (potentially earlier)
 ubuntu 14.04.2 LTS

I have been testing with a collection of large time-series files, being importing via 'influx -import' or via my own python utility using influxdb-python. The problem is present with both methods.

Series: 128, 2Hz (500ms sample period); each series with a sinusoidal signal, various amplitudes - either clean or additive random white noise (20% of max amplitude). The time values are *all* in the past.
Import Size: Tested with range of files size: 24 hrs - 14 days (336 hrs); 24 hrs = 187K lines
(BTW, I have also tested with "production data" with similar data-size/frequency characteristics, and problem also exists).

Method:
* Import file1 (covering period1); no fault observed
* Import file2 (covering period2): fault may/not not observed (perhaps depending on the period crossing a shard boundary)
* Keep repeating
* Import fileN (covering periodN):fault will *always occur* eventually; exact time-point seems to be related the number/size of the import files used. (Perhaps following a compaction event triggering?) 

The are *no* unusual (e.g. ERRORS/WARNINGS) entries in the influxdb.log; just the write and compaction events. 

Issue: Some data queries across the data series responsd with "missing" or "out of sequence" data. This can be visualised externally (for example, Grafana), but it present using the influxdb-CLI. Where there is a data fault, it will occur at the same time point in all series. This is observed in both raw (full) queries; and in query aggregated with GROUP BY time(<period>). 

(simplified example)
Query: SELECT mean('A') FROM 'X' WHERE time>t1 and time < t7 GROUP BY time(x)
(NOTE: this could be a raw query as well, such as: SELECT 'A' FROM 'X' WHERE time>t1 and time<t7)

> t1: good-data
> t2: good-data
> t3: (no data)
> t4: (no data)
> t5: (no data)
> t6: good-data
> t3: good-data (note the jump back in time)
> t4: good-data (still in past)
> t5: good-data (still in past)
> t6: good-data (repeat of the above data point)
> t7: good-data

Examples are attached. 

Anecdotally, I suspect the fault to occur once shard compaction begins. I have repeated the test nearly dozen times now on different host systems, using different memory configurations, at different import speeds. The problem *always* occurs at some point, but the exact number of import files or where the data faults occurs seems to vary - though the "jump" always seems to *end* close to the start of the latest import - and then pushing backwards in time to the previous "file").

Also, it does not seem to matter if the query (resulting in gap/jump-back) is issued during import, immediately after; or significantly >1hr.  

I realise this a complicated description, so I attach some influx CLI and grafana examples to try and illustrate.

(I have the database snapshot and import files available, but too large to casually upload) 

Jonathan

[dataFault.txt](https://github.com/influxdata/influxdb/files/337304/dataFault.txt)

![datafault01](https://cloud.githubusercontent.com/assets/19926908/16418966/f0f4dbc6-3d43-11e6-9d48-5ea2702a1dc8.png)
![datafault02](https://cloud.githubusercontent.com/assets/19926908/16418965/f0f2bbc0-3d43-11e6-87a7-0ccaeb3790d8.png)
![datafault03](https://cloud.githubusercontent.com/assets/19926908/16418964/f0f2ca0c-3d43-11e6-930b-8dbca84b1cd0.png)
![datafault04](https://cloud.githubusercontent.com/assets/19926908/16418967/f0f6d1e2-3d43-11e6-92f7-77ce66a6ce07.png)

**Comment by juliusloman** [comment]
I also ran into same issue with 1.0.0-beta1 and 1.0.0.-beta2 and I can confirm it. My findings are in the influxdb forum: https://groups.google.com/d/topic/influxdb/M2pk9iq5faA/discussion

I can confirm this bug is not present in 0.13 or 0.12.2. If I run those 0.x versions with the same data files query results are OK. As soon as I switch to 1.x versions, results are bad. So it looks this is a bug in the query engine, not in data files handling.

**Comment by jevans121** [comment]
I too have just tested my existing data-set (imported using 1.0.0-beta*) after reverted back to 0.13 and can also confirm the bug *not* present.
