### ISSUE TITLE
can retention policy be set in the config file? 

### ISSUE THREAD

**Issue by ucrkarthik** [influxdata/influxdb#6927]
Is it possible to set the retention policy in the config file rather than via a command line query?

**Comment by jackzampolin** [comment]
It is not. More information on retention policies [here](https://docs.influxdata.com/influxdb/v0.13/guides/downsampling_and_retention/). For general questions like this please refer to the [documentation](docs.influxdata.com) or the InfluxDB channel in the [Gopher Slack](https://blog.gopheracademy.com/gophers-slack-community/) Group.
