### ISSUE TITLE
Please unlock issue #3552

### ISSUE THREAD

**Issue by kipelovets** [influxdata/influxdb#6929]
Hey

It's impossible to even add a reaction to a locked issue #3552, please unlock it.

I don't think you should restrict users from contributing comments on that issue, we should be able to provide additional use-cases or discuss possible work-arounds. If you're so annoyed with mindless "+1"s, you should probably add a warning about that.

Sorry for creating an issue for that, I couldn't find another way of contacting you on this matter. 

Thanks!

**Comment by jsternberg** [comment]
Done. GitHub needs a way to allow me to prevent people from submitting +1 comments while still allowing meaningful discussion. I did not know that locking the issue would also lock reactions although it makes sense when I think about it.
