### ISSUE TITLE
[Feature Request] Add IOPS Sizing in Influxdb "hardware Sizing" Documentation 

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/influxdb#6930]
### Feature Request

I'm working currently with graphite and we have plans to migrate to Influxdb because we need to reduce IOPS to our storage backend.

https://github.com/graphite-project/carbon/issues/553

I've not found nothing , when looking information about IOPS sizing  in the influxdb official documentation

https://docs.influxdata.com/influxdb/v0.13/guides/hardware_sizing/#how-much-storage-do-i-need

I've notice also that there is also issues related  to IOPS  ( https://github.com/influxdata/influxdb/issues/6898)

__Proposal:__

I suggest to add in the hardware_sizing documentation a  relationship of input_points/second and IOPS that helps us to limit IO when limited resources.

We can suppose no CQ and all input_points have a also a delete point due to the retention policy applied on the incoming shard

__Use case:__ 

On our platform we don't have any disk array with SSD disks and all array disk are shared with other servers in production. We need to limit the impact by distributing influx boxes across several array disk, but we need some sizing info before.

Thank you very much for this great tool.

**Comment by jsternberg** [comment]
I think this is probably a better issue for our docs repository. @rkuchan thoughts? Do we have this information and should we include it in a section of the documentation?

**Comment by jsternberg** [comment]
Opened influxdata/docs.influxdata.com#570 to address this.

**Comment by beckettsean** [comment]
Added IOPS to more places in the hardware sizing page. 

>  a relationship of input_points/second and IOPS that helps us to limit IO when limited resources.

This is not possible. InfluxDB has a steady-state need for IOPS and there is not a simple relationship between write or query volume and IOPS required. There is no way to state what the IOPS would be for any given situation, except to say it will be more than 500 and less than 2000. 

The system may operate with fewer IOPS available, but we do not test or support that use case, so we cannot document it.
