### ISSUE TITLE
Error in SPREAD (0.13!)

### ISSUE THREAD

**Issue by TheOneValen** [influxdata/influxdb#6940]
Hi!

I have an issue where the SPREAD of my data yields (extremely) erronous results when grouped at specific intervals (tested 24h 2h, no error on 1h).

I don't want to publish my data here but I would send it to a developer for debugging.

The version I used is 0.13. If there is no interest please close this and sorry for the interruption. Then I will try to reproduce it when 1.0 is released.

Greetings,
Firefox

**Comment by jsternberg** [comment]
Thanks for the report! If you are willing to let one of our developers see the data, you can send an email to contact@influxdb.com. Include a link to this issue and somebody will help you send the data to us so we can take a look at it and try to fix the issue. Please be sure to send information about the expected output and the actual output so we can verify and fix the issue.

Thanks again!
