### ISSUE TITLE
Ability to use time interval as the window in moving_average

### ISSUE THREAD

**Issue by techgaun** [influxdata/influxdb#6944]
### Feature Request

__Proposal:__ Ability to use time interval as the window in moving_average

__Current behavior:__ We can only use the integer value `n` which basically calculates moving average based on last `n` number of items.

__Desired behavior:__ Be able to pass the time value such as 1m, 30m, etc. as the window so that the data within each 30m period for eg. can be used to calculate moving average.

Example:
```
select moving_average(grid, 15m) from measurement where (tag_id = '1') and (time > now() - 6h)
```

The above query should calculate data of each timestamp using last 15m data including itself.

__Use case:__ I personally think the moving average in case of time series should also be able to roll and calculate based on the time interval as well. An example is calculation of moving average for all values within each 30 minutes no matter how many data count are there. This gives us the confidence on the calculated measure of moving window of time. I'm not sure if I was able to best put it :)

**Comment by jsternberg** [comment]
What makes this different from just using `mean()` and a `GROUP BY time(...)`? If you want to find the mean of the last 15 minutes of data, you can just do:

```
SELECT mean(grid) FROM measurement WHERE (tag_id = '1') and (time > now() - 6h) GROUP BY time(15m)
```

If you need a moving average covering some time interval (say the last hour with 15 minute intervals), I think you can do something like this:

```
SELECT moving_average(sum(grid), 4) FROM measurement WHERE (tag_id = '1') and (time > now() - 6h) GROUP BY time(15m)
```

Does this work?

**Comment by jsternberg** [comment]
Closing this due to a lack of a response.

**Comment by kleini** [comment]
For me this does not work. I try to monitor a PWM with a pulse width of 15 minutes. I want to monitor the duty cycle and I have only to values within the pulse width, one value "1" when the PWM turns on and on value "0" when the PWM turns off. This happens once every 15 minutes, so a total of two values within 15 minutes. The duty cycle itself has an accuracy of seconds. 15 minutes are 900 seconds and the duty cycle may be every value between 0 and 900s.

To monitor the duty I currently use the following query:
`SELECT moving_average(last("value"), 900) FROM "Groundfloor_Bath_Heating" WHERE time >= now() - 1d GROUP BY time(1s) fill(previous)"`
This fills up the whole 900s with previous values, so I have 900 values divided up into ones and zeros. I want to know, which percentile of ones I now have within those 900 values.

This works okay for short time ranges. The longer the total time range in the WHERE condition is, the slower the execution becomes as more values needs to be processed. Having here the ability to scale down the integer value `N`for the moving_average() function and scaling up the time value of the GROUP BY statement should speed up the query with losing accuracy.
