### ISSUE TITLE
High CPU usage && continuous data delete and write

### ISSUE THREAD

**Issue by victorldb** [influxdata/influxdb#6945]
### linux version
![linux version](http://203.88.166.160:8009/img/1.jpg "linux version")
### influxdb version
![influxdb version](http://203.88.166.160:8009/img/2.jpg "influxdb version")
### influxdb config
![influxdb config](http://203.88.166.160:8009/img/3.jpg "influxdb config")
### cpu usage
![cpu usage](http://203.88.166.160:8009/img/4.jpg "cpu usage")
### infludb data
![infludb data](http://203.88.166.160:8009/img/5.jpg "infludb data")
### data changes(I do not have any data deletion)
![data changes](http://203.88.166.160:8009/img/6.jpg "data changes")

**Comment by jwilder** [comment]
Please use our issue template in the future.
