### ISSUE TITLE
Duplicate data for the same timestamp

### ISSUE THREAD

**Issue by maykSVK** [influxdata/influxdb#6946]
In some case is somehow possible to have multiple data with the same timestamp. I manage to simulate this behavior.

1. Create new database
2. Write this data. (I used curl for writing) [data.txt](https://github.com/influxdata/influxdb/files/343265/data.txt)
3. Write next data. 
[data2.txt](https://github.com/influxdata/influxdb/files/343270/data2.txt)
4. Now you can see in second series (select * from "24ZSS1204390000N") that everything is fine.
5. Drop database
6. Create new database with the same name.
7. Write again data.txt
8. Write again data2.txt
9. now you can see, that every entry is duplicate in 24ZSS1204390000N series

I suppose that there is some kind of cashing of the data, because when I restart InfluxDb server, everything works fine. Also when I use less data, it works fine.

**Comment by gunnaraasen** [comment]
@maykSVK Can you test if the latest nightly build shows this behavior?

**Comment by maykSVK** [comment]
I have tried it in today's nightly build (wget https://dl.influxdata.com/influxdb/nightlies/influxdb_nightly_amd64.deb) and the beahvior was still the same

**Comment by jwilder** [comment]
@maykSVK Thanks for the test data and repro steps that made reproducing this easy.  I was able to reproduce it and have a fix for it in #7027
