### ISSUE TITLE
External connecition to Amazon

### ISSUE THREAD

**Issue by eppak** [influxdata/influxdb#6947]
Hello,
i have a Influx 1.0 beta 2 on a Debian 8.5 (64 bit) and i noticed that influx enstablish a connection to an Amazon EC2 server (on a 443 port): visiting this server with a browser i find "Heroku | No such app". I cannot find documentation on this, it can be disabled? What is the purpose of this?

Thanks in advance.

**Comment by rossmcdonald** [comment]
@eppak InfluxDB will automatically report usage data every 24 hours. You can disable it through the configuration [here](https://github.com/influxdata/influxdb/blob/master/etc/config.sample.toml#L3) by setting reporting disabled to `true`:

```
reporting-disabled = true
```
