### ISSUE TITLE
[0.13][Ubuntu 14.04] Out of Memory while inserting data

### ISSUE THREAD

**Issue by jeltok** [influxdata/influxdb#6954]
The InfluxDB 0.13 crashed with 'out of memory' while inserting data points.

System info: AWS t2.large - 2CPU, 8GB memory, 100GB SSD volume, 300 IOPS
Fresh install (less than one day) of InfluxDB 0.13 usin apt
Inserting about a million data points per hour

After 10 hours of work InfluxDB crashed with the followin trace:

[httpd] 2016/07/03 08:51:26 52.70.38.156 - - [03/Jul/2016:08:51:26 +0000] POST /write?u=&p=&database=hw_stats&precision=ms&db=hw_stats HTTP/1.1 204 0 - - 53cc3e75-40fb-11e6-b901-
000000000000 39.016932ms
[httpd] 2016/07/03 08:51:26 52.70.38.156 - - [03/Jul/2016:08:51:26 +0000] POST /write?u=&p=&database=hw_stats&precision=ms&db=hw_stats HTTP/1.1 204 0 - - 53cc41dd-40fb-11e6-b902-
000000000000 40.844387ms
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xce4740, 0x16)
        /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sysMap(0xc9fdd00000, 0x400000, 0xd9400, 0x10efab8)
        /usr/local/go/src/runtime/mem_linux.go:206 +0x9b
runtime.(*mheap).sysAlloc(0x10d4de0, 0x400000, 0x0)
        /usr/local/go/src/runtime/malloc.go:429 +0x191
runtime.(*mheap).grow(0x10d4de0, 0x200, 0x0)
        /usr/local/go/src/runtime/mheap.go:651 +0x63
runtime.(*mheap).allocSpanLocked(0x10d4de0, 0x200, 0x0)
        /usr/local/go/src/runtime/mheap.go:553 +0x4f6
runtime.(*mheap).alloc_m(0x10d4de0, 0x200, 0x100000000, 0x43d936)
        /usr/local/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7f15c3138de8)
        /usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x10d4de0, 0x200, 0x10100000000, 0x20)
        /usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x400000, 0xc800000001, 0xc820253b28)
        /usr/local/go/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
        /usr/local/go/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc820012000)
        /usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1051

goroutine 2129071 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820253798 sp=0xc820253790
runtime.mallocgc(0x400000, 0xa1c880, 0xc800000001, 0xc836845810)
        /usr/local/go/src/runtime/malloc.go:665 +0x9eb fp=0xc820253870 sp=0xc820253798
runtime.newarray(0xa1c880, 0x400000, 0x0)
        /usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc8202538b0 sp=0xc820253870
runtime.makeslice(0xa05160, 0x400000, 0x400000, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc820253900 sp=0xc8202538b0

**Comment by gunnaraasen** [comment]
@jeltok What do the points look like? We typically see this kind of behavior when writing data with an unbounded number of tags, which creates too many series for the in-memory index.

If you want more info, see the note on ["Don't have too many series"](https://docs.influxdata.com/influxdb/v0.13/concepts/schema_and_data_layout/#discouraged-schema-design) in the discouraged schema design doc.

**Comment by jeltok** [comment]
Thanks for the response. Our data points contain one value (which is in most of the cases equals to one), and 2 tags, that give under a thousand permutations. We have reduces amount of data that we push into the INfluxDB for now, and will try the full volume again when you release version 1.0
