### ISSUE TITLE
how to join 2 time series database?

### ISSUE THREAD

**Issue by mukteshkrmishra** [influxdata/influxdb#6956]

**Comment by jsternberg** [comment]
Unfortunately, we can't help answer this question with no details, so I'm going to close the issue. If you are looking for support, please send a message with an explanation of what you are doing to our [mailing list](https://groups.google.com/forum/#!forum/influxdb) and somebody there will be able to help you. We try to keep the issue tracker to only feature requests and bugs if possible.
