### ISSUE TITLE
Enable a config option for pprof

### ISSUE THREAD

**Issue by daviesalex** [influxdata/influxdb#6957]
We are maintaining a trivial out-of-tree patch to main.go to make it easy to profile in production (below). This is hugely more useful than doing endless profiling for the entire lifetime of a process. 

This patch is trivial, and obviously should be off by default for security reasons, but would you be receptive to a PR that made this a config option? If so we will send you one.

```
[adavies@ljoit-adl1 influxdb (jw-planner)]$ git diff cmd/influxd/main.go
diff --git a/cmd/influxd/main.go b/cmd/influxd/main.go
index 1e21daf..5929609 100644
--- a/cmd/influxd/main.go
+++ b/cmd/influxd/main.go
@@ -16,6 +16,9 @@ import (
        "github.com/influxdata/influxdb/cmd/influxd/help"
        "github.com/influxdata/influxdb/cmd/influxd/restore"
        "github.com/influxdata/influxdb/cmd/influxd/run"
+
+       "net/http"
+       _ "net/http/pprof"
 )

 // These variables are populated via the Go linker.
@@ -39,6 +42,12 @@ func init() {
 }

 func main() {
+
+       go func() {
+               log.Println("Starting debug HTTP server")
+               log.Println(http.ListenAndServe(":6060", nil))
+       }()
+
        rand.Seed(time.Now().UnixNano())

        m := NewMain()
[adavies@ljoit-adl1 influxdb (jw-planner)]$
```

**Comment by jsternberg** [comment]
Why doesn't using the `/debug/pprof` endpoint work? You can hit the `/debug/pprof` endpoint right now through the HTTP server and it will start profiling and return the profile when the profile is ended.

https://golang.org/pkg/net/http/pprof/

**Comment by jsternberg** [comment]
I'm going to close this for now because of no response. If you comment on the issue again and respond to the above, I'll reopen the issue.

Thanks for submitting this issue! If you also need help with using the `/debug/pprof` endpoint, send a message to the [mailing list](https://groups.google.com/forum/#!forum/influxdb) and someone will help you there.

**Comment by daviesalex** [comment]
@jsternberg my apologies, I was being an idiot. I wanted to test this yesterday but have just tested it - it works just fine. Somehow I missed entirely that this was supported within [http] (which makes total sense).

Thanks for closing!
