### ISSUE TITLE
Specify database in schema exploration queries

### ISSUE THREAD

**Issue by willpiers** [influxdata/influxdb#6962]
### Feature Request

__Proposal:__ Make it possible to specify the database in more (hopefully all) queries for schema exploration.

__Current behavior:__ `SHOW RETENTION POLICIES ON <db>` works, but there is no analog for `SHOW MEASUREMENTS`.

__Desired behavior:__ I would love to be able to add `... ON <db>` to all of the queries mentioned in the [schema exploration docs](https://docs.influxdata.com/influxdb/v0.13/query_language/schema_exploration)

__Use case:__ This is important from a usability standpoint, in that it will make the query language more consistent. Our main use case is to support more raw/manual queries in chronograf-type applications

**Comment by jsternberg** [comment]
As part of this, I'm also going to remove the necessary `ON <db>` from some queries like `SHOW RETENTION POLICIES`. I don't believe that should be a breaking change and I get really annoyed I can't type `SHOW RETENTION POLICIES` when I'm using the CLI and have specified a default retention policy a lot. I can never remember which commands require it, which don't support it, and which support a weird combination of both so I think we should normalize everything to support both methods.
