### ISSUE TITLE
InfluxDB client no longer works after attempting to insert millions of records

### ISSUE THREAD

**Issue by lorenmh** [influxdata/influxdb#6969]
### Bug report / Feature request ?

**System info:**
InfluxDB v0.13.0
Ubuntu 14.04 lts
using the Go InfluxDB client / default InfluxDB client

**Overview:**
I am attempting to insert millions of records into InfluxDB.  Every time I try to do this, once I get to around ~2 million records inserted, InfluxDB no longer accepts client requests.  In the Go client I get an error of 'EOF'.

Once this happens, when I attempt to connect to InfluxDB using the default client (by running `influx` in bash) I get an error of:

```
Failed to connect to http://localhost:8086
Please check your connection settings and ensure 'influxd' is running.
```

I can see that the influxd process is running.  Sometimes at this point if I view `/var/log/influxdb/influxdb.log` I can see that InfluxDB is logging things, with messages like 'compacted level 1 group', etc. Even though it is logging messages, the client does not work.

Sometimes InfluxDB isn't logging anything and I have to restart it (`sudo service influxdb restart`), and then I influx logging messages again.  After a number of minutes the client begins working again and again I can insert records.

Is this a bug? What sort of behavior should I expect here? Additionally, what is the ideal way to insert millions of records?

**Steps to Reproduce:**
Attempt to insert millions of records

**Actual behavior:**
Client stops working

**Additional info:**
I am not inserting records in chronological order

**Comment by jwilder** [comment]
Inserting points out of order is very expensive and not recommended.  Try inserting them in order.  Also, I'd recommend using a current nightly as it has some fixes related to out of order points.

If you have the script that you are running that can reproduce the issue, please attach it here.

**Comment by dgnorton** [comment]
Closing since no response.
