### ISSUE TITLE
Silent OOM on restore of big DB in versions later than 0.10.3

### ISSUE THREAD

**Issue by Sahasrara** [influxdata/influxdb#6987]
This is on a machine with 20GB of ram.  If I restore a 7gb database backup on any version of influxdb past 0.10.3, influx will consume ALL of the ram, run for a while, then die without error.  During this period, it's also impossible to contact it via http.

Steps to reproduce:

1. install any version of influx after 0.10.3
2. restore a backup of a large database
3. watch influx explode quietly

I can't share the database backup, but it has thousands of measurements with thousands of samples.

**Comment by Sahasrara** [comment]
And actually, even though .10.3 doesn't crash, it also doesn't show the database and it also takes up most of the 20gb of ram.

**Comment by Sahasrara** [comment]
I have ~70k measurements.  Each one has about 1460 records.

**Comment by jwilder** [comment]
`0.10.3` is no longer maintained and a lot has changed since that version was released.  I'd suggest upgrading to the 1.0.2 releases.
