### ISSUE TITLE
[Feature Request] Batch create databases

### ISSUE THREAD

**Issue by ThatCoalGuy** [influxdata/influxdb#6992]
### Feature Request

__Proposal:__  Batch mode for CREATE DATABASE

__Current behavior:__  There is no current batch processing for creating a database, thus creating even 100 databases takes several seconds as each query is posted and processed. 

__Desired behavior:__ The ability to batch create new databases. For example, a text file containing a list of database names separated line-by-line.
```
curl -XPOST 'localhost:8086/query/create' --data-binary @dbnames.txt
```

__Use case:__ For some data models where data cannot be stored in a single database due to it having sensitive information and should only be accessible by the allowed users, thus requiring separate username/password for each database. Therefore, importing data would also require the creation of many databases which currently takes several minutes, high cpu and a large amount of memory to create 10,000 databases.

**Comment by jsternberg** [comment]
Now that we have query management, we can probably just make it possible to do batch queries in general when a person may not care about the result. My initial impression is that batch processing would be trivial to implement.

@jwilder thoughts?

**Comment by corylanou** [comment]
I'm confused.

Doesn't:

```
create database foo; create database bar;
```

Solve the problem for them already?

**Comment by jsternberg** [comment]
@corylanou no because both of those operations are blocking and won't return an HTTP response until they are finished. This is for running something when you don't care about the end result so the HTTP response will just return immediately saying it was submitted and is running.
