### ISSUE TITLE
Cluster config options don't take effect in front-end http queries

### ISSUE THREAD

**Issue by escoular** [influxdata/influxdb#6997]
__System info:__ v0.13.0

__Steps to reproduce:__

1. Change the defaults for some of the performance-related cluster options in the influx config file. 

 Here's my custom config: 
 ```
[admin]
  enabled = false

[http]
  auth-enabled = true
  log-enabled = false

[meta]
  dir = "/var/lib/influxdb/meta"
  logging-enabled = false

[data]
  dir = "/var/lib/influxdb/data"
  wal-dir = "/var/lib/influxdb/wal"
  query-log-enabled = true

[cluster]
  max-concurrent-queries = 0
  query-timeout = "10s"
  max-select-point = 150
  max-select-series = 5
  max-select-buckets = 5

[hinted-handoff]
  dir = "/var/lib/influxdb/hh"
 ```
2. Rebuild the config file, and restart influx
3. Run a query through the API guaranteed to return more than 150 points: "select * from db".

__Expected behavior:__ The documentation says influx should kill the query and output: `ERR: max number of points reached`. https://docs.influxdata.com/influxdb/v0.13/troubleshooting/query_management/#max-select-point

__Actual behavior:__ Influx returns the usual number of points with no regard for the new options.

__Additional info:__ It does log errors for internal continuous queries, but expected behaviour should be doing the same thing for the front-end. I'm not sure if these are the only options that don't take effect, but for sure max-select-point, max-select-series, and max-select-buckets.

**Comment by beckettsean** [comment]
@jwilder

**Comment by jsternberg** [comment]
@escoular are you seeing the following log message in your configuration file?

```
deprecated config option cluster replaced with coordinator; cluster will not be supported in a future release
```

There may also be a complication if both `coordinator` and `cluster` are in the same configuration file. Is the one you pasted the full configuration file?

Either way, you can try replacing `cluster` with `coordinator` and it should work. I would like to know if the compatibility code isn't working though.

**Comment by escoular** [comment]
@jsternberg I didn't see any log message that mentioned that deprecation. Changing `cluster` to `coordinator` didn't work, none of the cluster options took effect anymore. Here's the full config file:
```
reporting-disabled = false
bind-address = ":8088"
hostname = ""
join = ""

[meta]
  dir = "/var/lib/influxdb/meta"
  retention-autocreate = true
  logging-enabled = false
  pprof-enabled = false
  lease-duration = "1m0s"

[data]
  dir = "/var/lib/influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/wal"
  wal-logging-enabled = true
  query-log-enabled = true
  cache-max-memory-size = 524288000
  cache-snapshot-memory-size = 26214400
  cache-snapshot-write-cold-duration = "1h0m0s"
  compact-full-write-cold-duration = "24h0m0s"
  max-points-per-block = 0
  data-logging-enabled = true

[cluster]
  force-remote-mapping = false
  write-timeout = "5s"
  shard-writer-timeout = "5s"
  max-remote-write-connections = 3
  shard-mapper-timeout = "5s"
  max-concurrent-queries = 0
  query-timeout = "10s"
  log-queries-after = "0"
  max-select-point = 150
  max-select-series = 5
  max-select-buckets = 5

[retention]
  enabled = true
  check-interval = "30m0s"

[shard-precreation]
  enabled = true
  check-interval = "10m0s"
  advance-period = "30m0s"

[admin]
  enabled = false
  bind-address = ":8083"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
  Version = ""

[monitor]
  store-enabled = true
  store-database = "_internal"
  store-interval = "10s"

[subscriber]
  enabled = true

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = true
  log-enabled = false
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
  max-row-limit = 10000

[[graphite]]
  enabled = false
  bind-address = ":2003"
  database = "graphite"
  protocol = "tcp"
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "1s"
  consistency-level = "one"
  separator = "."
  udp-read-buffer = 0

[[collectd]]
  enabled = false
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "10s"
  read-buffer = 0
  typesdb = "/usr/share/collectd/types.db"

[[opentsdb]]
  enabled = false
  bind-address = ":4242"
  database = "opentsdb"
  retention-policy = ""
  consistency-level = "one"
  tls-enabled = false
  certificate = "/etc/ssl/influxdb.pem"
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "1s"
  log-point-errors = true

[[udp]]
  enabled = false
  bind-address = ":8089"
  database = "udp"
  retention-policy = ""
  batch-size = 5000
  batch-pending = 10
  read-buffer = 0
  batch-timeout = "1s"
  precision = ""

[continuous_queries]
  log-enabled = true
  enabled = true
  run-interval = "1s"
```

**Comment by jsternberg** [comment]
Ah, 0.13 still has the name as `[cluster]`.

There is one possibility for the reason why you see this. The point limiter is asynchronous rather than synchronous so it will not abort the query immediately once it hits the limit. It looks like that check interval is currently set for every 10 seconds.

Does this happen with the other limits like `max-select-series`? That one is supposed to be synchronous and should work properly.

**Comment by escoular** [comment]
It didn't work for `max-select-series`. I ran `SELECT * FROM /.*/ LIMIT 1` which returned more than the specified number of series and no error happened anywhere. I do still see errors logging for internal continuous queries that exceed the limit, however.

**Comment by jsternberg** [comment]
It looks like this got fixed at some point and I never closed this issue. This works in the 1.0 release.
