### ISSUE TITLE
[0.13] SHOW TAG VALUES FROM ... WITH KEY IN (...) is slower than SHOW SERIES FROM ...

### ISSUE THREAD

**Issue by adampl** [influxdata/influxdb#6998]
**System info:**
InfluxDB 0.13
CentOS 7

**Expected behavior:**
Both queries should run lightning fast.

**Actual behavior:**
The `SHOW TAG VALUES FROM` runs until it's killed by the timeout, while `SHOW SERIES FROM` works OK - which is illogical, because the same data is required in both queries.

Moreover, the series query returns a lot more results than tag values, so I would expect it to be actually slower.

**Comment by jwilder** [comment]
Can you test with a current nightly.  #6792 likely fixed this.

**Comment by adampl** [comment]
It was probably the same issue. I'll try to check it, maybe tomorrow evening.

**Comment by russorat** [comment]
closing due to lack of response.
