### ISSUE TITLE
Parameter "chunk_size" has no effect unless "chunked=true"

### ISSUE THREAD

**Issue by mhodson-qxbranch** [influxdata/influxdb#6999]
### Bug report

__System info:__

Ubuntu 14.04.4 LTS, 64-bit (trusty)
InfluxDB 0.13.0 (installed from package)

__Steps to reproduce:__

The following script reproduces the issue.

https://gist.github.com/mhodson-qxbranch/a7282f2a36936db419b16d15767915eb

__Expected behavior:__

Expect the first query to return 10000.
Expect the second and third queries to return 10001.

__Actual behavior:__

The second query, where "chunked=true" is not set, but "chunk_size=10001" is set, returns 10000.

__Additional info:__

The fix for this depends on whether the documentation at https://docs.influxdata.com/influxdb/v0.13/guides/querying_data/ is supposed to be correct. The documentation states that you only need to set the "chunk_size" parameter, and makes no mention of "chunked".

If the documentation is incorrect, it should be updated with parameter "chunked=true".

If the documentation is correct, then the functional problem resides in influxdb/services/httpd/handler.go (see code immediately under comment "// Parse chunk size. Use default if not provided or unparsable.")

**Comment by jsternberg** [comment]
You're right the documentation doesn't seem to explain it correctly. I've submitted a PR to update the documentation.

The gist of it is that `chunked=true` is required to get chunking to be enabled. If chunking is enabled, the batches are by series or by the maximum chunk size. So if you do `SELECT * FROM cpu GROUP BY *` and you have one point per series (unique set of tags), the responses will not be chunked by by the chunk size, but by the series.

If `chunked=true` is not specified, chunking is not done.

Sorry for the confusion.

**Comment by jsternberg** [comment]
Closing this in favor of influxdata/docs.influxdata.com#530.
