### ISSUE TITLE
Can't insert record into measurement after running  `delete from <measurement>`  

### ISSUE THREAD

**Issue by lostsummer** [influxdata/influxdb#7004]
### Bug report

__System info:__ 

InfluxDB version: 0.13.0
OS: Debian 8.5 amd 64

__Steps to reproduce:__

In influx shell:

    > use mydb
    Using database mydb
    > insert cpu,host=dev1 value=1
    > insert cpu,host=dev2 value=2
    > select * from cpu
    name: cpu
    ---------
    time                    host    value
    1468393511657317457     dev1    1
    1468393523027021170     dev2    2

    > delete from cpu
    > select * from cpu                        
    > insert cpu,host=dev1 value=1
    > insert cpu,host=dev2 value=2
    > select * from cpu                                  # no result return after enter this line
    >

**Comment by jsternberg** [comment]
Can you try this on master? I'm not able to reproduce the issue on master.

**Comment by yahooguntu** [comment]
Also seeing this. Happens in shell and via the Ruby API. If I restart the server then I can see all the data added after the measurement was deleted.

version 0.13.0
branch 0.13
commit e57fb88a051ee40fd9277094345fbd47bb4783ce
OSX 10.10.5

**Comment by jwilder** [comment]
I reproduced this in `0.13` and it is not reproducible in current `1.0beta2` and current master so going to close.  Please upgrade to `1.0beta2`.
