### ISSUE TITLE
Calculate percentage change in a measurement

### ISSUE THREAD

**Issue by code-decode** [influxdata/influxdb#7006]
### Feature Request

__Proposal: Provide a way to calculate percentage change in a measurement. 

Example from @beckettsean 

select difference("value") / value from measurement where "tag"='tag_value'

__Current behavior: Not allowed to use current value with aggregate functions

__Desired behavior: Allow 

__Use case: For a changing metric the % difference is more helpful many times than raw diff. Example when measuring number of queries sent on a request in a controlled test, i'd like to measure % change. There is some variation already in the metric, so i'd like to see only those that change by more than x%

**Comment by phemmer** [comment]
Smells like #6554

**Comment by himanshughai-okta** [comment]
yes seems like the same problem.

**Comment by code-decode** [comment]
yes seems like the same problem..

**Comment by jsternberg** [comment]
Closing in favor of #6554.
