### ISSUE TITLE
Backup/Restore problem on 1.0.0-beta2

### ISSUE THREAD

**Issue by eppak** [influxdata/influxdb#7008]
Hello, i have a Debian 8.5 with influx 1.0.0-beta2, i'have a problem with backup/restore function. I have 2 machines with the same influx revision (one debian 8.4 one 8.5). I have made this steps:

- SOURCE MACHINE: influxd backup -database devices /tmp/backup
- Move backup from source to destination
- DESTINATION MACHINE: influxd restore -database devices -datadir /var/lib/influxdb/data -metadir /var/lib/influxdb/meta /tmp/backup
- DESTINATION MACHINE: enter influx and drop database
- DESTINATION MACHINE: create database devices

Now i have 2 strange things, the first is that the data is still present, if i count the records the number is the same except for the new record added on destination. The second thing is that if i make another backup on destination this backup is 500+ kB, inside there are 1.5 million records.

# influxd backup -database devices /tmp/backup
2016/07/14 08:01:36 backing up db=devices since 0001-01-01 00:00:00 +0000 UTC
2016/07/14 08:01:36 backing up metastore to /tmp/backup/meta.01
2016/07/14 08:01:36 backing up db=devices rp=default shard=45 to /tmp/backup/devices.default.00045.00 since 0001-01-01 00:00:00 +0000 UTC
2016/07/14 08:01:36 backing up db=devices rp=default shard=53 to /tmp/backup/devices.default.00053.00 since 0001-01-01 00:00:00 +0000 UTC
2016/07/14 08:01:36 backing up db=devices rp=year shard=55 to /tmp/backup/devices.year.00055.00 since 0001-01-01 00:00:00 +0000 UTC
2016/07/14 08:01:36 backing up db=devices rp=year shard=63 to /tmp/backup/devices.year.00063.00 since 0001-01-01 00:00:00 +0000 UTC
2016/07/14 08:01:36 backing up db=devices rp=year shard=74 to /tmp/backup/devices.year.00074.00 since 0001-01-01 00:00:00 +0000 UTC
2016/07/14 08:01:36 backing up db=devices rp=monitor shard=82 to /tmp/backup/devices.monitor.00082.01 since 0001-01-01 00:00:00 +0000 UTC
2016/07/14 08:01:36 backing up db=devices rp=year shard=90 to /tmp/backup/devices.year.00090.00 since 0001-01-01 00:00:00 +0000 UTC
2016/07/14 08:01:36 backup complete

# ls -l /tmp/backup
-rw-r--r-- 1 root root 590848 Jul 14 07:48 devices.monitor.00082.00
-rw-r--r-- 1 root root 590848 Jul 14 08:01 devices.monitor.00082.01
-rw-r--r-- 1 root root   2774 Jul 14 07:48 meta.00
-rw-r--r-- 1 root root   2774 Jul 14 08:01 meta.01

**Comment by eppak** [comment]
I have found that the cause is the wrong ownership of /var/lib/influxdb/data/devices, any idea how it can happen? Thanks

**Comment by jwilder** [comment]
@eppak You need to run the restore as `influxdb` user or `chown` the meta/data dir to `influxdb.influxdb` if not.  It looks like you ran the restore as `root`.
