### ISSUE TITLE
Macosx install via homebrew no web UI

### ISSUE THREAD

**Issue by Fristi** [influxdata/influxdb#701]
Hi, 

Installed Influxdb via Homebrew. Got version 0.7.3. Staring with;

`influxdb --config config.toml`

Seeing this;

``` plain
[06/30/14 08:21:26] [INFO] Loading configuration file config.toml

+---------------------------------------------+
|  _____        __ _            _____  ____   |
| |_   _|      / _| |          |  __ \|  _ \  |
|   | |  _ __ | |_| |_   ___  _| |  | | |_) | |
|   | | | '_ \|  _| | | | \ \/ / |  | |  _ <  |
|  _| |_| | | | | | | |_| |>  <| |__| | |_) | |
| |_____|_| |_|_| |_|\__,_/_/\_\_____/|____/  |
+---------------------------------------------+
```

Would be nice if there is a message like: Server started or Server not started :)

After that when I go to localhost:8083 I am getting: `404 page not found`

Used the `config.sample.toml` config inside the default branch from here. Do you know what is wrong? Would love to give this db a swing :)

**Comment by simPod** [comment]
I have a similar problem. Installed `influxdb` via `brew` http://localhost:8086/ shows `404 page not found` Is there any additional configuration that must be set? Thanks!
