### ISSUE TITLE
influxql: $ character sometimes accepted as whitespace

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#7013]
Working from 921e4f5d20cdce65d583ab26dc1929beacf0cd8c. There appear to be several cases where `$` is accepted in a query, when it looks like it should be invalid:

```
> $show$databases
name: databases
---------------
name
_internal
z

> $show$measurements
name: measurements
------------------
name
m
t

> select*$from m
name: m
-------
time			i
1468529979248078256	0
```

**Comment by jsternberg** [comment]
@jwilder do you think we can get this into 1.0?

**Comment by jsternberg** [comment]
This is not going to end up in 1.0. I'm setting the milestone for 1.1 and putting up a PR to get it into master.

@rkuchan until this is merged, there's going to be an issue with bound parameters. If you use a keyword like `$SHOW`, the scanner ignores the dollar sign and treats it as `SHOW`. This applies to any keyword. Everything else should be fine.
