### ISSUE TITLE
Download influxdb-0.11.0-1 ?

### ISSUE THREAD

**Issue by deepujain** [influxdata/influxdb#7016]
I am unable to locate standalone 64bit binary of influxdb-0.11.0-1 ? I do not see "Older releases link" on influxDB website.

As influxdb-0.11.0-1 is last stable release with cluster support that is open sourced, it might be important for most of us looking for open source version with cluster support.

Please provide with a link.

**Comment by jsternberg** [comment]
You can build it from the tag that's in the repository. There's a download link [here](https://s3.amazonaws.com/influxdb/influxdb_0.11.0-1_amd64.deb), but I do not guarantee it will stay there forever.

I also highly advise you do not use this. Clustering was not complete in that version. If you want an open source solution, the Influx Relay is probably your best bet.

**Comment by abh** [comment]
Your documentation says we have to use it to upgrade to a newer version; so having downloads available would be nice (I got my binaries out of a backup).

**Comment by rossmcdonald** [comment]
They are also listed in the 0.12 documentation along with the upgrade instructions here:

https://docs.influxdata.com/influxdb/v0.12/administration/upgrading/#urls-for-influxdb-0-11
