### ISSUE TITLE
Unable to get cluster running with influxdb-0.11.1

### ISSUE THREAD

**Issue by deepujain** [influxdata/influxdb#7017]
I believe influxdb-0.11.1 is the last open source version that supported cluster.

My current single node (12GB RAM and 60GB disk instance of **influxdb-0.11.1 is running OOM and crashing at least 5 to 10** times in a day. Upgrading to latest version did not solve the problem. Hence am assuming cluster with influxdb-0.11.1 might save the day.

**Creating a single instance with more memory is not scalable and hence a better solution is clustering and adding nodes.**

I installed influxdb-0.11.1 on ubuntu 14 in root directory using standalone binary as my machines are behind firewall and followed instructions on https://docs.influxdata.com/influxdb/v0.11/clustering/cluster_setup/ for cluster setup. 

1. export INFLUXDB_HOME=/root/influxdb-0.11.0-1
2. I installed binary in three nodes.
3. Copied the IP address of each node in /root/influxdb-0.11.0-1/etc/influxdb/influxdb.conf in three location. Each file in each node contains its own ip.

I set INFLUXD_OPTS="-join <IP1>:8091,<IP2>:8091,<IP3>:8091" in /etc/default/influxdb and /root/influxdb-0.11.0-1/etc/default/influxdb and started influxdb on each machine using

sudo nohup $INFLUXDB_HOME/usr/bin/influxd -config $INFLUXDB_HOME/etc/influxdb/influxdb.conf > $INFLUXDB_HOME/db.txt &
tail -f $INFLUXDB_HOME/db.txt 

show servers on each machine shows only one node (itself) as both data and meta node.
log files shows that each node itself is leader and follower.

Questions
1. What am i missing ?
2. I do not see anywhere influxdb knowing the location of INFLUXD_OPTS that contains cluster information.

Help is appreciated.

**Comment by deepujain** [comment]
Node 1
=====


2016/07/14 20:04:39 InfluxDB starting, version 0.11.0, branch 0.11, commit 1572060c6890f5c6f6e540155d99238aca8617e3
2016/07/14 20:04:39 Go version go1.4.3, GOMAXPROCS set to 4
2016/07/14 20:04:39 Using configuration at: /root/influxdb-0.11.0-1/etc/influxdb/influxdb.conf
[meta] 2016/07/14 20:04:39 Starting meta service
[meta] 2016/07/14 20:04:39 Listening on HTTP: IP1:8091
[metastore] 2016/07/14 20:04:39 Using data dir: /var/lib/influxdb/meta
[metastore] 2016/07/14 20:04:39 Node at IP1:8088 [Follower]
[metastore] 2016/07/14 20:04:41 Node at IP1:8088 [Leader]. peers=[IP1:8088]
[store] 2016/07/14 20:04:41 Using data dir: /var/lib/influxdb/data


Node 2
=====

2016/07/14 20:04:39 InfluxDB starting, version 0.11.0, branch 0.11, commit 1572060c6890f5c6f6e540155d99238aca8617e3
2016/07/14 20:04:39 Go version go1.4.3, GOMAXPROCS set to 4
2016/07/14 20:04:39 Using configuration at: /root/influxdb-0.11.0-1/etc/influxdb/influxdb.conf
[meta] 2016/07/14 20:04:39 Starting meta service
[meta] 2016/07/14 20:04:39 Listening on HTTP: **IP2:8091**
[metastore] 2016/07/14 20:04:39 Using data dir: /var/lib/influxdb/meta
**[metastore] 2016/07/14 20:04:39 Node at IP2:8088 [Follower]
[metastore] 2016/07/14 20:04:41 Node at IP2:8088 [Leader]. peers=[IP2:8088]**
[store] 2016/07/14 20:04:41 Using data dir: /var/lib/influxdb/data

Node 3
======

2016/07/14 20:04:39 InfluxDB starting, version 0.11.0, branch 0.11, commit 1572060c6890f5c6f6e540155d99238aca8617e3
2016/07/14 20:04:39 Go version go1.4.3, GOMAXPROCS set to 4
2016/07/14 20:04:39 Using configuration at: /root/influxdb-0.11.0-1/etc/influxdb/influxdb.conf
[meta] 2016/07/14 20:04:39 Starting meta service
[meta] 2016/07/14 20:04:39 Listening on HTTP: IP3:8091
[metastore] 2016/07/14 20:04:39 Using data dir: /var/lib/influxdb/meta
**[metastore] 2016/07/14 20:04:39 Node at IP3:8088 [Follower]
[metastore] 2016/07/14 20:04:41 Node at IP3:8088 [Leader]. peers=[IP3:8088]**
[store] 2016/07/14 20:04:41 Using data dir: /var/lib/influxdb/data

**Comment by jsternberg** [comment]
@deepujain I'm sorry for the inconvenience, but 0.11 hasn't been supported since 0.12 was released back in early April. We also only use the issue tracker for features and bugs and don't provide support on the issue tracker. Clustering was not feature complete in 0.11 so it is highly likely that whatever problem you are running into is just a result of it being broken and incomplete.

I would advise updating to a newer version. If your setup only needs high availability, which fits most people's situations, you can use the Influx Relay to achieve a reasonable HA solution. If you need full clustering, you can go to our website to contact our support team or you can try our [cloud offering](https://cloud.influxdata.com/). Since you are trying to get 0.11 to work, I'm guessing you want the open source version. You can download and compile the project from [here](https://github.com/influxdata/influxdb-relay) to get started.

**Comment by deepujain** [comment]
Thanks.

1. For clustering requirements i need to use Relay instead of relying on influxDB-0.11.1 ?
2. And, does relay work with latest stable releases of InfluxDB, like 0.12 or even upcoming 1.0 ?

**Comment by deepujain** [comment]
Is there a binary available for Relay ? My machines are behind firewall and i cannot install anything from web. A binary would be easy to copy and install, like influxDB.

OS: Ubutuntu 14

**Comment by deepujain** [comment]
Setup seems complex, moving to a better machine for time being.
