### ISSUE TITLE
API should accept an auth password not in query string

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#7019]
### Feature Request

__Proposal:__ [Description of the feature]

InfluxDB API should accept the authentication password somewhere other than in the query string.

__Current behavior:__ [What currently happens]

Password must be passed as a query string parameter.

__Desired behavior:__ [What you would like to happen]

InfluxDB API should accept the authentication password somewhere other than in the query string.
For example, as a basic auth header.

__Use case:__ [Why is this important (helps with prioritizing requests)]

Query strings are often logged by any intermediate proxies. This results in the authentication password being logged in cleartext. This is bad for security.

**Comment by jsternberg** [comment]
The InfluxDB API will accept authentication with basic authentication. We don't do digest authentication, but basic authentication should be good enough with SSL. This worked for me:

```
$ INFLUXDB_HTTP_AUTH_ENABLED=true influxd &
$ curl -XPOST 'http://localhost:8086/query' --data-urlencode "q=CREATE USER admin WITH PASSWORD 'admin' WITH ALL PRIVILEGES"
$ curl -u admin:admin 'http://localhost:8086/query?db=_internal' --data-urlencode "q=SHOW MEASUREMENTS"
```

Is this working for you? Thanks.

**Comment by phemmer** [comment]
The docs don't mention anything about this: https://docs.influxdata.com/influxdb/v1.0/concepts/api/

**Comment by jsternberg** [comment]
I opened influxdata/docs.influxdb.com#532 for us to make the documentation more explicit. The documentation kind of implies it at the beginning by saying we support HTTP authentication, but it requires too much guessing to figure out we mean basic authentication there.

Thanks! We'll have that documentation fixed up soon.
