### ISSUE TITLE
New queries stop responding after multiple past queries

### ISSUE THREAD

**Issue by mire3212** [influxdata/influxdb#7022]
I'm seeing a weird issue where after some time, no new queries can be issued with any reasonable response time. 

Once in this position, the time to return a query on a very few records is around 1 minute or longer:

```
$ time influx -database 'photon' -execute 'select * from probe_temp'
name: probe_temp
----------------
time			probe	value
1468695709981311013	probe_1	121.55
1468695713053388450	probe_1	121.55
1468695716125313000	probe_1	121.55
...
...
...
real	1m26.416s
```

Another query:

```
$ time influx -database 'photon' -execute 'select * from probe_temp limit 10'
name: probe_temp
----------------
time			probe	value
1468695709981311013	probe_1	121.55
1468695713053388450	probe_1	121.55
1468695716125313000	probe_1	121.55
1468695719197226003	probe_1	121.55
1468695722269923640	probe_1	121.55
1468695725340826775	probe_1	121.55
1468695728413088464	probe_1	121.55
1468695731485209166	probe_1	121.55
1468695734455642896	probe_1	121.55
1468695737527134128	probe_1	121.55

Real	2m44.388s
```

There's only about 250 records from that query (it's a fresh DB).

OS X 10.12 (16A239j) beta 2
InfluxDB 0.13
Ingesting data via UDP on port 8088
One database with maybe 300 records?
Installed via homebrew

This was working amazing for weeks, I used it to monitor my BBQ Smoker temp for 4th of July and had 0 problems for 6 hours, now I'm getting ready to do a Sous Vide but I can't get it to track more than a few queries in Grafana. (Grafana has been disabled during testing).

EDIT: It seems that it's also not accepting new values via UDP (the primary mechanism I'm using to get data into the DB). I've not tested other mechanisms yet (not really sure how to be honest)

EDIT2: I installed a new instance into Debian 8 (in a VM) and it seems to be working well. But if I linked Grafana to this new DB it would crash just the same. I had to install Grafana into the VM as well to get it working correctly. Doesn't Grafan and Influx use Go as a back-end? maybe that's the problem?

**Comment by jsternberg** [comment]
Which version are you using? Are you overwriting any points during any of your writes?

I think there's a known issue with 0.13 regarding overwritten points where it can get screwed up and take an absurdly long time to return. I think that's fixed on master and might be fixed with beta2. #6611 for reference.

**Comment by mire3212** [comment]
I am using 0.13 but I am not overwriting any data points. I'll look at installing the current master branch. Thanks

**Comment by jsternberg** [comment]
Ok, please tell me if that doesn't fix your issue so that we can investigate more. I'm going to tag this with a label so we know to wait for a response. Thanks.

**Comment by mire3212** [comment]
I haven't had a chance to build from source yet, but I just noticed that go is being updated via homebrew to 1.6.3. I'm going to see if that makes a difference because I believe that may be the problem.

**Comment by mire3212** [comment]
Looks like an update to Go (v1.6.3) via Homebrew fixed this issue. It seemed fishy that everything was working then to have suddenly stopped with no code changes (I'm on the 0.13 chain). Plus Grafana seemed to do some odd things as well when the DB was acting up.

Closing since it's Go related.
