### ISSUE TITLE
CQs with offset in GROUP BY clause run at original time, not offset time

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7025]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

InfluxDB 0.13+

__Steps to reproduce:__
__Actual behavior:__ [What actually happened]

If a CQ is set up with an offset in the `GROUP BY` clause, the CQ will execute the query with the proper offset, but the query will be scheduled without respect to the offset. For example, a CQ with the clause `GROUP BY time(1d, 3h)` will run at `00:00 UTC` but the `WHERE time` clause will start at `03:00 UTC` and end at `02:59 UTC` the following day.

__Expected behavior:__ [What you expected to happen]

As a user, I would expect the CQ to execute at `03:00` if I have an offset in the `GROUP BY`.

**Comment by jsternberg** [comment]
Is the offset positive or negative? So if it runs at `00:00` on `01/01/2000`, will it start at `03:00` on `01/01/2000` or `12/31/1999`? It seems like it shouldn't be going into the future...

I'm looking at this now.

**Comment by beckettsean** [comment]
Offset is positive. `GROUP BY time(1h,5m)` will start buckets at `xx:05` rather than `xx:00`. `GROUP BY time(1h,-5m)` will start the buckets at `xx:55`.

In your example, with the current behavior, the CQ will kick off at 00:00 to query from 03:00 01/01 until 03:00 01/02
