### ISSUE TITLE
query for time spent in state

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7029]
### Feature Request

**Proposal:** 

A query that returns the time elapsed between state changes, and ideally including the start and end of each state.

**Current behavior:** 

This is a common IoT use case, measuring how long a system is in one state or another, and also recording the times when state changed. Currently there's no way to measure elapsed time except with `ELAPSED()`, which only works on successive points.

**Desired behavior:** 

Assuming `field` has possible values of `open`, `closed`, and `halfway`, then there should be a function `FOO()` such that 

`SELECT FOO(value) FROM bar WHERE time > 00:00 and time < 01:00` would return something like:

```
open
00:00-00:10, 10 minutes
00:45-00:50, 5 minutes

closed
00:10-00:30, 20 minutes

halfway
00:30-00:45, 15 minutes
00:50-01:00, 10 minutes
```

and perhaps `SELECT SUM(FOO(value)) FROM bar WHERE time > 00:00 and time < 01:00` would return:

```
open
15 minutes

closed
00:10-00:30, 20 minutes

halfway
35 minutes
```

**Use case:** 

Primarily for graphing of state changes and for calculating time spent in state. This is a common request from customers and I am happy to provide specific use cases.

**Comment by beckettsean** [comment]
@toddboom you had some ideas for this issue, yes?

**Comment by toddboom** [comment]
I would try to return something like this (in pseudo-data):
```
[{
  time: "2016-07-19 12:00:00",
  duration: 5000000000,
  value: "open"
},
{
  time: "2016-07-19 12:00:05",
  duration: 500000000,
  value: "closed"
}]
```

So, for a given time range, you would see the start time and duration (both in nanos) and the value for that interval. It should be pretty easy to build by iterating through the data in a straight line. 

Maybe the duration isn't even necessary?

**Comment by jack-kerouac** [comment]
We would be very happy about a function like the above mentioned one. The solution proposed by @toddboom is fine as long as the returned points/ranges cover the whole query interval.
The duration can be omitted if no duplication of information is wanted. Alternatively, the following response data would be great:
```json
[{
  "from": "2016-07-19 12:00:00",
  "to": "2016-07-19 12:00:05",
  "value": "open"
},
{
  "from": "2016-07-19 12:00:05",
  "to": "2016-07-19 12:00:20",
  "value": "closed"
}]
```

**Comment by jack-kerouac** [comment]
One additional thought: it would be great if successive data points with the same value would not result in multiple return intervals with the same value but be merged automatically.

**Comment by beckettsean** [comment]
closing in favor of #7581
