### ISSUE TITLE
Selecting just a tag returns no results

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#7041]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

influxdb-1.0.0_beta3-1.x86_64
centos/7

__Steps to reproduce:__

1. `select host from cpu where usage_idle < 1 and time > now() - 1h`  
*(the `where` clause doesn't matter)*

__Expected behavior:__ [What you expected to happen]
To see a list of hosts matching the criteria

__Actual behavior:__ [What actually happened]
No results (and no error)

__Additional info:__ [Include gist of relevant config, logs, etc.]
If I add a single field, any field, to the query, results come back. For example:  
`select host,usage_idle from cpu where usage_idle < 1 and time > now() - 1h`

**Comment by gunnaraasen** [comment]
Thanks @phemmer. Closing this in favor of https://github.com/influxdata/influxdb/issues/5548, which has been a longstanding request.
