### ISSUE TITLE
Lazy insert after delete?

### ISSUE THREAD

**Issue by darkness-y** [influxdata/influxdb#7057]
**Bug report**
I'm a green hand in influxdb and found something strange when running my demo.

**System info:** InfluxDB 0.13.0 Ubuntu 14.10

**Steps to reproduce:**
```
 # create a new database
 create database test
 # insert data
 insert test,a=a,b=b value=1
 # query data
 select * from test
 # delete all data
 delete from test
 # query again
 select * from test
 # insert again
 insert test,a=a,b=b value=1
 # query again
 select * from test
```

**Expected behavior:** Each query should return the latest snapshot of the database.

**Actual behavior:** Queries on database where no "delete" is executed, the result is the latest; while the result of "insert" won't be displayed once "delete" is executed without any "where" clause. Actually, the result will show up after I restart the influxdb server thoroughly.

**Comment by jwilder** [comment]
This is a dup of #7004.  This should be fixed in `1.0beta3`.
