### ISSUE TITLE
Uncontrolled memory consumption

### ISSUE THREAD

**Issue by rvrignaud** [influxdata/influxdb#7058]
### Bug report

Host type : VM
OS : Ubuntu 16.04
4 vCPU
25 GB of memory
Influxdb data disk : 500GB of SSD
Influxdb version : 1.0.0-beta3

**Steps to reproduce:**
We have multiple source of data : 
- telegraf (50GB of data)
- prometheus (99 GB of data)
- heapster (< 3GB of data)

**Expected behavior:** 
We expect influxdb not to consume more memory than available in the system.

**Actual behavior:** 
Very few minutes after startup, influxdb is eating more memory than the 25GB of RAM and get OOM killed.
This system has been working in production with great stability for a long time.
We do not use yet CQ so we are basically appending data.
We tried to purge some measurements but Influxdb got killed before dropping data. 

**Gists:**
block : https://gist.github.com/rvrignaud/40ec0a3e2a36356e85a108d52d797d2b
goroutines : https://gist.github.com/rvrignaud/c8a96202628f0ec39518246d43e99961
iostat : https://gist.github.com/rvrignaud/920bc3d158d46b23d05d68ddf8bffdbe
vars : https://gist.github.com/rvrignaud/25c51d774f817c493ce7e6f9c2753e14

**Comment by jwilder** [comment]
Can you also collect the following as well as attach the log with the full trace when you got the OOM?

```
curl -o heap.txt "http://localhost:8086/debug/pprof/heap?debug=1" 
influx -execute "show shards" > shards.txt
influx -execute "show stats" > stats.txt
influx -execute "show diagnostics" > diagnostics.txt
```

**Comment by sbadia** [comment]
Hi @jwilder, thanks for your answer! We upgraded the node from `26Gb` of RAM to `52Gb`  (so we don't hit again the issue for the moment :innocent: ) but the logs logs are here.
* https://gist.github.com/sbadia/0cceb4dfd94029a3b6dd6e8dfa5d6fab#file-heap-txt
* https://gist.github.com/sbadia/0cceb4dfd94029a3b6dd6e8dfa5d6fab#file-shards-txt
* https://gist.github.com/sbadia/0cceb4dfd94029a3b6dd6e8dfa5d6fab#file-stats-txt
* https://gist.github.com/sbadia/0cceb4dfd94029a3b6dd6e8dfa5d6fab#file-diagnostics-txt

**Comment by eodin** [comment]
I've tried influxdb from 0.13 up to 1.0.nightly on 36GB RAM Linux VM. Once it consumed 10mln rec. stocks log it OOM killed and now it crashes persistently. Upon start the process consumes all RAM available until next OOM. 

Dump is here https://gist.github.com/eodin/52d0af58cd29f35dc10b3f80a0e5d10f
It looks promising but unstable :-(

**Comment by jwilder** [comment]
@eodin I'd recommend using the 1.0rc1 build and not 0.13 going forward.  
* Are you writing historical data?  
* Are you overwriting points w/ the same timestamp?  
* Can you describe your writes, perhaps provide some sample writes in line protocol format?

**Comment by eodin** [comment]
I've reinstalled clean copy but it come to OOM again in couple of minutes. So I've shutdown grafana dashboard and now I ingested already 20mln of 100mln of historical records w/o any issue. Mem consumption is about 700Mb. 

Seems some grafanas query kill it to dead. I'll continue the debug once dataset will be fulfilled

**Comment by jwilder** [comment]
@eodin In 0.13, querying across a lot of shards can OOM the process.  1.0.0rc1 has some fixes for that, but it's still possible if you have sparse data and shard durations are not configured correctly.  If you could provide some details on your writes, that would help determine whether these is an  issue with your schema.

If queries are the problem, there are a number of limits you can enable to identify and kill the problem ones.

```
[coordinator]
  max-concurrent-queries = 0 # limits the number of concurrent queries, 0 is disables
  query-timeout = "0" # kills queries after a certain duration, "0" disables
  log-queries-after = "0"# logs slow queries after a certain duration, "0" disables
  max-select-point = 0 # kills queries that return more than a certain number of points, 0 disables
  max-select-series = 0 # kill queries that query more than a certain number of series, 0 disables
  max-select-buckets = 0 # kill queries that return more than a certain number of time buckets, 0 disables
```

**Comment by jwilder** [comment]
Is this still occurring w/ 1.2.2?

**Comment by tanji** [comment]
Same issue with 1.6 and prometheus integration via remote write, 32GB is reached in a matter of minutes

**Comment by relvan1** [comment]
@jwilder 
I am running the influxdb in the docker container and when I check the process usage, I could see the influxd process taking high memory consumption even if it is not used. When I use the influxDB for inserting the data, the memory usage goes very high and not getting released even after the process is completed. 
My config:
8vCPU,30G Ram
InfluxDB Version=1.6.3

Please suggest me the solution for this issue
