### ISSUE TITLE
Continuous queries will begin to lag behind on servers with lots of incoming data

### ISSUE THREAD

**Issue by YorickPeterse** [influxdata/influxdb#7059]
### Bug report

When an InfluxDB receives a high amount of incoming data _and_ a lot of continuous queries have been configured with a low interval (e.g. 1 minute) the CQs will not be able to keep up with the incoming data. That is, raw data may be of timestamp X while the CQs are still processing data from say 2 hours ago. This basically leads to graphs (when visualising this) such as:

![grafana](https://cloud.githubusercontent.com/assets/86065/17103749/2998db70-5280-11e6-862d-5bba74a4d4bb.png)

This particular graph plots data from a measurement that's filled using a CQ that runs (and groups data by) every minute.

In our case we have 3 databases (production, staging, and a private development environment), each running 64 continuous queries that all group data per 1 minute (with the exception of 1 query that groups data per 30 minutes).

Some statistics (as reported by InfluxDB's own statistics):

* 468 measurements
* ~260 000 series
* ~6 active queries per minute
* ~10.3 million points written per minute
* ~260 000 write requests per minute
* WAL compact timings between 40 and 60 seconds, peaks at 1.1 minute
* TSM1 cache size usually peaks up to 600 MB, then drops a bit
* TSM1 storage size is around 250 MB
* ~35MB of data received per minute
* Go heap usage peaks at around 1.5 GB
* ~1400 Goroutines active
* between 25 and 90 GC runs per minute (assuming I plotted the statistics correctly)

Server setup:

20 servers, each running 20-something processes (all writing data to InfluxDB), resulting in roughly 400 clients writing data to InfluxDB. InfluxDB server information can be found below.

Queries:

The various CQs we use can be found in the various directories located at https://gitlab.com/gitlab-org/influxdb-management/tree/master/queries.

Logs:

A few sample log entries showcasing the queries lagging behind is as follows:

```
[query] 2016/07/25 14:05:09 SELECT mean("duration") AS duration_mean, percentile("duration", 95) AS duration_95th, percentile("duration", 99) AS duration_99th, mean(cpu_duration) AS cpu_duration_mean, percentile(cpu_duration, 95) AS cpu_duration_95th, percentile(cpu_duration, 99) AS cpu_duration_99th, mean(call_count) AS call_count_mean, percentile(call_count, 95) AS call_count_95th, percentile(call_count, 99) AS call_count_99th INTO gitlab.downsampled.rails_method_call_timings_per_action_and_method FROM gitlab."default".rails_method_calls WHERE action =~ /.+/ AND action !~ /^Grape#/ AND time >= '2016-07-25T12:50:00Z' AND time < '2016-07-25T12:51:00Z' GROUP BY time(1m), method, action
[continuous_querier] 2016/07/25 14:05:24 executing continuous query rails_method_call_timings_per_action_and_method (2016-07-25 12:49:00 +0000 UTC to 2016-07-25 12:50:00 +0000 UTC)
[query] 2016/07/25 14:05:24 SELECT mean("duration") AS duration_mean, percentile("duration", 95) AS duration_95th, percentile("duration", 99) AS duration_99th, mean(cpu_duration) AS cpu_duration_mean, percentile(cpu_duration, 95) AS cpu_duration_95th, percentile(cpu_duration, 99) AS cpu_duration_99th, mean(call_count) AS call_count_mean, percentile(call_count, 95) AS call_count_95th, percentile(call_count, 99) AS call_count_99th INTO gitlab.downsampled.rails_method_call_timings_per_action_and_method FROM gitlab."default".rails_method_calls WHERE action =~ /.+/ AND action !~ /^Grape#/ AND time >= '2016-07-25T12:49:00Z' AND time < '2016-07-25T12:50:00Z' GROUP BY time(1m), method, action
[continuous_querier] 2016/07/25 14:05:38 executing continuous query rails_method_call_timings_per_action_and_method (2016-07-25 12:48:00 +0000 UTC to 2016-07-25 12:49:00 +0000 UTC)
[query] 2016/07/25 14:05:38 SELECT mean("duration") AS duration_mean, percentile("duration", 95) AS duration_95th, percentile("duration", 99) AS duration_99th, mean(cpu_duration) AS cpu_duration_mean, percentile(cpu_duration, 95) AS cpu_duration_95th, percentile(cpu_duration, 99) AS cpu_duration_99th, mean(call_count) AS call_count_mean, percentile(call_count, 95) AS call_count_95th, percentile(call_count, 99) AS call_count_99th INTO gitlab.downsampled.rails_method_call_timings_per_action_and_method FROM gitlab."default".rails_method_calls WHERE action =~ /.+/ AND action !~ /^Grape#/ AND time >= '2016-07-25T12:48:00Z' AND time < '2016-07-25T12:49:00Z' GROUP BY time(1m), method, action
[continuous_querier] 2016/07/25 14:05:52 executing continuous query rails_method_call_timings_per_action_and_method (2016-07-25 12:47:00 +0000 UTC to 2016-07-25 12:48:00 +0000 UTC)
[query] 2016/07/25 14:05:52 SELECT mean("duration") AS duration_mean, percentile("duration", 95) AS duration_95th, percentile("duration", 99) AS duration_99th, mean(cpu_duration) AS cpu_duration_mean, percentile(cpu_duration, 95) AS cpu_duration_95th, percentile(cpu_duration, 99) AS cpu_duration_99th, mean(call_count) AS call_count_mean, percentile(call_count, 95) AS call_count_95th, percentile(call_count, 99) AS call_count_99th INTO gitlab.downsampled.rails_method_call_timings_per_action_and_method FROM gitlab."default".rails_method_calls WHERE action =~ /.+/ AND action !~ /^Grape#/ AND time >= '2016-07-25T12:47:00Z' AND time < '2016-07-25T12:48:00Z' GROUP BY time(1m), method, action
[continuous_querier] 2016/07/25 14:06:07 executing continuous query rails_method_call_timings_per_action_and_method (2016-07-25 12:46:00 +0000 UTC to 2016-07-25 12:47:00 +0000 UTC)
[query] 2016/07/25 14:06:07 SELECT mean("duration") AS duration_mean, percentile("duration", 95) AS duration_95th, percentile("duration", 99) AS duration_99th, mean(cpu_duration) AS cpu_duration_mean, percentile(cpu_duration, 95) AS cpu_duration_95th, percentile(cpu_duration, 99) AS cpu_duration_99th, mean(call_count) AS call_count_mean, percentile(call_count, 95) AS call_count_95th, percentile(call_count, 99) AS call_count_99th INTO gitlab.downsampled.rails_method_call_timings_per_action_and_method FROM gitlab."default".rails_method_calls WHERE action =~ /.+/ AND action !~ /^Grape#/ AND time >= '2016-07-25T12:46:00Z' AND time < '2016-07-25T12:47:00Z' GROUP BY time(1m), method, action
```

__System info:__ InfluxDB 0.13.0, Ubuntu 16.04 (xenial). 8 CPU cores with 32GB of RAM

__Steps to reproduce:__

The exact steps are rather hard as it seems to highly depend on how much data is being sent, how much continuous queries one has, etc. CQs also don't immediately start to lag behind, instead it they slowly over time begin to lag behind the raw data.

__Expected behavior__: CQs should be able to keep up instead of starting to lag behind 1-2 hours.

__Actual behavior:__ CQs lag behind.

## Performance Files

The various performance related files requested can be found here: https://gist.github.com/YorickPeterse/f679563da15b95061732d40674a1c90c

**Comment by YorickPeterse** [comment]
Some extra server statistics:

CPU load average sits between 2.0 and 3.0 but is fairly consistent:

![cpu_load](https://cloud.githubusercontent.com/assets/86065/17104242/4e117fe6-5282-11e6-8466-5904cff07a38.png)

Disk IO (we're using SSDs by the way) isn't really exciting either:

![disk_io](https://cloud.githubusercontent.com/assets/86065/17104272/6d5724d2-5282-11e6-8fea-59a8e660ef6d.png)

Neither is CPU usage:

![cpu_usage](https://cloud.githubusercontent.com/assets/86065/17104288/8440ec78-5282-11e6-9be4-60923dfed536.png)

**Comment by YorickPeterse** [comment]
It's worth mentioning we have been observing this behaviour for the past few weeks. Generally the only short term solution is to block incoming data (e.g. by disabling the UDP listener or blocking input in the firewall) until the CQs have caught up, then unblock data. This however isn't a suitable solution as it means loss of data while input is blocked.

**Comment by YorickPeterse** [comment]
Retention policies we're using:

```
name            duration        shardGroupDuration      replicaN        default
default         1h0m0s          1h0m0s                  1               true
downsampled     168h0m0s        24h0m0s                 1               false
forever         0               168h0m0s                1               false
```

Everything is written to `default` by default and thus expires after 1 hour, downsampled data sticks around for a week. Given CQs lag behind enough this means they may end up being unable to process data as it has already been removed by InfluxDB. We're using this particular setup to keep an upper limit on the data/memory usage as we've found that InfluxDB was unable to handle much more data in our setup without constantly running out of memory upon booting up.

**Comment by jsternberg** [comment]
Can you try this the latest beta for 1.0? We adjusted CQ query execution to speed it up in these types of situations.

**Comment by YorickPeterse** [comment]
@jsternberg We deployed InfluxDB 1.0 beta3 earlier today, we'll keep an eye on it in the coming days to see how the CQs behave.

**Comment by YorickPeterse** [comment]
So far the queries have been keeping up so it seems 1.0 indeed solved this particular problem. Thanks!
