### ISSUE TITLE
[Feature Request] Continuous query definitions allow for new line characters.

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#7061]
Currently Continuous Query definitions dont allow for new line characters. This makes creating CQs a bit of a pain.

**Comment by jsternberg** [comment]
Do you mean within the `influx` binary? I think you can use newlines for continuous queries through the general HTTP API.

**Comment by desa** [comment]
I meant with the http api, didn't realize that would work. Would be nice in the CLI though.

**Comment by jsternberg** [comment]
I think this is an issue with the CLI so I think we'll have a different feature request for improving the CLI.
