### ISSUE TITLE
InfluxDb suddenly begins eating through all memory on the box

### ISSUE THREAD

**Issue by mpchadwick** [influxdata/influxdb#7062]
### Bug report

__System info:__

- InfluxDb v0.13.0
- CentOS Release v6.8
- 2GB Ram

__Steps to reproduce:__

Issue began to occur mysteriously, no event prompted it

__Expected behavior:__

InfluxDb does not eat through all the memory on the box

__Actual behavior:__

InfluxDb began to suddenly consume all the memory on our box. We did not begin pushing any new measurements / data or anything that would result in an increase in series cardinality.

The process was killed by oom-killer. Each time I restarted the process it would again be murdered. I turned off all systems that were pushing data to InfluxDb, changed the WAL directory but the issue still presented itself. 

Here's a screenshot from the Rackspace hosting panel showing the sudden spike in memory usage on the box. You can see the initial spike and then the waves up and down are each time I tried to restart the process again.

![image](https://cloud.githubusercontent.com/assets/4132322/17088427/c1a98826-51e8-11e6-9688-31f21f8f9911.png)

Then, I pointed to a new data-dir (empty) and the process started up smoothy.

Finally, we created a 4GB swap file. The InfluxDb process ran for about 10 minutes, consuming ~10% of the swap and then memory usage stabilized. It seems InfluxDb was needed to do *something* although I'm not sure what it was doing.

![image](https://cloud.githubusercontent.com/assets/4132322/17117995/b57fb3dc-528c-11e6-8813-f82e4510f5d1.png)

The screenshot below shows that nothing changed from a series cardinality standpoint

![image](https://cloud.githubusercontent.com/assets/4132322/17118386/5c685bf8-528e-11e6-9ce4-cf48589fad59.png)

__Additional info:__

**SHOW DIAGNOSTICS**
https://gist.github.com/mpchadwick/fe8a44fdaef511417cd6a3300ba1450e

**Debug Vars**
https://gist.github.com/mpchadwick/6385c9ffd3039ef31d52e1b4074e9da1

**SHOW STATS**
https://gist.github.com/mpchadwick/6ae382b45b6ca9942ff9bbf9cc389404

**SHOW SHARDS**
https://gist.github.com/mpchadwick/4c77695f6cb3fb5f1001f9fc77d52b31

**Comment by mpchadwick** [comment]
I had previously opened https://github.com/influxdata/influxdb/issues/7054 about this issue, but closed it as it was not following the template.

**Comment by jwilder** [comment]
@mpchadwick Do you have the logs for from 17:02-17:16?  It's likely a full compaction ran on one of the shards.  It could also have been CQs, shard expiration, etc.

**Comment by mpchadwick** [comment]
@jwilder 

https://gist.github.com/mpchadwick/f7b9653c343e6cc84d48affe05997345

**Comment by mpchadwick** [comment]
It seems like you're right?

```
[tsm1] 2016/07/25 16:02:55 beginning full compaction of group 0, 2 TSM files
[tsm1] 2016/07/25 16:02:55 compacting full group (0) /var/lib/influxdb/data/client_production/default/51/000000048-000000005.tsm (#0)
[tsm1] 2016/07/25 16:02:55 compacting full group (0) /var/lib/influxdb/data/client_production/default/51/000000080-000000005.tsm (#1)
```

**Comment by mpchadwick** [comment]
@jwilder assuming this is the result of a full compaction, are there any settings we can tune to prevent this from happening in the future? I was reading through [this issue](https://github.com/influxdata/influxdb/issues/5397) and it seems like the only option is "add more memory"?

**Comment by jwilder** [comment]
Upgrading to 1.0beta3 may help. There are a number of memory related fixes there.  Some are specifically related to compactions.

**Comment by mpchadwick** [comment]
@jwilder would a more aggressive retention policy / down sampling via CQs help?

**Comment by jwilder** [comment]
@mpchadwick I don't think so.  Are you overwriting points or writing points out of order?

**Comment by ProTip** [comment]
I'm hitting the same thing while backfilling data on an 8GB VM. 1.9G of disk used, every time influxdb starts now it will compact and crash again.  I would expect compactions to be much more unobtrusive than this.

**Comment by jwilder** [comment]
@ProTip Backfilling data requires changing your config settings to snapshot more frequently to avoid holding onto RAM for old shards.  I'd suggest lowering your `cache-snapshot-write-cold-duration` to `10s` while backfilling.  This issue was also logged for `0.13`, if you are running that version, I'd suggest upgrading to `1.0rc1` as that has several compaction related fixes.  If you are still running into issues after these suggestions, please open a new issue.
