### ISSUE TITLE
CQs and INTO queries should allow for non-nanosecond precision

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7072]
### Feature Request

__Proposal:__ [Description of the feature]

Allow users to specify the write precision for points written to InfluxDB with an `INTO` clause

__Current behavior:__ [What currently happens]

Currently all CQs and ad hoc INTO queries write points with full nanosecond precision.

__Desired behavior:__ [What you would like to happen]

We should be able to specify units other than `ns` for the timestamps, particularly `us`, `ms`, and `s`.

__Use case:__ [Why is this important (helps with prioritizing requests)]

Compression and throughput are better with less precise timestamps.

**Comment by pauldix** [comment]
This actually sounds like a bug. CQs are supposed to be idempotent and the only way that will be true is if the resulting timestamp is rounded to whatever bucket/precision the group by time on the CQ is.

At least, that's what the behavior used to be, once upon a time.

**Comment by mark-rushakoff** [comment]
@beckettsean AFAICT, using `precision rfc3339` in the CLI will display timestamps with  the same precision as what's stored.

A measurement that I know is stored with second precision:

```
> select n from go limit 1
name: go
--------
time			n
2016-03-31T16:54:14Z	50000
```

A measurement with microsecond precision:

```
> select bytes from hh_queue limit 1
name: hh_queue
--------------
time				bytes
2016-07-28T15:46:50.770082Z	191559
```

I'm not aware of a more efficient way to discover the stored precision of a point.

**Comment by beckettsean** [comment]
Thanks, @mark-rushakoff that works well. From my quick testing CQs do write with precision determined by the GROUP BY interval. Closing.
