### ISSUE TITLE
[Feature Request] unix socket binding

### ISSUE THREAD

**Issue by umbri** [influxdata/influxdb#7075]
### Feature Request

__Proposal:__ add support for unix socket binding services

__Current behavior:__ only tcp is used

__Desired behavior:__ this feature will reduce tcp overhead if client is running on the same machine, already mentioned in https://github.com/influxdata/influxdb/issues/4877

**Comment by jsternberg** [comment]
@umbri for clarification, is this for writing only or is this also for issuing queries with the HTTP protocol?

**Comment by jsternberg** [comment]
Fixed via #7135.
