### ISSUE TITLE
Restore data from another retention policy within same database

### ISSUE THREAD

**Issue by xamzab** [influxdata/influxdb#7087]
Hello,

Recently, we've changed our retention policy from 15 days to 6 months for data we were collecting through "collectd" plugins. Our mistake was to forget to change the "retention-policy" field inside "collectd" section inside influx settings.

When we've noticed the mistake, we've tried to make a new retention policy (through CREATE, we didn't know yet it was possible to make an ALTER). After the new policy was in place, we've seen we have lost data as it didn't return from queries sent to influx.

We think the data is still present as it's still present when we do a "influx_inspect" and we see the "shards" we want to restore.

The "influx_inject" output is attached. Please note that we've merged old folder and the new folder by moving files within "data" and "wal" into the retention policy folder.

[influx_inject.txt](https://github.com/influxdata/influxdb/files/387808/influx_inject.txt)

Do you have an idea on how we can let influxdb read and retrieve data from old "shards" ?

Kind regards,
H.

**Comment by jsternberg** [comment]
This is another use case for being able to output query data into the line protocol so it can be reinserted.

/cc @beckettsean
