### ISSUE TITLE
`select *` order tags before fields

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#7094]
### Feature Request

**Proposal:** [Description of the feature]
With the `influx` CLI tool, when doing a `select * from foo`, it would be useful to have tags ordered before fields.

**Current behavior:** [What currently happens]
Columns, both tags and fields, are sorted alphabetically together.

**Desired behavior:** [What you would like to happen]
Sort the tags alphabetically, and then sort the fields alphabetically, and put the tags before the fields.

**Use case:** [Why is this important (helps with prioritizing requests)]
When there are many fields and/or tags, separating the two would make it easier to visually identify the important values, or to easily distinguish between changing values and changing sources (hosts, tag sets, cardinals, whatever), or to easily know where to find a tag when you have the same tags on multiple measurements.

**Comment by dandv** [comment]
Definitely :+1: for displaying the tags before the fields, so the output matches the examples from https://docs.influxdata.com/influxdb/latest/write_protocols/line_protocol_tutorial/#syntax.
