### ISSUE TITLE
write immediate

### ISSUE THREAD

**Issue by yudingling** [influxdata/influxdb#7096]
hi, 
   i try to use  http  to write some records, after that i query the data but nothing found until  a few seconds  later, may be 30s.  is there a  way or config to make the flush immediately after write?

**Comment by jsternberg** [comment]
Hello @yudingling,

General questions like this should be sent to the [mailing list](https://groups.google.com/forum/#!forum/influxdb). The GitHub issue tracker is only for bugs and feature requests. If you have a reproducible test case for the issue you're having, then we can turn this into a bug report and I can investigate it.

Writes should be readable immediately and should not need to be flushed so if you're experiencing something else, you might be running into a bug. I would advice asking the mailing list first though just to check that there's no user error. When you send a message to the mailing list, please be sure to give more details about what you are doing, what version of the software, and any other information that would help a person reproduce your problem.
