### ISSUE TITLE
[BUG] DNS resolving issue on UI

### ISSUE THREAD

**Issue by blaggacao** [influxdata/influxdb#7101]
### Bug report

__System info:__ 
influxdb:1.0.0-beta3-alpine
rancher/stack on docker-for-windows (mobylinux host)
```
docker --version
Docker version 1.12.0, build 8eab29e, experimental
```

__Steps to reproduce:__

Unknown, need for debugging suggestions for further isolation.

__Actual behavior:__ 
![image](https://cloud.githubusercontent.com/assets/7548295/17272525/22965e88-565e-11e6-83d7-ddfcd378b6f8.png)

while:`docker exec 4e1cf8df45e6 wget -qO- http://localhost:8086/query?q=SHOW+SERIES+WHERE+FALSE`
successfully returns: `{"results":[{"error":"database name required"}]}`

Obviously `4e1cf8df45e6` is the influxdb container.
This means that rancher dns setting are working.
Further proof, any of those is working:
- `docker exec 4e1cf8df45e6 wget -qO- http://influxdb:8086/query?q=SHOW+SERIES+WHERE+FALSE`
- `docker exec 4e1cf8df45e6 wget -qO- http://tick_influxdb_1:8086/query?q=SHOW+SERIES+WHERE+FALSE`
- `docker exec 4e1cf8df45e6 wget -qO- http://influxdb.tick.rancher.internal:8086/query?q=SHOW+SERIES+WHERE+FALSE`

None of them host names work in the UI.

------
Awaiting further orientation on how to track this down. I'm as of now assuming it is a problem of influx using the `*rancher.internal` DNS servers. But beware:
```
docker exec 4e1cf8df45e6 cat /etc/hostname
tick_influxdb_1
```
Using `tick_influxdb_1` on the UI neither works. No idea about influxdb internals that could cause this behaviour.

**Comment by blaggacao** [comment]
How to enable logging for the 8083 UI service? Obviously the 8086 logs do not receive any call from the UI, only the wget calls show up.

**Comment by jsternberg** [comment]
I think this is a Docker issue and is covered by the docs for the Admin UI in the image, but the docs could potentially be better. Since you're on Windows, this is probably similar to the same issue on Mac OS X related to Docker because Docker can't be natively run.

> The administrator interface is not automatically exposed when using docker run -P. While the administrator interface is run by default, the adminstrator interface requires that the web browser have access to InfluxDB on the same port in the container as from the web browser. Since -P exposes the HTTP port to the host on a random port, the administrator interface is not compatible with this setting.

The hostname you need to use is the hostname of the virtual machine or the IP address of the virtual machine. Your localhost address won't work since Docker isn't running on localhost. Please try that and respond if that's not the issue. I'm going to close this since I don't think it's related to InfluxDB.

**Comment by blaggacao** [comment]
OK, got it: The browser client needs to be able to access this. Sidenote: Actually docker-for-windows does run on localhost. So exposing this port would make it work, however this brings about another issue:
- When I work with overlay networks, I do not need to expose this port to the wild, as it could potentially be a security risk. In such a setup (eg rancher) I cannot make use of the influxdb admin interface unless the client would get refactoring.

**Comment by jsternberg** [comment]
Hm, if docker-for-windows runs on localhost it should work attached to localhost. You might want to try visiting http://localhost:8086/ping and see what that returns. If that works, then the admin interface should work fine.

Yes, the admin web UI interface will not work unless it is able to access the port in some way. This is a limitation of the admin UI at the moment. Considering that the admin UI would have to be publicly exposed to begin with for it to work, it shouldn't be a very big deal to have the other port open too. I can see how it can get difficult to manage the ports, but I don't understand what you mean by a security risk. Can you explain the security risk in greater detail?

**Comment by blaggacao** [comment]
On localhost, 8086 is not exposed currently, doing so would just solve the issue. :smile: 

I've just seen that graylog Browser Client has a very similar pattern, so I guess it's somewhat a quite common pattern. Without really knowing about the detailed implications, I was thinking that the api endpoint has a tough enough job receiving telegraph messages throughout the network, so I thought it might not be optimal if someone from the outside world can reach it. Proxied through a web client is probably more elegant, as this has extra auth on it and can be put behind reverse proxy / web application firewall of choice.

Sidenote: My use case is a private cloud where normally every internal communication goes through a strongswan VPN network. So it just feels awkward if this is suddenly publicly available.
