### ISSUE TITLE
Needed Licence information for influxdb v0.13.0 clustering technology

### ISSUE THREAD

**Issue by abhilash07** [influxdata/influxdb#7104]
Dear Sir/Madam Thanks for your opensource. For a long time we are using influx-db opensource. Recently we heard that influx-db clustering technology will not apply from v0.12.0 for opensource (it means only for enterprise versions). But recently we make influx-db v0.13.0 bosh release version. When we check out with  git (git checkout v0.13.0) the cluster folder is automatically adding to our opensource influx-db v0.13.0 version. It means the clustering technology is applied to influx-db v0.13.0 opensource with the MIT licence in our local server. Please gives us needed information. Thanks in advance. 

Best Regards

Abhilash S

**Comment by jsternberg** [comment]
Hello @abhilash07,

We do not use the GitHub issue tracker for these types of questions. We only use it for bugs or feature requests. Please send your message to the [mailing list](https://groups.google.com/forum/#!forum/influxdb). Thank you.
