### ISSUE TITLE
[documentation] Unclear what RESAMPLE does for continuous queries

### ISSUE THREAD

**Issue by halt-hammerzeit** [influxdata/influxdb#7106]
While i can understand what `GROUP BY(time)` means, I didn't understand what `RESAMPLE` means, and what is its purpose (both `EVERY` and `FOR`).
You might want to write a section in the documentation clarifying that.

**Comment by halt-hammerzeit** [comment]
And also what does this mean

`The time ranges of the CQ results have round-number boundaries that are set internally by the database.`

**Comment by beckettsean** [comment]
@halt-hammerzeit please file this against the [documentation repo](https://github.com/influxdata/docs.influxdata.com/issues/new). When you do, please describe what is unclear or inadequate about the current [CQ docs](https://docs.influxdata.com/influxdb/v0.13/query_language/continuous_queries/#the-create-continuous-query-statement), as they do discuss `RESAMPLE EVERY...FOR...`

**Comment by halt-hammerzeit** [comment]
Done
https://github.com/influxdata/docs.influxdata.com/issues/568
