### ISSUE TITLE
[Feature request] Ordinality based queries

### ISSUE THREAD

**Issue by sveip** [influxdata/influxdb#7109]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

**Proposal:** 
Lets say that I store a point every second, and later want to query every n-th point from time x to time y. Since n might vary from query to query CQs aren't a good solution to solve this scenario.

**Current behavior:** 
n/a

**Desired behavior:**
A query like `SELECT * FROM h2o_feet WHERE time > now() - 7d ORDINALITY 10` should return every 10th point from `hto_fleet` for the last seven days.

**Use case:** 
E.g. when showing a historical graph on a web page that is limited by the resolution  (size) of the screen, the resolution of data-points can be matched/calculated so that an more appropriate amount of data is queried from the db and bandwidth is saved and speed is optimized.

**Comment by sveip** [comment]
Thank for your response @jsternberg. However this is not the same as the feature request you mention. That feature wants to do calculations (average etc.) of n adjacent points, I am talking about just picking every n-th measurement as is.

There is a big difference in computational power needed for these two different things I believe.

Regards,
Peter

**Comment by jsternberg** [comment]
Ah, you are correct. Sorry about that.

**Comment by sveip** [comment]
Short update. CQs turned out to not work on this scenario, since it will rename the field tag to the operator that is used (`first`, `max`, `min`, `mean`, etc.) SO for now I have created duplicate `measurements` that I write to with lower resolution/more seldom. Really hope there is a more elegant way planned (or existing that I don't know of.)

**Comment by jsternberg** [comment]
@sveip you can use aliases to write operators using the correct name. Something like:

```
SELECT first(value) as value INTO ... FROM ...
```

**Comment by sveip** [comment]
Thanks @jsternberg, that sure does help. The problem is that some of the value are strings, and no operator let me pick single of those as far as I understand.

**Comment by sveip** [comment]
Cool, does this mean that this feature will be available? That would be awesome and much appreciated! Then I could retire my duplication "throttled measurements" db's :)

**Comment by sveip** [comment]
I would still really like to be able to query every n-th entry in a measurement, this would be very handy when working with large data sets.

**Comment by tsat-psv** [comment]
Hope this can be implemented.

**Comment by sveip** [comment]
I would very much appreciate if this can be considered as a feature.
