### ISSUE TITLE
Unable to drop a measurement

### ISSUE THREAD

**Issue by stevenh** [influxdata/influxdb#7112]
### Bug report
We're unable to drop measurements, they report as dropped but soon after they re-appear.

The source of the measurements has been changed and is no longer sending the measurements with the older names. This was ingesting via telegraf using the statsd plugin, so we even tried stopping telegraf and the measurements still get re-created.

We initially raised this as a https://github.com/influxdata/telegraf/issues/1579, as stopping telegraf in our labs environment **seemed** to allow us to drop the measurements but in our live env this doesn't seem to help.

__System info:__
influxdb 0.12.2
linux 3.10

__Steps to reproduce:__

1. Run telegraf and ingest some stats via the statsd plugin.
2. Reconfigure telegraf so the stats are renamed e.g. change metric_separator .
3. Drop the old measurements using influx cli
4. List measurements and the drop measurement will be back.

__Expected behavior:__
Dropped measurements should stay dropped unless the generator is still sending them.

__Actual behavior:__
Measurements that are no longer being reported via statsd protocol either due to a client change or a telegraf configuration change so the names are now different are re-created, even when telegraf is turned off.

**Comment by jwilder** [comment]
This should be fixed in the latest nightlies.

**Comment by stevenh** [comment]
Thanks @jwilder do you have a commit reference as, we'd like to back port that as a stop gap until the next release.

**Comment by stevenh** [comment]
The other question is, is there any workaround that we can use to drop the measurements without using a nightly build?
