### ISSUE TITLE
Feature request: `influx inspect -export` should dump WAL files

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#7115]
### Feature Request

`influx inspect -export` currently does not read or export data from WAL files. It only reads .tsm files. In its current form, it is unable to extract data-at-rest that has not yet been snapshotted to TSM, which means not all of the data is recoverable with the `influx inspect` tool.

**Comment by jwilder** [comment]
These would need to be appended after the TSM files so that replaying them inserts them in the correct order.

**Comment by jwilder** [comment]
I have branch started here: https://github.com/influxdata/influxdb/tree/jw-tsm-wal-inspect

**Comment by corylanou** [comment]
The first question we need to answer is should a shard export include the wal file?

If not, do we add an option like `-include-wal` when exporting (or leave it as a separate command like this commit does: https://github.com/influxdata/influxdb/commit/6e60cbb14eeb690ced6e78fdc554441a4c753dc8), or have both options?

Additionally, do we want the ability to export an entire directory (retention policy) as well?  The functionality for this has been mostly completed already in https://github.com/influxdata/influxdb/commit/2ccf4bd303eb0ffded970710cc94470782c9df7e

//cc @dgnorton @jwilder

**Comment by jwilder** [comment]
Yes.  Export of a shard should include the wal segments automatically as they are part of the data stored in the shard.
