### ISSUE TITLE
0.9.6.1 no mode support

### ISSUE THREAD

**Issue by ikovalyov** [influxdata/influxdb#7123]
query?q=select+mode(response_time)+from+%22Dns+Provider%22&db=nodes
response:
{"results":[{"error":"function not found: \"mode\""}]}

**Comment by ikovalyov** [comment]
Ok, it looks like this function not supported since influx 0.8 Is there any workaround to calculate mode value on a column>
Thanks,

**Comment by phemmer** [comment]
You can use `top`: https://docs.influxdata.com/influxdb/v1.0/query_language/functions/#top

**Comment by jsternberg** [comment]
Related to #1823. While that issue is closed, it was put into an aggregate issue and we're still going to include it in the future. I'm closing this as a duplicate.
