### ISSUE TITLE
influxdb(v0.13) killed by OOM when query 

### ISSUE THREAD

**Issue by whille** [influxdata/influxdb#7134]
### Bug report

**System info**:
InfluxDB version:
    v0.13.0 (git: 0.13 e57fb88a051ee40fd9277094345fbd47bb4783ce)
CentOS release 6.5 (Final)
x86_64 GNU/Linux
32 cpu cores
256G RAM
300G+ SSD disks

**Steps to reproduce:**
influxdb run exclusivley in the server machine, and we use only one measurement(name: "access"), with a single tag, 10 int fields and 3 string fields.
every minute several hundred batch writes arrived(about 30ms per write), resulting int 32k data points increasing. if only writes: the influx server works OK, abount 20G RAM taken;
but if there're two queries running every minute to get the recent data in one minute, the server memory goes up staightly and got OOM(out of memory) killed by system.
here's the query:
    SELECT \* FROM access WHERE time >= 1470799664s AND time < 1470799724s

**Expected behavior**:
 server runs on

**Actual behavior**: 
influxdb run out of memory

**Additional info**:
 detailed info to gist link:
https://gist.github.com/whille/bae90287d51a7a924c83f448cffb36a0

**Comment by whille** [comment]
It seems RAM will drop slowly to small amount if no query continues, but i need to read recent data several times continuously. 
I'm try ing v1.0beta on 32G machine, but it's been killed, will try 256G RAM.
Or should v0.12 ok with the RAM problem?

**Comment by MikeSchroll** [comment]
What is your cardinality of that one tag? Is it highly variable data?

Try: `SELECT sum(numSeries) AS "total_series" FROM "_internal".."database" WHERE time > now() - 10s;`

**Comment by gunnaraasen** [comment]
@whille in addition to providing the results of Mike's query, the `queriesActive` stat shows 85 queries running, which seems high if only two queries are being run per minute. Can you provide the output of a `SHOW QUERIES` query?

There were some changes to the query engine merged a couple days ago which should improve memory use for `SELECT *` queries over a large number of series. Can you check whether the nightly build OOMs?

**Comment by whille** [comment]
@Mike, thanks.
sum(numSeries) in recent 10s returns about 300k or nothing, seems not const.

**Comment by whille** [comment]
@Gunnar, thanks. i’m running a while script to “show queries”, observing 'two select *’ are running each minutes.
i’ll try the nightly build.

**Comment by whille** [comment]
from the stat i guess the numSeries is numShard X numSeries_in_a_shard, i’ll try enlarge the shard group duration from 1h to 1d or 7d, since the series varies slowly. 
Do the query time slow down if shard group duration become lager?  i’m not sure if the time is indexed.

**Comment by gunnaraasen** [comment]
Larger shard group durations should definitely help as well. There shouldn't be any major speed hit from using larger shard groups. InfluxDB is a time series database so everything is already indexed by time.

**Comment by whille** [comment]
I’m not sure if i should change shard duration to 1d or 7d. What’s the benefit for small shard duration?
should the parameter be enlarged in cons?

  # CacheMaxMemorySize is the maximum size a shard's cache can
  # reach before it starts rejecting writes.
  # cache-max-memory-size = 524288000

  # CacheSnapshotMemorySize is the size at which the engine will
  # snapshot the cache and write it to a TSM file, freeing up memory
  # cache-snapshot-memory-size = 26214400

**Comment by whille** [comment]
influx log shows some 500 write error when sever query runs, i��m not sure if it��s related with the nightly-build InfluxDB version I��m using, or the config parameters.
the writes flow is from nginx->influx-relay->influxdb, no detailed log found in either influxdb or influx-relay


-----
"POST /write?consistency=&db=CDN&precision=m&rp= HTTP/1.1" 500 44 "-" "Go-http-client/1.1" 6754f1d8-5fac-11e6-a31b-000000000000 10123895

**Comment by whille** [comment]
current using nightly build, 200G RAM usage, info collected to:
https://gist.github.com/whille/25508cd236daa6c00e05e0847ab2a7a0

**Comment by jwilder** [comment]
@whille Can you provide some same output?  Are you storing access logs data?

**Comment by whille** [comment]
I’m using a minutely crontab to run a script, to call 4 select  simultaneously :

for i in 0 1 2 3; do
    time  influx "SELECT * FROM access WHERE time >= $((${cur_time} - 240 - ${i} * 1800))s AND time < $((${cur_time} - 180 - ${i} * 1800))s" > /dev/null &
#SELECT * FROM access WHERE time >= 1470818024s AND time < 1470818084s
done
wait

**Comment by jwilder** [comment]
@whille Can you provide some sample output of those queries?

**Comment by whille** [comment]
access
time	Dim	Req	Rt	S2XX	S499	S4XX	S5XX	SOther	Slow	bytesIn	bytesOut	domain	node	region
2016-08-11T16:17:00Z	"cdnbcun01//BeiJing_PBS"	28	0	9	0	19	0	0	0	2544	914558	""	"cdnbcun01"	"BeiJing_PBS"
2016-08-11T16:17:00Z	"cdnzzun01/www.saicmg.com/HeNan_CNC"	2	0	2	0	0	0	0	0	896	8465	"www.saicmg.com"	"cdnzzun01"	"HeNan_CNC"
2016-08-11T16:17:00Z	"cdnzzun01/www.roewe.com.cn/HeNan_CNC"	98	0	98	0	0	0	0	0	72496	1793730	"www.roewe.com.cn"	"cdnzzun01"	"HeNan_CNC"
2016-08-11T16:17:00Z	"cdnzzun01/v6.pstatp.com/ZheJiang_CNC"	12	17	12	0	0	0	0	0	4768	11235430	"v6.pstatp.com"	"cdnzzun01"	"ZheJiang_CNC"

**Comment by whille** [comment]
hi @jwilder i updated again, is it suitalbe? (wondering whether if email not trigger).
access
time	Dim	Req	Rt	S2XX	S499	S4XX	S5XX	SOther	Slow	bytesIn	bytesOut	domain	node	region
2016-08-11T16:17:00Z	"cdnbcun01//BeiJing_PBS"	28	0	9	0	19	0	0	0	2544	914558	""	"cdnbcun01"	"BeiJing_PBS"
2016-08-11T16:17:00Z	"cdnzzun01/www.saicmg.com/HeNan_CNC"	2	0	2	0	0	0	0	0	896	8465	"www.saicmg.com"	"cdnzzun01"	"HeNan_CNC"
2016-08-11T16:17:00Z	"cdnzzun01/www.roewe.com.cn/HeNan_CNC"	98	0	98	0	0	0	0	0	72496	1793730	"www.roewe.com.cn"	"cdnzzun01"	"HeNan_CNC"
2016-08-11T16:17:00Z	"cdnzzun01/v6.pstatp.com/ZheJiang_CNC"	12	17	12	0	0	0	0	0	4768	11235430	"v6.pstatp.com"	"cdnzzun01"	"ZheJiang_CNC"

**Comment by whille** [comment]
i've got a pprof from influx debug heap:
i guess the newIntegerCursor takes up most MEM. Is it abnormal  or could i chang data format to improve?  

(pprof) top20 -cum
39.62GB of 44.65GB total (88.73%)
Dropped 436 nodes (cum <= 0.22GB)
Showing top 20 nodes out of 48 (cum >= 1.87GB)
      flat  flat%   sum%        cum   cum%
         0     0%     0%    44.65GB   100%  runtime.goexit
    0.09GB   0.2%   0.2%    43.29GB 96.95%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetGroupIterators
         0     0%   0.2%    43.29GB 96.95%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators.func1
    0.69GB  1.54%  1.74%    43.20GB 96.75%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefSeriesIterator
         0     0%  1.74%    42.08GB 94.25%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).buildCursor
    0.44GB     1%  2.74%    34.85GB 78.06%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).buildIntegerCursor
   29.51GB 66.10% 68.84%    32.47GB 72.72%  github.com/influxdata/influxdb/tsdb/engine/tsm1.newIntegerAscendingCursor
         0     0% 68.84%    32.47GB 72.72%  github.com/influxdata/influxdb/tsdb/engine/tsm1.newIntegerCursor
    0.12GB  0.28% 69.12%     7.22GB 16.18%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).buildStringCursor
    4.63GB 10.38% 79.50%     6.51GB 14.57%  github.com/influxdata/influxdb/tsdb/engine/tsm1.newStringAscendingCursor
         0     0% 79.50%     6.51GB 14.57%  github.com/influxdata/influxdb/tsdb/engine/tsm1.newStringCursor
         0     0% 79.50%     2.96GB  6.62%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*KeyCursor).ReadIntegerBlock
         0     0% 79.50%     2.96GB  6.62%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*TSMReader).ReadIntegerBlockAt
         0     0% 79.50%     2.96GB  6.62%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*mmapAccessor).readIntegerBlock
    2.06GB  4.62% 84.12%     2.96GB  6.62%  github.com/influxdata/influxdb/tsdb/engine/tsm1.DecodeIntegerBlock
         0     0% 84.12%     2.50GB  5.59%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).KeyCursor
         0     0% 84.12%     2.50GB  5.59%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*FileStore).KeyCursor
    2.06GB  4.61% 88.73%     2.50GB  5.59%  github.com/influxdata/influxdb/tsdb/engine/tsm1.newKeyCursor
         0     0% 88.73%     1.87GB  4.19%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*KeyCursor).ReadStringBlock
         0     0% 88.73%     1.87GB  4.19%  github.com/influxdata/influxdb/tsdb/engine/tsm1.(*TSMReader).ReadStringBlockAt

**Comment by jwilder** [comment]
Is this still occurring w/ 1.2.2?
