### ISSUE TITLE
measurements & data present in multiple databases

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#7140]
### Bug report

__System info:__
InfluxDB 1.0 beta 3
CentOS/7

__Steps to reproduce:__
```
> create database db1
> use db1
Using database db1
> insert test1,foo=bar value=1i
> create database db2
> insert test1,foo=bar value=2i
> use db2
Using database db2
> insert test1,foo=bar value=3i
> select * from test1
```

__Expected behavior:__
```
name: test1
-----------
time			foo	value
1470868506225707010	bar	3
```

__Actual behavior:__
```
name: test1
-----------
time			foo	value
1470868283107824299		2
1470868506225707010	bar	3
```

__Additional info:__ 
Any data inserted into any measurement after a database is created will be present in that database. Only data which was inserted before a database was created will not show up in that database.

**Comment by jsternberg** [comment]
I'm afraid I'm unable to reproduce this with your test example. I tested using the docker image for 1.0.0-beta3. How did you insert the data? I used the CLI and typed in the exact commands.

**Comment by phemmer** [comment]
I'm no longer able to reproduce this. I did it once exactly as you see above, but can't seem to do it again. My only guess is that prior to my test, influxdb somehow got into a bad state, but I don't know how that would have happened.

Close?
