### ISSUE TITLE
Memory Limits

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#7142]
### Feature Request

**Proposal:**

The server should have a memory configuration limit for operators to minimize the risk of internal processes triggering OOMs.

**Current behavior:**

There are several places in the system where large allocations are possible which could OOM the processe.  

Generally, these have occurred around:
- **Queries** - Usually using too broad of filter criteria causing too many series to be loaded at once.
- **In-Memory Index** - High cardinality series cause the index to grow and OOM the process
- **Writes** - Many in-flight writes with large batches and slow disks can cause lots of internal buffers to build while waiting for disks to write/sync.
- **Compactions** - In some cases, large series could be loaded in order to deduplicate and chunk the points more optimally.

All of areas have had optimizations to reduce allocations or added limits to short-circuit expensive operations.  We've looked at adding memory limits for the in-memory index as well as queries, but have not found a good way to implement them.

**Desired behavior:**

The system should have a configuration setting for the max memory the process should be allowed to use before it aborts queries, writes, compactions, etc..  This setting would be for the process Heap as reported by [runtime.ReadMemStats](https://golang.org/pkg/runtime/#ReadMemStats).  

In critical sections of code that could potentially allocate a lot of memory, we would check if our Heap (or Sys/RSS) is above the limit, if so, the operation would return an error until memory is released by GC.  By default, the limit could be set to 90% of available memory.

**Comment by e-dard** [comment]
@jwilder have we satisfied this by now?

**Comment by jwilder** [comment]
@e-dard No.  We've reduced memory usage substantially, but this issue is about adding an explicit limit that when enabled would abort tasks that exceed the limit.

**Comment by hpbieker** [comment]
I think this feature will be most usefull if Influx only started such large jobs when it had enough available resources. This means that a compaction is only started if it can run it without having to abort it when 50 % is done due to lack of resources. Of course this can be hard to do when multiple go processes are working concurrently.
