### ISSUE TITLE
Can continuous query executed by http interface

### ISSUE THREAD

**Issue by z1q1q7** [influxdata/influxdb#7143]
I found that continuous queries aren't executed periodicly.
So, I want to executed it by http interface, can anyone tell me how to?

**Comment by jsternberg** [comment]
Hello @z1q1q7,

Questions asking for help should go to the [mailing list](https://groups.google.com/forum/#!forum/influxdb). If you find a bug or feature request in CQs, please open a new issue with details about the bug and how to reproduce the bug. Thanks.
