### ISSUE TITLE
Influxdb v1.0.0 beta not paging  (Seen in v0.13 also)

### ISSUE THREAD

**Issue by ldelossa** [influxdata/influxdb#7145]
Bug report

__System info:__ [v0.13 & v1.0.0 beta, Ubuntu Trusty, stock AWS AMI no alterations]

Here's a drop of keys and tags from the series:

```
> show tag keys
name: usage_costs
-----------------
tagKey
assemblyID
lineitem_lineitemtype
lineitem_operation
lineitem_productcode
lineitem_resourceid
lineitem_usageaccountid
lineitem_usageenddate
lineitem_usagetype
product_group
product_instancefamily
product_instancetype
product_operation
product_productname
product_requesttype
resourcetags_user_costcenter

> show field keys
name: usage_costs
-----------------
fieldKey
lineitem_blendedcost
lineitem_blendedrate
lineitem_unblendedcost
lineitem_unblendedrate
lineitem_usageamount
```

There's some could-be sensitive information so I'd rather not show series. 

__Steps to reproduce:__

Three databases were created: a 100k row series, 500k row series, and 1 million row series. This crash occurs on 500k series and up. 

I have a bash for loop sending the query locally with the influx client. Sleeps every 1 second. Normally latency of the request blocks past this, and script is actually running at the speed of query latency.
With three different queries running in the same fashion, I watch application memory fill cache and free, taking almost all memory.

The queries were as follows:

```
influx -database 'medium_example' -execute 'SELECT sum(lineitem_usageamount) from usage_costs group by lineitem_operation'

 influx -database 'medium_example' -execute 'SELECT sum(lineitem_unblendedcost) from usage_costs group by lineitem_operation'

influx -database 'medium_example' -execute 'SELECT sum(lineitem_unblendedrate) from usage_costs group by lineitem_usageaccountid, lineitem_productcode'
```

__Expected behavior:__ Influxdb uses all available memory, begins to page out to disk, and handles the load appropriately. 

__Actual behavior:__ influxdb uses all available memory, no paging occurs, influx crashes with out of memory issue

Additional info:

Hey guys,

I was stress testing Influxdb today, and I'm 95% certain I found a very repeatable memory leak. I don't have full details on the query but it was is just testing out basic schema and queries. With data sets above 500k points I saw application take over all free and cache ram space. Once it sat there for awhile it finally crashed. I have a monitor called vector collecting stats. I'm also watching vmstat. I see absolutely NO swap in or out, or any evidence of paging.

I deduced that two things are possible:

1) Influxdb is handling its own memory, which I don't believe is completely possible unless it's doing direct io, and avoiding the page cache (would this even stop paging cron happening??)

2) The kernel is flushing dirty pages quick enough to allocate more memory to influxdb.
My test is very hacky, I have a specific query that I run which sums up a few tags. I run this on a 100000 row Db, 500000 row Db. And 1000000 row Db.

I have a bash for loop sending the query locally with the influx client. Sleeps every 1 second. Normally latency of the request blocks past this, and script is actually running at the speed of query latency.
With three different queries running in the same fashion, I watch application memory fill cache and free, taking almost all memory.

I DO NOT see any signs of paging to disk, I used vmstat swap in and swap out metric to view.
I launch one more simultaneous repetitive query, and influx crashes- with a memory error message from influx.

I do not seem OOM run, and I see nothing. In dmesg or syslog. Making me think influx is handling all this, and crashes managing it's own memory, making me not want to use influx.

**Comment by jwilder** [comment]
We need more information in order to diagnose what is going on.  Can you update the issue description with the instructions listed in our [issue template](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md)?

**Comment by ldelossa** [comment]
Just confirmed, this behavior is not present in v0.9.6. 

Same data, same tests, memory is solid, no steep increase or crash.

**Comment by ctorres92** [comment]
Is there any update on this? I am experiencing the same issues

**Comment by jwilder** [comment]
@ctorres92 There is not enough information to diagnose this issue.  Can you run the following and attach them to the issue?

```
curl -o block.txt "http://localhost:8086/debug/pprof/block?debug=1" 
curl -o goroutine.txt "http://localhost:8086/debug/pprof/goroutine?debug=1" 
curl -o heap.txt "http://localhost:8086/debug/pprof/heap?debug=1" 
curl -o vars.txt "http://localhost:8086/debug/vars" 
iostat -xd 1 30 > iostat.txt
influx -execute "show shards" > shards.txt
influx -execute "show stats" > stats.txt
influx -execute "show diagnostics" > diagnostics.txt
```
