### ISSUE TITLE
fill(previous) does not honor math math functions

### ISSUE THREAD

**Issue by disser** [influxdata/influxdb#7158]
### Bug report

Using docker image influxdb:0.13.0, querying via grafana

query data series incorporating math operation and fill(previous).

Any filled results will NOT have math function applied; in this example, it means the filled values will be positive while the non-filled values are negative.

Example with fill(none):

`SELECT mean("kwatts") *-1 FROM "meter" WHERE $timeFilter GROUP BY time($interval) fill(none)`

![screenshot 2016-08-15 at 9 17 38 pm](https://cloud.githubusercontent.com/assets/94499/17687884/06ed7d56-632e-11e6-8aa6-7e22cb7928f1.png)

Same query with fill(previous):

`SELECT mean("kwatts") *-1 FROM "meter" WHERE $timeFilter GROUP BY time($interval) fill(previous)`

![screenshot 2016-08-15 at 9 18 00 pm](https://cloud.githubusercontent.com/assets/94499/17687886/1417f150-632e-11e6-935d-74ea25906e69.png)

**Comment by jsternberg** [comment]
Fixed by #6918 in 1.0.0-beta3.
