### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by ikovalyov** [influxdata/influxdb#7159]
__System info:__ InfluxDB Admin UI: v0.13.0 Server: v0.13.0
__Steps to reproduce:__
1. 
```
SELECT * FROM "performance" LIMIT 1
```
__Expected behavior:__ First entry returned
__Actual behavior:__  I get my db down.
__Additional info:__ It looks like simple limit 1 query eats up all RAM and SWAP instead of just reading first line.
__Gist:__ https://gist.github.com/jimaek/3b0c680d9c9eaea1bb33d3dda7b5b879

Same if I try it via curl:
```
curl '{server}/query?q=SELECT+*+FROM+"performance"+LIMIT+1&db=logs' -H 'Accept: */*' -H 'Referer: {server}' -H 'Origin: {server}' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36' --compressed
```
I get 
```
curl: (52) Empty reply from server
```

Another issue:
```
SHOW MEASUREMENTS
performance
```
```
SHOW TAG KEYS FROM "performance"
"node"
"name"
```
```
SHOW TAG VALUES FROM "performance" WITH KEY = "name"
1
2
3
4
...
```
```
SELECT * FROM "performance" WHERE "name" = "1"
Success! (no results to display)
```
__Expected behavior:__ All records with name=1 returned
__Actual behavior:__ No data returned

Is it something wrong with imported data or am I'm doing something wrong or there is an issue with db?

**Comment by ikovalyov** [comment]
SHOW SERIES FROM "performance"
performance,name=1,node=1

SELECT * FROM "performance" where "name"=1 and "node" = 1 limit 10
Success! (no results to display)

**Comment by jsternberg** [comment]
Can you try using 1.0.0-beta3 and tell me if that helps?

**Comment by mark-rushakoff** [comment]
@ikovalyov: tag values are strings and must be single quoted for queries.

`SELECT * FROM "performance" WHERE "name" = '1'` should work, whereas `... "name" = "1"` would have looked for a point where the field `name` and the field `1` were equal (but there was no field named `1`, so nothing matched).

**Comment by ikovalyov** [comment]
Hi, @jsternberg
1.0.0-beta3 didn't help.
I executed select top 3 query. After 14 hours influxdb ate 7GB RAM and 30 GB of swap.  After that service was restarted.

**Comment by ikovalyov** [comment]
@mark-rushakoff 
Thanks, I was able to get results from that query.

Here is updated performance info:
```
SELECT * FROM "performance" limit 10
```
No response, ate all available memory.

```
SELECT * FROM "performance" WHERE "name" = '1' limit 2000
```
Response within 2 seconds, still slow but works much better. Looks like there is huge performance drop if select query without params.

**Comment by jsternberg** [comment]
Can you try using chunked responses? How many points are inside of the performance database?

```
$ curl -G 'http://localhost:8086/query?chunked=true
```

**Comment by jsternberg** [comment]
It turns out that lazy iterators are not in beta3 but they are in the nightly. Can you try using that?

**Comment by ikovalyov** [comment]
InfluxDB Admin UI: v1.1.0~n201608180800
Server: v1.1.0~n201608180800

SELECT * FROM "performance" limit 10
Takes 2.3s to be executes which is awesome.
Thanks.

**Comment by jimaek** [comment]
@jsternberg Will lazy iterators be part of v1 stable when its released?

**Comment by ikovalyov** [comment]
performance db has 1123229054 points

**Comment by jsternberg** [comment]
Due to a bug, we had to back out lazy iterators for v1 stable. We continue to be aware of this issue though and are working on a fix. No news on an ETA yet for that fix to be included in a release. Sorry.

**Comment by jsternberg** [comment]
Closing this in favor of #7182. This is an issue with `LIMIT` and a large number of shards and/or series. It is certainly something we are working to address. Sorry for the inconvenience. For the moment, you can get around this issue by using a `WHERE` clause to limit the time that will be queried.
