### ISSUE TITLE
CPU usage spikes and db not usable under simple select queries from grafana

### ISSUE THREAD

**Issue by code-decode** [influxdata/influxdb#7160]
I posted my question on google groups, but trying to find an answer here. 

My setup is running on a single 4 cpu instance on aws. 0.13 version
Ingests about 5000 measurements with 4 tags each every 3 hours. 
Disk has provisioned iops set to 2000 and i/o wait might not be a problem

On simple select queries I get a lot of user cpu spikes(80-90%) and timeouts. If I request again after a while, it may work fine. 

https://gist.github.com/code-decode/ec1b68ddc504256d8923f28bc52747e0

I tried to follow steps on https://github.com/influxdata/influxdb/issues/5440#issuecomment-233230997 
alter retention policy default on influx_prod duration 520w
but this did not help.

Any help would be appreciated!

**Comment by KiNgMaR** [comment]
You should try v1.x (nightly or beta), it seems to have fixed excessive resource usage in many workloads.

**Comment by code-decode** [comment]
@KiNgMaR I tried updating to 1.0 from https://influxdata.com/downloads/#influxdb yesterday however that did not help so I reverted back. 

https://groups.google.com/forum/#!msg/influxdb/5_kGGQeSkMM/avPvxL4hAwAJ

Also little wary of using a beta version for my setup.

**Comment by code-decode** [comment]
If required, I can update my influxdb version and add diagnostics gists from the 1.x beta.

**Comment by jsternberg** [comment]
Can you explain why the 1.0 beta didn't work? Is it still the same problem with speed? Can you also post the result of `SHOW STATS` so we know how many series you have?

**Comment by code-decode** [comment]
https://gist.github.com/code-decode/12a0406a378778e74980b8319829a511

**Comment by beckettsean** [comment]
@code-decode, yes, you have 2.5 million series. That's a fairly high RAM requirement. What is the RAM available on the box?

**Comment by code-decode** [comment]
@beckettsean @jsternberg ram is only 8gb. I did not understand cardinality in influxdb metrics before. I think i do now. Appreciate your help. I am exporting the data and will write it back into the system modified. Thanks for your kind help and awesome db!

**Comment by beckettsean** [comment]
Thanks, @code-decode! I'll close the issue for now.
