### ISSUE TITLE
Delete table left some dirty data in cache

### ISSUE THREAD

**Issue by tyronecai** [influxdata/influxdb#7164]
# Bug report
## System info

CentOS 7 64bit
influxdb-1.0.0_beta3 rpm
## Step
1. install influxdb-1.0.0_beta3.x86_64, use default config
   `yum install influxdb-1.0.0_beta3.x86_64.rpm -y`
2. create database 'mydb'
   `curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"`
3. put some normal data
   `curl -i -XPOST "http://localhost:8086/write?db=mydb" --data-binary 'pb,did=02000075 wechataccount1="123",stamp=1471157833i 1462348054000000000'`
   `curl -i -XPOST "http://localhost:8086/write?db=mydb" --data-binary 'pb,did=02000076 wechataccount1="123",stamp=1471157833i 1462348054000000000'`
4. select data in influx, we get column 'did' as expect

```
> select * from pb;
name: pb
--------
time                   did    stamp    wechataccount1
1462348054000000000     02000075      1471157833    123
1462348054000000000     02000076      1471157833    123
```
1. put some dirty data
   `curl -i -XPOST "http://localhost:8086/write?db=mydb" --data-binary 'pb,did=02000077 did="",stamp=1471157833i 1462348055000000000'`
2. select the data in influx, now we get an unknown column 'did_1', and all data on it

```
> select * from pb;
name: pb
--------
time                                    did  did_1           stamp           wechataccount1
1462348054000000000        02000075   1471157833      123
1462348054000000000        02000076     1471157833    123
1462348055000000000        02000077     1471157833
```
1. delete this table in influx and make sure of it

```
> delete from pb;
> select * from pb;
```
1. put some normal data
   `curl -i -XPOST "http://localhost:8086/write?db=mydb" --data-binary 'pb,did=02000075 wechataccount1="123",stamp=1471157833i 1462348054000000000'`
2. select the data in influx, we still get column 'did_1'

```
> select * from pb;
name: pb
--------
time                                    did   did_1          stamp            wechataccount1
1462348054000000000        02000075   1471157833    123
```
1. restart influxdb
   `systemctl restart influxdb`
2. select the data in influx, it's OK now

```
> select * from pb;
name: pb
--------
time                                     did              stamp              wechataccount1
1462348054000000000     02000075    1471157833     123
```

**Comment by jwilder** [comment]
No longer reproducible in 1.2.
