### ISSUE TITLE
Continous query how to check next run time

### ISSUE THREAD

**Issue by daaatz** [influxdata/influxdb#7167]
Hi,

like in topic, I have continous queries, but I dont know how can I check time of next run for them ? Is it possible ?
Also is it possible to run one of them faster ?

**Comment by jackzampolin** [comment]
@daaatz 

[Continuous Queries](https://docs.influxdata.com/influxdb/v0.13/query_language/continuous_queries/)
[CQs for Downsampling](https://docs.influxdata.com/influxdb/v0.13/guides/downsampling_and_retention/)

This space is for issues with the database. For questions please use our [Google Group](https://groups.google.com/forum/#!forum/influxdb) or join the InfluxDB channel on the [Gopher Slack](https://invite.slack.golangbridge.org/).

Thank you
