### ISSUE TITLE
CQs INTO divides results into two, fourrecords

### ISSUE THREAD

**Issue by maciejbak85** [influxdata/influxdb#7178]
Hi I have strange issue using CQs, I have metric called feautres, I want to get how much different users used some of them.

```
> select count(distinct(user_id)) from features where time > now() - 30d
name: features
--------------
time            count
1469011159734975678 31813

```

If I do query manually, to insert to results table it looks ok.

```
> select count(distinct(user_id)) INTO "features_monthly_active_users" from features where time > now() - 30d
name: result
------------
time    written
0   1

> select * from features_monthly_active_users
name: features_monthly_active_users
-----------------------------------
time            count
1469010080502189991 31815
```

31815 Is good number.

I have done CQs:

`CREATE CONTINUOUS QUERY "features_monthly_active_users" ON metrics RESAMPLE EVERY 1m BEGIN select count(distinct(user_id)) INTO "features_monthly_active_users" from features GROUP BY time(30d) END`

reasable is every 1m, just for easier testing, but on prod it should be 1d. As each new day I want last 30d information about users.
Look what I have in results:

```
> select * from features_monthly_active_users
name: features_monthly_active_users
-----------------------------------
time            count
1467072000000000000 5342
1467072000000000000 5342
1469664000000000000 24890
1469664000000000000 24890
```

:(

`SHOW CONTINUOUS QUERIES` shows my only this one CQs.. While testing first time it was:

```
> select * from features_monthly_active_users
name: features_monthly_active_users
-----------------------------------
time            count
1467072000000000000 5342
1469664000000000000 24890
```

which was also wrong.
Im not sure if its a bug or Im doing smth wrong.

**Comment by daaatz** [comment]
Another example:

`CREATE CONTINUOUS QUERY "features_monthly" ON metrics RESAMPLE EVERY 15s BEGIN select count(distinct(user_id)) INTO "features_monthly" from features GROUP BY time(30d), feature, device END
`
result:

```
> select * from features_monthly where feature = 'unique_group_profile'
name: features_monthly
----------------------
time			count	device	feature
1467072000000000000	26		unique_group_profile
1467072000000000000	26		unique_group_profile
1469664000000000000	192		unique_group_profile
1469664000000000000	192		unique_group_profile
```

where : 

```
> select count(distinct(user_id)) from features where feature = 'unique_group_profile' and time > now() - 30d
name: features
--------------
time			count
1469012090536687444	259

```

**Comment by daaatz** [comment]
and why TS is not time of this write ? but some other value, probably depensing on group by time

**Comment by jsternberg** [comment]
So I think there might be a misunderstanding of the syntax here. Resample tells it how often to run the query to pick up new data, but it doesn't tell it what time interval to run the query. The query will always run over a timespan of 30 days and the time spans don't overlap. If you want a time span that overlaps, you probably will need to use `moving_average()` (although I'm not sure how well that will work with CQs) so we might need an improvement for that.
