### ISSUE TITLE
20160819 Nightly crashes on start up

### ISSUE THREAD

**Issue by liv3d** [influxdata/influxdb#7180]
We're seeing the currently nightly crash on startup, before we're able to do anything within influx itself.

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB Nightly - 1.1.0~n201608190800-0 (Previous 1.0-Beta3 [now rolled back to])
O/S Centos 7
160GB Memory

One of the databases currently has 22 million series in this, we tried the nightly for #7138 to help reduce memory usage as we're seeing the memory hit 99% and Influx locking up at this point. (I know that this is over the hardware guide and we were talking to sales at one point, I'm going to chase this up internally). 

Crash dump that we managed to capture is at https://gist.github.com/liv3d/ef671975df4d7644d61aef4d0650abf9

**Comment by jwilder** [comment]
@benbjohnson

**Comment by jwilder** [comment]
Fixed via #7196
