### ISSUE TITLE
 Problems in upgrading from influxdb-0.11.0-1 to Enterprise Edition

### ISSUE THREAD

**Issue by bhavukJain** [influxdata/influxdb#7217]
We are trying to upgrade from Influxdb-0.11.0-1 to Influx Enterprise Edition (latest paid version). I have installed the meta nodes and installed them as well. But when I try to install the data nodes, after downloading them, it shows me transaction errors as follows: 

[centos@ip-10-24-34-146 ~]$ sudo yum localinstall influxdb-data-1.0.0_beta3_c1.0.0rc1.x86_64.rpm
Loaded plugins: fastestmirror
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Examining influxdb-data-1.0.0_beta3_c1.0.0rc1.x86_64.rpm: influxdb-data-1.0.0_beta3_c1.0.0rc1-1.x86_64
Marking influxdb-data-1.0.0_beta3_c1.0.0rc1.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package influxdb-data.x86_64 0:1.0.0_beta3_c1.0.0rc1-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved
# 
#  Package                                  Arch                              Version                                            Repository                                                              Size

Installing:
 influxdb-data                            x86_64                            1.0.0_beta3_c1.0.0rc1-1                            /influxdb-data-1.0.0_beta3_c1.0.0rc1.x86_64                             64 M
# Transaction Summary

Install  1 Package

Total size: 64 M
Installed size: 64 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test

Transaction check error:
  file /etc/influxdb/influxdb.conf from install of influxdb-data-1.0.0_beta3_c1.0.0rc1-1.x86_64 conflicts with file from package influxdb-0.11.0-1.x86_64
  file /usr/bin/influx from install of influxdb-data-1.0.0_beta3_c1.0.0rc1-1.x86_64 conflicts with file from package influxdb-0.11.0-1.x86_64
  file /usr/bin/influx_inspect from install of influxdb-data-1.0.0_beta3_c1.0.0rc1-1.x86_64 conflicts with file from package influxdb-0.11.0-1.x86_64
  file /usr/bin/influx_stress from install of influxdb-data-1.0.0_beta3_c1.0.0rc1-1.x86_64 conflicts with file from package influxdb-0.11.0-1.x86_64
  file /usr/bin/influx_tsm from install of influxdb-data-1.0.0_beta3_c1.0.0rc1-1.x86_64 conflicts with file from package influxdb-0.11.0-1.x86_64
  file /usr/bin/influxd from install of influxdb-data-1.0.0_beta3_c1.0.0rc1-1.x86_64 conflicts with file from package influxdb-0.11.0-1.x86_64
  file /usr/lib/influxdb/scripts/init.sh from install of influxdb-data-1.0.0_beta3_c1.0.0rc1-1.x86_64 conflicts with file from package influxdb-0.11.0-1.x86_64
## Error Summary

Should I take this as a normal installation or is there any error which I have to rectify?

**Comment by jwilder** [comment]
@jainbhavuk630 You won't be able to upgrade an 0.11cluster to enterprise clustering directly.  I'd recommend contacting support for assistance on a migration path.  cc @beckettsean 

@rossmcdonald Any idea what's going on with the packaging?

**Comment by rossmcdonald** [comment]
The Enterprise influxdb-data and OSS influxdb packages are considered distinct by the package manager, but have conflicting directory usages (hence the file conflicts around `/etc/influxdb`, etc). 

When installing Enterprise influxdb-data over OSS influxdb, the influxdb package should be erased from the RPM database prior to installing influxdb-data. For example:

```
# Assuming OSS InfluxDB is already installed...

# Erase InfluxDB from RPM database (does not erase data directories, only binaries and configuration)
sudo rpm -e influxdb

# Install influxdb-data
sudo yum localinstall influxdb-data-1.0.0_beta3_c1.0.0rc1.x86_64.rpm
```
