### ISSUE TITLE
Measurements is missing after restart cluster

### ISSUE THREAD

**Issue by r9liucc** [influxdata/influxdb#7229]
I have restarted influxdb one after another. When all server started, I found that all the measurements is missing in the database, but the database is still in here. All 3 nodes are the same problem - missing measurements.

Restart scripts:
```
sudo /etc/init.d/influxdb stop
sudo /etc/init.d/influxdb start
```

Notice that:
- My influxdb version is: 0.9.4.2
- I can find data in filesystem. But it seams that the count of the data files of each node is different.
- I check `show servers`, the raft status is true for all nodes.
- I check `show retention policies on event_query`, the result is
```
name   	duration       	replicaN       	default
default	0      		3      		true
```

**Comment by jsternberg** [comment]
Sorry @r9liucc, but we don't support that version of InfluxDB anymore. Clustering was also not fully functional for that version and was listed as an experimental feature so there's no guarantee that the code is even functional.
