### ISSUE TITLE
error : Retention policy not found: default

### ISSUE THREAD

**Issue by JiDongHyun** [influxdata/influxdb#7242]
### Directions

I want to write test by connecting the influxdb and telegraf.
The installation influxdb, telegraf was completed, However, when start the program, receive the error message

### Bug report

OS : Ubuntu 14.04
InfluxDB  : v 1.0
telegraf  : v 0.13

1. InfluxDB installation (v 1.0)

2. Telegraf installation (v 0.13)

3. Configure telegraf.conf file (input : StatsD, output : influxDB)
(configure it to use input **StatsD** and output **Influxdb** (etc/telegraf/telegraf.conf))

```
 [[inputs.statsd]]
#   ## Address and port to host UDP listener on
    service_address = ":8125"
#   ## Delete gauges every interval (default=false)
    delete_gauges = true
#   ## Delete counters every interval (default=false)
    delete_counters = true
#   ## Delete sets every interval (default=false)
    delete_sets = false
#   ## Delete timings & histograms every interval (default=true)
    delete_timings = true
#   ## Percentiles to calculate for timing & histogram stats
    percentiles = [90]
# 
#   ## separator to use between elements of a statsd metric
   metric_separator = "_"
# 
#   ## Parses tags in the datadog statsd format
#   ## http://docs.datadoghq.com/guides/dogstatsd/
   parse_data_dog_tags = false

#   ## Statsd data translation templates, more info can be read here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#graphite
   templates = [
        "* measurement.field"
   ]
# 
#   ## Number of UDP messages allowed to queue up, once filled,
#   ## the statsd server will start dropping packets
    allowed_pending_messages = 10000
# 
#   ## Number of timing/histogram values to track per-measurement in the
#   ## calculation of percentiles. Raising this limit increases the accuracy
#   ## of percentiles but also increases the memory usage and cpu time.
    percentile_limit = 1000
```

**4. Execute influxdb and telegraf , The error is occured**

**1) telegraf status**
```
2016/08/30 22:27:50 ERROR: {"error":"retention policy not found: default"}
2016/08/30 22:27:50 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
2016/08/30 22:28:00 Output [influxdb] buffer fullness: 6945 / 10000 metrics. Total gathered metrics: 6945. Total dropped metrics: 0.
2016/08/30 22:28:00 ERROR: {"error":"retention policy not found: default"}
2016/08/30 22:28:00 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
2016/08/30 22:28:10 Output [influxdb] buffer fullness: 6986 / 10000 metrics. Total gathered metrics: 6986. Total dropped metrics: 0.
2016/08/30 22:28:10 ERROR: {"error":"retention policy not found: default"}
2016/08/30 22:28:10 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
```

**2) influxdb status**
```
[httpd] ::1 - - [30/Aug/2016:22:27:50 +0900] "POST /write?consistency=any&db=telegraf_database_v10&precision=s&rp=default HTTP/1.1" 500 72 "-" "InfluxDBClient" 8c388a01-6eb5-11e6-81c7-000000000000 8570
[httpd] ::1 - - [30/Aug/2016:22:28:00 +0900] "POST /write?consistency=any&db=telegraf_database_v10&precision=s&rp=default HTTP/1.1" 500 72 "-" "InfluxDBClient" 922eb8fd-6eb5-11e6-81c8-000000000000 7224
[httpd] ::1 - - [30/Aug/2016:22:28:10 +0900] "POST /write?consistency=any&db=telegraf_database_v10&precision=s&rp=default HTTP/1.1" 500 72 "-" "InfluxDBClient" 9824a048-6eb5-11e6-81c9-000000000000 5867
```

**Comment by jsternberg** [comment]
Try upgrading your Telegraf version. We updated the name of the default retention policy and Telegraf needed to be updated so it didn't hard code default as the retention policy.

**Comment by jsternberg** [comment]
Closing this since it seems to be an issue with using an old version of Telegraf.

**Comment by JiDongHyun** [comment]
Thank you @jsternberg  I solved the problem!

**Comment by directred** [comment]
Had this same error recently running Influxdb 1.2.2 after upgrading my Logstash output plugins. Added the retention_policy => "default" line in my logstash pipeline which fixed the issue. See my pipeline below

filter {
  metrics {
    meter => "events"
      add_tag => "metric"
    }
}


output {
      # only emit events with the 'metric' tag
  if "metric" in [tags] {
    file {
      path => "/var/log/logstash/metrics.log"
      codec => line {
        format => "1m rate: %{[events][rate_1m]} ( %{[events][count]} )"
      }
    }
    influxdb {
      coerce_values => { '1m' => 'float'
                         '5m' => 'float'
                         '15m' => 'float'
                         'count' => 'integer' }
      data_points => { "hostname" => "hostname"
                         "nodetype" => "ingest"
                         "1m" => "%{[events][rate_1m]}"
                         "5m" =>"%{[events][rate_5m]}"
                         "15m" => "%{[events][rate_15m]}"
                         "count" => "%{[events][count]}" }
      send_as_tags => [ "hostname", "nodetype" ]
      host => "hostname"
      **retention_policy => "default"**
    }
  }
