### ISSUE TITLE
after disk full -  panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by floored1585** [influxdata/influxdb#7244]
### Bug report

__System info:__ 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

Linux <hostname> 3.13.0-93-generic #140-Ubuntu SMP Mon Jul 18 21:21:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

InfluxDB v0.13.0 (git: 0.13 e57fb88a051ee40fd9277094345fbd47bb4783ce)

__Steps to reproduce:__

I haven't tried reproducing this outside of this machine.

__Expected behavior:__

Influxdb starts successfully

__Actual behavior:__ 

On startup while reading files, the following crash occurs:
https://gist.github.com/floored1585/422a042a936b35ed265ada06a01e882b

__Additional info:__ 

This crash began happening after the disk filled up to 100% and then was extended (LVM).

It doesn't seem to crash at the same place/time each time -- sometimes it'll load files for 5 minutes before crashing and sometimes it'll crash immediately.

**Comment by jwilder** [comment]
This should be fixed in the `1.0` release line by #6794.  Upgrading to `1.0.0rc2` should have the fix.
