### ISSUE TITLE
Cann't compile InfluxDB on Windows

### ISSUE THREAD

**Issue by davweiss** [influxdata/influxdb#7251]
### Bug report
Got Error follow Error with `go get -u -f ./...`:

```
# github.com/influxdata/influxdb/services/collectd/test_client
services\collectd\test_client\client.go:62: not enough arguments in call to conn.Write
```

Steps to reproduce:
	Compiling on Windows:
```
cd c:\go
mkdir projects
set "GOPATH=C:\Go\projects"
cd %gopath%
go get github.com/influxdata/influxdb
cd src\github.com\influxdata\influxdb
go get -u -f ./...
go build ./...
```

System info:
	InfluxDB version: Commit: c3fb8b8ef83def5d720bd6ead65fa055c063c78a
	Operating system name: Windows 10 Enterprise x64
	GO 1.7

**Comment by mark-rushakoff** [comment]
We manage our dependencies with [gdm](https://github.com/sparrc/gdm). Using `go get` will not retrieve the correct versions of the dependencies.  

See also [appveyor.yml](https://github.com/influxdata/influxdb/blob/c3fb8b8/appveyor.yml) for how we build on Windows in CI.
