### ISSUE TITLE
How to set path for every database?

### ISSUE THREAD

**Issue by fooevr** [influxdata/influxdb#7253]
hi, I have two databases and I want to save on different volume, but inlfuxdb.conf just have a global config item. How to set path for every database?
thanks.

**Comment by rossmcdonald** [comment]
Currently there is no way to set a per-database data directory configuration, however the database name is always set as the first-level directory name in the InfluxDB data directory. For example, if you have the config set to:

```
[data]
...
  dir = "/var/lib/influxdb/data"
...
```

Then a database with the name `mydb` will be placed in the directory:

```
/var/lib/influxdb/data/mydb
```
