### ISSUE TITLE
Permission Denied to create retention Policy monitor and Failed to create internal Storage

### ISSUE THREAD

**Issue by nrsekhar** [influxdata/influxdb#7259]
Hi ,

After restoring My LXC container (influxdb) I am getting error in logs.

Logs : 
monitor] 2016/09/06 11:26:52 failed to create retention policy 'monitor', failed to create internal storage: open /var/lib/influxdb/meta/meta.dbtmp: permission denied
[monitor] 2016/09/06 11:26:52 failed to store statistics: open /var/lib/influxdb/meta/meta.dbtmp: permission denied
[monitor] 2016/09/06 11:27:02 failed to create retention policy 'monitor', failed to create internal storage: open /var/lib/influxdb/meta/meta.dbtmp: permission denied
[monitor] 2016/09/06 11:27:02 failed to store statistics: open /var/lib/influxdb/meta/meta.dbtmp: permission denied
[monitor] 2016/09/06 11:27:12 failed to create retention policy 'monitor', failed to create internal storage: open /var/lib/influxdb/meta/meta.dbtmp: permission denied
[monitor] 2016/09/06 11:27:12 failed to store statistics: open /var/lib/influxdb/meta/meta.dbtmp: permission denied
[monitor] 2016/09/06 11:27:22 failed to create retention policy 'monitor', failed to create internal storage: open /var/lib/influxdb/meta/meta.dbtmp: permission denied
[monitor] 2016/09/06 11:27:22 failed to store statistics: open /var/lib/influxdb/meta/meta.dbtmp: permission denied
[monitor] 2016/09/06 11:27:32 failed to create retention policy 'monitor', failed to create internal storage: open /var/lib/influxdb/meta/meta.dbtmp: permission denied
[monitor] 2016/09/06 11:27:32 failed to store statistics: open /var/lib/influxdb/meta/meta.dbtmp: permission denied
 

I am not sure whats going wrong and no clue on whatever information required to debug the issue,please help me to rectify the issue.

Thank you,
Natraj

**Comment by jsternberg** [comment]
Hello @nrsekhar,

The InfluxDB GitHub issues are only for feature requests and bug reports. I think you'll get much better help by sending this message to the [mailing list](https://groups.google.com/forum/#!forum/influxdb).

Thanks!
