### ISSUE TITLE
querying_data missing output format line protocol?

### ISSUE THREAD

**Issue by steverweber** [influxdata/influxdb#7260]
https://docs.influxdata.com/influxdb/v0.13/guides/querying_data/

querying data API seems to be missing output format "line protocol" as an option. 
EDIT related to : https://github.com/influxdata/influxdb/issues/6234

This option would make dumping and importing data simple like it was in the past with JSON.

```
perhaps something like: format=line

curl -GET 'http://localhost:8086/query' --data-urlencode 'db=somedb' \
    --data-urlencode 'format=line' \
    --data-urlencode 'epoch=ms' \
    --data-urlencode 'q=SELECT * from oat01_action' | gzip > dump

cat dump | gzip -d | \
    curl -XPOST -d @- 'http://host2:8086/db/test/series?u=xzc&p=zxvcwae'
```

something like the above was simple when writing using JSON was enabled... sadly that is now gone.

**Comment by steverweber** [comment]
from: https://docs.influxdata.com/influxdb/v1.0/tools/shell/

it shows option `-import`

says to go to: https://github.com/influxdata/influxdb/tree/master/importer

The doc shows an api call `/export` cool.. but that call is missing from: https://docs.influxdata.com/influxdb/v1.0/tools/api/
and don't seem to work?

**Comment by jsternberg** [comment]
If you look at the docs for the importer, that is a tool to migrate from 0.8. I think we may have a tool to export data for 1.0 though. I think you can do it using `influx_inspect export` and then that can be imported with `influx -import` too.

**Comment by steverweber** [comment]
i was looking at `influx_inspect export` it seems like I can get it to work.. but it's really not built for this task. I'll need `mkfifo` an output file to workaround it not having an stdout option.. then pip the 60+GB of data to a production system that'll change the data precision using some hacky sed or grep and drop `tsm1_` records .... not too happy with the solution but it has to be done.

**Comment by jsternberg** [comment]
Can you expand on what portions (besides the lack of a stdout option) would help make it better? I'm afraid I don't understand what you mean by changing data precision.

**Comment by steverweber** [comment]
plan on exporting the data and importing it to a new server but with a data precision of seconds...

im going to try something like... 
```
mkfifo export
influx_inspect export -datadir /var/lib/influxdb/ -out export &
tail -n 9999999 -f export | sed '/tsm1_/d' | gzip > export_no_tsm1
# force time from nanoseconds to seconds for sometablename
cat export_no_tsm1 | gzip -d | grep sometablename | sed -r 's/([^ ]* [^ ]* [[:digit:]]{10}).*/\1/' > sometablename_seconds
```

for import... going to try and keep it simple and stream it in using curl in ~500line batches.
doint it this way because i can include `&precision=s` in the url.
`cat sometablename_seconds |`
```
#!/bin/bash
url='https://influxdb.math.xxx.ca:8086/write?db=test&u=xxxxx&p=zzzzzzzzz&precision=s'
procc=0
while read line
do
    lines=$line$'\n'
    for i in $(seq 1 500)
    do
        read line
        lines+=$line$'\n'
    done
# perhaps use tmp file 
curl -X POST $url --data-binary @- <<EOF
$lines
EOF
done
```

**Comment by jwilder** [comment]
The export tool is really the way to export shard data.  Converting the precision is something you'll need to do after on the exports themselves.
