### ISSUE TITLE
Cumulative Distribution Functions

### ISSUE THREAD

**Issue by szaydel** [influxdata/influxdb#7261]
### Feature Request

__Proposal:__ Addition of Cumulative Distribution Function as another function exposed to users.

__Current behavior:__ No existing alternative that I am aware of.

__Desired behavior:__ Running data through CDF should result in probability computation as expected from a traditional CDF function, where given data and a value to compare against that data, a probability of that value and anything less than that value being in the distribution is produced.

__Use case:__ This is a useful function for prediction of likely values in the dataset(s), as well as for measuring likelihood of presence of any given value in the data.

**Comment by jsternberg** [comment]
Can you give examples of the types of functions you want to see?

**Comment by samhatchett** [comment]
+1 
PDF/CDF would be quite useful. This issue seems like a good candidate for inclusion in #5930 - similar to the request for Histogram

**Comment by jwilder** [comment]
Moved this to #5930.

**Comment by szaydel** [comment]
Sorry about not replying, I completely missed updates on the thread. Yes, PDF/CDF would be great, right along with histograms.
