### ISSUE TITLE
All the downloads are telegraph

### ISSUE THREAD

**Issue by chengweiv5** [influxdata/influxdb#7267]
the download link [here](https://www.influxdata.com/downloads/#influxdb) just shows telegraf 4 times like below

![bug](https://cloud.githubusercontent.com/assets/689798/18334341/5301bdb4-75a9-11e6-887a-c4d25990e76e.png)

click everyone shows up the telegraf download & install instructions.

**Comment by chengweiv5** [comment]
another screenshot after chosen InfluxDB to download

![bug2](https://cloud.githubusercontent.com/assets/689798/18334415/c5dfd38e-75a9-11e6-9a41-3809a6ab5c09.png)

which says influxdb in title, but telegraf in details.

**Comment by toddboom** [comment]
@chengweiv5 we're pushing some updates to our site, so this will be fixed tonight. i'm closing this out since it's not related to issues with InfluxDB.
