### ISSUE TITLE
ERR: invalid operation: time and *influxql.BinaryExpr are not compatible

### ISSUE THREAD

**Issue by geekard** [influxdata/influxdb#7270]
influxdb v1.0 doesn't support time string adding/subing time offset, but v0.13 does

> select stddev("avgLoss") from ping_statistic where time > '2016-09-09' - 1h;

ERR: invalid operation: time and *influxql.BinaryExpr are not compatible

**Comment by jsternberg** [comment]
Confirmed the regression. This was introduced by f2fd988. I'm working on a fix and I'll backport it to 1.0.

cc @jwilder

**Comment by jsternberg** [comment]
Fixed via #7276.

**Comment by anichari** [comment]
Hi @jsternberg , when does this fix make it to the docker image? Or, how can I get a docker image with the fix
