### ISSUE TITLE
[1.0] Higher CPU usage and pointReq growing after upgrade from 0.11

### ISSUE THREAD

**Issue by ZhukovAlexey** [influxdata/influxdb#7275]
__System info:__ 1.0, RHEL 7

__Steps to reproduce:__

1. Upgrade from 0.11 up to 1.0
2. High CPU and and pointReq growing.

It is really similar to https://github.com/influxdata/influxdb/issues/6620

After upgrading from 0.11 to 1.0 the CPU usage has grown in 2 times.

![host_cpu](https://cloud.githubusercontent.com/assets/1679467/18395275/9ed6232e-76c6-11e6-87a2-54ac5065b10a.png)

I have a graph with SELECT derivative("pointReq", 1s) FROM "write"  (it was on your blog and it would be good to have a dashboard with all important system metrics, but I didn't find any info about this)

And the count of points has also grown from 2k points to 3k points.

![influx_points_req](https://cloud.githubusercontent.com/assets/1679467/18395632/e52c1c10-76c7-11e6-92a3-3af9b052abf6.png)

After downgrade to 0.12.2 (from https://github.com/influxdata/influxdb/issues/6620 I got that 0.13 wasn't a good candidate to choose) CPU goes back to normal and pointReq also goes to its normal values.

I don't know how count of points could grow over Influx version, I have a really stable workload as you can see.

All required diagnostics is here [diagnostics.zip](https://github.com/influxdata/influxdb/files/464447/diagnostics.zip)

**Comment by jwilder** [comment]
We actively use more cores in 1.0.  Higher cpu utilization should be expected.

**Comment by ZhukovAlexey** [comment]
@jwilder I'm sorry but could you please tell me what's so new in 1.0 has been added to lead 2x CPU utilization on the same workload?

**Comment by ZhukovAlexey** [comment]
To whom it may concern: 

I've done an upgrade to the latest 1.1 version and I can't see any CPU usage difference between 0.11 and 1.1. 

So I can recommend trying to install new version to see if it works fine in your environment.
