### ISSUE TITLE
Aggregation functions should provide interpolation when aggregating multiple series

### ISSUE THREAD

**Issue by jaredgisin** [influxdata/influxdb#728]
As a general purpose time series database, I was surprised to see that the aggregation functions do not perform interpolation. 

http://opentsdb.net/docs/build/html/user_guide/query/aggregators.html

Given mutliple series that report the same value over time at an irregular interval (like happens in the real world), the summation of such series with a query like:

select sum(value) from /disk.capacity.*/ group by time(5s)

produces a single value. I would expect it to first down sample each series matching /disk.capacity.*/ on 5s intervals, and then if necessary, interpolate each of those series to produce a correct aggregation.

This only roughly works if the group by time interval matches the reporting interval of the original series, but even that can produce a wavy summation line out of otherwise flat time series graphs due to the aggregation function having no idea about how many value it should expect in the sum and compute appropriate values from each series to fill in the missing values in the aggregate series.

The problem seems to be further worse in that the actual output sum in the query above for identical flat-line graphs is multiplied if the group by time() value is multiplied. For example in the above, group by(10s) will produce sums that are twice than what is expected.

Is this something that is on the roadmap to address?

**Comment by nazgu1** [comment]
> We'll be adding other options to fill later like mean, previous, and next.

When will you plan to add this options to fill() ?

**Comment by pauldix** [comment]
Either as part of the 0.9.0 release or in a point release shortly afterwards
