### ISSUE TITLE
Google search results bring up old documentation pages

### ISSUE THREAD

**Issue by dandv** [influxdata/influxdb#7282]
I think pretty much every InfluxDB Google search I've tried, has surfaced old docs, most often v0.8 or v0.9.

Any ideas for popping up the current docs first? How about adding

    <link rel="canonical" href="...link to current version">

in the `<head>` of old documentation pages?

**Comment by jsternberg** [comment]
Thanks @dandv. Can you make this issue at https://github.com/influxdata/docs.influxdata.com instead? I'm going to close this one because this issue tracker is for the software itself rather than the documentation.

**Comment by dandv** [comment]
Good catch. I've added to the discussion at https://github.com/influxdata/docs.influxdata.com/issues/207#issuecomment-246091590.
