### ISSUE TITLE
Document the integration with LetsEncrypt

### ISSUE THREAD

**Issue by dandv** [influxdata/influxdb#7283]
LetsEncrypt has revolutionized SSL certificate generation, and is extremely easy to use (`letsencrypt certonly -d mydomain`) and automate. It would be fantastic if InfluxDB could use directly the `.pem` files that LetsEncrypt generates (it appears that [some files need to be concatenated now](https://github.com/influxdata/influxdb/issues/1310#issuecomment-220161778), but it's [unclear which](https://groups.google.com/forum/#!msg/influxdb/Xf8fLoRIJXc/oBndOI7WBQAJ)). There's also an [option to specify the private key separately](https://github.com/influxdata/influxdb/pull/6666), which is nice but confuses things for LetsEncrypt users.

LetsEncrypt generates the following files:

```
cert.pem  (not interesting)
chain.pem  (not interesting)
fullchain.pem  <-- full certificate chain
privkey.pem  <-- private key
```

The correct configuration in `/etc/influxdb/influxdb/conf` is:

    https-certificate = "/etc/letsencrypt/live/yourdomain.com/fullchain.pem"
    ### Use a separate private key location.
    https-private-key = "/etc/letsencrypt/live/yourdomain.com/privkey.pem"

This makes setting up SSL easy and something the user will never have to worry about, as LetsEncrypt will automatically renew the files before the certificate expiration date.

----

Below are potential errors, for SEO.

Trying to supply `cert.pem` to `https-certificate` results in the following error:

> crypto/tls: found a certificate rather than a key in the PEM for the private key

even if `https-private-key` points to `privkey.pem`.

Not including the full chain can also result in `unable to verify the first certificate` when [connecting with certain client libraries](https://github.com/node-influx/node-influx/issues/176), even though the connection succeeds in the browser.

**Comment by dandv** [comment]
Turns out InfluxDB can actually already use the `cert.pem` and `privkey.pem` files, though only for the `[admin]` section, due to #7284.

This issue then becomes one of documenting how this can be done. Recommending a specific certificate tool may be a tiny bit beyond the scope of [the docs](https://docs.influxdata.com/influxdb/v1.0/administration/config/#https-certificate-etc-ssl-influxdb-pem), but given the lack of an example on that page, which has lead to use questions on the forum, I'm inclined to think it would help much more than it would harm.

Happy to submit a PR once #7284 is settled.

**Comment by jwilder** [comment]
Since this is docs issue.  Can you re-open it here: https://github.com/influxdata/docs.influxdata.com

**Comment by prune998** [comment]
Will comment here and keeps looking, but LetsEncrypt also generate really short-living certs (3 months).
Is there a way to reload the certs without stop/start influxdb ?

**Comment by vicatcu** [comment]
@dandv I just want to say thanks for your insights... I was using the cert.pem for https-certificate rather than fullchain.pem. Also had to change some folder permissions (/etc/letsencrypt/archive and /etc/letsencrypt/live to 750) and added userinfluxdb to the root group to get it to work, but it works like a charm after that :+1:

**Comment by odarriba** [comment]
Any solution for what @prune998 asked?
It will be good to force certificate reloading from point to point without having to restart the InfluxDB instance completely.

Has anyone got any way of doing it?

**Comment by prune998** [comment]
check Caddy, nginx-lego or traefik who implemented that in GO already... maybe it can help get it done faster (as this issue is more than a year old now :) )

**Comment by eh8** [comment]
> @dandv I just want to say thanks for your insights... I was using the cert.pem for https-certificate rather than fullchain.pem. Also had to change some folder permissions (/etc/letsencrypt/archive and /etc/letsencrypt/live to 750) and added user influxdb to the root group to get it to work, but it works like a charm after that +1

For those viewing this thread now, please bear in mind that this is not necessarily secure if you run bare-metal installs of influx. If you run everything in secured containers then I suppose you are fine.

First, chmod 750 will prompt certbot to complain that there are unsafe permissions present. Furthermore I am weary of adding `influxdb` as a `root` member of my system and granting it broad access to directories and files it shouldn't normally see.

A necessary step that was not mentioned is exposing the `influxdb` user to your private keys, or else influx will not have necessary permissions to read the keys. This is the most sketchy.

**Comment by therealbat** [comment]
> A necessary step that was not mentioned is exposing the `influxdb` user to your private keys, or else influx will not have necessary permissions to read the keys. This is very sketchy.

probably a lot less painful approach is to add a new group, say 'letsencrypt' - chgrp the dirs 'live' and 'archive' to it and set the permission to 0710 - as you don't need read permission for path traversal. the dirs below live and archive already have 0755 permissions, so no need to touch them. the single thing that needs adjustment is the file privkey1.pem in archive/your.host.name. just chgrp the file to 'letsencrypt' and add group read to it (0640).

it doesn't matter if certbot will revert the permissions as a post-install hook script can fix them afterwards.
this way Influxdb has only access to its own cert and private key, and is not a member of the group root.
