### ISSUE TITLE
Admin interface: the password is visible and gets stored in the autofill form data

### ISSUE THREAD

**Issue by dandv** [influxdata/influxdb#7285]
![image](https://cloud.githubusercontent.com/assets/33569/18408165/62279a32-76dc-11e6-94f9-df207eb4b9de.png)

**Comment by dandv** [comment]
Fixed by PR #7286. Not sure why GitHub didn't automatically detect that, since the PR title does mention this issue number. Maybe they only look in the commit message?

**Comment by jsternberg** [comment]
Fixed via #7286.
