### ISSUE TITLE
`auth` fails silently in the CLI

### ISSUE THREAD

**Issue by dandv** [influxdata/influxdb#7290]
Running the `auth` command with a wrong user/pass combination is indistinguishable from authenticating correctly (no output in either case). Is this intended? The authentication error will only be revealed when the next operation fails (`ERR: error authorizing query`).

IMO this is highly counter-intuitive (I don't recall ever seeing this type of behavior on failed logins in any other CLI tool).

**Comment by desa** [comment]
I agree that this behavior is non-intuitive. The reason there isn't any validation until you try to issue some command is because the `auth` command doesn't actually make any network calls. It simply sets the context for the underlying client.

https://github.com/influxdata/influxdb/blob/master/cmd/influx/cli/cli.go#L307-L337

https://github.com/influxdata/influxdb/blob/master/client/influxdb.go#L154-L158

**Comment by mrichman** [comment]
Would it make sense for `SetAuth()` to do an HTTP HEAD request (or some other light request) to validate credentials?

**Comment by pmyjavec** [comment]
@corylanou, 

After having a go of this, I just realised that there isn't really a reliable way to do this presently.  Originally I tried to use `client.Ping()`, but that doesn't actually check if a user is authenticated as far as I can tell. Then I was just running a query such as `SHOW DATABASES`, which is fine for admin users, but breaks for user without the correct level of access.

I basically don't think there is a reliable way to do this currently. I will maybe raise an issue which we can do something like adding something to the query language, like `SHOW AUTHENTICATED` or `WHOAMI` which can check if the user has supplied valid credentials and return an error if they haven't.

Thoughts?

**Comment by corylanou** [comment]
We could probably change one of the endpoints to validate auth if it's present.  It's not a very straightforward operation as the HTTP endpoint simply captures the credentials and sends them on.  we would then have to create another hook in the system to just validate auth.  Enterprise does this different than OSS, but they both share the same library, so both concerns would have to be addressed at the same time.

**Comment by drmclean** [comment]
Is there any update on this? I'd love to have some more obvious messages that the username/password were incorrect.
