### ISSUE TITLE
Permission denied while opening .pem file readable by others

### ISSUE THREAD

**Issue by dandv** [influxdata/influxdb#7292]
### Bug report

__System info:__ influxd 1.0.0 on Ubuntu 16.04.1.

__Steps to reproduce:__

1. Create a certificate with LetsEncrypt: `[stop web server if any &&] apt install letsencrypt && letsencrypt certonly -d mydomain.com`
2. See what the symlink created by LetsEncrypt points to:

        ls -al /etc/letsencrypt/archive/mydomain.com/cert.pem

3. Check the file attributes (it should be readable by all), e.g.

        ls -al /etc/letsencrypt/archive/mydomain.com/cert1.pem` will show `-rw-r--r--`

4. Edit influxdb.conf to point to the certificate in the `[http]` section:
5. `systemctl restart influxdb`  # wait ~10 seconds
6. `journalctl -u influxdb`

I see the service failing, and somewhere up buried in the logs is this error:

    run: open server: open service: open /etc/letsencrypt/archive/mydomain.com/cert1.pem: permission denied

If I execute influxd as root ([not a good idea](https://github.com/influxdata/influxdb/issues/4824#issuecomment-158202206)), it launches successfully, and SSL works.

I've even created a special group to give access to the `.pem` files, but I keep getting the same error.

```bash
addgroup sslapps
adduser influxdb sslapps
chown -vR :sslapps /etc/letsencrypt/archive/yourdomain/
chmod -vR g+r /etc/letsencrypt/archive/yourdomain/
```

**Comment by dandv** [comment]
Solution: make sure that all directories leading up to the `.pem` file(s) are e`x`ecutable by the group. For example, using `[namei](http://unix.stackexchange.com/questions/82347/how-to-check-if-a-user-can-access-a-given-file/157673#157673)`:

    namei -l /etc/letsencrypt/live/yourdomain/cert.pem

**Comment by dalu** [comment]
just adding a comment for the lazy
`chmod go+x /etc/letsencrypt/archive`
`chmod go+x /etc/letsencrypt/live`

**Comment by Alexander-Kreisler** [comment]
You Sir, are a scholar and a gentleman. Hvala & Danke!

**Comment by holdsworth** [comment]
I tried everything, I encounter the same issue and nothing helped so far.

**Comment by wrossmorrow** [comment]
These aren't working for me either

**Comment by ankitInfyOm** [comment]
Please give me a solution
```
[ErrorException]
  file_get_contents(C:\wamp64\bin\php\php7.1.9\extras\ssl): failed to open stream: Permission denied
```

**Comment by dalu** [comment]
@wrossmorrow read again carefully, you're supposed to give group and others execute permission the the 2 above mentioned directories.

@ankitInfyOm this has nothing to do with influxdb. It's about some php script not being able to open a certain file or dir. One line of error log taken out of context won't help you get help.
