### ISSUE TITLE
Lazily initialize iterators within series and shards

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#7303]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

**Proposal:** Lazily initialize iterators within each series and shard to lower the memory usage of the query engine when processing high cardinality data and make queries with limits faster.

**Current behavior:** Every shard iterator is initialized at the same time and there is a separate iterator for every series within every shard. With high cardinality data, this uses up a lot of memory as a baseline for even initializing the query. We also do not keep the returned series separate from each other when returning data from the shard which causes limit queries to return at least one data point from every shard within the time period rather than only reading the points it needs.

**Desired behavior:** We should only initialize the iterators we need. That means we need to organize them by the returned series and only initialize them when they are needed. They will also need to be sorted ahead of time by the shard start and end times.

**Use case:** This is required for LIMIT to run quickly when given an unbounded time and also for preventing OOM errors when a query has high cardinality.

**Comment by jsternberg** [comment]
I'm starting to experiment with this. I'm currently trying to work through the problem and I'll try to post a coherent write up by the end of day today.

**Comment by jsternberg** [comment]
I'm working on a prototype, but I think I've got the general gist of this.

So we'll need to modify how we create iterators when we've got a group of shards. At the moment, we retrieve a list of shards by the time range and then create iterators for every shard at the same time. Instead of retrieving individual shards, we will need to organize the sources alphabetically by their measurement name. Then we'll make a lazy iterator that creates a new Iterator for each measurement. Within each measurement, we'll need to retrieve the shard groups for that database and retention policy. Since we need to return the points in the order of their series key (not their shard group time), we will need to retrieve the tag sets from every shard before creating the iterators. I don't think we can do this portion lazily at the moment. We then have to have some kind of heap that organizes a shard group with the tag sets for that shard. Inside of that heap, we will prioritize the earliest series key. If the series keys are the same, we will prioritize an earlier shard group. Once we have decided on a shard group and series key combination, we will create a single iterator and will iterate through that completely before repeating this process.

That was a bit complicated of an explanation, so I'll try to organize it a bit more simply below.

1. Sort measurements by name.
2. Create a lazy iterator for each measurement.
3. Retrieve the shard groups for that measurement within the given time range.
4. Retrieve TagSets from every shard within every shard group (might be a problem?)
5. Create heap that is sorted by first series key in the TagSet first and shard start time second.
6. Create an iterator for a single series by popping a TagSet/Shard grouping off of the heap.
7. Read from that iterator.
8. If there are more TagSets, go to 4.
9. If there are more measurements, go to 2.

I don't know if the creation of the TagSets for every Shard is going to strain memory too much, but I'm not sure how else to do it. If it is, we might need to figure out how to create a version of the TagSets that uses less memory. The problem is that the series key needs to be prioritized before the shard group. While the shard group time is important and useful for organizing a series, we could have a series `cpu,host=server01` that starts in the last shard and a series `cpu,host=server02` that starts in the first shard. Unfortunately, we have to read from `cpu,host=server01` first even if it's in a later shard.

**Comment by srikara** [comment]
+1

**Comment by jsternberg** [comment]
Working on this further, retrieving the tag sets is definitely going to be a problem. Using the jwilder/ratings repository and using the query, I'm able to get the tag set calculation down to about 1 minute by parallelizing it and then about 15 seconds after that to return the `LIMIT 1`. This is before the tag sets have to be sorted by time and key.

I'm going to continue seeing if I can optimize that though. We might be able to offset some of that by using a heap. The main problem though is that we can't rely on the shard's start times to perform the sort. I'll also see if it's possible to separate the discovery of the series keys from the key itself since we don't need the tag sets, just the series keys to perform the sort.

**Comment by jsternberg** [comment]
I have a prototype, but I don't think it actually resolves the issue since I don't think anything ends up actually being lazy. The problem is that when you don't use a `GROUP BY`, I don't think there is actually a way to lazily return values. First, let's talk a bit about raw queries.

When it comes to a raw query, you first need to determine what the resulting series key the other series are going to be merged into. We do that by creating a tag set, which is a grouping of series keys to be merged into the same series. We can then later initialize all of these series and merge them into the same stream. We can also pretty safely organize the tag sets into the correct order because we know what tag set all points within that stream will be and so this lends itself pretty easily to using lazy iterators. The problem is that, inside of the same tag set, we do seem to have to initialize all of the iterators at the same time so that we can merge those streams together. For raw queries, we need to do that by time. For aggregates, we just need to organize them by the aggregate interval. But, without a `GROUP BY` of some kind to organize tags, we have to initialize 1M iterators at the same time when there are 1M series.

To be clear, **I think this is the biggest issue of what I'm saying**. The rest of the stuff in here is just kind of extra and I think can be worked around. I don't see of any way to avoid initializing one iterator for every series key at the moment. @jwilder any advice?

But then the thought comes that we might be able to only initialize one shard group at a time rather than all of them. As mentioned above, all iterators for all shard groups need to be initialized at the same time because we may need to retrieve a series key from the last shard before retrieving a series key from the first shard. We might be able to reduce this burden by having a special type of iterator that only initializes an iterator by series key rather than attempting to reuse the merge iterator, but that still won't get around the previous issue. I'll try that anyway though since that was the original plan.

**Comment by beckettsean** [comment]
Related `KILL QUERY` enhancement: https://github.com/influxdata/influxdb/issues/7457

**Comment by jsternberg** [comment]
This didn't work and we'll reevaluate this type of solution for some other future work. Organizing the iterators by time didn't work because they are sorted by the tags first.
