### ISSUE TITLE
Aliasing on downsampling

### ISSUE THREAD

**Issue by eppak** [influxdata/influxdb#7325]
Hello,
i have a influx 1.0 on a debian 8.5 64bit and a database with a standard sine signal. If i downsample the data with (for example) a mean value i got an aliasing problem; this mean, when i plot, the curve is distorced. This is only an idea, but for signa visualization an antialiasing filter (like an aggregation function) can be useful. (Or maybe there is already something i don't know?).

Thanks in advance.

**Comment by desa** [comment]
Not sure I follow what the issue is. Can you include the queries you're running.

**Comment by eppak** [comment]
Is not an issue, is more a feature request. Take a sine and push it in influx with a low frequency (or a big amplitude): for example take 1 sample per second and an aplitude of 60 seconds. If you display the curve with its sampling you obtain a normal sine, now push this signal for 1 hour. Resample the curve with a query like:

select mean(value) from sine group by time(1m)

The signal is no more a sine, you have a distortion of the original signal (you have aliasing). Sometime is interesting to apply some filter on the signal to attenuate this distortion (anti-aliasing). In IoT historical analysis (of analog signal) this can be a problem.

I ask if there is a solution or something in the future.
Hope this explain my question.
Thanks.

**Comment by eppak** [comment]
Can someone tell me at least if is a bad idea?
Thanks

**Comment by desa** [comment]
Doesn't sound like a bad idea to me. Can you open a formal feature request?

**Comment by jwilder** [comment]
If you would like to log a feature request, please open a new issue using our [feature request](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md#feature-request) template. Thanks!
