### ISSUE TITLE
Influxdb 1.0 crash pthread created failed

### ISSUE THREAD

**Issue by itsuugo** [influxdata/influxdb#7333]
### Bug report

__System info:__ 
*  InfluxDB starting, version 1.0.0, branch master, commit 37992377a55fbc138b2c01edd4deffed64b53989
* Linux sonar 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* KVM VM with 16G of RAM and 2 vCPUs

__Steps to reproduce:__

Influxdb crash without any interaction
```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f4b7c476c37 m=2
```

[influxcrash.log.zip](https://github.com/influxdata/influxdb/files/483594/influxcrash.log.zip)

**Comment by jwilder** [comment]
What does `ulimit -a` report?

**Comment by itsuugo** [comment]
`root@sonar:~# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 128315
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 128315
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited`

**Comment by jwilder** [comment]
@itsuugo You may need to increase your `open files` limit or your `pid max`.  What does `sysctl kernel.pid_max` report?

**Comment by itsuugo** [comment]
kernel.pid_max = 32768

**Comment by jwilder** [comment]
@itsuugo I'd try increasing both.  I'm going to close this since this is a configuration issue on your system.

**Comment by itsuugo** [comment]
thanks
