### ISSUE TITLE
Simple SELECT makes Influx 1.0 OOM

### ISSUE THREAD

**Issue by amw2104** [influxdata/influxdb#7336]
Running in AWS on an m4.large, Influx v1.0.0 running on Debian Jessie

I have one particular measurement that seems like maybe it is corrupted somehow. When I run a simple SELECT statement on it, e.g.

`select * from replay_outcome_stats limit 10`

Influx hangs and the heap shoots straight up until the whole box becomes unresponsive. I have to restart the instance to recover. See the attached grafana graph of "Heap Alloc" and "Heap Idle"

![image](https://cloud.githubusercontent.com/assets/2694638/18692568/2cecda22-7f69-11e6-95bd-4f62fb92fc18.png)

__shards__
http://pastebin.com/VEtq1JXAhttp://pastebin.com/VEtq1JXA

__stats__
http://pastebin.com/sTQKbAFY

__diagnostics__
http://pastebin.com/2qbgwcjK

**Comment by amw2104** [comment]
Also, the WAL directory has one sub-folder with a bunch of files still in it. This is the output from running tree on the filesystem:

http://pastebin.com/YEfLPTyk

**Comment by jwilder** [comment]
Your query has no time filters and it looks like you may have sparse data based on the number of shards you have.  That will cause memory to spike currently if you a querying across a lot of shards.  Can you attach the output of "show shards"?

**Comment by jsternberg** [comment]
Will probably be fixed by #7303.

**Comment by amw2104** [comment]
My "show shards" output is attached. 

[shards.txt](https://github.com/influxdata/influxdb/files/488639/shards.txt)

However, I'm concerned that there are all these un-compacted files in the WAL. The pastebin contains the output of the filesystem. 

http://pastebin.com/YEfLPTyk

I migrated the data from one machine to another via the backup and restore mechanism more than a month ago, and I think I remember seeing those files in the WAL then. Is it possible that somehow the compaction for that data fell through the cracks as a side effect of doing a backup on one machine and a restore into another?

**Comment by jwilder** [comment]
All of those wal segments are snapshotted already.  They are `0` size.

You need to change the shard group duration of your shards or specify a time filter.  Querying across that many shards at once triggers high memory usage currently. The majority of those shards look like they are expired and will get removed once the retention policy runs.

Going to close this as #7303 would fix this issue.

**Comment by amw2104** [comment]
It's section 123 specifically, I'm referring to:

├── [4.0K]  123
│   ├── [ 10M]  _00172.wal
│   ├── [ 10M]  _00173.wal
│   ├── [ 10M]  _00174.wal
│   ├── [ 10M]  _00175.wal
│   ├── [ 10M]  _00176.wal
│   ├── [ 10M]  _00177.wal
│   ├── [6.3M]  _00178.wal
│   └── [5.8M]  _00179.wal

**Comment by jwilder** [comment]
Shard `123` is the current shard for this week.  If it's taking writes, you'll have some wal segments until they are snapshotted or goes cold.

```
123	hsreplaynet	default			123		2016-09-19T00:00:00Z	2016-09-26T00:00:00Z	2016-09-26T00:00:00Z	
```
