### ISSUE TITLE
influxdb stops writing data after machine hibernates and wakes up

### ISSUE THREAD

**Issue by fleapapa** [influxdata/influxdb#7339]
After machine hibernates and wakes up, Influxdb version 1.0.0-beta3 stops processing insert requests of non-zero timestamp that are submitted via HTTP protocol. Have to reboot machine to get it work.

Insert requests from influx CLI do get processed, though.

**Comment by nhaugo** [comment]
@fleapapa Can you please give operating system and hardware specs.

**Comment by fleapapa** [comment]
Thanks for your attention!

My OS is Ubuntu 16.04 running as a VM on VirtualBox v5.1.2 on OS X v10.10.5 on a Macbook Air 2015.

  $uname -a
  Linux osboxes 4.4.0-38-generic #57-Ubuntu SMP 
  Tue Sep 6 15:42:33 UTC 2016 
  x86_64 x86_64 x86_64 GNU/Linux

The issue can always be reproduced by a nodejs script calling writeSeries() function of influx client library. After putting my Macbook to sleep and waking it up, the nodejs script continues to write series data but influxdb stops writing the data to database. 

At that time, from wireshark capture, i can see http requests with "/write" uri but influxdb doesn't fulfill the requests.

At the same time, however, i can write new series data using influx CLI.

Today, i found those unfulfilled write requests were fulfilled after i reboot the VM. They were NOT fulfilled if i just restart influxdb service.

Thanks again!

**Comment by russorat** [comment]
closing due to age. if the issue persists in the newest release of influxdb, please open a new issue.
