### ISSUE TITLE
query explainer

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7340]
### Feature Request

**Proposal:** 

A new query clause, `EXPLAIN`. When included, the query is not actually run, but the index is checked and TSM files are scanned to determine:
- number of points queried
- number of TSM files queried
- number of shard groups queried
- lower bound on required RAM for running the query (we can at least determine how many iterators would be needed, and then add some padding for string length) This would not be precise at all, just a helpful relative number.

**Current behavior:** 

There is no way to estimate before running a query how many resources it needs, other than reference to past experience with the same data set.

**Desired behavior:** 

**Use case:** [Why is this important (helps with prioritizing requests)]

Users can have some idea whether a query will succeed before running it and potentially OOM-ing the system.

**Comment by beckettsean** [comment]
https://github.com/influxdata/influxdb/issues/7341 is probably a good first step

**Comment by jsternberg** [comment]
This was done in #8776 and #8947.
