### ISSUE TITLE
add query execution stats to [query] logs

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7341]
### Feature Request

**Proposal:** [Description of the feature]

While discussing https://github.com/influxdata/influxdb/issues/7340, @jwilder had the great idea to add actual execution numbers to the end of the `[query]` log lines.

E.g. 

```
[query] 2016/09/21 06:50:40 SELECT ...    points_scanned=3562 series_scanned=12 query_runtime=42ms
```

**Comment by rbetts** [comment]
We now support an `explain analyze` that shows IO and block accesses.
