### ISSUE TITLE
Feature Request: Add `time_gt` (time greater than) function

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#7342]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

**Proposal:** 
New method called `time_gt` that returns the amount of time that a field was above a particular values.

**Desired behavior:** 
The query 

```
SELECT time_gt(value, 100) FROM cpu WHERE time > now() - 1h
```

should return that total amount of time that the field value was greater that `100` in the last hour. A `HAVING` clause would probably solve this problem as well.

**Use case:** 
Came up during the Austin training not totally sure of the use case, but it seems like it'd be useful.

**Comment by phemmer** [comment]
How do you know how long it was above a particular threshold?
Influxdb just stores a series of points in time. At a single moment in time the value might be greater than 100, but how do you know it was above 100 up until the next measurement? Maybe it went below 100 immediately after the measurement was taken.

Not saying that I don't think this shouldn't be allowed to be calculated, just that it might not be a good idea to provide a function which makes assumptions about the data to do what it's advertised (named) as doing.
What about something more general purpose like:

    SELECT sum(if(previous(value) > 100, time - previous(time), 0)) AS time_gt FROM cpu WHERE time > now() - 1h

Lets the users make their own assumptions about their data. It's also more general purpose, so it has more potential use cases.

**Comment by desa** [comment]
@phemmer Thanks for you thoughts.

Reporting new data on state change is a common practice for irregular time series data. Meaning that in the example you listed below, if the value was 100, and then dropped off immediately after, the new value would be reported immediately. And therefore assuming that the value was 100 until receiving the next value is valid. 

In the case where you data comes in at regular intervals and you sample a value at 100, but immediately afterwards the value drops off, you don't become aware of that until the next sample. If in this case we assume that that value was 100 until we get our next sample, we still get a decent approximation of the time a value was above 100. The higher our sample rate, the more accurate the approximation will be.

I think you still make an important point though, making assumptions about users data is usually a bad idea. However provided that the functions behavior is documented I think it allows users to make an informed decision as to whether this function suits their use case.
