### ISSUE TITLE
fill(none) doesn't work as expected with 1.0

### ISSUE THREAD

**Issue by caligula1989** [influxdata/influxdb#7344]
### Bug report

**System info:** 
Influx 1.0
Debian 7

**Steps to reproduce:**

I am running the following query. The measurement is a simple web-requests measurement.

`SELECT sum(ErrorCount) / sum(Total) AS ErrorRate FROM requests_per_hour WHERE time >= '2016-09-15 08:00:00' AND time < '2016-09-22 08:00:00' GROUP BY time(1h) fill(none)
`

**Expected behavior:** 
I am expecting the results to contain only values in which ErrorRate has a value, however something weird is happening. I get some hours more than once, at first with a value, and then with a null value:

```
2016-09-22T03:00:00Z    0.006191950464396285
2016-09-22T04:00:00Z    0.025157232704402517
2016-09-22T05:00:00Z    0.3526315789473684
2016-09-22T06:00:00Z    0.07964601769911504
2016-09-22T07:00:00Z    0.010869565217391304
2016-09-22T06:00:00Z    
2016-09-22T07:00:00Z
```

**Comment by jsternberg** [comment]
What happens when you do `sum(ErrorCount), sum(Total)` with the same query?
