### ISSUE TITLE
1.0.0 GA Admin Interface Documentation Button Links to 404

### ISSUE THREAD

**Issue by Will-Beninger** [influxdata/influxdb#7351]
__System info:__
1.0.0GA InfluxDB

__Steps to reproduce:__
1. log into Admin interface (localhost:8083)
2. Click on "Documentation"
3. Get Directed to:
https://docs.influxdata.com/influxdb/v1.0.0/introduction/getting_started/
Instead of:
https://docs.influxdata.com/influxdb/v1.0/introduction/getting_started/

__Expected behavior:__ [What you expected to happen]
Expected to end up at documentation

__Actual behavior:__ [What actually happened]
Ended up at 404 page

**Comment by jwilder** [comment]
Fixed via #6688
