### ISSUE TITLE
COUNT should return 0, not null

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7352]
### Feature Request

__Proposal:__ [Description of the feature]

`COUNT()` should always return a number. 

__Current behavior:__ [What currently happens]

COUNT() returns nulls if there are no matching fields in the query. This means that a query may return a value for every bucket, or it may return nothing. 

```
> insert countnull value=42
> select count(value) from countnull where time > now() - 20s GROUP BY time(5s)
name: countnull
---------------
time			count
2016-09-23T19:14:10Z	0
2016-09-23T19:14:15Z	0
2016-09-23T19:14:20Z	1
2016-09-23T19:14:25Z	0
2016-09-23T19:14:30Z	0

> select count(value) from countnull where time > now() - 20s GROUP BY time(5s)
name: countnull
---------------
time			count
2016-09-23T19:14:15Z	0
2016-09-23T19:14:20Z	1
2016-09-23T19:14:25Z	0
2016-09-23T19:14:30Z	0
2016-09-23T19:14:35Z	0
```

So far so good. But what if we wait until the written point is outside our time range?

```
> select count(value) from countnull where time > now() - 20s GROUP BY time(5s)
> 
```

Nothing. But if we insert a point again, we get full expected output:

```
> insert countnull value=42000
> select count(value) from countnull where time > now() - 20s GROUP BY time(5s)
name: countnull
---------------
time			count
2016-09-23T19:14:35Z	0
2016-09-23T19:14:40Z	0
2016-09-23T19:14:45Z	0
2016-09-23T19:14:50Z	0
2016-09-23T19:14:55Z	1

> 
```

__Desired behavior:__ [What you would like to happen]

COUNT() should always return 0 for no results, even if there are simply no matches at all. 

Rather than

```
> select count(value) from countnull where time > now() - 20s GROUP BY time(5s)
> 
```

It should return 

```
> select count(value) from countnull where time > now() - 20s GROUP BY time(5s)
name: countnull
---------------
time			count
2016-09-23T19:14:25Z	0
2016-09-23T19:14:30Z	0
2016-09-23T19:14:35Z	0
2016-09-23T19:14:40Z	0
2016-09-23T19:14:55Z	0
```

__Use case:__ [Why is this important (helps with prioritizing requests)]

This way systems like Kapacitor don't have to deal with (null) returns from a function that should never return them. This would also allow `FILL()` to operate more reasonably with `COUNT()`. In general, a user asking for a count expects a number.

One downside is that because InfluxDB doesn't return an error if the measurement doesn't exist. This change would mean that typos would be harder to find:

```
> select count(value) from does_not_exist where time > now() - 20s GROUP BY time(5s)
name: does_not_exist
---------------
time			count
2016-09-23T19:14:25Z	0
2016-09-23T19:14:30Z	0
2016-09-23T19:14:35Z	0
2016-09-23T19:14:40Z	0
2016-09-23T19:14:55Z	0
```

**Comment by beckettsean** [comment]
@nathanielc @jsternberg @rossmcdonald

**Comment by rossmcdonald** [comment]
Dupe of https://github.com/influxdata/influxdb/issues/6412

**Comment by beckettsean** [comment]
Looked but couldn't find it. Thanks, Ross!

**Comment by QuinnBast** [comment]
Please unlock the referenced issue and take a look at this. Returning null on a `count` breaks the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)
