### ISSUE TITLE
SHOW SHARDS, SHOW SHARD GROUPS should allow for filtered output

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7353]
### Feature Request

**Proposal:** [Description of the feature]

`SHOW SHARDS` should support the `ON` or `FOR` filter per database or retention policy, with regex.

**Current behavior:** [What currently happens]

`SHOW SHARDS` is monolithic, it always returns all data about all shards

**Desired behavior:** [What you would like to happen]

`SHOW SHARDS ON mydb` would show shards only for `mydb`. 

`SHOW SHARDS ON mydb.autogen` would show shards only for the `autogen` RP on `mydb`.

**Use case:** [Why is this important (helps with prioritizing requests)]

Production systems with many databases can easily have `SHOW SHARDS` output in the 10s of thousands of lines, and it's impossible to investigate a specific problematic database or RP.

**Comment by beckettsean** [comment]
fixed by https://github.com/influxdata/influxdb/pull/7295

**Comment by beckettsean** [comment]
perhaps I was too hasty

**Comment by jsternberg** [comment]
@jwilder proposing for 1.1.

**Comment by jsternberg** [comment]
@beckettsean I'm not sure `ON` is the appropriate syntax for this. We don't currently have any commands that use `ON` with both a database and retention policy. They all only have the database. I'm also not sure `FROM` is appropriate either since that usually references a measurement. I'm not sure we have anything that does both database and retention policy at the moment. Any ideas?

**Comment by beckettsean** [comment]
There aren't any queries that take a DB or a DB/RP combo. http://docs.influxdata.com/influxdb/v1.0/query_language/spec/#clauses

If it makes it easier, the first implementation can ignore the RP and only accept a database with ON. Later we can revisit if we need more granularity.

Also, I forgot to mention `SHOW SHARD GROUPS` as another query that needs the ability to restrict to a database.

**Comment by sprive** [comment]
In the meantime, this snippet may help some users (where 'dbname_5m' is the name of your db):
`
$ influx -execute "show shards" -database="dbname_5m" | sed -n '/name: dbname_5m/,/^$/p'
name: all_client_5m
id   database      retention_policy shard_group start_time           end_time             expiry_time          owners
--   --------      ---------------- ----------- ----------           --------             -----------          ------
... rows with shard-info just for this db...
`

**Comment by Infern1** [comment]
any update on this?
