### ISSUE TITLE
Support XFF logging for HTTP requests

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#7356]
It is common practice for Load Balancers and Proxies to substitute the source IP address of a packet with their own and (optionally) provide the originating IP address under the X-Forwarded-For header.

The influxd HTTP listener should be able to parse and log the address in the [X-Forwarded-For](https://en.wikipedia.org/wiki/X-Forwarded-For) header, if it exists.

The logs could include both the source and the originating address, e.g:

`[httpd] 172.30.22.4 - XFF 77.49.88.96 - [24/Sep/2016:16:17:33 +0300] "POST /write?consistency=any&db=telegraf&precision=ns&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 411c6f60-8259-11e6-8029-000000000000 2680`

**Comment by jsternberg** [comment]
Is there a common log format for XFF that we should follow so Telegraf can still parse it? /cc @sparrc

**Comment by kostasb** [comment]
@jsternberg @sparrc I think it is sufficient to just log the XFF IP instead of the source host IP when the XFF header is present.
Ideally XFF logging should be configurable/optional.
