### ISSUE TITLE
apt-get install influxdb installs 0.10.0

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#7358]
Just running 
```bash
$ apt-get update
$ apt-get install influxdb
```

installs `0.10.0`. Things work if they follow the [docs](http://docs.influxdata.com/influxdb/v1.0/introduction/installation/#ubuntu-debian), but the base if they don't they end up installing `0.10.0` which is definitely not what what we want.

@rossmcdonald

**Comment by rossmcdonald** [comment]
I'm assuming this is because you're installing the official Debian version of InfluxDB (which we don't maintain). You have to use the repos if you want the latest.

**Comment by desa** [comment]
This was with 16.0 4LTS

**Comment by rossmcdonald** [comment]
This is it: http://packages.ubuntu.com/xenial/influxdb

> Is there anyway to prevent installing the official Debian version?

Not that I'm aware of. If they add our repository then it will pull the latest, but we can't stop someone from jumping on any box and running `apt-get install influxdb`.

**Comment by desa** [comment]
Damn.
