### ISSUE TITLE
Feature Request: Document how to change field value data types

### ISSUE THREAD

**Issue by rdpoor** [influxdata/influxdb#7366]
__Current Situation:__ At present (v 1.0), it's not possible to change a field value data type from (say) a boolean to a float64, and #2651 makes it clear that this won't happen soon.  That's okay.

__Feature Request:__ In the meantime, it would be useful to document one or more techniques that have the overall effect of changing data types.  For example (from #2651) you can:

* use a new field name, 
* use a new retention policy, 
* wait for a new shard to be created and drop the old shards
... etc.

__Use case:__ Judging from comments on the web, a number of people stumble across this behaviour and would like a workaround.

**Comment by desa** [comment]
@rdpoor Sounds like docs issue. Opening mirror issue on docs repo.
