### ISSUE TITLE
Separate query-timeout for continuous queries

### ISSUE THREAD

**Issue by larrywalker** [influxdata/influxdb#7375]
### Feature Request

**Proposal:** [Description of the feature]
Add a separate query-timeout configuration value for continuous queries or maybe add the ability to specify a timeout as part of the query syntax (run query for upto X seconds and then give up).

**Current behavior:** [What currently happens]
The query-timeout value (when configured) stops queries that run longer than the configured value.

**Desired behavior:** [What you would like to happen]
We would like more control of timeout values for CQ or on every query, if not specified then a default value could  be used.

**Use case:** [Why is this important (helps with prioritizing requests)]
We are having a hard time getting a query-timeout balance that allows large nightly rollup CQ to complete, but still being able to kill slow/bad queries that might be issued by a user/application.
The CQ for out nightly rollup data has been observed to take several minutes, so we increased the query-timeout value to allow these rollups to complete, but then a user can issue a bad query that can kill the server in 30secs with an OOM.  Have a longer query-timeout for CQ or "system" queries and then a shorter timeout for user queries.

**Comment by balalinux** [comment]
Any idea on when this would get done?
