### ISSUE TITLE
Upgrading to 1.0 went bad

### ISSUE THREAD

**Issue by renaudcalmont** [influxdata/influxdb#7378]
Hi,

coming from 0.10 to 1.0, the meta/raft.db file is preventing the new version to start.
There is a misleading message stating that it should be OK to delete it.

After deletion, the new version starts but the whole config is gone!
No problem for me to recreate the whole config but how may I reimport the previous data held in the olds .tsm files?

Also, please replace the message with a gigantic WARNING...

**Comment by renaudcalmont** [comment]
Strangely enough, when you create a database with the same name as the previous one, a "SHOW MEASUREMENTS" request lists all previously known measurements but no data point.

**Comment by gunnaraasen** [comment]
Upgrading to 1.0 from 0.10 requires a couple steps to update the metastore. Please see the [documentation for upgrading from 0.10 to 1.0](http://docs.influxdata.com/influxdb/v1.0/administration/upgrading/#upgrading-from-0-10-or-0-11-to-1-0) for more detail. Please comment if the upgrade steps do not work as expected.

**Comment by renaudcalmont** [comment]
Please read the description again, the problem is how to reimport TSM data without the raft.db file?

**Comment by renaudcalmont** [comment]
FTR, here's the relevant documentation page: https://docs.influxdata.com/influxdb/v1.0/tools/influx_inspect/#influx-inspect-export

For me the final solution was:
$ influx_inspect export -dir /var/lib/influxdb -out export.txt -db your_db_name
$ influx -import -path=export.txt
