### ISSUE TITLE
Threshold for data records in a measurement varies.

### ISSUE THREAD

**Issue by artinegi1607** [influxdata/influxdb#7381]
### Bug report

System info :  Influx DB-0.13, Ubuntu-14.04

Steps to reproduce :

1. Create a measurement
2. Insert data records in a loop 
3. Check count of records

Expected behaviour : If threshold exists, it should terminate in a single point of time with reaching to threshold error.

Actual behaviour : Inserting data regularly into measurement, at some point measurement collapse and again start filling data from beginning. sometime it reaches to 900 records and sometime 2000 records. 

Additional info:  Inserting data using - write_points() API using json data.
 I am verifying the number of records using-
                             "select count(value) from "measurement_name".

I am a newbie to Influx DB. Am i missing something or doing anything wrong. Please help me in understanding this scenario.

**Comment by desa** [comment]
@artinegi1607 can you give an example of the data that you're writing in. I'm not sure what the issue is.

**Comment by jwilder** [comment]
I'd suggest upgrading to 1.0.2 as this may not be occurring any more.  If it is still occurring, please log a new issue with steps to reproduce.
