### ISSUE TITLE
Shards stats wrong diskBytes value

### ISSUE THREAD

**Issue by Uccio** [influxdata/influxdb#7382]
### Bug report

The monitory system often does not properly report the size of file system of the shard file

__System info:__ InfluxDB v 1.0.0

__Steps to reproduce:__

1. select path, diskBytes/1024/1024 as Disk_MB  from "shard" where "database" = '_internal' and time > now()  - 10s

   ![image](https://cloud.githubusercontent.com/assets/199549/18956541/0c4d0aae-865c-11e6-8e92-d13d8af23b4a.png)

2.  Perform disk usage check:  du /var/lib/influxdb/data/_internal -h 

    ![image](https://cloud.githubusercontent.com/assets/199549/18956854/3ded8aba-865d-11e6-9cdd-3914d40bc2cc.png)

__Expected behavior:__ Real disk space and "shards stats" display the same file dimension

__Actual behavior:__  The latest "shard file stats" is bigger than the real disk space (the dimension is like the entire database dimension)

__Additional info:__ The problem is not always present but often occurs especially for databases with traffic

**Comment by mark-rushakoff** [comment]
The reported disk bytes for the *shard* [include the size of the data directory and the WAL directory](https://github.com/influxdata/influxdb/blob/ea8a57233f8f3121f36e8771847463e8791f58b9/tsdb/shard.go#L316-L344).

It's misleading that the `shard` measurement only lists  the data path. I'm going to open a PR to include the WAL path as a tag.
