### ISSUE TITLE
SELECT .. FROM /.*/ queries return incorrect results in a cluster setup when database replication factor does not equal # of nodes

### ISSUE THREAD

**Issue by michaelzg** [influxdata/influxdb#7386]
### SELECT .. FROM /.*/ queries return incorrect results in a cluster setup when database replication factor does not equal # of nodes

__System info:__ 

Branch: 1.0
Commit: f0db39037796e2c501785b8dfb6e570d5b645c20
Build: 1.0.0-c1.0.0
**4 node cluster**

__Steps to reproduce:__

* Assuming you have a 4 node cluster
* Create two databases, one with replication factor == # nodes and one that is not.
```
CREATE DATABASE "TestRepl4" WITH DURATION INF REPLICATION 4 NAME "RP_TestRepl4"
CREATE DATABASE "TestRepl2" WITH DURATION INF REPLICATION 2 NAME "RP_TestRepl2"
```
* Insert dummy data into both
```
USE TestRepl4
INSERT INTO RP_TestRepl4 treasures,captain_id=pirate_king value=2

USE TestRepl2
INSERT INTO RP_TestRepl2 treasures,captain_id=pirate_king value=2
```
* Select using `FROM /.*/` on...

The database with replication factor == # of nodes
```
USE TestRepl4
select value from /.*/ where captain_id='pirate_king'
```
.. and you get data

However, select from the database with replication factor != # of nodes..

```
USE TestRepl2
select value from /.*/ where captain_id='pirate_king'
```
.. and _no data_.

Note that specifying the measurement in the `TestRepl2` does indeed return the data as expected.

```
select value from treasures where captain_id='pirate_king'
```

__Expected behavior:__ When querying the `TestRepl2` database, a read quorum should be at play to warn that we may be reading from stale nodes. Or else, when using `SELECT .. FROM /.*/`, a database with replication factor != # of nodes is instantly returning stale results to queries, without warning.

Without a way to specify read quorum for a cluster. Why then provide the option of Replication factor for a database at all when surely all users would want replication factor == node?

__Actual behavior:__ The `TestRepl2` database query returned no data, no warning.

shards (`Test` database in the log below is set to replication factor 2)

```
name: Test
----------
id	database	retention_policy	shard_group	start_time		end_time		expiry_time		owners
8	Test		RP_Test			3		2016-09-26T00:00:00Z	2016-10-03T00:00:00Z	2016-10-03T00:00:00Z	6,7
9	Test		RP_Test			3		2016-09-26T00:00:00Z	2016-10-03T00:00:00Z	2016-10-03T00:00:00Z	4,5


name: TestRepl4
---------------
id	database	retention_policy	shard_group	start_time		end_time		expiry_time		owners
10	TestRepl4	RP_TestRepl4		4		2016-09-26T00:00:00Z	2016-10-03T00:00:00Z	2016-10-03T00:00:00Z	4,5,6,7
```

**Comment by jsternberg** [comment]
This issue was copied to our internal tracker for clustering and will be fixed in a future version. Thank you for filing the bug report.
