### ISSUE TITLE
Support arm64 (aarch64) build

### ISSUE THREAD

**Issue by Nemykal** [influxdata/influxdb#7390]
### Feature Request

**Proposal:** Support building influxdb on a 64bit ARM system. 

**Current behavior:** Currently ./build.py fails because Go gets confused between 'aarch64' and 'arm64'

With influxdb 1.0.1, I get the following:

[INFO] build: Starting build for linux/aarch64...
[INFO] build: Using Go version: 1.7.1
[INFO] build: Using git branch: HEAD
[INFO] build: Using git commit: 8b354f72951f50b130894dddee2e05149a1801d8
[INFO] build: Sending build output to: /go/src/github.com/influxdata/influxdb/build
[INFO] build: Using version '1.0.1' for build.
[INFO] build: Building target: influx_stress
[ERROR] run: Command 'GOOS=linux GOARCH=aarch64 go build -o /go/src/github.com/influxdata/influxdb/build/influx_stress -ldflags="-X main.version=1.0.1 -X main.branch=HEAD -X main.commit=8b354f72951f50b130894dddee2e05149a1801d8" ./cmd/influx_stress' failed with error: cmd/go: unsupported GOOS/GOARCH pair linux/aarch64

**Desired behavior:** Should build influxdb without errors.

**Use case:** 64bit ARM chips are becoming more common, would be good to support the build so that we can test it more.

I was able to get influxdb to build by hardcoding GOARCH in build.py:
 build_command += "GOOS=linux GOARCH=arm64 ".format(platform, arch)

I believe the issue is that the os.uname()[4] returned by get_system_arch() is equal to "aarch64", whilst Go now expects "arm64" instead

Are there any more tests I can run to confirm everything is working?

influx_stress
Total Queries: 250
Average Query Response Time: 13.720512ms

Total Requests: 2000
        Success: 2000
        Fail: 0
Average Response Time: 222.85553ms
Points Per Second: 114147

**Comment by jwilder** [comment]
Does this work?

 `./build.py --platform linux --arch arm64`

**Comment by tcheneau** [comment]
Hello, I ran into the same issue and created the PR #7580 with a fix for the build.py script (@Nemykal did most of the job identifying where the issue was, thank you!).

**Comment by Nemykal** [comment]
I've tried building it again with @tcheneau's patch applied. Passing "arm64" to build.py doesn't seem to be enough, as it still tries to build with `GOARCH=arm` now instead

My testing:

On master branch, commit `aff2d7ce649ead1dbb5fd930b09c6e037ef31e0f`
On aarch64 system - `uname -a` output:
`Linux 07ee123c0a57 4.8.8-300.fc25.aarch64 #1 SMP Thu Nov 17 13:41:51 UTC 2016 aarch64 Linux
`

build_command is being set too early.

https://github.com/influxdata/influxdb/blob/master/build.py#L511

**Comment by Nemykal** [comment]
It looks like the build correctly picks it up as linux/arm64 but still uses the wrong environment variables later on:

```
/go/src/github.com/influxdata/influxdb # python2 ./build.py
[INFO] print_banner:
  ___       __ _          ___  ___
 |_ _|_ _  / _| |_  ___ _|   \| _ )
  | || ' \|  _| | || \ \ / |) | _ \
 |___|_||_|_| |_|\_,_/_\_\___/|___/
  Build Script

[INFO] check_environ: Checking environment...
[INFO] check_prereqs: Checking for dependencies...
[INFO] go_get: Downloading `gdm`...
[INFO] go_get: Retrieving dependencies with `gdm`...
[INFO] build: Starting build for linux/arm64...
[INFO] build: Using Go version: 1.7.3
[INFO] build: Using git branch: master
[INFO] build: Using git commit: aff2d7ce649ead1dbb5fd930b09c6e037ef31e0f
[INFO] build: Sending build output to: /go/src/github.com/influxdata/influxdb/build
[INFO] build: Using version '1.1.0' for build.
[INFO] build: Building target: influx_stress
[ERROR] run: Command 'GOOS=linux GOARCH=arm GOARM=6 go build -o /go/src/github.com/influxdata/influxdb/build/influx_stress -ldflags="-X main.version=1.1.0 -X main.branch=master -X main.commit=aff2d7ce649ead1dbb5fd930b09c6e037ef31e0f" ./cmd/influx_stress' failed with error: # github.com/influxdata/influxdb/cmd/influx_stress
warning: unable to find runtime/cgo.a
/usr/lib/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
gcc: error: unrecognized command line option '-marm'; did you mean '-fasm'?
```

**Comment by adomenech73** [comment]
Eventually a had the same problem but finally I could compile and execute ```python build.py --package``` just fine following this steps [GIST](https://gist.github.com/adomenech73/f47efc1b72992e9c9a31f59aa44e1bc1). I'm also finishing a Dockerfile to automate this process with an Alpine image, I post it when it's ready.

Hope it helps.

**Comment by adomenech73** [comment]
Actually I can reproduce @Nemykal error from the Alpine docker image.
If I search for cgo.a in the image I find it twice:

```
/usr/lib/go/pkg/linux_arm64_shared/runtime/cgo.a
/usr/lib/go/pkg/linux_arm64/runtime/cgo.a
```
Seems to me that could be some kind of problem associating aarch64 (os arch) with arm64 (go arch).
It's true that even defining environment variables as:
```
export GOOS="linux"
export GOARCH="arm64"
```
Python script tries to compile for arm arch

```
[ERROR] run: Command 'GOOS=linux GOARCH=arm GOARM=6 go build -o /go/src/github.com/influxdata/influxdb/build/influx_stress -ldflags="-X main.version=1.1.0 -X main.branch=master -X main.commit=153277c01d7206e15cdf7a942640c2ab7e06d2c4" ./cmd/influx_stress' failed with error: # github.com/influxdata/influxdb/cmd/influx_stress
warning: unable to find runtime/cgo.a
/usr/lib/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
gcc: error: unrecognized command line option '-marm'; did you mean '-fasm'?
```
On the other hand, ```build.py``` seems to use ```uname``` for arch detection. I don't know if this can be meaningful but here I can see some little differences in the output of uname from Ubuntu os or the Alpine image

- Ubuntu:
```
Linux pine64-build 3.10.102-2-pine64-longsleep #66 SMP PREEMPT Sat Jul 16 10:53:13 CEST 2016 aarch64 aarch64 aarch64 GNU/Linux
``` 

- Alpine:
```
Linux d5da31e9477e 3.10.102-2-pine64-longsleep #66 SMP PREEMPT Sat Jul 16 10:53:13 CEST 2016 aarch64 Linux
```
In fact Alpine ```uname -i``` returns ```unknown``` while Ubuntu returns ```aarch64```

**Comment by pavel-odintsov** [comment]
Hello!

ARM64 is rising server platform and we use it a lot. Any chance to get more attention to this issue, please?

Thank you!

**Comment by nuclearcat** [comment]
Want to add to previous comments, that except server platform i faced same problem on SBC (custom Espressobin), which is also ARM64.
I am using influxdb for monitoring/analysis of solar energy system efficiency, and running it on other platforms is suboptimal, as ARM64 is most energy efficient for such workload.

**Comment by davidgraeff** [comment]
Time to reopen this for influxdb 2? :)
