### ISSUE TITLE
wrong data in database

### ISSUE THREAD

**Issue by gescheit** [influxdata/influxdb#7391]
In some cases values in base and values that was written are different.
System: influxdb 1.0.0-1, Ubuntu 14.04.3 LTS.

Steps to reproduce:

Use this [script](https://gist.github.com/gescheit/f36746db7ac421831a0f2eada1c831dd)
Script constantly writes the same data to influx. The pattern of data is odd, but it causing the problem.

Expected data from gist example.
network,host=host rx=7094i 1474460700
network,host=host rx=4472i 1474460760
network,host=host rx=1850i 1474460820

Actual output of the script:
....
lines count 1849. duration 68
lines count 1853. duration 68
lines count 1857. duration 68
stopping. found bad value -9716
'name': 'network',
'values': [['2016-09-21T12:25:00Z', 'host', 7094],
               ['2016-09-21T12:26:00Z', 'host', -9716],
               ['2016-09-21T12:27:00Z', 'host', 12337]]}]}]}

**Comment by jwilder** [comment]
Thanks for the script @gescheit! I was able to reproduce this as well.

**Comment by gescheit** [comment]
Thanks!
