### ISSUE TITLE
non_negative_difference

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#7393]
### Feature Request

**Proposal:** [Description of the feature]

Add a `non_negative_difference` function, similar to `non_negative_derivative`.

**Current behavior:** [What currently happens]

No such function.

**Desired behavior:** [What you would like to happen]

Such a function.

**Use case:** [Why is this important (helps with prioritizing requests)]

For a counter which overflows and is frequently reset, using `difference` results in frequent negative values.

Note, this is NOT the same as the feature requested in #7076.

**Comment by desa** [comment]
@phemmer should it report the absolute value, or 0 if the value is negative?

**Comment by phemmer** [comment]
Nither, it should drop the value entirely, just like `non_negative_derivative` does.

**Comment by desa** [comment]
Ah, makes sense.

**Comment by zhexuany** [comment]
@jwilder If no one take this, I would like to devote my time on this feature. What is your opinion? Is this gonna be ok to adding in `influxDB`?

**Comment by jwilder** [comment]
@zhexuany Sounds good.  Thanks!

**Comment by rafaelncarvalho** [comment]
It's not better to make an absolute function? This way we could write `ABS(DIFFERENCE( ))` on query and it could replace the `non_negative_derivative` too

**Comment by phemmer** [comment]
@rafaelncarvalho that's not the same. However something like `max(derivative(foo),0)` would be.

**Comment by zhexuany** [comment]
I am so sorry for the delay. I planed to used my Spring Festival break to complete this.

**Comment by michalrus** [comment]
> Note, this is NOT the same as the feature requested in #7076.

But it covers the same use case! Please, do it. :cat: 

@zhexuany, you might want to take a look at the mentioned #7076 and #7093 for some more context on the use case.

**Comment by phemmer** [comment]
> But it covers the same use case! Please, do it. 🐱

Actually no it doesn't. Read the comments on #7076, this is a completely different feature.

**Comment by michalrus** [comment]
Ah, right, I wanted totals there. But you can get speed from totals (and I do this with my patch). Will I be able to get totals from your speed in #7393?

**Comment by zhexuany** [comment]
PR is ready. Please check: https://github.com/influxdata/influxdb/pull/8235.

**Comment by e-dard** [comment]
Fixed via https://github.com/influxdata/influxdb/pull/8235
