### ISSUE TITLE
RANDOM() Aggregate Function

### ISSUE THREAD

**Issue by ScottStevenson** [influxdata/influxdb#7394]
### Feature Request

__Proposal:__ 
A RANDOM() aggregation function which will select a random point from groups. Similar to FIRST()/LAST() but far less biased when dealing with periodic data.

__Current behavior:__ [What currently happens]
For non-numerical data SUM(), AVERAGE(), MEAN(), MODE(), MEDIAN() cannot be used. To down-sample this kind of data, we must currently use FIRST() or LAST() to grab a sample from each time window. This is problematic because if the data is periodic, it is very easy to end up with a bias in the sampling. If you are grouping by 5 minutes intervals and are sampling network data where there are scheduled jobs running every 5 minutes - you may always end up sampling the scheduled job rather than the other activity that is happening in the middle of the 5 minute window. 

__Desired behavior:__ [What you would like to happen]
A new aggregation called RANDOM() would be able to be used, which would instead select a random point out of each group. This would ensure that the down-sampling is statistically representative of the high-resolution data, without bias.

__Use case:__ [Why is this important (helps with prioritizing requests)]
I am hoping to use InfluxDB to store Netflow data. Netflow can be very granular and it needs to be downsampled in order to efficiently visualize it. Some of the data a Netflow point includes are: application type, port number, IP address, type of service, etc. These are things where SUM, MEAN, etc. are not useful.

**Comment by desa** [comment]
@ScottStevenson is it safe to assume that you'd like to get a random point with probability `1/n` where `n` is the number of points in the window?

**Comment by ScottStevenson** [comment]
@desa That's correct! A second field to determine the number of random points returned would definitely be a nice addition - but not absolutely necessary.

**Comment by desa** [comment]
@ScottStevenson PR was opened that implements this feature request.

**Comment by desa** [comment]
Added by https://github.com/influxdata/influxdb/pull/7415

**Comment by ScottStevenson** [comment]
Awesome. Thank you.
