### ISSUE TITLE
Aggregated graph strange behavior

### ISSUE THREAD

**Issue by anthony-sticky** [influxdata/influxdb#7395]
Hi,

I'm submitting a:
- [x] Bug report

- What Grafana version are you using?
Grafana v3.1.0

- What datasource are you using?
InfluxDB v1.0.0

- What OS are you running grafana on?
Debian Jessie.

- What did you do?
I try to graph and aggregated Nginx request per second (collectd default plugin) graph on some servers.

- What was the expected result?
Correct values for "Max" "Avg" sum and a correct scale for my graphs.

- What happened instead?
If i cumulate certain hosts together every metrics seems well calculated and the scale is OK, but sometimes one host will ruin the whole aggregated graph.

- Hosts 6 to 9 everything is ok:
![ads6-9-aggregated](https://cloud.githubusercontent.com/assets/5138633/19020206/51a8406c-88a2-11e6-8725-5e41727201e0.png)

- Hosts 6 to 10, the aggregated graph explodes:
![ads6-10-aggregated](https://cloud.githubusercontent.com/assets/5138633/19020210/7d09c1ea-88a2-11e6-9de3-56b8d78bcde4.png)

- Host 10 alone looks like all others taken independently:
![ads10-only](https://cloud.githubusercontent.com/assets/5138633/19020213/996af93a-88a2-11e6-9ab2-49b026903d16.png)

(Every capture is taken on the same timeframe:  "Last 24 hours").

- Here's the query construction:
![query_construction](https://cloud.githubusercontent.com/assets/5138633/19020258/e9ccf2ec-88a3-11e6-8432-a7153156bdfd.png)

Here is the raw response for

Server 10 alone:
[query_10alone.txt](https://github.com/grafana/grafana/files/505104/query_10alone.txt)

Server 11 alone:
[query_11alone.txt](https://github.com/grafana/grafana/files/505103/query_11alone.txt)

Servers 10 plus 11:
[query_10plus11.txt](https://github.com/grafana/grafana/files/505102/query_10plus11.txt)

**Comment by phemmer** [comment]
If you're going to combine multiple sources into one graph, you need a `group_by` to split them out into separate lines, or your results are going to get all jacked up as you can see.

**Comment by anthony-sticky** [comment]
Depending on nodes i can add a lot without any errors and without any group by node so i don't understand.

- On this 2 nodes it's working:
![working](https://cloud.githubusercontent.com/assets/5138633/19023483/5f2c2ac6-88ef-11e6-9946-ad730e963b48.png)

- On this 2 it isn't:
![not_working](https://cloud.githubusercontent.com/assets/5138633/19023484/63c5ea90-88ef-11e6-9693-9e2cec241d71.png)

They have almost the same traffic and if i take them individually on the same timeframe, i don't have any "high" peak.

Could you please explain the difference between my 2 slides ?

**Comment by phemmer** [comment]
While I don't know what your data looks like, the graph that you say is working is most likely also giving you invalid results.

Lets say you have a measurement that looks like this
```
test,host=foo value=0i 1000000000
test,host=bar value=0i 1001000000
test,host=bar value=9i 1999000000
test,host=foo value=2i 2000000000
test,host=foo value=3i 3000000000
test,host=bar value=10i 3001000000
```

Now lets look at what happens when you use `derivative` without any `group by`:

```
> select derivative(value) from test
name: test
----------
time		derivative
1001000000	0
1999000000	9.01803607214429
2000000000	-7000
3000000000	1
3001000000	7000
```
A complete mess.
Now lets throw a `group by` on:

```
> select derivative(value) from test group by host
name: test
tags: host=bar
time		derivative
----		----------
1999000000	9.01803607214429
3001000000	0.998003992015968

name: test
tags: host=foo
time		derivative
----		----------
2000000000	2
3000000000	1
```

Much better. We now see that `host=bar` had 9 & 1 requests (rounded), while `host=foo` had 2 & 1 requests.

This is a bit of a simplified example, but the concept carries through to your data.

**Comment by antoine-sticky** [comment]
OK, thanks for your reply.
GROUP BY host allows me to have correct values yes, but i have as many curves as series.

I have hundred of nodes with this metric and i only want one cumulative curve.

Our collectd instances feed InfluxDB with default Nginx plugin.
Per server it counts the number of queries per second with steady growth since the last restart. For this reason i used non_derivative transformation.

Isn't there any way to address my problematic ?

**Comment by anthony-sticky** [comment]
OK, thanks for your reply.
GROUP BY host allows me to have correct values yes, but i have as many curves as series.

I have hundred of nodes with this metric and i only want one cumulative curve.

Our collectd instances feed InfluxDB with default Nginx plugin.
Per server it counts the number of queries per second with steady growth since the last restart. For this reason i used non_derivative transformation.

Isn't there any way to address my problematic ?

**Comment by jwilder** [comment]
@anthony-sticky There is no way to do this currently.  I think what you would need would be sub-queries which is tracked as #4619.
