### ISSUE TITLE
[1.0]Higher CPU usage after upgrade from 0.12

### ISSUE THREAD

**Issue by yuichiro-kato** [influxdata/influxdb#7408]
System info: InfluxDB 1.0 , Ubuntu 14.04.4 LTS (GNU/Linux 3.14.69+ armv7l)

Steps to reproduce:
1. Upgrade from 0.12 up to 1.0
    -  I tried rename retention policy, not cleaning previous data.
2. High CPU usage growing ( about 8% => about 30-40% )

It is really similar to #7275

**Comment by jwilder** [comment]
1.0 uses more concurrency throughout the system to improve performance.  This is expected behavior.

**Comment by ZhukovAlexey** [comment]
To whom it may concern: 

I've done an upgrade to the latest 1.1 version and I can't see any CPU usage difference between 0.11 and 1.1. 

So I can recommend trying to install new version to see if it works fine in your environment.
