### ISSUE TITLE
Influxdb stops suddenly

### ISSUE THREAD

**Issue by Shashidhar014** [influxdata/influxdb#7409]
Hi All,

I am running influxdb(v0.13) server in ubuntu system from more than a month. But suddenly the server stops. I checked the logs, did not got cause for it. Can any one help me to get the cause and solution for it. Please find the below log file.

[influxd.log-20161002.zip](https://github.com/influxdata/influxdb/files/510235/influxd.log-20161002.zip)

Thanks & Regards,
Shashidhar K

**Comment by desa** [comment]
@Shashidhar014 can you include the log files as a gist. Also can you verify that this is still an issue with 1.0

**Comment by jwilder** [comment]
@Shashidhar014 It looks like a query was run that ultimately OOM'd the server:

```
[query] 2016/10/01 18:25:41 SELECT * FROM WaterMeters."default"./.*/ LIMIT 1
fatal error: runtime: out of memory
```

Your logs look like you may be leaking connections which might be causing RAM usage to be higher and causing that query to OOM.

I'd recommend upgrading to 1.0.2 as well as verifying your clients are not leaking HTTP connections.  In 1.0, you can set:

```
[http]
max-connection-limit = 100
```
which will prevent new connections once they exceed the limit.  Your client should start to return errors if it's leaking them.
