### ISSUE TITLE
Retention policy not removing old data

### ISSUE THREAD

**Issue by slavede** [influxdata/influxdb#7410]
### Bug report

__System info__:

Linux 2.6.32-358.el6.x86_64 x86_64
influxdb-1.0.0-1

__Steps to reproduce:__

Created retention policies and continuous query

CREATE RETENTION POLICY "1_hour" ON "st_test" DURATION 1h REPLICATION 1 DEFAULT;
CREATE RETENTION POLICY "a_year" ON "st_test" DURATION 52w REPLICATION 1;

CREATE CONTINUOUS QUERY "cq_30m" ON "st_test"
BEGIN SELECT mean("temperature") AS "mean_temperature",mean("latency") AS "mean_latency", max("temperature") AS "max_temperature", min("temperature") AS "min_temperature", max("latency") AS "max_latency", min("latency") AS "min_latency"
INTO "a_year"."metrics"
FROM "metrics"
GROUP BY time(30m),site_id END

__Expected behavior:__ [What you expected to happen]
I expected data older than one hour to be removed

__Actual behavior:__ [What actually happened]
I still see old data

__Additional info:__ [Include gist of relevant config, logs, etc.]

I have created retention policy to one hour:
![image](https://cloud.githubusercontent.com/assets/2838038/19114645/22494c7a-8b0f-11e6-87cb-1935bc9db75f.png)

But I still see following data in 1_hour retention policy:
![image](https://cloud.githubusercontent.com/assets/2838038/19114615/0a66fd5a-8b0f-11e6-97a4-99581eb3e610.png)

You can see data from 11:22:31 to 13:12:40 (moment of writing this post). I would expect that I would see less data.

**EDIT** eventually it was deleted, but I was able to see old data later on too...so at 14:18 I was still able to see data from 12:00, then in 14:19 policy was applied and it deleted data, but only up until 13:00 which just then made sense, because at 14:18 I didn't want to see data for 12:00.

**Comment by rossmcdonald** [comment]
Can you provide the output to a `SHOW SHARDS` query? Depending on data was written to the RP, the initial shards might have been created with an incorrect retention. The shard output will display when each expires, though.

**Comment by slavede** [comment]
Ahaaa, that's it, expiry was one more hour later. Is that expected behavior or can I make it somehow to remove as soon as it gets to downsampled/retained data?

**Comment by slavede** [comment]
Thanks for explanation, I'm closing this one and opened #7411
