### ISSUE TITLE
CLI writes auth commands to history permitting plain text password retrieval

### ISSUE THREAD

**Issue by jlennox** [influxdata/influxdb#7414]
__System info:__ 0.13.0, OS X 10.11.5

__Steps to reproduce:__

1. Run `influx`
2. Use `auth` command.
3. Use `exit` command to close influx.
4. Run `influx`
5. Press "up" or type `history`

__Expected behavior:__ The auth command should not of been written to history. It should be as if nothing was entered or perhaps a static text stub. This should even be the case for invalid authorization attempts because a typo is potentially very close to the correct credentials.

__Actual behavior:__ The auth command is shown allowing retrieval of the username and password in plain text. It can alternatively be seen in `~/.influx_history`

**Comment by desa** [comment]
@jlennox not exactly sure I see what the issue is. The user and password aren't stored, just that you used the auth command.

**Comment by jlennox** [comment]
@desa If you run `influx`, use the auth command, then `grep -i auth ~/.influx_history` it shows the username and password in plain text.

**Comment by desa** [comment]
@jlennox ah thats a problem

**Comment by desa** [comment]
@jlennox just tried to verify this for myself, and I don't see the same behavior. Can you verify that this is an issue with 1.0

**Comment by jlennox** [comment]
@desa I have updated and confirmed it behaves the same.

> joe in ~ λ influx
> Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
> Connected to http://localhost:8086 version v1.0.0
> InfluxDB shell version: v1.0.0
> > auth testuser testpassword
> > exit
> joe in ~ λ grep testpassword ~/.influx_history
> auth testuser testpassword

**Comment by jlennox** [comment]
Thanks!

**Comment by desa** [comment]
anytime
