### ISSUE TITLE
1.0.1 not available in the debian/ubuntu repository

### ISSUE THREAD

**Issue by francisdb** [influxdata/influxdb#7419]
The website mentions `1.0.1` as latest version but we are not getting the update through `apt-get`

See
https://repos.influxdata.com/debian/dists/xenial/stable/binary-amd64/Packages
vs
https://www.influxdata.com/downloads/

The repository is mentioned in the docs but not in the download section
http://docs.influxdata.com/influxdb/v1.0/introduction/installation/

**Comment by desa** [comment]
Did you go through the process described here: http://docs.influxdata.com/influxdb/v1.0/introduction/installation/#ubuntu-debian

If you didn't, you'll hit this issue https://github.com/influxdata/influxdb/issues/7358

**Comment by desa** [comment]
@rossmcdonald

**Comment by damm** [comment]
1.0.2 is released; and still nothing there.

I mentioned this in Slack; however it seems a bit confusing..

**Comment by rossmcdonald** [comment]
The repository has now been updated. Sorry for the delay!

**Comment by francisdb** [comment]
I guess this process is automated from now on so I won't have to come back asking for 1.0.3 :-)

**Comment by damm** [comment]
Let us hope.
