### ISSUE TITLE
Database restore doesnt work with root user

### ISSUE THREAD

**Issue by jimaek** [influxdata/influxdb#7420]
### Bug report

__System info:__ Influx 1.0.1, CentOS 7 x64

__Steps to reproduce:__

1. Completely backup influx as root
2. Restore backup as root
3. (I did it on a completely fresh server. Not sure if that affects the result)

__Expected behavior:__ A completely operational DB

__Actual behavior:__ Influx used the root user to create the local files and lost access to those files. Error `write failed for shard 143: engine: cache maximum memory size exceeded`

__Additional info:__ https://gist.githubusercontent.com/jimaek/5f7fe91cc5f689273bed64401e564db1/raw/5aea6861548a2f3d86940000f25576402bca29f5/gistfile1.txt

` chown -R influxdb:influxdb /var/lib/influxdb/` fixes the problem

**Comment by jwilder** [comment]
The error you get is because the files are owned by `root` and `influxdb` cannot write to them so the cache fills up.  If you run a backup, you need to run it as the `influxdb` user or chown the files on restore.
