### ISSUE TITLE
SQL Joins, FTW

### ISSUE THREAD

**Issue by inselbuch** [influxdata/influxdb#7422]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

Proposal: Implement SQL Joins in the Influx Query Language
Current behavior: Not supported.
Desired behavior: Supported.

Use case:

When requesting data from InfluxDB it would be very useful to combine metadata, configuration data, etc., from one "table" with the time-series data. For example:

assets (measurement)
time (actually not used in this table)
id (tag) = cryptic internal identifier
friendly (field) = character string
port (field) = number (TCP/IP port number used by the device)

i.e., 
insert assets,id=y268938rjnau3 friendly='Asset1',port=64200

rundata (measurement)
time
id (tag) = cryptic internal identifier
temperature (field)
pressure (field)

This works great:
select last(temperature) from rundata group by mac

But this is what I really want:

Timestamp               Machine          Temperature
-----------------    ----------        -------------
10/05/2016 8:04:06pm    C2475             1675.4
10/02/2016 9:02:11am    C7524             850.5

That might be done like this:

select
      c.time as "Timestamp", a.friendly as "Machine",last(c.temperature) as "Temperature"
from
     rundata c,assets a
where
      c.id = a.id
group by
      c.mac

**Comment by jwilder** [comment]
There is already a feature request for joins logged as: #3552.  Please add your use case to that issue.
