### ISSUE TITLE
[1.0.1] shards not auto-created with custom retention policy

### ISSUE THREAD

**Issue by markweghorst** [influxdata/influxdb#7424]
### Bug report
When i create a database with a custom retention policy, and then insert data with the python client new shards are not created.   This works correctly if you use "create database <name>" and accept the default retention policy.

__System info:__ 
RHEL 7.2
influxdb-1.0.1-1.x86_64
config file is all defaults, and has not been modified from the version deployed in the rpm

__Steps to reproduce:__
drop database amber (if it already exists)
run influx cli
create database amber with duration 1d replication 1 shard duration 1h
show retention policies on amber
run the python script from https://gist.github.com/markweghorst/6c415b05a63c7d6ace61fd6a8aeaf5ba
show shards (verify that the shards were not created when the inserts were done)

__Expected behavior:__ 
When data is inserted new shards should be created to hold the new data.  

__Actual behavior:__ 
No new shards were created and the data inserted was never stored

__Additional info:__ 
log file https://gist.github.com/markweghorst/e24ae6884043ff28c9486a2b93a11bbc
If you use "create database amber" and accept the default retention policies, this works correctly.  This is only broken with a user-specified retention policy.

**Comment by jwilder** [comment]
@markweghorst Your script is not specifying a precision of `s` so the points are being dropped because they parse as nanoseconds from the unix epoch.  If you run `SHOW STATS FROM 'write'`, you should see that `writeDrop` stat has increased.

If you change your script to write using:

```
        ifdb.write_points(json_body, time_precision="s")
```

you will see the shards get created.

**Comment by jwilder** [comment]
They are dropped because they would create a shard that would be immediately removed (points in a 1hr shards at `1970-01-01` that expires on `1970-01-02`).  The default rp has an infinite duration so the shards would not expire and the points are not dropped.
