### ISSUE TITLE
Stddev function accepts strings

### ISSUE THREAD

**Issue by Tomcat-Engineering** [influxdata/influxdb#7436]
[This line in the source code](https://github.com/influxdata/influxdb/blob/master/influxql/ast.go#L1171) specifically allows the `stddev` (standard deviation) function to accept time series of datatype "string".  

Obviously there is no sensible way to take the standard deviation of a load of strings, and [the implementation](https://github.com/influxdata/influxdb/blob/master/influxql/call_iterator.go#L749) always returns an empty string.

This is inconsistent with all the other comparable functions (such as `mean`), which throw an error if you feed them strings.

Was there a reason for this special case?

**Comment by jsternberg** [comment]
Looks like the piece of code that allows `stddev()` to operate on strings has been there since the beginning and I can't find a commit that explains why from a quick look.

@benbjohnson do you have any idea?

**Comment by benbjohnson** [comment]
@jsternberg I can't think of any reason to use a `string`. We can remove that.
