### ISSUE TITLE
What is func (c *Call) Fields() for?

### ISSUE THREAD

**Issue by Tomcat-Engineering** [influxdata/influxdb#7439]
I was adding a new InfluxQL function when I came across [this function](https://github.com/influxdata/influxdb/blob/master/influxql/ast.go#L3217).

I have a few questions about it:

1. What is it used for?  I can't see any obvious in the code which uses it.  If I delete it, everything still compiles.  Is it used for some top-secret part of the commercial clustering code?  Or is it old code which can be removed?

2. The comment says that it only applies to "specific calls".  How do I know which calls it should apply to?  For example, it currently works for `mean` and `mode` but not `median`... is there some subtle reason for this or is it just an oversight?  How do I know whether it should apply to my new function?

Thank you!

**Comment by jsternberg** [comment]
Probably just an old function that's not used anymore. There are a bunch of them that I try to purge whenever I find them. The query engine especially went through a major refactor in 0.11 and a lot of these kinds of functions that it used were not removed since they still compiled perfectly fine.
