### ISSUE TITLE
influxdb console shell should make use of the history

### ISSUE THREAD

**Issue by rolele** [influxdata/influxdb#7444]
using arrow up and arrow down on the influxdb console is giving this result:
````
> ^[[A^[[A^[[B^[[B
````
forcing me to re-enter each query manually. This is really annoying.
I know the webUI is providing this feature but I would like the console to it as well.

**Comment by jkahrs** [comment]
Influx is using [Liner](https://github.com/peterh/liner) for the CLI.

You should be able to search the history (cmd+r) -> search term.
However it seems there is currently no support for ArrowUp/ArrowDown within that lib.

**Comment by jsternberg** [comment]
What are you running this inside of? If you run it in a normal terminal, this should already work. I think there might be an issue though if you run the CLI within Docker. I haven't investigated why the arrow keys don't work in Docker yet, but I think I remember running into that before.

I know it works on Mac OS X. If you can tell us where this happens, we can work on getting the issue to the appropriate spot.

**Comment by casertap** [comment]
I am running influxdb in a Docker container. I am using tmux, and my terminal is item.

While running influxdb in a container, you do not want to open the port to access the UI. You just want a console that work.

thank a lot for your interest in this issue

**Comment by rolele** [comment]
I am running influxdb in a Docker container. I am using tmux, and my terminal is item.

While running influxdb in a container, you do not want to open the port to access the UI. You just want a console that work.

thank a lot for your interest in this issue

**Comment by jsternberg** [comment]
Closing this in favor of influxdata/influxdata-docker#26.

**Comment by grahamnicholls** [comment]
And frankly, if it doesn't support Vim mode, then it's broken.   Yes
