### ISSUE TITLE
Config setting to insist that measurement names be ascii

### ISSUE THREAD

**Issue by pbooth** [influxdata/influxdb#7446]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

**Proposal:**  Add a configuration setting to enforce that measurement names must be ascii

**Current behavior:** Today measurement names are internationalizable and can contain special characters

**Desired behavior:**  For influxdb.conf to have a setting that requires that measurement names be ascii

**Use case:**  At times, due to human error, I have written gzipped files to the UDP and HTTP end-points of influxdb instances. The result has been the creation of measurements with non-ascii names, 
Thus far, the only way to rectify this situation that I have found has been to drop the entire database and start again:

for example:

```
> use intake
Using database intake
> show measurements
name: measurements
------------------
name
6�u{�/�1'��
amps_latencies
dummy
latency
latency_micros
ma_latencies
prism
prismAPI
prism_latencies

The problem with this is that DROP MEASUREMENT '6�u{�/�1'��' doesn't work:
> DROP MEASUREMENT '6�u{�/�1'��'
ERR: error parsing query: found 6�u{�/�1, expected identifier at line 1, char 17
> DROP MEASUREMENT 6�u{�/�1'��
ERR: error parsing query: found 6, expected identifier at line 1, char 18
> DROP MEASUREMENT "6�u{�/�1'��"
ERR: measurement not found: 6�u{�/�1'��
```

Of course, if there were a regex syntax acceptable to DROP MEASUREMENT then there would be no real need for the feature that I suggest.

**Comment by jsternberg** [comment]
Hm, it should absolutely be possible to drop measurements with foreign characters. My best guess would be that your computer is not showing the correct characters when it outputs UTF-8 so, when you try to repaste the text, it doesn't get read correctly by the parser.
