### ISSUE TITLE
Documentation Theme Toggling Broken

### ISSUE THREAD

**Issue by mingraham** [influxdata/influxdb#7452]
When you navigate to https://docs.influxdata.com/ with Dark Mode toggled on (the default, meaning that in the upper right corner you see a sun icon), click any of the options (Telegraf, InfluxDB, Chronograf, Kapacitor, Enterprise), and then toggle to light mode (click the sun icon), CSS discovers entropy.

**Comment by jsternberg** [comment]
Can you make a new ticket at https://github.com/influxdata/docs.influxdata.com for this? We don't handle documentation issues in this repository. Thanks.

/cc @rkuchan
