### ISSUE TITLE
Strange continuous queries behaviour

### ISSUE THREAD

**Issue by szank** [influxdata/influxdb#7453]
### Bug report
InfluxDB 0.13.0, FreeBSD 11.0-RC2 installed via `pkg`

Steps to reproduce 

1.Create continuous query no.1 
`CREATE CONTINUOUS QUERY "99thPercentileSourceType1-Second" ON testDB BEGIN SELECT percentile(value, 99) AS percentile99 INTO testDB.hourly.SourceType1-99thPercentileSecond FROM testDBRaw.raw."source1-raw" GROUP BY time(1s), node, operation END`

2.Create continuous query no.2
`CREATE CONTINUOUS QUERY "99thPercentileSourceType2-Second" ON testDB BEGIN SELECT percentile(value, 99) AS percentile99 INTO testDB.hourly.SourceType2-99thPercentileSecond FROM testDBRaw.raw."source2-raw" GROUP BY time(1s), node, operation, source, intent END`

Expected behaviour:
Both CQs beeing executed in real time  

Actual bevaviour: 
From what I can see, in the logs, cq `99thPercentileSource1-Second` executes, and backfills data from `NOW()` to the oldest timestamp in the `testDBRaw.raw."source1-raw"`, it takes, an hour or two let's say. The CQs sometimes take less than one second, sometimes ~20 seconds. Measured by the `show queries` command. 
When there are no more data to backfill, the `99thPercentileSource2-Second` kicks in, starts backfilling. Finishes after one or two hours,  and `99thPercentileSource1-Second` kicks in. The problem is that,  two hours have passed already and the CQ starts backfilling the data again!. 

We are graphing the results of those CQs in grafana, and we just can't get view on the latest numbers, as the CQs are backfiliing the data constantly. 

The number of concurrent queries is not limited in the config. 

My working theory is that Influx ticks every 1 second and checks if there is a CQ to run. It doesn't start the queries concurrently though, so on ever tick it starts only one CQ. Is that correct ?

I could try run my CQs with `RESAMPLE`, this might help, potentially, but if I resample every 10 sec for examople, and the larger CQ takes more than 10 seconds, then I guess I will have the same problem. 

Any ideas?

**Comment by jwilder** [comment]
I'd recommend upgrading to 1.0.2 as there are many query/write and CQ bug fixes.  I'm going to close this, but if it's still occurring comment on this issue and we'll re-open.
