### ISSUE TITLE
port 8086 8083 can not start!

### ISSUE THREAD

**Issue by Witee** [influxdata/influxdb#7460]
CentOS release 6.8 (Final)

version : influxdb-1.0.2.x86_64.rpm

when I restart influxdb use /etc/init.d/influxdb restart, only 8088 cat listen,8086 and 8083 can not!
why ?

**Comment by Witee** [comment]
Waiting for half an hour after the start of their own！
why ?

**Comment by jwilder** [comment]
We need more information in order to diagnose what is going on.  Can you update the issue description with the instructions listed in our [issue template](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md)?

**Comment by Witee** [comment]
Sorry for that.

I delete all of influxdb data files, and resetart influxdb, it works!

Thank you.
