### ISSUE TITLE
influx db error {"error":"[shard 5] unknown engine format"}

### ISSUE THREAD

**Issue by juliangamble** [influxdata/influxdb#7461]
### Bug report

__Steps to reproduce:__

curl -i -XPOST 'http://server:8086/write?db=data_db&precision=s' --data-binary @file   

__Expected behavior:__ [What you expected to happen]

File uploaded successfully. 

__Actual behavior:__ [What actually happened]

    HTTP/1.1 100 Continue
    HTTP/1.1 500 Internal Server Error
    Content-Type: application/json
    Request-Id: 8259da4b-8fed-11e6-b6f5-000000000000
    X-Influxdb-Version: 0.13.0
    Date: Tue, 11 Oct 2016 20:01:33 GMT
    Content-Length: 44

    {"error":"[shard 5] unknown engine format"}
    Complete: 0

__Additional info:__ [Include gist of relevant config, logs, etc.]

Here are the diagnostic files:
https://gist.github.com/juliangamble/7316282346d1a4f0585e8222054a7406

**Comment by jwilder** [comment]
@juliangamble Do you have old shards from prior releases?  If so, you will need to convert them to TSM using the [migration tool](https://github.com/influxdata/influxdb/blob/master/cmd/influx_tsm/README.md)

**Comment by juliangamble** [comment]
Thanks @jwilder - I've updated the names of the files in the linked gist: https://gist.github.com/juliangamble/7316282346d1a4f0585e8222054a7406

When I look at the stats.txt file - all the databases appear to be in `tsm1` format. (ie `engine=tsm1`). 

I haven't changed versions, and am still on the same one.  

What is my path to remediation?

**Comment by jwilder** [comment]
@juliangamble Can your run `find /data -type f -print`?

**Comment by juliangamble** [comment]
Here it is:
https://gist.github.com/juliangamble/16bb324b6e40655a7c2fc3b49454d129
What in particular am I looking for?

**Comment by e-dard** [comment]
@juliangamble I think that you have some old `bz1` shards in there:

```
/data/db/data_db/default/2
/data/db/data_db/default/5
/data/db/data_db/default/11
```

**Comment by jwilder** [comment]
@juliangamble Yeah, you have 3 shards that are not TSM shards.  You'll need to use the migration tool to convert them to TSM shards.  Alternatively, you can drop them if you don't need that data any longer.

**Comment by juliangamble** [comment]
Brilliant! Thanks.
