### ISSUE TITLE
Can't write data to explicit retention policy using the HTTP API?

### ISSUE THREAD

**Issue by MatMeredith** [influxdata/influxdb#7465]
I have two separate retention policies defined for my database and I want to specify which should be used for each stat that I write to the database (via the HTTP API).  On other APIs, the docs say that this can be achieved by fully qualifying the measurement: "<database>"."<retention_policy>"."<measurement>" but this doesn't seem to work on the HTTP API.   If a I post to "/write?db=main" and send content like

"main.stats_default.memBuffer value=888i 1476433915000000000"

then the HTTP request is successful (I get a 204), but no data is written to the DB for a measurement named "memBuffer".  Instead a measurement is created called "main.stats_default.memBuffer" (which isn't what I want, and even then I don't seem to get any data points when I query it).

Is this possible?   If not this is a major limitation.   I need to use the HTTP API for my application, and I need to be able to have two different sets of data with different retention policies...

**Comment by mark-rushakoff** [comment]
The dot-separated format of `db.rp.m` applies to queries. The [API documentation for the /write endpoint](https://docs.influxdata.com/influxdb/v1.0/tools/api/#write) explains that you must set the `rp` query parameter, e.g. `http://localhost:8086/write?db=main&rp=stats_default`.

Please open an issue on [the docs repo](https://github.com/influxdata/docs.influxdata.com) if there was anything particular that led to this confusion.

**Comment by MatMeredith** [comment]
Ah -- thanks.   I will raise a docs issue...

**Comment by nyfpos** [comment]
rb not rp ...
