### ISSUE TITLE
too many RAM intensive things happen on certain time boundaries

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7474]
### Feature Request

__Proposal:__ 

Avoid TSM file compactions too close to scheduled CQs. 

Make retention policy expirations lower priority than any active query.

__Current behavior:__ 

TSM file compactions, retention policy expirations, and continuous queries can all happen at round number boundaries, particularly midnight UTC.

__Desired behavior:__ 

TSM file compactions, retention policy expirations, and continuous queries can be staggered or jittered to prevent simultaneous execution.

__Use case:__ 

If a midnight CQ takes 20% of the RAM on the box, I want to make sure no compactions or retention policy expirations trigger then and compete for resources. Tasks with a weak real-time necessity should be delayed so CQs can execute cleanly.

**Comment by jwilder** [comment]
#7142 would address this.

**Comment by beckettsean** [comment]
Agreed, thanks, @jwilder. Closing in favor of #7142
