### ISSUE TITLE
improve error message for derivative()

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7487]
### Feature Request

__Current behavior:__ 

Without a `GROUP BY time` clause, the error message from an improper `DERIVATIVE()` query is pretty useless.

```
> select derivative("writeReq") from "shard" where time > 0 
ERR: invalid character 'j' looking for beginning of value
```

With the `GROUP BY time` clause, the error message from an improper `DERIVATIVE()` query is very clear.

```
> select derivative("writeReq") from "shard" where time > 0 group by time(10w) 
ERR: error parsing query: aggregate function required inside the call to derivative
```

__Desired behavior:__

The `ERR: error parsing query: aggregate function required inside the call to derivative` should be returned in both cases.

__Use case:__ 

Anyone not familiar with `DERIVATIVE()` syntax will likely get stuck with no way forward if they get the `'j'` error.

**Comment by beckettsean** [comment]
@e-dard

**Comment by rkuchan** [comment]
@beckettsean, I thought `derivative()` worked without a `GROUP BY time()` clause - see the first example in https://docs.influxdata.com/influxdb/v1.0/query_language/functions/#derivative. I just ran it in 1.0.2 on the doc's sample data and it worked.

**Comment by e-dard** [comment]
@beckettsean I don't see this error when I use the `influx` client installed as part of `1.0.2`. Is your `influx` up to date?

**Comment by rkuchan** [comment]
I believe it was fixed in 1.0.1: https://github.com/influxdata/influxdb/issues/7110

**Comment by beckettsean** [comment]
That is possible. My client is still 1.0.0

**Comment by beckettsean** [comment]
I no longer get the `'j'` error, but I got a weird set of errors when trying the same query:

```
> select derivative("writeReq") from "shard" where time > 0 
ERR: json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: NaN
json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: -Inf
json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: NaN
json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: -Inf
json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: NaN
json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: +Inf
... (maybe 100 repeats of one of the three)
```

**Comment by e-dard** [comment]
@beckettsean did you also run `1.0.2 influxd` along with `1.0.2 influx`?

**Comment by beckettsean** [comment]
@e-dard for yesterday's comment I used `1.0.0 influxd` along with `1.0.2 influx`.

I upgraded to `1.0.2 influxd` and the error is gone.
