### ISSUE TITLE
No data written on db

### ISSUE THREAD

**Issue by eppak** [influxdata/influxdb#7490]
Hello, i have a influx 1.02 on a debian 64 i backupped the data a week ago, i restored it today (with the command of the manual). 

#influxd restore -database devices -datadir /var/lib/influxdb/data -metadir /var/lib/influxdb/meta /tmp/backup

Now i post some data (sent with nanoseconds and seconds):

#curl -i -XPOST http://localhost:8086/write?db=devices "log,uuid=xxxxxx V11=0,V16=0,V21=0,V26=0,V31=0,V32=0,V0=1,V1=1,V3=-5,V4=-4,V5=-5,V6=-5,V7=79,V8=79,V9=79,V10=79,V15=0,V13=0,V14=0,V12=0,V20=0,V18=0,V19=0,V17=0,V25=0,V23=0,V24=0,V22=0,V30=0,V28=0,V29=0,V27=0,V33=0,V34=0,V35=0,V36=0,V37=0,V38=0,V39=0,V40=0,V41=0,V42=0,V43=0,V44=0,V45=0,V46=0,V47=0,V48=0,V49=0,V50=0,V51=0,V52=0,V53=0,V54=0,V55=0,V56=0,V57=0,V58=0,V59=0,V60=0,V61=0,V62=0,V63=0,V64=0,V65=0,V66=0,V67=0,V68=0,V69=0,V70=0,V71=0,V72=0,V73=0,V74=0,V75=0,V76=0,V77=0,V78=0,V79=0,V80=0,V81=0,V82=0,V83=0,V84=0,V85=0,V86=0,V87=0,V88=0,V89=0,V90=0,V91=0,V92=0,V93=0,V94=0,V95=0,V96=0,V97=0,V98=0,V99=0 1476969960000000000"
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: b7b69408-96cb-11e6-8009-000000000000
X-Influxdb-Version: 1.0.2
Date: Thu, 20 Oct 2016 13:47:18 GMT

The date is not in the future:
#date
Thu Oct 20 13:47:35 UTC 2016

In the database i see only old data, i got no errors on syslog, on va/log/influxdb there is no file. I restored permssion and user on /var/lib/influxdb. I have no idea how to trace a deep log.

Thanks

**Comment by jwilder** [comment]
That inserts fine for me and is query-able.  Try adding `time < now() + 1d` to your query to see if there is a difference in time on your server vs client.

**Comment by eppak** [comment]
Yes, tried but no luck, beside this i tried another way. Disinstalled influx and purged the packed, reinstalled and copied my old config file, created the db and the retention. From this i restored the data and now seem to work. Is possible that if you backup at date X then at date Y you make a restore of X, the data between X and Y (with metadata) create a conflict?

This tipe of behaviour frighten me a lot. Any chance to investigate with some other log?
Thanks for support.

**Comment by jwilder** [comment]
Did the default retention policy change from your restore?  Perhaps your writes were going into a different RP from the one you are querying?

I'm going to close this as it seems you have resolved it.  If you are able to reproduce the issue reliably, we can debug further.
