### ISSUE TITLE
GET method for /query with InfluxDB v0.10.0

### ISSUE THREAD

**Issue by soshnikov** [influxdata/influxdb#7491]
[InfluxDB allows GET only method for SELECT and SHOW query types.
https://docs.influxdata.com/influxdb/v1.0/tools/api/

But 
`func (c *client) Query(q Query) (*Response, error)` 
use only POST method for query. Than InfluxDB return HTTP 405 for such queries.

**Comment by jsternberg** [comment]
We are not continuing to support v0.10.0. If you need to use v0.10.0, you can pin your go dependency to an older revision or just take the code from an older revision and fork it into a new repository. Sorry.
