### ISSUE TITLE
panic: interface conversion: tsm1.Value is *tsm1.FloatValue, not *tsm1.StringValue

### ISSUE THREAD

**Issue by Apollon77** [influxdata/influxdb#7498]
Hi,

I use InfluxDB 1.0.2 on armhf Ubuntu Xenial.

Since yesterday I get a restart each hour with the following:

```
Oct 21 07:40:52 cubietruck3 influxd[18586]: [tsm1] 2016/10/21 07:40:52 Snapshot for path /var/lib/influxdb/data/iobroker/global/59 written in 5.377168818s
Oct 21 07:40:52 cubietruck3 influxd[18586]: panic: interface conversion: tsm1.Value is *tsm1.FloatValue, not *tsm1.StringValue
Oct 21 07:40:52 cubietruck3 influxd[18586]: goroutine 161 [running]:
Oct 21 07:40:52 cubietruck3 influxd[18586]: panic(0x6686f0, 0x1f1fc760)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/usr/local/go/src/runtime/panic.go:481 +0x330
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.encodeStringBlock(0x0, 0x0, 0x0, 0x17c685f0, 0xa, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:517 +0x200
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.Values.Encode(0x17c685f0, 0xa, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:82 +0x148
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*cacheKeyIterator).Read(0x1498d980, 0x0, 0x0, 0x7c6da700, 0x14605c03, 0xabe3e080, 0x146234eb, 0x0, 0x0, 0x0, ...)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1266 +0x28c
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0x11ec71c0, 0x181e60a0, 0x45, 0x7a5bc4a8, 0x1498d980, 0x0, 0x0)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:731 +0x498
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0x11ec71c0, 0x1, 0x1, 0x7a5bc4a8, 0x1498d980, 0x0, 0x0, 0x0, 0x0, 0x0)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:672 +0x2b4
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).WriteSnapshot(0x11ec71c0, 0x1b6776e0, 0x0, 0x0, 0x0, 0x0, 0x0)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:533 +0x138
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).writeSnapshotAndCommit(0x11075320, 0x15f6af88, 0x1, 0x1, 0x1b6776e0, 0x0, 0x0)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:776 +0x84
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).WriteSnapshot(0x11075320, 0x0, 0x0)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:751 +0x278
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactCache(0x11075320)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:814 +0x208
Oct 21 07:40:52 cubietruck3 influxd[18586]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).SetCompactionsEnabled
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:166 +0x11c
Oct 21 07:40:52 cubietruck3 systemd[1]: influxdb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 21 07:40:52 cubietruck3 systemd[1]: influxdb.service: Unit entered failed state.
Oct 21 07:40:52 cubietruck3 systemd[1]: influxdb.service: Failed with result 'exit-code'.
Oct 21 07:40:53 cubietruck3 systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.
Oct 21 07:40:53 cubietruck3 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
Oct 21 07:40:53 cubietruck3 systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
```

On Restart the line from "filestore" of open the tsm file is also missing for "59". The directory /var/lib/influxdb/data/iobroker/global/59 is empty
What can I do?

**Comment by Apollon77** [comment]
I was able to solve the problem by "drop shard 59" with the loss of all the data in that timeperiod ;-(
And I had the problem again some days later, but this time with an auto-restart-loop. I was able to solve it by explicitely stopping the service and start again, then "snapshotting" was disabled.
I deleted the affected shard (other number) too and did a stop-start and snapshotting was enabled again.

I currently migrate many data from a file based logging into influxdb for better future usage and sometimes there are "type conflicts" because of float vs boolean and such, but normallyI would await that these problems are simply not written and  so du not make any problem.

**Comment by e-dard** [comment]
@Apollon77 thanks for the report, and apologies that you had to drop the shard to stop this. This looks like an issue with the same field containing data of different types. As you say, it's the type conflicts from your dataset.

Yes these writes shouldn't make it into the system and we'll keep you updated as we investigate.

**Comment by jwilder** [comment]
@Apollon77 Did you upgrade from a prior version at some point?  There was a bug (#6652) that existed in earlier 1.0 releases.

**Comment by Apollon77** [comment]
yes, I had 1.0.0 and then upgraded to 1.0.2 via "apt-get upgrade" as it was available.
I use InfluxDB since mid september 2016 ...

**Comment by jwilder** [comment]
Hmm.  That bug/fix was in the 1.0 beta releases which was prior to 1.0.0.  This may be a different, but similar issue.

**Comment by Apollon77** [comment]
I also noticed one interesting fact and want to share it ... maybe it's connected.

As said above I currently migrate a lot of "old data" colelcted in other formats into the InfluxDB. It seems to happen that the old data (e.g. June 2016) and current dats (now) have different datatypes (boolean vs float/int). This should be ok as soon as these data are written into different shards.

My software collects data and does a "mass write" after reached a certain limit of datapoints. So it seems to happen that data for several shards are in the same write call. Then it happens that I get infos on type conflicts, e.g. 

```
[write] 2016/10/26 15:05:06 write failed for shard 73: field type conflict: input field "value" on measurement "hm-rpc.1.CUX0200001.1.STATE" is type float64, already exists as type boolean
```
because of such cases no data are written to influxDB my software writes these data again per measurement.
And now the interesting fact: The write succeeded in that second try.

So it seems to me that for "multi-shard" or "multi-measurement" or "mass" writes the type checking sometimes is strange somehow ...
And maybe based there the reason is also in ?!
... just an idea/info :-)

**Comment by jwilder** [comment]
@Apollon77 That's helps.  I was able to reproduce this in a test which on this [branch](https://github.com/influxdata/influxdb/tree/jw-7498).  It occurs more easily on 1.0, but not as frequently on 1.1 due to some recent changes.  No fix yet.
