### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by asquare** [influxdata/influxdb#7503]
I could'nt find a LICENSE or a license header in the source, please consider adding one. Thanks

**Comment by jsternberg** [comment]
There's a [license file](https://github.com/influxdata/influxdb/blob/master/LICENSE) in the root of the repository. Is there anything else you want?

**Comment by asquare** [comment]
Ah thanks - I was only looking at the client, missed the LICENSE at the top-level of the repo.
