### ISSUE TITLE
Influx 0.12.2 memory consumption spikes and then freezes on all query requests

### ISSUE THREAD

**Issue by rtv2222** [influxdata/influxdb#7506]
### Bug report

Influx DB Version : 0.12.2
OS : Ubuntu 14.04 on VMware
cpus : 8
Memory : 16 GB
Disk : SSD

__Steps to reproduce:__

I have 4 measurements on influx with the largest of them having around 3086448 points. Data is being written to this measurement at the rate of 4000 points every minute.

After about 2 hours of uptime, InfluxDB memory usages spikes from 1.2 GB to 16 GB. The spikes are about 30 mins apart and while the consumption comes down eventually, influxdb freezes and stops responding to any requests (via InfluxDB java client or over http). Influx would have to be killed (kill -9) and restart for it to start responding to queries again.

Here is the HeapAloc output from the _internal database of Influx as seen on Chronograph.

![image](https://cloud.githubusercontent.com/assets/13368028/19643601/b8fe73ea-9a08-11e6-9fc0-deb0dbf22947.png)

__Expected behavior:__ Continue to use around 2 GB of memory instead of the spike. Continue responding to queries.

__Actual behavior:__  Please see the description above

__Additional info:__ 

The following information is post restart of influx db

[shards.txt](https://github.com/influxdata/influxdb/files/547623/shards.txt)
[block.txt](https://github.com/influxdata/influxdb/files/547621/block.txt)
[diagnostics.txt](https://github.com/influxdata/influxdb/files/547622/diagnostics.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/547618/goroutine.txt)
[heap.txt](https://github.com/influxdata/influxdb/files/547620/heap.txt)
[iostat.txt](https://github.com/influxdata/influxdb/files/547619/iostat.txt)
[stats.txt](https://github.com/influxdata/influxdb/files/547624/stats.txt)
[vars.txt](https://github.com/influxdata/influxdb/files/547625/vars.txt)

Here is the influxdb.conf

[influxdb.conf.txt](https://github.com/influxdata/influxdb/files/547632/influxdb.conf.txt)

Do let me know what other data can be collected when influx freezes since I will not be able to run most of the above.

**Comment by jwilder** [comment]
`0.12.2` is no longer maintained.  Please upgrade to `1.0.2` as there have been many fixes since `0.12.2`.  If the issue is still occurring in 1.0.2, please log a new issue.

**Comment by rtv2222** [comment]
Thanks for the quick revert.  I will repeat the steps with 1.0.2 Could you answer the following question ?
Do let me know what other data can be collected when influx freezes since I will not be able to run most of the above.

Thanks,
Rajesh

**Comment by jwilder** [comment]
@rtv2222 What your captured and recorded is useful.  We would need to have the captures (especially heap) when the memory usage is high though.  After restart doesn't help much in this case.

**Comment by rtv2222** [comment]
Thanks Jason. I just created #7508 with 1.0.2 where I am already seeing a lot of spikes in memory consumption upto 9 Gig.
