### ISSUE TITLE
Slow group by time

### ISSUE THREAD

**Issue by ikovalyov** [influxdata/influxdb#7511]
### Bug report

**System info:** InfluxDB Admin UI: v1.0.2 Server: v1.0.2

**Steps to reproduce:**
1. I have nodes.infinity.DPMeanHourly measurement with 6246433 points
2. Do call 
   
   `SELECT count(response_time) FROM infinity.DPMeanHourly WHERE time >= 1475280000000000000 AND time <= 1476489600000000000`
3. Received response 6246433 within 799ms which is absolutely ok
4. Do call
   
   `SELECT mean(response_time) FROM infinity.DPMeanHourly WHERE time >= '2016-10-01 12:00:00' AND time <= '2016-10-15 04:00:00' GROUP BY time(1h)`
5. Received response within 24s which is definitely not ok .

**Expected behavior:** group by 1h request should take 1-3 seconds

**Actual behavior:** It takes 24s

**Additional info:** [gist](https://gist.github.com/ikovalyov/179a1f8b254e3204c36f589ffc56af55)

**Comment by ikovalyov** [comment]
The query

```SELECT count(response_time) FROM infinity.DPMeanHourly WHERE time >= 1475280000000000000 AND time <= 1476489600000000000 GROUP BY time(1d)```
Takes 2.34s to respond

The query 

```SELECT count(response_time) FROM infinity.DPMeanHourly WHERE time >= 1475280000000000000 AND time <= 1476489600000000000 GROUP BY time(2h)```
Takes 12.42s to respond.

It looks like influx response time is proportional to the response points count, not processed data length. Definitely looks like an issue for me.

Thanks.

**Comment by jwilder** [comment]
Can you run:
`curl -O http://localhost:8086/debug/pprof/profile`

and then run the slower query and attach the `profile` file that is recorded when the curl command completes?  It will collect a profile for 30s.

**Comment by ikovalyov** [comment]
[profile.txt](https://github.com/influxdata/influxdb/files/552555/profile.txt)
Here you are

**Comment by jimaek** [comment]
@jwilder Any news on this?

**Comment by jwilder** [comment]
Can you try `1.1rc1`?

**Comment by ikovalyov** [comment]
InfluxDB Admin UI: v1.1 Server: v1.1.0~rc1

```
SELECT count(response_time) FROM infinity.DPMeanHourly WHERE time >= 1475280000000000000 AND time <= 1476489600000000000
```
Takes 616ms vs 799ms

```
SELECT mean(response_time) FROM infinity.DPMeanHourly WHERE time >= '2016-10-01 12:00:00' AND time <= '2016-10-15 04:00:00' GROUP BY time(1h)
```
Takes 19.43 vs 24s

```
SELECT count(response_time) FROM infinity.DPMeanHourly WHERE time >= 1475280000000000000 AND time <= 1476489600000000000 GROUP BY time(1d)
```
Takes 1.73 vs 2.34

```
SELECT count(response_time) FROM infinity.DPMeanHourly WHERE time >= 1475280000000000000 AND time <= 1476489600000000000 GROUP BY time(2h)
```
Takes 11.33 vs 12.42

Faster but still not so fast as it should be :)

**Comment by ikovalyov** [comment]
any update?

**Comment by ikovalyov** [comment]
performance degradation at 1.2

```
SELECT count(response_time) FROM nodes.infinity.DPMeanHourly WHERE time >= '2017-01-01' AND time <= '2017-01-15'
```
803 ms

```
SELECT count(response_time) FROM nodes.infinity.DPMeanHourly WHERE time >= '2017-01-01' AND time <= '2017-01-15' group by time(1h)
```
25.74 s

```
SELECT count(response_time) FROM nodes.infinity.DPMeanHourly WHERE time >= '2017-01-01' AND time <= '2017-01-15' group by time(1d)
```
1.96

```
SELECT count(response_time) FROM nodes.infinity.DPMeanHourly WHERE time >= '2017-01-01' AND time <= '2017-01-15' group by time(2h)
```
13.45

**Comment by jimaek** [comment]
@jwilder Check it out when you have time please

**Comment by jimaek** [comment]
ping

**Comment by dgnorton** [comment]
@briandilley which release are you on?

**Comment by russorat** [comment]
closing due to lack of response.
