### ISSUE TITLE
Installation of 1.0.2 on Ubuntu 16.10 fails

### ISSUE THREAD

**Issue by tagliola** [influxdata/influxdb#7512]
As the yakkety pages are not available yet (from apt-get update):

`Err:9 https://repos.influxdata.com/ubuntu yakkety/stable i386 Packages`
`404  Not Found`

I tried installing it by downloading the deb. However, after installation it fails to start, due to missing config:

`Oct 25 11:22:29 machine influxd[11974]: [run] 2016/10/25 11:22:29 Using configuration at: /etc/influxdb/influxdb.conf`
`Oct 25 11:22:29 machine influxd[11974]: run: parse config: open /etc/influxdb/influxdb.conf: no such file or directory`

I tried creating the configfile, and moving it there:

`influxd config > influxdb.conf`
`sudo mv influxdb.conf /etc/influxdb/`

However, then I get a Permission Denied on startup:

`Oct 25 11:26:07 machine influxd[12191]: [run] 2016/10/25 11:26:07 Using configuration at: /etc/influxdb/influxdb.conf`
`Oct 25 11:26:07 machine influxd[12191]: run: create server: mkdir all: mkdir /home/username/.influxdb/meta: permission denied`

Not sure how to proceed from here. Probably related issue: https://github.com/influxdata/influxdb/issues/3799

**Comment by desa** [comment]
@tagliola which `deb` did you install?

**Comment by logston** [comment]
Had the same issue on Ubuntu 14.04 with influx 1.0.2.

Turns out the config file was this:

```
...
[meta]
  dir = "/home/influxdb/.influxdb/meta"
  retention-autocreate = true
  logging-enabled = true

[data]
  dir = "/home/influxdb/.influxdb/data"
  engine = "tsm1"
  wal-dir = "/home/ubuntu/.influxdb/wal"
...
```

But influx was installed by `apt` with a home directory at `/var/lib/influxdb`. 

##### /etc/passwd

```
influxdb:x:999:999::/var/lib/influxdb:/bin/false
```

Updating the config file to this solved my issues:

```
...
[meta]
  dir = "/var/lib/influxdb/.influxdb/meta"
  retention-autocreate = true
  logging-enabled = true

[data]
  dir = "/var/lib/influxdb/.influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/.influxdb/wal"
...
```

**Comment by tagliola** [comment]
@desa Appologies, I missed your request for information. 

First one, as I wanted to have the apt repo, the [installation instructions](https://docs.influxdata.com/influxdb/v1.0/introduction/installation/):

`curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -`
`source /etc/lsb-release`
`echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list`
`sudo apt-get update && sudo apt-get install influxdb`

but as mentioned, the packages for yakkety were not available yet.

Second attempt was the [download instructions](https://www.influxdata.com/downloads/) for Ubuntu:
`wget https://dl.influxdata.com/influxdb/releases/influxdb_1.0.2_amd64.deb`
`sudo dpkg -i influxdb_1.0.2_amd64.deb`
`systemctl start influxdb`

This was one a almost pristine install of Ubuntu 16.10 server, the only other items installed before this were sshd and Oracle java8 through the webupd8team repository.

**Comment by desa** [comment]
@tagliola and in both cases it doesn't work?

**Comment by tagliola** [comment]
Yes, the install instructions failed due to https://repos.influxdata.com/ubuntu/dists/yakkety/ not being there. Now I see that it has been added, so I can try again.

The download instructions failed with the permission denied as in my first comment.
