### ISSUE TITLE
[http].max-connection-limit seems to have no effect --> Causes very high memory

### ISSUE THREAD

**Issue by abadyan-vonage** [influxdata/influxdb#7513]
### Bug report

__System info:__ InfluxDB 1.0.0, hosted on AWS, centos 7.

__Steps to reproduce:__

We currently have lots of clients doing both queries and writes in the following form:
1. Start the process
2. query
3. write
4. process ends

This means the client never closes the connection. 
**Question: Does this matter given that the process is closed? Would the client still cause a memory leak?**

To handle this until we change the clients, I tried setting the max-connection-limit setting to 1000. I did not find it in the influxdb config file so I added it under the [http] section. This had no effect - running netstat still showed several thousands of open connections.

**The problem: max-connection-limit doesn't seem to work or maybe it is not included in 1.0.0?** Anyway, config should be updated.

This is my http section:

>   [http]
>   enabled = true
>   bind-address = ":REMOVED"
>   auth-enabled = true
>   log-enabled = true
>   write-tracing = false
>   pprof-enabled = false
>   https-enabled = false
>   https-certificate = "/etc/ssl/influxdb.pem"
>   ### Use a separate private key location.
>   # https-private-key = ""
>   max-row-limit = 10000
>   max-connection-limit = 1000
>   realm = "InfluxDB"

**Comment by jwilder** [comment]
@abadyan-vonage You should be closing your connections when your client ends.  A `max-connection-limit = 1000` is very high.  That would allow your server to hold onto 1000 _concurrent_ open connections which would very likely cause other parts of the system to queue and consume more memory.  I'd suggest lowering that by a factor or 10 or more and explicitly closing/tearing down your client connections when the process ends.

**Comment by abadyan-vonage** [comment]
Thanks @jwilder, I changed the connection limit to 80 and server seems to perform better now.
Stupid of me not to check that right away, what confused me was the number of connection in netstat, but I guess they were not all open simultaneously.
We will fix the clients soon, hope this will eliminate the problem altogether.
