### ISSUE TITLE
Can't install influxdb on osx 10.12 (macOS Sierra)

### ISSUE THREAD

**Issue by masudjbd** [influxdata/influxdb#7520]
I'm using brew to install influxdb on my mac:
`$. brew install influxdb`

But getting error as follows:

> Warning: You are using OS X 10.12.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.
> go: This formula either does not compile or function as expected on OS X
> versions newer than El Capitan due to an upstream incompatibility.
> Error: An unsatisfied requirement failed this build.

**Comment by jwilder** [comment]
@rossmcdonald @jsternberg Any ideas?

**Comment by rossmcdonald** [comment]
Looks like this is an issue with the Go homebrew formula. @gunnaraasen Any ideas?

**Comment by gunnaraasen** [comment]
@masudjbd Can you try running the following commands?

```
xcode-select --install
brew update
brew install influxdb
```

If that doesn't work, can you provide the output of `brew doctor`?

**Comment by masudjbd** [comment]
I've tried and still having same result:

`$. xcode-select --install`
> xcode-select: note: install requested for command line developer tools

`$. brew update` 
> Already up-to-date.

`$. brew install influxdb`
> Warning: You are using OS X 10.12.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.
> go: This formula either does not compile or function as expected on OS X
> versions newer than El Capitan due to an upstream incompatibility.
> Error: An unsatisfied requirement failed this build.

**Comment by masudjbd** [comment]
Doctor's report:

`$. brew doctor`
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!
> 
> Warning: "config" scripts exist outside your system or Homebrew directories.
> `./configure` scripts often look for *-config scripts to determine if
> software packages are installed, and what additional flags to use when
> compiling and linking.
> 
> Having additional scripts in your path can confuse software installed via
> Homebrew if the config script overrides a system or Homebrew provided
> script of the same name. We found the following "config" scripts:
>     /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
>     /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
>     /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config
>     /opt/local/bin/ncurses6-config
>     /opt/local/bin/ncursesw6-config
>     /opt/local/bin/pcre-config
>     /opt/local/bin/pkg-config
> 
> Warning: Python is installed at /Library/Frameworks/Python.framework
> 
> Homebrew only supports building against the System-provided Python or a
> brewed Python. In particular, Pythons installed to /Library can interfere
> with other software installs.
> 
> Warning: You have MacPorts or Fink installed:
>   /opt/local/bin/port
> 
> This can cause trouble. You don't have to uninstall them, but you may want to
> temporarily move them out of the way, e.g.
> 
>   sudo mv /opt/local ~/macports
> 
> Warning: Unbrewed dylibs were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected dylibs:
>     /usr/local/lib/libformw.6.dylib
>     /usr/local/lib/libmenuw.6.dylib
>     /usr/local/lib/libncursesw.6.dylib
>     /usr/local/lib/libpanelw.6.dylib
>     /usr/local/lib/librtmp.dylib
> 
> Warning: Unbrewed header files were found in /usr/local/include.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected header files:
>     /usr/local/include/ncursesw/eti.h
>     /usr/local/include/ncursesw/form.h
>     /usr/local/include/ncursesw/menu.h
>     /usr/local/include/ncursesw/ncurses.h
>     /usr/local/include/ncursesw/ncurses_dll.h
>     /usr/local/include/ncursesw/panel.h
>     /usr/local/include/ncursesw/term.h
>     /usr/local/include/ncursesw/termcap.h
>     /usr/local/include/ncursesw/unctrl.h
>     /usr/local/include/node/android-ifaddrs.h
>     /usr/local/include/node/ares.h
>     /usr/local/include/node/ares_build.h
>     /usr/local/include/node/ares_rules.h
>     /usr/local/include/node/ares_version.h
>     /usr/local/include/node/libplatform/libplatform.h
>     /usr/local/include/node/nameser.h
>     /usr/local/include/node/node.h
>     /usr/local/include/node/node_buffer.h
>     /usr/local/include/node/node_object_wrap.h
>     /usr/local/include/node/node_version.h
>     /usr/local/include/node/openssl/aes.h
>     /usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
>     /usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
>     /usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
>     /usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
>     /usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
>     /usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
>     /usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
>     /usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
>     /usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
>     /usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
>     /usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
>     /usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
>     /usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
>     /usr/local/include/node/openssl/archs/linux32-s390x/opensslconf.h
>     /usr/local/include/node/openssl/archs/linux64-s390x/opensslconf.h
>     /usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
>     /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
>     /usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
>     /usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
>     /usr/local/include/node/openssl/asn1.h
>     /usr/local/include/node/openssl/asn1_mac.h
>     /usr/local/include/node/openssl/asn1t.h
>     /usr/local/include/node/openssl/bio.h
>     /usr/local/include/node/openssl/blowfish.h
>     /usr/local/include/node/openssl/bn.h
>     /usr/local/include/node/openssl/buffer.h
>     /usr/local/include/node/openssl/camellia.h
>     /usr/local/include/node/openssl/cast.h
>     /usr/local/include/node/openssl/cmac.h
>     /usr/local/include/node/openssl/cms.h
>     /usr/local/include/node/openssl/comp.h
>     /usr/local/include/node/openssl/conf.h
>     /usr/local/include/node/openssl/conf_api.h
>     /usr/local/include/node/openssl/crypto.h
>     /usr/local/include/node/openssl/des.h
>     /usr/local/include/node/openssl/des_old.h
>     /usr/local/include/node/openssl/dh.h
>     /usr/local/include/node/openssl/dsa.h
>     /usr/local/include/node/openssl/dso.h
>     /usr/local/include/node/openssl/dtls1.h
>     /usr/local/include/node/openssl/e_os2.h
>     /usr/local/include/node/openssl/ebcdic.h
>     /usr/local/include/node/openssl/ec.h
>     /usr/local/include/node/openssl/ecdh.h
>     /usr/local/include/node/openssl/ecdsa.h
>     /usr/local/include/node/openssl/engine.h
>     /usr/local/include/node/openssl/err.h
>     /usr/local/include/node/openssl/evp.h
>     /usr/local/include/node/openssl/hmac.h
>     /usr/local/include/node/openssl/idea.h
>     /usr/local/include/node/openssl/krb5_asn.h
>     /usr/local/include/node/openssl/kssl.h
>     /usr/local/include/node/openssl/lhash.h
>     /usr/local/include/node/openssl/md4.h
>     /usr/local/include/node/openssl/md5.h
>     /usr/local/include/node/openssl/mdc2.h
>     /usr/local/include/node/openssl/modes.h
>     /usr/local/include/node/openssl/obj_mac.h
>     /usr/local/include/node/openssl/objects.h
>     /usr/local/include/node/openssl/ocsp.h
>     /usr/local/include/node/openssl/opensslconf.h
>     /usr/local/include/node/openssl/opensslv.h
>     /usr/local/include/node/openssl/ossl_typ.h
>     /usr/local/include/node/openssl/pem.h
>     /usr/local/include/node/openssl/pem2.h
>     /usr/local/include/node/openssl/pkcs12.h
>     /usr/local/include/node/openssl/pkcs7.h
>     /usr/local/include/node/openssl/pqueue.h
>     /usr/local/include/node/openssl/rand.h
>     /usr/local/include/node/openssl/rc2.h
>     /usr/local/include/node/openssl/rc4.h
>     /usr/local/include/node/openssl/ripemd.h
>     /usr/local/include/node/openssl/rsa.h
>     /usr/local/include/node/openssl/safestack.h
>     /usr/local/include/node/openssl/seed.h
>     /usr/local/include/node/openssl/sha.h
>     /usr/local/include/node/openssl/srp.h
>     /usr/local/include/node/openssl/srtp.h
>     /usr/local/include/node/openssl/ssl.h
>     /usr/local/include/node/openssl/ssl2.h
>     /usr/local/include/node/openssl/ssl23.h
>     /usr/local/include/node/openssl/ssl3.h
>     /usr/local/include/node/openssl/stack.h
>     /usr/local/include/node/openssl/symhacks.h
>     /usr/local/include/node/openssl/tls1.h
>     /usr/local/include/node/openssl/ts.h
>     /usr/local/include/node/openssl/txt_db.h
>     /usr/local/include/node/openssl/ui.h
>     /usr/local/include/node/openssl/ui_compat.h
>     /usr/local/include/node/openssl/whrlpool.h
>     /usr/local/include/node/openssl/x509.h
>     /usr/local/include/node/openssl/x509_vfy.h
>     /usr/local/include/node/openssl/x509v3.h
>     /usr/local/include/node/pthread-barrier.h
>     /usr/local/include/node/pthread-fixes.h
>     /usr/local/include/node/stdint-msvc2008.h
>     /usr/local/include/node/tree.h
>     /usr/local/include/node/uv-aix.h
>     /usr/local/include/node/uv-bsd.h
>     /usr/local/include/node/uv-darwin.h
>     /usr/local/include/node/uv-errno.h
>     /usr/local/include/node/uv-linux.h
>     /usr/local/include/node/uv-sunos.h
>     /usr/local/include/node/uv-threadpool.h
>     /usr/local/include/node/uv-unix.h
>     /usr/local/include/node/uv-version.h
>     /usr/local/include/node/uv-win.h
>     /usr/local/include/node/uv.h
>     /usr/local/include/node/v8-debug.h
>     /usr/local/include/node/v8-experimental.h
>     /usr/local/include/node/v8-platform.h
>     /usr/local/include/node/v8-profiler.h
>     /usr/local/include/node/v8-testing.h
>     /usr/local/include/node/v8-util.h
>     /usr/local/include/node/v8-version.h
>     /usr/local/include/node/v8.h
>     /usr/local/include/node/v8config.h
>     /usr/local/include/node/zconf.h
>     /usr/local/include/node/zlib.h
> 
> Warning: Unbrewed static libraries were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected static libraries:
>     /usr/local/lib/libformw.a
>     /usr/local/lib/libmenuw.a
>     /usr/local/lib/libncursesw.a
>     /usr/local/lib/libpanelw.a
> 
> Warning: You have unlinked kegs in your Cellar
> Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
> those kegs to fail to run properly once built. Run `brew link` on these:
>     atlassian-plugin-sdk
>     docker
>     node
>     python3
>     tomcat
> 
> Warning: You are using OS X 10.12.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.
> 
> Warning: Homebrew's sbin was not found in your PATH but you have installed
> formulae that put executables in /usr/local/sbin.
> Consider setting the PATH for example like so
>   echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
> 
> Warning: You have a non-Homebrew 'pkg-config' in your PATH:
>   /opt/local/bin/pkg-config
> 
> `./configure` may have problems finding brew-installed packages using
> this other pkg-config.
> 
> Warning: Some installed formula are missing dependencies.
> You should `brew install` the missing dependencies:
>   brew install python
> 
> Run `brew missing` for more details.

**Comment by gunnaraasen** [comment]
Can you also try running `brew upgrade`, then `brew install influxdb`? If that doesn't work, I recommend [opening an issue on the Homebrew repo](https://github.com/Homebrew/homebrew-core/issues/new) since it seems like this may be a brew issue.

**Comment by masudjbd** [comment]
Upgrade report:

`$.brew upgrade`

> Warning: You are using OS X 10.12.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.
> ==> Upgrading 25 outdated packages, with result:
> docker 1.12.0, elasticsearch 2.3.5, flex 2.6.1, fontconfig 2.11.1_4, freetype 2.6.5, gd 2.2.3, gettext 0.19.8.1, git 2.9.2, gnutls 3.4.14, go 1.6.3, gradle 2.14.1, libtasn1 4.9, libtiff 4.0.6_2, little-cms2 2.8, mercurial 3.9_1, homebrew/binary/ngrok2 2.1.3, node 6.3.1, sane-backends 1.0.25, sbt 0.13.12, pivotal/tap/springboot 1.4.0.RELEASE, telegraf 0.13.1, tomcat 8.5.4, tor 0.2.8.6, wget 1.18, wine 1.8.3
> go: This formula either does not compile or function as expected on OS X
> versions newer than El Capitan due to an upstream incompatibility.
> Error: An unsatisfied requirement failed this build.

`$. brew install influxdb`
> Warning: You are using OS X 10.12.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.
> go: This formula either does not compile or function as expected on OS X
> versions newer than El Capitan due to an upstream incompatibility.
> Error: An unsatisfied requirement failed this build.

**Comment by masudjbd** [comment]
Thanks for suggestion , I was able to install influxdb.
https://github.com/Homebrew/homebrew-core/issues/6272#issuecomment-256296060

👍 :)
