### ISSUE TITLE
[Feature Request] -  Provide Time picker next to the query editor & page viewer

### ISSUE THREAD

**Issue by jayannah** [influxdata/influxdb#7528]
Some time people just type the query without specifying time range which hangs the browser and see high memory & CPU usage too.

Hence, request for the following feature
1.  Provide Time range picker (by default set to 15min (or few min) and people change can change it whatever the time they want to query) 
2. When the result returned from the query is lots of rows, those should be displayed in page viewer (default 20 rows per page). People should be able to select the designated number of rows per page.

Influx version 1.0

**Comment by jayannah** [comment]
May I know why this issue is closed? Is this fixed in 1.1?

**Comment by jwilder** [comment]
The admin interface is deprecated as of 1.1.  See the [release notes](https://github.com/influxdata/influxdb/blob/1.1/CHANGELOG.md#deprecations)
