### ISSUE TITLE
InfluxDB v1.0.2: unexpected fault address 0xa200

### ISSUE THREAD

**Issue by Apollon77** [influxdata/influxdb#7537]
Hey,

I use InfluxDB 1.0.2 on Ubiuntu Xenial with 4.8.4 Kernel and got now the following twice with difference:

see attachement
[influx-fatal.txt](https://github.com/influxdata/influxdb/files/558579/influx-fatal.txt)

You can also see the restart in there, but using the process id you can see all error output from the first process too ... Restart was successfull  and everything worked afterwards

**Comment by e-dard** [comment]
Should be fixed in 1.2
