### ISSUE TITLE
InfluxDB should better optimize memory usage of large queries

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#7539]
### Feature Request

__Proposal:__ [Description of the feature]
InfluxDB should better optimize large queries to use less memory.

__Current behavior:__ [What currently happens]
Version: influxdb-1.0.2
Currently running a search over a 7 day time span will use much more memory than running the same search 7 times over 1 day spans.
This behavior can cause InfluxDB to OOM itself.

For example:
![image](https://cloud.githubusercontent.com/assets/1826947/19822986/458ba962-9d34-11e6-968b-2e5d9bfc2f5f.png)
This is a graph of the _internal.runtime.HeapAlloc metric. The gaps are where I restarted InfluxDB to make sure it had a clean start.
The first bump at 17:14:00 is when I ran the following:

```
for i in {0..6}; do
  influx -database telegraf -execute "SELECT count(active) AS active FROM telegraf.autogen.postgresql_activity WHERE host = 'fll2gdbs10stg' AND time > now() - $((7-i))d AND time < now() - $((6-i))d AND active = true GROUP BY time(5m) fill(0)"
done
```

The second bump at 17:16:45 is when I ran:
```
influx -database telegraf -execute "SELECT count(active) AS active FROM telegraf.autogen.postgresql_activity WHERE host = 'fll2gdbs10stg' AND time > now() - 7d AND active = true GROUP BY time(5m) fill(0)"
```

Both queries will return the same data, but the first query uses far less memory.
Also by splitting the executions up into multiple queries, the memory usage plateaus, no matter how far back you go. However with the one big query, memory usage increases the larger the time range.

__Desired behavior:__ [What you would like to happen]
InfluxDB should better utilize memory so it doesn't OOM itself.

__Use case:__ [Why is this important (helps with prioritizing requests)]
Being able to run large queries without triggering OOM, and without requiring the user to have to manually break their query up provides a much better experience.

**Comment by jwilder** [comment]
@phemmer Would you be able to test with the current nightlies by chance?  There are many changes that reduce memory usage for queries and writes.

**Comment by phemmer** [comment]
@jwilder where are the nightlies kept these days? I used to be able to find them on the main download page (https://www.influxdata.com/downloads/), but they are no longer there.

**Comment by rossmcdonald** [comment]
@phemmer Sorry, we're in the process of getting the nightlies back on the Downloads page. Here are the links:

https://dl.influxdata.com/influxdb/nightlies/influxdb_nightly_amd64.deb
https://dl.influxdata.com/influxdb/nightlies/influxdb-nightly.x86_64.rpm
https://dl.influxdata.com/influxdb/nightlies/influxdb-nightly_linux_amd64.tar.gz

**Comment by phemmer** [comment]
Ok, tried with the nighly, and wow. The difference is insane. The heap usage barely even moves. And it completes over 5 times faster.

Going ahead and closing this since it seems to be resolved.

Thanks

**Comment by phemmer** [comment]
![image](https://cloud.githubusercontent.com/assets/1826947/19826522/cbf1bb7e-9d5a-11e6-9b5b-adad6d9c1e38.png)

Can you tell when the new version was installed? :-)
