### ISSUE TITLE
InfluxDB gives incorrect results when using epoch times.

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#7540]
### Bug report

**System info:** [Include InfluxDB version, operating system name, and other relevant details]
influxdb-1.1.0~n201610280800-0.x86_64
CentOS/7

**Steps to reproduce:**
1. `select count("connection_time") from postgresql_activity where host='iad1gdbs01' and time > '2016-10-28 00:08:21' and time < '2016-10-28 00:14:08' group by time(1m)`
2. `select count("connection_time") from postgresql_activity where host='iad1gdbs01' and time > 1477699701s AND time < 1477700048s group by time(1m)`

**Expected behavior:** [What you expected to happen]
Receive the same results for both queries.

**Actual behavior:** [What actually happened]
Received different results for both queries.

**Additional info:** [Include gist of relevant config, logs, etc.]
This is a regression as the issue is not present in InfluxDB 1.0.2

`1477699701` == `2016-10-28 00:08:21`
`1477700048` == `2016-10-28 00:14:08`

```
> select count("connection_time") from postgresql_activity where host='iad1gdbs01' and time > '2016-10-28 00:08:21' and time < '2016-10-28 00:14:08' group by time(1m)
name: postgresql_activity
time            count
----            -----
2016-10-28T00:08:00Z    163
2016-10-28T00:09:00Z    161
2016-10-28T00:10:00Z    160
2016-10-28T00:11:00Z    160
2016-10-28T00:12:00Z    157
2016-10-28T00:13:00Z    160
2016-10-28T00:14:00Z    0

> select count("connection_time") from postgresql_activity where host='iad1gdbs01' and time > 1477699701s AND time < 1477700048s group by time(1m)
name: postgresql_activity
time            count
----            -----
2016-10-29T00:08:00Z    166
2016-10-29T00:09:00Z    166
2016-10-29T00:10:00Z    162
2016-10-29T00:11:00Z    0
2016-10-29T00:12:00Z    325
2016-10-29T00:13:00Z    162
2016-10-29T00:14:00Z    0
```

`1477699860` == `2016-10-28 00:11:00`
`1477699920` == `2016-10-28 00:12:00`

```
> select active from postgresql_activity where host='iad1gdbs01' and time > 1477699860s and time < 1477699920s
(no results)

> select active from postgresql_activity where host='iad1gdbs01' and time > '2016-10-28 00:11:00' and time < '2016-10-28 00:12:00'
name: postgresql_activity
time                active
----                ------
2016-10-28T00:11:51.694Z    false
2016-10-28T00:11:51.695Z    false
2016-10-28T00:11:51.705Z    false
2016-10-28T00:11:51.705Z    false
2016-10-28T00:11:51.72Z     false
2016-10-28T00:11:51.722Z    false
2016-10-28T00:11:51.722Z    false
2016-10-28T00:11:51.723Z    false
2016-10-28T00:11:51.723Z    false
2016-10-28T00:11:51.723Z    false
2016-10-28T00:11:51.723Z    false
2016-10-28T00:11:51.723Z    false
2016-10-28T00:11:51.723Z    false
...
...
...
```

**Comment by jsternberg** [comment]
I'm not sure your unix times are correct. Quick code snippet: https://play.golang.org/p/9g5ZBTQwD0

This gives me `1477613301` for `2016-10-28T00:08:21Z`, but it looks like you tried `1477699701`. Can you double check your numbers to make sure I didn't mess up anything?

**Comment by phemmer** [comment]
Nope, you're right. I apparently made a typo during my initial conversion to epoch time, and then kept on using the bad value for all further calculations. Using the proper unix epoch time, I get the same value for both.

I am experiencing an issue with the nightly, but apparently misdiagnosed it. I'll reinvestigate and create a new issue once I identify the pattern.

**Comment by jsternberg** [comment]
Ok, thanks!
