### ISSUE TITLE
Stacked graph in chronograf?

### ISSUE THREAD

**Issue by ksalman** [influxdata/influxdb#7543]
I just installed chronograf alongside grafana to play with it and possibly replace grafana. But I cannot find a way to do a stacked graph in chronograf, unless I am missing something obvious. I can do something like 

```
SELECT iowait + system FROM glances.autogen."localhost.cpu" WHERE tmpltime()
```

but that is not really a stacked graph of the two metrics. Is there a more canonical way to do a stacked graph in chronograf, or is that maybe a future feature?

**Comment by jwilder** [comment]
Please log an issue in the [Chronograf](https://github.com/influxdata/chronograf) repo.
