### ISSUE TITLE
`influxd config` prints deceptive output

### ISSUE THREAD

**Issue by mattbasta** [influxdata/influxdb#7546]
### Bug report

**System info:**

```
InfluxDB v1.0.2 (git: master ff307047057b7797418998a4ed709b0c0f346324)
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial
```

running on an AWS m4.large

**Steps to reproduce:**
1. Install Influx on Ubuntu per [these instructions](https://docs.influxdata.com/influxdb/v1.0/introduction/installation/) for Ubuntu using `apt-get`. Using the CLI, add an admin user.
2. Add `INFLUXDB_CONFIG_PATH=/path/to/conf` to `/etc/environment` with a path to the `influxdb.generated.conf` file that's described. In this conf file, set `auth-enabled` to `true`.
3. Reboot everything for good measure.
4. At this point, you should be able to run `influxd config` and the output will show `auth-enabled = true`, as someone setting up Influx for the first time might expect.

**Expected behavior:** Authentication is enabled.

**Actual behavior:** Authentication is not enabled.

**Additional info:** 

If you now update the original conf file (`/etc/influxdb/influxdb.conf`) with `auth-enabled = true`, the output of `influxd config` does not change, but after rebooting the server, authentication will be enabled.

The documentation doesn't line up with what is happening:

> The `influxd config` command will print out a new TOML-formatted configuration with all the available configuration options set to their default values.

This is not true. Any configuration changes made in the config file referenced by the `INFLUXDB_CONFIG_PATH` will be reflected in the output of `influxd config`. Despite `influxd` using `INFLUXDB_CONFIG_PATH`'s config, `influxd` respects the values in `/etc/influxdb/influxdb.conf` instead.

I would expect one or both of the following two things to happen:
- `influxd config` does what the documentation says and outputs the default values for each config option.
- InfluxDB respects the configuration referenced by `INFLUXDB_CONFIG_PATH`.

**Comment by jwilder** [comment]
For packaged installs, you should not need to generate a config file.  

I'm not able to reproduce what you are seeing with `INFLUXDB_CONFIG_PATH`.  If you run:

```
INFLUXDB_CONFIG_PATH=/path/to/influxdb.generated.conf influxd config
```

does is print out the correct value for `auth-enabled` that you have set in that file?

**Comment by mattbasta** [comment]
Oh, I know what's going on. This is my mistake. Perhaps this will help someone learn a lesson the easy way. 

The packaged version gets installed with the `-config` parameter in the command that starts the service. It never used the config referenced by the environment variable. My mistake was assuming `influxd config` would output what the service believes to be the config. I wasn't passing the `-config` parameter to `influxd config`, and so it was using the config from the environment variable.

Sorry about that!
