### ISSUE TITLE
The apt-get repos for ubuntu xenial arm64 has problem

### ISSUE THREAD

**Issue by scriptfans** [influxdata/influxdb#7547]
Why I can't install the latest version of the influxdb on my arm64 ubuntu 16.04 system use `apt-get install influxdb`? I noticed the index file is empty:

https://repos.influxdata.com/ubuntu/dists/xenial/stable/binary-arm64/Packages

**Comment by scriptfans** [comment]
https://github.com/influxdata/influxdb/issues/6773

@rossmcdonald

**Comment by rossmcdonald** [comment]
@scriptfans Sorry for the delay! This should now be resolved.
