### ISSUE TITLE
SHOW TAG VALUES seems to ignore ON in the CLI

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#7552]
### Bug report

Ubuntu, nightly (updated October 31, 2016)

__Steps to reproduce:__

**1.** Create two databases and write data to them with different tag values of the `tagtag` tag key

```
> create database pluto
> use pluto
Using database pluto
> insert mymeas,tagtag=space value=1

> create database dog
> use dog
Using database dog
> insert meas,tagtag=house value=1
```

**2.** Query the `dog` database for tag values of the `tagtag` tag key without `ON`, with `ON pluto`, and then query the `pluto` database for tag values of the `tagtag` tag key.

```
> show tag values with key=tagtag
name: meas
key        value
---        -----
tagtag     house

> show tag values on pluto with key=tagtag
name: meas
key      value
---      -----
tagtag   house

> use pluto
Using database pluto

> show tag values with key=tagtag
name: mymeas
key      value
---      -----
tagtag   space
```

__Expected behavior:__

I would have expected to get the same results for `SHOW TAG VALUES ON pluto WITH KEY=tagtag` and when I used `pluto` and ran `SHOW TAG VALUES`.

__Actual behavior:__

When I use the `dog` database and run `SHOW TAG VALUES ON pluto WITH KEY=tagtag`, I still see the value of `tagtag` that's specific to the `dog` database.

**Comment by jwilder** [comment]
@jsternberg

**Comment by jsternberg** [comment]
Looks like I implemented this in the parser and forgot to actually implement it in the command itself. I'll have a PR up soon for this.
