### ISSUE TITLE
% operator

### ISSUE THREAD

**Issue by kfox1111** [influxdata/influxdb#7553]
Proposal: Would like the % operator

Current behavior: doesn't exist

Desired behavior: % works

Use case:
I have a data set that has a state value of 0: off, 1: heat, 2: cool.
I'd like to convert this value to be cool < off < heat to make the singlestat grafana plugin able to display it nicely. the % operator could be used to reformat the data nicely in this case.

**Comment by jwilder** [comment]
Can you provide a sample syntax of how this would work?  Is the `%` operator the same as a case statement in SQL?
