### ISSUE TITLE
Influxdb client didn't read the whole address of influxdb service. It reads only the first field in the url

### ISSUE THREAD

**Issue by medhedifour** [influxdata/influxdb#7555]
I manage a kubernetes cluster. I want to send queries from go code.
I have created a replication controller and a service of Influxdb.
The url of service is : http://@IP/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb:8086
I made a client like this code :
 // Make client
    c, err := client.NewHTTPClient(client.HTTPConfig{
        Addr: "http://@IP/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb:8086",
        Username: username,
        Password: password,
    })
But this client take only the first part of the url "http://@IP/" .
Can someone help me to solve this problem.

@jwilder 
@otoolep

**Comment by jwilder** [comment]
@medhedifour The address is just the scheme, host and port.  The v2 client does not support what you are trying to do.

**Comment by medhedifour** [comment]
@jwilder 
So How can I make this possible ? 
Are there any solution ?

**Comment by anderskvist** [comment]
I also have a different endpoint for my InfluxDB, so I used way too long time tonight to find out why my data wasn't written...

This temporary fixed it for me:
```
diff --git a/client/v2/client.go b/client/v2/client.go
index 2870cf8..7ff4929 100644
--- a/client/v2/client.go
+++ b/client/v2/client.go
@@ -367,7 +367,7 @@ func (c *client) Write(bp BatchPoints) error {
        }
 
        u := c.url
-       u.Path = "write"
+       u.Path = "/influxdb/write"
        req, err := http.NewRequest("POST", u.String(), &b)
        if err != nil {
                return err
```

Maybe it should just be changed to appending write to path instead of overwriting it?

**Comment by StianOvrevage** [comment]
Absolutely agree with @anderskvist . We are not able to use InfluxDB, and all the other stuff that depends on InfluxDB, because of this.

**Comment by ragnarlonn** [comment]
@jwilder Would something bad happen if instead of doing `u.Path = "write"`, the client would just append "write" (or "/write") to u.Path, keeping whatever path the user supplied as a prefix?

From what I can see (https://github.com/influxdata/influxdb/blob/master/client/v2/client.go#L88) the path given by the user when calling NewHTTPClient() should be stored in u.Path before it is overwritten on line 370, so the information is there. But maybe it can generate bad side effects somewhere, if paths are allowed in the URL?

**Comment by StianOvrevage** [comment]
Any news on this one? The fix is easy. The decision is hard.
