### ISSUE TITLE
Can't connect to influxdb with http client with golang

### ISSUE THREAD

**Issue by medhedifour** [influxdata/influxdb#7557]
I created a client of Influxdb using this code : 
c, err := client.NewHTTPClient(client.HTTPConfig{
    Addr:"http://IP:8086",
    Username: username,
    Password: password,
     })

Always getting the error below when connection to Influxdb IP address using Http client with golang language:
 
Post http://@IP:8086/query?db=square_holes&q=CREATE+DATABASE+square_holes: dial tcp  @IP:8086: getsockopt: connection timed out

@jwilder
@otoolep
@beckettsean

**Comment by jwilder** [comment]
@medhedifour We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.

I would suggest taking a look at the example code, documentation and tests in the client repo: https://github.com/influxdata/influxdb/tree/master/client

**Comment by medhedifour** [comment]
@jwilder
This problem is due to a bug generated in influxdb.
I have seen the example code in https://github.com/influxdata/influxdb/tree/master/client.
So this question is not a general question, and I think that we can connect to influxdb only in localhost machine and in my case I have a server with public IP that Influxdb is accessible via IP_Address:Port.
I tried to connect to my server but it generates problems.

**Comment by beckettsean** [comment]
@medhedifour How can you be certain that there is a bug in InfluxDB? I see a generic networking error that may have bubbled up from the OS, and most of the interesting syntax has been obfuscated for privacy.

Can you show that a connection via `curl` works but the Golang client doesn't, for instance?
