### ISSUE TITLE
Feature-Request: Allow type casts from boolean to int/float (0/1)

### ISSUE THREAD

**Issue by Apollon77** [influxdata/influxdb#7562]
__Proposal:__
Allow type casts from boolean fields to int/float and convert true to 1 and false to 0. At leas in queries.
If it really make sense to also support that automatically on "insert type conflicts" (e.g. if field is boolean but value is 0/1 then store as boolean instead of returning a write error and the other way around) may be a bigger question :-)

__Current behavior:__
Type casts are only done currently  between int and float fields.

Many systems do not really distinguish between int and boolean and 0/1 is often used in a boolean meaning. If you do not take care it can end up in mixtures between 0/1 and false/true, maybe also in the same measurement. When mixed in same measurement it comes to weired effects when querying ... when mixing shards with different types only some values are shown and else "empty values" which is very confusing (I needed 1h to come to the clue that this happened) ...

**Comment by jwilder** [comment]
Moved to #5930 which consolidates many query language feature requests.
