### ISSUE TITLE
upgrading influxdb from 1.0.0 to 1.0.2

### ISSUE THREAD

**Issue by nirpodo** [influxdata/influxdb#7566]
looking for documentation on how to upgrade influxdb (and kapacitor) from v1.0.0 to v1.0.2 on centos7
can anyone share his experience with the new versions, any problems?

**Comment by jsternberg** [comment]
Hello @nirpodo, support questions should go to the [mailing list](https://groups.google.com/forum/#!forum/influxdb) instead of the issue tracker. Thanks!
