### ISSUE TITLE
[Feature Request] Show the top N grouped series and ordered by its value

### ISSUE THREAD

**Issue by sbengo** [influxdata/influxdb#7567]
### Feature Request

__Proposal:__ 

Hi, i'm trying to figure out how to show the first N top series based on its value.

As an example: I have 10 series with the tags: `tagA` and it is having M possible values. I want to calculate the maximum on a period and grouping by the tagA, so M diferent series must be shown.

After that, I want to show only the N first result series based on its value.
 
In Graphite, you can do it with the statement: 

```
highestAverage(seriesList, n)
Takes one metric or a wildcard seriesList followed by an integer N. Out of all metrics passed, draws only the top N metrics with the highest average value for the time period specified.

Example:

&target=highestAverage(server*.instance*.threads.busy,5)
```

**Comment by jwilder** [comment]
I believe this would be addressed by the `having` syntax support.  #5266
