### ISSUE TITLE
Influx 1.0.2 fill(0) behavior is different than 0.9.6

### ISSUE THREAD

**Issue by earthnut** [influxdata/influxdb#7572]
### Bug report  
We use  Kapacitor to build health check alert.
Each host will send out heartbeat every 10s. The alert script will monitor a time window. And any host has no point in a window, the alert will be raised for that host.
So base on that, the alert query is something like
 
     `SELECT sum(\"value\") as value FROM \"collectd\".\"default\".xxxxxxxxxx where time >= 'xxxxxxx' AND time < 'xxxxxxxx' GROUP BY host fill(0)`

__Expected behavior:__ [What you expected to happen]
in 0.9.6 the query result is :
`{
    "results": [
        {
            "series": [
                {
                    "name": "xxxxxxx",
                    "tags": {
                        "host": "host1"
                    },
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "timexxxxxxxxxxxxx",
                            24
                        ]
                    ]
                },
                {
                    "name": "xxxxxxx",
                    "tags": {
                        "host": "host2"
                    },
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "timexxxxxxxxxxx",
                            0
                        ]
                    ]
                }
            ]
        }
    ]
}`

__Actual behavior:__ [What actually happened]

but in 1.0.2:
`{
    "results": [
        {
            "series": [
                {
                    "name": "xx",
                    "tags": {
                        "host": "host1"
                    },
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "timexxxxxxxx",
                            24
                        ]
                    ]
                }
            ]
        }
    ]
}`

As you can see, "host2" is not in result and alert will not be triggered for "host2".

**Comment by jwilder** [comment]
@earthnut Do you have a way that we could reproduce this?

**Comment by jwilder** [comment]
@jsternberg Any ideas?

**Comment by jsternberg** [comment]
@jwilder this looks like it's expected and changed as part of the new query engine in 0.11. It will not fill in intervals where there is not at least one series in that interval, otherwise, we would have a lot of difficulty with high cardinality data returning null values for way beyond them being gone.

We should possibly think of opening a discovery issue for this though as it's a common point of confusion. During all of the times I've explained it, I haven't heard a reasonable solution that works, but it's definitely something worth exploring.

**Comment by earthnut** [comment]
Is there any workaround so far?
