### ISSUE TITLE
Influxdb going OOM due to 100 batch queries of kapacitor every 1 min

### ISSUE THREAD

**Issue by ruchi15** [influxdata/influxdb#7574]
Hi,
we are running a telegraf which is pushing data to Influxdb machine(Ssd.8c.32g.105G) from kafka on which 1000 docker containers of telegraf publishing data. All tools are on the different machines. Now we are hitting influxdb with 100 batch queries of kapacitor every 1 min. And we observed that after 200-300 queries, Influxdb process was aggressively occupying the memory and It was going OOM. After that systemd was killing the process and restarting again. fyi telegraf was pushing data in influxdb for 4-5 days continuously in every 10s interval.

we already read about the series cardinality issue but we don't have enough data by which series cardinality could corss 10 million range or greater. So why influxdb taking so much memory or what could be done in this case.

All responses would be appreciated. Grafana Screenshots are attached here.

![screenshot from 2016-11-03 15 44 27](https://cloud.githubusercontent.com/assets/7676413/19962311/1c98bd6c-a1dd-11e6-87ee-2a1f0680c20d.png)
![screenshot from 2016-11-03 15 44 01](https://cloud.githubusercontent.com/assets/7676413/19962312/1c9e2a72-a1dd-11e6-9ca1-3944ef19957b.png)

**Comment by jwilder** [comment]
We need more information in order to diagnose what is going on.  Can you update the issue description with the instructions listed in our [issue template](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md)?

There are also many memory improvements in the `1.1rc1` release.  Can you test w/ that to see if there is an improvement?

**Comment by ruchi15** [comment]
Sure jwilder, I am providing the version of influxdb we are using and OS details. we are using influxdb 1.0.2 and centos7 machine with configuration (Ssd.8c.32g.105G). Telegraf (- version 1.0.1) is pushing data to influxdb machine and we are hitting influxdb with 100 batch queries of kapacitor (1.0.2) every 1 min through http api. Influxdb process is occupying memory very aggressively and after 100 queries, It is going OOM.

**Comment by jwilder** [comment]
@ruchi15 Did you test with 1.1rc1?

When memory usage is growing, can you run the following:
```
curl -o block.txt "http://localhost:8086/debug/pprof/block?debug=1" 
curl -o goroutine.txt "http://localhost:8086/debug/pprof/goroutine?debug=1" 
curl -o heap.txt "http://localhost:8086/debug/pprof/heap?debug=1" 
curl -o vars.txt "http://localhost:8086/debug/vars" 
iostat -xd 1 30 > iostat.txt
influx -execute "show shards" > shards.txt
influx -execute "show stats" > stats.txt
influx -execute "show diagnostics" > diagnostics.txt
```
