### ISSUE TITLE
influx client non-interactive mode doesn't accept meta commands anymore

### ISSUE THREAD

**Issue by ndegory** [influxdata/influxdb#7575]
### Bug report

__System info:__

influxdb 1.1.0-rc1 in a Docker container based on Alpine linux 3.4

__Steps to reproduce:__

1. Build a Docker image in which influxd is launched in background and the influx CLI is used to execute a query (or import a file)
2. Design a docker-compose file containing an influxdb service and other services depending on the influxdb service
3. Start the influxdb service (docker-compose run influxdb)
4. Stop it (docker-compose down)
5. Start an other service depending on influxdb (docker compose run sut)

__Expected behavior:__

The CLI commands are executed on the influxdb server, and queries are seen in the influxdb container logs.

__Actual behavior:__

The expected behavior is observed on step 3.
The expected behavior is not observed on step 5, influxdb container logs complain about an empty `q` parameter.

__Additional info:__

Until influxdb 1.0.2 this was working as expected, the regression is observed since commit [2f5f9957828c09e73bbc725729f7da9cd66633be](https://github.com/influxdata/influxdb/commit).

The Docker image and the docker-compose.test.yml files are implemented in the [appcelerator/influxdb](https://github.com/appcelerator/docker-influxdb/tree/influxdb-1.1) repo, branch influxdb-1.1. A patch is included to workaround the issue.

**Comment by jwilder** [comment]
@jsternberg Maybe related to #7440

**Comment by jsternberg** [comment]
I think it's definitely #7440. @ndegory when you are using the `influx` CLI this way, you should specify those command line options using command line flags if you can. I don't think this is something we are going to be able to conceivably fix at the moment without breaking multi-line queries. Would that work for you?

**Comment by ndegory** [comment]
@jsternberg I am using those options, the issue is that it is ignored where there's no TTY (which is the case with Docker services).

command | TTY | no TTY
------------- | ------ | ----------
influx -execute "query"  | the query is sent to the server | the query is ignored by the client, a call is done to the server with an empty query, which obviously fails
influx -import -path /filename | the file is read and executed on the server | the file is ignored, and an empty query is sent to the server

The patch in #7576 will check when there's no TTY if stdin is empty (which anyway leads to an error on the server), and then try to use the meta commands as is the case when there's a TTY. This fix the regression, and I don't think it breaks any other cases.

**Comment by jsternberg** [comment]
Ah, I understand it. So basically the TTY code accidentally intercepts the other use cases? I don't think your PR is the correct way to fix it, but I think I understand the issue now and I'll be able to fix it. Thanks.
