### ISSUE TITLE
OFFSET without LIMIT returns odd results

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#7577]
### Bug report

Ubuntu, nightly

__Steps to reproduce:__

**1.** Write some data
```
> create database mydb
> use mydb
Using database mydb
> insert mymeas,color=yellow value=2
> insert mymeas,color=yellow value=3
> insert mymeas,color=yellow value=4
> insert mymeas,color=yellow value=5
> SELECT * FROM mymeas
name: mymeas
time				color	value
----				-----	-----
2016-11-02T23:27:55.659009728Z	yellow	2
2016-11-02T23:27:57.532365177Z	yellow	3
2016-11-02T23:27:59.352763724Z	yellow	4
2016-11-02T23:28:01.064617644Z	yellow	5
```
**2.** Run an `OFFSET` query without `LIMIT`
```
> SELECT * FROM mymeas OFFSET 1
name: mymeas
time				color	value
----				-----	-----
2016-11-02T23:27:57.532365177Z	yellow	3
```
**3.**  Run an `OFFSET` query with `LIMIT`
```
> SELECT * FROM mymeas LIMIT 2 OFFSET 1
name: mymeas
time				color	value
----				-----	-----
2016-11-02T23:27:57.532365177Z	yellow	3
2016-11-02T23:27:59.352763724Z	yellow	4
```

__Expected behavior:__ 

I'd expect the query in step 2 to return an error about needing `LIMIT` or maybe the output below:
```
name: mymeas
time				color	value
----				-----	-----
2016-11-02T23:27:57.532365177Z	yellow	3
2016-11-02T23:27:59.352763724Z	yellow	4
2016-11-02T23:28:01.064617644Z	yellow	5
```

__Actual behavior:__ [What actually happened]

I can't really explain the results in step 2.

**Comment by devinus** [comment]
This is happening on macOS 10.12.2 and Influx v1.1.1.

**Comment by rbetts** [comment]
We should reproduce this on 1.5.x

**Comment by jsternberg** [comment]
This doesn't appear to happen anymore. I wrote three points to the database of the latest release and used `OFFSET 1` without a limit and got the last two points.

**Comment by roman-v1** [comment]
Happens for me on 1.5.1.
