### ISSUE TITLE
SOFFSET without SLIMIT returns odd results

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#7578]
### Bug report

Ubuntu, 1.1 nightly

__Steps to reproduce:__

**1.** Write some data
```
> create database mydb
> use mydb
Using database mydb
> insert mymeas,color=yellow value=2
> insert mymeas,color=yellow value=3
> insert mymeas,color=yellow value=4
> insert mymeas,color=yellow value=5
> insert mymeas,color=blue value=800
> insert mymeas,color=blue value=900
> SELECT * FROM mymeas
name: mymeas
time				color	value
----				-----	-----
2016-11-02T23:27:55.659009728Z	yellow	2
2016-11-02T23:27:57.532365177Z	yellow	3
2016-11-02T23:27:59.352763724Z	yellow	4
2016-11-02T23:28:01.064617644Z	yellow	5
2016-11-02T23:29:08.953855972Z	blue	800
2016-11-02T23:29:11.427777943Z	blue	900
```

**2.**  Run an `SOFFSET` query without `SLIMIT`
```
> SELECT * FROM mymeas SOFFSET 1
>
```

**3.**  Run an `SOFFSET` query with `SLIMIT`
```
> SELECT * FROM mymeas SLIMIT 1 SOFFSET 1
>
```
**4.** Run an `SOFFSET` query with `SLIMIT` and `GROUP BY *`
```
> SELECT * FROM mymeas GROUP BY * SLIMIT 1 SOFFSET 1
name: mymeas
tags: color=yellow
time				value
----				-----
2016-11-02T23:27:55.659009728Z	2
2016-11-02T23:27:57.532365177Z	3
2016-11-02T23:27:59.352763724Z	4
2016-11-02T23:28:01.064617644Z	5
```

__Expected behavior:__

I'm not sure what I'd expect the query in step 2 to return; in a bare `SELECT * FROM measurement` query InfluxDB returns all series so how would it paginate through series if it returns all of them by default? I might expect to see an error about requiring an `SLIMIT` clause.

I'd expect the query in step 3 to return what I get in step 4.

__Actual behavior:__ [What actually happened]

 The query in step 2 returns nothing. The query in step 3 also returns nothing - I'm guessing this has something to do with https://github.com/influxdata/influxdb/issues/7571.

**Comment by rbetts** [comment]
Let's try to reproduce this against 1.5.x.

**Comment by jsternberg** [comment]
It looks like this still happens. For `SLIMIT` and `SOFFSET` you need some form of grouping, but `SOFFSET` without `SLIMIT` seems to return nothing for whatever reason.
