### ISSUE TITLE
Use proper password type field for http web client password

### ISSUE THREAD

**Issue by andyfeller** [influxdata/influxdb#7583]
The password field of the InfluxDB web client isn't treated like a password-type input field, which allows browsers to remember values entered as well as not obscuring values typed in said field.  This is a pretty big security issue.
![screen shot 2016-11-04 at 2 48 59 pm](https://cloud.githubusercontent.com/assets/2089743/20018503/4ef80378-a29e-11e6-964a-fa3470225b12.png)

**Comment by toddboom** [comment]
@andyfeller what version of InfluxDB are you using? this should have been fixed in #7286 and made it into a release quite some time ago.

**Comment by andyfeller** [comment]
Confirming this doesn't appear to be the case on both the Influx Enterprise data v1.0.0-c1.0.0 package and InfluxDB OSS v1.0.2

**Comment by andyfeller** [comment]
It appears this is part of the 1.1.0 release that hasn't been cut yet based upon the [change log](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md).  So totally worth closing this!  Thanks
