### ISSUE TITLE
Database droplist overruns viewport

### ISSUE THREAD

**Issue by kmuthupa** [influxdata/influxdb#7585]
### Bug report

__System info:__ > 0.13

__Steps to reproduce:__

1. The list of databases needs to be quite long for this to be observed.

__Expected behavior:__ Be able to pick a DB that's at very end of the list by scrolling through the list. 

__Actual behavior:__ Unable to pick a DB since a bunch of them are being cut off as a result of the overrun

__Additional info:__

*Please note, the quickest way to fix a bug is to open a Pull Request.*

![influx_ui_error](https://cloud.githubusercontent.com/assets/308052/20020436/41d35282-a29f-11e6-9dff-f5cf6912ec53.png)

**Comment by kmuthupa** [comment]
Was this fixed @jwilder?

**Comment by jwilder** [comment]
@kmuthupa No.  The admin interface is deprecated as 1.1 (See [changelog](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#deprecations)) so this will not be fixed.

**Comment by kmuthupa** [comment]
ah ok.
