### ISSUE TITLE
Feature Request - Support time in WHERE clause for SHOW TAG VALUES

### ISSUE THREAD

**Issue by mvadu** [influxdata/influxdb#7588]
As part of #4385 functionality was added to block time part in WHERE clause in  SHOW TAG VALUES queries. e.g. `SHOW TAG VALUES FROM anomalies WITH KEY = "ServerName" where time > 1459520932s and time < 1459520932s + 6h`

__Proposal:__ [Support time in WHERE clause for SHOW TAG VALUES]

__Current behavior:__ [Server returned error: `SHOW TAG VALUES doesn't support time in WHERE clause`]

__Desired behavior:__ [Return values for the given tag that appear in the time window given]

__Use case:__ When you have very large data sets you can have hundreds of tag values. It becomes tedious task to display / select a specific tag values in visualization layer (grafana in my case). Grafana already supports refreshing template variables when time window changes.  If Influx supports time window, the dropdowns for the template variables can be assured to have a data point in the selected time window. It helps data analysis of large data sets even without involving grafana.

**Comment by jwilder** [comment]
This is a dup of #5668.

**Comment by BushnevYuri** [comment]
Found workaround for all of those who are looking to use tags from InfluxDB with respect of timeFilter for Grafana variables templating.

https://stackoverflow.com/questions/54931888/query-tags-from-influxdb-with-respect-of-timefilter-for-grafana-variables-templa/54933003#54933003

**Comment by Fusl** [comment]
@BushnevYuri That works very well for small time ranges but is extremely slow when the `$timeFilter` time range is weeks or even months.
