### ISSUE TITLE
CURL post data doesnt work with retention policy

### ISSUE THREAD

**Issue by Scott-St** [influxdata/influxdb#7590]
### Retention Policies
I created a one_day retention policy as shown below:

name	duration	shardGroupDuration	replicaN	default
autogen	"0"	"168h0m0s"	1	true
****one_day**	"24h0m0s"	"1h0m0s"	1	false**

### Bash Script command
As per documentation I used CURL with the following command.  If I remove  _&rp=one_day_ the data is inserted as expected.  Once I add the retention policy no data is entered.

DBURL=http://192.168.XXX.XXX:8086
DBNAME=statistics
DEVICE="UNRAID"
CURDATE=`date +%s`

curl -is -XPOST "$DBURL/write?db=$DBNAME&rp=one_day" --data-binary "diskPowerOnHours,DEVICE=${DEVICE},DISK=${DESCRIPTION[$i]} PowerOnHours=${POWERONHOURS} ${CURDATE}000000000" >/dev/null 2>&1

### build
Branch	Build Time	Commit	Version
master	""	"ff307047057b7797418998a4ed709b0c0f346324"	"1.0.2"

**Comment by rossmcdonald** [comment]
@Scott-St How do you know data is not being inserted? Are you getting an error, or is the data not appearing in queries? Are you sure you are querying the correct retention policy?

**Comment by Scott-St** [comment]
@rossmcdonald when I use a select statement in the admin interface there is no new data.  If I leave out the retention policy part of the insert I can see the new entry from the select in the admin interface but when I include the retention policy part and run the same select there is no new data.

This is my select statement:

`select * from diskPowerOnHours order by time desc`

**Comment by rossmcdonald** [comment]
@Scott-St If you don't specify an RP in the query, then it will use the default (`autogen` typically). What about this query?

```
select * from "statistics"."one_day".diskPowerOnHours order by time desc
```

**Comment by Scott-St** [comment]
You're right. If I specify the retention policy in the query I see the results.  I guess I misunderstood the documentation.  I thought it would all be inserted together but just purged as per the retention policy from the insert statement.

Thanks for the help.
