### ISSUE TITLE
SELECT COUNT(*) FROM /.*/ returns only the count of one measurement

### ISSUE THREAD

**Issue by coussej** [influxdata/influxdb#7593]
System info: InfluxDB 1.0.2 on Ubuntu 16.04. I have a testdatabase with multiple measurements:
```
> SHOW MEASUREMENTS
name: measurements
------------------
name
RPi_distance
RPi_humidity
RPi_temperature
events
fill_level
flow_rate
pump_speed
testvalue
valve_state
```

__Steps to reproduce:__

```
SELECT COUNT(*) FROM /.*/ WHERE time > now() - 4d AND time < now()
```

__Expected behavior:__ 

The count of all individual datapoints is returned for each measurement.

__Actual behavior:__ 

Only the count of one measurement is returned.
```
> SELECT COUNT(*) FROM /.*/ WHERE time > now() - 4d AND time < now()
name: valve_state
-----------------
time			count_value
1478162623144713977	1303
```

__Additional info:__ 

I'm sure some of the other measurements actually contain data for the selected period:
```
> SELECT COUNT(*) FROM fill_level WHERE time > now() - 4d AND time < now()
name: fill_level
----------------
time			count_value
1478162757199746274	1728000
```

Others however don't have datapoints: (maybe this is a possible cause?)
```
> SELECT COUNT(*) FROM RPI_distance WHERE time > now() - 4d AND time < now()
>
```

**Comment by jwilder** [comment]
I can't reproduce this in 1.0.2 or 1.1rc1.  Do you have a way for us to recreate this issue?  Could you provide some steps to recreate some data that has this problem?

**Comment by coussej** [comment]
I created a backup from the full database, could that help? 
https://transfer.sh/CFUzC/testdata-backup.tar.gz

**Comment by coussej** [comment]
Hi @jwilder, have you downloaded the file above? It won't be online for much longer.

**Comment by jwilder** [comment]
@coussej I was able to download it, but have not had a chance to look into the issue further.

**Comment by coussej** [comment]
@jwilder OK, no worries. As long a you have the data :+1:
