### ISSUE TITLE
start of the week is Thursday. how to configure to start from monday/sunday ?

### ISSUE THREAD

**Issue by hariteritreee** [influxdata/influxdb#7594]
when I group by time(1w). I still see week starting from Thursday . I want week to start from sunday or monday. Please let me know how to get it done. I spent 4,5 hours trying to figure it out.  I am using 1.0.2 version

SELECT SUM(value) FROM measurement_name WHERE time >= '2016-10-09T18:30:00Z' AND time < '2016-11-07T18:29:59Z' GROUP BY time(1w)

**Comment by beckettsean** [comment]
http://docs.influxdata.com/influxdb/v1.0/query_language/data_exploration/#advanced-group-by-time-syntax

**Comment by zhaoweiguo** [comment]
So why not start from Monday or Sunday?
Is there any special reason?

**Comment by maartenderie** [comment]
> So why not start from Monday or Sunday?
> Is there any special reason?

It's because the epoch was a Thursday (1 January 1970). Influx only cares about epoch (a.k.a. unix) time. Which is also why you can't group by month.

**Comment by zhaoweiguo** [comment]
> > So why not start from Monday or Sunday?
> > Is there any special reason?
> 
> It's because the epoch was a Thursday (1 January 1970). Influx only cares about epoch (a.k.a. unix) time. Which is also why you can't group by month.

Thanks
