### ISSUE TITLE
Not clear if Go 1.6.2 or Go 1.7 is required

### ISSUE THREAD

**Issue by marcv81** [influxdata/influxdb#7602]
Since https://github.com/influxdata/influxdb/commit/3774d5e7340517b4feb7c379df2f457e49c562a7 (update latest dependencies with Godeps) Go 1.7 is now required to build, which does not match the recommendations in https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md.

If Go 1.6.2 is supported please partially revert the above commit.

1) Use the following Godeps: `collectd.org 3f276a01c9ef9dba3e8013d3252a6243a7240473`. This is not the previously used commit but the latest released commit supporting Go 1.6.
2) Do not import context in services/collectd/test_client/client.go.

Otherwise please update CONTRIBUTING.md.

**Comment by jwilder** [comment]
Should be 1.7.3.  Looks like the docs are out of date after merging #7522
