### ISSUE TITLE
What are the _internal metrics?

### ISSUE THREAD

**Issue by evbo** [influxdata/influxdb#7604]
Is it possible to shed some light on what these internal metrics mean? Specifically (of interest to me personally):

1. runtime.PauseTotalNs
1. graphite.batchesTx
1. graphite.batchesTxFail
1. graphite.bytesRx
1. subscriber.writeFailures
1. httpd.req

Some of them appear to be cumulative? Some of them appear to reset themselves (are they purging after X hours?). Any insight would be tremendously helpful in understanding what to do about them.

**Comment by jwilder** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.

There is a [stats documentation PR](https://github.com/influxdata/docs.influxdata.com/pull/777) with more information that might be helpful to take a look at.
