### ISSUE TITLE
InfluxDB Documentation link broken for influxdb-data

### ISSUE THREAD

**Issue by andyfeller** [influxdata/influxdb#7609]
### Bug report

__System info:__ influxdb-data 1.0.0-c1.0.0, CentOS 7, Chrome

__Steps to reproduce:__

1. Load InfluxDB HTTP client
2. Click Documentation link at top of screen

__Expected behavior:__ Web browser tab open going to the documentation of the same version as the package.  In my case, influxdb-data 1.0.0-c1.0.0 should have gone to [influxdb v1.0 documentation](https://docs.influxdata.com/influxdb/v1.0/introduction/getting_started/) instead of [404 page](https://docs.influxdata.com/influxdb/v/introduction/getting_started/)

__Actual behavior:__ Navigated to [404 page](https://docs.influxdata.com/influxdb/v/introduction/getting_started/) seemingly due to package version issue
![screen shot 2016-11-09 at 8 19 31 am](https://cloud.githubusercontent.com/assets/2089743/20139805/f8e4be66-a655-11e6-8fc3-665264c00e25.png)
![screen shot 2016-11-09 at 8 23 35 am](https://cloud.githubusercontent.com/assets/2089743/20139786/e1e1599a-a655-11e6-83e7-b718c70104eb.png)

**Comment by jwilder** [comment]
This will be fixed via #7531.
