### ISSUE TITLE
Enhancing DIFFERENCE() to support 2 columns

### ISSUE THREAD

**Issue by annismckenzie** [influxdata/influxdb#761]
Currently, the DIFFERENCE() function only supports one column and subtracts the first and last values per interval respectively.

Supporting two columns would be great so I can choose what columns to subtract from each other. Is this possible?

**Comment by pauldix** [comment]
This works on the 0.11 release:

```sql
select first(column1) - last(column1) from foo where time > now - 4h group by time(10m)
```

**Comment by annismckenzie** [comment]
As the internal project I was going to use this for has been dead for over a year I'm no longer in need of this feature. @pauldix: that wasn't what I was asking – I wanted the difference between the first and the last value of two different columns without dumping everything into its own time series first.

You may close this issue.

**Comment by pauldix** [comment]
The query I put up outputs a single series with data points at each 10m window so I think it gives you that. If you just want the single point for the series as a whole then it doesn't do that. Although it might if you do `GROUP BY time(5000000000000h)`
