### ISSUE TITLE
NSQ Consumer support for reader-opt

### ISSUE THREAD

**Issue by elvarb** [influxdata/influxdb#7612]
NSQ supports authentication and the NSQ command line tools either use 
    -reader-opt "auth_secret,verysecretreader"
or
    -producer-opt "auth_secret,verysecretproducer"

So in the NSQd auth server you can configure that the verysecretreader identity can only consume data from a specific topic/channel.

**Comment by jwilder** [comment]
I think you might have logged this in the wrong repository.  This is the InfluxDB repository.

**Comment by elvarb** [comment]
Yah true, should be in the telegraf one will post there
