### ISSUE TITLE
Continuous queries on times series in the future

### ISSUE THREAD

**Issue by gwuillou** [influxdata/influxdb#7617]
Hello, 

I am using InfluxDB version 1.0.0. . I am doing real-time analysis of energy data with a visualisation on Grafana. I have 2 types of times series: real and forecast. The forecast data go in the future ( 72h). In the forecast data, I have also different types of forecast. I would like to compare real data with forecast data but also forecast data with forecast data. In order to do that, I use CQs to get statistic about data. The goal in to take decisions in real time depending on the behavior of my statistic. 

Currently, CQs are done for the current data but no for the future data.

I would like to have the possibility to do that for future data. An example of continuous query is 

`CREATE CONTINUOUS QUERY bla ON database1 RESAMPLE EVERY 15m FOR 5h BEGIN SELECT distinct(value) AS blabla INTO database1."default"."puissance.electricite" FROM database2."default"."puissance.electricite" WHERE source = 'source' AND station = 'data.consommation.PCV' AND typeof = 'forecast' GROUP BY time(15m) END`

The FOR could be in the past and in the futur?

Thank you

**Comment by daviskirk** [comment]
Same use case here.  However I think it might be more elegant to have syntax to modify the "base" time which would be `now()` in the default case.   Maybe something like.

```
CREATE CONTINUOUS QUERY bla ON database1 RESAMPLE EVERY 15m FOR 5h UNTIL now() + 5h BEGIN SELECT distinct(value) AS blabla INTO database1."default"."puissance.electricite" FROM database2."default"."puissance.electricite" WHERE source = 'source' AND station = 'data.consommation.PCV' AND typeof = 'forecast' GROUP BY time(15m) END
```

**Comment by gwuillou** [comment]
Hello,

Have you scheduled to add this feature any time? Otherwise, I will stop to use influxdb although it is a nice database! 


Nice new year!

**Comment by jli2sc** [comment]
I need a similar feature as well for weekly data comparison.
CREATE CONTINUOUS QUERY bla ON database1 RESAMPLE EVERY 1m FOR 1m Shift now() - 7d BEGIN SELECT distinct(value) AS blabla INTO database1."default"."puissance.electricite" FROM database2."default"."puissance.electricite"  GROUP BY time(1m) END

**Comment by olsn** [comment]
I would also welcome feature like this
