### ISSUE TITLE
Update Elapsed function to return 0 for aggregations of less than two points

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#7619]
Feature Request

Currently the elapsed function returns nil if it aggregated less than 2 points. It makes sense to me to have it return a point with value of zero, when it aggregates less than 2 points. Since zero time has elapsed form one point to itself, or from no points.

Use case:

This use case came up here in this mailing list discussion https://groups.google.com/forum/?pli=1#!topic/influxdb/1CdjyXrhbjY

The basic idea is that elapsed time is being calculated between pairs of points. But if a point is missing no value is returned instead of reporting that no time elapsed.

**Comment by jwilder** [comment]
Sounds reasonable to me.
