### ISSUE TITLE
SAMPLE() with * weeds out string fields

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#7621]
### Bug report

nightly, Ubuntu

__Steps to reproduce:__

1. Write some data
```
> use mydb
Using database mydb
> insert blah value=6
> insert blah cal=6
> insert blah boo="hi, how are you"
> SELECT * FROM blah
name: blah
time				boo		cal	value
----				---		---	-----
2016-11-11T23:56:26.051934756Z				6
2016-11-11T23:56:32.538336046Z			6
2016-11-11T23:57:44.541442213Z	hi, how are you
```

2. Use `*` in the `SAMPLE()` function

```
> select sample(*,1) from blah
name: blah
time				sample_cal	sample_value
----				----------	------------
2016-11-11T23:56:26.051934756Z			6
2016-11-11T23:56:32.538336046Z	6
```

__Expected behavior:__ [What you expected to happen]

Return a sample for the string field.

I'm actually not sure what I expect `SAMPLE()` with `*` to do. I specified `1` point but I'll end up with three points, technically.

__Actual behavior:__ [What actually happened]

The string field is ignored in the results.

**Comment by jwilder** [comment]
I think many of the functions ignore strings and booleans.  cc @jsternberg @benbjohnson

**Comment by jsternberg** [comment]
This is a problem with the wildcard expansion. It defaults to only supporting floats and integers and we have to whitelist other types for other functions. It's an easy fix, but also really easy to forget.
