### ISSUE TITLE
why need %3B for multi query instead of support ;

### ISSUE THREAD

**Issue by jiafu1115** [influxdata/influxdb#7623]
I use followed code in chrome:

SELECT * FROM db;SELECT * FROM db

it will be encode when I use newest ok http client to:
SELECT%20*%20FROM%20db;SELECT%20*%20FROM%20db

then multiquery fail for only one recode.

So I want know why not support ; instead of %3B only.

I use okhttp, They said they follow browser： https://github.com/square/okhttp/issues/2975

I know the %3B is standard. why browser always not encode ; it confused me a lot.

anybody help me to understand it?

**Comment by jiafu1115** [comment]
I decode ; it will still be ;. so why not support ; but only support %3B

**Comment by jwilder** [comment]
I'm not exactly sure what you are asking.  `;` is a reserved character in URLs and need to be encoded.  See [RFC1738](https://www.ietf.org/rfc/rfc1738.txt)

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
