### ISSUE TITLE
Downsampling to save disk space with the use of continuous query

### ISSUE THREAD

**Issue by FelixDefrance** [influxdata/influxdb#7624]
Hi, 

I need to save disk space and i want to deal with downsampling to do the job.

I'd like to relocate measurement and tag set from the default Retention Policy to a new RP called "1month"

if I try to "copy" them with a CQ like the query below,  I get an error because my CQ doesn't have aggregation

Query :
```
CREATE RETENTION POLICY "1month" ON "snmpdb" DURATION 30d REPLICATION 1 SHARD DURATION 4h
CREATE CONTINUOUS QUERY "cq_60s" on "snmpdb" begin select * into "1month"."downsampled_snmpdb" from snmpdb group by time(60s), * end
```
Error :
```
ERR: error parsing query: GROUP BY requires at least one aggregate function
```
Maybe CG feature is not for that use... 
Anyone has a similar use case?

Thx,

**Comment by jwilder** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
