### ISSUE TITLE
Incorrect one-off values calculated by CQ using aggregate functions

### ISSUE THREAD

**Issue by dhakadamit** [influxdata/influxdb#7626]
The following continuous query leads to random, one-off (1 in 100) extremely large values being generated. We use these to calculate traded volume of stocks. 

`CREATE CONTINUOUS QUERY ohlc ON [DATABASE] RESAMPLE EVERY 1m FOR 1m  BEGIN SELECT first(last) as open, max(last) as high, min(last) as low, last(last) as close, max(volume)-min(volume_was) as volume INTO ohlc FROM scrips GROUP BY time(1m), id END`

We haven't been able to figure out a pattern as it happens at random times and rerunning the continuous query does not seem to fix the problem. Only overwriting the exact point works.

This used to work perfect till v0.13

System info:
Influxdb - 1.0.2
OS - Ubuntu 14.04

**Comment by jwilder** [comment]
What field is off and what is the type of that field?  We'll need some way to reproduce this issues in order to figure out what is going on.  Do you have a way to reproduce it?

**Comment by dhakadamit** [comment]
No, we aren't able to reproduce it. We can't even detect a pattern. It happens randomly. We write simultaneously to two instances (since we dont use cluster) and both the instances face the same issue. However, when the issue occurs, it happens only on one of them at once, not both. 

**Field:** volume (in the above query)
**Math:** max(volume)-min(volume_was)
**Type:** all fields are of type float
