### ISSUE TITLE
Query issues

### ISSUE THREAD

**Issue by jweikai** [influxdata/influxdb#7629]
OS: Centos
InfluxDB version：1.1.0, 1.0
mesurement: call
tag:  uid  corpid  industryid  areaid   deviceid
time: utc + 8h

query 1.  time between '2015-12-02' and '2015-12-03'. At 2015-12-02, Line 8 results
![Image of Yaktocat](https://raw.githubusercontent.com/jweikai/thread/master/1.png)

query 2.  time between '2015-12-02' and '2015-12-08'. At 2015-12-02,  Line 12 results
![Image of Yaktocat](https://raw.githubusercontent.com/jweikai/thread/master/2.png)

Why the same time two different query results?

**Comment by N-Coder** [comment]
I have the same problem, when I select a timerange as a whole I get more results than if I select it in two parts:

![screenshot from 2016-11-16 17-16-09](https://cloud.githubusercontent.com/assets/1306276/20368074/6f5983ea-ac20-11e6-99ab-17e77ad67af9.png)

Timerange 
`2014-02-13 15:04:21.150000 to 2014-04-14 15:04:21.150000` (second panel) has less values when queried as two ranges 
`2014-02-13 15:04:21.150000 to 2014-03-15 15:04:21.150000` plus 
`2014-03-15 15:04:21.150000 to 2014-04-14 15:04:21.150000` (first panel)

```
> SELECT COUNT(*) FROM charge_cycles WHERE ((detector::tag='charger_acvoltage') AND (discarded::tag='True') AND (participant::tag='2')) AND (time >= '2014-02-13 15:04:21.150000' AND time < '2014-03-15 15:04:21.150000');
name: charge_cycles
-------------------
time                    count_sample_count      count_soc_end   count_soc_start count_value
2014-02-13T15:04:21.15Z 38                      38              38              38

> SELECT COUNT(*) FROM charge_cycles WHERE ((detector::tag='charger_acvoltage') AND (discarded::tag='True') AND (participant::tag='2')) AND (time >= '2014-03-15 15:04:21.150000' AND time < '2014-04-14 15:04:21.150000');
name: charge_cycles
-------------------
time                    count_sample_count      count_soc_end   count_soc_start count_value
2014-03-15T15:04:21.15Z 10                      10              10              10

> SELECT COUNT(*) FROM charge_cycles WHERE ((detector::tag='charger_acvoltage') AND (discarded::tag='True') AND (participant::tag='2')) AND (time >= '2014-02-13 15:04:21.150000' AND time < '2014-04-14 15:04:21.150000');
name: charge_cycles
-------------------
time                    count_sample_count      count_soc_end   count_soc_start count_value
2014-02-13T15:04:21.15Z 78                      78              78              78
```

**Comment by jwilder** [comment]
@jweikai  I'm not sure I see the issue you are pointing out here.  The first has an end time of `2015-12-03` and the second has an end time of `2015-12-08` which are different times. 

#7484 might be related.

**Comment by jwilder** [comment]
@jsternberg

**Comment by N-Coder** [comment]
> @jweikai I'm not sure I see the issue you are pointing out here. The first has an end time of 2015-12-03 and the second has an end time of 2015-12-08 which are different times.

Both queries should include the 2015-12-02 09:08 row (as it is smaller than both 2015-12-03 and 2015-12-08), but it is only included in the latter query, which has more 'buffer time' between that row and the limit.

**Comment by jweikai** [comment]
@jwilder I'm sorry I'm not good at English, so the expression is not very clear...
as N-Code said, although the two end time is different, but include the 2015-12-02 this point in time

**Comment by jwilder** [comment]
Can you run `show shards` and attach the output?

**Comment by jweikai** [comment]
dbName: statistics, measurement: 
id	database	retention_policy	shard_group	start_time	end_time	expiry_time	owners
179	"statistics"	"rp_year"	179	"2015-11-30T00:00:00Z"	"2015-12-07T00:00:00Z"	"2016-12-07T00:00:00Z"	""
180	"statistics"	"rp_year"	180	"2015-12-07T00:00:00Z"	"2015-12-14T00:00:00Z"	"2016-12-14T00:00:00Z"	""
181	"statistics"	"rp_year"	181	"2015-12-14T00:00:00Z"	"2015-12-21T00:00:00Z"	"2016-12-21T00:00:00Z"	""
182	"statistics"	"rp_year"	182	"2015-12-21T00:00:00Z"	"2015-12-28T00:00:00Z"	"2016-12-28T00:00:00Z"	""
183	"statistics"	"rp_year"	183	"2015-12-28T00:00:00Z"	"2016-01-04T00:00:00Z"	"2017-01-04T00:00:00Z"	""
220	"statistics"	"rp_year"	220	"2016-01-04T00:00:00Z"	"2016-01-11T00:00:00Z"	"2017-01-11T00:00:00Z"	""
215	"statistics"	"rp_year"	215	"2016-01-11T00:00:00Z"	"2016-01-18T00:00:00Z"	"2017-01-18T00:00:00Z"	""
216	"statistics"	"rp_year"	216	"2016-01-18T00:00:00Z"	"2016-01-25T00:00:00Z"	"2017-01-25T00:00:00Z"	""
217	"statistics"	"rp_year"	217	"2016-01-25T00:00:00Z"	"2016-02-01T00:00:00Z"	"2017-02-01T00:00:00Z"	""
166	"statistics"	"rp_year"	166	"2016-02-01T00:00:00Z"	"2016-02-08T00:00:00Z"	"2017-02-08T00:00:00Z"	""
167	"statistics"	"rp_year"	167	"2016-02-08T00:00:00Z"	"2016-02-15T00:00:00Z"	"2017-02-15T00:00:00Z"	""
211	"statistics"	"rp_year"	211	"2016-02-15T00:00:00Z"	"2016-02-22T00:00:00Z"	"2017-02-22T00:00:00Z"	""
212	"statistics"	"rp_year"	212	"2016-02-22T00:00:00Z"	"2016-02-29T00:00:00Z"	"2017-03-01T00:00:00Z"	""
213	"statistics"	"rp_year"	213	"2016-02-29T00:00:00Z"	"2016-03-07T00:00:00Z"	"2017-03-08T00:00:00Z"	""
218	"statistics"	"rp_year"	218	"2016-03-07T00:00:00Z"	"2016-03-14T00:00:00Z"	"2017-03-15T00:00:00Z"	""
219	"statistics"	"rp_year"	219	"2016-03-14T00:00:00Z"	"2016-03-21T00:00:00Z"	"2017-03-22T00:00:00Z"	""
204	"statistics"	"rp_year"	204	"2016-03-21T00:00:00Z"	"2016-03-28T00:00:00Z"	"2017-03-29T00:00:00Z"	""
214	"statistics"	"rp_year"	214	"2016-03-28T00:00:00Z"	"2016-04-04T00:00:00Z"	"2017-04-05T00:00:00Z"	""
184	"statistics"	"rp_year"	184	"2016-04-04T00:00:00Z"	"2016-04-11T00:00:00Z"	"2017-04-12T00:00:00Z"	""
185	"statistics"	"rp_year"	185	"2016-04-11T00:00:00Z"	"2016-04-18T00:00:00Z"	"2017-04-19T00:00:00Z"	""
186	"statistics"	"rp_year"	186	"2016-04-18T00:00:00Z"	"2016-04-25T00:00:00Z"	"2017-04-26T00:00:00Z"	""
187	"statistics"	"rp_year"	187	"2016-04-25T00:00:00Z"	"2016-05-02T00:00:00Z"	"2017-05-03T00:00:00Z"	""
205	"statistics"	"rp_year"	205	"2016-05-02T00:00:00Z"	"2016-05-09T00:00:00Z"	"2017-05-10T00:00:00Z"	""
188	"statistics"	"rp_year"	188	"2016-05-09T00:00:00Z"	"2016-05-16T00:00:00Z"	"2017-05-17T00:00:00Z"	""
189	"statistics"	"rp_year"	189	"2016-05-16T00:00:00Z"	"2016-05-23T00:00:00Z"	"2017-05-24T00:00:00Z"	""
206	"statistics"	"rp_year"	206	"2016-05-23T00:00:00Z"	"2016-05-30T00:00:00Z"	"2017-05-31T00:00:00Z"	""
168	"statistics"	"rp_year"	168	"2016-05-30T00:00:00Z"	"2016-06-06T00:00:00Z"	"2017-06-07T00:00:00Z"	""
169	"statistics"	"rp_year"	169	"2016-06-06T00:00:00Z"	"2016-06-13T00:00:00Z"	"2017-06-14T00:00:00Z"	""
170	"statistics"	"rp_year"	170	"2016-06-13T00:00:00Z"	"2016-06-20T00:00:00Z"	"2017-06-21T00:00:00Z"	""
171	"statistics"	"rp_year"	171	"2016-06-20T00:00:00Z"	"2016-06-27T00:00:00Z"	"2017-06-28T00:00:00Z"	""
172	"statistics"	"rp_year"	172	"2016-06-27T00:00:00Z"	"2016-07-04T00:00:00Z"	"2017-07-05T00:00:00Z"	""
190	"statistics"	"rp_year"	190	"2016-07-04T00:00:00Z"	"2016-07-11T00:00:00Z"	"2017-07-12T00:00:00Z"	""
191	"statistics"	"rp_year"	191	"2016-07-11T00:00:00Z"	"2016-07-18T00:00:00Z"	"2017-07-19T00:00:00Z"	""
208	"statistics"	"rp_year"	208	"2016-07-18T00:00:00Z"	"2016-07-25T00:00:00Z"	"2017-07-26T00:00:00Z"	""
192	"statistics"	"rp_year"	192	"2016-07-25T00:00:00Z"	"2016-08-01T00:00:00Z"	"2017-08-02T00:00:00Z"	""
209	"statistics"	"rp_year"	209	"2016-08-01T00:00:00Z"	"2016-08-08T00:00:00Z"	"2017-08-09T00:00:00Z"	""
207	"statistics"	"rp_year"	207	"2016-08-08T00:00:00Z"	"2016-08-15T00:00:00Z"	"2017-08-16T00:00:00Z"	""
193	"statistics"	"rp_year"	193	"2016-08-15T00:00:00Z"	"2016-08-22T00:00:00Z"	"2017-08-23T00:00:00Z"	""
194	"statistics"	"rp_year"	194	"2016-08-22T00:00:00Z"	"2016-08-29T00:00:00Z"	"2017-08-30T00:00:00Z"	""
210	"statistics"	"rp_year"	210	"2016-08-29T00:00:00Z"	"2016-09-05T00:00:00Z"	"2017-09-06T00:00:00Z"	""
195	"statistics"	"rp_year"	195	"2016-09-05T00:00:00Z"	"2016-09-12T00:00:00Z"	"2017-09-13T00:00:00Z"	""
196	"statistics"	"rp_year"	196	"2016-09-12T00:00:00Z"	"2016-09-19T00:00:00Z"	"2017-09-20T00:00:00Z"	""
197	"statistics"	"rp_year"	197	"2016-09-19T00:00:00Z"	"2016-09-26T00:00:00Z"	"2017-09-27T00:00:00Z"	""
198	"statistics"	"rp_year"	198	"2016-09-26T00:00:00Z"	"2016-10-03T00:00:00Z"	"2017-10-04T00:00:00Z"	""
199	"statistics"	"rp_year"	199	"2016-10-03T00:00:00Z"	"2016-10-10T00:00:00Z"	"2017-10-11T00:00:00Z"	""
200	"statistics"	"rp_year"	200	"2016-10-10T00:00:00Z"	"2016-10-17T00:00:00Z"	"2017-10-18T00:00:00Z"	""
201	"statistics"	"rp_year"	201	"2016-10-17T00:00:00Z"	"2016-10-24T00:00:00Z"	"2017-10-25T00:00:00Z"	""
202	"statistics"	"rp_year"	202	"2016-10-24T00:00:00Z"	"2016-10-31T00:00:00Z"	"2017-11-01T00:00:00Z"	""
203	"statistics"	"rp_year"	203	"2016-10-31T00:00:00Z"	"2016-11-07T00:00:00Z"	"2017-11-08T00:00:00Z"	""
291	"statistics"	"rp_year"	291	"2016-11-14T00:00:00Z"	"2016-11-21T00:00:00Z"	"2017-11-22T00:00:00Z"	""

**Comment by jweikai** [comment]
@jwilder 
dbName: statistics, measurement call: 
id	database	retention_policy	shard_group	start_time	end_time	expiry_time	owners
179	"statistics"	"rp_year"	179	"2015-11-30T00:00:00Z"	"2015-12-07T00:00:00Z"	"2016-12-07T00:00:00Z"	""
180	"statistics"	"rp_year"	180	"2015-12-07T00:00:00Z"	"2015-12-14T00:00:00Z"	"2016-12-14T00:00:00Z"	""
181	"statistics"	"rp_year"	181	"2015-12-14T00:00:00Z"	"2015-12-21T00:00:00Z"	"2016-12-21T00:00:00Z"	""
182	"statistics"	"rp_year"	182	"2015-12-21T00:00:00Z"	"2015-12-28T00:00:00Z"	"2016-12-28T00:00:00Z"	""
183	"statistics"	"rp_year"	183	"2015-12-28T00:00:00Z"	"2016-01-04T00:00:00Z"	"2017-01-04T00:00:00Z"	""
220	"statistics"	"rp_year"	220	"2016-01-04T00:00:00Z"	"2016-01-11T00:00:00Z"	"2017-01-11T00:00:00Z"	""
215	"statistics"	"rp_year"	215	"2016-01-11T00:00:00Z"	"2016-01-18T00:00:00Z"	"2017-01-18T00:00:00Z"	""
216	"statistics"	"rp_year"	216	"2016-01-18T00:00:00Z"	"2016-01-25T00:00:00Z"	"2017-01-25T00:00:00Z"	""
217	"statistics"	"rp_year"	217	"2016-01-25T00:00:00Z"	"2016-02-01T00:00:00Z"	"2017-02-01T00:00:00Z"	""
166	"statistics"	"rp_year"	166	"2016-02-01T00:00:00Z"	"2016-02-08T00:00:00Z"	"2017-02-08T00:00:00Z"	""
167	"statistics"	"rp_year"	167	"2016-02-08T00:00:00Z"	"2016-02-15T00:00:00Z"	"2017-02-15T00:00:00Z"	""
211	"statistics"	"rp_year"	211	"2016-02-15T00:00:00Z"	"2016-02-22T00:00:00Z"	"2017-02-22T00:00:00Z"	""
212	"statistics"	"rp_year"	212	"2016-02-22T00:00:00Z"	"2016-02-29T00:00:00Z"	"2017-03-01T00:00:00Z"	""
213	"statistics"	"rp_year"	213	"2016-02-29T00:00:00Z"	"2016-03-07T00:00:00Z"	"2017-03-08T00:00:00Z"	""
218	"statistics"	"rp_year"	218	"2016-03-07T00:00:00Z"	"2016-03-14T00:00:00Z"	"2017-03-15T00:00:00Z"	""
219	"statistics"	"rp_year"	219	"2016-03-14T00:00:00Z"	"2016-03-21T00:00:00Z"	"2017-03-22T00:00:00Z"	""
204	"statistics"	"rp_year"	204	"2016-03-21T00:00:00Z"	"2016-03-28T00:00:00Z"	"2017-03-29T00:00:00Z"	""
214	"statistics"	"rp_year"	214	"2016-03-28T00:00:00Z"	"2016-04-04T00:00:00Z"	"2017-04-05T00:00:00Z"	""
184	"statistics"	"rp_year"	184	"2016-04-04T00:00:00Z"	"2016-04-11T00:00:00Z"	"2017-04-12T00:00:00Z"	""
185	"statistics"	"rp_year"	185	"2016-04-11T00:00:00Z"	"2016-04-18T00:00:00Z"	"2017-04-19T00:00:00Z"	""
186	"statistics"	"rp_year"	186	"2016-04-18T00:00:00Z"	"2016-04-25T00:00:00Z"	"2017-04-26T00:00:00Z"	""
187	"statistics"	"rp_year"	187	"2016-04-25T00:00:00Z"	"2016-05-02T00:00:00Z"	"2017-05-03T00:00:00Z"	""
205	"statistics"	"rp_year"	205	"2016-05-02T00:00:00Z"	"2016-05-09T00:00:00Z"	"2017-05-10T00:00:00Z"	""
188	"statistics"	"rp_year"	188	"2016-05-09T00:00:00Z"	"2016-05-16T00:00:00Z"	"2017-05-17T00:00:00Z"	""
189	"statistics"	"rp_year"	189	"2016-05-16T00:00:00Z"	"2016-05-23T00:00:00Z"	"2017-05-24T00:00:00Z"	""
206	"statistics"	"rp_year"	206	"2016-05-23T00:00:00Z"	"2016-05-30T00:00:00Z"	"2017-05-31T00:00:00Z"	""
168	"statistics"	"rp_year"	168	"2016-05-30T00:00:00Z"	"2016-06-06T00:00:00Z"	"2017-06-07T00:00:00Z"	""
169	"statistics"	"rp_year"	169	"2016-06-06T00:00:00Z"	"2016-06-13T00:00:00Z"	"2017-06-14T00:00:00Z"	""
170	"statistics"	"rp_year"	170	"2016-06-13T00:00:00Z"	"2016-06-20T00:00:00Z"	"2017-06-21T00:00:00Z"	""
171	"statistics"	"rp_year"	171	"2016-06-20T00:00:00Z"	"2016-06-27T00:00:00Z"	"2017-06-28T00:00:00Z"	""
172	"statistics"	"rp_year"	172	"2016-06-27T00:00:00Z"	"2016-07-04T00:00:00Z"	"2017-07-05T00:00:00Z"	""
190	"statistics"	"rp_year"	190	"2016-07-04T00:00:00Z"	"2016-07-11T00:00:00Z"	"2017-07-12T00:00:00Z"	""
191	"statistics"	"rp_year"	191	"2016-07-11T00:00:00Z"	"2016-07-18T00:00:00Z"	"2017-07-19T00:00:00Z"	""
208	"statistics"	"rp_year"	208	"2016-07-18T00:00:00Z"	"2016-07-25T00:00:00Z"	"2017-07-26T00:00:00Z"	""
192	"statistics"	"rp_year"	192	"2016-07-25T00:00:00Z"	"2016-08-01T00:00:00Z"	"2017-08-02T00:00:00Z"	""
209	"statistics"	"rp_year"	209	"2016-08-01T00:00:00Z"	"2016-08-08T00:00:00Z"	"2017-08-09T00:00:00Z"	""
207	"statistics"	"rp_year"	207	"2016-08-08T00:00:00Z"	"2016-08-15T00:00:00Z"	"2017-08-16T00:00:00Z"	""
193	"statistics"	"rp_year"	193	"2016-08-15T00:00:00Z"	"2016-08-22T00:00:00Z"	"2017-08-23T00:00:00Z"	""
194	"statistics"	"rp_year"	194	"2016-08-22T00:00:00Z"	"2016-08-29T00:00:00Z"	"2017-08-30T00:00:00Z"	""
210	"statistics"	"rp_year"	210	"2016-08-29T00:00:00Z"	"2016-09-05T00:00:00Z"	"2017-09-06T00:00:00Z"	""
195	"statistics"	"rp_year"	195	"2016-09-05T00:00:00Z"	"2016-09-12T00:00:00Z"	"2017-09-13T00:00:00Z"	""
196	"statistics"	"rp_year"	196	"2016-09-12T00:00:00Z"	"2016-09-19T00:00:00Z"	"2017-09-20T00:00:00Z"	""
197	"statistics"	"rp_year"	197	"2016-09-19T00:00:00Z"	"2016-09-26T00:00:00Z"	"2017-09-27T00:00:00Z"	""
198	"statistics"	"rp_year"	198	"2016-09-26T00:00:00Z"	"2016-10-03T00:00:00Z"	"2017-10-04T00:00:00Z"	""
199	"statistics"	"rp_year"	199	"2016-10-03T00:00:00Z"	"2016-10-10T00:00:00Z"	"2017-10-11T00:00:00Z"	""
200	"statistics"	"rp_year"	200	"2016-10-10T00:00:00Z"	"2016-10-17T00:00:00Z"	"2017-10-18T00:00:00Z"	""
201	"statistics"	"rp_year"	201	"2016-10-17T00:00:00Z"	"2016-10-24T00:00:00Z"	"2017-10-25T00:00:00Z"	""
202	"statistics"	"rp_year"	202	"2016-10-24T00:00:00Z"	"2016-10-31T00:00:00Z"	"2017-11-01T00:00:00Z"	""
203	"statistics"	"rp_year"	203	"2016-10-31T00:00:00Z"	"2016-11-07T00:00:00Z"	"2017-11-08T00:00:00Z"	""
291	"statistics"	"rp_year"	291	"2016-11-14T00:00:00Z"	"2016-11-21T00:00:00Z"	"2017-11-22T00:00:00Z"	""

**Comment by N-Coder** [comment]
Similar situation here, the problem is when around the shard boundaries:
```
[...]
106	drive4data	autogen			106		2014-03-03T00:00:00Z	2014-03-10T00:00:00Z	2014-03-10T00:00:00Z	
107	drive4data	autogen			107		2014-03-10T00:00:00Z	2014-03-17T00:00:00Z	2014-03-17T00:00:00Z	
126	drive4data	autogen			126		2014-03-17T00:00:00Z	2014-03-24T00:00:00Z	2014-03-24T00:00:00Z	
127	drive4data	autogen			127		2014-03-24T00:00:00Z	2014-03-31T00:00:00Z	2014-03-31T00:00:00Z	
[...]
```
https://gist.github.com/N-Coder/22ed81a7bb60aa3b706172b07f132f9a
Please also note that the first row in the data set is at 2013-04-05T16:36:50.04Z and the last row is at 2016-08-26T19:00:43Z, so I don't know here those shards from 1970 and 2017 came from.

**Comment by michele** [comment]
I'm having the same problem here: I imported 5 days worth of data (from 2017-08-06 to 2017-08-10) and no matter if I user `influx -import` or do it through the go client, all the data is compressed in a single day:

```
id	database	retention_policy	shard_group	start_time		end_time		expiry_time		owners
--	--------	----------------	-----------	----------		--------		-----------		------
1	testdb		duration		1		2017-08-07T00:00:00Z	2017-08-08T00:00:00Z	2017-09-07T00:00:00Z
```

The db was created with this query:

```
"CREATE DATABASE \"testdb\" WITH DURATION 30d REPLICATION 1 SHARD DURATION 1d NAME \"duration\""
```

Timestamps are with nano second precision and for the import file were passed to `Sprintf` using this: `r.StartedAt.UnixNano()` where `StartedAt` is a Go `time.Time`.

Any help with this?

Thanks!

**Comment by rbetts** [comment]
We want to re-test this in 1.5.x

**Comment by jsternberg** [comment]
I can't reproduce this on the latest version. If you are still running into the issue, please tell us and we'll attempt to fix this. We implemented time zones at some point though so if the issue was time zone based, it was likely fixed when we did that.
