### ISSUE TITLE
after DISTINCT()  count value show times

### ISSUE THREAD

**Issue by heijiu** [influxdata/influxdb#7630]
select * from test
username books
mike book1
summer book1
Abel book2
mike book3
zeal book2
Abel book3
mike book2

how to get after DISTINCT count value show times And sort
mike 3
Abel 2
summer 1
zeal 1

**Comment by heijiu** [comment]
select count("books") from test group by username 
how can order by count

**Comment by jwilder** [comment]
This isn't possible currently. See #4794.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list in the future.
