### ISSUE TITLE
configurably prevent highly non-performant retention schema

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7638]
### Feature Request

__Proposal:__ [Description of the feature]

We should restrict any `CREATE RETENTION POLICY` statement that would lead to more than `max_shard_groups` shard groups, which would be a configuration in the `[retention]` section of the config.

__Current behavior:__ [What currently happens]

Users can make any RP they like without warning. One recent customer had a 1 year retention with 30 minute shards. That's 4000+ shard groups, which is highly non-performant.

__Desired behavior:__ [What you would like to happen]

Users attempting to create an RP with `DURATION > (SHARD DURATION * max_shard_groups)` would get an error linking to http://docs.influxdata.com/influxdb/latest/administration/config/#retention, which would have a description of the restriction and why it would almost always be a bad idea to remove the restriction.

__Use case:__ [Why is this important (helps with prioritizing requests)]

Fewer shards is better for performance in almost every way. The only reason to have shorter shards is to enable more frequent data expiration. Let's keep users from setting up pathological RPs by accident. Right now there is no indication that this is a decision with massive performance implications.

**Comment by beckettsean** [comment]
I think `max_shard_groups` should be initially set to 20 or so.

**Comment by beckettsean** [comment]
@jwilder @pauldix this would be hugely helpful in preventing terrible RPs with hundreds or even thousands of shard groups. We typically don't hear from customers until the performance craters, and since there's no way to alter historic shards, they're stuck with the decision forever unless they export and rewrite all the data.

**Comment by pauldix** [comment]
For the initial setting, we'd have to do some testing to really get a feel for it. I think 20 is significantly lower than is reasonable. For example, for an `inf` retention policy the default duration is 7d. Although, I guess that begs the question of what should the limit check be on `inf` retention policies.

One thing to consider is that in upcoming releases, the measurement/tag index will be on a per shard basis. We don't want that to get too polluted with ephemeral series and the way to do that is to roll over the shard from time to time.

Probably a bit to think about on this.

**Comment by beckettsean** [comment]
Thanks for the context on how the new indexing will affect this, @pauldix. Since each shard has a fixed overhead for query iterators, more shards means more RAM for queries. If the indices are per-shard, but the shards are never dropped (INF DURATION), it seems like the SHARD DURATION should also be infinite.

All I know is that we get many many more issues from shards that are too short than we do from series cardinality issues. Mostly because the latter is well known and documented and has config options as firewalls against accidentally exploding the cardinality. I think we need to do the same for shard durations. Right now people are left to their own intuition, which will almost invariably be wrong.
