### ISSUE TITLE
Backup does not require authentication?

### ISSUE THREAD

**Issue by ericvrp** [influxdata/influxdb#7639]
Today I started creating backups with:

> influxd backup -database mydb -since 2016-01-01T00:00:00Z -host sub.domain.com:8088 snapshots

but I am very surprised that this works even though I have auth_enabled=true in my config. Connecting to the server from the commandline does not allow me to use mydb as expected.

**Comment by jwilder** [comment]
Authentication is only for the HTTP endpoint (port 8086). Backup uses a different endpoint (port 8088) and an different protocol altogether.  You can bind that endpoint to the loopback interface to at least require host level access.

**Comment by ericvrp** [comment]
In that case I find the default settings very bad. No authentication over http and a completely open port for backups. Why not enable authentication and disable to backup port. And if enabled at least bind to localhost only.

Great product apart from this! 👍

**Comment by ericvrp** [comment]
How do I bind to localhost in the config? Can't find port :8088 in there.
