### ISSUE TITLE
SHOW TAG with a WHERE does not work for tags with _ as prefix

### ISSUE THREAD

**Issue by steverweber** [influxdata/influxdb#7642]
```
root@influxdb-p01:/srv# influx -version
InfluxDB shell version: 1.1.0
```

```
> select time, "_group", "_room", "heartbeat.latest" from vmware_sys

vmware_sys

time	_group	_room	heartbeat.latest
2016-11-18T16:03:17Z	"mfcf-test"	"m33101"	30
2016-11-18T16:04:37Z	"mfcf-service"	"lost(mc3015)"	30
2016-11-18T16:05:13Z	"mfcf-research"	"m33101"	30
2016-11-18T16:06:51Z	"mfcf-service"	"mc3015"	30
2016-11-18T16:07:52Z	"mfcf-service"	"mc3015"	30
2016-11-18T16:08:57Z	"mfcf-staff"	"mc3015"	0
2016-11-18T16:09:52Z	"mfcf-service"	"m33110"	30


> SHOW TAG VALUES FROM "vmware_sys" WITH KEY = "_room" WHERE "_group" = "mfcf-test"

vmware_sys

key	value
_room	"lost(mc3015)"
_room	"m33101"
_room	"m33110"
_room	"mc3015"

### expected to only have "m33101"

> SHOW TAG VALUES FROM "vmware_sys" WITH KEY = "_room" WHERE "vmware_sys"."_group" = "mfcf-test"

Success! (no results to display)
### expected result of "m33101"

```

**Comment by jwilder** [comment]
I think you have the wrong quotes in your where clause.  Try using single-quotes `'` for the value:

```
SHOW TAG VALUES FROM "vmware_sys" WITH KEY = "_room" WHERE "_group" = 'mfcf-test'
```

```
SHOW TAG VALUES FROM "vmware_sys" WITH KEY = "_room" WHERE "vmware_sys"."_group" = 'mfcf-test'
```

**Comment by steverweber** [comment]
```
SHOW TAG VALUES FROM "vmware_sys" WITH KEY = "_room" WHERE "vmware_sys"."_group" = 'mfcf-test'
```

same error.

**Comment by jwilder** [comment]
Maybe the extra "vmware_sys" in the where clause is causing problems:

Does this work:
```
SHOW TAG VALUES FROM "vmware_sys" WITH KEY = "_room" WHERE "_group" = "mfcf-test"
SHOW TAG VALUES FROM "vmware_sys" WITH KEY = "_room" WHERE "_group" = 'mfcf-test'
```

**Comment by steverweber** [comment]
that was already tested as the first attempt.
```
> SHOW TAG VALUES FROM "vmware_sys" WITH KEY = "_room" WHERE "_group" = "mfcf-test"
```
retried changing " to '
```
SHOW TAG VALUES FROM "vmware_sys" WITH KEY = "_room" WHERE "_group" = 'mfcf-test'
It lists everything... it's not filtering using the WHERE
```

seems that this is being tested...:
```
https://github.com/influxdata/influxdb/blob/af72d9b0e4ebe95be30e89b160f43eabaf0529ed/influxql/parser_test.go#L1420
```

could it be an issue with the under scores?

**Comment by steverweber** [comment]
humm perhaps its because '_group' is a KEY not a metric value.

**Comment by jwilder** [comment]
@steverweber I think it's because the tag keys have `_` a prefix.  We rewrite some meta queries an use `_` as a special internal character.  I believe it's failing here: https://github.com/influxdata/influxdb/blob/master/tsdb/shard.go#L1270

@jsternberg

**Comment by steverweber** [comment]
I'll remove the `_` and retest.

**Comment by steverweber** [comment]
this might be the issue... I'll preform another test to be %100

**Comment by steverweber** [comment]
confirmed. `HasPrefix(tag.Val, "_")

I did feel that me using an `_`  was asking for trouble but it did't jump out at me when reading the documents.... Perhaps some extra documents would be helpful to close this issue.

**Comment by steverweber** [comment]
also i should note that I need to be careful where i use `"` and `'`.

this worked.
```
SHOW TAG VALUES FROM "vmware_sys" WITH KEY = "x_fqdn" WHERE "x_group" = 'mfcf-test'
```

**Comment by cv711** [comment]
Some more info on this issue from my experience:

`SELECT * FROM "event" WHERE "_name" = 'value'` : no results
`SELECT * FROM "event" WHERE "_name" =~ /value/` : no results
`SELECT * FROM "event" WHERE "_name" =~ /*/` : correct results
`SELECT * FROM "event" WHERE "_key1" = 'value1'` : correct results
`SHOW TAG VALUES WITH KEY = "_name"`
```
name: event
key	value
---	-----
_name	value
_name	testing
```

Of course all the above queries should return some results. So it looks like at least there is some clash when the tag name is `_name`

**Comment by jwilder** [comment]
@cv711 Yes.  The workaround currently is to not use `_` as prefix for tag names.

**Comment by steverweber** [comment]
related:
https://github.com/influxdata/influxdb/issues/6011
