### ISSUE TITLE
influxql.TimeRange can be tricked into returning bad time range

### ISSUE THREAD

**Issue by keep94** [influxdata/influxdb#7649]
### Bug report

__System info:__

Linux Ubuntu 14.04. Using git hub revision b765a4b "Merge pull requests #7631 from influxdata/jw-timer-allocs"

__Steps to reproduce:__

I wrote this code.
```
package main

import (
        "errors"
        "fmt"
        "github.com/influxdata/influxdb/influxql"
        "strings"
        "time"
)

func TimeRange(sql string) (min, max time.Time, err error) {
        p := influxql.NewParser(strings.NewReader(sql))
        stmt, err := p.ParseStatement()
        if err != nil {
                return
        }
        s, ok := stmt.(*influxql.SelectStatement)
        if !ok {
                err = errors.New("Not an influx statement")
                return
        }
        fmt.Println(s.String())
        now := time.Now().UTC()
        nowValuer := influxql.NowValuer{Now: now}
        s.Condition = influxql.Reduce(s.Condition, &nowValuer)
        return influxql.TimeRange(s.Condition)
}

func main() {
  min, max, err := TimeRange("select field0 from metrics where time >= now() - 2h or time < now() - 1h")
  fmt.Println(min, max, err)
}
```

__Expected behavior:__ [What you expected to happen]

I would expect the call to TimeRange to return min = max = 0 since the OR causes the where clause to cover ALL times.

__Actual behavior:__ [What actually happened]

Instead I get min = now() - 2h and max = now() - 1h

__Additional info:__ [Include gist of relevant config, logs, etc.]

If I use AND instead of OR, I get min = now() - 2h and max = now() -1h as expected. When I look at the
code, it appears that influxql.TimeRange walks the expression and whenever it sees a comparison operator such as less than or greater than and 'time' on one side of it, it adjusts the min or max time. However, it seems that influxql.TimeRange pays no attention to context such as where these comparison operators appear within the overall expression making it easy to trick.

We have a requirement that we know the time range that a query spans in advance so that we can make decisions about where to send the query.

**Comment by jsternberg** [comment]
I think this is related to #3290 and is being tracked in #7530. Does this sound like it matches your issue?

**Comment by keep94** [comment]
Yep #7530 sums up this issue fairly well. Feel free to mark this as a duplicate. Sorry about that.
