### ISSUE TITLE
Inconsistent response on SHOW GRANTS query

### ISSUE THREAD

**Issue by dstreppa** [influxdata/influxdb#7650]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Centos 6.7
InfluxDB 1.0.2

__Expected behavior:__ [What you expected to happen]
```
> show databases
name: databases
---------------
name
pv_monitoring
_internal
togo
geo_besso
sodapro

> show grants for geobesso_ro
database	privilege
```

__Actual behavior:__ [What actually happened]
```
> show databases
name: databases
---------------
name
pv_monitoring
_internal
togo
geo_besso
sodapro

> show grants for geobesso_ro
database	privilege
geobesso	READ
```

__Additional info:__ [Include gist of relevant config, logs, etc.]

Database _geobesso_ does not exist actually. It was an old db now dropped. However, for SHOW GRANTS query _geobesso_ still exists.

**Comment by e-dard** [comment]
@jwilder one to add to the 1.2 milestone?
