### ISSUE TITLE
CLI or UI command to retrieve metadata for each measurements

### ISSUE THREAD

**Issue by jayannah** [influxdata/influxdb#7657]
Influxdb : v 1.0

I would like to know if there is any command to know the metadata information for given measurements or all measurements in the InfluxDb instances which will give the details of how many rows are written/exists in a measurement.

When I execute the command SHOW SHARDS, the output of the commands gives the shards details at database, but not the how many rows in the database.

Even though select count(*) from <m_name> or select count(fieldname) from <m_name> gives number of rows, it may not the best approach as it will read the database and counts the number of rows.  If metadata file is having such info, the reading for database can be avoided.

Hence, I'm looking for the following if there is faster ways (without reading the database & counting process)
1.  The command which give the total number of rows in the database
2.  The command which give the total number of rows in the measurement

Please let me know if any more details required.

**Comment by e-dard** [comment]
I think if you want the number of points for a given database or measurement you will have to execute the appropriate `COUNT` query.

If you want to know the number of measurements or series in a database you can get hold of that information using the `_internal` database. For example, something like:

```
SELECT LAST(numSeries) AS "series", LAST(numMeasurements) AS "measurements" from "database" GROUP BY "database"
```

**Comment by jayannah** [comment]
Thanks for the response. What have you given is good information for knowing number of series in each database & measurement.

I would like to know number of data points in each database & measurement. If there is a command, without doing select count(fieldname), to get number of datapoints is great to know whether the influx instances which are behind the replay are in sync or not in sync.

**Comment by jayannah** [comment]
Any update on this question or is this limitation in Influxdb now?

**Comment by e-dard** [comment]
@jayannah it's a limitation of the DB for now.

**Comment by jayannah** [comment]
ok..thanks. Can you please tag this as bug/enhancement request?

**Comment by jayannah** [comment]
It would be great by adding the total number of rows in a database to the "database" measurement in the _internal database.

Currently we can know how many # of series in each database.  Requesting to add total number of rows to the same table.. It would be even great if you have the another measurement called "measurement" and that will have details about # of rows, Total # of keys, Total # of field values, measurement name, etc.

time	database	hostname	numMeasurements	numSeries
2016-12-15T16:15:50Z	"TEST"	"influx-db-qa-node1us-east-1b"	1	2
2016-12-15T16:16:00Z	"TEST"	"influx-db-qa-node1us-east-1b"	1	2
2016-12-15T16:16:10Z	"TEST"	"influx-db-qa-node1us-east-1b"	1	2
