### ISSUE TITLE
crash on invalid collectd packet

### ISSUE THREAD

**Issue by borcsokj** [influxdata/influxdb#7660]
### Bug report

__System info:__ InfluxDB 1.1.0

__Steps to reproduce:__

1. enable collectd and set typesdb configuration property
```
[[collectd]]
  enabled = true
  bind-address = ":25826"
  database = "collectd"
  typesdb = "/usr/share/collectd/types.db"
```

2. add composite type definition to types DB, i.e. for JMX threading
```
jmx_threading           threads_all:GAUGE:0:U, threads_daemon:GAUGE:0:U
```

3. send collectd packet with more numeric values than specified in types.db

__Expected behavior:__ store first section of values (that are specified in types.db), drop unspecified values

__Actual behavior:__ InfluxDB have been crashed

**Comment by jwilder** [comment]
@borcsokj Can you attach the full trace from the logs from the crash?

**Comment by borcsokj** [comment]
Here is the error message from logs:
```
panic: runtime error: index out of range

goroutine 193 [running]:
panic(0x9cf120, 0xc4200100a0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/kimor79/gollectd.Packets(0xc427188c00, 0x51b, 0x5ac, 0xc42a723f50, 0x7f5d4b8fb4b0, 0x0, 0x51b)
        /root/go/src/github.com/kimor79/gollectd/gollectd.go:225 +0x1388
github.com/influxdata/influxdb/services/collectd.(*Service).handleMessage(0xc420167180, 0xc427188c00, 0x51b, 0x5ac)
        /root/go/src/github.com/influxdata/influxdb/services/collectd/service.go:324 +0x6e
github.com/influxdata/influxdb/services/collectd.(*Service).serve(0xc420167180)
        /root/go/src/github.com/influxdata/influxdb/services/collectd/service.go:318 +0x177
github.com/influxdata/influxdb/services/collectd.(*Service).Open.func2(0xc420167180)
        /root/go/src/github.com/influxdata/influxdb/services/collectd/service.go:180 +0x57
created by github.com/influxdata/influxdb/services/collectd.(*Service).Open
        /root/go/src/github.com/influxdata/influxdb/services/collectd/service.go:180 +0x707
```

Is it enough for analysis / reproducing?

**Comment by allenpetersen** [comment]
This looks like a clear bug in gollectd

https://github.com/kimor79/gollectd/blob/master/gollectd.go#L225

It seems like the number and order of valueTypes in the packet doesn't need to line up with what is in typesdb so the index [i] isn't going to match up.

The good news InfluxDB has switched from gollectd to collectd.org last month. There is a good chance that 1.2.0 will not have this crash.

**Comment by borcsokj** [comment]
Thank you, I will check release 1.2.0.

**Comment by jsternberg** [comment]
It seems since the code that caused this panic no longer exists, the panic likely doesn't exist anymore either. I'm going to close this. If you need a faster resolution such as work trying to put it into 1.1.1 or 1.2 doesn't resolve the issue in some way, please respond and I'll reopen the issue so we can evaluate if this change is worth backporting.

Thanks.
