### ISSUE TITLE
Enhancement commands for managing subscription

### ISSUE THREAD

**Issue by jayannah** [influxdata/influxdb#7664]
### Feature Request
__Proposal:__ [Description of the feature]
Add the commands for to achieve the following
1. Allow Admin to disable & Enable all subscription
  DISABLE SUBSCRIPTION ALL ==> will disable the subscription, will NOT remove the subscriptions
  ENABLE SUBSCRIPTION ALL ==> Will enable all the subscriptions as per the previously subscribed entries

2.  ALL Admin user to remove all subscriptions
  DROP SUBSCRIPTION ALL ==> will remove all subscriptions from all database

3. Allow Admin to remove subscription for giving for giving kapacitor destination id (shown in show subscriptions commands)
   e.g:  DROP SUBSCRIPTION  <kapacitor-destination-id>   => should remove the subscription of this ID from all the databases

4. Remove ALL subscriptions for particular database
   e.g:  DROP SUBSCRIPTION ALL on  <database>.<policy>  ==> should remove all subscription on the given database & policy
   e.g:  DROP SUBSCRIPTION ALL on <Database>  ==> Should remove all subscription on the database

__Current behavior:__ [What currently happens]
Manually every subscription for every entry needs to be dropped, which is painful.

__Desired behavior:__ [What you would like to happen]
Admin user should be able to manage subscription with few commands as stated above.

__Use case:__ [Why is this important (helps with prioritizing requests)]
When Kapacitors are down or not in use, The influxDB are sending all data points to Kapacitor.. Not sure why they will send each every data.. Administration

**Comment by aarongorka** [comment]
In the mean time, here's a bash oneliner for dropping all subscriptions:

```bash
IFS=$'\n'; for i in $(influx -format csv -username $INFLUXUSER -password $INFLUXPASS -database _internal -execute 'show subscriptions' | tail -n +3); do echo "drop subscription \"$(echo "$i" | cut -f 3 -d ',')\" ON \"$(echo "$i" | cut -f 1 -d ',')\".\"$(echo "$i" | cut -f 1 -d ',')\""; done
```
