### ISSUE TITLE
[Feature request] Add logfile in influxdb.conf to specify log file location

### ISSUE THREAD

**Issue by wei-hai** [influxdata/influxdb#7678]
__Proposal:__ 
Add logfile in influxdb.conf to specify log file location like that in telegraf
__Current behavior:__ 
The latest version writes log via systemd journal
__Desired behavior:__ 
Provide an option to use the old way for logging
__Use case:__
We use Telegraf's plugin tail and logparser to find error message from influxdb's log file and they cannot work with journalctl, so it would be flexible to provide an option to explicitly specify where the log file is.

**Comment by jsternberg** [comment]
It might be most appropriate to do this as part of the change to structured logging that's being done in #7036.

The initial PR for that won't do what this issue is requesting, but it's a very small step to add that functionality afterwards.

**Comment by e-dard** [comment]
I'm 👎  on add functionality to log to files. I don't think the database should be concerning itself with that. If it's necessary to redirect database logs to file(s) then using shell redirection and/or tools like `tee` seems like the best way to do this.

**Comment by pauldix** [comment]
Does the information on this page give a good answer for how to work with the InfluxDB output in log files? https://docs.influxdata.com/influxdb/v1.2/administration/logs/
