### ISSUE TITLE
WebUI Query Autocomplete does not work with firefox

### ISSUE THREAD

**Issue by rolele** [influxdata/influxdb#7680]
It is working fine with chrome but the autocomplete is not showing with firefox.

**Comment by jsternberg** [comment]
We don't currently have an autocomplete feature in the WebUI that I'm aware of. This sounds like the autocomplete that's included in all browsers. If you switch your browser, of course the autocomplete from the old browser will be gone.

The WebUI is also deprecated so we are not accepting PR's for it anymore. If you still need the WebUI, feel free to fork the code for that and run it as a separate project. It would be really easy to just set up an Nginx server to serve the files.
