### ISSUE TITLE
Add internal stat to record number of dropped series/measurements

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/influxdb#7697]
### Feature Request

__Proposal:__ Add internal stats to track the number of series and measurements dropped.

__Current behavior:__ Series and measurements are dropped silently when shard are dropped or `DROP` statements are executed.

__Desired behavior:__ It would be nice to have `num_series_dropped` and `num_measurements_dropped` fields in the `database` measurement or whichever internal measurement makes the most sense.

__Use case:__  There is currently no easy way to track the number of dropped series and measurements. Knowing the number of dropped series/measurements is useful for determining the rate series are being removed by a retention policy capacity planning. It is also hard to determine the number of series measurements removed when `DROP` statements are executed.

**Comment by e-dard** [comment]
Related to: #7691.

**Comment by jwilder** [comment]
The number of series dropped can be seen using a `difference` query over the current counters.  If it's positive, it's the number series added.  If it's negative, it's the number of series deleted.

**Comment by gunnaraasen** [comment]
Using the `difference` function works in some cases, but doesn't allow aggregation over a time period that is longer than the internal stats collection interval. For example, running

```
SELECT difference(max("numSeries")) FROM "influxdb_database" WHERE "host" = 'monitor' AND time > now() - 14d GROUP BY time(1d)
``` 

in a busy system with >1M series, the number of net dropped series becomes harder to discern. Sub-queries and the [`integral` function](https://github.com/influxdata/influxdb/pull/7591) would make this possible, but it feels like an explicit stat is easier to reason about. Tracking (and alerting on) series created/dropped is an integral part of debugging InfluxDB performance issues.

I was going to open some other PRs to add a `numSeriesCreated` and maybe even shard-level dropped stats, e.g. `shard..seriesDropped` (mirroring `shard..seriesCreate`). If this isn't the way to go, then we really need to finish up the [`_internal` stats documentation](https://github.com/influxdata/docs.influxdata.com/pull/777) and add examples.

Also, I'm not sure if these stats will be effectively moot when the TSI is merged.
