### ISSUE TITLE
Should support moving averages aggregate function

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#77]
Should be able to calculate moving averages of different types. Simple, weighted, exponential, etc. Need to come up with specific syntax and stuff, but for now there's more reading here http://en.wikipedia.org/wiki/Moving_average

**Comment by ajcrowe** [comment]
+1

**Comment by probepark** [comment]
+1

**Comment by Paulche** [comment]
+1

**Comment by tbillet** [comment]
+1

**Comment by naneau** [comment]
+1

**Comment by ebereketoglu** [comment]
+1

**Comment by tcolgate** [comment]
I'd really like to have a go at this (and Holt winters forecasting). CQ seems the right way of doing these. They'd need access previous buckets/periods. Any tips would be appreciated. I'll start having a dig around

**Comment by cemo** [comment]
+1

**Comment by mbalkanloo** [comment]
window functions give the simple moving average for free and they are a really nice feature (http://www.postgresql.org/docs/9.4/static/tutorial-window.html).

haven't seen a database that provides EMA out of the box. usually it's a user defined function.

**Comment by mooremo** [comment]
:+1:

**Comment by digitalwm** [comment]
+1

**Comment by geronime** [comment]
+1, moving average is something we would also appreciate.

Our use case is having metrics of raw monitoring data, let's say every minute pushing:

    memory.<hostname>
      free: <free_bytes>
      total: <total_memory_bytes>

I was trying to have continuous query for pctFree_memory.<hostname>

    select (free * 100.0 / total) from /^memory\./ into pctFree_:series_name

This one on it's own does not work (the historical values are calculated but new ones are propagated with `free` and `total`; the calculated value is not there).

On the other note I was trying something like:

    select mean(free * 100.0 / total) as pctFreeAvg5m from /^memory\./ where (time > now() - 5m) AND (time < now()) into pctFreeAvg5m_:series_name

But this one also does not work.

Can you perhaps point me into a right direction if such metrics are possible directly with continuous queries at all?

**Comment by kespindler** [comment]
+1 on this. One way mentioned on this page is

```select mavg(val) from temp_series group by time(1h) into temp_series.mavg.1h
```

but that only gives a downsampled average, not a moving average. Does anyone have leads on this?

**Comment by jsfrerot** [comment]
+1

**Comment by josh-padnick** [comment]
+1

**Comment by nzjess** [comment]
+1

**Comment by robochat** [comment]
+1

**Comment by mmedeiros** [comment]
+1

**Comment by MarekRychlik** [comment]
+1

**Comment by ezeql** [comment]
+1

**Comment by p4fg** [comment]
+1

**Comment by andremann** [comment]
+1

**Comment by dmichael** [comment]
++

**Comment by zachkendrick** [comment]
+1

**Comment by mipapo** [comment]
+1

**Comment by daijithegeek** [comment]
++

**Comment by bbinet** [comment]
+1

**Comment by cagdascirit** [comment]
+1

**Comment by markuspatrick** [comment]
+1

**Comment by manoochehri** [comment]
+1 :-)

**Comment by lunxian** [comment]
+1 
This is a useful function in Graphite, I need it in influxdb also.

**Comment by wzph** [comment]
+1

**Comment by hillar** [comment]
bump

**Comment by aadrian** [comment]
+1

**Comment by smaddula** [comment]
+1

**Comment by bill0ute** [comment]
+1

**Comment by maklaut** [comment]
+1

**Comment by rackunits** [comment]
+1

**Comment by filippovitale** [comment]
+1

**Comment by mariusoe** [comment]
+1

**Comment by gilgamezh** [comment]
+1

**Comment by burthen** [comment]
+1

**Comment by jonseymour** [comment]
+1

**Comment by ddaka** [comment]
+2

**Comment by jcmartins** [comment]
+1

**Comment by men1n2** [comment]
+1

**Comment by leomaros** [comment]
+1

**Comment by jlmcgehee21** [comment]
+1

**Comment by aglagla** [comment]
+1

**Comment by zas** [comment]
+1

**Comment by cwegener** [comment]
+1

**Comment by brumfb** [comment]
+1

**Comment by mhiller** [comment]
+1

**Comment by mrwulf** [comment]
+1

**Comment by ojarva** [comment]
:+1:

**Comment by j3ffrw** [comment]
+1

**Comment by zapient** [comment]
+1

**Comment by adrianlzt** [comment]
+1

**Comment by pieroxy** [comment]
+1

**Comment by jmaitrehenry** [comment]
+1

**Comment by mbalkanloo** [comment]
unsubscribe

**Comment by thegreatjerboa** [comment]
+1

**Comment by mbalkanloo** [comment]
unsubscribe

**Comment by pauldix** [comment]
@mbalkanloo that's not how you unsubscribe to an issue. You're adding more noise whenever you send that email. Follow the link to GH and unsubscribe to the issue using their interface.

**Comment by hailpam** [comment]
+1

**Comment by tomazbracic** [comment]
+1

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by jsternberg** [comment]
I'll be making a new issue for each component of this issue. The simple moving average aggregate is in #6112 and we hope to be able to get that into 0.12.0, but no promises.

I'm reclosing this issue for now.

**Comment by k3gk3gk3g** [comment]
+1

**Comment by szymic1** [comment]
+1

**Comment by Planet2010** [comment]
+1

**Comment by shawafts** [comment]
+1

**Comment by dterg** [comment]
+1

**Comment by vincentbarat** [comment]
+1

**Comment by jsternberg** [comment]
We have implemented some moving average functions. If you need a moving average function that isn't included in the latest version, please open a new issue so we can triage the issue.

Thanks. I'm going to lock this conversation to prevent additional +1 comments.
