### ISSUE TITLE
Add tab completion to CLI

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#7704]

**Comment by FourSeventy** [comment]
Looks like this can be done for bash by making some bash completion scripts and installing them to the correct directory, `/etc/bash_completion.d` on Debian for example. This article seems to explain how to do it https://debian-administration.org/article/317/An_introduction_to_bash_completion_part_2

The hard part would be figuring out how to get the completions installed to the correct place for various shells/operating systems.
