### ISSUE TITLE
Error while calculating percentage

### ISSUE THREAD

**Issue by thealphaking01** [influxdata/influxdb#7707]
I have been running a Kapacitor Tick Script on top of Influx, with the query 

```
SELECT  (sum("successful")/COUNT("successful")) * 100 as success_percent, 
COUNT("successful") as observation_points
FROM.....
GROUP BY tag1, tag2
```

Here, "successful" is a field with value either 0 or 1 indicating failure and success respectively. 

Now, everything is working correctly most of the time, giving me the correct success percentage but sometimes I suddenly get values more than 100, going even into thousands and ten thousands. I have tried replicating this directly from Influxdb CLI but have been unsuccessful so far. 

When scheduled on Kapacitor, however, this script runs every 30 minutes or so, and gives skewed values, again, not always. 

Is there a problem with the COUNT() keyword? I have a check that I would receive a trigger only when the COUNT("successful") is greater than a minimum threshold, so a divide by zero doesn't look like the cause, or is it? I am not sure what is causing the error here. Would be grateful for some help.

**Comment by e-dard** [comment]
This seems like an issue that should be opened on https://github.com/influxdata/kapacitor? Thanks!
