### ISSUE TITLE
how to change the default bind port?

### ISSUE THREAD

**Issue by lygn128** [influxdata/influxdb#7711]
run] 2016/12/10 05:37:51 InfluxDB starting, version 1.1.1, branch master, commit e47cf1f2e83a02443d7115c54f838be8ee959644
[run] 2016/12/10 05:37:51 Go version go1.7.4, GOMAXPROCS set to 32
[run] 2016/12/10 05:37:51 Using configuration at: ../../etc/influxdb/influxdb.conf
run: open server: listen: listen tcp :8088: bind: address already in use

but  i have not find the config item in influx.conf, can i solve this? thank you very much.

**Comment by mebezac** [comment]
8088 is the port backup/restore uses, it can be changed in `influx.conf` or by setting the `INFLUXDB_BIND_ADDRESS` ENV variable.

https://docs.influxdata.com/influxdb/v1.1/administration/config/#bind-address-8088

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list.

Thanks.
