### ISSUE TITLE
GraphQL endpoint

### ISSUE THREAD

**Issue by mytototo** [influxdata/influxdb#7713]
Hey,

Do you have plans about a GraphQL endpoint admin so we can consume it instead of the REST API ? Way much easier for a dashboard.

Thanks.

**Comment by e-dard** [comment]
@mytototo we don't have any plans for that, no. Please feel free to open a new issue with a feature request.

**Comment by danlg** [comment]
agree with @mytototo and would support the creation of a GraphQL end point, this would probably speed up the dev of [chronograf] (https://github.com/influxdata/chronograf)
