### ISSUE TITLE
Is it possible to output the query results which are in different measurements in time-order?

### ISSUE THREAD

**Issue by nyg2015** [influxdata/influxdb#7714]
Hi , I am using influxdb, and it is awesome. 

I met a problem and donot know how to do . I have several measurements in my database .  Is it possible to output the query results which are in different measurements in time-order? 

For example , the points in "t_trade" (a measurement in database)
time                   docType          packageID    volume
14000000001     "trade"           1                     2
14000000003     "trade"           3                     2

the points in "t_order" (a measurement in database)
time                   docType          packageID     orderID
14000000002     "order"           2                     4

My expected results are 
time                   docType          packageID    volume   orderID
14000000001     "trade"           1                     2
14000000002     "order"           2                                       4
14000000003     "trade"           3                     2

But the results I using the "select * from /^t_*/ order by time" are as follows
name: t_trade
time                   docType          packageID    volume   orderID
14000000001     "trade"           1                     2
14000000003     "trade"           3                     2

name: t_order
time                   docType          packageID    volume   orderID
14000000002     "order"           2                                       4

One solution is that merge all the fields from different measurements into a big measurement ,but maybe it is not a good solution, Can you give me some suggestions?

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list.

(Currently it's not possible to query across measurements).

Thanks.
