### ISSUE TITLE
tcp.Mux: handler not registered: 71. Connection from [::1]:49853 closed

### ISSUE THREAD

**Issue by MayukhSobo** [influxdata/influxdb#7716]
I know this has been answered several times but I am still not able to fix this. Please help me.
My config file looks like this
http://pastebin.com/Db27RArp
I don't know if I am doing anything wrong. Please help.

**Comment by jwilder** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list in the future.

That message is usually logged when something is incorrectly connecting to port `8088`.  `8088` is an internal port.  Most likely you should be using `8086`.
