### ISSUE TITLE
InfluxDB Docker container giving error when writing to external volume

### ISSUE THREAD

**Issue by jakobnotseth** [influxdata/influxdb#7720]
### Bug report

__System info:__

Docker:
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64
Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

InfluxDB:
Official InfluxDB image
Version 1.1.0

__Steps to reproduce:__

1. Create docker container using InfluxDB image and map data volume
2. Load a lot of data (I'm currently loading 8 x 1KB/100ms)
3. If load is high enough, you'll start seeing error With tsm1 adding New TSM files
4. If you stop then start the container again, you get another error (even if you got the one above first or not) on invalid files, non-existing files or similar

__Expected behavior:__ 
Expect it to read/Write to docker-volum correctly

__Actual behavior:__ 
[tsm1] 2016/12/14 12:14:12 error adding new TSM files from snapshot: fsync: invalid argument
[tsm1] 2016/12/14 12:14:12 Snapshot for path /var/lib/influxdb/data/rrdev/deductible_seconds/3 written in 974.2724ms
[tsm1] 2016/12/14 12:14:12 error writing snapshot: fsync: invalid argument
This error is also referenced here: http://stackoverflow.com/questions/40125447/docker-giving-error-when-writing-to-external-volume
[tsm1] 2016/12/14 12:23:17 error replacing new TSM files: fsync: invalid argument
- Or this one
[tsm1] 2016/12/14 12:26:23 error adding new TSM files from snapshot: fsync: invalid argument
also more often than not, the cacheloader and tsm1 will report errors trying to read non existing files, and get stuck since it will not continue past the non-existing files.

**Comment by jakobnotseth** [comment]
Here is one of the invallid file Messages as well:
[tsm1] 2016/12/14 12:37:20 error compacting TSM files: open /var/lib/influxdb/data/rrdev/deductible_seconds/4/000000003-000000002.tsm: no such file or directory

**Comment by jakobnotseth** [comment]
Gist With Complete output sequence when trying to start container again after stop
https://gist.github.com/jakobnotseth/f995cd8275cbf6241bfc0025cb24513c

**Comment by jwilder** [comment]
* Can you show how you are starting the container?  
* Is the host volume you are mounting in a local disk?

If you can provide some steps to reproduce this that would be great.  It looks like this might be a docker volume issue.  I also see `OS/Arch: windows/amd64`, are you running docker on windows?

**Comment by jakobnotseth** [comment]
I'm using docker-compose currently,to get my environment running but the issue is the same if using the "official" docker run command from the docker hub site:
  influxdb:
    image: influxdb:1.1.0
    restart: always
    ports: 
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
The host volum is a local disk, and yes, this is docker for Windows.
As far as I know, I don't do anything in particular for the error to appear other than stopping and starting the containers (I'm using Kitematic if that has any importance).

**Comment by jakobnotseth** [comment]
also even if not restarting the container, it will get these issues after running a while:
[tsm1] 2016/12/15 23:11:44 error compacting TSM files: open /var/lib/influxdb/data/rrdev/running_seconds/6/000000044-000000001.tsm: no such file or directory
[tsm1] 2016/12/15 23:11:44 beginning level 2 compaction of group 0, 2 TSM files
[tsm1] 2016/12/15 23:11:44 compacting level 2 group (0) /var/lib/influxdb/data/rrdev/running_seconds/17/000000035-000000002.tsm (#0)
[tsm1] 2016/12/15 23:11:44 compacting level 2 group (0) /var/lib/influxdb/data/rrdev/running_seconds/17/000000039-000000002.tsm (#1)
[tsm1] 2016/12/15 23:11:44 error compacting TSM files: open /var/lib/influxdb/data/rrdev/running_seconds/17/000000035-000000002.tsm: no such file or directory
[write] 2016/12/15 23:11:44 write failed for shard 1: engine: cache-max-memory-size exceeded: (2147499584/2147483648)
[httpd] 172.16.238.15 - - [15/Dec/2016:23:11:42 +0000] "POST /write?db=rrdev HTTP/1.1" 500 96 "-" "-" d792da45-c31b-11e6-93ea-000000000000 1325344
[httpd] 172.16.238.15 - - [15/Dec/2016:23:11:40 +0000] "POST /write?db=rrdev HTTP/1.1" 500 98 "-" "-" d64984ed-c31b-11e6-93d4-000000000000 3495586
[write] 2016/12/15 23:11:44 write failed for shard 1: engine: cache-max-memory-size exceeded: (2147490608/2147483648)
[httpd] 172.16.238.15 - - [15/Dec/2016:23:11:41 +0000] "POST /write?db=rrdev HTTP/1.1" 500 98 "-" "-" d6a651cd-c31b-11e6-93da-000000000000 3019432
[write] 2016/12/15 23:11:44 write failed for shard 1: engine: cache-max-memory-size exceeded: (2147499712/2147483648)
[httpd] 172.16.238.15 - - [15/Dec/2016:23:11:41 +0000] "POST /write?db=rrdev HTTP/1.1" 500 97 "-" "-" d6f74db6-c31b-11e6-93dc-000000000000 2495830
[tsm1] 2016/12/15 23:11:44 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/12/15 23:11:44 compacting level 1 group (0) /var/lib/influxdb/data/rrdev/dynamic_hours/7/000000041-000000001.tsm (#0)
[tsm1] 2016/12/15 23:11:44 compacting level 1 group (0) /var/lib/influxdb/data/rrdev/dynamic_hours/7/000000043-000000001.tsm (#1)
[tsm1] 2016/12/15 23:11:44 error compacting TSM files: open /var/lib/influxdb/data/rrdev/dynamic_hours/7/000000041-000000001.tsm: no such file or directory
[write] 2016/12/15 23:11:44 write failed for shard 1: engine: cache-max-memory-size exceeded: (2147484032/2147483648)

**Comment by jwilder** [comment]
This is very likely an issue w/ docker on windows and how it handles mounting volumes.  Their [docs](https://docs.docker.com/engine/tutorials/dockervolumes/) note several caveats.  The errors looks very similar to what happens when using NFS for the data dir.  The database uses memory mapped files which doesn't work well with network filesystems  My guess is docker for windows is using something like NFS to mount host volumes which won't work.

If you can reproduce this error outside of docker we can re-open the issue.

**Comment by franklsm1** [comment]
I am currently seeing the exact same issue with docker on Mac when handling a mounted volume of influx data.

**Comment by michaelsogos** [comment]
Dear,

I'm facing the same issue, a lot of error during compacting my "appmetrics" database.
![image](https://user-images.githubusercontent.com/971120/29493947-a10e204e-85a0-11e7-861b-0477bebcca8d.png)

Do you have a solution for this?
