### ISSUE TITLE
InfluxDB doesn't allow inserting "null" value for fields

### ISSUE THREAD

**Issue by pprkut** [influxdata/influxdb#7722]
### Bug report

__System info:__ InfluxDB 1.1.0, CentOS 7

__Steps to reproduce:__

1. INSERT measure,purpose=test value=1i,not_working=null 1481713571901366407

__Expected behavior:__ Successful insert

__Actual behavior:__ ERR: {"error":"unable to parse 'measure,purpose=test value=1i,not_working=null 1481713571901366407': invalid number"}

__Additional info:__ 

I checked the documentation and as far as I can see, there is no indication that inserting null values should not be working. Even if they shouldn't work, the error message "invalid number" is rather misleading.

**Comment by jwilder** [comment]
`null` is not a valid field value and is unsupported.  There are only 4 field types supported, `int64`, `float64`, `bool` and `string`.  See the [line protocol docs](https://docs.influxdata.com/influxdb/v1.1/write_protocols/line_protocol_reference/) for valid syntax for each of those field types.

**Comment by pprkut** [comment]
Ah, you're right. I see it now.
