### ISSUE TITLE
incorrect data when define param epoch=ms 

### ISSUE THREAD

**Issue by eshkel** [influxdata/influxdb#7734]
Trying to use grafana for visualization, and this service added param epoch=ms to InfluxDB query.
query for test data is quite simple 

> SELECT "value" FROM "datafield0" where did='101c6bf561ceccbc' limit 1000

the data without epoch param

> {"results":[{"series":[{"name":"datafield0","columns":["time","value"],"values":[["1970-01-01T00:00:00.000051Z",42],["1970-01-01T00:00:00.000168Z",18],["1970-01-01T00:00:00.000269Z",23],["1970-01-01T00:00:00.000399Z",0]...

if I add epoch=ms (same results I receive for parameters: epoch=m epoch=s epoch=h ) I got 

> {"results":[{"series":[{"name":"datafield0","columns":["time","value"],"values":[[0,42],[0,18],[0,23],[0,0],[0,37],[0,15],[0,59],[0,18],[0,1],[0,33],[1,37],[1,32],[1,48],[1,55],[1,48],[1,26],[1,33],[1,16],[1,43],[2,58]...

if I add epoch=0 I got 

> {"results":[{"series":[{"name":"datafield0","columns":["time","value"],"values":[[51000,42],[168000,18],[269000,23],[399000,0],[449000,37],[575000,15],[692000,59],[734000,18],[842000,1],[971000,33],[1080000,37]

that seems correct result for ms (test data was generated near to unix start time 1970 ). 

seems the epoch param is broken.

tested on
---
apt-show-versions influxdb
influxdb:amd64/xenial 1.1.1-1 uptodate

**Comment by mark-rushakoff** [comment]
Your timestamps are at sub-millisecond resolution, i.e. `1970-01-01T00:00:00.000051Z` is 51 _microseconds_ or 0.051 milliseconds.

The `epoch` query parameter has always returned whole number time values, as far as I know, and 0.051 milliseconds rounds to 0 milliseconds.

When you specify `epoch=0`, which is not valid but effectively the same as specifying nanoseconds, you see the timestamps as the number of nanoseconds past Unix epoch, and the output you pasted is correct based on the RFC3339 timestamps.

What do you think is broken exactly?

**Comment by eshkel** [comment]
thank you, it's clear now, just used time_precision instead of precision parameter(opened old documentation for v0.8 instead of actual version) for inserting data, so data was inserting in nanos.
