### ISSUE TITLE
[Feature Request]Support multiple types.db for collectd

### ISSUE THREAD

**Issue by wei-hai** [influxdata/influxdb#7736]
### Feature Request
__Proposal:__
Support multiple types.db files in [[collectd]] in config file

__Current behavior:__
It supports only one types.db file

__Desired behavior:__
Supports multiple types.db, e.g., typesdb = ["/usr/local/share/collectd/types.db", "/usr/local/share/collectd/generic-jmx.db"]

__Use case:__
Some collectd plugin needs extra metric type such as jmx for collectd-java which is not in the default types.db

**Comment by e-dard** [comment]
@wei-hai I don't know much about collectd, but can you not merge your types into a single file?

**Comment by jwilder** [comment]
I believe this is already supported via #6908.  This is also a dup of #1110

**Comment by wei-hai** [comment]
@jwilder Can you please give an example of how to add multiple types.db in the config file?

**Comment by jwilder** [comment]
@wei-hai I believe you should be able to specify a directory as your types db path and it will scan the directory.

```
typesdb = ["/usr/local/share/collectd"]
```

**Comment by wei-hai** [comment]
@jwilder Thank you for the example. Please update the default config to `typesdb = ["/usr/local/share/collectd"]` if possible, or add comment about the it in the config file, right now the default setting is `typesdb = "/usr/local/share/collectd/types.db"`.

**Comment by poonia0arun** [comment]
["/usr/local/share/collectd"] seems not working. Is there anyway to include whole directory for typesdb..
