### ISSUE TITLE
Feature request: read-only mode of influxd 

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#7737]
Given a dataset that is behaving unexpectedly, I want to be able to run `influxd` with that dataset and be sure that no TSM files are compacted and no WAL files are snapshotted or modified. I want to avoid a compaction or snapshot that may change the behavior of the dataset, and I do not want to allow any writes to happen.

Currently, workarounds to achieve similar behavior include:

* Modifying all the config settings that may affect data on disk
  * Downside: there's a lot of settings that have to change, and many of them would involve simply setting excessively high timeouts / file size limits, etc.
* Using `chown -R a-w $PATH_TO_INFLUX_DIR`
  * Downside: There will likely be many errors in the logs, and it's hard to predict how the different subsystems will behave following those errors. It's difficult to later restore permissions to precisely the way they were prior to running `chmod`.

This could be implemented as `influxd -readonly`, but it would probably be better as a top-level config file option so that static datasets could be hosted without concern of modification.

**Comment by yokinfx** [comment]
+1 , I'm also interested on this request. I am sharing the influxdb data folder through nfs, and hace another server that wants yo read this data, but only read. Mounting the nfs share as read-only gives lots of errors

**Comment by balalinux** [comment]
+1 I would love this too. I could make use of it during the backup.
