### ISSUE TITLE
Derivative emits timestamp with END of GROUP BY period instead of START of GROUP BY period

### ISSUE THREAD

**Issue by ot3** [influxdata/influxdb#7738]
Consider the following query:

```
SELECT derivative(mean("value"), 1h) FROM "gas_meter" WHERE time>1481673600000000 GROUP BY time(1h) fill(none)

2016-12-14T07:00:00Z 0.028999999999996362
2016-12-14T08:00:00Z 0.6169999999997344
2016-12-14T09:00:00Z 0.9340000000001965
2016-12-14T10:00:00Z 0.9279999999998836
2016-12-14T11:00:00Z 0.849999999999909
2016-12-14T12:00:00Z 0.7699999999999818
```

The value of "0.6169999999997344" has a timestamp of 08:00 UTC which is at the END of the period for which this value is true. This means that when I use a presentation program such as Grafana, it renders the value of "0.6169999999997344" from 08:00-09:00 UTC which is incorrect and undesirable as this value is only valid between 07:00 and 08:00. 

I have not found any solution to avoid this 1hr. offset. If such a solution exists, I'd like to know, if not I'll submit a feature request.

Is there a solution or even a workaround?

ADDED: InfluxDB shell version: 1.1.0 on Raspbian GNU/Linux 8 (jessie)

**Comment by e-dard** [comment]
@jsternberg any idea on this?

**Comment by desa** [comment]
Looks like we do a [backward difference](https://en.wikipedia.org/wiki/Finite_difference#Forward.2C_backward.2C_and_central_differences) instead of a forward one. Relevant lines are [functions.go#L106-L127](https://github.com/influxdata/influxdb/blob/master/influxql/functions.go#L106-L127).

We should definite allow people to specify what kind of derivative they want.

**Comment by ot3** [comment]
Thanks for pinpointing the problem. Before deciding on how to implement a fix, is there a use case for doing a backward difference? If no, this is most likely a bug, if yes the user has to be provided with the option to do either.

Is there a workaround that can be used until a proper solution is available?

**Comment by ot3** [comment]
Any progress on providing answers/solutions?

**Comment by desa** [comment]
@ot3 sorry for the delay. We haven't had a chance to investigate this more since December. The easiest thing I can this of right now is to simply implement another function that does a forward difference.

**Comment by ot3** [comment]
Fully agree; when is this expected to happen?

**Comment by desa** [comment]
Hard to say exactly, if you could open a formal feature request, we can start getting it properly prioritized.
