### ISSUE TITLE
[InfluxQL] Quering boolean changes for timestamp

### ISSUE THREAD

**Issue by freeseacher** [influxdata/influxdb#7739]
Hi!

I have a boolean value that changes sometimes. I want to show that value as annotation on grafana's dashboard. 
My query looks like 
```
SELECT "value", "interface" FROM "Interface | Status | Oper" WHERE "object" =~ /^myswitch$/ AND "interface" =~ /^GigabitEthernet1\/0\/13$/ AND time > xxxx and time < xxxx
```
and data looks like 
```
1481957373000000000	true	GigabitEthernet3/0/13
1481957673000000000	true	GigabitEthernet3/0/13
1481957974000000000	true	GigabitEthernet3/0/13
1481958274000000000	true	GigabitEthernet3/0/13
1481958574000000000	false	GigabitEthernet3/0/13
1481958873000000000	false	GigabitEthernet3/0/13
1481959182000000000	false	GigabitEthernet3/0/13
```
how i can show only time when value is changed?

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list.

Thanks.
