### ISSUE TITLE
About  Min() and Auxiliary fields

### ISSUE THREAD

**Issue by liurunchao** [influxdata/influxdb#7749]
当我执行select min(price),hostName from host，使用min函数再加辅助字段时，在返回的结果中，我希望辅助字段hostName的值和price值的最小值是属于同一个point的。就像使用first函数那样。

**Comment by e-dard** [comment]
HI @liurunchao, `min(price)` is an aggregator and works on just one field. There currently isn't a way to include auxiliary fields belonging to the same selected point in the result. This is why you will see the wrong `hostName` value associated with the `price` value.

In future, the mailing list would be better for these types of questions, and please use English.

**Comment by e-dard** [comment]
Dupe of #7719.

**Comment by oiooj** [comment]
@e-dard I told him use Chinese and I will translate later. Not everyone good at English in China. You can understand Chinese？ Maybe google, lol

**Comment by e-dard** [comment]
@oiooj I used Google translate 😄
