### ISSUE TITLE
(*models.point).UnmarshalBinary panics due to lack of bounds checking

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#7759]
[(*point).UnmarshalBinary](https://github.com/influxdata/influxdb/blob/de4436e/models/points.go#L1431-L1448), called from [NewPointFromBytes](https://github.com/influxdata/influxdb/blob/de4436e/models/points.go#L1200-L1210) doesn't check slice boundaries and will panic on short slices. 

The early bounds checks are straightforward, but the unclear part of fixing this is that it looks like the call to `(*time.Time).UnmarshalBinary` deliberately discards its error (because the `time` field is pre-set to now), and it looks like closed source utilities may depend on that behavior.

**Comment by e-dard** [comment]
Is this fixed via #8080?

**Comment by mark-rushakoff** [comment]
Yes, looks like #8080 closes this issue.
