### ISSUE TITLE
 404 error on api InfluxDB version: 1.1.1 - docker 

### ISSUE THREAD

**Issue by RotemEmergi** [influxdata/influxdb#7763]
Hi !

I am using InfluxDB shell version: 1.1.0 in docker , server ubuntu 16.04.

I get 404 error on curl http://localhost:8086 and none on curl http://localhost:8086/ping .

In the logs I see :

[snapshot] 2016/12/25 09:18:31 Starting snapshot service
[admin] 2016/12/25 09:18:31 Starting admin service
[admin] 2016/12/25 09:18:31 DEPRECATED: This plugin is deprecated as of 1.1.0 and will be removed in a future release
[admin] 2016/12/25 09:18:31 Listening on HTTP: [::]:8083
[continuous_querier] 2016/12/25 09:18:31 Starting continuous query service
[httpd] 2016/12/25 09:18:31 Starting HTTP service
[httpd] 2016/12/25 09:18:31 Authentication enabled: false
[httpd] 2016/12/25 09:18:31 Listening on HTTP: [::]:8086
[retention] 2016/12/25 09:18:31 Starting retention policy enforcement service with check interval of 30m0s
[graphite] 2016/12/25 09:18:31 Starting graphite service, batch size 5000, batch timeout 1s
[monitor] 2016/12/25 09:18:31 'graphite:tcp::2003' registered for diagnostics monitoring
[monitor] 2016/12/25 09:18:31 Storing statistics in database '_internal' retention policy 'monitor', at interval 10s
[graphite] 2016/12/25 09:18:31 Listening on TCP: [::]:2003
2016/12/25 09:18:31 Sending usage statistics to usage.influxdata.com
[run] 2016/12/25 09:18:31 Listening for signals

**Comment by ZhukovAlexey** [comment]
What do you expect from http://localhost:8086 ?

There're three endpoints you can use: ping, query and write.
See https://docs.influxdata.com/influxdb/v1.1/tools/api/

**Comment by RotemEmergi** [comment]
I get 404 error on curl http://localhost:8086 .
There is no response on curl http://localhost:8086/ping .

**Comment by ZhukovAlexey** [comment]
Provide "docker run" command, please.

**Comment by RotemEmergi** [comment]
I am using a docker-compose file 
`version: '2'
volumes:
    prometheus_data: {}
    grafana_data: {}
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
      - influxdb
    depends_on:
      - cadvisor
    networks:
      - back-tier
    restart: always
  
  node-exporter:
    image: prom/node-exporter
    expose:
      - 9100
    networks:
      - back-tier
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes: 
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    restart: always  
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      - back-tier
    restart: always
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - /private/grafana-selfsigned.key:/home/ssl/grafana-selfsigned.key
      - /certs/grafana-selfsigned.crt:/home/ssl/grafana-selfsigned.crt
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - ./prometheus/data:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "2003:2003"
      - "8090:8090"
    networks:
      - back-tier
      - front-tier
    env_file:
      - 'env.influxdb'
    restart: always`
And in the env.influxdb : 
`INFLUXDB_GRAPHITE_ENABLED=true
INFLUXDB_GRAPHITE_DATABASE=jmeter`

I run just docker-compose up -d

**Comment by ZhukovAlexey** [comment]
Do you experience any write problems?

From your post you said "I get 404 error on curl http://localhost:8086 and none on curl http://localhost:8086/ping ."

404 error on curl http://localhost:8086 is OK, because you should use /ping, /query and /write endpoints.
See https://docs.influxdata.com/influxdb/v1.1/tools/api/

Empty request on curl http://localhost:8086/ping is fine too, because it returns empty body with 204 response code. To see header use `curl -sl -I http://localhost:8086/ping`
See  https://docs.influxdata.com/influxdb/v1.1/tools/api/#ping


Show output:

1. `sudo lsof -i :8086`
2. `sudo netstat -ltupn | grep 8086`
3. `docker ps`
4. `curl http://localhost:8086/query?q=SHOW+DATABASES`
5. `curl http://localhost:8086/write`
6. `curl -sl -I http://localhost:8086/ping`

**Comment by desa** [comment]
@RotemEmergi I'm not exactly sure what the issue is. I think the system is behaving as expected.

**Comment by RotemEmergi** [comment]
Hi!


rotem@prometheus-monitoring:~$ lsof -i :8086
rotem@prometheus-monitoring:~$  netstat -ltupn | grep 8086
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::8086                 :::*                    LISTEN      -               
rotem@prometheus-monitoring:~$ docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                                           
                                 NAMES
caf609c10027        grafana/grafana      "/run.sh"                2 days ago          Up 3 minutes        0.0.0.0:3000->3000/tcp                                          
                                 prometheus_grafana_1
5b8168d0d1da        prom/prometheus      "/bin/prometheus -con"   2 days ago          Up 3 minutes        0.0.0.0:9090->9090/tcp                                          
                                 prometheus
0e921ead92e1        influxdb:latest      "/entrypoint.sh influ"   2 days ago          Up 3 minutes        0.0.0.0:2003->2003/tcp, 0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->80
86/tcp, 0.0.0.0:8090->8090/tcp   influxdb
3b45534b3df3        google/cadvisor      "/usr/bin/cadvisor -l"   4 weeks ago         Up 3 minutes        8080/tcp                                                        
                                 prometheus_cadvisor_1
aedb7344be04        prom/alertmanager    "/bin/alertmanager -c"   4 weeks ago         Up 3 minutes        0.0.0.0:9093->9093/tcp                                          
                                 prometheus_alertmanager_1
8fa63f35bfa7        prom/node-exporter   "/bin/node_exporter"     4 weeks ago         Up 3 minutes        9100/tcp                                                        
                                 prometheus_node-exporter_1


4.curl http://localhost:8086/query?q=SHOW+DATABASES
root@0e921ead92e1:/# curl http://localhost:8086/query?q=SHOW+DATABASES
{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["jmeter"]]}]}]}
5.curl http://localhost:8086/write
root@0e921ead92e1:/# curl http://localhost:8086/write
Method Not Allowed
6. curl -sl -I http://localhost:8086/ping
root@0e921ead92e1:/# curl -sl -I http://localhost:8086/ping
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 213424c4-ccd5-11e6-8002-000000000000
X-Influxdb-Version: 1.1.1
Date: Wed, 28 Dec 2016 08:10:43 GMT

**Comment by desa** [comment]
I'm still not sure what the issue is. Seems like everything is working as expected. The only thing I see is in `5` you are making a `GET` request to an endpoint that only accepts `POST`.

```sh
curl -XPOST -sl -i http://localhost:8086/write?db=_internal
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: ea493103-cd0d-11e6-8006-000000000000
X-Influxdb-Version: unknown
Date: Wed, 28 Dec 2016 14:57:13 GMT
```
