### ISSUE TITLE
A question of "WHERE 1 = 1"

### ISSUE THREAD

**Issue by sfwn** [influxdata/influxdb#7766]
As we all know, you can use
```sql
select * from cpu where 1 = 1
```
in regular sql for conveniently appending `AND` or `OR` clause.

But when I used sql above in influxdb, I got a null resultset even though there are much data indeed.
When I append some other filter conditions(real fields) I can get right result.
```sql
select * fom cpu where 1 = 1 and time < now()
```

I guess my operation was wrong but I want to know whether "where 1 = 1" supported in influxdb?

**Comment by desa** [comment]
@sfwn at the moment it isn't supported, a work around would be to use `time < now()` as `1 = 1` because all queries use this time bound implicitly.

**Comment by doug-ess** [comment]
For anyone else who finds this in the future, I've been using `WHERE true` successfully.
