### ISSUE TITLE
The time field of point

### ISSUE THREAD

**Issue by vicanso** [influxdata/influxdb#7769]
Some time get the point from influxdb, the time field is '2016-12-28T11:30:55.80327349Z'. The length of it is 29. normally the length should be 30(ns). Is it a bug?

**Comment by mark-rushakoff** [comment]
Not a bug, see https://github.com/influxdata/influxdb/issues/2977.

Likewise, the [Go documentation example for formatting time](https://golang.org/pkg/time/#example_Time_Format) explains that trailing zeros will be dropped when formatting nanoseconds in RFC3339.

**Comment by dangerrockstar** [comment]
how to we drop Zero 
my query:
"select count(quantity) from test group by time" 
result:
             2017-07-21 00:00:00+00:00     64
             2017-07-22 00:00:00+00:00      **0**
             2017-07-23 00:00:00+00:00      **0**
             2017-07-24 00:00:00+00:00     57
             2017-07-25 00:00:00+00:00     86
