### ISSUE TITLE
Upcoming breaking changes to zap logging library

### ISSUE THREAD

**Issue by akshayjshah** [influxdata/influxdb#7770]
### Feature Request

__Proposal:__ I'm the primary author of [zap](github.com/uber-go/zap), the high-performance logging library that InfluxDB uses. I'm so, so jazzed that y'all are using my little project, especially since I've been following Influx for a long time! However, I'm planning quite a few breaking changes before the upcoming stable release of version 1.0 (mostly around logger construction, not the logger interface itself). I'd like to update all of InfluxDB's use of zap as soon as we land the breaking changes.

__Current behavior:__ If someone doesn't do this, you'll have one painful upgrade. 1.0 should land sometime in January.

__Desired behavior:__ I :heart: Influx, so I'd like to do the upgrade for you. Cool?

__Use case:__ N/A

Perhaps @jsternberg is the right person for this?

**Comment by jsternberg** [comment]
Works for me! Feel free to send me any messages if you need any help. We pin our dependencies so we will likely use the pre-1.0 zap library for our next release, but we'll have your changes land in master when master switches to the next version.

For dependencies, we use a custom tool made by a person on our team called [gdm](https://github.com/sparrc/gdm). To upgrade the pinned dependency, you just need to do this:

```bash
$ gdm restore
$ cd $GOPATH/src/go.uber.org/zap
$ git checkout master
$ cd -
$ gdm save
```

Then verify the `Godeps` file only updated the dependencies you were looking for. I know zap has a dependency on `go.uber.org/atomic` too so you might need to update that to the master branch too.

**Comment by mark-rushakoff** [comment]
If this is going to touch all of the `WithLogger` methods, it would be great if they could all get renamed to perhaps `SetLogger` instead.

**Comment by jsternberg** [comment]
The reason why I didn't use `SetLogger` is because the code isn't really setting the logger. It's modifying a parent logger and using its own sublogger. At least that's what my rationale was.

**Comment by nathanielc** [comment]
@akshayjshah I am starting the same standardization process for Kapacitor and would like to use the new 1.0 zap API. Any update on the 1.0 status of zap? It is close enough I can use a preview branch to get started on the Kapacitor side of things?

**Comment by BGodding** [comment]
Is this currently broken? Went to build latest for some benchmarking and was getting

```ERROR restoring some imports:
-   Error checking out rev 416270f07a9f696922512bb6487df46a2238f73d of repo /root/gocodez/src/go.uber.org/zap, exit status 128
```

Have never had an issues in the past. 

Building on RPi3 running Raspbian.

**Comment by jwilder** [comment]
@BGodding Yes.  See  https://github.com/influxdata/influxdb/pull/8029
