### ISSUE TITLE
How can I upgrade influxdb form 0.9.6 to 1.1?

### ISSUE THREAD

**Issue by zh4af** [influxdata/influxdb#7771]
I had used influxdb 0.9.6 serval month, now I want to upgrade it to 1.1 while reserving the metrics in influxdb.
I found this page [https://docs.influxdata.com/influxdb/v1.1/administration/upgrading/#upgrade-from-0-10-or-0-11-to-1-1](url), is it usefull to upgrade from 0.9 to 1.1?

**Comment by desa** [comment]
Upgrading from 0.9.6 to 1.1.1 is strongly encouraged. There have been major improvements for writes and queries. See [documentation on version difference](http://docs.influxdata.com/influxdb/v1.1/administration/previous_differences/). The upgrade process is a bit painful. You'll need to upgrade to 0.10 first then follow the [upgrade documentation](http://docs.influxdata.com/influxdb/v1.1/administration/upgrading/#upgrade-from-0-10-or-0-11-to-1-1).
