### ISSUE TITLE
group by time(1d) doesn't return last days of month

### ISSUE THREAD

**Issue by peterdk** [influxdata/influxdb#7774]
### Bug report

Every month I experience the same bug in Grafana, where in a last 30 days graph, the last days of the month don't have any data. It turns out that this is reproducible in influx cli, so it seems to be a bug in Influxdb.

![cutoff_graph](https://cloud.githubusercontent.com/assets/668007/21549612/a3e336fc-cdf3-11e6-87de-c5c71c71d9dd.png)

Issue: When selecting timerange of last 30 days from now, and when now is a day >= 28 of the month and now < 1d of next month, group by time(1d) doesn't return the last days of that month.

Examples:
(current date when querying was 29 December 2016)

Query that fails:
`select non_negative_derivative(mean("value"),1d) from "private.backend.ruby.preferred_apps.requests" where time > now() - 30d group by time(1d)`
Result:

> [..]
> 2016-12-24T00:00:00Z	4435.453819444447
> 2016-12-25T00:00:00Z	4004.844791666663
> 2016-12-26T00:00:00Z	3975.3388888888876
> 2016-12-27T00:00:00Z	4097.527199074073
> 

When changing the group_by to 12h instead of 1d, it suddenly returns some more data, but has a jump from 28T00 to 29T12.
Query:
`select non_negative_derivative(mean("value"),1d) from "private.backend.ruby.preferred_apps.requests" where time > now() - 30d group by time(12h)`
Result:

> [..]
> 2016-12-27T00:00:00Z	3835.6305555555446
> 2016-12-27T12:00:00Z	4376.256481481483
> 2016-12-28T00:00:00Z	3917.921296296292
> 2016-12-29T12:00:00Z	3299.215885279098
> 

Simpler query that also shows a jump from 28T00 to 29T12:
`select mean("value") from "private.backend.ruby.preferred_apps.requests" where time > now() - 30d group by time(1d)`
Result:

> [..]
> 2016-12-27T00:00:00Z	3835.6305555555446
> 2016-12-27T12:00:00Z	4376.256481481483
> 2016-12-28T00:00:00Z	3917.921296296292
> 2016-12-29T12:00:00Z	3270.104573170732
> 

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB 1.1.1, Ubuntu 14.04 64 bit

__Expected behavior:__ [What you expected to happen]
It should return data until the current day
__Actual behavior:__ [What actually happened]
It returns data up until the 28th of the month, when current date is between 28 and 31 of the month

**Comment by peterdk** [comment]
It looks to be maybe a bit simpler. It turns out that the counter is somehow reset for the last days, resulting in a derivative of -20.000 or so for a few days. Since I use non_negative_derivative, these 2 days don't show up. Still that's a weird issue, does Influxdb not store the counters when restarting?  I am not sure if this happening at the end of the month is a coincidence, or just caused by a upgrade to a newer version.

**Comment by desa** [comment]
@peterdk  I'm not sure what this means
>Still that's a weird issue, does Influxdb not store the counters when restarting? I am not sure if this happening at the end of the month is a coincidence, or just caused by a upgrade to a newer version.
What's the issue?

**Comment by peterdk** [comment]
@desa, the problem seems to be that the StatsD counters reset to 0 when Telegraf restarts. So it turns out to not really be a InfluxDB issue, but more of a issue how Telegraf handles restarts.
