### ISSUE TITLE
fatal error "out of memory" sometimes (mostly around 3:00am if this helps)

### ISSUE THREAD

**Issue by Apollon77** [influxdata/influxdb#7778]
I use most current Influxdb package on Ubuntu Xenial on ARMHF device (Cubietruck).

Now for the third time after working some days the influxd crashes at night (around 3am german winter time) with a fatal (see attachement) ... System has 2 GB memory and DB is around 1,3GB.

Influxdb automatically restarts itself.

Hope the stack trace helps

[Uploading influxd-fatal.txt…]()

**Comment by desa** [comment]
@Apollon77 What version of InfluxDB are you using? Also what kind of load is your system under?

**Comment by desa** [comment]
The link doesn't currently point to the stack trace.
