### ISSUE TITLE
Allow optional change of behavior when combining metrics with identical timestamps

### ISSUE THREAD

**Issue by Grant1219** [influxdata/influxdb#7779]
### Feature Request

__Proposal:__
Create an optional parameter for the HTTP API which allows for different behavior when combining two metrics with the same tags, fields, and timestamp.

__Current behavior:__
Currently InfluxDB will take the last metric and overwrite any data in previous metrics with the same tags, fields, and timestamp.

__Desired behavior:__
The ability to tell InfluxDB to sum numerical field types when two sent metrics contain the same timestamp. Default behavior should still overwrite.

__Use case:__
When using a lower precision (seconds, or minutes) it is currently very difficult to create a "counter" measurement because any metrics sent with identical timestamps are overwritten. Right now the options are increasing precision, attaching some sort of UUID tag to each metric sent, or using something like StatsD and forwarding to InfluxDB.

For example, if one wants to count user logins (success, failure) per second this feature would make it very easy to fire off metrics for measurement `user_auth` with tag `result=(success|failure)` and a `count=1` field which is later summed with other `user_auth` metrics that happened that second.

**Comment by jwilder** [comment]
This isn't possible without adding something like a `statsd` endpoint to InfluxDB.  Overwriting of duplicate points is a core piece of how the TSM engine works.
  
`telegraf` currently has a [statsd](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd) plugin that can be used as well before writing to influxdb.  This also might be more easily supported with a new [aggreagator plugin](https://github.com/influxdata/telegraf#aggregator-plugins) in `telegraf`.  cc @sparrc
