### ISSUE TITLE
Select multiple into - doesn't work

### ISSUE THREAD

**Issue by fornol74** [influxdata/influxdb#7782]
Hi, I am new here so would like to welcome everybody.

I starded using influx for my home automation project. Domoticz sends measurements to database and the main purpose is long term data collection and maybe some charts generation. Everything works on RPi 3.

Data is sent. Stored in separate measurements for each device. For instance: device_5_1.

Now I wanted to create separate measurements with calculated fields and, obviously, with differend retention period. Found a nice guide on influx web page and got stuck.

What I found:

"select min(value) from device_5_1" returns:

name: device_5_1
time		min
timestamp	19.6

"select min(value), max(value) from device_5_1" returns:

name: device_5_1
time		min		max
timestamp	19.6		65.4

"select min(value) as device_5_1_min , max(value) as device_5_1_max from device_5_1" returns:

name: device_5_1
time		device_5_1_min		device_5_1_max
timestamp	19.6			65.4

"select min(value) as device_5_1_min into test from device_5_1" creates new measurement test with content:
name: test
time		device_5_1_min
timestamp	19.6

And now:
"select min(value) as device_5_1_min , max(value) as device_5_1_max into test from device_5_1" returns no error but no measurement is created. (Previous measurement was dropped if anybody asks.)

Above select command is basically the same as the one found on influxdb web page with downsampling guide (with obvious difference that I am working with default retention policy for test purposes). So, I suppose is should be working - somehow is not.
I tested this on influxdb 1.0 and confirmed on 1.1.
Tested using web browser and command line - no change.
Internet search did not help.

Is this a bug? Or maybe this is normal, intended behavior (what I doubt since this is what I found in a downsampling guide). Or, maybe, simply I am missing something in my command.

If anybody asks, I would like to store min, max and mean values calculated from every device in one measurement. For clarity purposes and my sanity - typing separate commands to create separate measurements for multiple devices and later manage that ...

Any explanation/help appreciated.

**Comment by jwilder** [comment]
I can't seem to reproduce the problem. 

When I try:
> And now:
"select min(value) as device_5_1_min , max(value) as device_5_1_max into test from device_5_1" returns no error but no measurement is created. (Previous measurement was dropped if anybody asks.)

I have a new measurement created.

One thing that might be causing you issues is the timestamp is `0` when you use multiple selectors:

```
> select min(value) as device_5_1_min , max(value) as device_5_1_max from device_5_1
name: device_5_1
time device_5_1_min device_5_1_max
---- -------------- --------------
0    1              10

> select min(value) as device_5_1_min from device_5_1
name: device_5_1
time                device_5_1_min
----                --------------
1483565382464814098 1
```

With multiple selectors in this case, it appears that only one point is ever created at timestamp `0`.

**Comment by fornol74** [comment]
Hm, I am able to replicate.

Now I have three databases created:
- main one: domoticz
- second  one to store downsampled data: domoticz_10y
- third one for test pursposes: domoticz_test

Additional retention policy was created on all of them:
CREATE RETENTION POLICY rp_1h ON domoticz DURATION 1h REPLICATION 1
CREATE RETENTION POLICY rp_1h ON domoticz_10y DURATION 1h REPLICATION 1
CREATE RETENTION POLICY rp_1h ON domoticz_test DURATION 1h REPLICATION 1

Additional continuous queries were created also:
ON domoticz BEGIN SELECT min(value) as dev_5_1_min, max(value) as dev_5_1_max INTO domoticz.rp_1h.dev_5_1_test FROM domoticz.rp_7_days.device_5_1 GROUP BY time(5m)

ON domoticz BEGIN SELECT min(value) as dev_5_1_min, max(value) as dev_5_1_max INTO domoticz_10y.rp_1h.dev_5_1_test FROM domoticz.rp_7_days.device_5_1 GROUP BY time(5m)

ON domoticz BEGIN SELECT min(value) as dev_5_1_min, max(value) as dev_5_1_max INTO domoticz_test.rp_1h.dev_5_1_test FROM domoticz.rp_7_days.device_5_1 GROUP BY time(5m)

After 5 minutes of waiting resut is:
Measurement dev_5_1_test was created in domoticz database
Measurement dev_5_1_test was created in domoticz_10y database
Measurement dev_5_1_test was created in domoticz_test database

Below screen shots of select command after some time:

domoticz database
![image](https://cloud.githubusercontent.com/assets/24889864/21718916/e32e3f46-d41a-11e6-9351-7a54d8bdf161.png)

domoticz_10y database
![image](https://cloud.githubusercontent.com/assets/24889864/21718942/0c4f18b4-d41b-11e6-9706-637b6ee0b016.png)

domoticz_test database
![image](https://cloud.githubusercontent.com/assets/24889864/21718952/2361daaa-d41b-11e6-9690-deef6926d0b0.png)

It seems that engine has some problems with populating measurement with data when multiple selector is used (single selection works fine as far as I remember) and destination is not a default retention policy.

As presented above I worked around my problem by creating second database, with default, longer retention policy to store downsampled data. However, I am still pretty sure that instructions in downsampling guide will not work.
