### ISSUE TITLE
influxdb 1.1.1 did not build on Mac 10.12.1 (16B2657)

### ISSUE THREAD

**Issue by xing-kenny** [influxdata/influxdb#7783]
when exec flowing to install influxdb 1.1.1

    brew update
    brew install influxdb

error message like these...

        ==> Cloning https://github.com/influxdata/influxdb.git
	Updating /Users/kenny/Library/Caches/Homebrew/influxdb--git
	git config remote.origin.url https://github.com/influxdata/influxdb.git
	git config remote.origin.fetch +refs/tags/v1.1.1:refs/tags/v1.1.1
	==> Checking out tag v1.1.1
	git checkout -f v1.1.1 --
	HEAD is now at e47cf1f... Update 1.1.1 release date
	git reset --hard v1.1.1
	HEAD is now at e47cf1f Update 1.1.1 release date
	==> gdm restore
	======= Go Dependency Manager =======
	= working dir: /private/tmp/influxdb-20170103-11251-5ngqod/src/github.com/influxdata/influxdb
	= GOPATH:      /private/tmp/influxdb-20170103-11251-5ngqod
	=====================================
	Error getting VCS info for golang.org/x/crypto

	==> Formula
	Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/influxdb.rb
	==> Configuration
	HOMEBREW_VERSION: 1.1.2
	ORIGIN: https://github.com/Homebrew/brew
	HEAD: 0f529dae1043639058130092cf35e68d18907cb8
	Last commit: 5 weeks ago
	Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
	Core tap HEAD: 193111ae961a45e6445a359f7ebbcf8ad9e78a06
	Core tap last commit: 38 minutes ago
	HOMEBREW_PREFIX: /usr/local
	HOMEBREW_REPOSITORY: /usr/local/Homebrew
	HOMEBREW_CELLAR: /usr/local/Cellar
	HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
	CPU: quad-core 64-bit haswell
	Homebrew Ruby: 2.0.0-p648
	Clang: 8.0 build 800
	Git: 2.9.3 => /Library/Developer/CommandLineTools/usr/bin/git
	Perl: /usr/bin/perl
	Python: /usr/bin/python
	Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	Java: 1.8.0_111
	macOS: 10.12.1-x86_64
	Xcode: N/A
	CLT: 8.1.0.0.1.1476494586
	X11: N/A
	==> ENV
	HOMEBREW_CC: clang
	HOMEBREW_CXX: clang++
	MAKEFLAGS: -j4
	CMAKE_PREFIX_PATH: /usr/local
	CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
	CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
	PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
	PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/gdm/bin:/usr/local/opt/go/bin:/usr/bin:/bin:/usr/sbin:/sbin

	Error: influxdb 1.1.1 did not build

**Comment by rossmcdonald** [comment]
@xing-kenny Does the issue persist after multiple runs? It looks like it's having issues pulling the git information from golang.org/x/crypto, so make sure you have an active Internet connection while the build is running.

**Comment by rossmcdonald** [comment]
@xing-kenny Are you still seeing this failure, or can this issue be closed?

**Comment by superkully** [comment]
This worked fine for me on two 10.12.1 boxes. Close?
