### ISSUE TITLE
[feature request] Support a generic SHOW RETENTION POLICIES query

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#7790]
### Feature Request

__Proposal:__ 

Currently `SHOW RETENTION POLICIES` requires a database parameter in order to be run. It would be great if `SHOW RETENTION POLICIES` (without a database specified) would show the RP's for all databases on the instance.

__Current behavior:__ 

Without a database name, an error is thrown:

```
> show retention policies
ERR: database name required
```

So to list out the RP for every database, you have to collect the DB names first and then iterate over each one.

```
> show retention policies on _internal
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
monitor 168h0m0s 24h0m0s            1        true
```

__Desired behavior:__ 

If no DB name is specified, it will show all RP's for all databases

```
> show retention policies
db        name    duration shardGroupDuration replicaN default
--        ----    -------- ------------------ -------- -------
_internal monitor 168h0m0s 24h0m0s            1        true

....
```

__Use case:__ 

The current functionality is a pain to deal with if you need to list out all retention policies.

**Comment by marcvandermeiren** [comment]
as a workaround on Linux you can list all retention policies as follows  : 

for i in $(influx -execute "show databases" -format csv|grep databases|cut -d',' -f2)
do
 echo $i
 influx -database $i -execute "show retention policies"
done
