### ISSUE TITLE
the influxdb process has "fatal error: runtime: cannot allocate memory" error

### ISSUE THREAD

**Issue by zhu312542860** [influxdata/influxdb#7791]
server info: 
server memory is 64gb
cpu is 12 core.
influxdb version 1.0

my influxdb process often crash with the same error "fatal error: runtime: cannot allocate memory".even i upgrade the influxdb version,the error still appear.

above is a little influxdb error log:
```
[tsm1] 2017/01/05 10:42:12 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000304-000000007.tsm (#3)
[tsm1] 2017/01/05 10:42:12 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000336-000000005.tsm (#4)
[tsm1] 2017/01/05 10:42:12 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000340-000000003.tsm (#5)
[tsm1] 2017/01/05 10:42:12 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000344-000000003.tsm (#6)
[tsm1] 2017/01/05 10:42:12 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000348-000000003.tsm (#7)
[tsm1] 2017/01/05 10:42:12 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000349-000000001.tsm (#8)
[tsm1] 2017/01/05 10:42:12 aborted full compaction group (0). compaction in progress
[tsm1] 2017/01/05 10:42:13 beginning full compaction of group 0, 9 TSM files
[tsm1] 2017/01/05 10:42:13 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000128-000000006.tsm (#0)
[tsm1] 2017/01/05 10:42:13 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000128-000000007.tsm (#1)
[tsm1] 2017/01/05 10:42:13 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000304-000000006.tsm (#2)
[tsm1] 2017/01/05 10:42:13 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000304-000000007.tsm (#3)
[tsm1] 2017/01/05 10:42:13 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000336-000000005.tsm (#4)
[tsm1] 2017/01/05 10:42:13 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000340-000000003.tsm (#5)
[tsm1] 2017/01/05 10:42:13 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000344-000000003.tsm (#6)
[tsm1] 2017/01/05 10:42:13 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000348-000000003.tsm (#7)
[tsm1] 2017/01/05 10:42:13 compacting full group (0) /data/influxdb/data/dcos/autogen/34/000000349-000000001.tsm (#8)
fatal error: runtime: cannot allocate memory

runtime stack:
runtime.throw(0xd5d880, 0x1f)
        /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.persistentalloc1(0x4000, 0x8, 0x116b498, 0xcbcfe81f50)
        /usr/local/go/src/runtime/malloc.go:937 +0x2e3
runtime.persistentalloc.func1()
        /usr/local/go/src/runtime/malloc.go:890 +0x3b
runtime.systemstack(0x7f602b7fdbc0)
        /usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.persistentalloc(0x4000, 0x0, 0x116b498, 0x1)
        /usr/local/go/src/runtime/malloc.go:891 +0x58
runtime.(*fixalloc).alloc(0x1153700, 0x7f60297250e0)
        /usr/local/go/src/runtime/mfixalloc.go:67 +0xee
runtime.(*mheap).allocSpanLocked(0x11506e0, 0x1, 0x7f6029724e10)
        /usr/local/go/src/runtime/mheap.go:582 +0x195
runtime.(*mheap).alloc_m(0x11506e0, 0x1, 0xb, 0x7f6029724e10)
        /usr/local/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7f602b7fdd00)
        /usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x11506e0, 0x1, 0x1000000000b, 0x412944)
```

**Comment by jwilder** [comment]
Can you attach the full stack trace?

**Comment by zhu312542860** [comment]
@jwilder thanks for the answer.I will upgrading the influxdb version to 1.1.1.Now,my influxdb config is like this:
## Welcome to the InfluxDB configuration file.

# Once every 24 hours InfluxDB will report usage data to usage.influxdata.com
# The data includes a random ID, os, arch, version, the number of series and other
# usage data. No data from user databases is ever transmitted.
# Change this option to true to disable reporting.
reporting-disabled = true

# we'll try to get the hostname automatically, but if it the os returns something
# that isn't resolvable by other servers in the cluster, use this option to
# manually set the hostname
# hostname = "localhost"

###
### [meta]
###
### Controls the parameters for the Raft consensus group that stores metadata
### about the InfluxDB cluster.
###

[meta]
  # Where the metadata/raft database is stored
  dir = "/data/influxdb/meta"

  retention-autocreate = true

  # If log messages are printed for the meta service
  logging-enabled = true
  pprof-enabled = false

  # The default duration for leases.
  lease-duration = "1m0s"

###
### [data]
###
### Controls where the actual shard data for InfluxDB lives and how it is
### flushed from the WAL. "dir" may need to be changed to a suitable place
### for your system, but the WAL settings are an advanced configuration. The
### defaults should work for most systems.
###

[data]
  # Controls if this node holds time series data shards in the cluster
  enabled = true

  dir = "/data/influxdb/data"

  # These are the WAL settings for the storage engine >= 0.9.3
  wal-dir = "/data/influxdb/wal"
  wal-logging-enabled = false

  # Trace logging provides more verbose output around the tsm engine. Turning
  # this on can provide more useful output for debugging tsm engine issues.
  trace-logging-enabled = false

  # Whether queries should be logged before execution. Very useful for troubleshooting, but will
  # log any sensitive data contained within a query.
  query-log-enabled = false

  # Settings for the TSM engine

  # CacheMaxMemorySize is the maximum size a shard's cache can
  # reach before it starts rejecting writes.
  # cache-max-memory-size = 524288000

  # CacheSnapshotMemorySize is the size at which the engine will
  # snapshot the cache and write it to a TSM file, freeing up memory
  # cache-snapshot-memory-size = 26214400

  # CacheSnapshotWriteColdDuration is the length of time at
  # which the engine will snapshot the cache and write it to
  # a new TSM file if the shard hasn't received writes or deletes
  # cache-snapshot-write-cold-duration = "1h"

  # MinCompactionFileCount is the minimum number of TSM files
  # that need to exist before a compaction cycle will run
  # compact-min-file-count = 3

  # CompactFullWriteColdDuration is the duration at which the engine
  # will compact all TSM files in a shard if it hasn't received a
  # write or delete
  # compact-full-write-cold-duration = "24h"

  # MaxPointsPerBlock is the maximum number of points in an encoded
  # block in a TSM file. Larger numbers may yield better compression
  # but could incur a performance penalty when querying
  # max-points-per-block = 1000

###
### [coordinator]
###
### Controls the clustering service configuration.
###

[coordinator]
  write-timeout = "10s"
  max-concurrent-queries = 0
  query-timeout = "0"
  log-queries-after = "0"
  max-select-point = 0
  max-select-series = 0
  max-select-buckets = 0

###
### [retention]
###
### Controls the enforcement of retention policies for evicting old data.
###

[retention]
  enabled = true
  check-interval = "30m"

###
### [shard-precreation]
###
### Controls the precreation of shards, so they are available before data arrives.
### Only shards that, after creation, will have both a start- and end-time in the
### future, will ever be created. Shards are never precreated that would be wholly
### or partially in the past.

[shard-precreation]
  enabled = true
  check-interval = "10m"
  advance-period = "30m"

###
### Controls the system self-monitoring, statistics and diagnostics.
###
### The internal database for monitoring data is created automatically if
### if it does not already exist. The target retention within this database
### is called 'monitor' and is also created with a retention period of 7 days
### and a replication factor of 1, if it does not exist. In all cases the
### this retention policy is configured as the default for the database.

[monitor]
  store-enabled = true # Whether to record statistics internally.
  store-database = "_internal" # The destination database for recorded statistics
  store-interval = "10s" # The interval at which to record statistics

###
### [admin]
###
### Controls the availability of the built-in, web-based admin interface. If HTTPS is
### enabled for the admin interface, HTTPS must also be enabled on the [http] service.
###

[admin]
  enabled = true
  bind-address = ":8083"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

###
### [http]
###
### Controls how the HTTP endpoints are configured. These are the primary
### mechanism for getting data into and out of InfluxDB.
###

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = false
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
  ### Use a separate private key location.
  # https-private-key = ""
  max-row-limit = 10000
  realm = "InfluxDB"

###
### [subsciber]
###
### Controls the subscriptions, which can be used to fork a copy of all data
### received by the InfluxDB host.
###

[subsciber]
  enabled = true
  http-timeout = "30s"


###
### [[graphite]]
###
### Controls one or many listeners for Graphite data.
###

[[graphite]]
  enabled = false
  # database = "graphite"
  # bind-address = ":2003"
  # protocol = "tcp"
  # consistency-level = "one"

  # These next lines control how batching works. You should have this enabled
  # otherwise you could get dropped metrics or poor performance. Batching
  # will buffer points in memory if you have many coming in.

  # batch-size = 5000 # will flush if this many points get buffered
  # batch-pending = 10 # number of batches that may be pending in memory
  # batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit
  # udp-read-buffer = 0 # UDP Read buffer size, 0 means OS default. UDP listener will fail if set above OS max.

  ### This string joins multiple matching 'measurement' values providing more control over the final measurement name.
  # separator = "."

  ### Default tags that will be added to all metrics.  These can be overridden at the template level
  ### or by tags extracted from metric
  # tags = ["region=us-east", "zone=1c"]

  ### Each template line requires a template pattern.  It can have an optional
  ### filter before the template and separated by spaces.  It can also have optional extra
  ### tags following the template.  Multiple tags should be separated by commas and no spaces
  ### similar to the line protocol format.  There can be only one default template.
  # templates = [
  #   "*.app env.service.resource.measurement",
  #   # Default template
  #   "server.*",
  # ]

###
### [collectd]
###
### Controls one or many listeners for collectd data.
###

[[collectd]]
  enabled = false
  # bind-address = ""
  # database = ""
  # typesdb = ""

  # These next lines control how batching works. You should have this enabled
  # otherwise you could get dropped metrics or poor performance. Batching
  # will buffer points in memory if you have many coming in.

  # batch-size = 1000 # will flush if this many points get buffered
  # batch-pending = 5 # number of batches that may be pending in memory
  # batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit
  # read-buffer = 0 # UDP Read buffer size, 0 means OS default. UDP listener will fail if set above OS max.

###
### [opentsdb]
###
### Controls one or many listeners for OpenTSDB data.
###

[[opentsdb]]
  enabled = false
  # bind-address = ":4242"
  # database = "opentsdb"
  # retention-policy = ""
  # consistency-level = "one"
  # tls-enabled = false
  # certificate= ""
  # log-point-errors = true # Log an error for every malformed point.

  # These next lines control how batching works. You should have this enabled
  # otherwise you could get dropped metrics or poor performance. Only points
  # metrics received over the telnet protocol undergo batching.

  # batch-size = 1000 # will flush if this many points get buffered
  # batch-pending = 5 # number of batches that may be pending in memory
  # batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit

###
### [[udp]]
###
### Controls the listeners for InfluxDB line protocol data via UDP.
###

[[udp]]
  enabled = false
  # bind-address = ""
  # database = "udp"
  # retention-policy = ""

  # These next lines control how batching works. You should have this enabled
  # otherwise you could get dropped metrics or poor performance. Batching
  # will buffer points in memory if you have many coming in.

  # batch-size = 1000 # will flush if this many points get buffered
  # batch-pending = 5 # number of batches that may be pending in memory
  # batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit
  # read-buffer = 0 # UDP Read buffer size, 0 means OS default. UDP listener will fail if set above OS max.

  # set the expected UDP payload size; lower values tend to yield better performance, default is max UDP size 65536
  # udp-payload-size = 65536

###
### [continuous_queries]
###
### Controls how continuous queries are run within InfluxDB.
###

[continuous_queries]
  log-enabled = true
  enabled = true
  # run-interval = "1s" # interval for how often continuous queries will be checked if they need to run


if there is a better suggestion to modify the influxdb config
