### ISSUE TITLE
[feature request] Add DROP SHARDS query for bulk removal of shards

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#7794]
### Feature Request

__Current behavior:__

Currently attempting to drop multiple shards at once is a bit of a pain, as you can only drop one shard at a time (meaning to drop 10 shards, you must issue 10 `DROP SHARD` queries).

```
DROP SHARD 1
DROP SHARD 2
DROP SHARD 3
...
```

__Desired behavior:__

It would be great if you could drop multiple shards at once via `DROP SHARDS` query that takes optional database and time parameters. For example:

```
DROP SHARDS WHERE database = 'metrics' AND start_time < '2011-10-28T00:00:00Z'
```

Which would drop all shards belonging to the `metrics` database that have start_time's before October 28th, 2011. Or:

```
DROP SHARDS WHERE start_time < '2011-10-28T00:00:00Z'
```

Which would drop all shards (from all databases) that have start_time's before October 28th, 2011.

__Use case:__

It's a pain to drop a lot of shards, especially if they were created in error due to an incorrect write precision (writing `s` timestamps with `ns` precision). This enhancement would make it much easier to drop multiple shards at once.

**Comment by gigake** [comment]
I also need this functionality! :-)
