### ISSUE TITLE
not able to execute a script

### ISSUE THREAD

**Issue by pranabpal** [influxdata/influxdb#7796]
I am using the version:
Connected to http://localhost:8086 version 1.1.1
InfluxDB shell version: 1.1.1

I cannot able to execute a script and insert data in table in influx db. can anyone help how to achieve this?

But I can insert data by executing statement from windows command prompt.

e.g. insert disk_free,hostname=server01,disk_type=SSD value=442221834240i

Not able to execute this statement in windows command prompt:
>influx -import -path=datarrr.txt -precision=s

Throwing error:
D:\Prev_Machine\Pranab\Daimler\Xtech\software\influxdb-1.1.1_windows_amd64\influ
xdb-1.1.1-1>influx -import -path=datarrr.txt -precision=s
2017/01/06 11:19:44 error: error parsing query: found treasures, expected SELECT
, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1
2017/01/06 11:19:44 error: error parsing query: found treasures, expected SELECT
, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1
2017/01/06 11:19:44 error: error parsing query: found treasures, expected SELECT
, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1
2017/01/06 11:19:44 error: error parsing query: found treasures, expected SELECT
, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1
2017/01/06 11:19:44 error: error parsing query: found treasures, expected SELECT
, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1
2017/01/06 11:19:44 error writing batch:  {"error":"database is required"}

**Comment by jwilder** [comment]
`-import` is used to replay an export generated from an 0.8 export.  If you want to create one manually, the format can be found [here](https://github.com/influxdata/influxdb/tree/master/importer).
