### ISSUE TITLE
Collectd SecurityLevel Encrypt leads to parse error

### ISSUE THREAD

**Issue by lz1irq** [influxdata/influxdb#7797]
### Bug report

__System info:__  InfluxDB 1.1.1-1 from the influxdata.com/debian repository, running on Debian Jessie

__Steps to reproduce:__

1. Install `influxdb` from the above-mentioned repo and `collectd-core` from the official Debian repositories.
2. Configure collectd to send encrypted packets to influxdb (see config below)
3. Configure influxdb collectd module to only accept encrypted messages and give it an auth file (see config below)
4. Set UDP buffer sizes [according to instructions](https://github.com/influxdata/influxdb/blob/77e2c80a4f220770a2da00bc1ff048c762f8cc66/services/udp/README.md#a-note-on-udpip-os-buffer-sizes).
5. Restart collectd and influxdb to apply the new configuration.

__Expected behavior:__ InfluxDB should be able to decrypt the packets and log the data from collectd.

__Actual behavior:__ No data is logged. There is a "Collectd parse error: Unsupported packet" message in influxdb's log.

__Additional info:__  [Gist including collectd's configuration, the collectd plugin configuration for influx, and the auth file](https://gist.github.com/lz1irq/13aa16e1e88e02fd2b4b0a6bf89f804b)

I also noticed people are complaining about this in #4986.

**Comment by jwilder** [comment]
Encrypted packets are not supported in 1.1.  They are only supported in master/nightlies currently and will be in the next release.  See #7435
