### ISSUE TITLE
Piping insert statement into influx CLI results in error

### ISSUE THREAD

**Issue by pasamio** [influxdata/influxdb#7805]
### Bug report

__System info:__ InfluxDB 1.1.1, macOS Sierra 10.12.1

__Steps to reproduce:__

```
$ echo 'insert size,podcast=Catalyst value=180' | /usr/local/bin/influx --database podcasts
ERR: error parsing query: found INSERT, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1
error parsing query: found INSERT, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1
$ /usr/local/bin/influx --database podcasts
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version v1.1.1
InfluxDB shell version: v1.1.1
> insert size,podcast=Catalyst value=180
>
```

__Expected behavior:__ The piped insert statement should work. This used to work in 0.10.x series.

__Actual behavior:__ Error about not expecting an insert statement. The command works when influx CLI is run interactively.

__Additional info:__ Following "writing data to InfluxDB with insert" section from manual here: https://docs.influxdata.com/influxdb/v1.1/tools/shell/#write-data-to-influxdb-with-insert

**Comment by e-dard** [comment]
@pasamio you can achieve this with the `-execute` flag.

```
influx -database podcasts -execute 'insert size,podcast=Catalyst value=180'
```

**Comment by pasamio** [comment]
Ugh, so I'm going to have to wrap it all in xargs to pipe in the entries I have now.

Any idea why the behaviour changed between versions?

**Comment by mark-rushakoff** [comment]
Looks like the behavior was introduced [here](https://github.com/influxdata/influxdb/commit/2f5f9957828c09e73bbc725729f7da9cd66633be#diff-0fd886f0e523c3c78e745df868bf1076R93), and currently located [here](https://github.com/influxdata/influxdb/blob/6768c6ed3bba76d8b2098fd1b89c08f7268f666e/cmd/influx/cli/cli.go#L160), in an effort to fix something with piping in files but getting treated as interactive input. @jsternberg?

@pasamio probably the simplest way to achieve writing a point from the command line is [via curl](https://docs.influxdata.com/influxdb/v1.1/guides/writing_data/#writing-data-using-the-http-api). Batching your points is the preferable approach, but if you really need to write a single point at a time, curl's fine for that too.

**Comment by pasamio** [comment]
I guess I was relying on the interactive input behaviour consistent with most other tools though do you have documentation on how piping in is supposed to work?

What I'm doing here is pulling in a count of files in a bunch of directories that store my podcasts and I'm just use some simple shell scripting and a sed statement to turn that into the INSERT statement so that I can track how I do over time (poorly generally). The CLI seemed to support this really nicely and it's a shame that got broken. I might try spilling to a file and using the import syntax instead.

**Comment by mark-rushakoff** [comment]
@pasamio it doesn't look like our docs currently have anything to say about piping to the `influx` CLI.

If I was right about when the bug was introduced, you should be able to revert to the 1.0 version of the `influx` CLI for the previous behavior when piping input; or, again, curl should work just as well with:

```
curl http://localhost:8086/write?db=podcasts --data-binary "$(your_script.sh)"
```

just exclude the `insert` word from the script output when using the `/write` endpoint directly.

**Comment by pasamio** [comment]
Ok, I'll give the curl a shot tonight. Thanks for the help :)

It'd be good to have some clear documentation on what the CLI is expected to do with piped data and it'd be nice if you could return some of the support for piping in queries (even supporting just the line format would be cool but I tried that and it didn't seem to work either).

**Comment by bslade** [comment]
This issue was discussed in [5078](https://github.com/influxdata/influxdb/issues/5078).

> What is most likely happening here is that INSERT is not a real keyword. Instead it is intercepted by the CLI and converted into a write query. The CLI code should be updated to check for that in non-interactive mode.
