### ISSUE TITLE
the kill query doesn't work in 1.0.2 version

### ISSUE THREAD

**Issue by pingliu** [influxdata/influxdb#7811]
I use kill query for test.
when I run:
```
select value from "cpu.clock"
```
then run:
```
kill query 187
```
the query is killed ,but the memory of servers still rise up .
![image](https://cloud.githubusercontent.com/assets/6415493/21804948/a1bf6904-d76c-11e6-803f-0122aa66016a.png)

**Comment by desa** [comment]
@pingliu can you verify that this is still an issue with `1.1.1`.

**Comment by pingliu** [comment]
@desa  I test it with 1.1.1. 
it is still issue with 1.1.1.

![image](https://cloud.githubusercontent.com/assets/6415493/22005920/341182e4-dca2-11e6-8aff-8d482ca699ca.png)
![image](https://cloud.githubusercontent.com/assets/6415493/22005932/428312b6-dca2-11e6-8055-38c570140128.png)

**Comment by jwilder** [comment]
Fixed via #8158
