### ISSUE TITLE
Slow query performance when using offset and limit to page through results

### ISSUE THREAD

**Issue by pjmyburg** [influxdata/influxdb#7826]
### Bug report

__System info:__ 

InfluxDB 1.0.2, Amazon Linux AMI on EC2

__Steps to reproduce:__

1. Start with a clean database
2. Insert an hours worth of second resolution data
3. Query 1000 data points with offset 0 and the start time equal to the start time of the data
4. Query the same 1000 data points, but with a start time a few weeks or months earlier and offset equal to the number of seconds difference between the new start time and the start time in 3 above

__Expected behavior:__

I expect the above offset to have minimal impact on query performance on an empty DB.
I could sort of understand slower performance on the second query on a full DB, but in this case the DB has no data other than the hour being queried for.

__Actual behavior:__

In my case, the first query responds in 200ms (over http).
The second query, however, responds in 13932ms with exactly the same result.

**Comment by pjmyburg** [comment]
Just to add - this situation is aggravated on a full DB.  Querying for data with the start and end time a day apart is orders of magnitude faster than querying for the same data with the start and end times months apart with an applicable offset.

**Comment by catap** [comment]
I can confirm this bug on 1.2.0

**Comment by rozpuszczalny** [comment]
I'm also getting high response time when using large offset

**Comment by dandv** [comment]
Same here. The same query for 1000 points with OFFSET 0 is nearly instant, but with offset 2000123 takes 30+ seconds. DO SSD instance with 1 CPU and 512MB RAM.

**Comment by dandv** [comment]
Another report: https://community.influxdata.com/t/selecting-data-with-offset-results-in-slow-query/8856

**Comment by dandv** [comment]
Still seeing this with v1.7.7 on XFS. Offsets in the millions take MINUTES to return data.

**Comment by dandv** [comment]
Is anyone else currently seeing this?

**Comment by dandv** [comment]
Unstale
