### ISSUE TITLE
Performance deterioration after upgrading to 1.1

### ISSUE THREAD

**Issue by abadyan-vonage** [influxdata/influxdb#7827]
### Bug report

InfluxDB 1.1, Centos7, hosted on EC2, c4.xlarge.
Write is done using HTTP.
Our current model includes about 30 databases with ~120 ops points written and 60 ops queries.
This is after limiting the number of connections to 300 because we had memory issues (We are reporting from about 450 servers once a minute).
Also we are using kapacitor that adds to the querying and writes and have Grafana querying the db.
Until a couple of days ago we were using 1.0 and decided to upgrade to 1.1 because of performance improvements.
Unfortunately, our performance seriously deteriorated:
![image](https://cloud.githubusercontent.com/assets/17905032/21886408/4ebfcfa6-d8c4-11e6-8ba4-63b0c0bddb54.png)

I don't have the performance dumps, I'm afraid, because I had to downgrade as this was a production issue, but I do have the data in the _internal db so if you want me to query something let me know.

**Comment by jwilder** [comment]
Could you share your `_internal` db?

**Comment by abadyan-vonage** [comment]
@jwilder the entire _internal db weighs 80MB when exported and after tar.gz.
I can upload it somewhere if you want, but let me know if it's relevant.

**Comment by abadyan-vonage** [comment]
I'm not sure the above pull request fixes the issue, as the number of series was pretty fixed:
![image](https://cloud.githubusercontent.com/assets/17905032/21961010/e0d626ee-db06-11e6-9da6-ec4726a6e5b8.png)
After the upgrade the number of series jumped up for some reason, but stayed pretty constant afterwards.
