### ISSUE TITLE
How can I delete the Tag Keys's value when there is no data 

### ISSUE THREAD

**Issue by Chentongxuedefanhua** [influxdata/influxdb#7833]
influxdb version 0.13
I get the data from k8s by heapster , and keep it for 30 days. Then i show the data by Grafana and filter by Tag keys value like this :
![1](https://cloud.githubusercontent.com/assets/18111540/21923785/f45a889c-d9b0-11e6-8fa4-28952da9e342.png)
the question is :some pod does not hava data ,so the grafana will be empty
how can i delete the Tag Keys's value when there is no data

**Comment by desa** [comment]
To reduce the noise on our issues, we ask that they be used for bug reports or feature requests. Can you please ask your question either on [StackOverflow](http://stackoverflow.com/) or our [mailing list](https://groups.google.com/forum/#!forum/influxdb)
