### ISSUE TITLE
very slow query performance ... influxdb unusable ???

### ISSUE THREAD

**Issue by play113** [influxdata/influxdb#7842]
- start with new db
- system: 32gb ram, 8core i7, ssd

where is the problem with this simple query ?
running time ~9min ... wow ...

$> time influx -database TestDB -execute 'select count(f1) from "TestMeas"'
name: TestMeas
time    count
----    -----
0       673734

real    0m0.641s
user    0m0.008s
sys     0m0.000s

$> time influx -database TestDB -execute 'select * from "TestMeas" WHERE gState>0 ORDER BY time LIMIT 10'
name: TestMeas
...
...
...

real    0m18.440s
user    0m0.004s
sys     0m0.004s

$> time influx -database TestDB -execute 'select * from "TestMeas" WHERE gState>0 ORDER BY time DESC LIMIT 10'
name: TestMeas
...
...
...

real    8m57.146s
user    0m0.000s
sys     0m0.008s

**Comment by mark-rushakoff** [comment]
@play113 Please fill out the [issue template](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md) and include a script to insert data that can reproduce the issue.

**Comment by play113** [comment]
#!/usr/bin/env perl

use strict;
use warnings;
use EV;
use AnyEvent;
use AnyEvent::Socket;
use AnyEvent::Handle;
use AnyEvent::InfluxDB;
use InfluxDB::LineProtocol qw(data2line);
use Data::Dumper;

my $db = AnyEvent::InfluxDB->new( server => 'http://localhost:8086' );

my $hdl = undef;
tcp_server undef, 8888, sub {
    my ($fh, $host, $port) = @_;
    $hdl = AnyEvent::Handle->new( fh => $fh );

    $hdl->push_read(
        line => sub {
            my (undef, $line) = @_;
            my ($device, $length, $gwStatus, $vbStatus, $vbSensor1stat, $vbSensor2stat, $vbSensor3stat,
                $u1eff, $u2eff, $u3eff, $i1eff, $i2eff, $i3eff, $pw1, $pw2, $pw3, $f1, $f2, $f3,
                $pf1, $pf2, $pf3, $u_ges, $i_ges, $pw_ges, $tms, $ts,
                $s1, $s2, $s3, $q1, $q2, $q3, $s_ges, $q_ges, $pf_ges, $crc) = split(/,\s*/,$line);
            $db->write(
                database    => 'TestDB',
                data    => [
                    data2line('TestMeas',
                        # values
                        {
                            gState      => sprintf("%032b", $gwStatus),
                            vbStatus_bin      => sprintf("%016b", $vbStatus),
                            vbS1StatusReg_bin => sprintf("%016b", $vbSensor1stat),
                            vbS2StatusReg_bin => sprintf("%016b", $vbSensor2stat),
                            vbS3StatusReg_bin => sprintf("%016b", $vbSensor3stat),
                            u1eff             => int($u1eff),
                            u2eff             => int($u2eff),
                            u3eff             => int($u3eff),
                            u_ges             => int($u_ges),
                            i1eff             => int($i1eff),
                            i2eff             => int($i2eff),
                            i3eff             => int($i3eff),
                            i_ges             => int($i_ges),
                            pw1               => int($pw1),
                            pw2               => int($pw2),
                            pw3               => int($pw3),
                            pw_ges            => int($pw_ges),
                            f1                => int($f1),
                            f2                => int($f2),
                            f3                => int($f3),
                            pf1               => sprintf("%.3f", $pf1),
                            pf2               => sprintf("%.3f", $pf2),
                            pf3               => sprintf("%.3f", $pf3),
                            pf_ges            => sprintf("%.3f", $pf_ges),
                            s1                => int($s1),
                            s2                => int($s2),
                            s3                => int($s3),
                            s_ges             => int($s_ges),
                            q1                => int($q1),
                            q2                => int($q2),
                            q3                => int($q3),
                            q_ges             => int($q_ges)
                        },
                        # tag keys
                        {
                            GATEWAY_NAME        => "TestGW1",
                            LOCATION_ShortName  => "TestLocation",
                            CONSUMER_ID         => "$device"
                        },
                        $ts
                    )
                ],
                # on_success  => sub { print "$line written\n"; },
                on_success  => sub { print "ok\n"; },
                on_error    => sub { print "$line error: @_\n"; },
            );
            $hdl->on_drain(
                sub {
                    $hdl->fh->close;
                    undef $hdl;
                }
            );
        },
    );
};

EV::run;
