### ISSUE TITLE
Keep Influx client in separate repository

### ISSUE THREAD

**Issue by retorquere** [influxdata/influxdb#7843]
When I execute `go get "github.com/influxdata/influxdb/client/v2"`, I get:

```
# cd .; git clone https://github.com/influxdata/influxdb /home/emiliano/go/src/github.com/influxdata/influxdb
Cloning into '/home/emiliano/go/src/github.com/influxdata/influxdb'...
fatal: unable to access 'https://github.com/influxdata/influxdb/': GnuTLS recv error (-54): Error in the pull function.
package github.com/influxdata/influxdb/client/v2: exit status 128
```

**Comment by retorquere** [comment]
OK, I've found part of the cause; the command to install the client pulls in the entire influxdb repo at 56MB of data rather than just the go client. Could the go client be split off to a separate repository?

**Comment by e-dard** [comment]
@retorquere Hi, this has been considered in the past and may even arrive in the future. I'm converting this issue to a feature request as I can't find an existing issue that requests this.

**Comment by jsternberg** [comment]
We have plans to create a new client. Some of that work has already begun at https://github.com/influxdata/influxdb-client. If you have the opportunity, please leave any feedback or requests for that new client in that repository.

Thanks.

**Comment by retorquere** [comment]
Is this client already usable? I'm open to use help test this.

**Comment by jsternberg** [comment]
It's experimental at the moment. If you're going to use it, you should vendor or version pin in some way because the API is likely going to change. It is usable for querying at the moment and I'm currently working on a write API.

**Comment by retorquere** [comment]
The write API is what I'm most interested in. I don't mind the API changing, the tool I'm building is under heavy change itself, so this would just fold in. But without write, I can't start using this.

**Comment by retorquere** [comment]
(BTW, I'm currently using raw line protocol for writes because the current v2 API was unusably slow for my use-case at least)

**Comment by jsternberg** [comment]
I have a PR up for an initial version of the write API for that new client in influxdata/influxdb-client#4. If you're interested, you can check out that PR and try using it. The API currently allows either writing directly with line protocol or having the protocol get encoded for you.

There's still more work to do to build convenience functions on top of it, but just having the PR gets a baseline to start the work at least.

**Comment by schmurfy** [comment]
I am curious as to why the client was moved into the influxdb repository in the first place as https://github.com/influxdata/influxdb-go shows, I am really not a big fan of the way go handles dependencies but in that case having to clone the full database repository to interface with it is totally silly, I would imagine you won't have to clone mariadb repository to request it, at least I hope xD
