### ISSUE TITLE
Golang client v2: how to insert nanosecond precision?

### ISSUE THREAD

**Issue by retorquere** [influxdata/influxdb#7844]
I already have a nanosecond precision timestamp, but `point, err := influx.NewPoint("accesspoint", tags, fields, t)` gives me `cannot use t (type int64) as type time.Time in argument to client.NewPoint`

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list.

Thanks.
