### ISSUE TITLE
Can't set influxd to run at boot

### ISSUE THREAD

**Issue by dandv** [influxdata/influxdb#7850]
### Bug report

__System info:__
Influx v1.1.1, Ubuntu 16.04
```sh
$ uname -a
Linux localhost 4.8.6-x86_64-linode78 #1 SMP Tue Nov 1 14:51:21 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
````

__Steps to reproduce:__

1. `systemctl enable influxd`

__Expected behavior:__ [What you expected to happen]
influxd is set to start at boot

__Actual behavior:__ [What actually happened]
> Failed to execute operation: Too many levels of symbolic links

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list.

Thanks.

**Comment by dandv** [comment]
Didn't get any help [on the group](https://groups.google.com/forum/#!searchin/influxdb/Too$20many$20levels$20of$20symbolic$20links%7Csort:relevance/influxdb/a5_v_s1rCGc/Gr0f6-riAwAJ).

The inability to set influx to run at boot is pretty critical IMO, to consider this a bug,

**Comment by dandv** [comment]
Still seeing this issue with Influx v1.4.2.

```sh
# uname -a
Linux localhost 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
