### ISSUE TITLE
CREATE DATABASE WITH can alter the default RP

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#7860]
### Bug report

Ubuntu 16.04, version 1.2~rc1

__Steps to reproduce:__

1. Create a database with a retention policy called `first`
```
> CREATE DATABASE "dataz" WITH NAME "first"

> SHOW RETENTION POLICIES ON "dataz"

name  duration shardGroupDuration replicaN default
----  -------- ------------------ -------- -------
first 0s       168h0m0s           1        true
```

2. Create the same database with a retention policy called `second`
```
> CREATE DATABASE "dataz" WITH NAME "second"

> SHOW RETENTION POLICIES ON "dataz"

name   duration shardGroupDuration replicaN default
----   -------- ------------------ -------- -------
first  0s       168h0m0s           1        false
second 0s       168h0m0s           1        true
```

__Expected behavior:__

I'd expect this to return an error like it did in 1.1.

__Actual behavior:__ 

The system created the new RP and made it the default RP.

**Comment by e-dard** [comment]
I looked at this with @rkuchan today and it does seem like a regression, probably introduced in https://github.com/influxdata/influxdb/pull/7449?

```
1.1

> create database db7 with name rp0
> create database db7 with name rp1
ERR: retention policy conflicts with an existing policy
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
>
```

But with `1.2` there is no error and both retention policies are created.
