### ISSUE TITLE
[Feature request] Support GROUP BY time(AUTO)

### ISSUE THREAD

**Issue by wei-hai** [influxdata/influxdb#7873]
__Proposal:__
adjust time interval based on time window in GROUP BY clause
__Current behavior:__
time interval must be fixed value
__Desired behavior:__
Suppose the query is `select value from measurementA where TIME_WINDOW group by time(AUTO)`, influxdb shall detect the TIME_WINDOW and smartly adjust the time interval, for example

TIME_WINDOW  |  AUTO
----------------|-------
<= 6 hours | 1m
<= 12 hours | 5m
<= 24 hours | 10m
<= 3 days | 30m
<= 7 days | 1h
<= 30 days | 1d

__Use case:__
This feature will be helpful when working with visualization tool such as Grafana.

**Comment by jsternberg** [comment]
This seems similar to #7198.
