### ISSUE TITLE
SELECT INTO : panic:interface conversion

### ISSUE THREAD

**Issue by max3163** [influxdata/influxdb#7878]
Hello, 

I try to transfer data with select into query from a selected time range and the query crash :

```
Server returned error: SELECT * INTO qualif.one_month.process FROM qualif."default".process WHERE application::tag =~ /achille/ AND time::float > '2016-05-23T15:10:18+02:00' AND time::float < '2016-05-23T15:22:23+02:00' GROUP BY * [panic:interface conversion: interface is float64, not time.Time]
```

```
[query] 2017/01/25 08:52:35 SELECT * INTO qualif.one_month.process FROM qualif."default".process WHERE application =~ /achille/ AND time > '2016-05-23T15:10:18+02:00' AND time < '2016-05-23T15:22:23+02:00' GROUP BY *
[query] 2017/01/25 08:52:35 SELECT * INTO qualif.one_month.process FROM qualif."default".process WHERE application::tag =~ /achille/ AND time::float > '2016-05-23T15:10:18+02:00' AND time::float < '2016-05-23T15:22:23+02:00' GROUP BY * [panic:interface conversion: interface is float64, not time.Time] goroutine 3862 [running]:
runtime/debug.Stack(0xc42650f8c0, 0xc423f60d00, 0xcf)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/influxdata/influxdb/influxql.(*QueryExecutor).recover(0xc4201fdda0, 0xc42650f8c0, 0xc42e7d5920)
        /root/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:364 +0x96
panic(0x9d3700, 0xc42ca55ac0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/influxdata/influxdb/coordinator.convertRowToPoints(0xc43046c850, 0x7, 0xc42a274b40, 0xc42650f940, 0xc42a274b40, 0xc425fcf901, 0xc425fcf9b0, 0xc42a274b70)
        /root/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:1059 +0x48b
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).writeInto(0xc4202695c0, 0xdd92c0, 0xc427ff6af0, 0xc42cb4a000, 0xc42a274b40, 0x2710, 0xc42cb4a000)
        /root/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:1014 +0x70
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc4202695c0, 0xc42602e2a0, 0xc425fcfc58, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:444 +0x462
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc4202695c0, 0xde4e80, 0xc42602e2a0, 0x0, 0x5, 0xc42de9f020, 0xc42e7d5920, 0xc42026cf50, 0xc42de9ef60, 0xc42ea7e0de, ...)
        /root/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:51 +0x2b06
github.com/influxdata/influxdb/influxql.(*QueryExecutor).executeQuery(0xc4201fdda0, 0xc42650f8c0, 0xc42ea7e0de, 0x6, 0x2710, 0x1, 0x0, 0x0, 0xc42e7d5860, 0xc42e7d5800, ...)
        /root/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:314 +0x575
created by github.com/influxdata/influxdb/influxql.(*QueryExecutor).ExecuteQuery
        /root/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:209 +0xb5
```

The query without the INTO clause work. 

I try with different format of date ( epoch in nanosecond ) and it's the same :

```
Server returned error: SELECT * INTO qualif.one_month.process FROM qualif."default".process WHERE application::tag =~ /achille/ AND time::float > 1464009018452477184 AND time::float < 1464009743384997120 GROUP BY * [panic:interface conversion: interface is float64, not time.Time]
```

Information : InfluxDB Admin UI: v1.1 Server: v1.1.0

**Comment by e-dard** [comment]
@max3163 thanks for the report. This is something we need to fix, but it does something about your query does look fishy. Specifically `time::float > '2016-05-23T15:10:18+02:00'`.

Can you try your query without `time::float` and just use `time` on its own? That may prevent the panic from triggering and allow you to get your queries executing.

**Comment by max3163** [comment]
I upgraded to Influxdb 1.2 and same problem.
My query doesn't have time::float , it's just in the response error. ( not present in 1.2 )

To be clear, this is my query  : 

```
select * INTO qualif.one_month.process from process where application =~ /afls/ and time > 1468237266173747456 and time < 1468244523413598976 GROUP BY *
```
And the response : 
```
Server returned error: SELECT * INTO qualif.one_month.process FROM qualif."default".process WHERE application =~ /afls/ AND time > 1468237266173747456 AND time < 1468244523413598976 GROUP BY * [panic:interface conversion: interface is float64, not time.Time]
```

**Comment by e-dard** [comment]
@max3163 OK thanks for the clarification.

**Comment by jsternberg** [comment]
@max3163 have you ever written any floats with the field name `time`?

**Comment by max3163** [comment]
Hi, 

I don't have hany field with this name but may be ...  How I could verify it ? and fix it if it's the case ?

**Comment by e-dard** [comment]
@max3163 you could try `SHOW FIELD KEYS` (docs [here](https://docs.influxdata.com/influxdb/v1.2/query_language/spec/#show-field-keys)

If `process` is then troublesome measurement then I think you would want `SHOW FIELD KEYS FROM process`

**Comment by max3163** [comment]
You were totally right! 

fieldKey	fieldType
lwp	"float"
pcpu	"float"
pmem	"float"
rss	"float"
time	"float"
vsz	"float"
version	"float"

How I could in my query specify that time is for time::Time and not time::Float ?

**Comment by ptitou** [comment]
One workaround is doing this query : 
`select <FIELDS TO COPY> into process_tmp from process where application =~ /afls/ and time > 1468237266173747456 and time < 1468244523413598976 group by <TAGS TO COPY>`

**Comment by jsternberg** [comment]
It seems as if we introduced a filter on writing to prevent a field of `time` from being written so we're not going to fix this issue. To fix this on a local server instance that has the bad field, you can try deleting that field from the data.

If that doesn't work for you, you will probably need to copy the fields from one retention policy to another and filter out that one field.
