### ISSUE TITLE
Process crash due to Point contains null value

### ISSUE THREAD

**Issue by mzhang6666** [influxdata/influxdb#7890]
InfluxDB V1.1 process crashed in random interval while processing random influxql, following are the detail panic callstack, causing by a nil pointer dereference.

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x461322]
> 
> goroutine 9339 [running]:
> panic(0x9cf120, 0xc420010070)
>         /usr/local/go/src/runtime/panic.go:500 +0x1a1
> github.com/influxdata/influxdb/influxql.(*floatChanIterator).setBuf(0xc441e885a0, 0xc420301f00, 0xa, 0xc48576ad00, 0x14, 0xc4854ab260, 0x149c9cc804013000, 0x9995a0, 0x0, 0x0)
>         /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:958 +0x3af
> github.com/influxdata/influxdb/influxql.auxIteratorFields.send(0xc4259c4420, 0x3, 0x3, 0xde5e40, 0xc456515080, 0xc420650c01)
>         /root/go/src/github.com/influxdata/influxdb/influxql/iterator.go:484 +0x746
> github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xc4218a59b0)
>         /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:908 +0xf0
> created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
>         /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:861 +0x3f_**          

With the source code analysis, probably figure out the root cause is a particular point read by floatChanIterator contains nil value.

Step1: Send AuxFloatPoint, invoke itr.fields.send(p);
> func (itr *floatAuxIterator) stream() {
> 	for {
> 		// Read next point.
> 		p, err := itr.input.Next()
> 		if err != nil {
> 			itr.output <- auxFloatPoint{err: err}
> 			itr.fields.sendError(err)
> 			break
> 		} else if p == nil {
> 			break
> 		}
> 
> 		// Send point to output and to each field iterator.
> 		itr.output <- auxFloatPoint{point: p}
> 		if ok := itr.fields.send(p); !ok && itr.background {
> 			break
> 		}
> 	}
> 
> 	close(itr.output)
> 	itr.fields.close()
> }

Step2: Loop point aux() then send points. Invoke itr.setBuf(p.name(), tags, p.time(), v)

> func (a auxIteratorFields) send(p Point) (ok bool) {
> 	values := p.aux()
> 	for i, f := range a {
> 		v := values[i]
> 
> 		tags := p.tags()
> 		tags = tags.Subset(f.opt.Dimensions)
> 
> 		// Send new point for each aux iterator.
> 		// Primitive pointers represent nil values.
> 		for _, itr := range f.itrs {
> 			switch itr := itr.(type) {
> 			case *floatChanIterator:
> 				ok = itr.setBuf(p.name(), tags, p.time(), v) || ok
> 			case *integerChanIterator:
> 				ok = itr.setBuf(p.name(), tags, p.time(), v) || ok
> 			case *stringChanIterator:
> 				ok = itr.setBuf(p.name(), tags, p.time(), v) || ok
> 			case *booleanChanIterator:
> 				ok = itr.setBuf(p.name(), tags, p.time(), v) || ok
> 			default:
> 				panic(fmt.Sprintf("invalid aux itr type: %T", itr))
> 			}
> 		}
> 	}
> 	return ok
> }
> 

Step3: Here is the Panic! In each SetBuf call, this function will try to identify value type per 
**switch v := value.(type)** , when value is nil value, then nil pointer dereference occurred, here could be the main cause trigger the panic issue.

> func (itr *floatChanIterator) setBuf(name string, tags Tags, time int64, value interface{}) bool {
> 	itr.cond.L.Lock()
> 	defer itr.cond.L.Unlock()
> 
> 	// Wait for either the iterator to be done (so we don't have to set the value)
> 	// or for the buffer to have been read and ready for another write.
> 	for !itr.done && itr.buf.filled {
> 		itr.cond.Wait()
> 	}
> 
> 	// Do not set the value and return false to signal that the iterator is closed.
> 	// Do this after the above wait as the above for loop may have exited because
> 	// the iterator was closed.
> 	if itr.done {
> 		return false
> 	}
> 
> 	switch v := value.(type) {
> 	case float64:
> 		itr.buf.points[itr.buf.i] = FloatPoint{Name: name, Tags: tags, Time: time, Value: v}
> 
> 	case int64:
> 		itr.buf.points[itr.buf.i] = FloatPoint{Name: name, Tags: tags, Time: time, Value: float64(v)}
> 
> 	default:
> 		itr.buf.points[itr.buf.i] = FloatPoint{Name: name, Tags: tags, Time: time, Nil: true}
> 	}
> 	itr.buf.filled = true
> 
> 	// Signal to all waiting goroutines that a new value is ready to read.
> 	itr.cond.Signal()
> 	return true
> }

Here comes my question:
1. Could you provide Influxsql which may capable to scan out nil value according to a FloatPoint.
2. If we are on right track of this nil panic, any workarounds available to sort this out.

**Comment by e-dard** [comment]
@mzhang6666 can you repro this using the point sent to the influxdb server using the HTTP API for example?

Use of the `influxql` package outside of the InfluxDB project isn't supported by us.

**Comment by mzhang6666** [comment]
@e-dard We are unable to reproduce on demand, but this symptom periodically occurred in our local InfluxDB V1.1 deployment, and represent same panic call stack each time process crashing.

Our live environment build Telegraf+Grafana+InfluxDb solution with minor code enhancement, no additional 3rd party package installed. According to this issue, we are still not quite sure panic triggered by Telegraf point insert or Grafana query, Following is the core function involved in panic, 
> func (a auxIteratorFields) send(p Point) (ok bool) {

By reviewing panic call stack, apparently issue caused by a corrupted nil data in AuxFloatPoint, apply null reference check at code level could suppress crash. 

As hotfix, is there any workaround to fix nil value of AuxFloatPoint, a way to scan/fix existing nil data or patching some functions deferring the panic.

Thanks for your support.

**Comment by russorat** [comment]
closing due to age. if this is still a problem in the latest release, please open a new issue.
