### ISSUE TITLE
Issues with top query

### ISSUE THREAD

**Issue by pavel-odintsov** [influxdata/influxdb#7894]
Hello!

I come here from ticket https://github.com/grafana/grafana/issues/2721

I just tried to sue few examples in ticket but all of them generate errors:
```
select mean(bits_incoming) from hosts_traffic where time > now() - 1h group by time(1m), top(mean(bits_incoming), host, 5, 10m)
```

What's right way to extract values / tags for topX values?

Thank you!

**Comment by kostasb** [comment]
@pavel-odintsov Selector functions like top can't be used in the `group by` clause. The query mentioned in grafana/grafana#2721 is hypothetical. Only time and tags are allowed in `group by`.

This will return the top 3 values per minute along with each of the returned points "host" tag:

```
select top(bits_incoming,3),host from hosts_traffic where time > now() - 1h group by time(1m)
```
