### ISSUE TITLE
error when using top and sum in subquery

### ISSUE THREAD

**Issue by gescheit** [influxdata/influxdb#7898]
Hi! I am trying to use subqueries and found some error.
influxdb  version 1.2.0-1 from https://repos.influxdata.com/ubuntu/ trusty/stable amd64 Packages

`curl -i -XPOST 'http://localhost:8086/write?db=testdb' --data-binary '
cpu_load_short,host=server1,cpu=cpu1 value=1i 1422568543702900257
cpu_load_short,host=server1,cpu=cpu2 value=2i 1422568543702900257
cpu_load_short,host=server1,cpu=cpu3 value=3i 1422568543702900257
cpu_load_short,host=server2,cpu=cpu1 value=1i 1422568543702900257
cpu_load_short,host=server2,cpu=cpu2 value=2i 1422568543702900257
cpu_load_short,host=server2,cpu=cpu3 value=3i 1422568543702900257'`

`influx -database testdb -execute "select top(value, host, 3) from (select sum(value) as value from cpu_load_short group by host)"`

returns error.  In log file:
[I] 2017-01-27T14:13:36Z SELECT top(value, host, 3) FROM (SELECT sum(value) AS value FROM testdb.autogen.cpu_load_short GROUP BY host) service=query
panic: runtime error: index out of range

goroutine 697 [running]:
panic(0xa03980, 0xc420012150)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/influxql.filterIntegerByUniqueTags(0xc436aa2300, 0x2, 0x2, 0xc43449a820, 0x1, 0x1, 0xbac6f8, 0xc436aa2300, 0x0, 0x1100000060)
        /root/go/src/github.com/influxdata/influxdb/influxql/call_iterator.go:1050 +0x2b6
github.com/influxdata/influxdb/influxql.NewIntegerTopReduceSliceFunc.func1(0xc436aa2300, 0x2, 0x2, 0xc42ceafba8, 0xc42ceafc98, 0xc42ceafc98)
        /root/go/src/github.com/influxdata/influxdb/influxql/call_iterator.go:860 +0x45b
github.com/influxdata/influxdb/influxql.(*IntegerSliceFuncReducer).Emit(0xc42dcbd2a0, 0xc42ceafba8, 0xc4201680a0, 0xe)
        /root/go/src/github.com/influxdata/influxdb/influxql/functions.gen.go:595 +0x44
github.com/influxdata/influxdb/influxql.(*integerReduceIntegerIterator).reduce(0xc42cea2b40, 0x43db15, 0xc4206396c8, 0x8679c0, 0x18, 0xc420639778)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3961 +0x807
github.com/influxdata/influxdb/influxql.(*integerReduceIntegerIterator).Next(0xc42cea2b40, 0xc42024cf80, 0xc420356180, 0x20002)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3874 +0xa1
github.com/influxdata/influxdb/influxql.(*integerInterruptIterator).Next(0xc42da54820, 0xc420978720, 0x867996, 0x180001)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3296 +0x52
github.com/influxdata/influxdb/influxql.(*bufIntegerIterator).Next(0xc42da54840, 0xc420356180, 0x8679c0, 0x180001)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:2614 +0x3c
github.com/influxdata/influxdb/influxql.(*integerAuxIterator).stream(0xc42da548a0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3393 +0x32
created by github.com/influxdata/influxdb/influxql.(*integerAuxIterator).Start
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3379 +0x3f

If i use max instead of sum i get normal answer.

**Comment by jwilder** [comment]
#7966 prevents the panic, but the query results will need to looked at in a subsequent PR.

**Comment by jsternberg** [comment]
This should be fixed by #8081.

**Comment by jsternberg** [comment]
Fixed by #8081.
