### ISSUE TITLE
Installation failure on Ubuntu 14.04.5

### ISSUE THREAD

**Issue by jmichaelbarker** [influxdata/influxdb#7899]
### Bug report

__System info:__

Ubuntu 14.04.5 on kernel 2.6.32-042stab116.1
influxdb 1.2.0-1 from `deb https://repos.influxdata.com/ubuntu trusty stable`

__Steps to reproduce:__

1. apt-get install influxdb

__Expected behavior:__

Should install the package on the target system.

__Actual behavior:__

```
root@vps1:~# apt-get install influxdb
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  influxdb
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/17.3 MB of archives.
After this operation, 55.1 MB of additional disk space will be used.
Selecting previously unselected package influxdb.
(Reading database ... 75217 files and directories currently installed.)
Preparing to unpack .../influxdb_1.2.0-1_amd64.deb ...
Unpacking influxdb (1.2.0-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up influxdb (1.2.0-1) ...
Failed to issue method call: No such file or directory
dpkg: error processing package influxdb (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 influxdb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@vps1:~#
```

__Additional info:__

I don't know what additional information to provide, as this is long before any opportunity to configure anything.

Also, if this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

```
curl -o block.txt "http://localhost:8086/debug/pprof/block?debug=1" 
curl -o goroutine.txt "http://localhost:8086/debug/pprof/goroutine?debug=1" 
curl -o heap.txt "http://localhost:8086/debug/pprof/heap?debug=1" 
curl -o vars.txt "http://localhost:8086/debug/vars" 
iostat -xd 1 30 > iostat.txt
influx -execute "show shards" > shards.txt
influx -execute "show stats" > stats.txt
influx -execute "show diagnostics" > diagnostics.txt
```

Please run those if possible and link them from a [gist](http://gist.github.com).

Can't run these, as the package does not finish installing.

If there's any other info I can provide, I will happily do so.

**Comment by jwilder** [comment]
@rossmcdonald @gunnaraasen any ideas?

**Comment by rossmcdonald** [comment]
@jmichaelbarker We are unable to reproduce this issue. Are you sure you are running Ubuntu Trusty? Trusty (or any other Ubuntu) doesn't ship with a `2.6` kernel version...

From some quick Googling, this may be related to the `systemctl enable influxdb` command that is run in the [post-install script](https://github.com/influxdata/influxdb/blob/master/scripts/post-install.sh#L14). That call shouldn't be run on Ubuntu Trusty, though, as it doesn't run systemd. Can you provide us with the output to the following command?

```
cat /etc/lsb-release
```

**Comment by jwilder** [comment]
Related? #7933

**Comment by martinseener** [comment]
The running Kernel - 2.6.x - seems too old for me for that kind of recent 14.04 distribution, so i guess that SysVinit is indeed running on that system instead of systemd, therefore my fix in PR #7933 should indeed fix that issue, as it correctly sees that sysvinit is running and not systemd and therefore installs influxdb using the sysvinit procedure.

**Comment by jmichaelbarker** [comment]
Can confirm that #7933 fixes this - the reason I had such an old kernel was that the system was on an OpenVZ VPS with an older host kernel.

**Comment by pavleec** [comment]
Great, thanks for immediate response. When do you plan to release 1.2.1 builds then?

**Comment by cok666n** [comment]
I too am having this exact issue, running it on a AWS Lightsail instance (not sure why they ship with the old kernel tbh) (in case anyone gets here with the same issue).

Anyone has a temp solution? As it seems this wasn't fixed and goes back to last year or so?
