### ISSUE TITLE
Feature to configure influx db's roll up policy

### ISSUE THREAD

**Issue by keep94** [influxdata/influxdb#7903]
### Feature Request

Support a query like:

select mean(value) from "my_metric" where time > now() - 1d group by time(5m+2.5m)

__Proposal:__ 

The above query would be identical to select mean(value) from "my_metric" where time > now() - 1d group by time(5m) except that it would add 2.5m onto each time stamp in the result set. So the timestamps would be something like 10:02:30; 10:07:30; 10:12:30; etc. instead of 10:00; 10:05; 10:10

__Current behavior:__ 

Currently a query like select mean(value) from "my_metric" where time > now() - 1d group by time(5m) reports the start time of time interval e.g 10:00; 10:05; 10:10 etc.

__Desired behavior:__ [What you would like to happen]

In our particular use case, we want aggregated queries to report the midpoint time of each time interval. 10:02:30; 10:07:30; 10:12:30; etc.

__Use case:__ 

We have several metrics that increase with time. user_cpu_time is one example.  Using the start time of each time interval, the way influx does currently consistently overestimates the value of the metric at a given time especially for large time intervals. If a metric is ever increasing and the time interval is 1 hour, the average of this metric between 10:00 and 11:00 will overestimate the average of this metric right at 10:00.  We believe that using the midpoint time of each time interval will give more realistic estimates even for larger time intervals.

**Comment by pkittenis** [comment]
Doesn't `non_negative_derivative(mean(value))`  give expected results? Counter values, like cpu time, would best use derivative to get expected values in aggregation.
