### ISSUE TITLE
Anchors not working as expected with case-insensitive regex

### ISSUE THREAD

**Issue by sethm** [influxdata/influxdb#7906]
### Bug report

__System info:__ InfluxDB 1.2.0 on OS X 10.12.2 (installed with Homebrew)

__Steps to reproduce:__

1. Create a test database
2. Populate with test data
        
        h2o_feet,location=santa_monica water_level=10 0
        h2o_feet,location=santa_monica water_level=12 10000000000
        h2o_feet,location=santa_monica water_level=11 20000000000
        h2o_feet,location=santa_monica water_level=13 30000000000

3. Attempt to use a case-insensitive regular expression with anchors:

        SELECT * FROM h2o_feet WHERE location =~ /(?i)^SANTA_MONICA$/

__Expected behavior:__ Should return four rows

__Actual behavior:__ Returns no rows

__Additional info:__ Note that leaving off EITHER anchor returns the expected rows. Replacing either anchor with `\b` also returns expected rows.

**Comment by e-dard** [comment]
@sethm thanks for this report. I think I know where the issue is. As a workaround for the moment you could, as you suggest, use `=~ /(?i)^SANTA_MONICA/` or `=~ /(?i)SANTA_MONICA$/` or `=~ /(?i)SANTA_MONICA/` if any of those are precise enough for you.

**Comment by sethm** [comment]
Addendum: I just discovered that the anchors work properly when in a subquery, but not when in a main query. I hope that helps narrow it down.
