### ISSUE TITLE
InfluxDB 500 errors without any details and hungs too

### ISSUE THREAD

**Issue by jayannah** [influxdata/influxdb#7908]
Hi

We are using Influx 1.0.0.
 
I see too many 500 http errors for write to database XXXX, and write to other database are fine.  In the InfluxDB logs there are no details on why the influxdb server is returning 500 errors. 

Also, the influxDB too slow or kind of hungs. 

When I restart the influx server, all the HTTP status code are 2xx include the write to the database XXXX.. but within few min influx DB is returning 500 for database XXXX..

Is there way to configure influx server to log why it is returning 500 ??

Best Regards
Jayanna Hallur

**Comment by e-dard** [comment]
@jayannah please upgrade to `1.2.0`, which has many performance improvements over `1.0.0`

**Comment by jayannah** [comment]
Thanks for the quick response.
So, is there a bug in 1.0 it will get hung after frequent 500 errors?? 

Is Influx 1.2 has the error details in the logs to indicate why it logs 500 errors?
