### ISSUE TITLE
functions don't work on results of sub-subqueries

### ISSUE THREAD

**Issue by meekmichael** [influxdata/influxdb#7909]
### Bug report

__System info:__ 1.2.0

__Steps to reproduce:__

I have this query:

```select count(v) from (select sum as v from (select sum(value) from "some.metric" where person='michael' and time > 0 group by time(1d)) where sum<5000)```

I would expect it to show me the number of rows in `some.metric` where the `person` tag was `michael` and the `value` of the 1-day sum was < 5000.  It always returns nothing.  There are no errors logged.

If, however, I remove the `count` on the outermost query, I get back _N_ rows of data, as expected.  Ditto for `sum` or `mean` on that outermost query.

**Comment by jsternberg** [comment]
This is an issue with the condition so, since the condition isn't getting applied correctly, I think it's likely filtering out all of the rows because everything wrongly evaluates to false.

**Comment by gabrieldp** [comment]
Any progress on this issue? Currently using version 1.2.2 and have a similar use case for this functionality, with the "count()" aggregator, still experiencing the same results described above.
Thanks!

**Comment by jsternberg** [comment]
Can you try this on master? I think the fix is in there and it should be part of 1.3.

**Comment by gabrieldp** [comment]
I've just tried it on 1.3 and can confirm that it indeed works.

**Comment by jsternberg** [comment]
I'm going to close this. If you continue to have issues, please report them as a new issue.
