### ISSUE TITLE
Incremental backup doesn't work as expected

### ISSUE THREAD

**Issue by mattibf** [influxdata/influxdb#7911]
### Bug report

__System info:__ 
InfluxDB version: 1.1.1
OS: CentOS7

__Steps to reproduce:__

1. Create a backup of a database, with parameter "since"
2. Stop database
3. Delete existing data
4. Restore backup
5. Start database again
6. Retrieve data by date

__Expected behavior:__ 
Only data with a time stamp newer than the given date "since" for backup should be visible.
I.e., only 

__Actual behavior:__ 
Varying:
Sometimes, all data can be seen.
In other cases, the "since" - parameter was interpreted, but I was able to see all data of a specific shard, not just the data starting from the time, specified with "since".

__Additional info:__ [Include gist of relevant config, logs, etc.]

Pls. refer to the samples below for details.
Besides, I got a bit confused:
With influxdb 1.2, there was an announcement that incremental backup is supported now for Enterprise version. However, this timestamp-based backup exists already longer...
So, is it expected that the since-parameter does what it should do?

Concrete examples:

1. backup, starting from 2017-01-30, 10:20:15

1.1 Queries return data even from "2017-01-25" (the oldest data in this database).
      I.e., a whole backup has been taken and restored.

1.2 Result from "show shards":
name: mon
id      database        retention_policy        shard_group     start_time              end_time                expiry_time             owners
--      --------        ----------------        -----------     ----------              --------                -----------             ------
6       mon             persister_all           6               2017-01-02T00:00:00Z    2017-01-03T00:00:00Z    2017-03-04T00:00:00Z
8       mon             persister_all           8               2017-01-03T00:00:00Z    2017-01-04T00:00:00Z    2017-03-05T00:00:00Z
10      mon             persister_all           10              2017-01-04T00:00:00Z    2017-01-05T00:00:00Z    2017-03-06T00:00:00Z
12      mon             persister_all           12              2017-01-05T00:00:00Z    2017-01-06T00:00:00Z    2017-03-07T00:00:00Z
14      mon             persister_all           14              2017-01-06T00:00:00Z    2017-01-07T00:00:00Z    2017-03-08T00:00:00Z
16      mon             persister_all           16              2017-01-07T00:00:00Z    2017-01-08T00:00:00Z    2017-03-09T00:00:00Z
18      mon             persister_all           18              2017-01-08T00:00:00Z    2017-01-09T00:00:00Z    2017-03-10T00:00:00Z
20      mon             persister_all           20              2017-01-09T00:00:00Z    2017-01-10T00:00:00Z    2017-03-11T00:00:00Z
22      mon             persister_all           22              2017-01-10T00:00:00Z    2017-01-11T00:00:00Z    2017-03-12T00:00:00Z
24      mon             persister_all           24              2017-01-11T00:00:00Z    2017-01-12T00:00:00Z    2017-03-13T00:00:00Z
26      mon             persister_all           26              2017-01-12T00:00:00Z    2017-01-13T00:00:00Z    2017-03-14T00:00:00Z
28      mon             persister_all           28              2017-01-13T00:00:00Z    2017-01-14T00:00:00Z    2017-03-15T00:00:00Z
30      mon             persister_all           30              2017-01-14T00:00:00Z    2017-01-15T00:00:00Z    2017-03-16T00:00:00Z
32      mon             persister_all           32              2017-01-15T00:00:00Z    2017-01-16T00:00:00Z    2017-03-17T00:00:00Z
34      mon             persister_all           34              2017-01-16T00:00:00Z    2017-01-17T00:00:00Z    2017-03-18T00:00:00Z
36      mon             persister_all           36              2017-01-17T00:00:00Z    2017-01-18T00:00:00Z    2017-03-19T00:00:00Z
38      mon             persister_all           38              2017-01-18T00:00:00Z    2017-01-19T00:00:00Z    2017-03-20T00:00:00Z
40      mon             persister_all           40              2017-01-19T00:00:00Z    2017-01-20T00:00:00Z    2017-03-21T00:00:00Z
42      mon             persister_all           42              2017-01-20T00:00:00Z    2017-01-21T00:00:00Z    2017-03-22T00:00:00Z
44      mon             persister_all           44              2017-01-21T00:00:00Z    2017-01-22T00:00:00Z    2017-03-23T00:00:00Z
46      mon             persister_all           46              2017-01-22T00:00:00Z    2017-01-23T00:00:00Z    2017-03-24T00:00:00Z
48      mon             persister_all           48              2017-01-23T00:00:00Z    2017-01-24T00:00:00Z    2017-03-25T00:00:00Z
50      mon             persister_all           50              2017-01-24T00:00:00Z    2017-01-25T00:00:00Z    2017-03-26T00:00:00Z
52      mon             persister_all           52              2017-01-25T00:00:00Z    2017-01-26T00:00:00Z    2017-03-27T00:00:00Z
54      mon             persister_all           54              2017-01-26T00:00:00Z    2017-01-27T00:00:00Z    2017-03-28T00:00:00Z
56      mon             persister_all           56              2017-01-27T00:00:00Z    2017-01-28T00:00:00Z    2017-03-29T00:00:00Z
58      mon             persister_all           58              2017-01-28T00:00:00Z    2017-01-29T00:00:00Z    2017-03-30T00:00:00Z
60      mon             persister_all           60              2017-01-29T00:00:00Z    2017-01-30T00:00:00Z    2017-03-31T00:00:00Z
62      mon             persister_all           62              2017-01-30T00:00:00Z    2017-01-31T00:00:00Z    2017-04-01T00:00:00Z
64      mon             persister_all           64              2017-01-31T00:00:00Z    2017-02-01T00:00:00Z    2017-04-02T00:00:00Z

2. backup, starting from 2017-01-30, 10:20:25 (i.e.: 10 seconds later than in example1!)

2.1 Queries return data 2017-01-30 and later.
      However, it returns all existing data with timestamp "2017-01-30...", even those earlier than 10:20:25

1.2 Result from "show shards":
Same as before.
However, in the file-system, only files for segments 6, 62 and 64 did exist.

**Comment by timhallinflux** [comment]
@stevebang -- please review given the current implementation.
