### ISSUE TITLE
Graphite Input Templet/Tags are not working for Measurements having Unique Values

### ISSUE THREAD

**Issue by nrsekhar** [influxdata/influxdb#7912]
I Have tomcat JMX metrics collecting from Collectd and we are storing the Data in graphite way using Graphite plugin , and as our system have huge number of metrics we enabled Tags as like below,

[[graphite]]
  enabled = true
  bind-address = ":port"
  database = "database_name"
  protocol = "tcp"
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "1s"
  consistency-level = "one"
  separator = "."
  udp-read-buffer = 10000
 templates = [
       "host.measurement*",
   ]

Now the issue is with few tomcat JMX metrics like this,
1. GenericJMX-dead_catalina_request_processor-_http-nio-10_30_1_30-2344_.io_octets-global.rx
2. GenericJMX-dump_catalina_request_processor-_http-nio-10_30_1_33-2345_.io_octets-global.rx
3. GenericJMX-dude_catalina_request_processor-_http-nio-10_30_1_30-2346_.io_octets-global.rx.

I am trying to push these all metrics to one measurement with name "io_octets-global.rx" but its not pushing the metrics as i expected.

I tried below "Filters and Templates" but none of them worked for me.

#  "*.io_octets-global.rx  host.resource.measurement"
#  "*.GenericJMX-[a-z,A-Z]{2-32}_catalina_request_processor-_http-nio-\d{1-3}_\d{1-3}_\d{1-3}_\d{1-3}-\d{1-4}_.io_octets-global.tx   host.resource.measurement"
#  "*.rx host.service.resource.measurement"
#  "server.*.rx host.field.measurement"
#  "*.GenericJMX-[a-z,A-Z]{2-32}_catalina_request_processor-_http-nio-[0-9]+_[0-9]+_[0-9]+_[0-9]+-[0-9]+.io_octets-global.rx host.service.measurement"
#   "*.GenericJMX-dump* host.resource.measurement"
#   "*.io_octets-global.tx host.service.measurement"
#     "host.GenericJMX*.measurement*",
#     "host.GenericJMX*  host.resource.measurement*",

few of them are very blunt and wrong way of filtering but tried . 

As our primary requirement is to aggregate the data across the tables we couldn't find proper solution and thought of using templates to push the data into single measurement . but its also not supporting.

Can any one suggest me to do the things to resolve the issue. 
 

Is templates wont support globs or regex ? then how can we achieve this scenario?
 

System info: 
Os - Ubuntu 16.04
Influx db version :  1.1.0-1

**Comment by nrsekhar** [comment]
I am getting metrics with *.*.io_octets_global.tx and host.service.measurement* filter.

Thank you :)

**Comment by nrsekhar** [comment]
still i am getting duplicate measurements in database.

**Comment by pkittenis** [comment]
`host.measurement*` means that metrics like `my_host.my_measurement.rest.of.metric` will get parsed into a measurement `my_measurement.rest.of.metric` and a host tag value of `my_host` due to the `measurement*` glob.

If you do not want everything after the measurement to be part of measurement do not use the glob.

This should work - `host.measurement.field*`

`io_octets-global` will be measurement and all fields after it will be a field on the `io_octets-global` measurement.

**Comment by nrsekhar** [comment]
@pkittenis  Thank you for your response, i am able implement it. :)
