### ISSUE TITLE
Invalid index-version should abort startup

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#7917]
### Bug report

__System info:__ `tsi` branch.

__Steps to reproduce:__

1. INFLUXDB_DATA_INDEX_VERSION=foo influxd

__Expected behavior:__

The process should abort startup with an error indicating that `foo` is not a valid index version.  Should suggest that `tsi1` and `inmem` are the valid values.

__Actual behavior:__

The process starts but every write and query fails with an error.  The behavior is different from other config options which abort the process with invalid config options.

**Comment by e-dard** [comment]
Fixed via 54193e11
