### ISSUE TITLE
Yum repo out of date

### ISSUE THREAD

**Issue by hanej** [influxdata/influxdb#7920]
### Bug report

The yum repos do not have the latest (1.2.0) versions of the applications.  I'm accessing them at https://repos.influxdata.com/centos/6/x86_64/stable/ and https://repos.influxdata.com/centos/7/x86_64/stable/.

**Comment by rossmcdonald** [comment]
It looks like it's up-to-date:

https://repos.influxdata.com/centos/6/x86_64/stable/influxdb-1.2.0.x86_64.rpm

**Comment by hanej** [comment]
So weird.  Yes I see them now.  Never mind.  Thanks.
