### ISSUE TITLE
TSI files not backed up

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#7921]
### Bug report

__System info:__ `tsi` branch

__Steps to reproduce:__

1. INFLUXDB_DATA_INDEX_VERSION=tsi1 influxd
2. influx_stress
3. influxd backup -database stress /tmp/backup
4. tar -tvf /tmp/backup/stress.autogen.00001.00

__Expected behavior:__ 

The contents of the backups should have the `index` directory and `tsi` files.

__Actual behavior:__

No tsi files are backed up.

**Comment by benbjohnson** [comment]
Fixed with 57f44d5.
