### ISSUE TITLE
TSI index automatically created at startup for existing shards

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#7923]
### Bug report

With existing shards on disk, when `tsi1` is enabled, a TSI index is created for all shards concurrently at startup.  Existing DBs with thousands of shards will take a very long time to start the first time this is run.

We should leave the existing shards as is and use `inmem` indexes for them and use `tsi1` indexes for 
new shards.  We should also consider a way to manually trigger a migration of shards from `inmem` to `tsi1`.

__System info:__ `tsi` branch

__Steps to reproduce:__

1. INFLUXDB_DATA_INDEX_VERSION=inmem influxd
2. influx_stress
3. INFLUXDB_DATA_INDEX_VERSION=tsi1 influxd
4. `ls ~/.influxdb/data/stress/1/index` will show TSI files now

__Expected behavior:__ 

Existing shards still use `inmem` index.

__Actual behavior:__ 

Old shards are converted synchronously at startup.

**Comment by benbjohnson** [comment]
@jwilder Fixed with c246f3d9b0ac1f146bcb1c9dd57391216a011b76.

I also made it so that changing `INFLUXDB_DATA_INDEX_VERSION` back to `inmem` will use the in-memory index (even for existing tsi1 shards). What do you think? It seemed like it'd be good to allow people to stop using tsi if they were trying it out.

**Comment by benbjohnson** [comment]
Hmm, actually, people can just delete the `index` directory so I'll remove that last feature.

**Comment by jwilder** [comment]
Yeah, I think deleting `index` dir is probably better since if you switched back to `inmem` wrote new series and then switched to `tsi1`, those series would not show up.

**Comment by jwilder** [comment]
`index-version` should probably control what new shard indexes will be.  Once created, they stay that way unless you manually remove it.  Seem ok?

**Comment by benbjohnson** [comment]
@jwilder Yeah, I fixed it in 76235f1 so that shards will keep the index type they were originally created with.

**Comment by jwilder** [comment]
Verified this is fixed.
