### ISSUE TITLE
max-values-per-tag needs to be re-enabled in TSI

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#7927]
The check for `[max-values-per-tag](https://github.com/influxdata/influxdb/blob/tsi/tsdb/shard.go#L525)` needs to be re-enabled in TSI.  It was disabled during development because the check was not performant.

**Comment by benbjohnson** [comment]
@jwilder There doesn't seem to be a fast way to implement this accurately since name/key/value can be duplicated across TSI files within a single shard.

Is this feature still worth supporting since TSI should help alleviate high cardinality tag values?

**Comment by jwilder** [comment]
Can we push it into the `inmem` index and skip it for `tsi1`?

**Comment by benbjohnson** [comment]
@jwilder Sure, np. I'll add it in `inmem`.

**Comment by benbjohnson** [comment]
Added to `inmem` in d91e6ea.
