### ISSUE TITLE
any way to create local mirror for telgraf/influxdb repos?

### ISSUE THREAD

**Issue by chenggl007** [influxdata/influxdb#7928]
Say, for Ubuntu/Debian, the mirror creation attempt failed:

debmirror -h repos.influxdata.com -r debian  <localdir>

with error message:

Net::FTP: connect: Connection timed out

**Comment by chenggl007** [comment]
There is no repos for sles 11/12 at https://repos.influxdata.com/. Thanks.

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list.

Thanks.
