### ISSUE TITLE
Issue in displaying Jenkins build data to influxDB

### ISSUE THREAD

**Issue by preetisaini01** [influxdata/influxdb#7930]
I am facing some issues in fetching Jenkins build data into influxDB. Actually, the main requirement in automated testing services is to show Jenkins job data on Grafana dashboard. So, I have created a Jenkins job and also added influxDB plugin for the same with all configuration changes made as per steps provided in  http://christoph-burmeister.eu/?p=2887http://stackoverflow.com/questions/26116711/how-to-install-influxdb-in-windows.

The only change I did is that I have created a sample Windows batch command instead of Shell command (as I am using a Windows 7 machine). Further, the database is shown in Grafana dashboard. But since the Jenkins job data is not shown in influxDB so its not shown in Grafana dashboard as well.

Please let me know in case some step is not included in URL provided above so that Jenkins build data can be shown in influxDB.

**Comment by deveth0** [comment]
Hi Preetisaini01,

I also tried this plugin but found an easier solution in the plugin provided by jenkins:
https://wiki.jenkins-ci.org/display/JENKINS/InfluxDB+Plugin

although not documented, it works fine with latest influx versions, so probably give this a try.

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list.

Thanks.

**Comment by preetisaini01** [comment]
Thanks for providing your suggestions on my issue. I will look into it.
