### ISSUE TITLE
Missing data on large range in grafana

### ISSUE THREAD

**Issue by p0nt** [influxdata/influxdb#7931]
I use influxdb in combination with grafana. As soon as I check a graph with month's of data some lines are not completely drawn because there seems to be a max data points limit somewhere. In the past with graphite you can just change the max data points value in grafana, but how can this be done for influxdb?

Please see this screenshot for more info:

after 1/26 the line stops:
http://shot.xsnews.nl/stefan/e98ed8f8610a4e4f.png

but if I check closely on 1/26, it is there:
http://shot.xsnews.nl/stefan/8b50202211b0b6f0.png

my queries:
http://shot.xsnews.nl/stefan/059a4ce09ef18f9d.png

Also, when I select big ranges on a per 5 min data graph, it will show me data per 20 minutes instead of 5 which is ofcourse because of speed, but how can I make it that it will keep each 5 min?
Please keep in mind that I do not expire my data, it goes infinite.

**Comment by jwilder** [comment]
You might be hitting the `max-row-limit` config option.  You can disable it via:

```
[http]
max-row-limit = 0
```

**Comment by ZhukovAlexey** [comment]
@jwilder hello, thanks for your answer, I hit the same problem and setting max-row-limit in 0 helped.

The strange thing is that max-row-limit was set in 10000 in 1.1 too and there wasn't any problem to have graphics which render more than 10000 points. It seems that in 1.1 it was ignored or smth. else.

**Comment by jwilder** [comment]
Yes.  I believe it was not working in 1.1.
