### ISSUE TITLE
Non-admin users receive forbidden response when making subqueries

### ISSUE THREAD

**Issue by Nicholi** [influxdata/influxdb#7946]
I can't make subqueries on any non-admin users. I don't see anything in the documentation about privilege requirements in order to make subqueries. Getting back a forbidden authorization response with the status of "invalid measurement". I attempted with a user that even has ALL privileges for the particular database, but same error. Only after a user is made admin will the subquery work.

System info:
Ubuntu 16.04.1
InfluxDB 1.2.0-1 (from repos.influxdata.com)
HTTP Auth and HTTPS are enabled in influxdb.conf. No other special settings.

# Reproduce bug
1. Setup a test db and user
```
CREATE DATABASE "testSubQuery"
USE "testSubQuery"
INSERT test,name=tag1 things=30
INSERT test,name=tag1 things=12
INSERT test,name=tag2 things=4
INSERT test,name=tag2 things=9
CREATE USER "testSubUser" WITH PASSWORD 'test'
```

2. Note all our users and their admin status
```
> SHOW USERS
user         admin
----         -----
__admin      true
testSubUser  false
```

3. Note our test users privileges (currently none)
```
> SHOW GRANTS FOR "testSubUser"
database privilege
-------- ---------
```

4. Attempt querying data with testSubUser
```
> SELECT * FROM test
ERR: error authorizing query: testSubUser not authorized to execute statement 'SELECT * FROM test', requires READ on testSubQuery
```
Makes total sense, user has no privileges.

5. Give testSubUser READ privileges
```
> GRANT READ ON "testSubQuery" TO "testSubUser"
> SHOW GRANTS FOR "testSubUser"
database     privilege
--------     ---------
testSubQuery READ
```

6. Repeat query with testSubUser
```
> SELECT * FROM test
name: test
time                name things
----                ---- ------
1486168403498343817 tag1 30
1486168403580866258 tag1 12
1486168403625002589 tag2 4
1486168403775352570 tag2 9
```
Query works as expected, now a simple GROUP BY test

```
> SELECT * FROM test GROUP BY "name"
name: test
tags: name=tag1
time                things
----                ------
1486168403498343817 30
1486168403580866258 12

name: test
tags: name=tag2
time                things
----                ------
1486168403625002589 4
1486168403775352570 9
```
Again as expected. Now simply take this last GROUP BY query and use it in a subquery. This query should be syntactically sound, and is only here for showing the permissions problem. As this query could be easily simplified into 1 query.

```
> SELECT SUM(things) FROM (SELECT * FROM test GROUP BY "name")
ERR: error authorizing query: invalid measurement: (SELECT * FROM test GROUP BY "name")
```
Getting authorization problems now. Invalid measurement?

7. Give testSubUser ALL privileges on DB
```
> GRANT ALL ON "testSubQuery" TO "testSubUser"
> SHOW GRANTS FOR "testSubUser"
database     privilege
--------     ---------
testSubQuery ALL PRIVILEGES
```

9. Repeat query, same error.
```
> SELECT SUM(things) FROM (SELECT * FROM test GROUP BY "name")
ERR: error authorizing query: invalid measurement: (SELECT * FROM test GROUP BY "name")
```

10. Give testSubUser ADMIN privileges
```
> GRANT ALL PRIVILEGES TO "testSubUser"
> SHOW USERS
user         admin
----         -----
__admin      true
testSubUser  true
```

11. Repeat query, now works.
```
> SELECT SUM(things) FROM (SELECT * FROM test GROUP BY "name")

name: test
time sum
---- ---
0    55
```

**Comment by jwilder** [comment]
Fixed via #7952
