### ISSUE TITLE
[1.2] Potential memory leak

### ISSUE THREAD

**Issue by ConfiDev** [influxdata/influxdb#7950]
System (VM):
12 Cores
32 GB Ram
100 GB SSD
Ubuntu 16.04
InfluxDB 1.2

We are trying to import germany's weather data into the InfluxDB.
~1000 weather station
14 different values per weather station (temperature, humidity, etc...)
~5-45 years of data (earliest possible time stamp 1970-01-01) (1 value per day)
=>
~14000 series cardinality (results from our current BE structure - could of course be reduced to 1000)
~100 +- 20 million values (hard to judge)

The import itself is not the problem - there was a problem, but got fixed with v1.2. It actually seems like, that the InfluxDB is consuming a lot of memory in idle mode because of the data. I could not even import about 500 thousand values without a out of memory crash. With several crashes we imported about 1 million values and restarted the InfluxDB service and left it that way for some time. The InfluxDB started to consume all of the available memory and the whole server got unstable. I could not even drop the databases. Had to stop the service and remove them directly from the hard disk.

Since we already performed a mass import of about 180 million values which cover about 1-2 years without any problems, I am assuming, this problem has to do with the time range of the imported data. Here we import data of up to 45 years.

The green line is the VM with InfluxDB on it. The data import job got started at arround 11:30 with 10 worker processes. When we reduced the processes to 2 the first crash got just delayed because the data got not imported that fast. But once there was a crash the graph seems similar.
![crashes](https://cloud.githubusercontent.com/assets/22637669/22628018/ae4a274e-ebcc-11e6-937f-a107e6ba3142.png)

**Comment by jwilder** [comment]
For sparse data like this, you will need to increase the shard duration in your retention policy.  I would recommend setting it for `52w` in this case... possibly higher.

Also, can you attache the following to the issue:
```
influx -execute "show shards" > shards.txt
influx -execute "show stats" > stats.txt
influx -execute "show diagnostics" > diagnostics.txt
```

**Comment by ConfiDev** [comment]
I changed the shard duration to 52w and everything was just fine. (it makes total sense - missed that)
I will for sure be using a long shard duration now.

Since I dunno if it is/was an expected behaviour, I changed back to retention policy "autogen" to provide the required data (shards, stats, diagnostics) about the crash. (import done to "dev_enerlisa" database) There is no panic/stack trace, just the one from the linux kernal about an out of memory exception.
![crash](https://cloud.githubusercontent.com/assets/22637669/22854643/6bb53e5e-f073-11e6-8a31-0b81f19feeed.png)
[diagnostics.txt](https://github.com/influxdata/influxdb/files/768496/diagnostics.txt)
[shards.txt](https://github.com/influxdata/influxdb/files/768497/shards.txt)
[stats.txt](https://github.com/influxdata/influxdb/files/768498/stats.txt)
