### ISSUE TITLE
[feature request] Be able to set different query limits depending on source of query (user, system)

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#7953]
### Feature Request

__Proposal:__

Add option to set different query limit configurations depending on the source of the query. For example, being able to set different limits for queries initiated over the HTTP API (ie, those created by a user of the database) vs those initiated by the continuous query runner (ie, those created by the InfluxDB database itself, or the 'system'). 

__Current behavior:__

Query limits are enforced at a global scale. There is no way to set specific query limits depending on where the query originated.

__Desired behavior:__

Query limits are enforced depending on the source of the query. For example, an administrator should be able to set a 1m query timeout for queries initiated over the HTTP API and, simultaneously, a 5m query timeout for queries initiated for CQ's.

__Use case:__

The current functionality prevents administrators from effectively limiting bad queries initiated by users while simultaneously ensuring the overall health of the system.

**Comment by gunnaraasen** [comment]
Setting configurable query limits might work better as an authorization setting per user.

**Comment by CAFxX** [comment]
Agree with @gunnaraasen: having the ability to specify per-user overrides to the global limits (`max-select-series`, `max-select-points`, `max-select-buckets`, `query-timeout` and `max-concurrent-queries`) would be extremely useful to be able to control load and guarantee a certain level of user experience.

Our use-case is having different querying limits based on user "type": we commonly have different types of users performing read queries: regular users, privileged users and administrators. We would love the ability to give increasing "query quotas" to the various types of users (regular users would have the lowest quotas, privileged users would have higher quotas and administrators the highest quotas).
