### ISSUE TITLE
HTTP Basic authentication credentials take precedence over URL query parameters

### ISSUE THREAD

**Issue by akloeber** [influxdata/influxdb#7957]
### Bug report

__System info:__ 
- InfluxDB 1.2.0
- Ubuntu 16.04.1 LTS

__Steps to reproduce:__
1. Create database `test`
2. Create user `tiger` with password `scott` that is allowed to access database `test`
3. Enable authentication
4. Authenticate with query parameters:
```{bash}
$ curl 'http://localhost:8086/query?u=tiger&p=scott' --data-urlencode 'db=test' --data-urlencode 'q=SHOW SERIES'
{"results":[{"statement_id":0}]}
```
5. Authenticate with query parameters while HTTP Basic credentials are also present:
```{bash}
$ curl -u foo:bar 'http://localhost:8086/query?u=tiger&p=scott' --data-urlencode 'db=test' --data-urlencode 'q=SHOW SERIES'
{"error":"authorization failed"}
```

__Expected behavior:__
The documentation says:
> If you authenticate with both Basic Authentication and the URL query parameters, the user credentials specified in the query parameters take precedence.

So the given HTTP Basic Credentials (_foo/bar_) should be ignored.

__Actual behavior:__ 
The request is denied with error _"authorization failed"_ although the HTTP Basic credentials which are unknown to InfluxDB should be ignored.

**Comment by jsternberg** [comment]
@pauldix should we update the documentation for this? It seems to me that HTTP Basic credentials should have higher priority.

**Comment by akloeber** [comment]
@jsternberg in InfluxDB 0.8 is was the other way around.

In my opinion that was correct as when credentials are provided through the URL this somehow feelds "closer" to the application und should have a higher priority. Furthermore a common use case is running InfluxDB behind a reverse proxy which itself does a first level of authentication for all incoming request (HTTP basic or client cert). Normally those credentials are different and unknown in the second tier (application/services likes InfluxDB).

**Comment by jsternberg** [comment]
Hm, I think the proxy argument is most compelling personally. I'll prepare a PR for this and wait for the final call from @pauldix.
