### ISSUE TITLE
Enhancement Request:  List the previous searches queries (history) in Query bar

### ISSUE THREAD

**Issue by jayannah** [influxdata/influxdb#7959]
Influx Version: 1.0
It would nice if there is history of previously ran searches (atleast previous 10 or 20) for quicker help in searching ..

**Comment by Tomcat-Engineering** [comment]
I assume that this relates to the "HTTP Admin Interface" ?  Unfortunately this [is now deprecated](https://docs.influxdata.com/influxdb/v1.2/tools/web_admin/) so it is unlikely that anyone will add this  feature :-(

In case it is useful, I forked [a standalone version of the interface](https://github.com/Tomcat-Engineering/influx-admin), with added graphs, and I could probably add your requested feature to that.
