### ISSUE TITLE
[1.2.0] Selecting from measurements starting with `_` errors with 'unknown system source'

### ISSUE THREAD

**Issue by pkittenis** [influxdata/influxdb#7961]
### Bug report

__System info:__ 1.2.0, Linux

__Steps to reproduce:__

1. `create database test`
2. `use test`
3. `insert _m1 a=1`
4. `select "a" from "_m1"`

__Expected behavior:__ Data is returned by query

__Actual behavior:__ Query errors with `ERR: unknown system source: _m1`

__Additional info:__ Behaviour is as expected in 1.1.x. Selecting with database set and measurement quoted but without retention works around the issue, for example `select "a" from "test._m1"` returns data. This is not a documented behaviour of the `FROM` clause, however.

**Comment by gerrickw** [comment]
The database name and retention name is applied automatically from grafana, even in raw edit mode, so I am unable to use this workaround. :(

I need to revert to influx 1.1, it'd be great if this could be fixed in the next release, so I can use future versions.

**Comment by gerrickw** [comment]
As a note, this problem happened a year or so ago and was a discussion about character restrictions.

Similar bug that was fixed: #5870
https://github.com/influxdata/influxdb/issues/6011#issuecomment-196547163

**Comment by pkittenis** [comment]
Duplicate of #8044 - closing.
