### ISSUE TITLE
[1.2.0] Show series, fields and tags with over 10k series in DB are truncated (unexpected behaviour)

### ISSUE THREAD

**Issue by pkittenis** [influxdata/influxdb#7962]
### Bug report

__System info:__ 1.2.0, Linux

__Steps to reproduce:__

1. Insert 15k series into DB
2. `SHOW SERIES LIMIT 20000`
3. Length of series list returned is 10k

__Expected behavior:__ Series list would return up to 20k series.

__Actual behavior:__ Series list was truncated to 10k

__Additional info:__ Not sure if this is a bug or expected behaviour but saw nothing in change log about `SHOW` queries now having a 10k max limit, regardless of limit set in query. With or without an explicit limit in the query, max series returned is always 10k.

 Looking at the json returned by influxdb, it contains `partial: true`, but no messages in influxdb logs otherwise. Also, at least in the python influxdb client, there is no indication that partial results have been returned. The behaviour with `1.1.x` is that a `value of LIMIT` number of series is returned. This has [affected some influxdb clients](https://github.com/InfluxGraph/influxgraph/issues/24) on upgrading to `1.2.0`.

`SHOW FIELD KEYS` and `SHOW TAG KEYS` are also similarly truncated to 10k.

**Comment by joelio** [comment]
We are also seeing similar behavior via Grafana. Large series of metrics that displayed perfectly in 1.1 now are truncated and partially rendered.

**Comment by joelio** [comment]
I see - https://docs.influxdata.com/influxdb/v1.2/administration/config/#max-row-limit-10000

**Comment by pkittenis** [comment]
Yes, though `max-row-limit` did not apply to `SHOW` queries before `1.2`.

**Comment by joelio** [comment]
👍

**Comment by jwilder** [comment]
`max-row-limit` has a default of 10000 which was added in #6126 back when `0.12` was released.  It looks like it was not working properly and was fixed in `1.2` via #7368.  The workaround currently is to set `max-row-limit = 0` in your config.

**Comment by pkittenis** [comment]
Thanks @jwilder, sounds like clients will need to handle this behaviour.

**Comment by pkittenis** [comment]
Closing as not a bug

**Comment by geethanjalieswaran** [comment]
@jwilder Even after setting max-row-limit = 0 in my config, my results are truncated to 10000.  Expected or a bug indeed? This works as (my) expected in version 1.1 (i.e results not truncated).

**Comment by jwilder** [comment]
@geethanjalieswaran you have under the `[http]` sections?
```
[http]
max-row-limit = 0
```

**Comment by geethanjalieswaran** [comment]
@jwilder Sorry for the false alarm! It was not under [http] section. 
Confirming that below is working as expected in version 1.2.

[http]
max-row-limit = 0
