### ISSUE TITLE
[1.2.0] Main query doesn't use all results from subquery

### ISSUE THREAD

**Issue by misko321** [influxdata/influxdb#7964]
**InfluxDB version: 1.2.0**

I need to calculate disk space taken up by all Cassandra nodes. I have 4 nodes in the cluster. This is the result returned by subquery alone:
```
> SELECT last("Load_Count") FROM "cassandraStorage" GROUP BY "host"   

name: cassandraStorage
tags: host=cassandra-staging/node-a
time			last
----			----
1486561241000000000	3.92816878e+09

name: cassandraStorage
tags: host=cassandra-staging/node-b
time			last
----			----
1486561241000000000	3.98345454e+09

name: cassandraStorage
tags: host=cassandra-staging/node-c
time			last
----			----
1486561241000000000	3.924538952e+09

name: cassandraStorage
tags: host=cassandra-staging/node-d
time			last
----			----
1486561241000000000	3.867005806e+09
```

**Actual main query result**:
```
> SELECT sum("last") FROM (SELECT last("Load_Count") FROM "cassandraStorage" GROUP BY "host")
name: cassandraStorage
time	sum
----	---
0	7.795174586e+09
```

**It sums only the first and last value.**

**Expected main query result**:
```
> SELECT sum("last") FROM (SELECT last("Load_Count") FROM "cassandraStorage" GROUP BY "host")
name: cassandraStorage
time	sum
----	---
0	something around 15.7
```

Similarly for `max`:

**Actual**:

```
> SELECT max("last") FROM (SELECT last("Load_Count") FROM "cassandraStorage" GROUP BY "host")

name: cassandraStorage
time			max
----			---
1486562931000000000	3.92816878e+09
```

**Takes into account only the first and last value, although the max value is 3.98345454e+09**.

**Expected**:

```
> SELECT max("last") FROM (SELECT last("Load_Count") FROM "cassandraStorage" GROUP BY "host")

name: cassandraStorage
time			max
----			---
1486562931000000000	3.98345454e+09
```

**Comment by argyakrivos** [comment]
+1 Same problem here too!

**Comment by vkadam** [comment]
Any temporary resolution for this one, or estimation?

**Comment by abadyan-vonage** [comment]
We're having a similar problem. It seems like last and first specifically return partial results, while other functions like mean or min return all the results.
`select res from (select last(idle) as res from cpuStats group by host)`
This query only returns some of the results returned by the subquery.
We're using 1.2.0 as well.
