### ISSUE TITLE
How `GROUP BY time()` vs `GROUP BY tag` works in the main query

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#7971]
How `GROUP BY time()` vs `GROUP BY tag` works in the main query

#### Steps to reproduce:

1. Write some data
```
> insert giraffes,name=chrono leaves_consumed=12 1485298440000000000
> insert giraffes,name=graf leaves_consumed=8 1485298440000000000
> insert giraffes,name=chrono leaves_consumed=13 1485298445000000000
> insert giraffes,name=graf leaves_consumed=2 1485298445000000000
> insert giraffes,name=chrono leaves_consumed=15 1485298450000000000
> insert giraffes,name=graf leaves_consumed=4 1485298450000000000
> insert giraffes,name=chrono leaves_consumed=13 1485298455000000000
> insert giraffes,name=graf leaves_consumed=5 1485298455000000000

> select * from giraffes
name: giraffes
time                 leaves_consumed name
----                 --------------- ----
2017-01-24T22:54:00Z 12              chrono
2017-01-24T22:54:00Z 8               graf
2017-01-24T22:54:05Z 13              chrono
2017-01-24T22:54:05Z 2               graf
2017-01-24T22:54:10Z 15              chrono
2017-01-24T22:54:10Z 4               graf
2017-01-24T22:54:15Z 13              chrono
2017-01-24T22:54:15Z 5               graf
```

2. Run a query with a `GROUP BY tag` clause in the main query
```
> SELECT * FROM (SELECT MAX("leaves_consumed") FROM "giraffes" WHERE time >= '2017-01-24T22:54:00Z' AND time <= '2017-01-24T22:54:15Z') GROUP BY "name"
name: giraffes
tags: name=graf
time                 max
----                 ---
2017-01-24T22:54:00Z 8

name: giraffes
tags: name=chrono
time                 max
----                 ---
2017-01-24T22:54:10Z 15
```
3. Run the same query but replace the `GROUP BY tag` clause with a `GROUP BY time()` clause
```
> SELECT * FROM (SELECT MAX("leaves_consumed") FROM "giraffes" WHERE time >= '2017-01-24T22:54:00Z' AND time <= '2017-01-24T22:54:15Z') GROUP BY time(10s)
ERR: error parsing query: GROUP BY requires at least one aggregate function
```

#### Actual behavior and Expected behavior

I know this is how subqueries work now. So a `GROUP BY tag` clause in the main query is automatically applied to the subquery, and a `GROUP BY time()` clause in the main query is not automatically applied to the subquery - but, that difference in behavior for the same InfluxQL clause seems strange to me.

I'd expect that the subquery is basically independent from the main query - so the system runs the subquery and then runs the main query on the data that are returned from the subquery - and no clauses are transported between the two queries. That might be naiive but that's how I thought they'd work.

Pulled from: https://github.com/influxdata/influxdb/issues/7875

**Comment by jsternberg** [comment]
I think this is an effective explanation for this behavior: https://github.com/influxdata/influxdb/issues/7875#issuecomment-275258217

I'm going to close this issue. If that explanation doesn't work, please reopen so I can clarify this behavior further.
