### ISSUE TITLE
API query endpoint doesn't use the rp query string parameter

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#7973]
### Bug report

Ubuntu 16.04, version 1.2.0 (and 1.1.1)

__Steps to reproduce:__

**1.** Write some data to a non-default retention policy
```
~# influx
Connected to http://localhost:8086 version 1.2.0
InfluxDB shell version: 1.2.0
> create database test
> use test
Using database test
> create retention policy alternate on test duration 1d replication 1
> show retention policies on test
name      duration shardGroupDuration replicaN default
----      -------- ------------------ -------- -------
autogen   0s       168h0m0s           1        true
alternate 24h0m0s  1h0m0s             1        false

> insert into alternate mymeas value=1
> select * from test.alternate.mymeas
name: mymeas
time                value
----                -----
1486587715372417917 1
```

**2.**  Query the data in the `alternate` retention policy using the `rp` query string parameter
```
~# curl -G "http://localhost:8086/query?db=test&rp=alternate" --data-urlencode "q=SELECT * FROM mymeas"
{"results":[{"statement_id":0}]}
```

**3.** Query the data in the `alternate` retention policy by fully qualifying the measurement
```
~# curl -G "http://localhost:8086/query?db=test&rp=alternate" --data-urlencode "q=SELECT * FROM test.alternate.mymeas"
{"results":[{"statement_id":0,"series":[{"name":"mymeas","columns":["time","value"],"values":[["2017-02-08T21:01:55.372417917Z",1]]}]}]}
```

__Expected behavior:__ 
I'd expect the request in step two to return the results that I got in step three.

__Actual behavior:__ 
The query in step two returns no results.

__Additional info:__ [Include gist of relevant config, logs, etc.]

If I'm reading the logs correctly, the query in step 2 seems to target `autogen` instead of `alternate`.

```
Feb 08 21:24:22 blah influxd[8441]: [I] 2017-02-08T21:24:22Z SELECT * FROM test.autogen.mymeas service=query
Feb 08 21:24:22 blah influxd[8441]: [httpd] 127.0.0.1 - - [08/Feb/2017:21:24:22 +0000] "GET /query?db=test&q=SELECT+%2A+FROM+mymeas&rp=alternate HTTP/1.1" 200 33 "-" "curl/7.47.0" f5bc7d77-ee44-11e6-8002-000000000000 1350

Feb 08 21:24:27 blah influxd[8441]: [I] 2017-02-08T21:24:27Z SELECT * FROM test.alternate.mymeas service=query
Feb 08 21:24:27 blah influxd[8441]: [httpd] 127.0.0.1 - - [08/Feb/2017:21:24:27 +0000] "GET /query?db=test&q=SELECT+%2A+FROM+test.alternate.mymeas&rp=alternate HTTP/1.1" 200 137 "-" "curl/7.47.0" f894204c-ee44-11e6-8003-000000000000 1170
```

> Note: I'm able to write to a non-default RP with the API.

**Comment by mark-rushakoff** [comment]
AFAICT the `/query` endpoint was never coded to accept the `rp` query parameter (I looked through the history of services/httpd/handler.go through May 2015). The docs say you can use the `rp` query parameter for `/query` but the docs are wrong in this case.

I'm re-tagging this issue as a feature request.

**Comment by rkuchan** [comment]
Oh, OK! Thanks. I'll get the docs updated.

**Comment by timhallinflux** [comment]
If you specify an rp -- it is simply ignored and the default rp is used.  So, we should either add the rp into the query API and/or return an error if a user submits a query parameter which is unsupported.

**Comment by rbetts** [comment]
Proposal:  User can specify `rp` as a query parameter to write to that `rp`; If the  user does both - provides a fully qualified named and an `rp` parameter that mis-match - then error.

**Comment by jacobmarble** [comment]
Tangentially, when (HTTP url param or POST form) `db=foo` and the queried measurement is `bar.rp.m`, `bar` wins. 😬

**Comment by jacobmarble** [comment]
In my last comment, I was worried that a user could access a database they didn't have access to by providing conflicting db values to the HTTP query and InfluxQL, but have tested and found this is not the case.

@rbetts after playing with this for a couple of hours, I think it feels natural to leave the current behavior. The code refers to the HTTP db param as "defaultDB" [here](https://github.com/influxdata/influxdb/blob/master/query/executor.go#L268) and [here](https://github.com/influxdata/influxdb/blob/master/coordinator/statement_executor.go#L1248), and I'm in favor of continuing this style.

**Comment by e-dard** [comment]
@jacobmarble @rbetts does #9737 satisfy this ticket's requirements, or is there more to do?

**Comment by rbetts** [comment]
I’d like to discuss - respecting rp on /query but not /write is what’s
proposed?

**Comment by jacobmarble** [comment]
@rbetts Looking closer at /write behavior.

**Comment by jacobmarble** [comment]
For [documentation](https://docs.influxdata.com/influxdb/v1.5/tools/api/#query) change:

`rp` is now supported on the `/query` endpoint. A query that specifies a fully qualified series with `db.rp.measurement` will override the HTTP `db` and `rp` HTTP parameters (`db` override was already true, `rp` override is new behavior because `rp` HTTP parameter is new).
