### ISSUE TITLE
different values for nanoseconds @ /write precision=n, /query epoch=ns

### ISSUE THREAD

**Issue by Cyclenerd** [influxdata/influxdb#7985]
Hi,

I noticed a small inaccuracy. At least it confused me as a InfluxDB beginner.

According to the documentation, the parameters epoch and precision expect different values for nanoseconds.

* [precision=n](https://docs.influxdata.com/influxdb/v1.2/tools/api/#write)
* [epoch=ns](https://docs.influxdata.com/influxdb/v1.2/guides/querying_data/#other-options-when-querying-data)

Is this really so, or is it an error in the docu.

Best regards
Nils

**Comment by jwilder** [comment]
I think this might be a documentation issue.  cc @rkuchan 

For `epoch` and `precision`, it looks like it's assumed to be nanoseconds so it looks like `ns` or `n` won't have any affect for either of them.  I haven't tested this to verify though.

**Comment by rkuchan** [comment]
This is a docs issue. If you set the precision to `ns` or `n`, InfluxDB writes the timestamp in nanoseconds. For consistency with the rest of the system, the docs should say `ns` for the `precision` query string parameter.

Thanks for letting me know, @jwilder and @Cyclenerd! I've opened an issue on the docs repo to get this fixed.
