### ISSUE TITLE
Problems when all tags are null

### ISSUE THREAD

**Issue by robinsonjj** [influxdata/influxdb#7986]
### Bug report

influxdb v1.2 on linux

__Steps to reproduce:__

I'm sorry in advance but I haven't been able to find a way to easily produce a fresh measurement which exhibits the problem I am having. As such, I'm happy to try queries on my machine if that is helpful but otherwise will not expect this issue to remain open - just hope that it's useful to flag that this is a problem somewhere!

1. I have a measurement with several tags
2. When I try a query like ```curl -G 'http://192.168.1.100:8086/query?pretty=true' --data-urlencode "db=db_v0.4" --data-urlencode "q=select * from m1 where time = '2017-02-03 12:00:00' and id = 'id1' limit 3"``` as well as the data I would expect to get back, I also get back a data point whose tags are all null (the first value in this screenshot):

![image](https://cloud.githubusercontent.com/assets/10656485/22829221/70558872-ef99-11e6-908f-a0c341e3fa1a.png)

3. The first issue is that this data point is being returned at all since it doesn't match the requested id.
4. The second issue is that I can't remove this data point either by using delete or drop where `id = ''`. In fact I can't even select the point by using `where id = ''`

If you have any ideas on how to fix this they would be much appeciated. Sorry again for not being able to provide a reproducible dataset.

**Comment by jwilder** [comment]
@robinsonjj If you can come up with a way to reproduce this your issue, that would be helpful.

**Comment by russorat** [comment]
closing due to lack of response.
