### ISSUE TITLE
fatal error: sweep increased allocation count since 1.2

### ISSUE THREAD

**Issue by Apollon77** [influxdata/influxdb#7991]
Hey,

I use inflixdb on cubietruck (armhf) and since 1.2 I get very often this error together with an auto-restart:

fatal error: sweep increased allocation count

Attached two trace dumps, hope it helps.

Is it possible to downgrade to 1.1.2 (whch was the last version before, or ?!) or will this not work?
[fatal-influxd2.txt](https://github.com/influxdata/influxdb/files/769216/fatal-influxd2.txt)
[fatal-influxd.txt](https://github.com/influxdata/influxdb/files/769217/fatal-influxd.txt)

**Comment by jwilder** [comment]
This might be a Go runtime issue.  Some relevant ones logged there:

* https://github.com/golang/go/issues/19029
* https://github.com/golang/go/issues/16778

You should be able to downgrade to 1.1.2.

**Comment by jwilder** [comment]
@Apollon77 Did you compile the binary yourself or use one of our released versions.  If you compiled it, which version of Go did you use?

**Comment by rsc** [comment]
@jwilder FWIW, I can tell from the line numbers in the stack traces that it was compiled with at least Go 1.7 and at most Go 1.7.4, not Go 1.7.5.

**Comment by Apollon77** [comment]
I used The only provided as package by your PPA (installation as described on your website).
I moved some data into a second instance and now it is more stable, but experienced this error first in 1.2

**Comment by jwilder** [comment]
@Apollon77 @rsc This would be with 1.7.4 then.  Our released binaries are compiled with 1.7.4.

**Comment by Apollon77** [comment]
not able to reproduce with current builds ...
