### ISSUE TITLE
"The specified key does not exist" error when downloading influxdb

### ISSUE THREAD

**Issue by KPACHbIuLLIAnO4** [influxdata/influxdb#7993]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

$ uname -a
Linux **** 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

__Steps to reproduce:__

1. Go to https://portal.influxdata.com/downloads and select Ubuntu Unstable amd64
2. Press Download and copy the link
3. $ wget https://dl.influxdata.com/telegraf/releases/influxdb_1.2.1~rc1_amd64.deb

__Expected behavior:__ 

HTTP 200

__Actual behavior:__ [What actually happened]

$ wget https://dl.influxdata.com/telegraf/releases/influxdb_1.2.1~rc1_amd64.deb
--2017-02-12 18:03:46--  https://dl.influxdata.com/telegraf/releases/influxdb_1.2.1~rc1_amd64.deb
Resolving dl.influxdata.com (dl.influxdata.com)... 54.192.127.251, 54.192.127.76, 54.192.127.74, ...
Connecting to dl.influxdata.com (dl.influxdata.com)|54.192.127.251|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-02-12 18:03:48 ERROR 404: Not Found.

__Additional info:__ [Include gist of relevant config, logs, etc.]

No technical contacts on the site, no place to report a problem, nothing on google about this, only stories of success on twitter and everywhere and "contact sales" links. So here I am creating an issue. Your download links are broken.

**Comment by mark-rushakoff** [comment]
We've very recently made some changes to our downloads page, and it looks like you've stumbled across a bug. The "telegraf" segment of the URL should be "influxdb", i.e. the correct URL is https://dl.influxdata.com/influxdb/releases/influxdb_1.2.1~rc1_amd64.deb . I'm going to raise this with the appropriate team and leave this issue open until we've resolved the bug on the download page. Thanks for letting us know about it.

**Comment by KPACHbIuLLIAnO4** [comment]
This helps, thanks.

**Comment by jimaek** [comment]
Also you incorrectly say to use `dpkg ` for CentOS
It should be ` yum localinstall` like in the old website

**Comment by mark-rushakoff** [comment]
Looks like the related issues have all been fixed - closing this.

**Comment by jimaek** [comment]
It continues to say `dpkg` for CentOS. That command is for Debian-like systems.
