### ISSUE TITLE
InfluxData downloads page points to wrong URL of InfluxDB build

### ISSUE THREAD

**Issue by natemurthy** [influxdata/influxdb#7994]
When I navigate to https://portal.influxdata.com/downloads I select:

```
Influxdb > Stable > Amd64 Ubuntu
```

and click the "Download" button which brings me to a page that reads:

**Download Influxdb (Stable) for Amd64 Ubuntu**
```
wget https://dl.influxdata.com/telegraf/releases/influxdb_1.2.0_amd64.deb
sudo dpkg -i influxdb_1.2.0_amd64.deb
```
```
MD5: f79959802930c7e9d6e81ffd366c0629
```

The URL provided is incorrect and returns a `404 Not Found` response from the file server. The correct URL should be:

```
wget https://dl.influxdata.com/influxdb/releases/influxdb_1.2.0_amd64.deb
```

I suspect there are few other broken links as well.

**Comment by phemmer** [comment]
See #7993

**Comment by marthjod** [comment]
Stumbled across this as well, please fix.

**Comment by jwilder** [comment]
Closing this since download links are maintained in a different repo: https://github.com/influxdata/docs.influxdata.com/issues/1014
