### ISSUE TITLE
Add prefix to rpm

### ISSUE THREAD

**Issue by goaquin** [influxdata/influxdb#7996]
Hello,
A simple request: I need to install InfluxDB in a single disk. So, can you add a prefix in the rpm script?
https://github.com/influxdata/influxdb/blob/master/scripts/post-install.sh

So it could be possible to do this:
` rpm -i --prefix=/data/sdb/influxdb influxdb-1.2.0.x86_64.rpm`

Regards,
Joaquín Silva

**Comment by jwilder** [comment]
cc @rossmcdonald
