### ISSUE TITLE
[Bug] Query results for a specific point in time

### ISSUE THREAD

**Issue by jl98800** [influxdata/influxdb#7999]
### Directions
_GitHub Issues are reserved for actionable bug reports and feature requests._
_General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb)._

_Before opening an issue, search for similar bug reports or feature requests on GitHub Issues._
_If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
_Erase the other section and everything on and above this line._

### Bug report

__System info:__ [Ubuntu 14.04, Influxdb version is 1.2 (recently upgraded).
 Grafana version is 3.1.0. ]

__Steps to reproduce:__

1. Every 60 seconds we run 8 queries to pull data from InfluxDB and present it in a Grafana dashboard. 

Queries:
 A
SELECT last("value") FROM "jobs.running" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
B 
SELECT last("value") FROM "jobs.failed" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
C
SELECT last("value") FROM "jobs.succeeded" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
D
SELECT last("value") FROM "jobs.failed_awaiting_restart" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
E
SELECT last("value") FROM "jobs.long_running" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
F
SELECT last("value") FROM "jobs.total" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
G
SELECT last("value") FROM "jobs.avg_job_attempts" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
H SELECT last("value") FROM "jobs.avg_run_time" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

2. View the time intervals in Grafana under quick ranges shows all data from 5 minutes to 3 hours.  Then many queries fail to render anything (including null values).  We need to see data in snapshots or chunks of time for all supported ranges in Grafana (up to 5 years).

__Expected behavior:__ [What you expected to happen]
Then many queries fail to render anything (including null values).  We need to see data in snapshots or chunks of time for all supported ranges in Grafana (up to 5 years).  We were expecting data in tables/graphs to show up for that point in time - even if null.

__Actual behavior:__ [What actually happened]
Rows fail to render in results for tables and graphs show not values (nothing) for points in time past 3 hours.

**Comment by jwilder** [comment]
Is the data just truncated after a certain period of time or does nothing render at all?

It may be that `max-row-limit`.

Try changing your config:
```
[http]
max-row-limit = 0
```

**Comment by jl98800** [comment]
Hi - we see the data in the response tab in google chrome, developer view.  But nothing renders in grafana (tables or graphs) at all.  Not null or 0 as it's configured to do.  Just nothing.   We can't set the max row limit to zero in our situation - it would certainly kill influxdb as we share the instance with a lot of development teams.  And the unlimited setting for max row wouldn't entirely solve the problem as we just want to see results for a window of time up to 1 year.   We did increase max row limit and it did help up to 3 hours.  We poll the DB every 60 seconds and we can't change that without losing results.

**Comment by jl98800** [comment]
But wait - there's more...

I was taking a look in developer tools to see what the request was going to influx for time interval
If I choose 30days, then the interval is 30minutes
If I choose 1year, then the interval is 6hours
30days * 24 hours * 60 minutes * 8 metrics = 345,600 / 30 = 11,520
365 days * 24 hours * 60 minutes * 8 metrics = 4,204,800 / (6hrs*60)  = 11,680
so it seems that the max-row-limit needs to be about 12,000
for 8 metrics

**Comment by jwilder** [comment]
You may also be able to increase your group by intervals to reduce the number of rows being returned as well.  `max-row-limit` was not actually working properly prior to 1.2 so if you were running 1.1 before, it was effectively set to `0` due to a bug.

**Comment by jl98800** [comment]
Jason,

Since we have A LOT of DBs on this instance and a lot of development teams potentially running queries - does this mean a max-row-limit = 12000 is PER QUERY?  In other words if we have 10 teams running queries with a lot of data being pulled - is that going to hurt performance by eating up resources faster?  

Thanks

**Comment by jwilder** [comment]
The limit is evaluated per query.
