### ISSUE TITLE
GET /query results do not match the documentation

### ISSUE THREAD

**Issue by PyDeq** [influxdata/influxdb#8004]
### Bug report

__System info:__
server: InfluxDB 1.2.0 from [the official Docker container](https://hub.docker.com/_/influxdb/) (Debian GNU/Linux 8, x86_64)
client: curl 7.47.0, Ubuntu 16.04.1, x86_64

__Steps to reproduce:__

Follow the InfluxDB's documentation. E.g.:
```console
$ curl -XPOST 'http://localhost:8086/query' --data-urlencode 'q=CREATE DATABASE "mydb"'
$ curl -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'mymeas,mytag1=1 myfield=12i 1463779800000000000'
$ curl -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'mymeas,mytag1=2 myfield=11i 1463779820000000000'
$ curl -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'mymeas,mytag2=1 myfield=18i 1463779840000000000'
$ curl -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'mymeas,mytag2=3 myfield=19i 1463779860000000000'
$ #and finally:
$ curl -G 'http://localhost:8086/query?db=mydb' --data-urlencode 'q=SELECT * FROM "mymeas"'
```

__Expected behavior:__
Either:
```json
{"results":[{"series":[{"name":"mymeas","columns":["time","myfield","mytag1","mytag2"],"values":[["2016-05-20T21:30:00Z",12,"1",null],["2016-05-20T21:30:20Z",11,"2",null],["2016-05-20T21:30:40Z",18,null,"1"],["2016-05-20T21:31:00Z",19,null,"3"]]}]}]}
```
or the actual response (see bellow) to be in the documentation
or a more precise [documentation of the possible responses](https://docs.influxdata.com/influxdb/v1.2/tools/api/#query)
or a more precise documentation of the InfluxDB's versioning scheme and its compatibility guarantees.

__Actual behavior:__
```json
{"results":[{"statement_id":0,"series":[{"name":"mymeas","columns":["time","myfield","mytag1","mytag2"],"values":[["2016-05-20T21:30:00Z",12,"1",null],["2016-05-20T21:30:20Z",11,"2",null],["2016-05-20T21:30:40Z",18,null,"1"],["2016-05-20T21:31:00Z",19,null,"3"]]}]}]}
```

__Additional info:__
The current documentation of the possible responses is a bit vague. It's not clear what we can expect in responses to our requests. Since my application does not expect a `statement_id` property, it started failing since last update of InfluxDB. I have no problem with changing my app but I'd like to see a change on the InfluxDB's side in order to avoid similar problems in the future.

**Comment by jwilder** [comment]
Please log an issue in the documentation repo: https://github.com/influxdata/docs.influxdata.com
