### ISSUE TITLE
[BUG] Import Bug. The shell is displaying all the data by auto-import from a file

### ISSUE THREAD

**Issue by Metamathematics** [influxdata/influxdb#8006]
Im using influxdb-1.0.2.
I am importing my Data with the CLI through an .txt file. It looks like this:
![unbenannt](https://cloud.githubusercontent.com/assets/16038096/22928449/cb5833ee-f2b6-11e6-8813-a5182c7d46c3.png)

The result should be like this:
2017/02/02 12:25:06 Processed 1 commands
2017/02/02 12:25:06 Processed 60000 inserts
2017/02/02 12:25:06 Failed 0 inserts

I most cases the import is successfull and has no Problems. But in ~5% of the imports the CLI is showing all of the data that is imported. Like this:
![unbenannt2](https://cloud.githubusercontent.com/assets/16038096/22928505/153203d2-f2b7-11e6-9b1f-16f0687e05e6.png)

Or even sometimes like this:
![unbenannt3](https://cloud.githubusercontent.com/assets/16038096/22928507/1d2a8028-f2b7-11e6-8330-3d73d8005d88.png)

There is no coruption of the data itself. The DB receives it correctly. But Im working with a lot of imports, and there are some of status-messages coded with the import. When this occurs, the messages can not be seen normally (because there are 20000 lines of imports after them).

Do anyone has on idea whats going on? Can i fix this, or is this a BUG?

**Comment by jwilder** [comment]
Looks like you have an error in there.  I see a `invalid field format` error and unable to parse `__test__,environment=... response_time_ms=815,5 1781638770000: invalid field format`.  The `,` in the `response_time_ms` field is not valid.  If the value should have commas, it needs to be surrounded by double-quote '"' to store it as a string. Floats should just be numbers and a decimal.  If it should be integer, add a `i` suffix.

See the [line prototocol docs](https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_tutorial/) for more details.
