### ISSUE TITLE
difference() output is not in order

### ISSUE THREAD

**Issue by ahmetkizilay** [influxdata/influxdb#8009]
### Bug report
I have an increasing time-series data and I would like to get the difference between two consecutive measurements. I am using the difference() function, but I get erroneous negative output and irregular time order in the output.

__System info:__ v1.2, Ubuntu 14.04

__Steps to reproduce:__

1. Insert the following data (daily increasing values from 2016-09-01 to 2016-11-18)
gist link: https://gist.github.com/ahmetkizilay/8159e06b5680aac2c6365df44fae0305

2. View inserted data (for sanity check)
```
SELECT DIFFERENCE(value) FROM daily_stats_3
```
3. Call `difference()` function:
```
SELECT DIFFERENCE(value) FROM daily_stats_3
```
__Expected behavior:__ I expect to see time values ascending in order, and only positive values as this is an increasing time series data

__Actual behavior:__ The time order seems to be inconsistent, hence the difference values are wrong
```
> SELECT DIFFERENCE(value) FROM daily_stats_3
name: daily_stats_3
time                 difference
----                 ----------
2016-09-02T04:00:00Z 7
2016-09-03T04:00:00Z 4
2016-09-04T04:00:00Z 5
2016-11-14T05:00:00Z 833
2016-11-15T05:00:00Z 14
2016-11-16T05:00:00Z 10
2016-11-17T05:00:00Z 15
2016-11-18T05:00:00Z 10
2016-11-07T05:00:00Z -185
2016-11-08T05:00:00Z 29
2016-11-09T05:00:00Z 14
2016-11-10T05:00:00Z 28
2016-11-11T05:00:00Z 34
2016-11-12T05:00:00Z 8
2016-11-13T05:00:00Z 11
2016-10-31T04:00:00Z -189
```
__Additional info:__ The following query, however, seems to work as expected. (I have one value per day, so MIN is the only value recorded for that day)
```
SELECT DIFFERENCE(MIN(value)) FROM daily_stats_3 WHERE time >= '2016-09-01' GROUP BY time(1d)
```

**Comment by jsternberg** [comment]
It might be related to this one: #8214.

Can you try it out with that commit included? If that PR doesn't match your issue or it doesn't work, please comment again and I'll reopen this issue. Thanks.
