### ISSUE TITLE
continuous query not work if setting time range in where !

### ISSUE THREAD

**Issue by imiskolee** [influxdata/influxdb#8012]
System info:

Amazon AWS Linux InfluxDB 1.2.0

0. datas

```sh
> select * from raw
name: raw
time                aid cid mt    value
----                --- --- --    -----
1487024460000000000 c   a   event 12
1487161260000000000 c   a   image 20
1487233199000000000 c   a   event 1
1487233199000000000 c   a   text  1
1487233199000000000 b   a   text  10

```

1. create the continuous queries 

```sh
CREATE CONTINUOUS QUERY hours_raply2 ON t4 BEGIN SELECT sum(value) AS value INTO t4.autogen.hours_2 FROM t4.autogen.raw WHERE time > now() - 2d AND time <= now() - 1h GROUP BY time(1h), cid, aid, mt END
```

2.  contioues queries log : 

```sh
[I] 2017-02-16T10:00:00Z finished continuous query hours_raply2 (2017-02-16 09:00:00 +0000 UTC to 2017-02-16 10:00:00 +0000 UTC) in 404.387µs service=continuous_querier
```

3. question

not any data in `hours_2`.but the query 

```sh

SELECT sum(value) AS value INTO t4.autogen.hours_2 FROM t4.autogen.raw WHERE time > now() - 2d AND time <= now() - 1h GROUP BY time(1h), cid, aid, mt 
``` 

its working !!!!

4. Why do we need to calculate the data of longer before ？

In real case , we report the raw data is usually delayed (such as network failure, equipment failure, etc.), over a period of time after all data will be reported.

====================================

i want calculate something delay sometime(such as 1d,2d,6h,etc.),and we have another options ?

**Comment by desa** [comment]
@imiskolee There's a bit of an issue with your CQ. Try changing it to

```
CREATE CONTINUOUS QUERY hours_raply2 ON t4 BEGIN SELECT sum(value) AS value INTO t4.autogen.hours_2 FROM t4.autogen.raw GROUP BY time(1h), cid, aid, mt END
```
The issue with the CQ as you have it is
```
WHERE time > now() - 2d AND time <= now() - 1h
```
CQs do not require that time ranges be specified.

**Comment by zxyz** [comment]
Hello @desa,
sry for necrobumping this issue.

I've got the same issue as @imiskolee (running influxdb 1.6.2) but I need the `where time` clause in my CQs, so just dropping the clause would be a problem. If I run the query by hand it works as expected:

`SELECT mean(value) AS value INTO "test"."agg_1h".:MEASUREMENT FROM "test"."autogen"./.*/ WHERE time < now() -2w GROUP BY time(1h),*`

But if I run it as this CQ:

`CREATE CONTINUOUS QUERY "cq_agg_1h" ON "test" BEGIN SELECT mean(value) AS value INTO "test"."agg_1h".:MEASUREMENT FROM "test"."autogen"./.*/ WHERE time < now() -2w GROUP BY time(1h),* END`

It starts aggregating data which is only an hour old and not which is older than 2 weeks.
My question is, is my CQ worng or is it just no possible to use time clauses in CQs? If the latter applys, are there plans for this feature in CQs in the future?

Thanks a lot for your time & help!
