### ISSUE TITLE
Broken Build?

### ISSUE THREAD

**Issue by keep94** [influxdata/influxdb#8016]
### Bug report

__System info:__ Github head version; linux

__Steps to reproduce:__

1. mkdir mygo
2. cd mygo
3. export GOPATH=~/mygo
4. go get github.com/influxdata/influxdb/...

__Expected behavior:__  Influx should build successfully

__Actual behavior:__ Influx fails to compile.

src/github.com/influxdata/influxdb/influxql/query_executor.go:184: undefined: zap.NullEncoder

**Comment by keep94** [comment]
uber-go/zap made breaking changes to their API. 

Off master branch:

Last good zap version for influxdb: 61159f0
first version of zap with breaking changes: e5bfe32

**Comment by rossmcdonald** [comment]
You need to restore the correct dependencies using the included Godeps file. Please follow the instructions in [contributing.md](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#build-and-test) when building.

**Comment by keep94** [comment]
Not trying to contribute just trying to build the project. Shouldn't it
build as-is when checked out from GitHub using go get?

**Comment by rossmcdonald** [comment]
@keep94 No, since we don't vendor dependencies (yet). You need to use `gdm` to restore the pinned dependency commit, otherwise you'll get build errors due to `go get` pulling the latest version from each dependency. Your steps need to be updated to:

```
...
go get github.com/sparrc/gdm
go get github.com/influxdata/influxdb
cd $GOPATH/src/github.com/influxdata/influxdb
gdm restore
go install ./...
```

**Comment by keep94** [comment]
Thx I didn't see on contributing.md instructions to run gdm restore.
Consider providing step by step directions for compiling

**Comment by wonderflow** [comment]
I meet the same problem and I use `gdm restore`, Unfortunately I got

```
ERROR restoring some imports:
-   Error checking out rev 416270f07a9f696922512bb6487df46a2238f73d of repo /Users/sunjianbo/gopath/src/go.uber.org/zap, exit status 128
```

**Comment by wonderflow** [comment]
master branch is ok
