### ISSUE TITLE
Unable to bring up kapacitor after adding morgoth as kapacitor udf

### ISSUE THREAD

**Issue by divgwd** [influxdata/influxdb#8020]
Hi,
I am unable to bring up kapacitor service after adding morgoth as udf below is the output of /var/log/kapacitor/kapacitor.log
`
[run] 2017/02/17 12:04:14 I! Kapacitor starting, version 1.2.0, branch master, commit 5408057e5a3493d3b5bd38d5d535ea45b587f8ff [run] 2017/02/17 12:04:14 I! Go version go1.7.4 [srv] 2017/02/17 12:04:14 I! Kapacitor hostname: localhost [srv] 2017/02/17 12:04:14 I! ClusterID: 8433611d-9a3d-480a-993b-4e226288b192 ServerID: 4082d455-aec0-4245-9e0e-e6f94e2a5696 [task_master:main] 2017/02/17 12:04:14 I! opened [httpd] 2017/02/17 12:04:14 I! Closed HTTP service [task_master:main] 2017/02/17 12:04:14 I! closed [run] 2017/02/17 12:04:14 E! open server: open service *udf.Service: failed to load process info for "morgoth": fork/exec /root/projects/bin/morgoth: permission denied
chnaged the binary permission to kapacitor and influxd also still same error .
`
Any help is appreciated .
Thanks !

**Comment by jwilder** [comment]
Please log an issue in the [kapacitor](https://github.com/influxdata/kapacitor) repo.  cc @nathanielc
