### ISSUE TITLE
Feature request: InfluxQL comments

### ISSUE THREAD

**Issue by rw** [influxdata/influxdb#8025]
__Proposal:__ Comments in InfluxQL.

__Current behavior:__ Comments are not supported.

__Desired behavior:__ Allow line-oriented comments in InfluxQL. Example:

```
# This query computes a bar from foo.
select bar from foo
```

__Use case:__ When performing data analysis, I end up using scripting pipelines that look like this:
```
cat my_query.infuxql | influx > output.txt
```

Inside `my_query.influxql` I have no way to document the queries (and now, subqueries). Comments would increase maintainability.

**Comment by mark-rushakoff** [comment]
I've found myself reaching for the `--` line comment on a few occasions. It looks like many other SQL variants support `/* */` block comments, but I don't know whether supporting block comments would require us to add support for multi-line commands.

**Comment by jsternberg** [comment]
We technically already have multiline commands. Whitespace is mostly ignored so you can split a command between multiple lines pretty easily (although the CLI does not support it, but that's different than the server not supporting it).

I think this should be fairly easy to do and is a nice little feature. Thoughts @pauldix?

**Comment by jsternberg** [comment]
Also, what's the settled syntax for this? `--` for single line comments and `/* */` for multiline comments? Should we support nested multiline comments such as `/* /* */ */`? I vote no on the latter, but I thought I would bring it up anyway as some programming languages like D support that.

**Comment by mark-rushakoff** [comment]
Agreed, no need to support nested multiline comments. Supporting `--` for
single line and `/* */` for multiline seems sufficient to me.

**Comment by pauldix** [comment]
LGTM. Although I am wondering if people will also try `//` for single line and get confused since we support `/* */` for multi-line and generally if you support the latter, you support the former.
