### ISSUE TITLE
[1.2.0] write slow every night

### ISSUE THREAD

**Issue by oiooj** [influxdata/influxdb#8032]
customer monitor system data stored in InfluxDB 1.2.0

```
name: build
Branch Build Time Commit                                   Version
------ ---------- ------                                   -------
master            b7bb7e8359642b6e071735b50ae41f5eb343fd42 1.2.0


name: network
hostname
--------
monitor_store_db205v2


name: runtime
GOARCH GOMAXPROCS GOOS  version
------ ---------- ----  -------
amd64  24         linux go1.7.4
```

Problem occurred at 3:10 AM Beijing Time, and new data queued in MQ. I fixed at 8:00.
4000 points per second now.

![image](https://cloud.githubusercontent.com/assets/2253095/23099340/0c23c14a-f69f-11e6-832b-d6f07a7c6ba7.png)
![image](https://cloud.githubusercontent.com/assets/2253095/23099358/4778d028-f69f-11e6-96c4-537f89ffcac6.png)
![image](https://cloud.githubusercontent.com/assets/2253095/23099359/5b907ac0-f69f-11e6-8b63-bddb4677698c.png)

Got lots of write errors after 3:10 AM in my log, Perhaps a FD leak.

write error log

```
dial tcp 10.x.x.x:8086: connect: cannot assign requested address) for msg 078d03995fde8000

```

_intrenal database write statics:

![image](https://cloud.githubusercontent.com/assets/2253095/23099518/32906040-f6a4-11e6-85b3-ee42c7c4a76c.png)

**Comment by oiooj** [comment]
Today is normal, close first.

**Comment by oiooj** [comment]
Reproduced last night

**Comment by jwilder** [comment]
We need more information in order to diagnose what is going on.  Can you update the issue description with the instructions listed in our [issue template](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md)?  Profile data around the time of the slow write would be helpful.
