### ISSUE TITLE
Allow single value to be repeated in query result

### ISSUE THREAD

**Issue by htj** [influxdata/influxdb#8033]
### Feature Request

__Proposal:__ [Description of the feature]

Repeating a value is often useful or graphing or somehow inspecting data. This value could be a constant, but will typically be derived from the data in query result.

Further, some visualizations tools (grafana, AFAICT) does not allow the extension of a single point into a time series, while others do.

__Current behavior:__ [What currently happens]

When selecting a single value (max/min/mean/avg/percentile) over a time series, the value is returned for a single time in the middle of the selected time (a point in time). The value however is not representative for that time, but for a selected interval of time.

__Desired behavior:__ [What you would like to happen]

SELECT REPEAT(percentile(some_value, 95)) FROM ...

The single value will then be added is a column to each timestamp.

"repeat" is a suggested name. Could be constant or extend or similar.

Allowing injection of value might also be useful, e.g.:

SELECT REPEAT (4) as four, value FROM ...

But not so sure about that one.

__Use case:__ [Why is this important (helps with prioritizing requests)]

Showing an aggregated value for a certain interval can be quite helpful for certain applications. E.g., 95/98 percentile is a very commonly used metric in networking. Getting it as a single value is not ideal.

There is probably a discussion here about how customizable the data from influxdb should be and how much functionality should be in the upper layers. With a grafana + influxdb setup, the functionality sort of falls between chairs (I might have missed some functionality).

**Comment by bbczeuz** [comment]
You don't want to use GROUP BY time(15m) ? This would perform the percentile calculation for batches of 15m. Can you give a data example? (input data, expected output data)

**Comment by htj** [comment]
I already use group by (usually), but it is not what I want.

Consider the following query:

SELECT percentile("ifInOctets", 95) *8 AS "in95", non_negative_derivative("ifHCInOctets", 1s) *8 AS "in", non_negative_derivative("ifHCOutOctets", 1s) *8 AS "out", moving_average("speed", 2) AS "speed" FROM "interfacecounters" WHERE "router" = 'router' AND "interface" = 'if1' AND time > 1448398731879ms and time < 1448463613458ms GROUP BY "interface", "router"

(Percentile should really be calculated on the result of non_negative_derivate on ifHCInOctets, but that isn't allowed currently, but can be solved with a continuous query. Similar the interface speed with moving_average is also a sorta hack, but it works well enough).

Snippet output data (from the cli):

1448430665000000000             2.8472771764666667e+09 3.0345017733333334e+07 4e+10
1448430785000000000             2.8554603180666666e+09 2.50013262e+07         4e+10
1448430905000000000 32893602400 2.9660320214e+09       2.1437377666666668e+07 4e+10
1448431025000000000             3.2139536656e+09       2.2703227066666666e+07 4e+10
1448431145000000000             3.0827745448e+09       1.92045058e+07         4e+10

The percentile is only reported for a single row. I'd like the value to occur in all rows.

The value is relevant for the entire duration. It isn't really related to the grouping.

**Comment by bbczeuz** [comment]
That's how I do it
- Use a CQ to translate the byte counters into bit per second and ```GROUP BY time()``` to have regular intervals
- Use ```SELECT percentile(*,95) AS perc95 FROM ...``` to calculate the percentiles of all columns from CQ's result (above example creates fields perc95_ifInOctets, perc95_ifOutOctets,... (it simply prefixes perc95_ to all source fields)

They recently started supporting subqueries. Probably you can achieve similar results with them; but having pre-calculated the derivatives with a CQ always helps.

**Comment by htj** [comment]
Hi, thanks for the help, but we are misunderstanding each other here.

I can calculate the percentile for a given interval just fine, but I need it to be repeated for graphing purposes. It might also be possible to do this in some graphing tools, but AFAICT it is not possible in grafana; it expects series of points to plot.

Getting percentile per time group doesn't really make any sense for the data I have here (but of course it might make sense in other situations).
