### ISSUE TITLE
Using the TSM field separator in measurement name breaks retrieval

### ISSUE THREAD

**Issue by joelegasse** [influxdata/influxdb#8037]
Using the `tsm1.keyFieldSeparator` in a measurement name will break measurement name detection:

```
> insert measure#!~#ment v=1
> show series
key
---
measure#!~#ment

> select * from "measure#!~#ment"
name: measure#!~#ment
time                v
----                -
1487695683980820866 1

```
Reboot...
```
> show series
key
---
measure

> select * from "measure#!~#ment"
> select * from "measure"
name: measure
time                ment#!~#v
----                ---------
1487695683980820866 1
```

Since names aren't restricted (not even to printable characters), there really isn't a good way to combine the key and field into a single string. Any codepoint or combination of codepoints could be inserted into the key (measurement name, tag key, tag value) or the field name.

### Bug report

__System info:__ Any and all versions using TSM (currently tested on `master` branch)

__Steps to reproduce:__

(see above example)

__Expected behavior:__ return the same thing before/after reboot, or restrict names to reduce usable character set (probably too late for that).

__Actual behavior:__ (see above example)

__Additional info:__ No errors in the log, even for things like this: 
```
> insert m,t=t1,t2=#!~# v=1
[RESTART]
> show series
key
---
m,t=t1,t2=

> select * from m
name: m
time                #!~#v t
----                ----- -
1487696685200754867 1     t1
```

Notice the series key is invalid, the tag `t2` is never seen after a restart, but is seen before the restart.

I'm not sure what a backwards-compatible fix would look like, since `#!~#` could be inserted anywhere in the series key or field name to thwart "use the last index, instead":

`m#!~#v1#!~#v2` -- Is that a measurement named `m` with a field named `v1#!~#v2` or a measurement named `m#!~#v1` with a field named `v2`?

This is probably a longer-term fix that should be included with removing TSM's dependency on the current line-protocol escaping quirks being stored directly in the file.

**Comment by jwilder** [comment]
This is something that would be fixed by #7176
