### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by cattvm** [influxdata/influxdb#8039]
I recently installed influxdb v 1.2 on raspberry pi, but when i tried reaching https://localhost:8086 it says page not found, where as 8088 is not reachable. Please help me.

**Comment by mark-rushakoff** [comment]
GitHub Issues are reserved for actionable bug reports and feature requests. General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

That being said, please go through the [getting started guide](https://docs.influxdata.com/influxdb/v1.2/introduction/getting_started/). Or maybe you were looking for the (deprecated) Admin UI which is on port 8083.
