### ISSUE TITLE
[1.2.1~rc4] Subqueries; A function and WHERE tag clause in the main query returns no results 

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#8045]
### Bug report

__System info:__ 
Ubuntu 16.04, v1.2.1~rc4

__Steps to reproduce:__

1. Write some data
```
> CREATE DATABASE mydb
> USE mydb
Using database mydb
> INSERT pond toads=2
> INSERT pond toads=4
> INSERT pond toads=9

> SELECT * FROM "pond"
name: pond
time                           toads
----                           -----
2017-02-22T17:44:35.234902449Z 2
2017-02-22T17:44:43.444176616Z 4
2017-02-22T17:44:49.651820179Z 9
```
2. Run a subquery that includes just a function in the main query
```
> SELECT MEAN("toads") FROM (SELECT "toads" FROM "pond")
name: pond
time                 mean
----                 ----
1970-01-01T00:00:00Z 5
```
(This is fine)

3. Run a subquery that includes just a WHERE clause in the main query
```
> SELECT "toads" FROM (SELECT "toads" FROM "pond") WHERE "toads" > 3
name: pond
time                           toads
----                           -----
2017-02-22T17:44:43.444176616Z 4
2017-02-22T17:44:49.651820179Z 9
```
(This is also fine)

4. Run a subquery that includes both a function and a WHERE clause in the main query
```
> SELECT MEAN("toads") FROM (SELECT "toads" FROM "pond") WHERE "toads" > 3
>
```
(Unexpectedly - no results)

__Expected behavior:__ 
I'd expect the query in step 4 to return the average value of `toads` calculated across values of `toad` that are greater than three:
```
name: pond
time                 mean
----                 ----
1970-01-01T00:00:00Z 6.5
```

__Actual behavior:__
The query in step 4 returns no results.

__Additional information:__ 
Queries with a subquery, a function in the main query, and a `WHERE` time clause in the main query behave as expected:
```
> SELECT MEAN("toads") FROM (SELECT "toads" FROM "pond") WHERE time >= '2017-02-22T17:44:43.444176616Z' AND time <= '2017-02-22T17:44:49.651820179Z'
name: pond
time                           mean
----                           ----
2017-02-22T17:44:43.444176616Z 6.5
```

Taken from a Google Groups post: https://groups.google.com/forum/#!topic/influxdb/MOSSMVdFz2g

**Comment by emmenko** [comment]
This also relates to this other thread https://groups.google.com/d/msg/influxdb/JSm6cdgeSPE/5cwpWP-qAwAJ
