### ISSUE TITLE
[feature request] EXPLAIN for continuous queries

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/influxdb#8046]
### Feature Request

__Proposal:__ Add an `EXPLAIN CONTINUOUS QUERY` statement to print stats about a continuous query.

__Current behavior:__ A continuous query must be created and the user has to look in the logs after the continuous query runs to determine what was actually run, whether it worked, and what it actually produced.

__Desired behavior:__ An `EXPLAIN CONTINUOUS QUERY` statement that would allow the user to enter the equivalent of a `CREATE CONTINUOUS QUERY` statement, but would output some basic stats about the continuous query, like:
- Timestamps of the next 5 times the CQ would be schedule to run.
- Example of the generated continuous query output as a compiled query (probably for the most recent time the CQ would have been executed).
- Display of results of the generated continuous query.
- Display how long the CQ took to execute.
- Optional: return additional query suggestions, warnings, or errors if applicable.

__Use case:__ At them moment, a user has to execute a CQ to debug and test it, which is slow and hard to do for some CQs that run on larger time ranges. The actual query executed can mostly be inferred, but it's hard to also determine the exact times the CQ would run and all the separate queries that would be generated.

**Comment by kostasb** [comment]
**Enhancement Request:** Also add a `TRIGGER CONTINUOUS QUERY` statement that will force-trigger a continuous query to run now. The query should be able to run on the current time range specified by its `group by` clause, or use a specified `FOR` time range.

**Comment by timhallinflux** [comment]
Proposed: start by adding logging of the query and execution stats for CQs rather than introducing a new meta query.

Add:
```
[continuous-query]
logging-enabled = false
```
