### ISSUE TITLE
[feature request] Retention Policy for Empty Series

### ISSUE THREAD

**Issue by thoHeinze** [influxdata/influxdb#8048]
We use influxdb to store monitoring data of our SPARK jobs. Each SPARK job creates a small number of individual series. Given that we have many short-living Spark jobs, the number of series increases currently roughly by 10000 series per day. The data gets been deleted after some time due to the retention policy. But the series stay, which influences the overall performance of influxdb after some time. 

Is there a way to define a retention policy, which automatically deletes all series of a certain pattern (maybe only if the series is empty)? 

An alternative solution would be if influxdb would support a new case for DROP SERIES to drop only empty series, something like "DROP SERIES from /*.spark.*/ IF EMPTY;" (to allow to delete the series using a cron job or similar). 

This feature request results from an outtage we observed in one of our landscapes, where influxdb became unresponsive until we manually dropped many Spark-related series.

__System info:__
*  we started with InfluxDB 1.0.2, during our investigation we updated to 1.1.0. 
*  we use a single node setup with Ubuntu 14.04 LTS and a c4.xlarge on AWS. 

__Additional info:__  
* our Retention policy: CREATE RETENTION POLICY metrics_default ON metrics DURATION 7d REPLICATION 1 DEFAULT;
* when we started our investigation we had about 800,000 series inside our influxdb. 
* influxdb used up to 4GB RAM
* opening a simple grafana dashboard with 10 to 15 charts (refresh time 1 min; we optimized all queries based on influxdb recommendations) resulted in 100% CPU consumption. 
* afterwards we manually dropped all SPARK-related series (without checking if they were empty; but most of them should be empty due to the retention policy) and now we have only 97000 series, 950 MB RAM  usage and the dashboard response time is ok.

**Comment by jwilder** [comment]
We need more information in order to diagnose what is going on.  Can you update the issue description with the instructions listed in our [issue template](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md)?

What version are you running?  The series are removed from the index when there is no more data on disk.

**Comment by thoHeinze** [comment]
Hi @jwilder I added some information about our setup. Please let me know if you need additional information.

**Comment by fabiopedrosa** [comment]
This issue is also important for me.

I have a lot of empty series that should just be deleted after RP is enforced.

**Comment by fabiopedrosa** [comment]
@jwilder any news on this?

**Comment by GerryLon** [comment]
how is the end?

**Comment by GerryLon** [comment]
In my case, empty series exist, how can I delete it(line with mark *// 4*)?
```
> show series from test;
key
---
test // 4
test,type=rtt
test,type=status
```

Many Thanks!

**Comment by dbk-rabel** [comment]
Why is this issue closed? Is it already possible to delete empty series automatically?

**Comment by nimrodfeae** [comment]
Any news on this?
