### ISSUE TITLE
select * from device_stats limit 10 == dead database

### ISSUE THREAD

**Issue by simonmorley** [influxdata/influxdb#8059]
Running that query on a db with 87m rows not only kills the server but corrupts the whole freaking disc.

We're running in GCE with 8Gb ram, 2 CPUs. First time I did it, we had to recover from a snapshot. 

Second time, I thought we wouldn't have the problem. But.. same issue. Dead drive. Snapshot time.

Third time lucky, I'm not going to risk it.

We started with 1.1 and are now using 1.2.0 both the same. So, I'm happy to NOT run that command but it's a bit naff...

**Comment by e-dard** [comment]
@simonmorley thanks for the report. You're describing some strange behaviour there, so we would certainly like to get some more information.

The query you describe is read-only, so it shouldn't be modifying the database on-disk in anyway. There is still some optimisations to make I believe with `LIMIT N`, but the corruption is the more important thing in this issue.

 - Is the corruption limited to certain directories?
 - How are you validating that the data is corrupted?
 - Can you provided any logs or more information from the server or OS?
