### ISSUE TITLE
Error when writing field value that contains single quotes

### ISSUE THREAD

**Issue by mattibf** [influxdata/influxdb#8060]
### Bug report

__System info:__ InfluxDB V1.1.1, OS: CentOS 7.2

We recently started to switch to InfluxDB 1.1, moving from JSON to influxDB line protocol.
Now, we have an issue with values for fields of type string:
If the string contains a single quote (i.e. ') an error is returned (400, bad request: unable to parse, unbalanced quotes). Escaping the single quotes doesn't resolve the problem.
According to documentation, escape char in string values for fields is only necessary for double quotes.
Using double quotes and escaping them does work, but doesn't resolve the problem: The string to be stored contains single quotes. 

__Steps to reproduce:__
The issue can be easily reproduced using curl: 
1. [First Step]
curl -i -XPOST 'http:...:8086/write?db=abc&rp=&precision=ms' --data-binary 'http_status, component=def error="error111 'Connection refused'."
__Expected behavior:__ rc=2xx (OK)
__Actual behavior:__ 400 (Bad Request), error: unable to parse ...error=\"error111 Connection':  unbalanced quotes"
(Note: Pls. note the single and double quotes in the reported error message)
2. [Second Step]
The same statement works without problems if the string between single quotes doesn't contain a space, i.e.: ...error="error111 'Connectionrefused'."

**Comment by e-dard** [comment]
@mattibf I'm unable to reproduce this using the Influx CLI client. It could be to do with how cURL or your terminal handles the quoting?

```
$ influx
>
> insert http_status,component=def error="error111 'Connection refused'."
>
> SELECT * FROM http_status
name: http_status
time                component error
----                --------- -----
1488199439985171242 def       error111 'Connection refused'.
>
>
```

**Comment by phemmer** [comment]
This is a shell quoting issue. Firstly, the command given cannot be the full command, as if entered exactly as is, the shell is going to wait for another single quote to be entered because it wasn't closed. However assuming that there is a trailing single quote that wasn't provided in the example, 
the `curl` command is going to be wordsplit into the following arguments:

1. `curl`
2. `-i`
3. `-XPOST`
4. `http:...:8086/write?db=abc&rp=&precision=ms`
5. `--data-binary`
6. `http_status, component=def error="error111 Connection`
7. `refused."`

**Comment by mattibf** [comment]
Many thanks for your quick answers.
@phemmer: Of course, you're right, regarding the missing single quote at the end. However, it has been used for the test.
@e-dard, @phemmer: Thanks for your hints, we'll check this. I'll update the issue accordingly after our tests.

**Comment by mattibf** [comment]
Hello, everybody,

Many thanks for your input.
We used the curl to reproduce an issue we had when writing data from Java.
However, the error that occurred was not exactly the same, what we didn't recognize before.
Now, the issue has been resolved.
Many thanks for your quick help!
