### ISSUE TITLE
[Query Fuzz] Query doesn't return

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#8061]
This issue was found by fuzzing the database with a query generator tool. It may be possible to simplify the query to help identify the root cause.

##### Dataset
```
$ curl https://s3.amazonaws.com/noaa.water-database/NOAA_data.txt -o NOAA_data.txt
$ influx -import -path=NOAA_data.txt
```

##### Query

```
USE NOAA_water_database

SELECT  BOTTOM("index", 380),   BOTTOM("water_level", "location","randtag","location", 7),   BOTTOM("index", 6356) FROM  "h2o_quality" GROUP BY "__" ORDER BY time DESC
```

##### Result

The query hangs. Heap remains very low, no CPU activity.

See attached `SIGQUIT` on the server.

I have managed to simplify a query that triggers this issue to: 
```
SELECT    BOTTOM("index", 1),   BOTTOM("water_level", "location","randtag","location", 7), BOTTOM("index", 10) FROM  "h2o_quality"
```

[1488215779326390930.txt](https://github.com/influxdata/influxdb/files/804443/1488215779326390930.txt)

**Comment by jsternberg** [comment]
Same as my comment in #8065. I think we shouldn't allow this type of query.

**Comment by jsternberg** [comment]
Closing in favor of #8065.
