### ISSUE TITLE
[Query Fuzz] Query doesn't return

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#8065]
This issue was found by fuzzing the database with a query generator tool. It may be possible to simplify the query to help identify the root cause.

##### Dataset
```
$ curl https://s3.amazonaws.com/noaa.water-database/NOAA_data.txt -o NOAA_data.txt
$ influx -import -path=NOAA_data.txt
```

##### Query
```
SELECT    BOTTOM("degrees", "location", 5)  AS "_",   NON_NEGATIVE_DERIVATIVE("degrees") +   STDDEV("water_level") FROM  "h2o_temperature"
```

##### Results

The query hangs. Heap remains low, no CPU activity.

Possibly related to #8061 but there is only one `BOTTOM`, so it's possible this is a different issue.

[1488220069229540178-freeze.txt](https://github.com/influxdata/influxdb/files/804741/1488220069229540178-freeze.txt)

**Comment by jsternberg** [comment]
I think this query shouldn't be possible. @jwilder thoughts? I'm of the opinion that anything involving `TOP()` and `BOTTOM()` should just be by themselves.
