### ISSUE TITLE
[Query Fuzz] FILL(linear) hangs query

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#8068]
This issue was found by fuzzing the database with a query generator tool. It may be possible to simplify the query to help identify the root cause.

Possibly dupe of #8067.

##### Dataset
```
$ curl https://s3.amazonaws.com/noaa.water-database/NOAA_data.txt -o NOAA_data.txt
$ influx -import -path=NOAA_data.txt
```

##### Query

```
USE NOAA_water_database

SELECT  "index" - "index" * "water_level" FROM  "h2o_quality" GROUP BY "c","F" FILL(linear)
```

##### Result

The query hangs. Heap remains very low, no CPU activity.

See attached `SIGQUIT` on the server.

[1488220965147175060-freeze.txt](https://github.com/influxdata/influxdb/files/804789/1488220965147175060-freeze.txt)

**Comment by jsternberg** [comment]
This happens for the reasons listed in [this comment](https://github.com/influxdata/influxdb/issues/8067#issuecomment-284008144) and because `FILL(linear)` was never implemented for expressions so `FILL(linear)` has a bug where it acts the exact same as `FILL(none)`.

**Comment by jsternberg** [comment]
I'm merging this with #8067.
