### ISSUE TITLE
[1.2.0]multiple function with mathematical operator return different line

### ISSUE THREAD

**Issue by kauchy** [influxdata/influxdb#8072]
### Bug report

__System info:__ [1.2.0, CentOS 7]

__Steps to reproduce:__

1. Insert the following data
```
test value=1 1488252141000000000
test value=2 1488252151000000000
test value=3 1488252161000000000
```
2. Call max(),min() function with multiply
```
SELECT max("value")*1000,min("value")*1000 from test where time>1488252131s
```

__Expected behavior:__

```
time                max  min 
----                ---  ---
1488252131000000000 3000 1000
```

__Actual behavior:__
```
time                max  min 
----                ---  ---
1488252141000000000      1000
1488252161000000000 3000    
```

__Additional info:__

if  delete the multiply operator,the result is what I expected
```
SELECT max("value"),min("value") from test where time>1488252131s

time                max min 
----                --- ---
1488252131000000000 3   1 
```
and in old version(v0.11.0),the result is always return 1 line with start query time.

**Comment by jsternberg** [comment]
It looks like it somehow got tricked into thinking that you had two selectors and didn't normalize the time for each one. I'll take a look at it.

**Comment by jsternberg** [comment]
Closing this in favor of #8167.
