### ISSUE TITLE
[Feature request] Extra function: NEAR()

### ISSUE THREAD

**Issue by Kortenbach** [influxdata/influxdb#8073]
For SELECTing with GROUP BY time() I would like to suggest a new kind of function NEAR(). Unlike MAX(), MIN(), MEAN() etc. NEAR() doesn't take all samples within an interval into account. It only takes the samples nearest to the ones you request.

Example: 
- Samples are taken every second and put into the database
- GROUP BY time(60s) requests data with 60s intervals
- If MEAN() would be used, all samples of a one minute interval are needed for a correct result.
- If NEAR() would be used, only the sample nearest to the minute boundery is needed.

A similar function could use the previous and the next sample and interpolate between them to create a new 60s interval sample.

Best regards,
Bert Kortenbach

**Comment by phemmer** [comment]
It sounds like you want [`first`](https://docs.influxdata.com/influxdb/v1.2/query_language/functions/#first) and [`last`](https://docs.influxdata.com/influxdb/v1.2/query_language/functions/#last), as well as [`fill(linear)`](https://docs.influxdata.com/influxdb/v1.2/query_language/data_exploration/#group-by-time-intervals-and-fill)

**Comment by Kortenbach** [comment]
Sounds like you are right. First and Last might do the trick...
Ik will look into it!

**Comment by Kortenbach** [comment]
OK, `last` seems to do what I want, but I don't know how to do the interpolation between `last` and `first` (the two nearest samples)...

**Comment by Kortenbach** [comment]
For now I'll leave it at this.
Thanks for the tip!
