### ISSUE TITLE
[1.2.0] insert historical data

### ISSUE THREAD

**Issue by mkren** [influxdata/influxdb#8076]
### Bug report

__System info:__ [ influxdb_1.2.0, Ubuntu 14.04, 8GB RAM]

__Steps to reproduce:__

1. InfluxDB install
```
sudo dpkg -i influxdb_1.2.0_amd64.deb
sudo service influxdb start
```

2. Historical data to insertion - average temperature for each day from year 1775 to 2016
```
 wget http://www.deskriptiva.com/temperature.txt
head -n 4 temperature.txt
prg_weather t_avg=-7.0 -6153541064
prg_weather t_avg=-2.2 -6153454664
prg_weather t_avg=-1.0 -6153368264
prg_weather t_avg=0.1 -6153281864

wc temperature.txt
  88054  264162 3006853 temperature.txt

```

3. Insert
```
curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE historical_data"
time curl -i -XPOST 'http://localhost:8086/write?db=historical_data&precision=s' --data-binary @temperature.txt

...

HTTP/1.1 500 Internal Server Error
{"error":"timeout"}

...

influx
Failed to connect to http://localhost:8086: Get http://localhost:8086/ping: dial tcp 127.0.0.1:8086: getsockopt: connection refused
Please check your connection settings and ensure 'influxd' is running.




```

__Expected behavior:__ insertion 88054 points to DB  

__Actual behavior:__ Server Error and "sudo service influxdb restart" does not help

**Comment by jwilder** [comment]
You'll need to alter the shard group duration of your retention policy if you are writing that far into the past.  By default, it would use 1w shards which would create about 44K shards with that time span.  I'd suggest increasing that to several years to reduce the number of shards you have.  

For backfilling data, you may also need to lower snapshot write cold duration to avoid having all of your data held in cache for every shard:
```
[data]
cache-snapshot-write-cold-duration = "10s"
```
