### ISSUE TITLE
Can't drop measurement that contains double quotes in name

### ISSUE THREAD

**Issue by bogdanveres** [influxdata/influxdb#8086]
By mistake a new measurement with the name: DEVICE_1_US_21" was created. Now I want to drop this measurement using:

`DROP MEASUREMENT DEVICE_1_US_21"`

This will return the following error message:

`ERR: error parsing query: found BADSTRING, expected identifier at line 1, char 32`

Is there a way to escape the double quote and delete the measurement?

**Comment by mark-rushakoff** [comment]
Enclose the measurement with double quotes and use a backslash to escape the embedded double quote.

```
> create database test
> use test
Using database test
> insert measurement_with_quote" n=0i
> show measurements
name: measurements
name
----
measurement_with_quote"

> drop measurement measurement_with_quote"
ERR: error parsing query: found BADSTRING, expected identifier at line 1, char 39
> drop measurement measurement_with_quote\"
ERR: error parsing query: found \, expected ; at line 1, char 40
> drop measurement "measurement_with_quote\""
> show measurements
```

**Comment by aschmied** [comment]
On a related note I am unable to delete a measurement named `mea \ with _ *@$^,[){;?"' // surement` although it appears to work. Using Influx shell v1.0.2 connected to InfluxCloud 1.7.8

```
> show measurements
name: measurements
------------------
name
mea \ with _ *@$^,[){;?"' // surement

> drop measurement "mea \\ with _ *@$^,[){;?\"' // surement"
> show measurements
name: measurements
------------------
name
mea \ with _ *@$^,[){;?"' // surement
```
