### ISSUE TITLE
Wrong SELECT result when regular expressions used in FROM

### ISSUE THREAD

**Issue by pga23** [influxdata/influxdb#8089]
### Bug report

__System info:__
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-65-generic x86_64, InfluxDB 1.2.0

__Steps to reproduce:__

1. create example database
2. insert the following data:
```
mydata_1 value=1
mydata_2 value=2
mydata_3 value=3
```
3. execute 1st query:
```
SELECT * FROM /mydata_.+/
```
4. execute 2nd query:
```
SELECT time, value FROM /mydata_.+/
```

__Expected behavior:__
Both queries should return the same results

__Actual behavior:__ [What actually happened]
1st query returns correct data
2nd query returns no data

__Additional info:__
Works correctly in InfluxDB < 1.2.0

**Comment by mark-rushakoff** [comment]
Looks like this is working correctly on HEAD of the 1.2 branch (fab0b86dc3d69e85c218296220fb9c4b321eb465) and on v1.2.1-rc5. 

```
> use test
Using database test
> insert mydata_1 value=1
> insert mydata_2 value=2
> insert mydata_3 value=3
> SELECT * FROM /mydata_.+/
name: mydata_1
time			value
----			-----
1488477069852545590	1

name: mydata_2
time			value
----			-----
1488477075403540074	2

name: mydata_3
time			value
----			-----
1488477078339596962	3

> SELECT time, value FROM /mydata_.+/
name: mydata_1
time			value
----			-----
1488477069852545590	1

name: mydata_2
time			value
----			-----
1488477075403540074	2

name: mydata_3
time			value
----			-----
1488477078339596962	3
```

I'm not sure exactly which commit fixed this, but I'm closing this issue.
