### ISSUE TITLE
[0.9.3] Unable to make queries on localhost:8086

### ISSUE THREAD

**Issue by michaeleco** [influxdata/influxdb#8107]
On a Odroid C1+ card (RPi like) i have installed influxdb 0.9.3 and use influxdb python (version 2.3.0) for communication.
Sometimes, when i restart my Odroid card i can't make queries on influxdb server with my python script.
So i tried `curl` command directly on influxdb and curl stay in infinite loop request. 

Here i put my process to test this issue:

1. Influxdb log at restart:

> [srvr] 2017/03/08 02:07:04 GOMAXPROCS set to 4
> [srvr] 2017/03/08 02:07:04 using configuration at: /root/influxdb.conf
> [srvr] 2017/03/08 02:07:04 influxdb started, version 0.9, commit unknown
> [srvr] 2017/03/08 02:07:04 Cluster server listening on [::]:8086
> [srvr] 2017/03/08 02:07:15 broker opened at /root/.influxdb/broker
> [raft] 2017/03/08 02:07:15 stopped[1]: log open: created at /root/.influxdb/broker/raft, with ID 1, term 1, last applied index of 27901046
> [raft] 2017/03/08 02:07:15 log open: promoting to leader immediately
> [srvr] 2017/03/08 02:07:15 broker already member of cluster.  Using existing state and ignoring join URLs
> [srvr] 2017/03/08 02:07:15 Loading metadata index for datapoints
> [srvr] 2017/03/08 02:07:16 data node(1) opened at /root/.influxdb/data
> [messaging] 2017/03/08 02:07:16 connected to broker: http://localhost:8086/messaging/messages?index=26095014&streaming=true&topicID=0
> [messaging] 2017/03/08 02:07:16 connected to broker: http://localhost:8086/messaging/messages?index=846138&streaming=true&topicID=1
> [srvr] 2017/03/08 02:07:17 data node already member of cluster. Using existing state and ignoring join URLs
> [srvr] 2017/03/08 02:07:17 authentication enabled: false
> [srvr] 2017/03/08 02:07:17 broker enforcing retention policies with check interval of 10m0s
> [srvr] 2017/03/08 02:07:17 shard group pre-create with check interval of 45m0s
> [srvr] 2017/03/08 02:07:17 snapshot server listening on 0.0.0.0:8086
> [srvr] 2017/03/08 02:07:17 admin server listening on :8083
> [srvr] 2017/03/08 02:07:17 Not running continuous queries. [continuous_queries].disabled is set to true.
> [srvr] 2017/03/08 02:07:17 API server listening on 0.0.0.0:8086
> [messaging] 2017/03/08 02:07:17 connected to broker: http://localhost:8086/messaging/messages?index=27901046&streaming=true&topicID=9
> [messaging] 2017/03/08 02:07:18 connected to broker: http://localhost:8086/messaging/messages?index=8178760&streaming=true&topicID=4
> [messaging] 2017/03/08 02:07:18 connected to broker: http://localhost:8086/messaging/messages?index=2688366&streaming=true&topicID=2
> [messaging] 2017/03/08 02:07:18 connected to broker: http://localhost:8086/messaging/messages?index=20675820&streaming=true&topicID=7
> [messaging] 2017/03/08 02:07:18 connected to broker: http://localhost:8086/messaging/messages?index=16076566&streaming=true&topicID=6
> [messaging] 2017/03/08 02:07:18 connected to broker: http://localhost:8086/messaging/messages?index=11826774&streaming=true&topicID=5
> [messaging] 2017/03/08 02:07:18 connected to broker: http://localhost:8086/messaging/messages?index=5132613&streaming=true&topicID=3
> [messaging] 2017/03/08 02:07:18 connected to broker: http://localhost:8086/messaging/messages?index=26129635&streaming=true&topicID=8
>[broker] 2017/03/08 02:17:14 executing truncation check for 10 topic(s)
  
my influxdb.conf:

> hostname = "localhost"
> bind-address = "0.0.0.0"
> port = 8086
> reporting-disabled = false
> 
> [initialization]
>   join-urls = ""
> 
> [authentication]
>   enabled = false
> 
> [admin]
>   enabled = true
>   port = 8083
> 
> [api]
>   bind-address = ""
>   port = 0
>   ssl-port = 0
>   ssl-cert = ""
>   read-timeout = "0"
> 
> [collectd]
>   bind-address = ""
>   port = 0
>   database = ""
>   enabled = false
>   typesdb = ""
> 
> [opentsdb]
>   address = ""
>   port = 0
>   enabled = false
>   database = ""
>   retention-policy = ""
> 
> [udp]
>   enabled = false
>   bind-address = ""
>   port = 0
> 
> [broker]
>   dir = "/root/.influxdb/broker"
>   enabled = true
>   truncation-interval = "10m0s"
>   max-topic-size = 52428800
>   max-segment-size = 10485760
> 
> [raft]
>   apply-interval = "10ms"
>   election-timeout = "1s"
>   heartbeat-interval = "100ms"
>   reconnect-timeout = "10ms"
> 
> [data]
>   dir = "/root/.influxdb/data"
>   enabled = true
>   retention-auto-create = true
>   retention-check-enabled = true
>   retention-check-period = "10m0s"
>   retention-create-period = "45m0s"
> 
> [snapshot]
>   enabled = true
> 
> [logging]
>   http-access = true
>   write-tracing = false
>   raft-tracing = false
> 
> [monitoring]
>   enabled = false
>   write-interval = "1m0s"
> 
> [debugging]
>   pprof-enabled = false
> 
> [continuous_queries]
>   recompute-previous-n = 2
>   recompute-no-older-than = "10m0s"
>   compute-runs-per-interval = 10
>   compute-no-more-than = "2m0s"
>   disabled = true

My upstart scrit:

> description     "InfluxDB"
> 
> start on runlevel [2345]
> stop on runlevel [016]
> 
> respawn
> 
> pre-start script
>         rm -rf /root/.influxdb/data/messaging
> end script
> 
> exec /root/influxd -config /root/influxdb.conf

My distro:
Linux Odroid 3.10.80-131 #1 SMP PREEMPT Thu Oct 15 19:53:29 BRT 2015 armv7l armv7l armv7l GNU/Linux

On a terminal i tried:
`curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=datapoints" --data-urlencode "q=SHOW SERIES"`

This command does not return response (it seems infinite loop)

Next, i tried:
`curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=datapoints" --data-urlencode "q=SHOW SERIES" -m 5 -vvvv`

and response is:

> * Hostname was NOT found in DNS cache
> *   Trying 127.0.0.1...
> * Connected to localhost (127.0.0.1) port 8086 (#0)
> > GET /query?pretty=true&db=datapoints&q=SHOW%20SERIES HTTP/1.1
> > User-Agent: curl/7.35.0
> > Host: localhost:8086
> > Accept: */*
> >
> * Operation timed out after 5001 milliseconds with 0 bytes received
> * Closing connection 0
> curl: (28) Operation timed out after 5001 milliseconds with 0 bytes received 

It's annoying because the problem is random every time I restart my card. I know I use an older version of influxdb but I would like to know if this problem has already been identified and resolved for my version

Thank very much

**Comment by jwilder** [comment]
Unfortunately, 0.9.3 is no longer maintained.  You can take a look at the [changelog](https://github.com/influxdata/influxdb/blob/0.9.6/CHANGELOG.md) to see what was fixed from 0.9.3 to 0.9.6 and try upgrading to 0.9.6 to see if the issue is resolved.  I'd recommend migrating to the latest release though.  The [docs](https://docs.influxdata.com/influxdb/v1.2/administration/upgrading/) have more information about upgrading from older versions.
