### ISSUE TITLE
Query returns just ERR if the query contains TOP and the subquery GROUPs BY a tag

### ISSUE THREAD

**Issue by macckoo** [influxdata/influxdb#8112]
Hello,
I am running into a very similar issue to #7968 , supposedly fixed via #8051.

-I have the latest (with the fix merged) v1.2.1 installed and I am:

SELECTing top(value,sometag,5) from (select sum(leaves_consumed) as value from "someMeasurement" where time >= 'sometime' and time <= 'sometime' group by sometag)

In the Influx log (attached below) I get the error: "status=2/INVALIDARGUMENT".

@rossmcdonald @jsternberg is this because 'TOP' is used, is that not allowed?

*****INFLUX

    SELECT top(value,"name",2) FROM (SELECT SUM("leaves_consumed") as value FROM "giraffes" WHERE time >= '2017-01-24T22:54:00Z' AND time <= '2017-01-24T22:54:15Z' GROUP BY time(10m),"name")

actual behavior:
ERR:

expected behavior:
Should select the top 2 from the sum, and keep the tags.

*****INFLUX
As in here: (without the 'TOP')

    SELECT * FROM (SELECT SUM("leaves_consumed") FROM "giraffes" WHERE time >= '2017-01-24T22:54:00Z' AND time <= '2017-01-24T22:54:15Z' GROUP BY time(10m),"name")
    name: giraffes
    time name sum

1485298200000000000 chrono 53
1485298200000000000 graf 19
*****INFLUX
Subquery as a query seems to work:

    SELECT SUM("leaves_consumed") as value FROM "giraffes" WHERE time >= '2017-01-24T22:54:00Z' AND time <= '2017-01-24T22:54:15Z' GROUP BY time(10m),"name"
    name: giraffes
    tags: name=chrono
    time value

1485298200000000000 53

name: giraffes
tags: name=graf
time value

1485298200000000000 19

**************************LOG

    influxd[6549]: [I] 2017-03-07T12:01:10Z write udp 127.0.0.1:40532->127.0.0.1:58666: write: connection refused service=subscriber
    influxd[6549]: [I] 2017-03-07T12:01:13Z SELECT top(value, "name", 2) FROM (SELECT sum(leaves_consumed) AS value FROM gpgwp_sprint.autogen.giraffes WHERE time >= '2017-
    influxd[6549]: panic: runtime error: index out of range
    systemd[1]: influxdb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
    systemd[1]: influxdb.service: Unit entered failed state.
    systemd[1]: influxdb.service: Failed with result 'exit-code'.
    systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.
    systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.

**************************LOG

**Comment by macckoo** [comment]
Any news on this? 
Can I help somehow?

**Comment by LeJav** [comment]
Same problem for me with 1.2.2 with top and count in subquery

# influxd version
InfluxDB v1.2.2 (git: master 1bcf3ae74c6b9c4897dab68d513d056277eb24f7)

> SELECT top(Total,"tagname",3) from (SELECT count("fieldname") as "Total" FROM "my_measurement" WHERE time > now() - 600m   GROUP BY tagname)
ERR: 

in logs:

Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: panic: runtime error: index out of range
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: goroutine 795 [running]:
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: panic(0xa05e00, 0xc4200120b0)
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: github.com/influxdata/influxdb/influxql.filterIntegerByUniqueTags(0xc423b04c00, 0x5, 0x8, 0xc42227de18, 0x1, 0x1, 0xbaf1b8, 0xc423b04c00, 0x0, 0x1100000180)
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 	/root/go/src/github.com/influxdata/influxdb/influxql/call_iterator.go:1050 +0x2b6
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: github.com/influxdata/influxdb/influxql.NewIntegerTopReduceSliceFunc.func1(0xc423b04c00, 0x5, 0x8, 0xc422cf9bb8, 0xc422cf9ca8, 0xc422cf9ca8)
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 	/root/go/src/github.com/influxdata/influxdb/influxql/call_iterator.go:860 +0x45b
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: github.com/influxdata/influxdb/influxql.(*IntegerSliceFuncReducer).Emit(0xc422e118e0, 0xc422cf9bb8, 0xc4205ba9b0, 0xb)
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 	/root/go/src/github.com/influxdata/influxdb/influxql/functions.gen.go:595 +0x44
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: github.com/influxdata/influxdb/influxql.(*integerReduceIntegerIterator).reduce(0xc422f62140, 0xc421d69ef0, 0x456e30, 0xc421d69ee0, 0xc421d69ee8, 0x686fb9)
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:4131 +0x807
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: github.com/influxdata/influxdb/influxql.(*integerReduceIntegerIterator).Next(0xc422f62140, 0xbb0408, 0xc420045370, 0x0)
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:4044 +0xa1
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: github.com/influxdata/influxdb/influxql.(*integerInterruptIterator).Next(0xc422f611c0, 0xc4232c48a0, 0x9ce020, 0xc423974060)
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3432 +0x52
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: github.com/influxdata/influxdb/influxql.(*bufIntegerIterator).Next(0xc422f611e0, 0x0, 0xc424166af0, 0x0)
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:2750 +0x3c
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: github.com/influxdata/influxdb/influxql.(*integerAuxIterator).stream(0xc422f61220)
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3529 +0x32
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: created by github.com/influxdata/influxdb/influxql.(*integerAuxIterator).Start
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: 	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3515 +0x3f
Apr  7 16:24:00 az-influxdb-int az_influxdb[15]: start script for influxdb daemon
Apr  7 16:24:02 az-influxdb-int az_influxdb[15]: 


In fact, I want in output (for grafana) the value and the tagname
But if I do:
> SELECT top(Total,3),"tagname"  from (SELECT count("servicetype") as "Total" FROM "my_measurement" WHERE time > now() - 600m   GROUP BY tagname)
name: my_measurement
time                top  tagname
----                ---  -----------
1491546169804780584 1563 
1491546169804780584 149  
1491546169804780584 81   

I have nothing in tagname column...

**Comment by jsternberg** [comment]
Should be fixed by #8081.

**Comment by LeJav** [comment]
Many thanks for your work.

**Comment by jsternberg** [comment]
Fixed by #8081.
