### ISSUE TITLE
Data stuck in WAL - InfluxDB Crashed

### ISSUE THREAD

**Issue by nirvana1122** [influxdata/influxdb#8114]
I am facing a strange issue where influx DB fails to move new data from WAL to TSM.  I have cache-snapshot-memory-size = 16214400. But WAL grows to 5.5GB before crashing the InfluxDB. I have tried to restart delete the database and reexported the data twice with the same results. Any help would be greatly appreciated! I am using v1.2

**Comment by jwilder** [comment]
We need more information in order to diagnose what is going on.  Can you update the issue description with the instructions listed in our [issue template](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md)?

**Comment by nirvana1122** [comment]
For now I was able to fix the issue by forcing the engine to write TSM file more frequently by changing cache-snapshot-write-cold-duration = "1m". 

But this could be a potential bug/area for improvement. I have copied the details below. Please let me know if you need more info.

System info: InfluxDb 1.2, Windows 10. WAL on an SSD and TSM files location on a separate SSD.

Expected behavior: cache-snapshot-memory-size  was initially set at 26214400. So I expected InfluxDB to move files from WAL to TSM files after WAL reached that size.

Actual behavior: WAL grew to more than 5GB and crashed InfluxDB

Additional info: Please see the attached files.

[vars.txt](https://github.com/influxdata/influxdb/files/831585/vars.txt)
[stats.txt](https://github.com/influxdata/influxdb/files/831589/stats.txt)
[shards.txt](https://github.com/influxdata/influxdb/files/831588/shards.txt)
[heap.txt](https://github.com/influxdata/influxdb/files/831592/heap.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/831591/goroutine.txt)
[diagnostics.txt](https://github.com/influxdata/influxdb/files/831593/diagnostics.txt)
[block.txt](https://github.com/influxdata/influxdb/files/831594/block.txt)

**Comment by jwilder** [comment]
@nirvana1122 It looks like you may have been backfilling data since you have 1400+ shards going back to 2007.  If you are backfilling data, you would need to lower `cache-snapshot-write-cold-duration` as you did.  If the data is spare (e.g. something like stock tick data), you should also increase the shard duration on your retention policy to avoid creating so many shards.

**Comment by jwilder** [comment]
If this is the issue, we're working on some [docs](https://github.com/influxdata/docs.influxdata.com/issues/1046) to explain this better.

**Comment by nirvana1122** [comment]
Thank you for the recommendation.

**Comment by nirvana1122** [comment]
I created a new retention policy, but now some of my data is under autogen, and new data is under longer shard retention policy. How can I transfer the data from autogen to the new retention policy?

Thank you!
