### ISSUE TITLE
[Bug] Authentication issues with subqueries

### ISSUE THREAD

**Issue by khenderick** [influxdata/influxdb#8117]
Since InfluxDB 1.2 subqueries are supported. They work great without authentication, but once authentication is enabled, I have authentication issues using grafana.

Example query:

```
SELECT count("value") FROM (SELECT max("value") as "value", "name" FROM "output" WHERE "value" > 0 AND "type" =~ /^light$/ AND "floor" =~ /^1|2|3|255$/ AND time > now() - 12h GROUP BY time(1m), "name") WHERE time > now() - 12h GROUP BY "name"
```

Error:

```
{
  "error": "error authorizing query: invalid measurement: (SELECT max(value) AS value, \"name\" FROM output WHERE value > 0 AND type =~ /^light$/ AND floor =~ /^1|2|3|255$/ AND time > now() - 12h GROUP BY time(1m), \"name\")",
  "message": "error authorizing query: invalid measurement: (SELECT max(value) AS value, \"name\" FROM output WHERE value > 0 AND type =~ /^light$/ AND floor =~ /^1|2|3|255$/ AND time > now() - 12h GROUP BY time(1m), \"name\")"
}
```

Using:
* InfluxDB 1.2.0
* Grafana: 4.1.2

This ticket was initially (albeit with a different query) reported on the Grafana repo, but it was stated that since the authentication is in the header, it could not be a Grafana issue: grafana/grafana#7793

**Comment by jwilder** [comment]
@jsternberg

**Comment by jsternberg** [comment]
@khenderick does this look the same as #7946? I think we just released 1.2.1 either yesterday or today. Can you try that out and see if that was the same bug?

**Comment by khenderick** [comment]
It indeed is most likely a duplicate of #7946. I probably forgot to select closed issues when I searched whether the issue was already known. I'll give 1.2.1 a shot and report back.

**Comment by khenderick** [comment]
This is indeed fixed. Thanks.
