### ISSUE TITLE
DROP DATABASE is too slow for high cardinality databases

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#8118]
I have noticed for a while that DROP DATABASE is just too slow when series cardinality is reasonably high.

**Comment by sebito91** [comment]
Have you looked and/or noticed that DROP MEASUREMENT seems to have the same behavior?

https://support.influxdb.com/hc/en-us/requests/5002

**Comment by e-dard** [comment]
@sebito91 yes same underlying issue. Also affects `DROP RETENTION POLICY`. The issue is down to moving memory around in an unnecessary way. While this PR is a shortcut for the drop database fix, fixing the measurement and retention policy issues will require some more work. I'll try and take a look next week.

/cc @jwilder
