### ISSUE TITLE
tsm compaction does not remove .tmp on error (e.g. disk full)

### ISSUE THREAD

**Issue by hpbieker** [influxdata/influxdb#8123]
System info: InfluxDB 1.2.1, Linux

**Actual behavior:**
When tsm compaction failes because of disk full, it reports:
Mar 12 07:58:20 PPS-UbuntuLTS influxd[11583]: [I] 2017-03-12T06:58:20Z error compacting TSM files: write /media/db_disk/data/XXXX/autogen/84/000000294-000000003.tsm.tmp: no space left on device engine=tsm1

But the file is not removed (three hours later):
$ sudo ls -l /media/db_disk/data/XXXX/autogen/84/000000294-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 125829120 Mar 12 10:59 /media/db_disk/data/history/autogen/84/000000294-000000003.tsm.tmp

**Desired behaviour:**
The .tmp file from the compaction should be removed. (It is removed when Influx is restarted.) This is especially a problem because InfluxDB tries to compact many directories at the same time, which eats up the disk space.

Looking at the comment line 734-737 (https://github.com/influxdata/influxdb/blob/549b7adf35512e8b1fa9f7649ac2883ec134b4c2/tsdb/engine/tsm1/compact.go#L734) in tsdb/engine/tsm1/compact.go it looks like it is supposed to remove the file, but the actual implementation does not.
		// We hit an error but didn't finish the compaction.  Remove the temp file and abort.
		if err != nil {
			return nil, err
		}

**Comment by hpbieker** [comment]
I guess the files in the "files" list should be deleted in addition to the file in "fileName".

**Comment by jwilder** [comment]
Fixed via #8348
