### ISSUE TITLE
[bug] systemd script automatically enabled upon package install

### ISSUE THREAD

**Issue by bbczeuz** [influxdata/influxdb#8126]
### Bug report

__System info:__ 
InfluxDB 1.2.1 (and previous)
operating system name: RHEL 7, CentOS 7 , Debian 8

__Steps to reproduce:__

1. Install package (`yum install influxdb`, `apt-get install influxdb`)
2. `reboot`

Alternate path:

3. `systemctl disable influxd`
4. `yum update influxdb`
5. `reboot`

__Expected behavior:__ 
- Influxdb will start with the default cfg (or some manually edited cfg)
- Installed packages should not start unless manually enabled by the administrator or via some config mgmt solution.

__Actual behavior:__
- Influxd automatically enables itself
- This is potentially dangerous as it will start a daemon on the next reboot without any manual cfg actions, potentially leading to backdoors, DoS, resource exhaustion,...
- At least it's a surprising behavior as all other tools I'm aware of don't self-enable.
- It's further surprising as the next reboot could happen in weeks from now.

__Additional info:__
- I call this a bug report, not a feature request as this report tries to fix a counter-intuitive behavior.
- There might be users that got used to this IMHO surprising behavior, so removing 'systemctl enable influxd' is a potentially breaking change.

**Comment by phemmer** [comment]
It's standard practice for debian based systems for services to start (and enable) themselves automatically after install, but not on RedHat systems.

**Comment by bbczeuz** [comment]
OK, I was just outed as a mostly RHEL/Centos user. Doesn't this create issues with tools running on default configs (e.g. influxdb without any auth or infinite retention)?

**Comment by phemmer** [comment]
Well you have to create a database for there to be a retention policy at all. And that's manual.
For other services auto starting, it's practice for them to be configured to where they don't pose a vulnerability.

I'm not defending the auto-start either. I despise that practice on debian based systems.
Just saying it's standard over there. :-)

**Comment by bbczeuz** [comment]
Ok, so we probably need judging from Influxdata about auto-enabling on Debian.
- I'm against auto-enabling on any system. This follows the principle of least surprise (POLS).
- If everybody auto-enables services on Debian, following this would be POLS as well.
- The current behavior is especially surprising during updating: On a Debian system, I manually disabled the service, updated it and - pouf - it's enabled again.

**Comment by lanceshelton** [comment]
The correct behavior for a systemd service is to let systemd presets determine whether or not to enable the service on install (see`man systemd.preset`).

A typical systemd post-install script would include this:
```
if [ $1 -eq 1 ] ; then
        # Initial installation
        systemctl preset influxdb.service >/dev/null 2>&1 || :
fi
```

This allows the distribution to determine whether or not to enable the service on install.

RHEL includes the following script to disable most services by default:
/usr/lib/systemd/system-preset/99-default-disable.preset:
`disable *`

A distribution may add `enable influxdb` or `disable influxdb` to a file in /usr/lib/systemd/system-preset/ to determine whether or not influxdb should be started on install.

The current influxdb post-install script does not play nice with any of that, but if the code snippet above is used, it is left up to the distribution/administrator.

**Comment by lanceshelton** [comment]
Any thoughts on using presets?
