### ISSUE TITLE
Several files have old uber-go/zap import

### ISSUE THREAD

**Issue by clebs** [influxdata/influxdb#8127]
query_executor.go still has the old ZAP import `github.com/uber-go/zap` instead of `go.uber.org/zap` in master, although this was fixed in #7728.

It is a trivial change so I will send a PR for it right away.

**Comment by clebs** [comment]
I just analyzed and apparently there are several places where the import is still `github.com/uber-go/zap`.

Shall I update them all?

**Comment by mark-rushakoff** [comment]
Related: #8029

**Comment by clebs** [comment]
I see, thanks for the info @mark-rushakoff!
The status of this matter is quite confusing, but if there is already an issue where this is being resolved, I will close this one to avoid more confusion.

**Comment by clebs** [comment]
Closing this issue, will be fixed in #8029
