### ISSUE TITLE
Inconsistent mean() result for float data in select query with wildcards

### ISSUE THREAD

**Issue by mindkir** [influxdata/influxdb#8129]
### Bug report
__System info:__ InfluxDB version 1.1.1, Go version go1.7.4 on RHEL 5.8

__Steps to reproduce:__

1. Sample data:

>\> SELECT * FROM middleware.autogen.ProcessCpuLoad where host = 'server1' and time > 1489486800000000000 and time < 1489487100000000000
name: ProcessCpuLoad
time                    agent           appname         envtype host    mbean           metric_type     service value
>----                    -----           -------         ------- ----    -----           -----------     ------- -----
>1489486809000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0.021296218663536516
>1489486869000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0.022803487592219986
>1489486929000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0.0238255033557047
>1489486989000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0.027565341625346667
>1489487049000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0.021481916589745742

2. Select returning correct mean():

>\> SELECT mean(value) AS value FROM middleware.autogen.ProcessCpuLoad where host = 'server1' and time > 1489486800000000000 and time < 1489487100000000000 GROUP BY time(5m),*
>
>name: ProcessCpuLoad
>tags: agent=jmxtransagents, appname=demo1000, envtype=TEST, host=server1, mbean=OperatingSystem, metric_type=gauge, service=demo
>time                    value
>----                    -----
>1489486800000000000     0.023394493565310724

3. Select returning incorrect mean():

>\> SELECT mean(value) AS value FROM middleware.autogen./.\*/ where host = 'server1' and time > 1489486800000000000 and time < 1489487100000000000 GROUP BY time(5m),*
>...
>
>name: ProcessCpuLoad
>tags: agent=jmxtransagents, appname=demo1000, envtype=TEST, host=server1, mbean=OperatingSystem, metric_type=gauge, service=demo
>time                    value
>----                    -----
>1489486800000000000     **0**
>
>...

__Expected behavior:__ Both selects should return the same mean value for ProcessCpuLoad.

__Actual behavior:__ Select with wildcard return ProcessCpuLoad mean = 0

Using wildcard select in continuous queries for data downsampling destroy float data precision, eg:

>\> show continuous queries
>name: middleware
>name    query
>----    -----
>archive CREATE CONTINUOUS QUERY archive ON middleware BEGIN SELECT mean(value) AS value INTO middleware.archive.:MEASUREMENT FROM middleware.autogen./.*/ GROUP BY time(5m), * END

Result in "archive" RP is always 0:

>\> select * from middleware.archive.ProcessCpuLoad where host = 'server1' and time > 1489486700000000000
>name: ProcessCpuLoad
>time                    agent           appname         envtype host    mbean           metric_type     service value
>----                    -----           -------         ------- ----    -----           -----------     ------- -----
>1489486800000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0
>1489487100000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0
>1489487400000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0
>1489487700000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0
>1489488000000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0
>1489488300000000000     jmxtransagents  demo1000     TEST    server1 OperatingSystem gauge           demo 0

**Comment by e-dard** [comment]
@mindkir can you upgrade to 1.2 and see if this is still present?

**Comment by mindkir** [comment]
@e-dard, indeed issue is not present on version 1.2.1, thus closing.
