### ISSUE TITLE
duplicate tags in aggregation result when grouping by time period

### ISSUE THREAD

**Issue by shermster** [influxdata/influxdb#8130]
### Bug report

__System info:__ [InfluxDB 1.2.0 running on Centos 6]

__Steps to reproduce:__

There may be a simple explanation for this but I'm just struggling to understand the results I'm getting for aggregations grouped by a time period.

1. The data set being used is available here https://dl.dropboxusercontent.com/u/21030364/call_details_influxdb.zip and can be loaded using

influx -import -path=call_details_influxdb_filtered -precision=s

There are 10,000 records of timestamped call data records.

2.   I'm getting inconsistent grouping results depending on the time period specified in the where clause.

For example running the query from the 26 Feb to 10 March

select count(asterisk_uniqueid) as call_count from call_details where time >= '2017-02-26' AND time <= '2017-03-10' AND queue='ob-7018' GROUP BY call_disposition,time(1d) fill(0) order by time desc

This produces the correct result set with results for call_disposition ANSWERED and call_disposition UNANSWERED

```
name: call_details
tags: call_disposition=UNANSWERED
time                 call_count
2017-03-10T00:00:00Z 0
2017-03-09T00:00:00Z 1
2017-03-08T00:00:00Z 3
2017-03-07T00:00:00Z 1
2017-03-06T00:00:00Z 2
2017-03-05T00:00:00Z 3
2017-03-04T00:00:00Z 2
2017-03-03T00:00:00Z 0
2017-03-02T00:00:00Z 0
2017-03-01T00:00:00Z 5
2017-02-28T00:00:00Z 0
2017-02-27T00:00:00Z 0
2017-02-26T00:00:00Z 0


name: call_details
tags: call_disposition=ANSWERED
time                 call_count
2017-03-10T00:00:00Z 0
2017-03-09T00:00:00Z 9
2017-03-08T00:00:00Z 17
2017-03-07T00:00:00Z 16
2017-03-06T00:00:00Z 25
2017-03-05T00:00:00Z 41
2017-03-04T00:00:00Z 19
2017-03-03T00:00:00Z 0
2017-03-02T00:00:00Z 9
2017-03-01T00:00:00Z 31
2017-02-28T00:00:00Z 6
2017-02-27T00:00:00Z 0
2017-02-26T00:00:00Z 0
```

However if I shorten the time period for example 26 Feb to 2 March

select count(asterisk_uniqueid) as call_count from call_details where time >= '2017-02-26' AND time <= '2017-03-02' AND queue='ob-7018' GROUP BY call_disposition,time(1d) fill(0) order by time desc

I then get three results 

```
name: call_details
**tags: call_disposition=ANSWERED**
time                 call_count
2017-03-02T00:00:00Z 0
2017-03-01T00:00:00Z 31
2017-02-28T00:00:00Z 0
2017-02-27T00:00:00Z 0
2017-02-26T00:00:00Z 0

name: call_details
tags: call_disposition=UNANSWERED
time                 call_count
2017-03-02T00:00:00Z 0
2017-03-01T00:00:00Z 5
2017-02-28T00:00:00Z 0
2017-02-27T00:00:00Z 0
2017-02-26T00:00:00Z 0

name: call_details
**tags: call_disposition=ANSWERED**
time                 call_count
2017-03-02T00:00:00Z 0
2017-03-01T00:00:00Z 0
2017-02-28T00:00:00Z 6
2017-02-27T00:00:00Z 0
2017-02-26T00:00:00Z 0
```

Why is this happening?  I don't understand why there are two ANSWERED groups?

Regards,
Ian

**Comment by desa** [comment]
As mentioned in [community](https://community.influxdata.com/t/inconsistent-aggregation-results-when-grouping-by-time/206/6)
If you remove the `ORDER BY time DESC` clause everything works as expected.
```
> select count(asterisk_uniqueid) as call_count from call_details where time >= '2017-02-26' AND time <= '2017-03-02' AND queue='ob-7018' GROUP BY call_disposition,time(1d) fill(0)
name: call_details
tags: call_disposition=ANSWERED
time			call_count
----			----------
1488067200000000000	0
1488153600000000000	0
1488240000000000000	6
1488326400000000000	31
1488412800000000000	0

name: call_details
tags: call_disposition=UNANSWERED
time			call_count
----			----------
1488067200000000000	0
1488153600000000000	0
1488240000000000000	0
1488326400000000000	5
1488412800000000000	0
```

**Comment by shermster** [comment]
Thanks.  The solution of removing the order by is acceptable

**Comment by jsternberg** [comment]
If anybody runs into this issue with `ORDER BY desc` still, please comment here or make a new issue.
