### ISSUE TITLE
Influx_inspect report -h does not list <path> argument

### ISSUE THREAD

**Issue by dp1140a** [influxdata/influxdb#8145]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB 1.2 on Centos7 on Vagrant

__Steps to reproduce:__
1. influx_inspect report -detailed

__Expected behavior:__ [What you expected to happen]
Expected to see the report.

__Actual behavior:__ [What actually happened]
report: no tsm files at

__Additional info:__ [Include gist of relevant config, logs, etc.]
Looking for subcommand help shows:

[vagrant@localhost ~]$ influx_inspect report -h
Displays shard level report.

Usage: influx_inspect report [flags]

    -pattern <pattern>
            Include only files matching a pattern.
    -detailed
            Report detailed cardinality estimates.
            Defaults to "false".

There should be a way to specify the TSM file or other dir

**Comment by jwilder** [comment]
It's a positional argument.  Pass it as `influx_inspect report /path/to/shard`

**Comment by dp1140a** [comment]
Awesome.  Got it working.  Needs to be documented.
