### ISSUE TITLE
 tcp.Mux: handler not registered: 71 Connection from 127.0.0.1:50366 closed

### ISSUE THREAD

**Issue by sLuvpreet33** [influxdata/influxdb#8151]
I have just installed the influxdb and I am trying to run it using
`influxd -config /etc/influxdb/influxdb.conf`

And it shows this ,

`[httpd] 127.0.0.1 - - [17/Mar/2017:15:44:00 +0530] "POST /write?consistency=any&db=telegraf&precision=ns&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 7076aa36-0afa-11e7-8028-000000000000 48777`
`[tcp] 2017/03/17 15:44:09 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:50360 closed`
`[tcp] 2017/03/17 15:44:09 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:50362 closed`
`[tcp] 2017/03/17 15:44:09 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:50364 closed`
`[tcp] 2017/03/17 15:44:09 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:50366 closed`
`[tcp] 2017/03/17 15:44:09 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:50368 closed`
`[tcp] 2017/03/17 15:44:09 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:50370 closed`
`[tcp] 2017/03/17 15:44:09 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:50372 closed`
`[tcp] 2017/03/17 15:44:09 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:50374 closed`
`[tcp] 2017/03/17 15:44:09 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:50376 closed`
`[tcp] 2017/03/17 15:44:09 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:50378 closed`

It keeps on looping on the screen infintely unitl I do `Ctrl-C`.
While it keeps looping in this way, I opened another terminal, and I am able to create a new database and store data into it. I can also query that data from the database.

If I do `sudo service influxdb status` , it says it is inactive.

Please tell me why it keeps on looping those statements.

**Comment by sLuvpreet33** [comment]
`luvpreet@DHARI-Inspiron-3542:~/django/tutorial$ sudo service influxdb status`
`● influxdb.service - InfluxDB is an open-source, distributed, time series database`
  ` Loaded: loaded (/lib/systemd/system/influxdb.service; enabled; vendor preset: enabled)`
   `Active: inactive (dead) (Result: exit-code) since Fri 2017-03-17 15:51:33 IST; 7s ago`
    ` Docs: https://docs.influxdata.com/influxdb/`
 ` Process: 6062 ExecStart=/usr/bin/influxd -config /etc/influxdb/influxdb.conf ${INFLUXD_OPTS} (code=exited, status=1/FAILURE)`
` Main PID: 6062 (code=exited, status=1/FAILURE)`

`Mar 17 15:51:33 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Unit entered failed state.`
`Mar 17 15:51:33 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Failed with result 'exit-code'.`
`Mar 17 15:51:33 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.`
`Mar 17 15:51:33 DHARI-Inspiron-3542 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.`
`Mar 17 15:51:33 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Start request repeated too quickly.`
`Mar 17 15:51:33 DHARI-Inspiron-3542 systemd[1]: Failed to start InfluxDB is an open-source, distributed, time series database.`

**Comment by jwilder** [comment]
@sLuvpreet33 Something on that host is connecting to port `8088` instead of `8086`. Do you have a health check ping that port?  Or another application try to write data using the wrong port?

**Comment by jwilder** [comment]
See #7716 #5138.  Closing this as dup of those.

**Comment by sLuvpreet33** [comment]
I am starting it now by,

`sudo service influxdb start`

After this, I checked its status by ,
`sudo service influxdb status`

And this was the output,

`● influxdb.service - InfluxDB is an open-source, distributed, time series database`
   `Loaded: loaded (/lib/systemd/system/influxdb.service; enabled; vendor preset: enabled)`
   `Active: inactive (dead) (Result: exit-code) since Sat 2017-03-18 19:42:39 IST; 2s ago`
    ` Docs: https://docs.influxdata.com/influxdb/`
 ` Process: 11529 ExecStart=/usr/bin/influxd -config /etc/influxdb/influxdb.conf ${INFLUXD_OPTS} (code=exited, status=1/FAILURE)`
 `Main PID: 11529 (code=exited, status=1/FAILURE)`

`Mar 18 19:42:39 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Unit entered failed state.`
`Mar 18 19:42:39 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Failed with result 'exit-code'.`
`Mar 18 19:42:39 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.`
`Mar 18 19:42:39 DHARI-Inspiron-3542 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.`
`Mar 18 19:42:39 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Start request repeated too quickly.`
`Mar 18 19:42:39 DHARI-Inspiron-3542 systemd[1]: Failed to start InfluxDB is an open-source, distributed, time series database.`
 
Why is this happening?

**Comment by themukeshbansal** [comment]
Try running this command "/usr/bin/influxd -config /etc/influxdb/influxdb.conf " 
It will dispay a bind adderss failed error.
Use this command to find which process is using it. Then kill if if not needed.
sudo netstat -ltnp | grep :<port no>
