### ISSUE TITLE
System should not allow removing last admin privileges, if non-admin users exist

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#8157]
__Proposal:__ 

When one admin user exists, and one or more non-admin users exist, the system should return an error on `DROP USER <admin>` or `REVOKE ALL PRIVILEGES FROM <admin>`.

__Current behavior:__ 

If exactly one admin user exists, and one or more non-admin users exist, and either the admin user is dropped or the admin user either has all permissions revoked, it is impossible to create a new admin user while authentication is still enabled.

Example on 1.2, starting a brand new server with auth enabled:
```
# Create admin and non-admin user:
> create user admin with password 'admin' with all privileges
> auth admin admin
> show users
user  admin
----  -----
admin true
> create user u with password 'p'

# Non-admin user gets explicit unauthorized message:
> auth u p
> show queries
ERR: error authorizing query: u not authorized to execute statement 'SHOW QUERIES', requires READ on
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".

# Admin user can drop self without error:
> auth admin admin
> drop user admin

# "no user provided" error with stale credentials
> show users
ERR: error authorizing query: no user provided
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".

# Non-admin user, that was previously getting explicit permission error, 
# now sees "no user provided" error
> auth u p
> show queries
ERR: error authorizing query: no user provided
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```

(The only way I found to recover from this state is to restart the server with auth disabled, add an admin user or make the other user adjustments, and then restart with auth enabled again.)

On the other hand, dropping the last admin user when that is the _only_ user, leaves the system in a "recoverable" state:

```
# Starting from a fresh database
> create user admin with password 'admin' with all privileges
> auth admin admin
> show users
user  admin
----  -----
admin true

> drop user admin

# "Logging out" and then attempting a query, returns correct error:
> auth
username:
password:
> show queries
ERR: error authorizing query: create admin user first or disable authentication
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".

# Creating a new admin user works correctly:
> create user root with password 'root' with all privileges
> auth root root
> show queries
qid query        database duration
--- -----        -------- --------
5   SHOW QUERIES          35µs

> show users
user admin
---- -----
root true
```

__Desired behavior:__ 

Attempting to drop the last admin user, when non-admin users exist, should be disallowed.

Arguably an admin user should not be allowed to drop themselves.

__Use case:__

Prevent a silly mistake that leaves the system in a difficult-to-recover state.

**Comment by zhexuany** [comment]
@mark-rushakoff  If you do not mind, I could fix this bug.

**Comment by mark-rushakoff** [comment]
@zhexuany go ahead. Thanks!
