### ISSUE TITLE
Influxdb service not starting.

### ISSUE THREAD

**Issue by sLuvpreet33** [influxdata/influxdb#8165]
I have installed influxdb as stated on the official page, 
My system is ubuntu 16.04, and I have tried so many solutions, looking itno other issues also, but did not get anything for my problem.
It fails to start,

`luvpreet@DHARI-Inspiron-3542:/$ sudo service influxdb status`
`● influxdb.service - InfluxDB is an open-source, distributed, time series database`
  ` Loaded: loaded (/lib/systemd/system/influxdb.service; enabled; vendor preset: enabled)`
  ` Active: inactive (dead) (Result: exit-code) since Mon 2017-03-20 13:59:49 IST; 3s ago
     Docs: https://docs.influxdata.com/influxdb/`
 ` Process: 12356 ExecStart=/bin/sh -c /usr/bin/influxd -config /etc/influxdb/influxdb.conf` `${INFLUXD_OPTS} >>${STDOUT} 2>>${STDERR} (code=exite
 Main PID: 12356 (code=exited, status=1/FAILURE)`

`Mar 20 13:59:49 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Unit entered failed state.`
`Mar 20 13:59:49 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Failed with result 'exit-code'.`
`Mar 20 13:59:49 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.`
`Mar 20 13:59:49 DHARI-Inspiron-3542 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.`
`Mar 20 13:59:49 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Start request repeated too quickly.`
`Mar 20 13:59:49 DHARI-Inspiron-3542 systemd[1]: Failed to start InfluxDB is an open-source, distributed, time series database.`

and also 

`luvpreet@DHARI-Inspiron-3542:~$ journalctl -xe`

here is the output, 

`Mar 20 14:00:40 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:30:40Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:00:50 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:30:50Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:00:50 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:30:50Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:01:00 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:00Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:01:00 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:00Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:01:10 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:10Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:01:10 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:10Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:01:20 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:20Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:01:20 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:20Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:01:30 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:30Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:01:30 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:30Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:01:40 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:40Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:01:40 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:40Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:01:50 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:50Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:01:50 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:31:50Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:02:00 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:00Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:02:00 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:00Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:02:10 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:10Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:02:10 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:10Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:02:20 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:20Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:02:20 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:20Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:02:29 DHARI-Inspiron-3542 sudo[12379]: pam_unix(sudo:session): session closed for user root`
`Mar 20 14:02:30 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:30Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:02:30 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:30Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:02:40 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:40Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:02:40 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:40Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:02:50 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:50Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:02:50 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:32:50Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:03:00 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:33:00Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:03:00 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:33:00Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:03:10 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:33:10Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:03:10 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:33:10Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`
`Mar 20 14:03:20 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:33:20Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency`
`Mar 20 14:03:20 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:33:20Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`

**Comment by sLuvpreet33** [comment]
Have a look at this also,

`luvpreet@DHARI-Inspiron-3542:/$ journalctl -xe
Mar 20 14:11:14 DHARI-Inspiron-3542 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
-- Subject: Unit influxdb.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit influxdb.service has finished shutting down.
Mar 20 14:11:14 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Start request repeated too quickly.
Mar 20 14:11:14 DHARI-Inspiron-3542 systemd[1]: Failed to start InfluxDB is an open-source, distributed, time series database.
-- Subject: Unit influxdb.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit influxdb.service has failed.
-- 
-- The result is failed.
Mar 20 14:11:16 DHARI-Inspiron-3542 sudo[13682]: luvpreet : TTY=pts/11 ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/service influxdb stop
Mar 20 14:11:16 DHARI-Inspiron-3542 sudo[13682]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 20 14:11:16 DHARI-Inspiron-3542 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
-- Subject: Unit influxdb.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit influxdb.service has finished shutting down.
Mar 20 14:11:16 DHARI-Inspiron-3542 sudo[13682]: pam_unix(sudo:session): session closed for user root
Mar 20 14:11:19 DHARI-Inspiron-3542 sudo[13730]: luvpreet : TTY=pts/11 ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/service influxdb start
Mar 20 14:11:19 DHARI-Inspiron-3542 sudo[13730]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 20 14:11:19 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Start request repeated too quickly.
Mar 20 14:11:19 DHARI-Inspiron-3542 systemd[1]: Failed to start InfluxDB is an open-source, distributed, time series database.
-- Subject: Unit influxdb.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit influxdb.service has failed.
-- 
-- The result is failed.
Mar 20 14:11:19 DHARI-Inspiron-3542 sudo[13730]: pam_unix(sudo:session): session closed for user root
Mar 20 14:11:20 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:41:20Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency
Mar 20 14:11:20 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:41:20Z E! Error writing to output [influxdb]: Could not write to any InfluxDB
Mar 20 14:11:30 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:41:30Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency
Mar 20 14:11:30 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:41:30Z E! Error writing to output [influxdb]: Could not write to any InfluxDB
Mar 20 14:11:40 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:41:40Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency
Mar 20 14:11:40 DHARI-Inspiron-3542 telegraf[1285]: 2017-03-20T08:41:40Z E! Error writing to output [influxdb]: Could not write to any InfluxDB`

**Comment by betimd** [comment]
It's happening to me as well.

**Comment by sLuvpreet33** [comment]
What I do is start the influxdb with the config file, in the terminal. This does not start your process as a daemon, and you have to dedicate that terminal window to influxdb only and do stuff in other terminal.

**Comment by r4ravi2008** [comment]
Same issue for me..Any solutions?

**Comment by sLuvpreet33** [comment]
@r4ravi2008 I uninstalled it, and installed it again. That solved it.
