### ISSUE TITLE
Data lost during upgrade from 1.1.1 to 1.2.0

### ISSUE THREAD

**Issue by ashish198907** [influxdata/influxdb#8166]
### Bug report

__System info:__ [1.2.0, ubuntu]

We upgraded influx version from 1.0.0 to 1.2.0 after taking the backup of exiting data.

But after upgrade data was not visible on grafana dashboard. On Analysing we found that we have data of after upgrad and before of 31st Dec 2016. In between data (1 Jan 17 to 20 Mar 17) is lost.

We tried restoring from backup but still no luck. It seems like backup is also not having the data.

Please help on what we should do to restore the lost data.

**Comment by jaapz** [comment]
Before people can help you, you probably need to tell how you upgraded, how you backed up, how you tried to restore the backup, etc.

**Comment by arpitjain305** [comment]
Try restoring meta data first and then the actual data 
1. influxd restore -metadir /var/lib/influxdb/meta tmp/mysnapshot
2. influxd restore -database <dbname> -datadir /var/lib/influxdb/data tmp/mysnapshot
