### ISSUE TITLE
[1.2 regression] Math on multiple selectors returns distinct points

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#8167]
v1.2.1 behavior:

```
> insert metrics value=1
> insert metrics value=2
> SELECT min(value),max(value) from metrics
name: metrics
time min max
---- --- ---
0    1   2

> SELECT min(value)*1,max(value)*1 from metrics
name: metrics
time                min max
----                --- ---
1490013334977108401 1   
1490013337400734540     2
```

1.1.4 behavior:

```
> insert metrics value=1
> insert metrics value=2
> SELECT min(value),max(value) from metrics
name: metrics
time	min	max
----	---	---
0	1	2

> SELECT min(value)*1,max(value)*1 from metrics
name: metrics
time	min	max
----	---	---
0	1	2
```

May be related to https://github.com/influxdata/influxdb/issues/8072

@jsternberg

**Comment by DAfanasyev** [comment]
Looks like it is third issue about the same regression:
https://github.com/influxdata/influxdb/issues/8164

**Comment by jsternberg** [comment]
Bisect says it was introduced by subqueries. I'll be looking into this. I'll close the other issues to consolidate around this one.

Bisect says it's this commit, but it's a large one: d7c8c7c.

**Comment by timhallinflux** [comment]
@rkuchan -- please add this to the release notes for 1.2.2 enterprise as a known issue -- along with the proposed workaround.
