### ISSUE TITLE
query parser is confused by subtraction without whitespace

### ISSUE THREAD

**Issue by gsauthof** [influxdata/influxdb#8174]
### Bug report

__System info:__ 1.2.2

__Steps to reproduce:__

1. start influx CLI shell
2. enter

e.g.

    > select * from my_measurement where time > now()-1m and db='mydb';

__Expected behavior:__ 

No parse error, the same result as with:

    > select * from my_measurement where time > now()- 1m and db='mydb';

or

    > select * from my_measurement where time > now() - 1m and db='mydb';

__Actual behavior:__

this error is printed:

    ERR: error parsing query: found -1m, expected ; at line 1, char 46

__Additional info:__ 

This violates the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). I don't know any other shell/expression language that has this limitation - dealing with negative signs when parsing infix expressions is a standard exercise.

**Comment by jsternberg** [comment]
I've have to check how other scanners/parsers resolve this conflict. The reason ours has trouble with this is because it scans the tokens and sees a `DURATIONVAL` token instead of a `SUB` token. It really should be able to handle this situation.

**Comment by gsauthof** [comment]
You can look for context-dependent precedence. With a good parser generator you can use a directive to declare it for a rule - cf. e.g. [a small example in the Bison manual](https://www.gnu.org/software/bison/manual/html_node/Contextual-Precedence.html).

**Comment by jsternberg** [comment]
Thanks. I'll take a look at that. I was also just thinking of having it always produce a `SUB` token and then having `DURATIONVAL` not include the `+` or `-` and then modify the parser to handle unary operators like that. I need to investigate what a few more languages do. I know Ruby is apparently insane, but that's probably par for the course.

For example, this appears absurd, but would functionally work perfectly fine so I might just do this:

```
$ ruby -e 'puts -+-+-1'
-1
```
