### ISSUE TITLE
BUG report cumulative_sum function InfluxDB

### ISSUE THREAD

**Issue by flenning** [influxdata/influxdb#8180]
Connected to http://localhost:8086 version 1.2.1
InfluxDB shell version: 1.2.1
Ubuntu 16.04 LTS
The select cumulative sum function jumps unexpected in values of around 1000 up or down at some days, not all always, at midnight timestamp. 
I wanted to create a row of numbers, to number the timestamp for experimental calculations with time. Create a 0 as field value +1 and sum it cumulative. There are values in the fields before qurey.

select cumulative_sum("zeit" - "zeit" + 1) AS "zeit" INTO "linreg" FROM "linreg"

You can change read and write in different field keys, same result. WHERE time / GROUP BY changes nothing
result example:
2016-01-24T23:30:00Z  2302
2016-01-24T23:40:00Z  2303
2016-01-24T23:50:00Z  2304
2016-01-25T00:00:00Z  433
2016-01-25T00:10:00Z  434
2016-01-25T00:20:00Z  435
2016-01-25T00:30:00Z  436
any ideas how to fix this?

**Comment by jsternberg** [comment]
This is likely fixed by #8214. I'm going to close this for now, but can you try it out? If it's not fixed by that, I'll reopen this.
