### ISSUE TITLE
Write CQ stats to _internal

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#8188]
Make the CQ service write stats to _internal. This will provide users visibility into CQ activity and aid in troubleshooting.

**Comment by dgnorton** [comment]
- Number of CQs executed
- Number of CQ errors
- CQ durations
- Maybe node(s) that CQ was distributed to?

**Comment by stuartcarnie** [comment]
@dgnorton, what are your thoughts regarding extending the `monitor` service to provide a new API for consumers to _push_ points in addition to the current pull model. The justification for this approach is the monitor pulls aggregated statistics at a set interval (10s by default) however a service like CQs may execute queries very infrequently, resulting in many identical points until the next CQ is run. We are also forced to aggregate individual metrics and accumulate a large number of statistics in the CQ service for each CQ. By writing individual points each time a CQ is run, we can write the value immediately in addition to having accurate, point-in-time data to correlate slow queries with other system events, such as compactions, high CPU load, etc and to be able to analyze trends for individual CQs.

> Maybe node(s) that CQ was distributed to?

That information is internalized by the query and statement executors when sources are mapped to shards. We could add a new API to the executor to list the shards that will be queried for a given

**Comment by dgnorton** [comment]
@stuartcarnie This is probably a dumb question but instead of a separate API, could it use the `/write` endpoint?

Re adding an API to the executor, there have been discussions about adding an `EXPLAIN` feature or ways of retrieving info from the query engine about how a query will be executed.

**Comment by stuartcarnie** [comment]
@dgnorton it may be possible to use `/write` but we would incur additional overhead going through auth, point parsing, etc. We would also add a number of dependencies inside the CQ service as to which DB is used for statistics, which port to write to, credentials to use (if auth is enabled). A direct API on `Monitor` would be relatively easy to implement and abstracts the details of how / where to write this data. Conceivably, we could extend the monitor to send to a separate influxd instance, etc. 

Sounds like we could expand the stats when the `EXPLAIN` feature is added.

**Comment by stuartcarnie** [comment]
Fixed by #8471

**Comment by jgysel** [comment]
Although #8188 is mentioned to be part of v1.3.0 (see https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) , it looks like this is going to be released on v1.4.0. It wasn't merged to 1.3.0. The changelog on master seems to be outdated.
