### ISSUE TITLE
History file should redact passwords before saving to history

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#8190]
Statements like `create user username with password 'password'` are stored in clear text in .influx_history

This can be considered as a security vulnerability since passwords are saved in a clear text file. Passwords should be concealed in the history file.

**Comment by dgnorton** [comment]
The `auth` command also needs to strip the password.

**Comment by kostasb** [comment]
Same for `SET PASSWORD FOR <username> = '<password>'`
