### ISSUE TITLE
TestMaxSeriesLimit skipped in TSI inmem

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#8196]
`TestMaxSeriesLimit` is skipped in `tsi` branch w/ `t.Skip("TODO(edd): AWAITING SERIES CHECK FUNCTIONALITY")`.  Enabling this test fails.  This will create a regression.

It also looks like the config option has changed to `max-series-per-shard` from `max-series-per-database` which will need to be documented in the release notes.

**Comment by jwilder** [comment]
I think this limit should switch back to `max-series-per-database` and only apply to `inmem` indexes so that the functionality remains the same.  That's how we handle the `max-values-per-tag` limit as well.

We can add a `max-series-per-shard` limit for `tsi1` indexes later if needed.

**Comment by benbjohnson** [comment]
Fixed in 9fb8f1ec1d66c9ac367c4b9dc80738aa72751891.

**Comment by benbjohnson** [comment]
I kept the the `max-series-per-shard`. I wanted to get @pauldix's feedback before ripping it out. @pauldix, do we need series limits on TSI?

**Comment by pauldix** [comment]
We could have them, but I prefer not to. At the very least if we have them they should be zero by default.

**Comment by benbjohnson** [comment]
@pauldix I agree. I removed it in d2b396b.

**Comment by jwilder** [comment]
`max-series-per-database` is working again, but not the same as before. 

It should only apply on writes.  It's currently applied when shards are loaded causing shards to fail to load.  May need to disable the limit at startup and set it again after loading.

**Comment by benbjohnson** [comment]
@jwilder Fixed in 2edfb1c. The limit is ignored during load.

**Comment by jwilder** [comment]
Works like before.
