### ISSUE TITLE
Tags keys and associated values are incorrect when calling opentsdb API

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#8199]
### Bug report

__System info:__ `master` and `1.2` branch

__Steps to reproduce:__

1. Show there are no series prior to executing commands

~~~bash
$ ./influx -execute 'show series' -database=opentsdb -precision=rfc3339
key
---

~~~

2. Post the following payload via **opentsdb** API. Note the values for the tags `APPLE` and `A Foo`

~~~json
{"metric":"test.cpu", "timestamp": 1490324507, "value":18, "tags": {"APPLE":"orange", "A Foo":"bar"} }
~~~

~~~bash
$ curl -X POST -H "Content-Type: application/json" :4242/api/put -d "{\"metric\":\"test.cpu\", \"timestamp\": $(date +'%s'), \"value\":18, \"tags\": {\"APPLE\":\"orange\", \"A Foo\":\"bar\"} }"
~~~

3.
~~~bash
$ ./influx -execute 'show series' -database=opentsdb -precision=rfc3339
key
---

test.cpu,APPLE=bar,A\ Foo=orange

~~~

4.
~~~bash
$ ./influx -execute 'select * from "test.cpu"' -database=opentsdb -precision=rfc3339
name: test.cpu
time                 A Foo  APPLE value
----                 -----  ----- -----
2017-03-24T02:50:56Z orange bar   18
~~~

__Expected behavior:__ 

* **orange** should be associated with **APPLE** tag
* **bar** should be associated with **A Foo** tag

__Actual behavior:__

* **orange** was associated with **A Foo** tag
* **bar** should be associated with **APPLE** tag

## Issue

The issue lies in the [tags.HashKey][] method, which is currently [sorting][] the keys after they have been escaped, however as it [reconstructs the key][] it pulls the [escaped][] values here in the order of the original tags array.

**NOTE:** An invariant of `Tags`, assuming it is constructed from the [NewTags][] function, is the tags are always sorted by the keys. As such, if there are no escaped keys, this would not be an issue.

Also, this issue does not surface when using the line protocol, as it requires the tags already be escaped and during parsing, [sorts the tags][] if they are not already.

### Tests

The following unit test can be added to [points_test.go][] to demonstrate the specific issue

~~~go
func TestTags_HashKey(t *testing.T) {
	tags = models.NewTags(map[string]string{"A FOO": "bar", "APPLE": "orange", "host": "serverA", "region": "uswest"})
	got := tags.HashKey()
	if exp := ",A\\ FOO=bar,APPLE=orange,host=serverA,region=uswest"; string(got) != exp {
		t.Log("got: ", string(got))
		t.Log("exp: ", exp)
		t.Error("invalid match")
	}
}
~~~

[points_test.go]: https://github.com/influxdata/influxdb/blob/master/models/points_test.go
[sorting]: https://github.com/influxdata/influxdb/blob/master/models/points.go#L1794
[tags.HashKey]: https://github.com/influxdata/influxdb/blob/master/models/points.go#L1770
[reconstructs the key]: https://github.com/influxdata/influxdb/blob/master/models/points.go#L1800-L1810
[escaped]: https://github.com/influxdata/influxdb/blob/master/models/points.go#L1807
[NewTags]: https://github.com/influxdata/influxdb/blob/master/models/points.go#L1662
[sorts the tags]: https://github.com/influxdata/influxdb/blob/master/models/points.go#L449-L482

**Comment by stuartcarnie** [comment]
I am not sure which branch to create a pull request with a fix. Given the tags are always sorted after being escaped in the line protocol, I presume this behavior should duplicated in the `Tags.HashKey` function.

**Comment by jwilder** [comment]
@stuartcarnie Target `master`.
