### ISSUE TITLE
Bug report HTTP write 500 thousand data loss of 20 thousand

### ISSUE THREAD

**Issue by afreetgo** [influxdata/influxdb#8201]
## Bug report
    CentOS Linux release 7.2.1511 (Core)
    InfluxDB shell version: 1.2.0

1.  use okhttp send 500 thousand data . 
2.  open influxdb log
 `[httpd] 127.0.0.1 - root [24/Mar/2017:11:12:54 +0800] "POST /write?consistency=one&db=snbc_monitor&p=%5BREDACTED%5D&precision=n&rp=snbc_policy_30d&u=root HTTP/1.1" 204 0 "-" "okhttp/2.7.5" c5a6cba0-103f-11e7-8935-000000000000 30929
[I] 2017-03-24T03:12:54Z Write body received by handler: cpu.load.5,cpu=all,cpuNumber=2,host=512927274,sdkVersion=19,systemVersion=1 step=10i,ts="2017-03-24 11:04:31",type="Gauge",value=56.75 1490325174287000000  （exist）
cpu.load.5,cpu=all,cpuNumber=2,host=512927333,sdkVersion=19,systemVersion=1 step=10i,ts="2017-03-24 11:04:31",type="Gauge",value=30.59 1490325174287000000 （not exist）
   .... .....
`

3.  `select count(*) from "cpu.load.5"  
    result : 475648  loss :24352`

4. ` InfluxDB shell version: 1.2.0
> show stats for 'write'`
name: write
pointReq pointReqLocal req  subWriteDrop subWriteOk writeDrop writeError writeOk writeTimeout
-------- ------------- ---  ------------ ---------- --------- ---------- ------- ------------
587904   587904        2927 0            2927       0         0          2927    0

**Comment by jwilder** [comment]
Can you try w/ 1.2.2?  This may be a dup of #8084

**Comment by afreetgo** [comment]
thanks，Influxdb-java problem has been solved
