### ISSUE TITLE
segmentation violation on models.Tags.Clone

### ISSUE THREAD

**Issue by mathfool** [influxdata/influxdb#8206]
version 1.2.2, branch master, 1bcf3ae74c6b9c4897dab68d513d056277eb24f7

I use 1.2.0 and encounter issue #8022 , after upgrade to 1.2.2 still got segmentation violation

[httpd] 10.22.22.43 - - [24/Mar/2017:21:29:56 -0400] "POST /write?consistency=&db=system&precision=ns&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 8e00bc50-10fa-11e7-bdde-000000000000 1624
[httpd] 10.22.22.43 - - [24/Mar/2017:21:29:56 -0400] "POST /write?consistency=&db=inventory&precision=ms&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 8e0108bf-10fa-11e7-bddf-000000000000 1873
unexpected fault address 0x7f3858d7084a
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f3858d7084a pc=0x460f71]

goroutine 5080950 [running]:
runtime.throw(0xab6f37, 0x5)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc58df3abb8 sp=0xc58df3ab98
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc58df3ac10 sp=0xc58df3abb8
runtime.memmove(0xc422a1ddc0, 0x7f3858d7084a, 0xd)
        /usr/local/go/src/runtime/memmove_amd64.s:164 +0x371 fp=0xc58df3ac18 sp=0xc58df3ac10
github.com/influxdata/influxdb/models.Tags.Clone(0xc42391eb40, 0x4, 0x4, 0x608efe, 0xc42958e460, 0xc58df3ada8)
        /root/go/src/github.com/influxdata/influxdb/models/points.go:1685 +0x1f4 fp=0xc58df3ad58 sp=0xc58df3ac18
github.com/influxdata/influxdb/tsdb.(*Series).Tags(0xc4323cf180, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/meta.go:1639 +0x96 fp=0xc58df3ad98 sp=0xc58df3ad58
github.com/influxdata/influxdb/tsdb.(*DatabaseIndex).TagsForSeries(0xc420292f00, 0xc431ec7c70, 0x4e, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/meta.go:277 +0xbe fp=0xc58df3add0 sp=0xc58df3ad98
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefSeriesIterator(0xc420334ea0, 0xc57a9b72a0, 0xc420dc2a20, 0xc431ec7c70, 0x4e, 0xc5cbd8dea0, 0x0, 0x0, 0xc47a860440, 0x0, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1517 +0x9f fp=0xc58df3bbd0 sp=0xc58df3add0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetGroupIterators(0xc420334ea0, 0xc57a9b72a0, 0xc420dc2a20, 0xc4ec53d5d0, 0x29, 0x393, 0xc5cbd8dea0, 0xc4ec5444d0, 0x29, 0x393, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1504 +0x20d fp=0xc58df3bdc8 sp=0xc58df3bbd0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators.func1(0xc4402a1c60, 0xc45d842200, 0x20, 0x20, 0xc420334ea0, 0xc57a9b72a0, 0xc420dc2a20, 0xc5cbd8dea0, 0xc4e08d9680, 0x15)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1459 +0x12d fp=0xc58df3bf50 sp=0xc58df3bdc8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc58df3bf58 sp=0xc58df3bf50
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1460 +0x3c3

goroutine 1 [chan receive, 69 minutes]:

**Comment by rbetts** [comment]
Thank you for the update. #8022 has been re-opened and a better fix is being tested. We need to verify startup performance for larger workloads for the new approach.

**Comment by jwilder** [comment]
Fixed via #8192
