### ISSUE TITLE
Backup issues with v1.1 and v1.2

### ISSUE THREAD

**Issue by bchandramouli** [influxdata/influxdb#8208]
This is in reference to https://community.influxdata.com/t/issues-with-backup/303. Not sure if an issue was already opened for it? 

Steps to reproduce:
1. Generated on v1.1. 
2. Restore on a new server
3. On the new server backup generation does not work. On v1.1 - it silently failes. On v1.2 - it says it failed the backup... See logs below.

I am on AMI ec2-instances t2.micro. 

v1.1 - silently fails storing the data - only meta is stored
[ec2-user@ip-172-31-39-157 ~]$ influxd backup -database test1 ./influxBkup/
2017/03/26 20:48:10 backing up db=test1 since 0001-01-01 00:00:00 +0000 UTC
2017/03/26 20:48:10 backing up metastore to influxBkup/meta.08
2017/03/26 20:48:10 backing up db=test1 rp=autogen shard=21 to influxBkup/test1.autogen.00021.00 since 0001-01-01 00:00:00 +0000 UTC
2017/03/26 20:48:10 backing up db=test1 rp=autogen shard=20 to influxBkup/test1.autogen.00020.00 since 0001-01-01 00:00:00 +0000 UTC
2017/03/26 20:48:10 backing up db=test1 rp=autogen shard=19 to influxBkup/test1.autogen.00019.00 since 0001-01-01 00:00:00 +0000 UTC
2017/03/26 20:48:10 backing up db=test1 rp=autogen shard=28 to influxBkup/test1.autogen.00028.00 since 0001-01-01 00:00:00 +0000 UTC
2017/03/26 20:48:10 backing up db=test1 rp=autogen shard=36 to influxBkup/test1.autogen.00036.00 since 0001-01-01 00:00:00 +0000 UTC
2017/03/26 20:48:10 backup complete
[ec2-user@ip-172-31-39-157 ~]$ ls -al ./influxBkup/
total 44
drwxrwxr-x 2 ec2-user ec2-user 4096 Mar 26 20:48 .
drwx------ 8 ec2-user ec2-user 4096 Mar 25 21:04 ..
-rw-rw-r-- 1 ec2-user ec2-user 3917 Mar 25 19:18 meta.00
-rw-rw-r-- 1 ec2-user ec2-user 3917 Mar 25 20:26 meta.01
-rw-rw-r-- 1 ec2-user ec2-user 3917 Mar 25 20:27 meta.02
-rw-rw-r-- 1 ec2-user ec2-user 3917 Mar 25 20:34 meta.03
-rw-rw-r-- 1 ec2-user ec2-user 3917 Mar 25 20:50 meta.04
-rw-rw-r-- 1 ec2-user ec2-user 3917 Mar 25 20:59 meta.05
-rw-rw-r-- 1 ec2-user ec2-user 3917 Mar 25 21:10 meta.06
-rw-rw-r-- 1 ec2-user ec2-user 3955 Mar 26 20:12 meta.07
-rw-rw-r-- 1 ec2-user ec2-user 3955 Mar 26 20:48 meta.08

v1.2 - fails with error - only meta backed up
[ec2-user@ip-172-31-42-137 ~]$ influxd backup -database test1 ./influxBkup/
2017/03/26 20:33:29 backing up db=test1 since 0001-01-01 00:00:00 +0000 UTC
2017/03/26 20:33:29 backing up metastore to influxBkup/meta.00
2017/03/26 20:33:29 backing up db=test1 rp=autogen shard=21 to influxBkup/test1.autogen.00021.00 since 0001-01-01 00:00:00 +0000 UTC
2017/03/26 20:33:29 Download shard 21 failed copy backup to file: err=<nil>, n=0.  Retrying (0)...
2017/03/26 20:33:30 Download shard 21 failed copy backup to file: err=<nil>, n=0.  Retrying (1)...
2017/03/26 20:33:31 Download shard 21 failed copy backup to file: err=<nil>, n=0.  Retrying (2)...
2017/03/26 20:33:32 Download shard 21 failed copy backup to file: err=<nil>, n=0.  Retrying (3)...
2017/03/26 20:33:33 Download shard 21 failed copy backup to file: err=<nil>, n=0.  Retrying (4)...
2017/03/26 20:33:34 Download shard 21 failed copy backup to file: err=<nil>, n=0.  Retrying (5)...
2017/03/26 20:33:35 Download shard 21 failed copy backup to file: err=<nil>, n=0.  Retrying (6)...
2017/03/26 20:33:36 Download shard 21 failed copy backup to file: err=<nil>, n=0.  Retrying (7)...
2017/03/26 20:33:37 Download shard 21 failed copy backup to file: err=<nil>, n=0.  Retrying (8)...
2017/03/26 20:33:38 Download shard 21 failed copy backup to file: err=<nil>, n=0.  Retrying (9)...
2017/03/26 20:33:39 backup failed: copy backup to file: err=<nil>, n=0
backup: copy backup to file: err=<nil>, n=0

All logs for requested commands at: https://gist.github.com/bchandramouli/1b17b125a93636906e6fd326f1601ff0

```
curl -o block.txt "http://localhost:8086/debug/pprof/block?debug=1" 
curl -o goroutine.txt "http://localhost:8086/debug/pprof/goroutine?debug=1" 
curl -o heap.txt "http://localhost:8086/debug/pprof/heap?debug=1" 
curl -o vars.txt "http://localhost:8086/debug/vars" 
iostat -xd 1 30 > iostat.txt
influx -execute "show shards" > shards.txt
influx -execute "show stats" > stats.txt
influx -execute "show diagnostics" > diagnostics.txt
```

**Comment by bchandramouli** [comment]
In my case it turned out to be a permission issue. :( Closing this.

**Comment by christian-oudard** [comment]
@bchandramouli Having the same problem, could you elaborate on the permission issue?

**Comment by bchandramouli** [comment]
Can you check the chown where data is stored? The owner must be influxdb:influx
