### ISSUE TITLE
Duplicate data when having forecasted values

### ISSUE THREAD

**Issue by jdursel** [influxdata/influxdb#8210]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Influx 1.0.2
Debian Jessie

__Steps to reproduce:__
We have some planned energy production processes that have plannings. We are injecting the forecasts up to 5 days in advance. The day after is always filled with non-zeroes data and the last 4 days are often zeroes.
exemple: on the 22nd (@14:00), we are filling the data for the 22nd midnight to 26th midnight. The 22nd and 23rd are filled with non-zero values and 24, 25 and 26 with zeroes.
on the 23rd (@14:00), the data for the 23rd and 24 are updated with non-zeroes and the 25, 26, 27 are filled with zeroes. And so forth.

It is quite difficult to reproduce because it seems to be dependent to the current server date/time.
When the writing window is getting on the "summer time" change (March 27th this year) the zeroes are not overwritten and we get duplicate data into the measurement. 
When selecting the data, if the 27 is not in the selection, only the zeroes are selected otherwise, both are.

Remark: it is more visible with zero and non zero values, but could potentially happen with any value.

__Expected behavior:__ [What you expected to happen]
Zeroes must be overwritten

__Actual behavior:__ [What actually happened]
Duplicated timestamp data

__Additional info:__ [Include gist of relevant config, logs, etc.]

influx -execute "show shards" > shards.txt
`425	"tpm"	"default"	425	"2017-03-20T00:00:00Z"	"2017-03-27T00:00:00Z"	"2017-03-27T00:00:00Z"

431	"tpm"	"default"	431	"2017-03-27T00:00:00Z"	"2017-04-03T00:00:00Z"	"2017-04-03T00:00:00Z"	`

**Comment by steffenknott** [comment]
We have the same problem here and can confirm that it happens with non-zero values, too. For us, it happens independently of current server date/time or DST. Up to now, we faced the problem only when dealing with timestams ahead of the current time (forecast values).

**Comment by jdursel** [comment]
Since it is not linked to the summer time, I've removed the quote from the title.
