### ISSUE TITLE
Feature Request: Add handedness clause to InfluxQL

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#8213]
### Feature Request
From https://github.com/influxdata/kapacitor/issues/1258

Consider the following InfluxDB query
```sql
SELECT mean(*) FROM ... time >= '2017-03-13T17:50:00Z' AND time < '2017-03-13T17:51:00Z'
```
We will refer to **`'2017-03-13T17:50:00Z' `**  as the left boundary, lower boundary, or `tMin`.
Similarly, we will refer to  **` '2017-03-13T17:51:00Z'`** as the right boundary, upper boundary, or `tMax`.

Executing this query against InfluxDB will yield the following result
```
time                        mean
----                        ----
2017-03-13T17:50:00Z        8.083532716666666e+08
```
Note here that this is the **lower boundary** for the time interval. 

A similar operation in Kapacitor
```
batch
  |query('SELECT queryDurationNs FROM "_internal".monitor.queryExecutor')
    .period(1m)
    .every(1m)
    .align()
  |mean('queryDurationNs')
```
would result in 
```
time                        mean
----                        ----
2017-03-13T17:51:00Z        8.083532716666666e+08
```
Note here that this is the **upper boundary** for the time interval.

InfluxDB and Kapacitor choose different time boundaries.  Kapacitor chooses `tMax` and InfluxDB chooses `tMin`. The choice between using `tMax` or `tMin` is somewhat arbitrary for InfluxDB, however the same thing cannot be said for Kapacitor.

This is because of Kapacitors ability to do joins on overlapping time windows. Meaning if you were to join the mean over the last month with the the mean over the least day, you would need their resulting values to occur at the same time. Using the most recent time, `tMax`, to represent both points makes sense.

This has lead to two issues in the community: [issue](https://community.influxdata.com/t/influxdb-cq-vs-kapacitor-batch-vs-kapacitor-stream/202) and https://github.com/influxdata/kapacitor/issues/1257

__Proposal:__
Add a handedness clause to InfluxDB

Similar issues with right and left handed ness of time buckets has come up else where in InfluxDB and therefore it may be worthwhile to implement it here. 

https://github.com/influxdata/influxdb/issues/7738

__Current behavior:__ 
All queries use left handed timestamp for time.

__Desired behavior:__
Add a handedness clause to queries so that the left or right handed time values may be specified.

__Use case:__
See write up above.

**Comment by jsternberg** [comment]
cc @nathanielc

**Comment by hraftery** [comment]
+1, see https://community.influxdata.com/t/shift-timestamp-returned-by-select-query/575 for another use case.

**Comment by R-e-M** [comment]
+1
What do think about also adding a third choice being the middle of the time interval ? For example for plotting purpose, if I plot sum of values over days with GROUP BY time(), the point would be centered in the middle of the day, and not at the beginning or the end.

**Comment by hraftery** [comment]
Looks like there was some groundswell of support for this to be included in InfluxQL 2.0, but the trail went quiet. I believe this is still an important request - it provides a bit of consistency with Kapacitor and makes a whole bunch of use cases more plausible. Did anything come of it?

**Comment by rayalan** [comment]
I came across this trying to create a nice saw tooth graph by subtracting cumulative_sum(all data except this window) from cumulative_sum(all data). Being able to shift the timestamp on one of the windows seemed like the easiest way to tackle the problem, which definitely makes me interested in this issue.

**Comment by zagorsky** [comment]
When I run a Continuous Query in Kapacitor v1.5.5, it saves the results with the *left-side* timestamp, not the right-side timestamp as @desa describes above.  My workaround is to use [`|shift()`](https://docs.influxdata.com/kapacitor/v1.5/nodes/shift_node/) by the amount of the period to move the results to the right-side timestamp.
