### ISSUE TITLE
InfluxDB 1.2.1 fatal error: acquirep: invalid p state

### ISSUE THREAD

**Issue by Apollon77** [influxdata/influxdb#8217]
__System info:__ 
* Intel Nuc with Ubuntu 16.04 64 bit
* InfluxDB starting, version 1.2.1, branch master, commit 3ec60fe2649b51a85cd1db6c8937320a80a64c35
*Go version go1.7.4, GOMAXPROCS set to 2

Influxdb process crashed with 

```
acquirep: p->m=842350622720(5) p->status=1
fatal error: acquirep: invalid p state
```

The influxdb process were manually run as root inside "screen" with debug options (GOTRACEBACK=system GODEBUG=gctrace=1) while collectiong infos for #8135

complete Logfile (crash starting line 8888):
[influxdb3.txt](https://github.com/influxdata/influxdb/files/875792/influxdb3.txt)

**Comment by jwilder** [comment]
Are you able to test w/ the current nightly?  The nightly build uses go1.8.3 which may have resolved this.

**Comment by Apollon77** [comment]
I had this probem only once and upgraded kernel in the meantime which also solved the #8135 problem for me ... So will be hard to reproduce ... I can try but don't expect too much ...

**Comment by jwilder** [comment]
Ok.  Going to close this since it's either a kernel or go runtime issue.

**Comment by Apollon77** [comment]
sure, thank you for following up on it!!
