### ISSUE TITLE
Queries slow or never respond but only on certain days and when database reaches ~150G

### ISSUE THREAD

**Issue by billevans1963** [influxdata/influxdb#8221]
### Bug report

__System info:__ 
 version 1.2.1, branch master, commit 3ec60fe2649b51a85cd1db6c8937320a80a64c35

__Steps to reproduce:__
Note: This bug report follows community case: https://community.influxdata.com/t/strange-query-issues-when-database-reaches-140g/297/19

Background: 

- We are using Influx to store time series data for the last 5 working days (i.e. 7 day retention but with no data recorded on weekends).
- We aggregate data from 30+ different sources and there is a high degree of back-filling.
- Cardinality is ~5200.
- Typical queries:
-- Count the records in a specified 1 minute time period, from a specified source. 
-- Select all tags and queries using the same criteria and returning 1000 records (limit).

1. I populate influx database by running my server.
2. I let database reach about 80% loaded, which is equal to about 150G on disk.
3. I perform some queries to examine the data.

__Expected behavior:__ 
I expect "count" queries to return in 300ms or less and "select 1000" queries to return in 3000ms or less.

__Actual behavior:__ [What actually happened]
Many of the queries return within spec. However, I am also finding one day in five where data retrieval is either very slow or not successful.  When this happens, memory usage typically starts crawling up to 90% at which point kswap0 starts getting very active.  

So, for example, 

- My database has 5 days worth of data: 2017 March 21, 22, 23, 24 & 27.
- It occupies 151Gb (according to 'du' display)
- 1000 rows of data can be retrieved under 3 seconds but only if retrieved from days 21, 22, 23 and 27.
- If I try and select all tags & fields for any time period on March 24, it never returns and memory/cpu on the influx machine gradually increases.
- If I try doing a "select count(field)" for the same time period, I can sometimes (after about 10 seconds) get a count number back. However, it does not work for all fields, only some.
- Furthermore, if I do a select on only one field for the same time period it can work, but again only after several seconds.

__Additional info:__ [Include gist of relevant config, logs, etc.]

There is no obvious error reporting to the influxdb.log.

See https://gist.github.com/billevans1963/e4c0ad09ce457c78dde6573eed303924

**Comment by billevans1963** [comment]
I did another more controlled test:

- Influxdb server newly started.
- Send in a "count" query 
- When complete, send in "select"

**Observations**

1. Influx log shows that "count" querey completed in about 10 seconds. Then "select" query was issued but it never completed.
2. While running, I issued "show queries" command.  After 20 seconds the "select" query no longer showed as being active.
3. Influxdb memory went up to 95% and stayed there.
[stats.txt](https://github.com/influxdata/influxdb/files/890480/stats.txt)
[shards.txt](https://github.com/influxdata/influxdb/files/890476/shards.txt)
[heap.txt](https://github.com/influxdata/influxdb/files/890475/heap.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/890478/goroutine.txt)
[vars.txt](https://github.com/influxdata/influxdb/files/890474/vars.txt)
[block.txt](https://github.com/influxdata/influxdb/files/890477/block.txt)
[show-queries.txt](https://github.com/influxdata/influxdb/files/890479/show-queries.txt)

**Comment by jwilder** [comment]
Can you grab a `goroutine` profile while the query is running?  I see a lot of allocations due to merging values at query time.  That would hint at data being written out of order which needs to be fixed at query time (until a compaction can fix it).

**Comment by jwilder** [comment]
Also, can you try building off of `1.2` branch?  Specifically from 7119ef8 may improve this as well.
