### ISSUE TITLE
reading more than 10000 samples in influxdb python

### ISSUE THREAD

**Issue by taringoo** [influxdata/influxdb#8222]
Hi I am using python to connect to influxdb to get the data. But it seems the python client query only return 10000 samples of the database. Is there any way to increase the size of the data returned by the python query?

**Comment by tdeleeuw** [comment]
Did you checked the parameter "max-row-limit" (in the http section) of the InfluxDB server?
Note that this default value will change after upgrade to 1.2.1
See https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#v122-2017-03-14

**Comment by taringoo** [comment]
Thanks that works.
