### ISSUE TITLE
Windows build failing on tsi branch

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#8229]
AppVeyor is [complaining with](https://ci.appveyor.com/project/influx/influxdb/build/0.641-qvqathtw):

```
==1352==ERROR: ThreadSanitizer failed to allocate 0x80000 (524288) bytes of DenseSlabAllocator (error code: 1455)
FATAL: ThreadSanitizer CHECK failed: gotsan.cc:6498 "((0 && "unable to mmap")) != (0)" (0x0, 0x0)
FAIL	github.com/influxdata/influxdb/tsdb/engine/tsm 502.513s
```

According to msdn, error code `1455` is to do with the [paging file being too small](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681385(v=vs.85).aspx)

```
ERROR_COMMITMENT_LIMIT
1455 (0x5AF)
The paging file is too small for this operation to complete
```

@benbjohnson @jwilder

**Comment by jwilder** [comment]
This seems to be only an issue w/ appveyor.  I've skipped the problem tests on appveyor for now.
