### ISSUE TITLE
Number of percentiles and group by tags significantly affects performance

### ISSUE THREAD

**Issue by Williamdroullere** [influxdata/influxdb#8233]
Hi,

We observed what we could consider as an abnormal performance behaviour related to percentiles and group by computations.

The elapsed time of the query grows **significantly when new values are added** (no new tags).
Also, if we:

 - reduce the numbers of percentiles computed
and/or
 - reduce the number of tags in the group by clause

then the elapsed time of the query decrease significantly.

Our test case:

Influx: 1.2.2

1 measurement
76 numseries
624644 values
9 Tags
Tag1: nbr distinct keys: 13
Tag2: nbr distinct keys: 3
Tag3: nbr distinct keys: 76
Tag4: nbr distinct keys: 2
Tag5: nbr distinct keys: 3
Tag6: nbr distinct keys: 16
Tag7: nbr distinct keys: 76
Tag8: nbr distinct keys: 4
Tag9: nbr distinct keys: 1

Results:

Query1 duration 23 seconds:
SELECT percentile("cpu", 100) AS "max", percentile("cpu", 99) AS "99th Pctl", percentile("cpu", 90) AS "90th Pctl", percentile("cpu", 75) AS "75th Pctl", percentile("cpu", 50) AS "50th Pctl", mean("cpu")
AS "avg" FROM "testcasemeasure" GROUP BY "Tag1", "Tag2", "Tag3", "Tag4", "Tag5", "Tag6", "Tag7", "Tag8", "Tag9"

Query2 duration 6 seconds:
SELECT percentile("cpu", 100) AS "max", percentile("cpu", 99) AS "99th Pctl", percentile("cpu", 90) AS "90th Pctl", percentile("cpu", 75) AS "75th Pctl", percentile("cpu", 50) AS "50th Pctl", mean("cpu")
AS "avg" FROM "testcasemeasure" GROUP BY "Tag6"

Query3 duration 5 seconds:
SELECT percentile("cpu", 99) FROM "testcasemeasure" GROUP BY "Tag1", "Tag2", "Tag3", "Tag4", "Tag5", "Tag6", "Tag7", "Tag8", "Tag9"

Query4 duration 1 second:
SELECT percentile("cpu", 99) AS "99th Pctl" FROM "testcasemeasure" GROUP BY "Tag6"

So much performance differences between the queries is a normal behaviour?
If not, we can provide our test case.

Thanks
William

**Comment by DainDwarf** [comment]
I think I have a similar case with distinct instead of percentile, using version 1.6.0. The performance seems impacted when adding more tags to group by.

```name: running_strategies
tagKey
------
account
host
stock
timescale
version

fieldKey fieldType
-------- ---------
execid   string

> select count(*) from running_strategies where time >= '2018-07-27'
name: running_strategies
time                 count_execid
----                 ------------
2018-07-27T00:00:00Z 898355

> explain analyze  select count(distinct(execid)) from running_strategies where time >= '2018-07-27'
EXPLAIN ANALYZE
---------------
.
└── select
    ├── execution_time: 1.317090234s
    ├── planning_time: 68.933715ms
    ├── total_time: 1.386023949s
    └── build_cursor
        ├── labels
        │   └── statement: SELECT count(distinct(execid::string)) FROM influxdb_llvm.autogen.running_strategies
        └── iterator_scanner
            ├── labels
            │   └── expr: count(distinct(execid::string))
            └── create_iterator
                ├── labels
                │   ├── measurement: running_strategies
                │   └── shard_id: 402
                ├── cursors_ref: 2670
                ├── cursors_aux: 0
                ├── cursors_cond: 0
                ├── float_blocks_decoded: 0
                ├── float_blocks_size_bytes: 0
                ├── integer_blocks_decoded: 0
                ├── integer_blocks_size_bytes: 0
                ├── unsigned_blocks_decoded: 0
                ├── unsigned_blocks_size_bytes: 0
                ├── string_blocks_decoded: 2434
                ├── string_blocks_size_bytes: 10252806
                ├── boolean_blocks_decoded: 0
                ├── boolean_blocks_size_bytes: 0
                └── planning_time: 68.653108ms

> explain analyze  select count(distinct(execid)) from running_strategies where time >= '2018-07-27' group by time(5m), host
EXPLAIN ANALYZE
---------------
.
└── select
    ├── execution_time: 2.345479996s
    ├── planning_time: 70.348459ms
    ├── total_time: 2.415828455s
    └── build_cursor
        ├── labels
        │   └── statement: SELECT count(distinct(execid::string)) FROM influxdb_llvm.autogen.running_strategies GROUP BY time(5m), host
        └── iterator_scanner
            ├── labels
            │   └── expr: count(distinct(execid::string))
            └── create_iterator
                ├── labels
                │   ├── measurement: running_strategies
                │   └── shard_id: 402
                ├── cursors_ref: 2676
                ├── cursors_aux: 0
                ├── cursors_cond: 0
                ├── float_blocks_decoded: 0
                ├── float_blocks_size_bytes: 0
                ├── integer_blocks_decoded: 0
                ├── integer_blocks_size_bytes: 0
                ├── unsigned_blocks_decoded: 0
                ├── unsigned_blocks_size_bytes: 0
                ├── string_blocks_decoded: 2434
                ├── string_blocks_size_bytes: 10252806
                ├── boolean_blocks_decoded: 0
                ├── boolean_blocks_size_bytes: 0
                └── planning_time: 70.069905ms
```
