### ISSUE TITLE
getsockopt: connection refused [OOM]

### ISSUE THREAD

**Issue by lin-credible** [influxdata/influxdb#8236]
Versions:
Influxdb: `1.2.0`
OS: `CentOS Linux release 7.3.1611 (Core)`
Go: `go version go1.8 linux/amd64`

---

ERROR Messages  (**Regularity happen**)
```
Failed to connect to http://localhost:8086: Get http://localhost:8086/ping: dial tcp [::1]:8086: getsockopt: connection refused
Please check your connection settings and ensure 'influxd' is running.
```

influxdb.conf:
```
reporting-disabled = true
[meta]
  dir = "/path/to/influxdb/meta"
[data]
  dir = "/path/to/influxdb/data"
  wal-dir = "/path/to/influxdb/wal"
[coordinator]
[retention]
[shard-precreation]
[monitor]
[admin]
[http]
[subscriber]
[[graphite]]
[[collectd]]
  enabled = true
  bind-address = "my-private-ip:25826"
  database = "collectd"
  retention-policy = ""
  typesdb = "/usr/local/share/collectd/types.db"
  security-level = "none"
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "10s"
  read-buffer = 0
[[opentsdb]]
[[udp]]
[continuous_queries]
```

Some other informations:

`service influxd status -l`

![default](https://cloud.githubusercontent.com/assets/3191641/24542964/3e095732-1630-11e7-96dc-486862b44663.png)

help me :)

**Comment by lin-credible** [comment]
Maybe I got it.

`OOM`

**Comment by jwilder** [comment]
Can you attache the full crash log?

**Comment by jwilder** [comment]
Closing due to lack of information.

**Comment by lin-credible** [comment]
❤️ Sorry for this @jwilder 
I didn't check this question as there were some other more important things I need to deal with.
