### ISSUE TITLE
data is lost after changing file ownership

### ISSUE THREAD

**Issue by alparslanuysal** [influxdata/influxdb#8237]
Hi folks, I cannot not access data. I think its deleted.All measurements is lost after changing file(/var/lib/influxdb/data/mydb) ownership from root to influxdb user.

Influx version: 1.1.1
OS : Ubuntu 16.04

**Comment by zhexuany** [comment]
Have you tried to change the ownership back?

**Comment by alparslanuysal** [comment]
Yes, I tried

**Comment by jwilder** [comment]
Can you run `ls -lah /var/lib/influxdb`?  If you installed `influxdb` via the official packages, everything should be owned by `influxdb.influxdb` I believe.   If you are running `influxd` as `root` (not advised), it may have created the files owned by root.

It sounds like your file permissions are incorrect somewhere and the user running `influxd` cannot access them so they appear to be lost.
