### ISSUE TITLE
Potential error with 'SUM' calculations in 1.2.1

### ISSUE THREAD

**Issue by SonarSoftware** [influxdata/influxdb#8238]
### Bug report

__System info:__ InfluxDB 1.2.1, Ubuntu 14.04

__Steps to reproduce:__

Please see the two queries below. This is counter based data that I collect to track bandwidth utilization.

> SELECT inbytes AS inbytes, outbytes AS outbytes FROM data_usage WHERE time >= 1491015840000000000 AND time <=  1491016560000000000 AND account_id='2265' GROUP BY * ORDER BY time ASC
name: data_usage
tags: account_id=2265, data_source_identifier=ABC (2265), data_source_parent=Z-001-PROC-01 (1), data_type=Surfer* Speed (474)
time                inbytes     outbytes
----                -------     --------
1491015859883094151 66673674833 2679482286
1491015919926052882 66678679770 2679647851
1491015980020916808 66683655199 2679808824
1491016039908118147 66688269119 2680032854
1491016162486264298 66691116756 2680129238
1491016163344381646 66696054050 2680288065
1491016220257483733 66700067497 2680424138
1491016280202685491 66703869159 2680565287
1491016339933479235 66707878334 2680700737
1491016400046170372 66714004043 2680898051
1491016459917455809 66719310802 2681076410
1491016519961087522 66724682872 2681248418

This appears to be incrementing correctly and as expected. Now here are the results when I run a 'DIFFERENCE' query.

SELECT DIFFERENCE(SUM(inbytes)) AS inbytes, DIFFERENCE(SUM(outbytes)) AS outbytes FROM data_usage WHERE time >= 1491015840000000000 AND time <=  1491016560000000000 AND account_id='2265' GROUP BY *, time(1m) ORDER BY time ASC

name: data_usage
tags: account_id=2265, data_source_identifier=ABC (2265), data_source_parent=Z-001-PROC-01 (1), data_type=Surfer* Speed (474)
time                inbytes      outbytes
----                -------      --------
1491015840000000000 6277036      199808
1491015900000000000 5004937      165565
1491015960000000000 4975429      160973
1491016020000000000 4613920      224030
1491016140000000000 66698901687  2680384449
1491016200000000000 -66687103309 -2679993165
1491016260000000000 3801662      141149
1491016320000000000 4009175      135450
1491016380000000000 6125709      197314
1491016440000000000 5306759      178359
1491016500000000000 5372070      172008

You can see there are two majorly different calculations within the data, one where it rocks up to an unrealistic high value, and then flips in the other direction. I'm guessing the issue here is the 'SUM' call inside the DIFFERENCE function, but I did not see this kind of behavior prior to 1.2.x. My expectation in this call was that data would be grouped uniquely, and the SUM would not overlap boundaries (e.g. it would never SUM data from the same timestamp in two different groupings.) My only guess here is that this is what is happening.

__Expected behavior:__ I expected to see the difference between two sets of counter based data.

__Actual behavior:__ It appears additional data is being caught in the 'SUM' calculation, which I did not ever see prior to 1.2.x.

__Additional info:__ https://gist.github.com/SonarSoftware/db1200998784959239f415e96508517d

**Comment by jsternberg** [comment]
Can you try this out on master? I think this may have been fixed by #8214.

**Comment by SonarSoftware** [comment]
@jsternberg Do you think so? It looks like that fix is related to data not being ordered, but I am explicitly specifying an ORDER BY here. Is this something more underlying related to the engine itself?

**Comment by jsternberg** [comment]
`ORDER BY` doesn't really do anything other than set it to be ascending or descending. So `ORDER BY time ASC` is essentially just filler so that there's a syntax version of the opposite of `ORDER BY time DESC`.

The ordering was a bug within the query engine itself so it wouldn't be something resolvable through the query language.

The ordering thing caused a bunch of weird issues where data got fed into aggregates in the wrong order and created some weird results like this. So it's most likely the issue. If you still see it, then it might be something else, but I would bet on it being resolved now if I were a gambling man.

**Comment by SonarSoftware** [comment]
Great, thanks for the clarification. I'll give it a shot!

**Comment by jsternberg** [comment]
I'm going to close this for now. If it's still not fixed, please comment and I'll reopen this.
