### ISSUE TITLE
Failed to connect to http://localhost:8086 when I have acces to web admin interface

### ISSUE THREAD

**Issue by DAHHOU** [influxdata/influxdb#8246]
I cannot connect to The InfluxDB's command line interface when HTTPS is enabled in my config file.
My config file look like this : 

 [admin]
  #Determines whether the admin service is enabled.
   enabled = true

  #The default bind address used by the admin service.
   bind-address = ":8083"

  #Whether the admin service should use HTTPS.
   https-enabled = true

  #The SSL certificate used when HTTPS is enabled.
   https-certificate = "/etc/ssl/influxDB.pem"

[http]
  #Determines whether HTTP endpoint is enabled.
   enabled = true

  #The bind address used by the HTTP service.
   bind-address = ":8086"

  #Determines whether HTTP authentication is enabled.
   auth-enabled = true

  #The default realm sent back when issuing a basic auth challenge.
  #realm = "InfluxDB"

  #Determines whether HTTP request logging is enable.d
   log-enabled = true

  #Determines whether detailed write logging is enabled.
   write-tracing = false

  #Determines whether the pprof endpoint is enabled.  This endpoint is used for
  #troubleshooting and monitoring.
   pprof-enabled = false

  #Determines whether HTTPS is enabled.
   https-enabled = true

  #The SSL certificate to use when HTTPS is enabled.
   https-certificate = "/etc/ssl/influxDB.pem"

- When I want to acces to InfluxDB's CLI, it returns  : 
Failed to connect to http://localhost:8086
Please check your connection settings and ensure 'influxd' is running.

- Even my output influxdb on logstash don't work when HTTPS is enabled.
But the administrative interface on http://localhost:8083 is ok.

And when HTTPS is disabled everything works fine except the administrative interface.

My goal is to be able to access to both the administrative interface and the InfluxDB's CLI.

Thank you!!

**Comment by YusufLiu** [comment]
+1 having the same problem

**Comment by jwilder** [comment]
Are you running the CLI w/ `-ssl`?  It defaults to HTTP unless `-ssl` is specified.  Run `influx -h` to see other options.

**Comment by DAHHOU** [comment]
I already run it et tried what they suggest.
$ influx -ssl                  :  Failed to connect to https://localhost:8086
                                       Please check your connection settings and ensure 'influxd' is running.
$ influx -unsafeSsl       : Failed to connect to http://localhost:8086
                                      Please check your connection settings and ensure 'influxd' is running.

**Comment by jwilder** [comment]
Did you try `influx -ssl -unsafeSsl`?  `-ssl` causes HTTPS to be used.  `-unsafeSsl` is needed w/ self-signed certs.

**Comment by bsnape** [comment]
Thanks @jwilder, using `influx -ssl -unsafeSsl` worked for me.

**Comment by pgemme** [comment]
> Did you try `influx -ssl -unsafeSsl`? `-ssl` causes HTTPS to be used. `-unsafeSsl` is needed w/ self-signed certs.

Even with a valid signed certificate I still needed the -unsafeSsl because it defaults to https://localhost instead of <hostname>. Is there a way to config the URL or no?
