### ISSUE TITLE
Duplication of results on complex queries

### ISSUE THREAD

**Issue by dimiii** [influxdata/influxdb#8250]
### Bug report

__System info:__ [InfluxDB  v1.2.0, OS X 10.11.6]

__Steps to reproduce:__

1. Populate database
```
> insert bug_report current_reading=43008 1491336000000000000
> insert bug_report current_reading=43008 1491336300000000000
> insert bug_report current_reading=43008 1491336600000000000
> insert bug_report current_reading=43008 1491336900000000000

> select * from bug_report
name: bug_report
time                 current_reading
----                 ---------------
2017-04-04T20:00:00Z 43008
2017-04-04T20:05:00Z 43008
2017-04-04T20:10:00Z 43008
2017-04-04T20:15:00Z 43008

```
2.  Execute a query with aggregate functions and a query with aggregate functions and some arithmetical operations
```
> precision rfc3339
> select sum(current_reading), percentile(current_reading, 95) from bug_report 
name: bug_report
time                 sum    percentile
----                 ---    ----------
1970-01-01T00:00:00Z 172032 43008

> select sum(current_reading), 8 * percentile(current_reading, 95) from bug_report
name: bug_report
time                 sum    percentile
----                 ---    ----------
1970-01-01T00:00:00Z 172032
2017-04-04T20:15:00Z        344064

```
__Expected behavior:__ Identical shape of results i.e one row with sum and percentile values both having timestamp 1970-01-01T00:00:00Z 

__Actual behavior:__  What actually happened

**Comment by SonarSoftware** [comment]
I wonder if this is related to https://github.com/influxdata/influxdb/issues/8238 ?

**Comment by dimiii** [comment]
> if this is related to #8238

Not sure. Anyway, I found it may be regarded as a regression. At least for 

Influxdb **0.9.5.1**
Linux xxx 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I got correct results.

```
time			sum	percentile
1970-01-01T00:00:00Z	172032	43008
```

**Comment by SonarSoftware** [comment]
I didn't test on an earlier version, but the issue described in #8238 also appeared to begin occurring in 1.2.x and didn't occur previously.
