### ISSUE TITLE
Remote backup (linux -> windows)

### ISSUE THREAD

**Issue by ConfiDev** [influxdata/influxdb#8256]
I cannot do a remote backup of a linux influxdb instance from a windows machine.

I get the following error:
backup: expected database, retention policy, and shard id in path: database/years/13944

The error seems to be related to the following line.
https://github.com/influxdata/influxdb/blob/master/cmd/influxd/backup/backup.go#L381
I just assume, that "filepath.Separator" returns the windows separator "\\" which than is used to split a linux path with "/" as separator.

**Comment by shotor** [comment]
Did you manage to find a work around that doesn't involve switching to a Linux machine?

**Comment by ConfiDev** [comment]
No, I did not find any work around for that. Using a linux machine.

**Comment by hpbieker** [comment]
Any chance this will be fixed so that we can back up to Windows machines? :-)

**Comment by pkenell** [comment]
I have the sam issue, but other way around. Windows -> Linux

**Comment by nzhammer** [comment]
Same issue here, can't backup from Linux -> Windows

**Comment by darrepac** [comment]
Seems this problem is still present (trying to backup a linux influx instance from windows)
