### ISSUE TITLE
Support string comparison operators for <, >, <=, >=

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#8265]
If you have string fields and you do queries against them they return no results. We should evaluate them lexicographically.

For example:

```
insert foo val1="a",val2="b"

select * from foo where val1 < val2
- should return the row
```

The `!=` and `=` operators work as expected.

**Comment by jsternberg** [comment]
Should this also apply to tags?

**Comment by pauldix** [comment]
Probably, but I think these would show up in completely different areas of the query engine so would be best to log one issue for fields, one for tags.

**Comment by jsternberg** [comment]
They are, but they would likely need to be done together to keep overall cohesiveness in the query engine.

**Comment by Jeel-Dhamsaniya** [comment]
Hi community any updates on this?
