### ISSUE TITLE
Data still there after dropping

### ISSUE THREAD

**Issue by hongquan** [influxdata/influxdb#8278]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB 1.2.0, amd64. OS: Ubuntu 16.10 amd64.

__Steps to reproduce:__

1. Have a table `condition` with some data
2. Drop data with `DROP SERIES` and `DROP MEASUREMENT` commands
3. SELECT data again

__Expected behavior:__
The data returned should be empty.

__Actual behavior:__
Still see old data

__Additional info:__

Log: https://hastebin.com/orizobiboh.md

[influx-debug.tar.gz](https://github.com/influxdata/influxdb/files/909514/influx-debug.tar.gz)

**Comment by hongquan** [comment]
Update: The issue still there after upgrading to InfluxDB v.1.2.2
Log: https://hastebin.com/yojumiteri.md

**Comment by jwilder** [comment]
Would you be able to backup your `test_plantinghouse` database and attach it to the issue?  `influxd backup -database test_plantinghouse /path/to/backup/to`.

**Comment by hongquan** [comment]
Here you are:

[test_plantinghouse.zip](https://github.com/influxdata/influxdb/files/913849/test_plantinghouse.zip)

**Comment by hongquan** [comment]
Upgraded Ubuntu to 17.04.
The problem still exists.

**Comment by jwilder** [comment]
Looks like the repro steps that were in `hastebin` are gone.  I'm not sure how repro this.  I ran a few drops and deletes on the attached database and they all worked.
