### ISSUE TITLE
Aggretation function not working with subquery if the subquery has a WHERE clause

### ISSUE THREAD

**Issue by Stjerndal** [influxdata/influxdb#8287]
### Bug report

__System info:__ InfluxDB 1.2.2, Windows 10.

__Steps to reproduce:__ 

1. Use NOAA_data sample data like in docs.
2. Perform a query with a WHERE clause and a function. In my case:
```
> SELECT "elapsed" FROM (SELECT ELAPSED("water_level", 20m) FROM h2o_feet WHERE "water_level" > 9.5) WHERE "elapsed" > 40
name: h2o_feet
time                 elapsed
----                 -------
2015-08-29T06:30:00Z 70
2015-08-30T07:42:00Z 69
2015-08-31T09:00:00Z 71
2015-09-01T22:00:00Z 69
2015-09-02T22:42:00Z 69
2015-09-03T23:30:00Z 69
```
I.e. rougly "amount of time between water levels that are above 9.5 feet".
3. Now try to get the sum of those values using subquerying:
```
> SELECT SUM("elapsed") FROM (SELECT "elapsed" FROM (SELECT ELAPSED("water_level", 20m) FROM h2o_feet WHERE "water_level" > 9.5) WHERE "elapsed" > 40)
>
```

__Expected behavior:__ 
```
time			sum
1970-01-01T00:00:00Z	417
```
__Actual behavior:__ 
No results at all.

__Additional info:__ 
If you remove `WHERE "elapsed" > 40` from the query in step 3, a sum is calculated correctly.

**Comment by jsternberg** [comment]
This will be fixed by #8081.
