### ISSUE TITLE
Explore an idea for handling client commands on the server

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#8296]
### Feature Request

This is mostly something I've been kicking around in my head while also thinking about a new client, but I want to expand the discussion here.

For the client, we need to support commands like `USE database` for both a user-friendly experience and because people familiar with SQL are familiar with that command. While specifying the database isn't required in our system, it's still really convenient to do.

But in our system, the database being used is completely up to the client. It gets sent through a query parameter and that's the only way to do it. So at the moment, the client would need to do a partial parse of the query it's about to send to the server to check to see if it sees a client command.

But that also provides a bit of a problem. Since these queries are implemented on the client and not the server, sending a `USE database` inside of an HTTP request to the server means nothing. For those who might use the CLI to execute commands, this could end up being weird. Additionally, the parser in the client is a poor man's version of the parser in the server, but we don't really want to perform parsing on both the client and the server.

I would prefer it if we could just send the entire query to the server and it figures things out. But, while we could make that work with uploading the entire file, it could cause some issues with the client because the client doesn't keep a persistent connection to the server.

On the other hand, there are some client commands that make no sense on the server. While it might make sense to have `USE` and `INSERT` work on the server, I don't think there's a very strong case that `FORMAT` needs to be processable because that is a UI issue.

With that background...

__Proposal:__ Make some client commands processable by the server.

__Current behavior:__ Client commands have to be parsed out separately from the query and can't be interspersed easily within the query statements without putting undue pressure on the client.

__Desired behavior:__ I would like to see `USE`, `INSERT`, and probably everything except for `FORMAT` be processable by the server. I would like to see them return something within their result to indicate to the client. I would like the following query to work if done through `curl`.

```sql
USE NOAA_water_database;
SELECT count(*) FROM h2o_pH;
```

It should then include in a response something that indicates the the default database was changed so the client can change its value locally. Either as part of the JSON response or as part of the HTTP headers.

__Use case:__ Described above. It would clean up a lot of the code within the client and remove the bad parser we have there. It would also allow people to create a schema file that can be uploaded through something other than the client without requiring a custom format like `influx -import` supports.

**Comment by russorat** [comment]
closing due to age.
