### ISSUE TITLE
Regex math in fields not working if the regex is surrounded by double quotes

### ISSUE THREAD

**Issue by skyrocknroll** [influxdata/influxdb#8300]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Installed Packages
Name        : influxdb
Arch        : x86_64
Version     : 1.2.0
Release     : 1
Size        : 53 M
Repo        : installed
From repo   : /influxdb-1.2.0.x86_64
Summary     : Distributed time-series database.
URL         : https://github.com/influxdata/influxdb
License     : MIT
Description : Distributed time-series database.

Amazon Linux AMI release 2016.09
Kernel \r on an \m

__Steps to reproduce:__

1. `SELECT mean(/^25_percentile/) FROM "xxx" WHERE time > now() - 1d GROUP BY time(5m) fill(none)`
The above one works
2. `SELECT mean("/^25_percentile/") FROM "xxx" WHERE time > now() - 1d GROUP BY time(5m) fill(none)`
^^ This immediate above one is not working. 

__Desired behavior:__ [What you would like to happen]
I would expect 2 method also to be working. 

__Use case:__ [Why is this important (helps with prioritizing requests)]
We are using Grafana Template variables. Grafana fires tempated queries using the second method

**Comment by phemmer** [comment]
Sounds like a bug in grafana.

**Comment by skyrocknroll** [comment]
@phemmer The same surrounding with doubles quotes in tag values are working.

**Comment by jsternberg** [comment]
@skyrocknroll regexes shouldn't be surrounded by quotes. If you surround it with quotes, you're telling the query language that it's an identifier. That means it's looking for a measurement with the literal value `/^25_percentile/`.

This is working as designed. If Grafana is making these queries, it's an issue with their query builder not understanding the difference between a regex and an identifier.
