### ISSUE TITLE
[HELP] Calculate total time based on binary value

### ISSUE THREAD

**Issue by almottier** [influxdata/influxdb#8308]
Hello,

I am using influxdb to monitor my reservoir water level and record the pumps power (ON/OFF).
I receive the data from a LORA node, around every 10-15 seconds, it is not regular.
I would like to query the influx database to know how long the pumps were ON on the last 24 hours.
As I only insert a binary value (0 or 1), not on regular basis, I didn't find a way to do this.
Please check the screenshot from grafana, I want to know the total time of the green areas : http://i.imgur.com/G2POW9X.png
Do you have any idea how to do this ??
Thanks

**Comment by Scott-St** [comment]
Did you ever figure out a way to do this?  I have a very simular scenario.

**Comment by psellers89** [comment]
Not really...
As I don't receive the data on a regular basis, I simply execute a script every minute which record in a database the binary value. Then I simply use a count on a defined period to know how long the pump was ON. Tell me if you find a better solution.

**Comment by StephenG89** [comment]
Hey @psellers89, I've been looking for a display like this in Grafana for boolean data, how did you do it?
