### ISSUE TITLE
How to generate timestamp in python or shell ?

### ISSUE THREAD

**Issue by itfanr** [influxdata/influxdb#8311]
```
import datetime
d = datetime.datetime.utcnow() # <-- get time in UTC
print d.isoformat("T") + "Z"
print d.isoformat("T") 
```

As above, I can only get a UTC time, which cannot be imported to influxdb .But how to transfer it to timestamp that influxdb supported?

Thans you .

**Comment by jsternberg** [comment]
The issue tracker is only for bugs or feature requests. Please check out our new community website where you are more likely to get an answer for this type of question: https://community.influxdata.com

Thank you.
