### ISSUE TITLE
Last() enhancement to return the latest point by timestamp

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#8312]
Current behavior: last(X) needs a field argument to search for the latest point that stores a value for it.

Feature request: last() should also be able to search for the latest point by timestamp and return any fields and tags it finds in it.

Example:

```
> create database last_demo

> use last_demo
Using database last_demo

> insert test,host=local cpu=8,ram=9
> insert test,host=remote cpu=11

> select last(ram),cpu from test where host = 'local'
name: test
time                last cpu
----                ---- ---
1492780095383923027 9    8

> select last(ram),cpu from test where host = 'remote'
>
```

Desired behavior:

```
> select last(),ram,cpu from test where host = 'remote'
name: test
time                ram cpu
----                ---- ---
1492780095383923027      11
```

**Comment by rbetts** [comment]
@jsternberg Can you provide an example that accomplishes with this SELECT .. ORDER BY . LIMIT(1)?

**Comment by jsternberg** [comment]
I think it would be possible to do: `select * from test where host = 'remote' order by time desc limit 1`.

**Comment by timhallinflux** [comment]
@biker27 -- I believe the above example will address your request.  Please review.
