### ISSUE TITLE
Lost of precision when migrating with python API from milliseconds to microseconds and from 2 versions

### ISSUE THREAD

**Issue by dannywillems** [influxdata/influxdb#8313]
### Directions

I migrate an old InfluxDB database using Influx 0.9.5.2 and timestamps are in milliseconds. The new version is 1.2.2 and timestamps are microseconds.
I use the Python API. I select all points from the source and insert it in the destination (no timestamp conversion, I keep the initial string returned by the API).
After that, I want to check the points are in the destination and I have issues with timestamps.

### Bug report

InfluxDB - Source: 0.9.5.1, Destination: 1.2.2
Ubuntu 16.04

Select data from 0.9.5.1, in milliseconds and insert it in a 1.2.2 in microseconds.
Some examples:
```
2016-01-22T04:04:31.493999Z
2016-01-22T04:04:31.494Z

2016-01-22T04:00:38.401999Z (two different insertions)
2016-01-22T04:00:38.402Z

2016-01-22T04:00:38.401999872Z
2016-01-22T04:00:38.402Z

2016-01-22T04:01:43.049999Z
2016-01-22T04:01:43.05Z
```

### Expected outputs

```
2016-01-22T04:04:31.494000Z
2016-01-22T04:04:31.494Z

2016-01-22T04:00:38.402000Z (two different insertions)
2016-01-22T04:00:38.402Z

2016-01-22T04:00:38.4020000Z
2016-01-22T04:00:38.402Z

2016-01-22T04:01:43.050000Z
2016-01-22T04:01:43.05Z
```

**Comment by jsternberg** [comment]
I think this question would be much better on our community website at https://community.influxdata.com. The issue tracker is just for bugs or feature requests.

**Comment by dannywillems** [comment]
But it's a bug... Not a question.

**Comment by jsternberg** [comment]
I'm afraid I don't understand the bug then. Can you give more thorough instructions with the code you're using and the select statements you're using?

**Comment by dannywillems** [comment]
@jsternberg
I've an influx 0.9.5 running on a server with time precision in milliseconds and I want to migrate all data to a new influx 1.2 with time precision in microseconds.

For that, I use influxdb-python. I simply use SELECT to select all points between two dates, and use the write function given by the package.

For 99,9% (it's theoretical, I didn't do statistics) of the points, it's OK. But, for a small subset, instead of writing the timestamp corresponding to `2016-01-22T04:00:38.402Z`, the timestamp, on the new database, is `2016-01-22T04:00:38.401999Z`.

It's really important because we can't write check functions and detect which points are not written if some points are missing. Or, it's more difficult to write one.

**Comment by jsternberg** [comment]
This looks like a potential error with the python library. Can you paste the code you're using?
