### ISSUE TITLE
[HELP] Create admin user with password on container initialization

### ISSUE THREAD

**Issue by bogdanveres** [influxdata/influxdb#8317]
I have the following *.yml file: 

`   
    version: '2'

    services:

    influxdb:
        build: 
            context: Services/Influxdb
            args:
                - INFLUXDB_VERSION=$INFLUXDB_VERSION  
        image: systems/influxdb
        environment:
            INFLUXDB_HOSTNAME: "${INFLUXDB_HOSTNAME}"
            INFLUXDB_USERNAME: "${INFLUXDB_USERNAME}"
            INFLUXDB_PASSWORD: "${INFLUXDB_PASSWORD}"
        ports:
            - 8086:8086
            - 8083:8083
        volumes:
            - jit-data.influxdb:/var/lib/influxdb
        env_file:
            - service-variables.env
        networks:
            - influx
            - default
        logging:
            driver: json-file
            options: 
                max-size: "100m"
                max-file: "3"
        restart: always`

And the docker file:

`

    FROM alpine:3.5

    ARG INFLUXDB_VERSION

    RUN apk add --no-cache --virtual .build-deps wget gnupg tar ca-certificates && \
    update-ca-certificates && \
    gpg --keyserver hkp://ha.pool.sks-keyservers.net \
        --recv-keys 05CE15085FC09D18E99EFB22684A14CF2582E0C5 && \
    wget -q https://dl.influxdata.com/influxdb/releases/influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz.asc && \
    wget -q https://dl.influxdata.com/influxdb/releases/influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz && \
    gpg --batch --verify influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz.asc influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz && \
    mkdir -p /usr/src && \
    tar -C /usr/src -xzf influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz && \
    rm -f /usr/src/influxdb-*/influxdb.conf && \
    chmod +x /usr/src/influxdb-*/* && \
    cp -a /usr/src/influxdb-*/* /usr/bin/ && \
    rm -rf *.tar.gz* /usr/src /root/.gnupg && \
    apk del .build-deps

    RUN apk add --update curl && \
	rm -rf /var/cache/apk/*

    COPY influxdb.conf "/etc/influxdb/influxdb.conf"
    COPY DBUtils.sh "/DBUtils.sh"

    COPY entrypoint.sh /entrypoint.sh
    #ENTRYPOINT ["/entrypoint.sh"]
    CMD ["influxd"]`

In my influxdb.conf file:
`auth-enabled = true`

Is it possible to create the admin user with password on container initialization? The container is successfully created but the user/pass are not. Is there way to create the user with password without restarting the container? 

.env file:

`INFLUXDB_USERNAME=admin`
`INFLUXDB_PASSWORD=blabla`

The tutum image is deprecated. There was an example with a custom shell script but  maybe there is another way to fix this issue.

**Comment by jsternberg** [comment]
Please file this issue in the influxdata/influxdata-docker repository. Thanks.
