### ISSUE TITLE
Unable to access admin page for influxdb 

### ISSUE THREAD

**Issue by anarwal27** [influxdata/influxdb#8318]
I am using macOS Sierra for running docker image of influxdb (downloaded from https://store.docker.com/images/influxdb?tab=description) but I am unable to access admin page from my system. I tried to update config file also, but it did not use the config file I provided. Can someone please help me with the issue?

**Comment by jsternberg** [comment]
I'll update that documentation. The admin interface is disabled by default in 1.2 and will be removed in 1.3 so I should just remove mentions of it from the documentation.

If you're still trying to use it, setting `INFLUXDB_ADMIN_ENABLED=true` should work.
