### ISSUE TITLE
influxdb logs to /var/log/messages by default

### ISSUE THREAD

**Issue by randomeleven** [influxdata/influxdb#8319]
I am running (Influxdb 1.1.0), (Telegraf 1.1.0) and Grafana 3.0 (soon will run kapacitor) on a RHEL 7.0 server , and I ran into a 100% disk utilization issue because of the file **/var/log/messages** .

Seems like telegraf , influxdb and grafana are all logging their events to this file, resulting in a large file size quickly.

How do I direct the logs somewhere else ?
And what is the difference between info logged in **/var/log/messages** and **/var/log/influxdb/{{ .product }}** ?

The file contains event logs by influxdb, telegraf and grafana, like when a batch of points has been been written by telegraf, a point is arriving to influxdb via http or typical grafana query activity. I'll give an example:

```
Apr 20 10:03:32 my-server-host-name influxd: [query] 2017/04/20 10:03:32 SELECT mean(value) FROM db.rp.measure WHERE time > now() - 1h GROUP BY time(30s)
Apr 20 10:03:32 my-server-host-name influxd: [query] 2017/04/20 10:03:32 SELECT mean(value2) FROM db.rp.measure WHERE time > now() - 1h GROUP BY time(30s)
Apr 20 10:03:32 my-server-host-name influxd: [httpd] ::1 - influx_user [20/Apr/2017:10:03:32 +0400] "GET /query?db=db&epoch=ms&q=SELECT+mean....etc
Apr 20 10:03:32 my-server-host-name influxd: [httpd] ::1 - influx_user [20/Apr/2017:10:03:32 +0400] "GET /query?db=db&epoch=ms&q=SELECT+mean%......etc
Apr 20 10:03:37 my-server-host-name influxd: [httpd] X.X.X.X - influx_user2 [20/Apr/2017:10:03:37 +0400] "POST /write?db=db&p=%5BREDACTED%5D&precision=ms&rp=rp&u=influx_user2 HTTP/1.1" 204 0 "-" "python-requests/2.11.0" 1864a5ab-258f-11e7-8309-000000000000 18886
Apr 20 10:03:41 my-server-host-name telegraf: 2017/04/20 10:03:41 I! Output [influxdb] buffer fullness: 30 / 10000 metrics. Total gathered metrics: 35263075. Total dropped metrics: 0.
Apr 20 10:03:41 my-server-host-name telegraf: 2017/04/20 10:03:41 I! Output [influxdb] wrote batch of 30 metrics in 223.127Âµs
Apr 20 10:04:06 my-server-host-name influxd: [httpd] X.X.X.X - influx_user2 [20/Apr/2017:10:04:06 +0400] "POST /write?db=db&p=%5BREDACTED%5D&precision=ms&rp=rp&u=influx_user2 HTTP/1.1" 204 0 "-" "python-requests/2.4.3 CPython/2.7.9 Linux/3.16.0-4-amd64" 29b25ca8-258f-11e7-83fc-000000000000 8499
Apr 20 10:04:06 my-server-host-name influxd: [httpd] X.X.X.X - influx_user2 [20/Apr/2017:10:04:06 +0400] "POST /write?db=db&p=%5BREDACTED%5D&precision=ms&rp=rp&u=influx_user2 HTTP/1.1" 204 0 "-" "python-requests/2.4.3 CPython/2.7.9 Linux/3.16.0-4-amd64" 29b33168-258f-11e7-83fd-000000000000 10269
......
......
more of the same

```

What's alarming is that the file is growing in size by about 0.5GB / 24 hours.

I am thinking about purging these logs after having directed them away from **/var/log/messages**

**Comment by pkittenis** [comment]
This is an issue with the system, not influx. This behaviour is *not* seen in RHEL6 or Ubuntu 12 and 14 distributions and I would wager this applies to all non-systemd distributions as well.

**Comment by jmvbxx** [comment]
@pkittenis That may be the case. However, for better or for worse, more and more systems are moving to systemd and logs not being properly directed by default is something though I believe should be addressed.

**Comment by chekolyn** [comment]
There is something we can do at the rsylog level (Also using RHEL 7.0)

We can create a simple rule in **/etc/rsyslog.d/influxdb.conf** to change the destination log:

```
### InfluxDB Rules ###
if $programname == 'influxd' then {
   action(type="omfile" file="/var/log/influxdb/influxd.log")
}
```

@pkittenis Perhaps these simple rules can be added to the packages (like we do for logrotate confs).

**Comment by pkittenis** [comment]
I am not part of the project, cannot help you there. I pointed out the issue does not occur on RHEL6 or other non-systemd based systems, which points to an issue with systemd rather than influx.

**Comment by abusayeedn** [comment]
I install grafana and influxdb latest version in same pc.
I have to monitoring another ubuntu syslog via Grafana. 
And I also same monitoring mikrotik syslog too. 
How can I insert remote syslog into influxdb database?

need anybody help.
Thanks

**Comment by HaoChou** [comment]
I have a same problem that influxdb logs to /var/log/messages by default .and I try some configs and failed~

**Comment by acidnag** [comment]
Same behaviour observed in influxdb:1.7.6
Putting an override in /etc/default/influxdb didn't work as per the [documentation](https://docs.influxdata.com/influxdb/v1.7/administration/logs/)
System Info: Centos7.5.1804
Installation Info: Launched as a service

**Comment by RadekHavelka** [comment]
same problem here. Added the /etc/rsyslog.d/influxdb.conf as mentioned above solved it for me for now

**Comment by vladak** [comment]
> Same behaviour observed in influxdb:1.7.6
> Putting an override in /etc/default/influxdb didn't work as per the [documentation](https://docs.influxdata.com/influxdb/v1.7/administration/logs/)
> System Info: Centos7.5.1804
> Installation Info: Launched as a service

Thanks for the link to the documentation. I was too hit by this problem on my Raspberry Pi running Raspbian (where this is especially painful due to the SD card wearing off) with default syslog configuration. In my case `/var/log/daemon.log` was being blasted with entries such as:
```
Aug  7 21:30:48 teplota influxd[608]: ts=2019-08-07T19:30:48.898237Z lvl=info msg="Executing query" log_id=0H5zn~Kl000 service=query query="SELECT mean(cpu) FROM systemp.autogen.systemp WHERE url = 'http://localhost:5000/' AND time > now() - 5m GROUP BY time(200ms)"
Aug  7 21:31:01 teplota influxd[608]: ts=2019-08-07T19:31:01.541080Z lvl=info msg="Executing query" log_id=0H5zn~Kl000 service=query query="SELECT mean(usage_idle) FROM telegraf.autogen.cpu WHERE time >= now() - 6h GROUP BY time(20s)"
Aug  7 21:31:01 teplota influxd[608]: ts=2019-08-07T19:31:01.559447Z lvl=info msg="Executing query" log_id=0H5zn~Kl000 service=query query="SELECT mean(free) FROM telegraf.autogen.mem WHERE time >= now() - 6h GROUP BY time(20s)"
Aug  7 21:31:01 teplota influxd[608]: ts=2019-08-07T19:31:01.571080Z lvl=info msg="Executing query" log_id=0H5zn~Kl000 service=query query="SELECT mean(used_percent) FROM telegraf.autogen.disk WHERE time >= now() - 6h GROUP BY time(20s)"
```
I solved that by setting log level to `error` in `/etc/influxdb/influxdb.conf` and restarting the service.

**Comment by memetb** [comment]
I don't know how this issue is close to 3 years old and marked as "won't fix", when the solution is basic systems administration and should come out of the box.

In the `/etc/systemd/system/influxdb.service`, set the following parameters:

     StandardOutput=null
     StandardError=null

The above will simply zap the log output. But if this is not desired, one can also set these values to say `append:/var/log/influxdb/influxd`, which can be combined by setting /var/log/influxdb to be a sym link to some other storage medium.

 As an aside, it's quite obviously poor form to dump http logs into syslog.

Systemd logging configuration [reference](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#id-1.17).

**Comment by snenkov** [comment]
I am running influxDB version: 1.7.8 on Ubuntu machine (18.04.3 LTS).
Currently my syslog file keep increasing by 5 GB per day.
I consider this an issue with InfluxDB.
I don't understand why the DB need to log such info by default.

**Comment by jessie00** [comment]
> There is something we can do at the rsylog level (Also using RHEL 7.0)
> 
> We can create a simple rule in **/etc/rsyslog.d/influxdb.conf** to change the destination log:
> 
> ```
> ### InfluxDB Rules ###
> if $programname == 'influxd' then {
>    action(type="omfile" file="/var/log/influxdb/influxd.log")
>    stop
> }
> ```
> 
> @pkittenis Perhaps these simple rules can be added to the packages (like we do for logrotate confs).

Thanks a lot.

**Comment by est** [comment]
leaving everything to rsyslog is wrong.

**Comment by nemesisdesign** [comment]
I have noticed that when HTTP query logging is enabled, it doesn't just log to syslog but also /var/log/messages and /var/log/user.log: https://github.com/influxdata/influxdb/issues/21726.

**Comment by DesireWithin** [comment]
Is it really solved?
I have a pure Centos 7.6, 
I tried [this](https://github.com/influxdata/influxdb/issues/8319#issuecomment-324754459) and [this](https://github.com/influxdata/influxdb/issues/8319#issuecomment-541410711) comment above,
They both don't work for me.

**Comment by snow8261** [comment]
> Is it really solved? I have a pure Centos 7.6, I tried [this](https://github.com/influxdata/influxdb/issues/8319#issuecomment-324754459) and [this](https://github.com/influxdata/influxdb/issues/8319#issuecomment-541410711) comment above, They both don't work for me.

same with me

**Comment by TheFlipside** [comment]
as of today with version 1.8.10 of influxdb on a rocky linux 8.7 system i was able to workaround the issue the following way:

edit the configuration in /etc/influxdb/influxdb.conf

in the [http] section set
**access-log-path = "/var/log/influxdb/access.log"**

and in the [logging] section set
**level = "error"**

create a new configuration at /etc/logrotate.d/influxdb_http with

**/var/log/influxdb/access.log {
    daily
    rotate 7
    missingok
    dateext
    copytruncate
    compress
}**

restart the service to apply the configuration

**sudo systemctl restart influxd**

**Comment by Sysselix** [comment]
Thanks to [TheFlipside](https://github.com/TheFlipside) !
That worked for me.
I moved all .logs from the internal microSD (RasPi) to an secure disk (ext. USB SSD)

**Comment by lcgogo** [comment]
> as of today with version 1.8.10 of influxdb on a rocky linux 8.7 system i was able to workaround the issue the following way:
> 
> edit the configuration in /etc/influxdb/influxdb.conf
> 
> in the [http] section set **access-log-path = "/var/log/influxdb/access.log"**
> 
> and in the [logging] section set **level = "error"**
> 
> create a new configuration at /etc/logrotate.d/influxdb_http with
> 
> **/var/log/influxdb/access.log { daily rotate 7 missingok dateext copytruncate compress }**
> 
> restart the service to apply the configuration
> 
> **sudo systemctl restart influxd**

Thanks, I use followed os/influxdb version is useful to configure, the other comments are useless now.

ubuntu 20.04 and apt install influxd 
influxd version
InfluxDB v1.6.4 (git: unknown unknown)
