### ISSUE TITLE
help ( Extract data from Influxdb and send it to OpenTsdb )

### ISSUE THREAD

**Issue by yani01** [influxdata/influxdb#8321]
Hello

I'm looking for an idea to extract data from Influxdb and send them in OpenTsdb ?????

I also saw that Infliuxdb Uses the OpenTsdb entries of the coque esque OpenTsdb can replace Influxdb ????

Thank you for your help

**Comment by jsternberg** [comment]
The issue tracker is only for bugs or feature requests. Please try out our new community website and ask your question there where it is more likely to get a response: https://community.influxdata.com
