### ISSUE TITLE
Merge duplicate points

### ISSUE THREAD

**Issue by williame** [influxdata/influxdb#8325]
### Feature Request

__Proposal:__ Enable merging of duplicate points

__Current behavior:__ If a point is submitted with an identical measurement, tag set, and timestamp it will silently overwrite the previous point. 

https://docs.influxdata.com/influxdb/v0.9/troubleshooting/frequently_encountered_issues/#writing-duplicate-points

__Desired behavior:__ A new endpoint, e.g. `/upsert`, works exactly as `/write` in all respects except behaviour with duplicate points.  This new endpoint sums the numeric measurements when the tag set and timestamp are identical to an existing measurement.

__Use case:__ The current behaviour, while intentional, is such a bugbear that there's even a section in the FAQ for it!  When the measurements being inserted into influx are already aggregations from another system its very common for points to collide, and people following the advice in the FAQ are busy filling up their database with distinct events (adding random nanoseconds or tags and hoping those random numbers don't collide) because they aren't able to update-in-place.

**Comment by jwilder** [comment]
The behavior of newer values overwriting older ones within a series is deeply ingrained into the storage engine.  An `/upsert` API would probably require querying every series being written for identical series which would be very expensive.  This is very unlikely to be implemented in the database itself.

If you have a window of time where duplicate data could arrive, you may be able to use [telegraf aggregators](https://docs.influxdata.com/telegraf/v1.2/concepts/aggregator_processor_plugins/) to receive the writes, aggregate them and then send to influxdb.

**Comment by williame** [comment]
I don't know Go and I don't know the Influx code-base, being just a user, but my guess is that its a ordered map where the key is the tag set and the value is a hash map of field name values.  When you receive the new measurements you have to get the tag set to find the map of fields.  When you have found the place to insert the new value, you can easily check if the value is already there.  In Java, for example, Map.put returns the previous value.

**Comment by josephxsxn** [comment]
Second this, we have the same problem of trying to add random nano-seconds and hoping it doesn't collide. Saddly we have been finding it still collides frequently leaving the only solution to have a UUID-4 tag to ensure insert uniqueness at a given timestamp.
