### ISSUE TITLE
Request: Test schemas with very large field cardinalities

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#8328]
### Test Request

During a schema consult, I was asked what the performance implications of having very high field cardinality are. Doing preliminary testing using ~20k series with ~100 measurements each with 4000 fields. For the most part during the test, the schema seemed to perform without issue. It would be interesting to get a bit more information around how this type of schema impacts the performance of InfluxDB.

__Use case:__
Schema Consultations.

**Comment by bpcrao** [comment]
can any one tell if this schema is good

I have 3000 Sensors 1500 of temperature 1000 of humidity and 500 of pressure
Each of these sensors are mapped to a location , i.e I have 3000 locations
Location can be like Building/Block/Floor/Room/LocA and Building/Block/Floor/Room/LocB (this being the parent Building/Block/Floor/Room )
data is read from the sensors every 15 seconds
What should be my schema for InfluxDB ?

Here are my thoughts

I thought I will have these as measurements

temperature
pressure
humidity
And the Tags as Location | sensorID (3000 tags for all the sensors which makes my cardinality 3000 )

Location | sensorID 
---------|---------
location A| sensor1
location B| sensor2
so I will have 3000 series, data stored every 15 seconds Is this scalable? Do you see any issues with this schema design
