### ISSUE TITLE
[BUG] Non descriptive field type error

### ISSUE THREAD

**Issue by zezuladp** [influxdata/influxdb#8332]
InfluxDB version 1.2.2
OS Ubuntu 14.04

I am using fluentd influx plugin to import many large JSON objects into InfluxDB. I can't provide the exact data to reproduce. But I am consistently getting this error on my data set. I even wipe the measurement every time before import.

Here is the exact error I see `{"error":"[shard 206] field type conflict"}` (shard number changes)

I have run multiple validators on my dataset to confirm there actually isn't any conflicts.
I also have gotten field type conflicts before that say exactly what field and what type so they've been easy to fix. This issue seems much deeper than that.

I will attempt to pinpoint the exact data/point where it does this. But I think this is worthy of at least a look at this point.

**Comment by corentingi** [comment]
Could it be because of the FluentD plugin sending sometime **Integer** and sometimes **Float** for the same field ?
https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_reference/#data-types
Integer are sent in the form `154i`

**Comment by zezuladp** [comment]
I've run into that before and the Influx error will tell me that specifically. Something like "The field already exists as float" as opposed to some non-descriptive shard error. 

I also convert all ints to floats as a result of getting said error.

**Comment by danielnelson** [comment]
I think it would be useful to change the error message to contain the full series key for the offending field, something like:
```
{
    "error": "partial write: field type conflict: input field \"value\" on series \"stuff,host=foo\" is type float, already exists as type integer dropped=1"
}
```

Often the source of the point is encoded in the tagset like `fluentd,host=example.org`.  If we printed the series key you could determine the source of the type conflict and fix it more easily.
