### ISSUE TITLE
InfluxDB running out of memory

### ISSUE THREAD

**Issue by m4ce** [influxdata/influxdb#8334]
Environment:

* 8 x CPU cores
* 16GB of memory
* InfluxDB database size: 10G
* Version: 1.2.2
* OS: CentOS 7.2 x86_64
* Docker: 1.12.1

When starting up Influx, the process memory consumption rapidly increases to almost 70% of the total memory. 

```
15042 root      20   0 17.860g 0.010t 3.289g S   0.0 68.0   5:11.48 influxd
```

I've also attached the log file which shows the the initial start up.

Could anyone shed some light into why this might be happening?
[block.txt](https://github.com/influxdata/influxdb/files/962893/block.txt)
[diagnostics.txt](https://github.com/influxdata/influxdb/files/962891/diagnostics.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/962895/goroutine.txt)
[heap.txt](https://github.com/influxdata/influxdb/files/962892/heap.txt)
[influxdb_conf.txt](https://github.com/influxdata/influxdb/files/962896/influxdb_conf.txt)
[influxdb_log.txt](https://github.com/influxdata/influxdb/files/962894/influxdb_log.txt)
[iostat.txt](https://github.com/influxdata/influxdb/files/962898/iostat.txt)
[shards.txt](https://github.com/influxdata/influxdb/files/962900/shards.txt)
[stats.txt](https://github.com/influxdata/influxdb/files/962897/stats.txt)
[vars.txt](https://github.com/influxdata/influxdb/files/962899/vars.txt)

**Comment by jwilder** [comment]
We need more information in order to diagnose what is going on.  Can you update the issue description with the instructions listed in our [issue template](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md)?

**Comment by m4ce** [comment]
Hi @jwilder,

sorry, my bad, should've seen that earlier. I've attached all the necessary log files and updated the system information.

**Comment by jwilder** [comment]
@m4ce Your `systems` DB has around 3.2M series and heap is about 7.5GB in those profiles.  A lot of the heap in use is for the in-memory index related to the number of series you have.  I'm not sure what stat you are looking at for "process memory", but the DB uses memory mapped files which can show as a lot of virtual memory in use.

The docs have some [hardware sizing guidelines](https://docs.influxdata.com/influxdb/v1.2/guides/hardware_sizing/#general-hardware-guidelines-for-clusters) which gives some general recommendations bases on series cardinality.

**Comment by m4ce** [comment]
@jwilder, thanks for the feedback. I will look into more then.

**Comment by m4ce** [comment]
@jwilder - I actually found out what's going on. We are running telegraf in our cluster to collect system metrics. However, the docker input plugin is enabled. As we happen to spawn thousand of jobs on our grid, all the metrics for these containers get sent to Influx. The bad news is that Telegraf keeps sending metrics for containers that are in a exit state too :/ I will have to temporarily disable the plugin as Telegraf doesn't seem to support any option to disable monitoring non-running containers.

**Comment by jwilder** [comment]
@m4ce Ah.  That would definitely contribute to higher cardinality.  Looks like you logged an issue in telegraf repo: https://github.com/influxdata/telegraf/issues/2737 so I'm going to close this.
