### ISSUE TITLE
confused about influx backup mechanism with "-since" option! bug or not?

### ISSUE THREAD

**Issue by wangchunpeng** [influxdata/influxdb#8335]
### Bug report
influx db version: 1.2.2
os : x86_64 GNU/Linux

__Steps to reproduce:__
1. Create a "test_backup" database, and then insert some points into "cup" measurement.
2. the points' time varied from 2017-4-28 06:42:00 UTC to 2017-4-28 06:50:00 UTC
3. I did a backup operation of metadata, followed by which I began to backup metric data.
using the clause below:
"_influxd backup -database test_backup -since 2017-04-28T06:49:00Z  /tmp/backup/influxdb "_

4. when I restored the data,  all the points are in the new db. not only the points since 06:49:00.

![image](https://cloud.githubusercontent.com/assets/13312951/25521631/f7cb0306-2c32-11e7-8206-d126120a6fce.png)

__Expected behavior:
The expected result should be like the pic shown below, only the followling points should be backup and restore:

![image](https://cloud.githubusercontent.com/assets/13312951/25521640/0497788a-2c33-11e7-8b66-b794d4588038.png)

**Comment by jwilder** [comment]
`-since` currently uses the modified time of shard TSM files.  It is not a time cutoff for data within a shard. 

Unfortunately, since TSM files get compacted as new data arrives, the time gets updated frequently which causes a lot of the shard to be backed up each time.

**Comment by aanthony1243** [comment]
In the upcoming 1.5 release, users will be able to provide   -start and -end arguments which filter backup data to include only points with timestamps between start and end, respectively.  To achieve the result above: 

`influxd backup -database test_backup -start 2017-04-28T06:49:00Z -end 2017-04-28T06:50:00Z /tmp/backup/influxdb`
