### ISSUE TITLE
Enhancement request: Allow nested select functions, ex: select sum(derivate(value))...;

### ISSUE THREAD

**Issue by cboggs** [influxdata/influxdb#834]
We store our data in InfluxDB such that each individual metric is its own series, and we insert a hostname value into each update so that we can build out dashboards for clustered services without falling back to regex'd series names, and we keep our series count down.

Some of our metrics are counters that we take a derivative of at search time. When viewing each host individually this works fine, but if I want to roll up those values easily across a set of hostnames that exist in the series, I can't do much other than:
`select derivative(value) from seriesName group by time(30s), hostname;`
and then see independent lines graphed for each hostname in tools like Grafana.

If I could instead query it as follows, aggregate graphs would be much easier and more universally applicable:
`select sum(derivative(value)) from seriesName group by time(30s);`

**Comment by reardencode** [comment]
:+1: sum(derivative(value)) would also be very useful for me.

**Comment by srikara** [comment]
+1

**Comment by h-svab** [comment]
mean(derivative(value)) would be very welcome

**Comment by grypyrg** [comment]
+1

**Comment by daniel-nichter** [comment]
+1

**Comment by nethalo** [comment]
+1

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by fillest** [comment]
I'm getting `error parsing query: expected field argument in sum()` for `SELECT sum(non_negative_derivative("requests_started", 1s)) FROM "nginx.status" WHERE "host" =~ /censored-.*/ AND $timeFilter GROUP BY "host"` - is it the same issue, should I reopen it?

**Comment by fillest** [comment]
Forgot to mention the version: 1.0.2-1

**Comment by fillest** [comment]
Aaah sorry, I didn't read previous comment about the aggregated issue.

**Comment by erowan** [comment]
+1

**Comment by dddda212** [comment]
+1

**Comment by leftwukaixing** [comment]
+1

**Comment by henriklb** [comment]
+1
