### ISSUE TITLE
influxdb cost too much memory every 24hours

### ISSUE THREAD

**Issue by smartczy** [influxdata/influxdb#8340]
### Bug report

__System info:__ [InfluxDB version: 0.13, operating system name: CentOS 6.7]

__Actual behavior:__ 
     Our influxdb is running stablely for nearly one year. But in this week, one influxdb relay(include two influxdb) throws error log like : 
```
Problem posting to relay "group2" backend "local1": Post http://1.1.1.1:8086/write?consistency=&db=database&precision=s&rp=default: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
so our data can not write into influxdb. And meanwhile in this machine the influxd cost almost 56G memory( 62G total), but the other machines only cost 30G memory and are running normally . One or two hour before errors occured  this meachine also cost 30G memory. Is it a memory leak problem? 
Another strange phenomenon is that this happend every 24 hours in this week. I have to restart influxdb evey 24 hours  and the problom is solved temporarily. 

My problem is a little like this :[#6747]

**Comment by eighteen14k** [comment]
I had this problem (influxdb growing huge) ... upgrading to 1.2.2 fixed it.

**Comment by smartczy** [comment]
@eighteen14k 
Is it(version 1.2.2) running stablely?

**Comment by jwilder** [comment]
Closing this since this is reported for 0.13 which is very old.  Please upgrade to the 1.2 release line and open a new issue if this is still occurring.
