### ISSUE TITLE
CQ Controls -- Stop/Start

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/influxdb#8345]
### Feature Request

__Proposal: Once Continuous Queries (CQs) are created there is no way to halt them...other than via the DROP command. This then requires a "re-creation" of the Continuous Query -- to get going again.  Ideally, CQs would allow for some finer-grained controls -- such as stop/start to allow the administrator with flexibility in terms of halting their execution.

__Current behavior: CREATE CONTINUOUS QUERY....  creates the CQ and starts it.  DROP CONTINUOUS QUERY is the only way to halt its execution.

__Desired behavior: CREATE CONTINUOUS QUERY would create and activate the query, as it does today.  But, new commands would be introduced to allow for the query to be halted...and re-started.  STOP CONTINUOUS QUERY <NAME>
START CONTINUOUS QUERY <NAME>
This would prevent the user from having to DROP and then re-load the entire query.

__Use case: There are situations where the CQ should be halted temporarily and then re-started.

**Comment by rbetts** [comment]
This proposal creates two new top level InfluxQL statements: STOP and START that apply only to CQs. We could, as an alternative that doesn't introduce new statement keywords, add an optional "ENABLE" clause to the CREATE CQ statement then support `ALTER CONTINUOUS QUERY <cq_name> ENABLE no`.  This would mirror the existing `ATLER RETENTION POLICY` command. It would also mean `SHOW` of the CQ declaration would show the active state without needing to modify the schema of `SHOW CONTINUOUS QUERIES`.  It also allows a CQ to be defined un-enabled atomically as a single statement.

The new CQ syntax would be:

```
create_continuous_query_stmt = "CREATE CONTINUOUS_QUERY" query_name_on_clause
    [ "RESAMPLE" resample_opts ]
    [ "ENABLE" enable_opts]
    "BEGIN" select_stmt "END" .
...
enable_opts = (yes | no)
```

Some other details:

 -  SHOW command to display the "STOP / START" status (or automatically pick up `enable_opts`)
 - If we add a separate state, START / STOP status needs to be written to RAFT and persist across a cluster restart.
 - Need to update the InfluxQL documentation with whichever new syntax is chosen.
 - If we use START/STOP, we will need to map those new statements to the /query endpoint POST handler. Documentation needs to be updated for this change as well.

**Comment by timhallinflux** [comment]
@rkuchan -- can we ask for you to review/comment on the use of YES | NO as activation parameters...vs. say TRUE | FALSE  (or other) to maintain consistency with the rest of the query language?

**Comment by rkuchan** [comment]
@timhallinflux, I don't think there's any comparable language in InfluxQL. There's one somewhat related command ([`KILL QUERY`](https://docs.influxdata.com/influxdb/v1.2/troubleshooting/query_management/#stop-currently-running-queries-with-kill-query)) but there's no way to un-kill a query so I don't think that's useful here. Also `living` | `killed` seems extreme for CQs 😊

Kapacitor, on the other hand, does have a [`status` property](https://docs.influxdata.com/kapacitor/v1.2//api/api/#tasks) with possible values of `enabled` or `disabled`. I like the clause `STATUS enabled | disabled` but it is wordier.

**Comment by jwilder** [comment]
I'd suggest `enabled true|false`.  `enabled` is also terminology we use in the config for config settings. 
e.g. 
```
  logging-enabled = true
  query-log-enabled = true
  trace-logging-enabled = false
  enabled = true
  store-enabled = true
  auth-enabled = false
```
