### ISSUE TITLE
High usage of ram influxdb process killed by OS

### ISSUE THREAD

**Issue by pravensoni** [influxdata/influxdb#8346]
### Bug report

System info: 
influxdb version 1.2,
O/S – centos 6.5
CPU – 8 core
RAM – 10 gb

Steps to reproduce:

1. Started writing data to influxdb with 10 million records with size of 1 GB but in a batch of 10k records.
     This is a  Java program which writes to influxdb. The RAM usage by influxdb went high (around 80%). 
     The whole 1GB of data was written.  
3. Again started writing data to influxdb in batch of 10k records but in a different database. 
    After inserting 3 million records the whole ram was used up and the process was killed by OS.  
    The total memory consumed was more than 9 GB RAM.  

Actual behavior: 
1. It used all of the RAM and got killed by the OS. 
2. The space taken by influxdb was high for storing 1GB of data (around 2.8 G in var/lib/influxdb/data/) 

Expected behavior: 
1. The process influxdb must not have utilised such high RAM and be eventually killed by the OS.
2. The space taken by influxdb  for storing 1GB of data must be less. 

messages log attached.

Additional info:
schema : 
Tag: scId
Field: exchangeId
Field: tradedVolume
Field: tradedValue
Field: avgPrice
Field: open
Field: high
Field: low
Field: close
Field: prevClose
[messageslog.txt](https://github.com/influxdata/influxdb/files/969536/messageslog.txt)

**Comment by dstarmanhr** [comment]
we are experiencing similar issue, we have several instances of influx running. 

older nightly build from jan - 700GB dataset - working ok using 60GB of RAM

1.2.4 stable and 1.2.4 latest nightly, 423G dataset - using 140GB of RAM in peaks

**Comment by rbetts** [comment]
@dstarmanhr Can you attach a script or some steps to reproduce this observation?

**Comment by dstarmanhr** [comment]
Not really, we have thousands of telegraf clients writing to all three nodes. But memory usage is still growing on the two nodes.

**Comment by dstarmanhr** [comment]
@rbetts some info about the hardware, let me know what additional info I can provide.

__System info:__ 

influx instance 1 - influx 1.2.2-1, debian jessie, Dual Hexa-core Xeon E5-2630 v2 2.6 GHz 256.00GB RAM, 4x1TB SSDs in RAID10 configuration
influx instance 2 - influx 1.3.0~n201705250800-0, debian jessie, Dual Hexa-core Xeon E5-2630 v2 2.6 GHz 256.00GB RAM, 4x1TB SSDs in RAID10 configuration
influx instance 3 - influx nightly from Jan 14, debian wheezy, Dual Hexa-core Xeon E5-2630 v2 2.6 GHz 128.00GB RAM, 4x1TB SSDs in RAID10 configuration

instances 1 and 2 were upgraded in RAM last week due to the fact they started OOM-ing, until that, they were indentical in hardware.

instance 3 is currently our "stable" instance, there are currently no issues with it, memory usage is stable and it has 4 months of data.

instance 1 was cleanly installed around april 1st, getting data from then, memory usage was stable until around may 1st, where it started to consume more memory.
around may 1st, instance 2 was setup in the following way: instance 1 was stopped, data copied to instance 2 and then started. 

We are writing around 5k wps with spikes of up to 15k wps.

__Steps to reproduce:__

1. Send data to influx via telegraf client

__Expected behavior:__ 
Memory usage to remain stable

__Actual behavior:__ 
Memory usage on instances 1 and 2 is growing.

**Comment by dstarmanhr** [comment]
also, it looks like instance 1 occasionally starts to to return 500, instance 2 doesn't seem to have these issues.

tail -1000000 influxdb.log | grep 'HTTP/1.1" 500'  | wc -l
30943

tail -1000000 influxdb.log | grep 'HTTP/1.1" 500'  | wc -l
0

**Comment by dstarmanhr** [comment]
much more futex errors on instance that is not working ok:

instance 1: 
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 63.62   35.462154         290    122090     18671 futex
 23.62   13.167382       24072       547           fsync
  6.13    3.415251         332     10294           epoll_wait
  5.93    3.302832         101     32628           select
  0.41    0.226533          21     10923         6 write
  0.25    0.138402          54      2552           sched_yield
  0.02    0.010490           1      7077      2891 read
  0.01    0.006402         915         7           unlinkat
  0.01    0.005899           4      1507           close
  0.01    0.004057           2      2166           epoll_ctl
  0.00    0.000301           0      1051           setsockopt
  0.00    0.000204           0      2059      1008 accept4
  0.00    0.000162           0      1051           getsockname
  0.00    0.000160           0       912           lstat
  0.00    0.000069           0       395         2 openat
  0.00    0.000015           0       774           getdents64
  0.00    0.000000           0         7         2 stat
  0.00    0.000000           0         7           fstat
  0.00    0.000000           0         4           lseek
  0.00    0.000000           0         2           mmap
  0.00    0.000000           0         6         6 rt_sigreturn
  0.00    0.000000           0        61        60 madvise
  0.00    0.000000           0         1         1 restart_syscall
  0.00    0.000000           0         2           renameat
------ ----------- ----------- --------- --------- ----------------
100.00   55.740313                196123     22647 total

instance 3:

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 75.17   32.705686         748     43752      4877 futex
 17.40    7.571877       12899       587           fsync
  2.89    1.257138         119     10599           epoll_wait
  2.46    1.071720          46     23051           select
  0.84    0.363444          29     12371         7 write
  0.44    0.191002          29      6669      2480 read
  0.18    0.079405          35      2286           sched_yield
  0.15    0.067259          17      3974           lstat
  0.12    0.052356          16      3182           epoll_ctl
  0.11    0.047661          14      3510           close
  0.08    0.036323          13      2886      1301 accept4
  0.08    0.034256           9      3820           getdents64
  0.04    0.016507           9      1915         1 openat
  0.01    0.005327           3      1585           setsockopt
  0.01    0.005289           3      1585           getsockname
  0.01    0.002284         761         3           unlinkat
  0.00    0.000000           0         4         1 stat
  0.00    0.000000           0         4           fstat
  0.00    0.000000           0         2           lseek
  0.00    0.000000           0         1           mmap
  0.00    0.000000           0         7         7 rt_sigreturn
  0.00    0.000000           0         1         1 restart_syscall
  0.00    0.000000           0         1           renameat
------ ----------- ----------- --------- --------- ----------------
100.00   43.507534                121795      8675 total

**Comment by dstarmanhr** [comment]
ok, our issues were caused by the large number of not needed series that were being written, after clearing them, now it works fine.
