### ISSUE TITLE
Backup doesn't work

### ISSUE THREAD

**Issue by shotor** [influxdata/influxdb#8347]
### Bug report

InfluxDB 1.2.3 running on Docker Hyper-V
OS: Windows 10 Enterprise Preview 16179

__Steps to reproduce:__

1. Run Influx 1.2.3 with Docker using Hyper-V
1. Create some database
2. Add some data
3. Run backup command: `influxd backup -database test ~/docker/foo`

__Expected behavior:__
Backup to be made and files to be downloaded to `~/docker/foo`

__Actual behavior:__
Only the metastore was backed up, the process then fails and exits:

```
$ influxd backup -database test ~/docker/foo
2017/05/02 14:03:28 backing up db=test since 0001-01-01 00:00:00 +0000 UTC
2017/05/02 14:03:28 backing up metastore to C:\Users\U\docker\foo\meta.01
2017/05/02 14:03:28 backup failed: expected database, retention policy, and shard id in path: test/autogen/2
backup: expected database, retention policy, and shard id in path: test/autogen/2
```

I don't know much about the `influxd` tool and how it's setup. But looking at that path: `test/autogen/2`. It contains 3 values, the first of which is my database name. The second looks like it could be a retention policy and the third also looks an id. 

Edit:

My best guess is that `filepath.Seperator` is either returning `/` while `\` is expected, or the other way around.

Looking at the code: https://github.com/influxdata/influxdb/blob/master/cmd/influxd/backup/backup.go#L380

And the logged messages:

```
# I enter / as separator
$ influxd backup -database test ~/docker/foo
# but it logs the windows \ seperator
2017/05/02 14:03:28 backing up metastore to C:\Users\U\docker\foo\meta.01
```

Edit 2:

Specify shard and retention policy in command:

```
$ influxd backup -database test -retention autogen -shard 2 "c:\temp\influx"
2017/05/02 15:30:43 backing up metastore to c:\temp\influx\meta.09
2017/05/02 15:30:43 backing up db=test rp=autogen shard=2 to c:\temp\influx\test.autogen.00002.00 since 0001-01-01 00:00:00 +0000 UTC
2017/05/02 15:30:43 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (0)...
2017/05/02 15:30:44 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (1)...
2017/05/02 15:30:45 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (2)...
```

Checking the shards, the parameters seem to be correct

```
name: test
id database retention_policy shard_group start_time           end_time             expiry_time          owners
-- -------- ---------------- ----------- ----------           --------             -----------          ------
2  test     autogen          2           2017-05-01T00:00:00Z 2017-05-08T00:00:00Z 2017-05-08T00:00:00Z
```

Problem now looks a lot like an issue that was reported yesterday: https://github.com/influxdata/influxdb/issues/8342

Edit 3:

Seems this issue was reported 27 days ago as well: https://github.com/influxdata/influxdb/issues/8256

**Comment by starrett67** [comment]
> My best guess is that filepath.Seperator is either returning / while \ is expected, or the other way around.

This has to be it. Must be a windows thing.

**Comment by gpomykala** [comment]
Is anybody looking into this issue? Currently there is no way to initiate a remote backup of unix host from windows pc - it works from unix to unix though on same db version (1.6)
