### ISSUE TITLE
[feature request] RENAME RETENTION POLICY

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#8351]
proposed syntax: `ALTER RETENTION POLICY name RENAME TO new_name`

Would also need to update all relevant CQs.

Related to: https://github.com/influxdata/influxdb/issues/4154

**Comment by Alestrix** [comment]
Please reopen. Changing the definition of a retention policy after some time of collecting data is probably a very common thing to happen.

**Comment by bapBardas** [comment]
Please, consider this feature which would definitely avoid all the burden required to replicate a given RP into a new one simply for changing the name.
Thanks !
