### ISSUE TITLE
[feature request] influx -import options to specify destination db/rp

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#8352]
Add destination database and retention policy arguments to `influx -import` to override the DML options.

**Use case:** A large database is exported from TSM storage in compressed format. The resulting compressed file includes DDL and DML statements to create and set the target database and retention policy for imported points.

```
influx_inspect export -database=mydb -datadir=/var/lib/influxdb/data -waldir=/var/lib/influxdb/wal -compress -out=here.gz
```

```
# DML
# CONTEXT-DATABASE:mydb
# CONTEXT-RETENTION-POLICY:myrp
```

If users wants to import the data in a different database or retention policy, they need to unzip and modify the file - which can be infeasible due to the size of the resulting uncompressed file (e.g. 100GB can result in more than 1TB uncompressed).

**Proposed feature request:** 

Include command line arguments like destdb,destrp to override the DML defintions specified in the export file.

```
influx -import -compressed -path=dumpfile -pps=1000 -destdb=newdb -destrp=newrp
```

**Comment by sachinrase** [comment]
+1

**Comment by kostasb** [comment]
@sachinrase in this case the destination database and retention policy can be manually created by the user before the import is started - just so we can keep this request simple. Otherwise a number of parameters would be needed like retention policy duration, shard duration, replication factor.

**Comment by pmyjavec** [comment]
I just had a talk with @kostasb about this and should have a PR submitted on Monday afternoon, fingers crossed ;)

**Comment by sachinrase** [comment]
is there any  candidate release rpm i can try to test ?

**Comment by dirkdevriendt** [comment]
This would indeed be a useful enhancement.
It took me by surprise actually since the `influx -import` statement allows for a `-database` option but it's just not taken into account.

Especially with the crippled backup/restore support in InfluxCloud I'd expect better import/export options to play around with the data...

**Comment by JogiInnov** [comment]
+1
