### ISSUE TITLE
Small edits to /etc/config.sample.toml

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/influxdb#8358]
### Bug report

__System info:__  InfluxDB v1.2.2

Three issues:
1) [coordinator]
``` 
# The maximum number of series a SELECT can run.  A value of 0 will make the maximum series
# count unlimited.
```
<parameter to set is MISSING>

Next line should be:
```
#max-select-series = 0
```
2) [http]
```
# Determines whether HTTP authentication is enabled.
# auth-enabled = false
```
This is a little confusing as the setting applies equally to situations where HTTPS is enabled, so I would propose "HTTP/HTTPS" to avoid confusion. Otherwise it really does look like you're saying "auth only with http... but what about https?")

3) [http]
```
# Determines whether HTTP request logging is enable.d
# log-enabled = true
```
should read:
```
# Determines whether HTTP request logging is enabled.
# log-enabled = true
```

**Comment by jsternberg** [comment]
I'm a bit confused by #1. I see this in the current file:

```
  # The maximum number of series a SELECT can run. A value of zero will make the maximum series
  # count unlimited.
  # max-select-series = 0
```

What's wrong with that? The only difference I see is the lack of a space between `#` and `max-select-series`.

**Comment by jsternberg** [comment]
Also, for the second, should we not make a reference to HTTP? It makes it sound like the authentication has something to do with HTTP rather than it being authentication used over HTTP. Maybe it should read: `Determines whether user authentication is enabled over HTTP/HTTPS.`

**Comment by timhallinflux** [comment]
agreed..  it should read ```...enabled over HTTP/HTTPS.```

**Comment by jsternberg** [comment]
Never mind on the first. I think I found the issue:

```
  # The maximum number of series a SELECT can run.  A value of 0 will make the maximum series
  # count unlimited.

  # The maximum number of series a SELECT can run. A value of zero will make the maximum series
  # count unlimited.
  # max-select-series = 0
```

**Comment by timhallinflux** [comment]
👍
