### ISSUE TITLE
[Feature Request] Allow `WHERE` clause in `show field keys`

### ISSUE THREAD

**Issue by pkittenis** [influxdata/influxdb#8363]
### Feature Request

__Proposal:__ 

[Show field keys API](https://docs.influxdata.com/influxdb/v1.2/query_language/schema_exploration/#show-field-keys) currently only allows for a measurement to be specified.

It would be great to also be able to limit field key list on tag values via `where` clause, for example:

`SHOW FIELD KEYS FROM <measurement> WHERE <tag key>='<tag value>'`

__Current behavior:__

Show field keys only accepts `FROM` <measurement>

__Desired behavior:__ 

Show field keys to also optionally accept `WHERE <tag key>='<tag value>' [AND|OR <..>]`

__Use case:__

Use case is client filtering of key list on a specific tag or set of tags, eg grafana field key list and other visualisation clients.

Without this it is not possible to retrieve a field key list on a specific tag value,
all field keys for all tag values in the measurement are returned instead.

This makes it impossible for clients to get which field keys are valid for a particular tag and users are forced to go through a potentially very large field key list and try them out one by one to get which fields belong to the tags they are interested in.

**Comment by powertronglobal** [comment]
+1

**Comment by qi-zhou** [comment]
+1

**Comment by bolausson** [comment]
+1

**Comment by vhdmsm** [comment]
+1

**Comment by hallvar** [comment]
+1

**Comment by colin-infersens** [comment]
+1

**Comment by micbuh** [comment]
+1
@rbetts , Milestone 1.4.0 passed by. Still in progress?

**Comment by samirhashdex** [comment]
+1

**Comment by rasanentimo** [comment]
+1

**Comment by DefauIt** [comment]
+1

**Comment by Hortt** [comment]
+1

**Comment by klashagel** [comment]
+1

**Comment by D0mc3k** [comment]
+1 - that would be really valuable

**Comment by fgaetano** [comment]
+1

**Comment by rmarabini** [comment]
+1

**Comment by descilla** [comment]
+1
