### ISSUE TITLE
how to show key values filter by other key values

### ISSUE THREAD

**Issue by qi-zhou** [influxdata/influxdb#8375]
I am a beginner, there is a problem confused me, can you help me? many thanks!
```
influx -version
InfluxDB shell version: 1.2.2
```

for example:
```
> SHOW TAG VALUES FROM "system" WITH KEY = "group"
name: system
key   value
---   -----
group app
group backend
group system
```
```
> SHOW TAG VALUES FROM "system" WITH KEY = "host"
name: system
key  value
---  -----
host applog-1
host appmq_1
host appmq_2
host appmq_3
host backend_1
host backend_2
host backend_3
host backend_4
.......................
```
I want to list host where in my server group,maybe as below:
![influx](https://cloud.githubusercontent.com/assets/16607058/25899725/8726ac3c-35c3-11e7-92da-566965f80cef.png)

how to query ?

**Comment by PatelParas** [comment]
I am also looking for same....

**Comment by PatelParas** [comment]
`SHOW TAG VALUES FROM "system" WITH KEY = "host" WHERE  host =~ /^$servergroup*/`
it should be work. include "all" option with '*' value.

**Comment by qi-zhou** [comment]
I have try it, but it's still not work....and I folow by official doc try it as follows:
![issu01](https://cloud.githubusercontent.com/assets/16607058/26308422/bee3ed94-3f2b-11e7-8eac-ec35d8f238f6.png)
![issue02](https://cloud.githubusercontent.com/assets/16607058/26308411/b3b016c8-3f2b-11e7-825b-c91bd947261d.png)
but the host can't associate with the tags.......

**Comment by juanpaulo** [comment]
If I find understand your issue, `SHOW TAG VALUES FROM "system" WITH KEY = "host" WHERE group =~ /$group/` in the Query field should do it.
