### ISSUE TITLE
Can't use nanosecond duration derivative

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#8390]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Current master (51b60e2)
CentOS/7 & OS-X 10.11.3

__Steps to reproduce:__

1. 
```
insert test v=0i 0
insert test v=1000000000i 1000000000
insert test v=3000000000i 2000000000
insert test v=6000000000i 3000000000
```

2. `select derivative(last(v),1n) from test where time >= 0 and time <= 3000000000 group by time(1s)` 

__Expected behavior:__ [What you expected to happen]
```
name: test
time       derivative
----       ----------
1000000000 1
2000000000 2
3000000000 3
```

__Actual behavior:__ [What actually happened]
```
ERR: error parsing query: invalid duration
```

__Additional info:__ [Include gist of relevant config, logs, etc.]
On older versions of InfluxDB, such as 1.2.1, the resulting derivative would be all `0`.

My current workaround is to do:

    select derivative(last(v),1u)/1000 from test where time >= 0 and time <= 3000000000 group by time(1s)

**Comment by jsternberg** [comment]
Seems reasonable. This lack of parity has annoyed me in the past too.
