### ISSUE TITLE
Upgraded from 1.2.0 to 1.2.2 and Influx only reads WAL files

### ISSUE THREAD

**Issue by antiquechrono** [influxdata/influxdb#8395]
InfluxDB 1.2.0 -> 1.2.2
Windows Server 2008

I backed up my data and downloaded 1.2.2. I assumed all I would need to do is configure 1.2.2 to point at my existing data and it would be able to read it. However when 1.2.2 runs it only reads the WAL files (you can see this in the log) and it never reads any of the data files.

I figured that maybe I needed to perform a backup of the 1.2.0 database and restore it in 1.2.2 so I did that following the instructions in the docs and it copied all the data files to the 1.2.2 directory with the same result, it would only open and read the old WAL files once again.

Something in the log that caught my eye are the following entries.
[I] 2017-05-14T05:57:40Z autogen is not a valid ID. Skipping shard. service=store
[I] 2017-05-14T05:57:40Z monitor is not a valid ID. Skipping shard. service=store
[I] 2017-05-14T05:57:40Z autogen is not a valid ID. Skipping shard. service=store
[I] 2017-05-14T05:57:40Z autogen is not a valid ID. Skipping shard. service=store
[I] 2017-05-14T05:57:40Z autogen is not a valid ID. Skipping shard. service=store
[I] 2017-05-14T05:57:40Z monitor is not a valid ID. Skipping shard. service=store
[I] 2017-05-14T05:57:40Z autogen is not a valid ID. Skipping shard. service=store
[I] 2017-05-14T05:57:40Z autogen is not a valid ID. Skipping shard. service=store

There are no upgrade guides for minor versions so I am assuming this is not expected behavior.

**Comment by jwilder** [comment]
It looks look like your data dir config option is wrong or you restored into the wrong directory.  Can you attach your config file?

Upgrading from 1.2.0 to 1.2.2 only needs to update the package.  Your config and data files on disk don't need to change.

The [release notes](https://github.com/influxdata/influxdb/blob/1.2/CHANGELOG.md#v122-2017-03-14) usually indicate any config option changes that may be important for upgrading.

**Comment by antiquechrono** [comment]
Wow do I feel stupid. I have been trying to get this to work for days, and your comment on the data directory being wrong was correct. Thanks for kicking me in the right direction. 1.2.2 seems to have fixed a query performance problem I was having too.
