### ISSUE TITLE
1.1.4 and 1.2.4 Crash on initialization, out of memory (memory leak?)

### ISSUE THREAD

**Issue by pythianarceri** [influxdata/influxdb#8403]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB 1.1.4 and 1.2.4, Running on docker (17.04) container from rancherOS (1.0.1) on EC2 Instance (r3.large), using telegraf and graphite endpoint to collect metrics
 
__Steps to reproduce:__
Clean databases and wal directories
Start InfluxDB
Let some metrics be captured
Stop InfluxDB
Start it again
(OUT OF MEMORY ERROR)

__Expected behavior:__ [What you expected to happen]
InfluxDB should not try to allocate all available memory

__Actual behavior:__ [What actually happened]
InfluxDB starts allocating all the available memory, if i set /proc/sys/vm/overcommit_memory to 0 or 2 it crashes with the Out of memory error 

__Additional info:__ [Include gist of relevant config, logs, etc.]
[Influxdb_error_dump.txt](https://github.com/influxdata/influxdb/files/1012974/Influxdb_error_dump.txt)

**Comment by jwilder** [comment]
You have a wal segment that looks like it's corrupted and not being recovered correctly.  Can you attach `/data/influxdb/wal/telegraf-internal-prod/autogen/4/_00001.wal` to the issue?  If you move that file out of the way, the DB should startup again.

**Comment by jwilder** [comment]
Looks like this might be fixed in master via https://github.com/influxdata/influxdb/pull/8305

**Comment by pythianarceri** [comment]
@jwilder Here's the suspect wal file, please confirm if the #8305 Fixes it.
Also, can you give a quick explanation about what is causing the corruption/memory leak ? 

[Influxdb_error_dump.txt](https://github.com/influxdata/influxdb/files/1014786/Influxdb_error_dump.txt)

**Comment by pythianarceri** [comment]
Just did @jwilder, check my previous post, i just attached the right file

**Comment by jwilder** [comment]
@pythianarceri Looks like that file is not the problem one.  It loads fine for me.  Can you attach these ones as well?

```
/data/influxdb/wal/rancher/autogen/1/_00001.wal
/data/influxdb/wal/telegraf-dev/autogen/3/_00001.wal
/data/influxdb/wal/rancher/autogen/1/_00004.wal
```

**Comment by pythianarceri** [comment]
I just built a container using a nightly build and it seems to resolve the issue, i'm restoring a database backup and will perform additional checks,

**Comment by jwilder** [comment]
Closing this since you've verified that master resolved the issue.
