### ISSUE TITLE
[Feature Request]Min , Max with number of values to be returned

### ISSUE THREAD

**Issue by rajkumar1994tec** [influxdata/influxdb#8411]
Top gives error results

**Comment by jsternberg** [comment]
Have you tried `top()`?

**Comment by rajkumar1994tec** [comment]
Yes,Top will give the first five data values of the measurement .. its' time dependent .. it doesn't give max 5 values.. it will give first 5 entries..

**Comment by jsternberg** [comment]
I'm not sure I understand. `top()` will give the 5 max values. It breaks ties by using time, but so does `max()`. If `top()` isn't returning the maximum 5 values, can you give me a reproducer so I can see what's happening?

**Comment by rajkumar1994tec** [comment]
close this... my mistake

**Comment by rajkumar1994tec** [comment]
![screen shot 2017-05-22 at 9 49 43 pm](https://cloud.githubusercontent.com/assets/20771097/26318483/e252216c-3f38-11e7-8faa-9a86c7890a0c.png)
