### ISSUE TITLE
No way to close current shard to avoid "field type conflict"

### ISSUE THREAD

**Issue by muravjov** [influxdata/influxdb#8412]
__Use case:__ 

I write points to Influxdb with retention policy duration 1hour with type **float**.
Now I want to change type and write them as **integers**. To not lose a lot of points I have to wait till the end of an hour and start writing integers instead of floats, e.g. at 55 minutes. I will lose 5 minutes but that is the only way to change type on the fly.

If I fail and at the start of an hour the new shard is created with float type again, I have an option to drop the shard.

If the retention policy is sufficiently long, e.g. 1 year long, waiting for the end of shard group duration is not an option.

__Proposal:__ 
I suggest to add a command or way to force ending of the current shard at any time.

__System info:__ Influxdb 1.2.0

**Comment by rbetts** [comment]
https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/cluster-commands/#truncate-shards
