### ISSUE TITLE
Cannot delete point where time > now()

### ISSUE THREAD

**Issue by ConfiDev** [influxdata/influxdb#8413]
### Bug report

__System info:__
InfluxDB Version 1.2.4
Ubuntu 16.04.2 LTS

__Steps to reproduce:__
1. Insert point which has a timestamp > now(). E.g. `test,id=123 value=2 1514764800000000000`
2. Try to delete this point. E.g. `delete from test where time > now()` or just `delete from test`
3. `select * from test` to see that the point is still there

__Expected behavior:__
Point is deleted

__Actual behavior:__
Point is still in the database

**Comment by jsternberg** [comment]
This will be fixed in 1.3.0 by #8329.
