### ISSUE TITLE
Not safe to call client.Write 

### ISSUE THREAD

**Issue by swagerebus** [influxdata/influxdb#8414]
### Bug report

In file: client/v2/client.go line: 368

```
u := c.url
u.Path = "write"
```

It's not safe to call `client.Write(bp BatchPoints)`  while `c.url` is shared with multi go routines, and it's undocumented.
I think a little bit change tohe API make it safer.

**Comment by jsternberg** [comment]
`c.url` seems to be a value so this line:

```
u := c.url
```

This creates a copy. That should be safe for multiple goroutines since everything is read-only.

**Comment by swagerebus** [comment]
My mistake, didn't notice that c.url is not a pointer.
