### ISSUE TITLE
An upper time bound seems to be required to run GROUP BY time, while the documentation states that `now()` is implied.

### ISSUE THREAD

**Issue by AndreCAndersen** [influxdata/influxdb#8415]
### Bug report

__System info:__

InfluxDB v1.2.4 (git: master 77909d7c7826afe597b12d957996d6e16cd1afaa), with Grafana v4.3.0-beta1 (commit: 3a89272) on Ubuntu 14.04.5.

__Steps to reproduce:__

This is a general issue, however, the following query serves as an example: `SELECT mean("HeapInUse") FROM "runtime" WHERE "hostname" = 'myhost' AND time > now() - 3h GROUP BY time(1m)`

__Expected behavior:__

The last 3 hours of HeapInUse binned in 1 minute averages. 

__Actual behavior:__

Error is given: "Server returned error: max-select-buckets limit exceeded: (128798969/1000000)" 

It thinks it is returning the last 3 hours, and up to all future time. If you add an upper bound it works:

`SELECT mean("HeapInUse") FROM "runtime" WHERE "hostname" = 'myhost' AND time > now() - 3h AND time < now() GROUP BY time(1m)`

__Additional info:__

The following commit and location might be where this was changed: https://github.com/influxdata/influxdb/commit/d7c8c7ca4fbb86ac95d1828aaed82545a3d70883#diff-084cb29c383c1c0fffae2fac08113ad5L521

The following grafana issue was also raised: https://github.com/grafana/grafana/issues/8437#issuecomment-303075105

Where in the docs it says the `now()` upper bound is implied: https://docs.influxdata.com/influxdb/v1.2/troubleshooting/frequently-asked-questions/#why-don-t-my-group-by-time-queries-return-timestamps-that-occur-after-now

**Comment by IvanVas** [comment]
+1
