### ISSUE TITLE
Aggregrate Function on Tag Key

### ISSUE THREAD

**Issue by xylene1980** [influxdata/influxdb#8419]
I have enabled **procstat** plugin to track my **httpd** process. I would like to get the count of **process_name** field. The **process_name** field seems to be a tag key field and am not able to get the count of the same. Is there any way to get the count of the tag key field?

I understand that tag keys cannot be used alone. Please advise

**Comment by rbetts** [comment]
I believe you are asking for this feature:
https://github.com/influxdata/influxdb/issues/3880?

**Comment by jsternberg** [comment]
So I don't really know how well this works, but you can hack subqueries to be able to do this. As long as you select at least one field in the subquery. So you can do something like this:

```
> insert cpu,host=server01 value=2
> insert cpu,host=server02 value=3
> select count(distinct(host)) from (select value, host from cpu)
```
