### ISSUE TITLE
Admin interface database list unreachable when list extends past window

### ISSUE THREAD

**Issue by offero** [influxdata/influxdb#8423]
When you have many databases, they are not selectable in the admin UI because the dropdown doesn't allow you to scroll.

## How to reproduce:

- Create a bunch of influx databases
- Go to the admin web interface
- Shrink your browser
- Click the database dropdown
- Databases are unreachable (no scroll)

Influx DB 1.2.4

**Comment by rbetts** [comment]
[Chronograf](https://docs.influxdata.com/chronograf/v1.3/) has replaced the admin web interface on `master` and we aren't enhancing the older versions.

**Comment by offero** [comment]
There's an admin like interface in chronograf now?

**Comment by rbetts** [comment]
Yes - you can read more at the link above or some of the details from the beta period were published on the [blog](https://www.influxdata.com/chronograf-beta-update-dashboards-databases-graph-types-oh/).
