### ISSUE TITLE
how to create udp retention policy 

### ISSUE THREAD

**Issue by Kruler** [influxdata/influxdb#8438]
Hi
I write data into influxdb by using UDP protocol. And I want to create a half_year retention policy for data that be written by UDP. I want to set this configure into config file and don't know how to do, can you give me an example for how to set my own udp retention policy in the config file ? Here is the UDP configure in the config file, I don't know how to set.
enabled = true
bind-address = ":38086"
database = "mkt_data"
retention-policy = ""

**Comment by rbetts** [comment]
Answered here: https://community.influxdata.com/t/how-to-create-udp-retention-policy/1074
