### ISSUE TITLE
retention policy not working as accepted

### ISSUE THREAD

**Issue by lfarkas** [influxdata/influxdb#8439]
Hi.
first i try to describe a very simple basic setup which we'd like to achieve:
* we'd like to push data into a database "test"
* we'd like to push every second a data
* we'd like to keep this detailed data for one hour
* we'd like to keep data for every minutely average for 3 hours
* we'd like to keep data for 15 minutes average data for 6 hours.
is it possible? how can we achieve this? since we're unable to do so. either influxdb do not insert the data or not that way.

of course the 1 3 and 6 hour and the 1 sec, 1min and 15min is just an example. but aging in such a way is a normal way and we're not able to get this result.

we try with latest influxdb on rhel 7. 
i attached a small shell script which demonstrate the problem.

```
influx -execute "DROP DATABASE test"
influx -execute "CREATE DATABASE test"
influx -execute "CREATE RETENTION POLICY one_hour ON test DURATION 1h REPLICATION 1 DEFAULT"
influx -execute "CREATE RETENTION POLICY three_hour ON test DURATION 3h REPLICATION 1"
influx -execute "CREATE RETENTION POLICY six_hour ON test DURATION 6h REPLICATION 1"

#WORKING
#influx -database test -execute "CREATE CONTINUOUS QUERY cq_avg_1m ON test BEGIN SELECT mean(value) AS value_mean INTO cqrptest_1m FROM cqrptest GROUP BY time(1m), unit END"
#influx -database test -execute "CREATE CONTINUOUS QUERY cq_avg_15m ON test BEGIN SELECT mean(value) AS value_mean INTO cqrptest_15m FROM cqrptest GROUP BY time(15m), unit END"

#WORKING
#influx -database test -execute "CREATE CONTINUOUS QUERY cq_avg_1m ON test BEGIN SELECT mean(value) AS value_mean INTO test."one_hour".cqrptest_1m FROM test."one_hour".cqrptest GROUP BY time(1m), unit END"
#influx -database test -execute "CREATE CONTINUOUS QUERY cq_avg_15m ON test BEGIN SELECT mean(value) AS value_mean INTO test."one_hour".cqrptest_15m FROM test."one_hour".cqrptest GROUP BY time(15m), unit END"

#NOT WORKING
influx -database test -execute "CREATE CONTINUOUS QUERY cq_avg_1m ON test BEGIN SELECT mean(value) AS value_mean INTO test."three_hour".cqrptest_1m FROM test."one_hour".cqrptest GROUP BY time(1m), unit END"

#NOT WORKING
#influx -database test -execute "CREATE CONTINUOUS QUERY cq_avg_1m ON test BEGIN SELECT mean(value) AS value_mean INTO test."three_hour".cqrptest_1m FROM test."one_hour".cqrptest GROUP BY time(1m), unit END"
#influx -database test -execute "CREATE CONTINUOUS QUERY cq_avg_15m ON test BEGIN SELECT mean(value) AS value_mean INTO test."six_hour".cqrptest_15m FROM test."one_hour".cqrptest GROUP BY time(15m), unit END"


NODATA=0
while true; do
#       [ "$NODATA" -ge 10 ] && echo && break
        curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary "cqrptest,unit=1 value=$RANDOM" &>/dev/null
        echo -n "."
        sleep 1
        ((NODATA++))
done

echo "DONE"
```

**Comment by rbetts** [comment]
@lfarkas This is a pretty common question. I'd like to point you to some documentation and a couple community posts to see if those documents can help. If not, we would appreciate feedback on how to improve those explanations.

Docs on downsampling: https://docs.influxdata.com/influxdb/v1.2/guides/downsampling_and_retention/

Community questions that might be relevant: 
https://community.influxdata.com/t/downsample-and-downsampling-a-downsample/477
https://community.influxdata.com/t/dependent-continuous-queries-at-multiple-resolutions/638
