### ISSUE TITLE
How can I move data from one Retention Policy to another?

### ISSUE THREAD

**Issue by mflourenco** [influxdata/influxdb#8441]
Sorry for my dumb question, I look around in the internet but I could find an answer for that. A create a new Retention Policy and now all new data are going to this new RP. How can I move the data from another RP for this new one?

Thanks in advance

**Comment by rbetts** [comment]
This community site thread might help - there are a few other threads on community about similar questions if you search for *retention policy*, too. 

https://community.influxdata.com/t/applying-retention-policies-to-existing-measurments/802
