### ISSUE TITLE
Measurement name with '#' character seems not being inserted but there is no error

### ISSUE THREAD

**Issue by mikefonted** [influxdata/influxdb#8444]
### Bug report

__System info:__
Windows 10
Docker 17.03.1-ce
Influxdb 1.2.4

__Steps to reproduce:__

1. The only difference between these two commands is the '#' character in the measurement name. Not a single error/exception when inserting them.
```
curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'foo,host=server01,region=us-west value=0.64 1434055562000000000'
curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary '#foo,host=server01,region=us-west value=0.64 1434055562000000000'
```
2. Check measurements
```
curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=SHOW MEASUREMENTS;"
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "measurements",
                    "columns": [
                        "name"
                    ],
                    "values": [
                        [
                            "foo"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

__Expected behavior:__
I tried to insert more data with another characters, such as !, $, =, :, _ and so on, and all of them are shown when checking measurements. I thougth that would be the case for #.

__Actual behavior:__
There is no error/exception when inserting a measurement with # character, but it is not shown when checking measurements.

**Comment by jwilder** [comment]
`#` defines a comment.  You're second example is a commented out line which is skipped.

See: https://github.com/influxdata/influxdb/blob/master/models/points.go#L288
