### ISSUE TITLE
unexpected fault address 0x13d739f0

### ISSUE THREAD

**Issue by yesman85** [influxdata/influxdb#8453]
[error.txt](https://github.com/influxdata/influxdb/files/1053239/error.txt)

When I run telegraf on Windows 2016 version 1.3.1, I receive attached error.

This my config:

```
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_buffer_limit = 1000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  hostname = "Pr

od-1"

[[outputs.influxdb]]
  urls = ["http://1.2.3.4:8086"] 
  database = "telegraf"
  precision = "s"
  timeout = "5s"

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = ["% Processor Time"]
    Measurement = "win_cpu"
```

I tried stripping things from my config to a bare minimum but the problem stays.

**Comment by jwilder** [comment]
I think you'll need to log this in the [telegraf](https://github.com/influxdata/telegraf) repo.  This is the InfluxDB repo.

**Comment by yesman85** [comment]
I must have been dreaming.. Sorry!
