### ISSUE TITLE
What is the time unit of CompactionDuration in "_internal"."monitor"."tsm1_engine"?

### ISSUE THREAD

**Issue by yuguangchuan** [influxdata/influxdb#8463]
What is the time unit of **CompactionDuration** in "_internal"."monitor"."tsm1_engine"? Nanoseconds?

For example, the time unit of field **cacheCompactionDuration**, **tsmFullCompactionDuration**. Follow is a snapshot of "_internal"."monitor"."tsm1_engine":

![image](https://user-images.githubusercontent.com/15685761/26916895-a6806580-4c5e-11e7-9611-d15a8e5e9d6b.png)

Thanks a lot if somebody can give some tips. I can't find this info from official doc.

**Comment by jwilder** [comment]
Nanoseconds.

**Comment by yuguangchuan** [comment]
thank you~
