### ISSUE TITLE
Unable to write "multiple points" using HTTP call

### ISSUE THREAD

**Issue by karanrajpal14** [influxdata/influxdb#8464]
I'm currently trying to write multiple points into my database using a HTTP call but I can't seem to get it to work. Even the example call given on your documentation isn't working for me. Here's a run down of the different permutations of calls I've tried and what error I'm facing with them.

1 Just one point
`curl -i -XPOST 'http://localhost:8086/write?db=sensordata' -d 'flow,host=server01,region=us-west value=0.64'`

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 1d858abf-4c2d-11e7-832c-000000000000
X-Influxdb-Version: 1.2.4
Date: Thu, 08 Jun 2017 09:30:31 GMT

This works. None of the other permutations that I use below work.

2 Two points and no timestamp
`curl -i -XPOST 'http://localhost:8086/write?db=sensordata' -d 'flow,host=server01,region=us-west value=0.64 flow,host=server02,region=us-west value=0.65'`

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 4b2a3d3a-4c2d-11e7-832d-000000000000
X-Influxdb-Version: 1.2.4
Date: Thu, 08 Jun 2017 09:31:47 GMT
Content-Length: 135

{"error":"unable to parse 'flow,host=server01,region=us-west value=0.64 flow,host=server02,region=us-west value=0.65': bad timestamp"}

3 Two points and one timestamp
`curl -i -XPOST 'http://localhost:8086/write?db=sensordata' -d 'flow,host=server01,region=us-west value=0.64 flow,host=server02 value=1.2 1496914088'`

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 7251f9b5-4c2d-11e7-832e-000000000000
X-Influxdb-Version: 1.2.4
Date: Thu, 08 Jun 2017 09:32:53 GMT
Content-Length: 134

{"error":"unable to parse 'flow,host=server01,region=us-west value=0.64 flow,host=server02 value=1.2 1496914088': bad timestamp"}

4 Two points and two timestamps
`curl -i -XPOST 'http://localhost:8086/write?db=sensordata' -d 'flow,host=server01,region=us-west value=0.64 1496914087 flow,host=server02 value=1.2 1496914088'`

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 7251f9b5-4c2d-11e7-832e-000000000000
X-Influxdb-Version: 1.2.4
Date: Thu, 08 Jun 2017 09:32:53 GMT
Content-Length: 134

{"error":"unable to parse 'flow,host=server01,region=us-west value=0.64 1496914087 flow,host=server02 value=1.2 1496914088': bad timestamp"}

**Comment by hvr993** [comment]
add a line break after every point 

`curl -i -XPOST 'http://localhost:8086/write?db=sensordata' -d 'flow,host=server01,region=us-west value=0.64 **line-break** flow,host=server02,region=us-west value=0.65'`

**Comment by karanrajpal14** [comment]
While that might work (I'll confirm once I'm at work) when I manually enter from the command-line, how would I be doing this from a script? There are a few thousand points that I will be pushing to the database. I tried adding \n and \r\n. Any suggestions?

**Comment by ZhukovAlexey** [comment]
On HP-UX there is a solution
https://github.com/influxdata/influxdb/issues/6636#issuecomment-219941760

But in Linux I couldn't make it today.

**Comment by ZhukovAlexey** [comment]
It works

```
data="OIDTCP,pid=123 tcp=2\nOIDTCP,pid=2345 tcp=3"

curl -X POST $url -A "TCP_LOG INFLUX" --data-binary @- <<EOF
`echo -e $data`
EOF
```

**Comment by carao2020** [comment]
Hi, I am trying to insert data through HTTP post call. Only last point is getting inserted. Could you please help me in this issue.

**Comment by carao2020** [comment]
I can see the data has line break for each point in the http log. But only last point is getting inserted. Kindly help me on this issue.

**Comment by ZhukovAlexey** [comment]
@carao2020 please provide the example of your POST call.

**Comment by carao2020** [comment]
Hi Alexey,

I am trying to insert below mentioned data.

X12_837,type=A ccn="c123456789"
X12_837,type=A ccn="d123456789"

Please see below screenshot showing the content.

![image](https://user-images.githubusercontent.com/33798392/33794399-b9afc42c-dc99-11e7-9873-bcacf85faf54.png)

In addition, please see below Trace content that shows the HTTP POST call from IBM Transformation Extender HTTP Adapter.

![image](https://user-images.githubusercontent.com/33798392/33794438-4da2ca9e-dc9a-11e7-9cae-ab8ac44a2984.png)

Please see below screenshot showing ASCII content of the data that I am trying to insert.

![image](https://user-images.githubusercontent.com/33798392/33794458-9a1aac16-dc9a-11e7-9766-f720cb3fb26d.png)

Kindly review and let me know for additional information. Thanks

**Comment by ZhukovAlexey** [comment]
@carao2020 sorry, I cant' reproduce it because I don't have IBM Transformation Extender and it's not easy to install it.

The problem is definetely in new line symbol.

What platform do you have InfluxDB running on? Windows or Linux?

**Comment by ZhukovAlexey** [comment]
@carao2020 oops, my bad, didn't notice you have identical measurement name, tag set, and timestamp.

See https://docs.influxdata.com/influxdb/v1.3//troubleshooting/frequently-asked-questions/#how-does-influxdb-handle-duplicate-points

**Comment by carao2020** [comment]
Hi Alexey,

Thank you very much for the details. I am able to resolve this issue now. Thanks once again. :)

**Comment by shao82456** [comment]
i thought this problem not sovled.i want to post multiple points to influxdb by program,not a terminal.
also i don't want to write a file then to post.
i want post by concat a string then post,just like

val data="..."
HttpUtil.post(url,data)

i'm sure add '\n' or '\r\n' doesn't work
