### ISSUE TITLE
illumos build broken on syscall.Mmap again

### ISSUE THREAD

**Issue by bahamat** [influxdata/influxdb#8466]
### Bug report

__System info:__

* InfluxDB version: 1.3.0 (according to CHANGELOG.md)
* operating system: SmartOS (illumos) 2017Q1 base-64 image
* Go version: go version go1.8 solaris/amd64

__Steps to reproduce:__

    GOPATH=${PWD}
    PATH=${GOPATH}/bin:$(PATH)
    go get golang.org/x/sys/unix
    go get github.com/sparrc/gdm
    go get github.com/influxdata/influxdb
    ( cd src/github.com/influxdata/influxdb; gdm restore )
    go clean github.com/influxdata/influxdb/...
    go install github.com/influxdata/influxdb/...

__Expected behavior:__

Successful build

__Actual behavior:__

Build error

    go clean github.com/influxdata/influxdb/...
    go install github.com/influxdata/influxdb/...
    # github.com/influxdata/influxdb/pkg/mmap
    src/github.com/influxdata/influxdb/pkg/mmap/mmap_unix.go:30: undefined: syscall.Mmap
    src/github.com/influxdata/influxdb/pkg/mmap/mmap_unix.go:42: undefined: syscall.Munmap
    Makefile:8: recipe for target 'bin/influxdb' failed
    make: *** [bin/influxdb] Error 2

**Comment by bahamat** [comment]
This is similar to #4787.

**Comment by jwilder** [comment]
There is an `mmap_solaris.go` in the repo which is the fix for #4787, but it looks like your OS is using the unix one for some reason. 


`mmap_unix.go` has:
```
// +build !windows,!plan9,!solaris
```

`mmap_solaris.go` has:

```
// +build solaris
```

Maybe try `GOOS=solaris go install github.com/influxdata/influxdb/...`?  Perhaps the build constraints need to specify `illumos` as well?

**Comment by bahamat** [comment]
Ok, I'll try setting `GOOS=solaris` when I get a chance to try it again.

**Comment by bahamat** [comment]
Simply setting `GOOS` doesn't help. It fails with the same error.

The fix for #4787 has a `mmap_solaris.go` specifically for the tsdb package. The error I'm getting is in `pkg/mmap`.

I made an attempt at duplicating the `mmap_solaris.go` file in `pkg/mmap`, which I *think* made progress, but still ultimately fails. The error I get now is:

```
# github.com/influxdata/influxdb/tsdb/index/tsi1
src/github.com/influxdata/influxdb/tsdb/index/tsi1/index_file.go:80: undefined: mmap.Map
src/github.com/influxdata/influxdb/tsdb/index/tsi1/index_file.go:97: undefined: mmap.Unmap
src/github.com/influxdata/influxdb/tsdb/index/tsi1/index_files.go:156: undefined: mmap.Unmap
src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:104: undefined: mmap.Map
src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:153: undefined: mmap.Unmap
src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:866: undefined: mmap.Unmap
src/github.com/influxdata/influxdb/tsdb/index/tsi1/series_block.go:975: undefined: mmap.Map
```

**Comment by jwilder** [comment]
@bahamat Can you try building from #8514?  It should resolve the compilation issue now.

**Comment by bahamat** [comment]
I've confirmed that I can build after this commit.
Thanks!
