### ISSUE TITLE
Piping CURL statement into influx CLI results in error

### ISSUE THREAD

**Issue by PritishDeb** [influxdata/influxdb#8467]
Bug report

System info: influxdb-1.2.4-1, Windows 7

Steps to reproduce:
query: curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

Expected behavior: It should create a database mydb

Actual behavior: 
Server returned error: error parsing query: found curl, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1

Additional info: Is it like configuration file needs to be modified somewhere to make it work.

**Comment by mark-rushakoff** [comment]
Curl needs to be run from your shell, not from the `influx` prompt.

The command you pasted works correctly:

```
curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Request-Id: d5a4f92a-689c-11e7-8001-000000000000
X-Influxdb-Version: 1.2.4
Date: Fri, 14 Jul 2017 14:00:46 GMT
Transfer-Encoding: chunked

{"results":[{"statement_id":0}]}
```

Corresponding influxdb log lines:

```
[I] 2017-07-14T14:00:46Z CREATE DATABASE mydb service=query
[httpd] 172.17.0.1 - - [14/Jul/2017:14:00:46 +0000] "POST /query HTTP/1.1" 200 33 "-" "curl/7.51.0" d5a4f92a-689c-11e7-8001-000000000000 13532
```
