### ISSUE TITLE
Aggregate data automaticly

### ISSUE THREAD

**Issue by lwhile** [influxdata/influxdb#8472]
### Feature Request

__Proposal:__ 
Aggregate data automaticly like zabbix.

__Desired behavior:__ 
I write some metrics to influxdb in every 1s. I hope 1h later influxdb can  delete some metrics and save metrics that interval by 1m.

__Use case:__ 
 System monitor

**Comment by marchtea** [comment]
I think that's exactly what `continuous query` and `retention policy` does, you can take a [look](https://docs.influxdata.com/influxdb/v1.2/guides/downsampling_and_retention)

**Comment by lwhile** [comment]
@marchtea  I had solved my problem by continuous query and retention policy, thank you
