### ISSUE TITLE
SIGSEGV in store.go

### ISSUE THREAD

**Issue by hpbieker** [influxdata/influxdb#8483]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB starting, version 1.3.0-n201705150800, branch master, commit 3b700863eaa3fae65a995ce65ca12fc85c0a6995
Ubuntu 16.4, x64, 16 cores, 96 GB RAM

__Steps to reproduce:__
Unknown.

__Expected behavior:__ [What you expected to happen]
Do not crash.

__Actual behavior:__ [What actually happened]
June 13th 2017, 02:12:37.000	INFO	[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x830062]
June 13th 2017, 02:12:37.000	INFO	#011/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:623 +0x48
June 13th 2017, 02:12:37.000	INFO	goroutine 11400756 [running]:
June 13th 2017, 02:12:37.000	INFO	github.com/influxdata/influxdb/tsdb.(*Store).monitorShards.func2(0xc4203c88c0, 0x0, 0xca8d9a1fb4)
June 13th 2017, 02:12:37.000	INFO	github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1(0xcaf6ad8ae0, 0xca847889c0, 0xc4203c88c0)
June 13th 2017, 02:12:37.000	INFO	created by github.com/influxdata/influxdb/tsdb.(*Store).walkShards
June 13th 2017, 02:12:37.000	INFO	#011/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:629 +0x97
June 13th 2017, 02:12:37.000	INFO	github.com/influxdata/influxdb/tsdb.(*Shard).ForEachMeasurementTagKey(0xc4203c88c0, 0xc955018880, 0x19, 0x20, 0xcae6c33e00, 0x0, 0x0)
June 13th 2017, 02:12:37.000	INFO	#011/root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:967 +0x92
June 13th 2017, 02:12:37.000	INFO	#011/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:1117 +0x19c

__Additional info:__ [Include gist of relevant config, logs, etc.]

June 13th 2017, 02:12:39.000	INFO	InfluxDB starting, version 1.3.0~n201705150800, branch master, commit 3b700863eaa3fae65a995ce65ca12fc85c0a6995
June 13th 2017, 02:12:39.000	 - 	Stopped InfluxDB is an open-source, distributed, time series database.
June 13th 2017, 02:12:39.000	INFO	   888            d88P"  888                   888  "Y88b 888  "88b
June 13th 2017, 02:12:39.000	INFO	   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
June 13th 2017, 02:12:39.000	INFO	   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
June 13th 2017, 02:12:39.000	ERROR	influxdb.service: Unit entered failed state.
June 13th 2017, 02:12:39.000	 - 	influxdb.service: Service hold-off time over, scheduling restart.
June 13th 2017, 02:12:39.000	 - 	influxdb.service: Failed with result 'exit-code'.
June 13th 2017, 02:12:39.000	INFO	 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"
June 13th 2017, 02:12:39.000	INFO	Using configuration at: /etc/influxdb/influxdb.conf
June 13th 2017, 02:12:37.000	INFO	panic: runtime error: invalid memory address or nil pointer dereference
June 13th 2017, 02:12:37.000	INFO	[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x830062]
June 13th 2017, 02:12:37.000	INFO	#011/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:623 +0x48
June 13th 2017, 02:12:37.000	INFO	goroutine 11400756 [running]:
June 13th 2017, 02:12:37.000	INFO	github.com/influxdata/influxdb/tsdb.(*Store).monitorShards.func2(0xc4203c88c0, 0x0, 0xca8d9a1fb4)
June 13th 2017, 02:12:37.000	INFO	github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1(0xcaf6ad8ae0, 0xca847889c0, 0xc4203c88c0)
June 13th 2017, 02:12:37.000	INFO	created by github.com/influxdata/influxdb/tsdb.(*Store).walkShards
June 13th 2017, 02:12:37.000	INFO	#011/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:629 +0x97
June 13th 2017, 02:12:37.000	INFO	github.com/influxdata/influxdb/tsdb.(*Shard).ForEachMeasurementTagKey(0xc4203c88c0, 0xc955018880, 0x19, 0x20, 0xcae6c33e00, 0x0, 0x0)
June 13th 2017, 02:12:37.000	INFO	#011/root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:967 +0x92
June 13th 2017, 02:12:37.000	INFO	#011/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:1117 +0x19c
June 13th 2017, 02:12:36.000	INFO	Closing /media/wal_disk/wal/_internal/monitor/3436 engine=tsm1 service=wal
June 13th 2017, 02:12:36.000	INFO	deleted shard group 3436 from database _internal, retention policy monitor service=retention
June 13th 2017, 02:12:36.000	INFO	retention policy shard deletion check commencing service=retention
June 13th 2017, 02:12:35.000	INFO	compacting level 2 group (0) /media/db_volume/data/_internal/monitor/3570/000000004-000000002.tsm (#1) engine=tsm1
June 13th 2017, 02:12:35.000	INFO	compacted level 1 2 files into 1 files in 1.906092086s engine=tsm1
June 13th 2017, 02:12:35.000	INFO	compacting level 2 group (0) /media/db_volume/data/_internal/monitor/3570/000000002-000000002.tsm (#0) engine=tsm1

**Comment by hpbieker** [comment]
This is perhaps a duplicate of #8473?

**Comment by jwilder** [comment]
Dup of #8473
