### ISSUE TITLE
modify schema (add new tags) on a point given a timestamp

### ISSUE THREAD

**Issue by tcloaa** [influxdata/influxdb#8484]
Hi,

In the documentation of v1.2, it is stated that: "InfluxDB is a schemaless database which means it’s easy to **add new measurements, tags, and fields at any time**. It’s designed to make working with time series data awesome." 

But after searching all the information in the docs, I don't see methods that can add new tags/fields on a point given a timestamp.

Can anyone explain this?

Thanks,

**Comment by mark-rushakoff** [comment]
@tcloaa would you mind taking this question to https://community.influxdata.com ?
