### ISSUE TITLE
InfluxDB write http curl missing fields

### ISSUE THREAD

**Issue by mykolaminaiev** [influxdata/influxdb#8490]
I try to perform curl write to influx
curl -i -XPOST "http://host:8086/write?db=test&u=root&p=root" --data-binary 'events title="fixVersion",text="Git branch",tags="sometag"'
and I get error
{"error":"unable to parse 'events': missing fields"}
What I did wrong?

**Comment by boonyachengdu** [comment]
> 
> 
> I try to perform curl write to influx
> curl -i -XPOST "http://host:8086/write?db=test&u=root&p=root" --data-binary 'events title="fixVersion",text="Git branch",tags="sometag"'
> and I get error
> {"error":"unable to parse 'events': missing fields"}
> What I did wrong?

I meet the same problem. What do you solve it?

 public static async System.Threading.Tasks.Task<string> PostAsync(string url,string database, string username, string password,string sql,string rp)
        {
            using (var client = new HttpClient())
            {
                HttpHelper.SetRequestHeaders(client,username,password);
                var values = new List<System.Collections.Generic.KeyValuePair<string, string>>();
                values.Add(new KeyValuePair<string, string>("db", database));
                values.Add(new KeyValuePair<string, string>("u", username));
                values.Add(new KeyValuePair<string, string>("p", password));
                values.Add(new KeyValuePair<string, string>("q", sql));
                values.Add(new KeyValuePair<string, string>("rp", rp));
                var content = new FormUrlEncodedContent(values);

                var response = await client.PostAsync(url, content);

                var responseString = await response.Content.ReadAsStringAsync();

                return responseString;
            }
        }

I used url with http://localhost:8086/write . If I submit params like that I'll get {"error":"database is required"}.But, When I add all params in url and I get parse error.

**Comment by bdekoz** [comment]
You're both missing a datestamp field.

'events title="fixVersion",text="Git branch",tags="sometag" DATESTAMP-in-SEC-or-WHATEVER-db-is-using'
