### ISSUE TITLE
Order by time desc inverts transformations across groupings (difference, derivative, etc)

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#8498]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB: 0b4528b
OS: OS-X

__Steps to reproduce:__

1. 

    insert test v=1i 0
    insert test v=2i 1000000000
    insert test v=3i 2000000000

2. `select difference(v) from test order by time desc`

__Expected behavior:__ [What you expected to happen]
```
name: test
time       difference
----       ----------
2000000000 1
1000000000 1
```

__Actual behavior:__ [What actually happened]
```
name: test
time       difference
----       ----------
1000000000 -1
0          -1
```

__Additional info:__
Not sure if this is intentional behavior or not, but to me it seems like a bug.

**Comment by jsternberg** [comment]
It seems to me like the value at 2s is 3 and the value at 1s is 2. If you are going in descending order, that's a difference of -1 between those two points. Are you saying that the difference should be calculated left to right regardless of ordering?

**Comment by phemmer** [comment]
`ORDER BY` should be controlling the order of the output, not the input.

Since InfluxDB is trying to be SQL-like, it should follow SQL standards, and what people expect.
The best official doc I could find is https://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt. Unfortunately to obtain recent revisions of the spec requires purchasing them. However from the referenced doc we have:

> If an &lt;order by clause&gt; is specified, then the ordering of rows
            of the **result** is effectively determined by the <order by clause>
            as follows:
> ...

*(emphasis mine)*
