### ISSUE TITLE
[1.4.0] Subquery aliases not being honored by main query

### ISSUE THREAD

**Issue by sethm** [influxdata/influxdb#8499]
### Bug report

__System info:__ CentOS 7.2, InfluxDB Nightly 1.4.0 (downloaded on 2017-06-15)

__Steps to reproduce:__

    > create database testdb
    > use testdb
    > insert example,host_name="host_1" load=2.0
    > insert example,host_name="host_2" load=3.0
    > insert example,host_name="host_1" load=1.8
    > insert example,host_name="host_2" load=2.8
    > insert example,host_name="host_1" load=1.0
    > insert example,host_name="host_2" load=3.1

Now select using an `AS` alias, which works exactly as expected:

    > SELECT load, host_name AS host FROM example
    name: example
    time                load host
    ----                ---- ----
    1497564540373915680 2    "host_1"
    1497564544694285527 3    "host_2"
    1497564548965953957 1.8  "host_1"
    1497564555365609713 2.8  "host_2"
    1497564559645782517 1    "host_1"
    1497564564412889302 3.1  "host_2"

But, use this query in a subquery and try to group by `host`.

    > SELECT MEAN(load) FROM (SELECT load, host_name AS host FROM example) GROUP BY host

__Expected behavior:__ 

Results should be returned grouped by `host_name` aliased as `host`.

__Actual behavior:__ 

No grouping occurs.

    > SELECT MEAN(load) FROM (SELECT load, host_name AS host FROM example) GROUP BY host
    name: example
    tags: host=
    time mean
    ---- ----
    0    2.283333333333333

Could this issue be related to #7972 ? It's the nearest thing I could find when searching for similar reports.

**Comment by jsternberg** [comment]
It is not possible to do that. Since `host` gets converted to a field in the subquery, you cannot group by it in the outer query. We also do not have a way to alias tags.

**Comment by jsternberg** [comment]
I'm going to close this since there's no resolution possible for it. I do not believe this to be related to #7972. Thank you for reporting this issue and if you have any further trouble, please feel free to reach out to our [community site](https://community.influxdata.com).
