### ISSUE TITLE
Provide packages for Debian 9 'stretch'

### ISSUE THREAD

**Issue by mcktr** [influxdata/influxdb#8506]
### Feature Request

I relay don't know if I am right here and I don't know if there is anything planned. 

__Proposal:__ 

Please provide packages for Debian 9 'stretch'. 
I know that the release of Debian 9 happened this weekend and that it is still hot, so no stress :) 

__Current behavior:__ 

There are no packages for Debian 9 on the [repository](https://repos.influxdata.com/debian/dists/).

__Desired behavior:__ 

Packages for Debian 9 on the official repository.  

__Use case:__ 

Debian 9 is now the stable release.

**Comment by gjuric** [comment]
It looks like this has already been implemented -> https://repos.influxdata.com/debian/dists/stretch/

**Comment by mcktr** [comment]
Thanks for the hint. The day I created this issue I couldn't find a stretch package. 

Since this issue is resolved, I am closing this here. Thanks.
