### ISSUE TITLE
Query can return both strings and parseable JSON

### ISSUE THREAD

**Issue by tagyoureit** [influxdata/influxdb#8508]
### Bug/feature report

__System info:__ 1.2.4 - HTTP query response

__Steps to reproduce:__

1. http://localhost:8086/query?q=select+*+from+circuits+limit+4&db=_your_db_here_&chunked=true&chunk_size=5
2. http://localhost:8086/query?q=select+*+from+circuits+limit+6&db=_your_db_here_&chunked=true&chunk_size=5

__Expected behavior:__ I would expect both of these queries to return similar types of responses.

__Actual behavior:__ Step 1 returns parseable JSON.  Step 2 returns a string that has to be split with "/n".  While this example coerces the behavior of the response, similar scenarios can happen with any data<chunk_size compared to data>chunk_size.  

Results for 1: {"results":[{"statement_id":0,"series":[{"name":"circuits","columns":["time","circuitFunction","colorStr","freeze","friendlyName","lightgroup","name","number","numberStr","status"],"values":[["2017-05-17T14:40:02.285055781Z","Spa","off",0,"SPA","-1","SPA","1","circuit1",0],["2017-05-17T14:40:02.285865363Z","Intellibrite","off",0,"POOL LIGHT","4","POOL LIGHT","8","circuit8",0],["2017-05-17T14:40:02.285865365Z","Intellibrite","off",0,"PATH LIGHTS","4","PATH LIGHTS","9","circuit9",0],["2017-05-17T14:40:02.285867742Z","Generic","off",0,"WATERFALL MEDIUM","-1","WtrFall 2","13","circuit13",0]]}]}]}

Results for 2:
{"results":[{"statement_id":0,"series":[{"name":"circuits","columns":["time","circuitFunction","colorStr","freeze","friendlyName","lightgroup","name","number","numberStr","status"],"values":[["2017-05-17T14:40:02.285055781Z","Spa","off",0,"SPA","-1","SPA","1","circuit1",0],["2017-05-17T14:40:02.285865363Z","Intellibrite","off",0,"POOL LIGHT","4","POOL LIGHT","8","circuit8",0],["2017-05-17T14:40:02.285865365Z","Intellibrite","off",0,"PATH LIGHTS","4","PATH LIGHTS","9","circuit9",0],["2017-05-17T14:40:02.285867742Z","Generic","off",0,"WATERFALL MEDIUM","-1","WtrFall 2","13","circuit13",0],["2017-05-17T14:40:02.285872332Z","Generic","off",0,"AIR BLOWER","-1","AIR BLOWER","3","circuit3",0]],"partial":true}],"partial":true}]}
/n
{"results":[{"statement_id":0,"series":[{"name":"circuits","columns":["time","circuitFunction","colorStr","freeze","friendlyName","lightgroup","name","number","numberStr","status"],"values":[["2017-05-17T14:40:02.285878446Z","Generic","off",0,"WATERFALL HIGH","-1","WtrFall 3","14","circuit14",0]]}]}]}

This make is very unfriendly to try to programmatically deal with responses because we need to first test to see if the response is a string or a JSON (and this precludes the use of $.getJSON if a string is being returned).  Then additional logic is needed to split the string and then parse those into JSON.  

__Additional info:__ I do see similar issues/PRs but not sure if they are solving this exact problem.
https://github.com/influxdata/influxdb/pull/8477
https://github.com/influxdata/influxdb/issues/8450

Also, this part "]],"partial":true}],"partial":true}]}" doesn't look quite correct.  Are there supposed to be two partial:"true" elements in the object?

**Comment by phemmer** [comment]
Remove `chunked=true` from your URL.

**Comment by tagyoureit** [comment]
Yes, clearly I could remove `chunked=true` for a small sample like this.  My point, however, is that my code _was_ working as I did my development on a manageable (~20k rows) dataset.  When I put my code in production Influx automatically started chunking my results and my code broke.  I didn't add the `chunked=true`.  It took me 3 days to track down this "behavior" which is the reason I'm logging this as a bug.

There is also no mention of this artifact in the docs either [here](https://docs.influxdata.com/influxdb/v1.2/guides/querying_data/#chunking) or [here](https://docs.influxdata.com/influxdb/v1.2/tools/api/#query-string-parameters) when talking about chunking data back.  There also isn't any indication that the InfluxDB definition of chunked responses is different from a traditional [chunked encoding](https://www.httpwatch.com/httpgallery/chunked/) which also took some time to understand.

Love the DB!  Just pointing out things that are really hard to understand and not consistent within the product/docs.

**Comment by jsternberg** [comment]
This is intentional and we'll work on improving the documentation for the current behavior. The two `"partial": true` values are also intentional. One of them says that the series is partial (and will be returned in the next result returned) and the second says that the result is partial (and should be merged with the first).

I know this is confusing which is the reason why #8450 exists to try and simplify this structure so we can retire the existing syntax. While we won't eliminate the current method since that would be backwards incompatible, the new method would offer an easier way to get the same thing in an easier to parse way.

I hope that helps clarify it a bit. I'll leave this open until I create the issue for documenting the chunking format in more detail.
