### ISSUE TITLE
Ethereum Geth Miner Bloackchain Sync Error "Fatal Error: out of memory"

### ISSUE THREAD

**Issue by Jordz2203** [influxdata/influxdb#8511]
**Expected Behavior-** 
For Geth to Sync to Ethereum Network.

**What Actually Happened-**  **(Full Stack In Attached Text Doc)** 
[Blockchain Sync Error.txt](https://github.com/influxdata/influxdb/files/1087839/Blockchain.Sync.Error.txt)
runtime: out of memory: cannot allocate 268435456-byte block (905314304 in use)
fatal error: out of memory 
runtime stack:
runtime.throw(0xc6c852, 0xd)
        C:/go/src/runtime/panic.go:596 +0x7c
runtime.largeAlloc(0x10000000, 0x1e50001, 0x44c033)
        C:/go/src/runtime/malloc.go:809 +0xdb
runtime.mallocgc.func1()
        C:/go/src/runtime/malloc.go:702 +0x31
runtime.systemstack(0x12126000)
        C:/go/src/runtime/asm_386.s:337 +0x5e
runtime.mstart()
        C:/go/src/runtime/proc.go:1132

**Additional Information-**

PC Rig Specs:
CPU: i5-6600k @ 3.5 GHz
RAM: 16GB-DDR4-2133 MHz-2x8GB
Storage: Samsung 256GB M.2 SSD + 2TB Segate SSHD
Motherboard: Gigabyte Z170-XP-SLI
GPU: 2x Palit GeForce GTX 970-Core clock = 1050 MHz-Memory clock = 3505
No items in this list are overclocked.

Command/s Used: `geth --rpc` and same error for `geth --rpc --fast --cache=1024`

Versions of Software:
Win-10 
geth-windows-386-1.6.5-cf87713d
cpp-ethereum-windows-v1.2.8

**Comment by phemmer** [comment]
I think you took a wrong turn somewhere. This is the InfluxDB repo :-)

**Comment by Jordz2203** [comment]
@phemmer yeaaaaaahhhhh maybe a little bit😂
