### ISSUE TITLE
Influxdb can't properly startup and then crash when running in cluster mode

### ISSUE THREAD

**Issue by eugene64** [influxdata/influxdb#8517]
### Bug report

Influx 0.11.1-1 on Ubuntu 14.04

Influx configured on 3 nodes. At some one of the influx instances may crash, that randomly causes other nodes to crash, or to enter a non-functional state.
Removing /var/lib/influx/meta/raft.db helps starting influx.

At crash, influx generates > 1 Gigabyte of logs with stacktraces.
Exrtact from one of the log files:

[http] 2017/06/19 13:18:53 172.31.0.7 - lma [19/Jun/2017:13:18:48 +0000] POST /write?db=lma&precision=ms HTTP/1.1 200 23 - Go 1.1 package http d48fa359-54f1-11e7-b9bf-000000000000 4.241293808s [panic:runtime error: invalid memory address or nil pointer dereference]
[http] 2017/06/19 13:18:53 172.31.0.7 - lma [19/Jun/2017:13:18:51 +0000] POST /write?db=lma&precision=ms HTTP/1.1 200 23 - Go 1.1 package http d661a174-54f1-11e7-ba92-000000000000 1.191367571s [panic:runtime error: invalid memory address or nil pointer dereference]
[http] 2017/06/19 13:18:53 172.31.0.7 - lma [19/Jun/2017:13:18:46 +0000] POST /write?db=lma&precision=ms HTTP/1.1 200 23 - Go 1.1 package http d365ae70-54f1-11e7-b974-000000000000 6.198227652s [panic:runtime error: invalid memory address or nil pointer dereference]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x58 pc=0x5b39ec]

goroutine 1723 [running]:
github.com/influxdata/influxdb/cluster.(*PointsWriter).MapShards(0xc20805d4a0, 0xd16d4ebdc0, 0x8, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/points_writer.go:215 +0x6ec
github.com/influxdata/influxdb/cluster.(*PointsWriter).WritePoints(0xc20805d4a0, 0xd16d4ebdc0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/points_writer.go:248 +0x233
github.com/influxdata/influxdb/cmd/influxd/run.(*monitorPointsWriter).WritePoints(0xc20805d4a0, 0xc208087e90, 0x9, 0xc334a0, 0x7, 0xca68321000, 0x7f, 0x7f, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:759 +0xf8
github.com/influxdata/influxdb/monitor.(*Monitor).storeStatistics(0xc20811e000)
        /tmp/influxdb/src/github.com/influxdata/influxdb/monitor/service.go:344 +0xbf8
created by github.com/influxdata/influxdb/monitor.(*Monitor).Open
        /tmp/influxdb/src/github.com/influxdata/influxdb/monitor/service.go:105 +0x33c

That is followed by strack trace of almost 1.5 millions of goroutines (which possibly is a reason of crash, OOM?)

**Comment by mark-rushakoff** [comment]
We no longer support influxdb 0.11.
