### ISSUE TITLE
The ability to restore an InfluxDB backup to a different database name.

### ISSUE THREAD

**Issue by JeremySTX** [influxdata/influxdb#8519]
### Feature Request

__Proposal:__ 
The `influxd backup` command backs up a named database to a set of files.  The `influxd restore` command reads those files to create a database.  This request is to allow the `restore` command to create the output database with a different name.

__Current behavior:__
The restored database inherits the name of the backed-up database, and there is no way to change it.

__Desired behavior:__ 
Allow the restored database to get a different name to that which it had when the backup was made.

__Use case:__ 
We back up our InfluxDB database daily. If we need to compare the "live" database against a backup the only way to do it now is to restore the database to another system.  Being able to restore the backup to the same server, but with a different name assigned to the restored database, would simplify direct comparison between the old and new "live" databases, without interfering with InfluxDB activitiy on any other server.

**Comment by bpcrao** [comment]
on the same problem any other solution to this ?

**Comment by aanthony1243** [comment]
This is resolved as of version 1.5.  See: https://docs.influxdata.com/influxdb/v1.5/administration/backup_and_restore/
