### ISSUE TITLE
 Nested queries performing horribly - performance bug?

### ISSUE THREAD

**Issue by PauloAugusto-Asos** [influxdata/influxdb#8520]
### Bug(?) report
As per the community thread in:
https://community.influxdata.com/t/nested-queries-performing-horribly-performance-bug/1321

I'm seeing the performance of InfluxDB's nested queries be extremely poor.

For example, this query, which returns 659 lines runs in 120~150 ms:
`SELECT last("ServiceStatus") as ServiceStatus FROM "DefaultPaulo"."ServiceStats" WHERE "Environment" =~ /^PT02$/ AND Time > now() - 7m AND ServiceName != 'Asos.Service.Emailer' AND ServiceName != 'Asos.Stock.DespatchImportService' AND ServiceName != 'Asos.Stock.StockExportService' AND ServiceStartType <> 4 GROUP BY "ServiceName", "host"`

While this simple SELECT FROM the same query with a trivial WHERE, runs in 4~5 seconds:
`SELECT host, ServiceName, ServiceStatus FROM (`
`SELECT last("ServiceStatus") as ServiceStatus FROM "DefaultPaulo"."ServiceStats" WHERE "Environment" =~ /^PT02$/ AND Time > now() - 7m AND ServiceName != 'Asos.Service.Emailer' AND ServiceName != 'Asos.Stock.DespatchImportService' AND ServiceName != 'Asos.Stock.StockExportService' AND ServiceStartType <> 4 GROUP BY "ServiceName", "host"`
`) WHERE "ServiceStatus" <> 4`

---
...
---

I do know things like the Regex expression filters can naturally perform poorly due to the underlying complexity of regex searches. However, both of those things are performing just fine in the inner query - 120~150ms.

The nested query, though, is adding very minimal work on top of the inner query, not justifying making it 30 times slower... It's applying 1 single WHERE filter against the only selected field. I can't conceive any reason for that 2nd layer of querying to add such a performance hit: we're talking of 660 lines of data, and the field "ServiceStatus" will only have some 2~5 different values, which is what's making me guess this is a performance problem.

**Comment by jackzampolin** [comment]
@PauloAugusto-Asos Can you share your InfluxDB version?

**Comment by PauloAugusto-Asos** [comment]
@jackzampolin Doh! I should have remembered that that info would be required, sorry...

`influx -version` _(which I seem to understand is bound to the version of "influxdb" itself)_ reports:
`InfluxDB shell version: 1.2.4`

**Comment by daveselan** [comment]
We have also seen this issue (running the latest nightly builds) and found exactly the same result when moving the time constraint to the inner SELECT. The query would run 30x slower!
The results are very consistant, doesn't seem to matter how or what we query.

** where time is in inner SELECT, runs in 16.51 seconds! **

```
% time influx -database 'testdb' -execute 'SELECT count(first) FROM (SELECT first("jobcount") FROM "jobstats" WHERE "group" =~ /GPU/ AND "area" =~ /testing/ AND time > now() - 1h GROUP BY "jobno")'
name: jobstats
time count
0    422

0.000u 0.004s 0:16.51
```

** where time is in outer SELECT, runs in 0.360 seconds **

```
% time influx -database 'testdb' -execute 'SELECT count(first) FROM (SELECT first("jobcount") FROM "jobstats" WHERE "group" =~ /GPU/ AND "area" =~ /testing/ GROUP BY "jobno") WHERE time > now() - 1h'
name: jobstats
time count
0    422

0.004u 0.000s 0:00.36
```

**Comment by sinmki** [comment]
@daveselan I can confirm this issue remains within the latest 1.4.2 release. Thanks for the heads up.
