### ISSUE TITLE
Select substring of key value

### ISSUE THREAD

**Issue by waltari2001** [influxdata/influxdb#8522]
Hi,

I am trying to extract a substring from a key value. The select statement returns:

1498157240000000000 ip=10.11.180.1,port=6380,state=online,offset=1617190510,lag=1

And I need to set a graph based on the value of offset. Is there a substr like function?

Thanks,

Sadek

**Comment by jsternberg** [comment]
Can you show me how you are getting that data?

**Comment by waltari2001** [comment]
The data is being fed to influxDB via the redis input plugin.

**Comment by jsternberg** [comment]
I mostly mean how are you querying the data? Are you using curl or a library? Can you show me some of the code? I'm not sure where you are getting line protocol output from when querying the server.

**Comment by waltari2001** [comment]
Using influx CLI. The line above is the output of this SELECT statement

select slave0 from redis

**Comment by jsternberg** [comment]
@waltari2001 can you show me which redis plugin this is? If that's the query you are using, it appears that the data is getting fed in improperly somehow. Can you show me the copy and pasted output from the CLI?

/cc @jackzampolin

**Comment by waltari2001** [comment]
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/redis

the 'slaveX' fields are just deducted from the output of the redis-cli info (Replication section).

# redis-cli  info replication
# Replication
role:master
connected_slaves:2
slave0:ip=10.148.10.32,port=6379,state=online,offset=3627,lag=1
slave1:ip=10.148.10.33,port=6379,state=online,offset=3627,lag=0
master_repl_offset:3627
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:2
repl_backlog_histlen:3626


influx CLI output

> select slave0 from redis limit 2;
name: redis
time                slave0
----                ------
1498757360000000000 ip=10.148.10.32,port=6379,state=online,offset=2759,lag=1
1498757360000000000 ip=10.148.10.32,port=6379,state=online,offset=2745,lag=1

**Comment by jackzampolin** [comment]
@waltari2001 Would you mind posting this over on community.influxdata.com. That site is more for q&a while we try to keep Github just for issues.

**Comment by dandv** [comment]
@waltari2001: [InfluxDB doesn't have string processing functions](https://community.influxdata.com/t/query-data-from-json/2334/3?u=dandv). You'll need to split your data into field=value pairs before storing it.
