### ISSUE TITLE
Unable to copy field names after aggregation

### ISSUE THREAD

**Issue by Nopik** [influxdata/influxdb#8524]
When query like `select sum(*) from foo` is executed, the field names are having added `sum_` prefix by default. So, the resulting fields might be `sum_bar` & `sum_baz`. `AS` is supported, but only allows to change one prefix to another, not to remove the prefix. I.e. `sum(*) as summary` will name fields `summary_bar` & `summary_baz`. The problem is: it does not allow lack of prefix. The best you can do is to `sum(*) as ""`, but it will still produce `sum_bar` & `sum_baz` as if `AS` would not be there.

Why this is a problem? When having a number of continuous queries to gradually degrade the precision, the prefixes do accumulate. So, if you have one CQ to aggregate last hour by 1 minute and another CQ to aggregate last day by 1 hour, you will end up with `sum_sum_bar` or `sum_sum_baz`.

That requires your application to be very sensitive throughout its code to the aggregation settings, as introducing new aggregation period will add another instance of the prefix into the fields, potentially breaking unprepared applications. Alternative - you need to specify each field manually, which kind of breaks the schemaless approach.  

Expected behavior: being able to get `bar` and `baz` plain original names after CQ is executed.

# System info
InfluxDB: 1.3.0, from Docker Hub.

**Comment by Nopik** [comment]
Since there is `:MEASUREMENT` backref possible when operating on numerous measurements, maybe some `sum(*) AS :FIELD` would do? Or at least `AS ""` to actually drop the prefix (& the `_` join string!) - but this will alter existing semantics, so probably is not advisable.

**Comment by Nopik** [comment]
Anyone? :(

**Comment by mark-rushakoff** [comment]
Seems like a reasonable feature request to me. I can't speak to how it compares to our other current priorities.

**Comment by jsternberg** [comment]
I think this may be the same as #7332. If I'm wrong, please comment and I'll reopen.
