### ISSUE TITLE
count() doesn't support tag

### ISSUE THREAD

**Issue by tongh-qtl** [influxdata/influxdb#8529]
It's diffrerent from mysql
I know we can use show tag values to do the same thing but we may query very more times

**Comment by jsternberg** [comment]
A current workaround for this is to trick the system using subqueries. You just need to choose a known field and do this:

```
SELECT count(distinct(host)) FROM (SELECT value, host FROM cpu)
```

Not as performant as an ideal solution, but it works.

**Comment by sebito91** [comment]
This would be awesome, to be honest :heart:

**Comment by tongh-qtl** [comment]
@jsternberg it works,thx
we may make the tag be a redundancy field.it may waste some storage but the performance may be good

**Comment by jcmcken** [comment]
This would be extremely useful. I often have a need to visualize the number of rows that match certain criteria (e.g. in Grafana). I'm using the workaround suggested by @jsternberg , but it would be nice if this were baked into a real feature of the language.

**Comment by to-masz** [comment]
`SHOW TAG VALUES CARDINALITY FROM memcached WITH KEY = "host" WHERE environment =~ /^$country$/`

**Comment by TUTUBIG** [comment]
it's too slow to count a field even we have tag.wish could count something like "time" just to make this process quick
