### ISSUE TITLE
Allow math in aggregate functions

### ISSUE THREAD

**Issue by jgysel** [influxdata/influxdb#8530]
### Feature Request

__Proposal:__ Allow simple math on fields before applying aggregate functions
Example:
```
> SELECT sum(valueA * valueB) as prodAB FROM input."default".measureAB where time > now() - 1h group by time(5m)

time                 prodAB
----                 ---------
2017-06-27T09:30:00Z 22
```
for the following input:
```
> SELECT valueA,valueB FROM input."default".measureAB where time > now() - 1h

time                 valueA valueB
----                 ------ ------
2017-06-27T09:28:40Z 3      4
2017-06-27T09:29:00Z 2      5
```

__Current behavior:__ 
```
> SELECT sum(valueA * valueB) as prodAB FROM input."default".measureAB where time > now() - 1h group by time(5m)
ERR: error parsing query: expected field argument in sum()
...
```

**Comment by jsternberg** [comment]
This is possible with subqueries at the moment. Have you tried using those?

**Comment by jgysel** [comment]
Using subqueries may be a solution for short term. I'm currently cautious using subqueries because of issue #8528. IMHO in the long term this issue should be implemented as (according to my observations) subqueries are not that performant.
