### ISSUE TITLE
[bug] tag in the where clause returning unexpected tag in result

### ISSUE THREAD

**Issue by MarshallRJ** [influxdata/influxdb#8532]
### Bug report

System: Ubuntu 14.04.4 LTS
Docker InfluxDb version: 1.2.1

 On our production server. When running the following query for a specific tag "serial". The returned result is for a different tag "serial".

1.  curl -G 'http://myserver:8086/query?pretty=true' --data-urlencode "db=mdm" --data-urlencode "q=SELECT * FROM \"profile\" WHERE \"**serial**\"='**ELON083465**' LIMIT 1"

__Expected behavior:__ We expect  the returned result to be have a "serial" tag value of "**ELON083465**"

__Actual behavior:__  The query returns the result for a  different "serial" tag of "**ELON062399**"

returned result:

>

    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "profile",
                    "columns": [
                        "time",
                        "measure",
                        "rate",
                        "serial",
                        "type",
                        "value"
                    ],
                    "values": [
                        [
                            "2017-05-29T12:00:00Z",
                            "forwardActiveEnergy",
                            null,
                            "ELON062399",
                            0,
                            769
                        ]
                    ]
                }
            ]
        }
    ]

**Comment by MarshallRJ** [comment]
update: After a restart of  the influx db docker container. The result started to return the correct tag value as expected.

> 

    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "profile",
                    "columns": [
                        "time",
                        "measure",
                        "rate",
                        "serial",
                        "type",
                        "value"
                    ],
                    "values": [
                        [
                            "2017-05-29T12:00:00Z",
                            "forwardActiveEnergy",
                            null,
                            "ELON083465",
                            0,
                            769
                        ]
                    ]
                }
            ]
        }
    ]

**Comment by jsternberg** [comment]
I'm not sure what this was, but I'm going to close this issue since it seems to have resolved itself. If you or anybody else runs into this same issue, please comment again and I can reopen this.
