### ISSUE TITLE
What would be the correct query?

### ISSUE THREAD

**Issue by anarwal27** [influxdata/influxdb#8542]
Hi, 

I am new to influxdb and was working on different querires, however I was unable to get through one:

```
 SELECT * FROM "timers" GROUP BY "category"
name: timers
tags: category=histogram
time                entity                           hostname lower    mean     metric    p50      p70.5    upper
----                ------                           -------- -----    ----     ------    ---      -----    -----
1498682444113000000 Controller-getAll someHost    16908288 16908288 histogram 16908288 16908288 16908288
```

In the above table, I am trying to value mean. What will be the query?

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.
