### ISSUE TITLE
Some deletes by tag don't work

### ISSUE THREAD

**Issue by alex-tan** [influxdata/influxdb#8544]
### Bug report

__System info:__

Influx: 1.2.4
Ubuntu 14

__Steps to reproduce:__

1. Insert data with different tag values.
2. Run delete query.

__Expected behavior:__

Data with the given tag deletes

__Actual behavior:__

Data will sometimes delete

__Additional info:__

I ran a delete query with something like `delete from samples where sample_adapter_id='1' or sample_adapter_id='2'...` for around 10k tag values and about 9k of them successfully deleted but some remaining samples with certain tag values won't delete.

Example of deletion failure:
```bash
> select count(*) from samples where sample_adapter_id='138650'
name: samples
time count_value
---- -----------
0    4472

> delete from samples where sample_adapter_id='138650'
> select count(*) from samples where sample_adapter_id='138650'
name: samples
time count_value
---- -----------
0    4472
```

**Comment by e-dard** [comment]
@alex-tan can you provide the script or exact dataset to reproduce this issue?

**Comment by alex-tan** [comment]
@e-dard Yeah I'll see if I can get you both sometime next week

**Comment by jwilder** [comment]
Is any of your data in the future?  #8329 fixed the default `time < now()` which might be the issue you are seeing.

**Comment by jwilder** [comment]
#8576 may fix this.

**Comment by alex-tan** [comment]
@jwilder yes we have future data. Pretty confident that's the issue at this point.

I'll close the issue for now unless something changes.

Thanks!
