### ISSUE TITLE
Run CQs in parallel

### ISSUE THREAD

**Issue by jgysel** [influxdata/influxdb#8545]
### Feature Request

__System info:__ Influx 1.2.4, Linux 4.1.19_1, 4x E5-2660 v4 @ 2.00GHz (56 cores in total), 256GB RAM, 2TB SSD RAID 10 (8 Disks)

__Current behavior:__ We run a 1.6M cardinality InfluxDB  with ~500 CQs. We cannot add any further CQs as they're processed sequentially and overall runtime must be below the lowest CQ interval (of 5m).  
We already tried to use kapacitor batch tasks to offload expensive CQs. But enabling kapacitor with two subscriptions introduces an 3x increase in memory consumption and 2x increase in CPU without having any enabled kapacitor task.

__Desired behavior:__ Introduce parallelization. I've seen the pro and cons regarding parallelism https://github.com/influxdata/influxdb/issues/8005#issuecomment-298076222. I think on the long term there is no way around it as this will become a limiting factor for larger setups. 

To avoid the introduction of a dependency tree I could imagine to introduce parallelization only for CQs operating on a single DB as a first implementation.

**Comment by bbczeuz** [comment]
Have you tried using a cron-triggered script that performs the query?
i.e something like:
```
influx -execute 'SELECT * INTO dest FROM src WHERE time > ... AND time < ...'
```
Not sure if this more performant than CQ. I had to use this solution to handle some cases in a previous setup.

**Comment by jgysel** [comment]
Thanks @bbczeuz for the hint! Wrote a script triggered by cron that runs CQ-like queries as proposed by you. The load is much lower compared to using kapacitor. 
Unfortunately absolute time must be used. Using relative time (e.g. `WHERE time > now() AND time < now - 10m`) would be much easier to implement, but leads to wrong results (as the cronjobs are always slightly delayed and aren't able to run exactly at the desired time).

**Comment by sethm** [comment]
I'd like to bump this feature request a bit.

We're running a system with many CQs. Ideally we would like to have all of our data aggregated every 5 minutes, but since the sum of all CQs run in series takes over 10 minutes... we're backing up, and it's leading to a poor customer experience.

The queries are largely looking at completely separate measurements, so we're not facing a condition where locking should be a big issue.
