### ISSUE TITLE
Points recently inserted are returning empty fields

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#8546]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB: 2f11347
OS: MacOS X

__Steps to reproduce:__

1. Insert data at a high rate
2. `select * from test where time > now() - 100ms`

Script for # 1: 
```
i=0
while true; do
	i=$((i+2))
	curl -X POST "http://localhost:8086/write?db=test&precision=ns" --data-binary "test,t1=a,t2=b,t3=c v1=$i,v2=${i}i,v3=\"$i\""
done 
```

__Expected behavior:__ [What you expected to happen]
Receive complete points with all fields populated.

__Actual behavior:__ [What actually happened]
Receive incomplete points with some fields null.

```
> select * from test where time > now() - 100ms
name: test
time                           t1 t2 t3 v1     v2     v3
----                           -- -- -- --     --     --
2017-06-29T15:04:01.906665463Z a  b  c  813769 813769 813769
2017-06-29T15:04:01.922380449Z a  b  c  813771 813771 813771
2017-06-29T15:04:01.939411767Z a  b  c  813773 813773 813773
2017-06-29T15:04:01.955888153Z a  b  c  813775 813775 813775
2017-06-29T15:04:01.969290488Z a  b  c  813777 813777 813777
2017-06-29T15:04:01.982402594Z a  b  c  813779 813779 813779
2017-06-29T15:04:01.99984825Z  a  b  c         813781 813781
2017-06-29T15:04:02.06506347Z  a  b  c                813783
```

__Additional info:__ [Include gist of relevant config, logs, etc.]
If I run the query a second later, the data comes back fully populated:
```
> select * from test where time='2017-06-29T15:04:02.06506347Z'
name: test
time                          t1 t2 t3 v1     v2     v3
----                          -- -- -- --     --     --
2017-06-29T15:04:02.06506347Z a  b  c  813783 813783 813783
```

**Comment by e-dard** [comment]
@phemmer I suspect that this is because we process data to be made queryable asynchronously. When writes are returned as successful, that's an indication that the server received the data and persisted it within the WAL. It's not an indication that the data is queryable. 

I expect if you were to insert the same amount of data, but it was batched up so it span across a single or several writes that you would be unlikely to see this issue. Have you experienced this issue with batched up data?

**Comment by phemmer** [comment]
To me this seems like a significant problem. In regards to the asynchronous thing, I would expect the point to come back fully, or not come back at all. How is a client supposed to differentiate a point where the fields really are null from a point which is incomplete because InfluxDB hasn't finished constructing it?

I tried micro-batches (2 or 3 points per batch) and observed the same behavior. I had not tried larger.
