### ISSUE TITLE
Support Inequalities in SELECT

### ISSUE THREAD

**Issue by philbarclay** [influxdata/influxdb#8552]
### Feature Request

__Proposal:__ Support inequalities (`=`,`!=`,`<`,`>`,`<=`,`>=`) in SELECT statements

__Current behavior:__ Empty results for all data types, [as per documentation](https://docs.influxdata.com/influxdb/v1.2/query_language/math_operators/#logical-operators-are-unsupported)

__Desired behavior:__ Return a time-series of boolean results based on the inequality test.

__Use case:__ I monitor the power draw of a pump from which I would like to infer the state of operation.  The pump draws <1W (but not 0) when off, and about 100W when active.  I would like to interpret this as a boolean time-series to allow a plot of on/off.  I would like to do something along the lines of:
```
SELECT mean("value") > 50 FROM "pump_power"
```

This was previously mentioned in case #3552 but that case is slightly different.

**Comment by bbczeuz** [comment]
Currently, this is possible using kapacitor (eval+lambda), but I'd prefer to have such a feature in the query language. This is much more flexible (and easier to use).

**Comment by bbczeuz** [comment]
If this feature is going to be implemented:
- Allow arbitrary complex queries with booleans and/or inequalities. (e.g. `SELECT pump_power > 50 AND pump_pressure < 10 AND pump_inlet_volume >= pump_outlet_volume - 10 FROM "pump_stats"`)
