### ISSUE TITLE
How to aggregate on the results of 2 columns?

### ISSUE THREAD

**Issue by tcloaa** [influxdata/influxdb#8554]
In InfluxDB0.12, it is ok to do `select min(a) from measurement`, where `a` is a field/tag.

However, if I would like to do `select min(a - b) from measurement`, where `a` and `b` are columns.(which means that I would like to see the min/max/median of 2 columns). How shall I perform this action in InfluxDB?

I always receive error parsing query: expected field argument in min()

**Comment by yangguang760** [comment]
select min(c) from (select a - b as c from measurement)

**Comment by tcloaa** [comment]
Thanks, but I think

`select min(*) from (select a-b from measurement)`

 will do as well...
