### ISSUE TITLE
Ahead of time grouping with null values.... 

### ISSUE THREAD

**Issue by theoDiefenthal** [influxdata/influxdb#8555]
We have an Open Source (Community) InfluxDB instance running remotely in version 1.2.2 in a docker container.

If I query a measurement all along with aggregation, a grouping by time and a given start but without an end date, I expect the result to be matched to the entire dataset beginning from start and going to the end, but not more. However, in the result Influx creates some more "time group buckets" ahead of time and fills their values with `null` as there are obviously no points yet. I would be happy, if you exclude those meaningless `null`-buckets. 

For a demonstration. I have a measurement like this:
```
> SELECT value FROM "MY_SENSOR" ORDER BY time DESC LIMIT 10
name: MY_SENSOR
time                 value
----                 -----
2017-06-30T03:45:00Z 1.2
2017-06-30T03:30:00Z -3.6
2017-06-30T03:15:00Z 5.2
2017-06-30T03:00:00Z -9.6
2017-06-30T02:45:00Z 7.2
2017-06-30T02:30:00Z 0
2017-06-30T02:15:00Z 0.40000000000003
2017-06-30T02:00:00Z 4
2017-06-30T01:45:00Z 0
2017-06-30T01:30:00Z 0
```

and now, I do an aggregation operation on that measurement like the following:
```
> SELECT MEAN("value") AS "value" FROM "MY_SENSOR" WHERE time >= '2017-05-07T11:45:00Z' GROUP BY time(100m)
name: MY_SENSOR
time                 value
----                 -----
2017-05-07T11:20:00Z 0.15999999999999998
2017-05-07T13:00:00Z -2.6285714285714343
2017-05-07T14:40:00Z 3.8285714285714305
.....
Lot more values
.....
2017-06-30T02:00:00Z 0.5142857142857186
2017-06-30T03:40:00Z 1.2
2017-06-30T05:20:00Z null
2017-06-30T07:00:00Z null
2017-06-30T08:40:00Z null
2017-06-30T10:20:00Z null
2017-06-30T12:00:00Z null
2017-06-30T13:40:00Z null
```

As you see, there are some useless null entries at the end... 
They occur for COUNT, MEAN ,... doesn't matter.

This behavior occurs in the Java Influx SDK as well as in the CLI, so it's a problem of the response which is sent by Influx via REST...

**Comment by phemmer** [comment]
https://docs.influxdata.com/influxdb/v1.2/query_language/data_exploration/#group-by-time-intervals-and-fill

> none                                        Reports no timestamp and no value for time intervals with no data.

**Comment by theoDiefenthal** [comment]
This is not about fills. This is about that the query response goes "over range". I don't want to fill anything which shouldn't be there...

**Comment by phemmer** [comment]
What do you mean "over range". You didn't specify a maximum time.

**Comment by theoDiefenthal** [comment]
Well by not specifying a maximum, I expect influx to send "buckets" for all data which it has, and not more. In my opinion, there is a logical end where influx should stop creating buckets which is, when there are no more time points. (And not 1-20 buckets later). That's what the ticket is about.

**Comment by e-dard** [comment]
@theoDiefenthal do you happen to have, for example, points data with timestamps between `2017-06-30T12:00:00Z` and `2017-06-30T13:40:00Z`? I'm thinking that the buckets might be being created based on the boundaries in the shard, i.e., upto the maximum known point in the shard, and that towards the end of the shard you don't have any `value` fields in the points data.
