### ISSUE TITLE
Continous query mismatch when grouping by one week

### ISSUE THREAD

**Issue by dbason** [influxdata/influxdb#8569]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
influxdb-1.2.4, CentOS 7.3

__Steps to reproduce:__

1. Create a continuous query with a group by period of either 1w or 7d
2. Check the downscaled data and note that it is missing data

__Expected behavior:__ [What you expected to happen]
The continuous query should run with a time range from Thursday - Thursday as this is how the 7d period is grouped (based on epoch time)

__Actual behavior:__ [What actually happened]
The time period for the continuous query runs Monday to Monday so it only delivers 4 days worth of data

__Additional info:__ [Include gist of relevant config, logs, etc.]
WHERE time >= '2017-07-03T00:00:00Z' AND time < '2017-07-10T00:00:00Z'
(journalctl is terrible sorry so I can't grab the full log line)  This is the most recent WHERE clause produced by the CQ.

**Comment by dbason** [comment]
Hi, any comments on this?  It's causing a few issues for our downsampling use case

**Comment by rbetts** [comment]
@jsternberg has traced this to: https://github.com/influxdata/influxdb/blob/master/services/continuous_querier/service.go#L351

We incorrectly expected this to `Truncate()` to a Thursday but it truncates to the golfing zero time start of week -- which is Monday. We will have to change our code to fix this bad assumption. This playground shows the actual result: https://play.golang.org/p/WAzIHdUcxo
