### ISSUE TITLE
Suddenly getting "authorization failed" messages for admin and users

### ISSUE THREAD

**Issue by capaulson** [influxdata/influxdb#8573]
Version:
Connected to -------------:8086 version 1.2.4
InfluxDB shell version: 1.2.4

Steps to recreate:
In influx:

> auth
username: admin
password:
> show users
ERR: authorization failed

System hasn't been modified, no passwords have been changed. It just suddenly stopped authenticating. Any ideas on what went wrong? Hints on how to reset passwords?

**Comment by mvadu** [comment]
same here.. Trying with nightly.. 
```powershell
    #start without auth
    $proc = Start-Process -FilePath $influxd -PassThru
    $user = "influx"
    $passwd = "admin"
    $r = Invoke-WebRequest -Method Post -Uri "http://localhost:8086/query" -Body "q=CREATE USER   $user WITH PASSWORD '$passwd' WITH ALL PRIVILEGES" -UseBasicParsing
	
    #enable auth & restart
    $proc.Kill()
    (get-content $influxconf | foreach-object {$_ -replace "# auth-enabled = false" , "auth-enabled = true" })  | Set-Content $influxconf	
    Start-Process -FilePath $influxd -ArgumentList "-config $influxconf" | Out-Null

    $r = Invoke-WebRequest -Method Post -Uri "http://localhost:8086/query?u=$user&p=$passwd" -Body "q=show users" -UseBasicParsing
````
giving me ` Invoke-WebRequest : {"error":"authorization failed"}`

**Comment by mvadu** [comment]
Update on my situation, 

1. I needed to re-generate the config file on the target platform (Windows in my test)
2. It does not like to have a non ASCII letter in password. (e.g. `influx§`)

```
.\influx.exe -username admin -password influx§

Connected to http://localhost:8086 version 1.4.0~n201707240800
InfluxDB shell version: 1.4.0~n201707240800
> show databases
ERR: authorization failed
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```

**Comment by prab2014** [comment]
Getting the same issue with influxdb hosted on containers version 1.8.6 oss
