### ISSUE TITLE
InfluxClient raises Errors during insert without context

### ISSUE THREAD

**Issue by Tsachi-Simplex** [influxdata/influxdb#8581]
### Bug report
InfluxDBClient sometimes raises Exceptions on insert without data.
This makes it hard to debug issues and know whether they are on my end.
Using InfluxDBClient version 4.1.0.

__System info:__ Only Python client version is relevant - InfluxDBClient 4.1.0

__Steps to reproduce:__
Once in every ~500-1000 insert operations, I get an Error without a description / message / stack trace

1. Use `client.write_points([measurement_dict])` many times, eventually I get an error.

__Expected behavior:__ If I get an error - I should have some context to know what was the issue

__Actual behavior:__ Empty exception.

**Comment by mark-rushakoff** [comment]
Sounds like this bug belongs on the https://github.com/influxdata/influxdb-python issue tracker.
