### ISSUE TITLE
Backslash in measurement name does not produce expected measurements

### ISSUE THREAD

**Issue by danielnelson** [influxdata/influxdb#8587]
### Bug report

While testing escaping in line protocol I noticed an odd corner cases with backslashes in the measurement name.  Based on [the latest docs](https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_reference/#special-characters) the only values you can escape in the measurement name are spaces and commas, but it seems that in some cases you can escape a double backslash.

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

InfluxDB v1.2.4 (git: master 77909d7c7826afe597b12d957996d6e16cd1afaa)

__Steps to reproduce:__

1. Start influx cli
```
> insert a\\b v=1
> show measurements
name: measurements
name
----
a\\b

> insert a\\=b v=1
> show measurements
name: measurements
name
----
a=b
a\\b

> select * from "a\\b"
> select * from "a\\=b"
name: a\=b
time                v
----                -
1499818212841546478 1
```

__Expected behavior:__ [What you expected to happen]

Measurement named `a\\=b` created

__Actual behavior:__ [What actually happened]

Measurement named `a=b` was created

**Comment by jwilder** [comment]
Backslashes in the line protocol are problematic and some cases are not fixable without breaking changes.  See #6008 #5231 #4865 #5407
