### ISSUE TITLE
influxdb crash and be killed for the fatal error:out of memory

### ISSUE THREAD

**Issue by zj861222** [influxdata/influxdb#8588]
[attach.zip](https://github.com/influxdata/influxdb/files/1141308/attach.zip)
Actually,influxdb run normaly for about one month,but today the influxdb crash again,and be killed .i check the log file, there is a fatal error :out of memory .

then when i restart the influx db ,it crash again qunickly,and can not work any more.

#### System info: 
[  InfluxDB shell version: 1.0.2, 
  Running on Linux version 4.4.19-29.55.amzn1.x86_64 (mockbuild@gobi-build-64012),and 12G memory for free, 
  and we use grafana to show the collected data from influxdb ]

#### Steps to reproduce:

[First Step]  influxdb crashed,the be killed.
[Second Step] restart the influxdb,then it start and quickly crash again.

#### Expected behavior: 
[i hope it can run normally,without out of memory error]

#### Actual behavior:
 [it always crash, and be killed]

#### Additional info:
 [ attach file is the influxd.log and the influxdb.conf.]
[attach.zip](https://github.com/influxdata/influxdb/files/1141308/attach.zip)

**Comment by jrbury** [comment]
Based on the fact that it goes out of memory on startup leads me to believe that you may have tag cardinality that is too high, and the server is going OOM when trying to build the tag index.

Are you able to temporarily increase the memory of the VM? If so and you can get it started you can try running this query to see your Cardinality

```
SELECT numSeries FROM "_internal".."database" WHERE time > now() - 10s GROUP BY "database" ORDER BY desc LIMIT 1
```

**Comment by zj861222** [comment]
@jrbury  you mean the tags cardinality is too high?the memory can not increase anymore,so i delete the data and it can run normally.  actually everytime where i delete  the data,it can run normally for about two month ,so i doubt it is caused by the data increased .the influxdb can create a job to periodic delete the data ?or could you give me a suggest how to avoid  the OOM?

**Comment by jrbury** [comment]
Yes, because Influx has to build an in memory index for all tags having high tag cardinality can cause the box to go OOM. If clearing the database fixes it then it is most likely your issue. You can create a retention policy on the database which will automatically delete data outside the retention window.


If you want to modify the default retention policy you can use this query, by default the auto retention policy is infinite
```
ALTER RETENTION POLICY autogen ON <database_name> DURATION <duration> REPLICATION 1 [DEFAULT]
```

**Comment by jwilder** [comment]
@zj861222 It's crashing while trying to allocate a slice when compacting a string series.  1.0.2 is pretty old and you may be hitting a bug that was already fixed.  I'd suggest upgrading to the latest release.

**Comment by zj861222** [comment]
@jrbury   actually i have set the retention policy ,
> SHOW RETENTION POLICIES ON server_monitor
name	duration	shardGroupDuration	replicaN	default
autogen	72h0m0s		24h0m0s			1		true

**Comment by zj861222** [comment]
@jwilder thank you very much ,i will have a try to update to the latest version.

**Comment by kshcherban** [comment]
I face the same issue, upgrade from 1.3.1 to 1.3.7 didn't help. Lots of errors like 
```
WARN: 100% of max-values-per-tag limit exceeded: (100001/100000), db=telegraf shard=605 measurement=docker_container_blkio tag=container_name service=store
```
Mostly for the `docker_container_*` measurements. 

4-7 minutes after startup influxdb dies out of memory.
The funny thing that instance has 32GB of RAM and only 48GB of metrics data.
Is there a possibility to make influxdb work without adding more memory or deleting all data?
