### ISSUE TITLE
[bug] SHOW FIELD KEYS missing results

### ISSUE THREAD

**Issue by bbczeuz** [influxdata/influxdb#8589]
### Bug report

__System info:__ 
```
[lab@test ~]$ uname -a
Linux test.local 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[lab@test ~]$ influx
Connected to http://localhost:8086 version 1.2.4
InfluxDB shell version: 1.2.4
```
- Kapacitor 1.3.1
- Telegraf v1.3.1 (git: release-1.3 f93615672b02a41d9bc867bd92bf31c1d777989b)

__Steps to reproduce:__

1. I use telegraf's snmp plugin to store interface metrics in DB `telegraf`, measurement `interface` (Retention policy `raw`)
2. InfluxDB streams this data to Kapacitor; Kapacitor performs some calculations and stores the results in measurement `interface_norm` (Retention policy `store30d`)
3. I want to display the scheme of interface_norm:
```
> USE telegraf.store30d
Using database telegraf
Using retention policy store30d
> FORMAT json
> SHOW FIELD KEYS FROM interface_norm
{"results":[{}]}
> 
```

__Expected behavior:__
```
> USE telegraf.store30d
Using database telegraf
Using retention policy store30d
> FORMAT json
> SHOW FIELD KEYS FROM interface_norm
{"results":[{"series":[{"name":"interface","columns":["fieldKey","fieldType"],"values":[["ifOutDiscards","integer"],["ifOutErrors","integer"],["ifOutMulticastPkts","integer"],["ifSpeed","integer"]
...
```
__Actual behavior:__ 
```
> USE telegraf.store30d
> SHOW MEASUREMENTS
name: measurements
name
----
[...]
interface
interface_norm
[...]

> SHOW FIELD KEYS FROM interface_norm
[nothing!]

> SELECT ifName, rx_bps FROM interface_norm WHERE "hostname" = 'qfx5100-01' AND "ifName" = 'ge-0/0/45' LIMIT 1
name: interface_norm
time                 ifName    rx_bps
----                 ------    ------
2017-07-05T16:34:02Z ge-0/0/45 2914.6666666666665
```

__Additional info:__ 
- There is actual data in `interface_norm` (SELECT returns data)
- There are many series in `interface_norm`:
```
[lab@test ~]$ influx -database telegraf -execute 'SHOW SERIES' | egrep '^interface_norm' | wc -l
203
```
- Possibly the issue arises as measurement `interface_norm` only exists in retention policy `store30d`
- I cannot select a RP with `SHOW FIELD KEYS`

**Comment by bbczeuz** [comment]
__Additional info__
- We have tags and fields. Displaying tags works:
```
> SHOW TAG KEYS FROM interface_norm
name: interface_norm
tagKey
------
agent_host
host
hostname
ifAlias
ifDescr
ifName
kapacitor
```
- There are 1.8M rows:
```
> SELECT COUNT(rx_bps) FROM interface_norm
name: interface_norm
time                 count
----                 -----
1970-01-01T00:00:00Z 1845537
```

**Comment by mark-rushakoff** [comment]
I suspect there's some funny interaction between the CLI's `use` statement, `SHOW FIELD KEYS`, and the default retention policy. Do you get the correct result if you specify the fully qualified measurement, i.e. `SHOW FIELD KEYS FROM my_db.my_rp.my_measurement`?

**Comment by bbczeuz** [comment]
Yes, that could act as a workaround. Manually selecting an RP in the SHOW FIELD KEYS query displays the correct fields.
```
> USE telegraf
Using database telegraf
> SHOW RETENTION POLICIES
name     duration shardGroupDuration replicaN default
----     -------- ------------------ -------- -------
raw      168h0m0s 24h0m0s            1        true
store30d 720h0m0s 24h0m0s            1        false
> SHOW FIELD KEYS FROM raw.interface
name: interface
fieldKey                   fieldType
--------                   ---------
ifConnectorPresent         integer
ifAdminStatus              integer
[...]
> SHOW FIELD KEYS FROM raw.interface_norm
> SHOW FIELD KEYS FROM store30d.interface
> SHOW FIELD KEYS FROM store30d.interface_norm
name: interface_norm
fieldKey      fieldType
--------      ---------
ifAdminStatus integer
ifOperStatus  integer
[...]
```
(the middle two results are empty)

But this is still quite surprising:
```
SHOW FIELD KEYS
```
always shows the field keys of the series in the default RP (not the one currently selected using `USE my_db.my_rp`)
(it actually doesn't even display the measurements not existing in the default RP)
So, in order to get the whole picture, one needs to iterate through all RPs and measurements.... probably even the shards as according to the docs, different shards can have different field types.

**Comment by bbczeuz** [comment]
Any updates on this?

**Comment by rbetts** [comment]
The internal iterators used for several of the `show` commands has been changed on master to re-use more code from the query engine. We should re-test this on master.

**Comment by e-dard** [comment]
@rbetts this is still not working on `tip`. I'll add to 1.4 milestone and we can review if we have enough time to fix?

**Comment by jwilder** [comment]
This looks related or similar root issue as #7404

**Comment by dannybeeckman** [comment]
+1
