### ISSUE TITLE
Shell ignores extra parameters

### ISSUE THREAD

**Issue by aseigneurin** [influxdata/influxdb#8593]
### Feature Request

__Proposal:__ trigger an error when launching the shell with extra parameters (arguments, not options).

__Current behavior:__ when you launch the shell, arguments are simply ignored. This can be misleading.

Each database has its own CLI, and you could forget whether you need to pass the hostname to connect to as an option or as an argument. If you pass the hostname as an argument and have a local InfluxDB database running, it will connect to your local DB, but you might think it successfully connected to the remote host.

```
$ influx host_I_want_to_connect_to
Connected to http://localhost:8086 version v1.3.0
InfluxDB shell version: v1.3.0
>
```

__Desired behavior:__ an error would be ideal. It should print the usage and indicate that the extra argument is not valid.

__Use case:__ this just saves time in case people make a mistake in their command line.

**Comment by stop-start** [comment]
Hi! I would like to take this if nobody is working on it.

**Comment by mark-rushakoff** [comment]
@stop-start I believe everyone on the Influx team is focused on other efforts right now - feel free to pick this up if you'd like. Thanks.
