### ISSUE TITLE
InfluxDB Write Performance

### ISSUE THREAD

**Issue by J8299** [influxdata/influxdb#8594]
**Problem Statement:**
  I am having trouble getting InfluxDB to keeping up with my write requests.

**Problem Experienced Detail:**
  I seem to be missing subsequent requests for the next 3-5 minutes as the 1st request "catches up" - I assume the DB is locking out later requests until it finishes with the first work loads
  The Grafana dashboard looks like an electrocardiograph with peaks every 5 minutes

**Hardware:**
  RHEL7 EC2: m4.2xl with 8 vCPUs & 32 GB Ram
  EBS: io1 - 2TB - IOPS = 20,000 (x2)

**InfluxDB:**
  version 1.2.4

**Data:**
  15k-20k records a minute
  Records are 3 fields + 3 tags

**Attempts:**
  I can write 1 by 1 or 2000-4000 records at a time
  I have tried writing http & python influxdb
  I can write these records with "204 success", showing up in my parsed log of several days running, 99.93% of the time - the server seems to keep up more often than not
  I have a Grafana dash and I can literally watch the volume bars "grow" as the database catches up

**Remedies:**
  I tried adding a UDP _(mounted on a different device)_ but still see slow catch-up
  I tried upping the IO buffer per docs: https://docs.influxdata.com/influxdb/v0.9/write_protocols/udp/

Any help would be greatly appreciated!

**Comment by 25ar** [comment]
I have the same issue.
Help please to resolve it

**Comment by allen13** [comment]
I've ran into this problem in the past with UDP just dropping data. The biggest problem is that since it's UDP, you don't know when something bad happens. I've found it's more performant and 100% reliable to just use batched http requests. 

https://docs.influxdata.com/influxdb/v1.3/guides/writing_data/#writing-multiple-points
