### ISSUE TITLE
Cannot back up database starting with underscore character

### ISSUE THREAD

**Issue by mdbartos** [influxdata/influxdb#8598]
### Bug report

__System info:__
Influxdb version (Remote): 1.0.0
Operating system name (Remote): Ubuntu, 14.04.4 LTS (AWS EC2 instance)  
Influxdb version (Local): 1.3.0
Operating system name (Local): macOS

__Steps to reproduce:__
Start influxd on remote machine
Start influxd on local machine
Run backup service on local machine to backup remote database
```influxd backup -database _TEST -host <host>:8088 /path/to/backup```

__Expected behavior:__
Database should back up normally. All databases not starting with an underscore character back up without any issues.

__Actual behavior:__
Influxdb fails to back up databases starting with an underscore character.

__Additional info:__
Relevant logs:

```
2017/07/17 02:24:13 backing up db=_TEST since 0001-01-01 00:00:00 +0000 UTC
2017/07/17 02:24:13 backing up metastore to /path/to/backup
2017/07/17 02:24:14 backing up db=_TEST rp=autogen shard=294 to /path/to/backup since 0001-01-01 00:00:00 +0000 UTC
...
2017/07/17 02:24:14 Download shard 10 failed copy backup to file: err=<nil>, n=0.  Retrying (0)...
2017/07/17 02:24:15 Download shard 10 failed copy backup to file: err=<nil>, n=0.  Retrying (1)...
...
2017/07/17 02:24:25 backup failed: copy backup to file: err=<nil>, n=0
backup: copy backup to file: err=<nil>, n=0
```

**Comment by steverweber** [comment]
related.
https://github.com/influxdata/influxdb/issues/7642

**Comment by liketic** [comment]
Hi @e-dard Is this still an issue worth to contribute? Thanks!
