### ISSUE TITLE
Drop/delete measurements with specified tag keys, not tag values

### ISSUE THREAD

**Issue by Punkoivan** [influxdata/influxdb#8604]
### Feature Request

Due to problems with network our data have been corrupted - [some issue with telegraf](https://community.influxdata.com/t/influxdb-corrupted-measurements-created/459)
And we have a lot of these corrupted measurements in influxdb, for example:
```
diqk
diqkio
disi
disiio
disk
diskim
diskio
diskio.host=hostname.com
diskio.host=hostname.com
dksk
dkskio
```
and if execute 
`show series`
also a lot of corrupted data, one series as example:
`xml,hostnamg=hostname.com,jost=hostname.com`
As you can see there are **"hostnamg"** and **"jost"** tag keys instead of **hostname** and **host** respectively.
and in my case I have ~2k of bogus series (impossible to clean up manually)
__system info:__
```
[username@hostname ~]$ influx --version
InfluxDB shell version: 1.2.4
[username@hostname ~]$ cat /etc/redhat-release
CentOS Linux release 7.0.1406 (Core)
```

__Proposal:__ 
Admin should be able to run something like this:
`drop series with tag keys = "tag_key"`
Even w/o regexp support it will be great.

__Current behavior:__ 
Currently we have instrument to dropping series only by tag _value_, not _keys_
`DROP SERIES FROM <measurement_name[,measurement_name]> WHERE <tag_key>='<tag_value>'`

__Use case:__ 
It's really useful when we need to clean up corrupted/old/wrong from the DB

If I can do this with existing instrument (CLI commands) please point me to the docs, because I didn't find in official docs.

Thanks,

Ivan Pun'ko

**Comment by mark-rushakoff** [comment]
I'll leave this issue open as a feature request, but one workaround is to use tag key not equal to empty string:

```
> insert m,host=a n=1i
> insert m,host=b n=1i
> insert m,jost=abc n=5i
> insert m,hhost=def n=5i
> show series
key
m,hhost=def
m,host=a
m,host=b
m,jost=abc

> drop series from m where jost != ''
> show series
key
m,hhost=def
m,host=a
m,host=b

> drop series from m where hhost != ''
> show series
key
m,host=a
m,host=b
```

**Comment by Punkoivan** [comment]
Thanks, @mark-rushakoff for workaround and  hope that we can see this feature in some of the next releases, if someone else interesting in.

Ivan

**Comment by Punkoivan** [comment]
Hello @dali20022 , I believe no.
@mark-rushakoff , is there any plan for this?

**Comment by mark-rushakoff** [comment]
I'm not aware of any immediate plans. Possibly this is something we're addressing with Flux for 2.0.

Ping @timhallinflux?

**Comment by dali20022** [comment]
After upgrade to version 1.7 in sandbox environment the problem is fixed 
we waiting to confirm that in production
