### ISSUE TITLE
math parser error

### ISSUE THREAD

**Issue by howardtopher** [influxdata/influxdb#8605]
### Bug report

__System info:__
CentOS 6.9 x64
InfluxDB 1.2.4 (from yum repository)

__Steps to reproduce:__

1. query:
```
select degreesCelsius*9/5+32 from "temp-sensor-01"
```

__Expected behavior:__ 
Expected that the calculation would succeed

__Actual behavior:__
Parsing error:
```
ERR: error parsing query: found +32, expected FROM at line 1, char 26
```

__Additional info:__
After asking about this on the Influx user forums, it was noted that adding a space between the + and 32 fixed this issue.  I tried that out and it does in fact fix the issue.

**Comment by jsternberg** [comment]
Looks like this will be fixed in 1.3 with #8174. Can you try this out and if it doesn't work, please comment on the issue and I'll reopen to look at it again. Thanks.
