### ISSUE TITLE
Drop database freezes while index compactions running

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#8614]
1. With `tsi1` enabled, write a bunch of data with many unique series into database `foo`
2. Run `drop database foo` while TSI compactions are still running

The drop database command looks like it freezes.

**Comment by jwilder** [comment]
I have also seen this when a large TSM compactions is running.  From some stack traces, the `drop database` statement gets blocked waiting for the TSM compactions to be interrupted.  TSM compactions are currently only interruptible when a new TSM file is finished writing which could take a while if it needs to write out a 2GB file first.  We would need to push the interrupt further down into the actual compaction process to allow it to exit faster.

My guess is that TSI compactions may have the same issue.

**Comment by e-dard** [comment]
Should be fixed via #8629
