### ISSUE TITLE
Missing data about continuous query

### ISSUE THREAD

**Issue by ghost** [influxdata/influxdb#8625]
I use telegraf for collecting apache's logs via logparse plugin. I want to use CQ to aggregate metrics by status code. So I create some CQs as follow:

```
CREATE CONTINUOUS QUERY "access_log_count_all" ON "telegraf" BEGIN SELECT COUNT("resp_time") as count_xxx INTO "access_log_count" FROM "apache_access_log" GROUP BY time(1m), service fill(0) END
```

```
CREATE CONTINUOUS QUERY "access_log_count_2xx" ON "telegraf" BEGIN SELECT COUNT("resp_time") as count_2xx INTO "access_log_count" FROM "apache_access_log" WHERE resp_code =~ /^2/ GROUP BY time(1m), service fill(0) END
```

```
CREATE CONTINUOUS QUERY "access_log_count_4xx" ON "telegraf" BEGIN SELECT COUNT("resp_time") as count_4xx INTO "access_log_count" FROM "apache_access_log" WHERE resp_code =~ /^4/ GROUP BY time(1m), service fill(0) END
```

I found an issue is that the count_2xx > count_all, It's so weird.

![8952d5ea-e0ba-4478-9f9c-6a2bcbbe228a](https://user-images.githubusercontent.com/30432058/28563568-eea4528a-7158-11e7-975b-a452b10f2f25.png)

**Comment by pootzko** [comment]
SO what exactly is the issue here?

**Comment by brainsea** [comment]
resp_code.2xx and resp_code.4xx is extracted from apache_access_log with a where condition. This means that resp_code.all should have the most number if points.

**Comment by russorat** [comment]
I'm going to close this issue as it hasn't been updated since 2017. If this issue is still happening, please open an new issue and  post the relevant details. Thanks!
