### ISSUE TITLE
Influxdb is crashing multiple times with a panic error

### ISSUE THREAD

**Issue by singhimayank** [influxdata/influxdb#8632]
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 223101 [running]:
panic(0xa5e100, 0xc86e7c8420)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
sync.(*WaitGroup).Wait(0xc82054c9c0)
	/usr/local/go/src/sync/waitgroup.go:129 +0x114
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).SetCompactionsEnabled(0xc82054c9a0, 0xa28900)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:188 +0x2ef
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).DeleteSeriesRange(0xc82054c9a0, 0xc85d1b29d0, 0x1, 0x1, 0x8000000000000001, 0x14d4a47ebd429cb8, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:627 +0x78
github.com/influxdata/influxdb/tsdb.(*Shard).DeleteSeriesRange(0xc820568c80, 0xc85d1b29d0, 0x1, 0x1, 0x8000000000000001, 0x14d4a47ebd429cb8, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:417 +0xd2
github.com/influxdata/influxdb/tsdb.(*Store).deleteSeries.func2(0xc820568c80, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:752 +0x111
github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1(0xc85ffcdb30, 0xc86ddeea80, 0xc820568c80)
	/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:537 +0x38
created by github.com/influxdata/influxdb/tsdb.(*Store).walkShards
	/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:543 +0xef

**Comment by singhimayank** [comment]
@nathanielc can you please check and let me know what can be done for this issue.

**Comment by e-dard** [comment]
@singhimayank hi, can you please provide the version of Influx you're using? Is it `1.3.1`?

Also, if you have any more information about operations leading up to the panic that would be great. Ideally an InfluxDB log including the stacktrace from the panic would help.

Thanks!

**Comment by e-dard** [comment]
@singhimayank based on line numbers in your stacktrace it looks like you might be running `v1.3.0` or earlier. The latest release is `v1.3.1` and it contains some fixes around compactions, which appears to be where your issues are. Can you update and then report back if it resolves things for you?

**Comment by singhimayank** [comment]
using influxdb 1.0.2 version.

**Comment by jwilder** [comment]
This was fixed as part of https://github.com/influxdata/influxdb/pull/7165 in 1.1.
