### ISSUE TITLE
high default on max-values-per-tag considered harmful

### ISSUE THREAD

**Issue by matti** [influxdata/influxdb#8634]
https://docs.influxdata.com/influxdb/v1.3/administration/config/#max-values-per-tag-100000

I kind of understand why this has been limited, but having this high limit causes users to learn about this limit at potentially very late stage..

**Comment by e-dard** [comment]
Hi @matti,

We try and keep GitHub Issues for actionable bug reports or feature requests. 
Certainly consider creating a post on the [Community site](https://community.influxdata.com) though, where it can be discussed, and if necessary, changes proposed for a future default setting.

Thanks.
