### ISSUE TITLE
influx_inspect export failes with "no such file or directory"

### ISSUE THREAD

**Issue by tbe** [influxdata/influxdb#8638]
### Bug report

__System info:__ 
- InfluxDB 1.3.1
- Debian Jessie

__Steps to reproduce:__

1. run `influx_inspect export`

__Expected behavior:__
The data is completely exported according to the given command line options

__Actual behavior:__
The export fails with
`writing out tsm file data for telegraf/autogen...export: open /space/data/influxdb/data/telegraf/autogen/32/000001076-000000002.tsm: no such file or directory`
or
`writing out wal file data for telegraf/autogen...export: open /space/data/influxdb/wal/telegraf/autogen/2/_05698.wal: no such file or directory`

**Comment by dgnorton** [comment]
@tbe do you also see `WARNING: detected deletes` in the log?

**Comment by ambikasam** [comment]
This issue is till happening.
Tho' files exists it says not file exists.

export: lstat ~/influxdb/data: no such file or directory

**Comment by ambikasam** [comment]
The way it was resolved is not to give the ubuntu's absolute path - in this case ~/influxdb/data but the influxdb's path i.e., "/var/lib/influxdb/data" (that it he mounted path in the container, i guess). But, this path when checked on ubuntu, you will not find. Leaving this note here, so if anyone comes like me with limited knowledge comes across this ticket, it will help them.

**Comment by riteshja88** [comment]
Below command worked for me:
```
influx_inspect export -datadir /var/lib/influxdb/data -waldir /var/lib/influxdb/wal -out ./export -compress
```
