### ISSUE TITLE
Proposal: shorten syntax for querying many attribute or tag values

### ISSUE THREAD

**Issue by natejgardner** [influxdata/influxdb#8643]
__Current behavior:__

Currently, the only way to query a large number of tag values or attributes is:

```
select * from blah
where itemNo = "1234" 
or itemNo = "5678" 
or itemNo = "9012" 
or itemNo = "3456"
```
etc.
__Desired behavior:__

I would prefer to query with the following syntax or similar:

```
select * from blah where itemNo in ["1234","5678","9012","3456"]
```

__Use case:__ 

When I have to query 12,000 or more of these numbers from an application and I'm building up these queries on the client side, I don't want to transmit `"itemNo"` over and over. Even though it's compressed out, it's still a big performance hit, not to mention difficult to read and modify. The improved syntax would allow me to directly take a list and build the query.

**Comment by jwilder** [comment]
You can use a regex to accomplish the same thing:

```
select * from blah where itemNo =~ /^1234|5678|9012|3456$/
```

If the regex matches the form `/^X|Y|Z$/` it gets optimized to look up the values in the index directly as opposed to scanning with the regex.

**Comment by natejgardner** [comment]
This really shortens the query (and I'm so glad to learn arbitrary regex can be passed in), but another benefit of the array syntax (not to mention its similarity to standard SQL) is the ability to pass in a standard data type. From my client side app it'd look like this:
```
`select stuff from measurement
where time >= ${this.startDate}
and itemNo in ${this.selectedItemsArray}
`
```

Otherwise, I'd have to write a special function to generate the regex string, which is nearly as bad as generating `and (itemNo = 'foo' or itemNo = 'bar' or itemNo = ...)`. Today I wrote a typescript method that took in an array of item numbers and converted it to the above syntax, then appended it to the end of my query string. It took a while to test and get working properly, even in this relatively simple case.

Generally when interfacing with the database from a webapp, It's very helpful to be able to use standard data types wherever possible to minimize db-related code and allow development time to be more focused on business logic.
