### ISSUE TITLE
Influx 'drop series' only removes data not the series

### ISSUE THREAD

**Issue by ABarnett99** [influxdata/influxdb#8649]
Previously I have been able to drop a series from influx and this would remove all the data points plus the series itself. Now I find that the data points are removed, but the series is not, i.e.....

     > show series where fs = 'memuser'
     key
     ---
     nfs,fs=memuser,host=hfs02,type=capacity

     > drop series where fs = 'memuser'

     > show series where fs = 'memuser'
     key
     ---
     nfs,fs=memuser,host=hfs02,type=capacity

This function seems to work properly on my other influx servers running influxdb 1.1.0

OS: CentOS 7.2
Influxdb version: 1.1.0 (I have also upgraded to 1.3.1-1 but with the same results)

Could this be a bug, or am I missing something silly?

**Comment by jwilder** [comment]
@ABarnett99 If you restart does the series disappear?

**Comment by ABarnett99** [comment]
I have restarted the influx service several times. I also rebooted the server this morning. Unfortunately I am still unable to remove the series.

**Comment by petrsmrcka** [comment]
same thing happened to me, I'm not able to delete data from a measurement by any approach - delete from <measurement> nor drop series from <measurement> doesn't work - data points can be added  but when I try to delete all of them or by specifying tag value (or time interval with DELETE command) nothing happens, logs are clear 

any idea what is wrong? 

I experienced this issue with server version 0.13 and after several attempts to fix it I upgraded to 1.3.2 - first I kept original data, then I created new one a restored databases from previous backups using 'influxd  backup|restore' commands

**Comment by jwilder** [comment]
There were two recent fixes for delete and drop measurement fixed #8701 and #8579.  I have not been able to reproduce any issue w/ `drop series` though.

**Comment by petrsmrcka** [comment]
maybe I'm experiencing different bug - I\m just not able get rid of old data from measurement "sunlist" by any approach
I tried

1. 
```
> select * from "sunlist" 
name: sunlist
time                SourceId           Status      reason                                                                                                                         value
----                --------           ------      ------                                                                                                                         -----
1479131553000000000 B02_eds26_1_RED    Integratori success OCR test, StateInfo- History - B02_eds26_1_RED_UPS                                                                     1
1479131553000000000 M24_eds53_2_RED    Ok Dohled   -
```

2.` delete from sunlist`

3.`drop series from sunlist`

4.`drop measurement sunlist`
and data are still there

5. 
```
>select * from "sunlist" 
name: sunlist
time                SourceId           Status      reason                                                                                                                         value
----                --------           ------      ------                                                                                                                         -----
1479131553000000000 B02_eds26_1_RED    Integratori success OCR test, StateInfo- History - B02_eds26_1_RED_UPS                                                                     1
1479131553000000000 M24_eds53_2_RED    Ok Dohled   -
```

I tried upgrading to nightly build 1.4.0~n201708170800-0 - same behavior.

**Comment by petrsmrcka** [comment]
I found workaround how to get the measurement/series working again.
I duplicated complete database - `CREATE DATABASE mydb2`, copyied all data by `use mydb; SELECT * INTO mydb2..:MEASUREMENT FROM /.*/ GROUP BY *` , dropped 'broken' database by 'DROP DATABASE mydb', created new one wiht the same name and copied data back by `use mydb2, SELECT * INTO mydb..:MEASUREMENT FROM /.*/ GROUP BY *`

now I can remove single points from measurement

**Comment by e-dard** [comment]
This should be fixed.
