### ISSUE TITLE
Influxdb error:post http://xxxx:8086/write?consistency=xxxx: dial tcp xxx:8086: connect:cannot assign requested address

### ISSUE THREAD

**Issue by shanquanqiang** [influxdata/influxdb#8653]
Influxdb error:post http://xxxx:8086/write?consistency=xxxx: dial tcp xxx:8086: connect:cannot assign requested address
how to fix this problem

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.
