### ISSUE TITLE
Identical continuous queries not running on multiple databases

### ISSUE THREAD

**Issue by mahammer** [influxdata/influxdb#8654]
### Bug report

__System info:__
Ubuntu Server 16.04.2 LTS, GNU/Linux 4.4.0-79-generic x86_64
package influxdb 0.10.0+dfsg1-1

__Steps to reproduce:__
I have multiple DBs all of the same type on different VPS. I have a "create script" where I replace {DATABASE} with the name I need and it does:
`create database "{DATABASE}"`
`create retention policy "1h" on "{DATABASE}" duration 1h replication 1 default`
`create retention policy "2d" on "{DATABASE}" duration 2d replication 1`
`create retention policy "4w" on "{DATABASE}" duration 4w replication 1`
`drop retention policy "autogen" ON "{DATABASE}"`
`drop retention policy "default" ON "{DATABASE}"`

After that it creates identical continuous queries to downsample data into the different retentions. Consolidate 15m from "1h" into "2d" and consolidate 2h from "2d" into "4w".

On the VPS where there is only a single database everything works flawlessly.
Now I have one VPS where I have three databases as they don't receive data with such a high frequency.
However only the one I initially created has data in all 3 retentions.
The other two receive data allright into "1h" but the other two retentions remain empty, thus I suspect that the CQ of the other two databases are not running.

I checked `/var/log/influxdb` but it's empty.

__Expected behavior:__ I expcted all CQs to run and the two downsampling retentions to have data.

__Actual behavior:__ Only the CQs of the first database I created seems to have run as the downsampling retentions of all databases but the first one have no data.

**Comment by rbetts** [comment]
If you are reporting this against 0.10, we are unlikely to investigate. That is a very old version. Can you move forward to a more recent version?
