### ISSUE TITLE
How to customize measurement  name with backreferencing

### ISSUE THREAD

**Issue by shanquanqiang** [influxdata/influxdb#8662]
CREATE CONTINUOUS QUERY "cq_basic_br" ON "transportation"
BEGIN
  SELECT mean(*) INTO "downsampled_transportation"."autogen".:MEASUREMENT FROM /.*/ GROUP BY time(30m),*
END

how to customize measurement  name in this cq

**Comment by jrbury** [comment]
The INTO clause specifies the destination measurement name. So if you wanted to downsample everything in the source measurement `transportation` to `downsampled_transportation` you would do

```
SELECT mean() INTO "databasename"."retentionpolicy"."downsampled_transportation" FROM "databasename"."retentionpolicy"."transportation" GROUP BY time(30m),*
```

**Comment by shanquanqiang** [comment]
If there is only one measurement ,it's ok,and i know how to write the CQ,but i want to downsample everything in the source database which has thousands measurements into  the destination database ,and i have to write thousands CQs.

:MEASUREMENT means destination measurements have the same name as the source measurements,and i want destination measurements name have the same suffix compare to the source measurements name

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.
