### ISSUE TITLE
Ensure all appropriate unit tests and benchmarks run on both indexes

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#8663]
Since the in-memory index isn't going anywhere for at least a release cycle or two, we should ensure that all relevant unit tests run on both the `inmem` and `tsi1` index.

Relevant packages/types to test both indexes with would include:

 - `tests`
 - `tsdb.Store`
 - `tsdb.Shard`

**Comment by jwilder** [comment]
I added TSI builder for circle in https://github.com/influxdata/influxdb/pull/8617

**Comment by e-dard** [comment]
Completed via #8685
