### ISSUE TITLE
bad data returned by SELECT query on time series

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#8666]
### Directions
System info: Influxdb 1.3.2, CentOS 6.6
Installation: Backend for Grafana 4.4, fed by collectd 5.5.3

In Grafana, I have a query something like this:

SELECT non_negative_derivative(sum("value"), 1m) FROM "A" WHERE "host" =~ /^$host$/ AND "instance" = 'X' AND "type" = 'Y' AND "type_instance" =~ /^$Z$/ AND time > now() - 6h GROUP BY time(2m), "type_instance"

And the data comes back like this, with really large spikes in it:

1502100120000, 1823
1502100240000, 1707
1502100360000, 1687
1502100480000, 1745
1502100720000, 15916461.5
1502100840000, 1603

Running the query with a narrower interval, I see this:

SELECT non_negative_derivative(sum("value"), 1m) FROM "A" WHERE "host" =~ /^$host$/ AND "instance" = 'X' AND "type" = 'Y' AND "type_instance" =~ /^$Z$/ AND time > now() - 4h AND time < now() - 3h GROUP BY time(1m), "type_instance"

1502100120000, 921
1502100180000, 933
1502100240000, 829
1502100300000, 823
1502100360000, 862
1502100420000, 827
1502100480000, 899
1502100540000, 865
1502100660000, 840
1502100720000, 887
1502100780000, 773
1502100840000, 798

**Comment by phemmer** [comment]
You have a gap in your data:
```
1502100480000 = Mon Aug  7 06:08:00 EDT 2017
1502100540000 = Mon Aug  7 06:09:00 EDT 2017
1502100660000 = Mon Aug  7 06:11:00 EDT 2017
1502100720000 = Mon Aug  7 06:12:00 EDT 2017
```

You're using the `derivative` transformation, which calculates based on elapsed time. Meaning inconsistent time will screw it up.

**Comment by jsternberg** [comment]
I think this question would be better for the community website. If it turns out to be a bug, I can reopen it here if you comment on the issue. I think phemmer is right that this is due to a gap in the data, but the fact that your second query doesn't have that gap feels weird.

The community website is at https://community.influxdata.com.
