### ISSUE TITLE
Consider switching WTFPL dependency

### ISSUE THREAD

**Issue by caniszczyk** [influxdata/influxdb#8668]
It would be great if you can use another toml library since WTFPL is not a OSI approve license which can cause issues with adoption:  https://github.com/chanezon/toml#about-this-fork

> This project is a fork of https://github.com/BurntSushi/toml relicensed under the Apache 2 license, for use in containerd. The original project uses the WTFPL license, which is not OSI approved. When giving containerd to CNCF we need an OSI approved license. BurntSushi won't change the license on his project. Since the WTFPL license lets you relicense a project The WTFPL lets you relicense the work under any other license. I will maintain a fork of the BurntSushi/toml project with only the license file and the README changed.

We recommend switching to this fork: https://github.com/chanezon/toml

**Comment by pauldix** [comment]
@caniszczyk actually it looks like it was relicensed to MIT: https://github.com/BurntSushi/toml/pull/184/files

So #8734 should resolve the issue?
