### ISSUE TITLE
No results when adding two aggregates using group by time, fill none, and order descending

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#8672]
### Bug report

__System info:__ InfluxDB 1.3.x and older

__Steps to reproduce:__

1. Insert points into two fields within the database with some points having a value for both fields and some only having one.
2. Use a query with group by time, fill none, and order by descending.

Example code:

```go
package main

import (
    "fmt"
    "math/rand"
    "time"

    influxdb "github.com/influxdata/influxdb-client"
)

func main() {
    client := influxdb.Client{}
    if err := client.Execute("CREATE DATABASE db1"); err != nil {
        panic(err)
    }

    w := client.Writer()
    w.Database = "db1"
    writer := influxdb.NewBufferedWriter(w)

    start, _ := time.Parse(time.RFC3339, "2017-07-11T00:00:00Z")
    end := start.Add(time.Hour)
    for ; start.Before(end); start = start.Add(time.Minute) {
        fields := make(map[string]interface{}, 3)
        for i := 1; i <= 3; i++ {
            if rand.Intn(100) >= 50 {
                fields[fmt.Sprintf("v%d", i)] = rand.Intn(101)
            }
        }
        pt := influxdb.Point{
            Name:   "cpu",
            Fields: fields,
            Time:   start,
        }
        pt.WriteTo(writer)
    }
    writer.Flush()
}
```

The query used:

```
> select mean(v1) + mean(v2) from cpu where time >= '2017-07-11T00:00:00Z' and time < '2017-07-11T01:00:00Z' group by time(1m) fill(none) order by desc
```

__Expected behavior:__ It outputs what `ORDER BY ASC` does, but backwards.

__Actual behavior:__ No output.

__Additional info:__ This has likely existed for awhile. I think it should be in all previous versions. It's not a common query which is likely why it has never been encountered. The iterator that matches the outputs from aggregate iterators only happens when you use `fill(none)`.

**Comment by desa** [comment]
@jsternberg Whats the exact query that shows the issue?

**Comment by jsternberg** [comment]
I updated the comment above with the query I used.
