### ISSUE TITLE
how to customize all measurements name when use a function with a wildcard (*) and INTO query’s backreferencing syntax to automatically downsample data from all measurements and numerical fields in a database.

### ISSUE THREAD

**Issue by shanquanqiang** [influxdata/influxdb#8684]
CREATE CONTINUOUS QUERY "cq_basic_br" ON "transportation"
BEGIN
  SELECT mean(*) INTO "downsampled_transportation"."autogen".‘$1_sss’ FROM /.*/ GROUP BY time(30m),*
END

I want to customize all measurements name  ,maybe there is some way like that instand of :MEASUREMENT  ?

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.
