### ISSUE TITLE
8083 port not working

### ISSUE THREAD

**Issue by allenbunny** [influxdata/influxdb#8687]
8083 works fine for quit a long time.
but today, I found the admin interface not working...8083

restart influx serveral times, not working

how to start up the admin interface manually?

```
[root@jsi-dell10 influxdb]# service influxdb start
Starting influxdb...
influxdb process was started [ OK ]
[root@dell10 ~]# netstat -anp | grep LISTEN|grep 8083
[root@dell10 ~]# netstat -anp | grep LISTEN|grep 8086
tcp        0      0 :::8086                     :::*                        LISTEN      684575/influxd      
[root@dell10 influxdb]# influx
Connected to http://localhost:8086 version 1.3.2
InfluxDB shell version: 1.3.2


```

**Comment by pskuza** [comment]
It was removed in 1.3.0

https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#v130-2017-06-21

**Comment by JodeZer** [comment]
Was it removed due to security? Or some other reasons?

**Comment by jaapz** [comment]
They have a different product (Chronograf) which was duplicating the admin interface's functionality.
