### ISSUE TITLE
Restore InfluxDB using only TSM file

### ISSUE THREAD

**Issue by MayukhSobo** [influxdata/influxdb#8688]
Hello, 

   I made a blunder. I tried to restore my Infuxdb from another server into my AWS server without taking a backup and my old data got deleted. Now when I am looking into the /data/autogen directory I am able to see all the tsm files. But some how that database is not showing up in the InfluxDB. Is there any way to restore all the data from TSM file?

**Comment by MayukhSobo** [comment]
This is a problem that some of the influxDB support people also didn't have..at least I could not find. The point is that if we can restore the database if the meta files are messed up. Because cross system backup and restore only merges the tsm files but replaces the meta files. Now if your meta files are messed up, you can't get data even if you have all your TSM files intact. But there is a solution

```sh
influx_inspect export -database dbname -datadir path -waldir path -out exportfile.txt
influx -import -path=exportfile.txt
```

**Comment by phelicksen** [comment]
@MayukhSobo Thanks, this saved me!

**Comment by govsco** [comment]
Thanks a lot for this... with this i can recover my lost databases from my TSM files !!...

**Comment by niyautho** [comment]
MY Raspberry Pi SDcard was corrupted and the Pi was no longer bootable, but I was able to grasp the data from the SDcard from the influx folder to apply @MayukhSobo recommendation above. 
Success: 
```
2021/01/18 20:15:58 Processed 15500000 lines.  Time elapsed: 10m13.376456367s.  Points per second (PPS): 25269
2021/01/18 20:16:05 Processed 1 commands
2021/01/18 20:16:05 Processed 15583993 inserts
2021/01/18 20:16:05 Failed 0 inserts
```
🆒 stuff!

**Comment by xandlsoft** [comment]
> This is a problem that some of the influxDB support people also didn't have..at least I could not find. The point is that if we can restore the database if the meta files are messed up. Because cross system backup and restore only merges the tsm files but replaces the meta files. Now if your meta files are messed up, you can't get data even if you have all your TSM files intact. But there is a solution
> 
> ```shell
> influx_inspect export -database dbname -datadir path -waldir path -out exportfile.txt
> influx -import -path=exportfile.txt
> ```

Is it possible without a "waldir"?
