### ISSUE TITLE
[Feature Request] http receiver for collectd

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#8692]
The collectd metric receiver is UDP. By design this means that metrics can be lost either on the network or locally on the host. The unfortunate part of this is that not all of influxdb's functions work well when data goes missing (i.e. due to lost packets.)

To provide better reliability it would be fantastic if influxdb could act as a receiver for the "write_http" plugin in collectd.

**Comment by dgnorton** [comment]
@e-dard noticed you removed the `feature request` tag. Does this functionality exist already?

**Comment by e-dard** [comment]
Must have been a fat finger error on my part @dgnorton
