### ISSUE TITLE
Drop Series Cause Write Fail/Write Timeouts/High Memory Usage

### ISSUE THREAD

**Issue by danyli78** [influxdata/influxdb#8697]
When dropping series, we see high memory usage causing write fail/timeouts. If drop series across the entire database, influxdb would crash. when restarting influxdb due to the crash, load are still high (hoovering 7-9), a reboot is then required.

influxdb version: v1.3.2
os: redhat 7.3
spec: m4.2xlarge (8 core / 32GB)

screenshot from influxdb "_internal" stats:

![image](https://user-images.githubusercontent.com/8359284/29285922-0ece2680-80e5-11e7-9a63-34284e6c5bd0.png)

![image](https://user-images.githubusercontent.com/8359284/29286033-741052a2-80e5-11e7-9c05-f6bc33de4485.png)

![image](https://user-images.githubusercontent.com/8359284/29286059-84c37728-80e5-11e7-8e20-72acc6f3c0ad.png)

**Comment by jwilder** [comment]
Can you run the following when memory usage is high and attach the output to the issue?

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"

curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
```

**Comment by pingliu** [comment]
@jwilder  I also have this problem.
![image](https://user-images.githubusercontent.com/6415493/30103623-c7fa6afe-9325-11e7-933a-0733c431f30e.png)
![image](https://user-images.githubusercontent.com/6415493/30103643-d5b6cc1e-9325-11e7-91e4-4887d2ee343b.png)

write-timeout = "2m" also write timeout when influxdb drop series.

**Comment by jwilder** [comment]
#8801 should fix this.
