### ISSUE TITLE
subquery doesn't support order by

### ISSUE THREAD

**Issue by jasper-zhang** [influxdata/influxdb#8699]
InfluxDB version: 1.3.1  

When I run the subquery with `order by`, it doesn't work:

```
> select * from cpu order by time desc
name: cpu
time                host    region  value
----                ----    ------  -----
1502764231978282504 serverA us_west 0.6
1502763228833832379 serverA us_west 0.61
1502763224144379689 serverA us_west 0.64
> 
> select * from (select * from cpu) order by time desc
name: cpu
time                host    region  value
----                ----    ------  -----
1502763224144379689 serverA us_west 0.64
1502763228833832379 serverA us_west 0.61
1502764231978282504 serverA us_west 0.6
```

**Comment by jsternberg** [comment]
The order of the query is inherited by any subqueries. While there is no mechanic in place to catch changing the ordering between a subquery and the query itself, it's not tested and unlikely to do anything useful and should probably be an error to switch the order by within a subquery.

This could be clarified in the documentation. Do you have a specific use case in mind where you needed to specify the ordering in a separate direction?

**Comment by jasper-zhang** [comment]
You are right, I really don't have this use case. I just find this coincidentally. Maybe InfluxDB return some error or nothing, instead of the result that is not as user expected.
