### ISSUE TITLE
Influx DB memory leak 

### ISSUE THREAD

**Issue by alok87** [influxdata/influxdb#8718]
**What?**
InfluxDB memory in few days increases from 2GB to 13-14GB. There is some leakage.
We had setup grafana-influxdb-heapster following this document - https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb
Our machine spec:
```
node: m4.xlarge, 4cores 16GB
kubernetes version: 1.6.4
influx version: `image: gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
```

- How can we fix this?

**Comment by e-dard** [comment]
@alok87 can you upgrade to the latest release? We're on `1.3.3`.

**Comment by alok87** [comment]
@e-dard need to ask kuberentes heapster community to bump the version. let me try

**Comment by philios33** [comment]
I'm on version 1.3.5 and have even cleared out my data storage.  I'm still seeing the same memory issues.  Is this issue still ongoing for anybody?

Ah I see 1.3.6 has been released since, will upgrade and test...

**Comment by bltb** [comment]
I also noticed a leak using the latest

https://dl.influxdata.com/influxdb/releases/influxdb_1.3.7_amd64.deb

**Comment by alok87** [comment]
I am not getting memory leak but, this is happening when heapster writes to influx. Not sure how to fix this yet
```{"log":"E1115 14:45:05.485833       1 influxdb.go:186] InfluxDB write failed: {\"error\":\"partial write: max-series-per-database limit exceeded: (1000000) dropped=4929\"}\n","stream":"stderr","time":"2017-11-15T14:45:05.486074258Z"}```
