### ISSUE TITLE
String field with backslash quote results in unable to parse error

### ISSUE THREAD

**Issue by danielnelson** [influxdata/influxdb#8728]
### Bug report

When sending a string field containing a literal `\"`, I receive a unable to parse error if there is also a space in the field.  I believe the line protocol is being escaped correctly, only the double quote character is backslash escaped within the quotes, the other backslashes are literals.

__System info:__

InfluxDB 1.3.3

__Steps to reproduce:__

```
curl -X POST 'http://localhost:8086/write?db=telegraf' --data 'foo bar="\\"howdy doody\\"" 1503364403083465901'
```

__Expected behavior:__

204 No Content

__Actual behavior:__
```
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Request-Id: 5df3f53d-86da-11e7-8005-000000000000
< X-Influxdb-Version: 1.3.3
< Date: Tue, 22 Aug 2017 01:36:49 GMT
< Content-Length: 101
< 
{"error":"unable to parse 'foo bar=\"\\\\\"howdy doody\\\\\"\" 1503364403083465901': bad timestamp"}
```

__Additional info:__

This quoting allows for correct parsing: `foo bar="\\\"howdy doody\\\"" 1503364403083465901`, but is incorrect according to https://docs.influxdata.com/influxdb/v1.3/write_protocols/line_protocol_reference/#special-characters

This is the root cause of https://github.com/influxdata/telegraf/issues/3142

**Comment by jwilder** [comment]
It looks like you are escaping the slash before the quotes.  Try:
```
curl -X POST 'http://localhost:8086/write?db=telegraf' --data 'foo bar="\"howdy doody\"" 1503364403083465902'
```

Or if the first slash is supposed to there, try:
```
curl -X POST 'http://localhost:8086/write?db=telegraf' --data 'foo bar="\\\"howdy doody\"" 1503364403083465901'
```

```
$ influx -database telegraf -execute "select * from foo"
name: foo
time                bar
----                ---
1503364403083465901 \"howdy doody"
1503364403083465902 "howdy doody"
```

**Comment by danielnelson** [comment]
The backslash and quote are both supposed to be there.  I can definitely change Telegraf to escape/unescape backslashes within string fields, but I want to make sure it is correct since this is not what is documented and it needs to work with Kapacitor and the Telegraf read side.

**Comment by jwilder** [comment]
It looks like those docs are incorrect for strings escaping (and have been since 0.9.4).  Backslashes need to be escaped within string fields.  Here are some example tests we have for that case:

https://github.com/influxdata/influxdb/blob/master/models/points_test.go#L1300

This is the commit that added support for backslashes in strings: https://github.com/influxdata/influxdb/commit/6ca7970f017ef69156ac4683087ac5676311ca0d#diff-4fbf62c788a5b69da86ec473a6f13f22

**Comment by gzll** [comment]
https://github.com/influxdata/influxdb-java/issues/372

**Comment by e-dard** [comment]
I'm assuming this is now resolved.

**Comment by danielnelson** [comment]
I think there should be a documentation update to close this.

**Comment by e-dard** [comment]
@danielnelson an issue should be opened on the docs repo to track this.

**Comment by sanchomuzax** [comment]
How can I use whitespace in BASH variable?

Example:

~~~
a="foo,bar=howdy\ doody"
curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary $a' value=1'

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 3c146692-f60d-11e7-ac46-000000000000
X-Influxdb-Version: 1.3.7
Date: Wed, 10 Jan 2018 13:50:36 GMT
Content-Length: 68

{"error":"unable to parse 'foo,bar=howdy\\\u0000': missing fields"}
curl: (6) Could not resolve host: doody value=1; Name or service not known
~~~
