### ISSUE TITLE
1.3.1 Influx DB memory leak? when series number is almost 30000000 

### ISSUE THREAD

**Issue by shanquanqiang** [influxdata/influxdb#8731]
Is series number too much?

**Comment by e-dard** [comment]
@shanquanqiang that's a lot of series for the `inmem` index. Please consider upgrading to `1.3.3` and using the opt-in `tsi1` index. You'll need to change your configuration and start a new database. (Any existing databases would continue to use the `inmem` index.

I'm going to close this issue as it's not really an actionable bug report. You might find the [Community Site](https://community.influxdata.com) helpful.

**Comment by lets00** [comment]
can I migrate series from tsm1 or inmem based to tsi1 index?
