### ISSUE TITLE
Using POST to query data (Documentation bug)

### ISSUE THREAD

**Issue by datamuc** [influxdata/influxdb#8747]
The [documentation](http://docs.influxdata.com/influxdb/v1.3/guides/querying_data/) says:

> perform a query send a `GET` request to the `/query` endpoint, set the URL parameter `db` as the target database, and set the URL parameter `q` as your query. 

With scripted dashboards it happened that some regular expression became quite big and reached the maximum url length limit. I've tried to query with a `POST` request, and it works just fine. So I suggest to update the docs to something like:

> perform a query send either a `GET` or a `POST` request to the `/query` endpoint, set the parameter `db` as the target database, and set the parameter `q` as your query.

**Comment by jsternberg** [comment]
Can you make a PR to the repository at https://github.com/influxdata/docs.influxdata.com or create an issue there? Thanks.

**Comment by aocenas** [comment]
@jsternberg I think similar update should be also done for API reference https://docs.influxdata.com/influxdb/v1.7/tools/api/#query-http-endpoint.
