### ISSUE TITLE
error syncing wal

### ISSUE THREAD

**Issue by been2io** [influxdata/influxdb#8758]
After upgrade version 1.2.2 to 1.3.4, found quiet a lot  responses like {"error":"engine: error syncing wal"}, is this a disk performance bottleneck ? when I set wal-fsync-delay = “5s”,got lots more errors,and then set wal-fsync-delay="1s", less errors occured.

**Comment by jwilder** [comment]
`5s` is too high for `wal-fsync-delay` and will cause the errors you are seeing.  You really should not need to change this setting.   If it is changed, a value of `100ms` or less is more appropriate.
