### ISSUE TITLE
FIRST/ LAST return "interface is nil, not engine.FirstOrLastAggregatorState"

### ISSUE THREAD

**Issue by nicolai86** [influxdata/influxdb#876]
I've a query which looks like this:

```
SELECT FIRST(a), FIRST(b) FROM my_series WHERE time > now() - 7d GROUP BY c, d, time(24h) fill(0);
```

In influxdb 0.7.3 this worked just fine, 0.8.0 returns

```
Internal Error: interface conversion: interface is nil, not engine.FirstOrLastAggregatorState
```

I'm not quite sure why this stopped working - according to the 0.8 docs the functions should work the same still.

Removing `FIRST` makes the query execute again, but it returns different results.

**Comment by pablo-tech** [comment]
this error persist as of today for

select FIRST(PRICE), MIN(PRICE), MAX(PRICE), LAST(PRICE) from "SPX-INDEX-TRADED" group BY time(1h) fill(0) where time > '2015-07-01 00:00:00' AND time < '2015-07-08 23:59:59'

at http://calvinklein-fluxcapacitor-1.c.influxdb.com:8083

**Comment by beckettsean** [comment]
@pablo-tech that server is running version 0.8.2, for which there is no longer ongoing support. As I recommended, try putting the `fill(0)` at the end of the query, but otherwise the solution is to upgrade to 0.9.
