### ISSUE TITLE
Document subquery ordering requirement in changelog

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#8762]
https://github.com/influxdata/influxdb/pull/8754 changed the behavior of subqueries using different `order by` settings from an accepted query to a query returning the error `subqueries must be ordered in the same direction as the query itself`.

One example query demonstrating the issue is: `SELECT value FROM (SELECT value FROM cpu ORDER BY time DESC) ORDER BY time ASC`.

These queries were previously accepted but are now returning an error, so they should be documented as a breaking change for 1.4.0. This type of query is nonsensical, so nobody _should_ be using them, but it's possible someone may be relying on that behavior – hence the need to document it in the changelog.

**Comment by hackertron** [comment]
why the order by ASC and DESC not supported ? . it's needed in some cases
