### ISSUE TITLE
tsi index problem once process is restarted

### ISSUE THREAD

**Issue by micastle** [influxdata/influxdb#8773]
### Bug report
I run 1.3.2 with tsi engine enabled on windows and index is built as expected. but once the process is killed and restarted, it report below failure and write does not success.  the log says:

[I] 2017-08-31T05:58:56Z write failed for shard 2: [shard 2] truncate D:\Data\influxdb\data\kensho\autogen\2\index\L0-00000021.tsl: Access is denied. service=write
[I] 2017-08-31T05:58:56Z write failed for shard 2: [shard 2] truncate D:\Data\influxdb\data\kensho\autogen\2\index\L0-00000021.tsl: Access is denied. service=write

I always run the process with administrator account. and this always happen to me, not sure why.

**Comment by micastle** [comment]
I tried out with latest version 1.3.5, but no luck. the same failure and same logs. I tested it with a new environment, still the same.

**Comment by benbjohnson** [comment]
hmm, it seems odd that you can't access the file if you're running as an administrator. What are the file permissions on the `tsl` files?

**Comment by micastle** [comment]
It is full control with all permissions on the index file. Is it possible the issue is not about permission? and what does truncate mean in this context, maybe the truncate file action has problem on windows somehow?

**Comment by benbjohnson** [comment]
A `truncate()` shrinks or grows a file to a specified size. From this [SO thread][https://stackoverflow.com/questions/25534857/truncating-open-os-file-access-denied) it looks like files may need to be closed before truncating on Windows. However, the only place we truncate in TSI is when opening and not when writing. I can try to add that fix and see if it helps though.

**Comment by micastle** [comment]
Thanks! maybe you can add more detailed logs to show the error code when file error happened, thus we can track what happened if error show up again.
