### ISSUE TITLE
Lots of errors after loading sample data 

### ISSUE THREAD

**Issue by MattHoneycutt** [influxdata/influxdb#8775]
Let me prefix this by saying that what I'm attempting to do may be a Bad Idea or not supported: Running InfluxDB in an Azure Container Instance, persisting data to an Azure File Share. 

### Bug report
__System info:__ 
InfluxDB 1.3.5
Running on Azure via Docker and Azure Container Instances.  

__Steps to reproduce:__

1. Start the container
2. Load in the NOAA sample data via the HTTP API
3. Sit back and wait

__Expected behavior:__ 
No errors?  

__Actual behavior:__ 
Lots of errors started showing up a minute or so later.  Here's what they look like:
[I] 2017-08-31T15:45:35Z error adding new TSM files from snapshot: sync /var/share/data/mydb/autogen/2: invalid argument engine=tsm1
[I] 2017-08-31T15:45:35Z Snapshot for path /var/share/data/mydb/autogen/2 written in 205.634589ms engine=tsm1
[I] 2017-08-31T15:45:35Z error writing snapshot: sync /var/share/data/mydb/autogen/2: invalid argument engine=tsm1
[I] 2017-08-31T15:45:35Z error adding new TSM files from snapshot: sync /var/share/data/mydb/autogen/2: invalid argument engine=tsm1
[I] 2017-08-31T15:45:35Z Snapshot for path /var/share/data/mydb/autogen/2 written in 183.925456ms engine=tsm1
[I] 2017-08-31T15:45:35Z error writing snapshot: sync /var/share/data/mydb/autogen/2: invalid argument engine=tsm1

__Additional info:__ 
The only config I've specified is the data dir via the INFLUXDB_DATA_DIR environment variable.  It is bound to a mounted Azure Storage File Share.   It looks like it is able to write to the share correctly.  I see folders and TSM files in there.  Any suggestions? 

[vars.txt](https://github.com/influxdata/influxdb/files/1267728/vars.txt)
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/1267729/profiles.tar.gz)

**Comment by MattHoneycutt** [comment]
Please let me know if there's any other info I can provide.  I'd love to be able to get this working so that I can document the setup for others.  Thanks!

**Comment by tangoecho4** [comment]
I seem to be getting the same issue.

Debian 9.1, running the influxdb official docker container.

Start with `docker kill $(docker ps -a -q)` and `docker rm $(docker ps -a -q)` everything for sake of sanity.

I have run two instances: one with it's volume located on network share, and the other's volume located locally:
`docker run -d -p 8086:8086 --name influxdb_local -v /mnt/:/var/lib/influxdb influxdb`
and
`docker run -d -p 8087:8086 --name influxdb_remote -v /mnt/projects/Docker/influxdb:/var/lib/influxdb influxdb`

Note that `/mnt/` is local, but `/mnt/projects/Docker/influxdb` is a samba share hosted on another machine.

I then load the NOAA sample data:
`influx -import -path=NOAA_data.txt -precision=s -database=NOAA_water_database`
and
`influx -port 8087 -import -path=NOAA_data.txt -precision=s -database=NOAA_water_database`

...and then I watch the logs and wait...
`docker logs -f influxdb_local`
and
`docker logs -f influxdb_remote`

Both log files start the same, and the loading of the NOAA data runs the same too (at `05/Sep/2017:07:59:40 +0000` for reference). Exactly 10 minutes later they output this:

influxdb_local:
```
[I] 2017-09-05T08:09:39Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/1 written in 20.636846ms engine=tsm1
[I] 2017-09-05T08:09:39Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/3 written in 29.440772ms engine=tsm1
[I] 2017-09-05T08:09:39Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/4 written in 19.043738ms engine=tsm1
[I] 2017-09-05T08:09:39Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/2 written in 30.004635ms engine=tsm1
[I] 2017-09-05T08:09:39Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/5 written in 14.821338ms engine=tsm1
```
influxdb_remote:
```
[I] 2017-09-05T08:09:40Z error adding new TSM files from snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/1: invalid argument engine=tsm1
[I] 2017-09-05T08:09:40Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/1 written in 128.533656ms engine=tsm1
[I] 2017-09-05T08:09:40Z error writing snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/1: invalid argument engine=tsm1
[I] 2017-09-05T08:09:40Z error adding new TSM files from snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/3: invalid argument engine=tsm1
[I] 2017-09-05T08:09:40Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/3 written in 162.812614ms engine=tsm1
[I] 2017-09-05T08:09:40Z error writing snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/3: invalid argument engine=tsm1
[I] 2017-09-05T08:09:40Z error adding new TSM files from snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/2: invalid argument engine=tsm1
[I] 2017-09-05T08:09:40Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/2 written in 164.768609ms engine=tsm1
[I] 2017-09-05T08:09:40Z error writing snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/2: invalid argument engine=tsm1
[I] 2017-09-05T08:09:40Z error adding new TSM files from snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/4: invalid argument engine=tsm1
[I] 2017-09-05T08:09:40Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/4 written in 165.253803ms engine=tsm1
[I] 2017-09-05T08:09:40Z error writing snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/4: invalid argument engine=tsm1
[I] 2017-09-05T08:09:40Z error adding new TSM files from snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/5: invalid argument engine=tsm1
[I] 2017-09-05T08:09:40Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/5 written in 123.762398ms engine=tsm1
[I] 2017-09-05T08:09:40Z error writing snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/5: invalid argument engine=tsm1
```

10 minutes after that, the log for `influx_remote` starts going nuts.
```
[I] 2017-09-05T08:19:51Z error adding new TSM files from snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/1: invalid argument engine=tsm1
[I] 2017-09-05T08:19:51Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/1 written in 115.911881ms engine=tsm1
[I] 2017-09-05T08:19:51Z error writing snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/1: invalid argument engine=tsm1
[I] 2017-09-05T08:19:51Z error adding new TSM files from snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/3: invalid argument engine=tsm1
[I] 2017-09-05T08:19:51Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/3 written in 122.61052ms engine=tsm1
[I] 2017-09-05T08:19:51Z error writing snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/3: invalid argument engine=tsm1
[I] 2017-09-05T08:19:51Z error adding new TSM files from snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/2: invalid argument engine=tsm1
[I] 2017-09-05T08:19:51Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/2 written in 134.581686ms engine=tsm1
[I] 2017-09-05T08:19:51Z error writing snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/2: invalid argument engine=tsm1
[I] 2017-09-05T08:19:51Z error adding new TSM files from snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/4: invalid argument engine=tsm1
[I] 2017-09-05T08:19:51Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/4 written in 111.876917ms engine=tsm1
[I] 2017-09-05T08:19:51Z error writing snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/4: invalid argument engine=tsm1
[I] 2017-09-05T08:19:51Z error adding new TSM files from snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/5: invalid argument engine=tsm1
[I] 2017-09-05T08:19:51Z Snapshot for path /var/lib/influxdb/data/NOAA_water_database/autogen/5 written in 74.071225ms engine=tsm1
[I] 2017-09-05T08:19:51Z error writing snapshot: sync /var/lib/influxdb/data/NOAA_water_database/autogen/5: invalid argument engine=tsm1
```

This repeats **every second** until I killed the container. Meanwhile, `influxdb_local` is doing nothing.

I've included the two log files for your interest.

[influxdb_local_log.txt](https://github.com/influxdata/influxdb/files/1276598/influxdb_local_log.txt)
[influxdb_remote_log.txt](https://github.com/influxdata/influxdb/files/1276599/influxdb_remote_log.txt)



Interestingly, I was getting the same (or a very similar) issue while running influxdb on docker for windows. I suspected that the network share was the issue, as it seems that docker for windows uses samba to share files between the windows host and the VM that runs docker.

**Comment by makhdumi** [comment]
I'm getting this on Windows as well, with `/var/lib/influxdb` mapped locally:

Running this:
`docker run --name influxdb -p 8086:8086 -v %cd%\influxdb:/var/lib/influxdb influxdb `

Started producing the exact same behaviour after about an hour.
I only inserted < 10 points of a test measurement and was reading from Grafana every 5 seconds.

**Comment by StianOvrevage** [comment]
Also getting this. Mapped disk on windows locally. data/_internal/monitor also fills the disk pretty quickly.
