### ISSUE TITLE
Clean shutdown impossible with collectd plugin

### ISSUE THREAD

**Issue by simonvanderveldt** [influxdata/influxdb#8780]
influxdb 1.3.2 on linux

When I start influxd and send a `SIGTERM` to it the following output is shown
```
[I] 2017-09-02T13:02:46Z Listening on UDP: [::]:25826 service=collectd
[I] 2017-09-02T13:02:46Z Listening for signals
[I] 2017-09-02T13:03:38Z Signal received, initializing clean shutdown...
[I] 2017-09-02T13:03:38Z Waiting for clean shutdown...
[I] 2017-09-02T13:03:38Z shutting down monitor system service=monitor
[I] 2017-09-02T13:03:38Z snapshot listener closed service=snapshot
[I] 2017-09-02T13:03:38Z continuous query service terminating service=continuous_querier
[I] 2017-09-02T13:03:38Z collectd ReadFromUDP error: read udp [::]:25826: use of closed network connection service=collectd

[I] 2017-09-02T13:04:08Z time limit reached, initializing hard shutdown
```
I don't think this should happen and influxd should be able to cleanly shutdown with collectd enabled.
Looking through the old/existing issues, this might be similar to #4016

**Comment by jsternberg** [comment]
Does this happen all the time or just occasionally? Also, are you actively writing to the endpoint when you Ctrl+C?

Next time that this happens, can you try sending a SIGQUIT signal to the process before it does a hard shutdown? A SIGQUIT should get it to drop a stacktrace. I have a feeling there's a deadlock in the service shutdown happening somewhere.
