### ISSUE TITLE
Enable programmatic determination of remote Influx server versions

### ISSUE THREAD

**Issue by kmoppel** [influxdata/influxdb#8783]
### Feature Request

__Proposal:__  Adding some command to enable easy/programmatic determination of the Influx version of a remote database.

__Current behavior:__ Currently one can easily determine the version of local binaries with "influx -version" but for remote hosts one needs to go into the CLI (not good for scripting) or parse the response text of "SHOW DIAGNOSTICS" with some regex

__Desired behavior:__ influx -execute "SHOW VERSION"

__Use case:__ All common databases have such features for easier scripting

**Comment by mark-rushakoff** [comment]
Note that you can narrow down the output of show diagnostics with

```
$ influx -execute "show diagnostics for 'system'"
name: system
PID  currentTime                    started                        uptime
---  -----------                    -------                        ------
2499 2017-09-06T19:50:50.570294271Z 2017-09-06T19:32:11.314331889Z 18m39.255962598s
```

All HTTP responses should include an `X-Influxdb-Version` header. One way to extract the version with curl:
```
$ curl -s -i http://localhost:8086/ping | grep 'X-Influxdb-Version' | awk '{print $2}'
1.3.5
```
