### ISSUE TITLE
now() not working in subqueries

### ISSUE THREAD

**Issue by quarantadue** [influxdata/influxdb#8788]
### Bug report

Tested on:
version 1.4.0~n201709050800 on debian

Using standard test data (NOAA_data):

select max(mean) from ( select mean(degrees) from h2o_temperature where time > now() - 740d and time < now() - 730d group by time(1d) )
Gives error:
ERR: invalid operation: time and *influxql.BinaryExpr are not compatible

inner query works fine if alone:
select mean(degrees) from h2o_temperature where time > now() - 740d and time < now() - 730d group by time(1d)
(gives expected result)

And replacing now() with actual date in the nested queries also works fine:
select max(mean) from ( select mean(degrees) from h2o_temperature where time > '2017-09-05' - 740d and time < '2017-09-05' - 730d group by time(1d) )
name: h2o_temperature
(gives expected result)

I have made some more test and the problem really seems related to the presence of now() in the subquery.

**Comment by lpic10** [comment]
Seeing same behavior here. 

Also doing some math does not work anymore, eg:

select "usage_user" / (10 * 10) from "cpu" 
ERR: cannot perform a binary expression on two literals

As the direct operation works
select "usage_user" / 100 from "cpu"
