### ISSUE TITLE
cli can't handle database names with space, http api can

### ISSUE THREAD

**Issue by knan-nrk** [influxdata/influxdb#8789]
### Bug report

__System info:__ 

Connected to http://localhost:8086 version 1.3.4
InfluxDB shell version: 1.3.4
Ubuntu 16.04

__Steps to reproduce:__

1. create database "with space"
2. use "with space"

__Expected behavior:__ 

database "with space" created, ability to use it in cli queries

__Actual behavior:__ 

database "with space" created
> use "with space"
Could not parse database name from "use \"with space\"".

__Additional info:__ 

HTTP api has no problems accepting data for the database, seems to be a pure cli problem. Can create and drop the database "with space" via the cli, just not use/inspect it.

**Comment by joelegasse** [comment]
Fixed by #8845
