### ISSUE TITLE
types.db error does not mention type or sender

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#8798]
__System info:__ Influxdb 1.3.2, CentOS 6.6

__Steps to reproduce:__

1. Configure inflxuxdb to run as collectd server
2. Send collectd data to influxdb
3. Observe influxdb log

__Expected behavior:__ influxdb to log the the host/plugin/instance/type/type-instance
__Actual behavior:__ influxdb just mentions mismatch in types, e.g:

2017/09/07 16:55:07 unable to convert values according to TypesDB: len(args) = 3, want 4

What would be good is to see something like this:

2017/09/07 16:55:07 unable to convert values from server.example.com according to TypesDB entry df_value/sda/gauge: len(args) = 3, want 4

**Comment by yellowpattern** [comment]
This is not a bug in influxdb per se, it is in collectd/go-collectd.

**Comment by yellowpattern** [comment]
diff -u ./go-collectd/network/parse.go ./go/src/collectd.org/network/parse.go
--- ./go-collectd/network/parse.go	2017-09-08 19:32:59.949965463 +1000
+++ ./go/src/collectd.org/network/parse.go	2017-09-08 23:18:41.574964616 +1000
@@ -110,7 +110,7 @@
 				// Returns an error if the number of values is incorrect.
 				v, err := ds.Values(ifValues...)
 				if err != nil {
-					log.Printf("unable to convert values according to TypesDB: %v", err)
+					log.Printf("unable to convert metric %v values %v according to %v in TypesDB: %v", state, ifValues, ds, err)
 					continue
 				}
 				vl.Values = v

**Comment by jsternberg** [comment]
@yellowpattern if you can get that fix put into the collectd.org library, I would be happy to update the dependency.

**Comment by yellowpattern** [comment]
https://github.com/collectd/go-collectd/issues/32

**Comment by dgnorton** [comment]
@yellowpattern looks like `go-collectd` project likes your proposed solution but requested that you make a PR. Are you still planning to get that change merged into their project?

**Comment by russorat** [comment]
closing due to lack of response.
