### ISSUE TITLE
The more aggregated fields, the slower mean()

### ISSUE THREAD

**Issue by makareth** [influxdata/influxdb#8799]
Steps to reproduce:
1. Issue a query calculating mean() aggregation on almost all fields of a a measurement.
For example, the following query completes in ~1 second even though the related lines (those implied by the WHERE clause) are very few (10 lines), as returned by SELECT  * FROM sensors WHERE time > '2017-07-30T23:40:00Z' AND time < '2017-07-30T23:50:00Z' GROUP BY id, customer, user_id :

SELECT mean(powerApparentConsumed1) AS powerApparentConsumed, mean(currentRms1) AS currentRms1, mean(currentRms2) AS currentRms2, mean(currentRms3) AS currentRms3, mean(voltageRms1) AS voltageRms1, mean(voltageRms2) AS voltageRms2, mean(voltageRms3) AS voltageRms3, last(powerApparentBreak) AS powerApparentBreak, last(powerApparentReference) AS powerApparentReference, mean(powerApparentConsumed1) AS powerApparentConsumed1, mean(powerApparentConsumed2) AS powerApparentConsumed2, mean(powerApparentConsumed3) AS powerApparentConsumed3, mean(powerApparentProduced) AS powerApparentProduced, max(powerApparentConsumedMax) AS powerApparentConsumdeMax, max(powerApparentProducedMax) AS powerApparentProducedMax, mean(powerRealLoadCurve) AS powerRealLoadCurve, max(energyActiveConsumedTotal) AS energyActiveConsumedTotal, max(energyActiveProducedTotal) AS energyActiveProducedTotal, max(energyActiveConsumed01) AS energyActiveConsumed01, max(energyActiveConsumed02) AS energyActiveConsumed02, max(energyActiveConsumed03) AS energyActiveConsumed03, max(energyActiveConsumed04) AS energyActiveConsumed04, max(energyActiveConsumed05) AS energyActiveConsumed05, max(energyActiveConsumed06) AS energyActiveConsumed06, max(energyActiveConsumed07) AS energyActiveConsumed07, max(energyActiveConsumed08) AS energyActiveConsumed08, max(energyActiveConsumed09) AS energyActiveConsumed09, max(energyActiveConsumed10) AS energyActiveConsumed10, last(status) AS status, last(priceIndex) AS PriceIndex, last(priceProvider) AS priceProvider, last(priceProviderCalendar) AS priceProviderCalendar, last(message1) AS message1, last(message2) AS message2 FROM sensors WHERE time > '2017-07-30T23:40:00Z' AND time < '2017-07-30T23:50:00Z' GROUP BY id, customer, user_id

2. Tried the same query, but with much less fields, returned almost immediately : 
SELECT  * FROM sensors WHERE time > '2017-07-30T23:40:00Z' AND time < '2017-07-30T23:50:00Z' GROUP BY id, customer, user_id

Expected behavior:
The expected behaviour is to have a much faster aggregation even though multiple fields are added. The cost of aggregating 20+ fields looks like too high to me based on very limited volume. Aggregating 20+ fields on 10 lines in 1 second seems a low performance.

Actual behavior:
The requests are very slow, this makes manual aggregation by 10minutes slots very slow, even for very very limited volumes.

Provided the result of curl -O http://localhost:8086/debug/pprof/profile : 

[profile.tar.gz](https://github.com/influxdata/influxdb/files/1284182/profile.tar.gz)

iostat shows minimal disk usage (around 5%), iowait is 0.1.

Using InfluxDB 1.2.2, Ubuntu 16.04.1 LTS

**Comment by AlexInGitHub** [comment]
+1
