### ISSUE TITLE
[Bug Report] SHOW RETENTION POLICIES returns invalid formated duration

### ISSUE THREAD

**Issue by vicinus** [influxdata/influxdb#8813]
### Bug report

__System info:__ 

* Ubuntu 16.04.3 LTS
* influxdb 1.3.5

__Steps to reproduce:__

```
> ALTER RETENTION POLICY test1 ON test DURATION 336h14ms

> SHOW RETENTION POLICIES ON test

name    duration     shardGroupDuration replicaN default
----    --------     ------------------ -------- -------
test1   336h0m0.014s 24h0m0s            1        true

> ALTER RETENTION POLICY test1 ON test DURATION 336h0m0.014s
ERR: error parsing query: invalid duration at line 1, char 47
```

__Expected behavior:__ The duration returned by SHOW RETENTION POLICIES should be a valid formated duration, which can be used in a ALTER RETENTION POLICY query

__Actual behavior:__ The duration returned by SHOW RETENTION POLICIES is not in all cases a valid formated duration

**Comment by liketic** [comment]
I think I can take this.
