### ISSUE TITLE
influxd.exe [v1.2.0] has a 32GB memory limit on windows server?

### ISSUE THREAD

**Issue by micastle** [influxdata/influxdb#8815]
I am running influxd.exe on windows server and seems it always crash when memory goes up to about 32GB, while I have 64GB RAM on the machine, and now other application running on the server. I double checked that my OS is 64bit version and I didn't apply any limit on the process's memory limit. 

It seems the influxd.exe is built to use only 32GB of memory on windows? I am not sure whether it is influxdb's problem or Go's problem. any suggestion to make it using all available memory?

**Comment by micastle** [comment]
Crashes are mostly like below, I suppose it is caused by OOM?

unexpected fault address 0xf67e6a0
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xf67e6a0 pc=0x4607e1]

goroutine 16243167 [running]:
runtime.throw(0xac0609, 0x5)
	/usr/local/go/src/runtime/panic.go:566 +0x9c fp=0xc148810c48 sp=0xc148810c28
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_windows.go:164 +0x10b fp=0xc148810c78 sp=0xc148810c48
runtime.memmove(0xc11cb38d30, 0xf67e6a0, 0xe)
	/usr/local/go/src/runtime/memmove_amd64.s:164 +0x371 fp=0xc148810c80 sp=0xc148810c78
runtime.slicebytetostring(0x0, 0xf67e6a0, 0xe, 0x56748f2, 0xc091934ba0, 0x41381b)
	/usr/local/go/src/runtime/string.go:94 +0x85 fp=0xc148810cd8 sp=0xc148810c80
github.com/influxdata/influxdb/models.Tags.Map(0xc05ab4b560, 0x5, 0x5, 0xc05ab4b560)
	/root/go/src/github.com/influxdata/influxdb/models/points.go:1755 +0x116 fp=0xc148810dc0 sp=0xc148810cd8

**Comment by e-dard** [comment]
@micastle can you upgrade to the latest version (`1.3.5`) and report back?

**Comment by micastle** [comment]
I did try with 1.3.5 but blocked by another bug, which failed to load index due to access failure. I have reported the issue already.

**Comment by maruta** [comment]
This will be Go's problem.
https://github.com/golang/go/blob/38c561cb2caa8019e44059e2be71c909ceef30a6/src/runtime/malloc.go#L137-L149

**Comment by jsternberg** [comment]
influxdata/docs.influxdata.com#1409
