### ISSUE TITLE
Glyphicons License Clarity

### ISSUE THREAD

**Issue by Msys-tech** [influxdata/influxdb#8816]
We selected influxdb for time series databases for an OEM product. The software is preinstalled on the device and shipped to the customers. 

Please clarify the licensing part of glyphicons. It is not clear where it is used and what license is required. We are using only the influxdb server and influxdb Python client. Can you clarify whether glyphicon licensing policy applies to us? Should we buy any commercial license from glyphicons?

**Comment by jwilder** [comment]
I believe Glyphicons was used in the admin interface https://github.com/influxdata/influxdb/tree/1.2/services/admin/assets/fonts which was deprecated a few releases ago and removed in 1.3.  I think the license list still lists Glyphicons incorrectly.

**Comment by rbetts** [comment]
We'll clean this up and backport the license change to 1.3 for our next (1.3.6) maintenance release.
