### ISSUE TITLE
INFLUXDB_META_CONFIG_PATH does not source properly

### ISSUE THREAD

**Issue by wookdark** [influxdata/influxdb#8817]
INFLUXDB_META_CONFIG_PATH will not source properly since the config parameter in "/usr/lib/systemd/system/influxdb-meta.service" gets hardcoded 

Despite setting the environment variable and adding the same entry to /etc/default/influxdb-meta it does not take the variable 

Changes to be done should be ExecStart=/usr/bin/influxd-meta -config ${INFLUXDB_META_CONFIG_PATH} ${INFLUXD_OPTS} instead /usr/bin/influxd-meta -config /etc/influxdb/influxdb-meta.conf ${INFLUXD_OPTS}

**Comment by e-dard** [comment]
@wookdark looks like you're using an unsupported version of Influx? What version are you running?
