### ISSUE TITLE
Flush due to idle. Flushing 7 series with 7 points... (console spamming this message each 10 secs)

### ISSUE THREAD

**Issue by Colkard** [influxdata/influxdb#8823]
Hello, I have an issue with influx 0.9.5.1 (I'm using this as I saw I need it for using graphios repository). I couldn't find what cause this problem but here is:
I have this kind of spam on my "`influxd`":

> [wal] 2017/09/13 12:44:20 write to index of partition 1 took 8.159513ms
> [wal] 2017/09/13 12:44:30 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:44:30 write to index of partition 1 took 7.158607ms
> [wal] 2017/09/13 12:44:40 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:44:40 write to index of partition 1 took 7.303805ms
> [wal] 2017/09/13 12:44:50 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:44:50 write to index of partition 1 took 10.004981ms
> [wal] 2017/09/13 12:45:00 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:45:00 write to index of partition 1 took 8.505238ms
> [wal] 2017/09/13 12:45:10 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:45:10 write to index of partition 1 took 3.665214ms
> [wal] 2017/09/13 12:45:20 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:45:20 write to index of partition 1 took 3.449958ms
> [wal] 2017/09/13 12:45:29 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:45:29 write to index of partition 1 took 6.447883ms
> [wal] 2017/09/13 12:45:39 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:45:39 write to index of partition 1 took 11.186351ms
> [wal] 2017/09/13 12:45:49 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:45:49 write to index of partition 1 took 6.882614ms
> [wal] 2017/09/13 12:45:59 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:45:59 write to index of partition 1 took 6.263871ms
> [wal] 2017/09/13 12:46:09 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:46:09 write to index of partition 1 took 6.175143ms
> [wal] 2017/09/13 12:46:19 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:46:19 write to index of partition 1 took 3.603478ms
> [wal] 2017/09/13 12:46:29 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:46:29 write to index of partition 1 took 6.73813ms
> [wal] 2017/09/13 12:46:39 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:46:39 write to index of partition 1 took 9.842425ms
> [wal] 2017/09/13 12:46:49 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:46:49 write to index of partition 1 took 8.991898ms
> [wal] 2017/09/13 12:46:59 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:46:59 write to index of partition 1 took 6.668614ms
> [wal] 2017/09/13 12:47:09 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:47:09 write to index of partition 1 took 5.660435ms
> [wal] 2017/09/13 12:47:19 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:47:19 write to index of partition 1 took 9.271004ms
> [wal] 2017/09/13 12:47:29 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:47:29 write to index of partition 1 took 7.227102ms
> [wal] 2017/09/13 12:47:39 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:47:39 write to index of partition 1 took 13.518472ms
> [wal] 2017/09/13 12:47:49 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:47:49 write to index of partition 1 took 7.888707ms
> [wal] 2017/09/13 12:47:59 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:47:59 write to index of partition 1 took 5.666711ms
> [wal] 2017/09/13 12:48:09 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:48:09 write to index of partition 1 took 4.327209ms
> [wal] 2017/09/13 12:48:19 Flush due to idle. Flushing 7 series with 7 points and 407 bytes from partition 1
> [wal] 2017/09/13 12:48:19 write to index of partition 1 took 7.061829ms

I only have 1 DB and is empty. And also I have the __internal.
Thank you for reading!

**Comment by jwilder** [comment]
This is is likely due the `_internal` database where stats are stored periodically.   Also, it looks like you are using `0.9.5` which is no longer supported.  I would recommend upgrading to the latest at some point.
