### ISSUE TITLE
influx -import outputs to stderr on success.

### ISSUE THREAD

**Issue by gambrose** [influxdata/influxdb#8830]
### Bug report

__System info:__ influxdb-1.3.5_windows_amd64

__Steps to reproduce:__

1. curl https://s3.amazonaws.com/noaa.water-database/NOAA_data.txt -o NOAA_data.txt
2. influx -import -path=NOAA_data.txt -precision=s -database=NOAA_water_database

__Expected behavior:__ Outputed to stdout
```
2017/09/14 22:53:20 Processed 1 commands
2017/09/14 22:53:20 Processed 76290 inserts
2017/09/14 22:53:20 Failed 0 inserts
``` 

__Actual behavior:__ Outputed to **stderr**
```
2017/09/14 22:53:20 Processed 1 commands
2017/09/14 22:53:20 Processed 76290 inserts
2017/09/14 22:53:20 Failed 0 inserts
``` 
__Additional info:__ 

Logging to stderr makes PowerShell think the command failed when it didn't

```Powershell
influx -import -path NOAA_data.txt -precision s

influx : 2017/09/14 23:05:10 Processed 1 commands
At line:1 char:1
+ influx -import -path NOAA_data.txt -precision s
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (2017/09/14 23:05:10 Processed 1 commands:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
2017/09/14 23:05:10 Processed 76290 inserts
2017/09/14 23:05:10 Failed 0 inserts
```

**Comment by e-dard** [comment]
@gambrose the importer uses Go's standard `log.Logger`, which by default emits its output to `stderr`.

I think I agree with you that there should be a better separation there. I'll put up a PR to use `stderr` and `stdout` appropriately.

**Comment by gambrose** [comment]
Thanks @e-dard looks good to me. 👍
