### ISSUE TITLE
"list series" has gotten slow.

### ISSUE THREAD

**Issue by Dieterbe** [influxdata/influxdb#884]
`list series /regex/` used to return in 150~300ms for me.
nowadays it's around 480ms.
and `list series` now takes about 860ms. not sure what this used to be, i have some old notes saying 2-3s but those may be outdated.

anyway this probably has something to do with #830: we now sort everytime we request the series list.
i recently upgraded to rc5 so that seems to make sense.

it's important that `list series` and `list series /regex` return speedily
for example graphite-influxdb gets user requests, then needs to figure out which series it needs, for which it executes `list series /regex/` and then queries influxdb for data.  It caches the list outputs, but still with a cold cache (new graph) it can take several seconds before we even know which series to use (because the user supplies multiple expressions)
I can imagine othen monitoring systems being built on top of influx will need similar things.

so how can me make this as fast as it can be?
maybe influx can keep the sorted list of series readily available for querying?

**Comment by pkittenis** [comment]
Will have to agree with @Dieterbe here.

In our testing we are finding InfluxDB query performance where many data points are returned to be entirely CPU limited with the bottleneck seeming to be serialisation as with this issue. 

The API refactor will not change this, InfluxDB will still be returning the same amount of data even after the refactor.

Our use case is querying a days' or more worth of 60 second sampled metric data from Grafana in order to display a dashboard. The data itself is Graphite metric series ingested directly by InfluxDB.

1 days' worth of 60 second resolution data means 86400 (time,value) data point tuples to be returned by InfluxDB *per metric name*. 

On a 4 CPU 2.8Ghz Xeon E312xx InfluxDB takes ~3sec to serialise 86400 data points with almost linear scaling as number of days requested/datapoints returned is increased.

1 day:
```
2015-01-12 17:19:32,004 - DEBUG - Sending request - http://10.206.77.194:80/render?from=01:00_20150106&until=01:00_20150107&target=stats.amers.alpha-us1-cell.rtd-cph-idsi.us1i-cphidsi01.ids.perf.inUpdateRate&format=json
2015-01-12 17:19:35,285 - INFO - Query duration - 3.281203 sec. Datapoints: 86401
2015-01-12 17:19:35,392 - DEBUG - Sending request - http://10.206.77.194:80/render?from=01:00_20150106&until=01:00_20150107&target=<graphite series>&format=json
2015-01-12 17:19:38,690 - INFO - Query duration - 3.298818 sec. Datapoints: 86401
```

2 days:

```
2015-01-12 17:18:15,764 - DEBUG - Sending request - http://10.206.77.194:80/render?from=01:00_20150106&until=01:00_20150108&target=<graphite series>&format=json
2015-01-12 17:18:22,712 - INFO - Query duration - 6.948422 sec. Datapoints: 172801
```

3 days:
```
2015-01-12 17:20:19,836 - DEBUG - Sending request - http://10.206.77.194:80/render?from=01:00_20150106&until=01:00_20150109&target=<graphite series>&format=json
2015-01-12 17:20:32,875 - INFO - Query duration - 13.39656 sec. Datapoints: 259201
```

4 days:
```
2015-01-12 17:20:35,064 - DEBUG - Sending request - http://10.206.77.194:80/render?from=01:00_20150106&until=01:00_20150110&target=<graphite series>&format=json
2015-01-12 17:20:54,630 - INFO - Query duration - 19.565301 sec. Datapoints: 345601
```

We can provide the script used to perform these queries if that would be useful. 

The underlying InfluxDB queries are normal `select time,value from <series name> where time > X and time < Y order asc` queries generated by the graphite_influxdb handler.

**Comment by toddboom** [comment]
@pkittenis The changes for v0.9.0 will include much more than an API refactor. The entire codebase has been rewritten, and introduction of indexed tags will eliminate the need for such a proliferation of series names. In light of that, we're going to keep this issue closed. There may still be serialization overhead we'll want to address down the road, but I think that's best left for a separate issue once the new codebase has been released and profiled.

**Comment by pauldix** [comment]
My other question is why are you returning 8600 data points for graphing?
You can't visualize that much raw data. You should be using rollup
intervals. This means you should be returning anywhere from 200-1000 data
points for a given series that you're visualizing.

That being said, we're working on performance enhancements across the board
(API serialization included)

**Comment by Civil** [comment]
@pauldix for graphing purpose you need to get list of all series, except of the retention scheme.

And for 8600 data points for graphing... well... I know people that are doing that and they say that it's useful (at my current work one of the manager graph stats for all the client-related stats on one graph, and it's thousands of lines, he says that he can see when something bad happens and also he's saying that he need to have all thousands of line)

**Comment by pkittenis** [comment]
Thanks for the update, will wait for 0.9.0 to retest.

While I would agree rollup intervals should be used the queries themselves are generated by grafana via the graphite_influxdb handler. The queries are not something we're doing manually.

Any grafana dashboard with an influxdb backend will generate those queries and try and retrieve 86400 data points for the default 1min resolution graphite metric series if the time range spans 2 months or more.

**Comment by adampl** [comment]
Getting a list of all datasets is probably the most basic operation in any DBMS. If this is a serious project, then __pagination is a must__. I hope this feature will be added soon.

**Comment by pauldix** [comment]
This is fixed in 0.9.0-rc7. Actually since before then. For example you can do:

```
SHOW SERIES LIMIT 10 OFFSET 20
```

**Comment by adampl** [comment]
Oh, that's good news :)

Is it also possible to paginate results from queries such as `SELECT * FROM /.*/ LIMIT 1`?
It is too expensive (in terms of time, bandwith and memory) when there are hundreds of thousands of series :(

**Comment by Dieterbe** [comment]
for those using influx 0.8 as graphite backend,
i added support to graphite-influxdb for using elasticsearch to query metric metadata, bypassing influxdb `list series`. before: 400~800ms, via ES i get <50ms most of the time. with a few outliers, but all cases (median, upper 90th, upper) always at least as good as influx.
![influx-vs-es](https://cloud.githubusercontent.com/assets/20774/6690319/54a44fa0-cc96-11e4-88fe-4d28742cad01.png)
(see https://github.com/vimeo/graphite-influxdb/blob/de5dd7f37c2174bee6b7be860e31cf9635571337/get-series-influxdb-vs-es.png for more numbers)
