### ISSUE TITLE
How to set precision at  DB level

### ISSUE THREAD

**Issue by appunni-dishq** [influxdata/influxdb#8846]
Extension of #8746 : 

I have tried to set the precision in the config file as seconds. But as i write data and tries to fetch it its again showing Nanoseconds timestamp.

I read the whole Doc but couldn't figure it out 
only change in my config file is:  precision = "s"

help me understand these things

How do I set the precision at DB level and how will I make sure I only get set precision timestamps in epoch. And I am using IST as timezone for my Application so also tell me how to set the same for InfluxDB in configuration

I am using python-influxdb client seriesHelper to write data into db and not specifying any time while writing data.

**Comment by appunni-dishq** [comment]
I know its a question. So I am linking it to stackoverflow. [Question](https://stackoverflow.com/questions/46294051/influx-db-precision-setting-at-db-level). You can answer there and close this issue . This is for future reference for anyone searching this up.

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.
