### ISSUE TITLE
Influxdb HTTP GET query stream output

### ISSUE THREAD

**Issue by rapport** [influxdata/influxdb#8862]
### Feature Request

We are trying to improve the performance and remove the latency of our application. Currently we call data from influxdb via HTTP GET and manipulate the data for presentation then we re-request every 1 or 5 seconds for updates. When re-requesting like this most of the data we use is the same as we already have displayed and it is not really needed and we are doing this just to keep the latency low on the display regards to showing new values. Is there any way we can hook onto a HTTP GET to read from an infinite stream of data from the database as new data is coming in? If not could this be added as a new feature?

**Comment by phemmer** [comment]
I don't think it's documented anywhere, but influxdb does have subscriptions where it pushes out all data it receives. This is how kapacitor works. However it requires your app to listen on a socket for the HTTP calls.

See also #8536

**Comment by davemt** [comment]
It seems like this would pair naturally with continuous queries. Would it be easier to implement if it was scoped to CQs?

**Comment by Paxa** [comment]
Is there any example of how to use it?

I only find udp example https://docs.influxdata.com/influxdb/v1.3/query_language/spec/#create-subscription
