### ISSUE TITLE
fill(somevalue) produces incorrect results

### ISSUE THREAD

**Issue by NotionCommotion** [influxdata/influxdb#8867]
**System info:**

InfluxDB shell version 1.3.5
CentOS Linux release 7.3.1611

**Steps to reproduce:**

```
> DROP DATABASE test_fill
> CREATE DATABASE test_fill
> USE test_fill
Using database test_fill
> INSERT m1 f3=1 1504609223000000000
> INSERT m1 f1=1,f2=1 1504609224000000000
> INSERT m1 f1=1,f2=1,f3=1 1504609284000000000
> INSERT m1 f1=1,f3=1 1504609344000000000
> INSERT m1 f2=1 1504609345000000000
>
> select f1, f2, f3, 1.5*f1+2*f2-f3+100 as tot from m1 where time < 1504609384000000000 and time > 1504609184000000000 fill(100)
name: m1
time                f1 f2 f3 tot
----                -- -- -- ---
1504609223000000000       1  299
1504609224000000000 1  1     3.5
1504609284000000000 1  1  1  102.5
1504609344000000000 1     1  200.5
1504609345000000000    1     102
>

```
**Expected behavior:**

```
+---------------------+-----+-----+-----+-------+----------+--------+
|        time         | f1  | f2  | f3  |  tot  | Expected | Error  |
+---------------------+-----+-----+-----+-------+----------+--------+
| 1504609223000000000 | 100 | 100 |   1 |   299 |      449 |   -150 |
| 1504609224000000000 |   1 |   1 | 100 |   3.5 |      3.5 |      0 |
| 1504609284000000000 |   1 |   1 |   1 | 102.5 |    102.5 |      0 |
| 1504609344000000000 |   1 | 100 |   1 |   200 |    300.5 | -100.5 |
| 1504609345000000000 | 100 |   1 | 100 |   102 |      152 |    -50 |
+---------------------+-----+-----+-----+-------+----------+--------+

```

**Actual behavior:**

See Steps to reproduce

**Additional info:**

After additional investigation, maybe I just don't know the precedent of arthritic.  Sorry in advance if that is the case.

```
+---------------------+-----+-----+-----+----------+--------+--------+--------+--------+--------+--------+
|        time         | f1  | f2  | f3  | Expected | Test 1 | Test 2 | Test 3 | Test 4 | Test 5 | Test 6 |
+---------------------+-----+-----+-----+----------+--------+--------+--------+--------+--------+--------+
| 1504609223000000000 | 100 | 100 |   1 |      449 |    299 |    199 |    299 |    299 |    199 |    299 |
| 1504609224000000000 |   1 |   1 | 100 |      3.5 |    3.5 |    3.5 |    3.5 |    3.5 |    3.5 |    3.5 |
| 1504609284000000000 |   1 |   1 |   1 |    102.5 |  102.5 |  102.5 |  102.5 |  102.5 |  102.5 |  102.5 |
| 1504609344000000000 |   1 | 100 |   1 |    300.5 |    200 |  200.5 |  200.5 |  200.5 |  200.5 |  200.5 |
| 1504609345000000000 | 100 |   1 | 100 |      152 |    102 |      2 |    102 |    102 |      2 |    102 |
+---------------------+-----+-----+-----+----------+--------+--------+--------+--------+--------+--------+

```
Test 1: select f1, f2, f3, 1.5*f1+2*f2-f3+100 as tot from m1 where time < 1504609384000000000 and time > 1504609184000000000 fill(100)										
Test 2: select f1, f2, f3, 100+1.5*f1+2*f2-f3 as tot from m1 where time < 1504609384000000000 and time > 1504609184000000000 fill(100)										
Test 3: select f1, f2, f3, 100+(1.5*f1+2*f2-f3) as tot from m1 where time < 1504609384000000000 and time > 1504609184000000000 fill(100)										
Test 4: select f1, f2, f3, (1.5*f1+2*f2-f3)+100 as tot from m1 where time < 1504609384000000000 and time > 1504609184000000000 fill(100)										
Test 5: select f1, f2, f3, 1.5*f1+100+2*f2-f3 as tot from m1 where time < 1504609384000000000 and time > 1504609184000000000 fill(100)										
Test 6: select f1, f2, f3, 1.5*f1+2*f2+100-f3 as tot from m1 where time < 1504609384000000000 and time > 1504609184000000000 fill(100)

**Comment by e-dard** [comment]
@NotionCommotion this definitely looks like a bug to me...

Take for example: 

```
select "f1", "f2", "f3", 1.5*f1+2*f2-f3+100 as tot from "m1" where time < 1504609384000000000 and time > 1504609184000000000 fill(100)
```

Assuming the `fill(100)` worked correctly and filled `f1` and `f2` (since we know `f3 == 1`), then we can simplify for the earliest point in the data :

```
1.5*f1+2*f2-f3+100 == 1.5 * 100 + 2 * 100 - 1 + 100 == 449
```

Let's assume that the `fill(100)` doesn't work and `f1` and `f2` remain as `0`, then we can simplify for the earliest point in the data to:

```
1.5*f1+2*f2-f3+100 == 1.5 * 0 + 2 * 0 - 1 + 100 == 99
```

Yet when I run the following:

```
DROP DATABASE test_fill
CREATE DATABASE test_fill
USE test_fill

INSERT m1 f3=1 1504609223000000000
INSERT m1 f1=1,f2=1 1504609224000000000

select "f1", "f2", "f3", 1.5*f1+2*f2-f3+100 as tot from "m1" where time < 1504609384000000000 and time > 1504609184000000000 fill(100)

name: m1
time                f1 f2 f3 tot
----                -- -- -- ---
1504609223000000000       1  299
1504609224000000000 1  1     3.5
>
```

The first point here has the value `tot == 299`, which is neither `99` or `449`. Seems to me like `f2` has been filled (though not displayed on the output) and `f1` has neither been filled or displayed, since:

```
1.5*f1+2*f2-f3+100 == 1.5 * 0 + 2 * 100 - 1 + 100 == 299
```

**Comment by NotionCommotion** [comment]
@e-dard Thanks for your comment.  Glad I wasn't wasting my time writing this issue and other people's time reading it.

**Comment by CptTZ** [comment]
It seems to be right now.
