### ISSUE TITLE
Problem with inserting data into influx (about 1000inserts/s)

### ISSUE THREAD

**Issue by paolss** [influxdata/influxdb#8868]
Hi Trying to insert data by some python script into influx bad have problem with updates for similar records - one record is inserted and second not for example:

GOOD - DB UPDATED:
data on ifasnstats {'writer_id': 'asn-if-in-amqp/19211', 'iface_in': 134, 'stamp_updated': '2017-09-24 17:36:01', 'event_type': 'purge', 'bytes': 6098400, 'as_src': 21249, 'packets': 7200, 'stamp_inserted': '2017-09-24 17:35:00'}
GOOD - DB UPDATED:
data on ifasnstats {'writer_id': 'asn-if-out-amqp/19209', 'iface_out': 134, 'stamp_updated': '2017-09-24 17:36:01', 'event_type': 'purge', 'as_dst': 50531, 'bytes': 23200, 'packets': 400, 'stamp_inserted': '2017-09-24 17:35:00'}

BAD - DB NOT UPDATED:
data on ifasnstats {'writer_id': 'asn-if-out-amqp/19209', 'iface_out': 134, 'stamp_updated': '2017-09-24 17:36:01', 'event_type': 'purge', 'as_dst': 25135, 'bytes': 7716800, 'packets': 5200, 'stamp_inserted': '2017-09-24 17:35:00'}
AND ERROR :
influxdb update failed for [{'time': datetime.datetime(2017, 9, 24, 15, 36, 10, 183069, tzinfo=<UTC>), 'tags': {'customer': 'all', 'asn': 25135, 'interface': 134}, 'fields': {'pps': 8.67, 'bps': 102890.67}, 'measurement': 'asn-if-out'}]

I cant find any difference that can cause this.
There is about 1000 updates/s
There is no problem with RAM/Disc or something that can be HW related - mysql can handle inserts at this lvl - on same host.

**Comment by paolss** [comment]
Problem solved
Cahnged
   max-series-per-database = 1000000
to
   max-series-per-database = 0

Now no problem with updates

**Comment by e-dard** [comment]
@paolss also make sure for efficiency that you're batching your requests up. Sending one request with 10,000 points in it is much more performant than sending 10,000 requests with a single point in each one.
