### ISSUE TITLE
Subscription separates one point into two

### ISSUE THREAD

**Issue by hrj713** [influxdata/influxdb#8869]
System info:

docker version: 1.12.6  
system version: ubuntu 16.04  
base image ubuntu version: 14.04  
influxdb version: 1.3.5  
kapacitor version: 1.3.1  
telegraf version: 1.3.0

Steps to reproduce:  

Telegraf collects `system` metrics and write into influxdb,    
Kapacitor subscription protocol is http.  

Expected behavior:  

Influxdb should not separate a point into two points while transporting points to kapacitor.  

Actual behavior:  

Influxdb will separate a single system point into two points.   
Using tcpdump can see a `system` point is separated:   
```
system,host=192.168.161.101 n_users=0i,n_cpus=4i,load1=1.78,load5=1,load15=0.72 1506332650000000000  
system,host=192.168.161.101 uptime_format="97 days,  8:28",uptime=8411309i 1506332650000000000  
```
Only happens on telegraf's `system` measurement.  

Additional info:  

same issue:
https://github.com/influxdata/kapacitor/issues/1116

**Comment by e-dard** [comment]
@hrj713 what version of Telegraf are you using? This seems according to the thread in influxdata/kapacitor#1116 that this might be a Telegraf issue? /cc @danielnelson

**Comment by hrj713** [comment]
@e-dard telegraf version: 1.3.0

**Comment by hrj713** [comment]
tcpdump shows telegraf sent two points to influxdb:
```
POST /write?consistency=any&db=telegraf&rp=r90d HTTP/1.1
...
system,host=192.168.161.105 n_users=0i,n_cpus=4i,load1=1.04,load5=1.03,load15=0.86 1506422030000000000
system,host=192.168.161.105 uptime_format="22 days,  4:55",uptime=1918538i 1506422030000000000
```

**Comment by danielnelson** [comment]
I believe this is the issue described in https://github.com/influxdata/kapacitor/issues/1217.

**Comment by hrj713** [comment]
@danielnelson yes it is and we will use batch for this kind of circumstance. Thank you very much.
