### ISSUE TITLE
Unable to save data in influx via telegraf

### ISSUE THREAD

**Issue by ankush4188** [influxdata/influxdb#8875]
E! ERROR in input [inputs.exec]: Errors encountered: [unable to parse 'Seconds_Behind_Master 0 Seconds_Behind_Master 0 Seconds_Behind_Master 0 Seconds_Behind_Master 0': invalid field format]

want save data in influx through telegraf unable to do that please help

**Comment by rbetts** [comment]
@ankush4188 Our community forum would be a good place to ask this question: https://community.influxdata.com/c/ts-collect
