### ISSUE TITLE
Cache Snapshot Last Write Duration

### ISSUE THREAD

**Issue by mlee-liveaction** [influxdata/influxdb#8888]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

__Proposal:__ [Description of the feature]
Allow configuring the duration since the last snapshot was written to a TSM file which the engine will snapshot the cache and write it to a new TSM file

__Current behavior:__ [What currently happens]
Current we can only configure `cache-snapshot-memory-size` and `cache-snapshot-write-cold-duration`.

__Desired behavior:__ [What you would like to happen]
Instead of `cache-snapshot-write-cold-duration`, we want to be able to configure `cache-snapshot-last-write-duration`.

__Use case:__ [Why is this important (helps with prioritizing requests)]
In our use case we sometimes have high write rate, and we can tolerate a small window of data loss (a minute or two) in case of server crash. So we are considering putting the WAL on tmpfs. It seems the WAL would get flushed to a TSM file either when it reaches a certain size or when it is idle for the configured "cold duration". However, when the WAL is not idle but not much data is written, the window of data loss could be surprisingly large because it is not idle and it is not reaching the size that would cause a flush. The `cache-snapshot-write-cold-duration` is therefore not helpful in our case. We want to be able to control the window of data loss by configuring `cache-snapshot-last-write-duration`, which is the duration since the last snapshot got written to a TSM file, so we know the WAL will get flushed by the duration even when it is not idle and regardless of the size.

**Comment by rbetts** [comment]
Can I re-phrase to see if I understand the idea?

You'd like a `cache-snapshot-max-age` parameter. The cache should snapshot (flush) either after `cache-snapshot-max-age` seconds or when it fills to `cache-snapshot-memory-size`, whichever happens first.

**Comment by mlee-liveaction** [comment]
@rbetts That's correct. Thanks.
