### ISSUE TITLE
Can't write data point

### ISSUE THREAD

**Issue by soichih** [influxdata/influxdb#890]
Hi. I just learened about InfluxDB and I am giving it a spin. I've fired up a influxdb Docker container from tutum/influxdb (https://registry.hub.docker.com/u/tutum/influxdb/), and I was able to startup influxdb and login to the Web UI.

When I try to write some test data to my database, the web UI tries to contact following URL

> POST: http://some.server.com:48086/db/logs/series?u=hayashis&p=xxxxxxx
> The server respond "400 Bad Request" with following message.
> Unknown type map[string]interface {}

I am pretty much just following this doc > http://influxdb.com/docs/v0.8/introduction/getting_started.html

What I am doing wrong?

**Comment by mindnuts** [comment]
Sorry to resurrect this old thread. I am still getting this very same error. I tried to validate my JSON and it is valid but still the error thrown by the API is "Unknown type map[string]interface {}"

the offending JSON:

```JSON
{
"level":"info",
"message":"express is listening on http://0.0.0.0:7020",
"meta":{},
"timestamp":1423574929004
}
```

Apparently the JSON parser in influxdb does not like empty objects?

**Comment by toddboom** [comment]
@mindnuts Are you sending this with a client? I'm guessing there's something wrong with the payload that's being generated, but it's hard to tell from just the snippet you've pasted. If you can send over more info, we'll see what we can do, but it's most likely just due to improperly formed JSON.

Also, the API is changing quite a bit for v0.9.0, so the format for writing points will be different. Hopefully, this issue will no longer come up after that.

**Comment by mindnuts** [comment]
@toddboom here you go:

Request:
```SHELL
curl 'http://localhost:8086/db/easyDb/series?u=root&p=root' -H 'Content-Type: application/json' -H 'Accept: application/json, text/javascript' -H 'Referer: http://localhost:8083/' -H 'Connection: keep-alive' --data-binary '[{"points":[["info","express is listening on http://0.0.0.0:7020",{},1423574929004]],"name":"events.ec7411ee-4b64-4b3b-b913-bf0424b8f739","columns":["level","message","meta","timestamp"]}]'
```

Response:
```shell
Unknown type map[string]interface {}
```

**Comment by dahankzter** [comment]
I get a similar error:

panic: json: cannot unmarshal number into Go value of type struct { Results []client.Result "json:\"results,omitempty\""; Err string "json:\"error,omitempty\"" }

This when using the code from the sample "writePoints" method:

https://github.com/influxdb/influxdb/tree/master/client

Ping and login works fine (at least I get an understandable error when supplying invalid credentials).
The DB admin interface works and the database is created.

I have the latest Mac install from homebrew.

**Comment by dahankzter** [comment]
Sorry this seems to be referred to in issue #1635  still seems to be an issue though.

**Comment by JesusIslam** [comment]
I got the same problem too with influxdb Go client

I am using InfluxDB v0.8.8 and the latest client

This is the code I am using to write the datapoints

```
if len(memdatas) >= 100 {
            bps = client.BatchPoints{
                Points:     memdatas,
                Database:   DB,
            }
            _, err = conn.Write(bps)
            if err != nil {
                log.Println(err)
            }
            memdatas = []client.Point{}
        }

        mem = systemstat.GetMemSample()
        memdata = client.Point{
            Name:           "memory",
            Timestamp:      mem.Time,
            Fields:         map[string]interface{}{
                "buffers":      mem.Buffers,
                "cached":       mem.Cached,
                "memTotal":     mem.MemTotal,
                "memUsed":      mem.MemUsed,
                "memFree":      mem.MemFree,
                "swapTotal":    mem.SwapTotal,
                "swapUsed":     mem.SwapUsed,
                "swapFree":     mem.SwapFree,
            },
            Precision:      "ms",
        }
        memdatas = append(memdatas, memdata)
```

**Comment by otoolep** [comment]
@JesusIslam -- if, by the "latest client", you mean master code, you should know that master code and v0.8.8 are incompatible. You must use the client code from the 0.8.8 tag with InfluxDB 0.8.

**Comment by FredMeu** [comment]
Hi,

sorry for the dummy question, but how to get this tag? When using "go get" with the path, I have an error message.

Thanks!

**Comment by marcosnils** [comment]
@FredMeu when using go get you'll get the latest client for the 0.9 version. If you need the client for 0.8.x you'll have to manually checkout the 0.8 version of the dependency or use somehing like [godep](https://github.com/tools/godep) in your app.

**Comment by ReetiR** [comment]
func writePoints(con *client.Client) error {
    var (
        shapes     = []string{"circle", "rectangle", "square", "triangle"}
        colors     = []string{"red", "blue", "green"}
        sampleSize = 1000
        pts        = make([]client.Point, sampleSize)
    )

    rand.Seed(42)
    for i := 0; i < sampleSize; i++ {
        pts[i] = client.Point{
            Measurement: "shapes",
            Tags: map[string]string{
                "color": strconv.Itoa(rand.Intn(len(colors))),
                "shape": strconv.Itoa(rand.Intn(len(shapes))),
            },
            Fields: map[string]interface{}{
                "value": rand.Intn(sampleSize),
            },
            Time: time.Now(),
            Precision: "s",
        }
    }

    bps := client.BatchPoints{
        Points:          pts,
        Database:        MyDB,
        RetentionPolicy: "default",
    }

    
    _, err := con.Write(bps)
    if err != nil {
        log.Fatal(err)
    }
    return err
}

This gives and error:  json: cannot unmarshal number into Go value of type struct { Results []client.Result "json:\"results,omitempty\""; Err string "json:\"error,omitempty\"" }

What is the solution?

**Comment by brithefarmer** [comment]
Server error: `POST http://localhost:8086/write?db=innoplux&retentionPolicy=default` resulted in a `500 Internal Server Error` response:
{"error":"invalid character 'i' looking for beginning of value"}

how can we fix this?

**Comment by beckettsean** [comment]
@brithefarmer this is a very old issue for a prior version of the database. Please open a new issue for your problem, and give the actual write statement that was passed to the database.
