### ISSUE TITLE
[1.3.6] InfluxDB RPM contains no manpages

### ISSUE THREAD

**Issue by sethm** [influxdata/influxdb#8908]
I just noticed that the InfluxDB 1.3.6 RPM released to https://dl.influxdata.com/influxdb/releases/influxdb-1.3.6.x86_64.rpm does not contain any manpages.

Previous releases included manpages under /usr/share/man/man1

**Comment by mark-rushakoff** [comment]
We've made some recent changes to our build pipeline, and the omission of the manpages was unintentional. Thanks for raising the issue.
