### ISSUE TITLE
How to specify the database, when dropping measurements via Chronograph query

### ISSUE THREAD

**Issue by GeorgWa** [influxdata/influxdb#8927]
Im sorry to ask this question here, but i cant find information on this topic in the Influxdb docs.
I want do delete a measurement using the Chronograph query interface.
How do i specify the database i want to affect ?

The suggested syntax 
`DROP MEASUREMENT "weather"  ` 
returns 
`Database not found`

In the Influx Interface i can see, that there is no database specified
`POST /query?db=&epoch=ms&q=DROP+MEASUREMENT+weather&rp= HTTP/1.1"`

Using 
`DROP MEASUREMENT "therm"."autogen"."weather" `
returns 
`found . ,expected ; at line 1 char 25` 
suggesting, that no further input is required after the first string.
The same error comes up when specifying 
 `DROP MEASUREMENT "weather" FROM "therm"."autogen" `

**Comment by jsternberg** [comment]
It looks like we do not support `ON <db>` for this type of query. I'll mark this down as something for us to talk about at the next planning meeting.

**Comment by MooreDerek** [comment]
Any progress on this?

**Comment by mythsman** [comment]
mark

**Comment by algotradersxyz** [comment]
Any updates on this please :(

**Comment by Willis0826** [comment]
Is there any workaround ? Temporarily, I couldn't drop the measurement.

**Comment by tonylee2016** [comment]
same problem here

**Comment by tonylee2016** [comment]
reopen, this is important

**Comment by bm2u** [comment]
Hi @tonylee2016, here is what I did to drop certain measurement (in your case weather):

`use therm.autogen`
`drop measurement weather`

It's gone - It works!

**Comment by tomasaschan** [comment]
/reopen please.

Or at least give some reason why this won't be addressed. Is there some way the community could help out with this?

**Comment by optimuspaul** [comment]
@bm2u how can you do that in chronograf? This is pretty frustrating as I don't have direct access to this database.

**Comment by bm2u** [comment]
@optimuspaul I don't think so. I've used the command line interface (influx) to drop data.

**Comment by alexeinz** [comment]
same here.. its pretty frustrating in fact...

**Comment by upMKuhn** [comment]
same here.. its pretty frustrating in fact...

**Comment by one-random-dev** [comment]
Same here, having to use the command line is a limitation.

Please reopen this or have someone tag it as won't fix, at least some kind of feedback please

**Comment by bernardolm** [comment]
+1

**Comment by lelithium** [comment]
This would be very useful.

**Comment by Kosygor** [comment]
I do upvote. Right now I am playing around with dump measurements for few days.

**Comment by matthewdowney** [comment]
If I 

```
use database foo
drop measurement bar
```

It appears that this drops all measurements named "bar", regardless of database? How can I drop a measurement for just one database?

**Comment by PhilippJust** [comment]
You can add the database as extra parameter like

```
curl -v -XPOST https://[YOUR-HOST]/query -u [USER]:[PASSWORD]  --data-urlencode 'db=[YOUR-DB]' --data-urlencode 'q=DROP MEASUREMENT "[YOUR-MEASUREMENT]"'
```
