### ISSUE TITLE
Heavy memory usage followed by OOM kill from the OS when HDD is full

### ISSUE THREAD

**Issue by lyondhill** [influxdata/influxdb#8946]
### Bug report

__System info:__ 1.3.6 enterprise, but I suspect it is OSS as well

__Steps to reproduce:__

1. Start Influxdb
2. fill the hard drive with data

__Expected behavior:__ Disk Full error message.

__Actual behavior:__ Server started using all RAM until it was OOM killed by OS

__Additional info:__ 
The servers in the cluster are cycling between accessable and locked. After the OS kills the server I can connect and get the profile for a short time before the influxd binary fills the ram again.
I am not sure how useful the proflie will be because the server I pulled it from had only recovered an hour before and was in the process of refilling the RAM.
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/1370587/profiles.tar.gz)

**Comment by jwilder** [comment]
I can't reproduce this with `master`.  @lyondhill Are you able to reproduce w/ `master`?

**Comment by lyondhill** [comment]
I was able to reproduce the failure state, Although I believe now the full HD is a symptom of a failure instead of the cause.

I believe I was able to reproduce this:
I used `pcl` to create a new cluster of small servers (3 meta and 6 data) with the latest nightly build.

I then created a database with a RF of 2

then i started a process that would insert 10000 data points per second with 125 int64 fields per point. 

It ran for about an hour and the disk/cpu/mem seemed fine. The first server stopped responding followed by a second
<img width="1498" alt="screen shot 2017-10-16 at 1 01 43 pm" src="https://user-images.githubusercontent.com/453855/31630989-8f853810-b275-11e7-9685-c3efb9551797.png">

Then The servers began resetting 

<img width="465" alt="screen shot 2017-10-16 at 1 04 34 pm" src="https://user-images.githubusercontent.com/453855/31631136-f84412ea-b275-11e7-88cd-a71e215cac51.png">

I turned off data insertion and the cluster is failing to recover:

```
ubuntu@ip-10-0-235-5:~$ influxd-ctl show
Data Nodes
==========
ID	TCP Address		Version
7	10.0.152.44:8088	1.3.0rc1-c1.3.0rc1
8	10.0.156.131:8088	1.3.0rc1-c1.3.0rc1
5	10.0.174.116:8088	1.3.0rc1-c1.3.0rc1
4	10.0.178.40:8088	1.3.0rc1-c1.3.0rc1
6	10.0.243.2:8088		
9	10.0.248.96:8088	

Meta Nodes
==========
TCP Address		Version
10.0.171.194:8091	1.3.0rc1-c1.3.0rc1
10.0.235.5:8091		1.3.0rc1-c1.3.0rc1
10.0.64.66:8091		1.3.0rc1-c1.3.0rc1
```

I tested this earlier and If I didnt turn of data insertion the HH would fill and then more then 2 servers would fail.

<img width="1498" alt="screen shot 2017-10-16 at 1 01 43 pm" src="https://user-images.githubusercontent.com/453855/31631173-19c54c9a-b276-11e7-983c-fe1b96cacfc8.png">

**Comment by lyondhill** [comment]
After our conversation @jwilder I tested using t2.medium servers. After a short duration I began getting connection refused:
<img width="1474" alt="screen shot 2017-10-17 at 9 52 34 am" src="https://user-images.githubusercontent.com/453855/31675159-09e5f512-b321-11e7-8993-fcda611f573e.png">

The larger servers seemed to be a bit better but I still saw issues with one or 2 servers. I changed the write consistency to 'all' and ran the test overnight.

<img width="1491" alt="screen shot 2017-10-17 at 9 35 34 am" src="https://user-images.githubusercontent.com/453855/31675227-3db89b06-b321-11e7-84ac-937a94e6daf9.png">

It lasted longer but the one server I was writing to ended up filling its disk. and is now non communicative.

I am going to try writing to all instead of one and see if that is causing the problem

**Comment by lyondhill** [comment]
Node failure continues to happen when load balancing writes

<img width="1464" alt="screen shot 2017-10-17 at 1 44 53 pm" src="https://user-images.githubusercontent.com/453855/31685790-70d25a34-b341-11e7-9843-28e6171889be.png">

**Comment by lyondhill** [comment]
With seperate volumes for the influxdb data It ran out of disk space on a server: 

<img width="1467" alt="screen shot 2017-10-17 at 4 01 40 pm" src="https://user-images.githubusercontent.com/453855/31691804-9620b228-b354-11e7-92c1-8013762a691b.png">

Then ran out of memory. Then crashed.
I was able to retrieve the Stack trace.

```

**Comment by lyondhill** [comment]
This issue was moved to influxdata/plutonium#1796
