### ISSUE TITLE
[Enterprise] License environment variable names are wrong in the logs

### ISSUE THREAD

**Issue by svartulv** [influxdata/influxdb#8958]
### Bug report

__System info:__ InfluxDB Enterprise 1.3.6, Debian 9

__Steps to reproduce:__

1. Do not set license parameter in either configuration file or environment variable.
2. Run `service influxdb-meta start` in case of Meta node, or `service influxdb start` in case of Data node, or run corresponding binaries directly.

__Expected behavior:__
Log message suggests to set your license via either config file or environment variables **INFLUXDB_ENTERPRISE_LICENSE_KEY** or **INFLUXDB_ENTERPRISE_LICENSE_PATH**.

__Actual behavior:__
Log message suggests to set your license via either config file or environment variables **LICENSE_KEY** or **LICENSE_PATH**, which actually do not work and are not what documentation says.

__Additional info:__ 
Example of actual log messages:
```
# cat /var/log/influxdb/influxd.log

[I] 2017-10-12T17:13:10Z InfluxDB starting, version 1.3.6-c1.3.6, branch 1.3, commit 728dc885da9eb56913bc68391acab4ffa139c66f
[I] 2017-10-12T17:13:10Z Go version go1.8.3, GOMAXPROCS set to 2
[I] 2017-10-12T17:13:10Z Using configuration at: /etc/influxdb/influxdb.conf

[I] 2017-10-12T17:13:10Z Starting hinted handoff service service=handoff
[I] 2017-10-12T17:13:10Z 'hh' registered for diagnostics monitoring service=monitor
[I] 2017-10-12T17:13:10Z Using data dir: /var/lib/influxdb/hh service=handoff
[I] 2017-10-12T17:13:10Z Using data dir: /var/lib/influxdb/data service=store
[I] 2017-10-12T17:13:10Z opened service service=subscriber
run: open server: 
This product requires a license key or file to run.
Please enter your license key or path to your license
file in the configuration file, like so:

[enterprise]
license-key = "my-license-key"
license-file = "/path/to/file"

Licenses can also be set using the following ENV variables:

LICENSE_KEY
LICENSE_PATH

If you do not have a valid license key, then please head over to
https://portal.influxdata.com to purchase a license for this product.
```

Links to corresponding documentation:
https://docs.influxdata.com/enterprise_influxdb/v1.3/administration/configuration/#license-key
https://docs.influxdata.com/enterprise_influxdb/v1.3/administration/configuration/#license-path

**Comment by timhallinflux** [comment]
Need to fix error message output.

**Comment by jsternberg** [comment]
To add to this, `license-file` is not correct. `license-path` is correct. So the error message has to be fixed for more than just the environment variables.
