### ISSUE TITLE
There is no exe file When I unzip influxdb-1.3.6_windows_amd64.zip 

### ISSUE THREAD

**Issue by zhangshuiyong** [influxdata/influxdb#8960]
I go to the influxdata official website download page https://portal.influxdata.com/downloads

Then download windows Windows Binaries (64-bit) version And Unzip the influxdb-1.3.6_windows_amd64.zip.

Only influx,influx_inspect,influx_stress,influx_tsm,influxd file.But these are not exe file and no influxdb.conf.

**Comment by thibodux** [comment]
Confirm the same issue for me. I had to rename all the file to include the ".exe" extension.

**Comment by mark-rushakoff** [comment]
We made some changes to our packaging system and the 1.3.6 Windows release mistakenly lost the .exe extension and missed the example configuration file. The next release will have the extension and the configuration file. Sorry for the inconvenience.

**Comment by mark-rushakoff** [comment]
The packaging in 1.3.7 should be identical to 1.3.5 and earlier. Sorry again for the inconvenience with 1.3.6.
