### ISSUE TITLE
 If you enable authentication and have no users, InfluxDB will not enforce authentication and will only accept the query that creates a new admin user.

### ISSUE THREAD

**Issue by shanquanqiang** [influxdata/influxdb#8967]
i create an admin user with CREATE USER admin WITH PASSWORD '<password>' WITH ALL PRIVILEGES but it get an error : unable to parse authentication credentials，my influxdb 1.3.1

what‘s the mean about this note: If you enable authentication and have no users, InfluxDB will not enforce authentication and will only accept the query that creates a new admin user.

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.

**Comment by douglasg14b** [comment]
This seems like an actionable bug report, just worded poorly.

He has enabled auth, but did not create a user. When OP tries to create a user, just as the docs guide us to, he gets `ERR: unable to parse authentication credentials`. Whioch is what I'm getting as well.

**Comment by douglasg14b** [comment]
@e-dard  any comment?

**Comment by quaxsze** [comment]
I am also seeing this issue. What is the status on this?

**Comment by dzhus** [comment]
It will probably be more productive to create a new reworded bug report rather than keep commenting on a closed issue.
