### ISSUE TITLE
Missing 1.3.6 RPM in yum repo

### ISSUE THREAD

**Issue by adrianlzt** [influxdata/influxdb#8972]
InfluxDB 1.3.6 was released 19 days ago but the [official repo](https://repos.influxdata.com/rhel/7/x86_64/stable/?C=M;O=D) still does not have the rpm.

**Comment by austinbutler** [comment]
Also [the changelog](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) shows last release as 1.3.3.

**Comment by adrianlzt** [comment]
Version 1.3.7 in the repo https://repos.influxdata.com/rhel/7/x86_64/stable/influxdb-1.3.7.x86_64.rpm
Thanks!
