### ISSUE TITLE
Is there a reason why Influxd doesn't remove its PID file when it stops

### ISSUE THREAD

**Issue by thibodux** [influxdata/influxdb#8983]
While digging into https://github.com/influxdata/chronograf/issues/2075 over in Chronograf, I realized that neither Influxd or Kapactiord do anything to remove their respective PID files when the daemons go down. They do not monitor the PID file as a shutdown control either, i.e., deleting the PID file would kill the daemon.

Is there a reason for these omissions?

Telegraf does remove its PID file when the process terminates, but it does not monitor the PID file as a shutdown indicator.

**Comment by jsternberg** [comment]
I don't think there's any program that monitors the pid file as a shutdown indicator. Can you give me an example of that?

I'll look to make sure the PID file is getting deleted correctly on shutdown though.

**Comment by thibodux** [comment]
Don't have any off the top of my head (been a while since I dealt with it), but I feel like that is a feature of some. Regardless, that is unimportant relative to the clean-up of the pid file. That is really the main feature request. Applies to Kapacitor too.

**Comment by jsternberg** [comment]
I've merged a fix for InfluxDB and submitted a fix for Kapacitor. You say that Telegraf does this correctly and Chronograf doesn't appear to have a PID writing feature from what I can find. The Kapacitor fix will be handled in the Kapacitor repository in the linked issue.

**Comment by thibodux** [comment]
Thanks for the changes @jsternberg. There is an issue in Chronograf for this request: https://github.com/influxdata/chronograf/issues/2075. Would be good to have. As that issue says, Telegraf has this, but the code is completely different. Might be worth cleaning up the Telegraf code to reuse the code here and in Kapacitor.

**Comment by danger89** [comment]
@ jsternberg Yes Monit will use the pid file as indicator: https://mmonit.com/monit/documentation/#PID-TEST
