### ISSUE TITLE
Influxdb security know-how

### ISSUE THREAD

**Issue by gowrisankar22** [influxdata/influxdb#8988]
Hi Experts,

I would like to hear few aspects for influx db security, can somebody can help me here?

1. what are all the different authentication mechanism influx-db supports (example: basic authentication …etc) ?? and which authentication mechanism is more safe ?

2. How to Harden Docker image from attackers if influxdb is docker based ?

3. how the vulnerability scanning is done for influxdb??

Thanks,
GS.

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.

**Comment by gowrisankar22** [comment]
@e-dard  posted my queries. can you check https://community.influxdata.com/t/influxdb-security-know-how/2811
