### ISSUE TITLE
influx_inspect report -detailed: sort by estimated cardianlity and/or show top items

### ISSUE THREAD

**Issue by jumptrading-linux** [influxdata/influxdb#9002]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

__Proposal:__ 
influx_inspect report -detailed returns one line per measurement/tag/field. The likely use case calling it is looking for the highest cardinality items. This proposal is to sort the fields (starting with the highest cardinality) and add a -show-top=10 to only show the top X of each type.

__Current behavior:__ [What currently happens]
Several thousand lines are returned, and the user eyeballs them to find the high rows.

__Desired behavior:__ [What you would like to happen]
Return the list sorted, so for each type (tag/field/measurement) the highest cardinality items are returned first. 
Provide a way to only show the top X for each type

__Use case:__ [Why is this important (helps with prioritizing requests)]
In the event of somebody injecting garbage data, being able to locate it quickly and delete it from disks is critical - InfluxDB can be down and unstartable until this occurs. Having to eyeball thousands of lines of output to do this is not ideal.

**Comment by rbetts** [comment]
TopN is an interesting request. 

You might also be interested in the rent addition of `show cardinality` commands. We'd like to make it much easier to understand DB cardinality without needing to use influx_inspect. You can see the recently merged `show cardinality` work here: https://github.com/influxdata/influxdb/pull/8636.

**Comment by alexdaviesjump** [comment]
@rbetts thanks - our problem is that where we have something that injects enormous cardinality (which means somebody screwed up on our side), we often either cant start the database, or it takes an absurd amount of time to start and run any SHOW commands. This is better in 1.4 but I believe still not something totally solved (to be fair, i've not tested with pathological cardinality under very recent commits).
