### ISSUE TITLE
incorrect processing of where clause with subqueries

### ISSUE THREAD

**Issue by cxcv** [influxdata/influxdb#9010]
### Bug report

__System info:__ 
Debian 9 x86_64
InfluxDB 1.3.6-1 from repos.influxdata.com

__Steps to reproduce:__
Background:
I've time series data from Icinga2 and I want to identify stalled machines, e.g. machines with no updated series since the last 30 days. To achieve this, I select the LAST value for each series, and I wrap this in a subquery. Now, the outer query uses a WHERE clause, but this is somehow "magically" applied to the subquery - which is logically wrong.

1. Sub Query: ```select time, hostname, last(value) from ping4 group by hostname```

2. Full Query:
```select * from (select time, hostname, last(value) from ping4 group by hostname ) where time < now()-30d```

__Expected behavior:__
The Full Query should reduce the result set from the Sub Query using the WHERE clause, so only outdated series are eturned.

__Actual behavior:__ 
Instread, the WHERE clause is applied to the Sub Query, and the result includes all up-to-date series and the LAST value is 30 days old.

In fact, this is the same result as when I move the WHERE clause to the Sub Query:
```select * from (select time, hostname, last(value) from ping4 where time < now()-30d group by hostname)```

**Comment by svet-b** [comment]
Just wanted to confirm that I'm experiencing the exact same issue, when running a very similar use case. Was surprised to see that the `WHERE` clause in the main query is actually applied to the subquery. I'm assuming this isn't intentional (or at least does not appear to be documented).

Happy to provide more supporting info if potentially helpful.

**Comment by derrix060** [comment]
It should be, at least, documented somewhere.
