### ISSUE TITLE
SHOW MEASUREMENTS not working

### ISSUE THREAD

**Issue by lpic10** [influxdata/influxdb#9016]
### Bug report

InfluxDB version: nightly (version: 1.4.0~n201710250800) on a RHEL 7 (x86-64)

This is a test environment and I've been using nightly versions for some months already, upgrading from time to time. 

The issue appears in a database named "kubernetes" that is using tsi1 (which was a big improvement in terms of memory consumption) and has ~450 measurements and ~1500000 series. When running SHOW MEASUREMENTS on this database InfluxDB starts consuming a lot of memory until the kernel invokes oom-killer 2-5 minutes later.  

I started a profile and few seconds after issuing it:
[profile.tar.gz](https://github.com/influxdata/influxdb/files/1418429/profile.tar.gz)

I noticed this was happening few weeks ago, I don't know exactly since when and I didn't have time to dig into this before. The instance seems stable otherwise. Also other databases running in this same InfluxDB instance responds normally to the SHOW MEASUREMENTS.

Let me know if you need more information.

**Comment by e-dard** [comment]
@lpic10 thanks for the report. I'm looking at this now. How much RAM do you have on the box?

**Comment by lpic10** [comment]
I can confirm tomorrow but if I remember well this VM has 12 GB of RAM.

**Comment by lpic10** [comment]
I can't see this issue anymore. I downgraded InfluxDB to 1.3.7 few weeks ago and recently I applied upgrade procedure to 1.4 and since I don't see any issue when running nightlies.
