### ISSUE TITLE
cannot compact index files index=tsi error=tag value out of order:

### ISSUE THREAD

**Issue by anatolijd** [influxdata/influxdb#9025]
### Bug report

Have switched to `index-version = "tsi1"` couple of days ago and it's been running it with no issues.
Today we've upgraded to 1.3.7 version and now log file is flooded with messages like:

### cannot compact index files index=tsi token=95cf12 error=tag value out of order: prev=cpu6, new=cpu20

Number of uncompacted index files rapidly grows:

root:~# ll -h /opt/influxdb/data/telegraf/default/842/index/|tail
-rw-r--r-- 1 influxdb influxdb  13M Oct 27 09:12 L2-00002571.tsi
-rw-r--r-- 1 influxdb influxdb  13M Oct 27 09:12 L2-00002572.tsi
-rw-r--r-- 1 influxdb influxdb  13M Oct 27 09:12 L2-00002573.tsi
-rw-r--r-- 1 influxdb influxdb  13M Oct 27 09:12 L2-00002574.tsi
-rw-r--r-- 1 influxdb influxdb  13M Oct 27 09:12 L2-00002575.tsi
-rw-r--r-- 1 influxdb influxdb  13M Oct 27 09:12 L2-00002576.tsi
-rw-r--r-- 1 influxdb influxdb  13M Oct 27 09:12 L2-00002577.tsi
-rw-r--r-- 1 influxdb influxdb  13M Oct 27 09:12 L2-00002578.tsi
-rw-r--r-- 1 influxdb influxdb 704K Oct 27 09:12 L2-00002579.tsi
-rw-r--r-- 1 influxdb influxdb  449 Oct 27 09:00 MANIFEST

root:~# ll -h /opt/influxdb/data/telegraf/default/842/index/|wc -l
2593

```
Version: 1.3.7-c1.3.7
cache-max-memory-size = 8194304000
cache-snapshot-memory-size = 26214400
index-version = "tsi1"

```
telegraf database stats:

```
Size on disk: 40G
Measurements: 23
Series: 225647447

```

short log output:

```
# tail -n10 -f  /opt/log/influxdb/influxd.log|grep compact
[E] 2017-10-27T09:04:30Z cannot compact index files index=tsi token=b62b4f error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:30Z performing full compaction index=tsi token=20b698 src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000949.tsi
[E] 2017-10-27T09:04:31Z cannot compact index files index=tsi token=20b698 error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:31Z performing full compaction index=tsi token=ad2ec9 src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000950.tsi
[E] 2017-10-27T09:04:31Z cannot compact index files index=tsi token=ad2ec9 error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:31Z performing full compaction index=tsi token=e41ffc src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000951.tsi
[E] 2017-10-27T09:04:31Z cannot compact index files index=tsi token=e41ffc error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:31Z performing full compaction index=tsi token=f570b2 src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000952.tsi
[E] 2017-10-27T09:04:32Z cannot compact index files index=tsi token=f570b2 error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:32Z performing full compaction index=tsi token=ef3089 src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000953.tsi
[E] 2017-10-27T09:04:32Z cannot compact index files index=tsi token=ef3089 error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:32Z performing full compaction index=tsi token=09b05f src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000954.tsi
[E] 2017-10-27T09:04:32Z cannot compact index files index=tsi token=09b05f error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:32Z performing full compaction index=tsi token=60ac5e src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000955.tsi
[E] 2017-10-27T09:04:32Z cannot compact index files index=tsi token=60ac5e error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:32Z performing full compaction index=tsi token=ef43bd src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000956.tsi
[E] 2017-10-27T09:04:33Z cannot compact index files index=tsi token=ef43bd error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:33Z performing full compaction index=tsi token=49e50a src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000957.tsi
[E] 2017-10-27T09:04:33Z cannot compact index files index=tsi token=49e50a error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:33Z performing full compaction index=tsi token=8c0e5d src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000958.tsi
[E] 2017-10-27T09:04:33Z cannot compact index files index=tsi token=8c0e5d error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:33Z performing full compaction index=tsi token=af52bf src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000959.tsi
[E] 2017-10-27T09:04:33Z cannot compact index files index=tsi token=af52bf error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:33Z performing full compaction index=tsi token=c76d86 src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000960.tsi
[E] 2017-10-27T09:04:34Z cannot compact index files index=tsi token=c76d86 error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:34Z performing full compaction index=tsi token=2a148d src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000961.tsi
[E] 2017-10-27T09:04:34Z cannot compact index files index=tsi token=2a148d error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:34Z performing full compaction index=tsi token=f06bae src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000962.tsi
[E] 2017-10-27T09:04:34Z cannot compact index files index=tsi token=f06bae error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:34Z performing full compaction index=tsi token=3aaa6f src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000963.tsi
[E] 2017-10-27T09:04:34Z cannot compact index files index=tsi token=3aaa6f error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:34Z performing full compaction index=tsi token=95cf12 src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000964.tsi
[E] 2017-10-27T09:04:35Z cannot compact index files index=tsi token=95cf12 error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:35Z performing full compaction index=tsi token=7ffec5 src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000965.tsi
[E] 2017-10-27T09:04:35Z cannot compact index files index=tsi token=7ffec5 error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:35Z performing full compaction index=tsi token=96af59 src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000966.tsi
[E] 2017-10-27T09:04:35Z cannot compact index files index=tsi token=96af59 error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:35Z performing full compaction index=tsi token=ef5081 src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000967.tsi
[E] 2017-10-27T09:04:36Z cannot compact index files index=tsi token=ef5081 error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:36Z performing full compaction index=tsi token=d17b5e src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000968.tsi
[E] 2017-10-27T09:04:36Z cannot compact index files index=tsi token=d17b5e error=tag value out of order: prev=cpu6, new=cpu20
[I] 2017-10-27T09:04:36Z performing full compaction index=tsi token=9fe905 src=2,1 dst=/opt/influxdb/data/telegraf/default/842/index/L2-00000969.tsi
[E] 2017-10-27T09:04:36Z cannot compact index files index=tsi token=9fe905 error=tag value out of order: prev=cpu6, new=cpu20
```

There is 2 data nodes in the cluster.    this happens on both data nodes.

**Comment by benbjohnson** [comment]
@anatolijd The error comes from a consistency check we added. Unfortunately, because of a bug in 1.3.6, some of the index values are stored out of order and you will need to rebuild your index. We have rebuilding tools in `master` but I'm in the process of backporting them to the `1.3.x` branch right now. I will let you know once I get those backported.

**Comment by benbjohnson** [comment]
@rbetts Backport `influx_inspect inmem2tsi` (https://github.com/influxdata/influxdb/pull/9036).

**Comment by mmuller99** [comment]
Is this failure leaving behind files? After a restart and seeing the same logs, our influx grew with 300gb with any new data coming in?

**Comment by MikeSchroll** [comment]
I upgraded from 1.3.3 to 1.3.7 and am experiencing this issue... never ran 1.3.6.

**Comment by mmuller99** [comment]
Only one of our `autogen` index folders are excessively large, 4.4TB at time of going back to 1.3.6.  The index folder has `1039718` .tsi files in.  So the compaction process is definitely creating `tsi` files in an endless loop.

**Comment by benbjohnson** [comment]
@mmuller99 It looks like it's not cleaning up properly on failure. TSI only uses the files listed in the `MANIFEST` file so you can safely delete any other files in the directory as long as the shard is not actively compacting.

**Comment by MikeSchroll** [comment]
How is influx_inspect supposed to fix this?

I ran:
influx_inspect inmem2tsi -datadir /var/lib/influxdb/data/mydbname/one_day/2414724147 -waldir /var/lib/influxdb/wal/mydbname/one_day/24147

[I] 2017-10-30T21:28:09Z checking index path path=24147/index
inmem2tsi: tsi1 index already exists

my logs still flood with:
```
[E] 2017-10-30T21:25:23Z cannot compact index files index=tsi token=ab0dfc error=tag value out of order: prev=8, new=40,6,3,19
[I] 2017-10-30T21:25:23Z performing full compaction index=tsi token=e6c130 src=2,1 dst=/var/lib/influxdb/data/mydbname/one_day/24147/index/L2-00088755.tsi
```

my manifest does not list any L2 files.

I'm waiting on resolution by just running `while :; do rm L2*; sleep 1; done`
to stop the HD from filling while waiting for a solution.

I have been running index-version = "tsi1" for many months.
Running influx 1.3.7

It was also doing it on an 'hourly' measurement; but stopped once that rotated out. So this may also 'fix itself' once tomorrow comes around, and this is purged.

But why did this happen? And can I make sure the HD doesn't fill again?

**Comment by benbjohnson** [comment]
@MikeSchroll `inmem2tsi` rebuilds the index from the `tsm` files directly. Here are the steps to rebuild it:

1. Stop `influxd`.
2. Remove the old `index` directory in your shard's data directly (or move it to a different location).
3. Run the `inmem2tsi` command that you listed above.
4. Start `influxd`.

The issue occurred because the tag values can get written out of order in `1.3.6` and cause duplicates to show in `SHOW TAG VALUES`. We added an additional safety check in `1.3.7` to notify if there was an issue but the recovery issue was not intentional.

Once the index is rebuilt then the issue won't happen again.

**Comment by MikeSchroll** [comment]
Great -- that worked. Thanks!

**Comment by sandebains** [comment]
Can this be added as a DB startup option or a flag? This has happened twice on two different databases in the last 24 hours. It is annoying as the defect left the system in  unusable due to disk size limits.

**Comment by sandebains** [comment]
I actually manually dropped a measurement and after that started seeing this issue... In the past 2 weeks this has happened thrice (last time this happened when I manually dropped a measurement).

**Comment by syepes** [comment]
I just faced this issue when moving from 1.3 to 1.4, here is a quick fix

- Stop influxd.
- Fix indexes

> for db in $(ls /var/lib/influxdb/data/); do        
 for i in $(ls /var/lib/influxdb/data/$db/raw/); do                                                           
  rm -rf /var/lib/influxdb/data/$db/raw/$i/index                                                              
  influx_inspect inmem2tsi -datadir /var/lib/influxdb/data/$db/raw/$i -waldir /var/lib/influxdb/wal/$db/raw/$i  
 done                                              
done

- Start influxd.

**Comment by e-dard** [comment]
This can be resolved with the `inmem2tsi` tooling.
