### ISSUE TITLE
Influxdb autorization issue

### ISSUE THREAD

**Issue by rehanch178** [influxdata/influxdb#9027]
Hi,

I ma facing lot of issues with influxdb authorization in version 1.3.6
Could you please help.

**Comment by rehanch178** [comment]
{"timestamp":"2017-10-28T04:22:02.312461-0700","level":"warn","message":"failed to require extension","file":"/etc/sensu/extensions/influxdb.rb","error":{"path":"multi_json","~bt_locations":"#<Thread::Backtrace:0x00000001344c60>","~mesg":"cannot load such file -- multi_json","~bt":["/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/etc/sensu/extensions/influxdb.rb:4:in `<top (required)>'","/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.0/lib/sensu/extensions/loader.rb:81:in `load_file'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.0/lib/sensu/extensions/loader.rb:97:in `block in load_directory'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.0/lib/sensu/extensions/loader.rb:96:in `each'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.0/lib/sensu/extensions/loader.rb:96:in `load_directory'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.0/lib/sensu/extensions.rb:20:in `load'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.0/lib/sensu/extensions.rb:44:in `get'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/daemon.rb:154:in `load_extensions'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/daemon.rb:55:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:42:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:30:in `new'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:30:in `run'","/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/exe/sensu-server:10:in `<top (required)>'","/opt/sensu/bin/sensu-server:22:in `load'","/opt/sensu/bin/sensu-server:22:in `<main>'"]}}

this is the error

**Comment by jsternberg** [comment]
The first line of the log file appears to be that sensu cannot load the influxdb extension. That means it is likely an issue with your sensu installation and not with InfluxDB.
