### ISSUE TITLE
percentile(field,95) returns unexpected result

### ISSUE THREAD

**Issue by drocsid** [influxdata/influxdb#9046]
### Bug report

__System info:__ [InfluxDB shell version: 1.3.7]

__Steps to reproduce:__

1. ["""given a select statment query called Qry that generates a result like: 
     timestamp                       api           xtime
     1509217200047800974 some-api 20
     1509217200077447322 some-api 21
     1509217200102388293 some-api 16
     1509217200128704647 some-api 56
     1509217200166677893 some-api 13
     1509217200178389013 some-api 20
     1509217200182976417 some-api 16
     1509217200255217252 some-api 47
     1509217200258091020 some-api 18
     1509217200279101702 some-api 12"""]

2. execute a subquery like select percentile(xtime,95) from (Qry)

__Expected behavior:__ [From a spreadsheet the 95th percentile is 51.949999999]

__Actual behavior:__ [
"""gives 55 as the resulting 95th percentile.
time                                percentile
1509217221991931199 55"""
]

**Comment by jsternberg** [comment]
I believe percentile does not do any kind of average of values. It is a selector so it always chooses one of the values. Are you sure that the actual behavior wasn't to choose 56 rather than 55?

**Comment by dgnorton** [comment]
Closing. If this is still an issue on 1.5.2 or newer, please create a new issue.
