### ISSUE TITLE
InfluxDB fails on NFS with "stale NFS file handle" error

### ISSUE THREAD

**Issue by bedrin** [influxdata/influxdb#9047]
### Bug report

I'm using InfluxDB 1.3.4 on Linux with storage on a NFS mount

NFS share had some intermetting issues which lead to "error writing snapshot: error opening new segment file for wal" errors in InfluxDB. Although NFS share went back online InfluxDB didn't recover from it and continue writing following errors to the log:

`[I] 2017-11-01T08:35:17Z error writing snapshot: error opening new segment file for wal (1): write /data/influxdb/db/wal/_internal/monitor/24/_00005.wal: stale NFS file handle engine=tsm1`

Eventually it crashed with following error:

`fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fdeb830007c pc=0x9b8b88]
goroutine 5215247 [running]:
runtime.throw(0xb88157, 0x5)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc438f4c4d8 sp=0xc438f4c4b8
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:287 +0xf4 fp=0xc438f4c528 sp=0xc438f4c4d8
github.com/influxdata/influxdb/tsdb/engine/tsm1.DecodeIntegerBlock(0x7fdeb830007c, 0x1a, 0x80d8a, 0xc43bbfc560, 0xc420330400, 0x110, 0x7fdeddf6aa30, 0x0, 0xc431
b64520)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:619 +0x48 fp=0xc438f4c620 sp=0xc438f4c528
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*mmapAccessor).readIntegerBlock(0xc4299b86c0, 0xc42d9b2e10, 0xc43bbfc560, 0x8, 0x1, 0x0, 0x8, 0xc4281f9db8)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:1151 +0xb1 fp=0xc438f4c6a0 sp=0xc438f4c620
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*TSMReader).ReadIntegerBlockAt(0xc432eb4000, 0xc42d9b2e10, 0xc43bbfc560, 0x1, 0xc4281f9db8, 0xc438f4c7e8, 0x410
fb2, 0xc43bbfc540)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:283 +0x71 fp=0xc438f4c720 sp=0xc438f4c6a0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*KeyCursor).ReadIntegerBlock(0xc44bdb6c00, 0xc43bbfc560, 0xa, 0xc43c784960, 0xa, 0xa, 0xc438f4c870)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.gen.go:182 +0x85 fp=0xc438f4c828 sp=0xc438f4c720
github.com/influxdata/influxdb/tsdb/engine/tsm1.newIntegerAscendingCursor(0x14f0c2f56859f9b2, 0xc433422000, 0x1af7, 0x1af7, 0xc44bdb6c00, 0xc44bdb6c00)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:808 +0x146 fp=0xc438f4c8b0 sp=0xc438f4c828
github.com/influxdata/influxdb/tsdb/engine/tsm1.newIntegerCursor(0x14f0c2f56859f9b2, 0xc42d9b2d01, 0xc433422000, 0x1af7, 0x1af7, 0xc44bdb6c00, 0xb, 0xc42d9b2d40
)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:779 +0x60 fp=0xc438f4c8f0 sp=0xc438f4c8b0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).buildIntegerCursor(0xc42b8979e0, 0xc421253975, 0x5, 0xc420fcf920, 0x2a, 0xc421253570, 0xb, 0xeb2360, 0
xc42ee17080, 0xf15d90, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2022 +0x20a fp=0xc438f4cb60 sp=0xc438f4c8f0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).buildCursor(0xc42b8979e0, 0xc421253975, 0x5, 0xc420fcf920, 0x2a, 0xc43b25a720, 0xeb2360, 0xc42ee17080,
 0xf15d90, 0x0, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2001 +0x3e7 fp=0xc438f4ccf8 sp=0xc438f4cb60
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefSeriesIterator(0xc42b8979e0, 0xc43b25a720, 0xc421253975, 0x5, 0xc420fcf920, 0x2a, 0xc43d59
c0f0, 0x0, 0x0, 0xf15d90, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1939 +0xa01 fp=0xc438f4db88 sp=0xc438f4ccf8
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetGroupIterators(0xc42b8979e0, 0xc43b25a720, 0xc421253975, 0x5, 0xc431b640e0, 0x1, 0x1, 0xc4
3d59c0f0, 0xc431b64100, 0x1, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1811 +0x2d4 fp=0xc438f4dde0 sp=0xc438f4db88
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators.func1(0xc431b64220, 0xc43bbfc480, 0x1, 0x1, 0xc42b8979e0, 0xc43b25a720, 0xc42125
3975, 0x5, 0xc43d59c0f0, 0xc42b950900, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1766 +0x12c fp=0xc438f4df88 sp=0xc438f4dde0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc438f4df90 sp=0xc438f4df88
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1767 +0x33a
goroutine 1 [chan receive, 2290 minutes]:
main.(*Main).Run(0xc420170980, 0xc420010200, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:98 +0x416
main.main()
        /root/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:46 +0xad
goroutine 17 [syscall, 2290 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
goroutine 5 [syscall, 2290 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41`

__Expected behavior:__ InfluxDB should recover once NFS share is back online

__Actual behavior:__ InfluxDB crashes after NFS issues

**Comment by jwilder** [comment]
NFS is not a supported storage backend for the DB.  You'll likely get crashes and possibly data corruption when using NFS so I would strongly recommend switching to a local SSD.
