### ISSUE TITLE
[Question] how to cache meta data 

### ISSUE THREAD

**Issue by infordb** [influxdata/influxdb#9051]
Hi 
I'm studying the influxdb cluster these days, and I have a few questions

1. How does the data node know meta data(shard group, shard owner) ?
    Does the data node ask the meta node every query?
    If a data node caches meta data, how and when does data node update it?

2. When the replication factor is 2, A particular shard is managed by two data nodes.
    Which data node does the coordinator node request data from?

3. Can I set the read consistency level like cassandra ?
   if impossible , does read consistency level mean one ?

Thanks...

**Comment by timhallinflux** [comment]
working via support.
