### ISSUE TITLE
InfluxQL regex operator =~ requires a space after it but other operators do not

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#9058]
### Bug report

__System info:__ 
InfluxDB shell version: v1.3.6
Mac OS X 10.13

__Steps to reproduce:__

1. run a query with a regex such as `SELECT mean("usage_idle") AS "mean_usage_idle" FROM "telegraf"."autogen"."cpu" WHERE "cpu"=~/cpu0/` and notice that it has a parse error
2. add a space after the regex operator `SELECT mean("usage_idle") AS "mean_usage_idle" FROM "telegraf"."autogen"."cpu" WHERE "cpu"=~ /cpu0/` and notice it succeeds
3. run a query with an equals operator and notice that there is no space `SELECT mean("usage_idle") AS "mean_usage_idle" FROM "telegraf"."autogen"."cpu" WHERE "cpu"='cpu0'` which succeds

__Expected behavior:__ InfluxQL should not require a space after the regex operator

__Actual behavior:__ the query fails to parse unless there is a space following the regex operator

__Additional info:__ none

**Comment by rye** [comment]
I think this was fixed by #4—should this issue be closed?

**Comment by cktang88** [comment]
Yeah I think this should be closed.
