### ISSUE TITLE
error processing shards: could not identify suitable source node

### ISSUE THREAD

**Issue by infordb** [influxdata/influxdb#9061]
System info: 

OS: CentOS Linux 7  

InfluxDB version :
Data Nodes
ID      TCP Address     Version
4       test01:8088  1.3.6-c1.3.6
5       test02:8088  1.3.6-c1.3.6
6       test03:8088  1.3.6-c1.3.6

Meta Nodes
TCP Address     Version
test01:8091  1.3.6-c1.3.6
test02:8091  1.3.6-c1.3.6
test03:8091  1.3.6-c1.3.6

Configuration for cluster version
 - cache-max-memory-size = 10GB
 - replication factor : 2
 - write consistency level : one
 - otherd are default 

I am doing a write only load test.
The odd thing is,  
the single version of influxdb 1.3 handles 400,000 throughputs while the 3node cluster version handles 200,000 throughputs, resulting in the following error.
Are there any important settings I miss?

 
Cluster version error log

Nov  6 13:59:42 test03 influxd: [E] 2017-11-06T04:59:42Z error processing shards: could not identify suitable source node for shard 9, from owners [{6} {4}] service=ae
Nov  6 14:00:12 test03 influxd: [E] 2017-11-06T05:00:12Z error processing shards: could not identify suitable source node for shard 9, from owners [{6} {4}] service=ae
Nov  6 14:00:42 test03 influxd: [E] 2017-11-06T05:00:42Z error processing shards: could not identify suitable source node for shard 9, from owners [{6} {4}] service=ae
Nov  6 14:01:12 test03 influxd: [E] 2017-11-06T05:01:12Z error processing shards: could not identify suitable source node for shard 556, from owners [{6} {4}] service=ae
Nov  6 14:01:43 test03 influxd: [E] 2017-11-06T05:01:43Z error processing shards: could not identify suitable source node for shard 580, from owners [{6} {4}] service=ae
Nov  6 14:02:13 test03 influxd: [E] 2017-11-06T05:02:13Z error processing shards: could not identify suitable source node for shard 580, from owners [{6} {4}] service=ae
Nov  6 14:02:42 test03 influxd: [E] 2017-11-06T05:02:42Z error processing shards: could not identify suitable source node for shard 580, from owners [{6} {4}] service=ae

Cluster version resource usage rate
 - cpu 50% 
 - Memory : 14GB
 - Disk io : 20MB/one second

**Comment by e-dard** [comment]
Hi @infordb. We would love to help you out with this via our Enterprise support system, which you can use by emailing our support team. There could be a number of reasons why you're seeing that throughput, e.g., whether your load balancer is configured correctly or you shard or retention policy durations are appropriate for the cluster. We would be able to help with that via the Enterprise support system.

**Comment by timhallinflux** [comment]
working this via support.
