### ISSUE TITLE
run: create server: mkdir all: mkdir /var/lib/influxdb/meta: permission denied

### ISSUE THREAD

**Issue by karanatree** [influxdata/influxdb#9062]
Hi I'm using official influxdb image (docker pull influxdb)

Could you help me out with the required permission changes?

Thanks

  |  
-- | --
  | 8888888           .d888 888                   8888888b.  888888b.
  | 888            d88P"  888                   888  "Y88b 888  "88b
  | 888            888    888                   888    888 888  .88P
  | 888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
  | 888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
  | 888   888  888 888    888 888  888   X88K   888    888 888    888
  | 888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
  | 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"
  |  
  | [I] 2017-11-06T06:22:40Z InfluxDB starting, version 1.3.7, branch 1.3, commit 2d474a3089bcfce6b472779be9470a1f0ef3d5e4
  | [I] 2017-11-06T06:22:40Z Go version go1.8.4, GOMAXPROCS set to 3
  | [I] 2017-11-06T06:22:40Z Using configuration at: /etc/influxdb/influxdb.conf
  | run: create server: mkdir all: mkdir /var/lib/influxdb/meta: permission denied

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.
