### ISSUE TITLE
SHOW TAG KEYS does not work when default retention policy is empty

### ISSUE THREAD

**Issue by kovetskiy** [influxdata/influxdb#9072]
1. Create database with default retention policy:
```
create database "xxx" with duration 3d replication 1 shard duration 3h name "default"
```
2. Create custom retention policy
```
create retention policy "testrp" on "xxx" duration 2d replication 1 shard duration 2h
```
3. Switch to created database
```
use xxx
```
4. Insert some data into "testrp" retention policy measurement "yyy":
```
insert into "testrp" yyy,tag_foo=1 value_bar=1
```
5. Check that "SHOW TAG KEYS FROM yyy" does not returns data for yyy serie (because retention policy is not specified)
```
show tag keys from "yyy"
```
output is empty, ok.
6. Insert some data to default retention policy:
```
insert into "default" yyy_default,tag_default=1 value_default=1
```
7. Now check that "SHOW TAG KEYS FROM yyy" returns tags from non default retention policy.
```
> show tag keys from "yyy"
name: yyy
tagKey
------
tag_foo
```

Why `SHOW TAG KEYS` does not return data from non-default retention policy when default retention policy is empty?
If `SHOW TAG KEYS` without specifying retention policy works only with default retention policy then why it returns data from non-default retention policy after writing some data into default retention policy?

**Comment by jwilder** [comment]
This is a dup of #7404.
