### ISSUE TITLE
Should be able to query where a column is null

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#908]
For example `select * from foo where col1 = null` should return all the results where col1 doesn't have a value.

**Comment by dandv** [comment]
@pauldix: #454 was closed without explanation. Can we revisit, as either a feature request, or documentation to help those coming from SQL and trying to query for NULLs?

**Comment by pauldix** [comment]
@dandv we should document it. It's a column oriented data store, which means we don't store nulls. This is part of the underlying storage engine implementation and is very unlikely to change.
