### ISSUE TITLE
Unable to start influxd after power failure

### ISSUE THREAD

**Issue by frederikaalund** [influxdata/influxdb#9082]
### Bug report

__System info:__
InfluxDB 1.3.2 (commit 742b9cb3d74ff1be4aff45d69ee7c9ba66c02565)
Go 1.8.3
Buildroot (Linux 4.4.0)
Running on an embedded system (ARM Cortex A9)
Using the Linux binaries for ARM (from https://portal.influxdata.com/downloads)

__Steps to reproduce:__

1. Attempt to start influxd

__Expected behavior:__
influxd should begin running in the background

__Actual behavior:__
influxd returns with the following message:

	 8888888           .d888 888                   8888888b.  888888b.
	   888            d88P"  888                   888  "Y88b 888  "88b
	   888            888    888                   888    888 888  .88P
	   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
	   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
	   888   888  888 888    888 888  888   X88K   888    888 888    888
	   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
	 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

	[I] 2017-11-08T13:46:30Z InfluxDB starting, version 1.3.2, branch 1.3, commit 742b9cb3d74ff1be4aff45d69ee7c9ba66c02565
	[I] 2017-11-08T13:46:30Z Go version go1.8.3, GOMAXPROCS set to 2
	[I] 2017-11-08T13:46:30Z Using configuration at: /opt/etc/influxdb/influxdb.conf
	run: create server: proto: required field "{Unknown}" not set

__Additional info:__

This seems very similar to #274 and #369 that were both closed long ago.

When I recreate the `influxdb` directory, everything works again. 

I think that the root cause of the issue is when the power of abruptly cut from the system. That is, when influxd is not given the chance to shut down gracefully. Somehow, the `influxdb` directory is in an invalid state that influxd can't start from.

Please try with [my broken `influxdb` directory](https://www.dropbox.com/s/nk075b74cubg5p3/influxdb.zip?dl=0). It is only around 12 MB.

I think that a database such as InfluxDB should be able to recover from sudden power failures. Please let me know if you need additional information to fix the issue.

**Comment by jwilder** [comment]
It's failing to load `meta.db` because that file is `0`length now.  That's definitely a bug, and it looks like we might be missing an `fsync` on the meta dir after replacing the file.

What file system and mount options are you using for your `meta` dir?

**Comment by frederikaalund** [comment]
Thanks for looking into this.

> What file system and mount options are you using for your meta dir?

Here is the relevant `fstab` entry

	# <file system>    <mount pt>     <type>   <options>                    <dump> <pass>         
	/dev/mmcblk0p1     /opt           vfat     ro,defaults                  0      0

The `meta` directory is at `/opt/var/influxdb/meta`. It's FAT32 (I know that it is ancient).

**Comment by jwilder** [comment]
That _might_ be part of the of the problem as well.  Any chance you can switch that `ext4`?

**Comment by frederikaalund** [comment]
> That might be part of the of the problem as well.

I feared that it might. We are using FAT32 due to compatibility issues.

> Any chance you can switch that ext4?

I can try that with a development build, sure. Though I won't have time to do so this week.

**Comment by frederikaalund** [comment]
For the record, we switched to ext4 and saw no issues with influxd on that file system.
