### ISSUE TITLE
How to Use Literal Character Strings in InfluxQL SELECT

### ISSUE THREAD

**Issue by zlq4863947** [influxdata/influxdb#9088]
__System info:__ macOS Sierra 10.12, InfluxDB 1.3.5

__Steps to reproduce:__

1. Create measurement And Insert data
```
 > insert test,mode=1 uuid="d79df0c0-c52a-11e7-929e-83a8856009b0" 
 > insert test,mode=1 uuid="d79df0c0-c52a-11e7-929e-83a8856009b0"
```

__Expected behavior:__  
I want to put the “5min” fixed string into result set.

```
> select uuid, "5min" as unit from test
name: test
time                uuid                                 unit
----                ----                                 ----
1510279506236603945 d79df0c0-c52a-11e7-929e-83a8856009b0 5min
1510279507204696343 d79df0c0-c52a-11e7-929e-83a8856009b0 5min
```

__Actual behavior:__ 
But influxdb didn't put in 5min to result set

```
> select uuid, "5min" as unit from test
name: test
time                uuid                                 unit
----                ----                                 ----
1510279506236603945 d79df0c0-c52a-11e7-929e-83a8856009b0 
1510279507204696343 d79df0c0-c52a-11e7-929e-83a8856009b0 
```

**Comment by jsternberg** [comment]
I'm not entirely certain of the use case here. So you want to put a literal that you specify into the response?

If you can explain the use case, maybe I would understand what you want and why better.

**Comment by alanjcastonguay** [comment]
@jsternberg  I was hoping to do something like the above in conjunction with `SELECT ... INTO`, to set a tag (eg the device that the sensor is attached to) that wasn't known at the time of the original ingestion. (And leaving out the `import_job` field at the same time.)

**Comment by antonbayer** [comment]
I have more or less the same use case: setting a tag in a continuous query.

**Comment by aspring** [comment]
I have a similar need -- my use case is using the functionality to add annotation data to the result -- this specifically is for Grafana annotations.
 
Doing something like this would remove the need for a CQ:

```
SELECT "host" as "tags", "state_candidate", "Election Started" as "title" FROM "consul_raft" WHERE $timeFilter
```

**Comment by memetb** [comment]
Same need. 

For instance: Grafana has annotation queries that take "title" and "description" fields. It makes no sense to store a UI string in the database as a tag.

**Comment by palmerabollo** [comment]
It's also useful in [node-red](https://flows.nodered.org/node/node-red-contrib-influxdb), to join the results from two different influxdb queries and still be able to distinguish each one.

**Comment by robie2011** [comment]
same need. 

I like to reduce the output of a field value to specific range. E.g. 0 or 1. So I tried SQL-Style-Like `min(fieldname, 1)` but it didn't work.

**Comment by MarkusBe** [comment]
Same need here. I need this for Grafana-Annotations.

**Comment by timhallinflux** [comment]
Possible today with Flux technical preview with 1.7.  Should be supported for production workloads with 1.8 -- Flux GA.

**Comment by elhenro** [comment]
@timhallinflux Can please describe how this is possible?

**Comment by rawadrifai** [comment]
@timhallinflux ?

**Comment by timhallinflux** [comment]
Here's an example in Flux, using the `map()` function:
https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/map/#add-new-columns-and-preserve-existing-columns

if you are using 1.x, the same example is described here: https://docs.influxdata.com/flux/v0.65/stdlib/built-in/transformations/map#sidebar



This allows you to dynamically add these columns on the fly.  It does NOT store the new columns into the DB.  

Does that help?

**Comment by timhallinflux** [comment]
Another, slightly different example... I want to inject some additional dynamic data into the result set.  In this case, I'm trying to put a "wildcard" value into a list of tags.  In my case, I have a set of tags for the devices I'm monitoring.  I want a dashboard that allows me to see all the hosts in aggregate, but also drill-down into specific devices.   In this case I use `union()` and dynamically add the tag like this:
```import "influxdata/influxdb/v1"
import "csv"

hosts = v1.tagValues(
  bucket: "default",
  tag: "host",
  start: -72h
)

wildcard = csv.from(csv: "
#datatype,string,long,string
#group,false,true,false
#default,,,
,result,table,_value
,,0,*
")

union(tables: [hosts,wildcard])```

Then, in my dashboard queries, I use conditional logic to alter the filters.  Here's an example:

```
rom(bucket: v.bucket)
  |> range(start: v.timeRangeStart)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> filter(fn: (r) => r._field == "usage_user" or r._field == "usage_system" or r._field == "usage_idle")
  |> filter(fn: (r) => 
    if v.host != "*" 
      then r.cpu == "cpu-total" and r.host == v.host
      else r.cpu == "cpu-total")
  |> window(period: v.windowPeriod)
  |> mean()
  |> group(columns: ["_value", "_time", "_start", "_stop"], mode: "except")
  |> yield(name: "mean")
```

**Comment by timhallinflux** [comment]
Using InfluxDB 2.0, along with Flux Tasks, I believe you could add the literals back into the DB by using the `map()` example.  In this case you would use the `to()` function to write the resulting data back into the measurement using the same timestamps and other tag keys.  Since InfluxDB is an append only system, it will overwrite the existing points (same timestamps and tag keys) with the new fields.  

At the moment, there is no `to()` function in the 1.x version of Flux.  This is being considered for a future 1.x release here: https://github.com/influxdata/influxdb/issues/17790
