### ISSUE TITLE
points beyond retention policy !! what does this mean??

### ISSUE THREAD

**Issue by 756445638** [influxdata/influxdb#9093]
/inflxud has this output

2017-11-13T06:28:54Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=44 service=udp
[I] 2017-11-13T06:28:55Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:28:57Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:28:58Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=44 service=udp
[I] 2017-11-13T06:28:59Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:00Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:02Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:03Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=44 service=udp
[I] 2017-11-13T06:29:04Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:06Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=44 service=udp
[I] 2017-11-13T06:29:07Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:09Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=44 service=udp
[I] 2017-11-13T06:29:10Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:12Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:13Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=44 service=udp
[I] 2017-11-13T06:29:14Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:15Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:17Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:18Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=44 service=udp
[I] 2017-11-13T06:29:19Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:21Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:22Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=44 service=udp
[I] 2017-11-13T06:29:23Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:24Z failed to write point batch to database "udp": partial write: points beyond retention policy dropped=22 service=udp
[I] 2017-11-13T06:29:25Z failed to write point batch to database "udp": partial write: points beyond retention policy

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

In this specific case it means that you're trying to write a point to a retention policy that has a timestamp that's so old, that the retention policy would have immediately scrubbed it from the database. For example, if your retention policy is 6 months (keep data for 6 months then delete it), and you try to add a point with a timestamp that's 8 months in the past, then you would see this error.

Thanks.

**Comment by 756445638** [comment]
thanks

**Comment by chench00** [comment]
@e-dard I understand this is not the best place for troubleshooting but I am facing the same problem when using a few telegraf input plugins to send data to influx:

    2023-01-25T23:40:08Z E! [outputs.influxdb] E! [outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: points beyond retention policy dropped=1

I am trying to figure out how to view this old data in order to pinpoint the culprit. Everything is working and all my dashboards in Grafana are functioning properly but would love to make these messages go away.
