### ISSUE TITLE
Case conversion of influxdb output.

### ISSUE THREAD

**Issue by Himanshu-pupneja** [influxdata/influxdb#9094]
Is there any way to convert influxdb output to lower/upper case? may be from regex or any inbuilt function, something like that.

For example:
show tag values from measurement_name with key in (key1) where status = 'xyz'

I need the above query output in upper case. That will be great if anyone can help.

Thanks in advance!!

-Himanshu

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

The short answer is no, we don't currently have any text conversion functions like that.

Thanks.
