### ISSUE TITLE
Homebrew not finding v1.4.0 branch

### ISSUE THREAD

**Issue by pastaman-lg** [influxdata/influxdb#9097]
Hello I am trying to install influxdb on OS X via homebrew, but it can't find the remote branch:

> $ brew install influxdb
==> Cloning https://github.com/influxdata/influxdb.git
Cloning into '/Users/myuser/Library/Caches/Homebrew/influxdb--git'...
warning: Could not find remote branch v1.4.0 to clone.
fatal: Remote branch v1.4.0 not found in upstream origin
Error: Failed to download resource "influxdb"

**Comment by mark-rushakoff** [comment]
1.4.1 will be available soon, see https://github.com/influxdata/influxdb/issues/9107.

**Comment by ilovezfs** [comment]
1.4.1 has now shipped
