### ISSUE TITLE
Current version?

### ISSUE THREAD

**Issue by ilovezfs** [influxdata/influxdb#9107]
In Homebrew, I shipped v1.4.0 on Wed Nov 8 22:07:58 2017 -0800 (https://github.com/Homebrew/homebrew-core/pull/20440)

At that time the git commit revision was 0614ebb1d1b0bf0523a88196fbf270e14cb21acb

At some point the v1.4.0 tag was deleted here, which was then reported to Homebrew:
https://github.com/Homebrew/homebrew-core/pull/20440#issuecomment-343243638

Now a v1.4.0 tag has reappeared but with a different git commit revision: 0993cb4cd2714c70ad85e9038b45f011e37a22e4

I see there is also a new v1.4.1 tag with the git commit revision 882ce8753d52d04a92c01758d8efcfe5c37bd93a

What is the current stable version? 1.4.0? 1.4.1? Or something else?

https://portal.influxdata.com/downloads lists 1.3.7 so I'm not sure if we should force downgrade people to 1.3.7 (hopefully not), or upgrade them to the new 1.4.0 (hopefully not), or upgrade them to the new 1.4.1 (hopefully this, assuming the tag is going to continue to exist).

CC @jwilder

**Comment by mark-rushakoff** [comment]
The current stable version is 1.4.1. There will be a release announcement tomorrow (Nov 14).

1.4.0 was tagged erroneously last week, and we chose to delete the tag. It was live for approximately 15 hours, mostly overnight in US time.

Today's 1.4.0 tag was intended to be complete, but following Murphy's Law, we found out it was missing one piece of functionality for tomorrow's release announcement, so we had to immediately follow up with 1.4.1.

**Comment by ilovezfs** [comment]
Thanks @mark-rushakoff 

I'll wait for tomorrow's announcement and then ship 1.4.1

>It was live for approximately 15 hours, mostly overnight in US time.

It's likely to be picked up by our livechecks in even half that time, or less.

You may also want to use explicit GitHub releases, not just tags (GUI https://help.github.com/articles/creating-releases/ or API https://developer.github.com/v3/repos/releases/#create-a-release), though if you do go that route be sure to do it consistently every release, otherwise https://github.com/influxdata/influxdb/releases/latest will end up pointed at something old. We always try to honor explicit releases over mere tags when there is a tag with a newer version number but it hasn't been marked as an explicit release yet.

**Comment by ilovezfs** [comment]
I just noticed that https://github.com/influxdata/influxdb/releases/latest is in fact pointed at a very old release currently, which is the situation I was describing. If you're not going to use explicit releases going forward, I'd suggest deleting

https://github.com/influxdata/influxdb/releases/tag/v1.0.0-rc1
and
https://github.com/influxdata/influxdb/releases/tag/v1.1.0

Deleting the release won't disrupt the underlying tag. It'll just make sure https://github.com/influxdata/influxdb/releases/latest isn't telling lies.

Alternatively, you could mark 1.4.1 as an explicit release and use the explicit releases going forward.

**Comment by mark-rushakoff** [comment]
@ilovezfs the announcement is live: https://www.influxdata.com/blog/whats-new-influxdb-oss-1-4/

We haven't yet made a decision on what we'll do with regard to GitHub releases.

**Comment by ilovezfs** [comment]
Thanks @mark-rushakoff! OK, I've shipped 1.4.1 https://github.com/Homebrew/homebrew-core/pull/20609

**Comment by xPaw** [comment]
@mark-rushakoff Sorry to bother if this is not the right place, but Debian packages were not updated with v1.4 release.

 https://repos.influxdata.com/debian still has v1.3 packages.

**Comment by goller** [comment]
Hey @xPaw repos is now up-to-date!
