### ISSUE TITLE
How to do mathematical operations on one field with different WHERE filter

### ISSUE THREAD

**Issue by geraybos** [influxdata/influxdb#9110]
for example, temperature data from two different locations stored in one measurement, like

```
time                temperature               location
----                ----                              ----
1                     15                                 A
2                     20                                 B
3                     17                                 A
4                     18                                 B
```

How to calculate the difference between temperatures at A and B with querying? 
i.e.  expecting something like "SELECT a.temperature - b.temperature FROM measurement WHERE location = 'A' as a WHERE location = 'B' as b"

Thanks

**Comment by jsternberg** [comment]
This question is better for the community site at https://community.influxdata.com. The issue tracker on GitHub is only for bugs and feature requests. Thanks.
