### ISSUE TITLE
Not able to install influxdb

### ISSUE THREAD

**Issue by Sanjayfmc** [influxdata/influxdb#9112]
I am installing influxdb in MAC 10.10.5. I have downloaded influxdb--git in my machine but when I hit the command brew install influxdb getting below. 

z00405348-mac:Homebrew sanjaykumaradmin$ brew install influxdb
==> Cloning https://github.com/influxdata/influxdb.git
Updating /Users/sanjaykumaradmin/Library/Caches/Homebrew/influxdb--git
==> Checking out tag v1.4.0
Error: v1.4.0 tag should be 0614ebb1d1b0bf0523a88196fbf270e14cb21acb
but is actually 0993cb4cd2714c70ad85e9038b45f011e37a22e4
z00405348-mac:Homebrew sanjaykumaradmin$ 

Can you please let me know why I am facing this challenges.

Error: v1.4.0 tag should be 0614ebb1d1b0bf0523a88196fbf270e14cb21acb
but is actually 0993cb4cd2714c70ad85e9038b45f011e37a22e4

**Comment by mark-rushakoff** [comment]
1.4.1 will be available soon, see https://github.com/influxdata/influxdb/issues/9107.

**Comment by Sanjayfmc** [comment]
Thanks so much for the update,

Can you please inform me once 1.4.1 is available to download?

Thanks,
Sanjay

**Comment by ilovezfs** [comment]
it is now
