### ISSUE TITLE
InfluxDB 1.3.7 issue enabling http authentication on Windows

### ISSUE THREAD

**Issue by ZachHerridge** [influxdata/influxdb#9113]
I am unable to get authentication to enable on Windows.

I’ve downloaded a fresh version of influxDB
Then I create a admin user with the command CREATE USER WITH PASSWORD ‘’ WITH ALL PRIVILEGES
I open the config file and change the [http] section to as follows
[http] enabled = true
bind-address = ":8086"
auth-enabled = true # :sparkles:
log-enabled = true
write-tracing = false
pprof-enabled = false
https-enabled = false
https-certificate = “/etc/ssl/influxdb.pem”

Then after restarting InfluxDB the console shows “Authentication enabled:false service=httpd” and authentication does not work.

**Comment by jsternberg** [comment]
Can you show me the commands you are running and the logs from each run of `influxd`?

**Comment by ZachHerridge** [comment]
Here the logs for the initial startup, creating the user, showing the users, and restarting the db. 

8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

[I] 2017-11-15T21:39:49Z InfluxDB starting, version 1.4.1, branch 1.4, commit 882ce8753d52d04a92c01758d8efcfe5c37bd93a
[I] 2017-11-15T21:39:49Z Go version go1.9.2, GOMAXPROCS set to 8
[I] 2017-11-15T21:39:49Z no configuration provided, using default settings
[I] 2017-11-15T21:39:49Z Using data dir: C:\Users\zgh\.influxdb\data service=store
[I] 2017-11-15T21:39:49Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\1\_00001.wal, size 33977 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:39:49Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\1\_00002.wal, size 266375 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:39:49Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\1\_00003.wal, size 39747 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:39:49Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\1\_00004.wal, size 17748 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:39:49Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\1\_00005.wal, size 0 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:39:49Z C:\Users\zgh\.influxdb\data\_internal\monitor\1 opened in 95.1082ms service=store
[I] 2017-11-15T21:39:49Z opened service service=subscriber
[I] 2017-11-15T21:39:49Z Starting monitor system service=monitor
[I] 2017-11-15T21:39:49Z 'build' registered for diagnostics monitoring service=monitor
[I] 2017-11-15T21:39:49Z 'runtime' registered for diagnostics monitoring service=monitor
[I] 2017-11-15T21:39:49Z 'network' registered for diagnostics monitoring service=monitor
[I] 2017-11-15T21:39:49Z 'system' registered for diagnostics monitoring service=monitor
[I] 2017-11-15T21:39:49Z Starting precreation service with check interval of 10m0s, advance period of 30m0s service=shard-precreation
[I] 2017-11-15T21:39:49Z Starting snapshot service service=snapshot
[I] 2017-11-15T21:39:49Z Starting continuous query service service=continuous_querier
[I] 2017-11-15T21:39:49Z Storing statistics in database '_internal' retention policy 'monitor', at interval 10s service=monitor
[I] 2017-11-15T21:39:49Z Starting HTTP service service=httpd
[I] 2017-11-15T21:39:49Z Authentication enabled:false service=httpd
[I] 2017-11-15T21:39:49Z Listening on HTTP:[::]:8086 service=httpd
[I] 2017-11-15T21:39:49Z Starting retention policy enforcement service with check interval of 30m0s service=retention
[I] 2017-11-15T21:39:49Z Listening for signals
[I] 2017-11-15T21:39:49Z Sending usage statistics to usage.influxdata.com


CREATE USER zach WITH PASSWORD ‘123123’ WITH ALL PRIVILEGES

Connected to http://localhost:8086 version 1.4.1
InfluxDB shell version: 1.4.1
> show users
user admin
---- -----
root true
zach true
There was an error writing history file: open : The system cannot find the file specified.
>


 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

[I] 2017-11-15T21:45:40Z InfluxDB starting, version 1.4.1, branch 1.4, commit 882ce8753d52d04a92c01758d8efcfe5c37bd93a
[I] 2017-11-15T21:45:40Z Go version go1.9.2, GOMAXPROCS set to 8
[I] 2017-11-15T21:45:40Z no configuration provided, using default settings
[I] 2017-11-15T21:45:40Z Using data dir: C:\Users\zgh\.influxdb\data service=store
[I] 2017-11-15T21:45:40Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\2\_00001.wal, size 113801 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:45:40Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\1\_00001.wal, size 33977 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:45:40Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\1\_00002.wal, size 266375 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:45:40Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\2\_00002.wal, size 0 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:45:40Z C:\Users\zgh\.influxdb\data\_internal\monitor\2 opened in 37.0251ms service=store
[I] 2017-11-15T21:45:40Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\1\_00003.wal, size 39747 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:45:40Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\1\_00004.wal, size 17748 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:45:40Z reading file C:\Users\zgh\.influxdb\wal\_internal\monitor\1\_00006.wal, size 0 engine=tsm1 service=cacheloader
[I] 2017-11-15T21:45:40Z C:\Users\zgh\.influxdb\data\_internal\monitor\1 opened in 78.0609ms service=store
[I] 2017-11-15T21:45:40Z opened service service=subscriber
[I] 2017-11-15T21:45:40Z Starting monitor system service=monitor
[I] 2017-11-15T21:45:40Z 'build' registered for diagnostics monitoring service=monitor
[I] 2017-11-15T21:45:40Z 'runtime' registered for diagnostics monitoring service=monitor
[I] 2017-11-15T21:45:40Z 'network' registered for diagnostics monitoring service=monitor
[I] 2017-11-15T21:45:40Z 'system' registered for diagnostics monitoring service=monitor
[I] 2017-11-15T21:45:40Z Starting precreation service with check interval of 10m0s, advance period of 30m0s service=shard-precreation
[I] 2017-11-15T21:45:40Z Starting snapshot service service=snapshot
[I] 2017-11-15T21:45:40Z Storing statistics in database '_internal' retention policy 'monitor', at interval 10s service=monitor
[I] 2017-11-15T21:45:40Z Starting continuous query service service=continuous_querier
[I] 2017-11-15T21:45:40Z Starting HTTP service service=httpd
[I] 2017-11-15T21:45:40Z Authentication enabled:false service=httpd
[I] 2017-11-15T21:45:40Z Listening on HTTP:[::]:8086 service=httpd
[I] 2017-11-15T21:45:40Z Starting retention policy enforcement service with check interval of 30m0s service=retention
[I] 2017-11-15T21:45:40Z Listening for signals
[I] 2017-11-15T21:45:40Z Sending usage statistics to usage.influxdata.com

**Comment by jsternberg** [comment]
I see this:

```
[I] 2017-11-15T21:45:40Z Go version go1.9.2, GOMAXPROCS set to 8
[I] 2017-11-15T21:45:40Z no configuration provided, using default settings
[I] 2017-11-15T21:45:40Z Using data dir: C:\Users\zgh.influxdb\data service=store
```

Are you specifying the configuration file with `-config`? The default has authentication disabled. You can also try setting `INFLUXDB_HTTP_AUTH_ENABLED=true`.

**Comment by ZachHerridge** [comment]
Setting the config manually worked, thanks a lot!
