### ISSUE TITLE
Feature request: migrate collectd multiple measurements to single

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#9121]
With the introduction of parse-multivalue-plugin in 1.4.1 it is possible to for influxdb to use a single measurement where as in 1.3, it required multiple.

If I enable  parse-multivalue-plugin today, then data is split.

I need a way to migrate old data to this new method.

**Comment by dgnorton** [comment]
@yellowpattern one way to do this is with `SELECT ... INTO` queries. E.g., If you have two measurements `m_a` and `m_b` with one field `v` each...
```
> select * from /m_.*/
name: m_a
time                           v
----                           -
1970-01-01T00:00:00Z           1
1970-01-01T00:00:00.000000001Z 2
1970-01-01T00:00:00.000000002Z 3
name: m_b
time                           v
----                           -
1970-01-01T00:00:00Z           4
1970-01-01T00:00:00.000000001Z 5
1970-01-01T00:00:00.000000002Z 6
```
They could be combined into a single measurement `m` with two fields `a` and `b` with a couple `SELECT ... INTO`s...
```
> select v as a into foo.autogen.m from m_a
> select v as b into foo.autogen.m from m_b
```
Which would then look like...
```
> select * from m
name: m
time                           a b
----                           - -
1970-01-01T00:00:00Z           1 4
1970-01-01T00:00:00.000000001Z 2 5
1970-01-01T00:00:00.000000002Z 3 6
```

**Comment by russorat** [comment]
closing due to lack of response.
