### ISSUE TITLE
Not able to increase data ingestion rate

### ISSUE THREAD

**Issue by akansal1** [influxdata/influxdb#9135]
I am using Latest version of Influx on my system

I am converting data in nearly 300 nearly to Influx, data in files ranges between 2-5 years, sampled at 1Min interval, with 5-20 columns each.

I am using a 4 Core, 16 GB RAM machine with SSD

- I am not able to get data ingestion rate above 10k points per second with batch size less than 5K.
- If I try to increase the data ingestion rate, memory consumption increases drastically
- On looking further, I noticed that Kapacitor is causing increase in memory consumption
- On Stop Kapacitor, I am not facing any memory overflow issue irrespective of my ingestion rate
- I am still now able to increase ingestion rate

I am using influxdb-python client for ingestion

Any help in any direction will help

Thanks

**Comment by jwilder** [comment]
For that range of time that you are backfilling, you may want to bump up the shard duration to greater than 1 week to reduce the number of shards you have.  1-3 months might be better.  If that data is never going to be removed, even as high as 1 year would be good.  You'll also need to lower the `cache-snapshot-write-cold-duration = "10s"` config option to force cache snapshotting more frequently than the defaults.

This [FAQ](https://docs.influxdata.com/influxdb/v1.3/troubleshooting/frequently-asked-questions/#what-are-the-configuration-recommendations-and-schema-guidelines-for-writing-sparse-historical-data) has other suggestions about config and schema design.

For writing data, you you should have separate threads/processes writing in parallel as well.  With four cores, you will likely saturate them with a modest amount of parallelism.

If you grab some profiles (`curl -o profiles.tar.gz http://localhost:8086/debug/pprof/all`), that would also help see what's going on.
