### ISSUE TITLE
how can i build release packages?

### ISSUE THREAD

**Issue by lfarkas** [influxdata/influxdb#9139]
Is there any documentation how do you build a given release ie. those files which are at https://portal.influxdata.com/downloads ?
I'd like to run influxdb on siemens iot2000. unfortunately this is an intel Quark SoC X1000 which is not able to run your 32 bit build ie: https://dl.influxdata.com/influxdb/releases/influxdb-1.4.2_linux_i386.tar.gz since this cpu has not mmx support. os I'd like to rebuild the package but at the end I' like to get a similar tar.gz. how can i do that?
what is th command i'd have to run?
currently based on this file Dockerfile I able to build with
```
RUN go get -u github.com/sparrc/gdm
COPY Godeps /go/src/github.com/influxdata/influxdb/Godeps
WORKDIR /go/src/github.com/influxdata/influxdb
RUN gdm restore
COPY . /go/src/github.com/influxdata/influxdb
RUN go install ./cmd/...
```
but after this if i try something like this:
```
./build.py --package --branch=1.3 --version=1.3.7
```
but this use the master branch and i'd like to build exactly the same source and result as the released versions.
How can i do so? it's be useful to document it:-)
Thanks

**Comment by mark-rushakoff** [comment]
The build.py tooling is deprecated and will be removed in the future.

We're currently building the releases through the scripts in the `releng` folder.

Run `./releng/source-tarball/build.bash` to generate a source tarball, then pass that output to `./releng/raw-binaries/build.bash` to generate the full set of binaries. Running either script with `-h` will output the full set of required inputs.

It's unlikely that we will formally document this process in much more detail than what I've described here. There is low external demand for building _releases_ from source, and maintaining the documentation increases the friction involved with updates on our end.

**Comment by lfarkas** [comment]
but there is no releng in other packages (telegraf, kapacitor...) so it can not be do the same way in other packages:-(
