### ISSUE TITLE
Accept negative regular expression in SHOW MEASUREMENTS

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#9140]
`SHOW MEASUREMENTS WITH MEASUREMENT =~ /a/` works as intended, but `SHOW MEASUREMENTS WITH MEASUREMENT !~ /a/` fails with `{"error":"error parsing query: found !~, expected =, =~ at line 1, char 36"}`.

The parser should allow a negative regular expression in that context.

**Comment by benjaminsirb** [comment]
Is there any update on this issue?

**Comment by mark-rushakoff** [comment]
AFAIK this is still an outstanding issue.
