### ISSUE TITLE
Group by no longer supports now() as offset_interval

### ISSUE THREAD

**Issue by jurom** [influxdata/influxdb#9142]
### Bug report

This used to work in version 1.3.7, and I'm not sure if it was removed deliberately, or by accident (it was not mentioned in the [CHANGELOG] )(https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md)

__System info:__ InfluxDB version 1.4.2, 

__Steps to reproduce:__ Any query with offset in grouping by time set to `now()`:

```
SELECT sum(amount) FROM payments WHERE time > now() - 2w AND time < now() GROUP BY time(1d, now())
```

__Expected behavior:__ Results grouped by days, offset to current time.

__Actual behavior:__  `ERR: invalid time dimension offset: now()`

**Comment by tux-00** [comment]
Same here.

I run two instances of InfluxDB (version 1.4.2 on both) one is Debian 9.3 and the other is Debian 9.1.
The instance on Debian 9.1 is working with group by including now() the other is not.
Each instance collect different data.

**Comment by ainguyen** [comment]
+1

**Comment by jsternberg** [comment]
This was not intentional. I'm sorry this took so long for me to see. I'll look into this so we can restore this functionality.

**Comment by tux-00** [comment]
@jsternberg Any news on this issue ?

**Comment by vmironenko** [comment]
+1

**Comment by jsternberg** [comment]
This is being backported for 1.5.2. We will unfortunately not be backporting this to the 1.4.x series.

Backport PR is #9651.
