### ISSUE TITLE
Query regression: allow multiple count(distinct()) aggregates

### ISSUE THREAD

**Issue by rbetts** [influxdata/influxdb#9144]
function distinct() cannot be combined with other functions

[I] 2017-11-21T15:50:00Z SELECT count(distinct(a_f)) AS a, count(distinct(b_f)) AS b INTO blah FROM baz WHERE type = 'u' OR type = 'c' OR type = 'd'  AND time >= '2017-11-21T15:45:00Z' AND time < '2017-11-21T15:50:00Z' GROUP BY time(5m) service=query 
[I] 2017-11-21T15:50:00Z error: aggregate function distinct() cannot be combined with other functions or fields.

**Comment by Codelica** [comment]
Sorry to revive a closed issue, but we have a lot of queries that I believe are being affected by this.  Just curious if there is an ETA for 1.4.3, which I assume includes the fix?  Will it be pending a fix for #9134 ?

Again, sorry to ask, but I just haven't been able to think through a workaround for our counts.

**Comment by larrywalker** [comment]
I had to down rev to 1.3.6 because this broke several of our continuous queries that had distinct(count(field)) in them.  The queries won't run in 1.4.

Waiting for this one to get merged into 1.4.3 before I try again.

**Comment by jsternberg** [comment]
This has been backported to 1.4 and will be in 1.4.3.

**Comment by kjschnei001** [comment]
@jsternberg Unfortunately, this still seems to be affecting us in 1.4.3:
```
Connected to https://team.metricstore.business.com:8084 version 1.4.3
InfluxDB shell version: 1.4.3
> SELECT difference(distinct("_exCompleted")) FROM "camel_routes" WHERE ("domain" = 'goose' AND "env" =~ /^stage$/ AND "role" = 'transform' AND "route" = 'SomeRoute') AND time >= now() - 3h GROUP BY time(1m), "host", "route" fill(null)
ERR: aggregate function distinct() cannot be combined with other functions or fields
```
