### ISSUE TITLE
Client - Allow path in address

### ISSUE THREAD

**Issue by genofire** [influxdata/influxdb#9154]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

__Steps to reproduce:__
https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/v2/client.go#L26
With a `Addr` like `https://example.org/influxdb/` like behind a proxy server or so

__Expected behavior:__ [What you expected to happen]
concat path with e.g. `ping`.

__Actual behavior:__ [What actually happened]
override path with e.g. `ping`.

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/v2/client.go#L123

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/v2/client.go#L370

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/v2/client.go#L476

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/influxdb.go#L191

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/influxdb.go#L267

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/influxdb.go#L345

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/influxdb.go#L391

**Comment by easyrasta** [comment]
+1: same problem
