### ISSUE TITLE
Tag key cardinality not functioning in `tsi1` index

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#9157]
The `monitor` service regularly asks each shard to check for each of its measurements' tag keys, the current cardinality of all the tag values under that key. If the cardinality exceeds the `max-values-per-tag` in the `[data]` section of the config. 

This means users won't see the following log lines when the limit is nearing:

```
WARN: 80% of max-values-per-tag limit exceeded: (x/y), db=db0 measurement=cpu tag=host
```

We need to decide if we need to support `max-values-per-tag` under `tsi1` or not. It's reasonable that the index shouldn't need to be concerned with the cardinality of tag values, since it's designed for handling high cardinalities, however, omitting support for this would mean the `tsi1` index differed from the `inmem` index with respect to that setting.

**Comment by jwilder** [comment]
The limit should only apply to inmem.  We decided this several months ago during initial tsi dev work.

**Comment by e-dard** [comment]
@jwilder SGTM, in that case we just need to make sure we add some documentation to the release notes for TSI. I'm going to keep this open until that's done.
