### ISSUE TITLE
DELETE doesn't delete fresh data

### ISSUE THREAD

**Issue by lsitzmann** [influxdata/influxdb#9161]
__System info:__ I tried 1.4.0, 1.4.1 and 1.4.2 on debian linux. I'm _not_ able to reproduce it on 1.3.7

__Steps to reproduce:__

We have a unit test that does the following steps:

1. Clean our test-database (drop database and create database)
2. Insert some data
3. Delete some of the data
4. Query for the deleted data

__Expected behavior:__ The deleted data should not be in the result of step 4.

__Actual behavior:__ Until 1.3.7 it worked as expected. Since 1.4.0 some of the deleted data is retuned by the result of step 4, which makes our test red.

__Additional info:__ 
We thought it might be a timing problem, but even if we add a sleep of 10 seconds between step 2 and 3 AND between step 3 and 4 we can easily reproduce the problem.

Below is the log-output of the influxdb service during our test:
```
Nov 27 17:20:51.310521 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z DROP DATABASE TSM service=query
Nov 27 17:20:51.312877 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=DROP+DATABASE+TSM&u=+ HTTP/1.1" 200 171 "-" "InfluxData.Net.InfluxDb" ef6246ed-d38e-11e7-80d6-000000000000 2516
Nov 27 17:20:51.315628 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z CREATE DATABASE TSM service=query
Nov 27 17:20:51.317332 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=CREATE+DATABASE+TSM&u=+ HTTP/1.1" 200 173 "-" "InfluxData.Net.InfluxDb" ef630643-d38e-11e7-80d7-000000000000 2100
Nov 27 17:20:51.321191 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=DROP+MEASUREMENT+tsm_meta_rp.tsm_data&u=+ HTTP/1.1" 400 72 "-" "InfluxData.Net.InfluxDb" ef63ddd7-d38e-11e7-80d8-000000000000 89
Nov 27 17:20:51.332277 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z DROP MEASUREMENT tsm_typical_data_age service=query
Nov 27 17:20:51.332390 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=DROP+MEASUREMENT+%22tsm_typical_data_age%22&u=+ HTTP/1.1" 200 191 "-" "InfluxData.Net.InfluxDb" ef659388-d38e-11e7-80d9-000000000000 339
Nov 27 17:20:51.354930 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z CREATE RETENTION POLICY tsm_meta_rp ON TSM DURATION 0s REPLICATION 1 service=query
Nov 27 17:20:51.357041 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?p=%5BREDACTED%5D&q=CREATE+RETENTION+POLICY+tsm_meta_rp+ON+TSM+DURATION+inf+REPLICATION+1&u=+ HTTP/1.1" 200 222 "-" "InfluxData.Net.InfluxDb" ef690abd-d38e-11e7-80da-000000000000 2320
Nov 27 17:20:51.359788 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z SHOW RETENTION POLICIES ON TSM service=query
Nov 27 17:20:51.359918 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=SHOW+RETENTION+POLICIES+ON+TSM&u=+ HTTP/1.1" 200 204 "-" "InfluxData.Net.InfluxDb" ef69c719-d38e-11e7-80db-000000000000 260
Nov 27 17:20:51.362819 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z SHOW RETENTION POLICIES ON TSM service=query
Nov 27 17:20:51.362953 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=SHOW+RETENTION+POLICIES+ON+TSM&u=+ HTTP/1.1" 200 204 "-" "InfluxData.Net.InfluxDb" ef6a3c05-d38e-11e7-80dc-000000000000 268
Nov 27 17:20:51.373083 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z SHOW RETENTION POLICIES ON TSM service=query
Nov 27 17:20:51.373283 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=SHOW+RETENTION+POLICIES+ON+TSM&u=+ HTTP/1.1" 200 204 "-" "InfluxData.Net.InfluxDb" ef6bc835-d38e-11e7-80dd-000000000000 334
Nov 27 17:20:51.375442 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z DROP DATABASE TSM service=query
Nov 27 17:20:51.377294 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=DROP+DATABASE+TSM&u=+ HTTP/1.1" 200 171 "-" "InfluxData.Net.InfluxDb" ef6c2c68-d38e-11e7-80de-000000000000 1949
Nov 27 17:20:51.379727 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z CREATE DATABASE TSM service=query
Nov 27 17:20:51.381461 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=CREATE+DATABASE+TSM&u=+ HTTP/1.1" 200 173 "-" "InfluxData.Net.InfluxDb" ef6cd1cb-d38e-11e7-80df-000000000000 1985
Nov 27 17:20:51.383868 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=DROP+MEASUREMENT+tsm_meta_rp.tsm_data&u=+ HTTP/1.1" 400 72 "-" "InfluxData.Net.InfluxDb" ef6d79d0-d38e-11e7-80e0-000000000000 73
Nov 27 17:20:51.386617 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z DROP MEASUREMENT tsm_typical_data_age service=query
Nov 27 17:20:51.386759 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=DROP+MEASUREMENT+%22tsm_typical_data_age%22&u=+ HTTP/1.1" 200 191 "-" "InfluxData.Net.InfluxDb" ef6dd893-d38e-11e7-80e1-000000000000 336
Nov 27 17:20:51.409606 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z CREATE RETENTION POLICY tsm_meta_rp ON TSM DURATION 0s REPLICATION 1 service=query
Nov 27 17:20:51.411274 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?p=%5BREDACTED%5D&q=CREATE+RETENTION+POLICY+tsm_meta_rp+ON+TSM+DURATION+inf+REPLICATION+1&u=+ HTTP/1.1" 200 222 "-" "InfluxData.Net.InfluxDb" ef715e4c-d38e-11e7-80e2-000000000000 2056
Nov 27 17:20:51.414152 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z SHOW RETENTION POLICIES ON TSM service=query
Nov 27 17:20:51.414303 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=SHOW+RETENTION+POLICIES+ON+TSM&u=+ HTTP/1.1" 200 204 "-" "InfluxData.Net.InfluxDb" ef721033-d38e-11e7-80e3-000000000000 286
Nov 27 17:20:51.417470 ubuntu influxd[4156]: [I] 2017-11-27T16:20:51Z SHOW RETENTION POLICIES ON TSM service=query
Nov 27 17:20:51.417590 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "GET /query?db=TSM&p=%5BREDACTED%5D&q=SHOW+RETENTION+POLICIES+ON+TSM&u=+ HTTP/1.1" 200 204 "-" "InfluxData.Net.InfluxDb" ef7276fe-d38e-11e7-80e4-000000000000 312
Nov 27 17:20:51.466050 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "POST /write?db=TSM&p=%5BREDACTED%5D&precision=ns&rp=tsm_meta_rp&u=+ HTTP/1.1" 204 0 "-" "-" ef7a014a-d38e-11e7-80e5-000000000000 49
Nov 27 17:20:51.533784 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "POST /write?db=TSM&p=%5BREDACTED%5D&precision=ns&rp=autogen&u=+ HTTP/1.1" 204 0 "-" "-" ef8385de-d38e-11e7-80e6-000000000000 5441
Nov 27 17:20:51.609196 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:20:51 +0100] "POST /write?db=TSM&p=%5BREDACTED%5D&precision=ns&rp=tsm_meta_rp&u=+ HTTP/1.1" 204 0 "-" "-" ef8f0803-d38e-11e7-80e7-000000000000 5435
Nov 27 17:21:01.543393 ubuntu influxd[4156]: [I] 2017-11-27T16:21:01Z DELETE FROM tsm_data WHERE f_l0 = 'aggnode1' AND f_l1 = 'aggnode2' AND f_l2 = 'aggnode51' AND f_l3 = 'datanode62' AND f_l4 = '' AND time >= -9223372036854772800 AND time <= -9223372036854771800 service=query
Nov 27 17:21:01.546139 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:21:01 +0100] "GET /query?db=TSM&epoch=ns&p=%5BREDACTED%5D&q=DELETE+FROM+tsm_data+WHERE+f_l0+%3D+%27aggnode1%27+AND+f_l1+%3D+%27aggnode2%27+AND+f_l2+%3D+%27aggnode51%27+AND+f_l3+%3D+%27datanode62%27+AND+f_l4+%3D+%27%27+AND+time+%3E%3D+-9223372036854772800+AND+time+%3C%3D+-9223372036854771800&u=+ HTTP/1.1" 200 33 "-" "InfluxData.Net.InfluxDb" f57ba274-d38e-11e7-80e8-000000000000 3093
Nov 27 17:21:11.551815 ubuntu influxd[4156]: [I] 2017-11-27T16:21:11Z SELECT * FROM TSM.autogen.tsm_data WHERE f_l0 = 'aggnode1' AND f_l1 = 'aggnode2' AND f_l2 = 'aggnode51' AND f_l3 = 'datanode62' AND f_l4 = '' AND time >= -9223372036854772800 AND time <= -9223372036854771800 ORDER BY time ASC LIMIT 100 service=query
Nov 27 17:21:11.552201 ubuntu influxd[4156]: [httpd] 192.168.91.1 -   [27/Nov/2017:17:21:11 +0100] "GET /query?db=TSM&epoch=ns&p=%5BREDACTED%5D&q=SELECT++%2A+FROM+autogen.tsm_data+WHERE+f_l0+%3D+%27aggnode1%27+AND+f_l1+%3D+%27aggnode2%27+AND+f_l2+%3D+%27aggnode51%27+AND+f_l3+%3D+%27datanode62%27+AND+f_l4+%3D+%27%27+AND+time+%3E%3D+-9223372036854772800+AND+time+%3C%3D+-9223372036854771800+ORDER+BY+time+ASC+LIMIT+100&u=+ HTTP/1.1" 200 2224 "-" "InfluxData.Net.InfluxDb" fb72c96b-d38e-11e7-80e9-000000000000 1002
```

**Comment by jwilder** [comment]
Do you have a script that we can run to reproduce this?

**Comment by lsitzmann** [comment]
Thanks Jason for the quick response.
Yes I stripped my test down to the attached script.
This is a transcript of my usage of the script:
`lars@ubuntu:~$ sudo dpkg -i influxdb_1.3.7_amd64.deb
dpkg: warning: downgrading influxdb from 1.4.2-1 to 1.3.7-1
(Reading database ... 94349 files and directories currently installed.)
Preparing to unpack influxdb_1.3.7_amd64.deb ...
Unpacking influxdb (1.3.7-1) over (1.4.2-1) ...
Setting up influxdb (1.3.7-1) ...
Installing new version of config file /etc/influxdb/influxdb.conf ...
Processing triggers for man-db (2.7.5-1) ...
lars@ubuntu:~$ sudo systemctl restart influxdb
lars@ubuntu:~$ /mnt/hgfs/D/data/influx-delete2.sh
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
lars@ubuntu:~$ sudo dpkg -i influxdb_1.4.2_amd64.deb
(Reading database ... 94349 files and directories currently installed.)
Preparing to unpack influxdb_1.4.2_amd64.deb ...
Unpacking influxdb (1.4.2-1) over (1.3.7-1) ...
Setting up influxdb (1.4.2-1) ...
Installing new version of config file /etc/influxdb/influxdb.conf ...
Processing triggers for man-db (2.7.5-1) ...
lars@ubuntu:~$ sudo systemctl restart influxdb
lars@ubuntu:~$ /mnt/hgfs/D/data/influx-delete2.sh
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0,"series":[{"name":"tsm_data","columns":["time","f_changed","f_l0","f_l1","f_l2","f_l3","t_old_data","vl_0_label52","vl_1_label54","vl_2_label56","vl_3_label58","vl_4_label60"],"values":[["1677-09-21T00:12:43.1452272Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452272,-0.08063101069679558,-0.0806310102,529122247631452272,-1100342216],["1677-09-21T00:12:43.1452273Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452273,-0.08063101069679558,-0.0806310102,529122247631452273,-1100342216],["1677-09-21T00:12:43.1452274Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452274,-0.08063101069679558,-0.0806310102,529122247631452274,-1100342215],["1677-09-21T00:12:43.1452275Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452275,-0.08063101069679558,-0.0806310102,529122247631452275,-1100342215],["1677-09-21T00:12:43.1452276Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452276,-0.08063101069679558,-0.0806310102,529122247631452276,-1100342214],["1677-09-21T00:12:43.1452277Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452277,-0.08063101069679558,-0.0806310102,529122247631452277,-1100342214],["1677-09-21T00:12:43.1452278Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452278,-0.08063101069679558,-0.0806310102,529122247631452278,-1100342213],["1677-09-21T00:12:43.1452279Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452279,-0.08063101069679558,-0.0806310102,529122247631452279,-1100342213],["1677-09-21T00:12:43.145228Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452280,-0.08063101069679558,-0.0806310102,529122247631452280,-1100342212],["1677-09-21T00:12:43.1452281Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452281,-0.08063101069679558,-0.0806310102,529122247631452281,-1100342212],["1677-09-21T00:12:43.1452282Z",1511864140346845600,"aggnode1","aggnode2","aggnode51","datanode62","True",529122247631452282,-0.08063101069679558,-0.0806310102,529122247631452282,-1100342211]]}]}]}
`

**Comment by jwilder** [comment]
@lsitzmann Thanks for the repro script.  #9173 should fix this on master once merged.  I'll backport to 1.4 as well.
