### ISSUE TITLE
Inserting point with nano time precision are dropped because of Retention policy 

### ISSUE THREAD

**Issue by idobarash** [influxdata/influxdb#9177]
__System info:__ 
Influx db version:   1.3.7
Influx java client: 2.7

__Steps to reproduce:__

1. create default retention policy for one year:   
`CREATE RETENTION POLICY one_year ON winner DURATION 365d PERCISREPLICATION 1 DEFAULT;`

2. Insert point:
```
Point point = Point.measurement(metricName)
                    .addField("aa", "valA")
                    .time(System.nanoTime(), TimeUnit.NANOSECONDS)
                    .tag("cc", "tagC")
                    .build();
```

__Expected behavior:__   Points will be added with nano percision since my retention policy is for the current year and point are new.

__Actual behavior:__  No point was inserted. Got this exception:
`{"error":"partial write: points beyond retention policy dropped=1"}`

**Comment by e-dard** [comment]
@idobarash I can't reproduce this. It's likely an error when setting the client fields. Probably you're sending a timestamp that isn't correctly formatted as nanoseconds, so InfluxDB is converting it to an historic time.

**Comment by idobarash** [comment]
@e-dard 

Using .time(System.nanoTime(), TimeUnit.NANOSECONDS)

I got this:   401609508779220

**Comment by e-dard** [comment]
@idobarash that's `1970-01-05 15:33:29.50877922 +0000 UTC`, which is why the data is being dropped.

**Comment by idobarash** [comment]
OK @e-dard  thank you very much, 
What did I do wrong?
How do I get this right?

I am using java 8.

**Comment by e-dard** [comment]
@idobarash we try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

I don't think `System.nanoTime()` gives you wall-clock time in nano seconds. I would start there. We can't provide any more help on the tracker here. Thanks.

**Comment by IdanFridman** [comment]
@e-dard Do you mind pasting the code you used to get the nano-seconds value? In the beginning it looked like an issue. thanks for pointing out that it was an java system issue

**Comment by e-dard** [comment]
https://play.golang.org/p/iQINVN8C3j

**Comment by IdanFridman** [comment]
wish live with java would be easier as that. thank you!
