### ISSUE TITLE
Influx Package Repos Are Unresponsive

### ISSUE THREAD

**Issue by kjschnei001** [influxdata/influxdb#9191]
### Bug report

__Steps to reproduce:__

1. Yum is timing out connecting to https://repos.influxdata.com on all of our machines, as well as on personal machines on home networks.
```
https://repos.influxdata.com/centos/7/x86_64/stable/repodata/repomd.xml: [Errno 12] Timeout on https://repos.influxdata.com/centos/7/x86_64/stable/repodata/repomd.xml: (28, 'Operation timed out after 30000 milliseconds with 0 out of 0 bytes received')
        Trying other mirror.
https://repos.influxdata.com/centos/7/x86_64/stable/repodata/repomd.xml: [Errno 12] Timeout on https://repos.influxdata.com/centos/7/x86_64/stable/repodata/repomd.xml: (28, 'Operation timed out after 30001 milliseconds with 0 out of 0 bytes received')
        Trying other mirror.
```
2. I also tried to access it from my browser and get an error message saying `The site cannot be reached`.

**Comment by pootzko** [comment]
Hi,

could you please say why you closed this? It started working again or?

**Comment by kjschnei001** [comment]
@pootzko I was unable to reproduce from my home network, leading me to believe that the report of it also being broken from other networks was the result of a test done from home on a VPN.  We have focused our debug efforts internally.  I apologize for the false report.

**Comment by pootzko** [comment]
No problem. We started getting 504 gateway timeouts this weekend (influxcloud) for /write requests so I was wondering if these two events were perhaps related. Thanks for the reply.

**Comment by kjschnei001** [comment]
Just to check, you guys aren't blocking traffic from `161.225.x.x` are you?

**Comment by pootzko** [comment]
Just for the clarity, by "we", I mean the company I work for (we're using the InfluxCloud service). I'm not part of Influx team. :)

**Comment by kjschnei001** [comment]
We were blocked, and for what it's worth, these type of support questions should be opened [here](https://support.influxdb.com)
