### ISSUE TITLE
elapsed transformation as continuous query

### ISSUE THREAD

**Issue by nanicpc** [influxdata/influxdb#9202]
### Feature Request

Hello guys,

I've been working with influx for a while now and I 'm getting and increasing number of request from the final users for the kind "time between events". In several use cases this information is actually need in near "realtime" (updates of 5m are the actual requirement).
Since elapsed can't be used with the group by clause as documented in the "Common Issues with ELAPSED() section. Issue2"

> The ELAPSED() function supports the GROUP BY time() clause but the query results aren’t particularly useful. Currently, an ELAPSED() query with a nested function and a GROUP BY time() clause simply returns the interval specified in the GROUP BY time() clause

**Proposal:** extend elapsed function to be accepted by the continuous querier

**Current behavior:**
The query:

 `CREATE CONTINUOUS QUERY "elapsed_5m" ON "db" RESAMPLE FOR 5m BEGIN SELECT elapsed(value, 1s) INTO db.rp.elapsedTime FROM db_original.autogen.Measurement GROUP BY tag1, tag2, tag3... END`

Raise the following error:

> Server returned error: error parsing query: found tag1, expected GROUP BY time(...) at line 1, char ...

**Desired behavior**: To be able to run automatically and periodically (on realtime) the elapsed query

`CREATE CONTINUOUS QUERY "elapsed_5m" ON "db" RESAMPLE FOR 5m BEGIN SELECT elapsed(value, 1s) INTO db.rp.elapsedTime FROM db_original.autogen.Measurement GROUP BY tag1, tag2, tag3... END`

**Use case**: storing and quering the time elapsed between events on realtime automatically

**Comment by cscheuermann81** [comment]
+1

**Comment by dandv** [comment]
@stale: unstale
