### ISSUE TITLE
 "error": "partial write: unable to parse 'yla1,host=server01,region=us-west httpsRequests=100i\r': invalid number\nunable to parse

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [influxdata/influxdb#9203]
Problem Statement:
I am trying post multiple data into influx db and I am getting the partial write error. Please refer the screen shot attached.

Data using to post :
yla1,host=server01,region=us-west httpsRequests=100i
yla1,host=server01,region=us-west bodySize=7528i
yla1,host=server01,region=us-west contentLength=7528i
yla1,host=server01,region=us-west httpTrafficCompleted=754i
yla1,host=server01,region=us-west timeToFirstByte=752i
yla1,host=server01,region=us-west timeToLastByte=755i
yla1,host=server01,region=us-west htmlCount=1i

Error Details:
{
    "error": "partial write: unable to parse 'yla1,host=server01,region=us-west httpsRequests=100i\r': invalid number\nunable to parse 'yla1,host=server01,region=us-west bodySize=7528i\r': invalid number\nunable to parse 'yla1,host=server01,region=us-west contentLength=7528i\r': invalid number\nunable to parse 'yla1,host=server01,region=us-west httpTrafficCompleted=754i\r': invalid number\nunable to parse 'yla1,host=server01,region=us-west timeToFirstByte=752i\r': invalid number\nunable to parse 'yla1,host=server01,region=us-west timeToLastByte=755i\r': invalid number dropped=0"
}

![test](https://user-images.githubusercontent.com/6301012/33661178-c91cf55e-daac-11e7-8c8e-eed4b0058693.PNG)

I am sure this is not a bug, must be doing something wrong. ^ any thoughts on this

**Comment by jwilder** [comment]
It looks like your writes are not valid line protocol.  I think windows uses `\r\n` to separate lines, but line protocol requires only `\n`.  Switching `\r\n` to `\n` should resolve this for you.

**Comment by JyotiPrakashMallick** [comment]
@jwilder thank you, let me try

**Comment by JyotiPrakashMallick** [comment]
@jwilder I tried with both I am getting the same error,

yla2,host=server01,region=us-west httpsRequests=100i \r\n
yla2,host=server01,region=us-west bodySize=7528i \r\n
yla2,host=server01,region=us-west contentLength=7528i \r\n
yla2,host=server01,region=us-west httpTrafficCompleted=754i \r\n
yla2,host=server01,region=us-west timeToFirstByte=752i \r\n
yla2,host=server01,region=us-west timeToLastByte=755i \r\n
yla2,host=server01,region=us-west htmlCount=1i \r\n

also tried with 
yla1,host=server01,region=us-west httpsRequests=100i\n
yla1,host=server01,region=us-west bodySize=7528i\n
yla1,host=server01,region=us-west contentLength=7528i\n
yla1,host=server01,region=us-west httpTrafficCompleted=754i\n
yla1,host=server01,region=us-west timeToFirstByte=752i\n
yla1,host=server01,region=us-west timeToLastByte=755i\n
yla1,host=server01,region=us-west htmlCount=1i\n

I am getting the same error. Any thought on this ? Please check the output,
{
    "error": "unable to parse 'yla2,host=server01,region=us-west httpsRequests=100i \\r\\n\r': bad timestamp\nunable to parse 'yla2,host=server01,region=us-west bodySize=7528i \\r\\n\r': bad timestamp\nunable to parse 'yla2,host=server01,region=us-west contentLength=7528i \\r\\n\r': bad timestamp\nunable to parse 'yla2,host=server01,region=us-west httpTrafficCompleted=754i \\r\\n\r': bad timestamp\nunable to parse 'yla2,host=server01,region=us-west timeToFirstByte=752i \\r\\n\r': bad timestamp\nunable to parse 'yla2,host=server01,region=us-west timeToLastByte=755i \\r\\n\r': bad timestamp\nunable to parse 'yla2,host=server01,region=us-west htmlCount=1i \\r\\n': bad timestamp"
}

**Comment by jwilder** [comment]
@JyotiPrakashMallick The output shows that you're still sending the `\r`character.  Each line needs to end with only `\n`.

**Comment by JyotiPrakashMallick** [comment]
@jwilder I tried all the possibility and I am getting the same error, please check the screenshot attached.
![error](https://user-images.githubusercontent.com/6301012/33671218-08d086aa-dacd-11e7-930e-eb1f0f7727c9.PNG)

**Comment by JyotiPrakashMallick** [comment]
anything I am doing wrong ?

**Comment by jaikensai888** [comment]
if you use import by txt file you can check the file line ending is LF/CRLF/CR by vscode;

**Comment by mananpatel1** [comment]
> anything I am doing wrong ?

I got same error.

**Comment by JyotiPrakashMallick** [comment]
@mananpatel1 I fix the above by writing a small script, could please help me whether you are trying manually or from some code ?

**Comment by mananpatel1** [comment]
> @mananpatel1 I fix the above by writing a small script, could please help me whether you are trying manually or from some code ?

I write some data in csv file then trying to upload that csv file on CLI , and I got same error which you were got.
