### ISSUE TITLE
InfluxDB requires as much virtual memory as it's 'data' set size

### ISSUE THREAD

**Issue by raidan2** [influxdata/influxdb#9221]
### Feature Request

By scrapping community questions, vague notes in this issue tracker I'm realizing — InfluxDB requires as much virtual memory as its data set size.

Unfortunately, there is no information of this behavior on ‘Hardware Sizing Guidelines’ and frankly I feel it must be there.

Like if you have 1B events with 10 series, with total 'data' size of 14 GiB — you have to run this database on machine with 16+ GiB RAM (or 8+ GiB RAM + 8+ GiB Swap); basically turns InfluxDB into some kind of 'in-memory database' (especially when you have ulimit on virtual memory).

This is exactly what I see with InfluxDB 1.3.7 and 1.4.2.
If the total amount of data (regardless of series cardinality) exceeds total amount of virtual memory available of this machine — InfluxDB cannot start with 'out of memory' error.

Now I completely understand why — all the data will be loaded with memory-mapped files without much care if it will be used later or not.
I wonder if this behavior will change some day.

__Proposal:__ Don't pay with memory if you don't use it.

__Current behavior:__ load everything into virtual memory, having extremely rigorous restrictions on both series cardinality (RSS memory) and total data set (virtual memory).

__Desired behavior:__ do not load shards into memory if they not used; restrict total amount of loaded shards.

__Use case:__ InfluxDB cannot be used as a long-term data storage for some applications; which it could be.

**Comment by sferrett** [comment]
Maybe you have a ulimit set for the user, or something like that creating an artificial limit?

I have about 90G of data files in my influxdb at the moment:
```
[influxdb@prdops02 influxdb]$ du -sh data
92G     data

```
On a machine with 32G of RAM and 16G of swap:
```
[influxdb@prdops02 influxdb]$ free -g
             total       used       free     shared    buffers     cached
Mem:            31         29          1          0          0         15
-/+ buffers/cache:         13         18
Swap:           15          0         15

```
The influxd reports over 100G of "virtual memory" in use, most of which I assume are mapped files:
```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                  
 2301 influxdb  20   0  109g  11g 2.5g S 145.4 36.0 101112:47 influxd                                                                                                  

```
This well exceeds the amount of available RAM in my case (this server does other things as well) and I have not had any issues starting up or using influxdb.  Indeed, the system shows still half the available memory being used as disk buffer. 

So - maybe you have a system limit set?   Running `ulimit -a` as the user who runs influxdb would potentially show them.

I am using influxdb 1.3.6

**Comment by raidan2** [comment]
@sferrett, indeed, we have ulimit on both max and virtual memory, for all Linux hosts regardless if it's physical or virtual.
I can't imagine production host without those options though.

Anyway, thanks for noticing this. I've updated my post a little bit.
This is definetely not a bug, but nice feature to have.

**Comment by phemmer** [comment]
My own $0.02: I don't think trying to reduce virtual size is a good idea. Virtual memory, in this case memory-mapped files are a good thing. It uses minimal amounts of real memory (RAM), it effectively uses RAM as a cache for the disk, and the kernel can easily evict the data from RAM because it can fetch the data back from disk when needed. However reducing its usage can result in a performance degradation (since the kernel can no longer optimize its usage based on overall health of the system), and requires more code on the application side.
