### ISSUE TITLE
Ubuntu package does not restart service after package update (broken post-install script)

### ISSUE THREAD

**Issue by davidgubler** [influxdata/influxdb#9228]
### Bug report

__System info:__ InfluxDB 1.3.7 upgraded to InfluxDB 1.4.2 on Ubuntu 16.04

__Steps to reproduce:__

1. Install version 1.3.7
2. Upgrade Package to 1.4.2
3. Check which version is running - it's still 1.3.7
4. restart server, now 1.4.2 is running.

The postinstall script of the Ubuntu package should restart the service. It doesn't do that currently.

**Comment by crab86** [comment]
Sure this is a bug? At least the documentation states that a restart of the service is necessary after upgrade:

https://docs.influxdata.com/influxdb/v1.6/administration/upgrading/

Currently as far as i understand the post-install.sh it never restarts the service itself no matter what init system is used and no matter what OS? Although the change in the post-install.sh should be quite easy?! 
```bash
function restart_influxdb {
    systemctl restart influxdb
}
[...]
elif [[ -f /etc/debian_version ]]; then
    # Debian/Ubuntu logic
    if command -v systemctl &>/dev/null; then
        install_systemd
        restart_influxdb 
```
Or am i missing something here? (Considering myself as a newbie in open-source development and i did not find any other file that would need to be adopted to resolve the mentioned issue).
