### ISSUE TITLE
Netdata does not require basic auth to send data to influx. Does this count as a bug?

### ISSUE THREAD

**Issue by luvpreetsingh** [influxdata/influxdb#9231]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

Influxdb version - 1.2.2
OS - ubuntu 16.04
Netdata version - v1.8.0-14-g0837fec_rolling

I am sending netdata metrics to influxdb database.

__Steps to reproduce:__

1. Open a port via influxdb to get input data in graphite format.

In `/etc/influxdb/influxdb.conf` file,

    [[graphite]]
      # Determines whether the graphite endpoint is enabled.
      enabled = true
      database = "netdata"
      # retention-policy = ""
      bind-address = ":2004"
      protocol = "tcp"

2. Configure netdata to send data to influxdb via port opened for graphite data.

In `/etc/netdata/netdata.conf` file,

        [backend]
         enabled = yes
         type = graphite
         destination = localhost:2004
         prefix = nd
         hostname = server1
         update every = 10

3. Restart netdata and influxdb

__Expected behavior:__ [What you expected to happen]

I have enabled basic auth(username and password) in influxdb. So, the client can only be connected to influxdb if it provides correct username and password.

So, influxdb should not accept this data as no username and password is provided.

__Actual behavior:__ [What actually happened]

But influxdb accepts this connection even when nothing is provided.

Influxdb must ask for username and password from netdata.

So, are you aware of this thing? Does this count as a bug?

**Comment by simonszu** [comment]
In my eyes this doesn't count as a bug. InfluxDB auth is only available for the InfluxDB HTTP API. Netdata doesn't access InfluxDB via its HTTP endpoint but via its graphite endpoint. I have opened a similar issue at netdata to support HTTP auth, and Netdata's maintainer told me it is using graphite which doesn't use auth at all. As you can see in the `influxdb.conf`, the `auth-enabled` flag is in the `[http]` subsection and not in the `[[ graphite ]]` section. 

There is already a feature request at Netdata requesting native InfluxDB connection. See https://github.com/netdata/netdata/issues/3824
