### ISSUE TITLE
[tcp] tcp.Mux: handler not registered: 71 influx server getting terminated

### ISSUE THREAD

**Issue by Vish17agr** [influxdata/influxdb#9245]
My influx is starting fine but after 1-2 hour of execution influx server is getting terminated.

I checked the log and find below message many times:
[tcp] 2017/12/18 12:38:44 tcp.Mux: handler not registered: 71

I am listening on localhost :8086 port. and I am using  http://173.36.80.163:8086 url to read data from influx in grafana. 

I am inserting the data into the influx from oracle database using java code.

I checked many GitHub issues with the same error message but couldn't able to relate the issue with them. As i am not using different nodes and listening on the same port through grafana.

I am using influx 0.9.6.1 version as it supports statsd.

Attached the influx log to debug the issue.
[influxops.log.log](https://github.com/influxdata/influxdb/files/1571856/influxops.log.log)

**Comment by jsternberg** [comment]
Hello, we do not support influx 0.9.6.1. Sorry, we will be closing this issue. If you continue to experience this problem on a recent version of InfluxDB, please comment so we can address this issue if it appears there.
