### ISSUE TITLE
GOMAXPROCS setting in config file not respected

### ISSUE THREAD

**Issue by omki2005** [influxdata/influxdb#9249]
I am using version 1.3.5, branch HEAD, commit 9d9001036d3585cf21925c13a57881bc6c8dcc7e

Steps to reproduce :- 
1. Add the following line to config file :- 
    GOMAXPROCS = 8
2. Start influxd with the above config file
3. Observe the following line in the output :- 
    Go version go1.8.3, GOMAXPROCS set to 24

Expected behaviour :- GOMAXPROCS set to 8
Actual behaviour :- GOMAXPROCS set to 24

It works as expected if I use an environment variable however.

**Comment by jwilder** [comment]
This is a [Go environment variable](https://golang.org/pkg/runtime/?m=all#hdr-Environment_Variables), not an InfluxDB specific setting.  There is no config file option to set this.

**Comment by omki2005** [comment]
That's not what this says :- 

https://docs.influxdata.com/influxdb/v1.4/administration/config/#global-options

**Comment by omki2005** [comment]
The list of environment variables is listed in the documentation at :- 

https://docs.influxdata.com/influxdb/v1.4/administration/config/#environment-variables

**Comment by jwilder** [comment]
The documentation isn't clear and is incorrect.  It is not settable via the config.  You can only set it via the environment variable.  

Only the options listed in the config (`influxd config`) are settable via environment variables and they are prefixed with `INFLUXDB_`.

I have opened a docs issue https://github.com/influxdata/docs.influxdata.com/issues/1357 highlighting this issue in the docs.

**Comment by jwilder** [comment]
I see you created a similar issue in https://github.com/influxdata/docs.influxdata.com/issues/1356.  I'll close the one I just created.
