### ISSUE TITLE
can ascLocations make sure sortable?

### ISSUE THREAD

**Issue by liluo1990** [influxdata/influxdb#9251]
func (a ascLocations) Less(i, j int) bool {
	if a[i].entry.OverlapsTimeRange(a[j].entry.MinTime, a[j].entry.MaxTime) {
		return a[i].r.Path() < a[j].r.Path()
	}
	return a[i].entry.MinTime < a[j].entry.MinTime
}

can this function make sure , if a < b and b < c ;then a<c ?

**Comment by jsternberg** [comment]
Hi, this question is likely more suited to something like stackoverflow if it is a question about code itself. If there is a specific issue with InfluxDB where you noticed the code is wrong in some way, then I would love to work with you and get that fixed. But, this looks like a homework question at the moment and issue trackers aren't an appropriate place to get help with computer science type questions.

I apologize if I have misunderstood the purpose of this issue, but I'm going to close this. I would assume that the method above follows the property `a < b` and `b < c` then `a < c`, but I have not checked if that is indeed true at the time I am writing this message.
