### ISSUE TITLE
github.com/influxdata/influxdb/services/collectd : too many errors

### ISSUE THREAD

**Issue by nicolasStevenin** [influxdata/influxdb#9263]
### Bug report

_System info:
CentOS Linux release 7.4.1708
influxdata/influxdb version:   1.4.2
Go Version : 1.8.3

_Error
Hello,
When I try to test cmd/influxd/run, it fails with
# github.com/influxdata/influxdb/services/collectd 
../../../services/collectd/service.go:47: undefined: api.TypesDB
../../../services/collectd/service.go:51: undefined: api.NewTypesDB
../../../services/collectd/service.go:113: s.popts.TypesDB undefined (type network.ParseOpts has no field or method TypesDB)
../../../services/collectd/service.go:118: undefined: api.NewTypesDB
../../../services/collectd/service.go:148: s.popts.TypesDB undefined (type network.ParseOpts has no field or method TypesDB)
../../../services/collectd/service.go:155: s.popts.TypesDB undefined (type network.ParseOpts has no field or method TypesDB)
../../../services/collectd/service.go:317: s.popts.TypesDB undefined (type network.ParseOpts has no field or method TypesDB)
../../../services/collectd/service.go:317: undefined: api.NewTypesDB
../../../services/collectd/service.go:369: cannot use valueList (type api.ValueList) as type *api.ValueList in argument to s.UnmarshalValueListPacked
../../../services/collectd/service.go:371: cannot use valueList (type api.ValueList) as type *api.ValueList in argument to s.UnmarshalValueList
../../../services/collectd/service.go:371: too many errors

Thank you for your help

**Comment by jsternberg** [comment]
I'm not sure what the reason is, but it looks like a compilation error. You should check to see if you have an up to date version of the library. I updated my local copy to master and compiling it still worked.
