### ISSUE TITLE
1.4.0 regression: fill() in a subquery causes long delay and incorrect result

### ISSUE THREAD

**Issue by sandeen** [influxdata/influxdb#9271]
### Bug report

__System info:__ influxdb-1.4.2-1.x86_64 on CentOS7

__Steps to reproduce:__

On my database:

`SELECT sum("BTU_Hr") FROM (SELECT mean("value") as "BTU_Hr" FROM "modbus_value" WHERE ("type_instance" = 'firing-rate') AND time >= now() - 1h GROUP BY time(5m) fill(36))
`

From scratch:

```
> create database testdb
> use database testdb
> insert test value=2
> SELECT mean("value") FROM "test" WHERE time >= now() - 10m GROUP BY time(5m) fill(36)
name: test
time                mean
----                ----
1516650300000000000 36
1516650600000000000 36
1516650900000000000 2
>
```

(note first timestamp, use that in next query to work around other parsing bug(?))

```
> SELECT SUM(mean) FROM (SELECT mean("value") FROM "test" WHERE time >= 1516650300000000000 GROUP BY time(5m) fill(36))
name: test
time sum
---- ---
0    3138415850
>
```
Note the incorrect value and the very long wait.

__Expected behavior:__ A value is quickly returned
__Actual behavior:__ Influxdb returns after long delay with incorrect value

__Additional info:__ 

This works if I use fill(null) instead:

```
> SELECT SUM(mean) FROM (SELECT mean("value") FROM "test" WHERE time >= 1516650300000000000 GROUP BY time(5m) fill(null))
name: test
time sum
---- ---
0    2
```
This seems to be a regression between 1.3.8 and 1.4.0

**Comment by sandeen** [comment]
A report from a faster machine indicates that it may simply be very slow, not hung.

**Comment by sandeen** [comment]
Is there any further information I could provide on this to help resolve the issue?

**Comment by sandeen** [comment]
I ran a git bisect between v1.3.8 and v1.4.0 and landed on:
```
commit 905e7fe05ed2a45513497b0790e682f22c253e4a
Author: Jonathan A. Sternberg <jonathan@influxdb.com>
Date:   Thu Aug 24 16:23:00 2017 -0500

    Refactor validation code and move it to the compiler
    
    This refactors the validation code so it is more flexible and performs a
    small bit of work to make preparing and executing the query easier.
    
    The general idea is that compilation will eventually do more heavy
    lifting in creating the initial plan and prepare will construct an
    actual plan rather than just doing some basic field rewriting.
    
    This change at least sets us up for that change in the future and moves
    the validation code to the query execution instead of in the parser.
    
    This also frees up the parser to parse the complete AST without worrying
    if the query itself is valid. That could be useful for client code that
    wants to compile a partial query to an AST and then perform
    modifications on the AST for some reason.
```

**Comment by sebito91** [comment]
Had an offline conversation with @sandeen about this and it indeed looks like a regression. Given the amount of data processed I would not expect this type of query to return in 20-30s...seems way too long to calculate especially when the inner query returns almost immediately.

**Comment by sandeen** [comment]
Added a simple reproducer

**Comment by sandeen** [comment]
Time ranges are clearly getting screwed up:

```
> SELECT FIRST(mean) FROM (SELECT mean("value") FROM "test" WHERE time >= 1516650300000000000 GROUP BY time(5m) fill(36))
name: test
time                 first
----                 -----
-9223371873709551616 36
> SELECT LAST(mean) FROM (SELECT mean("value") FROM "test" WHERE time >= 1516650300000000000 GROUP BY time(5m) fill(36))
name: test
time                last
----                ----
9223371900000000000 36
```
those times look suspiciously like they could be memory addresses... 0x7FFFFFE022D1D800

**Comment by jsternberg** [comment]
It looks like the part of the query engine that turned the implicit `fill(null)` into a `fill(none)` broke so the query engine is likely churning through a bunch of null responses and doing nothing useful.

I'll work on fixing it. The fix shouldn't be too difficult, but would it be possible for you guys to try it out and see if it fixes your issue? This one is a bit harder to test.

**Comment by sandeen** [comment]
Great thanks - sure, I would be happy to test it with my real data - please note the short reproducer in the first comment as well.

**Comment by jsternberg** [comment]
There's a PR up now. I'm going to try your reproducer on both with and without to see the difference.

**Comment by sandeen** [comment]
FWIW this seems like more than just a performance problem, it's a wrong value returned as well, so check that not just speed.  ;)

**Comment by jsternberg** [comment]
Yea, I'm sorry. The issue reminded me of something when originally developing subqueries. I don't think it's related so I'm back to looking for the bug.

**Comment by jsternberg** [comment]
I think this is correct, but can you try adding `WHERE time <= now()` somewhere in your query?

The query is tricking the system into generating intervals until the end of time instead of using an implicit now as the end time. It's definitely a bug, but adding the `time <= now()` should be good for a temporary workaround and would confirm that's the bug.

It seems to work for me locally.

**Comment by sandeen** [comment]
I'll need to get my environment w/ the newer influxdb booted up again, but this:
```
> create database testdb
> use database testdb
> insert test value=2
> SELECT FIRST(mean) FROM (SELECT mean("value") FROM "test" WHERE time >= 1516650300000000000 GROUP BY time(5m) fill(36))
name: test
time                 first
----                 -----
-9223371873709551616 36
> SELECT LAST(mean) FROM (SELECT mean("value") FROM "test" WHERE time >= 1516650300000000000 GROUP BY time(5m) fill(36))
name: test
time                last
----                ----
9223371900000000000 36
```
seems to indicate that both start & finish timestamps are messed up, no?

**Comment by jsternberg** [comment]
Yes, it does seem to indicate that both timestamps are messed up. For whatever reason, adding `time <= now()` seems to fix that timestamp issue.

I'm taking a look at it now.

**Comment by sandeen** [comment]
Thanks for sorting this out, btw.
