### ISSUE TITLE
GROUP BY tag returning group without a tag

### ISSUE THREAD

**Issue by nheath** [influxdata/influxdb#9281]
### Bug report

__System info:__ 

Standard single server setup 

Ubuntu 14.04.5 LTS
http://localhost:8086 version 1.4.2
InfluxDB shell version: 1.4.2

__Steps to reproduce:__

We are sending two series to a measurement, `account_winbacks` one representing the total, using the standard `value` name, and a second series `by_duration` for which all records include a `duration` tag value (the `value` series does not include this tag). e.g. some sample data:

```
> SELECT * FROM "account_winbacks" limit 10

name: account_winbacks
time                by_duration duration value
----                ----------- -------- -----
1513727810000000000                      182941
1513728410000000000 66          9yr
1513728410000000000 146252      +9yr
1513728410000000000 821         1wk
1513728410000000000 3580        3mo
1513728410000000000 4063        3yr
1513728410000000000 8456        1yr
1513728410000000000 2129        4yr
1513728410000000000 1143        5yr
1513728410000000000 865         1mo
```

We are using `GROUP BY "duration"`, and displaying a single chart with multiple series in grafana. Here's a simplified version of our query that exhibits the problem:

```
> SELECT max("by_duration") FROM "account_winbacks" WHERE time > now() - 1h  GROUP BY "duration" fill(none) limit 1 slimit 5
name: account_winbacks
tags: duration=
time                max
----                ---
1515103070000000000 183044

name: account_winbacks
tags: duration=+9yr
time                max
----                ---
1515103070000000000 146311

name: account_winbacks
tags: duration=1mo
time                max
----                ---
1515103070000000000 866

name: account_winbacks
tags: duration=1wk
time                max
----                ---
1515103070000000000 821

name: account_winbacks
tags: duration=1yr
time                max
----                ---
1515103070000000000 8469
```

__Actual behavior:__ 

A group is returned with an empty tag value (in the above example):
```
name: account_winbacks
tags: duration=                <===== HERE
time                max
----                ---
1515103070000000000 183044
```

__Expected behavior:__ 

We select only the `by_duration` field, for which all values have the `duration` tag, so I dont understand why we're getting this group returned. I have tried to confirm that we dont have a record  causing issues, by adding clauses like `WHERE "duration" != ""` and `WHERE "duration" != NULL` and neither seems to have any effect. I'm unclear how empty values are handled, and if these types of where clauses are even a valid approach; I also tried to find such records like `select * from "account_winbacks" WHERE "duration" = ""` and got no records, so it appears this isnt the correct approach.

It looks like this is a bug in the way grouping by tag is handled when using multiple series in a measure, but I may be missing something. Would love any additional feedback or troubleshooting steps. - Thanks!

**Comment by hamsterready** [comment]
To anyone that might be looking for a solution: you could use where `tag =~ /./` to include only the records with the `tag` however when you have many records the performance is really poor. As such it seems that subquery with `tag != ''` or `tag =~ /./` is the way to go.

**Comment by hamsterready** [comment]
And for anyone willing to use subquery as a solution, there is #9122 which has impact on performance.

**Comment by iwittkau** [comment]
Hmm, seems like I am 26 days too late to the game. 

I just hit this bug and I think it is still a problem. Can we reopen this?

**Comment by PawZawDev** [comment]
I have a similar problem, I'm using a query: 

`SELECT * FROM service_resources_utilization GROUP BY service ORDER BY time ASC`

I get the grouped data, but without the service tag - so I don't know which group is which service.
Any workaround?
