### ISSUE TITLE
Import data into influxdb

### ISSUE THREAD

**Issue by yuvarajanlga** [influxdata/influxdb#9298]
May i know the procedure to import the data to influxdb database ? 

is there any link available for importing data to existing database ?

**Comment by davidgs** [comment]
That depends in large part on what format the data is in currently. Is this an InfluxDB data backup? Is it in CSV format? What is the format of the data that you are trying to import?

**Comment by timhallinflux** [comment]
There is documentation on line protocol:  https://docs.influxdata.com/influxdb/v1.4/write_protocols/line_protocol_tutorial/

**Comment by jsternberg** [comment]
I'm going to close this since it seems it is a support question. If you need help with this, please visit our [community](https://community.influxdata.com) forum. Thanks.
