### ISSUE TITLE
make the home button work on the cli

### ISSUE THREAD

**Issue by f1-outsourcing** [influxdata/influxdb#9306]
when you are testing sql queries from the command line it could be nice when you press the arrow up key, to then jump to the start with the HOME key.

**Comment by f1-outsourcing** [comment]
and END for that matter

**Comment by mark-rushakoff** [comment]
Home and end, and ^a ^e, work on my machine (OSX, iterm). What's your setup? What version are you running?

Note that we are using https://github.com/peterh/liner for these CLI features.

**Comment by f1-outsourcing** [comment]
Just a regular updated CentOS7 machine. OSX is not relevant environment, (if I were to guess) the most serious production environments use rhel/centos.

Hmmm, I looked at the CLI features, maybe not to wise to use Ctrl A, that is the default key combination of screen.

**Comment by f1-outsourcing** [comment]
Hello hello, still not available in InfluxDB shell version: 1.6.2

**Comment by f1-outsourcing** [comment]
WTF
