### ISSUE TITLE
"New issue" documentation regarding cUrl for pprof is wrong

### ISSUE THREAD

**Issue by makareth** [influxdata/influxdb#9312]
__System info:__ 

Influx 1.2.2
Ubuntu 16.04.02

__Steps to reproduce:__
1. Go to Github Influxdb repo 
2. Create new issue
3. Cut and paste curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true" command to the influxdb host. 
4. Execute the curl command

__Expected behavior:__
The content of the tar.gz file should be tar gzipped content with pprof data.

__Actual behavior:__ 
The file contains "Unknown profile: all"

**Comment by jsternberg** [comment]
Your version of InfluxDB is too old. Please upgrade to 1.3.0 to get that functionality. Sorry for the inconvenience, but adding additional 1.2.x instructions for generating the profile to the issue template would make the instructions more confusing than they already are and we already advise upgrading to an officially supported version for most bugs and especially for things like performance analysis.
