### ISSUE TITLE
Data getting duplicated and data not getting populated into influxdb but returns status code 204

### ISSUE THREAD

**Issue by braja-nayak** [influxdata/influxdb#9320]
Hi,
We are using influxdb in our application and found some rows are getting duplicated for same tags and timestamp. So I deleted all the records for that tag and tried inserting data for that tag again. But I can see data are not getting populated in influx even though I am getting 204 as response.

I tried above process into another db and I am able see the data getting populated into db. So can anybody kindly suggest me any solution for this problem.

**Comment by marcintustin** [comment]
@braja-nayak  Did you ever solve this? Any tips on investigating this?
