### ISSUE TITLE
InfluxDB high CPU usage for one simple query

### ISSUE THREAD

**Issue by levtomer66** [influxdata/influxdb#9354]
__System info:__ [InfluxDB v1.4.2 (git: 1.4 6d2685d1738277a1c2672fc58df7994627769be6)
Ubuntu, 16.04, xenial, Ubuntu 16.04.3 LTS"
AWS Machine: 2 CPU 4GB RAM
Type: t2.medium

__Steps to reproduce: 

1. Running 4 times this query: 
```SELECT percentile("value", 95) FROM  "myMeasurement"  WHERE time > now() - 15m GROUP BY time(1h)``` 
creates high CPU.

__Expected behavior: Normal CPU usage 

__Actual behavior: Very high CPU usage >60% for one query if running 2 concurrently it jump to 100%+ 

__Additional info:

```
SHOW TAG KEYS from myMeasurement
name: myMeasurement
tagKey
------
distinctor
```

```
SHOW FIELD KEYS from myMeasurement
name: myMeasurement
fieldKey fieldType
-------- ---------
value    float
```

![image](https://user-images.githubusercontent.com/15570898/35222536-f0e0398a-ff86-11e7-878a-1580feb3603b.png)

I created influxdcpu.prof:
```
sudo /usr/bin/influxd -cpuprofile influxdcpu.prof
```
while running the query above, attached the file.

```SHOW STATS```
[stats.txt](https://github.com/influxdata/influxdb/files/1652124/stats.txt)

[profile001.pdf](https://github.com/influxdata/influxdb/files/1652076/profile001.pdf)

Cardinality on database: 68899 series.
Cardinality of this specific measurement ("myMeasurement") ~9000 series

Looks like I'm doing something wrong how is that possible the CPU is so high for one simple query ?

Thanks :)

**Comment by hardiksondagar** [comment]
I'm having a similar issue on 1.7, series cardinality is only 14000 and machine have 16 core. Still 100% CPU usage.

**Comment by kraken0909** [comment]
please, bot, no. i have same problem 1.7.1

**Comment by Elleanora** [comment]
Having this issue in 1.8.0 as well.

**Comment by MrZbb** [comment]
Having this issue in 1.8.10 as well
