### ISSUE TITLE
i want to my influxdb has no "path", what should i do?

### ISSUE THREAD

**Issue by liuhoom** [influxdata/influxdb#9358]
![image](https://user-images.githubusercontent.com/6359476/35271188-3db6d09e-006c-11e8-8d43-a1f47343918a.png)

**Comment by jsternberg** [comment]
I apologize but I have no idea what you mean. Are you using Telegraf to write this data into InfluxDB or something else?

This also appears to be a support question. We only handle feature requests and bug reports on the issue tracker. For support, please join our [community](https://community.influxdata.com) forum. Thanks.
