### ISSUE TITLE
Adding multiple time-series in InlfuxDB/Grafana - HELP !!

### ISSUE THREAD

**Issue by balajikalluri** [influxdata/influxdb#9364]
Dear friends,

I am still an early-stage user of InfluxDB with Grafana. 

I would like to find a simple approach to "add" multiple data streams at once. 

A quick example of a Grafana dashboard (find the attached) presenting time-series data points from InfluxDB is used for illustration. 

The bar chart presents time-series record of energy consumption per day of different points.
 
In the above, I would like to simply "add" all values everyday to compute aggregated energy consumption. 

How do I implement this? 

Your quick help will be appreciated. 

Thanks & regards.

Bala 
![influxdb_help1](https://user-images.githubusercontent.com/7898603/35428389-ab7cf34e-02a9-11e8-96ed-07fab1341e33.jpg)

**Comment by jsternberg** [comment]
Hello, the issue tracker is only for bugs or feature requests. For help with support, please go to our [community](https://community.influxdata.com) website. Thanks!
