### ISSUE TITLE
SHOW SERIES returns no results if default retention policy is empty

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#9368]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB Version: 28f3912
OS: CentOS/7 & Arch Linux

__Steps to reproduce:__

```
create database test
create retention policy foo on test duration inf replication 1
use test.foo
insert test,foo=bar v=1i
show series
```

__Expected behavior:__ [What you expected to happen]
```
test,foo=bar
```

__Actual behavior:__ [What actually happened]
```
```

**Comment by jwilder** [comment]
This is a dup of #7404
