### ISSUE TITLE
Group by tag without time return wrong aggregates

### ISSUE THREAD

**Issue by julienmathevet** [influxdata/influxdb#9370]
### Bug report
__System info:__ 1.4.2

If I set group by on tag without time aggregate I have strange results. But theses results correspond to old correct values. Something in cache ?

I tried to reproduce this bug wth fake data, bug I think I haven't inserted enough data. May be is related to my data.

__Expected behavior:__

__Actual behavior:__
```
select count(value) from asset_kpi where time > now() - 2h group by asset
name: vod_kpi
tags: asset=asset1
time                count
----                -----
1517228590693966062 273

name: vod_kpi
tags: asset=asset2
time                count
----                -----
1517228590693966062 253

name: vod_kpi
tags: asset=asset3
time                count
----                -----
1517228590693966062 250

name: vod_kpi
tags: asset=asset4
time                count
----                -----
1517228590693966062 251

name: vod_kpi
tags: asset=asset5
time                count
----                -----
1517228590693966062 266
```

__Additional info:__
```
select count(value) from asset_kpi where time > now() - 2h group by asset, time(1h)
name: vod_kpi
tags: asset=asset1
time                count
----                -----
1517227200000000000 1
1517230800000000000 0
1517234400000000000 0

name: vod_kpi
tags: asset=asset2
time                count
----                -----
1517227200000000000 3
1517230800000000000 1
1517234400000000000 1

name: vod_kpi
tags: asset=asset3
time                count
----                -----
1517227200000000000 2
1517230800000000000 0
1517234400000000000 1

name: vod_kpi
tags: asset=asset4
time                count
----                -----
1517227200000000000 0
1517230800000000000 2
1517234400000000000 1

name: vod_kpi
tags: asset=asset5
time                count
----                -----
1517227200000000000 1
1517230800000000000 2
1517234400000000000 1

```

**Comment by jsternberg** [comment]
Is the data consistently incorrect? You say that the data is correct for an older value, but does that mean that a second query gives you the correct answer? I'm wondering if the data just hasn't shown up yet in time for the first query.

**Comment by easyrasta** [comment]
No sorry, I haven't explained correctly. This request is always wrong. That I would said values seems like a request for a common interval, like a day in past.
I saw that because any values was inserted today, and some queries returns data

**Comment by jsternberg** [comment]
To clarify, I see two queries above. One includes a `GROUP BY time(...)` and the other does not. You are saying the ones with `GROUP BY time(...)` are correct (so for asset1, there is a total count of 1) and the ones without `time(...)` are not correct (the 273).

Is there any way that you could share the data with us? We can provide a way to send us the data in a secure method if needed and anonymized data is fine. I would like to be able to reproduce the issue if at all possible.

**Comment by easyrasta** [comment]
Yes that's it. How I could send you data ?
