### ISSUE TITLE
TSI: Compact series file segment files to remove tombstoned series

### ISSUE THREAD

**Issue by benbjohnson** [influxdata/influxdb#9371]
TSI currently compacts and removed tombstones from series file lookup maps but does not shrink the segment files. The `SeriesFileCompactor` should do both.

* Tombstone aggregate tracking #9514
* Tombstone rewriting #9516
* Integration #9517
* Metrics on tombstones/compactions #9518

**Comment by e-dard** [comment]
I'm re-opening this as this effort was never completed.

The main thing missing is compaction on series segment files. Currently they can grow unbounded with many new series created and many deletions. There is no way to reduce the size of the segments without a rebuild of the TSI indexes and Series File.

**Comment by e-dard** [comment]
don't close.

**Comment by 8none1** [comment]
https://github.com/influxdata/influxdb/tree/er-series-compact

**Comment by 8none1** [comment]
This PR addresses the issue for the 1.8 release:  https://github.com/influxdata/influxdb/pull/16542
