### ISSUE TITLE
error compacting TSM files: compaction aborted: bad plan

### ISSUE THREAD

**Issue by hpbieker** [influxdata/influxdb#9393]
### Bug report

__System info:__ 
Influx 1.4.2 on Ubuntu Linux 16.4.

__Steps to reproduce:__

Unknown. It happens from time to time.

__Expected behavior:__ 
No error message in the log.

__Actual behavior:__ 
I keep getting this error message in the log from time to time (once every day or two).
error compacting TSM files: compaction aborted: bad plan: 
```
error compacting TSM files: compaction aborted: bad plan: /media/db_volume/data/_internal/monitor/6309/000004413-000000001.tsm engine=tsm1
```

**Comment by jwilder** [comment]
@hpbieker How do you have your volume mounted at `/media/`?  Is this a directly attached SSD, NAS, NFS, RAID, docker volume, etc..?

That error is strange in that a file appears to have disappeared from the time it was planned for a compaction.  I have seen similar issues with users trying to use NFS for the data dir in the past.

Also, can you attach your config?

**Comment by hpbieker** [comment]
@jwilder The volume under /media is an ext4 filesystem located on a volumegroup device. The volume group is stored on a set of disks that is made available from our virtual machine host (VMware vSphere). The actual disks are located in a SAN with spinning disks.

I have not actually seen the message lately.

```
$ cat /etc/influxdb/influxdb.conf|grep -v '^ *#\|^$'
 reporting-disabled = true
[meta]
  dir = "/media/db_volume/meta"
[data]
  dir = "/media/db_volume/data"
  wal-dir = "/media/wal_disk/wal"
  wal-fsync-delay = "0.1s"
  trace-logging-enabled = true
  max-concurrent-compactions = 8
[coordinator]
  write-timeout = "60s"
  log-queries-after = "10s"
[retention]
[shard-precreation]
[monitor]
[http]
[subscriber]
  http-timeout = "120s"
[[graphite]]
[[collectd]]
[[opentsdb]]
[[udp]]
[continuous_queries]
```

**Comment by jwilder** [comment]
I suspect there is something going on with how your disks are setup.  The error is more of a warning that a TSM file was part of a compaction plan, but immediately after the file could not be found.  In this case, the compaction aborts and there is a new plan created.

If you happen to see this again, can you attach the logs for the error for several minutes before the error?  Compactions log which files they are going to work on beforehand so I'm curious if there happened to be two plans that were assigned the same file (should not happen as of #8886)
