### ISSUE TITLE
aggregation not working in where clause

### ISSUE THREAD

**Issue by schmurfy** [influxdata/influxdb#9394]
I am using influxdb 1.4.2 and trying to make this query works:

```sql
select "level", LAST("level") FROM raw.alerts WHERE "last" = 'OK'
```
If I replace the where clause with `WHERE "level" = 'OK'` it correctly returns one result and the `last` column shows the correct value but I cannot make this works with the aggregated value `last`, in sql you need to use `HAVING` if I remember well but there is no such thing in influxQL so I suppose this is supposed to work, is it ?

I tried various ways but none worked and it really looks like a bug althought it is hard to say since influxdb basically never returns an error...

Here is what I tried:
- `select "level", LAST("level") AS "last_level" FROM raw.alerts WHERE "last_level" = 'OK'`
- `select "level", LAST("level") FROM raw.alerts WHERE last = 'OK'`
- `select "level", LAST(level) FROM raw.alerts WHERE last = 'OK'`

While none returned anything they also do not return an error.

**Comment by phemmer** [comment]
See #5266

**Comment by schmurfy** [comment]
thanks, is there a way to achieve this right now ?
Since the isse you linked has been opened two years ago I doubt this will be an option in a close future...

**Comment by jsternberg** [comment]
I believe subqueries can do this if you want to use an aggregate and then filter on the result. So for your example:

```
select "level" from (SELECT LAST("level") AS "level" FROM raw.alerts) WHERE "last" = 'OK'
```

**Comment by schmurfy** [comment]
@jsternberg  thanks !
It works well for my need :)
