### ISSUE TITLE
Import values w/ timestamps in RFC3339 format

### ISSUE THREAD

**Issue by henrydan** [influxdata/influxdb#9395]
Unsure whether this is expected behavior however influx rejects data points on imports that specify time in RFC3339 format instead of Unix time even with the "-precision=rfc3339" switch

Sample Error: 
'inMDS,stream=ALL nb/sec=736,avg=939,max=2222,total=17198277 2018-01-15T01:47:16.97Z': bad timestamp\nunable to parse

Command:
./influx -import -path=/apps/InfluxDB/usr/bin/toInflux2.txt -precision=rfc3339

Sample Data: 
inMDS,stream=ALL nb/sec=1151,avg=569,max=2222,total=13008787 2018-01-15T00:00:00.05Z

Version: 1.2.2, branch master, commit 1bcf3ae74c6b9c4897dab68d513d056277eb24f7

reason for using RFC3339 format while importing is it was easier to append date to the beginning and 'Z' to the end of a historic log where timestamp is given in hh:mm:ss.xx format than convert to epoch time

**Comment by jwilder** [comment]
The `-precision` flag applies to how timestamps are show in the CLI when running queries.  For imports, the lines must adhere to line protocol format which is a nanosecond precision integer.

https://docs.influxdata.com/influxdb/v1.4/write_protocols/line_protocol_tutorial/

**Comment by jesusmendozaa** [comment]
Hello,
What about the last version (1.6)? Can I import data in RFC3339 format?

regards!
