### ISSUE TITLE
Cyclic high memory usage

### ISSUE THREAD

**Issue by ricco24** [influxdata/influxdb#9409]
### Bug report

__System info:__
**Ubuntu version**: 16.04 LTS
**Influx version**: 1.4.2 and 1.3.5 (two machines, same behaviour)

__Expected behavior:__ 
Stabile memory usage in time

__Actual behavior:__
Every monday morning, around 6am influx is restarted (really dont know why, i dont found any error msg in syslog, /var/log/influxdb folder is empty and no cron is setup at this time). After restart memory usage continually grows.

__Additional info:__

Server 1:
![server1](https://user-images.githubusercontent.com/1409647/35933506-21001764-0c3b-11e8-8668-6c3246e8ecc8.png)

Server 2:
![server2](https://user-images.githubusercontent.com/1409647/35933515-23d0431a-0c3b-11e8-8bab-d6bc29578e77.png)

On one server i have 40 databases. Highest series cardinality when i run command

`SELECT numSeries FROM "_internal".."database" WHERE time > now() - 10s GROUP BY "database" ORDER BY desc LIMIT 1`

is 172 for my databases and 4k for _internal.

**Comment by russorat** [comment]
closing due to age. please upgrade to the latest version and open a new issue if this is still happening.
