### ISSUE TITLE
influxdb database list not updated

### ISSUE THREAD

**Issue by Lahorde** [influxdata/influxdb#9414]
I'm using `InfluxDB shell version: v1.4.3`
And influxdb is `X-Influxdb-Version: 1.4.2`

# Steps to reproduce 
Create a DB using HTTP API :

    curl -u user:user -i -XPOST http://server:8086/query  --data-urlencode "q=create database test"

I can check db has been created :

```
curl -G http://server:8086/query --data-urlencode "u=user" --data-urlencode "p=user" --data-urlencode "q=SHOW DATABASES"
{"results":[{"statement_id":0,"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["test"]]}]}]}
```

In client : 
```
> show databases
name: databases
name
----
_internal
```
**Newly created DB is not shown.**
Moreover I can create it

```
create database test
> show databases
name: databases
name
----
_internal
test1
```

**Comment by jsternberg** [comment]
Is authentication enabled?

**Comment by Lahorde** [comment]
I found problem, influxdb client host was a server backup from host used in curl requests.
