### ISSUE TITLE
Running CQs after every write

### ISSUE THREAD

**Issue by karanrajpal14** [influxdata/influxdb#9419]
### Feature Request

__Proposal:__
Allowing continuous queries to run on every write.
Let's say I have a measurement with two fields - a,b
Every time a, b are inserted into my measurement "cpu" I'd like my continuous query to perform some arithmetic operation and store this within another field, say ab.

The CQ would look something along the lines of this
```
CREATE CONTINUOUS QUERY "calc_product" ON "sensordata"
BEGIN
SELECT a*b
AS ab
INTO cpu
FROM cpu
END
```

__Current behavior:__
CQs are run periodically

__Desired behavior:__
Allow CQs to run on every write

__Use case:__
Would be great for some underpowered sensors where floating point arithmetic would be taxing on the system.

**Comment by agriffit79** [comment]
Surely that's a classic use case for Kapacitor?

**Comment by dgnorton** [comment]
@karanrajpal14 as suggested by @agriffit79, this is probably best solved with Kapacitor. I haven't tested this but a Kapacitor TICKScript for that might look something like:
```
dbrp "sensordata"."autogen"

stream
   |from()
      .measurement('cpu')
   |eval(lambda: "a" * "b")
      .as('ab')
   |influxDBOut()
      .database('sensordata')
      .retentionPolicy('autogen')
      .measurement('ab')
      .tag('anything', 'youwant')
      .tag('anothertag', 'youneed')
