### ISSUE TITLE
Add CA certificate, CRL and HTTPS client certificate verification support for InfluxDB

### ISSUE THREAD

**Issue by mjf** [influxdata/influxdb#9421]
Hello,

it would be nice to add *CA* certificate, *CRL* and *HTTPS* **client certificate verification** support for *InfluxDB*. As far as I know *HAProxy* or another proxy is needed in front of *InfluxDB* to achieve client certificate verification for now. Desired configuration could look like the following example one:

    [http]
        # ... snip ...
        https-enabled = true

        # ... snip ...
        https-certificate = "/path/to/some.crt"
        https-key = "/path/to/some.key"

        # NEW OPTIONS
        https-ca-certificate = "/path/to/some.crt"
        # https-crl = "/path/to/some.crl"
        https-client-certificate-verify = true
        https-client-certificate-verify-required = true

-----
Snippet from the *HAProxy* v1.8 documentation on how this works in it:

``verify [ none | optional | required ]``

*[...] If set to 'none', client certificate is not requested. In other cases, a client certificate is requested.
If the client does not provide a certificate after the request and if 'verify' is set to 'required', then the
handshake is aborted, while it would have succeeded if set to 'optional'. The certificate provided by the
client is always verified using CAs from 'ca-file' and optional CRLs from 'crl-file'. [...]*

-----
(also see [HAProxy Configuration Manual](https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.1-verify))

**Comment by FendiJatmiko** [comment]
anyone currently working on this ..? i would like to working on this issue, please. .

**Comment by mahekchheda** [comment]
@mgaffney is this issue still needed? I would like to start contributing to this project so don't mind picking this up.

**Comment by mgaffney** [comment]
@mahekchheda I'm not sure what the status of this is.

**Comment by OmgImAlexis** [comment]
Can this please be reopened?
