### ISSUE TITLE
Implement trigonometry functions

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#9424]
### Feature Request

__Proposal:__ Implement the trigonometry functions: `sin()`, `cos()`, `tan()`.

__Current behavior:__ They are not implemented.

__Desired behavior:__ They would be implemented.

__Use case:__ Using the trigonometry functions.

Earlier versions of the query engine had a problem with implementing trigonometry functions because these would be a new class of functions labeled transform functions. A transform function gets parsed as a call, but it is effectively another binary operator so query validation works differently. Since earlier versions of the query parser relied on assuming that a call was a selector or an aggregator, this was difficult or impossible.

In 1.4, I changed the query compilation so this assumption is no longer made... as frequently. I think there are a few places where this assumption is still made, but they should be reasonably easy to remove and then we can implement the query engine to handle these calls as part of the normal processing of a binary operator.

**Comment by epa095** [comment]
Hi, if you also implement atan2 you make it possible to take the [average of circular quantities](https://en.wikipedia.org/wiki/Mean_of_circular_quantities) (e.g. average heading).

**Comment by jsternberg** [comment]
Yea, we can do that. The primary difficulty is supporting the first. After that, they are all decently easy to implement.
