### ISSUE TITLE
TSI: log entry checksum should be validated before decoding entry

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#9425]
Garbage input to (*LogEntry).UnmarshalBinary can cause panics in some instances (e.g. if binary.Uvarint returns a negative length [here](https://github.com/influxdata/influxdb/blob/90c921fc0f7f0186955641fcf4b4c9e256b3696d/tsdb/index/tsi1/log_file.go#L1038-L1039)).

Assuming these panics come from corrupted input files, the CRC validation should happen at the start of UnmarshalBinary rather than validated at the end.

**Comment by mark-rushakoff** [comment]
Side note: that negative length was the only panic I discovered in (*LogEntry).UnmarshalBinary in a brief go-fuzz test.

**Comment by benbjohnson** [comment]
@mark-rushakoff I tried fixing this but I realized that the TSI entries don't write their size first so the entry has to be read before we can get to the checksum. What's the panic that you're getting?

**Comment by mark-rushakoff** [comment]
@benbjohnson on these lines: https://github.com/influxdata/influxdb/blob/90c921fc0f7f0186955641fcf4b4c9e256b3696d/tsdb/index/tsi1/log_file.go#L1038-L1039

If you're reading in garbage data, you may get a negative `n` from binary.Uvarint:
https://golang.org/pkg/encoding/binary/#Uvarint
```
n  < 0: value larger than 64 bits (overflow)
        and -n is the number of bytes read
```

Or in another case it may return `n > len(data)`.

**Comment by jacobmarble** [comment]
@mark-rushakoff in what case will the returned `n > len(data)` ?

**Comment by mark-rushakoff** [comment]
I think that could only happen if reading corrupted or garbage data. A properly encoded log would never return `n > len(data)`.

**Comment by jacobmarble** [comment]
Corrupted/garbage data is why this bug exists, right? :)
