### ISSUE TITLE
Could I use a network share disk as data storage?

### ISSUE THREAD

**Issue by HeathKang** [influxdata/influxdb#9427]
Hi,
Here was the thing. My linux's space was almost full. So I was wondering could I mount a network share disk as the location of influxdb data storage as a temporary solution?
I had known that influxdb is  very dependent on speed of IOPS. An IOPS test guide would be helpful too!!!
Thanks a lot!

**Comment by mark-rushakoff** [comment]
https://docs.influxdata.com/influxdb/v1.4/guides/hardware_sizing/#what-kind-of-storage-do-i-need

> InfluxDB is designed to run on SSDs. InfluxData does not test on HDDs or networked storage devices, and we do not recommend them for production

You can try using a network mounted drive, but we do not officially support anything but SSDs. We've seen many strange bugs arising from network mounted storage that does not play well with mmap'ed files.
