### ISSUE TITLE
[CLI] "influx -execute" parses queries strange while executed from bash-script.

### ISSUE THREAD

**Issue by EliasGabrielsson** [influxdata/influxdb#9428]
### Directions
When using `influx -execute` from a bash script it parses query strange and gives an error. Similar executions from commandline works as intended. The goal of script below is to do a reset of the admin password.

### Bug report

__System info:__ 
* `InfluxDB shell version: 1.4.2`
* `influxd version 1.4.2`
* Ubuntu 16.04, latest patchset

__Steps to reproduce:__
Make a script like this in a file and execute like a sudo bash script:
```
sed -i "s/.*auth-enabled = .*/  auth-enabled = false/g" /etc/influxdb/influxdb.conf # Disable authentication
systemctl restart influxdb.service
sleep 2 # Ensure service has restarted
influx -execute "\"SET PASSWORD FOR admin = '$passwordChange'\"" 
```
__Expected behavior:__ The script shall change the admin password to `val`

__Actual behavior:__ 
Error output below. Observe that the query looks correct parsed in the error message.
```
ERR: error parsing query: found SET PASSWORD FOR admin = 'val', expected SELECT, DELETE, SHOW, CREATE, DROP, EXPLAIN, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
error parsing query: found SET PASSWORD FOR admin = 'val', expected SELECT, DELETE, SHOW, CREATE, DROP, EXPLAIN, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1

```
__Additional info:__
Could be related to this issue: https://github.com/influxdata/influxdb/issues/7805

**Comment by jsternberg** [comment]
Remove the extra set of double quotes. What's happening is you are sending this query to the server: `"SET PASSWORD FOR admin = 'val'"` and it is getting parsed as a variable. Since a variable isn't appropriate there, it tells you which values to use, but then it prints out what it found which is the variable name that looks like a correct statement.

If you remove the extra set of quotes, it will just send the actual query.

**Comment by EliasGabrielsson** [comment]
Thats explains it all. Thanks now everything works 😄  🎊
