### ISSUE TITLE
CentOS repo not updated with 1.4.3

### ISSUE THREAD

**Issue by austinbutler** [influxdata/influxdb#9440]
### Bug report

__System info:__ CentOS 7, InfluxDB 1.4.2

__Steps to reproduce:__ yum update

__Expected behavior:__ Upgrade available for 1.4.3.

__Actual behavior:__ No upgrade available.

__Additional info:__ The [downloads portal](https://portal.influxdata.com/downloads) indicates 1.4.3 is available, although the [changelog](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#v143-unreleased) says it's unreleased, so one of those is wrong.

**Comment by ronnbcnews** [comment]
+1

**Comment by codylewandowski** [comment]
I opened a ticket with Influx for this and received this response back: 

Hello Cody,

I've checked with our engineering team and at the moment, there are no plans to add it to the YUM repo. However, we have added this as a request to our backlog and 
1.4.3 should be added sometime in the near future. I wish I could give you an exact date, but should I have any new details on this, I will reach out to you.

At this point, I will proceed to close this ticket. however, feel free to re-open it by simply replying back if you have any additional questions or concerns on this ticket.

**Comment by jimaek** [comment]
That makes no sense. Why would they not prioritize the release of their own software on yum. Whats the point of the repo otherwise.
