### ISSUE TITLE
Influxdb starts very slow with semi-large databases

### ISSUE THREAD

**Issue by vladimir-smirnov-sociomantic** [influxdata/influxdb#945]
I've got pretty large database - 67GB (~700k metrics), stored on SSD and restart process takes a lot of time - more than 20 minutes.

I've ran perf on that, and it shows that during the start most of the time is spent in this:

```
+  62.91%  influxdb  influxdb           [.] std::_Rb_tree_increment(std::_Rb_tree_node_base const*)
+  36.03%  influxdb  influxdb           [.] rocksdb::VersionSet::Builder::Apply(rocksdb::VersionEdit*)
```

Is there any way to speedup start process, cause 20 minutes is very-very slow?

Config settings are default.

**Comment by MikeSchroll** [comment]
This is being currently discussed over here: https://github.com/influxdata/influxdb/issues/5764
