### ISSUE TITLE
Abnormally high CPU load

### ISSUE THREAD

**Issue by sammy007** [influxdata/influxdb#9457]
### Bug report

__System info:__ [1.4.3, Ubuntu Xenial, Xeon E3 4c 8t, SSD]

__Expected behavior:__ Normal CPU load.

__Actual behavior:__ High CPU load.

__Additional info:__ Queries: https://gist.github.com/sammy007/c26cfabaabb9c0fa1b2a903fa086b4be

I execute a number of queries which are specified in a gist every 10 seconds. Writing approximately 300 points in batch via http every 5 seconds, 500 different tags (`worker` names) and a few `src` tags. Point also consist of 3 numeric value fields (`diff`, `valid` and `stale`).

Influxdb configured to run continuous queries every 2 seconds. Almost default config with adjusted `cache-snapshot-memory-size = "256m"`.

![](https://cdn.pbrd.co/images/H7RPkPF.png)

InfluxDB is a cyan on a chart.

**Comment by JordanP** [comment]
lol that's a good one !

**Comment by sammy007** [comment]
I am a bit confused, could you be more specific @JordanP?

**Comment by tkeffer** [comment]
I think what he's saying is that you are putting some high demands on the database, so a high CPU load is to be expected.
