### ISSUE TITLE
Enhance windowing to include Interpolation option which would interpolate values for Start and End Window times

### ISSUE THREAD

**Issue by edbernier** [influxdata/influxdb#9484]
### Feature Request

__Proposal:__When querying a time window also include the two values just outside the current boundary and the points just inside the window (if they exist) to interpolate what the value you would get at the exact Start and End points of the window.  This provides a sense of direction taking into account the distance between points.

__Current behavior:__ If there were no points in the window nothing would be returned.  Also, currently there is no interpolation to return a point at the exact Start and End window timestamps.

__Desired behavior:__
I'll use an example:  Given a window with Start timestamp of 01/01/2018 10:00:00 and an End timestamp of 01/02/2018 10:00:00.
Lets say we have 2 points inside the window at  
   Point B is at timestamp of 01/02/2018 11:00:00
   Point C is at timestamp of 01/02/2018 11:30:00
and lets say we have 2 points outside the window at
   Point A is at timestamp of 10/02/2017 11:00:00
   Point D is at timestamp of 01/03/2018 2:30:00
By considering the points outside the window range I can interpolate the values for the Start and End timestamps based on these outside points, which would take into account the direction and distance between points.  This becomes especially important if the window doesn't happen to intersect any points.

Here is a good example of the behavior we are looking for: https://www.youtube.com/watch?v=dsOsp5Iwv3A

__Use case:__This is especially important for irregular series with sparse data and would allow the condition where the window doesn't have any points within it but has points just outside the range to interpolate what the points at the Start and End of the window would be.

**Comment by timhallinflux** [comment]
@nathanielc -- shall we tag this for a future Flux addition?
