### ISSUE TITLE
SHOW TAG KEYS FROM disk_value not returning data

### ISSUE THREAD

**Issue by f1-outsourcing** [influxdata/influxdb#9485]
SHOW TAG KEYS FROM disk_value not returning data 

CentOS7 
influxdb-1.4.2-1.x86_64

https://community.influxdata.com/t/lost-tag-keys-values-post-upgrade-to-1-4-2/3489

**Comment by dgnorton** [comment]
@f1-outsourcing did you try this on 1.5? Still need help with rebuilding the index?

**Comment by dgnorton** [comment]
@f1-outsourcing I'm going to close this issue. If you're still having trouble, ping us again on the community forum issue.

**Comment by f1-outsourcing** [comment]
I have heard rebuilding the indexes that before, but can't find any manual for this
