### ISSUE TITLE
Make usage reporting optional

### ISSUE THREAD

**Issue by udf2457** [influxdata/influxdb#9497]
At the moment influx sends back usage data every restart (and perhaps more frequently ?).  In the name of privacy etc. please make this optional.  Thank you.

**Comment by mark-rushakoff** [comment]
It's already configurable: http://docs.influxdata.com/influxdb/v1.4/administration/config/#reporting-disabled-false

**Comment by jwilder** [comment]
@udf2457 It is optional.  You can disable in your config with
```
reporting-disabled = true
```

Or by setting `INFLUXDB_REPORTING_DISABLED=true influxd`

**Comment by udf2457** [comment]
@jwilder oops ;-)
