### ISSUE TITLE
Writing points from a file doesn't work

### ISSUE THREAD

**Issue by stevebang** [influxdata/influxdb#9498]
@donnyyu (https://github.com/donnyyu) posted the following as a docs issue, but it appears to be an InfluxDB issue. 

II used two methods, influxdb -import and curl @data4.txt
Both of two method only imported the last line data-point from text file

My data4.txt file
`# DML
# CONTEXT-DATABASE:sf200db

sf200,siteID=59,farm=L firmwareV="2.5.2.409",IP="172.16.59.4"
sf200,siteID=59,farm=L firmwareV="2.5.2.409",IP="172.16.59.14"
sf200,siteID=59,farm=L firmwareV="2.5.2.409",IP="172.16.59.12"
sf200,siteID=59,farm=L firmwareV="2.5.2.409",IP="172.16.59.6"
sf200,siteID=59,farm=L firmwareV="2.5.2.409",IP="172.16.59.8"
sf200,siteID=59,farm=L firmwareV="3.1.4.122",IP="172.16.59.20"
sf200,siteID=59,farm=L firmwareV="3.1.4.122",IP="172.16.59.22"
sf200,siteID=59,farm=L firmwareV="2.5.2.409",IP="172.16.59.2"
sf200,siteID=59,farm=L firmwareV="3.1.4.122",IP="172.16.59.18"
sf200,siteID=59,farm=L firmwareV="3.1.1.80",IP="172.16.59.16"
sf200,siteID=59,farm=L firmwareV="2.4.0.382",IP="172.16.59.26"
sf200,siteID=59,farm=L firmwareV="3.1.1.80",IP="172.16.59.24"`

curl method
`curl -i -XPOST 'http://localhost:8086/write?db=sf200db' --data-binary @data4.txt`
influx -import method
`influx -import -path=data4.txt 
2018/02/28 11:27:37 Processed 0 commands
2018/02/28 11:27:37 Processed 12 inserts
2018/02/28 11:27:37 Failed 0 inserts
`
###### What products and version are you using?
influxdb 1.4

**Comment by donnyyu** [comment]
I found problem, it's my data point Syntax issue.

I modified text file, it worked.

Old text file:
`
...
sf200,siteID=59,farm=L firmwareV="3.1.4.122",IP="172.16.59.18"
sf200,siteID=59,farm=L firmwareV="3.1.1.80",IP="172.16.59.16"
sf200,siteID=59,farm=L firmwareV="2.4.0.382",IP="172.16.59.26"
...
`

New text file:
`
...
sf200,siteID=59,farm=L,IP=172.16.59.18 firmwareV="3.1.4.122"
sf200,siteID=59,farm=L,IP=172.16.59.16 firmwareV="3.1.1.80"
sf200,siteID=59,farm=L,IP=172.16.59.26 firmwareV="2.4.0.382"
...
`

Resolved

**Comment by stevebang** [comment]
Closed -- user error.
