### ISSUE TITLE
[Question] Tag indexing when having same measurement with multiple retention policies

### ISSUE THREAD

**Issue by ittaiyam** [influxdata/influxdb#9500]
Hi,
A question, if I may post it here, because I can't find an answered after scouring the web.
In my organization we are trying to design a solution where a measurement has points written to it over a short retention policy (call it raw), and a CQ is configured to aggregate that raw data, daily.
Let’s call the measurement M1, so that the short retention measurement can be described like so:
myDb.raw.M1 = F1 T1,T2,T3
And the aggregated measurement can be described like so:
myDb.daily.M1 = F1 T1,T2,T3
F1 is a field and T1,T2,T3 are tags.
The CQ groups raw M1 by T1,T2,T3 and sets daily M1’s F1 as the sum of raw M1’s F1.
What would the indexing memory behavior be?
Does the memory allocated for indexing T1,T2,T3 double itself after running the CQ?
Do raw.M1 and daily.M1 in that respect get treated like two completely different measurements?

**Comment by dgnorton** [comment]
@ittaiyam The best place for usage questions is on our [community forum](https://community.influxdata.com/). We use this issue tracker for bugs in the software. :)
