### ISSUE TITLE
Add support for docker runtime env variable

### ISSUE THREAD

**Issue by gganeshan** [influxdata/influxdb#9501]
I am running influxdb in a docker container using the latest influxdb image from docker hub.
Now I want to enable SSL for this instance.

The documentation in [Influx Data website](https://docs.influxdata.com/influxdb/v1.2) is excellent. However, I have a slightly different (but not so unique) usecase for which it would be great if you could add support for docker runtime variables.

If not, can you suggest a workaround??

### Use case:
* I want to run separate influxdb instances for each environment, namely prod, dr, cert, dev etc.
* I have different certs for different environments.
* I want to include all these certs in my image in `/etc/ssl/<environment_name>` dir
* I want to supply a docker runtime env variable called DOCKER_RUNTIME_ENV
* I want influxdb container to honor this runtime variable and use the correct cert from `/etc/ssl/${DOCKER_RUNTIME_ENV}` dir.

#### System Info:
Docker Image: `influxdb:latest`
InfluxDB version: `InfluxDB shell version: 1.4.3`
OS: `Linux c486ff3efb29 4.14.11-coreos #1 SMP Fri Jan 5 11:00:14 UTC 2018 x86_64 GNU/Linux`

#### Steps to reproduce:

1. make sure you have environment specific certs
```
$ tree ssl/
ssl/
├── cert
│   ├── cert.crt
│   └── cert.key
├── dev
│   ├── cert.crt
│   └── cert.key
├── dr
│   ├── cert.crt
│   └── cert.key
├── prod
│   ├── cert.crt
│   └── cert.key
└── qa
    ├── cert.crt
    └── cert.key
```
2. Create a `Dockerfile` with the following contents:
```
FROM influxdb

COPY ssl/ /etc/ssl/
```
3. Build the image using:
`docker build -t influxdb .`
4. Run the container using:
```
docker run -d -it \
  --env DOCKER_RUNTIME_ENV=dev \
  --env INFLUXDB_HTTP_HTTPS_ENABLED=true \
  --env INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/${DOCKER_RUNTIME_ENV}/cert.crt \
  --env INFLUXDB_HTTP_HTTPS_KEY=/etc/ssl/${DOCKER_RUNTIME_ENV}/cert.key \
  --read-only \
  --publish 8086:8086 \
  --volume /var/lib/influxdb \
  --name influxdb \
  influxdb
```

##### Expected behavior:
`influxdb` container should start successfully with TLS enabled. It should honor the docker runtime variable and use the appropriate certificate.

##### Actual behavior:
`influxdb` container fails with the below error:
```
$ docker logs influxdb 

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

[I] 2018-03-01T17:15:35Z InfluxDB starting, version 1.4.3, branch 1.4, commit 60d27e6995558f38a39e90b35a92cbac080310a3
[I] 2018-03-01T17:15:35Z Go version go1.9.2, GOMAXPROCS set to 4
[I] 2018-03-01T17:15:35Z Using configuration at: /etc/influxdb/influxdb.conf
[I] 2018-03-01T17:15:35Z Using data dir: /var/lib/influxdb/data service=store
[I] 2018-03-01T17:15:35Z opened service service=subscriber
[I] 2018-03-01T17:15:35Z Starting monitor system service=monitor
[I] 2018-03-01T17:15:35Z 'build' registered for diagnostics monitoring service=monitor
[I] 2018-03-01T17:15:35Z 'runtime' registered for diagnostics monitoring service=monitor
[I] 2018-03-01T17:15:35Z 'network' registered for diagnostics monitoring service=monitor
[I] 2018-03-01T17:15:35Z 'system' registered for diagnostics monitoring service=monitor
[I] 2018-03-01T17:15:35Z Starting precreation service with check interval of 10m0s, advance period of 30m0s service=shard-precreation
[I] 2018-03-01T17:15:35Z Starting snapshot service service=snapshot
[I] 2018-03-01T17:15:35Z Starting continuous query service service=continuous_querier
[I] 2018-03-01T17:15:35Z Starting HTTP service service=httpd
[I] 2018-03-01T17:15:35Z Authentication enabled:false service=httpd
[I] 2018-03-01T17:15:35Z Storing statistics in database '_internal' retention policy 'monitor', at interval 10s service=monitor
run: open server: open service: open /etc/ssl//cert.crt: no such file or directory
```

Please let me know if anymore information is required from my end.

**Comment by jwilder** [comment]
It looks like there is a problem in your docker run command:

```
docker run -d -it \
  --env DOCKER_RUNTIME_ENV=dev \
  --env INFLUXDB_HTTP_HTTPS_ENABLED=true \
  --env INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/${DOCKER_RUNTIME_ENV}/cert.crt \
  --env INFLUXDB_HTTP_HTTPS_KEY=/etc/ssl/${DOCKER_RUNTIME_ENV}/cert.key \
  --read-only \
  --publish 8086:8086 \
  --volume /var/lib/influxdb \
  --name influxdb \
  influxdb
```

You're setting`DOCKER_RUNTIME_ENV=dev` in the container that will be started, but you also reference the variable `INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/${DOCKER_RUNTIME_ENV}/cert.crt` which will be undefined because the `DOCKER_RUNTIME_ENV` doesn't exist in your current shell.

Try:
```
export DOCKER_RUNTIME_ENV=dev 
docker run -d -it \
  --env DOCKER_RUNTIME_ENV \
  --env INFLUXDB_HTTP_HTTPS_ENABLED=true \
  --env INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/${DOCKER_RUNTIME_ENV}/cert.crt \
  --env INFLUXDB_HTTP_HTTPS_KEY=/etc/ssl/${DOCKER_RUNTIME_ENV}/cert.key \
  --read-only \
  --publish 8086:8086 \
  --volume /var/lib/influxdb \
  --name influxdb \
  influxdb
```
