### ISSUE TITLE
Tag values not expiring correctly

### ISSUE THREAD

**Issue by alexrkopp-xx** [influxdata/influxdb#9503]
### Bug report

__System info:__ Influx 1.4, ubuntu

__Steps to reproduce:__

Not sure what exactly is causing it, but here's the setup:

Problem: tag values still show up in `show tag values from "raw_data" with key=route` despite some of those values having no data points in the `raw_data` measurement (I have a short two-day retention policy).

Here's roughly how I have things set up:

I have three RPs:
- Autogen (not used)
- 2_days
- 90_days

Data comes into the `raw_data` measurement in the `2_days` RP. The data has a route tag and a value.

Every 15 minutes, I have a kapacitor script to downsample the data and writing the new samples into a different measurement (say `data_15m`) in the `90_days` RP. These new samples are also tagged by `route`.

I'm assuming that I should be able to use `show tag values from "raw_data" with key=route` to get a list of routes that have been seen over the past 2ish days, but I definitely see routes in that list that return no results when I try to select them from the `raw_data` measurement.

__Expected behavior:__ Only tag values that have data points are returned when calling `show tag values`

__Actual behavior:__ Tag values with no data points in any RP are still being returned in `show tag values`

__Additional info:__ Restarting InfluxDB seems to trigger this prune of orphaned tag values. See https://community.influxdata.com/t/tag-values-not-expiring/4208 which has some observations from Igor.

**Comment by leucos** [comment]
**System info**: 
- 1.5.2, Ubuntu 18.04
- 1.6.1, Ubuntu 16.04

I am experiencing a very similar issues where a `SHOW TAG VALUES FROM "somerp".current_hosts WITH KEY = "host"` returns data **even if the RP has been dropped**.

Another issue is that `SHOW TAG VALUES FROM "somerp".current_hosts WITH KEY = "host"` return hosts that have no actual points in the RP.

I guess those issues are related.

**Actual behavior**

- create a DB
- create a first RP ("myrp"), make it default
- create another RP ("2hours")
- create a CQ to insert data from default RP to "2hours"
- insert data
- drop "2hours" RP
- `SHOW TAG VALUES FROM mydb."2hours"` still returns data despite RP previously being DROPPED

**Expected behaviors**

- `SHOW TAG VALUES FROM mydb."2hours" ` should not return values if the RP has been dropped
- `SHOW TAG VALUES FROM mydb."2hours" ` should not return specific tags if it is not present in any measurement in the RP

**Full test case using docker**

```
$ docker run --name influx -d influxdb
$ docker exec -ti influx bash

# influx -execute "CREATE DATABASE mydb"
# influx -database mydb -execute 'CREATE RETENTION POLICY "2hours" ON "mydb" DURATION 2h REPLICATION 1'
# influx -database mydb -execute 'CREATE RETENTION POLICY "myrp" ON "mydb" DURATION 720h REPLICATION 1 DEFAULT'
# influx -database mydb -execute 'SHOW RETENTION POLICIES'

name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 0s       168h0m0s           1        false
2hours  2h0m0s   1h0m0s             1        false
myrp    720h0m0s 24h0m0s            1        true

# curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu,host=server01,region=us-west value=0.64'
# influx -database mydb -execute "SELECT * FROM cpu"

name: cpu
time                host     region  value
----                ----     ------  -----
1434055562000000000 server01 us-west 0.64

# influx -database mydb -execute 'CREATE CONTINUOUS QUERY current_hosts_query ON mydb BEGIN SELECT max(value) AS value INTO mydb."2hours".current_hosts FROM mydb.myrp.cpu GROUP BY time(5m), host END'
# influx -database mydb -execute 'SHOW CONTINUOUS QUERIES'

name: mydb
name                query
----                -----
current_hosts_query CREATE CONTINUOUS QUERY current_hosts_query ON mydb BEGIN SELECT max(value) AS value INTO mydb."2hours".current_hosts FROM mydb.myrp.cpu GROUP BY time(5m), host END

name: _internal
name query
---- -----

# curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu,host=server01,region=us-west value=0.64'
# curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu,host=server01,region=us-west value=0.64'


# influx -database mydb -execute 'SHOW TAG VALUES FROM mydb."2hours".current_hosts WITH KEY = "host"'
# timeout 5m bash -c 'while true; do curl -s -XPOST "http://localhost:8086/write?db=mydb" --data-binary "cpu,host=server01,region=us-west value=0.${RANDOM}"; sleep 5; echo -n "."; done'
# influx -database mydb -execute 'SHOW TAG VALUES FROM mydb."2hours".current_hosts WITH KEY = "host"'

name: current_hosts
key  value
---  -----
host server01

# influx -database mydb -execute 'DROP RETENTION POLICY "2hours" ON "mydb"'
# influx -database mydb -execute 'SHOW RETENTION POLICIES'

name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 0s       168h0m0s           1        false
myrp    720h0m0s 24h0m0s            1        true

# influx -database mydb -execute 'SHOW TAG VALUES FROM mydb."2hours".current_hosts WITH KEY = "host"'

name: current_hosts
key  value
---  -----
host server01
```
