### ISSUE TITLE
Wrong number of measurements in _internal

### ISSUE THREAD

**Issue by hahnjo** [influxdata/influxdb#9506]
__System info:__
InfluxDB `master`, similar problems seen on a production server with a version between 1.4.2 and 1.4.3.

__Steps to reproduce:__
(wait 10 seconds before querying `_internal` to make sure updated statistics were gathered)

1. Start empty InfluxDB
2. `CREATE DATABASE test`
3. `USE test`
4. `INSERT test key="value"`
5. `SELECT numMeasurements, numSeries FROM "_internal".."database" WHERE "database" = "test"`
--> 1 measurement, 1 series as expected
6. `DROP MEASUREMENT test`
7. `SELECT numMeasurements, numSeries FROM "_internal".."database" WHERE "database" = "test"`
--> 0 measurements, 0 series as expected (see #8198)
8. `INSERT test key="value"`

__Actual behavior:__

9. `SELECT numMeasurements, numSeries FROM "_internal".."database" WHERE "database" = "test"`
--> 0 measurements, 1 series which is clearly wrong!

__Expected behavior:__
The query should return 1 measurement and 1 series.

__Additional info:__

10. Restart InfluxDB
11. `SELECT numMeasurements, numSeries FROM "_internal".."database" WHERE "database" = "test"`
--> 1 measurement, 1 series

On a production system I see slightly different problems and the number of series is wrong, too. But IMO chances are high that this is the same underlying issue with tombstone entries (?): I did drop some (derived) series and recreated them afterwards without restarting the server since. If wanted I can do that to see if the problem goes away.

**Comment by dgnorton** [comment]
@hahnjo `numMeasurements` and `numSeries` are estimates, [currently implemented using HLL](https://github.com/influxdata/influxdb/blob/master/tsdb/index/inmem/inmem.go#L73). The numbers returned by the estimates when there are thousands or millions of measurements or series should be accurate within a relatively small margin of error.

**Comment by hahnjo** [comment]
@dgnorton just wanted to make sure that the numbers aren't off by percentage. Thanks for confirming!
