### ISSUE TITLE
ErrDatabaseNotFound should be a type

### ISSUE THREAD

**Issue by corpix** [influxdata/influxdb#9507]
I see here https://github.com/influxdata/influxdb/blob/19ef39d9478fa08beac598e828caef76cbbf9ca5/errors.go#L15 `ErrDatabaseNotFound` is just a constructor for the non-typed error...

I want to know when my application failed to insert something into database because database was not found. Should I match error with `strings.HasPrefix(err.Error(), "database not found:")`?

Probably this constructor should be converted into type definition:

``` go
import (
    "fmt"
)

type ErrDatabaseNotFound string

func (e ErrDatabaseNotFound) Error() string {
    return fmt.Sprintf("database not found: %s", string(e))
}
```

Which will allows you to match this error:

``` go
switch err.(type) {
    case ErrDatabaseNotFound:
        // ...
    // ...
}
```

**Comment by corpix** [comment]
Ouch! Things worse than I thought.

``` go
points, err := client.NewBatchPoints(...)
if err != nil { ... }

err = influxdbHttpClient.Write(points)
fmt.Printf("%#v\n", err) // outputs: &errors.errorString{s:"{\"error\":\"database not found: \\\"testdatabase\\\"\"}\n"}
```

The error returned by the database client is not `ErrDatabaseNotFound`, looks like it was constructed with go std lib `errors.New`. One common thing between the `ErrDatabaseNotFound` and `errors.errorString` is... the error message. Okay, I'll match this error by it's error message string :(

But you know, this is terrible way to handle the errors, isn't it?

**Comment by jsternberg** [comment]
The client returns whatever the HTTP server returns. Since the client and the server aren't the same process, it wouldn't be possible for the types to transfer.

You should just match on the text.

@nathanielc should we consider having some way to type errors back to the client for easier identification of specific errors in ifql? It seems to me like some enum could be helpful with this.

**Comment by corpix** [comment]
@jsternberg 

> The client returns whatever the HTTP server returns. Since the client and the server aren't the same process, it wouldn't be possible for the types to transfer.

Yeah, but I mean… your database and client are written in Go, why not just make client serialize errors into the same types?
