### ISSUE TITLE
WHERE matches always with SHOW TAG VALUES if tag key begins with underscore

### ISSUE THREAD

**Issue by salomatu** [influxdata/influxdb#9522]
I came across with this behavior when trying to use the template facilities of Grafana while using data stored in InfluxDB by the Prometheus interface. The interface stores the names of the metrics in the tag key `__name__`, so it would occasionally make sense to retrieve, for example, all "instance" values that have a certain series defined by the method described below.

I figure names like these might be interfering with some internal mechanisms, but I couldn't find any way to quote the tag key in such a way that it would work either. If this is by design, then the naming established in the Prometheus interface might require reworking, and that is a completely another story.

__System info:__
InfluxDB 1.4.2 on Centos 7 x86_64 from official InfluxDB repository.

__Steps to reproduce:__

1. Create measurements with a tag with underscores
```
> select * from testseries
name: testseries
time       __name__ meas uniq
----       -------- ---- ----
1439856000 bar      1    ccc
1439856000 bar      1    ddd
1439856000 foo      1    aaa
1439856000 foo      1    bbb
```
2.  Try to show tag values
```
> SHOW TAG VALUES FROM testseries WITH KEY = "uniq" WHERE "__name__" = 'bar'
```

__Expected behavior:__
Values of tag key "uniq" where tag `__name__` equals "bar" are returned.
```
name: testseries
key  value
---  -----
uniq ccc
uniq ddd
```
__Actual behavior:__
All possible values for the tag key "uniq" are returned. The result is always the same if the tag key after WHERE begins with an underscore, eg. `WHERE "_asdfa" = ...`
```
name: testseries
key  value
---  -----
uniq aaa
uniq bbb
uniq ccc
uniq ddd
```

**Comment by e-dard** [comment]
I have reproduced this in `1.4.2`, and confirmed it was not fixed as part of the `1.5.0` cycle. Investigating further, it appears that a `WHERE` clause containing a tag key beginning with an underscore will trigger this bug.

For example, the following will also return all of the tag key values for the `uniq` key:

```
SHOW TAG VALUES FROM testseries WITH KEY = "uniq" WHERE "_" = 'a'
SHOW TAG VALUES FROM testseries WITH KEY = "uniq" WHERE "_s" = 'a'
SHOW TAG VALUES FROM testseries WITH KEY = "uniq" WHERE "______" = 'a'
```

**Comment by e-dard** [comment]
@salomatu (sorry I closed by mistake). In terms of a workaround until we fix this bug, I suggest that you use an alternative tag key that doesn't begin with an underscore.

In general we don't advise anything (measurements, tag keys etc) are named with leading underscores, as we use leading underscores identifiers for some internal functionality.

**Comment by e-dard** [comment]
@salomatu I'm glad you have a workaround. We'll get this fixed 👍

**Comment by datamuc** [comment]
I don't have a workaround :crying_cat_face:

**Comment by datamuc** [comment]
I guess this is where it happens:

https://github.com/influxdata/influxdb/blob/8efed00569f8b0f3c396342d182acdade477a5cf/tsdb/store.go#L1343

I've tried to find a proper explanation for that code and traced it back to

https://github.com/influxdata/influxdb/blob/2f0e2467571300fe4166741683534df221607a2f/tsdb/shard.go#L925

But couldn't find anything meaningful.

**Comment by dgnorton** [comment]
Duplicate / related issues: #5870, #6011, #7642
