### ISSUE TITLE
Error creating the shard directory in 1.4.2 after restore from version 1.2.2

### ISSUE THREAD

**Issue by RagHarnoor** [influxdata/influxdb#9532]
### Bug report

__System info:__ v1.4.2, Ubuntu 14.04

__Steps to reproduce:__

1. Take a back up in v1.2.2 and restore it in v1.4.2
2. No change to the retention policy, keep the default behavior 

__Expected behavior:__ Write continues in v1.4.2 influx to the same database without any errors

__Actual behavior:__ Error while creating the corresponding shard directory with the below mentioned error:
```
{"error":"[shard 301] mkdir /var/lib/influxdb/data/sparkAutomation/autogen/301: permission denied"}
```
__Additional info:__ 

- Stack trace seen in the program
```
17:14:16 [25-02-2018 17:12:32] - jenkinsbot:INFO:test_issue_map:{'tpHostMeetAtSiteGuestUsernameAtSite': [(170, 'Meeting has not started')]}
17:14:16 [25-02-2018 17:12:32] - jenkinsbot:INFO:----------------------------------------------------------------------------------------------------
17:14:17 Traceback (most recent call last):
17:14:17 File "jenkinsbot.py", line 660, in
17:14:17 bot.process_jenkins_build()
17:14:17 File "jenkinsbot.py", line 627, in process_jenkins_build
17:14:17 datetime_obj, job_msg_result, parse_logs_result, job_number, joburl, env, influx_client)
17:14:17 File "jenkinsbot.py", line 262, in process_failed_success_with_retries_build
17:14:17 jobid, parse_logs_result[3], self._job_name, success_status_val):
17:14:17 File "/jenkins_log_analyzer/src/influx_dbmanager.py", line 22, in write_data_to_job_results_t
17:14:17 result = write_data(client, db_data)
17:14:17 File "/jenkins_log_analyzer/src/influx_dbmanager.py", line 168, in write_data
17:14:17 result = client.write_points(data)
17:14:17 File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 468, in write_points
17:14:17 tags=tags, protocol=protocol)
17:14:17 File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 532, in _write_points
17:14:17 protocol=protocol
17:14:17 File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 312, in write
17:14:17 headers=headers
17:14:17 File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 267, in request
17:14:17 raise InfluxDBServerError(response.content)
17:14:17 influxdb.exceptions.InfluxDBServerError: {"error":"[shard 301] mkdir /var/lib/influxdb/data/sparkAutomation/autogen/301: permission denied"}
17:14:17
17:14:17 Build step 'Execute shell' marked build as failure
```

**Comment by RagHarnoor** [comment]
Hi, any other information needed for this issue? let me know. Thanks

**Comment by aanthony1243** [comment]
Hi, Adam from the influx team here.  
1. can you give a listing of filenames from the backup folder?  
2. was the 1.4.2 database empty when you did the import?
3. Did you use the same user for the restore, as you do to start the influx DB service?  

The issue here appears to be incorrect Unix permissions on one or more data directories.  We just have to trace out when/where it happens, and we should be able to get you up and running.

**Comment by RagHarnoor** [comment]
Hi Adam, Sorry for the delayed response. Here are the details asked for:
1. Following are the file names seen in the backup folder:
<img width="1014" alt="screen shot 2018-04-10 at 12 55 21" src="https://user-images.githubusercontent.com/7761894/38542052-7c5f7826-3cbe-11e8-9188-eec6cf09f6c2.png">

2. No, the 1.4.2 database was not empty when the import was done. There was already some data in the measurements. I was trying to restore the older data of these measurements. 
3. We have only 1 user created. So, yes, the same user which was used to start the influx db service was used to restore the data.

**Comment by aanthony1243** [comment]
@RagHarnoor  could you check the user/group permissions on folders in /var/lib/influxdb/data  ?  

Also, what commands did you use to restore the data?  Did you restore the metadata prior to restoring the database?  If you do not, there will be collisions in the shard space.  unfortunately there's not a great way to merge old data into an existing database in 1.4.2.  If that is your use-case, you may need to export the data using `influx_inspect export `  and then import the resulting line protocol in the usual way.

**Comment by RagHarnoor** [comment]
@aanthony1243 

- This was the command used to restore the data 
```influxd backup -database -since 2017-02-01T00:00:00Z sparkAutomation tmp/backup1/```

- I think the metadata was not restored. Any idea how I resolve the shard space collision now? Would 
```influx_inspect export``` help resolve the collision now?

**Comment by aanthony1243** [comment]
@RagHarnoor   on 1.4.2 and earlier,  backup/restore is a pretty destructive process.  So we are on the same page, it takes 3 steps to restore a database: 
1.  Run a backup to get metadata + data directory backup files
2.  Run a restore to restore the metadata,  `influxd restore -metadir /path/to/metadir /path/to/backup`
3.  Run a restore to restore the actual data:  `influxd restore -datadir /path/to/datadir /path/to/backup`

I see a few potential problems in what you've done: 
1.  The datadir appears to be owned by `root`.   Is the influxd server running as root?  If not, then the DB will be unable to create new shards.  
2.  If you restore the -datadir   make sure you run it as the same user as the influxd service
3.  If you run only the -datadir restore without also running the -metadir  restore, the data will be corrupted.   You need to first run the metadir restore, and then run the data dir restore. 

Please be advised that any data currently existing on the system will be deleted by the restore process.

**Comment by RagHarnoor** [comment]
@aanthony1243 

- If I want to move to 1.5X and above. How do I go about doing it? I want to get all the data from this 1.4.2 database in there but without the shard collision. Can you tell me how I can go about doing that?

**Comment by aanthony1243** [comment]
@RagHarnoor   first of all, if you ran a data-dir restore on the 1.4.2 server, whatever data was present before the restore was deleted.  Do you have that data stored elsewhere?

If you want to unify the data between the 1.2.2 database and the 1.4.2 database, I would: 

1.  Here is some information on upgrading your 1.4.2 server to 1.5: https://docs.influxdata.com/influxdb/v1.5/administration/upgrading/

2.  Use `influxd backup -database sparkAutomation /backup/dir`  on the 1.2.2 db to create a backup of your target database to the backup dir of your choosing

3.  Copy the backup files to the upgraded 1.5 server

4. IMPORTANT: when you run the restore on the 1.5 server make sure you use the `-online` flag.  
 run `influxd restore -online -db sparkAutomation -newdb sparkAutomationTmp /backup/dir`

5.  Once the data is restored, you will have two DB's:  sparkAutomation  and sparkAutomationTmp.  You can sideload the TMP data using:   
```
>  use sparkAutomationTmp
> SELECT * INTO sparkAutomation..:MEASUREMENT FROM /.*/ GROUP BY *
```
