### ISSUE TITLE
show tag values returns panic:runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by scotloach** [influxdata/influxdb#9539]
### Bug report

__System info:__ InfluxDB 1.5, built from released docker container.  inmem indexes.

__Steps to reproduce:__

This is reproduced using an existing database; I wasn't able to reproduce it with a trivial new database but I hope this will provide enough information to narrow down the bug.
```
> SHOW TAG VALUES FROM <meas> WITH KEY = <tag_key> WHERE "x" = 1
ERR: SHOW TAG VALUES FROM <meas> WITH KEY = <tag_key> WHERE x = 1 [panic:runtime error: invalid memory address or nil pointer dereference]
```

If I remove the WHERE clause, it works fine.  I can replace the "x" and value with anything, either a valid or invalid tag, and it has the same error.

This was working fine before I updated to 1.5.

**Comment by Programie** [comment]
I've exactly the same issue as already described in https://github.com/influxdata/influxdb/issues/8786#issuecomment-371897162.

**Comment by e-dard** [comment]
Thanks for this @scotloach. I've opened a separate issue to track both of these occurrences.

**Comment by e-dard** [comment]
@scotloach - if we are unable to reproduce this, would you be willing to securely and privately upload your database to us, so we can repro using your data?

**Comment by scotloach** [comment]
yes I could do that.
