### ISSUE TITLE
Service silently crashes after start

### ISSUE THREAD

**Issue by vsviridov** [influxdata/influxdb#954]
Today we've experienced a situation when the database stopped responding to HTTP queries on the admin interface.
After the restart it stopped responding to all HTTP requests and crashes occasionally.
If I restart it with clean data folder it starts normally.
There's nothing in the log that points to any potential issues.

Please advise.

**Comment by rahul9878** [comment]
I am also facing this issue( influx service is failing after some seconds), but didn't find any working solution for this issue.

content of my log file is:
2015/11/24 00:06:14 InfluxDB starting, version 0.9.4.2, branch 0.9.4, commit da1b59e
2015/11/24 00:06:14 Go version go1.5, GOMAXPROCS set to 1
2015/11/24 00:06:15 Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/11/24 00:06:15 Using data dir: /var/opt/influxdb/meta
[metastore] 2015/11/24 00:06:15 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2015/11/24 00:06:15 Node at localhost:8088 [Follower]
[metastore] 2015/11/24 00:06:16 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2015/11/24 00:06:16 Updated node id=1 hostname=localhost:8088
[monitor] 2015/11/24 00:06:16 Starting monitor system
[monitor] 2015/11/24 00:06:16 'build' registered for diagnostics monitoring
[monitor] 2015/11/24 00:06:16 'runtime' registered for diagnostics monitoring
[monitor] 2015/11/24 00:06:16 'network' registered for diagnostics monitoring
[monitor] 2015/11/24 00:06:16 'system' registered for diagnostics monitoring
[store] 2015/11/24 00:06:16 Using data dir: /var/opt/influxdb/data
[monitor] 2015/11/24 00:06:16 Storing statistics in database '_internal' retention policy '', at interval 10s
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/_internal/monitor/61
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/_internal/monitor/64
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/_internal/monitor/65
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/_internal/monitor/66
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/_internal/monitor/67
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/eventdb/default/15
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/14
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/24
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/34
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/4
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/46
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/57
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/6
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/62
[wal] 2015/11/24 00:06:17 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:17 WAL writing to /var/opt/influxdb/wal/testdb/default/13
[wal] 2015/11/24 00:06:17 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:17 WAL writing to /var/opt/influxdb/wal/testdb/default/2
[wal] 2015/11/24 00:06:18 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:18 WAL writing to /var/opt/influxdb/wal/testdb/default/23
[wal] 2015/11/24 00:06:18 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:18 WAL writing to /var/opt/influxdb/wal/testdb/default/3
[wal] 2015/11/24 00:06:18 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:18 WAL writing to /var/opt/influxdb/wal/testdb/default/33
[wal] 2015/11/24 00:06:18 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:18 WAL writing to /var/opt/influxdb/wal/testdb/default/37
[wal] 2015/11/24 00:06:18 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:18 WAL writing to /var/opt/influxdb/wal/testdb/default/38
[wal] 2015/11/24 00:06:19 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:19 WAL writing to /var/opt/influxdb/wal/testdb/default/45
[wal] 2015/11/24 00:06:19 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:19 WAL writing to /var/opt/influxdb/wal/testdb/default/48
[wal] 2015/11/24 00:06:21 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:21 WAL writing to /var/opt/influxdb/wal/testdb/default/5
[wal] 2015/11/24 00:06:21 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:21 WAL writing to /var/opt/influxdb/wal/testdb/default/56
[wal] 2015/11/24 00:06:22 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:22 WAL writing to /var/opt/influxdb/wal/testdb/default/63
[wal] 2015/11/24 00:06:22 reading WAL files to flush to index
[retention] 2015/11/24 00:06:22 retention policy enforcement terminating
[monitor] 2015/11/24 00:06:22 shutting down monitor system
[monitor] 2015/11/24 00:06:22 terminating storage of statistics
run: open server: open tsdb store: failed to open shard 63: load metadata index: read block: EOF

can you please help me how to fix this issue
Thanks.

**Comment by ThiruKumar** [comment]
Hello Friends,

 i have single influxdb node having data over 170GB of data. things were working well. but today it crashed suddenly. after restart using "service influxdb restart" the status shows 

sometimes "influxdb Process is not running [ FAILED ]"
and after 10 seconds "influxdb Process is not running [ OK ]"
and again after 10 seconds "influxdb Process is not running [ FAILED ]"
again after 10 seconds "influxdb Process is not running [ OK ]"

when i visit log file it shows the following error. please help me friends. i cant access the "8083","8086" ports.
panic: not ordered: 712 1455942607000000000 >= 1455942607000000000goroutine 676 [running]:
panic(0xa3c020, 0xc84380d9e0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/influxdb/tsdb/engine/tsm1.Values.assertOrdered(0xc857ed4000, 0x3db, 0x3db)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.gen.go:39 +0x2fc
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).chunk(0xc84d7a3c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1026 +0x70
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).combine(0xc84d7a3c00, 0xc85a6d1201, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:953 +0x16f
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).merge(0xc84d7a3c00)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:901 +0x12f
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).Next(0xc84d7a3c00, 0xc803f39cef)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:868 +0xbff
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0xc848fe9f40, 0xc8607bd090, 0x42, 0x7f32fa3b8288, 0xc84d7a3c00, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:607 +0x53b
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0xc848fe9f40, 0x2d4, 0x4, 0x7f32fa3b8288, 0xc84d7a3c00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:554 +0x3a1
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).compact(0xc848fe9f40, 0x486200, 0xc8605cce40, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:513 +0x4fe
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).CompactFull(0xc848fe9f40, 0xc8605cce40, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:526 +0xfd
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel.func1(0xc8531b32f0, 0xc8411b4180, 0x3, 0x0, 0x0, 0xc8605cce40, 0x4, 0x4)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:767 +0xfd7
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:786 +0x265
[run] 2016/08/20 13:37:44 InfluxDB starting, version 1.0.0-beta1, branch master, commit bf3c22689b68a6d03d20eac695a7049a7c78b21d

**Comment by ThiruKumar** [comment]
Sorry friends, the issue was rectified by my colleague(Thomas Kurz), by simple version update. now the influxdb up again. my influxdb was beta1.0 and the influxdb is upgraded to beta1.3 version. i wasn't aware of it. and it again working like a charm. thanks for the bug fixes.

**Comment by ThiruKumar** [comment]
Again the same issue is coming in "beta1.3 version" also.i should find another way to fix it. I thought everything was ok. but again the error persists.

Below is the output of "/var/log/influxdb/influxd.log"

panic: not ordered: 793 1455352203000000000 >= 1455352203000000000

goroutine 2026 [running]:
panic(0xa4ac60, 0xc87f73d340)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/influxdb/tsdb/engine/tsm1.Values.assertOrdered(0xc8c5980000, 0x3e8, 0x3e8)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.gen.go:51 +0x2fc
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).chunk(0xc855124100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1138 +0x70
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).combine(0xc855124100, 0xc8c620d001, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1065 +0x16f
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).merge(0xc855124100)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1013 +0x12f
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).Next(0xc855124100, 0xc80425fe9f)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:980 +0xbff
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0xc8a309ad20, 0xc8622a4fa0, 0x42, 0x7f98c1f0a3d8, 0xc855124100, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:719 +0x53b
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0xc8a309ad20, 0x17c, 0x4, 0x7f98c1f0a3d8, 0xc855124100, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:666 +0x3a1
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).compact(0xc8a309ad20, 0x0, 0xc822714a00, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:602 +0x4fe
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).CompactFull(0xc8a309ad20, 0xc822714a00, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:615 +0x115
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel.func1(0xc8ba4c8ad0, 0xc893d49930, 0x3, 0xc8724aa800, 0x0, 0xc822714a00, 0x4, 0x4)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:844 +0x113c
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:866 +0x28e
[run] 2016/08/20 14:42:52 InfluxDB starting, version 1.0.0-beta3, branch master, commit 30efa2d922babde5ccbdf09960e510c0de5e0bcb
[run] 2016/08/20 14:42:52 Go version go1.6.2, GOMAXPROCS set to 8

**Comment by shaunwarman** [comment]
Same issue.. all the sudden too. Not sure why. It's been working for a long time (>2 years)

Limits:
```
stack@influx-7197:/opt/influxdb/shared$ cat /proc/1799/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             120162               120162               processes
Max open files            65536                65536                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       120162               120162               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

Shards:
`max_open_shards=0 // unlimited` which I have grafana configs which creates about 20 shards

Queries:
I also have heka anomaly detection querying influx and I do see these iffy queries at startup of log.txt:
```
[2016/09/02 11:25:20 PDT] [INFO] (github.com/influxdb/influxdb/server.(*Server).ListenAndServe:139) Starting admin interface on port 8083
[2016/09/02 11:25:20 PDT] [INFO] (github.com/influxdb/influxdb/server.(*Server).ListenAndServe:156) Graphite input plugins is disabled
[2016/09/02 11:25:20 PDT] [INFO] (github.com/influxdb/influxdb/server.(*Server).ListenAndServe:178) Collectd input plugins is disabled
[2016/09/02 11:25:20 PDT] [INFO] (github.com/influxdb/influxdb/server.(*Server).ListenAndServe:187) UDP server is disabled
[2016/09/02 11:25:20 PDT] [INFO] (github.com/influxdb/influxdb/server.(*Server).ListenAndServe:187) UDP server is disabled
[2016/09/02 11:25:20 PDT] [INFO] (github.com/influxdb/influxdb/server.(*Server).ListenAndServe:216) Starting Http Api server on port 8086
[2016/09/02 11:25:21 PDT] [INFO] (github.com/influxdb/influxdb/coordinator.(*Coordinator).RunQuery:41) Start Query: db: npmjs, u: root, q: select count(status) from "request" where (time < 1472840700000000000) AND (time > 1472840580000000000) group by time(1m)
[2016/09/02 11:25:21 PDT] [INFO] (github.com/influxdb/influxdb/coordinator.(*Coordinator).RunQuery:41) Start Query: db: npmjs, u: root, q: select count(status) from "request" where (time < 1472840721000000000) AND (time > 1472840623000000000) group by time(1s)
```

Any ideas? Turned off heka and restarted influx and still a no go. Silently dies after about 30 seconds. Changed logging to `debug` in `config.toml` and still nothing obvious.
