### ISSUE TITLE
show tag keys returns empty rows

### ISSUE THREAD

**Issue by scotloach** [influxdata/influxdb#9545]
### Bug report

__System info:__ InfluxDB 1.5 built from standard docker container, inmem indexes.

__Steps to reproduce:__

I updated from 1.4 to 1.5 on a large system with multiple databases.
Since the upgrade, I noticed that on some (but not all) of the databases, a "show tag keys from <rp>.<measurement>" query returns the first row as an empty string, and then the actual tag keys associated with the measurement.

Looks like a regression from 1.4.

Here is actual output, with names redacted.

```
> show tag keys from "autogen"."meas"
name: meas
tagKey
------

tag1
tag2
tag3
tag4
tag5
tag6
tag7
tag8
tag9
tag10
```

**Comment by e-dard** [comment]
@scotloach do you have some test data that can be used to reproduce this issue?

**Comment by e-dard** [comment]
Reproduced with the following:

```
CREATE DATABASE ""
USE 
INSERT cpu,tag0=v\, value=1
SHOW TAG KEYS
```

Results in:
```
name: cpu
tagKey
------

tag0
```

Also, rather than this being a formatting issue, it looks like the index is seeing multiple tag keys:

```
> SHOW TAG KEY CARDINALITY
name: cpu
count
-----
2
>
```

Yet:

```
> SHOW SERIES
key
---
cpu,tag0=v\,
>
```

It's affecting both `inmem` and `tsi1`. I have confirmed it's not in `1.4`.
