### ISSUE TITLE
Deploying InfluxDB 1.4.2 from scratch: db "_internal" not found

### ISSUE THREAD

**Issue by jochenehret** [influxdata/influxdb#9547]
Hi,

we're running InfluxDB 1.4.2 and we want to grant read permissions for the "_internal" db for one user. When we deploy from scratch, it seems that the "_internal" db is not immediately ready:

__Steps to reproduce:__

```
influx -username root -password <password> -execute "CREATE USER grafana_user WITH PASSWORD <password>"
influx -username root -password <password> < bootstrap.sql
```
bootstrap.sql contains various `CREATE`, `SET PASSWORD` and `GRANT` statements. The relevant ones are:
```
CREATE DATABASE metrics
...
GRANT READ ON metrics TO grafana_user;
GRANT READ ON _internal TO grafana_user;
...
```
__Expected behavior:__
`GRANT READ ON _internal` is executed successfully.

__Actual behavior:__
We're getting `ERR: database not found: _internal`. After re-executing the above statements, everything works.

Do we have to wait some time until `_internal` is ready? Or do we have to switch databases with `USE`?

Thanks for you support!

**Comment by e-dard** [comment]
`_internal` won't appear on a fresh install until the monitoring service has ticked over. It does this every 10 seconds. You may want to add a delay during setup to your deployment scripts.

**Comment by jochenehret** [comment]
Ah, ok that helps! Thanks for the quick reply!
