### ISSUE TITLE
InfluxDB 1.5.0 not listening to http after starting the process

### ISSUE THREAD

**Issue by nettosama** [influxdata/influxdb#9550]
### Bug report

__System info:__ InfluxDB 1.5.0, Ubuntu 16.04.4 (tested with the same data in ArchLinux also)

__Steps to reproduce:__

1. Start InfluxDB service
2. Try to connect to the http service or check bound ports (8086)

__Expected behavior:__ 8086 port listening

__Actual behavior:__ No open port, no http service

__Additional info:__ systemd log:
```
Mar 12 09:10:03 userver systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
Mar 12 09:10:03 userver influxd[3483]: ts=2018-03-12T12:10:03.657940Z lvl=info msg="InfluxDB starting" log_id=06nXj02G000 version=1.5.0 branch=1.5 commit=6ac835404e7e64ea7299a6eebcce1ab1ef15fe3c
Mar 12 09:10:03 userver influxd[3483]: ts=2018-03-12T12:10:03.657982Z lvl=info msg="Go runtime" log_id=06nXj02G000 version=go1.9.2 maxprocs=4
Mar 12 09:10:03 userver influxd[3483]: ts=2018-03-12T12:10:03.759523Z lvl=info msg="Using data dir" log_id=06nXj02G000 service=store path=/var/lib/influxdb/data
Mar 12 09:10:03 userver influxd[3483]: ts=2018-03-12T12:10:03.759568Z lvl=info msg="Open store (start)" log_id=06nXj02G000 service=store trace_id=06nXj0Rl000 op_name=tsdb_open op_event=start
```

The process is running, but no connections are accepted. The configuration file is the default one.

It was running correctly (for around 2 months) until yesterday.

Only deleting the "data" folder I can get it to start running again correctly.

**Comment by jsternberg** [comment]
How much data do you have? It might be spending a long time opening the data store.

Was this an upgrade from 1.4 to 1.5?

@e-dard could this be related to any changes with the index and migrating the index?

**Comment by e-dard** [comment]
@nettosama is this reproducible? If so, could you provide steps?

Is the log you provided the entire log?

**Comment by nettosama** [comment]
That's the entire log I get out of influxd. There's no log in /var/log/influxdb/.

The only way to get it to start again is by deleting the /var/lib/influxdb/data/home_assistant/ folder.

This is the log when it runs after deleting that folder:

```
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.038145Z lvl=info msg="InfluxDB starting" log_id=06naMOcW000 version=1.5.0 branch=1.5 commit=6ac835404e7e64ea7299a6eebcce1ab1ef15fe3c
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.038175Z lvl=info msg="Go runtime" log_id=06naMOcW000 version=go1.9.2 maxprocs=4
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138673Z lvl=info msg="Using data dir" log_id=06naMOcW000 service=store path=/var/lib/influxdb/data
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138772Z lvl=info msg="Open store (start)" log_id=06naMOcW000 service=store trace_id=06naMP0W001 op_name=tsdb_open op_event=start
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138809Z lvl=info msg="Open store (end)" log_id=06naMOcW000 service=store trace_id=06naMP0W001 op_name=tsdb_open op_event=end op_elapsed=0.039ms
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138832Z lvl=info msg="Opened service" log_id=06naMOcW000 service=subscriber
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138838Z lvl=info msg="Starting monitor service" log_id=06naMOcW000 service=monitor
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138842Z lvl=info msg="Registered diagnostics client" log_id=06naMOcW000 service=monitor name=build
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138846Z lvl=info msg="Registered diagnostics client" log_id=06naMOcW000 service=monitor name=runtime
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138850Z lvl=info msg="Registered diagnostics client" log_id=06naMOcW000 service=monitor name=network
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138860Z lvl=info msg="Registered diagnostics client" log_id=06naMOcW000 service=monitor name=system
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138889Z lvl=info msg="Starting precreation service" log_id=06naMOcW000 service=shard-precreation check_interval=10m advance_period=30m
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138897Z lvl=info msg="Starting snapshot service" log_id=06naMOcW000 service=snapshot
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138901Z lvl=info msg="Starting continuous query service" log_id=06naMOcW000 service=continuous_querier
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.138905Z lvl=info msg="Starting HTTP service" log_id=06naMOcW000 service=httpd authentication=false
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.139090Z lvl=info msg="Listening on HTTP" log_id=06naMOcW000 service=httpd addr=[::]:8086 https=false
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.139126Z lvl=info msg="Starting retention policy enforcement service" log_id=06naMOcW000 service=retention check_interval=30m
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.139138Z lvl=info msg="Storing statistics" log_id=06naMOcW000 service=monitor db_instance=_internal db_rp=monitor interval=10s
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.139767Z lvl=info msg="Sending usage statistics to usage.influxdata.com" log_id=06naMOcW000
Mar 12 10:13:31 userver influxd[10973]: ts=2018-03-12T13:13:31.140205Z lvl=info msg="Listening for signals" log_id=06naMOcW000
```

It gets to open store (end).

I don't really know if upgrading from an earlier version was what caused this, but this is the latest upgrade:

```
Upgrade: python-twisted-core:amd64 (16.0.0-1, 16.0.0-1ubuntu0.2), friendly-recovery:amd64 (0.2.31, 0.2.31ubuntu1), python-twisted-bin:amd64 (16.0.0-1, 16.0.0-1ubuntu0.2), gitlab-ce:amd64 (10.5.2-ce.0, 10.5.3-ce.0), nodejs:amd64 (8.9.4-1nodesource1, 8.10.0-1nodesource1), libpq5:amd64 (9.5.11-0ubuntu0.16.04, 9.5.12-0ubuntu0.16.04), libpq-dev:amd64 (9.5.11-0ubuntu0.16.04, 9.5.12-0ubuntu0.16.04), chronograf:amd64 (1.4.1.3-1, 1.4.2.2-1), grafana:amd64 (5.0.0, 5.0.1), influxdb:amd64 (1.4.2-1, 1.5.0-1)
```

**Comment by nettosama** [comment]
Update: Reverted back to the influxdb_1.4.2_amd64.deb package, and everything works correctly:

```
Mar 12 15:05:26 userver influxd[32297]: [I] 2018-03-12T18:05:26Z Starting snapshot service service=snapshot
Mar 12 15:05:26 userver influxd[32297]: [I] 2018-03-12T18:05:26Z Starting continuous query service service=continuous_querier
Mar 12 15:05:26 userver influxd[32297]: [I] 2018-03-12T18:05:26Z Starting HTTP service service=httpd
Mar 12 15:05:26 userver influxd[32297]: [I] 2018-03-12T18:05:26Z Authentication enabled:false service=httpd
Mar 12 15:05:26 userver influxd[32297]: [I] 2018-03-12T18:05:26Z Listening on HTTP:[::]:8086 service=httpd
Mar 12 15:05:26 userver influxd[32297]: [I] 2018-03-12T18:05:26Z Starting retention policy enforcement service with check interval of 30m0s service=retention
Mar 12 15:05:26 userver influxd[32297]: [I] 2018-03-12T18:05:26Z Listening for signals
Mar 12 15:05:26 userver influxd[32297]: [I] 2018-03-12T18:05:26Z Storing statistics in database '_internal' retention policy 'monitor', at interval 10s service=monitor
Mar 12 15:05:26 userver influxd[32297]: [I] 2018-03-12T18:05:26Z Sending usage statistics to usage.influxdata.com
Mar 12 15:07:19 userver influxd[32297]: [I] 2018-03-12T18:07:19Z SELECT "key" FROM home_assistant.autogen._series LIMIT 1 service=query
```

Will keep this version until a related fix is patched.

**Comment by e-dard** [comment]
@nettosama does this happen every time you try to run `1.5.0` with the `/var/lib/influxdb/data/home_assistant/ ` in place?

**Comment by nettosama** [comment]
Yes. Even on a second machine (OS: Archlinux). The biggest problem I'd say is that there isn't any log to point out possible problems. Maybe it's a migration issue?

For now it's running (Ubuntu 16.04.4, 1.4.2).

**Comment by ragzilla** [comment]
I'm getting this on a 1.3.5 -> 1.5.0 upgrade as well.  Rolled package back to 1.4.2 and it started right up even with no changes to index-version (I switched to tsi1 during the 1.5.0 upgrade).

**Comment by csari-chimera** [comment]
Having exactly the same issue after upgrading to 1.5 on Ubuntu 16.04 (AWS) from a previous version  - I did the second upgrade to 1.5.1 today morning but the results are the same. The config file is also the same for all installation. Influx does not bind to the HTTP port, started to eat 50G memory and does a big load on the machine.

**Comment by e-dard** [comment]
@csari-chimera are you running `inmem` or `tsi1`?

**Comment by csari-chimera** [comment]
@e-dard it's inmem

**Comment by rbetts** [comment]
Can anyone reproducing this share the database folder with us? We have a private method of sharing that data vs. uploading it here.  We would really appreciate a way to reproduce.

**Comment by csari-chimera** [comment]
@rbetts Hey, We have three TICK instances. One of them was dead yesterday, and one them died today. I have one instance which will suffer this issue as soon as I restart the service on it. Just to clarify what I got, and what were the steps:

- **Machine**: 2 vCPU and 8GB of RAM (AWS EC2 instance)

- **OS**: 
```# uname -a
Linux ip-10-20-1-36 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

- **Upgrade with apt**: 
```Start-Date: 2018-03-16  13:10:26 
Upgrade: influxdb:amd64 (1.4.2-1, 1.5.0-1)```

- **Issue**: after upgrading from 1.4.2-1 to 1.5.0-1 or to 1.5.1-1 everything seems fine, except after 3-4 days huge IO is generated on the machine, and only able to resolve it by restarting the InfluxDB. But as soon as I restart it, it does not bind anymore to the HTTP port (I did a debug level setting in the conf, but I never had success to have appropriate logs from Influx, and it doesn't matter what I do, it goes to the syslog. To "repair" the issue I'm deleting the content of the data folder, restart InfluxDB and works again. 

Config file for InfluxDB is attached (as txt...): [influxdb.conf.txt](https://github.com/influxdata/influxdb/files/1855591/influxdb.conf.txt)

What else information or anything else do you need?

**Comment by spolyack** [comment]
I ran into this exact same issue, with starting "hanging" after "Open store (start)". The problem ended up being that I naively ran the 'influxd_inspect buildtsi' command as root, and not as the influxdb user. This resulted in the new ts1 index files being owned as root. Although they were readable, they were not writeable.

YMMV, but recursively chowning my data directory resolved this for me and allowed InfluxDB 1.5.0 to start.

**Comment by dgnorton** [comment]
@spolyack thanks for the info. What did the ifluxdb log show in that case?

/cc @e-dard

**Comment by kalidasya** [comment]
same issue here, I updated from 1.1.0 with enabling tsi, I had the "running the `influxd_inspect buildtsi` as root" problem (it said permission denied in the log) so I changed the owner, but influxdb still does not start. 
Last message I see is:
```
Apr 13 07:42:41 ------- influxd[26803]: ts=2018-04-13T07:42:41.651852Z lvl=info msg="Open store (start)" log_id=07RV8sxG000 service=store trace_id=07RV8sxl000 op_name=tsdb_open op_event=start
```
No CPU usage, running it on Centos 7.2

**Comment by e-dard** [comment]
@csari-chimera did recursively chowning the data directory with the correct user (I guess influxdb:influxdb or whatever use runs the dB) fix the problem?

**Comment by csari-chimera** [comment]
@e-dard Nope, since I only do an upgrade - not other stuff was executed like no inmem-tsi1 migration.

**Comment by xaochuan1987** [comment]
I'm getting this bug with InfluxDB 1.2.4 and 1.5.2.

**Comment by sammcj** [comment]
We're also getting this bug with CentOS 7.5 and InfluxDB 1.5.2.

* InfluxDB is hammering the CPU sending info level logs to journald.
* All files in `/var/lib/influxdb` are owned by the influxdb user.
* InfluxDB has not created a log in the `/var/log/influxdb` directory despite having this specified as the log location.
* There are no errors in journald for influxdb.

**Comment by e-dard** [comment]
@sammcj you mention it's hammering the CPU by sending lots of logs, but you don't see any of the logs? Did you maybe take profiles to determine this?

**Comment by dpedu** [comment]
I'm seeing this bug with InfluxDB 1.7.2.

**Comment by jfschneider** [comment]
Any news on this? We have the same problem as of today (that we noticed). RHEL7, InfluxDB 1.6.3. Updated to 1.7.3 to no effect. I have errors in the journal, here and there, though it seems not reproducably after a restart:
Jan 14 14:30:55 ... influxd[11452]: ts=2019-01-14T13:30:55.051470Z lvl=info msg="Series partition compaction (start)" log_id=0C~6qFul000 partition=4 trac
e_id=0C~8lrnl000 op_name=series_partition_compaction path=/web/databases/influxdb/data/icinga2/_series/04 op_event=start
Jan 14 14:30:55 ... influxd[11452]: fatal error: runtime: out of memory
Jan 14 14:30:55 ... influxd[11452]: runtime stack:
Jan 14 14:30:55 ... influxd[11452]: runtime.throw(0x123d974, 0x16)
Jan 14 14:30:55 ... influxd[11452]: /usr/local/go/src/runtime/panic.go:608 +0x72
Jan 14 14:30:55 ... influxd[11452]: runtime.sysMap(0xe664000000, 0x154000000, 0x1da9518)
Jan 14 14:30:55 ... influxd[11452]: /usr/local/go/src/runtime/mem_linux.go:156 +0xc7
Jan 14 14:30:55 ... influxd[11452]: runtime.(*mheap).sysAlloc(0x1d8f780, 0x154000000, 0x0, 0x40e1d7)
Jan 14 14:30:55 ... influxd[11452]: /usr/local/go/src/runtime/malloc.go:619 +0x1c7
Jan 14 14:30:55 ... influxd[11452]: runtime.(*mheap).grow(0x1d8f780, 0xaa000, 0x0)
Jan 14 14:30:55 ... influxd[11452]: /usr/local/go/src/runtime/mheap.go:920 +0x42
Jan 14 14:30:55 ... influxd[11452]: runtime.(*mheap).allocSpanLocked(0x1d8f780, 0xaa000, 0x1da9528, 0x0)
Jan 14 14:30:55 ... influxd[11452]: /usr/local/go/src/runtime/mheap.go:848 +0x337
Jan 14 14:30:55 ... influxd[11452]: runtime.(*mheap).alloc_m(0x1d8f780, 0xaa000, 0x101, 0x149ea88)

So far only soluation seems to be deleting all data and starting fresh. Could this be size related? The data dir is ~260G in size now.

**Comment by nettosama** [comment]
As a followup, I tried updating once again after a year, now to version 1.7.4, but I got the same error, so I'm still running version 1.4.2
