### ISSUE TITLE
Flaky Test

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#9554]
During CI checks for #9551 `TestService_ModeANY` kept failing in Circle. I was unable to make it fail locally. The output looks like:

```
--- FAIL: TestService_ModeANY (0.02s)
	service_test.go:254: expected points request```

I have skipped the test in #9551

**Comment by jacobmarble** [comment]
I'll start by writing a script that just runs the test lots of times, record a baseline failure rate.

**Comment by jacobmarble** [comment]
This command builds the test, then runs it 1000000 times, completes in 66 seconds:
```
go test -run TestService_ModeANY -count 1000000
```

It passes on my workstation.

**Comment by jacobmarble** [comment]
Playing with CircleCI, see if I can reduce latency to complete. Currently ~18m, but only ~5m on my laptop after the first run, because the docker image doesn't have to be rebuilt. Multiple improvements are available.

**Comment by jacobmarble** [comment]
Test has been re-enabled, will watch for failure over the next few days.
