### ISSUE TITLE
Clear the points in a batchpoints structure ?

### ISSUE THREAD

**Issue by telemac** [influxdata/influxdb#9558]
Hello,

In the client library, may be it could be practical to reuse a batchpoints structure, by allowing to clear its contained points.

May be just adding such a function is enough ? I made some tests that worked but i don't have the whole picture.

```go
func (bp *batchpoints) ClearPoints() {
	bp.points = nil
}
```

**Comment by e-dard** [comment]
Hi @telemac, do you have profiles or data to show that this is a performance bottleneck?
