### ISSUE TITLE
Line Protocol: unable to parse...invalid float

### ISSUE THREAD

**Issue by brettwooldridge** [influxdata/influxdb#9560]
### Bug report

__System info:__ InfluxDB 1.5, Linux

__Steps to reproduce:__

Step 1:
Try to insert, via line protocol:
```
...
storagePercentUsed,_host=52dc1127-e2fe-5bb5-bd69-1b2863aaf080,_index=36,_network=Default type="snmp",value=1.797693134862316e+308 1520922581346
...
```
Step 2:
Error is received:
```
{"error":"partial write: unable to parse 'storagePercentUsed,_host=52dc1127-e2fe-5bb5-bd69-1b2863aaf080,_index=36,_network=Default type=\"snmp\",value=1.797693134862316e+308 1520922581346': invalid float dropped=0"}
```
__Expected behavior:__ 
AFAIK, ``1.797693134862316e+308`` is a valid IEEE 754 64-bit representation, so I would expect the point to be inserted.

__Actual behavior:__ 
A 400 error was received in the HTTP response.

Wireshark dump attached (text form).
[wireshark.txt](https://github.com/influxdata/influxdb/files/1805775/wireshark.txt)

EDIT: In Java, when I run this code...
```java
01  double d = Double.parseDouble("1.797693134862316e+308");
02  System.out.println(d);
```
Line 2 prints the word "Infinity".  (But the value is still validly parsed as an IEEE 754 64-bit double value).

**Comment by e-dard** [comment]
@brettwooldridge hi, InfluxDB is built using Go, and as such we support whatever the Go runtime supports. In this case, the highest double-precision float is `1.7976931348623157e+308`. 

Floating point values are not precisely represented and so different languages might have different representations. 

https://play.golang.org/p/7TPBAuzdHo4
