### ISSUE TITLE
SHOW TAG VALUES WITH KEY = "host" returns no data

### ISSUE THREAD

**Issue by rreilly-edr** [influxdata/influxdb#9561]
### Bug report
influxdb 1.5.0 
ubuntu 14.04

__Steps to reproduce:__

1.  SHOW TAG VALUES WITH KEY = "host"

__Expected behavior:__ 
list all tag values with key "host"

__Actual behavior:__ 
Nothing is returned
__Additional info:__ 
I definitely have tag values with the key "host"
```
load_avg_one,host=tf-p-xx-xx-e-00,metric=load-metrics
load_avg_one,host=tf-p-xx-xx-e-01,metric=load-metrics
load_avg_one,host=tf-p-xx-xx-e-02,metric=load-metrics
load_avg_one,host=tf-p-xx-xx-k-00,metric=load-metrics
load_avg_one,host=tf-p-xx-xx-l-00,metric=load-metrics
```
This was working yesterday, I restarted influxdb and it just stopped working because of this 
templating in grafana is broken. there are no interesting log entries.

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
```
this fails with a 404, I changed it to my hostname as I am not listening on localhost
```
curl -o vars.txt "http://localhost:8086/debug/vars"
```
[gist](https://gist.github.com/rreilly-edr/ea9d0dea53a9c066e63679e5f35aebf0)
```
iostat -xd 1 30 > iostat.txt
```
[gist](https://gist.github.com/rreilly-edr/dd2a6cb4529ca6901d574399b0a5a971)

strange is this dose work, but returns only the tags for influxdb itself
```
show tag values with key = "hostname"
```
```
name: write
key      value
---      -----
hostname tf-p-xx-xx-00
```
as does 
```
show tag values with key =~ /^hostname$/
```
but not 
```
show tag values with key =~ /^host$/
```
I can select the value and tag 
```
time                 value      host
----                 -----      ----
2018-03-13T18:36:07Z 698818003  tf-p-zz-xx-e-00
2018-03-13T18:36:07Z 701569227  tf-p-zz-xx-e-01
2018-03-13T18:36:07Z 704201471  tf-p-zz-xx-e-02
2018-03-13T18:36:07Z 1162912754 tf-p-zz-xx-k-00
2018-03-13T18:36:07Z 4482675120 tf-p-zz-xx-l-00
2018-03-13T18:36:07Z 559988027  tf-p-zz-yy-00
2018-03-13T18:36:07Z 13780122   tf-p-zz-yy-00
2018-03-13T18:36:07Z 15234703   tf-p-zz-yy-00
2018-03-13T18:36:07Z 557511652  tf-p-zz-yy-00
2018-03-13T18:36:07Z 577228529  tf-p-zz-yy-00
2018-03-13T18:36:07Z 574795956  tf-p-zz-yy-00
2018-03-13T18:36:07Z 86708991   tf-p-zz-yy-00
```

**Comment by rreilly-edr** [comment]
So I upgraded to the latest nightly and this issue went away, hopefully 1.6.0 will be out soon

**Comment by rreilly-edr** [comment]
This actually did not fix my issue, i restored my old data and I still cannot see key values, not sure what happened, if there is any data needed for forensics i would really like to know what happened.

**Comment by e-dard** [comment]
@rreilly-edr are you using the `inmem` or `tsi1`?

I am unable to reproduce your issue. Could you provide test data that does?
