### ISSUE TITLE
Restore needs to skip shards not imported from metadata

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/influxdb#9565]
when importing metadata, a special case is when the _internal database metadata is imported.  Since this database is generated internally, it should not be overwritten by a restore.   

The meta-data restore correctly skips the _internal data references.  The shard restore does not.  

fix:  add check that a shard's ID is correctly mapped into the new system, skip if not found.   
also:   debug tests which should have caught this bug.

**Comment by e-dard** [comment]
Closed via #9569
