### ISSUE TITLE
Not able to connect to influx using influx CLI and using grafana whereas influxd is running

### ISSUE THREAD

**Issue by Vish17agr** [influxdata/influxdb#9572]
I am running influx DB 1.3.7 version in centos 7 with two CPUs
centos-release-7-3.1611.el7.centos.x86_64
centos-release-7-4.1708.el7.centos.x86_64 

I am ingesting millions of record in influx using java program.
After two days of data ingestion, my influx is not responding, while influxd is up and running.

While I try to connect to influx using influx CLI it throws a socket exception.
Failed to connect to http://localhost:8086: Get http://localhost:8086/ping: dial tcp [::1]:8086: getsockopt: connection refused
Please check your connection settings and ensure 'influxd' is running.
and from Grafana as well getting network Error: undefined.

I checked the memory usage:
![image](https://user-images.githubusercontent.com/17724050/37395441-3bd7ab3e-279c-11e8-9287-02ab51401560.png)
It shows 90% memory usage by the influx DB.
Data stored in the influx is of size 3GB

After 1-hour memory consumption reduces 27% and again start increasing exponentially.
After 20 min again memory consumption reaches 90%+.

Strange thing I noticed, I am to connect to influx using influx CLI after 30 min and then again influx CLI stopped working. During this period I have stopped all the writes into the influx.

Attached the influx DB conf file used:

[influxdb_conf.txt](https://github.com/influxdata/influxdb/files/1810535/influxdb_conf.txt)

**Comment by e-dard** [comment]
@Vish17agr sounds like you have possibly got a very high cardinality use-case. Please upgrade to `1.5.0`, which is much more performant than `1.3.7`. Once you have upgraded you could look at your cardinality for a given database and see how high it really is. Do this using `SHOW SERIES CARDINALITY`.

If it's in the millions then consider migrating from the `inmem` index to the `tsi1` index.

**Comment by Vish17agr** [comment]
I can't upgrade my influx DB to 1.5 at the current state of my project. Is there any other way, I can reduce my series cardinality. I am keeping only two days data to reduce the data load. 
Whenever I execute (select * from TWO.measurementName limit 2) query my measurement which has 1 million+ records influxdb service become un-responsive while the influxd is still running. I am not getting a log message as well in logs.

**Comment by e-dard** [comment]
@Vish17agr reducing series cardinality is a domain problem. It's not one that the database can help you with. We have a community site: https://community.influxdata.com where you could talk to people in the company about questions like schema design.

**Comment by Vish17agr** [comment]
Thanks, @e-dard for your inputs.

I have one question why these messages are not logged into the log file. Like when the influxdb service becomes unresponsive and the query is been failed due to high cardinality or memory issue, In that scenario message should be logged into the log file.

**Comment by Vish17agr** [comment]
Hi @e-dard , 
Any update whether we are improving the logging.
As I saw many times influx service went down due to high memory usage but no error message has been logged into the logging.
