### ISSUE TITLE
Improve RewriteRegexConditions to handle regex OR

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#9574]
The current [`RewriteRegexConditions`][rewrite] API handles the following case

* `tag =~ /^foo$/`

and rewrites it to

* `tag = foo`

allowing the use of a faster index search. However, dashboards generate more complex regular expressions that could also be rewritten for improved performance. Specifically

* `tag =~ /^foo$|^bar$|^fee$/`
* `tag =~ /^(foo|bar|fee)$/`

could be rewritten to

* `tag = foo OR tag = bar OR tag = fee`

Again allowing faster index lookups.

When updating this API, it should be moved to a top-level function so it can be reused for all conditions rather than just those attached to a select statement.

[rewrite]: https://github.com/influxdata/influxql/blob/master/ast.go#L1371-L1411

**Comment by e-dard** [comment]
@jsternberg can we get this merged in? It's useful for a number of users.
