### ISSUE TITLE
Query one particular DB return [panic:runtime error: invalid memory address or nil pointer dereference]

### ISSUE THREAD

**Issue by szibis** [influxdata/influxdb#9590]
Same on InfluxDB 1.4.3 and now 1.5.0

Data are writing but when we query this DB, then no data with this error in the log.

This influxdb instance has a second bigger DB which is working fine.

After DB drop all is working again and then after some time, we get this again. Currently recreated DB and all back to normal.

ts=2018-03-16T09:44:39.595482Z lvl=error msg="SHOW TAG VALUES WITH KEY = region WHERE env =~ /production/ [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 334050020 [running]:\nruntime/debug.Stack(0xc655fc0540, 0xc617b39240, 0x3b)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/influxdata/influxdb/query.(*QueryExecutor).recover(0xc4202436e0, 0xc655fc0540, 0xc771a34e40)\n\t/go/src/github.com/influxdata/influxdb/query/query_executor.go:451 +0xaf\npanic(0xce4120, 0x1302970)\n\t/usr/local/go/src/runtime/panic.go:491 +0x283\ngithub.com/influxdata/influxdb/tsdb.(*MeasurementFields).HasField(0x0, 0xc6535c2a56, 0x3, 0xc6cb418c30)\n\t/go/src/github.com/influxdata/influxdb/tsdb/shard.go:1408 +0x26\ngithub.com/influxdata/influxdb/tsdb.IndexSet.seriesByBinaryExprIterator(0xc5e5da21b0, 0x3, 0x3, 0xc6cb418c30, 0xc4b65bd4a4, 0x1b, 0x1bf, 0xc5e5da2150, 0x0, 0xe100000000000000, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:1833 +0xdd2\ngithub.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc5e5da21b0, 0x3, 0x3, 0xc6cb418c30, 0xc4b65bd4a4, 0x1b, 0x1bf, 0x12cae00, 0xc5e5da2150, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:1786 +0x476\ngithub.com/influxdata/influxdb/tsdb.IndexSet.tagValuesByKeyAndExpr(0xc5e5da21b0, 0x3, 0x3, 0xc6cb418c30, 0x7f248008cbf0, 0xc5be1aa390, 0xc4b65bd4a4, 0x1b, 0x1bf, 0xc4dacde830, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:2144 +0x1a0\ngithub.com/influxdata/influxdb/tsdb.IndexSet.MeasurementTagKeyValuesByExpr(0xc5e5da21b0, 0x3, 0x3, 0xc6cb418c30, 0x7f248008cbf0, 0xc5be1aa390, 0xc4b65bd4a4, 0x1b, 0x1bf, 0xc4dacde830, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:2293 +0xca1\ngithub.com/influxdata/influxdb/tsdb.(*Store).TagValues(0xc420001e00, 0x7f248008cbf0, 0xc5be1aa390, 0xc76328cf40, 0x3, 0x4, 0x12cae00, 0xc5e5da2000, 0x4, 0x10, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/store.go:1517 +0x946\ngithub.com/influxdata/influxdb/coordinator.LocalTSDBStore.TagValues(0xc420001e00, 0x7f248008cbf0, 0xc5be1aa390, 0xc76328cf40, 0x3, 0x4, 0x12cae00, 0xc5e5da2000, 0x32f2d7fe, 0x109d537404, ...)\n\t<autogenerated>:1 +0x97\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeShowTagValues(0xc420267730, 0xc730501c80, 0xc8dab65c48, 0xdf7588, 0xf)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:1066 +0x840\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc420267730, 0x12ce780, 0xc730501c80, 0x0, 0x4290, 0xc6bc90f030, 0xc771a34e40, 0xc771a34ea0, 0xc530a3150e, 0x5, ...)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:194 +0x2937\ngithub.com/influxdata/influxdb/query.(*QueryExecutor).executeQuery(0xc4202436e0, 0xc655fc0540, 0xc530a3150e, 0x5, 0x7f248008cbf0, 0xc5be1aa390, 0x2710, 0x1, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/query_executor.go:389 +0xae8\ncreated by github.com/influxdata/influxdb/query.(*QueryExecutor).ExecuteQuery\n\t/go/src/github.com/influxdata/influxdb/query/query_executor.go:285 +0xc3\n" log_id=06pz~HQG000 service=query

**Comment by benbjohnson** [comment]
@szibis Thanks for the report. It looks like this is fixed in https://github.com/influxdata/influxdb/pull/9551 and we'll be releasing that fix soon.
