### ISSUE TITLE
`runtime: out of memory` when using TSI indexes and many databases

### ISSUE THREAD

**Issue by dlanderson** [influxdata/influxdb#9592]
### Bug report

__System info:__ 
InfluxDB 1.5.0
Ubuntu 16.04
AWS EC2 i3.16xlarge (64 "cores", 488GB RAM)

__Steps to reproduce:__

1. Install InfluxDB 1.5.0 (new install - no existing data)
2. Set `index-version = "tsi1"` in `/etc/influxdb/influxdb.conf`
3. Create many databases (2000 in this case) and fill with a small amount of data:

```
# Create databases
$ for i in `seq 1 2000`; do influx -execute "CREATE DATABASE org_$i"; done

# Fill databases with some data
for pirate in blackbeard gentleman sparrow; do echo $pirate; for n in `seq 1 5`; do echo $n; for i in `seq 1 2000`; do influx -database org_${i} -execute "INSERT treasures,captain_id=${pirate} value=${n}"; done; done; done
```

__Expected behavior:__ InfluxDB should start and load databases without crashing

__Actual behavior:__ InfluxDB crashes due to unable to allocate memory when initializing sketches for HLL:

```
ts=2018-03-16T16:51:13.037855Z lvl=info msg="Reading file" log_id=06swOiT0000 engine=tsm1 service=cacheloader path=/influx_wal/influxdb/wal/org_3509/autogen/3510/_00001.wal size=1040
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xdfdc6a, 0x16)
	/usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc6d4080000, 0x100000, 0x0, 0x1337df8)
	/usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x131e880, 0x100000, 0x2b935c8b2990)
	/usr/local/go/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0x131e880, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0x131e880, 0x8, 0x1337e08, 0x2b935c8b28f8)
	/usr/local/go/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0x131e880, 0x8, 0xc4ae470101, 0x2b935c8b28f8)
	/usr/local/go/src/runtime/mheap.go:666 +0x118
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0x2b5bdf974e10)
	/usr/local/go/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0x131e880, 0x8, 0x2b935c010101, 0x2b935c8b28f8)
	/usr/local/go/src/runtime/mheap.go:732 +0xa1
runtime.largeAlloc(0x10000, 0x2b5bdf970101, 0x2b935c8b28f8)
	/usr/local/go/src/runtime/malloc.go:827 +0x98
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:722 +0x46
runtime.systemstack(0xc420a58db8)
	/usr/local/go/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1135

goroutine 29184 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:298 fp=0xc5c2c4db28 sp=0xc5c2c4db20 pc=0x45b970
runtime.mallocgc(0x10000, 0xc9b7a0, 0x1, 0xc6cf4d7560)
	/usr/local/go/src/runtime/malloc.go:721 +0x7ae fp=0xc5c2c4dbd0 sp=0xc5c2c4db28 pc=0x41289e
runtime.makeslice(0xc9b7a0, 0x0, 0x10000, 0x0, 0xc6ce775a10, 0x10000)
	/usr/local/go/src/runtime/slice.go:54 +0x77 fp=0xc5c2c4dc00 sp=0xc5c2c4dbd0 pc=0x445197
github.com/influxdata/influxdb/pkg/estimator/hll.newCompressedList(...)
	/go/src/github.com/influxdata/influxdb/pkg/estimator/hll/compressed.go:101
github.com/influxdata/influxdb/pkg/estimator/hll.NewPlus(0x10, 0xc6ca435950, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/pkg/estimator/hll/hll.go:87 +0x191 fp=0xc5c2c4dc68 sp=0xc5c2c4dc00 pc=0x917171
github.com/influxdata/influxdb/pkg/estimator/hll.NewDefaultPlus(0xc6ca435950)
	/go/src/github.com/influxdata/influxdb/pkg/estimator/hll/hll.go:106 +0x26 fp=0xc5c2c4dc98 sp=0xc5c2c4dc68 pc=0x9172e6
github.com/influxdata/influxdb/tsdb/index/tsi1.NewLogFile(0xc4633aba40, 0xc6cb3b12c0, 0x4d, 0xc6cb3b12c0)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:72 +0x7d fp=0xc5c2c4dd48 sp=0xc5c2c4dc98 pc=0xadfa6d
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).openLogFile(0xc6d1eda240, 0xc6cb3b12c0, 0x4d, 0xc6cb3b12c0, 0x4d, 0x8)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:221 +0x47 fp=0xc5c2c4dd80 sp=0xc5c2c4dd48 pc=0xaee597
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).Open(0xc6d1eda240, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:164 +0x5f4 fp=0xc5c2c4df80 sp=0xc5c2c4dd80 pc=0xaedc54
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Open.func1(0xc6c5d3f194, 0x8, 0xc6996eecf0, 0xc6d1ee4120, 0x5)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:202 +0x30 fp=0xc5c2c4dfb8 sp=0xc5c2c4df80 pc=0xafce00
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc5c2c4dfc0 sp=0xc5c2c4dfb8 pc=0x45e5a1
created by github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Open
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:196 +0x64e
```

__Additional info:__ [See this gist for startup log with crash info](https://gist.githubusercontent.com/dlanderson/32a4f2d671ce75c972ffa800d8a73e8c/raw/0e26f5e1b57e0f0f6601997f30640b46dcdceebd/influx_1.5.0_TSI_oom_hll.log)

**Comment by benbjohnson** [comment]
@dlanderson Thanks for digging into that and figuring it out. I'm surprised that too many mmap files manifested as an OOM.

There's a shared per-database series file that is partitioned into 8 sections. Each section has segment files that start at 4MB and double in size as a new one is added (up to 1GB). Each database will have a minimum of 8 memory-mapped file to manage series.

**Comment by e-dard** [comment]
Hi @dlanderson, what is your usecase? 2000 databases is a large number, and the database isn’t well suited to running that many databases. It’s more suited to separating data at the measurement/series level.

**Comment by dlanderson** [comment]
Hi @e-dard - We use InfluxDB for our APM (Application Performance Monitoring) product at [https://scoutapp.com/](https://scoutapp.com/). We currently have almost 8000 databases on a single influx server, currently running Influx 1.4. The only reason for this is because Influx < 0.10 could not provide sufficient write throughput using a single influx database (we started using influx in 0.8x days) and we have not migrated the data back into fewer databases yet.

Thanks for the info @benbjohnson !

**Comment by timhallinflux** [comment]
@dlanderson -- so you are provisioning 1 DB/customer?  Again, 8k DBs is way, way beyond what we would expect a single instance to handle.

**Comment by Keleir** [comment]
I met the simliar question with influxdb version `1.5.0` booted by systemd.
```
Mar 20 09:19:41 kernel:  Out of memory: Kill process 8589 (influxd) score 952 or sacrifice child
Mar 20 09:19:41 kernel:  Killed process 8589 (influxd) total-vm:48539612kB, anon-rss:31133404kB, file-rss:0kB, shmem-rss:0kB
Mar 20 09:19:44 systemd: influxdb.service: main process exited, code=killed, status=9/KILL
Mar 20 09:19:44 systemd: Unit influxdb.service entered failed state.
Mar 20 09:19:44 systemd: influxdb.service failed.
Mar 20 09:19:44 systemd: influxdb.service holdoff time over, scheduling restart.
```
The influxdb service config is as following: 
```
[Unit]
Description=InfluxDB is an open-source, distributed, time series database
Documentation=https://docs.influxdata.com/influxdb/
After=network-online.target

[Service]
User=influxdb
Group=influxdb

LimitAS=infinity
LimitRSS=infinity
LimitCORE=infinity
LimitNOFILE=infinity

EnvironmentFile=-/etc/default/influxdb
ExecStart=/usr/bin/influxd -config /etc/influxdb/influxdb.conf $INFLUXD_OPTS
KillMode=control-group
Restart=on-failure

[Install]
WantedBy=multi-user.target
Alias=influxd.service
```
And there was too much file descriptor used by influxd process, the `lsof` output is [here](https://gist.github.com/Keleir/79f7b720a50f302c67996cc4cfb55141). Owing to this influxdb service port `8086` not listenning after restart.

**Comment by e-dard** [comment]
@keleir, your issue looks different , as you only have a couple of databases. You could possibly check your `ulimit` setting and bump it up if necessary.

**Comment by dlanderson** [comment]
@timhallinflux Correct - and yes I certainly understand that it is not a recommended configuration :) That said, what is the reasonable limit for the number of databases on a single instance? I don't think I've come across any benchmarks or documentation that addresses multiple Influx databases and their limits.

**Comment by e-dard** [comment]
@dlanderson I don't think we have done any extensive testing in terms of how performance/resource requirements scale out, but I would say the comfort zone is in tens and not hundreds (or thousands!).
