### ISSUE TITLE
panic: keys must be added in sorted order

### ISSUE THREAD

**Issue by thomo** [influxdata/influxdb#9596]
### Bug report

__System info:__ InfluxDB version=1.5.0 branch=1.5 commit=6ac835404e7e64ea7299a6eebcce1ab1ef15fe3c
(Docker image 1.5.0)

After migrate from 1.2.0 via 1.4.3 to 1.5.0 influxdb crash:

```
ts=2018-03-17T16:36:36.911429Z lvl=info msg="Compacting file" log_id=06uCwwwl000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06uCyLgW000 op_name=tsm1_compact_group tsm1_index=7 tsm1_file=/var/lib/influxdb/data/_internal/monitor/2474/000000120-000000001.tsm
ts=2018-03-17T16:36:36.980597Z lvl=info msg="TSM compaction (end)" log_id=06uCwwwl000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06uCyLgW000 op_name=tsm1_compact_group op_event=end op_elapsed=69.591ms
panic: keys must be added in sorted order: shard,database=collectd,engine=tsm1,hostname=c761de96bf2f,id=1583,path=/var/,ib/influxdb/data/collectd/default/1583,retentionPolicy=default,walPath=/var/lib/influxdb/wal/collectd/default/1583#!~#writePointsOk < shard,database=collectd,engine=tsm1,hostname=c761de96bf2f,id=1583,path=/var/lib/influxdb/data/collectd/default/1583,retentionPolicy=default,walPath=/var/lib/influxdb/wal/collectd/default/1583#!~#writePointsErr
goroutine 2516 [running]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*directIndex).Add(0xc43cf53d40, 0x7fb5e892091b, 0xd0, 0x4fd4ac, 0x1, 0x151c7eb2ac0a0000, 0x151c7f455af71c00, 0xae30, 0x1c)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:337 +0x706
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmWriter).WriteBlock(0xc45b421880, 0x7fb5e892091b, 0xd0, 0x4fd4ac, 0x151c7eb2ac0a0000, 0x151c7f455af71c00, 0x7fb5e8879068, 0x18, 0x5a4d5f, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:686 +0x1ef
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0xc420a0d480, 0xc451d69f90, 0x49, 0x12d0000, 0xc43c5aa580, 0xc45b317301, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1099 +0x265
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0xc420a0d480, 0x78, 0x2, 0x12d0000, 0xc43c5aa580, 0x1, 0x12d0000, 0xc43c5aa580, 0x0, 0x0, ...)
ts=2018-03-17T16:36:40.128572Z lvl=info msg="InfluxDB starting" log_id=06uCyYG0000 version=1.5.0 branch=1.5 commit=6ac835404e7e64ea7299a6eebcce1ab1ef15fe3c
ts=2018-03-17T16:36:40.128656Z lvl=info msg="Go runtime" log_id=06uCyYG0000 version=go1.9.2 maxprocs=2
[log.txt](https://github.com/influxdata/influxdb/files/1821855/log.txt)
```

It seems that there is an error in the path (in the second log line above) `... id=1583,path=/var/,ib/influxdb/data/collectd/default/1583,retentionPolicy=default ...` but I have no idea where/how to fix it. 

__Additional info:__
- I switched to `tsi1`
- I run `influx_inspect buildtsi -datadir /var/lib/influxdb/data -waldir /var/lib/influxdb/wal` without an error
- even `influx_inspect verify -dir /var/lib/influxdb` shows all files are healthy and `Broken Blocks: 0 / 3428465, in 15.046504985s` 

**Update**: add logfile
[influxdb.log](https://github.com/influxdata/influxdb/files/1822682/influxdb.log)

**Comment by e-dard** [comment]
@thomo hi, did you switch to `tsi1` during the `1.4.3` release?  The TSI index is only supported from `1.5.0` onwards, therefore any older TSI indexes must be removed and rebuilt using the `influx_inspect buildtsi` command.

Having said all of that, this error looks more like a TSM issue to me. /cc @jwilder

**Comment by thomo** [comment]
@e-dard There are no `*.tsi` files (also not in a new data folder I start from scratch with 1.5.0)!?
So I removed the index folders, like `/var/lib/influxdb/data/_internal/monitor/2474/index`, and rebuilt the index with `influx_inspect buildtsi`. ([buildtsi_output.log](https://github.com/influxdata/influxdb/files/1832181/buildtsi_output.log))

But restarting influxdb gives the same error again:
```
# docker run -v /var/lib/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro -v /var/lib/influxdb/data:/var/lib/influxdb -v /usr/share/collectd/types.db:/usr/share/collectd/types.db:ro influxdb:1.5.0
panic: keys must be added in sorted order: shard,database=collectd,engine=tsm1,hostname=c761de96bf2f,id=1583,path=/var/,ib/influxdb/data/collectd/default/1583,retentionPolicy=default,walPath=/var/lib/influxdb/wal/collectd/default/1583#!~#writePointsOk < shard,database=collectd,engine=tsm1,hostname=c761de96bf2f,id=1583,path=/var/lib/influxdb/data/collectd/default/1583,retentionPolicy=default,walPath=/var/lib/influxdb/wal/collectd/default/1583#!~#writePointsErr

goroutine 2522 [running]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*directIndex).Add(0xc45c74b4a0, 0x7f6efe19f91b, 0xd0, 0x4fd4ac, 0x1, 0x151c7eb2ac0a0000, 0x151c7f455af71c00, 0xae30, 0x1c)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:337 +0x706
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmWriter).WriteBlock(0xc45c317140, 0x7f6efe19f91b, 0xd0, 0x4fd4ac, 0x151c7eb2ac0a0000, 0x151c7f455af71c00, 0x7f6efe0f8068, 0x18, 0x5a4d5f, 0x0, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:686 +0x1ef
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0xc4200f2c00, 0xc45c621e00, 0x49, 0x12d0000, 0xc45c6482c0, 0xc45d799701, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1099 +0x265
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0xc4200f2c00, 0x78, 0x2, 0x12d0000, 0xc45c6482c0, 0x1, 0x12d0000, 0xc45c6482c0, 0x0, 0x0, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:994 +0x259
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).compact(0xc4200f2c00, 0xe21f00, 0xc45c63f380, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:903 +0x5d7
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).CompactFull(0xc4200f2c00, 0xc45c63f380, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:921 +0x18e
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*compactionStrategy).compactGroup(0xc425d09c70)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1967 +0x136b
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*compactionStrategy).Apply(0xc425d09c70)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1943 +0x4d
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactHiPriorityLevel.func1(0xc45c2b8440, 0xc420082120, 0x1, 0xc425d09c70)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1860 +0xe0
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactHiPriorityLevel
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1855 +0x122
```

My config: 
[influxdb.conf.txt](https://github.com/influxdata/influxdb/files/1832190/influxdb.conf.txt)

**Comment by jwilder** [comment]
How is `/var/lib/influxdb` attached to your host?  What kind of disks are they?  Is there RAID involved, mounted over NFS, etc..  Is your host OS also linux?

It looks like one of the TSM files in an `_internal` shard had a single bit flip on one byte in the index causing the series keys to be unsorted in the index.

`l` is `6c` which is `01101100`
',' is '2c` which is `00101100`

It looks like bit 7 got changed from a `1` to a `0` which causes the series keys that should have had an `l` to switch to a `,` and then causes the index to be unsorted.  `influx_inspect verify` won't catch this particular issue as it just looks at the block data and not the index.  Since TSM files are never modified and we write the indexes our sorted, this looks more like a hardware or filesystem corruption issue. 

The simplest thing to do would be to move the `_internal` database out of the way.  `_internal` is just used for stats collection and storage and is not necessary for the operation of the database.

I would also check your host logs to see if there is anything reporting hardware of filesystem errors.

**Comment by thomo** [comment]
1. `/var/lib/influxdb/[data,wal]` is on a SSD, direct mounted, xfs fs
1. OS is CENTOS 7.4
1. after removing the `/var/lib/influxdb/data/_internal` folder all works fine again

I have not found a hint for an error in the log files - but I will look further.

I want to suggest a note in the documentation that the `_internal` database can be removed in such situations - but I'm not sure if there are any side effects.

Thanks

**Comment by seanch80** [comment]
I am on version 1.8.3 now in 2021 and I still get this issue about every 3 weeks. I have to delete the _internal folder and then it starts working again. I am doubtful the SSD is bad as it is quite new, M.2 attached and has no I/O errors or other fault indication.

There is a strange hostname in the syslog below.

Things I have tried:
- Upgraded influxdb every time there is a new version for about 2 years
- Switched index-version = "inmem" to "tsi1"
- Deleted index files and recreated index with: su -s /bin/bash -c 'influx_inspect buildtsi -datadir /var/lib/influxdb/data/ -waldir 
- Configured  /etc/security/limits.conf:
influxdb soft nofile unlimited
influxdb hard nofile unlimited
- Configured /etc/systemd/system/influxd.service
LimitNOFILE=262144
- Limited the amount of data in the database
- Increased the shard sizes

Every time influxdb crashes, the system is DOS'ed with 100% CPU restarting the process in a tight crash loop, and also massive syslog writes. I have added a 30 second restart delay to the service to mitigate this, but then the clients have a lot of grief as well.

Linux hasu 4.4.0-201-generic #233-Ubuntu SMP Thu Jan 14 06:10:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
ASUS VIVO-Mini UN45-VM065M Intel Pentium N3700
Kingston Valueram 4GB 1600MHz DDR3L Non-ECC CL11

I'm puzzled why there is a hostname=hisu in the syslog excerpt below, as the hostname as always been hasu and has never changed. If I mistyped some influx command over the years, where would I possibly find the fault and remove it?

Jan 29 13:41:11 hasu influxd[4332]: ts=2021-01-29T12:41:11.927900Z lvl=info msg="Starting retention policy enforcement service" log_id=0R\~YR3D0000 service=retention check_interval=30m
Jan 29 13:41:11 hasu influxd[4332]: ts=2021-01-29T12:41:11.928009Z lvl=info msg="Listening for signals" log_id=0R\~YR3D0000
Jan 29 13:41:12 hasu influxd[4332]: ts=2021-01-29T12:41:12.029210Z lvl=info msg="Sending usage statistics to usage.influxdata.com" log_id=0R\~YR3D0000
Jan 29 13:41:12 hasu influxd[4332]: ts=2021-01-29T12:41:12.919938Z lvl=info msg="TSM compaction (start)" log_id=0R\~YR3D0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0R\~YRDql000 op_name=tsm1_compact_group op_event=start
Jan 29 13:41:12 hasu influxd[4332]: ts=2021-01-29T12:41:12.920083Z lvl=info msg="Beginning compaction" log_id=0R\~YR3D0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0R\~YRDql000 op_name=tsm1_compact_group tsm1_files_n=4
Jan 29 13:41:12 hasu influxd[4332]: ts=2021-01-29T12:41:12.920164Z lvl=info msg="Compacting file" log_id=0R\~YR3D0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0R\~YRDql000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/_internal/monitor/1267/000000008-000000002.tsm
Jan 29 13:41:12 hasu influxd[4332]: ts=2021-01-29T12:41:12.920247Z lvl=info msg="Compacting file" log_id=0R\~YR3D0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0R\~YRDql000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/_internal/monitor/1267/000000018-000000002.tsm
Jan 29 13:41:12 hasu influxd[4332]: ts=2021-01-29T12:41:12.920272Z lvl=info msg="Compacting file" log_id=0R\~YR3D0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0R\~YRDql000 op_name=tsm1_compact_group tsm1_index=2 tsm1_file=/var/lib/influxdb/data/_internal/monitor/1267/000000026-000000002.tsm
Jan 29 13:41:12 hasu influxd[4332]: ts=2021-01-29T12:41:12.920295Z lvl=info msg="Compacting file" log_id=0R\~YR3D0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0R\~YRDql000 op_name=tsm1_compact_group tsm1_index=3 tsm1_file=/var/lib/influxdb/data/_internal/monitor/1267/000000034-000000002.tsm
Jan 29 13:41:14 hasu influxd[4332]: ts=2021-01-29T12:41:14.041750Z lvl=info msg="TSM compaction (end)" log_id=0R\~YR3D0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0R\~YRDql000 op_name=tsm1_compact_group op_event=end op_elapsed=1121.842ms
**Jan 29 13:41:14 hasu influxd[4332]: panic: keys must be added in sorted order: tsm1_engine,database=management,engine=tsm1,hostname=hasu,id=1231,indexType=tsi1,path=/var/lib/influxdb/data/management/autogen/1231,retentionPolicy=autogen,walPath=/var/lib/influxdb/wal/management/autogen/1231#!\~#tsmOptimizeCompactionQueue < tsm1_engine,database=management,engine=tsm1,hostname=hisu,id=1231,indexType=tsi1,path=/var/lib/influxdb/data/management/autogen/1231,retentionPolicy=autogen,walPath=/var/lib/influxdb/wal/management/autogen/1231#!\~#tsmOptimizeCompactionErr**
Jan 29 13:41:14 hasu influxd[4332]: goroutine 1899 [running]:
Jan 29 13:41:14 hasu influxd[4332]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*directIndex).Add(0xc00c931ec0, 0x7fab8922bba6, 0xf0, 0x1d9155, 0x1, 0x165e942d8cb00000, 0x165e9d53d369f800, 0x1b4b9a, 0xc00000006b)
Jan 29 13:41:14 hasu influxd[4332]: #011/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:337 +0x594
Jan 29 13:41:14 hasu influxd[4332]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmWriter).WriteBlock(0xc00b4fa300, 0x7fab8922bba6, 0xf0, 0x1d9155, 0x165e942d8cb00000, 0x165e9d53d369f800, 0x7fab88feb671, 0x67, 0x41968a, 0x0, ...)
Jan 29 13:41:14 hasu influxd[4332]: #011/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:686 +0x1ea
Jan 29 13:41:14 hasu influxd[4332]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0xc0003aa240, 0xc0141f6140, 0x49, 0x25919e0, 0xc00576a000, 0xc00f185401, 0x0, 0x0)
Jan 29 13:41:14 hasu influxd[4332]: #011/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1162 +0x287
Jan 29 13:41:14 hasu influxd[4332]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0xc0003aa240, 0x22, 0x3, 0xc00b4fa140, 0x4, 0x4, 0x25919e0, 0xc00576a000, 0x1, 0x25919e0, ...)
Jan 29 13:41:14 hasu influxd[4332]: #011/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1045 +0x18f
Jan 29 13:41:14 hasu influxd[4332]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).compact(0xc0003aa240, 0xc00b4fa100, 0xc00b4fa140, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)

Any tips is greatly appreciated.

Thanks

**Comment by seanch80** [comment]
I've added an ExecPreStart to /lib/systemd/system/influxdb.service now, hoping it will help:

**ExecStartPre=/bin/sh -c 'sleep 10; rm -rf /var/lib/influxdb/data/_internal/'**

**Comment by cheeseandcereal** [comment]
I'm seeing the same issue as @seanch80 as well. Using influxd v1.8.5 currently, but I've observed it on older versions as well.

For me all data is hosted on a ZFS raid and I can confirm no bits have ever been corrupted or flipped, and there have been no i/o errors, so this must be caused by something else. For me, deleting the _internal database doesn't help because the keys that is not always the db with the issue, sometimes it is my other dbs with seemingly bad keys. Not sure how this can happen.

If anyone else can give tips to further debug I'd be glad to assist and would appreciate the help.

**Comment by dtillner** [comment]
I have the same problem on my development instance. I run the latest docker image of version 1.8 with automatic update to the latest version. I do regularly dropping and seeding of new series with dev data.

Host system is Ubuntu 21.04 on a SSD. Tested the SSD with smartctl and couldn't find any problems.

```
ts=2021-05-12T09:41:46.678223Z lvl=info msg="TSM compaction (end)" log_id=0U3~5Wo0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0U3~66eW000 op_name=tsm1_compact_group db_shard_id=2551 op_event=end op_elapsed=911.886ms
panic: keys must be added in sorted order: tsm1_engine,database=production_instance_dev,engine=tsm1,hostname=2a0f0b93e5cc,id=2230,indexType=inmem,path=/var/lib/influxdb/data/production_instance_dev/autogen/2230,retentionPolicy=autogen,walPath=/var/lib/influxdb/wal/production_instance_dev/autogen/2230#!~#cacheCompactions < tsm1_engine,database=production_instance_dev,engine=tsm1,hostname=2a0f0b93e5cc,id=2230,indexType=inmem,path=/var/lib/influxdb/data/production_instance_dev/autogen/2230,setentionPolicy=autogen,walPath=/var/lib/influxdb/wal/production_instance_dev/autogen/2230#!~#cacheCompactionErr
```

If  I can help to debug this problem I'd be glad to assist.

**Comment by axipher** [comment]
Thank you so much for this thread.

My InfluxDB 1.8 Docker just started a crazy restart loop this morning and the only thing I had was a similar "panic" in the docker log:

`panic: keys must be added in sorted order: tsm1_wal,database=LSCPU,engine=tsm1,hostname=abcde12345,id=1019,indexType=inmem,path=/var/lib/influxdb/data/LSCPU/autogen/1019,retentionPolicy=autogen,walPath=/var/lib/influxdb/wal/LSCPU/autogen/1019#!~#writeErr < tsm1_wal,database=LSCPU,engine=tsm1,hostname=abcde12345,id=1019,indexType=inmem,path=/var/lib/influxdb/data/LSCPU/autogen/1019,retentionPolicy=autogen,walPath=/var/lib/influxdf/wal/LSCPU/autogen/1019#!~#oldSegmentsDiskBytes`



First I tried just renaming _internal to _internal.bak but it would still keep restarting the docker and giving the panic message in the logs.

Second I just deleted the _internal folder and now it's back up and running with no restarts.

**Comment by george-cz** [comment]
I had a similar thing happen two times with a few weeks in between. Ended up testing the RAM as the timing coincided with me upgrading it.

Turns out one of the 2 sticks was bad. I replaced the RAM and I'm hoping I will not see this issue again :)
