### ISSUE TITLE
Write with multiple values in influxdb using HTTP API

### ISSUE THREAD

**Issue by juergenschubert** [influxdata/influxdb#9601]
API write issues. When I go on the commandline and add some values things are find:
influx
Connected to http://localhost:8086 version 1.5.0
InfluxDB shell version: 1.5.0
> USE IOT
Using database IOT
> INSERT dht22 t=20.60,h=50.90,hic=20.04
> INSERT dht22 t=20.60,h=51.00,hic=20.05
> SELECT * FROM dht22
name: dht22

> time                h    hic   t
> ----                -    ---   -
> 1521489555934808439 50.9 20.04 20.6
> 1521489589939138336 51   20.05 20.6

> SELECT * FROM dht22
name: dht22
time                h    hic   t
----                -    ---   -
1521489555934808439 50.9 20.04 20.6
1521489589939138336 51   20.05 20.6

now when I try a 
pi@raspberrypi:~ $ curl -i -XPOST 'http://192.168.1.117:8086/write?db=IOT' --data-binary 'dht22,t=20.60,h=50.90,hic=20.04'
HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 93c95899-2bb1-11e8-9577-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Error: unable to parse 'dht22,t=20.60,h=50.90,hic=20.04': missing fields
X-Influxdb-Version: 1.5.0
X-Request-Id: 93c95899-2bb1-11e8-9577-000000000000
Date: Mon, 19 Mar 2018 20:10:32 GMT
Content-Length: 78

{"error":"unable to parse 'dht22,t=20.60,h=50.90,hic=20.04': missing fields"}

**Comment by dgnorton** [comment]
@juergenschubert, @shakefu is correct. There needs to be a space.

Thanks @shakefu :)

**Comment by juergenschubert** [comment]
You are all correct. It is cracy how I am checking my syntax. I did some more tags and fields and got a 

curl -i -XPOST 'http://192.168.1.50:8086/write?db=IOT&u=root&p=123456' --data-binary 'dht22,location=Speicher,client=ESP01 temperatur=22.30,humidity=50.50,heat_index=21.90'

it came back with a 

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 94b2eb72-2d1d-11e8-8040-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.5.0
X-Request-Id: 94b2eb72-2d1d-11e8-8040-000000000000
Date: Wed, 21 Mar 2018 15:36:10 GMT

but when I do a lookup on my db
SELECT * FROM dht22 LIMIT 10
name: dht22

time                client heat_index humidity location temperatur
----                ------ ---------- -------- -------- ----------
1521652085918661398 ESP01  21.9       50.5     Speicher 22.3
so it seams to work, the question is what is the
HTTP/1.1 204 No Content
telling me?

**Comment by dgnorton** [comment]
@juergenschubert 204 No Content is the HTTP status code meaning the request was successfully processed but the response to the request contains no content. https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_Success

**Comment by juergenschubert** [comment]
Ah which does make sense. Thanks for that clarification.
