### ISSUE TITLE
HTTP/1.1 204 No Content : But no data is written

### ISSUE THREAD

**Issue by rohithmn3** [influxdata/influxdb#9605]
I am using the below curl command to push the data to InfluxDB. 
```
measurement="download_speed,component=java_jdk,landscape=aws duration=10,status=100"
echo "$measurement" >/tmp/curl.input
curl -k -m 30 -i -XPOST $url/write?db=<database_name> -u ${username}:${password} --data-binary @/tmp/curl.input
```

MY Output:
```
HTTP/1.1 204 No Content
Server: nginx/1.13.8
Date: Mon, 19 Mar 2018 08:39:28 GMT
Content-Type: application/json
Connection: keep-alive
Request-Id: 057a880f-2b51-22e8-9r45-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.4.2
X-Request-Id: 057a880f-2b51-22e8-9r45-000000000000
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Expires: Sat, 26 Jul 1997 05:00:00 GMT
```

But when i check the measurement, i don't find any data..!

Regards,
Rohith

**Comment by e-dard** [comment]
Can you provide more detail please, as outlined in the Issue template?

**Comment by rohithmn3** [comment]
Issue was like - Even after 204 success message, the data was not inserted in the influx DB. When i query for the measurement nothing was available. 
I got this issue fixed by modifying my CURL command by adding precision as seconds to it.
FYI...
`curl -k --connect-timeout 30 -XPOST "${url}/write?db=${database}&precision=s" -u "${username}:${password}" --data-binary "$measurement"`

**Comment by e-dard** [comment]
Thanks. This was a problem with how you were querying the data by the sounds of it.
