### ISSUE TITLE
Where clause with 2 absolute TIME using OR not working

### ISSUE THREAD

**Issue by Pangaj** [influxdata/influxdb#9606]
### Example:
```
select checkInPersonName from attendanceMsr where (time >= 1519220502409000000 and time <= 1519306902409000000) or (time >= 1519825302409000000 and time <= 1519911702409000000)
```
and group by clause example
```
select sum(price) as totalPrice from factoryOutlet where (time >=now() - 2h and time <= now() - 1h) or (time >=now() - 5d2h and time <= now() - 5d1h) group by time(1m) fill(0)
```

#### using single where clause, I am able to get the data. But combining the 2 where clause, I am unable to fetch the data.

**Comment by dgnorton** [comment]
The docs note that OR is not supported with absolute times but don't see anything mentioned about relative times. I tested an example similar to the one in the issue and see the same behavior.

**Comment by jsternberg** [comment]
Yea, OR isn't supported at all so you can't select multiple time intervals. Changing this behavior isn't possible because the change would make some common queries not work the same as they did before.

**Comment by dgnorton** [comment]
@jsternberg thanks for the clarification. I'll flag this for documentation update.

I see two locations in the docs that specifically say `OR` doesn't work with absolute time but it needs to say something to the effect of `OR can't be used to specify multiple time ranges`.
* https://docs.influxdata.com/influxdb/v1.0/query_language/data_exploration/#issue-2-using-or-with-absolute-time
* https://docs.influxdata.com/influxdb/v1.0/troubleshooting/frequently-asked-questions/#why-is-my-query-with-a-where-or-time-clause-returning-empty-results
