### ISSUE TITLE
Use aggregation and selector functions in where clause

### ISSUE THREAD

**Issue by ikovalyov** [influxdata/influxdb#9610]
### Feature Request
__Proposal:__ Aggregate functions in where clause

__Current behavior:__ Using returns no data

__Desired behavior:__ Should return data

__Use case:__ 
Sometimes we need to skip highest/lowest data in our dataset. It can be easily accomplished by using something like

```
where value > percentile("value", 10) and value < percentile("value", 90)
```

Also it can be interesting to select only data which is more or less then average
```
where value > mean("value")
```
or 
```
where value < mean("value")
```

**Comment by gsrcobr** [comment]
+1

**Comment by dragosm-thg** [comment]
+1
