### ISSUE TITLE
No log message reported in case of DB crash and influx db service down in influx log.

### ISSUE THREAD

**Issue by Vish17agr** [influxdata/influxdb#9611]
I am using influx 1.4.2 for the telemetry.

Many times my influx service running on 4CPU 32GB centos server crashes or influx service becomes inactive but no log messages been reported in the influx log. 

I have enabled all the log tracing in influxdb.conf file but that is also not helping me.

**Comment by dgnorton** [comment]
@Vish17agr when it crashes, how do you usually find out that it crashed? Is there any information you can add to the issue about the nature of it?

**Comment by petetnt** [comment]
![image](https://user-images.githubusercontent.com/7641760/37771545-94c33ee4-2de0-11e8-8eaf-b95903d80ad9.png)
I think we are running into the same issue while running 1.5 with Docker, these are the only logs available.

**Comment by dgnorton** [comment]
@petetnt we recommend time bounding queries. Even though that query has a `LIMIT 10` it could still cause problems in the current query engine. There's a [proposal](https://github.com/influxdata/influxdb/issues/9411) to make improvements on this.

**Comment by dgnorton** [comment]
Closing because this should be fixed in a future release by #9411

**Comment by petetnt** [comment]
Thanks for the heads @dgnorton!

**Comment by Vish17agr** [comment]
@dgnorton Sorry for the late response. The issue is happening when the influx database is hit by multiple queries from grafana, or we query the measurement which has millions of records provided limit 10 from the influx CLI. The query gets fail and influx database crashes.
