### ISSUE TITLE
Lost data using Go Client

### ISSUE THREAD

**Issue by andy-zhangtao** [influxdata/influxdb#9616]
I use go client `github.com/influxdata/influxdb/client/v2` test my influxdb.  I found the count of record is wrong. I write a sample code test. 

The code loop ten times, there are should be ten records. But the count not equal 10, little than 10. 
```
package main

import (
	"github.com/influxdata/influxdb/client/v2"
	"fmt"
	"time"
)

func main() {
	c, err := client.NewHTTPClient(client.HTTPConfig{
		Addr: "http://cznews.cc:8086",
	})
	if err != nil {
		fmt.Println("Error creating InfluxDB Client: ", err.Error())
	}
	defer c.Close()

	// Create a new point batch
	bp, _ := client.NewBatchPoints(client.BatchPointsConfig{
		Database:         "hicd",
		Precision:        "s",
		WriteConsistency: "all",
	})

	i := 0
	for {

		if i == 10 {
			break
		}
		// Create a point and add to batch
		tags := map[string]string{"name": "github.com/andy-zhangtao/humCICD"}
		fields := map[string]interface{}{
			"log": "L",
		}
		pt, err := client.NewPoint("github.com/andy-zhangtao/humCICD", tags, fields, time.Now())
		if err != nil {
			fmt.Println("Error: ", err.Error())
		}
		bp.AddPoint(pt)
		i ++
		err = c.Write(bp)
		if err != nil {
			fmt.Println(err.Error())
		}

		fmt.Println("OK")
	}
}
```
There are no err in influxdb log.  I use shell script re-test, the count is right . 
```
while true; do curl -i -XPOST 'http://cznews.cc:8086/write?db=hicd' --data-binary 'github.com/andy-zhangtao/humCICD,name=github.com/andy-zhangtao/humCICD log="L"'; let i+=1; echo $i; done;
```

Is that a bug in go client sdk? Or my configure issue?

Tks
Andy

**Comment by e-dard** [comment]
@andy-zhangtao you're very likely writing multiple points per second, which means that they will have the same timestamp (because your precision is set to seconds). A new point with the same measurement, tags and timestamp will overwrite the previous one.

To verify instead of writing `time.Now()` as the timestamp, try writing `i * time.Second`. You should find that you get your ten points.

**Comment by andy-zhangtao** [comment]
@e-dard  O. Yes, that's my fault.  I add `time.Now()`. That's works! 

Tks 👍

**Comment by Tang-RoseChild** [comment]
@e-dard bravo, dude, i has been stuck for a while,thx
