### ISSUE TITLE
Write data failed when TSM compaction in progress on InfluxDB 1.5.1 

### ISSUE THREAD

**Issue by R4scal** [influxdata/influxdb#9617]
**Bug report**

**System info:** Ubuntu 16.04, InfluxDB 1.5.1 

**Steps to reproduce:**
1. Upgrade InfluxDB from 1.4.2 to 1.5.1
2. Write data to large DB (7 GB shard size)
3. Start TSM compaction process

**Expected behavior:** There is no effect on writing data during the compaction of shard

**Actual behavior**: Message "failed to store statistics" in logs and wtite timeouts for clients

![screen shot 2018-03-22 at 15 09 52](https://user-images.githubusercontent.com/16123585/37769777-2a76e9e8-2de3-11e8-9c9b-78e11692bae1.png)

**Logs:**
`
influxd[69961]: ts=2018-03-22T11:19:23.258451Z lvl=info msg="Snapshot for path written" log_id=06~KN2j0000 engine=tsm1 trace_id=06~MnVCl000 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/large-database/onemonth/397 duration=5191.415ms
`
`
influxd[69961]: ts=2018-03-22T11:19:23.258965Z lvl=info msg="Cache snapshot (end)" log_id=06~KN2j0000 engine=tsm1 trace_id=06~MnVCl000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=5191.926ms
`
`
influxd[69961]: ts=2018-03-22T11:19:24.067214Z lvl=info msg="TSM compaction (start)" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group op_event=start
`
`
influxd[69961]: ts=2018-03-22T11:19:24.067273Z lvl=info msg="Beginning compaction" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group tsm1_files=8
`
`
influxd[69961]: ts=2018-03-22T11:19:24.067283Z lvl=info msg="Compacting file" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/large-database/onemonth/397/000000049-000000001.tsm
`
`
influxd[69961]: ts=2018-03-22T11:19:24.067291Z lvl=info msg="Compacting file" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/large-database/onemonth/397/000000050-000000001.tsm
`
`
influxd[69961]: ts=2018-03-22T11:19:24.067300Z lvl=info msg="Compacting file" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group tsm1_index=2 tsm1_file=/var/lib/influxdb/data/large-database/onemonth/397/000000051-000000001.tsm
`
`
influxd[69961]: ts=2018-03-22T11:19:24.067307Z lvl=info msg="Compacting file" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group tsm1_index=3 tsm1_file=/var/lib/influxdb/data/large-database/onemonth/397/000000053-000000001.tsm
`
`
influxd[69961]: ts=2018-03-22T11:19:24.067315Z lvl=info msg="Compacting file" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group tsm1_index=4 tsm1_file=/var/lib/influxdb/data/large-database/onemonth/397/000000054-000000001.tsm
`
`
influxd[69961]: ts=2018-03-22T11:19:24.067322Z lvl=info msg="Compacting file" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group tsm1_index=5 tsm1_file=/var/lib/influxdb/data/large-database/onemonth/397/000000055-000000001.tsm
`
`
influxd[69961]: ts=2018-03-22T11:19:24.067330Z lvl=info msg="Compacting file" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group tsm1_index=6 tsm1_file=/var/lib/influxdb/data/large-database/onemonth/397/000000056-000000001.tsm
`
`
influxd[69961]: ts=2018-03-22T11:19:24.067338Z lvl=info msg="Compacting file" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group tsm1_index=7 tsm1_file=/var/lib/influxdb/data/large-database/onemonth/397/000000057-000000001.tsm
`
`
influxd[69961]: ts=2018-03-22T11:20:10.305401Z lvl=info msg="failed to store statistics" log_id=06~KN2j0000 service=monitor error=timeout
`
`
influxd[69961]: ts=2018-03-22T11:20:11.972104Z lvl=info msg="Compacted file" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/large-database/onemonth/397/000000057-000000002.tsm.tmp
`
`
influxd[69961]: ts=2018-03-22T11:20:11.972767Z lvl=info msg="Finished compacting files" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group groups=8 files=1 duration=47905.567ms
`
`
influxd[69961]: ts=2018-03-22T11:20:11.973067Z lvl=info msg="TSM compaction (end)" log_id=06~KN2j0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=06~Mnrdl000 op_name=tsm1_compact_group op_event=end op_elapsed=47905.858ms
`

**Comment by lobocobra** [comment]
I have the same errors....
`Nov 11 02:33:50 OpenhabCat influxd[1029]: ts=2019-11-11T01:33:50.029261Z lvl=info msg="failed to store statistics" log_id=0J1ywLal000 service=monitor error=timeout
Nov 11 02:34:00 OpenhabCat influxd[1029]: ts=2019-11-11T01:34:00.054924Z lvl=info msg="failed to store statistics" log_id=0J1ywLal000 service=monitor error=timeout
`
Newest Version installed.... it seems to happen, while the backup is running (on another path).
=> was this solved?
