### ISSUE TITLE
Different InfluxDB versions and remote backup causes "connection reset by peer"

### ISSUE THREAD

**Issue by dictvm** [influxdata/influxdb#9618]
### Bug report

__System info:__ 
Server:
InfluxDB v1.3.6 (git: 1.3 a7c3d3c0f7b74f71919047adbc4933460967a576)
Ubuntu 16.04.3 LTS

Backup target/client:
InfluxDB v1.5.1 (git: 1.5 cdae4ccde4c67c3390d8ae8a1a06bd3b4cdce5c5)
Ubuntu 16.04.3 LTS

__Steps to reproduce:__

1. Run an InfluxDB 1.3 server that binds to `:8088`
2. Setup another InfluxDB server with e.g. InfluxDB version 1.5
3. Execute backup from the server in step 2 to the server in step 1

__Expected behavior:__ The remote backup should work because there is no documented requirement of the remote and the client being the same version. Other database command line tools are also not very picky with regards to the server version being used.

__Actual behavior:__ The connection is not being established and fails with a `connection reset by peer` error message. 

__Additional info:__ 
[Output of the remote backup command](https://gist.github.com/dictvm/3603770c3974789f9a2e56f8f1143898)
[Logs from the InfluxDB during the connection attempts](https://gist.github.com/dictvm/4acc6f55e90ba33e9279e95e7996649d)

This is happening on AWS though I do not expect that to be relevant. The security group of the server node has been updated to allow TCP connections from the client taking the remote backup. This has been verified to work:

```
telnet 172.21.23.183 8088
Trying 172.21.23.183...
Connected to 172.21.23.183.
```

If the differences between versions are the root cause, this should be documented and caught during the initial connection.

**Comment by dictvm** [comment]
I have updated the issue to also include the logs from the server during a backup connection attempt.

**Comment by dgnorton** [comment]
@dictvm should work if...
1.  pull bits from 1.5.1 using 1.5.1 binaries
2.  injest bits to 1.3.6 using 1.3.6 binaries

Did you do that or use the same binary for both?

**Comment by dictvm** [comment]
@dgnorton I was attempting to connect to a server running 1.3 with the binary of 1.5. 

I was attempting to build an automation for updating Terraform-managed InfluxDB-nodes in an immutable way by a) starting a node with a newer version of Influx which takes a remote backup from the current InfluxDB in order to b) then automatically stop the old and c) start the new server. But I guess that won't be possible then.

**Comment by dgnorton** [comment]
@dictvm seems like that should be possible. Can it use the binary on the original node to create the backup and then use the binary on the new node to restore it?

**Comment by dictvm** [comment]
@dgnorton sure, that was my first approach because I didn't know about the remote backup functionality. It would have saved me the hassle of adding temporary public keys to use rsync for the data transfer. 😢

**Comment by dgnorton** [comment]
@dictvm you should be able to add the 1.3.6 `influxd` binary to the new server and use it to pull the backup from the old server. Then use the latest `influxd` binary to restore the backup.

**Comment by dictvm** [comment]
@dgnorton yeah, that is an option, but it makes the provisioning more complex because I need to track different versions of InfluxDB and keep a compatibility matrix somewhere. I'll just keep migrating the backup data via rsync from host to host and do a restore.

I'd still prefer the option of taking a remote backup between different versions. I think that's a nice feature to have for future versions.

**Comment by melvinkoh2** [comment]
Is this issue solved? I'm still facing the same issue in version 1.6.2.
