### ISSUE TITLE
RPM Package dependency error with OpenSuse distro

### ISSUE THREAD

**Issue by claneys** [influxdata/influxdb#9623]
### Bug report

__System info:__ OpenSuse Tumbleweed witrh InfluxDB 1.5.1
__Steps to reproduce:__

1. Download RPM at https://dl.influxdata.com/influxdb/releases/influxdb-1.5.1.x86_64.rpm
2. Try to install using `zypper` package manager. 

__Expected behavior:__ RPM installation processing without error

__Actual behavior:__ Dependency problem:

```bash
Problem: nothing provides shadow-utils needed by influxdb-1.5.1-1.x86_64
 Solution 1: do not install influxdb-1.5.1-1.x86_64
 Solution 2: break influxdb-1.5.1-1.x86_64 by ignoring some of its dependencies
```

__Additional info:__ Problem located in script inlfuxdb_packages.bash which include hardcoded dependency to shadow-util but OpenSuse equivalent package is named shadow. If I remember correctly, `rpmbuild` tool should be able to detect those deps, no ? So you wouldn't have it to specify it.

Thanks :)

**Comment by lanox** [comment]
I am having same issue here ? is there any solution to this ?

**Comment by LIV2** [comment]
@lanox I, too am having this issue

**Comment by kaiokassiano** [comment]
I am facing this in openSUSE 42.3 with an Ansible task (zypper module) to install influxdb.

**Comment by zexxar** [comment]
The Problem still exists with a recent version is there any solution yet?

![influxdb_suse_update](https://user-images.githubusercontent.com/4499859/57223615-e96f2200-7006-11e9-9b53-c9317c34831b.png)

**Comment by cmd-influx** [comment]
The state has not changed.  For OpenSuse we continue to suggest "rpm -i --nodeps" for Influxdb.

**Comment by alpi-ua** [comment]
come here from Aug 2020
