### ISSUE TITLE
Value not converted into integer from sub query

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#9624]
I noticed this:

```
> create database db
> use db
Using database db
>
> insert cpu value=5
> insert cpu value=2
>
> SELECT value FROM (SELECT MEAN(value) AS value FROM cpu)
name: cpu
time value
---- -----
0    3.5
>
> SELECT value::float FROM (SELECT MEAN(value) AS value FROM cpu)
name: cpu
time value
---- -----
0    3.5
>
> SELECT value::integer FROM (SELECT MEAN(value) AS value FROM cpu)
name: cpu
time value
---- -----
0
>
```

Tested on `1.5.0`. Also seems broken on `1.4.2`

**Comment by jsternberg** [comment]
This is partially fixed on master, but not completely. On master, this does not perform the final cast to coerce it to be the correct type, which the cursor should absolutely do.

The fix on master will likely be different than the fix for 1.5.0 and 1.4.2.
