### ISSUE TITLE
Is there any API used to modify influxdb configuration file?

### ISSUE THREAD

**Issue by crazy-canux** [influxdata/influxdb#9644]
Hi there,
              I want to know is there any API used to modify  /etc/influxdb/influxdb.conf ?
              I know kapacitor have some http api used for this.
              But what about telegraf & influxdb?

**Comment by dgnorton** [comment]
@crazy-canux there isn't an API in InfluxDB for this but it's just a [toml](https://github.com/toml-lang/toml) file and there are libraries available for working with toml.

Closing since this is a usage question.
