### ISSUE TITLE
fatal error: runtime: out of memory - 16Core-100GB Ram - Influx-1.5

### ISSUE THREAD

**Issue by kunalag** [influxdata/influxdb#9654]
### Bug report

__System info:__ 1.5.0-1, Debian GNU/Linux 9.3, 16Core , 104GB RAM, 100GB SSD

__Steps to reproduce:__

1. Trying to run a simple query to get 50-100 records based on time and tags

__Expected behavior:__ To return the records in very less time

__Actual behavior:__ All cores go to 100% and ram usage also starts increasing and after 100% ram usage, influx crashes -with error "fatal error: runtime: out of memory"

__Additional info:__ [ShardGroupDuration - 7 days][ No of series >10Mil][Measurement contains 1 tag, overall 32K field values(it varies series to series, 32K is not for every series point, data is very similar in the fields, but requirement was to have different field name based on each tag value)][Data Ingestion works just fine][Not able to query any data in db]

Attaching the debug files as requested:
[iostat.txt](https://github.com/influxdata/influxdb/files/1859620/iostat.txt)
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/1859621/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/influxdb/files/1859622/vars.txt)

**Comment by shilicqupt** [comment]
we meet same problem, any progress?

**Comment by dgnorton** [comment]
@kunalag not sure I understand the shape of the data but a different field name for every tag value in a database with high tag cardinality is likely to cause problems at query time. What's the use-case for doing that? Are you trying to index the fields?

Also, can you post an example query that's causing the OOM?

**Comment by russorat** [comment]
closing due to lack of response from the user.
