### ISSUE TITLE
WAL file corrupt

### ISSUE THREAD

**Issue by dev-e** [influxdata/influxdb#9657]
System info: InfluxDB 1.5.1 running on k8s with data volume stored on NFS mouted via PVC
CoreOS 1632.3.0
Docker version 17.09.1-ce, build 19e2cf6

After a possible deficite on available disk space (~5% available) a single-node InfluDB instance after restart reported that some wal files are corrupted. It resulted in ~40 minutes loss of data in all measurements in all databases.

Log messages during deficite on available disk space:
```
lvl=error msg="[500] - \"engine: error rolling WAL segment: error opening new segment file for wal (2): close /var/lib/influxdb/wal/amis/default/1879/_00095.wal: file already closed\"" log_id=078ERvAl000 service=httpd
lvl=info msg="Write failed" log_id=078ERvAl000 service=write shard=1879 error="engine: error rolling WAL segment: error opening new segment file for wal (2): close /var/lib/influxdb/wal/amis/default/1879/_00095.wal: file already closed"
lvl=info msg="Error compacting TSM files" log_id=078ERvAl000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078SFPDl000 op_name=tsm1_compact_group error="remove /var/lib/influxdb/data/amis/default/1371/000000185-000000002.tsm.tmp: no space left on device"
```

Log messages after restart:
```
lvl=info msg="File corrupt" log_id=078ERvAl000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/amis/default/1311/_00534.wal pos=3567596`
```

Expected behavior: no data loss, when there is space available!

**Comment by dgnorton** [comment]
The `no space left on device` is the Go runtime and probably OS saying there isn't enough space so that's definitely one problem. The system needs to have at least enough space left to compact the largest shard, flush the WAL, and any data cached in memory.

**Comment by dev-e** [comment]
So is there a way to recover corrupted WAL files?

**Comment by dgnorton** [comment]
You could try the [`influx_inspect` tool](https://github.com/influxdata/influxdb/tree/master/cmd/influx_inspect). Run `influx_inspect export -help` for options. I'm not sure if it will work with a corrupt WAL file. If the file was simply truncated due to running out of disk space, then it may be possible to salvage the data.

**Comment by dev-e** [comment]
I exported the time interval from db, where the data was lost, with `influx_inspect export`. During the creation of the export file there was no errors. `influx_inspect verify` also shows no errors.
But when I imported this file back with `influx -import` the command ended with error: `ERROR: 4548838 points were not inserted`.
InfluxDB on the start now does not report any errors with wal files. Anyway, the data is lost.

**Comment by dgnorton** [comment]
@dev-e on the machine where you ran the import, did it dump errors to stderr? Looks like the export was successful, at least for 4.5M points. Those should be recoverable if we can figure out what stopped the import from working. Also, the export file should either be plain text with InfluxDB line protocol or compressed. Either way, you should be able to examine the contents and see if the data looks reasonable.
