### ISSUE TITLE
Write tool to import data with new retention policy

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#9674]
Tool is paired with `influx-tools export` (#9675) and is responsible for importing a database with a alternate retention policy. It is intended to be used offline. It must be capable of handling a large data set.

Primary goal is efficiency in reading the exported data and writing fully compacted TSM files. It must use the meta service abstraction to facilitate use in the OSS and Enterprise editions.

Default behavior is the tool will not overwrite local data unless the `--replace` option is specified.

## Import format:

* text: line protocol
* binary (suggestion): similar to the storage RPC API (frames) 
    * reduce the data size and work required to process

## Other required options:

| argument | comment |
| :----- | :----- |
| `-database` | target database
| `-rp` | target retention policy name
| `-duration` | target retention policy duration
| `-shard-duration` | target shard duration
| `-replace` | required if the target retention policy exists _or_ does not match the specified parameters (duration and shard duration).

---- 

`-replace`

* if the specified retention policy exists and the `-duration` or `-shard-duration` does not match, existing shards should be deleted and new ones created
* replace is also required in order to overwrite existing shards

**Comment by toni-moreno** [comment]
@stuartcarnie if still you need this feature, we have coded a tool that can help you.

https://github.com/toni-moreno/syncflux/blob/master/README.md#run-as-a-database-replication-tool
