### ISSUE TITLE
Unable to connect to Influxdb in docker when using ssl

### ISSUE THREAD

**Issue by anarwal27** [influxdata/influxdb#9681]
### Directions
I have an instance of influxdb deployed in kubernetes cluster, which I can assure is working as ping command (curl -sl -I -k https://<domain_name>/ping) works.  For this,  I am getting following response
```
 curl -sl -I -k https://<domain_name>/ping
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: dd94973b-3826-11e8-8001-000000000000
X-Influxdb-Version: 1.3.1
Date: Wed, 04 Apr 2018 16:40:21 GMT
```

However when I exec in running container and try to connect to influx using 
`influx -ssl -unsafeSsl -host <domain_name>.com`

Error: connection timed out

I was also able to run POST and GET

`curl -i -k -XPOST https://<domain_name>/query --data-urlencode "q=CREATE DATABASE mydb"`
and verify that Database is created and exists

`curl -k -G 'https://<domain_name>/query' --data-urlencode 'q=SHOW DATABASES'
{"results":[{"statement_id":0,"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["mydb"]]}]}]}`

Looks like there any issue with using cli with https version of influxdb.

**Comment by anarwal27** [comment]
Also there is an issue with documentation.

![image](https://user-images.githubusercontent.com/27233659/38329825-f1e6c406-381c-11e8-8382-6b1172638e13.png)

**Comment by jsternberg** [comment]
What port are you using? The influx CLI uses port 8086 by default, but your `curl` commands are using `443` since that's the default for HTTPS. If you are running InfluxDB on port 443, you might have to add `-port 443` to the CLI invocation or you can run InfluxDB on port 8086 and use `curl https://localhost:8086`.

**Comment by anarwal27** [comment]
@jsternberg using just `influx -ssl -unsafeSsl` worked for me. I dint had to supply host name when inside the docker container where influxDB is running. Not sure where this would go in documentation.
