### ISSUE TITLE
[1.5.0 - 1.6.0] Show tag value with regex very long

### ISSUE THREAD

**Issue by ptitou** [influxdata/influxdb#9683]
### Bug report

__System info:__ 

Branch | Build Time | Commit | Version
-- | -- | -- | --
1.5 | "" | "6ac835404e7e64ea7299a6eebcce1ab1ef15fe3c" | "1.5.0"
and next versions

__OS__ : 
CentOS Linux release 7.2.1511 (Core)

__Steps to reproduce:__

Launch a query "show tag values" with on or more regex in where clause

SHOW TAG VALUES FROM "jmeter" WITH KEY= "transaction" where application =~ /wadis/ and transaction =~ /[^GetMesure|all]/

Every regex do the same result, even with only one regex is the where clause.

__Results:__ 

| Version | commit | result | duration | cpu time |
| -- | -- | -- | -- | -- |
| 1.3.5 | 9d9001036d3585cf21925c13a57881bc6c8dcc7e | ok | 52767µs | real    0m0.115s |
| 1.4.2 | 6d2685d1738277a1c2672fc58df7994627769be6 | ok | 43049µs | real 	0m0.089s |
| 1.5.0 | 6ac835404e7e64ea7299a6eebcce1ab1ef15fe3c | [panic:runtime error: invalid memory address or nil pointer dereference] | - | real    0m0.084s |
| 1.5.1 | cdae4ccde4c67c3390d8ae8a1a06bd3b4cdce5c5 | ok | 21660486µs | real    0m21.629s |
| 1.6.0 | aa61359cc74f220f4e5680de3a6d699691c0b793 | ok | 21536867µs | real    0m21.495s |

All versions are running in inmem configuration, same os, same hardware.

I thank I was in this bug #9597 but even when a I do many restart, I've the behaviour. When I reload the database in v 1.3.5 or 1.4.2, the performances are ok.
I reference also this issue #8640 because maybe there is regression in 1.5.0 and next version ?

**Comment by max3163** [comment]
Still no information about it ?
