### ISSUE TITLE
Applying selectors on math based queries

### ISSUE THREAD

**Issue by droidnxs** [influxdata/influxdb#9688]
**InfluxDB version**: 1.4.3
When I issue a query as `SELECT percentile(((last("colA")-first("colA")),90) FROM..;` it expects a field as argument to the percentile selector and the query fails. I also tried something like `SELECT ((last("colA")-first("colA")) AS colB, percentile(colB,95) AS pct FROM..;` and that simply outputs an empty column for pct. Is there any else way of achieving this, or could be considered as a future addition?

**Comment by dgnorton** [comment]
@droidnxs a subquery should work for that. E.g.,
```
select percentile(diff,90) from (select last(a)-first(a) as diff from...)
```
For usage questions, the best place to ask is in the [InfluxData community](https://community.influxdata.com/) forum.
