### ISSUE TITLE
InfluxDB CONTINUOUS QUERIES does not work

### ISSUE THREAD

**Issue by qli-aa** [influxdata/influxdb#9691]
I had a InfluxDB 1.5.1 container running in AWS ECS
I tried to create CONTINUOUS QUERIES into influxdb, but it does not work after I created.

e.g.:
CREATE CONTINUOUS QUERY cpu_usage_daily_avg ON test_a BEGIN SELECT mean(usage_active) AS cpu_usage_active, mean(usage_guest) AS usage_guest, mean(usage_guest_nice) AS usage_guest_nice, mean(usage_idle) AS usage_idle, mean(usage_iowait) AS usage_iowait, mean(usage_irq) AS usage_irq, mean(usage_nice) AS usage_nice, mean(usage_softirq) AS usage_softirq, mean(usage_steal) AS usage_steal, mean(usage_system) AS usage_system, mean(usage_user) AS usage_user INTO report_daily.system.cpu FROM bdp.system.cpu WHERE cpu = 'cpu-total' GROUP BY time(1d), * END

DB report_daily and retention policy system was created before I created the CONTINUOUS QUERIES, I did not get any useful info from logs

here is the config about CONTINUOUS QUERIES:
```
[continuous_queries]
  enabled = true
  log-enabled = true
  query-stats-enabled = false
  run-interval = "1s"
```

**Comment by qli-aa** [comment]
If I run INFLUX SQL manually, it works normal.

**Comment by pauljherrera** [comment]
Having a similar problem.

I am running InfluxDB 1.5.2 on Ubuntu 16.04

My continuous query is:
```
CREATE CONTINUOUS QUERY second_to_minute ON live_rp BEGIN SELECT first(rp) AS open, max(rp) AS high, min(rp) AS low, last(rp) AS close INTO live_rp_1m.one_year.:MEASUREMENT FROM live_rp.one_day./.*/ GROUP BY time(1m) END
```
But it's not working. If I run the following query alone in the CLI it works:
```
SELECT first(rp) AS open, max(rp) AS high, min(rp) AS low, last(rp) AS close INTO live_rp_1m.one_year.:MEASUREMENT FROM live_rp.one_day./.*/ GROUP BY time(1m)
```

**Comment by pauljherrera** [comment]
On my end, the problem was simply a divergence of timezones. The server receiving the data was writing it using UTC-3, the server with the DB was using UTC. Therefore, when running the CQ, the database didn't found timestamps during the last minute.

**Comment by JayHyeonwoo** [comment]
@pauljherrera  That's a point.
There would be a difference between "Times in the series" and "UTC OS time".
So when you change the time manually, using now() method, the time difference makes an error!
good luck
