### ISSUE TITLE
Filtering by tag return empty set.

### ISSUE THREAD

**Issue by pauloone** [influxdata/influxdb#9695]
I have a consequent influxdb database, and it appears that filtering by tags stopped working.
For example:
If I do
SELECT "value" FROM "load" WHERE time >=  now() - 15m AND "dc"="afra" GROUP BY time(15m), "dc";
I got an empty set (with no delay)
but
SELECT "value" FROM "load" WHERE time >=  now() - 15m GROUP BY time(15m), "dc";
works. and return values for dc afra.

there is no particular influx db logs, set are just empty.

System details:
ubuntu Xenial (16.04.4)
influxdb 1.5.0 then 1.5.1 (problem continue after upgrade)
One standalone node.

**Comment by dgnorton** [comment]
@pauloone does it work with single quotes around `'afra'`? InfluxQL uses double quotes around identifiers (e.g, field and tag keys) and single quotes around string literals (e.g., tag values).

**Comment by pauloone** [comment]
That doesn't work with neither single or double quotes.

**Comment by pauloone** [comment]
> SELECT mean("value") FROM "load" WHERE time >= now() - 15m AND "dc"='afra' GROUP BY time(1m), "dc";

return 0 data.
and 
> SELECT mean("value") FROM "load" WHERE time >= now() - 15m GROUP BY time(1m), "dc";

works, and returns elements for the "afra" dc (as well as other DC values too).

The following query is also returning an empty set of values:
> SELECT mean("value") FROM "load" WHERE time >= now() - 15m AND "dc" =~ /.*/ GROUP BY time(1m), "dc";

Where are originaly using grafana to build the query, and that was working fine until last friday. The query has not been changed.

Note that if I use grafana to query data before friday, I have successfull result with and without per DC filtering.

**Comment by dgnorton** [comment]
@pauloone did it stop working when you upgraded from 1.5.0 to 1.5.1? Or, were you on an older version that was working and it broke after upgrading to 1.5.0?

What does this query return?
```
select count("value") from "load" where time >=now() - 15m and "dc"='afra'
```
What does this shell command return?
```
influx -database <your-db-name> -execute 'select count("value") from "load" where time >=now() - 15m and "dc"='\''afra'\'' group by "dc"' | grep tags
```

**Comment by pauloone** [comment]
@dgnorton No I upgraded because the bug appears, hoping latest version may have a bug fix, but did not resolve it.
Queries are now working again since 1:00 AM. Nothing has changed.
If an ran query on time including the bad period, I have empty set of result.

`select count("value") from "load" where time >=now() - 24h and "dc"='afra'`

return nothing.

`select count("value") from "load" where time >=now() - 2h and "dc"='afra'`

is successfull.

 `influx -database <your-db-name> -execute 'select count("value") from "load" where time >=now() - 15m and "dc"='\''afra'\'' group by "dc"' | grep tags`

return tags: dc=afra

 `influx -database <your-db-name> -execute 'select count("value") from "load" where time >=now() - 96h and "dc"='\''afra'\'' group by "dc"' | grep tags`

return nothing

 `influx -database <your-db-name> -execute 'select count("value") from "load" where time >=now() - 96h  group by "dc"' | grep tags`

return tags: dc=afra

**Comment by tux-00** [comment]
Maybe linked with https://github.com/influxdata/influxdb/issues/9529 ?

I have a similar problem on 1.5.2.
`select direction from mybase` returns nothing but `select * from mybase` return the `direction` column with his different values.

**Comment by dannybeeckman** [comment]
I am also encountering this problem:

**DATA:**
`SELECT "diskFreeBlocks", "diskTotalBlocks" FROM "diskPartitions" WHERE time >= now() - 1h GROUP BY "hostname", "partitionName"`

**NO DATA:**
`SELECT "diskFreeBlocks", "diskTotalBlocks" FROM "diskPartitions" WHERE ("partitionName" <> '/tmp') AND time >= now() - 1h GROUP BY "hostname", "partitionName"`

**NO DATA:**
`SELECT "diskFreeBlocks", "diskTotalBlocks" FROM "diskPartitions" WHERE ("partitionName" = '/var') AND time >= now() - 1h GROUP BY "hostname", "partitionName"`

**Comment by badhop** [comment]
Could you check if you have fields and tags with the same name?
For example:
SHOW FIELD KEYS FROM "load"
SHOW TAG KEYS FROM "load"

**Comment by tiagostutz** [comment]
Maybe you should specify a **field** in the `SELECT` clause, as described in https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#common-issues-with-the-select-statement

To show an example:

When I run the query:
```SELECT * from "speedY"```

The result is:
```
name: speedY
time                $documentHeight $unit $url                                            accountId baseTopic             deviceId                             domain   entityId entityName                              entityType          id_pessoa key                                                                      nodeId userId usuario                            value  value_1
----                --------------- ----- ----                                            --------- ---------             --------                             ------   -------- ----------                              ----------          --------- ---                                                                      ------ ------ -------                            -----  -------
1551959946220205932 23345           px/s  http://localhost:3001/atividade-academica/m/161 edidatico accounts/edidatico/52 56493ca0-7a51-11e8-b9bd-eb453bcb7cc9 accounts 30       Preservar você ou o Meio Ambiente? (30) atividade-academica 113       accounts/edidatico/52/56493ca0-7a51-11e8-b9bd-eb453bcb7cc9/scroll/speedY scroll 52     Jorge Curado (jorge@edidatico.com) 153.6  153.6
...
```

Then, to get only **field** data, I run: ```SELECT *::field from "speedY"```
And the result is: 
```
name: speedY
time                $documentHeight $unit $url                                            value
----                --------------- ----- ----                                            -----
1551959946220205932 23345           px/s  http://localhost:3001/atividade-academica/m/161 153.6
```

But if I run the following to get only **tag** data: ```SELECT *::tag from "speedY"```

The result is **empty**

Also, if I try to run a select only on tags, like 
```
SELECT "accoundId", "entityType" from "speedY"
```

Empty result again.

Now, if I run those tag queries above with the **field** "$url" (not a keyword it is a field on my test data) in the `SELECT` clause, the data comes.

Query:
```
SELECT "$url", "accoundId", "entityType" from "speedY"
```
Result:
```
name: speedY
time                $url                                            accoundId entityType
----                ----                                            --------- ----------
1551959946220205932 http://localhost:3001/atividade-academica/m/161           atividade-academica
```

Query:
```
SELECT "$url", *::tag from "speedY"
```

Result:
```
name: speedY
time                $url                                            accountId baseTopic             deviceId                             domain   entityId entityName                              entityType          id_pessoa key                                                                      nodeId userId usuario                            value
----                ----                                            --------- ---------             --------                             ------   -------- ----------                              ----------          --------- ---                                                                      ------ ------ -------                            -----
1551959946220205932 http://localhost:3001/atividade-academica/m/161 edidatico accounts/edidatico/52 56493ca0-7a51-11e8-b9bd-eb453bcb7cc9 accounts 30       Preservar você ou o Meio Ambiente? (30) atividade-academica 113       accounts/edidatico/52/56493ca0-7a51-11e8-b9bd-eb453bcb7cc9/scroll/speedY scroll 52     Jorge Curado (jorge@edidatico.com) 153.6
...
```

**Comment by Klagopsalmer** [comment]
I have experienced quite the same issue:

This works:
```
select count("he1_measure_degree_celsius") from "autogen"."CX-1 log" where time >= now() - 10d and "air_status" ='1.0'
name: CX-1 log
time                count
----                -----
1553262272443865272 14609
```

But not this:
`select count("he1_measure_degree_celsius") from "autogen"."CX-1 log" where time >= now() - 30d and "air_status" ='1.0'`

I have found that I had a field and a tag with the name `air_status` for a while. I'm not able to clearly reproduces the issue around the time I stopped using a field with the same name but I know that this works:

```
select count("he1_measure_degree_celsius") from "autogen"."CX-1 log" where time >= now() - 30d and "air_status"::tag ='1.0'
name: CX-1 log
time                count
----                -----
1551534615484287003 713841
```

Hope it can help.

**Comment by midN** [comment]
Any workaround yet? That's one nasty bug :(

**Comment by jportoles** [comment]
I'm seeing this exact issue as well.

`SELECT value FROM "ping.backend" WHERE time >= now() -1h;`
`> data`

`SELECT value FROM "ping.backend" WHERE time >= now() - 1h AND server='blub';`
`> empty response (no error)`

Oddly, regexp selects don't appear to be affected by this issue:

`SELECT value FROM "ping.backend" WHERE time >= now() - 1h AND server =~ /blub/;`
`> data pertaining to blub`

**Comment by surbhim7** [comment]
Any way to resolve this issue yet??
