### ISSUE TITLE
provide an package client error to match for non existing database.

### ISSUE THREAD

**Issue by krasi-georgiev** [influxdata/influxdb#9702]
Provide some official string constants as client error code.

## Current behavior:
The query method of influxdb client returns an error, but there is not stable way of determining its type other than string matching.

## Desired behavior:
Provide some official error code, or just some sting contants that we can use to determine the error type.

## Use case
Some monitoring clients (promethus remote storage adaptor) needs to create database in influxdb if database not exist.
https://github.com/prometheus/prometheus/pull/3542#pullrequestreview-98503220

here is one example how this is handled in the standard os package
https://golang.org/pkg/os/#IsNotExist

**Comment by jsternberg** [comment]
I agree this would be helpful, but a workaround at the moment is just to always create the database. It's an idempotent operation so you can do it as much as you want.

**Comment by krasi-georgiev** [comment]
got it thanks.
