### ISSUE TITLE
Upgrade from repository fails as of 10APR2018

### ISSUE THREAD

**Issue by Team503** [influxdata/influxdb#9704]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Ubuntu 16.04 LTS virtual machine on ESX 6.5
After failed upgrade: influxdb/unknown 1.5.1-1 amd64 [upgradable from: 0.10.0+dfsg1-1]
InfluxDB Repository deb https://repos.influxdata.com/debian jessie stable

__Steps to reproduce:__

1. sudo apt-get update
2. sudo apt-get upgrade

__Expected behavior:__ [What you expected to happen]
Upgrade to latest version

__Actual behavior:__ [What actually happened]
Upgrade failed with errors below, InfluxDB is now non-functional

sudo systemctl status influxdb
● influxdb.service - LSB: InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/etc/init.d/influxdb; bad; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

Apr 10 18:37:40 DFWpINFLUXDB01 systemd[1]: Stopped LSB: InfluxDB is an open-source, distributed, time series database.
Apr 11 09:55:00 DFWpINFLUXDB01 systemd[1]: Stopped LSB: InfluxDB is an open-source, distributed, time series database.
Apr 11 10:01:33 DFWpINFLUXDB01 systemd[1]: Stopped LSB: InfluxDB is an open-source, distributed, time series database.

__Additional info:__ [Include gist of relevant config, logs, etc.]
sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  influxdb
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/22.6 MB of archives.
After this operation, 58.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 92883 files and directories currently installed.)
Preparing to unpack .../influxdb_1.5.1-1_amd64.deb ...
Unpacking influxdb (1.5.1-1) over (0.10.0+dfsg1-1) ...
dpkg: error processing archive /var/cache/apt/archives/influxdb_1.5.1-1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/influx', which is also in package influxdb-client 0.10.0+dfsg1-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
influxdb.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install disable influxdb
insserv: warning: current start runlevel(s) (empty) of script influxdb' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script influxdb' overrides LSB defaults (0 1 6).
insserv: warning: current start runlevel(s) (empty) of script influxdb' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script influxdb' overrides LSB defaults (0 1 6).
/usr/bin/deb-systemd-helper: error: unable to read influxdb.service
insserv: warning: current start runlevel(s) (empty) of script influxdb' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script influxdb' overrides LSB defaults (0 1 6).
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/influxdb_1.5.1-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by rbabaee** [comment]
having the same problem here

**Comment by rbabaee** [comment]
Well, as it turns out, before upgrading , you must kill ALL influx processes ( cliend and influxd ). 
It will solve the problem :)
