### ISSUE TITLE
error writing snapshot

### ISSUE THREAD

**Issue by makareth** [influxdata/influxdb#9708]
__System info__
Influx v1.2.2
Ubuntu 16.04.2 LTS
Linux web1 4.9.87-xxxx-std-ipv6-64 #1 SMP Tue Mar 13 18:41:47 CET 2018 x86_64 x86_64 x86_64 GNU/Linux

__Steps to reproduce:__

1. Create a backup of 3 databases (x,y, and z) on host A.
2. Restore the meta from the x database to B.
3. Restore x, y, and z data to B.
4. Start inserting data

__Expected behavior:__
No "error writing snapshot" logs

__Actual behavior:__
The logs show the following, repeated approximatively every single second. Only the database prediction_db is impacted by this issue.

```
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z Snapshot for path /home/web/influxdb/data/prediction_db/autogen/775 written in 97.136903ms engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z error writing snapshot: compaction in progress engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z error writing snapshot from compactor: compaction in progress engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z Snapshot for path /home/web/influxdb/data/prediction_db/autogen/900 written in 106.127518ms engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z error writing snapshot: compaction in progress engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z error writing snapshot from compactor: compaction in progress engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z Snapshot for path /home/web/influxdb/data/prediction_db/autogen/770 written in 115.098612ms engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z error writing snapshot: compaction in progress engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z error writing snapshot from compactor: compaction in progress engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z Snapshot for path /home/web/influxdb/data/prediction_db/autogen/769 written in 55.496839ms engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z error writing snapshot: compaction in progress engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z error writing snapshot from compactor: compaction in progress engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z Snapshot for path /home/web/influxdb/data/prediction_db/autogen/774 written in 56.002377ms engine=tsm1
Apr 12 11:22:13 tdb influxd[30172]: [I] 2018-04-12T09:22:13Z error writing snapshot: compaction in progress engine=tsm1

```

**Comment by e-dard** [comment]
Hi @makareth. We can't effectively support or triage issue on v1.2.2. I highly recommend you upgrade to the latest release (v1.5.1). You need to follow [this upgrade path](https://docs.influxdata.com/influxdb/v1.5/administration/upgrading/#upgrading-influxdb-1-0-1-4-to-1-5) if you wish to move from `1.2.2` to `1.5.1` using the standard `inmem` index.

I'm happy to keep this issue open if you want to report back if you're still having issues.

**Comment by makareth** [comment]
Hi @e-dard, thank you. We have no upgrade planned for now but will definitely try to upgrade regularly to get support.

Looked like permissions of the failing database were no set correctly, so I suggest we have this issue closed.

**Comment by dgnorton** [comment]
@makareth thanks for letting us know.
