### ISSUE TITLE
influxDB 1.5 docs give wrong info on backup

### ISSUE THREAD

**Issue by xhpgkx** [influxdata/influxdb#9709]
### System Info: 
OS: Ubuntu 16.04.3
InflxDB: 1.5.1-1

### Issue details

[Docs ](https://docs.influxdata.com/influxdb/v1.5/administration/backup_and_restore/) for InfluxDB 1.5 say that "influxd backup <path-to-backup>" can be used "To back up everything". 
In reality it backs up only metastore([old](https://docs.influxdata.com/influxdb/v1.4/administration/backup_and_restore/) docs are correct on that matter).

__Steps to reproduce:__

1. run `influxd backup /tmp/backup`

__Expected behavior:__

Full(metastore, databases) backup is created.

__Actual behavior:__

Only metastore is backed up.

**Note: `influxd backup -portable <path>` does all databases' backup**

**Comment by stevebang** [comment]
Closing here -- moved to https://github.com/influxdata/docs.influxdata.com/issues/1535

**Comment by stevebang** [comment]
@xhpgkx Congratulations on opening your first GitHub issue -- unlike lots of first issues filed, which are typo corrections (and appreciated too!), your catch was an important error of omission that likely impacted many users. InfluxData appreciates the time you invested to help us! Thanks! The fix will be published within a few hours.
