### ISSUE TITLE
[tsi1 Index] Upgrading from 1.4.x to 1.5.2

### ISSUE THREAD

**Issue by binary0111** [influxdata/influxdb#9719]
### Clarification Request

I am upgrading my InfluxDB instances from versions 1.4.x using the tsi1 index to 1.5.2. The instances were a fresh install at the time of deployment and been using the tsi1 index from the get go. I just wanted to clarify if I still need to rebuild the index before migrating?

According to @benbjohnson's comment https://github.com/influxdata/influxdb/issues/9534#issuecomment-371910301 I need to.  I migrated one host as is and everything seems to be running fine.

**Comment by dgnorton** [comment]
@binary0111 Would you mind posting this as a question on the [community site](https://community.influxdata.com/) since it's not an issue?
