### ISSUE TITLE
Kapacitor union node doesn't work as expected

### ISSUE THREAD

**Issue by Yaski** [influxdata/influxdb#9720]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Ubuntu 16.04
InfluxDB 1.5.1
Kapacitor OSS 1.4.1 (git: HEAD b05bb0f6be089d6a1a391867ad4020344ce42a53)

__Steps to reproduce:__

Documentation says that union just passes points through
In my case I want to use union node to merge logic of writing data in database. I have points that are valid before union but union doesn't process them for some reason. When I remove union - points are writed in db as expected.

Simple script:
```

var values = stream
    |from()
        .measurement('measurement')

var o1 = values|where(lambda: "e1_a" > 0.01)
var o2 = values|where(lambda: "e1_a" < -0.01)

o1|union(o2)
    |influxDBOut()
        .database('kapacitor')
        .measurement('test_union')
        .buffer(0)
```

stream can be anything - doesn't matter in this case.
I just get points and filter them based on some logic and the points go in separate nodes and then I try to merge them again (collect resulted points) to write in database.
What I see is that when one of the parents of union node is empty - points doesn't flow through.

> stream0 [avg_exec_time_ns="0s" errors="0" working_cardinality="0" ];
> stream0 -> from1 [processed="289"];
> 
> from1 [avg_exec_time_ns="1.79µs" errors="0" working_cardinality="0" ];
> from1 -> where3 [processed="289"];
> from1 -> where2 [processed="289"];
> 
> where3 [avg_exec_time_ns="99.75µs" errors="138" working_cardinality="1" ];
> where3 -> union5 [processed="0"];
> 
> where2 [avg_exec_time_ns="278.35µs" errors="138" working_cardinality="1" ];
> where2 -> union5 [processed="151"];
> 
> union5 [avg_exec_time_ns="2.834µs" errors="0" working_cardinality="0" ];
> union5 -> influxdb_out6 [processed="0"];
> 
> influxdb_out6 [avg_exec_time_ns="0s" errors="0" points_written="0" working_cardinality="0" write_errors="0" ];

Points are collected in node. It looks like a cache because when I stop script - all points go to database. It is very strange because documentation doesn't say anything about a cache and futhermore I don't see any reason for union to cache points.

**Comment by jsternberg** [comment]
This belongs in the [kapacitor](https://github.com/influxdata/kapacitor) issue tracker.
