### ISSUE TITLE
No way to make a full(users+databases) restore from '-portable' backup

### ISSUE THREAD

**Issue by xhpgkx** [influxdata/influxdb#9723]
### Bug/lack of functionality report

__System info:__ 
InfluxDB: 1.5.1-1

__Steps to reproduce:__

1. Create database and user, grant it access to DB
1.1. `create database test`
1.2. `create user hi`
1.3. `grant all on test to hi`
2. Make a full backup
2.1 `influxd backup -portable /tmp/influx_backup`
3. Drop user and database/purge your InfluxDB installation
4. Restore `test` database from '-portable' backup
4.1 `influxd restore -portable -db test /tmp/influx_backup`

__Expected behavior:__
Database `test` is restored along with user that has grants on the DB.

__Actual behavior:__
Database is restored. User is not, grants are not.

__Additional info:__
Restoring '_internal' database doesn't restore users and grants, too.

This bug or feature of new '-portable' backup makes it impossible to have a true full restore on a brand new instance of InfluxDB.

Also, restoring users and grants from old metastore backup makes it impossible to restore data using 'influxd restore -portable' since latter requires the database to be absent and fails with `error updating meta: DB metadata not changed. database may already exist`.

**Note: 'xxxxxxxxx.meta' file generated by `influxd backup -portable' contains user data and probably grants data too**

**Comment by marcosmoreno** [comment]
We are experiencing exactly the same issue. Our databases rely on users and permission grants, therefore we really need them in order to work with InfluxDB. We stumbled upon this while trying to setup a system with the backup information. So we cannot make the restore procedure work, therefore we cannot migrate to 1.5.3. Any information from the dev team? Something we might be missing?

Steps followed:
* Started with version 1.3.1 (server A)
* Migrated to 1.5.3 (server A)
* Backed up the databases with -portable option (server A)
* Installed a new system (server B)
* Deleted the existing databases (server B)
* Restored the database with -portable option (server B)

**Expected result:** all data, users and grants from Server A are in Server B
**What actually happens:** users and grants are not in Server B.

**Comment by dictvm** [comment]
This would make it extremely easy to provide Point in Time Recovery and enable easy upgrade-paths for immutable infrastructure setups.

**Comment by w4tsn** [comment]
I've just migrated from one 1.5.x instance to another 1.5.x instance - with rather "small" pain. Here is what I did (Actually the research and trial and error were pain, so maybe I can prevent you from this).

## You'll need:

1. A full `-portable` backup `influxd backup -portable /path/to/backup`
2. A meta legacy backup `influxd backup /path/to/legacybackup`

## A workflow that worked was:

1. start with a fresh instance of influxdb
2. start influxdb (or the container with the required volumes)
3. make your influxd restore -portable ... to recover all databases and data (users and grants are missing)
4. stop influxdb
5. make an offline restore `influxd restore -metadir /var/lib/influxdb/meta /path/to/legacybackup/`
6. start influxdb and be happy about a running instance with users and grants :+1: 

## When using docker

Just to make this clear. When using docker you can do:

1. first in the running container `influxd restore -portable /path/to/backup`
2. then with container stopped `docker run --rm -v /srv/influxdb/data:/var/lib/influxdb -v /srv/influxdb/backup:/tmp/backup influxdb:1.5 influxd restore -metadir /var/lib/influxdb/meta /tmp/backup/20190523.snapshot`

With `meta.00` being in the backup volume under `/tmp/backup/20190523.snapshot/meta.00`.

When the container is started again, everything should be fine.

**Comment by lafrech** [comment]
Thanks @w4tsn for sharing this. The fact that users and permissions are not copied in the backup/restore process came as a surprise to me.

For some reason, the method you're sharing didn't work for me (still no data showing up) but it put me on the right track and I got it working using only legacy backups as explained in #9685.

**Comment by forzagreen** [comment]
It's really surprising that the restore does not restore everything. There must be an option to restore users grants.

**Comment by mahadi** [comment]
Cant't believe it, but thank you for sharing this!

**Comment by shadowlmd** [comment]
This bug is still there in 1.8.10 version. There is no way to restore users / grants from a portable backup. Even when you are restoring everything, users / grants are not restored.

**Comment by ThiefMaster** [comment]
How the hell is a bug like this open for 6 years?!
