### ISSUE TITLE
Add human-readable output for "GET /"

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#9724]
Over time, I've seen many reports from users about receiving a 404 error when they curl or use their browser to open `http://localhost:8086`.  Here's some community posts about it:

https://community.influxdata.com/t/404-page-not-found/4249
https://community.influxdata.com/t/localhost-8086-shows-404-page-not-found-how-do-i-see-the-gui/2364
https://community.influxdata.com/t/unable-to-browse-through-influx-db-after-setting-it-up-on-windows-nor-linux-machine/4768

And a couple github issues:
https://github.com/influxdata/influxdb/issues/436
https://github.com/influxdata/influxdb/issues/9668

We could eliminate some confusion if we emitted a simple HTML page that offered a brief usage explanation and included links to relevant docs pages.

**Comment by ryuhhnn** [comment]
What about simply returning text that states the status of the server? Adding in an HTML page (while trivial) might overly complicate things, when a simply "InfluxDB is running" message would suffice.

**Comment by evaryont** [comment]
Teaching my coworkers that a 404 is OK, in this specific instance, is still a hurdle for some of them. It'd be easier if the index page returned something, even a blank 200 page. Even better to include a message like the above.

**Comment by russorat** [comment]
In influxdb 2, the UI is served from that endpoint. We do not have plans to address this in the 1.x line.
