### ISSUE TITLE
Add Facebook's Prophet forecasting function to InfluxDB

### ISSUE THREAD

**Issue by jasonkeller** [influxdata/influxdb#9726]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

__Proposal:__ Add Facebook's Prophet forecasting function to InfluxDB

__Current behavior:__ We don't have this function today, only Holt-Winters.

__Desired behavior:__ Ideally we'd have this shiny new function!

__Use case:__ We currently have a project for forecasting the network traffic trends for all customer endpoint devices.  Playing around in R, it seems Prophet is doing a pretty good job at this, so it'd be nice to have this function native to InfluxDB.

**Comment by norillsa** [comment]
+1 - additive algorithm keeps it simple for the non-math types, plus...ya know...Facebook.
