### ISSUE TITLE
how to hide influxdb version for admin api

### ISSUE THREAD

**Issue by yixuan178** [influxdata/influxdb#9729]
hello, for security concern, is there way to disable version number show for http admin api? such as result from nmap.
8086/tcp  open  http         InfluxDB http admin 1.4.2
thanks,
Eugene

**Comment by jsternberg** [comment]
Can you show me what you mean? You say you used nmap to get that result, but can you give me the specific command? I'm not really sure where that name comes from.

**Comment by jsternberg** [comment]
So it looks like this is just part of nmap. I think the best solution to this would be to run InfluxDB behind an http proxy server and require nginx to be used as the proxy. You can run nginx on port 8086 if you wanted to and then have influxdb run on a different port.

You can hide headers using nginx: https://veggiespam.com/headers/#nginx-as-reverse-proxy

See `proxy_hide_header`.

I don't think that this is something that is appropriate for within InfluxDB though. If you want a more secure HTTP server, using nginx as a proxy is going to get you a lot further.
