### ISSUE TITLE
Backup both databases and metadata with new backup format

### ISSUE THREAD

**Issue by tgquan67** [influxdata/influxdb#9730]
Version: InfluxDB 1.5.1/1.5.2
OS: Debian 9.4
Step to reproduce: run `influxd backup -portable path/to/backup` on the first machine and run `influxd restore -portable path/to/backup` on the second machine.
Expected result: users from the first machine also got replicated on the second machine along with databases.
Actual result: several shards do not get replicated, all belong to _internal database.
Additional information: the old way of backing up metadata and each database works. There is no need to backup _internal database (perhaps it's included in the metadata backup?). But I need to backup everything without knowing what database is there. And I tried mixing the new full backup and the old metadata backup, but it also didn't work (I can see the users, databases and measurements, but cannot see any series).

Edit: is copying the whole /var/lib/influxdb directory and /etc/influxdb/influxdb.ini a legit way to backup influxdb?

**Comment by xhpgkx** [comment]
duplicate: https://github.com/influxdata/influxdb/issues/9723

**Comment by dgnorton** [comment]
Closing as duplicate
