### ISSUE TITLE
influxdb1.5 take too much memory

### ISSUE THREAD

**Issue by z1q1q7** [influxdata/influxdb#9739]
__System info:__ [1.5.1, CentOS release 6.9 (Final)]

__Steps to reproduce:__

1. [use influx_stress]
  
2. [after about one hour]
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
14579 influxdb  20   0  191g 102g  78g S 71.2 81.1   7042:08 influxd
3. [free -mh]
             total       used       free     shared    buffers     cached
Mem:          125G       125G       387M       224K       6.9M        98G
-/+ buffers/cache:        26G        98G
Swap:           0B         0B         0B

__Expected behavior:__ 
heapsys should be high or idle should be high.

__Actual behavior:__ 
_internal database show that heapsys about 30G. idle - released about 10G.
The influxd should take 40G?

__Additional info:__
stress config as follows:
 my template as follows:
    [write.point_generator.basic]
      # number of points that will be written for each of the series
      point_count = 151200
      # number of series
      series_count = 5000000
      # How much time between each timestamp
      tick = "1m"
      # Randomize timestamp a bit (not functional)
      jitter = true
      # Precision of points that are being written
      precision = "s"
      # name of the measurement that will be written
      measurement = "cpu"
      # The date for the first point that is written into influx
      start_date = "2018-Apr-16"
      # Defines a tag for a series
      [[write.point_generator.basic.tag]]
        key = "host"
        value = "server"
      [[write.point_generator.basic.tag]]
        key = "location"
        value = "us-west"
      [[write.point_generator.basic.tag]]
        key = "vip"
        value = "1.1.1.1"
      # Defines a field for a series
      [[write.point_generator.basic.field]]
        key = "bandwidth"
        value = "float64" # supported types: float64, int, bool

  [write.influx_client]
    [write.influx_client.basic]
      # If enabled the writer will actually write
      enabled = true
      # Addresses is an array of the Influxdb instances
      addresses = ["localhost:8086"] # stress_test_server runs on port 1234
      # Database that is being written to
      database = "stress3"
      # Precision of points that are being written
      precision = "s"
      # Size of batches that are sent to db
      batch_size = 5000
      # Interval between each batch
      batch_interval = "20s"
      # How many concurrent writers to the db
      concurrency = 100

I found that `heapsys` doesn't change too much. It seems `cached in free` so high, and `drop_caches` doesn't release it.
So, I'm wondering why influxdb process take so much res.

**Comment by z1q1q7** [comment]
I found that the shared memory so high. I don't understand who share memory with influxd?

**Comment by dgnorton** [comment]
@z1q1q7 if `influxd` is running the default config, then the index is completely held in memory. Looks like in the test it was configured for 5 million series. The more series, the larger the in-memory index. There are other factors involved as well but that is the most significant. You could try enabling `tsi1` index.

Probably not related to the mem usage but noticed the start date in the test was current day, time between timestamps was 1 minute, and points per series was ~151K so data is probably being written two or three months into the future. Again, probably not an issue but also not common real world usage.

Performance can vary greatly based on many use-case specific factors. We encourage users to test with data shapes and write & query loads that resemble their actual usage. If you run into problems under those conditions, the [community site](https://community.influxdata.com/) is a good place to ask questions about performance tuning. Then, if the problem continues, open an issue for it here.
