### ISSUE TITLE
Cache stores duplicate data points with resampling CQs

### ISSUE THREAD

**Issue by hahnjo** [influxdata/influxdb#9740]
### Bug report

__System info:__
InfluxDB 1.5.2 on CentOS 7
reproduced with `master` branch, built on ArchLinux

__Steps to reproduce:__

1. Start empty server
2. `CREATE DATABASE test`
3. Run `while true; do ./influx -database 'test' -execute 'INSERT test,tag=value field=1'; sleep 10; done` to create a stream of data (`SELECT derivative(pointsWrittenOK, 10s) FROM httpd WHERE time > NOW() - 1m` -> 1 point in 10 seconds)
4. `CREATE CONTINUOUS QUERY test_cq ON test RESAMPLE EVERY 10s FOR 20s BEGIN SELECT mean("field") as "field" INTO "test_agg" FROM "test" GROUP BY time(10s), * END`
5. Wait some time (see below)
6. `DROP CONTINUOUS QUERY test_cq ON test` and `CREATE CONTINUOUS QUERY test_cq ON test RESAMPLE EVERY 10s FOR 1m BEGIN SELECT mean("field") as "field" INTO "test_agg" FROM "test" GROUP BY time(10s), * END`

__Expected behavior:__
At above step 3:
```
> SELECT derivative(memBytes, 10s) FROM tsm1_cache WHERE time > NOW() - 1m AND "id" = '2'
name: tsm1_cache
time                derivative
----                ----------
1524054570000000000 16
1524054580000000000 16
1524054590000000000 16
1524054600000000000 16
1524054610000000000 16
```

I would expect `memBytes` to increase twice as fast with the CQ because old, resampled data doesn't differ from previously inserted data.

__Actual behavior:__
After step 5:
```
> SELECT derivative(memBytes, 10s) FROM tsm1_cache WHERE time > NOW() - 1m AND "id" = '2'
name: tsm1_cache
time                derivative
----                ----------
1524054980000000000 48
1524054990000000000 48
1524055000000000000 48
1524055010000000000 48
1524055020000000000 48
```
Note: `(2 + 1) x 16 = 48`

After step 6:
```
> SELECT derivative(memBytes, 10s) FROM tsm1_cache WHERE time > NOW() - 1m AND "id" = '2'
name: tsm1_cache
time                derivative
----                ----------
1524055020000000000 48
1524055030000000000 48
1524055040000000000 48
1524055050000000000 112
1524055060000000000 112
```
Note: `(6 + 1) * 16 = 112`

__Additional info:__
I understand that the cache is optimized for writes and is append-only. However, maybe the database can avoid storing unchanged data as often happening with resampling CQs? Even if we don't want to check `tsm` data, it might be a tradeoff to check the values already in the cache.

__Rationale:__
I assumed the only cost of raising the resample interval was increased CPU usage because it needs to consider a larger data volume. However, on a production system I immediately noticed a larger amount of data being written to the cache. As a first consequence this triggers more cache compactions and consequently more disk IO. Additionally I think this could also slow down queries because AFAICS the database needs to check the current cache for updates of old data which is now growing much faster.

**Comment by dgnorton** [comment]
@hahnjo For performance, it can't search the cache for every value while writing to ensure no duplication. The cache does deduplication at query time and compaction.

**Comment by hahnjo** [comment]
@dgnorton I see and I understand that the checking still needs to be done. But that will unnecessarily increase query time. Maybe it pays off to check for duplicates only for CQs which insert mostly duplicate data?

**Comment by hahnjo** [comment]
Thinking a bit more, the database doesn't need to check the whole cache: It would be sufficient to mark the position that the last invocation of this CQ started inserting and check backwards until that point.
