### ISSUE TITLE
Low percentile returns empty results for low count series 

### ISSUE THREAD

**Issue by vicvicg** [influxdata/influxdb#9741]
InfluxDB 1.5.

Input data:
name: percent
time                val
----                ---
1502296446000000000 0
1502296449000000000 0.24
1502296452000000000 1.14
1502296455000000000 1.9800000004
1502296458000000000 1.98
1502296461000000000 1.98

The following query returns empty result (expected: [1502296446000000000, 0]):
> SELECT percentile("val",5) FROM percent

Percentiles 10 and higher return expected results.

**Comment by sysadmin1139** [comment]
Just reproduced this! We were generating some 2nd and 98th percentile numbers in a bid to replace a statsd-like service with Influx and CQs. The 98th ones show up every time, the 2nd ones only if enough of them happened.

Influx 1.5.2

**Comment by shish** [comment]
I'm seeing this happen too, v1.7.2 - with 10 data points, I can get p50-p100, but p0-p49 return empty

**Comment by srinivasrk** [comment]
Same here with v1.7.1 (more info : https://github.com/influxdata/influxdb/issues/15202)

**Comment by nick-merrill** [comment]
I've run into this issue as well. I'd love to understand why this happens, as it really affects our data analytics quality.
