### ISSUE TITLE
InfluxDB frozen while trying to start on Windows platform

### ISSUE THREAD

**Issue by dz123** [influxdata/influxdb#9764]
I am using InfluxDB version 1.5 and Windows 10 machine on AWS instance

@tzonghao @aviau @xginn8 @sebito91

I followed the directions [here](http://www.vmkdaily.com/posts/how-to-guide-compiling-influxdb-on-windows) and [here](https://stackoverflow.com/questions/26116711/how-to-install-influxdb-in-windows) to install influxdb files on to Windows machine. When I try to run influx db via:

influxd -config influxdb.generated.conf

I get the following error message, and I am unable to see the localhost:PORT response. What am I doing wrong? Could it be that it doesnt detect a "version/branch/commit"? 

Config below:

> reporting-disabled = false
> bind-address = "127.0.0.1:8088"
> 
> [meta]
> dir = "C:\Users\Administrator\.influxdb\meta"
> retention-autocreate = true
> logging-enabled = true
> 
> [data]
> dir = "C:\Users\Administrator\.influxdb\data"
> index-version = "inmem"
> wal-dir = "C:\Users\Administrator\.influxdb\wal"
> wal-fsync-delay = "0s"
> query-log-enabled = true
> cache-max-memory-size = 1073741824
> cache-snapshot-memory-size = 26214400
> cache-snapshot-write-cold-duration = "10m0s"
> compact-full-write-cold-duration = "4h0m0s"
> max-series-per-database = 1000000
> max-values-per-tag = 100000
> max-concurrent-compactions = 0
> max-index-log-file-size = 1048576
> trace-logging-enabled = false
> 
> [coordinator]
> write-timeout = "10s"
> max-concurrent-queries = 0
> query-timeout = "0s"
> log-queries-after = "0s"
> max-select-point = 0
> max-select-series = 0
> max-select-buckets = 0
> 
> [retention]
> enabled = true
> check-interval = "30m0s"
> 
> [shard-precreation]
> enabled = true
> check-interval = "10m0s"
> advance-period = "30m0s"
> 
> [monitor]
> store-enabled = true
> store-database = "_internal"
> store-interval = "10s"
> 
> [subscriber]
> enabled = true
> http-timeout = "30s"
> insecure-skip-verify = false
> ca-certs = ""
> write-concurrency = 40
> write-buffer-size = 1000
> 
> [http]
> enabled = true
> bind-address = ":8086"
> auth-enabled = false
> log-enabled = true
> suppress-write-log = false
> write-tracing = false
> pprof-enabled = true
> https-enabled = false
> https-certificate = "/etc/ssl/influxdb.pem"
> https-private-key = ""
> max-row-limit = 0
> max-connection-limit = 0
> shared-secret = ""
> realm = "InfluxDB"
> unix-socket-enabled = false
> unix-socket-permissions = "0777"
> bind-socket = "/var/run/influxdb.sock"
> max-body-size = 25000000
> access-log-path = ""
> 
> [logging]
> format = "auto"
> level = "info"
> suppress-logo = false
> 
> [ifql]
> enabled = false
> log-enabled = true
> bind-address = ":8082"
> 
> [[graphite]]
> enabled = false
> bind-address = ":2003"
> database = "graphite"
> retention-policy = ""
> protocol = "tcp"
> batch-size = 5000
> batch-pending = 10
> batch-timeout = "1s"
> consistency-level = "one"
> separator = "."
> udp-read-buffer = 0
> 
> [[collectd]]
> enabled = false
> bind-address = ":25826"
> database = "collectd"
> retention-policy = ""
> batch-size = 5000
> batch-pending = 10
> batch-timeout = "10s"
> read-buffer = 0
> typesdb = "/usr/share/collectd/types.db"
> security-level = "none"
> auth-file = "/etc/collectd/auth_file"
> parse-multivalue-plugin = "split"
> 
> [[opentsdb]]
> enabled = false
> bind-address = ":4242"
> database = "opentsdb"
> retention-policy = ""
> consistency-level = "one"
> tls-enabled = false
> certificate = "/etc/ssl/influxdb.pem"
> batch-size = 1000
> batch-pending = 5
> batch-timeout = "1s"
> log-point-errors = true
> 
> [[udp]]
> enabled = false
> bind-address = ":8089"
> database = "udp"
> retention-policy = ""
> batch-size = 5000
> batch-pending = 10
> read-buffer = 0
> batch-timeout = "1s"
> precision = ""
> 
> [continuous_queries]
> log-enabled = true
> enabled = true
> query-stats-enabled = false
> run-interval = "1s

Log of the response:

> ts=2018-04-24T03:25:02.885131Z lvl=info msg="InfluxDB starting" log_id=07eQmA90000 version=unknown branch=unknown commit=unknown
> ts=2018-04-24T03:25:02.885131Z lvl=info msg="Go runtime" log_id=07eQmA90000 version=go1.10.1 maxprocs=8
> ts=2018-04-24T03:25:02.987133Z lvl=info msg="Using data dir" log_id=07eQmA90000 service=store path=C:\Users\Administrator\.influxdb\data
> ts=2018-04-24T03:25:02.987133Z lvl=info msg="Open store (start)" log_id=07eQmA90000 service=store trace_id=07eQmAYl000 op_name=tsdb_open op_event=start
> ts=2018-04-24T03:25:02.992133Z lvl=info msg="Reading file" log_id=07eQmA90000 engine=tsm1 service=cacheloader path=C:\Users\Administrator\.influxdb\wal\_internal\monitor\1\_00001.wal size=322183
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Opened shard" log_id=07eQmA90000 service=store trace_id=07eQmAYl000 op_name=tsdb_open path=C:\Users\Administrator\.influxdb\data\_internal\monitor\1 duration=31.000ms
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Open store (end)" log_id=07eQmA90000 service=store trace_id=07eQmAYl000 op_name=tsdb_open op_event=end op_elapsed=35.000ms
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Opened service" log_id=07eQmA90000 service=subscriber
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Starting monitor service" log_id=07eQmA90000 service=monitor
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Registered diagnostics client" log_id=07eQmA90000 service=monitor name=build
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Registered diagnostics client" log_id=07eQmA90000 service=monitor name=runtime
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Registered diagnostics client" log_id=07eQmA90000 service=monitor name=network
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Registered diagnostics client" log_id=07eQmA90000 service=monitor name=system
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Starting precreation service" log_id=07eQmA90000 service=shard-precreation check_interval=10m advance_period=30m
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Starting snapshot service" log_id=07eQmA90000 service=snapshot
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Starting continuous query service" log_id=07eQmA90000 service=continuous_querier
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Starting HTTP service" log_id=07eQmA90000 service=httpd authentication=false
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="opened HTTP access log" log_id=07eQmA90000 service=httpd path=stderr
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Storing statistics" log_id=07eQmA90000 service=monitor db_instance=_internal db_rp=monitor interval=10s
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Listening on HTTP" log_id=07eQmA90000 service=httpd addr=[::]:8086 https=false
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Starting retention policy enforcement service" log_id=07eQmA90000 service=retention check_interval=30m
> ts=2018-04-24T03:25:03.022134Z lvl=info msg="Listening for signals" log_id=07eQmA90000
> ts=2018-04-24T03:25:03.023136Z lvl=info msg="Sending usage statistics to usage.influxdata.com" log_id=07eQmA90000
> [tcp] 2018/04/24 03:28:58 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:54478 closed
> [tcp] 2018/04/24 03:28:58 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:54479 closed
> [tcp] 2018/04/24 03:28:58 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:54480 closed
> [tcp] 2018/04/24 03:28:58 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:54481 closed
> [tcp] 2018/04/24 03:28:58 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:54482 closed
> [tcp] 2018/04/24 03:28:58 tcp.Mux: handler not registered: 71. Connection from 127.0.0.1:54483 closed

**Comment by dgnorton** [comment]
@dz123 does that happen just by running `influxd.exe` or does it hang when you try to connect with the `influx` cli? If it's the altter, are you using a MINGW64 terminal? If so, try a regular CMD shell.

**Comment by dz123** [comment]
This happens when I run the "influxd.exe" on a normal command prompt window. The InfluxDB bannerhead loads and then it gets "stuck" right after "Sending Usage statistics to usage.influxdata.com". 

When I tried again just now the new logs show:

> ts=2018-04-24T04:05:01.491129Z lvl=info msg="Sending usage statistics to usage.influxdata.com" log_id=07eT3Z60000
> ts=2018-04-24T04:35:01.533476Z lvl=info msg="Retention policy deletion check (start)" log_id=07eT3Z60000 service=retention trace_id=07eUmR7G000 op_name=retention_delete_check op_event=start
> ts=2018-04-24T04:35:01.533476Z lvl=info msg="Retention policy deletion check (end)" log_id=07eT3Z60000 service=retention trace_id=07eUmR7G000 op_name=retention_delete_check op_event=end op_elapsed=0.000ms
> ts=2018-04-24T05:05:01.564600Z lvl=info msg="Retention policy deletion check (start)" log_id=07eT3Z60000 service=retention trace_id=07eWVIV0000 op_name=retention_delete_check op_event=start
> ts=2018-04-24T05:05:01.564600Z lvl=info msg="Retention policy deletion check (end)" log_id=07eT3Z60000 service=retention trace_id=07eWVIV0000 op_name=retention_delete_check op_event=end op_elapsed=0.000ms

**Comment by safdarrizvi** [comment]
Hi, I am also facing same issue. Please help me to install the Influxdb.

2018-07-16T09:06:08.104608Z     info    Sending usage statistics to usage.influxdata.com        {"log_id": "09KaHZjW000"}
2018-07-16T09:36:08.126148Z     info    Retention policy deletion check (start) {"log_id": "09KaHZjW000", "service": "retention", "trace_id": "09Kb~RkW000", "op_name": "retention_delete_check", "op_event": "start"}
2018-07-16T09:36:08.126148Z     info    Retention policy deletion check (end)   {"log_id": "09KaHZjW000", "service": "retention", "trace_id": "09Kb~RkW000", "op_name": "retention_delete_check", "op_event": "end", "op_elapsed": "0.000ms"}

**Comment by joesixpack** [comment]
Just ran into this on 1.7.1.  Fail.
