### ISSUE TITLE
HTTP 204 returned from /ping endpoint is unsuitable for Google Kubernetes Cloud healthcheck

### ISSUE THREAD

**Issue by cypressious** [influxdata/influxdb#9772]
## Use case

I want to deploy an InfluxDB instance to the Google Kubernetes Cloud. In order to expose the application to the outer world, I need to create an Ingress.

## Problem

The Ingress requires a health check. I can configure the endpoint of the health check but it needs to return a HTTP 200. The `/ping` endpoint currently returns an HTTP 204 which is unsuitable.

## Sugggestion

Consider adding an endpoint that returns a HTTP 200 or make the status code returned from `/ping` configureable.

**Comment by e-dard** [comment]
@cypressious I think this is a good suggestion, if it's not possible to configure the expected status code on that cloud platform.

In the meantime, you could use `/metrics` or `/debug/vars`, which will both return a `200`.

**Comment by e-dard** [comment]
Please do!

**Comment by russorat** [comment]
@cypressious according to the k8s docs found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request

> Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.

Is this issue still relevant?
