### ISSUE TITLE
Cannot compute math on result of two subqueries

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#9779]
### Bug report

__System info:__ Influxdb 1.5.2

__Steps to reproduce:__

If I run this query:

`SELECT * FROM (SELECT SUM(lastval) as bytes FROM (SELECT LAST("value") AS lastval FROM "filecount" WHERE ("host" =~ /hostname/ AND "type" = 'bytes' AND "instance" =~ /db1 mysql/)  GROUP BY instance)),(SELECT SUM(lastval) as entries FROM (SELECT LAST("entries") AS lastval FROM "db" WHERE ("host" =~ /hostname/ AND "type" = 'dbtype') GROUP BY instance)) GROUP BY instance
`
then I get this as output:

```
name: filecount
tags: instance=db1 mysql
time bytes        entries
---- -----        -------
0    164665707245

name: db
tags: instance=db1
time bytes entries
---- ----- -------
0          466577

```
If I run this query:

`SELECT bytes/entries FROM (SELECT SUM(lastval) as bytes FROM (SELECT LAST("value") AS lastval FROM "filecount" WHERE ("host" =~ /hostname/ AND "type" = 'bytes' AND "instance" =~ /db1 mysql/)  GROUP BY instance)),(SELECT SUM(lastval) as entries FROM (SELECT LAST("entries") AS lastval FROM "db" WHERE ("host" =~ /hostname/ AND "type" = 'dbtype') GROUP BY instance)) GROUP BY instance
`

I get this:
```
name: filecount
time bytes_entries
---- -------------
0

name: db
time bytes_entries
---- -------------
0

```
Removing the "GROUP BY" does not change the behaviour.

Adding "GROUP BY time(0s)" does not change the behaviour.

If I run this query:

`SELECT filecount.bytes/db.entries FROM (SELECT SUM(lastval) as bytes FROM (SELECT LAST("value") AS lastval FROM "filecount" WHERE ("host" =~ /hostname/ AND "type" = 'bytes' AND "instance" =~ /db1 mysql/)  GROUP BY instance)),(SELECT SUM(lastval) as entries FROM (SELECT LAST("entries") AS lastval FROM "db" WHERE ("host" =~ /hostname/ AND "type" = 'dbtype') GROUP BY instance)) GROUP BY instance
`

then there is no output

__Expected behavior:__

To get this as output:

```
time bytes_entries
---- --------------
0     352922.89856765335625202271

```
__Actual behavior:__

the math on the two fields from subqueries was not performed.

__Additional info:__

**Comment by yellowpattern** [comment]
This is close to what I want:

```
> SELECT * INTO j FROM (SELECT SUM(lastval) as bytes FROM (SELECT LAST("value") AS lastval FROM "filecount" WHERE ("host" =~ /hostname/ AND "type" = 'bytes' AND "instance" =~ /db1 mysql/))),(SELECT SUM(lastval) as entries FROM (SELECT LAST("entries") AS lastval FROM "db" WHERE ("host" =~ /hostname/ AND "type" = 'dbtype'))); select bytes/entries from j;
name: result
time written
---- -------
0    2

name: j
time bytes_entries
---- -------------
0    352922.8985676534
>
```

Which could be done with a continuous query... but I'd like to do it without that. If only I could make the first SELECT produce no output!

**Comment by yellowpattern** [comment]
Another attempt that does not work:

`SELECT j.bytes/j.entries FROM j,(SELECT * INTO j FROM (SELECT SUM(lastval) as bytes FROM (SELECT LAST("value") AS lastval FROM "filecount" WHERE ("host" =~ /hostname/ AND "type" = 'bytes' AND "instance" =~ /db1 mysql/))),(SELECT SUM(lastval) as entries FROM (SELECT LAST("entries") AS lastval FROM "db" WHERE ("host" =~ /hostname/ AND "type" = 'dbtype'))))`

**Comment by jsternberg** [comment]
This is something that's not possible at the moment. We are planning to support this as part of ifql which will have proper support for joining two different streams.

The reason this doesn't work is because using two subqueries is a concatenation operation rather than a join operation so it's not doing what you want it to do.
