### ISSUE TITLE
UDP Configuration confussion

### ISSUE THREAD

**Issue by cv711** [influxdata/influxdb#9790]
### Bug report

At the top of the configuration file it states:
https://github.com/influxdata/influxdb/blob/ecf474fd982e220a4d8221056f5ff0269a26849b/etc/config.sample.toml#L4-L5

and then lower at the UDP section:
https://github.com/influxdata/influxdb/blob/ecf474fd982e220a4d8221056f5ff0269a26849b/etc/config.sample.toml#L475-L489

__Expected behavior:__ I would expect that for example `batch-size = 5000` should be the default.

__Actual behavior:__ Makes me wonder if that's actually true since the header of the section states `You should have this enabled otherwise you could get dropped metrics or poor performance` Does that mean that the UDP defaults are different than the commented out sections?

Thanks,
Chris

**Comment by dgnorton** [comment]
@cv711 The values show in that sample config file are the default values. `batch-size = 5000` is the default. At the top of the sample config file, after the part you mentioned, it says...

> The commented out lines are the configuration field and the default value used. Uncommenting a line and changing the value will change the value used at runtime when the process is restarted.
