### ISSUE TITLE
HTTP response changes with the number of fields

### ISSUE THREAD

**Issue by MzazM** [influxdata/influxdb#9799]
### Bug report
Two very similar writes produce different HTTP response.

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB version: 1.5.1
__Steps to reproduce:__
Starting from the example that shows how to write multiple points at the same time here [https://docs.influxdata.com/influxdb/v1.5/guides/writing_data/#writing-multiple-points](url), I slightly modified it to increase the number of points written.

1. Using HTTP API write the following:

cpu_load_short,host=server02,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server02,region=us-west value=2.0 1524675030020
cpu_load_short,host=server03,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server03,region=us-west value=2.0 1524675030020
cpu_load_short,host=server04,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server04,region=us-west value=2.0 1524675030020
cpu_load_short,host=server05,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server05,region=us-west value=2.0 1524675030020
cpu_load_short,host=server06,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server06,region=us-west value=2.0 1524675030020
cpu_load_short,host=server07,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server07,region=us-west value=2.0 1524675030020
cpu_load_short,host=server08,region=us-west value=0.55 1524675030020

2. Using HTTP API write the following: (I just added an extra line at the bottom.. actually even few characters (e.g., a longer tag) would raise the issue). 

cpu_load_short,host=server02,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server02,region=us-west value=2.0 1524675030020
cpu_load_short,host=server03,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server03,region=us-west value=2.0 1524675030020
cpu_load_short,host=server04,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server04,region=us-west value=2.0 1524675030020
cpu_load_short,host=server05,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server05,region=us-west value=2.0 1524675030020
cpu_load_short,host=server06,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server06,region=us-west value=2.0 1524675030020
cpu_load_short,host=server07,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server07,region=us-west value=2.0 1524675030020
cpu_load_short,host=server08,region=us-west value=0.55 1524675030020
cpu_load_short,direction=in,host=server08,region=us-west value=2.0 1524675030020

__Expected behavior:__ 
Same HTTP response for both cases

__Actual behavior:__ 
For Case 1 I get  (**expected**): 
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: bba8340c-4e19-11e8-9e26-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.5.1
X-Request-Id: bba8340c-4e19-11e8-9e26-000000000000
Date: Wed, 02 May 2018 15:01:46 GMT

for Case 2 I get (**not expected**):
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: dbbaf187-4e19-11e8-9e28-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.5.1
X-Request-Id: dbbaf187-4e19-11e8-9e28-000000000000
Date: Wed, 02 May 2018 15:02:40 GMT

**Comment by dgnorton** [comment]
The client (`curl`?) must be sending the request with `Expect: 100-continue` header. Try POSTing the write request without that header.

**Comment by MzazM** [comment]
Thank you for pointing me to the right direction. Indeed the client I am using (LabVIEW HTTP API) sends `Expect: 100-continue` header if the content length is > 1024. Unfortunately, I cannot remove the additional header, but I found another workaround. Thanks.
