### ISSUE TITLE
need multiple types per row in backend storage

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#9811]
Using influxdb 1.5.2, when I do "select *" from a collectd table with "join" turned on, I see something like this:

```
time                fiel1  field2   fie3       field4  field5     host     instance field6   field7      field8 type
----                -----  ------   ----       ------- ---------- ----     -------- ------   ------      ------- ----
1525656780000000000 225787                     5889    27738      hostname instanc1                      227903  row_type1
1525656780000000000        31075569                               hostname instanc1 31300443                     row_type2
1525656780000000000                 7182587906                    hostname instanc1          64446422924         row_type3

```

If we look at how collectd receives data using PUTVAL, we have:

PUTVAL host/plugin-plugin_instance/type-type_instance

Prior to "join" mode, a complex type was broken down to a row per field in a type, so the above would be 8 rows in a table.

In terms of database space efficiency, my hope would have been to see multiple types per row but for now, there is a row per plugin/type

**Comment by dgnorton** [comment]
@yellowpattern not sure how that would work. How would InfluxDB `collectd` service know which plugin/type combos were supposed to go together? The `type` tag uniquely identifies where the data came from, so separate sources end up as separate series, and on different rows. Also, I'm not sure if that would result in better space efficiency.

What problem are you experiencing? Excessive disk usage? Can't query the data as desired with current schema? Etc.?

**Comment by yellowpattern** [comment]
The problem is disk space. I'm trying to work out what the best way to organise collectd data feeds for storage in influxdb. Do I need to organise it such that there are no blank fields in any row, for example.

**Comment by dgnorton** [comment]
@yellowpattern I think this is a usage question and not a bug. Would you post it on the [InfluxData community site](https://community.influxdata.com/)? Maybe a title like `disk space when using collectd`, brief description, and a link to this issue? If the discussion there determines there's a bug or optimization that needs to be made, comment here again and we'll reopen this issue. Thanks!

**Comment by dgnorton** [comment]
@yellowpattern GitHub issues are used to track bugs and feature requests and the [InfluxData community site](https://community.influxdata.com/) to answer usage questions. In this particular case, it is a usage question about how best to configure `collectd` and / or shape data to optimize disk space. It's not a bug / feature that can be assigned to someone to fix. The quickest way to get answers to usage questions is to ask them on the community site. We have people dedicated to answering usage questions there.
