### ISSUE TITLE
repos.influxdata.com does not support IPv6

### ISSUE THREAD

**Issue by wido** [influxdata/influxdb#9813]
repos.influxdata.com only has IPv4 DNS records (A) and does not support IPv6.

It seems to be running on AWS CloudFront which supports IPv6: https://aws.amazon.com/blogs/aws/ipv6-support-update-cloudfront-waf-and-s3-transfer-acceleration/

It would be very nice if this would be enabled for repos.influxdata.com (website already does IPv6!) so that IPv6-only hosts can download InfluxDB and Telegraf.

**Comment by claytondukes** [comment]
This is causing problems on all of our servers and customer servers now as well. We've had to disable ipv6 in linux in order to get the updates.

apt update stalls:
```
100% [Connecting to repos.influxdata.com (2600:9000:2013:3600:7:7790:e740:93a1)
```

To disable ipv6:
```
sudo su -
grep -q 'net.ipv6.conf.all.disable_ipv6 = 1' /etc/sysctl.conf || { echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf; sysctl -p; }
```

**Comment by wido** [comment]
This means something is not properly configured on IPv6 on your servers. You should not advise people to disable IPv6.

In your case there can be something wrong with firewalling or routing on your side. Disabling is *not* the right way to go.

**Comment by claytondukes** [comment]
@wido - no, it doesn't. IPv6 has been enabled and running on our servers forever (and working). It means that the influx repo servers are doing something wrong. When apt-get runs, it is ONLY trying to access `2600:9000:2013:3600:7:7790:e740:93a1` and refuses to connect. Thus, I provided a workaround...which, incidentally is the ONLY way currently to get influxdb to update.

Having said that, I should have added: "re-enable ipv6 after you update influxdb".

**Comment by wido** [comment]
@claytondukes Ok! That might be something which is not working on the Amazon CloudFront side, you might want to look into that.

For me it works just fine over IPv6.

**Comment by claytondukes** [comment]
>That might be something which is not working on the Amazon CloudFront side
Well now you lost me - we're on not Amazon, this is our corp lan. Noteworthy: Some of our servers use Hamachi which requires ipv6. Thus, when I disabled it to update influxdb, I had to re-enable it before hamachi would work again. So that leads me to believe that the influx team might have made a mistake in their repo.

**Comment by wido** [comment]
@claytondukes No problem! What I mean is that repos.influxdata.com runs on Amazon CloudFront.

So you might have a (local) issue with reaching them over IPv6.

<pre>
wido@wido-laptop:~$ host repos.influxdata.com
repos.influxdata.com has address 52.85.255.168
repos.influxdata.com has address 52.85.255.207
repos.influxdata.com has address 52.85.255.221
repos.influxdata.com has address 52.85.255.226
repos.influxdata.com has IPv6 address 2600:9000:2002:4a00:7:7790:e740:93a1
repos.influxdata.com has IPv6 address 2600:9000:2002:6a00:7:7790:e740:93a1
repos.influxdata.com has IPv6 address 2600:9000:2002:e600:7:7790:e740:93a1
repos.influxdata.com has IPv6 address 2600:9000:2002:b800:7:7790:e740:93a1
repos.influxdata.com has IPv6 address 2600:9000:2002:5800:7:7790:e740:93a1
repos.influxdata.com has IPv6 address 2600:9000:2002:7800:7:7790:e740:93a1
repos.influxdata.com has IPv6 address 2600:9000:2002:7600:7:7790:e740:93a1
repos.influxdata.com has IPv6 address 2600:9000:2002:f000:7:7790:e740:93a1
wido@wido-laptop:~$
</pre>

These are all addresses from AWS.

**Comment by wido** [comment]
Closing this one as it works for me.
