### ISSUE TITLE
Invoke-restmethod or invoke-webrequest to write multiple points from a text file to influxdb

### ISSUE THREAD

**Issue by amoghmahesh** [influxdata/influxdb#9815]
Is it possible to to write multiple points to influx from a file which has data in format [ measurement-name,tag-name=tag-value value-name=value ] using Invoke-RestMethod ?

as in curl we use
[ curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary @cpu_data.txt ]

**Comment by dgnorton** [comment]
@amoghmahesh Yes, that should work. Usage questions should be asked on the [InfluxData community site](community.influxdata.com).
