### ISSUE TITLE
Data loss and performance optimization

### ISSUE THREAD

**Issue by vicochan** [influxdata/influxdb#9818]
One single node 1.5.1 on production environment, one ssd hard-disk, physical  machine. There are three InfluxDB service running on this machine, In addition, there are 9 write influxdb programs.

### 1.Device information:
- 1.1 Machine: 80 core, 512G ram. 900G SSD

- 1.2 os: Red Hat Enterprise Linux 7.4

- 1.3 Current memory usage:
~~~
# free -lg
              total        used        free      shared  buff/cache   available
Mem:            503          52         427           0          22         448
Low:            503          75         427
High:             0           0           0
Swap:            23           0          23
~~~
- 1.4 io:
~~~
# iostat 
Linux 3.10.0-693.el7.x86_64 (jtdc-influxdb-1) 	05/09/2018 	_x86_64_	(80 CPU)
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           2.24    0.00    0.37    0.05    0.00   97.34
           
Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda              80.55         0.24     11756.40     485619 23332028469
dm-0              0.20         0.21        11.39     421188   22595208
dm-1              0.00         0.00         0.00       2228          0
dm-2              0.00         0.00         0.00       3896       4183
dm-3             13.58         0.00      2881.55       6236 5718800274
dm-4             67.26         0.01      8863.45      18493 17590625971
~~~
- 1.5 
~~~
#top
top - 15:06:41 up 22 days, 22:56,  3 users,  load average: 0.76, 1.21, 1.56
Tasks: 771 total,   1 running, 770 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.1 sy,  0.0 ni, 99.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 52768972+total, 47086956+free, 33540960 used, 23279208 buff/cache
KiB Swap: 25165820 total, 25165820 free,        0 used. 49242508+avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                           
17641 root      20   0 35.290g 0.023t 8.852g S  11.9  4.8 252:52.25 influxd                                                                            
 18026 root      20   0   18180  12200   2644 S   8.6  0.0  28:49.97 redis2influxdb                                                                    
  3177 root      20   0 31.223g 0.015t 5.324g S   5.0  3.1  14282:46 influxd                                                                           
 18031 root      20   0   17412  11180   2664 S   4.6  0.0  15:18.26 redis2influxdb                                                                    
  3229 root      20   0 5152936 541760  44332 S   1.7  0.1 223:48.71 influxd                                                                           
103362 root      20   0   18180  12560   2688 S   1.7  0.0 127:16.18 redis2influxdb                                                                    
103363 root      20   0   18180  11200   2632 S   1.0  0.0  43:16.96 redis2influxdb                                                                    
103371 root      20   0   16612   6584   2684 S   0.7  0.0   8:36.51 redis2influxdb 
~~~

### 2.The main configuration of influxdb is as follows:
~~~
[data]
    wal-fsync-delay = "50ms"
    cache-max-memory-size = "16g"
    cache-snapshot-memory-size = "1g"
    cache-snapshot-write-cold-duration = "10m"
    compact-full-write-cold-duration = "4h"
    max-series-per-database = 0
    max-values-per-tag = 0
[coordinator]
    write-timeout = "10s"
    max-concurrent-queries = 0
[retention]
    enabled = true
    check-interval = "30m"
[http]
    max-row-limit = 0
    max-connection-limit = 0
[[udp]]
    enabled = true
    bind-address = ":3080"
    database = "mingjun"
    retention-policy = "rpmj"
    batch-size = 50
    batch-pending = 10
    batch-timeout = "1s"
    read-buffer = 0
~~~
### 3. influxdb retention polices
~~~
> show retention policies 
name duration shardGroupDuration replicaN default
---- -------- ------------------ -------- -------
rpmj 6h0m0s   1h0m0s             1        true
~~~
### 4.  amount of data
The amount of data written in this database per day is 400 million

### quest
now ,I have two questions
question No.1: When I use udp to write data, some data is lost.I'm not sure whether the influx cache is flushed due to lost data.
question No.2: After a few days, querying through the http API interface becomes very slow and there will be a timeout.

What's wrong with this database?

**Comment by dgnorton** [comment]
@vicochan For the amount of data written per day, is that 400 million points? How many fields does each point have? If it's in the 1 - 4 fields per point range, that's < 20K values per second. Depending on the type of data you're writing and how quickly, it may be that the increased cache size settings are causing it to go long periods between flushes. Is this a test server that gets rebooted or the `influxd` daemon restarted?

Regarding query performance, can you give an example of a query that's timing out?

**Comment by vicochan** [comment]
1. yes, This database requires that 400 million data points be written, per point has 6 fields ，and this is a test server .
~~~
> select *::field from fencealltaxi01 where time > now() -10s limit 1
name: fencealltaxi01
time                 event ext.dir ext.height ext.lat ext.lon   ext.speed
----                 ----- ------- ---------- ------- -------   ---------
2018-05-10T02:31:50Z 1     68      0          23.1373 113.30994 12
> select event,*::tag from fencealltaxi01 where time > now() -10s limit 1
name: fencealltaxi01
time                 event ext.attr.car_stat ext.attr.nearbymeter ext.id  ids         type
----                 ----- ----------------- -------------------- ------  ---         ----
2018-05-10T02:32:32Z 1     1                 0                    A1CY26 capacity:86 alltaxi01


Using database _internal
> select derivative(pointReq,1s) from "write" where time > now() -5m
name: write
time                 derivative
----                 ----------
2018-05-10T02:30:10Z 1638.8
2018-05-10T02:30:20Z 1857.9
2018-05-10T02:30:30Z 1738.4
2018-05-10T02:30:40Z 1799.2
2018-05-10T02:30:50Z 1719.1
2018-05-10T02:31:00Z 1243.3
2018-05-10T02:31:10Z 1219.2
2018-05-10T02:31:20Z 2061.4
2018-05-10T02:31:30Z 1487.3
2018-05-10T02:31:40Z 1518.4
2018-05-10T02:31:50Z 1674.9
2018-05-10T02:32:00Z 1692.3
2018-05-10T02:32:10Z 1121.4
2018-05-10T02:32:20Z 1774.8
2018-05-10T02:32:30Z 1811.1
2018-05-10T02:32:40Z 1838.5
2018-05-10T02:32:50Z 962.5
2018-05-10T02:33:00Z 1902.6
2018-05-10T02:33:10Z 1723.9
2018-05-10T02:33:20Z 1765.6
2018-05-10T02:33:30Z 1870.1
2018-05-10T02:33:40Z 1851.5
2018-05-10T02:33:50Z 1620
2018-05-10T02:34:00Z 1735.4
2018-05-10T02:34:10Z 1586.9
2018-05-10T02:34:20Z 1822
2018-05-10T02:34:30Z 1817.6
2018-05-10T02:34:40Z 1778.8
2018-05-10T02:34:50Z 1174.1

> select count(event) from fencealltaxi01 where time > now() -1h
name: fencealltaxi01
time                           count
----                           -----
2018-05-10T01:39:29.715227558Z 3402554
~~~
2 .The query script that caused the timeout 
~~~
select count(last)
  from (select last("event"), ids, "ext.attr.car_stat"
          from "fencealltaxi01"
         where "ext.attr.nearbymeter" = '100'
         group by "ext.id")
 where time > now() - 30s
 group by ids, "ext.attr.car_stat"
~~~

**Comment by dgnorton** [comment]
@vicochan even at 6 fields, that's about 28K values per second, which the hardware you have should handle. Have you tried running with the default config values for `cache-max-memory-size` and `cache-snapshot-memory-size`?

**Comment by vicochan** [comment]
Yes, I used to running with the default configuration value, but the performance was slow and I observed that there was data loss, so I increased the values of these two cache-max-memory-size and cache-snapshot-memory-size.After testing and verifying, the parameters affecting the speed of storage are not the above two parameters, but batch-size. When I adjust it to the default value equal to 5000, the system is not blocked when it is put into storage.

**Comment by vicochan** [comment]
I would  to know that the more value of  `cache-max-memory-size ,` the less time Write TSM files frequently, and the longer the data is stored in memory. The system has enough time to write data to the database without flushing data at the next refresh , is this? 
and other , Is this also  the value of  `batch-size`  ? What is its maximum and minimum value?

**Comment by dgnorton** [comment]
@vicochan yes, the larger the value of  `cache-max-memory-size`, the longer data is stored in memory before flushing. A `batch-size` setting of 5000 should be okay for the volume of writes in this case. I don't know that there are minimums and maximums for batch size but 5K and 10K are common. You could use lower values in environments with lower values / second being written. The reason for batching writes is for performance.

**Comment by vicochan** [comment]
question No.2: After a few days, querying through the http API interface becomes very slow and there will be a timeout.
The query script is
~~~
select count(last)
  from (select last("event"), ids, "ext.attr.car_stat"
          from "fencealltaxi01"
         where "ext.attr.nearbymeter" = '100'
         group by "ext.id")
 where time > now() - 30s
 group by ids, "ext.attr.car_stat"
~~~~
![image](https://user-images.githubusercontent.com/20240490/40219506-3d86bd82-5aa8-11e8-88a5-18ac885cc88a.png)

![image](https://user-images.githubusercontent.com/20240490/40219711-261f1116-5aa9-11e8-96d7-ed2259d955de.png)

**Comment by CAFxX** [comment]
> question No.1: When I use udp to write data, some data is lost.I'm not sure whether the influx cache is flushed due to lost data.

UDP has no delivery guarantees (i.e. data can be lost). This is by design and has nothing to do with InfluxDB. If you want to make sure your data doesn't get lost use a protocol with delivery guarantees (e.g. http).

**Comment by natejgardner** [comment]
Any luck optimizing here? I'm getting similarly poor performance using LAST() as the number of records in the database increases.
