### ISSUE TITLE
graphite format inputs are written into _internal 

### ISSUE THREAD

**Issue by prasadbhagwat93** [influxdata/influxdb#9820]
### Directions
_GitHub Issues are reserved for actionable bug reports and feature requests._
_General questions should be sent to the [InfluxDB Community Site](https://community.influxdata.com)._

_Before opening an issue, search for similar bug reports or feature requests on GitHub Issues._
_If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
_Erase the other section and everything on and above this line._

### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
DB Version: 1.5.2
OS: Linux
__Steps to reproduce:__

1. [First Step]
Added graphite as datasource and config is below

[[graphite]]
  enabled = true
  bind-address = ":2003"
  protocol = "tcp"
  database = "graphite-test"
  templates = [
    "measurement.host.interface.field"
 ]

2. [Second Step]
send data to influx like below
echo "example.foo.bar.gama 3 `date +%s`"|nc localhost 2003

3. [and so on...]
When I switch to chronograf, a database called "graphite-test" gets created(as expected), but actual data like measurements are shown in _internal database.and I do not see field values too.

__Expected behavior:__ [What you expected to happen]
Data written into write database
__Actual behavior:__ [What actually happened]
Writing into _internal database
__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by dgnorton** [comment]
@prasadbhagwat93 are you sure it's the same data sent to port `2003` showing up in `_internal` or could it be system data that looks similar?
