### ISSUE TITLE
Millions of writes while back filling DB: Writes stop being ingested 

### ISSUE THREAD

**Issue by toomanycats** [influxdata/influxdb#9825]
### Bug report

1. InfluxDB shell version: 1.5.0 
2. CentOS 7

Using a Python 3 program I've written, I'm creating ~300 million entries to back fill a test Database
to check the feasibility of using InfluxDB for a scientific application in a research facility.

I'm reading custom compressed files iteratively and pushing every 10k rows, using the Pandas interfac e and let the program run over night.

I monitor the write by issuing: `select count(X) from Measurement;`

At some point, the count does not continue to climb and there's no errors being thrown in `influx` or in the Python program. My back fill program is still running and using resources as seen in `top`.
I am using the process pool feature of Python to run my back fill program on 5 cores, each instance of the program working on unique data.

Looking at the disk usage with this query:
`select sum(diskBytes) / 1024 / 1024 /1024 from _internal."monitor"."shard" where time > now() - 10s
name: shard`

`                        
time: 2018-05-10T18:18:53.437099466Z 
sum: 13.290545747615397
`

The 13 GB is well within my storage capacity, and I do see that number grow slowly as the ingestion continues.

I restart the back fill program where it left off and the count increases as I would expect.
Also, the disk usage grows slightly as expected.

**Comment by docmerlin** [comment]
Are you just streaming the rows in or chunking them?

**Comment by dgnorton** [comment]
@toomanycats when the `select count` query stops showing progress, are you still seeing `POST`s to `/write` in the influxdb log?

**Comment by toomanycats** [comment]
@dgnorton 
I'll re-nable DEBUG  level and check. Might be a while since the behavior doesn't occur in a convenient time.
