### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by vtoupet** [influxdata/influxdb#9837]
We are experiencing sporadic memory leak issues on our server leading to 'out of memory' crash. 

Environment:
 - Amazon Linux: 4.14.33-59.34.amzn2.x86_64 (instance type t2.medium with 4GB RAM)
 - influxDB package: influxdb-1.4.3.x86_64.rpm

Used RAM is usually around 1GB and sometimes, it rapidly increases to 100% (in no more than 30 sec). We could not locate a specific query that leads to this problem.

Attaching the debug files as requested:
[out_of_memory_stacktrace.log](https://github.com/influxdata/influxdb/files/2000831/out_of_memory_stacktrace.log)
[vars.txt](https://github.com/influxdata/influxdb/files/2000832/vars.txt)
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/2000830/profiles.tar.gz)
[iostat.txt](https://github.com/influxdata/influxdb/files/2000827/iostat.txt)

**Comment by timhallinflux** [comment]
Suggest grabbing 1.5.2 and seeing if this issue was addressed already.
