### ISSUE TITLE
time returned in queries using math is corrupt

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#9840]
Influxdb version: 1.5.2

Three queries:

1)
```
SELECT MIN(field) FROM table WHERE (host = 'localhost' AND instance = 'fred') AND time > now() - 3d GROUP BY host
2)
SELECT MAX(field) FROM table WHERE (host = 'localhost' AND instance = 'fred') AND time > now() - 3d GROUP BY host
3)
SELECT MAX(field) - MIN(field) FROM table WHERE (host = 'localhost' AND instance = 'fred') AND time > now() - 3d GROUP BY host
```

Time reported by query 1: `1526081280000000000`
Time reported by query 2: `1526340360000000000`
Time reported by query 3: `1526081184863897245`

I cannot comprehend where the time for query 3 comes from. It is not "now".

For reference:
4)
```
SELECT FIRST(field) FROM table WHERE (host = localhost' AND instance = 'fred') AND time > now() - 3d GROUP BY host
```
produces this time stamp: `1526081580000000000`

All of the values for "time" in "table" are modulo 60.

Ok, so there was some "lag" time in building this issue but this is reproducible - doing this:
```
SELECT MAX(field) - MIN(field) ...
```
always produces a time that is before the first entry and is "random".

**Comment by dgnorton** [comment]
@yellowpattern I believe the timestamp is the first interval within the time range specified in the `WHERE` clause. In the example given above in the issue, `1526081184863897245` is some time Friday, which I'm guessing was `3d` before the query was run (`time > now() - 3d`).

**Comment by yellowpattern** [comment]
Yes, it is "some time Friday" but the "some time" part is a rubbish value.

Here's a good example of the problem:

> select max(rx) - min(rx) from interface where host = 'localhost' and time > now() - 1d;
name: interface
time                max_min
----                -------
1526347397942320883 52187745805
> select last(rx) from interface where host = localhost' and time > now() - 1d;
name: interface
time                last
----                ----
1526433791549252531 0
> select first(rx) from interface where host = 'localhost' and time > now() - 1d;
name: interface
time                first
----                -----
1526347401549220126 41171266786

time(max-min) - time(first)
1526347397942320883-1526347401549220126
-3606899243
This means that the time in the "max() - min()" line is before that for "first()". The above three queries where cut-pasted at the same time.

The time for max() - min() should be the time of the max() value.

**Comment by dgnorton** [comment]
Converting those timestamps to human times...

| query | time |
| --- | --- |
| `max(rx) - min(rx)` | `GMT: Tuesday, May 15, 2018 1:23:17.942 AM` |
| `first(rx)` | `GMT: Tuesday, May 15, 2018 1:23:21.549 AM` |

Looks like those queries were run in the `influx` CLI about 3.5 seconds apart. The timestamp returned by the `max(rx) - min(rx)` query appears to be the first time in the range of `time > now() - 1d`. Try replacing the relative `now() - 1d` with the same fixed time for both queries.

**Comment by yellowpattern** [comment]
> select max(rx) - min(rx) from interface where host = 'localhost' and time > '2018-05-15 00:00:00'; select last(rx) from interface where host = 'localhost' and time > '2018-05-15 00:00:00'; select first(rx) from interface where host = 'localhost' and time > '2018-05-15 00:00:00'
name: interface
time                max_min
----                -------
1526342400000000001 52511478306

name: interface
time                last
----                ----
1526436361549414326 0

name: interface
time                first
----                -----
1526342401549205023 40536544449

max_min - first:
1526342400000000001-1526342401549205023
-1549205022

Try this for yourself.

**Comment by dgnorton** [comment]
The timestamp returned by `max(rx) - min(rx)` is `2018-05-15 00:00:00`, which is the start of the query's time range. I think that is the correct behavior.  /cc @jsternberg ?

**Comment by dgnorton** [comment]
@yellowpattern  on a side note (and you may already know this), running the following command in the `influx` CLI will format the result timestamps in human readable form...
```
> precision rfc3339
```

**Comment by yellowpattern** [comment]
Right, well if you want to argue that the behaviour of influxdb is correct then let me tell you that its behaviour is utterly useless in this regard.

This is just a simple example - the original example is from a table where all of the 'time" values in collectd are multiples of 60 seconds. The value returned by max-min is completely f*****d and utterly useless as it does not represent any actual value in the respective table.

**Comment by dgnorton** [comment]
@yellowpattern The query is asking for a difference of a field value between two points in time and the result's timestamp is for the first of those two points in time...not the timestamp of one of the actual values between those two points in time. I believe that's the same behavior in the original example as well. I've CC'ed one of the devs that knows that part of the code well.

Can you describe the problem you're trying to solve? Maybe there's another way to get the data you need.

**Comment by jsternberg** [comment]
The current behavior for influxql is correct and will not be changed so I'm going to close this issue. Here is the relevant documentation describing the behavior: http://docs.influxdata.com/influxdb/v1.5/query_language/functions/#selector-functions

The version 2 of the query language currently codenamed ifql is still in production and we can change things about how it works. This is one of the things we are changing. ifql will default to using the end time instead of the start time for the timestamp in these situations and there are options to customize the timestamp. If you have any ideas or opinions about how timestamps should work that differ from those ideas, you can open an issue in the ifql repository.

If you do decide to open an issue there, please describe exactly what you want, the output you would expect, and why that output is useful for you so we can ensure that ifql meets the needs of as large an audience as possible. If you need help with how to use influxdb, you can visit our [community forum](https://community.influxdata.com).

**Comment by yellowpattern** [comment]
For design work for the future of ifql, please consider https://github.com/influxdata/influxdb/issues/9859
