### ISSUE TITLE
TOP() should have option to return sorted results

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/influxdb#9843]
### Bug report

__System info:__ InfluxDB v1.5.2

__Steps to reproduce:__

1. Insert a few points
2. Run a raw query using the `TOP()` function
3. Note that the results are ordered by time and not the field selected by `TOP()`.

__Expected behavior:__ `TOP()` pulls the greatest field values. In that context, most people expect the results will be sorted by value, not timestamp.

__Actual behavior:__ `TOP()` returns the greatest field values, but the results are ordered by timestamp. Almost all use of this function requires clients to sort the data themselves.

__Additional info:__ Since the existing behavior may be relied upon, I propose that an optional argument be added to `TOP()` to indicate whether results should be sorted, e.g. `TOP("f", 3, true)`; new function signature `TOP( <field_key>[,<tag_key(s)>],<N>[,<sorted>] )[,<tag_key(s)>|<field_key(s)>]`

**Comment by nathanielc** [comment]
Added difficulty/medium to implement new `sorted` variants of the top/bottom. Adding these to the transpiler will be straightforward and Flux can already perform sorted top and bottom queries.
