### ISSUE TITLE
time returned from queries using delta to now() is useless for merging

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#9851]
Influxdb version: 1.5.2
Grafana version: 5.1.2

Running 4 queries like this into grafana to build a table:
SELECT MAX("rowcount") - MIN("rowcount") AS col1 FROM "db" WHERE ("host" =~ /$Host/ AND "instance" =~ /app/ AND "type" = 'history' AND "type_instance" = 'rows') AND $timeFilter GROUP BY host
SELECT MAX("total") - MIN("total") AS col2 FROM "app" WHERE ("host" =~ /$Host/ AND "instance" =~ /app/ AND "type" = 'app_data' AND "type_instance" = 'app_type') AND $timeFilter GROUP BY host
SELECT max("value") - min("value") AS col3 FROM "mysql" WHERE ("host" =~ /^$Host$/ AND "instance" = 'mysql' AND "type" = 'mysql_commands' AND "type_instance" = 'insert') AND $timeFilter GROUP BY host
SELECT max("rx") - min("rx")  AS bytes FROM "mysql" WHERE ("host" =~ /^$Host$/ AND "instance" = 'mysql' AND "type" = 'mysql_octets') AND $timeFilter GROUP BY host

produces results like this:

1526229137797 | hostname | - | - | - | 1.03 TiB
1526229137786 |hostname | - | - | 3085331 | -
1526229137784 | hostname | - | 3064854 | - | -
1526229137782 | hostname | 3064794 | -

In version 5.1.2 of grafana, it will merge multiple queries into a single output row if the timestamps match. Because there is a small variation in the time at which influxb executes the "now() - 3d" (which is the value of $timeFilter), each query has a slightly different timestamp.

If I change the "max - min" to be last, then the output comes out like this:

1526488686590 | hostname | - | - | - | 7.97 TiB
1526488686589 | hostname | - | - | 23963530 | -
1526488680000 | hostname | 23802480 | 23802898 | - | -

The goal is to get a single row in a grafana table to show up like this:

1526488680000 | hostname | 23802480 | 23802898 | 23802898 | 7.97 TiB

rows 1 & 2 I need to work on fixing the timestamp but row 3 is more typical of the data I generate so that aligning samples is easier for analysis. In fact for the most part, the sub-second time accuracy is of no importance to me at all.

At the moment I'm more or less totally screwed in aligning rows 1 & 2 (from collectd plugins) but it shouldn't be too hard to fix that problem.

Note that time supplied to influxdb via collectd is no finer grained than a second, so there is questionable benefit in providing output more finely grained than with which it is supplied.

If I could set the millisecond values to be "0" in the first example then it would actually work properly. See my previous comment about how useful they are.

**Comment by yellowpattern** [comment]
Note that in the above, while all of the "time as a number" values are different, the human readable time is the same.

**Comment by yellowpattern** [comment]
Actually, this problem may be more complex than it first appears and what's actually required is a "transaction group time" for a number of sequential SELECT statements to use as an agreed to value of "now()" (if we accept that the second hand might move between any two of the above four SELECT statements.)

In which case what's required is something like this:

SET_TRANSACTION_TIME();
SELECT a ... WHERE time > tnow() - 3d ...
SELECT b ... WHERE time > tnow() - 3d ...
SELECT c ... WHERE time > tnow() - 3d ...

If I were to assume a pathological case and where each query might take a substantial amount of time then although multiple queries are being received individually, the user expectation is that for each query the value of "now()" will be the same. Or at least that's what *I* expect. If I'm using now() for multiple panels in a page for grafana (or your UI of choice), then as a user I expect all queries to be related to the same point in time, even if they take 20 seconds to load.

**Comment by yellowpattern** [comment]
https://github.com/grafana/grafana/pull/10050

**Comment by yellowpattern** [comment]
Also: https://github.com/influxdata/influxdb/issues/9859

**Comment by davkal** [comment]
When using multiple queries, Grafana sends them in the same request, delimited by a `;`. I reckon `now()` gets evaluated when it's parsed. I would expect this time to be the same within the same query, but not across queries even if they arrive in the same request. If you need to rely on some form of bucketing, a date round function could be helpful, but I dont think influx has that.

I'm curious if you *need* the timestamp column to be displayed. If not, you can mark it as Type: Hidden in the column Styles of Grafana, then they wont be considered for row merges. If you still need to mention some time aspect, you can put it in the panel title as e.g., "Last 3h".

**Comment by yellowpattern** [comment]
I don't need the timestamp column to be displayed, but I do need all of the queries aligned in time because that is how the multi-query table alignment works. Rounding up/down to the nearest second might work but only in a very limited sense. For example, if my query to influxdb from grafana is like this:

SELECT x FROM y; -- this takes .5 seconds to complete
SELECT a FROM b; -- this takes 5 seconds to complete
SELECT c FROM d; -- this takes 5 seconds to complete
SELECT g FROM h; -- this takes 1 second to complete
SELECT m FROM n; -- this takes 0.5 seconds to complete

then there is very little in the way of alignment possible (in terms of time) of all queries.

Further to this, if all of the above are from collectd sources using the standard 10 second interval then "g,m" are not going to be from the same time bucket as "x,a,c". As long as selection functions aren't used to give the pretense of all being from the same point in time, it isn't really harmful as some series that are reported will just begin/end differently.

When all the queries take less than a second to complete, life is good, but some queries can take longer.

The "now()" function in iql is very useful for standalone queries but as part of a group, it is perhaps less useful than at first sight.
