### ISSUE TITLE
influx_inspect dumptsi requires -series-file

### ISSUE THREAD

**Issue by hahnjo** [influxdata/influxdb#9862]
### Bug report

__System info:__
InfluxDB 1.5.2

__Steps to reproduce:__

```
$ influx_inspect dumptsi --help
Dumps low-level details about tsi1 files.

Usage: influx_inspect dumptsi [flags] path...

    -series
            Dump raw series data
    -measurements
            Dump raw measurement data
    -tag-keys
            Dump raw tag keys
    -tag-values
            Dump raw tag values
    -tag-value-series
            Dump raw series for each tag value
    -measurement-filter REGEXP
            Filters data by measurement regular expression
    -tag-key-filter REGEXP
            Filters data by tag key regular expression
    -tag-value-filter REGEXP
            Filters data by tag value regular expression

If no flags are specified then summary stats are provided for each file.
```

__Expected behavior:__
Find documentation about `-series-file` which is required since commit 288c5217e81d2df7edaf050f554c300eba71bd6b.

__Actual behavior:__
When calling `influx_inspect dumptsi` as documented, it just prints `dumptsi: series file path required`.

**Comment by timhallinflux** [comment]
Looks like the -series-file path parameter does not appear in the CLI help output.

Also logging the documentation issue to describe the parameter.  https://github.com/influxdata/docs.influxdata.com/issues/1622

**Comment by benbjohnson** [comment]
Added `-series-file` to CLI help in https://github.com/influxdata/influxdb/pull/9884.
