### ISSUE TITLE
After reaching max-concurrent-queries limit, Influx is not executing the queries even after it has been left for 24 hour without executing any query

### ISSUE THREAD

**Issue by Vish17agr** [influxdata/influxdb#9865]
I have got below issue when i was ingesting data and checking it from the CLI and the same database has been used by grafana to show the graph.

show databases
ERR: max-concurrent-queries limit exceeded(10, 10)

I can't restart the influx, So, i left my work and then checked next day.
I saw influx CLI, is still throwing same error message.

Is the queries running in influx not been killed even after 24 hours even I have stopped all my ingestion's in the influx.

Is there any way to check which all the queries are running in influx and kill them.

**Comment by timhallinflux** [comment]
There sure is.  Have a look at this: https://docs.influxdata.com/influxdb/v1.5/troubleshooting/query_management/

**Comment by Vish17agr** [comment]
Thanks @timhallinflux

**Comment by DerMika** [comment]
I just had this situation, but I'm not able to even execute `SHOW QUERIES` because that query throws the same error. How did you fix this?
