### ISSUE TITLE
How to change the time zone？

### ISSUE THREAD

**Issue by afreetgo** [influxdata/influxdb#9873]
I want the "time" field to be saved as the local time zone. Options that are not configured in the configuration file. Please tell me how to do it？

**Comment by dgnorton** [comment]
@afreetgo InfluxDB only stores timestamps in UTC. Here's the [relevant area in the docs](https://docs.influxdata.com/influxdb/v1.5/concepts/glossary/#timestamp). Query results [can be returned in a particular timezone](https://docs.influxdata.com/influxdb/v1.5/query_language/data_exploration/#the-time-zone-clause). Please post usage questions in the [community forum](https://community.influxdata.com/) in the future.
