### ISSUE TITLE
Enhancement Request: Output TCP address rather than Node ID

### ISSUE THREAD

**Issue by ono760** [influxdata/influxdb#9875]
Instead of  `node 3`, which is the `id`,  InfluxDB should output the `TCP Address` (hostname).  By supplying the node id only, it requires the administrator to either keep a handy reference of the mapping between node ids and hosts...or execute another command...
```
Data Nodes

==========

ID TCP Address Version

3 ent-node-01:8088 1.3.9-c1.3.9
4 ent-node-02:8088 1.3.9-c1.3.9
```
`ERR: partial success, node 3 may be down (rpc error: failed to start stream: connection write timeout)`

**Comment by timhallinflux** [comment]
Moved to the enterprise repo.
