### ISSUE TITLE
SELECT INTO cannot handle fields with same name and different data types

### ISSUE THREAD

**Issue by hahnjo** [influxdata/influxdb#9887]
### Bug report

__System info:__
Reproduced with latest `master`

__Steps to reproduce:__

```
> CREATE DATABASE test
> CREATE DATABASE test_bak
> USE test_bak
> INSERT foo field=1i
> INSERT bar field=1
> SELECT * INTO test..:MEASUREMENT FROM /.*/ GROUP BY *
```

__Expected behavior:__
```
> SHOW FIELD KEYS
name: bar
fieldKey fieldType
-------- ---------
field    float

name: foo
fieldKey fieldType
-------- ---------
field    integer
> USE test
Using database test
> SHOW FIELD KEYS
name: bar
fieldKey fieldType
-------- ---------
field    float

name: foo
fieldKey fieldType
-------- ---------
field    integer
```

__Actual behavior:__

```
> USE test
Using database test
> SHOW FIELD KEYS
name: bar
fieldKey fieldType
-------- ---------
field    float

name: foo
fieldKey fieldType
-------- ---------
field    float
```
(Note that `foo`'s `field` has type `float`!)

Sometime this seems to be caught by `SELECT INTO` which complains about a type conflict, but I can't make this error out reliably?!? Maybe I've only been seeing this error after executing the `SELECT INTO` a second time...

__Additional info:__
This is the suggested way to restore incremental backups, see https://github.com/influxdata/influxdb/issues/9593#issuecomment-380994623.

**Comment by timhallinflux** [comment]
Use explicit casting to resolve: https://docs.influxdata.com/influxdb/v1.0/query_language/data_exploration/#data-types-and-cast-operations-in-queries

**Comment by hahnjo** [comment]
Huh, `SELECT INTO` creates these measurements with wrong types. I don't see why I need casts when the query is explicit about copying data 1:1...

**Comment by Ilyasbel** [comment]
Hi, I think you have the same problem as I have with the RegEx `/.*/` not with `SELECT INTO`.
You can find more information in these issues: #10022, #10006, and #8858 
Sadly, they are closed as "working as intended", but I think this behaviour generates many problems (like this one, with CQs, and with Kapacitor batch tasks) and I'm not sure why this is intentional.

**Comment by hahnjo** [comment]
Ok, I see. Thanks for the links!

**Comment by basking-in-the-sun2000** [comment]
Had a similar thing happened. However, it was a problem with functions not insuring an integer was returned. 

Tried all options; round, ceil, and floor with the same result. The mean gives back a float when the input are integers.

Select round(MEAN("M_A-P")) AS "M_A-P" INTO logger_ds.autogen.Huawei FROM logger.autogen.Huawei GROUP BY time(5m)

This would only happen once so often, but it is consistent (i think at least happened on every run). The failure is about once every 3000 to 5000 records. 

Strangely it doesn't seem to happen if I output to the terminal (without the into clause). Other similar cases worked, but only fails when the input are integers or the field name is in quotes. Tried it without the quotes, but the call failed. 

Worked around the issue making the output float in all cases ( MEAN("M_A-P") + 0.00001 AS "M_A-P" ).
