### ISSUE TITLE
[Feature Request] function to calculate rate for gauge metrics

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#9890]
With counter metrics, the "derivative" and related transformation functions do an excellent job of taking (say) a set of network interface counters and producing a rate.

e.g.
select derivative("rx",1s) from interface where host = 'localhost' and instance = 'lo' and type = 'if_packets'
this works because "rx" is a counter and for (rx(t=t2) - rx(t=t1))/(t2-t1), the data rate on the network is easily displayed.

however if I get a "rx" value that reflects the amount of data that has passed my last system in the previous 60 seconds then there is no longer a function I can use to get a per-second derivative. Whilst it may be tempting to use "math(/60)", that doesn't work if you then do "GROUP BY time(..)" and end up with more than one value in a bucket.

It also does not make sense to try and "fix" any of the existing difference/derivative functions to behave differently for gauge counters - they simply need a function that makes it easy to transform a gauge that represents a total for a period into a different total for a different period.
e.g my gauge says "100" for "10 seconds", what should it be for "1 second" or if I use "group by time()" to merge multiple gauges into a single bucket, how can I then get the combined average as a rate?

**Comment by cout** [comment]
Related: https://github.com/influxdata/influxdb/issues/3976
