### ISSUE TITLE
Tag on measurement renamed to <tag_name>_1 mysteriously

### ISSUE THREAD

**Issue by sorrison** [influxdata/influxdb#9891]
### Bug report

__System info:__ Influx 1.5.2 running on Ubuntu 16.04 via deb package install

__Steps to reproduce:__

Currently unknown how to reproduce

__Expected behavior:__ 

Tags not to be renamed

__Actual behavior:__ 

I have a measurement that has data going into it via a continuous query, this has been working fine for over a year. A couple of days ago I could no longer query data using the one tag that is on the data.

The  CQ is:

`CREATE CONTINUOUS QUERY samples_stats_max_86400 ON gnocchi BEGIN SELECT max(value) AS value INTO gnocchi.rp_3153600000.samples_stats_max_86400 FROM gnocchi.rp_stats_incoming.samples_stats GROUP BY time(1d), metric_id END`

Sample data in rp_stats_incoming.samples_stats:

```
select * from rp_stats_incoming.samples_stats limit 5;
name: samples_stats
time                 metric_id                            value
----                 ---------                            -----
2018-05-21T22:00:05Z 005da82f-6432-4a27-b5ba-26ace2134d36 32
2018-05-21T22:00:05Z 086b6f02-3e4c-44a7-a98f-8e6a867ce12d 2
2018-05-21T22:00:05Z 0b93301d-4310-4110-96d2-236e81ebf7bb 14
2018-05-21T22:00:05Z 14def77d-4533-448a-b5f1-a1821f2f8e42 167
2018-05-21T22:00:05Z 15b40240-a63c-4222-a2b6-8d41fbdb2706 346
```

However the data in the measurement that the CQ is putting data into is:

```
select * from rp_3153600000.samples_stats_mean_86400 limit 5;
name: samples_stats_mean_86400
time                 metric_id metric_id_1                          value
----                 --------- -----------                          -----
2017-01-11T00:00:00Z           0017e418-e6d7-44ba-9434-d4b6bb7bd43c 1
2017-01-11T00:00:00Z           fff3011c-f95e-4b9f-9f44-e0d53b5e649b 1
2017-01-11T00:00:00Z           0033f98c-22ad-4b7b-9c12-2e4b562ff8cd 1
2017-01-11T00:00:00Z           00602eb3-4bcc-4a0d-968a-e8b75f172c2c 4096
2017-01-11T00:00:00Z           00b4dcd3-9bbf-4e87-adf2-c7bdbd9965e3 49152
```

As you can see it's renamed the tag from `metric_id` to `metric_id_1`

The data was all under `metric_id` and existing data has somehow moved to have the tag name `metric_id_1`

All new data seems to be going in under metric_id_1 tag.

There are less than 1% of data points that do still have the `metric_id` tag 
```select * from rp_3153600000.samples_stats_mean_86400 where metric_id =~ /.*/;
name: samples_stats_mean_86400
time                 metric_id                            metric_id_1 value
----                 ---------                            ----------- -----
2018-05-11T00:00:00Z 39b00c4d-3d5e-44f9-b436-60177377e571             98336054346200
2018-05-12T00:00:00Z 39b00c4d-3d5e-44f9-b436-60177377e571             98357939241400
2018-05-13T00:00:00Z 39b00c4d-3d5e-44f9-b436-60177377e571             98344015528400
2018-05-14T00:00:00Z 39b00c4d-3d5e-44f9-b436-60177377e571             98531959865800
```
__Additional info:__ 

Using tsm and all defaults in the config except 
```
max-series-per-database = 0                                                                                                                                                                    
max-values-per-tag = 0
```

**Comment by jsternberg** [comment]
You added a field with the same name as a tag. The system treats fields and tags as different so when you do `SELECT *`, it renames one of the two columns to avoid a name conflict. It just so happens the tag ends up being second so it's the one that is renamed. Its real name isn't `metric_id_1` so filtering by that doesn't work, although I can see how that's confusing. I think you can convince the query engine to use the correct `metric_id` by explicitly specifying that it's a tag like this:

```
WHERE metric_id::tag = '...'
```

This is only required for fields and the where clause. It's not needed for group by which only supports tags so it always chooses the tag.

It was most likely a mistake for you to write `metric_id` as a field somewhere in the system. Unfortunately, this is the issue tracker so we can't help you with that. Fortunately, we have a [community website](https://community.influxdata.com) designed for helping users with these kinds of problems!

I'm going to close this issue. If you create a thread on that site and link back here to the explanation, someone can probably help you clear out the bad data from the system so it returns back to normal.

**Comment by sorrison** [comment]
Ah ok, thanks for your explanation. But this means that somehow all my points somehow changed from a tag of metric_id to a field of metric_id. These data points go back over a year and all of a sudden they turned to fields. Plus the CQ is the only thing writing into this measurement and it seemed to continue working just putting them in as fields. We also have a couple other CQ's reading from the same source measurement and writing to different measurements that didn't see this issue and I've checked the source measurement and the data all has metric_id as a tag.

I don't think this is expected behaviour so maybe this is a bug?

**Comment by jsternberg** [comment]
I'm not sure. My bet is that you have something in your system that wrote metric_id as a field somewhere. You can try doing:

```
SELECT metric_id::field FROM ...
```

Then you can see how many points were written in that way and when it started. If it started happening after you upgraded to a newer version of InfluxDB, we can reopen this and begin to investigate. My current thought is whatever piece of code writes the metrics changed and is now writing the metrics incorrectly.

It is probably not that all of your points changed. It could be as simple as one point changing the schema which the above query will help you find.

**Comment by sorrison** [comment]
But a data point that had a tag couldn't change to have that as a field? As that is what happened. The change didn't happen as part of an upgrade. We were running 1.3 and when I was debugging this issue and failing I upgraded to 1.5.2 to see if that would fix it. The only thing writing data was the CQ

All points in the measurement changed from having a tag to a field around 18k, except 4 points which I'm not sure why.

I've fixed this up by dumping the data and deleting the measurement and CQ and recreating but I'm pretty sure there is an issue here. Maybe due to our large number of tags etc. (Going to move to tsi1 soon)

**Comment by tagyoureit** [comment]
Hi, 

I've been very frustrated with this same error as well.  I posted an article on the [community forums](https://github.com/influxdata/influxdb/issues?utf8=%E2%9C%93&q=tags+written+as+fields) and I'm using Python for entry, but I don't think that makes a difference.  

In my example, the tags are being converted to fields upon the very first write.  

I originally thought this was happening when dropping/recreating the measurement (maybe something was being cached somehow), but despite dropping the measurement/restarting Influx, I am still able to replicate the issue consistently.

tag

**Comment by S474N** [comment]
Have working solution!

Copy all data to a temporary measurement
`SELECT * INTO metrics_clean FROM metrics`

Drop existing dirty measurement
`DROP measurement metrics`

Copy temporary measurement to existing measurement
`SELECT * INTO metrics FROM metrics_clean`

Drop temporary measurement
`DROP measurement metrics_clean`

**Comment by tagyoureit** [comment]
> @[tagyoureit](https://github.com/tagyoureit) Can you send correct URL to forum? Have same problem. Thank you.

I don't know where that original post went.
