### ISSUE TITLE
fill(<value>) can contain only one value

### ISSUE THREAD

**Issue by Kortenbach** [influxdata/influxdb#9894]
Currently it seems that fill() can only provide one value for all of the missing samples.
example: fill(10) --> fills ALL missing values with "10".

Is there a way to provide separate fill values for each series in a query?
example: Select meas1, meas2 .... fill(1,2)
Would fill missing data from meas1 with "1" and missing data from meas2 with "2".

Being able to provide only one value for fill() seems oddly asymetric. Since I can provide multiple measurements in my select clause I would expect fill() to accept the same number of measurements.

**Comment by dgnorton** [comment]
@Kortenbach you're right that it's not current supported and, off the top of my head, I can't think of a workaround. I'll flag it as a feature request to be considered.
