### ISSUE TITLE
"DELETE FROM" should support deleting a field only

### ISSUE THREAD

**Issue by hpbieker** [influxdata/influxdb#9899]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

__Proposal:__ 
I would like to be able to delete all values for a given field in a given time period.

__Current behavior:__ 
You can do:
DELETE FROM "someMeasurement" WHERE (time >= 'XXX' AND time < 'YYY')
to delete all points for a measurement in a given time period, but you cannot restrict it to a specific field.

__Desired behavior:__ 
DELETE FROM "someMeasurement"."field" WHERE (time >= 'XXX' AND time < 'YYY')
to delete all values for field "field" for "someMeasurement" in the time period given.

(I do not know what the proper syntax would be, but I need the functionality.)

__Use case:__ 
I use InfluxDb to store calculations, and some times I need to recalculate. I update only one field at the time, so I need to delete the field in the given period before I write the data to ensure that no old values are kept in the database.

**Comment by hpbieker** [comment]
Any chance to get this supported?

**Comment by sandonet13** [comment]
Yes, we need this too, nothing so far ?
