### ISSUE TITLE
Allow specification of new timestamp for data written by a SELECT INTO clause

### ISSUE THREAD

**Issue by DanSoQt** [influxdata/influxdb#9900]
### Feature Request

__Proposal:__  Allow specification of a new timestamp for data written into a measurement using the SELECT INTO clause

__Current behavior:__ When SELECT returns results that have no timestamp, the oldest timestamp from the WHERE clause's date range is used when inserting data with an INTO clause.

__Desired behavior:__ Allow specification of a timestamp to be used for data written with the INTO clause. Suggested syntax: SELECT data INTO measurement WITH time=[datestring or now()]

__Use case:__ This can be useful for running continuous queries that collect moving averages and calculates percent changes over a given period. For example, take the query below. This calculates the percent difference between the min/max values for a period of the last 30 days. The query works, but the INTO places the timestamp for the calculated data at [today - 30days.] I would like place this type of query in a continuous query and run it daily to track our stats and catch degradations over a certain threshold. With the date at [today - 30 days] however, the data is offset to an unusable degree.

SELECT (max(moving_average) - min(moving_average)) / max(moving_average) AS percent_difference INTO bench_30d_change FROM bench_moving_averages WHERE time >=now()-30d GROUP BY benchmark,hardwareId,branch fill(none)

**Comment by eirirlar** [comment]
Stale bot is really helpful - just wait until it comes around and one does not have to do anything :)
Second this feature request btw.
