### ISSUE TITLE
Delete Tags alone from series

### ISSUE THREAD

**Issue by Pangaj** [influxdata/influxdb#9915]
My database measurement has reached a series of 1,00,000 records because of misplacement of tag instead of field, and causing 400 http response code.

Can I able to **delete the TAG** alone from a series

Or can I able to **change the tag value to field value**

I can bear to lose my tag keys alone and not the series. How to do it?

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.
