### ISSUE TITLE
Results have incomplete data records

### ISSUE THREAD

**Issue by shuiyue0626** [influxdata/influxdb#9941]
version:1.2.4
I query datas while inserting, then I find the records has null field(insert with data).

**Comment by sisyphsu** [comment]
meet the same issue.
my measurement has 10 columns, which all have different value. 
but occasionally, my program can only fetch 2 or 3 columns, others were all null

**Comment by e-dard** [comment]
@shuiyue0626 please update to the latest version — `1.5.3`. Version `1.2.4` is so far behind we can't practically support/triage issues for it.

Feel free to open another issue if you can reproduce with a more recent version.
