### ISSUE TITLE
show measurement and show tag keys from measurement --> Not working correctly

### ISSUE THREAD

**Issue by Pangaj** [influxdata/influxdb#9945]
I created new measurement with name "**new_msr**", by inserting the below query in CLI in existing DB - **database_phone**
--> insert new_msr,device=android,version=8,model=samsung score=200

1. After that, I used **"show measurements", it DOES NOT showed my new measurement**
2. I used SELECT clause, --> SELECT * from new_msr, It listed the above record correctly
3. I used --> SHOW FIELD KEYS from new_msr, --> showed "score=200", correctly
4. But, I used --> **SHOW TAG KEYS from new_msr --> Does not showed anything**
5. I used EXPLAIN ANALYZE SELECT * from new_msr, showed "device, version, and model as tags", and "score as field"

I don't know, 
#### If the keys are NOT FIELD, then it must belong to TAG. Why it is not showing?

**Comment by e-dard** [comment]
@Pangaj

Can you provide more detail please, as outlined in the Issue template?

**Comment by russorat** [comment]
closing due to lack of response.
