### ISSUE TITLE
Show measurement is not working properly

### ISSUE THREAD

**Issue by Pangaj** [influxdata/influxdb#9948]
I have 2 influx machines, each running on separate linux servers
I have **created new measurement** named "**new_msr**" in an **existing db** by inserting an item,
--> insert new_msr,tag1=tagone,tag2=tagTwo field1='fieldOne'

**Show measurement** --> shows **new_msr** in one Linux server and **not in another**

**Note : There is no change in influxdb.conf in both influx machines**

Why I can't get newly created measurement in my influx?? 😕 😕 😕

**Comment by e-dard** [comment]
Can you provide more detail please, as outlined in the Issue template?
