### ISSUE TITLE
the tag key NAME can not be used in where clause 

### ISSUE THREAD

**Issue by yhang1989** [influxdata/influxdb#9955]
influxdb : 1.2
os version : centos 6.1 x86_64
select * from cpu_load_short where name = 'yh' 
Server returned error: error parsing query: found NAME, expected identifier, string, number, bool at line 1, char 36

select * from cpu_load_short where name1 = 'yh'
successful 
and other columes can  also use behind where , so I need to aviod  use name for the colume name ?

**Comment by e-dard** [comment]
Use `"name"`
