### ISSUE TITLE
Query "Show tag keys" extremely slow in large databases

### ISSUE THREAD

**Issue by waxitoh** [influxdata/influxdb#9956]
### Bug report

**System info:** 

InfluxDB shell version: 1.5.3 on debian Stretch (Debian 4.9.65 x86_64 GNU/Linux)

__Steps to reproduce:__

1. Run "show tag keys" on a relatively large database (16 tags and cardinality estimation: 4769361)

__Expected behavior:__ 

Faster results as was the case in version 1.4.3

__Actual behavior:__ 

Very slow on "huge" databases and this affects adhoc filters greatly. 

__Additional info:__

[someone else had the same issue](https://github.com/influxdata/influxdb/issues/8825) but it was closed. 

I've just moved from Influx 1.4.3 to Influx 1.5.3 and i've noticed the same thing: Query performance has hugely improved but "show tag keys" has become quite slow. 

I've also set index the version to "tsi1" (from inmem) and issued the index_inspect command to convert the index. 

thx

**Comment by dgnorton** [comment]
Local repro of the issue...

```
inch -m 15 -t 16,100,140 -p 10 -c 10 -b 10000 -start-time 1975-06-12T15:16:20.359926Z -time "7200h" -shard-duration 3d
```

inmem:
```
real    0m0.463s
user    0m0.010s
sys     0m0.005s
```

tsi1:
```
real    0m16.618s
user    0m0.005s
sys     0m0.000s
```
```
Measurements: 15
Tag cardinalities: [16 100 140]
Points per series: 10
Total series: 3360000
Total points: 33600000
Total fields per point: 1
Batch Size: 10000
Database: stress (Shard duration: 3d)
```

CPU profile of the query path:

![image](https://user-images.githubusercontent.com/209347/41315212-d6f0a2c2-6e5c-11e8-8ac6-91b023adf30b.png)
