### ISSUE TITLE
restore failed whehn shard number is multiple of 10

### ISSUE THREAD

**Issue by yylt** [influxdata/influxdb#9962]
i backup some date from influxdb service , and when i restore these to influxdb backup dir , it successed , but when start influxdb service , data is disappeared !

influxdb version 1.5.3Rc2 ; commit ee54b2

thest are what i do 
~~~
influxd backup -host 127.0.0.1:18086 -database test -retention default -shard 10 backup
influxd restore -datedir /var/lib/influxdb/data -metadir /var/lib/influxdb/meta -database test bakcup/
influxd -config influx.conf
~~~

when execute "show shards" i found below , but data is none:
~~~
name: test
id database retention_policy shard_group start_time         end_time       owners
1  test          default               1                xxx                   xxx
~~~

https://github.com/influxdata/influxdb/blob/ee54b276692cf8eb966c82943f6af44672c659e3/cmd/influxd/restore/restore.go#L547-L560

may be it is should be use "strings.TrimLeft" ?

**Comment by StephenSorriaux** [comment]
Hi,

Just encountered the same problem now, every shards multiple of 10 are not restored or may be restored in the wrong shard (for instance, shard with id `790` in backup will become shard with id `79` in database).
