### ISSUE TITLE
Query results for time range greater than table data should return results

### ISSUE THREAD

**Issue by tagyoureit** [influxdata/influxdb#9999]
__System info:__ 
Influx 1.5.1 running in Docker Container on Synology NAS

__Steps to reproduce:__

1. Create table with Data
2. Query for data with time range before table exists

__Expected behavior:__ Data should be returned for whatever exists in the table

__Actual behavior:__ No data is being returned

__Additional info:__ 
I have a table with only 6 days worth of data in it.  

```
> select * from filter order by asc limit 2
name: filter
time                 adc  current_filter_change psi  pump1_rpm source source_1   type type_1  voltage
----                 ---  --------------------- ---  --------- ------ --------   ---- ------  -------
2018-06-15T05:48:01Z      0                                           python_app      change
2018-06-15T05:48:11Z 4810 0                     2.53 1400             python_app      reading 0.6
```

My earliest date is 6-15 5:48UTC and current 6-23 12:56pm UT as of this writing.  

Any query that is run for a date range after the table was created returns valid data.

```
> SELECT last("psi") FROM "filter" WHERE ("type" = 'reading') AND time >= now() - 3h GROUP BY time(1h)
name: filter
time                 last
----                 ----
2018-06-23T09:00:00Z 2.66
2018-06-23T10:00:00Z 2.65
2018-06-23T11:00:00Z 2.61
2018-06-23T12:00:00Z 2.76
```

```
> SELECT last("psi") FROM "filter" WHERE ("type" = 'reading') AND time >= now() - 3d GROUP BY time(1d)
name: filter
time                 last
----                 ----
2018-06-20T00:00:00Z 2.91
2018-06-21T00:00:00Z 10.83
2018-06-22T00:00:00Z 2.67
2018-06-23T00:00:00Z 2.7
```

Up to 5 days works...

```
> SELECT last("psi") FROM "filter" WHERE ("type" = 'reading') AND time >= now() - 5d GROUP BY time(1d)
name: filter
time                 last
----                 ----
2018-06-18T00:00:00Z 2.94
2018-06-19T00:00:00Z 3.12
2018-06-20T00:00:00Z 2.91
2018-06-21T00:00:00Z 10.83
2018-06-22T00:00:00Z 2.67
2018-06-23T00:00:00Z 2.59
```

However, any query that tries to query for now()-6d returns no values.

```
> SELECT last("psi") FROM "filter" WHERE ("type" = 'reading') AND time >= now() - 6d GROUP BY time(1d)
>
```
(I realized now()-6d should actually be after the table was created, so maybe my description isn't correct... but still don't know why I'm not getting data back.)

**Comment by russorat** [comment]
closing due to age. please upgrade to the latest version of influxdb and open a new issue if this persists.
